### ISSUE TITLE
一键搬空活动商店

### ISSUE THREAD

**Issue by koocey** [MaaAssistantArknights/MaaAssistantArknights#10008]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

希望能出新功能对活动商店/生息演算商店等进行识别，自动从左至右兑换所有项目

**Comment by status102** [comment]
Duplicate of #6096
