### ISSUE TITLE
萨卡兹肉鸽去伪存真进入印象重构点完退出后卡住

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#10000]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨卡兹肉鸽去伪存真进入印象重构点完退出后卡住
尝试关闭gpu加速问题依旧

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0
Core Version: v5.5.0

### 日志文件

23点55分左右
[gui(3).log](https://github.com/user-attachments/files/16444483/gui.3.log)
[asst(3).log](https://github.com/user-attachments/files/16444509/asst.3.log)

### 截图

![3`T71H7F@7GSV$4ED)8V2G8](https://github.com/user-attachments/assets/99a4f5c6-a72e-4133-86d0-246da4121bef)

### 还有别的吗？

mumu12模拟器

**Comment by Saratoga-Official** [comment]
等我把这个issue改成有意义的issue好了，成员能编辑，让你抢还发没意义的
