### ISSUE TITLE
开始萨卡兹自动肉鸽关机

### ISSUE THREAD

**Issue by sakurasaber2020** [MaaAssistantArknights/MaaAssistantArknights#10004]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

开始萨卡兹自动肉鸽关机，其他功能正常运行

### Version

![1](https://github.com/user-attachments/assets/012a1675-cb68-4399-94c7-3bab71b77317)
V5.5.0

### 日志文件

[asst.bak.log](https://github.com/user-attachments/files/16441420/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/16441421/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/16441422/gui.bak.log)
([gui.log](https://github.com/user-attachments/files/16441423/gui.log))
[asst.bak.log](https://github.com/user-attachments/files/16441476/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/16441479/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/16441480/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/16441482/gui.log)
问题在2024-07-31 18:00 ~2024-07-31 19:30 间发生，之前也多次发生

**Comment by zzyyyl** [comment]
电脑配置 & 模拟器配置 可以提供吗

**Comment by Rbqwow** [comment]
你说的关机指的是正常关机 还是突然断电黑屏

**Comment by sakurasaber2020** [comment]
> 电脑配置 & 模拟器配置 可以提供吗


处理器	Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz   2.60 GHz
机带 RAM	8.00 GB (7.87 GB 可用)
设备 ID	6B514947-687E-4052-BA86-4C9E9ABF2160
产品 ID	00342-33274-47793-AAOEM
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入
版本	Windows 10 家庭中文版
版本号	22H2
安装日期	‎2024/‎1/‎30
操作系统内部版本	19045.4651

显卡  GTX 960M

**Comment by Constrat** [comment]
Try another type of I.S. 
I have the exact same machine type as yours except with 32GB of RAM and I never had any issues of crashing. Just looking at it, I'm thinking it could be RAM related as 8GB in 2024 with a Win10 install might not be enough.
