### ISSUE TITLE
一直重复部署

### ISSUE THREAD

**Issue by Dionysussin** [MaaAssistantArknights/MaaAssistantArknights#1000]
（应该是识别错误吧）肉鸽关卡酒商运输队在高台已经没有部署位的情况下依旧会一直尝试部署
雷电模拟器

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8990244/asst.zip)
![image](https://user-images.githubusercontent.com/60726665/175900144-5bb749fe-215b-4bda-a218-2f369e07276a.png)

**Comment by Shawnsdaddy** [comment]
恭喜你，成为maa第1000个issue 的发起者。

**Comment by Dionysussin** [comment]
> 恭喜你，成为maa第1000个issue 的发起者。

还行

**Comment by Dionysussin** [comment]
补图
![image](https://user-images.githubusercontent.com/60726665/176116382-ae70033e-7a11-4f53-8763-618a31a04ff1.png)

**Comment by zzyyyl** [comment]
酒商运输队这张图已经有好多人反映相同的问题了，事实上在玛丽的b站演示视频上也能找到这个问题，~不知道为什么到现在都没人处理（~

**Comment by MistEO** [comment]
fixed
