### ISSUE TITLE
更新系统相关错误

### ISSUE THREAD

**Issue by inktree** [MaaAssistantArknights/MaaAssistantArknights#10018]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

不可取消的自动检查更新在取消勾选其他所有更新相关选项后依然会尝试自动更新，而且是更新到所谓的“最新版本”，5.51强制更新到5.50的天才操作是真的挺厉害的，希望能别再做这种东西了，平时经常更新时因为无法正常解压更新包覆盖文件导致闪退都不说了，希望能尽快修复强制“更新”到别的版本的问题

### Version

Core Version: v5.5.1-alpha.1.d084.g5f5eccda7

### 日志文件

[gui.log](https://github.com/user-attachments/files/16458599/gui.log)
[asst.log](https://github.com/user-attachments/files/16458601/asst.log)

### 截图

![image](https://github.com/user-attachments/assets/b28fdf8e-528d-4595-96b8-446b01805964)
![image](https://github.com/user-attachments/assets/5bd0c27b-8b68-439a-a842-15b88bf44b0c)
![ZY1)~F70T{ 9HEAL$0_3)PI](https://github.com/user-attachments/assets/8c4f6814-ef6d-4b77-b39f-78721a128dda)

**Comment by Agnes4m** [comment]
+1,从下午5点就试过，试过重下覆盖无效，插个眼

**Comment by Daydreamer114** [comment]
> 5.51强制更新到5.50的天才操作是真的挺厉害的，希望能别再做这种东西了

请注意你的语气，不喜欢可以不用
鉴于截图中你选择的是稳定版，最新稳定版就是5.5.0

> 无法正常解压更新包覆盖文件导致闪退

这个问题从来没有在我们的电脑上出现过，你不想说就请接受，而不是抱怨

**Comment by Daydreamer114** [comment]
> +1,从下午5点就试过，试过重下覆盖无效，插个眼

你也是从5.5.1更新到5.5.0？
如果是资源版本的话，现在服务器有问题，可以去用户群看手动覆盖的教程

**Comment by Daydreamer114** [comment]
@ABA2396 当时为啥要把自动检查更新锁上？解锁且取消勾选是不是能省一些服务器负担

**Comment by Rbqwow** [comment]
自动打包出了问题 导致内测版在打包的同时又被打成了另一个公测版的包
而实际上这个公测版不存在 所以会触发自动更新 下alpha的就好了 别下beta

根本问题只是因为MAA的服务器顶不住了 因为更新设计之初就没考虑过这么多的用户量
在更新系统重构结束之前只能先这样缓解

> 当时为啥要把自动检查更新锁上？解锁且取消勾选是不是能省一些服务器负担

因为即使锁定自动更新了也会有用旧稳定版来发 Issue 的 防不胜防
MAA 和企鹅物流服务器问都是最近几个月才彻底顶不住的

**Comment by Daydreamer114** [comment]
fixed with [08fa931](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/08fa9313c3b92d4a7705aa611f91e353cbc4de3a)

**Comment by SherkeyXD** [comment]
由于制作 OTA 的 ci 在下载过往完整包时出现网络问题，未能成功地下载 v5.5.0-beta.1.d241.gbc3ad67a0 的完整包，导致制作 v5.5.0-beta.1.d241.gbc3ad67a0 版本到 v5.5.1-alpha.1.d084.g5f5eccda7 的 OTA 包时发生错误

在此前提下，CI 错误地将下载了一半的，损坏的 v5.5.0-beta.1.d241.gbc3ad67a0 的“完整”包上传到了 v5.5.1-alpha.1.d084.g5f5eccda7 的 Release 附件中
