### ISSUE TITLE
日服 肉鸽 主界面Icon变动 未适配

### ISSUE THREAD

**Issue by ShirasawaYui** [MaaAssistantArknights/MaaAssistantArknights#10029]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

进入肉鸽的入口图标更新了
![image](https://github.com/user-attachments/assets/cf96672b-5ee5-4f79-b994-2367fd5c9e1d)
除了繁中其他也该一起适配了
![image](https://github.com/user-attachments/assets/701f3915-dfdb-49e3-aa6e-e997287ec008)

### Version

Resource Version: 懐黍離
UI Version: v5.5.0
Core Version: v5.5.0

### 日志文件

[asst.log](https://github.com/user-attachments/files/16465510/asst.log)

**Comment by ShirasawaYui** [comment]
![image](https://github.com/user-attachments/assets/a8788245-8dfd-4bec-bac5-126f5edaa428)
新增的关卡也没一起适配，现在需要手动通关

**Comment by Constrat** [comment]
How about we update the version? 5.5.0 was released before the new client update dropped. How would it have the new content?
