### ISSUE TITLE
游戏资源更新慢，或者直接失败

### ISSUE THREAD

**Issue by MurphyZX** [MaaAssistantArknights/MaaAssistantArknights#10025]
### 说说你遇到的问题？

![image](https://github.com/user-attachments/assets/f6d71308-fca1-4859-b09d-3ca1a187cbb9)
开clash tun 全局代理也一直失败，是什么原因呢

**Comment by kelo-kelo** [comment]
+1 一直失败 公测版稳定版都这样

**Comment by status102** [comment]
服务器运行不良，预期行为，已知问题

**Comment by 416130325** [comment]
我也是这样

**Comment by status102** [comment]
坐等修复就行
