### ISSUE TITLE
MAA游戏资源更新失败，异常自动回退版本

### ISSUE THREAD

**Issue by 1352900** [MaaAssistantArknights/MaaAssistantArknights#10026]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新不了，编制索引之后获取更新资源要么是直接失败，要么是下载速度异常缓慢然后失败，并且出现过一次更新失败后闪退再打开之后版本自动回退到上一版本的情况（这个的日志可能已经没了，因为卸载了一次），而且每次更新失败都会弹窗提示已经是最新版本
另外官网的下载也异常缓慢，会彻底卡死进度停滞，我是去github手动下载的新版MAA，但仍然重复上述情况

### Version

Resource Version: 太阳甩在身后

### 日志文件

[asst.log](https://github.com/user-attachments/files/16465180/asst.log)
[gui.log](https://github.com/user-attachments/files/16465181/gui.log)

最近一次应该在12点08左右

**Comment by mark021232** [comment]
我编制索引都失败了，我甚至还是上个版本

**Comment by 1352900** [comment]
> 我编制索引都失败了，我甚至还是上个版本

我其实也是上个版本出现的这个问题，我提交的反馈是新版是因为我在github手动下载的新版，但是仍然出现同样问题，我有写在详细里面

**Comment by WarpTamako** [comment]
我也遇到了这个问题，从上个版本开始出现。今天手动再GitHub下载新版后，问题仍然存在

**Comment by Eigh18n** [comment]
v5.5.0版本在同样的情况 卡在编辑索引

**Comment by zingwu** [comment]
+1,同样问题

**Comment by zhui0405** [comment]
+1，编制索引后持续一段时间后显示更新失败

**Comment by zuouzoyunyun** [comment]
+1,同样的问题，编制索引更新失败。根据公告内容两个运行库已经更新，maa也是重新下载的最新版，设置里面的版本也是5.5没问题
<img width="362" alt="屏幕截图 2024-08-02 145203" src="https://github.com/user-attachments/assets/6cdd6058-14b0-44a4-9be9-58a5a22d5b4f">

**Comment by ksharperd** [comment]
> ### 在提问之前...
> * [x]  我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
> * [x]  我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
> * [x]  我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
> * [x]  我已检查了置顶议题（pinned issue），确认我的问题未被提及
> 
> ### 问题描述
> 更新不了，编制索引之后获取更新资源要么是直接失败，要么是下载速度异常缓慢然后失败，并且出现过一次更新失败后闪退再打开之后版本自动回退到上一版本的情况（这个的日志可能已经没了，因为卸载了一次），而且每次更新失败都会弹窗提示已经是最新版本 另外官网的下载也异常缓慢，会彻底卡死进度停滞，我是去github手动下载的新版MAA，但仍然重复上述情况
> 
> ### Version
> Resource Version: 太阳甩在身后
> 
> ### 日志文件
> [asst.log](https://github.com/user-attachments/files/16465180/asst.log) [gui.log](https://github.com/user-attachments/files/16465181/gui.log)
> 
> 最近一次应该在12点08左右
> 
> ### 截图
> _No response_
> 
> ### 还有别的吗？
> _No response_

update server looks down though.
related:
> Due to server resource constraints, resource version updates are temporarily suspended. Please manually import the level file or wait for a new version release
