### ISSUE TITLE
基建错误

### ISSUE THREAD

**Issue by 110MT011** [MaaAssistantArknights/MaaAssistantArknights#10039]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

基建识别错误，不能快速收取生产材料，干员名称识别失败
mumu雷电均进行了尝试

### Version

Core Version: v5.5.11451

### 日志文件

[asst.log](https://github.com/user-attachments/files/16468774/asst.log)
[gui.log](https://github.com/user-attachments/files/16468775/gui.log)

**Comment by HoshinoAyako** [comment]
![QQ_1722593435040](https://github.com/user-attachments/assets/3e15cee8-c354-4a41-8460-2c660496de4a)
建议使用720p

**Comment by 110MT011** [comment]
[asst.log](https://github.com/user-attachments/files/16550081/asst.log)
[gui.log](https://github.com/user-attachments/files/16550083/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/16550085/asst.bak.log)
问题找到了，家里笔记本的默认GPU(Intel(R) UHD Graphics)有问题，不使用GPU加速就能正常检索了

**Comment by 110MT011** [comment]
我用英伟达显卡就能正常检索了，不知道是我的问题还是程序的问题
