### ISSUE TITLE
设置里的Http代理清空后依然走之前配置的代理

### ISSUE THREAD

**Issue by LonelyWindG** [MaaAssistantArknights/MaaAssistantArknights#10031]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

#### 条件说明
1. 切换配置里只有"Default"一个配置且是当前选中配置
2. gui.json的的"Default"配置里"VersionUpdate.Proxy"有配置过的代理(不知道是之前配置的还是什么情况下写入的, 没在界面上找到能改动这个的地方)

#### 目前的问题
- 设置里"软件更新"一栏的代理清空还是不管怎么设置, gui.json里都只有"Global"下对应的"VersionUpdate.Proxy"会发生变化;
- 实际软件更新仍然是走"Default"的代理, 导致界面上的修改完全不起效

### Version

UI Version: v5.5.0
Core Version: v5.5.0

### 日志文件

[gui.json](https://github.com/user-attachments/files/16465902/gui.json)
[gui.log](https://github.com/user-attachments/files/16465904/gui.log)
[asst.log](https://github.com/user-attachments/files/16465905/asst.log)

**Comment by ABA2396** [comment]
dev修了，等发版
