### ISSUE TITLE
请求萨米添加3层boss关前停止战斗选项，或者求好心人告知5层boss关停止战斗选项的json在哪里 我试试自己修改

### ISSUE THREAD

**Issue by Tacenda5618** [MaaAssistantArknights/MaaAssistantArknights#10032]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

需要刷黑白舞鞋 这两个除了告解就只有第三层第五层出了 希望添加选项 可以自己接手打完，或者打完提供选项，优先购买黑白舞鞋，类似水月肉鸽里的寻路鳞优先购买。

**Comment by octopusYan** [comment]
- 提高商店购买的优先度：在 `MAA\resource\roguelike\Mizuki` 目录下的 `shopping.json` 文件中把黑白舞鞋放到最上面

- 邪道方法（没试）：把 `MAA\resource\template` 目录下的 `Mizuki@Roguelike@StageDreadfulFoe-5.png` 换成 第三层的截图

**Comment by CASUUU** [comment]
好像只能在打完一整层后才停下来吧，具体可以看[这里](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/tasks.json)在9000行附近

优先拿藏品和购买藏品都是在[这里](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/roguelike/Sami/shopping.json)设置的

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/165f62a9-1941-47d3-a3ea-9b8b4152581b)
\MAA\resource\roguelike\Sami\shopping.json，这个文件是有序的，可以把舞鞋提到最前面

\MAA\resource\roguelike\Sami\encounter，如果你知道什么不期而遇出舞鞋，也可以在这里面调
不过maa拿掉落藏品是随机的，有可能有舞鞋也拿了另一个

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/db309bde-544f-4489-b4ab-1793d0c38846)
5层boss前暂停就在高级设置里

**Comment by octopusYan** [comment]
> ![图像](https://private-user-images.githubusercontent.com/74444214/354574011-db309bde-544f-4489-b4ab-1793d0c38846.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTY5OTgsIm5iZiI6MTcyMjU5NjY5OCwicGF0aCI6Ii83NDQ0NDIxNC8zNTQ1NzQwMTEtZGIzMDliZGUtNTQ0Zi00NDg5LWI0YWItMTc5M2QwYzM4ODQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDExMDQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZWZiYjY3ZGY0NTU3ODEwMDRiMjBiMTJjMWQ4YjM1MjMyNzkzNTE3MjZhOWRiYzdhZWQ0ODE3OTYxYmRhOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K2t_3Dw_Kj3lfungnEZWA5PsFX-Hp8-2e6jbXRNBl68) 5层boss前暂停就在高级设置里

他想改成第三层就停

**Comment by Daydreamer114** [comment]
> 他想改成第三层就停

简单，让他来写

**Comment by Daydreamer114** [comment]
> 请求萨米添加3层boss关前停止战斗选项

这个可以提一个enhancement，写第五层的现在不在线@Tacenda5618

**Comment by Daydreamer114** [comment]
#9813 
这个是添加第五层的代码，看得懂自己改也可以

**Comment by octopusYan** [comment]
邪道方法（没试过）：把`MAA\resource\template` 下的 `Mizuki@Roguelike@StageDreadfulFoe-5.png` 改成第三层的截图

**Comment by Daydreamer114** [comment]
> 邪道方法（没试过）：把`MAA\resource\template` 下的 `Mizuki@Roguelike@StageDreadfulFoe-5.png` 改成第三层的截图

草

**Comment by Tacenda5618** [comment]
感谢各位的解答 非常感谢！就不一一艾特各位了。
