### ISSUE TITLE
报错“此 Visual 未连接到 PresentationSource”

### ISSUE THREAD

**Issue by lbls741** [MaaAssistantArknights/MaaAssistantArknights#10042]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在软件更新弹出更新日志或公告时，关闭公告窗口，出现错误提示“此 Visual 未连接到 PresentationSource”。关闭这个窗口软件会强制退出，重新运行后一切正常。
这个bug几乎100%出现，但不影响正常使用。（不修复也行）
感谢你们为明日方舟社区和开源社区的贡献

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11451
Core Version: v5.5.11451

### 日志文件

源日志文件：[asst.log](https://github.com/user-attachments/files/16469349/asst.log)     [gui.log](https://github.com/user-attachments/files/16469353/gui.log)     [错误信息.txt](https://github.com/user-attachments/files/16469478/default.txt)
错误发生时间：8.24,16:15，即版本号第一次为5.5.11451时

### 还有别的吗？

模拟器：雷电9，版本9.0.75
操作系统：Windows 11 专业版，版本号 23H2，操作系统版本 22631.3958
maa版本号和日志只是这次错误的，之前这个bug也经常出现

**Comment by ABA2396** [comment]
我记得之前有人提到过来着，不知道为啥找不到issue了。先试试看更新 .net 版本

**Comment by ABA2396** [comment]
发一下config/gui.json

**Comment by lbls741** [comment]
更新.net运行库似乎有效，临时下载的测试软件没有再出现错误。
谢谢大佬指点。
请问这个issue应当如何处理？需要关闭吗？
