### ISSUE TITLE
ui bug : 错误的任务列表位置

### ISSUE THREAD

**Issue by yc080713** [MaaAssistantArknights/MaaAssistantArknights#10049]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

你甚至可以把基建任务拖到任务列表中

### Version

UI Version: DEBUG VERSION

### 日志文件

无

### 截图

![image](https://github.com/user-attachments/assets/1512918a-23a3-40f5-b299-d0b1adf19be2)

**Comment by Daydreamer114** [comment]
学姐：留着好玩.jpg
