### ISSUE TITLE
萨卡兹肉鸽：卡在巴别塔雇员

### ISSUE THREAD

**Issue by lingxinquan** [MaaAssistantArknights/MaaAssistantArknights#10045]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨卡兹肉鸽卡在巴别塔雇员

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11451
Core Version: v5.5.11451

### 日志文件

[asst.log](https://github.com/user-attachments/files/16470811/asst.log)
[gui.log](https://github.com/user-attachments/files/16470812/gui.log)

### 截图

![kale](https://github.com/user-attachments/assets/03a7fb6f-00e2-45b5-ab13-b4c23535ea09)

**Comment by Daydreamer114** [comment]
你的模拟器分辨率和dpi是多少？

**Comment by lingxinquan** [comment]
> 你的模拟器分辨率和dpi是多少？

dx模式 ，高性能，显存使用策略：资源占用更少，强制使用独立显卡，分辨率：1280x720，60帧，磁盘共享：只读系统盘。手机型号预设vivo  s15

**Comment by Daydreamer114** [comment]
@DavidWang19 佬，这个识别分数该不该降？你当时测试的时候得分多少？
