### ISSUE TITLE
选中完成后关机 在重启后变成休眠

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#10043]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

完成后动作在选中关机 休眠 无其他MAA关机 无其他MAA休眠时
关掉MAA再启动 总会变成休眠

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11451
Core Version: v5.5.11451

**Comment by status102** [comment]
fe17ecfccc79949ae635eeb44b0f8765ae954ae4 fixed
