### ISSUE TITLE
【Globle/JP】 日服萨米肉鸽卡在风雪蔽目无法进行下一步

### ISSUE THREAD

**Issue by Kingjizrw** [MaaAssistantArknights/MaaAssistantArknights#10055]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

日服在使用萨米肉鸽存钱功能时，一层商店存完钱回到萨米主题页面结束一局肉鸽时卡在风雪蔽目（手动点击完相关信息回到萨米主题页时可以继续自动打关存钱）

### Version

Resource Version: 懐黍離
UI Version: v5.5.11451
Core Version: v5.5.11451

### 日志文件

时间点均为日志的结尾
[logs.zip](https://github.com/user-attachments/files/16478583/logs.zip)

### 截图

![屏幕截图 2024-08-03 153426](https://github.com/user-attachments/assets/697f5002-d234-458a-8e42-29316bab935c)

### 还有别的吗？

使用模拟器为mumu版本v3.9.3
未使用截图增强和ＧＰＵ加速推理

**Comment by Manicsteiner** [comment]
duplicate of #10037

**Comment by Kingjizrw** [comment]
> duplicate of #10037

删除Sami@Roguelike@MissionFailedFlag2.png后已解决
