### ISSUE TITLE
无其他MAA时 选项无法保存，重启后不选中

### ISSUE THREAD

**Issue by bronzitro** [MaaAssistantArknights/MaaAssistantArknights#10054]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

完成后的选项 “无其他MAA时” 不能保存，重启后重置

### Version

5.5.11451

### 日志文件

无

**Comment by status102** [comment]
信息过少，无法复现

**Comment by bronzitro** [comment]
> 信息过少，无法复现

需要什么样的信息？

**Comment by status102** [comment]
> > 信息过少，无法复现
> 
> 需要什么样的信息？

遇到该现象的操作流程，刚刚花10分钟复现出来。不过等会要出门了，修完没时间测了估计

**Comment by bronzitro** [comment]
https://github.com/user-attachments/assets/87c375e5-ad78-46f4-b18c-4aef70e05516

**Comment by status102** [comment]
aa083beaaf7599a4f1f79b7a7c1eb2eeeccaba52 fixed
