### ISSUE TITLE
Mumu方舟专版已支持截图增强模式

### ISSUE THREAD

**Issue by starrin** [MaaAssistantArknights/MaaAssistantArknights#10057]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

不知道是哪个版本开始实装的，但今天偶然发现夏活版本中已经有相关dll了，而且完全可以正常使用

### 有什么好的想法？

希望可以更新相关文档和UI界面提示

### 其他内容

![da609732-f8a0-4cb8-b974-54d915a8bb08](https://github.com/user-attachments/assets/150a9e03-7517-4148-9175-22d6f8f633ec)
![e285f21c-3b4c-4b78-8e81-e9ec337f1d49](https://github.com/user-attachments/assets/01ef95a3-18c4-4dd1-8dbd-d5280207f0bb)

**Comment by ABA2396** [comment]
我去问问mumu那边

**Comment by deYangar** [comment]
国际版3.8.18(2845)，也有该dll了

**Comment by ABA2396** [comment]
> 国际版3.8.18(2845)，也有该dll了

![image](https://github.com/user-attachments/assets/ab349a5a-c4f9-425e-ace3-994c89eaa110)
有这个文件，但没有截图增强的功能，你到主界面之后可以看到用的还是原来的截图方式

**Comment by deYangar** [comment]
> > 国际版3.8.18(2845)，也有该dll了
> 
> ![image](https://private-user-images.githubusercontent.com/99072975/356218584-ab349a5a-c4f9-425e-ace3-994c89eaa110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjkzNTksIm5iZiI6MTcyMzEyOTA1OSwicGF0aCI6Ii85OTA3Mjk3NS8zNTYyMTg1ODQtYWIzNDlhNWEtYzRmOS00MjVlLWFjZTMtOTk0Yzg5ZWFhMTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE0NTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZjcwMGNjMjg3OTBmZDczMzFjNWI0MGFhMmY2Y2ZmZTFkYjZjYzM2Y2U2NzQ1ODVhYzIwZWMyZGRkMjg2MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cWqleNbfYNe3P-rTC32jIhPkpn17BtQbxm05-jBQR6g) 有这个文件，但没有截图增强的功能，你到主界面之后可以看到用的还是原来的截图方式

好吧
