### ISSUE TITLE
小工具公招识别使用maa语言输出

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#10067]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在用的是明日方舟客户端对应语言，希望同时输出maa的语言设置对应的语言

**Comment by Manicsteiner** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2dceadbd7d1273c158f4def6327652e61c01dff0/src/MaaWpfGui/ViewModels/UI/RecognizerViewModel.cs#L320
在这里改成 `string operName = DataHelper.GetLocalizedCharacterName(oper["name"]?.ToString());` 就能解决干员名称，但是tag似乎没有直接替换的方法
![图片](https://github.com/user-attachments/assets/cbfac37e-36d3-4ec4-94a1-80f86e215198)

**Comment by ABA2396** [comment]
tag影响不大吧，名字对就行了
这个要不加个判断，要是游戏语言和界面语言不一样就两个都显示
