### ISSUE TITLE
版本更新以后无法设置成完成以后自动关机了，选刷完关机以后再次开启电脑他又会默认变成刷完休眠

### ISSUE THREAD

**Issue by mokamomoka** [MaaAssistantArknights/MaaAssistantArknights#10065]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

没有选择仅一次选项，直接选择的完成后关机，但是尝试了等他刷完关机和，没刷完重开MAA都不能解决，MAA重启以后变成默认完成后休眠的选项

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11451
Core Version: v5.5.11451

### 日志文件

[asst.log](https://github.com/user-attachments/files/16480979/asst.log)
[gui.log](https://github.com/user-attachments/files/16480980/gui.log)

### 配置信息

MUMU  1600*900 240dpi
win10
未开

### 截图

![AN_(`WJ90FXP9RHZ(I0_%Y2](https://github.com/user-attachments/assets/5778501e-fd19-450c-a1b9-04436fc0d87f)

**Comment by Rbqwow** [comment]
Duplicate of #10043
