### ISSUE TITLE
在肉鸽中如果高台位置已被占满，仍会反复尝试放置高台干员

### ISSUE THREAD

**Issue by raku8947** [MaaAssistantArknights/MaaAssistantArknights#1006]
在例如酒商运输队和邪异囚笼这类高台位置较少的地图尤为明显，不知道能否判定位置是否全部被占据……

**Comment by ABA2396** [comment]
现在好像是不会在重复的格子重复放人吧，也就是被打掉了就等于少了一个可部署区域（）

**Comment by MistEO** [comment]
> 现在好像是不会在重复的格子重复放人吧，也就是被打掉了就等于少了一个可部署区域（）

是，~~我懒得做识别~~，并且被打掉的位置可能会一直被打，直接放弃这个位置按目前的效果来看还行。

可能得考虑下这种高台很少的图要怎么处理
