### ISSUE TITLE
maa自动退出并关闭模拟器功能异常

### ISSUE THREAD

**Issue by xinlingheidong** [MaaAssistantArknights/MaaAssistantArknights#1007]
小助手已经关掉了。模拟器也关了，但是没有完全关。
![image](https://user-images.githubusercontent.com/94310025/176031414-d5a44190-3fc0-432f-ae47-723ef6f5541c.png)
小助手选择的是退出并关闭模拟器
但是再打开小助手后显示的是无动作
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8995506/asst.log)
蓝叠模拟器，B服

**Comment by MistEO** [comment]
蓝叠国内版是用管理员权限启动的，maa 关不掉他。

考虑用管理员启动 maa, 或者直接换个模拟器，除了 mumu 和蓝叠国内版之外，其他的应该都不需要管理员

**Comment by MistEO** [comment]
可能和 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1043 是同一个问题

**Comment by zzyyyl** [comment]
大多数模拟器都有同样的问题，#1043 有一些目前的讨论结果
