### ISSUE TITLE
幸运墙无法领取

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#10074]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

[bandicam 2024-08-04 10-14-02-369.zip](https://github.com/user-attachments/files/16484559/bandicam.2024-08-04.10-14-02-369.zip)
见视频所示，

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[asst - 副本.log](https://github.com/user-attachments/files/16484560/asst.-.log)
[gui - 副本.log](https://github.com/user-attachments/files/16484561/gui.-.log)

### 配置信息

MUMU12：1920 x 1080（DPI 280）60帧
MuMu截图增强：开启

**Comment by status102** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10050#issuecomment-2267595792 
大概是修了
