### ISSUE TITLE
建议存储赠送线索的好友档案json以方便线索互赠，并只领取有收益的赠送线索

### ISSUE THREAD

**Issue by DaseinL** [MaaAssistantArknights/MaaAssistantArknights#10077]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

如题，建议在基建线索交流部分增加一个选项：
回赠选项
> 可以保存谁给我赠送了线索，赠送了多少，我回赠了多少。如果我和其他人的线索差值为0，那么我优先赠送已有线索给赠送我线索最多的人。
具体保存格式如图。
另外，还可以增加一个选项，是否将全部自己获得的线索赠送。
而在领取线索时每天只领取快过期的前三个线索。

### 其他内容

<img width="578" alt="截屏2024-08-04 14 58 00" src="https://github.com/user-attachments/assets/6dab4f65-1060-4b09-a81c-8bdf60cf66e0">

**Comment by Constrat** [comment]
Out of scope
