### ISSUE TITLE
自动使用某些技能导致战斗拖沓

### ISSUE THREAD

**Issue by lulu20060202** [MaaAssistantArknights/MaaAssistantArknights#10072]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

肉鸽战斗中不断尝试释放空弦2技能, 但是范围内没有敌人放不出来, 导致不断点开技能界面试图放技能而拉长战斗时间

### 有什么好的想法？

选择技能时避开类似技能

**Comment by HoshinoAyako** [comment]
一样的。类似的情况有刻刀，异客，锏等
都是需要技能范围内有敌方单位为目标时才能用出去。
刻刀比较特殊，官方专注失调也会不断重复尝试使用技能。
