### ISSUE TITLE
增加自动抄作业推主线功能

### ISSUE THREAD

**Issue by CO2mega** [MaaAssistantArknights/MaaAssistantArknights#10085]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题，不能自动抄作业推主线，想开模组了发现前面主线没推需要一关关找作业

### 有什么好的想法？

把已有的干员识别和作业站结合做到全自动推主线关，干员识别可以选超过某个自定义等级的作为可用干员，然后自动编队

**Comment by Daydreamer114** [comment]
作业作者在写作业的时候是自由选择干员的，所以用户需要按照自己的干员池和干员练度去选择作业

由于精二券的发放，如果需求量够大的话，会出主线ew/令+阿米娅全通，但如果没有这两个干员就需要借助战，目前maa无法自动借助战，需要等方舟借助战自由选择技能和模组的功能实装
