### ISSUE TITLE
[Global/EN] Recognizing un-clickable option in Encounter Stage

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#10088]
From Phantom,
Does it mean that the clickable option is brighter than this?

match_templ | Phantom@Roguelike@StageEncounterOptionFree.png score: 0.981162 rect: [ 1141, 188, 104, 85 ] roi: [ 1100, 0, 180, 700 ]
![image](https://github.com/user-attachments/assets/0b6e995f-204a-45eb-8b75-47f7626bf5ea)
![MuMu12-20240805-132223](https://github.com/user-attachments/assets/73b83547-d93b-4977-a3f1-26b9386ceed0)

**Comment by Constrat** [comment]
Legendary issue this one, never bothered to fix as it has always been a pain in the ass for all global clients.
Older issues were probably closed by the stale automation.

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/0f616fb4-6610-4191-a2e2-5c80df352fbe)
at least put the original text here incase ocr works well/_ \

![image](https://github.com/user-attachments/assets/bfca099c-d8d0-4c80-ae53-5a98a684bc1d)

**Comment by Constrat** [comment]
This was all automated by the Resource Updater XD

**Comment by Constrat** [comment]
I'm already checking everything. The problem is that what is detected is correct and all the replace were already prepared for the missing spaces, hence the question marks for regex. It seems like they are
- being completely skipped (why lol)
- there's no replace at all being done (which is even worse)

**Comment by Constrat** [comment]
> after processing roguelike task, you can go to asst.log and search "Unknown Event", you can probably see a lot.
> I assume that adding ocr replace will lead them to one of the file in \resource\roguelike\Sami\encounter\ and let it work correctly.

I think the replacement is directly not being done.

**Comment by Daydreamer114** [comment]
> I think the replacement is directly not being done.

I agree. I'll go through RoguelikeStageEncounterTaskPlugin.cpp first.

**Comment by Constrat** [comment]
For now I will revert your commit as the regex is correct. I'm investiganting the deeper issue.

**Comment by Constrat** [comment]
Yeah, let me do it myself :)
Regexing is a huge part of ocrReplacing as we can drastically reduce the replaces count (we can't put infinite replaces, after around 650~ MAA crashes [lol])

**Comment by Daydreamer114** [comment]
yeah i get this thx

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/1e725087-19e4-4e74-a42b-7edd80073f1a)
I cant see any code for replacing here?

**Comment by Constrat** [comment]
set_task_info is correct, and it's always used, unless also the CN needs ocrReplace otherwise it won't work, but this is the first it happens as all other times with ocrreplace it usually worked

**Comment by Constrat** [comment]
If you check inside of analyze(), the OCRer class will do a lot more steps based on the m_params

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/1c1c7788-03e2-4d7c-8421-e4b97f7d4c23)
In regular expressions, `.` represents any character. If you want to match the actual "." character, you need to write it as `\.` Is everything really okay here?

**Comment by Constrat** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/355159293-1c1c7788-03e2-4d7c-8421-e4b97f7d4c23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NzIzNTIsIm5iZiI6MTcyMjg3MjA1MiwicGF0aCI6Ii85OTA3Mjk3NS8zNTUxNTkyOTMtMWMxYzc3ODgtMDNlMi00ZDdjLTg0MjEtZTRiOTdmN2Q0YzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE1MzQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYzA0Yjk1NDNhNmUyZGUwMTlmZmViNmJkMTVjNWVjNGZmODZmZWQzMzQ2YTJiZTAxMDM2ZjEyMjYyYzNmMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jlq-CdM0oJ8Pjx9_dy88gVx8zgwBjYw__0E2W-b-VuE) In regular expressions, `.` represents any character. If you want to match the actual "." character, you need to write it as `\.` Is everything really okay here?

This makes a lot of sense lollll
