### ISSUE TITLE
傀影肉鸽选择刷源石锭，但是运行时不投资源石锭就直接退出重开

### ISSUE THREAD

**Issue by czt635** [MaaAssistantArknights/MaaAssistantArknights#10084]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

傀影肉鸽选择刷源石锭，但是运行时不投资源石锭就直接退出重开
![image](https://github.com/user-attachments/assets/4b265219-dd0b-4f33-811f-b491e33c4c16)
![image](https://github.com/user-attachments/assets/756da6a0-919e-4274-893b-e266e6b41780)

### Version

UI Version: v5.5.11452

### 日志文件

[asst.log](https://github.com/user-attachments/files/16489014/asst.log)
[gui.log](https://github.com/user-attachments/files/16489015/gui.log)
2024.8.5 5点多

### 配置信息

雷电模拟器9.0.71 分辨率 1920*1080 dpi280 帧率60FPS
WINDOWS 10 企业版 LTSC

**Comment by Daydreamer114** [comment]
请填写配置信息

**Comment by czt635** [comment]
> 请填写配置信息

已填写

**Comment by status102** [comment]
asst.log不包含错误发生时间日志，检查asst.bak.log内容并上传

**Comment by czt635** [comment]
[gui.log](https://github.com/user-attachments/files/16508119/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/16508122/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/16508124/asst.log)

**Comment by czt635** [comment]
> asst.log不包含错误发生时间日志，检查asst.bak.log内容并上传

已上传

**Comment by status102** [comment]
没匹配到投资入口

印象中傀影肉鸽不是必出投资入口的，给个待定

**Comment by czt635** [comment]
应该不是这个原因 我是从前一天晚上开始挂的 结果早上起来一块钱都没投 手打了几把 每把都有投资入口

**Comment by status102** [comment]
> 应该不是这个原因 我是从前一天晚上开始挂的 结果早上起来一块钱都没投 手打了几把 每把都有投资入口

用模拟器内置截图截一下商店的画面看看？

我没通关没法测（

**Comment by status102** [comment]
```
[2024-08-08 15:07:09.429][TRC][Px3b48][Tx40f4] │││ match_templ | Roguelike@StageTraderInvestSystem.png score: 0.959512 rect: [ 417, 177, 176, 116 ] roi: [ 360, 51, 450, 450 ]
```

怪，你的图我直接跑通了测试
