### ISSUE TITLE
[iOS/MAC] MaaTools missing from PlayCover

### ISSUE THREAD

**Issue by TranMK** [MaaAssistantArknights/MaaAssistantArknights#10086]
### The problems you have encountered?

The option for MaaTools is not shown when configuring PlayCover
Installed Maa first, then PlayCover and Arknights
![image_2024-08-05_111641681](https://github.com/user-attachments/assets/8acf9cc1-e1e5-441e-b711-d18b58f23a08)

**Comment by wangl-cc** [comment]
Which version of PlayCover are you using? The `MaaTools` option only exists in [our fork](https://github.com/hguandl/PlayCover/releases).
