### ISSUE TITLE
生息演算刷奖励自动停止

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#10083]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

搞个插件，连续多少次(做个保底)代币数量一样，则认为刷完点数并停止任务
直接ocr，或者拿每次的截图的左下角做模板匹配

**Comment by Lancarus** [comment]
可以直接通过task实现，满了在过结算日的时候会出现生息点数max

**Comment by ABA2396** [comment]
感觉不是不行，抓个人加一个task就好了

**Comment by ABA2396** [comment]
对的，在开启下一天之前加个识别max的task，这个task的next接stop就好了
