### ISSUE TITLE
地图相机参数偏移

### ISSUE THREAD

**Issue by NTFA102** [MaaAssistantArknights/MaaAssistantArknights#10093]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用自动战斗时会出现选中并拖出干员到对应坐标但不部署，以及部署后不会自动开启技能的情况

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

问题出现在8.5 16:05~16:09
[asst.log](https://github.com/user-attachments/files/16492904/asst.log)
[gui.log](https://github.com/user-attachments/files/16492905/gui.log)

### 配置信息

雷电模拟器 1920*1080dpi280 60帧 Windows11 GPU加速推理开启 AMD Radeon™ 610M

### 截图

![main_07-07](https://github.com/user-attachments/assets/d09bbb49-85f6-4867-b05b-5f724586028e)

**Comment by status102** [comment]
这是哪张图

**Comment by status102** [comment]
![main_07-13](https://github.com/user-attachments/assets/03d28bff-baeb-4bcd-a142-51fcf86c5781)

7-15也发现偏移现象

cc @yuanyan3060

**Comment by HLHTHoldWind** [comment]
在大量其他地图中也存在该问题
似乎在早期地图尤为明显（待确认）
截图来自 [act5d0_ex04, act5d0_ex05, act5d0_ex06, act5d0_ex07, act5d0_ex08, act11d0_08]
![act5d0_ex04](https://github.com/user-attachments/assets/147c85d3-1fd6-41d3-b122-ea6a2d4b4ed0)
![act5d0_ex05](https://github.com/user-attachments/assets/c0d17a79-5603-4be1-85c7-ca9306d7561a)
![act5d0_ex06](https://github.com/user-attachments/assets/5db2daf4-f9c4-43a6-a28a-ddc1501ddcc4)
![act5d0_ex07](https://github.com/user-attachments/assets/6ada9348-dd65-4973-9e1b-90bab3d5089d)
![act5d0_ex08](https://github.com/user-attachments/assets/42b71e6d-f555-4cbf-839a-f5e397941b63)
![act11d0_08](https://github.com/user-attachments/assets/962cbd26-5dcb-4377-ad5e-16c393253db2)

**Comment by yuanyan3060** [comment]
> ![main_07-13](https://private-user-images.githubusercontent.com/102887808/355292253-03d28bff-baeb-4bcd-a142-51fcf86c5781.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMTUzNDMsIm5iZiI6MTcyMzMxNTA0MywicGF0aCI6Ii8xMDI4ODc4MDgvMzU1MjkyMjUzLTAzZDI4YmZmLWJhZWItNGJjZC1hMTQyLTUxZmNmODZjNTc4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQxODM3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWVmYzdjNGJiZmIzMThhZWQ3ZDkxYTExOWIwOGZiNzg0N2ZkYTlhYmNkYzRhNzgyZDM2YTcwNWNkZTQzYmZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._ap5DPLs6MYxSo7Cpz4DBBOLaVLDcDhPaB_Er8uajV8)
> 
> 7-15也发现偏移现象
> 
> cc @yuanyan3060

似乎无法复现（
![image](https://github.com/user-attachments/assets/7addd9df-d299-47fc-806d-5d8ee39b4143)

**Comment by yuanyan3060** [comment]
我觉得是yj的问题

**Comment by Constrat** [comment]
@status102 For some reason your screencap is more zoomed in compared to yuanyuan's

**Comment by status102** [comment]
![image](https://github.com/user-attachments/assets/6d8c2f14-25a6-4e10-b881-8b04dc0c17a6)

疑似yj已修复
