### ISSUE TITLE
基建自动换班不知道能不能只换疲劳的干员

### ISSUE THREAD

**Issue by LBacteria** [MaaAssistantArknights/MaaAssistantArknights#1009]
如题，我发现在基建换班过程中会把还有体力在工作的干员换下

**Comment by YipKei** [comment]
设置->基建设置->宿舍入驻心情阈值

有一说一，不建议将这个数值改得太小，对于3发电用户来说这个比例应该不小于你的换班时间除以36.9，2发电用户则为换班时间除以34.2。
以8小时上线一次为例，这个比例应该分别为22%和24%。

至于能上60小时班的组合，这个得等未来优化。

**Comment by LBacteria** [comment]
好的谢谢
