### ISSUE TITLE
为加工站添加自动合成精英材料功能。

### ISSUE THREAD

**Issue by GithubtoMicrosoft** [MaaAssistantArknights/MaaAssistantArknights#10095]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

现有的排班表生成器能指定干员在加工站，但无合成精英材料功能。
能否增加指定精英材料合成，可以在MAA选择精英材料合成。
(选择合成"D32、RMA70-24"等材料)
(像MAA刷理智的关卡选择，下拉式选单选择"龙门币-6/5、1-7"。)

**Comment by Daydreamer114** [comment]
你每天需要合不止一次精英材料吗？不是练干员的时候才需要合吗
放加工站是为了蹭信赖的

**Comment by Constrat** [comment]
^
Workshop (or processing depends on the translation) with automated shifts is only used for
- Trustfarm
- Complex base schedules that require operators from different factions, for example Nian for Sui or Magallan for Rhine Lab.

Adding an automatic material merge seems useless as you craft materials based on what you need, not on an automatic base
