### ISSUE TITLE
修改一键长草任务列表顺序在程序重启后失效

### ISSUE THREAD

**Issue by bodayw** [MaaAssistantArknights/MaaAssistantArknights#10094]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

手动拖动修改一键长草任务列表的顺序，重启程序后仍然会恢复为默认顺序

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

应该不需要

### 配置信息

Windows 10

**Comment by Daydreamer114** [comment]
拖完之后运行一下maa应该能解决

**Comment by bodayw** [comment]
> 拖完之后运行一下maa应该能解决，点一下link start再stop就行，不用连上模拟器

嗯，确实如此。不过还是应该能自动保存才符合直觉

**Comment by Daydreamer114** [comment]
cc @ABA2396
