### ISSUE TITLE
剿灭作战的作业代码无法识别

### ISSUE THREAD

**Issue by Bloody-Doll** [MaaAssistantArknights/MaaAssistantArknights#10092]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

最近想要体验剿灭作战的作业，一直出现粘贴作业代码之后无法识别的情况，其他作业代码使用正常

### Version

UI Version: v5.5.11452

### 日志文件

[asst.log](https://github.com/user-attachments/files/16492929/asst.log)
[gui.log](https://github.com/user-attachments/files/16492930/gui.log)

### 配置信息

mumu12/1280x720/240/60
win10
未增强
无加速

### 截图

![QQ_1722846141575](https://github.com/user-attachments/assets/d539ef7d-5749-451b-9296-da34d5886c9c)

**Comment by Daydreamer114** [comment]
单个作业把作战列表关了

**Comment by Bloody-Doll** [comment]
收到，经过尝试已解决，非常感谢，顺带提问有没有支援链接或者投喂二维码

**Comment by Daydreamer114** [comment]
不好意思，暂时不接受捐款与赞助，谢谢支持

**Comment by Saratoga-Official** [comment]
去b站搜索maaofficial，可以支持下主播
