### ISSUE TITLE
自动练干员

### ISSUE THREAD

**Issue by EricLuo-163** [MaaAssistantArknights/MaaAssistantArknights#10100]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

选择干员培养等级并自动规划刷图战斗

**Comment by EricLuo-163** [comment]
被maa养废了谢谢

**Comment by Constrat** [comment]
Thank you for using MAA; unfortunately this features is out of scope for the project, as there already a lot of tools that allow you to calculate the necessary resources, and prepare a plan to tell MAA what stages to farm.

**Comment by Daydreamer114** [comment]
https://penguin-stats.cn/planner
