### ISSUE TITLE
萨卡兹肉鸽驮兽到达了它的终点卡死

### ISSUE THREAD

**Issue by curtin18** [MaaAssistantArknights/MaaAssistantArknights#10106]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

两周前有同样bug出现，查询issue下提示已修复，但我在使用过程中还是出现了这个问题。当“驮兽到达了它的终点”，maa不会有任何动作，手动点击取消之后，可以继续执行

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[asstAgui.zip](https://github.com/user-attachments/files/16505554/asstAgui.zip)
出现问题时间为2024-08-06 03:35左右

### 配置信息

MUMU模拟器12，分辨率1920x1080（DPI280），帧率30
操作系统Windows 10
mumu截图增强未开启
GPU加速推理已开启
GPU型号：AMD Radeon RX580 2048SP

### 截图

![XU8ZO719{E3XQUYK76`N ZD_tmb](https://github.com/user-attachments/assets/2663c0ac-b428-415d-b361-67f0561b9f1b)

**Comment by Daydreamer114** [comment]
错误：离开去伪存真后直接识别到了思绪混乱，然后弹出驮兽离开，然后点击思绪界面（无效）
