### ISSUE TITLE
设置完成后关机，总是变回休眠

### ISSUE THREAD

**Issue by atkdefender** [MaaAssistantArknights/MaaAssistantArknights#10103]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

完成后那里设置关机，一看又给我系统休眠了

### Version

资源版本 太阳甩在身后
界面版本 v5.5.11452
核心版本 v5.5.11452

### 日志文件

[asst.log](https://github.com/user-attachments/files/16504232/asst.log)
[gui.log](https://github.com/user-attachments/files/16504233/gui.log)

### 配置信息

Win 10

**Comment by ABA2396** [comment]
11452还这样？

**Comment by atkdefender** [comment]
> 11452还这样？

我再观察。
我台式弄了早晚7点自动开机，靠Maa关机，之前在旅行一直靠向日葵操作Maa，这几天要么刷图从9图跳回1-7，要么电脑休眠（我从来都是设置关机）。昨晚今天都运行为休眠，我目前又调整为关机（就像之前远程向日葵设置那样）。如果没问题我过几天回来Close。

**Comment by ABA2396** [comment]
11451有问题，11452修了，我看日志里你还没在11452版本用过关机

**Comment by status102** [comment]
v5.5.11452 无法复现

**Comment by Saratoga-Official** [comment]
用户群也有一个，也是11452版本，应该是还有问题

**Comment by status102** [comment]
复现后再来个新issue吧
