### ISSUE TITLE
开启uu加速器后Maa无法连接模拟器

### ISSUE THREAD

**Issue by Aoki-Li** [MaaAssistantArknights/MaaAssistantArknights#1010]
以前使用mumu模拟器开启过uu加速器后maa就无法连接模拟器了，更换为蓝叠模拟器后开启uu加速器也会导致无法连接，这次是打到一半打开uu加速器maa这边就断开连接了，刷1-7刷到半截断开了，遇到这种办法以前的解决方式是重启电脑就好，但我电脑后台很多软件每次重启要很久所以反馈一下看是我的问题还是加速器的问题。

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8996697/asst.log)倒着往上看吧，只看28日就好了。

**Comment by Aoki-Li** [comment]
不是100%会发生但概率应该蛮高的，我经常因为没法一键长草而重启电脑

**Comment by MistEO** [comment]
和碧蓝脚本 ALAS 那边的大佬聊了一下，他们也遇到过这种问题，应该是 UU 的问题，别的加速器都没有。

我们这边没法复现，可能是 UU 针对特定加速的游戏做了什么操作，你加速的是哪款游戏？加速模式什么的有设置么

这个问题可能考虑给 UU 他们报个 bug

**Comment by Aoki-Li** [comment]
> 加速apex港服，我现在都是点游戏图片下方弹出的“立即加速”
![uu](https://user-images.githubusercontent.com/46291296/176081782-8097a33c-ffb1-4ab8-8f48-040bfd96a191.png)
，但我以前有特别选过路由模式（很久以前了），不过我猜测默认加速模式应该是进程模式。
以前问题都是晚上打完apex然后挂方舟发现连接不上，这次问题是打开uu加速器发生的甚至没有加速游戏。
刚看链接的另一个issues，我后台有挂clash v0.19.22，但我觉得不是这个问题因为昨天晚上我也是挂着的，唯一的区别就是我没打游戏，防火墙我不好说我看不懂，反正点取消也能用QAQ。
感觉不好做判断，等我下次遇到了我接着发日志吧。

**Comment by soundofautumn** [comment]
应该不是clash的问题，我这边一直开着clash没出过这种问题

**Comment by BalanceSteelyard** [comment]
貌似是TUN网卡兼容的锅，关掉这个选项后只使用路由模式就可以了。软件模式还是会连不上，开启TUN网卡兼容使用路由模式也一样。

**Comment by DoctorKoKoDaYo** [comment]
> 貌似是TUN网卡兼容的锅，关掉这个选项后只使用路由模式就可以了。软件模式还是会连不上，开启TUN网卡兼容使用路由模式也一样。

确实
