### ISSUE TITLE
为基建换班功能添加全选及清除功能

### ISSUE THREAD

**Issue by 1736698520** [MaaAssistantArknights/MaaAssistantArknights#10102]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

![QQ20240806-000723](https://github.com/user-attachments/assets/7457ec9b-8d56-4fe8-8468-7d8e8d0333fd)
希望能给基建换班添加全选或者清除功能，当只想换宿舍的时候操作起来非常麻烦

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/4cfc91b9-931e-458a-a015-1c8f830c54b8)
