### ISSUE TITLE
Mac版萨卡兹肉鸽卡在“思维已阻滞”界面

### ISSUE THREAD

**Issue by zycBruce** [MaaAssistantArknights/MaaAssistantArknights#10114]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

Mac版萨卡兹肉鸽卡在“思维已阻滞”界面，不自动舍弃思绪

### Version

v5.5.11452（508）

### 日志文件

1

### 配置信息

MacOS

### 截图

<img width="985" alt="iShot_2024-08-06_23 14 24" src="https://github.com/user-attachments/assets/88c7f5ce-ff60-4347-ab93-1c0be656966d">

**Comment by Saratoga-Official** [comment]
没有日志解决不了
