### ISSUE TITLE
"MuMu截图增强"功能，在自动重新开启模拟器后出现“截图失败”

### ISSUE THREAD

**Issue by pu4ers** [MaaAssistantArknights/MaaAssistantArknights#10110]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

勾选“截图增强”功能后**首次连接正常**。
在maa自动**关闭模拟器**/手动**关闭模拟器后**，maa自动**重启模拟器**，出现**截图失败异常**。
此时取消勾选再勾选“截图增强”选项，方可正常连接。

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.0
Core Version: v5.5.0

### 日志文件

[asst.log](https://github.com/user-attachments/files/16507448/asst.log)
[gui.log](https://github.com/user-attachments/files/16507449/gui.log)

### 配置信息

mumu模拟器
分辨率1600*900
DPI默认
帧率60
操作系统windows10
截图增强开启
GPU加速推理开启，RTX2060笔记本

### 截图

![Snipaste_2024-08-06_16-08-55](https://github.com/user-attachments/assets/e4977a69-c379-43cb-9c85-45b04448cabf)
![image](https://github.com/user-attachments/assets/805b6af5-2ef6-4f5d-8d28-e571bf82b038)

**Comment by Saratoga-Official** [comment]
把gpu加速关了

**Comment by ABA2396** [comment]
> 把gpu加速关了 还有你这maa版本旧了，更新一下

和gpu加速没啥关系，mumu截图加速就有这个问题，重启模拟器没重启maa的话就会遇到截图错误

**Comment by Daydreamer114** [comment]
> 和gpu加速没啥关系，mumu截图加速就有这个问题，重启模拟器没重启maa的话就会遇到截图错误

要不要给截图失败加个检测，开了mumuExtra就弹窗提醒重启（）

**Comment by pu4ers** [comment]
> 把gpu加速关了 还有你这maa版本旧了，更新一下

我刚刚重下了最新版本，把配置文件复制过去之后，测试了稳定复现的方法：

无论GPU加速是否开启，在任务完成/手动停止任务执行后，重启模拟器且不重启maa，就会出现这个问题。
如果是maa任务结束自动关闭了模拟器，则自动重启模拟器不会出现这个问题（之前的版本用这个方法也会出现问题）。

**Comment by Saratoga-Official** [comment]
不是所有截图失败都是这个原因吧，而且加的话MAA本身就能直接重启，用不着提醒

**Comment by pu4ers** [comment]
> 不是所有截图失败都是这个原因吧，而且加的话MAA本身就能直接重启，用不着提醒

可以在“完成后”选项中加一个“重启当前MAA”；
另外，其实托盘图标里不是很好点出来（任务栏有收起托盘图标），可以把重启MAA选项也加到主UI里吗。
