### ISSUE TITLE
建议：增加在MAA完成任务后切换到其他配置的选项

### ISSUE THREAD

**Issue by gorougaru** [MaaAssistantArknights/MaaAssistantArknights#10117]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

可以让MAA在完成大号的日常后接着去做小号的日常
<img width="175" alt="image" src="https://github.com/user-attachments/assets/86829512-e51a-4acd-a2f2-354725dc0866">

**Comment by Saratoga-Official** [comment]
#9751
