### ISSUE TITLE
IS4 encounter  recognition failure

### ISSUE THREAD

**Issue by reb1rthgamer** [MaaAssistantArknights/MaaAssistantArknights#10112]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [ ] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

makes no move when on events 

### Version

Resource Version: Here A People Sows
UI Version: v5.5.11452
Core Version: v5.5.11452

### Log files

[gui.log](https://github.com/user-attachments/files/16510221/gui.log)
[asst.log](https://github.com/user-attachments/files/16510222/asst.log)

ln63152 in gui is when the problem started 

### Configuration information

blue stacks 5.21.212.1027 p64 1920x1080 320dpi 60fps
windows

**Comment by Constrat** [comment]
>  I have checked the latest beta update and there is no mention of the bug being fixed.
Did not check
