### ISSUE TITLE
集成战略部分关卡部署逻辑不正确

### ISSUE THREAD

**Issue by YipKei** [MaaAssistantArknights/MaaAssistantArknights#1011]
![com hypergryph arknights_Screenshot_2022 06 28_10 03 58](https://user-images.githubusercontent.com/53115298/176077042-43786d6e-0235-4b93-b279-1b90c82a4daf.png)

如图，顺序是：
山 -> 安塞尔 -> 梓兰 -> 可颂 -> 三星医疗 -> 凯尔希 -> M3

建议多写一套逻辑，对图进行分类，一类是开局单路，一路是双路的

双路地图则将次要路线的阻挡部署顺序提前

除此之外，山和重装的部署逻辑似乎也有问题（山会部署在重装后面，部分地图会导致超时），不知道能不能解决

**Comment by MistEO** [comment]
现在部署逻辑全改了，先关了（
