### ISSUE TITLE
萨卡兹肉鸽战斗完成后获得灵感不点击“NEXT”

### ISSUE THREAD

**Issue by curtin18** [MaaAssistantArknights/MaaAssistantArknights#10123]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

肉鸽战斗关卡，战斗完成阶段 弹出“驱城 灵感”窗口，MAA不识别，反复点击“抉择”下的选择
手动点击NEXT可继续操作

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

出现时间2024-08-07 11:10，战斗完成之后
[debug.zip](https://github.com/user-attachments/files/16518171/debug.zip)

### 配置信息

MUMU12 1920x1080 （DPI 280） 60帧
操作系统 Windows11
mumu截图增强已开启
GPU加速未开启

### 截图

![}XG W13FYEF1Y)7`{OE}@OA](https://github.com/user-attachments/assets/fbe18905-272b-4024-b6e7-b0d287af5ebf)

**Comment by Daydreamer114** [comment]
maybe fixed by #10109

**Comment by Daydreamer114** [comment]
@Lancarus 我看不懂getdrops怎么写的，你看一下closecollectionclose和closecollectioncontinue加在哪里合适

**Comment by Daydreamer114** [comment]
issue 发布至今修复过类似的问题，若仍出现问题，可发布新的 issue
