### ISSUE TITLE
肉鸽选人建议选6星加3星组合，而不是2个等级不高的5星

### ISSUE THREAD

**Issue by hkp1995** [MaaAssistantArknights/MaaAssistantArknights#1012]
我近卫有精二60级的山，棘刺，42，银灰，辅助有精一55的梓兰，其它辅助都是1级。每次选人的时候，都选的近卫阿米娅+1级初雪+155安塞尔。漏怪次数很多。建议优化算法，选择山或者棘刺，加155的梓兰，可能胜率会高些。

**Comment by MistEO** [comment]
优先是选山的，可能是识别错了，来个 bug report 吧

**Comment by YipKei** [comment]
请附带log
正常状态下你这配置选人应该会优先选山的
另外，你的剑兔是不是等级比山高
