### ISSUE TITLE
今天发现的一个事

### ISSUE THREAD

**Issue by vandark-9527** [MaaAssistantArknights/MaaAssistantArknights#10135]
### 说说你遇到的问题？

maa如果选择无人机用途：贸易站-龙门币，贸易站选择：谈判策略-龙门商法，当有源石订单且土块为空的时候，无人机加速这个操作不会生效……
这情况正常吗）

**Comment by Saratoga-Official** [comment]
目前maa如果识别到无法交付的订单就会不使用加速
