### ISSUE TITLE
企鹅物流上传超时反馈（存疑）

### ISSUE THREAD

**Issue by AbyssAzrael** [MaaAssistantArknights/MaaAssistantArknights#10137]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

运行完任务后会有约半分钟的无动作时间，然后再运行下一个项目，已出现多次
常出现于自动公招与购物，刷理智与领取奖励 的衔接之间
看了一眼log应该是上传企鹅物流超时
retrying... | why: Connection timed out after 10002 milliseconds status_code: 0

### Version

资源版本：太阳甩在身后
界面版本：v5.5.11452
核心版本：v5.5.11452

### 日志文件

[asst.log](https://github.com/user-attachments/files/16534730/asst.log)
[gui.log](https://github.com/user-attachments/files/16534731/gui.log)

### 配置信息

mumu模拟器12 分辨率720p

### 截图

![QQ图片20240808060412](https://github.com/user-attachments/assets/9b64f905-a6fa-4931-8e76-bfa62f0ce434)
![QQ图片20240808061317](https://github.com/user-attachments/assets/8b110c4d-40fe-4600-bba1-9c4658d2594c)

**Comment by Saratoga-Official** [comment]
#9849
