### ISSUE TITLE
地图宽高比导致ui偏移，MAA无法释放技能

### ISSUE THREAD

**Issue by d542Bb** [MaaAssistantArknights/MaaAssistantArknights#10136]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

-加个动作类型，比如按分辨率比例位置进行点击操作？

### 其他内容

略微向下偏移的
<img width="640" alt="41681d12a1838fa6755a44edcae7d6b" src="https://github.com/user-attachments/assets/a06b26c5-2e04-4a68-ab9c-2d4c4ce37508">
正常的
<img width="640" alt="a57b9e8b0c51dc61afc9bcd38eb674b" src="https://github.com/user-attachments/assets/1326f5c8-60db-40fd-8aef-d22c2551e4f9">

**Comment by Saratoga-Official** [comment]
#9923
