### ISSUE TITLE
【MAC端】萨卡兹肉鸽刷源石锭会卡住无法进入商店

### ISSUE THREAD

**Issue by Chal1ce** [MaaAssistantArknights/MaaAssistantArknights#10146]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

- 从MAC端5.5.1正式版本开始，选择萨卡兹肉鸽 刷源石锭模式就会卡在点击诡异行商这个页面，不会点击右下角的进入。
- 回退到之前的版本和之前的测试版本，则没有出现上述问题

### Version

v5.5.11452

### 日志文件

文件只有这四行，并且只有这个文件，没有gui.log

[asst.log](https://github.com/user-attachments/files/16537859/asst.log)

### 配置信息

模拟器：playcover
操作系统：MacOS

### 截图

![2024-07-30_20-56-51-374_raw](https://github.com/user-attachments/assets/ab411085-09bd-4836-b556-7d126ecc0e04)

**Comment by Daydreamer114** [comment]
这个需要你尝试复现一下并上传你的log，现在这样连你为什么卡住都不知道

**Comment by Daydreamer114** [comment]
Please reopen the issue after reproducing the bug and uploading the log.
