### ISSUE TITLE
公招操作异常点击

### ISSUE THREAD

**Issue by NishikiAsumi0** [MaaAssistantArknights/MaaAssistantArknights#10149]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

公招的时候有概率误点击停止招募导致后面流程全部卡住

![image](https://github.com/user-attachments/assets/5df2ae86-6667-4657-8318-6215a62800a2)
![image](https://github.com/user-attachments/assets/f7c9f1c9-a8ac-4323-9bb2-b6582685fcc9)

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[gui.log](https://github.com/user-attachments/files/16541993/gui.log)
[asst.log](https://github.com/user-attachments/files/16541994/asst.log)

### 配置信息

Mumu12 v4.0.0(3179) 1280*720 240DPI 60FPS
Windows 11 企业版 23H2 22631.3880
开启增强
关闭GPU加速

**Comment by ayhhyhh** [comment]
同样遇到了这个问题。
![误点停止招募](https://github.com/user-attachments/assets/c181fb0b-7bb8-48be-b309-92d3f3010083)

日志文件
[asst.log](https://github.com/user-attachments/files/16714719/asst.log)
[gui.log](https://github.com/user-attachments/files/16714721/gui.log)

配置信息
MUMU V3.0.30(3010) 1280*720(240DPI)
Windows 11 64-bit Kernel 10.0.22631
开启MUMU截图增强
关闭GPU加速

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

**Comment by ABA2396** [comment]
[v5.6.0-beta.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v5.6.0-beta.1) fixed

**Comment by Book-fall2wish** [comment]
5.6.0-beta.1的确已解决
