### ISSUE TITLE
无法正确定位AS系列关卡

### ISSUE THREAD

**Issue by SHthemW** [MaaAssistantArknights/MaaAssistantArknights#10144]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在进入自动战斗时, 若选择AS系列关卡, MAA会在进入选关卡界面后先将视野拉到最右侧, 然后拉回最左侧, 最后不再移动.
此时若手动拖动屏幕定位到要打的关卡, 则MAA可以自动选中它并开始游戏.

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[asst.log](https://github.com/user-attachments/files/16537037/asst.log)
[gui.log](https://github.com/user-attachments/files/16537040/gui.log)

### 配置信息

win11 mumu12模拟器 120hz
未开启gpu推理和截图增强.

**Comment by Saratoga-Official** [comment]
提供一下模拟器分辨率

**Comment by status102** [comment]
MAA暂不支持超过2k的分辨率 `2160x3840`

**Comment by Saratoga-Official** [comment]
还是竖屏分辨率，改成横屏的
