### ISSUE TITLE
自動戰鬥時跳過劇情

### ISSUE THREAD

**Issue by XuQingTW** [MaaAssistantArknights/MaaAssistantArknights#10158]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

我原本是想開始戰鬥後如果沒有檢測到UI介面檢查有沒有skip要跳過劇情
以及戰鬥結束的介面出來前檢查有沒有skip

**Comment by Saratoga-Official** [comment]
本来就是有跳过剧情啊，如果没跳过是bug，提一个bugissue
