### ISSUE TITLE
【识别错误】干员[逻各斯]无法识别

### ISSUE THREAD

**Issue by Agnes4m** [MaaAssistantArknights/MaaAssistantArknights#10164]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

资源文件到我发这个信息为止也是更新仓库最新的，都发现到无法识别干员的情况，仅逻各斯一个。
**而且检查过cache文件里头像是对应无误的**，因此我并不知道是哪里出了问题导致识别错误。具体看下面截图

### Version

5.5.11452

### 日志文件

[asst.log](https://github.com/user-attachments/files/16555528/asst.log)
[gui.log](https://github.com/user-attachments/files/16555533/gui.log)

### 配置信息

windows10，雷电模拟器9，安卓9.0，64位
GPU核显加速（i7-11800H）

### 截图

![image](https://github.com/user-attachments/assets/61fd2251-df38-4e68-ae83-edb8b95b8dfb)
![image](https://github.com/user-attachments/assets/1a31b773-6ccd-4226-a81b-06403febf68f)

**Comment by Daydreamer114** [comment]
自动编队是ocr文字识别

**Comment by Daydreamer114** [comment]
```python
[2024-08-09 11:17:09.784][TRC][Px5224][Tx5a14] asst::WordOcr [{ 各斯: [ 0, 0, 63, 21 ], score: 0.930143 }] by OCR Rec , cost 329 ms
[2024-08-09 11:17:09.784][TRC][Px5224][Tx5a14] Proceed [{ 各斯: [ 878, 318, 63, 21 ], score: 0.930143 }]
```

**Comment by Saratoga-Official** [comment]
gpu加速关了呢，OCR识别问题可能是这个导致的

**Comment by Agnes4m** [comment]
关闭gpu加速后已正常使用，感谢
