### ISSUE TITLE
【MAC端】萨卡兹肉鸽刷源石锭，无法进入商店

### ISSUE THREAD

**Issue by Chal1ce** [MaaAssistantArknights/MaaAssistantArknights#10160]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

- 从MAC端5.5.1正式版本开始，选择萨卡兹肉鸽 刷源石锭模式就会卡在点击诡异行商这个页面，不会点击右下角的进入。
- 回退到之前的版本和之前的测试版本，则没有出现上述问题

### Version

v5.5.11452

### 日志文件

差不多2024-08-09 02:28:18 到最后一行

[asst.log](https://github.com/user-attachments/files/16552066/asst.log)

### 配置信息

Playcover
1920x1080
MacOS

### 截图

- 下图为MAA Debug文件夹肉鸽包里的截图
![2024-07-30_20-56-53-775_raw](https://github.com/user-attachments/assets/11b86ac4-8826-48d1-90bd-0f8df7d79854)

- 下图为卡住关卡位置截图
![iShot_2024-08-09_02 38 08](https://github.com/user-attachments/assets/01fe49dc-8f90-4c84-bf5d-9907a49fca69)

-下图为maa运行界面
![iShot_2024-08-09_02 38 14](https://github.com/user-attachments/assets/5abd1ad5-e603-40cf-a861-e11bfd8b5d2c)

**Comment by Saratoga-Official** [comment]
[2024-08-09 02:28:18.063][TRC][Px145d3][Txdb58] match_templ | Sarkaz@Roguelike@StageTraderEnter.png score: 0.784675 rect: [ 1054, 482, 200, 84 ] roi: [ 1035, 370, 226, 300 ]
出发前往的识别度只有0.78左右，0.8才能通过

**Comment by Saratoga-Official** [comment]
[2024-08-09 02:28:18.063][TRC][Px145d3][Txdb58] match_templ | Sarkaz@Roguelike@StageTraderEnter.png score: 0.784675 rect: [ 1054, 482, 200, 84 ] roi: [ 1035, 370, 226, 300 ]
出发前往的识别度只有0.78左右，0.8才能通过

**Comment by Daydreamer114** [comment]
<img width="513" alt="截屏2024-08-11 01 24 01" src="https://github.com/user-attachments/assets/a69d0579-ede9-4292-bfe0-64314f957420">
不动教程以外的设置的话，这个配置可以以0.8143的分数通过

[asst.log](https://github.com/user-attachments/files/16570396/asst.log)
在商店只有0.81的分数，在不期而遇却有0.95的分数，怎么汇市呢
cc @zzyyyl

**Comment by Chal1ce** [comment]
> <img alt="截屏2024-08-11 01 24 01" width="513" src="https://private-user-images.githubusercontent.com/74444214/356827291-a69d0579-ede9-4292-bfe0-64314f957420.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMzk2NjksIm5iZiI6MTcyMzMzOTM2OSwicGF0aCI6Ii83NDQ0NDIxNC8zNTY4MjcyOTEtYTY5ZDA1NzktZWRlOS00MjkyLWJmZTAtNjQzMTRmOTU3NDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDAxMjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOTBkNjBjMTdjODQ4OTkxMzk5MWIyMjA0NGJmNjQ5MGRlMzY5OTkyOGFkYmQ1NTZkNjk4Y2Q5ZWU0YzY5MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LxzLnyUov_dPXe9dA2_MlQTBLGeJEVbyPIz-pKC26Qc">
> 不动教程以外的设置的话，这个配置在M2 max可以以0.8143的分数通过 其实没什么解决方法，不会为了一个样本去降识别要求的分数 @Chal1ce
> 
> [asst.log](https://github.com/user-attachments/files/16570396/asst.log) 在商店只有0.81的分数，在不期而遇却有0.95的分数，怎么汇市呢 cc @zzyyyl

OK，我去看一下，因为那些设置我都是默认设置
