### ISSUE TITLE
[EN server] Phantom IS getting stuck at Encounter when 0 hope 傀影肉鸽卡如果0希望会卡在需要希望的不期而遇 

### ISSUE THREAD

**Issue by lirao** [MaaAssistantArknights/MaaAssistantArknights#10161]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

傀影肉鸽里，会优先选第一个选项，如果第一个选项没法选(0hope)，就不会选第二个继续了
In Phantom, Encounter will prefer the top choice, but when the top choice is unselectable because I have 0 hope, MAA is unable to proceed.
![2024-08-08_13-28-27-349_raw](https://github.com/user-attachments/assets/de85a44b-b724-4643-9d65-542a3fbbded6)

### Version

Resource Version: Here A People Sows
UI Version: v5.5.11452
Core Version: v5.5.11452

### Log files

[asst.bak.log](https://github.com/user-attachments/files/16553173/asst.bak.log)
[gui.log](https://github.com/user-attachments/files/16553174/gui.log)

### Configuration information

Bluestacks 5.13 Windows 10 
240 dpi 1920x1080 30fps

**Comment by HX3N** [comment]
duplicate #10088 

Please download [this file](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/global/YoStarEN/resource/tasks.json) and  place it in the `/resource/global/YostarEN/resource/`

**Comment by Constrat** [comment]
But this is strange. `v5.5.11452` should already have `.*Reprieve.*` no?

**Comment by Constrat** [comment]
Wow navigating the git blame is now impossible with all the stupid code formatting in between.
We should somehow automate the https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/.git-blame-ignore-revs to add the pre-commit blames

**Comment by Constrat** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/5c0825328cc1bee32336b2062c678e5d86a1d8e3/resource/global/YoStarEN/resource/tasks.json#L1961

This is the line when the tag was released

**Comment by HX3N** [comment]
It seems to be because the following `ocrReplace` was included in version v5.5.11452.

**Comment by Constrat** [comment]
Oh yeah the stupid error I made lmao.
That's why I forgot it
