### ISSUE TITLE
[Feature Request] "Speed" Option in Auto Battle like IS

### ISSUE THREAD

**Issue by ItsukaHiro** [MaaAssistantArknights/MaaAssistantArknights#10165]
### Before raising the issue...

- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I'm probably sure this is a new feature/suggestion and not a bug encountered (please attach logs if you're not sure)

### The problems you have encountered?

After using MAA for a while, I found that normally the screenshot time take a round 200~300ms.
Beside, Deploy in Pause trick only actually work in 1X Speed ingame (sometimes)

### Any good ideas?

Allow users to choice perform battle in "1X" or "2X" Speed. 2X for people need fast afk, while 1X for who want more accurate automated gameplay (idk who really think like that, but... it should be a option)

**Comment by Constrat** [comment]
The screenshot time is completely related to your machine only. So 200-300ms is not indicative. Some users may easily have over 1000 and other users using MuMu Enhanced are as low as 5ms.

Allowing to choose a speed will only increase discrepancies in runs as what MAA is doing is already hard enough: clearing stages in I.S.
The increase in speed will not drastically reduce the time for runs I think we can talk about a ~25% max. Meanwhile it will increase the risk of error by a higher degree leading to more failed runs.

**Comment by Daydreamer114** [comment]
For Copilot, who wrote the "homework" decide the speed. You can download the JSON file and delete this part for your own use.
![image](https://github.com/user-attachments/assets/58ccc81f-596a-4b83-9f8e-6f1fb48fab9b)
![image](https://github.com/user-attachments/assets/6fe0660f-0271-478f-b4ae-ea44a5a4d80a)

200-300ms is enough for roguelike.
