### ISSUE TITLE
mumuextras未生效

### ISSUE THREAD

**Issue by Kalta-yurri** [MaaAssistantArknights/MaaAssistantArknights#10162]
### 说说你遇到的问题？

未开启后台保活，填了路径，可是仍显示mumuextras未生效
![Image_1723165679567](https://github.com/user-attachments/assets/2ee40589-1358-4802-829e-b51c2b00f590)
![Image_1723165683319](https://github.com/user-attachments/assets/6e9fdbb0-3ada-44e2-ace1-6098aada62a4)

**Comment by HoshinoAyako** [comment]
请重新检阅一遍文档。
![Screenshot_2024-08-09-10-19-58-294_com microsoft emmx-edit](https://github.com/user-attachments/assets/8e41720e-68cb-466d-a4a2-b9387c364ba2)

![Screenshot_2024-08-09-10-18-23-431_com microsoft emmx-edit](https://github.com/user-attachments/assets/a1f10845-6b38-4e5e-ad4b-ed6f4bc023e1)
