### ISSUE TITLE
萨卡兹肉鸽战斗失败后模拟器退回主界面（可能闪退？

### ISSUE THREAD

**Issue by atkdefender** [MaaAssistantArknights/MaaAssistantArknights#10168]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题如图，发生在10点半am左右

### Version

资源版本 太阳甩在身后
界面版本 v5.5.11452
核心版本 v5.5.11452

### 日志文件

[gui.log](https://github.com/user-attachments/files/16556334/gui.log)
[asst - 副本.zip](https://github.com/user-attachments/files/16556336/asst.-.zip)

### 配置信息

Win10

### 截图

![QQ截图20240809130650](https://github.com/user-attachments/assets/5c74dc7a-9b34-4101-9fe8-1089238a25c9)

**Comment by HoshinoAyako** [comment]
mumu方面的问题。长时间游玩肉鸽模式，会自动闪退。
![Screenshot_2024-08-09-17-38-30-352_com microsoft emmx](https://github.com/user-attachments/assets/e24d5d6c-2aec-4b35-aa90-2e42b865e903)
