### ISSUE TITLE
[JP] Auto battle cant use memory item Potion

### ISSUE THREAD

**Issue by wallsman** [MaaAssistantArknights/MaaAssistantArknights#10172]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

After the state of no reason, the operation is canceled by itself at the selection screen and the operation is terminated.
![スクリーンショット 2024-08-09 21 52 51](https://github.com/user-attachments/assets/9ddd94d2-5c10-485c-9de0-f73bb17daacf)

### Version

Resource Version: 懐黍離
UI Version: v5.5.11452
Core Version: v5.5.11452

### Log files

[asst.log](https://github.com/user-attachments/files/16561424/asst.log)
[gui.log](https://github.com/user-attachments/files/16561444/gui.log)

### Configuration information

Mumu12 V3.8.29 / 1600*900 210DPI / Screenshot Enhance
Windows10

**Comment by ABA2396** [comment]
I think you can take this in advance because MAA doesn't recognize this shape of the medicine. Since it will expire, there's no need to keep it as a memento.

**Comment by Constrat** [comment]
![image](https://github.com/user-attachments/assets/38b9ece2-d015-401d-a9fc-cdde32acafef)
This is UseMedicine.png

**Comment by ABA2396** [comment]
Manual use)

**Comment by wallsman** [comment]
Ah,OK.
use it.

**Comment by Constrat** [comment]
I think we should be able to pull those items from the ResourceUpdater?

**Comment by wallsman** [comment]
If the data update itself is done automatically, is only the image data needed? (Was the image updated automatically as well?)

I think we can use the distributed items as soon as they are distributed, but people who don't know about them may get hooked on them as well, so I think that is a possible response.

**Comment by Constrat** [comment]
No no, this is not in the current resource. This is directly from the gamedata dir. We filter a lot of stuff from those dirs. They are 112MB for official and 101 for Global

**Comment by Constrat** [comment]
![image](https://github.com/user-attachments/assets/98ce8f13-ea79-43e3-a854-a705d4ea1ae8)
In the Maa/Resource it seems we stopped pulling them.

**Comment by Constrat** [comment]
@ABA2396 Should we reallow them?

**Comment by Constrat** [comment]
I think the items being in the resource/items dir is a mistake. We never changed the prefix in the resourceupdater.

**Comment by Manicsteiner** [comment]
I know what happened now. These special medicine have too many white patches on them, causing text recognition failures.
Just change these fields will make MAA use these special medicine, at least for this cake.
![图片](https://github.com/user-attachments/assets/9bea67d1-cf52-4114-82ad-97f20aef3408)
![图片](https://github.com/user-attachments/assets/8c42fca3-bc92-449c-8e64-b660eac47c03)

logs: first time no changes, second time with 230/200, third time 250/230 and worked
[asst - 副本.log](https://github.com/user-attachments/files/16594006/asst.-.log)
[gui - 副本.log](https://github.com/user-attachments/files/16594008/gui.-.log)

**Comment by status102** [comment]
![image](https://github.com/user-attachments/assets/4fc573b5-48d4-4b21-8ce1-875b1f3e5975)

看上去是因为外服没有蓝色遮罩

**Comment by Manicsteiner** [comment]
> 看上去是因为外服没有蓝色遮罩

哦流啤还能有这种问题的

**Comment by status102** [comment]
cc @Constrat and add it to EN if same thing happens on EN client

**Comment by Constrat** [comment]
@status102 This is strange. I'm having a similar problem, but the blue is correct I think, on both type of medicines
![image](https://github.com/user-attachments/assets/a9036ff0-f9b7-4102-9d03-1cd038ecbf67)

**Comment by Constrat** [comment]
I'm retarded I didn't activate the use of sanity option, but there's a reason.
The GUI is inconsistent. Battle List automatically enables Auto Squad, but after that, you can manually disable autosquad and the Copilot will still work (with the last used squad).
But in this environment the Use of Sanity will not work. (The log shows no UseMedicine subtask)

**Comment by Manicsteiner** [comment]
当前日服仍不能自动使用常规的理智药，固定识别为T，调整maskrange也只会使其识别为其他字母，如“E”、“PT”等。
目前建议为"NumberOcrReplace"添加替换：["T", "1"]
![pic1](https://github.com/user-attachments/assets/618f0568-dcfd-4d5e-bd5d-d16cd89e2b44)

```
[2024-08-17 11:48:35.597][TRC][Pxc78][Tx11b4] asst::MedicineCounterTaskPlugin::_run | leave, 820 ms
[2024-08-17 11:48:35.597][TRC][Pxc78][Tx11b4] ready to sleep 500
[2024-08-17 11:48:36.099][TRC][Pxc78][Tx11b4] end of sleep 500
[2024-08-17 11:48:36.099][TRC][Pxc78][Tx11b4] asst::MedicineCounterTaskPlugin::_run | enter
[2024-08-17 11:48:36.522][INF][Pxc78][Tx11b4] Call ` adb -s emulator-5554 exec-out "screencap | gzip -1" ` ret 0 , cost 423 ms , stdout size: 2998463 , socket size: 0
[2024-08-17 11:48:36.565][TRC][Pxc78][Tx11b4] multi_match |  result: [{ rect: [ 765, 215, 28, 26 ], score: 0.998703 }] roi: [ 750, 200, 500, 50 ]
[2024-08-17 11:48:36.665][TRC][Pxc78][Tx11b4] asst::CharOcr [{ T: [ 0, 0, 56, 61 ], score: 0.143284 }] by OCR Rec , cost 99 ms
[2024-08-17 11:48:36.665][TRC][Pxc78][Tx11b4] Proceed [{ T: [ 693, 241, 56, 61 ], score: 0.143284 }]
[2024-08-17 11:48:36.718][TRC][Pxc78][Tx11b4] asst::CharOcr [{ 2: [ 0, 0, 15, 21 ], score: 0.999691 }] by OCR Rec , cost 53 ms
[2024-08-17 11:48:36.718][TRC][Pxc78][Tx11b4] Proceed [{ 2: [ 754, 308, 15, 21 ], score: 0.999691 }]
[2024-08-17 11:48:36.718][ERR][Pxc78][Tx11b4] asst::MedicineCounterTaskPlugin::init_count unable to convert ocr result to int, use: T , inventory: 2
[2024-08-17 11:48:36.719][TRC][Pxc78][Tx11b4] asst::MedicineCounterTaskPlugin::_run | leave, 620 ms
```

**Comment by status102** [comment]
这个能不能跟外服说说，已经影响到正常用户的使用了甚至。很难看清数字

**Comment by Manicsteiner** [comment]
Finally...
![Screenshot_1728635892](https://github.com/user-attachments/assets/7554a365-4288-4cc4-99f2-b359b0086719)
