### ISSUE TITLE
能否在连战次数的选项中增加自动最大的选项？

### ISSUE THREAD

**Issue by TieHuan** [MaaAssistantArknights/MaaAssistantArknights#10171]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

在日常使用中，为了确保理智刷空必须把连战次数设为1，但这增加了耗时，设置较大的连战数可能导致理智剩余过多（有时早上起来还没够6次连战）

### 有什么好的想法？

能否根据设置（是否使用体力药，源石）来智能选择连战次数（如当连战次数为自动时，根据设置选择带蓝色+的连战次数，或选择不带蓝色+的最大等）

**Comment by Constrat** [comment]
The time consumption wasted is next to none since MAA already starts it for you.
Using both MAA and the "new" feature doesn't really make any sense.
That feature was basically added as a "MAA-alternative" directly from HG
