### ISSUE TITLE
（win11版）在萨卡兹肉鸽刷等级时，发现MAA在”讲述者列表“处反复循环重开。

### ISSUE THREAD

**Issue by Libra-yuri** [MaaAssistantArknights/MaaAssistantArknights#10176]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

在萨卡兹肉鸽刷等级的时候，发现MAA在”讲述者列表“处反复循环重开。
具体表现为：在一局萨卡兹肉鸽结束后，MAA主动点击左侧的”讲述者列表“，并且启动了新一轮肉鸽，然后自动退出，重新开始，然后自动退出，重新开始，反复循环。

### Version

资源版本：太阳甩在身后
UI版本：V5.5.11452
核心版本：V5.5.11452

### 日志文件

[gui.log](https://github.com/user-attachments/files/16562035/gui.log)
直接拉到文件最下端可见描述的内容
[asst.log](https://github.com/user-attachments/files/16563305/asst.log)

### 配置信息

DELL笔记本电脑配置：
系统：win11（64x）
版本号：23H2
操作系统版本：22631.3880
处理器：12th Gen Intel(R) Core(TM) i5-12500H   2.50 GHz
显卡：NVIDIA GeForce RTX 3050 Ti Laptop GPU

使用MUMU模拟器12
模拟器分辨率：1600x900
帧率：60
未启动MUMU截图增强模式
MAA未使用GPU加速推理
[gui.json](https://github.com/user-attachments/files/16563318/gui.json)

### 截图

![2024-08-09_21-38-15-604_raw](https://github.com/user-attachments/assets/a2df0a70-3c7b-442b-b6b7-e00f446c60eb)
以上内容为debug文件中的截图，其中萨卡兹肉鸽主页面的截图文件名带有error字符
![屏幕截图 2024-08-09 214801](https://github.com/user-attachments/assets/62bbd21f-584e-4977-ad68-ac1e87682c3a)
这个是游戏外对MAA的截图

### 还有别的吗？

之前使用MAA刷源石锭时能够正常稳定运行，但是刷等级时经常卡在”讲述者列表“页面需要重新启动。重新启动MAA和更新配置文件均无法解决该问题，在正常运行1-5局游戏后便会进入该状态

**Comment by Libra-yuri** [comment]
![2024-08-09_21-33-11-185_Page2_Error](https://github.com/user-attachments/assets/cacd46d2-d4c4-4d8a-815f-59bd187e3e80)
![2024-08-09_21-34-24-067_raw](https://github.com/user-attachments/assets/18752321-f800-4cea-9114-c2377f109bd3)
补充图片

**Comment by Daydreamer114** [comment]
是maa选的讲述者列表还是你选的讲述者列表？

**Comment by Daydreamer114** [comment]
尝试一下重新在GitHub下载maa并运行？

**Comment by Daydreamer114** [comment]
我没能理解为什么这里不做识别而是直接点
把rect缩到~, ~, ~, 10就不会点进讲述者了
![image](https://github.com/user-attachments/assets/4dbad586-81d7-4a93-bfdc-09329d6aab48)
