### ISSUE TITLE
完成后选项 “仅一次” 说明不清

### ISSUE THREAD

**Issue by kiry-b2** [MaaAssistantArknights/MaaAssistantArknights#10175]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

![QQ20240809-223304](https://github.com/user-attachments/assets/a0577d4a-c21e-4509-82f4-1113df8fab03)
更新前的任务完成后选择“仅一次关机”，那么关机完的下一次打开就会恢复“无操作”；而更新之后选择“仅一次关机”则下一次打开只是把“仅一次”的勾去掉了，仍然会保留“关机”的选项，那“仅一次”的意义在哪里呢？

### 有什么好的想法？

恢复旧版或者让“仅一次”执行完之后清除所有勾选

**Comment by ABA2396** [comment]
先选 仅一次，之后的修改不会保存。没选 仅一次 的时候，其他的选项是变了就保存。

**Comment by ABA2396** [comment]
而且原来的逻辑也不是你说的恢复“无操作”，而是不保存那次的修改，比如你之前选的是退出模拟器，跑完仅一次关机之后也是变成退出模拟器。

现在仅一次确实没什么提示，感觉得加个明显点的教学 @status102

**Comment by status102** [comment]
> 而且原来的逻辑也不是你说的恢复“无操作”，而是不保存那次的修改

那给仅一次的tooltip多写点（看不看就不知道了

**Comment by status102** [comment]
> 更新前的任务完成后选择“仅一次关机”，那么关机完的下一次打开就会恢复“无操作”

这个行为已经在N个版本前被修改掉了，除非你在切换成`关机(仅一次)`之前选择的是`无动作`

**Comment by status102** [comment]
![image](https://github.com/user-attachments/assets/4cdf79e0-8aba-49d4-9926-f17f9bd6f3c6)
