### ISSUE TITLE
基建设置中入驻心情阈值调整为按剩余工作时间近似值换班

### ISSUE THREAD

**Issue by YipKei** [MaaAssistantArknights/MaaAssistantArknights#1017]
提供一个开关和一个时间选项。

## 动态心情阈值
通过时间选项和内置的可工作时长动态计算心情阈值，对不同的组合执行不同的换班。

反正意思就是3个人上班的设施心情消耗速度一般为0.65，两个人上班的设施心情消耗速度一般为0.70
然后发电站为0.75，中枢取决于你上的什么干员，最大0.75，最小-0.05

然后期望心情阈值的计算方式是：剩余工作时间×心情消耗速度÷24
一个参考例子：
设置为8小时——
发电换班阈值：8 × 0.75 ÷ 24＝25%
三人普通制造站：8 × 0.65 ÷ 24＝21.7%
红云组制造站：8 × 0.4 ÷ 24＝13.3%

此前如果要确保除发电外换班正常，就只能设置22%的有阈值，导致部分组合在线时间较短（虽然我个人觉得是这些长效组合的收益反而会变低，但有人就是喜欢压榨呢？）

如果额外进行排序的话，因为要进行大量额外的截图判断，效率反而会变低吧。
不过说到底，按换班时间显然比现在的按心情阈值更符合直觉。

## 心情对齐锁

再加个开关选择是否对齐普通换班就好了——打开按钮之后，长班会统一到标准班的换班时间。
如果玩家的长班效率比标准班低的时候打开这个选项可以提升平均的收益，避免长班赖着不走，也可以避免因为班次不对齐导致的炸班现象。

开启选项之后，MAA先反向计算标准班的在班时间，然后将在班时间设置为长班的在班时间，再反推出长班的换班阈值

同样是例子：
设置为8小时时：
普通制造站换班阈值21.7% -> 标准班在班时间28.9小时
长班在班阈值：28.9 × 0.4 ÷ 24＝48.2%
长班换班阈值：100% - 48.2%＝51.8%

**Comment by ABA2396** [comment]
现在还折腾基建的估计都是用自定义了，玛丽估计也不会想改基建.jpg
