### ISSUE TITLE
mac 端自动战斗编队时报错

### ISSUE THREAD

**Issue by chesha1** [MaaAssistantArknights/MaaAssistantArknights#10187]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

对新活动进行自动战斗时，编队时报错

对老关卡正常

### Version

v5.5.11452

### 日志文件

[asst.log](https://github.com/user-attachments/files/16569732/asst.log)

### 配置信息

macos + playcover

### 截图

<img width="1012" alt="image" src="https://github.com/user-attachments/assets/54444b4a-91bc-42e1-a937-78762484a198">

### 还有别的吗？

之前自动战斗根本无法开始，在手动更新资源后，可以开始，但是在自动编队时报错，过程 #10170 

感觉应该和本 issue 没什么关系，但是时间顺序上是 #10170 后发生了本 issue

**Comment by Saratoga-Official** [comment]
看log似乎是maa在切换术师职业没有切换成功，还是近卫职业找了半天逻各斯和小羊找不到报错了

**Comment by Saratoga-Official** [comment]
可以给我录个视频吗，编队的全过程，我看有没有什么影响因素

**Comment by chesha1** [comment]
> 可以给我录个视频吗，编队的全过程，我看有没有什么影响因素

视频如下：
https://virworks-my.sharepoint.com/:v:/g/personal/chesha1_virworks_onmicrosoft_com/EcPSwyn54C1AmsSbyqd4Ab4BHvP3wiYUvBErPHDDzLgyNA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=NVHcDi

**Comment by Saratoga-Official** [comment]
> > 可以给我录个视频吗，编队的全过程，我看有没有什么影响因素
> 
> 视频如下： https://virworks-my.sharepoint.com/:v:/g/personal/chesha1_virworks_onmicrosoft_com/EcPSwyn54C1AmsSbyqd4Ab4BHvP3wiYUvBErPHDDzLgyNA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=NVHcDi

请附上新的asstlog

**Comment by chesha1** [comment]
@Saratoga-Official 因为自动战斗后我又用了一下 maa，所以自动战斗的日志和别的混在一起不好找了，我就又录了一份新的仅仅包含自动战斗的日志和录屏的文件：https://virworks-my.sharepoint.com/:f:/g/personal/chesha1_virworks_onmicrosoft_com/EggerF13AFxHpX-SKfJ3a4YBUU5YWl6hl1UZ0SeQJXuZqw?e=s50CYA

**Comment by chesha1** [comment]
@Saratoga-Official 下面是一个用小羊打 1-7 的例子，可以正常选到，但是不是通过术士分类选到的，是在大类的选的

https://virworks-my.sharepoint.com/:f:/g/personal/chesha1_virworks_onmicrosoft_com/Er-nYwN0zMtEvpJwATdAn28BSZPo73Bp_fplsK56XAAmlQ?e=FWD1o4

**Comment by Saratoga-Official** [comment]
> @Saratoga-Official 下面是一个用小羊打 1-7 的例子，可以正常选到，但是不是通过术士分类选到的，是在大类的选的
> 
> https://virworks-my.sharepoint.com/:f:/g/personal/chesha1_virworks_onmicrosoft_com/Er-nYwN0zMtEvpJwATdAn28BSZPo73Bp_fplsK56XAAmlQ?e=FWD1o4

没有帮助，我需要术师分队选到的，你找个没有干员组的

**Comment by chesha1** [comment]
@Saratoga-Official MAA上是在没有现成可用的，我就自己搓了一个，看上去老关卡也没法选择到术士分类

https://virworks-my.sharepoint.com/:f:/g/personal/chesha1_virworks_onmicrosoft_com/Eqhyx4yB7fdDkaoGRZduMn0B5bGbJtZRf8zkW29_sEe8sA?e=xIhvEZ

**Comment by Daydreamer114** [comment]
@Saratoga-Official 0.781214

**Comment by Saratoga-Official** [comment]
能发一下你的明日方舟图像设置界面吗

**Comment by chesha1** [comment]
> 能发一下你的明日方舟图像设置界面吗

<img width="1012" alt="image" src="https://github.com/user-attachments/assets/13bcaa90-3d78-4c67-95f5-d1bcd20effc0">

因为 macos 不像 Windows 一样可以开启多少比例的缩放，只能在调整系统分辨率比显示器最大分辨率更小实现放大，playcover 这里的设置，如果不把分辨率改小一点，整个屏幕就放不下，这个会影响自动战斗吗？其他功能都没问题的

**Comment by Saratoga-Official** [comment]
> > 能发一下你的明日方舟图像设置界面吗
> 
> <img width="1012" alt="image" src="https://github.com/user-attachments/assets/13bcaa90-3d78-4c67-95f5-d1bcd20effc0">
> 
> 因为 macos 不像 Windows 一样可以开启多少比例的缩放，只能在调整系统分辨率比显示器最大分辨率更小实现放大，playcover 这里的设置，如果不把分辨率改小一点，整个屏幕就放不下，这个会影响自动战斗吗？其他功能都没问题的

缩放改成1.0应该就好了

**Comment by chesha1** [comment]
> > > 能发一下你的明日方舟图像设置界面吗
> > 
> > 
> > <img alt="image" width="1012" src="https://private-user-images.githubusercontent.com/49867392/356856813-13bcaa90-3d78-4c67-95f5-d1bcd20effc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjM5MDYsIm5iZiI6MTcyMzM2MzYwNiwicGF0aCI6Ii80OTg2NzM5Mi8zNTY4NTY4MTMtMTNiY2FhOTAtM2Q3OC00YzY3LTk1ZjUtZDFiY2QyMGVmZmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA4MDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYjllZWY5NTM1MmRjNzE4ODA5MmI0NzQ2ZTQzNGZjY2VlM2QxOWQ3MzU2NzY5NTQ0OGU4OGIwZGJmN2EyMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8x_mwGyUfEO3jJLSVc7t0eUarUPue265Dhw7oqCTWKw">
> > 因为 macos 不像 Windows 一样可以开启多少比例的缩放，只能在调整系统分辨率比显示器最大分辨率更小实现放大，playcover 这里的设置，如果不把分辨率改小一点，整个屏幕就放不下，这个会影响自动战斗吗？其他功能都没问题的
> 
> 缩放改成1.0应该就好了

确实好了，谢谢

**Comment by chesha1** [comment]
@Saratoga-Official 现在问题确实是解决了，但是 2.0 调成 1.0 之后变模糊了，这个能考虑修一下吗？

毕竟其他一键长草功能都正常，只有自动战斗不能选术士

**Comment by Saratoga-Official** [comment]
> @Saratoga-Official 现在问题确实是解决了，但是 2.0 调成 1.0 之后变模糊了，这个能考虑修一下吗？
> 
> 毕竟其他一键长草功能在 2.0 的时候都正常，只有自动战斗不能选术士

这个是另一个问题了，重开个issue

**Comment by Daydreamer114** [comment]
把分辨率改成1080p？

**Comment by chesha1** [comment]
现在有两种状态：
1. 1280 * 720 2倍分辨率缩放，自动战斗功能部分不正常
2. 任意分辨率的 1倍缩放，全功能正常

如果想用 maa 的自动战斗功能，确实可以手动切换一下，但是每次用自动战斗都去 playcover 里调设置也比较繁琐

为什么不调大分辨率，因为 macos 不支持 Windows 上的保持高分辨率，提高缩放比例让显示效果大一点，只能调低分辨率让整体显示大一点

因为显示器原生的分辨率就很小，1280 * 720 已经是极限了，分辨率再大点就会超出屏幕了，下图是 1280 * 720 的效果

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/0edee7d8-e2e8-4416-9d8a-a22e0f03b1b9">

**Comment by Saratoga-Official** [comment]
> 现在有两种状态：
> 
> 1. 1280 * 720 2倍分辨率缩放，自动战斗功能部分不正常
> 2. 任意分辨率的 1倍缩放，全功能正常
> 
> 如果想用 maa 的自动战斗功能，确实可以手动切换一下，但是每次用自动战斗都去 playcover 里调设置也比较麻烦
> 
> 为什么不调大分辨率，因为 macos 不支持 Windows 上的保持高分辨率，提高缩放比例让显示效果大一点，只能调低分辨率让整体显示大一点
> 
> 因为显示器原生的分辨率就很小，1280 * 720 已经是极限了，分辨率再大点就会超出屏幕了，下图是 1280 * 720 的效果
> 
> <img alt="image" width="1024" src="https://private-user-images.githubusercontent.com/49867392/356862719-0edee7d8-e2e8-4416-9d8a-a22e0f03b1b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjcxNjEsIm5iZiI6MTcyMzM2Njg2MSwicGF0aCI6Ii80OTg2NzM5Mi8zNTY4NjI3MTktMGVkZWU3ZDgtZTJlOC00NDE2LTlkOGEtYTIyZTBmMDNiMWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA5MDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNDQzYjkxMTQ0NmZiNGQ3Y2NlN2QzNTU2ZGFhOWRjZDEwYTMwZWE2YzVhOTU5ZTk0M2MyMTllMTE5OTJmNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rULcw7ZwvdRBO22JEfXt9xjvTqAam9wnDg9coKaNi2Y">

不是，你这叫模糊吗

**Comment by Daydreamer114** [comment]
<img width="1512" alt="截屏2024-08-11 17 28 18" src="https://github.com/user-attachments/assets/5a2d014f-7527-470c-b31f-d8262c1bbddc">

**Comment by chesha1** [comment]
> <img alt="截屏2024-08-11 17 28 18" width="1512" src="https://private-user-images.githubusercontent.com/74444214/356864433-5a2d014f-7527-470c-b31f-d8262c1bbddc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjkxMjEsIm5iZiI6MTcyMzM2ODgyMSwicGF0aCI6Ii83NDQ0NDIxNC8zNTY4NjQ0MzMtNWEyZDAxNGYtNzUyNy00NzBjLWIzMWYtZDgyNjJjMWJiZGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA5MzM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYjdkYTIyNGJhMDZlOTBiOTYzOGU5ZDlmOWE4MmQ2ZDMyN2YyM2ZiMGVlMWJhMTk0MTQwNGY1YTc3MGMyMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._bVaU7XZpSN0VUo9pPPdK1Nu2p7gt0JbkjMQJ52JKEI">

确实是可以在显示器本身分辨率比较大的情况下（比如你图里的 1512 * 982），明日方舟用 1080p，但是这样其他应用就会显得很小

我视力不好，显示器分辨率用的是 1024 * 666，这种情况，playcover 里的明日方舟用 1280 * 720 就已经是极限了
