### ISSUE TITLE
自动战斗 开始后显示连接错误但仍可以继续运行

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#10185]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

RT 见视频
[bandicam 2024-08-10 18-34-21-399.zip](https://github.com/user-attachments/files/16569250/bandicam.2024-08-10.18-34-21-399.zip)
点击开始之后显示连接错误 同时按键仍然为开始而非停止，但是继续运行

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11453-alpha.1.d109.g0e51aaba0
Core Version: v5.5.11453-alpha.1.d109.g0e51aaba0

### 日志文件

[asst - 副本.zip](https://github.com/user-attachments/files/16569258/asst.-.zip)
[gui - 副本.log](https://github.com/user-attachments/files/16569259/gui.-.log)

### 配置信息

[gui.json](https://github.com/user-attachments/files/16569262/gui.json)
模拟器： MuMu12
MuMu 截图增强：开启
GPU 加速推理：GTX 1650

**Comment by Saratoga-Official** [comment]
我看了下log好像没有为什么会断开的信息，前面好像都是正常运行的

**Comment by ABA2396** [comment]
我最近的一个commit应该修了

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/0e51aaba09df36d025f709519ec26275c55c56c9

**Comment by ntgmc** [comment]
> [0e51aab](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/0e51aaba09df36d025f709519ec26275c55c56c9) fixed

![image](https://github.com/user-attachments/assets/3a156fb0-7fb0-4f7e-b01d-9dfabea9b8ed)
这版本不是已经包含了这个commit吗 还是有这个问题

**Comment by Saratoga-Official** [comment]
我也触发了一模一样的问题
