### ISSUE TITLE
任务完成后连接会重置

### ISSUE THREAD

**Issue by ala-404** [MaaAssistantArknights/MaaAssistantArknights#10183]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/user-attachments/assets/05e92b17-47e2-4be8-a23d-46cc3fc783a8)

### Version

UI Version: v5.5.11453-alpha.1.d106.g290d10418
Core Version: v5.5.11453-alpha.1.d106.g290d10418

### 日志文件

[asst.log](https://github.com/user-attachments/files/16568712/asst.log)
[gui.log](https://github.com/user-attachments/files/16568713/gui.log)
从2024-08-10 13:53:34.757开始

### 配置信息

[gui.json](https://github.com/user-attachments/files/16568624/gui.json)
mumu12 1920x1080 dpi280 120帧率
截图增强开启 gpu加速推理开启
显卡3060

**Comment by ABA2396** [comment]
在外面，等下回去看

**Comment by ABA2396** [comment]
你之前用的是小工具里的公招识别吗？

**Comment by ala-404** [comment]
是的，在使用小工具的公招识别前已完成刷理智
