### ISSUE TITLE
希望添加“更新后”自定义脚本

### ISSUE THREAD

**Issue by ElluIFX** [MaaAssistantArknights/MaaAssistantArknights#10189]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

考虑到当前资源文件更新需要手动，大部分人想要实现半自动更新基本是使用类似下面的脚本

```bat
taskkill /im MAA.exe /f

@rem 某种下载命令

start MAA.exe
```

因此，允许设置一个MAA本体更新完成后的调用脚本，就可以实现完全的自动化资源更新，至少可以在自动资源更新机制修改的过渡期提供一种自动化方案

**Comment by ABA2396** [comment]
这种东西也没必要放maa的包里，QQ群里已经有传过更新的脚本文件了。真要有能力上github我觉得自己写个更新脚本也不是什么难事吧
