### ISSUE TITLE
更新资源文件的方法

### ISSUE THREAD

**Issue by tsctsc6** [MaaAssistantArknights/MaaAssistantArknights#10188]
@nc7s 可能是因为这件事情没有向大家说明过：
<img width="427" alt="截屏2024-08-10 22 08 03" src="https://github.com/user-attachments/assets/026b8bb7-79cd-464d-9a4c-bca995a50ebb">
基于“面向开发者的服务”这一条，所有使用git的方案均不被考虑且被认为滥用。

如果有用户有更好的想法的话也欢迎通过 Enhancement 提出。

_Originally posted by @Daydreamer114 in https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10033#issuecomment-2281999716_

**Comment by Daydreamer114** [comment]
？

**Comment by tsctsc6** [comment]
我有异议！“自建git服务器”，严格来说，也不完全算得“面向开发者的服务”。
我们需要利用的是git管理文件的功能，

**Comment by Daydreamer114** [comment]
广义的讨论结果是，maa客户端不会直接或间接从GitHub获取内容

**Comment by ABA2396** [comment]
现在是有个git仓库，但其实我感觉用git管理资源文件并不是一个好的想法。这种东西也没必要版本控制，只要有最新版的就好了。

~其实有github打底也是有好处的~

**Comment by tsctsc6** [comment]
自建git服务器，意思就是不用github啦

**Comment by tsctsc6** [comment]
> 我有异议！“自建git服务器”，严格来说，也不完全算得“面向开发者的服务”。 也就是说，可以自建一个git服务器，专门用于资源的发布。 我们需要利用的是git管理文件的功能，思维可以开阔一点。

所谓“git管理文件的功能”，就是利用git来实现增量更新。

**Comment by Daydreamer114** [comment]
那自建git服务器要钱吗

> 自建git服务器，意思就是不用github啦

**Comment by SherkeyXD** [comment]
git 并不是一个很好的更新资源方式，会存下无数的历史版本

**Comment by tsctsc6** [comment]
> 那自建git服务器要钱吗
> 
> > 自建git服务器，意思就是不用github啦

[https://github.com/go-gitea/gitea](https://github.com/go-gitea/gitea)
[https://github.com/gogs/gogs](https://github.com/gogs/gogs)

**Comment by tsctsc6** [comment]
> git 并不是一个很好的更新资源方式，会存下无数的历史版本

不发release就行了

**Comment by ABA2396** [comment]
即使不发布 release，Git 依然会保存所有的提交历史。每次提交都会被记录下来，并且可以通过 Git 的历史记录查看到过去的版本。Release 只是将特定的 commit 标记为一个里程碑，它并不会影响 Git 保存历史版本的机制。

**Comment by tsctsc6** [comment]
`git checkout --orphan <new_branch>`
使用 `--orphan` 选项，可创建1个"清洁"分支(无任何的提交历史，但是当前分支的内容一应俱全。但严格意义上说，这样创建的分支还不是一个真正的分支，因为HEAD指向的引用中没有commit值，只有在进行一次提交后，它才算得上真正的分支。

**Comment by Daydreamer114** [comment]
> https://github.com/go-gitea/gitea https://github.com/gogs/gogs

用别人的服务器不还是白嫖吗

**Comment by tsctsc6** [comment]
> > https://github.com/go-gitea/gitea https://github.com/gogs/gogs
> 
> 用别人的服务器不还是白嫖吗

什么别人的服务器，那个只是可选。
你可以下载他们的软件，在自己的电脑上部署啊

**Comment by Daydreamer114** [comment]
在自己的服务器上部署不还是要钱吗（
总的来说，别惦记git了

**Comment by ABA2396** [comment]
你是不是搞错了一件事情，现在是自己部署的下载服务器流量扛不住了，你就算换成了git更新，走的不还是自己的流量

**Comment by tsctsc6** [comment]
> 你是不是搞错了一件事情，现在是自己部署的下载服务器流量扛不住了，你就算换成了git更新，走的不还是自己的流量

但是会少很多。

**Comment by Daydreamer114** [comment]
另外你如果愿意拿自己的电脑给maa搞这种事，你可以自己写一下

**Comment by ABA2396** [comment]
本来就是做的增量更新，又不是下完整包。本质上和git下流量对比也没多少区别，怎么得出的流量会少很多的结论
