### ISSUE TITLE
繁中服薩米肉鴿無法正確執行刷坍縮範式任務

### ISSUE THREAD

**Issue by oooRANGEooo** [MaaAssistantArknights/MaaAssistantArknights#10193]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

繁中服執行該任務時會卡在確認有否獲得坍縮範式的任務中

### Version

Resource Version: 綠野幻夢·復刻
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[asst.log](https://github.com/user-attachments/files/16570425/asst.log)
[gui.log](https://github.com/user-attachments/files/16570426/gui.log)
大致时间点 01:35~01:40

### 配置信息

[gui.json](https://github.com/user-attachments/files/16570428/gui.json)
windows 藍碟  1280*720 240 60 
無

### 截图

![Screenshot_2024 08 11_01 35 37 960](https://github.com/user-attachments/assets/76a80213-c6ef-41f7-b32e-5cfc300403bb)

**Comment by Daydreamer114** [comment]
duplicate of #10181

**Comment by Daydreamer114** [comment]
#10186 fixed

**Comment by Daydreamer114** [comment]
刚改的内容，连测试版都没发呢，你可以先去看看改了啥，然后本地替换一下
