### ISSUE TITLE
OCR识别错误：“采购中心”的“采”字有可能被挡住

### ISSUE THREAD

**Issue by yongpassby** [MaaAssistantArknights/MaaAssistantArknights#10194]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

一句话总结，限定抽卡凭证+月卡到期提醒，会把采购中心的“采”字上面部分挡住，使得OCR识别出错。
相关日志条目如下：
`[2024-08-10 20:09:18.100][TRC][Px2dac][Tx302c] asst::WordOcr [{ 即将到期: [ 6, 6, 62, 26 ], score: 0.990886 }, { 米购): [ 22, 35, 98, 26 ], score: 0.881819 }, { TORI: [ 25, 67, 42, 16 ], score: 0.906153 }] by OCR Pipeline , cost 165 ms
`
![屏幕截图 2024-08-11 063123](https://github.com/user-attachments/assets/7e747d87-2d0d-402d-86ac-c3646beae2e3)

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[debug.zip](https://github.com/user-attachments/files/16571079/debug.zip)
时间戳：
From 2024-08-10 20:08:55.977
To 2024-08-10 20:09:18.100

### 配置信息

[gui.json](https://github.com/user-attachments/files/16571080/gui.json)
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.19045 暂缺 Build 19045
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
模拟器：蓝叠模拟器5 国际版
模拟器分辨率：1600*900
DPI：160
帧率：60

### 截图

抱歉我没看到有这么一栏我直接贴在问题描述里了……
![屏幕截图 2024-08-11 063123](https://github.com/user-attachments/assets/7e747d87-2d0d-402d-86ac-c3646beae2e3)

**Comment by ABA2396** [comment]
我记得其实识别到中心也是可以的，不知道为啥中心也没识别到）等下加个即将到期的识别好了

**Comment by Saratoga-Official** [comment]
我觉得可能和主题皮肤有关系
