### ISSUE TITLE
日服自動戰鬥無法開始

### ISSUE THREAD

**Issue by Godkiller12345** [MaaAssistantArknights/MaaAssistantArknights#10196]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

應該是因為生息演算的關係，MAA會在介面卡住，然後說任務出錯

### Version

Resource Version: 懐黍離
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[debug.zip](https://github.com/user-attachments/files/16571643/debug.zip)

starrt at
[2024-08-11 13:00:00.487][TRC][Px6950][Tx7390] asst::ProcessTask::_run | enter

### 配置信息

[gui.json](https://github.com/user-attachments/files/16571645/gui.json)

**Comment by Godkiller12345** [comment]
另外，基建換班無法識別林的時裝

**Comment by Saratoga-Official** [comment]
> 另外，基建換班無法識別林的時裝

基建换人是看干员名字的ocr，和你换什么皮肤没一点关系

**Comment by Saratoga-Official** [comment]
能给我一张maa卡住的时候模拟器界面截图吗

**Comment by Manicsteiner** [comment]
活动导航目前改成图片任务了，最低需要 v5.5.11453-alpha.1.d052.g6277e5fa4
基建的干员名ocr不好说

**Comment by Constrat** [comment]
Only way to get new templates for recognition is by updating to a latest non-stable version.

Also `v5.5.0-beta.1` is at least 3 weeks old and it's even a stable release. I highly suggest updating.
