### ISSUE TITLE
更新资源文件的方法2

### ISSUE THREAD

**Issue by tsctsc6** [MaaAssistantArknights/MaaAssistantArknights#10191]
关于 Git 类方案的补充说明：

1. Git 需要在本地存储二进制 repo 数据，对于文本内容可以近似认为是一堆 patch，但对于二进制内容则是在用户硬盘上以不同的格式（blob object 有 header）存储两份相同的数据，同时 Git 没有任何形式的二进制差分，即需要完整保存新旧版本。
2. 虽然可以通过[一定方式](https://stackoverflow.com/questions/4698759/converting-git-repository-to-shallow)使本地不保存历史版本，但这意味着需要引入整个 Git 版本库逻辑，哪怕 MAA 并不需要其中的绝大部分功能。而频繁调用 git 之类的命令行工具则更是需要避免的。（喜欢我 MAA 截图一次开一个 adb.exe 吗？）
  同理，如果不希望 git repo 占用双倍大小则需要自行实现从 bare repo 中提取文件~~还有给 MAA 增加 VFS 支持~~，更是无谓地增加了程序的复杂度。
3. Git 的 HTTP fetch 本质上还是下载 index 和 object（或 pack）文件，与单独打包差异文件并下载没有本质区别。自己在命令行环境下使用方便并不是将其集成进 MAA 的理由。

---

太长不看版：高射炮打蚊子，自己玩玩可以，别想着转正了😅

_Originally posted by @dantmnf in https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10033#issuecomment-2282186781_

**Comment by tsctsc6** [comment]
好，第一点可以用lfs解决（虽然我搞不太懂这个）
第二点我无可辩驳
第三点，好吧，那就采用git方案咯。

最后我想说，就算你们不同意我的方案，也用不着禁言吧

**Comment by Daydreamer114** [comment]
<img width="240" alt="截屏2024-08-10 23 59 48" src="https://github.com/user-attachments/assets/ae1eb84e-201c-40d0-977e-4a70c3c29561">
纯粹是不想跟你讨论这个问题了
