### ISSUE TITLE
请问 Mac版怎么手动更新资源文件？

### ISSUE THREAD

**Issue by zhangweijian97** [MaaAssistantArknights/MaaAssistantArknights#10203]
### 说说你遇到的问题？

如题，教程说要覆盖cache和resource文件夹。但是mac这边没有cache文件夹
<img width="397" alt="image" src="https://github.com/user-attachments/assets/b28b1631-2811-4d71-8f67-fec4a45d4c52">

**Comment by ABA2396** [comment]
mac本来就没有资源热更。想用的话就直接把resource里的内容添加到现有的文件夹里就可以了

**Comment by zhangweijian97** [comment]
> mac本来就没有资源热更。想用的话就直接把resource里的内容添加到现有的文件夹里就可以了

突然发现MaaResource里面的stages.json没有 AS-ex-，只有普通关，没有高难关。怪不得覆盖了也不行。那为什么作业站上看评论似乎大家都可以用？

**Comment by Manicsteiner** [comment]
stages.json是掉落物信息，地图文件是 resource/Arknights-Tile-Pos/act35side_ex01-activities-act35side-level_act35side_ex01.json 这些

**Comment by Constrat** [comment]
^

**Comment by zhangweijian97** [comment]
谢谢，解决了。就是把Arknights-Tile-Pos文件夹覆盖就好了

**Comment by Saratoga-Official** [comment]
你不会翻阅一下以前关闭的issue吗，我都解决好几个mac资源更新问题了

**Comment by Saratoga-Official** [comment]
Duplicate of #10170 #10033
