### ISSUE TITLE
萨米肉鸽 将不期而遇的出发前往识别为紧急作战

### ISSUE THREAD

**Issue by TacLoky** [MaaAssistantArknights/MaaAssistantArknights#10207]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

和上次在萨卡兹一样.jpg
卡住半小时一动不动
上次：
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10105

### Version

MUMU12 1280x720 挂机15fps win10 未开启 未开启 3080

### 日志文件

[debug.zip](https://github.com/user-attachments/files/16574193/debug.zip)

### 配置信息

[gui.log](https://github.com/user-attachments/files/16574206/gui.log)

### 截图

![JSIDHIJYZONR6LV(Q`P2T@U](https://github.com/user-attachments/assets/a1aa62dc-6af3-4e1a-a4a6-08eafac54af4)

**Comment by Daydreamer114** [comment]
2024-08-11 16:58:27 这次你的asst.log从这里开始，没有在gui.log中找到执行时间异常的位置

**Comment by TacLoky** [comment]
> 2024-08-11 16:58:27 这次你的asst.log从这里开始，没有在gui.log中找到执行时间异常的位置

坏了，合着这回是忘了截图maa？

**Comment by Daydreamer114** [comment]
好惨哥们，下次记得遇到bug立刻看log还在不在，肉鸽这种任务产生的log很多，文件太大了或者到一定时间了maa就把之前的删了

**Comment by Daydreamer114** [comment]
```
[2024-08-07 20:12:08.948] <1><> 事件: 鲍勃杂货店
[2024-08-07 20:29:22.825] <1><> 事件: 猜疑链
```

gui.log里确实有一次异常，但是在asst.log里已经滚没了

**Comment by Daydreamer114** [comment]
上次那个问题我盲修了一下，给一些奇怪的位置加了弹窗识别，估计以后遇不到了

**Comment by TacLoky** [comment]
> 上次那个问题我盲修了一下，给一些奇怪的位置加了弹窗识别，估计以后遇不到了

有个奇怪的问题，像这种问题一般不是跳报错并停止任务然后自动上报bug吗？

**Comment by Daydreamer114** [comment]
> 有个奇怪的问题，像这种问题一般不是跳报错并停止任务然后自动上报bug吗？

maa有点……史山，现在的逻辑大体是识别到内容，执行，下一步有序识别一系列内容，执行第一个成功识别的内容，下一步有序识别一系列内容...
很多任务识别不到要求的内容会自循环，绝大部分任务有失败次数（INT_MAX）
同时绝大多数任务是拿自己做有序下一步的最后一个内容，一直成功的话甚至没有次数限制，第一个成功识别的内容就是写在了下一步的最后一个，只能是用着用着发现了，然后看log在干啥

**Comment by TacLoky** [comment]
> 万一弹出了什么东西，挡住了前四个的位置，让开了第五个的位置，但又让第五个点不到，就

![8Z7$5KIT6TL%~DT}@Y)1ZF](https://github.com/user-attachments/assets/6de0c42e-4549-4caf-9ff0-3ae1275b1877)

**Comment by Daydreamer114** [comment]
那就先关了，这个不期而遇要联动抗干扰识别，看不到你当时的情况就确实不知道为啥卡住
![image](https://github.com/user-attachments/assets/5d8126f0-0495-4651-9e2a-6c8f65d25e6f)

**Comment by TacLoky** [comment]
> 那就先关了，这个不期而遇要联动抗干扰识别，看不到你当时的情况就确实不知道为啥卡住

可以...下次要追加什么截图或者文件吗？感觉萨米的卡死触发得比其他都频繁。

**Comment by Daydreamer114** [comment]
不用别的，这次的挺好，就是晚了点＞﹏＜

**Comment by TacLoky** [comment]
> 不用别的，这次的挺好，就是晚了点＞﹏＜

不应该啊？对比上次卡了12小时才睡醒起来发帖而言这次可能算及时的了 
![RSC9{6A$E{ZRW5`WF1W4 `P](https://github.com/user-attachments/assets/9e54a6dd-967d-4d1b-b068-54701be4a270)

**Comment by TacLoky** [comment]
？没道理呀，这回至少比上回快多了，上回可是卡了10个小时睡醒才上来发帖反馈的

**Comment by Daydreamer114** [comment]
那没事了我太依赖搜索了

**Comment by Daydreamer114** [comment]
\debug\roguelike\2024-08-11_23-02-29-648_raw.png
找找这张图

**Comment by TacLoky** [comment]
![2024-08-11_23-02-29-648_raw](https://github.com/user-attachments/assets/d51cb47e-8941-45d9-b560-73d23e7e7beb)
![2024-08-11_23-02-33-825_raw](https://github.com/user-attachments/assets/e28f4583-70ee-4021-8bbf-4aaeda29c1c5)

**Comment by Daydreamer114** [comment]
![Sami@Roguelike@StageEmergencyDpsEnter](https://github.com/user-attachments/assets/9580f571-0e59-486b-b97b-ef0274fd0e8f)
嗯……把不期而遇的出发前往识别成这个了

cc @zzyyyl

**Comment by Daydreamer114** [comment]
把鼠标悬停在他的名字上就可以看到他在vocation啦
这两天他不在，issue挂着吧

**Comment by zzyyyl** [comment]
萨米的我之前没动啊（

你自己改改呗，换成 HSVCount 就行了，大概

**Comment by TacLoky** [comment]
刚睡醒。新问题，关卡识别错误
![image](https://github.com/user-attachments/assets/dd409b06-9979-4474-a45c-0369e78325da)
我应该开个新issue吗

**Comment by TacLoky** [comment]
![image](https://github.com/user-attachments/assets/58fcc5b1-f201-4216-b3ad-de2e8865faca)
卡在了“联系中断”画面
![image](https://github.com/user-attachments/assets/6c9cd275-ec65-4107-a323-c6d8dd6a7d85)
手动结算之后自动开启下一次探索了

**Comment by TacLoky** [comment]
[debug.zip](https://github.com/user-attachments/files/16579880/debug.zip)
有种感觉是网络波动导致的结果。。？
debug截图
![image](https://github.com/user-attachments/assets/5ddc5470-5dfe-445b-be1d-6268e9173abf)

**Comment by Daydreamer114** [comment]
关卡识别错误忍忍吧（）OCR抽疯常有的事（）但是卡住就不对了，你可以发个新的
