### ISSUE TITLE
通过git版本管理手动更新，比每次都下载zip简单点。

### ISSUE THREAD

**Issue by Rainbowcatm** [MaaAssistantArknights/MaaAssistantArknights#10201]
### 说说你遇到的问题？

不是issue！不是issue！不是issue！（因为没有别的权限只能用question标签）

找到MAA安装文件夹，如果没有.git文件夹，git命令行执行
`git init`
如果有直接执行后面：
先新建一个存储分支：
`git add .`
`git checkout localmain`
`git commit -m "init"`

把main分支建出来：
`git checkout main`
添加远程分支关联
`git remote add origin https://github.com/MaaAssistantArknights/MaaResource.git`
关联本地和远程分支
`git branch --set-upstream-to=origin/main main`
`git pull`

切回分支：
`git checkout localmain`
`git merge --allow-unrelated-histories main`
遇到编辑直接:!q退出就完事了，以后就是切到main分支拉一下然后切回到localmain分支merge一下就行了。

**Comment by Rainbowcatm** [comment]
各位大神如果有时间可以把git集成为一个cmd或者sh脚本使用，当作一个临时方案。

**Comment by ABA2396** [comment]
这也太麻烦了，你还不如单独起一个储存库更新完复制到maa文件夹下）
``` cmd
@echo off
chcp 65001 >nul

REM 更新仓库
echo 正在获取资源文件……
cd MaaResource
git reset --hard
git pull
cd ..

REM 复制文件到当前目录
echo 替换中……
robocopy MaaResource\resource MAA\resource /E
```
这只是个临时方案，并不打算让maa自带

**Comment by Rainbowcatm** [comment]
可以，有方案就行。我这边反正是嫌整个拉MAA慢就只更新，cache和resource来着。

> 这也太麻烦了，你还不如单独起一个储存库更新完复制到maa文件夹下）
> 
> ```batchfile
> @echo off
> chcp 65001 >nul
> 
> REM 更新仓库
> echo 正在获取资源文件……
> cd MaaResource
> git reset --hard
> git pull
> cd ..
> 
> REM 复制文件到当前目录
> echo 替换中……
> robocopy MaaResource\resource MAA\resource /E
> ```
> 
> 这只是个临时方案，并不打算让maa自带

可以有方案就行。我就是随便写写提个方案，之后能继承最好。

**Comment by Daydreamer114** [comment]
你可以先读一下10033号issue

**Comment by Rainbowcatm** [comment]
好的，我的。版太长了我没看几条就去敲了个脚本我的问题。那我的建议是还是整个手动更新的按钮让用户自己选择更不更新吧。因为以我作为用户的需求来看并不是每天开机我都希望MAA更新的，有的时候频繁更新用户还会觉得很烦。所以我的建议是添加类似游戏的手动更新机制，在程序中加入版本号来差分更新，整包安装方式维持现状让用户手动来git下载。至于更新方式的话买服务器免不了有成本，服务器少就还和以前一样emmm。

**Comment by Rainbowcatm** [comment]
感觉要稳定还是需要服务器，建议拉个赞助或者众筹一下？

**Comment by Daydreamer114** [comment]
哥们从火星回来的。。可以看一下b站官号之前的动态

**Comment by Rainbowcatm** [comment]
> 哥们从火星回来的。。可以看一下b站官号之前的动态

本来就是刚刚加班回来，憋扎心了~~~
