### ISSUE TITLE
希望能加入自动连续公招选项并停止招募3星tag 加急4/5星tag 跳过六星tag

### ISSUE THREAD

**Issue by ww352** [MaaAssistantArknights/MaaAssistantArknights#10209]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

希望可以自动连续公招刷黄票或者是高资，对于那些攒了很多公招券的老玩家来说一个一个刷太费劲了，并且不是所有的公招都值得用加急券，如果可以只为4/5/6星tag使用加急券，自动停止招募3星以下tag就好了

### 有什么好的想法？

（现在已有功能）在maa自动设置时间，自动选择最佳tag 开始公招
（希望可以有的）如果此次公招没有4/5星tag，开始公招后自动停止招募
                             如果有4/5星tag，开始公招后自动使用加急许可结束公招
                             如果有高资，不开始公招，跳过当前槽位到第二个槽位
                             设置期望公招次数 公招____次/使用完所有券/被高资占满四个槽位
谢谢！

**Comment by Saratoga-Official** [comment]
自动连续刷公招其实已经做了，你给maa设置公招次数，然后选择自动使用加急和不确认五六星，maa就一直公招直到达到次数

**Comment by ABA2396** [comment]
没懂只加速四五星的意义在哪里，最终消耗的时间不还是一样的吗

**Comment by Daydreamer114** [comment]
他说的是3星放弃招募而不是加急）

**Comment by ABA2396** [comment]
那不考虑，到时候哪天又有人来说maa浪费绿票了

**Comment by Constrat** [comment]
Halting recruitment is a waste of resources, including the recruit permit and potential subsequent green tickets. Is it all just to use public tickets on higher rarities? 
The rate of acquiring recruitments versus the rate of usage is so disproportionate that employing just four recruits daily will deplete them in the month.

**Comment by ww352** [comment]
损失绿票是必然的，但是我现在离换258还有20张票，我不确定剩下的两天里公招能不能攒够20黄票，就为了三星的10张绿票。我会以损失一些（或很多）绿票的结果去加速我黄票的获取速度，这个功能更像是紧急情况下才会使用的。

what you said makes all the sense, but im only 20 yellow ticket away fom 258 (exchanging pull card) and i dont know if i have times to wait oh those 10 green ticket per recruit before the pool close.  honestly i would waste some ( or a lot) of green ticket at this moment just to get that 20 yellow ticket. this this much more in a emgerency event like what you said, if you know what i mean.
