### ISSUE TITLE
关于基建的建议

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#1020]
Hi Maa Team:

1. 无人机使用在含技能为增加更高赤金量订单的贸易站收益更高，是否可以增加该条识别逻辑。
2. 贸易站更换干员时它似乎不认识龙舌兰？
3. 能天使，德克萨斯，拉普兰德这类固定组合在更换时能否绑定？
4. 有没有可能加个自动把九色鹿用碳叠到36点的功能？

Thanks

**Comment by YipKei** [comment]
> 无人机使用在含技能为增加更高赤金量订单的贸易站收益更高，是否可以增加该条识别逻辑。

虽然有点反逻辑，但我要提醒你，巫恋组刚换上去的时候，裁缝系列技能的加成是不生效的
如果你想实现这个，那么还得加一个心情阈值的判断，否则还不如不做

> 能天使，德克萨斯，拉普兰德这类固定组合在更换时能否绑定？

如果MAA没有绑定更换，说明对于你的阵容来说，不绑定的收益更高，MAA是能够识别特定组合的。

另外，如果真正想要基建的收益，建议手动换班，MAA的基建换班功能主要是为懒得换班的人提供一个保底的，不可能做到完美适配最新的排班，而且开发者也明确表示过，不打算开放相关的自定义功能。

**Comment by MistEO** [comment]
> 1. 无人机使用在含技能为增加更高赤金量订单的贸易站收益更高，是否可以增加该条识别逻辑。

现在就是有的，专门识别巫恋并加速，没有的话可能是你遇到了 bug

> 2. 贸易站更换干员时它似乎不认识龙舌兰？

也是有的，可能是 bug

> 3. 能天使，德克萨斯，拉普兰德这类固定组合在更换时能否绑定？

德克萨斯这个组合相对效率并不高，maa 只考虑效率

> 4. 有没有可能加个自动把九色鹿用碳叠到36点的功能？

以后可能会支持，但也不一定
