### ISSUE TITLE
能否自动战斗支持生息演算副本？

### ISSUE THREAD

**Issue by insine-inverse** [MaaAssistantArknights/MaaAssistantArknights#10202]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

想要抄B站作业但是怕自己操作不行，发现自动战斗不支持生息演算……

### 有什么好的想法？

能不能支持陌域的几个boss本能自动抄视频作业呢？挖矿太难了就算了_(:3」∠)_

**Comment by Saratoga-Official** [comment]
目前实现很困难，近期没有计划
