### ISSUE TITLE
生息演算出现UI偏移，通过制造刷点数无法正常工作

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#10200]
### 说说你遇到的问题？

v5.5.11453-alpha.1.d109.g0e51aaba0

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/d81515fc-7a1e-4d79-ac6a-2d1a1055e797)
比如开始任务的第一项，这个已经往右偏出roi了，tasks里写的五百多

**Comment by ABA2396** [comment]
那你改改）范围扩大一点就好了吧？这玩意啥时候变的，这个月才刚用过

**Comment by Daydreamer114** [comment]
我没有一个号正经打过盐酸，点进这个页面之后的task就跟我号里的对不上了
