### ISSUE TITLE
我多开的maa无法使用，具体体现为多开端无法识别多开的模拟器屏幕

### ISSUE THREAD

**Issue by AlanJiang1205** [MaaAssistantArknights/MaaAssistantArknights#10217]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

我使用的是Mumu 12模拟器，模拟器版本：V4.02(3233)。我试图根据使用手册连接设置“多开maa"一章里”通过附加命令启动“的方法设置自动多开maa，但是多开的maa无法运行。附件如下图：

p1：两个模拟器和两个maa的运行情况以及两个模拟器的adb地址，几乎同时启动maa但是多开的maa界面卡死，具体体现为无法抓取多开的模拟器界面截图（猜测）；

p2, p3：端口号为16384的maa的配置信息，负责运行明日方舟b服（包括”启动设置“和”连接设置“，附加命令为：--cmd launchApp --package "com.hypergryph.arknights.bilibili"）；
p4, p5：端口号为16448的maa的配置信息，负责运行明日方舟官服（包括”启动设置“和”连接设置“，附加命令为：-v 2 --cmd launchApp --package "com.hypergryph.arknights"）；
两者的模拟器路径均为G:\Program Files\Netease\MuMuPlayer-12.0\shell\MuMuPlayer.exe

p6：任务管理器”命令行“信息；

![微信截图_20240812125158](https://github.com/user-attachments/assets/072d8b25-f8b7-435e-819a-5f967f25cb84)

![image](https://github.com/user-attachments/assets/5a59305b-855e-4eaa-87e1-de85de8221a4)
![image](https://github.com/user-attachments/assets/bcb036ec-6aa5-410e-a653-d1a7701cf74e)

![image](https://github.com/user-attachments/assets/9ce2a69f-3d92-4bba-92bf-99483aa08e29)
![image](https://github.com/user-attachments/assets/e60ef138-b05c-41a6-af24-9615da9899c1)

![image](https://github.com/user-attachments/assets/cae4923a-dca9-40c4-9cc5-4db004cbcf58)

我不知道这是什么情况，所以我想寻求研发团队诉诸解决，感谢！

### Version

两个maa的Resource Version均为太阳甩在身后；
UI Version均为v5.5.11452；
Core Version均为v5.5.11452；
均为公测版。

### 日志文件

端口号为16384的：
[asst.log](https://github.com/user-attachments/files/16577638/asst.log)
[gui.log](https://github.com/user-attachments/files/16577639/gui.log)

端口号为16448的：
[asst.log](https://github.com/user-attachments/files/16577642/asst.log)
[gui.log](https://github.com/user-attachments/files/16577643/gui.log)

出现问题的大致时间是：2024/8/12 12:45 (GMT +8)

### 配置信息

端口号为16384的：
[gui.json](https://github.com/user-attachments/files/16577651/gui.json)

端口号为16448的：
[gui.json](https://github.com/user-attachments/files/16577652/gui.json)

操作系统及版本：Windows 11家庭中文版 23H2 22631.3880；
模拟器品牌：网易Mumu模拟器12；
分辨率均为平板版1280*720；
DPI均为240；
帧率均为60帧；
Mumu截图增强均已开启；
GPU加速推理均未开启。

### 截图

屏幕截图：
![微信截图_20240812125158](https://github.com/user-attachments/assets/4333d0d2-43ae-4d73-8fe9-e4bb990ec138)

端口为16448的模拟器截图：
![MuMu12-20240812-132354](https://github.com/user-attachments/assets/97580b28-fda9-45f0-95fd-231fab4a04ac)

端口为16448的maa自动截图错误图片（它还是截到b服去了，已打包）：
[roguelike.zip](https://github.com/user-attachments/files/16577702/roguelike.zip)

**Comment by status102** [comment]
![image](https://github.com/user-attachments/assets/b44deeb3-5b5a-46e8-b625-1a3730b7bc18)

多开的实例编号不可能一样

**Comment by AlanJiang1205** [comment]
问题解决了，给maa的佬佬佬们磕一个

**Comment by Saratoga-Official** [comment]
？你这也没关上啊
