### ISSUE TITLE
B服卡登陆

### ISSUE THREAD

**Issue by YZCSLZY** [MaaAssistantArknights/MaaAssistantArknights#10212]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

B服每次关闭游戏重新登陆都会跳出隐私政策提示要点一下才能继续登陆

### 有什么好的想法？

希望MAA能优化一下

### 其他内容

![QQ图片20240812013027](https://github.com/user-attachments/assets/57e61123-d121-4d5c-ae79-a2f93825d25f)
![QQ图片20240812012944](https://github.com/user-attachments/assets/93fd2a8b-cefd-4698-b179-128d7f86efcb)

**Comment by Saratoga-Official** [comment]
Duplicate of #8343

**Comment by ABA2396** [comment]
隐私策略在没更新的情况下只要点一次就不会出现了。如果没有频繁切号的话建议卸载重装游戏或者重装模拟器实例

**Comment by Saratoga-Official** [comment]
代同意协议是违法的，maa不会做
