### ISSUE TITLE
关于信用商店的黑白名单

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#1021]
Hi Maa Team:

能否将黑白名单改手动输出为按钮选择以此避免输错名称的发生？

Thanks

**Comment by YipKei** [comment]
别说输错了，现在信用商店识别的准确率都没保证
买东西建议手动，反正也花不了两分钟的时间

**Comment by zzyyyl** [comment]
输错名字不行，但是你可以少输入几个字，比如 `加急凭证` 可以就输入 `加急`，甚至就一个 `急` 估计也没问题（
信用商店目前的识别是有 `replace_map` 的（就是 `CreditShop-ProductName`，好像就只有一个龙门币），我目前为止还没有出现识别错误的情况，如果有准确性问题可以提一个 issue。

**Comment by MistEO** [comment]
> 别说输错了，现在信用商店识别的准确率都没保证 买东西建议手动，反正也花不了两分钟的时间

没有吧，我感觉识别的还挺准的，确实如果有识别问题可以提个 issue 看看，这种的问题应该比较好解决

**Comment by aysyxx53** [comment]
或许黑白名单可以采用类似一键长草的那种复选框设计？

**Comment by aysyxx53** [comment]
或许黑白名单可以采用类似一键长草的那种复选框设计？
