### ISSUE TITLE
[JP]刷理智 无限吃48小时内过期药 未生效

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#10210]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/user-attachments/assets/d41b908b-9aa8-4ff2-a694-ecd2f32f99a6)
![image](https://github.com/user-attachments/assets/8228faef-5186-4a9d-bbdb-b5a0e291910c)
点一下开始行动，进入吃药界面，然后大概十秒退出吃药界面，然后任务完成

### Version

Resource Version: 懐黍離
Core Version: v5.5.11453-alpha.1.d132.gd319bac4a

### 日志文件

[asst.log](https://github.com/user-attachments/files/16574485/asst.log)
574行

### 配置信息

谴责自己给自己挖的坑
------------
vulkan模式，4处理器8GB，自动调优，强制独显，1080p，DPI280，画面亮度50 普通，60帧
Win11
MumuExtras on
GPU开启 3070ti laptop

**Comment by Constrat** [comment]
Try not to use "global". 
For global we mean all clients that are not the cn (or bilibili) server.
If the issue if with JP it's just JP, if the issue is for all non-cn it's only Global.

**Comment by Daydreamer114** [comment]
> For global we mean all clients that are not the cn (or bilibili) server. If the issue if with JP it's just JP, if the issue is for all non-cn it's only Global.

sry>_<

**Comment by Manicsteiner** [comment]
Probably the same reason as #10172

**Comment by status102** [comment]
Duplicate of #10172
