### ISSUE TITLE
自动战斗页面的自定义追加干员功能添加职业筛选减少操作时间提高效率

### ISSUE THREAD

**Issue by AKiSA07** [MaaAssistantArknights/MaaAssistantArknights#10219]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

每一次自定义追加干员都是从最后一个作业需求干员后从全部干员中慢慢识别，效率略低

### 有什么好的想法？

是否能通过添加字段如"辅助,令,3;重装,黍,1"实现每次追加干员时像选择作业需求干员一样通过不同职业筛选的方式省去很多时间？

**Comment by Saratoga-Official** [comment]
没必要，自定义干员就贪点信赖，你挂基建挂几天就满了

**Comment by Constrat** [comment]
^ If you really want to trust, enable the auto select trust operators.
