### ISSUE TITLE
建议增加遇见高星tag时自动使用加急许可

### ISSUE THREAD

**Issue by cglcv** [MaaAssistantArknights/MaaAssistantArknights#1022]
如题，仅在出现4/5/6星时使用加急许可，用于快速获取黄票
~顺便要不要来一个自动兑换信物功能？~

**Comment by MistEO** [comment]
又是一个会被放置一万年的 issue（

**Comment by ABA2396** [comment]
760张加急许可路过

**Comment by zzyyyl** [comment]
580张黄票路过（黄票有那么缺吗.jpg）

**Comment by cglcv** [comment]
> 580张黄票路过（黄票有那么缺吗.jpg）

零氪党表示黄票还是挺难搞的（
