### ISSUE TITLE
源石锭为999且“投资源石锭”“到上限停止”时烧水失败

### ISSUE THREAD

**Issue by heyan2454** [MaaAssistantArknights/MaaAssistantArknights#10222]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

在烧开水时，若源石锭为999（上限），则在高级设置中，勾选投资源石锭会导致烧水失败。
当勾选“投资源石锭”与“到上限停止”时，会在一层投资完成后，进二层直接退出，并认定任务成功。
源石锭不为999或不勾选“到上限停止”时，正常烧水。

### Version

Core Version: v5.5.11452

### 日志文件

[asst.log](https://github.com/user-attachments/files/16580354/asst.log)
[gui.log](https://github.com/user-attachments/files/16580357/gui.log)

2024-08-12 17:00:48.838 第一次出现。后面用其他肉鸽测试了一下。

### 配置信息

[gui.json](https://github.com/user-attachments/files/16580375/gui.json)

Mumu12，截图增强开启。不开启加速推理。

### 截图

![傀影烧水失败](https://github.com/user-attachments/assets/dd51930c-c353-4856-ad52-f31a4016f1af)

图为后面测试的一次傀影肉鸽（999源石锭），进入二层后直接退出并认定完成。

**Comment by ABA2396** [comment]
所以这个逻辑有什么问题吗

**Comment by heyan2454** [comment]
> 所以这个逻辑有什么问题吗

个人认为常规设置中的“刷开局”策略应该在更高的优先级。感觉边界条件卡着了。
当然由于源石锭为999为少见情况且可以通过不勾选“到上限停止”而成功烧水，不处理是毫无问题的。
首次提issue，仅作为一个建议，如有问题请见谅，感谢MAA开发者们。

**Comment by Saratoga-Official** [comment]
源石锭满了还勾选不就是你自己的问题吗
