### ISSUE TITLE
多开时maa关闭模拟器导致其他模拟器断网

### ISSUE THREAD

**Issue by T-Chaos** [MaaAssistantArknights/MaaAssistantArknights#10239]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

多开模拟器时，一个maa完成任务后执行“退出模拟器”操作后会导致其他模拟器断网并与maa断连

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[0gui.log](https://github.com/user-attachments/files/16607029/0gui.log)
[gui.log](https://github.com/user-attachments/files/16607030/gui.log)
[0asst.log](https://github.com/user-attachments/files/16607031/0asst.log)
[asst.log](https://github.com/user-attachments/files/16607032/asst.log)
标记数字0的为执行关闭模拟器操作的maa
10:16分maa关闭模拟器后另一个模拟器随即断网

### 配置信息

[gui.json](https://github.com/user-attachments/files/16607034/gui.json)
[0gui.json](https://github.com/user-attachments/files/16607036/0gui.json)
标记数字0的为执行关闭模拟器操作的maa

操作系统：Win10企业版 22H2
模拟器：MuMu12 V4.0.3 (3244)
模拟器分辨率：1280x720 (DPI: 240)
模拟器帧率：最高帧率限制60帧；动态调整帧率30帧
截图增强已开启；未开启GPU加速推理

### 还有别的吗？
可能是adb相关bug，出现该现象后其他maa启动任务时均无法连接至模拟器

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/a00787b0-2616-404a-ab99-609691a3d98d)
这玩意开着没

**Comment by Kagura-Nanaa** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/357879614-a00787b0-2616-404a-ab99-609691a3d98d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODM2NTYsIm5iZiI6MTcyMzY4MzM1NiwicGF0aCI6Ii85OTA3Mjk3NS8zNTc4Nzk2MTQtYTAwNzg3YjAtMjYxNi00MDRhLWFiOTktNjA5NjkxYTNkOThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAwNTU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NWFkOWNjMWEwMDE5ZWUzMTVjYzQwMGE1YmU0NGY5YzRlMjk2MmZhMGFlZjBiYTBlYjU1MTMyMWNiZjQ4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.avlBfkB3vVY2AccjIzGljSXRihznBjdUhTs0nJo8EEs) 这玩意开着没
我也有一样的问题，退出释放adb没有打开

**Comment by Kagura-Nanaa** [comment]
[asst.log](https://github.com/user-attachments/files/16620419/asst.log)
[gui.log](https://github.com/user-attachments/files/16620420/gui.log)
[gui.json](https://github.com/user-attachments/files/16620421/gui.json)

**Comment by T-Chaos** [comment]
> > ![image](https://private-user-images.githubusercontent.com/99072975/357879614-a00787b0-2616-404a-ab99-609691a3d98d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODM2NTYsIm5iZiI6MTcyMzY4MzM1NiwicGF0aCI6Ii85OTA3Mjk3NS8zNTc4Nzk2MTQtYTAwNzg3YjAtMjYxNi00MDRhLWFiOTktNjA5NjkxYTNkOThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAwNTU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NWFkOWNjMWEwMDE5ZWUzMTVjYzQwMGE1YmU0NGY5YzRlMjk2MmZhMGFlZjBiYTBlYjU1MTMyMWNiZjQ4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.avlBfkB3vVY2AccjIzGljSXRihznBjdUhTs0nJo8EEs) 这玩意开着没
> > 我也有一样的问题，退出释放adb没有打开
试过了，没有效果。

**Comment by ABA2396** [comment]
退模拟器用的是mumu的控制台方法，感觉得找 mumu 的说说了

**Comment by spec123321** [comment]
mumu12 V4.0.3版本有同样问题，回退到V4.0.0版本就正常了，可能和新版更新的远程控制有关
