### ISSUE TITLE
肉鸽关卡识别出错卡死

### ISSUE THREAD

**Issue by KUAPT** [MaaAssistantArknights/MaaAssistantArknights#10235]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

肉鸽关卡识别出错卡死，反复尝试刷新刷新次数已耗尽的关卡，并且误识别为紧急作战

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11453-alpha.1.d146.g657a1c254
Core Version: v5.5.11453-alpha.1.d146.g657a1c254

### 日志文件

[asst.log](https://github.com/user-attachments/files/16595815/asst.log)
[gui.log](https://github.com/user-attachments/files/16595817/gui.log)
14点13分发生

### 配置信息

[gui.json](https://github.com/user-attachments/files/16595826/gui.json)
win11 23H2 22635.4010
蓝叠国际版；1280x720；DPI=240；帧率60
开启GPU加速推理，型号：NVIDIA GeForce RTX 4060 Laptop GPU

### 还有别的吗？

资源已手动更新至最新版本

**Comment by KUAPT** [comment]
不好意思   之前网卡了图没上传上来，现在补充

**Comment by HoshinoAyako** [comment]
尝试过关掉gpu加速推理吗？

**Comment by KUAPT** [comment]
> 尝试过关掉gpu加速推理吗？

最近一段时间都在高强度刷肉鸽，此前未遇到此问题，近两天才高频出现，期间GPU推理加速一直是开着的
今天试了关闭GPU加速，问题依旧

**Comment by Saratoga-Official** [comment]
[2024-08-13 14:13:58.498][TRC][Px5454][Tx38a0] match_templ | Sarkaz@Roguelike@StageRefresh.png score: 0.808328 rect: [ 803, 210, 38, 15 ] roi: [ 790, 130, 60, 144 ]
识别刷新次数超限只有0.8左右识别度，0.9才能通过

**Comment by zzyyyl** [comment]
所以说不要用 matchtemplate 匹配带中文的东西，该 ocr 还是得 ocr（
