### ISSUE TITLE
获取信用及购物中，借助战打OF-1的操作勾选了，却没有执行

### ISSUE THREAD

**Issue by Altria-Joker** [MaaAssistantArknights/MaaAssistantArknights#10232]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

在目前最新版的MAA中，获取信用及购物里面勾选了借助战打OF-1赚信用的操作，但是在实际执行的时候，好友信用收取完，在主界面停顿以后，直接就进商店获取信用，然后就直接完成了这个任务，并没有进关卡的操作或其他，熔炉还魂版本并没有这个问题，通过更换主界面主题，打开截图增强也未能解决
![微信截图_20240813084153](https://github.com/user-attachments/assets/aa072eef-af21-4e70-a1b0-1004753f4266)

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452
![微信截图_20240813084246](https://github.com/user-attachments/assets/f6ef35db-18e7-41f3-99f8-4387b259238a)

### 日志文件

[asst.log](https://github.com/user-attachments/files/16593126/asst.log)
[gui.log](https://github.com/user-attachments/files/16593128/gui.log)

### 配置信息

[gui.json](https://github.com/user-attachments/files/16593130/gui.json)
操作系统：win11
模拟器：MUMU12  分辨率：1600X900  dpi 240  帧率60
一开始没开MUMU截图增强，后面开了
GPU加速未开启

**Comment by Saratoga-Official** [comment]
刷理智不能选当前上次

**Comment by Saratoga-Official** [comment]
刷理智不能选当前上次
＃9956
