### ISSUE TITLE
Auto I.S. Mizuki aborts when you have to decide between 2 recruitment vouchers

### ISSUE THREAD

**Issue by dragonheart107** [MaaAssistantArknights/MaaAssistantArknights#10233]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

Main Issue is the first one:
1. Auto I.S. settings
- Theme: Mizuki
- Strategy: Gain Experience Points, clear as many nodes as possible
- Starting Squad: Mind Over Matter Squad
- Starting Roles: Slow and Steady Wins the Race
- Starting Operator: Horn

After encountering the 'decide between 2 different recruitment vouchers' options after a battle MAA gets stuck and quits current exploration, to restart auto I.S. If you manually click on one of the vouchers it plays normally again (looks at selectable operators, then picks and continues to auto) until the next 'decide between 2 different recruitment vouchers'. This is consistantly replicable.

2. ~~MAA sometimes ignores high-value (6*) operators (with enough hope to recruit) and picks the Reserve Operators from I. S. instead, is that intended or bug?~~

### Version

Resource Version: Here A People Sows
UI Version: v5.5.11452
Core Version: v5.5.11452

### Log files

[asst.bak.log](https://github.com/user-attachments/files/16593434/asst.bak.log)
[gui.log](https://github.com/user-attachments/files/16593441/gui.log)

Had to upload the asst.bak data and not the asst data, as the issues were in there.
Issue 1: start of the retry loop [2024-08-13 03:41:32.518]

Issue 2: around " [2024-08-13 03:22:06 ", not sure anymore if it was the battle before rogue trader or after, where a weaker operator got selected

### Configuration information

Windows 11, Mumu 12 global V3.8.18 (2845), 1920 x1080 (DPI 280), 60fps
no MuMu screenshot enhancement
GPU accelerated inference enabled: AMD Radeon RX 7900 XTX
[gui.json](https://github.com/user-attachments/files/16593447/gui.json)

### Screenshots

![2024-08-13_03-41-51-585_raw](https://github.com/user-attachments/assets/c6a12b6f-6c80-4fb7-83b8-619732515941)

**Comment by Constrat** [comment]
The double recruit permit issue was present about a year ago but I was sure I had it fixed. There's a low score of 0.81 for the Mizuki@Roguelike@GetDropSelectRecruit

Regarding the priority for Reserve operators, sometimes that can happen. As in specific cases it's better to not waste hope on 6 stars and to keep more hope for more important operators.

**Comment by Constrat** [comment]
Trying to replicate this is not easy.

**Comment by Constrat** [comment]
Let me know how it goes, if it fixes it, I'll push the change.

**Comment by dragonheart107** [comment]
alright, will try a few runs and will also test on the other I. S.

**Comment by Constrat** [comment]
Testing other IS won't necessarily be useful as they have different templates.

**Comment by dragonheart107** [comment]
Alright, that change seems to have resolved the issue.
Regarding other I.S. : I'll keep that in mind, but since I'll be running those anyway, it couldn't hurt (though for now phantom and sami will be run as is)

**Comment by Constrat** [comment]
Strange that the threshold deteriorated. Yostar always fucking things up

**Comment by ItsukaHiro1111** [comment]
> Trying to replicate this is not easy. @dragonheart107 I think it's just a threshold issue. Go to maa_dir/resource/global/YoStarEN/resource/tasks.json. Look for this: `Mizuki@Roguelike@GetDropSelectRecruit`. Replace
> 
> ```json
>     "Mizuki@Roguelike@GetDropSelectRecruit": {
>         "template": "Mizuki@Roguelike@GetDropSelectRecruit.png"
>     },
> ```
> 
> With this
> 
> ```json
>     "Mizuki@Roguelike@GetDropSelectRecruit": {
>         "templThreshold": 0.8,
>         "template": "Mizuki@Roguelike@GetDropSelectRecruit.png"
>     },
> ```

seem like that fixed the problem.

**Comment by Constrat** [comment]
The it's most likely that an update arrived that changed some DPI / rendering values on the global client.

**Comment by dragonheart107** [comment]
> The it's most likely that an update arrived that changed some DPI / rendering values on the global client. Since it's just threshold I can OTA this one. But a better solution would be to update the template.

Sorry to comment on this closed issue again. I found another bug related to recruitment and didn't want to open a new issue since we might not fix it anyway: If you have that one relic that gives you an additional option for recruitment, it gets stuck on the now **3** vouchers. Would this be an easy fix with threshold again or require the template to be updated or a complete new code block? Also it may be not worth the effort since getting that relic might not be the most common thing.

**Comment by Constrat** [comment]
Technically it should work. The ROI is a huge rectangle that's as wide as the entire screen, so it not working is a big question, it still might be a threshold level, meaning the more recruitments there are the shittier the image is but it feels kinda stupid. If you can extract the score results of the moment it happened we can quickly check it. If the score doesn't say anything useful than unfortunately I think it'll be a no-fix

**Comment by Constrat** [comment]
I mean the exact part where in the log it says: time date, template.png: score: a number, roi: something something etc
