### ISSUE TITLE
請求增加薩米肉鴿打完第三層boss後自動重刷功能

### ISSUE THREAD

**Issue by Hech0344** [MaaAssistantArknights/MaaAssistantArknights#10234]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

需要刷漆黑的舞鞋 
目前已將shopping.json檔中的黑鞋調高購買優先順序
只是想增加刷關的效率...麻煩各位大佬們 謝謝

**Comment by Daydreamer114** [comment]
duplicate of #10032

**Comment by status102** [comment]
> duplicate of #10032

重复的记得关
