### ISSUE TITLE
GUI - Copilot Battle List sanity potion not being used

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#10246]
### Description

When using Battle List, Auto Squad will be automatically turned on. You can still disable Auto Squad and everything works: MAA will directly start the selected stage without changing the squad:
![image](https://github.com/user-attachments/assets/c8337b66-1d38-430b-9469-cc03edbcdfa9)

The use of sanity option can also be turned on in this case, but it will not run the UseMedicine subtask:
![image](https://github.com/user-attachments/assets/8a9397df-a460-4cd2-ae2b-9a9fff70f866)

To run the UseMedicine, Auto Squad needs to be turned on. Like this:
![image](https://github.com/user-attachments/assets/c6aaa922-71db-44d7-80bc-778f045f6283)

I'm guessing this is probably intended, but if it, Use of Sanity should be locked to both Auto Squad and Battle list.
If it's not intended, then there's something going on between Auto Squad and Use of Sanity.
ref: https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10172#issuecomment-2291139802

### Version

5.5.1143 - d.150

### Log files

Combat error (without AutoSquad):
[log_error.txt](https://github.com/user-attachments/files/16624905/log_error.txt)

No combat error (AutoSquad enabled):
[log_valid.txt](https://github.com/user-attachments/files/16624952/log_valid.txt)

**Comment by status102** [comment]
![image](https://github.com/user-attachments/assets/48530883-decf-453f-99a5-46e05c8d700f)

seems good in old version

**Comment by status102** [comment]
also works well on 165afc8d90fd99d113d3d224b24c630c52dff849

**Comment by Constrat** [comment]
But you can see that there's no usemedicine subtask with that nightly.
And the subtask appears if the autosquad is turned on.

**Comment by Constrat** [comment]
Ok. Now it worked. No idea how.
