### ISSUE TITLE
 自动战斗在关卡（如 AS-S-1）存在教程时无法从暂停中退出

### ISSUE THREAD

**Issue by mslxl** [MaaAssistantArknights/MaaAssistantArknights#10247]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

在最新的 AS-S-1 关卡中，可能是干员识别的逻辑和教程（杜宾的对话）冲突导致 MAA 无法退出暂停，并依次尝试放置所有干员。过程见视频

使用作业 https://prts.plus/?op=40311

### Version

Resource Version: 太阳甩在身后 https://github.com/MaaAssistantArknights/MaaResource/commit/31956ebb86d13b4580ace21f969265e572040753
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[asst.log](https://github.com/user-attachments/files/16624878/asst.log)
[gui.log](https://github.com/user-attachments/files/16624880/gui.log)

大概从 2024-08-15 19:48:30.064 开始，有3次尝试，均存在此问题

### 配置信息

[gui.json](https://github.com/user-attachments/files/16624889/gui.json)

Bluestack5国际版 1920x1080 240DPI 60FPS

开启 GPU 加速推理，NVIDIA GeForce GTX 1650 Laptop

### 截图

https://github.com/user-attachments/assets/c53a3056-5492-43ce-925a-bf7373f48252

Edited: 似乎视频没法播放，压缩包：
[recording.zip](https://github.com/user-attachments/files/16625033/recording.zip)

**Comment by Saratoga-Official** [comment]
开mumu截图增强可以解决，截图快能先暂停后触发对话

**Comment by HX3N** [comment]
It seems that the OCR recognition didn't work because the screen was blocked when Instructor `杜宾` was giving the explanation.
For now, if you keep clicking the screen to skip the explanation while it's being given, it will work properly.

<details><summary>log</summary>

``` python
[2024-08-15 19:51:34.756][TRC][Px3b7c][Tx315c] asst::BattleProcessTask::check_in_battle | leave, 8 ms
[2024-08-15 19:51:34.787][TRC][Px3b7c][Tx315c] asst::WordOcr [{ : [ 0, 0, 125, 41 ], score: 0.000000 }] by OCR Rec , cost 31 ms
[2024-08-15 19:51:34.787][WRN][Px3b7c][Tx315c] ocr with preprocess got a invalid name, try to use detect model
[2024-08-15 19:51:34.835][TRC][Px3b7c][Tx315c] asst::WordOcr [{ 、、: [ 0, 0, 191, 37 ], score: 0.659057 }] by OCR Pipeline , cost 48 ms
[2024-08-15 19:51:34.836][TRC][Px3b7c][Tx315c] Proceed [{ 、、: [ 5, 177, 191, 37 ], score: 0.659057 }]
[2024-08-15 19:51:34.836][ERR][Px3b7c][Tx315c] name is empty

~~~~~~~~

[2024-08-15 19:51:37.215][TRC][Px3b7c][Tx315c] asst::BattlefieldMatcher::pause_button_analyze count 375 threshold 200
[2024-08-15 19:51:37.225][TRC][Px3b7c][Tx315c] The best match is { name: 桃金娘, matched: [ 0, 0, 60, 60 ] } 桃金娘
[2024-08-15 19:51:37.225][TRC][Px3b7c][Tx315c] The best match is { name: 德克萨斯, matched: [ 0, 0, 60, 60 ] } 德克萨斯
[2024-08-15 19:51:37.226][TRC][Px3b7c][Tx315c] The best match is { name: 能天使, matched: [ 0, 0, 60, 60 ] } 能天使
[2024-08-15 19:51:37.226][TRC][Px3b7c][Tx315c] The best match is { name: , matched: [ 0, 0, 60, 60 ] } 
[2024-08-15 19:51:37.226][TRC][Px3b7c][Tx315c] The best match is { name: 夜莺, matched: [ 0, 0, 60, 60 ] } 夜莺
[2024-08-15 19:51:37.227][TRC][Px3b7c][Tx315c] The best match is { name: 逻各斯, matched: [ 0, 0, 60, 60 ] } 逻各斯
[2024-08-15 19:51:37.227][TRC][Px3b7c][Tx315c] The best match is { name: 塞雷娅, matched: [ 0, 0, 60, 60 ] } 塞雷娅
[2024-08-15 19:51:37.227][TRC][Px3b7c][Tx315c] The best match is { name: 艾雅法拉, matched: [ 0, 0, 60, 60 ] } 艾雅法拉
[2024-08-15 19:51:37.227][TRC][Px3b7c][Tx315c] The best match is { name: 煌, matched: [ 0, 0, 60, 60 ] } 煌
[2024-08-15 19:51:37.227][TRC][Px3b7c][Tx315c] asst::BattleProcessTask::check_in_battle | enter

```

</details>

**Comment by mslxl** [comment]
@HX3N  Would it be possible to detect pause button before place operator? I think this would be the simplest to fix it. Besides, it hard to meet this bug since I installed bluestack to an old HDD, which is rare nowadays.

@Saratoga-Official 那可能是我这边运行的太慢了导致的，~~我把模拟器塞到了一块祖传HDD上~~

**Comment by HX3N** [comment]
> 到头来还是要点对话吗，附上我自己测试的视频，没触发过这个bug，对话前就把干员点完了

If the screenshot delay is minimal like with Mumu screenshot enhance, it wouldn't be an issue. However, with Bluestack, there usually seems to be a delay of about 300~500ms, which could cause problems. I just tested it, and I encountered the same issue.

**Comment by mslxl** [comment]
I tried to track the problem follow my mind within browser, and I found here:

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/7330494e589058fa95555f8d17306a182077a615/src/MaaCore/Task/BattleHelper.cpp#L217-L225

and here

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/7330494e589058fa95555f8d17306a182077a615/src/MaaCore/Task/BattleHelper.cpp#L273

It is worth mentioning that the `pause()` will run [this task](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/7330494e589058fa95555f8d17306a182077a615/resource/tasks.json#L4533C6-L4538), which just click the position of pause button without any match or check:

```json
    "BattlePause": {
        "algorithm": "JustReturn",
        "action": "ClickRect",
        "specificRect": [1170, 20, 60, 60],
        "postDelay": 200
    },
```

so that's interesting, MAA have already checked the button, but it checks too fast than game. 

Here is the reason I guessed: When the tour shows, the button become to `play` automatically, and then MAA click the button and invoke `check_pause_button()` immediately. The tour was closed slowly but MAA take the screenshot immediately, then MAA got a picture that including `play` button, which passed the check. 😢 When code executes to line 273, the game was paused directly.


It's hard to adapt all situation, but I have an _dirty_ idea: delay few time before check pause button. **I am not sure whether it breaks other features and whether it fixes the problem**, but I think the problem is here. 

Currently I do not have any development environment. So it still need other to test. Hope this information would help you.

**Comment by mslxl** [comment]
> @HX3N I tried to track the problem follow my mind within browser, and I found here:
> 
> https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/7330494e589058fa95555f8d17306a182077a615/src/MaaCore/Task/BattleHelper.cpp#L217-L225
> 
> and here
> 
> https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/7330494e589058fa95555f8d17306a182077a615/src/MaaCore/Task/BattleHelper.cpp#L273
> 
> It is worth mentioning that the `pause()` will run [this task](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/7330494e589058fa95555f8d17306a182077a615/resource/tasks.json#L4533C6-L4538), which just click the position of pause button without any match or check:
> 
> ```json
>     "BattlePause": {
>         "algorithm": "JustReturn",
>         "action": "ClickRect",
>         "specificRect": [1170, 20, 60, 60],
>         "postDelay": 200
>     },
> ```
> 
> so that's interesting, MAA have already checked the button, but it checks too fast than game changes.
> 
> Here is the reason I guessed: When the tour shows, the button become to `play` automatically, and then MAA click the button and invoke `check_pause_button()` immediately. The tour was closed slowly but MAA take the screenshot immediately, then MAA got a picture that including `play` button, which passed the check. 😢 When code executes to line 273, the game was paused directly.
> 
> It's hard to adapt all situation, but I have a _dirty_ idea: delay few time before check pause button. **I am not sure whether it breaks other features and whether it fixes the problem**, but I think the reason is here.
> 
> ~Currently I do not have any development environment. So it still need other to test.~ I just notice there is a field called `postDelay` in json, so I will try to modify it later.
> 
> Hope this information would help you.

It did not fix the problem completely, but sometimes it works. The text of tour are display word by word. The first click on the `pause` will make the tour display fully, and then MAA will check the button. After passed the check, MAA will try to analyze operator by click, which would close tour dialog and the game start to play. After analyze, MAA will click the position of `pause` button while the game is on `playing` status, which would pause the game. 

Maybe it need to change the code of `BattleHelper.cpp`， but currently I have no tools to modify and compile code.
