### ISSUE TITLE
[KR] 水月肉鸽点击尚不可进入的boss关卡然后卡死

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#10242]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

p1是debug\Roguelike的截图，
p2是点掉关卡详情的截图
实际上该左边的普通作战了，但是点进了boss

### Version

Core Version: v5.5.11453-alpha.1.d161.gfdbd7a05f

### 日志文件

[asst.bak - 副本.log](https://github.com/user-attachments/files/16621488/asst.bak.-.log)
这个风雨际会结束之后就是bug

### 配置信息

Mumu12，1080p，DPI280，60帧
Win11
MumuExtras 开启
GPU开启 3070ti laptop

### 截图

![2024-08-15_10-09-48-852_raw](https://github.com/user-attachments/assets/8b70dbbd-bfcd-4816-a40a-8cbe96132ec1)
![MuMu12-20240815-121551](https://github.com/user-attachments/assets/f154ce06-9f0d-44e7-9ac6-7d81273ef5cd)

**Comment by HX3N** [comment]
Is this issue recurring?
It doesn't seem to be an OCR problem, but rather an issue with the template image(If it’s not an external issue like misclicked).

**Comment by vvincee7** [comment]
我也遇到了同样的问题，卡在了地图详情里

**Comment by Magic-Turtlecn** [comment]
我也遇到了这个问题

**Comment by PikaChen123** [comment]
It’s a recurring issue to me. I will try the 720 to see if it can be solved. 

> Is this issue recurring? I'm not sure why this is happening, as I've never experienced this issue before. It doesn't seem to be an OCR problem but rather an issue with the template image, unless it's due to something external like a misclick.
> 
> For now, try using a 720p resolution. Since the template images for KR were created in 720p, if the issue is related to the images, this might resolve it, though I'm not certain.

**Comment by PikaChen123** [comment]
> It’s a recurring issue to me. I will try the 720 to see if it can be solved.
> 
> > Is this issue recurring? I'm not sure why this is happening, as I've never experienced this issue before. It doesn't seem to be an OCR problem but rather an issue with the template image, unless it's due to something external like a misclick.
> > For now, try using a 720p resolution. Since the template images for KR were created in 720p, if the issue is related to the images, this might resolve it, though I'm not certain.

After I changed it to 720 I haven’t have issues yesterday

**Comment by Constrat** [comment]
Good. Use 720. Resolved

**Comment by vvincee7** [comment]
中国服务器，mumu12，在修改到了720分辨率后，今天仍然出现了此问题

**Comment by HX3N** [comment]
The 720p solution is specific to the YostarKR server. I'm not sure about other servers.

**Comment by PikaChen123** [comment]
> > 中国服务器，mumu12，在修改到了720分辨率后，今天仍然出现了此问题
> 
> If it's a similar issue, the 720p solution is specific to the YostarKR server. I'm not sure about other servers.

我用的就是中国服务器 官服 mumu12。昨天和今天挂机刷了两个晚上 没有再遇到这个问题。需要再看看别的设置哪里不一样
I am using the Chinese server, two whole nights without issues. We should compare our settings to see differences.

**Comment by PikaChen123** [comment]
> > > 中国服务器，mumu12，在修改到了720分辨率后，今天仍然出现了此问题
> > 
> > 
> > If it's a similar issue, the 720p solution is specific to the YostarKR server. I'm not sure about other servers.
> 
> 我用的就是中国服务器 官服 mumu12。昨天和今天挂机刷了两个晚上 没有再遇到这个问题。需要再看看别的设置哪里不一样 I am using the Chinese server, two whole nights without issues. We should compare our settings to see differences.

After two days no issue with 720. I am having the same issues again today.
