### ISSUE TITLE
MUMU截图增强问题

### ISSUE THREAD

**Issue by TMXKLTX** [MaaAssistantArknights/MaaAssistantArknights#10245]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

在使用MUMU增强模式的时候游戏处于前台但是却只能识别模拟器的主页面，并非是路径，实例编号和屏幕编号的问题（更改后只能使用最开始的识别模式）貌似很多个版本都有这个问题，但不清楚是否只在我这里出现。

### Version

UI Version: v5.5.11453-alpha.1.d161.gfdbd7a05f
Core Version: v5.5.11453-alpha.1.d161.gfdbd7a05f

### 日志文件

[asst.log](https://github.com/user-attachments/files/16624038/asst.log)
[gui.log](https://github.com/user-attachments/files/16624039/gui.log)
中途某几个版本可以使用，后面就不行了

### 配置信息

[gui.json](https://github.com/user-attachments/files/16624052/gui.json)
Windows 11 家庭中文版 23H2 22631.4037
mumu模拟器 1920*1080 DPI:280 165帧（模拟器帧率增强） 开启截图增强

### 截图

![1](https://github.com/user-attachments/assets/3b0c3701-1c84-4e94-9f6c-1feb23d17b8e)
![2](https://github.com/user-attachments/assets/5dd931b2-d59f-41ad-aa69-0e917602a41d)

### 还有别的吗？

暂无

**Comment by Constrat** [comment]
![image](https://github.com/user-attachments/assets/14242320-d1cc-480b-bb74-2c26f0bb34b6)
From docs, did you try this?

**Comment by TMXKLTX** [comment]
Thank you, after off this function it worked.

**Comment by Constrat** [comment]
Docs exist for this exact reason :)

**Comment by Saratoga-Official** [comment]
我觉得可以直接duplicate了，前面的issue就有问这个问题，建议提问前查一下关掉的issue有没有人问，没人问再提
