### ISSUE TITLE
自动战斗时干员无法识别

### ISSUE THREAD

**Issue by infected-apricity** [MaaAssistantArknights/MaaAssistantArknights#10255]
内测版v5.5.11453 使用自动战斗时无法识别到黍
<img width="600" alt="3CEB3818FEE8438383EC6C9C019E4672" src="https://github.com/user-attachments/assets/414db21e-be5d-4dce-997c-d35bb4bb3f04">

**Comment by zzyyyl** [comment]
日志

**Comment by infected-apricity** [comment]
[gui.log](https://github.com/user-attachments/files/16641752/gui.log)
[asst.bak.zip](https://github.com/user-attachments/files/16641867/asst.bak.zip)
[asst.log](https://github.com/user-attachments/files/16641881/asst.log)

**Comment by infected-apricity** [comment]
第二个文件59MB，被迫压缩了一下

**Comment by zzyyyl** [comment]
你编队界面黍在什么位置啊（

**Comment by zzyyyl** [comment]
顺带一提，我没问题（x
![image](https://github.com/user-attachments/assets/e440b2b6-70a7-453f-b765-44e379a204ba)

另外建议用 maa 时分辨率设成 1280x720（

**Comment by infected-apricity** [comment]
> 你编队界面黍在什么位置啊（

我给黍弄了特别关注好像，应该是最前面的

**Comment by infected-apricity** [comment]
> 建议用 maa 时分辨率设成 1280x720
> 
> 顺带一提，我没问题（x
> 
> ![image](https://private-user-images.githubusercontent.com/74587068/358833762-e440b2b6-70a7-453f-b765-44e379a204ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NDk5NzYsIm5iZiI6MTcyMzk0OTY3NiwicGF0aCI6Ii83NDU4NzA2OC8zNTg4MzM3NjItZTQ0MGIyYjYtNzBhNy00NTNmLWI3NjUtNDRlMzc5YTIwNGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDAyNTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYTkxM2JmMWFkYWQwNzYzMWFiODMxZDAxNTNlMzZhNGYwZGY3ZmY0NDMwZjc0M2NiZmE0MGQ3ZTczOThhODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x58OLFHffR-Q0gq-4ALgb_InfnG4W9M_OyYHtGtEhUY)

那我改一下分辨率再试一下吧，谢谢啦

**Comment by infected-apricity** [comment]
![image](https://github.com/user-attachments/assets/f4abfbbe-76bb-4937-81b5-21aa2735d334)
好像恢复正常了，再次感谢
