### ISSUE TITLE
Fight Tasks Error on Event Stages HS-7, HS-8, and HS-9 After 'Trials for Navigator' Update

### ISSUE THREAD

**Issue by Wirowo** [MaaAssistantArknights/MaaAssistantArknights#10258]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

After the Trials for Navigator event update, the Fight tasks errors out when selecting event stages (From Here a People Sows) such as HS-7, HS-8, and HS-9. This issue doesn't happen with other stages.

First-time bug reporting, my apologies for any mistakes made.

### Version

Resource Version: Here A People Sows
UI Version: v5.5.11452
Core Version: v5.5.11452

### Log files

[asst.log](https://github.com/user-attachments/files/16642278/asst.log)
[gui.log](https://github.com/user-attachments/files/16642279/gui.log)

### Configuration information

[gui.json](https://github.com/user-attachments/files/16642281/gui.json)
Windows 10, MuMu 12 Global Version 3.8.18, 1920 x 1080 resolution. DPI is 1600 and frame rate was 144, but the same happens at 60 and 30. 
MuMu screenshot is enabled.
GPU acceleration is enabled with an RTX 4070 Mobile.

### Screenshots

This is the screen where the Fight Task errors out and doesn't continue. There were no other screenshots in the debug folder.
![MuMu12-20240816-182059](https://github.com/user-attachments/assets/c3fc4953-238c-430c-824f-6c65c2fc8237)

**Comment by ABA2396** [comment]
We're working on generic navigation. So for now, let's go with current/last

**Comment by swablueme** [comment]
I have been using the internal beta (it's linked on the main github page) for now, as it has the changes for that. Otherwise you can just use current/last.

**Comment by Wirowo** [comment]
Just tested it, and I can confirm that in the beta the issue has been resolved. 

Thank you very much for the clarification. When I initially tested, the fix wasn't in place yet, but everything is working smoothly now. I will be closing the issue as it will probably be fixed in the next release. Thanks MAA team!
