### ISSUE TITLE
保全LT-3 LT-5 作战前 退回到桌面 后台也没了

### ISSUE THREAD

**Issue by YuguangNevL** [MaaAssistantArknights/MaaAssistantArknights#10260]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

保全LT-3 LT-5 作战前 退回到桌面 后台也没了

### Version

UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[debug.zip](https://github.com/user-attachments/files/16643240/debug.zip)

### 配置信息

[gui.json](https://github.com/user-attachments/files/16643246/gui.json)
版本	Windows 10 专业版
版本号	21H2
安装日期	‎2023/‎3/‎24
操作系统内部版本	19044.2846
体验	Windows Feature Experience Pack 120.2212.4190.0
MUMU12  1280x720 DPI240 144Hz
MUMU截图增强开启
GPU加速没开

**Comment by Miuzarte** [comment]
有没有想过可能是游戏自己崩了

**Comment by YuguangNevL** [comment]
> 有没有想过可能是游戏自己崩了

草，我把配置提到4G好像能正常运行了（ 粥粥对于模拟器要求还挺高
