### ISSUE TITLE
关于肉鸽初始阵容的建议

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#1026]
大号有山，选的山，
小号有煌有棘刺无山，却选的煌
建议将棘刺的优先级提高
还有建议增加肉鸽初始队伍选择的自定义框（或指定选择）
如山，凯尔希，棘刺，煌，令等较强开局

**Comment by ntgmc** [comment]
那能否借一个山？我的煌总是撑不了多久奶不回来，棘刺起码可以自回血

**Comment by zzyyyl** [comment]
助战估计不会做了（
~~煌不是也有紧急除颤吗~~

**Comment by ABA2396** [comment]
好像是没准备做肉鸽借人来着，不过肉鸽都是挂机用的，应该也不用在意这么点效率差距了吧（）

**Comment by ntgmc** [comment]
主要是经常遇到高压的时候（其实也不算高压），奶就奶不回来了，然后就全寄了，接着就结束了，最后可能连第二层的第一关都过不去，我之前拿山的时候试过打到第四层（感觉这样效率高，实际上可能没高多少）

**Comment by MistEO** [comment]
你自己打肯定不一样啊，再怎么也没人聪明的。总是第二层寄估计练度有点低

**Comment by VictoryHero** [comment]
MAA打肉鸽主要用来刷蜡烛，快就完事儿了，要想打得高，还得上手动。

MistEO ***@***.***> 于2022年6月30日周四 01:36写道：

**Comment by ntgmc** [comment]
能加一个自选干员开局吗，指定那种（就是选择框，选令，山，凯尔希等强力干员）

**Comment by WWPXX233** [comment]
可以使用一个开局自选干员在maa里面设置，但是令 凯尔西等带召唤物的干员maa可能不太会使用建议还是使用常规干员比较好

**Comment by MistEO** [comment]
好几个月前的 Issue，现在能自定义开局干员了，我关！
