### ISSUE TITLE
自动编队干员识别错误（应编入塞、黍，实际编入雷蛇、泥岩）

### ISSUE THREAD

**Issue by HydrogenDeuterium** [MaaAssistantArknights/MaaAssistantArknights#10261]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

参见 #9239 ，编队时选择干员错误
看表现应该就是因为 #9853 里面讲的回弹问题导致的

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[gui.log](https://github.com/user-attachments/files/16644034/gui.log)
[asst.zip](https://github.com/user-attachments/files/16644035/asst.zip)

### 配置信息

[gui.json](https://github.com/user-attachments/files/16644036/gui.json)

### 截图

![image](https://github.com/user-attachments/assets/00ee28f2-a21b-4abb-95be-2b1fd1b174b6)
回弹界面

### 还有别的吗？

N/A

**Comment by HydrogenDeuterium** [comment]
研究了一下 这个改 /resource/tasks.json 的 BattleFormationOperListSwipeToTheLeft 可以解决吗？能的话我就自己改改看能不能修

**Comment by Daydreamer114** [comment]
请填写配置信息

**Comment by zzyyyl** [comment]
怎么会差这么多，感觉可以加一个识别到画面中空白太多的时候先 sleep 一会儿（
