### ISSUE TITLE
在基建换班中加入“不将训练室训练位干员放入其他位置”选项

### ISSUE THREAD

**Issue by xxxxxxxxxhzz** [MaaAssistantArknights/MaaAssistantArknights#10264]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

用logos练老猫专2到专3技能书不够了等着刷，结果给我把老猫放控制中枢去了没绷住

**Comment by Daydreamer114** [comment]
你如果使用了排班表，排班表优先级最高，会强制安排用户指定的干员；
如果没使用排班表，请找到log或复现此问题，提交issue。

**Comment by Daydreamer114** [comment]
建议不要纠结这个问题了，省几个小时意义不大，有需求可以自己写排班表
目前只有宿舍不放置已入驻干员
