### ISSUE TITLE
自动战斗神秘代码问题

### ISSUE THREAD

**Issue by RYUbot114** [MaaAssistantArknights/MaaAssistantArknights#10277]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

下载最新地图包进行替换之后，自动战斗输入代码会显示未找到对应作业。需要挂vpn才能搜索到相应作业

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

时间为8月18日20点08分
[asst.zip](https://github.com/user-attachments/files/16648329/asst.zip)
[gui.log](https://github.com/user-attachments/files/16648330/gui.log)

### 配置信息

win11
[gui.json](https://github.com/user-attachments/files/16648326/gui.json)

### 截图

![屏幕截图 2024-08-18 200733](https://github.com/user-attachments/assets/adc38355-03c1-46c0-aecc-45073a319467)

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/160d8c3d-cb3b-422f-b800-2f0a7a43b52e)
你设了代理，但没开代理
