### ISSUE TITLE
肉鸽异常

### ISSUE THREAD

**Issue by ZZYSBY** [MaaAssistantArknights/MaaAssistantArknights#10272]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

可能是某次更新导致的问题，最近至少3天内都有十分密集的问题发生，肉鸽关卡中，无法部署干员，界面会一直卡在附件的照片那种状态并知道此关卡因生命耗尽而结束，可能经常发生问题的为仇白干员
![微信图片_20240818162458](https://github.com/user-attachments/assets/0de00ac0-0788-40a0-858e-78a983782bde)

### Version

太阳甩在身后
v5.5.11452
v5.5.11452

### 日志文件

[Desktop.zip](https://github.com/user-attachments/files/16647684/Desktop.zip)

### 配置信息

[gui.json](https://github.com/user-attachments/files/16647687/gui.json)
win10工作站版，mumu12，1600*900，DPI：1000，60
开启截图增强
GPU：NVIDIA GeForce GTX 1650 ti

### 还有别的吗？

最近3天内的肉鸽都是第一关就输了，挂了3天等级一级都没涨，每次肉鸽的时间大概20多分钟才能打完一关

**Comment by Saratoga-Official** [comment]
dpi调那么高是想干嘛
可以尝试下图方法解决![Screenshot_2024-08-20-12-06-31-702_com.tencent.mobileqq-edit.jpg](https://github.com/user-attachments/assets/07b2c079-4f5d-4a54-b80c-bb2480243805)
