### ISSUE TITLE
希望外部通知支持同时启用多个通知配置

### ISSUE THREAD

**Issue by xiaofeiTM233** [MaaAssistantArknights/MaaAssistantArknights#10270]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

外部通知现在一个配置只能选择启用一个通知配置
假设我现在需要两个通道SMTP和Server Chan都发送通知则无法满足需求

### 有什么好的想法？

支持同时启用多个通知配置

### 其他内容

目前还不支持配置 Webhook 通知，不然可以自己做一下转发的……
Webhook 通知相关 Issue：#9082

**Comment by xiaofeiTM233** [comment]
![image](https://github.com/user-attachments/assets/0efd87b7-82f6-4289-baaa-e35975af3063)
不是很喜欢 Server Chan，要是能手动写 Webhook 就好了

**Comment by ABA2396** [comment]
不知道好不好使，我也没用过外部通知，可以试试看）
