### ISSUE TITLE
定时执行的问题修改方案

### ISSUE THREAD

**Issue by woshilinbei11** [MaaAssistantArknights/MaaAssistantArknights#10289]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

当我们在使用maa进行挂机时，定时执行是一个长时间不在电脑身边的人的一个福音，but，定时执行它在打资源收集关卡中，只能打一日的关卡，如我在刷理智中设置打PR-A-2，然而此关不是每天都开放的，因此可以对此进行改进

### 有什么好的想法？

在定时执行中设置不同日期，星期，时间可以使用不同的配置，以方便玩家的使用，谢谢

**Comment by LinXu-LinXu** [comment]
![image](https://github.com/user-attachments/assets/fdb07780-7ba2-4571-9857-bc6088b94ed1)

**Comment by ABA2396** [comment]
所以为什么不用刷理智里的备选关卡）

**Comment by Constrat** [comment]
Both are correct answers:
Either create different config with different schedules, or just use alternate stages as they were made for this exact reason.

**Comment by woshilinbei11** [comment]
哦，谢谢
