### ISSUE TITLE
关于maa可能出现的截图问题

### ISSUE THREAD

**Issue by TAN90temp** [MaaAssistantArknights/MaaAssistantArknights#10297]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

如题，在使用maa时出现截图问题导致程序无法正常运行且无报错，且其他maa程序无此异常状况

### Version

Resource Version: 太阳甩在身后
UI Version: v5.6.0-beta.1
Core Version: v5.6.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16660753/asst.log)
[gui.log](https://github.com/user-attachments/files/16660770/gui.log)

### 配置信息

[gui.json](https://github.com/user-attachments/files/16660801/gui.json)
使用了mumu12的截图增强与rts3060的gpu加速

### 截图

![屏幕截图 2024-08-19 204857](https://github.com/user-attachments/assets/b1e3d2c5-1ad9-4286-99d0-68f0196e61d5)

**Comment by Constrat** [comment]
![image](https://github.com/user-attachments/assets/1798a9f0-8617-41c0-a55e-1d8bc5e86177)
It's always the same fucking thing.
Either read the documentation or older issues.
