### ISSUE TITLE
任务出错：Fight

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#1029]
Hi Maa Team:

![image](https://user-images.githubusercontent.com/74366156/176345734-576fa5c6-7a4b-48b3-861a-0f90fffa3f56.png)
执行到第六次时报错，停止再启动直接报错。似乎是在结算界面卡顿导致的？

Thanks
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9007045/asst.log)

**Comment by MistEO** [comment]
刷理智任务并不支持从关卡结算界面开始任务。

前一次任务失败是因为 adb 连接断开了，看起来像是模拟器的问题
