### ISSUE TITLE
更新时非当前配置文件不会获取到更新公告

### ISSUE THREAD

**Issue by Yuanlailai** [MaaAssistantArknights/MaaAssistantArknights#10305]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

我在"美服"配置下更新，"Default"下查看不到最新的更新日志

![image](https://github.com/user-attachments/assets/ca6ff023-9d9a-47c2-845a-72412cfe8d34)
![20240820134531](https://github.com/user-attachments/assets/7c4506d2-479c-4da7-b66b-8a60fd7552b6)
![20240820134508](https://github.com/user-attachments/assets/1916f2ea-a1ce-42d2-bee1-dda04c18c596)

### Version

UI Version: v5.6.0-beta.1

### 日志文件

ui和配置问题，日志应当不需要

### 配置信息

[gui.json](https://github.com/user-attachments/files/16669572/gui.json)

### 还有别的吗？

公告似乎也有也有类似问题，这类应该放入全局变量中吧
![image](https://github.com/user-attachments/assets/9250d21f-6e2f-46e5-bfe5-045401096ca9)

**Comment by Saratoga-Official** [comment]
看了一下更新日志和公告都是gui.json存着的

**Comment by Yuanlailai** [comment]
652行，配置美服下最新的更新日志确实存着，因为我是在这个配置下更新的，但180行(5.5.11451)，416行(5.11452)，就是老版本了，公告可能是当时在11451的时候停止了资源更新，在default下获取了，但其他配置文件的公告就还是老的github actions

![image](https://github.com/user-attachments/assets/ec2185eb-b2fc-4718-9429-6bfcbdda33ba)
![image](https://github.com/user-attachments/assets/16ca8370-696e-456c-a8a3-44ace4e9d8d0)

**Comment by ABA2396** [comment]
等下改改

**Comment by ABA2396** [comment]
af27e95fdc90aa886edabfe054bba8ccd26e4ad3 fixed
