### ISSUE TITLE
肉鸽商店根据已有干员购买藏品

### ISSUE THREAD

**Issue by guanosine-diphosphate** [MaaAssistantArknights/MaaAssistantArknights#1030]
我的肉鸽队伍里没有医疗干员，但是在商店中会购买直接精二医疗干员的藏品
之前也好几次遇到这种情况，比如没有特种还买了
希望可以识别肉鸽编队的干员种类，再判断是否购买相关藏品
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9007394/asst.log)

**Comment by ABA2396** [comment]
购买藏品现在没做识别，随缘（）
