### ISSUE TITLE
保全白云间药铺玉门市集的地图坐标问题

### ISSUE THREAD

**Issue by Saratoga-Official** [MaaAssistantArknights/MaaAssistantArknights#10303]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

保全白云间药铺玉门市集部分关卡存在坐标位置问题，导致开不了技能或摆不上人等情况
例如他乡（lt3）这个图，在坐标3 4无法使用技能

### Version

Resource Version: 太阳甩在身后
UI Version: v5.6.0-beta.1.d030.g078d8ee50
Core Version: v5.6.0-beta.1.d030.g078d8ee50

### 日志文件

[gui.log](https://github.com/user-attachments/files/16667880/gui.log)
[asst.zip](https://github.com/user-attachments/files/16667885/asst.zip)

### 配置信息

WIN11系统 1600×900分辨率240dpi
MUMU12截图增强开启
GPU加速开启
[gui.json](https://github.com/user-attachments/files/16667931/gui.json)

### 截图

![他乡](https://github.com/user-attachments/assets/6d79194f-fb07-4f7f-b9e5-54a2c5995911)

### 还有别的吗？

玉门天灾工事和正常高台不一样，改地图也不行

**Comment by status102** [comment]
LT几？只有这张图是吧

**Comment by Saratoga-Official** [comment]
> LT几？只有这张图是吧

LT3 4 5都有问题

**Comment by status102** [comment]
> > LT几？只有这张图是吧
> 
> LT3 4 5都有问题 剩下的勉强凑合能开

彳亍，还没打到，没法测试

**Comment by status102** [comment]
参照地图站，这个位置确实不是高台，考虑加新算法了
