### ISSUE TITLE
当前内测版Full Changelog链接错误

### ISSUE THREAD

**Issue by Manicsteiner** [MaaAssistantArknights/MaaAssistantArknights#10308]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v5.6.0-beta.1.d004.g5fdea2ada
以此为例，Full Changelog中 v5.6.0"-"beta.1 文本和链接均包含一对额外的引号，导致无法转到正确的compare界面
问题可能在release-nightly-ota.yml#L78
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/d539d26ac853119ead720b3c68f84ddb2f446724/.github/workflows/release-nightly-ota.yml#L78

### Version

v5.6.0-beta.1.d004.g5fdea2ada - v5.6.0-beta.1.d030.g078d8ee50

### 日志文件

https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/10461848736/job/28970997316

### 配置信息

---

**Comment by zzyyyl** [comment]
73505b0c5273c0a29a274ed9ab0d43ca7d984e9f @MistEO

**Comment by Constrat** [comment]
I'm wondering why it started appearing only now? Or we never noticed this before?

**Comment by Constrat** [comment]
![image](https://github.com/user-attachments/assets/7f4e6177-7736-4dbd-a4a3-9d831afd2dca)
