### ISSUE TITLE
公招"干员"中的“干”字无法识别

### ISSUE THREAD

**Issue by Here-is-Daiyu** [MaaAssistantArknights/MaaAssistantArknights#10302]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

在公招识别时对"干员"中的“干”字无法识别，多次测试后发现此问题与mumu截图增强无关，猜测为识别时直接忽略了“干”字

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[asst.log](https://github.com/user-attachments/files/16667831/asst.log)
[gui.log](https://github.com/user-attachments/files/16667832/gui.log)
最后一次尝试和出错事件：[2024-08-20 10:13:00.814]

### 配置信息

[gui.json](https://github.com/user-attachments/files/16667841/gui.json)
版本	Windows 11 家庭中文版
版本号	23H2
mumu12明日方舟专版 
分辨率 1600*900 DPI 240 fps 60
未开启截图增强
*实际检测发现是否开启截图增强与是否识别出错无关

### 截图

![image](https://github.com/user-attachments/assets/2df053b6-9067-4458-ac0d-cf8f456fe158)
![MuMu12-20240820-101317](https://github.com/user-attachments/assets/3d2fc11b-6bd8-4a0f-98ac-6f141c5b4afc)
![谁家好人干字识别不出来啊（](https://github.com/user-attachments/assets/39ed636e-ffa1-4fed-9eb2-1938acd8eefa)

### 还有别的吗？

之前测试时发现在自动作战的选择作战时也会出现无法识别的问题，但是换了模拟器没有记录就这样了把（
建议在处理时改为模糊匹配（）

**Comment by Saratoga-Official** [comment]
GPU加速开了吗

**Comment by Here-is-Daiyu** [comment]
没开（
忘了写了（）

**Comment by Saratoga-Official** [comment]
按理说不会忽略干字的，你这种情况很像开了GPU加速，目前已知就GPU加速会影响OCR缺字
不会是专版问题吧，我是无法复现，都是正常识别的

**Comment by Here-is-Daiyu** [comment]
重新试了一下又行了（
很怪

**Comment by ayhhyhh** [comment]
我也出现过类似卡公招的问题，最近感觉还挺频繁
```
[2024-08-20 18:47:24.335][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | enter
[2024-08-20 18:47:24.389][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 32 ms
[2024-08-20 18:47:24.434][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 23 ms
[2024-08-20 18:47:24.480][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 23 ms
[2024-08-20 18:47:24.529][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 25 ms
[2024-08-20 18:47:24.538][INF][Px1854][Tx1e48] Assistant::append_callback | ConnectionInfo {"details":{"avg":8,"max":11,"min":6},"uuid":"c23e3607deb978f1","what":"ScreencapCost"}
[2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 26 ms
[2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | leave, 242 ms
[2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] ready to sleep 500
[2024-08-20 18:47:25.079][TRC][Px1854][Tx1e48] end of sleep 500
[2024-08-20 18:47:25.079][INF][Px1854][Tx1e48] Assistant::append_callback | SubTaskError {"class":"asst::AutoRecruitTask","details":{},"subtask":"AutoRecruitTask","taskchain":"Recruit","taskid":2,"uuid":"c23e3607deb978f1","what":"RecruitError","why":"识别错误"}
```

```
[2024-08-20 18:51:55.789][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | enter
[2024-08-20 18:51:55.796][INF][Px1854][Tx1e48] Assistant::append_callback | ConnectionInfo {"details":{"avg":7,"max":12,"min":6},"uuid":"c23e3607deb978f1","what":"ScreencapCost"}
[2024-08-20 18:51:55.879][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 71 ms
[2024-08-20 18:51:55.970][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 71 ms
[2024-08-20 18:51:56.063][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 37, 18 ], score: 0.999727 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 73 ms
[2024-08-20 18:51:56.148][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 67 ms
[2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 68 ms
[2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | leave, 447 ms
[2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] ready to sleep 500
[2024-08-20 18:51:56.737][TRC][Px1854][Tx1e48] end of sleep 500
[2024-08-20 18:51:56.737][INF][Px1854][Tx1e48] Assistant::append_callback | SubTaskError {"class":"asst::AutoRecruitTask","details":{},"subtask":"AutoRecruitTask","taskchain":"Recruit","taskid":8,"uuid":"c23e3607deb978f1","what":"RecruitError","why":"识别错误"}
```

**Comment by zzyyyl** [comment]
> 我也出现过类似卡公招的问题，最近感觉还挺频繁
> 
> ```
> [2024-08-20 18:47:24.335][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | enter
> [2024-08-20 18:47:24.389][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 32 ms
> [2024-08-20 18:47:24.434][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 23 ms
> [2024-08-20 18:47:24.480][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 23 ms
> [2024-08-20 18:47:24.529][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 25 ms
> [2024-08-20 18:47:24.538][INF][Px1854][Tx1e48] Assistant::append_callback | ConnectionInfo {"details":{"avg":8,"max":11,"min":6},"uuid":"c23e3607deb978f1","what":"ScreencapCost"}
> [2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 26 ms
> [2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | leave, 242 ms
> [2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] ready to sleep 500
> [2024-08-20 18:47:25.079][TRC][Px1854][Tx1e48] end of sleep 500
> [2024-08-20 18:47:25.079][INF][Px1854][Tx1e48] Assistant::append_callback | SubTaskError {"class":"asst::AutoRecruitTask","details":{},"subtask":"AutoRecruitTask","taskchain":"Recruit","taskid":2,"uuid":"c23e3607deb978f1","what":"RecruitError","why":"识别错误"}
> ```
> 
> ```
> [2024-08-20 18:51:55.789][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | enter
> [2024-08-20 18:51:55.796][INF][Px1854][Tx1e48] Assistant::append_callback | ConnectionInfo {"details":{"avg":7,"max":12,"min":6},"uuid":"c23e3607deb978f1","what":"ScreencapCost"}
> [2024-08-20 18:51:55.879][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 71 ms
> [2024-08-20 18:51:55.970][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 71 ms
> [2024-08-20 18:51:56.063][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 37, 18 ], score: 0.999727 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 73 ms
> [2024-08-20 18:51:56.148][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 67 ms
> [2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 68 ms
> [2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | leave, 447 ms
> [2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] ready to sleep 500
> [2024-08-20 18:51:56.737][TRC][Px1854][Tx1e48] end of sleep 500
> [2024-08-20 18:51:56.737][INF][Px1854][Tx1e48] Assistant::append_callback | SubTaskError {"class":"asst::AutoRecruitTask","details":{},"subtask":"AutoRecruitTask","taskchain":"Recruit","taskid":8,"uuid":"c23e3607deb978f1","what":"RecruitError","why":"识别错误"}
> ```

单凭这么一段看不出什么，感觉是你在和maa抢鼠标

**Comment by ayhhyhh** [comment]
> > 我也出现过类似卡公招的问题，最近感觉还挺频繁
> > 
> > ```
> > [2024-08-20 18:47:24.335][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | enter
> > [2024-08-20 18:47:24.389][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 32 ms
> > [2024-08-20 18:47:24.434][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 23 ms
> > [2024-08-20 18:47:24.480][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 23 ms
> > [2024-08-20 18:47:24.529][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 25 ms
> > [2024-08-20 18:47:24.538][INF][Px1854][Tx1e48] Assistant::append_callback | ConnectionInfo {"details":{"avg":8,"max":11,"min":6},"uuid":"c23e3607deb978f1","what":"ScreencapCost"}
> > [2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 26 ms
> > [2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | leave, 242 ms
> > [2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] ready to sleep 500
> > [2024-08-20 18:47:25.079][TRC][Px1854][Tx1e48] end of sleep 500
> > [2024-08-20 18:47:25.079][INF][Px1854][Tx1e48] Assistant::append_callback | SubTaskError {"class":"asst::AutoRecruitTask","details":{},"subtask":"AutoRecruitTask","taskchain":"Recruit","taskid":2,"uuid":"c23e3607deb978f1","what":"RecruitError","why":"识别错误"}
> > ```
> > 
> > ```
> > [2024-08-20 18:51:55.789][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | enter
> > [2024-08-20 18:51:55.796][INF][Px1854][Tx1e48] Assistant::append_callback | ConnectionInfo {"details":{"avg":7,"max":12,"min":6},"uuid":"c23e3607deb978f1","what":"ScreencapCost"}
> > [2024-08-20 18:51:55.879][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 71 ms
> > [2024-08-20 18:51:55.970][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 71 ms
> > [2024-08-20 18:51:56.063][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 37, 18 ], score: 0.999727 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 73 ms
> > [2024-08-20 18:51:56.148][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 67 ms
> > [2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 68 ms
> > [2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | leave, 447 ms
> > [2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] ready to sleep 500
> > [2024-08-20 18:51:56.737][TRC][Px1854][Tx1e48] end of sleep 500
> > [2024-08-20 18:51:56.737][INF][Px1854][Tx1e48] Assistant::append_callback | SubTaskError {"class":"asst::AutoRecruitTask","details":{},"subtask":"AutoRecruitTask","taskchain":"Recruit","taskid":8,"uuid":"c23e3607deb978f1","what":"RecruitError","why":"识别错误"}
> > ```
> 
> 单凭这么一段看不出什么，感觉是你在和maa抢鼠标，根据OCR的结果来看你这都不在对应的界面里

> 没有抢鼠标的。如果我没记错的话，下边这段应该卡在停止公招页面。可能之后我再测一下。

**Comment by Saratoga-Official** [comment]
> > > 我也出现过类似卡公招的问题，最近感觉还挺频繁
> > > 
> > > ```
> > > [2024-08-20 18:47:24.335][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | enter
> > > [2024-08-20 18:47:24.389][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 32 ms
> > > [2024-08-20 18:47:24.434][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 23 ms
> > > [2024-08-20 18:47:24.480][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 23 ms
> > > [2024-08-20 18:47:24.529][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 25 ms
> > > [2024-08-20 18:47:24.538][INF][Px1854][Tx1e48] Assistant::append_callback | ConnectionInfo {"details":{"avg":8,"max":11,"min":6},"uuid":"c23e3607deb978f1","what":"ScreencapCost"}
> > > [2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 26 ms
> > > [2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | leave, 242 ms
> > > [2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] ready to sleep 500
> > > [2024-08-20 18:47:25.079][TRC][Px1854][Tx1e48] end of sleep 500
> > > [2024-08-20 18:47:25.079][INF][Px1854][Tx1e48] Assistant::append_callback | SubTaskError {"class":"asst::AutoRecruitTask","details":{},"subtask":"AutoRecruitTask","taskchain":"Recruit","taskid":2,"uuid":"c23e3607deb978f1","what":"RecruitError","why":"识别错误"}
> > > ```
> > > 
> > > ```
> > > [2024-08-20 18:51:55.789][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | enter
> > > [2024-08-20 18:51:55.796][INF][Px1854][Tx1e48] Assistant::append_callback | ConnectionInfo {"details":{"avg":7,"max":12,"min":6},"uuid":"c23e3607deb978f1","what":"ScreencapCost"}
> > > [2024-08-20 18:51:55.879][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 71 ms
> > > [2024-08-20 18:51:55.970][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 71 ms
> > > [2024-08-20 18:51:56.063][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 37, 18 ], score: 0.999727 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 73 ms
> > > [2024-08-20 18:51:56.148][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 67 ms
> > > [2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 68 ms
> > > [2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | leave, 447 ms
> > > [2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] ready to sleep 500
> > > [2024-08-20 18:51:56.737][TRC][Px1854][Tx1e48] end of sleep 500
> > > [2024-08-20 18:51:56.737][INF][Px1854][Tx1e48] Assistant::append_callback | SubTaskError {"class":"asst::AutoRecruitTask","details":{},"subtask":"AutoRecruitTask","taskchain":"Recruit","taskid":8,"uuid":"c23e3607deb978f1","what":"RecruitError","why":"识别错误"}
> > > ```
> > 
> > 单凭这么一段看不出什么，感觉是你在和maa抢鼠标，根据OCR的结果来看你这都不在对应的界面里
> 
> 没有抢鼠标的。如果~~我没记错的话~~(应该记错了)，~~下边这段应该卡在停止公招页面~~。忘了是卡在哪里，但是印象里有几次是卡在停止公招，可能之后我再测一下。

问题不太一样的请新开个issue而不是在老issue下反馈

**Comment by ayhhyhh** [comment]
> > > > 我也出现过类似卡公招的问题，最近感觉还挺频繁
> > > > ```
> > > > [2024-08-20 18:47:24.335][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | enter
> > > > [2024-08-20 18:47:24.389][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 32 ms
> > > > [2024-08-20 18:47:24.434][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 23 ms
> > > > [2024-08-20 18:47:24.480][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 23 ms
> > > > [2024-08-20 18:47:24.529][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 25 ms
> > > > [2024-08-20 18:47:24.538][INF][Px1854][Tx1e48] Assistant::append_callback | ConnectionInfo {"details":{"avg":8,"max":11,"min":6},"uuid":"c23e3607deb978f1","what":"ScreencapCost"}
> > > > [2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] asst::WordOcr [{ _: [ 0, 0, 480, 120 ], score: 0.940161 }] by OCR Pipeline , cost 26 ms
> > > > [2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | leave, 242 ms
> > > > [2024-08-20 18:47:24.578][TRC][Px1854][Tx1e48] ready to sleep 500
> > > > [2024-08-20 18:47:25.079][TRC][Px1854][Tx1e48] end of sleep 500
> > > > [2024-08-20 18:47:25.079][INF][Px1854][Tx1e48] Assistant::append_callback | SubTaskError {"class":"asst::AutoRecruitTask","details":{},"subtask":"AutoRecruitTask","taskchain":"Recruit","taskid":2,"uuid":"c23e3607deb978f1","what":"RecruitError","why":"识别错误"}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```
> > > > [2024-08-20 18:51:55.789][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | enter
> > > > [2024-08-20 18:51:55.796][INF][Px1854][Tx1e48] Assistant::append_callback | ConnectionInfo {"details":{"avg":7,"max":12,"min":6},"uuid":"c23e3607deb978f1","what":"ScreencapCost"}
> > > > [2024-08-20 18:51:55.879][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 71 ms
> > > > [2024-08-20 18:51:55.970][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 71 ms
> > > > [2024-08-20 18:51:56.063][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 37, 18 ], score: 0.999727 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 73 ms
> > > > [2024-08-20 18:51:56.148][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 67 ms
> > > > [2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] asst::WordOcr [{ 185: [ 115, 6, 36, 18 ], score: 0.999690 }, { 是否消耗一张加急许可立即完成招募?: [ 81, 53, 358, 19 ], score: 0.965904 }] by OCR Pipeline , cost 68 ms
> > > > [2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] asst::AutoRecruitTask::recruit_calc_task | leave, 447 ms
> > > > [2024-08-20 18:51:56.236][TRC][Px1854][Tx1e48] ready to sleep 500
> > > > [2024-08-20 18:51:56.737][TRC][Px1854][Tx1e48] end of sleep 500
> > > > [2024-08-20 18:51:56.737][INF][Px1854][Tx1e48] Assistant::append_callback | SubTaskError {"class":"asst::AutoRecruitTask","details":{},"subtask":"AutoRecruitTask","taskchain":"Recruit","taskid":8,"uuid":"c23e3607deb978f1","what":"RecruitError","why":"识别错误"}
> > > > ```
> > > 
> > > 
> > > 单凭这么一段看不出什么，感觉是你在和maa抢鼠标，根据OCR的结果来看你这都不在对应的界面里
> > 
> > 
> > 没有抢鼠标的。如果~我没记错的话~(应该记错了)，~下边这段应该卡在停止公招页面~。忘了是卡在哪里，但是印象里有几次是卡在停止公招，可能之后我再测一下。
> 
> 问题不太一样的请新开个issue而不是在老issue下反馈

好的，请见[#10149](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10149#issuecomment-2305149988)
谢谢！
