### ISSUE TITLE
[EN] RA auto randomly stop because of error

### ISSUE THREAD

**Issue by ItsukaHiro1111** [MaaAssistantArknights/MaaAssistantArknights#10301]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

After updating to beta and using Auto RA, this process randomly stop because of error (mostly at the reward screen in day 4)

### Version

Resource Version: Trials for Navigator
UI Version: v5.6.0-beta.1
Core Version: v5.6.0-beta.1

### Log files

[asst.log](https://github.com/user-attachments/files/16667645/asst.log)

### Configuration information

[gui.log](https://github.com/user-attachments/files/16667643/gui.log)

**Comment by Constrat** [comment]
Seems to get stuck on the SkipDay thing. But after 2 tries it should wipe the data.
