### ISSUE TITLE
日服薩米/水月肉鴿:選項上下並且不選擇

### ISSUE THREAD

**Issue by teiyanesu** [MaaAssistantArknights/MaaAssistantArknights#10313]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

選項上下跟不會選擇

### Version

Resource Version: 導灯の試練
UI Version: v5.6.0-beta.1
Core Version: v5.6.0-beta.1

### 日志文件

0820 21:56-21:57、21:24-21:26、、20:40左右、19:02左右
[debug.zip](https://github.com/user-attachments/files/16677123/debug.zip)

### 配置信息

win11
bluestacks 5 1280x720/240dpi/60fps
NVIDIA RTX4060ti
[gui.json](https://github.com/user-attachments/files/16677136/gui.json)

### 截图
![2024-08-20_21-57-38-465_raw](https://github.com/user-attachments/assets/34a8deff-fdae-48b1-9347-b55dac155232)
![2024-08-20_21-26-16-076_raw](https://github.com/user-attachments/assets/d09a4d52-3460-49ab-9402-b31b0046363c)
![2024-08-20_20-40-01-835_raw](https://github.com/user-attachments/assets/e64d4464-7d69-4f2c-9f69-9d32e24d8f7e)

包含一些太久沒LOG的但情況是一樣的截圖供參考
[Roguelike.zip](https://github.com/user-attachments/files/16677178/Roguelike.zip)

**Comment by Manicsteiner** [comment]
行き先を求めて/探寻前路 2024-08-20 21:56:13.923
识别正确，依次执行了三选二、三选三、三选二、三选一、二选二、二选一、一选一，然后卡在了一个选择了选项一的界面，正常来说不会进入这个界面，很奇怪，不确定发生了什么

利益工作/有利可图 2024-08-20 21:24:28.916
识别正确，执行了三选一，卡在了再次选择的界面，期间通过识别StageEncounterOptionUnknown点击了一次，下一步应该是`Sami@Roguelike@StageEncounterLeaveConfirm.png`，但得分只有0.72多一点

観測ステーション/科考站 2024-08-20 20:39:55.794
识别正确，正确点击一次，`Sami@Roguelike@StageEncounterLeaveConfirm.png`得分也只有0.72

観測ステーション/科考站 2024-08-20 19:02:43.908
识别正确，同上

或许需要重置一下`Sami@Roguelike@StageEncounterLeaveConfirm.png`了

**Comment by Manicsteiner** [comment]
挂了一中午，遇到两次`Sami@Roguelike@StageEncounterLeaveConfirm.png`，得分能到0.86，还是不好确定什么原因
```
[2024-08-21 12:58:08.492][TRC][Px4ce0][Tx50f8] match_templ | Sami@Roguelike@StageEncounterLeaveConfirm.png score: 0.862484 rect: [ 1116, 243, 161, 51 ] roi: [ 1069, 0, 211, 700 ]
[2024-08-21 13:33:52.745][TRC][Px4ce0][Tx50f8] match_templ | Sami@Roguelike@StageEncounterLeaveConfirm.png score: 0.862147 rect: [ 1116, 243, 161, 51 ] roi: [ 1069, 0, 211, 700 ]
```

**Comment by teiyanesu** [comment]
不太確定有沒有關聯,但其實上次這個[#10240](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10240#issuecomment-2295096125)也沒修好,即使手動改了ROI還是上下(更新v5.6.0-beta.1後測試),也是0.75分左右
[debug_log_0821_18.57.49.zip](https://github.com/user-attachments/files/16690621/debug_log_0821_18.57.49.zip)

**Comment by teiyanesu** [comment]
非專業不知道是否會因使用者而異
總之先打包上傳上文的LOG跟更換後的範本

>運行環境
win11/bluestacks 5 1280x720/240dpi/60fps/無開啟GPU
[debug_log+template.zip](https://github.com/user-attachments/files/16695412/debug_log%2Btemplate.zip)

**Comment by teiyanesu** [comment]
補充:
後來遇到了有利可圖,也過了
>[2024-08-22 01:26:55.168][TRC][Px3c9bc][Tx46388] match_templ | Sami@Roguelike@StageEncounterOptionUnknown.png score: 0.994021 rect: [ 1212, 297, 62, 21 ] roi: [ 1100, 0, 180, 700 ]
[2024-08-22 01:26:56.563][TRC][Px3c9bc][Tx46388] match_templ | Sami@Roguelike@StageEncounterLeaveConfirm.png score: 0.995576 rect: [ 1117, 324, 158, 48 ] roi: [ 1069, 0, 211, 700 ]
