### ISSUE TITLE
傀影肉鸽三个选项的bug

### ISSUE THREAD

**Issue by Arthur-hub-maker** [MaaAssistantArknights/MaaAssistantArknights#10329]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

照之前的修改过的方案还是不行

### Version

Resource Version: What the Firelight Casts - Retrospection
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[asst.log](https://github.com/user-attachments/files/16709692/asst.log)
[gui.log](https://github.com/user-attachments/files/16709693/gui.log)

### 配置信息

[gui.json](https://github.com/user-attachments/files/16709687/gui.json)

### 截图

![image](https://github.com/user-attachments/assets/f88b1a9d-adcb-4afe-ac66-a152937ee1d0)

**Comment by Arthur-hub-maker** [comment]
> asst.log is completely empty. Get asst.bak.log

[asst.bak.log](https://github.com/user-attachments/files/16713298/asst.bak.log)
mb i attached the wrong one

**Comment by Constrat** [comment]
Was it at the end of the log you sent?  Right before `2024-08-22 18:30:52.211`

**Comment by Arthur-hub-maker** [comment]
> Was it at the end of the log you sent? Right before `2024-08-22 18:30:52.211` Actually no, StageEncounterOcr at all in the entire log. Strange
> 
> This seems the log of a single run between `2024-08-22 17:41:04.258` and `2024-08-22 18:30:52.211`

[asst.bak.log](https://github.com/user-attachments/files/16714236/asst.bak.log)
u can have a look on this file i think the issue is shown now

**Comment by Arthur-hub-maker** [comment]
> Was it at the end of the log you sent? Right before `2024-08-22 18:30:52.211` Actually no, StageEncounterOcr at all in the entire log. Strange
> 
> This seems the log of a single run between `2024-08-22 17:41:04.258` and `2024-08-22 18:30:52.211`

[asst.bak.log](https://github.com/user-attachments/files/16714257/asst.bak.log)
how about now? u can have a look at the end of the log

**Comment by Constrat** [comment]
No idea, neither this one shows that StageEncounterOcr which is very strange, since if no Encounter is recognized, then MAA logic is to fallback to template recognition which always fails in these cases.

**Comment by lyu0131** [comment]
Getting the same problem here and when you actually finish the final boss on floor 5. There is this ending screen that you get and I also get stuck on that screen.

**Comment by Constrat** [comment]
Two different issues. They might have changed the ending screen template.
