### ISSUE TITLE
水月肉鸽点击异常导致卡死

### ISSUE THREAD

**Issue by Here-is-Daiyu** [MaaAssistantArknights/MaaAssistantArknights#10323]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

水月肉鸽中有出现错误点击到关卡地图预览并导致卡死的情况
*尚未测试其他肉鸽，但并没有发现过相同情况

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[gui.log](https://github.com/user-attachments/files/16700901/gui.log)
[新建 文本文档.txt](https://github.com/user-attachments/files/16700902/default.txt)
asst.log原文档有99MB有什么头绪吗(

### 配置信息

[gui.json](https://github.com/user-attachments/files/16700905/gui.json)
版本 Windows 11 家庭中文版
版本号 23H2
mumu12明日方舟专版
分辨率 1600*900 DPI 240 fps 60
未开启截图增强
GPU加速推理未开启

### 截图

![image](https://github.com/user-attachments/assets/38385f5d-6116-48de-8850-952ebd227e22)
非常好卡死，使我半个晚上消失（）
![2024-08-22_05-06-40-643_raw](https://github.com/user-attachments/assets/1d1ccb94-778d-47ee-835b-ac234604a3b4)
卡在这个位置大家有什么头绪吗（）
![image](https://github.com/user-attachments/assets/423a793a-114b-44cf-8e10-85e48a7ab893)
maa给我在.\debug\roguelike里截了159张这个图片（

### 还有别的吗？

已经阅读过
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8781 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8792 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8984
这几篇issue ~~就是因为看过了发现issue已经被关闭了才再提一次~~
似乎只出现在第三层关底boss前
之前也出现过好多次但换了模拟器没记录了（
建议通过检测
![image](https://github.com/user-attachments/assets/d1175f86-48c6-449d-a548-619aa376fca2)
和周围黑框来避免此类问题（

**Comment by Saratoga-Official** [comment]
关闭是因为汇总在ToDo了，不用新开issue

**Comment by Here-is-Daiyu** [comment]
补一个
![image](https://github.com/user-attachments/assets/c49e9ae3-2439-45a1-a119-68f709d33ec4)
好像只出现在这一关
<del/>还有log能不能改成多存几份backup但单文件小一点啊（每次log都是200-300MB打都打不开<del>
