### ISSUE TITLE
关于活动交接过程中的活动自动刷取优化

### ISSUE THREAD

**Issue by Orirock** [MaaAssistantArknights/MaaAssistantArknights#10330]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

太阳甩在身后活动结束后，我忘记将首选刷取关卡设置为火山旅梦关卡，而且我设置了借助战打of-1，这导致maa在运行过程中直接跳过后续的备选关卡，直接刷取剩余理智选定的关卡

### 有什么好的想法？

希望在当期活动结束后，如果关卡选择列表中有当期活动关卡，自动将那个格子禁用，而不是自动改成当前/上次

**Comment by ABA2396** [comment]
当期活动结束后也不是立刻变成 当期/上次 的啊，得你重启 maa 之后才会变

**Comment by Orirock** [comment]
就是希望他能等玩家手动选了关卡之后才生效，而不是重启之后就生效

**Comment by Orirock** [comment]
其实可以针对这个出个选项，让玩家来选是重启后自动变当前/上次还是直接禁用
