### ISSUE TITLE
mumu extras未生效

### ISSUE THREAD

**Issue by Pavel-Ivanovich-Batov** [MaaAssistantArknights/MaaAssistantArknights#10339]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

开始任何任务时都会显示“mumu extras未生效”，随后停止任务

### Version

5.6.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16721147/asst.log)
[gui.log](https://github.com/user-attachments/files/16721149/gui.log)

### 配置信息

[gui.json](https://github.com/user-attachments/files/16721151/gui.json)
WIndows11、Mumu12、1920×1080、DPI280、帧率60
截图增强已开启，GPU加速未开启

### 截图

![ba80be7e01ef502332e97894f0d30a89](https://github.com/user-attachments/assets/b22369ab-1839-4d93-be2d-5be3838dc2e7)

**Comment by status102** [comment]
Mumu截图增强参数填写错误

**Comment by Pavel-Ivanovich-Batov** [comment]
> Mumu截图增强参数填写错误

![9eca1d2a9f5549dfe152c866d0d5166b](https://github.com/user-attachments/assets/b8e0129a-7593-485c-b80b-e0e627bf70bd)
已重新打开maa，确认截图增强已开启

**Comment by ABA2396** [comment]
你路径没填

**Comment by Pavel-Ivanovich-Batov** [comment]
> 你路径没填

填上地址以后这个问题解决了，但是开始任何任务都没反应了，关了截图增强才能正常使用，希望修复这个问题

**Comment by status102** [comment]
> > 你路径没填
> 
> 填上地址以后这个问题解决了，但是开始任何任务都没反应了，关了截图增强才能正常使用，希望修复这个问题

截图测试做了吗？？

**Comment by Saratoga-Official** [comment]
> > 你路径没填
> 
> 填上地址以后这个问题解决了，但是开始任何任务都没反应了，关了截图增强才能正常使用，希望修复这个问题

鉴定为已开启后台保活
