### ISSUE TITLE
希望可以取消生息演算点数刷满后自动完成任务

### ISSUE THREAD

**Issue by wei-dh** [MaaAssistantArknights/MaaAssistantArknights#10332]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

刷生息演算限时活动时，由于之前已经刷满点数，每刷一次都会自动完成任务，需要频繁点击开始连接。

### 有什么好的想法？

取消刷满点数自动完成任务的设定，或者让它可自选。

**Comment by ABA2396** [comment]
限时任务不做生息演算的也有点数吧。还有是什么任务要用这个任务来刷的，制造自己造一轮直接回档就好了吧

**Comment by DCxDESIGN** [comment]
![image](https://github.com/user-attachments/assets/39ba62e9-b1bd-44d9-866c-8062e4b38cbb)

需要刷的任务是这个

虽然 18 天也不算多，但主要还是不想自己动手【

建议还是加上一个“刷满后自动停止”的选项，勾选了才自动停，不勾选就一直运作，毕竟以后还可能会有别的情况也需要在满了之后继续刷

**Comment by xiaoweiXX** [comment]
赞同，现在刷限时活动得一遍一遍点，没法离开电脑挂机刷。只靠日常任务有可能拿不完奖励（比如线索交流开不满3次或者公招不够40次），还是得做一下生稀盐酸的跨天和节点任务比较保险，正好MAA也可以刷。

**Comment by ABA2396** [comment]
现在生息演算在整体重构，单独为这个出一半也太多余了，你自己下个老版本吧，老版本是没自动停的

**Comment by Lancarus** [comment]
活动持续到下个月，9月1号再刷不行么

**Comment by Daydreamer114** [comment]
#10345 
你们owner谁想合就合这个吧

**Comment by xiaoweiXX** [comment]
> 活动持续到下个月，9月1号再刷不行么

9月1号不是就停止了吗？领奖励可以到1号之后
