### ISSUE TITLE
征集贸易站`巫恋`组不使用`龙舌兰`的日志

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#1033]
天天在群里听群友说 maa 新版本不会用龙舌兰了，这显然是 bug 啊。但是日志呢？！我怎么一个没看到_(:з」∠)_

**Comment by ABA2396** [comment]
我这里选龙舌兰就没问题.jpg

**Comment by MistEO** [comment]
好嘛，我自己复现了

> 2022-06-29 10:03:02.327

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9015668/asst.log)

**Comment by chenjie1234567890** [comment]
![image](https://user-images.githubusercontent.com/39559452/176823099-bfa94982-29dc-447a-968e-47de9b5bdf2c.png)
![image](https://user-images.githubusercontent.com/39559452/176823132-b07d2c58-ea4f-48a2-99cf-ded1da427671.png)
如图，有龙舌兰的情况下，却带的是精零的卡夫卡

模拟器：蓝叠国际版5.6.0.1126
出错时间：2022-07-01 9点左右
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9025044/asst.bak.log)
