### ISSUE TITLE
着装缪尔赛斯基建无法识别

### ISSUE THREAD

**Issue by liu284709** [MaaAssistantArknights/MaaAssistantArknights#10349]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

基建中缪尔赛斯更换衣服后无法被MAA识别

### Version

![QQ_1724463904771](https://github.com/user-attachments/assets/ea9aeb15-afed-4ddb-94c6-199264eb10ca)

### 日志文件

主动关闭,程序未崩溃
[gui.log](https://github.com/user-attachments/files/16734845/gui.log)
[asst.log](https://github.com/user-attachments/files/16734846/asst.log)

### 配置信息

无截图增强,雷电模拟
![Uploading QQ_1724464042788.png…]()

### 截图

![QQ_1724463796256](https://github.com/user-attachments/assets/415cf321-02b6-44ca-9cf0-39d0092df36b)

### 还有别的吗？

无

**Comment by Daydreamer114** [comment]
我老婆叫缪尔赛思，不叫缪尔赛斯

**Comment by liu284709** [comment]
缪尔赛斯是输入法自动的名字,还有我老婆缪缪很可爱&nbsp;


淡忘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月24日(星期六) 下午2:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 着装缪尔赛斯基建无法识别 (Issue #10349)














 
我老婆叫缪尔赛思，不叫缪尔赛斯

**Comment by Daydreamer114** [comment]
你改一下你的排班表，理论上就行了

**Comment by liu284709** [comment]
&nbsp; 行吧,
&nbsp; 只能让缪缪住宿舍了,25%的发电(无人机)效率不如我直接进进去发电.
不能让缪缪工作了
&nbsp;


淡忘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月24日(星期六) 下午2:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 着装缪尔赛斯基建无法识别 (Issue #10349)














 
你改一下你的排班表，理论上就行了
