### ISSUE TITLE
MAA for macOS "closedown"任务不能退出明日方舟

### ISSUE THREAD

**Issue by lemon-sundae** [MaaAssistantArknights/MaaAssistantArknights#10347]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

mac端MAA最后一步“关闭游戏”貌似执行了没报错 但是没有退出游戏
游戏为安卓国服，设备为安卓实体机
win版MAA这一步记得是正常的

### Version

v5.5.11452（508）

### 日志文件

仅执行了“开始唤醒”和“关闭游戏”任务作展示，勾选其他任务对于此问题效果相同

[asst.log](https://github.com/user-attachments/files/16732834/asst.log)

### 配置信息

macOS 14.6.1 (23G93)

### 还有别的吗？

貌似翻到以前有issue提过并且修了这个问题，但是又好像不太一样（？） #5920

**Comment by Rbqwow** [comment]
坏了 mac gui那边应该是没加客户端类型回调
和之前那个没关系 是最近新重构的 #9658
cc @hguandl

**Comment by wangl-cc** [comment]
> maa-cli 在 macOS 下也受到影响，前几天升级最新 core 之后好几天不能关闭游戏了。模拟器内的游戏长期不关闭容易莫名其妙卡死，所以能定期关闭游戏还是很重要的。

maa-cli 最新版已经适配了 Core 的改动。但是你至少需要在任意一个 StartUp，Fight 或者 CloseDown 里面设置参数 `client_type` 参数，然后 maa-cli 会把这个参数赋给所有需要 client_type 的任务。

**Comment by rainux** [comment]
> > maa-cli 在 macOS 下也受到影响，前几天升级最新 core 之后好几天不能关闭游戏了。模拟器内的游戏长期不关闭容易莫名其妙卡死，所以能定期关闭游戏还是很重要的。
> 
> maa-cli 最新版已经适配了 Core 的改动。但是你至少需要在任意一个 StartUp，Fight 或者 CloseDown 里面设置参数 `client_type` 参数，然后 maa-cli 会把这个参数赋给所有需要 client_type 的任务。
> 
> EDIT: 0.4.12 我改成了，如果不设置，默认 client_type 为 Official 来避免这个问题。但是如果是官服以外客户端，那么依旧需要至少在一个任务里面设置了 client_type。

感谢回复，确认 maa-cli 0.4.12 工作正常。我平时习惯是经常 git 更新 core 的代码自己编译没有频繁升级 maa-cli 所以遇到这个问题。

**Comment by wangl-cc** [comment]
MacGUI 应该还没有修复这个问题。

**Comment by Argonautes0607** [comment]
昨天更新的内测版依旧没有修复这个问题
