### ISSUE TITLE
基建训练室小审判官类似技能相关

### ISSUE THREAD

**Issue by desktop4025** [MaaAssistantArknights/MaaAssistantArknights#1035]
emmm怎么说，可以加一个特判，因为小审判官出了训练室效果就没了，所以刷基建宿舍的时候可以加个特判。可能还有其它干员有这种特性，所以提一嘴

**Comment by ABA2396** [comment]
之前提过一次，换基建的时候可以先清空宿舍（压榨干员的时候并不需要满心情，当然也可以先忽略这一步），然后开始正常换班，到宿舍的时候选择`未进驻`标签选人，这样可以避免如艾丽妮这样的技能问题（虽然现在还没有其他人），但这种方式的话加工站就不会换人了，会导致加工过材料心情未满的人不进宿舍，除非手动换下来让干员变成未进驻的状态

**Comment by Nova-Noir** [comment]
赞同。
一般加工站的干员我认为大多数玩家都是用完就丢宿舍的（一般加工材料都是直接压榨完全到溃散的吧，笑），就算忘了下次造东西的时候应该也会手动丢去宿舍，虽然有代价但是个人认为不大。
相比起来，训练室训着训着就被丢进宿舍，尤其是小审判官减半效果没了的话，其时间成本是远远大于加工站心情未满干员不进驻宿舍的时间成本的。

当然最好的解决方法就是添加宿舍进驻的干员的过滤器，不过这样的话工作量太大了；或许可以通过判断左上角是否有进驻训练室的 icon 来解决？
![image](https://user-images.githubusercontent.com/68760718/179339852-d150faeb-dbb8-46fb-8d64-ec666d94fad8.png)

**Comment by ABA2396** [comment]
Duplicate of #763

**Comment by MistEO** [comment]
新增了按 `未进驻` 过滤进驻宿舍，fixed
