### ISSUE TITLE
基建换班办公室经常出错

### ISSUE THREAD

**Issue by insine-inverse** [MaaAssistantArknights/MaaAssistantArknights#10350]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

基建换班时候常常卡在找不到絮雨，我也不知道什么原因，偶尔也有别的人
连斥罪也是

### Version

Resource Version: 太阳甩在身后
UI Version: v5.6.0-beta.1
Core Version: v5.6.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16734951/asst.log)
[gui.log](https://github.com/user-attachments/files/16734952/gui.log)

### 配置信息

[gui.json](https://github.com/user-attachments/files/16734955/gui.json)

### 截图
<img width="134" alt="1724799573731" src="https://github.com/user-attachments/assets/aa3b7997-7192-4eea-978e-d49137a18626">

<img width="168" alt="1724466920953" src="https://github.com/user-attachments/assets/748bb1f7-858b-4979-b4f0-feef7b286038">

### 还有别的吗？

[153三班.json](https://github.com/user-attachments/files/16734956/153.json)
附上换班文件

**Comment by Constrat** [comment]
Is your screen turned off when this happens?
I've been having this issue for quite a long time, without any fixes except turning on the screen when MAA needs to run. It doesn't bring issues in stage farming or other tasks, but infrastructure shift is very picky and needs to be precise.

**Comment by insine-inverse** [comment]
并没有关闭显示器的习惯……不过也许会用远程操作软件TODESK来用手机操作MAA
