### ISSUE TITLE
MAA开启后卡死

### ISSUE THREAD

**Issue by bronzitro** [MaaAssistantArknights/MaaAssistantArknights#10364]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

MAA开启后启动模拟器，等待时间过后卡死，没有响应。偶尔会出现一次，不是一直能重现...

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[asst.log](https://github.com/user-attachments/files/16738843/asst.log)
[gui.log](https://github.com/user-attachments/files/16738844/gui.log)

### 配置信息

win10，蓝叠5.13.200.1026

**Comment by octopusYan** [comment]
maa卡死无响应？

**Comment by bronzitro** [comment]
> maa卡死无响应？

是的，出现频率很低，大概一个月有一次

**Comment by bronzitro** [comment]
今天又出现一次
[gui.log](https://github.com/user-attachments/files/16826556/gui.log)
[asst.log](https://github.com/user-attachments/files/16826557/asst.log)
![捕获](https://github.com/user-attachments/assets/418647be-8ede-44cd-98b1-39a494386605)

**Comment by bronzitro** [comment]
看日志每次都卡在[2024-09-01 02:09:14.677][TRC][Px23424][Tx31b3c] asst::CopilotConfig :: asst::AbstractConfig::load | enter
我的copilot文件夹里只有OF-1_credit_fight.json

**Comment by bronzitro** [comment]
[stack.txt](https://github.com/user-attachments/files/16903049/stack.txt)
dump call stack

**Comment by bronzitro** [comment]
最近又卡了几次，每次都是卡在日志 asst::CopilotConfig :: asst::AbstractConfig::load | enter，call stack也每次都是在等待打开文件。感觉是前一次写完还没关掉就再打开导致的，希望可以看一下，或者加个不写日志的开关试试
