### ISSUE TITLE
无法记住“最小化时隐藏至拖盘”的设置

### ISSUE THREAD

**Issue by KuiPer-LTW** [MaaAssistantArknights/MaaAssistantArknights#1036]
每次打开都要重新设置
![QQ截图20220630003556](https://user-images.githubusercontent.com/103661658/176490447-19104c79-c621-47b2-bbb8-6e18d816d0b2.jpg)

**Comment by MistEO** [comment]
v4.0.2 修了，版本再等一小会就出来了
