### ISSUE TITLE
[日服]生息演算开局不久就任务出错

### ISSUE THREAD

**Issue by Crimson-Veluriyam** [MaaAssistantArknights/MaaAssistantArknights#10360]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

生息演算开局不久就任务出错
1.已清空编队
2.删除存档后重新开局
3.高级设置：未勾通过制造刷点数

### Version

UI Version: v5.6.0-beta.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/16736773/gui.log)
[asst.log](https://github.com/user-attachments/files/16736774/asst.log)
2024-8-24晚上8：41、9:15均有报错

### 配置信息

[gui.json](https://github.com/user-attachments/files/16736780/gui.json)
WIN10，雷电模拟器v9.0.69，1600*900，dpi240

### 截图

![(B0D)A9K0ES)%~AV$FFXP3Q](https://github.com/user-attachments/assets/6a7ead63-ba63-48c9-a659-c9355fa028fc)

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/5762a30a-08f6-400b-aef9-01db005fb076)
![image](https://github.com/user-attachments/assets/0daa5018-a248-4763-96eb-5c39f5b0f56a)

**Comment by Crimson-Veluriyam** [comment]
![image](https://github.com/user-attachments/assets/ca77c2f9-0519-40fa-9733-69a4f0856c75)
主要是不时会卡在这个画面，此时MAA Link Start!后则会卡在下图画面
![image](https://github.com/user-attachments/assets/1863d60a-e9b8-4ce9-9f9d-53cdda48b6f5)
得自己手动点掉这个对话，再Link Start! 即可继续刷
