### ISSUE TITLE
娜仁图亚一技能

### ISSUE THREAD

**Issue by ydz2021** [MaaAssistantArknights/MaaAssistantArknights#10382]
### 在提问之前...

- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

娜仁图亚一技能CD转好直接切换，类似技能效果的山二技能并不会

### 有什么好的想法？

在单线图时多打一格的输出并不如常驻开启一技能，希望能参照山二技能修改一下orz

**Comment by Daydreamer114** [comment]
哪关？

**Comment by ydz2021** [comment]
肉鸽 版本5.6.0B1
