### ISSUE TITLE
其它功能正常使用，单独使用生息演算功能报错无法运行

### ISSUE THREAD

**Issue by AbyssAzrael** [MaaAssistantArknights/MaaAssistantArknights#10389]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

运行生息演算时无动作，15s后即报错退出，几天内反复测试均为同一结果
（已提前切换到游戏内生息演算主菜单并且未开启游戏）
唤醒，公招，清理智，领取任务等功能均可以正常使用
debug 的 log看不懂啦（

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452
资源已更新到Maaresource的最新版本

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16769376/asst.log)
[gui.log](https://github.com/user-attachments/files/16769377/gui.log)
[gui.json](https://github.com/user-attachments/files/16769378/gui.json)

### 配置信息

mumu12 720p

gpu加速推理开启和关闭均为同样的报错，型号为4070s

### 截图或录屏

![image](https://github.com/user-attachments/assets/990fc5ad-991c-45a8-8bea-abcff56939df)

**Comment by Daydreamer114** [comment]
是否按照常规设置文字描述进行配置？

**Comment by AbyssAzrael** [comment]
> 是否按照常规设置文字描述进行配置？

是的

**Comment by Daydreamer114** [comment]
> （已提前切换到游戏内生息演算主菜单并且未开启游戏）

再仔细读去，看看你读的和你选的是不是同一个模式
