### ISSUE TITLE
建议：作业模式改成读取内置的资源文件夹里的文件

### ISSUE THREAD

**Issue by caozhongpeng001** [MaaAssistantArknights/MaaAssistantArknights#1038]
流程：
1、用户将作业文件放入maa目录下的固定的某个文件夹里
2、用户选择某关卡，然后选择使用默认配置还是某个作业
3、LinkStart!

**Comment by MistEO** [comment]
那么多作业哪来。。

所以现在不是有专门的作业网站并且可以粘贴神秘代码了吗（
