### ISSUE TITLE
萨米肉鸽某些固定的关卡识别错误

### ISSUE THREAD

**Issue by offical-HYC** [MaaAssistantArknights/MaaAssistantArknights#10383]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

使用MAA的功能”自动肉鸽“代理萨米肉鸽时遇见”事不过四“”低空机动“”死囚之夜“等关卡（有且仅有这几个关卡会出现这个情况）时会显示”关卡识别错误“，进入关卡后不执行任何操作，但完成作战后仍能正常运行。安装后首次运行不会有该问题的出现。重启MAA有时可以解决该问题，但也有无法解决的情况。

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16759810/asst.log)
[gui.json](https://github.com/user-attachments/files/16759973/gui.json)
[gui.log](https://github.com/user-attachments/files/16759938/gui.log)

### 配置信息

操作系统：Windows 10
模拟器：MUMU模拟器12
分辨率：1600x900 (DPI 240)
帧率：60
MuMu截图增强正常开启
GPU加速未开启

### 还有别的吗？

最开始的时候，如果打开MAA运行后停止，不关闭MAA再次运行就会出现该问题
但现在即使重启MAA首次运行也会出现问题
辛苦各位大大了

**Comment by offical-HYC** [comment]
[gui.json](https://github.com/user-attachments/files/16759973/gui.json)
抱歉刚才看了一下这个文件好像没有成功发送

**Comment by Constrat** [comment]
@ABA2396 
> [!Caution]
link

Tested instantly :)

**Comment by offical-HYC** [comment]
Thanks for your suggestion,I'll try :)

**Comment by Daydreamer114** [comment]
你的mumu截图增强未生效，gui里告诉你了
![image](https://github.com/user-attachments/assets/4214ef95-a94d-4db8-9afb-fa092722559c)
这种截图间隔，截不到是正常的，你可以考虑升级电脑配置或者正确设置截图增强

**Comment by offical-HYC** [comment]
Well.It seems to work, thank you again for your help.
o(*￣▽￣*)ブ
