### ISSUE TITLE
肉鸽模式：险路恶故“恐怖传说”干员部署错误

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#1039]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9019298/asst.log)
干员“煌”在boss走后部署在仅有boss通过的道路，如下图
![OODWSW 9HE$XR@ELOXMF{6I](https://user-images.githubusercontent.com/74061867/176666132-4c57d5bd-0eaa-4d76-8725-a2832512b205.png)

**Comment by ntgmc** [comment]
暂停是我暂停的

**Comment by ABA2396** [comment]
（再拖会儿肉鸽就结束了）

**Comment by ntgmc** [comment]
太baby辣
