### ISSUE TITLE
生息演算制造荧光棒刷点数过程遇到2种任务出错情况

### ISSUE THREAD

**Issue by BlackCA1495** [MaaAssistantArknights/MaaAssistantArknights#10393]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

第一个问题，在组装台列表，往下滑动到“荧光棒”时，如果“荧光棒”贴近“技术脉络”图标，会点击进技术脉络里，导致任务出错
第二个问题，量定之日，58点的转化技术点数会让该界面维持较久，程序已经到下一步，且没有可操作的读取存档行为，导致任务出错

### Version

Resource Version: 太阳甩在身后
UI Version: v5.6.0-beta.1
Core Version: v5.6.0-beta.1

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16780553/asst.log)
[gui.log](https://github.com/user-attachments/files/16780555/gui.log)
[gui.json](https://github.com/user-attachments/files/16780564/gui.json)
第一个问题时间点8月28日16点24分
第二个问题时间点8月28日16点29分

### 配置信息

win10家庭中文版，版本号22H2
MuMu12模拟器，并开启了截图增强，模拟器分辨率1600x900，dpi设240，帧率60
已开启gpu加速，NVIDIA GeForce GTX 1070

### 截图或录屏

https://github.com/user-attachments/assets/bc966c0b-4d27-4f46-84ab-e8f7ec53edbf

https://github.com/user-attachments/assets/7d2ea709-d72f-4641-9cb1-8359346182c9

**Comment by Daydreamer114** [comment]
这部分任务已经被重构，尚未发版
