### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by You-afk** [MaaAssistantArknights/MaaAssistantArknights#10408]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

试过所说的解决方法后都不可用，显示“连接失败 请检查连接设置或尝试重启模拟器与ADB或重启电脑”

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/16823824/gui.log)
[asst.log](https://github.com/user-attachments/files/16823825/asst.log)
[gui.json](https://github.com/user-attachments/files/16823827/gui.json)

### 配置信息

Win10 版本：22H2 
模拟器品牌：MUMU12 
分辨率：1600*900（DPI：240）
帧率：60
没开启截图增强

### 截图或录屏

![Desktop Screenshot 2024 08 31 - 15 47 54 93](https://github.com/user-attachments/assets/4afb36c0-f7ff-42f1-8e14-868030009891)

**Comment by Rbqwow** [comment]
原因都是 `cannot connect to 127.0.0.1:16384: 由于目标计算机积极拒绝，无法连接。 (10061)`
确认一下adb地址对不对 自己手动连一下试试 再看看有没有什么会影响网络环境的东西

**Comment by wzj042** [comment]
看看防火墙，看了几个issue后我发现可能和我电脑上adb版本比较多有关系。打开防火墙一看有多个重复的规则，而且其中策略似乎也各不相同。干脆删除到只保留 maa 和 模拟器 的 adb两条规则，允许访问。然后重启之后就解决了此前一直出现的模拟器断开的问题。

**Comment by You-afk** [comment]
没事了 )： 重装了mumu就好了
