### ISSUE TITLE
能添加自动更新明日方舟安装包的功能吗

### ISSUE THREAD

**Issue by 2714AC** [MaaAssistantArknights/MaaAssistantArknights#10404]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

每次到大版本更新时 需要手动下载新安装包并手动安装
希望能在开始唤醒前加一个自动更新的过程
明日方舟可更新时 手动点击明日方舟会出现一个大概非安卓界面的窗口(MuMu模拟器)
![MuMu模拟器12 2024_8_30 15_58_38](https://github.com/user-attachments/assets/2287a048-2332-4ef0-8139-1d8a346a5577)
如果未更新 运行maa则会出现(maa使用了启动maa自动启动模拟器+启动maa自动执行任务)
![MAA (Default) - v5 5 11452 - 太阳甩在身后 - MuMu 模拟器 12 (127 0 0 1_16384) - 官服 2024_8_30 15_59_35](https://github.com/user-attachments/assets/bd9cfcac-86f3-4ee8-9a8a-c9f3a8c67e4f)
此时执行自动唤醒会进入明日方舟且一秒后自动退回主界面(类似闪退吧)
应该是mumu检测到adb启动旧版本的游戏 自动退了

### 有什么好的想法？

以前maa通过adb指令进入未更新的明日方舟时mumu貌似是不会闪退回主界面的
会正常进入并跳转浏览器下载安装包 不会自动安装就是了(此时下拉状态栏能看到下载进度 点击安装即可)
现在会出现闪退
可以在主界面adb截屏识别方舟图标 用模拟点击打开方舟
再用mumu提供的方式更新
![MuMu模拟器12 2024_8_30 15_58_38](https://github.com/user-attachments/assets/320565c8-f8a5-4d90-aa1e-298e4a9bfb3e)
但这按钮玩意不知道adb点不点的到 好像是属于电脑窗口 在模拟器上的...

**Comment by ABA2396** [comment]
这玩意点不到，倒不如问问能不能让mumu自动更新）

**Comment by HoshinoAyako** [comment]
为什么要让MAA去做MUMU应该做的事（
