### ISSUE TITLE
关于刷生息盐酸的优化方案

### ISSUE THREAD

**Issue by testpaper007** [MaaAssistantArknights/MaaAssistantArknights#10402]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

制造荧光棒的操作过慢

### 有什么好的想法？

通过刷荧光棒的方式进行攒积分，但是实际过程中增加荧光棒的操作是点按的，可以直接改为长按，识别数量99，或者识别无足够材料后进行制作。可以把制造速度提升50%

**Comment by Daydreamer114** [comment]
cc @Alan-Charred

**Comment by ABA2396** [comment]
https://github.com/user-attachments/assets/e65a887f-a9c1-4ad0-a6f5-987f4cb5e579

**Comment by Alan-Charred** [comment]
待我做做实验试试。我改动后的确是刻意把这里的速度降低了。每次点击之间会有 500ms 的 delay。恢复到原来的速度的话，就是去掉这个 delay。再进一步就是检测一次位置后记住位置盲点99次。
