### ISSUE TITLE
萨卡兹肉鸽中多次出现完成作战后放弃探索的问题

### ISSUE THREAD

**Issue by Mou-Froski** [MaaAssistantArknights/MaaAssistantArknights#10401]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

在完成部分关卡后会卡在关卡掉落的招募券界面，随后放弃探索

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志和配置文件

[新建文件夹.zip](https://github.com/user-attachments/files/16801723/default.zip)
[2024-08-14 17:43:33.960] <1><> 已放弃本次探索
[2024-08-21 01:58:18.601] <1><> 已放弃本次探索
[2024-08-29 23:19:50.450] <1><> 已放弃本次探索
（还有很多

### 配置信息

版本	Windows 10 家庭中文版
版本号	22H2
操作系统内部版本	19045.4780
mumu12，分辨率1440*810，DPI202，60帧
未开启截图增强，未开启GPU

### 截图或录屏

![2024-08-29_23-19-50-419_raw](https://github.com/user-attachments/assets/6757ec0f-ebba-45a5-a8e1-8b3fd46f6d97)

**Comment by Mou-Froski** [comment]
（帧率也有可能是动态调整20帧，不知道是否有影响

**Comment by Mou-Froski** [comment]
今天在无罪净土、巫咒同盟、残损学院、飞越大水坑同样出现了该问题，debug截图均为发券界面。

**Comment by HoshinoAyako** [comment]
![QQ_1725025411859](https://github.com/user-attachments/assets/53f9cdd2-5f09-4355-8717-6c2078c98269)把这个去掉勾。挂一会试试？

**Comment by HoshinoAyako** [comment]
![QQ_1725026415106](https://github.com/user-attachments/assets/07b4407b-a656-4064-8820-71b1a0731614)
MAA推荐的分辨率是16:9，因为识别模板会随着分辨率变化缩放。建议重新调整分辨率。

**Comment by HoshinoAyako** [comment]
![Image_1725032817711.png](https://github.com/user-attachments/assets/7600af39-efed-4eb6-b12a-c877679588b1)

破案了。是模板调用错了。
