### ISSUE TITLE
大厅进入肉鸽模式失败

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#1040]
如题，在大厅界面无法直接进入肉鸽模式界面，需要手动进入后再开启肉鸽功能

该bug复现方法（可能）：在未打完今日轮换危机合约时在大厅直接进行“无限刷肉鸽”
具体卡住的页面：
![image](https://user-images.githubusercontent.com/74061867/176670137-0e8cbd62-7263-4c44-9142-28d545e4138d.png)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9019483/asst.zip)

**Comment by ABA2396** [comment]
这个界面没有肉鸽的入口（）现在是直接在这里找入口的，之后可能会做个从下面的导航

**Comment by ntgmc** [comment]
![image](https://user-images.githubusercontent.com/74061867/176671179-32394660-9730-4d11-afac-a04f80f585b9.png)
不能在这里两步进入吗

**Comment by ABA2396** [comment]
> ![image](https://user-images.githubusercontent.com/74061867/176671179-32394660-9730-4d11-afac-a04f80f585b9.png) 不能在这里两步进入吗

没做这种方式的，因为以前主界面就能进，但是现在加了个集成战略，入口被挤掉了

**Comment by zzyyyl** [comment]
bf659e1351958d8357de928fbaebbcc643b3d046 fixed.
