### ISSUE TITLE
生息演算中使用荧光棒刷点数时滑动后点击判定错误

### ISSUE THREAD

**Issue by dhy1921** [MaaAssistantArknights/MaaAssistantArknights#10410]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

在4本生息演算制造刷点数中，由于制造荧光棒点击区与下方导航栏“科技树”按钮点击区过于接近，而将点击判定到科技树上，进而导致流程错误并退出。该问题在我的设备上出现概率极高，但仍有小概率能点击到正常位置。

### Version

Resource Version: 太阳甩在身后
UI Version: v5.6.0-beta.1
Core Version: v5.6.0-beta.1

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16824477/asst.log)
[gui.log](https://github.com/user-attachments/files/16824478/gui.log)
[gui.json](https://github.com/user-attachments/files/16824479/gui.json)

### 配置信息

操作系统：Windows 11 家庭中文版 23H2
模拟器品牌：雷电模拟器 9.0.76.3
模拟器分辨率：1920*1080 dpi280 帧率120fps
GPU加速：开启，NVIDIA GefForce RTX4060 Laptop，关闭GPU加速该问题仍然存在

### 截图或录屏

https://github.com/user-attachments/assets/39d73aa7-5d7d-4f86-8cf7-7847b05d7ad5

### 还有别的吗？

自己尝试了雷电模拟器的多个版本，发现在某一版本提及雷电模拟器存在滑动轨迹问题，该问题在旧版雷电模拟器中出现的尤其明显，在最新版雷电模拟器中出现概率略有下降，但仍然存在。

**Comment by ABA2396** [comment]
有点过于抽象了
@Alan-Charred 重构的时候缩小点识别的范围吧

**Comment by Alan-Charred** [comment]
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/e0c180a9-3766-4e7a-a71b-14242b487fce">
这是目前的 roi
我给上调到565试试看
<img width="1057" alt="image" src="https://github.com/user-attachments/assets/7e360790-62f4-4b48-ace7-957922f5209c">

**Comment by Alan-Charred** [comment]
> <img alt="image" width="1125" src="https://private-user-images.githubusercontent.com/44151844/364452465-e0c180a9-3766-4e7a-a71b-14242b487fce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjU2NDksIm5iZiI6MTcyNTQ2NTM0OSwicGF0aCI6Ii80NDE1MTg0NC8zNjQ0NTI0NjUtZTBjMTgwYTktMzc2Ni00ZTdhLWE3MWItMTQyNDJiNDg3ZmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDE1NTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNTdmY2EwYmZkNGQ2ZGRiMzQxYjQ1YTM3NTExM2Y3NjA0NzU4MTI2Zjc2OGVkNjMyMjU4ZTRhYTM0MDRlYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vxHeemhVUAwWWKl6R1-nRFXa2DdSfl3KzAaEN73TFZc"> 这是目前的 roi 我给上调到565试试看 <img alt="image" width="1057" src="https://private-user-images.githubusercontent.com/44151844/364452853-7e360790-62f4-4b48-ace7-957922f5209c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjU2NDksIm5iZiI6MTcyNTQ2NTM0OSwicGF0aCI6Ii80NDE1MTg0NC8zNjQ0NTI4NTMtN2UzNjA3OTAtNjJmNC00YjQ4LWFjZTctOTU3OTIyZjUyMDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDE1NTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YmFiN2FhNzMzNjU1MmM3ZDhlZmQ3ZWQzOTY0YzM4OGUzNjFiNTdiMmE1ZWY0ODhhMDhiNzU3MTg0OTM3ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nBuFH2k_FCYEUiwAdt6QVo8BhY79bM-WUIKOAbQaa6Q">

不对不对，那个条的实际触控范围比肉眼可视部分要大得多，再往上抬。

**Comment by Alan-Charred** [comment]
<img width="661" alt="image" src="https://github.com/user-attachments/assets/3f655b27-2673-4a0b-a94e-83d85b8411f6">
修改为这个
