### ISSUE TITLE
非独显直连的笔记本截图问题

### ISSUE THREAD

**Issue by BalanceSteelyard** [MaaAssistantArknights/MaaAssistantArknights#10419]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

复现：使用带独立显卡并且没有独显直连的笔记本，模拟器图形使用独显。将模拟器窗口放到笔记本屏幕，自动息屏且未休眠，截图得到的结果是黑屏或者卡住。将窗口拖到连接独显的外接显示器就不会有问题，即使自动息屏

### Version

太阳甩在身后
5.6.0-beta.1
5.6.0-beta.1

### 日志和配置文件

[gui.json](https://github.com/user-attachments/files/16829103/gui.json)
[gui.bak.log](https://github.com/user-attachments/files/16829106/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/16829113/gui.log)
[asst_2.zip](https://github.com/user-attachments/files/16829131/asst_2.zip)

### 配置信息

gpu推理加速开启，1650ti
win10 21h2，蓝叠4国际（内核版本更新为5.10.250.1004），分辨率1280x720，240dpi，帧率60

### 截图或录屏

![屏幕截图 2024-09-01 214847](https://github.com/user-attachments/assets/851ada7e-71dd-4542-83d1-257eebf16b6f)
模拟器此时仍在运行但是截图卡住，并且实际画面不是这个失败画面，已经到了结算

**Comment by Constrat** [comment]
I probably said this before.
I think I have been running on the same issue where when the screen turns off automatically, especially the infrastructure OCR will stop working. The only solution I ever found was to automate via task scheduler and AutoHotkey a simple key press right before MAA had to run (and set the display off time at about 15 minutes, which is the standard time for MAA to clear all tasks).

**Comment by BalanceSteelyard** [comment]
> I probably said this before. I think I have been running on the same issue where when the screen turns off automatically, especially the infrastructure OCR will stop working. The only solution I ever found was to automate via task scheduler and AutoHotkey a simple key press right before MAA had to run (and set the display off time at about 15 minutes, which is the standard time for MAA to clear all tasks).

奇怪的是，电源设置已经取消了休眠和睡眠，息屏后截图却出现了问题。我无法确定为什么外接显示器后板载显卡就停止工作了，但是独立显卡正常工作，因为历史记录告诉我他在息屏后占用0。移除外接显示器板载显卡就不会在息屏后停止工作

**Comment by BalanceSteelyard** [comment]
> 这个问题我感觉你更应该找模拟器，为什么在息屏情况下adb拿到的图是黑屏或者卡住

试了别的模拟器一样的，要不就不用独显

**Comment by ABA2396** [comment]
那你找maa有啥用呢，maa就是靠adb传出来的图来识别的，模拟器都不渲染了，我咋知道显示的什么东西

**Comment by Rbqwow** [comment]
在一台机子上用两种显卡接两块屏幕是下头行为
如果不在乎离电续航 可以去bios里找找能不能直接屏蔽核显

**Comment by BalanceSteelyard** [comment]
> 在一台机子上用两种显卡接两块屏幕的行为会让各种软件觉得下头 如果不在乎离电续航 可以去bios里找找能不能直接屏蔽核显

在乎肯定是不在乎的，都拿来挂游戏了。下头的是你关了板载显卡电脑打开就黑屏了，外接的也不会亮。开机关了集显cpu占用就100%，因为笔记本的画面就是硬算的了（

**Comment by BalanceSteelyard** [comment]
> 那你找maa有啥用呢，maa就是靠adb传出来的图来识别的，模拟器都不渲染了，我咋知道显示的什么东西

是蓝叠的锅，新版本显卡穿透出问题了，换了蓝叠4和远古版本蓝叠3咋折腾都是正常的（mumu不行，直接崩了）。那没有别的问题了

**Comment by Rbqwow** [comment]
![image](https://github.com/user-attachments/assets/e135f062-6dfe-40e5-bfde-1cbb0236a52c)
↑屏蔽核显的暗影精灵试图启用Nvidia热切换时的提示
已知暗影精灵 拯救者 ROG都可以通过bios关闭核显 让独显完全接管所有显示
但确实不是所有笔记本都支持冷切换

**Comment by BalanceSteelyard** [comment]
> ![image](https://private-user-images.githubusercontent.com/55343783/363845386-e135f062-6dfe-40e5-bfde-1cbb0236a52c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzk4NjksIm5iZiI6MTcyNTMzOTU2OSwicGF0aCI6Ii81NTM0Mzc4My8zNjM4NDUzODYtZTEzNWYwNjItNmRmZS00MGU1LWJmZGUtMWNiYjAyMzZhNTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA0NTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YWE3Y2FiMGNiYjZhODg2ODRhN2E1ZjAwY2Y1YTkxZjFhYTliYWVmNDViMTdiMzdiNTg0MWRiYWY2ZGRhOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WmMFE6obMjbWYIITZd4_9m5Qa22HvOEHr1Jk4Bd_B-E)↑屏蔽核显的暗影精灵试图启用Nvidia热切换时的提示 已知暗影精灵 拯救者 ROG都可以通过bios关闭核显 让独显完全接管所有显示 但确实不是所有笔记本都支持冷切换

老笔记本了，不能切换。关了集显后笔记本显示器就是cpu硬算的了。
