### ISSUE TITLE
未完成见习任务时无法领取日常奖励

### ISSUE THREAD

**Issue by QDH734** [MaaAssistantArknights/MaaAssistantArknights#10413]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

生息演算限时任务开启后，未完成见习任务的账号出现了日常任务奖励没有领取，但会退回主页并且显示完成任务。已经完成见习任务的账号就能正常领取日常任务奖励
虽然发现的有点晚了，这活动今天凌晨四点就结束了，但不知道具体是什么原因，所以来反馈一下

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16825513/asst.log)
[gui.log](https://github.com/user-attachments/files/16825521/gui.log)
[gui.json](https://github.com/user-attachments/files/16825523/gui.json)
2024-09-01 01:22

### 配置信息

版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎3/‎22
操作系统版本	22635.4082
体验	Windows Feature Experience Pack 1000.22700.1038.0

雷电模拟器9.0.68（9）
1920x1080（dpi280） 60帧

GPU 加速推理未开启

**Comment by SherkeyXD** [comment]
因为见习任务会把每日任务顶到后面去，且没对见习任务做适配
不过说真的会有新手用maa吗（

**Comment by QDH734** [comment]
> 因为见习任务会把每日任务顶到后面去，且没对见习任务做适配 不过说真的会有新手用maa吗（

很早之前开的小号，也就开限定池的时候抽卡，平时就每天挂着刷日常攒玉

**Comment by status102** [comment]
ee9c1f38ba0261791418a65be5c6f8e839c38aa1 fixed
