### ISSUE TITLE
萨米肉肉鸽编队异常（只编入了等级/稀有度最低的角色）

### ISSUE THREAD

**Issue by testpaper007** [MaaAssistantArknights/MaaAssistantArknights#10412]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

在拥有超过编队数量的角色时，会出现只选择了低等级/低稀有度的角色，导致无法获胜。
按照正常流程来讲，应该是在原有的编队基础上加人，不会出现丢ew的情况。
在拥有超过编队数量的角色后，会在编队界面清除编队，但是不是从最左边选角色，而是从第二列开始选择了

注：选择的编队是我退出战斗后重新编了一下，顺序可能有问题，但是确实未将ew编入队伍内

![MuMu12-20240831-215208](https://github.com/user-attachments/assets/31284dae-7d7d-4a94-811d-4077005c8caf)
![MuMu12-20240831-215506](https://github.com/user-attachments/assets/5362eb0b-36b0-4b54-b1cc-a9b1fc8fa342)

### Version

Resource Version: 太阳甩在身后
UI Version: v5.6.0-beta.1
Core Version: v5.6.0-beta.1

### 日志和配置文件

[Uploading debug.zip…]()
[gui.json](https://github.com/user-attachments/files/16825013/gui.json)

### 配置信息

Windows 10 Home 22H2 19045.4651
MUMU12 开启截图增强    1920*1080  DPI280  帧率60
开启GPU加速 显卡为笔记本的1660ti

**Comment by testpaper007** [comment]
![Uploading MuMu12-20240831-215208.png…]()
![Uploading MuMu12-20240831-215506.png…]()

**Comment by testpaper007** [comment]
![Uploading MuMu12-20240831-215208.png…]()
![Uploading MuMu12-20240831-215506.png…]()

**Comment by testpaper007** [comment]
[Uploading Screenshots.zip…]()
截图文件

**Comment by testpaper007** [comment]
大概是2024.8.31  22：16之前的那场战斗，又发生了一次

**Comment by ABA2396** [comment]
d5ed0db686da6646881cf3a7e358efee4bb4d497 fixed

**Comment by ABA2396** [comment]
你这传了这么多文件，就一个 gui.json 传好了发上来了，文件都没传完这么着急就点提交评论干嘛

**Comment by testpaper007** [comment]
qwq
“你有一些文件没有上传成功，请重新上传。”ta提示我这玩意，我就多传了几次

**Comment by testpaper007** [comment]
这个视频应该比较清楚，在清空编队后，重新编队时，会在选择角色的时候向左划一行。
https://github.com/user-attachments/assets/ef420d82-30e3-4fa3-90fd-2caff7776b1f
下面是对应的日志
[debug23.37.zip](https://github.com/user-attachments/files/16825201/debug23.37.zip)
[gui.json](https://github.com/user-attachments/files/16825203/gui.json)
