### ISSUE TITLE
信用购物无任何操作直接结束

### ISSUE THREAD

**Issue by U98de** [MaaAssistantArknights/MaaAssistantArknights#1042]
如题，信用购物在领取每日信用后无任何操作，直接完成任务

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9019528/asst.log)
蓝叠国际版64位
一个月前用复制粘贴文件夹的方式双开maa，双开的另一份没有出现此问题

**Comment by MistEO** [comment]
现在信用购物商店的干员还没买完就会出这个问题，算是 corner case, 有空再修（

**Comment by U98de** [comment]
现在干员买完了，还是有问题（
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9078470/asst.log)
