### ISSUE TITLE
界面主题“滋味”识别异常

### ISSUE THREAD

**Issue by BlackBoxSpace** [MaaAssistantArknights/MaaAssistantArknights#10433]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

使用界面主题“滋味”后，MAA“一键长草”的各项任务间的切换无法正常执行（压根跑不动😥）

### Version

Resource Version: 泰拉饭
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16842183/asst.log)
[gui.log](https://github.com/user-attachments/files/16842184/gui.log)
[gui.json](https://github.com/user-attachments/files/16842186/gui.json)

### 配置信息

Windows 11
MuMu 1600*900（DPI 240） 60
关闭
关闭

**Comment by zhongfly** [comment]
已经解决了，等下一个公测或正式版发布，或者去下内测版
