### ISSUE TITLE
完成任务后的 `关闭模拟器` 功能无法正常使用

### ISSUE THREAD

**Issue by MouseWhite** [MaaAssistantArknights/MaaAssistantArknights#1043]
![image](https://user-images.githubusercontent.com/17306018/176704229-0356c128-f3ae-496d-8c79-342ad026baf0.png)
选择完成后关闭模拟器 完成任务后模拟器会变成如上界面，使用管理员模式启动MAA也是一样

**Comment by ABA2396** [comment]
问题来到了夜神）

**Comment by kxdxzr** [comment]
同款问题

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/e73f0c62d6a7bd5b2d9b7282aab2b16beff8201b/src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs#L577

如果我没理解错的话, 现在 MAA 关闭模拟器是通过杀死占用 adb 端口的进程来达成的. 
夜神模拟器打开之后会出现三个相关的进程, (可能还有作为服务的 `nox_adb.exe`)
```
Nox.exe
NoxVMSVC.exe
NoxVMHandle.exe
```

而 `netstat` 结果可能为
```
  TCP    127.0.0.1:42657        127.0.0.1:62001        ESTABLISHED     nox_adb.exe
  TCP    127.0.0.1:62001        0.0.0.0:0              LISTENING       NoxVMHandle.exe
  TCP    127.0.0.1:62001        127.0.0.1:42657        ESTABLISHED     NoxVMHandle.exe
```
这样很可能杀死的只是 `NoxVMHandle.exe`, 但是模拟器界面所在的 `Nox.exe` 并没有被杀死, 然后就出现这种奇怪的情况了

**Comment by MistEO** [comment]
同步群里讨论结果，准备直接 kill 掉进程所在目录及其子目录中所有 exe 的同名进程（

**Comment by horror-proton** [comment]
> 同步群里讨论结果，准备直接 kill 掉进程所在目录及其子目录中所有 exe 的同名进程（

我看到现在用的是 `System.Diagnostics.Process.Kill()` 强制终止, 感觉这样不好, 可能把虚拟机搞坏.

如果真的要根据文件结构杀死的话, 更建议使用 `Process.CloseMainWindow()`, 这个函数对没有 GUI 的进程会返回 `false`, 对 GUI 进程才有效, 这样就相当于手动关闭模拟器了, 感觉更安全一点.

**Comment by MistEO** [comment]
> > 同步群里讨论结果，准备直接 kill 掉进程所在目录及其子目录中所有 exe 的同名进程（
> 
> 我看到现在用的是 `System.Diagnostics.Process.Kill()` 强制终止, 感觉这样不好, 可能把虚拟机搞坏.
> 
> 如果真的要根据文件结构杀死的话, 更建议使用 `Process.CloseMainWindow()`, 这个函数对没有 GUI 的进程会返回 `false`, 对 GUI 进程才有效, 这样就相当于手动关闭模拟器了, 感觉更安全一点. 

内存还占着咋整，关模拟器的目的是释放资源占用吧（？

**Comment by horror-proton** [comment]
可能更好的解决方法是增加一个 "执行命令" 选项, 允许用户自己填写命令行, 比如 https://support.yeshen.com/zh-CN/qt/adb

**Comment by horror-proton** [comment]
> > > 同步群里讨论结果，准备直接 kill 掉进程所在目录及其子目录中所有 exe 的同名进程（
> > 
> > 
> > 我看到现在用的是 `System.Diagnostics.Process.Kill()` 强制终止, 感觉这样不好, 可能把虚拟机搞坏.
> > 如果真的要根据文件结构杀死的话, 更建议使用 `Process.CloseMainWindow()`, 这个函数对没有 GUI 的进程会返回 `false`, 对 GUI 进程才有效, 这样就相当于手动关闭模拟器了, 感觉更安全一点.
> 
> 内存还占着咋整，关模拟器的目的是释放资源占用吧（？

关闭了模拟器窗口一般后面的虚拟机也会关闭吧 (至少应该是可设置的), 如果真的有拒绝关闭的 (比如它弹了个框让你确定关闭) 时候再 Kill 可能比较好 (x

**Comment by ChildeRolando** [comment]
夜神模拟器有同样的问题，我是改用手动调用解决的，用的是如下代码：
`def kill(hwnd, windowname):
  titles = {}
  if IsWindow(hwnd) and IsWindowEnabled(hwnd) and IsWindowVisible(hwnd):
    titles['title'] = GetWindowText(hwnd)
    titles['hwnd'] = hwnd

  if titles:
    if titles.get('title') == windowname:
      hwnd = titles.get('hwnd')
      PostMessage(hwnd, win32con.WM_CLOSE, 0, 0)

EnumWindows(kill, VMName) 
#VMName为模拟器的窗口名，将模拟器实例快捷方式命名为模拟器同名，即可以传入的快捷方式文件名确定窗口名
`

**Comment by yyyy52** [comment]
hyper-v的逍遥模拟器，出现类似问题。除非手动确定退出否则无法通过maa再次启动。
![image](https://user-images.githubusercontent.com/53691794/213139368-13e28c51-a586-4b6a-881f-911ce4908da4.png)

**Comment by ABA2396** [comment]
#3980 添加了雷电、夜神、逍遥模拟器的控制台退出方式，可以试试能不能用 @MouseWhite @yyyy52

**Comment by yyyy52** [comment]
> #3980 添加了雷电、夜神、逍遥模拟器的控制台退出方式，可以试试能不能用 @MouseWhite @yyyy52

在管理员模式下成功关闭hyper-v逍遥模拟器
