### ISSUE TITLE
生息演算相关

### ISSUE THREAD

**Issue by Rinkansumishiro** [MaaAssistantArknights/MaaAssistantArknights#10435]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

生息演算进程较上一版本感觉更像上上版本未修改的模样（生息演算闪退情况和停滞情况（指修改完高级设置后仍会停滞在同一界面）较为严重）

### Version

资源版本：泰拉饭24.09.02
界面版本：v5.6.0-beta.2
核心版本：v5.6.0-beta.2

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/16842757/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/16842758/asst.log)
在2024.9.3 10:10之后
[gui.json](https://github.com/user-attachments/files/16842760/gui.json)
[gui.new.json](https://github.com/user-attachments/files/16842761/gui.new.json)

### 配置信息

Windows11 MuMu模拟器12

**Comment by Rinkansumishiro** [comment]
<img width="932" alt="屏幕截图 2024-09-04 204042" src="https://github.com/user-attachments/assets/587615a5-7c88-4d6f-8f75-9cf025dd0085">
第一日关卡打开后持续数秒就显示任务出错

**Comment by Rbqwow** [comment]
![image](https://github.com/user-attachments/assets/5a169f0f-b1a0-410b-997b-9b3ee3638d73)

**Comment by Alan-Charred** [comment]
> <img alt="屏幕截图 2024-09-04 204042" width="932" src="https://private-user-images.githubusercontent.com/106914193/364378820-587615a5-7c88-4d6f-8f75-9cf025dd0085.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTY2MjEsIm5iZiI6MTcyNTQ1NjMyMSwicGF0aCI6Ii8xMDY5MTQxOTMvMzY0Mzc4ODIwLTU4NzYxNWE1LTdjODgtNGQ2Zi04Zjc1LTljZjAyNWRkMDA4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMzI1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWQ1YjYzNmRlY2MzYjFmM2MyZjI4ODAyMzE5MGU3YTFlOTYxMmQwMmQ0NmJkYjBiNzBiMDQyZDRkNmEwN2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7pAKemBonVcUOUOn06lgA_zzQPmBwfcdcQEJC_IPAR4"> 第一日关卡打开后持续数秒就显示任务出错

您好，修改后部分功能做得不完善给您添麻烦了。
根据您分享的日志文件，估计是队伍中有 1-6 人，导致既没有弹出提示也没有清空队伍。我这就修一下。
请尝试一下在队伍清空的的情况下使用生息演算功能，应该能正常运行。
另外若您使用的是无存档刷点模式，请在删除存档后，于活动主界面开始生息演算任务。与之前的版本相比，短期内将不再支持在局内中途开启生息演算任务。

**Comment by Rinkansumishiro** [comment]
> ![图像](https://private-user-images.githubusercontent.com/55343783/364387364-5a169f0f-b1a0-410b-997b-9b3ee3638d73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTcyMjAsIm5iZiI6MTcyNTQ1NjkyMCwicGF0aCI6Ii81NTM0Mzc4My8zNjQzODczNjQtNWExNjlmMGYtYjFhMC00MTBiLTk5N2ItOWIzZWUzNjM4ZDczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDEzMzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMmU2NGJjZTdhNDM1YTY2OGYyNzk5MGIxOWI5ODE3NjFmNWE0ZTNjYzY4ZTk1MjBjYmMwM2RiNWI5OTFjNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SNCiOHO_1n7YZyMUNtLSKwxRlLUGaRFpfpOZLcuLvZI)
> 
> 清了还是不办事再开

在无存档的情况下开的，开完就卡在这儿了

**Comment by Rinkansumishiro** [comment]
> Warning
> 
> 存在未确认的链接，请谨慎访问。 There are unconfirmed links, please visit with caution.
> 
> > <img alt="屏幕截图 2024-09-04 204042" width="932" src="https://private-user-images.githubusercontent.com/106914193/364378820-587615a5-7c88-4d6f-8f75-9cf025dd0085.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTY2MjEsIm5iZiI6MTcyNTQ1NjMyMSwicGF0aCI6Ii8xMDY5MTQxOTMvMzY0Mzc4ODIwLTU4NzYxNWE1LTdjODgtNGQ2Zi04Zjc1LTljZjAyNWRkMDA4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMzI1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWQ1YjYzNmRlY2MzYjFmM2MyZjI4ODAyMzE5MGU3YTFlOTYxMmQwMmQ0NmJkYjBiNzBiMDQyZDRkNmEwN2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7pAKemBonVcUOUOn06lgA_zzQPmBwfcdcQEJC_IPAR4"> 第一日关卡打开后持续数秒就显示任务出错
> 
> 您好，修改后部分功能做得不完善给您添麻烦了。 根据您分享的日志文件，估计是队伍中有 1-6 人，导致既没有弹出提示也没有清空队伍。我这就修一下。 请尝试一下在队伍清空的的情况下使用生息演算功能，应该能正常运行。 另外若您使用的是无存档刷点模式，请在删除存档后，于活动主界面开始生息演算任务。与之前的版本相比，短期内将不再支持在局内中途开启生息演算任务。

好的。我不是在局内中途开的而是无存档模式开的，现在清空队内人员后可以正常运行，谢谢

**Comment by Rinkansumishiro** [comment]
> Warning
> 
> 存在未确认的链接，请谨慎访问。 There are unconfirmed links, please visit with caution.
> 
> > <img alt="屏幕截图 2024-09-04 204042" width="932" src="https://private-user-images.githubusercontent.com/106914193/364378820-587615a5-7c88-4d6f-8f75-9cf025dd0085.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTY2MjEsIm5iZiI6MTcyNTQ1NjMyMSwicGF0aCI6Ii8xMDY5MTQxOTMvMzY0Mzc4ODIwLTU4NzYxNWE1LTdjODgtNGQ2Zi04Zjc1LTljZjAyNWRkMDA4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMzI1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWQ1YjYzNmRlY2MzYjFmM2MyZjI4ODAyMzE5MGU3YTFlOTYxMmQwMmQ0NmJkYjBiNzBiMDQyZDRkNmEwN2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7pAKemBonVcUOUOn06lgA_zzQPmBwfcdcQEJC_IPAR4"> 第一日关卡打开后持续数秒就显示任务出错
> 
> 您好，修改后部分功能做得不完善给您添麻烦了。 根据您分享的日志文件，估计是队伍中有 1-6 人，导致既没有弹出提示也没有清空队伍。我这就修一下。 请尝试一下在队伍清空的的情况下使用生息演算功能，应该能正常运行。 另外若您使用的是无存档刷点模式，请在删除存档后，于活动主界面开始生息演算任务。与之前的版本相比，短期内将不再支持在局内中途开启生息演算任务。

追加反馈：偶有队伍内有人的情况仍会不提醒卡机（甚至不是第一编队（（）

**Comment by Alan-Charred** [comment]
> 队伍内有人的情况仍会不提醒

我先修着，修完后您再试试。
