### ISSUE TITLE
不适配【滋味】主题

### ISSUE THREAD

**Issue by haze347** [MaaAssistantArknights/MaaAssistantArknights#10437]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [x] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/user-attachments/assets/d832a158-98a4-434e-be10-17e409d9f1b4)
无法刷理智

### Version

v5.6.0-beta.2

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16844170/asst.log)
[gui.log](https://github.com/user-attachments/files/16844171/gui.log)
[gui.json](https://github.com/user-attachments/files/16844175/gui.json)

### 配置信息

Win11
MUMU12，未开启截图增强

**Comment by ABA2396** [comment]
#10427
