### ISSUE TITLE
252班表內容誤植為243

### ISSUE THREAD

**Issue by uttchen** [MaaAssistantArknights/MaaAssistantArknights#10431]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

252 班表內容錯誤：現有 252 班表其實為 243 的班表
從 .json 檔內可以看到，現有班表只排了 4製造站，並且有 3發電站

### Version

Core Version: v5.6.0-beta.2

### 日志和配置文件

無關。

### 配置信息

無關。

### 截图或录屏

![image](https://github.com/user-attachments/assets/44b9d290-126f-41bb-b518-2c47001825e8)

**Comment by status102** [comment]
等会问问有没有人做

**Comment by ABA2396** [comment]
> 等会问问有没有人做

先把记录里的还原出来吧（还是说一直都没有）
