### ISSUE TITLE
MAA进行萨卡兹肉鸽时会卡在“以血还血”节点

### ISSUE THREAD

**Issue by CCH3CH3CH3Li** [MaaAssistantArknights/MaaAssistantArknights#10432]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

MAA进行自动肉鸽操作时选择了进入“以血还血”节点，在选择干员部署到第三个敌人下方格子后卡住，长时间无操作。手动完成关卡后仍能继续其他自动肉鸽操作。

### Version

Resource Version: 泰拉饭24.09.02
UI Version: v5.6.0-beta.2
Core Version: v5.6.0-beta.2

### 日志和配置文件

[log.zip](https://github.com/user-attachments/files/16840649/log.zip)

### 配置信息

**Windows信息：**
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2024/‎3/‎16
操作系统内部版本	19045.4780
体验	Windows Feature Experience Pack 1000.19060.1000.0

**模拟器信息：**
模拟器品牌：MUMU12
模拟器版本 :  4.0.2.3233
分辨率 :  2560 * 1440
DPI：360
帧率：240
截图增强：开启
GPU 加速推理：开启
GPU型号：NVIDIA GeForce RTX 4070 SUPER

**Comment by Daydreamer114** [comment]
请找到这个文件并上传：debug\Roguelike\2024-09-03_02-36-19-358_raw.png

另外，maa点击的是小白点这一行的坐标，无论如何都不应该点进战斗
![image](https://github.com/user-attachments/assets/f687afd6-f157-4bcc-814f-cd038fbd0e28)
![image](https://github.com/user-attachments/assets/dec5e933-b8cb-49d0-9efc-13963a15cfe6)

**Comment by Daydreamer114** [comment]
log中显示maa点了两次下方的选项，但是没有成功离开狭路相逢，没有更多信息的情况下，我认为是你的设备卡顿了

**Comment by CCH3CH3CH3Li** [comment]
![2024-09-03_02-36-19-358_raw](https://github.com/user-attachments/assets/228ca834-0a17-4cf7-8c58-b5394ec9ae0f)

**Comment by CCH3CH3CH3Li** [comment]
收到，可能确实是设备卡顿，会留意是否有类似情况复现，届时会提交issue。感谢回复，辛苦了。
________________________________
发件人: 晓丶梦丶仁 ***@***.***>
发送时间: 2024年9月3日 12:01
收件人: MaaAssistantArknights/MaaAssistantArknights ***@***.***>
抄送: CCH3CH3CH3Li ***@***.***>; Author ***@***.***>
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] MAA进行萨卡兹肉鸽时会卡在“以血还血”节点 (Issue #10432)


log中显示maa点了两次下方的选项，但是没有成功离开狭路相逢，没有更多信息的情况下，我认为是你的设备卡顿了

―
