### ISSUE TITLE
任务结束后增加邮件通知设置

### ISSUE THREAD

**Issue by Weiss-Guertena** [MaaAssistantArknights/MaaAssistantArknights#10436]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

玩别的游戏用脚本发现有这个功能，感觉我们也可以试试

### 有什么好的想法？

在完成一次任务后发送邮件通知，记录任务开始前的理智、龙门币、合成玉、石头等数量以及结束的数量，完成的任务，关卡等

### 其他内容

> `
![$)G0ZNEFT0QU9%LVJVO_DOR](https://github.com/user-attachments/assets/14731ec1-cf86-4d8e-a32f-ecc539b0080b)
`
![12](https://github.com/user-attachments/assets/c3cf1cca-3ea4-4341-8561-058693711cbb)
 #/

**Comment by Weiss-Guertena** [comment]
![$)G0ZNEFT0QU9%LVJVO_DOR](https://github.com/user-attachments/assets/5d0d89c9-d083-45b4-8450-0fcfe00cf779)

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/3cbf05c4-70fb-4f01-9004-95159c7d22be)

**Comment by Weiss-Guertena** [comment]
您好，已收到您的邮件。
