### ISSUE TITLE
【允许吃源石保存状态】会被自动取消勾选

### ISSUE THREAD

**Issue by MobiusT** [MaaAssistantArknights/MaaAssistantArknights#10447]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

开启【允许吃源石保存状态】并选中吃源石后，如果遇到了原先会导致一次性勾选取消的情况下仍然会取消勾选吃源石，是否能在开启保存状态后不再自动取消勾选

**Comment by Daydreamer114** [comment]
碎石刷理智本来就是只允许当次生效，因为这是一个比较危险的，消耗玩家游戏内付费货币的功能

**Comment by ABA2396** [comment]
我看看怎么回事）

**Comment by ABA2396** [comment]
我先吃一颗看看）
