### ISSUE TITLE
MAA进行萨卡兹肉鸽时会卡在“分队选择”界面

### ISSUE THREAD

**Issue by m5s2l1** [MaaAssistantArknights/MaaAssistantArknights#10448]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

该问题仅在萨卡兹肉鸽中出现，其余三款肉鸽中均正常运行
MAA进行自动肉鸽操作时在进入“分队选择”界面后卡住，长时间无操作。手动完成选择后不能继续其他自动肉鸽操作。会自动放弃本次探索

### Version

泰拉饭
5.5.11452
5.5.11452

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16848468/asst.log)
[gui.json](https://github.com/user-attachments/files/16848545/gui.json)
[gui.log](https://github.com/user-attachments/files/16848472/gui.log)

### 配置信息

 mumu12，win10/win11，全分辨率、dpi、帧率下均存在
MuMu 截图增强开启
GPU 加速推理 否

### 截图或录屏

![image](https://github.com/user-attachments/assets/3c81b752-99ad-4aa9-9d3a-4711082d6b48)

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/119ded42-6aa3-48b7-9b56-2dd1c748c705)
你这是把中间这段日志给删了？

**Comment by m5s2l1** [comment]
重新传
[gui_new .log](https://github.com/user-attachments/files/16849286/gui_new.log)
[asst_new .log](https://github.com/user-attachments/files/16849289/asst_new.log)

**Comment by Daydreamer114** [comment]
请找到 debug\roguelike\2024-09-03_21-15-12-490_raw.png 并上传

**Comment by m5s2l1** [comment]
![490_raw](https://github.com/user-attachments/assets/743160bf-b479-4220-90cb-5ce7e6a433f0)
![852_raw](https://github.com/user-attachments/assets/eb522c68-aab2-4ebb-a4e0-73cc3ccaddaa)

**Comment by Daydreamer114** [comment]
芝士什么（

**Comment by m5s2l1** [comment]
> 芝士什么（

？？？

**Comment by Daydreamer114** [comment]
> > 芝士什么（
> 
> ？？？

我对看到截图后对这个bug感到无能为力的状态进行一个感叹

**Comment by m5s2l1** [comment]
> > > 芝士什么（
> > 
> > 
> > ？？？
> 
> 我看到这个 bug 的截图后感到惊讶不已，感到震惊

震惊的地方是指？ 刚又去测试了v5.6.x beta x 问题依旧存在

**Comment by m5s2l1** [comment]
> 你是那个模拟器，而不是找maa
 
如果是模拟器的问题，另外三款肉鸽的界面都是一样的截图，如何解释？

**Comment by ABA2396** [comment]
> 如果是模拟器的问题，另外三款肉鸽的界面都是一样的截图，如何解释？

你问我我咋知道，maa 就是拿到截图然后去处理判断，你图都给的有问题那我怎么处理

**Comment by Daydreamer114** [comment]
@m5s2l1 你从哪quote到的对话？
![image](https://github.com/user-attachments/assets/33e5a5b5-6b8b-470b-bbc1-393d4ee6d566)
![image](https://github.com/user-attachments/assets/31dcd453-863b-45e2-8bda-e18bf81336c9)
