### ISSUE TITLE
任务完成后关机选项失效

### ISSUE THREAD

**Issue by 68star89** [MaaAssistantArknights/MaaAssistantArknights#10451]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

任务完成后关机选项失效，初步复现后，发现目前MAA在执行自动关机前未关闭模拟器，导致模拟器阻碍关机进程执行，计算机在关机失败后自动进入休眠（注销？）状态

### Version

Resource Version: 泰拉饭24.09.02
UI Version: v5.6.0-beta.2.d010.g92b4fee51
Core Version: v5.6.0-beta.2.d010.g92b4fee51

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16859585/asst.log)
[gui.log](https://github.com/user-attachments/files/16859586/gui.log)
[gui.json](https://github.com/user-attachments/files/16859588/gui.json)

### 配置信息

WIN11 10.0.22631
MuMu12 截图增强、GPU增强已开启

**Comment by ABA2396** [comment]
关机只是给所以应用发送一个关闭的信号，挂起的应用在超时后会强制关闭。而有些应用确实会拒绝关机，我感觉这种情况下不应该由maa来决定。如果是模拟器的原因，可以勾上退出模拟器提前调用mumu的api关闭

**Comment by 68star89** [comment]
> 关机只是给所以应用发送一个关闭的信号，挂起的应用在超时后会强制关闭。而有些应用确实会拒绝关机，我感觉这种情况下不应该由maa来决定。如果是模拟器的原因，可以勾上退出模拟器提前调用mumu的api关闭

但是之前只勾选关机不勾选退出模拟器的话也能正常关机，就这次出了问题，莫非是mumu的更新出了什么幺蛾子？（

**Comment by ABA2396** [comment]
这个情况是必现的吗？一般来说应用拒绝关机过一段时间也是会关闭的。能录个视频看看吗？

**Comment by 68star89** [comment]
> 这个情况是必现的吗？一般来说应用拒绝关机过一段时间也是会关闭的。能录个视频看看吗？

必现，刚刚又复现了一次，但github貌似只能发10mb的文件？视频发不出来

**Comment by status102** [comment]
> 不勾选退出模拟器的话也能正常关机，就这次出了问题，莫非是mumu的更

近期更换了关机的实现

**Comment by 68star89** [comment]
二次试验，勾选退出模拟器-关机可以正常实现关机，但仅勾选关机仍会被模拟器阻止关机导致关机失败，系统回到锁屏界面

**Comment by ABA2396** [comment]
按理来说现在的逻辑是合理的，有应用阻止关机不关机也没问题。

**Comment by ABA2396** [comment]
按理来说现在的逻辑是合理的，有应用阻止关机不关机也没问题。
