### ISSUE TITLE
泰拉饭活动中的“宝箱的肉”识别不出来

### ISSUE THREAD

**Issue by ala-404** [MaaAssistantArknights/MaaAssistantArknights#10456]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

活动要求的5个食材除了宝箱的肉无法截图下来识别，其他都截图下来识别

### Version

Resource Version: 泰拉饭24.09.02
UI Version: v5.6.0-beta.2.d010.g92b4fee51
Core Version: v5.6.0-beta.2.d010.g92b4fee51

### 日志和配置文件

从2024-09-03 23:46:36.912开始
[asst.log](https://github.com/user-attachments/files/16861923/asst.log)
[gui.log](https://github.com/user-attachments/files/16861924/gui.log)
[gui.json](https://github.com/user-attachments/files/16861925/gui.json)

### 配置信息

win11 23h2
mumu12 1920x1080 dpi280 120帧率
截图增强开启 gpu加速推理开启
显卡3060

### 还有别的吗？

识别出来的都在MAA\cache\avatars中
![闪亮果实](https://github.com/user-attachments/assets/5a106c3b-95bf-4a02-abb4-15978fa91f46)
![奇异黑光果实](https://github.com/user-attachments/assets/633dec29-0e5b-4da4-9960-58e87ea4e0c1)
![香甜烤果子](https://github.com/user-attachments/assets/27bf9cf0-fee3-4087-9552-c68664353214)
![缤纷果酒](https://github.com/user-attachments/assets/ea2d53e5-a58e-4dee-9488-0073c52dd6bd)

**Comment by Daydreamer114** [comment]
你的asst.log和gui.log的时间是错开的

**Comment by ala-404** [comment]
2024-09-04 15:42:17.586开始
[asst.log](https://github.com/user-attachments/files/16862528/asst.log)
[gui.log](https://github.com/user-attachments/files/16862531/gui.log)

**Comment by ala-404** [comment]
2024-09-04 15:49:46.571开始
[asst.log](https://github.com/user-attachments/files/16862647/asst.log)
[gui.log](https://github.com/user-attachments/files/16862648/gui.log)

**Comment by Manicsteiner** [comment]
> [2024-09-04 15:49:46.571][TRC][Px9c4][Tx57bc] asst::WordOcr [{ 宝箱的肉?: [ 0, 0, 100, 24 ], score: 0.994012 }] by OCR Rec , cost 8 ms
[2024-09-04 15:49:46.571][TRC][Px9c4][Tx57bc] Proceed [{ 宝箱的肉?: [ 17, 185, 100, 24 ], score: 0.994012 }]
[2024-09-04 15:49:46.571][WRN][Px9c4][Tx57bc] ocr with preprocess got a invalid name, try to use detect model
[2024-09-04 15:49:46.608][TRC][Px9c4][Tx57bc] asst::WordOcr [{ 宝箱的肉?: [ 12, 9, 98, 24 ], score: 0.992171 }] by OCR Pipeline , cost 37 ms
[2024-09-04 15:49:46.609][TRC][Px9c4][Tx57bc] Proceed [{ 宝箱的肉?: [ 17, 186, 98, 24 ], score: 0.992171 }]

识别成半角问号了，需要全角问号，大概加一条ocrreplace就可以吧

**Comment by Daydreamer114** [comment]
我测一会，过会加
