### ISSUE TITLE
新界面UI“滋味”识别未支持

### ISSUE THREAD

**Issue by BlazingQ** [MaaAssistantArknights/MaaAssistantArknights#10452]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

新更新的迷宫饭界面UI“滋味”尚未支持识别，希望早点支持。

### 其他内容

![image](https://github.com/user-attachments/assets/f8b18921-014d-4abe-b611-0119ca25e16b)

**Comment by ABA2396** [comment]
#10427
