### ISSUE TITLE
迷宫饭主题界面无法识别

### ISSUE THREAD

**Issue by losscia** [MaaAssistantArknights/MaaAssistantArknights#10454]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

游戏联动版本更新后，新加入的主题界面经多次测试后，确认maa无法识别

### Version

Resource Version: 泰拉饭24.09.02
UI Version: v5.6.0-beta.2
Core Version: v5.6.0-beta.2

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16861108/asst.log)
[gui.log](https://github.com/user-attachments/files/16861110/gui.log)
[gui.json](https://github.com/user-attachments/files/16861112/gui.json)

### 配置信息

操作系统版本：Windows11(22631.4112)
模拟器品牌：MuMu12
模拟器分辨率：1920*1080
模拟器dpi：280
MuMu截图增强是否开启：是
GPU加速推理是否开启：是(型号:NVIDIA GeForce RTX 3070 Laptop)

### 截图或录屏

![屏幕截图 2024-09-04 130251](https://github.com/user-attachments/assets/18c7db3b-7d5b-4c43-adeb-ac8cab9eff26)

**Comment by HoshinoAyako** [comment]
duplicate
