### ISSUE TITLE
希望提供刷本优先级排序，依次找到当前开放关卡

### ISSUE THREAD

**Issue by miyouzi** [MaaAssistantArknights/MaaAssistantArknights#1045]
众所周知，资源副本不是每天都有开的。希望可以自定义刷本顺序，依顺序找到当前开放的关卡。

比如 先钱本，后红票，都没开就 1-7。

另希望加入芯片本寻路，配合以上功能能发挥更大作用。

**Comment by MistEO** [comment]
@ABA2396 学姐——带带芯片本导航（

**Comment by ABA2396** [comment]
芯片本寻路有了，优先级排序新建文件夹）

**Comment by ABA2396** [comment]
现在有备选了，可以更新版本去设置里开启（虽然只有一个备选）
