### ISSUE TITLE
公招自动确认4星出现问题

### ISSUE THREAD

**Issue by fzj-official** [MaaAssistantArknights/MaaAssistantArknights#10450]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

在公招的时候出现4星tag
自动确认4星tag已打钩的情况下，无法自动确认，而是直接跳过，

### Version

Resource Version: 泰拉饭24.09.02
UI Version: v5.6.0-beta.2
Core Version: v5.6.0-beta.2

### 日志和配置文件

时间点为2024-09-04 09-13-56左右
[asst.log](https://github.com/user-atta
[gui.json](https://github.com/user-attachments/files/16859577/gui.json)
chments/files/16859573/asst.log)
[gui.log](https://github.com/user-attachments/files/16859574/gui.log)

### 配置信息

win10 mumu 已开增强

### 截图或录屏

https://github.com/user-attachments/assets/f016737e-2d5e-4ff6-a6c0-8a8ecc3176ea.mp4

**Comment by Daydreamer114** [comment]
你勾选了手动确认1星，有支援器械，不就不选4星了吗

**Comment by HoshinoAyako** [comment]
牛牛：这是1星tag，需要手动确认。
牛牛：不对，这是4星tag，得自动确定。
牛牛：啊，对的对的
牛牛：嗯？不对！哎呀不对不对！
