### ISSUE TITLE
开启截图增强后生息验算偶发报错

### ISSUE THREAD

**Issue by TheZafkiel** [MaaAssistantArknights/MaaAssistantArknights#10463]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

开启截图增强后  生息验算-通过开局刷点数  第一幕开始时 偶发报错
（已测试关闭截图增强挂机半小时无报错）
（报错位于视频02：00-02：15处）

### Version

Resource Version: 泰拉饭24.09.02
UI Version: v5.6.0-beta.2
Core Version: v5.6.0-beta.2

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/16870683/gui.log)
[asst.log](https://github.com/user-attachments/files/16870685/asst.log)
[gui.json](https://github.com/user-attachments/files/16870686/gui.json)

### 配置信息

MuMu 12 V4.0.3(3244) DX模式 4核4G 1920x1080(dpi 280) 60fps
开启 MuMu 截图增强模式 开启 GPU 加速推理
NVIDIA GeForce GTX 1080
驱动程序版本:	32.0.15.6081
DirectX 版本:	12 (FL 12.1)

### 截图或录屏

https://github.com/user-attachments/assets/8fd328ed-54d8-4fa0-b9ab-cbd2b7455a9f
![11](https://github.com/user-attachments/assets/888c2332-267f-41d5-9f08-9bc38357d296)
![22](https://github.com/user-attachments/assets/6ddba280-f762-4d8c-90bc-6856e2e7eb5d)

**Comment by blade2005** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
