### ISSUE TITLE
Reclamation in EN server not starting 

### ISSUE THREAD

**Issue by lirao** [MaaAssistantArknights/MaaAssistantArknights#10469]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

After a UI update (introduction of the Contention Reiteration missions?) in Reclamation mode, MAA is unable to start this mode, it will get stuck at the loading page and unable to proceed. tried both 5.6.0 beta1 and beta2

### Version

Resource Version: What the Firelight Casts - Retrospection24.09.02
UI Version: v5.6.0-beta.2
Core Version: v5.6.0-beta.2

### Log and config files

[asst.log](https://github.com/user-attachments/files/16882551/asst.log)
[gui.log](https://github.com/user-attachments/files/16882552/gui.log)

### Configuration information

Bluestacks 5.13.220.1002

### Screenshots or recordings

![Screenshot_2024 09 04_18 06 07 740](https://github.com/user-attachments/assets/781faf25-b964-437f-bba2-cad9202257b1)

**Comment by Daydreamer114** [comment]
We are not supporting starting the tasks with this interface. Also, Reclamation Algorithm was refactored each, both in beta1 and beta2.

Delete your save data manually with "I do not have a save" strategy or click "Resume" manually with "I do have a save" strategy.

Try read the tutorial description in the general setting of "Reclamation Algorithm".
