### ISSUE TITLE
MAA可以连接到模拟器并打开明日方舟，但随后会不停出现任务出错的情况

### ISSUE THREAD

**Issue by SheenaMimi** [MaaAssistantArknights/MaaAssistantArknights#10467]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [ ] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

MAA在模拟器进入明日方舟界面前无任何异常，但是当MAA完成启动的任务，就会在StartUp处卡顿一段时间，然后发生任务出错的情况

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16874080/asst.log)
[gui.log](https://github.com/user-attachments/files/16874081/gui.log)
[gui.json](https://github.com/user-attachments/files/16874086/gui.json)

### 配置信息

操作系统:Win11 版本23H2 (OS 内部版本 22631.4037)
模拟器:雷电模拟器
模拟器分辨率:1920*1080
DPI:280
帧率:60

### 截图或录屏

![image](https://github.com/user-attachments/assets/b99758e7-bbe9-48fa-8e08-b0181c1a57ab)

**Comment by Rbqwow** [comment]
用的是迷宫饭主题？

**Comment by SheenaMimi** [comment]
是的
