### ISSUE TITLE
重新安装游戏后，窗口识别错误

### ISSUE THREAD

**Issue by likdawn** [MaaAssistantArknights/MaaAssistantArknights#10466]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述
我是通过【截图测试】发现的问题
错误：重装游戏，运行maa发现识别的是模拟器主窗口
衍生问题：因为窗口错误的判定为主窗口，maa会不断尝试启动游戏，但实际窗口已经在明日方舟中，有可能导致勿进商店并消费源石
个人解决办法：maa设置→连接设置→修改屏幕编号

### Version

UI Version: v5.5.11452

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16873618/asst.log)
[gui.log](https://github.com/user-attachments/files/16873621/gui.log)
[gui.json](https://github.com/user-attachments/files/16873622/gui.json)
大概在23点40分以后

### 配置信息

win11家庭中文版
操作系统版本：22631.4037
模拟器：mumu12
模拟器分辨率1600x900 DPI：300 60帧
MuMu截图增强已经开启
GPU加速推理未开启 GeForce RTX 2060

### 还有别的吗？

原先是模拟器的游戏中心安装的，重装是用taptap

**Comment by ABA2396** [comment]
哥们其实你已经很接近真相了
![image](https://github.com/user-attachments/assets/633c4118-7b7b-4e9a-ab34-9a2adceb6be8)
