### ISSUE TITLE
求预约叫醒睡了一半的令的功能和线索交流结束重开功能

### ISSUE THREAD

**Issue by wb871029** [MaaAssistantArknights/MaaAssistantArknights#1047]
除非调准时闹钟，否则我总是忘记叫醒令和忘记重开线索交流，让令直接睡到满心情了。
线索也是一样，就算调了闹钟，几周过去慢慢延后了几分钟，切到干别的事就忘记回来开了。
求能识别宿舍里的令回到半血时间和线索交流结束时间，自动生产预约任务功能。炭条被九色鹿用完了，不舍得给令消耗。。。

**Comment by MistEO** [comment]
没听懂（）

**Comment by wb871029** [comment]
就是在令恢复到12心情是把她踢出休息室。。。
