### ISSUE TITLE
Reclamation Stuck in "Score" Screen - YostarEN

### ISSUE THREAD

**Issue by ItsukaHiro1111** [MaaAssistantArknights/MaaAssistantArknights#10477]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

RA auto is have bug. MAA cant understand the screenshot so it's stuck here forever (or show error and stop).
![MuMu12-20240905-135334](https://github.com/user-attachments/assets/ecd24495-c5aa-4fb8-abab-06b68fa0a73e)

2 weeks ago, RA auto is working very good, without problems.

### Version

Resource Version: What the Firelight Casts - Retrospection24.09.02
UI Version: v5.6.0-beta.2
Core Version: v5.6.0-beta.2

### Log and config files

[asst.log](https://github.com/user-attachments/files/16884573/asst.log)
[gui.log](https://github.com/user-attachments/files/16884575/gui.log)
[gui.json](https://github.com/user-attachments/files/16884590/gui.json)

### Configuration information

Windows 11 Pro -  24H2 - 26100.1591
Mumu163 v4.0.6 - 1280x720 - 240DPI - 60FPS
MuMu Screenshot Enhancement Enabled
GPU Accelerated: NVIDIA GeForce RTX 3050 Laptop

**Comment by Daydreamer114** [comment]
same

**Comment by HX3N** [comment]
`T` has disappeared

``` python
[2024-09-05 12:45:50.664][INF][Px2424][Tx221c] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["Tales@RA@PNS-FinishCalc","Tales@RA@PNS-SkipToCalc-StartToday","Tales@RA@PNS-SkipToCalc","Tales@RA@PNS-SkipToCalc-CalcOrNextDay"]},"first":["Tales@RA@ProsperityNoSave"],"pre_task":"Tales@RA@PNS-SkipToCalc-CalcOrNextDay","subtask":"ProcessTask","taskchain":"Reclamation","taskid":1}
[2024-09-05 12:45:50.807][TRC][Px2424][Tx221c] asst::WordOcr [{ ap anywhere to continue: [ 24, 28, 202, 13 ], score: 0.942240 }] by OCR Pipeline , cost 128 ms
```

    "Tales@RA@FinishCalc": {
        "text": ["Tap anywhere to continue"]
    },

**Comment by Manicsteiner** [comment]
maybe too small roi area again #10414 task.json(JP) - Tales@RA@ResourceGained
