### ISSUE TITLE
开机后第一次启动所有设置丢失

### ISSUE THREAD

**Issue by LinYanxi0** [MaaAssistantArknights/MaaAssistantArknights#10481]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

启动maa后，发现进入引导模式，同时先前的链接地址及个人设置等都恢复默认

### Version

Resource Version: 泰拉饭24.09.02
UI Version: v5.6.0-beta.2
Core Version: v5.6.0-beta.2

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16885289/asst.log)

[gui.json](https://github.com/user-attachments/files/16885292/gui.json)

### 配置信息

win10 22h2
mumu12
截图增强开启
gpu加速关闭

### 还有别的吗？

上个版本（太阳甩在身后）也出现过

**Comment by RWoxiN** [comment]
我也遇到了，出现两次了

**Comment by status102** [comment]
之前所使用的完成后动作是啥

**Comment by RWoxiN** [comment]
> 之前所使用的完成后动作是啥

一直是退出明日方舟，然后晚上睡前手动关机，第二天早上开机配置就没了；每天都是同样的行为，一般第二天早上开机是正常的。

**Comment by LinYanxi0** [comment]
无动作，有结束后脚本

**Comment by ABA2396** [comment]
gui.log

**Comment by MFunction96** [comment]
v5.6.0也出现了，重新开机配置全部重置了。

我注意到gui.log里有个异常，很大概率是这个问题的根源。GUI拿C#写的话，路径拼接为什么不用`Path.Combine(arg1, arg2, ...)`，而选择了手动拼接？

![image](https://github.com/user-attachments/assets/99e3c29e-fc47-4b22-926f-395b56da0fb1)

[gui.log](https://github.com/user-attachments/files/16987098/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/16987100/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/16987101/asst.log)

**Comment by MFunction96** [comment]
我注意到WpfGui有两个配置相关的类，合理怀疑出现了**文件读写锁**冲突，目前猜测是和**资源更新**逻辑相关。
- `src\MaaWpfGui\Helper\ConfigurationHelper.cs` 使用`System.Text.Json.JsonSerializer`进行Json序列化与反序列化工作
- `src\MaaWpfGui\Configuration\ConfigFactory.cs` 使用`Newtonsoft.Json.JsonConvert`进行Json序列化与反序列化工作
以我粗浅的代码阅读来看，各自在独立static方法工作，文件读写的触发条件和机制各不相同。`ConfigFactory`侧重于GUI配置操作，`ConfigurationHelper`用的地方就多了，包括上面提到的**资源更新**。
**资源更新**是独立的线程进行，更新的同时会写配置文件；而GUI线程在MAA启动时会进行读操作。两个线程极有可能使用了两个不同的配置类，两个类的lock并不是同一个，因此实际并未做文件读写控制，会偶发性出现了读写冲突

**Comment by ABA2396** [comment]
ConfigFactory是重构后的配置，写的是 gui.new.json，照理来说应该没影响吧

**Comment by MFunction96** [comment]
> ConfigFactory是重构后的配置，写的是 gui.new.json，照理来说应该没影响吧

抱歉，是我眼花了没注意到文件不同，光顾着看逻辑了=_=||

**Comment by MFunction96** [comment]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> ConfigFactory是重构后的配置，写的是 gui.new.json，照理来说应该没影响吧

目前我这边这样操作偶尔会触发这个bug，触发步骤如下：
1. 按照我本地设备及定时任务配置MAA。附完整配置：[config.zip](https://github.com/user-attachments/files/16988654/config.zip)
2. 启动MAA代理，**开始唤醒**检测并自动配置后**停止**MAA代理
3. 修改ADB路径至自行配置ADB路径
4. 重新启动MAA代理并等待完成
5. 在不退出MAA的情况下，直接重启计算机
6. 偶尔会出现下图情况，json文件为空。附出现异常时的配置文件：[bug_config.zip](https://github.com/user-attachments/files/16988685/bug_config.zip)

![image](https://github.com/user-attachments/assets/879bac96-18d8-4243-8472-8d87b028b4b2)
![image](https://github.com/user-attachments/assets/e3fbe019-247c-4350-bd7a-22962ac2cba1)

附复现操作时的log文件：[debug.zip](https://github.com/user-attachments/files/16988691/debug.zip)

**Comment by ABA2396** [comment]
怀疑是这个 commit 后出现的问题，等下看看
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/9c69899620030211d6b63638405b8f85e979d27f

**Comment by ABA2396** [comment]
好像也不是，虽然有点问题，但是都是和 .bak 相关，还是不知道为什么 gui.json 会变成空的

**Comment by ABA2396** [comment]
@MFunction96 是正常关机吧

**Comment by ABA2396** [comment]
我这边复现不出来，你可以试试看这个版本再用你说的方法会不会再遇到这个问题
https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/10845625660/artifacts/1928820477
@MFunction96

**Comment by MFunction96** [comment]
> @MFunction96 是正常关机吧

对，是的，正常关机，没有强制断电。我复现也是试了好几次才出来一次。我试试这个版本再观察一下。

**Comment by MFunction96** [comment]
> 我这边复现不出来，你可以试试看这个版本再用你说的方法会不会再遇到这个问题 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/10845625660/artifacts/1928820477 @MFunction96

另外，有可能的话可否分别在代码和设置里增加类似`Debug`或者`Verbose`级别的日志记录设置，出现问题的时候可调整日志级别记录更详细的信息方便Debug。

**Comment by MFunction96** [comment]
> 怀疑是这个 commit 后出现的问题，等下看看 [9c69899](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/9c69899620030211d6b63638405b8f85e979d27f)

我打开代码看到Resharper提示我有几个变量没有同步锁限制，我没有仔细读代码，但直觉告诉我图二这几个变量是不是选择`ConcurrentDictionary<T1,T2>`（线程安全字典）类型好像更合理…？

![image](https://github.com/user-attachments/assets/1cc43c3f-966c-4d7b-ab05-73840ad1e322)

![image](https://github.com/user-attachments/assets/ea7896d3-3797-48f3-b49f-2d4fb9a06914)

**Comment by ABA2396** [comment]
> 我打开代码看到Resharper提示我有几个变量没有同步锁限制，我没有仔细读代码，但直觉告诉我图二这几个变量是不是选择`ConcurrentDictionary<T1,T2>`（线程安全字典）类型好像更合理…？
> 

那个分支里已经都加上锁了，直接换 ConcurrentDictionary 应该也行

**Comment by MFunction96** [comment]
> 我这边复现不出来，你可以试试看这个版本再用你说的方法会不会再遇到这个问题 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/10845625660/artifacts/1928820477 @MFunction96

这个版本问题依旧，我刚启动了触发了这个Bug。
配置备份：[gui.json.zip](https://github.com/user-attachments/files/16992387/gui.json.zip)

**Comment by ABA2396** [comment]
> > 我这边复现不出来，你可以试试看这个版本再用你说的方法会不会再遇到这个问题 [MaaAssistantArknights/MaaAssistantArknights/actions/runs/10845625660/artifacts/1928820477](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/10845625660/artifacts/1928820477) @MFunction96
> 
> 这个版本问题依旧，我刚启动了触发了这个Bug。 配置备份：[gui.json.zip](https://github.com/user-attachments/files/16992387/gui.json.zip)

是说 gui.json.bak 有数据但 gui.json 没有？发下日志看看

**Comment by MFunction96** [comment]
> > > 我这边复现不出来，你可以试试看这个版本再用你说的方法会不会再遇到这个问题 [MaaAssistantArknights/MaaAssistantArknights/actions/runs/10845625660/artifacts/1928820477](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/10845625660/artifacts/1928820477) @MFunction96
> > 
> > 
> > 这个版本问题依旧，我刚启动了触发了这个Bug。 配置备份：[gui.json.zip](https://github.com/user-attachments/files/16992387/gui.json.zip)
> 
> 是说 gui.json.bak 有数据但 gui.json 没有？发下日志看看

是的，和上述情况一样。
[debug.zip](https://github.com/user-attachments/files/16994101/debug.zip)

**Comment by ABA2396** [comment]
#10601 这些已经加了，不读 .bak 是之前有人重构的时候写错文件名了
加了个根目录下有 DEBUG 或者 DEBUG.txt 时输出 Debug 和 Verbose 信息
