### ISSUE TITLE
支持「集成战略」中途游戏崩溃后重启游戏

### ISSUE THREAD

**Issue by xfrqh** [MaaAssistantArknights/MaaAssistantArknights#1049]
用MAA长时间挂「集成战略」。亿段时间后查看效果，发现方舟已关闭。MAA没有重启方舟来继续任务。

<img width="1236" alt="2022-07-01_15-20-13" src="https://user-images.githubusercontent.com/73733485/176848378-70f7e5b2-1894-4635-a09d-77c69a986762.png">

----

[asst.7z.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9027044/asst.7z.zip)

**Comment by MistEO** [comment]
游戏崩了吧，模拟器 or 游戏本身的锅，maa 现在没有支持肉鸽中途游戏崩溃的重启的
