### ISSUE TITLE
5.6日服生息演算无存档刷点数时任务出错

### ISSUE THREAD

**Issue by wavesZh** [MaaAssistantArknights/MaaAssistantArknights#10499]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

5.6版本日服maa新增生息演算，故尝试。在任务执行过程中，时不时发生任务出错提醒导致任务中断。出错发生节点不确定，什么时候都可能发生

### Version

UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/16902374/gui.log)

[gui.json](https://github.com/user-attachments/files/16902376/gui.json)
[asst.log](https://github.com/user-attachments/files/16902377/asst.log)

### 配置信息

win10  mumu12 截图增强开启

**Comment by ABA2396** [comment]
cc @Alan-Charred 卡在识别 Tales@RA@SkipDay.png 了

@wavesZh 来个卡住界面的截图看看

**Comment by wavesZh** [comment]
> cc @Alan-Charred 卡在识别 Tales@[RA@SkipDay.png](mailto:RA@SkipDay.png) 了
> 
> @wavesZh 来个卡住界面的截图看看

出问题时的界面很随机，什么节点都可能发生。
![MuMu12-20240906-151002](https://github.com/user-attachments/assets/2fff55d9-aa8a-4e7e-8709-855cc6c0b608)
![MuMu12-20240906-152004](https://github.com/user-attachments/assets/c04264c5-76e0-43d8-a997-cbeeb42e70b3)
![MuMu12-20240906-144933](https://github.com/user-attachments/assets/fdd3c8e3-b93e-4092-9ae2-59069fe80c73)

发现一个很奇怪的现象，只要mumu模拟器不在最上层挂着，就很快会出问题。在最上层挂十几分钟都没什么事，想用电脑做其他事，把mumu最小化或者被其他东西覆盖后不一会就出问题了

**Comment by Alan-Charred** [comment]
您好，抱歉回复迟了。请尝试关闭截图增强模式，应该会好很多。
我已经增加了一些地方通过回滚机制增加容错率，将在下个版本推出，到时候您再试试看截图增强模式下的体验。
