### ISSUE TITLE
V5.6.0 日服生息演算卡在最开始这个界面

### ISSUE THREAD

**Issue by Argonautes0607** [MaaAssistantArknights/MaaAssistantArknights#10497]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

如题

### Version

v5.6.0（514）

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16901494/asst.log)

### 配置信息

macOS 14.5
playcover

### 截图或录屏

<img width="1546" alt="截屏2024-09-06 08 46 59" src="https://github.com/user-attachments/assets/9b13523e-df51-47f8-9e44-493e281eb45e">

**Comment by Manicsteiner** [comment]
> [2024-09-06 08:46:45.713][TRC][Px17a91][Tx600f] asst::WordOcr [{ 集会環: [ 10, 9, 52, 15 ], score: 0.788493 }, { 人タカ+事二印: [ 10, 28, 102, 14 ], score: 0.680272 }] by OCR Pipeline , cost 84 ms

ocr 问题，稍后和另一个重量级问题一起修
