### ISSUE TITLE
自动公招相关功能建议

### ISSUE THREAD

**Issue by PianCat** [MaaAssistantArknights/MaaAssistantArknights#105]
能否添加一个针对小车和火神/因陀罗的公招机制

大概就是见到小车优先锁小车，见到火神或因陀罗优先锁这两个，没有的时候就去赌火神或者因陀罗。

优先级顺序大概可以做一个这样的操作：

六星＞五星因陀罗和火神＞五星＞四星或小车＞普通

**Comment by MistEO** [comment]
小车支持了，五星的话没啥好办法我感觉？
