### ISSUE TITLE
maa能否支持更低版本的mac

### ISSUE THREAD

**Issue by wavesZh** [MaaAssistantArknights/MaaAssistantArknights#10508]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

应用点击提示 ”您使用的是macOS 10.15.7。该应用程序要求macOS 12.0或更高版本。“
能否支持更低版本的macos。2015款的旧mac，还是想保持目前比较耐用的系统

**Comment by AlisaAkiron** [comment]
macOS 10.15 (Catalina) 已于 2022-09-12 停止支持，macOS 11 (Big Sur) 已于 2023-09-26 停止支持。

**Comment by wangl-cc** [comment]
MAA 使用了一些比较新的 C++ 特性，这些在低版本的 macOS 带的 `libc++` 缺少的支持，所以 MAA 只支持的 macOS 12.0 及以上。如果你真的想在低版本的 macOS 上用 MAA，并且熟悉 C++ 编译，你可以试试装一个高版本的 LLVM，然后用 LLVM 编译链接到 LLVM 的 libc++ 上。至于 MacGUI 我不是很清楚，但是我认为 GUI 很可能也不能在这么低版本的 macOS 上编译成功。

此外苹果官方通常只对最新的三个大版本的 macOS 提供支持，即使是 macOS 12 也会在一个月以内停止支持。

**Comment by Daydreamer114** [comment]
如果你的版本低到使用的还是 intel 芯片，你可以尝试安装 windows 系统然后使用 windows 版 maa 和 mumu。
