### ISSUE TITLE
生息验算功能无法正常使用

### ISSUE THREAD

**Issue by lanzhendong** [MaaAssistantArknights/MaaAssistantArknights#10505]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在明日方舟生息演算界面启动maa生息演算功能，长时间无任何反应

### Version

UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16905933/asst.log)
[gui.log](https://github.com/user-attachments/files/16905934/gui.log)
[gui.json](https://github.com/user-attachments/files/16905941/gui.json)
问题发生于2024/9/6（刚发生即上传问题）

### 配置信息

win11
mumu12最新版本
无截图增强模式
1600*900（DPI 240）
无GPU加速

**Comment by ABA2396** [comment]
![Screenshot_2024-09-06-17-52-49-789_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/29b2f0f4-3b06-449b-b354-00ea0d0587ef)

你选的是制造刷点数

**Comment by lanzhendong** [comment]
> ![Screenshot_2024-09-06-17-52-49-789_com.android.chrome-edit.jpg](https://private-user-images.githubusercontent.com/99072975/365121360-29b2f0f4-3b06-449b-b354-00ea0d0587ef.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTY4MTAsIm5iZiI6MTcyNTYxNjUxMCwicGF0aCI6Ii85OTA3Mjk3NS8zNjUxMjEzNjAtMjliMmYwZjQtM2IwNi00NDliLWIzNTQtMDBlYTBkMDU4N2VmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA5NTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlODIwYWIyZWUzOTNhMzY1ZWU1YzhkYTIyZTE4NTEzNjMwZmQ5MDM1NzEzNDdhNjEwOTA2Y2E2YjdjNTkzZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y3EVSveMzaBjHdFcjpTAkK3TG3-Ee69PeocEcF0ubHA)
> 
> 你选的是制造刷点数

添麻烦了，默认是这个没有修改
