### ISSUE TITLE
MAA挂机肉鸽，ew三技能秒开秒关

### ISSUE THREAD

**Issue by LorenYue** [MaaAssistantArknights/MaaAssistantArknights#10503]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

![技能开启](https://github.com/user-attachments/assets/e7f4ee36-f5ee-4ad4-bcd8-6270780f3ef5)
![技能秒关](https://github.com/user-attachments/assets/180b678d-c2ee-4b2f-bf2a-2947b2f73e7c)

### Version

![版本](https://github.com/user-attachments/assets/0fe4fd2d-6d45-473d-98a0-41ecac7ec843)

### 日志和配置文件

[Uploading asst.
[gui.log](https://github.com/user-attachments/files/16905392/gui.log)
log…]()
[gui.json](https://github.com/user-attachments/files/16905396/gui.json)
[2024-09-06 10:46:38.045]前后时间

### 配置信息

Win10 MuMu模拟器12，分辨率1600*900，帧率60
使用默认设置，无法确定是否开启截图增强及GPU

**Comment by ABA2396** [comment]
我又不会算命，你发个
[Uploading asst.
gui.log
log…]()
gui.json
我能看出啥

**Comment by Daydreamer114** [comment]
正确上传文件，确认是否开启截图增强和gpu加速后再 open issue

**Comment by LorenYue** [comment]
[asst.log](https://github.com/user-attachments/files/16906441/asst.log)
[gui.log](https://github.com/user-attachments/files/16906442/gui.log)
[gui.json](https://github.com/user-attachments/files/16906450/gui.json)
截图增强、GPU加速均未启用。
第一次使用论坛并不熟悉，非常抱歉为您带来了困扰，感谢大佬对于MAA的维护和运营。


> 我又不会算命，你发个 上传助手。 gui.log log… gui.json 我能看出啥

**Comment by Daydreamer114** [comment]
正在重新训练模型
