### ISSUE TITLE
萨卡兹肉鸽中，如果事件给了多个思绪，MAA不会点next，会卡住，刚才回来看发现卡了半小时

### ISSUE THREAD

**Issue by yonokoyo** [MaaAssistantArknights/MaaAssistantArknights#10504]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

事件格中MAA选了思绪奖励，思绪简介界面会卡住，不点击next
[2024-09-06 16:27:49.668] <1><> 节点: 诡意行商
[2024-09-06 16:28:24.577] <1><> 事件: 戴冠式
[2024-09-06 16:58:13.822] <1><> 事件: 在故事结束之后
[2024-09-06 16:58:50.114] <1><> 事件: 前瞻

### Version

Resource Version: 泰拉饭
Resource Time: 2024/9/6 01:26:34
UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16905719/asst.log)
[gui.log](https://github.com/user-attachments/files/16905722/gui.log)
[gui.json](https://github.com/user-attachments/files/16905724/gui.json)

### 配置信息

WIN10
 MUMU12截图增强已开启
1280x720 240dpi

**Comment by Daydreamer114** [comment]
你的asst.log中不包含bug发生的时间段，请上传asst.bak.log
