### ISSUE TITLE
自动肉鸽招募和商店购买逻辑优化（高难向，新手向，穷局向）

### ISSUE THREAD

**Issue by shikakihuso** [MaaAssistantArknights/MaaAssistantArknights#10518]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

本人是8月新入坑的萌新，最近开始尝试使用maa打肉鸽，目前发现招募逻辑中对阵容完备度检测的条件较高，主要表现在部分肉鸽刚需某些核才能完成阵容完备度检测，且绝大部分条件下三层一个奶也可以通过但就是完备条件要求两个奶，对新人玩家，穷局情况，稍高难度希望增加条件不太友好，在使用EW助战且精二的情况下尤为明显。另外，商店购买对一些胡局常用藏品（如岩角号、技力藏品、超大幅增伤藏品、蓝门真伤藏品等）购买优先级标准较低（主要为肉鸽开放初期为了适配抄wiki导致的），导致容易漏超绝藏品。

### 有什么好的想法？

目前尝试在阵容完备度检测中放宽对“其他高台”“高台输出”的要求，以提供在低星干员或六星大杯干员的条件下顺利通过前期关卡的可能性，尽量使其尽早过渡到后面开始招募补全阵容的干员。另外对于部分能够提供多种功能的干员（如我个人常用的阿米娅医疗和锡人，目前只改了这两个）赋予key位。
同时，本人还在尝试在临时招募到干员时通过其表现在招募逻辑中给到其相应优先级以扩大阵容适配度。
其他改动：
1.强行增加了阿米娅医疗的优先级，实际上老肉鸽对这种多功能干员也非常欢迎
2.参考艾雅法拉的优先级给玛露希尔定了优先级（没有检查有没有漏的）
3.参考提丰的优先级给莱伊定了优先级（没有检查有没有漏的）
4.参考晓歌的优先级给齐尔查克定了优先级（没有检查在回费等tag里有没有写）
5.老肉鸽增加了锡人的招募逻辑（数值暂时给的和多萝西一样）
6.水月肉鸽忘记提高益达招募优先级导致天天把我1级百嘉招过来

当前测试结果：在N6/N7难度下撑到第三层且成功额外招募一个核的概率大幅提高，之前是第一层就容易暴毙

欢迎各位大佬提出建议
[Mizuki_recruitment.json](https://github.com/user-attachments/files/16914108/Mizuki_recruitment.json)
[Mizuki_shopping.json](https://github.com/user-attachments/files/16914084/Mizuki_shopping.json)

[Phantom_recruitment.json](https://github.com/user-attachments/files/16913804/Phantom_recruitment.json)
[Phantom_shopping.json](https://github.com/user-attachments/files/16914086/Phantom_shopping.json)

[Sakazi_recruitment.json](https://github.com/user-attachments/files/16913806/Sakazi_recruitment.json)
[Sakazi_shopping.json](https://github.com/user-attachments/files/16914087/Sakazi_shopping.json)

[Sami_recruitment.json](https://github.com/user-attachments/files/16913808/Sami_recruitment.json)
[Sami_shopping.json](https://github.com/user-attachments/files/16914089/Sami_shopping.json)

### 其他内容

另外，临时招募未适配招募逻辑的干员较多，这在出现临时招募省希望的机会时容易漏掉一些能用的干员，临时招募+600的优先级在高难下完全不够看（低难有时候也是），建议临时招募中6星干员优先级+900，五星+700（本人实在不知道怎么改）

本issue已提交pr，但是check卡住了，新手不知道什么原因

**Comment by Saratoga-Official** [comment]
先说两个地方吧，阿米娅医疗和马鹿应该都不行的，阿米娅是maa区分不了各种职业的阿米娅，马鹿是maa没有适配魔力机制

**Comment by shikakihuso** [comment]
阿米娅医疗实测可以在不区分职业的前提下抓
玛露希尔先给她优先级抓了，如果是满练基本可以不管魔力开二技能挂机



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月7日(周六) 中午12:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 自动肉鸽招募和商店购买逻辑优化（高难向，新手向，穷局向） (Issue #10518)




 
先说两个地方吧，阿米娅医疗和马鹿应该都不行的，阿米娅是maa区分不了各种职业的阿米娅，马鹿是maa没有适配魔力机制

**Comment by shikakihuso** [comment]
> 先说几点吧，阿米娅医疗和马鹿应该都不行的，阿米娅是maa区分不了各种职业的阿米娅，马鹿是maa没有适配魔力机制，还有莱伊是maa不会用莱伊，maa用莱伊效果很差

召唤物问题，那次临时招募莱伊之后没用召唤物，直接1和3技能不靠召唤物打的输出
暂时先这样吧，主要是临时招募很多角色不适配会丢失大量希望，应当先让它抓干员再考虑用尽可能简单的方法使用它
