### ISSUE TITLE
日服 基建人员无法填满

### ISSUE THREAD

**Issue by Sakitoks** [MaaAssistantArknights/MaaAssistantArknights#10519]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在使用MAA进行日服游戏代理的过程中，我遇到了三个问题，具体情况如下：

1.在消耗当前所有理智之后，不会使用理智药（已经勾选使用理智药且仓库内有理智药未使用）。
**这个我看到置顶的公告中有这项，但是具体的解决办法没有太看明白，请问能不能和我说一下具体要怎么操作。**
2.战斗结束后不会进行任务列表中的后续任务，只会卡在原地不动。
3.进行基建收菜后，会有大量空余没有填满，哪怕再度选择进行基建任务也不会填满，只能手动进行（此问题在我使用台服和国际服账号游玩的时候同样会出现），此外使用国际服账号游玩的时候无人机不会使用，但是日服和台服的账号则会自动使用给选定的贸易站。
4.**此选项乃建议项，与问题无关。**希望获取信物及自动购物-高级选项-优先购买/黑名单可以提供下拉列表，记录曾经写过的物品。因为我本人有四个账号，每个账号的优先购买和黑名单不同，尤其是日服、台服、国际服识别的字不同，每次需要用相对应的语言重新填写。

以上是我遇到的问题和建议，请查收。

附件：
1.选择了后续任务但是在做完战斗后只会卡在原地不动
![image](https://github.com/user-attachments/assets/df9092d2-4855-4153-9bc6-92f12124871f)
2.仓库内有理智药但是不会自动使用（在勾选使用理智药的情况下）看到置顶有这条问题，请问我该怎么操作，没有看明白解释的内容。
![image](https://github.com/user-attachments/assets/b913c48d-7a17-4be7-ae03-13224f548fc0)
3.开始基建工作并完成之后会有大量房间空余
![image](https://github.com/user-attachments/assets/d9f05e0f-b9d8-45a7-b318-5366fc38789b)
![image](https://github.com/user-attachments/assets/bf8734c9-3a9f-4210-a9cb-134c00bb38b5)
![image](https://github.com/user-attachments/assets/ee988873-5768-4b40-a9f0-df01ff8b612d)

### Version

UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16914148/asst.log)
[gui.log](https://github.com/user-attachments/files/16914149/gui.log)
[gui.json](https://github.com/user-attachments/files/16914150/gui.json)

### 配置信息

1.资源版本
Resource Version: OP:LA
Resource Time: 2024/9/5 16:42:23
2.模拟器品牌
雷电模拟器9
3.电脑系统版本
Windows10

**Comment by Manicsteiner** [comment]
1. 当前日服使用理智药界面缺少蓝色遮罩，无法识别理智药上的数字，只能等悠星修这个（可能可以通过在`NumberOcrReplace`里添加ocrReplace规则`["^t$", "1"]`解决使用一个理智药时的问题，但可能造成更多难以预测的问题）
2. 彩六联动界面的左上角返回按钮不是通用的按钮，大概算是联动彩蛋，MAA不能识别
3. 4. 不清楚，等别人解释

**Comment by status102** [comment]
4. 建议使用多个配置用对不同服，每个服填对应的购物

**Comment by Sakitoks** [comment]
> 1. 当前日服使用理智药界面缺少蓝色遮罩，无法识别理智药上的数字，只能等悠星修这个（可能可以通过在`NumberOcrReplace`里添加ocrReplace规则`["^t$", "1"]`解决使用一个理智药时的问题，但可能造成更多难以预测的问题）
> 2. 彩六联动界面的左上角返回按钮不是通用的按钮，大概算是联动彩蛋，MAA不能识别
> 3. 4. 不清楚，等别人解释

好的，前两项我明白了，那么只能先等活动结束和yostar什么时候修了orz

**Comment by Sakitoks** [comment]
> 4. 建议使用多个配置用对不同服，每个服填对应的购物

请问这种操作是使用不同的模拟器还是能怎么在MAA保存下来曾经写的方案？

**Comment by ABA2396** [comment]
新增配置的时候会复制当前的配置

**Comment by ABA2396** [comment]
搞不懂的话直接复制一份maa的文件夹也行）

**Comment by status102** [comment]
> > 4. 建议使用多个配置用对不同服，每个服填对应的购物
> 
> 请问这种操作是使用不同的模拟器还是能怎么在MAA保存下来曾经写的方案？

约等于复制一份MAA，只是不能同时跑

**Comment by ABA2396** [comment]
@status102 能不能临时取消掉日服的理智药数量检查？反正现在没有理智小样，不是连战也不会吃多个，直接 `.* -> 1` 行不行
可以给日服单独加个说明
cc @Manicsteiner

**Comment by status102** [comment]
> @status102 能不能临时取消掉日服的理智药数量检查？反正现在没有理智小样，不是连战也不会吃多个，直接 `.* -> 1` 行不行 可以给日服单独加个说明 cc @Manicsteiner

我给拉到255, 255了，日服是没人反馈还是官方懒得修，搞不懂。现在没遮罩别说ocr，人眼都看不清

**Comment by Manicsteiner** [comment]
![图片](https://github.com/user-attachments/assets/deb802ec-b3c3-4d03-b31a-cc8c35c40178)
反馈过了但还是没人管

**Comment by Manicsteiner** [comment]
![图片](https://github.com/user-attachments/assets/3c6b7969-0583-4271-86f0-6434831aaa93)
![图片](https://github.com/user-attachments/assets/cba08e49-3f8d-4ffb-8a57-0a25360a8a80)
加到[255, 255]会认不出日期，[250, 255]应该刚好

![图片](https://github.com/user-attachments/assets/9935ba66-2eb7-4e67-b1c2-4eb6f782cc78)
能不能从亮度模型改成RGB模型，看起来可能会好一点

**Comment by status102** [comment]
255是数量，日期没动
