### ISSUE TITLE
“滋味”界面主题，公开招募有数字气泡时，Mac上的MAA无法识别

### ISSUE THREAD

**Issue by Emery319** [MaaAssistantArknights/MaaAssistantArknights#10513]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

![a](https://github.com/user-attachments/assets/f278a16f-3f5c-425d-b6ac-6fffb36e0a72)

如题，有气泡就无法识别

### 有什么好的想法？

![RecruitDelicious-2](https://github.com/user-attachments/assets/19161557-40e6-441b-a013-b15cff8dc5f8)
![RecruitDelicious](https://github.com/user-attachments/assets/67ab10d1-35da-4204-a614-bb87ff19e260)

看了更新的资源文件，似乎是截图的遮挡区域太小了，没挡住气泡，改大一点能解决

### 其他内容

不清楚是不是Mac版MAA独有的问题，懒得找log就当建议发了

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/60338bea-4f9b-40a5-9794-07602d49f427)
![image](https://github.com/user-attachments/assets/8c6f4084-cee3-403c-b00f-e4a108912c59)
我试了下倒是没问题，但得分确实偏低，是应该改下
