### ISSUE TITLE
Combat -> 'unlimited use of expiring sanity potion' advanced option not working?

### ISSUE THREAD

**Issue by dragonheart107** [MaaAssistantArknights/MaaAssistantArknights#10516]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I am using the latest version of the current update and have reviewed both the updates released so far and the unreleased changes in the Pull Requests, there is no mention of the bug being fixed.
- [X] I have reviewed the Pinned issue (Announcements), Open issues, and Closed issues to ensure that my issue has not been mentioned.

### Description

initial situation:
not enough sanity to run combat task, whether 'use sanity potion' general option is selected, does not seem to matter for this

MAA start:
tries to start mission-> sanity add pop-up -> deselect preselected -> error -> stops task

### Version

Resource Version: Operation Lucent Arrowhead
Resource Time: 9/5/2024 19:26:34
UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 9/5/2024 19:35:35

### Log and config files

[asstlog.zip](https://github.com/user-attachments/files/16913742/asstlog.zip)

bug loop around 2024-09-06 13:05:42.150

[gui.log](https://github.com/user-attachments/files/16913743/gui.log)

[gui.json](https://github.com/user-attachments/files/16913744/gui.json)

### Configuration information

Windows 11, Mumu 12 global V3.8.18 (2845), 1920 x1080 (DPI 280), 60fps
no MuMu screenshot enhancement
GPU accelerated inference enabled: AMD Radeon RX 7900 XTX

**Comment by status102** [comment]
MAA仅会使用48小时内到期的理智药，ocr显示该药到期时间为不足3天（即游戏内显示为2day）故不会使用该药

cc @Constrat Shall we optimize the text, it's `use expiring` in EN and `use 48` in zh-cn, zh-tw, jp, and even ko

**Comment by Constrat** [comment]
I mean... `Use expiring` is pretty straightforward and understandable XD.
I guess to keep consistency we can change it like all the others: `use potions that expire in 48 hours` something like this

**Comment by status102** [comment]
maybe `use expiring(48h)`? or just do what you like

**Comment by Constrat** [comment]
Let me open VS and start thinking :)

**Comment by dragonheart107** [comment]
i mean the thing is, it was expiring, it just didn't take it

**Comment by dragonheart107** [comment]
I think it is an easy fix if you just add a hovering field on that option saying expiring in 48 h and maybe that ingame it may show already as 2 days expiring but is in fact between 2d>x>3d

**Comment by status102** [comment]
现在MAA只把48小时内当做临过期，而显示2day的是48~72小时的药，所以不会作为临期药品使用

**Comment by Constrat** [comment]
x days = more than 48 hours (49 50 51 hours etc)
xx hours = less or equal than 48 hours.

Just like when an event is ending. The it ends it will say 20 hours left, 10 hours left, 1 hour left. But the day before it will say 1 day left (meaning more than 1 day,  less than 2 days)
