### ISSUE TITLE
完成后退出明日方舟失效

### ISSUE THREAD

**Issue by qqqxppp** [MaaAssistantArknights/MaaAssistantArknights#10524]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

”完成后“退出明日方舟失效，其他“完成后”功能正常

### Version

Resource Version: 泰拉饭
UI Version: v5.2.0
Core Version: v5.6.0

### 日志和配置文件

[Uploading gui.log…]()
[Uploading gui.json…]()

### 配置信息

win11
mumu12
2560x1440
dpi 360
60帧
未开启截图增强
开启gpu加速 3050Ti

**Comment by Rbqwow** [comment]
> UI Version: v5.2.0
> Core Version: v5.6.0

你的界面和核心版本不一样 先重装一下 MAA
