### ISSUE TITLE
生稀盐酸点数没刷满，报错已完成

### ISSUE THREAD

**Issue by Daoketa** [MaaAssistantArknights/MaaAssistantArknights#10522]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

，生稀盐酸点数没刷满就完成任务

### Version

UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16914423/asst.log)
[gui.log](https://github.com/user-attachments/files/16914424/gui.log)
[gui.json](https://github.com/user-attachments/files/16914426/gui.json)

### 配置信息

Windows11，版本号23H2，操作系统版本22631.4037
mumu模拟器4.0.5.3284，分辨率1080p，DPI280，帧率240
截图增强已开启，GPU加速推理已开启
GPU型号：RTX 4070 laptop

### 截图或录屏

![image](https://github.com/user-attachments/assets/611dfb25-88d5-40f2-9257-5676fb3ad9da)

**Comment by HYY1116** [comment]
有按照自动生息演算的说明一步一步进行吗

**Comment by Alan-Charred** [comment]
您好，我看了一下，应该是在某一步点击太快，没能成功进入关卡，又想要点击右上角退出关卡，所以卡住了。
可以请您尝试关闭 mumu 截图增强模式，再试试看是否会频繁卡住吗？

**Comment by Daoketa** [comment]
不行呀老师，已尝试关闭mumu截图增强，还是老样子，直接回生稀盐酸主题界面了



---原始邮件---
发件人: "Weiyou ***@***.***&gt;
发送时间: 2024年9月7日(周六) 晚上6:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 生稀盐酸点数没刷满，报错已完成 (Issue #10522)




 
您好，我看了一下，应该是在某一步点击太快，没能成功进入关卡，又想要点击右上角退出关卡，所以卡住了。
 可以请您尝试关闭 mumu 截图增强模式，再试试看是否会频繁卡住吗？

**Comment by Alan-Charred** [comment]
> 不行呀老师，已尝试关闭mumu截图增强，还是老样子，直接回生稀盐酸主题界面了
>> 您好，我看了一下，应该是在某一步点击太快，没能成功进入关卡，又想要点击右上角退出关卡，所以卡住了。 可以请您尝试关闭 mumu 截图增强模式，再试试看是否会频繁卡住吗？

回到生息演算主题界面是指？我可以确认下流程吗？
您应该是在生息演算战斗编队清空的情况下，删除存档，然后在生息演算主题界面点开 MAA 的任务。
之后您是在哪一步卡住的呢？如果稳定触发，可以给我一个录屏 + asst.log + gui.log 吗？感谢。

**Comment by PikaChen123** [comment]
[gui.log](https://github.com/user-attachments/files/16922763/gui.log)
[asst.log](https://github.com/user-attachments/files/16922764/asst.log)
你好我也是更新之后就用不了生稀盐酸了 试了好几次了 一启动就说完成了或者走了一个回合就说完成了。更新之前是可以挂机的， 设置也是确认编队清空删除存档的

**Comment by PikaChen123** [comment]
这是录屏

**Comment by PikaChen123** [comment]
https://github.com/user-attachments/assets/34a6efdc-3d99-442a-9348-99c43a18d7f5

这是录屏 请帮忙看看

**Comment by Alan-Charred** [comment]
<img width="357" alt="image" src="https://github.com/user-attachments/assets/d89dbf0d-f434-4b39-bb07-8fdeaf35e0bf">

@PikaChen123 您好，您分享的日志文件，最后一次卡死是没有检测到上图中的文字所导致。我不清楚原因，根据您的截图，位置应该是正确的。

而先前的两次卡死，不知是没有成功退出区域还是别的什么原因，未能检测到右下角的图标。
您有开启 mumu 截图增强模式吗？可以尝试关闭增强模式后再试试吗？

**Comment by HoshinoAyako** [comment]
或许可以试试关闭GPU加速推理。

**Comment by Daoketa** [comment]
没用的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月9日(周一) 上午10:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 生稀盐酸点数没刷满，报错已完成 (Issue #10522)




 
或许可以试试关闭GPU加速推理。

**Comment by Daoketa** [comment]
都有尝试过，包括GPU加速



---原始邮件---
发件人: "Weiyou ***@***.***&gt;
发送时间: 2024年9月9日(周一) 上午8:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 生稀盐酸点数没刷满，报错已完成 (Issue #10522)




 image.png (view on web) 
@PikaChen123 您好，您分享的日志文件，最后一次卡死是没有检测到上图中的文字所导致。我不清楚原因，根据您的截图，位置应该是正确的。
 
而先前的两次卡死，不知是没有成功退出区域还是别的什么原因，未能检测到右下角的图标。
 您有开启 mumu 截图增强模式吗？可以尝试关闭增强模式后再试试吗？

**Comment by PikaChen123** [comment]
你好 我关闭了截图增强模式 第一次刷了1000积分mumu掉线了 第二次开了20分钟了目前还在正常运行

**Comment by Alan-Charred** [comment]
@PikaChen123
好嘞，那先用着。对于未能检测到文字，我目前没有太多办法，一个字都没有识别到，识别位置也是对的。如果之后又一直发生，请尝试调整模拟器 DPI，看看会不会让画面更清晰一些能解决问题。我自己的配置如下。

<img width="461" alt="image" src="https://github.com/user-attachments/assets/3e27d421-7537-48e2-95e1-d95afac6c899">
<img width="454" alt="image" src="https://github.com/user-attachments/assets/14ed30a5-36bd-4658-acb4-32c1f746bfa1">

总之 Mumu 模拟器这类会在您输入自定义分辨率时自动调整 DPI，用它的默认数值就好。

关于在进入关卡后未能成功离开关卡而卡住的问题，我这边加了一下回滚机制以增强容错，将在下个版本推出。

**Comment by Alan-Charred** [comment]
修复补丁已经推出一段时间了，我现在关闭这个 Issue。
如果还遇到同样的问题，欢迎 reopen 并分享最新的日志文件与截图（有录屏更好）。
如果遇到新的问题，还请新开一个 Issue，我们会尽快处理～
