### ISSUE TITLE
生息任务出错

### ISSUE THREAD

**Issue by cobe-bryant** [MaaAssistantArknights/MaaAssistantArknights#10528]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

![出错](https://github.com/user-attachments/assets/643ec98b-b256-4f9b-bf8a-17ef4760a13a)
自动肉鸽没有问题，自动生息演算每次报错

### Version

Resource Version: 泰拉饭
Resource Time: 2024/9/6 01:26:34
UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16917078/asst.log)
[gui.log](https://github.com/user-attachments/files/16917079/gui.log)
2024/9/7   16:13:13生息演算任务出错
[gui.json](https://github.com/user-attachments/files/16917097/gui.json)

### 配置信息

Windows 10 专业版
MuMu 12，已开启截图增强
1600×900（DPI 240）60帧
无GPU加速推理

### 截图或录屏

![出错](https://github.com/user-attachments/assets/d183d61f-4207-43ef-bf59-f497d2fbc4ea)

### 还有别的吗？

无

**Comment by ABA2396** [comment]
你看设置了吗？

**Comment by cobe-bryant** [comment]
> 你还在看设置吗？

你说的具体是哪个设置，之前是没有问题的，是从昨天手动更新之后maa自动生息就一直报错，有时候1分钟报错，有时候10分钟报错

**Comment by Alan-Charred** [comment]
您好，我看了一下 asst.log 文件，似乎是在识别到区块节点后未能成功点击，导致卡死。
我会尽快在这块儿补充一点判定以增加容错。
可以请您试一下关闭 mumu 截图增强模式后，是否还会频繁出错吗？

**Comment by cobe-bryant** [comment]
> 您好，我看了一下 asst.log 文件，似乎是在识别到区块节点后未能成功点击，导致卡死。 我会尽快在这块儿补充一点判定以增加容错。 可以请您试一下关闭 mumu 截图增强模式后，是否还会频繁出错吗？

关了截图增强，到目前为止30分钟没有报错，应该没有问题了

**Comment by Alan-Charred** [comment]
> > 您好，我看了一下 asst.log 文件，似乎是在识别到区块节点后未能成功点击，导致卡死。 我会尽快在这块儿补充一点判定以增加容错。 可以请您试一下关闭 mumu 截图增强模式后，是否还会频繁出错吗？
> 
> 关了截图增强，到目前为止30分钟没有报错，应该没有问题了

好好好，我这边已尝试再加了一个检查判定，以增加容错。将会在下个版本推出。

**Comment by cobe-bryant** [comment]
> > > 您好，我看了一下 asst.log 文件，似乎是在识别到区块节点后未能成功点击，导致卡死。 我会尽快在这块儿补充一点判定以增加容错。 可以请您试一下关闭 mumu 截图增强模式后，是否还会频繁出错吗？
> > 
> > 
> > 关了截图增强，到目前为止30分钟没有报错，应该没有问题了
> 
> 好好好，我这边已尝试再加了一个检查判定，以增加容错。将会在下个版本推出。

好的👌，谢谢啦
