### ISSUE TITLE
自动关机无法取消

### ISSUE THREAD

**Issue by 3221775697** [MaaAssistantArknights/MaaAssistantArknights#10520]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

版本更新后升级了自动关系的提醒，变成圆圈倒计时了，但我发现明明我点击了倒计时中间偏下的关闭，还是自动关机了，

### Version

UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/16914212/gui.log)
[asst.log](https://github.com/user-attachmen
[gui.json](https://github.com/user-attachments/files/16914214/gui.json)
ts/files/16914213/asst.log)

### 配置信息

win11
mumu7.0.5.0 1080P
增强兼容模式

**Comment by 3221775697** [comment]
补充，点击关闭自动关机后，关闭MAA，百分百复现这个问题。

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/69d9b718-d943-4373-9b1f-cd9449f8058d)
没复现出来，现在这个逻辑是定时 70s 后关机，但 60s 的时候会检查有没有取消
cc @moomiji

**Comment by 3221775697** [comment]
<img width="1237" alt="屏幕截图 2024-09-08 133156" src="https://github.com/user-attachments/assets/4b79794e-6673-48bc-a801-c0008057d7fa">
弹出这个画面的时候，点击取消，然后关闭MAA和模拟器，成功复现。另外我没有出现这个注销被取消的通知提醒。我开了通知免打扰。

**Comment by 3221775697** [comment]
打错字了，成功复现，电脑依旧会自动关机。

**Comment by 3221775697** [comment]
复现

**Comment by 3221775697** [comment]
不关闭MAA则不会继续自动关机

**Comment by Decwar** [comment]
出现同样情况，点击了windows弹窗关机提醒的取消，并点击了MAA转圈关机的取消后（不记得在这之后是否关闭MAA），仍然关机

**Comment by ABA2396** [comment]
加了点修改和日志，用这个版本跑跑看，再发下 gui.log 的日志
https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/10757909645/artifacts/1905622606

**Comment by 3221775697** [comment]
不是哥们，我用了你发的这个提示都没有直接给我关机了
[gui.log](https://github.com/user-attachments/files/16925490/gui.log)

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/959a3ed1-4daf-4ecf-a24e-8291680d2deb)
![image](https://github.com/user-attachments/assets/c7e3ffd6-ad2f-4bbe-856b-d9e226c53b4a)
有点看不懂了，照理来说这两个日志怎么也会输出一条，但这个什么都没有一分钟后就关机了
@moomiji

**Comment by ABA2396** [comment]
> 不是哥们，我用了你发的这个提示都没有直接给我关机了

是指没有弹窗等一分钟之后就关机了吗

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/9021c590-032b-49b5-a641-d8566f9d1be3)
![image](https://github.com/user-attachments/assets/3e9e7da0-2d24-43e1-8b73-225595686da6)
不对，你这日志里有两个，一个取消了一个没取消，你说的到底是什么时候的

**Comment by ABA2396** [comment]
看样子是MessageBoxHelper.Show会有个弹窗出来，不管ui有没有显示。而这个倒计时是随窗口走的，ui最小化的时候不会主动弹出，加了个提示前显示窗口
