### ISSUE TITLE
进行“开始唤醒”任务导致游戏卡死

### ISSUE THREAD

**Issue by kiana-quan** [MaaAssistantArknights/MaaAssistantArknights#10525]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

任务清单中选中“开始唤醒”选项，会导致游戏直接卡死无响应，需要关闭游戏重新打开才可以恢复，如果不选择开始唤醒进程直接进行其他任务则没有问题可以完成。

### Version

Resource Version: 泰拉饭
Resource Time: 2024/9/6 01:26:34
UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16915170/asst.log)
[gui.log](https://github.com/user-attachments/files/16915171/gui.log)
[gui.json](https://github.com/user-attachments/files/16915172/gui.json)

### 配置信息

操作系统：Windows 10 22H2
模拟器：MuMu12  V4.0.2（3233）
1600x900（DPI 240） 已开启MuMu增强截图

**Comment by ABA2396** [comment]
我不觉得是开始唤醒的问题，只是单纯的游戏卡死了

**Comment by kiana-quan** [comment]
> 我不觉得是开始唤醒的问题，只是单纯的游戏卡死了

但是我手动进入到游戏的主界面之后再点击开始唤醒一样会卡死，如果是没有打开游戏的情况下运行开始唤醒的话就会在打开游戏之后鹰角网络logo这里直接卡死

**Comment by ABA2396** [comment]
![Screenshot_2024-09-07-17-14-06-641_com.carriez.flutter_hbb.jpg](https://github.com/user-attachments/assets/52e7c615-ace2-482c-b47b-4f408fd40c96)

啥玩意，你家方舟里面有圣斗士啊？自己开了截图增强还不看设置，能怪谁

**Comment by kiana-quan** [comment]
[asst.log](https://github.com/user-attachments/files/16917282/asst.log)
我把增强截图关了，还是一样卡死啊

**Comment by Alan-Charred** [comment]
您好，我看了一下您最新的 asst.log 文件，似乎是卡在了下面的这个画面。

![551aa5c627ea05d785602765f6a71711](https://github.com/user-attachments/assets/8ce1f37d-0833-48cf-b11b-09de63f9a64f)

已成功识别画面并进行了点击操作。但画面没有改变，的确是游戏卡死了的样子。
请允许我再次确认一下，这个时候就算您亲自点击屏幕也不会有用，只能重启游戏或模拟器对吧？
MAA 应该不会导致游戏卡死才对。可以请您尝试复现这个情况，并上传一下录屏（配上对应的 asst.log + gui.log）吗？

**Comment by kiana-quan** [comment]
[asst.log](https://github.com/user-attachments/files/16917657/asst.log)
[gui.log](https://github.com/user-attachments/files/16917658/gui.log)
[gui.json](https://github.com/user-attachments/files/16917660/gui.json)

https://github.com/user-attachments/assets/4acfb583-b0a0-41e9-b59a-4e0f316e5768

卡死之后是怎么点击也没有反应了，需要吧游戏关闭重新打开才能恢复正常。如果跳过唤醒步骤直接从下一个任务开始就是正常的

**Comment by Alan-Charred** [comment]
> Warning
> 
> 存在未确认的链接，请谨慎访问。 There are unconfirmed links, please visit with caution.
> 
> [asst.log](https://github.com/user-attachments/files/16917657/asst.log) [gui.log](https://github.com/user-attachments/files/16917658/gui.log) [gui.json](https://github.com/user-attachments/files/16917660/gui.json)
> 
>  2024-09-07.18-50-13.mp4 
> 卡死之后是怎么点击也没有反应了，需要吧游戏关闭重新打开才能恢复正常。如果跳过唤醒步骤直接从下一个任务开始就是正常的

真的完全卡住了，连下面的按钮都不闪了。我去摇人来看看。
