### ISSUE TITLE
在关卡选择中添加大小芯片关卡

### ISSUE THREAD

**Issue by blenkor** [MaaAssistantArknights/MaaAssistantArknights#1052]
可以选择刷大芯片还是小芯片，最好还能根据日期判断当日是否可刷，不可刷的话弹出通知并跳过刷理智任务

**Comment by ABA2396** [comment]
昨天就写了（）还没发版罢了

**Comment by ABA2396** [comment]
不过没有判断日期，但是现在刷理智关卡错了会跳过，就是等的时间比较长（）

**Comment by MistEO** [comment]
> 不过没有判断日期，但是现在刷理智关卡错了会跳过，就是等的时间比较长（）

我写了，自动隐藏当日不可用关卡

**Comment by blenkor** [comment]
> 我刚写了，自动隐藏当日不可用关卡 [194f5bb](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/194f5bbdddaa61997086100402e969c6e5352c57)

隐藏不太好吧，例如如果我想把今日剩余体力留到明天4点来刷明天才开放的关卡，不就不行了嘛，建议改为增加一个今日不可刷的提示就好了
