### ISSUE TITLE
日服挂不了生息演算

### ISSUE THREAD

**Issue by jiongshiqi** [MaaAssistantArknights/MaaAssistantArknights#10526]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

日服挂生息演算，进入第一幕后在剧情那里就不动了，然后报任务出错。国服可以正常挂，只有日服不行

### Version

UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16910399/asst.log)
[gui.log](https://github.com/user-attachments/files/16910400/gui.log)

### 配置信息

操作系统：win11
模拟器品牌：mumu12，分辨率：1920*1080，DPI280，帧率60，截图增强没有开启

### 截图或录屏

![QQ20240906-235016](https://github.com/user-attachments/assets/e78dd373-59e9-453c-9ddd-f1244f416756)

**Comment by Daydreamer114** [comment]
duplicate of #10497
