### ISSUE TITLE
[日服]生息演算开局不久就任务出错

### ISSUE THREAD

**Issue by Crimson-Veluriyam** [MaaAssistantArknights/MaaAssistantArknights#10535]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

生息演算开局不久就任务出错
1.已清空编队
2.删除存档后重新开局

### Version

UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16918514/asst.log)
[gui.log](https://github.com/user-attachments/files/16918515/gui.log)
[gui.json](https://github.com/user-attachments/files/16918517/gui.json)

### 配置信息

WIN10，雷电模拟器v9.0.69，1600*900，dpi240

### 截图或录屏

![圖片_2024-09-07_214553026](https://github.com/user-attachments/assets/93399f41-40f9-4609-af2a-81b899b8ae01)
![圖片_2024-09-07_215802271](https://github.com/user-attachments/assets/0b547a7a-dbfa-419b-82c2-f564bd5bd48e)

### 还有别的吗？

不时会卡在这个画面

**Comment by Manicsteiner** [comment]
asst.log 为空，请上传 asst.bak.log

**Comment by Alan-Charred** [comment]
您好，这个卡住的画面位置看起来很奇怪。一般来说您的画面应当只会在以下两个位置卡住才对。
地图回正之前
![screenshot_20240908_001720](https://github.com/user-attachments/assets/ac1840c1-57a6-41d4-9d1a-c30e61cda032)
地图回正之后
![screenshot_20240908_001832](https://github.com/user-attachments/assets/6dc32ec2-21f2-46d5-a363-e4e71f63becc)
在这期间，maa没有滑动操作，不应该会使画面偏移到您截图的位置。
如果您经常遇到这个问题，可以请您分享一个录屏+对应的 asst.log 文件吗？感谢。

**Comment by Crimson-Veluriyam** [comment]
[asst.bak.log](https://github.com/user-attachments/files/16920155/asst.bak.log)

**Comment by Manicsteiner** [comment]
昨天的日志已经被覆盖了，当前日志中有三次重试二十次的记录，都是卡在 聚羽之地/羽獣の集う地 识别成功并点击之后
根据日志来说，唯一找到的规律是点击位置稍稍偏左时会失败，无法识别下一步的“行动开始”

Fail
Click with scaled coordinates (178, 376) 1.25
minitouch click: (222, 470)
Click with scaled coordinates (180, 377) 1.25
minitouch click: (225, 471)
Click with scaled coordinates (187, 371) 1.25
minitouch click: (233, 463)

Success
minitouch click: (237, 466)
minitouch click: (250, 465)
minitouch click: (238, 470)
minitouch click: (247, 477)
minitouch click: (240, 472)
minitouch click: (237, 468)
minitouch click: (243, 466)
minitouch click: (243, 472)
minitouch click: (247, 471)
minitouch click: (243, 463)

**Comment by Alan-Charred** [comment]
@Crimson-Veluriyam 
您好，感谢反馈。根据日志和截图，是没有成功点击区块节点，无法在右下角识别到 <开始行动> 按钮导致卡死。这个问题我们已经修好了，将在下个版本发布。

话说，您分享的截图好像不是 16:9，可以请您确认下模拟器的分辨率为 16:9 吗？（可能是我多虑了，多半是因为右边的控制栏）

@Manicsteiner  感谢帮助！

**Comment by Crimson-Veluriyam** [comment]
![圖片_2024-09-08_163913884](https://github.com/user-attachments/assets/1d6bdc3c-81f1-4e5b-aedf-925655fa203f)
