### ISSUE TITLE
生息演算荧光棒刷点数任务出错

### ISSUE THREAD

**Issue by yuanlemon** [MaaAssistantArknights/MaaAssistantArknights#10539]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

运行生息演算，制造完成荧光棒，进入下一天后就出现任务出错了。

### Version

Resource Version: 泰拉饭
UI Version: v5.6.0
Core Version: v5.6.0
Resource Time: 2024/9/6 01:26:34
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/16918694/gui.log)
[asst.log](https://github.com/user-attachments/files/16918696/asst.log)
[gui.json](https://github.com/user-attachments/files/16918697/gui.json)

### 配置信息

Windows 10 专业版
版本号	22H2
操作系统内部版本	19045.4780
mumu模拟器12
2560*1440 DPI 360 60帧
未开启截图增强
开启GPU加速推理 AMD RX 6600 XT

### 截图或录屏

https://github.com/user-attachments/assets/05837e62-97ec-4461-9230-2bcafd4b27dc

<img width="1430" alt="微信图片_20240907224203" src="https://github.com/user-attachments/assets/9190b3e9-6c98-439e-827a-615448953ae5">

**Comment by Alan-Charred** [comment]
您好，根据 asst.log，分析是 MAA 检测到了确认按钮，过早进行了点击，未能生效，导致卡死。
之前我已经通过加 preDelay=500 来尝试修复这个问题。
看来还是有问题。我会在这里加一个回滚机制来提高容错率。
请问这个情况出现得频繁吗？

**Comment by yuanlemon** [comment]
我这是每次都会出现

**Comment by Alan-Charred** [comment]
> 我这是每次都会出现

了解了，我明天会尝试复现一下，并看看还未发布的修复后的版本是否已解决了这个问题。感谢反馈。

**Comment by yuanlemon** [comment]
> > 我这是每次都会出现
> 
> 了解了，我明天会尝试复现一下，并看看还未发布的修复后的版本是否已解决了这个问题。感谢反馈。

好的，谢谢。

**Comment by Alan-Charred** [comment]
您好，我未能成功复现您说的情况。
等 #10464 合进 dev 后我会给您发一个测试用客户端，您如果方便的话，届时再请试试。

**Comment by yuanlemon** [comment]
> 您好，我未能成功复现您说的情况。 等 #10464 合进 dev 后我会给您发一个测试用客户端，您如果方便的话，届时再请试试。

好的

**Comment by Alan-Charred** [comment]
试试这个 [MAA-win-x64](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/10758958656/artifacts/1905821260)

**Comment by Alan-Charred** [comment]
等用户尝试新的测试客户端后，确认 bug 被修复后再关。

**Comment by yuanlemon** [comment]
> 试试这个 [MAA-win-x64](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/10758958656/artifacts/1905821260)


https://github.com/user-attachments/assets/4bc7577f-35f2-426d-8a47-fee8ef5e9167

这个选不到荧光棒一直下滑

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/10464/files#diff-e4bbe100aeda09b805293411f77994bead0c0bdae1d07644c3bd5abd9fe3d5abR12089
草 额外滑动是垂直方向的，这玩意不能这么用，原来我第三个参数加的那个就是为了消除末端速度的
@Alan-Charred

**Comment by Alan-Charred** [comment]
@yuanlemon 修复用 PR 发上去了，等之后再给您一版。
在这之前您可以尝试，用下面这个文件替换一下 resource/tasks.json 文件后，重启 MAA 再试一次。

[tasks.json](https://github.com/user-attachments/files/16926548/tasks.json)

**Comment by Alan-Charred** [comment]
@ABA2396 我白天的时候尝试了一下，原来不同分辨率下滑动效果会有很大差异。我在 720p 下测试无误的滑动参数，1080p 下就全乱了。怀疑是因为不同分辨率下滑动同样的相对距离后，末端速度不一致。🤔️ 还是得相信学姐的智慧，在最新的 PR 里改好了。

**Comment by yuanlemon** [comment]
> @yuanlemon 修复用 PR 发上去了，等之后再给您一版。 在这之前您可以尝试，用下面这个文件替换一下 resource/tasks.json 文件后，重启 MAA 再试一次。
> 
> [tasks.json](https://github.com/user-attachments/files/16926548/tasks.json)

替换了这个可以用了，不过开了MuM截图增强模式还是会在进入下一天卡住。

**Comment by Alan-Charred** [comment]
> > @yuanlemon 修复用 PR 发上去了，等之后再给您一版。 在这之前您可以尝试，用下面这个文件替换一下 resource/tasks.json 文件后，重启 MAA 再试一次。
> 
> > 
> 
> > [tasks.json](https://github.com/user-attachments/files/16926548/tasks.json)
> 
> 
> 
> 替换了这个可以用了，不过开了MuM截图增强模式还是会在进入下一天卡住。

您好，感谢帮忙测试！我本人没有Mumu截图增强模式的使用环境，您可以提供一个卡住的 asst.log文件吗？我看看是哪个任务卡住了，再加强一下。

**Comment by yuanlemon** [comment]
https://github.com/user-attachments/assets/854a5373-9687-4d0e-b5cc-b7123e566e59

[asst.log](https://github.com/user-attachments/files/16935271/asst.log)
在2:51分吧

**Comment by Alan-Charred** [comment]
@yuanlemon 看了一下，是右上角没有成功点击到下一天的图标所致。我现在加了一个回滚机制。您试试这个：[tasks.json](https://github.com/user-attachments/files/16940194/tasks.json)

非常感谢帮忙测试！

**Comment by yuanlemon** [comment]
> @yuanlemon 看了一下，是右上角没有成功点击到下一天的图标所致。我现在加了一个回滚机制。您试试这个：[tasks.json](https://github.com/user-attachments/files/16940194/tasks.json)
> 
> 非常感谢帮忙测试！

这个可以正常用了，谢谢。

**Comment by yuanlemon** [comment]
> > > @yuanlemon 看了一下，是右上角没有成功点击到下一天的图标所致。我现在加了一个回滚机制。您试试这个：[tasks.json](https://github.com/user-attachments/files/16940194/tasks.json)
> > > 非常感谢帮忙测试！
> > 
> > 
> > 这个可以正常用了，谢谢。
> 
> 有在截图增强模式下尝试吗？非常感谢帮忙测试！这些改动将在下一个版本正式推出。

增强模式也试过了 可以用

**Comment by yuanlemon** [comment]
> > > > > @yuanlemon 看了一下，是右上角没有成功点击到下一天的图标所致。我现在加了一个回滚机制。您试试这个：[tasks.json](https://github.com/user-attachments/files/16940194/tasks.json)
> > > > > 非常感谢帮忙测试！
> > > > 
> > > > 
> > > > 这个可以正常用了，谢谢。
> > > 
> > > 
> > > 有在截图增强模式下尝试吗？非常感谢帮忙测试！这些改动将在下一个版本正式推出。
> > 
> > 
> > 增强模式也试过了 可以用
> 
> 好好好，非常感谢您的帮助！以后如果您使用生息演算功能还遇到问题，我们可以继续这样合作～万分感谢！

好的，谢谢。
