### ISSUE TITLE
生息演算当基地无产出时无法进入下一日

### ISSUE THREAD

**Issue by KasuganoHaruku** [MaaAssistantArknights/MaaAssistantArknights#10542]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

使用生息演算制造荧光棒刷点数时，如游戏内处于荒季导致基地无产出，无法自动点击进入下一日，卡在以下界面；
![image](https://github.com/user-attachments/assets/e53db362-bf6c-4f07-a37a-6d7f48ac3ff7)
手动点击后脚本继续正常运行，如不处理脚本报错并终止。

基地有产出时不出现此问题。

### Version

UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16919058/asst.log)
[gui.log](https://github.com/user-attachments/files/16919059/gui.log)
[gui.json](https://github.com/user-attachments/files/16919060/gui.json)

### 配置信息

MuMu模拟器12，模拟小米12S Pro，1920*1080 (DPI 280)，60帧
已开启截图增强
已开启加速推理，GPU型号RTX 3070

**Comment by Alan-Charred** [comment]
您好，感谢反馈，我们已注意到这个问题。是由于识别到确认按钮后点击太快，导致未能进入新的一天而卡住。关闭截图增强模式可以缓解这个情况。将会在下个版本通过回滚机制增加这个地方的容错率。
