### ISSUE TITLE
[CICD] 调整 CI 构建和 Release 发包

### ISSUE THREAD

**Issue by LiamSho** [MaaAssistantArknights/MaaAssistantArknights#1054]
PS：「文件数据」指的是文件的文件名、校验码、所属版本、相对位置信息；「文件本体」指的是文件二进制数据本身。

## 为什么

MAADS 我越整越乱。

说一下现在的 MAADS 的逻辑：

1. 下载完整的 MAA 包，解压，压缩 `resource` 文件夹后再删除它。将 `resource.zip` 和其他文件作为这个版本的所有文件，计算校验码，与数据库比对，去重后将新文件数据加入数据库，将该文件本体加入文件库。

2. 从数据库检索本次更新的版本所有的文件数据，以及前几个版本的所有文件数据，作对照，然后打包出一个更新包，将更新包数据加入数据库，更新包文件作为一个可下载文件提供服务。

3. 将完整版数据加入数据库，将完整包文件本体作为一个可下载文件提供服务。

现在的逻辑过于繁琐且有弊端，并且一旦 MAA 打包文件作出变更，需要 MAADS 在其变更前作出变更，不然就炸。例如第一，现在的 MAA 完整包，包含一个设计器文件夹，而 MAADS 若按照上述（之前定的）逻辑运行，那么会将这个设计器文件夹中所有的内容是为一个个单独的文件，而不是作为一个整体。第二，MAADS 处理之后的更新包，`resource` 文件夹是被压缩过的，而完整包内没有，两个文件逻辑不一致。

### （1）MAA

定义以下 MAA 的组成：

1. MaaCore - MAA 的核心 DLL 文件，单独一个文件
2. MaaDependency - MAA 核心依赖文件，即除了 MAA 核心 DLL 以外其他 DLL 文件组成的集合
4. MaaResource - MAA 资源文件，MAA 的 `resource` 文件夹，已在单独的仓库发布 Release
5. MaaLegacyFullBundle - 现在的 `MeoAssistantArknights_vX.Y.Z.zip` 文件，即包含 WPF 在内的 v5.0.0（计划） 前完整 MAA 包
6. MaaLegacyOTA - 现在的 `MeoAssistantArknights_OTA_vX.Y.Z.zip` 文件，即 v5.0.0（计划）前的 OTA 升级包
7. 其他单独 MAA 组件

#### 在 Push 标签时，运行自动构建和发布，此仓库 Release 中生成以下文件

1. `MaaCore-vX.Y.Z.zip` - MAA 的核心 DLL 文件打包为 ZIP
2. `MaaDependency-vX.Y.Z.zip` - MAA 核心依赖文件打包为 ZIP
3. `MaaDependency-NoAvx-vX.Y.Z.zip` - MAA 核心依赖文件（NOAVX）打包为 ZIP
4. `MaaBundle-vX.Y.Z.zip` - 包含 WPF 在内的 v5.0.0（计划） 前完整 MAA 包，和现在的一致
5. `MaaBundle-OTA-vX.Y.Z.zip` - v5.0.0（计划）前的 OTA 升级包，和现在的一致
6. checksum.txt - 以上所有文件的 MD5（或是SHA1，待定） 校验码（或者内容可以放在更新日志内），格式为：

``` txt
MaaCore-Windows-x64-vX.Y.Z.zip:AFBF1E37FF4CE7A014799CDEDFF469E3
MaaDependency-Windows-x64-vX.Y.Z.zip:ABBEFAD4567B92B02A61059F6556B325
...
```

#### 在 `master` 分支收到 Push 后，在其他仓库中的操作

对于追踪的资源目录有所更改，则生成 `MaaResource-{VERSION_STRING}.zip` 文件并发布在 `MAA/MaaResourceRelease` 仓库，如果是对应服务器的，比如美服，则生成 `MaaResource-NA-{VERSION_STRING}.zip` 文件再发布

对于其他 MAA 组件，例如使用 Kotlin 编写的 Maa HTTP API，有需要可以单独编写 GitHub Actions 配置文件，然后在该项目路径在 master 下有更改时，运行 Actions 并在一个新建的仓库中发布 Release，所有其他 MAA 组件类别的东西均发布在这个仓库中

### （2）MAADS

MAADS 将不再做包处理的工作

MAADS 包含 3 个部分，即 API，更新器，MAA 文件服务器

#### API

1. 查询更新的 API，代替从 GitHub 直接查询，主要目的是提高国内的访问成功率
2. 提供文件下载 API，访问后将 302 重定向到真正的下载站点

#### 更新器

检查 GitHub Release 的发布，当有 Release 时，通知 MAA 文件服务器去下载，或者下载文件然后上传至 MAA 文件服务器、其他类型的文件服务器等，当文件服务器保证了文件存在时，告知 API，将版本更新数据加入数据库。

#### MAA 文件服务器

`MAA 文件服务器` 是一个单独的软件，可以部署一个文件下载节点。

一个节点是一个可提供文件下载的 API，MAADS API 将根据用户请求 IP 来源导航至合适的下载点。有多个可用的节点：GitHub Release，FastGit 镜像站，Cloudflare Worker，以及部署的 `MAA 文件服务器` 节点。下载请求端可以带上合适的参数，请求转发到某个类型的节点，GitHub Release 节点作为最终的 Fallback 节点。

为什么通过这个方式：CDN 或者 COS 之类的服务忒贵了，不如直接在现有的服务器上架设，然后 MAA 文件服务器 可以告知 MAADS API “流量告警，别来了”，那么 MAADS API 便不会向这个节点转发请求（

## 需要做的（指 MAA）

> 不需要了（

~~现在 WPF UI 部分只做了过滤掉包含 OTA 字样的 assets，需要做出更改（所以之前就只是改成这样而没有做完整的文件名匹配？？？~~

~~**在做出更改后过几个版本再修改 CI 构建和 Release 的发布模式，防止出现大量用户未更新使用 Patch 过的 WPF UI，更新 Release 模式和下载到期望之外的包而更新失败的问题**~~

~~https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/e73f0c62d6a7bd5b2d9b7282aab2b16beff8201b/src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs#L428-L432~~

## 好处

1. 调整 CI 和 Release 的改动量小，而 MAADS 的设计可以极大简化，MAA 其他组件也可以被囊括在 MAADS 可镜像的范围内，不用单独编写新的逻辑。
2. MAADS 中的包和 Release 中的完全一致，因为 MAADS 不会对包进行二次操作，因此前端不用为不同的文件结构单独做适配了。
3. MAADS 会直接获取并缓存 Release 里所有的文件，在新 UI 生出来前，现在的 WPF 版本也能利用 MAADS 了。

**Comment by LiamSho** [comment]
@MistEO 看看（

**Comment by MistEO** [comment]
见鬼，你们都不睡觉的吗.jpg

我爬了白天再看（

**Comment by MistEO** [comment]
> 在 Push 标签时，运行自动构建和发布，此仓库 Release 中生成以下文件
MaaCore_Windows_x64_vX.Y.Z.zip - MAA 的核心 DLL 文件打包为 ZIP
MaaDependency_Windows_x64_vX.Y.Z.zip - MAA 核心依赖文件打包为 ZIP
MeoAssistantArknights_vX.Y.Z.zip - 包含 WPF 在内的 v5.0.0（计划） 前完整 MAA 包，和现在的一致
MeoAssistantArknights_OTA_vX.Y.Z.zip - v5.0.0（计划）前的 OTA 升级包，和现在的一致
checksum.txt - 以上所有文件的 MD5（或是SHA1，待定） 校验码（或者内容可以放在更新日志内），格式为：
MaaCore-Windows-x64-vX.Y.Z.zip:AFBF1E37FF4CE7A014799CDEDFF469E3
MaaDependency-Windows-x64-vX.Y.Z.zip:ABBEFAD4567B92B02A61059F6556B325
MeoAssistantArknights_vX.Y.Z.zip:76866718C0C6EA226F4601F1FF81B93C
MeoAssistantArknights_OTA_vX.Y.Z.zip:28CD3CEDD59F066C0589DA2229DD9CBE

不行，鬼知道用户会下载成哪个，然后又会有人来问为什么打不开

或许可以把 MaaRelease 那个仓库再利用起来

**Comment by MistEO** [comment]
MaaRelease 怎么没了（？）

**Comment by LiamSho** [comment]
> MaaRelease 怎么没了（？）

早没了（

跨仓库推送太麻烦了

顶上加个

# 第一次使用请下载 xxxxx

不会还tm有小白搞错吧（

**Comment by LiamSho** [comment]
而且不对啊，为啥要从 Release 下载，直接首页，README 加个巨大按钮去到下载链接就好（

**Comment by MistEO** [comment]
很多人只收藏了 Release 页面，除非我每次都在 changelog 里面加一句 `第一次使用请下载`，重复的内容每次发，而且感觉也太啰嗦了

**Comment by LiamSho** [comment]
我认为这个疑虑时多余的（

怎么那么多开源项目这么干的就 MAA 用户智商低一点的？（

**Comment by MistEO** [comment]
是啊，因为本来就是面向小白的。我发现 maa 的小白用户相比 aah 多的离谱

**Comment by MistEO** [comment]
而且要考虑到兼容性问题，很多人很久才更新一次，用老版本客户端请求的时候请求下来哪个不对的，直接就炸了

**Comment by MistEO** [comment]
群里讨论了一下，开整！

**Comment by qianxu2001** [comment]
题外提一句，压缩包内最好套一层文件夹，免得有的人直接解压会出来一坨文件，另外也可以避免使用解压软件的解压到(压缩包文件名/)文件夹，因为这样文件夹名后面会带版本号，还得手动改

**Comment by xiaoyv404** [comment]
> 题外提一句，打包的时候压缩包内最好套一层文件夹，免得有的人直接解压会出来一坨文件，另外也可以避免使用解压软件的解压到(压缩包文件名/)文件夹，因为这样文件夹名后面会带版本号，还得手动改

同意

**Comment by xiaoyv404** [comment]
> 题外提一句，打包的时候压缩包内最好套一层文件夹，免得有的人直接解压会出来一坨文件，另外也可以避免使用解压软件的解压到(压缩包文件名/)文件夹，因为这样文件夹名后面会带版本号，还得手动改

同意

**Comment by LiamSho** [comment]
> 题外提一句，打包的时候压缩包内最好套一层文件夹，免得有的人直接解压会出来一坨文件，另外也可以避免使用解压软件的解压到(压缩包文件名/)文件夹，因为这样文件夹名后面会带版本号，还得手动改

大部分文件还是给程序使用的，没有必要。而 OTA 和 Bundle 要是多套一层，现在的更新逻辑就炸了（
