### ISSUE TITLE
保全派驻中部分角色操作异常

### ISSUE THREAD

**Issue by 0O0o0oOoO00** [MaaAssistantArknights/MaaAssistantArknights#10551]
### 说说你遇到的问题？

在使用`resource\copilot\SSS_玉门市集-维什戴尔+澄闪+浊心斯卡蒂+纯烬艾雅法拉or流明-攀云机.json`时，`维什戴尔`的三技能有时候在被打开后立刻关闭，在最后一关中尤其明显

携带干员:
![image](https://github.com/user-attachments/assets/211c0ae8-dd7a-45da-861c-c501f493d022)

Resource Version: 泰拉饭
Resource Time: 2024/9/6 01:26:34
UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

操作系统: Windows 10 22H2 19045.4780 专业版
模拟器: MuMu12 V4.0.0(3179)，1280*720，DPI 240，60FPS
MAA: 未开启截图增强，使用GPU 加速推理，GPU: NVIDIA GeForce RTX 3060 Laptop GPU，GPU驱动版本: 32.0.15.6081

[log.zip](https://github.com/user-attachments/files/16920702/log.zip)

**Comment by Daydreamer114** [comment]
cc @ABA2396 开技能的间隔同步到保全了吗？要不要给保全的默认截屏间隔加一点，看最近说连开连关的人挺多的

**Comment by ABA2396** [comment]
> cc @ABA2396 开技能的间隔同步到保全了吗？要不要给保全的默认截屏间隔加一点，看最近说连开连关的人挺多的

dev 改了，还加了点日志，没发版
