### ISSUE TITLE
繁中板 迷城主題 辨識異常

### ISSUE THREAD

**Issue by meikenakinori** [MaaAssistantArknights/MaaAssistantArknights#10559]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

繁中板 迷城主題 辨識異常 

### Version

UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

09/09 18:20
[asst.log](https://github.com/user-attachments/files/16929076/asst.log)
[gui.log](https://github.com/user-attachments/files/16929079/gui.log)
[gui.json](https://github.com/user-attachments/files/16929083/gui.json)

### 配置信息

MuMu 12，MuMu 截图增强开启
 GPU 开启 intel 內顯

**Comment by kobi1108** [comment]
same for 暗黑主題，只有原版能辨析

**Comment by Manicsteiner** [comment]
只是纯粹的没人做适配，前些日子给繁中服做适配的那位有一阵子没活跃了

您现在可以做的事：
 - 等待适配
 - 提供一张这个主题的主界面截图，需要是模拟器生成的原生分辨率的原图，然后由我们来截取对应模板
   - 考虑到这是繁中服初次实装主题功能，最好也把另两个已有主题的主界面也提供一下
 - ~~克隆一份源代码，将以上图片重命名为MistCity.png，放置在`\tools\GetImageFromROI\src\`下，在配置好的Python环境下运行`\tools\GetImageFromROI\start.bat`，把dst目录下生成的图片模板移动到需要的目录中，然后提交commit、提交pr~~

**Comment by kobi1108** [comment]
BS内建截圖，另外有一張肉鴿還沒解所以就沒有了
![Screenshot_2024 09 09_23 42 58 339](https://github.com/user-attachments/assets/e35063ef-eced-420e-a3f4-830e3ad23c03)
![Screenshot_2024 09 09_23 43 07 266](https://github.com/user-attachments/assets/4738e102-6c43-4e98-9769-3d5e24794d30)

**Comment by Manicsteiner** [comment]
感谢提供！其实已经加入客户端但暂时无法获取的主题可以在 更换主题-预览 的界面，点击空白处查看完整的界面，使用这个预览图也可以制作图片模板

**Comment by kobi1108** [comment]
有了 原來可以這樣xd
![Screenshot_2024 09 09_23 48 55 045](https://github.com/user-attachments/assets/07cad4e9-c761-44a6-818b-3e334bf4ed93)
