### ISSUE TITLE
集成战略干员识别异常

### ISSUE THREAD

**Issue by Here-is-Daiyu** [MaaAssistantArknights/MaaAssistantArknights#10553]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

水月和傀影肉鸽中发生干员错误识别现象

### Version

Resource Version: 泰拉饭
Resource Time: 2024/9/8 18:05:05
UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16922550/asst.log)
[gui.log](https://github.com/user-attachments/files/16922551/gui.log)

### 配置信息

win11 23h2
mumu12舟专版 1600*900 DPI240 15帧
开启截图增强
开启GPU加速推理	Intel(R) Iris(R) Xe Graphics

	驱动程序版本:	32.0.101.5971
	驱动程序日期:	2024.08.16
	DirectX 版本:	12 (FL 12.1)

### 截图或录屏

![image](https://github.com/user-attachments/assets/2fcb4630-dc11-4f3a-970c-0021c3baf7ac)
.\cache\avatars<del/>不太确定是不是这里但是看到好像有问题就截出来了<del>文件之前删过一次有些少（

### 还有别的吗？

确切的说是在傀影肉鸽里发现maa疯狂把益达往地上扔才感觉有问题
本来以为是傀影的问题就换了水月
结果它开始把logos往地上扔
然后就感觉不对劲看log也没看出什么
看了部署方法和点位发现<del/>应该<del>没问题就开始看是不是识别问题（
萨卡兹没试过但在萨米好像也有过

**Comment by Daydreamer114** [comment]
这截图要笑死我了

试试删掉这个文件夹里的所有东西，然后关掉mumu增强和gpu加速，能不能复现这个问题？

**Comment by Here-is-Daiyu** [comment]
![image](https://github.com/user-attachments/assets/37bf1df3-208d-4490-9b9b-8879d6238425)
看上去好像不出现了，应该是GPU加速的锅（

**Comment by Here-is-Daiyu** [comment]
![image](https://github.com/user-attachments/assets/821ce1f4-f2bc-4b85-9367-841ce8aa1c87)
错误的 还是发生了（

**Comment by Rbqwow** [comment]
等下 帧数是多少？
如果有什么后台自动节能之类的得关了
> 所有涉及到自动战斗的功能都需要至少 60 帧的稳定游戏帧数，这包括但不限于自动战斗和自动肉鸽。
> —— [文档站](https://maa.plus/docs/zh-cn/manual/introduction/integrated-strategy.html)

**Comment by Here-is-Daiyu** [comment]
w之前没看文档站改了帧数再试试（
<del>还有maa能不能加一个检测到明日方舟闪退了自动调用“开始唤醒”重新进入游戏的功能啊<del>

**Comment by Here-is-Daiyu** [comment]
![image](https://github.com/user-attachments/assets/cd96b7ba-216b-4a09-ae42-137dc23e790e)
补一个:高台米格鲁(
![image](https://github.com/user-attachments/assets/9bc0ba8e-34fd-4fdf-b513-4a0e7e4e27fe)
没改帧数挂了一天好像比开了gpu加速好点，打开mumu截图加速实测无影响

**Comment by ABA2396** [comment]
这个核显之前没进黑名单吗）我记得之前 ban 了一大批

**Comment by Rbqwow** [comment]
> 这个核显之前没进黑名单吗）我记得之前 ban 了一大批

有些核显没 比如Xe
蛋佬说的是Xe驱动重写过还是啥来着 总之想象中应该不会出问题
核显全拉进来得了(

> ~~还有maa能不能加一个检测到明日方舟闪退了自动调用“开始唤醒”重新进入游戏的功能啊~~

有个叫守护线程的PR是 但是貌似还没写完

**Comment by Constrat** [comment]
> There's a PR called the daemon thread, but it doesn't seem to be finished yet

Still a big work in progress, since we need to square some things first.
