### ISSUE TITLE
保全派驻有没可能出自动刷关呢?

### ISSUE THREAD

**Issue by zoe4477** [MaaAssistantArknights/MaaAssistantArknights#1055]
保全太折磨了
能刷前三关拿到三级模组材料就行

**Comment by YipKei** [comment]
玛丽昨天被保全派驻打爆了（字面含义）
所以可能还得等一段时间厘清作战逻辑并抽象出来
如果有可能的话，你也可以设想一个相对通用的作战逻辑来加快这一进程。

**Comment by MistEO** [comment]
我自己还没玩明白.jpg

**Comment by ntgmc** [comment]
我给出我的设想（请勿轻信）：根据拥有的干员主动选择对应的方案，如先锋+泥岩，攻击温蒂，攻速澄闪，攻速铃兰，攻速灵芝等，反正地图都是固定的，只有干员和顺序的区别，低配就直接忽略

**Comment by YipKei** [comment]
＃1064 半成品框架 @ntgmc

**Comment by ttxs25830** [comment]
感觉主要思路就是先挑选几个高练强力干员，再配合拿低费快部署干员作为升级素材吧。
高练干员可以写死那几个，判断练度够不够就可以了。然后取出对应的战术装备配置。最后形成一个总共需要的战术装备列表。
最后按比例挑选那些低费在部署快的干员即可

**Comment by YipKei** [comment]
> 我的思路设想：先挑选几个高练强力干员，再配合拿低费快部署干员作为升级素材吧。 高练干员可以写死那几个，判断练度够不够就可以了。然后取出对应的战术装备配置。最后形成一个总共需要的战术装备列表。 最后按比例挑选那些低费在部署快的干员即可

通关的套路让玩家开发，开发者只负责提供玩家实现套路的方式，这样的方式才是具备可持续性的，如果靠开发者将这些东西写死，除了累死开发者之外，碰到什么新的需求也很难做到尽可能快地满足玩家的需求。毕竟开发MAA对大佬来说只是兴趣而不是工作。

**Comment by MistEO** [comment]
WIP https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/3203
