### ISSUE TITLE
保全需要优化娜仁图雅1、梅尔2、ew3的自动释放逻辑

### ISSUE THREAD

**Issue by MoXiaoX** [MaaAssistantArknights/MaaAssistantArknights#10550]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [x] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

娜仁图雅1和山2、赫德雷2同款切换型技能，需要优化逻辑避免不停开关；
梅尔2在没有召唤物的情况下无法释放（与刻刀索敌失败后返还技力逻辑不同，但一样会导致技能一直亮着），maa会反复尝试开启。
还有ew的爆裂黎明，因为加了攻击间隔，开启前摇特别长，在前摇期间技能会一直亮着，如果正好卡在前摇期间进行了截图识别会导致爆裂黎明秒开后秒关。*攻速提升、ew前摇帧减少后，这种情况的发生率大大降低，故得此结论
另外，在maa选中干员准备开启技能的瞬间，干员被控无法释放技能，会导致一直停留在选中干员的时停阶段，没有下一步操作。
以上情况均为保全模式测得，不清楚其他模式的自动释放逻辑是否会出现相似问题。

### Version

UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16920639/asst.log)

### 配置信息

gpu加速：已开启3080laptop
系统版本：win11,23h2,22631.4037
模拟器：蓝叠5.21.150.1024 安卓9 1080P 240DPI 60FPS

**Comment by Mou-Froski** [comment]
感觉不止保全，肉鸽的ew也有相同问题
保全里爱丽丝2和梅尔2的问题相同，不知道maa有没有“不开启技能”的逻辑，有的话给保全非核心干员套上得了（

**Comment by ABA2396** [comment]
之前改了下技能识别和使用的逻辑，ew 如果在1.5s 内能开出技能来应该不会再关了）
