### ISSUE TITLE
任务重复中途停止时系统概率卡死，一段时间后蓝屏报错Critical_process_died

### ISSUE THREAD

**Issue by gClov** [MaaAssistantArknights/MaaAssistantArknights#10567]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及
- [X] 我正在使用最新的 MAA 公测版本和最新的官版或方舟专版 MuMu 模拟器
- [X] 我已参考文档确定安装路径、实例编号、屏幕编号填写正确，并确认在关闭截图增强模式后问题消失
- [X] 我未开启后台保活，帧数设置为 60，显存使用策略为“画面表现更好”

### 问题描述

 模拟器版本4.0.6时，概率直接蓝屏KERNEL_DATA_INPAGE_ERROR，重启后事件查看器出现“驱动程序在 \Device\MuMuVMMNetLwf 上检测到内部驱动程序错误。”覆盖安装4.0.6后仍然出现，在设置中显示“directx当前不可用”。卸载后安装4.0.5.3292版本，directx恢复，未出现KERNEL_DATA_INPAGE_ERROR、“驱动程序在 \Device\MuMuVMMNetLwf 上检测到内部驱动程序错误。”。

模拟器版本4.0.5.3292，概率卡死后触发Critical_process_died。
-尝试单独运行mumu模拟器，切换显卡渲染模式，未触发问题。
-使用maa，启用截图增强模式，显卡渲染模式为directx，使用显卡加速或不使用gpu加速。执行”开始唤醒“或”自动公招“时多次重复开始、中断任务，出现系统卡死，一段时间后蓝屏Critical_process_died。连续复现五次。
-关闭截图增强，使用显卡加速或不使用gpu加速。执行”开始唤醒“，”自动公招“时多次重复开始、中断任务。系统及程序正常运行。

显卡驱动为560.94，系统为win10，错误发生后覆盖安装过win10系统，仍然出现。

不确定仅仅由于截图增强模式导致重复开始、中断任务时系统卡死蓝屏。且在蓝屏时无法正常转储存文件，没有生成dump。

最近五次成功复现的大致时间可参考下图。
![image](https://github.com/user-attachments/assets/51312d7b-bb25-45a5-924a-60374827bd42)

### Version

UI Version: v5.6.0
Core Version: v5.6.0
Resource Version: 泰拉饭
mumu版本：4.0.5.3292

### MAA 日志文件

[asst.log](https://github.com/user-attachments/files/16932808/asst.log)
[gui.log](https://github.com/user-attachments/files/16932813/gui.log)

### MuMu 问题诊断

基础信息
UUID :  73a9ec04-ac5b-4402-8f72-b2a69f4ad191
模拟器版本 :  4.0.5.3292
模拟器磁盘（可用/总）空间 :  115.2GB/125GB
日志路径 :  D:\Netease\MuMu Player 12\vms\MuMuPlayer-12.0-0\logs\

运行环境
VT :  开启
Hyper-V :  关闭
网络环境检测 :  正常
以管理员运行方式 :  否
DirectX 11是否安装 :  是
防火墙 :  开启（建议关闭）

电脑配置
主板型号 :  Manufacturer: HP  Product: 88F4
CPU :  11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
系统版本 :  Windows 10 64-bit Kernel 10.0.19045
显卡驱动 :  正常
显卡驱动型号 :  32.0.15.6094 (20240814)
所有显卡 :  NVIDIA GeForce RTX 3060 Laptop GPU  |  Intel(R) UHD Graphics  |  Microsoft Basic Render Driver
当前使用显卡 :  NVIDIA GeForce RTX 3060 Laptop GPU
安装磁盘(可用/总)空间 :  113.3GB/931.5GB
可用内存/总内存 :  18.6GB/31.6GB

模拟器设置
Root :  关闭
显卡渲染模式 :  DirectX 模式
性能设置 :  6核/12GB
手机型号 :  Xiaomi 12S Pro
分辨率 :  1920 * 1080
高帧率 :  开启
后台保活 :  关闭

连接设备
音频输入 :  已连接
音频输出 :  已连接

网络信息
MuMu DNS :  192.168.5.1
电脑DNS :  192.168.5.1
Rom MAC地址 :  08:fb:47:7b:10:00

ADB调试端口 :  16384
MuMu出口IP地址 :  10.0.2.15
电脑出口IP地址 :  123.154.161.5

其它信息
其它版本信息 :  vm: 120.1.79.004 hyperv: 6.3.27.0 renderer: 0.0.184.0
Vendor :  NetEase
OpenGL Renderer :  MuMu GL (NVIDIA GeForce RTX 3060 Laptop GPU Direct3D11 vs_5_0 ps_5_0)
OpenGL Version :  OpenGL ES 3.1 V132
运行时间 :  0 : 44 : 38

### 截图

有3个复现蓝屏的视频，上传了一个在阿里云盘[链接](https://www.alipan.com/s/MdtBZBvPbGV) 提取码： ao29 ，复现流程基本是通过截图增强模式连接，多次重复开始、中途结束任务如自动公招。当右键任务栏或桌面未出现弹窗时基本复现成功。卡死后出现过一次windows资源管理器自动重启系统成功恢复，再次重复触发流程后死机蓝屏。其余复现都为死机后直接蓝屏。

### 其他

[Uploading gui.json…]()

**Comment by gClov** [comment]
[gui.json](https://github.com/user-attachments/files/16933225/gui.json)

**Comment by gClov** [comment]
不确定是否能在其他电脑复现，可以按步骤重复中断任务试试，如果只是个例可以关闭这个issue

**Comment by gClov** [comment]
4.0.7版本已经无法复现了，应该修复了

**Comment by genrihx2** [comment]
【MuMu模拟器安卓12】版本：4.0.8

The driver encountered an internal driver error on \Device\MuMuVMMNetLwf.    
![image](https://github.com/user-attachments/assets/ae7f6f05-c7bd-4210-8755-9df8c481c3c0)
