### ISSUE TITLE
建议自动关机可以指定时间

### ISSUE THREAD

**Issue by zoe4477** [MaaAssistantArknights/MaaAssistantArknights#1056]
设置了定时任务, 想要当天最后一次定时任务完成后再自动关机, 但目前好像只能当前任务完成后自动关机, 希望可以指定关机时间

**Comment by MistEO** [comment]
那自己用 shutdown 命令就好啦

**Comment by ABA2396** [comment]
win+R
输入 cmd 回车
输入 shutdown -s -t `距离指定关机的时间（秒）` *或者 at* `指定关机时间（如输入12:00）` shutdown -s
如果要取消的话就输入 shutdown -a

**Comment by ABA2396** [comment]
> win+R 输入 cmd 回车 输入 shutdown -s -t `距离指定关机的时间（秒）` _或者_ at `指定关机时间（如输入12:00）` shutdown -s 如果要取消的话就输入 shutdown -a
