### ISSUE TITLE
开启截图增强后MuMu12 明日方舟无故闪退

### ISSUE THREAD

**Issue by jinghuashang** [MaaAssistantArknights/MaaAssistantArknights#10574]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及
- [X] 我正在使用最新的 MAA 公测版本和最新的官版或方舟专版 MuMu 模拟器
- [X] 我已参考文档确定安装路径、实例编号、屏幕编号填写正确，并确认在关闭截图增强模式后问题消失
- [X] 我未开启后台保活，帧数设置为 60，显存使用策略为“画面表现更好”

### 问题描述

在开启MuMu12的截图增强后，会出现无故闪退情况，并且在DT-EX-1 尤为明显(100%闪退)，其他关卡也是概率出现，包括肉鸽等，但关闭后不会出现这个问题。

电脑的GPU是AMD核显(R7-5800H)

### Version

MAA 版本 ： v5.6.0
MuMu版本：V4.0.5
OS : Win11 工作站版

### MAA 日志文件

[Uploading asst.log…]()

### MuMu 问题诊断

基础信息
模拟器版本 :  4.0.5.3284
模拟器磁盘（可用/总）空间 :  100.7GB/125GB
日志路径 :  D:\Program Files\MuMuPlayer-12.0\vms\MuMuPlayer-12.0-0\logs\

运行环境
VT :  开启
Hyper-V :  开启
网络环境检测 :  正常
以管理员运行方式 :  否
DirectX 11是否安装 :  是
防火墙 :  开启（建议关闭）

电脑配置
主板型号 :  Manufacturer: ASUSTeK COMPUTER INC.  Product: M3500QA
CPU :  AMD Ryzen 7 5800H with Radeon Graphics
系统版本 :  Windows 11 64-bit Kernel 10.0.22631
显卡驱动 :  正常
显卡驱动型号 :  31.0.21912.14 (20240220)
所有显卡 :  AMD Radeon(TM) Graphics  |  Microsoft Basic Render Driver
当前使用显卡 :  AMD Radeon(TM) Graphics
安装磁盘(可用/总)空间 :  110GB/480.5GB
可用内存/总内存 :  3.7GB/13.9GB

模拟器设置
Root :  关闭
显卡渲染模式 :  DirectX 模式
性能设置 :  6核/6GB
手机型号 :  Xiaomi 12S Pro
分辨率 :  1600 * 900
高帧率 :  开启
后台保活 :  关闭

连接设备
音频输入 :  已连接
音频输出 :  已连接

ADB调试端口 :  16384

其它信息
其它版本信息 :  vm: 120.1.79.004 hyperv: 6.3.27.0 renderer: 0.0.184.0
Vendor :  NetEase
OpenGL Renderer :  MuMu GL (AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0)
OpenGL Version :  OpenGL ES 3.1 V132
运行时间 :  0 : 11 : 45

**Comment by jinghuashang** [comment]
[asst.log](https://github.com/user-attachments/files/16943458/asst.log)
[gui.log](https://github.com/user-attachments/files/16943459/gui.log)

问题大概出现在 17:40-18:10

**Comment by HYY1116** [comment]
原来是mumu增强的问题吗？感觉mumu本身的问题可能更大一点，我在不使用MAA时也会闪退

**Comment by jinghuashang** [comment]
我倒是没遇到过不使用MAA闪退的情况，也可能是不使用MAA的时候没挂多长时间（

但雀氏在DT-EX-1的时候MAA（增强启用的时候）挂着自动打还没通关就闪退了，反正关了使用MAA到ex关打完了都没闪退过

**Comment by jinghuashang** [comment]
> 原来是mumu增强的问题吗？感觉mumu本身的问题可能更大一点，我在不使用MAA时也会闪退

我倒是没遇到过不使用MAA闪退的情况，也可能是不使用MAA的时候没挂多长时间（

但雀氏在DT-EX-1的时候MAA（增强启用的时候）挂着自动打还没通关就闪退了，反之关了使用MAA到ex关打完了都没闪退过

**Comment by dantmnf** [comment]
可以尝试转译运行 ARM64 版明日方舟，缓解 32 位地址空间耗尽导致的闪退问题

```
adb install --abi arm64-v8a arknights-hg-2361.apk
```

**Comment by jinghuashang** [comment]
> 可以尝试转译运行 ARM64 版明日方舟，缓解 32 位地址空间耗尽导致的闪退问题
> 
> ```
> adb install --abi arm64-v8a arknights-hg-2361.apk
> ```

有其他办法吗，每次都转感觉有点麻烦

**Comment by jinghuashang** [comment]
刚刚转了，还是会闪退

**Comment by jinghuashang** [comment]
还有大佬有其他解决方案吗，转译arm64版本还是会存在闪退问题

**Comment by dantmnf** [comment]
这个估计只能跟 mumu 那边反馈了，虽然我个人感觉截图不会影响模拟器里的游戏进程（
