### ISSUE TITLE
任务完成后的系统通知疑似格式化失效

### ISSUE THREAD

**Issue by SST-03** [MaaAssistantArknights/MaaAssistantArknights#10579]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

![4%9BACU@Y5UZ9881GR8AZSO](https://github.com/user-attachments/assets/1ee44e2e-4a0b-4860-b024-d74391b27ece)
如图所示。

但是MAA页面内的是正常的“任务已全部完成！
(0h 0m 5s 后)”

### Version

Resource Version: 泰拉饭
Resource Time: 2024/9/9 17:05:05
UI Version: v5.6.1-alpha.1.d062.g08f44e066
Core Version: v5.6.1-alpha.1.d062.g08f44e066
Build Time: 2024/9/10 19:17:51

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16956885/asst.log)
[gui.log](https://github.com/user-attachments/files/16956886/gui.log)

时间点：今日10:04

### 配置信息

Windows 11 22H2（22621.4037）
~~使用了StartAllBack，不确定是否是软件之间的兼容性问题~~ 关闭StartAllBack之后仍然复现。

**Comment by SST-03** [comment]
[commit 08f44e0](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/08f44e066df77c316d1037f48f759899a7017e88)
bug是从这个commit之后才出现的，所以大概率是这个commit漏了点什么

**Comment by SST-03** [comment]
> #10562 bug是从这个pr之后才出现的，所以大概率是这个pr漏了点什么

以及，“理智将在 {DateTime} 回满。({TimeDiff} 后)”的表现是正常的。

**Comment by Constrat** [comment]
fixed with 1c00f4277e627dacf5fc7ff42c462e0fb7dcc3ab



> 以及，“理智将在 {DateTime} 回满。({TimeDiff} 后)”的表现是正常的。

I didn't change the sanity report output. Just tweaked the "standard" "All tasks have been completed" to add some more context :)
