### ISSUE TITLE
【日服】明日方舟萨米代理识别问题（一层沼泽里的抽泣声；一层待宰的兽群干员放置偏离问题）

### ISSUE THREAD

**Issue by MAUSARK** [MaaAssistantArknights/MaaAssistantArknights#10577]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

MAA萨米肉鸽刷钱代理问题：
开局锏，突击战术分队。
一层沼泽里的抽泣声（流泪狗）出现卡关，下面两个选项反复切换但是不点下去。
一层待宰的兽群，开局锏有概率不放在蓝门口导致战斗失败。

### Version

Resource Version: OP:LA
Resource Time: 2024/9/5 16:42:23
UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16946086/asst.log)
[gui.log](https://github.com/user-attachments/files/16946093/gui.log)
[gui.json](https://github.com/user-attachments/files/16946097/gui.json)
问题时间：9月3日15：00左右和9月8日19：00左右

### 配置信息

操作系统及版本Windows 11 64-bit Kernel 10.0.22635
模拟器品牌MUMU
模拟器分辨率1280*720
DPI240
帧率60
GPU加速推理开启（GPU型号：MX250）

### 截图或录屏

[debug-roguelike文件夹内截图.zip](https://github.com/user-attachments/files/16946002/debug-roguelike.zip)
截图日期为9月3日和9月8日。我看到是有不一样关卡的截图，都可以看看有没有识别问题。流泪狗那关大概率是有问题的。截图时用模拟器的分辨率是1280*720，后续用1920*1080分辨率后未出现问题。

**Comment by MAUSARK** [comment]
[asst.bak.log](https://github.com/user-attachments/files/16946450/asst.bak.log)
补充文件

**Comment by liuyifan-eric** [comment]
log过期了。看gui时间点有可能是没识别出事件

**Comment by lemorld** [comment]
日服水月"涙目のペッロー"也就是狗眼婆娑在1280720下有同样错误@Manicsteiner
