### ISSUE TITLE
可不可以取消掉落物识别啊？

### ISSUE THREAD

**Issue by wuwukaibukaigua** [MaaAssistantArknights/MaaAssistantArknights#1057]
每次打完关卡都要等个10几秒就为了识别掉落物，但是我我觉得很多人根本不在意这个。你只要关卡刷的对，掉落物都是趋近于概率的。感觉取消掉落物识别，直接开始下一把更不错，或者搞个功能开关一下。大神你觉得呢。

**Comment by ABA2396** [comment]
但你觉得是在识别掉落物的时候可能是在识别结束战斗的标志（）你是不是打了那些带有随机属性的关卡，那些会根据你第一次通关的时间或者最长的通关时间计算，如果你有小于这时间的通关记录就会调子等待时间很长

**Comment by wuwukaibukaigua** [comment]
ok，懂了

**Comment by MistEO** [comment]
掉落物识别本身只需要几十毫秒，等待的时间是在等关卡结束

**Comment by wuwukaibukaigua** [comment]
那是不是我有一次关卡通关时间很长，哪怕关了机再重新打开，它都会以最长时间结算。还是说每次打开都要重新计算通关时间。

**Comment by MistEO** [comment]
不是，上面解释的不准确。

是因为刷理智时间较长，不可能每秒都在频繁识别，没有必要而且也太占用电脑性能了，所以现在的策略是约 6 秒才识别一次；

但是考虑到有可能识别错误，所以还要再加个容错机制，也就是即使识别到已经不在作战中了，还要再等 6 秒再次识别并确认。

考虑到这些逻辑你应该就明白了，到了作战结束结束，最少也要等 12 秒才能去点下一步

和记录的作战时间关系不是很大，当然那个也有影响

**Comment by ABA2396** [comment]
> 不是，上面解释的不准确。
> 
> 是因为刷理智时间较长，不可能每秒都在频繁识别，没有必要而且也太占用电脑性能了，所以现在的策略是约 6 秒才识别一次；
> 
> 但是考虑到有可能识别错误，所以还要再加个容错机制，也就是即使识别到已经不在作战中了，还要再等 6 秒再次识别并确认。
> 
> 考虑到这些逻辑你应该就明白了，到了作战结束结束，最少也要等 12 秒才能去点下一步
> 
> 和记录的作战时间关系不是很大，当然那个也有影响

那你是没挂过10图那些关卡吧（）有个隐形飞机，没打掉靠自己扣血的话前后差距能有30秒，那关就很明显，你如果有一个没打掉后面时间都长30秒
