### ISSUE TITLE
MAA在MUMU12模拟器运行日服明日方舟进行自动生息演算时报错（卡在第一天初始界面）

### ISSUE THREAD

**Issue by MXIM1111** [MaaAssistantArknights/MaaAssistantArknights#10587]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

根据MAA提示，删除了之前的存档并且在生息演算界面开始运行MAA，但是MAA在开始演算后，卡在了要见森蚺的地方（如下图）
![屏幕截图 2024-09-12 141109](https://github.com/user-attachments/assets/6e2083f9-5455-43fd-94f5-a02cbf140f46)

这种情况出现了很多次，有时候能刷取2到3次，有时候则刚开始就卡住。我并未开启“MUMU截图增强功能”
这个问题只在日服发现，我上午在日服出现bug后，在同一个模拟器的官服明日方舟尝试自动生息演算，结果一切正常

### Version

Resource Version: OP:LA
Resource Time: 2024/9/5 16:42:23
UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/16974484/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/16974486/asst.log)
[gui.log](https://github.com/user-attachments/files/16974487/gui.log)

[gui.json](https://github.com/user-attachments/files/16974491/gui.json)

时间则是“14:10:24 -- 14:10:59”

### 配置信息

操作系统为WIN11家庭中文版，
模拟器为MUMU12模拟器，
分辨率为2560 X 1440，
DPI为360，
帧率为165，
没有开启MUMU截图增强功能
MUMU模拟器本身也未开启任何限制帧率的功能
GPU加速推理未开启

### 截图或录屏

![屏幕截图 2024-09-12 141109](https://github.com/user-attachments/assets/6d17d089-e518-4fd4-91a7-a2aa0dec0b1d)

https://github.com/user-attachments/assets/6787106e-42bc-4c7f-95f2-8d46a373332b

（视频进行了2倍速处理，还是用QQ录制的，可能没啥用...）

**Comment by Manicsteiner** [comment]
> [2024-09-12 14:10:58.570][TRC][Px4c18][Tx5220] asst::WordOcr [{ 集会環: [ 9, 7, 53, 17 ], score: 0.783672 }, { 人タカ事一場所: [ 10, 28, 102, 14 ], score: 0.726241 }] by OCR Pipeline , cost 18 ms

如果只是ocr问题的话已经修了，5.6.0正式版之后已经大修了一轮，等更新吧
