### ISSUE TITLE
WPF 完成任务通知中的计时器存在问题

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#10584]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

如题 或者如图
这是啥啊 原来不是理智预计恢复时间吗(

### Version

DEBUG VERSION

### 截图或录屏

![image](https://github.com/user-attachments/assets/70c7fd7b-eae3-4df2-acdc-1c16fcb7fc7d)
![image](https://github.com/user-attachments/assets/9d1e4703-b118-4fda-969c-5781d5e66dd3)

**Comment by SherkeyXD** [comment]
toast里面写错了？

**Comment by SherkeyXD** [comment]
#10579

**Comment by Rbqwow** [comment]
...?
草 学姐那个雷电分支里面没这个commit
