### ISSUE TITLE
自动战斗 拖入视频  任务出错：VideoRecognition

### ISSUE THREAD

**Issue by hqyxd** [MaaAssistantArknights/MaaAssistantArknights#10580]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

任务出错：VideoRecognition
系统平台  macOS 12.7 (21G816)  CPU Apple M1 Pro
视频链接 https://www.bilibili.com/video/BV1VS48eKEdG/?spm_id_from=333.337.search-card.all.click&vd_source=6
c54a1e8416bbf11e6ac4920b6a3c541 我下载下来已经转成16:9 1080p的视频了 

### Version

maa版本
v5.5.11452（508）

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/16959952/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/16959953/asst.log)

### 配置信息

系统平台  macOS 12.7 (21G816)  CPU Apple M1 Pro

**Comment by Daydreamer114** [comment]
这就是个测试功能，写着玩的，现在也不维护了
