### ISSUE TITLE
多个 adb 进程时如何确定要 kill 的是哪个？

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#10588]
### 说说你遇到的问题？

我的任务管理器中有 5 个 adb 进程，它们只有 PID 不同。
其中四个由 maa 正常使用，第五个 adb 导致两个 maa 无法连接模拟器
请问我应该如何确定哪个 adb 被意外占用了？

**Comment by ABA2396** [comment]
全 kill 了

**Comment by Daydreamer114** [comment]
我有4个正在换基建的不想kill）

**Comment by HoshinoAyako** [comment]
获取端口，对指定端口关闭。
