### ISSUE TITLE
水月肉鸽刷源石不投资

### ISSUE THREAD

**Issue by killerxhp** [MaaAssistantArknights/MaaAssistantArknights#10582]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

给小号刷源石的时候发现挂了一下午啥都没增加
![屏幕截图 2024-09-11 203619](https://github.com/user-attachments/assets/396cf62c-d3d9-4197-b56f-1b4761753cdd)

### Version

Resource Version: 泰拉饭UI Version: v5.1.0-beta.2Core Version: v5.1.0-beta.2

### 日志和配置文件

[asst.zip](https://github.com/user-attachments/files/16964002/asst.zip)
[gui.log](https://github.com/user-attachments/files/16964005/gui.log)
[gui.json](https://github.com/user-attachments/files/16964010/gui.json)

### 配置信息

win10、雷电、平板1920X1080、dpi280、60帧率

### 截图或录屏

![屏幕截图 2024-09-11 203619](https://github.com/user-attachments/assets/781e9214-a4cb-4e13-8b3e-83bb84fae772)

**Comment by status102** [comment]
可能是没有刷出来投资

**Comment by killerxhp** [comment]
> 可能是没有刷出来投资

我眼睁睁看着有投资入口，然后他只是在商店界面停了几秒然后退出，他根本就没点，我测试了好几遍，不管是重启模拟器还是maa

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/ef0f9234-41d7-4130-8fff-6998c69060a8)
没复现出来，最好在进商店的时候暂停下，用模拟器自带的截图和用 maa 设置-连接设置-截图测试 里截张图看看

**Comment by Daydreamer114** [comment]
![Roguelike@StageTraderInvestSystem](https://github.com/user-attachments/assets/21a98bb7-cf2f-4b14-a0ec-318cc143873d)
在你的log中，这个图片完全没被识别到，需要你提供一下用模拟器自带截屏得到的商店图片

**Comment by killerxhp** [comment]
> ![Roguelike@StageTraderInvestSystem](https://private-user-images.githubusercontent.com/74444214/366833319-21a98bb7-cf2f-4b14-a0ec-318cc143873d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxODA5MDksIm5iZiI6MTcyNjE4MDYwOSwicGF0aCI6Ii83NDQ0NDIxNC8zNjY4MzMzMTktMjFhOThiYjctY2YyZi00YjE0LWEwZWMtMzE4Y2MxNDM4NzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDIyMzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NTRiN2Y5MzUyZjZhMzNiNTU1M2Y1NWM1NzQ4ODJmYTEyMTYwMWYwMjU3YmQxOWNiZDQ1ZTVlMzQ2YTZmODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q6zLyfKxKo4YiZ53sOAKh9yptEZ_xncLHXUUhuGudpw) 在你的log中，这个图片完全没被识别到，需要你提供一下用模拟器自带截屏得到的商店图片

第一次没有 但是后面我重启测试的时候我是盯着进商店的，他根本没点

**Comment by killerxhp** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/366753509-ef0f9234-41d7-4130-8fff-6998c69060a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxODA5MDksIm5iZiI6MTcyNjE4MDYwOSwicGF0aCI6Ii85OTA3Mjk3NS8zNjY3NTM1MDktZWYwZjkyMzQtNDFkNy00MTMwLThmZmYtNjk5OGM2OTA2MGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDIyMzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMzViNDExZTA4NWVhMjM0ODg1OGQ5ODI3NTJlNDUzNGNkMGQ5YTMyZmM1ZWJmNTQ4YTk2ZDM3ZDdhODgxMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fy8xlostAQd0a0H-n0H2WPCIsmZX4_lVOfv2qXIq1cI) 没复现出来，最好在进商店的时候暂停下，用模拟器自带的截图和用 maa 设置-连接设置-截图测试 里截张图看看

这是第一次的，你看探索第二次有个停止，就是我看到他没有点投资才手动停的，然后我关了maa重启打开，还是这样

**Comment by status102** [comment]
要不更新一下再试试？你用的版本已经很旧

**Comment by Daydreamer114** [comment]
草，我才看见，510beta2，这修个毛啊

**Comment by killerxhp** [comment]
> 草，我才看见，510beta2，这修个毛啊

咋了 我是之前更新之后 有次maa死活连上不上模拟器 然后我就 找到很久之前版本用的 就可以了 然后没就更新过

**Comment by killerxhp** [comment]
> 要不更新一下再试试？你用的版本已经很旧

好的 我试试

**Comment by killerxhp** [comment]
> 要不更新一下再试试？你用的版本已经很旧

为啥我点更新之后没反应呢

**Comment by status102** [comment]
> > 要不更新一下再试试？你用的版本已经很旧
> 
> 为啥我点更新之后没反应呢

直接下载最新版，复制Config文件夹过去

**Comment by killerxhp** [comment]
> > > 要不更新一下再试试？你用的版本已经很旧
> > 
> > 
> > 为啥我点更新之后没反应呢
> 
> 直接下载最新版，复制Config文件夹过去

好的 感谢 再问下 有办法双开 我号多0.0

**Comment by killerxhp** [comment]
> > > 草，我才看见，510beta2，这修个毛啊
> > 
> > 
> > 咋了 我是之前更新之后 有次maa死活连上不上模拟器 然后我就 找到很久之前版本用的 就可以了 然后没就更新过
> 
> 因为这期间的bug修复太多了

好的 感谢 再问下有办法双开吗0.0

**Comment by ABA2396** [comment]
复制一个文件夹

**Comment by killerxhp** [comment]
> 复制一个文件夹

那咋识别另一个模拟器 我之前也是这样操作的 结果互相冲突导致失败

**Comment by ABA2396** [comment]
文档里都写很清楚了。你要多开就不能自己填连接地址？
