### ISSUE TITLE
adb connect 回应固定为无法解析

### ISSUE THREAD

**Issue by Manicsteiner** [MaaAssistantArknights/MaaAssistantArknights#10595]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

#10571 

Android SDK Platform-Tools 35.0.2 所有已连接设备 执行 adb connect 均返回 cannot resolve，不含 connected 或 device

### Version

UI Version: v5.6.1-alpha.1.d070.g389ce2d5f
Core Version: v5.6.1-alpha.1.d070.g389ce2d5f
Build Time: 2024/9/12 21:52:03

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/16987262/gui.log)
[asst.log](https://github.com/user-attachments/files/16987264/asst.log)

### 配置信息

下图，依次为 redmi k60， huawei kirin659上古机型， AVD 35.1.20

### 截图或录屏

![图片](https://github.com/user-attachments/assets/e328688c-f664-44ed-ae5a-3a33e9dbdee8)
![图片](https://github.com/user-attachments/assets/ed2de551-6a9d-4456-82a3-a334ca52e0e6)
![图片](https://github.com/user-attachments/assets/822b69ec-05a0-48b2-913d-31053205c7b7)
![图片](https://github.com/user-attachments/assets/eb9ab1da-4d47-4a34-b9b4-a6f554eda904)

**Comment by Manicsteiner** [comment]
进行了紧张刺激的更换adb版本和MAA/MAACore混用测试，初步认定为 src/MaaCore/Controller/AdbController.cpp 764行修改造成的问题

**Comment by ABA2396** [comment]
![Screenshot_2024-09-13-10-08-05-509_com.github.android-edit.jpg](https://github.com/user-attachments/assets/b1859e02-7bad-458c-a701-f95f937f311a)

草，那这里怎么判断成功

**Comment by ABA2396** [comment]
按原来的逻辑，如果是计算机机器拒绝也会继续走下面的流程。

**Comment by Manicsteiner** [comment]
~~优质解答：我不知道~~
以前问gpt给的方案：
```bash
adb devices > devices.txt
findstr /C:"emulator-5554" devices.txt | findstr /C:"device" > nul
if %errorlevel%==0 (
    echo 设备已连接
) else (
    echo 设备未连接
)
del devices.txt
```
[startupAVD.bat.txt](https://github.com/user-attachments/files/16987692/startupAVD.bat.txt)

**Comment by ABA2396** [comment]
好像有道理，再起个devices命令看看返回有没有device就好了，但还得切一下换行和对比设备名）

**Comment by TimCrownie** [comment]
我还在想为啥一直连不上，都准备写issue了
还好多看了一眼issues（
