### ISSUE TITLE
【TODO】肉鸽新干员招募适配、旧作战策略优化

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#10596]
### 欢迎指出你发现的招募选择不合理、部署不合理、可避免的漏怪等问题
尽量带上截屏或录屏哦

## 水月

![image](https://github.com/user-attachments/assets/d6fa7d03-956f-420a-931a-9d0e47884c3a)

## 萨米
求敌得敌：ew适配
乐理之灾：部署与撤退的condition重合
违和：郁金香宝宝会把挡路箱子拆了
事不过四：31应该朝下
度假村冤魂 ew朝上

**Comment by Daydreamer114** [comment]
求敌得敌
乐理之灾，部署与撤退的condition重合

**Comment by Daydreamer114** [comment]
key 干员的范围应该增大

**Comment by 2352719595** [comment]
干员招募的时候，在没有合适的招募干员时，不会去选择招募临时干员，

**Comment by wuuser95** [comment]
违和：队伍里副输出站位优化一下，可以先对站桩大哥造成伤害，否则精一ew的站位处理不掉
