### ISSUE TITLE
肉鸽当拥有干员超过8个时（有三列干员的时候）不会主动选择第三列及之后的干员

### ISSUE THREAD

**Issue by FindNoWay** [MaaAssistantArknights/MaaAssistantArknights#1059]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9032611/asst.log)

**Comment by MistEO** [comment]
v4.1.0-beta.4 fixed

**Comment by MistEO** [comment]
v4.1.0 fixed
