### ISSUE TITLE
日服生息演算使用有存档刷荧光棒方案会卡在这个界面

### ISSUE THREAD

**Issue by Argonautes0607** [MaaAssistantArknights/MaaAssistantArknights#10607]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

用起来基本正常，就是在载入之前天数的存档确认时会卡住，手动点会继续进行，刷的差不多了，还是来反馈下

### Version

v5.6.0（514）

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17001512/asst.log)

### 配置信息

Mac os 14.5 playcover

### 截图或录屏

<img width="1590" alt="截屏2024-09-14 15 58 22" src="https://github.com/user-attachments/assets/fc0d67a5-1a3f-4d80-b7d4-92c64c98f463">

**Comment by Alan-Charred** [comment]
您好，感谢您的反馈！日/韩服在加载存档时会弹出警告提示框，而这个在国服是没有的。
@Manicsteiner 老师已经在 #10498 修复了这个问题，似乎正好是在 5.6.0 之后 merge 的，所以没有出现在您现在使用的 MAA 版本中。下个版本这个修复就会生效。
