### ISSUE TITLE
水月肉鸽有大量希望, 还是一直选预备干员

### ISSUE THREAD

**Issue by kayiu131** [MaaAssistantArknights/MaaAssistantArknights#10611]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

水月肉鸽有20希望以上, 明明有大量6星可选项, 本来的输出位都已精二, 还是一直选3星预备干员
但萨米肉鸽的选角一切正常

另外可上场干员数量一旦大于8, 永远只能上8位
一样只有水月有这个情况

### Version

Resource Version: 爍塵煙中
Resource Time: 2024/9/5 16:42:23
UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17002965/asst.log)
[gui.log](https://github.com/user-attachments/files/17002966/gui.log)
[gui.json](https://github.com/user-attachments/files/17002969/gui.json)

### 配置信息

MUMU 12 
2560*1440 (DPI 360)
60幀

**Comment by Daydreamer114** [comment]
你的asst.log为空

**Comment by kayiu131** [comment]
> 你的asst.log为空

那可能我今天再挂一个通宵再放上来吧......因为挺常见, 昨天不知道为什么文件没有了

**Comment by kayiu131** [comment]
[asst.bak.log](https://github.com/user-attachments/files/17004319/asst.bak.log)
重新上载一次asst.log
我不知道是不是水月负面buff导致的选角问题

**Comment by shikakihuso** [comment]
日志我没太看懂，但是我有一个推测：
水月肉鸽的阵容完备度要求很高，你在前10次招募达成了半队阵容完备的要求但是没达成全部阵容完备，然后抓券特别不顺利导致你的六星干员全部不在白名单（key）上，所以它就会一直选预备干员

**Comment by kayiu131** [comment]
> 日志我没太看懂，但是我有一个推测： 水月肉鸽的阵容完备度要求很高，你在前10次招募达成了半队阵容完备的要求但是没达成全部阵容完备，然后抓券特别不顺利导致你的六星干员全部不在白名单（key）上，所以它就会一直选预备干员

我挂了一晚上, 自己通关了两次, 但我看通关的两次, 他都是可以带满干员打的
但是很多时候有6星不选, 有6星不精二, 我自己有看过recruitment, 明明很多6星的干员的priority是比其他4-5星高, 但它经常大量希望自己拿4星-5星, 由其爱拿阿米娅当术师, 但明明龙羊的priority更高....
这个选角逻辑是受其他问题影响吗? 因为真的一把都没拿到龙羊, 很奇怪

**Comment by shikakihuso** [comment]
> > 日志我没太看懂，但是我有一个推测： 水月肉鸽的阵容完备度要求很高，你在前10次招募达成了半队阵容完备的要求但是没达成全部阵容完备，然后抓券特别不顺利导致你的六星干员全部不在白名单（key）上，所以它就会一直选预备干员
> 
> 我挂了一晚上, 自己通关了两次, 但我看通关的两次, 他都是可以带满干员打的 但是很多时候有6星不选, 有6星不精二, 我自己有看过recruitment, 明明很多6星的干员的priority是比其他4-5星高, 但它经常大量希望自己拿4星-5星, 尤其爱拿阿米娅当术师, 但明明龙羊的priority更高.... 这个选角逻辑是受其他问题影响吗? 因为真的一把都没拿到龙羊, 很奇怪

阿米娅是老问题了，小羊是压根没给白名单。你可以等低练适配，或者到#10573里把这个测试版的低练文件替换了试试，可能会好一点

**Comment by Daydreamer114** [comment]
<img width="570" alt="66302ff9ad625b349bcb777886a38555" src="https://github.com/user-attachments/assets/bb57f4df-b985-4d20-984e-783317b5b614">

没有细看，初步怀疑你的预备干员被识别为了临时招募干员；或cpp代码出现问题，将临时招募权重给了预备干员

<img width="680" alt="截屏2024-09-15 14 39 36" src="https://github.com/user-attachments/assets/ce086f1b-ce8c-42a1-9345-0ac2070fd386">
<img width="665" alt="截屏2024-09-15 14 40 40" src="https://github.com/user-attachments/assets/57f0a3af-19d7-4caf-9acb-03cc41cbfa76">
<img width="581" alt="截屏2024-09-15 14 42 08" src="https://github.com/user-attachments/assets/85236c7f-ce3b-4318-abbe-e8c151194bcb">
<img width="540" alt="截屏2024-09-15 14 43 18" src="https://github.com/user-attachments/assets/550d275d-f450-493c-81ba-d6db85233a49">
<img width="321" alt="截屏2024-09-15 14 43 56" src="https://github.com/user-attachments/assets/091ae5f5-2ff7-47f5-aecd-ad7d3ab65b8a">

**Comment by Daydreamer114** [comment]
水月的优先级，阿米娅就是高于龙羊的

**Comment by kayiu131** [comment]
> <img alt="66302ff9ad625b349bcb777886a38555" width="570" src="https://private-user-images.githubusercontent.com/74444214/367563603-bb57f4df-b985-4d20-984e-783317b5b614.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDgwMzksIm5iZiI6MTcyNjQwNzczOSwicGF0aCI6Ii83NDQ0NDIxNC8zNjc1NjM2MDMtYmI1N2Y0ZGYtYjk4NS00ZDIwLTk4NGUtNzgzMzE3YjViNjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzNDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NzU5MThjZDUxNmNjNWJlZTk1Y2ZkMjhjNTRhYjg2NzE0ZjM4YjAzZTRjMDM2Mzk0NTMwMTJjMDk2YzYzNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GWlCDT9wcRui0cQXqm__v9zI1v1nL9XrFfnkqqumZ9Y">
> 没有细看，初步怀疑你的预备干员被识别为了临时招募干员；或cpp代码出现问题，将临时招募权重给了预备干员
> 
> <img alt="截屏2024-09-15 14 39 36" width="680" src="https://private-user-images.githubusercontent.com/74444214/367563851-ce086f1b-ce8c-42a1-9345-0ac2070fd386.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDgwMzksIm5iZiI6MTcyNjQwNzczOSwicGF0aCI6Ii83NDQ0NDIxNC8zNjc1NjM4NTEtY2UwODZmMWItY2U4Yy00MmExLTkzNDUtMGFjMjA3MGZkMzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzNDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNmY3NGJmZmFjNjlhYzM4MTYxYTY2MzU3MmM2NjQ3Y2ZlMzkxODlkNTNhZjVmNTNjOTYxMWRlY2QyMGJjOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yidb3zhOQ4T99itApgSBt_gQ8jbeJsbMRYwmbi9sWuA"> <img alt="截屏2024-09-15 14 40 40" width="665" src="https://private-user-images.githubusercontent.com/74444214/367563890-57f0a3af-19d7-4caf-9acb-03cc41cbfa76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDgwMzksIm5iZiI6MTcyNjQwNzczOSwicGF0aCI6Ii83NDQ0NDIxNC8zNjc1NjM4OTAtNTdmMGEzYWYtMTlkNy00Y2FmLTlhY2ItMDNjYzQxY2JmYTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzNDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZGVjY2U5MmM2MzVlMjY3ODQzYWUwODU3YTJjZGI0YmZkNGJjZmFhOWFmYWNhMTRjZThhMmQ3NmMwZTE1OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L5OzP4BBlsH6tTHdtupfvBIdPj4kfymK237QwNkhGkc"> <img alt="截屏2024-09-15 14 42 08" width="581" src="https://private-user-images.githubusercontent.com/74444214/367563959-85236c7f-ce3b-4318-abbe-e8c151194bcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDgwMzksIm5iZiI6MTcyNjQwNzczOSwicGF0aCI6Ii83NDQ0NDIxNC8zNjc1NjM5NTktODUyMzZjN2YtY2UzYi00MzE4LWFiYmUtZThjMTUxMTk0YmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzNDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MzFhY2Q5NTIyMmU0YjFkMDE0MTkxMzQ1NDY3ZTllY2U5NDJiNDU2OTg3ZDNhNjEzZjJjNDg2NWJiZGI3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iFDqAfaC6xpGx2o8i54UxJquqtu336wbto6C4bjXFPE"> <img alt="截屏2024-09-15 14 43 18" width="540" src="https://private-user-images.githubusercontent.com/74444214/367564018-550d275d-f450-493c-81ba-d6db85233a49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDgwMzksIm5iZiI6MTcyNjQwNzczOSwicGF0aCI6Ii83NDQ0NDIxNC8zNjc1NjQwMTgtNTUwZDI3NWQtZjQ1MC00OTNjLTgxYmEtZDZkYjg1MjMzYTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzNDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OTk3MjVlZDA4NTgxYjIwNjI2YTBiZmViMzM5Y2U5ZWE0OGE0OWU1NGJmZjAwNjUyYWI1NzFhNTVmZjFhY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LDndzUK1oO6WlAHQ15ZGvcvdf58xw5TYpzilbFcEHsk"> <img alt="截屏2024-09-15 14 43 56" width="321" src="https://private-user-images.githubusercontent.com/74444214/367564044-091ae5f5-2ff7-47f5-aecd-ad7d3ab65b8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDgwMzksIm5iZiI6MTcyNjQwNzczOSwicGF0aCI6Ii83NDQ0NDIxNC8zNjc1NjQwNDQtMDkxYWU1ZjUtMmZmNy00N2Y1LWFlY2QtYWQ3ZDNhYjY1YjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzNDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZjU0Yzc4Zjk5NzIxMGVjNjAzYzk5YmZlZjZkZTY5NjlkMmRkOTJjZjBmNDljZmIzMTU0MGMwMzU5YjZiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.279Fn_HgSC0WEI1Vc3OFzOu1aijD3r18np4x6FOheEs">

这种情况是个例子还是本来设定就是这样？ 
需要等更新，还是我自己可以修改？
