### ISSUE TITLE
公招同时出现4星和5星词条时选择了四星词条

### ISSUE THREAD

**Issue by yhzl1707** [MaaAssistantArknights/MaaAssistantArknights#1061]
泪目了
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9032659/asst.log)
![QQ图片20220702162815](https://user-images.githubusercontent.com/108570169/176993139-06ad020c-0b35-4dcb-889e-909d287a9efa.png)

**Comment by yhzl1707** [comment]
用的夜神模拟器

**Comment by MistEO** [comment]
![Screenshot_2022-07-02-16-51-30-665_com.android.chrome.jpg](https://user-images.githubusercontent.com/18511905/176993819-94a4acb4-5e6f-4071-854d-f125b4c992cc.jpg)

这也是五星（

**Comment by yhzl1707** [comment]
群主对不起我是傻逼呜呜
