### ISSUE TITLE
干员ocr识别错误

### ISSUE THREAD

**Issue by B11215058** [MaaAssistantArknights/MaaAssistantArknights#10617]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

琳瑯施懷雅基建無法被選中(台服)

### Version

v5.6.0

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17005292/asst.log)
[gui.log](https://github.com/user-attachments/files/17005293/gui.log)
2024-09-15 14:08:32.232

### 配置信息

Windows 10 家用版22H2,雷電1920*1080 320dpi 60fps
 GPU 加速推理關閉

**Comment by Manicsteiner** [comment]
![图片](https://github.com/user-attachments/assets/a3308f08-82ca-4ef1-af62-02d25141bb2b)
其实是有替换规则的，只是异格前干员的替换规则没有匹配限制。大概可以盲改
