### ISSUE TITLE
肉鸽 第三关boss大盗当头每隔1s就选中干员一次。

### ISSUE THREAD

**Issue by miduoli** [MaaAssistantArknights/MaaAssistantArknights#1062]
![N)@$W~U@C`3G_G1AR{6~$FU](https://user-images.githubusercontent.com/82594386/177000276-69a8cbad-35c8-4d2f-8cea-2cec0538492e.png)
如图会一直选中调香师，用的逍遥模拟器。如果没有调香师，则会一直选中安塞尔。
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9033006/asst.zip)

**Comment by zzyyyl** [comment]
#1195
