### ISSUE TITLE
更新5.6.1后, adb-lite的连接模式炸了

### ISSUE THREAD

**Issue by yyjdelete** [MaaAssistantArknights/MaaAssistantArknights#10622]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

我也忘了之前是为啥开着adb-lite了, 我只是来报告下这个东西炸了
这个选项在连接设置那里, 触控模式下面, 不开是能正常工作的(测试的时候注意下切换开关需要重启MAA)
上一个正式版(5.6.0)是正常的

界面上的提示是: 
`触控模式不可用。请进入 设置 - 连接设置 切换其他触控模式。` 
`连接失败 请检查连接设置或尝试重启模拟器与 ADB 或重启电脑`

### Version

5.6.1
2024/09/11 00:45:21
2024/09/15 22:30:48

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17008183/asst.log)
[gui.log](https://github.com/user-attachments/files/17008184/gui.log)

### 配置信息

Win11 preview(27695)
MuMu 4.0.7，截图增强开启；

**Comment by Faultiness** [comment]
遇到相同问题，使用maatouch时报错TouchModeNotAvaiable
环境：M2 mac 13.6 + mumu 1.4.46 + maa 5.6.1

**Comment by Fan-SJ** [comment]
遇到相同问题，使用maatouch时报错TouchModeNotAvaiable， 其他touch也是
环境：M3 14.5 (23F79) + mumu 1.4.11 + maa 5.6.1

**Comment by ABA2396** [comment]
没太看懂啥原因，但是开关一下lite又能用了

**Comment by ABA2396** [comment]
找到问题了，有点抽象，adb lite好像必须要connect一下才能设置serial，等下改改

**Comment by ABA2396** [comment]
d2040d33284d80cc81b0fccca0c17e8cba306175 fixed
