### ISSUE TITLE
肉鸽中涧三技能释放

### ISSUE THREAD

**Issue by wy17783438734** [MaaAssistantArknights/MaaAssistantArknights#10621]
### 说说你遇到的问题？

挂肉鸽时，涧技能好了就会自动释放，但是很多时候范围内又没有敌人放不出来，导致会一直尝试释放技能，使得过一关的时间及其长，同理还有逻各斯的一技能，不知有没有解决办法，望后续能优化技能释放

**Comment by status102** [comment]
缺少版本等其他信息，issue相关内容近期有改动
