### ISSUE TITLE
macOS 15 iPhone Mirroring 支持

### ISSUE THREAD

**Issue by Trccc** [MaaAssistantArknights/MaaAssistantArknights#10637]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

我是一个iOS，macos用户，最近macos正式推送了 Sequoia 15.0， 一个重要的更新就是iPhone mirror，简单的来说就是在macos上镜像iPhone，也就是可以在macOS上玩粥了，效果图如下，不知道这个对MAA之后的开发会不会有影响，之后有可能会增加这个的支持吗。效果图如下
<img width="716" alt="Screenshot 2024-09-17 at 13 15 39" src="https://github.com/user-attachments/assets/3f90d881-9d2d-4474-88ec-4b76aeb9b468">

**Comment by Constrat** [comment]
Pretty sure that not a valid resolution 16:9 since there are the black bars. Currently macOS is not even that much updated, so I really don't think this will be adapted any time soon unfortunately. Not enough mac / iOS developers.

**Comment by Rbqwow** [comment]
MAA 至今都是完全基于 ADB 实现的，现在看来大家貌似都没啥搞新轮子的兴趣
之前上架 MacOS 时也讨论过要不要搞个原生支持，然后不了了之了
~~所以说为啥非要在苹果那堆玩意上玩游戏啊~~

**Comment by Trccc** [comment]
> MAA 至今都是完全基于 ADB 实现的，现在看来大家貌似都没啥搞新轮子的兴趣 之前上架 MacOS 时也讨论过要不要搞个原生支持，然后不了了之了 ~所以说为啥非要在苹果那堆玩意上玩游戏啊~

在国外学的cs，所有东西都是苹果的，但是还想玩国内的游戏- -

**Comment by BrandenXia** [comment]
> MAA 至今都是完全基于 ADB 实现的，现在看来大家貌似都没啥搞新轮子的兴趣 之前上架 MacOS 时也讨论过要不要搞个原生支持，然后不了了之了 ~所以说为啥非要在苹果那堆玩意上玩游戏啊~

https://maa.plus/docs/zh-cn/manual/device/macos.html
之前看到有playcover的支持，这个不是基于 adb 实现的吧

**Comment by Constrat** [comment]
Completely different things.

**Comment by SherkeyXD** [comment]
看起来并不会暴露 adb 端口

**Comment by wangl-cc** [comment]
我个人的体验来说 iPhone Mirroring 的延迟有点严重，我觉得即使能够实现，也很难说有多好的效果。况且目前由于缺乏 ADB 或者 PlayTools 这样的类似的截图和触控借口，想要实现的难度是非常大的。如果是想在 Apple Silicon Mac 上使用 MAA，我认为PlayCover 客户端，MuMuPro，AVD 都是更好的选择。即使是 Intel Mac，我觉得跑个旧版的 MuMu 也比这个好。
