### ISSUE TITLE
WpfGui设置项修改

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#10639]
### 说说你遇到的问题？

![image](https://github.com/user-attachments/assets/aac4ed82-91d2-42dd-a842-94ab1c32a0e2)

（以下选项包含在连接设置
![image](https://github.com/user-attachments/assets/9e5da186-447b-46e8-927f-b80dd42f7358)
![image](https://github.com/user-attachments/assets/1512f138-f2ad-424b-a8e1-fc5f9467fb7a)

打算重构Config的时候把这些放一起，然后改个名。GPT起了个ExecutionSettings（
连接设置那几个有点和连接关系不大了

cc @MaaAssistantArknights/wpfgui-developers

**Comment by ABA2396** [comment]
客户端类型在开始唤醒里有，我感觉去掉也行，或者把掉线重连、划火柴什么的也放游戏设置里

**Comment by status102** [comment]
> 客户端类型在开始唤醒里有，我感觉去掉也行

closeDown任务也要传客户端类型

**Comment by ABA2396** [comment]
如果选了 closeDown 的时候如果没选就弹窗提示好了，和 adb 连接失败启动模拟器 的选项一样

**Comment by status102** [comment]
那adb地址也改到开始唤醒里面么，那些也是两边都有

**Comment by ABA2396** [comment]
连接设置还是放设置里吧，反正第一次开教程会设置一次，这玩意也不是经常改的

**Comment by status102** [comment]
那就是游戏设置下面放这些

![image](https://github.com/user-attachments/assets/a75d0479-ae86-4b88-9d37-9315309f51ff)
