### ISSUE TITLE
萨卡兹肉鸽卡在节点界面

### ISSUE THREAD

**Issue by TacLoky** [MaaAssistantArknights/MaaAssistantArknights#10642]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

卡在节点界面最右边，需要手动向左划动才能识别到对应节点，从而继续任务

### Version

UI Version: v5.6.2
Core Version: v5.6.2
Build Time: 2024/9/16 16:44:25

### 日志和配置文件

[debug.zip](https://github.com/user-attachments/files/17052178/debug.zip)

### 配置信息

MUMU12 1280x720 挂机15fps win10 未开启 未开启 3080

### 截图或录屏

![QQ截图20240919091745](https://github.com/user-attachments/assets/791ec02a-52d3-4b9e-a287-1e05582fb191)

**Comment by Daydreamer114** [comment]
这是一个方舟的偶发bug
你可以试试把帧率固定到60帧，这也是maa要求的帧数

**Comment by Daydreamer114** [comment]
改为60帧后还有这个情况吗？

**Comment by TacLoky** [comment]
> 改为60帧后还有这个情况吗？

目前没有
