### ISSUE TITLE
肉鸽第一层刷源石碇策略，无法投资后依旧会继续购买其他物品而不是直接退出

### ISSUE THREAD

**Issue by MigdalBavel** [MaaAssistantArknights/MaaAssistantArknights#1065]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9033781/asst.log)

**Comment by ABA2396** [comment]
算是特性吧.jpg
之前是没购买物品的，但是有人提出要开图签，别浪费源石锭才加上的

**Comment by MistEO** [comment]
顺手刷收藏品的
