### ISSUE TITLE
MAA退出后会重置设置

### ISSUE THREAD

**Issue by offical-HYC** [MaaAssistantArknights/MaaAssistantArknights#10654]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

退出MAA再次打开后，包括“一键长草”的勾选以及绝大部分设置的勾选都会重置成初始状态（取消勾选）

### Version

Resource Version: 泰拉饭
Resource Time: 2024/9/16 04:04:19
UI Version: v5.6.2
Core Version: v5.6.2
Build Time: 2024/9/16 16:44:25

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17083536/asst.log)
[gui.log](https://github.com/user-attachments/files/17083537/gui.log)
[gui.json](https://github.com/user-attachments/files/17083541/gui.json)

### 配置信息

Win 11
其他的好像跟这个没关系不填了

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/f8fd7242-35c8-4b85-a803-4909a5112404)
没有文件的写入权限，要么换个文件夹，要么给提高软件权限

**Comment by offical-HYC** [comment]
好的 已解决 应该是将文件夹中的文件设置为“隐藏”的问题 感谢
