### ISSUE TITLE
SSSCopilot 选择干员后又取消选中

### ISSUE THREAD

**Issue by Jackhr-arch** [MaaAssistantArknights/MaaAssistantArknights#10650]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

使用内置的`SSS_交战荒野_澄闪+塞雷娅+纯烬艾雅法拉or流明+重岳or水月or阿斯卡纶_皇家科学院望远镜.json`时，启动SSSCopilot，则
- 不会选择战术装备（直接点击下一步）
- 不会选择更改阵容（直接点击下一步）
- 手动干预到“快捷编队”界面时，重复点击第一排左起第二个干员

### Version

maa 0.4.12
来自[这个release](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v5.6.2)的`MAA-v5.6.2-linux-x86_64.tar.gz`

### 日志和配置文件

之后提供

### 配置信息

Debian 12 Wayroid 1080x720

**Comment by Jackhr-arch** [comment]
[asst.log](https://github.com/user-attachments/files/17078582/asst.log)

**Comment by Jackhr-arch** [comment]
外部工具截图
![截图 2024-09-21 01-19-12](https://github.com/user-attachments/assets/a2d9a302-6cce-4e18-bdb7-712bb82a7341)
MAA截图
![术法冲锋](https://github.com/user-attachments/assets/0d2ef0a6-942d-4bbf-9db5-9a33c583443c)

**Comment by status102** [comment]
![image](https://github.com/user-attachments/assets/24b08c45-c305-485f-a372-861eb7be39ec)
