### ISSUE TITLE
台服傀影肉鸽打通关, 不会自己skip结算重新开始

### ISSUE THREAD

**Issue by kayiu131** [MaaAssistantArknights/MaaAssistantArknights#10661]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

如题, 打通关后不会自己skip掉剧情, 直接卡在那个画面不动, 但如果是失败是会自己跳剧情

### Version

Resource Version: 爍塵煙中
Resource Time: 2024/9/8 18:05:05
UI Version: v5.6.2
Core Version: v5.6.2
Build Time: 2024/9/16 16:44:25

### 日志和配置文件

file太大压缩完 zip file不支援上载

### 配置信息

MUMU 12
2560*1440 (DPI 360)
60幀

**Comment by status102** [comment]
没有log无法诊断
