### ISSUE TITLE
更改 设置-连接地址 貌似不会影响 一键长草-开始唤醒-连接地址

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#10665]
### 说说你遇到的问题？

调整完 设置-连接地址，在调整mumu截图增强的实例编号至新地址对应的模拟器后。可以正常识别，但是无法点击；
手动调整 一键长草-开始唤醒-连接地址 后可正常运行

**Comment by HoshinoAyako** [comment]
我记得是一样的。无论改哪个都会同步改的。
改动后，点下截图测试，看屏幕实际对上没。
