### ISSUE TITLE
mumu12模拟器连接失败

### ISSUE THREAD

**Issue by zjc19980122ss** [MaaAssistantArknights/MaaAssistantArknights#10667]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

中秋节的时候使用正常，后续几天没有使用，今天清临期体力的时候发现maa无法连接了。尝试重新安装maa、重新下载adb、重启电脑都没有解决。提示连接adb失败，但是终端直接执行abd connect 127.0.0.1:16384提示成功，实在不知道啥情况

### Version

5.6.2

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17090578/asst.log)
[gui.json](https://github.com/user-attachments/files/17090579/gui.json)
[gui.log](https://github.com/user-attachments/files/17090581/gui.log)
maa是我出了问题之后重新安装的，后面一直在尝试重新连接，全部失败。

### 配置信息

操作系统：windows10家庭版22H2
模拟器：mumu12
分辨率：1280*720(DPI 240)
帧率：60
截图增强未开启，GPU加速推理未开启

**Comment by ABA2396** [comment]
你这 adb 的端口怎么都不是 5037 ，有自己改过环境变量吗？
![image](https://github.com/user-attachments/assets/6b9c771e-3196-49c1-82fb-73633322bc16)
看看有没有别的软件也起了个 adb 然后冲突了

**Comment by zjc19980122ss** [comment]
是的，我之前做别的配置的时候为避免冲突手动在环境变量里设置了adb的端口为24678，没有使用默认的端口号。
我关掉模拟器和maa后adb的进程没有结束，是否说明有其他应用占用了adb进程，有什么方法可以确认吗？我重启电脑后只打开了模拟器和maa，没有再打开其他的软件。

**Comment by zjc19980122ss** [comment]
…误操作关闭issue了，重开一下

**Comment by ABA2396** [comment]
adb lite现在还不支持非5037端口，不过我看日志里只有中间一段有，现在应该没开吧

**Comment by zjc19980122ss** [comment]
是的，之前连不上我试了lite+三种触控模式的组合发现都不行，开了lite的重试时间也比较长，后面就没有开lite模式了
