### ISSUE TITLE
水月肉鸽 点开关卡地图之后没有正常关闭，导致一直卡在那

### ISSUE THREAD

**Issue by ReimsWwW** [MaaAssistantArknights/MaaAssistantArknights#10662]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [x] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

扫了一眼前两页没看见一样post。 
如题，点开关卡地图之后不关，导致在那里卡住，多发生在险路恶敌。

### Version

Resource Version: 泰拉饭
Resource Time: 2024/9/15 16:04:19

UI Version: v5.6.2
Core Version: v5.6.2
Build Time: 2024/9/16 04:44:25

### 日志和配置文件

[log.zip](https://github.com/user-attachments/files/17088111/log.zip)
[gui.json](https://github.com/user-attachments/files/17088112/gui.json)

### 配置信息

蓝叠国际版
加速推理 RTX4070 

### 还有别的吗？

顺便一提……刚才在贴吧刷到了个贴，标题"是明日方舟离不开maa"，配图直接把不让到处发的那个长期公告拍上去了。看到之后人麻了

**Comment by ReimsWwW** [comment]
仔细挨个看了一遍，发现有别的标题的相同bug了。听说在todo list 了……

**Comment by Daydreamer114** [comment]
具体bug是会跳过一个节点去点险路恶敌，这个是已知；没人修
