### ISSUE TITLE
[日服]萨米肉鸽刷源石锭卡在结算画面

### ISSUE THREAD

**Issue by Crimson-Veluriyam** [MaaAssistantArknights/MaaAssistantArknights#10668]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

按放弃本次探索后，卡在结算画面

### Version

UI Version: v5.6.2
Core Version: v5.6.2
Build Time: 2024/9/16 16:44:25

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17091897/asst.log)
[gui.log](https://github.com/user-attachments/files/17091899/gui.log)
[gui.json](https://github.com/user-attachments/files/17091902/gui.json)

### 配置信息

WIN10，雷电模拟器v9.0.69，1600*900，dpi240

### 截图或录屏

![image](https://github.com/user-attachments/assets/613171f7-01a0-408c-9083-f16be1d3f464)
![OB%OR %8)U{%W)SUS 4X2FR](https://github.com/user-attachments/assets/f7db0155-86d5-43e0-8edc-bb63ccf5c6c8)

**Comment by Daydreamer114** [comment]
这是你模拟器自带工具截的图？那就跟maa没关系了

**Comment by Crimson-Veluriyam** [comment]
@Daydreamer114  请问是什么意思？

**Comment by Daydreamer114** [comment]
maa需要识别风雪蔽目这四个字的位置，但你那连分数都没有

**Comment by Manicsteiner** [comment]
在gui.json中找到的萨米肉鸽投资似乎都是只运行一次就结束了的，水月肉鸽倒是能正常运行
上次改动日服肉鸽还是 v5.5.11452，移除了`resource/global/YostarJP/resource/template/Sami@Roguelike@MissionFailedFlag2.png`，改为直接使用国服版本，如果是手动解压了更新包可能不会移除这个文件，请查看一下
