### ISSUE TITLE
希望加入自动刷关的脚本开发

### ISSUE THREAD

**Issue by RoeeXu** [MaaAssistantArknights/MaaAssistantArknights#1066]
我有诸多小号，每次活动，刷全关卡就挺费时间

想要借强大的MAA来一劳永逸

所以，如何加入“自动战斗 Beta”的开发组（脚本组）呢，求大佬告知

**Comment by ABA2396** [comment]
你加作业群了吗？在 `设置` - `关于我们` 里面有个作业分享的Q群链接

**Comment by MistEO** [comment]
https://www.prts.plus/
