### ISSUE TITLE
肉鸽 能不能不要自动买没有的职业干员的书

### ISSUE THREAD

**Issue by qosew34** [MaaAssistantArknights/MaaAssistantArknights#1067]
![YTU9ND0T8V_)XX~2MUZF{$2](https://user-images.githubusercontent.com/108598629/177021420-846441af-775e-491f-a5af-085873762845.png)
![L~A)$VLC3{7HO8C_P1CR08B](https://user-images.githubusercontent.com/108598629/177021429-094286fc-99ee-48eb-9fe1-eb595cf6fd30.png)
看起来有点笨，能不能优先买同价位的别的东西

**Comment by zhongfly** [comment]
自动打肉鸽的主要目的只是完成每月任务、刷源石而已
