### ISSUE TITLE
关于一键长草中自动肉鸽功能消失的问题

### ISSUE THREAD

**Issue by Mistalker** [MaaAssistantArknights/MaaAssistantArknights#10674]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

9/21 在启动MAA后发现自动肉鸽功能消失了。于是去官网重新下载并安装了MAA，自动肉鸽功能仍然没有出现。

### Version

MAA v5.6.2

### 日志和配置文件

没有在mac中搜索到这两个文件诶🤔

### 配置信息

PlayCover 3.0.0.maa.5
mac OS sonoma 14.2
MacBook Pro M3

### 截图或录屏

![WX20240923-141700@2x](https://github.com/user-attachments/assets/7e71e04b-00d4-44c5-b5b7-97c763fdae18)

**Comment by ABA2396** [comment]
cc @hguandl

**Comment by hguandl** [comment]
@Mistalker 点一下右上方工具栏的➕试试，应该能添加回来
