### ISSUE TITLE
minitouch触控模式卡在开始唤醒界面

### ISSUE THREAD

**Issue by Autumn174** [MaaAssistantArknights/MaaAssistantArknights#10687]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

minitouch触控模式卡在开始唤醒界面，其他的两个触控模式都没问题，屏幕大小为1080*1920的竖屏模式（因为要用maa的森空岛签到），开启明日方舟后会自动转变为横屏大小，分辨率如图一所示，在这种情况下会卡在开始唤醒的界面处，如图二，已开启GPU加速及mumu增强截图，
![Screenshot 2024_9_26 12_34_23-1](https://github.com/user-attachments/assets/1542335d-5f1d-45f7-85ce-61ae52227f04)
<img width="699" alt="微信图片_20240926123812" src="https://github.com/user-attachments/assets/69d87614-fe7e-4939-9ee3-5fb455730875">

### Version

UI Version: v5.6.2
Core Version: v5.6.2
Build Time: 2024/9/16 16:44:25
Resource Version: 不义之财 复刻
Resource Time: 2024/9/19 19:04:29

### 日志和配置文件

asst.log的时间是从2024-09-26 12:33:06.757开始
gui.log是从2024-09-26 12:33:04.827开始
[asst.log](https://github.com/user-attachments/files/17142836/asst.log)
[gui.log](https://github.com/user-attachments/files/17142839/gui.log)
[gui.json](https://github.com/user-attachments/files/17142840/gui.json)

### 配置信息

操作系统:win11
模拟器为mumu12
模拟器分辨率为竖屏1080*1920，开明日方舟会自动横屏，横屏后分辨率如图所示
![Screenshot 2024_9_26 12_34_23-1](https://github.com/user-attachments/assets/e2f5a72e-53b6-48f6-9879-5d2dd703a58e)

DPI为480
帧率为60帧
 MuMu 截图增强已经开启
 GPU 加速推理已经开启，GPU为RTX3060laptop

**Comment by Rbqwow** [comment]
试试把分辨率改成16:9而不是9:16
感觉像老问题
