### ISSUE TITLE
勾选不撤离进驻干员后仍撤离逻各斯

### ISSUE THREAD

**Issue by memgkong** [MaaAssistantArknights/MaaAssistantArknights#10682]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/user-attachments/assets/d655eeb9-ab61-43cd-b922-581d50e66eab)
在勾选该选项后仍将正在训练室协助位中的逻各斯撤入宿舍中，正在准备进行技能的专二到专三的专精，但是材料没有提前合成

### Version

Resource Version: 不义之财 复刻
Resource Time: 2024/9/20 01:43:25
UI Version: v5.7.0-beta.1
Core Version: v5.7.0-beta.1
Build Time: 2024/9/21 23:45:47

### 日志和配置文件

大致时间为2024-09-21 22点左右
[debug.zip](https://github.com/user-attachments/files/17113858/debug.zip)
[gui.json](https://github.com/user-attachments/files/17113865/gui.json)

### 配置信息

操作系统：
版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎9/‎12
操作系统版本	22631.4169
体验	Windows Feature Experience Pack 1000.22700.1034.0

MuMu模拟器12，截图增强未开启

GPU加速推理未开启

**Comment by ABA2396** [comment]
日志没存这么久的，只有24号的日志，近期有遇到吗

**Comment by memgkong** [comment]
今天也有个，还没完，再出现问题了我再发今天的日志吧，今天要是没问题我就尽量重现一下出现问题的场景

**Comment by memgkong** [comment]
> 日志没存这么久的，只有24号的日志，近期有遇到吗

今天也有个，还没完，再出现问题了我再发今天的日志吧，今天要是没问题我就尽量重现一下出现问题的场景

**Comment by ABA2396** [comment]
模拟器很卡吗？正常来说只有点了返回没反应一段时间才会点第二次，也可能是点的时候刚好出去了又点了一次，又或者是模拟器截图出问题了返回了之前的图

**Comment by memgkong** [comment]
> 模拟器很卡吗？正常来说只有点了返回没反应一段时间才会点第二次，也可能是点的时候刚好出去了又点了一次，又或者是模拟器截图出问题了返回了之前的图

不卡啊，我看它操作很流畅，这个情况我也经常见，基建任务运行的时候也是经常会退出去重新进然后继续任务

**Comment by ABA2396** [comment]
正常来说退出最多到基建总览页面，不会说退出到主界面再重新进基建

**Comment by memgkong** [comment]
> 正常来说退出最多到基建总览页面，不会说退出到主界面再重新进基建

不知道了，反正这情况我蛮常见的

**Comment by a0wsxz9** [comment]
确实是经常有这样的问题发生，因为最近上号手操频率低了，这个问题就更常见了。以前如果只是专精好隔了一天上操的话，基本不会出问题，现在隔的时间长了，进去一看基本都会被撤掉。😐最少存在2个月了，一直等更新也没见有修复。
