### ISSUE TITLE
"借助战打OF-1赚信用" 数天没有执行

### ISSUE THREAD

**Issue by ReimsWwW** [MaaAssistantArknights/MaaAssistantArknights#10685]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

换了几个关键词搜一溜够没找着相同问题啊，遂新开一post。
如题，访问好友-> 访问商店之后就直接结束阶段了。 中间没有执行接助战打of-1 这个行动。 查看log之后发现上次是21号，更新之后还执行了一次。重新勾选并重启maa之后还是没有恢复执行，仍然是给跳过去了
三开maa，只有其中一个出现这个问题了，其他两个都是每天都有一次。

### Version

UI Version: v5.7.0-beta.1
Core Version: v5.7.0-beta.1
Build Time: 2024/9/21 11:45:47

Resource Version: 不义之财 复刻
Resource Time: 2024/9/19 13:43:25

### 日志和配置文件

[debug.zip](https://github.com/user-attachments/files/17123242/debug.zip)
[gui.json](https://github.com/user-attachments/files/17123246/gui.json)

### 配置信息

win10-22H2 mumu12 1080p 鼠标dpi2000 144帧率 怎么东西越来越多……dpi能影响什么啊
截图增强已开启
GPU加速 不使用

**Comment by ReimsWwW** [comment]
将"刷理智"的"关卡选择"改成了 **非** "当前/上次"的图，然后就能执行助战of1了……是这么个设计的吗？晕了

**Comment by ReimsWwW** [comment]
我还以为看过浮标了……刚想说"浮标里也没写"……行吧……

**Comment by ABA2396** [comment]
dpi说的是模拟器的dpi，不是鼠标的

主要是打完 of-1 之后上次关卡就变成 of-1了，下一个执行 当前/上次 就会跑去刷这玩意了，刷理智任务等于没跑

**Comment by ReimsWwW** [comment]
> dpi说的是模拟器的dpi，不是鼠标的
> 
> 主要是打完 of-1 之后上次关卡就变成 of-1了，下一个执行 当前/上次 就会跑去刷这玩意了，刷理智任务等于没跑

这个我可以改哪个文件自己调吗？有时候我想打的关卡不在列表里面，手动输入也不支持，所以有时候会先放一把录像再开maa。

**Comment by ABA2396** [comment]
既然这样，为什么不手动打一遍of-1，反正这也放一个干员就能挂机了）

**Comment by ABA2396** [comment]
切换上次关卡也不用打完，演戏进去直接退就行了
