### ISSUE TITLE
理智药选择和界面设置建议

### ISSUE THREAD

**Issue by UniMars** [MaaAssistantArknights/MaaAssistantArknights#1069]
1. 理智药选择那里能否增加仅使用快过期的理智药选项，我长草期一般只会在理智药快过期才使用
2. 能否增加关闭窗口时自动最小化到托盘选项，这个选项好像在一些后台应用里面比较常见

**Comment by zzyyyl** [comment]
`关闭窗口时自动最小化到托盘` 现在其实有一个类似的功能是 `最小化时隐藏至托盘`，我觉得后者应该更加适合？

理智药选择的话可能会不做了，毕竟不是大众需求，而且基于现在的理智药逻辑可能做起来比较麻烦（判断一下红色黄色绿色？）。也许你可以在 maa 开始执行任务的时候自己设置理智药个数。
~~还有就是，为什么不早点把理智药用用完呢（？~~
