### ISSUE TITLE
刷理智-不义之财的关卡打开到矢量突破了

### ISSUE THREAD

**Issue by yfeng445** [MaaAssistantArknights/MaaAssistantArknights#10703]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

当自动理智清理选择不义之财复刻中的关卡时, 由于终端左下banner更新导致MAA会打开矢量突破, 然后跳过任务
(不过复刻也马上结束了

### Version

Resource Version: 泰拉饭
Resource Time: 2024/9/15 16:04:19
UI Version: v5.6.2
Core Version: v5.6.2
Build Time: 2024/9/16 04:44:25

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17174398/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17174399/asst.log)
[gui.log](https://github.com/user-attachments/files/17174400/gui.log)
[gui.json](https://github.com/user-attachments/files/17174401/gui.json)

问题出现的时间: 09/28/2024 8:30左右

### 配置信息

操作系统: Windows 11 23H2
模拟器: Mumu模拟器12, 未开启截图增强
GPU加速推理开启, GPU型号: RTX4090

### 还有别的吗？

感谢大佬们的付出!

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/91e37771-56a4-4cce-bdf5-eaa69f23ee71)
这玩意马上就关了，懒得改了 XD

**Comment by hahg2000** [comment]
挂了半天，发现没刷到（捂脸
