### ISSUE TITLE
Stuck on decision vouchers in IS4

### ISSUE THREAD

**Issue by thesadru** [MaaAssistantArknights/MaaAssistantArknights#10704]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I am using the latest version of the current update and have reviewed both the updates released so far and the unreleased changes in the Pull Requests, there is no mention of the bug being fixed.
- [X] I have reviewed the Pinned issue (Announcements), Open issues, and Closed issues to ensure that my issue has not been mentioned.

### Description

When playing IS4 (集成战略 #4「探索者的银凇止境」) and selecting a decision voucher, the game gets stuck and chooses to abandon the run.

This does not happen with foldartals (密文板).

### Version

v5.7.0-beta.1

### Log and config files

[asst.log](https://github.com/user-attachments/files/17176826/asst.log)
[gui.log](https://github.com/user-attachments/files/17176827/gui.log)
[gui.json](https://github.com/user-attachments/files/17176828/gui.json)

local time: ~2024-09-29 00:58, 2024-09-29 00:34, ...

### Configuration information

Windows 11, Bluestacks 5 Hyper-V 1280x720, 60fps

### Screenshots or recordings

![image](https://github.com/user-attachments/assets/7708c222-26a0-43a8-99ba-5dd6facc1e39)

### Anthing else?

I greatly appreciate the work the developers do 🙇‍♀️.

**Comment by Constrat** [comment]
> `1280x720`
Please use `1920x1080` as stated in the FAQ
