### ISSUE TITLE
公招识别没勾自动设置时间还是会点9小时

### ISSUE THREAD

**Issue by zm873502894** [MaaAssistantArknights/MaaAssistantArknights#1070]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9034816/asst.log)
![屏幕截图 2022-07-03 210031](https://user-images.githubusercontent.com/87477693/177041105-50560dea-36ec-4a97-af94-6457f10fe6ed.jpg)
MUmu模拟器

**Comment by zzyyyl** [comment]
不是 bug，是特性（
