### ISSUE TITLE
希望增加自动点击登录功能

### ISSUE THREAD

**Issue by tsctsc6** [MaaAssistantArknights/MaaAssistantArknights#1072]
希望在LinkStart后，执行任务前，自动点击登录并执行任务
可以做成一个可选项

**Comment by ABA2396** [comment]
能具体点什么功能么
如果是要点击开始唤醒进游戏的话 `开始唤醒`选项就是这个功能
如果在设置里勾选了启动后直接运行和自动打开模拟器并选择了客户端版本，那启动maa后会自动打开游戏并执行任务
现在任务执行失败也是会尝试自动打开游戏重新登录

**Comment by tsctsc6** [comment]
原来如此，那没事了
