### ISSUE TITLE
增加自动肉鸽可使用指定角色模式下进行（如月度小队、追忆映射、探索者档案）

### ISSUE THREAD

**Issue by Leo2285na** [MaaAssistantArknights/MaaAssistantArknights#10725]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

肉鸽不能自动打月度小队、追忆映射、探索者档案模式，也不能完成深入调查条件任务，可以考虑完善一下。

**Comment by Saratoga-Official** [comment]
Duplicate of #8866
