### ISSUE TITLE
[global arknight] Can't make the coin deposit for Sami I.S.

### ISSUE THREAD

**Issue by hiew** [MaaAssistantArknights/MaaAssistantArknights#10735]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I am using the latest version of the current update and have reviewed both the updates released so far and the unreleased changes in the Pull Requests, there is no mention of the bug being fixed.
- [X] I have reviewed the Pinned issue (Announcements), Open issues, and Closed issues to ensure that my issue has not been mentioned.

### Description

MAA appears to have clicked on the confirm button for a deposit during the game. But it doesn't work.

### Version

V5.7.0

### Log and config files

[asst.log](https://github.com/user-attachments/files/17265128/asst.log)
[gui.log](https://github.com/user-attachments/files/17265129/gui.log)

### Configuration information

![Screenshot 2024-10-05 141842](https://github.com/user-attachments/assets/9e6b2acf-874a-4377-99a3-647358d65546)
![Screenshot 2024-10-05 140802](https://github.com/user-attachments/assets/33b63894-2c1c-4175-aecf-a1215302f908)![Screenshot 2024-10-05 140648](https://github.com/user-attachments/assets/657c4dad-5da7-4d3e-8ad2-8662480aea6d)

### Screenshots or recordings

![Screenshot 2024-10-05 142031](https://github.com/user-attachments/assets/00981146-3a4b-4d04-ad1b-94aad689dcf6)

https://github.com/user-attachments/assets/fa8684f7-46f7-459d-b269-b27ce155babc

**Comment by Constrat** [comment]
1920x1080.
It's literally written when you change from Official to YostarEN. How is this still an issue.
![image](https://github.com/user-attachments/assets/6866a685-6b6a-4753-98a2-3fa16b0e367e)
![image](https://github.com/user-attachments/assets/6fe9684f-b02c-4386-bc07-85e0e36e4be4)
