### ISSUE TITLE
server酱更新了3.0，希望支持

### ISSUE THREAD

**Issue by fengziyun** [MaaAssistantArknights/MaaAssistantArknights#10737]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

[server酱3官网 https://sc3.ft07.com/](https://sc3.ft07.com/)
官方集成了多个接口，server酱3推送更方便了

**Comment by Yebolin** [comment]
希望直接支持自定义webhook，比绑死这个酱好。

**Comment by icaruszezen** [comment]
+1

**Comment by ABA2396** [comment]
其实这几个平台我都没用过，等个有缘人来写）
