### ISSUE TITLE
[优化建议]希望优化"完成后”中仅一次执行后逻辑

### ISSUE THREAD

**Issue by Book-fall2wish** [MaaAssistantArknights/MaaAssistantArknights#10730]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

在"完成后"功能中，若使用"仅一次"运行后再次打开程序，所有选项都清空了勾选（恢复至勾选仅一次前一刻的状态）。而我在使用仅一次功能时使用的选项是差不多的，因此希望添加一个不执行选项，以此保存其他选项的勾选状态，或者为仅一次功能添加自动勾选上一次使用仅一次时执行的动作。

**Comment by ABA2396** [comment]
没太看懂这个描述。勾了仅一次之后所有操作都是不保存的。要不你直接说说你需要的几种状态和你的操作顺序？

**Comment by Book-fall2wish** [comment]
> 没太看懂这个描述。勾了仅一次之后所有操作都是不保存的。要不你直接说说你需要的几种状态和你的操作顺序？

好像我的确说的很绕。
现在勾选仅一次，然后选中关机，关机以后下一次打开MAA，完成后里面不会有任何选项，我某天还想仅一次关机，又需要重新勾选仅一次、关机（点两次）。
如果先勾选关机，然后勾选仅一次，关机后下次打开MAA，完成后里面还是勾选着关机，仅一次就没什么作用了。

我希望可以“仅一次”执行以后跳到新的选项，例如“不执行“上，但是仍然保留着关机框的勾选，下一次使用仅一次时只需要勾选仅一次即可自动选中关机（按一下就能仅一次关机）。

实际上的程序逻辑并不一定要有不执行的勾选状态，可以在当前仅一次的保存逻辑上变为：勾选仅一次以后选中的动作，在下一次勾选仅一次时会自动加上。这样就可以实现正常情况下MAA执行完成自动退出模拟器，勾选仅一次以后自动变为退出模拟器并且关机。

**Comment by Book-fall2wish** [comment]
> 如果你只是想关机的话，直接右键点关机，就是仅一次关机了。

我一般要勾选关闭模拟器+关机😭我好几次关机导致模拟器镜像崩溃了

**Comment by Mou-Froski** [comment]
> 没太看懂这个描述。勾了仅一次之后所有操作都是不保存的。要不你直接说说你需要的几种状态和你的操作顺序？

先勾选其他选项再勾选“仅一次”会导致完成任务后仍然保留勾选其他选项的状态，如果要实现“仅一次”功能必须优先勾选“仅一次”。虽说“仅一次”的介绍里有说“勾选‘仅一次’时，执行动作后将恢复至勾选‘仅—次’前一刻的状态”，但这个逻辑本身就显得很奇怪。

**Comment by Mou-Froski** [comment]
> 没太看懂这个描述。勾了仅一次之后所有操作都是不保存的。要不你直接说说你需要的几种状态和你的操作顺序？

先勾选其他选项再勾选“仅一次”会导致完成任务后仍然保留勾选其他选项的状态，如果要实现“仅一次”功能必须优先勾选“仅一次”。虽说“仅一次”的介绍里有说“勾选‘仅一次’时，执行动作后将恢复至勾选‘仅—次’前一刻的状态”，但这个逻辑本身就显得很奇怪。
