### ISSUE TITLE
Reclamation Algorithm with existing save stops after selecting item count [EN]

### ISSUE THREAD

**Issue by swablueme** [MaaAssistantArknights/MaaAssistantArknights#10742]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I am using the latest version of the current update and have reviewed both the updates released so far and the unreleased changes in the Pull Requests, there is no mention of the bug being fixed.
- [X] I have reviewed the Pinned issue (Announcements), Open issues, and Closed issues to ensure that my issue has not been mentioned.

### Description

Steps
1. Use 'I do have a save, let's farm prosperity points by crafting tools' mode
2. Press Start
3. MAA will stop clicking after selecting the amount of items and will not craft them

Previous versions of MAA, (eg UI Version: v5.6.0-beta.1.d061.gc3a5471ca were working)

### Version

UI Version: v5.7.0
Core Version: v5.7.0
Build Time: 2024/10/03 16:50:57
Resource Time: 2024/09/28 02:45:03
Client: YostarEN

### Log and config files

Log
[asst.log](https://github.com/user-attachments/files/17273177/asst.log)
[gui.log](https://github.com/user-attachments/files/17273202/gui.log)

### Configuration information

LDPlayer9.041(9)
Frame rate: 60 FPS
Screen resolution: 1920x1080
DPI: 280
GPU accelerated inference: Not enabled
Windows 10

### Screenshots or recordings

Recording
https://github.com/user-attachments/assets/200ab114-d4e1-4e66-b0fe-0dfd6389c943

Screenshots
![image](https://github.com/user-attachments/assets/36b93512-89f1-4c2b-9911-5149e6d80ce6)
![image](https://github.com/user-attachments/assets/d1fe6e4f-a803-4c67-b349-f972f8904d9e)
![image](https://github.com/user-attachments/assets/52239891-0872-4ec5-a3b9-fd40c4c3f09c)

**Comment by Constrat** [comment]
![image](https://github.com/user-attachments/assets/9c847d4b-0b9b-47a7-b19c-2400685cdf36)
@Alan-Charred Very interesting

**Comment by Constrat** [comment]
@swablueme I can try to make the fix deploy instantly through MaaRelease. You just need to restart MAA and wait for the purple text saying 
@ABA2396 There shouldn't be no problem overwriting this task. It's a baseTask but since it gets detected before from the cache 
```json
    "Tales@RA@Craft": {
        "doc": "模板任务: 点击开始组装图标",
        "roi": [982, 500, 80, 50],
        "action": "ClickSelf"
    },
```

**Comment by Alan-Charred** [comment]
> ![image](https://github.com/user-attachments/assets/9c847d4b-0b9b-47a7-b19c-2400685cdf36)
> 
> @Alan-Charred Very interesting
> 
> 
> 
> It's probably because `Craft` is shorter in English.
> 
> 
> 
> To not go in a rabbit hole and make other tasks I will just increase the ROI to `982, 500, 80, 50` if it's not a problem
> 
> To this:
> 
> ![image](https://github.com/user-attachments/assets/5c234060-ed00-4661-9898-060d9fae3182)
> 
> 

Interesting... I should learn a lesson from this... Previously I try stick to smaller roi, and it turns out to be an improper practice now.

Thanks for help!

**Comment by Alan-Charred** [comment]
> @swablueme I can try to make the fix deploy instantly through MaaRelease. You just need to restart MAA and wait for the purple text saying 
> 
> @ABA2396 There shouldn't be no problem overwriting this task. It's a baseTask but since it gets detected before from the cache 
> 
> ```json
> 
>     "Tales@RA@Craft": {
> 
>         "doc": "模板任务: 点击开始组装图标",
> 
>         "roi": [982, 500, 80, 50],
> 
>         "action": "ClickSelf"
> 
>     },
> 
> ```

Oh this fix is perfect.
Yes just enlarge the roi in this single-step task.

Ahh.. are you going to submit a PR in this repo? I think I just need to approve this change...

**Comment by Constrat** [comment]
> Ahh.. are you going to submit a PR in this repo? I think I just need to approve this change...

No need to worry, I have write access.

The mentioned PR: https://github.com/MaaAssistantArknights/MaaRelease/pull/192 is in MaaRelease to drop the OTA update. To allow everyone to have the fix day zero, instead of nightly.

**Comment by Alan-Charred** [comment]
> > Ahh.. are you going to submit a PR in this repo? I think I just need to approve this change...
> 
> No need to worry, I have write access.
> 
> The mentioned PR: [MaaAssistantArknights/MaaRelease#192](https://github.com/MaaAssistantArknights/MaaRelease/pull/192) is in MaaRelease to drop the OTA update. To allow everyone to have the fix day zero, instead of nightly. It's just that I'm not sure about how the cache section interacts with the other resources since it's a basetask.

Cool!

**Comment by swablueme** [comment]
> @swablueme I can try to make the fix deploy instantly through MaaRelease. You just need to restart MAA and wait for the purple text saying @ABA2396 There shouldn't be no problem overwriting this task. It's a baseTask but since it gets detected before from the cache
> 
> ```json
>     "Tales@RA@Craft": {
>         "doc": "模板任务: 点击开始组装图标",
>         "roi": [982, 500, 80, 50],
>         "action": "ClickSelf"
>     },
> ```

Thankyou @Constrat @Alan-Charred I'll grab the release from internal beta (MAARelease)

**Comment by Constrat** [comment]
My intention is to have it automated. Without betas / nightlies. Just need MAA to be connected to internet to get the update JSON resource directly

**Comment by swablueme** [comment]
> My intention is to have it automated. Without betas / nightlies. Just need MAA to be connected to internet to get the update JSON resource directly.
> 
> But I want to make sure it doesn't break anything.

That's perfectly understandable: better safe than sorry in these cases! 😄
