### ISSUE TITLE
招募界面点停止招募上了，导致后续所有、全部、任何行为都会报失败

### ISSUE THREAD

**Issue by ReimsWwW** [MaaAssistantArknights/MaaAssistantArknights#10749]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

把is open 去了，看了一页没找到类似问题。
这两天，有时候叮咣一通系统音，把模拟器拖出来发现停在停止招募的确认界面了。

### Version

Resource Version: 矢量突破
Resource Time: 2024/9/29 07:23:34

UI Version: v5.7.0
Core Version: v5.7.0
Build Time: 2024/10/3 02:50:57

### 日志和配置文件

[archive.zip](https://github.com/user-attachments/files/17307071/archive.zip)
倒数第二次林可死大头的时候应该有

### 配置信息

win10 Mumu12 1920x1080 DPI280 fps60
画面增强开启，用雷电的话可以不说吗？
没开GPU加速，是不是跟画面增强冲突来着？

### 还有别的吗？

有可能加个一键收集模拟器和debug用的信息的功能吗……
我看有人都不填这些

**Comment by Saratoga-Official** [comment]
可能是截图增强导致截图速度太快，我记得上个版本应该加延迟了，可以先试试关了

**Comment by ReimsWwW** [comment]
刚才刚好看到，脚本卡在主页啥也没干。我过去点了一下公招，结果直接跳到fight环节，然后在此时，对着停止招募一顿猛点…………然后fight失败，然后进入infrast，我点了继续招募之后，脚本又对着停止招募一顿猛点……
[asst.log](https://github.com/user-attachments/files/17367926/asst.log)
[gui.log](https://github.com/user-attachments/files/17367927/gui.log)

**Comment by ABA2396** [comment]
日志里显示的是点的 ReturnButton，是不是触控又翻转了

**Comment by ABA2396** [comment]
minitouch 好像对竖屏翻转成的横屏支持不是很好，直接把模拟器设置成横屏的吧

**Comment by Saratoga-Official** [comment]
他说1920x1080，这不是横屏分辨率吗（挠头）

**Comment by ABA2396** [comment]
> 1920x1080

![image](https://github.com/user-attachments/assets/3e1b5794-c0b3-4dfb-94b2-8f52fe79c71b)

**Comment by ReimsWwW** [comment]
我开两个mumu12 一个蓝叠，就其中这个会出现这个情况……很奇怪。会是啥设置的问题吗？
[有bug的gui.json](https://github.com/user-attachments/files/17386256/bug.gui.json)
[无bug的gui01.json](https://github.com/user-attachments/files/17386257/bug.gui01.json)
[无bug的gui02.json](https://github.com/user-attachments/files/17386258/bug.gui02.json)
其中有bug的maa的gui配置用的是名称为"6468"的那个

**Comment by ReimsWwW** [comment]
> > 1920x1080
> 
> ![image](https://private-user-images.githubusercontent.com/99072975/376594742-3e1b5794-c0b3-4dfb-94b2-8f52fe79c71b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxODU3NDgsIm5iZiI6MTcyOTE4NTQ0OCwicGF0aCI6Ii85OTA3Mjk3NS8zNzY1OTQ3NDItM2UxYjU3OTQtYzBiMy00ZGZiLTk0YjItOGY1MmZlNzljNzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDE3MTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MzA0ODhjNTY4MDg4NjA3YTM1YTg3YmViYzAxY2MwZTdjMDEyOWJkMDQzODNhYzRkYjhlODYyOTc4Y2FlZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Rrlf6P2HDXBkf3Oyitw7QvXFFDRRZHp2bqiV3zX8HFg)

在另一个mumu12上也出现了这个问题……痛失俩小时基建和一颗蓝土。这里是说我的模拟器被识别成了竖屏吗？我往上翻了一下好像回回都是这个`10 1080 1920 0`。`[2024-10-16 21:09:49.928][INF][Px29d58][Tx2c010] Assistant::append_callback | ConnectionInfo {"details":{"adb":"D:\\Games\\YXArkNights-12.0\\shell\\adb.exe","address":"127.0.0.1:16384","config":"MuMuEmulator12","height":1080,"width":1920...
`这里是能正常识别成横屏的意思？

**Comment by ReimsWwW** [comment]
我还发现了一点，就是大多数情况(大概3/4左右？)卡在这个页面的时候，它是刚完成左上角格子的"选标签+打钩确认进行招募" 的行为，剩下三个格子都还没开始招，然后就卡在 "停止招募" 的确认界面了。不知道这个跟行为逻辑啥的有没有关系……
[asst.log](https://github.com/user-attachments/files/17416699/asst.log)
[gui.log](https://github.com/user-attachments/files/17416700/gui.log)
[gui.json](https://github.com/user-attachments/files/17416701/gui.json)
这是第二个mumu12 的log。 我用的是跟鹰角合作的那个专供版本，可能小版本跟官方的不太一样 (md官方模拟器广告都太tmd多了，红点怎么都消不完)。

**Comment by ABA2396** [comment]
把触控模式换成maatouch试试？我记得那个是有特殊处理的

**Comment by ReimsWwW** [comment]
> 把触控模式换成maatouch试试？我记得那个是有特殊处理的

我试试吧，之前一个换maatouch了，另一个把截图增强关了，看看还有没有这个情况……其实如果不挂肉鸽盐酸啥的也不是特别需求截图增强，但它真的好快好爽啊……

**Comment by ReimsWwW** [comment]
> 把触控模式换成maatouch试试？我记得那个是有特殊处理的

不行，maatouch的寄了
[asst.log](https://github.com/user-attachments/files/17427329/asst.log)
[gui.log](https://github.com/user-attachments/files/17427330/gui.log)
[gui.json](https://github.com/user-attachments/files/17427331/gui.json)

**Comment by Alan-Charred** [comment]
> Warning
> 
> 存在未确认的链接，请谨慎访问。 There are unconfirmed links, please visit with caution.
> 
> Warning
> 
> 存在未确认的链接，请谨慎访问。 There are unconfirmed links, please visit with caution.
> 
> > 把触控模式换成maatouch试试？我记得那个是有特殊处理的
> 
> 不行，maatouch的寄了 [asst.log](https://github.com/user-attachments/files/17427329/asst.log) [gui.log](https://github.com/user-attachments/files/17427330/gui.log) [gui.json](https://github.com/user-attachments/files/17427331/gui.json) `[2024-10-17 23:06:09.310][INF] <1><> 出现错误，已返回` `[2024-10-17 23:06:09.317][INF] <1><> 任务出错: Recruit`

您好，我看您 log 里显示 maa 保存了一些截图，您能找找，发上来看看吗？`debug\recruit\2024-10-17_23-06-01-601_raw.png`。不知道 maa 到底点击到哪里去了（

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/10846 加了个保底机制，应该有点用

**Comment by ReimsWwW** [comment]
等更新了我再试试吧……感谢各位
