### ISSUE TITLE
自动编队追加自定义干员无法选中 维娜·维多利亚

### ISSUE THREAD

**Issue by BX2333** [MaaAssistantArknights/MaaAssistantArknights#10760]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

自动编队追加自定义干员无法选中 维娜·维多利亚

### Version

UI Version: v5.7.0
Core Version: v5.7.0
Build Time: 2024/10/3 14:50:57

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17324234/asst.log)
[gui.log](https://github.com/user-attachments/files/17324239/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17324240/asst.bak.log)
[gui.bak.log](https://github.com/user-attachments/files/17324241/g
[gui.json](https://github.com/user-attachments/files/17324244/gui.json)
ui.bak.log)
2024.10.10 15：30分左右

### 配置信息

win11专业版 mumu12 1080p 280dpi 120fps
未开启截图增强
GPU加速开启 rtx2060 笔记本

**Comment by ABA2396** [comment]
草，怎么识别成 准娜·维多利亚 了
