### ISSUE TITLE
活动新关卡自动战斗可正常抄作业，但无法从刷理智启动

### ISSUE THREAD

**Issue by YashinNieh** [MaaAssistantArknights/MaaAssistantArknights#10773]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

![QQ_1728613054041](https://github.com/user-attachments/assets/71d419be-bcd0-4997-bb94-52e51f988a63)

追迹日落以西活动更新后，已经手动替换更新了resource资源，maa已更新至5.7.0，目前已知：
1. 新关卡可以正常抄作业；
2. 刷理智无法启动追迹日落以西的新关卡，没有报错，仅是点击开启任务后会自动停止；
3. 如果多个任务中勾选了刷新关卡的理智，其他任务也会无法正常启动，点击开启任务后会自动停止；
4. 同样是手动更新替换resource，之前不义之财的活动关卡可以正常刷理智；

### Version

MAA version: v5.7.0（524）

resource：手动替换至最新（mac怎么没有一键复制版本信息…）

### 日志和配置文件

日志时间线
[2024-10-11 09:51:17.830] 左右，刷理智 GO-8 失败
[2024-10-11 10:11:24.159] 左右，抄作业GO-8（42245.json 两次，第一次不小心把窗口放回调度了任务失败，第二次正常）

[asst.log](https://github.com/user-attachments/files/17336834/asst.log)
[asst.bak.log](https://github.com/user-attachments/files/17336836/asst.bak.log)

### 配置信息

操作系统：macOS 15.0.1
模拟器： Playcover 版本3.0.0.maa.5 (5)

### 截图或录屏

刷理智（GO-8）无法启动的录屏
https://github.com/user-attachments/assets/82d75340-7b7b-4110-bbc0-43fb3c66cb24

**Comment by ABA2396** [comment]
macos 的 ui 没处理 cache 的逻辑，而 GO-8 的任务是在 \cache\resource\tasks.json 里的，最近写 macos 的大佬比较慢，一直没机会加，你可以把下面这段加到 resource\tasks.json 里（不是 cache 文件夹下的 resource）
```
"GO-9": {
        "algorithm": "JustReturn",
        "sub": ["GO-OpenOpt"],
        "next": ["GO-9@SideStoryStage", "GO-9@SwipeToStage"]
    },
    "GO-8": {
        "algorithm": "JustReturn",
        "sub": ["GO-OpenOpt"],
        "next": ["GO-8@SideStoryStage", "GO-8@SwipeToStage"]
    },
    "GO-7": {
        "algorithm": "JustReturn",
        "sub": ["GO-OpenOpt"],
        "next": ["GO-7@SideStoryStage", "GO-7@SwipeToStage"]
    },
    "GO-4": {
        "algorithm": "JustReturn",
        "sub": ["GO-OpenOpt"],
        "next": ["GO-4@SideStoryStage", "GO-4@SwipeToStage"]
    },
    "GO-OpenOpt": {
        "algorithm": "JustReturn",
        "next": ["GO-OpenOcr", "GO-Open"]
    },
    "GO-Open": {
        "baseTask": "SS-Open",
        "template": "StageSideStory.png",
        "next": ["GOChapterToGO"]
    },
    "GO-OpenOcr": {
        "baseTask": "SS-OpenOcr",
        "text": [
           "追迹日落以西",
           "未了往昔"
        ],
        "next": ["GOChapterToGO"]
    },
   "GOChapterToGO": {
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": [
           "无名之勋",
           "名之"
        ],
        "preDelay": 3000,
        "roi": [914, 579, 101, 34],
        "next": ["#self", "ChapterSwipeToTheRight"]
    },
    "GO-9@SideStoryStage": {
        "text": ["GO-9"]
    },
    "GO-8@SideStoryStage": {
        "text": ["GO-8"]
    },
    "GO-7@SideStoryStage": {
        "text": ["GO-7"]
    },
    "GO-4@SideStoryStage": {
        "text": ["GO-4"]
    },
```
![image](https://github.com/user-attachments/assets/59a92ce7-10b0-49a7-a29e-e8d5a8b8e89f)

**Comment by YashinNieh** [comment]
感谢，经尝试问题已解决

**Comment by YashinNieh** [comment]
> macos 的 ui 没处理 cache 的逻辑，而 GO-8 的任务是在 \cache\resource\tasks.json 里的，最近写 macos 的大佬比较忙，一直没机会加，你可以把下面这段加到 resource\tasks.json 里（不是 cache 文件夹下的 resource）
> 

感谢，经尝试问题已解决
