### ISSUE TITLE
TODO: 自动战斗 编队 自动借助战

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#10775]
### 说说你遇到的问题？

在 #10820 中实现招募好友干员；
将会实现练度筛选（允许自定义）

**Comment by Floatingcloud01** [comment]
每日打of-1借助战卡这里
![11](https://github.com/user-attachments/assets/3f200b1b-974f-4ece-8105-0df360284a2c)

**Comment by ABA2396** [comment]
of-1 借助战的已经修了，还没发版。这个写的是自动借助战功能

**Comment by status102** [comment]
> ### 说说你遇到的问题？
> working on [`feat`/SupportOper](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/feat/SupportOper?rgh-link-date=2024-10-11T03%3A19%3A42Z)

404 Not Found

**Comment by GreenDragonflyy** [comment]
> of-1 借助战的已经修了，还没发版。这个写的是自动借助战功能

请问我最近用OF-1借助战它只会编队一个芬，然后放下去没有其他动作等输是因为这个原因吗，往后会修复吗

**Comment by ABA2396** [comment]
几级的芬，打不过这关吗
![image](https://github.com/user-attachments/assets/a5a22ddf-7130-41e9-b3f4-20a186bdc4de)
这关不是可以漏十个吗）

**Comment by GreenDragonflyy** [comment]
> 几级的芬，打不过这关吗 ![image](https://private-user-images.githubusercontent.com/99072975/376528636-a5a22ddf-7130-41e9-b3f4-20a186bdc4de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5ODIyMzYsIm5iZiI6MTcyODk4MTkzNiwicGF0aCI6Ii85OTA3Mjk3NS8zNzY1Mjg2MzYtYTVhMjJkZGYtNzEzMC00MWU5LWIzZjQtMjBhMTg2YmRjNGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA4NDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNzllNDZkNjY0MjNmYjAxYThhODE0MmFlZGI1ZGY1ZGQ2YTFjNzJmNzM1YjUxNDZjMDE1ZGE5OWY3ZDlhYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YK7GqZfP5QjSnPggLoMCpqgyQdNWCFlRZcFzTQQiO7U) 这关不是可以漏十个吗）

精一0级的....剩15个的时候被虫子活活吐死了....

**Comment by Saratoga-Official** [comment]
> > of-1 借助战的已经修了，还没发版。这个写的是自动借助战功能
> 
> 请问我最近用OF-1借助战它只会编队一个芬，然后放下去没有其他动作等输是因为这个原因吗，往后会修复吗

练度不够怪谁，正常有风笛会编风笛的我记得，你应该是没有，还有这个issue不是讨论of1借助战功能的地方，想反馈问题另开issue
