### ISSUE TITLE
RB6 Theme affects Base & Credit Store Functions that MAA is not recognized

### ISSUE THREAD

**Issue by pangchewe** [MaaAssistantArknights/MaaAssistantArknights#10777]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I am using the latest version of the current update and have reviewed both the updates released so far and the unreleased changes in the Pull Requests, there is no mention of the bug being fixed.
- [X] I have reviewed the Pinned issue (Announcements), Open issues, and Closed issues to ensure that my issue has not been mentioned.

### Description

![image](https://github.com/user-attachments/assets/c0e5d15e-6ae8-4622-9c64-a5c049d93dac)
![image](https://github.com/user-attachments/assets/54a91f8e-f4fb-4a78-919d-6fb3c48c0ece)
As you see, When I using R6S Theme,Infrast(Base) and Credit Store ( Buying Credit Task  which go to friend base task is working ) is not recognize it and mark it as errors. When changing to Default Theme,It's working
It's happened after Babel event coming in.

### Version

Resource Version: Operation Originium Dust - Retrospection
Resource Time: 2024/9/27 23:45:03

UI Version: v5.7.0
Core Version: v5.7.0
Build Date: 2024/10/3 13:50:57

### Log and config files

[asst.log](https://github.com/user-attachments/files/17337849/asst.log)

### Configuration information

NOX

**Comment by Constrat** [comment]
@ABA2396 I had to add the template because they were"different". 
I also noticed this issue and temporarily am using the other theme.
I'll have a look at it.

**Comment by Constrat** [comment]
Btw, still only half fixed. Check this out:
New template: 
![image](https://github.com/user-attachments/assets/a0d82bf5-0d7d-4d8d-acf9-2d4e6ec92246)

Old template (currently being used):
![image](https://github.com/user-attachments/assets/f9e4519f-a4eb-468e-85df-4075aeb7c507)
