### ISSUE TITLE
获取信用及购物中不勾选访问好友也会执行

### ISSUE THREAD

**Issue by Miuzarte** [MaaAssistantArknights/MaaAssistantArknights#10776]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/user-attachments/assets/24513f84-530f-4818-a3d2-bb86d1db788d)

### Version

Resource Version: 追迹日落以西
Resource Time: 2024/10/9 16:44:46
UI Version: v5.7.1-alpha.1.d008.g194c34c18
Core Version: v5.7.1-alpha.1.d008.g194c34c18
Build Time: 2024/10/9 18:52:18

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17337560/asst.log)
[gui.log](https://github.com/user-attachments/files/17337558/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17337559/asst.bak.log)
[gui.bak.log](https://github.com/user-attachments/files/17337561/gui.bak.log)

[gui.json](https://github.com/user-attachments/files/17337565/gui.json)

### 配置信息

![image](https://github.com/user-attachments/assets/e7e4f2c5-acda-4e58-928e-8f49e6be9649)
1080P 280DPI 165
![image](https://github.com/user-attachments/assets/67a2d98b-ef81-46be-80f4-cce74c6f48d2)
![image](https://github.com/user-attachments/assets/128a0899-3749-4db1-a9c5-29ef92d7969d)

**Comment by ABA2396** [comment]
好像是有这个问题，有空看看
