### ISSUE TITLE
神秘代码未找到作业，战斗出错

### ISSUE THREAD

**Issue by skaaadiii** [MaaAssistantArknights/MaaAssistantArknights#10772]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

新活动复制代码提示未找到作业，下载json文件运行提示战斗出错

### Version

Resource Version: 追迹日落以西
Resource Time: 2024/10/11 02:03:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17336855/asst.log)
[gui.log](https://github.com/user-attachments/files/17336856/gui.log)
[gui.json](https://github.com/user-attachments/files/17336859/gui.json)
2024-10-11-10:28分左右

### 配置信息

Win11 23H2 专业工作站版，MUMU模拟器，1920x1080DPI280,60帧，截图增强已开启，GPU加速推理已开启，GPU型号：TITIAN RTX

### 截图或录屏

![1](https://github.com/user-attachments/assets/a0248aed-50e0-4039-8bf4-8eef7cc67925)
![2](https://github.com/user-attachments/assets/2a2b67c2-3354-4f30-9d5c-005ae12d22ad)

### 还有别的吗？

无

**Comment by Rbqwow** [comment]
https://maa.plus/docs/zh-cn/manual/introduction/copilot.html

**Comment by ABA2396** [comment]
不是战斗列表的话没有导航，只会看你当前右下角有没有开始战斗或者已经进到里面一层准备编队或者开始了。
战斗列表也不支持在这个界面开始，只会在当前页面左右划看有没有对应的关卡名

第二个报错是网络问题，连不上服务器
![image](https://github.com/user-attachments/assets/c1ffc2b0-fefb-48af-a331-a21ca392d332)
