### ISSUE TITLE
借助战刷

### ISSUE THREAD

**Issue by PrionVir** [MaaAssistantArknights/MaaAssistantArknights#10770]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

<img width="965" alt="a64338015e76fc969b8d3667a263d59" src="https://github.com/user-attachments/assets/5f8afb1e-ec9a-4419-85e7-a91d0695b716">
卡在这个页面，不知道是否是因为还没有制作新助战界面的识别系统？

### Version

UI Version: v5.7.0
Core Version: v5.7.0
Build Time: 2024/10/3 14:50:57

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17336683/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17336685/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17336686/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17336687/gui.log)
[gui.json](https://github.com/user-attachments/files/17336689/gui.json)

### 配置信息

Win 11 Mumu模拟器12 1920*1080（DPI 280）
已开启截图增强

**Comment by Rbqwow** [comment]
#10757

**Comment by Daydreamer114** [comment]
duplicate of #10752
