### ISSUE TITLE
基建线索搜集建议

### ISSUE THREAD

**Issue by Crownor** [MaaAssistantArknights/MaaAssistantArknights#1077]
基建里边遇到了关于线索搜集的问题：

1. 控制中枢貌似不会放线索倾向增强干员（阿和惊蛰）。
2. 基建先更换制造站和订单，导致这一步里边部分线索倾向干员就被安排了（比如杰西卡），导致后续在会议室无合适线索倾向干员可用。

建议更换顺序至少让会议室稳定放入合适的倾向干员QAQ。

**Comment by MistEO** [comment]
设置里基建设置顺序是可以拖动的，如果觉得会客室比较重要可以把它拖到前面。

控制中枢就是新建文件夹了（

**Comment by YipKei** [comment]
补充提几句：
线索增强功能价值较低，210 信用＝875% 会客室产出，会客室产出＝制造设施的 5.4%（小数点没错）
因此可以简单得出，从绝对无法实现线索交流，到稳定每天一次线索交流（这实际上不可能），等效于 47.25% 的制造站产率。
而且实际上，因为你用线索倾向强化实现了增加交流的目的，至少会吃掉一张线索，也就是实际增幅要乘以 19/21，也就是最大收益是 42.75% 。
这还没完，如果开交流的7张线索全是你的，那么实际上净增益只有 70 信用，当然，一般如果是每天开一次这种最理想的情况的话，平均有 4.5 张线索来自于好友，那就意味着净增益大概是 160 信用左右，实际收益是 36% 
那如果你不是天天都不能开的话，实际价值是有效增加天数除以总天数，再乘以这个 36%
而实际操作中，除非严格定时，否则也做不到 7 天开 7 次交流。
实际上倾向强化这一点做不到天天交流，没有倾向强化也做不到天天不交流。
增幅如果能达到 1/3 的话，也很难和中枢里的其他提供制造加成的干员竞争。

综上所述，与其考虑用线索增幅干员强化会客室开线索交流的频率，不如去买两三个小号，三天登录一次去给大号送线索就行了。就算做不到天天开，七天开个五六天肯定能做到，已经比中枢放人要强得多了，还不用练。
因此你这个需求属于小众需求，同时在实现难度上也相对较大，一般来说还是优先考虑能给更多人带来提升的功能的开发的。

**Comment by Crownor** [comment]
> 设置里基建设置顺序是可以拖动的，如果觉得会客室比较重要可以把它拖到前面。
> 
> 控制中枢就是新建文件夹了（

嗯嗯，好的

**Comment by Crownor** [comment]
> 补充提几句： 线索增强功能价值较低，210 信用＝875% 会客室产出，会客室产出＝制造设施的 5.4%（小数点没错） 因此可以简单得出，从绝对无法实现线索交流，到稳定每天一次线索交流（这实际上不可能），等效于 47.25% 的制造站产率。 而且实际上，因为你用线索倾向强化实现了增加交流的目的，至少会吃掉一张线索，也就是实际增幅要乘以 19/21，也就是最大收益是 42.75% 。 这还没完，如果开交流的7张线索全是你的，那么实际上净增益只有 70 信用，当然，一般如果是每天开一次这种最理想的情况的话，平均有 4.5 张线索来自于好友，那就意味着净增益大概是 160 信用左右，实际收益是 36% 那如果你不是天天都不能开的话，实际价值是有效增加天数除以总天数，再乘以这个 36% 而实际操作中，除非严格定时，否则也做不到 7 天开 7 次交流。 实际上倾向强化这一点做不到天天交流，没有倾向强化也做不到天天不交流。 增幅如果能达到 1/3 的话，也很难和中枢里的其他提供制造加成的干员竞争。
> 
> 综上所述，与其考虑用线索增幅干员强化会客室开线索交流的频率，不如去买两三个小号，三天登录一次去给大号送线索就行了。就算做不到天天开，七天开个五六天肯定能做到，已经比中枢放人要强得多了，还不用练。 因此你这个需求属于小众需求，同时在实现难度上也相对较大，一般来说还是优先考虑能给更多人带来提升的功能的开发的。

有理有据，令人信服欸，回头多开几个小号去
