### ISSUE TITLE
模拟器重启后出现连接错误、任务出错

### ISSUE THREAD

**Issue by alon74** [MaaAssistantArknights/MaaAssistantArknights#1078]
如题
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9038080/asst.log)
![image](https://user-images.githubusercontent.com/42845804/177123103-209a8337-da7c-44f0-a813-f02ef224c876.png)

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
