### ISSUE TITLE
基建还没识别维娜？

### ISSUE THREAD

**Issue by insine-inverse** [MaaAssistantArknights/MaaAssistantArknights#10796]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

贸易站换班找不到维娜，明明就在第一个……

### Version

Resource Version: 追迹日落以西
Resource Time: 2024/10/9 16:44:46
UI Version: v5.7.0
Core Version: v5.7.0
Build Time: 2024/10/3 14:50:57

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17351813/asst.log)
[gui.log](https://github.com/user-attachments/files/17351814/gui.log)
[153.json](https://github.com/user-attachments/files/17351815/153.json)

### 配置信息

win11 mumu12 增强截图开启

**Comment by oooyiyangc** [comment]
应该是ocr识别不准确的原因
#10760

**Comment by Saratoga-Official** [comment]
asstlog不完整,请上传asstlogbak，不行你就重新运行一遍，再上传
