### ISSUE TITLE
[功能建议]:希望能够增加每次大更自动更新明日方舟的功能

### ISSUE THREAD

**Issue by smzzqxw1915** [MaaAssistantArknights/MaaAssistantArknights#10791]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

none

### 有什么好的想法？

拿mumu模拟器举例子,mumu在获取明日方舟版本后会有可更新字样的角标，此时可点击图标，然后点击弹窗中的确定进行更新。希望在开启“启动MAA后自动开启模拟器”和“启动MAA后直接运行”的功能（还有“开始唤醒”）的情况下，进入明日方舟时能够进行更新并等待更新，更新后进入游戏执行“一键长草”行为，而不是出现可能的卡死。
没有考虑过代码上的可行性，如果无法实现，就当没有这个issue。如果能实现，会对像我一样给电脑设自动开机且启动maa清日常的人十分友好。

**Comment by Daydreamer114** [comment]
maa 启动明日方舟不靠点图标；点完图标那个弹窗是模拟器的，maa 点不到；等待更新已经写了

**Comment by status102** [comment]
Duplicate of #8123
