### ISSUE TITLE
繁中刷理智無法使用

### ISSUE THREAD

**Issue by ryan24580245** [MaaAssistantArknights/MaaAssistantArknights#10795]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在進行自動刷理智時
會告知戰鬥出錯
卡在終端畫面
目標關卡為ZT-8

### Version

UI Version: v5.7.0
Core Version: v5.7.0
Build Time: 2024/10/3 14:50:57

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17351744/asst.log)
[gui.log](https://github.com/user-attachments/files/17351745/gui.log)
[gui.json](https://github.com/user-attachments/files/17351747/gui.json)

### 配置信息

Win 10
MUMU12
1280X720
240
60
無截圖增強

### 还有别的吗？

要求的配置文件缺少的是因為Debug資料夾裡面沒有

**Comment by Manicsteiner** [comment]
> [2024-10-13 06:52:39.463][TRC][Px3b78][Tx3148] asst::WordOcr [{ 種威無情”內關卡已開放: [ 123, 44, 210, 15 ], score: 0.894029 }, { -: [ 388, 35, 48, 63 ], score: 0.293905 }, { 6V1O: [ 32, 63, 32, 13 ], score: 0.820791 }, { L: [ 8, 90, 16, 14 ], score: 0.780296 }, { 1天: [ 21, 89, 51, 19 ], score: 0.999942 }] by OCR Pipeline , cost 770 ms
> [2024-10-13 06:52:39.463][INF][Px3b78][Tx3148] {"class":"asst::ProcessTask","details":{"cur_retry":15,"retry_times":20,"to_be_recognized":["ZT-OpenOcr"]},"first":["ZT-OpenOcr"],"pre_task":"","subtask":"ProcessTask","taskchain":"Fight","taskid":3}

看起来是卡在了这一步，但是看热更新的task应该是可以识别的，不清楚是什么情况
https://github.com/MaaAssistantArknights/MaaRelease/blob/e8fa4dc24816ab4673192bc3d3b9cdf0f977e61c/MaaAssistantArknights/api/resource/global/txwy/resource/tasks.json#L6
