### ISSUE TITLE
公招时间相关

### ISSUE THREAD

**Issue by LBacteria** [MaaAssistantArknights/MaaAssistantArknights#1080]
在出现必出4星以及4星以上的tag时，时间可以拉满，不然会被划掉

**Comment by MistEO** [comment]
本来就是拉满 9 小时的呀，如果你遇到了没拉满可能是 bug, 重新提个 bug report 看看

**Comment by LBacteria** [comment]
啊不是bug，我看了下回放，当时是我手点点多了，因为他每次公招只会选择三个格子第四个不招

**Comment by zzyyyl** [comment]
公招招几个可以自己设置的，在 `设置-自动公招` 里

要是没问题了就 close
