### ISSUE TITLE
B服登录bug&定时bug

### ISSUE THREAD

**Issue by GasaiYuno314** [MaaAssistantArknights/MaaAssistantArknights#10800]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在MuMu模拟器中,手动切换账号后,再次打开游戏时会弹出隐私政策,需要点击确认.

B服无法使用自动的账号切换,会卡在账号切换界面,不会正确点开账号列表,会反复点击附近区域.

定时7的分钟无法设置超过40的值,输入或者点击旁边的按钮也不行.

### Version

UI Version: v5.7.0
Core Version: v5.7.0
Build Time: 2024/10/3 14:50:57

### 日志和配置文件

[gui.json](https://github.com/user-attachments/files/17356019/gui.json)
[asst.bak.log](https://github.com/user-at
[gui.bak.log](https://github.com/user-attachments/files/17356070/gui.bak.log)
tachments/files/17356024/asst.bak.log)
[asst.log](https://github
[gui.log](https://github.com/user-attachments/files/17356084/gui.log)
.com/user-attachments/files/17356028/asst.log)

### 配置信息

版本	Windows 11 专业工作站版
版本号	23H2
安装日期	‎2024/‎1/‎27
操作系统版本	22631.4317
体验	Windows Feature Experience Pack 1000.22700.1041.0

MuMu12模拟器,开启截图增强 
模拟器3840*2160(DPI 540)  60帧

开启GPU加速, 3060ti

**Comment by Rbqwow** [comment]
隐私政策不点是预期行为 大家讨论后认为 MAA 不该代为同意法律文件

B服的账号切换 不同的分辨率和不同的 DPI 排列组合出来的界面全部都不一样 实在是没适配精力 现在的应该是只支持 1280x720 DPI240 后续有可能直接推荐使用模拟器多开

最后一个 #10804 

> 以及由于某些屎山问题 还是在 1280x720 或者 1920x1080 下跑比较好 分辨率再高有可能会出问题
