### ISSUE TITLE
关于自动代理的建议

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#1081]
建议增加全关卡匹配
建议增加多关卡顺序代理 如先打n次4-5，再打m次1-7。
最好可以自定义5关 （灵感来源于其他脚本）

**Comment by zzyyyl** [comment]
我记得不做是因为现在的 UI 不太好整这个？
要是急需的话也可以试试 maa 的 python 接口，core 是支持这个逻辑的（

**Comment by ABA2396** [comment]
> 我记得不做是因为现在的 UI 不太好整这个？ 要是急需的话也可以试试 maa 的 python 接口，core 是支持这个逻辑的（

不是这个问题，主要是全关卡导航不好做，根据现在的task的写法起码得写几千行

**Comment by ABA2396** [comment]
就算拆分成章节导航也会有s关的干扰，还是挺麻烦的

**Comment by ABA2396** [comment]
现在支持导航的关卡倒是可以考虑下这个逻辑，还能顺带把刷关优先级的问题解决了（跳过当天未开放的关卡）

**Comment by ntgmc** [comment]
> > 我记得不做是因为现在的 UI 不太好整这个？ 要是急需的话也可以试试 maa 的 python 接口，core 是支持这个逻辑的（
> 
> 不是这个问题，主要是全关卡导航不好做，根据现在的task的写法起码得写几千行

每章节设置一个数组，每关设置一个坐标作为该章的数组成员，选择框搞两个，一个选章节，第二个读取第一个选的章节再显示每个数组成员选择

**Comment by ntgmc** [comment]
> 就算拆分成章节导航也会有s关的干扰，还是挺麻烦的

s关也加到数组里面 当成普通关一样算 不要填 用选的

**Comment by ABA2396** [comment]
> > 就算拆分成章节导航也会有s关的干扰，还是挺麻烦的
> 
> s关也加到数组里面 当成普通关一样算 不要填 用选的

问题就是找到指定的关卡，章节都不是问题

**Comment by ntgmc** [comment]
我这里只说的是主线，插曲和别传

**Comment by ABA2396** [comment]
> > 就算拆分成章节导航也会有s关的干扰，还是挺麻烦的
> 
> s关也加到数组里面 当成普通关一样算 不要填 用选的

为了减少代码量肯定是章节导航通用，然后做n个选关，问题就是s关和普通关怎么区分

**Comment by ntgmc** [comment]
> > > 就算拆分成章节导航也会有s关的干扰，还是挺麻烦的
> > 
> > 
> > s关也加到数组里面 当成普通关一样算 不要填 用选的
> 
> 问题就是找到指定的关卡，章节都不是问题

每关设定一个坐标嘛 不一定要通用

**Comment by ABA2396** [comment]
> > > > 就算拆分成章节导航也会有s关的干扰，还是挺麻烦的
> > > 
> > > 
> > > s关也加到数组里面 当成普通关一样算 不要填 用选的
> > 
> > 
> > 问题就是找到指定的关卡，章节都不是问题
> 
> 每关设定一个坐标嘛 不一定要通用

那就是几千行代码

**Comment by ntgmc** [comment]
不一定吧 当成一个常量数组 到时候选择后引用

**Comment by ntgmc** [comment]
关卡的坐标

**Comment by ABA2396** [comment]
现在导航的逻辑是定位到`终端`主界面-进入`章节`-寻找关卡-进入关卡

**Comment by ABA2396** [comment]
选关不是硬编码，全在task.json里，里面有个1-7的导航你看下就知道了

**Comment by ABA2396** [comment]
按照现在的写法可以当做每一关都要写这么长一段

**Comment by ABA2396** [comment]
> > 选关不是硬编码，全在task.json里，里面有个1-7的导航你看下就知道了
> 
> 就是选关也要ocr吗 我以为只是固定数值

选关要拖动，不同的电脑一次拖动的距离都不一样，固定坐标肯定不行

**Comment by ntgmc** [comment]
> > > 选关不是硬编码，全在task.json里，里面有个1-7的导航你看下就知道了
> > 
> > 
> > 就是选关也要ocr吗 我以为只是固定数值
> 
> 选关要拖动，不同的电脑一次拖动的距离都不一样，固定坐标肯定不行

我之前自己写的话是先确定我的分辨率的滑动距离，再根据分辨率（或窗口大小）按比例缩放

**Comment by ABA2396** [comment]
> 等之后OCR好了，选关就全用OCR搞别用模板匹配了（ 然后按照左到右的顺序给每个关卡编个号，再做个章节导航，选关的时候按照编号顺序从左往右拖动就好了

现在的活动关卡用的全都是ocr

**Comment by zzyyyl** [comment]
> > 等之后OCR好了，选关就全用OCR搞别用模板匹配了（ 然后按照左到右的顺序给每个关卡编个号，再做个章节导航，选关的时候按照编号顺序从左往右拖动就好了
> 
> 现在的活动关卡用的全都是ocr

我之前1-7用OCR的时候被玛丽吐槽说为什么不用模板匹配（

**Comment by ntgmc** [comment]
之前我用过的脚本是apk的，所以不会受电脑的影响

**Comment by ABA2396** [comment]
说实话感觉全关卡导航其实意义不大来着）

**Comment by zzyyyl** [comment]
> 说实话感觉全关卡导航其实意义不大来着）

全关卡导航之后可以跟企鹅的刷图规划器联动的（
~虽然我从来没有在活动关之外刷过材料~

**Comment by ABA2396** [comment]
我感觉现在应该先摸个刷关优先级，弄一个要刷的关卡列表，跳过当日未开放的关卡，去刷第一个匹配上的

**Comment by ntgmc** [comment]
> > 之前我用过的脚本是apk的，所以不会受电脑的影响
> 
> 手机我觉得也有影响的吧，性能不同的手机可能每次滑动距离都不一样 adb每次滑动会有一个忽大忽小的惯性滑动距离，就是这个导致的问题（当然跟玛丽把起点终点都用泊松分布也有关系）

可以在滑动完立刻点击一下 不就能停止滑动了吗

**Comment by zzyyyl** [comment]
总之全关卡导航应该还不是这几个版本能更新的

~当然如果是学姐的话一下就解决了（~
