### ISSUE TITLE
B站账号切换功能完全无法使用

### ISSUE THREAD

**Issue by DLmaster361** [MaaAssistantArknights/MaaAssistantArknights#10815]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

我尝试了1080p dpi280 与 720p dpi240 两个分辨率、完整用户名与用户名片段，结果MAA正常登录退出后成功到达账号切换界面，但是完全无法识别出目标用户完成账号切换。

### Version

MAA版本v5.7.0;资源日期24/09/29

### 日志和配置文件

[gui.json](https://github.com/user-attachments/files/17371188/gui.json)

### 配置信息

MuMu12，未开启截图增强，intel核显加速

### 截图或录屏

![MuMu12-20241015-100614](https://github.com/user-attachments/assets/ced8914b-50e0-4c6a-bc2c-b5ecdc3e65fb)

### 还有别的吗？

无

**Comment by status102** [comment]
B服的账号切换功能缺乏维护，而且B站的登录框缩放比较麻烦，近期将移除对B服的账号切换支持

**Comment by status102** [comment]
- #10817
