### ISSUE TITLE
在#10784之后，MuMu截图增强依旧不能使用

### ISSUE THREAD

**Issue by Dean-Mon10** [MaaAssistantArknights/MaaAssistantArknights#10816]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及
- [X] 我正在使用最新的 MAA 公测版本和最新的官版或方舟专版 MuMu 模拟器
- [X] 我已参考文档确定安装路径、实例编号、屏幕编号填写正确，并确认在关闭截图增强模式后问题消失
- [x] 我未开启后台保活，模拟器帧数为 60，显存使用策略为“画面表现更好”

### 问题描述

在 #10784 后，使用内测版本号尾数0e2f、5a8d、5407开启截图增强，均不能正常使用截图增强功能（“截图增强未生效，请检查相关设置”）。但正式版5.7.0与内测01a6可正常使用。

以上每个版本的“连接设置”和“启动设置”均设置了相同参数。

### Version

资源版本：均为` # 1011`
MAA ver：见上方`问题描述`
MuMu ver：`4.0.10`和`4.1.0`

### MAA 日志和配置文件

[forDebug.zip](https://github.com/user-attachments/files/17372170/forDebug.zip)
只用来测试，应该没有冗余内容，或者可以倒序查看。

### MuMu 问题诊断

[mumuDiag.txt](https://github.com/user-attachments/files/17372195/mumuDiag.txt)

### 其他

以上版本均已开启GPU加速推理，型号为RTX 4060 Laptop。

**Comment by Daydreamer114** [comment]
<img width="603" alt="截屏2024-10-15 13 35 49" src="https://github.com/user-attachments/assets/eef799c1-9d21-49bb-9c15-23dbfbdf8301">
@Rbqwow

**Comment by Rbqwow** [comment]
虽然找到问题原因了 但在这之前有一个关键问题想问
你的 MuMu 12 调试端口为什么是 7555

**Comment by Rbqwow** [comment]
更正一下上句话 刚刚少看个日志

> ADB调试端口 :  16384

你的调试端口明明是 16384 为啥要去连 7555 然后一会连的上一会连不上
🤔重点是为什么能连上 是在同时开别的模拟器吗
