### ISSUE TITLE
关于肉鸽精2某个特定干员优先级的问题

### ISSUE THREAD

**Issue by quarx613** [MaaAssistantArknights/MaaAssistantArknights#10828]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

不知道知道为什么肉鸽维什戴尔不精2吗 把我的玛恩纳和浊心斯卡蒂精2了都不精 抽到狙击券不是放弃就是选些牛马 本体已经290了
![QQ图片20241017110049](https://github.com/user-attachments/assets/9e53a163-8f46-4b3a-9326-180dbefa1575)
![QQ截图20241017110035](https://github.com/user-attachments/assets/ce841455-ca78-4879-84c9-d1eaaac6baf4)
![360截图20241017110224](https://github.com/user-attachments/assets/61b6006a-9d2e-42da-ab2a-7dca9a936d27)

### Version

UI Version: v5.7.0
Core Version: v5.7.0
Build Time: 2024/10/3 14:50:57

### 日志和配置文件

[Uploading Desktop.zip…]()

### 配置信息

系统: Microsoft Windows 11 64位 23H2
CPU: AMD Ryzen 7 5700X3D 8-Core Processor           
主板: 微星 MAGB550MMORTARMAXWIFI(MS-7C94)
内存: 可用内存(5.7GB) 内存(15.9GB)
屏幕: 1920x1080
显卡: NVIDIA GeForce RTX 4070 SUPER(20240905)
OpenGL: 4.6.0 NVIDIA 561.09
VT:已开启
HyperV:已关闭
以管理员身份运行: 否
安装磁盘: E盘(SSD-NTFS) 可用空间(260GB) 总空间(631GB)
模拟器版本: 9.0.78.0(64)
运行参数: CPU(4核) 内存(4096M) 分辨率(1920x1080 DPI 280) FPS(60)
多开参数: 当前序号(0) 正在运行(1) 高速模式(1) FPS限制(60) 极致多开(0)
可用空间: 类型(自动扩充) 可用空间(25GB) 总空间(29GB)
机型: 品牌(samsung) 型号(SM-G9730)
ASTC: 开启
ROOT 权限: 开启
模拟器路径: E:\leidian\LDPlayer9\
日志路径: C:\Users\Administrator\AppData\Roaming\leidian9\log

### 截图或录屏

![QQ截图20241017110035](https://github.com/user-attachments/assets/4c63bdd5-c8bf-46be-8266-89a528f462f1)
![QQ图片20241017110049](https://github.com/user-attachments/assets/4e5eb120-f4be-4081-a37b-0919a4d4c7f1)
![360截图20241017110224](https://github.com/user-attachments/assets/0eb79f16-3839-47ff-8fe1-36635a121345)

**Comment by quarx613** [comment]
[Uploading Desktop.zip…]()

**Comment by quarx613** [comment]
[asst.bak.log.zip](https://github.com/user-attachments/files/17405549/asst.bak.log.zip)
[asst.zip](https://github.com/user-attachments/files/17405552/asst.zip)
[gui.bak.log.zip](https://github.com/user-attachments/files/17405554/gui.bak.log.zip)
[gui.zip](https://github.com/user-attachments/files/17405555/gui.zip)

**Comment by Daydreamer114** [comment]
completed with #10831

**Comment by quarx613** [comment]
> 完成 #10831

请问我需要重新下载MAA以更新肉鸽文件吗？
