### ISSUE TITLE
水月肉鸽自动3次后在最后一层boss战前会进入地图界面停止不动

### ISSUE THREAD

**Issue by Leo2285na** [MaaAssistantArknights/MaaAssistantArknights#10837]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

水月肉鸽自动推图3次后，在最后一层失尘岩洞的险路恶敌boss战会进入地图界面，然后也不点出去也不停止不动。发现是前面一层选择没有进行选择,导致boss战没有开始按钮。急需修复！
![MuMu12-20241018-082855](https://github.com/user-attachments/assets/2b77fcae-1b9d-4810-8954-dda929a64b35)
![MuMu12-20241018-083354](https://github.com/user-attachments/assets/e8e3ba5e-ce6f-4edc-a40d-9e06c6eb7dc2)
![MuMu12-20241018-083401](https://github.com/user-attachments/assets/7a987f56-1e61-4543-90f7-616cfa182d13)
![MuMu12-20241018-083405](https://github.com/user-attachments/assets/3c676375-9146-4c63-9ad5-629ceeccec6a)

### Version

5.7.0

### 日志和配置文件

[debug.zip](https://github.com/user-attachments/files/17426089/debug.zip)
[gui.json](https://github.com/user-attachments/files/17426092/gui.json)
出现时间每次都是，挂了一晚上，游戏没掉线，但就是停在地图界面不动

### 配置信息

win11 23H2，mumu模拟器12，1920*1080,dpi280，帧率60，截图增强已开启，光谱加速推理开启，gtx1650

**Comment by Saratoga-Official** [comment]
Duplicate of ＃10323
老bug了，目前没人修
