### ISSUE TITLE
LD截图增强增加对高分辨率的支持

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#10835]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用LD截图功能时，如果使用2560*1440这种高分辨率，会报错，实际截图速度大概是三四百毫秒。

### 有什么好的想法？

增加对高分辨率的支持。

### 其他内容

高帧率实际上对LD截图增强并无影响，我雷电模拟器设置的165FPS（不知道为啥实际会跑在170多FPS上），也能正常运行，截图速度只有三四十毫秒。

**Comment by Constrat** [comment]
- Framerate never had anything to do with screencap times.
- Framerate has to do with the touch operations (mainly swiping). At too low fps the swiping won't work correctly leading to a lot of other issues.
- The error and subsequent 300-400 delay means that the enhancement mode was not activated (hence the error and the slower screencapping) 

On a personal note, I know from personal experience that having a 2k / 4k monitor and not being able to play the game at that specific resolution can be tedious, but trust me the difference is minimal between 2k and 1080 (from an emulator standpoint).

**Comment by xiaoweiXX** [comment]
> * Framerate never had anything to do with screencap times.
> * Framerate has to do with the touch operations (mainly swiping). At too low fps the swiping won't work correctly leading to a lot of other issues.
> * The error and subsequent 300-400 delay means that the enhancement mode was not activated (hence the error and the slower screencapping)
> 
> On a personal note, I know from personal experience that having a 2k / 4k monitor and not being able to play the game at that specific resolution can be tedious, but trust me the difference is minimal between 2k and 1080 (from an emulator standpoint).

According to issues template, develops believe that framerate can influence LD screenshot enhancement function. Besides, this issue is an feature request, I hope develops can update high resolution support.

**Comment by ABA2396** [comment]
雷电提供的接口 CreateScreenShotInstance 在高分辨率下直接返回 null 了，找 maa 没用，我和雷电那边提了，这你只能等雷电更新

**Comment by xiaoweiXX** [comment]
> 雷电提供的接口 CreateScreenShotInstance 在高分辨率下直接返回 null 了，找 maa 没用，我和雷电那边提了，这你只能等雷电更新

有点怀疑雷电还会不会更新OpenGL的版本了。。。
雷电现在最新版是9.1.28，再更新可能也是更新Vulkan的版本。。。

**Comment by ABA2396** [comment]
不是，他两个版本是分开的，Vulkan 版本的截图增强还是今天才上的

**Comment by Rbqwow** [comment]
因为 MAA 的屎山问题 国服唯二推荐的分辨率和帧数是 720P60 和 1080P60
别的并不是不能跑 而是出过问题 所以才这么写
高分辨率下某些地方会卡住 是因为那些地方压缩之后的图片没办法 OCR 文字识别 这个影响所有截图方式
刚更新截图增强时公招炸了一大片 是因为高帧率击碎了屎山 截图变快了导致截到了多余的帧 这个只影响截图增强
写条这个是为了能先排查一下类似问题
(以及 MuMu 那边还有些别的说明 只是换到雷电这只剩这一条了

**Comment by xiaoweiXX** [comment]
> 不是，他两个版本是分开的，Vulkan 版本的截图增强还是今天才上的

那就好，我多等等吧，这两天我就先用用看已提交内存无限增多的bug修了没。

**Comment by xiaoweiXX** [comment]
> 因为 MAA 的屎山问题 国服唯二推荐的分辨率和帧数是 720P60 和 1080P60 别的并不是不能跑 而是出过问题 所以才这么写 高分辨率下某些地方会卡住 是因为那些地方压缩之后的图片没办法 OCR 文字识别 这个影响所有截图方式 刚更新截图增强时公招炸了一大片 是因为高帧率击碎了屎山 截图变快了导致截到了多余的帧 这个只影响截图增强 写条这个是为了能先排查一下类似问题 (以及 MuMu 的模板那边还有些别的说明 只是换到雷电这只剩这一条了

自从我4月份换新笔记本之后就一直用2K，目前是没发现有啥严重的bug。

**Comment by ABA2396** [comment]
2k 还行，4k 以上就会遇到导航问题了

**Comment by xiaoweiXX** [comment]
> 不是，他两个版本是分开的，Vulkan 版本的截图增强还是今天才上的

今天我检测了一下雷电的更新，版本号显示0090000啥的，我看也不是91xxxxx，以为不是雷电9.1，就点了更新。结果更新完了之后雷电版本号9.1.32.0，变成了支持vulkan的版本。我又测试了一下LD截图增强功能，发现失效了，最快截图耗时变成了140多毫秒（之前只有几十毫秒）。

下面是我的一些环境信息：

系统: Microsoft Windows 11 64位 23H2
CPU: Intel(R) Core(TM) i7-14700HX
主板: 联想 LNVNB161216
内存: 可用内存(18.1GB) 内存(29.7GB)
屏幕: 2560x1600
显卡: NVIDIA GeForce RTX 4070 Laptop GPU(20241015)【当前使用】
显卡: Intel(R) UHD Graphics(20240608)
OpenGL: 4.6.0 NVIDIA 566.03
VT:已开启
HyperV:已关闭
以管理员身份运行: 否
安装磁盘: E盘(SSD-NTFS) 可用空间(2500GB) 总空间(3815GB)
模拟器版本: 9.1.32.0(64)
运行参数: CPU(8核) 内存(6144M) 分辨率(1920x1080 DPI 280) FPS(165)
多开参数: 当前序号(0) 正在运行(1) 高速模式(1) FPS限制(60)
可用空间: 类型(手动扩充) 可用空间(5GB) 总空间(9GB)
机型: 品牌(Xiaomi) 型号(2203121C)
ROOT 权限: 关闭
模拟器路径: E:\Game\leidian\LDPlayer9\
日志路径: C:\Users\xiaoweiXX\AppData\Roaming\leidian9\log

Resource Version: 出苍白海
Resource Time: 2024/12/5 17:03:51
UI Version: v5.11.0-beta.1
Core Version: v5.11.0-beta.1
Build Time: 2024/12/6 02:06:01

![屏幕截图 2024-12-08 233426](https://github.com/user-attachments/assets/702b2b43-b937-4a0c-9b47-7094da2750bf)

[debug.zip](https://github.com/user-attachments/files/18052810/debug.zip)

重启过MAA，效果也是一样

**Comment by xiaoweiXX** [comment]
> 不是，他两个版本是分开的，Vulkan 版本的截图增强还是今天才上的

现在MAA支持Vulcan版本了吗？

**Comment by xiaoweiXX** [comment]
> 不是，他两个版本是分开的，Vulkan 版本的截图增强还是今天才上的

非截图检测的情况下速度好像正常了🧐
![屏幕截图 2024-12-08 234125](https://github.com/user-attachments/assets/a333cd64-4de7-4a01-9c81-d3628d8b2bee)

**Comment by ABA2396** [comment]
这个截图只是测一次的时间，模拟器偶尔抽风一次跑的时间多点也正常

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/c910445f-6e10-4d3e-8ef6-f6758e7a046e)

**Comment by xiaoweiXX** [comment]
> ![image](https://github.com/user-attachments/assets/c910445f-6e10-4d3e-8ef6-f6758e7a046e)
> 

我点了升级之后自动升级的是9.1.32啊，不能2K截图只支持29不支持32吧。我自己又改成2560*1600（这个像素是匹配我笔记本显示器的）还是不行，不会只支持1440P吧。

**Comment by Constrat** [comment]
2560*1600 is not 16:9. MAA only supports 16:9 resolutions, as all templates and OCR regions are taken with 16:9 clients.

**Comment by xiaoweiXX** [comment]
> 2560\*1600 is not 16:9. MAA only supports 16:9 resolutions, as all templates and OCR regions are taken with 16:9 clients.
> If you need the 2K resolution you need to lower to 2560*1440, but for the CN official we suggest a simpler 1280\*720

😱
