### ISSUE TITLE
点击maa自动弹出Microsoft store窗口

### ISSUE THREAD

**Issue by sbdmxigs** [MaaAssistantArknights/MaaAssistantArknights#10833]
### 说说你遇到的问题？

win11最新版本打不开maa，vc+与.net都下载完毕，点击maa自动弹出Microsoft store窗口提示需要下载应用，确定进入之后无任何应用可供下载
![IMG_20241017_124734](https://github.com/user-attachments/assets/3dbfd7cf-f552-4d3f-ba85-d00348933169)
![IMG_20241016_142514](https://github.com/user-attachments/assets/4545fef5-ada7-43d2-a983-ea625e26f591)

**Comment by ABA2396** [comment]
弹这个基本就是.net8没装好，确定没下错吗

**Comment by sbdmxigs** [comment]
.net8跟着maa群里面的下的，我也重新卸载安装了几次，vc+的都跟着重新卸载安装了几次，都弹这个，这个的权限也开了

**Comment by sbdmxigs** [comment]
> .net8跟着maa群里面的下的，我也重新卸载安装了几次，vc+的都跟着重新卸载安装了几次，都弹这个，这个的权限也开了

![Uploading Screenshot_2024-10-16-22-54-43-501_com.tencent.mobileqq.jpg…]()

**Comment by sbdmxigs** [comment]
![Uploading Screenshot_2024-10-16-22-54-43-501_com.tencent.mobileqq.jpg…]()

**Comment by sbdmxigs** [comment]
是因为这些权限没开完吗
![IMG_20241016_200603](https://github.com/user-attachments/assets/8b815386-fed2-4779-9c19-b58307020816)

**Comment by ABA2396** [comment]
你群里找个管理远程看看吧

**Comment by Saratoga-Official** [comment]
![EA9@AGXV0NTQQS@QRWXHV9](https://github.com/user-attachments/assets/1d7b4a95-1b1e-4460-9b8b-35fd0e2fcf47)
