### ISSUE TITLE
关于肉鸽萨米编队界面识别错误放弃探索

### ISSUE THREAD

**Issue by quarx613** [MaaAssistantArknights/MaaAssistantArknights#10836]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

肉鸽萨米选择完关卡以后
编队选择完毕
界面识别错误
开始关卡的时候
放弃探索
时间点发生在23：09：50~23：10：44之间

### Version

UI Version: v5.7.0
Core Version: v5.7.0
Build Time: 2024/10/3 14:50:57

### 日志和配置文件

[asst.bak.log.zip](https://github.com/user-attachments/files/17415022/asst.bak.log.zip)
[asst.zip](https://github.com/user-attachments/files/17415024/asst.zip)
[gui.bak.log.zip](https://github.com/user-attachments/files/17415025/gui.bak.log.zip)
[gui.zip](https://github.com/user-attachments/files/17415023/gui.zip)

### 配置信息

系统: Microsoft Windows 11 64位 23H2
CPU: AMD Ryzen 7 5700X3D 8-Core Processor           
主板: 微星 MAGB550MMORTARMAXWIFI(MS-7C94)
内存: 可用内存(3.4GB) 内存(15.9GB)
屏幕: 1920x1080
显卡: NVIDIA GeForce RTX 4070 SUPER(20240905)
OpenGL: 4.6.0 NVIDIA 561.09
VT:已开启
HyperV:已关闭
以管理员身份运行: 否
安装磁盘: E盘(SSD-NTFS) 可用空间(260GB) 总空间(631GB)
模拟器版本: 9.0.78.0(64)
运行参数: CPU(4核) 内存(4096M) 分辨率(1920x1080 DPI 280) FPS(60)
多开参数: 当前序号(0) 正在运行(1) 高速模式(1) FPS限制(60) 极致多开(0)
可用空间: 类型(自动扩充) 可用空间(25GB) 总空间(29GB)
机型: 品牌(samsung) 型号(SM-G9730)
ASTC: 开启
ROOT 权限: 开启
模拟器路径: E:\leidian\LDPlayer9\
日志路径: C:\Users\Administrator\AppData\Roaming\leidian9\log

### 截图或录屏

![3](https://github.com/user-attachments/assets/ce3ea2f2-1c03-47fa-857c-e50504b4dd9d)
![2](https://github.com/user-attachments/assets/5bb45bf9-b786-43db-a367-74b5b0ff9c38)
![1](https://github.com/user-attachments/assets/c56b5431-0f01-4433-a8f8-a065f587a3bf)

### 还有别的吗？

关于缄默德克萨斯和夜刀的放置逻辑 有优化可能吗？

**Comment by quarx613** [comment]
> 不会优化快活逻辑，以maa目前的识别方法识别不出来哪里有怪的，只会固定位置放

关于肉鸽萨米编队界面识别错误放弃探索是我的设置问题 还是电脑配置不够？

**Comment by Daydreamer114** [comment]
那个不是编队界面，那个是在编队完关卡加载的过程中要识别一下关卡的中文名；
识别失败之后放弃是符合流程的

识别失败的原因目前未知，电脑配置不够的可能性比较大

**Comment by quarx613** [comment]
> 那个不是编队界面，那个是在编队完关卡加载的过程中要识别一下关卡的中文名； 识别失败之后放弃是符合流程的
> 
> 识别失败的原因目前未知，电脑配置不够的可能性比较大

好的感谢回答 只不过没想到5700X3D+4070S的配置还是吃不透

**Comment by Daydreamer114** [comment]
具体的原因应该是识别的那一下卡了，不太要求平均配置
