### ISSUE TITLE
签到卡死bug及小建议

### ISSUE THREAD

**Issue by Black1312** [MaaAssistantArknights/MaaAssistantArknights#1084]
![5B${M RZT~BO `%AABS5$QV](https://user-images.githubusercontent.com/64343218/177231549-bf28daee-db1d-4bac-ae6b-9e1f0b994df2.png)
maa其他功能正常，但签到无法正常点击，使用的是夜神模拟器，群内也有群友出现这种情况。
建议：公招识别内增加时间提示，比如小车的3小时和资深/高资的9小时并采用醒目颜色标注。（因为我记不清小车是不是3小时，需要maa帮我一下。
感谢回复。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9042606/asst.log)

**Comment by zzyyyl** [comment]
签到确实是个问题

小车我记得没有做自动选择的操作，其它的都是固定 9 小时
还有小车一般不是 3 小时 50 分吗（？

**Comment by horror-proton** [comment]
签到卡死相关: https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/974

不过原因不完全相同, 实际上应该并不是签到的问题, 这里是连接之后没有马上进入主界面, "StartUp" 的重试次数耗尽退出了, 没有处理后续的 `CloseAnno`. 

每次重试只间隔 0.5 秒...感觉应该设置得更长, 我自己试了一下, 在没有感觉启动很卡的情况下识别到 `Terminal.png` 前都消耗了 14 次重试. 尤其是 `StartUpConnectingFlag` 之后和 `Terminal` 之后

```
[2022-07-05 05:06:18.774][INF][Px25f0][Tx24cc] {"taskchain":"StartUp","details":{"to_be_recognized":["StartToWakeUp","StartLoginBServer","StartUpConnectingFlag","Terminal","CloseAnno","OfflineConfirm","TodaysSupplies"],"cur_retry":20,"retry_times":20},"taskid":1,"class":"class asst::ProcessTask","subtask":"ProcessTask"}
```

**Comment by horror-proton** [comment]
看了下 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/974 我猜是 `StartUp` 在识别到 `Terminal.png` 之后等了 0.5 秒不巧截图到了什么每日签到的中间动画, 导致 `"TodaysSupplies"` `"CloseAnno"` 都没识别到, 于是就 `"Stop"` 了, 没有处理签到页面

**Comment by zzyyyl** [comment]
我觉得吧，加重试时间感觉可能不如加一个识别连接画面的操作（？

**Comment by zzyyyl** [comment]
woc，我知道原因了，鹰角把加载动画改了，就是 `StartUpConnectingFlag`

**Comment by horror-proton** [comment]
哦草, 还有鹰角网络几个字变重了, 我注意到启动界面有这个字变重了, 没想到 StartUpConnectingFlag 也要改

**Comment by zzyyyl** [comment]
我来整吧

**Comment by horror-proton** [comment]
然而这个 issue 是更新前出现的, `StartUpConnectingFlag.png` 的识别是正确的, 并不是因为这个原因而卡住 (我猜更新后可能更容易卡住了) @zzyyyl

**Comment by zzyyyl** [comment]
我之前网络不好的时候有时候会在下面这个界面卡超时
![Screenshot_20220706-153629](https://user-images.githubusercontent.com/74587068/177495907-f7864916-a0cd-48b1-b2b2-cb1b73e00116.png)
你可以加个模板试试，上面这张就是模拟器截的 `1280x720` 的原图

**Comment by zzyyyl** [comment]
现在主要的问题还是进主界面后没有马上显示签到页面，然后 MAA 检测到 `Terminal` 就以为成功登录了（也就是#974）

这块也许可以加个延时，就是建两个 task `pre-Terminal` 和 `Terminal` ，两个都检测 `Terminal.png` ，然后登录的时候首先进入 `pre-Terminal` 上，检测到了等几秒钟再进入 `Terminal`，没检测到就 `TodaysSupplies` 和 `CloseAnno`

**Comment by horror-proton** [comment]
对的我也是这样, 这个界面确实容易卡超时, 我暂时先放宽重试时间看看. 
因为理论上开启游戏时候的中间画面还有好几个, 不大可能每个都加模板上去

**Comment by zzyyyl** [comment]
还有下面这俩，大概可以简单用 ocr 处理一下
![Screenshot_20220706-154858](https://user-images.githubusercontent.com/74587068/177498157-673c32f9-517e-411d-9058-5b1951d5e878.png)
![Screenshot_20220706-154031](https://user-images.githubusercontent.com/74587068/177498256-4c76a25a-1d1d-44d8-b280-e7fe683d7637.png)

其他界面不会卡很久的，都是动画，时间是固定的

**Comment by horror-proton** [comment]
emm 其实这个只要增加等待时间放宽重试次数就可以解决了. 感觉疯狂塞模板不是很好的解决方法. 除非有需要做出操作的画面, 但实际上这几个图片就算识别到了还是得等着...
甚至 `StartUpConnectingFlag` 也不是必要的
