### ISSUE TITLE
关于MuMu截图增强模式删除`屏幕编号`设置

### ISSUE THREAD

**Issue by MoYuRuan** [MaaAssistantArknights/MaaAssistantArknights#10856]
### 说说你遇到的问题？

首先，我知道maa是不支持后台保活的，但我还是开了后台保活（有需求）。但是，通过对屏幕编号的调整，是可以做到正常使用的。这次更新后，取消了实例编号与屏幕编号，导致在开后台保活后屏幕编号为0（即模拟器桌面），无法截取方舟画面。
希望在下个版本将该设置再次显示出来。欧内该，我什么都会做的😭

**Comment by MoYuRuan** [comment]
MAA版本v5.8.0-beta.1
MUMU版本v4.1.0（3407）

**Comment by Saratoga-Official** [comment]
我记得新版应该加了对后台包活的支持 所以才把序号删了，你这怕是bug

**Comment by Rbqwow** [comment]
这次是公测版所以没发省流版更新日志 加上bot干坏事把一条commit日志去掉了

beta1 加了后台保活适配 填完路径和 adb 地址就能直接用了

**Comment by snk18952** [comment]
我用5.7好像是有编号的。
但是我想知道你屏幕编号是怎么填的？（填0的话是主页，填1的话截图失败
如果顺利的话是不是可以单个mumu开其他应用，然后让方舟在后台被截图？

**Comment by MoYuRuan** [comment]
填2我记得。
反正一个个填，然后截图测试，能截到就能用。
如果多开要记得是第几个窗口，填n+1应该就可以了

**Comment by MoYuRuan** [comment]
> 这次是公测版所以没发省流版更新日志 加上bot干坏事把一条commit日志去掉了
> 
> beta1 加了后台保活适配 填完路径和 adb 地址就能直接用了 俩编号都会自动获取

我是用保活来多开的（cpu不支持我用多开器，开了会卡死），这就导致编号不只0和1。

**Comment by MoYuRuan** [comment]
> 我用5.7好像是有编号的。 但是我想知道你屏幕编号是怎么填的？（填0的话是主页，填1的话截图失败 如果顺利的话是不是可以单个mumu开其他应用，然后让方舟在后台被截图？

填2我记得。
反正一个个填，然后截图测试，能截到就能用。
如果多开要记得是第几个窗口，填n+1应该就可以了

**Comment by ABA2396** [comment]
现在截图截的是顶部窗口，而且原来就算用后台保活也不可能同时多开啊，触控是不支持的。

**Comment by MoYuRuan** [comment]
> 现在截图截的是顶部窗口，而且原来就算用后台保活也不可能同时多开啊，触控是不支持的。

的确是这样。但我用maa不是来刷日常的，所以在使用maa时我不会多开。但现在的情况是只开一个方舟都用不了

**Comment by ABA2396** [comment]
@MistEO

**Comment by MistEO** [comment]
log 呢

**Comment by MoYuRuan** [comment]
beta.2版本已修复该BUG

**Comment by ABA2396** [comment]
然而情况是b2啥都没改）

**Comment by MoYuRuan** [comment]
真...真修了吗？

**Comment by MoYuRuan** [comment]
现在发现了真正的问题：如果存在更多的方舟，只识别第一个方舟
