### ISSUE TITLE
IS#4's originium ingot investment program does not invest, but instead go into the investment screen, then quit the run (PlayCover)

### ISSUE THREAD

**Issue by TranMK** [MaaAssistantArknights/MaaAssistantArknights#10853]
### The problems you have encountered?

Downloaded newest update of (v5.7.0) and MAA is on v3.1.0, the plan to invest ingots goes well, combats are perfect save for occasional emergency runs, but after it reaches rogue trader, it enters the investment screen, does not go into the secondary screen for investment, instead quits out of the run and ends it without investing any ingot. 
The settings I used for the run is in the image below. 
I don't know Chinese, so I'm at a disadvantage and have to use Google Translate. I have not found a way to change language to English as of the time of writing.
Any help for either of these issues would be heavily appreciated.
![image_2024-10-18_174428077](https://github.com/user-attachments/assets/f03a5b88-54d6-495d-a4e5-1641a1fec5b6)

**Comment by Daydreamer114** [comment]
Considering this issue as a bug, we may need your log file. Please try to find "文件" or "Document" on the top-left corner of the screen, click "打开日志文件夹" of "Open the Log Filter", and upload any ".log" file.

**Comment by Daydreamer114** [comment]
I would suggest you create a new issue using "bug-report" template to give us further information.

**Comment by Daydreamer114** [comment]
Continued in #10855
