### ISSUE TITLE
自动战斗时自动编队选取干员错误，导致战斗中卡部署

### ISSUE THREAD

**Issue by MCasdfghjk** [MaaAssistantArknights/MaaAssistantArknights#10858]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

使用自动战斗功能-自动编队-选取医疗干员时，会出现列表显示选取纯烬艾雅法拉(图1)，但游戏内实际选取的闪灵(图2)，在局内部署医疗时会卡住无法部署导致失败。
关卡GO-EX-2 ，作业代码maa://42484

### Version

Resource Version:追迹日落以西
MAA Version:v5.8.0-beta1

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17438977/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17438978/asst.log)
[gui.log](https://github.com/user-attachments/files/17438979/gui.log)
[gui.json](https://github.com/user-attachments/files/17438992/gui.json)
问题出现时间 2024.10.19 01:36 :24

### 配置信息

操作系统:Win 11专业版22H2 22621.2428
模拟器:MUMU12 分辨率720p(DPI 240)60FPS,开启截图增强
开启GPU加速推理，GPU:AMD Radeon(TM) Graphics  (AMD R7 4700ge的核显)

### 截图或录屏

![图1](https://github.com/user-attachments/assets/cc4ecfab-a05b-4947-9b2e-bfe9c56f19f9)

![图2](https://github.com/user-attachments/assets/33da8480-c6ad-4ed5-b7a2-14d7573522c7)

**Comment by Saratoga-Official** [comment]
Duplicate of ＃10825
