### ISSUE TITLE
使用新的截图方案降低截图用时

### ISSUE THREAD

**Issue by aixx999** [MaaAssistantArknights/MaaAssistantArknights#10868]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

在使用MAA连接实体设备运行时，MAA总是提示我“截图用时过长”。但在我使用同样依赖adb的屏幕控制软件scrcpy时，屏幕的画面和触控几乎是实时的。

### 有什么好的想法？

能否考虑使用scrcpy的技术方案进行截图，降低不支持截图增强功能的设备的截图用时？附scrcpy的技术分析：https://juejin.cn/post/6844904097796079624

**Comment by ABA2396** [comment]
scrcpy 有损压缩，模板匹配会出问题，不考虑。

**Comment by aixx999** [comment]
> scrcpy 有损压缩，模板匹配会出问题，不考虑。
我是说采用这个技术方案，先push jar到手机，然后推流的方式把延迟降低下来。你说的有损压缩是对画面的处理部分，和传输方案无关。

**Comment by aixx999** [comment]
> scrcpy 有损压缩，模板匹配会出问题，不考虑。

我是说采用这个技术方案，先push jar到手机，然后推流的方式把延迟降低下来。你说的有损压缩是对画面的处理部分，和传输方案无关。

**Comment by Constrat** [comment]
Honestly, if you think you can do it, do it.
But we've already discussed new possibilities of reducing screen cap timings. Currently we offer quite a strong solution via Mumu (and LDPlayer [new]).
Using native Android is also most likely a pain in the ass and a feature that most of the user base doesn't / will not use, since we are limited anyway by SELinux in Android > 10, as minitouch will not work, so even if we get (example) 5 ms of delay between devices, ADBinput will be painfully slow as touch input anyway, requiring root anyway.

Returning to the first point, we greatly accept new inputs and are free to open a PR whenever you have the time :)

**Comment by aixx999** [comment]
> Honestly, if you think you can do it, do it. But we've already discussed new possibilities of reducing screen cap timings. Currently we offer quite a strong solution via Mumu (and LDPlayer [new]). Using native Android is also most likely a pain in the ass and a feature that most of the user base doesn't / will not use, since we are limited anyway by SELinux in Android > 10, as minitouch will not work, so even if we get (example) 5 ms of delay between devices, ADBinput will be painfully slow as touch input anyway, requiring root anyway.
> 
> Returning to the first point, we greatly accept new inputs and are free to open a PR whenever you have the time :)

了解，感谢您的回复。

**Comment by Rbqwow** [comment]
Scrcpy is powerful. It provides a complete solution for capturing and inputting on any version of Android and device, making it a replacement for minitouch.

However, the only problem is that MAA cannot work with lossy images. While the human eye cannot tell the difference between compressed and original images, MAA is very sensitive to this, which can result in matching failures.

Additionally, even small differences between compressed and original images can significantly increase bandwidth requirements. MuMu and LD transfer screenshots using memory, which offers high I/O performance, but scrcpy cannot.

Back to MAA, most of the recognition process runs on the CPU, with GPU acceleration take a little part. You may notice that enabling screenshot enhancements during Copilot consumes a lot of CPU resources, which also limits the screenshot speed.

省流：换了也没什么太大优点 有损、带宽、性能是三个绕不过的坎
不过也不是完全不能实现 SRC星铁速溶茶就做的很好
但毕竟这是个开源东西 那俩截图增强也够用 日子也就这样过着了

> 考虑有损的话，要求是完全不能使用颜色识别，不能对小图标进行模板匹配，否则有损图片下会错误
> 然后scrcpy并没有想象中地好，实际发现设置10fps的视频流，收到的截图延迟是200ms
> 讨论一下才发现这是香农定理，普通截图是调用才执行截图，而scrcpy是持续输出的视频流
> 我是觉得现在有mumu和雷电的专属截图，scrcpy该扔扔
> —— LmeSzinc

---

或许你想问为啥我非要先说段英语再说点汉语
我也不知道 边走路边打字打着打着就成这样了
就当照顾照顾外国老哥)
