### ISSUE TITLE
关于肉鸽抓取角色的意见

### ISSUE THREAD

**Issue by 2352719595** [MaaAssistantArknights/MaaAssistantArknights#10860]
### 说说你遇到的问题？

现在的maa不会在抓取角色时选择临时招募的角色，希望后续优化一下抓取角色的优先度。

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/d0077b1b-792e-4a4e-8839-8e7a4c7af267)


https://maa.plus/docs/zh-cn/protocol/integrated-strategy-schema.html
#10807
