### ISSUE TITLE
关于使用理智药以及碎石回理智方面

### ISSUE THREAD

**Issue by zhwe83** [MaaAssistantArknights/MaaAssistantArknights#1087]
不√理智药只√石头的情况下在需要碎石的时候会识别为刷理智任务完成而停止
两者都√，但理智药选择使用量为0的情况下依然会在需要碎石的时候识别为任务完成而停止

**Comment by ABA2396** [comment]
所以为什么会有要碎石而不用理智药的需求呢

**Comment by zhwe83** [comment]
因为理智药吃完了（

**Comment by zzyyyl** [comment]
那只要勾上理智药就行了

**Comment by zhwe83** [comment]
勾上了，一样会不碎石就判断任务完成

**Comment by zzyyyl** [comment]
> 勾上了，一样会不碎石就判断任务完成

你是不是设置了理智药=0？

**Comment by zzyyyl** [comment]
听起来有点像bug，不过应该不会啊（
也许你可以传一下日志文件

**Comment by zzyyyl** [comment]
> 对，设置的理智药=0

那就是你还有理智药

也就是说，你想在有理智药的情况下，不用理智药但是碎石。
但是maa的逻辑是，必须优先使用理智药，不能在理智药没用完的情况下碎石。
也就是说其实这不是bug（
#1089 已经在UI上避免了勾选碎石但不勾选理智药的情况了
