### ISSUE TITLE
日服干员 阿罗玛 识别错误

### ISSUE THREAD

**Issue by 53nemu** [MaaAssistantArknights/MaaAssistantArknights#10875]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

已更新最新资源
基建换人的时候无法识别阿罗玛
日服，MUMU12，1280*720

### Version

Resource Version: 先途追想
Resource Time: 2024/10/18 04:03:11
UI Version: v5.7.0
Core Version: v5.7.0
Build Time: 2024/10/3 15:50:57

### 日志和配置文件

没有gui.bak
[asst.log](https://github.com/user-attachments/files/17450657/asst.log)
[gui.json](https://github.com/user-attachments/files/17450658/gui.json)
[gui.log](https://github.com/user-attachments/files/17450659/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17450661/asst.bak.log)

### 配置信息

日服，MUMU12，1280*720
GPU加速开启，1660TI

**Comment by Manicsteiner** [comment]
其他服务器的资源更新不只包括在常规的资源更新里，干员名称替换这种数据的在task.json里，目前只会跟随程序版本更新。
此问题请使用10月11日及以后的版本，比如 v5.8.0-beta.1。
