### ISSUE TITLE
官服切换账号功能无法正确选中账号

### ISSUE THREAD

**Issue by HYY1116** [MaaAssistantArknights/MaaAssistantArknights#10878]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在MAA当中的开始唤醒选项卡里，填入需要切换的账号后，若当前登陆账号并非选中账号，则会滑动寻找账号，但是无法正确点击账号进行登陆，若当前账号为选中账号，则登陆可以正常进行

### Version

Resource Version: 追迹日落以西
Resource Time: 2024/10/16 17:03:52
UI Version: v5.8.0-beta.1.d008.g0d6ad34b9
Core Version: v5.8.0-beta.1.d008.g0d6ad34b9
Build Time: 2024/10/19 22:28:26

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/17451274/gui.log)
[asst.log](https://github.com/user-attachments/files/17451286/asst.log)
[gui.json](https://github.com/user-attachments/files/17451293/gui.json)

10月20日开始出现这个问题，在10月20日开始进行的任务中，仅有11:00与3:00进行的任务成功，因为当前登陆账号与切换目标账号相同

### 配置信息

操作系统:Win10
模拟器参数：雷电模拟器9.0.77 1280*720 240dpi 60FPS
未开启截图增强
GPU推理：Tesla P4

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/0e9ae02b-e90c-4f78-abcb-e68c40b187b7)
我操嘞这玩意到底是怎么识别成这种东西的

**Comment by ABA2396** [comment]
现在最简单的办法就是你只填手机尾号后四位，这个要改不一定能改好，我先试试看

**Comment by HYY1116** [comment]
> 现在最简单的办法就是你只填手机尾号后四位，这个要改不一定能改好，我先试试看

更新beta.2后能正常切换账户了

**Comment by ABA2396** [comment]
b2把官服和b服的登录分开了，官服因为只有手机号，所以就用纯英文模型了
