### ISSUE TITLE
信用购买错误

### ISSUE THREAD

**Issue by G-aay** [MaaAssistantArknights/MaaAssistantArknights#10888]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

![新建 BMP 图像](https://github.com/user-attachments/assets/e3cf835c-5da8-43e8-9b56-af6a359ef090)

之前基建还用巫恋龙舌兰搓玉

### Version

Resource Version: 追迹日落以西
Resource Time: 2024/10/11 21:28:55

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17460560/asst.bak.log)
[gui.json](https://github.com/user-attachments/files/17460563/gui.json)
[asst.log](https://github.com/user-attachments/files/17460569/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17460571/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17460572/gui.log)

### 配置信息

mumu版本 :V4.1.0 (3407),截图增强开启

**Comment by G-aay** [comment]
[Uploading asst.bak.log…]()
时间大概早上8点多

**Comment by G-aay** [comment]
[asst.bak.log](https://github.com/user-attachments/files/17460844/asst.bak.log)

**Comment by Saratoga-Official** [comment]
的确没上传对。除了asstlogbak都打不开

**Comment by G-aay** [comment]
[asst.log](https://github.com/user-attachments/files/17468282/asst.log)

[gui.bak.log](https://github.com/user-attachments/files/17468287/gui.bak.log)

[gui.json](https://github.com/user-attachments/files/17468355/gui.json)


[gui.log](https://github.com/user-attachments/files/17468291/gui.log)

**Comment by G-aay** [comment]
> 的确没上传对。除了 asstlogbak都打不开 不行建议搞个百度网盘什么链接也行

令人疑惑，为什么就没传成功，佬可有教我？

**Comment by Saratoga-Official** [comment]
> > 的确没上传对。除了 asstlogbak都打不开 不行建议搞个百度网盘什么链接也行
> 
> 令人疑惑，为什么就没传成功，佬可有教我？

可以了，问下你出问题的大致时间

**Comment by Saratoga-Official** [comment]
再重传一下asstbaklog，我推测你是昨天早上出的问题，现在由于时间关系，那段记录到bak里面了

**Comment by G-aay** [comment]
昨天早上8点多

**Comment by G-aay** [comment]
[asst.bak.log](https://github.com/user-attachments/files/17468464/asst.bak.log)
