### ISSUE TITLE
建议恢复可以使用户多开MAA功能

### ISSUE THREAD

**Issue by Eloise412** [MaaAssistantArknights/MaaAssistantArknights#10886]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

MAA版本；
UI Version: v5.8.0-beta.2
Core Version: v5.8.0-beta.2
Build Time: 2024/10/21 02:54:25
更新到该版本后开启第二个MAA会显示“同一路径下只能启动一个实例”的提示框，而之前版本是没有的，我有两个号习惯了同时开启两个MAA对两个模拟器实例执行相同任务，这样多号玩家刷图速度会快一些，建议恢复可以多开的功能。

**Comment by ABA2396** [comment]
https://maa.plus/docs/zh-cn/manual/connection.html#maa-和模拟器多开

**Comment by Constrat** [comment]
Aka, just copy paste the MAA folder.
Example:
![{B7F64930-FB1A-4602-82E3-424C29AF00B8}](https://github.com/user-attachments/assets/28f9ff08-9672-4ca6-af00-8cf70d038538)

**Comment by TimCrownie** [comment]
> Aka, just copy paste the MAA folder. Example: ![{B7F64930-FB1A-4602-82E3-424C29AF00B8}](https://private-user-images.githubusercontent.com/56174894/378392474-28f9ff08-9672-4ca6-af00-8cf70d038538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NDA3NzMsIm5iZiI6MTcyOTU0MDQ3MywicGF0aCI6Ii81NjE3NDg5NC8zNzgzOTI0NzQtMjhmOWZmMDgtOTY3Mi00Y2E2LWFmMDAtOGNmNzBkMDM4NTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE5NTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhOGZhNTZkNTNiMGY5YzcyN2RjYzZmYjlhZjc4ZWM5MzU1ZTQ5MGM4MjRmY2FmYjBkZWRmMTY3NjYzODY0NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5zzvF4dzZxfTCk4RkHf2CKSGS8SLlGuNnQ1NNYz_xZg)
I'm sorry, but nobody's drive space is free.
![image](https://github.com/user-attachments/assets/d1040642-6539-4028-9139-21b64041cfa3)
PS. My MAA used to be a just 500MB folder.

**Comment by Constrat** [comment]
You do know that's mainly just debug right?
MAA dir:
![{9C561953-3B86-4275-9802-98138D12FF64}](https://github.com/user-attachments/assets/c20e6989-6093-4b5a-bb59-d617743c7ee4)
debug folder:
![{DC329F85-7EA7-422D-8E6A-0006ABE8969B}](https://github.com/user-attachments/assets/178f350e-21d4-45ce-b983-81c438b122ad)
