### ISSUE TITLE
MAA运行时填满磁盘空间会导致配置清空

### ISSUE THREAD

**Issue by woqucao** [MaaAssistantArknights/MaaAssistantArknights#10897]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

我一边开MAA，一遍开下载软件，把文件下载到和MAA所在的磁盘中。因为文件过大，磁盘空间一个字节都不剩。第二天发现MAA进程退出（我没有设置执行后MAA自动退出），并且设置全部清空

### Version

UI Version: v5.7.0
Core Version: v5.7.0
Build Time: 2024/10/3 14:50:57

### 日志和配置文件

config ：[gui.json](https://github.com/user-attachments/files/17473749/gui.json)
debug：
[asst.bak.log](https://github.com/user-attachments/files/17473756/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17473758/asst.log)
[gui.log](https://github.com/user-attachments/files/17473759/gui.log)

翻了一下gui.bak.log没有,问题时间：2024/10/21-2024/10/22

### 配置信息

操作系统win11
版本23H2
模拟器品牌 MUMU
模拟器分辨率 1920x1080
DPI 240 
帧率60

**Comment by Daydreamer114** [comment]
你把你自己的盘炸了……
你希望 maa 干啥吗

**Comment by woqucao** [comment]
> 你把你自己的盘炸了…… 你希望 maa 干啥吗
但是配置为啥也丢了？

**Comment by Saratoga-Official** [comment]
> > 你把你自己的盘炸了…… 你希望 maa 干啥吗
> 
> 但是配置为啥也丢了？

磁盘都满了配置还能存住吗

**Comment by woqucao** [comment]
> > > 你把你自己的盘炸了…… 你希望 maa 干啥吗
> > 
> > 
> > 但是配置为啥也丢了？
> 
> 磁盘都满了配置还能存住吗
担心是之前有配置，现在都没了

**Comment by Saratoga-Official** [comment]
归根结底还是你的使用问题，要正常使用磁盘空间足够配置丢了还行，这种我感觉没必要修，现在配置丢了也不能恢复配置了
