### ISSUE TITLE
肉鸽可关闭技能连点问题

### ISSUE THREAD

**Issue by immunity-spy** [MaaAssistantArknights/MaaAssistantArknights#10894]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

肉鸽模式里诸如ew3技能、山2技能，使用maa时候会在技能可关闭时候直接关闭

### 有什么好的想法？

希望能识别角色头顶标识来控制开关，或者拥有可关闭技能的角色有技能使用间隔

**Comment by Daydreamer114** [comment]
有识别，而且识别模型正在重新训练

开几次技能都是写好的，像山2固定只开一次，如果开多了的话是bug

**Comment by Saratoga-Official** [comment]
提个bugissue，提交log，否则不解决
