### ISSUE TITLE
指定材料为`异铁`时开始任务后闪退

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#1090]
![image](https://user-images.githubusercontent.com/74061867/177316827-09be83d6-e63c-40e6-a8d5-6feadded83e3.png)
如图所示，在进行如下操作时，当按下开始后maa开始连接模拟器后，maa未响应并自动关闭
![image](https://user-images.githubusercontent.com/74061867/177317184-3af2dcbf-03be-4f17-85ba-7fd85a9450d0.png)

![image](https://user-images.githubusercontent.com/74061867/177317066-4550e3c8-60b3-441d-aa21-377cbcd3f058.png)
关卡为2-1
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9045929/asst.log)
ps：此bug可无限复现，非随机

**Comment by ntgmc** [comment]
补充：经过排除 好像是指定材料的问题 一打开就会卡死

**Comment by ABA2396** [comment]
叫我有啥用.jpg

**Comment by ABA2396** [comment]
我刚试了下没报错来着，清空log再发个试试？

**Comment by ntgmc** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9046565/asst.log)

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/177334710-9984204c-6831-48d9-b3de-74e45663dc6c.png)

**Comment by ntgmc** [comment]
为啥你的选项顺序不一样

**Comment by zzyyyl** [comment]
选项顺序可以拖动

**Comment by zzyyyl** [comment]
？？？为什么你可以
[asst-yitie.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9046569/asst-yitie.log)
[asst-固源岩.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9046571/asst-.log)

**Comment by ntgmc** [comment]
> 选项顺序可以拖动

我的不行哎

**Comment by ntgmc** [comment]
> [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9046565/asst.log)

新打开一次的log

**Comment by zzyyyl** [comment]
@ntgmc 你要不试试看其他材料行不行（？

**Comment by ABA2396** [comment]
日志好像啥都没提示来着，让玛丽来看吧

**Comment by MistEO** [comment]
> > > > 选项顺序可以拖动
> > > 
> > > 
> > > 我的不行哎
> > 
> > 
> > 不行的话先点一下试试，选中文字右边一点的地方
> 
> 试过了，确实不行，就当我没说过吧

不在运行的时候才能拖动

**Comment by zzyyyl** [comment]
玛丽nb！

**Comment by ntgmc** [comment]
> @ntgmc 你要不试试看其他材料行不行（？

其他好像都行
