### ISSUE TITLE
maa无法导航至关卡9-19刷理智

### ISSUE THREAD

**Issue by RyuGaGotoku3** [MaaAssistantArknights/MaaAssistantArknights#10904]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

maa进了第九章划到一半又划回去了在s9-1的地方

### Version

Resource Version: 追迹日落以西
Resource Time: 2024/10/23 17:03:29

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/17492836/gui.log)
[asst.log](https://github.com/user-attachments/files/17492840/asst.log)
[asst.bak.log](https://github.com/user-attachments/files/17492842/asst.bak.log)
[gui.json](https://github.com/user-attachments/files/17492843/gui.json)

### 配置信息

Window 10 Home 22H2
Mumu 12 1280×720 DPI 240 帧率60
开启截图增强 开启GPU推理 GTX 745

### 截图或录屏

https://github.com/user-attachments/assets/7fab8af3-a4d4-4dcf-b54a-561127549a00

**Comment by ABA2396** [comment]
试试看把 resource/tasks.json 中的 ChapterSwipeToTheRight 里 maxTimes 的值改成 10
