### ISSUE TITLE
助战更新后一直无法刷OF-1

### ISSUE THREAD

**Issue by SAYUII** [MaaAssistantArknights/MaaAssistantArknights#10909]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

助战界面更新后，借助战刷OF-1时不能自动点击确认助战干员，画面定在确认选择助战干员页面，后续所有流程全部无法执行，只要手动帮MAA点击确认助战干员，后续流程全部正常。无其他异常。

### Version

UI Version: v5.7.0
Core Version: v5.7.0
Build Time: 2024/10/3 14:50:57

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17508881/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17508905/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17508927/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17508958/gui.log)
异常时间：每日第一次使用MAA，最近一次：2024-10-24 09:10:09

### 配置信息

Windows 11 家庭中文版   23H2   22631.4391
MUMU12 V4.1.0（3407）
2560*1440（DPI360） 帧率60 
截图增强、GPU加速推理情况不详

### 截图或录屏

![image](https://github.com/user-attachments/assets/22be2a56-dd54-46d0-b2c7-e8d6e8eaf85e)

**Comment by Saratoga-Official** [comment]
在公测版已修复此问题，等正式版发布或者更新公测即可
