### ISSUE TITLE
改进建议：肉鸽刷开局可以增加难度选择

### ISSUE THREAD

**Issue by kaphisalur** [MaaAssistantArknights/MaaAssistantArknights#10916]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

玩肉鸽都是玩12级难度，第一次用这个刷开局功能，结果发现自动给我选最高难度开始了，然而我并不想玩15级，所以希望对刷开局流程进行改进

### 有什么好的想法？

在自动肉鸽设置面板增加新开局的难度选择

### 其他内容

与MAA改进无关：

想问问大家都是用什么模拟器玩的，我用雷电模拟器玩会有闪退情况，用mumu模拟器挂机会有卡死的情况
给模拟器分配的6核处理器，9GB运存，显卡渲染模式Vulkan

**Comment by Saratoga-Official** [comment]
Duplicate of #6494

**Comment by Saratoga-Official** [comment]
关于模拟器的讨论可以加入官方QQ群和频道交流
