### ISSUE TITLE
肉鸽刷开局，源石锭满了时会在第一层商店直接退出

### ISSUE THREAD

**Issue by AlearXS** [MaaAssistantArknights/MaaAssistantArknights#10917]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题。高级设置里有选项，但是感觉逻辑不是很符合直觉，可以调整一下逻辑。

### 有什么好的想法？

可以改成储备源石锭达到上限时停止改为仅投资模式下生效。

**Comment by status102** [comment]
有选项能关，请关上
