### ISSUE TITLE
萨卡兹肉鸽的一种更高效存钱方法

### ISSUE THREAD

**Issue by SplendidNova** [MaaAssistantArknights/MaaAssistantArknights#10911]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

众所周知，10月23日萨卡兹肉鸽更新了内容拓展一，新增了三个分队。
我发现其中 “**_点刺成锭分队_**” 的效果是 “**_每进入新的一层_**，源石锭+5，**_首次刷新不消耗构想并出现诡意行商_**，击败<年代之刺>额外获得2源石锭。” 
于是我诞生了一个想法：选这个分队开局，招募时甚至不用招募干员，进一层后第一个节点直接刷新成商店就可以存钱，存完直接退出。
事实证明我这个想法是可行的，并且我在B站也找到了和我这个想法相同的视频：https://www.bilibili.com/video/BV1ojyfYGEKE
手动存钱比起以前没有区别（都要等1分钟的冷却，通常会剩20秒左右），但是maa用这个方法存钱比以前的方法效率会高非常多。因为程序运行识图需要时间，总会超过1分钟的冷却时间，但即便如此也比以前要经过4个节点快得多。

**Comment by SplendidNova** [comment]
想了一下，貌似直接用模拟器自带的操作录制都能实现……

**Comment by Saratoga-Official** [comment]
你可以看下最新的pr

**Comment by Windsland52** [comment]
charred老师已经写完了，就是上面这个，不开截图增强运行接近1分钟

**Comment by SplendidNova** [comment]
试用了一下，完全匹配我的想法。感谢。
