### ISSUE TITLE
获取信用及购物里，借助战打of-1赚信用，会卡住

### ISSUE THREAD

**Issue by nandehututu** [MaaAssistantArknights/MaaAssistantArknights#10915]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

获取信用及购物里，借助战打of-1赚信用，会卡住。
不知道什么原因，会卡在这个名片界面，
(不确定是不是因为每个人不同，观察了以下好像并没有点击招募助战的按钮，可能应该是没有识别到特征)
至于触发频率，好像更新5.7后每天都会卡在这，也不知道是不是加了好友的原因

![image](https://github.com/user-attachments/assets/23d15243-e450-4c8e-8f1a-fc6a3024f44e)
![image](https://github.com/user-attachments/assets/3881cbb7-4c64-46e5-9fc9-3cfd7c7e8270)

### Version

UI Version: v5.7.0
Core Version: v5.7.0
Build Time: 2024/10/3 14:50:57

### 日志和配置文件

[gui.bak.log](https://github.com/user-attachments/files/17515378/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17515379/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17515380/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17515382/asst.log)
[gui.json](https://github.com/user-attachments/files/17515383/gui.json)
![image](https://github.com/user-attachments/assets/3881cbb7-4c64-46e5-9fc9-3cfd7c7e8270)
出现时间是11点36分00到11点37分46秒超时提示错误，然后就跳程序错误直接结束

### 配置信息

win10ltsc 1809，雷电9模拟器，1280*720，DPI240，帧率60
雷电9模拟器，没有开启LD截图增强。
有开启gpu加速推理，gpu 580 8g，但是经过测试，这个选项不影响，开不开都卡在那里

### 截图或录屏

没有找到那时刻的截图，提供一个录屏，希望能找到问题所在。
录频分两次对比，第一次不可行，第二次我自己鼠标点击一次就可以继续运行脚本
10m传不了视频，在下面蓝奏云
https://nandehutu.lanzouo.com/ib6OB2dawmid

**Comment by Rbqwow** [comment]
Duplicate of #10909
