### ISSUE TITLE
5.8版本信用商店购物成功后无操作需手动点击确认

### ISSUE THREAD

**Issue by lele09-53** [MaaAssistantArknights/MaaAssistantArknights#10928]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

信用商店购买商物品成功后的获得物资界面无操作，需手动点击后才继续购买操作

### Version

v5.8.0

### 日志和配置文件

[gui.json](https://github.com/user-attachments/files/17530140/gui.json)
[asst.bak.log](https://github.com/user-attachments/files/17530119/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17530116/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17530117/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17530118/gui.log)

### 配置信息

win10系统家庭中文版，蓝叠模拟器5，帧率240，DPI240，分辨率1600*900。GPU加速未开启

**Comment by lele09-53** [comment]
您好，这是我第一次在github反馈问题，如有错误还请谅解

**Comment by ABA2396** [comment]
改好了，重启下 MAA

**Comment by lele09-53** [comment]
非常感谢！
