### ISSUE TITLE
购买信用界面购买一个道具之后就停止工作

### ISSUE THREAD

**Issue by icescotch** [MaaAssistantArknights/MaaAssistantArknights#10929]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

信用购买界面购买一个商品之后商品展示界面停顿住
![4 C_8F39DZQHXB1OJ@5X1U2](https://github.com/user-attachments/assets/47af3c11-ea66-42cf-9d75-9257a16e8f3e)

### Version

UI Version: v5.8.0
Core Version: v5.8.0
Build Time: 2024/10/26 16:43:45

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17530202/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17530203/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17530204/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17530205/gui.log)

### 配置信息

windows11 21h2 
mumu6
1920*1080  60帧
未开启gpu加速

### 截图或录屏

![4 C_8F39DZQHXB1OJ@5X1U2](https://github.com/user-attachments/assets/4f716a33-4d2d-4941-8b7e-bae9acdf73f2)

**Comment by ABA2396** [comment]
改好了，重启下 MAA
