### ISSUE TITLE
活动关卡界面无法进入，疑似等待时间过少

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#1092]
如题
具体内容与 #1091 相同
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9047071/asst.log)
看了一下日志等待时间只有500ms，这次活动进入的过场动画较长
从出现按钮“实验基地”到按钮停止移动，至少经过3000ms，建议将等待时间改为3500ms或4000ms
![image](https://user-images.githubusercontent.com/74061867/177350035-5d879730-d918-4b32-94b6-9ec94515479c.png)

**Comment by ABA2396** [comment]
修了下加了个重复判断，根据提交修改下task.json试试，我这里复现不了bug

**Comment by ntgmc** [comment]
> 修了下加了个重复判断，根据提交修改下task.json试试，我这里复现不了bug

更改json后可以了
