### ISSUE TITLE
萨卡兹肉鸽中，维什戴尔技能策略错误

### ISSUE THREAD

**Issue by slowpoke007** [MaaAssistantArknights/MaaAssistantArknights#10926]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在萨卡兹肉鸽中，维什戴尔的技能总是在开启后立刻被手动关闭。这在99.99%的关卡中都是明显错误的做法，且都会导致损失目标点生命值甚至直接战败。

### Version

v5.7.0

### 日志和配置文件

[debug.zip](https://github.com/user-attachments/files/17529811/debug.zip)
[gui.json](https://github.com/user-attachments/files/17529812/gui.json)

### 配置信息

Windows 10，Mumu 12，1920*1080，DPI 280，帧率 30
未启用增强
未开启

**Comment by ABA2396** [comment]
技能识别模型的问题，有3%的改了把可关闭的图标当成技能图标然后使用，现在在重新训练模型
