### ISSUE TITLE
5.8版本，mumu6，1-7入口疑似错误（卡再章节界面）

### ISSUE THREAD

**Issue by icescotch** [MaaAssistantArknights/MaaAssistantArknights#10927]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

5.8更新之后进入1-7入口时会卡再1-7那一章的界面
![J$)U (PV$D)I9N9~ZR(VZP4_tmb](https://github.com/user-attachments/assets/d0f7f8f6-2abc-49cf-8583-a3dbb5424ba0)

### Version

UI Version: v5.8.0
Core Version: v5.8.0
Build Time: 2024/10/26 16:43:45

### 日志和配置文件

2024.10.26  18：03出现  上传文件时maa已经关闭
[asst.bak.log](https://github.com/user-attachments/files/17529945/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17529946/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17529947/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17529948/gui.log)

### 配置信息

windows11 21h2
mumu6
1920*1080  
帧率60
未开启gpu加速

### 截图或录屏

![J$)U (PV$D)I9N9~ZR(VZP4_tmb](https://github.com/user-attachments/assets/429c4bf0-2075-47ec-b20f-6e4463d4eb4c)

**Comment by ABA2396** [comment]
改好了，重启下
