### ISSUE TITLE
归龙潮和新月同行小助手 在B站上面看到模拟器能直接运行1998但是没有这两款游戏的开源项目大佬能不能写一个进行开源

### ISSUE THREAD

**Issue by qincenhua** [MaaAssistantArknights/MaaAssistantArknights#10936]
### Before raising the issue...

- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I'm probably sure this is a new feature/suggestion and not a bug encountered (please attach logs if you're not sure)

### The problems you have encountered?

归龙潮和新月同行小助手 希望也能写一个一件长草的神器同样在模拟器运行我是在B站上面看到了有类似的但是没有大佬开源所以来此题建议希望能得到各位大佬的解决方案我是自己不会写没办法见到已经写出来的大佬是崩坏三的用的就是模拟器运行

### Any good ideas?

希望不仅仅只是模拟器运行也可以输入其他命令在都是同样打开exe应用程序供用户两种打开方案小助手如果无法解决先做出来abk模拟器的希望能解放双手自动过去行我是在B站上面看到1998实现了快速过剧情以及打斗的一些画面有所启发来这里问问题

### Additional

希望有大佬能写出来并且第一时间通知我要开源一起用才是最好用的使用的初衷能解放双手

**Comment by Saratoga-Official** [comment]
你可以去MAAFW看看有没有人开发，这里是明日方舟的
