### ISSUE TITLE
生息演算主页无任何动作，其他功能皆正常

### ISSUE THREAD

**Issue by 0001dddq** [MaaAssistantArknights/MaaAssistantArknights#10947]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

生息演算主页无任何动作，其他功能皆正常
![屏幕截图 2024-10-27 203344](https://github.com/user-attachments/assets/63499563-8e0d-45c9-9fce-1338deaede27)

### Version

UI Version: v5.8.1
Core Version: v5.8.1
Build Time: 2024/10/26 21:58:00

### 日志和配置文件

10月27日 21：04-21：05

### 配置信息

win11 
23h2
mumu模拟器2560*1440 360 60
未开启
核显

### 截图或录屏

![Uploading 屏幕截图 2024-10-27 203344.png…]()

**Comment by 0001dddq** [comment]
![Uploading 屏幕截图 2024-10-27 203344.png…]()

**Comment by 0001dddq** [comment]
![Uploading 屏幕截图 2024-10-27 203344.png…]()

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/8f9234b7-4a3d-4c8a-953f-3edede7b0eda)
