### ISSUE TITLE
什么时候支持萨卡兹肉鸽新分队，欧内该

### ISSUE THREAD

**Issue by chixiaoyan-single** [MaaAssistantArknights/MaaAssistantArknights#10943]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

商店分队可以稳定1分钟左右刷源石碇这个挺好的

**Comment by ABA2396** [comment]
写好了没发版
