### ISSUE TITLE
Fight任务日志中的掉落报告会出现不明项目，显示名字为furni

### ISSUE THREAD

**Issue by ttxs25830** [MaaAssistantArknights/MaaAssistantArknights#1094]
疑似为战斗中博士等级提升导致
![窗口截图](https://user-images.githubusercontent.com/57991009/177380780-1ec081fa-e43b-48f6-9279-eeb62ad7df76.png)
请求添加相关中文翻译

**Comment by MistEO** [comment]
这个是家具，企鹅物流那边得要上传这个名字

**Comment by ttxs25830** [comment]
那至少显示的时候显示“家具”吧，毕竟日志是给人看的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月6日(周三) 上午8:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] Fight任务日志中的掉落报告会出现不明项目，显示名字为furni (Issue #1094)




 
这个是家具，企鹅物流那边得要上传这个名字

**Comment by zzyyyl** [comment]
furni=furniture
~还挺好理解的（~
