### ISSUE TITLE
因如“UU加速器”等软件可能导致adb服务器被占用可行的解决办法

### ISSUE THREAD

**Issue by HaSiGeRen** [MaaAssistantArknights/MaaAssistantArknights#10942]
### 说说你遇到的问题？

我在使用MAA之前和使用MAA的过程中发现如果启动了 “UU加速器”的加速服务 可能会导致模拟器断开并且无法重连的情况。
Ps：此情况可以通过重启电脑简单解决

![192EF9384AA6557547C3AE113028EB6D](https://github.com/user-attachments/assets/af6dcb4f-41b5-42b3-acf4-21c38f45950e)
图中我先启动了MAA，在**11:34:50之后**启动了UU加速器，一如往常地出现模拟器断开无法重连的情况。

通过对 **常见问题文档** 的查询得知原因是 “**已经存在活动的adb 服务器**”
同时参照 **常见问题文档** 解决办法结束所有adb服务器进程之后MAA可以正常启动运行
链接：https://docs.qq.com/doc/DREVCRFBtY0FIdWxP

![90BB2F2083121C1604DF30E63302C282](https://github.com/user-attachments/assets/be300b94-d73e-4703-8228-8a6fef6ceb47)
图中我于 **12:24:33之前** 启动了UU加速器的加速服务，并于 **12:24:33** 启动adb调试服务器 发现 已经存在活动的adb服务器 。输入adb kill-server关闭所有adb服务器后于 **12:27:18** 重新启动MAA发现可以正常运行
（图中 12:27:20 出现连接失败的原因笔者尚未查明，但结果上并未异常，遂暂时搁置）

因此，笔者确定导致问题产生的原因是**启动“UU加速器”的加速服务导致占用adb服务器**

按照常见问题文档的解决办法，用户需要频繁地参照文档结束其他已活动的adb服务器，笔者认为还是比较繁琐。因此笔者开始寻求一劳永逸的解决办法，通过上网查询得到MuMu模拟器的问题帮助
链接：https://mumu.163.com/help/20240321/35047_1144608.html

即在UU加速器的 **节点选择** 页面取消选中**“进程模式”**，之后重新选择节点并保存。（保险起见笔者依然建议重启一次电脑）
![35fcac9f-2a62-4d27-9f1a-f55c3bc53b63](https://github.com/user-attachments/assets/c2baad85-aacf-4d21-9308-c8af2f7d2017)

之后笔者进行测试发现问题已得到解决
![ABF733BCA9E4F27C6CBD544693368447](https://github.com/user-attachments/assets/c5e3a748-a597-4945-b7a9-4bcaf0d37603)

笔者希望这种问题能写进常见问题文档中供用户参考，最后有相关问题欢迎大家友好讨论。这是笔者第一次提交issue，如有不足与疏漏还请多多包涵多多指正。

**Comment by ABA2396** [comment]
![Screenshot_2024-10-27-13-24-13-479_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/45e284c0-1b6d-47ac-a81b-44396eb86fc7)

![Screenshot_2024-10-27-13-24-40-154_com.android.chrome.jpg](https://github.com/user-attachments/assets/87ef2862-80e5-403a-98f6-c849afdc327a)

其实文档里已经提到了）

**Comment by ABA2396** [comment]
@HoshinoAyako

**Comment by HoshinoAyako** [comment]
okk马上弄进去
