### ISSUE TITLE
格雷伊与承曦格雷伊基建冲突问题

### ISSUE THREAD

**Issue by yione1** [MaaAssistantArknights/MaaAssistantArknights#1095]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9050373/asst.log)
两者在自动基建中的优先级冲突导致发电站无法自动基建
![QQ浏览器截图20220706080736](https://user-images.githubusercontent.com/108771447/177436413-283e472c-8035-492f-9a76-e91399c5b125.jpg)
![QQ浏览器截图20220706080722](https://user-images.githubusercontent.com/108771447/177436417-cef0d225-be5a-4a1c-98f4-2313a7ce666f.jpg)

MUMU模拟器，MAA版本4.0.4

**Comment by MistEO** [comment]
v4.0.5-beta.1 fixed

**Comment by smiledrunk** [comment]
修了但没完全修，在宿舍识别干员休息时格雷伊和异格会报错然后把在工作的卸下来[
![Baidu IME_2022-7-7_7-6-30](https://user-images.githubusercontent.com/64001920/177657673-f1744894-60c6-4b1f-8947-ea1525c44c68.jpg)
](url)

**Comment by smiledrunk** [comment]
[
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9059128/asst.log)
](url)

**Comment by ABA2396** [comment]
> 格雷伊在上班 异格心情不满会被放在宿舍 把上班的挤掉 v4.0.5-beta.1 玛丽加油 再修修

只能说如果一直用maa换班应该就不会出现异格心情不满的情况）

**Comment by SnailZq** [comment]
> > 格雷伊在上班 异格心情不满会被放在宿舍 把上班的挤掉 v4.0.5-beta.1 玛丽加油 再修修
> 
> 只能说如果一直用maa换班应该就不会出现异格心情不满的情况）

作为一只懒狗当然一直都用的maa，正式版本这个bug还有 当我发现这个bug的时候我的两个电站已经旷工好久了
然后我换了测试版本，还是不行，基建关于异格这块问题还有，克洛丝也有可能同时登场（不过只要干员够多应该触发不了）
