### ISSUE TITLE
生息演算30min后Sub error and not ignored Tales

### ISSUE THREAD

**Issue by pein0saga** [MaaAssistantArknights/MaaAssistantArknights#10957]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/user-attachments/assets/ce7b7777-e43b-403b-9f27-c5c74148a33a)

本来无法正常运行生息，后来更新了资源&换成了maatouch正常运行了30min后报错Sub error and not ignored Tales

### Version

![image](https://github.com/user-attachments/assets/6a732f21-cdc0-465f-92e0-63e15da79d71)

5.8.1

20241027

### 日志和配置文件

 主要内容在asst.bak.log里面

[gui.json](https://github.com/user-attachments/files/17540145/gui.json)

[asst.bak.log](https://github.com/user-attachments/files/17540185/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17540186/asst.log)
[gui.log](https://github.com/user-attachments/files/17540187/gui.log)

16:24:29 gui上报错

### 配置信息

win10 22H2

Bluestacks 5

![image](https://github.com/user-attachments/assets/34745452-6a01-422b-adc8-257fca1c0a34)

![image](https://github.com/user-attachments/assets/c632a75a-06ca-49a6-8c84-d9b765b051de)

![image](https://github.com/user-attachments/assets/c216d8c0-fcd3-4b6d-bc85-5cba5214e6f2)

AMD NO！卡无法用GPU加速

### 截图或录屏

![image](https://github.com/user-attachments/assets/c19cf0c7-6da0-4dd1-91bc-e4c99f473273)

### 还有别的吗？

![image](https://github.com/user-attachments/assets/a27df626-0b63-4c4f-b6ad-58e6db082262)

ANDROID 11

**Comment by Daydreamer114** [comment]
cc @Alan-Charred 
他点开三个点了，也点到那个删除存档了，但看样子没弹出来两次确认？
需不需要允许 sub error，给 next 加兜底？（就是容易错误后死循环）
![image](https://github.com/user-attachments/assets/a5ea6c79-0264-404b-a02f-a030d4f0accb)

**Comment by Alan-Charred** [comment]
> cc @Alan-Charred 他点开三个点了，也点到那个删除存档了，但看样子没弹出来两次确认？ 需不需要允许 sub error，给 next 加兜底？（就是容易错误后死循环） ![image](https://private-user-images.githubusercontent.com/74444214/380730417-a5ea6c79-0264-404b-a02f-a030d4f0accb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNTcwNjcsIm5iZiI6MTczMDE1Njc2NywicGF0aCI6Ii83NDQ0NDIxNC8zODA3MzA0MTctYTVlYTZjNzktMDI2NC00MDRiLWEwMmYtYTAzMGQ0ZjBhY2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDIzMDYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhODVmZDI3MzIyZDIwZjc5OGRiMzEwNWEzOGU3ZDRkMDJmNmFmZjg5YjYxZTRlMTI0MDQ2ZmZjYjIwZDNjNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ScRpJx1tUJADqDDfYw7zD7EwkHblAoee95Ei-OM6kRc)

最后的截图令我感到困惑，感觉更像是滑动了一下屏幕导致点到了其他地方。用户的截图延迟够长，不存在截图太快等导致问题。我只能简单加一重保险试试，但我私下里认为这不是 MAA 操作的问题。

**Comment by Daydreamer114** [comment]
Completed with #10965
