### ISSUE TITLE
希望美服适配能尽快跟进

### ISSUE THREAD

**Issue by frankchenfu** [MaaAssistantArknights/MaaAssistantArknights#1096]
首先，非常感谢maa开发组。
在我看来，美服和国服的图标、点击位置等几乎完全相同，个人认为从图像识别角度，二者没有太大区别，但是美服这边一直使用不了国服的信用商店、公招等功能，剩余功能仅与按键精灵相当。
因此，我希望在开发组有时间时，能将基础功能适配一下美服（只是公招基建这些，打关卡这种UI差别大的应该比较困难，我也不想麻烦各位大佬）
最后，再次感谢你们。

**Comment by zzyyyl** [comment]
其实好像打关也差不多（？
目前用的是图像匹配，所以用不了，之后改用文字识别，已经在做了（
~你先别急.jpg~

**Comment by MistEO** [comment]
没人手，慢慢来吧

**Comment by StanXM** [comment]
我的美服开始不了 不知道为什么

**Comment by MistEO** [comment]
基本功能现在都有了，慢慢来吧
