### ISSUE TITLE
萨卡兹肉鸽 相遇事件 选择`希望时代`替代`美愿时代`

### ISSUE THREAD

**Issue by hdbbbb** [MaaAssistantArknights/MaaAssistantArknights#10962]
### 在提问之前...

- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

在相遇事件中，选择希望时代的涂鸦比美愿时代可以更好刷新非战斗节点，但maa会选择美愿时代，导致增加自动刷源石锭的时间。

### 有什么好的想法？

希望修改为选择希望时代

**Comment by yu-0420** [comment]
resource/roguelike/Sarkaz/encounter/default.json

**Comment by Daydreamer114** [comment]
请以 bug-report 的方式重新提交 issue

**Comment by Daydreamer114** [comment]
maa 尚未适配内容拓展 I ，出现错误选择应视为 bug。你可以等 maa 完成适配，也可以以 bug-report 的形式重新提交 issue。
