### ISSUE TITLE
请求禁止maa自动基建排班动用训练室中的干员

### ISSUE THREAD

**Issue by Roguelife1215** [MaaAssistantArknights/MaaAssistantArknights#10969]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

这几天给剑陈专三，因为本身是maa重度用户，基本很少自己玩方舟，老是忘记点下一级，然后maa自动排版会反复把在训练室挂机的剑陈扔过去找线索，导致小鸟技能失效

### 有什么好的想法？

希望禁止maa自动基建排班动用训练室中的干员

**Comment by Iven-0628** [comment]
最近几天我也遇到了相似的问题
澄闪和艾丽妮在训练室，MAA将澄闪派去发电站
并且我已经勾选了“不将已进驻干员放入宿舍”

**Comment by ABA2396** [comment]
#10968

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/98ff67fa-5412-4633-850d-4d9667e440fc)
已有功能。但如果电脑比较卡的话可能会卡出基建导致失效，如果是开了遇到的话上面这个pr修了，如果没开仔细看看设置
