### ISSUE TITLE
为手动更新资源添加提示，在已有资源为最新时不更新资源

### ISSUE THREAD

**Issue by Cassy-Lee** [MaaAssistantArknights/MaaAssistantArknights#10960]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

点击资源更新后除了三个更新相关按钮灰掉以外什么提示也没有
网络不好时，没有任何提示，仅有的变化为三个按钮重新变为可用状态
资源更新完成后如果有任务仍在进行，按钮会保持在不可用状态

### 有什么好的想法？

为手动更新资源添加提示，就像版本更新那样
对资源版本进行检查

**Comment by Cassy-Lee** [comment]
> 这玩意只有你开了自动安装更新包才会直接重启，不然会问你要不要重启

好的，之前没发现，已更新

**Comment by ABA2396** [comment]
GitHub对单文件下载不太友好，国内裸连下完整包还行，那个单文件的域名是直接连不上的，完整包也就8M大小，检不检查感觉影响不是很大。

等下加个下载失败的提示

**Comment by Cassy-Lee** [comment]
> 国内裸连下完整包还行，那个单文件的域名是直接连不上的

- 作为人在国外的个例，我是连得上的人之一
- 或许会有人使用代理（比如完全连不上github的地区）
- 我看MAA貌似有提供对外服的支持，或许也可能有连得上Github外国玩家使用MAA

另外，就算不单独请求版本信息文件，也可以在完整仓库下载完成后检查其中的版本信息文件，避免不必要的重启

**Comment by ABA2396** [comment]
3d2307fced4f85b129e3dc6db52397f964f8d9eb
