### ISSUE TITLE
在最新版本5.8稳定出现MaaCore.dll 加载失败导致应用崩溃的问题，退回到5.6.x版本又恢复正常，没有做更多测试就不提bug了

### ISSUE THREAD

**Issue by henryli2002** [MaaAssistantArknights/MaaAssistantArknights#10972]
### 说说你遇到的问题？

报错信息：
'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)   at MaaWpfGui.Services.MaaService.AsstGetVersion()   at MaaWpfGui.ViewModels.UI.SettingsViewModel..cctor()   --- End of inner exception stack trace ---   at MaaWpfGui.ViewModels.UI.SettingsViewModel.<>c.<.ctor>b__12_0(String s)   at System.Linq.Enumerable.WhereArrayIterator1.MoveNext()   at System.Collections.Generic.HashSet1.UnionWith(IEnumerable1 other)   at System.Collections.Generic.HashSet1..ctor(IEnumerable1 collection, IEqualityComparer1 comparer)   at System.Linq.Enumerable.DistinctIterator1.ToArray()   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()   at lambda_method13(Closure, IRegistrationContext)   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)   at StyletIoC.Internal.Container.Get[T](String key)   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)   at MaaWpfGui.Main.Bootstrapper.Configure()   at Stylet.BootstrapperBase.Start(String[] args)   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)   at MaaWpfGui.App.OnStartup(StartupEventArgs e)   at System.Windows.Application.<.ctor>b__1_0(Object unused)   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Saratoga-Official** [comment]
![Screenshot_2024-10-27-22-22-39-922_com.tencent.mobileqq.jpg](https://github.com/user-attachments/assets/9e61cedc-9fba-47cc-acff-10d46c70cf00)

![Screenshot_2024-10-27-12-31-54-249_com.github.android-edit.jpg](https://github.com/user-attachments/assets/3208a59c-b79e-48df-99d8-fa6a28117ff7)
