### ISSUE TITLE
请求自动肉鸽功能刷源石锭时选择点刺成碇分队提高刷锭效率

### ISSUE THREAD

**Issue by 2jack5657** [MaaAssistantArknights/MaaAssistantArknights#10970]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

萨卡兹肉鸽更新了点刺成碇分队，可以刷新节点出商店然后投资，一般第一二层存钱完后直接退出即可。

**Comment by Saratoga-Official** [comment]
已经有了，没发正式版
