### ISSUE TITLE
Mac版，萨卡兹肉鸽在思维负荷超出上限时，进行舍弃思绪时卡死

### ISSUE THREAD

**Issue by growyyyyyy** [MaaAssistantArknights/MaaAssistantArknights#10973]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

Mac版，萨卡兹肉鸽在思维负荷超出上限时，进行舍弃思绪时卡死
![Uploading 01D73A680D596933C5902465F6499484.png…]()
![248039082F6487F2574B56D85C1E080F](https://github.com/user-attachments/assets/8106b017-d0aa-4375-af7f-9b0de82e95b2)

### Version

MAA v5.8.1 是当前的最新版本。

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17565533/asst.log)

没搜索到另外的文件
[asst.bak.log.zip](https://github.com/user-attachments/files/17565550/asst.bak.log.zip)

### 配置信息

苹果原生的playcover

### 截图或录屏

![248039082F6487F2574B56D85C1E080F](https://github.com/user-attachments/assets/1f9b2106-20d1-4d3e-b675-8c779e952f91)

**Comment by growyyyyyy** [comment]
![01d73a680d596933c5902465f6499484](https://github.com/user-attachments/assets/77defd55-7da6-4b38-ba5f-f74bdea39526)

**Comment by Alan-Charred** [comment]
您好，抱歉回复迟了。iOS 端的材质清晰度略有下降，因而模版匹配分数没有过阈值。现为 iOS 端将阈值从 0.95 降低到 0.9 以尝试修复这个问题。热更新那边我也会推一个修复。
