### ISSUE TITLE
指定材料选择失效

### ISSUE THREAD

**Issue by StellAr117** [MaaAssistantArknights/MaaAssistantArknights#1097]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9051958/asst.log)

指定材料无法选择，只剩下之前用过的一个选项
![image](https://user-images.githubusercontent.com/104726749/177477775-ed617e72-ff9a-4415-a5f5-4e258f6ac944.png)

**Comment by MistEO** [comment]
你把输入的内容删掉就有了
