### ISSUE TITLE
繁中服無法自動悖論模擬

### ISSUE THREAD

**Issue by B11215058** [MaaAssistantArknights/MaaAssistantArknights#10983]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

依照文檔操作無法自動戰鬥悖論模擬

### Version

v5.8.1

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17581197/asst.log)

### 配置信息

MuMu 12 截图增强

### 截图或录屏

![8B465F3133764C98A8BC5CA664542FF4](https://github.com/user-attachments/assets/84e954ad-0c9f-4961-bcab-eb16c63c9dc0)

**Comment by ABA2396** [comment]
你这日志报的 minitoucher is not initialized
是触控出问题了，重启maa和模拟器后还有这个问题吗

**Comment by B11215058** [comment]
> 你這日誌報的minitoucher is not initialized 是觸控出問題了，重啟maa和模擬器後還有這個問題嗎

解決了
