### ISSUE TITLE
已下运行库重启重装仍是喜报

### ISSUE THREAD

**Issue by MHKSI** [MaaAssistantArknights/MaaAssistantArknights#10985]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

![屏幕截图 2024-10-31 174508](https://github.com/user-attachments/assets/6ef97dac-f9c4-4e5a-9a9a-22a6e0a26aa7)
![屏幕截图 2024-10-31 182056](https://github.com/user-attachments/assets/6d1f3581-9d80-4ba3-a546-2e7c57cf4a9c)
![屏幕截图 2024-10-31 182101](https://github.com/user-attachments/assets/62199c17-2f1f-485e-8e83-acc8aa0baca7)
如图我应该已经安装完了吧？重启重装后仍不行，群u说在mumu文件夹重下maa，现在就在这个路径还是报喜。

### Version

群里下的最新版。

### 日志和配置文件

[gui.json](https://github.com/user-attachments/files/17586380/gui.json)
[gui.log](https://github.com/user-attachments/files/17586382/gui.log)
刚重装完maa，debug里面只有一个文件

### 配置信息

win11，mumu12，已开启，不知道gpu加速推理是啥，gpu是NVIDIA GeForce RTX 4060 Laptop

### 截图或录屏

![屏幕截图 2024-10-31 174508](https://github.com/user-attachments/assets/856acfde-fd37-4052-a2f1-b9cd48db76f6)
![屏幕截图 2024-10-31 182056](https://github.com/user-attachments/assets/a9853448-10d2-41c6-8033-0b6c6b11a20c)
![屏幕截图 2024-10-31 182101](https://github.com/user-attachments/assets/2be74bcf-00f1-47d5-a0f5-b4955ccd1f47)
上面发过了我不确定是否有问题再发一遍吧谢谢

**Comment by Saratoga-Official** [comment]
哪个群教的在mumu文件夹重装。。。是maa群吗

**Comment by Saratoga-Official** [comment]
issue我关了，如果还不行去群里找我，我是管理员萨拉托加
