### ISSUE TITLE
繁中服 點火石辨識異常(銀心湖列車)

### ISSUE THREAD

**Issue by Raymond9487** [MaaAssistantArknights/MaaAssistantArknights#10994]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

使用MAA Copilot作業( 網址https://prts.plus/?op=30688 )，點火石無法放下及辨識。

### Version

UI Version: v5.8.1
Core Version: v5.8.1
Build Time: 2024/10/26 21:58:00
Resource Version: 銀心湖列車
Resource Time: 2024/10/31 21:29:06

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17598734/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17598736/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17598737/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17598738/gui.log)
[gui.json](https://github.com/user-attachments/files/17598743/gui.json)

### 配置信息

操作系統:Windows 10
模擬器:藍疊模擬器
分辨率:1280*720

**Comment by Manicsteiner** [comment]
请使用 v5.9.0-beta.1 及以后的版本
