### ISSUE TITLE
基建换班存在干员差异时不能换班

### ISSUE THREAD

**Issue by 2333tech** [MaaAssistantArknights/MaaAssistantArknights#10999]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在换班配置文件中开启按顺序入住后，如果换班前后进驻干员存在差异，则无法选择顺序并确认，卡死在选择干员处。
推测原因：此次更新后已选中干员不会自动被排列到干员列表最前端，导致MAA无法排列顺序。

### Version

UI Version: v5.9.0-beta.1
Core Version: v5.9.0-beta.1
Build Time: 2024/10/31 23:56:49
Resource Version: 追迹日落以西
Resource Time: 2024/11/1 10:33:47

### 日志和配置文件

19:50:28处出现问题
[asst.bak.log](https://github.com/user-attachments/files/17599274/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17599276/asst.log)
[gui.json](https://github.com/user-attachments/files/17599277/gui.json)
[gui.json](https://github.com/user-attachments/files/17599293/gui.json)

### 配置信息

版本	Windows 10 IoT 企业版 LTSC
版本号	21H2
安装日期	‎2023/‎2/‎24
操作系统内部版本	19044.5011
体验	Windows Feature Experience Pack 1000.19060.1000.0

MUMU12 V4.1.2 1920*1080 DPI280
截图增强开启；165帧率上限；不使用GPU加速推理

### 截图或录屏

https://github.com/user-attachments/assets/5572d375-3032-4e27-a409-7b4abc53a029

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/5fec8ead-df6f-4113-94e7-7fbf3b6b8bd3)
是有这个问题，改个 roi 就好了
