### ISSUE TITLE
[建议] 自动公招增加1小时或者3小时50分选项用来刷1星

### ISSUE THREAD

**Issue by BlackNorton** [MaaAssistantArknights/MaaAssistantArknights#10992]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

自动公招现在有指定时间的设置（比如对三星7:40而非9:00），那能否增加自动设置时间为3:50（出1星可选的最长时间），或者直接默认1小时开刷，手动刷小车的潜能太痛苦了

**Comment by Saratoga-Official** [comment]
![P0@RC%VD0~(QMKB(7 _LDR](https://github.com/user-attachments/assets/7e00b062-820b-406f-9fb6-26efc8444b67)
