### ISSUE TITLE
台服適配後的功能測試

### ISSUE THREAD

**Issue by Arcelibs** [MaaAssistantArknights/MaaAssistantArknights#1099]
之前看作者有更新台服支持後(https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1082)
針對了幾個功能進行了測試

**開始喚醒**
助手執行後無反應，一段時間後顯示完成，但不會啟動明日方舟

**自動公招**
進入公招畫面後又回到主頁面循環

**基建換人**
目前看起來正常有成功換人，但會在此畫面與基建畫面反覆循環
![image](https://user-images.githubusercontent.com/49543451/177518720-764b581b-204d-4f5d-b824-fe9c143244f4.png)

附上三項功能的LOG紀錄
[asst_基建換人.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9053539/asst_.log)
[asst_公招.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9053540/asst_.log)
[asst_開始喚醒.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9053541/asst_.log)

系統是Window10 繁體中文，有設定非地區語言顯示
![image](https://user-images.githubusercontent.com/49543451/177520147-ceecaeb0-2dce-4915-8cca-526c065266e9.png)

**Comment by MistEO** [comment]
没有说支持台服啊，目前仍在开发中 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1082

**Comment by Arcelibs** [comment]
> 没有说支持台服啊，目前仍在开发中 #1082
> 
> 这个 pr 仍是激活状态，没有被合并

仔細一看還真的還沒合併，我搞錯了抱歉
