### ISSUE TITLE
删除config中的个性化数据（比如SMTP密码），对config做匿名化处理

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#11002]
### 说说你遇到的问题？

刚才在https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10996 中 @ABA2369 提醒我SMTP密码露出来了，我认为这种隐私数据应该从config删除或者做匿名化处理，因为提交issues需要上传config，而config所有人都能访问到，这样做很不安全。或者在提交issues的时候不再要求上传涉及隐私数据的config文件。

**Comment by ABA2396** [comment]
不是在 log 里，是在你的 gui.json 里）

**Comment by xiaoweiXX** [comment]
> 不是在 log 里，是在你的 gui.json 里）

差不多的意思，就是要么上传文件对个人信息做匿名化处理，要么在提交issue的时候不再要求上传含有个人信息的文件。

**Comment by dantmnf** [comment]
这种东西大概可以放进系统凭据存储里面（
