### ISSUE TITLE
PV-10导航出现出现错误

### ISSUE THREAD

**Issue by MoguJunn** [MaaAssistantArknights/MaaAssistantArknights#11009]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

没办法刷PV-10，导航到关卡页面能自动划到关卡所在位置，但是不会点进关卡,PV-其他关卡测试可刷

### Version

Resource Version: 追迹日落以西
Resource Time: 2024/11/1 22:03:06
UI Version: v5.9.0-beta.1
Core Version: v5.9.0-beta.1
Build Time: 2024/10/31 23:56:49

### 日志和配置文件

[gui.json](https://github.com/user-attachments/files/17601907/gui.json)
[asst.bak.log](https://github.com/user-attachments/files/17601920/asst.bak.log)
[gui.bak.log](https://github.com/user-attachments/files/17601925/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17601940/gui.log)
[asst.log](https://github.com/user-attachments/files/17601963/asst.log)
出现大致时间点为2024.11.2 0:19之后

### 配置信息

基础信息
模拟器版本 :  4.1.0.3411
模拟器磁盘（可用/总）空间 :  80GB/125GB

电脑配置
主板型号 :  Manufacturer: MECHREVO  Product: GM5HG7A
CPU :  AMD Ryzen 7 8845H w/ Radeon 780M Graphics
系统版本 :  Windows 11 64-bit Kernel 10.0.26100 （24H2）
显卡驱动 :  正常
显卡驱动型号 :  566.03 (20241015)
所有显卡 :  NVIDIA GeForce RTX 4070 Laptop GPU  |  AMD Radeon 780M Graphics  |  Microsoft Basic Render Driver
当前使用显卡 :  NVIDIA GeForce RTX 4070 Laptop GPU
安装磁盘(可用/总)空间 :  43.4GB/752.9GB
可用内存/总内存 :  12.3GB/31.3GB

分辨率 :  2560 * 1440
高帧率 :  开启
后台保活 :  关闭

ADB调试端口 :  16416
MuMu出口IP地址 :  10.0.2.15
电脑出口IP地址 :  14.26.204.188

截图增强已开启，GPU推理已开启

### 截图或录屏

https://15963574.xyz/usr/uploads/2024/11/2024-11-02%2000-42-04.mp4

**Comment by ABA2396** [comment]
改好了，重启下
