### ISSUE TITLE
资源无法更新

### ISSUE THREAD

**Issue by XGI-silence** [MaaAssistantArknights/MaaAssistantArknights#11005]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

更新资源失败，多次点击按键均无果，手动从仓库下载资源复制到对应文件夹后重新打开依然无法更新

### Version

资源版本：追迹日落以西
maa版本：UI Version: v5.9.0-beta.1
Core Version: v5.9.0-beta.1
Build Time: 2024/10/31 23:56:49

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17600252/asst.bak.log)

### 配置信息

[asst.log](https://github.com/user-attachments/files/17600260/asst.log)
Windows11，mumu模拟器12，开启截图增强，未开启GPU

**Comment by ABA2396** [comment]
也仓库也没更新啊）
