### ISSUE TITLE
繁中版肉鸽更新后识别不了锏, 新增关卡识别不到

### ISSUE THREAD

**Issue by kayiu131** [MaaAssistantArknights/MaaAssistantArknights#11012]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

繁中版肉鸽更新版本后识别不了锏, 开局自己有锏它也不选, 识别失败直接选山, 
道中的新增关卡识别不到, 直接不放干员卡死

### Version

Resource Version: 銀心湖列車
Resource Time: 2024/10/31 21:29:06
UI Version: v5.8.1
Core Version: v5.8.1
Build Time: 2024/10/26 21:58:00

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17604896/asst.log)
[gui.log](https://github.com/user-attachments/files/17604897/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17604898/asst.bak.log)
[gui.json](https://github.com/user-attachments/files/17604899/gui.json)
問題發生在1/11-2/11的肉鴿部分

### 配置信息

MUMU 12
2560*1440 (DPI 360)
60幀
截图增强开启
GPU 加速推理: NO

**Comment by Manicsteiner** [comment]
log里的识别看起来都没问题，只是task的替换还没有更新，请使用 v5.9.0-beta1 及以后的版本
