### ISSUE TITLE
请求增加肉鸽功能

### ISSUE THREAD

**Issue by Lelouch-Lyu** [MaaAssistantArknights/MaaAssistantArknights#11014]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

萨米肉鸽刷了6W个节点也没出黑舞鞋太惨了！。。

### 有什么好的想法？

在所有主题肉鸽中新增一项功能：选择某个藏品（如果技术方面允许的话也可以选择多个藏品），在挂机过程中如果遇到选择的藏品，该藏品获取优先级最高。    辛苦各位技术大佬了！

**Comment by Daydreamer114** [comment]
Duplicate of #10032
