### ISSUE TITLE
无法自动领取幸运墙的合成玉奖励

### ISSUE THREAD

**Issue by Genicur** [MaaAssistantArknights/MaaAssistantArknights#11015]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在勾选领取限时开采许可的每日合成玉奖励和领取幸运墙的每日合成玉奖励后，不能自动领取。

### Version

UI Version: v5.9.0-beta.1.d015.g0dced4556
Core Version: v5.9.0-beta.1.d015.g0dced4556
Build Time: 2024/11/1 22:05:44

### 日志和配置文件

传不上。。应该也没事（？

### 配置信息

24H2 mumu12 720p 60帧 开启截图增强 GPU：3060

**Comment by zhongfly** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11008

**Comment by Genicur** [comment]
> #11008

我搜的好运墙（XD，我的问题

**Comment by SherkeyXD** [comment]
因为 yj 改了外面的文字，没识别上（幸运墙变好运墙了）
