### ISSUE TITLE
基建换班宿舍无限循环

### ISSUE THREAD

**Issue by antidote02** [MaaAssistantArknights/MaaAssistantArknights#11010]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

基建换班宿舍无限循环
![屏幕截图 2024-11-02 004833](https://github.com/user-attachments/assets/9693181a-fe0e-46b1-ae11-6792516340c5)
![屏幕截图 2024-11-02 004858](https://github.com/user-attachments/assets/dd5e11ae-b791-4c7f-a569-1b84ec241a2a)
![屏幕截图 2024-11-02 004910](https://github.com/user-attachments/assets/f44cdba8-62b7-4bac-9c7b-c9ecedd440ff)

### Version

资源日期：2024/11/1 22:03:06
构建日期：2024/11/1 22:05:44

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17602228/asst.log)
[gui.log](https://github.com/user-attachments/files/17602245/gui.log)
[gui.json](https://github.com/user-attachments/files/17602257/gui.json)

### 配置信息

Windows 11 24H2 26100.2161
MuMu 12 启用 MuMu 截图增强模式
模拟器分辨率 1280 x 720
DPI 480
帧率 144
使用 GPU 加速推理 NVIDIA GeForce RTX 3080

### 截图或录屏

https://github.com/user-attachments/assets/f7d4c7e6-8c50-4490-a24a-53ca79520cbb

**Comment by antidote02** [comment]
干员冲突
清空宿舍后，重新只执行宿舍
![屏幕截图 2024-11-02 010835](https://github.com/user-attachments/assets/f2985617-ad4b-4391-87e7-1c281f1e0fb9)
[asst.log](https://github.com/user-attachments/files/17602394/asst.log)
[gui.log](https://github.com/user-attachments/files/17602396/gui.log)
[asst.bak.log](https://github.com/user-attachme
[gui.json](https://github.com/user-attachments/files/17602399/gui.json)
nts/files/17602397/asst.bak.log)

**Comment by ABA2396** [comment]
点一下设置里的资源更新等重启应该就能用了，基建可能跑的时间会长点但应该不会卡住。

**Comment by antidote02** [comment]
嗯解决了

**Comment by antidote02** [comment]
非工作区蹭信赖依然是放不满的
![屏幕截图 2024-11-02 050712](https://github.com/user-attachments/assets/659f9f02-dacb-4c1d-8909-d28af5ad1861)
![屏幕截图 2024-11-02 050717](https://g
[asst.log](https://github.com/user-attachments/files/17604192/asst.log)
ithub.com/user-attachments/assets/065a897b-95c7-4237-8846-fc9643be2674)
[asst.bak.zip](https://github.com/user-attac
[gui.log](https://github.com/user-attachments/files/17604194/gui.log)
hments/files/17604193/asst.bak.zip)
[gui.json](https://github.com/user-attachments/files/17604197/gui.json)
