### ISSUE TITLE
雷电管理器进肉鸽选完人进图软件就直接闪退，也找不到日志文件

### ISSUE THREAD

**Issue by 7i7iqaqa** [MaaAssistantArknights/MaaAssistantArknights#1101]
找了找原因是没有以管理员身份运行，姑且补充一下
软件目录在C盘的可能都有这个烦恼（大概）

**Comment by MistEO** [comment]
不可能没日志的，不然怎么选的人。。

和软件在哪个盘没有关系，因为我们是用的 adb 连接

**Comment by 7i7iqaqa** [comment]
> 

猜测是没有管理员权限导致没法在C盘创建文件导致崩溃，我清理智的时候就没这个问题，不生成日志文件也没事，但是选完人一进图就是稳定闪退了，看了下文件创建时间可能是map文件和aria2c.exe的问题？

**Comment by horror-proton** [comment]
应该确实是 map 文件的问题, 日志是用文件流写的, 写入失败不会出其他问题. 但创建 map 用的是 `std::filesystem::create_directory`, 而这个是会抛出异常的

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/ee3c6aee67634b68bfba2d40a4107b0146c6ac77/src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp#L480-L500

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/ee3c6aee67634b68bfba2d40a4107b0146c6ac77/src/MeoAssistant/BattleProcessTask.cpp#L139-L149

这边也会抛出 exception, 但是被 async 藏起来了, `draw_future.get()` 的时候会重新吐出来, 但是下面并没有 `.get()`, `future` 析构的时候也把它吞掉了, 所以...

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/ee3c6aee67634b68bfba2d40a4107b0146c6ac77/src/MeoAssistant/BattleProcessTask.cpp#L204

**Comment by FightingFZC** [comment]
我也是这样，用管理员身份运行就行了（东西都在c盘，用的夜神模拟器）

**Comment by zzyyyl** [comment]
昨天有群友雷电打不开软件直接闪退，也没日志，下面是他的目录

![Cache_-2dae1e1f580522bc](https://user-images.githubusercontent.com/74587068/179141460-3d6b1664-0c99-4461-bebf-d9382d35e93a.jpg)

**Comment by MistEO** [comment]
> 昨天有群友雷电打不开软件直接闪退，也没日志，下面是他的目录
> 
> ![image](https://user-images.githubusercontent.com/74587068/179141954-f57116ec-4e98-4a22-afbb-dd853c393a60.png)
> 
> 连 gui.json 和日志都没创建，大概是没有写权限吧（

noavx 和 c runtime 让他看看（

**Comment by zzyyyl** [comment]
他说按照群公告都操作了还是没用（

**Comment by zzyyyl** [comment]
<details>
<summary>长图预警</summary>

![image](https://user-images.githubusercontent.com/74587068/179143138-0e4a12fc-670c-4ed1-a799-9936a2ffb742.png)
</details>

**Comment by horror-proton** [comment]
没有写权限应该也不会完全打不开吧

**Comment by zzyyyl** [comment]
他没gui.json，第一次打开应该要创建的吧，创建失败就寄了

**Comment by horror-proton** [comment]
`gui.json` 没创建成功好像也能打开的
