### ISSUE TITLE
蓝叠模拟器HyperV版本模拟器关闭失败

### ISSUE THREAD

**Issue by kbps1024** [MaaAssistantArknights/MaaAssistantArknights#1102]
在win11系统中使用HyperV版本蓝叠模拟器，在设定“完成后：关闭模拟器”的情况下出现提示模拟器关闭失败，且模拟器正常运行并未被关闭。
MAA使用管理员权限运行。
<img width="1634" alt="image" src="https://user-images.githubusercontent.com/56375038/177547986-5bde841a-e032-4470-afa2-d8b16609e995.png">

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9054584/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9054583/asst.bak.log)

**Comment by kbps1024** [comment]
<img width="1634" alt="image" src="https://user-images.githubusercontent.com/56375038/177547806-98c3a076-5759-4058-bcf8-c72d38eea73b.png">

**Comment by zzyyyl** [comment]
大多数模拟器都有同样的问题，#1043 有一些目前的讨论结果
