### ISSUE TITLE
无法启动MAA

### ISSUE THREAD

**Issue by jeffzhou315** [MaaAssistantArknights/MaaAssistantArknights#11020]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

打开时报错maacore.dll初始化失败并且多次尝试，debug文件只有gui.log

### Version

V5.8.1

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/17606586/gui.log)

### 配置信息

没有启动模拟器，Windows11

### 还有别的吗？

最近安装了Qt开发库

**Comment by Saratoga-Official** [comment]
安装运行库

**Comment by jeffzhou315** [comment]
![tmpD40D](https://github.com/user-attachments/assets/184573e3-efd6-4bf9-8c2e-290b7603cf11)

**Comment by Saratoga-Official** [comment]
> ![tmpD40D](https://github.com/user-attachments/assets/184573e3-efd6-4bf9-8c2e-290b7603cf11)
> 

你去常见问题里看，是vc运行库和net8，不是net4.8

**Comment by jeffzhou315** [comment]
![tmp6618](https://github.com/user-attachments/assets/3e826a51-8ffe-46de-bf12-9231c91fb1cd)
依旧跳报错

**Comment by ABA2396** [comment]
vc++呢

**Comment by jeffzhou315** [comment]
之前可以，前几天突然不行的

**Comment by jeffzhou315** [comment]
而且这边办公用的Visual studio

**Comment by ABA2396** [comment]
新版本sdk打出来的包旧版本用不了，所以要更新运行库

**Comment by ABA2396** [comment]
所以常见问题你看了没

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/d4ff990c-82b4-48b5-87d3-c4d836257636)

**Comment by jeffzhou315** [comment]
嘶

**Comment by jeffzhou315** [comment]
对不起我的问题
