### ISSUE TITLE
通过ALAS使用MAA提示动态链接库初始化

### ISSUE THREAD

**Issue by Sakuraleiying** [MaaAssistantArknights/MaaAssistantArknights#11027]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

测试发现：
UI Version: v5.7.0版本未报错

UI Version: v5.8.1
UI Version: v5.9.0-beta.2版本均报错
其中UI Version: v5.9.0-beta.1更新中提到动态链接库修复，但仍未解决该问题

报错内容：
═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     00:32:30.734 │ Start scheduler loop: 明日方舟                             
INFO     00:32:30.739 │ [Server] cn                                                
INFO     00:32:30.747 │ Bind task ['General', 'Alas', 'Maa']                       
INFO     00:32:30.750 │ Save config ./config\明日方舟.maa.json,                    
         Commission.Scheduler.Enable=True, Research.Scheduler.Enable=True,         
         Reward.Scheduler.Enable=True                                              
INFO     00:32:30.758 │ Bind task ['General', 'Alas', 'Maa']                       
INFO     00:32:30.763 │ Pending tasks: ['MaaStartup', 'MaaInfrast', 'MaaAward',    
         'MaaRoguelike']                                                           
INFO     00:32:30.765 │ [Task] MaaStartup (Enable, 2024-11-03 00:09:27)            
INFO     00:32:30.767 │ Bind task ['General', 'Alas', 'MaaStartup', 'Maa']         
INFO     00:32:31.395 │ Scheduler: Start task `MaaStartup`                         
═══════════════════════════════════════════════════════════════════════════════════
                                    MAASTARTUP                                     
═══════════════════════════════════════════════════════════════════════════════════
INFO     00:32:31.400 │ Task call: MaaStartup                                      
INFO     00:32:31.418 │ Bind task ['General', 'Alas', 'MaaStartup', 'Maa']         
INFO     00:32:31.421 │ Save config ./config\明日方舟.maa.json,                    
         MaaStartup.Scheduler.NextRun=datetime.datetime(2024, 11, 3, 0, 32, 31),   
         MaaStartup.Scheduler.Enable=True, Commission.Scheduler.Enable=True,       
         Research.Scheduler.Enable=True, Reward.Scheduler.Enable=True              
INFO     00:32:31.429 │ MAA安装路径：D:\MAA                                        
ERROR    00:32:35.413 │ OSError: [WinError 1114] 动态链接库(DLL)初始化例程失败。   
         ╭────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                        │
         │ D:\ALAS\alas.py:69 in run                                              │
         │                                                                        │
         │    67 │   │   │   if not skip_first_screenshot:                        │
         │    68 │   │   │   │   self.device.screenshot()                         │
         │ ❱  69 │   │   │   self.__getattribute__(command)()                     │
         │    70 │   │   │   return True                                          │
         │    71 │   │   except TaskEnd:                                          │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │               command = 'maa_startup'                              │ │
         │ │                     e = OSError(22,                                │ │
         │ │                         '动态链接库(DLL)初始化例程失败。', None,   │ │
         │ │                         1114, None)                                │ │
         │ │                  self = <submodule.AlasMaaBridge.maa.ArknightsAut… │ │
         │ │                         object at 0x000001E4F00CE308>              │ │
         │ │ skip_first_screenshot = False                                      │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │ D:\ALAS\submodule\AlasMaaBridge\maa.py:121 in maa_startup              │
         │                                                                        │
         │   119 │                                                                │
         │   120 │   def maa_startup(self):                                       │
         │ ❱ 121 │   │   AssistantHandler(config=self.config, asst=self.asst).sta │
         │   122 │                                                                │
         │   123 │   def maa_annihilation(self):                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ self = <submodule.AlasMaaBridge.maa.ArknightsAutoScript object at  │ │
         │ │        0x000001E4F00CE308>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\ALAS\toolkit\lib\site-packages\cached_property.py:36 in __get__     │
         │                                                                        │
         │    34 │   │   │   return self._wrap_in_coroutine(obj)                  │
         │    35 │   │                                                            │
         │ ❱  36 │   │   value = obj.__dict__[self.func.__name__] = self.func(obj │
         │    37 │   │   return value                                             │
         │    38                                                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │  cls = <class 'submodule.AlasMaaBridge.maa.ArknightsAutoScript'>   │ │
         │ │  obj = <submodule.AlasMaaBridge.maa.ArknightsAutoScript object at  │ │
         │ │        0x000001E4F00CE308>                                         │ │
         │ │ self = <cached_property.cached_property object at                  │ │
         │ │        0x000001E4F026CFC8>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\ALAS\submodule\AlasMaaBridge\maa.py:74 in asst                      │
         │                                                                        │
         │    72 │   │   │   │   │   './cache/resource/global/' + self.config.Maa │
         │    73 │   │   │   │   )                                                │
         │ ❱  74 │   │   │   AssistantHandler.load(self.config.MaaEmulator_MaaPat │
         │    75 │   │   except ModuleNotFoundError:                              │
         │    76 │   │   │   logger.critical('找不到MAA，请检查安装路径是否正确') │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ incremental_path = ['D:\\MAA\\./cache']                            │ │
         │ │             self = <submodule.AlasMaaBridge.maa.ArknightsAutoScri… │ │
         │ │                    object at 0x000001E4F00CE308>                   │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\ALAS\submodule\AlasMaaBridge\module\handler\handler.py:34 in load   │
         │                                                                        │
         │    32 │   │   AssistantHandler.Message = utils.Message                 │
         │    33 │   │   AssistantHandler.InstanceOptionType = utils.InstanceOpti │
         │ ❱  34 │   │   AssistantHandler.Asst.load(path, user_dir=path,          │
         │       incremental_path=incremental_path)                               │
         │    35 │   │                                                            │
         │    36 │   │   AssistantHandler.ASST_HANDLER = None                     │
         │                                                                        │
         │ ╭──────────────── locals ─────────────────╮                            │
         │ │ incremental_path = ['D:\\MAA\\./cache'] │                            │
         │ │             path = 'D:\\MAA'            │                            │
         │ ╰─────────────────────────────────────────╯                            │
         │                                                                        │
         │ D:\ALAS\submodule\AlasMaaBridge\module\asst\asst.py:69 in load         │
         │                                                                        │
         │    67 │   │   except KeyError:                                         │
         │    68 │   │   │   os.environ[platform_values[platform_type]['environ_v │
         │       str(path)                                                        │
         │ ❱  69 │   │   Asst.__lib = lib_import_func(str(Asst.__libpath))        │
         │    70 │   │   Asst.__set_lib_properties()                              │
         │    71                                                                  │
         │                                                                        │
         │ ╭─────────────────────────── locals ────────────────────────────╮      │
         │ │ incremental_path = ['D:\\MAA\\./cache']                       │      │
         │ │  lib_import_func = <class 'ctypes.WinDLL'>                    │      │
         │ │             path = 'D:\\MAA'                                  │      │
         │ │    platform_type = 'windows'                                  │      │
         │ │  platform_values = {                                          │      │
         │ │                    │   'windows': {                           │      │
         │ │                    │   │   'libpath': 'MaaCore.dll',          │      │
         │ │                    │   │   'environ_var': 'PATH'              │      │
         │ │                    │   },                                     │      │
         │ │                    │   'darwin': {                            │      │
         │ │                    │   │   'libpath': 'libMaaCore.dylib',     │      │
         │ │                    │   │   'environ_var': 'DYLD_LIBRARY_PATH' │      │
         │ │                    │   },                                     │      │
         │ │                    │   'linux': {                             │      │
         │ │                    │   │   'libpath': 'libMaaCore.so',        │      │
         │ │                    │   │   'environ_var': 'LD_LIBRARY_PATH'   │      │
         │ │                    │   }                                      │      │
         │ │                    }                                          │      │
         │ │         user_dir = 'D:\\MAA'                                  │      │
         │ ╰───────────────────────────────────────────────────────────────╯      │
         │                                                                        │
         │ D:\ALAS\toolkit\lib\ctypes\__init__.py:364 in __init__                 │
         │                                                                        │
         │   362 │   │                                                            │
         │   363 │   │   if handle is None:                                       │
         │ ❱ 364 │   │   │   self._handle = _dlopen(self._name, mode)             │
         │   365 │   │   else:                                                    │
         │   366 │   │   │   self._handle = handle                                │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │       _FuncPtr = <class 'ctypes.CDLL.__init__.<locals>._FuncPtr'>  │ │
         │ │          flags = 0                                                 │ │
         │ │         handle = None                                              │ │
         │ │           mode = 0                                                 │ │
         │ │           name = 'D:\\MAA\\MaaCore.dll'                            │ │
         │ │           self = <WinDLL 'D:\MAA\MaaCore.dll', handle 0 at         │ │
         │ │                  0x1e4f027b908>                                    │ │
         │ │      use_errno = False                                             │ │
         │ │ use_last_error = False                                             │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         ╰────────────────────────────────────────────────────────────────────────╯
         OSError: [WinError 1114] 动态链接库(DLL)初始化例程失败。                  
INFO     00:32:35.999 │ No provider specified, skip sending                        
 

### Version

UI Version: v5.9.0-beta.2
Core Version: v5.9.0-beta.2
Build Time: 2024/11/2 23:23:09

### 日志和配置文件

[2024-11-02_MAA.txt](https://github.com/user-attachments/files/17607708/2024-11-02_MAA.txt)

### 配置信息

Win10 MUMU12 1280*720 DPI280 60FPS
无
无

**Comment by ABA2396** [comment]
所以你vc++更新了吗

**Comment by LDVC124** [comment]
alas无法使用maa插件可能不是没有更新组件库的原因。
maa单独是可以正常运行的，只是从alas运行就会报错：动态链接库(DLL)初始化例程失败。
（已确认更新了 Microsoft.VCRedist.2015+.x64 和 Microsoft.DotNet.DesktopRuntime.8
大佬有空再看看哇



> 所以你vc++更新了吗

**Comment by LDVC124** [comment]
猜测是alas需要做一些更新吧

> alas无法使用maa插件可能不是没有更新组件库的原因。 maa单独是可以正常运行的，只是从alas运行就会报错：动态链接库(DLL)初始化例程失败。 （已确认更新了 Microsoft.VCRedist.2015+.x64 和 Microsoft.DotNet.DesktopRuntime.8 大佬有空再看看哇
> 
> > 所以你vc++更新了吗

**Comment by Saratoga-Official** [comment]
> 猜测是alas需要做一些更新吧
> 
> > alas无法使用maa插件可能不是没有更新组件库的原因。 maa单独是可以正常运行的，只是从alas运行就会报错：动态链接库(DLL)初始化例程失败。 （已确认更新了 Microsoft.VCRedist.2015+.x64 和 Microsoft.DotNet.DesktopRuntime.8 大佬有空再看看哇
> > 
> > > 所以你vc++更新了吗
> 
> 

那你去alas那边提issue问问，我们只管maa

**Comment by Sakuraleiying** [comment]
我用图吧工具箱，手动更新了全部的VC++，确保了底层文件是最新的，软件本身可以使用，但alas仍不能使用，得等alas更新了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月4日(周一) 晚上9:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 通过ALAS使用MAA提示动态链接库初始化 (Issue #11027)




  
猜测是alas需要做一些更新吧
  
alas无法使用maa插件可能不是没有更新组件库的原因。 maa单独是可以正常运行的，只是从alas运行就会报错：动态链接库(DLL)初始化例程失败。 （已确认更新了 Microsoft.VCRedist.2015+.x64 和 Microsoft.DotNet.DesktopRuntime.8 大佬有空再看看哇
  
所以你vc++更新了吗
    
那你去alas那边提issue问问，我们只管maa
