### ISSUE TITLE
生息演算无存档刷点模式下，点击<丰饶灌木林>节点后未能成功进入，卡在原地

### ISSUE THREAD

**Issue by AmyCcb** [MaaAssistantArknights/MaaAssistantArknights#11026]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

生息开始没多久就会报错
重启，删除编队，删档，开始界面都无误

### Version

UI Version: v5.8.1
Core Version: v5.8.1
Build Time: 2024/10/26 21:58:00
Resource Version: 揭幕者们
Resource Time: 2024/11/2 00:28:41

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17607610/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17607611/asst.log)
[gui.log](https://github.com/user-attachments/files/17607612/gui.log)
[gui.json](https://github.com/user-attachments/files/17607633/gui.json)

### 配置信息

Windows 11 家庭中文版  23H2
雷电9 1600*900 DPI240 60FPS
截图增强否  GPU 加速推理否

### 截图或录屏

![PV)QRT}49F~1OU8$_7C%GT](https://github.com/user-attachments/assets/572b753e-c620-4d83-a10c-2432e7515bc3)

**Comment by Alan-Charred** [comment]
您好，根据 Log，卡住的原因如下：
正常的流程是：
1. 点击 <丰饶灌木林> 节点
2. 画面向左上滑动，同时右下角出现 <开始行动> 按钮
3. 成功识别到 <开始行动> 按钮，任务继续

而您的 MAA 在第二步未能识别到开始行动按钮，选择重新点击一遍<丰饶灌木林>节点“原先的位置”。我私下认为截图延迟是主要原因，除了在 1 和 2 之间加 postDelay 外没有什么更好的解决方法。这就发一个 PR。
