### ISSUE TITLE
添加基建换班对列轮换功能

### ISSUE THREAD

**Issue by eenima** [MaaAssistantArknights/MaaAssistantArknights#11037]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

近几天更新，明日方舟的基建排班系统升级了新的排班功能，从截图识别干员逐个切换已经有过时的迹象
![IMG_0420](https://github.com/user-attachments/assets/dded7d7a-dc80-4276-8f61-4dc1c98f8c5f)

### 有什么好的想法？

用户可以提前设置好基建队列，MAA只需要更换队列即可，并统一干员休整。这样可以大大提高基建部分运行的效率与准确性

**Comment by Daydreamer114** [comment]
这个功能在 yj 方面存在很多逻辑问题，暂不考虑对此版本进行较多适配
![4d0fce6e8fc01c70f94c15bfae024a4c](https://github.com/user-attachments/assets/07267871-0d1d-40a0-94d7-8ee1e7b12194)
