### ISSUE TITLE
公开招募时限1:00:00

### ISSUE THREAD

**Issue by antidote02** [MaaAssistantArknights/MaaAssistantArknights#11034]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

公开招募时限1:00:00

### Version

Resource Version: 揭幕者们
Resource Time: 2024/11/2 23:42:13
UI Version: v5.9.0-beta.2
Core Version: v5.9.0-beta.2
Build Time: 2024/11/2 23:23:09

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17607925/asst.log)
[gui.log](https://github.com/user-attachments/files/17607926/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17607927/asst.bak.log)
[gui.json](https://github.com/user-attachments/files/17607928/gui.json)

### 配置信息

Windows 11 24H2 26100.2161
MuMu 12 启用 MuMu 截图增强模式
模拟器分辨率 1920x1080
DPI 480
帧率 144
使用 GPU 加速推理 NVIDIA GeForce RTX 3080

### 截图或录屏

![屏幕截图 2024-11-03 021616](https://github.com/user-attachments/assets/607e4124-6365-4fd9-a92d-7eea5297628d)
![屏幕截图 2024-11-03 021618](https://github.com/user-attachments/assets/7a15004f-9648-4bf5-be62-63cec42e2a21)

**Comment by Saratoga-Official** [comment]
请更新Bata 3版本
