### ISSUE TITLE
刷理智选择活动关PV-10会意外进入烟花装配工坊界面导致卡住，其他关不会

### ISSUE THREAD

**Issue by Reecle** [MaaAssistantArknights/MaaAssistantArknights#11042]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

如题。其他条件完全不变的情况下，其他关卡，如PV-9的自动选关到刷理智无异常，因为会在关卡选择页面拉到最右后，往回拉一点，就能正确选择关卡开始战斗
PV-10拉到底后，不会往回拉（估计是OCR识别到了PV-10），直接选中时点到了重叠在上面的装配工坊按钮，于是进入了错误的页面，导致后续运行出错。
在模拟器1280*720和1600*900分辨率，240dpi下均尝试过，问题依旧

### Version

Resource Version: 揭幕者们
Resource Time: 2024/11/2 23:42:13
UI Version: v5.8.1
Core Version: v5.8.1
Build Time: 2024/10/26 21:58:00

### 配置信息

win11 23H2 家庭版 版本号22631.3880
mumu模拟器12明日方舟专版 v4.1.2(3439)（当前最新版）
模拟器分辨率1280*720，DPI 240，帧率限制30fps
截图增强未开启，GPU加速推理未开启

### 截图或录屏

![MuMu12-20241103-142951](https://github.com/user-attachments/assets/80b4d375-3d0c-41d0-a72b-ac511ccbbd3a)
如图所示，烟花装配工坊的按钮和PV-10的按钮叠在一起了

**Comment by ABA2396** [comment]
5.9加了个偏移，照理来说应该没问题了。更新之后还有遇到吗？

**Comment by zengjiaen** [comment]
5.9 log 我也出现了这个问题
[asst.bak.log](https://github.com/user-attachments/files/17619124/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17619125/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17619127/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17619128/gui.log)

**Comment by Reecle** [comment]
> 5.9加了个偏移，照理来说应该没问题了。更新之后还有遇到吗？

您好，更新后测试了两天还是遇到相同的问题。

Resource Version: 揭幕者们
Resource Time: 2024/11/2 23:42:13
UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

模拟器和maa都手动重启过了。

**Comment by ABA2396** [comment]
> 是否可能是新增的偏移没有生效？

改 cache 倒是不会变资源版本，你看下 cache/resource/tasks.json 里 "PV-10@SideStoryStage" 对应的 "rectMove" 是什么

**Comment by ABA2396** [comment]
如果是 0,0 的话可以手动改成 1,1 试试

**Comment by Reecle** [comment]
> "PV-10@SideStoryStage" 对应的 "rectMove" 是什么

是 [55, 0, 1, 1]，应该是更新过的。但问题照旧

![image](https://github.com/user-attachments/assets/8e70f37f-d2fa-45a7-aa17-37df738fbd09)

**Comment by ABA2396** [comment]
改成95 0 1 1然后重启 maa 看看

**Comment by Reecle** [comment]
> 改成95 0 1 1然后重启 maa 看看

正常了！非常感谢。刚才没注意到1小时前的资源更新
