### ISSUE TITLE
使用手动资源更新功能出错：Failed to extract MaaResource.zip

### ISSUE THREAD

**Issue by suyoleaves** [MaaAssistantArknights/MaaAssistantArknights#11043]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

点击“资源更新”按钮后，按钮变灰并且在一段时间后恢复正常，期间没有任何提示。重启MAA后，也没有提示资源文件更新。
期间能观察到MAA目录下会下载一个MaaResource.zip文件。
观察gui.log，能发现以下日志：
`[2024-11-03 16:13:09.739][ERR] <18><.NET TP Worker> Failed to extract MaaResource.zip: Access to the path 'pack-092859126ceaac143634cb19eebe225681ab18bf.idx' is denied.`
MAA.exe使用了带UAC的管理员身份运行，不知道是否是这个原因呢。

### Version

Resource Version: 揭幕者们
Resource Time: 2024/11/2 23:42:13
UI Version: v5.8.1
Core Version: v5.8.1
Build Time: 2024/10/26 21:58:00
UI Version: v5.8.1
Core Version: v5.8.1
Build Time: 2024/10/26 21:58:00

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17609734/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17609735/asst.log)
[gui.log](https://github.com/user-attachments/files/17609736/gui.log)
[gui.json](https://github.com/user-attachments/files/17609751/gui.json)

### 配置信息

Windows11 
模拟器Mumu11，已开启截图增强和加速推理（GPU:3070Laptop）

### 截图或录屏

屏幕录制：

https://github.com/user-attachments/assets/88d5635f-d9c4-4e73-a3b1-e564c9da7715

**Comment by suyoleaves** [comment]
这个问题在我手动删除了MaaResource文件夹之后解决了，删除MaaResource文件夹后点击资源更新可以正常更新并弹出提示。
这个文件夹是之前手动更新资源文件时创建的，不知道是不是因为某些原因冲突了。
![QQ20241104-002241](https://github.com/user-attachments/assets/5998cff6-c828-40e5-8e20-b81d6bcb41ce)
![QQ20241104-002202](https://github.com/user-attachments/assets/da89751d-09dd-438c-9fbf-dc858da31339)

**Comment by ABA2396** [comment]
git clone 操作会将文件创建为只读，Directory.Delete 无法删除文件夹导致解压失败

**Comment by suyoleaves** [comment]
原来如此，感谢解答！
