### ISSUE TITLE
使用自动战斗的情况下导入作业dv-s-1 工具闪退

### ISSUE THREAD

**Issue by 1394805163** [MaaAssistantArknights/MaaAssistantArknights#1104]
在使用dv-s-1 作业时会导致maa崩溃，该问题可以复现但是中途不会跳出任何报错直接嘎巴就没了
基本每次都会卡在识别干员阶段就没有了
夜神模拟器国际版

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9055655/asst.log)

**Comment by MistEO** [comment]
作业文件也发一下吧（不让上传的话可以打个压缩包）

**Comment by zzyyyl** [comment]
也许跟 #1122 发生原因相同，两周没新消息先关了
