### ISSUE TITLE
希望能自动切换账号

### ISSUE THREAD

**Issue by SmdxLa** [MaaAssistantArknights/MaaAssistantArknights#11046]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

目前实现了切号功能，非常好用，但是切号需要手动

### 有什么好的想法？

我希望能存储账号，在完成第一个账号后能自动切换下一个账号继续完成任务

**Comment by Saratoga-Official** [comment]
切号功能目前可以通过定时切换配置来实现自动切号，比如8点打第一个号，9点打第二个号，只要设置不同的配置就可以了

**Comment by Saratoga-Official** [comment]
Duplicate of #9751
