### ISSUE TITLE
不支援的關卡（灰燼澤地）-已將資源包更新到最新

### ISSUE THREAD

**Issue by fs910175** [MaaAssistantArknights/MaaAssistantArknights#11041]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

GUI訊息：
不支援的關卡，請檢查關卡名稱或前往「設置 - 軟體更新 - 資源更新」，嘗試更新資源版本！灰烬泽地
資源包已經更新到最新了，應該是缺少地圖檔案

### Version

Resource Version: 銀心湖列車
Resource Time: 2024/11/2 20:33:26

UI Version: v5.9.0-beta.3
Core Version: v5.9.0-beta.3
Build Time: 2024/11/3 02:20:45

### 日志和配置文件

[debug.zip](https://github.com/user-attachments/files/17609556/debug.zip)

### 配置信息

作業系統：Windows 11 22H2
模擬器品牌：雷電模擬器（中國版）ver：9.0.79.0（64）
分辨率：1920*1080（DPI：280、60FPS）
截圖增強：開啟
GPU加速：開啟（RTX 4070）

**Comment by Saratoga-Official** [comment]
灰烬泽地不是地图识别名，你抄的是哪个作业，应该是作业的问题

**Comment by fs910175** [comment]
> 灰烬泽地不是地图识别名，你抄的是哪个作业，应该是作业的问题

這一份：https://prts.plus/?op=30492

**Comment by Saratoga-Official** [comment]
> > 灰烬泽地不是地图识别名，你抄的是哪个作业，应该是作业的问题
> 
> 這一份：https://prts.plus/?op=30492

作业本身的问题，换个作业吧，这个作业只能用简介里的地图包使用，和资源里的地图不一样

**Comment by fs910175** [comment]
> > > 灰烬泽地不是地图识别名，你抄的是哪个作业，应该是作业的问题
> > 
> > 
> > 這一份：https://prts.plus/?op=30492
> 
> 作业本身的问题，这个作业只能用简介里的地图包使用，和资源里的地图不一样

理解了，原來地圖包還能自製，看來這幾份作業是廢了 QQ

**Comment by Saratoga-Official** [comment]
https://prts.plus/?op=30418这份作业才是灰烬泽地正确的关卡识别名，你找用这个关卡名的作业都可以用

**Comment by fs910175** [comment]
> https://prts.plus/?op=30418 这份作业才是灰烬泽地正确的关卡识别名，你找用这个关卡名的作业都可以用

学会了，谢谢！
