### ISSUE TITLE
在进行刷理智pv-9时，会点到活动商店页面导致卡住，弹窗显示战斗失败

### ISSUE THREAD

**Issue by 2396438255** [MaaAssistantArknights/MaaAssistantArknights#11051]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在进行刷理智pv-9时，会点到活动商店页面导致卡住，弹窗显示战斗失败

### Version

UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17612695/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17612700/asst.log)
[gui.log](https://github.com/user-attachments/files/17612701/gui.log)
[gui.json](https://github.com/user-attachments/files/17612702/gui.json)
11-4号，8.20后

### 配置信息

win11，雷电模拟器，1280*720p，240dpi，60fps，已开启截图增强，未开启gpu加速

### 截图或录屏

![image](https://github.com/user-attachments/assets/00e3d955-be58-4599-bd3e-891f904b1d73)
![image](https://github.com/user-attachments/assets/fc790fcf-afc5-4eed-9832-e90e767d4872)

**Comment by Daydreamer114** [comment]
<img width="657" alt="{8566CC72-4969-4477-AAFC-43E518A7D461}" src="https://github.com/user-attachments/assets/9a9a928e-8419-4a25-9316-0d8b4a44de7d">
点了两次四幕汇演，第二次点进商店了

**Comment by Gai-Chuntian** [comment]
作战关卡PV-10也有概率进入烟花配置界面导致出错

**Comment by Saratoga-Official** [comment]
> 作战关卡PV-10也有概率进入烟花配置界面导致出错

已经修了

**Comment by Alan-Charred** [comment]
没有什么好的办法，加点 postDelay 吧。请大家帮我看看位置对不对。话说这个 3 秒的 preDelay 也算是罪魁祸首之一。
