### ISSUE TITLE
自定义基建会客室优先级错误

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#11059]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

rt，在使用自定义基建的会客室补满空位时，maa优先上精二伊内丝和精0四爷，而不是精二的忍冬和精二的铃兰
似乎maa基建中无法识别干员的精英信息，建议增加黑名单功能

### Version

UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

### 日志和配置文件

略

### 配置信息

win11，蓝叠国外版5

**Comment by Saratoga-Official** [comment]
你要是不提供log就提个功能建议issue而不是bugissue

**Comment by Daydreamer114** [comment]
略略略
