### ISSUE TITLE
萨卡兹肉鸽-戴冠式 拿到带思绪的藏品会卡死在思绪获取界面

### ISSUE THREAD

**Issue by AnthHao** [MaaAssistantArknights/MaaAssistantArknights#11058]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

萨卡兹肉鸽戴冠式 拿到无名图腾会卡死在思绪获取界面 不会自动进行下一步
人工点击跳过思绪获得的界面以后恢复正常 继续自动刷肉鸽

### Version

UI Version: v5.9.1-alpha.1.d003.g755aeff1c
Core Version: v5.9.1-alpha.1.d003.g755aeff1c
Build Time: 2024/11/3 12:15:06

### 日志和配置文件

[gui.bak.log](https://github.com/user-attachments/files/17615334/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17615336/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17615337/asst.bak.log)
[gui.json](https://github.com/user-attachments/files/17615340/gui.json)

### 配置信息

MuMu12 开启截图增强
GPU加速开启，GTX1650

**Comment by XingHaiHuShen** [comment]
我也遇到了相似的问题，简单来说就是一碰到需要NEXT的思绪就无法识别了，人工如果无法及时接管，便会放弃本次探索，但是也放弃不了。
