### ISSUE TITLE
识别错误加任务出错 尝试回退和检查运行库无果

### ISSUE THREAD

**Issue by oldganger** [MaaAssistantArknights/MaaAssistantArknights#11052]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

![rydEtlvGIj1z418g](https://github.com/user-attachments/assets/698bfa36-4c73-4725-9ffc-03993590cef1)
多次调试后仍是任务出错 昨天仍可用 今天上午更新后出现问题

### Version

UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17613358/asst.log)
[gui.log](https://github.com/user-attachments/files/17613359/gui.log)
[gui.json](https://github.com/user-attachments/files/17613360/gui.json)

### 配置信息

win11 mumu模拟器 开启截图增强 gpu加速开启 3060

**Comment by oldganger** [comment]
尝试关闭截图增强后居然正常了 之前开着截图增强似乎没有这个问题 然后测试截图后发现截图增强截图的是模拟器桌面而并非游戏内截图

**Comment by Daydreamer114** [comment]
最近mumu更了截图增强，maa也进行了适配，检查mumu设置中的后台保活等内容
