### ISSUE TITLE
MAA设置定时执行任务不能自行启动

### ISSUE THREAD

**Issue by LuoYe233333** [MaaAssistantArknights/MaaAssistantArknights#11064]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

![Y(E`T}DTNWWQ_XC4${6M6AX](https://github.com/user-attachments/assets/4a06e5dd-f4a0-4160-8d60-8ca10488d54a)
如题，设置了定时执行任务不能自行启动，手动启动执行任务都没什么问题，测试了很多次，自行启动这块每次都是卡在【已停止】这一步。

### Version

UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17617520/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17617521/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17617523/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17617524/asst.bak.log)

[gui.json](https://github.com/user-attachments/files/17617531/gui.json)

### 配置信息

 MuMu 12，1920 x 1080 （DPI280） 帧率60

### 截图或录屏

![%5I1BSM(_14$VNJI0WNU~E3](https://github.com/user-attachments/assets/9bc1b777-0c5d-4c75-8827-4a57461bf7f8)
![Y(E`T}DTNWWQ_XC4${6M6AX](https://github.com/user-attachments/assets/3430dcc8-50d0-4792-ab25-6c191eea21cc)
![E DPOVWO(O)M DO18FYQF_E](https://github.com/user-attachments/assets/b96f8c03-f86d-46a8-b394-a9f984d648aa)
![X}49PH_GSIPZ![%5I1BSM(_14$VNJI0WNU~E3](https://github.com/user-attachments/assets/9bc1b777-0c5d-4c75-8827-4a57461bf7f8)
![Y(E`T}DTNWWQ_XC4${6M6AX](https://github.com/user-attachments/assets/3430dcc8-50d0-4792-ab25-6c191eea21cc)
![E DPOVWO(O)M DO18FYQF_E](https://github.com/user-attachments/assets/b96f8c03-f86d-46a8-b394-a9f984d648aa)
XNO`%N_TM](https://github.com/user-attachments/assets/087a7331-ab1a-4c7a-8526-b68cf7561b0b)
![CAQ$0~$JM$TJ7LLT4P4_2BL](https://github.com/user-attachments/assets/ab4ba41d-325f-43de-83ab-edda036c5376)

**Comment by ABA2396** [comment]
mumu用不了最小化启动模拟器，把那个去掉试试

**Comment by ABA2396** [comment]
看了下是开启maa后自动启动模拟器和定时冲突了，强制定时开始任务的时候会检查是不是正在执行任务，如果正在执行会先停止任务，因为开模拟器的时间太长了导致开模拟器的任务还没结束，然后就卡在这里了
