### ISSUE TITLE
取消更新MAA后立即执行任务

### ISSUE THREAD

**Issue by oEthan2333o** [MaaAssistantArknights/MaaAssistantArknights#11060]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

使用三个MAA加一个模拟器刷三个号时（人在学校不在家），MAA自动更新导致完成后任务的下一个MAA与前一个更新后的MAA（启动后立即执行任务）同时执行任务

### 有什么好的想法？

取消更新MAA后立即执行任务

**Comment by Saratoga-Official** [comment]
？你这什么多开方式，你要是用一个模拟器就利用好开始唤醒里面切换账号功能，设置定时切换配置就行

**Comment by oEthan2333o** [comment]
刷完的时间不确定

在 2024-11-04 20:40:26，"萨拉托加" ***@***.***> 写道：


？你这什么多开方式，你要是用一个模拟器就利用好开始唤醒里面切换账号功能，设置定时切换配置就行
