### ISSUE TITLE
基建换班同时使用指定干员和自动填充时，有概率自动填充将前面已经指定入住的干员填充到后续宿舍，导致前面宿舍空缺

### ISSUE THREAD

**Issue by ykw-9826** [MaaAssistantArknights/MaaAssistantArknights#11072]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

我使用自定义排班计划，dorm0为 菲亚梅塔；爱丽丝；车尔尼；塑心 剩下一个位置自动填充，dorm 1 2 3均为自动填充，观察到这段时间在dorm2中经常看到塑心，而dorm0的第四个位置本来应该有塑心的地方空着，猜测是因为塑心作为排序比较靠前的宿管技能干员，在更新后删除未进驻后有可能再次被选中(ps:按理说不会选中头上有工作站图标的干员吧？但是我也难以解释这个结果，在尝试复现时塑心均会正常被dorm0选中，问题我想还是在dorm2）。我今天在换班后上线合成了材料导致自动填充顺序已经轮不到塑心，暂时无法复现验证，明天会再尝试一次
出现问题时间：11/5 09:36:56-09:38:01
附排班文件（出现问题为09:30-17:29的第二班）
[09472-manufacture-askl-ew-ins-gldy-amy.json](https://github.com/user-attachments/files/17626764/09472-manufacture-askl-ew-ins-gldy-amy.json)

### Version

UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17626768/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17626772/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17626773/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17626782/gui.log)
[gui.json](https://github.com/user-attachments/files/17626783/gui.json)

### 配置信息

Win11 23H2
MUMU12模拟器 1920*1080 480dpi 60帧 开启截图增强
GPU加速开启 RTX3070 Laptop（notebooks）

**Comment by ABA2396** [comment]
现在ui更新之后把未进驻的选项给删了，没什么好办法，要么手动把所有要休息的都指定了

**Comment by Ch4iYiFei** [comment]
@ABA2396 我也遇到了同样的问题，就是即使已经在前面宿舍进驻了，但还是会被后面的宿舍选中，前面的宿舍有空缺。

但是好像我看这段逻辑里面其实有判断干员头上的设施名称的逻辑。即使未进驻相关逻辑失效，如果干员头上的设施有名称的话，if_oper_not_stationed 会是false，理论上应该不会被选中才是。
![image](https://github.com/user-attachments/assets/0370e83d-bbe6-41a7-a0da-4b02facc6504)
![image](https://github.com/user-attachments/assets/6619a2a4-8b52-4b91-b239-83f8bc4055e4)

所以我去看了看log，好像出现了许多次ERROR:!facility_analyzer.analyze()
![image](https://github.com/user-attachments/assets/8753d67f-9aec-4f42-995c-4126e2b0c081)

像下图的几次，头顶的设施名称没有正确识别，facility name都是不正确的，导致了将之前宿舍里的干员选中到了当前宿舍。
![image](https://github.com/user-attachments/assets/8f39d058-5001-4643-a787-e93cc4440c73)

详细的那个宿舍的log如下。
[if_oper_not_stationed问题.md](https://github.com/user-attachments/files/17892416/if_oper_not_stationed.md)


所以这个问题似乎把facility_analyzer的ocr识别相关逻辑修一下就能解决？

**Comment by ABA2396** [comment]
等下有空了瞅瞅

**Comment by ABA2396** [comment]
![8226e6bc305ce569b935d214b68c2c09](https://github.com/user-attachments/assets/ca3be497-b579-4716-b06d-37027b7f8ac6)
不知道从哪个版本开始这玩意的大小和位置也变了

**Comment by ykw-9826** [comment]
> ![8226e6bc305ce569b935d214b68c2c09](https://private-user-images.githubusercontent.com/99072975/389278888-ca3be497-b579-4716-b06d-37027b7f8ac6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NTc1OTIsIm5iZiI6MTczMjQ1NzI5MiwicGF0aCI6Ii85OTA3Mjk3NS8zODkyNzg4ODgtY2EzYmU0OTctYjU3OS00NzE2LWIwNmQtMzcwMjdiN2Y4YWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDE0MDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwYzlkNTQ2YjliOTg5YzA1MjVjOWNjYTJhMDY4YTFkMjUzNWUxN2Q5YzEwYmMzODZkOWM1MDFkOTFjY2I1OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o5oM2M3cj--YM70iDDc3czmBb45lxfPrQxVJ-4ofN24) 不知道从哪个版本开始这玩意的大小和位置也变了

也是这个版本干的，我看其他工作站不会把人扯下来还以为这玩意在正常工作呢
