### ISSUE TITLE
MAA在显示“关卡为剿灭任务”后停止运行或卡住

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#11070]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

如题，如图，以及asst.log 显示，
发现的时间是10点（自动挂的，已经晾了俩小时了）
mumu界面可以点击，手动登入后主界面maa仍无反应

此问题是偶然性的，不能稳定复现，但是遇到过几次了

### Version

Resource Version: 揭幕者们
Resource Time: 2024/11/2 23:42:13
UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

### 日志和配置文件

[asst.upload.2024.1105.log](https://github.com/user-attachments/files/17626667/asst.upload.2024.1105.log)
[gui.upload.2024.1105.log](https://github.com/user-attachments/files/17626678/gui.upload.2024.1105.log)

GUI.log 显示的内容与截图一致

### 配置信息

OS: Windows 10 (专业版) x86_64
Kernel: WIN32_NT 10.0.19045.4170 (22H2)

Mumu12 v4.1.0(3439),截图增强开启, 4核6G，DirectX，画面表现更好，1270x720,dpi180, 30FPS
 GPU 加速推理开启 NVIDIA GeForce RTX 2070 (7.82 GiB) [Discrete]

### 截图或录屏

<img width="640" alt="截图_20241105115059" src="https://github.com/user-attachments/assets/d5f49bd9-418f-46e2-a524-26d6f4fde55c">
<img width="645" alt="maa ss 2024 1105" src="https://github.com/user-attachments/assets/82a4519a-2968-4e0d-be9d-fe01d11bc0f5">

**Comment by Saratoga-Official** [comment]
你是不是开了模拟器后台保活模式

**Comment by ABA2396** [comment]
cc @MistEO 这玩意是不是又是读配置死锁了啊

**Comment by MistEO** [comment]
> cc @MistEO 这玩意是不是又是读配置死锁了啊

我不到啊（

**Comment by KJH-x** [comment]
> 看了一下log也没有任何报错信息，会不会是开始前脚本的原因

谢谢提醒，我检查了我的脚本动作日志是正常的（但仅限于从bat启动的内容，batch本身没有做错误处理，但之前并没有遇到相关问题），所以”应该“不是脚本的问题
（题外话，有人瞅瞅 #10813无窗口化而非最小化 启动结束后脚本 吗）

**Comment by KJH-x** [comment]
没有办法提供进一步的情报，可以认为是不可稳定复现的个例，暂时关闭此议题

**Comment by KJH-x** [comment]
[asst.upload.2024.1114.log](https://github.com/user-attachments/files/17742857/asst.upload.2024.1114.log)
再次出现卡顿，已确认启动前脚本为非阻塞返回，接下来会尝试取消开始前结束后脚本再作尝试
