### ISSUE TITLE
新关卡导航错误

### ISSUE THREAD

**Issue by WSMTBG** [MaaAssistantArknights/MaaAssistantArknights#11081]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

我关卡选择填的剿灭然后备选是活动图PV10，实际上直接进了活动商店然后报错
出现时间的是这两天次次这样，如果只勾选开始唤醒和刷理智是能正常进关卡的

### Version

UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17640520/asst.log)
[gui.log](https://github.com/user-attachments/files/17640521/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17640545/asst.bak.log)
[gui.bak.log](https://github.com/user-attachments/files/17640546/gui.bak.log)
[gui.json](https://github.com/user-attachments/files/17640548/gui.json)

### 配置信息

win11 家庭版23H2 操作系统版本22631.4317
蓝叠国际版5.10.220.1008 N64

**Comment by WSMTBG** [comment]
> 进行资源更新后再尝试

刚刚更新了还是不行，依旧是进商店
![图片](https://github.com/user-attachments/assets/57012985-42ee-40dd-be83-0e98cd96ba03)

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/5c2a79f4-9a5a-4a38-9f88-075eaf4dd7ef)
我还挺怀疑是截图的问题，怎么点了之后过三秒还是这个界面，再点一次就进商店了

**Comment by ABA2396** [comment]
把 https://github.com/MaaAssistantArknights/MaaRelease/blob/main/MaaAssistantArknights/api/resource/tasks.json 替换到 cache/resource/tasks.json 看看

**Comment by WSMTBG** [comment]
> 把 https://github.com/MaaAssistantArknights/MaaRelease/blob/main/MaaAssistantArknights/api/resource/tasks.json 替换到 cache/resource/tasks.json 看看

好耶进关卡了
