### ISSUE TITLE
基建换班不用双维娜+摩根的无条件120%效率贸易站组合

### ISSUE THREAD

**Issue by rua23332** [MaaAssistantArknights/MaaAssistantArknights#11089]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

基建换班不用双维娜+摩根的无条件120%效率贸易站组合，这个组合也没有别的前置其他设施的条件，但换班还是只用老的更低效率的组合

### 有什么好的想法？

把这个组合加上去贸易站换班

### 其他内容

无

**Comment by ABA2396** [comment]
推进之王并不带贸易站技能，无法根据技能图标来进行效率判断，而且因为没技能排的很后面，如果为了兼容这个还得改判断逻辑。
如果有特殊组合需求，建议使用
![image](https://github.com/user-attachments/assets/b774b05f-bb13-4c53-9c67-29b67ec70c41)
