### ISSUE TITLE
【无限刷肉鸽功能bug】无法进入肉鸽，一直卡在选择难度界面

### ISSUE THREAD

**Issue by VentusRanger** [MaaAssistantArknights/MaaAssistantArknights#1108]
1、错误情况：
使用无限刷肉鸽功能以后，一直卡在选择难度界面，无法进入肉鸽，同时不断显示“探索xx次”

2、错误截图：
<img width="593" alt="1" src="https://user-images.githubusercontent.com/91249201/177776733-2a03a3c6-8fe8-4b7e-a4dc-7ea542121e6c.png">
<img width="720" alt="2" src="https://user-images.githubusercontent.com/91249201/177776750-4802350c-6f2c-42dc-aca2-8b144588cc5a.png">

3、使用的是mumu模拟器
使用的maa版本是4.05-beta1版本

4、附上日志：
出错时间20:25~20:36（我手动停止）
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9063685/asst.log)

**Comment by ABA2396** [comment]
没做选难度）自己选一个就好了

**Comment by MistEO** [comment]
~~我咋知道你想选啥难度~~
