### ISSUE TITLE
MUMU12模拟器退出关闭失败

### ISSUE THREAD

**Issue by zhihuizhicong** [MaaAssistantArknights/MaaAssistantArknights#11083]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

完成所有任务后，退出模拟器失败

### Version

UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

### 日志和配置文件

问题出现在日志的最后
[MAA.log](https://github.com/user-attachments/files/17640776/MAA.log)

### 配置信息

win11
MUMU12 V4.1.2
3840×2160
截图增强开启
GPU加速开启 RTX 3060 LAPTAP

### 截图或录屏

![1730859162511](https://github.com/user-attachments/assets/600d8378-c7fe-4889-869c-12a38b309e83)

**Comment by ABA2396** [comment]
你mumu是管理员权限开的？非管理员权限的maa无法访问管理员权限软件的内存

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/79b78e92-3722-4cad-a8fa-7e8453d95836)
我这试了下没问题

**Comment by zhihuizhicong** [comment]
maa是管理员开的，mumu不是

**Comment by zhihuizhicong** [comment]
重启电脑突然就好了
