### ISSUE TITLE
信用商店购物时不会优先购买打折的商品

### ISSUE THREAD

**Issue by TimothyChan44** [MaaAssistantArknights/MaaAssistantArknights#1110]
- bug描述：
   - 不会优先购买打折的”加急许可“和”狗粮“而是优先买了不打折的商品
   - bug等级评估：轻微影响

- 日志文件：
[bug2.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9067882/bug2.log)

- 模拟器： Nox
- 截图：
    - 游戏截图：
![image](https://user-images.githubusercontent.com/49863417/177888199-7b03b7b4-6992-408d-bcb2-f20b700c7d17.png)

    - MAA截图：
![image](https://user-images.githubusercontent.com/49863417/177888676-f4d8ee86-ab27-4ea2-ade5-5598addd7dac.png)

**Comment by TimothyChan44** [comment]
> 请附一下完整的日志，不要截取。谢谢~
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9068413/asst.log)

**Comment by MistEO** [comment]
```log
[2022-07-08 06:58:23.492][INF][Px5040][Tx1d30] asst::Assistant::append_task Mall {"shopping":true,"buy_first":["招聘许可","龙门币"],"blacklist":["碳","家具"]} 
```

这里 `优先购买` 的意思是，无论这种商品打不打折，先买了再说。如果不希望这样可以把 `优先购买` 中的内容删掉，默认就是会先买打折的的

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
