### ISSUE TITLE
软件更新，检查更新/资源更新喜报

### ISSUE THREAD

**Issue by antidote02** [MaaAssistantArknights/MaaAssistantArknights#11104]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

覆盖更新后软件更新喜报

### Version

Resource Version: 揭幕者们
Resource Time: 2024/11/5 21:42:19
UI Version: v5.9.1-alpha.1.d041.ge13f1e357
Core Version: v5.9.1-alpha.1.d041.ge13f1e357
Build Time: 2024/11/8 04:09:27

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17670828/asst.log)
[gui.log](https://github.com/user-attachments/files/17670829/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17670831/asst.bak.log)
[gui.json](https://github.com/user-attachments/files/17670833/gui.json)

### 配置信息

Windows 11 24H2 26100.2161
MuMu 12 启用 MuMu 截图增强模式
模拟器分辨率 1280 x 720
DPI 480
帧率 144
使用 GPU 加速推理 NVIDIA GeForce RTX 3080

### 截图或录屏

![屏幕截图 2024-11-08 080500](https://github.com/user-attachments/assets/aa6f62d9-e917-41a4-9793-b7f8176bb35e)

**Comment by Rbqwow** [comment]
内测在拆分更新部分组件 出了些问题先revert了
手动更新一下刚发的新内测

**Comment by status102** [comment]
> 内测在拆分更新部分组件 出了些问题先revert了
> 手动更新一下刚发的新内测
> 
> ~~这俩关了怎么也不说一声~~

网卡没发出去好像，不知道114想干啥
