### ISSUE TITLE
maa.exe卡巴斯基报毒

### ISSUE THREAD

**Issue by ZeroBlock0** [MaaAssistantArknights/MaaAssistantArknights#11109]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

卡巴斯基报毒

事件: 检测到恶意对象
应用程序: MAA

用户类型: 发起者
组件: 系统监控
结果说明: 检测到
类型: 木马
名称: PDM:Trojan.Win32.Bazon.a
威胁级别: 高
对象类型: 进程
对象路径: C:\Users\MAA-win-x64
对象名称: MAA.exe
原因: 行为分析
数据库发布日期: 昨天，2024/11/8 21:33:00
MD5: 4D198E256719F10449ACD3F93FBEA64B

### Version

UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

### 日志和配置文件

没有

### 配置信息

没有

**Comment by Salvere-0000** [comment]
遇到了同样的问题

**Comment by Saratoga-Official** [comment]
加白名单不行吗

**Comment by Tekashi-gif** [comment]
我也遇到同样的问题，之前都好好的，今晚突然抽风，运行软件直接报毒然后删除，不过我这显示的类型是UDS:DangerousObject.Multi.Generic
目前将整个文件夹添加到排除项暂时解决问题了

**Comment by ZeroBlock0** [comment]
> 加白名单不行吗

加白名单可以解决 但是报毒就是另外一回事了，之前都是正常，今天就开始报了，直接触发高级查杀了

**Comment by mycreft** [comment]
同，添加入信任列表解决，问题出现是更新到最新版本后

**Comment by citydirector** [comment]
同问题，甚至概率性：
前两次打开会报毒，(按了关闭进程)，第三次打开又不报了
另外我有基本相同的四个文件夹：MAA1、MAA2、MAA3、MAA4，只有MAA1打开会报毒；尝试把MAA1删了然后复制一份MAA2并改名成MAA1，又报毒，非常奇怪

**Comment by Hue-cloud** [comment]
有点难绷，看起来是卡的问题

我这里触发报错的对象是explorer.exe，报错原因是UDS:DangerousObject.Multi.Generic
然后把我MAA.exe删了，八成是误报

有空的可以去卡巴提个单：https://support.kaspersky.com/us/common/error/other/1870

**Comment by HoshinoAyako** [comment]
如果报错UDS:DangerousObject.Multi.Generic
那就是基于卡巴云网络的一种拉黑，估计是某种行为被判断为恶意了。
估计是多次生成或修改文件导致的吧。multi.generic
而PDM:Trojan.Win32.Bazon.a
PDM 针对未知威胁类行为通常都报这个错，估计也是误报。
以前泰拉瑞亚的某次更新也有类似的情况。
[https://steamcommunity.com/app/105600/discussions/0/2247805152838813524/](url)

**Comment by ZeroBlock0** [comment]
最新状态
![image](https://github.com/user-attachments/assets/14a89c88-f270-476a-af8c-213bfa8bdd33)

**Comment by Saratoga-Official** [comment]
要是解决了就关了吧

> 最新状态, 已从不受信任变为受信任，可以移除白名单了 ![image](https://private-user-images.githubusercontent.com/43921443/384580854-14a89c88-f270-476a-af8c-213bfa8bdd33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDAyNjYsIm5iZiI6MTczMTEzOTk2NiwicGF0aCI6Ii80MzkyMTQ0My8zODQ1ODA4NTQtMTRhODljODgtZjI3MC00NzZhLWFmOGMtMjEzYmZhOGJkZDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA4MTI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZTIyMmUwMWEyNDQwMGY3ZGE4NGU5ZWI5YThjNTFiZTQzNTdlODgwZDY3M2M1MGE0OTk1MjhiMjI2NTdiOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qn6A-fflu1uFXhyG6zaKKzX4axi7uT3_zwEiROgjp14)
