### ISSUE TITLE
肉鸽刷开局和存钱到上限自动停止的逻辑问题

### ISSUE THREAD

**Issue by Fey-Agasha** [MaaAssistantArknights/MaaAssistantArknights#11111]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

如果在自动肉鸽种的高级设置勾选投资+到上限停止，且在常规设置种选择刷开局策略，会导致maa在一层商店投资后如果钱满了直接停止任务，不刷开局

### Version

UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

### 日志和配置文件

[gui.json](https://github.com/user-attachments/files/17685024/gui.json)
[four logs.zip](https://github.com/user-attachments/files/17685039/four.logs.zip)
11/9 早上七点左右，应该是最后的日志

### 配置信息

W11 蓝叠5.9 60hz 2560*1440

**Comment by Saratoga-Official** [comment]
Duplicate of #10917
