### ISSUE TITLE
杀毒软件报毒

### ISSUE THREAD

**Issue by Ishar-mla-DD** [MaaAssistantArknights/MaaAssistantArknights#11118]
### 说说你遇到的问题？

如题，卡巴斯基会在更新MAA资源或者解压资源包时报毒，可能是代码有被判定危险操作导致？总之不紧急但是可以参考一下
![image](https://github.com/user-attachments/assets/18b88939-c750-4e2d-be93-90e95eaf7b0d)
事件: 检测到恶意对象
组件: 应用程序控制
结果说明: 检测到
名称: UDS:DangerousObject.Multi.Generic
威胁级别: 高
对象路径: E:\Software\明日方舟MAA
对象名称: MAA.exe
原因: 云保护
MD5: 4D198E256719F10449ACD3F93FBEA64B

![image](https://github.com/user-attachments/assets/c2dbb847-b0d1-48a8-92a4-13a23b654d61)

事件: 检测到恶意对象
应用程序: MAA
用户: 
用户类型: 活动用户
组件: 系统监控
结果说明: 检测到
类型: 木马
名称: PDM:Trojan.Win32.Bazon.a
威胁级别: 高
对象类型: 进程
对象路径: e:\software\明日方舟maa
对象名称: maa.exe
原因: 数据库
数据库发布日期: 今天，2024-11-09 07:02:00

事件: 检测到恶意对象
应用程序: MAA
用户: 
用户类型: 活动用户
组件: 系统监控
结果说明: 检测到
类型: 木马
名称: PDM:Trojan.Win32.Bazon.a
威胁级别: 高
对象类型: 进程
对象路径: e:\software\明日方舟maa\.old
对象名称: maa.exe
原因: 数据库
数据库发布日期: 今天，2024-11-09 07:02:00

**Comment by Constrat** [comment]
Everything regarding MAA is completely open source and available to everyone to check.

We had an issue last year with Microsoft being retarded and detecting MAA as Trojan but we fixed it after finding the included library being discontinued.

There's not really a lot we can do about it, just ignore it :)

**Comment by Ishar-mla-DD** [comment]
> Everything regarding MAA is completely open source and available to everyone to check.
> 
> We had an issue last year with Microsoft being retarded and detecting MAA as Trojan but we fixed it after finding the included library being discontinued.
> 
> There's not really a lot we can do about it, just ignore it :)

Hi Constart,
Thanks for your reply, i will ignore it, thanks!
