### ISSUE TITLE
启动加载时点击 `停止` 后再点击 `LinkStart` 时出现未知错误

### ISSUE THREAD

**Issue by cglcv** [MaaAssistantArknights/MaaAssistantArknights#1112]
![image](https://user-images.githubusercontent.com/35825310/177909458-8d69799e-08f1-437e-bdb9-dc5f3cabe196.png)
日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9068657/asst.log)

启动后似乎直接锁定在了运行状态（LinkStart灰的），按停止后正常，此时按LinkStart有概率弹出现未知错误，再点一下LinkStart可正常开始任务
（其实之前好几个版本都有这问题，但不影响使用就没注意）

**Comment by ABA2396** [comment]
刚开的时候是在读文件吧（）

**Comment by MistEO** [comment]
你自己编的版本么，用的是 `Release` 还是 `RelWithDebInfo`? 

如果是 `RelWithDebInfo`, 这个模式没开编译优化，加载本来就是非常慢的，可能得多等一会

**Comment by cglcv** [comment]
> 你自己编的版本么，用的是 `Release` 还是 `RelWithDebInfo`?
> 
> 如果是 `RelWithDebInfo`, 这个模式没开编译优化，加载本来就是非常慢的，可能得多等一会

不是自己编译的，都是GitHub下载的版本
一般情况下加载两三秒就好了，但有时候会卡很久

**Comment by MistEO** [comment]
github 的版本怎么会是 debug version 呢（

**Comment by cglcv** [comment]
> github 的版本怎么会是 debug version 呢（

不是啊，log里也没看到debug version啊

**Comment by MistEO** [comment]
我看歪日志了，我是傻逼（

**Comment by MistEO** [comment]
问题是，core 正在加载，还没加载好。

但是现在停止按钮的逻辑，除了停止本身，还会让开始按钮亮起来。所以你这时候点击，其实还没加载好，就出了这种问题。

感觉没啥影响，先摆烂一段时间再说


日志里这个时间点才加载好，但是你截图里能看到 11:07:26 就点击了
```log
[2022-07-08 11:07:27.193][TRC][Px3510][Tx27f0] asst::Assistant::Assistant  | leave, 4 ms 
```
