### ISSUE TITLE
自动肉鸽相关bug

### ISSUE THREAD

**Issue by mouyuu** [MaaAssistantArknights/MaaAssistantArknights#11122]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在进行萨卡兹肉鸽“刷源石锭，到达第二层后直接退出”策略过程中，当选择异想天开分队随机出“每进入新的一层，获得2缕灵感，初始源石锭+20”效果时，进入二层后程序会卡死在“已放弃本次探索”这一步
![1](https://github.com/user-attachments/assets/60b7929f-d938-4151-b830-601945283200)
![2](https://github.com/user-attachments/assets/26e153f6-3122-4128-be1c-59458f9b29dd)
![3](https://github.com/user-attachments/assets/319f04d9-ad6f-4405-b7d6-27470d9590e2)

### Version

Resource Version: 揭幕者们
Resource Time: 2024/11/2 23:42:13
UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17691290/asst.log)
[gui.log](https://github.com/user-attachments/files/17691291/gui.log)
[asst.bak.zip](https://github.com/user-attachments/files/17691294/asst.bak.zip)
[gui.bak.log](https://github.com/user-attachments/files/17691295/gui.bak.log)

### 配置信息

版本	Windows 10 专业版 版本号	22H2
雷电9.0.78.0(64) 1920*1080 dpi 280 60帧
未开启截图增强
RTX 2060S

**Comment by Daydreamer114** [comment]
即将在刷源石锭策略中禁用这两个分队，以及更多分队

**Comment by mouyuu** [comment]
> 即将在刷源石锭策略中禁用这两个分队，以及更多分队

乐，不过我也只是想点亮个生还者合约，还好已经完成了
