### ISSUE TITLE
肉鸽凹开局难度自动拉到最低（包括只凹开局干员直升精二）

### ISSUE THREAD

**Issue by ghostfacejiang** [MaaAssistantArknights/MaaAssistantArknights#11128]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

水月或萨米肉鸽凹开局干员直升或者热水壶和两希望都会自动把难度拉到最低，无论你选择的是max还是手动调15难，上传的录屏只演示了水月max的情况（因为要录完10M肯定是装不下的）

### Version

UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17702186/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17702189/asst.log)
[gui.log](https://github.com/user-attachments/files/17702190/gui.log)
[gui.json](https://github.com/user-attachments/files/17702193/gui.json)

没有gui.bak.log这个文件

### 配置信息

版本	Windows 11 家庭中文版
版本号	23H2
安装日期	‎2023/‎10/‎11
操作系统版本	22631.4317
体验	Windows Feature Experience Pack 1000.22700.1041.0

MuMu模拟器12，分辨率2560*1440（DPI 360）帧率上限240（开了防闪退模式所以是动态帧率）
截图增强模式已开启，GPU加速已开启
GPU型号：NVIDIA GeForce RTX 4050 Laptop GPU

### 截图或录屏

https://github.com/user-attachments/assets/9d70b8ed-cf57-4eb6-881b-e410ad86f95e

### 还有别的吗？

希望能上传的视频大小能多一点，录制问题的时候因为太大上传不了争分夺秒的操作可能会增加你们的工作量

**Comment by ghostfacejiang** [comment]
> 凹开局是绑定烧热水的，低难烧水成功率高

但是我是凹随机直升精二开，低难烧完水后他还是继续低难开而不是我选择的n15开

**Comment by Saratoga-Official** [comment]
> > 凹开局是绑定烧热水的，低难烧水成功率高
> 
> 但是我是凹随机直升精二开，低难烧完水后他还是继续低难开而不是我选择的n15开

你视频里只演示了烧水前的片段，我看看log里面有没有

**Comment by Saratoga-Official** [comment]
看了下你的log，没有发现他烧完水完了去刷开局的记录

**Comment by Alan-Charred** [comment]
> > 凹开局是绑定烧热水的，低难烧水成功率高
> 
> 但是我是凹随机直升精二开，低难烧完水后他还是继续低难开而不是我选择的n15开

您好，如果您能复现这个问题，可否再次上传一份包含这个复现流程的日志文件？
顺带，我们将在下个版本调整相关机制，在仅刷精二开局的情况下，将跳过 N0 烧开水的步骤。

**Comment by ghostfacejiang** [comment]
> > > 凹开局是绑定烧热水的，低难烧水成功率高
> > 
> > 
> > 但是我是凹随机直升精二开，低难烧完水后他还是继续低难开而不是我选择的n15开
> 
> 您好，如果您能复现这个问题，可否再次上传一份包含这个复现流程的日志文件？ 顺带，我们将在下个版本调整相关机制，在仅刷精二开局的情况下，将跳过 N0 烧开水的步骤。

[asst.log](https://github.com/user-attachments/files/17711301/asst.log)
[gui.log](https://github.com/user-attachments/files/17711304/gui.log)

https://github.com/user-attachments/assets/3aaee4f6-1beb-4f97-b4e8-3f122f379dcf

以上前两份是刚刚测的时候的日志文件，第三个是只刷精二开的录屏，希望对你们有所帮助

**Comment by Saratoga-Official** [comment]
> Warning
> 
> 存在未确认的链接，请谨慎访问。 There are unconfirmed links, please visit with caution.
> 
> > > > 凹开局是绑定烧热水的，低难烧水成功率高
> > > 
> > > 
> > > 但是我是凹随机直升精二开，低难烧完水后他还是继续低难开而不是我选择的n15开
> > 
> > 
> > 您好，如果您能复现这个问题，可否再次上传一份包含这个复现流程的日志文件？ 顺带，我们将在下个版本调整相关机制，在仅刷精二开局的情况下，将跳过 N0 烧开水的步骤。
> 
> [asst.log](https://github.com/user-attachments/files/17711301/asst.log) [gui.log](https://github.com/user-attachments/files/17711304/gui.log)
> 
>  2024-11-12.12-54-10.mp4 
> 以上前两份是刚刚测的时候的日志文件，第三个是只刷精二开的录屏，希望对你们有所帮助

这是正常的，目前只要刷开局就要先烧水，不管你之前烧没烧过，他烧好了才会回头切难度
我还以为你说他烧好也会n0刷开局
等下个版本才会有刷开局跳过烧水，590还没有

**Comment by ghostfacejiang** [comment]
> Warning
> 
> 存在未确认的链接，请谨慎访问。 There are unconfirmed links, please visit with caution.
> 
> > Warning
> > 存在未确认的链接，请谨慎访问。 There are unconfirmed links, please visit with caution.
> > > > > 凹开局是绑定烧热水的，低难烧水成功率高
> > > > 
> > > > 
> > > > 但是我是凹随机直升精二开，低难烧完水后他还是继续低难开而不是我选择的n15开
> > > 
> > > 
> > > 您好，如果您能复现这个问题，可否再次上传一份包含这个复现流程的日志文件？ 顺带，我们将在下个版本调整相关机制，在仅刷精二开局的情况下，将跳过 N0 烧开水的步骤。
> > 
> > 
> > [asst.log](https://github.com/user-attachments/files/17711301/asst.log) [gui.log](https://github.com/user-attachments/files/17711304/gui.log)
> > 2024-11-12.12-54-10.mp4
> > 以上前两份是刚刚测的时候的日志文件，第三个是只刷精二开的录屏，希望对你们有所帮助
> 
> 这是正常的，目前只要刷开局就要先烧水，不管你之前烧没烧过，他烧好了才会回头切难度 我还以为你说他烧好也会n0刷开局 等下个版本才会有刷开局跳过烧水，590还没有

好的，感谢
