### ISSUE TITLE
刷理智失败，直接跳过了

### ISSUE THREAD

**Issue by kuankon** [MaaAssistantArknights/MaaAssistantArknights#1113]
[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9069251/asst.-.log)

![EV`B{Y3E}Y 8@`TRT$MKQBV](https://user-images.githubusercontent.com/97777104/177926386-e071887e-18c6-4e9f-b70e-8ebb9b4e2ef5.png)

**Comment by kuankon** [comment]
让次更新失手点错了360点成阻止通过，那个启动文件直接没了，我有重新下载替换了文件不知道是不是这个原因

**Comment by MistEO** [comment]
任务失败报错的时候，游戏卡在哪个界面了？

**Comment by kuankon** [comment]
> 任务失败报错的时候，游戏卡在哪个界面了？

应该是结算界面，随后就没反应了，过会就报错跳过刷理智任务执行其任务了，有一次我单独刷理智时只显示完成次数，材料啥的都不显示，不知道这个正常吗，这段时间正常使用了没问题了，额今天也不显示了
![WR49}8IZ5}VRN289RVJ2YXF](https://user-images.githubusercontent.com/97777104/178905303-e90e49d7-e661-449f-8113-8f5c234e2fbe.png)
