### ISSUE TITLE
Mac 版 5.9.0 找不到点刺分队

### ISSUE THREAD

**Issue by eurus-ch** [MaaAssistantArknights/MaaAssistantArknights#11137]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [ ] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

5.9.0 更新中实现了点刺分队存钱 #10901 ，在 Mac 版中只能看到旧版分队，还看不到点刺分队，期待更新！Love your work!!

### Version

MAA v5.9.0 是当前的最新版本。
下载源为：https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v5.9.0/MAA-v5.9.0-macos-universal.dmg

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17711265/asst.log)
[asst.bak.log](https://github.com/user-attachments/files/17711269/asst.bak.log)

gui.log 和 gui.bak.log 未找到。

### 配置信息

Macbook M2 Pro
macOS Sequoia 15.1
PlayCover 3.1.0.maa

### 截图或录屏

<img width="1036" alt="截屏2024-11-12 12 53 27" src="https://github.com/user-attachments/assets/3843124b-c289-4b12-8fc6-cfd4f8879d1e">
<img width="372" alt="截屏2024-11-12 12 53 51" src="https://github.com/user-attachments/assets/e82d0897-a6af-4a92-8c91-c2496bc809be">

**Comment by Saratoga-Official** [comment]
Dupilcate of #11108
