### ISSUE TITLE
Dormitory Recongnition Error

### ISSUE THREAD

**Issue by rayveiled** [MaaAssistantArknights/MaaAssistantArknights#11139]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I am using the latest version of the current update and have reviewed both the updates released so far and the unreleased changes in the Pull Requests, there is no mention of the bug being fixed.
- [X] I have reviewed the Pinned issue (Announcements), Open issues, and Closed issues to ensure that my issue has not been mentioned.

### Description

The dormitory function in Base is no longer functional for the YoStarEN client.
"Task Error: Infrast" is given.
![image](https://github.com/user-attachments/assets/21330ab1-0cf6-4f89-9214-3e1c3610dddc)
![Screenshot_20241112-020930](https://github.com/user-attachments/assets/ef151305-5eec-43fb-bd20-6c82e7cfc6b0)

### Version

UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/03 06:22:21

### Log and config files

[asst.log](https://github.com/user-attachments/files/17714662/asst.log)
[gui.log](https://github.com/user-attachments/files/17714663/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17714665/asst.bak.log)
[gui.bak.log](https://github.com/user-attachments/files/17714667/gui.bak.log)
[gui.json](https://github.com/user-attachments/files/17714669/gui.json)

[2024-11-12 01:56:02.450] Error.

### Configuration information

Windows 10
LDPlayer 9.0.67

1280x720, 240DPI, 60FPS.

**Comment by Constrat** [comment]
![{03156014-078E-4F2F-84BF-F73EC6886521}](https://github.com/user-attachments/assets/719ee095-d92b-49c3-95cd-57540fd0cf74)

![{A4D511B1-FCD3-462B-873E-2D513A1C5FC5}](https://github.com/user-attachments/assets/f36ee6d2-f6a7-427a-bde2-7d235d7ef8ca)

And I thought this was enough warning
