### ISSUE TITLE
日服 沒有領取特殊月卡

### ISSUE THREAD

**Issue by meowings20000** [MaaAssistantArknights/MaaAssistantArknights#11143]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在點選領取特殊月卡獎勵後 沒有領取特殊月卡獎勵 連點進去月卡界面也沒有

### Version

UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

### 日志和配置文件

[gui.json](https://github.com/user-attachments/files/17720668/gui.json)
[asst.bak.zip](https://github.com/user-attachments/files/17720671/asst.bak.zip)

### 配置信息

作業系統：Windows 11
模擬器：Bluestacks 5

**Comment by Manicsteiner** [comment]
> [2024-11-13 01:41:52.018][TRC][Px12428][Txd3b8] asst::WordOcr [{ 大感謝奈: [ 14, 8, 70, 18 ], score: 0.930273 }, { ス夕ンフ: [ 13, 28, 69, 20 ], score: 0.843716 }, { 期間限定: [ 13, 62, 70, 17 ], score: 0.999548 }, { 採掘評可: [ 14, 83, 68, 17 ], score: 0.723625 }, { 大感謝奈: [ 13, 116, 71, 17 ], score: 0.885897 }, { 月パス: [ 13, 136, 53, 17 ], score: 0.840608 }] by OCR Pipeline , cost 47 ms
> [2024-11-13 01:41:54.197][TRC][Px12428][Txd3b8] asst::WordOcr [{ i..: [ 29, 6, 116, 29 ], score: 0.528628 }, { s: [ 244, 1, 53, 37 ], score: 0.771803 }, { k: [ 10, 56, 38, 40 ], score: 0.233675 }, { 大感謝祭: [ 76, 58, 73, 22 ], score: 0.991846 }, { ス夕ンフ: [ 78, 80, 67, 18 ], score: 0.719923 }, { 田: [ 12, 114, 35, 35 ], score: 0.424932 }, { 期間限定: [ 77, 114, 70, 19 ], score: 0.999973 }, { 採掘許可: [ 76, 134, 71, 19 ], score: 0.928567 }, { 风: [ 10, 162, 39, 41 ], score: 0.361338 }, { 大感謝祭: [ 76, 168, 72, 18 ], score: 0.977879 }, { 月ハズ: [ 75, 185, 56, 22 ], score: 0.631971 }] by OCR Pipeline , cost 87 ms
> [2024-11-13 01:41:58.874][TRC][Px12428][Txd3b8] asst::WordOcr [{ i..: [ 29, 6, 114, 29 ], score: 0.498612 }, { s: [ 245, 3, 51, 34 ], score: 0.710055 }, { k: [ 10, 56, 38, 40 ], score: 0.233675 }, { 大感謝祭: [ 76, 58, 73, 22 ], score: 0.992487 }, { ス夕ンフ: [ 78, 80, 67, 18 ], score: 0.755970 }, { 田: [ 12, 114, 35, 35 ], score: 0.424932 }, { 期間限定: [ 77, 114, 70, 19 ], score: 0.999974 }, { 採掘許可: [ 76, 134, 71, 19 ], score: 0.942333 }, { 风: [ 10, 162, 39, 41 ], score: 0.361338 }, { 大感謝祭: [ 76, 168, 72, 18 ], score: 0.976550 }, { 月ハズ: [ 75, 185, 56, 22 ], score: 0.638377 }] by OCR Pipeline , cost 91 ms

看起来是概率识别错误

**Comment by Manicsteiner** [comment]
closed by https://github.com/MaaAssistantArknights/MaaRelease/pull/223
