### ISSUE TITLE
最新内测版在Windows 24H2 26100.2161下闪退

### ISSUE THREAD

**Issue by e-legy** [MaaAssistantArknights/MaaAssistantArknights#11142]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

开启MAA后报错，报错信息如下

> MAA 遇到了问题
> 	A valid active Window is needed to update the Taskbar.
> 解决方案
> 	出现未知错误
> 详细信息
> System.InvalidOperationException: A valid active Window is needed to update the Taskbar.
>    at Microsoft.WindowsAPICodePack.Taskbar.TaskbarManager.get_OwnerHandle()
>    at Microsoft.WindowsAPICodePack.Taskbar.TaskbarManager.SetProgressValue(Int32 currentValue, Nullable`1 maximumValue)
>    at MaaWpfGui.ViewModels.UI.RootViewModel.set_TaskProgress(Nullable`1 value)
>    at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.UpdateMainTasksProgress(Nullable`1 completedCount)
>    at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.set_Idle(Boolean value)
>    at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.RunningState_IdleChanged(Object sender, Boolean e)
>    at MaaWpfGui.States.RunningState.OnIdleChanged(Boolean newIdleValue)
>    at MaaWpfGui.States.RunningState.set_Idle(Boolean value)
>    at MaaWpfGui.States.RunningState.SetIdle(Boolean idle)
>    at MaaWpfGui.Main.AsstProxy.Init()
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location ---
>    at MaaWpfGui.ViewModels.UI.RootViewModel.InitProxy()
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 

### Version

资源版本：
`{
    "activity": {
        "name": "揭幕者们",
        "time": 1730433600
    },
    "gacha": {
        "pool": "恶人寥寥",
        "time": 1730433600
    },
    "last_updated": "2024-11-08 09:03:20.961"
}`
MAA版本：v5.9.1-alpha.1.d066.g378ecd762+378ecd762918b40273bcaf68a2907a1179235fd9

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17720264/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17720266/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17720267/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17720268/gui.log)
[gui.json](https://github.com/user-attachments/files/17720271/gui.json)
2024年11月13日

### 配置信息

系统版本：Windows 11 24H2 26100.2161

**Comment by e-legy** [comment]
以Windows 8兼容模式运行可以正常开启

**Comment by ABA2396** [comment]
[MAA-v5.9.1-alpha.1.d067.gffa7ce55e-win-x64.zip](https://github.com/MaaAssistantArknights/MaaRelease/releases/download/v5.9.1-alpha.1.d067.gffa7ce55e/MAA-v5.9.1-alpha.1.d067.gffa7ce55e-win-x64.zip) fixed
