### ISSUE TITLE
肉鸽刷源石锭bug

### ISSUE THREAD

**Issue by KuiPer-LTW** [MaaAssistantArknights/MaaAssistantArknights#11165]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

非常诡异，明明选好了开局干员，结果就是三个招募券都不招人，然后在这个界面发呆，过了一会就放弃探索

![1](https://github.com/user-attachments/assets/1caa2e4d-7e31-4a12-8028-299ce6f1b20c)

### Version

UI Version: v5.10.0
Core Version: v5.10.0
Build Time: 2024/11/16 00:23:55

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/17784009/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17784010/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17784012/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17784014/gui.bak.log)
16点之后开始的

### 配置信息

Win10专业版
2560 x 1440 (DPI 360)
120fps
MuMu 12
截图增强开启
GPU 加速推理开启
RTX 3070

**Comment by KuiPer-LTW** [comment]
刚刚下了5.9试了试，完全没问题，所以大概应该不是我的问题了

**Comment by Constrat** [comment]
> 2560 x 1440 (DPI 360)
For Official CN, 1440 is not recommended

**Comment by Saratoga-Official** [comment]
确实，最好还是调小分辨率吧，高分辨率可能存在一些未知问题

**Comment by Saratoga-Official** [comment]
`[2024-11-16 16:32:04.626][TRC][Px5260][Tx0d38] match_templ | Sarkaz@Roguelike@EnterAfterRecruit.png score: 0.899083 rect: [ 1104, 319, 106, 105 ] roi: [ 1078, 234, 202, 239 ]
[2024-11-16 16:32:04.626][TRC][Px5260][Tx0d38] asst::PipelineAnalyzer::analyze | MatchTemplate Sarkaz@Roguelike@EnterAfterRecruit
[2024-11-16 16:32:04.626][INF][Px5260][Tx0d38] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":2,"max_times":2147483647,"result":{"score":0.899083},"task":"EnterAfterRecruit"},"first":["Sarkaz@Roguelike@Begin"],"pre_task":"Sarkaz@Roguelike@ChooseOperConfirmToGiveUp","subtask":"ProcessTask","taskchain":"Roguelike","taskid":6,"uuid":"a6bb2138068cebcf"}
[2024-11-16 16:32:04.626][TRC][Px5260][Tx0d38] Click with scaled coordinates (1149, 369) 2
[2024-11-16 16:32:04.626][TRC][Px5260][Tx0d38] minitouch click: (2298, 738)
[2024-11-16 16:32:04.727][TRC][Px5260][Tx0d38] ready to sleep 3000
[2024-11-16 16:32:07.728][TRC][Px5260][Tx0d38] end of sleep 3000
[2024-11-16 16:32:07.728][INF][Px5260][Tx0d38] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":2,"max_times":2147483647,"result":{"score":0.899083},"task":"EnterAfterRecruit"},"first":["Sarkaz@Roguelike@Begin"],"pre_task":"Sarkaz@Roguelike@ChooseOperConfirmToGiveUp","subtask":"ProcessTask","taskchain":"Roguelike","taskid":6,"uuid":"a6bb2138068cebcf"}
[2024-11-16 16:32:07.728][TRC][Px5260][Tx0d38] ready to sleep 500
[2024-11-16 16:32:08.228][TRC][Px5260][Tx0d38] end of sleep 500`
的确诡异，已经识别到并且点击了，但还卡在这个界面，可能没点到正确位置，可能和分辨率有点关系

**Comment by KuiPer-LTW** [comment]
> 确实，最好还是调小分辨率吧，高分辨率可能存在一些未知问题

可是5.9就没任何问题啊

**Comment by Saratoga-Official** [comment]
> > 确实，最好还是调小分辨率吧，高分辨率可能存在一些未知问题
> 
> 可是5.9就没任何问题啊

5.10应该没动这块

**Comment by KuiPer-LTW** [comment]
> > > 确实，最好还是调小分辨率吧，高分辨率可能存在一些未知问题
> > 
> > 
> > 可是5.9就没任何问题啊
> 
> 5.10应该没动这块
那咋办？

**Comment by KuiPer-LTW** [comment]
> > > 确实，最好还是调小分辨率吧，高分辨率可能存在一些未知问题
> > 
> > 
> > 可是5.9就没任何问题啊
> 
> 5.10应该没动这块

那咋办？

**Comment by wperson** [comment]
1600*900一样

**Comment by KuiPer-LTW** [comment]
> 1600*900一样

也是之前没问题这个版本突然有问题了吗

**Comment by wperson** [comment]
> > 1600*900一样
> 
> 也是之前没问题这个版本突然有问题了吗

应该是吧，我之前刷了999就好久没刷过了。我这现在是时好时坏的，有时候能正常刷

**Comment by KuiPer-LTW** [comment]
> > > 1600*900一样
> > 
> > 
> > 也是之前没问题这个版本突然有问题了吗
> 
> 应该是吧，我之前刷了999就好久没刷过了。我这现在是时好时坏的，有时候能正常刷

就在刚刚我还眼看着它成功存了一次钱，然后下一次探索又卡住了

**Comment by KuiPer-LTW** [comment]
我觉得

> > > > 1600*900一样
> > > 
> > > 
> > > 也是之前没问题这个版本突然有问题了吗
> > 
> > 
> > 应该是吧，我之前刷了999就好久没刷过了。我这现在是时好时坏的，有时候能正常刷
> 
> 就在刚刚我还眼看着它成功存了一次钱，然后下一次探索又卡住了

我是觉得这种情况加之之前的版本从来没bug过，大概并不是分辨率的问题

**Comment by KuiPer-LTW** [comment]
是不是稍微改一下开始探索的点击位置能改善？

**Comment by Saratoga-Official** [comment]
MAA又不是点固定位置的，是识别开始讲述这四个字来点的
![Sarkaz@Roguelike@EnterAfterRecruit](https://github.com/user-attachments/assets/2e3bd7df-f6b1-42dd-9d92-7c28a1babb62)

**Comment by KuiPer-LTW** [comment]
> > > > 1600*900一样
> > > 
> > > 
> > > 也是之前没问题这个版本突然有问题了吗
> > 
> > 
> > 应该是吧，我之前刷了999就好久没刷过了。我这现在是时好时坏的，有时候能正常刷
> 
> 就在刚刚我还眼看着它成功存了一次钱，然后下一次探索又卡住了

[asst.bak.log](https://github.com/user-attachments/files/17784795/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17784796/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17784798/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17784799/gui.log)
还有这个，之前忘记上传了
[gui.json](https://github.com/user-attachments/files/17784800/gui.json)
不知道这莫名其妙成功的一次有没有线索

**Comment by KuiPer-LTW** [comment]
> > > 1600*900一样
> > 
> > 
> > 也是之前没问题这个版本突然有问题了吗
> 
> 应该是吧，我之前刷了999就好久没刷过了。我这现在是时好时坏的，有时候能正常刷

你现在能复现吗？要不也上传一下debug文件？

**Comment by wperson** [comment]
[asst.bak.log](https://github.com/user-attachments/files/17784838/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17784839/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17784840/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17784841/gui.log)

**Comment by Daydreamer114** [comment]
@KuiPer-LTW @wperson 请尝试使用这个文件替换掉根目录下的 ./resource/tasks.json
[tasks.json](https://github.com/user-attachments/files/17784949/tasks.json)

若仍出现问题，请再次上传 log

**Comment by KuiPer-LTW** [comment]
> @KuiPer-LTW @wperson 请尝试使用这个文件替换掉根目录下的 ./resource/tasks.json [tasks.json](https://github.com/user-attachments/files/17784949/tasks.json)
> 
> 若仍出现问题，请再次上传 log

哦！OK了
![1](https://github.com/user-attachments/assets/07a758a5-2cb9-4ddd-a33d-93d87b2e60a4)

**Comment by Saratoga-Official** [comment]
归根结底是MAA点太快的问题，和版本没关系
