### ISSUE TITLE
`干员名称显示语言` 设置为 `跟随游戏客户端` 会导致MAA无法启动

### ISSUE THREAD

**Issue by yokinanya** [MaaAssistantArknights/MaaAssistantArknights#11170]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

目测该bug仅为gui的bug，与core无关

### Version

UI Version: v5.10.1-alpha.1.d006.gfc3bade2d
Core Version: v5.10.1-alpha.1.d006.gfc3bade2d
Build Time: 2024/11/17 09:04:39

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/17788756/gui.log)
[gui.json](https://github.com/user-attachments/files/17788759/gui.json)

### 配置信息

与配置无关

**Comment by Saratoga-Official** [comment]
v5.10.1 fixed
