### ISSUE TITLE
干员识别异常

### ISSUE THREAD

**Issue by nicson44** [MaaAssistantArknights/MaaAssistantArknights#11186]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

部分干员识别出来是未存在，但是实际上存在，检查截图并未从最右侧开始截图，而且缺少了一帧截图（在最右侧前一帧）

### Version

5.10.2

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17798756/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17798758/asst.log)
[gui.log](https://github.com/user-attachments/files/17798759/gui.log)
[gui.json](https://github.com/user-attachments/files/17798762/gui.json)
gui.bak.log未找到

### 配置信息

win10，mumu12，未开启截图增强，未开启GPU加速推理

### 截图或录屏

[oper2.zip](https://github.com/user-attachments/files/17798730/oper2.zip)
[oper.zip](https://github.com/user-attachments/files/17798732/oper.zip)

**Comment by Heart-of-engine** [comment]
同意，今天在MAA作业站复制maa://43603作业时，反馈未找到煌等相关干员，但实际上我有这些干员。

**Comment by Saratoga-Official** [comment]
> 同意，今天在MAA作业站复制maa://43603作业时，反馈未找到煌等相关干员，但实际上我有这些干员。

如果要反馈就提供你的log，问题有可能不一样

**Comment by Saratoga-Official** [comment]
请问是哪部分干员识别不出来，能给出具体干员名吗

**Comment by nicson44** [comment]
好多，具体只记得有ew 李狗剩&nbsp; 异拉狗

**Comment by nicson44** [comment]
我等会回去后把识别后的代码发你

**Comment by Saratoga-Official** [comment]
> 好多，具体只记得有ew 李狗剩&nbsp; 异拉狗

看了一下截图，你狗剩和拉狗是有新语音图标的，那玩意会影响识别

**Comment by Saratoga-Official** [comment]
![2024-11-18_18-11-18-419_raw](https://github.com/user-attachments/assets/f9b838f9-0b79-436d-b66e-55ec24567101)
你把所有新语音都点了应该就正常多了，你看浊蒂都遮住前面名字了，MAA是识别干员名字的

**Comment by nicson44** [comment]
嗯，我回去后点掉后再试下看看

**Comment by inktree** [comment]
> ![2024-11-18_18-11-18-419_raw](https://private-user-images.githubusercontent.com/151550168/387256316-f9b838f9-0b79-436d-b66e-55ec24567101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjMwMTksIm5iZiI6MTczMjAyMjcxOSwicGF0aCI6Ii8xNTE1NTAxNjgvMzg3MjU2MzE2LWY5YjgzOGY5LTBiNzktNDM2ZC1iNjZlLTU1ZWMyNDU2NzEwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxMzI1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGQ1YWNiY2M3MmI3MDM2Njc2NWRhZDYyNDllYTM2YTBhYTlhOTcwZDZlMTFjNTc4YWJmMjVkOGE1YTdhYTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GHDKtfKcGZTdlE5dqqmCwYal-vjgJH21VFCIeHe4-cM) 你把所有新语音都点了应该就正常多了，你看浊蒂都遮住前面名字了，MAA是识别干员名字的

![6NL9_}F927NQ32`6GJO3 ~T](https://github.com/user-attachments/assets/963e8b08-2fa2-40ec-b6ab-41ba6724fd6b)
实际上跟语音没有关系，就是识别有问题，无法正常识别已拥有的干员

**Comment by Saratoga-Official** [comment]
> > ![2024-11-18_18-11-18-419_raw](https://private-user-images.githubusercontent.com/151550168/387256316-f9b838f9-0b79-436d-b66e-55ec24567101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjMwMTksIm5iZiI6MTczMjAyMjcxOSwicGF0aCI6Ii8xNTE1NTAxNjgvMzg3MjU2MzE2LWY5YjgzOGY5LTBiNzktNDM2ZC1iNjZlLTU1ZWMyNDU2NzEwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxMzI1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGQ1YWNiY2M3MmI3MDM2Njc2NWRhZDYyNDllYTM2YTBhYTlhOTcwZDZlMTFjNTc4YWJmMjVkOGE1YTdhYTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GHDKtfKcGZTdlE5dqqmCwYal-vjgJH21VFCIeHe4-cM) 你把所有新语音都点了应该就正常多了，你看浊蒂都遮住前面名字了，MAA是识别干员名字的
> 
> ![6NL9_}F927NQ32`6GJO3 ~T](https://private-user-images.githubusercontent.com/120291655/387672513-963e8b08-2fa2-40ec-b6ab-41ba6724fd6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjMxNzQsIm5iZiI6MTczMjAyMjg3NCwicGF0aCI6Ii8xMjAyOTE2NTUvMzg3NjcyNTEzLTk2M2U4YjA4LTJmYTItNDBlYy1iNmFiLTQxYmE2NzI0ZmQ2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxMzI3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmU2YTlhMjU4YzYyNjlkZThmYTI2ZDhiN2I3M2M5YmViZTIzMDE3OTBkYjgyYzEyZmMzMDM0ZDNhNTJiYzUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2fxhGbx_spCi9YWy7rM833QudMpunMLWZqZ3qOzwurI) 实际上跟语音没有关系，就是识别有问题，无法正常识别已拥有的干员

你的问题不一样，拉狗的识别已经修了，还没发版

**Comment by Saratoga-Official** [comment]
这个issue的问题就是新语音造成的，log里都有证据，他把逻各斯识别成了new逻各斯，这个new就只能是新语音的问题，就别来瞎掺和
