### ISSUE TITLE
在自动战斗中无法选中荒芜拉普兰德

### ISSUE THREAD

**Issue by Baiyuqiao0416** [MaaAssistantArknights/MaaAssistantArknights#11183]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在自动战斗的编队界面无法选中荒芜拉普兰德，会自动忽视。无论是用自定义加干员还是代码抄作业都无法选中。

### Version

UI Version: v5.10.2
Core Version: v5.10.2
Build Time: 2024/11/18 00:09:38
Resource Version: 卫戍协议
Resource Time: 2024/11/15 17:03:33

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17794957/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17794964/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/17794969/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17794972/gui.log)
[gui.json](https://github.com/user-attachments/files/17795002/gui.json)

时间点2024-11-18 13:09:18.814

### 配置信息

版本	Windows 11 专业版
版本号	24H2
安装日期	‎2024/‎11/‎8
操作系统版本	26100.2314
体验	Windows Feature Experience Pack 1000.26100.32.0
BlueStacks 5.21.210.1023 P64 1920x1080 320dpi 60fps
加速推理开启 RTX 4060 Laptop GPU

### 截图或录屏

![image](https://github.com/user-attachments/assets/5637f3f9-3549-4b34-bedf-1051a23a78c3)
![Screenshot_2024 11 18_13 26 26 544](https://github.com/user-attachments/assets/c3ae3bbf-df7f-4066-8bb4-cbd4f43d4987)

**Comment by Saratoga-Official** [comment]
识别问题，没识别到前面的荒字
