### ISSUE TITLE
Copilot files for SSS out of date

### ISSUE THREAD

**Issue by tmprnc** [MaaAssistantArknights/MaaAssistantArknights#11189]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I am using the latest version of the current update and have reviewed both the updates released so far and the unreleased changes in the Pull Requests, there is no mention of the bug being fixed.
- [X] I have reviewed the Pinned issue (Announcements), Open issues, and Closed issues to ensure that my issue has not been mentioned.

### Description

The JSON files for SSS Copilot are out of date and correspond to a season which is no longer available.
![1731940296](https://github.com/user-attachments/assets/22e638af-4193-41b4-9024-2f5cf443f560)

### Version

UI Version: v5.10.2
Core Version: v5.10.2
Build Time: 2024/11/17 17:09:38
Resource Version: Rhodes Island Icebreaker Games
Resource Time: 2024/11/14 18:26:34

### Log and config files

n/A

### Configuration information

LDPlayer 9, no screenshot enhancement
GPU accelerated with GeForce RTX 3070

**Comment by Saratoga-Official** [comment]
CC @Constrat

**Comment by Constrat** [comment]
I'm sorry but I'm deep under exams.

**Comment by tmprnc** [comment]
Translation is not critical for my use, I can just use DeepL to know which operators are required. I just did not know where to find the files for the corresponding towers. This is more than good enough in interim, thank you.

**Comment by Constrat** [comment]
For now I'm just going to remove the older ones in the old folder. When I'll have time, I'll add the translations.
