### ISSUE TITLE
建议在肉鸽中“安全的角落”拿取高级物资配给券

### ISSUE THREAD

**Issue by sun-jiao** [MaaAssistantArknights/MaaAssistantArknights#11187]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

在傀影肉鸽中遇到安全的角落没有抓取高级物资配给券。

### 有什么好的想法？

我认为在当前有未精二干员的情况下，高级物资配给券应该是比几点希望或者几点生命值更值得抓取的。

**Comment by Daydreamer114** [comment]
安全的角落的选项与其它不期而遇的处理方式一样，均为固定选择第几选项。

肉鸽事件类节点对于选择选项的重构已经在 #10980 中进行。

**Comment by sun-jiao** [comment]
好的，谢谢。
