### ISSUE TITLE
使用命令行切换MAA配置时有可能使“刷理智”的关卡设置被覆盖

### ISSUE THREAD

**Issue by star-whisper9** [MaaAssistantArknights/MaaAssistantArknights#11199]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### **这个问题在多台机器上无法100%复现，我尝试使用了三台无关联的Windows设备，其中有一台无法复现**

复现步骤：

1. 打开MAA
2. 新建若干个不同名字的配置，并为其设置不同的“刷理智”板块的关卡选择
3. 关闭MAA
4. 使用命令行方式打开特定配置的MAA（`MAA.exe --config {profile}`）
5. 看到对应配置的MAA中，“刷理智”板块的关卡选择不是原有的，而是上一次打开MAA时的配置内的，但其他配置都是正确未被修改的

例如，有两个配置，一个`LS6`关卡选择为LS-6，一个`AP5`关卡选择为AP-5。关闭MAA时，配置文件为`LS6`，此时如果使用命令行参数`--config AP5`打开`AP5`配置，可以看到本应为AP-5的关卡选择，变成了LS-6。

---

复现测试变量：

- 测试了包含 **中文** / **仅包含字母与数字** 的配置文件名称，均可以复现
- 测试使用的MAA是最新的Release版本，全新安装（下载并单独解压到新文件夹）。测试时没有其他MAA实例在运行。
- 三台设备使用的MAA版本是相同的

### Version

UI Version: v5.10.2
Core Version: v5.10.2
Build Time: 2024/11/18 00:09:38

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17817461/asst.log)
[gui.log](https://github.com/user-attachments/files/17817464/gui.log)
[gui.json](https://github.com/user-attachments/files/17817469/gui.json)

### 尝试的操作系统（√表示成功复现）
- [x] Windows Server 2022
- [ ] Windows 11 家庭版
- [x] Windows 11 专业版（有概率无法复现）

### 模拟器
**未开启**，三个测试设备安装的模拟器分别是夜神、Mumu+雷电、逍遥。

### GPU加速
均未开启

### 截图或录屏

*[蓝奏云文件附测试录屏](https://star-whisper.lanzn.com/iAje42fk6i7e)*

**Comment by Saratoga-Official** [comment]
你提供的gui.json里存储的1-7啊，你确定你设置上了吗
![5BQ5YVT R}7PCQKB3W$6OTK](https://github.com/user-attachments/assets/bb44cde1-7988-4cf9-8cfe-7f52ce67de92)

**Comment by star-whisper9** [comment]
上传的 gui.json 是测试视频演示完以后的

**Comment by star-whisper9** [comment]
> 那你上传他有啥用，倒是把之前的上传一下啊

视频内展示已经很清楚了，上传的 gui.json 与最初的只有四行区别，三个配置的关卡选择全部被覆盖成了1-7，CurrentProfile变成了最后退出所在的Profile。如果没有看视频建议看完。

**Comment by Saratoga-Official** [comment]
> > 那你上传他有啥用，倒是把之前的上传一下啊
> 
> 视频内展示已经很清楚了，上传的 gui.json 与最初的只有四行区别，三个配置的关卡选择全部被覆盖成了1-7，CurrentProfile变成了最后退出所在的Profile。如果没有看视频建议看完。

问题是我无法复现，所以要你提供下你之前的guijson，我试试能不能复现

**Comment by Daydreamer114** [comment]
的确如你所说，家庭版无法复现。

我自己的专业版在使用时也被同步了关卡，且备选关卡也被同步。
我的所有配置中，只有留空（当前/上次）的没被同步，其它的配置均被同步为第 4 配置（计入Default，总共6个）。

**Comment by Saratoga-Official** [comment]
![$2G @Y~@DV}5H)J}G4YN@4R](https://github.com/user-attachments/assets/a2845e38-0739-4a5b-8ae4-078d459a968a)
![5 NL`5T``B R L(G55{M`~5](https://github.com/user-attachments/assets/2347124c-f252-40c7-be0b-c4904dee5577)
家庭中文版无法复现

**Comment by Daydreamer114** [comment]
![7888d54df28cbe360fe78ad645ec9c51](https://github.com/user-attachments/assets/b6bb78bd-c75c-46d4-97cf-638e0a096075)
![aec6972abe058f45e6395987d2d3c490](https://github.com/user-attachments/assets/108b2ff0-aac9-48b8-82ed-19733b26a254)

专业工作站版无法复现

**Comment by Daydreamer114** [comment]
我打完这把再测一次

**Comment by ABA2396** [comment]
看了下应该是 OnInitialActivate 的 InitializeItems 中有更新列表的操作，在更新的过程中如果修改了 config 会导致更新后的关卡保存到新配置里，我看看怎么改

**Comment by ABA2396** [comment]
感觉脑子不是很清晰，没想到什么好办法，之后看看
