### ISSUE TITLE
MAA刷关时候有几率发生崩溃现象

### ISSUE THREAD

**Issue by NightFrost42** [MaaAssistantArknights/MaaAssistantArknights#1119]
在刷关时，有几率在关卡结束页面发生闪退现象，如下图所示
![image](https://user-images.githubusercontent.com/49632085/178042638-842676db-572c-4adc-9b93-68d1efa8cb99.png)
在我的多个设备可复现，原因未知，已排除性能的问题

目前只在蓝叠中国版出现过此问题

由于在短时间内复现，故日志文件较短，全部日志已经贴入pastebin中方便查看，在下方链接可以查看

https://pastebin.com/VYqHr1vQ

**Comment by MistEO** [comment]
> 我昨天也崩了

日志也发下

**Comment by MistEO** [comment]
问题非常奇怪，我想不到这里有什么崩溃的可能性。。

尝试着改了下，试试有没有用，这个 [调试版本]( https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/2638237949)

**Comment by Shawnsdaddy** [comment]
> > 我昨天也崩了
> 
> 日志也发下

崩 了重启一下就完了，，只是偶然遇到了

**Comment by horror-proton** [comment]
是点了开始行动后一直等到关卡结束的时候才闪退的吗

**Comment by horror-proton** [comment]
> 我昨天也崩了

也是长时间 sleep 完成后崩溃的吗

**Comment by NightFrost42** [comment]
> 是点了开始行动后一直等到关卡结束的时候才闪退的吗

这个我不清楚，之前没有仔细观察过，目前只知道是在开始行动到打完之间出现的问题，具体时间需要我再观察

**Comment by Shawnsdaddy** [comment]
> 是点了开始行动后一直等到关卡结束的时候才闪退的吗
我的是，关卡打完了没反应，我说咋回事结果MAA都没了

**Comment by horror-proton** [comment]
可以尝试查看 Windows 的 "可靠性历史记录" (可以直接在开始菜单里面搜素到), 找一下又没有对应的 `MeoAsstGui`项, 如果有的话打开它然后复制详细信息

**Comment by horror-proton** [comment]
日志和 #1858 的第一次崩溃好像有一点相似
