### ISSUE TITLE
日服 自定义基建换班找不到魔王

### ISSUE THREAD

**Issue by Argonautes0607** [MaaAssistantArknights/MaaAssistantArknights#11203]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

大概是识别问题（猜的，因为字比较小

### Version

v5.10.2（547）
更新时间：2024-11-15 09:03:33.875

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17827271/asst.log)

### 配置信息

macOS 15.2 playcover 

### 截图或录屏

<img width="1103" alt="截屏2024-11-20 16 15 59" src="https://github.com/user-attachments/assets/d2db614e-a273-41cf-b6cb-ebff67be2b33">

**Comment by Saratoga-Official** [comment]
log里面没有16点15分之前的内容，请重新上传

**Comment by Argonautes0607** [comment]
至于log里面没有16点15分之前的内容，我也不知道，抱歉

**Comment by Argonautes0607** [comment]
这个问题今天又复现了，补一下log
[asst.log](https://github.com/user-attachments/files/17867144/asst.log)

**Comment by Saratoga-Official** [comment]
一个建议，由于mac没有guilog，所以反馈的时候最好附上软件的截图

**Comment by ABA2396** [comment]
应该是 `シヴィライト・エテルナ` 吧，被识别成 `シヴラィトエテルナ` 了
![image](https://github.com/user-attachments/assets/e1bb5d72-c60a-4f45-bd6d-96329c981f49)

**Comment by ABA2396** [comment]
cc @Manicsteiner 日服要不统一处理下 ・ 的替换，感觉这玩意挺容易识别错的

**Comment by Argonautes0607** [comment]
<img width="1590" alt="截屏2024-11-23 09 00 29" src="https://github.com/user-attachments/assets/22f2fbc5-8c2b-42de-a735-a68117564e66">

**Comment by Manicsteiner** [comment]
替换规则是 ["ヴィライト.*エ", "魔王"]，・没问题，少识别到了半高的 ィ
