### ISSUE TITLE
部署列表成员过多时，选取干员会引起干员图标位置发生改变，使得无法正确选择干员部署

### ISSUE THREAD

**Issue by nightofknife** [MaaAssistantArknights/MaaAssistantArknights#1121]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9074501/asst.log)

模拟器：mumu
MAA版本：4.0.5
问题描述：方舟在部署列表人数过多的情况下，会放大选取的成员，这一操作会引起选取成员移位，导致MAA无法正确的选取到成员进行部署。
具体表现（关卡DV-S-2，干员数12。）：部署泥岩干员时，会选取到多萝西的地雷进行部署。
![MuMu20220709025317](https://user-images.githubusercontent.com/73384329/178054840-4dd87c6f-8489-498c-bd1a-9f5153d1614d.png)
![MuMu20220709025322](https://user-images.githubusercontent.com/73384329/178054843-245fb6e0-3763-4d14-9278-0b3c5c998f27.png)

：

**Comment by MistEO** [comment]
第二张图是你手动点的泥岩？还是说 maa 点开泥岩之后，却把地雷滑动上去了？

**Comment by nightofknife** [comment]
这个是我手点用来演示的
实际情况是MAA点开泥岩后把地雷画上去了

**Comment by MistEO** [comment]
> 这个是我手点用来演示的 实际情况是MAA点开泥岩后把地雷画上去了

就是说点开的是一个人，滑动的却是另一个？

**Comment by nightofknife** [comment]
另外
选取11人队伍不会有这种问题

**Comment by nightofknife** [comment]
是的

**Comment by nightofknife** [comment]
带了助战（13人队伍）后好像maa会崩溃？
我会提另一个issue

**Comment by MistEO** [comment]
现在压根不点击干员了，是不是没这个问题了（？

**Comment by MistEO** [comment]
@ABA2396 @nightofknife 所以现在还有这个问题（？

**Comment by zzyyyl** [comment]
#6803
