### ISSUE TITLE
MAA切换配置后不会自动启动

### ISSUE THREAD

**Issue by HYY1116** [MaaAssistantArknights/MaaAssistantArknights#11217]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

当前最新内测版本MAA在手动或自动切换配置后，无法自动启动，需要手动启动，启动后为切换的新配置

### Version

Resource Version: 卫戍协议
Resource Time: 2024/11/21 15:03:39
UI Version: v5.10.3-alpha.1.d036.gc7cf92df6
Core Version: v5.10.3-alpha.1.d036.gc7cf92df6
Build Time: 2024/11/22 01:50:23

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17856336/asst.log)
[gui.log](https://github.com/user-attachments/files/17856337/gui.log)

### 配置信息

操作系统:Win10/Win11
开启GPU推理

**Comment by HYY1116** [comment]
Win10为22H2专业版，Win11为23H2专业版，猜测这个问题可能和前段时间命令行切换MAA配置的改动有关）

**Comment by ABA2396** [comment]
哦草，之前测试的东西忘删了

**Comment by ABA2396** [comment]
cd0a53fbe5eb5fe3e0371901243f06d0db1247ec fix
等下打个包
