### ISSUE TITLE
在出现2星作战后，会放弃当作战并尝试继续刷取

### ISSUE THREAD

**Issue by HugeHamster-YWang** [MaaAssistantArknights/MaaAssistantArknights#11221]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

如图，
![屏幕截图 2024-11-23 084124](https://github.com/user-attachments/assets/c98c9500-7f2f-4482-bf30-1b4aa5e67f10)
一觉起来发现maa刷了200把二星的磨难14-12
连续代理失败好像有自动取消刷理智的机制，但是代理二星并不会，这种情况会导致大量理智消耗
以及在mumu模拟器的明日方舟闪退后，maa如果仍在运行，会导致占用的电脑性能大幅增加，一觉起来电脑风扇基本上是拉满的

### Version

UI Version: v5.10.2
Core Version: v5.10.2
Build Time: 2024/11/18 00:09:38

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17877765/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17877770/asst.log)
[gui.log](https://github.com/user-attachments/files/17877772/gui.log)
[gui.bak.log](https://github.com/user-attachments/files/17877771/gui.bak.log)
[gui.json](https://github.com/user-attachments/files/17877766/gui.json)
今天凌晨3点左右的一轮maa出的问题

### 配置信息

mumu, 截图增强未启用，GPU加速未开启，

### 还有别的吗？

感谢maa

**Comment by Saratoga-Official** [comment]
Duplicate of #11207
