### ISSUE TITLE
备选 第二个选项不执行。

### ISSUE THREAD

**Issue by Coney97** [MaaAssistantArknights/MaaAssistantArknights#11230]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

第一备选： pv-9  第二备选：经验本
当检测到pv-9无法开始后，不会去检查第二备选的关卡是否可以进入。

### Version

UI Version: v5.10.2
Core Version: v5.10.2
Build Time: 2024/11/18 00:09:38

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17891520/asst.log)
[gui.log](https://github.com/user-attachments/files/17891521/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17891522/asst.bak.log)
[gui.json](https://github.com/user-attachments/files/17891524/gui.json)
2024/11/24 10：20左右

### 配置信息

MUMU 12   1920*1080 320dpi  60帧
开启gpu加速推理，rtx4090

**Comment by ABA2396** [comment]
39997a467b7f5da60ec81d46ae21c3c3689a50ec fixed
