### ISSUE TITLE
在使用仅一次关机后，执行完关机命令，下一次仅会取消仅一次，而不会取消关机

### ISSUE THREAD

**Issue by hzsy** [MaaAssistantArknights/MaaAssistantArknights#11231]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

如果先点关机再点仅一次，下一次打开maa后仅一次选项被取消而关机选项没有被取消，而正常先点仅一次后点关机则可以正常执行都被取消，目前尚未尝试过是否所有选项均有这个问题，顺带一提这个bug是完成后选项模块化之后出的bug

### Version

UI Version: v5.10.2
Core Version: v5.10.2
Build Time: 2024/11/18 00:09:38

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17891780/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17891781/asst.log)
[gui.log](https://github.com/user-attachments/files/17891782/gui.log)
[gui.new.json](https://github.com/user-attachments/files/17891783/gui.new.json)

### 配置信息

操作系统：Win10 分辨率：1920*1080 DPI：280 帧率：120
模拟器：MuMu12且已开启截图增强
GPU加速推理已开启 笔电3060TI

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/ff5eade6-414a-4d4d-bd35-40a82e7c22d3)
