### ISSUE TITLE
模拟器关闭成功但是提示关闭失败

### ISSUE THREAD

**Issue by Cassy-Lee** [MaaAssistantArknights/MaaAssistantArknights#11234]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

结束时设置自动关闭模拟器，可能出现成功关闭模拟器但是提示关闭失败的情况

### Version

Resource Version: 卫戍协议
Resource Time: 2024/11/15 03:03:33
UI Version: v5.10.2
Core Version: v5.10.2
Build Time: 2024/11/17 10:09:38

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17892394/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17892395/asst.log)
[gui.json](https://github.com/user-attachments/files/17892397/gui.json)
[gui.log](https://github.com/user-attachments/files/17892396/gui.log)
不存在gui.bak.log
相关日志出现在gui.log末尾2024-11-24 01:43:23.186时

### 配置信息

Windows 11
MuMu 12 明日方舟专版 截图增强
未开启GPU加速

### 还有别的吗？

可能是由于GUI尝试在命令行关闭模拟器后获取模拟器实例PID，应在关闭前获取PID并在关闭后检查

**Comment by ABA2396** [comment]
看了下现在是先通过控制台退出再保险起见kill了下端口。感觉最后一步已经没必要了，因为就算kill了对于双进程的模拟器来说只会是报错
