### ISSUE TITLE
异格格雷伊基建错误

### ISSUE THREAD

**Issue by jsls0702** [MaaAssistantArknights/MaaAssistantArknights#1123]
今天基建换班的时候，MAA先将一个格雷伊放入发电站，又将另一个格雷伊放入卧室休息，这样会导致发电站的格雷伊被拿走而没有人值班
日志文件：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9075759/asst.log)

**Comment by Shawnsdaddy** [comment]
新版本好像修复了，你试试新版本

**Comment by MistEO** [comment]
新版本把异格格雷伊的权重拉到最低了，在异格格雷伊心情回复满的情况下这个问题应该不会再出现了
