### ISSUE TITLE
肉鸽bug

### ISSUE THREAD

**Issue by Qwe123-bit** [MaaAssistantArknights/MaaAssistantArknights#11243]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

萨米肉鸽遇到这种消耗材料会一直卡住，水月和傀影刷的时候没有遇到过

### Version

5.10.2

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/17911907/gui.log)
[Uploading gui.js
[gui.new.json](https://github.com/user-attachments/files/17911906/gui.new.json)
on…]()

### 配置信息

12

### 截图或录屏

![IMG_1237](https://github.com/user-attachments/assets/c7ef847a-a725-4b5c-9370-1b9b8709a4c8)

![IMG_1242](https://github.com/user-attachments/assets/a808945d-5baf-420c-8998-f5b9e7f7a29e)

![IMG_1249](https://github.com/user-attachments/assets/8c2cf9b4-c207-448c-beea-71239621532e)

![IMG_1259](https://github.com/user-attachments/assets/ed4c92e5-a8d3-4b90-86e6-5eb6cab8b783)
![Uploading IMG_1260.p
![IMG_1258](https://github.com/user-attachments/assets/0b005066-c73b-43e1-a143-7507592e70c7)
ng…]()

### 还有别的吗？

上传不了其他文件

**Comment by Saratoga-Official** [comment]
日志没上传全，好好看看说明，把debug下的asstlog guilog有多少上传多少

**Comment by Saratoga-Official** [comment]
这位的log太大传不上来，我传到开发群的群文件里了
