### ISSUE TITLE
模拟器一直挂着，第二天重连会卡在更新资源的地方，无法正常继续运行。

### ISSUE THREAD

**Issue by PiDanShouRouZhouXD** [MaaAssistantArknights/MaaAssistantArknights#1124]
日志：
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9075840/asst.zip)

模拟器一直挂着，第二天重连会卡在更新资源的地方，无法正常继续运行。
使用的模拟器是蓝叠Hyper-V版本。
（图没截到）

**Comment by PiDanShouRouZhouXD** [comment]
![image](https://user-images.githubusercontent.com/38401147/178131302-a9d0706d-ddfe-462d-8a4f-505f821b5b75.png)
今天的截图

**Comment by ntgmc** [comment]
该bug已经修复，感谢您的反馈
