### ISSUE TITLE
MAA的退出并关闭模拟器功能无法正常关闭模拟器

### ISSUE THREAD

**Issue by imomor** [MaaAssistantArknights/MaaAssistantArknights#1125]
日志：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9076008/asst.log)

MAA版本：4.0.5

模拟器：MuMu模拟器（群友反应雷电模拟器也有相同问题，未测试）

问题描述：使用MAA完成任务后动作：退出并关闭模拟器，会导致模拟器卡住，需要手动强制关闭程序或结束进程，MAA本体能正常关闭没有影响。该BUG每次执行都能完美复刻。
具体表现如下

执行功能前MAA设置：
![M2U52K}}`8X{_7IV80X`~QH](https://user-images.githubusercontent.com/66689344/178095002-4bea7a2d-9bf6-4544-81c6-08ffab6db527.png)

执行功能后模拟器状态（MAA已秒退没有截到图）：
![8LS3N_USX3 NI}4WI}}E J5](https://user-images.githubusercontent.com/66689344/178095021-bf816b50-27f0-4fa9-857d-342ae290bf5a.png)

**Comment by VentusRanger** [comment]
遇到了一样的问题

**Comment by lmwtju** [comment]
对的，我也是没法正常使用这个功能，雷电模拟器，把MAA设置成管理员运行也不行。模拟器最后会卡住不会关闭

**Comment by MouseWhite** [comment]
这个bug不知道能不能修一修，应该很多人都碰到了 @MistEO

**Comment by zzyyyl** [comment]
> 这个bug不知道能不能修一修，应该很多人都碰到了 @MistEO

之前说也许可以把同个文件夹下的所有进程都 kill 了，然后又说 WSA 可能出问题的来着

**Comment by zzyyyl** [comment]
大多数模拟器都有同样的问题，#1043 有一些目前的讨论结果
