### ISSUE TITLE
MAA资源更新失败

### ISSUE THREAD

**Issue by crimsonpike** [MaaAssistantArknights/MaaAssistantArknights#11256]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

![ZQM)})}M}6G`E(3OBD)SN2H](https://github.com/user-attachments/assets/700498a7-9137-48ff-a8b9-f767724ebbac)
自从更新资源更新功能以来 无论是半夜还是白天 资源更新都是失败 还是只能手动下载资源包 同时挂过梯子也没有用
依旧是带宽堵塞的原因吗？运营商是湖南电信

**Comment by Saratoga-Official** [comment]
你提错issue了吧，这不应该是功能建议

**Comment by ABA2396** [comment]
有问题带日志提bug
