### ISSUE TITLE
maa无法启动

### ISSUE THREAD

**Issue by itissad** [MaaAssistantArknights/MaaAssistantArknights#11269]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

启动时提示需要安装或更新dotnet环境，尝试下载并更新（从提示窗口的链接下载）后错误无变化；尝试卸载dotnet后重新安装仍无效

### Version

5.10.2

### 日志和配置文件

由于应用未启动，无最新日志生成

### 配置信息

win11

### 截图或录屏

![图片](https://github.com/user-attachments/assets/ac1801cd-0945-43df-b5d7-546d86582b88)
![图片](https://github.com/user-attachments/assets/33783f0c-452f-47fa-b692-8bd598a1ea59)

**Comment by Saratoga-Official** [comment]
检查一下环境变量有无异常

**Comment by Saratoga-Official** [comment]
如果还是没解决，建议加githubreadme下面的QQ群找管理员，这种问题在github反馈也没用
