### ISSUE TITLE
公开招募无法识别

### ISSUE THREAD

**Issue by Heart-of-engine** [MaaAssistantArknights/MaaAssistantArknights#11267]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/user-attachments/assets/7c954154-7a99-449e-b965-84b81a068f0d)
如图，**已开启MUMU模拟器截图增强模式**，截图测试一切正常，但无法正常识别公开招募信息

### Version

Resource Version: 卫戍协议
Resource Time: 2024/11/22 04:27:50

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17969126/asst.bak.log)
[asst.log]无效
[gui.bak.log](https://github.com/user-attachments/files/17969141/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/17969143/gui.log)
[gui.json](https://github.com/user-attachments/files/17969150/gui.json)
问题出现的大致时间点为：2024年12月1日21:45

### 配置信息

操作系统：Win10
模拟器品牌：MUMU模拟器12，已开启截图增强模式
模拟器分辨率：2560 x1440(DPI 360) （MUMU模拟器12安装时的默认设置）
模拟器帧率：90
已开启GPU加速推理，GPU型号：Intel(R) lris(R) Xe Graphics

### 还有别的吗？

暂无

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/d19f44c8-cada-4131-9206-32b71ed279b2)
log 没传上来

**Comment by Heart-of-engine** [comment]
估计是网络原因，我再重新传一次
[asst.log](https://github.com/user-attachments/files/17970880/asst.log)

**Comment by Saratoga-Official** [comment]
请提供一下debug\recruit\2024-12-01_21-43-26-439_raw.png这张截图

**Comment by Heart-of-engine** [comment]
![2024-12-01_21-43-26-439_raw](https://github.com/user-attachments/assets/a1323fdf-25b5-4fde-a3b5-0cbc9448e2f5)

**Comment by Saratoga-Official** [comment]
我觉得你可以试试关了gpu加速

**Comment by ABA2396** [comment]
有点抽象，看日志里所有 `干` 字都没识别到，而且 ocr 得分整体偏低。先试试更新下显卡驱动，再不行就别开 gpu 推理了，IU 的核显确实不太行

**Comment by Heart-of-engine** [comment]
确实，关了GPU推理之后就正常了，谢谢！本以为GPU可以作为加分项，没想到反而拖累了整个进程；
![image](https://github.com/user-attachments/assets/40fc785c-dfb4-4d61-aa68-f0f731a1f384)
