### ISSUE TITLE
国服萨卡兹肉鸽使用“刷等级”策略时投资到达999任务被异常结束

### ISSUE THREAD

**Issue by qwedc001** [MaaAssistantArknights/MaaAssistantArknights#11262]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

应该没有重复 report 吧，closed 实在是太多了（
![image](https://github.com/user-attachments/assets/5b901a0e-5838-4370-80a8-8969b9e17b75)
如图，我在常规设置里开启了刷等级策略，但是 MAA 执行到 投资 999 的时候直接放弃了游戏并且结算了任务。
然后肉鸽就刷了一级。
![image](https://github.com/user-attachments/assets/928bb83b-bd8f-413b-b2b0-434a56e38285)
怀疑是投资这一块的逻辑写混了，麻烦佬们检查一下了。

### Version

Resource Version: 崔林特尔梅之金·复刻
Resource Time: 2024/11/26 05:26:05
UI Version: v5.10.2
Core Version: v5.10.2
Build Time: 2024/11/18 00:09:38

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17967706/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17967707/asst.log)
[gui.log](https://github.com/user-attachments/files/17967708/gui.log)
[gui.json](https://github.com/user-attachments/files/17967711/gui.json)
文件夹下未找到 gui.bak.log
问题出现的时间点在上面的截图中有提及。

### 配置信息

Windows 11 24H2 MuMu 12 增强截图开启
开启GPU推理 RTX 4070 Laptop

**Comment by ABA2396** [comment]
高级设置点开，把投资到999就停给去掉

**Comment by qwedc001** [comment]
草，原来是我的问题
说起来这个东西是不是和刷等级设置本来就是冲突的

**Comment by ABA2396** [comment]
说是刷等级，其实只第一层不退罢了，界面上有的设置都是生效的
