### ISSUE TITLE
双击MAA托盘图标导致窗口被固定在 (-32000, -32000)

### ISSUE THREAD

**Issue by Miuzarte** [MaaAssistantArknights/MaaAssistantArknights#11274]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

MAA本体最小化一段时间(过程中没有更改显示器分辨率/插拔显示器)后，窗口位置被固定在显示器外的 (-32000, -32000)，如下方GIF录屏所示

### Version

> 不是最新版，刚刚重启检测到更新了

UI Version: v5.10.3-alpha.1.d071.gb4a674efe
Core Version: v5.10.3-alpha.1.d071.gb4a674efe
Build Time: 2024/12/1 12:20:06
Resource Version: 崔林特尔梅之金·复刻
Resource Time: 2024/11/26 05:26:05

### 日志和配置文件

[config.zip](https://github.com/user-attachments/files/17978270/config.zip)

### 配置信息

![image](https://github.com/user-attachments/assets/8d40e4b6-4eab-4057-b369-972c3e42a651)
![image](https://github.com/user-attachments/assets/e2f3f249-0cce-4ff4-a56a-18ead6b02fe6)
![image](https://github.com/user-attachments/assets/a8ae0bf8-71a3-460b-999e-ff127de0ed91)
![image](https://github.com/user-attachments/assets/8a83a850-f82b-469a-8d9a-0e7ff8fc37fe)

### 截图或录屏

![raUHK8Vw4A](https://github.com/user-attachments/assets/bdbf99f0-7efe-44ea-b976-2f30d62a4d41)

**Comment by ABA2396** [comment]
没遇到过，试试看右键图标点强制显示试试看

**Comment by Miuzarte** [comment]
> 没遇到过，试试看右键图标点强制显示试试看

还有这种功能 确实有用，我之前都是最大化再拖标题栏麻烦死了

**Comment by Miuzarte** [comment]
草，顺便发现托盘图标点快点就能稳定触发了

**Comment by ABA2396** [comment]
草

**Comment by ABA2396** [comment]
没太搞懂这个机制，甚至还不是必现的，试几次偶尔会出现一次，先强制显示凑合用吧（）

**Comment by ABA2396** [comment]
没搞懂，但是不能双击就解决了（x）
