### ISSUE TITLE
萨卡兹肉鸽魂灵护送分队卡死在进第二层获得灵感的地方

### ISSUE THREAD

**Issue by yyjdelete** [MaaAssistantArknights/MaaAssistantArknights#11289]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

看日志好像一直死活匹配不上Sarkaz@Roguelike@CloseCollectionContinue.png, score=0.76..., 
还有的时候不知道为啥反而去匹配上了Sarkaz@Roguelike@DecreaseBurdenChaos.png, score=0.99... (出现时的对应截图是图二"筑墙"和图三"折磨")

asst.log
[2024-12-04 22:05:36.870][TRC][Px6140][Tx6328] match_templ | Sarkaz@Roguelike@CloseCollectionContinue.png score: 0.767828 rect: [ 582, 501, 35, 28 ] roi: [ 549, 440, 123, 130 ]

asst.bak.log
[2024-12-04 21:49:40.531][TRC][Px99d4][Tx8830] match_templ | Sarkaz@Roguelike@CloseCollectionContinue.png score: 0.767571 rect: [ 582, 501, 35, 28 ] roi: [ 549, 440, 123, 130 ]
[2024-12-04 21:49:40.535][TRC][Px99d4][Tx8830] match_templ | Sarkaz@Roguelike@DecreaseBurdenChaos.png score: 0.991592 rect: [ 609, 658, 57, 25 ] roi: [ 559, 608, 157, 112 ]

### Version

UI Version: v5.10.3-alpha.1.d094.g79c656e27
Core Version: v5.10.3-alpha.1.d094.g79c656e27
Build Time: 2024/12/4 21:26:08
Resource Version: 崔林特尔梅之金·复刻
Resource Time: 2024/12/4 16:29:43

### 日志和配置文件

[gui.json](https://github.com/user-attachments/files/18009465/gui.json)
[asst.log.gz](https://github.com/user-attachments/files/18009479/asst.log.gz)
[asst.bak.log.gz](https://github.com/user-attachments/files/18009571/asst.bak.log.gz)

### 配置信息

Win11
MuMu 12 V4.1.7, 截图增强已开启, 1280*720, DPI=320, FPS=60
MaaTouch
GPU加速: GTX 1060/关闭

### 截图或录屏

![2024-12-04_22-06-09-376_raw](https://github.com/user-attachments/assets/22cfd4f1-ecd0-40bb-9acf-1d5ba615a97c)
![MuMu12-20241204-215727](https://github.com/user-attachments/assets/0bde4c16-f627-4742-9eaa-33e920f755cd)
![MuMu12-20241204-222152](https://github.com/user-attachments/assets/14e29e02-f3c9-43af-bd0f-7fcc8556ccfe)

**Comment by Saratoga-Official** [comment]
你既然都会看日志了那教你怎么改
![Z{LR)J%Z3MI~Y3$8Y8UT(VO](https://github.com/user-attachments/assets/381fa0cd-dcbe-45ef-8713-c906daaa6459)
![)`H$X))DSQ$)JFAI}V`HS~6](https://github.com/user-attachments/assets/d74efd23-6a6f-44ce-8e7a-09152926ac81)
把这个改成0.76

**Comment by ABA2396** [comment]
感觉不应该靠降阈值来搞这个，这玩意如果受背景影响的话感觉用 RGBCount 或者 HSVCount 框一下颜色范围应该就好了

**Comment by Saratoga-Official** [comment]
我记得这玩意之前降过一次了，要不不能0.79，反正让他自己改试试呗，不然还要等发版才能修

**Comment by yyjdelete** [comment]
我试下0.76

**Comment by Daydreamer114** [comment]
@yyjdelete 用这个替换掉原来的任务试试，看看得多少分

```json
    "Sarkaz@Roguelike@CloseCollectionContinue": {
        "action": "ClickSelf",
        "roi": [549, 440, 123, 130],
        "method": "RGBCount",
        "colorScales": [
            [
                [100, 100, 100],
                [140, 140, 140]
            ]
        ],
        "next": [
            "Sarkaz@Roguelike@StageEncounterEnter",
            "Sarkaz@Roguelike@Stages#next",
            "Sarkaz@Roguelike@DropsFlag",
            "Sarkaz@Roguelike@CloseEvent",
            "Sarkaz@Roguelike@ChooseOperFlag",
            "Sarkaz@Roguelike@DecreaseBurdenSwapUiToDefault1",
            "Sarkaz@Roguelike@DecreaseBurdenSwapUiToDefault2"
        ]
    },
```

**Comment by yyjdelete** [comment]
"maskRange": [50, 255] -> 跑了一晚上, 日志里面70次, 大部分0.9675~0.9676, 两次0.7823(日志里面OCR出了`互相置换`, 应该是什么事件, 不是下楼的时候的)
删掉maskRange->0.9942(没怎么跑这个, 不知道事件里面是多少)

RGBCount->跑了一上午, 得分0.9428~0.9431, 偶有0.9417, 有出过几次`互相置换`是0.8289, 但0.5s后下一张截图能到正常范围, 
有一次0.79496的, 不知道是啥事件, 看截图里面确认和下一个的图标是半透明叠在一起的, 怀疑用现在这幅图就识别不出来, 不过最后能正常取消探索, MAA自动截图如下
![2024-12-06_09-16-26-270_raw](https://github.com/user-attachments/assets/6a6a70d9-a30a-4fc2-bbbb-7674fea88a66)
![2024-12-06_09-16-29-329_raw](https://github.com/user-attachments/assets/d2aace6a-b2b5-45a7-bda0-b49a8b17d04d)
![2024-12-06_09-16-29-970_raw](https://github.com/user-attachments/assets/7d712018-7594-48ce-a99b-400387e27309)
![2024-12-06_09-16-30-605_raw](https://github.com/user-attachments/assets/3319d553-0ca4-48c2-a658-2808312b6196)
![2024-12-06_09-16-31-241_raw](https://github.com/user-attachments/assets/2bc13be7-a143-4990-bd38-7ac4af8047cc)
![2024-12-06_09-16-31-874_raw](https://github.com/user-attachments/assets/b131443b-be24-4634-afba-f943ea89cbe0)
![2024-12-06_09-16-32-512_raw](https://github.com/user-attachments/assets/c1cab20e-b1a1-422f-8d62-7e769a1ade5a)

**Comment by Daydreamer114** [comment]
感谢，我按照这个灰度再调一下
