### ISSUE TITLE
肉鸽功能增强——关于选择结局的建议

### ISSUE THREAD

**Issue by XingHaiHuShen** [MaaAssistantArknights/MaaAssistantArknights#11283]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [ ] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

目前肉鸽的自动化已经很强大了，但是用途仅限于刷等级、刷钱，关于一些更深层次的功能——例如结局选择并未涉及

### 有什么好的想法？

通过更改MAA选项，在关键的结局导向关卡时更改选择，从而达到刷指定结局的目的
前面的部分就是固定的剧情关换个选项，但是可能很麻烦的是结局BOSS关的自动作战会消耗一定的精力来构建，不知道难度如何

**Comment by Saratoga-Official** [comment]
目前最大的难点是，MAA基本打不过别的结局，这几个肉鸽，2结局3结局4结局基本都是各种机制，MAA只会好了就放，不用机制打打不过

**Comment by Saratoga-Official** [comment]
还有这个issue有人提过了

Duplicate of #7947 #8911

**Comment by XingHaiHuShen** [comment]
成功率这个我觉得其实还好，因为哪怕一结局，他过的概率也不算高，我算是一个轻度肉鸽玩家，就属于肉鸽纯为奖励了，我拿maa挂难度五难度四都做不到，直接通关就一次性的
但是让他反复刷的话，他也可以做到通关


所以我的想法更多是，给个选择，真想要不同结局徽章的人自己自动慢慢刷就好了，总会有一次能够力大砖飞跳过机制的


至于机制利用我就不知道怎么整了，要不能以后maa上个ai模型，让maa_ai来决定什么时候放技能😉



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月3日(周二) 晚上9:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽功能增强——关于选择结局的建议 (Issue #11283)




 
目前最大的难点是，MAA基本打不过别的结局，这几个肉鸽，2结局3结局4结局基本都是各种机制，MAA只会好了就放，不用机制打打不过

**Comment by Daydreamer114** [comment]
目前为肉鸽添加寻路功能已经开始，但进展极为缓慢。
