### ISSUE TITLE
[Yostar servers] Reclamation updates, no need to double confirm

### ISSUE THREAD

**Issue by Manicsteiner** [MaaAssistantArknights/MaaAssistantArknights#11284]
### 说说你遇到的问题？

Tales@RA@PIS-ProsperityBelowLimit-LoadSave
"docRef": "https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/bed66f2c7b8b3f6bd195659121a3d9a0acff8f8b",
"doc": "Needs to be edited if confirmation window is removed later"

No need to double confirm when load-save after this update, time to remove these edits. @Constrat please have a check

**Comment by Constrat** [comment]
1 hour and 30 minutes of maintenance still.

**Comment by HX3N** [comment]
I checked in KR as well, and the double confirm has been removed.
