### ISSUE TITLE
雷电模拟器 多开会自动把修改好的端口号修改为默认端口

### ISSUE THREAD

**Issue by XuyuEre** [MaaAssistantArknights/MaaAssistantArknights#1128]
使用雷电模拟器多开，每次启动 MAA 都会自动把设置好的连接地址 `emulator-5556` 修改为 `emulator-5554`。
手动改回后点击 Linkstart 又会修改回去，只有把占用 `emulator-5554` 端口的模拟器关闭后才不会自动修改。

**Comment by XuyuEre** [comment]
> 使用雷电模拟器多开，每次启动 mma都会自动把设置好的连接地址`emulator-5556` 修改为`emulator-5554`。 手动改回后点击Linkstart 又会修改回去，只有把占用`emulator-5554`端口的模拟器关闭后才不会自动修改。

PS：5554端口模拟器运行的其他游戏且需要使用adb无法关闭

**Comment by MistEO** [comment]
只在连不上的时候才会去自动修改地址的，可能你的 5556 并不能正常连接

发个日志康康
