### ISSUE TITLE
基建干员识别错误

### ISSUE THREAD

**Issue by mingruo233** [MaaAssistantArknights/MaaAssistantArknights#1129]
在有斑点的情况下（并且心情值高于百分之80），选择了未精二的贝娜，砾，以及夜烟。效率低于选择斑点。
在有的情况下调香师的情况下，选择了水月，杰西卡，以及多萝西。效率低于选择调香师。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9077657/asst.log)

**Comment by MistEO** [comment]
看日志识别是正确的，电脑有点卡，在滑动过后画面没有在短时间内停下来，导致识别的那一帧画面和点击的时候不一样，然后点歪了

**Comment by MistEO** [comment]
试试 v4.0.6 还有这个问题么？
