### ISSUE TITLE
MUMU12开启一键长草概率卡死

### ISSUE THREAD

**Issue by swy2018** [MaaAssistantArknights/MaaAssistantArknights#11304]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

mumu12模拟器，在定时或手动开启一键长草时有较大概率（50%左右）明日方舟窗口卡死，已经尝试切换DX和VULKAN、开关后台保活、开关截图增强、开关GPU推理，均无明显变化。电脑配置较高，不太可能是硬件资源不够的原因。
另外，在使用模拟器玩完其他游戏后（无论是否关闭其他游戏窗口）下一次启动MAA定时长草卡死概率明显提高。

### Version

5.11.0beta1

### 日志和配置文件

[debug.zip](https://github.com/user-attachments/files/18035215/debug.zip)
[gui.json](https://github.com/user-attachments/files/18035217/gui.json)
最近一次问题出现时间为2024.12.6 16:30左右
以前的错误大概率发生在在每日00:30 08:30 16:30 20:30这四个MAA定时启动的时间

### 配置信息

win11专业版24H2 hyper-V关闭 9700K Z390 32G 2070SUPER
MUMU12 4.1.8 1080P 280DPI 60帧
截图增强开关、GPU加速推理开关均尝试过，无明显改善

**Comment by ABA2396** [comment]
那不应该找mumu吗）

**Comment by chisato2233** [comment]
我也认为更有可能是mumu的问题而不是maa,这是因为从日志上来看maa好像一切正常,所以也许更换一个模拟器能够解决这个问题
