### ISSUE TITLE
日服 48小時吃理智藥失效

### ISSUE THREAD

**Issue by meowings20000** [MaaAssistantArknights/MaaAssistantArknights#11306]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在勾選無限吃48小時内過期的理智藥但沒用， 似乎是文字辨識錯誤才會導致的

### Version

Resource Version: 生存航路
Resource Time: 2024/12/4 15:03:57
UI Version: v5.11.0-beta.1
Core Version: v5.11.0-beta.1
Build Time: 2024/12/6 02:06:01

### 日志和配置文件

[gui.bak.zip](https://github.com/user-attachments/files/18046176/gui.bak.zip)
[asst.zip](https://github.com/user-attachments/files/18046178/asst.zip)
[asst.bak.zip](https://github.com/user-attachments/files/18046179/asst.bak.zip)

### 配置信息

使用 Bluestacks5 系統：windows11

**Comment by Manicsteiner** [comment]
> [2024-12-07 13:17:24.261][TRC][Px62c][Tx1194] asst::WordOcr [{ T日: [ 0, 0, 33, 23 ], score: 0.984103 }] by OCR Rec , cost 50 ms

这个问题又回来了
