### ISSUE TITLE
i got error when try starting Maa

### ISSUE THREAD

**Issue by MeinMein123** [MaaAssistantArknights/MaaAssistantArknights#11319]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I am using the latest version of the current update and have reviewed both the updates released so far and the unreleased changes in the Pull Requests, there is no mention of the bug being fixed.
- [X] I have reviewed the Pinned issue (Announcements), Open issues, and Closed issues to ensure that my issue has not been mentioned.

### Description

MAA has encountered an error
	External component has thrown an exception.
Solution
	Unknown error occurred
Details
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at MaaWpfGui.Services.MaaService.AsstConnect(IntPtr handle, Byte* adbPath, Byte* address, Byte* config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(IntPtr handle, String adbPath, String address, String config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<>c__DisplayClass91_0.<ConnectToEmulator>b__4()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.ConnectToEmulator()
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.LinkStart()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

![image](https://github.com/user-attachments/assets/c4bf3500-a12d-4f01-8d0a-b7840bfab99e)

### Log and config files

[asst.log](https://github.com/user-attachments/files/18053649/asst.log)
[gui.log](https://github.com/user-attachments/files/18053650/gui.log)
[gui.json.bak.log](https://github.com/user-attachments/files/18053652/gui.json.bak.log)
[gui.new.json](https://github.com/user-attachments/files/18053653/gui.new.json)
[gui.new.json.bak.log](https://github.com/user-attachments/files/18053654/gui.new.json.bak.log)
[gui.json](https://github.com/user-attachments/files/18053655/gui.json)

### Configuration information

Operating system: Microsoft Windows 11 64 bit 24H2
CPU model: AMD Ryzen 7 7800X3D 8-Core Processor           
Motherboard: ASRock B650MPGRiptide
Total memory: Available memory(6.3GB) Total memory(31.1GB)
Resolution: 3440x1440 [Currently in use]
Resolution: 1920x1080
Resolution: 1920x1080
Graphics card: NVIDIA GeForce RTX 3080 Ti(20240926) [Currently in use]
Graphics card: AMD Radeon(TM) Graphics(20240715)
OpenGL: 4.6.0 NVIDIA 565.90
VT: On
HyperV: Off
Run as administrator: No
Disk path: J(SSD-NTFS) Free space(401GB) Total space(475GB)
LDPlayer version: 9.1.26.3(64)
Operating parameters: CPU(4 cores) RAM(4096M) Resolution(1920x1080 DPI 280) FPS(60)
Multi-instance: No.(0) Runing(1) High speed(1) FPS(60) Ultimate multi-instance mode(0)
Disk size: Disk mode(Auto) Available(24GB) Total size(29GB)
Model: Manufacture(OnePlus) Model(GM1900)
Root permission: Off
LDPlayer path: J:\LDPlayer\LDPlayer9\
Log path: C:\Users\quang\AppData\Roaming\XuanZhi9\log

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/7037f082-cdbe-4438-8de9-790b3a2b0740)
Are you sure this is the connection address?
The connection address of LD should be similar to that of `emulator-5554`

**Comment by MeinMein123** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/393774742-7037f082-cdbe-4438-8de9-790b3a2b0740.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzkzMjgsIm5iZiI6MTczMzczOTAyOCwicGF0aCI6Ii85OTA3Mjk3NS8zOTM3NzQ3NDItNzAzN2YwODItY2RiZS00NDM4LThkZTktNzkwYjNhMmIwNzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDEwMTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YTU3ZmJjZWRkMzcxOTRhZTU3YTljNTYzNDQxNjQyMGZhYWRjMjk0NTUzMmVlOGEyYzdmMDhhMjYxOTM0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OMQPM0fnSy5hvVNvdMBaAaUWIluulp9hHwvqWIbWc_0) Are you sure this is the connection address? The connection address of LD should be similar to that of `emulator-5554`

i change it manually and it worked! thank you
