### ISSUE TITLE
萨卡兹肉鸽在进入下一层收灵感的时候卡住，怀疑是只能点next但没有点到

### ISSUE THREAD

**Issue by ffffatgoose** [MaaAssistantArknights/MaaAssistantArknights#11315]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

萨卡兹肉鸽，在进入第二层开始系统会发放灵感，必须点next的位置才能进行下一步，总是在这一步上卡住，然后log显示程序一直在放弃探索也放弃不了，就卡住了

### Version

v5.10.2

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/18050724/asst.bak.log)
[gui.log](https://github.com/user-attachments/files/18050725/gui.log)

### 配置信息

mac os sequoia 15.1.1

### 截图或录屏

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/83c0c43b-da56-4f0a-ab4e-e33e501d210b">

**Comment by Saratoga-Official** [comment]
Duplicate of #11289
