### ISSUE TITLE
添加基建按固定排班表换班的功能

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#1131]
目前的自适应换班智能程度欠佳，对于熟练使用迷迭香、乌有、黑键、灵知等跨设施套组的刀(zi)客(ben)塔(jia)（例如我本人）帮不上什么忙，反而会做出一些高血压行为，需要人工干预。希望可以做一个按照指定排班表进行基建换班的功能。
可以把每一班基建单独保存成json配置文件，然后运行时导入指定的配置文件进行一键换班。
以下表为例，博士自行填写八个班次的排班表，然后在运行的时候手动指定使用哪一张表，当然更好的选择是加一个计数器自动切换当前使用的排班表编号。
![ST5Q(HT1Q9 Y4 5X0~9%NUI](https://user-images.githubusercontent.com/30530115/178133219-d838fa30-73ce-4849-914a-e281b85b2c23.png)
最好再给宿舍加一个黑名单，因为需要使用芳汀的博士会准备20个0心情工具人供芳汀使用，这20个人在平时是不可以进入宿舍回复心情的。
直截了当一些可以直接让玩家的排班表把宿舍的排班也包括进去，而不使用自动识别心情，不过可以额外加入一个按信赖值从小到大排列依次填充宿舍空位的功能（前提是填充的干员为满心情）

**Comment by MistEO** [comment]
不会做，绝大部分用户是不懂基建排班的，他们甚至没有 maa 现在的单设施排的好

至于各个设施联动功能，现在已经在做了 https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/refactor/infrast

**Comment by drunkenQCat** [comment]
其实你可以自己用maa的python接口来实现。每次运行的时候判断一下日志，替换一下备用的infrast.json，这样就可以了。

**Comment by Minepig** [comment]
> 其实你可以自己用maa的python接口来实现。每次运行的时候判断一下日志，替换一下备用的infrast.json，这样就可以了。

请问可否提供相应的文档？

**Comment by Minepig** [comment]
> 其实你可以自己用maa的python接口来实现。每次运行的时候判断一下日志，替换一下备用的infrast.json，这样就可以了。

此外，同时运行三个MAA与三个模拟器，那么中途替换infrast.json是否会导致三个MAA各自逻辑的混乱

**Comment by drunkenQCat** [comment]
> > 其实你可以自己用maa的python接口来实现。每次运行的时候判断一下日志，替换一下备用的infrast.json，这样就可以了。
> 
> 请问可否提供相应的文档？

[集成文档](docs/集成文档.md)里写了。在maa安装文件夹的`Python`文件夹下可以看到asst,py 和相应的例程。

**Comment by drunkenQCat** [comment]
> > 其实你可以自己用maa的python接口来实现。每次运行的时候判断一下日志，替换一下备用的infrast.json，这样就可以了。
> 
> 此外，同时运行三个MAA与三个模拟器，那么中途替换infrast.json是否会导致三个MAA各自逻辑的混乱

理论上是不会的。毕竟json读取之后是在内存里，第一个程序读取修改外部json不会影响另一个程序的读取。另外如果要开三个模拟器，python脚本也可以修改不同的adb连接地址。

**Comment by MistEO** [comment]
不会做自定义换班的，有需求可以试试隔壁 ark mover

**Comment by Minepig** [comment]
实测mower稳定性不太好，要不然我也不会来这里发issue，我早就试过mower和ArknightsAutoHelper了

**Comment by Minepig** [comment]
> 不会做自定义换班的，有需求可以试试隔壁 ark mover

实测mower稳定性不太好，要不然我也不会来这里发issue，我早就试过mower和ArknightsAutoHelper了
