### ISSUE TITLE
领取邮件奖励时，不领取（有时出错，有时不出错）

### ISSUE THREAD

**Issue by 1011official** [MaaAssistantArknights/MaaAssistantArknights#11325]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在“领取奖励”选择“领取邮件奖励”的情况下，不领取邮件并报错

### Version

![屏幕截图 2024-12-09 184857](https://github.com/user-attachments/assets/e0c44109-6ecf-4f1e-bda5-d30d4f33f96e)

### 日志和配置文件

2024-12-09 04:28
[gui.log](https://github.com/user-attachments/files/18058239/gui.log)

[asst.bak.log](https://github.com/user-attachments/files/18058234/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/18058235/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/18058237/gui.bak.log)

### 配置信息

版本	Windows 11 家庭版
版本号	23H2
操作系统版本	22631.4460
模拟器 MuMu 12
分辨率 1920*1080 (DPI 280)
帧率 60
已开启截图增强
GPU加速推理 未开启

### 截图或录屏

https://www.bilibili.com/video/BV1bDqxYsEXJ/

**Comment by 1011official** [comment]
其他录制文件见Q群：290949547→群文件（上传者：长按大拇指3秒）

**Comment by Daydreamer114** [comment]
是澳✌，我们有救了
