### ISSUE TITLE
[EN服][Mac][Playcover] 生息演算制造荧光棒异常

### ISSUE THREAD

**Issue by Nachogao** [MaaAssistantArknights/MaaAssistantArknights#11320]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在使用MAA-生息演算-有存档功能时，设置通过反复制造支援装置来获得生息点数。
但在制造完装置后，无法继续下一步，进而出现异常。

### Version

v5.10.2（547）

### 日志和配置文件

问题出现在20:53分，此前尝试过约三次，都是同一个结果。
[asst.bak.log](https://github.com/user-attachments/files/18054598/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/18054599/asst.log)

### 配置信息

MacBook Air M1, 2020
macOS Sonoma 14.4.1
模拟器：Playcover 3.1.0.maa (310)
分辨率：1080p

### 截图或录屏

<img width="1439" alt="截屏2024-12-08 20 54 22" src="https://github.com/user-attachments/assets/0e769f28-893f-4316-8456-48d7759eaab0">

### 还有别的吗？

荧光棒在EN服必须手动改为Glow Stick。

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/f6427979-e35d-448f-a184-68d369a4f2f3)
只识别到了 anywhere to contin
是不是 roi 框小了
cc @Alan-Charred

**Comment by Alan-Charred** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/393701915-f6427979-e35d-448f-a184-68d369a4f2f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MTkzODgsIm5iZiI6MTczMzcxOTA4OCwicGF0aCI6Ii85OTA3Mjk3NS8zOTM3MDE5MTUtZjY0Mjc5NzktZTM1ZC00NDhmLWExODQtNjhkMzY5YTRmMmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA0MzgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1OWM5OTM1MzZkY2Y4Njk0YTIxZTZjNWQzMDZkY2Q1MzI3ZDg1ZWJmYzlkMmFkYTRhNzhmYTlkYzZiNDQxNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r_1N3FFEsMjn9FhtOy3yGs6ULOf7IwIAOf73KoX24zM) 只识别到了 anywhere to contin 是不是 roi 框小了 cc @Alan-Charred

是的，我决定改为 [500, 445, 280, 41]

**Comment by Alan-Charred** [comment]
您好，初步判断问题是由于 roi 参数给小了导致 OCR 文字不全导致。
已经在修复中。如果方便，您可以尝试手动按照https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11322/files 修改文件。

> 荧光棒在EN服必须手动改为Glow Stick。
MacGui下 目前没有做这个适配，所以的确需要手动修改。我之后会看看能不能优化——
