### ISSUE TITLE
可以终止技能的问题

### ISSUE THREAD

**Issue by Amnesia6** [MaaAssistantArknights/MaaAssistantArknights#11328]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

维什戴尔在打肉鸽的时候出现开个三技能又立即关掉的情况，而且是每次开技能都这样

### 有什么好的想法？

开技能出现stop的时候可以设置不去主动关闭这种技能

**Comment by Saratoga-Official** [comment]
Duplicate of #10926

**Comment by Saratoga-Official** [comment]
技能识别模型的问题，给#10799 提供截图能帮助解决这个问题
