### ISSUE TITLE
肉鸽支持`雪山上的来客`关卡超时自动放弃

### ISSUE THREAD

**Issue by warningme** [MaaAssistantArknights/MaaAssistantArknights#1134]
自动肉鸽关卡“雪山上的来客”时不时出现卡关的现象，敌人在左上角被冻结装置永冻但是没干员打得到导致卡关现象，而且没有退出关卡导致卡住一小时以上好几次。
模拟器用的是蓝叠国际4，64位的，使用的maa软件版本是最新的4.0.5
附上log，不过是最后一次卡死发生是在10号凌晨的3-6点时，而且因为是两个号其中之一（记得是号2），log找起来可能会比较痛苦，截图因为习惯了直接关就没留（如果找不到原因的话，按理说这2天应该还能出一次bug吧，到时专门保存一下log再发。)
[logs.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9079722/logs.zip)

**Comment by MistEO** [comment]
原因就是没有做退出的功能（
