### ISSUE TITLE
请求禁止调度训练室干员

### ISSUE THREAD

**Issue by Roguelife1215** [MaaAssistantArknights/MaaAssistantArknights#11345]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

自从某次更新后，我的logos从来没有触发过一次基建技能，专精没领都能被揪出来扔进宿舍

### 有什么好的想法？

如题，禁止maa调度训练室干员，或者增加一个相关可选项

**Comment by Saratoga-Official** [comment]
Duplicate of #10969

**Comment by Saratoga-Official** [comment]
已有功能，如果有问题请提交一个bug反馈issue

**Comment by ABA2396** [comment]
不是，方舟把这个筛选删了，现在这个用不了了

**Comment by Saratoga-Official** [comment]
也算是bug，没有对应的bugissue开着，先提一个挂着也行

**Comment by Roguelife1215** [comment]
> 已有功能，如果有问题请提交一个bug反馈问题

哪有这个功能？不是直接提示用不了吗

**Comment by Saratoga-Official** [comment]
> > 已有功能，如果有问题请提交一个bug反馈问题
> 
> 哪有这个功能？不是直接提示用不了吗

用不了算bug啊，提issue得提bug反馈而不是功能建议

**Comment by LockRim** [comment]
基建换班高级设置里面勾选训练完成后继续专精
然后把训练室拖到宿舍之前
这样只要提前准备好材料就能自动专精技能
或者只能在换班前自己手动专精
![image](https://github.com/user-attachments/assets/7da63204-d4e7-43c1-bac7-3d897125c6a8)
![image](https://github.com/user-attachments/assets/1ec94980-9627-4d36-86ef-bbcb07615d83)
