### ISSUE TITLE
maa开启时闪退报错，在群里求助后解决不了前来提issue

### ISSUE THREAD

**Issue by q1uqiu** [MaaAssistantArknights/MaaAssistantArknights#11343]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

![N7$G_GT@T)70(K5B~_RY`{7](https://github.com/user-attachments/assets/eacc5a05-d95c-4130-bd7a-a75061dd07d5)

### Version

5.10.2

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/18088649/asst.log)
[gui.log](https://github.com/user-attachments/files/18088650/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/18088652/asst.bak.log)
[gui.bak.log](https://github.com/user-attachments/files/18088653/gui.bak.log)
问题时间点：
12/10 23:00左右 当天上午还能使用晚上就不行了
12/11 10:00左右 隔了一晚上还是不行就到群里求助了
[gui.json](https://github.com/user-attachments/files/18088672/gui.json)

### 配置信息

![image](https://github.com/user-attachments/assets/2ca63003-875c-46ac-9fbb-0e537ec63d6d)
mumu12 分辨率（平板版）1920*1080   dpi280  帧率60  截图增强已开启（maa打不开无法截图）
GPU加速开启  NVIDIA GeForce RTX 3060 Laptop GPU

**Comment by Saratoga-Official** [comment]
群里求助你找管理员了吗，私聊一个叫萨拉托加的管理员（就是我）
