### ISSUE TITLE
在OCR异常时自动截屏，便于定位BUG

### ISSUE THREAD

**Issue by Loner-Knowledge** [MaaAssistantArknights/MaaAssistantArknights#11357]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

今天MAA自动运行的时候报错了，但是在下一次自动运行的时候又一切正常，于是压根没有看到问题出现现场，翻了一下log也没发现到底哪里出了错，log里唯一异常的是非常频繁的`asst::WordOcr [{ _: [ 0, 0, 300, 150 ], score: 0.952789 }] by OCR Pipeline , cost 105 ms`（一共111次）

### 有什么好的想法？

所以希望在“开始唤醒”完成后（因为在这之前也会识别到上面这种情况），识别到这种情况时能自动截屏。
考虑到正常使用用不到的话，可以加一个调试模式的开关，打开之后遇到异常OCR会自动截屏。

### 其他内容

附上出错的log，里面有详细的`asst::WordOcr [{ _: [ 0, 0, 300, 150 ], score: 0.952789 }] by OCR Pipeline , cost 105 ms`。
[asset.log](https://github.com/user-attachments/files/18105586/asset.log)
[gui.log](https://github.com/user-attachments/files/18105587/gui.log)

**Comment by ABA2396** [comment]
那你怎么判断这玩意到底是异常还是有个字就是 `_` ）

**Comment by Saratoga-Official** [comment]
gpu加速开了吗，有些gpu会影响ocr识别出错
