### ISSUE TITLE
定时执行时出现异常

### ISSUE THREAD

**Issue by drunkenQCat** [MaaAssistantArknights/MaaAssistantArknights#1135]
早上起来看maa的界面提示，发现战斗和公招会报错。已经接连几天这样，3:00的任务就会报错。
[asst_711.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9080358/asst_711.log)
电脑是NoAVX的，运行明日方舟的是我的畅玩X6，MAA版本是4.0.5。实际上4.0.4的时候就已经有了这样的问题。

**Comment by horror-proton** [comment]
那明日方舟有没有成功打开, 我看日志好像根本没打开成功

**Comment by drunkenQCat** [comment]
我看了一下，后面基建的部分也有问题，早上起来的时候手机是停在了启动界面。看来确实是没启动成功。我再测试一下。

**Comment by drunkenQCat** [comment]
> 我看了一下，后面基建的部分也有问题，早上起来的时候手机是停在了启动界面。看来确实是没启动成功。我再测试一下。

好了，我知道怎么回事儿了。我个蠢蛋，把手机解锁的定时时间给设成三点五十九了……
