### ISSUE TITLE
新版本活动读取文件失败

### ISSUE THREAD

**Issue by killerxhp** [MaaAssistantArknights/MaaAssistantArknights#11365]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

自动战斗读取失败

### Version

UI Version: v5.11.0-beta.1
Core Version: v5.11.0-beta.1
Build Time: 2024/12/6 02:06:01

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/18135988/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/18135989/asst.log)
[gui.bak.log](https://github.com/user-attachments/files/18135990/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/18135991/gui.log)
[gui.json](https://github.com/user-attachments/files/18135992/gui.json)

### 配置信息

雷电模拟器

### 截图或录屏

![屏幕截图 2024-12-14 211904](https://github.com/user-attachments/assets/cea13f18-1452-410b-9f94-8771c2743a0d)

**Comment by Saratoga-Official** [comment]
更新资源版本即可

**Comment by killerxhp** [comment]
> 更新资源版本即可
点了更新没反应

**Comment by Saratoga-Official** [comment]
挂梯子，你直连也上不了github吧

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/be61360a-7b25-4c97-9b06-44eccd3a3e86)

打开系统通知就能看到成功或失败的提示

即使连不上，公告的最开始就是手动更新教程

**Comment by Saratoga-Official** [comment]
> 即使连不上，公告的最开始就是手动更新教程

现在手动更新教程已经改成让你手点按钮了，不是最早的找资源仓库

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/76a66c98-cec5-404b-a455-fe54c78f2011)
