### ISSUE TITLE
进入战斗后无法放置干员

### ISSUE THREAD

**Issue by athrunclan-xuan** [MaaAssistantArknights/MaaAssistantArknights#11364]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

进入战斗后，到了放置干员那一步，会拖动干员进场，但是没有放到指定位置就结束了，直接导致作业失败。
重新安装没有效果。

### Version

UI Version: v5.10.2
Core Version: v5.10.2
Build Time: 2024/11/18 00:09:38

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/18134349/asst.bak.log)
[gui.json](https://github.com/user-attachments/files/18134351/gui.json)
12/14 
[gui.log](https://github.com/user-attachments/files/18134353/gui.log)
时间：12:00-13:00之间

### 配置信息

MUMU12

### 截图或录屏

无

### 还有别的吗？

无

**Comment by Daydreamer114** [comment]
asst.log.bak 中不包含问题发生时间。

另外，尝试更换触控方式。

**Comment by Saratoga-Official** [comment]
上传新log前先关了

**Comment by athrunclan-xuan** [comment]
重启电脑好了，谢谢




子不语
***@***.***
