### ISSUE TITLE
自动编队时无法识别荒芜拉普兰德

### ISSUE THREAD

**Issue by Kroritaa** [MaaAssistantArknights/MaaAssistantArknights#11361]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

MAA版本v5.10.2，资源版本最新，本次活动代理作业无障碍

但是编队过程中，发现脚本无法识别荒芜拉普兰德，错误判定为没有这个干员
拉普练度如图，立绘为精二立绘
![image](https://github.com/user-attachments/assets/66ac6263-1c82-4f5b-bba6-3a147918f24f)
![image](https://github.com/user-attachments/assets/5f8462db-b13b-41c9-9a1c-ede48677103e)

### Version

资源版本：出苍白海
MAA版本：v5.10.2
![image](https://github.com/user-attachments/assets/9cdfa5f8-61bc-4c05-840b-dd4184b2dc65)

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/18120635/asst.log)
[gui.log](https://github.com/user-attachments/files/18120636/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/18120637/asst.bak.log)
12月13号北京时间上午10:55-11:00
[gui.json](https://github.com/user-attachments/files/18120643/gui.json)

### 配置信息

Windows 10
MuMu模拟器12，未启用截图增强
分辨率1600 x 900，DPI240，最高帧率限制60，没有截图增强和GPU加速推理

### 还有别的吗？

没有了。谢谢MAA，一直都很好用

**Comment by Kroritaa** [comment]
![image](https://github.com/user-attachments/assets/81f92915-6a30-4db8-bf01-c8d829efb6e0)
相似的问题，有的时候黍也识别不出来

**Comment by Windsland52** [comment]
```log
[2024-12-13 10:55:22.249][TRC][Px2a4c][Tx1b94] asst::WordOcr [{ 芜拉普兰德: [ 0, 0, 104, 20 ], score: 0.999939 }] by OCR Rec , cost 16 ms
```
加个(荒)?芜拉普兰德

**Comment by ABA2396** [comment]
荒芜的荒没识别到，改下正则就好了。但黍没什么办法，模型有时候认为这不是个字，识别出来都是空的，只能说720p下识别准确率会稍微高一点

**Comment by Saratoga-Official** [comment]
5.11b1公测版已修复该问题，更新公测版即可

**Comment by Saratoga-Official** [comment]
黍那个如果你有特别关注黍就把特别关注取消了，特别关注会影响识别，如果还不行也没法修，就是maa压根不认识这个字

**Comment by Saratoga-Official** [comment]
反正特关是有必要关的非要删干啥，总不能说没办法解决吧
很多干员都受特别关注影响的，不只黍一个啊

**Comment by Kroritaa** [comment]
啊谢谢，我下的是官网的5.10.2，我去看看更新。
然后如果特殊关注有影响的话，FYI，黍是我的特殊关注，芜拉不是。下次打新关卡我移除特关试试看。
