### ISSUE TITLE
作业编辑器貌似有bug

### ISSUE THREAD

**Issue by HMZyueshen** [MaaAssistantArknights/MaaAssistantArknights#1137]
作业中写了描述或者标题，maa才识别得出来
好像不写描述或者标题作业文件里没有doc
![image](https://user-images.githubusercontent.com/106477016/178181880-29793aaa-6d4f-42db-a41c-2bed35b5285c.png)
![image](https://user-images.githubusercontent.com/106477016/178181936-4ac48bf2-d19e-49d5-a025-2f35e09d0469.png)
没有“doc”？

**Comment by MistEO** [comment]
https://prts.plus/create
