### ISSUE TITLE
一键长草无法自动肉鸽，多个任务序列有肉鸽时也无法正常启动

### ISSUE THREAD

**Issue by YashinNieh** [MaaAssistantArknights/MaaAssistantArknights#11371]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

一键长草任务序列中包含或者仅包含肉鸽时，会出现无法启动任务的状态，按钮只是短暂的从 ▶️ 变成 loading 再回到 ▶️ ，显示“正在运行中……”，游戏无任何反应，也没有相关报错。

### Version

Resource Version：最新
MAA version：v5.10.2（547）

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/18145023/asst.log)

### 配置信息

MacOS  Sequoia 15.0.1 
Playcover  3.1.0.maa (310)

### 截图或录屏

https://github.com/user-attachments/assets/078317bc-9183-4099-92f8-c50a7c51fbe8

**Comment by Saratoga-Official** [comment]
请把maa更新到公测版再尝试，更新设置里选择使用开发版

**Comment by Saratoga-Official** [comment]
Duplicate of #11215

**Comment by YashinNieh** [comment]
> 请把maa更新到公测版再尝试，更新设置里选择使用开发版

问题解决了，谢谢！
