### ISSUE TITLE
台服刷理智完引导卡在活动页面

### ISSUE THREAD

**Issue by amasoiD** [MaaAssistantArknights/MaaAssistantArknights#11392]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

刷完理智会卡在活动页面，无法回到主页面，导致其他任务出错
![Screenshot_20241219-234038](https://github.com/user-attachments/assets/9822345f-a317-4be7-9b8a-cbf46f840041)

### Version

UI Version: v5.11.0-beta.2.d039.g6a9390170
Core Version: v5.11.0-beta.2.d039.g6a9390170
Build Time: 2024/12/19 06:09:51

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/18200069/asst.log)
[gui.log](https://github.com/user-attachments/files/18200070/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/18200072/asst.bak.log)
没有gui.bak.log
[gui.json](https://github.com/user-attachments/files/18200077/gui.json)

### 配置信息

操作系统: Windows 10 家用版 20H2
模拟器: 雷电 9.1.32.0(64)、分辨率1280 x 720、DPI 240、帧率60
未开启截图增强、GPU 加速推理

**Comment by Manicsteiner** [comment]
活动界面左上角的返回按钮不是标准的返回按钮，无法识别

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/2aa5aa24-dd77-45e1-a61e-17b475e5411a)
草了，之前这个活动就给改成了 0.7 ，结果这位的得分是 0.699）

**Comment by ABA2396** [comment]
这个活动反正也是最后一次了，感觉没必要再整个多匹配的图。手动改一下 tasks.json 里的
```
"Return": {
    "action": "ClickSelf",
    "templThreshold": 0.7,
    "postDelay": 2000,
    "roi": [0, 0, 180, 80]
},
```
```
"Return": {
    "action": "ClickSelf",
    "templThreshold": 0.68,
    "postDelay": 2000,
    "roi": [0, 0, 180, 80]
},
```
吧

**Comment by waya1s** [comment]
請教一下tasks.json在哪裡??

**Comment by ABA2396** [comment]
在maa文件夹的resource文件夹里

**Comment by Saratoga-Official** [comment]
> 这个活动反正也是最后一次了，感觉没必要再整个多匹配的图。手动改一下 tasks.json 里的

也不好说啊，万一过两年又复刻了呢，源石尘也有先例
