### ISSUE TITLE
蓝叠模拟器双开无法识别端口号

### ISSUE THREAD

**Issue by UniMars** [MaaAssistantArknights/MaaAssistantArknights#1139]
蓝叠每次启动都会更改adb端口，所以之前我通过  "Bluestacks.Config.Path": xxx"的方式让软件自动识别端口。
但是后来当我通过附加命令”--instance Nougat64_1“的方式启动模拟器双开之后，软件总是自动识别初始引擎的端口，无法正确识别新双开引擎的端口号，并且当我注释掉"Bluestacks.Config.Path": xxx"之后，软件启动后会自动删除这一行，之后无法直接从注释状态进行切换。
是否有办法让软件自动识别不同引擎的端口号，或者识别出所有的端口号，并在第一个端口号连接失败后切换至下一个端口号？

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
