### ISSUE TITLE
建议公招出现组合词条的高星干员提示具体组合方式

### ISSUE THREAD

**Issue by FreddieGeorge** [MaaAssistantArknights/MaaAssistantArknights#11397]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

![image](https://github.com/user-attachments/assets/e9776b1b-acb9-485a-95cb-f4b613025fa2)

目前版本的高星公招在遇到组合tag的时候，没有提示具体是什么组合可能出五星

### 有什么好的想法？

增加输出提示

**Comment by ABA2396** [comment]
~~显然是先锋控场德克萨斯~~

**Comment by ABA2396** [comment]
感觉没必要，不然出个资深的词条一整页都是输出了

**Comment by Daydreamer114** [comment]
自动选择干嘛告诉你有什么组合，如果不想自动就把自动五星关了，然后用 小工具 - 公招识别 自己看
