### ISSUE TITLE
萨米肉鸽稀有坍缩泛式自动刷取遇到一级坍缩直接退出存在的逻辑问题

### ISSUE THREAD

**Issue by Yress** [MaaAssistantArknights/MaaAssistantArknights#11399]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

目前老师制作的maa萨米肉鸽稀有坍缩泛式脚本存在一个刷取逻辑问题
一般来说刷取稀有坍缩泛式的人同时也需要能遇见坍缩2级图鉴
但是目前maa是遇见稀有坍缩1级直接退出，导致白刷了

### 有什么好的想法？

maa设置建议改成遇见初级稀有坍缩后（目空一切和图像损坏）选择停止操作，交由玩家自己决定是否遇见二级坍缩

### 其他内容

![6c5bbf75-3ba3-4ff2-8311-4ce206ebb8d7](https://github.com/user-attachments/assets/6b3581ed-8d83-4c42-99ec-92b2bd5af5b7)

**Comment by Daydreamer114** [comment]
#11327

**Comment by ABA2396** [comment]
如果你自己不填要刷的东西，那默认刷到稀有坍缩就会停，一二级的稀有坍缩都是稀有。如果你要刷指定的，那你就自己传列表
![image](https://github.com/user-attachments/assets/367613ac-7f01-48ea-8d6c-9cfc40c606dc)

**Comment by Alan-Charred** [comment]
您好，遇到需要的坍缩范式后，MAA 会退出当前探索，但不会放弃当前探索。您应该可以通过继续探索来加深坍缩范式。
