### ISSUE TITLE
定时任务无法识别签到界面

### ISSUE THREAD

**Issue by CesareEligos** [MaaAssistantArknights/MaaAssistantArknights#1140]
使用定时任务开启模拟器时，MAA不会识别每天初次签到，会卡在主界面
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9083985/asst.log)
。

**Comment by CesareEligos** [comment]
使用的模拟器是蓝叠
![PHJVO1LWN~9WFV)5PLX5NHW](https://user-images.githubusercontent.com/107906930/178265223-64d0c987-2d1c-4c48-83c3-7075cd3b2192.png)

**Comment by horror-proton** [comment]
和这个好像是一样的问题 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/974
好像是因为 `TodaysSupplies.png` 的画面弹出到一半的时候截了图, 结果都没匹配上然后进入 Stop 了

ref. https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1098#issuecomment-1175818799

**Comment by horror-proton** [comment]
还有一种可能的解决方法是 `"TodaysSupplies"`, `"CloseAnno"` 第一次没识别到的话间隔一秒重新识别一次, 防止正好截图到中间画面. 
或者也许直接像类似于 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1098#issuecomment-1176221755 提到的一样, 写一个能从任意状态返回主界面的 task 加在其他每个任务前面 (比如疯狂点右上角, 遇到 Confirm 按钮全部确定, 遇到通知全部关闭 (x
