### ISSUE TITLE
一键解决复刻活动

### ISSUE THREAD

**Issue by 0u0u0** [MaaAssistantArknights/MaaAssistantArknights#11402]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 有什么好的想法？

建议增加复刻模式：一键自动代理作战本次复刻活动内全部关卡，包括ex之类的附加关卡，自动使用理智药。现在的模式似乎不会代理ex，似乎无法自动补充理智直到复刻关卡都刷完。

**Comment by ABA2396** [comment]
所以为什么要打ex呢）

**Comment by Saratoga-Official** [comment]
补充理智的话勾选使用理智药就行了，至于复刻的ex，公认都是没必要刷，主要的奖励打完普通关就能拿到了，ex没石头也没掉落光是活动点数比较亏
