### ISSUE TITLE
[国际服EN]生息刷分故障卡住/Stuck when farming Reclamation point

### ISSUE THREAD

**Issue by BlackNorton** [MaaAssistantArknights/MaaAssistantArknights#11401]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

用MAA在生息刷分会卡住，使用的是最后拓展才加的捕网发射器

Using maa to farm points in RA, stuck at item crafting for "Hunting Net Launcher"

### Version

Resource Version: Rhodes Island Icebreaker Games
Resource Time: 2024/11/15 01:26:34
UI Version: v5.10.2
Core Version: v5.10.2
Build Time: 2024/11/18 00:09:38

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/18216711/asst.log)
[gui.log](https://github.com/user-attachments/files/18216712/gui.log)
[gui.json](https://github.com/user-attachments/files/18216714/gui.json)

### 配置信息

Win10
Bluestack 5.21.610.1003 Android 11
1920x1080 320dpi

### 截图或录屏

![Screenshot_2024 12 21_08 55 18 285](https://github.com/user-attachments/assets/bdaf9024-a84c-4cde-aaa1-c9c88d4c51ff)

**Comment by BlackNorton** [comment]
Update the resource to the newest, still stuck at the same spot

Resource Version: Path of Life
Resource Time: 2024/12/21 01:27:38

**Comment by BlackNorton** [comment]
The issue also occur when try to craft "glow stick"
![Screenshot_2024 12 21_09 21 03 871](https://github.com/user-attachments/assets/613588cd-7bb5-4d3a-bbef-6e6db0388fed)

**Comment by ABA2396** [comment]
参考 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/11320
现在还没发正式版，你可以照着 commit 自己修改，或者尝试更新公测版

**Comment by BlackNorton** [comment]
> 参考 #11320 现在还没发正式版，你可以照着 commit 自己修改，或者尝试更新公测版

修改后解决了卡在物品合成界面，但是又在回档天数那里卡住了
[gui.log](https://github.com/user-attachments/files/18218879/gui.log)
[asst.log](https://github.com/user-attachments/files/18218880/asst.log)

![Screenshot_2024 12 21_23 08 22 369](https://github.com/user-attachments/assets/416b5d15-0c04-4ece-83a5-520057f9442a)

很在之前在b服也出现过这个问题，当时汇报过了
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9312#issue-2340985151

**Comment by ABA2396** [comment]
cc @Alan-Charred

**Comment by Alan-Charred** [comment]
（挠头）没看懂 Log，进入了这个后为什么开始识别 `Tales@RA@DialogConfirmYellow` 了？您修改后的 tasks.json 文件可以分享一下吗？感觉流程里出现了我没配置过的东西。

**Comment by Alan-Charred** [comment]
> （挠头）没看懂 Log，进入了这个后为什么开始识别 `Tales@RA@DialogConfirmYellow` 了？您修改后的 tasks.json 文件可以分享一下吗？感觉流程里出现了我没配置过的东西。

我意识到了发生了什么。。。
国际服有改动。
@ABA2396 e7925f51 学姐这个 commit 在什么状态？dev、测试服、正式服？

**Comment by Alan-Charred** [comment]
请尝试更新版本或参考 e7925f51 改改文件喵。

**Comment by Constrat** [comment]
@Alan-Charred I just noticed. For the future. To check the status of a commit just click here:
![{E1A94FBF-926B-47E3-AA57-CE2B6D0C68BB}](https://github.com/user-attachments/assets/b6b035b0-814e-49d0-baf8-21be2ff4cc6d)

![{7DF3F091-BDA7-4216-8CAE-2720428E4D28}](https://github.com/user-attachments/assets/abb21312-a388-4d9d-913b-abaea156b9f5)

**Comment by Alan-Charred** [comment]
> @Alan-Charred I just noticed. For future reference. To check the status of a commit just click here:
> 
> ![{E1A94FBF-926B-47E3-AA57-CE2B6D0C68BB}](https://github.com/user-attachments/assets/b6b035b0-814e-49d0-baf8-21be2ff4cc6d)
> 
> 
> 
> ![{7DF3F091-BDA7-4216-8CAE-2720428E4D28}](https://github.com/user-attachments/assets/abb21312-a388-4d9d-913b-abaea156b9f5)
> 
> 
> 
> > Resource Version: Rhodes Island Icebreaker Games
> 
> Resource Time: 2024/11/15 01:26:34
> 
> UI Version: v5.10.2
> 
> Core Version: v5.10.2
> 
> Build Time: 2024/11/18 00:09:38
> 
> 
> 
> Outdated indeed :)

Thanks! That's pretty handy.

**Comment by Constrat** [comment]
It is indeed. Otherwise, the only solution is to check each tag individually by "latest commit."

**Comment by BlackNorton** [comment]
> （挠头）没看懂 Log，进入了这个后为什么开始识别 `Tales@RA@DialogConfirmYellow` 了？您修改后的 tasks.json 文件可以分享一下吗？感觉流程里出现了我没配置过的东西。

[tasks.json](https://github.com/user-attachments/files/18220359/tasks.json)

**Comment by BlackNorton** [comment]
> 请尝试更新版本或参考 [e7925f5](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/e7925f5191a4fa636947a9f5904c1d08344e0ebe) 改改文件喵。

同时更改[roi](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11322/files)和[e7925f5](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/e7925f5191a4fa636947a9f5904c1d08344e0ebe#diff-8964c6f83c91b3a235924066c5b7efbdd8cb5f67fdcf00e431699756c388d067R2596)
问题解决
