### ISSUE TITLE
Wrong event identification in IS2 Phantom

### ISSUE THREAD

**Issue by IX-Vyselotte** [MaaAssistantArknights/MaaAssistantArknights#11416]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I am using the latest version of the current update and have reviewed both the updates released so far and the unreleased changes in the Pull Requests, there is no mention of the bug being fixed.
- [X] I have reviewed the Pinned issue (Announcements), Open issues, and Closed issues to ensure that my issue has not been mentioned.

### Description

According to MAA's activity log, it seems that the BOT has identified the event node "A Gentleman's Ending" as the trading node "Rogue Trader"

### Version

Both versions 5.10 and 5.11 beta 2 have this bug

### Log and config files

[gui.log](https://github.com/user-attachments/files/18224079/gui.log)

### Configuration information

MuMu 12 
![image](https://github.com/user-attachments/assets/4a1cb804-cc3f-4afc-ba5d-ddd126337477)
![image](https://github.com/user-attachments/assets/63630607-b70c-45be-b4aa-de32d14bce2a)
![image](https://github.com/user-attachments/assets/04ff69e0-1ffd-411c-a7cc-29d5c7bae21f)
![image](https://github.com/user-attachments/assets/a0f43f55-c2a5-4d87-83ad-f50f7072af07)
![image](https://github.com/user-attachments/assets/b0a5de33-1a7d-4ea5-80b7-e817f07f9aad)
![image](https://github.com/user-attachments/assets/17ca5797-b23d-4744-a842-c3150c53b0a8)
![image](https://github.com/user-attachments/assets/f784373b-b4f2-4b9a-ae87-05475393751f)

### Anthing else?

This can be considered a bug because after misidentifying the node (as noted above), the BOT enters AFK state, not working until I make the choice to end the "A Gentleman's Ending" node and the BOT works normally again (for MAA 5.11 beta 2); or loses connection and has to wait for reconnection to the MuMu emulator (for MAA 5.10).
In addition, there is a file that the admin requested with the extension .bak.log that I cannot upload because the capacity exceeds the allowed limit

**Comment by Constrat** [comment]
![{434E0ECB-4225-4F12-9E50-BA98F9EFCB38}](https://github.com/user-attachments/assets/5de163ae-c6ef-40ec-99cf-1d36118c4378)

**Comment by Daydreamer114** [comment]
well, for asst representing assistant, without log file, we can not tell anything about what maa has got.

this issue mostly because of your resolution. try update your mumu12 to get 1920 x 1080 option.

![image](https://github.com/user-attachments/assets/5002b909-aa42-4ffc-9fb2-81c526ae446b)
