### ISSUE TITLE
繁中服 好友訪問沒反應

### ISSUE THREAD

**Issue by EROTCZ** [MaaAssistantArknights/MaaAssistantArknights#11418]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

繁中服
主頁面進入 好友 然後就停在好友列表 沒反應了
時間點大約是18:49:12那

後續 開始OF-1 刷信賴 跟商店領信用 <這邊都正常

### Version

Resource Version: 水晶箭行動
Resource Time: 2024/12/19 01:07:59
UI Version: v5.11.0-beta.2
Core Version: v5.11.0-beta.2
Build Time: 2024/12/15 20:57:06

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/18228588/asst.log)
[gui.log](https://github.com/user-attachments/files/18228591/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/18228596/asst.bak.log)
[gui.bak.log](https://github.com/user-attachments/files/18228600/gui.bak.log)
[gui.json](https://github.com/user-attachments/files/18228603/gui.json)

### 配置信息

WIN 11 23H2
MuMu Player 12 V3.8.18
1920 x 1080(DPI 280)
帧率 60
截图增强 沒開啟

### 截图或录屏

![螢幕擷取畫面 2024-12-23 190521](https://github.com/user-attachments/assets/53cfec87-374d-4f11-ae5e-337f363bb74a)
![螢幕擷取畫面 2024-12-23 185452](https://github.com/user-attachments/assets/c0d2a5b3-1ba5-4d2c-9a3f-409b83bb78f6)

**Comment by Saratoga-Official** [comment]
可以看一下＃11246 看来台湾服的ui更新了，导致之前的适配失效了

**Comment by momomochi987** [comment]
#11384

已經有處理過這個問題了，可以等後續的公測版更新或是自行操作以下內容

1. 直接刪除 `你的 MAA 資料夾/resource/global/txwy/resource/template` 中的 StartToVisit.png 此張圖片檔案

2. 移除 `你的 MAA 資料夾/resource/global/txwy/resource/tasks.json` 中的以下內容

```json
    "StartToVisit": {
        "doc": "Temp fix until Overseas gets the same interface as Official, expected to be removed in December 2024 OPERATION LUCENT ARROWHEAD",
        "templThreshold": 0.8,
        "roi": [920, 91, 162, 141]
    },
```

**Comment by EROTCZ** [comment]
謝謝 刪除後重啟MAA 好友訪問正常了
