### ISSUE TITLE
[小工具->干员识别] 这个功能用到的数据库中包含了非常驻的罗德岛精英干员和助战干员

### ISSUE THREAD

**Issue by APLaS-Plus** [MaaAssistantArknights/MaaAssistantArknights#11411]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，确认我的建议未被提及
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的建议未被提及

### 说说你遇到的问题？

在卫戍协议版本后的MAA中，干员仓库的识别结果里面多了罗德岛精英干员和临时助战干员，这些都不是常驻角色，属于改改数据库引用的小问题。

建议在干员识别这个功能中直接加入黑名单

**Comment by Saratoga-Official** [comment]
你应该是没更新maa到最新版本，这个问题已经修了，你把maa版本更新改成公测版应该就可以了
