### ISSUE TITLE
繁中服活動水晶箭行動關卡作戰道具無法識別

### ISSUE THREAD

**Issue by laetita0319** [MaaAssistantArknights/MaaAssistantArknights#11429]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

已將MAA版本及資源更新到最新的情況下
自動戰鬥作業中
無法識別道具詭雷布設裝置
其他兩項作戰道具或許也有相同問題

### Version

UI Version: v5.11.0-beta.2
Core Version: v5.11.0-beta.2
Build Time: 2024/12/15 20:57:06
Resource Version: 水晶箭行動
Resource Time: 2024/12/19 01:07:59

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/18245083/asst.bak.log)
[gui.json](https://github.com/user-attachments/files/18245085/gui.json)
[asst.log](https://github.com/user-attachments/files/18245105/asst.log)
[gui.log](https://github.com/user-attachments/files/18245106/gui.log)

時間點2024-12-25 17:26:23及17:34:53

### 配置信息

模擬器Bluestacks 5
分辨率1600 x 900
240 DPI
60FPS

**Comment by laetita0319** [comment]
自行解決方式：
resource/global/txwy/resource/tasks.json

CharsNameOcrReplace底下新增三行
            ["封阻加固裝置", "封阻加固装置"],
            ["臨時掩護裝置", "临时掩护装置"],
            ["詭雷布設裝置", "诡雷布设装置"],

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/97fc987e-5292-44b2-a3e8-e47ec7a52739)

自动添加内容是正常的，没发版

我把你说的另外两个添进去吧

@ABA2396 外服的这个 CharsNameOcrReplace 是不是应该放到资源更新里
