### ISSUE TITLE
美服基建换班报错

### ISSUE THREAD

**Issue by XIACHKaaaaaaaaaa** [MaaAssistantArknights/MaaAssistantArknights#11424]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I am using the latest version of the current update and have reviewed both the updates released so far and the unreleased changes in the Pull Requests, there is no mention of the bug being fixed.
- [x] I have reviewed the Pinned issue (Announcements), Open issues, and Closed issues to ensure that my issue has not been mentioned.

### Description

基建换班功能到宿舍 选人时卡住
![微信截图_20241224230400](https://github.com/user-attachments/assets/54d2abcb-c194-4861-92f2-e8747bacecaf)

### Version

![微信截图_20241224225636](https://github.com/user-attachments/assets/abc115a3-2cfe-4b1c-9491-581dd02059b6)

### Log and config files

[gui.json](https://github.com/user-attachments/files/18240492/gui.json)
[asst.bak.log](https://github.com/user-attachments/files/18240494/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/18240495/asst.log)
[gui.log](https://github.com/user-attachments/files/18240496/gui.log)
此文件夹（debug）未拥有gui.bak.log文件

### Configuration information

win10 MuMu 12 3核心 6G 1280*720 60 截图增强未启用 GPU 加速推理未启用

**Comment by Constrat** [comment]
> 1280*720

> 5.10.2

1. Change to 1080p
2. update to at least the latest beta

**Comment by XIACHKaaaaaaaaaa** [comment]
可以 解决了 我的问题 耽误大家时间了
