### ISSUE TITLE
作业协议的“groups”增加“qty_reqd”字段以支持不定干员的作业

### ISSUE THREAD

**Issue by Lancarus** [MaaAssistantArknights/MaaAssistantArknights#1142]
1.作业的指令是否应该增加未找到干员时跳过或者超时跳过(肉鸽和保全需要这样)
2.群组增加需要数量的字段,在编队时编入所需数量的干员后跳出该群组
3.部署或者释放技能时的"name"可以是群组名,查找群组内第一个存在的干员并部署/释放技能

**Comment by MistEO** [comment]
这字段啥意思（

**Comment by Lancarus** [comment]
百度翻译下？狗头



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月12日(周二) 中午11:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 作业协议的“groups”增加“qty_reqd”字段以支持不定干员的作业 (Issue #1142)




 
这字段啥意思（

**Comment by Lancarus** [comment]
[肉鸽作业.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9089385/default.zip)
[萝卜矿场.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9089386/default.zip)
[盘桓蜀道_棘刺+煌+桃金娘+伊芙利特+艾雅法拉+塞雷娅+温蒂+伊桑+拉普兰德.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9089388/_.%2B.%2B.%2B.%2B.%2B.%2B.%2B.%2B.txt)
再肝只支持应该就能用了格式的要改下后缀名
