### ISSUE TITLE
老关卡作业关于关卡名识别问题

### ISSUE THREAD

**Issue by AKiSA07** [MaaAssistantArknights/MaaAssistantArknights#11425]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

喧闹法则EX关作业(CB-EX)由于关卡名EX后并非是[EX-数字]格式而是[EX数字]导致MAA无法识别关卡和导入作业信息，只能通过下载json一个一个在战斗列表下方的关卡名修改后才能正常识别并开始战斗

### Version

Resource Version: 银心湖列车·复刻
UI Version: v5.11.0-beta.2.d066.g01e4b2470
Core Version: v5.11.0-beta.2.d066.g01e4b2470

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/18240615/asst.log)
[gui.log](https://github.com/user-attachments/files/18240616/gui.log)

### 配置信息

Windows10 mumu12 1280*720 DPI:240 60Fps
开启截图增强，使用GPU加速推理 NVIDIA GeForce RTX2060

### 截图或录屏

![1](https://github.com/user-attachments/assets/72fd490c-e1f8-49f4-a928-4b7f23211f26)
![2](https://github.com/user-attachments/assets/9315581d-0b80-4b52-947d-a37ac96e9b47)
![3](https://github.com/user-attachments/assets/a402f52d-3fb1-470f-bab9-625b14a9d00f)
![4](https://github.com/user-attachments/assets/e50127d2-c934-4b1a-9035-47baaf0efca3)

**Comment by AKiSA07** [comment]
直接导入json可以开始战斗，可是会卡在识别关卡名，一直在划关卡

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/a2b3bd79-f464-47d7-925d-7e080307abe1)
这个地方是可以手动输入的，输完之后点右边的 +

**Comment by AKiSA07** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/398444906-a2b3bd79-f464-47d7-925d-7e080307abe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNjEwMDYsIm5iZiI6MTczNTA2MDcwNiwicGF0aCI6Ii85OTA3Mjk3NS8zOTg0NDQ5MDYtYTJiM2JkNzktZjQ2NC00N2Q3LTkyNWQtN2UwODAzMDdhYmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDE3MTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZDM2ODYzZThkOWJmNjhmMTgwMGJiZTE2N2I1NGJlYWM4MjVjZTI0Y2M1NzlkY2Q3MzRkOGMxYzE5YzViNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B1dJWllW5_aBlI7ZpANMG6GGaAvTR_EQoaOJsvYCdHk) 这个地方是可以手动输入的，输完之后点右边的 +

如果是作业集一键导入战斗列表的话，战斗列表根本识别不了

**Comment by ABA2396** [comment]
那难道不应该修改作业匹配格式吗）

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/46c7cdf5-ac3f-4a6f-8d84-b200c1de07ab)
![image](https://github.com/user-attachments/assets/59585e05-f3aa-4756-9394-0a881c7289cc)

右键导不进来任何东西，可以考虑适配一下 @ABA2396 (祝好)

**Comment by ABA2396** [comment]
这不是改一下作业名就好了吗）

**Comment by Daydreamer114** [comment]
就是说这个作业名是和游戏里对着的，战斗列表ocr也应该用当前这个作业名
