### ISSUE TITLE
Github Actions workflow secrets permissions

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#11426]
### The problems you have encountered?

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/45c803def4dd050122ddb4385f5b741eed8e6c44/.github/workflows/smoke-testing.yml#L121-L134

Using `secrets.GITHUB_TOKEN` works for all organization branches as by default the `permissions` are `actions: write`.

The issue arises when the workflow is run from a branch of a forked repo, where by default the `secrets.GITHUB_TOKEN` only has `actions: read` for obvious security reasons.

To delete cache, `actions: write` is required. What secret is the most optimal one? Minimum amount of permissions that has at least `actions: write`? MISTEOWORKFLOW? But it's an organization secret and seems to have a lot more permissions.

I longer have access to the secrets section to check, which is why asking the question.

cc @ABA2396 @AnnAngela

**Comment by AnnAngela** [comment]
I recommend skipping this step in a forked repo or changing the url in L133 to match the forked repo, since the main repo's cache should not be affected by the forked repo.

**Comment by AnnAngela** [comment]
Maybe we can use seperate workflow to delete the cache for forked repo, like <https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries>?

**Comment by AnnAngela** [comment]
and we can use github cli to rewrite the curl command

**Comment by Constrat** [comment]
- Using the API is better since we don't need the clone and checkout the repo
- Using it in the single workflow is to reduce calling times and overcomplicate the workflow logic. If the cache is created there, I would like it to delete it there as well. 
The only issue is that I don't know if there are any secrets with `actions: write`.

I think there are some but they have a lot more permissions that will not be used.

**Comment by AnnAngela** [comment]
I just don't like the idea, but if you want it, use `secrets.MAA_ACTION_READ_WRITE`
