### ISSUE TITLE
asst.log中 Bskill_ctrl_lda（老鲤 浮生得闲） 被错认为是 吽的坚毅随和

### ISSUE THREAD

**Issue by HeroTch** [MaaAssistantArknights/MaaAssistantArknights#1143]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9085626/asst.log)
v4.0.5 7/11 23:41:17开始控制中枢换班，老鲤技能在log里被错误识别 ，之前的控制中枢中存在**老鲤单独上班**的情况

**Comment by MistEO** [comment]
确定了下 Bskill_ctrl_lda 识别错误这个问题 v4.0.6 已经修复了，更新下试试

**Comment by MistEO** [comment]
不对似乎还有其他问题，那等等 v4.0.7 吧
