### ISSUE TITLE
肉鸽招募卡着

### ISSUE THREAD

**Issue by kingegora** [MaaAssistantArknights/MaaAssistantArknights#11436]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

选招募只选山（我放了锏）
![Screenshot 2024-12-27 001325](https://github.com/user-attachments/assets/f0502cb0-d872-4589-96b3-94e9779ae4e9)

### Version

v5.11.0

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/18253823/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/18253824/asst.log)
[gui.log](https://github.com/user-attachments/files/18253825/gui.log)

### 配置信息

window 11 
bluestack5

### 截图或录屏

![Screenshot 2024-12-26 233806](https://github.com/user-attachments/assets/6e1294c2-f533-4c03-936f-9c04d287f2bf)

**Comment by Daydreamer114** [comment]
bro你指望识别简中的匹配库能识别繁中是吧

**Comment by ABA2396** [comment]
设置指引的时候不就让你设客户端类型了）
