### ISSUE TITLE
新内测版（24.12.29）开始唤醒时无法在模拟器首页启动游戏

### ISSUE THREAD

**Issue by 68star89** [MaaAssistantArknights/MaaAssistantArknights#11448]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

开始唤醒时无法在模拟器（mumu）首页启动游戏，可稳定复现
手动点开游戏后，MAA可以正常执行后续唤醒流程
昨日之前均可以直接在mumu首页自动拉起游戏进行唤醒

### Version

UI Version: v5.11.1-alpha.1.d012.ga0047a6d4
Core Version: v5.11.1-alpha.1.d012.ga0047a6d4
Build Time: 2024/12/29 06:08:09

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/18268260/gui.log)
[asst.log](https://github.com/user-attachments/files/18268261/asst.log)
[asst.bak.log](https://github.com/user-attachments/files/18268262/asst.bak.log)
[gui.json](https://github.com/user-attachments/files/18268265/gui.json)

### 配置信息

Windows11 23H2
MUMU12 V4.1.6（3488） 
截图增强已开启，GPU加速推理已开启，RTX4060 laptop

**Comment by ABA2396** [comment]
开始唤醒里的客户端类型选了没

**Comment by 68star89** [comment]
> 开始唤醒里的客户端类型选了没

草……好像是内测更新把这个选项还原成不选择了？刚刚改回来就正常了

**Comment by ABA2396** [comment]
找到问题了 ~~其实 d1e6ca611a764e53c2ffe9623c9abc884e4c20f3 已经修了~~
