### ISSUE TITLE
自动战斗能支持只自动开技能

### ISSUE THREAD

**Issue by qianxu2001** [MaaAssistantArknights/MaaAssistantArknights#1144]
例如在凹剿灭的时候，有时先锋只带了一个桃金娘，因为剿灭前中段基本不需要操作，这时候只需要回费，但是又懒得点（
期望的功能使用情景是：玩家已经在剿灭中部署好了所有干员，此时在 maa 中开启`自动开技能`功能，就会一直识别游戏屏幕，然后自动使用技能，然后用户点击停止后就停下

**Comment by YipKei** [comment]
[`"skill_usage": 1`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E6%88%98%E6%96%97%E6%B5%81%E7%A8%8B%E5%8D%8F%E8%AE%AE.md) 
这是已经支持的功能，提问前请先阅读文档

**Comment by qianxu2001** [comment]
> [`"skill_usage": 1`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E6%88%98%E6%96%97%E6%B5%81%E7%A8%8B%E5%8D%8F%E8%AE%AE.md) 
> 这是已经支持的功能，提问前请先阅读文档

用法不同啊，目前是全自动战斗，还得开局识别干员什么的，我想要的是半自动，只需要在战斗中帮我开技能，你看清楚我上面说的使用场景
