### ISSUE TITLE
linux包glibc依赖版本过高

### ISSUE THREAD

**Issue by LLreader** [MaaAssistantArknights/MaaAssistantArknights#11445]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

操作系统: Debian bookworm aarch64

当前Debian系统稳定版的glibc版本为2.36
```
➜  ~ ldd --version
ldd (Debian GLIBC 2.36-9+rpt2+deb12u9) 2.36
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
在最近一次更新后，使用maa-cli时候出现如下报错，需求glibc版本为2.38
`1: /lib/aarch64-linux-gnu/libc.so.6: version 'GLIBC_2.38' not found (required by /home/spark/.local/share/maa/lib/libMaaCore.so)`

能否考虑降低glibc依赖版本为2.36？

### Version

MAA版本:v5.11.0

### 日志和配置文件

无

### 配置信息

Android 实体设备

**Comment by qiopgh** [comment]
ubuntu22.04lts只支持glibc2.35,我暂时用docker跑了个ubuntu24.10来运行

**Comment by Manicsteiner** [comment]
目前 github ci 的 ubuntu-latest 已经改成了 24.04LTS ( https://github.com/actions/runner-images/issues/10636 )，MAA的ci build会直接用 ubuntu-latest 版本，估计也被跟着改了。近期的C++改动只有multi craft ( https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/01e4b2470f102b3dfc5afe76882fa15970187f3a )，看起来应该也没有C++新特性，不太清楚是什么造成的。

**Comment by wangl-cc** [comment]
应该就是 GitHub Action 更新导致的，把 ubuntu-latest 改成  ubuntu-22.04 应该就可以解决这个问题。

**Comment by wangl-cc** [comment]
你可以试试这个包吗，https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/12529461989/artifacts/2368271138，这里面的 MaaCore 和 CLI 都是通过 Ubuntu 22.04 的 Runner 编译的。

**Comment by Manicsteiner** [comment]
![图片](https://github.com/user-attachments/assets/7f666ce0-6174-4478-bee0-62ca6e8fe6f9)
大概是可以了吧（昨天晚上我自己改的ci跑了9个小时都没有给分配2204的runner image）

**Comment by LLreader** [comment]
> 你可以试试这个包吗，https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/12529461989/artifacts/2368271138, 这里面的 MaaCore 和 CLI 都是通过 Ubuntu 22.04 的 Runner 编译的。

我试了，可以了，非常感谢🥰
