### ISSUE TITLE
关于分辨率识别，提高程序通用性的一些代码

### ISSUE THREAD

**Issue by Celin-C** [MaaAssistantArknights/MaaAssistantArknights#1145]
我曾尝试使用无线调试对手机进行操作，使用前用WM命令修改了手机分辨率为720x1280 320PPI，但是MAA依然报分辨率不正确。本人曾写过一个刷图小程序，可以在以上工况正确识别分辨率，基本逻辑为：截图→识别截图尺寸→获取分辨率。此段代码如下（从截屏获取信息可以保证只要能通过ADB进行截屏和触摸操作就可以使用该程序）：

# 得到当前分辨率（Python）
def getRp():
    filename = 'screenshot.png'
    try:
        global hx
        global hy
        global True_image_size
        img = Image.open(filename)
        True_image_size = img.size
        maxSize = max(True_image_size)
        minSize = min(True_image_size)
        hx = maxSize//2
        hy = minSize//2
        return hx, hy, True_image_size
    except:
        print('ADB连接失败,请打开模拟器后重试')
        sys.exit(0)

**Comment by MistEO** [comment]
这个问题已经修复了，该用了新的获取分辨率的命令。还没发版

**Comment by Celin-C** [comment]
> 这个问题已经修复了，改用了新的获取分辨率的命令。还没发版

好的，感谢大佬
