### ISSUE TITLE
提高无人机的利用效率

### ISSUE THREAD

**Issue by xfrqh** [MaaAssistantArknights/MaaAssistantArknights#1148]
目前，MAA在利用无人机加速贸易站时，会选择最大（数量），直接加速完一个订单

如果少用一架无人机，剩余时间将小于一架无人机的加速时间。可见，最后一架无人机的利用效率较低

**建议：MAA点完”最大”后，点一次”减号“。确认。然后等待订单完成。**

**Comment by MistEO** [comment]
用脚本换基建真的还在乎无人机这点效率么（

**Comment by Shawnsdaddy** [comment]
什么葛朗台

**Comment by KyonCN** [comment]
那点效率提升还不如多抽一两个高级打工仔

**Comment by a504558403** [comment]
我自己换都懒得弄这个 一架根本没用
