### ISSUE TITLE
自动战斗-自动编队 偶现点开快速编队列表后，任务出错

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#1149]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9092421/asst.log)

![image](https://user-images.githubusercontent.com/18511905/178480923-744eaf2f-0873-407c-8cf7-9e09be916a79.png)

**Comment by prcuzz** [comment]
我也遇到了这个问题，如果有玩家能看到我这条留言的话，可以先凑合用：
**只需要清空一下编队即可，**
当前编队和所需编队完全一致的时候，会报这个错误。
也希望这个复现条件能帮助开发者大佬们快速定位问题。
