### ISSUE TITLE
肉鸽模式中被歼灭数图标挡住的干员开不出技能

### ISSUE THREAD

**Issue by Morturi** [MaaAssistantArknights/MaaAssistantArknights#1152]
夜神模拟器，推测是黄色方块被挡住了

**Comment by Morturi** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9098349/asst.log)

**Comment by MistEO** [comment]
有图吗，看看啥样的。

不过本来就是基于图像识别，图像被挡住了 我觉得大概率没啥办法
