### ISSUE TITLE
求macos打包版本

### ISSUE THREAD

**Issue by BoredTape** [MaaAssistantArknights/MaaAssistantArknights#1154]
rt

**Comment by BoredTape** [comment]
我有mac，但是就是单纯懒，没编译

**Comment by horror-proton** [comment]
#2306 在做了

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.6.5-beta.1 开始已经有 macOS 版本了
