### ISSUE TITLE
长时间挂机刷肉鸽软件会崩溃，大约四五个小时？应当是稳定有问题，昨天和今天都遇到了，最简单的办法就是挂着然后去睡觉，一觉醒来win提示软件崩溃

### ISSUE THREAD

**Issue by KiligLin** [MaaAssistantArknights/MaaAssistantArknights#1158]
基本上挂着一觉醒来就会发现软件崩溃了，

使用的是夜神模拟器，忘记截图了，今晚我再试试，崩溃的话会再截图

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9101895/asst.log)

**Comment by MistEO** [comment]
日志里只有个 `2022-07-13 20:07:06.862` 正常退出软件的记录，可能是你后来又使用，之前的日志被刷新掉了。

下次再遇到在发个看看，最好给游戏也截个图（需要用模拟器自带的截图工具截的原图）

**Comment by KiligLin** [comment]
我又试了一下，.6版本应该不会再这样了，应该没问题了

**Comment by KiligLin** [comment]
![屏幕截图 2022-07-16 110142](https://user-images.githubusercontent.com/97935169/179339177-97a05386-870d-43f0-8ba0-0b2bab54624f.png)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9125147/asst.zip)
是我天真了，因为上次跑了一夜都没事我以为.6版本没这个问题了
不过不太一样，.5版本应用界面是直接没掉的，这次还有，可能是有点区别？

**Comment by KiligLin** [comment]
哦对，模拟器好像没有什么反应？就是正常的不操作导致失败的界面

**Comment by zzyyyl** [comment]
函数 `asst::RoguelikeBattleTaskPlugin::calc_best_direction_and_score` 炸了

我猜应该是 `.at()` 抛了个异常？其它地方看着都不像是会炸的样子
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/v4.0.7-beta.1/src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp#L649

**Comment by horror-proton** [comment]
我也是这么想的, 但在算 *艾丽妮* 的时候这个函数没炸, 而算到 *预备干员-后勤* 第一个位置就炸了. 而看上去这个 `at` 的参数只取决于地图, 看来问题并不在这里? 

```
778987   │ [2022-07-16 09:19:04.077][TRC][Px1b44][Tx50b0] OcrPack::recognize | raw :  艾丽妮 : [ 0, 0, 0, 0 ], score: 0.974315,
778988   │ [2022-07-16 09:19:04.078][TRC][Px1b44][Tx50b0] OcrPack::recognize | proc :  艾丽妮 : [ 17, 185, 67, 23 ], score: 0.974315,
778989   │ [2022-07-16 09:19:04.078][TRC][Px1b44][Tx50b0] asst::OcrPack::recognize | leave, 26 ms
778990   │ [2022-07-16 09:19:04.078][TRC][Px1b44][Tx50b0] asst::OcrImageAnalyzer::analyze | leave, 26 ms
778991   │ [2022-07-16 09:19:04.078][TRC][Px1b44][Tx50b0] asst::RoguelikeBattleTaskPlugin::calc_best_direction_and_score | enter
778992   │ [2022-07-16 09:19:04.078][TRC][Px1b44][Tx50b0] asst::RoguelikeBattleTaskPlugin::calc_best_direction_and_score | leave, 0 ms
778993   │ [2022-07-16 09:19:04.078][TRC][Px1b44][Tx50b0] asst::RoguelikeBattleTaskPlugin::calc_best_direction_and_score | enter
778994   │ [2022-07-16 09:19:04.078][TRC][Px1b44][Tx50b0] asst::RoguelikeBattleTaskPlugin::calc_best_direction_and_score | leave, 0 ms
778995   │ [2022-07-16 09:19:04.078][TRC][Px1b44][Tx50b0] asst::RoguelikeBattleTaskPlugin::calc_best_direction_and_score | enter
778996   │ [2022-07-16 09:19:04.078][TRC][Px1b44][Tx50b0] asst::RoguelikeBattleTaskPlugin::calc_best_direction_and_score | leave, 0 ms
778997   │ [2022-07-16 09:19:04.078][TRC][Px1b44][Tx50b0] asst::RoguelikeBattleTaskPlugin::calc_best_direction_and_score | enter
778998   │ [2022-07-16 09:19:04.078][TRC][Px1b44][Tx50b0] asst::RoguelikeBattleTaskPlugin::calc_best_direction_and_score | leave, 0 ms
```

**Comment by horror-proton** [comment]
方便的话可以尝试打开 Windows 的可靠性历史记录 (可以在开始里面搜到), 找到这一条然后贴一下报告?

**Comment by horror-proton** [comment]
> 

等下, 这个 `home_point` 和 `home_rect` 好像根本没有用到过, 虽然感觉不是这里的问题, 不过还是把它去掉比较好 ?

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/7f4e5223a486cb124b3905c439e7c3f3f2c2d8b1/src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp#L649-L650

**Comment by KiligLin** [comment]
应该没问题了吧

**Comment by zzyyyl** [comment]
（还没发版呢，只是 merge 到 dev 了，不过 close 了就 close 吧）
