### ISSUE TITLE
稀音红云组会重置时间

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaAssistantArknights#1159]
虽然我记得好像说修了, 但我这边还是会重置时间。

可能是因为我这边没有小刻, 是稀音红云黑角?
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9102015/asst.-.Copy.log)

**Comment by one-pyy** [comment]
啊, 就是会调换位置, 然后效率会被重置()

**Comment by MistEO** [comment]
那这个还没改呢（

**Comment by one-pyy** [comment]
好耶

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
