### ISSUE TITLE
无限肉鸽中，在商店里买了精二券但没有其职业的干员的情况下，会直接退出本轮肉鸽重新开一把

### ISSUE THREAD

**Issue by genicse** [MaaAssistantArknights/MaaAssistantArknights#1160]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9102716/asst.zip)

mumu模拟器

**Comment by MistEO** [comment]
```log
asst::Assistant::append_task Roguelike {"mode":1}
```

你自己选的 `刷源石锭，第一层商店后自动退出`，在 MAA 的肉鸽设置里
