### ISSUE TITLE
公开招募左下角格子招募失败

### ISSUE THREAD

**Issue by alon74** [MaaAssistantArknights/MaaAssistantArknights#1161]
执行自动公开招募时有概率仅招募3次,左下角招募栏留空并未进行招募
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9103050/asst.log)

**Comment by MistEO** [comment]
请进入软件设置，公招设置，调整默认公招次数

**Comment by alon74** [comment]
一直是默认设置4，没有改动过

**Comment by MistEO** [comment]
> 一直是默认设置4，没有改动过

默认是 3 啊

**Comment by alon74** [comment]
我这里一直默认是4,没有改动过
但仍然存在只招募3次并无视左下角槽位的问题

**Comment by zzyyyl** [comment]
> 我这里一直默认是4,没有改动过 但仍然存在只招募3次并无视左下角槽位的问题

以前默认一直是3的。这次更新改成了4，你现在是不是更新过了

**Comment by zzyyyl** [comment]
忽略左下角是因为排序问题，总之是3的时候就会忽略一个，有时候是左下有时候是右下

**Comment by alon74** [comment]
最近没有过更新，问题是即使是4了也存在忽略一格的问题

**Comment by zzyyyl** [comment]
`[2022-07-13 12:01:48.849][TRC][Px5ec8][Tx2970] OcrPack::recognize | raw :  术师干员 : [ 30, 84, 84, 23 ], score: 0.987303, 近战位 : [ 207, 83, 64, 23 ], score: 0.941887, 辅助干员 : [ 365, 14, 82, 19 ], score: 0.971930, 击于员 : [ 197, 13, 85, 22 ], score: 0.713624, 近卫干员 : [ 28, 11, 86, 25 ], score: 0.991751,  `
日志显示，你的 `狙击干员` 没识别出来（识别成了 `击干员`）
MAA在识别不出来的时候不会自动刷新（避免刷新掉没识别出来的稀有 Tags），然后你应该也不会自己去刷新，所以就一直寄了

@MistEO 也许可以考虑给 `击干员` 直接替换成 `狙击干员` ~（无处不在的 string_replace！~
