### ISSUE TITLE
关于肉鸽选干员的问题

### ISSUE THREAD

**Issue by QYream** [MaaAssistantArknights/MaaAssistantArknights#1162]
肉鸽开局默认选的是蓝蒂、预备干员（辅助、医疗）。首先蓝蒂很难打下去，基本怪多一点就寄了。其次本身的三星应该比预备干员强，一般优先会选择自己的，但也有可能有些人没练，不过每个人都是从新手过来的，多少会练吧。总之，如果能让玩家多一个选择，首选哪个六星就好了。（蓝蒂是真的顶不住）

**Comment by QYream** [comment]
练度不是很高但比如小羊棘刺这种应该更好一些吧。刚刚GitHub网页连接重置了以为没传上去。这么晚了大佬辛苦了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月13日(星期三) 晚上10:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 关于肉鸽选干员的问题 (Issue #1162)





 
是练度识别+优先级的，不是默认选择。看看你练了哪些？

**Comment by QYream** [comment]
但小羊或令开局应该也不错吧，棘刺倒是一般后面拿

**Comment by MistEO** [comment]
通常意义上，近卫开局是最稳的。除非你近卫都没练这种
