### ISSUE TITLE
代码运行异常

### ISSUE THREAD

**Issue by WarmLight7** [MaaAssistantArknights/MaaAssistantArknights#1163]
pull下来项目之后在vs2019里面跑但是没成功出现如下报错
![image](https://user-images.githubusercontent.com/59765294/178779699-bc3ed8b2-f249-412f-8b6a-24e915a336c3.png)

![image](https://user-images.githubusercontent.com/59765294/178779937-0ea11c69-80db-4fd4-8464-ba02271ade8c.png)
感觉代码运行成功了但是可能缺少测试组件？
要修改什么才能正确运行代码？
要额外配置什么东西吗？

**Comment by MistEO** [comment]
设一下启动项目
