### ISSUE TITLE
之后是否会添加自动保全派驻的功能？

### ISSUE THREAD

**Issue by litchiar** [MaaAssistantArknights/MaaAssistantArknights#1166]

**Comment by drunkenQCat** [comment]
群里说过的，这个现在不是首要的开发任务。可能得等有识之士来pr了。

**Comment by lxq-9527** [comment]
保全先用素王豆腐的明日再肝吧

**Comment by zzyyyl** [comment]
[To Do](https://github.com/MaaAssistantArknights/MaaAssistantArknights/projects/1#card-84177292)

**Comment by MistEO** [comment]
WIP https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/3203
