### ISSUE TITLE
任务奖励识别错误

### ISSUE THREAD

**Issue by drunkenQCat** [MaaAssistantArknights/MaaAssistantArknights#1168]
任务奖励领取任务出现错误，奖励未领取。log如下：
[asst_award.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9108216/asst_award.log)

**Comment by MistEO** [comment]
请附上完整的日志，提供尽可能多的信息，而不是从中间截取一段然后什么别的信息都没有
