### ISSUE TITLE
建议在控制中枢检测到彩虹小队就跳过操作

### ISSUE THREAD

**Issue by Yue-plus** [MaaAssistantArknights/MaaAssistantArknights#1169]
彩虹小队不用换班的：

![image](https://user-images.githubusercontent.com/33195150/178902288-36190b5f-1a3d-47a8-9ee3-d77164306e1c.png)

**Comment by ABA2396** [comment]
你可以在设置里取消勾选控制中枢）

**Comment by Yue-plus** [comment]
> 你可以在设置里取消勾选控制中枢）

az，抱歉，打扰了。

**Comment by MistEO** [comment]
彩虹小队是低效组合，只是为了图省事。都用脚本了为啥不来点高效组合呢（

**Comment by Yue-plus** [comment]
> 彩虹小队是低效组合，只是为了图省事。都用脚本了为啥不来点高效组合呢（~虽然也没高到哪里去~

😂就是看它把我彩虹小队撤下来，然后阿米娅、诗怀雅一起放上去了才来提的建议

**Comment by MistEO** [comment]
> > 彩虹小队是低效组合，只是为了图省事。都用脚本了为啥不来点高效组合呢（~虽然也没高到哪里去~
> 
> 😂就是看它把我彩虹小队撤下来，然后阿米娅、诗怀雅一起放上去了才来提的建议

那这个问题在 v4.0.7-beta.1 版本已经修复了

**Comment by ABA2396** [comment]
> > 彩虹小队是低效组合，只是为了图省事。都用脚本了为啥不来点高效组合呢（~虽然也没高到哪里去~
> 
> 😂就是看它把我彩虹小队撤下来，然后阿米娅、诗怀雅一起放上去了才来提的建议

现在不会一起了

**Comment by Yue-plus** [comment]
> > > 彩虹小队是低效组合，只是为了图省事。都用脚本了为啥不来点高效组合呢（~虽然也没高到哪里去~
> > 
> > 
> > 😂就是看它把我彩虹小队撤下来，然后阿米娅、诗怀雅一起放上去了才来提的建议
> 
> 那这个问题在 v4.0.7-beta.1 版本已经修复了

好的我去升级一下，谢谢了。
