### ISSUE TITLE
掉落識別錯誤

### ISSUE THREAD

**Issue by Sean1781031** [MaaAssistantArknights/MaaAssistantArknights#1172]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9111601/asst.log)

不確定是因為繁中版的掉落物不支援辨識或是其他原因
使用的是BlueStacks5 國際版

刷了30多次一直都是掉落錯誤

**Comment by Sean1781031** [comment]
![image](https://user-images.githubusercontent.com/68652201/178979575-62003135-430b-41de-afab-b41b602b324c.png)

**Comment by Sean1781031** [comment]
那麼有辦法手動關閉嗎?

**Comment by MistEO** [comment]
没有_(:з」∠)_
