### ISSUE TITLE
肉鸽 驯兽小屋 42奶奶摆放位置错误

### ISSUE THREAD

**Issue by saobilin** [MaaAssistantArknights/MaaAssistantArknights#1173]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9113271/asst.log)
肉鸽 普通战斗 驯兽小屋 42奶奶摆放方向错误（自我感觉有问题）
![image](https://user-images.githubusercontent.com/50769148/179023101-90000320-3536-47da-9aea-3734cb460469.png)
![image](https://user-images.githubusercontent.com/50769148/179023125-b7e0968a-aab8-4912-b891-95ec2706f49c.png)

**Comment by saobilin** [comment]
首演 42位置也是反向摆了 
![image](https://user-images.githubusercontent.com/50769148/179153113-e013b598-98cf-4f7d-ba99-19babd4f176e.png)
![image](https://user-images.githubusercontent.com/50769148/179153118-8ceb88bc-d2ad-4488-b950-4405a9b994f6.png)

**Comment by ntgmc** [comment]
感谢反馈。无法修复该bug
