### ISSUE TITLE
干员选择bug

### ISSUE THREAD

**Issue by WarmLight7** [MaaAssistantArknights/MaaAssistantArknights#1174]
报一个也不算bug的bug吧，在自定义选人的json的时候发现即使我注释掉了水蒂但是他还是会选取，应该是因为近卫里面有skd，水蒂里面包含skd，所以直接就pick了，这个我也不知道能不能优化QAQ，也不知道需不需要优化（个人直接把skd注掉了）

**Comment by ABA2396** [comment]
有点没看懂）是哪里的选人？maa好像不管你有么有注释的来着，直接删了试试

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/179035001-c1f53442-4e7f-4a30-8f8f-5934241209d4.png)
