### ISSUE TITLE
[bug]无法识别游戏内设置界面

### ISSUE THREAD

**Issue by OTLFrostA** [MaaAssistantArknights/MaaAssistantArknights#1177]
蓝叠模拟器，如图
1，因为不明原因挂机一定时间就会自动点开游戏内设置界面。猜测是因为MAA点了多次返回
2，只要游戏进入设置菜单之后，所有任务全都会卡死或者失败

一个比较简单的解决方案是建议把点选返回的坐标右移一点，这样就算多次点选也只是会进入公告页面不会卡死

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9115868/asst.log)

![image](https://user-images.githubusercontent.com/5652631/179096381-324fd9f2-b359-4acd-8ecb-58c3d132fb02.png)

**Comment by zzyyyl** [comment]
"返回的坐标右移" 应该不太可能，现在是图像识别后随机点 ~~（运气好就点到公告了~~
这个问题一般是电脑太卡了，adb 截图耗费时间过多引起的，好像以前也有人提过

**Comment by zzyyyl** [comment]
也许可以卡住的时候 adb 发送键盘 ESC 直接返回 @MistEO

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
