### ISSUE TITLE
集成战略卡死在进入楼层的页面

### ISSUE THREAD

**Issue by YipKei** [MaaAssistantArknights/MaaAssistantArknights#1178]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9116781/asst.zip)
![屏幕截图 2022-07-15 084457](https://user-images.githubusercontent.com/53115298/179124414-470766ad-d07d-4911-95b1-f88a6a198935.png)

具体卡死的页面一下子脑抽忘记截图了，我手动点了一下画面，MAA就开始退出重开下一把了。

蓝叠 5.5.101.1002 P64

这一把寒渊惜别肯定是过了的，因为刚好有藏品解锁，所以应该是卡在了进入第四层的画面，其他的希望log有记录吧。

**Comment by MistEO** [comment]
卡在哪个画面了啊，描述下？

**Comment by YipKei** [comment]
> 卡在哪个画面了啊，描述下？或者找个例子也行

就是正中间有个时钟的那个进入下一层的画面，就遇到一次

**Comment by MistEO** [comment]
> 

时钟那个画面不用点击啊，过一会就到下一层了，是不是游戏卡住了

**Comment by MistEO** [comment]
这个问题在水月那边修了，傀影这边没管。

问题出现在刚刚离开行商/不期而遇，进入下一层时，4 点更新了。这时候再次进入肉鸽“继续探索”，就会停在楼层加载的界面，必须要手动点一下
