### ISSUE TITLE
公招时MAA误触基建，然后卡死报错

### ISSUE THREAD

**Issue by YipKei** [MaaAssistantArknights/MaaAssistantArknights#1180]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9116918/asst.log)

前半部分在 #1178 

卡死在基建退出提示（忘记关了）

我不清楚是怎么点错到基建里去的，然后MAA应该是试图退出，但被卡在那了。

玛丽既然说做了基建退出提示的判断，那么应该正常的退出基建是没问题的。

我怀疑有可能是不是所有返回主菜单的尝试都做了这种异常判断，但是这种异常判断可能会增加很大的额外开销，不知道怎么解决。

可以考虑在非特定页面强制退出出现弹窗的时候，无视具体内容，取样两个选项位置的点的颜色然后根据颜色选择？不知道这个对话框的尺寸是不是固定的，如果非固定那就寄了。

**Comment by zzyyyl** [comment]
开销不大，就是有的 Return 没加Confirm。现在 task.json 的 Return 机制太复杂了，有必要单独拿出来整一个 `ReturnTaskPlugin` 了

**Comment by MistEO** [comment]
> > 我怀疑有可能是不是所有返回主菜单的尝试都做了这种异常判断，但是这种异常判断可能会增加很大的额外开销，不知道怎么解决。
> 
> 开销不大，确实就是有的 Return 没加 Confirm。现在 task.json 的 Return 机制太复杂了，我记得之前说要重写返回机制来着
> 
> 所以什么时候重写 @MistEO

哪个没加啊，我以为都加了来着）

**Comment by MistEO** [comment]
重写太麻烦了 QAQ

**Comment by YipKei** [comment]
> 重写太麻烦了 QAQ

确实，看着现在这个 task 写的互相唤起逻辑就头大

重写之前很有必要有人整理一张逻辑图出来才能理顺关系

**Comment by zzyyyl** [comment]
> > > 我怀疑有可能是不是所有返回主菜单的尝试都做了这种异常判断，但是这种异常判断可能会增加很大的额外开销，不知道怎么解决。
> > 
> > 
> > 开销不大，确实就是有的 Return 没加 Confirm。现在 task.json 的 Return 机制太复杂了，我记得之前说要重写返回机制来着
> > 所以什么时候重写 @MistEO
> 
> 哪个没加啊，我以为都加了来着）

`ReturnToActivities`。

**Comment by MistEO** [comment]
> > > > 我怀疑有可能是不是所有返回主菜单的尝试都做了这种异常判断，但是这种异常判断可能会增加很大的额外开销，不知道怎么解决。
> > > 
> > > 
> > > 开销不大，确实就是有的 Return 没加 Confirm。现在 task.json 的 Return 机制太复杂了，我记得之前说要重写返回机制来着
> > > 所以什么时候重写 @MistEO
> > 
> > 
> > 哪个没加啊，我以为都加了来着）
> 
> `ReturnToActivities`。

这个没用上（

**Comment by MistEO** [comment]
v4.2.2-beta.1 修了一个基建滑动失效的问题，可能是这个原因，不过现在也没啥头绪总之先关了，之后再出现再来个日志看看（
