### ISSUE TITLE
MUMU无法连接使用

### ISSUE THREAD

**Issue by Reminiserces** [MaaAssistantArknights/MaaAssistantArknights#1181]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9117041/asst.log)
![image](https://user-images.githubusercontent.com/87899500/179131299-8b358f50-6bdb-4f6b-8ff9-dff3194294f1.png)

**Comment by zzyyyl** [comment]
看你前面的日志是蓝叠的，蓝叠也有这个问题吗？

**Comment by Reminiserces** [comment]
蓝叠5没有&nbsp; &nbsp;原因有无可能是路径存在中文？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月15日(星期五) 上午10:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] MUMU无法连接使用 (Issue #1181)





 
看你前面的日志是蓝叠的，蓝叠也有这个问题吗？

**Comment by zzyyyl** [comment]
你 MUMU 的分辨率不对啊，不是 `1980x1080` ，应该是 `1920x1080`吧（

**Comment by Reminiserces** [comment]
我去更改一下试试

**Comment by zzyyyl** [comment]
> 我去更改一下试试

改完测试了记得来反馈一下啊（
