### ISSUE TITLE
肉鸽进入时点了选择难度 导致了死循环

### ISSUE THREAD

**Issue by Hengkongchushi83** [MaaAssistantArknights/MaaAssistantArknights#1185]
模拟器 蓝叠国际版
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9120083/asst.log)
附视频
https://user-images.githubusercontent.com/81248614/179207595-9c2a5885-7523-454f-bd21-95dd956d3fa8.mp4

**Comment by ABA2396** [comment]
[v4.0.7-beta.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.0.7-beta.1) fixed
