### ISSUE TITLE
未知原因公招识别错误直接跳过公招了

### ISSUE THREAD

**Issue by desktop4025** [MaaAssistantArknights/MaaAssistantArknights#1186]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9121575/asst.zip)

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/ef0ac7f32038bcc7917c328e3b6f24c741dc0705 fixed
