### ISSUE TITLE
希望能够像自动战斗那样在一键长草里面加一个自选json的功能

### ISSUE THREAD

**Issue by ylsy2002** [MaaAssistantArknights/MaaAssistantArknights#1188]
想把maa应用到阴阳师上去
以前用autojs写过大部分功能，思路有了，参照~~小刻都能看懂的~~任务流程协议写出json倒也不是啥难事（已经写好了，图片也截好了）
~~然后我发现我改不动源码~~
所以能不能实现自己选择json的功能呢？
~~C艹什么的才不是学不会呢~~
~~不行的话当心我跪下来求你~~

**Comment by zzyyyl** [comment]
可以去看看 [`resource/tasks.json`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/v4.0.6/resource/tasks.json)，~~应该还是很好理解的~~

**Comment by ntgmc** [comment]
感谢反馈。
Thank you for your feedback.
