### ISSUE TITLE
win10虚拟机下软件无法启动（直接闪退），未生成日志或类似的错误报告

### ISSUE THREAD

**Issue by Well2333** [MaaAssistantArknights/MaaAssistantArknights#1189]
如题，软件无法正常启动，已按照docs中的常见问题进行排查（包括替换PaddleOCR为NoAVX版本）仍不成功。

我尝试过 [Windows2019的某个魔改专业版](https://www.bilibili.com/video/BV1j3411Y75z) 及 [Windows Server 2019 datacenter版](https://next.itellyou.cn/Original/Index#cbp=Product?ID=303127af-cb4f-ea11-bd31-b025aa28351d)，二者均出现了类似的问题。

宿主机为PVE，使用的配置如下：
AMD Ryzen 5 PRO 4650G with Radeon Graphics
A320M-HDV R4.0

PVE的配置如下：
内核版本 Linux 5.15.39-1-pve #1 SMP PVE 5.15.39-1 (Wed, 22 Jun 2022 17:22:00 +0200)
PVE管理器版本 pve-manager/7.2-7/d0dd0e85

**Comment by Well2333** [comment]
![00](https://user-images.githubusercontent.com/40534114/179270346-3795d7dc-28c5-4b21-97ce-a1513b7806c2.jpg)
![00](https://user-images.githubusercontent.com/40534114/179270346-3795d7dc-28c5-4b21-97ce-a1513b7806c2.jpg)
![01](https://user-images.githubusercontent.com/40534114/179270355-0c1ab0e3-9c6a-43e4-857d-fa08247162b1.jpg)
![01](https://user-images.githubusercontent.com/40534114/179270355-0c1ab0e3-9c6a-43e4-857d-fa08247162b1.jpg)
![02](https://user-images.githubusercontent.com/40534114/179270357-0a2108f4-5b0c-4a5b-bcac-7a1d99b12522.jpg)
![02](https://user-images.githubusercontent.com/40534114/179270357-0a2108f4-5b0c-4a5b-bcac-7a1d99b12522.jpg)
![03](https://user-images.githubusercontent.com/40534114/179270360-423a7de1-984d-48a2-bd10-41eb931d12db.jpg)
![03](https://user-images.githubusercontent.com/40534114/179270360-423a7de1-984d-48a2-bd10-41eb931d12db.jpg)
![04](https://user-images.githubusercontent.com/40534114/179270365-6eec9eea-3890-4e30-b0cf-25d02c8f829d.jpg)
![04](https://user-images.githubusercontent.com/40534114/179270365-6eec9eea-3890-4e30-b0cf-25d02c8f829d.jpg)
![05](https://user-images.githubusercontent.com/40534114/179270369-f4f67954-8c5a-478e-abad-c2d76f1713fe.jpg)
![05](https://user-images.githubusercontent.com/40534114/179270369-f4f67954-8c5a-478e-abad-c2d76f1713fe.jpg)

**Comment by Well2333** [comment]
![01](https://user-images.githubusercontent.com/40534114/179270615-2ef648db-6860-4714-aae2-cea54118b6e1.jpg)
![02](https://user-images.githubusercontent.com/40534114/179270619-62a4f5a7-7483-4fab-8036-8cd866dc22ac.jpg)
![03](https://user-images.githubusercontent.com/40534114/179270621-a9bd3620-6df6-422d-b1c1-5e2f4cde6f32.jpg)
![04](https://user-images.githubusercontent.com/40534114/179270623-80c03165-8547-4d20-8ff6-7401054c8cb6.jpg)
![05](https://user-images.githubusercontent.com/40534114/179270630-1b924e65-04ef-4120-9b17-ad145de1de49.jpg)

**Comment by Well2333** [comment]
此版本我在我的物理机上是可以正常使用的，因此可以排除是文件损坏导致的。

**Comment by zzyyyl** [comment]
图片没传上来，不过问题解决了就好（

**Comment by Well2333** [comment]
> 图片没传上来，不过问题解决了就好（

个人建议，可以在常见问题中新增一条针对Server、LTSC或其他精简版虚拟机的环境配置建议，因为仅靠目前常见问题提供的方法无法解决。
实际上，造成这个问题的原因还是由于环境缺乏所致，我使用的两个版本均不带Windows应用商店，因此并没有预装.Net及C++运行环境，在通过[vistaul cpp build tool](https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/)的c++及.net环境安装后可正常运行。

**Comment by zzyyyl** [comment]
@MistEO 喊你加文档了

**Comment by zzyyyl** [comment]
> > 图片没传上来，不过问题解决了就好（
> 
> 个人建议，可以在常见问题中新增一条针对Server、LTSC或其他精简版虚拟机的环境配置建议，因为仅靠目前常见问题提供的方法无法解决。 实际上，造成这个问题的原因还是由于环境缺乏所致，我使用的两个版本均不带Windows应用商店，因此并没有预装.Net及C++运行环境，在通过[vistaul cpp build tool](https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/)的c++及.net环境安装后可正常运行。

有能力的话来个 PR 呗

**Comment by Well2333** [comment]
OK

**Comment by horror-proton** [comment]
~~话说这是在 PVE 里面开了个 Windows 虚拟机跑 MAA, 去控制一个安卓虚拟机里的明日方舟? 听起来有点奇怪~~

**Comment by Well2333** [comment]
> ~话说这是在 PVE 里面开了个 Windows 虚拟机跑 MAA, 去控制一个安卓虚拟机里的明日方舟? 听起来有点奇怪~


确实奇怪，挺逆天的

**Comment by Well2333** [comment]
话说问题已经解决了，文档也更新了，我就先close了
