### ISSUE TITLE
没有4星以上的tag组合，用公招票刷新tag

### ISSUE THREAD

**Issue by HeroTch** [MaaAssistantArknights/MaaAssistantArknights#1190]
希望公招没有4星tag时，用1小时停止招募的方法用公招票刷新tag组合

**Comment by zzyyyl** [comment]
？？为啥要浪费招聘许可啊（

**Comment by zzyyyl** [comment]
一般加急许可绝对比招聘许可多的吧，那样的话 `自动公招-自动使用加急许可` 大概就能满足你的需求了

**Comment by MistEO** [comment]
没有 4 星 tags 的时候拉满 9 小时，也是有小概率出 4/5 星的啊。1 小时就彻底没概率了
