### ISSUE TITLE
启动闪退

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaAssistantArknights#1191]
RT
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9124523/asst.log)

**Comment by MistEO** [comment]
多来点信息啊 xd

**Comment by zzyyyl** [comment]
你这 DEBUG VERSION 是哪个 commit 的啊（

**Comment by Shawnsdaddy** [comment]
> 多来点信息啊 xd

闪退完还有log嘛，它就这么多啊

**Comment by horror-proton** [comment]
Windows 的可靠性历史记录里面有相关的报告吗

**Comment by Shawnsdaddy** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9133384/asst.log)
今天又闪退了一次

**Comment by zzyyyl** [comment]
我昨天也闪退了一次，不过是 DEBUG 版本，但是第二次打开又正常运行了，日志被我删了（我以为是我的问题

**Comment by zzyyyl** [comment]
也许是 gui.json 不兼容引起的？备份一下删掉再重新打开试试
