### ISSUE TITLE
干员选定问题、4.0.6版本设置闪退

### ISSUE THREAD

**Issue by ilikecongee** [MaaAssistantArknights/MaaAssistantArknights#1195]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9125100/asst.zip)

使用模拟器：蓝叠国内版，分辨率：1920*1080

干员选定问题：
无限肉鸽模式，大盗当头关卡，山放在芙蓉上面一格（山朝左芙蓉朝左），脚本运行时会一直、反复选定技能处于冷却中的芙蓉，（此时二技能的山处于能释放技能状态），怀疑是图像识别范围过大，导致反复选定还不能释放技能的芙蓉。而山放芙蓉下方一格时并没有出现上诉情况。

干员放置图：
![image](https://user-images.githubusercontent.com/97867349/179338590-ab03f22d-fc61-4462-b635-47296b7c953f.png)

设置闪退：
4.0.6版本中，除了第一次版本更新后能点击设置，而后只要点击设置必闪退，更新4.0.7beta版本后恢复正常，4.0.6的上一个版本也能正常点击设置。

**Comment by MistEO** [comment]
- 设置闪退是 4.0.6 新增问题，4.0.7-beta.1 的更新日志里写了修复这条了
- 点技能这个好像也有人反馈过，还得研究下咋解决（

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
