### ISSUE TITLE
4.0.6 windows 安全中心 报毒

### ISSUE THREAD

**Issue by edward-yin** [MaaAssistantArknights/MaaAssistantArknights#1197]
windows 10 21H1 内部版本 19043.1766
反恶意软件客户端版本: 4.18.2205.7
引擎版本: 1.1.19400.3
防病毒软件版本: 1.371.241.0
反间谍软件版本: 1.371.241.0

在官网下载了 4.0.6 的压缩包后安全中心报毒，然后默认会被删除。
报错内容是：Trojan:Script/Wacatac.B!ml
附上 windows 的 ”更多信息“ 网址：
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fWacatac.B!ml&threatid=2147735503
截图如下：
![image](https://user-images.githubusercontent.com/22809582/179346446-2a79082a-2286-45c5-98f5-13027eecc366.png)

**Comment by zzyyyl** [comment]
![FCBT6DTH2~TUZXZLJLFTP_7](https://user-images.githubusercontent.com/74587068/179346546-b4c3dc91-acdd-4a5f-8338-135b04ed9fe9.jpg)

**Comment by MistEO** [comment]
什么应用行为会触发这个？有大佬了解么

目前和操作系统相关的 api 应该只调用了 socket 连接相关的，会占掉一个端口

**Comment by cglcv** [comment]
我把maa主程序（仅exe，因为整体超过限制了）扔微步云沙箱里面检查了一下，没查出病毒来
建议楼主全盘扫一下，有可能时下载时maa感染了病毒
![image](https://user-images.githubusercontent.com/35825310/179358265-81d4a633-543d-456d-9488-5e9aed1f35e8.png)

但是maa为什么要尝试读取windows defender的注册表呢
![image](https://user-images.githubusercontent.com/35825310/179358104-88856f97-ed1d-4c3c-ab0c-d64124bb4655.png)

**Comment by horror-proton** [comment]
我的 Windows Defender 也报告病毒, 非常奇怪 @cglcv

**Comment by cglcv** [comment]
> 我的 Windows Defender 也报告病毒, 非常奇怪 @cglcv

我自己主力电脑的卡巴斯基没报毒，在另一台用wd的电脑下了个4.0.6也没报啊（病毒库均已更新）

**Comment by horror-proton** [comment]
我用的 WD:
```
反恶意软件客户端版本: 4.18.2205.7
引擎版本: 1.1.19400.3
防病毒软件版本: 1.371.248.0
反间谍软件版本: 1.371.248.0
```

另外这玩意估计是人工智能 (zhang) 检测出来的, 很可能说不清楚具体是什么触发了检测

**Comment by MistEO** [comment]
> 我把maa主程序（仅exe，因为整体超过限制了）扔微步云沙箱里面检查了一下，没查出病毒来
> 建议楼主全盘扫一下，有可能时下载时maa感染了病毒
> ![image](https://user-images.githubusercontent.com/35825310/179358265-81d4a633-543d-456d-9488-5e9aed1f35e8.png)
> 
> 但是maa为什么要尝试读取windows defender的注册表呢
> ![image](https://user-images.githubusercontent.com/35825310/179358104-88856f97-ed1d-4c3c-ab0c-d64124bb4655.png)
> 
> 此外，如果真是WD报毒，应该已经大面积反馈上来了吧

没读啊，上次写的那个开机自启跟这个有关系吗

**Comment by cglcv** [comment]
> > 我把maa主程序（仅exe，因为整体超过限制了）扔微步云沙箱里面检查了一下，没查出病毒来
> > 建议楼主全盘扫一下，有可能时下载时maa感染了病毒
> > ![image](https://user-images.githubusercontent.com/35825310/179358265-81d4a633-543d-456d-9488-5e9aed1f35e8.png)
> > 但是maa为什么要尝试读取windows defender的注册表呢
> > ![image](https://user-images.githubusercontent.com/35825310/179358104-88856f97-ed1d-4c3c-ab0c-d64124bb4655.png)
> > 此外，如果真是WD报毒，应该已经大面积反馈上来了吧
> 
> 没读啊，上次写的那个开机自启跟这个有关系吗

我觉得没关系，开机自启读写注册表的位置是`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`和这个差太远
有没有可能是某个第三方包导致的？

**Comment by cglcv** [comment]
> 我用的 WD:
> 
> ```
> 反恶意软件客户端版本: 4.18.2205.7
> 引擎版本: 1.1.19400.3
> 防病毒软件版本: 1.371.248.0
> 反间谍软件版本: 1.371.248.0
> ```
> 
> 另外这玩意估计是人工智能 (zhang) 检测出来的, 很可能说不清楚具体是什么触发了检测

我WD是1.371.253.0
你报病毒的类型和楼主一样吗

**Comment by horror-proton** [comment]
> 我WD是1.371.253.0 你报病毒的类型和楼主一样吗

是一样的

**Comment by wky9710** [comment]
![image](https://user-images.githubusercontent.com/24762209/190911753-27a60253-719b-4f8b-9e56-51a6af89afce.png)
遇到类似问题，maa版本4.3.0, wd版本如下
![image](https://user-images.githubusercontent.com/24762209/190911807-bf9b5524-abc6-440c-a958-8d1e5813c133.png)
但是是用了好久之后才报毒的，之前没遇到过，也仅仅删除了.exe文件，其他文件未被删除

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
