### ISSUE TITLE
[公招识别] 考虑使用干员头像进行区分

### ISSUE THREAD

**Issue by GalvinGao** [MaaAssistantArknights/MaaAssistantArknights#1198]
（我只是传话的.jpg

<img width="831" alt="image" src="https://user-images.githubusercontent.com/12567059/179348185-4ed11d05-41e8-4362-b299-d016996628c6.png">

**Comment by MistEO** [comment]
wpf 我会做个锤子头像（

催催时雨新 ui, 好像已经有头像了

**Comment by tsctsc6** [comment]
要不搞个不同颜色，以区分不同星级

**Comment by MistEO** [comment]
开摆！
