### ISSUE TITLE
干员识别问题

### ISSUE THREAD

**Issue by nightofknife** [MaaAssistantArknights/MaaAssistantArknights#1199]
相关日志：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9125942/asst.log)

测试模拟器：mumu
测试分辨率：1280*720
测试帧率：60
MAA版本：4.0.7-beta.1
测试用关卡：OF-5

看了一下，涉及干员为：孑，傀影
具体的识别结果如下
![~6P2HWNP~BK4`_2$(UKYP57](https://user-images.githubusercontent.com/73384329/179358059-be2186d1-4181-4958-8870-19eb4e351bec.png)
![_)O5_TG7G4R_%PGMGAJF6LW](https://user-images.githubusercontent.com/73384329/179358065-90eecb8a-3657-4848-8e39-6bc628307d0d.png)

以下为代提（相关人为一群”xzr然哥”）

相关日志：
[asst (1).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9125947/asst.1.log)

测试模拟器：mumu
测试分辨率：2000*1125
测试帧率：60
MAA版本：4.0.7-beta.1
测试用关卡：傀影悖论模拟

看了一下，涉及干员为：傀影
具体的识别结果如下
![S1TL1QYZEVU)B~X5E$Q6T`7](https://user-images.githubusercontent.com/73384329/179358134-5e5f1818-ef60-48af-8b6a-7667271c2f21.png)

ps：我不会提pr。噫，哭鲁西
ps2：我记得在4.0.5版本傀影识别为愧影还是正常的（？

**Comment by ABA2396** [comment]
来了来了2）

**Comment by ABA2396** [comment]
deb5da550e8e6781245fb58d86baeec4eed9b64b fixed

**Comment by ABA2396** [comment]
deb5da550e8e6781245fb58d86baeec4eed9b64b fixed
