### ISSUE TITLE
English GUI translation

### ISSUE THREAD

**Issue by CLInewb** [MaaAssistantArknights/MaaAssistantArknights#1201]
Hello, I found this project recently, and I always wanted an Arknights helper like this!

When I tried to launch the software (latest), all of the text was in CN.
There is English documentation, but I don't see anything that shows the software's language, or navigation..

Could there be a translation of the GUI, so users from overseas could try it as well please?

Thank you very much!

**Comment by horror-proton** [comment]
**Comment as a user:**

I'm not sure if the present UI is properly written even as a monolingual project, perhaps some refactoring is necessary to make multi language support possible. 
I saw [a new UI](https://github.com/MaaAssistantArknights/MaaAsstElectronUI) under development, at least  they are planning to have multi language support (ref. [多语言支持](https://github.com/MaaAssistantArknights/MaaAsstElectronUI/projects/1#card-82054507)) ~~before it is too late, like this one~~.

**Comment by MistEO** [comment]
It's in progress now!

**Comment by MistEO** [comment]
v4.2.0-alpha.1 released
