### ISSUE TITLE
关于基建的一些设置

### ISSUE THREAD

**Issue by a504558403** [MaaAssistantArknights/MaaAssistantArknights#1202]
用了多次之后有些小建议：
1诗怀雅和阿米娅应该是轮班的 放一起没用
2森蚺、清流、温蒂的组合好像只有1.12的。一般来讲森蚺放控制中枢，制造站放清流、温蒂、异客，发电站搭配医疗小车 效率有1.42
3希望加个检索使用菲亚功能。菲亚基本用在巫恋、龙舌兰、卡夫卡/柏喙永动上。两班的话只要给巫恋、龙舌兰回 然后卡夫卡和柏喙交换上班就行
4其实左上角有个总的换起来更快 不用一个个设施进去换心情
不知道基建底层逻辑实现是怎么样的。有没有可能检索干员列表之后存个本地文件，以后就不用检索了，要更新列表的话单独在设置里添一个键

**Comment by a504558403** [comment]
还有个会客室的优先级问题：我发现他是远山优先于红。会客室的加速是星级+技能的。五星比四星要快。所以会客室最快其实是红陈

**Comment by a504558403** [comment]
因为基建是每天都差一点收益的。所以效率上我怕作者有些小东西不清楚 所以提一下。有些可能是比较好改的

**Comment by ABA2396** [comment]
1. 诗怀雅和阿米娅同时上班的问题新版本已经解决了（如果更新之后还有bug再提issue）
2. 现在还没有做跨基建的联动，所以是不看其他设施下的单设施最优解（如果没bug的话）
3. 肥鸭技能比较麻烦，但有计划做（新建文件夹）
4. 总览换人是快，但会导致不知道制造站贸易站的产品是什么，不能通过这个知道用什么技能，之后其他设施可能会换成这种换人方式（大概）

**Comment by zzyyyl** [comment]
自定义基建能解决大部分问题了（
