### ISSUE TITLE
肉鸽商店不投资

### ISSUE THREAD

**Issue by hckkk** [MaaAssistantArknights/MaaAssistantArknights#1203]
rt,肉鸽我想尽可能往后打（拿蜡烛）同时也想投资 :(

**Comment by MistEO** [comment]
尽可能往后打也是会投资的

**Comment by hckkk** [comment]
![image](https://user-images.githubusercontent.com/52353100/179387199-b87c7d7e-1ece-47ad-ba2e-642ca91cd4a5.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9127172/asst.log)
但是他真的没有投资，我又试了一次也是不投资搁那买东西，有录屏

**Comment by MistEO** [comment]
你的分辨率太奇怪了，是 `1720 x 968`, 换个正常点的 16:9 吧
