### ISSUE TITLE
刷肉鸽时，初始招募必定闪退；自动公招退出进入无限循环

### ISSUE THREAD

**Issue by HotTea601** [MaaAssistantArknights/MaaAssistantArknights#1204]
夜神模拟器7.0.3.1，软件版本号v4.0.6
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9127020/asst.log)
初始自动放弃近卫招募
![Screenshot_20220717-115257](https://user-images.githubusercontent.com/109448405/179383416-ba5da034-b3f6-4b50-876d-7cd322c37f34.png)
辅助招募红蒂
![Screenshot_20220717-115326](https://user-images.githubusercontent.com/109448405/179383419-4fc770ff-caf6-476f-8188-f77628087dee.png)
然后停在医疗招募界面，软件必定闪退
![Screenshot_20220717-115330](https://user-images.githubusercontent.com/109448405/179383420-36e0ca13-51f2-4dbe-89db-9fb0b10f812f.png)

自动公招不会进行新的招募，也不会收取已完成招募，一直在招募界面和主界面反复横跳，

**Comment by MistEO** [comment]
设置里面你选了韩服

**Comment by HotTea601** [comment]
原来如此
