### ISSUE TITLE
肉鸽内部分关卡布局不合理导致作战无法结束

### ISSUE THREAD

**Issue by hryw** [MaaAssistantArknights/MaaAssistantArknights#1209]
如图，在关卡正义内由于治疗阻挡了最后一个怪导致作战无法结束，程序无法继续运行
![a277cf34cdc875b601b5bf90dc39cc5](https://user-images.githubusercontent.com/77156277/179401799-ad2f694c-cdef-4955-9e81-16c41050c6c0.png)

**Comment by zzyyyl** [comment]
超时后会自动退出的（

**Comment by horror-proton** [comment]
现在的设计好像是卡了 5 分钟自动撤退干员, 如果你发现卡了超过 5 分钟还没有自动撤退, 那应该被视为 bug, 可以提交一下日志

**Comment by ABA2396** [comment]
自从玛丽改了蓝门位置之后干员就喜欢反过来站了）
