### ISSUE TITLE
基建识别错误

### ISSUE THREAD

**Issue by Aoki-Li** [MaaAssistantArknights/MaaAssistantArknights#1210]
晚上使用MAA（v4.0.7-beta1）挂机的时候发现基建并没有正常运作，并且仅重启MAA可以多次复现（日志不包含但看了模拟器操作过程都是一模一样），手动换基建并重启模拟器后正常，手动换基建时发现很多都红了，所以我怀疑早上挂的时候也失败了（日志不包含早上）。

使用模拟器：
![uTools_1658069635729](https://user-images.githubusercontent.com/46291296/179404068-97a15a12-508b-4c1c-a6e0-2562db0d1775.png)

日志：[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9127905/asst.log)

录制了一段视频不清楚配合log能否帮助您发现问题
链接：https://pan.baidu.com/s/1Tu46SpJNZPfR1HMrzcVF6Q 
提取码：m3jt

**Comment by horror-proton** [comment]
我看到你把开发者选项里的显示指针位置打开了, 这一层是会被 adb 截图到的, 你可以把它关了再试一下, 而且据我所知把这个打开除了会使基建不正常之外可能还会导致商店里面不能正常领取信用?

**Comment by Aoki-Li** [comment]
行我明天给他关了，其实手操并重启之后试了好几次已经正常了更新到v4.0.7也没有问题，我也感觉是adb之类的出了问题但我害怕碰到逻辑有问题才发起的issue，你要这么一说看来很有可能是我操作不当导致的。
打开指针是因为昨天在用明日再肝的保全我看他半天不动事并且提前自动退出想看看是啥问题，但脚本是加密的我就打开指针看看什么情况，开着指针刷理智好像没啥问题就没管了。

**Comment by ABA2396** [comment]
如果还遇到问题的话再发一下
