### ISSUE TITLE
肉鸽剧目独行客触发后识别不到

### ISSUE THREAD

**Issue by WarmLight7** [MaaAssistantArknights/MaaAssistantArknights#1213]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9127948/asst.log)

![image](https://user-images.githubusercontent.com/59765294/179405105-aa655904-10d0-4e02-bac8-e0aaf7769fd1.png)

剧目独行客触发后识别不到，整个界面卡死到这个页面，我当时也慌了，乱点了两下，maa直接退了QAQ，好不容易打到第五章，我都准备见证挑战傀影了，好可惜，我是录屏了的，需要补充可以再说

![image](https://user-images.githubusercontent.com/59765294/179405161-c4e840b9-6057-41c9-b90c-6505db34d9c3.png)

**Comment by WarmLight7** [comment]
这里面还有一些奇怪的bug，比如澄闪在配置文件里面选的3技能或者2技能，但是前面不知何时变成了一技能
![image](https://user-images.githubusercontent.com/59765294/179405350-2115e560-e12f-42c9-acde-03fb64bf8016.png)
![image](https://user-images.githubusercontent.com/59765294/179405370-2691800d-6695-4b45-b689-4fb49326f4ac.png)
![image](https://user-images.githubusercontent.com/59765294/179405401-e0eb7699-d6de-45e0-a98b-c92482e37383.png)

**Comment by WarmLight7** [comment]
![image](https://user-images.githubusercontent.com/59765294/179406881-86baa72b-58a9-4295-be55-2858dd08ae1d.png)
这个bug应该也在这个日志里面，maa识别不到感化这关最上面一排的干员技能，因为是被阻挡了，地面中间这个位置技能还是挺重要的，无论是山还是棘刺都得开两下，而且这个位置是不会变的，可以添加一下识别

**Comment by horror-proton** [comment]
技能被挡住相关 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1152 , 感觉还是有可能想办法让它识别到的, 但是需要亿点 cv

**Comment by PenguinLogistics** [comment]
肉鸽有一些剧目会卡住，是识别不到吗

**Comment by WarmLight7** [comment]
是识别不到吧，到了那个页面就没有响应了

**Comment by zzyyyl** [comment]
肉鸽剧目现在没有做识别

**Comment by WarmLight7** [comment]
其实也不需要识别，随便点一下就好了，后续正常识别应该是可以的

**Comment by zzyyyl** [comment]
> 其实也不需要识别，随便点一下就好了，后续正常识别应该是可以的

这如果没有剧目随便点一下有可能出事（
不过加一个检测那个 X 就可以了

**Comment by zzyyyl** [comment]
还有就是，不同的 bug 多开几个 issue，~~还能水contribution~~

我暂且把你上面的几个 off topic 的 hide 了

**Comment by WarmLight7** [comment]
> 

ok，那我去新开几个，主要这个asst有点大，他们都在同一个里面

**Comment by MistEO** [comment]
这个太难触发了，下次遇到了帮忙截个原图发下（模拟器自带的截图工具）

**Comment by MistEO** [comment]
说起来这个问题应该修掉了
