### ISSUE TITLE
希望可以添加无限刷肉鸽的时间限制或者次数限制

### ISSUE THREAD

**Issue by Garan902** [MaaAssistantArknights/MaaAssistantArknights#1214]
如题，比如刷2小时后 或者刷114次后结束

**Comment by ABA2396** [comment]
那就不叫无限刷肉鸽了（bushi）

**Comment by Garan902** [comment]
> 那就不叫无限刷肉鸽了（bushi）

可以设计成填入0或者不填的时候无限刷，增加时间或次数限制将会对睡前挂上然后自动关机很有帮助

**Comment by ABA2396** [comment]
可以：
手动 `win+r `
输入 `cmd` `回车`
输入 `at 12:00(你要关机的时间) shutdown -s ` 或者 `shutdown -s -t 3600(延时关机延时时间 单位:秒)` `回车`

**Comment by Garan902** [comment]
时间上确实可以通过外部方法解决，但是如果说 比如想要投资200锭后结束就没有什么替代办法

**Comment by ABA2396** [comment]
应该可以做成和 `指定材料` 差不多的样子？催催玛丽

**Comment by MistEO** [comment]
> 应该可以做成和 `指定材料` 差不多的样子？催催玛丽

做不了啊，能做早做了（

**Comment by MistEO** [comment]
似乎可以通过 UI 来实现，而不是通过 core，但感觉这样不太优雅

**Comment by Garan902** [comment]
> 似乎可以通过 UI 来实现，而不是通过 core，但感觉这样不太优雅

刷肉鸽的时候日志里不是会输出“已投资x个源石锭”吗

**Comment by MistEO** [comment]
fixed
