### ISSUE TITLE
如果LinkStart的时候停留在保全派驻的页面，没有办法回到主页

### ISSUE THREAD

**Issue by zaiziw** [MaaAssistantArknights/MaaAssistantArknights#1216]
希望能把暂停任务那个标志也加进去
![Snipaste_2022-07-18_11-27-07](https://user-images.githubusercontent.com/27818332/179441200-794d550f-c300-4ea0-8a65-39f6201be03b.png)

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
