### ISSUE TITLE
mumu模拟器刷肉鸽第一层源石锭 到商店不投资 把源石锭花完后退出

### ISSUE THREAD

**Issue by kaichengw1** [MaaAssistantArknights/MaaAssistantArknights#1217]

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/179456584-d276ff9c-770a-4c40-89ad-79ff71f5dcea.png)

**Comment by zzyyyl** [comment]
请检查你的 `设置-肉鸽设置`，并上传你的日志文件。
