### ISSUE TITLE
使用蓝叠稳定出现无法收取采购中心信用的情况，无论国际版还是国内版都如此

### ISSUE THREAD

**Issue by Sigritstorm** [MaaAssistantArknights/MaaAssistantArknights#1218]
### 日志
日志为勾选“收取信用及购物”一项后脚本开始运行到任务完成的全过程
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9129515/asst.log)

### 问题描述
执行“收取信用及购物”时有如下反应
1、进入信用交易所，然后停顿几秒
2、点击第一排最右边第五个商品，之后停顿几秒
3、脚本显示任务完成（如果存在其他任务则会退出信用交易所继续执行其他任务流程）

注：若我手动收取了信用，则脚本会正常购物，信用没收取就会卡上述问题
![56c682f0f45deeb19542564a896ae3e](https://user-images.githubusercontent.com/103521040/179448612-7855c842-cc72-45d5-88ab-d72c355e6a7e.jpg)
![c18c4d4610e5bb35a2097c4393a8bbe](https://user-images.githubusercontent.com/103521040/179448618-15252460-f41b-41bf-a62c-bd967f99ede8.jpg)
![7fc8d1fa7b45e50d25c44edf157140c](https://user-images.githubusercontent.com/103521040/179448621-5c0fc486-ad62-4b9e-95dd-1a559f266394.jpg)

**Comment by horror-proton** [comment]
根据你的日志, 已经识别到要收取信用并点击过了, 点击的位置也没什么问题 (1286, 40), 但是没有成功领取信用吗

```
[2022-07-18 12:53:22.859][TRC][Px1668][Tx110c] match_templ | CollectCredit.png score: 0.913188 rect: [ 956, 12, 131, 47 ] roi: [ 900, 0, 250, 100 ]
[2022-07-18 12:53:22.859][TRC][Px1668][Tx110c] Assistant::task_callback | SubTaskStart {"details":{"task":"CollectCredit","action":257,"exec_times":1,"max_times":2147483647,"algorithm":1},"taskchain":"Mall","taskid":1,"class":"class asst::ProcessTask","subtask":"ProcessTask","uuid":"f93efb0e943a2773\r\n"}
[2022-07-18 12:53:22.859][TRC][Px1668][Tx1340] asst::Controller::call_command | `C:\Program Files\BlueStacks_nxt_cn\.\HD-Adb.exe -s 127.0.0.1:5555 shell input tap 1286 40` | enter
[2022-07-18 12:53:23.024][TRC][Px1668][Tx1340] Call ` C:\Program Files\BlueStacks_nxt_cn\.\HD-Adb.exe -s 127.0.0.1:5555 shell input tap 1286 40 ` ret 0 , output size: 0
[2022-07-18 12:53:23.024][TRC][Px1668][Tx1340] asst::Controller::call_command | `C:\Program Files\BlueStacks_nxt_cn\.\HD-Adb.exe -s 127.0.0.1:5555 shell input tap 1286 40` | leave, 165 ms
```

**Comment by Sigritstorm** [comment]
是的，之前测试下来都是这样，现在换成MUMU模拟器能正常收取，由于今天已经收取了信用没法测试，明天我再下回蓝叠测试一下，如果仍然如此就上传录屏供您分析

**Comment by Sigritstorm** [comment]
郁闷，下回来测试了一次确实还是不行的，可是当我准备好录屏，重启脚本再来的时候又可以领了，但是购物好像有问题，跳过了好几个打折的没买（未加入黑名单），有点莫名其妙，请再给我一天时间，明天我直接开录屏，所有问题一起反馈

**Comment by Sigritstorm** [comment]
> 根据你的日志, 已经识别到要收取信用并点击过了, 点击的位置也没什么问题 (1286, 40), 但是没有成功领取信用吗
> 
> ```
> [2022-07-18 12:53:22.859][TRC][Px1668][Tx110c] match_templ | CollectCredit.png score: 0.913188 rect: [ 956, 12, 131, 47 ] roi: [ 900, 0, 250, 100 ]
> [2022-07-18 12:53:22.859][TRC][Px1668][Tx110c] Assistant::task_callback | SubTaskStart {"details":{"task":"CollectCredit","action":257,"exec_times":1,"max_times":2147483647,"algorithm":1},"taskchain":"Mall","taskid":1,"class":"class asst::ProcessTask","subtask":"ProcessTask","uuid":"f93efb0e943a2773\r\n"}
> [2022-07-18 12:53:22.859][TRC][Px1668][Tx1340] asst::Controller::call_command | `C:\Program Files\BlueStacks_nxt_cn\.\HD-Adb.exe -s 127.0.0.1:5555 shell input tap 1286 40` | enter
> [2022-07-18 12:53:23.024][TRC][Px1668][Tx1340] Call ` C:\Program Files\BlueStacks_nxt_cn\.\HD-Adb.exe -s 127.0.0.1:5555 shell input tap 1286 40 ` ret 0 , output size: 0
> [2022-07-18 12:53:23.024][TRC][Px1668][Tx1340] asst::Controller::call_command | `C:\Program Files\BlueStacks_nxt_cn\.\HD-Adb.exe -s 127.0.0.1:5555 shell input tap 1286 40` | leave, 165 ms
> ```

您好，我刚才换了个小号，把全过程录下来了，模拟器和脚本的设置信息也录进去了

### 录屏下载
百度网盘链接：https://pan.baidu.com/s/18vgyfrhPJ2C8RtrH5ok9JA 
提取码：7777 

录屏时长1分27秒，176MB，下载麻烦您了，抱歉

### 录屏全程对应日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9146764/asst.log)
该日志就是录屏中的日志

另，虽然前面用大号时偶然出现了一次可以领取的情况，但是我没搞懂什么原因（模拟器和脚本设置均一样），目前依然继续保持无法领取的情况，还有什么情况我发现后会及时补充，感谢。

**Comment by yyyy52** [comment]
相同问题，持续一周以上，使用的是Hyper-V蓝叠
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9147006/asst.log)

**Comment by horror-proton** [comment]
> > 
> 
> 那快去next里加一句）

在搞了在搞了.png

**Comment by Sigritstorm** [comment]
> 根据这几个日志, MAA 肯定都识别到要收取信用并点击过了, 感觉模拟器和 adb 不大可能出现只有右上角点不了的 bug. 看视频可以注意到网络延迟比较严重, 打开信用交易所后 收取信用♢ 马上就出现了, 但是经过很长时间交易所才完全加载好, 可能在此之前点击收取信用是无效的?
> 
> #### `[2022-07-20 14:23:46.154]`
> 在信用交易所内截图, 大致对应视频帧 `0:01:08:02`
> 
> #### `[2022-07-20 14:23:46.357]`
> 点击领取信用, 大致对应视频帧 `0:01:08:08` 而此时才刚刚提交反馈至神经完成, 交易所可能还没有加载完
> 
> (以上视频时间均为估计)

由于目前人还在国外，上国服网络延迟的问题确实是一直有的，但是我猜测应该还是模拟器的问题？
因为之前用蓝叠发现这个问题后我先是换用了夜神，然后就正常收取了，不过由于夜神存在音效延迟，又换了mumu，也都是正常收取的，所以我才认为是蓝叠的问题，这个问题在其他两个模拟器上一次也没出现过

**Comment by horror-proton** [comment]
因为 `asst::ProcessTask` 里对 sleep 处理的问题, 电脑性能比较好和模拟器比较快可能反而会导致遇到这种问题的概率增大 (

**Comment by MistEO** [comment]
v4.1.0-beta.2 fixed

**Comment by Sigritstorm** [comment]
刚才测了一下新版本已能正常收取了，感谢

**Comment by ABA2396** [comment]
不对这好像还不是正式版）
