### ISSUE TITLE
日服肉鴿 幹員 ocrReplace 成中文後閃退

### ISSUE THREAD

**Issue by natt3** [MaaAssistantArknights/MaaAssistantArknights#1220]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9130555/asst.log)
下面是 Visual Studio 2022 community 裡的
'[21608] MeoAsstGui.exe' 程式以返回碼 3221226505 (0xc0000409) 結束。

這裡用的是CharsNameOcrReplace裡的ocrReplace。

跳過幹員選擇的部分後，來到BattleStageName的ocrReplace，這裡的中文替換是可以正常執行的。

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/cda54a375842d781c71e1e262990829747c177e0/src/MeoAssistant/RoguelikeRecruitImageAnalyzer.cpp#L85-L86

猜测是这里崩了，没做数字的校验

**Comment by MistEO** [comment]
不过修复了崩溃问题，但我看这里把等级识别成了 `:`，不知道具体是哪个数字，可能得对应的做个 replace

**Comment by MistEO** [comment]
v4.0.8 fixed
