### ISSUE TITLE
希望可以降低内存占用

### ISSUE THREAD

**Issue by YinY1** [MaaAssistantArknights/MaaAssistantArknights#1221]
## rt, 完整跑一遍长草过程，轻而易举涨到了近1G的占用
![image](https://user-images.githubusercontent.com/36351545/179475363-1575a6b0-af95-40fc-8a00-139f7732e1ef.png)

并且任务结束之后内存占用并不会下来

![image](https://user-images.githubusercontent.com/36351545/179475547-e65db5a9-ed85-4eb4-8fca-c21a3fa773db.png)

### 附刚启动MAA时的内存占用
![image](https://user-images.githubusercontent.com/36351545/179475702-065fa521-0935-4c12-9240-88644556587a.png)

**Comment by MistEO** [comment]
这个是飞桨的缓存（也可能是内存泄漏），第三方库，似乎并没有什么特别好的办法解决

**Comment by BombaxCeiba** [comment]
可不可以在执行完任务后把飞浆的库从内存中卸载（

**Comment by ABA2396** [comment]
> 可不可以在执行完任务后把飞浆的库从内存中卸载（

可以选择执行完任务关闭MAA（）

**Comment by BombaxCeiba** [comment]
> > 可不可以在执行完任务后把飞浆的库从内存中卸载（
> 
> 可以选择执行完任务关闭MAA（）

那MAA的定时功能就用不了了（

**Comment by horror-proton** [comment]
可以在一个单独的进程里跑 OCR, 一段时间后杀掉重新创建?

**Comment by MistEO** [comment]
> 可以在一个单独的进程里跑 OCR, 一段时间后杀掉重新创建?

我感觉飞桨应该有某个参数可以限制或者关闭缓存？但我没找到，有没有大佬去研究研究（

**Comment by MistEO** [comment]
> 挖个坟
> 
> ##肉鸽内存占用竟然没有其他长草高？
> 
> 如果是OCR内存的缓存问题，那长时间肉鸽（开个10把左右）不是应该有更高占用才对嘛？
> 
> ![image](https://user-images.githubusercontent.com/36351545/180010002-38f0eed5-7e97-4df0-a036-f8f6626d5804.png)

准确来说是飞桨的检测模型缓存巨大。肉鸽没用飞桨的检测模型，都是用传统 cv 算法做的检测
