### ISSUE TITLE
奇怪的干员识别问题

### ISSUE THREAD

**Issue by nightofknife** [MaaAssistantArknights/MaaAssistantArknights#1224]
全日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9134590/asst.log)

涉及干员：幻影（夜莺召唤物）
识别结果：
![DE$5~%7B@YF4$ UIFX 0A1V](https://user-images.githubusercontent.com/73384329/179585090-f28ff30b-2238-4465-9de3-7cc9cfea6526.png)

由于聊天记录丢失，所以没法提供MAA版本（应该是406以上的）和模拟器类型以及分辨率

**Comment by ABA2396** [comment]
草我还特意看了下有没有什么影的干员结果被夜莺背刺了

**Comment by ABA2396** [comment]
663a864bbc4ae86637677711f23b1cd7e287307b fixed

**Comment by Sunkncost** [comment]
好家伙是我昨晚遇到的（然后就自己手打过了x

**Comment by MistEO** [comment]
> [663a864](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/663a864bbc4ae86637677711f23b1cd7e287307b) fixed

感觉还是得尽量少用通配，得抽空检查下别的通配会不会带来啥问题）

**Comment by MistEO** [comment]
v4.0.8 fixed
