### ISSUE TITLE
关于自动编队功能风笛识别错误

### ISSUE THREAD

**Issue by AnnoyingFlowers** [MaaAssistantArknights/MaaAssistantArknights#1232]
自动编队功能，风笛默认是三技能的时候，识别会有问题
蓝叠国际版 2560*1440
maa v4.0.8版本
![image](https://user-images.githubusercontent.com/89131639/179757671-8b85f2aa-df9f-45fa-884f-4d152c2c1b10.png)
![image](https://user-images.githubusercontent.com/89131639/179757625-30906621-9dde-4871-beab-30b8a8bd185f.png)
![image](https://user-images.githubusercontent.com/89131639/179757941-26f40cff-2e90-4cb2-b2dc-601c04aa1101.png)
可能是三技能图标的问题，默认技能换成二技能就没问题了
而且默认技能问题可能会出现在很多干员身上。。。建议修改一下识别范围啥的（不懂瞎说的）
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9141310/asst.log)

**Comment by ABA2396** [comment]
简简单单加个替换吧）

**Comment by ABA2396** [comment]
c1362597fe3e96b0dbc71c46fa5148f28de5314f fixed

**Comment by AnnoyingFlowers** [comment]
1280 * 720和2560 * 1440的默认一技能、三技能都会识别错误，只有默认二技能是好的（
只不过720p识别的岚笛，
![image](https://user-images.githubusercontent.com/89131639/179899280-aa722f9d-611c-4499-bd7e-69b360b3b930.png)
1440p识别的凤笛
![image](https://user-images.githubusercontent.com/89131639/179900359-d428b902-6863-4317-9984-944e9b602bf6.png)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9146633/asst.log)

**Comment by zzyyyl** [comment]
没事反正已经修了（

**Comment by AnnoyingFlowers** [comment]
如果只是加个替换的话
其他干员有可能会出问题（
我打算这两天浅测一下其他干员
这个就先关了
