### ISSUE TITLE
一些小小的建议（（（

### ISSUE THREAD

**Issue by DeathofBrain** [MaaAssistantArknights/MaaAssistantArknights#1234]
1. 希望能出个代打保全派驻（主流打法 铃兰 澄闪 攻速流） 像肉鸽一样能打几层是几层，拿奖励就行
2. 关于基建希望能细分一下功能： 
   1 可以将换班和收菜分开，有时候我就是懒得点一下XD
   2 换班希望能让用户自己保存干员配置
3. 有没有可能，我是说可能，出个自动抽卡，这样如果没出货就可以安慰自己不是自己脸黑了XDDDDDDDDDDDD

**Comment by zzyyyl** [comment]
Q1. **可以将换班和收菜分开**
- 换班和收菜分开也许可以整一个

Q2. **换班希望能让用户自己保存干员配置**
- 按照玛丽的意思，换班是不会出用户自定义配置了（但是全局最优解已经在做了

Q3. **出个自动抽卡，这样如果没出货就可以安慰自己不是自己脸黑了**
- 自动抽卡？让用户说自己脸黑比说 MAA 脸黑要好（确信

**Comment by MistEO** [comment]
我反而觉得自动抽卡可以出，因为幸存者偏差，出了 6 星一定会有人来群里海豹：“maa 帮我出六星啦”；但是一直紫气东来在群里吐槽：“maa 怎么这么非”，一会会有人回：”是你自己黑吧哈哈哈哈“

综上（）

**Comment by ABA2396** [comment]
之前写过活动自动一抽了，在task里可以找到啊（）

**Comment by lxq-9527** [comment]
> 我反而觉得自动抽卡可以出
> 
> 出了 6 星一定会有人来群里海豹：“maa 帮我出六星啦”； 如果一直紫气东来在群里吐槽：“maa 怎么这么非”，一定会有人回：”是你自己黑吧哈哈哈哈“
> 
> 而且因为幸存者偏差，时间一长就会给大家造成一种 maa 非常欧的感觉（x

有没有一种可能 如果一直紫气东来在群里吐槽：“maa 怎么这么非，还不如我自己抽呢” 
偶尔出了六星没歪就可以说maa太非了 还好我够欧^_^

**Comment by MistEO** [comment]
> Q1. 可以将换班和收菜分开

把 maa 基建设置里所有设施的 √ 都关掉应该就可以了
