### ISSUE TITLE
开机自动启动MAA时无法打开并且报告停止工作

### ISSUE THREAD

**Issue by m15476** [MaaAssistantArknights/MaaAssistantArknights#1236]
问题：开机的时候MAA打开时报告停止工作，用的是NoAVX的版本（电脑有点老,CPU-Z里面CPU指令集里面没有AVX），想用别的打开MAA也跟开机自启一样打不开
注：人工直接打开能用，但是自动打开那里用不了
对这个问题不是很懂，问一下

模拟器：用的最近从官网下的夜神模拟器

截图：![捕获](https://user-images.githubusercontent.com/109606699/179785854-c29a586f-add6-4f7c-a747-7b7e2ad92bb4.PNG)

日志：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9142455/asst.log)

第一次发github，有什么问题见谅

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
