### ISSUE TITLE
日服测试版 有闪退问题 夜神模拟器 安卓7 64位 分辨率 1600*900

### ISSUE THREAD

**Issue by mikelookmlik** [MaaAssistantArknights/MaaAssistantArknights#1237]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9142992/asst.log)
![Screenshot_20220720-002240](https://user-images.githubusercontent.com/106502472/179801667-5868dad4-87b7-4ef6-9d7e-ba5f7e48000c.png)

**Comment by mikelookmlik** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9143557/asst.log)
![Screenshot_20220720-015628](https://user-images.githubusercontent.com/106502472/179818032-c52bc213-10ad-4fa3-8fce-4b6017799bf6.png)

**Comment by zzyyyl** [comment]
@mikelookmlik 问一个问题，你的泡泡和能天使是多少级的（

**Comment by mikelookmlik** [comment]
@zzyyyl  能天使是 精1 80

**Comment by MistEO** [comment]
还真是 8，@zzyyyl 那你来.jpg
