### ISSUE TITLE
使用OTA更新到4.0.8后启动MAA未响应然后崩溃

### ISSUE THREAD

**Issue by lxq-9527** [MaaAssistantArknights/MaaAssistantArknights#1238]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9145681/asst.log)
4.0.7版本使用OTA更新到4.0.8 能正常使用，第二天启动MAA未响应然后崩溃（必现）

**Comment by lxq-9527** [comment]
> 日志里没有信息（
> 
> 那重下一个试试？

重下一个最新的就恢复正常了

**Comment by zzyyyl** [comment]
那应该算解决了吧（
