### ISSUE TITLE
4.0.8版本任务栏图标不见了

### ISSUE THREAD

**Issue by Baiyuqiao0416** [MaaAssistantArknights/MaaAssistantArknights#1239]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9145810/asst.log)

![image](https://user-images.githubusercontent.com/55887104/179877557-c898a6f5-e1c6-4f2e-afb6-e2e0593f72ae.png)
如图，左边是蓝叠国际版，右边是微信，中间是Maa。
通过下载github上面的OTA升级包进行的更新。

**Comment by MistEO** [comment]
清一下电脑缩略图缓存把
