### ISSUE TITLE
`StartUp` 任务支持游戏热更新

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#1240]
![Screenshot_2022 07 20_09 47 08 233](https://user-images.githubusercontent.com/18511905/179878457-af9e17c6-3bbf-4680-b86f-6d1e17527ac1.png)

![Screenshot_2022 07 13_10 23 36 908](https://user-images.githubusercontent.com/18511905/179878541-d02b26a9-844d-4989-ab49-3f626f8f28fe.png)

1080p 下原图，识别下右上角的标应该就行了

**Comment by status102** [comment]
- fixed #10680
