### ISSUE TITLE
关卡永无尽头内反复尝试往已有干员的高台上放置干员

### ISSUE THREAD

**Issue by hryw** [MaaAssistantArknights/MaaAssistantArknights#1244]
如视频
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9146142/asst.bak.log)

https://user-images.githubusercontent.com/77156277/179886318-cf7481cb-8fae-40c2-8451-0524f1cfb891.mp4
（保全派驻叠干员操作疑似提前流出？

**Comment by MistEO** [comment]
修了
