### ISSUE TITLE
偶现掉落识别错误

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#1245]
![2022-07-20_09-53-35 104_raw](https://user-images.githubusercontent.com/18511905/179885868-a9590380-796d-4174-a0a9-9d0483b97e46.png)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9146111/asst.log)

![image](https://user-images.githubusercontent.com/18511905/179885922-501bf5e3-b141-428f-b5fd-ac988013671d.png)

**Comment by zzyyyl** [comment]
让我来猜猜，肯定是空弦的腿太白导致的（

**Comment by ABA2396** [comment]
这还太白？
