### ISSUE TITLE
MuMu模拟器运行没反应，会直接完成任务

### ISSUE THREAD

**Issue by Afurete233** [MaaAssistantArknights/MaaAssistantArknights#1247]

**Comment by Afurete233** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9146462/asst.log)

**Comment by zzyyyl** [comment]
看上去是 screencap 炸了？

还有就是你的 adb 看上去不是 mumu 自带的 adb，不知道有没有影响（

**Comment by MistEO** [comment]
所以不要用 mumu

![image](https://user-images.githubusercontent.com/18511905/179990115-2bcfe50d-09a3-4ae5-9b37-5aa25a1c901a.png)
