### ISSUE TITLE
调整 `自动战斗 Beta` 的小提示

### ISSUE THREAD

**Issue by AnnoyingFlowers** [MaaAssistantArknights/MaaAssistantArknights#1248]
鉴于很多人不看`小提示`就点`开始`，然后`小提示`就被清空了，毫无提示作用。

![image](https://user-images.githubusercontent.com/89131639/179904531-38fc947e-884f-4166-a299-c0e5e07daf2e.png)

这里提供两种解决方案
-------------------------
* 第一种：
.\src\MeoAsstGui\ViewModels\CopilotViewModel.cs 里，第295行把`ClearLog();`这行删掉

![image](https://user-images.githubusercontent.com/89131639/179904675-fe4524e1-b182-4552-bd01-21998f739680.png)

* 第二种：
还是.\src\MeoAsstGui\ViewModels\CopilotViewModel.cs 里，第42行的`AddLog("小提示：...");`复制一份放到第296行

![image](https://user-images.githubusercontent.com/89131639/179906602-e2d70626-bdf9-4cac-a963-c7f7882e7cac.png)

**Comment by ABA2396** [comment]
36cf3b9449f4c531dc31a53aec06d3f434b8faa3 bbdc106d008c9886a328039de247eeac3c13cbf7

**Comment by MistEO** [comment]
v4.1.0 fixed
