### ISSUE TITLE
肉鸽干员技能选择错误

### ISSUE THREAD

**Issue by WarmLight7** [MaaAssistantArknights/MaaAssistantArknights#1249]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9147704/asst.log)
这里面还有一些奇怪的bug，比如澄闪在配置文件里面选的3技能或者2技能，前面选择的时候也是正确的，但是在招募到灵知之后，干员的技能选择变成了一技能
![image](https://user-images.githubusercontent.com/59765294/179928519-08e76345-44d1-4836-af22-e5e8726e77b9.png)
![image](https://user-images.githubusercontent.com/59765294/179928567-c3f045bb-7292-421c-bca5-902e98e86400.png)
![image](https://user-images.githubusercontent.com/59765294/179928609-39f0b718-63a3-4c0a-a6c6-10dcdafd7cf7.png)

**Comment by MistEO** [comment]
修了
