### ISSUE TITLE
偶发掉落物数量识别错误

### ISSUE THREAD

**Issue by Karonheaven** [MaaAssistantArknights/MaaAssistantArknights#1251]
刚才刷1-7时发现固源岩数量超过合理范围，排查日志发现某次掉落数量识别错误，推测将掉落数量1识别为7。软件界面LOG如下图所示：

![PrtSc 2022-07-20 19-18-31](https://user-images.githubusercontent.com/23610722/179970574-19602b3c-d839-4194-9c2f-f5c6926a8f84.png)

日志文件如下：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9149319/asst.log)

但重试数次未能重现该BUG，暂不清楚可能是什么原因导致的该识别问题

Envs
OS: Windows 10 LSTC 2021
模拟器: Mumu Global
Android Debug Bridge version 1.0.41
Version 33.0.2-8557947

**Comment by MistEO** [comment]
没有原图这种问题几乎没法修复（

新的测试版修了一个别的掉落识别错误，不知道会不会顺便也解决这个问题，总之先挂起来了

**Comment by MistEO** [comment]
v4.1.1 fixed
