### ISSUE TITLE
基建换班不合理

### ISSUE THREAD

**Issue by 1838860816** [MaaAssistantArknights/MaaAssistantArknights#1252]
全部人都换下来之后宿舍装不下, 长期使用脚本换基建会导致人都换光了, 建议往基建里进人的时候不只选心情百分百的, 最好和宿舍入住一样给一个阈值选择,

**Comment by MistEO** [comment]
不会有这种情况的，除非

- 你换班频率太低了
- 你把心情阈值拉的太高了

**Comment by 1838860816** [comment]
> 请问入住制造站的时候会选择心情低于百分百的吗 我现在仓库里很多大半心情的它不选择 然后返回我干员不足的信息

**Comment by 1838860816** [comment]
> 不会有这种情况的，除非
> 
> * 你换班频率太低了
> * 你把心情阈值拉的太高了



> 不会有这种情况的，除非
> 
> * 你换班频率太低了
> * 你把心情阈值拉的太高了

请问入住制造站的时候会选择心情低于百分百的吗 我现在仓库里很多大半心情的它不选择 然后返回我干员不足的信息

**Comment by ABA2396** [comment]
会，但不能低于阈值，截个图看看啥样的

**Comment by 1838860816** [comment]
> 不会有这种情况的，除非
> 
> * 你换班频率太低了
> * 你把心情阈值拉的太高了

即使我把心情阈值调低, 不也仅仅是宿舍不入住了吗, 制造站依旧不会选择心情不满的干员

**Comment by 1838860816** [comment]
> 会，但不能低于阈值，截个图看看啥样的

设置中的阈值不是入住宿舍的阈值吗 和制造站有关系吗 我现在仓库里有很多大半心情的干员 但是maa界面说干员不足, 不给我入住
![image](https://user-images.githubusercontent.com/61180940/180239966-fe9518a8-8fea-41ad-89c7-7fad0b75b827.png)

**Comment by ABA2396** [comment]
你阈值设了多少

**Comment by ABA2396** [comment]
> > 你阈值设了多少
> 
> 99 但那不是宿舍的阈值吗

那就是低于99%的都要去宿舍，就不能去工作

**Comment by 1838860816** [comment]
> 你阈值设了多少

您的意思是这个阈值同时也是制造站入住的阈值吗

**Comment by 1838860816** [comment]
> > > 你阈值设了多少
> > 
> > 
> > 99 但那不是宿舍的阈值吗
> 
> 那就是低于99%的都要去宿舍，就不能去工作

我懂了一点, 我调低试试 感谢您的解惑

**Comment by ABA2396** [comment]
一般这个设成40%左右，要是8小时一班可以设成30%，这个用默认其实是差不多的

**Comment by MistEO** [comment]
- 只要是心情不满 + 不在工作的干员，都会被入驻宿舍
- 心情低于设定阈值的干员，不会去工作

感觉这个文本描述不太准备，或许可以改改？

**Comment by ABA2396** [comment]
> * 只要是心情不满 + 不在工作的干员，都会被入驻宿舍，与阈值无关
> * 心情低于设定阈值的干员，不会去工作（最终还是会被塞到宿舍里）
> 
> 感觉这个文本描述不太准备，或许可以改改？

改成工作阈值（？）

**Comment by 1838860816** [comment]
> * 只要是心情不满 + 不在工作的干员，都会被入驻宿舍
> * 心情低于设定阈值的干员，不会去工作
> 
> 感觉这个文本描述不太准备，或许可以改改？

是的 我就没有理解这里的意思 我觉得您可以采用另一位说的工作阈值
