### ISSUE TITLE
肉鸽部分地图部署干员朝向错误

### ISSUE THREAD

**Issue by Yuheh** [MaaAssistantArknights/MaaAssistantArknights#1253]
上个版本还是正常的，今天更新4.0.8肉鸽摆干员就有问题了（芙蓉你在什么呀）。图二全体向右看齐，太乐了。
![image](https://user-images.githubusercontent.com/71119972/179989417-66d0f4e8-cacb-485a-9545-de8beb659e22.png)

![image](https://user-images.githubusercontent.com/71119972/179987622-14d50cf1-4add-4b79-b363-8d26e36e4793.png)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9149929/asst.log)

**Comment by MistEO** [comment]
@zzyyyl 出来挨打！

**Comment by 1127626014** [comment]
我肉鸽还是全部都往右边放，不管地面单位还是高台单位

**Comment by 1127626014** [comment]
![问题](https://user-images.githubusercontent.com/57735361/180277949-50427851-7800-4e13-a868-d8e52db68428.png)

**Comment by ABA2396** [comment]
> ![问题](https://user-images.githubusercontent.com/57735361/180277949-50427851-7800-4e13-a868-d8e52db68428.png)

这是靠近蓝门放，至少不是全朝右了）

**Comment by MistEO** [comment]
> 我肉鸽还是全部都往右边放，不管地面单位还是高台单位

啥版本，更新了没

**Comment by zzyyyl** [comment]
> 我肉鸽还是全部都往右边放，不管地面单位还是高台单位

这不是没有全部朝右嘛（
~~那就是算法问题了，不是我的问题（~~

**Comment by 1127626014** [comment]
这应该是最新的吧







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月22日(星期五) 上午9:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽部分地图部署干员朝向错误 (Issue #1253)





  
我肉鸽还是全部都往右边放，不管地面单位还是高台单位
  
啥版本，更新了没

**Comment by 1127626014** [comment]
问题是蓝门在左，煌是面对右边，但是蓝门在右，煌还是对右边。确实是靠近蓝门，但是所有不管蓝门在左在右，干员都是朝向右边



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月22日(星期五) 凌晨1:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽部分地图部署干员朝向错误 (Issue #1253)





  

  
这是靠近蓝门放，至少不是全朝右了）

**Comment by 1127626014** [comment]
就是算法可以有个干员朝向和蓝门相反，这不管蓝门在左在右，干员都超右边




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月22日(星期五) 上午9:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽部分地图部署干员朝向错误 (Issue #1253)





  
我肉鸽还是全部都往右边放，不管地面单位还是高台单位
  
这不是没有全部朝右嘛（
 那就是算法问题了，不是我的问题（

**Comment by MistEO** [comment]
> 这应该是最新的吧
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人: ***@***.***&gt;; 
> 发送时间: 2022年7月22日(星期五) 上午9:36
> 收件人: ***@***.***&gt;; 
> 抄送: ***@***.***&gt;; ***@***.***&gt;; 
> 主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽部分地图部署干员朝向错误 (Issue #1253)
> 
> 
> 
> 
> 
>   
> 我肉鸽还是全部都往右边放，不管地面单位还是高台单位
>   
> 啥版本，更新了没
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

不要应该，哪个版本

**Comment by zzyyyl** [comment]
发个日志

**Comment by zzyyyl** [comment]
> 就是算法可以有个干员朝向和蓝门相反，这不管蓝门在左在右，干员都超右边
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年7月22日(星期五) 上午9:45 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽部分地图部署干员朝向错误 (Issue #1253) 我肉鸽还是全部都往右边放，不管地面单位还是高台单位 这不是没有全部朝右嘛（ 那就是算法问题了，不是我的问题（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

从你的图里看，泥岩和桃金娘至少不是朝右的

**Comment by MistEO** [comment]
> > 就是算法可以有个干员朝向和蓝门相反，这不管蓝门在左在右，干员都超右边
> > […](#)
> > ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年7月22日(星期五) 上午9:45 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽部分地图部署干员朝向错误 (Issue #1253) 我肉鸽还是全部都往右边放，不管地面单位还是高台单位 这不是没有全部朝右嘛（ 那就是算法问题了，不是我的问题（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
> 
> 从你的图里看，泥岩和桃金娘至少不是朝右的

我觉得就是版本没更新而已

**Comment by ABA2396** [comment]
> 但我下的是官网最新版，检测更新也是说最新的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年7月22日(星期五) 中午1:05 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽部分地图部署干员朝向错误 (Issue #1253) 就是算法可以有个干员朝向和蓝门相反，这不管蓝门在左在右，干员都超右边 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年7月22日(星期五) 上午9:45 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽部分地图部署干员朝向错误 (Issue #1253) 我肉鸽还是全部都往右边放，不管地面单位还是高台单位 这不是没有全部朝右嘛（ 那就是算法问题了，不是我的问题（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 从你的图里看，泥岩和桃金娘至少不是朝右的 我觉得就是版本没更新而已 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

这个在测试版本修了，正式版可能还没上

**Comment by MistEO** [comment]
> 但我下的是官网最新版，检测更新也是说最新的
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人: ***@***.***&gt;; 
> 发送时间: 2022年7月22日(星期五) 中午1:05
> 收件人: ***@***.***&gt;; 
> 抄送: ***@***.***&gt;; ***@***.***&gt;; 
> 主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽部分地图部署干员朝向错误 (Issue #1253)
> 
> 
> 
> 
> 
>    
> 就是算法可以有个干员朝向和蓝门相反，这不管蓝门在左在右，干员都超右边
>  …
>  ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年7月22日(星期五) 上午9:45 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽部分地图部署干员朝向错误 (Issue #1253) 我肉鸽还是全部都往右边放，不管地面单位还是高台单位 这不是没有全部朝右嘛（ 那就是算法问题了，不是我的问题（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
>   
> 从你的图里看，泥岩和桃金娘至少不是朝右的
>   
> 我觉得就是版本没更新而已
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

Issue 不是评论吐槽区，想解决问题请提供有效的信息，而不是一句 “最新版”，问你版本号又不说，日志也没有，我们这一群人围着你猜问题是什么吗？

**Comment by 1127626014** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Horror ***@***.***&gt;; 
发送时间: 2022年7月22日(星期五) 中午1:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽部分地图部署干员朝向错误 (Issue #1253)





  
我肉鸽还是全部都往右边放，不管地面单位还是高台单位
  
v4.0.8 出现的 bug, 理论上会导致干员朝向混乱的方向, 应该是因为屏幕大小限制等原因表现为大多数都被朝右放置, 这个 bug 在 v4.1.0-beta.3 被修复, 你可能并没有更新到已经修复的版本
