### ISSUE TITLE
自动公招能不能加一个同时最大公招数

### ISSUE THREAD

**Issue by SuzhiChair** [MaaAssistantArknights/MaaAssistantArknights#1254]
如题，目前的每次最大公招数会导致不到四个的情况下，在9小时内又运行的时候补满到四个

**Comment by ABA2396** [comment]
core没做存储，你可以用那个单独的公招功能啊）

**Comment by SuzhiChair** [comment]
可不可以在开始公招之前加一个步骤，检测当前公招数大于最大公招数就直接完成该任务，这样应该就不需要存储了吧
