### ISSUE TITLE
干员识别问题

### ISSUE THREAD

**Issue by Sunkncost** [MaaAssistantArknights/MaaAssistantArknights#1255]
罗宾的召唤物 "夹子" 不能正常部署，换成  "夹孑"之后就正常了。 是哪里写反了吗
![Screenshot 2022-07-20 223535](https://user-images.githubusercontent.com/86833635/180010205-11ffac99-c9b2-4664-98d8-80d1f4741a81.png)

日志文件：

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9150808/asst.zip)

模拟器：夜神
MAA版本：4.0.8

**Comment by MistEO** [comment]
v4.1.0 fixed
