### ISSUE TITLE
问问肉鸽的选人机制

### ISSUE THREAD

**Issue by xingyu1272** [MaaAssistantArknights/MaaAssistantArknights#1259]
![2` }TM89YX95EF%K0(P`790](https://user-images.githubusercontent.com/107303890/180112438-1f886f9c-fc7a-41ff-b13a-e62b446c7605.png)
![)QD)8Z8VRIMTGFQLL`BQ{U8](https://user-images.githubusercontent.com/107303890/180112444-26df754d-5b6a-4f01-bd3c-88f015d42acc.png)
![A{0}G2CAK7~4K` T5G2%9OA](https://user-images.githubusercontent.com/107303890/180112454-a3f9971d-b974-47e7-838e-07450ca9b788.png)
![NCO1W}`ZON( 7R$~ AG}Y6N](https://user-images.githubusercontent.com/107303890/180112461-7415b74c-7082-4a94-908d-4a42f312df02.png)
发现肉鸽中每次开局自动选的人都是羽毛笔+巫恋+临时医疗（P1）
P2-4为box 为什么自动识别练度之后却选了这三个人（）
是什么机制导致的 可以解决吗 或者自己修改阵容选择吗

**Comment by MistEO** [comment]
现在的机制是近卫优先，你近卫练的太少了（

**Comment by xingyu1272** [comment]
> 现在的机制是近卫优先，你近卫练的太少了（

然后就选了甚至没精二的羽毛笔吗（）

**Comment by xingyu1272** [comment]
> > 现在的机制是近卫优先，你近卫练的太少了（
> 
> 然后就选了甚至没精二的羽毛笔吗（）

甚至精一都没拉满

**Comment by zzyyyl** [comment]
羽毛笔，肉鸽的神！

**Comment by xingyu1272** [comment]
诶 好像漏了第一张图
![Q%2BS@_ ~PHWJ %W{8 X6 M](https://user-images.githubusercontent.com/107303890/180126840-482c388c-6f4a-4368-879e-e5580d198e6c.png)
近卫算很少吗（）

**Comment by zzyyyl** [comment]
现在是不选六星的机制，玛丽之后好像要改（？

**Comment by MistEO** [comment]
> 现在是不选六星的机制，玛丽之后好像要改（？

没不选 6 星啊。银灰 棘刺 在肉鸽里没精二的话，讲道理不如羽毛笔

**Comment by zzyyyl** [comment]
> > 现在是不选六星的机制，玛丽之后好像要改（？
> 
> 没不选 6 星啊。银灰 棘刺 在肉鸽里没精二的话，讲道理不如羽毛笔

欸我记得有个 Discussion 就是说这个的？

**Comment by MistEO** [comment]
> > > 现在是不选六星的机制，玛丽之后好像要改（？
> > 
> > 
> > 没不选 6 星啊。银灰 棘刺 在肉鸽里没精二的话，讲道理不如羽毛笔
> 
> 欸我记得有个 Discussion 就是说这个的？ #1167

现在啥都拿，和星级没关系，他希望我们去掉 4、5 星的

**Comment by YipKei** [comment]
> 诶 好像漏了第一张图 ![Q%2BS@_ ~PHWJ %W{8 X6 M](https://user-images.githubusercontent.com/107303890/180126840-482c388c-6f4a-4368-879e-e5580d198e6c.png) 近卫算很少吗（）

从你贴出的练度来看，羽毛笔是最佳选择，MAA的判断没毛病。

MAA现在的选择逻辑是按指挥分队走的，同时地面优先，指挥分队抓开局的时候优先考虑一二技能，你现在的干员组合下，如果玩家手动打的话最优组合确实不是羽毛笔，而是水陈+史都华德+斑点，或者凯尔希+梓兰+月见夜，但问题在于，这两个六星核心的战斗逻辑都和MAA的肉鸽核心战斗逻辑不符，如果要考虑这些组合的话，就要单独多写几套逻辑再进行判断。

MAA目前在肉鸽方面的设计理念是帮助尽可能多的玩家以尽量将简单的方式完成几个预定目标。

羽毛笔+巫恋+三星医疗的决策方式和这一设计理念并无冲突。

机器和人的判断有很大区别，有的时候需要一定思维方式上的转换。

**Comment by MistEO** [comment]
其实 maa 没有所谓核心战斗逻辑，啥阵容都能打，只不过 “选择分队” 这个功能不太好做，而且肉鸽的理念是能刷就行，所以就摆烂选近卫了（

**Comment by zzyyyl** [comment]
> 其实 maa 没有所谓核心战斗逻辑，啥阵容都能打，只不过 “选择分队” 这个功能不太好做，而且肉鸽的理念是能刷就行，所以就摆烂选近卫队了（

选择分队原来是随便选的吗，难道不是因为 MAA 会漏得比较多为了能尽量往后打所以才选的指挥分队吗（
选择分队要做的话应该很简单的吧（？

**Comment by MistEO** [comment]
> > 其实 maa 没有所谓核心战斗逻辑，啥阵容都能打，只不过 “选择分队” 这个功能不太好做，而且肉鸽的理念是能刷就行，所以就摆烂选近卫队了（
> 
> 选择分队原来是随便选的吗，难道不是因为 MAA 会漏得比较多为了能尽量往后打所以才选的指挥分队吗（
> 选择分队要做的话应该很简单的吧（？
> 哦说的是职业啊，也差不多吧（大概

我是指开放到界面上让用户选择

**Comment by MistEO** [comment]
这玩意是个 task 链，真要做的话或许可以抽个 plugin 来选（？

**Comment by zzyyyl** [comment]
> 这玩意是个 process task 链，真要做的话或许可以抽个 plugin 来选（？

代码量++
不过好像也没用户提这个需求，还是摆了吧（

**Comment by MistEO** [comment]
> > 这玩意是个 process task 链，真要做的话或许可以抽个 plugin 来选（？
> 
> 代码量++
> 不过好像也没用户提这个需求，还是摆了吧（

我突然觉得真可以做，这是我们比隔壁最大的优势来着（自适应编队），得利用起来

**Comment by YipKei** [comment]
> > > 这玩意是个 process task 链，真要做的话或许可以抽个 plugin 来选（？
> > 
> > 
> > 代码量++
> > 不过好像也没用户提这个需求，还是摆了吧（
> 
> 我突然觉得真可以做，这是我们比隔壁最大的优势来着（自适应编队），得利用起来

有一个问题啊，水陈-斑点-史都华德的组合，还有凯尔希-梓兰-月见夜的组合，放置干员的顺序和现在是不一样的。

自选编队我觉得更大程度上可能是兼容同样是地面开局的棘刺-梓兰-安塞尔这种地面精二核的分队。

还是说MAA会自动根据优选的主核来判断应该执行哪个task链，同时还得有人写新的优先级。

**Comment by YipKei** [comment]
> 我突然觉得真可以做，这是我们比隔壁最大的优势来着（自适应编队），得利用起来

另外，从某种意义上来说，除了棘刺+近卫队之外，稳定性最高的自选编队我觉得你不会想去做的，现有的热点算法基本不可能跑得动那玩意。（指挥分队+令，根据地图自适应选择技能）
