### ISSUE TITLE
无限刷肉鸽自动作战异常停滞#2

### ISSUE THREAD

**Issue by DrBlindriver** [MaaAssistantArknights/MaaAssistantArknights#1260]
如图所示，肉鸽自动作战进行到2022-07-21 03:21左右时，提示战斗失败。之后直到2022-07-21 09:10左右，游戏一直都卡在主界面，并且在重复进行点击助理干员并播放“交谈”语音的过程，期间无任何错误提示。

MAA版本：v4.1.0-beta1，在使用v4.0.7和v4.0.8时，均无出现类似问题。

<img width="591" alt="捕获" src="https://user-images.githubusercontent.com/19852923/180112979-6fcc5fd7-1a22-45b3-bbfd-b145d6f4240c.PNG">

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9155538/asst.zip)

**Comment by DrBlindriver** [comment]
PS：09:12:59的“已停止”消息，是我点击了停止按钮，终止了无限刷肉鸽（助理谈话）循环。xD

**Comment by MistEO** [comment]
应该是凌晨 4 点游戏刷新了，没识别到，或者哪里出问题了

**Comment by zzyyyl** [comment]
#MAA调戏助理干员#
