### ISSUE TITLE
肉鸽是否考虑选择临时招募干员

### ISSUE THREAD

**Issue by Komori-AA** [MaaAssistantArknights/MaaAssistantArknights#1261]
单纯好奇，之前看有临时6星招募没有选择，而且这个要做的识别挺多的如果不是常用干员

**Comment by ntgmc** [comment]
是否判断有两个解法：
1：打开maa的肉鸽模式，自己看
2：自己翻源码

**Comment by Komori-AA** [comment]
可能我话说的不是很明白，因为我认为没有所以才写了一个issue出来，表达得比较委婉不好意思。

**Comment by MistEO** [comment]
duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1951

**Comment by ntgmc** [comment]
临时也是打分机制，不会因为是临时而加分
