### ISSUE TITLE
指定材料刷关异常

### ISSUE THREAD

**Issue by tsctsc6** [MaaAssistantArknights/MaaAssistantArknights#1262]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9155625/asst.log)
指定刷医疗芯片，软件去刷医疗芯片组了

**Comment by MistEO** [comment]
指定材料和关卡导航无关。关卡导航只支持 “关卡选择“ 里面的那几个

**Comment by zzyyyl** [comment]
嘤，好像不是第一次有人问出这个问题了？也许得考虑改改描述

**Comment by MistEO** [comment]
> 嘤，好像不是第一次有人问出这个问题了？也许得考虑改改描述

把 pr 那种 tip 也给加一个（？

**Comment by tsctsc6** [comment]
哦，是不是‘指定材料’并不会选关，打的关还是‘关卡选择’所选择的关卡？

**Comment by ABA2396** [comment]
> 哦，是不是‘指定材料’并不会选关，打的关还是‘关卡选择’所选择的关卡？

这个只是用来限定刷你这关的次数的，导航还是根据 `关卡选择` 来的

**Comment by tsctsc6** [comment]
好的，我明白了

**Comment by ABA2396** [comment]
增加了个鼠标悬停的提示，应该会有点提示）

**Comment by tsctsc6** [comment]
哦，我看到了
