### ISSUE TITLE
能否添加自动识别仓库并作出刷图规划

### ISSUE THREAD

**Issue by SinCSSu** [MaaAssistantArknights/MaaAssistantArknights#1263]
Rt，如果将这个功能添加进MAA，就可以不用一边对着仓库扒拉一边企鹅物流了！懒人指数upup！
如果项目组人手不足也可以帮忙开发（虽然很菜）

**Comment by MistEO** [comment]
core 已经做完了，现在就是有接口的且可以正常用的，然后没空写界面 orz

**Comment by ntgmc** [comment]
这里给个工具箱，不用去企鹅物流了https://arkn.lolicon.app/#/material

**Comment by MistEO** [comment]
有仓库识别了
