### ISSUE TITLE
建议加一个自己找的线索全送人的选项~

### ISSUE THREAD

**Issue by Yue-plus** [MaaAssistantArknights/MaaAssistantArknights#1264]
现在是 *自己找的* 和 *别人送的* 线索都会挂上去，像我这种好友多的比较希望能积极交换线索。

**Comment by lxq-9527** [comment]
我记得说明文档里有调整送线索个数的介绍

**Comment by Yue-plus** [comment]
![image](https://user-images.githubusercontent.com/33195150/180120050-7a11c58d-6be3-4a0c-b91e-1ab6057913dd.png)

我想全送，有多少送多少（带善人

仓库里的线索不挂上去别人也会看到你有这个线索的，然后我个人比较倾向送给缺了对应线索的（每次都多翻几页找

**Comment by zzyyyl** [comment]
想全送就填 10 不就好了（

**Comment by Yue-plus** [comment]
> 想全送就填 10 不就好了（

那也得等自己找满10个才会开始送（
