### ISSUE TITLE
自动战斗如果编队选择了删除编队会提示战斗出错

### ISSUE THREAD

**Issue by zaiziw** [MaaAssistantArknights/MaaAssistantArknights#1266]
当我编队是这个样子的时候会直接提示战斗出错，感觉不是很清晰，是不是可以把识别的按钮改成单独的蓝色小人++图标
![AD@Z4UKU93L`RT5RPGYN~TT](https://user-images.githubusercontent.com/27818332/180126572-a8c47aa2-b4f2-4673-948e-965ade6da4b7.png)

**Comment by ABA2396** [comment]
炒饭）
