### ISSUE TITLE
建议为“关卡选择”增加后备选项

### ISSUE THREAD

**Issue by jsjjsyc** [MaaAssistantArknights/MaaAssistantArknights#1271]
主要需求是想要长期无人值守刷红票，但红票本不开的日子就会卡住。
希望能增加后备选项，在优先选项不开的时候刷其他材料。
例如：
![maa](https://user-images.githubusercontent.com/2813773/180208817-3ed126f6-0df8-44cf-a5dd-06164bd12f9f.jpg)
期望的效果：
周一四六日刷红票，周二刷龙门币，周三五刷精英材料。

**Comment by MouseWhite** [comment]
+1

**Comment by ABA2396** [comment]
现在有备选了，不过只有一个）

**Comment by ABA2396** [comment]
现在有两个了）但很丑
