### ISSUE TITLE
希望增加一个选项，不改变控制中枢的人员构成

### ISSUE THREAD

**Issue by chaimao403** [MaaAssistantArknights/MaaAssistantArknights#1273]

**Comment by zzyyyl** [comment]
你的意思是不换控制中枢吗？如果是的话，这个选项在设置里有

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/180278747-6d7654eb-6486-4e7e-b830-59ba0d07df38.png)
这样就是不换控制中枢
