### ISSUE TITLE
MAA相关文件和协议关联

### ISSUE THREAD

**Issue by ghost** [MaaAssistantArknights/MaaAssistantArknights#1274]
突发奇想，可以给现有的maa作业文件单独定义一个扩展名，如`.maawork`这类的
然后实现双击作业文件自动打开maa并跳转到自动战斗界面（maa打开时直接弹出并跳转）

与之前我提的 #786 结合一下，也可以搞一个类似的任务配置文件，双击打开直接加载配置

**Comment by MistEO** [comment]
作业平台就是 maa 专用的神秘代码，这个可能是以后趋势： `maa://12345` 这种感觉

你说的似乎也有道理_(:з」∠)_

**Comment by cglcv** [comment]
> 作业平台就是 maa 专用的神秘代码，这个可能是以后趋势： `maa://12345` 这种感觉
> 
> 你说的似乎也有道理_(:з」∠)_

那还可以再扩展一点，把maa协议也绑定maa，浏览器输入maa://直接交给maa打开
作业分享站加一个用maa打开的选项，直接返回maa协议调maa

**Comment by enpitsuLin** [comment]
url协议挺酷的，关于后缀名的话

~~不如发明个DSL描述作业顺便绑定后缀名好了~~
