### ISSUE TITLE
模拟器重启后重连失败

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantArknights#1277]
版本是 `v4.1.0-beta.3`

1. [ ] 模拟器一直重连，原因是模拟器重启后 AdbSerial 由 `emulator-5554` 变为 `127.0.0.1:5555`。
2. [X] 点击停止后 MAA 仍然不断尝试重连

- MAA 界面截图：  
![K6UAH~59 UR%C$ WYOLZ)J](https://user-images.githubusercontent.com/74587068/180346077-dbfae1f5-c18b-4f15-9e24-77967e395960.png)
- 日志：[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9163872/asst.-.log)

**Comment by MistEO** [comment]
这个 flag 传进去也好，还可以让 `停止` 把 `正在连接中` 早点停掉，下次一定（

**Comment by zzyyyl** [comment]
是不是应该给 Controller 也加个 `m_exit_flag` 和 `need_exit()`？

**Comment by zzyyyl** [comment]
@MistEO 你这不是只修了 2，没修 1 嘛（

**Comment by MistEO** [comment]
对了，现在不勾选 “自动检测连接” 则不会去修改地址，需求冲突了，所以！
