### ISSUE TITLE
自动战斗干员识别错误

### ISSUE THREAD

**Issue by Hengkongchushi83** [MaaAssistantArknights/MaaAssistantArknights#1280]
模拟器 蓝叠国际
maa v4.0.8
可能是开了模组的原因？没点特别关注的风笛识别不出来
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9164468/asst.log)
![QQ截图20220722112833](https://user-images.githubusercontent.com/81248614/180358928-0fc327eb-2a07-483e-99c9-02a9086d3630.png)

**Comment by ABA2396** [comment]
截个图看看

**Comment by MistEO** [comment]
v4.1.0 fixed
