### ISSUE TITLE
EN服肉鸽无法选人

### ISSUE THREAD

**Issue by Aliding** [MaaAssistantArknights/MaaAssistantArknights#1289]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

EN服肉鸽选完编队之后没法自动选人，程序超时自动放弃探索。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9170448/asst.log)

### 截图

见2群文件video recorder 1

### 还有别的吗？

Windows10, Nox9

**Comment by BlackNorton** [comment]
同遇到这个问题，win10，蓝叠国际版
日志：https://we.tl/t-77tBL3RHbs

**Comment by MistEO** [comment]
改了一下，试试这个 [金丝雀版本](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/2722354909) 有没有效果

**Comment by Aliding** [comment]
试了，没有效果
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9173130/asst.log)

**Comment by haoma119** [comment]
我也是，而且改了之后的一个都选不了，没改之前的那个版本是选了一个山之后才卡掉的

**Comment by MistEO** [comment]
似乎 `1600 x 900` 就会有问题，你们试试 `1280 x 720`
