### ISSUE TITLE
关卡选择filter没有按照服务器时间

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaAssistantArknights#1290]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

按照本地时间，结果周五下午在美西刷不了lmb

### 日志文件

N/A

**Comment by MistEO** [comment]
可以先在 设置 - 界面设置 里选择不隐藏关卡
