### ISSUE TITLE
基建会重复使用异格干员

### ISSUE THREAD

**Issue by sugeinmy** [MaaAssistantArknights/MaaAssistantArknights#1291]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

制造站会选择普通克洛斯，把中枢的异格克洛斯顶下来，然后到宿舍环节又因为心情不满，把异格克洛斯丢去宿舍了，这样就导致制造站少一个

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9172901/asst.log)
9：58的时候

**Comment by zzyyyl** [comment]
不要打错克洛丝的名字啊 kora

**Comment by ABA2396** [comment]
如果一直用软件换班的话应该是不会往中枢里塞异格克洛丝的吧

**Comment by MistEO** [comment]
如果一直用软件换班的话应该是不会往中枢里塞异格克洛丝的
