### ISSUE TITLE
升级到4.10后点击start闪退

### ISSUE THREAD

**Issue by 1ouloum** [MaaAssistantArknights/MaaAssistantArknights#1292]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

4.08之前一直正常没出过问题，今天早上自动升级至4.10后，一点击linkstart，右边显示正在连接模拟器10s左右后，maa自动关闭。
重启电脑，重启蓝叠，删除4.10重新下载安装，问题依旧。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9172904/asst.log)

### 截图

<img width="582" alt="aaa" src="https://user-images.githubusercontent.com/109835415/180586601-8718baa8-f2fa-4b66-b1ca-2bb6e55bb3b0.png">

### 还有别的吗？

蓝叠国际版N64。 系统Win10专业版。

**Comment by zzyyyl** [comment]
也许是 gui 文件新旧版本不兼容？你先把文件夹下的 gui.json 备份一下，然后删掉再重新打开试试

**Comment by horror-proton** [comment]
看上去好像和 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1191 第一个日志的情况一模一样?

**Comment by zzyyyl** [comment]
就是肉鸽的字段名字改了（删完gui.json就好了，或者手动把里面的 `无限刷肉鸽` 改成 `自动肉鸽` 就完事了

**Comment by zzyyyl** [comment]
> 看上去好像和 #1191 第一个日志的情况一模一样?

这么说，那边也可能是 gui.json 引起的问题

**Comment by 1ouloum** [comment]
感谢楼上几位回复，问题已解决，就是gui.json的问题，删除后就好了。

**Comment by horror-proton** [comment]
话说如果发现不兼容自动新建一个 gui.json 这种事情最好还是能让软件自动完成? 不然会让用户很迷惑, 反正我肯定想不到是这个原因

**Comment by zzyyyl** [comment]
> 话说如果发现不兼容自动新建一个 gui.json 这种事情最好还是能让软件自动完成? 不然会让用户很迷惑, 反正我肯定想不到是这个原因

因为前面的版本出过一样的问题，都怪玛丽 @MistEO

**Comment by zzyyyl** [comment]
> 话说如果发现不兼容自动新建一个 gui.json 这种事情最好还是能让软件自动完成, 或者有更新的时候自动打补丁? 不然会让用户很迷惑, 反正我肯定想不到是这个原因

我觉得现在确实不算解决了，reopen 等人打补丁
