### ISSUE TITLE
基建换班-艾丽妮

### ISSUE THREAD

**Issue by ilikecongee** [MaaAssistantArknights/MaaAssistantArknights#1293]
### 说说你遇到的问题？

基建换班会把训练室的艾丽妮给换下来，导致其被动失效。

### 有什么好的想法？

希望能不要自动将艾丽妮换下来。

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/763  (所以为啥https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/630 明明是最早提出这个问题的 issue 却被 close 了

**Comment by zzyyyl** [comment]
因为他写的少了（x
~~因为玛丽说他 duplicate 了~~

差不多啦，反正相关issue留住一个就能保留问题了

**Comment by ABA2396** [comment]
现在的办法大概是不换基建.jpg

**Comment by helloIris415** [comment]
希望能把训练干员改成不清空理智不进轮换。

**Comment by MistEO** [comment]
新增了按 `未进驻` 过滤进驻宿舍，fixed
