### ISSUE TITLE
ペンギンロジスティクスは、JPスーツのドロップを認識することはできますが、ソフトウェアが

### ISSUE THREAD

**Issue by foxlesbiao** [MaaAssistantArknights/MaaAssistantArknights#1294]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

ペンギンロジスティクスは、JPスーツのドロップを認識することはできますが、ソフトウェアが

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9173249/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/41581909/180594271-12b23de9-1361-46f5-aa0b-920808256934.png)
![image](https://user-images.githubusercontent.com/41581909/180594273-dcc816eb-f817-4d8f-a181-efefe0fa916b.png)

**Comment by ABA2396** [comment]
中国服务器的掉落结算画面和其他服务的结算画面不一样，所以识别不了掉落。日本服务器大概还有3个月会更新新的结算画面，那个时候可能会支持识别
![image](https://user-images.githubusercontent.com/99072975/180595654-a5e31c36-7f30-4152-bc63-94c815535742.png)

**Comment by IranksAdral** [comment]
今は日本のサーバーに支持できないらしいから、後三ヶ月ぐらいで更新してください、ごめなさいねm(_ _)m

**Comment by foxlesbiao** [comment]
> 今は日本のサーバーに支持できないらしいから、後三ヶ月ぐらいで更新してください、ごめなさいねm(_ _)m

OK、ありがとう
