### ISSUE TITLE
今日份掉落识别错误

### ISSUE THREAD

**Issue by IranksAdral** [MaaAssistantArknights/MaaAssistantArknights#1295]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

不知道为什么连装置都能识别失败

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9173360/asst.log)

### 截图

![2022-07-23_15-56-33 688_raw](https://user-images.githubusercontent.com/87361258/180596751-750bd5e9-246c-409d-9945-7649aad6cd40.png)
![HHECXAG))3%SZAG7ECT6@KG](https://user-images.githubusercontent.com/87361258/180596755-cf90769d-1e8c-4fd3-b6f5-f83af4dc6ceb.png)

**Comment by ABA2396** [comment]
新版本修了下掉落识别，更新下看看有没有解决

**Comment by MistEO** [comment]
我离线跑了一下，这张图还是错。晚点修复一下

**Comment by MistEO** [comment]
![S0`9$FSN`Y_ 5@Y3Q($9IKP](https://user-images.githubusercontent.com/18511905/180600318-b206ee7b-963b-4a66-8255-566533e31ff5.jpg)
![5I7_Y}2NS2X}~FHO T6K{A6](https://user-images.githubusercontent.com/18511905/180600337-648dfb79-d84e-4262-af04-5745ef2c2ee4.jpg)


阈值分割的方案已经快到极限了，下次再出错改用霍夫圆了
