### ISSUE TITLE
请不要让这个系统带梅尔

### ISSUE THREAD

**Issue by Zzzzzach** [MaaAssistantArknights/MaaAssistantArknights#1296]
### 说说你遇到的问题？

不知道为什么这个maa特别执着于放梅尔的破机器人 而且还是乱放
再加上不会撤干员每次选完基本上都会死

### 有什么好的想法？

ban掉梅尔，并加上手动操作功能这样有时候看到就不至于高血压

**Comment by Zzzzzach** [comment]
其他的问题还有类似于褐果这种技能的干员 放下去之后就会一个劲的点技能别的什么都不管了 这个是最致命的

**Comment by zzyyyl** [comment]
#1004

**Comment by zzyyyl** [comment]
肉鸽想要不招募某位干员，可以到 `resource/roguelike_recruit.json` 里给对应干员的名字加一个 `_N` 后缀或者直接删除。

**Comment by Zzzzzach** [comment]
> 肉鸽想要不招募某位干员，可以到 `resource/roguelike_recruit.json` 里给对应干员的名字加一个 `_N` 后缀或者直接删除。

好的明白了还有如何不让它去打大锁？ 每次看到大锁必会点去打
接着还有一个小bug 当maa部署类似褐果这种技能的干员的时候他不管里面有没有人或者需不需要只会一个劲的点技能（他的技能必须要在范围内有干员扣血才能触发但如果最先部署褐果的话则会陷入死循环）

**Comment by ABA2396** [comment]
> > 肉鸽想要不招募某位干员，可以到 `resource/roguelike_recruit.json` 里给对应干员的名字加一个 `_N` 后缀或者直接删除。
> 
> 好的明白了还有如何不让它去打大锁？ 每次看到大锁必会点去打 接着还有一个小bug 当maa部署类似褐果这种技能的干员的时候他不管里面有没有人或者需不需要只会一个劲的点技能（他的技能必须要在范围内有干员扣血才能触发但如果最先部署褐果的话则会陷入死循环）

那就把褐果也禁了。照理来说应该是不会去打大锁的，遇到的话可以用模拟器截个图然后发个日志看看

**Comment by LBacteria** [comment]
我还特意去练了梅尔……

**Comment by HYLazy** [comment]
如果配置文件能加一些注释就更好了

**Comment by MistEO** [comment]
fixed
