### ISSUE TITLE
请求肉鸽干员死亡后再部署

### ISSUE THREAD

**Issue by dsanying** [MaaAssistantArknights/MaaAssistantArknights#1298]
### 说说你遇到的问题？

肉鸽干员部署后如果死亡，冷却结束后不会被再次部署，出现有费放干员却一个都不放的情况，导致漏怪100%

### 有什么好的想法？

添加下方干员栏识别，如果有干员可部署并且冷却完毕即再次部署

### 其他内容

玛丽牛逼！

**Comment by MistEO** [comment]
就是死亡后再部署的，你应该是遇到了一个 bug，提个 bug report 看看

**Comment by dsanying** [comment]
ok
