### ISSUE TITLE
肉鸽干员有费不部署干员

### ISSUE THREAD

**Issue by dsanying** [MaaAssistantArknights/MaaAssistantArknights#1299]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽明明有费用，下面也有干员可以部署却在那里摆烂

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9173638/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9173639/asst.bak.log)
出错时间：tinghiqian停止前，19:29左右

### 截图

![image](https://user-images.githubusercontent.com/53586564/180603122-827a7c49-7b98-4a46-a231-e8e47bae3eeb.png)

### 还有别的吗？

逍遥模拟器
win10 64位

**Comment by dsanying** [comment]
补充全体摆烂图片
![image](https://user-images.githubusercontent.com/53586564/180610591-6889de71-e5f5-4ceb-9f32-e553f209a645.png)

**Comment by MistEO** [comment]
这个问题我这里无法复现，逍遥模拟器我们测的比较少，不知道有没有影响。尝试着加了个备用的识别方案，试试看这个 [金丝雀版本](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/2726414601) 有没有效果
