### ISSUE TITLE
EN服肉鸽 安全屋卡住

### ISSUE THREAD

**Issue by peter1997546** [MaaAssistantArknights/MaaAssistantArknights#1302]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

跟[EN服肉鸽 安全屋卡住 #1300](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1300)
类似状况
这次是在安全屋卡住
依旧是等了很久没反应

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9173802/asst.zip)

### 截图

![1](https://user-images.githubusercontent.com/23149848/180606052-a66c584c-ad90-4a3a-a3c0-9dba63b28ed6.PNG)

**Comment by MistEO** [comment]
看了下帮忙做美服支持的朋友没给这个地方截图，可能是漏了 orz

下次再遇到帮忙发一张模拟器自带的截图工具截取的原图，我们加一下

![image](https://user-images.githubusercontent.com/18511905/180635728-ad8a088d-6dba-46d2-80ad-497046c93e78.png)

**Comment by peter1997546** [comment]
> Roguelike1StageSafeHouseEnter.png
![Screenshot_2022 07 24_15 33 28 933](https://user-images.githubusercontent.com/23149848/180637217-9162bb03-3c1b-4e52-be95-dc1ed5f3f696.png)
![Roguelike1StageSafeHouseEnter](https://user-images.githubusercontent.com/23149848/180637220-4da53660-132e-4caa-b9e6-b8dc9c81f1d0.png)
[Roguelike1StageSafeHouseEnter.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9175326/Roguelike1StageSafeHouseEnter.zip)

**Comment by MistEO** [comment]
感谢~ 试试这个 [金丝雀版本](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/2726475528)

**Comment by cookie223** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/discussions/1212#discussioncomment-3185433

这里写了哪些还没截，第一层没有遇到的基本都没……估计boss战也会进不去，Select估计都会被忽视
