### ISSUE TITLE
更新日志弹出时报错

### ISSUE THREAD

**Issue by bingyunhe** [MaaAssistantArknights/MaaAssistantArknights#1305]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

提示更新下载完安装包后，重启MAA会弹截图所示弹框，如果点击关闭程序则更新公告无法弹出，如果不点击则更新公告能正常弹出，此时点关闭程序则更新公告消失。（日志感觉和这个错误无关

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9174419/asst.log)

### 截图

![ZC%(S9MEA@`I2TE9Z5F(RUV](https://user-images.githubusercontent.com/75605943/180618514-dc0e2c5f-896e-4e61-8a75-fa58624b284e.png)

### 还有别的吗？

雷电模拟器（应该无关，因为只在下载完更新包再次启动时会弹出）

版本	Windows 11 专业版
版本	21H2
安装日期	‎2021-‎11-‎11
操作系统版本	22000.739
体验	Windows 功能体验包 1000.22000.739.0

处理器	Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz   2.81 GHz
机带 RAM	16.0 GB (15.9 GB 可用)
显卡 1060 6g
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

**Comment by bingyunhe** [comment]
而且这bug是近几次更新后出现的，而我系统最近一次更新是6-16，应该和系统无关

**Comment by MistEO** [comment]
> 如果不点击则更新公告能正常弹出，此时点关闭程序则更新公告消失。

啥样的，来个图看看

**Comment by bingyunhe** [comment]
> > 如果点击更新公告能够正常弹出，此时关闭点程序则公告消失。
> 
> 啥样的，来个图看看

额，那得等下次更新才能截图了。
就是如果这个错误弹框留着不关闭，MAA的更新公告还是能弹出的。
如果点了错误弹窗的关闭程序，MAA更新公告会闪退.

**Comment by bingyunhe** [comment]
> > 如果不点击则更新公告能正常弹出，此时点关闭程序则更新公告消失。
> 
> 啥样的，来个图看看

奇怪，更新4.11没弹那个报错。
之前三四次更新都有的

**Comment by MistEO** [comment]
那就解释的通了，这个 bug 从 v4.1.0 开始被修掉了。我还以为是之后才出现的 orz
