### ISSUE TITLE
基建卡在会客室，软件继续执行下一步操作，游戏内无变化。

### ISSUE THREAD

**Issue by tachangan** [MaaAssistantArknights/MaaAssistantArknights#1307]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

每次执行到会客室，线索界面打开后，软件对游戏内的操作就会停止，但软件里的日志会显示已经进行接下来的操作，如领取日常奖励，游戏仍会停留在会客室线索界面。

### 日志文件

[Uploading asst.log…]()

**Comment by ABA2396** [comment]
日志没发上来

**Comment by ChildeRolando** [comment]
遇到相同的问题，在传递线索时会卡住，现在我都不开会客室换班

**Comment by MistEO** [comment]
> 遇到相同的问题，在传递线索时会卡住，现在我都不开会客室换班

也发下日志吧，楼主日志没发上来，现在没得排查问题（或者你重开一个 issue 也行

**Comment by tachangan** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9187484/asst.log)

@MistEO 抱歉，不是程序员，Github 使用得比较少，不太熟悉。辛苦老师。
