### ISSUE TITLE
在之前可以正常使用的情况下，打开应用会闪退

### ISSUE THREAD

**Issue by 3Th0u3and** [MaaAssistantArknights/MaaAssistantArknights#1308]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

之前下载了4.0.6版本，正常使用一段时间后，某天打开出现闪退情况，在能用与闪退期间，做过唯一的大动作是重新给电脑分区，但并未调整与该软件相关内容(都放在C盘，没有动),自此之后重新下载过4.08与4.10版本，都会直接闪退，

### 日志文件

没有找到相关软件日志，启动后直接闪退，估计没有生成日志文件

### 还有别的吗？

使用的是蓝叠模拟器，个人认为是电脑环境问题，如果可以，我可以在非工作日接受远程控制工具接受调整，万分感谢

**Comment by MistEO** [comment]
现在 v4.0.6 你还能用么？先确定一下是系统环境变化导致还是软件修改导致

如果 v4.0.6 现在你仍然能正常打开，麻烦测试一下具体是从哪个版本开始打不开了，例如：v4.0.7-beta.2 能正常打开，v4.0.7-beta.3 就打不开了。缩小一下排查范围

**Comment by MistEO** [comment]
仔细看了下你的描述，是说 v4.0.6 也不可用了？尝试按 [常见问题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#%E8%BD%AF%E4%BB%B6%E4%B8%80%E6%89%93%E5%BC%80%E5%B0%B1%E9%97%AA%E9%80%80) 重新配一遍环境试试吧，有时候环境这玩意比较玄学x

**Comment by 3Th0u3and** [comment]
v4.0.6 也已经不可用了，已经按常见问题配置过环境了VC++的是现安装的，然后 .NET的说已经有了更高版本的了，然后也下载了CPU-Z检查过CPU支持AVX指令集

**Comment by MistEO** [comment]
.NET 4.8 装一下，高版本和低版本不冲突

**Comment by 3Th0u3and** [comment]
![图片](https://user-images.githubusercontent.com/109887703/180645153-d64bb66f-f263-4b53-83e8-1d8e3cf59492.png)
已经不让安装了，还是会有这个问题，我现在在尝试下载代码到本地运行看看报什么错误然后到时候在这边实时反馈吧

**Comment by 3Th0u3and** [comment]
已经可以用了，我去下载了编译器拉了代码，然后跟着编译器的提示更新了环境，然后现在可以跑起来了，.net的那个环境我也百度着重新装了一次，不知道是哪个解决的，感谢！
