### ISSUE TITLE
关于MAA打肉鸽的趣味性

### ISSUE THREAD

**Issue by YinY1** [MaaAssistantArknights/MaaAssistantArknights#1309]
# 进一步提高肉鸽随机趣味性
![K8BZ1OEL0%7KFF RM6`L71P](https://user-images.githubusercontent.com/36351545/180633745-bd93dfdd-86d8-4bb2-a491-9a1262a4866b.png)

## 可行的方案：

1. 增加一个选项，勾选后在执行肉鸽过程中，MAA会掷色子决定接下来是否要进行降智操作
2. 牛牛醉酒后进行一个“全撤了”（如果干员全撤被判定为依然能赢的话）
3. //根据直播弹幕下干员、进行操作

**Comment by ChildeRolando** [comment]
我感觉MMA本来就很降智了，120级肉鸽大队5把过一次第三层，观众血压满中之满
