### ISSUE TITLE
ジャパンサーバー ベースの幹部は入れ替わらない

### ISSUE THREAD

**Issue by foxlesbiao** [MaaAssistantArknights/MaaAssistantArknights#1311]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

ジャパンサーバー ベースの幹部は入れ替わらない，また、FPを回収できない購入欄があります。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9175249/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/41581909/180635623-16e262b5-eb3e-4c22-a2b6-c497f67ba12d.png)
![image](https://user-images.githubusercontent.com/41581909/180635624-7eda5d80-2fcb-49d5-80db-0758fe023e65.png)

**Comment by MistEO** [comment]
The auto shift function of building is NOT supports JP client now, pls refer to [this doc](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/resource/global/YoStarJP/readme.md) , and if you want to help us to make it work, you can refer to [this](https://github.com/MaaAssistantArknights/MaaAssistantArknights/discussions/1212#discussioncomment-3176596)

**Comment by IranksAdral** [comment]
確かに今は他のサーバーにできることが少ない、ほぼ周回しかできないみたいで。。。すみません、yostarのせいかもしれないだから(^_^;)

**Comment by zzyyyl** [comment]
> The auto shift function of building is NOT supports JP client now, pls refer to [here](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/resource/global/YoStarJP/readme.md) , and if you want to help us to make it work, you can refer to [here](https://github.com/MaaAssistantArknights/MaaAssistantArknights/discussions/1212#discussioncomment-3176596)

也许我们可以在文档里加上 `暂不支持xxx` 的提示（？

**Comment by foxlesbiao** [comment]
> The auto shift function of building is NOT supports JP client now, pls refer to [here](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/resource/global/YoStarJP/readme.md) , and if you want to help us to make it work, you can refer to [here](https://github.com/MaaAssistantArknights/MaaAssistantArknights/discussions/1212#discussioncomment-3176596)

では、引き続き確認します。
