### ISSUE TITLE
[代发] 源石制造站换班异常

### ISSUE THREAD

**Issue by YipKei** [MaaAssistantArknights/MaaAssistantArknights#1317]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

心情阈值设置41%

基建自动换班后，源石制造站无人上班

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9175731/asst.log)

### 截图

![7U@(SXU65@ Z(8W5PO8V$2P](https://user-images.githubusercontent.com/53115298/180646049-d682dbea-b0d2-4b31-ad1a-f0b10d45100a.jpg)

![EMDTJQZ)R@5WLV 9DHPK(OR](https://user-images.githubusercontent.com/53115298/180646267-cdd5b2fa-e881-418b-bdf7-195c833d2cba.jpg)

### 还有别的吗？

蓝叠5.8.101.1001 N32

**Comment by MistEO** [comment]
v4.2.2-beta.1 修了一个基建滑动失效的问题，可能是这个原因，不过现在也没啥头绪总之先关了，之后再出现再来个日志看看（

**Comment by YipKei** [comment]
原问题的发现者提出了一个问题
他在近期将源石制造的干员补足了 6 人之后没有再出现过这种问题。

建议检查一下源石制造站和源石生产判断相关的代码，不知道为啥会产生这种现象。
之前他只有四个源石生产的干员的时候就必定出现这种现象。

**Comment by MistEO** [comment]
？？又没新日志 reopen 个啥，之前也改过其他滑动相关问题的

**Comment by YipKei** [comment]
> ？？又没新日志 reopen 个啥，之前也改过其他滑动相关问题的

不是滑动问题啊玛丽，问题已经定位到了，要新日志我现在去拿一份就好了。
四个源石干员变六个源石干员就解决问题。
然后修滑动问题之后他还是有那个问题，不过这个日志估计就被覆盖掉了。

**Comment by MistEO** [comment]
> > ？？又没新日志 reopen 个啥，之前也改过其他滑动相关问题的
> 
> 不是滑动问题啊玛丽，问题已经定位到了，要新日志我现在去拿一份就好了。 四个源石干员变六个源石干员就解决问题。 然后修滑动问题之后他还是有那个问题，不过这个日志估计就被覆盖掉了。

有必现方法？那来个日志康康_(:з」∠)_

**Comment by MistEO** [comment]
方便的话最好再来个录屏，看看具体是咋操作的

**Comment by YipKei** [comment]
> 方便的话最好再来个录屏，看看具体是咋操作的

我倒是想让他去复现啊，问题是干员的精二不可逆的，他原本四个源石加成干员，现在六个了，六个之后就没问题了。
你可能需要去找个同样有四个源石加成干员的志愿者来试了。
话说最初的那个日志分析不出是哪一步没丢上去吗。

**Comment by MistEO** [comment]
> > 方便的话最好再来个录屏，看看具体是咋操作的
> 
> 我倒是想让他去复现啊，问题是干员的精二不可逆的，他原本四个源石加成干员，现在六个了，六个之后就没问题了。 你可能需要去找个同样有四个源石加成干员的志愿者来试了。 话说最初的那个日志分析不出是哪一步没丢上去吗。

看到的都是正常计算然后正常选择了，唯一的不可控变量就是滑动，所以我怀疑是滑动的问题

**Comment by YipKei** [comment]
> 看到的都是正常计算然后正常选择了，唯一的不可控变量就是滑动，所以我怀疑是滑动的问题

怪事，那我去再跟他确认一下他的版本升级时间点和精二时间点，最坏的可能是，他白升了那两张卡，然后咱们白浪费了十几分钟。

**Comment by MistEO** [comment]
修了
