### ISSUE TITLE
掉落物识别错误

### ISSUE THREAD

**Issue by fastboot-rec** [MaaAssistantArknights/MaaAssistantArknights#1318]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

掉落物识别失败，时而成功，时而失败

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9175792/asst.log)

### 截图
![错误](https://user-images.githubusercontent.com/75794588/180647362-de44e57c-53f8-4923-aa1c-2cc5fc1a9d0f.png)

### 还有别的吗？

系统：windows 10 专业版 21H2
模拟器：蓝叠5.9.0.1061 N64

**Comment by ABA2396** [comment]
这种问题没图基本解决不了（霍夫圆赶紧提上日程）

**Comment by zzyyyl** [comment]
我记得以前会把识别不了的图自动存在 debug 文件夹下的？现在没这个功能了吗（

**Comment by fastboot-rec** [comment]
> 我记得以前会把识别不了的图自动存在 debug 文件夹下的？现在没这个功能了吗（

刚刚看了一下，确实有，都是令和能天使背景
![2022-07-24_19-51-52 412_raw](https://user-images.githubusercontent.com/75794588/180648454-520ca8f4-1a6d-4c35-8bae-4d01e28fa8a1.png)
![2022-07-24_19-54-51 176_raw](https://user-images.githubusercontent.com/75794588/180648457-92c7b7ad-48cc-4995-9779-5cc5439b1f83.png)
![2022-07-24_20-00-23 075_raw](https://user-images.githubusercontent.com/75794588/180648462-cf65695e-b69a-4dd0-ad77-d34ab8ba533f.png)
![2022-07-24_20-06-17 314_raw](https://user-images.githubusercontent.com/75794588/180648463-80d17e8c-c3a8-4ba1-806b-14b9052c50a1.png)
![2022-07-24_20-27-07 491_raw](https://user-images.githubusercontent.com/75794588/180648465-8ce6f21d-68cc-4bf7-a7bf-1ebb639f88b2.png)
![2022-07-24_20-28-36 249_raw](https://user-images.githubusercontent.com/75794588/180648469-a85042fe-1e18-4f2f-a7c1-0647d01e3728.png)
![2022-07-24_20-30-05 498_raw](https://user-images.githubusercontent.com/75794588/180648471-51740e7c-ccc2-48a9-86d5-16b9773c2f0d.png)
![2022-07-24_20-34-30 011_raw](https://user-images.githubusercontent.com/75794588/180648473-2275d372-443c-425f-bf9a-2577aadccccb.png)
的

**Comment by zzyyyl** [comment]
玛丽说现有算法寄了，可能修复得要一段时间了（

**Comment by ABA2396** [comment]
> 玛丽说现有算法寄了，可能修复得要一段时间了（

明明霍夫圆很好用）等玛丽加上就有了

**Comment by zzyyyl** [comment]
> > 玛丽说现有算法寄了，可能修复得要一段时间了（
> 
> 明明霍夫圆很好用）等玛丽加上就有了

学姐快来加霍夫圆！
