### ISSUE TITLE
关于自动编队中干员识别错误

### ISSUE THREAD

**Issue by AnnoyingFlowers** [MaaAssistantArknights/MaaAssistantArknights#1319]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，目前版本（v4.1.1）在`自动战斗beta`功能中还是会经常出现识别错误的问题。
我使用2560 * 1440分辨率测试了部分干员，结果如下

>Test01：风笛+艾丽妮+赫拉格+棘刺+山+史尔特尔+耀骑士临光+银灰+泥岩+塞雷娅+灰烬+能天使 √
>
>
>
>Test02：艾雅法拉+伊芙利特+凯尔希+令+浊心斯卡蒂+傀影+煌+帕拉斯+黑+澄闪+闪灵+夜莺 
>
>**傀影：默认二技能 识别为影**
>![image-20220721203206370](https://user-images.githubusercontent.com/89131639/180645372-c86edbd3-a0a1-46bd-9a45-e2431242c5db.png)
>
>
>
>Test03：温蒂+极境+近卫阿米娅+幽灵鲨+白面鸮+华法琳+安洁莉娜+桃金娘+卡达+砾+陈+斯卡蒂
>
>**近卫阿米娅：默认二技能 识别为阿来娅**（有时候成功有时候失败）
>![image-20220721205105767](https://user-images.githubusercontent.com/89131639/180645401-16b488f1-2038-48dd-b8c3-153f4bd51a30.png)
>
>
>
>Test04：年+星熊+早露+刻俄柏+流明+铃兰+夜半+拉普兰德+羽毛笔+雷蛇+陨星+推进之王
>
>**推进之王：默认三技能 识别为推进之主**
>![image-20220721212547414](https://user-images.githubusercontent.com/89131639/180645412-b957fa6c-2cb2-4c26-a21b-72db9d634df4.png)
>
>
>
>Test05：瑕光+麦哲伦+德克萨斯+絮雨+苏苏洛+孑+琴柳+焰尾+W+卡涅利安+夕+歌蕾蒂娅
>
>**夕：默认一技能 识别为多**
>![image-20220721215940286](https://user-images.githubusercontent.com/89131639/180645420-77c1a9c5-43bd-4db7-841b-7b3b1a4b998a.png)
>
>**默认二技能 识别为岁**
>![image-20220721221855813](https://user-images.githubusercontent.com/89131639/180645435-e0725a93-73e4-415f-a6b4-ccf02ab3c4a9.png)
>
>**默认三技能 识别为多**
>![image-20220721222318899](https://user-images.githubusercontent.com/89131639/180645441-a87b62c4-f945-4514-844d-f66ee7b055f2.png)
>
>**W：默认三技能 识别为小写w**（没错小写w它也不认）
>![image-20220721222244752](https://user-images.githubusercontent.com/89131639/180645445-143024fc-b6d0-47e9-b7c0-90018ea83c5e.png)
>
>
>
>Test06：术士阿米娅+蓝毒+调香师+伊桑+桑葚+森蚺+菲亚梅塔+莫斯提马+阿+老鲤+水月+初雪 √
>
>
>

还有很多干员没有测试（而且听说夕还能被识别成年），为了根除这些问题，我认为只加替换是不够的，我的**建议**有如下两点：
- **使用字典/枚举类，要求识别出的文字经过替换以后，只在字典/枚举类中选择，避免出现不存在的干员名。**
![image](https://user-images.githubusercontent.com/89131639/180646539-c9a03347-da6c-4c2d-adef-10bc5a427c81.png)

- **调整ocr的识别范围。**
    - 只识别这两条范围里的
![TZ$RV1YJV2_5632 5_ O _8](https://user-images.githubusercontent.com/89131639/180646453-25351d1f-06ef-44ba-a732-d3f83cbc7cd7.png)

    - 或者将其他会影响识别的部分做遮挡
![QQ截图20220724202024](https://user-images.githubusercontent.com/89131639/180646760-6db81760-4d34-4b55-be78-d464c006fb20.png)

**（还有作战中的识别也可能会出错，我还没有想好怎么根除，因为这还涉及到干员皮肤的颜色，也许对截图调整对比度、灰度处理会有效果。）**

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9175684/asst.log)
（此日志只展示了一部分）

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1232  然后真的出问题了 (
