### ISSUE TITLE
关于信用商店购买优先度的问题

### ISSUE THREAD

**Issue by YuricaZRAN** [MaaAssistantArknights/MaaAssistantArknights#1322]
### 说说你遇到的问题？

我设置了优先购买的商品之后，不管有没有打折都会优先购买同一种商品，有些时候就会买一些性价比非常低的东西。
现在的逻辑应该是：假如设置了AB两个打折商品，购买时就会买A(打折)→买A(没打折)→买B(打折)→买B(没打折)→......

### 有什么好的想法？

希望就是可以设置一下优先购买打折的商品。
运行逻辑大概是：设置AB为打折商品，买A(打折)→买B(打折)→买A(没打折)→买B(没打折)→......
这样应该就能买到更多性价比高的材料

**Comment by YipKei** [comment]
我记得玛丽说过，打折不好识别（至少他当时是这么说的）

我当初提过引入一图流价值表的建议来着，他是这么说的。

**Comment by YuricaZRAN** [comment]
> 我记得玛丽说过，打折不好识别（至少他当时是这么说的）
> 
> 我当初提过引入一图流价值表的建议来着，他是这么说的。

或者设置成优先购买第一排的商品？因为打折商品会默认排在前面，这样就可以优先买到打折的了

**Comment by MistEO** [comment]
不填优先购买就好了。。正常每天的信用是足够支持把所有打折商品买完的

**Comment by YuricaZRAN** [comment]
> 不填优先购买就好了。。正常每天的信用是足够支持把所有打折商品买完的

明白了

**Comment by MistEO** [comment]
那我关了哦（
