### ISSUE TITLE
识别干员后“安洁莉娜”被二次识别（类似于召唤物）导致部署失败

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#1323]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

RT

### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9178276/asst.-.log)
最近5分钟

### 截图

![image](https://user-images.githubusercontent.com/74061867/180705331-519467da-d267-4c06-a321-f5b0ec673f2e.png)

### 还有别的吗？

使用的脚本：
[北原冰封废城_泥岩+闪灵+白面鸮+拉普兰德+艾雅法拉+塞雷娅+煌+伊芙利特+安洁莉娜 (1).json.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9178287/_.%2B.%2B.%2B.%2B.%2B.%2B.%2B.%2B.1.json.txt)
由于json不让上传，请删除最后的.txt后缀
该脚本未上传maa作业群，仅为个人测试

**Comment by ntgmc** [comment]
需要注明的是，这里的杰哥是借的

**Comment by MistEO** [comment]
看了一下是因为洁哥太红了，被识别成 cd 中了。。

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/5565d5ad0a313c0786bfb5555031c2e95d1b1ace fixed
