### ISSUE TITLE
模拟器无法自动连接

### ISSUE THREAD

**Issue by fastboot-rec** [MaaAssistantArknights/MaaAssistantArknights#1330]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

模拟器无法自动连接，以前可以自动搜索模拟器的adb路径，现在不行了，已使用管理员权限

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9186564/asst.log)

### 截图

![无法自动连接](https://user-images.githubusercontent.com/75794588/180924366-651e5a3e-231f-47ee-bae2-723311501702.png)

### 还有别的吗？

系统：Windows10 专业版 21H2
模拟器：蓝叠5.9.0.1061 N64

**Comment by ryuujo1573** [comment]
你需要找出adb的路径，或者设置adb所在目录（一般为platform-tools）的PATH变量并在软件设置中正确配置，
如
![image](https://user-images.githubusercontent.com/16525512/180926073-991cbf26-cc3a-453b-9d06-4124c8819c92.png)
模拟器之间的区别不重要，主要是adb是否开启并正确连接

**Comment by fastboot-rec** [comment]
> 你需要找出adb的路径，或者设置adb所在目录（一般为platform-tools）的PATH变量并在软件设置中正确配置， 如 ![image](https://user-images.githubusercontent.com/16525512/180926073-991cbf26-cc3a-453b-9d06-4124c8819c92.png) 模拟器之间的区别不重要，主要是adb是否开启并正确连接

这个我是知道的，但之前MAA可以自动识别模拟器自带adb路径，玛丽应该没删这个功能吧🤔

**Comment by MistEO** [comment]
看看任务管理器里进程名叫啥

**Comment by fastboot-rec** [comment]
> 看看任务管理器里模拟器的进程名叫啥，报这个错就是进程名没抓到

![image](https://user-images.githubusercontent.com/75794588/181169180-6491e84a-248f-4f0b-893a-d8a38177410c.png)

**Comment by ryuujo1573** [comment]
> 

这个不是进程名哦，进程名应该转到详细信息

**Comment by fastboot-rec** [comment]
> > 
> 
> 这个不是进程名哦，进程名应该转到详细信息

![image](https://user-images.githubusercontent.com/75794588/181177609-359918ac-9ba9-4426-9ddb-4e0f7057db7d.png)
是这两个吗？

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
