### ISSUE TITLE
[HTTP 接口开关] 增加HTTP接口，并在设置中提供简单接口配置（如端口号和开关）

### ISSUE THREAD

**Issue by ryuujo1573** [MaaAssistantArknights/MaaAssistantArknights#1331]
### 说说你遇到的问题？

我使用的BlueStack 5 Hyper-V版本，adb端口随启动随机选择，官方Reddit回复表示暂时无解。

于是想使用python脚本扫描一下IANA动态端口，找到并尝试使用adb连接，连接成功后再使用MAA进一步操作。

### 有什么好的想法？

我需要使用到的：[HTTP接口](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/src/Java/Maaj/Readme.md#%E6%8E%A5%E5%8F%A3%E5%90%8D%E7%A7%B0-%E5%88%9B%E5%BB%BA%E8%BF%9E%E6%8E%A5)
这样可以避免每次使用都手动：打开蓝叠设置 - 查看adb端口 - 打开MAA设置 - 修改端口号 - LinkStart!

### 其他内容

想法参考Clash For Windows的灵活设计

**Comment by MistEO** [comment]
这个用不了么 [蓝叠模拟器国际版 Hyper-V 版本](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.md#-%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E5%9B%BD%E9%99%85%E7%89%88-hyper-v-%E7%89%88%E6%9C%AC)

**Comment by ryuujo1573** [comment]
> 这个用不了么 [蓝叠模拟器国际版 Hyper-V 版本](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.md#-%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E5%9B%BD%E9%99%85%E7%89%88-hyper-v-%E7%89%88%E6%9C%AC)

这个解决了问题，谢谢。没有认真读文档
