### ISSUE TITLE
AsstDestroy的签名可能导致调用方野指针

### ISSUE THREAD

**Issue by enpitsuLin** [MaaAssistantArknights/MaaAssistantArknights#1335]
还是写rust绑定的测试发现的😑

因为不太会C以为是rust问题，研究好一会还去rust社区[提问](https://rustcc.cn/article?id=54d1c752-e12c-4174-9a58-5944f38f81ce) 

指针做形参并不会改变实参的值，rust调用的话自己处理是直接传指针引用就可以解决的，实现代码不需要改，但是源码中的函数签名可能会导致bindgen自动生成的绑定在使用时出现野指针。

跑了自带的TestCaller也是一样的，改下签名就没问题了~~甚至怀疑GUI程序也有这个问题~~

~~所以之前好奇为什么C调用参考还需要自己手动置null，明明实现都做了~~

**Comment by MistEO** [comment]
想解决野指针确实需要传二级指针进去，不过感觉大家用 c api 可能都习惯了，写的时候没考虑这么多，因为 C 一般 delete 或者 free 完都是习惯性置一下 NULL，C 调用里的手动 NULL 也是基于这种习惯。

现在改可能不好改了，各个语言接口集成都要动，会被打的（bushi

**Comment by enpitsuLin** [comment]
积重难返确实，不过软件工程就是这样啦 so sad🥲
