### ISSUE TITLE
资深干员 公招识别出错

### ISSUE THREAD

**Issue by CoffeeRong** [MaaAssistantArknights/MaaAssistantArknights#1336]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

公招招募时有“资深干员”的Tag，软件已经识别出Tag，但是在选择时发生错误，并没有选上该Tag。在软件窗口中显示已确认招募，但是在模拟器中，仍然停止在是否确认招募的界面（方舟会再次确认没有选上资深干员Tag，是否继续招募）【本人手残点了确认】希望帮忙看下是BUG还是本人软甲设置的原因，并且剩下的任务直接完成了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9194962/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/45674719/181151143-993abc9f-fb40-47b4-8731-eea51c1e6fd6.png)

### 还有别的吗？

蓝叠模拟器国际版，WIN11 21H2，I7-9750H 16G 1660Ti
![image](https://user-images.githubusercontent.com/45674719/181151722-4b73c1ae-2f5c-4188-aa22-9d774719fdde.png)

**Comment by ABA2396** [comment]
召唤必出梅尔，因为深海色寻访限定，所以选一个召唤就能出5星

**Comment by MistEO** [comment]
召唤也是 5 星，而且省龙门币一点。

所以设置里自动 5 星的选项默认是不勾选的

**Comment by ABA2396** [comment]
虽然这个日志也没发上来（）

**Comment by MistEO** [comment]
不过话说回来这个问题是不是可以聚焦在，有 召唤 + 资深 的情况下，公招报错卡住？

**Comment by CoffeeRong** [comment]
但是为什么后面的任务都显示完成呢
游戏界面是卡在是否招募界面

**Comment by CoffeeRong** [comment]
日志重新发了（）

**Comment by horror-proton** [comment]
> 不过话说回来这个问题是不是可以聚焦在，有 召唤 + 资深 的情况下，公招报错卡住？
> 
> cc @horror-proton 新版要不要顺便修了这个（

这个我前几天在发电群里问了好像群友说召唤刷黄票效率高, 我就不知道怎么改了, pr 里可以找到一个 TODO

**Comment by zzyyyl** [comment]
> > 不过话说回来这个问题是不是可以聚焦在，有 召唤 + 资深 的情况下，公招报错卡住？
> > cc @horror-proton 新版要不要顺便修了这个（
> 
> 这个我前几天在发电群里问了好像群友说召唤刷黄票效率高, 我就不知道怎么改了, pr 里可以找到一个 TODO

不如直接两个tag都选上

**Comment by CoffeeRong** [comment]
> > > 不过话说回来这个问题是不是可以聚焦在，有 召唤 + 资深 的情况下，公招报错卡住？
> > > cc @horror-proton 新版要不要顺便修了这个（
> > 
> > 
> > 这个我前几天在发电群里问了好像群友说召唤刷黄票效率高, 我就不知道怎么改了, pr 里可以找到一个 TODO
> 
> 不如直接两个tag都选上 或者识别一下确认招募的界面？

软件里进度日志写一句召唤更好，选择召唤之类的？

**Comment by zzyyyl** [comment]
> > > > 不过话说回来这个问题是不是可以聚焦在，有 召唤 + 资深 的情况下，公招报错卡住？
> > > > cc @horror-proton 新版要不要顺便修了这个（
> > > 
> > > 
> > > 这个我前几天在发电群里问了好像群友说召唤刷黄票效率高, 我就不知道怎么改了, pr 里可以找到一个 TODO
> > 
> > 
> > 不如直接两个tag都选上 或者识别一下确认招募的界面？
> 
> 软件里进度日志写一句召唤更好，选择召唤之类的？

有写啊，你界面上不是显示选了召唤吗

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/902 
比较简单的改法就是直接修改排序规则, 把有资深的组合强制排到前面

**Comment by zzyyyl** [comment]
> #902 比较简单的改法就是直接修改排序规则, 把有资深的组合强制排到前面

我觉得行，识别确认招募的界面感觉可能有误操作的风险（
