### ISSUE TITLE
重启蓝叠模拟器HyperV后无法正常连接

### ISSUE THREAD

**Issue by LeoQ7** [MaaAssistantArknights/MaaAssistantArknights#1337]
### 说说你遇到的问题？

蓝叠模拟器HyperV版每次重新启动模拟器会使用随机的新的ADB端口。
目前读取配置文件的逻辑在https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/a31ff2429e710cca84f7a23ba8ba72fe55aebced/src/MeoAsstGui/Helper/AsstProxy.cs#L818 实现。
而如果重启模拟器后，没有关闭MAA的话，`m_inited`为true，会走到https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/a31ff2429e710cca84f7a23ba8ba72fe55aebced/src/MeoAssistant/Controller.cpp#L360 处的逻辑尝试重连。
重连20次失败后，才可以再次点击停止和LinkStart，使用新的端口信息进行连接

### 有什么好的想法？

希望能够在重试时实现端口信息的更新或是提供按钮供用户手动重新初始化m_inited、端口信息等。

**Comment by zzyyyl** [comment]
#1277
