### ISSUE TITLE
肉鸽关卡雕匠与石像卡死

### ISSUE THREAD

**Issue by LuffYH** [MaaAssistantArknights/MaaAssistantArknights#1343]
### 问题描述

奶阻挡了敌人，孑哥一直扣费，导致无法部署干员击杀敌人

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9200553/asst.log)

### 截图

![0C }Q7O6NB3FFRNZDTP%R7Y](https://user-images.githubusercontent.com/28567642/181288874-24ac51f2-fb48-42ea-8283-5941508cb75e.png)

**Comment by MistEO** [comment]
等五分钟就全撤了
