### ISSUE TITLE
奇怪的基建问题(为什么我这边基建好像奇妙的不稳定)

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaAssistantArknights#1346]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

昨天晚上的换班, 换出了  温蒂 某个exp+30% 断罪者, 也就是45%的效率(应该是asst.log.bak吧)

今早7点的换出了四月+巫恋+龙舌兰的组合以及把铃兰放进中枢

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9204404/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9204405/asst.log)

### 还有别的吗？

蓝叠国际版 5.5.100.1040 N64

![image](https://user-images.githubusercontent.com/72590023/181397725-03387659-1e16-4a9c-9a52-597f1ebd1bce.png)
看了一下, 中枢这边铃兰排的还是挺近的, 会不会是多划了一下什么的

**Comment by MistEO** [comment]
v4.2.2-beta.1 修了一个基建滑动失效的问题，可能是这个原因，不过现在也没啥头绪总之先关了，之后再出现再来个日志看看（
