### ISSUE TITLE
公招遇到小车tag无法完成公招任务

### ISSUE THREAD

**Issue by down-one** [MaaAssistantArknights/MaaAssistantArknights#1347]
### 说说你遇到的问题？

公招遇到小车tag，软件不会招募，但是公招次数会加一，有的时候四个位置都有小车tag，一次公招都不执行

### 有什么好的想法？

对于我这种老咸鱼来说，小车潜能早就已经满了，希望增加一个选项，忽略小车tag。
另外我建议增加一个选项，当四个位置在公招，但是没有完成指定的公招次数时，可以自动使用招募卷以完成设定的公招次数

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/181401754-c6201189-b86b-4447-abbe-03baa5018cb1.png)
