### ISSUE TITLE
信用商店中卡住

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#1349]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Hi Maa Team,

模拟器：MUMU
在信用商店中仅购买部分商品便停止，未完全购买非黑名单的打折商品，剩余信用大于300，停止在商店界面，后续Award任务显示完成。
bug已经多次出现。
忘记截图商店了，你们要是要商店截图的话我明天看看是不是还会出现。

Regards,
kxdxzr

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9205939/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/74366156/181433045-c1c948fa-c62a-4d8e-9882-e5c18ba1545d.png)

**Comment by kxdxzr** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9205920/asst.log)
emmm我是不是没传上去log文件……

**Comment by kxdxzr** [comment]
![MuMu20220802125946](https://user-images.githubusercontent.com/74366156/182282500-6d893404-51cc-4fd6-bfb7-be6401d3b04e.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9238732/asst.log)
重现了，商店的截图和log

**Comment by kxdxzr** [comment]
Hi Maa Team,

版本号：v4.2.2
bug又一次出现。
卡住的画面：
![MuMu20220805211126](https://user-images.githubusercontent.com/74366156/183066071-1b192ed1-90c9-430e-9f08-840fa260aa7e.png)
商店画面：
![MuMu20220805211320](https://user-images.githubusercontent.com/74366156/183066171-6b43c302-4287-4891-92d4-d75332263d87.png)
软件截图：
![image](https://user-images.githubusercontent.com/74366156/183066293-b2850a80-3b1c-4ff6-833b-0cd6920831b8.png)
Log 文件：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9268077/asst.log)

Regards,
kxdxzr

**Comment by kxdxzr** [comment]
考虑到我在海外所以我觉得可能是由于卡顿导致的

**Comment by MistEO** [comment]
知道卡在哪了，那问题就好办的多了

**Comment by MistEO** [comment]
![Screenshot_2022 08 08_22 26 28 287](https://user-images.githubusercontent.com/18511905/183441407-a09a8e2b-8da0-4131-9b1a-78646eb63a15.png)

初步怀疑是在这个界面 `正在提交神经网络` 时间过长导致的
