### ISSUE TITLE
任务完成未跳出提示

### ISSUE THREAD

**Issue by beastvl** [MaaAssistantArknights/MaaAssistantArknights#1355]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

任务完成不跳出提示

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9210445/asst.log)

**Comment by MistEO** [comment]
啥系统？看一下准确的版本号，另外你语言和时区设置之类的有改过么

**Comment by beastvl** [comment]
![image](https://user-images.githubusercontent.com/103806099/181574246-7eab1ce4-59ba-4463-9c28-127a2091fb07.png)

版本	Windows 11 专业版
版本	21H2
安装日期	‎2022/‎2/‎13
操作系统版本	22000.527
体验	Windows 功能体验包 1000.22000.527.0

**Comment by beastvl** [comment]
版本	Windows 11 专业版
版本	21H2
安装日期	‎2022/‎2/‎13
操作系统版本	22000.527
体验	Windows 功能体验包 1000.22000.527.0
![image](https://user-images.githubusercontent.com/103806099/181574501-410c476c-5533-41ca-b207-d6fb845f621b.png)
区域和语言我一直保持这样的

**Comment by MistEO** [comment]
只有任务完成不跳出提示？其他的信息提示么

另外 MAA 设置里弹出通知的选项勾了么

**Comment by zzyyyl** [comment]
我觉得我可能也有，但是点进通知里面能看到MAA的消息提示，我就一直以为是我没注意到弹出的通知（

**Comment by MistEO** [comment]
> 我觉得我可能也有，但是点进通知里面能看到MAA的消息提示，我就一直以为是我没注意到弹出的通知（

是不是开了专注/勿扰模式

**Comment by cglcv** [comment]
![image](https://user-images.githubusercontent.com/35825310/181771240-137b057d-5da5-4f93-bd38-ad396f2ab1a3.png)
开全屏工作、游戏（甚至maa执行时模拟器开了全屏）时系统有可能会自动开启专注模式，如果这时候maa任务完成自动退出了操作中心中maa的通知还会自动删除
于是就会有一种maa根本没弹出过通知的感觉
如果想让maa在专注模式下继续弹出通知可以把maa添加到专注助手的高优先级列表中，并把专注助手的规则调成仅高优先级
![image](https://user-images.githubusercontent.com/35825310/181774215-ce6f70a6-997e-4393-91ab-04208386c7f8.png)

**Comment by beastvl** [comment]
win11&nbsp;
版本	Windows 11 专业版
版本	21H2
安装日期	‎2022/‎2/‎13
操作系统版本	22000.527
体验	Windows 功能体验包 1000.22000.527.0




语言在用maa后没改过




cjjmgame
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 晚上11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 任务完成未跳出提示 (Issue #1355)





 
啥系统？看一下准确的版本号，另外你语言和时区设置之类的有改过么
