### ISSUE TITLE
蓝叠模拟器多开时，无法正常使用

### ISSUE THREAD

**Issue by xiaoyv404** [MaaAssistantArknights/MaaAssistantArknights#1356]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

两个 MaaAssistantArknights 客户端同时打开且同时链接不同的模拟器，会提示模拟器断开正在重试
甚至 MaaAssistantArknights 可能会崩溃

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9210846/asst.log)

### 还有别的吗？

使用了 #286 的方法，把助手的整个文件夹复制多份

**Comment by ABA2396** [comment]
手动填写了不同的端口号了吗

**Comment by xiaoyv404** [comment]
> 手动填写了不同的端口号了吗

是的

**Comment by xiaoyv404** [comment]
我刚刚去测试了一下手动用adb链接。。。好像也会导致这个问题

**Comment by xiaoyv404** [comment]
能告诉我这个怎么解决吗。。。qwq

**Comment by xiaoyv404** [comment]
![image](https://user-images.githubusercontent.com/63290381/181565098-ad2b567c-c502-495a-b725-23f66d3b7887.png)
我尝试了使用常见问题页面内下载的adb，问题依旧

**Comment by ABA2396** [comment]
啥模拟器，看着不像是MAA的问题  ~~你手动都连不上MAA连不上也正常吧~~

**Comment by xiaoyv404** [comment]
> 啥模拟器，看着不像是MAA的问题 ~你手动都连不上MAA连不上也正常吧~

蓝叠加MuMu，用蓝叠多开也是一样（ ~我也觉得，我在排查问题~

**Comment by xiaoyv404** [comment]
我用adb链接手机以后MAA也出现了断连。。。真奇怪

**Comment by xiaoyv404** [comment]
我倒是有成功过一次，就两个都连上了

**Comment by ABA2396** [comment]
这个一直都没动过，我试了下也是能用的（x）

**Comment by xiaoyv404** [comment]
> 这个一直都没动过，我试了下也是能用的（x）

坏

**Comment by xiaoyv404** [comment]
> 用同一个 adb 试试，adb 好像会踢掉其他版本不同的 adb 进程

好的

**Comment by xiaoyv404** [comment]
![image](https://user-images.githubusercontent.com/63290381/181570879-c689f788-6618-4bab-a824-9ccb175ea942.png)
确实是不同adb

**Comment by xiaoyv404** [comment]
可以了！谢谢各位大佬

**Comment by xiaoyv404** [comment]
那我先close这个 issue了

**Comment by xiaoyv404** [comment]
hummm，但是还是再出问题

**Comment by xiaoyv404** [comment]
多开不同模拟器是可以，但是用蓝叠的多开就不能连接了

**Comment by xiaoyv404** [comment]
![like this](https://user-images.githubusercontent.com/63290381/181573488-0557676a-afbd-445c-bbba-e31f30a66014.png)

**Comment by YipKei** [comment]
> ![like this](https://user-images.githubusercontent.com/63290381/181573488-0557676a-afbd-445c-bbba-e31f30a66014.png)

蓝叠的多开在adb的使用上好像有个问题，就是子模拟器抓取时需要依赖根模拟器来启动adb。
试下根模拟器和子模拟器同时打开，然后先启动对应子模拟器的MAA，再启动根模拟器的MAA。

**Comment by xiaoyv404** [comment]
> 蓝叠的多开在adb的使用上好像有个问题，就是子模拟器抓取时需要依赖根模拟器来启动adb。 试下根模拟器和子模拟器同时打开，然后先启动对应子模拟器的MAA，再启动根模拟器的MAA。

好的，十分感谢

**Comment by xiaoyv404** [comment]
> > ![like this](https://user-images.githubusercontent.com/63290381/181573488-0557676a-afbd-445c-bbba-e31f30a66014.png)
> 
> 蓝叠的多开在adb的使用上好像有个问题，就是子模拟器抓取时需要依赖根模拟器来启动adb。 试下根模拟器和子模拟器同时打开，然后先启动对应子模拟器的MAA，再启动根模拟器的MAA。

我尝试了一下这个方式 ，可是似乎不行，还是连接失败
