### ISSUE TITLE
肉鸽模式蓝毒会选自动触发的1技能，但会一直尝试开技能

### ISSUE THREAD

**Issue by et2012** [MaaAssistantArknights/MaaAssistantArknights#1357]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽模式中，蓝毒会选自动触发的1技能，但会一直点蓝毒，尝试开技能。

时间点：
2022-07-28 22:07:45.222 选择了蓝毒
2022-07-28 22:12:44.592 进入大盗当头
2022-07-28 22:18:28 战斗失败

地图：大盗当头

站位大致如下：

德狗  山   (蓝门)
         <-蓝毒

山带的2技能，蓝毒1技能，德狗2技能。
有时候也会反复开关山的技能，不知道是不是因为山和蓝毒站得接近，其实是想点山，结果一直在点蓝毒。

### 日志文件

github 日志一直上传失败，我传到百度盘了

链接：https://pan.baidu.com/s/1GTMLnNG1CkyKs9zsRXTYsg?pwd=vcte 
提取码：vcte

**Comment by zzyyyl** [comment]
估计跟 #1195 ，#1062 是一个问题

**Comment by et2012** [comment]
> 估计跟 #1195 ，#1062 是一个问题

应该是的，我先关闭这个 issue 了。
