### ISSUE TITLE
游戏没有奔溃，软件识别崩溃，然后重启失败任务

### ISSUE THREAD

**Issue by yangcunbiao** [MaaAssistantArknights/MaaAssistantArknights#1360]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://user-images.githubusercontent.com/45910752/181652736-59a8bc38-6d26-4e47-97cd-28a5e999da25.png)
之前的版本也有这样的情况，然后再次点击开始，就可以继续，但是上次更新完一直不行

### 日志文件

[Uploading asst.log…]()

### 还有别的吗？

雷电模拟器 ，win10 专业版

**Comment by MistEO** [comment]
你日志没传上来 orz

**Comment by zzyyyl** [comment]
#964 有人提过类似的问题，但是发生原因应该不一样（

**Comment by yangcunbiao** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9276816/asst.log)

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
