### ISSUE TITLE
基建换班经常卡在“是否退出罗德岛基建”

### ISSUE THREAD

**Issue by zaiziw** [MaaAssistantArknights/MaaAssistantArknights#1361]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

设了凌晨1点和早上10点的定时任务，最近每天早上看就是卡在这个地方不知道为什么

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9215579/asst.zip)

### 截图

![Snipaste_2022-07-29_10-30-26](https://user-images.githubusercontent.com/27818332/181670443-2448c93e-73a7-4f8d-8257-cf67dd971800.png)

**Comment by zzyyyl** [comment]
我没看日志，估计跟 #1180 是一个问题

如果真的是同一个问题的话谁看了日志的记得标一个 `duplicate`

**Comment by MistEO** [comment]
v4.2.2-beta.1 修了一个基建滑动失效的问题，可能是这个原因，不过现在也没啥头绪总之先关了，之后再出现再来个日志看看（
