### ISSUE TITLE
肉鸽商店购买升级干员类藏品后卡住

### ISSUE THREAD

**Issue by zhangweijian97** [MaaAssistantArknights/MaaAssistantArknights#1364]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

商店购买了折戟-典训（近卫升级道具），然后并没有干员可以升级。卡在了选择干员进行升级的页面。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9215661/asst.log)

### 截图

忘记截图，手动点了确定招募，期望他能继续跑，结果不动。

### 还有别的吗？

蓝叠国际版，win10

**Comment by zzyyyl** [comment]
与 #1030 类似
