### ISSUE TITLE
肉鸽bug

### ISSUE THREAD

**Issue by zhangweijian97** [MaaAssistantArknights/MaaAssistantArknights#1365]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

高台干员数量大于地图中高台数量，多出来的干员，一直放，但是放不下，但就一直放，依次尝试每一个高台，无限循环。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9215751/asst.log)

### 截图

![Screenshot_2022 07 29_11 09 20 971](https://user-images.githubusercontent.com/52686008/181675091-37122460-2abf-4923-a7b8-43a97cd9f15d.png)

**Comment by zzyyyl** [comment]
Duplicate of #1244

**Comment by MistEO** [comment]
这个问题不少人说了，其实不难修，参考一下自动战斗那边识别是否是同一个干员的逻辑，如果下场了就删掉对应的格子占用就好了。但主要是这并不影响肉鸽的实际结果，只是耽误一点点效率，~~然后我比较懒~~，所以暂时没有排在太高的优先级上

**Comment by MistEO** [comment]
修了
