### ISSUE TITLE
关于引入专业代码风格审查工具的必要性与可行性讨论

### ISSUE THREAD

**Issue by LYZhelloworld** [MaaAssistantArknights/MaaAssistantArknights#1366]
### 说说你遇到的问题？

随着 MAA 团队的不断壮大，我们的产品迎来了一个新的里程碑。在此之上，无数的开发者都参与到了该项目中。在集思广益的同时，我们也应当注意到，新成员的不断加入为团队带来新鲜血液的同时，也带来了小小的问题，比如代码风格不统一。这种瑕疵虽然并不足以造成事故，但会令开发和维护变得稍许麻烦。以下是一个经典的例子：

```csharp
new Dictionary<string, int>()
{
  { "a": 1 },
  { "b": 2 }
}
```

最后一个项目（即`{ "b": 2 }`）在行尾无论有没有逗号时均不报错。如果将来新增了新的内容：

```csharp
new Dictionary<string, int>()
{
  { "a": 1 },
  { "b": 2 }，
  { "c": 3 }
}
```

那么在 Git 改动中势必会显示成两行改动，而：

```csharp
new Dictionary<string, int>()
{
  { "a": 1 },
  { "b": 2 },
}
```

只会造成一行改动。

当然，以上的案例只是冰山一角，具体情况还有更多。这些问题是自带的 `.editorconfig` 所不能解决的，因此可以考虑引入专业的代码风格审查器。

### 有什么好的想法？

我谨在此向团队推荐 [StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) 作为代码审查工具。作为本人所在单位以及本人个人项目所使用的工具，我相信其经得起时间的考验，能够担当此重任。

该工具的主要功能有：

1. 更为严格的代码风格审查，尽力确保所有人的风格保持一致。
2. 严格要求撰写正确的文档和注释，杜绝了添加新功能而不写注释的行为，以及注释与用法不符的现象。
3. 自定义文件头部版权标识注释，拥有比 `.editorconfig` 更为完善的定制功能。

主要检查的代码风格有：

1. 字符间距检查及空格使用
2. 可读性检查
3. 类成员顺序检查
4. 可维护性检查
5. 代码布局检查
6. 文档检查
7. 以及其它可能会用到的检查

参考文档

- https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/DOCUMENTATION.md
- https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md

**Comment by MistEO** [comment]
？谁提的谁写.jpg

**Comment by et2012** [comment]
StyleCopAnalyzers 好像只能检查 .NET 代码吧？Gui 项目没多少代码文件，需要代码审查的大概也就 ViewModel 和 Helper。
核心的 C++ 项目才是大坑。

**Comment by LYZhelloworld** [comment]
> StyleCopAnalyzers 好像只能检查 .NET 代码吧？Gui 项目没多少代码文件，需要代码审查的大概也就 ViewModel 和 Helper。 核心的 C++ 项目才是大坑。

@et2012 那个救不了，再见。

**Comment by cglcv** [comment]
我赞同引入专业代码风格审查工具的必要性，但Gui将来不是要迁移到Vue去吗？如果只检查Gui项目的话是不是不太必要？
~话说新UI啥时候能做好……~
