### ISSUE TITLE
肉鸽投资达到上限就会自动放弃本次探索

### ISSUE THREAD

**Issue by chenmodcm** [MaaAssistantArknights/MaaAssistantArknights#1367]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽投资达到上限就会自动放弃本次探索，设置选择的是“刷蜡烛，尽可能稳定的打更多层数“，也没勾上”源石锭达到上限停止“选项。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9216138/asst.log)

### 截图

![XXIB EM2O83N`R%ZHYVTZYS](https://user-images.githubusercontent.com/104850646/181684883-28cf8bc6-35ac-48cd-a2c8-ea18327114c1.png)
![(A@3YWLFY}FI8_739BVQ$JW](https://user-images.githubusercontent.com/104850646/181684902-1b48bcc1-15f1-4abf-8b74-015501e66699.png)

### 还有别的吗？

蓝叠国际版，win10，MAA版本号: v4.2.0-alpha.1

**Comment by MistEO** [comment]
看起来和 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1367 是同一个问题
