### ISSUE TITLE
定时任务无法开启模拟器

### ISSUE THREAD

**Issue by MouseWhite** [MaaAssistantArknights/MaaAssistantArknights#1369]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我用蓝叠模拟器定时任务结束后如果选择关闭模拟器，下次定时任务的话就会显示模拟器断开并且无法开启模拟器导致任务出错，奇怪的是假如我点停止然后重新开始任务，又能够正常开启模拟器了。感觉要隔一次失败之后才能开启成功一次

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9219823/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/17306018/181757643-acdc4dcf-1b3c-4e9b-bc4d-778a395b3954.png)

**Comment by ABA2396** [comment]
感觉定时任务应该加上启动模拟器装个设置，根据 `启动后自动开启模拟器` 的勾选状态判断就行了

**Comment by MouseWhite** [comment]
嗯 希望能形成 定时刷任务->结束关闭模拟器->下次定时自动开模拟器自动刷的循环，我的电脑开着模拟器的时候打游戏会很卡，最好能只有刷的时候开模拟器
