### ISSUE TITLE
公开招募三星确认的时间

### ISSUE THREAD

**Issue by miku1958** [MaaAssistantArknights/MaaAssistantArknights#137]
三星tag/不勾选，实测其实7个小时40分就够了，既省时间又省钱

**Comment by miku1958** [comment]
实测7个小时40分无tag也会出4星5星，人为感知概率和9个小时没区别

**Comment by MistEO** [comment]
不知道有没有大佬算过概率，但是如果设 7:40, 肯定会有很多人不同意。又不差那点龙门币为什么不把时间打满呢，假如有概率提升呢。所以这个不会去做的

**Comment by Yaklo** [comment]
> 不知道有没有大佬算过概率，但是如果设 7:40, 肯定会有很多人不同意。又不差那点龙门币为什么不把时间打满呢，假如有概率提升呢。所以这个不会去做的

事实是根本没区别，我740没词条也出过好几个五星，我认为时间影响的主要是词条是否被划掉的概率
