### ISSUE TITLE
特种干员被归类为 3★Tags

### ISSUE THREAD

**Issue by qianxu2001** [MaaAssistantArknights/MaaAssistantArknights#1371]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

[v4.2.0-alpha.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.2.0-alpha.1) 版本重构公招功能后遇到

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9221279/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/62287903/181792990-68825b9f-9350-4ace-a001-78714928fd15.png)

**Comment by MistEO** [comment]
日志没传上来 orz 再发一下

cc @horror-proton

**Comment by qianxu2001** [comment]
> 日志没传上来 orz 再发一下
> 
> cc @horror-proton

补上了

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/ba23af15889b2bc4042c846ca9719a87a61f6a9d 应该是这样
