### ISSUE TITLE
公招刷新时报错

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#1375]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

v4.2.0-alpha.3 版本，偶现问题

### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9223286/asst.-.log)

### 截图

![image](https://user-images.githubusercontent.com/18511905/181844878-34bf161a-a574-4f42-8e09-a1c822429bf2.png)

**Comment by MistEO** [comment]
手动点取消看了一下，应该是公招券没有了，然后出现这个问题

tag 和 9 小时是正常设置了的

![image](https://user-images.githubusercontent.com/18511905/181845103-809a0549-2585-4b8a-945d-0edb9936e339.png)

**Comment by MistEO** [comment]
```log
[2022-07-30 05:12:27.205][INF][Px7464][Tx8bdc] Failed to confirm current recruit config.
[2022-07-30 05:12:27.205][TRC][Px7464][Tx8bdc] asst::AutoRecruitTask::recruit_one | leave, 7786 ms
[2022-07-30 05:12:27.205][TRC][Px7464][Tx8bdc] asst::AutoRecruitTask::recruit_one | enter
[2022-07-30 05:12:27.205][INF][Px7464][Tx8bdc] recruit_index 1
```
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/780e1487fe3e68712d2a5ac03cabbf5f75e3c265/src/MeoAssistant/AutoRecruitTask.cpp#L187-L200

这里没有重新识别的逻辑，直接去点下一个槽位了（话说很早之前也是这种行为，后来好像改过，但我不记得了）。不过最好还是改成 每次画面有可能较之前不同时 的点击都是建立在重新识别的基础上的，不要用 `m_pending_recruit_slot` 类似这种的缓存

**Comment by MistEO** [comment]
```log
[2022-07-30 05:12:27.205][INF][Px7464][Tx8bdc] recruit_index 1
[2022-07-30 05:12:27.205][TRC][Px7464][Tx6bc0] asst::Controller::call_command | `C:\Program Files\BlueStacks_nxt\.\HD-Adb.exe -s 127.0.0.1:5555 shell input tap 1886 686` | enter
[2022-07-30 05:12:27.387][TRC][Px7464][Tx6bc0] Call ` C:\Program Files\BlueStacks_nxt\.\HD-Adb.exe -s 127.0.0.1:5555 shell input tap 1886 686 ` ret 0 , output size: 0
[2022-07-30 05:12:27.387][TRC][Px7464][Tx6bc0] asst::Controller::call_command | `C:\Program Files\BlueStacks_nxt\.\HD-Adb.exe -s 127.0.0.1:5555 shell input tap 1886 686` | leave, 182 ms
```

`1886 686` 大概在这里，正好点到刷新按钮了

![image](https://user-images.githubusercontent.com/18511905/181847066-2dd818ab-a450-4861-8e12-4a628f2db7a1.png)

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/874e06ccb85e962f7e40c7cf215431f02ea95cd6 我开始写的时候 `recruit_one()` 没有考虑确认按钮点击失败这种要求退出整个公招 Task 的错误, 现在应该勉强能绕过这个问题. 
如果每次回到公招主界面都重新识别的话看上去应该把 `m_start_buttons` 也去掉, 然后 `analyze_start_buttons` 每次只取一个结果?

**Comment by horror-proton** [comment]
类似这样? 
```diff
-   if (!m_use_expedited) { // analyze once only
-       if (!analyze_start_buttons()) return false;
-   }

    static constexpr size_t slot_retry_limit = 3;

    // m_cur_times means how many times has the confirm button been pressed, NOT expedited plan used
    while ((m_use_expedited || !m_pending_recruit_slot.empty()) && m_cur_times != m_max_times) {
        if (m_force_discard_flag) { return false; }
        if (m_slot_fail >= slot_retry_limit) { return false; }
        if (!check_recruit_home_page()) { return false; }
        if (m_use_expedited) {
            Log.info("ready to use expedited");
            if (need_exit()) return false;
            if (!recruit_now()) {
                m_force_discard_flag = true;
                return false;
            }
-           analyze_start_buttons();
        }
+       analyze_start_buttons();
        if (need_exit()) return false;
        if (!recruit_one())
            ++m_slot_fail;
        else
            ++m_cur_times;
    }
    return true;

```

**Comment by MistEO** [comment]
> 类似这样?
> 
> ```diff
> -   if (!m_use_expedited) { // analyze once only
> -       if (!analyze_start_buttons()) return false;
> -   }
> 
>     static constexpr size_t slot_retry_limit = 3;
> 
>     // m_cur_times means how many times has the confirm button been pressed, NOT expedited plan used
>     while ((m_use_expedited || !m_pending_recruit_slot.empty()) && m_cur_times != m_max_times) {
>         if (m_force_discard_flag) { return false; }
>         if (m_slot_fail >= slot_retry_limit) { return false; }
>         if (!check_recruit_home_page()) { return false; }
>         if (m_use_expedited) {
>             Log.info("ready to use expedited");
>             if (need_exit()) return false;
>             if (!recruit_now()) {
>                 m_force_discard_flag = true;
>                 return false;
>             }
> -           analyze_start_buttons();
>         }
> +       analyze_start_buttons();
>         if (need_exit()) return false;
>         if (!recruit_one())
>             ++m_slot_fail;
>         else
>             ++m_cur_times;
>     }
>     return true;
> ```
> 
> 然后去掉多余的 `m_start_buttons` 和 `m_pending_recruit_slot` 之类的, 然后干脆让 `analyze_start_buttons()` 返回一个 `std::optional<Rect>`?

那整一个？_(:з」∠)_
