### ISSUE TITLE
希望增加肉鸽刷开局藏品的功能

### ISSUE THREAD

**Issue by AllenDengMs** [MaaAssistantArknights/MaaAssistantArknights#1376]
### 有什么好的想法？

一些娱乐性的功能，比如：
1. 开局选异客，重复刷第一层商店，直到出现扩散之手。购买后，完成任务。
2. 重复刷第一层商店，直到出现金杯之酒。购买后，完成任务。
这样能体验天胡开局的快乐

**Comment by ABA2396** [comment]
Duplicate of #705
