### ISSUE TITLE
希望不自动将艾丽妮入住宿舍

### ISSUE THREAD

**Issue by 1838860816** [MaaAssistantArknights/MaaAssistantArknights#1377]
### 说说你遇到的问题？

艾丽妮的效果要持续在训练室才能生效 进入宿舍后技能就失效了

### 有什么好的想法？

希望将艾丽妮加入白名单 进入宿舍的时候不选中 或者干脆不将训练室的干员入住宿舍也挺好

**Comment by ABA2396** [comment]
Duplicate of #763
