### ISSUE TITLE
肉鸽黑名单

### ISSUE THREAD

**Issue by kongkongji** [MaaAssistantArknights/MaaAssistantArknights#1378]
比如我群奶练度比单奶高那么一丢丢，系统就会选择群奶而不是单奶，群奶在前期遇到某些关卡自动放的位置是奶不到人的，导致会输，所以希望作者添加一个肉鸽黑名单，可以把干员名字写在里面系统就不会选择他了。（就是给肉鸽添加一个干员黑名单）

**Comment by MistEO** [comment]
最新测试版干员攻击范围识别也加了，试试看吧
