### ISSUE TITLE
公招四个槽位都有人时报错

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantArknights#1379]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

两个问题
- [X] 界面显示 `出现错误` 的 l10n 大概漏了
- [X] 还有就是，在 @horror-proton 重构之前，四个槽位都满的时候我记得不会报错的

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9225566/asst.log)

### 截图

![IXNKKKK 1U$V9 8~$}2EO0E](https://user-images.githubusercontent.com/74587068/181879539-e2302186-bf38-4367-8994-61bb52ed5729.png)

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/91c1eb9513348c642a2a07902b8b4172bbe4faa1#diff-baa577c09c49d2b5ab4edfc819b3317809ec67c62a65c65068e97e4d28f71682L134-R136

看上去是因为这个 commit 里面有个笔误, 我应该 `return true` 而不是 `false`

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/6cf5bf0e01c815dd64ea38693be7e480b02cd5b8 公招过程之后可能还得改一下, 改过之后应该不需要这几行了, 不过这里还是先修一下

**Comment by zzyyyl** [comment]
This issue will be outdated when #1375 fixed.
