### ISSUE TITLE
肉鸽自定义干员：斑点 无法实现

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#1381]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

RT
我本来是想斑点+澄闪+克洛丝的
使用空格分开后是一样的效果

### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9225830/asst.-.log)

### 截图

![image](https://user-images.githubusercontent.com/74061867/181903137-babea51d-fc22-4499-be79-a13ff3685ebf.png)

### 还有别的吗？

![image](https://user-images.githubusercontent.com/74061867/181903160-d230a9cb-d4bc-4a6b-948a-d90544d7d026.png)

**Comment by MistEO** [comment]
只能填一个人名，比如你可以填 澄闪

另外有新版本了，可以更新一下

**Comment by ntgmc** [comment]
我填了斑点 没用QAQ
现在更新

**Comment by MistEO** [comment]
> 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

你看了么（

**Comment by ntgmc** [comment]
这是群文件能找到的最新版了￣□￣｜｜

**Comment by et2012** [comment]
可能是因为招募时不会往后翻页，第一页看不见某位干员就会认为没有这位干员。
因为按星级排序，斑点在最后。
同理，用招募券时也不会翻页，导致希望不够6点招募6星时，想招募点3星干员充数也无法实现。

**Comment by MistEO** [comment]
> 可能是因为招募时不会往后翻页，第一页看不见某位干员就会认为没有这位干员。
> 因为按星级排序，斑点在最后。
> 同理，用招募券时也不会翻页，导致希望不够6点招募6星时，想招募点3星干员充数也无法实现。
> 
> 楼主的问题有一个解决方案，但需要修改配置文件：
> resource 文件夹下有一个 roguelike_recruit.json
> 默认的职业招募顺序是这样：
> ```
>     "roles": [
>         "Warrior",
>         "Pioneer",
>         "Tank",
>         "Sniper",
>         "Caster",
>         "Special",
>         "Medic",
>         "Support",
>         "Alternate"
>     ],
> ```
> 即：近卫 > 先锋 > 重装 > 狙击 > 术师 > 特种 > 医疗 > 辅助 > 后备干员。
> 你可以把术师的优先级放到重装前面，就会优先招募术师（澄闪）并消耗掉希望，然后招募重装就会招募斑点了。
> 具体如下（注意备份，免得改出问题）：
> ```
>     "roles": [
>         "Warrior",
>         "Pioneer",
>         "Caster",
>         "Tank",
>         "Sniper",
>         "Special",
>         "Medic",
>         "Support",
>         "Alternate"
>     ],
> ```
> 

测试版已经可以翻页了

**Comment by et2012** [comment]
> > 可能是因为招募时不会往后翻页，第一页看不见某位干员就会认为没有这位干员。
> > 因为按星级排序，斑点在最后。
> > 同理，用招募券时也不会翻页，导致希望不够6点招募6星时，想招募点3星干员充数也无法实现。
> > 楼主的问题有一个解决方案，但需要修改配置文件：
> > resource 文件夹下有一个 roguelike_recruit.json
> > 默认的职业招募顺序是这样：
> > ```
> >     "roles": [
> >         "Warrior",
> >         "Pioneer",
> >         "Tank",
> >         "Sniper",
> >         "Caster",
> >         "Special",
> >         "Medic",
> >         "Support",
> >         "Alternate"
> >     ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 即：近卫 > 先锋 > 重装 > 狙击 > 术师 > 特种 > 医疗 > 辅助 > 后备干员。
> > 你可以把术师的优先级放到重装前面，就会优先招募术师（澄闪）并消耗掉希望，然后招募重装就会招募斑点了。
> > 具体如下（注意备份，免得改出问题）：
> > ```
> >     "roles": [
> >         "Warrior",
> >         "Pioneer",
> >         "Caster",
> >         "Tank",
> >         "Sniper",
> >         "Special",
> >         "Medic",
> >         "Support",
> >         "Alternate"
> >     ],
> > ```
> 
> 测试版已经可以翻页了，并且也不需要修改顺序

刚才试了一次，招募券招募重装时不会翻页。重装的默认顺序是：泥岩>塞雷娅>斑点>卡缇。
现有希望5点，出现重装招募券后直接取消招募了，第一页看不见斑点。

**Comment by MistEO** [comment]
我的意思是你自定义的干员是会翻页的_(:з」∠)_

**Comment by et2012** [comment]
> 我的意思是你自定义的干员是会翻页的_(:з」∠)_

OK~ 我理解错了。
不过还是希望有空把招募券翻页也实现一下，因为某些4/5星真的是浪费希望，还不如6星+3星。

**Comment by et2012** [comment]
初始招募也有点问题：

例如我初始近锋队，用月见夜测试，结果没有翻到最后一页，招了个阿米娅。

![image](https://user-images.githubusercontent.com/1037590/181919429-be8e974b-6461-4bc6-a98e-30c17e590dc1.png)
![Screenshot_2022 07 30_22 42 26 882](https://user-images.githubusercontent.com/1037590/181919478-6e0aaa04-8772-4ae0-aa47-fda45a0713ba.jpg)

**Comment by MistEO** [comment]
因为我觉得正常人不会开局要求选择 3、4 星的，所以翻的次数是有限制的。（不要点炒饭.jpg

**Comment by et2012** [comment]
> 因为我觉得正常不会开局要求选择 3、4 星的，所以翻的次数是有限制的。（不要点炒饭.jpg

所以楼主想招澄闪+斑点+克洛斯，还真的要改招募顺序，先招澄闪用掉一些希望才能实现，不然重装多一点确实是招不到斑点的。
或者可以加一个初始招募职业顺序的配置选项，不光是输入名字。

**Comment by MistEO** [comment]
> > 因为我觉得正常不会开局要求选择 3、4 星的，所以翻的次数是有限制的。（不要点炒饭.jpg
> 
> 所以楼主想招澄闪+斑点+克洛斯，还真的要改招募顺序，先招澄闪用掉一些希望才能实现，不然重装多一点确实是招不到斑点的。 或者可以加一个初始招募职业顺序的配置选项，不光是输入名字。

输入澄闪的话，就会先去术师里面招澄闪。接着才是重装，因为希望已经被澄闪用掉了，所以这时候斑点是在第一页

**Comment by MistEO** [comment]
即 maa 是会自动判断你输入 干员名 的职业的

**Comment by et2012** [comment]
> > > 因为我觉得正常不会开局要求选择 3、4 星的，所以翻的次数是有限制的。（不要点炒饭.jpg
> > 
> > 
> > 所以楼主想招澄闪+斑点+克洛斯，还真的要改招募顺序，先招澄闪用掉一些希望才能实现，不然重装多一点确实是招不到斑点的。 或者可以加一个初始招募职业顺序的配置选项，不光是输入名字。
> 
> 输入澄闪的话，就会先去术师里面招澄闪。接着才是重装，因为希望已经被澄闪用掉了，所以这时候斑点是在第一页

OK，理解了。
另外关于招募券翻页的问题，有个稍微简单一点的方案：如果当前页面没有符合条件的干员，则往后翻一页，只翻3次。
这样既能避免放弃招募，也能用3星或后备干员充数攒希望。
