### ISSUE TITLE
换下会客室干员后没有换上去

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaAssistantArknights#1383]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

发现换上会客室干员后没换上去

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9226197/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/72590023/181909671-8694b23c-e742-48c2-a504-d605894a27ac.png)

![image](https://user-images.githubusercontent.com/72590023/181909684-50be267c-2be0-42e8-86e5-ea9c95ccb0b0.png)

这是过了一个小时后的会客室截图, 考虑和线索满了有关?

(另外能不能加一个线索有几个后送好友的自定义, 不然没满没送人说不定一个小时后就满了)

### 还有别的吗？

蓝叠国际版 5.5.100.1040 N64

**Comment by one-pyy** [comment]
![image](https://user-images.githubusercontent.com/72590023/181909770-a452975d-9e81-43b9-a7b0-b6c4e7c46261.png)
另外还有这个桃金娘

![image](https://user-images.githubusercontent.com/72590023/181909791-bb6d92c5-9160-4ad5-b9af-d5baf0ee06e4.png)
这个泥岩


(总之就是奇奇怪怪的问题)

**Comment by MistEO** [comment]
v4.2.2 修了一些基建选人的问题，再试试看看还有没有出现了。

这个我先关了（
