### ISSUE TITLE
刷理智无法进行

### ISSUE THREAD

**Issue by swan-sw** [MaaAssistantArknights/MaaAssistantArknights#1386]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷理智的时候会显示“游戏崩溃，重新启动”，但实际上游戏并没有崩溃。于是程序会停止。
检查了日志，发现每次游戏崩溃的提示都出现在开启游戏两分钟整之后，推测是因为我的作战时间太长（或模拟器太慢导致加载时间太长），所以在开启后两分钟的时候还没有结束战斗，于是报错了？
可以允许自行更改这个时间嘛？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9227989/asst.log)
2022-07-31 10:54:51.019 及其后的2分钟

**Comment by MistEO** [comment]
看日志来说，你的电脑实在实在太卡了，我不知道是电脑的问题还是模拟器的问题，如果你电脑配置还不错，推荐换个模拟器试试。如果是电脑本身问题，可以参考 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/892 尝试修改一下 MAA 的配置

**Comment by swan-sw** [comment]
> 看日志来说，你的电脑实在实在太卡了，我不知道是电脑的问题还是模拟器的问题，如果你电脑配置还不错，推荐换个模拟器试试。如果是电脑本身问题，可以参考 #892 尝试修改一下 MAA 的配置

太感谢大佬了！我用的mumu和逍遥模拟器都很卡，可以麻烦大佬帮我看一下是不是电脑配置的问题嘛？确实是轻薄本不是游戏本，而且重装过一次

处理器	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz
机带 RAM	8.00 GB (7.85 GB 可用)

感谢！

**Comment by MistEO** [comment]
试试蓝叠国际版，使用说明里有推荐的。还不行就按 #892 这个改下配置吧
