### ISSUE TITLE
基建换班经常第一个制造站清空后不放人

### ISSUE THREAD

**Issue by qianxu2001** [MaaAssistantArknights/MaaAssistantArknights#1395]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建换班经常第一个制造站清空后不放人，只发生在第一个制造站，遇到过好几次

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9229084/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/62287903/182031774-a7066968-cee4-42c5-877b-baa7d99d5732.png)

**Comment by qianxu2001** [comment]
又遇到了，再补一个日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9235449/asst.log)

**Comment by MistEO** [comment]
v4.2.2-beta.1 修了一个基建滑动失效的问题，可能是这个原因，不过现在也没啥头绪总之先关了，之后再出现再来个日志看看（
