### ISSUE TITLE
这里是不是有个typo..本地build RelWithInfo 失败

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaAssistantArknights#1396]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/023d3685fcb5e5d1e50f52cc7b419db5bd0b6e30/src/MeoAssistant/DepotImageAnalyzer.cpp#L51

**Comment by Shawnsdaddy** [comment]
PS: 从代码直接建 issue 模板就无了。Interesting

**Comment by zzyyyl** [comment]
草，dsize

**Comment by MistEO** [comment]
草，这谁改的

**Comment by MistEO** [comment]
进行一个锅的甩

**Comment by lhhxxxxx** [comment]
焯，重构的时候没开asstdebug环境变量

**Comment by lhhxxxxx** [comment]
dev的issue fix了可以直接关掉吧
