### ISSUE TITLE
公招出小车时一直在同一槽位

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantArknights#1397]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

`v4.2.0-beta.1`

如图，不知道是一直在同一个界面没退出还是退出之后一直点第一个槽位，卡了四次一个没招就退了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9230363/asst.log)

### 截图

![ZQ2WCUH4)BLN98R})($NEO2](https://user-images.githubusercontent.com/74587068/182057774-89902d71-9c24-4482-b451-46ef6fdfa7b7.png)

**Comment by zzyyyl** [comment]
欸这log没有，等我找找

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/d6b2f47f9ad0844bd2d0b465b46e338cd2fa2783 这样应该行, 虽然我不觉得这是啥好方法 😭
