### ISSUE TITLE
建议基建增加挂信赖功能

### ISSUE THREAD

**Issue by Misaka2623** [MaaAssistantArknights/MaaAssistantArknights#1398]
### 有什么好的想法？

可以用信赖干员填满基建所有空缺的位置（比如没有使用的宿舍、加工站）
另外，可以在中枢提示信赖已满时更换基建副手

**Comment by zzyyyl** [comment]
虽然 `duplicate`，但也算是个总结

我把所有相关issue列在下面：
#432 #803 #1392

**Comment by ABA2396** [comment]
现在宿舍有填充干员刷信赖了，可以更新后去设置里开启
