### ISSUE TITLE
(我们的肉鸽开局是不支持狙击+医疗队嘛)

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaAssistantArknights#1399]
### 说说你遇到的问题？

![image](https://user-images.githubusercontent.com/72590023/182068432-78cedcc0-307c-41a9-b8ad-42e31c12f56d.png)

如图, 是不是少一个队

**Comment by MistEO** [comment]
叫啥来着，可能写漏了

**Comment by one-pyy** [comment]
> 叫啥来着，可能写漏了

叫远程战术分队
