### ISSUE TITLE
自动肉鸽 有概率会卡关

### ISSUE THREAD

**Issue by ji-zhe** [MaaAssistantArknights/MaaAssistantArknights#1400]
### 说说你遇到的问题？

关卡场景：高台地面部署无限制
触发前提：所有干员均已部署但纯奶干员在前方接敌
后果：没有干员对敌人造成有效输出，但怪又打不死纯奶，无限打年糕

### 有什么好的想法？

如果优化自动部署策略比较繁琐的话，建议直接加计时器，关卡时间超过“用户设置的阈值”后，直接放弃作战重新开始肉鸽。

**Comment by ji-zhe** [comment]
不过，触发概率不算高，刷了这么久就遇到过一次

**Comment by ABA2396** [comment]
> 不过，触发概率不算高，刷了这么久就遇到过一次

过五分钟就自己全撤了

**Comment by MistEO** [comment]
过五分钟就全撤了，过 6 分钟就会自动放弃当场战斗
