### ISSUE TITLE
肉鸽灾厄开局和战斗时开技能的问题

### ISSUE THREAD

**Issue by rong-wo-si-kao** [MaaAssistantArknights/MaaAssistantArknights#1401]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

- [ ] 一直点安塞尔(已经开了的)治疗技能
- [ ] 一直开关山的技能
- [ ] 一直点陈技能(敌人没走进技能范围
- [ ] 打直面灾厄的时候，会自动选择收藏品(高卢长袍)，会使全员希望+1，导致开局选择不了6星干员

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9233627/asst.zip)

### 还有别的吗？

希望可以增加一个识别敌人与干员技能范围距离的功能，这样在敌人来之前就不会一直乱点技能

**Comment by zzyyyl** [comment]
- 干员技能范围识别已经有了，但是识别敌人太过困难了（

- 反复开关山的技能应该是bug，山应该只会开一次技能

- 一直点安塞尔的技能应该是识别到旁边的技能图标了（上面的山估计也是类似），这种情况最好能给个截图

**Comment by zzyyyl** [comment]
提 issue 的时候最好说明一下你是在哪个模块遇到了 bug（看你的表述应该是肉鸽）

**Comment by ABA2396** [comment]
一直开关山的技能新版本已经修了

**Comment by rong-wo-si-kao** [comment]
嗯，好的，下次遇到问题的时候我会带上截图

**Comment by rong-wo-si-kao** [comment]
> 嗯，好的，下次遇到问题的时候我会带上截图



> 提 issue 的时候最好说明一下你是在哪个模块遇到了 bug（看你的表述应该是肉鸽）

嗯，好的，下次遇到问题的时候我会带上截图

**Comment by wangnengjie** [comment]
补充一下一直点安塞尔的情况

![image](https://user-images.githubusercontent.com/43722125/187080036-75db56fc-5b31-4992-92d3-48d691083021.png)

肉鸽 大盗当头 这关，图里我已经在手操了所以技能是转好的...主要表现是安塞尔技能没好也在一直点安塞尔，部署在右上角蓝门左下的位置。

我猜测是识别到了山头上的标

**Comment by MistEO** [comment]
fixed
