### ISSUE TITLE
肉鸽 刷蜡烛改良方案

### ISSUE THREAD

**Issue by noriole** [MaaAssistantArknights/MaaAssistantArknights#1406]
### 说说你遇到的问题？

https://www.bilibili.com/video/BV1mr4y1a7NE/
单令无藏品通关灾厄关卡合集
建议内置这个作业
刷蜡烛选择开局辅助分队，没有令就自动借好友的
效率比山要高一些，因为容错率更高
蜡烛计算规则
一层50个
领袖战斗30
精英战斗20
普通战斗10
物品5
干员次数2

**Comment by MistEO** [comment]
现在是没有肉鸽作业这种东西的，也不打算去做。另外新版本可以自己选开局干员了

**Comment by lxq-9527** [comment]
> 现在是没有肉鸽作业这种东西的，也不打算去做。另外新版本可以自己选开局干员了

自选干员 能选择助战吗

**Comment by ABA2396** [comment]
> > 现在是没有肉鸽作业这种东西的，也不打算去做。另外新版本可以自己选开局干员了
> 
> 自选干员 能选择助战吗

不能
