### ISSUE TITLE
多开时关闭一个connection会让另一个connection也断连且无法重连

### ISSUE THREAD

**Issue by ChildeRolando** [MaaAssistantArknights/MaaAssistantArknights#1413]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

多开时关闭一个connection会让另一个connection也断连且无法重连
无论是用GUI还是手动链接或是二者混用多开，都会100%遇到任意一个connection被关闭时有另一个connection也掉线的情况，且软件反复尝试重连无法成功，GUI也必须关闭重启，否则无法继续使用。
在尝试同时挂多个账号时发现这个问题，一个账号完成任务/关闭窗口断开连接会导致另一个账号也立刻断线，这导致MAA无法并行
我认为是关闭的方式：```asst::Controller::call_command | `F:\Nox\bin\adb.exe kill-server` | enter ```过于粗暴，应该kill掉port对应的abd（如果能区分的话）
上传的日志中port分别为62001和62025，可以看到其中一个被关闭时另一个陷入无限尝试重连状态
### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9239360/asst.log)

### 截图

![微信截图_20220802074736](https://user-images.githubusercontent.com/43607124/182301072-3c6319a2-ccf2-4ce9-836f-bb5d11b4bc40.png)

### 还有别的吗？

夜神模拟器，但手动连接选择general时也有同样的问题
MAA在各个版本(最新4.2.1)中都遇到这个问题

**Comment by MistEO** [comment]
不 kill-server 会有子进程残留的，disconnect 也没用。暂时没想到有啥好办法可以解决。可能等新版 ui 能原生支持多开了就好了吧（
