### ISSUE TITLE
希望对于肉鸽新加功能完善python文档(4.2.1)

### ISSUE THREAD

**Issue by ChildeRolando** [MaaAssistantArknights/MaaAssistantArknights#1414]
### 说说你遇到的问题？

即自选开局干员和分队这些功能，不知道要怎么调用
此外文档整体似乎也略显老旧，需要更新

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/fc6b1be975b6f7d13dcb0929b58a3641bbeea9b5/tools/TestCaller/main.cpp#L82-L88

文档下次一定（

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/2ddfef694f361f20b9b6395b247d1b79b1d05d03 fixed
