### ISSUE TITLE
肉鸽第一层结束后自动停止

### ISSUE THREAD

**Issue by Hambaby** [MaaAssistantArknights/MaaAssistantArknights#1416]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽中未勾选选项【源石锭达到上限停止】，但依旧在第一层结束后显示任务已全部完成。

### 日志文件

[Uploading asst.log…]()

### 截图

![QQ截图20220802113054](https://user-images.githubusercontent.com/97278349/182306807-e911d143-1678-4b5e-81d8-c80c0cc22388.png)
![QQ截图20220802113100](https://user-images.githubusercontent.com/97278349/182306815-999d58e7-45dd-4e4a-a9f8-af648e95c739.png)

### 还有别的吗？

w10 雷电

**Comment by MistEO** [comment]
因为你写了投资次数 0 。。。

**Comment by MistEO** [comment]
补充一下这个设置投资次数的意思是刷到这个次数就任务停止。举个使用场景的例子，比如我要出门了，希望 maa 帮我刷 200 个原始锭然后自动关机，这时候设个使用次数 200，然后选上 完成后关机

现在投资功能是没法关掉的，是必投资的。以后可能考虑出一个不投资的选项，也可能等到下次新肉鸽再说了

**Comment by Hambaby** [comment]
那有办法跳过投资吗 现在投资满了只想刷蜡烛

**Comment by Hambaby** [comment]
另外今天也出过另外一个BUG   自选了突击分队耀骑士临光开局 打到第二个战斗关卡发现都会在进关卡选人时候会把临光去掉少选一个人

**Comment by Hambaby** [comment]
好的 第一个懂得怎么修改了 是我理解有问题，那我想反馈另外一个问题 肉鸽中自选了突击分队耀骑士临光开局 打到第二个战斗关卡发现每次都会在进关卡选人时候把临光去掉少选一个人导致游戏失败，我刚才又重新开了一把并录制了视频发现依旧如此

**Comment by MistEO** [comment]
> 好的 第一个懂得怎么修改了 是我理解有问题，那我想反馈另外一个问题 肉鸽中自选了突击分队耀骑士临光开局 打到第二个战斗关卡发现每次都会在进关卡选人时候把临光去掉少选一个人导致游戏失败，我刚才又重新开了一把并录制了视频发现依旧如此

那重开一个 issue 发个日志看看吧，这个我先关咯（另外这个的日志你没传上来，应该还在上传的时候就点了提交，下次传日志可能要多等一会
