### ISSUE TITLE
肉鸽中自动取消了干员选择

### ISSUE THREAD

**Issue by Hambaby** [MaaAssistantArknights/MaaAssistantArknights#1417]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽中使用了突击近卫分队开局 使用干员为耀骑士临光，在第二个战斗关卡的时候会突然将耀骑士临光取消选择，进入了战斗关卡

### 日志文件

[Uploading asst.log…]()
log文件最后两次肉鸽都出现了这种问题

### 截图

https://user-images.githubusercontent.com/97278349/182327485-5dc4be99-7a4a-4f4a-8943-b7da4940055a.mp4

![QQ截图20220802162035](https://user-images.githubusercontent.com/97278349/182327680-53d285d1-bba9-4c5e-acf2-d1b1e0035368.png)
![QQ截图20220802162046](https://user-images.githubusercontent.com/97278349/182327707-f9277d4b-cc42-47ad-8eef-5745e61cd359.png)

### 还有别的吗？

w10  雷电

**Comment by MistEO** [comment]
所以你的日志还是没有传上来。。

**Comment by Hambaby** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9240543/asst.log)

**Comment by MistEO** [comment]
v4.2.2-beta.1 fixed
