### ISSUE TITLE
更改语言貌似没有全部生效

### ISSUE THREAD

**Issue by fastboot-rec** [MaaAssistantArknights/MaaAssistantArknights#1418]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在设置选项更改语言后，部分文字没有自动切换
在切换语言后，确定选项ui不正常

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9240585/asst.log)

### 截图

![1](https://user-images.githubusercontent.com/75794588/182334449-d4ce52f6-71c1-4e58-92db-131a858fd512.png)
![2](https://user-images.githubusercontent.com/75794588/182334460-48ef8fa4-6cae-488d-bb3b-1c1ed46cce2b.png)
![没对齐](https://user-images.githubusercontent.com/75794588/182334471-b83645be-9ca5-4a3a-90cc-78224cd40976.png)

### 还有别的吗？

系统：Windows 10 专业版 21H2
MAA版本：v4.2.1

**Comment by ABA2396** [comment]
这个是新加的，翻译还没跟上

**Comment by fastboot-rec** [comment]
好吧，我还以为翻译不全是个bug，原来是翻译没跟上
但ui不正常应该是bug吧

**Comment by ABA2396** [comment]
> 好吧，我还以为翻译不全是个bug，原来是翻译没跟上 但ui不正常应该是bug吧

是指那两个按钮吗？那个是封装好的 ~~（没找到在哪里改）~~

**Comment by fastboot-rec** [comment]
> > 好吧，我还以为翻译不全是个bug，但原来不是跟上ui不正常应该是bug吧
> 
> 是指那两个按钮吗？~（没找到哪里改）~

对，就是这两个按钮，ui不统一看着好难受，虽然感觉不会常用（bushi）
![image](https://user-images.githubusercontent.com/75794588/182388618-e94861f7-f79f-454e-b44a-cd06d8777d09.png)

**Comment by MistEO** [comment]
v4.2.2-beta.1 fixed and supportted
