### ISSUE TITLE
在网络连接性较差时会出现的一些问题

### ISSUE THREAD

**Issue by EmberNed** [MaaAssistantArknights/MaaAssistantArknights#1419]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在网络连接较差或区域延迟过高时，一些后续任务的间隔时间会小于游戏沟通鹰角服务器的时间而导致吞操作。
目前已知的有：
选取已有线索，赠送线索
信用购物（购物无法全部完成，无法返回主界面继续进行领取日常奖励等）

此类问题在网络较好延迟较低时均未出现，在国外高物理延迟网络环境中普遍存在。
是否可以增加一个基于识别“正在提交反馈至神经。。。“的检测来规避此类问题。或者更简洁的使得间隔可以由客户端调整固定值。

环境：蓝叠国际版

### 日志文件

暂时无需日志文件

**Comment by MistEO** [comment]
这说了等于白说。。常见场景我们都是有做 “正在提交反馈至神经。。。“ 的识别的，下次遇到了带上日志具体问题具体分析吧
