### ISSUE TITLE
基建換班無法正常做動

### ISSUE THREAD

**Issue by jt851113** [MaaAssistantArknights/MaaAssistantArknights#1421]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用最新release version v4.2.1在使用基建換班時，會停在主頁面不做動
其他功能皆是正常的，有嘗試過調整解析度至建議的橫屏1280 * 720並且調整至320 dpi 異常依舊
Log錄製手法是單純的點擊 Link start後，發現該功能不做動，手動按下停止
上傳的log是先將原先log移除後，由程式自動生成的，因此應該只會錄製到本次行為
感謝協助

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9244294/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/33995805/182433213-08ff4801-dce4-4236-a8ed-ee79ff6ee8d7.png)

### 还有别的吗？

OS : Win10 
Simulator : Bluestacks Nougat 64bits v5.9.0.1061
用戶端版本: YoStarJP 日服

**Comment by MistEO** [comment]
日服并没有支持基建换班，请参考文档
