### ISSUE TITLE
公招支援+群攻识别为 6★Tags，白高兴了

### ISSUE THREAD

**Issue by qianxu2001** [MaaAssistantArknights/MaaAssistantArknights#1422]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9244490/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/62287903/182439467-5c1e03b5-83af-44f6-bcb5-872d59786571.png)
![image](https://user-images.githubusercontent.com/62287903/182439546-3af7b7e5-1031-4ff2-935d-c09ce9e61b5d.png)

**Comment by MistEO** [comment]
呜怎么又有新 bug

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/b8a76450f04f26d186dbfc327b5f972136986ef4/src/MeoAssistant/AutoRecruitTask.cpp#L73-L87

这里应该是 `remove_if` 而不是 `find_if`

**Comment by zzyyyl** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/af750a4302d235a73ffb14a62b63e75e076bf6e6#diff-baa577c09c49d2b5ab4edfc819b3317809ec67c62a65c65068e97e4d28f71682R84
@horror-proton 这行 continue 跳过了一个元素

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/fcff27858ac8f0c331e44681fc2a4020d7beed8f 应该是这样 (草这问题也太隐蔽了, 我被坑过好几次
