### ISSUE TITLE
日服开始唤醒卡在Tap to Start

### ISSUE THREAD

**Issue by ClaisenR** [MaaAssistantArknights/MaaAssistantArknights#1423]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [ ] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用逍遥模拟器8.0.2 安卓7.1 64位版本登录日服，启动预设选择日服，从桌面开始唤醒，卡在了tap to start，三次尝试均复现

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9247285/asst.log)

**Comment by MistEO** [comment]
日服还没有支持开始唤醒，请参考文档
