### ISSUE TITLE
公招 支援+近战位+重装干员+识别成塞雷娅（六星干员）

### ISSUE THREAD

**Issue by TTTTTTTT-Teio** [MaaAssistantArknights/MaaAssistantArknights#1424]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，公招识别的时候在没有高级资深干员tag的情况下将tag组合识别成六星tag。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9247614/asst.log)

大致时间是十点四十六分

### 截图

![image](https://user-images.githubusercontent.com/109303702/182516025-272ae825-0691-48d5-a59e-b18609eb3b51.png)
![image](https://user-images.githubusercontent.com/109303702/182516098-94331a24-0f6e-4122-b34c-e8f54fb53a84.png)

### 还有别的吗？

no

**Comment by zzyyyl** [comment]
Similar to #1422
