### ISSUE TITLE
开始刷理智后取消勾选消耗理智药，仍会自动吃药

### ISSUE THREAD

**Issue by seuqo** [MaaAssistantArknights/MaaAssistantArknights#1425]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

开始任务时勾选了吃理智药3个，是之前设置的忘了取消，遂取消了勾选，结果还是自动吃药了
如果吃药是按开始就确定好的，那开始之后，吃理智药的选项是否应当变灰？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9247748/asst.log)

### 截图

![maa_吃理智](https://user-images.githubusercontent.com/106660185/182518672-e2287492-d6aa-4b72-92ad-340e67bb5841.png)

这是后来取消勾选吃理智药的截图

### 还有别的吗？

模拟器：蓝叠-hyperV
操作系统：win11

**Comment by seuqo** [comment]
日志从[2022-08-03 10:56:52.921]开始

**Comment by MistEO** [comment]
你需要点那个 "修改" 按钮，才能生效的

**Comment by seuqo** [comment]
> 
原来如此，完全没注意有这个按钮
