### ISSUE TITLE
建议提高肉鸽智能度

### ISSUE THREAD

**Issue by Pavel-Ivanovich-Batov** [MaaAssistantArknights/MaaAssistantArknights#1428]
### 说说你遇到的问题？

肉鸽模式中：
单核高星干员（如令、棘刺）摆放顺位较低，常常三四星干员下完了才下；
不懂得攒希望拿六星，有希望就会乱招一堆四五星干员；
干员放置位置不佳，近战不阻挡、远程送到歌姬脸上。
以上问题导致原本能保送第五层的令、棘刺等开局常常在第一层就失败，极大影响了刷蜡烛的效率，能否有一稳妥的解决方案？

**Comment by MistEO** [comment]
有就写了
