### ISSUE TITLE
4.2.1版本Crash

### ISSUE THREAD

**Issue by TakanashiHitomi** [MaaAssistantArknights/MaaAssistantArknights#1429]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我在约2天前下载4.2.1版本，正常运行约1天后启动闪退，无法使用；
今天重新下载4.2.1版本，至中午可以使用；
晚上8点40左右启动失败，闪退；

日志中未发现相关错误堆栈，测试版也未发现相关修复commit；

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9251449/asst.log)

### 还有别的吗？

模拟器：BlueStack X
操作系统：Windows 11 21H2 22000.795

可能和更新有关，我在目录下发现了`MaaBundle-OTA-v4.2.2.zip` 和 `MaaBundle-OTA-v4.2.2.zip.temp`

**Comment by MistEO** [comment]
估计和弹通知有关，先把设置-界面设置里，弹出通知关了，另外问下你具体的系统版本和版本号是？

**Comment by TakanashiHitomi** [comment]
> 估计和弹通知有关，先把设置-界面设置里，弹出通知关了试试

请问在哪里关呢，`gui.json`里没有看到Notification相关设置

**Comment by MistEO** [comment]
> 设置-界面设置

设置-界面设置

**Comment by TakanashiHitomi** [comment]
> > 设置-界面设置
> 
> 设置-界面设置

但是我现在启动就crash……
如果不需要复现我重新安装4.2.2版本 了

**Comment by TakanashiHitomi** [comment]
好吧我已经重新安装并且去除通知叻，观察两天看看

**Comment by TakanashiHitomi** [comment]
目前尚未复现，先close
