### ISSUE TITLE
肉鸽无反应，日志乱码

### ISSUE THREAD

**Issue by SekiBetu** [MaaAssistantArknights/MaaAssistantArknights#1430]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

脚本在肉鸽一些界面上经常停止，无反应，截图里是我看见卡界面了于是手动停止的

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9251756/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/38283893/182621292-3d676125-f366-4b96-828a-8a9306829f10.png)
![image](https://user-images.githubusercontent.com/38283893/182621392-67a75efa-856c-4e2b-a16d-62cdfd1f24b5.png)

### 还有别的吗？

雷电9模拟器
win11系统
最新版4.2.2的脚本

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/182632949-6f046014-e3fe-4cf7-b894-02512d604ce3.png)
![image](https://user-images.githubusercontent.com/38283893/182632974-b2cee069-28df-4e9f-94de-0cfaf3f104ec.png)
![image](https://user-images.githubusercontent.com/38283893/182633069-9bf9298f-7bf9-49fd-b08f-2f850c0b572b.png)
又卡住了，日志和上面的错误一模一样

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/182634064-bd51106f-aec3-42a1-8eb3-ff8f167c1da0.png)
![image](https://user-images.githubusercontent.com/38283893/182634111-b730b853-3e98-419b-8ffc-2d5904407c7f.png)
并且填了煌依然给我选帕拉斯

**Comment by MistEO** [comment]
请参考模拟器支持文档，雷电的支持不是很好，换个模拟器试试

**Comment by SekiBetu** [comment]
那只能用夜神了，蓝叠卡出翔

**Comment by SekiBetu** [comment]
好家伙，夜神模拟器音频都不同步的

**Comment by ABA2396** [comment]
日志乱码是你的编码格式不对，用utf8

**Comment by ABA2396** [comment]
看日志里的append_task Roguelike里没有设置干员
![image](https://user-images.githubusercontent.com/99072975/182810925-38bcc89d-4943-44fa-b316-f6eae5cd9436.png)
正常填入后应该是
![image](https://user-images.githubusercontent.com/99072975/182811008-2558f0ba-da0b-44e3-a01c-c99be48c380a.png)
你当时填写自定义干员的时候是咋样的？

**Comment by SekiBetu** [comment]
抱歉，我已经换模拟器了，脚本也删光了重下了，没有以前的日志了，等下一个碰到类似BUG的人来报告吧
