### ISSUE TITLE
肉鸽问题

### ISSUE THREAD

**Issue by sillyone4** [MaaAssistantArknights/MaaAssistantArknights#1431]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽初始招募中选择辅助招募券时
如果辅助干员较多，会招募失败，一直重复左右滑动没法点到预备干员（术士）

### 日志文件

[Uploading asst.log…]()

**Comment by MistEO** [comment]
日志没传上来，另外多来点图看看

**Comment by sillyone4** [comment]
![BS_PIC_2022-08-03-22-38-37](https://user-images.githubusercontent.com/104875373/182636582-b0df1dc1-8e7f-4f91-a19b-b3098885c271.png)
![BS_PIC_2022-08-03-22-38-43](https://user-images.githubusercontent.com/104875373/182636622-2611ecf7-e274-414a-9315-d6ffa429dd80.png)

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9252446/asst.bak.log)

时间大概在22：40的样子吧，很奇怪的是，会卡在那个地方很久不招募，过一段时间后直接放弃招募了

**Comment by MistEO** [comment]
你的日志被刷掉了（maa 会自动清理过时的日志），下次遇到再发个看看

**Comment by MistEO** [comment]
这个问题已经修复了，请期待下个版本吧~

**Comment by sillyone4** [comment]
辛苦了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月13日(星期六) 晚上10:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽问题 (Issue #1431)





 
这个问题已经修复了，请期待下个版本吧~
