### ISSUE TITLE
更新后mma一键长草找不到自动剿灭

### ISSUE THREAD

**Issue by Bluevolador** [MaaAssistantArknights/MaaAssistantArknights#1432]
虽然好像一直没有自动剿灭的选项

**Comment by MistEO** [comment]
在 关卡选择 里，是刷理智的一部分功能

**Comment by Bluevolador** [comment]
！！！！

**Comment by zzyyyl** [comment]
我有个问题，为什么好多人都把 MAA 叫成 mma 呢（

**Comment by MistEO** [comment]
> 我有个问题，为什么好多人都把 MAA 叫成 mma 呢（

星际选手

**Comment by zzyyyl** [comment]
> > 我有个问题，为什么好多人都把 MAA 叫成 mma 呢（
> 
> 星际选手

原来不是综合格斗看多了吗（x
