### ISSUE TITLE
感觉肉鸽智能化向着奇怪的方向发展了

### ISSUE THREAD

**Issue by atkdefender** [MaaAssistantArknights/MaaAssistantArknights#1433]
### 说说你遇到的问题？

今天下午旅行，中午挂个肉鸽。
出门前，发现打到了第三层关底，在maa不断点临时医疗的技能，导致进度缓慢（临时医疗没技能）。

### 有什么好的想法？

这是一个没必要处理的bug。
挂肉鸽大多图两个东西，①投币，②蜡烛
投币：到达第一层末尾即可
蜡烛：到达第二层关首退出即可（一把大概有60个蜡烛）
到第二层关首完全可以靠山/羽毛笔等单人过掉，也就没必要招募临时医疗，自然没必要修这个bug

于是出门前，我改为挂自动精灵，把自动投币机稍作改动，得到自动蜡烛机。
然后9点多回来就155级了（3点多出发，大概6小时）

真心佩服开发MAA的大佬们，看日志发现去年就开始了，相见恨晚。
佩服大佬们的默默工作。
但另一方面，水月肉鸽实装在即，又对大佬们的发电电力用在解决这些一个又一个的"肉鸽智能化bug"上感到不那么划算。
（当然这只是个人想法，如果大佬非常乐于搞智能化，则另当别论。

### 其他内容

自动投币机的度盘链接：https://pan.baidu.com/s/1SpzfBA5DtlPrmkFSPW3yUA 
提取码：e2c9

**Comment by MistEO** [comment]
《内卷》

**Comment by et2012** [comment]
你遇到的问题应该是那张图的特有BUG，无论谁放在右上角的高台位置都会一直点。

我倒是觉得肉鸽还有很多可以优化的，毕竟写BUG也是一种乐趣。
例如我就想把过关奖励二选一（尤其是招募券）的逻辑优化一下，而不是老选左边那个。
如果可能的话，再把不期而遇的选择也变成智能的。

**Comment by atkdefender** [comment]
> 你遇到的问题应该是那张图的特有BUG，无论谁放在右上角的高台位置都会一直点。
> 
> 我倒是觉得肉鸽还有很多可以优化的，毕竟写BUG也是一种乐趣。 例如我就想把过关奖励二选一（尤其是招募券）的逻辑优化一下，而不是老选左边那个。 还有招募干员的优先级，应该是每个编队不一样的，而不是写死在json里。 如果可能的话，再把不期而遇的选择也变成智能的。 肉鸽战斗系统问题也很多，现在很多关卡完全是靠博士手撕过的。
> 
> 还有这么多可以优化的东西，想想都觉得刺激呢.jpg
大佬orz。发现MMA还有主页的时候就感觉这不一般。

**Comment by et2012** [comment]
> ### 有什么好的想法？
> 这是一个没必要处理的bug。 挂肉鸽大多图两个东西，①投币，②蜡烛 投币：到达第一层末尾即可 蜡烛：到达第二层关首退出即可（一把大概有60个蜡烛） 到第二层关首完全可以靠山/羽毛笔等单人过掉，也就没必要招募临时医疗，自然没必要修这个bug
> 

“第二层关首” 和 “第一层末尾” 有什么区别？就是进入第二层马上退出吗？
如果这样做的效率最高，倒是可以尝试一下。

---

关于肉鸽的智能化方向，不知道 @MistEO 有没有什么想法。

我这几天做了一些尝试，自己玩着效果还行，但给别人用感觉还不够成熟：
- 用 task.json 实现了招募券二选一的优先级逻辑，但感觉还是写个插件比较好，所以提了一个 PR 又关掉了
- 实现了肉鸽商店购买招募券的基本逻辑，可以用于干员晋升或者补充特定职业的干员（保证队伍里至少有 1 个先锋、医疗和重装）

现在离 “肉鸽智能化” 其实还差得远，很多东西都是随缘，例如编队（招募）、战斗、不期而遇，要做的东西比较多。
而且用户的需求也不一样，有些可能像楼主这样是投币、刷蜡烛，有些可能想通关。
另外水月肉鸽就快要出了，现在花这么大力气去更新逻辑，到时候可能还是要重写。

**Comment by atkdefender** [comment]
> > ### 有什么好的想法？
> > 这是一个没必要处理的bug。 挂肉鸽大多图两个东西，①投币，②蜡烛 投币：到达第一层末尾即可 蜡烛：到达第二层关首退出即可（一把大概有60个蜡烛） 到第二层关首完全可以靠山/羽毛笔等单人过掉，也就没必要招募临时医疗，自然没必要修这个bug
> 
> “第二层关首” 和 “第一层末尾” 有什么区别？就是进入第二层马上退出吗？ 如果这样做的效率最高，倒是可以尝试一下。 我用令单刷队试了一下，普通难度打到第一个BOSS失败退出的话，有200多蜡烛。
> 
> 关于肉鸽的智能化方向，不知道 @MistEO 有没有什么想法。
> 
> 我这几天做了一些尝试，自己玩着效果还行，但给别人用感觉还不够成熟：
> 
> * 用 task.json 实现了招募券二选一的优先级逻辑，但感觉还是写个插件比较好，所以提了一个 PR 又关掉了
> * 实现了肉鸽商店购买招募券的基本逻辑，可以用于干员晋升或者补充特定职业的干员（保证队伍里至少有 1 个先锋、医疗和重装）
> 
> 现在离 “肉鸽智能化” 其实还差得远，很多东西都是随缘，例如编队（招募）、战斗、不期而遇，要做的东西比较多。 而且用户的需求也不一样，有些可能像楼主这样是投币、刷蜡烛，有些可能想通关。 另外水月肉鸽就快要出了，现在花这么大力气去更新逻辑，到时候可能还是要重写。

第二层关首离第一关关尾，脚本就差几个离开点击，时间就差一个升层小动画。
蜡烛从15左右增加到60左右，非常划算。

**Comment by MistEO** [comment]
> 就是一升第二层就退出。
> 第二层关首离第一关关尾，脚本就差几个点击，时间就差一个升层过度小动画。
> 蜡烛从15左右增加到60左右，非常划算（推荐投币后直接到2层退，两者都刷了）。
> 效率倒是其次，主要是需要处理的问题大大减少。如无必要勿增实体嘛XD。

fixed
