### ISSUE TITLE
关于公招的资深干员tag与其他5星tag优先级冲突，导致触发保险机制而卡住

### ISSUE THREAD

**Issue by micrototem** [MaaAssistantArknights/MaaAssistantArknights#1436]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我在MAA中设置了公招时“自动确认5星”。

我发现公招tag同时出现“资深干员”和“召唤”时，
MAA会自动选择“召唤”，忽略“资深”tag触发游戏保险机制。

游戏会询问“未选中稀有职业需求，是否确认？”
MAA不能正确识别，从而卡住。

截图3显示“出现错误，已返回”
是因为我手点了“x”，不然还会卡在截图2的界面。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9254023/asst.log)

时间点是 8月4日 1点41分后

### 截图

公招tag
![32a0c8865f8307a7bb543e4725a0779](https://user-images.githubusercontent.com/43628968/182679243-adde6a81-042a-4f5a-94dd-7d97e445a843.png)
触发保险
![ab7bd332d57bf30308116e4a312235a](https://user-images.githubusercontent.com/43628968/182679255-29e7e1a3-5d14-4ebe-adc9-ab738c99ce95.png)
行动记录
![db6d25664730d54cb7d11f1e6fbc240](https://user-images.githubusercontent.com/43628968/182681900-ddbd9948-29cc-4a00-9c7f-9f4b17d7e559.jpg)
自动公招的设置情况
![7a376338de844b802f4610229358f10](https://user-images.githubusercontent.com/43628968/182680799-8b37cc9e-a38c-43e4-8a3f-10c3338c285f.jpg)

**Comment by horror-proton** [comment]
我看到你出问题的版本是 `4.0.8` 这个问题现在已经修复了, 现在的行为是只选择资深干员 tag
