### ISSUE TITLE
BlueStacks hyper-v adb_port 识别问题

### ISSUE THREAD

**Issue by weedi0** [MaaAssistantArknights/MaaAssistantArknights#1437]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

BlueStacks hyper-v 随机端口，新版没法正确识别，3.x旧版可以识别。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9256087/asst.log)

**Comment by cglcv** [comment]
[蓝叠模拟器国际版 Hyper-V 版本](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.md#蓝叠模拟器国际版 Hyper-V 版本)

是不是没改gui.json啊，我这边一切正常~甚至就算是通用模式下换了WSA还在读蓝叠的随机端口~

**Comment by weedi0** [comment]
> [蓝叠模拟器国际版 Hyper-V 版本](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.md#-%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E5%9B%BD%E9%99%85%E7%89%88-hyper-v-%E7%89%88%E6%9C%AC)
> 
> 是不是没改gui.json啊，我这边一切正常~甚至就算是通用模式下换了WSA还在读蓝叠的随机端口~
是这个情况，之前旧版不需要设置，和没仔细看使用说明！
