### ISSUE TITLE
阿消悖论模拟作业无法正常使用

### ISSUE THREAD

**Issue by nightofknife** [MaaAssistantArknights/MaaAssistantArknights#1441]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在测试阿消悖论模拟时发现MAA会在切换二倍速行为中点击暂停按键，同时点击阿消，从而卡住。

### 日志文件

全日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9259263/asst.log)
起始时间节点
2022-08-04 19:17:10.398

### 截图

MAA出错时截图
![WEI~0HKOF84W`X4A%4D4GBY](https://user-images.githubusercontent.com/73384329/182837923-205080fd-4ead-4521-81b7-9101b4783663.png)

出错时模拟器界面截图
![Screenshot_2022 08 04_19 29 13 345](https://user-images.githubusercontent.com/73384329/182837932-3045c153-7c3a-40d0-b965-10793f7bf965.png)

其他测试人员提供的截图
![Uploading QQ图片20220804195003.jpg…]()
![Uploading QQ图片20220804195007.jpg…]()

### 还有别的吗？

系统：win10
模拟器：蓝叠国际版9.9.0.1061 N32版本（MUMU经过测试也会如此，但提供不了日志）
MAA版本：4.2.2（4.1.0到4.2.2均有出现此问题，但是有小概率不出现，原因未知，日志未能保留）
使用作业：
[喷射！_阿消 (3).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9259329/_.3.zip)
：
视频：
https://user-images.githubusercontent.com/73384329/182840202-38830e13-c194-4ef0-8f2f-48207d728cea.mp4

**Comment by ntgmc** [comment]
作业问题联系作者吧
另外现在4.6.x应该已经能用了
