### ISSUE TITLE
希望增加一个识别肉鸽等级并回报的功能，最好能满级之后自动结束肉鸽任务

### ISSUE THREAD

**Issue by ChildeRolando** [MaaAssistantArknights/MaaAssistantArknights#1443]
### 说说你遇到的问题？

一直在打很难知道到底挂到多少级了，必须退出来才能看到，一直惦记着很不爽
且每个月挂肉鸽总会满级后还重复打，很浪费电

**Comment by ABA2396** [comment]
现在能设置挂肉鸽的次数，虽然不能准确到满级就停下，但可以避免一直刷下去

**Comment by ChildeRolando** [comment]
> 

希望能更解手一点（这是可以说的吗）不然的话还得创建一个本地日志来记录每个账号打了多少次，好麻烦啊orz
