### ISSUE TITLE
Change checksum.json's encoding

### ISSUE THREAD

**Issue by Lutra-Fs** [MaaAssistantArknights/MaaAssistantArknights#1444]
### 说说你遇到的问题？

I have written a scoop app manifest for this software. When I want to add auto-update for it using JSON. The software cannot handle UTF8-with-BOM encoding. UTF8-with-BOM is neither required nor recommended.

### 有什么好的想法？

Suggest changing the encoding to UTF8(-without-BOM)

### 其他内容

https://stackoverflow.com/questions/2223882/whats-the-difference-between-utf-8-and-utf-8-without-bom

P.S. my manifest
```
scoop bucket add lutra https://github.com/Lutra-Fs/scoop-bucket.git 
scoop install maa-arknights
```
Chinese is okay for the reply. I just don't want to change the input method.

**Comment by LiamSho** [comment]
C# Encoding problem.

fixed

**Comment by LiamSho** [comment]
@Lutra-Fs

??? 

Why you close this issue? The changes have not been merged into main.

Please don't do this anymore.
