### ISSUE TITLE
【自动公招】没有招募券的时候，若为4星及以上，不从别的空挡刷新标签

### ISSUE THREAD

**Issue by Komori-AA** [MaaAssistantArknights/MaaAssistantArknights#1452]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

没有招募券的时候，若为4星以上，不从别的空挡刷新标签，联络次数满了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9264235/asst.log)
[2022-08-04 17:12:48.495]

**Comment by horror-proton** [comment]
设计是一但用完招募许可就退出公招任务的, 遇到这个情况好像确实不利于刷标签 🤔

**Comment by Komori-AA** [comment]
刷新逻辑只有3星应该是无条件刷掉的，毕竟3星没用，可以优先于别的

**Comment by ntgmc** [comment]
该功能已经修复，感谢您的反馈！
