### ISSUE TITLE
基建干员放置问题

### ISSUE THREAD

**Issue by Wanbi1** [MaaAssistantArknights/MaaAssistantArknights#1453]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建中的会客室有时会没有放置干员进行联络，出现的时间不固定。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9264723/asst.log)
问题出现在最近的一次基建任务当中

**Comment by superybq** [comment]
是不是基建没有选会客室
我是不选会客室的,在操作宿舍的时候,当会客室干员心情很低的时候就会进宿舍休息.

**Comment by Wanbi1** [comment]
> 问题挺奇怪的，是 `2022-08-05 10:00:13` 这个时间点附近么，看日志应该是都正确识别到并且选了的。。
> 
> 下次再遇到有机会的话帮忙看看具体是怎么操作的（比如是没选人就点了确定，还是正确选人了去宿舍又把人放进去了之类的）

今天做了实验，将心情阈值调高，并且设置基建只对办公室和宿舍进行处理，没有出现相关bug。如果再出现会再上传日志。
