### ISSUE TITLE
关卡选择1-7时会卡在选择关卡页面

### ISSUE THREAD

**Issue by Notofnice** [MaaAssistantArknights/MaaAssistantArknights#1454]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

关卡选择1-7后开始运行，但是一直卡在第二个图的关卡选择界面不动

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9264991/asst.log)
8月5日11点半左右

### 截图

![image](https://user-images.githubusercontent.com/63146701/182995456-2561e2b8-18d0-4285-9c83-3db4fa91767e.png)
![image](https://user-images.githubusercontent.com/63146701/182995488-ea166246-0604-4799-9406-dde8b0d81003.png)

**Comment by zzyyyl** [comment]
@ABA2396

**Comment by zzyyyl** [comment]
我也有这个问题，而且我卡在了第 0 章...

**Comment by ABA2396** [comment]
> 我也有这个问题，而且我卡在了第 0 章... [asst.log]

上面这个问题解决了，你这个跑到第零章我是着实没想到）

**Comment by zzyyyl** [comment]
> > 我也有这个问题，而且我卡在了第 0 章... [asst.log]
> 
> 上面这个问题解决了，你这个跑到第零章我是着实没想到）

它先点进了第三章，然后一个个往前点（估计是点太快了）就点到了第 0 章（

**Comment by ABA2396** [comment]
加个延迟吧，我没测出点到第0章，看看改完之后还会不会有问题

**Comment by myjdem** [comment]
![捕获](https://user-images.githubusercontent.com/76983930/183109868-7d86abb6-7cc8-4cbb-9988-a5426f0a700d.PNG)
一样也遇到了这个问题mumu模拟器和蓝叠模拟器都出现过

**Comment by desktop4025** [comment]
> > 我也有这个问题，而且我卡在了第 0 章... [asst.log]
> 
> 上面这个问题解决了，你这个跑到第零章我是着实没想到）

同样遇到。。

**Comment by ABA2396** [comment]
> 一样也遇到了这个问题mumu模拟器和蓝叠模拟器都出现过

已经修了但没发版，选择要用的话可以去action下载完整包或者去下载dev分支下的resource/[tasks.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/tasks.json)替换你的task.json

**Comment by myjdem** [comment]
> > 一样也遇到了这个问题mumu模拟器和蓝叠模拟器都出现过
> 
> 已经修了但没发版，选择要用的话可以去action下载完整包或者去下载dev分支下的resource/[tasks.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/tasks.json)替换你的task.json
![捕获](https://user-images.githubusercontent.com/76983930/183239555-6698a86d-43ab-455a-b11e-8c9409eb774a.PNG)

不行直接替换会报错

**Comment by ABA2396** [comment]
> 不行直接替换会报错

没有更改过其他文件，最新版本直接替换应该是不会有问题的。如果还是不行就直接下载Actions-dev-build里最新的Artifacts

**Comment by myjdem** [comment]
> > 不行直接替换会报错
> 
> 没有更改过其他文件，最新版本直接替换应该是不会有问题的。如果还是不行就直接下载Actions-dev-build里[fix: 修复1-7导航问题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/2802480908)的[artifacts](https://github.com/MaaAssistantArknights/MaaAssistantArknights/suites/7680320553/artifacts/320530105)
![捕获](https://user-images.githubusercontent.com/76983930/183240446-55755a72-04ae-4e09-8695-8ba69e284e46.PNG)


artifacts版本的可以正常识别到1-7

**Comment by MistEO** [comment]
v4.2.3 fixed
