### ISSUE TITLE
公募型プロポーザル

### ISSUE THREAD

**Issue by foxlesbiao** [MaaAssistantArknights/MaaAssistantArknights#1457]
### 说说你遇到的问题？

自動公開募集を使っていると、3つ星のタグ募集の設定が9時間というのは非常に理不尽だと感じました。

### 有什么好的想法？

星3つのタグの募集を1時間、星4つ以上のタグの募集を9時間に設定することを推奨 希望する場合、24時間ノンストップで募集した場合の時間としてカウント可能

**Comment by zzyyyl** [comment]
在只有三星 Tags 的时候，我们一般认为招募时间越长，出4、5星的概率也越高。所以这个应该不会去做的。这个问题之前已经讨论过了。https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/137#issuecomment-1145819399

When there are only three stars Tags, we generally believe that the longer the recruitment time, the higher the probability of 4 or 5 stars. So we will not go for it. This issue has been discussed before. https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/137#issuecomment-1145819399

星3つのタグしかない場合、一般的には募集期間が長いほど、星4つ以上の確率が高くなると考えています。ですから、それを狙うことはありません。この問題は以前から議論されています。https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/137#issuecomment-1145819399

我语言表达不太行，有没有人再来讲讲（？

**Comment by foxlesbiao** [comment]
> 在只有三星 Tags 的时候，我们一般认为招募时间越长，出4、5星的概率也越高。所以这个应该不会去做的。这个问题之前已经讨论过了。[#137 (comment)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/137#issuecomment-1145819399)
> 
> When there are only three stars Tags, we generally believe that the longer the recruitment time, the higher the probability of 4 or 5 stars. So we will not go for it. This issue has been discussed before. [#137 (comment)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/137#issuecomment-1145819399)
> 
> 星3つのタグしかない場合、一般的には募集期間が長いほど、星4つ以上の確率が高くなると考えています。ですから、それを狙うことはありません。この問題は以前から議論されています。[#137 (comment)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/137#issuecomment-1145819399)
> 
> 我语言表达不太行，有没有人再来讲讲（？ （上面两个基本上都是 deepl 翻译的）

しかし、私はその確率が低すぎると思います

**Comment by lhhxxxxx** [comment]
> しかし、私はその確率が低すぎると思います

いずれにしても、星1/2つを避けるために7時間40分まで設定する必要がある

**Comment by ABA2396** [comment]
这两天无tag拉9小时出了2个5星
