### ISSUE TITLE
mumu模拟器连接问题

### ISSUE THREAD

**Issue by myjdem** [MaaAssistantArknights/MaaAssistantArknights#1460]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

安装了蓝叠模拟器后maa无法连接上mumu模拟器，在卸载掉蓝叠模拟器后也无法连接上，尝试过重装mumu模拟器和重新下载maa依然不行

### 日志文件

[Uploading asst.log…]()

### 截图

![maa连接设置](https://user-images.githubusercontent.com/76983930/183101110-3e7a020c-c729-4f0c-bc45-507c21fb1d84.PNG)
![模拟器版本](https://user-images.githubusercontent.com/76983930/183101254-5a5c0e2d-6da6-478b-b0f9-c111ae5da318.PNG)

**Comment by myjdem** [comment]
![连接失败](https://user-images.githubusercontent.com/76983930/183102183-d2b68432-4593-4296-8950-2f6f169dcf49.PNG)

**Comment by MistEO** [comment]
你的日志没上传上来，重发下看看

**Comment by myjdem** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9269658/asst.log)

**Comment by myjdem** [comment]
> 没上传上来，重发下看看

发了

**Comment by MistEO** [comment]
- `D:\Program Files\emulator\nemu\EmulatorShell\..\vmonitor\bin\adb_server.exe` 确定下这个路径是不是对的（我不知道是自动识别出来的还是你手动填写的，总之先确认一下
- 如果是对的，很大可能是文件夹权限问题，可以尝试
  - 自己下个 adb，然后把自己下的 adb 路径填进去，不用 mumu 自带的那个
  - 把 maa 换个位置，总之别放 C 盘
  - 把模拟器重新装一下，换个可能访问权限更宽松的路径
  - 直接换个模拟器，别用 mumu 了

**Comment by myjdem** [comment]
> * `D:\Program Files\emulator\nemu\EmulatorShell\..\vmonitor\bin\adb_server.exe`确定下这条路不是对的（我不确认是自动识别出来的还是你手动重新填写的，总之先知道的
> * 如果是对的，很大可能是文件夹权限问题，可以试一下
>   
>   * 自己下个adb，然后把自己下个的adb 填进去，不用mumu自带的那个
>   * 把maa换个位置，总之别放C盘
>   * 可以把一个偶然的途径安装，换个更方便的访问权限
>   * 直接换个爱，别用 mumu 了

adb跟着自动识别的路径找的，我试试看下个aadb看看

**Comment by myjdem** [comment]
麻了下adb替换反而出现未知的错误，将maa放去D盘在换回mumu模拟器的adb又可以了
