### ISSUE TITLE
未知原因卡住

### ISSUE THREAD

**Issue by desktop4025** [MaaAssistantArknights/MaaAssistantArknights#1463]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

未知原因卡在开始作战

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9270260/asst.zip)

### 截图

![_~_KT@3IJ0VG$GHN R)@(V2](https://user-images.githubusercontent.com/107090995/183119426-e5d81ad3-5121-42c6-a96a-196c2842a73c.png)

### 还有别的吗？

无

**Comment by MistEO** [comment]
v4.2.3 fixed
