### ISSUE TITLE
Maa莫名不能正常工作

### ISSUE THREAD

**Issue by ping1999** [MaaAssistantArknights/MaaAssistantArknights#1465]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Maa莫名不能正常工作，战斗、公招直接失败，基建给我点进商店。

### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9270725/asst.-.log)

### 截图

![LL96~ETYA~O${VO@$LLT08R](https://user-images.githubusercontent.com/20700230/183133944-d808c570-cbf8-4f8f-bf1e-ae89a9126a47.png)

**Comment by ping1999** [comment]
![61B$TH)2K7V1%9}M9(_`EOU](https://user-images.githubusercontent.com/20700230/183134339-dc6a1431-c2f4-4cfb-a90f-c8bc93dfec09.png)
肉鸽模式长时间后不工作，也不提示报错。

**Comment by horror-proton** [comment]
注意到 Ocr 和模板匹配全部失败了, 难道是模拟器的截图出了问题, 我现在用的也是 7.0.3.1 版本的夜神, 暂时没遇到过. 
可以尝试手动运行下
```shell
D:\Program Files\Nox\bin\.\nox_adb.exe -s 127.0.0.1:62001 exec-out screencap -p > temp.png
```
然后打开 temp.png 看下有没有什么明显的问题, 比如黑屏之类的

**Comment by swk67018** [comment]
I also have an issue similar to this in JP client with BlueStacks.

I tried to take a screenshot in PowerShell as follows

```sh
C:\Program Files\BlueStacks_nxt\HD-Adb.exe -s 127.0.0.1:61041 exec-out screencap -p
```
but the image was corrupted.

From what I've found, it seems to be caused by convering LF to CRLF when taking a screenshot.
https://stackoverflow.com/questions/13578416/read-binary-stdout-data-like-screencap-data-from-adb-shell

When I took a screenshot using Command Prompt instead of Powershell, it worked fine.
I don't know the details, but it may have something to do with the default shell.

**Comment by horror-proton** [comment]
>

On Windows, MAA would call adb with `CreateProcessW` and pipe data from output, which does not depend on default shell I guess.

Some emulators do convert LF to CRLF in adb output (which is annoying), and MAA should be able to convert it back properly. 
ref.
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/ef2a7e8ce189972e88114ec6982c60a2986da6e0/src/MeoAssistant/Controller.cpp#L526

**Comment by swk67018** [comment]
On second thought, it works fine in my environment except infrast and some parts of fight. So it's not a shell problem.
I'll look into it some more.

**Comment by swk67018** [comment]
sorry, I looked at the log but I couldn't find out what was wrong.

**Comment by ABA2396** [comment]
> 

[YoStarEN/readme.md](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/resource/global/YoStarEN/readme.md)

**Comment by ABA2396** [comment]
> > On second thought, it works fine in my environment except infrast and some parts of fight. So it's not a shell problem. I'll look into it some more.
> 
> Do you have any clues about why this happened? The same thing happened to me for v7.3.x

[YoStarEN/readme.md](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/resource/global/YoStarEN/readme.md)
