### ISSUE TITLE
当前/上次作战卡住

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantArknights#1468]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 合并 当前/上次 作战之后我还没用过这个功能（x

从战斗界面开始的任务，回来之后发现卡在了结算界面

因为是第一次用，也不知道是不是玛丽删了这个功能（但是以前当前作战我记得是支持从战斗界面开始任务的

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9274528/asst.zip)

### 截图

![image](https://user-images.githubusercontent.com/74587068/183237511-1e2c7aa7-7d5b-4fd4-a2f2-e97333681436.png)
![image](https://user-images.githubusercontent.com/74587068/183237533-8049214f-993a-4a61-9e81-469db16e6223.png)

**Comment by ABA2396** [comment]
可能合并之后没了）

**Comment by zzyyyl** [comment]
Feature no longer exists.

**Comment by MistEO** [comment]
其实也可以支持一下的（
