### ISSUE TITLE
无法找到关卡后自动切换1-7

### ISSUE THREAD

**Issue by helloIris415** [MaaAssistantArknights/MaaAssistantArknights#1469]
### 说说你遇到的问题？

活动结束后没有调整清理智关卡选择就去上班，电脑在选择界面卡了一天。

### 有什么好的想法？

希望能在关卡选择界面卡住不动10分钟之后自动切换成1-7模式

**Comment by zzyyyl** [comment]
我估计这会是 wontfix。之前有人提过类似的 issue

**Comment by ABA2396** [comment]
之前和玛丽讨论过，但是有人是不刷1-7的）

**Comment by ABA2396** [comment]
感觉更好的解决方法应该是加一个备用关卡选择，在前一个导航失败的时候选择第二个

**Comment by helloIris415** [comment]
> 之前和玛丽讨论过，但是有些人是不刷1-7的）

那能否改成在设置里自己选狗粮，LMB或者1-7的模式

**Comment by ABA2396** [comment]
现在的界面设置里有一个不显示当日未开放的关卡的选项，那个点上之后如果关卡选择的是当日未开放的关卡会自动换成上一次，正常用户的上一次应该就是常刷的关卡

**Comment by MistEO** [comment]
> 感觉更好的解决方法应该是加一个备用关卡选择，在前一个导航失败的时候选择第二个

现在的问题是没这个关卡任务就卡住了，还得想一下怎么让那个 subtask 不要重试那么多次（

**Comment by ABA2396** [comment]
现在有了备选关卡，可以去设置里打开，关卡选择要刷的关卡，备选填上1-7就行了

**Comment by ABA2396** [comment]
不过好像活动结束还是会有问题）要活动结束后更新关闭活动导航入口
