### ISSUE TITLE
关于服务器自动化

### ISSUE THREAD

**Issue by LGY07** [MaaAssistantArknights/MaaAssistantArknights#1470]
### 说说你遇到的问题？

高中要开学了，可能半年都难玩几次，希望借助此软件在服务器上面自动登录

### 有什么好的想法？

# 希望做到很低的性能需求，以至于可以在轻量应用服务器运行
可以把Linux的安装方式弄得更简单，因为Linux的性能比Windows好得多
# 也可以弄个web管理页面
经常通过ssh或者vnc检查状态就太麻烦了

### 其他内容

（仅是建议，如果很难实现的话算了

**Comment by zzyyyl** [comment]
Linux 用户能自己解决问题.jpg

**Comment by zhongfly** [comment]
还得同时运行安卓模拟器的…不是只运行这个就可以的，性能需求低不了

**Comment by LGY07** [comment]
> Linux 用户能自己解决问题.jpg

确实，不说了，我去试试（

**Comment by LGY07** [comment]
> 

可以QEMU，性能算精准一点

**Comment by LGY07** [comment]
> Linux 用户能自己解决问题.jpg

那可以编译个appimage放到Releases吗

**Comment by MistEO** [comment]
其实问题在于 maa team 里现在没有 linux 玩的特别好的大佬，主要的几位开发都是 Windows or macOS，我们也不知道要咋编一个 appimage 出来orz

**Comment by kurumaniya** [comment]
可以装个ltsc版的windows 用rpa可以自动跑

**Comment by Sea-Sheep** [comment]
一般来说云服务器是不支持二次虚拟化的（没显卡），想在阿里云什么的上跑模拟器是不行的

**Comment by chestbursters** [comment]
同时租服务器和云手机就行了(
