### ISSUE TITLE
希望能自动填满休息室并尽可能多的将空余位置填上回心情加成干员

### ISSUE THREAD

**Issue by MisterCoBen** [MaaAssistantArknights/MaaAssistantArknights#1472]
### 说说你遇到的问题？

迷迭香基建的加成需要宿舍干员尽可能填满

### 其他内容

![Screenshot 2022-08-06 112130](https://user-images.githubusercontent.com/97687476/183243022-7782997f-372c-48c6-b6c9-9090bce7bb78.png)

**Comment by ABA2396** [comment]
用软件换班也不会选择迷迭香）

**Comment by zzyyyl** [comment]
Duplicate of #201

**Comment by ABA2396** [comment]
现在有了用信赖未满的干员填满休息室，如果你干员全是满信赖那回复心情的干员就在最前面了（）

**Comment by zzyyyl** [comment]
另外迷迭香的问题可以选择自定义基建（
