### ISSUE TITLE
夜神模拟器连接失败问题

### ISSUE THREAD

**Issue by dongmeng123** [MaaAssistantArknights/MaaAssistantArknights#1473]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

一开始还是能用的，后来好像更新了一下子就不能用了，一直是连接失败的状态。看到常见问题上面显示夜神是可以完美适配的，之前试了一次也能用，不知道为什么现在不能用了（蓝叠模拟器没有见到官网，电脑小白也不太敢随便下载qaq）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9274757/asst.log)

时间点的话，就是下午吧！中午十一点多的时候前几次是能用的（大概两次），更新了以后就不能用了

### 截图

![image](https://user-images.githubusercontent.com/110719782/183243231-a1d4e0e9-8276-4833-a62f-4c8d128a64b2.png)
![image](https://user-images.githubusercontent.com/110719782/183243911-b513c462-d140-4673-88ab-8883bc34f3dd.png)

### 还有别的吗？

![image](https://user-images.githubusercontent.com/110719782/183243292-b7c27862-6d7b-42e2-bba3-eb267a88f1d5.png)
![image](https://user-images.githubusercontent.com/110719782/183243305-efef75cd-2e96-4b50-9d40-d2be66b03b50.png)

**Comment by ABA2396** [comment]
中间有个图片没发上来，连接失败试下重启MAA-重启模拟器-重启电脑，还是不行的话参照[常见问题.md](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md)里的 `连接错误`

**Comment by dongmeng123** [comment]
> 目前情况是已经重启maa和重启模拟器以及电脑，仍为连接失败。已参考常见问题-连接错误-方法一 更改过里面的地址（之前有填充），没有什么效果；蓝叠模拟器没有见到官网，电脑小白也不太敢随便下载qaq

这里补一下第二张图，希望可以看得到（截图里的地址就是之前自动填充下的地址）
![image](https://user-images.githubusercontent.com/110719782/183243911-b513c462-d140-4673-88ab-8883bc34f3dd.png)

**Comment by ABA2396** [comment]
看了下日志应该是其他其他程序占用了5037端口（adb的端口），可以百度一下解决其他软件占用端口的方法，或者按常见问题里的方法下载adb
![image](https://user-images.githubusercontent.com/99072975/183244148-1e4d0d0a-a264-4946-8189-1a3f632451ff.png)

**Comment by zzyyyl** [comment]
有没有可能你开了好几个 MAA，adb 互相占用了（？

**Comment by dongmeng123** [comment]
想咨询您，如果下载adb的话还是放在这个原来选择路径的文件夹嘛？
如果是查端口占用，应该是在哪个上面点 “开始--->运行---->cmd,或者是window+ R组合键，调出命令口。”
感谢您

**Comment by zzyyyl** [comment]
> 想咨询您，如果下载adb的话还是放在这个原来选择路径的文件夹嘛？ 如果是查端口占用，应该是在哪个上面点 “开始--->运行---->cmd,或者是window+ R组合键，调出命令口。” 感谢您

adb 放到哪里都行，自己改连接设置里的 adb 路径就可以了

> `开始--->运行---->cmd,或者是window+ R组合键，调出命令口。`
`开始` 指的是左下角那个 windows 图标（

**Comment by ABA2396** [comment]
> 

新下的adb放哪里没关系，也可以直接放在MAA文件夹下
查询可以用“window + R组合键”， `window ` 键盘应该是在你 `Ctrl` 键的右边，如果是笔记本可能是 `fn` 的右边，就是那个windows 图标

**Comment by dongmeng123** [comment]
> 有没有可能你开了好几个 MAA，adb 互相占用了（？

我没有多开欸，就是开机——打开模拟器——打开maa，我刚刚打开任务管理器查看，感觉是一个的样子~
因为我从任务管理器关掉jio本，然后再打开maa的（但是更新前明明我还用了一下是正常的！体验了一下高科技的便利！可恶！！）

**Comment by zzyyyl** [comment]
> > 有没有可能你开了好几个 MAA，adb 互相占用了（？
> 
> 我没有多开欸，就是开机——打开模拟器——打开maa，我刚刚打开任务管理器查看，感觉是一个的样子~ 因为我从任务管理器关掉jio本，然后再打开maa的（但是更新前明明我还用了一下是正常的！体验了一下高科技的便利！可恶！！）

你可以看看右边的小图标，有没有好几个MAA

**Comment by ABA2396** [comment]
> 你可以看看任务栏右边的小图标，有没有好几个MAA 比如这样

刚开机应该不是这个问题，我觉得可能是其他软件占用了

**Comment by dongmeng123** [comment]
> > > 有没有可能你开了好几个 MAA，adb 互相占用了（？
> > 
> > 
> > 我没有多开欸，就是开机——打开模拟器——打开maa，我刚刚打开任务管理器查看，感觉是一个的样子~ 因为我从任务管理器关掉jio本，然后再打开maa的（但是更新前明明我还用了一下是正常的！体验了一下高科技的便利！可恶！！）
> 
> 你可以看看任务栏右边的小图标，有没有好几个MAA

![image](https://user-images.githubusercontent.com/110719782/183244575-baea06b9-d49a-40b3-81cc-e66e982e4dbb.png)
好像确实也只有一个！！但是就是不能使用（

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/183244647-f022dadb-e08b-4020-a96b-a2161c59cd31.png)

**Comment by dongmeng123** [comment]
> > 你可以看看任务栏右边的小图标，有没有好几个MAA 比如这样
> 
> 刚开机应该不是这个问题，我觉得可能是其他软件占用了

![image](https://user-images.githubusercontent.com/110719782/183244667-a0d73df8-bcd6-4caa-a616-c1a1265e5110.png)

**Comment by zzyyyl** [comment]
为什么你开了两个夜神（x

**Comment by dongmeng123** [comment]
> 为什么你开了两个夜神（x

另一个是小助手，不知道有啥用，下载送我的，我也不会卸载（我是fw

**Comment by ABA2396** [comment]
> 为什么你开了两个夜神（x

可能一个是夜神的管理器，这个没影响吧

**Comment by dongmeng123** [comment]
> ![image](https://user-images.githubusercontent.com/99072975/183244647-f022dadb-e08b-4020-a96b-a2161c59cd31.png)

![image](https://user-images.githubusercontent.com/110719782/183244835-ca21ff4a-63f6-46f8-b9d0-cc5a055db282.png)
看到您的图片，我在任务管理器里面没有找到（见上图）

在windows+r后是这样的，然后试图输入adb.exe
![image](https://user-images.githubusercontent.com/110719782/183244885-1778c048-5a64-4513-bd7a-9cf67c7c58f8.png)
![image](https://user-images.githubusercontent.com/110719782/183244902-79847345-c039-4d63-b2d0-787fa32f8982.png)

**Comment by zzyyyl** [comment]
Win + R之后输入 cmd，然后
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1473#issuecomment-1207188766

**Comment by ABA2396** [comment]
windows+r后输入cmd，在cmd窗口输入 `netstat -ano | findstr "5037"`查找哪个软件占用了5037端口，结束进程

**Comment by dongmeng123** [comment]
> 

![image](https://user-images.githubusercontent.com/110719782/183244959-5cd7a9a2-78aa-4d14-87e4-6426848e98f5.png)

**Comment by zzyyyl** [comment]
任务管理器那个，点进详细信息

**Comment by dongmeng123** [comment]
> netstat -ano | findstr "5037"

我输入以后，那个windows+r出现的窗口随着我点确认的时候消失不见了（惊恐

**Comment by zzyyyl** [comment]
输入 cmd

**Comment by ABA2396** [comment]
> > netstat -ano | findstr "5037"
> 
> 我输入以后，那个windows+r出现的窗口随着我点确认的时候消失不见了（惊恐

不是在那里面输入，输入cmd之后确定出现一个窗口，在那里面输入netstat -ano | findstr "5037"

**Comment by horror-proton** [comment]
> 我输入以后，那个windows+r出现的窗口随着我点确认的时候消失不见了（惊恐

打开一个 cmd 或者 powershell 再输入, 不是直接输入到 Windows+R 那个里面 (虽然这也能运行

**Comment by dongmeng123** [comment]
> 任务管理器那个，点进详细信息

![image](https://user-images.githubusercontent.com/110719782/183245123-32736e34-1d21-456f-857f-3e826f1a4973.png)
![image](https://user-images.githubusercontent.com/110719782/183245135-4ae7a65a-80a5-444f-89b0-155693fd792e.png)
没有见到adb.exe  qaq

**Comment by ABA2396** [comment]
> > 任务管理器那个，点进详细信息
> 
>  没有见到adb.exe qaq

不是让你关掉adb，是让你关掉刚刚用netstat -ano | findstr "5037"查出来占用5037端口号的PID，关掉PID对应的程序

**Comment by dongmeng123** [comment]
> netstat -ano | findstr "5037"

![image](https://user-images.githubusercontent.com/110719782/183245192-91965c55-4fea-4aca-a44b-73f6bb9499bf.png)
嘶 为什么会这样

**Comment by dongmeng123** [comment]
> > > 任务管理器那个，点进详细信息
> > 
> > 
> > 没有见到adb.exe qaq
> 
> 不是让你关掉adb，是让你关掉刚刚用netstat -ano | findstr "5037"查出来占用5037端口号的PID，关掉PID对应的程序

![image](https://user-images.githubusercontent.com/110719782/183245237-c2830bf7-6179-4093-99db-16a60a230976.png)
ohhhhhhhhh

**Comment by dongmeng123** [comment]
> > > 任务管理器那个，点进详细信息
> > 
> > 
> > 没有见到adb.exe qaq
> 
> 不是让你关掉adb，是让你关掉刚刚用netstat -ano | findstr "5037"查出来占用5037端口号的PID，关掉PID对应的程序

29392就是PID嘛（？  
我的任务管理器里面好像没有PID29392的（？
![image](https://user-images.githubusercontent.com/110719782/183245341-5bf49263-e60c-46f9-94a6-ea3d62615a2a.png)

**Comment by dongmeng123** [comment]
> > > 任务管理器那个，点进详细信息
> > 
> > 
> > 没有见到adb.exe qaq
> 
> 不是让你关掉adb，是让你关掉刚刚用netstat -ano | findstr "5037"查出来占用5037端口号的PID，关掉PID对应的程序
29392就是PID嘛（？
我的任务管理器里面好像没有PID29392的（？
![image](https://user-images.githubusercontent.com/110719782/183245374-6a9f0557-643a-4260-a408-5a26fcac1c9c.png)

**Comment by ABA2396** [comment]
还是下个[adb](https://dl.google.com/android/repository/platform-tools-latest-windows.zip)吧，然后软件里填上新下的adb的地址

**Comment by dongmeng123** [comment]
> 还是下个[adb](https://dl.google.com/android/repository/platform-tools-latest-windows.zip)吧，然后软件里填上新下的adb的地址

虽然当时，还是想请教您。他这里变来变去是正常的嘛（？
![image](https://user-images.githubusercontent.com/110719782/183245604-c955af6b-b729-4a56-a09d-130a1f83931d.png)

**Comment by ABA2396** [comment]
感觉不是很正常，感觉要么是短时进程要么是一直崩溃重启，换个adb吧

**Comment by dongmeng123** [comment]
> 感觉不是很正常，感觉要么是短时进程要么是一直崩溃重启，换个adb吧

好的我去搜一下下载adb，十分感谢大家的耐心回复，不知道哪里可以稍稍投喂一下大家，作为感谢请大家喝可乐XD

**Comment by ABA2396** [comment]
> 还是下个[adb](https://dl.google.com/android/repository/platform-tools-latest-windows.zip)吧，然后软件里填上新下的adb的地址

点这个蓝字就是下载

**Comment by dongmeng123** [comment]
> > 还是下个[adb](https://dl.google.com/android/repository/platform-tools-latest-windows.zip)吧，然后软件里填上新下的adb的地址
> 
> 点这个蓝字就是下载

okok感谢您！！

**Comment by dongmeng123** [comment]
> > 还是下个[adb](https://dl.google.com/android/repository/platform-tools-latest-windows.zip)吧，然后软件里填上新下的adb的地址
> 
> 点这个蓝字就是下载

![image](https://user-images.githubusercontent.com/110719782/183270999-482a8b17-5276-41e1-829f-994f4711ee41.png)
![image](https://user-images.githubusercontent.com/110719782/183271001-532ab8b7-042c-4c8a-b556-b78dbc472729.png)
实在不好意思！！下载了昨天您给的adb，今天选择了它的路径，还是连接失败。很奇怪，我昨天尝试重新下载夜神，刚下载是可以用的，然后今天打开又不能用了。
请问是改了adb路径之后，是链接地址也要改嘛

**Comment by Wpekxknkgf-2** [comment]
出现问题前你有没有安装或者卸载过其他的模拟器，我今天遇到过和你类似的报错。表现为在命令行提示符使用adb.exe connect ip:port命令可以连接，但是在MAA中Start后提示“连接失败……”。
问题发生时间是在已经安装了夜神的前提下，安装了雷电模拟器又卸载后发生的。推测是卸载雷电模拟器的时候把SysWOW64里一些adb相关一并删除了。
我自己的问题是通过将夜神模拟器安装文件夹（Program Files\Nox\bin）里adb.exe  AdbWinApi.dll AdbWinUsbApi.dl粘贴到C:\Windows\SysWOW64解决的，这也许对你有一定的借鉴价值。

**Comment by MistEO** [comment]
> > > 还是下个[adb](https://dl.google.com/android/repository/platform-tools-latest-windows.zip)吧，然后软件里填上新下的adb的地址
> > 
> > 
> > 点这个蓝字就是下载
> 
> ![image](https://user-images.githubusercontent.com/110719782/183270999-482a8b17-5276-41e1-829f-994f4711ee41.png) ![image](https://user-images.githubusercontent.com/110719782/183271001-532ab8b7-042c-4c8a-b556-b78dbc472729.png) 实在不好意思！！下载了昨天您给的adb，今天选择了它的路径，还是连接失败。很奇怪，我昨天尝试重新下载夜神，刚下载是可以用的，然后今天打开又不能用了。 请问是改了adb路径之后，是链接地址也要改嘛

再发下现在失败的日志

**Comment by dongmeng123** [comment]
> 出现问题前你有没有安装或者卸载过其他的模拟器，我今天遇到过和你类似的报错。表现为在命令行提示符使用adb.exe connect ip:port命令可以连接，但是在MAA中Start后提示“连接失败……”。 问题发生时间是在已经安装了夜神的前提下，安装了雷电模拟器又卸载后发生的。推测是卸载雷电模拟器的时候把SysWOW64里一些adb相关一并删除了。 我自己的问题是通过将夜神模拟器安装文件夹（Program Files\Nox\bin）里adb.exe AdbWinApi.dll AdbWinUsbApi.dl粘贴到C:\Windows\SysWOW64解决的，这也许对你有一定的借鉴价值。

确实之前下载过雷电模拟器，但是我是先卸载雷电后下载了夜神，而且夜神刚下载时是可以使用的，再次开机后就不能使用，是有些奇怪的www

**Comment by dongmeng123** [comment]
> > > > 还是下个[adb](https://dl.google.com/android/repository/platform-tools-latest-windows.zip)吧，然后软件里填上新下的adb的地址
> > > 
> > > 
> > > 点这个蓝字就是下载
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/110719782/183270999-482a8b17-5276-41e1-829f-994f4711ee41.png) ![image](https://user-images.githubusercontent.com/110719782/183271001-532ab8b7-042c-4c8a-b556-b78dbc472729.png) 实在不好意思！！下载了昨天您给的adb，今天选择了它的路径，还是连接失败。很奇怪，我昨天尝试重新下载夜神，刚下载是可以用的，然后今天打开又不能用了。 请问是改了adb路径之后，是链接地址也要改嘛
> 
> 再发下现在失败的日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9313275/asst.log)

大概情况是 6号重新下载了一次夜神，然后就可以正常运行，就打了一轮肉鸽。第二天打开就不能使用了，所以下载了您给的链接下载了adb，然后重新选择了adb的路径，然后还是连接失败。
今天卸载夜神换了雷电，还是连接失败（主要是它没能自动匹配，我也找不到雷电里面的adb文件）
辛苦您！！！！

**Comment by MistEO** [comment]
试试不要把模拟器装在中文目录下

**Comment by dongmeng123** [comment]
> 试试不要把模拟器装在中文目录下

之间装在d盘了，还是不行qaq

**Comment by dongmeng123** [comment]
> 试试不要把模拟器装在中文目录下

这个是我装在d盘后是日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9355970/asst.log)

**Comment by dongmeng123** [comment]
> 试试不要把模拟器装在中文目录下

每次都是重新下载安装后是可以用的，电脑重启后就不能用了qaq

**Comment by dongmeng123** [comment]
> > 还是下个[adb](https://dl.google.com/android/repository/platform-tools-latest-windows.zip)吧，然后软件里填上新下的adb的地址
> 
> 点这个蓝字就是下载

想问一下您，这个adb安装后只需要改adb路径，别的都不需要改嘛
（因为之前光改adb路径是不行的）

**Comment by ntgmc** [comment]
直接勾选自动连接，删除adb和端口，模式选择通用模式即可自动选择（更新后有时要这样）
该功能已经修复，感谢您的反馈！

**Comment by dongmeng123** [comment]
> 直接勾选自动连接，删除adb和端口，模式选择通用模式即可自动选择（更新后有时要这样） 该功能已经修复，感谢您的反馈！

很抱歉再次打扰您！似乎还是有类似问题！为您附上日志！
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12440660/gui.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12440662/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12440665/asst.log)
