### ISSUE TITLE
蓝叠中国版肉鸽的辅助招募无法识别梓兰

### ISSUE THREAD

**Issue by asd4036** [MaaAssistantArknights/MaaAssistantArknights#1474]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

蓝叠中国版肉鸽的辅助招募无法识别梓兰，会在辅助列表一直向左拖动，到程序设定的时间延迟判定后结束ORC并放弃选人。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9275247/asst.zip)
2022-8-6  22:45:15-22:46:40   日志的终段就是发生错误的地方，我在放弃选人的那一步后结束了软件的流程。

**Comment by MistEO** [comment]
挺奇怪的，完全没识别到，中间也不像有滑过头的样子，方便来几张图看看你肉鸽辅助招募界面干员是啥顺序么（左右拖动一下多来几张）

**Comment by asd4036** [comment]
大佬你好，很高兴接到你的反馈，我最近近卫练度提升了，所以开局近卫券选择银灰花掉6个点数之后，辅助券梓兰位置发生了变化（以前是选择泡普卡的，0费），所以没法再提供新的日志记录啥的，但可以给你提供当时选泡普卡后辅助券选人的截图。ps:在最新版本下，有可能是你的更新的作用或者因为我购买了6费银灰改变了梓兰在辅助券的位置（后者情况可能性不大，毕竟是ORC跟位置应该关系不大），梓兰已经可以被正确选用，可能已经被你修复了。








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月8日(星期一) 晚上10:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 蓝叠中国版肉鸽的辅助招募无法识别梓兰 (Issue #1474)





 
挺奇怪的，完全没识别到，中间也不像有滑过头的样子，方便来几张图看看你肉鸽辅助招募界面干员是啥顺序么（左右拖动一下多来几张）

**Comment by MistEO** [comment]
@zzyyyl labeler bot 只生效了一个
