### ISSUE TITLE
肉鸽 深入调查 几个刷量的任务可以自动去探索

### ISSUE THREAD

**Issue by ManutdGTA** [MaaAssistantArknights/MaaAssistantArknights#1478]
### 说说你遇到的问题？

到达第四第五层，可以不用去自动探索
但 招募几个干员，获得希望，收藏品，材料啥的可以通过以量取胜的方式慢慢完成

**Comment by MistEO** [comment]
没听懂（

**Comment by ABA2396** [comment]
> 没听懂（

就是想让MAA支持刷 `深入调查` 吧

**Comment by ManutdGTA** [comment]
> > 没听懂（
> 
> 就是想让MAA支持刷 `深入调查` 吧
对，就这个意思

**Comment by ntgmc** [comment]
现在支持了
该功能已经修复，感谢您的反馈！
