### ISSUE TITLE
肉鸽挂机 有时会卡在拾取剧目页面

### ISSUE THREAD

**Issue by SteveWang92** [MaaAssistantArknights/MaaAssistantArknights#1480]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽挂机时偶尔卡在剧目页面，猜测是因为第一次获得，需要点击两次，但是只点击了一次

不停止maa，手动点击一下屏幕后，就会直接放弃当次探索进行结算

附上了log，我在看到卡住的页面之后就手动停止了maa
下次再遇到我会传一份不停止maa 直接结算的log

时间点：
15:55:46 战斗完成
16:03:47 手动停止

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9276279/asst.-.zip)

### 截图

![夜神模拟器 2022_8_7 16_03_54](https://user-images.githubusercontent.com/26997414/183277789-3c600eac-b6d2-499c-955f-120232f84a24.png)
![MaaAssistantArknights - 夜神模拟器 (127 0 0 1_62001) 2022_8_7 16_10_02](https://user-images.githubusercontent.com/26997414/183277798-ab94b0af-9985-441f-bb28-dcdb9081b69a.png)

### 还有别的吗？

夜神模拟器 7.0.3.2
maa 4.2.2 4.2.3

**Comment by SteveWang92** [comment]
补充log

这次是卡在剧目获取页面之后不停止maa，手动点击一次屏幕，表现为maa退出探索进行结算

手动点击的时间是19:13左右
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9276515/asst.zip)

**Comment by ChildeRolando** [comment]
同，经常卡在剧目页面，从一个月之前刚开始用时就是这样

**Comment by MistEO** [comment]
需要一张原图，下次再卡住帮忙用模拟器自带的截图工具截张图发下

**Comment by SteveWang92** [comment]
![Screenshot_20220809-120404](https://user-images.githubusercontent.com/26997414/183554806-202949b0-5f2b-4b4d-9ff2-d93e822623d6.png)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9286458/asst.zip)
这是卡住时的截图和最新的log

猜测会不会因为点击太快了，但是游戏有延迟，所以没点击成功

**Comment by ChildeRolando** [comment]
![Screenshot_20220809-135522](https://user-images.githubusercontent.com/43607124/183641158-11502a6a-62dd-4a8f-b024-a07f60e2de33.png)

**Comment by Komori-AA** [comment]
同遇到过这个问题，但是没保存当时数据
