### ISSUE TITLE
关于肉鸽+夜神模拟器

### ISSUE THREAD

**Issue by cloudwind233** [MaaAssistantArknights/MaaAssistantArknights#1481]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

每次后台挂肉鸽的时候，过一段时间总是卡在某个界面不动，有的时候是一直卡死无法操作，有的时候模拟器直接崩溃。
最近一次专门测试并出现bug是8.7下午14:14。出现bug前已经关闭除模拟器、脚本、任务管理器意外的所有程序。
bug出现时游戏无法继续进行（通过干员再部署时间以及完全无法操作可知），maa提示模拟器断开正在尝试重连（图一）。我准备截图保存证据的时候突然模拟器（应该是吧）直接崩溃，然后弹出对话框“应用程序错误”（因为电脑卡得无法截屏，故手机拍屏），为图二。点击确定后模拟器关闭，maa仍在重连模拟器（图三）。
图四是之前测试bug的时候夜神崩溃报错1040，说是显卡驱动低于4.0（图中标注处，为4.6.0）后将渲染模式改为OpenGL+才解决故障（大概吧）。
在测试之前，无论是游戏内还是模拟器，都已经将画质帧率调到最低。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9276292/asst.log)

### 截图

![bug1](https://user-images.githubusercontent.com/110757514/183278578-ec83601f-3929-422d-b2b1-e5467620f24c.png)
![bug2](https://user-images.githubusercontent.com/110757514/183278580-ba42501d-738f-4264-a392-dece2931063f.jpg)
![bug3](https://user-images.githubusercontent.com/110757514/183278582-f7a8efa4-dd81-4321-9d86-b0ee919624ae.png)
![bug4](https://user-images.githubusercontent.com/110757514/183278583-98bde7d3-bf14-4eea-9a0a-dd72f387f560.png)

**Comment by cloudwind233** [comment]
之后电脑太卡完全无法操作重启了一次电脑和maa，可能导致日志被覆盖，如果不行我在重新测试一次

**Comment by zhongfly** [comment]
我的低配笔记本用夜神也会这样。主要原因是电脑配置低
和maa关系不大

**Comment by MistEO** [comment]
模拟器崩了实在没有办法，考虑换个模拟器试试，听群友说雷电吃性能比较低，但我自己这里雷电总是有奇奇怪怪的问题（所以我在文档里说不推荐使用），有兴趣的话可以试一下

**Comment by cloudwind233** [comment]
换了一下蓝叠国内版，应该是没什么问题了，谢谢大佬

> 模拟器崩了实在没有办法，考虑换个模拟器试试，听群友说雷电吃性能比较低，但我自己这里雷电总是有奇奇怪怪的问题（所以我在文档里说不推荐使用），有兴趣的话可以试一下
