### ISSUE TITLE
可以考虑把基建收取和基建换班的功能拆分开

### ISSUE THREAD

**Issue by starrin** [MaaAssistantArknights/MaaAssistantArknights#1487]
### 说说你遇到的问题？

我的基建用着自己的比较极端的排班表，收益我自己很满意，不希望工具帮我换班，但有的比较忙的时候希望由工具帮我完成收取基建的工作，目前工具的设计似乎收取和换班是捆绑在一起的，无法单独进行
不算太大的痛点，但在我这觉得如果加上会更好，也不会带来太大的工作量

### 有什么好的想法？

在基建换班的部分增加只收取不换班的选项，可以默认不开启

**Comment by zzyyyl** [comment]
duplicate of #1234

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/183422232-0a8a59ad-e175-49e0-8f75-e5ceead5af27.png)
![image](https://user-images.githubusercontent.com/18511905/183422245-7e179d7d-4e25-49ad-a84d-d30b315b6b90.png)

附张图，就像这样。我自己简单测了两次应该没啥问题

**Comment by starrin** [comment]
> ![image](https://user-images.githubusercontent.com/18511905/183422232-0a8a59ad-e175-49e0-8f75-e5ceead5af27.png) ![image](https://user-images.githubusercontent.com/18511905/183422245-7e179d7d-4e25-49ad-a84d-d30b315b6b90.png)
> 
> 附张图，就像这样。我自己简单测了两次应该没啥问题

我试过，直接不收

**Comment by MistEO** [comment]
不收那就是 bug, 重开个 bug 反馈来个日志看看
