### ISSUE TITLE
肉鸽：雕匠与石像部署bug

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#1489]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

RT
如图所示，会卡关，需要等待maa全撤了，导致效率降低

### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9279761/asst.-.log)

### 截图

![image](https://user-images.githubusercontent.com/74061867/183364353-102acdd0-46c0-43cc-90f7-e1dc88aaefe5.png)

**Comment by zzyyyl** [comment]
我觉得这不算是 bug（x

**Comment by irrrrrrrr** [comment]
我的会把高台干员部署在前面（悲）
