### ISSUE TITLE
选择自动使用加急许可时 自动公招出现未知bug

### ISSUE THREAD

**Issue by SteveWang92** [MaaAssistantArknights/MaaAssistantArknights#1491]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选择自动使用加急许可时，自动公招出现未知bug，信息为‘出现错误，已返回’

如果当前没有进行中的招募，maa直接在公招页面等待一段时间报错

如果有进行中的招募，maa会使用一次加急，然后点开一个空格位置，等待一段时间报错

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9281332/asst.zip)

### 截图

![MaaAssistantArknights - 夜神模拟器 (127 0 0 1_62001) 2022_8_8 21_26_44](https://user-images.githubusercontent.com/26997414/183408003-fb5b1fb7-48ab-40ea-87d9-3f009f64611a.png)

### 还有别的吗？

夜神 7.0.3.2
maa 4.2.3

**Comment by SteveWang92** [comment]
补充

刚才又测试了一下，问题也许出在第四个位置上是六星/一星tag，选择使用加急时的自动公招会一直在第四个位置加急/招募，如果这里是一个没有自动确认的tag，程序就会卡住

**Comment by horror-proton** [comment]
看上去这是因为 *是否消耗一张加急许可立即完成招募?* 的确认按钮按了一次之后卡了, 然后又按了一次, 错误点开了第四个位置

**Comment by MistEO** [comment]
> 我注意到好像之前的一次公招任务居然也出现了完全相同的问题, ~也许确实是卡的时间比较准,~ 问一下如果你手动点那个勾, 是不是会卡大约一秒左右才能完成确认

识别下公招 flag？

**Comment by horror-proton** [comment]
改过之后可以容忍这个问题发生几次, 不会马上失败, 但可能还需要更好的修复方法, 比如把 `RecruitNow` 设成仅使用加急许可而不确认招募

**Comment by SteveWang92** [comment]
> 我注意到好像之前的一次公招任务居然也出现了完全相同的问题, ~也许确实是卡的时间比较准,~ 问一下如果你手动点那个勾, 是不是会卡大约一秒左右才能完成确认

是的，原来只有我一个人吗。可能因为我在国外，一般的操作都需要一两秒的时间来确认

**Comment by horror-proton** [comment]
> 是的，原来只有我一个人吗。可能因为我在国外，一般的操作都需要一两秒的时间来确认

如果你发现操作延迟比较大的话, 可以打开软件目录下的 resource/config.json 文件, 把里面的 `taskDelay` 数值给调大
