### ISSUE TITLE
当有 commit 提及 `fix`, `close` 某个 issue 时候，自动为该 issue 打上 `fixed` label

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#1492]
### 说说你遇到的问题？

比如 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/02bfb6b160113d75c657ad4a1a265566aa7736a5 (*^▽^*)

**Comment by zzyyyl** [comment]
还有 duplicate

**Comment by zzyyyl** [comment]
> > 还有 duplicate
> 
> 这太容易误判了吧

我指的是 issue comment，谁发一个 [Dd]uplicate of #xxxx 自动给当前的加上 `duplicate`

**Comment by MistEO** [comment]
好耶

**Comment by MistEO** [comment]
我说的 fix 是 commit 啊，不是 comment _(:з」∠)_

**Comment by zzyyyl** [comment]
> > 我说的 fix 是 commit 啊，不是 comment _(:з」∠)_
> 
> 我知道（ 估计要开一个新的 action 了（

要不干脆整一个 MeoIssueBot 扔到组织仓库里（

**Comment by MistEO** [comment]
那整！
