### ISSUE TITLE
基建一个房间只放两个人

### ISSUE THREAD

**Issue by ChildeRolando** [MaaAssistantArknights/MaaAssistantArknights#1495]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

两个三级贸易站里面都只放了两个人，之前在制造站也有过相同的情况
不知复现条件是什么，出现概率并不高
### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9287072/asst.-.log)

### 截图

![Screenshot_20220809-072427](https://user-images.githubusercontent.com/43607124/183571038-249d4807-75a4-45ef-9162-70048cc6dbbe.png)

**Comment by MistEO** [comment]
类似的问题有不少朋友报过了，但是一直没啥头绪，看日志都是一切正常

有机会的话帮忙看下到底是怎么操作的，是选人的时候就少选了一个？还是正常选了人，后面又把他塞到宿舍去了？还是啥别的情况
