### ISSUE TITLE
在存在没通关地图的情况下，剿灭会在拿满奖励后仍一直打

### ISSUE THREAD

**Issue by ChildeRolando** [MaaAssistantArknights/MaaAssistantArknights#1497]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

比方说北原冰封废城没有拿到400杀，
虽然这周剿灭已经打满，仍会浪费体力去开废城，然后寄掉再一直开
因为右上角的剿灭TODO是存在未开荒地图的
目前的判断逻辑只适合剿灭已经完全毕业的账号
建议是加个OCR判断 已获取合成玉/合成玉上限 == 1
### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9288110/asst.-.log)
8/9 9:15左右

**Comment by ABA2396** [comment]
勾选指定材料，材料选合成玉，数量填还差多少合成玉。或者直接指定次数就好了吧？

**Comment by ChildeRolando** [comment]
> 勾选指定材料，材料选合成玉，数量填还差多少合成玉。或者直接指定次数就好了吧？

我不是用GUI的，我用的python API，在一号多人使用的情况下，不能获知已获取合成玉数量/正确停止就没办法设计算法每周自动剿灭

**Comment by ChildeRolando** [comment]
> 勾选指定材料，材料选合成玉，数量填还差多少合成玉。或者直接指定次数就好了吧？

而且如果当期剿灭没打过的话，也不会自动去刷市区

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
