### ISSUE TITLE
剿灭在打完一次后会因为指引面板弹出卡在某个页面

### ISSUE THREAD

**Issue by ChildeRolando** [MaaAssistantArknights/MaaAssistantArknights#1499]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在第一次全权委托之后会卡在这，本来设计上会一次点过这个页面，但是因为弹出了一个指引面板，所以只点掉了指引面板，卡在了这个页面
![Screenshot_20220809-114228](https://user-images.githubusercontent.com/43607124/183619291-37654ec0-8ebb-4f5e-9a81-90d194042536.png)

### 日志文件

不需要日志了吧

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
