### ISSUE TITLE
自动公招中自动使用加急许可一项在重启后不保存设置及相关问题的建议

### ISSUE THREAD

**Issue by lhfhybxm** [MaaAssistantArknights/MaaAssistantArknights#1500]
### 说说你遇到的问题？

很显然，绝大多数人在使用你软件之前都没有耐心每次公招都使用加急许可（这主要是因为其确认过程过于繁琐所导致的）。这些人目前的加急许可都处于（很有可能是严重处于）溢出状态。以我为例，我目前拥有170张招聘许可，但是加急许可却有400张。
因此我有理由认为，自动使用加急许可并非是类似于碎源石一类需要谨慎考虑的内容，无需不保存设置
对于忘记关闭这一选项并且加急许可耗尽这一特殊情况，我认为无需担心。你软件会因识别错误自动跳过公招项目。
我谨顺带提出另一项建议，当部分项目出错时弹出系统通知，用于告知用户该项目并未完全执行

### 有什么好的想法？

我谨提出我的建议：
取消自动使用加急许可一项在重启后不保存设置
当部分项目出错时弹出系统通知
具体理由见上

### 其他内容

第二项建议主要是为了电脑配置低下的用户考虑的。很显然，他们会经常遇到项目执行错误的问题。事实上，这个建议我认为更为重要。
非常感谢你的付出，和提供其他语言的支持。这为我和我的朋友提供了一定程度的方便

**Comment by MistEO** [comment]
@horror-proton @zzyyyl @ABA2396 你们怎么看（

**Comment by ABA2396** [comment]
我感觉没必要改，白票多了可以一次刷完，留几张加急也可以在出小车或者高星的时候直接加速

**Comment by horror-proton** [comment]
如果资源没有耗尽, 因识别错误自动跳过公招项目是不正常的, 如果发现频繁出现这种情况, 应该提出 issue, 如果怀疑是网络延迟引起的, 可以尝试适当调大 resource/config.json 中的 `taskDelay` 的数值
