### ISSUE TITLE
公招识别自动公招时间设置

### ISSUE THREAD

**Issue by Yaklo** [MaaAssistantArknights/MaaAssistantArknights#1501]
### 有什么好的想法？

默认词条时间设置7小时40分，高资自动9小时
或者添加选项，让用户自己决定该如何设定时间

**Comment by zzyyyl** [comment]
Duplicate of #137

**Comment by MistEO** [comment]
我还和之前的 issue 中一样的想法，倾向于不做。

~~不过现在公招有 @horror-proton 大佬帮忙了他要是愿意做我也没意见~~

**Comment by zzyyyl** [comment]
会很麻烦（

因为原来只用识别小时的数字（

**Comment by horror-proton** [comment]
> 会很麻烦（
> 
> 因为原来只用识别小时的数字（

那直接 OCR 得了, ~~这么大的数字应该不会识别歪掉吧~~
还有一个问题就是如何点击最少的次数调到对应的时间

**Comment by Yaklo** [comment]
> > 会很麻烦（
> > 因为原来只用识别小时的数字（
> 
> 那直接 OCR 得了, ~这么大的数字应该不会识别歪掉吧~ 还有一个问题就是如何点击最少的次数调到任意的时间

我觉得直接正向调就好了，省事不容易出错。反正要快肯定都是自己上手调

**Comment by MistEO** [comment]
调时间是不受网络影响的，我觉得要不识别到 1 （小时）之后，就别识别了时间了，直接识别 向下的按钮 然后点击它算了，做个 ProcessTask 从 1:00 变成 7:40 这种

**Comment by horror-proton** [comment]
> 调时间是不受网络影响的，我觉得要不识别到 1 （小时）之后，就别识别了时间了，直接识别 向下的按钮 然后点击它算了，做个 ProcessTask 从 1:00 变成 7:40 这种

现在是先盲调时间, 确认之前校验时间是否设置正确, 因为之前好像提到因为刷新标签的延迟, 时间可能设定失败, 那个 01 小时的模板并没有被使用 ~~(而且刚被我删掉)~~
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/300#issuecomment-1073287984

**Comment by zzyyyl** [comment]
我觉得干脆做一个 `x:y0` 调到 `a:b0` 的 Task （就是会麻烦一点）
这样还能在一次没调对的情况下再次调用（

顺带一提，方舟有时候会莫名其妙地 ”正在连接“，包括之前说过的 基 建 选人也有可能是突然卡出一个正在连接然后没选上（

**Comment by horror-proton** [comment]
> 我觉得干脆做一个 `x:y0` 调到 `a:b0` 的 Task （就是会麻烦一点） 这样还能在一次没调对的情况下再次调用（
> 
> 顺带一提，方舟有时候会莫名其妙地 ”正在连接“，包括之前说过的 基 建 选人也有可能是突然卡出一个正在连接然后没选上（

用 cpp 写倒是不难, 用 task 怎么写? 
现在假如发现时间没调对会先关闭槽位再打开的, 实际只需要从 `01:00:00` 开始调. 
主要问题是现在怎么识别时间, 是用 OCR 还是给每个数字都加一个模板...

**Comment by zzyyyl** [comment]
那当然 OCR

**Comment by MistEO** [comment]
加上选项了，下个版本体现~
