### ISSUE TITLE
【关闭模拟器】功能为什么不能直接用adb reboot -p来实现

### ISSUE THREAD

**Issue by xyxyx718** [MaaAssistantArknights/MaaAssistantArknights#1504]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA的【完成后关闭模拟器】功能在蓝叠模拟器Hyper-V版本无效，我看了以前的反馈，大概是通过杀进程的方法来关闭模拟器的。
但是我在命令行运行adb reboot -p之后模拟器就直接退出了，为什么不通过这种方法来实现呢？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9295621/asst.log)

### 截图

![20220810-084230775_4](https://user-images.githubusercontent.com/59339633/183787797-9ccadc51-a539-4002-a1e9-53f60974ab97.gif)

### 还有别的吗？

蓝叠模拟器Hyper-V版本 5.9.0.1061 N64 ；
Windows 11 21H2 ；
gif中的命令行内容：
cd C:\Program Files\BlueStacks_nxt\
HD-Adb connect 127.0.0.1:6937
HD-Adb reboot -p

**Comment by zzyyyl** [comment]
并不是所有的模拟器都能用 adb reboot 实现关机的（

_而且现在的关机任务应该是由GUI实现的_

**Comment by horror-proton** [comment]
这样只能让虚拟机关机, 并不能关闭部分模拟器的前端

**Comment by xyxyx718** [comment]
了解了，既然不通用就没办法了
