### ISSUE TITLE
开机自动启动无效

### ISSUE THREAD

**Issue by Private233** [MaaAssistantArknights/MaaAssistantArknights#1505]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![QQ截图20220810100045](https://user-images.githubusercontent.com/108540840/183794004-583b645f-a4b5-4ef5-9660-5527ef5f783f.png)
MAA“开机自动启动”没有运行，另外两个打勾选项是正常运行的

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9295923/asst.log)

### 截图

![$QC}FUNOR(} OP$}HC9IG4R](https://user-images.githubusercontent.com/108540840/183794150-9af878fd-b5f3-4477-9cfa-ea71d61dc5b0.png)
![XD%VS$R8Y JBY(F4Q YKC@U](https://user-images.githubusercontent.com/108540840/183794152-2d08bd4b-f111-4f1b-a663-fc7c233aa231.png)
第一张是系统的图，第二张是火绒的图，至少说明权限都是开的，不是很懂这个无效

### 还有别的吗？

mumu模拟器2.6.37.0
MAA4.2.3

**Comment by zzyyyl** [comment]
fixed by #1507
