### ISSUE TITLE
肉鸽招募时判断是否可精二

### ISSUE THREAD

**Issue by lhhxxxxx** [MaaAssistantArknights/MaaAssistantArknights#1508]
### 说说你遇到的问题？

![image](https://user-images.githubusercontent.com/91231470/183932773-934c1d61-9ec3-45c1-a5c5-16aec1843c66.png)
现行的精二逻辑检测无法判断精一满级的干员是否可精二

### 有什么好的想法？

![image](https://user-images.githubusercontent.com/91231470/183933337-1cf0c582-c686-4887-806b-93ae32efe2c1.png)
![image](https://user-images.githubusercontent.com/91231470/183933395-89d1d2ff-f9ac-4536-9ac7-573605f9a38b.png)
招募时检测左侧的字样可以区分精一满级和可精二干员（此处四月为精一满级，陨星可精二）

### 其他内容

ttml

**Comment by MistEO** [comment]
谁提的谁写.jpg

另外 @zzyyyl MAA-Team 呢（

**Comment by lhhxxxxx** [comment]
锅要一起背（）
我先去看看能不能给战斗掉落多个收藏品应用优先逻辑
