### ISSUE TITLE
请问日服能用吗

### ISSUE THREAD

**Issue by kiritoer** [MaaAssistantArknights/MaaAssistantArknights#151]
看到了美服的配置文件。想请教日服该如何使用

**Comment by MistEO** [comment]
不行，因为现在的 ocr 模型只支持中英文，日文换模型可能也可搞，但是需求太小众了而且改起来很麻烦，所以短期内应该不会去支持_(:з」∠)_

**Comment by feed1stblood** [comment]
@MistEO 请问英文现在能用么？试了一下全部任务都失败了，像是不认字

**Comment by MistEO** [comment]
> @MistEO 请问英文现在能用么？试了一下全部任务都失败了，像是不认字

请参考 [详细介绍](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md#%E6%88%91%E6%98%AF%E5%9B%BD%E9%99%85%E6%9C%8D%E7%8E%A9%E5%AE%B6%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E4%B9%88)，下载的包里应该有美服的资源

**Comment by feed1stblood** [comment]
> > @MistEO 请问英文现在能用么？试了一下全部任务都失败了，像是不认字
> 
> 请参考 [详细介绍](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md#%E6%88%91%E6%98%AF%E5%9B%BD%E9%99%85%E6%9C%8D%E7%8E%A9%E5%AE%B6%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E4%B9%88)，下载的包里应该有美服的资源

谢谢，我刚才找到了就把评论删了，没想到这么快就回复了。

**Comment by MistEO** [comment]
In progress: https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1082
