### ISSUE TITLE
会客室中线索放置不完全

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#1517]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Hi Maa Team,

软件在会客室中会放一部分已有的线索但不会全放。我录了个屏来展示。

Regards,
kxdxzr

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9305449/asst.log)

### 截图

会客室录屏：
[明日方舟 - MuMu模拟器 2022-08-11 11-19-49 (online-video-cutter.com).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9305453/-.MuMu.2022-08-11.11-19-49.online-video-cutter.com.zip)

### 还有别的吗？

模拟器：MUMU
系统：win11家庭版

**Comment by MistEO** [comment]
之前看过一次，没什么头绪。后面这块改了一点，如果再出现麻烦再提一下吧
