### ISSUE TITLE
刷理智时自动点到了保全派驻

### ISSUE THREAD

**Issue by cglcv** [MaaAssistantArknights/MaaAssistantArknights#1520]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷图时自动点进了保全派驻模式，然后卡在那里
怀疑是点到了终端右上角保全派驻的按钮上

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9308447/asst.log)
发生时间约19：58

### 截图

![屏幕截图 2022-08-11 195926](https://user-images.githubusercontent.com/35825310/184130041-988c2d36-be07-49a3-bd4b-09e7f3aefb60.png)
![Screenshot_2022 08 11_19 59 46 271](https://user-images.githubusercontent.com/35825310/184130104-6723ac83-a9c6-4cb3-9678-d4822413aa30.png)
![Screenshot_2022 08 11_20 00 36 804](https://user-images.githubusercontent.com/35825310/184130124-42409dc8-f443-41d7-a8f3-0b580d4822e0.png)

### 还有别的吗？

模拟器蓝叠Hyper-V
MAA 4.2.4
Windows11

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
