### ISSUE TITLE
优化 Maa 的构建

### ISSUE THREAD

**Issue by LiamSho** [MaaAssistantArknights/MaaAssistantArknights#1522]
- [x] 什么时候 C# 生成文档了。。。多了个 MeoAsstGui.xml
~~- [ ] 加入 Core 的 Linux Build 脚本并尝试 Action 构建 （寄）~~

**Comment by MistEO** [comment]
wow，好！！！

**Comment by MistEO** [comment]
看起来是没戏了（？）
