### ISSUE TITLE
在夜神模拟器中识别不到IC-9

### ISSUE THREAD

**Issue by sekipo** [MaaAssistantArknights/MaaAssistantArknights#1527]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在夜神模拟器中识别不到IC-9

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9312936/asst.bak.log)

**Comment by MistEO** [comment]
卡在哪了，来个图看看

**Comment by sekipo** [comment]
视频可以不

**Comment by sekipo** [comment]
https://user-images.githubusercontent.com/111097714/184268080-785bce73-c5e8-4162-824f-a9ca32f018a6.mp4

**Comment by ABA2396** [comment]
日志发错了吧，在里面都是2022-08-04和2022-08-05的日志

**Comment by sekipo** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9313910/asst.log)

**Comment by sekipo** [comment]
> 日志发错了吧，在里面都是2022-08-04和2022-08-05的日志

重新发了
