### ISSUE TITLE
完成后【退出并关闭模拟器】无法正常执行

### ISSUE THREAD

**Issue by shiguang2016** [MaaAssistantArknights/MaaAssistantArknights#1531]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选择完成后【退出并关闭模拟器】，任务完成后模拟器界面被关闭，但是后台留有模拟器进程占用大量cpu

### 日志文件

![asst zip](https://user-images.githubusercontent.com/68940402/184281677-556df078-32b7-45ef-9779-f3763e40ca55.jpg)

### 截图

![微信图片_20220812114513](https://user-images.githubusercontent.com/68940402/184281711-91b9f81f-6295-4749-a821-3b441f89f097.jpg)

### 还有别的吗？

夜神模拟器
![QQ截图20220812114948](https://user-images.githubusercontent.com/68940402/184281808-3f02c0fd-c395-4b12-8827-f51563007c77.png)

**Comment by shiguang2016** [comment]
日志文件无法正常上传
我传到这了
https://unlimited.lanzouy.com/iEkXM09fa14f

**Comment by zzyyyl** [comment]
Add GUI
