### ISSUE TITLE
不能识别多开的蓝叠模拟器的端口

### ISSUE THREAD

**Issue by ChSF001** [MaaAssistantArknights/MaaAssistantArknights#1533]
最近挖出了这个好玩的项目，首先感谢开发者大大们，节省了我每日长草的时间。

    本人使用蓝叠国际版hyper-v 5.4.100，双开了俩个Nougat64, 使用第二个玩方舟，参考用户文档配置了自动识别adb服务端口，结果仅仅能识别第一个系统，而不能正常识别第二个系统。

   本人的蓝叠生成bluestacks.conf如下：

```properties
# Other configurations
# Instance 1
bst.instance.Nougat64.status.adb_port="60874"
# Other configurations
# Instance 2
bst.instance.Nougat64_2.status.adb_port="53048"
# Other configurations
```

    本人多次修改该文件，把系统1从配置中删去，只留下系统2，得出一个结论，这个端口配置检索应该是通过Nougat关键字去识别的吧，如果是Nougat64_2就不能正常的识别吧。

    以上问题本人可以通过手动配置端口去解决，但考虑到开发者已经能智能识别第一个端口，何不去适配一下多开了？

**Comment by ChSF001** [comment]
第一次在Github上写Markdown,排版不行，还请赏光😁

**Comment by MistEO** [comment]
感谢你的反馈，但需求建议请使用 `需求建议` 模板，我们的 bot 会自动进行一系列的操作，而不是使用 `其他议题`

![image](https://user-images.githubusercontent.com/18511905/184353665-16bfc6ca-47cb-4c50-8a6f-6c1dcb0c8469.png)

**Comment by MistEO** [comment]
想了一下倒也不难实现，把 `Nougat64` 也放到配置文件里，如果有需要可以自己修改，是不是就行了？
