### ISSUE TITLE
关于基建训练室干员换班的建议

### ISSUE THREAD

**Issue by 1317** [MaaAssistantArknights/MaaAssistantArknights#1534]
### 说说你遇到的问题？

训练室协助加速专精的干员会被换下（到宿舍，制造站，贸易站，etc. 去），导致专精无法加速时间

### 有什么好的想法？

1. 自动识别专精干员及其协助者，若其在训练室则跳过对其换班
2. 根据训练室当前训练中的干员职业、协助者的技能和心情状态，自动选择合适的协助者

_similar issue #763_

**Comment by MistEO** [comment]
现在应该可以用自定义换班 + “未进驻” 选项来解决了
