### ISSUE TITLE
关于夜半干员在肉鸽中放置地面单位问题

### ISSUE THREAD

**Issue by hua1163668195** [MaaAssistantArknights/MaaAssistantArknights#1538]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

夜半属于高台先锋干员   但在行动中却放置 地面  这导致了干员无法正常放置### 

### 日志文件

夜半属于高台先锋干员   但在行动中却放置 地面  这导致了干员无法正常放置### 

### 还有别的吗？

夜半属于高台先锋干员   但在行动中却放置 地面  这导致了干员无法正常放置###

**Comment by MistEO** [comment]
什么版本，现在的版本压根不会选夜半的

**Comment by zzyyyl** [comment]
夜半在肉鸽设置中已经被ban了，你这估计是临时招募，属于极小概率事件了（

**Comment by MistEO** [comment]
另外希望你是真的看了这几句话才打勾的，我们是用爱发电的开源项目，不是那种大公司搞什么免责声明看都不看直接点掉。希望你真的看了这几句话并且进行了对应的操作再来提问

![image](https://user-images.githubusercontent.com/18511905/184360580-7e307e01-4820-4f0d-aa58-872c5684f6ef.png)
