### ISSUE TITLE
重构 Resource 及相关资源管理类

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#1541]
### 说说你遇到的问题？

RT, 是时候推倒屎山了

**Comment by et2012** [comment]
肉鸽招募系统的优化我也准备推翻重做，内置资源的方式确实不好。
这种设置就应该从 UI 传入，由用户自定义。

**Comment by MistEO** [comment]
> 肉鸽招募系统的优化我也准备推翻重做，内置资源的方式确实不好。
> 这种设置就应该从 UI 传入，由用户自定义。

不好，不应该把那么复杂的配置交给用户

**Comment by et2012** [comment]
> > 肉鸽招募系统的优化我也准备推翻重做，内置资源的方式确实不好。
> > 这种设置就应该从 UI 传入，由用户自定义。
> 
> 不好，不应该把那么复杂的配置交给用户

行吧，等你们重构结果了，我不管了。我在自己的仓库自娱自乐就行了。
