### ISSUE TITLE
贸易站干员选择问题

### ISSUE THREAD

**Issue by Private233** [MaaAssistantArknights/MaaAssistantArknights#1545]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

贸易站用的空弦，海蒂，雪雉三人，maa把雪雉给换成能天使了，心情轴就对不上了阿（
当时雪雉心情还有一半，阈值设的20%，试了两次都是这样

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9330522/asst.log)
今天早上早些时候

### 还有别的吗？

mumu模拟器
maa4.2.4

**Comment by MistEO** [comment]
maa 不对心情轴的，效率一样的情况下选心情高的，一般来说似乎没啥问题？_(:з」∠)_

**Comment by Private233** [comment]
> maa 不对心情轴的，效率一样的情况下选心情高的，一般来说似乎没啥问题？_(:з」∠)_

明白了
