### ISSUE TITLE
[Feature Request] 当设置为蓝叠模拟器时，自动识别 bluestacks.conf 中的 ADB 端口号

### ISSUE THREAD

**Issue by Mark9804** [MaaAssistantArknights/MaaAssistantArknights#1547]
### 说说你遇到的问题？

在国际版 Bluestacks 5 当中，蓝叠不再支持自定义 ADB 端口号，仅在模拟器开始运行时随机生成。[reference](https://www.reddit.com/r/BlueStacks/comments/qzlhg9/disabling_randomized_adb_port_on_bluestacks_5/)

但是可以通过读取 `C:\ProgramData\BlueStacks_nxt\bluestacks.conf` 第 90 行的内容来获取本次运行时随机生成的端口号

```
bst.instance.Nougat64.status.adb_port="7160"
```

### 有什么好的想法？

启动时：
1. 尝试连接模拟器，如果未成功：
2. 如果当前配置是蓝叠模拟器：
3. 尝试启动模拟器，并等待启动 timeout
4. timeout 结束后，如果存在文件  `C:\ProgramData\BlueStacks_nxt\bluestacks.conf`：
5. 读取文件中 `bst.instance.Nougat64.status.adb_port` 的配置值，并尝试使用此值作为端口号进行连接

**Comment by ABA2396** [comment]
Add GUI

**Comment by cglcv** [comment]
[蓝叠模拟器国际版 Hyper-V 版本](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.md#-%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E5%9B%BD%E9%99%85%E7%89%88-hyper-v-%E7%89%88%E6%9C%AC)

现在也有的，但是哪种模拟器模式都生效
~要不考虑下读`bluesteak.conf`的生效范围吧~

**Comment by MistEO** [comment]
楼上提供的方法，就是用你说的读取 conf 文件的方式实现的

**Comment by Mark9804** [comment]
我的问题，没发现 GUI 里面有这个选项还以为没做功能
