### ISSUE TITLE
是不是可以考虑遵循 git flow 提交规范

### ISSUE THREAD

**Issue by et2012** [MaaAssistantArknights/MaaAssistantArknights#1549]
### 有什么好的想法？

虽然 MAA Team 没有明确说过用的是 git flow，但分支模型应该是参考 git flow，那是不是考虑遵循一些 git flow 的基本规范：
- master 不能直接推送只能合并，每次合并都是一次版本发布
- dev 应该保持线性，每个提交就是一个功能点
- feat 分支开发完后，squash 为一个提交，合并回 dev

另外，如果默认拉取行为是 merge，推送时如果远程分支有更新，会出现一条 Merge branch 'dev' into dev 的提交，虽然扯上这个人有点小题大做：但这真的是 Linus 都吐槽过的，这种提交会破坏分支的线性，出现莫名其妙的分叉和拐弯。

---

这个问题我憋了很久了，所以下面的发言可能会带点情绪，下面这一段之后可能会删掉：

本来以一个业余项目来说，怎么提交都问题不大。
但以我最近提的几个 PR 和 issue 的反馈来说，MAA 团队对 Contribution 的要求还是挺严格的。
那么是否对 MAA Team 也一视同仁，把提交的质量也提上来？因为我观察了最近的一些提交，真的有点一言难尽。
Contributor 想 PR 一点东西，MAA Team 会全方位的检查；但 MAA Team 自己写的代码，就随便怎么来是吗？
master 随便推，dev 上的一个功能连着 push 好几个 fix，是完全没有在 feat 分支上测试过吗？
还有 Merge master into dev / Merge dev into feat，真的是万物皆可 merge。
这样的做法是不是跟你们对 Contribution 的高标准有点冲突？

以上这些跟代码质量无关，只是提交方式显得有点业余。

最后，毕竟 C++ 不是我擅长的领域，可能我也没完全理解 MAA Team 的逻辑，所以我还是暂时做个伸手党，只提 issue 不提 PR 比较好。

**Comment by horror-proton** [comment]
之前好像有人抱怨过 push 的时候应该用 rebase 不要 merge, 但还是有不少 (?) 成员经常用 merge, 导致现在历史还是一团糟 😿

**Comment by MistEO** [comment]
我们没要求过 commit 数量，经常有 pr 不也是一堆乱糟糟的 fix 就直接合了吗。这个有分过是不是 member？

严格的审核审的是代码内容，不是 commit 内容和数量。git 只是为代码服务的工具而已，想让它变好是好的，但没法要求所有人。

**Comment by MistEO** [comment]
- 往 master 乱推：因为最近在改 github bot / readme 文档，推到 dev 是不生效的 / 别人看不见的
- 不 squash ：方便大家水提交数（

我们也从来没说过一定要遵循 git flow，应该没有哪个 pr 说commit 不符合要求，你不改我不合的吧？还是那句话 git 是为代码服务的。

**Comment by MistEO** [comment]
另外，所有的 member 都是在我们的开发群里的，我们在做一个大点的功能前也会互相讨论很长时间。pr 里没有审核也不代表我们没有在群里互喷。

当然，加这个群是 free 的。

**Comment by et2012** [comment]
> 我们没要求过 commit 数量，经常有 pr 不也是一堆乱糟糟的 fix 就直接合了吗。这个有分过是不是 member？
> 
> 严格的审核审的是代码内容，不是 commit 内容和数量。git 只是为代码服务的工具而已，想让它变好是好的，但没法要求所有人。

“没法要求所有人” 的意思是不是：你没法要求 member 遵守提交规范（因为他们 push 不需要经过审查）。
换个角度说，member 是不是某种敲门砖，只要成为 member，就能豁免某些东西？
我想说的是 member 的提交质量不够高，有改进的空间。

代码内容方面我没法说什么，毕竟 C++ 不是我擅长的领域。不过我有点不满的是：
- 我提出改进想法 => 谁提的谁写
- 我写了，再提个 issue 收集意见 => 没人反馈
- 我准备换一种改进思路 => 不好。既然你有想法，那为什么不说、或者自己写？

既然你们 MAA Team 有一套标准，那是不是应该让 Contributor 知道这套标准是什么，应该怎么配合你们。
而不是我们提出什么，你们都说 “谁提的谁写”，写完了又说不好。

**Comment by MistEO** [comment]
请注意，我回复的所有的 “谁提的谁写”，author  **全部** 都是我们的 member，~~当然可能他没有设置成 public~~，我们从来没有，也永远不会对新来的的朋友发出 “谁提的谁写” 这种傻逼的要求

**Comment by MistEO** [comment]
虽然说这话有点昧良心：我觉得我们严格审核并说清楚要如何修改已经非常不错了，不知道你有没有给其他 repo 提 pr 的经历，辛辛苦苦写了很久的提交，被束之高阁，几个月没人理，然后来一句 outdated 直接 close 掉，这种太常见了。

**Comment by et2012** [comment]
> 请注意，我回复的所有的 “谁提的谁写”，author **全部** 都是我们的 member，~当然可能他没有设置成 public~，我们从来没有，也永远不会对新来的的朋友发出 “谁提的谁写” 这种傻逼的要求

#1366

我是大概半个月注意到这个项目的，这是我参与回复的第一个 issue。
当时也没想过 contribute，因为我上面反复强调了，C++ 不是我擅长的领域。
后来看了一下代码，有些东西.. .hmm，以我的水平好像也能改，所以就提了个 PR。
可能第一印象真的比较深刻，我也不是想对线，只是想说 “谁提的谁写” 至少在我这是印象深刻。

> 虽然说这话有点昧良心：我觉得我们严格审核并说清楚要如何修改已经非常不错了，不知道你有没有给其他 repo 提 pr 的经历，辛辛苦苦写了很久的提交，被束之高阁，几个月没人理，然后来一句 outdated 直接 close 掉，这种太常见了。

虽然不是什么大项目，我还真提过。
不接受以后就不提了呗，又不是像 linux core 那样的项目，挂个 contributor 是有多荣耀似的。
我上面也说了，那我可以只提 issue 不提 pr 当伸手党啊。我自己想实现什么功能，在自己 fork 的 repo 里自嗨就行了。

**Comment by horror-proton** [comment]
> 

Organization visibility 是可以设成 private 的, 你看到标签是 Contributor 的不一定就不是 Member

**Comment by MistEO** [comment]
> 再回过头去看你们 member 的提交质量，就会让人莫名的火大。
> member 提交写成那个鬼样子，对 contributor 审查倒是挺严格，我们提出想法，你们又不参与，合着我们在这自嗨。

- 你们提出想法，我们就要参与？我们得到什么好处了吗，说白了 maa 这个项目让我们获得什么好处了？
- 那以后 pr 不满意我们直接不理好了，毕竟绝大部分大型开源项目都是这么个状态

另外你觉得不满意大可以自己写。无论是 fork maa 去魔改成你想要的样子，还是开始一个全新的项目，当然你也可以参考 maa 的代码，记得别忘了 AGPLv3 开源协议哦~

**Comment by ChingCdesu** [comment]
> > 我们没要求过 commit 数量，经常有 pr 不也是一堆乱糟糟的 fix 就直接合了吗。这个有分过是不是 member？
> > 严格的审核审的是代码内容，不是 commit 内容和数量。git 只是为代码服务的工具而已，想让它变好是好的，但没法要求所有人。
> 
> “没法要求所有人” 的意思是不是：你没法要求 member 遵守提交规范（因为他们 push 不需要经过审查）。 换个角度说，member 是不是某种敲门砖，只要成为 member，就能豁免某些东西？ 我想说的是 member 的提交质量不够高，有改进的空间。
> 
> 代码内容方面我没法说什么，毕竟 C++ 不是我擅长的领域。不过我有点不满的是：
> 
> * 我提出改进想法 => 谁提的谁写
> * 我写了，再提个 issue 收集意见 => 没人反馈
> * 我准备换一种改进思路 => 不好。既然你有想法，那为什么不说、或者自己写？
> 
> 关于肉鸽改进的想法，我长篇大论的发了好几个评论了，你们有回过一个字吗？ 既然你们 MAA Team 有一套标准，那是不是应该让 Contributor 知道这套标准是什么，应该怎么配合你们。 而不是我们提出什么，你们都说 “谁提的谁写”，写完了又说不好。那你们自己写就好了啊。
> 
> 再说得明确一点： 肉鸽某些功能本身就是一坨x，你自己也说了准备推翻屎山（虽然不完全是指肉鸽）。 我之前也说过了，我希望至少先把 59 分不及格的功能，改进到 “可以用” 的程度。 至于这个 “可以用” 是什么程度，要达到什么标准？没人知道，因为你只知道什么不行，但从来不说应该怎么做。 再回过头去看你们 member 的提交质量，就会让人莫名的火大。 member 提交写成那个鬼样子，对 contributor 审查倒是挺严格，我们提出想法，你们又不参与，合着我们在这自嗨。

* 活跃的成员基本上每天都在保持联系，相互交流意见，以最少2000字每天来计算，而且这种交流是双向的，实时的。GitHub的issue中的交流无法做到这两点，而且issue的篇幅不太可能很长，因为长了反而没人看，所以提issue也是一门学问。
* member之所以会直接提交到master的原因主要有以下几种可能：
  * 由于拼写错误/误触等造成的错误
  * 调试ci
  * doc，i18n之类的提交
  * 最近其他member不会动的文件，并且与他们确认过
  所以类似于大的feature，breaking change等这些是不可能直接提交到master的，而且就算所有人都切换到dev开发，那和所有人都在master开发有什么区别呢。
* 对Contributor的代码review之所以严格是因为我们得确保他们提交的代码不会影响到正常功能，以及他们在一定程度上决定了未来的一些开发思路，所以我们需要时间和精力去努力理解你们的想法（如果你给每行代码都写上注释我想review确实花不了多少时间，但对 contributor 来说太不划算了），如果这个时候正好赶上方舟出活动等，我们肯定会暂时搁置大多数的issue，把时间给到对新关卡的适配上
* 我们并不是全职开发Maa，它只是我们生活的一部分，我们只能尽可能多的分时间来开发和维护它。member中大多数人是打工人和学生，有自己的主要目标，但是我们觉得开发和维护MAA是我们的责任，希望你能考虑到这一点。

> 我是大概半个月注意到这个项目的，这是我参与回复的第一个 issue。 当时也没想过 contribute，因为我上面反复强调了，C++ 不是我擅长的领域。 后来看了一下代码，有些东西.. .hmm，以我的水平好像也能改，所以就提了个 PR。 可能第一印象真的比较深刻，我也不是想对线，只是想说 “谁提的谁写” 至少在我这是印象深刻，可能确实误解比较深。

如果你觉得半个月的pr没人理就觉得不公平了，那你看看我这个https://github.com/amiremohamadi/DuckX/pull/72。我的处理方式是fork一个然后自己用，确实也解决了我的需求。

MAA Team并不大，以及team里的都不是圣人。

**Comment by et2012** [comment]
> 如果你觉得半个月的pr没人理就觉得不公平了

我不是指这个。我的意思是，我半个月前才注意到这个项目。
我也没有未处理的 PR，而是觉得社区不活跃，成员的提交质量有待提高。
但这和是否全职开发没什么关系，为爱发电也不能太随意。
既然 issue 已经关了，那我已经知道你们的态度了，不再回了。

**Comment by ChingCdesu** [comment]
> 我不是指这个。我的意思是，我半个月前才注意到这个项目。 我也没有未处理的 PR，而是觉得社区不活跃，成员的提交质量有待提高。 但这和是否全职开发没什么关系，为爱发电也不能太随意。 既然 issue 已经关了，那我已经知道你们的态度了，不再回了。

reply: 
> MAA Team并不大，以及team里的都不是圣人。

请问您加群了吗？您经过充分调研了吗？您知道README中写了**群已满**吗？您有认真看过README吗？

我真的不想把火药味搞得那么重，发言请多多包涵🙂。

**Comment by et2012** [comment]
> > 我不是指这个。我的意思是，我半个月前才注意到这个项目。 我也没有未处理的 PR，而是觉得社区不活跃，成员的提交质量有待提高。 但这和是否全职开发没什么关系，为爱发电也不能太随意。 既然 issue 已经关了，那我已经知道你们的态度了，不再回了。
> 
> reply:
> 
> > MAA Team并不大，以及team里的都不是圣人。
> 
> 请问您加群了吗？您经过充分调研了吗？您知道README中写了**群已满**吗？您有认真看过README吗？
> 
> 我真的不想把火药味搞得那么重，发言请多多包涵🙂。

again. 我真的不是来对线的。
README 我有看，QQ一群的状态修改都已经来回 push 了好几个 commit 了。
你想说的是你们的交流主要在 QQ 群，所以你们的社区是很活跃的，我理解了。
而我说的社区不活跃，主要是指 github 这边，和 contributor 的交流。

既然挂着 contributor 也不一定不是 member，那纯粹的 contributor 除了我之外好像没几个了 (少我一个不少)。
至于我为什么不加用户群 / 开发者群 / 不尝试加入 member：
一是自我要求，我在C++方面的能力和自我定位，现阶段做 contributor 更合适，member 对我来说意味着某些责任和义务；
二是觉得既然在 github 开源了，以我接触的开源项目大多是以 github community / discord 为主的，我 “以为” issue 和 discussion 也会被重视，但和我想的似乎有点偏差。

火药味什么的，从关闭这个 issue 开始是稍微有点了，不过我已经 get 到你们的想法了。
所以也请多多包涵吧，现在也只能说 “maa是一款我的问题”。
既然已经关了，反正别人也看不到，应该不会再有什么负面影响了。

**Comment by horror-proton** [comment]
对作为开源项目 QQ 群确实过于封闭了不算什么正式的交流场所, 不过有一个肯定比单纯使用 GitHub 和邮件来得方便, 再加上贡献者主要来自中国大陆, 所以不少交流主要还是在 QQ 群里

**Comment by zzyyyl** [comment]
> 你想说的是你们的交流主要在 QQ 群，所以你们的社区是很活跃的，我理解了。
> 而我说的社区不活跃，主要是指 github 这边，和 contributor 的交流。

tg 群 / QQ 群都欢迎加入。GitHub 确实不是 MAA 主要交流的地方。

> “加入我们一起建设 MAA” 已经被划掉了

这大概只是 @MistEO 的习惯罢了（这条在被写进 README 的时候就是划掉的状态
MAA 还是欢迎大家一起建设的。

> Contributor 想 PR 一点东西，MAA Team 会全方位的检查；但 MAA Team 自己写的代码，就随便怎么来是吗？

新的 PR 下面 comment 很多，是因为 MAA Team 没有其他联系 Contributor 的方式。
MAA Team 自己写的代码，大部分在群里已经经过了大家讨论了。（谁写的代码会没有 bug 呢？应该不多吧）

> 我 “以为” issue 和 discussion 也会被重视，但和我想的似乎有点偏差。

我觉得吧，MAA 已经比较重视 issue 了，大家也不是全职写 MAA 的，回复和思考总需要一些时间，尤其是比较大的改动。

#### 另外说几句
MAA 目前并不是只有 cpp 的项目，还有 [MeoAsstGui](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/master/src/MeoAsstGui)，[MaaAsstElectronUI](https://github.com/MaaAssistantArknights/MaaAsstElectronUI)，[MaaCopilotDesigner](https://github.com/MaaAssistantArknights/MaaCopilotDesigner) 等等项目正在开发。
MAA 有很多小白 Contributor，因此 MAA 甚至有 [Github Pull Request 流程简述](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/PR%E6%B5%81%E7%A8%8B%E7%AE%80%E8%BF%B0.md)，所以 MAA 对新 PR 的审查会相对严格。

关于 master 的问题，由于近期 master 上的提交基本都是我的，我暂且解释一下。现在通常意义上的 master 其实是 `stable` 分支，master 上会有各种 docs/ci 的修改。master 往 dev 合并，是因为 dev 需要 bot 的功能。
以及现在 master 是不能直接往上推的，你看到应该都是 PR rebase 的结果。

还有，开发大的功能/大的修改前尽量与 MAA Team 联系一下，因为有可能会与 MAA 的更新计划有冲突，到时候就是各种要求修改，显得 MAA Team 对 Contributor 要求很高。
