### ISSUE TITLE
可不可以考虑加个屏幕常亮？

### ISSUE THREAD

**Issue by noahyung** [MaaAssistantArknights/MaaAssistantArknights#1550]
### 说说你遇到的问题？

屏幕会自动熄屏，似乎会导致动作中断。

### 有什么好的想法？

希望添加一个屏幕常亮的功能。

**Comment by zzyyyl** [comment]
Add GUI

**Comment by ABA2396** [comment]
息屏没关系，睡眠和休眠才会

**Comment by horror-proton** [comment]
指的是电脑屏幕还是手机屏幕, 如果是电脑屏幕, 可以去 Windows 的电源和睡眠设置中修改熄屏和睡眠时间

**Comment by ntgmc** [comment]
感谢反馈。
Thank you for your feedback.
