### ISSUE TITLE
完成后关机bug

### ISSUE THREAD

**Issue by Jacky0910** [MaaAssistantArknights/MaaAssistantArknights#1551]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在使用“完成后关机”功能时，可以正常实现完成任务后关机需求，但在电脑重启后磁盘占用率非常高，达到100%，其中进程占用高的进程为wsappx和system。若自己手动进行关机则不会出现该情况，进行了几次对比验证应该是“完成后关机”功能导致的。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9331536/asst.log)

### 还有别的吗？

使用mumu模拟器

**Comment by zzyyyl** [comment]
Add GUI

**Comment by MistEO** [comment]
挺奇怪的，你试试手动在 `运行` 里输 `shutdown -s -t 60` 关机，看会有这种问题么？

**Comment by Jacky0910** [comment]
> 挺奇怪的，你试试手动在 `运行` 里输 `shutdown -s -t 60` 关机，看会有这种问题么？

刚刚试了一下好像用了这条关机也会，所以大概是我的问题而不是程序的bug？

**Comment by MistEO** [comment]
是的，程序就是直接执行的这条命令，你可能得看看为啥你的电脑用 shutdown 命令会有这种问题

**Comment by Jacky0910** [comment]
> 是的，程序就是直接执行的这条命令，你可能得看看为啥你的电脑用 shutdown 命令会有这种问题

好的谢谢哦
