### ISSUE TITLE
肉鸽干员招募界面不能使用 SwipeToTheLeft

### ISSUE THREAD

**Issue by et2012** [MaaAssistantArknights/MaaAssistantArknights#1552]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽招募界面左侧 353 x 720 的干员信息面板不能作为滑动起点，类似基建选择干员界面。

SwipeToTheLeft 左侧起点是 width * 0.1, height * 0.4 即 (128, 288) 附近，会点进干员信息区域。

目前没有不良影响，只会导致无干员可招募时，不会划回左边，实际上好像也不需要划回左边。

如果后续需要用基建类似算法（把全部干员划一遍计算优先级，再划回左边做选择）时，可以新增一个类似 InfrastAbstractTask::swipe_to_the_left_of_operlist 的方法和相关 task。

### 日志文件
```
void asst::ProcessTask::exec_swipe_task(ProcessTaskAction action)
{
    const auto&& [width, height] = m_ctrler->get_scale_size();

    const static Rect right_rect(
        static_cast<int>(width * 0.8),
        static_cast<int>(height * 0.4),
        static_cast<int>(width * 0.1),
        static_cast<int>(height * 0.2));

    const static Rect left_rect(
        static_cast<int>(width * 0.1),
        static_cast<int>(height * 0.4),
        static_cast<int>(width * 0.1),
        static_cast<int>(height * 0.2));

    switch (action) {
    case asst::ProcessTaskAction::SwipeToTheLeft:
        Log.trace("[Squad] SwipeToTheLeft");
        m_ctrler->swipe(left_rect, right_rect);
        break;
    case asst::ProcessTaskAction::SwipeToTheRight:
        m_ctrler->swipe(right_rect, left_rect);
        break;
    default: // 走不到这里，TODO 报个错
        break;
    }
}
```

### 截图

![image](https://user-images.githubusercontent.com/1037590/184497900-5b81381f-b5b1-4852-b311-9054a7476031.png)

**Comment by ABA2396** [comment]
Remove infrast

**Comment by horror-proton** [comment]
也许应该加一个可选的 `Rect` 参数用来提示需要滑动的窗口的位置? 🤔

**Comment by et2012** [comment]
> 也许应该加一个可选的 `Rect` 参数用来提示需要滑动的窗口的位置? 🤔

这个界面只在 RoguelikeRecruitTaskPlugin 中使用，加一个 task 也可以。
虽然现在还用不上，不过后续可以支持复杂一点的算法（类似基建自动选最佳人选）。
基建也有几个界面（中枢、情报、制造站）的自定义划动是通过添加 task 来实现的。
