### ISSUE TITLE
公招词条选择错误？

### ISSUE THREAD

**Issue by SHIKI015M** [MaaAssistantArknights/MaaAssistantArknights#1554]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

两个爆发，一个正常选择，一个点了快活。 有4不选5吗这个。

### 日志文件

确实出了点问题，我们无法处理该文件。 

### 截图

![AT2OTZEFRA{Q`RMSICHL}OW](https://user-images.githubusercontent.com/76200575/184499601-b40c9568-5297-46a6-a6fc-1fb0a337f20f.png)
![XYRZT8@S~5S @FTTXB~R%2M](https://user-images.githubusercontent.com/76200575/184499602-a7333cc9-ed84-47ed-8048-b8c991e8d2eb.png)

**Comment by MistEO** [comment]
`刻刀` 加入公招，`爆发` 现在是 4 星 tag 了

**Comment by SHIKI015M** [comment]
> `刻刀`加入招公，`爆发`现在是4星标签了

OMG，完全没有注意到这个，还以为爆发是5呢。
