### ISSUE TITLE
在文字识别匹配时，去除所有空白符（以及一些特殊字符？）

### ISSUE THREAD

**Issue by lhhxxxxx** [MaaAssistantArknights/MaaAssistantArknights#1556]
现在core的文字识别匹配在遇到空白符时会匹配失败，在一些非用户输入的场合问题可能不明显，但在如黑名单等用户输入的环节，多余的空格会导致无法成功匹配。
虽然在 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/6443e54ee74e9f33510f0c7b404137ef8f09dfbd 中在GUI端修复了首尾空白符的问题，但这个问题仍需要尽量在core中解决，因为可能会有英文的文本中间空格，识别产生的特殊字符等意外情况。

**Comment by lhhxxxxx** [comment]
@zzyyyl issue checker似乎识别不了core

**Comment by lhhxxxxx** [comment]
包括肉鸽藏品的`“”`双引号也可以去掉

**Comment by zzyyyl** [comment]
> @zzyyyl issue checker似乎识别不了core

没做 core，因为 core 不好加关键词（

**Comment by MistEO** [comment]
如果是识别结果有空格可以去一下，但输入参数就是得完全正确啊，我觉得没啥问题（

**Comment by lhhxxxxx** [comment]
> 如果是识别结果有空格可以去一下，但输入参数就是得完全正确啊，我觉得没啥问题（
> 
> ---
> 
> 一个函数参数输入错误你还指望他能正常工作吗，预期结果就应该是遵照错误的参数执行

考虑英文的情况，如果要去掉识别结果的空格，那输入的空格显然也要去掉

**Comment by MistEO** [comment]
等等，到底是识别结果，还是输入参数。怎么感觉在跨服交流

**Comment by MistEO** [comment]
我说的去掉识别空格指的是 trim

**Comment by MistEO** [comment]
英文识别结果感觉不能去掉中间的空格，一串字母连在一起可能拆出来好几个意思，万一有俩物品字母一样咋整

**Comment by lhhxxxxx** [comment]
> 我说的去掉识别空格指的是 trim

我的意思是去掉输入参数与识别结果中所有空白符以及特殊字符

考虑#1282这样的问题

至于英文我似乎没想到连起来会歧义的例子，反而是识别过程中中间空格不对的情况概率更大

**Comment by MistEO** [comment]
英文识别也没有中间空格错误的例子。。飞桨这点还是能保证的

**Comment by zzyyyl** [comment]
输入参数 和 识别结果 都 trim 一遍基本就没问题了（现在就是这样了吧）
#1282 我觉得大概不是特殊字符的原因（

**Comment by lhhxxxxx** [comment]
> 输入参数 和 识别结果 都 trim 一遍基本就没问题了（现在就是这样了吧）
> #1282 我觉得大概不是特殊字符的原因（

也行吧，但目前trim是在gui做的，我觉得是不是应该改到core里

（怪，手机github又点到编辑了）

**Comment by MistEO** [comment]
另外群里大佬们说可以写的更简洁一点，你挑一个，这几种都行，别跑 for 循环了（

![image](https://user-images.githubusercontent.com/18511905/184646196-fe379d6b-4922-4f7b-9b9a-cd3bf60593a5.png)

![image](https://user-images.githubusercontent.com/18511905/184646215-10adffd5-d374-4378-8325-ade19c90e538.png)

**Comment by lhhxxxxx** [comment]
> 另外群里大佬们说可以写的更简洁一点，你挑一个，这几种都行，别跑 for 循环了（
> 
> ![image](https://user-images.githubusercontent.com/18511905/184646196-fe379d6b-4922-4f7b-9b9a-cd3bf60593a5.png)
> 
> ![image](https://user-images.githubusercontent.com/18511905/184646215-10adffd5-d374-4378-8325-ade19c90e538.png)
> 

不太会c#，之前试了下foreach不能修改循环变量就放弃了（）
