### ISSUE TITLE
完成后的一些问题

### ISSUE THREAD

**Issue by miku1958** [MaaAssistantArknights/MaaAssistantArknights#1557]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

- 退出并关闭模拟器不会关闭MuMu模拟器，模拟器设置是这样的
参数是MAA自己生成的
![image](https://user-images.githubusercontent.com/24806909/184517908-f8b7d507-cd37-4b26-85b8-1a7fd8d7d283.png)

- 自动关机选项不会被保存
我的使用场景是，出门前开一下电脑让它自动跑完关机，但是下次启动我还是需要手动改一下
然后我才发现休眠和关机是带星号是意味着不会被保存，可否给个选项能自动记住自动关机呢
![image](https://user-images.githubusercontent.com/24806909/184517815-5f163ae6-fc58-4b6f-8be5-d846833e806f.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9332474/asst.log)

**Comment by cglcv** [comment]
呃……模拟器窗口名称是什么？
模拟器启动的时候要管理员权限了吗

**Comment by miku1958** [comment]
![image](https://user-images.githubusercontent.com/24806909/184518468-e65756e4-ea08-4bae-b8a4-21f4767d8eaa.png)

模拟器没有要权限，我试过开管理员权限的话MAA打不开模拟器，所以我没开

**Comment by cglcv** [comment]
测了一下，我这边MuMu要了管理员权限，maa在试图关闭时直接报异常退了，要管理员权限的无解，你可能没开uac所以没提示
至于打不开的问题，你检查一下maa填的启动路径是否正确，可以尝试把MuMu快捷方式里面的路径(引号内部分)和附加命令复制进maa看看行不行，再不行可能就是MuMu的锅了
add gui

**Comment by miku1958** [comment]
我有开UAC，MuMu只要开启了服务就不需要权限，我都可以直接taskkill结束它
![image](https://user-images.githubusercontent.com/24806909/184519516-73f31e0f-c022-47a2-bbbc-d4b13c4ee6a3.png)

**Comment by cglcv** [comment]
> 我有开UAC，MuMu只要开启了服务就不需要权限，我都可以直接taskkill结束它 ![image](https://user-images.githubusercontent.com/24806909/184519516-73f31e0f-c022-47a2-bbbc-d4b13c4ee6a3.png)

给个教程？
我这边把管理员权限去了它根本无法启动

**Comment by miku1958** [comment]
我也不清楚怎么回事, 开机的时候那个Service就会启动, 之后就不需要管理员打开Player了

你试试在Player.exe的属性里看看能不能直接把以管理员权限关了?

**Comment by cglcv** [comment]
> 我也不清楚怎么回事, 开机的时候那个Service就会启动, 之后就不需要管理员打开Player了
> 
> 你试试在Player.exe的属性里看看能不能直接把以管理员权限关了?

试了，寄了

**Comment by miku1958** [comment]
那应该就是Service的问题了

**Comment by cglcv** [comment]
我试着在管理员权限下启动和关闭mumu都没有问题，是不是你启动链接多加了引号什么的？

**Comment by cglcv** [comment]
这应该就是管理员权限的问题，那无解

**Comment by miku1958** [comment]
自动生成的adb路径长这样
C:\Users\vv195\Application\MuMu\emulator\nemu\EmulatorShell\..\vmonitor\bin\adb_server.exe
文件夹路径是这样
C:\Users\vv195\Application\MuMu\emulator\nemu\vmonitor\bin

模拟器填的是（没带引号）
C:\Users\vv195\Application\MuMu\emulator\nemu\EmulatorShell\NemuPlayer.exe

**Comment by miku1958** [comment]
> 这应该就是管理员权限的问题，那无解

问题是我开MuMu不需要管理员权限

**Comment by miku1958** [comment]
加引号会报错
"C:\Users\vv195\Application\MuMu\emulator\nemu\EmulatorShell\NemuPlayer.exe"
![image](https://user-images.githubusercontent.com/24806909/184521931-29c24509-53c4-4c40-99fc-3160a85b4697.png)

**Comment by miku1958** [comment]
哦我懂了，只要MuMu不是最前面的窗口，被MAA关闭就会失败，看起来应该是被Service重启了

**Comment by cglcv** [comment]
> 哦我懂了，只要MuMu不是最前面的窗口，被MAA关闭就会失败，看起来应该是被Service重启了

好怪

你填的内容没问题，加引号会报错的
以及如果MuMu没运行明日方舟的话应该关不了
它现在靠识别窗口名称找模拟器，MuMu的窗口名称随着运行程序的不同会变

**Comment by miku1958** [comment]
我的意思是，如果这个MuMu不是当前激活的窗口，被MAA关闭后它会被Service重启，然后有概率直接卡死了，如果不能直接把Player干掉，能不能先激活一下窗口把它bring到最前面？
