### ISSUE TITLE
还是识别问题

### ISSUE THREAD

**Issue by IranksAdral** [MaaAssistantArknights/MaaAssistantArknights#1558]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

看来是在我羊皮和家具同时掉落的时候会出现识别错误

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9332640/asst.log)

### 截图

![2022-08-12_14-45-26 118_raw](https://user-images.githubusercontent.com/87361258/184520897-026b585f-02a6-493c-99cc-d943493bcc74.png)
![2022-08-14_11-10-16 045_raw](https://user-images.githubusercontent.com/87361258/184520899-e4614414-62ca-4670-9dfa-cbdd6bcc35dd.png)

**Comment by horror-proton** [comment]
材料底下的线居然还有白色的

**Comment by MistEO** [comment]
顺手整理了一下测试集，以后再改好验点 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/a53673e2c02549f4296721354b09406d8f0cca20
