### ISSUE TITLE
艾丽妮专精技能时心情低于阈值被maa换下

### ISSUE THREAD

**Issue by SlientGriever** [MaaAssistantArknights/MaaAssistantArknights#1559]
### 说说你遇到的问题？

昨晚在用艾丽妮给百炼嘉维尔专精，今早上直接开了maa，艾丽妮心情低于阈值直接被换下去了，血亏一半训练时间

### 有什么好的想法？

可以加一个训练室不换下干员的选项

**Comment by ABA2396** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/763
