### ISSUE TITLE
肉鸽通关后无法继续

### ISSUE THREAD

**Issue by et2012** [MaaAssistantArknights/MaaAssistantArknights#1561]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

点到炒饭了，用近锋队+优化阵容自动通关了。
通关只是谢幕前面多了一段结局剧情，应该只需要加一个 SKIP 识别。

题外话：虽然不能保证每次都通关，但至少证明招募阵容优选是有效果的。
再优化一下战斗逻辑，自动通关（至少普通难度）是有可能的。

### 日志文件

无

### 截图

![image](https://user-images.githubusercontent.com/1037590/184532208-6a591f94-053c-4fb6-b93c-0f852c6de5a8.png)

**Comment by MistEO** [comment]
我太菜了，自己打半天都通不了关，所以现在没图可以截（

应该是改下 tasks.json 就好了
