### ISSUE TITLE
刷理智功能无法选择特别开放关卡

### ISSUE THREAD

**Issue by devwian** [MaaAssistantArknights/MaaAssistantArknights#1566]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

玩家回归资源收集关卡会特别开放，刷理智功能将卡在选择关卡处

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9334657/asst.log)

08-15 10:10:47执行任务

### 截图

![image](https://user-images.githubusercontent.com/24718632/184566325-808bc287-9ed2-4f88-bbf5-c43a5937907d.png)

**Comment by MistEO** [comment]
设置 - 界面设置 里有

**Comment by MistEO** [comment]
理解错了，可能要把模板图片裁一半掉 @ABA2396

**Comment by zzyyyl** [comment]
> 理解错了，可能要把模板图片裁一半掉 @ABA2396

用 mask 吧（

**Comment by zzyyyl** [comment]
Add fight

**Comment by MistEO** [comment]
这哪个服啊，我想测试一下才发现国服咋没特别开放 orz

**Comment by MistEO** [comment]
帮忙把这个界面左右滑动各截几张图吧，因为现在没法测试，只能凭感觉修一下（需要用模拟器自带的截图工具截的原图）

**Comment by devwian** [comment]
> 帮忙把这个界面左右滑动各截几张图吧，因为现在没法测试，只能凭感觉修一下（需要用模拟器自带的截图工具截的原图）
![Screenshot_2022 08 15_22 27 16 710](https://user-images.githubusercontent.com/24718632/184654403-aa081fc3-f472-423a-8bf0-58371889cf55.png)
![Screenshot_2022 08 15_22 27 24 210](https://user-images.githubusercontent.com/24718632/184654415-bfa312e8-464f-4109-a9f0-a8718e24c581.png)

底下的七个点会随着时效变化，我就剩4天了，所以还有四个黄点
