### ISSUE TITLE
新公招更新需要

### ISSUE THREAD

**Issue by 446276170** [MaaAssistantArknights/MaaAssistantArknights#1567]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

2022年8月15日10:24:50
公招更新后，爆发tag加入了刻刀，单点爆发不再是必出守林人 
即爆发狙击双tag为5星守林人
单爆发tag为守林人和刻刀的公招问题处理
{"details":{"result":[{"tags":["爆发"],"opers":[{"name":"守林人","level":5},{"name":"THRM-EX","level":1}],"level":5},

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9335031/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/26543213/184574467-bcbabd3d-789f-4d47-838d-1e6e294263e6.png)

**Comment by horror-proton** [comment]
根据日志, 你用的还是 `v4.2.3` 版本, [`v4.2.4`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.2.4) 已经更新了公开招募的配置
