### ISSUE TITLE
办公室不上班

### ISSUE THREAD

**Issue by akra3523** [MaaAssistantArknights/MaaAssistantArknights#1573]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建收菜时办公室没有调班，该问题在艾雅法拉理智涣散时生效，有一次在点开调班操作时发现直接跳过办公室并未点进去选择干员

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9347386/asst.log)

最新一次操作点是08-16 09:41:50

### 截图

<img width="674" alt="image" src="https://user-images.githubusercontent.com/74871358/184781404-b0a05dc7-0763-496f-9e8b-f419912a0a79.png">

### 还有别的吗？

模拟器：夜神模拟器 7.0.3.1
操作系统：Windows 10 21H2 19044

**Comment by seuqo** [comment]
我遇到同样问题，完成任务后发现办公室空了，没放人。日志从 [2022-08-26 10:59:18.389] 开始
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9429575/asst.log)

**Comment by akra3523** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9474266/asst.log)
该问题能成功复现多次，最新一次操作时间点是09-02 09:28:36

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。

Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
