### ISSUE TITLE
v4.3.0-beta.1 版本无法正确使用加急招募

### ISSUE THREAD

**Issue by Mark9804** [MaaAssistantArknights/MaaAssistantArknights#1574]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启用设置中的“自动加急”之后，若当前公招槽位中没有可以加急的进行中招募则会报错
![image](https://user-images.githubusercontent.com/9006264/184802009-dda25b4b-af81-4bab-91ad-8a2c1578534c.png)

### 日志文件

08-16 13:19:58

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9347986/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/9006264/184802200-3d992746-c663-4086-af74-ce47ba6e3b22.png)

**Comment by horror-proton** [comment]
这个问题应该会在刚进入招募就导致失败, 而不是招募了一半出现. 看了下你的日志, 感觉还存在别的问题.
一开始在 *是否消耗加急许可* 的确认界面, 按下一次确认按钮后可能因为某种原因 (比如网络卡顿) 确认界面没有马上关闭, 导致识别到后又点了一次确认按钮的位置, 结果点进了第四个公招槽位 (ref: #1491), MAA 正确处理了这种情况并关闭了这个槽位. 
然后发现没有招募完成的 *聘用候选人* 按钮, 甚至没有正在倒计时的招募, 这是怎么回事 🤔

**Comment by Mark9804** [comment]
> 这个问题应该会在刚进入招募就导致失败

当所有公招栏都是空栏的时候，会 100% 触发这个 bug

> 而不是招募了一半出现

刚刚重新尝试了一遍边界情况，重新触发了招募一半出现的情景，但是我 windows 单纯就是个游戏机，没装录屏软件，我口头描述一下

情景设置：手动点击第一个槽位，选择7:40，确定，启动 MAA 
观察到的情况：
1. 正确点击并完成了第一次加急招募
2. 正确点击了第 n 个槽位（看不出是哪个）并出现了选择 tag 的界面
3. 卡在选择 tag 界面大约 3-5 秒钟
4. 回退到主界面
5. 重新进入到公招界面
6. 所有公招栏都是空栏，触发该 bug

**Comment by Mark9804** [comment]
稍后我清一下已有日志上传一个干净的复现日志

**Comment by horror-proton** [comment]
> 稍后我清一下已有日志上传一个干净的复现日志

不用了, 这个问题已经进行了简单的修复, 应该不管刚进入招募还是误触第四个公招槽位都不会出现这种情况了, 可以等待之后的版本, 感谢提供信息
