### ISSUE TITLE
基建换班的时候掉线，但是maa并没有识别而是继续任务

### ISSUE THREAD

**Issue by koujinn** [MaaAssistantArknights/MaaAssistantArknights#1576]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

你好。
在基建进行换班的时候，游戏掉线，错误代码是400。
但是maa没有识别出来而是继续任务，直到最后显示完成任务，都没有识别出掉线。
第一张截图是错误代码的截图，第二张截图是游戏自动弹回登录界面，以及maa没有登录而是一直进行任务直到结束的截图。
这个问题之前我也出现了好几次，但是看issue和常见问题也没有什么提及的。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9348043/asst.log)

### 截图

![MuMu20220816140622](https://user-images.githubusercontent.com/103643351/184803639-144b7172-6262-42d7-a73a-65c9e7a8f023.png)
![1](https://user-images.githubusercontent.com/103643351/184803990-578ff557-8196-477d-ab7b-41e5f9e344aa.png)

### 还有别的吗？

使用的模拟器是mumu。
明日方舟是国服。

**Comment by MistEO** [comment]
确实，现在只有刷理智和肉鸽做了掉线重连_(:з」∠)_

等有空再弄吧

**Comment by Tastror** [comment]
Fight 的初始阶段也有这种情况
@MistEO @zzyyyl 

这里一直卡了几个小时（）

<a href="https://paste.ubuntu.com/p/xtB5RpBbcY/" target="_blank">asst.log</a>

![](https://s2.loli.net/2022/08/29/god4P1hzWMO2iqy.png)
![](https://s2.loli.net/2022/08/29/M6PsYRhovtc9uOf.jpg)

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
