### ISSUE TITLE
在新环境下肉鸽未选择难度就卡着无法开始

### ISSUE THREAD

**Issue by wzx1205** [MaaAssistantArknights/MaaAssistantArknights#1581]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

点开始就提示为选择难度 然后就识别失败一遍又一遍

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9355366/asst.zip)

### 还有别的吗？

MAA 版本：v4.3.0-beta.1

**Comment by zzyyyl** [comment]
by design

**Comment by zzyyyl** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/7fe8e5a49c8942b5f305dc3ae4c604b621be9363

@MistEO

**Comment by MistEO** [comment]
来张图看看（

**Comment by MistEO** [comment]
我感觉可以关了，反正马上开水月了（
