### ISSUE TITLE
从当前/上次关卡开始程序有概率不认当前页面

### ISSUE THREAD

**Issue by IranksAdral** [MaaAssistantArknights/MaaAssistantArknights#1582]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

碎石后有概率不直接进本而是退出到主界面再一层一层进本

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9359167/asst.zip)

**Comment by MistEO** [comment]
似乎和手动碎石有关，现在既然已经加了 “博朗台碎石” 功能了，那我就先关了（
