### ISSUE TITLE
beta版新功能宿舍填充干员的问题

### ISSUE THREAD

**Issue by Private233** [MaaAssistantArknights/MaaAssistantArknights#1584]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

这也算比较巧的一件事吧（
前面异格炎熔进发电站工作之后，填宿舍的时候恰好选到了三星炎熔，异格炎熔就强制下班了

### 日志文件

之前文件改崩了，重新下了一次，日志文件就无了，不过应该不重要吧）

### 还有别的吗？

maa 4.3.0 beta-1

**Comment by MistEO** [comment]
那这个问题头疼了 orz, 想要解决的话必须得想办法识别异格了

cc @Hydrogina

**Comment by Hydrogina** [comment]
![BS_PIC_2022-08-17-22-28-56](https://user-images.githubusercontent.com/46482682/185160676-933c20c8-81e5-4ecc-a935-0d5d5d957c1b.png)
识别干员左上角的那个“格雷伊 B303”可以吗

**Comment by et2012** [comment]
图标还不太一样，是根据本体进驻的设施来显示的。
格雷伊那个图标是本体/异格在发电站。

![image](https://user-images.githubusercontent.com/1037590/185209095-28944b1f-822c-43fd-a594-39a5b489a982.png)
中枢

![image](https://user-images.githubusercontent.com/1037590/185208305-000c8845-1f49-4df1-a8ec-346c8cd7cafe.png)
会客室

![image](https://user-images.githubusercontent.com/1037590/185208658-dd67614f-9281-4615-aa5a-c34465c75fb0.png)
制造站

![image](https://user-images.githubusercontent.com/1037590/185209386-fea50a69-9932-4c91-b552-7dda5d1cc59d.png)
贸易站

![image](https://user-images.githubusercontent.com/1037590/185209647-0a5e747a-8128-4e40-8efb-13fd63d22b75.png)
办公室

![image](https://user-images.githubusercontent.com/1037590/185209855-2bfd2e3d-7624-45c1-b0f3-cf0c99fd642f.png)
训练室

![image](https://user-images.githubusercontent.com/1037590/185208218-e1552110-0756-40d4-8903-7aa3ef5e1be4.png)
宿舍

加工站就不管了，撤了就撤了。

**Comment by MistEO** [comment]
fixed
