### ISSUE TITLE
Bluestack Hyper-V 版无法自动调整端口号

### ISSUE THREAD

**Issue by Zhang-RQ** [MaaAssistantArknights/MaaAssistantArknights#1587]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在按照 [文档](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.md) 的方法修改gui.json后仍然无法正常自动修改端口号，会保持默认的5000。在手动修改端口号后可以正常运行。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9363483/asst.log)

**Comment by MistEO** [comment]
请确认你的 json 修改的是对的

**Comment by Zhang-RQ** [comment]
在重新安装MAA后问题解决。

**Comment by roo12589** [comment]
感谢 配置了路径并 更新了最新版助手 解决问题了
