### ISSUE TITLE
MAA已停止工作

### ISSUE THREAD

**Issue by 446276170** [MaaAssistantArknights/MaaAssistantArknights#1588]
### 说说你遇到的问题？

新下载的压缩包，win7系统，i5，4g内存 
运行库VC++2015-2022  .net 4.0
电脑中有一个新解压的4.24版本和老版本4.00（另一个电脑上能正常用的）在此电脑都打不开
管理员运行也是提示已停止工作。
![image](https://user-images.githubusercontent.com/26543213/185161004-2703e064-8a0d-4071-96bb-ac939b4b3216.png)
请问是什么原因造成的

**Comment by 446276170** [comment]
![image](https://user-images.githubusercontent.com/26543213/185169422-ac15eb07-e07a-4dfd-803d-ebb01a2ac5bb.png)
fushang附上问题设备的图

**Comment by MistEO** [comment]
你按替换 avx 的那个方法试试，目前发现有 avx 但没有 avx2 似乎也不行

**Comment by 446276170** [comment]
好的 十分感谢 回家以后我试一下

**Comment by 446276170** [comment]
这几天比较忙 没有及时回应
仍然是上图的配置
按照常见问题中[NoAvx](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/3rdparty/ppocr_noavx.zip)方法替换了同名文件
1.ppocr.dll
2.paddle_inference.dll
3.openbla.dll文件尝试直接解压和重命名替换opencv_world453.dll文件都没有解决问题
仍然打开MAA提示MAA已停止工作。
请问作者在不更换电脑配置的情况下还有其他解决办法吗。
麻烦。

**Comment by 446276170** [comment]
新下载的压缩包，win7系统，i5，4g内存
运行库VC++2015-2022 .net 4.0
电脑中有一个新解压的4.24版本和老版本4.00（另一个电脑上能正常用的）在此电脑都打不开
管理员运行也是提示已停止工作。
![image](https://user-images.githubusercontent.com/26543213/186433011-64d3ef4c-d9f6-4e52-b3b8-7d4f5cb06760.png)

![image](https://user-images.githubusercontent.com/26543213/186432974-a64eefbf-ae76-4a18-a3eb-333d07a90b2f.png)

这几天比较忙 没有及时回应开发者提供的建议
仍然是上图的配置
按照常见问题中[NoAvx](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/3rdparty/ppocr_noavx.zip)方法替换了同名文件
1.ppocr.dll
2.paddle_inference.dll
3.openbla.dll文件尝试直接解压和重命名替换opencv_world453.dll文件都没有解决问题
仍然打开MAA提示MAA已停止工作。
请问作者在不更换电脑配置的情况下还有其他解决办法吗。
麻烦。
