### ISSUE TITLE
基建干员冲突 一个发电站没上人

### ISSUE THREAD

**Issue by SnailZq** [MaaAssistantArknights/MaaAssistantArknights#1590]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建干员冲突 有一个发电站没有干员

maa版本4.3.0-beta.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9364390/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/59328830/185185856-27993fe8-f467-422b-b605-58bda96df1ea.png)

### 还有别的吗？

蓝叠

**Comment by MistEO** [comment]
长期使用 maa 换班是不会有干员冲突的，这个就是提示你要手动换一下

**Comment by MistEO** [comment]
现在测试版本应该不会把异格干员扔到宿舍了
