### ISSUE TITLE
模拟器卡在启动中99%

### ISSUE THREAD

**Issue by number9029** [MaaAssistantArknights/MaaAssistantArknights#1593]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

模拟器关联Maa后，第一次运行正常。关掉后重新启动模拟器就一直卡在99%。试过蓝叠和夜深，都是同样的情况，卡在99%，重启也没用。卸载模拟器重新安装后，又出现同样情况：第一次正常，关掉后就卡99%

### 日志文件

.....

**Comment by ABA2396** [comment]
那你把MAA删了之后试试呢

**Comment by YipKei** [comment]
所以日志呢？

**Comment by zzyyyl** [comment]
> 关掉后重新启动模拟器就一直卡在99%。
 
你关模拟器前有没有关 MAA（？
