### ISSUE TITLE
肉鸽有时不会选择指定低星满练干员

### ISSUE THREAD

**Issue by GreenGhost1** [MaaAssistantArknights/MaaAssistantArknights#1594]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

2022.8.17
一整天都在用maa挂机刷肉鸽 近卫，辅助，医疗
因为整体练度不高 打不到太高的层数 但也足够刷蜡烛了
配置一直是 玫兰莎，临时，调香师
2022.8.18
今天中午发现的 近卫那里不会选择玫兰莎
对于攻击力800+的0费玫兰莎 maa仍会选择攻击力300+的0费临时招募
对于干员的位置  8.17玫兰莎在临时招募之前一列 8.18玫兰莎在临时招募之后一列
我尝试了各种办法 包括调整roguelike_shopping.json中的优先级，maa设置中的开局分队，开局职业组，以及开局干员
但仍不能选择玫兰莎
有趣的是 观察到对于先锋 干员芬的位置是在临时招募之后 但无论是8.17还是8.18都会选择芬而不是临时招募

### 日志文件

[Uploading asst.log…]()

### 截图

![MuMu20220818163820](https://user-images.githubusercontent.com/111494055/185350671-708afa84-1eb0-4ed6-8800-3e034bd97c7c.png)
他会在滑到这个位置后选择临时招募

**Comment by GreenGhost1** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9371924/asst.log)
日志文件

**Comment by GreenGhost1** [comment]
关于之前提到的先锋 他的位置与近卫略微不同

![MuMu20220818164337](https://user-images.githubusercontent.com/111494055/185352236-516dd37a-c2e9-4dd4-bfd8-c1e860a676ea.png)

可以看到 芬虽然在临时招募之后 但仍然在一列
而玫兰莎和临时招募则是在不同的列

**Comment by et2012** [comment]
是有这个问题，主要是为了减少滑动次数，检测到预备干员的时候，就会停止滑动。

**Comment by GreenGhost1** [comment]
没有找到"is_alternate": true在哪个json源文件中....

**Comment by et2012** [comment]
> 没有找到"is_alternate": true在哪个json源文件中....

roguelike_recruit.json

**Comment by GreenGhost1** [comment]
把"is_alternate": false添加到Alternate前面吗
（我曾尝试把最后的整个alternate删掉 仍然不起作用）

**Comment by et2012** [comment]
> 把"is_alternate": false添加到Alternate前面吗 （我曾尝试把最后的整个alternate删掉 仍然不起作用）

只把 true 改为 false，像这样：

```
    "ALTERNATE": [
        {
            "name": "预备干员-近战",
            "skill": 0,
            "recruit_priority": 5,
            "promote_priority": 0,
            "is_alternate": false
        },
        {
            "name": "预备干员-狙击",
            "skill": 0,
            "recruit_priority": 5,
            "promote_priority": 0,
            "is_alternate": false
        },
        {
            "name": "预备干员-术师",
            "skill": 0,
            "recruit_priority": 5,
            "promote_priority": 0,
            "is_alternate": false
        },
        {
            "name": "预备干员-后勤",
            "skill": 0,
            "recruit_priority": 5,
            "promote_priority": 0,
            "is_alternate": false
        }
    ]

```

或者下载这个改好的，去掉后缀 .txt （.json.txt 改为 .json）
[roguelike_recruit.json.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9372401/roguelike_recruit.json.txt)

**Comment by GreenGhost1** [comment]
奇怪 我的这个json文件最底部没有这样的代码
[roguelike_recruit.json.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9372410/roguelike_recruit.json.txt)


不过无关紧要吧 对于这个问题近期会进行优化吗？

**Comment by et2012** [comment]
> 奇怪 我的这个json文件最底部没有这样的代码 [roguelike_recruit.json.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9372410/roguelike_recruit.json.txt)
> 
> 不过无关紧要吧 对于这个问题近期会进行优化吗？

这就很神奇了，你用的是最新测试版 4.3.0-beta.1 吗？
你的资源文件是旧版的，但程序的行为却是新版的。

**Comment by GreenGhost1** [comment]
我记得下载的是稳定版吧...（神奇）
不过既然能正常运行就先用着吧 期待下次更新 谢谢

**Comment by MistEO** [comment]
> > 奇怪 我的这个json文件最底部没有这样的代码 [roguelike_recruit.json.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9372410/roguelike_recruit.json.txt)
> > 
> > 不过无关紧要吧 对于这个问题近期会进行优化吗？
> 
> 这就很神奇了，你用的是最新测试版 4.3.0-beta.1 吗？
> 你的资源文件是旧版的，但程序的行为却（像）是新版的。
> 觉得影响不大的话可以等更新，之后会优化的。

稳定版 ROI 设小了，beta 修过了

**Comment by GreenGhost1** [comment]
> > > 奇怪 我的这个json文件最底部没有这样的代码 [roguelike_recruit.json.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9372410/roguelike_recruit.json.txt)
> > > 不过无关紧要吧 对于这个问题近期会进行优化吗？
> > 
> > 
> > 这就很神奇了，你用的是最新测试版 4.3.0-beta.1 吗？  你的资源文件是旧版的，但程序的行为却（像）是新版的。  觉得影响不大的话可以等更新，之后会优化的。
> 
> 稳定版 ROI 设小了，beta 修过了
> 
> 在日志头部可以看到版本号的

所以测试版是目前比较完善，bug较少的对吧

**Comment by et2012** [comment]
> 
> 所以测试版是目前比较完善，bug较少的对吧

你可以两个版本都试用一下，对比一下看看效果。
测试版改了招募逻辑，会把干员滑一遍再选一个优先级最高的。
但遇到预备干员就会停止划动。

**Comment by et2012** [comment]
> 昨晚经过测试 已经将roguelike_recruit.json中的"is_alternate": ture改为"is_alternate": false&nbsp; 该问题仍然无法解决 仍会选择临时招募 今早试了两次 开局干员那里可以填别的 但是填最后一列的任何干员都会无法识别到 另外附上日志 

日志没上传成功

**Comment by GreenGhost1** [comment]
> > 昨晚经过测试 已经将roguelike_recruit.json中的"is_alternate": ture改为"is_alternate": false  该问题仍然无法解决 仍会选择临时招募 今早试了两次 开局干员那里可以填别的 但是填最后一列的任何干员都会无法识别到 另外附上日志
> 
> 日志没上传成功

有点大 压缩了一下
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9381585/asst.zip)

**Comment by et2012** [comment]
> > > 昨晚经过测试 已经将roguelike_recruit.json中的"is_alternate": ture改为"is_alternate": false  该问题仍然无法解决 仍会选择临时招募 今早试了两次 开局干员那里可以填别的 但是填最后一列的任何干员都会无法识别到 另外附上日志
> > 
> > 
> > 日志没上传成功
> 
> 有点大 压缩了一下 [asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9381585/asst.zip)

11:33:46.913 、12:36:02.641、13:19:15.913 的重装招募，选了预备干员，那是因为重装没有别的可以选了。
当前页面干员：预备干员-近战, 临光, 古米, 暮落, 角峰, 泡泡, 蛇屠箱, 坚雷。
这些都不在候选列表里，默认重装只会招募：泥岩、塞雷娅、斑点、卡缇，如果没有这四个，就会招募预备干员。

12:31:58.191、14:40:46.708 的辅助招募，选了预备干员-术师，也是一样的原因。
当前页面干员：预备干员-术师, 月禾, 深海色, 初雪, 波登可, 地灵, 罗比菈塔。

没看到近卫招募不选枚兰莎。
