### ISSUE TITLE
肉鸽模式 每次出现剧目后即卡死

### ISSUE THREAD

**Issue by passingby000** [MaaAssistantArknights/MaaAssistantArknights#1595]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽模式中，出现剧目后卡死。多次出现该问题。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9372948/asst.zip)
时间点：末尾。见截图。

### 截图
第一张和第二张截图为卡死时的模拟器状态，第三张是我手动停止脚本后的消息，可以看见12分卡死后直到19分时没有任何动作。

![report1](https://user-images.githubusercontent.com/80258900/185383460-fadf0f83-865d-4602-83cd-a15ca17c11de.png)
![report2](https://user-images.githubusercontent.com/80258900/185383465-e5ba14c6-3871-41f1-b570-19ab7076ee80.png)
![report3](https://user-images.githubusercontent.com/80258900/185383476-a34a64b7-5863-4059-aa04-a46aa1df4eb7.png)

### 还有别的吗？

模拟器版本：BlueStacks App Player 5.9.10.1008 N32
MAA版本：4.2.4
系统版本：win10

**Comment by zzyyyl** [comment]
link to #221, #1480

@MistEO 

另外，我没找到 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/221#issuecomment-1114010406 里提到的 `v3.1.3` 版本找到修复这个问题的提交啊（？

**Comment by Mangolia-club** [comment]
我想我找到了解决办法（刚刚
它那个背景后面有一层烟雾效果
而resources里面的匹配图片过大，通常会导致检测时包含了背景里面变化的烟雾效果而识别失败卡死
我自己试了下把匹配的图片的框选范围变小能很大很大程度上解决这个问题
明天我自己测试下，如果稳定不出现同样的问题提一下pr

**Comment by Mangolia-club** [comment]
> 我想我找到了解决办法（刚刚
> 它那个背景后面有一层烟雾效果
> 而resources里面的匹配图片过大，通常会导致检测时包含了背景里面变化的烟雾效果而识别失败卡死
> 我自己试了下把匹配的图片的框选范围变小能很大很大程度上解决这个问题
> 明天我自己测试下，如果稳定不出现同样的问题提一下pr

补充，识别的是对勾图标的外切正方形，我尝试的是减小到只有对勾，目前误触的其他地方的情况还没出现过
