### ISSUE TITLE
自动战斗功能下史尔特尔部署阶段识别问题

### ISSUE THREAD

**Issue by daichuanqi11** [MaaAssistantArknights/MaaAssistantArknights#1596]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

8.19夏活新关卡IC-EX-1和IC-EX-2，尝试使用群里两份含史尔特尔的作业，在自动编队过程中没有出现问题，进入战斗后，都在部署史尔特尔这一步卡住，先后尝试换了4个立绘都无法正常识别部署。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9375635/asst.log)
以下截图在00:15左右运行脚本时生成

### 截图

![U%YD)(~3SC2U_~%NRU17ASQ](https://user-images.githubusercontent.com/52565645/185444082-2606b8ac-a274-499a-8780-dda37bbe3007.png)
![1 B V~}5`URJC848RBWT)5A](https://user-images.githubusercontent.com/52565645/185444935-998620af-b5c2-4aa0-90c9-d0b5ab4423d3.png)

不清楚adb保存截图存放位置，debug和map文件夹下都没找到相关截图

### 还有别的吗？

win10环境，模拟器是蓝叠中国5 Nougat64位

**Comment by daichuanqi11** [comment]
补充一下，用无专精立绘时有时可以正常部署，有偶发性

**Comment by zzyyyl** [comment]
估计是因为42立绘太红，跟上次的洁哥一个问题
