### ISSUE TITLE
新测试版基建填充信赖干员的问题

### ISSUE THREAD

**Issue by Misaka2623** [MaaAssistantArknights/MaaAssistantArknights#1598]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

为第3个宿舍填充信赖干员后，如果第4个宿舍内已有干员，信赖值的排序会将这些干员放在最前面，然后MAA会选择之前已经入驻了的干员，但并不判断他们的信赖是否为100%

也许可以在补充信赖干员时先清空并保存一次宿舍然后再补充？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9378169/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/7156817/185509951-eb029828-fef2-4255-8c11-3e75ee80795c.png)

**Comment by MistEO** [comment]
@ABA2396 提到一个问题，假如我最后一个宿舍让 `年` + 另外两个回心情的干员 996，按信赖选是不是就把那俩回心情的下掉了

cc @Hydrogina

**Comment by MistEO** [comment]
link to https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1592

**Comment by MistEO** [comment]
> > @ABA2396 提到一个问题，假如我最后一个宿舍让 `年` + 另外两个回心情的干员 996，按信赖选是不是就把那俩回心情的下掉了
> > cc @Hydrogina
> 
> 利用宿舍来蹭信赖和利用宿舍来回心情这两个需求是互斥的，只能把蹭信赖功能做成可选的，在GUI里加一个选项了

当前测试版本其实这样的就还好我感觉，不下人的同时又小蹭一手信赖 XD

**Comment by ABA2396** [comment]
> > > @ABA2396 提到一个问题，假如我最后一个宿舍让 `年` + 另外两个回心情的干员 996，按信赖选是不是就把那俩回心情的下掉了
> > > cc @Hydrogina
> > 
> > 
> > 利用宿舍来蹭信赖和利用宿舍来回心情这两个需求是互斥的，只能把蹭信赖功能做成可选的，在GUI里加一个选项了
> 
> 当前测试版本其实这样的就还好我感觉，不下人的同时又小蹭一手信赖 XD

问题是全部满信赖的时候是按照技能排的，菲亚梅塔是第一个，导致直接给心情未满的回复了

**Comment by ABA2396** [comment]
说起来刷信赖都按照未进驻选择了，为啥回心情不用未进驻选）

**Comment by MistEO** [comment]
加了个未进驻的选项 fixed
