### ISSUE TITLE
能适配台服吗？

### ISSUE THREAD

**Issue by zxc173123** [MaaAssistantArknights/MaaAssistantArknights#1602]
### 说说你遇到的问题？

不认繁体字

**Comment by ABA2396** [comment]
参考[README_zh-TW.md](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/README_zh-TW.md#%E5%A4%96%E6%9C%8D%E6%94%AF%E6%8F%B4)

**Comment by MistEO** [comment]
![Screenshot_2022-08-19-20-07-04-767_com.github.android-edit.jpg](https://user-images.githubusercontent.com/18511905/185615127-b82e1570-5561-4220-bd76-84ddf769d263.jpg)
