### ISSUE TITLE
最大化至纯源石转换理智效率

### ISSUE THREAD

**Issue by martinwang2002** [MaaAssistantArknights/MaaAssistantArknights#1607]
### 说说你遇到的问题？

MAA不考虑恢复下一点理智所需要的时间，直接使用源石。
如果在0:01后恢复理智，则相当于浪费了1点理智。

1理智也是理智，如果不考虑挂机过程中的时间消耗，应当勤俭节约。

### 有什么好的想法？

只有在恢复下一点理智需要的时间大于5:30(? 5:00也不是不行)的时候，才使用源石。

可以提供设置修改该行为。

**Comment by zzyyyl** [comment]
这点理智优化，大概是不会做的吧。
感觉跟基建无人机卡时间差不多操作，没啥必要？

~~你都碎石了，缺这点理智吗.jpg~~

**Comment by MistEO** [comment]
价格插件到好做，就感觉没啥必要

**Comment by MistEO** [comment]
这个模式叫啥名字好？

**Comment by zzyyyl** [comment]
理智管理大师.jpg
