### ISSUE TITLE
C# 代码注释相关的还是不要 warning 了吧（

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#1611]
### 说说你遇到的问题？

太烦了（

而且我觉得绝大部分变量依赖变量名完全足够理解它是做什么用的了。如果不行，要么是写的人的问题，要么是读的人的问题。

**Comment by LYZhelloworld** [comment]
@MistEO 有截图吗？

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/185728117-85cdfe44-2dd4-4c50-abe1-3e8a24fdd34c.png)
