### ISSUE TITLE
会客室换班的干员效率问题

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaAssistantArknights#1612]
### 说说你遇到的问题？

根据PRTS [线索搜集](https://prts.wiki/w/%E7%BD%97%E5%BE%B7%E5%B2%9B%E5%9F%BA%E5%BB%BA/%E4%BC%9A%E5%AE%A2%E5%AE%A4#%E7%BA%BF%E7%B4%A2%E6%90%9C%E9%9B%86%E7%9B%B8%E5%85%B3)
![image](https://user-images.githubusercontent.com/72590023/185721438-b2e2eac5-8de8-4aea-aaef-5e62fd405fff.png)

也就是精二干员和六星干员也会对效率产生影响

那么能不能改一下放干员的算法呢 (譬如不要把12f放上去, 以及不要放精一的白雪上去 ~虽然现在他没有用但12小时候就有用了啊~)

### 有什么好的想法？

以上

### 其他内容

以上

**Comment by ABA2396** [comment]
Duplicate of #46
