### ISSUE TITLE
关于`无限刷肉鸽`按钮的位置

### ISSUE THREAD

**Issue by sileence114** [MaaAssistantArknights/MaaAssistantArknights#1616]
### 说说你遇到的问题？

我觉得无限刷肉鸽应该作为任务列表完成后的操作，而不应该作为任务本身。

### 有什么好的想法？

将“无限刷肉鸽”选项移动到“完成后”的操作列表，与关模拟器、关机、休眠等操作并列。
（当前版本下无限刷肉鸽点上之后任务队列就不会结束，也不会进入后续的关机等操作。）
![image](https://user-images.githubusercontent.com/35139387/185733122-bb13deba-4050-49da-979e-ba9cc0f18cc5.png)

### 其他内容

如果目前有无限刷肉鸽有添加终止条件（如刷多长时间、出多少蜡烛等条件）的计划，则可考虑保留任务列表中的肉鸽选项，将”**无限**刷肉鸽“（无终止条件）的选项添加到”完成后菜单“

**Comment by sileence114** [comment]
我觉得label应该添加[module: GUI](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues?q=is%3Aissue+is%3Aopen+label%3A%22module%3A+GUI%22)

**Comment by MistEO** [comment]
有没有发现现在不叫 `无限刷肉鸽` 了，看下设置界面（
