### ISSUE TITLE
定时启动模拟器 

### ISSUE THREAD

**Issue by julynet** [MaaAssistantArknights/MaaAssistantArknights#1619]
### 说说你遇到的问题？

每次使用定时运行功能时，都要将模拟器挂在后台，比较耗资源

### 有什么好的想法？

定时任务进行开始前，默认选项加一个是否启动模拟器。结合运行完成关闭模拟器，形成完美闭环（

**Comment by sher-l** [comment]
连接不成功会自动打开模拟器的

**Comment by julynet** [comment]
> 连接不成功会自动打开模拟器的

![image](https://user-images.githubusercontent.com/93466263/185818285-87698225-e392-4a20-bb40-f2613ab99a59.png)
昨晚的定时（

**Comment by zzyyyl** [comment]
草，这个跟我之前说的是一个问题

**Comment by sher-l** [comment]
> > 连接不成功会自动打开模拟器的
> 
> ![image](https://user-images.githubusercontent.com/93466263/185818285-87698225-e392-4a20-bb40-f2613ab99a59.png) 昨晚的定时（

那建议勾选打开启动后开启模拟器,
然后自己设置个定时打开MAA好了, 这样你甚至可以不挂MAA在后台.

**Comment by julynet** [comment]
> > > 连接不成功会自动打开模拟器的
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/93466263/185818285-87698225-e392-4a20-bb40-f2613ab99a59.png) 昨晚的定时（
> 
> 那建议勾选打开启动后开启模拟器, 然后自己设置个定时打开MAA好了, 这样你甚至可以不挂MAA在后台.

我前面测试了下 “启动后直接运行”这个选项好像没有效果

**Comment by julynet** [comment]
> > > 连接不成功会自动打开模拟器的
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/93466263/185818285-87698225-e392-4a20-bb40-f2613ab99a59.png) 昨晚的定时（
> 
> 那建议勾选打开启动后开启模拟器, 然后自己设置个定时打开MAA好了, 这样你甚至可以不挂MAA在后台.

感谢 我先测试几天后再反馈结果

**Comment by zzyyyl** [comment]
不是 `启动后直接运行`，是 `启动后自动开启模拟器`
然后要填上模拟器路径

**Comment by julynet** [comment]
> 不是 `启动后直接运行`，是 `启动后自动开启模拟器` 然后要填上模拟器路径

我已经搞定了 哈哈哈 是我太心急了 脚本启动前有个sleep我忘记了
![image](https://user-images.githubusercontent.com/93466263/185833898-e691395e-9b54-4cc9-bc6c-6eb704c8aca5.png)
