### ISSUE TITLE
使用自动战斗时程序卡住

### ISSUE THREAD

**Issue by heluene** [MaaAssistantArknights/MaaAssistantArknights#1620]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

运行某个别人可以正常使用的作业脚本，到某一步时（包括指定时机的部署和技能），程序实际上不再执行任何指令，如停止开始等

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9388151/asst.log)

### 截图

![QQ截图20220821073530](https://user-images.githubusercontent.com/107483017/185769448-a99208ff-c658-4ed4-acf6-53052b234073.png)
![QQ截图20220821073540](https://user-images.githubusercontent.com/107483017/185769450-7c1eeb95-7267-4969-8e7d-4ef22cf143a9.png)

**Comment by MistEO** [comment]
这份作业还在么，发下瞅瞅

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/187040690-e6b825d5-0793-403e-b361-a9a978c8d51a.png)


是群里这份作业么，这作业写得有问题啊，别人能运行么？_(:з」∠)_

cost change 怎么可能达到 99 啊

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/187040823-bc11e021-0fcd-4224-bd48-237f0b15fdfd.png)

下次跟作业作者说一下 orz

**Comment by heluene** [comment]
在执行63费的步骤之前就已经卡住了，点停止都没反应

**Comment by heluene** [comment]
作业写错了那是另一回事，除非后面的步骤出错能影响前面的

**Comment by heluene** [comment]
顺便问一句，50000前延迟撤退干员，点了一下干员又点到别处去了没撤退，是bug吗？

**Comment by heluene** [comment]
要再提个issue吗？
