### ISSUE TITLE
建议肉鸽开局支持借干员

### ISSUE THREAD

**Issue by XinyuShe** [MaaAssistantArknights/MaaAssistantArknights#1621]
### 说说你遇到的问题？

练度较低的号刷肉鸽等级过慢了

### 有什么好的想法？

如果可以借一个棘刺或者山效率更高一些，建议加个可以识别设置的开局干员是否在精一以上，否则借一个精二的

**Comment by passingby000** [comment]
隔壁软件的自动刷原石锭就是靠借一个精二山。
https://www.yuque.com/books/share/918203ee-a168-4718-bb13-ff46c0088faa

其中开源版本下载页
https://www.yuque.com/books/share/918203ee-a168-4718-bb13-ff46c0088faa/egf2pg

**Comment by MistEO** [comment]
确实可以加，不过马上傀影肉鸽都结束了，等水月肉鸽出来再看看吧

**Comment by Kevin-Beta** [comment]
自动精灵脚本刷肉鸽有这一项，还是希望MAA也能加上这个功能

**Comment by cenfusheng** [comment]
Done
