### ISSUE TITLE
肉鸽：压轴登场地面干员部署错误

### ISSUE THREAD

**Issue by irrrrrrrr** [MaaAssistantArknights/MaaAssistantArknights#1622]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

会把地面干员全部部署在下路，左路一直漏

### 日志文件

[Uploading asst.log…]()

### 截图

![Uploading MuMu20220821120504.png…]()

**Comment by MistEO** [comment]
> 你的日志没有上传成功，请重新上传。
> 
> Your log did not upload successfully, please re-upload it.

@zzyyyl 这种自动加个 “miss log” 的 label ？

**Comment by zzyyyl** [comment]
incomplete 是吧

**Comment by MistEO** [comment]
> incomplete 是吧

那能不能再在重新上传日志后，自动去掉 imcomplete （

**Comment by zzyyyl** [comment]
> > incomplete 是吧
> 
> 那能不能再在重新上传日志后，自动去掉 imcomplete （

我试试。

**Comment by zzyyyl** [comment]
@irrrrrrrr 你的日志没有上传成功，请重新上传。

Your log did not upload successfully, please re-upload it.
