### ISSUE TITLE
周日 `今日关卡小提示` 与 `备选` 在默认窗口大小下会重叠

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantArknights#1623]
### 说说你遇到的问题？

RT

### 有什么好的想法？

也许可以调调选项间距或者加个滚轮？
或者干脆把默认窗口大小调大一点？

### 其他内容

![image](https://user-images.githubusercontent.com/74587068/185776863-39c54746-bb83-4207-b94a-90a0d418ad08.png)

**Comment by ABA2396** [comment]
只有星期天有这种情况（）
