### ISSUE TITLE
关于肉鸽的一些改进建议

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantArknights#1630]
### 说说你遇到的问题？

~~其实没遇到问题来着~~

### 有什么好的想法？

1. 建议把通过关卡之后获得的藏品做一个识别
   - [ ] 每关打完后可能掉落藏品，可以加进现有的藏品联动逻辑
   - [ ] 第三层 boss 打完有自选藏品<sup>1</sup>，可以利用藏品列表做一个优选
   - [ ] 有的剧目集<sup>2</sup>会额外赠送藏品，也可以考虑进来
2. 建议把一些藏品增加到藏品列表里并且提高优先级
   - [ ] `无度`<sup>3</sup>

---
_Note 1:  如果有藏品 `四叶草化石`，在每关打完后掉落藏品也有自选_

_Note 2:  `《独行客》`：本层在下一次进入的商店中任意消费后，获得一件赠送的随机收藏品_

_Note 3:  MAA 现有的逻辑是拿命填，因此 `无度` 显得比较有用。`无度`：每次敌人进入保护目标点时，立刻对全场所有敌人造成 3000 点真实伤害_

**Comment by zzyyyl** [comment]
就是这么整的话好像还得大改，还是等水月出来之后再看看吧（

**Comment by Guy1m0** [comment]
孑的优先级能不能调低一些，无论是招募选择还是上场时机。。看着场下坐着一堆6星精二干员因为卡费上不去，自己手操又会导致“任务出错”，谢谢

**Comment by zzyyyl** [comment]
> 孑的优先级能不能调低一些，无论是招募选择还是上场时机。。看着场下坐着一堆6星精二干员因为卡费上不去，自己手操又会导致“任务出错”，谢谢

孑已经ban了，检查你的版本号，如果有的话新开一个bug issue。

**Comment by zzyyyl** [comment]
> > 
> 
> > > 孑的优先级能不能调低一些，无论是招募选择还是上场时机。。看着场下坐着一堆6星精二干员因为卡费上不去，自己手操又会导致“任务出错”，谢谢
> > 
> > 
> > 我记得孑已经ban了，检查你的版本号，如果还有问题的话新开一个bug issue。
> 
> 从哪个版本开始？前一阵子用4.24，最近改了4.30 beta2，还是有主动选择

那大概是bug？来个新 issue，带上日志

**Comment by zzyyyl** [comment]
对不起，不知道为啥所有人都觉得孑已经被 ban 了，但是其实没有（

**Comment by zzyyyl** [comment]
对不起，不知道为啥所有人都觉得孑已经被 ban 了，但是其实没有（

**Comment by xuyuanhao-SK07** [comment]
> 对不起，不知道为啥所有人都觉得孑已经被 ban 了，但是其实没有（ 马上改

肉鸽里老鲤这类行商是不是都该ban一下，有一局正好看见MAA选了老鲤，然后我看着他把老鲤下了导致后面一个人都上不了最后寄了。
