### ISSUE TITLE
肉鸽剧目在4.3.0 Beta2 版本下依然卡死

### ISSUE THREAD

**Issue by passingby000** [MaaAssistantArknights/MaaAssistantArknights#1631]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽 剧目集界面卡死
与之前相似报告的情况相同，最新版还是不行。

### 日志文件

上传失败，我重新上传一下

### 还有别的吗？

模拟器版本：BlueStacks App Player 5.9.10.1008 N32
MAA版本：4.3.0 Beta.2
系统版本：win10

**Comment by passingby000** [comment]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9392117/asst.zip)
asst 日志文件
![image](https://user-images.githubusercontent.com/80258900/185861235-1bad88f8-5a17-4ebe-9507-1d180c912cc6.png)
截图文件

**Comment by zzyyyl** [comment]
嗯？什么时区
