### ISSUE TITLE
肉鸽使用非默认分队/职业组出现的孑招募问题

### ISSUE THREAD

**Issue by Guy1m0** [MaaAssistantArknights/MaaAssistantArknights#1633]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

之前另一个Post里面提到了这个问题，以为是潜在优化点，后来发现孑其实已经ban了。。

开局分队选择：突击战术分队
开局职业选择：取长补短
开局干员（单个）：棘刺

在这个组合下，出现了特种招募券，会优先选择 孑，导致后续上场会卡费。因为没有留意时间点，暂时把全部的日志附上，下次等我复现了问题，在提供较为具体的时间

PS: 程序好像链接的默认端口是5050，但每次启动bluestack，端口都会变，都要手动调整一次。。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9394943/asst.zip)

### 还有别的吗？

Win10，BlueStacks 5.9.12.1003，MAA版本：4.2.4 及 4.3.0 beta2

**Comment by Guy1m0** [comment]
可能因为我的孑已经拉满了，所以会优先先择。。2703双技能

**Comment by zzyyyl** [comment]
行商不太符合 maa 目前的战斗逻辑。马上就 ban 掉。

计划加入一些傀儡师和地刺干员。

**Comment by Guy1m0** [comment]
以及出现了两次蓝屏，Stop code: SYSTEM_THREAD_EXCEPTION_NOT_HANDLED，不知道是不是我个例问题，内存：32G，处理器：Xeon(R) W-2235
