### ISSUE TITLE
建议搞个尝试重启模拟器

### ISSUE THREAD

**Issue by desktop4025** [MaaAssistantArknights/MaaAssistantArknights#1635]
### 说说你遇到的问题？

有时候模拟器抽风了会一直重连，可以搞个尝试启动模拟器嘛，而且会卡住
![K%BR2R`)0G59X4ZE58XS@(D](https://user-images.githubusercontent.com/107090995/185943780-138890b1-fd71-48b4-a1d7-16da4684fa6b.png)

**Comment by zzyyyl** [comment]
Add GUI

**Comment by zzyyyl** [comment]
是不是跟 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1277 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1619 类似？

**Comment by zzyyyl** [comment]
你这是什么情况下遇到的问题啊（

是你的模拟器卡了么？然后希望 maa 把模拟器重启一下？
还是说模拟器直接退了？

**Comment by desktop4025** [comment]
> 你这是什么情况下遇到的问题啊（
> 
> 是你的模拟器卡了么？然后希望 maa 把模拟器重启一下？ 还是说模拟器直接退了？

对的

**Comment by desktop4025** [comment]
现在是直接游戏崩溃，然后就不行了
![_K`1S7~99$VO$PB`NL3$ZBP](https://user-images.githubusercontent.com/107090995/185949535-32db8b82-c46a-4232-b3b9-98cc510ec1fc.png)
还有这样

**Comment by desktop4025** [comment]
希望把模拟器重启一下，maa没退

**Comment by desktop4025** [comment]
显示是游戏崩了

**Comment by zzyyyl** [comment]
那标题是不是应该写 ”重启“ ？我应该没理解错吧（

**Comment by desktop4025** [comment]
> 那标题是不是应该写 ”重启“ ？我应该没理解错吧（ 不过这估计有点难整，现在好像连关闭模拟器都没整好（？
> 
> ps: 这应该是模拟器自己的问题了吧，或者是配置有点低（？

**Comment by desktop4025** [comment]
> 那标题是不是应该写 ”重启“ ？我应该没理解错吧（ 不过这估计有点难整，现在好像连关闭模拟器都没整好（？
> 
> ps: 这应该是模拟器自己的问题了吧，或者是配置有点低（？

**Comment by desktop4025** [comment]
> 那标题是不是应该写 ”重启“ ？我应该没理解错吧（ 不过这估计有点难整，现在好像连关闭模拟器都没整好（？
> 
> ps: 这应该是模拟器自己的问题了吧，或者是配置有点低（？

发现问题了
只有在刷ic-7时发生这个错误
![5O53K60I8B87GD}F BPQGOP](https://user-images.githubusshangmnt.com/107090995/185953866-10d5c85c-e000-4e3c-8bc6-308643dcca6b.png)
，看来是个bug
上面是我点错了别管就行（x
shang'm

**Comment by desktop4025** [comment]
综上就是我建议加一个重启模拟器，但是这个刷ic-7卡住应该是bug

**Comment by zzyyyl** [comment]
Add GUI

**Comment by desktop4025** [comment]
我现在观察下来是因为不知道为什么会跳7的剧情可能是因为这个卡住了

**Comment by desktop4025** [comment]
我看再刷几次是什么原因

**Comment by desktop4025** [comment]
现在好了看来是因为跳出剧情了才卡住了

**Comment by desktop4025** [comment]
如果可以的话也可以加个啥如果出剧情就跳过的判断啥的

**Comment by zzyyyl** [comment]
> 如果可以的话也可以加个啥如果出剧情就跳过的判断啥的

虽然好像是已知问题了，但你也可以再来个 issue

**Comment by desktop4025** [comment]
> > 如果可以的话也可以加个啥如果出剧情就跳过的判断啥的
> 
> 虽然好像是已知问题了，但你也可以再来个 issue

遇到了也就知道了，可以给大家个提醒，先这样吧（x

**Comment by ABA2396** [comment]
ic7的剧情活动刚开的时候yj可能忘了放了，后来是闪断更新补上的，所以会跳剧情。模拟器抽风可能没啥办法，但我感觉任务失败重启游戏还是好做的（）

**Comment by ntgmc** [comment]
感谢反馈。
Thank you for your feedback.
