### ISSUE TITLE
GUI中以下字段仅在link start后保存，似乎并没有这么做的意义？

### ISSUE THREAD

**Issue by lhhxxxxx** [MaaAssistantArknights/MaaAssistantArknights#1638]
### 说说你遇到的问题？

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/c91f2c3ad7fe3329a3301eefb2c4aea333f66096/src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs#L771-L787

看git blame后，怀疑是历史遗留问题
![image](https://user-images.githubusercontent.com/91231470/186009384-fee49a7f-02bc-4c6e-b04e-4ccd32b16331.png)

**Comment by lhhxxxxx** [comment]
并且这导致了在运行时点修改也不会保存修改的内容，虽然可以在修改时也调用此函数，但似乎改为即时保存更为直接

**Comment by MistEO** [comment]
下次机器 commit 内容加个 fix #xxx

**Comment by lhhxxxxx** [comment]
> 下次记得 commit 内容加个 fix #xxx

push完想起来了（）
