### ISSUE TITLE
要不要加一个代理连续失误（三次及以上）就停止刷理智，去做下一项任务。

### ISSUE THREAD

**Issue by rnzfgm** [MaaAssistantArknights/MaaAssistantArknights#1641]
### 说说你遇到的问题？

点了代理就去上厕所了，回来一看心脏骤停，当然这是我代理百分百失误的问题（），平常人应该遇不到这种情况（我是笨蛋），要是大家忙的话，这个issue就当我没提，毕竟也算极端情况了（）。

### 有什么好的想法？

加一个代理连续失误（三次及以上）就停止刷理智，去做下一项任务。

### 其他内容

![5 0O_J @ Y7 2AC17T(5I5X](https://user-images.githubusercontent.com/73269504/186059538-af898e9e-b085-4700-ac76-516073655311.png)

**Comment by zzyyyl** [comment]
现在的代理失误好像是纯粹的 ProcessTask？
连续三次以上好像不太好整，要不整一个累计失误多少次停止？

**Comment by MistEO** [comment]
> 现在的代理失误处理好像是纯粹的 ProcessTask？
> 
> 连续三次以上好像要重构，要不整一个累计失误多少次停止？

好整，设个 3次，然后再每次作战成功就 reduceOthers 把代理失败 -1，

**Comment by rnzfgm** [comment]
> 现在的代理失误处理好像是纯粹的 ProcessTask？
> 
> 连续三次以上好像要重构，要不整一个累计失误多少次停止？

都行（），大家怎么方便写怎么来吧（orz）

**Comment by zzyyyl** [comment]
来个日志？
