### ISSUE TITLE
肉鸽招募只有少量干员时加快招募速度

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantArknights#1642]
### 说说你遇到的问题？

具体见下面截图。
在这个界面，会不断试图往右寻找干员，但其实没有必要
（大概是因为蜜莓优先级有点低？）

### 其他内容

![image](https://user-images.githubusercontent.com/74587068/186058940-bb0d8fa0-7aea-48f6-9120-14c0aa69451a.png)

暂且也传个日志，不过感觉大概没啥必要
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9398979/asst.-.3.log)
（大概在靠后的部分，10：51左右）

**Comment by et2012** [comment]
27e76fa7a308a33d70794ad73a2f85aa9ff2c940 其实我已经改好了，在测试

**Comment by MistEO** [comment]
是不是修过了
