### ISSUE TITLE
基建赤金队清流队友建议

### ISSUE THREAD

**Issue by suzakinishi** [MaaAssistantArknights/MaaAssistantArknights#1651]
### 说说你遇到的问题？

243 无小车
清流森蚺温蒂  1.15
清流至简砾      1.15
MAA的逻辑会优先选择清流至简砾，导致二队只能上30的工具人。如果优先选清流森蚺温蒂，把至简砾留给其他队效率会高一些

**Comment by MistEO** [comment]
来个日志看看

**Comment by suzakinishi** [comment]
日志我上传了，基建换队从13:49:03开始。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9421800/asst.log)
