### ISSUE TITLE
肉鸽卡招募界面

### ISSUE THREAD

**Issue by TStianshi** [MaaAssistantArknights/MaaAssistantArknights#1655]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天发现（之前没发现）模拟器打肉鸽时卡招募界面，显示“确认放弃此次招募机会吗”

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9415543/asst.zip)

### 截图

![OR$3{X QW)}ZDWW 584V$17](https://user-images.githubusercontent.com/99545796/186404890-e3327bbd-e490-4036-9943-31b6922dcf0b.png)
![A}BE 9EUIT D@$9$69NDBCM](https://user-images.githubusercontent.com/99545796/186404972-ec567e03-b1ea-41b9-8389-a30828cf1df2.png)

### 还有别的吗？

夜神模拟器
win11
cpu Intel 酷睿i5 10400
GPU GTX750ti

**Comment by et2012** [comment]
看样子是截屏问题
17:19:40.636 截屏返回大小只有 36230，估计是黑屏。正常大小应该是 1225372
17:19:40.687 识别干员失败，因为没滑动过，会被判定为：检测到晋升界面但没有干员可以晋升，退出招募

**Comment by TStianshi** [comment]
修改清晰度就正常了

**Comment by MistEO** [comment]
v4.4.0-beta.2 修了一个截图问题，试试看
