### ISSUE TITLE
佬们请问我该下载哪个AWA

### ISSUE THREAD

**Issue by Cintser** [MaaAssistantArknights/MaaAssistantArknights#1659]
### 说说你遇到的问题？

我win10，64位，明日方舟用的雷电模拟器AWA
顺便问一下在github每当遇到琳琅满目的文件时该如何选出自己需要的文件？

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/186595214-4a6c918d-b116-46a2-a6af-39490a84ec36.png)
[MaaBundle](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.3.0-beta.4/MaaBundle-v4.3.0-beta.4.zip)是完整包 
[MaaBundle-OTA](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.3.0-beta.4/MaaBundle-OTA-v4.3.0-beta.4.zip)是老版本的升级包 
[MaaDependencyNoAvx](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.3.0-beta.4/MaaDependencyNoAvx-v4.3.0-beta.4.zip)是给不支持Avx用户的替代 
具体的考验看文档
其他的不用管

**Comment by MistEO** [comment]
遇到问题提问前请先看文档，特别是在主文档上强调了三遍的问题
