### ISSUE TITLE
多次出现maa虚空执行并完成任务的情况

### ISSUE THREAD

**Issue by Asattos** [MaaAssistantArknights/MaaAssistantArknights#1660]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

遇到过多次这种情况：

(maa设置：勾选了‘’开始唤醒‘’及其后的一系列任务，其他设置也没有任何问题，唯一特别的是勾选了 开机自动启动、启动后直接运行 和 启动后自动开启模拟器 ，等待模拟器启动时间 为120秒)

maa在模拟器还没初始化完毕，或者模拟器中的方舟刚刚成功由maa点开时，就已经结束了“开始唤醒”任务，然后便开始虚空执行其后的所有任务，并且其他任务几乎都在开始后10秒内显示完成。最后“任务已全部完成”，但游戏还在热更新界面跳动着黄色菱形。。。

家里的两台电脑（都是古董QAQ）上都碰到过这种情况，而且多发生在非手动打开maa的时候（比如说windows自带的任务计划程序或者bios的定时开机）。。。我只是想通过台式机bios里的定时开机实现彻底的自动化挂机方舟啊，想当究极懒狗终究是太难了T-T

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9422647/asst.log)

时间段：
[2022-08-25 15:01:35.668]由 bios的电源设置-定时开机 + maa自身设置开机自启 启动maa
到
[2022-08-25 15:06:44.106]maa界面显示“任务已全部完成”

### 截图

![01](https://user-images.githubusercontent.com/112066685/186604562-a112db8e-6cc9-4213-9273-1c377a00f27a.png)
![02](https://user-images.githubusercontent.com/112066685/186604572-6b0d419e-6683-4f8a-bcb5-542b4e756d74.png)

### 还有别的吗？

使用的模拟器：蓝叠国际版Nougat 64
操作系统：win10 x64

老电脑，配置能流畅运行模拟器里的方舟，但刚重装过系统，且不支持 AVX指令集 ，按教程解决该问题后能手动正常使用maa，《常见问题》里需要的几个运行库也装了，但会出现上面提到的虚空执行情况。

**Comment by Asattos** [comment]
（明天就要返校了，住校生，可能会很晚才能回复）

**Comment by Asattos** [comment]
> （明天就要返校了，住校生，可能会很晚才能回复）

刚才试了几次夜神模拟器就没有这个问题，不会是蓝叠模拟器的原因吧。。。

**Comment by ABA2396** [comment]
先说个替代方法，把启动模拟器换成启动明日方舟，可以通过附加命令启动，或者将选择模拟器地址换成方舟的快捷方式

**Comment by MistEO** [comment]
截图一直报错，不知道为什么。可能蓝叠还没完全启动，你把 120 秒再调长点试试

**Comment by MistEO** [comment]
link to https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1672

**Comment by Asattos** [comment]
感谢，更新后这几天住校时用着都没问题，每次只用点开maa就能挂着不管了，也没有出现连接失败的情况（目前在用逍遥模拟器，蓝叠没时间再去测试了，还有1小时就得返校QAQ）
