### ISSUE TITLE
肉鸽自定义选人方法

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#167]
肉鸽选人是可配置的，但是由于时间关系还没来得及做到界面上

有需要的话可以手动修改 `resource/task.json` 文件中 `"Roguelike1ChooseOper"` 字段~

Tips: 这个文件每个版本都或多或少有差异，请不要将老版本的文件直接替换到新版本上来用，会出现一些莫名其妙的问题

![image](https://user-images.githubusercontent.com/18511905/151666026-716ca1ae-b66b-44de-8000-11e6eec3ef81.png)

同一个问题的 issue 比较多，我先统一关了，后续这个问题的新方案在这里跟进进展_(:з」∠)_

**Comment by MistEO** [comment]
Tips: 这个文件每个版本都或多或少有差异，请不要将老版本的文件直接替换到新版本上来用，会出现一些莫名其妙的问题

**Comment by duanyunlun** [comment]
我把近卫的可选人物剩下棘刺一个的时候，选不了

**Comment by Tanulav** [comment]
稍微改了一下干员list然后程序打不开了，显示出现未知异常

**Comment by MistEO** [comment]
> 稍微改了一下干员list然后程序打不开了，显示出现未知异常

对比没改过的几行，有没有多个逗号少个逗号之类的，以及双引号是否为半角等。JSON 文件是严格要求格式的

**Comment by Tanulav** [comment]
> > 稍微改了一下干员list然后程序打不开了，显示出现未知异常
> 
> 对比下没改过的行，有没有多个逗号少个逗号之类的，以及双引号是否为半角，等等。JSON 文件是严格要求格式的

ok，重新检查了一下修复了。

**Comment by Ga1en70** [comment]
怎么改带的技能啊，选什么干员都是默认1技能噢...

**Comment by nvtijuewang** [comment]
选干员不像基建那样会向后查看
比如编辑修改task.json近卫只留煌 抓干员时煌不在第一页8人里面 就会卡住
不改task.json情况都是抓优先级低的帕拉斯 因为他在第一页，不是群攻 第一层都难打过

**Comment by Lancarus** [comment]
"text": [
            "---三星备选干员---",
            "芬",
            "梓兰",
            "安赛尔",
            "克洛丝",
            "泡普卡",
            "香草",
            "史都华德",
            "夜刀",
            "预备干员",
            "---近卫---",
            "棘刺",
            "史尔特尔",
            "银灰",
            "---先锋---",
            "桃金娘",
            "---重装---",
            "塞雷娅",
            "---狙击---",
            "假日威龙陈",
            "空弦",
            "白雪",
            "---术士---",
            "艾雅法拉",
            "---治疗---",
            "凯尔希",
            "---辅助---",
            "浊心斯卡蒂",
            "---特种---",
            "红"
        ],

**Comment by NetatioAl** [comment]
我把煌改到前面根本没用啊，不知道是哪里出问题了

**Comment by NetatioAl** [comment]
> 我把煌改到前面根本没用啊，不知道是哪里出了问题了

好了，用的notepad++改会出现错行问题，用vscode改就完美解决了

**Comment by NetatioAl** [comment]
> 我把煌到前面根本没用啊，不知道是哪里的问题了

好了，用的notepad++改会出现错行问题，用vscode改就完美解决了

**Comment by zhongfly** [comment]
能不能自定义选什么队啊，目前默认是近卫辅助医疗队

**Comment by Sorakage033** [comment]
盼望修改一下人工智能的算法，在驯兽小屋那一关让芙蓉的攻击方向可以朝下🤔

**Comment by mis-match** [comment]
这里的顺序是优先级吗

**Comment by luka-cn** [comment]
我想问一下肉鸽模式怎么才能进入二倍速战斗？

**Comment by MistEO** [comment]
> 我想问一下肉鸽模式怎么才能进入二倍速战斗？

就是二倍速的，如果没点可能是bug，新开个Issue发个日志看下吧~

**Comment by Alexzz96** [comment]
肉鸽模式，技能是能设置用什么吗？比如山开一次二技能，鸡翅开2次三技能

**Comment by mengmengdm** [comment]
肉鸽建议能抓的收藏品和免费干员都抓，这样获取蜡烛的效率更高（包括多出来的原石锭随便买点东西什么的）

**Comment by MistEO** [comment]
从 v3.9.0-beta.6 版本开始，已支持自动练度识别及干员选择，使用新版本请勿再按本 issue 进行操作！
