### ISSUE TITLE
mumu启动卡死

### ISSUE THREAD

**Issue by ability66** [MaaAssistantArknights/MaaAssistantArknights#1672]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

mumu用开始唤醒启动模拟器卡死在startup

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9429307/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/106503132/186803085-bf4f1cdf-3f55-48e5-b057-3981049250da.png)
![image](https://user-images.githubusercontent.com/106503132/186803107-7e565ec9-90d6-4ac2-a70a-08a4d96737e6.png)

**Comment by horror-proton** [comment]
看上去类似于 #1509

**Comment by MistEO** [comment]
模拟器的问题，这种情况直接重启下电脑吧，如果经常遇到推荐换蓝叠国际版

MAA 或许可以在界面上加个提示啥的
