### ISSUE TITLE
http proxy如何填写

### ISSUE THREAD

**Issue by hydra24-njus** [MaaAssistantArknights/MaaAssistantArknights#1673]
### 说说你遇到的问题？

有梯子，需要这方面的用户指南

**Comment by zzyyyl** [comment]
这不应该问问你的梯子么（
一般是 `127.0.0.1:xxxx` 形式的

**Comment by ABA2396** [comment]
一般设置里都有

![image](https://user-images.githubusercontent.com/99072975/187015927-0b9e76e3-f695-40fb-a422-3d481e3da0a1.png)
127.0.0.1:7890
![image](https://user-images.githubusercontent.com/99072975/187016007-91145bbf-e733-4e6e-8c1b-8d7d4902164e.png)
127.0.0.1:10808
