### ISSUE TITLE
基建换班干员效率优化

### ISSUE THREAD

**Issue by t-lights** [MaaAssistantArknights/MaaAssistantArknights#1675]
### 说说你遇到的问题？

类似巫恋组以及红云组这样的基建加成效率受工作时间影响的组合，会因为换班时的重新选取刷新工作时长导致效率降低。
比如刻俄柏的基建技能会随工作时间增加而提高加成效率，但是如果换班时重新选择该制造站的干员并确定更换，即使仍然选择原来的干员（保持顺位不变）依然会使小刻的加成回到初始状态。贸易站巫恋组的高效率主要集中在后半段（高品质订单出率加成更多），如果换班刷新工作时长计数会导致巫恋组实质上效率达不到理想状态。

### 有什么好的想法？

换班时加个特判，如果选择的干员不变，直接点击左上角退出而非点击确定，这样就不会刷新干员工作状态了。

**Comment by Minepig** [comment]
实测重新选择干员，只要顺位不变，暖机就不会清除

**Comment by MistEO** [comment]
这个问题之前看过，不好解决。不过现在可以用自定义换班了，是可以强制排序的（
