### ISSUE TITLE
一些rogue下干员的策略问题

### ISSUE THREAD

**Issue by Mashiro173** [MaaAssistantArknights/MaaAssistantArknights#168]
![image](https://user-images.githubusercontent.com/98558933/151665973-24cdf84d-637d-446a-ad6b-df8662362940.png)
干员会下在一些比较奇怪的地方导致完全没有作用 如图中山和芙蓉一个位置有问题一个朝向有问题 还有一个三行不分高台平地的图也有同样问题 会将近卫干员下在最上面一行 将没有攻击能力的奶下在下面出怪的两行且在最前排 可能会导致阻挡怪但无人攻击导致卡关
并且目前好像都只会默认选1技能 是否可以在后续版本加入自定义选干员技能的选项 
![image](https://user-images.githubusercontent.com/98558933/151666199-9819352c-fcb3-4737-94b8-51807cc88796.png)
奶的朝向问题目前来看影响较大 能否改为判定朝向我方干员最多的方向
感谢大佬开发

**Comment by Mashiro173** [comment]
![image](https://user-images.githubusercontent.com/98558933/151674378-9def6ca4-192d-49dd-9414-a6307d38d0d3.png)
这会又截到一张 术士面壁

**Comment by MistEO** [comment]
[v3.0.1](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v3.0.1) 版本简单优化了一下。没有办法做到完全智能的_(:з」∠)_
