### ISSUE TITLE
掉落识别和上传企鹅带上唯一 id，并加上上传成功的回调

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#1681]
### 说说你遇到的问题？

方便 ui 区分是哪次上传成功了。

另外公招的上传也可以加一下

cc @ChingCdesu @bakashigure

**Comment by MistEO** [comment]
现在 `SubTaskCompleted` 的 `ReportToPenguinStats` 和 `ReportToYituliu` 一定表示上传成功并 responsed 200 OK

id 不好做，摆烂了，一般网也不至于差到下一句都打完了上一局还没传好（

**Comment by ChingCdesu** [comment]
开摆！

**Comment by bakashigure** [comment]
好好好
