### ISSUE TITLE
基建换班添加黑名单功能

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#1683]
### 说说你遇到的问题？

合成站使用芳汀需要把一些心情不满的人塞进宿舍，maa会识别到这些心情不满的人并让他们睡觉

### 有什么好的想法？

给基建换班功能加个黑名单让他不要给这些干员换班

**Comment by Minepig** [comment]
另一个类似的情况是让艾丽妮去专三一个干员，但是中途材料不足，由于艾丽妮的技能要求双方均不可离开训练室（然而专二以后艾丽妮的心情通常已经小于maa的心情阈值），故希望可以加入黑名单功能

**Comment by MistEO** [comment]
你可以在设置中选择 “不将已进驻的干员放入宿舍” （目前仅测试版有该功能）

另外啥叫 “maa会识别到这些心情不满的人并让他们睡觉” ？没理解，本来就在宿舍里现在仍然放到宿舍里不是没区别么）

**Comment by Minepig** [comment]
> 



> 你可以在设置中选择 “不将已进驻的干员放入宿舍” （目前仅测试版有该功能）
> 
> 另外啥叫 “maa会识别到这些心情不满的人并让他们睡觉” ？没理解，本来就在宿舍里现在仍然放到宿舍里不是没区别么）

这些人本来不进驻任何设施，他们的心情可能是3～4这种很低的数值，maa在处理宿舍的时候因为是按照心情排序，这些心情很低但不在任何设施里的人就会被揪出来放进宿舍。但这些人本不应该进宿舍，他们是配合芳汀的后勤技能使用的，仅在芳汀合成材料时进驻宿舍，合成完就离开宿舍

**Comment by MistEO** [comment]
那这个功能太小众了，并且收益非常低。识别干员（文字识别）是非常耗费性能的，我觉得不值得做

**Comment by ABA2396** [comment]
配合芳汀技能用的人太少了，低级材料有九色鹿瑕光，高级材料有年，能用到大量材料的地方大概也就专精了，但材料充足的情况下限制专精的不是合成材料而是专精时间，按18小时算都够年回满4次心情合成8个金材料了

**Comment by Minepig** [comment]
> 配合芳汀技能用的人太少了，低级材料有九色鹿瑕光，高级材料有年，能用到大量材料的地方大概也就专精了，但材料充足的情况下限制专精的不是合成材料而是专精时间，按18小时算都够年回满4次心情合成8个金材料了

并不是人人都有年的啊（捂脸），比如我就没有

**Comment by ABA2396** [comment]
> 并不是人人都有年的啊（捂脸），比如我就没有

那确实比较麻烦，可能只能手动换宿舍了，要自定义黑名单就算输入也是个麻烦事

**Comment by Minepig** [comment]
> 你可以在设置中选择 “不将已进驻的干员放入宿舍” （目前仅测试版有该功能）
> 
> 另外啥叫 “maa会识别到这些心情不满的人并让他们睡觉” ？没理解，本来就在宿舍里现在仍然放到宿舍里不是没区别么）

那么，希望“不将已进驻的干员放入宿舍”可以尽快加入正式版吧

**Comment by Minepig** [comment]
> 那这个功能太小众了，并且收益非常低。识别干员（文字识别）是非常耗费性能的，我觉得不值得做

是否可以退一步，据我对maa的理解，它应该是基于对基建技能图标的识别完成基建排班的，那么是否可以添加一个技能图标的黑名单？
