### ISSUE TITLE
肉鸽通关后无法跳过剧情，并开始下一轮

### ISSUE THREAD

**Issue by 1254355586** [MaaAssistantArknights/MaaAssistantArknights#1685]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽通关后无法跳过剧情，并开始下一轮

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9438360/asst.zip)

**Comment by MistEO** [comment]
哪个界面，麻烦多提供些信息

**Comment by 1254355586** [comment]
> 哪个界面，麻烦多提供些信息

因为当时没截图，并且挂机通关也不是很容易，大概通关就是这样的（视频链接：https://www.bilibili.com/video/BV1oB4y147XB），会有那个报幕，那个界面就卡住了
