### ISSUE TITLE
基建宿舍刷信赖时异格干员冲突

### ISSUE THREAD

**Issue by KumaTea** [MaaAssistantArknights/MaaAssistantArknights#1687]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

版本 [`v4.3.0-beta.6`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.3.0-beta.6)

心情已满时刷信赖是很棒的功能，点个赞！

今天发现降序选取干员时，若有异格干员信赖较高，由于异格干员共享信赖，会导致选取时互斥，最终少入住1人。

异格相关 issues: #1123 #1291 #1584 #1590

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9438573/asst.log)

### 截图

https://user-images.githubusercontent.com/36222458/187045840-1e0553b0-4cd9-47e4-a6ae-548028a9a38d.mp4

可直接跳至 01:10 处。

~录出来好卡但是应该能表明问题~

### 还有别的吗？

模拟器：蓝叠
系统：Windows 11

P.S. 感觉是一个无伤大雅的小bug，没必要修，但是既然发现了就发上来好了（）

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/187045966-045aa76c-2d1d-4c22-8ebb-57189d0249c5.png)
异格算同一个人

**Comment by ABA2396** [comment]
之前测试的时候只遇到了工作的水陈和陈，没想到宿舍蹭信赖还能遇到异格距离这么近（）

**Comment by ABA2396** [comment]
之前测试的时候只遇到了工作的水陈和陈，没想到宿舍蹭信赖还能遇到异格距离这么近（）

**Comment by MistEO** [comment]
该 bug 已由 YJ 修复 XD

![29~({EK0Q% @P~J)2W_IE%K](https://user-images.githubusercontent.com/18511905/197392857-2a9ac6bd-51cc-4a0b-bd37-2ab45fc3d460.png)
