### ISSUE TITLE
`Link Start` 和 `停止` 按钮合并后，需要再新增一个禁用的状态

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#1689]
### 说说你遇到的问题？

在以下场景会出问题

- 软件刚启动，还没加载好，这时候显示的是 `停止`，点击之后变成 `Link Start` 了，这时候再点会提示任务出错
- 在出现某些未知错误后，之前的 `停止` 是一直可用的，用户可以强制进行停止。现在合并了，是否存在某种情况下，UI 这边记录的状态是已停止，但实际 core 仍在运行，然后又没有 ”停止“ 可以点击？（我觉得一定是存在的，特别是正在连接的时候，应该稍微折腾下就能出

### 有什么好的想法？

- [x] 问题 1: 或许可以加个标志位，判断是否初始化完成，把按钮 disable 掉
- [ ] 问题 2: 我不知道.jpg

**Comment by ABA2396** [comment]
说起来我之前测log都是一直点停止然后来着）

**Comment by zzyyyl** [comment]
问题一我很早就想过了，但是不会）

**Comment by ABA2396** [comment]
就是怎么判断是在运行还是在初始化）

**Comment by zzyyyl** [comment]
别新增禁用状态了，干脆别显示好了（

**Comment by zzyyyl** [comment]
搞定一个了

**Comment by MistEO** [comment]
问题 2 我想了下 core 可以增加个接口 isRunning 之类的

**Comment by MistEO** [comment]
> 问题 2 我想了下 core 可以增加个接口 isRunning 之类的

确实可以加，现在的接口设计有个 AsstCreate （不传入回调的版本），但这个版本我完全不知道有没有跑完，加个 isRunning 还可以拿来轮循
