### ISSUE TITLE
建议增加多次关卡识别

### ISSUE THREAD

**Issue by SedroD** [MaaAssistantArknights/MaaAssistantArknights#1693]
### 说说你遇到的问题？

在使用自动肉鸽功能时，进入第一个关卡，选人编队后进入地图，地图还在载入的时候，程序就显示“关卡识别错误”，又过了5秒之后才进入关卡，此时程序不再进行任何操作直至关卡失败。（模拟器放在机械硬盘，其他功能运转良好，安卓版本6）
![FCN%{ 47T)DOG4I{ WEUGC](https://user-images.githubusercontent.com/112334922/187082255-8098701b-2aaa-4bcc-81e9-9bfa10120f8b.png)

### 有什么好的想法？

建议第一次出现“关卡识别错误”之后多Retry两三次，间隔时间5~10秒

**Comment by MistEO** [comment]
这里会 retry 50 次的，提个 bug 反馈发个日志看下吧
