### ISSUE TITLE
日服肉鸽模式，不上人

### ISSUE THREAD

**Issue by ZhangZE0829** [MaaAssistantArknights/MaaAssistantArknights#1696]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

日服肉鸽，选完人第一个关卡在费用够的情况下，不上人

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9441570/asst.log)

在12：27分左右

### 截图

![22](https://user-images.githubusercontent.com/112367136/187122571-e1de47fd-6d35-4497-a287-c193605fae12.png)
![11](https://user-images.githubusercontent.com/112367136/187123290-b873f12f-f88b-4f04-a1b3-8cd51b8d797f.png)

### 还有别的吗？

蓝叠，逍遥均试过

**Comment by zzyyyl** [comment]
Simular to #1693 

应该不是日服独有的问题

**Comment by ZhangZE0829** [comment]
> 

我同样的使用环境，官服是完全没问题，可以正常使用的

**Comment by zzyyyl** [comment]
关卡识别错误之后不会上人的，主要问题就是为啥关卡识别错误了（

**Comment by MistEO** [comment]
> Simular to #1693
> 
> 应该不是日服独有的问题

OCR 错了呗

**Comment by MistEO** [comment]
草，我怎么推 master 上了 orz

**Comment by MistEO** [comment]
好像还有点别的问题，日服的 OCR 资源文件似乎没加载成功

**Comment by MistEO** [comment]
从你的日志来看，似乎日服的 OCR 资源没有成功加载（因为识别出来的都还是中文），但是不知道为啥，我自己测试复现不了 orz。试试重新下载个完整包？
