### ISSUE TITLE
刷OF-8时脚本偶发闪退 [Remove labels]

### ISSUE THREAD

**Issue by KuiPer-LTW** [MaaAssistantArknights/MaaAssistantArknights#1700]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷OF-8完成杀敌任务时偶发闪退，不知道是什么原因，是脚本闪退，模拟器没有问题
还蛮频繁的，刷着刷着发现不动了，但任务栏的图标还在，鼠标一移过去图标就没了
猜测是因为OF-8没有掉落物一直识别错误导致的
又或者是设置刷20次以上会出bug，我也没刷过别的关20次以上，所以不知道是刷很多次的原因还是OF-8的原因

### 日志文件

没有留意时间，反正发生过好多次了
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9443948/asst.log)

**Comment by ABA2396** [comment]
> 是测试版吗？我这边显示已经是最新版本了

是测试版

**Comment by KuiPer-LTW** [comment]
> > 是测试版吗？我这边显示已经是最新版本了
> 
> 是测试版



> > 是测试版吗？我这边显示已经是最新版本了
> 
> 是测试版

未来能把使用无人机单独做成一个选项吗，我贸易站是巫恋+菲亚梅塔永动的必须要选择换贸易站干员才会用无人机

**Comment by horror-proton** [comment]
之后如果遇到了可以麻烦截个结算界面的图吗, 最好用模拟器自己的截图工具或者 adb

**Comment by zzyyyl** [comment]
你可以到 debug/ 文件夹下看看有没有图

**Comment by horror-proton** [comment]
> 你可以到 debug/ 文件夹下看看有没有图

报掉落识别失败也会有图的 (那估计会有一大堆图了)，但是它是识别到直接一半炸了, 造成崩溃的那张应该存不下来 (?

**Comment by KuiPer-LTW** [comment]
> 之后如果遇到麻烦截个屏幕截图吗，最好用自己的db截图或者工具

明天我会去测试一下，今天没看到回复，说个不知道是不是问题的问题：就是今天打不开脚本，一打开就崩溃，我就直接复制了稳定版的安装包更新了，然后就没事了，这是bug吗还是说更新了稳定版测试版就用不了了？

**Comment by KuiPer-LTW** [comment]
> > 你可以到 debug/ 文件夹下看看有没有图
> 
> 报掉落识别失败也会有图的 (那估计会有一大堆图了)，但是它是识别到直接一半炸了, 造成崩溃的那张应该存不下来 (?

没错，debug里就是有一堆OF-8的结算，不过每次崩溃的时候都是停留在结算界面的，这个意义不大吧

**Comment by ABA2396** [comment]
> 明天我会去测试一下，今天没看到回复，说个不知道是不是问题的问题：就是今天打不开脚本，一打开就崩溃

崩溃的问题已经在#1704 解决了

现在最新版本的稳定版比测试版还新，最新的稳定版已经4.3.0了
