### ISSUE TITLE
危机合约期间特殊关卡开放问题

### ISSUE THREAD

**Issue by GOLDENGLOWGLOW** [MaaAssistantArknights/MaaAssistantArknights#1703]
### 说说你遇到的问题？

危机合约期间红票龙门币等都是常驻开放的，可maa却不认为开放，希望可以优化一下

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/187341868-7b06b356-d796-4a6c-b29d-d6fe638ac218.png)

**Comment by ABA2396** [comment]
![9Q0%~HN`PNJF7GOC5FDZNKY](https://user-images.githubusercontent.com/99072975/187343080-2088a161-3e0c-4b05-9109-a173aa662f2a.jpg)
之前群里讨论过添加一个这样的选框让用户选择，因为现在的模式是根据星期判断开放状态，如果根据开放日期的话又得要求及时更新。但如果添加这样一个选框放在主界面可能会让用户误解功能，而放在设置里其实效果和活动期间关闭备选功能也没有区别吧？
