### ISSUE TITLE
v4.3.0-beta.6的自动升级可能导致崩溃

### ISSUE THREAD

**Issue by liyu-kun** [MaaAssistantArknights/MaaAssistantArknights#1704]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

前两天一直在使用4.3.0的测试版本，今天看更新到了4.3.0正式版，结果打开之后发现程序发生崩溃，经过多次测试之后怀疑是自动升级中的某些逻辑导致了升级过程出错。

经测试，v4.3.0-rc.1也有同样问题

### 日志文件

[asst.log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9449373/asst.log.zip)

**Comment by Mikosilk** [comment]
无限死循环崩溃，感觉更新文件有问题，删了更新文件还自动下载，接着崩溃

**Comment by ABA2396** [comment]
之前格式化的时候用了C#的快捷属性，调用Url的时候没有默认值就崩溃了，老版本更新可以在github把OTA下好放进文件夹，下次启动就可以了
