### ISSUE TITLE
无法使用自动肉鸽功能及重启MAA后设置无法保存

### ISSUE THREAD

**Issue by litteguys** [MaaAssistantArknights/MaaAssistantArknights#1706]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

1.每次启动MAA，上次关闭前保存的设置都无法保存，会恢复到默认设置
2.自动肉鸽功能默认是不勾选的，点击全选也是无法选择，只有手动选中才可选，进入游戏点击link start后其他功能一切正常，只要进行到自动肉鸽功能就会闪退

### 日志文件

在文件目录下搜索.log文件，没有发现日志文件

**Comment by ABA2396** [comment]
是不是放在了没有写入权限的文件夹，试试用管理员权限打开maa或者换个普通的文件夹路径

**Comment by ABA2396** [comment]
肉鸽不算是日常任务，普通用户打完了也不会继续打肉鸽，所以全选反选这些全都是排除肉鸽的

**Comment by litteguys** [comment]
关键在于点击肉鸽功能后，进到第一张图MAA就闪退了，而且MAA设置无法保存，重启后又要再次设置一遍




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月30日(星期二) 中午12:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 无法使用自动肉鸽功能及重启MAA后设置无法保存 (Issue #1706)





 
肉鸽不算是日常任务，普通用户打完了也不会继续打肉鸽，所以全选反选这些全都是排除肉鸽的

**Comment by ABA2396** [comment]
设置是保存在gui.json的，日志是在asst.log，没有权限修改文件夹里的文件怎么保存设置和日志呢，肉鸽闪退的问题得有日志才能分析。

**Comment by horror-proton** [comment]
你是不是把 MAA 放到 C 盘了, 如果在没有权限的文件夹, 是无法写入日志也无法保存设置的

**Comment by litteguys** [comment]
确实是放在c盘了，我刚刚去修改了权限，可以了，麻烦你了，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Horror ***@***.***&gt;; 
发送时间: 2022年8月30日(星期二) 中午12:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 无法使用自动肉鸽功能及重启MAA后设置无法保存 (Issue #1706)





 
你是不是把 MAA 放到 C 盘了, 如果在没有权限的文件夹, 是无法写入日志也无法保存设置的
