### ISSUE TITLE
究极博朗台碎石模式

### ISSUE THREAD

**Issue by filwaline** [MaaAssistantArknights/MaaAssistantArknights#1707]
### 说说你遇到的问题？

博朗台碎石模式很好，满足了抠门博士的基本需求，但是还能得到改进。

碎石后理智溢出，自动恢复停止。由于普通战斗在结算界面才扣除理智，所以战斗中理智恢复仍然是暂停的（博朗台搓手

### 有什么好的想法？

之前上线的剿灭秒结算能很好地利用起来，它瞬间结算，所以不会有战斗中停止理智恢复的问题。

如果博士启用了博朗台碎石模式，建议先跳转到剿灭界面，并且检查这位博朗台有没有剿灭券和合成玉配额，如果有，就在剿灭界面等待理智恢复并碎石，使用剿灭券，然后再回头刷理智。

一个可能的bug：博朗台在刷高理智消耗的关卡（>25）， 但是剩余理智仍然超过25，需要考虑处理方式。

**Comment by lhhxxxxx** [comment]
战斗中会回复理智
如果该关卡失败过且是135理智进入战斗，会先扣为134理智，并在战斗期间回复
考虑到这是最可能的情况，因此无需做处理

**Comment by zzyyyl** [comment]
> 考虑到这是最可能的情况，因此无需做处理

碎完石头是 135 理智应该是最不可能的情况吧（

不过我觉得还是没必要，毕竟这个 feature 看起来比较难以实现，而且收益不大（一周也就五次能这么整）

**Comment by filwaline** [comment]
> > 考虑到这是最可能的情况，因此无需做处理
> 
> 碎完石头是 135 理智应该是最不可能的情况吧（
> 
> 不过我觉得还是没必要，毕竟这个功能看起来比较复杂，而且收益不大（这个功能一周最多也就用五次）

确实收益不大，我也就提个乐（

**Comment by lhhxxxxx** [comment]
> > 考虑到这是最可能的情况，因此无需做处理
> 
> 碎完石头是 135 理智应该是最不可能的情况吧（
> 
> 不过我觉得还是没必要，毕竟这个功能看起来比较复杂，而且收益不大（这个功能一周最多也就用五次）

原来是碎石吗，我以为是自然回复溢出了
