### ISSUE TITLE
蓝叠模拟器国际版Hyper-v版本链接异常

### ISSUE THREAD

**Issue by kakokara** [MaaAssistantArknights/MaaAssistantArknights#1708]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

1、在gui.json文件中填入填入 bluestacks.conf 的完整路径后，一启动MAA就会自动消失。导致每次启动仍然需要自己手动填写adb连接地址，不知是我哪里操作有问题。
2、在肉鸽中，当选择默认编队是，AI在近卫会固定选择艾丽妮，但有更多更实用的却不选择，不知道是什么逻辑思路。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9449719/asst.log)

**Comment by SekiBetu** [comment]
雷电和mumu模拟器都支持hyper-V，可以试试
