### ISSUE TITLE
StartUp时若模拟器黑屏会出错

### ISSUE THREAD

**Issue by Hydrogina** [MaaAssistantArknights/MaaAssistantArknights#1711]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

开始唤醒时，启动明日方舟偶尔模拟器会卡住黑屏，此时StartUp会出错，会错误地完成任务：StartUp，然后跳过Fight和Recruit直接进行Infrast

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9452566/asst.log)

### 截图

![无标题](https://user-images.githubusercontent.com/46482682/187431185-1da9267e-63e2-4d50-b490-6454c78c5410.png)

### 还有别的吗？

蓝叠模拟器 b服 Maav4.3.0

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。

Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
