### ISSUE TITLE
肉鸽投币优化建议

### ISSUE THREAD

**Issue by dolkx** [MaaAssistantArknights/MaaAssistantArknights#1713]
### 说说你遇到的问题？

肉鸽投币完成后，到第二层再退出能多刷点蜡烛，尤其对练度低的号相比一直刷到第二层打一局再g效率要高。

### 有什么好的想法？

肉鸽第一层结束后如果不能投币或投币完成，后搬空商店到第二层再结算，可以在商店结束后加一个跳转。这样蜡烛硬币都能刷效率高点。

### 其他内容

No response

**Comment by ABA2396** [comment]
明天就是新肉鸽了，到时候看看新的咋样再说）

**Comment by ntgmc** [comment]
该功能已经修复，感谢您的反馈！
