### ISSUE TITLE
任务列表与基建设置中拖动标签目前需要点击开始后才保存，能否改为立即保存 [Remove labels]

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#1714]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

所有可以拖动调整顺序的标签列表，在调整过后似乎不会保存，下一次启动仍然是默认顺序

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9453157/asst.log)

**Comment by MistEO** [comment]
@Tastror 出来接锅！

**Comment by Tastror** [comment]
这个要点一下 linkstart 才会保存（

**Comment by ABA2396** [comment]
虽然是实时修改的，但是如果在后台还没保存好的时候立即关闭maa还是不会保存）
