### ISSUE TITLE
希望一键长草能有更高的自定义空间

### ISSUE THREAD

**Issue by maidangdang1** [MaaAssistantArknights/MaaAssistantArknights#1718]
### 说说你遇到的问题？

最近在刷芯片本，发现刷完之后剩了好多理智，想用剩下来的理智继续刷1-7

### 有什么好的想法？

![image](https://user-images.githubusercontent.com/46847241/187581540-7ba56dca-12e0-4b1e-bf9c-a84371488ad1.png)
一般的，希望左边的任务界面能设计成一个list，用户能向里面自由插入需要的任务，例如我可以在“刷理智”后面插入一个“刷理智1”，并将任务设置为刷1-7，这样就能实现多种类型的任务自由组合。

更广泛的，还可以实现对每个任务进行重命名，这样用户就能直接看出这个任务是刷哪个材料

好像一口气提了好多困难的需求，求考虑😭

**Comment by ABA2396** [comment]
wpf可能比较难做，但是新ui已经有增减任务的功能了
![image](https://user-images.githubusercontent.com/99072975/187596092-1dd00c43-095f-4d5d-b90b-2df46d473000.png)
如果想自己折腾下可以看看[MaaAsstElectronUI](https://github.com/MaaAssistantArknights/MaaAsstElectronUI)
不想折腾就等新ui出来吧

**Comment by maidangdang1** [comment]
😲 新ui要咋用啊 我下了release里面的那个包，打开之后提示我maa core未安装
还是说新ui要编译之类的🥲

**Comment by ABA2396** [comment]
去设置里点版本号，会告诉你要下载什么

**Comment by maidangdang1** [comment]
好的好的 我研究一下 感谢🙏
