### ISSUE TITLE
必须第二次启动MAA才能截图识别成功的bug？

### ISSUE THREAD

**Issue by CorenoneSong** [MaaAssistantArknights/MaaAssistantArknights#1719]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

问题：首次启动MAA后，link Start，到开始任务：start up，就一直停在start界面，提示截图失败
尝试：重新连接、更改模拟器分辨率等。只能重启一下MAA才能正常运行
8.30更新前没有这个bug，只能重启一次才可以了吗

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9458411/asst.log)

### 截图

![屏幕截图(365)](https://user-images.githubusercontent.com/65541053/187591655-4b16f830-3278-460d-a68e-8d9bbec99ce5.png)
![屏幕截图(366)](https://user-images.githubusercontent.com/65541053/187591663-7d1f705e-440b-468c-b488-fbe02d7ffa94.png)

### 还有别的吗？

雷电，win10,

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/187594496-369e9b63-ac32-4fba-8a42-824d05baf099.png)
雷电给的图有问题，你可以自己试试日志里的那条adb命令看看能不能截到图

**Comment by MistEO** [comment]
别用雷电（

**Comment by zoe4477** [comment]
我用雷电也这样。。

**Comment by CorenoneSong** [comment]
这个是强制更新吗？我想用v4.2.3的版本，4.2.3没问题

**Comment by zzyyyl** [comment]
你的雷电模拟器什么版本啊，我一直用的雷电也没问题啊（

**Comment by zzyyyl** [comment]
> 这个是强制更新吗？我想用v4.2.3的版本，4.2.3没问题

现在确实是强制更新。

**Comment by zzyyyl** [comment]
![image](https://user-images.githubusercontent.com/74587068/187862478-aa0f8991-34b8-4b21-a530-241ca82b5d08.png)
感觉是解析有问题，不是雷电的问题
这边 data 的大小看上去是正常的，但是解析出来说 image is empty

@MistEO @ABA2396

**Comment by CorenoneSong** [comment]
> 你的雷电模拟器什么版本啊，我一直用的雷电也没问题啊（ ![image](https://user-images.githubusercontent.com/74587068/187859866-ed7932e5-5131-437d-948a-57380275a357.png)

我是4.0.64(64)，我更新试试

**Comment by zoe4477** [comment]
我用雷电也这样，MAA4.3之前的版本都正常的，更新以后出的问题。希望可以修复一下，虽然雷电跟MAA相性不佳，但是感觉蓝叠和夜神还是不如雷电好用。

**Comment by zzyyyl** [comment]
看日志好像雷电返回的行尾一会儿是 CRLF 一会儿是 LF（？
也许得改一下 Controller 的 cvt lf 逻辑
马上提个 pr
