### ISSUE TITLE
关于作战失败后无法识别的bug（？）以及制造站排班的问题

### ISSUE THREAD

**Issue by ShiuAsa** [MaaAssistantArknights/MaaAssistantArknights#172]
第一点是我之前做孑哥模组时打的作战不稳定，偶尔会失败，失败后所有操作全部显示出错。
第二点是经验制造站在有稀音、红云、牛牛的情况下，它选择了稀音、红云和小刻这一队产量低的，可能是优先级不太对？
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7964330/asst.log)

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/151675073-b588cdf2-6b46-48cd-962c-f49f8e5b5a49.png)

看了下计算出的最优解是牛牛呀_(:з」∠)_是点击错了么？

**Comment by MistEO** [comment]
代理失败的情况，之前专门做了。后来 yj 把代理失败之后的界面改了，我还没更新_(:з」∠)_

**Comment by ShiuAsa** [comment]
这个最优解是在我手动换成牛牛后才算出来的，在这之前是加了小刻

**Comment by MistEO** [comment]
基建已经改了很多了，不知道还有没有这个问题，再有的话重新提一个吧_(:з」∠)_
