### ISSUE TITLE
图形化界面一打开就无响应，进而崩溃

### ISSUE THREAD

**Issue by lxyddice** [MaaAssistantArknights/MaaAssistantArknights#1722]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

一打开就无响应，进而崩溃
是否以管理员权限运行都无法打开

### 日志文件

崩溃后未生成该文件

### 截图

![Snipaste_2022-09-01_07-56-30](https://user-images.githubusercontent.com/95132858/187805087-257e5289-1af1-46bd-872d-8f8bc2576bef.png)
![Snipaste_2022-09-01_07-57-04](https://user-images.githubusercontent.com/95132858/187805089-6c828044-9af0-4f87-ae39-80b6fed6e539.png)

**Comment by MistEO** [comment]
常见问题中的选项都尝试过了？
