### ISSUE TITLE
前端数字文本框（如吃理智药）填写时未正确进行格式检查

### ISSUE THREAD

**Issue by panda361** [MaaAssistantArknights/MaaAssistantArknights#1723]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在填写"aaa"之类的非数字字符串时，会正常提示格式错误（虽然UI有点问题，可能跟HiDPI有关？）
然而在填写如"1.1.1.1", "1.1.", "11a"之类的数字开头的不规范字符串时，理应提示格式错误，实际gui.json正常记录了字符串并且Parse后传入了

### 日志文件

[logandguijson.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9466695/logandguijson.zip)

### 截图

![image](https://user-images.githubusercontent.com/35888512/187827978-5acb762d-b63b-45b5-939f-a8e3062dc57a.png)
![image](https://user-images.githubusercontent.com/35888512/187828002-9c3574f3-610f-4788-8189-b8322b5df18f.png)

### 还有别的吗？

也许可以用这种方式来验证输入？
https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.validationrule.validatesontargetupdated?view=windowsdesktop-6.0

**Comment by zzyyyl** [comment]
欢迎 PR

**Comment by MistEO** [comment]
酒吧不准点炒饭！~~除非顾客愿意自己炒~~

**Comment by ABA2396** [comment]
a8f4e684a7e38bc9b00af0351c78152d06c18c7f fixed

**Comment by panda361** [comment]
Thanks for all contributors!
