### ISSUE TITLE
肉鸽选人主动放弃，然后在确认放弃界面上不再有动作

### ISSUE THREAD

**Issue by shxhmy** [MaaAssistantArknights/MaaAssistantArknights#1724]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

开始肉鸽后就不断放弃招募
先直接放弃近卫（我近卫干员齐全）
辅助招了
医疗也放弃，然后停止响应

有时候是开始招了近卫
然后放弃辅助，停止响应

asst.log文件大小飞速增长

还有，分辨率1920 1080
没有缩放模拟器
log是清掉了一次，为了测试重新创建了个log，log应该记录的是招了近卫，然后进入辅助页面选择放弃辅助（这点就很奇怪，界面上有至少两个0希望选择），在截图界面上maa不再有任何响应，但是log飞速变大，此时人工点x，则maa又开始选梓兰，正常继续
此问题会无限发生，自动肉鸽情况下，靠手动过了放弃界面，然后就又会在下一次选人中失去响应

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9466950/asst.zip)

### 截图

![47a28985800cc7af11b12ea4cceb783](https://user-images.githubusercontent.com/21029794/187834053-51137089-fad1-45fa-b92b-bba7f491a296.png)
![c2de10ee6a7108cc0e1d1a819ee54f3](https://user-images.githubusercontent.com/21029794/187834069-16429c8b-e2f9-4b43-9345-7ef5f4add459.png)

### 还有别的吗？

夜神模拟器 7.0.3.3030
maa 430

**Comment by shxhmy** [comment]
还有，分辨率1920 1080
没有缩放模拟器
log是清掉了一次，为了测试重新创建了个log，log应该记录的是招了近卫，然后进入辅助页面选择放弃辅助（这点就很奇怪，界面上有至少两个0希望选择），在截图界面上maa不再有任何响应，但是log飞速变大，此时人工点x，则maa又开始选梓兰，正常继续
此问题会无限发生，自动肉鸽情况下，靠手动过了放弃界面，然后就又会在下一次选人中失去响应

**Comment by et2012** [comment]
类似 #1655
同样是夜神模拟器，先确认是不是 DPI 的问题。

11:51:56.037 选择候选干员：艾丽妮
11:51:56.954 截图大小 36230
11:52:04.099 识别界面时出错

11:58:02.044 第二页干员识别结果：莱恩哈特, 星源, 特米米, 至简, 炎狱炎熔, 蜜蜡, 洛洛, 蚀清
11:58:05.601 截图大小 36230
11:58:05.637 识别第三页干员时失败
11:58:10.291 决定选择：薄绿

后面都是因为截图导致识别失败：
12:34:49.686
12:38:43.519
12:46:40.162
12:46:54.738
12:48:04.562
12:48:14.882

**Comment by shxhmy** [comment]
> 

我对比了下MuMu，确实没这个问题。夜神的dpi是240，MuMu的是360。这个差距这么大么

**Comment by shxhmy** [comment]
我觉得可以关闭了。。因为调用比较好不得不用夜神，但是夜神必须加参数才能改dpi
比如
"C:\Program Files\Nox\bin\Nox.exe" -dpi:360

**Comment by horror-proton** [comment]
蛤, 这和 DPI 有啥关系

**Comment by MistEO** [comment]
> 蛤, 这和 DPI 有啥关系

看意思好像是说夜神在默认 DPI 下就会有问题

**Comment by et2012** [comment]
> 蛤, 这和 DPI 有啥关系

因为 #1655 的提出者说改了清晰度解决了问题。如果不是 DPI 的问题，那就要继续找截图的问题了。

**Comment by shxhmy** [comment]
> 

我今天用360dpi跑了一下午，没问题。
最后是高台可以放地面的某关卡住了（奶妈卡怪无人输出，没办法）

**Comment by shxhmy** [comment]
> > 蛤, 这和 DPI 有啥关系
> 
> 因为 #1655 的提出者说改了清晰度解决了问题。如果不是 DPI 的问题，那就要继续找截图的问题了。

今天实验还是有问题，360dpi还是卡在 确认放弃招募 这个界面上。
这次是本来就应该放弃招募，因为界面上没有可选的人
卡了小两个小时的样子，log都40mb了，我不得不删了，有个短log  大概2mb。最后是我手动跳过的

**Comment by shxhmy** [comment]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9481866/asst.zip)
@et2012

**Comment by et2012** [comment]
大部分还是同样的问题，截图大小是 36230，这个大小不正常。
不过 11:54:55.268 的截图大小是 655267，也识别失败了，找不到干员的希望图标，这个可能是晋升界面但无可选干员。
那么，就不是 DPI 问题了。需要安装你用的夜神版本测试一下看到底是什么问题。

**Comment by shxhmy** [comment]
> 大部分还是同样的问题，截图大小是 36230，这个大小不正常。 不过 11:54:55.268 的截图大小是 655267，也识别失败了，找不到干员的希望图标，这个可能是晋升界面但无可选干员。 那么，就不是 DPI 问题了。如果你的模拟器没有其他用途，可以试试把分辨率调整为 1280x720 看看有没有改善。 我稍后测试一下看到底是什么问题。

我现在没在跑。截图大小一会大一会小也挺怪啊，感觉夜神有问题似的。设置里用的是opengl，换directx试试
我今天还遇到了我选中了关卡（是RI-6，刷石头的本）然后又退回去执行了上次作战（红票本）。没有日志了，我看看能不能复现，也许只是我记错了
用的夜神版本 7.0.3.5009 是安卓9版本，前几天应用内更新过应该是最新的

**Comment by shxhmy** [comment]
> 大部分还是同样的问题，截图大小是 36230，这个大小不正常。 不过 11:54:55.268 的截图大小是 655267，也识别失败了，找不到干员的希望图标，这个可能是晋升界面但无可选干员。 那么，就不是 DPI 问题了。如果你的模拟器没有其他用途，可以试试把分辨率调整为 1280x720 看看有没有改善。 我稍后测试一下看到底是什么问题。

还有就是，这个截图大小是怎么计算的，正常655267，异常才出来36230，好像差距过大了吧，夜神的输出有问题吧

**Comment by et2012** [comment]
> > 大部分还是同样的问题，截图大小是 36230，这个大小不正常。 不过 11:54:55.268 的截图大小是 655267，也识别失败了，找不到干员的希望图标，这个可能是晋升界面但无可选干员。 那么，就不是 DPI 问题了。如果你的模拟器没有其他用途，可以试试把分辨率调整为 1280x720 看看有没有改善。 我稍后测试一下看到底是什么问题。
> 
> 还有就是，这个截图大小是怎么计算的，正常655267，异常才出来36230，好像差距过大了吧，夜神的输出有问题吧

正常应该600K左右，36230 明显不正常。

我从 16:34 测试到 18:04 都无法重现你的问题。

夜神 7.0.3.3
大部分是默认设置，只改了性能设置：2核 3072MB 内存
显卡渲染模式：OpenGL
分辨率：1920 x 1080 
不过我会缩放到四分之一大小，因为一般都是双开两个模拟器，还要开一堆其他软件

**Comment by horror-proton** [comment]
~~如果截到黑屏啥的, 体积可能确实会很小?~~

**Comment by MistEO** [comment]
v4.4.0-beta.2 修了一个截图问题，试试看
