### ISSUE TITLE
连接失败，无法连接模拟器

### ISSUE THREAD

**Issue by Cycsics** [MaaAssistantArknights/MaaAssistantArknights#1725]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

开了hype-v，打开ff14这类游戏之后会无法连接模拟器，不开的话能用。
然后可能是因为更新了win11
现在无论有没有打开ff14都无法连接模拟器
提示连接失败，并且重启和重新下载模拟器以及MAA都无效。
已根据hype-v的支持修改gui.json，这是修改以后出现的问题。

### 日志文件

![image](https://user-images.githubusercontent.com/22937494/187837147-3327a902-c71f-4a6d-94e7-d5f7595ce52f.png)
![image](https://user-images.githubusercontent.com/22937494/187837172-a7e5116d-beb6-4ffc-90d6-4389ce88d6e0.png)

### 截图

![image](https://user-images.githubusercontent.com/22937494/187836804-435e1671-1f9c-43fa-9d61-99704ac24215.png)

### 还有别的吗？

模拟器：蓝叠国际版
系统：win11 64位
配置：12900k/3080/64G

**Comment by HerrMura** [comment]
去模拟器设置里面看一下ADB的连接地址，MAA的连接设置里面自动填写的跟这个不一致，手动改一下MAA里的，跟模拟器设置里面一致就可以了
<img width="573" alt="1" src="https://user-images.githubusercontent.com/106559052/187905466-4be9eced-814c-4cce-b51a-5641eb9304ed.png">
<img width="600" alt="2" src="https://user-images.githubusercontent.com/106559052/187905473-f71fd943-a690-4778-9f1f-4cdce52c36da.png">

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/187917687-ff4f7df3-ca34-42bd-8c5f-5014f54b3b6e.png) 呢？

**Comment by Cycsics** [comment]
> 

咦我上传了怎么变成截图了

**Comment by Cycsics** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9469894/asst.log)

**Comment by latiasatoshi** [comment]
夜神7在哪里啊
![image](https://user-images.githubusercontent.com/31753274/188121834-a8a27d6c-cd71-42ef-93f6-ebad0ac60ceb.png)


> 去模拟器设置里面看一下ADB的连接地址，MAA的连接设置里面自动填写的跟这个不一致，手动改一下MAA里的，跟模拟器设置里面一致就可以了 <img alt="1" width="573" src="https://user-images.githubusercontent.com/106559052/187905466-4be9eced-814c-4cce-b51a-5641eb9304ed.png"> <img alt="2" width="600" src="https://user-images.githubusercontent.com/106559052/187905473-f71fd943-a690-4778-9f1f-4cdce52c36da.png">

**Comment by Cycsics** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9481707/asst.log)
![image](https://user-images.githubusercontent.com/22937494/188253714-6d2fccd2-8d4e-4218-9daa-ff09c5f87f33.png)
经过确认后，是打开加速器的时候会导致连接失败

**Comment by MistEO** [comment]
之前也有朋友反馈过开加速器会有问题，这些傻逼加速器动不动喜欢开全局代理，靠 maa 估计解决不了，只能重启了，我去写到常见说明文档里去

**Comment by Cycsics** [comment]
好嘞我再试试uu加速器会不会这样，因为在国外我玩国内游戏只能开加速器，给你造成不便了十分抱歉
