### ISSUE TITLE
与模拟器连接失败

### ISSUE THREAD

**Issue by HerrMura** [MaaAssistantArknights/MaaAssistantArknights#1729]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天开启蓝叠模拟器时提示需要打开HyperV和虚拟机等功能，否则无法启动模拟器，按照提示操作以后成功进入模拟器。
但是MAA提示无法连接模拟器了。
尝试了重启电脑，重装蓝叠模拟器国际版，重装MAA，关闭HyperV与虚拟机后再开启，仍然无法解决该问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9468558/asst.log)

### 截图

<img width="600" alt="微信截图_20220901112042" src="https://user-images.githubusercontent.com/106559052/187879541-0d67e4b8-9ae5-4ac5-9eb6-2aeebf609ec1.png">

### 还有别的吗？

Win11专业版
处理器	AMD Ryzen 9 5900HS with Radeon Graphics           3.30 GHz
机带 RAM	24.0 GB 

p.s 今天win11更新了一次系统补丁，但不知道是否相关，因为昨天没有用过模拟器。上周使用MAA一切正常

**Comment by HerrMura** [comment]
> 

尝试了，也尝试了完全删除MAA再重新下载，也还是连接失败

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/187904018-87a730f0-18a5-40ed-8edf-7b0f0854f231.png)
去模拟器的设置里看看端口号是啥，maa试了几个都没连上

**Comment by HerrMura** [comment]
> ![image](https://user-images.githubusercontent.com/99072975/187904018-87a730f0-18a5-40ed-8edf-7b0f0854f231.png) 去模拟器的设置里看看端口号是啥，maa试了几个都没连上

感谢！解决了，MAA自动填写的一直是127.0.0.1:5555，但是模拟器里面变更了，把MAA里的手动改成一致就好了。
<img width="954" alt="1" src="https://user-images.githubusercontent.com/106559052/187905048-0459a969-9006-428c-a37c-ec7ef3e937cb.png">
<img width="600" alt="2" src="https://user-images.githubusercontent.com/106559052/187905057-c5a28880-795c-403d-ae30-33f3ea90d6cf.png">

**Comment by HerrMura** [comment]
问题应该出在MAA连接设置里面自动填写的连接地址与蓝叠模拟器的不一致，可能是win11更新以后导致地址被覆盖，重开HyperV以后模拟器自动更换了端口号

**Comment by ABA2396** [comment]
HyperV的话建议参考[模拟器支持](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.md),蓝叠 Hyper-V 的端口号是会变的
