### ISSUE TITLE
关于艾丽妮训练结束后会被放回宿舍的问题

### ISSUE THREAD

**Issue by Guaqin** [MaaAssistantArknights/MaaAssistantArknights#1732]
### 说说你遇到的问题？

艾丽妮在在训练室协助训练结束后，会被MAA放进宿舍导致艾丽妮技能失效，大大的降低了训练效率

### 有什么好的想法？

建议不要把训练室的干员放回宿舍，训练干员使用频率低，即使没有放回宿舍也不会造成多大的影响

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/187995907-4941450e-d7ca-491e-aac7-569911dd9f67.png)
