### ISSUE TITLE
Identify error (JP ドロップ認識エラー)

### ISSUE THREAD

**Issue by wallsman** [MaaAssistantArknights/MaaAssistantArknights#1733]
### The problems you have encountered?

Always error LS-5.
No particular problems are found with other operations.

[Emulator]Bluestack
[Server]JP-Yoster
![image](https://user-images.githubusercontent.com/63186641/188013401-2840840c-28df-4447-bfc1-020a1575a50a.png)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9473451/asst.log)

**Comment by MistEO** [comment]
Drops Recognition is NOT supported in overseas clients at this time, as the layout of drops screen in overseas clients is different from the CN client. Please wait a few months for the game to be updated with Chapter 10, when the drop screen will be the same as the CN client.
