### ISSUE TITLE
【逻辑】剿灭作战功能

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#1734]
### 说说你遇到的问题？

剿灭作战放在了挂机列表里，虽然乍一看逻辑没问题，就是战斗，也是刷理智

但是剿灭作战每个星期只用动到一次或两次，放在作战选择里我感觉不够合理，相比于其他的太少了

### 有什么好的想法？

直接把剿灭作战作为一个日常任务放在左边的侧栏里，这样打完剿灭还可以自己去打别的指定关卡

**Comment by ntgmc** [comment]
该功能暂时不会实现，感谢反馈。

This function will not be realized temporarily. Thank you for your feedback.
