### ISSUE TITLE
[建议]自动任务列表与刷指定关卡

### ISSUE THREAD

**Issue by nailao946** [MaaAssistantArknights/MaaAssistantArknights#1736]
可以自己选择关卡 x-x 和 刷的次数 n 然后添加到任务表，可以添加多个关卡 
比如：1-1 3次 1-2 3次
开始任务时候 会刷1-1 3次再刷 1-2三次 这样子
指定材料也可以添加到任务
xxx材料 n次
xxx材料 n次

望采纳

**Comment by zzyyyl** [comment]
这个估计不会做了 (?)，不过也许你可以试试[新 UI](https://github.com/MaaAssistantArknights/MaaAsstElectronUI/releases)，我记得有类似的功能。

还有，下次提 issue 的时候记得用模板（

**Comment by ntgmc** [comment]
#849
