### ISSUE TITLE
基建套组成员在宿舍的情况下即使满体力也无法被选取

### ISSUE THREAD

**Issue by zynxqfj1** [MaaAssistantArknights/MaaAssistantArknights#1738]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

贸易站和制造站默认分类方式为“工作状态”，当贸易站套组的成员处于宿舍时，maa就无法识别到该干员，原本以为能在“技能”分类下选择干员，但是那样会导致重复选取，所以姑且提一下（虽然有可能你们一早就知道这个问题）

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9474816/asst.zip)

**Comment by Minepig** [comment]
正常情况下心情回满以后就可以选取了，除非筛选的时候打开了“未进驻”，而“未进驻”开关应该是默认关闭且不保存的，或者你的套组里面有人没有贸易站技能，我想这应该不可能

**Comment by MistEO** [comment]
~~让打工人心情回满再上班吧~~

**Comment by MistEO** [comment]
有需要可以试试自定义基建
