### ISSUE TITLE
基建排班效率计算的问题

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#1740]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我观察到maa会为了最大化单设施收益把一些具有负面效果的干员放入基建中，例如泡普卡和石棉入驻制造站，或者孑入驻贸易站，这会导致仓库容量或订单容量下降，以致于下一次上线收菜的时候制造站或贸易站饱和，造成效率损失。（我甚至遇到过maa把泡普卡和石棉塞进同一个制造站的，结果上线的时候发现早就爆仓了）
建议在计算设施收益的时候把仓库容量和订单容量纳入考虑，可以在设置界面中提供一个设置项，让用户填写自己上线的平均时间间隔，供maa计算设施效率用

### 日志文件

虽然觉得这个bug应该不需要log但是还是拖上来
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9474937/asst.log)

**Comment by Minepig** [comment]
此外243基建清流不在制造站我不太理解

**Comment by cenfusheng** [comment]
（挖坟）现在可以通过自定义基建排班来实现按时间规划和跨房间联动了。
MAA目前默认的基建算法是局部最优，暂时没有改进的打算，自定义功能因此诞生。
