### ISSUE TITLE
每次启动关卡选择会重置为“活动已结束”

### ISSUE THREAD

**Issue by ruined404cjy** [MaaAssistantArknights/MaaAssistantArknights#1743]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

每次启动MMA时主页的关卡选择会被重置为“活动已结束”。
具体地，前次选择关卡为1-7、或者手动在游戏内选择1-7并选择“当前/上次”并开始连接、完成任务后，下次启动MMA时主页的关卡选择会被重置为“活动已结束”。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9480353/asst.log)
[2022-09-03 02:37:44.898]左右开始反复尝试修改关卡选择并退出重启MMA。

### 截图

![image](https://user-images.githubusercontent.com/43736600/188217423-6498dc54-7897-410e-9d3b-09b05a4288f4.png)

![image](https://user-images.githubusercontent.com/43736600/188217403-87a6c3ff-2ab7-47e3-984a-e81f91517614.png)

### 还有别的吗？

MMA：v4.3.0
模拟器：BlueStacks
OS：Windows 11

**Comment by ABA2396** [comment]
f85e0db4290b2b2ef3b4c629d257e3478a227f7c fixed

**Comment by MistEO** [comment]
v4.3.1 fixed
