### ISSUE TITLE
新安装明日方舟时，肉鸽出现“请选择难度”的问题

### ISSUE THREAD

**Issue by MarsCloud** [MaaAssistantArknights/MaaAssistantArknights#1746]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在肉鸽开始界面时，如果没有选择肉鸽难度，则会一直提示请选择难度，从而在开始界面一直提示请选择难度
这个问题只在新下载明日方舟的设备上可以复现（因为老设备会记住你上次战斗的难度）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9481758/asst.log)
2022-09-03 9:56:41 开始刷肉鸽

### 截图

![image](https://user-images.githubusercontent.com/43104628/188254719-81927745-5e6c-4fb2-adff-879fdf90c178.png)
如果没有选择难度，那么将会在游戏内显示“请选择难度”的提示
![image](https://user-images.githubusercontent.com/43104628/188254789-4bc24adf-ed89-4864-b714-0d865283919c.png)

**Comment by zhongfly** [comment]
预期行为，你自己选好难度就可以了
