### ISSUE TITLE
上报企鹅物流失败

### ISSUE THREAD

**Issue by Snow-dash** [MaaAssistantArknights/MaaAssistantArknights#1747]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

正常使用刷理智功能，选择1-7后执行。15:46:22上报失败，日志已给出。

在resource/config.json的[options][penguinReport][cmdFormat]的键值最后附加“ --ssl-no-revoke”可解决问题。（[extra]字符后）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9482186/asst.log)

[2022-09-03 15:46:22.499][INF][Px2894][Tx4dc4] response:
 curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - 吊销功能无法检查证书是否吊销。

PS:该报错使用GB2312编码。

### 还有别的吗？

人在国内，使用蓝叠国际版，代理使用clash，有系统代理。但没有在maa中设置任何代理端口。

关闭代理仍然会出现此问题。

如果将上报api改为 [penguin-stats.io](https://penguin-stats.io) 则会直接报超时，而不是汇报证书问题，所以我仍然使用的是企鹅物流国内api，并认为maa没有使用代理。

**Comment by zzyyyl** [comment]
我试了一下，开着代理的时候 `--ssl-no-revoke` 也不行（

![image](https://user-images.githubusercontent.com/74587068/188263743-a0bf3efe-53f7-484d-83aa-4a4d298f6cd3.png)

**Comment by Snow-dash** [comment]
> 

我这里管理员运行cmd并运行`curl https://www.baidu.com --ssl-no-revoke` 是正常连接的。。但不加取消参数仍然不能连接。

**Comment by zzyyyl** [comment]
“不能连接” 是**概率发生**还是**一定发生**（？

如果是概率发生加几次重试就完事了，我上面的 comment 里提到的现象是**概率发生**的

**Comment by Snow-dash** [comment]
> “不能连接” 是**概率发生**还是**一定发生**（？
> 
> 如果是概率发生加几次重试就完事了，我上面的 comment 里提到的现象是**概率发生**的

我实验了重启电脑后不开代理，打开代理，全局代理；curl使用-x参数，无-x参数，等等情况。

只有访问`http://www.baidu.com`或加上`--ssl-no-revoke`参数的情况能够成功。

其他例如访问`https://www.baidu.com`且不加ssl-no-revoke**一定**无法连接，报`吊销功能无法检查证书是否吊销。`

感觉越整越像我本地的某种证书问题，可我没折腾过这些，网上也没有搜索到相关问题。

**Comment by wanghr2000** [comment]
同上报失败，加`--ssl-no-revoke`后正常上报

`[2022-10-23 09:31:57.875][TRC][Px3924][Txd44] retrying... | why: unsupported protocol version`curl:` status_code: 0
[2022-10-23 09:31:57.875][INF][Px3924][Txd44] request:
curl -H "Content-Type: application/json" -s -S -m 10 -i -d "{\"server\":\"CN\",\"source\":\"MeoAssistant\",\"stageId\":\"main_01-07\",\"drops\":[{\"itemId\":\"30012\",\"quantity\":1,\"dropType\":\"NORMAL_DROP\"},{\"itemId\":\"2001\",\"quantity\":1,\"dropType\":\"EXTRA_DROP\"}],\"version\":\"v4.6.5-beta.1\"}" "https://penguin-stats.io/PenguinStats/api/v2/report" -H "authorization: PenguinID *******" -H "X-Penguin-Idempotency-Key: MAA34000b29ac4bbb27d9bc99e6b8c"
[2022-10-23 09:31:58.326][INF][Px3924][Txd44] response:
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - ���������޷����֤���Ƿ������
`
