### ISSUE TITLE
蓝叠模拟器国际版 Hyper-V 版本设置

### ISSUE THREAD

**Issue by wonder041** [MaaAssistantArknights/MaaAssistantArknights#1749]
### 说说你遇到的问题？

MAA连接蓝叠模拟器国际版 Hyper-V 版本需要修改json文件实现, 需要用户找到设置文件并新建字段.

### 有什么好的想法？

希望可以将连接Hyper-V版本的设置整个到软件界面中.

**Comment by MistEO** [comment]
这种设置一次就再也不会动的设置，而且是小众需求的，应该不会做到界面上
