### ISSUE TITLE
Cant Doing basement(JP client)

### ISSUE THREAD

**Issue by wallsman** [MaaAssistantArknights/MaaAssistantArknights#1750]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I spent at least 5 minutes thinking and preparing before raising the issue.
- [X] I have read the FAQ and the User Manual in the documentation and believe that this is most likely a bug and not designed to be so.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Maybe Base behavior is buggy.
-Dont pick up Finished product.
-It is also not placed in a location that was intentionally left vacant(Mfg).
-No use Drone(Setting EXP)
-The reception room is functioning, but the Life thresholds in the setting are not working.
-Control room Triple check, but nothing doing.

![image](https://user-images.githubusercontent.com/63186641/188274621-49d0c031-6068-443f-a6be-3316efdcaf01.png)
![image](https://user-images.githubusercontent.com/63186641/188274631-986a7074-4cca-4f08-b494-815045b2e4dd.png)

### Log files
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9482807/asst.log)

### Screenshots

![image](https://user-images.githubusercontent.com/63186641/188274697-a74d5f83-319a-4b92-89e1-4e995e1fabe1.png)
![image](https://user-images.githubusercontent.com/63186641/188274824-044c1433-f0af-4721-bdf2-56f8e16fcfeb.png)
![image](https://user-images.githubusercontent.com/63186641/188275540-913059bb-26be-4359-a5e9-f8e02f0466fe.png)

### Anthing else?

[Emulator]Bluestack
[Server]JP-Yoster

**Comment by MistEO** [comment]
The basement function is also not supported for JP clients, please refer [here](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/README_ja-JP.md#%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%AB%E5%BF%9C%E3%81%98%E3%81%A6%E3%82%B5%E3%83%9D%E3%83%BC%E3%83%88%E3%81%95%E3%82%8C%E3%82%8B%E6%A9%9F%E8%83%BD).

**Comment by wallsman** [comment]
Ah ok, i fail read document thx.
