### ISSUE TITLE
希望自动公招可以留几张白票

### ISSUE THREAD

**Issue by atkdefender** [MaaAssistantArknights/MaaAssistantArknights#1751]
### 说说你遇到的问题？

避免有出好词条，莫得白票用的情形
或者公招大更新时，没白票来把好词条收掉

**Comment by MistEO** [comment]
> 倒是希望有个自动使用联络次数而不直接公招的选项，毕竟早晚四次公招白票不够用，但是次数还是在刷

你把自动确认三星的勾去掉就好了啊
