### ISSUE TITLE
v4.3.1一键长草刷理智选择异铁时程序会直接闪退 [Remove labels]

### ISSUE THREAD

**Issue by Exiaaaaa** [MaaAssistantArknights/MaaAssistantArknights#1756]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

指定材料刷理智时，如果选择异铁，程序将会闪退，选择其他材料不会出现这个问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9483825/asst.log)

### 还有别的吗？

使用的蓝叠模拟器国内版

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/c91f2c3ad7fe3329a3301eefb2c4aea333f66096 @lhhxxxxx 为啥把判空删了啊

**Comment by lhhxxxxx** [comment]
> https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/c91f2c3ad7fe3329a3301eefb2c4aea333f66096 @lhhxxxxx 为啥把判空删了啊

仔细一看发现，好像是我当时看不出来这玩意有什么用，以为是存json放在外面才需要特殊处理，所以测了一下没出问题就删了
