### ISSUE TITLE
雷电模拟器下自动肉鸽问题

### ISSUE THREAD

**Issue by lbpdfs** [MaaAssistantArknights/MaaAssistantArknights#1759]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

1、自动肉鸽中，高概率发生截图失败，一般出现在运行20分钟左右。主线图未见发生此问题，至少已有超1.5小时挂机记录，而自动肉鸽目前没有成功持续超过30分钟不触发该问题。该问题在4.3.0、4.3.1、4.4.0-beta1版本均有发生，4.4.0-beta1略有改善并有概率间歇性在截图失败过程中进行部分操作。观察日志后有尝试手动重启adb/更换adb，并没有对问题产生改善。
2、自动肉鸽中，放置干员山后有一定概率不选择面向并始终保持在面向选择界面

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9484255/asst.zip)
问题1:2022.9.4下午有反复出现，最后一次截止在15:47，有手动重启adb、更换adb的操作。
问题2:2022.9.4下午15:42左右有一次出现，发现后手动选择了面向

### 还有别的吗？

设备名称	
处理器	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.81 GHz
机带 RAM	16.0 GB
设备 ID	
产品 ID	
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

版本	Windows 10 专业版
版本号	21H2
安装日期	‎2021/‎10/‎28
操作系统内部版本	19044.1889
体验	Windows Feature Experience Pack 120.2212.4180.0

操作系统：Microsoft Windows 10 64位  21H2
CPU型号：Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
主板：HP_8390
总内存：15.9 GB
可用内存：1.7 GB
显卡型号：NVIDIA GeForce GTX 1060 with Max-Q Design (20220721)
OpenGL：4.6.0 NVIDIA 516.94
IE版本：11.0
模拟器版本：9.0.19(9)
模拟器路径：D:\leidian\LDPlayer9
日志路径：C:\Users\HP\AppData\Roaming\leidian9\log
vt:开启
运行参数：CPU(4核) 内存：(4096M) 正在运行(1) 高速(1)
分辨率：1280x720 dpi 320 fps 30
总大小25 G，剩余19 G

**Comment by MistEO** [comment]
截图失败的问题 @zzyyyl  修了，还没发版

但我还是建议不要用雷电（

**Comment by zzyyyl** [comment]
> 截图失败的问题 @zzyyyl 修了，还没发版
> 
> 但我还是建议不要用雷电（

其实啊，v4.4.0.b1跟将要发的版截图这块差不多，author也说了 "略有改善"（
总之最好别用雷电（

**Comment by lbpdfs** [comment]
> > 截图失败的问题 @zzyyyl 修了，还没发版
> > 但我还是建议不要用雷电（
> 
> 其实啊，`v4.4.0-beta.1` 跟 即将要发的版 在截图这块差不多，author 也说了 "略有改善"（
> 
> 总之最好别用雷电（

_(:3J∠)_比较不能理解为什么主线图没问题肉鸽一直报错。雷电9是真的流畅到舍不得→_→夜神在我的电脑上直接卡到不能接受

**Comment by zzyyyl** [comment]
肉鸽截图比较频繁，主线图应该比较少？要不你试试 copilot 有没有问题（x

**Comment by MistEO** [comment]
试试蓝叠国际版？

**Comment by et2012** [comment]
> 
> _(:3J∠)_比较不能理解为什么主线图没问题肉鸽一直报错。雷电9是真的流畅到舍不得→_→夜神在我的电脑上直接卡到不能接受

可能是因为肉鸽截图比较频繁？
夜神也至少有两个 issue 说截图有问题了，但我测试了一个多小时无法重现。

**Comment by MistEO** [comment]
v4.4.0-beta.2 修了一个截图问题，试试看

**Comment by SekiBetu** [comment]
> 截图失败的问题 @zzyyyl 修了，还没发版
> 
> 但我还是建议不要用雷电（

蓝叠快破产了，最近一直在大量裁员...

**Comment by MistEO** [comment]
他一个客户端单机程序，破产了不是更好么（没广告了

**Comment by MistEO** [comment]
maa 不兼容雷电，不是说蓝叠和雷电用的不同的方案，然后我们选择支持了蓝叠的方案什么的。

而是，所有模拟器都是同一套标准方案，我们的代码写完，没有针对任何模拟器做过额外适配的情况下，蓝叠一切正常，表现良好；雷电动不动就报个错，动不动就给一张错误的图片，动不动就连接错误。

为此 maa 专门针对雷电做了大量额外的错误检查和处理，但即便如此还是没法覆盖雷电又新出个什么我们从来没见过的错误。这些种类令人眼花缭乱的错误，在蓝叠上，一个一次都没有出现过

**Comment by SekiBetu** [comment]
> maa 不兼容雷电，不是说蓝叠和雷电用的不同的方案，然后我们选择支持了蓝叠的方案什么的。
> 
> 而是，所有模拟器都是同一套标准方案，我们的代码写完，没有针对任何模拟器做过额外适配的情况下，蓝叠一切正常，表现良好；雷电动不动就报个错，动不动就给一张错误的图片，动不动就连接错误。
> 
> 为此 maa 专门针对雷电做了大量额外的错误检查和处理，但即便如此还是没法覆盖雷电又新出个什么我们从来没见过的错误。这些种类令人眼花缭乱的错误，在蓝叠上，一个一次都没有出现过
> 
> ~总结一句话就是，除了蓝叠和夜神，其他模拟器都是垃圾，雷电是垃圾中的垃圾~

不懂技术细节，也不知道maa用的什么技术截图，但是如果是airtest有三种不同的截图模式，minicap确实在雷电模拟器有问题，换用javacap完全没问题

**Comment by SekiBetu** [comment]
https://www.bilibili.com/read/cv14471436/
我觉得可以理解为，MAA是基于蓝叠自研安卓模拟器引擎开发，这个BBchannel是基于virtualbox引擎研发，因为对模拟器的支持完全是相反的，那边讨厌蓝叠和夜神，因为会出现无法点击和无法截图的BUG，这边反而是蓝叠和夜神好用

**Comment by MistEO** [comment]
不是，maa 是基于 adb 的，安卓标准调试接口。这都能报错只能是模拟器自身的问题。

不了解你发的这个，我看他塞了个可执行程序进去，可能他们是针对某些模拟器进行的适配才导致不兼容另一些模拟器。

**Comment by SekiBetu** [comment]
> 不是，maa 是基于 adb 的，安卓标准调试接口。这都能报错只能是模拟器自身的问题。
> 
> 不了解你发的这个，我看他塞了个可执行程序进去，可能他们是针对某些模拟器进行的适配才导致不兼容另一些模拟器。

![image](https://user-images.githubusercontent.com/38283893/188495088-490a7ec2-f13d-4b23-99fd-7875e49d9629.png)
![image](https://user-images.githubusercontent.com/38283893/188495120-651fdfe2-ad98-42b8-bfe5-7ab001bcf22b.png)
不知道能不能引入网易帮你适配好的程序当截图程序？

**Comment by SekiBetu** [comment]
> 不是，maa 是基于 adb 的，安卓标准调试接口。这都能报错只能是模拟器自身的问题。
> 
> 不了解你发的这个，我看他塞了个可执行程序进去，可能他们是针对某些模拟器进行的适配才导致不兼容另一些模拟器。

![image](https://user-images.githubusercontent.com/38283893/188495913-d1d88750-205c-45b2-9381-dacdafc9b81f.png)
![image](https://user-images.githubusercontent.com/38283893/188495939-c3b3f89c-c236-43cf-9e75-3a87d92fac41.png)
蓝叠的Adb肯定是魔改过的，不是官方的，体积不寻常地大，这可能就是与其他模拟器不同的地方

**Comment by lbpdfs** [comment]
> v4.4.0-beta.2 修了一个截图问题，试试看

很遗憾，并没有得到有效的修复，大概和之前相同的情境下，错误由“截图错误”变成了“adb命令乱码”。同时还出现了新的问题，在不断乱码的同时会高速的在我的temp文件夹里塞临时文件，十几分钟塞了有20+G，目前没有找出具体是什么文件，也不清楚是maa在塞还是雷电在塞╮(╯▽╰)╭
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9495823/asst.zip)
直接看log末位部分就行，目前这个问题好像只出现在雷电9上，雷电5和雷电4都没问题→_→大概率是雷电9自己的矛柄了。说起来隔壁alas那种自带一个atx辅助连接的方式能参考吗？alas目前在雷电9上运行还是良好的

**Comment by zzyyyl** [comment]
往 temp 临时文件？ dant——
@dantmnf

**Comment by dantmnf** [comment]
> 往 temp 塞临时文件？ dant—— @dantmnf [#1765 (comment)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1765#discussion_r962348913)

这不是还没进 release 吗（

**Comment by zzyyyl** [comment]
> > 往 temp 塞临时文件？ dant—— @dantmnf [#1765 (comment)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1765#discussion_r962348913)
> 
> 这不是还没进 release 吗（

草，好像确实哦（
那大概是雷电自己的问题（？

**Comment by dantmnf** [comment]
看了一下，log 里应该是嵌入了完整的 PNG 数据，虽然被换行符转换搞坏了.

那大概就是雷电自己的问题（

**Comment by horror-proton** [comment]
> 看了一下，log 里应该是嵌入了完整的 PNG 数据，虽然被换行符转换搞坏了.
> 
> 那大概就是雷电自己的问题（

好像数据过小就会打印出来 (
