### ISSUE TITLE
使用夜神模拟器，maa闪退

### ISSUE THREAD

**Issue by sysfzs** [MaaAssistantArknights/MaaAssistantArknights#1763]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更换模拟器，由雷神更换为夜神模拟器，adb正常修改，链接正常，但是开始执行任务就闪退，且黑屏。
![image](https://user-images.githubusercontent.com/61590548/188317952-40eb2250-5ab5-4347-ab12-c4f2022e6faf.png)
在此界面后闪退
![image](https://user-images.githubusercontent.com/61590548/188318088-efa9909f-7f3d-4215-a431-7f13455fa052.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9484844/asst.log)

### 截图

见上图

### 还有别的吗？

暂无

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
