### ISSUE TITLE
用作业制作器写的，解析错误

### ISSUE THREAD

**Issue by heluene** [MaaAssistantArknights/MaaAssistantArknights#1764]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用"index"写的作业，“解析作业文件错误！”
使用的作业无法上传github，见1群“日志文件”群文件夹中2763739926上传的脚本

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9484964/asst.log)

### 截图

![Uploading image.png…]()

### 还有别的吗？

最新稳定版和测试版都无法读取

**Comment by heluene** [comment]
![image](https://user-images.githubusercontent.com/107483017/188321306-ccdd68f3-b1da-4a79-9b15-3be4094eb1ca.png)
![image](https://user-images.githubusercontent.com/107483017/188321330-752009a7-642e-4e65-b56e-2105485a56bf.png)

**Comment by MistEO** [comment]
作业文件可以打个压缩包再传

**Comment by MistEO** [comment]
看到了，应该是因为你没写标题和简介

@LYZhelloworld 上次改的作业编辑器，不会自动补上空的的标题和简介么，直接没这个字段了

**Comment by MistEO** [comment]
[伦蒂尼姆边缘区块_桃金娘+煌+棘刺+银灰+山+泥岩+塞雷娅+黑角+流明+夜莺 (2).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9490183/_.%2B.%2B.%2B.%2B.%2B.%2B.%2B.%2B.%2B.2.zip)
