### ISSUE TITLE
肉鸽战斗意外

### ISSUE THREAD

**Issue by lbpdfs** [MaaAssistantArknights/MaaAssistantArknights#1766]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽战斗，关卡：正义中，奶妈摆放位置问题导致最后一只怪始终被卡住无人清理

### 日志文件

2022.9.5 01:17开始的战斗
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9485210/asst.zip)

### 截图

![0099](https://user-images.githubusercontent.com/49297944/188325790-ca66377d-3b81-4624-99bd-39f65ff821bf.png)
最后一只怪被卡在安塞尔边上，互相折磨，其余干员始终放置在其他位置，只能手动让安塞尔退场才能继续

**Comment by MistEO** [comment]
等 5 分钟会自动撤退的

**Comment by lbpdfs** [comment]
> 等 5 分钟会自动撤退的

感谢回复
