### ISSUE TITLE
肉鸽进入战斗关卡的黑屏等待时间不足，在低配电脑上出现关卡识别错误

### ISSUE THREAD

**Issue by lbpdfs** [MaaAssistantArknights/MaaAssistantArknights#1768]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

目前肉鸽进入战斗关卡的识别等待时间大概是25s？我目前的电脑进入关卡可能会黑屏40~60s的样子，然后就跳关卡识别错误了。
下面算废话
其实是昨天发现雷电的问题解决不了之后，不想在一台电脑上装两个模拟器来回切连接设置，就翻出来另一台老电脑安了新的模拟器，想着反正慢慢挂肉鸽稍微卡点也没事，结果因为配置太低了出现了新的问题_(:3J∠)_

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9488267/asst.zip)

**Comment by lbpdfs** [comment]
另外问下，经常出现这种放下干员不选择面向的问题是正常现象吗
![0099](https://user-images.githubusercontent.com/49297944/188433418-64a7d5c6-7581-4105-aada-1093bfde1f9e.png)

**Comment by MistEO** [comment]
> 应该不正常, 好像没有遇到过不选择朝向的情况

电脑太卡了滑动太快，滑动丢帧了，就会这样

**Comment by lbpdfs** [comment]
> > 应该不正常, 好像没有遇到过不选择朝向的情况
> 
> 电脑太卡了滑动太快，滑动丢帧了，就会这样

但是不对啊，我流畅的电脑出现这个反而比卡顿的电脑更多0.0

**Comment by MistEO** [comment]
- 肉鸽进入战斗关卡的黑屏等待时间不足
    可通过修改 `resource/tasks.json` 中 `Roguelike1WaitBattleStart` 加入 `rearDelay` 字段来延长一下等待时间，单位毫秒，例如
```jsonc
    "Roguelike1WaitBattleStart": {
        "Doc": "点了开始行动之后，可能会网络不好一直loading，用这个任务等一会",
        "template": "Roguelike1QuickFormation.png",
        "action": "DoNothing",
        "roi": [
            817,
            0,
            402,
            146
        ],
        "next": [
            "Roguelike1WaitBattleStart"
        ],
        "rearDelay": 20000
    },
```
- 出现这种放下干员不选择面向的问题
    可通过修改 `resource/tasks.json` 中 `BattleUseOper`, `BattleSwipeOper` 加入 `preDelay`, `rearDelay` 字段来延长一下等待时间，单位毫秒（文件中有注释，可参考）

**Comment by lbpdfs** [comment]
> * 肉鸽进入战斗关卡的黑屏等待时间不足
>   可通过修改 `resource/tasks.json` 中 `Roguelike1WaitBattleStart` 加入 `rearDelay` 字段来延长一下等待时间，单位毫秒，例如
> 
> ```js
>     "Roguelike1WaitBattleStart": {
>         "Doc": "点了开始行动之后，可能会网络不好一直loading，用这个任务等一会",
>         "template": "Roguelike1QuickFormation.png",
>         "action": "DoNothing",
>         "roi": [
>             817,
>             0,
>             402,
>             146
>         ],
>         "next": [
>             "Roguelike1WaitBattleStart"
>         ],
>         "rearDelay": 20000
>     },
> ```
> 
> * 出现这种放下干员不选择面向的问题
>   可通过修改 `resource/tasks.json` 中 `BattleUseOper`, `BattleSwipeOper` 中 `preDelay`, `rearDelay` 字段来延长一下等待时间，单位毫秒（文件中有注释，可参考）
> 
> 上面 @horror-proton 的方案并不能解决这两个问题_(:з」∠)_

感谢解答，上文提到的问题均得到了不同程度的改善，剩下的一些小问题都无伤大雅。另有一个小建议，就是在关卡选择的地方提前识别关卡名称，而不是去识别开幕，是不是会更稳定些
![识别这里](https://user-images.githubusercontent.com/49297944/188655023-fc1b8729-4e61-4ef4-b1fb-47ea849f9395.png)
