### ISSUE TITLE
【Feature Request】希望永久性解决screencap截图错误问题

### ISSUE THREAD

**Issue by SekiBetu** [MaaAssistantArknights/MaaAssistantArknights#1771]
### 说说你遇到的问题？

各种不同模拟器造成的多种不同的screencap截图错误问题挤满了本项目issue区，开发者也需要对不同模拟器进行不停地适配

### 有什么好的想法？

停止依赖模拟器自带的screencap工具，通过以下两种方式解决截图错误的问题

https://github.com/ArknightsAutoHelper/ArknightsAutoHelper/issues/268#issuecomment-949618025

- 在 ADB shell 里用 app_process 载入 java 代码调用系统 framework 获取 view 的截图 👈需要写一堆 Java；
- 使用 Windows.Graphics.Capture 获取窗口的 DXGI Surface，并且复制回 CPU 👈需要写一堆 COM；

### 其他内容

但取决于开发者的能力，是否对这些方式熟悉，所以先开个issue在这里，万一有免费劳动力过来提PR就赚了

**Comment by SekiBetu** [comment]
当然，如果那么多的screencap截图错误真的只是autocrlf的问题的话，那也不需要这么干了 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1728

**Comment by CorenoneSong** [comment]
> 当然，如果那么多的 [screencap截图错误](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/459#issuecomment-1120386093) 真的只是 [autocrlf](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1728) 的问题的话，那也不需要这么干了

应该不是[autocrlf](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1728)的问题，这个fix是为了解决我提出的截图问题，但是更新4.3.1之后问题仍然存在。建议仔细看一下4.2.3到4.3.0这次更新改了哪些地方，我就是这个更新之后才出现的错误。~~如果不是更新造成的，那可能与使用时长或次数有关？缓存爆了？瞎猜的~~

**Comment by zzyyyl** [comment]
事实上 4.2.3 到 4.3.0 根本没改截图相关的代码（

**Comment by CorenoneSong** [comment]
> 事实上 4.2.3 到 4.3.0 根本没改截图相关的代码（
bug已经能自我产生了，那它一定也能自我修复吧（

**Comment by MistEO** [comment]
> 事实上 4.2.3 到 4.3.0 根本没改截图相关的代码（

还是改了的，错把 socket 屏蔽掉了 orz

然后现在这一系列问题都是因为没用 socket 截图

**Comment by BombaxCeiba** [comment]
> ### 说说你遇到的问题？
> 各种不同模拟器造成的多种不同的screencap截图错误问题挤满了本项目issue区，开发者也需要对不同模拟器进行不停地适配
> 
> ### 有什么好的想法？
> 停止依赖模拟器自带的screencap工具，通过以下两种方式解决截图错误的问题
> 
> [ArknightsAutoHelper/ArknightsAutoHelper#268 (comment)](https://github.com/ArknightsAutoHelper/ArknightsAutoHelper/issues/268#issuecomment-949618025)
> 
> * 在 ADB shell 里用 app_process 载入 java 代码调用系统 framework 获取 view 的截图 👈需要写一堆 Java；
> * 使用 Windows.Graphics.Capture 获取窗口的 DXGI Surface，并且复制回 CPU 👈需要写一堆 COM；
> 
> ### 其他内容
> 但取决于开发者的能力，是否对这些方式熟悉，所以先开个issue在这里，万一有免费劳动力过来提PR就赚了

Windows.Graphics.Capture捕获的截图会不会受到窗口大小的影响，导致截图结果不符合要求。

**Comment by SekiBetu** [comment]
> > ### 说说你遇到的问题？
> > 各种不同模拟器造成的多种不同的screencap截图错误问题挤满了本项目issue区，开发者也需要对不同模拟器进行不停地适配
> > ### 有什么好的想法？
> > 停止依赖模拟器自带的screencap工具，通过以下两种方式解决截图错误的问题
> > [ArknightsAutoHelper/ArknightsAutoHelper#268 (comment)](https://github.com/ArknightsAutoHelper/ArknightsAutoHelper/issues/268#issuecomment-949618025)
> > 
> > * 在 ADB shell 里用 app_process 载入 java 代码调用系统 framework 获取 view 的截图 👈需要写一堆 Java；
> > * 使用 Windows.Graphics.Capture 获取窗口的 DXGI Surface，并且复制回 CPU 👈需要写一堆 COM；
> > 
> > ### 其他内容
> > 但取决于开发者的能力，是否对这些方式熟悉，所以先开个issue在这里，万一有免费劳动力过来提PR就赚了
> 
> 更新 Windows.Graphics.Capture 截图的方案必须要用户手动选择窗口，不够全自动，也算是不太可行吧。

说说你遇到的问题？
各种不同模拟器造成的多种不同的screencap截图错误问题挤满了本项目issue区，开发者也需要对不同模拟器进行不停地适配

**Comment by BombaxCeiba** [comment]
> > > ### 说说你遇到的问题？
> > > 各种不同模拟器造成的多种不同的screencap截图错误问题挤满了本项目issue区，开发者也需要对不同模拟器进行不停地适配
> > > ### 有什么好的想法？
> > > 停止依赖模拟器自带的screencap工具，通过以下两种方式解决截图错误的问题
> > > [ArknightsAutoHelper/ArknightsAutoHelper#268 (comment)](https://github.com/ArknightsAutoHelper/ArknightsAutoHelper/issues/268#issuecomment-949618025)
> > > 
> > > * 在 ADB shell 里用 app_process 载入 java 代码调用系统 framework 获取 view 的截图 👈需要写一堆 Java；
> > > * 使用 Windows.Graphics.Capture 获取窗口的 DXGI Surface，并且复制回 CPU 👈需要写一堆 COM；
> > > 
> > > ### 其他内容
> > > 但取决于开发者的能力，是否对这些方式熟悉，所以先开个issue在这里，万一有免费劳动力过来提PR就赚了
> > 
> > 
> > 更新 Windows.Graphics.Capture 截图的方案必须要用户手动选择窗口，不够全自动，也算是不太可行吧。
> 
> 说说你遇到的问题？ 各种不同模拟器造成的多种不同的screencap截图错误问题挤满了本项目issue区，开发者也需要对不同模拟器进行不停地适配

再更新
刚刚发现一个IGraphicsCaptureItemInterop::CreateForWindow method，可能能用，就是系统版本要求Windows 10 Build 20348。

**Comment by chengyuhui** [comment]
可以考虑使用[minicap](https://github.com/DeviceFarmer/minicap)，相关的预编译包在[这里](https://github.com/DeviceFarmer/minicap/issues/39#issuecomment-1220435651)有，设置一个合适的帧率然后等着收JPEG就行了。

不过粗略看了源码，minicap、scrcpy、screencap事实上使用的是同一个系列的接口（不过screencap存在一些区别，minicap和scrcpy的倒是非常相似），而之前有用户提到截图时好时坏，让人不得不怀疑部分模拟器这套屏幕捕获的管线本身就有问题，难以修复
