### ISSUE TITLE
内存占用过大

### ISSUE THREAD

**Issue by onlyacat** [MaaAssistantArknights/MaaAssistantArknights#1773]
### 说说你遇到的问题？

目前升级到了最新版[4.3.1]，内存占用大幅提高。启动跑一遍日常后，就用到了 800 M 内存。即便停止行动了，内存也不会释放。

因为用的是 windows server，运行过程中经常性导致 rdp 连接断开或者 OOM 需要重启电脑。

之前版本都没这问题，想看看有没有啥优化途径。

![image](https://user-images.githubusercontent.com/29370032/188528193-760aa9d2-14a3-4aa8-add3-393b03539094.png)

**Comment by MistEO** [comment]
试试测试版本

**Comment by onlyacat** [comment]
新版本似乎好了点，先 close 掉
