### ISSUE TITLE
关卡选择增加一图流的关卡

### ISSUE THREAD

**Issue by heiheiyoyo** [MaaAssistantArknights/MaaAssistantArknights#1776]
### 说说你遇到的问题？

gui中的关卡选择不够丰富

### 有什么好的想法？

增加[刷素材一图流](https://arkonegraph.herokuapp.com)中的关卡
api是https://arkonegraph.herokuapp.com/total/CN
不过好像导航不到SN-9，可能需要调一下
能有个仓库识别和长草模式就更好了🤣

**Comment by ABA2396** [comment]
core支持了全主线的导航，但是ui还没（）
