### ISSUE TITLE
日服自动肉鸽BUG

### ISSUE THREAD

**Issue by 466895132** [MaaAssistantArknights/MaaAssistantArknights#1777]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

日服自动肉鸽会卡在初始队伍招募界面    卡在选择完近卫干员之后的情况最多   看日志好像是截图没有匹配到任何情况     

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9498859/asst.zip)

### 截图

![1](https://user-images.githubusercontent.com/11262966/188686198-1e2b9857-aa45-4623-b26f-1b4a6509ce51.png)

**Comment by MistEO** [comment]
看起来你的干员等级都太低了，好多都是精 1 10 级之类的，不知道是不是识别错了，可以截个图看下么？

后面可能考虑在未选择任何干员的情况下，即使等级再低也要先选三个。

cc @et2012

**Comment by 466895132** [comment]
那可能就是识别错误了    我4星干员的确没怎么练  但是6星都是精二   3星都是精1满级的    不可能出现第一个位置就无干员可用的情况    近卫BOX
![1](https://user-images.githubusercontent.com/11262966/189496951-d6bb72e3-fef7-4f11-8551-9535bd05d44e.png)
![2](https://user-images.githubusercontent.com/11262966/189496957-9c7d5eff-60a7-4721-bc76-af528b420e37.png)
![3](https://user-images.githubusercontent.com/11262966/189496959-9b26efaa-8686-4c93-b70e-fe97bfc50819.png)

**Comment by et2012** [comment]
看样子是等级数字识别失败了，很多都识别成精一 1 级了，还有煌、棘刺 10 级，银灰、星极、幽灵鲨 0 级...
也许是日服字体的问题，离那个圆圈太近了。
