### ISSUE TITLE
希望关卡选择可以匹配“全天开放”的资源本

### ISSUE THREAD

**Issue by llomin** [MaaAssistantArknights/MaaAssistantArknights#1778]
### 说说你遇到的问题？

无论是今日关卡提示还是关卡选择栏都不能识别活动期间“全天开放”的特性。

### 有什么好的想法？

可以考虑使用PRTS上的“今日信息”。

**Comment by llomin** [comment]
> 440b2导航是支持的，可以更新测试版试试

解决了，但是“今日关卡提示”好像还是老样子，希望后续也更新一下~

**Comment by et2012** [comment]
> > 440b2导航是支持的，可以更新测试版试试
> 
> 解决了，但是“今日关卡提示”好像还是老样子，希望后续也更新一下~

全部显示出来会很占空间，所以这部分的逻辑没改。
后续可能会改成 “资源关卡全部开放中，9月8日 4:00 结束” 这种提示。

**Comment by ABA2396** [comment]
这个可能还得加个条件限制，活动开放还得看是不是简中服务器，不然外服用备选就炸了（）
