### ISSUE TITLE
更新之后连接模拟器时间过长

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#1789]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新之后，我想体验一下仓库识别功能，却发现MAA连接模拟器时间过长。之后我重启MAA，选择刷理智功能，从连接开始到连接成功之间长达一分钟，之前顶多几秒十几秒。

### 日志文件

问题发生在2022年9月9日上午9点20分之后
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9531629/asst.log)

### 截图

![屏幕截图 2022-09-09 092747](https://user-images.githubusercontent.com/92417243/189253629-5c33fdf2-3006-4d27-b23d-6eb99d7e2cbc.jpg)

### 还有别的吗？

我正在使用的模拟器是雷电模拟器4.0.72，操作系统是Windows11，电脑配置的9300H+1650、内测16G

**Comment by MistEO** [comment]
不要用雷电.jpg

**Comment by xiaoweiXX** [comment]
> 不要用雷电.jpg

更新之前速度虽然慢一点，但是连接时间也是按秒算的，更新完了之后是按分钟算，长了不知道几倍。另外我感觉还是雷电比较好用，我用过mumu，虽然效率可能比雷电高一些，但是用久了就会有很多的莫名小卡顿。

**Comment by zzyyyl** [comment]
可能是 nc port 不断重试的原因？

**Comment by zzyyyl** [comment]
call_command 把给定的 60s 跑满了（
