### ISSUE TITLE
自动重新登录功能请求

### ISSUE THREAD

**Issue by Nchyn** [MaaAssistantArknights/MaaAssistantArknights#179]
当我在随身的手机游玩方舟后，与MAA相连接的设备操作联网验证的内容时会提示账号在其他设备登录，并导致MAA任务中断，是否可以添加判断自动重新登录？（该操作不需要密码）

**Comment by MistEO** [comment]
刷理智、无限肉鸽，这俩功能当前就是支持掉线重连的，因为这俩一般耗时比较长，所以额外做了。

其他功能暂不支持，新建文件夹.jpg

**Comment by Nchyn** [comment]
@MistEO 
![image](https://user-images.githubusercontent.com/28627461/152084944-2ecd7122-1320-4a66-aedf-67104d48b87b.png)
在主界面待机，其他设备顶号之后启动全功能选择的一键长草会卡在这个步骤
以下是任务出错附近的日志文本
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7983217/asst.log)
谢谢大佬的软件让博士的肝重获新生（

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
