### ISSUE TITLE
设置了完成任务后自动关闭，夜神模拟器无法完全关闭进程

### ISSUE THREAD

**Issue by zoe4477** [MaaAssistantArknights/MaaAssistantArknights#1793]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动关闭后还会留下一个很占内存的夜神模拟器后台进程。之前用雷电模拟器时好像没有这情况。
![1](https://user-images.githubusercontent.com/38827851/189368495-790fa3b7-5c6e-44d9-b6b3-daec95e85325.jpg)

### 日志文件

时间点：最后运行时间
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9536062/asst.log)

**Comment by ntgmc** [comment]
模拟器关闭有时候会关不了
