### ISSUE TITLE
仓库识别 部分物品数值识别错误

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#1795]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

111 这种好多个1的数值会被识别为 1
两位数的 11 也会偶发错误
而其他例如 44 55 则不会出错
(麻了莫名搞笑

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9536960/asst.log)

### 截图

[截图s.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9536941/s.zip)

**Comment by MistEO** [comment]
@zzyyyl 该补上仓库识别的 labeler 了（

**Comment by ABA2396** [comment]
21也是1
![Screenshot_2022 09 10_20 48 31 702](https://user-images.githubusercontent.com/99072975/189485326-585ab0df-3fc4-425b-8d5f-9d3880e44f5c.png)
