### ISSUE TITLE
歌蕾蒂娅在控制中枢中产生非预期的效率数值

### ISSUE THREAD

**Issue by HeroTch** [MaaAssistantArknights/MaaAssistantArknights#1800]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Issue #1717 中降低了歌蕾蒂娅 bskill_ctrl_aegir 的效率值后为0.04，但在最终计算中可能与歌蕾蒂娅的bskill_ctrl_cost_aegir效率相加，变回0.05（log中为0.05）
（话说之前的效率值计算完后在log中是0.06，~~之前降低效率的时候是不是降少了~~）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9538842/asst.log)

### 截图

![图片](https://user-images.githubusercontent.com/29833444/189446341-f237c0b0-115f-4add-9112-5e87f83db013.png)

**Comment by MistEO** [comment]
考虑现在没啥深海组能上班，歌蕾蒂娅不就相当于普通的 `每小时恢复+0.05` 么，还要继续降么？
