### ISSUE TITLE
有新的控制中枢永动机，建议加在代码内

### ISSUE THREAD

**Issue by 208782779** [MaaAssistantArknights/MaaAssistantArknights#1801]
### 有什么好的想法？

![@X7}E)$(QLU KQZFQ`V8BL](https://user-images.githubusercontent.com/113219112/189462042-82c66ed6-5250-4731-86a8-8f7631716b19.png)
在控制中枢放入这三名三星异格干员，再加上另外两名异格干员，就能达成永动，而且在以后如果出另外一名三星异格干员的话，只需要四位干员就能达成永动，这个无疑会有很高的需求量，所以麻烦增加异格干员在控制中枢时不会被放入其他基建，除非没心情

**Comment by AnnoyingFlowers** [comment]
我觉得永动只是给基建咸鱼的逃课方法，你都用maa了，为啥不用效率更高的呢

**Comment by ABA2396** [comment]
可以自己换好，然后在设置里取消勾选控制中枢的换班

**Comment by Private233** [comment]
从效率来看，精二异格炎熔有为数不多的三级发电站技能，放中枢永动得亏多少无人机啊
还是前面那句话，都用maa了，为啥不追求更高的效率呢

**Comment by CorleoneSong** [comment]
有个建议
凯尔希和阿米娅加三个异格者能干三天，但是MAA会自己换掉异格者
这次的叔叔和但书也是新的基建幻神，但是MAA只能安排好但书，叔叔需要的那些很可能被换掉
前者7%的2%效率挺高了，后者能让差不多全基建的幻神加班更久，参考B站公孙长乐的计算，普通人都能干60h，更不用说巫恋组这样的了
__所以我建议MAA只需要针对控制中枢出一个成套的换班流，让玩家自己选择体系，不成体系或没有体系就按默认的换，不知是否可行__

**Comment by zzyyyl** [comment]
可以自定义基建（
