### ISSUE TITLE
基建 制造站生产 类型提议

### ISSUE THREAD

**Issue by nightofknife** [MaaAssistantArknights/MaaAssistantArknights#1806]
### 说说你遇到的问题？

虽然用maa已经很偷懒了
但是有时候确实没法上线
在现在的maa基建设置中超过一天不上线就全红了感觉有点小亏

### 有什么好的想法？

为基建提供两个设置，一个以效率优先选择高生产力的组合，一个以生产时间优先用来应对长时间不上线的情况（比如泡泡和贝娜这种提高仓库上限但是降低生产力的）

### 其他内容

使用生产时间优先的设置时候，如果同时勾选了基建设置里的  控制中枢  可以考虑换上永动组？

**Comment by MistEO** [comment]
实现感觉不难，搞两套配置文件就行了。但是维护成本++

**Comment by nightofknife** [comment]
虽然不知道maa现在的基建怎么算的效率
但是要不考虑群友的力量？

**Comment by myjdem** [comment]
要加算法搭配干员的基建技能，还要考虑到有些博士是没有这个干员组不成永动机，不过为什么次次能天使，德狗，拉狗会分开来啊，这三个明明我都有，他们在一起不是效率会更高嘛QAQ，而且出现了干员冲突maa是不会管你因为干员冲突而导致前面某一个制造站或者贸易站少人的= =

**Comment by MistEO** [comment]
> 要加算法搭配干员的基建技能，还要考虑到有些博士是没有这个干员组不成永动机，不过为什么次次能天使，德狗，拉狗会分开来啊，这三个明明我都有，他们在一起不是效率会更高嘛QAQ，而且出现了干员冲突maa是不会管你因为干员冲突而导致前面某一个制造站或者贸易站少人的= =

能天使，德狗，拉狗 是懒人组合，这三个在一起效率并不是最高的。而 maa 只考虑效率（

**Comment by myjdem** [comment]
> > 要加算法搭配干员的基建技能，还要考虑到有些博士是没有这个干员组不成永动机，不过为什么次次能天使，德狗，拉狗会分开来啊，这三个明明我都有，他们在一起不是效率会更高嘛QAQ，而且出现了干员冲突maa是不会管你因为干员冲突而导致前面某一个制造站或者贸易站少人的= =
> 
> 能天使，德狗，拉狗 是懒人组合，这三个在一起效率并不是最高的。而 maa 只考虑效率（

我一直以为这三个在一起是效率最高的= =

**Comment by MistEO** [comment]
有自定义基建了，我关！
