### ISSUE TITLE
JP client Depot Analyze Startpoint(JP版倉庫認識開始位置がおかしい)

### ISSUE THREAD

**Issue by wallsman** [MaaAssistantArknights/MaaAssistantArknights#1809]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I spent at least 5 minutes thinking and preparing before raising the issue.
- [X] I have read the FAQ and the User Manual in the documentation and believe that this is most likely a bug and not designed to be so.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Cant analysis "研磨石" left side.
If you start the analysis from the left above, you will not be able to start.

Can start at the halfway point as shown in the image in the Zip.

### Log files

[depot.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9541490/depot.zip)

### Screenshots

![image](https://user-images.githubusercontent.com/63186641/189504053-07077ff8-482c-48d1-86cf-ea1f5a22c662.png)

**Comment by MistEO** [comment]
Start from this screen, overseas clients don't yet support automatic entry here.

![image](https://user-images.githubusercontent.com/18511905/189520784-b9a40976-0d9e-4cb0-aa31-166dec1ea944.png)

**Comment by wallsman** [comment]
Thx, Oversees Client add Text later.
