### ISSUE TITLE
是否可以利用adb修改手机分辨率来适配手机？

### ISSUE THREAD

**Issue by Jie-Qiao** [MaaAssistantArknights/MaaAssistantArknights#181]
比如可以用
`./adb shell wm size 1080x1980`
来修改分辨率，用
`./adb shell wm density 320`
来修改dpi，

最后复原即可
`./adb shell wm size reset`
`./adb shell wm density reset`

自己试了下，好像还是不太行，可能是修改分辨率后坐标有些变化？

**Comment by Jie-Qiao** [comment]
经测试，可以在vmos中，将分辨率调整为1080x1920，并开启网络adb模式，可以完美运行。

**Comment by MistEO** [comment]
refer to https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/388
