### ISSUE TITLE
刷1-7刷出了一个叫做furni的东西

### ISSUE THREAD

**Issue by EnosRed** [MaaAssistantArknights/MaaAssistantArknights#1810]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新完在刷1-7的土块的时候发现了一个英文描述的物品，不知道是个啥？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9541515/asst.log)
时间大概是0911 5点32分的时候

### 截图

![1662851071502](https://user-images.githubusercontent.com/113267116/189504618-029cc606-6c3b-4c05-905e-ca0d92606d19.png)

### 还有别的吗？

没了

**Comment by aa889788** [comment]
furni是家具

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1094

**Comment by MistEO** [comment]
Maybe we can hard code the translation of furi.
