### ISSUE TITLE
关于基建收菜

### ISSUE THREAD

**Issue by lastxxx2** [MaaAssistantArknights/MaaAssistantArknights#1813]
### 说说你遇到的问题？

希望出一个基建不自动换班只收菜用无人机的功能

**Comment by zzyyyl** [comment]
你把基建设置里，所有设施的复选框全部取消就是这个功能

**Comment by myjdem** [comment]
基建的那个阈值按百分比搞得有点懵逼，到现在我都没明白到底是到了设定的百分比塞进宿舍还是去生产，感觉改成心情低于多少放入宿舍的话并且按照点心情来算会更容易理解一些。

**Comment by lastxxx2** [comment]
> 

如果全取消就不会清无人机了

**Comment by ltc-01** [comment]
把下面这段代码修改成你想要的，然后复制到记事本，保存，文件后缀改成json，基建设置里启用自定义基建选择刚刚保存的这个文件，并在想加速的房间上打勾。比如我想第二个制造站用无人机加速，但不换班：（“drones”里的room写加速的房间，index写房间序号，"rooms"里的manufacture是制造站， 要贸易站就改成"trading" ，index写了几个 ，” { "skip": true } ,“ 就复制几个，比如我上面index写的2，下面就复制两个）
```
{ 
    "plans": [{
            "drones": {           
                "enable": true,    
                "room": "manufacture",  
                "index": 2,       
                "rule": "all",     
                "order": "pre"    
            },
            "rooms": {            
                "manufacture": [
                    {"skip": true} ,
                    {"skip": true} 
                ]
            }
        }]
}
```
