### ISSUE TITLE
关于软件更新

### ISSUE THREAD

**Issue by UnicornXR** [MaaAssistantArknights/MaaAssistantArknights#1815]
### 说说你遇到的问题？

自动下载的这个能有其他下载源吗，另外 下载了多少也不知道

**Comment by GnahNehc** [comment]
确实，下载了多少不知道这点做的不太好，搞得我每次都是点更新然后放那边几个小时，给它足够的时间下载好。

**Comment by ntgmc** [comment]
现在ota镜像站已经做好，自动更新下载已经很快
至于下载进度不会做
感谢您的反馈！
