### ISSUE TITLE
上报失败及掉落识别错误

### ISSUE THREAD

**Issue by EnosRed** [MaaAssistantArknights/MaaAssistantArknights#1817]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

20把里掉落识别失败只有1次 但是上传已经有好几次失败了
上传失败大概显示的是上传失败，放弃上传至企鹅物流

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9544018/asst.log)

**Comment by MistEO** [comment]
和企鹅的开发大佬们沟通了下，上午企鹅的服务器炸了。现在应该恢复了

**Comment by horror-proton** [comment]
掉落识别失败如果软件的 debug 文件夹里面有图片的话可以打包发一下

**Comment by EnosRed** [comment]
里面有9张图，还有11号的，应该是之前也有但是我没有注意到
[drops.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9546747/drops.zip)

**Comment by MistEO** [comment]
看起来老鲤背景的识别可能有问题，还是要解决一下
