### ISSUE TITLE
关于手机

### ISSUE THREAD

**Issue by tsctsc6** [MaaAssistantArknights/MaaAssistantArknights#1819]
### 有什么好的想法？

建议把改分辨率的adb指令弄进软件里。
开启一个手机模式，软件开始任务时改分辨率，任务结束时还原分辨率。

**Comment by tsctsc6** [comment]
这个软件不是不支持非16:9分辨率嘛
手机的分辨率也不一定是16:9，但是可以改
这样就可以在手机运行明日方舟，用软件挂机了

**Comment by yuanze31** [comment]
（你都已经拿电脑开MAA了，都不能挂个模拟器吗）
虽然可能对一些低配电脑（带不起来模拟器）有点用，但是估计要做一堆非16：9适配
而且这个需求可能非常小众

**Comment by tsctsc6** [comment]
兄弟，我说的是改手机的分辨率。

**Comment by yuanze31** [comment]
> 兄弟，我说的是改手机的分辨率。

理论上改完能用
但是这个需求应该很小众

**Comment by tsctsc6** [comment]
行吧。
