### ISSUE TITLE
建议肉鸽也加一个可以抄作业的模式

### ISSUE THREAD

**Issue by ENE4546** [MaaAssistantArknights/MaaAssistantArknights#1831]
### 有什么好的想法？

可以让用户更改选干员的优先级什么的（跟自动肉鸽的差不多），选了什么干员就按怎样的作业（json）部署，那样打关的层数也会多一些。

**Comment by one-pyy** [comment]
肉鸽主要是为了刷源石锭和蜡烛, 打关的层数其实是次要的吧()

**Comment by MistEO** [comment]
肉鸽要考虑的问题非常多，没法简单的抽象成“作业”，目前加了一些字段来完善肉鸽的战斗逻辑，进度可以关注 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/2167
