### ISSUE TITLE
经常出现“模拟器断开，请尝试后重连（1）”

### ISSUE THREAD

**Issue by 2683807278** [MaaAssistantArknights/MaaAssistantArknights#1837]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在MAA更新到V4.4.1后出现这种情况，之前没出现过。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9556847/asst.log)
[asst(2).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9556859/asst.2.log)
编号2的log文件能和截图对应上，上一个忘截图了，大致情况就是脚本进行一次操作之后就断连一次

### 截图

![6](https://user-images.githubusercontent.com/77843037/189898188-56d6d5d6-6967-44e6-aeb2-15bf52e37825.png)

### 还有别的吗？

蓝叠模拟器 v5.9.110.16 N64
MAA v4.4.1
![屏幕截图 2022-09-13 200804](https://user-images.githubusercontent.com/77843037/189897639-f5af9807-8a05-4400-a1c6-c5763289da86.png)

**Comment by zzyyyl** [comment]
试试 [v4.5.0-beta.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.5.0-beta.1)
