### ISSUE TITLE
开启备选关卡模式，用户的关卡选择当前未开放时不应该重置为“当前/上次”

### ISSUE THREAD

**Issue by miyouzi** [MaaAssistantArknights/MaaAssistantArknights#1838]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

当MAA启用备选关卡模式时，通常为长时间的挂机运行（为了节电，我设置夜间关机），MAA重启后会根据关卡是否开放来重置用户的关卡选择，但该设计在启用备选关卡模式时不合适，在启用该模式是不应重置用户的关卡选择。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9558816/asst.log)

### 截图

![MAA_BUG](https://user-images.githubusercontent.com/24269465/189948000-9a6a1485-e644-4aa5-b578-83025d067578.gif)

**Comment by zzyyyl** [comment]
fixed by c6684accfded660143242914e50d246ded21866b
