### ISSUE TITLE
肉鸽有时候会在“安全的角落”事件卡住

### ISSUE THREAD

**Issue by Barainph** [MaaAssistantArknights/MaaAssistantArknights#1839]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动肉鸽有时会在安全的角落事件选完奖励后的界面（此时要再点一次才能回到地图）卡住，之后一段时间后因为卡住便自动放弃本次探险重新开始下一局

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9558975/asst.zip)

重点在下方截图的时间段

### 截图

![time](https://user-images.githubusercontent.com/113459806/189954833-31a48267-b4f5-4e66-aea1-fb8fe837543f.JPG)

### 还有别的吗？

蓝叠模拟器国际版
模拟器分辨率1280*720  320DPI
windows10操作系统
i7-9750H
RTX 2060
很抱歉我没有截到卡住时界面的图，下次遇到补上（

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
