### ISSUE TITLE
抄作业功能  关闭 假日威龙陈 技能失败

### ISSUE THREAD

**Issue by nightofknife** [MaaAssistantArknights/MaaAssistantArknights#1842]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

问题作业文件：
[AW-4_银灰+假日威龙陈+讯使+苏苏洛+古米+克洛丝+芬 (7).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9562577/AW-4_.%2B.%2B.%2B.%2B.%2B.%2B.7.zip)
水陈技能没法关
PS₁：关闭技能操作是再写一次开启技能
PS₂：猜测是对技能能否开始进行了识别，关技能的时候识别失败导致的

顺便提问：现在开技能是要识别技能图标下面的ready字母吗？

之前版本的MAA是可以通过 技能操作 关闭技能的

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9562537/asst.log)

末尾部分

### 截图

MAA界面截图
![AU4X(~4Y~{BF2`35E_Q7WZ9](https://user-images.githubusercontent.com/73384329/190056906-8f04c7f6-f8c3-415f-848e-4f0ae980991e.png)

模拟器界面截图
![Screenshot_2022 09 14_12 01 30 764](https://user-images.githubusercontent.com/73384329/190056799-36a05a98-4108-4e52-8617-cd9600718f86.png)

### 还有别的吗？

MAA版本：4.4.1
模拟器：蓝叠国际版

**Comment by ABA2396** [comment]
没做关技能的功能吧，不知道后来有没有加，主要是有那个30/32应该是当成技能还没好了

**Comment by MistEO** [comment]
> 没做关技能的功能吧，不知道后来有没有加，主要是有那个30/32应该是当成技能还没好了

停止做了的，晚上回去看看（

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
