### ISSUE TITLE
tag部分识别错误

### ISSUE THREAD

**Issue by 523548** [MaaAssistantArknights/MaaAssistantArknights#1846]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

爆发tag识别错误

### 日志文件

时间：2022.9.15.08.41.55
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9571138/asst.log)

### 截图

<img width="155" alt="捕获" src="https://user-images.githubusercontent.com/101058152/190295365-5b2fdc9b-af05-4efb-b521-02d1c9ffd0bd.PNG">

### 还有别的吗？

无

**Comment by MistEO** [comment]
啥意思？爆发现在就是 4 星了，刻刀加进来了

**Comment by 523548** [comment]
这个我不知道（手动狗头）

**Comment by 523548** [comment]
能不能删下两个评论 @zzyyyl

**Comment by zzyyyl** [comment]
已经 close 了就没事了，issue 是删不掉的
下次注意别不小心点错就行（
