### ISSUE TITLE
基建换班焰尾问题

### ISSUE THREAD

**Issue by yyyy52** [MaaAssistantArknights/MaaAssistantArknights#1848]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

砾进驻制造站制造赤金的同时，将焰尾进驻控制中枢，导致贵金属生产力降低。

### 日志文件

[asst0915.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9572904/asst0915.log)

**Comment by Private233** [comment]
这是你自己臆想出来的把？焰尾的效果并不会影响到砾，所以这个问题不成立

**Comment by yyyy52** [comment]
> 

确实，是我想当然了。不过退一步说，红松骑士团在制造赤金时有避免焰尾入驻控制中枢吗。我粗略的看了一下，“小小的领袖”是和“”左膀右臂“等归为一类处理，也没有对“红松的骑士”特殊的判别。不过既然和砾无关的话就是无关紧要的问题了。
