### ISSUE TITLE
能否添加备选关卡的依次刷取功能

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaAssistantArknights#1851]
### 说说你遇到的问题？

![image](https://user-images.githubusercontent.com/72590023/190394722-8c6eee39-f9fe-4877-90d0-3baabfbb7471.png)
当如此设计时, 可能会出现刷完剩下29理智的情况, 希望此时能接着尝试刷取备选关卡(因为我是半天一登, 12小时后理智就会溢出)

### 有什么好的想法？

让程序在刷完第一个后继续依次往下刷取即可

**Comment by MistEO** [comment]
为此加了个“剩余理智”选项，凑合用吧.jpg
