### ISSUE TITLE
无法正常使用指定材料选项

### ISSUE THREAD

**Issue by LoafSugar** [MaaAssistantArknights/MaaAssistantArknights#1854]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

软件中，无法选择指定材料，每次选完后，点击开始都会默认空白，或者点关卡选择也会跳转到指定材料项目。单独点关卡选择没问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9579790/asst.log)

**Comment by MistEO** [comment]
我试了下确实出现了，但是是偶现的，重启 maa 后就没法再复现了，看了下代码暂时没啥头绪。cc @ABA2396

**Comment by starrin** [comment]
遇到了相同问题，只要点击了软件中任意输入框，指定材料选项都会清空。尝试重启软件后恢复正常

**Comment by woui003woui** [comment]
同样遇到了这个问题，在启动了FIGHT任务后再去修改指定材料，点击输入框指定材料选项会清空。重启后在启动任务之前修改即可正常使用。

**Comment by MC57348** [comment]
我倒是有个设想：
就是把指定次数移入关卡选择当中，同时将关卡选择改成和指定材料一样的格式（只有勾选的时候才会弹出来运行几次），这样同时可以解决保留运行次数的功能。
或者是在指定材料和指定关卡当中加入优先级判断，让用户来做决定

**Comment by LoafSugar** [comment]
抱歉，最近这两天一直忙着写论文，基本没看邮箱，这两个方式都挺不错的，不过我个人更倾向于第一个。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月18日(周日) 晚上9:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 无法正常使用指定材料选项 (Issue #1854)




 
我倒是有个设想：
 就是把指定次数移入关卡选择当中，同时将关卡选择改成和指定材料一样的格式（只有勾选的时候才会弹出来运行几次），这样同时可以解决保留运行次数的功能。
 或者是在指定材料和指定关卡当中加入优先级判断，让用户来做决定

**Comment by MistEO** [comment]
> 我试了下确实出现了，但是是偶现的，重启 maa 后就没法再复现了，看了下代码暂时没啥头绪。cc @ABA2396

各位有啥头绪么（ @et2012 @ABA2396 @zzyyyl

**Comment by et2012** [comment]
我无法复现这个问题，有什么可以稳定复现的方法吗？

**Comment by MistEO** [comment]
没有，完全不知道复现路径 orz，问题出现后会一直可复现，但在重启软件后问题消失

**Comment by MistEO** [comment]
具体现象为：
1. 点击材料框，下拉框弹出
2. 点击任意材料，此时下拉框缩回去了，并正常显示了刚才点击的材料
3. 点击其他任意位置（失去焦点了），这时材料框会被清空

与开始任务，任务后修改等应该没有关系，初步的怀疑可能和 `DropsList_Loaded` 函数有关

**Comment by et2012** [comment]
可以把 ```targetComboBox.LostFocus``` 那一段删掉看看，本意是失去焦点时同步文本内容，可能引起了 bug。

**Comment by MistEO** [comment]
过两天发个版看看还有没有问题了（

**Comment by et2012** [comment]
加 ```targetComboBox.LostFocus``` 的本意是修复这种情况：
- 之前选择了 “源岩”
- 输入 “异铁”，弹出搜索结果后，什么都没选
- 此时下拉框显示的是 “异铁”，但其实选择的仍然是 “源岩”

删掉文本重置逻辑的话，上面这个问题会重新出现。

一些比较流行的前端 UI 的 ```select``` 组件是会自动重置文本的（输入文本了但没选，就重置为上一次的选项对应的文本），
而 ```Windows``` 的 ```ComboBox``` 没有这种逻辑（输入了文本但没选，文本还是用户输入的文本），用户需要习惯一下。
