### ISSUE TITLE
自动公招在勾选使用加急许可时逻辑异常

### ISSUE THREAD

**Issue by Hell-Tractor** [MaaAssistantArknights/MaaAssistantArknights#1856]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动公招前所有公招槽位为空。

自动公招在勾选使用加急许可时，加急许可消耗完毕后直接结束自动公招，未将4个槽位全部使用（后来手动补上忘记截图了故不提供）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9581651/asst.log)

### 截图

![日志截图](https://user-images.githubusercontent.com/32808149/190580625-9f1e17f9-2aa8-42ec-af9b-35aff561f2f1.png)

### 还有别的吗？

模拟器：夜神模拟器 7.0.3.5
操作系统：windows10 专业版 21H2

**Comment by zzyyyl** [comment]
公招逻辑修改好像有点久远了，但应该是 @horror-proton
