### ISSUE TITLE
在基建里面断连一次后不太能恢复, 然后引发一系列奇妙事件导致的奇妙问题

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaAssistantArknights#1857]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在第二个充电站的时候明日方舟说与神经网络失联, 然后退出了, 之后我看时间有点长手动点登陆(这个是不是之前有issue来着), 他自己回到了基建, 然后执行的是宿舍的换班。此时会客室线索全满, 因此在换班的时候会客室干员没有显示为`工作中`, 因此把会客室的人全换下来了, 就造成了会客室是空的的情况。(之前我这也有换完班会客室空了的情况)  
(要不要加一个会客室线索满x就送人y份的设置)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9590494/asst.log)

**Comment by one-pyy** [comment]
另外还有会客室操作完后还没领取当天的线索的情况, 应该是先领线索(已经满了没领成), 然后发现满了送线索?  
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9590514/asst.log)

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
