### ISSUE TITLE
公招识别后程序崩溃退出

### ISSUE THREAD

**Issue by joe-vettek** [MaaAssistantArknights/MaaAssistantArknights#1858]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

程序进行到自动公招，招募完昨天的结果后，我没有票，此时提示我识别出了五星，然后程序就崩溃了。

### 日志文件
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9590635/asst.log)

### 还有别的吗？

模拟器： 蓝叠国际版
操作系统: win10

**Comment by joe-vettek** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9590634/asst.log)

**Comment by joe-vettek** [comment]
我猜测是识别完之后的什么bug。因为我用公招识别界面看了看，结果也崩溃了。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9590640/asst.log)

**Comment by horror-proton** [comment]
好像没有复现出问题, 有当时公招 Tags 界面的截图吗 (没有的话我只能去p一张了

**Comment by joe-vettek** [comment]
我以为log有就没有截图了，不好意思，tag就是log里的，识别完就崩溃了。忘了MAA依赖图像识别。

**Comment by joe-vettek** [comment]
而且有识别结果的话应该不是识别本身的问题叭。我看在日志里已经得到了返回的公招识别可能获得的干员。

**Comment by zzyyyl** [comment]
possibly fixed by https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/973bea20c4e69923c92d9d56d1b7ea692192cbc0
