### ISSUE TITLE
关于晓歌常驻会客室的可能

### ISSUE THREAD

**Issue by Cherrling** [MaaAssistantArknights/MaaAssistantArknights#1859]
### 说说你遇到的问题？

晓歌真的是太强辣！

### 有什么好的想法？

精二晓歌的会客室特性：更容易获得未拥有的线索

那假如当一个玩家同时拥有晓歌的菲亚梅塔时，可否同时借助肥鸭的基建特性，实现晓歌24h会客室常驻？

先将肥鸭置于宿舍恢复至满状态，检测到会客室的晓歌心情低于阈值时，优先利用肥鸭的特性将晓歌的状态交换为满状态，然后后续进行正常的基建排班

**Comment by Cherrling** [comment]
仅以我个人观点，这个可以作为一个附加小项目放到设置里，仅对于同时拥有晓歌和肥鸭的玩家手动开启

**Comment by ABA2396** [comment]
会客室的效率并不高，与其这样的话反而还不如让巫恋007来的更划算

**Comment by zzyyyl** [comment]
自定义基建！
