### ISSUE TITLE
肉鸽莫名卡死

### ISSUE THREAD

**Issue by Genicur** [MaaAssistantArknights/MaaAssistantArknights#1863]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题 卡死后放弃探索

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9593390/asst.zip)
[2022-09-18 16:30:20.413]-[2022-09-18 16:31:46.951]

### 截图

![image](https://user-images.githubusercontent.com/93466263/190893352-de1a8445-5122-400e-ae98-5ee59a97a455.png)

### 还有别的吗？

模拟器环境 蓝叠 5.9.135.1001 P64 1280*720 320DPI
maa版本 4.4.2

**Comment by MistEO** [comment]
卡在哪了？游戏在哪个画面

**Comment by Genicur** [comment]
> 卡在哪了？游戏在哪个画面

我忘记叫什么了 但是记得有个火堆 我等等去查一下

**Comment by dawn23666** [comment]
似乎当前版本在识别截图的时候有点问题，我在roge战斗结算画面，刷理智结算，好像还有个不期而遇画面都崩溃过，4.4.1版本似乎是没有问题的

**Comment by Genicur** [comment]
> 卡在哪了？游戏在哪个画面

这次又被我逮到了 同样的放弃探索
[日记和截图.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9600624/default.zip)
