### ISSUE TITLE
基建换班忽略其他空宿舍

### ISSUE THREAD

**Issue by Genicur** [MaaAssistantArknights/MaaAssistantArknights#1864]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

rt 我发现只换一个宿舍的情况后 尝试复现 但是失败了

### 日志文件

[dorm all.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9593904/dorm.all.log)
上为尝试复现
[dorm 0.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9593907/dorm.0.log)
上为原log

**Comment by MistEO** [comment]
咋关了，还没来得及看呢，最近太忙了 orz

**Comment by MistEO** [comment]
这个问题修了，之后版本看看还有没有
