### ISSUE TITLE
肉鸽卡死后MAA停止工作

### ISSUE THREAD

**Issue by Wu-Yecheng** [MaaAssistantArknights/MaaAssistantArknights#1865]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动刷肉鸽出现卡死后MAA停止工作，windows提示错误强制关闭

### 日志文件

未发现

### 截图

![J6ZD6ZCYKSAFSC3CU0E( 8Q](https://user-images.githubusercontent.com/73373280/190902119-8befa166-1145-4692-b1b5-8a8405a97ca7.png)
![image](https://user-images.githubusercontent.com/73373280/190902129-b95fe9c6-0520-4e67-a71b-1ae7f7fd094e.png)

### 还有别的吗？

蓝叠5国际版

**Comment by MistEO** [comment]
把 MAA 放在个有写权限的文件夹，不然就会有问题

**Comment by Wu-Yecheng** [comment]
> 把 MAA 放在个有写权限的文件夹，不然就会有问题

OK，我试试

**Comment by Wu-Yecheng** [comment]
可以了，谢谢大佬
