### ISSUE TITLE
唤醒任务切换账号功能

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#1870]
### 说说你遇到的问题？

主要是模拟器的多开太占硬盘空间，目前由于maa只支持单账号，我的处理方式是模拟器多开分别登录大号和小号，然后开多个maa示例设置好定时全天候挂机。
如果可以支持切换账号，那么我就可以通过更改gui.json实现只用一个maa控制一个模拟器长草多个账号，或是直接使用python接口之类的。

### 有什么好的想法？

在开始唤醒任务中加入切换账号的功能，具体就是在唤醒界面点账号管理然后输入账号密码，账号密码直接明文放在设置界面我觉得问题不大

### 其他内容

加入这个功能以后假如出现网络连接不稳定导致登录失败“记忆模糊”，maa也可以自动填写账密登录，增加稳定性，对于单账号玩家也有益处

**Comment by JiHongYuan** [comment]
非常需要这个功能

**Comment by yige-yigeren** [comment]
> 有可能会遇到人机验证界面。这对maa来说，是不太可能完成的。

据我所知，隔壁似乎有通过手机算力解决的，而且方舟的验证是滑动解锁，搭配合适的模拟算法似乎不是不可能解开？（毕竟手机无障碍的方式都能解开）

**Comment by ntgmc** [comment]
首先人机验证仅会在重复登录5次以上才会遇到，
其次有关账号的内容具有风险，如果你的账号保存在本地，那被盗号了算谁的，如果上传服务器，那风险更大
感谢您的反馈！
