### ISSUE TITLE
MAA连接不上

### ISSUE THREAD

**Issue by Kulikaka** [MaaAssistantArknights/MaaAssistantArknights#1871]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA无法连接，显示模拟器断开，正在尝试重连后自动闪退

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9599186/asst.log)

### 截图

![微信截图_20220919211322](https://user-images.githubusercontent.com/113911860/191026157-0de9a320-0afb-4175-add9-6e3efe1e0290.png)
![微信截图_20220919211813](https://user-images.githubusercontent.com/113911860/191026425-5c99f1c7-7746-421a-81c8-9178cee2bd35.png)

### 还有别的吗？

*用的蓝叠5，win11操作系统，配置没改过就是让MAA自动连接的

**Comment by zzyyyl** [comment]
`adb server version (41) doesn't match this client (36)`

换个 adb？

**Comment by zzyyyl** [comment]
可以升一下测试版，我稍微改过一些连接的逻辑，不过我觉得对于这种情况大概也没有改善（

**Comment by Kulikaka** [comment]
> 
自己下一个adb么？我之前下过夜神也不行

**Comment by Kulikaka** [comment]
> 可以升一下测试版，我稍微改过一些连接的逻辑，不过我觉得对于这种情况大概也没有改善（

下了个adb手动连了一下，现在ok了~

**Comment by MistEO** [comment]
为啥会闪退啊，你有头猪么 @zzyyyl

**Comment by zzyyyl** [comment]
> 为啥会闪退啊，你有头猪么 @zzyyyl

我不到啊（
闪退好像就这一例？没怎么见其他人报啊（

**Comment by maximazl** [comment]
我的是正常开机以后  maa运行正常，但是再打开UU加速器后，立即报错，模拟器断开，正在尝试重连

**Comment by Calette** [comment]
> 

我也出现闪退了，log是adb server version (41) doesn't match this client (36); killing...，换了个自己下的adb就可以了

**Comment by Calette** [comment]
> > 为啥会闪退啊，你有头猪么 @zzyyyl
> 
> 我不到啊（ 闪退好像就这一例？没怎么见其他人报啊（

我也出现闪退了，log是adb server version (41) doesn't match this client (36); killing...，换了个下的adb就好了
