### ISSUE TITLE
自定义换班菲亚梅塔使用逻辑问题

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#1874]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用菲亚梅塔功能时，菲亚梅塔应该后于被交换心情的干员放入宿舍，但当菲亚梅塔已经在宿舍里的时候，MAA会由于先看见菲亚梅塔，而将菲亚梅塔放在被交换心情的干员前面，从而无法交换心情。
当且仅当菲亚梅塔在干员列表中位于被交换心情的干员之后，才能成功触发交换心情。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9603713/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/30530115/191158313-de5f0d93-5563-4664-81f5-8f1f42482261.png)
菲亚梅塔原本在宿舍中，迷迭香原本在制造站中，重复执行多次皆为此顺序
![image](https://user-images.githubusercontent.com/30530115/191158714-b51ba413-37f6-4d5f-8cae-cd43ba2870f4.png)
MAA界面如图

### 还有别的吗？

使用的模拟器：蓝叠中国版
目前我的曲线救国方案：每次用菲亚之前插入一个临时换班清空宿舍，但此方法过于臃肿，希望该bug能尽早修复

**Comment by Minepig** [comment]
测试用json文件：
```
{
    "plans": [
        {
            "Fiammetta": {
                "target": "迷迭香"
            },
            "drones": {
                "room": "manufacture",
                "index": 1
            },
            "rooms": {
            }
        }
    ]
}

```

**Comment by Minepig** [comment]
附带一个优化建议：当前版本下菲亚梅塔如果不在休息，那么在按技能降序排序时，一定在第一个，因此可以先按心情升序，找到要交换心情的干员，然后按技能降序，选取菲亚梅塔，此时如果检测到第一个干员不是菲亚梅塔，认为菲亚梅塔没有满心情，弹出警告

**Comment by MistEO** [comment]
昨晚的 a3 版本修了
