### ISSUE TITLE
自定义换班 宿舍用autofill不填额外补人

### ISSUE THREAD

**Issue by Fuynkio** [MaaAssistantArknights/MaaAssistantArknights#1877]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自定义换班走到宿舍的时候，不会填其他人
想法是 
一号宿舍用“杜林”+4个低心情
二号宿舍用”安比尔“+低心情
`                        "operators": [
                            "杜林"
                        ],
                        "autofill": true`
代码大致长这样
结果是 宿舍里只有杜林 安比尔 没有低心情的干员

### 日志文件

[Uploading asst.log…]()

### 截图

宿舍截图
![image](https://user-images.githubusercontent.com/50935992/191164754-45c7ae30-985c-4dec-b320-0887041fef0a.png)
代码部分
![image](https://user-images.githubusercontent.com/50935992/191164873-94f19d36-5903-48af-8160-dd88594f214e.png)
MAA部分
![image](https://user-images.githubusercontent.com/50935992/191164916-7c790a41-d075-420c-acf4-941067fce797.png)

**Comment by Fuynkio** [comment]
哦对 制造厂用autofill好像会把休息的人拉进去上班 但是我已经排完了 不想改了（

**Comment by MistEO** [comment]
fixed
