### ISSUE TITLE
运行时闪退BUG，极难复现

### ISSUE THREAD

**Issue by LET-max** [MaaAssistantArknights/MaaAssistantArknights#1879]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在4.4.0版本中使用MAA并无出现闪退情况，可能更新至4.4.1或4.4.2后出现的闪退BUG，最新测试版本并无显示修复情况。

在定时自动操作中可能复现，程序以每8小时定时运行一次设定的操作，这几天都有闪退现象，目前正在尝试最新测试版，已尝试的解决方案有：更新程序、删除程序并下载完整包、卸载并重新安装模拟器（蓝叠国际版）、在模拟器Gui.json中添加检测端口号的小后门（4.4.0之前并不需要检测端口号？（存疑））、安装程序所需运行库。

查看日志文件，在8点启动定时操作时程序闪退，模拟器页面停留在基建-选人界面。2022-09-20 08:05:40.476

在我编写BUG汇报时又闪退了一次，太棒力。这次模拟器页面还是停留在基建-宿舍界面（2022-09-20 16:30:43.724

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9605693/asst.log)

### 截图

![5{5FDV U9AWE H23(FG0_G6](https://user-images.githubusercontent.com/61637276/191213488-969607a1-0ef2-4087-a421-3c2dc09b91e9.png)这是编写BUG汇报时软件闪退时的截图

### 还有别的吗？

蓝叠模拟器国际版 Hyper-V版本

版本	Windows 11 专业版
版本	21H2
安装日期	‎2022/‎9/‎11
操作系统版本	22000.978
体验	Windows 功能体验包 1000.22000.978.0

设备名称	EVANGELION-MAGI
处理器	AMD Ryzen 5 3600 6-Core Processor                 3.60 GHz
显示卡	AMD  Radeon RX 6700XT
机带 RAM	16.0 GB
设备 ID	
产品 ID	
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

曾因为固态硬盘原因重新恢复过官方原本ISO系统，但是自行备份且恢复了数据，应该没有影响

检查可靠性历史记录，MAA有BEX64及CLR20r3的问题事件名称，这也许能够帮上一点忙

**Comment by horror-proton** [comment]
可靠性历史记录里面应该有个详细信息之类的表格, 能贴一下吗 (不知道会不会有用

**Comment by LET-max** [comment]
> 历史记录里面应该有详细信息之类的表格，能贴一下吗（不知道不会有用）

区区小事，何足挂齿（

问题事件名称:	BEX64
应用程序名:	MeoAsstGui.exe
应用程序版本:	1.0.0.0
应用程序时间戳:	8500d333
故障模块名称:	MeoAssistant.dll
故障模块版本:	0.0.0.0
故障模块时间戳:	63275198
异常偏移:	000000000010da71
异常代码:	c0000409
异常数据:	0000000000000007
OS 版本:	10.0.22000.2.0.0.256.48
区域设置 ID:	2052
其他信息 1:	eff8
其他信息 2:	eff8e83985ec160480eac615f4910f44
其他信息 3:	d660
其他信息 4:	d660b9b8c556b2c7d747cbc358883663

问题事件名称:	CLR20r3
问题签名 01:	MeoAsstGui.exe
问题签名 02:	1.0.0.0
问题签名 03:	8500d333
问题签名 04:	MeoAsstGui
问题签名 05:	1.0.0.0
问题签名 06:	8500d333
问题签名 07:	25
问题签名 08:	1d
问题签名 09:	RML5K4UDBMA5NI04CIYRWVDHKEWFDHCV
OS 版本:	10.0.22000.2.0.0.256.48
区域设置 ID:	2052
其他信息 1:	fd57
其他信息 2:	fd57ddb027d3046f7fa46e1025ca4425
其他信息 3:	9037
其他信息 4:	90377b8556a931efac0606a224c15521

问题事件名称:	CLR20r3
问题签名 01:	MeoAsstGui.exe
问题签名 02:	1.0.0.0
问题签名 03:	8500d333
问题签名 04:	MeoAsstGui
问题签名 05:	1.0.0.0
问题签名 06:	8500d333
问题签名 07:	25
问题签名 08:	1d
问题签名 09:	RML5K4UDBMA5NI04CIYRWVDHKEWFDHCV
OS 版本:	10.0.22000.2.0.0.256.48
区域设置 ID:	2052
其他信息 1:	fd57
其他信息 2:	fd57ddb027d3046f7fa46e1025ca4425
其他信息 3:	9037
其他信息 4:	90377b8556a931efac0606a224c15521

问题事件名称:	BEX64
应用程序名:	MeoAsstGui.exe
应用程序版本:	1.0.0.0
应用程序时间戳:	c5e64ccc
故障模块名称:	MeoAssistant.dll
故障模块版本:	0.0.0.0
故障模块时间戳:	6322e5d7
异常偏移:	00000000001098d1
异常代码:	c0000409
异常数据:	0000000000000007
OS 版本:	10.0.22000.2.0.0.256.48
区域设置 ID:	2052
其他信息 1:	8810
其他信息 2:	88102a644cb04d02849b7cc71be74cfb
其他信息 3:	354b
其他信息 4:	354b039a4fc057d8476fb8b3b22e1707
