### ISSUE TITLE
怎么改干员默认带的技能呀，选煌还是山都是带的一技能

### ISSUE THREAD

**Issue by Ga1en70** [MaaAssistantArknights/MaaAssistantArknights#188]
是没有专门的字段去选这个吗

**Comment by MistEO** [comment]
没有_(:з」∠)_本质上是挂机的刷源石锭和蜡烛的，也没指望打到多后面，所以效率还凑合就行了

**Comment by B14ck0ut** [comment]
> 

如果只是刷源石锭和蜡烛可以考虑一些稳定的单核打法比如山，水陈，令之类的，就可以完全不用管后续拿干员和摆放的问题了，光用一开始的三个干员也能无压力打穿前两图，节省不少工作量

**Comment by MistEO** [comment]
> > 
> 
> 如果只是刷源石锭和蜡烛可以考虑一些稳定的单核打法比如山，水陈，令之类的，就可以完全不用管后续拿干员和摆放的问题了，光用一开始的三个干员也能无压力打穿前两图，节省不少工作量

打古堡观光模式，当前就是可以稳定打穿第一层的，默认配置文件里的干员都是自动技能，适合当前的策略使用的
