### ISSUE TITLE
请求增加新功能：Box导出

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#1890]
### 说说你遇到的问题？

在和其他人分享box的时候，以截图格式分享的信息量较小。
是否能够生成Excel / csv格式导出所持有的干员信息（或者导出总干员表，在里面添一个标志位来表示持有

### 有什么好的想法？

举个例子
星级|代号|精英|等级
6|年|精2|90
6|泥岩|精0|0（0级代表未获得，或者单独设置标志位）

稀有度|代号|精英|等级|技能(数字代表常规等级，中文是专精)
6|夕|精2|90|7三7

稀有度|代号|精英|等级|技能|模组
6|令|精2|90|三三三|03（X模0级）（Y模3级）

**Comment by MistEO** [comment]
有计划了，但是这玩意分享有啥用

**Comment by status102** [comment]
> 有计划了，但是这玩意分享有啥用
> 
> #1855

比如抽卡规划，养成资源消耗计算？json格式感觉只能当做原始数据，有时候想问别人xx池子抽不抽的时候得截图3~4张，感觉挺麻烦的

**Comment by MistEO** [comment]
作为协议来说，方便人阅读和健壮性本身是冲突的，我觉得 maa core 作为一个偏底层的东西，健壮性是首要满足的，1 楼这种类似的格式不够合理；而且既然是方便人阅读，自然是带干员头像的图片这种更加合理，所以我突发奇想，或许我们可以和其他网站 or bot 合作：

比如输入 maa 导出的 json，生成一张包含每个干员头像缩略图 + 精英化、等级等信息的图片。

大佬们有没有兴趣来波联动（ @vivien8261 @Tsuk1ko
或者直接我们新 ui cover 掉 @ChingCdesu @bakashigure 

json 格式参考 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1855

**Comment by vivien8261** [comment]
> 作为协议来说，方便人阅读和健壮性本身是冲突的，我觉得 maa core 作为一个偏底层的东西，健壮性是首要满足的，1 楼这种类似的格式不够合理；而且既然是方便人阅读，自然是带干员头像的图片这种更直观，所以我突发奇想，或许我们可以和其他网站 or bot 合作：
> 
> 比如输入 maa 导出的 json，生成一张包含每个干员头像缩略图 + 精英化、等级等信息的图片。
> 
> 大佬们有没有兴趣来波联动（ @vivien8261 @Tsuk1ko 或者直接我们新 ui cover 掉 @ChingCdesu @bakashigure
> 
> json 格式参考 #1855

很棒的想法，此前我有做过生成练度图的项目，但苦于需要手动输入放弃了。如果能通过现成的数据生成那实在是太简单了。

**Comment by status102** [comment]
> 作为协议来说，方便人阅读和健壮性本身是冲突的，我觉得 maa core 作为一个偏底层的东西，健壮性是首要满足的，1 楼这种类似的格式不够合理；而且既然是方便人阅读，自然是带干员头像的图片这种更直观，所以我突发奇想，或许我们可以和其他网站 or bot 合作：
> 
> 比如输入 maa 导出的 json，生成一张包含每个干员头像缩略图 + 精英化、等级等信息的图片。
> 
> 大佬们有没有兴趣来波联动（ @vivien8261 @Tsuk1ko 或者直接我们新 ui cover 掉 @ChingCdesu @bakashigure
> 
> json 格式参考 #1855

如果是bot处理数据的话，json对于bot来说会不会过长。之前看mirai的文档好像是限制4k5个字符。有没有可能做的更加紧凑，比如
```
//ID,精英,等级,技能1,技能2,技能3,模组1,模组2 
172,2,90,7,7,7
```
代表172干员精二技能全7，无模组/未解锁模组

**Comment by Tsuk1ko** [comment]
感觉这个功能跟 bot 比较契合？在网页工具箱上生成好像意义不是很大（

例如原神 [yunzai bot](https://github.com/Le-niao/Yunzai-Bot) 的 [miao plugin](https://github.com/yoimiya-kokomi/miao-plugin)

<details>
 <summary>图</summary>

![3A70EB68123CB3F972B0F87064C7B6B6](https://user-images.githubusercontent.com/24877906/191430638-1ef104c9-adb7-42e5-b428-9be7c02f7d63.jpg)
</details>

> 如果是bot处理数据的话，json对于bot来说会不会过长

这个倒是可以通过发送文件的方式解决

**Comment by status102** [comment]
> 感觉这个功能跟 bot 比较契合？在网页工具箱上生成好像意义不是很大（
> 
> 例如原神 [yunzai bot](https://github.com/Le-niao/Yunzai-Bot) 的 [miao plugin](https://github.com/yoimiya-kokomi/miao-plugin)
> 
> <details>
>  <summary>图</summary>
> 
> ![3A70EB68123CB3F972B0F87064C7B6B6](https://user-images.githubusercontent.com/24877906/191430638-1ef104c9-adb7-42e5-b428-9be7c02f7d63.jpg)
> </details>
> 
> > 如果是bot处理数据的话，json对于bot来说会不会过长
> 
> 这个倒是可以通过发送文件的方式解决

还能这样实现，感谢
