### ISSUE TITLE
自定义基建在发电站和办公室选中干员之后又清空

### ISSUE THREAD

**Issue by Suprelorry** [MaaAssistantArknights/MaaAssistantArknights#1891]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自定义基建使用内置顶配排班时，在发电站和办公室均出现如下问题：查找并选中了相应所需干员，滑动回到干员列表前端，继续滑动两下，到这里都没问题，但是接下来maa会清空已选中的干员并确认，然后退出当前发电站或办公室，进行下一步操作，导致任务完成时，发电站和办公室都是空置的。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9613477/asst.log)

### 还有别的吗？

使用的夜神模拟器，操作系统是win10，早上已出现过同样的问题，但由于使用的不是同一台电脑，所以上传的asst.log文件中可能只有中午12点排班时出现问题的记录

**Comment by MistEO** [comment]
> 查找并选中了相应所需干员，滑动回到干员列表前端，继续滑动两下，到这里都没问题

这里接下来是点 “清空” 按钮，然后重新选人（用于按配置文件中的顺序排序），我忘了发电站和办公室没有 “清空” 按钮，而且只有一个人也没必要重新排序，今天应该会改一下重新发一版

**Comment by Suprelorry** [comment]
> > 查找并选中了相应所需干员，滑动回到干员列表前端，继续滑动两下，到这里都没问题
> 
> 这里接下来是点 “清空” 按钮，然后重新选人（用于按配置文件中的顺序排序），我忘了发电站和办公室没有 “清空” 按钮，而且只有一个人也没必要重新排序，今天应该会改一下重新发一版

好的，辛苦了
