### ISSUE TITLE
基建自定义换班把人全撤了

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#1898]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我也不知道发生了啥，反正MAA把我制造站里的人，除了1号站，之后全撤了
![image](https://user-images.githubusercontent.com/30530115/191568062-6a729e2b-77e0-408c-81da-da86e648dc28.png)
一个猜想：大概是没有更新某个数组下标的值？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9618932/asst.log)

**Comment by MistEO** [comment]
你更新的好快，b1 因为这个撤包了，b2 修了，再更下吧~

**Comment by Minepig** [comment]
我刚发完就看到release了（捂脸
