### ISSUE TITLE
基建自定义换班协议给每个设施加入ordered字段

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#1900]
### 说说你遇到的问题？

在某些情况下，MAA选完人会因为划不到最左边而没法重新给人排序，导致该设施被清空
常见出现于宿舍，因为已经在宿舍休息的人会在按心情排序时被放到最后面，设想我需要在换班的时候保留宿舍中两个仍在回复心情的干员，替换剩余三个已经恢复完成的干员，那么在MAA清空选择然后重新排序的时候，仍在回复心情的干员会被放到最后，MAA需要划过整个干员列表才能找到那两个人，非常费时间，最后还会因为划四下划不回去把整个设施清掉
典型案例是菲亚梅塔的使用：菲亚梅塔使用完后会在宿舍恢复心情，此时再给宿舍排班菲亚梅塔就会放到最后面去
此外，如果在排班表里面写入一些填充用的刷信赖干员（不使用autofill是因为autofill会把令姐塞进宿舍，我要控制令姐的心情不高于12），这些干员也会处于比较靠后的位置，触发类似的问题

### 有什么好的想法？

首先可以在清空以后，重新排序之前，先做一次ocr并选择干员，把原本就在设施里的人先选上，这样应该可以规避掉一部分问题
然后关于放信赖人导致的问题，根本原因还是因为连续划四下划不到头
如果单纯增加划动次数感觉有点蠢，也会增加耗时
不如给设施加个ordered字段，默认false，如果为false就选完人就确认，如果为true，就像现在这样在重排一遍，也能省下一些时间，因为必须要排好序的情况应该挺少的

**Comment by MistEO** [comment]
好主意
