### ISSUE TITLE
加一个操作延迟检测功能（？

### ISSUE THREAD

**Issue by nightofknife** [MaaAssistantArknights/MaaAssistantArknights#1901]
### 说说你遇到的问题？

在作业群里反馈的作业失败原因中，操作延迟的不同导致的作业失败次数是最多的（比如开局放干员要求比较快，或者有卡轴需求的时候）
虽然挂机作业能在一定程度上减少问题的产生，但是挂机作业有时候也会有开局快速放干员的情况
这个时候 高延迟 的用户使用 低延迟 情况下写出来的作业就往往会失败，
或许可以用个办法检测一下大致的操作延迟，把制作作业时的延迟写进作业文件里面（或者提供一个延迟选项比如 1s 2s 这种）
用户就可以自己看着自己的操作延迟选择对应的作业，减少因为MAA操作延迟导致的抄作业失败
PS：都慢这样了为什么不自己抄（怒

### 有什么好的想法？

无实现思路
纯胡思乱想

**Comment by zzyyyl** [comment]
其实操作延迟简单检测 screencap 的延迟就好了（
