### ISSUE TITLE
部分设施skip依旧有小问题

### ISSUE THREAD

**Issue by MigdalBavel** [MaaAssistantArknights/MaaAssistantArknights#1905]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

4.5.0-beta2
自定义基建，目前碰到控制中枢、第一个电站、办公室在设置skip情况下还是会点进人员列表里一遍，虽然不至于像以前一样换空了。
贸易制造站的skip目前正常。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9624050/asst.log)

**Comment by MistEO** [comment]
从日志看你的 json 内容：

<details>
```json
{
    "description": "干员配置要求极高，请留意\n若缺少干员请自行拷贝文件并修改（请勿直接修改，以免更新后被覆盖）\n\n作业作者：MistEO\n感谢公孙长乐大佬提供数据及方案支持！",
    "title": "243 极限效率，一天三换",
    "plans": [
        {
            "name": "A+B 组",
            "description": "最高效率长班\n下次换班请在约16小时后进行",
            "rooms": {
                "power": [
                    {
                        "operators": [
                            "澄闪"
                        ]
                    },
                    {
                        "operators": [
                            "格雷伊"
                        ]
                    },
                    {
                        "operators": [
                            "雷蛇"
                        ]
                    }
                ],
                "control": [
                    {
                        "operators": [
                            "阿米娅",
                            "玛恩纳",
                            "暴雨",
                            "清道夫",
                            "临光"
                        ]
                    }
                ],
                "meeting": [
                    {
                        "operators": [
                            "远山",
                            "塞雷娅"
                        ]
                    }
                ],
                "manufacture": [
                    {
                        "skip": true,
                        "product": "Battle Record"
                    },
                    {
                        "operators": [
                            "断罪者",
                            "红豆",
                            "Castle-3"
                        ],
                        "product": "Battle Record"
                    },
                    {
                        "skip": true,
                        "product": "Pure Gold"
                    },
                    {
                        "operators": [
                            "斑点",
                            "夜烟",
                            "白面鸮"
                        ],
                        "product": "Pure Gold"
                    }
                ],
                "trading": [
                    {
                        "skip": true,
                        "product": "LMD"
                    },
                    {
                        "operators": [
                            "拉普兰德",
                            "德克萨斯",
                            "孑"
                        ],
                        "product": "LMD"
                    }
                ],
                "hire": [
                    {
                        "skip": true
                    }
                ],
                "dormitory": [
                    {
                        "operators": [
                            "阿",
                            "布丁",
                            "陈",
                            "惊蛰",
                            "杜宾"
                        ]
                    },
                    {
                        "operators": [
                            "泡普卡",
                            "石棉",
                            "暗索",
                            "杰西卡",
                            "蛇屠箱"
                        ]
                    },
                    {
                        "operators": [
                            "黑角",
                            "能天使",
                            "正义骑士号",
                            "阿消",
                            "红云"
                        ]
                    },
                    {
                        "operators": [
                            "古米",
                            "空爆",
                            "THRM-EX"
                        ]
                    }
                ]
            }
        },
        {
            "name": "B+Y 组",
            "description": "次高效替补 1 班\n下次换班请在约4小时后进行",
            "rooms": {
                "power": [
                    {
                        "skip": true
                    },
                    {
                        "skip": true
                    },
                    {
                        "skip": true
                    }
                ],
                "control": [
                    {
                        "skip": true
                    }
                ],
                "meeting": [
                    {
                        "operators": [
                            "暗索",
                            "塞雷娅"
                        ]
                    }
                ],
                "manufacture": [
                    {
                        "operators": [
                            "断罪者",
                            "红豆",
                            "Castle-3"
                        ],
                        "product": "Battle Record"
                    },
                    {
                        "operators": [
                            "杰西卡",
                            "泡普卡",
                            "石棉"
                        ],
                        "product": "Battle Record"
                    },
                    {
                        "operators": [
                            "斑点",
                            "夜烟",
                            "白面鸮"
                        ],
                        "product": "Pure Gold"
                    },
                    {
                        "operators": [
                            "黑角",
                            "蛇屠箱",
                            "红云"
                        ],
                        "product": "Pure Gold"
                    }
                ],
                "trading": [
                    {
                        "operators": [
                            "拉普兰德",
                            "德克萨斯",
                            "孑"
                        ],
                        "product": "LMD"
                    },
                    {
                        "operators": [
                            "能天使",
                            "空爆",
                            "古米"
                        ],
                        "product": "LMD"
                    }
                ],
                "hire": [
                    {
                        "operators": [
                            "伊桑"
                        ]
                    }
                ],
                "dormitory": [
                    {
                        "operators": [
                            "巫恋",
                            "龙舌兰",
                            "柏喙",
                            "远山",
                            "艾雅法拉"
                        ]
                    },
                    {
                        "operators": [
                            "流明",
                            "白雪",
                            "食铁兽",
                            "砾",
                            "清流"
                        ]
                    },
                    {
                        "operators": [
                            "霜叶",
                            "香草"
                        ]
                    },
                    {
                        "skip": true
                    }
                ]
            }
        },
        {
            "name": "A+Y 组",
            "description": "次高效替补 2 班\n下次换班请在约4小时后进行",
            "period": [
                [
                    "12:30",
                    "15:58"
                ]
            ],
            "rooms": {
                "power": [
                    {
                        "operators": [
                            "正义骑士号"
                        ]
                    },
                    {
                        "operators": [
                            "THRM-EX"
                        ]
                    },
                    {
                        "operators": [
                            "阿消"
                        ]
                    }
                ],
                "control": [
                    {
                        "operators": [
                            "布丁",
                            "陈",
                            "杜宾",
                            "阿",
                            "惊蛰"
                        ]
                    }
                ],
                "meeting": [
                    {
                        "operators": [
                            "远山",
                            "暗索"
                        ]
                    }
                ],
                "manufacture": [
                    {
                        "operators": [
                            "霜叶",
                            "白雪",
                            "食铁兽"
                        ],
                        "product": "Battle Record"
                    },
                    {
                        "skip": true,
                        "product": "Battle Record"
                    },
                    {
                        "operators": [
                            "砾",
                            "清流",
                            "香草"
                        ],
                        "product": "Pure Gold"
                    },
                    {
                        "skip": true,
                        "product": "Pure Gold"
                    }
                ],
                "trading": [
                    {
                        "operators": [
                            "巫恋",
                            "龙舌兰",
                            "柏喙"
                        ],
                        "product": "LMD"
                    },
                    {
                        "skip": true,
                        "product": "LMD"
                    }
                ],
                "hire": [
                    {
                        "operators": [
                            "艾雅法拉"
                        ]
                    }
                ],
                "dormitory": [
                    {
                        "operators": [
                            "流明",
                            "德克萨斯",
                            "断罪者",
                            "玛恩纳",
                            "暴雨"
                        ]
                    },
                    {
                        "operators": [
                            "阿米娅",
                            "临光",
                            "清道夫",
                            "塞雷娅",
                            "澄闪"
                        ]
                    },
                    {
                        "operators": [
                            "格雷伊",
                            "雷蛇",
                            "斑点",
                            "夜烟",
                            "白面鸮"
                        ]
                    },
                    {
                        "operators": [
                            "Castle-3",
                            "红豆",
                            "伊桑",
                            "孑",
                            "拉普兰德"
                        ]
                    }
                ]
            }
        }
    ]
}
```
</details>

其中三个方案，没有办公室 skip 的，发电站仅有 plan_index = 1 是 skip 的，index 0 和 2 都没有 skip

从日志添加的任务来看

```log
[2022-09-22 12:51:16.277][INF][Px2668][Tx4b3c] asst::Assistant::append_task Infrast {"facility":["Control","Trade","Mfg","Power","Reception","Office","Dorm"],"drones":"CombatRecord","threshold":0.0,"dorm_notstationed_enabled":true,"drom_trust_enabled":false,"replenish":false,"mode":10000,"filename":"G:\\ArkNigga\\resource\\custom_infrast\\243.json","plan_index":2}

[2022-09-22 12:57:03.521][INF][Px2668][Tx4b3c] asst::Assistant::append_task Infrast {"facility":["Dorm"],"drones":"CombatRecord","threshold":0.0,"dorm_notstationed_enabled":true,"drom_trust_enabled":false,"replenish":false,"mode":10000,"filename":"G:\\ArkNigga\\resource\\custom_infrast\\243.json","plan_index":2}

[2022-09-22 16:07:21.218][INF][Px3c6c][Tx4a34] asst::Assistant::append_task Infrast {"facility":["Control","Trade","Mfg","Power","Office","Reception"],"drones":"CombatRecord","threshold":0.0,"dorm_notstationed_enabled":true,"drom_trust_enabled":false,"replenish":false,"mode":10000,"filename":"G:\\ArkNigga\\resource\\custom_infrast\\243.json","plan_index":0}

[2022-09-22 16:15:43.506][INF][Px3c6c][Tx4a34] asst::Assistant::append_task Infrast {"facility":["Dorm"],"drones":"CombatRecord","threshold":0.0,"dorm_notstationed_enabled":true,"drom_trust_enabled":false,"replenish":false,"mode":10000,"filename":"G:\\ArkNigga\\resource\\custom_infrast\\243.json","plan_index":0}
```

plan_index 只设置过 0 和 2 的，都是没有 skip 的啊

**Comment by MigdalBavel** [comment]
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9624313/asst.bak.log)
奥，我上午换过一次更新了，记录在bak里面。
`{
    "title": "243 极限效率，一天三换",
    "description": "干员配置要求极高，请留意\n若缺少干员请自行拷贝文件并修改（请勿直接修改，以免更新后被覆盖）\n\n作业作者：MistEO\n感谢公孙长乐大佬提供数据及方案支持！",
    "plans": [
        {
            "name": "A+B 组",
            "description": "最高效率长班\n下次换班请在约16小时后进行",
            "rooms": {
                "control": [
                    {
                        "operators": [
                            "阿米娅",
                            "玛恩纳",
                            "暴雨",
                            "清道夫",
                            "临光"
                        ]
                    }
                ],
                "trading": [
                    {
                        "skip": true,
                        "product": "LMD"
                    },
                    {
                        "operators": [
                            "拉普兰德",
                            "德克萨斯",
                            "孑"
                        ],
                        "product": "LMD"
                    }
                ],
                "manufacture": [
                    {
                        "skip": true,
                        "product": "Battle Record"
                    },
                    {
                        "operators": [
                            "断罪者",
                            "红豆",
                            "Castle-3"
                        ],
                        "product": "Battle Record"
                    },
                    {
                        "skip": true,
                        "product": "Pure Gold"
                    },
                    {
                        "operators": [
                            "斑点",
                            "夜烟",
                            "白面鸮"
                        ],
                        "product": "Pure Gold"
                    }
                ],
                "power": [
                    {
                        "operators": [
                            "澄闪"
                        ]
                    },
                    {
                        "operators": [
                            "格雷伊"
                        ]
                    },
                    {
                        "operators": [
                            "雷蛇"
                        ]
                    }
                ],
                "hire": [
                    {
                        "skip": true
                    }
                ],
                "meeting": [
                    {
                        "operators": [
                            "远山",
							"塞雷娅"
                        ]
                    }
                ],
                "dormitory": [
                    {
                        "operators": [
                            "阿",
                            "布丁",
							"陈",
							"惊蛰",
							"杜宾"
                        ]
                    },
                    {
                        "operators": [
                            "泡普卡",
                            "石棉",
							"暗索",
							"杰西卡",
							"蛇屠箱"
                        ]
                    },
                    {
                        "operators": [
                            "黑角",
                            "能天使",
							"正义骑士号",
							"阿消",
							"红云"
                        ]
                    },
                    {
                        "operators": [
                            "古米",
                            "空爆",
							"THRM-EX"
                        ]
                    }
                ]
            }
        },
        {
            "name": "B+Y 组",
            "description": "次高效替补 1 班\n下次换班请在约4小时后进行",
            "rooms": {
                "control": [
                    {
                        "skip": true 
                    }
                ],
                "trading": [
                    {
                        "operators": [
                            "拉普兰德",
                            "德克萨斯",
                            "孑"
                        ],
                        "product": "LMD"
                    },
                    {
						"operators": [
                            "能天使",
                            "空爆",
                            "古米"
                        ],                        
                        "product": "LMD"
                    }
                ],
                "manufacture": [
                    {
                        "operators": [
                            "断罪者",
                            "红豆",
                            "Castle-3"
                        ],
                        "product": "Battle Record"
                    },
                    {
                        "operators": [
                            "杰西卡",
                            "泡普卡",
                            "石棉"
                        ],
						"product": "Battle Record"
                    },
                    {
                        "operators": [
                            "斑点",
                            "夜烟",
                            "白面鸮"
                        ],
                        "product": "Pure Gold"
                    },
                    {
                        "operators": [
                            "黑角",
                            "蛇屠箱",
                            "红云"
                        ], 
                        "product": "Pure Gold"
                    }
                ],
                "power": [
                    {
                        "skip": true
                    },
                    {
                        "skip": true
                    },
                    {
						"skip": true
                    }
                ],
                "hire": [
                    {
                        "operators": [
                            "伊桑"
                        ]
                    }
                ],
                "meeting": [
                    {
                        "operators": [
                            "暗索",
							"塞雷娅"
							]
                    }
                ],
                "dormitory": [
                    {
                        "operators": [
                            "巫恋",
                            "龙舌兰",
                            "柏喙",
							"远山",
							"艾雅法拉"
                        ]
                    },
                    {
                        "operators": [
                            "流明",
                            "白雪",
                            "食铁兽",
							"砾",
							"清流"
                        ]
                    },
                    {
                        "operators": [
                            "霜叶",
                            "香草"
						]
                    },
                    {
                        "skip": true
                    }
                ]
            }
        },		
        {
            "name": "A+Y 组",
            "description": "次高效替补 2 班\n下次换班请在约4小时后进行",
			"period": [          
                [
                    "12:30",        
                    "15:58"
                ]
            ],
            "rooms": {
                "control": [
                    {
                        "operators": [
                            "布丁",
                            "陈",
                            "杜宾",
                            "阿",
                            "惊蛰"
                        ]
                    }
                ],
                "trading": [
                    {
                        "operators": [
                            "巫恋",
                            "龙舌兰",
                            "柏喙"
                        ],
                        "product": "LMD"
                    },
                    {
                        "skip": true,
                        "product": "LMD"
                    }
                ],
                "manufacture": [
                    {
                        "operators": [
                            "霜叶",
                            "白雪",
                            "食铁兽"
                        ],
                        "product": "Battle Record"
                    },
                    {
                        "skip": true,
                        "product": "Battle Record"
                    },
                    {
                        "operators": [
                            "砾",
                            "清流",
                            "香草"
                        ],
                        "product": "Pure Gold"
                    },
                    {
                        "skip": true,
                        "product": "Pure Gold"
                    }
                ],
                "power": [
                    {
                        "operators": [
                            "正义骑士号"
                        ]
                    },
                    {
                        "operators": [
                            "THRM-EX"
                        ]
                    },
                    {
                        "operators": [
                            "阿消"
                        ]
                    }
                ],
                "hire": [
                    {
                        "operators": [
                            "艾雅法拉"
							]
                    }
                ],
                "meeting": [
                    {
                        "operators": [
                            "远山",
							"暗索"
                        ]
                    }
                ],
                "dormitory": [
                    {
                        "operators": [
                            "流明",
                            "德克萨斯",
							"断罪者",
							"玛恩纳",
							"暴雨"
                        ]
                    },
                    {
                        "operators": [
                            "阿米娅",
                            "临光",
							"清道夫",
							"塞雷娅",
							"澄闪"
							]
                    },
                    {
                        "operators": [
                            "格雷伊",
                            "雷蛇",
							"斑点",
							"夜烟",
							"白面鸮"
							]
                    },
                    {
                        "operators": [
                            "Castle-3",
                            "红豆",
							"伊桑",
							"孑",
							"拉普兰德"
							]
                    }
                ]
            }
        }
    ]
}
`
目前配置是这样，10点左右换的B+Y的，然后13点A+Y，最后16点A+B

**Comment by MistEO** [comment]
看晕了，几次开始的作业都不一样。帮忙用你最新的作业重新抓一份吧

**Comment by MigdalBavel** [comment]
哦好我清空下日志专门用个配置试一下

**Comment by MigdalBavel** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9624418/asst.log)


```
{
    "title": "全skip",
    "description": "全skip",
    "plans": [
        {
            "name": "skip",
            "description": "skip",
            "rooms": {
                "control": [
                    {
                        "skip": true
                    }
                ],
                "trading": [
                    {
                        "skip": true
                    },
                    {
                        "skip": true
                    }
                ],
                "manufacture": [
                    {
                        "skip": true
                    },
                    {
                        "skip": true
                    },
                    {
                        "skip": true
                    },
                    {
                        "skip": true
                    }
                ],
                "power": [
                    {
                        "skip": true
                    },
                    {
                        "skip": true
                    },
                    {
                        "skip": true
                    }
                ],
                "hire": [
                    {
                        "skip": true
                    }
                ],
                "meeting": [
                    {
                        "skip": true
                    }
                ],
                "dormitory": [
                    {
                        "skip": true
                    },
                    {
                        "skip": true
                    },
                    {
                        "skip": true
                    },
                    {
                        "skip": true
                    }
                ]
            }
        }
    ]
}
```


用的全skip的配置

然后观察下来是：
控制中枢、办公室、第一个电站、第一间宿舍还是会点进设施，然后点进人员再排序重勾选一遍
会客室还是会进去收线索什么的（话说能否会客室加个是否进行线索操作的选项（
贸易站、制造站还是会点进设施，但不会再点进人员

**Comment by MigdalBavel** [comment]
阿不对，第一间宿舍点进去把人都换空了，和以前的问题一样。刚才发现。然后跳过了其他宿舍。
