### ISSUE TITLE
希望能分别指定贸易站和制造站的无人机加速

### ISSUE THREAD

**Issue by CaoMeiYouRen** [MaaAssistantArknights/MaaAssistantArknights#1910]
### 说说你遇到的问题？

如果无人机全加速制造站的话，那么赤金会过多
如果无人机全加速贸易站的话，那么订单会过多

### 有什么好的想法？

希望能分别指定加速的无人机的量，以平衡生产线。

**Comment by Minepig** [comment]
可以考虑一下使用自定义基建换班，如果不想亲自排可以所有设施全部填上autofill: true，在无人机条目中可以具体指定本次换班的无人机给哪个设施

**Comment by CaoMeiYouRen** [comment]
谢谢，我看下
