### ISSUE TITLE
自定义基建的歧义输出

### ISSUE THREAD

**Issue by lhhxxxxx** [MaaAssistantArknights/MaaAssistantArknights#1911]
自定义基建在换完当前组的班后，会自动切换下一组，并输出下一组的描述
例如当前为a+b组，应当在16小时后换班，但结束后自动切换至a+y时会输出a+y的描述“下次换班请在约4小时后进行”，引起歧义

**Comment by MistEO** [comment]
干嘛 assign 给我（

**Comment by lhhxxxxx** [comment]
思路：改成duration字段，此后加定时功能时可沿用

**Comment by lhhxxxxx** [comment]
方案：内置作业去除“下次换班请在约x小时后进行”一句，添加duration字段，gui根据该字段额外输出：
开启应用/切换方案时输出该队工作时间；换班完成自动切换时输出“下次换班请在约x小时后进行”，且用info色显目标识

**Comment by lhhxxxxx** [comment]
**赞美玛丽**
