### ISSUE TITLE
4.5.0RC2测试版连接雷电模拟器4.0.83错误，无法连接

### ISSUE THREAD

**Issue by DaDPrime** [MaaAssistantArknights/MaaAssistantArknights#1912]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

4.5.0RC2测试版连接雷电模拟器4.0.83错误，无法连接

提示连接失败，按提示重启无效，系统是win11专业版22622.601

### 日志文件

[Uploading asst.log…]()

### 截图

![{~PUFRO2$FA) ON%}9PW6NU](https://user-images.githubusercontent.com/63553473/191746109-a405948e-5601-42e5-8ae8-fd4675afe714.png)

**Comment by DaDPrime** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9625618/asst.log)

**Comment by DaDPrime** [comment]
![image](https://user-images.githubusercontent.com/63553473/191746525-85166e68-4618-4575-98da-bbf19266e6cf.png)

**Comment by DaDPrime** [comment]
前一分钟是正常的，更新RC2之后直接无法连接。我有理由怀疑是RC版本的问题

**Comment by MistEO** [comment]
把这个关了试试

![image](https://user-images.githubusercontent.com/18511905/191748695-11e57fdc-5867-455b-95bb-886743c9a32d.png)

**Comment by MistEO** [comment]
看错了，应该是把这个选项勾上试试

![image](https://user-images.githubusercontent.com/18511905/191749272-3f8f53a4-47c0-4b48-b352-7003266836a2.png)

**Comment by MistEO** [comment]
雷电的端口在不断变动，所以从这次更新后，你可能每次连不上都要手动勾一下

之前相当于每次都会自动检测模拟器，所以雷电用的没问题；但这个选项给其他几乎所有模拟器带来了坏处，我们已经在文档中说明不支持雷电了，所以这个选项以后也不会再改回去。

建议更换模拟器
