### ISSUE TITLE
基建自定义换班的skip还是有一点小问题

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#1914]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我在json中写的是这样的：
```
"power": [
    {"operators": ["承曦格雷伊"]},
    {"operators": ["正义骑士号"], "skip": true},
    {"operators": ["雷蛇"]}
]
```
但是实际上MAA把前两个发电站换了班，而第三个被跳过了

### 日志文件

1：08
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9628031/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/30530115/191810280-7766a2b2-f574-486d-8421-e270d4418a84.png)

**Comment by MistEO** [comment]
看了下确实有这个问题，似乎只有电站有这个问题？
