### ISSUE TITLE
搓玉生产站换班的bug

### ISSUE THREAD

**Issue by SilnaMasiro** [MaaAssistantArknights/MaaAssistantArknights#1915]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建搓玉生产站经常在换班时不清空已选择的干员导致换班失败三人红脸。

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9630691/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9630692/asst.log)

**Comment by MistEO** [comment]
maa 的具体操作是啥样的？

**Comment by SilnaMasiro** [comment]
进入换班状态之后没有取消选择，检视了能换班的干员，点击了三个选好的干员然后确定，没有将心情差的干员换班下来

**Comment by bgchaoren** [comment]
我也遇到了这个问题。搓玉制造站会时不时出现这个bug，赤金和经验书制造站还没有遇到过。

**Comment by SilnaMasiro** [comment]
换了一台电脑挂机依然出现不换班的问题
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9671767/asst.log)
