### ISSUE TITLE
一些肉鸽模式的改进建议

### ISSUE THREAD

**Issue by Lancarus** [MaaAssistantArknights/MaaAssistantArknights#192]
一、肉鸽招募相关
1.碰到肉鸽招募界面时检测第一个干员的招募希望是不是0，再按列表ocr选择干员。这样遇到免费干员和免费进阶的不会放弃
![07`6IIF9)37XHJ06ABE48~A](https://user-images.githubusercontent.com/34369130/152184528-aff0edf8-cd79-4de6-9de6-6e9ee2424431.png)
2.第一页内没有列表干员的时候滑到最右边识别选择三星备选干员
3.拿到收藏品和一些不期而遇时间要检测几秒是否到达招募界面

二、商店相关
如果第一层没有存钱的按钮，可以考虑随机买一些商品，（识别绿色三角，可以顺带做一些花费源石锭的月度任务啥的）

三、干员技能
在没有指定那个干员优先配几技能的情况下能否在开始战斗界面按顺序快速点，以保障干员优先用高级的技能
![V$}BUTE3457H6Z`T3U0{Z@M](https://user-images.githubusercontent.com/34369130/152187857-36b4f1fc-3a3f-4021-bcab-e292a0ace8f2.png)
后续如果准备写哪个干员优先指定几技能可以通过在该界面ocr干员名字，点击相对技能位置确定

**Comment by MistEO** [comment]
dev 分支已支持，等待大佬把新 UI 做好，连同 4.0 版本一起发布
