### ISSUE TITLE
更新后模拟器多开不能连接了

### ISSUE THREAD

**Issue by swzplz** [MaaAssistantArknights/MaaAssistantArknights#1920]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

模拟器多开不能连接了，只有初始的模拟器能连上。之前用的mumu可以连，更新后多开连不上。换了推荐的蓝叠国际版n64，多开的还是连不上。管理员启动和重启都试过了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9638019/asst.log)

### 还有别的吗？

蓝叠模拟器国际版5.9.140.1014 N64 adb开了

**Comment by MistEO** [comment]
多开你要手动填地址呀

**Comment by swzplz** [comment]
> 多开你要手动填地址呀

前面的版本一直没遇到这问题，是要手动填连接地址吗，那我每次开都要重新填一次吗

**Comment by swzplz** [comment]
> > 多开你要手动填地址呀
> 
> 前面的版本一直没遇到这问题，是要手动填连接地址吗，那我每次开都要重新填一次吗

手动改了连接地址后连上了，不过几个多开的模拟器端口不同，如果换着挂机的话是不是每次都要手动改一下地址

**Comment by zzyyyl** [comment]
好像可以多复制几个 MAA 分别连接的

**Comment by LuZhuanz** [comment]
我使用的蓝叠国际版，多开一开始连不上，后来把连接模式从通用改为蓝叠就能用了，不知道对你的问题有没有帮助.
