### ISSUE TITLE
GUI界面剩余理智栏下拉列表问题

### ISSUE THREAD

**Issue by Shadowsorrow** [MaaAssistantArknights/MaaAssistantArknights#1921]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新了4.5.0之后主界面新增了多了个剩余理智，但是实际上居然是个和关卡选择同样内容的下拉列表。并且选择后也没什么用，不能指定关卡，也没发现理智有多少剩余。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9638249/asst.log)
24日下午进行的更新，更新后第一次使用就出现了问题

### 截图

![QQ截图20220924161636](https://user-images.githubusercontent.com/55953222/192088421-ed2f8a93-22ae-471e-8678-c881dbe8e7ad.png)

**Comment by ABA2396** [comment]
这个的意思是剩余的理智打什么，比如你选了芯片本，打一次要36，但你只有20理智，这20理智就会去打 `剩余理智` 选择的关卡（如1-7）

**Comment by Tastror** [comment]
加个浮动窗提醒一下用途.jpg
