### ISSUE TITLE
游戏正常却提示掉线也没重启游戏

### ISSUE THREAD

**Issue by Black1312** [MaaAssistantArknights/MaaAssistantArknights#1922]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

游戏正常运行却检测到掉线，也没重启游戏，直接显示任务完成

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9638577/asst.log)

### 截图

![Uploading image.png…]()
![Uploading image.png…]()

### 还有别的吗？

蓝叠国际版模拟器，win11 dev系统，最新 maa

**Comment by 545426** [comment]
![MKBM~DAB(VPGJH5UU6W@5{Y](https://user-images.githubusercontent.com/64343218/192095444-0e3b6235-9f32-48b7-bc0b-97c2604478ee.png)
![YK7SR@H{DR6IHGEBR%L@S0S](https://user-images.githubusercontent.com/64343218/192095446-72078cfc-3ab1-431a-bab2-ccab0974e312.png)

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
