### ISSUE TITLE
Win11软件内自启无效，设置注册表自启只生效一个模拟器

### ISSUE THREAD

**Issue by Inochi9** [MaaAssistantArknights/MaaAssistantArknights#1923]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Win11软件内自启无效，我复制了两个软件，一个D盘一个E盘，且分别对应蓝叠和夜神模拟器，但设置注册表开机自动启动只生效一个模拟器

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9638608/asst.log)

**Comment by MistEO** [comment]
啥叫只生效一个模拟器？

**Comment by 1522027679** [comment]
> 啥叫只生效一个模拟器？

就是我搞了两个软件，一个给蓝叠用，一个给夜神用，我把这俩exe文件都添加开机自启，但是开机只有夜神的那个mma会自动打开，蓝叠绑定那个不会

**Comment by zzyyyl** [comment]
maa!

**Comment by 1522027679** [comment]
> maa!

打错了！是不是因为两个软件虽然我分开放在d盘和e盘但本质上是一个软件所以只有先添加的会启动

**Comment by MistEO** [comment]
因为注册开机自启动绑定的是同一个注册表 key，或许得改下这个逻辑
