### ISSUE TITLE
希望增加长夜临光活动自动完成每日任务的功能

### ISSUE THREAD

**Issue by Qingying828** [MaaAssistantArknights/MaaAssistantArknights#1925]
### 说说你遇到的问题？

能够自定义材料和阵营倾向并自动完成关卡导航来实现一键长草，但是需要用户自己的代理作战符合完成任务的条件

### 其他内容

图一为每日事务，图二为材料倾向
![image](https://user-images.githubusercontent.com/114292286/192096979-68820eaf-08a1-4f50-a302-8adb8d60acb3.png)
![image](https://user-images.githubusercontent.com/114292286/192096980-6f6b26b3-a5d6-48ed-a8d9-8394b4be06a3.png)

**Comment by MistEO** [comment]
技术上可行，但是比较繁琐；而且这种活动一般就一两个星期，以后这些代码就再也用不上了，所以一般来不会做的

**Comment by Qingying828** [comment]
好的，了解了
