### ISSUE TITLE
能否增加“下一次推荐上线时间”的显示

### ISSUE THREAD

**Issue by Qingying828** [MaaAssistantArknights/MaaAssistantArknights#1926]
### 说说你遇到的问题？

能否增加“下一次推荐上线时间”的显示，比如体力将在什么时间回满或是基建大部分干员将在什么时候红脸

### 有什么好的想法？

或是增加选项“在推荐上线时间自动启动模拟器和MAA”

**Comment by ntgmc** [comment]
感谢反馈。
Thank you for your feedback.
