### ISSUE TITLE
自动启动模拟器时，无法自动开启游戏

### ISSUE THREAD

**Issue by BalanceSteelyard** [MaaAssistantArknights/MaaAssistantArknights#1932]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在使用taptap在蓝叠模拟器4直接安装时，游戏名称为arknights-taptap-308而不是明日方舟，无法确认是否此原因导致无法启动游戏，切换系统语言为简中时也无法自动启动游戏。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9640573/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/114338244/192139299-7d41315e-19ae-45c5-ab18-6b233177462b.png)

### 还有别的吗？

版本蓝叠模拟器4    53.145.1003 N64
分辨率1280x720  dpi160
模拟器cpu分配低（1核心）记忆体分配1GB 效能模式低记忆体消耗
帧率60，未启用垂直同步
模拟器系统版本Nougat 64bit
计算机系统Win10 12H2
显卡Intel(R) UHD Graphics

**Comment by MistEO** [comment]
这个包名是啥

**Comment by Black1312** [comment]
请查看maa设置-启动设置是否有“附加命令”如果没有请更新maa至最新开发版。蓝叠模拟器长按明日方舟应该会出现“创建快捷方式到桌面”然后右击此快捷方式选择“属性”将“目标”里面exe后面的字符复制到“附加命令”，下次maa自动启动模拟器时则会自动进入游戏。
如果以上操作无效，请复制目标中所有内容发出来给我们看看包名

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/209061369-40342c82-6803-4aca-bba2-5bce207a9aa2.png)
包名确实没问题不知道为啥就是没打开
