### ISSUE TITLE
自定义换班方案，制造站和贸易站中使用autofill:true无法自动填补干员

### ISSUE THREAD

**Issue by welbaken** [MaaAssistantArknights/MaaAssistantArknights#1933]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

例如：
```json
"trading": [
    {
        "operators": [
            "黑键"
        ],
        "autofill": true
    },
    {
        "skip": true
    }
],
```
第一个贸易站中希望用其他干员填充黑键之外的空位，但是运行后之放置了黑键一人。
附件里提供了完整的json供测试。

### 日志文件

[log&json.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9640625/log.json.zip)

**Comment by zzyyyl** [comment]
修了么（？

**Comment by Constrat** [comment]
@zzyyyl I've just checked.
```json
"manufacture": [
    {
        "product": "Pure Gold",
        "operators": [
            "斑点"
        ],
        "autofill": true
    },
```
it will choose `斑点` (`Spot`) but will ignore the autofill.
Maybe this isn't even a bug, it's just a missing "feature". The JSON might allow it, but the core doesn't know how to manage the request

**Comment by zzyyyl** [comment]
@ABA2396 autofill 是不是只支持宿舍（？
