### ISSUE TITLE
基建宿舍autofill需要填入滿信賴幹員補位

### ISSUE THREAD

**Issue by Beatrice-Am** [MaaAssistantArknights/MaaAssistantArknights#1934]
### 说说你遇到的问题？

用迷迭香套組的時候，宿舍要填滿，現在的宿舍autofill只能填入心情未滿的幹員和信賴未滿的幹員

### 有什么好的想法？

填完心情未滿的幹員和信賴未滿的幹員之後，把滿信賴的幹員也填補到空位上

**Comment by MistEO** [comment]
修了
