### ISSUE TITLE
GUI打开立即闪退

### ISSUE THREAD

**Issue by xiaochuanchuanXD** [MaaAssistantArknights/MaaAssistantArknights#1936]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

以管理员身份运行后立即闪退，甚至看不到软件的界面，文档中的三种方案都试过了

### 日志文件

（我甚至打不开，哪来的日志文件）

### 截图

![T3CVF_3D8QJ`(EG%9H$TXCO](https://user-images.githubusercontent.com/112225811/192177755-b8e81ecb-30b4-4ea3-9137-c2057e5b4a26.png)
![image](https://user-images.githubusercontent.com/112225811/192204558-9748dfa5-6c52-4553-a17e-0b37aec781a0.png)

**Comment by chihuoyanbing** [comment]
有没有可能是运行库缺失的问题?

**Comment by chihuoyanbing** [comment]
![image](https://user-images.githubusercontent.com/71063313/192181194-a8785696-43f5-47ba-885f-a92446f5f44f.png)

**Comment by xiaochuanchuanXD** [comment]
> ![image](https://user-images.githubusercontent.com/71063313/192181194-a8785696-43f5-47ba-885f-a92446f5f44f.png)

我甚至不会弹出这个界面

**Comment by zzyyyl** [comment]
看看目录？

**Comment by chihuoyanbing** [comment]
![image](https://user-images.githubusercontent.com/71063313/192204437-372818c7-c772-4706-a993-8260a961207d.png)

**Comment by xiaochuanchuanXD** [comment]
> ![image](https://user-images.githubusercontent.com/71063313/192204437-372818c7-c772-4706-a993-8260a961207d.png)
![image](https://user-images.githubusercontent.com/112225811/192204558-9748dfa5-6c52-4553-a17e-0b37aec781a0.png)

**Comment by zzyyyl** [comment]
你们都用的是哪个版本的 MAA 啊（

**Comment by zzyyyl** [comment]
话说文档中其实是有**四**种方案的（
都试过了么

**Comment by zzyyyl** [comment]
看看是不是目录没有写权限

**Comment by chihuoyanbing** [comment]
> 话说[文档](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#%E8%BD%AF%E4%BB%B6%E4%B8%80%E6%89%93%E5%BC%80%E5%B0%B1%E9%97%AA%E9%80%80)中其实是有**四**种方案的（ 都试过了么
细看文档，问题解决了，**服cpu q6600 缺少avx指令集
没仔细看，十分感谢

**Comment by xiaochuanchuanXD** [comment]
> 

4.5

**Comment by xiaochuanchuanXD** [comment]
> 话说[文档](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#%E8%BD%AF%E4%BB%B6%E4%B8%80%E6%89%93%E5%BC%80%E5%B0%B1%E9%97%AA%E9%80%80)中其实是有**四**种方案的（ 都试过了么
都试过了，都不行

**Comment by MistEO** [comment]
> > 话说[文档](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#%E8%BD%AF%E4%BB%B6%E4%B8%80%E6%89%93%E5%BC%80%E5%B0%B1%E9%97%AA%E9%80%80)中其实是有**四**种方案的（ 都试过了么
> > 细看文档，问题解决了，**服cpu q6600 缺少avx指令集
> > 没仔细看，十分感谢

所以现在是能用了还是仍然不能用？

**Comment by xiaochuanchuanXD** [comment]
> > > 话说[文档](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#%E8%BD%AF%E4%BB%B6%E4%B8%80%E6%89%93%E5%BC%80%E5%B0%B1%E9%97%AA%E9%80%80)中其实是有**四**种方案的（ 都试过了么
> > > 细看文档，问题解决了，**服cpu q6600 缺少avx指令集
> > > 没仔细看，十分感谢
> 
> 所以现在是能用了还是仍然不能用？

还是不能（哭

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
