### ISSUE TITLE
建议为自定义基建的基建计划添加一个仅收菜组

### ISSUE THREAD

**Issue by OKCHEN99** [MaaAssistantArknights/MaaAssistantArknights#1937]
### 说说你遇到的问题？

因为自定义基建需要在8点、12点、16点换班，所以我分别在上述时间点设置了定时执行。
但从16点到第二天8点，理智和制造站都会溢出，所以我想在22点也设置一个定时执行，只基建收菜，不基建换班。

### 有什么好的想法？

建议为自定义基建的基建计划添加一个第4组，于A+B组后6小时运行（22点），仅收菜，其他跳过。

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/192300765-eeae7a7a-d2a1-499e-8354-02fb36b52cc5.png)
自己在自定义作业文件里加一段就行了，换班全部跳过，但加速和收菜都会执行，但是这样的话建议把文件复制出来改，不然版本更新之后又回去了

**Comment by OKCHEN99** [comment]
> ![image](https://user-images.githubusercontent.com/99072975/192300765-eeae7a7a-d2a1-499e-8354-02fb36b52cc5.png) 自己在自定义作业文件里加一段就行了，换班全部跳过，但加速和收菜都会执行，但是这样的话建议把文件复制出来改，不然版本更新之后又回去了

谢谢大佬
