### ISSUE TITLE
2个明日方舟导致maa连接不上的问题

### ISSUE THREAD

**Issue by woshixiren** [MaaAssistantArknights/MaaAssistantArknights#1938]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最新版测试版本，电脑上有明日方舟官服和b服，做的多开模拟器，每次其中一个挂完了，关闭后启动另一个明日方舟，就会一直提示连接失败，请检查连接设置货尝试重启电脑，重复两次，然后管理员启动，直接启动，重启模拟器都不行，必须重启电脑才能连上。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9644165/asst.log)

### 截图

![Uploading 微信截图_20220926155528.png…]()

### 还有别的吗？

win11 最新22H2版本蓝叠国际版

**Comment by ABA2396** [comment]
如果是两个模拟器，切换模拟器之后要手动改连接设置里的端口号
