### ISSUE TITLE
肉鸽 干员名字不完全匹配

### ISSUE THREAD

**Issue by Jiucheng0** [MaaAssistantArknights/MaaAssistantArknights#194]
计划招募“克洛丝”，但给招了“寒芒克洛丝”

**Comment by zzyyyl** [comment]
这是子串匹配的问题。
还会把“赫默”识别成“赫黑大”，然后当成“黑”......
类似的问题还有“红豆”当成“红”等等
建议名字识别的时候加个`avoid`，比如给”红“设个`avoid="红豆"`（或者干脆用正则匹配？）
@MistEO
