### ISSUE TITLE
基建识别源石制造时不会自动换人

### ISSUE THREAD

**Issue by wowjijiji** [MaaAssistantArknights/MaaAssistantArknights#1940]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

每次基建自动换人时总是会遗漏源石制造的房间，会将所有人下了也会自动补充但是就是不会换人上

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9647032/asst.log)

**Comment by MistEO** [comment]
> 会将所有人下了也会自动补充但是就是不会换人上

没理解，自动补充是啥？可以描述下 maa 具体是怎么操作的么（或者直接录个视频？

**Comment by wowjijiji** [comment]
就是按全选开始以后到结束源石制造那个房间的时候只会将所有人撤下但是不会换人上去

MistEO ***@***.***>于2022年9月27日 周二上午11:21写道：

**Comment by MistEO** [comment]
所以是怎么操作的orz

清空 - 滑动 - 没选人 直接确定
还是
清空 - 滑动 - 选了几个体力不足的 - 确定，后面去宿舍又把体力不足的放宿舍了所以没人
还是其他什么情况

**Comment by MistEO** [comment]
如果是每次都换不上人，帮忙录个视频看看吧

**Comment by wowjijiji** [comment]
最近有些忙不开身，可能过两天才能发

MistEO ***@***.***>于2022年9月27日 周二下午12:04写道：
