### ISSUE TITLE
关于Win11自带的安卓子系统

### ISSUE THREAD

**Issue by ManySub** [MaaAssistantArknights/MaaAssistantArknights#1942]
### 说说你遇到的问题？

请问大佬以后会支持Win11的安卓子系统吗？

### 有什么好的想法？

感觉子系统比模拟器要流畅方便，启动速度也要快点，希望能考虑加入这个功能

**Comment by MistEO** [comment]
请看文档，谢谢

**Comment by weedi0** [comment]
目前子系统并没有比模拟器优秀，mma没适配高分辨率，使用文档的命令调整子系统分辨率，显示不正常（可能是我个例）。主要的问题是运行app时对系统资源的占用比模拟器高出几倍。并不划算

**Comment by ManySub** [comment]
好的
