### ISSUE TITLE
基建 办公室偶尔不会换干员

### ISSUE THREAD

**Issue by Mashiro173** [MaaAssistantArknights/MaaAssistantArknights#195]
蓝叠国际版
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7992849/asst.log)

**Comment by MistEO** [comment]
看了日志中的这次，应该是把小羊放在了办公室中的。如果实际发现办公室没人，考虑是公招刷新次数满了，干员被当做不在工作，放回宿舍了
