### ISSUE TITLE
肉鸽自动战斗不会选择临时招募干员

### ISSUE THREAD

**Issue by Kakkouii** [MaaAssistantArknights/MaaAssistantArknights#1951]
### 说说你遇到的问题？

肉鸽两种自动战斗模式均完全无视临时招募干员，包括高规格分队和开局临时四星招募。

### 有什么好的想法？

或许能够优化肉鸽招募的逻辑？当开局出现四星临时招募的时候/后续战斗出现特定星级，e.g. 五星及以上临时招募的时候优先选择临时招募干员

**Comment by LBacteria** [comment]
昨天我在观战它发病，买了个医疗招募券，里面有临时招募的太后，然后它就……看了下我的box，放弃招募

**Comment by MistEO** [comment]
duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1261

**Comment by WWPXX233** [comment]
目前白给的六星五星干员如果在设置的可选取范围内（比较好用的）会拿
