### ISSUE TITLE
水月肉鸽自动战斗无法正常识别“使用钥匙开启通道”和战利品“漂流秘匣”的场景

### ISSUE THREAD

**Issue by Kakkouii** [MaaAssistantArknights/MaaAssistantArknights#1952]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://user-images.githubusercontent.com/105268629/192603206-0c457ecb-63ce-415c-823e-e0cd0bc7ede3.png)
bug如图，自动战斗遇到“使用钥匙开启通道”的场景会卡住，没有下一步动作。推测为OCR未完全新增水月肉鸽的新场景。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9658708/asst.zip)

出现“使用钥匙开启通道”bug的时间点：9/28 02:06前后
出现战利品“漂流秘匣”bug的时间点：9/28 02:23前后

### 还有别的吗？

模拟器：蓝叠模拟器国际版 5.9.140.1014 N64
OS：Windows 11 专业版 21H2 22000.1042
系统配置：i5-12400 2x16G@3200MHz 模拟器运行在RX 580 2304SP 4G上
模拟器配置：4CPU 4G RAM 高性能模式下 1280x720 320dpi

**Comment by LBacteria** [comment]
诶，貌似没说新肉鸽可以代理吧，目前只有傀影肉鸽可以？

**Comment by MistEO** [comment]
> 诶，貌似没说新肉鸽可以代理吧，目前只有傀影肉鸽可以？

测试版更新了

**Comment by MistEO** [comment]
“漂流秘匣” 是啥样的

**Comment by Misterursw** [comment]
![3K2H{}G O2B@VSJ`~0DW 3](https://user-images.githubusercontent.com/114556289/192691401-1c75fd9e-f0ec-478f-8fc0-c0c38a53ff78.png)

**Comment by LBacteria** [comment]
遇到了，会一直停留在这个界面，不打开，也不直接走，手动打开使用之后会卡在关卡页面
