### ISSUE TITLE
国服 1.9.01 更新后，疑似因为仓库物品排序改变，仓库识别功能提前结束

### ISSUE THREAD

**Issue by bodayw** [MaaAssistantArknights/MaaAssistantArknights#1953]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题。貌似是因为新版本把几个新养成物品（切削液什么的）放在了前面，导致仓库识别开始后，还没扫描完就提前结束了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9659397/asst.log)

相关日志在最底部，大约从 [2022-09-28 04:18:03.968] 开始

**Comment by MistEO** [comment]
更新下测试版试试，应该没这个问题

**Comment by MistEO** [comment]
跟着资源一起更新的，就没写到 CHANGELOG 里，没想到无意间自动修了个 bug（

**Comment by bodayw** [comment]
确认 v4.6.0-alpha.2 没有问题
