### ISSUE TITLE
基建进驻时，始终使用固定的排序，避免效率随进驻时间增加的技能计时被重置

### ISSUE THREAD

**Issue by bodayw** [MaaAssistantArknights/MaaAssistantArknights#1954]
### 说说你遇到的问题？

一部分基建技能的效率加成是和进驻时间相关的，例如稀音：“进驻制造站后，生产力首小时+15%，此后每小时+2%，最终达到+25%”。

我注意到 Maa 在基建换班时，即使某个设施人员组成没有变动，有时却会改变已经进驻的人员的顺序。

例如：前一次进驻制造站，选取了“稀音、帕拉斯、红云”，其中红云因为更早之前被放进宿舍回复心情，选取时比较靠后，进驻时排在了第三位；接下来一次换班时，程序认为这个组合不需要变动，但是重新选择人员进驻时，把红云排在了第一个，变成了“红云、稀音、帕拉斯”。

进驻人员的排序一旦发生变化，会导致像稀音这种效率加成随进驻时间变化的技能计时被重置，即重新从 15% 开始。这样就造成了不必要的效率损失。

### 有什么好的想法？

可能需要更改一下进驻时选人的顺序逻辑，大致的想法是应该要在每次选择了一个设施的进驻人员列表后，始终保证使用同一个进驻的顺序，不受游戏内实际列表顺序影响。

**Comment by ABA2396** [comment]
现在自定义基建里有字段控制是否按顺序选择干员，详细看https://yituliu.site/riicCal
