### ISSUE TITLE
“一键长草”增加“信物兑换凭证”功能

### ISSUE THREAD

**Issue by bodayw** [MaaAssistantArknights/MaaAssistantArknights#1955]
### 有什么好的想法？

希望可以增加“信物兑换凭证”功能，将已获得的多余信物（基本上都是每日公招获得）及时兑换为绿票和黄票。

**Comment by LBacteria** [comment]
人类已经懒到这个程度了吗？（恼）这个东西也不急，需要的时候自己点一下就好了吧
