### ISSUE TITLE
水月肉鸽更新后无法开始战斗进入界面切换的循环

### ISSUE THREAD

**Issue by LBacteria** [MaaAssistantArknights/MaaAssistantArknights#1956]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

“自动肉鸽”模式中，在主界面，终端，集成战略，水月肉鸽页面，返回集成战略，这几个界面循环

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9660446/asst.zip)

### 还有别的吗？

使用的是雷电模拟器

**Comment by LBacteria** [comment]
![20220928084834](https://user-images.githubusercontent.com/108278294/192662744-71b0215a-97ec-4bd6-8dc9-10a32c231778.png)
还有设置选项里的肉鸽设置不适合水月肉鸽（分队什么的）

**Comment by Kakkouii** [comment]
> ![20220928084834](https://user-images.githubusercontent.com/108278294/192662744-71b0215a-97ec-4bd6-8dc9-10a32c231778.png) 还有设置选项里的肉鸽设置不适合水月肉鸽（分队什么的）

release v4.6.0 alpha.2 已适配水月肉鸽 酌情更新至测试版本或等待正式更新
