### ISSUE TITLE
水月肉鸽经常卡在战斗结束后

### ISSUE THREAD

**Issue by lxq-9527** [MaaAssistantArknights/MaaAssistantArknights#1957]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

水月肉鸽经常卡在战斗结束后 然后主动放弃探索

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9661054/asst.log)

时间点： 10.35.08 10.41.32 10.46.09

### 截图

![卡在战斗结束后](https://user-images.githubusercontent.com/109637300/192677452-a331f0de-1c89-4004-b868-bd26e4331581.jpg)
![多次挂机记录](https://user-images.githubusercontent.com/109637300/192677455-31311812-9f16-4cc6-8da4-edfa48f037d8.jpg)

### 还有别的吗？

蓝叠模拟器 
win10操作系统

**Comment by lxq-9527** [comment]
![肉鸽设置](https://user-images.githubusercontent.com/109637300/192680751-5361ed9b-9799-45b5-9c3f-c5a3c7440cc3.jpg)

**Comment by lxq-9527** [comment]
![肉鸽设置](https://user-images.githubusercontent.com/109637300/192680963-f3351455-444e-448c-81d4-f49ad7b071f0.jpg)
补充肉鸽设置

**Comment by sche11** [comment]
我也遇到了相同的情况,我使用的是近医辅开局,优先下医疗的逻辑会导致地面无阻挡漏怪,近卫除了山能及时下,比如煌,攒完20多费就漏没了;
我的解决办法是手动删至只有一个近卫,或者选择费低的山近卫开局.

**Comment by MistEO** [comment]
> 我也遇到了相同的情况

这和楼主说的情况不能说是一模一样，简直是毫不相干吧（
