### ISSUE TITLE
水月肉鸽中使用钥匙打开通道无法识别卡死

### ISSUE THREAD

**Issue by NULLlnull** [MaaAssistantArknights/MaaAssistantArknights#1962]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

水月肉鸽中使用钥匙打开通道无法识别卡死。另箱子无法识别，兴致盎然无法识别都会导致卡死。其他人的issues里好像有提到这个问题，我这里就没有截图了。

### 日志文件

[Uploading asst.zip…]()

### 截图

![QQ截图20220928135527](https://user-images.githubusercontent.com/35243163/192699532-b0aeb844-fe59-4837-8841-9ab267955a70.png)
![QQ截图20220928135537](https://user-images.githubusercontent.com/35243163/192699535-cd8fa5bb-1611-43c4-ae4d-145f82bcb3e5.png)

**Comment by NULLlnull** [comment]
另外，如果一些作战需要用钥匙开路的话。会在开始作战那个页面。按下开始作战之后才会弹出使用钥匙的对话框。在外面的地图中都是可以看见需要钥匙的。只是脚本无法自动识别路线

**Comment by KIDxiaoyuan** [comment]
我遇见了相同的问题这种情况只有结束 肉鸽和任务才可以解决。

**Comment by MistEO** [comment]
现在不会进需要钥匙的关卡了
