### ISSUE TITLE
水月肉鸽排异不选干员

### ISSUE THREAD

**Issue by 545426** [MaaAssistantArknights/MaaAssistantArknights#1963]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

拿到达里奥提灯（去除排异反应）后不选排异干员

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9662183/asst.zip)

### 截图

![Uploading UN50ENTV1$%B4K}1RR%~U9S.png…]()

**Comment by ABA2396** [comment]
图片没发上来

有些藏品的逻辑还没做，遇到卡住的话用模拟器自带的截图工具在每次需要点击前截下图
