### ISSUE TITLE
打完第三层停止操作

### ISSUE THREAD

**Issue by Trashis** [MaaAssistantArknights/MaaAssistantArknights#1964]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打到第三层选择收藏品的时候脚本停止操作，界面如下截屏捏（在本人操作手动点收藏品的时候就自动退出肉鸽下一把了捏）

### 日志文件

不知道这个要填什么捏，第一次反馈bug捏

### 截图

![XCB4 %~MB4S%RACEOR2MOQ9](https://user-images.githubusercontent.com/114566804/192721866-bb24aee2-3f37-4f3a-80ef-674ab911817f.png)

**Comment by MistEO** [comment]
下次遇到帮忙截个原图，需要用模拟器自带的截图工具截一下

**Comment by Trashis** [comment]
大佬我爱你




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月29日(星期四) 凌晨0:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 打完第三层停止操作 (Issue #1964)





 
找群友帮忙拿到图了
