### ISSUE TITLE
水月肉鸽模式的两个机制性bug与三个机制性缺陷

### ISSUE THREAD

**Issue by YipKei** [MaaAssistantArknights/MaaAssistantArknights#1965]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

机制性bug①（算是恶性的吧）：
在选择百炼嘉维尔开局后，在部分地图无法按正常逻辑作为地面单位优先部署，而是先部署了高台并开启了高台的技能，这里肯定有问题。
![Screenshot_2022 09 28_15 17 57 350](https://user-images.githubusercontent.com/53115298/192720639-f534a444-8aa5-4fed-b150-a898c8338190.png)
![Screenshot_2022 09 28_15 18 02 350](https://user-images.githubusercontent.com/53115298/192720752-9fff9664-ff21-4514-8045-ed1667e914dc.png)
![Screenshot_2022 09 28_15 18 09 217](https://user-images.githubusercontent.com/53115298/192720810-faaff279-8316-4bec-bde9-64f703cdfc7d.png)

机制性bug②（严重恶性）：
无法判断需要钥匙开启的得偿所愿，应该是相关逻辑还没写。
建议执行逻辑：先选择该路线，开启失败后，更换路线。
![Screenshot_2022 09 28_15 03 49 900](https://user-images.githubusercontent.com/53115298/192721072-7501fcaa-dcc1-4dc5-91e7-e54c806dbb1a.png)

机制性缺陷①（严重恶性）：
投锋占据了权重最高的守点位，然后开技能空门大开，在蓝点前只有唯一单线防守点时会导致失败率接近90%
建议逻辑调整：
先锋优先部署在防守原点“后”，其次选择部署在权重第二高的守点位，而不是最关键的阻挡节点。
没有对先锋进行区分，那最好的方式就是所有先锋都同步处理。

机制性缺陷②（恶性）：
开局干员未能优先部署
目前部署逻辑是按职业顺序+费用满足条件后执行部署操作。
当出现道中抓取干员费用低于目标职业后，maa会转而优先部署新抓取的干员，直接导致出现巨大的问题。
最典型的例子，近卫阿米娅18费，当开局干员大于18费时，maa会优先部署阿米娅，而近卫阿米娅的阻挡数为1，dps也相对不高，相比手动选定的18费以上挡二干员来说会导致开局能力直线下跌。
这一问题目前看来较难解决？

机制性缺陷③（较为恶性）：
战斗中部署骰子，带来几个负面效果。
首先，目前骰子按近战部署逻辑进行了部署，占用了最优部署位，导致后续部署逻辑出错。
其次，骰子在低楼层的战斗部署中作用较小，同时可以用于开启漂流盒子，目前MAA尚未有能力挑战水月肉鸽的高楼层，战斗部署带来的是以负面效果为主。

### 日志文件

[2022-9-28.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9662721/2022-9-28.zip)

**Comment by zzyyyl** [comment]
显然是因为嘉维尔费太高了（x

**Comment by YipKei** [comment]
> 显然是因为嘉维尔费太高了（x

雀食，不过以后还是会出这个问题的

**Comment by zzyyyl** [comment]
我记得现在的逻辑是超过半数干员可部署时，优先下地面（？

**Comment by YipKei** [comment]
> 我记得现在的逻辑是超过半数干员可部署时，再按照职业顺序（？）下干员
> 
> 嘉维尔费太高了，导致他只能在时间轴很靠后的位置才能落地（

有的图正常，有的图不正常，就搞不懂。（正常的图在日志里有，没提）

**Comment by cybearfish** [comment]
优化建议：骰子建议设置为局内不投，其他时候用（但骰子可能也会增加探索时事件的复杂性，为了稳定也可以提前消耗骰子——>但是也还是有可能刚拿到骰子就遇上相关事件了，在bug修完后可以优化一下）

**Comment by zzyyyl** [comment]
> 优化建议：骰子建议设置为局内不投，其他时候用（但骰子可能也会增加探索时事件的复杂性，为了稳定也可以提前消耗骰子——>但是也还是有可能刚拿到骰子就遇上相关事件了，在bug修完后可以优化一下）

不好写（
骰子会被当成召唤物类然后用掉，不重构肉鸽战斗大概很难处理骰子（
