### ISSUE TITLE
水月肉鸽部分地图的技能开启识别问题

### ISSUE THREAD

**Issue by YipKei** [MaaAssistantArknights/MaaAssistantArknights#1967]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，识别一半似乎也不太稳了，因为上方的遮挡超过了一半。
可能要考虑其他识别方式了？
有一个笨比方法，不过不建议使用，就是将分辨率改成3:2或者4:3

### 日志文件

-

### 截图

![Screenshot_2022 09 28_16 19 30 704](https://user-images.githubusercontent.com/53115298/192727533-1b362b2c-8ade-4cd5-a9ca-376a3fde06c5.png)

**Comment by ntgmc** [comment]
该问题为自动战斗技能自动开启的通用问题，详情请见 #2609
