### ISSUE TITLE
水月肉鸽刷投资开局

### ISSUE THREAD

**Issue by Ared-Fish** [MaaAssistantArknights/MaaAssistantArknights#1969]
### 说说你遇到的问题？

现开局默认选择第一个队伍，进入关卡后会选择干员“艾丽妮”作为主要输出，部分关卡下会出现漏怪多的情况，极端情况下会直接第一关就结束战斗，出现在关卡：
![@_TW_WI5OHPQ6BZT8_SIV(J](https://user-images.githubusercontent.com/114568605/192728916-6e9f6d98-ce0a-4272-82f3-ba0ed064bd58.png)

### 有什么好的想法？

可以在开局“人本策略”中选人换成开局选择“羽毛笔”或“海默”，医疗选择“调香师”（大部分都会有的吧），收割者加调香师的组合可以完美度过第一层所有关卡，除开出现宝箱怪刷新在攻击范围内的情况（目前没有遇到）
![%_~{H1}3%`8O2U 13HCE )7](https://user-images.githubusercontent.com/114568605/192729726-7ae63266-835b-4777-ba20-c56cd58cb828.png)
![EF9(VUJ2WK4%HF8_%Z{EA`P](https://user-images.githubusercontent.com/114568605/192731641-179bf4cb-4762-4dbb-ae12-63880df943a1.png)
![4U_L6QXTVMSA7{4`7Q96R0P](https://user-images.githubusercontent.com/114568605/192732096-e6063e14-33ae-4753-a6f2-6badb90815fe.png)
以上按顺序放置，除了虫群关卡紧急两只自爆虫一起炸没遇到过实测，其他的都有紧急实测，可通过。

### 其他内容

“调香师”和“收割者”有练的人应该还是比较多，这也仅是做一个建议，如果觉得可以一用，望请采纳

**Comment by Ared-Fish** [comment]
![X_AP~P{RRYG)}Z$)BMMDD2E](https://user-images.githubusercontent.com/114568605/192743396-8eb4bfec-579f-42dd-aa97-f22566253043.png)

**Comment by Ared-Fish** [comment]
另外有人说这关有宝箱怪的情况，调整羽毛笔位置即可解决，已测试
![$G@B)2~Z3HR$32GYI}~`WQ](https://user-images.githubusercontent.com/114568605/192743890-7ce0f30e-9814-4d7a-9201-b158e1fc8112.png)

**Comment by YipKei** [comment]
1、你可以在设置页面手动设置开局干员为羽毛笔，理论上能选到需要的干员。
2、MAA目前刷图不依赖作业，不是内置作业的问题，目前的地图判断机制有待优化，不过优先级暂时不高，目前团队需要优先解决各种卡死问题。

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/192827169-b0c9ca4b-fd7b-417b-84e6-2f1a5f0a9bc0.png)

你自己设呗
