### ISSUE TITLE
水月肉鸽模式下运行中途maa出现闪退

### ISSUE THREAD

**Issue by jxaycfk** [MaaAssistantArknights/MaaAssistantArknights#1970]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基本每一次运行都会出现模拟器断开，重连不回去然后闪退
连接设置里是自动填写完的

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9663838/asst.zip)
2022-09-28 17:20:26.049

### 还有别的吗？

夜神模拟器
win10
cpu支持avx
运行库都有下载并重启过
我在运行刷理智之类的不会出现这种情况

**Comment by MistEO** [comment]
修了个可能性，不知道有没有用（
