### ISSUE TITLE
水月肉鸽会在开始选择难度时卡住

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#1976]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

水月肉鸽会在选择难度时卡住，不能正常刷取

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9664607/asst.log)

### 截图

![屏幕截图 2022-09-28 195637](https://user-images.githubusercontent.com/92417243/192772931-71cbabba-f4a1-4731-a979-0bae2a2ade2a.jpg)

### 还有别的吗？

模拟器为4.0.72，操作系统为Windows11 21H2，电脑配置为9300H+1650，内存为16G

**Comment by xiaoweiXX** [comment]
我相信这应该是个bug而非需要增加的功能点

**Comment by zzyyyl** [comment]
选择难度只有第一次需要手动选择的，跟傀影肉鸽一样，现在没做吧

**Comment by xiaoweiXX** [comment]
> 选择难度只有第一次需要手动选择的，跟傀影肉鸽一样，现在没做自动选择难度吧

我在平板上打过一两次，但是还没有在模拟器中打过。我再试试

**Comment by xiaoweiXX** [comment]
> 选择难度只有第一次需要手动选择的，跟傀影肉鸽一样，现在没做自动选择难度吧

好像确实是这样

**Comment by MistEO** [comment]
自己选一下难度吧，选了之后就不会再主动弹出这个界面了。之后版本有空再改
