### ISSUE TITLE
水月肉鸽无法正常开始

### ISSUE THREAD

**Issue by a78239636** [MaaAssistantArknights/MaaAssistantArknights#1977]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

始终重复进入和退出肉鸽界面，像是在肉鸽界面图片识别没识别出来一样？ 

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9664711/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/34701894/192775009-a2a4b449-6d36-48b2-bf66-f1ee6d79c899.png)
最深只能到这个界面，再就会退回主界面，无限循环

### 还有别的吗？

MuMu 模拟器， Windows 10

**Comment by zzyyyl** [comment]
你需要在界面上勾选水月肉鸽的选项，并且这个按钮并不是实时生效，需要重启 MAA。

![image](https://user-images.githubusercontent.com/74587068/192776390-72005693-5aa2-45ae-ab77-931db9e39804.png)

**Comment by a78239636** [comment]
> 你需要在界面上勾选水月肉鸽的选项，并且这个按钮并不是实时生效，需要重启 MAA。
> 
> ![image](https://user-images.githubusercontent.com/74587068/192776390-72005693-5aa2-45ae-ab77-931db9e39804.png)

懂了，感谢！

**Comment by zhongfly** [comment]
应该使用更容易理解的文字介绍，这个For Mizuki看到之后完全不知道是什么意思，还以为是什么彩蛋

> 你需要在界面上勾选水月肉鸽的选项，并且这个按钮并不是实时生效，需要重启 MAA。
> 
> ![image](https://user-images.githubusercontent.com/74587068/192776390-72005693-5aa2-45ae-ab77-931db9e39804.png)

**Comment by zzyyyl** [comment]
pre-release 不要要求太多（x

**Comment by MistEO** [comment]
> 应该使用更容易理解的文字介绍，这个For Mizuki看到之后完全不知道是什么意思，还以为是什么彩蛋
> 
> > 你需要在界面上勾选水月肉鸽的选项，并且这个按钮并不是实时生效，需要重启 MAA。
> > ![image](https://user-images.githubusercontent.com/74587068/192776390-72005693-5aa2-45ae-ab77-931db9e39804.png)

故意的，版本刚发布，不想跳脸，藏一下
