### ISSUE TITLE
自动水月肉鸽策略是否改变？

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#1978]
### 说说你遇到的问题？

在傀影肉鸽中，默认选项为指挥分队，默认开局队伍为山、梓兰和芙蓉；而在水月肉鸽中，选人时近卫第一遍MAA貌似没有找到人（除了帕拉斯之外我6星近卫全了），返回去第二遍选了艾莉妮。我有点迷惑，所以问一下是不是改策略了。

**Comment by zzyyyl** [comment]
没改，估计你的 山 识别出 bug 了（

**Comment by xiaoweiXX** [comment]
> 没改，估计你的 山 识别出 bug 了（

淦哦

**Comment by MistEO** [comment]
艾丽妮现在就是优选，现在改了，需要的话自己设置下吧，想填谁填谁

![image](https://user-images.githubusercontent.com/18511905/192815631-5193d763-205a-4aee-897d-61b20cd4712f.png)
