### ISSUE TITLE
水月肉鸽无法识别山并选中

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#1979]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽中，6星近卫干员山无法被识别并选中。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9664886/asst.log)

### 还有别的吗？

模拟器为4.0.72，操作系统为Windows11 21H2，电脑配置为9300H+1650，内存为16G

**Comment by zzyyyl** [comment]
嘶，逻辑确实没改，艾丽妮 优先级确实比 山 要高（
大概是 9b333e8025fa80b14af10d035651b6415b612c42 这个 commit 导致选了艾丽妮？你的艾丽妮大概不在第一页吧（

**Comment by zzyyyl** [comment]
另外，开局干员可以在设置里改的（

**Comment by MistEO** [comment]
本来就是优选艾丽妮啊

**Comment by xiaoweiXX** [comment]
> 本来就是优选艾丽妮啊

我记得傀影肉鸽默认是先选山的，起码在7月份是这样的

**Comment by MistEO** [comment]
现在改了，需要的话自己设置下吧，想填谁填谁

![image](https://user-images.githubusercontent.com/18511905/192815631-5193d763-205a-4aee-897d-61b20cd4712f.png)
