### ISSUE TITLE
水月肉鸽不会自动投资

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#1980]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽在选择了刷蜡烛尽量往前打，并且勾选投资源石锭状态下，不会自动投资源石锭。我的源石锭并没有达到上限

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9664925/asst.log)

### 截图

![屏幕截图 2022-09-28 203435](https://user-images.githubusercontent.com/92417243/192779984-afc1920c-acf7-4230-925d-33f2db1bec0c.jpg)

### 还有别的吗？

模拟器为4.0.72，操作系统为Windows11 21H2，电脑配置为9300H+1650，内存为16G

**Comment by zzyyyl** [comment]
（题外话：小心投资多了商店有 debuff）

**Comment by MistEO** [comment]
是一个没投，还是投的少了。

如果是投的少了，肉鸽在你通关某个结局之前，商店出投资的概率会很低，傀影也是要通过大锁才会高概率出投资的

**Comment by xiaoweiXX** [comment]
> 是一个没投，还是投的少了。
> 
> 如果是投的少了，肉鸽在你通关某个结局之前，商店出投资的概率会很低，傀影也是要通过大锁才会高概率出投资的

一个没投。我打第一遍水月肉鸽的时候就出了投资，因此我以为投资和傀影一样是每次都出。

**Comment by xiaoweiXX** [comment]
> 是一个没投，还是投的少了。
> 
> 如果是投的少了，肉鸽在你通关某个结局之前，商店出投资的概率会很低，傀影也是要通过大锁才会高概率出投资的

怪了，我手打这几次都出投资

**Comment by MistEO** [comment]
所以说是看着 MAA 遇到了投资但是没进去，还是真的就压根没遇到投资_(:з」∠)_

**Comment by xiaoweiXX** [comment]
> 所以说是看着 MAA 遇到了投资但是没进去，还是真的就压根没遇到投资_(:з」∠)_

因为有点事所以我就一直挂着自己刷没注意，不过看log连刷了七八次一次投资都没有，换到我自己打就有投资，所以我猜是有投资没进去

**Comment by zzyyyl** [comment]
> > 所以说是看着 MAA 遇到了投资但是没进去，还是真的就压根没遇到投资_(:з」∠)_
> 
> 因为有点事所以我就一直挂着自己刷没注意，不过看log连刷了七八次一次投资都没有，换到我自己打就有投资，所以我猜是有投资没进去

我觉得可能只是没有投资选项（我今天连打四次第一层都没有投资选项）

如果看着 MAA 遇到了投资但是没进去的话再来反馈~

**Comment by xiaoweiXX** [comment]
> > > 所以说是看着 MAA 遇到了投资但是没进去，还是真的就压根没遇到投资_(:з」∠)_
> > 
> > 
> > 因为有点事所以我就一直挂着自己刷没注意，不过看log连刷了七八次一次投资都没有，换到我自己打就有投资，所以我猜是有投资没进去
> 
> 我觉得可能只是没有投资选项（我今天连打四次第一层都没有投资选项）
> 
> 如果看着 MAA 遇到了投资但是没进去的话再来反馈~

确实是没遇到，我太非了

**Comment by xiaoweiXX** [comment]
> 是一个没投，还是投的少了。
> 
> 如果是投的少了，肉鸽在你通关某个结局之前，商店出投资的概率会很低，傀影也是要通过大锁才会高概率出投资的

今天我跟一个人闲聊，他说他傀影肉鸽所有结局都通了之后也不会把把出投资，另外他把水月肉鸽结局都通了之后遇见投资的概率也是很低。我想问一下出投资的概率大概到底是是什么机制。
