### ISSUE TITLE
水月肉鸽蓝门位置设置建议

### ISSUE THREAD

**Issue by nightofknife** [MaaAssistantArknights/MaaAssistantArknights#1981]
### 说说你遇到的问题？

有些地图可以用干员卡一个好位置方便过，考虑到maa是堵门的
就替换蓝门就行

### 有什么好的想法？

部分地图蓝门替换位置建议：
蓄水池更改至 (6,4) ps:把怪堵在水里打
共生更改至(4,4) ps:对使用羽毛笔一类的可以白嫖位于(3,3)的敌人，而且可以让高台少被打几次
无声呼号更改至(3,2) ps:地面提前接敌减少被白嫖
海神的信者更改至(5,2) ps:这位置虽然会被冻，但是高台位会被放在后面减少被打
征兆更改至(3,3)或者(5,3) ps:手打的时候(3,3)的地面干员可以用来吸引右侧远程的伤害
除暴安良更改至(4,3) ps:这样一个干员就能堵两条路，但是(4,1)会落空降兵，可能会打不死，导致漏怪
后面的我的maa打不到就暂时不建议了

### 其他内容

建议增加地图地块黑名单设定，有些地块放干员收益不高，用黑名单阻止一下
PS：用傀影肉鸽改了个（笑
[roguelike_copilot.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9666014/roguelike_copilot.zip)

**Comment by zzyyyl** [comment]
来个pr呗
