### ISSUE TITLE
水月肉鸽 无法开始战斗，进入界面切换的循环

### ISSUE THREAD

**Issue by Win-X** [MaaAssistantArknights/MaaAssistantArknights#1984]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

平台：蓝叠 5.9.0.6502 N64
软件版本：v4.6.0 alpha2

看到一个相似问题，虽说标了fixed，但是对于我遇到的，并没有效果。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9666783/asst.log)
时间大概在23:17---23:26之间

**Comment by zzyyyl** [comment]
Duplicate of #1977
