### ISSUE TITLE
4.6.0-alpha.2 无法正常开始肉鸽

### ISSUE THREAD

**Issue by zhongfly** [MaaAssistantArknights/MaaAssistantArknights#1985]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

无法开始，软件一直重复如下过程：首页-集成战略-水月肉鸽的开始页面，但是不点击开始，直接又回到了首页
与肉鸽设置相关，出问题时设置为： 刷蜡烛 指挥分队 职业配置：取长补短（近卫那个）
修改2个开局设置为默认后正常开始

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9666807/asst.log)

### 截图

前文所述的“水月肉鸽的开始页面”即为下图:
![Screenshot_2022 09 28_23 54 36 043](https://user-images.githubusercontent.com/11155705/192827592-41b6d488-34e9-41e8-89c2-5f0abe01698b.png)

### 还有别的吗？

蓝叠国际版 5.9.0.1061 N64

**Comment by zzyyyl** [comment]
参考 #1977

**Comment by zhongfly** [comment]
> 参考 #1977

确实，我忘记我还把这个勾上就成功了
应该默认勾选啊

**Comment by zzyyyl** [comment]
草，有的人可能还想打傀影（确信
