### ISSUE TITLE
水月肉鸽卡无法进入

### ISSUE THREAD

**Issue by MisterCoBen** [MaaAssistantArknights/MaaAssistantArknights#1988]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽无法正常进入，卡在进入肉鸽和开始探索两个界面并循环切换

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9668396/asst.log)

**Comment by MistEO** [comment]
看置顶

**Comment by LotuSrc** [comment]
4.7.3还是有这个问题，界面一直循环切换，置顶貌似没有了

**Comment by ABA2396** [comment]
> 4.7.3还是有这个问题，界面一直循环切换，置顶貌似没有了

![image](https://user-images.githubusercontent.com/99072975/207280864-58f5e712-c1f3-4995-824e-63abc4780c11.png)
