### ISSUE TITLE
水月肉鸽卡死在战斗结束

### ISSUE THREAD

**Issue by MigdalBavel** [MaaAssistantArknights/MaaAssistantArknights#1989]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

4.6.0 alpha  2
连续两次肉鸽卡死在战斗结束选择战利品阶段。共同特征是都有漂流秘匣这个掉落，然后剩下最后不选择卡死在那。

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9668997/asst.bak.log)

### 截图

![QQ截图20220929051133](https://user-images.githubusercontent.com/105539375/192890503-dbf3bbef-b50d-43f4-8f4f-e7e3e2aef230.jpg)
![QQ截图20220929051240](https://user-images.githubusercontent.com/105539375/192890517-3a3f7df7-3405-4f2c-84fc-77b1422b89c1.jpg)

**Comment by MistEO** [comment]
试试 alpha.3

**Comment by MigdalBavel** [comment]
嗯嗯，alpha 3 正常了
