### ISSUE TITLE
增加多模拟器功能

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#199]
希望增加一个多模拟器的功能，如果打开多个模拟器，能给不同的模拟器设置相同或者不同的任务，方便挂机。

**Comment by MistEO** [comment]
吧文件夹复制多份就好了

**Comment by xiaoweiXX** [comment]
复制多份MAA同时启动，会不会出现多个MAA同时检测到同一个模拟器的情况？

**Comment by xiaoweiXX** [comment]
> 把 MAA 的文件夹复制多份就好了

复制多份MAA同时启动，会不会出现多个MAA同时检测到同一个模拟器的情况？

**Comment by MistEO** [comment]
手动在 MAA 设置里面修改连接就好了
