### ISSUE TITLE
水月肉鸽天光海岸理智不足时卡住

### ISSUE THREAD

**Issue by 1664587146** [MaaAssistantArknights/MaaAssistantArknights#1990]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽天光海岸理智不足以选第一和第二选项时卡住，建议将默认选项改为第三选项

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9669697/asst.zip)

1:46附近

### 截图

![2022-09-29_01-46-42 115_raw](https://user-images.githubusercontent.com/56779414/192910039-01b7d9dd-ab84-4669-bb83-3c3592697b54.png)

**Comment by cybearfish** [comment]
顺便说一下，正常结局应该要比骑士结局好打，而拿骑士对道中的帮助不多，建议直接设计为不拿
