### ISSUE TITLE
水月肉鸽总是还未遇到商店就放弃本次探索

### ISSUE THREAD

**Issue by wsyz5467** [MaaAssistantArknights/MaaAssistantArknights#1996]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

总是还未遇到商店就放弃本次探索
![image](https://user-images.githubusercontent.com/52782369/192953167-e2a4e1d2-4263-40a3-ac9f-d49dfcba8de7.png)
![image](https://user-images.githubusercontent.com/52782369/192953209-9ab358ff-8094-4def-a9c7-cda9c676ae4f.png)
![image](https://user-images.githubusercontent.com/52782369/192953231-46c4229f-d897-4c04-bc49-e74987ca8b44.png)
![image](https://user-images.githubusercontent.com/52782369/192953254-78a9ab3e-db8a-4483-b028-88d7773a28a1.png)

### 日志文件

时间点可以参考上截图
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9671579/asst.log)

### 还有别的吗？

上个测试版本好像没有这种情况

**Comment by zzyyyl** [comment]
不是每次探索都有投资的（而且 MAA 有可能打不到第一层结束）
你是看着 MAA 没进商店直接退出么？

**Comment by wsyz5467** [comment]
在发issue之前特地盯了一次过程，确定没有进商店就放弃了。
如果商店里没有投资的话，应该是这样的：
时间 关卡：诡意行商
时间 放弃本次探索

**Comment by wsyz5467** [comment]
刚刚退回了alpha2版本，也有这个情况。
![image](https://user-images.githubusercontent.com/52782369/192978658-2dbae97b-713e-4dd0-a1c7-f7f326a7beda.png)

**Comment by MistEO** [comment]
用 alpha.3 把 debug/roguelike/ 里面的截图发一下

**Comment by wsyz5467** [comment]
时间为早上的都是用alpha3，下午两点多开始用2
[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9672658/roguelike.zip)

**Comment by wsyz5467** [comment]
等我晚上有空的时候录个屏看看，有复现的话我再进行反馈。

**Comment by wsyz5467** [comment]
找到问题了，只要不期而遇的选项是三项，就有这个情况，我有视频录下来为证。视频有点大，请问视频我要怎么发给各位开发者。

**Comment by wsyz5467** [comment]
主要是这两个
![image](https://user-images.githubusercontent.com/52782369/193076416-93db6d2e-626c-4388-bee2-c3d96e6e375c.png)
![image](https://user-images.githubusercontent.com/52782369/193076481-70082627-cdc6-4a27-873a-1fc458706705.png)

**Comment by wsyz5467** [comment]
新版本卡这了……
![image](https://user-images.githubusercontent.com/52782369/193163995-aba63c35-dbe7-41c0-9799-ff4552041c29.png)

**Comment by cybearfish** [comment]
应该是还没有做出对应事件的操作，所以（在alpha3）会截屏debug然后重开
建议打开MAA下的debug文件夹里的rougelike反馈

**Comment by wsyz5467** [comment]
这个问题是偶然看见的，大概留意了一下，卡在这个招募界面不动大概有个一分多钟，然后用截图工具直接截图之后终止了MAA的运行。

**Comment by wsyz5467** [comment]
这次卡了五分钟多之后才放弃。第三到第五张图是debug文件夹里的，文件名对应情况见第六张图
![image](https://user-images.githubusercontent.com/52782369/193170775-8af95f5e-d6f5-4af9-be52-24e5b626c228.png)
![image](https://user-images.githubusercontent.com/52782369/193170997-28726196-dabf-4133-8655-3de70f9fd9c7.png)
![2022-09-30_09-10-49 941_raw](https://user-images.githubusercontent.com/52782369/193170833-7d54d37f-b8f2-4d10-b63c-fff61407f322.png)
![2022-09-30_09-19-23 500_raw](https://user-images.githubusercontent.com/52782369/193170836-761ffe7c-aa7b-4a40-aa0c-d16a9fc77463.png)
![2022-09-30_09-30-35 747_raw](https://user-images.githubusercontent.com/52782369/193170838-42edec1f-1f0b-46fb-b71d-da8bd561d5a1.png)
![image](https://user-images.githubusercontent.com/52782369/193171040-a89a3e44-252a-4c3a-a518-a678f1062fc3.png)

**Comment by MistEO** [comment]
全修了
