### ISSUE TITLE
当存在理智保护图标时无法正常刷图

### ISSUE THREAD

**Issue by ghost** [MaaAssistantArknights/MaaAssistantArknights#20]
如题，如果通关时没有失败过，首次通关理智保护图标还在的情况下辅助无法识别开始行动按钮，会出现错误

**Comment by MistEO** [comment]
感谢反馈，正好之前也经常有新出的活动图，开始按钮长得不一样的问题。正好一起改了_(:з」∠)_

[v1.1.1](https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/release.stable.1.1.1) 已修复
