### ISSUE TITLE
增加一键清理功能

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#2007]
### 说说你遇到的问题？

MAA每次更新，并不会把所有旧的文件清理，而是会选择保留一部分。测试版为了适配水月肉鸽，增加了在卡住时截屏的功能，但并不会自己清理，这些截图在汇报bug之后就没用了，可以让用户一键毫无保留的清理。

### 有什么好的想法？

增加一个按钮，一键清理缓存、旧文件、bug截图等无用内容

### 其他内容

虽然也可以用户自己手动清理，但是用户并不能百分百确定哪些能清理，哪些不能被清理。并且，人工清理也不能保证没有遗漏，软件设计者想的应该更加全面一些，能够清理干净。

**Comment by ShiinaWhite** [comment]
这个可以有
