### ISSUE TITLE
水月肉鸽 不停尝试将地面辅助（工匠）放在高台位

### ISSUE THREAD

**Issue by suzumimi** [MaaAssistantArknights/MaaAssistantArknights#2009]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

问题内容：
1、本次问题反馈重点反馈问题：水月肉鸽进行过程中，在招募了地面辅助（掠风）后，会在战斗关卡中不停尝试将掠风放置在高台位。另外我暂时未碰到招募高台先锋（如夜半、豆苗）的情况，对于高台先锋会不会存在同等问题暂不明晰。
2、由于我指定 百炼嘉维尔 开局，经观察发现，自动肉鸽默认使用百炼嘉维尔1技能，且偶尔会将百炼嘉维尔面朝蓝门放置。这是个小问题，仅作优化提议。

解决方案（抛砖引玉）：
问题1、建议添加自定义的招募黑名单，这可能是相对（？）简便的解决方案，顺带能解决了自动肉鸽在道中会招募我一些技能RANK1的基建人的问题
问题2、或许可以在自定义开局干员的同时自定义开局干员的默认技能选择？

水月肉鸽刚开始支持，不管是招募逻辑还是干员摆放、技能选择等等的优化空间还很大，肯定不如傀影肉鸽那么成熟，完全可以理解，当前版本还有很多人反馈的各种道中主动放弃探索的问题我看前面都有人提到，我就不重复提了，现在的maa功能已经很强大了，在此表示感谢。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9676223/asst.log)

### 还有别的吗？

模拟器：蓝叠

**Comment by zzyyyl** [comment]
已经有黑名单了的啊（
你的地面辅助是什么时候招募的（？

**Comment by suzumimi** [comment]
> 已经有黑名单了的啊（ 你的地面辅助是什么时候招募的（？

我的maa已经是最新版本了，想请问下黑名单在哪设……
招掠风应该大概是23点09分？

**Comment by suzumimi** [comment]
> > 已经有黑名单了的啊（ 你的地面辅助是什么时候招募的（？
> 
> 我的maa已经是最新版本了，想请问下黑名单在哪设…… 招掠风应该大概是23点09分？

不对，23点09分那是放掠风上高台后战斗失败的时间，招募的时候我没看模拟器不清楚具体时间点，估计是十点半到十一点之间吧

**Comment by suzumimi** [comment]
> > > 已经有黑名单了的啊（ 你的地面辅助是什么时候招募的（？
> > 
> > 
> > 我的maa已经是最新版本了，想请问下黑名单在哪设…… 招掠风应该大概是23点09分？
> 
> 准确的说是不在名单里的都不会招募。名单在 `resource\roguelike_recruit.json` 更新后会在 `resource\addition\Roguelike2\resource\roguelike_recruit.json`

为何在水月肉鸽里我有亲眼见到它替我招募了承曦格雷伊(ﾟДﾟ≡ﾟдﾟ)!?
我去翻开你提到的两个文件检查了一下，按理应该不会发生这种情况

**Comment by yueluoyang** [comment]
我检查了黑名单掠风不在里面也会被招募，是同样的问题QAQ

**Comment by et2012** [comment]
因为辅助干员的候选名单（白名单干员）比较少，可能是进入了后备逻辑，
即：没有候选干员时，会随便选一个精一50级以上的干员。

其实肉鸽有很多默认行为并不适合所有情况，但是全都做成选项的话，可能又会太复杂。

**Comment by MistEO** [comment]
现在不会招不在需求列表中的非精二干员了，相当于修了（确信
