### ISSUE TITLE
水月肉鸽遇到怪海后自动关闭山的技能，且失败后在结算界面卡着不动

### ISSUE THREAD

**Issue by guojunyu196** [MaaAssistantArknights/MaaAssistantArknights#2012]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

遇到怪海后自动关闭山的技能，且失败后在结算界面卡着不动

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9677606/asst.log)

### 截图

![2022-09-30_01-20-06 617_raw](https://user-images.githubusercontent.com/76220347/193100533-bb57dc89-973a-4b82-99b2-f0eba9c5b6a6.png)

**Comment by guojunyu196** [comment]
文件貌似没传上来orz
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9677606/asst.log)
![2022-09-30_01-20-06 617_raw](https://user-images.githubusercontent.com/76220347/193100533-bb57dc89-973a-4b82-99b2-f0eba9c5b6a6.png)

**Comment by MistEO** [comment]
这个数据回溯是怎么出现的呀，我正常打好像没有，什么条件下才会出？

**Comment by yueluoyang** [comment]
数据回溯是通关了之后才有的吧

**Comment by cybearfish** [comment]
题主为什么是 失败后出现的？

**Comment by guojunyu196** [comment]
我不到啊（
我之后也没出现这个情况了
