### ISSUE TITLE
水月肉鸽，开完盒子就尬住了，只能自动退出

### ISSUE THREAD

**Issue by Avalonal** [MaaAssistantArknights/MaaAssistantArknights#2015]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽，开完盒子就尬住了，只能自动退出

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9680158/asst.log)

### 截图

![2022-09-30_10-21-14 614_raw](https://user-images.githubusercontent.com/39792922/193176648-706b9b3d-a2c1-446b-bb74-46d17a58afe6.png)

**Comment by cybearfish** [comment]
看了日志，你是alpha3吧，试试alpha4？
我3也出现过好几次，4目前暂时没出现

**Comment by Avalonal** [comment]
> 

ok，确实，没注意到有alpha4
