### ISSUE TITLE
新肉鸽卡住

### ISSUE THREAD

**Issue by JINSQ1** [MaaAssistantArknights/MaaAssistantArknights#2016]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

大概是委托任务完成的界面 模拟器是蓝叠云国际最新版 win11 时间在9月30日上午9点42分29s 1个小时之后还在卡着

### 日志文件

[Uploading asst.log…]()

### 截图

[
![_R}})YG63KNT$F)H~QAV }W](https://user-images.githubusercontent.com/114714470/193178622-9a806a73-4383-4bb4-81a0-08f3fd2c2873.png)
[](url)](![QQ图片20220930103611](https://user-images.githubusercontent.com/114714470/193178646-6cb1105a-c0cf-4914-b7e9-78ee2f9d4f88.png))

### 还有别的吗？

模拟器是蓝叠云国际最新版 win11系统

**Comment by JINSQ1** [comment]
[Uploading asst.log…]()
![IFESZB57YM9AO)O}~QUOZ@9](https://user-images.githubusercontent.com/114714470/193179509-1579d700-19ec-41a7-a568-f83d31e4109b.png)

**Comment by JINSQ1** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9680270/asst.log)

**Comment by JINSQ1** [comment]
我手动奖励领取之后就自动继续运行了

**Comment by cybearfish** [comment]
顺便提一嘴，这个界面领不了奖励（yj你罪大恶极），点一下才能关闭，然后要在“干员”左边点进去领取
