### ISSUE TITLE
自动肉鸽会在肉鸽见面和主界面一直循环

### ISSUE THREAD

**Issue by Dtlasdfae** [MaaAssistantArknights/MaaAssistantArknights#2017]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

自动肉鸽会在主界面和肉鸽界面循环，以确认模拟器及其设置无误

### 日志文件

![MuMuThumbnail20220930103351](https://user-images.githubusercontent.com/114715144/193179961-c8274a0a-e278-432d-b8a5-0c54787c465d.png)

**Comment by cybearfish** [comment]
可以先研究一下设置再提问谢谢

**Comment by weedi0** [comment]
同样遇到主界面和肉鸽界面循环问题，看截图记录是断网重连的问题。
[在进入界面循环.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9680478/default.zip)

**Comment by cybearfish** [comment]
楼主先看一下这个打开没有
<img width="388" alt="image" src="https://user-images.githubusercontent.com/112690111/193185503-7b4b1fa5-e901-4e68-9707-5c32167a9d15.png">
楼上的网络问题建议百度
