### ISSUE TITLE
水月肉鸽 进入"重返家园"节点后卡死

### ISSUE THREAD

**Issue by kressety** [MaaAssistantArknights/MaaAssistantArknights#2018]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

4.6.0-alpha.4版本，水月肉鸽刷投资
进入不期而遇后，如果遇到"重返家园"事件，Maa会花2块钱购买一张随机招募券，进入招募页面后便会卡死，不回报任何信息，也不做任何动作。

### 日志文件

[Uploading asst.log…]()

### 截图

![image](https://user-images.githubusercontent.com/57744786/193180925-33c01fa8-9729-459c-820f-4773eaca9a84.png)

### 还有别的吗？

BlueStacks 5.9.0.1064 N64
Windows11 2H22

**Comment by kressety** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9680340/asst.log)

**Comment by cybearfish** [comment]
同上，且此时不会debug自动截图 
<img width="989" alt="屏幕截图 2022-09-30 104539" src="https://user-images.githubusercontent.com/112690111/193183111-534fc97a-d773-4c77-acf7-a14a3d4da570.png">
（手动截的）

**Comment by kressety** [comment]
又遇到了，补一张截图。即使希望足够进阶干员，Maa仍然会卡死。
![image](https://user-images.githubusercontent.com/57744786/193183631-690fec07-4e63-4eca-8a57-53c0b003d4bf.png)

**Comment by cybearfish** [comment]
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/112690111/193186728-f067e9c8-3906-4069-91fb-762639e8356f.png">
现在能肯定不是希望不够的原因了，应该是因为有多个职业同时招募的原因，等着修吧

**Comment by MistEO** [comment]
发下 `debug/roguelike/` 文件夹里面的图看看

**Comment by kressety** [comment]
已上传。但正如@cybearfish 所言，上述bug没有生成对应的截图。
[roguelike_9_30.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9680739/roguelike_9_30.zip)
