### ISSUE TITLE
肉鸽干员的晋升优先级往往比招募优先级低

### ISSUE THREAD

**Issue by cybearfish** [MaaAssistantArknights/MaaAssistantArknights#2019]
### 说说你遇到的问题？

在roguelike_recruit.json中，干员的晋升优先级往往比招募优先级低，**有时**会出现可以晋升但选择了招募其他干员的情况

### 有什么好的想法？

个人认为部分干员晋升提升更大，且能够节省希望，而且携带、部署有限
故建议将部分干员的晋升优先级调高
（当然同时兼顾更高价值干员的招募优先和多职业同时招募的顺序问题）
大家可以看看该文件，说说哪些干员的晋升优先级需要提高

### 其他内容

1. 欢迎大家合理探讨这个方案
2. 先修bug吧，这个不急
3. 如果这个涉及到其他机制不好改，可以直接将这个方案废除

**Comment by zzyyyl** [comment]
@et2012

**Comment by cybearfish** [comment]
还有我删掉阿米娅之后还是会招募阿米娅，而且不是临时招募

**Comment by et2012** [comment]
初版的招募逻辑是“完全随缘”、“谁精二就招谁”，那时候恐怕更不合理。
我设置大部分干员的晋升优先级比招募优先级低，是因为招募券是有限的，遇到了先招进来再说。
除非是那种精一完全没法用的（例如棘刺），那么TA的晋升优先级就会远远高于招募优先级。
但大部分干员并不会这么极端，精一也可以用，甚至有些干员就是只需要精一，节省希望（例如元素奶）。
如果你觉得某个干员晋升优先级应该比招募优先级更高，可以具体提出是谁。

**Comment by et2012** [comment]
我在设计优先级数值的时候有一些基本原则：
- 800以上：幻神，遇到了无脑招；或者晋升有质变（点名棘刺、银灰）。
- 600-800：基石，精一就能用
- 500-600：对策（说人话就是鸡肋，或者不适合MAA的自动战斗策略）
- 500以下：未来可期（说人话就是我觉得没什么用，我其实想删掉TA）

你说的 “晋升提升更大”，具体有多大？需要把它量化，就是优先级数值存在的意义。
如果你说所有干员的晋升优先级都应该是最高的（1000），然后1000以下再来排招募优先级（0-999），那我肯定不同意。
例如，晋升蜜酶的优先级比招募玛恩纳的优先级高？
我甚至根本不想晋升蜜酶，优先级写个 1 意思是 “医疗招募券是肯定轮不到晋升你的，除非是实在用不完了，或者是白嫖的晋升藏品”。

**Comment by cybearfish** [comment]
现在想想，大部分干员的优先级确实没必要改动，这一点是我欠考虑了
主要是一些差不多强度的干员之间的差别，比如百嘉和艾丽妮，我认为精二百嘉>精一百嘉+小鸟；精二山>精一山+煌（甚至小鸟）。还有同时招募多种职业就更麻烦了（怎么平衡）（或者直接设置一个职业优先级，遇到这种就只在一种职业里选？）
我当时是看到老猞猁和蜜梅选了蜜梅才这么想的（现在觉得MAA确实拿蜜梅比较好）
**当然这只是出于我个人的肉鸽理解，不一定适用于MAA**

**Comment by et2012** [comment]
> 比如百嘉和艾丽妮

百嘉、玛恩纳、菲亚梅塔、鸿雪、号角等新干员都还没放进优先级列表。
而且这个优先级列表是愧影肉鸽时代的了，水月肉鸽大概需要翻新一遍。

百嘉的问题在于她的2技能有一个莫名其妙的延迟（开了技能之后，那个闪烁的黄色图标要等1~2秒才会消失），会导致MAA重复识别，认为她的技能还没开，又会去点一下，然后卡住几秒。

鸿雪的问题在于她的打字机是只能部署在远程位的，但MAA认为所有召唤物都能放在近战位，会一直尝试把打字机往近战位放。在解决这个问题之前，暂时不招鸿雪比较好。

菲亚梅塔的问题在于以MAA的策略，可能会把她部署在没奶的位置，活活掉血掉死。

玛恩纳和号角倒是好像没什么问题。总之会找个合适的时间点把招募列表更新一下。

**Comment by cybearfish** [comment]
这些设计很棒，我之前是思考少了，我们可以就基石讨论一番
因为MAA里基石干员是很重要的一环【至少得把前两层过了吧】（我们是否可以将基石的范围扩大一些->技能永续/自动释放/可以随便放），那么基石的到底是晋升还是多招募一个提升更大就是应该讨论的
至于MAA如何使用决战技就靠大佬们了（笑）

**Comment by et2012** [comment]
> 这些设计很棒，我之前是思考少了，我们可以就基石讨论一番 因为MAA里基石干员是很重要的一环【至少得把前两层过了吧】（我们是否可以将基石的范围扩大一些->技能永续/自动释放/可以随便放），那么基石的到底是晋升还是多招募一个提升更大就是应该讨论的 至于MAA如何使用决战技就靠大佬们了（笑）

所以得具体到某（几）个干员，哪些干员的优先级需要调整或者新增哪些干员。

之前那个招募列表其实我也不太满意，尤其是那一堆5星，还有优先级500以下的，很多都是浪费希望，招TA我不如直接点放弃。但是这样改的话，招募列表容易演变成 “基石与幻神列表“，不在列表的一律不招，小号没有这些干员就没法玩了。

**Comment by cybearfish** [comment]
优先级的事要不在群里面征集一下，我一个人的意见肯定是没有代表性的，而github的使用人数与 8k+的群人数显然相去甚远

（其实肉鸽不太适合小号玩，只有傀影的影子才能拯救我的小号www）
很多 5 星其实小号也不会练，完全可以删了，比如雷蛇（以前傀影经常拿）；红之类的快活也是不太适合MAA的。
方舟里能用的 5 星很少，在肉鸽里更是一个不上不下的位置，不如 3、4 星功能基础省希望，不如 6 星强力，一般起的是过度作用，只有少部分功能特殊或者没有上位的有一席之地
对于新号，肉鸽能过一层投资就是胜利（就是我的小号），在MAA不能嫖好友干员的前提下，（即便能嫖）想往上走基本不可能，不如一开始就不考虑；毕竟自己打都不一定能打过，为什么要奢望MAA帮你打
就是说：**MAA可以基本不考虑小号肉鸽**
    当然，这只是我的个人观点

**Comment by MistEO** [comment]
插一嘴题外话，现在有个问题是选中了非 json 里的干员之后，不知道给他选哪个技能，通常就 1 技能直接上场了。或许我们可以把所有干员的信息都放到 json 里，如果不好用优先级就是 0 或者负数等，起码保证技能是正确的那个

**Comment by cybearfish** [comment]
有点好奇，为什么会选其他的非json干员呢，我就遇到过几次选阿米娅，芳汀（1技能漏完了）之类的

**Comment by et2012** [comment]
> 有点好奇，为什么会选其他的非json干员呢，我就遇到过几次选阿米娅，芳汀（1技能漏完了）之类的

"无候选干员时随机招募一个精一50级以上的干员" 是从初版招募系统继承的逻辑，当时没有招募优先级，所以谁等级高就招谁。
新增了招募优先级之后，为了防止一些意外放弃招募的情况，所以保留了这个逻辑。

例如拿到了白嫖的晋升藏品，但可晋升干员不在招募列表里。
由于晋升和招募是同一个界面，程序不知道现在是不是白嫖了一个晋升藏品，一律按招募优先级来算的话就应该点放弃招募。
但实际情况是：既然是白给的为什么要放弃，那就随机选一个等级最高的让TA晋升。

**Comment by zzyyyl** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2019#issuecomment-1263206091
玛丽说的也是一个比较好的解决方案（
