### ISSUE TITLE
Help with the proofreading of glossary? [Skip label]

### ISSUE THREAD

**Issue by LYZhelloworld** [MaaAssistantArknights/MaaAssistantArknights#2020]
### The problems you have encountered?

Hi @wallsman,

Thank you for contributing to the i18n of docs! Here we have something important that may need your help.

Would you like to help check if there is anything wrong or inconsistent in [Glossary](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/master/docs/glossary)? This would be very helpful because some of our translators do not have JP version client and could not confirm these proper nouns.

@wallsman 様へ

ドキュメントの作成にご協力いただきありがとうございました！今、あなたの助けが必要だと思う重要なことがあります。

[こちら](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/master/docs/glossary)のファイルは用語集です。その用語集の校正を手伝ってくれませんか？一部の翻訳者は日本語クライアントが手に入れませんから、用語が正しいかどうかわかりません。

**Comment by wallsman** [comment]
ざっと確認した限り問題はないと思います。
何点か不明部分があったためスクリーンショットでも構わないので該当部分を教えていただけると助かります。

I don't think there is a problem as far as I can tell from a quick check.
I would appreciate it if you could provide me with a screenshot of the relevant part, as there were a few points that were unclear.

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/glossary/general.md

どの部分で使用している分からない部分
- 情报
トップ画面だと思うのですが、友人のCN版の画面を見ても該当部分がわかりませんでした。
”好友”の下なら変更の必要があります。

I think it's the top screen, but I couldn't find it on my friend's CN version.
If it is under "好友" then it needs to be changed.

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/glossary/operators.md

Devに抜けていた部分は既にコミット済です。

The part that was missing in Dev has already been committed.

**Comment by MistEO** [comment]
Is this done?

**Comment by wallsman** [comment]
If the question part is resolved, we are done.
