### ISSUE TITLE
水月肉鸽的干员摆放及朝向问题

### ISSUE THREAD

**Issue by Cowjiang** [MaaAssistantArknights/MaaAssistantArknights#2025]
### 说说你遇到的问题？

有时候，这些干员的摆放位置和朝向好迷~

![9af24cc04fa176fe14be28a5eadd67d](https://user-images.githubusercontent.com/57822554/193227695-8bf8c31d-3bf4-49c5-90ea-b1c191e68372.jpg)

![a63ab917b7a5187d50f2b1336e69341](https://user-images.githubusercontent.com/57822554/193227522-21114d3b-ec76-421c-8d32-bb7867844daa.jpg)

![7758f503a8785678a38019f90659306](https://user-images.githubusercontent.com/57822554/193253093-140e52d5-3889-4084-aaa4-0e1ba3e30c1e.jpg)

**Comment by MistEO** [comment]
啥版本的，新版本应该没这问题了

**Comment by AshHuangQ** [comment]
![image](https://user-images.githubusercontent.com/74441922/193267870-7cd7ac13-de00-416b-8d67-53c0bdb4ceb6.png)
射手部队，桃金娘放门口，无缝开技能漏怪

**Comment by nightofknife** [comment]
我修
我修
呜呜呜
