### ISSUE TITLE
水月肉鸽在开始时反复进入退出

### ISSUE THREAD

**Issue by qwerdvd** [MaaAssistantArknights/MaaAssistantArknights#2027]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

已经在选项中打开了 For Mizuki
在水月肉鸽开局后，若游戏闪退等原因，肉鸽闪退
重新进入后，显示还在肉鸽，但是没有  X  的图标
此时需要选择继续探索，重新结算一次

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9682648/asst.log)

### 截图

![Screenshot_2022 09 30_17 09 51 833](https://user-images.githubusercontent.com/105906879/193236495-123a57a9-8f5f-433a-ad05-00fe0cbff531.png)

**Comment by MistEO** [comment]
请看置顶

**Comment by MistEO** [comment]
哦不好意思，我看错了（

**Comment by zhongfly** [comment]
这算是mrfz自己的bug吧，界面不显示X
