### ISSUE TITLE
水月肉鸽技能识别错误

### ISSUE THREAD

**Issue by BBMachines** [MaaAssistantArknights/MaaAssistantArknights#2031]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

山的技能图标识别出错，导致选中蜜梅试图开技能
截图时间2022-09-30 01:38:19~2022-09-30 01:38:22

### 日志文件

[all.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9683973/all.log)

### 截图

![Screenshot_2022 09 30_01 38 19 916](https://user-images.githubusercontent.com/114692637/193266376-8e87f8d8-2168-4f81-b8af-2cd99506c228.png)
![Screenshot_2022 09 30_01 38 21 684](https://user-images.githubusercontent.com/114692637/193266379-57ae4252-4b9b-4a89-ab93-f25819af24a0.png)

**Comment by lbpdfs** [comment]
这个问题不仅限于水月肉鸽，儡影肉鸽也有出现（甚至还有偶发的反复开关山技能），不过我那时候想着多点几次技能也就是过图慢一些，就没上报

**Comment by horror-proton** [comment]
类似 #1195

**Comment by horror-proton** [comment]
想不出是啥情况, 日志看好像是识别到蜜梅头上有个技能图标? 这个是哪来的

**Comment by MistEO** [comment]
> 想不出是啥情况, 日志看好像是识别到蜜梅头上有个技能图标? 这个是哪来的

Known issue，问题是山开完技能，身上会冒那种黄色的光，然后技能图标的模板匹配阈值设的很低。不光是山，比如梓兰等三星干员 1 技能，也有可能导致这种问题；

但是如果提高阈值又可能导致技能不能正常识别，可能得从图像的角度入手解决，不会弄_(:з」∠)_ 之前加了个点完之后 1 秒钟内还识别不到可以开技能，就会点一下旁边位置取消掉

**Comment by Superexboom** [comment]
Same， 目前水月肉鸽会出现山不选2技能，一选2技能就有概率出现反复开关的现象

**Comment by MistEO** [comment]
fixed
