### ISSUE TITLE
希望肉鸽“刷源石锭”模式，能走到第二层再退。

### ISSUE THREAD

**Issue by DoublesoulS** [MaaAssistantArknights/MaaAssistantArknights#2037]
### 有什么好的想法？

肉鸽商店只要多点一下到第二层，肉鸽经验和想象点都能多很多（比起停在第一层商店退出而言）
求大大们改一下功能，进到第二层再退出肉鸽~

**Comment by zhongfly** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1959

这个事都被说了不知道多少遍了，搜一下issue就知道了
