### ISSUE TITLE
水月肉鸽得偿所愿消失的习俗卡住导致退出

### ISSUE THREAD

**Issue by 666233j** [MaaAssistantArknights/MaaAssistantArknights#2040]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽第二层结束的得偿所愿消失的习俗卡在了那个结束页面，就是中心下方有一个√按了退出的界面，然后一直没按最后自己退了，本来结束了是要进第三层的

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9686071/asst.zip)
我卡死之后自己暂停退了然后又用软件开了一把肉鸽，打到一半又想起来报告

**Comment by MistEO** [comment]
发下 `debug/roguelike/` 下的图，可以压缩一下
