### ISSUE TITLE
全自動連續公招 沒有作用

### ISSUE THREAD

**Issue by Sean1781031** [MaaAssistantArknights/MaaAssistantArknights#2041]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在設定啟用自動使用加急許可 最大招募次數也設置成100之後

在全部位置都在進行招募中的情況下

啟動自動公招會直接結束任務

是台服尚未支持這個功能嗎?
又或著是我對這個功能理解錯誤了呢?

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9686263/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/68652201/193316845-102b71f9-4f52-4e61-b427-b7c0b7dae46c.png)

### 还有别的吗？

BlueStack國際板
win10
MAA V.4.5.0

**Comment by zzyyyl** [comment]
自动公招只有在有空余位置的时候才会执行。`自動使用加急許可` 也是如此。
这应该是 by design。

btw：`自動使用加急許可` 是用于一次性使用加急许可的，日常使用不必点上这个选项

**Comment by Sean1781031** [comment]
我是想要刷黃票 所以才想用用看全自動公招的

**Comment by zzyyyl** [comment]
那你可以手动把一个位置用加急许可加速，空出一个位置就可以使用这个功能了

**Comment by horror-proton** [comment]
> 自动公招只有在有空余位置的时候才会执行。`自動使用加急許可` 也是如此。 这应该是 by design。
> 
> btw：`自動使用加急許可` 是用于一次性使用加急许可的，日常使用不必点上这个选项

不是的, 他是没有从结果里过滤出 `立即招募` 我暂时没搞清楚为什么
