### ISSUE TITLE
水月肉鸽任务完成后选择物品界面卡住

### ISSUE THREAD

**Issue by sldark2000** [MaaAssistantArknights/MaaAssistantArknights#2043]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽任务完成后选择物品界面卡住，之前a4以前是部分藏品和宝箱会卡，a5更新后只有原石锭也卡住了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9686494/asst.log)

### 截图

![2022-10-01_01-09-32 527_raw](https://user-images.githubusercontent.com/77153417/193323127-717c5f0b-7a6f-493e-bf7c-f96db1147d3b.png)
![2022-10-01_01-13-56 176_raw](https://user-images.githubusercontent.com/77153417/193323138-f9bc7723-544f-4181-b58f-ad6653d6b79f.png)

**Comment by MistEO** [comment]
哪个时间点呀（这两张图的文件名叫啥

**Comment by sldark2000** [comment]
2022-10-01_01-09-32.527_raw.png
2022-10-01_01-09-34.323_raw.png
2022-10-01_01-13-56.176_raw.png
2022-10-01_01-13-57.901_raw.png

**Comment by MistEO** [comment]
> 2022-10-01_01-09-32.527_raw.png 2022-10-01_01-09-34.323_raw.png 2022-10-01_01-13-56.176_raw.png 2022-10-01_01-13-57.901_raw.png

你发的这两张叫啥，emm 要不直接打个包一起传下吧

**Comment by sldark2000** [comment]
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9686534/debug.zip)

压缩包包括两次选择物品界面卡住和两种不同的骑士事件卡住的截图和日志
