### ISSUE TITLE
检测模拟器出错请使用管理员权限打开本软件或手动设置连接

### ISSUE THREAD

**Issue by baodin0** [MaaAssistantArknights/MaaAssistantArknights#2046]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

检测模拟器出错请使用管理员权限打开本软件或手动设置连接
本来挂了几个小时没什么问题来着，复制过以后就这样了，我甚至直接群文件下载的压缩包到其他电脑上也是这样，无论我怎么重启，重新删掉解压，都启动不了了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9689236/asst.log)

### 截图

![QQ截图20221001085943](https://user-images.githubusercontent.com/114737414/193376974-4b69b782-68a4-4512-a479-b34b4c04d155.png)
![QQ截图20221001090028](https://user-images.githubusercontent.com/114737414/193377017-5c759eef-211a-4bc0-ba0d-4045f99cd86f.png)
![QQ截图20221001090059](https://user-images.githubusercontent.com/114737414/193377034-de63301f-0297-4277-9c01-d2f184568a26.png)
![QQ截图20221001090111](https://user-images.githubusercontent.com/114737414/193377038-e0dae417-c26e-48ed-b76a-03059c559033.png)

### 还有别的吗？

蓝叠，夜神，win10，5600x和570

**Comment by horror-proton** [comment]
尝试把软件里的 gui.json 备份后删除看看有没有解决 (也许发一下里面的内容?)

**Comment by MistEO** [comment]
手动填一下地址就好了

**Comment by baodin0** [comment]
> 手动填一下地址就好了

我把注册表全部删除以后解决了这个问题，应该是之前复制导致配置错误了

**Comment by baodin0** [comment]
> > 把蓝叠的模拟器复制了一遍
> 
> 这是什么意思,是怎么操作的

就是说我本来可以用的模拟器给他克隆了一份，想尝试多开

**Comment by MistEO** [comment]
没问题了的话我关咯

**Comment by baodin0** [comment]
> 没问题了的话我关咯

嗯嗯
