### ISSUE TITLE
水月肉鸽bug反馈

### ISSUE THREAD

**Issue by Soupcpu** [MaaAssistantArknights/MaaAssistantArknights#2047]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

使用自动肉鸽时会出现点开水月肉鸽而不进行游戏直接返回主页面并反复上述操作

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9689283/asst.log)
时间点应该在10/1 9:20-22分左右

### 还有别的吗？

模拟器：逍遥模拟器 安卓7 64位

**Comment by MistEO** [comment]
请看置顶
