### ISSUE TITLE
在水月肉鸽的时候，干员部署顺序

### ISSUE THREAD

**Issue by JammyR** [MaaAssistantArknights/MaaAssistantArknights#2049]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在水月肉鸽的时候，使用默认阵容，由于优先级内的干员只有煌，所以是煌+默认医疗+默认法师开局，但是开局后，每次部署顺序都是先医疗再煌，每次都是费用够或者差一点点费用部署煌的时候，先上了医疗，麻烦看看，谢谢！

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9689370/asst.log)
由于每次都是，直接看每次开局的情况即可，谢谢

### 截图

![1](https://user-images.githubusercontent.com/15321501/193380079-ede02620-8e01-4d7a-9104-fc4da028b47e.png)
![2](https://user-images.githubusercontent.com/15321501/193380082-5624d95f-a14b-4a07-93da-5ec00acd115e.png)

**Comment by zzyyyl** [comment]
煌费太高了。
Simular to https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1965

**Comment by MistEO** [comment]
> 煌费太高了。 Simular to #1965

我还没看，和费用高有啥关系啊

**Comment by zzyyyl** [comment]
> > 煌费太高了。 Simular to #1965
> 
> 我还没看，和费用高有啥关系啊

费高了就会迟下

**Comment by zzyyyl** [comment]
我记得是超过一半的人available的时候才会开始下人的逻辑，但是煌费太高导致两次都是煌不够费的时候就下人，这时候自然选不上煌

**Comment by MistEO** [comment]
> 我记得是超过一半的人available的时候才会开始下人的逻辑，但是煌费太高导致两次都是煌不够费的时候就下人，这时候自然选不上煌

一个人都没上的时候没有这个逻辑的，是近卫/先锋有限
