### ISSUE TITLE
水月肉鸽bug

### ISSUE THREAD

**Issue by angel-233** [MaaAssistantArknights/MaaAssistantArknights#2050]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在不期而遇中摇塞子妖道好运相连会给两个收藏品，界面会停在 不期而遇 不动。

### 日志文件

1

**Comment by angel-233** [comment]
![image](https://user-images.githubusercontent.com/62496000/193384021-e3625717-d474-48f6-92c7-2776fa22ee8f.png)

**Comment by MistEO** [comment]
所以日志文件呢，必填的意思是打个 1 吗

**Comment by angel-233** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9689464/asst.log)

**Comment by angel-233** [comment]
debug图片
![2022-10-01_10-58-15 873_raw](https://user-images.githubusercontent.com/62496000/193385916-848f9173-c275-4481-88d6-8a96bd743cba.png)

**Comment by MistEO** [comment]
更新下试试
