### ISSUE TITLE
水月肉鸽事件卡住及地图识别出错

### ISSUE THREAD

**Issue by Superexboom** [MaaAssistantArknights/MaaAssistantArknights#2051]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

相关事件的卡住已经在debug中看到数次，地图的识别问题也出现多次，都为同一地图

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9689427/asst.log)

### 截图

![2022-10-01_11-11-53 422_raw](https://user-images.githubusercontent.com/54000348/193384402-98527766-662e-4a6c-b0a5-451218b7ebe4.png)
![2022-10-01_11-11-51 000_raw](https://user-images.githubusercontent.com/54000348/193384404-791bda4f-e779-4364-a726-6d3debf7ea30.png)
![2022-09-30_21-02-57 667_raw](https://user-images.githubusercontent.com/54000348/193384405-a0842cad-e897-4da4-8bf4-4b317d7334e6.png)
![2022-09-30_21-02-55 166_raw](https://user-images.githubusercontent.com/54000348/193384406-d4831e1c-17af-4e97-8941-ce0595c406a4.png)
![2022-09-30_20-49-48 200_raw](https://user-images.githubusercontent.com/54000348/193384407-de1dd387-9536-4e96-a9a1-14a8633b1073.png)
![2022-09-30_20-49-45 898_raw](https://user-images.githubusercontent.com/54000348/193384409-259366e1-d012-40f0-99a2-6c395bead938.png)
![1](https://user-images.githubusercontent.com/54000348/193384414-fbf4e334-696a-49aa-aa2e-348a5649fa8b.png)

### 还有别的吗？

使用的是Nox模拟器 7.0.3.6版本；目前也有偶发Noxadb报错，无法证实是什么所致；也有偶发性的MAA闪退；报错与闪退的MAA版本为4.6.0-alpha4，事件与地图不识别的问题从alpha4到现在的alpha6都有

**Comment by Superexboom** [comment]
补充一下，好像也不是一定会卡，但还是卡的几率比较大

**Comment by MistEO** [comment]
更新下试试

**Comment by Superexboom** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9690084/asst.log)
alpha8依旧在该关卡识别错误，日志于18:24:59
