### ISSUE TITLE
刷理智第一次进入第十章弹出“环境难度兼容”时任务卡住继而失败

### ISSUE THREAD

**Issue by LoveLoliii** [MaaAssistantArknights/MaaAssistantArknights#2054]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

- 使用```MaaBundle-v4.6.0-alpha.6``` 进行默认勾选任务运行，在刷理智处卡住。
应该是没处理这种情况导致 卡在这个截图位置。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9689478/asst.log)
```10-01  11:42:58 任务出错：Fight```

### 截图

![Screenshot_2022 10 01_11 44 32 168](https://user-images.githubusercontent.com/12725100/193386108-0b617e83-4a02-478c-ba60-6d7eee1f678f.png)

### 还有别的吗？

- 蓝叠国际版
- Windows 11

**Comment by cybearfish** [comment]
这种只会出现一次的可以自己点一下

**Comment by MistEO** [comment]
Corner case, 没空修x
