### ISSUE TITLE
水月肉鸽重返家园节点卡住

### ISSUE THREAD

**Issue by xingyu1272** [MaaAssistantArknights/MaaAssistantArknights#2056]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在重返家园节点 估计是因为同时有两种干员 于是卡住

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9689590/asst.log)

### 截图

![2022-10-01](https://user-images.githubusercontent.com/107303890/193393519-fdabcd4e-3e0b-4737-a8a0-71bb75f67b8c.png)

**Comment by MistEO** [comment]
更新下
