### ISSUE TITLE
日服肉鸽错误

### ISSUE THREAD

**Issue by salenth** [MaaAssistantArknights/MaaAssistantArknights#2057]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

版本号为4.5，客户端为日服，使用功能为自动肉鸽，使用的模拟器为蓝叠N5
问题描述：
在选择干员界面会出现反复扫描干员列表、无法放置干员的问题
在它卡在选择预备队阶段时手动选择”煌“后，编队界面不切换技能
进入战斗后，不放置干员
以上问题经排查后确认并非日服干员名转国服干员名问题，也并非识别问题
同时，自动战斗功能和自动访问好友功能正常，但是自动公招不识别，即使有4星tag依旧空白招募。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9689616/asst.log)

### 截图

![Screenshot_2022 10 01_13 27 15 217](https://user-images.githubusercontent.com/114795190/193394099-55a57004-6c4c-4e78-b994-66245c9b8e33.png)
![Screenshot_2022 10 01_13 27 28 818](https://user-images.githubusercontent.com/114795190/193394100-6fd1560e-651b-4c0f-aabc-97ebf2f7bead.png)
![Screenshot_2022 10 01_13 26 41 701](https://user-images.githubusercontent.com/114795190/193394101-3c321f81-40cb-4a54-a721-34367a9fa5bb.png)

**Comment by zzyyyl** [comment]
日服和国服的招募界面不一样，需要改roi。

**Comment by salenth** [comment]
那咋整啊？

**Comment by salenth** [comment]
该去哪儿该roi啊？

**Comment by salenth** [comment]
而且招募界面不同的话，应该也不影响干员放置和技能修改吧？但是干员放置和技能修改也会有问题

**Comment by zzyyyl** [comment]
建议更新到测试版再试试

**Comment by salenth** [comment]
更新到最新版我记得我试过，连傀影肉鸽都进不去

**Comment by salenth** [comment]
我刚刚试过了，进了傀影界面之后就直接退出，回主界面了……

**Comment by zzyyyl** [comment]
傀影肉鸽的问题已经修了，还没发版（

**Comment by salenth** [comment]
那日服的问题会一并修复吗？

**Comment by zzyyyl** [comment]
日服问题已经大概在 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/6936700515a4d0d51964eb37b781af3cf684e406 修过了，上面不是有么

**Comment by salenth** [comment]
额，因为4.6傀影肉鸽进不去的问题，我之前在尝试使用4.5来着，那我等下次发包再试试看8

**Comment by zzyyyl** [comment]
急得话可以试试这边的 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/3167530094

**Comment by salenth** [comment]
倒也没有急到马上就要用，不过还是好奇问一句，那个是啥啊

**Comment by zzyyyl** [comment]
> 倒也没有急到马上就要用，不过还是好奇问一句，那个是啥啊

action 版本

**Comment by salenth** [comment]
刚刚更新了，但是……傀影还是进不去啊……
手动进去了都会退出来……话说傀影就是取消掉肉鸽设置里面的那个For Mizuko对吧？

**Comment by zzyyyl** [comment]
要重启一下maa

**Comment by salenth** [comment]
好家伙，出去买个夜宵的功夫就又更新了一版，但问题是……还是进不去。我不太懂你们这个语言，但我提供一个可能的解决思路，你们要不要试试把肉鸽的选择做成选项，而非现在这种是否为水月肉鸽。
瞎猜的，只是提供一个可能的方向：
有没有可能，现在的问题是因为取消选择“For Mizuko”后，本来应该定位至傀影肉鸽的识别图鉴因为未知原因没有正确定位，或者傀影肉鸽结局后，界面中被你们标定为识别图案的UI变化，导致按照正常流程进入傀影肉鸽后程序判断并非傀影肉鸽导致重新回到主页重启进入傀影肉鸽的流程？
以上是我根据它的操作做出的猜测，没有去查代码或logs，望周知

**Comment by zzyyyl** [comment]
我自己可以正常开始傀影了

**Comment by zzyyyl** [comment]
你自己需要 pin 一下傀影肉鸽
