### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by EnosRed** [MaaAssistantArknights/MaaAssistantArknights#2058]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

版本是刚刚更新的alph6 模拟器就是夜神
alpha5我记得还ok的 刚更新完想挂机肉鸽结果提示连接失败
尝试过重启模拟器以及重启maa后仍然没有得到解决 
想知道是什么原因啊或者是我不小心改了什么设置？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9689675/asst.log)

### 截图

![1664604362336](https://user-images.githubusercontent.com/113267116/193395299-9c86d66e-3b1c-4dab-87c5-6c2078e6b841.png)

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/193395403-d47e6c42-553d-43c9-a60a-9b4bc47f97ff.png)
清空地址重新勾选自动检测连接试试

**Comment by EnosRed** [comment]
ok了 不知道是自动检测的功劳还是重启的功劳哈哈哈 感谢
