### ISSUE TITLE
[肉鸽]疑似选人逻辑bug，疑似收取额外收藏品卡死

### ISSUE THREAD

**Issue by frankchenfu** [MaaAssistantArknights/MaaAssistantArknights#2060]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

本次作战选择水月肉鸽-刷蜡烛模式，突击战术分队山开局。疑似出现两个bug。
1. 一层作战掉落近卫招募券，在希望充足的情况下出现4~5次的向右滑动多次再向左滑到底的情况，且最终选择放弃招募。
2. 二层结束开收藏品时，骰到6点而额外获得一个收藏品后长时间卡顿，一段时间后直接退出探索。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9689793/asst.log)

### 还有别的吗？

mumu模拟器，Windows10.

**Comment by MistEO** [comment]
试试最新版本

**Comment by MistEO** [comment]
哦原来已经是了，打包发下 debug/roguelike 文件夹下的图吧

**Comment by frankchenfu** [comment]
图片只有这两张。
![2022-10-01_15-13-09 137_raw](https://user-images.githubusercontent.com/35485409/193398333-8156b422-1d4f-42b5-b4e9-01ebed2058c0.png)
![2022-10-01_15-13-11 483_raw](https://user-images.githubusercontent.com/35485409/193398334-72a60525-3e30-4ecb-b4b6-c36f29c489e3.png)

**Comment by zzyyyl** [comment]
修过了吧，版还没发

**Comment by MistEO** [comment]
alpha.8 修了，试试看
