### ISSUE TITLE
[肉鸽] 进入第二层时触发排异反应会卡死

### ISSUE THREAD

**Issue by onlyacat** [MaaAssistantArknights/MaaAssistantArknights#2061]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如题。
刷原石锭， 按理来说会在第二层退出。
但如果触发排异反应， 会直接卡死在界面。

### 日志文件

asst.log 16:19 左右开始出问题，50 分左右发现手动停掉
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9689935/asst.log)

### 截图

<img width="803" alt="image" src="https://user-images.githubusercontent.com/29370032/193400971-ad7cdd1c-b99e-4a10-ab90-87995b03a4e4.png">

**Comment by onlyacat** [comment]
版本是 [v4.6.0-alpha.6] 好像刚刚发了一个新版本，不知道修好了没有

**Comment by MistEO** [comment]
发下 debug/roguelike/ 下的图看看

**Comment by onlyacat** [comment]
> 发下 debug/roguelike/ 下的图看看

[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9689988/roguelike.zip)



补充过来了

**Comment by zzyyyl** [comment]
修过了

**Comment by zzyyyl** [comment]
你用的是版本是 alpha.5（
这个问题在 alpha.6 已经修了，不过现在直接下 alpha.8 就行了

**Comment by onlyacat** [comment]
> 你用的是版本是 alpha.5（ 这个问题在 alpha.6 已经修了，不过现在直接下 alpha.8 就行了

好的谢谢
