### ISSUE TITLE
水月肉鸽消失的习俗又卡住了

### ISSUE THREAD

**Issue by 666233j** [MaaAssistantArknights/MaaAssistantArknights#2062]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

消失的习俗卡在结束页面，不会按中心下方的√离开结束页面而是退出游戏

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9690069/asst.zip)
2022/10/1 18:22:41消失的习俗卡死退出

**Comment by zzyyyl** [comment]
给点图吧（
在软件目录的 `debug/roguelike` 下

**Comment by MistEO** [comment]
试试最新版

**Comment by Genicur** [comment]
> 试试最新版

我是alpha6 我在在消失的习俗也卡住了
![image](https://user-images.githubusercontent.com/93466263/193406369-54430751-6b73-4018-8532-4f2e2a6c6655.png)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9690114/asst.zip)
[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9690115/roguelike.zip)
