### ISSUE TITLE
水月肉鸽不期而遇信念卡死

### ISSUE THREAD

**Issue by 666233j** [MaaAssistantArknights/MaaAssistantArknights#2063]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

不期而遇信念卡在结束页面，和消失的习俗一样没有按下中心下方的√关闭页面而是放弃探索

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9690098/asst.zip)
2022/10/1/18:41:21不期而遇信念

**Comment by MistEO** [comment]
最新版都修了

**Comment by 666233j** [comment]
版本是v4.6.0-alpha.4

**Comment by 666233j** [comment]
额抱歉，更新太快了版本没跟上
