### ISSUE TITLE
水月肉鸽扔骰子优化

### ISSUE THREAD

**Issue by xingyu1272** [MaaAssistantArknights/MaaAssistantArknights#2064]
### 说说你遇到的问题？

水月肉鸽经常会在简单关就扔个骰子

### 有什么好的想法？

希望能判定一下高压波次（？）

### 其他内容

什么时候脚本能过海沫啊（bu

**Comment by xingyu1272** [comment]
顺便一提 在有些关干员朝向好像有问题 比如在海神的信徒煌会朝上面壁（不好意思忘截图了）

**Comment by xingyu1272** [comment]
> 顺便一提 在有些关干员朝向好像有问题 比如在海神的信徒煌会朝上面壁（不好意思忘截图了）

而且干员会放在冰祭坛的范围内

**Comment by paladiners** [comment]
个人建议是不是除了最后几关，别的时间战斗的时候就不用丢骰子了。

**Comment by zzyyyl** [comment]
> 个人建议是不是除了最后几关，别的时间战斗的时候就不用丢骰子了。

说的简单
骰子现在没做识别，会被当成召唤物直接下场的

**Comment by MistEO** [comment]
进度可以关注 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/2167

**Comment by zzyyyl** [comment]
> 什么时候脚本能过海沫啊

已经有人过辣
