### ISSUE TITLE
无法进入傀影肉鸽

### ISSUE THREAD

**Issue by Liudegloire** [MaaAssistantArknights/MaaAssistantArknights#2067]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

1. 更新后去掉for mizuki前的√并将魁影放到终端之后也无法进入傀影肉鸽，会来回在主界面-》终端-》肉鸽选择-》魁影-》肉鸽选择-》主界面循环跳动
2. 更新后在maa启动之后直接进行肉鸽会导致卡住 （去掉for mizuki前的√），必须在在for mizuki前打√才会进入行动

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9690383/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/39121540/193411195-c1f5f806-382a-4477-ac0b-9fb141cf7016.png)
![image](https://user-images.githubusercontent.com/39121540/193411199-7aac5b75-1e7e-43c0-a437-11ab485e8f77.png)
![image](https://user-images.githubusercontent.com/39121540/193411243-34e939db-f05a-43ec-b61c-1959285b6175.png)

**Comment by zzyyyl** [comment]
去掉 for mizuki 之后要重启 maa，你重启了么

**Comment by MistEO** [comment]
> 去掉 for mizuki 之后要重启 maa，你重启了么

傀影右上角有个 pin 图标，是不是有影响

**Comment by Liudegloire** [comment]
> > 去掉 for mizuki 之后要重启 maa，你重启了么
> 
> 傀影右上角有个 pin 图标，是不是有影响

没有重启，界面上好像没有写去掉之后要重启，然后那个pin的图标是发现去掉之后还是会进入水月肉鸽，在终端上固定魁影之后会进入魁影肉鸽
