### ISSUE TITLE
水月肉鸽不期而遇结束后多次停止在界面不动

### ISSUE THREAD

**Issue by angel-233** [MaaAssistantArknights/MaaAssistantArknights#2068]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在某一些不期而遇结束后停止在界面不进行操作，然后遇到bug直接结束肉鸽。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9690424/asst.log)

### 截图

![2022-10-01_21-22-43 200_raw](https://user-images.githubusercontent.com/62496000/193411695-d099284b-401b-4c7d-a5d1-e11dd2079126.png)

**Comment by angel-233** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9690424/asst.log)

**Comment by angel-233** [comment]
日志删减了一点，应该不影响，不然太大了发不出来

**Comment by zzyyyl** [comment]
给点 `debug/roguelike` 下的图（

**Comment by zzyyyl** [comment]
哦是风雨际会啊，还没做呢（

**Comment by angel-233** [comment]
debug图片
![2022-10-01_19-21-57 709_raw](https://user-images.githubusercontent.com/62496000/193433934-9bb898fe-919b-4602-b164-e9337760a073.png)
![2022-10-01_20-55-32 462_raw](https://user-images.githubusercontent.com/62496000/193433940-fdb0018c-54ee-450b-94ff-e2c0e44025dc.png)
不只是风雨际会哈哈哈

**Comment by zzyyyl** [comment]
三个认知塑造里开的关卡都没做呢
这样一张截图没用，要把整个节点的流程全部跑一遍，每个界面截张图（

**Comment by MistEO** [comment]
修了
