### ISSUE TITLE
肉鸽中遇到尖刺宝箱 海怪宝箱 MAA会选中这两个目标

### ISSUE THREAD

**Issue by SSG233** [MaaAssistantArknights/MaaAssistantArknights#2071]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如题 MAA会点一下这两个目标 导致这一局游戏会减速到结束 导致刷投资效率降低

### 日志文件

应该不用日志文件 4.6.0 alpha 6版本

**Comment by zzyyyl** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2052
