### ISSUE TITLE
信用溢出时无视黑名单的行为应该更保守一点：仅在下一次购物后剩余信用仍大于等于 300 时才进行购物

### ISSUE THREAD

**Issue by bodayw** [MaaAssistantArknights/MaaAssistantArknights#2075]
### 说说你遇到的问题？

例如当前信用值为 320，非黑名单物品已经买空，由于“信用溢出时无视黑名单”默认勾选，Maa 执行了一次购物，买了个价值 200 信用的碳。

这相当于“浪费”掉了 180 点信用，恐怕不是多数玩家所希望的。

### 有什么好的想法？

如题。不过这样一来就还要再加上识别商品价格的数字……

如果做起来很麻烦的话，我觉得至少应该把这个选项做成默认不勾选。顺便加上个注释告知玩家勾选的潜在后果，会比较好。

**Comment by zzyyyl** [comment]
link to https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1927

@Hydrogina

**Comment by Hydrogina** [comment]
加一个输入框来设定溢出值怎么样？默认溢出值是300，如果觉得浪费可以设成500

**Comment by bodayw** [comment]
> 加一个输入框来设定溢出值怎么样？默认溢出值是300，如果觉得浪费可以设成500

我觉得也不太能算是个很合理的设置。主要问题是这信用商店的东西价格，因为有 -50%、-75% 等等打折，差异经常是非常大的，所以很难在不考虑具体价格因素的前提下兼顾溢出信用的浪费和购买“无用”商品的损失。

**Comment by zzyyyl** [comment]
目前没有做打折和信用价值的识别，处理价格因素可能比较困难/麻烦。
我觉得 Hydrogina 提出的算是个可行的方案（

题外话：一般来讲，用 maa 的时候你今天满信用上限的时候明天基本上也是满的，也就是说今天不“浪费”掉一点信用，明天还得“浪费”（x

**Comment by bodayw** [comment]
非常同意再加上对商品价格的识别比较麻烦。所以我觉得这个功能暂且应该还是不要默认开启。

顺便说，我主帖里举的应该算是个比较极端的例子，但确实是真实发生在我这里了的（

**Comment by MistEO** [comment]
> 我觉得这个功能暂且应该还是不要默认开启

我觉得合理
