### ISSUE TITLE
水月肉鸽中疑似因未能识别而退出的部分场景

### ISSUE THREAD

**Issue by misakiycy** [MaaAssistantArknights/MaaAssistantArknights#2076]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

近期刷钱的时候出现了多次未能识别的情况，结合肉眼观察和debug截图与猜想反馈一下

1. “狂徒妄念”（骑士线不期而遇）界面无法识别，获得骑士线藏品后结局提示框无法识别
2. 招募干员超时或放弃，之后直接退出
3. 获得超额藏品（扔出6或者慷慨启示给了双藏品）时无法识别
4. “噬尘扩散”（叠3甲）等非两个选项的不期而遇无法识别
5. 地区委托无法识别
6. 未知原因导致卡死在关卡结束界面或地图界面

log文件很大，裁剪了连续退出2次的log，或许可以参考

### 日志文件

[asst.log.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9691740/asst.log.txt)

### 截图

debug文件夹部分图片打包

[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9691745/roguelike.zip)

**Comment by misakiycy** [comment]
debug部分截图文件
[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9691744/roguelike.zip)

**Comment by MistEO** [comment]
你用的是哪个版本？看了下图里的问题应该都修过了
