### ISSUE TITLE
肉鸽可以自己选择启用禁用干员

### ISSUE THREAD

**Issue by WWPXX233** [MaaAssistantArknights/MaaAssistantArknights#2077]
### 有什么好的想法？

希望有一个可以自己选择启用禁用干员的东西这样肉鸽就可以更好的去按照自己的练度来调整选取的范围

**Comment by zzyyyl** [comment]
可以自己调整 `resource/roguelike_recruit.json` 

~~（这东西原计划是不让用户调整的~~
