### ISSUE TITLE
请问现在还能刷猩红血钻的蜡烛吗

### ISSUE THREAD

**Issue by yunus1129** [MaaAssistantArknights/MaaAssistantArknights#2078]
### 说说你遇到的问题？

水月肉鸽出来后点击肉鸽日常不能刷傀影了 只能刷水月了 请问有办法区分一下吗  感谢！

**Comment by MistEO** [comment]
理论上是兼容的，实际上最近修改水月把部分傀影的代码也跟着改了，但还没来得及测，可能会有问题。

有需要的话先用 v4.5.0 刷傀影吧，之后 v4.6.0 的正式版本应该会保障傀影也可用

**Comment by zzyyyl** [comment]
修过了 beddc7c828126c678391e0b4da288db6d2c2d58a
还没发版
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2067

**Comment by yunus1129** [comment]
好的 谢谢大佬




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月2日(星期天) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 请问现在还能刷猩红血钻的蜡烛吗 (Issue #2078)





 
理论上是兼容的，实际上最近修改水月把部分傀影的代码也跟着改了，但还没来得及测，可能会有问题。
 
有需要的话先用 v4.5.0 刷傀影吧，之后 v4.6.0 的正式版本应该会保障傀影也可用
