### ISSUE TITLE
水月rogue在电脑熄屏之后会出错，导致停止继续刷图

### ISSUE THREAD

**Issue by clearrrlove** [MaaAssistantArknights/MaaAssistantArknights#2080]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如标题所说，使用的是雷电模拟器
在每次电脑因为长时间不运行而熄屏之后就会产生这个后果，最近一次就是今天（十月二号）凌晨开启脚本，一直开着电脑而在十一点左右才开始继续使用，这之后看脚本日志就发现到五点左右就不再继续自动刷图，并且点开最小化的模拟器界面发现一直停留在数据回溯界面不会再继续动弹，希望能请大家处理一下

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9691853/asst.zip)

大概是今天凌晨四点四十分和五点之间，之后虽然没有关闭电源让脚本和模拟器一直运行，但它也一直卡在数据回溯界面没有动作，直到我十一点钟重新使用电脑进行查看为止

### 截图

![电脑设置截图](https://user-images.githubusercontent.com/114846394/193439664-2f8e4936-1e82-4926-a8b1-2ff7198ff4da.png)
![停留界面截图](https://user-images.githubusercontent.com/114846394/193439864-f229cb8a-d4c2-4a6e-b579-51e00af69b2e.png)

可以保证只是熄屏，没有进入睡眠模式

**Comment by zhongfly** [comment]
建议查一下windows日志，我之前也有遇到明明没设置自动休眠结果还是睡眠/休眠了。后来看日志发现是触发了s0睡眠

**Comment by clearrrlove** [comment]
> 建议查一下windows日志(事件查看器-系统分类)，我之前也有遇到明明没设置自动休眠结果还是睡眠/休眠了。后来看日志发现是触发了s0睡眠

多谢回复，不过我这个情况还是有点不对劲
就是我之前忘了接下来要描述的东西，今天大概是两点半左右我就睡觉去留着电脑自己运行了，但是模拟器一直正常刷图到了将近五点左右才出现卡在数据回溯界面不会动的现象，感觉是时间上的这个问题或许和睡眠没有关系
而且之前用已经完善的脚本刷傀影rogue就没发生因为睡眠导致模拟器和脚本停用的事情，所以感觉还是得求制作组各位来帮忙看看是不是真的bug，能不能解决

**Comment by zhongfly** [comment]
用最新测试版再试试
看看debug的子文件夹里有没有图片，新版测试版卡图时会自动截图

**Comment by MistEO** [comment]
应该和睡眠没有关系吧，数据回溯这个现在没做识别，只是单纯的卡住了。

duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1997

**Comment by MistEO** [comment]
话说这个数据回溯，是不是只有在当前设备上第一次打肉鸽才会出？之后就没有了

**Comment by clearrrlove** [comment]
> 用最新测试版再试试(反馈问题时，提供诸如软件版本号之类的信息是基本要求) 看看debug的子文件夹里有没有图片，新版测试版卡图时会自动截图“新增 水月肉鸽 卡住时，自动保存截图到 debug/roguelike/”

啊，这个是我的失误，在另外一个反馈贴里给了版本截图但是这里就忘了
这两天是一直在时不时手动点击更新，已经是最新的测试版8了
.....然后听取老哥你的建议查看debug截图之后发现只有rogue的一个报错储存，存了有四百三十五张截图，最早的29号到今天的2号都一直在报错来着
![QQ图片20221002142352](https://user-images.githubusercontent.com/114846394/193441076-4e3ad984-a270-4819-8be7-39dcef974a44.png)
![QQ图片20221002142356](https://user-images.githubusercontent.com/114846394/193441083-032b9ed6-713d-428f-bb35-c4a3355cb51c.png)
![QQ图片20221002142822](https://user-images.githubusercontent.com/114846394/193441106-6129a0d6-da1b-46b2-bc75-3b71182fabb8.png)

**Comment by clearrrlove** [comment]
> 话说这个数据回溯，是不是只有在当前设备上第一次打肉鸽才会出？之后就没有了

......好像是？不过不好意思我也没注意这一点o(╥﹏╥)o
不过我使用的手机和模拟器都并不是第一次刷rogue，所以我猜应该就是脚本不知道发生了啥，就在结算界面主动点了左上角的数据回溯进入界面，导致卡住嘞
