### ISSUE TITLE
水月rogue在开局和局中招募干员时出现问题

### ISSUE THREAD

**Issue by clearrrlove** [MaaAssistantArknights/MaaAssistantArknights#2081]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如描述所说，使用模拟器为雷电模拟器
详细描述就是在开局（我所设置的是后勤分队，近卫辅助治疗，令开局）招募令之后脚本会对着那后勤分队额外给的两点希望“犯难”，在继续选择近卫招募时候不知道招募谁，连月见夜这些零希望干员都不会招募直接导致空选，之后因为缺少干员而过关失败
还有就是在手中已经是零希望招募不了任何干员时也一直卡在招募界面，而不是选择一位通用零希望干员了事或者速速退出继续刷图，希望能进行查看和处理

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9691870/asst.zip)

最近一次大概是在十一点到一点内

### 截图

![脚本配置1](https://user-images.githubusercontent.com/114846394/193440252-e1fb4a58-3833-4fab-9227-9f097c223de5.png)

![配置2](https://user-images.githubusercontent.com/114846394/193440297-f66e0efb-76c8-4732-b4a5-ae2e15179ff2.png)
![招募结果](https://user-images.githubusercontent.com/114846394/193440300-115cb9c2-8427-4c8b-979b-929465703ccb.png)

**Comment by clearrrlove** [comment]
少了个地面阻挡位＋运气不好三连战＋为了刷源石锭存款所以没有选血多的指挥分队＝数次漏的比咱们国足门将还厉害直接嘎掉_(:з」∠)_

**Comment by zzyyyl** [comment]
建议开局别带令，maa 对于召唤类辅助的处理很不好

**Comment by clearrrlove** [comment]
> 建议开局别带令，maa 对于召唤类辅助的处理很不好

好吧，那我就换个人了

**Comment by MistEO** [comment]
修了

**Comment by clearrrlove** [comment]
> 修了

感谢感谢，爱你！

**Comment by MistEO** [comment]
> 修了

看了下问题仍然存在，orz，下个版本再说（

**Comment by MistEO** [comment]
发个 beta.2 好了

**Comment by MistEO** [comment]
记录一下问题

![image](https://user-images.githubusercontent.com/18511905/193472240-85b2181d-e40e-48dc-9699-0b1d7ef157de.png)
![XGB(XAP$ L)X V0CUK4NYX7](https://user-images.githubusercontent.com/18511905/193472242-11968d2c-ff8f-40c7-995e-b380d45d38a1.jpg)
