### ISSUE TITLE
在4.6.0a8中，点击自动肉鸽后没有反应

### ISSUE THREAD

**Issue by abbaccadd0** [MaaAssistantArknights/MaaAssistantArknights#2082]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在4.6.0a8的MAA中，点击自动肉鸽后，模拟器没有任何反应
其他功能均能正常运行

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9692006/asst.log)

### 截图

![Snipaste_2022-10-02_15-43-01](https://user-images.githubusercontent.com/39579855/193443824-37ec5e72-2fe8-4d9b-9df5-3c9f0d3896d8.png)

### 还有别的吗？

模拟器：蓝叠模拟器Hyper-V版
系统：Windows 11

**Comment by zzyyyl** [comment]
检查 For Mizuki 是否打开。
