### ISSUE TITLE
有什么办法能在Arm芯片的MacOS下运行吗

### ISSUE THREAD

**Issue by AbyssVoyager** [MaaAssistantArknights/MaaAssistantArknights#2083]
试过Parallel Desktop安装Win11虚拟机，但是Win11 on arm不支持安卓模拟器，在网上也没找到类似的资料，所以来这里问一下，感激不尽

**Comment by zhongfly** [comment]
wsa好像是支持arm版的win11…不过这就变成套娃了，mac套win，win套android…

另外mac能运行linux版的maa吗？(maa支持linux，但要自己编译)

**Comment by bakashigure** [comment]
@ChingCdesu

**Comment by ChingCdesu** [comment]
首先，mac肯定不能运行linux版本的可执行文件或者动态库里的代码。
第二，编译肯定是有办法的，我能想到的就是通过安装mac下的gcc和g++编译，因为他们支持c++20的大部分特性，而apple- clang还有很多特性未实现。但是很多库提供者只会预编译好apple-clang的mac版本，这就意味着你需要自己重新编译maa所有需要的库，我尝试过大概在30个c++库左右（如果一个库依赖于另一个，则两个都需要自己编译）。
第三，原生的苹果设备的性价比本身就不高，关键在于他的系统优化做的比windows要好很多，实际硬件还是比较差的。而虚拟化这个东西，他完全吃硬件，与软件优化没太大关系。这就导致了苹果设备在开启一个虚拟机运行方舟后，并没有多少资源给到maa。

综上三点，我们暂时放弃了对macOS的支持。

**Comment by AbyssVoyager** [comment]
> 首先，mac肯定不能运行linux版本的可执行文件或者动态库里的代码。 第二，编译肯定是有办法的，我能想到的就是通过安装mac下的gcc和g++编译，因为他们支持c++20的大部分特性，而apple- clang还有很多特性未实现。但是很多库提供者只会预编译好apple-clang的mac版本，这就意味着你需要自己重新编译maa所有需要的库，我尝试过大概在30个c++库左右（如果一个库依赖于另一个，则两个都需要自己编译）。 第三，原生的苹果设备的性价比本身就不高，关键在于他的系统优化做的比windows要好很多，实际硬件还是比较差的。而虚拟化这个东西，他完全吃硬件，与软件优化没太大关系。这就导致了苹果设备在开启一个虚拟机运行方舟后，并没有多少资源给到maa。
> 
> 综上三点，我们暂时放弃了对macOS的支持。

没想到能得到这么严谨的答复，十分感谢！

**Comment by ChingCdesu** [comment]
在apple-clang能有对比较好的c++20特性的支持后，就会考虑对macOS平台的支持，用法可能是远程连接运行在服务器上的Android虚拟机，针对远程连接的速度和体验等我们还得后续优化。
而在mac上运行模拟器，可能需要等模拟器厂商支持苹果自研芯片m系列平台的支持。

**Comment by MistEO** [comment]
tg 群里有大佬编过了，link to https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/2159

**Comment by hguandl** [comment]
我初步完成了 MAA 在 M1 上的编译和运行。为了解决上面提到的诸多问题，我用了一些 hack 手段。这些修改是否可以合并、如何进行合并还需要再讨论一下。

> 而apple- clang还有很多特性未实现。

这一点已经在 #2159 解决，用了一些 workaround 兼容了 C++20 的新特性。

> 但是很多库提供者只会预编译好apple-clang的mac版本，这就意味着你需要自己重新编译maa所有需要的库，我尝试过大概在30个c++库左右（如果一个库依赖于另一个，则两个都需要自己编译）。

MAA 的主要依赖库有两个，OpenCV 和 PaddleOCR。其中前者是成熟的跨平台库，可以轻松地在 macOS 编译。而后者涉及到的依赖项特别多，构建过程很复杂。考虑到这个库的功能是做文字识别，而 Apple 是有系统 API 来实现的，我选择写了一个兼容 PaddleOCR API 的库，内部实现替换为 Apple 的 Vision 框架：https://github.com/hguandl/VisionOCR 。在使用这个库的前提下，CMake 构建可以简化为

```cmake
if (APPLE)
    add_subdirectory(3rdparty/VisionOCR)
    target_link_libraries(MeoAssistant
        vnocr
        "-framework CoreFoundation"
        "-framework CoreGraphics"
        "-framework Vision"
    )
else ()
        # Linux libraries...
endif (APPLE)
```

对于上面提到的这个库是否要合并可能还需要一些讨论。最好的办法就是提供一些基准测试，看 VisionOCR 是否达到了可以平替 PaddleOCR 的效果。如果可以合并的话可以极大地方便 macOS 版本 MAA 的构建。

至于安卓模拟器，目前 M1 上可用的只有 AVD，[NGA](https://nga.178.com/read.php?tid=32723867) 上有相关讨论。
