### ISSUE TITLE
出现未知错误

### ISSUE THREAD

**Issue by zzyyddsw** [MaaAssistantArknights/MaaAssistantArknights#2085]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

使用基建换班功能，开始能用修改了几次排班方案再导入文件部分识别错误 重启电脑后识别模拟器发现未知的错误
尝试过手动选择adb路径，下载adb并选择，更新新版本后自动选择，更新模拟器后重试仍然不行

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9692290/asst.log)

### 截图

![%BI05@Z__1PDQ~%ZU9FG0Y6](https://user-images.githubusercontent.com/114858768/193450456-ee5f8efc-070d-4d71-be98-b17e3128ffed.png)

### 还有别的吗？

蓝叠模拟器

**Comment by MistEO** [comment]
"filename":"D:\\桌面 文档 下载  视频 图片\\下载\\MaaBundle-v4.5.0 (1)\\resource\\custom_infrast\\1664705361725020 (1).json"

这什么鬼路径。。

**Comment by MistEO** [comment]
换个不要这么邪门的（）

**Comment by horror-proton** [comment]
我感觉并不是路径的问题, 试了一下这种路径是可以正常读取的, 但是日志的报错信息好像不对, 如果 json 解析失败返回了 `nullopt` (比如文件是空的或者不是 json 格式), 也会打印 `custom infrast file not exists` 🤔. 
要不让作者发一下这个这个自定义文件

**Comment by zzyyddsw** [comment]
今天又尝试了一下把文件夹挪出来了更新了能正常执行除了基建所有的任务。
又换了内置的基建文件可以正常运行，整不会了 一开始可以正常运行的
换班文件是在一图流自己改的 id1664779551085013   网址https://yituliu.site/riicCal/
因为不能上传json文件就改了个后缀上传了（
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9695245/asst.log)
[1664779551085013.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9695250/1664779551085013.txt)

**Comment by MistEO** [comment]
json 生成的有问题，我找一图流的大佬去看了

**Comment by zzyyddsw** [comment]
那该怎么解决（
 是我修改的有问题吗，我去重新改一份？

**Comment by zzyyddsw** [comment]
修改了一份问题解决了 感谢两位
