### ISSUE TITLE
宿舍蹭信赖问题

### ISSUE THREAD

**Issue by lindsayee** [MaaAssistantArknights/MaaAssistantArknights#2092]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

当前版本：v4.6.0-alpha.8
当宿舍里已进驻了没有满信赖的干员，同时又有未满心情的干员时，
MAA会先取消所有进驻的干员，逐一添加未满心情的干员，
若没有更多干员需要入驻，MAA会直接筛选未进驻的干员，
但是，在没点击确定的情况下，被取消的干员似乎还不算未进驻，此时搜不到。
这样就会导致宿舍空出位置，原先应该要蹭信赖的干员没有成功蹭到信赖。
不确定YJ这样是否设计如此，目前蹭信赖的实现可以考虑进行优化。
附图是手动操作的逻辑。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9692903/asst.zip)
时间点在：
10-02  23:22:35 当前设施：Dorm 3
10-02  23:23:18 完成任务：Infrast

### 截图

![image](https://user-images.githubusercontent.com/4250090/193463235-17a9a8e7-0740-42e8-82f8-61031c30ba39.png)
![image](https://user-images.githubusercontent.com/4250090/193463259-0d7d0359-0ef7-4b25-afeb-b958cc2e7133.png)
![image](https://user-images.githubusercontent.com/4250090/193463281-3272bbaf-a085-438a-966a-a34bd3453aec.png)
![image](https://user-images.githubusercontent.com/4250090/193463302-f43658d3-edc8-4cf1-977d-86a6986a9cd8.png)
![image](https://user-images.githubusercontent.com/4250090/193463410-4ed6d408-dd32-4ea0-9f8a-edc60543c743.png)

**Comment by MistEO** [comment]
嘶，感觉有点难解决

cc @Hydrogina

**Comment by lindsayee** [comment]
没满员的情况下先确认然后再进入该宿舍进行补位是否可行……？
不过这种情况应该比较少见，不改也影响不大╮(╯_╰)╭（吧（应该

**Comment by Hydrogina** [comment]
> 没满员的情况下先确认然后再进入该宿舍进行补位是否可行……？ 
应该可以，可以在识别到的干员全部满信赖后先确认然后再进入该宿舍进行补位
