### ISSUE TITLE
没有菲亚梅塔导致的bug

### ISSUE THREAD

**Issue by mxtzj** [MaaAssistantArknights/MaaAssistantArknights#2099]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在使用基建排班生成器时，我关掉了菲亚梅塔后面的绿色按钮，并且把巫恋的名字也删了，并且把宿舍全部设置成自动填充，结果maa依然在寻找着菲亚梅塔，并且找不到菲亚梅塔就不正常工作，最后直接罢工，宿舍里连车尔尼都没有，本来是选上了的，因为它找菲亚梅塔所以它又取消掉了车尔尼，最后迷迭香和黑键没吃到宿舍提供的半点效率，最后还是我手动填满的宿舍

### 日志文件

5点到6点之间

### 截图

![image](https://user-images.githubusercontent.com/114884657/193478209-706b09f8-5271-4e09-b4ee-3c8ea9468dbe.png)
![image](https://user-images.githubusercontent.com/114884657/193478210-34a5bd81-0668-4c91-b91a-adc2708cb6c0.png)

**Comment by MistEO** [comment]
日志没传上来

**Comment by MigdalBavel** [comment]
借路问下排班生成器在哪里下的啊？

**Comment by MistEO** [comment]
> 借路问下排班生成器在哪里下的啊？

https://yituliu.site/riicCal/ 在线的

**Comment by mxtzj** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9696049/asst.log)

**Comment by mxtzj** [comment]
> 日志没传上来

不知道怎么编辑到日志哪里，发在评论里了

**Comment by mxtzj** [comment]
发现是没有更新到4.6版本的4.5版本的bug，更新到4.6之后就没有了，之前用自动更新以为4.5是最新版本
