### ISSUE TITLE
周日剿灭防瞎功能

### ISSUE THREAD

**Issue by atkdefender** [MaaAssistantArknights/MaaAssistantArknights#2100]
### 说说你遇到的问题？

顾着打肉鸽忘了剿灭了5555

### 有什么好的想法？

周日，检测作战终端UI右侧的todolist，如果还有红色[合成玉]字样，就像公招发现五星六星那样，弹个通知说“周日了，剿灭还没有打完，还不可以休息哦。”

**Comment by zzyyyl** [comment]
界面上有 `周日了，记得打剿灭哦~` 的，不看是吧.jpg

**Comment by martinwang2002** [comment]
在舟游终端里会有本周合成玉进度条哎~

**Comment by ABA2396** [comment]
周一周日都有提示，但感觉都没人看（）

**Comment by atkdefender** [comment]
> 界面上有 `周日了，记得打剿灭哦~` 的，不看是吧.jpg

一个住校生，每周离开家时，
如果家人每次都会说，“好好穿衣服，别着凉”，就算夏天也这样说，那自然不会当回事。
如果家人只在天气变冷时候说，那多少会引起点注意。

**Comment by atkdefender** [comment]
> 在舟游终端里会有本周合成玉进度条哎~ maa的弹窗提示可以进一步提醒，但是这也不能防瞎（指没看到通知.jpg）

用Maa后我哪里还见过终端，只见过主界面和基建页面Doge
