### ISSUE TITLE
关于 `roguelike_recruit.json`

### ISSUE THREAD

**Issue by wpx20021125wp** [MaaAssistantArknights/MaaAssistantArknights#2102]
### 说说你遇到的问题？

 如何让一个干员在精英之前使用一个只开启一次的技能
```json
        {
            "name": "银灰",
            "skill": 3,
            "alternate_skill": 2,
             "skill_usage": 2,
            "recruit_priority": 500,
            "promote_priority": 800
        },
```
求大佬解答一下谢谢

**Comment by zzyyyl** [comment]
虽然不完全一样，但可以参考 `docs\3.3-战斗流程协议.md`

**Comment by zzyyyl** [comment]
草，我记得按照现在的逻辑好像不能确定你到底用的是什么技能来着，可能目前版本还不能选两个技能模式不一样的技能（
（不然你的真银斩也只会开一次 ^_^

**Comment by wpx20021125wp** [comment]
这可太草了

**Comment by wpx20021125wp** [comment]
那可以随意添加干员吗

**Comment by wpx20021125wp** [comment]
肉鸽文件里面可以添加等级要求字段吗

**Comment by zzyyyl** [comment]
> 肉鸽文件里面可以添加等级要求字段吗

不行（
参考 docs 的同时，也参考参考 roguelike_recruit.json 里原有的其他字段，基本上就是能用的字段了

**Comment by zzyyyl** [comment]
> 那可以随意添加干员吗

这倒是可以，但是不要添加地面辅助和高台先锋这类，会出问题

**Comment by wpx20021125wp** [comment]
招募优先级是按照recruit_priority的权级算还是按照顺序执行

**Comment by zzyyyl** [comment]
按权重来，recruit_priority 是招募优先级，promote_priority 是晋升优先级

**Comment by wpx20021125wp** [comment]
好的我写了一份准备运行一下试试）

**Comment by wpx20021125wp** [comment]
干员全写上会增加检测时长吗

**Comment by zzyyyl** [comment]
增加不了多少，但是你全写上了建议来个 pr，给 maa 做点贡献（x

**Comment by wpx20021125wp** [comment]
pr是什么）

**Comment by wpx20021125wp** [comment]
我也没敢写多少
增加了几个我觉得能用得上的

**Comment by wpx20021125wp** [comment]
在跑了看看能不能打死）
