### ISSUE TITLE
水月肉鸽通宵挂机时出现大量极短的战斗失败

### ISSUE THREAD

**Issue by HansBug** [MaaAssistantArknights/MaaAssistantArknights#2104]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

睡前开了脚本挂肉鸽，选了刷投资模式（第一层结束后退出），后勤分队，煌开局，认知塑造已经全开。

醒来后发现大约前5-10把是正常的（能遇到商店，且甭管有没有投资都在完事后重开），而之后的就大多不正常，根据软件显示的日志信息来看，应该是出门第一把就战斗失败了，而且无一例外。这种情况大约持续了数小时，直到我起床看电脑。

我是是在想不出来第一层那几关用煌开局是咋做到能把把都寄的，而且这种情况据我观察只出现在长时间的挂机场合（普遍超过一小时）下，而且经过实测，整个过程大致为：
1. 开始若干把都正常
2. 然后开始无限出门就挂
3. 被我看见后重开脚本，又恢复了1的状态

大约就是这样的循环往复，有点怀疑是资源释放/状态转移存在问题 （具体我也不太懂，只是感觉这症状像资源泄露累积后造成的问题），因此求助~~~

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9694564/asst.zip)

注意看2022.10.3，0时至9时的部分。

### 截图

[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9694579/roguelike.zip)

为2022.10.3全部debug路径下的图，不知道是否有用。

### 还有别的吗？

软件版本：v4.6.0-alpha.8
模拟器：逍遥模拟器
操作系统：win10
配置：16core 64G，主显卡+NVIDIA Quadro P620

笔记本，7x24开启高性能模式，且关闭了休眠，只会熄屏。
但是因为开发工作需要，需要把一多半配置都用来开虚拟机，因此模拟器依然可能会卡。

**Comment by zzyyyl** [comment]
发一下 gui.log 看看？

**Comment by HansBug** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9695104/gui.log)

**Comment by zzyyyl** [comment]
我觉得纯粹是战斗逻辑比较拉的问题（

**Comment by zzyyyl** [comment]
你说是煌开局，a8 的时候煌是不是最后下的？
可以更新到 b2 试试

**Comment by HansBug** [comment]
> 我觉得纯粹是战斗逻辑比较拉的问题（

感觉不像，不然解释不了为什么一般脚本刚开动的时候运行得普遍都挺正常。



> 你说是煌开局，a8 的时候煌是不是最后下的？ 可以更新到 b2 试试

有这个情况，我见到过。尤其是误触尖刺宝箱/宝箱怪后，会直接被干穿且不会做任何补救措施（yysy我觉得你们可以检测一波）。
已经更新到beta2，已经在测试中。这个问题总是得连续运行个把小时后才会出现，预计晚上给你们反馈。

**Comment by zzyyyl** [comment]
> 你说是煌开局，a8 的时候煌是不是最后下的？ 可以更新到 b2 试试

煌的问题是 a8 的 bug，b2 已经修了。我觉得这个原因可能很大（？

> 我觉得纯粹是战斗逻辑比较拉的问题（

你看你 10-03 早上七点 的几局，虽说基本都寄了，但至少第 54 局是过了一关的（x

**Comment by HansBug** [comment]
贴一段刚刚半个小时前的（已经升级到b2）

```
10-03  13:14:54 正在连接模拟器……
10-03  13:14:55 正在运行中……
10-03  13:14:55 开始任务：Roguelike
10-03  13:14:58 已开始探索 1 次
10-03  13:16:00 关卡：普通作战
10-03  13:16:14 开始战斗：射手部队
10-03  13:17:55 战斗完成
10-03  13:18:43 关卡：普通作战
10-03  13:19:02 开始战斗：蓄水池
10-03  13:20:40 战斗完成
10-03  13:21:33 关卡：不期而遇
10-03  13:21:51 关卡：不期而遇
10-03  13:22:03 关卡：诡意行商
10-03  13:22:11 已投资 1 次
10-03  13:22:13 已投资 2 次
10-03  13:22:15 已投资 3 次
10-03  13:22:17 已投资 4 次
10-03  13:22:19 已投资 5 次
10-03  13:22:22 已投资 6 次
10-03  13:22:24 已投资 7 次
10-03  13:22:26 已投资 8 次
10-03  13:22:28 已投资 9 次
10-03  13:22:31 已投资 10 次
10-03  13:22:33 已投资 11 次
10-03  13:22:52 已放弃本次探索
10-03  13:23:05 已开始探索 2 次
10-03  13:24:13 关卡：普通作战
10-03  13:24:26 开始战斗：虫群横行
10-03  13:26:20 战斗完成
10-03  13:27:15 关卡：不期而遇
10-03  13:27:29 关卡：普通作战
10-03  13:27:42 开始战斗：蓄水池
10-03  13:29:32 战斗完成
10-03  13:30:27 关卡：不期而遇
10-03  13:30:47 关卡：诡意行商
10-03  13:30:55 已投资 12 次
10-03  13:30:57 已投资 13 次
10-03  13:30:59 已投资 14 次
10-03  13:31:38 已放弃本次探索
10-03  13:31:51 已开始探索 3 次
10-03  13:32:56 关卡：普通作战
10-03  13:33:09 开始战斗：共生
10-03  13:34:43 战斗完成
10-03  13:35:31 关卡：紧急作战
10-03  13:35:44 开始战斗：射手部队
10-03  13:37:26 战斗完成
10-03  13:37:57 关卡：不期而遇
10-03  13:38:10 关卡：普通作战
10-03  13:38:23 开始战斗：虫群横行
10-03  13:40:37 战斗完成
10-03  13:41:41 关卡：诡意行商
10-03  13:41:48 已投资 15 次
10-03  13:41:51 已投资 16 次
10-03  13:41:53 已投资 17 次
10-03  13:42:08 已放弃本次探索
10-03  13:42:17 已放弃本次探索
10-03  13:42:31 已开始探索 4 次
10-03  13:43:41 关卡：普通作战
10-03  13:43:56 开始战斗：共生
10-03  13:47:31 战斗失败
10-03  13:47:49 已开始探索 5 次
10-03  13:49:00 关卡：普通作战
10-03  13:49:15 开始战斗：共生
10-03  13:55:34 战斗失败
10-03  13:55:51 已开始探索 6 次
10-03  13:57:07 关卡：普通作战
10-03  13:57:22 开始战斗：虫群横行
10-03  13:59:32 正在停止……
10-03  13:59:32 已停止
10-03  13:59:32 任务出错：Roguelike
```

就像4、5这两次这样。

不过这个确实还不足以说明问题，过几个小时我弄一波更大的出来~~~

> 虽说基本都寄了，但至少第 54 局是过了一关的

我的想法是，第一层这种低难度关，你哪管选的是帕拉斯+最菜的战斗逻辑，偶尔半道挂掉不奇怪，但是这挂率显然高到不太正常；而且偏偏每次刚开始几把都正常，总是运行一阵后才这样，就更奇怪了。

算了，先等等看吧，我稍后可以提供更多的例子。

**Comment by HansBug** [comment]
新的例子来了，这次是b2版本的。这里我大概在中间离开了一小时左右，在20次的时候回来的（具体来说，解开电脑锁屏后看到的是第20次），于是又看见之前的一堆失败，以及当前的这把在用斑点堵门，梓兰调香师都下了，唯独迟迟不下煌，甚至还开了斑点的技能，结果就是全漏光 😢 

更奇怪的是，在这之后的第21、22次居然又好了。。。甚至一直运行到了第24次，其中每次都正常运打了商店。

如果是这么说的话，我怀疑可能是电脑/模拟器有比较奇怪的坑，而且和系统的休眠有一定关系，于是导致这期间对opencv或其他依赖系统资源的部分造成了影响。当然具体细节我说不上来，还得你们来排查了，有劳！

* debug截图：[roguelike_20221003_2.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9695942/roguelike_20221003_2.zip)
* GUI Log：[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9695959/gui.log)
* 系统Log：[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9695965/asst.zip)

**Comment by fearlessxjdx** [comment]
借楼问一下，程序员在测试的时候，是用的哪个干员开局的？我选相同干员，是不是成功率大一点？

**Comment by DavidWang19** [comment]
> 借楼问一下，程序员在测试的时候，是用的哪个干员开局的？我选相同干员，是不是成功率大一点？

测试的时候目标永远不会是打的远或者稳，所以你问这个没有意义（

**Comment by zzyyyl** [comment]
海沫（x

**Comment by pingplug** [comment]
我也发现了类似问题，电脑设置只会黑屏不会锁屏，也是黑屏后出现大量失败，应该是半年前傀影肉鸽就有这个问题。。。
但我发现，只要**将模拟器的窗口最小化**，就能解决这个问题。。。

系统：Windows 10 22H2
模拟器：蓝叠国际版
也就是bug只会在模拟器有窗口显示，且系统黑屏的情况下出现。。。
希望对debug有帮助 @zzyyyl  。。。
