### ISSUE TITLE
肉鸽模式关卡战斗流程优化

### ISSUE THREAD

**Issue by karma-sun** [MaaAssistantArknights/MaaAssistantArknights#2105]
### 说说你遇到的问题？

肉鸽模式现在的前几关战斗流程不是最优的，第一二层翻车的几率很大

### 有什么好的想法？

至少前几层的关卡可以加载json格式的作业配置

**Comment by zzyyyl** [comment]
说的简单，要不你来写.jpg

**Comment by zzyyyl** [comment]
目前战斗优化最多是改改 replace_home，招募优先级，藏品优先级之类，移植 copilot 肯定要等很久
用户那边可以自选分队，开局现在可（zhi）以（neng）设一个初始干员，自定义的程度还算比较大了（
