### ISSUE TITLE
蓝叠连接失败

### ISSUE THREAD

**Issue by helloworldqwer** [MaaAssistantArknights/MaaAssistantArknights#2106]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

请教一下按教程里，蓝叠hyper-v版本，在gui.json添加字段保存后，打开maa连接失败是什么原因？并且再次打开gui.jion，添加的字段被清除了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9695163/asst.log)

### 截图

![屏幕截图](https://user-images.githubusercontent.com/114902425/193515070-8b37e9d3-8ff5-4d9d-920d-2df497e86196.png)

**Comment by MistEO** [comment]
两种可能：
1. maa 没有关掉就修改 json 去了，需要关掉之后再改
2. 你的 json 格式不正确，无法解析，自动回滚成没修改之前格式正确的版本了
