### ISSUE TITLE
maa 肉鸽操作优化

### ISSUE THREAD

**Issue by WWPXX233** [MaaAssistantArknights/MaaAssistantArknights#2107]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

肉鸽关卡行动优化

### 日志文件

无需日志

### 截图

![Uploading Screenshot_2022.10.03_15.07.16.948.png…]()

### 还有别的吗？

上下路应该分别设置放置近战位干员

**Comment by wpx20021125wp** [comment]
![Screenshot_2022 10 03_15 07 16 948](https://user-images.githubusercontent.com/64907423/193519779-0c5ea5b0-ec6d-418a-abfa-000fdfb36a2a.png)
