### ISSUE TITLE
roguelike_recruit.json 权重选择

### ISSUE THREAD

**Issue by WWPXX233** [MaaAssistantArknights/MaaAssistantArknights#2111]
### 说说你遇到的问题？

```json
{
    "name": "海沫",
    "skill": 1,
    "recruit_priority": 950,
    "promote_priority": 550
},
{
    "name": "羽毛笔",
    "skill": 1,
    "recruit_priority": 940,
    "promote_priority": 550
},
{
    "name": "山",
    "skill": 2,
    "skill_usage": 2,
    "recruit_priority": 900,
    "promote_priority": 550
},
```

依旧选择山不选择羽毛笔

**Comment by zzyyyl** [comment]
你的山等级很高吧

**Comment by wpx20021125wp** [comment]
事实上除了海沫没有 羽毛笔是拉满的 山也是

**Comment by wpx20021125wp** [comment]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/64907423/193601204-1665cd15-a047-4cbe-bd24-c5344eb4eacf.png">

**Comment by zzyyyl** [comment]
你改完文件重启过 maa 么？
你用的什么版本？
你改的文件路径是什么？

**Comment by wpx20021125wp** [comment]
程序目录下的resource文件夹的roguelike_recruit.json我马上去运行一下稍等

**Comment by wpx20021125wp** [comment]
已经重启过了还是不行包括整个电脑重启

**Comment by wpx20021125wp** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9698340/asst.log)
22：27：33开始

**Comment by zzyyyl** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9698378/asst.log)

注意保护个人信息（

**Comment by wpx20021125wp** [comment]
滑倒了有反应好像但是没有点击上

**Comment by zzyyyl** [comment]
我看你提到的时间，根本没出现羽毛笔的信息（
是滑动次数太少了 ~~（你练的干员太多了~~

22：28附近的识别，最后一个干员是 `暴行`，你的羽毛笔应该在她后面（

**Comment by wpx20021125wp** [comment]
并不是他已经把羽毛笔扫描过去了而且我看到羽毛笔的图标有变化可能是模仿滑动正好点在羽毛笔身上了

**Comment by wpx20021125wp** [comment]
改了一下午的权重结果自己不能用给别人用可以 自闭ing

**Comment by zzyyyl** [comment]
日志中显示你的干员列表从左往右从上到下是
```
帕拉斯
赫拉格
耀骑士临光
银灰

斯卡蒂
煌
艾丽妮
棘刺

陈
山
百炼嘉维尔
史尔特尔

玛恩纳
铸铁
布洛卡
星极

幽灵鲨
阿米娅
拉普兰德
暴行
```
你看看有没有漏

**Comment by wpx20021125wp** [comment]
稍等一下我刷完这把剿灭qwq

**Comment by wpx20021125wp** [comment]
这几个全部都有
后面开始因陀罗 羽毛笔 芙兰卡 柏喙
我刚开始觉得可能是皮肤原因
但我换了还是不对劲

**Comment by zzyyyl** [comment]
@MistEO 是不是可以考虑增加一下划动次数？或者自定义一下？

**Comment by zzyyyl** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/edf3da646fae543efecb3e9608baf972e9489f99
暂时先放到 tasks.json 里，等下个版本的时候有需要可以自己改

**Comment by wpx20021125wp** [comment]
修改成"maxTimes": 5就可以了吧

**Comment by wpx20021125wp** [comment]
诶我想到个好办法 通过检测当前希望是否＞6来决定滑动的次数 这样既能保证都能搜到又可以通过少希望不滑动来节省时间

**Comment by wpx20021125wp** [comment]
中练度号13次，意外结束3次，到5层一次，四层5次
高练度号6次，意外结束0次，到5层三次，四层4次
基本上遇到溟痕乐园就得死 建议优化溟痕乐园战斗逻辑

**Comment by wpx20021125wp** [comment]
是啊要招募到羽毛笔 就是6希望多滑动0希望就不用滑动直接选就行

**Comment by wpx20021125wp** [comment]
主要是觉得如果最大扫描数提高了如果目标不是六星五星会降低效率

**Comment by MistEO** [comment]
fixed
