### ISSUE TITLE
公招遇到多个单四星tag选择问题。

### ISSUE THREAD

**Issue by rnzfgm** [MaaAssistantArknights/MaaAssistantArknights#2112]
### 说说你遇到的问题？

上次在看到maa自动公招的时候刷出来的tag包含：爆发，支援，特种。然后maa只选择了一个，我加速招募了被划掉了（悲），于是想到能不能让maa在遇到这种单词条的时候多个选择，这样划掉的时候就可以至少剩下一个，而且还是四星了。

### 有什么好的想法？

在未检测到五六星tag的情况下，单tag出四星的有：支援，爆发，特种，快速复活，削弱，位移。当检测到有这些tag存在不止一个时进行多选。

### 其他内容

无（可有可无的建议，但这几天被划了四个，呜呜呜。）

**Comment by ntgmc** [comment]
#92
