### ISSUE TITLE
MAA随机闪退/卡死

### ISSUE THREAD

**Issue by EXCADOGOD** [MaaAssistantArknights/MaaAssistantArknights#2120]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

MAA运行中闪退/卡住无法退出，模拟器正常

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9703104/asst.zip)

### 截图

![QQ截图20221004134619](https://user-images.githubusercontent.com/45102804/193743871-e1cfd5f5-1804-4e8b-96d0-8eb5cb1e4bc7.png)
![QQ截图20221004134626](https://user-images.githubusercontent.com/45102804/193743877-0345bb26-db72-45c6-a355-81b92868645f.png)

### 还有别的吗？

蓝叠5国际版 11800H 3080laptop 32g内存 WIN11系统

**Comment by zzyyyl** [comment]
看看有没有gui.err.log？

**Comment by EXCADOGOD** [comment]
> 看看有没有gui.err.log？

没有

**Comment by 134820134820** [comment]
我也存在这个问题，随机卡死，特别是当一个maa执行时打开第二maa，有一些手动的操作时

**Comment by 134820134820** [comment]
在打1-7时情况好像会更加频繁？（不知道是不是1-7时间长）

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
