### ISSUE TITLE
想创建作业，不知道如何获得地图坐标图片？

### ISSUE THREAD

**Issue by windde** [MaaAssistantArknights/MaaAssistantArknights#2121]
### 说说你遇到的问题？

想要创建作业，在填写干员位置时不知道地图坐标，看见提示为“填完关卡名后开一局，会在目录下 map 文件夹中生成地图坐标图片”，不知道在哪里填写关卡名，map中也找不到

**Comment by ABA2396** [comment]
https://map.ark-nights.com/
设置里的坐标改成MAA格式

**Comment by ABA2396** [comment]
写关卡名是指创建一个新的空作业，在作业的关卡名里写上对应的关卡
