### ISSUE TITLE
水月肉鸽偶尔会点进收藏品界面卡住

### ISSUE THREAD

**Issue by Yue-plus** [MaaAssistantArknights/MaaAssistantArknights#2123]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽偶尔会点进收藏品界面卡住

挂了一天半出现了两次这个情况

### 日志文件

选取了最近一个小时的日志（建议对日志文件进行自动分割，我这边挂一天半日志已经 113 多 MB 了 Orz

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9703507/asst.log)

### 截图

![QQ截图20221004145614](https://user-images.githubusercontent.com/33195150/193755083-3fef7180-aa7d-4639-85f6-70aefa6c2e1a.jpg)
![QQ截图20221004145631](https://user-images.githubusercontent.com/33195150/193755086-ea81e172-1fd7-41f5-9b38-74bb886fd3d2.jpg)

### 还有别的吗？

蓝叠模拟器

MAA - v4.6.0-bate.2

分辨率 1600*900

**Comment by MistEO** [comment]
debug/roguelike/ 里的图片也打包传下看看

**Comment by Yue-plus** [comment]
> debug/roguelike/ 里的图片也打包传下看看
[roguelike_2.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9703924/roguelike_2.zip)
