### ISSUE TITLE
傀影肉鸽先遣小队识别失败导致卡住退出

### ISSUE THREAD

**Issue by 134820134820** [MaaAssistantArknights/MaaAssistantArknights#2127]
有好几次出现这个问题，在不期而遇中遇见事件先遣小队（可进阶一名五星以下干员）时，出现因为没有可以进阶对象而在确定放弃招募后卡在确认界面，过一分钟后退出重开的问题
![屏幕截图 2022-10-04 174335](https://user-images.githubusercontent.com/79043872/193799900-014de1b6-ca73-4d48-8ec5-5c4ad5b5f6a3.png)

**Comment by MistEO** [comment]
提下“问题反馈”，然后发下日志吧（而不是“其他问题”）
