### ISSUE TITLE
MAA中使用备选关卡，却仍然会按照原来的选项执行

### ISSUE THREAD

**Issue by 134820134820** [MaaAssistantArknights/MaaAssistantArknights#2128]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在MAA中选择剩余理智：1-7后，打开界面设置中的使用备选关卡选项，然后设置新的需要打的关卡，但maa仍会在打完关卡选择后去打1-7，其它也是一样，备选没用，只会按剩余理智的选项执行。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9705267/asst.log)

### 截图

![屏幕截图 2022-10-04 185102](https://user-images.githubusercontent.com/79043872/193802205-46d829ac-e49c-42b5-9839-b679d39fccfa.png)

**Comment by MistEO** [comment]
这块逻辑挺乱的，以后可能会想着整整

现在的设计确实如楼上所说，备选是在主关卡今日没开放的时候，才会去打

**Comment by 134820134820** [comment]
原来如此。。。那是否可以先将这块改为勾选备选后下边多显示备选选项的框，而不是把原先剩余理智的框覆盖掉，而仍有作用

**Comment by zzyyyl** [comment]
可以用滚轮...
