### ISSUE TITLE
没有部署位置时会一直选中待部署的干员维持慢速度

### ISSUE THREAD

**Issue by SwissRollC** [MaaAssistantArknights/MaaAssistantArknights#2129]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽，4高台位置，5高台干员，一直处于选中干员，慢速播放。
因一直在挂肉鸽文件过大无法上传，截图了关卡开始和完成的时间，日志文件截取的是从上层存钱到完成关卡完成后招募干员。

### 日志文件

[Uploading log.txt…]()

### 截图

这是实战过程中的截图
![QQ截图20221004183509](https://user-images.githubusercontent.com/114994436/193800350-3306ff17-c660-432f-a78f-1b6463e9b459.png)

这是关卡开始和完成时间
![QQ截图20221004185349](https://user-images.githubusercontent.com/114994436/193802146-6d9e9836-5b95-4ce7-a5d2-7698c8f5679a.png)

**Comment by SwissRollC** [comment]
发现后一直在点地板维持二倍速，直到关卡结束

**Comment by SwissRollC** [comment]
[log.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9705326/log.txt)

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/193863649-bfd1e957-0078-4cc3-a918-8a8249cef8bb.png)
![image](https://user-images.githubusercontent.com/38283893/193863674-1e2d7416-dab5-4779-8b9e-0699e0b485f7.png)
成功重现

**Comment by MistEO** [comment]
fixed
