### ISSUE TITLE
肉鸽 关卡：感化 输出不够被囚徒卡死

### ISSUE THREAD

**Issue by dichigo** [MaaAssistantArknights/MaaAssistantArknights#213]
![image](https://user-images.githubusercontent.com/98818071/153394083-c5254159-dc44-43e0-88bc-20398ac618cd.png)
应该无需log吧（我也想看看他能打到什么时候

**Comment by MistEO** [comment]
之前平民那个图，地面可以放高台干员的，有个群友的芙蓉阻挡了一个小兵，卡了三个小时哈哈哈哈哈哈
