### ISSUE TITLE
肉鸽干员招募，不要忽略免费的高星临时招募干员

### ISSUE THREAD

**Issue by MisterCoBen** [MaaAssistantArknights/MaaAssistantArknights#2130]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在肉鸽招募券招募干员的过程中，会自动忽略免费的高星级随机赠送干员，反而选择免费的预备干员

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9706148/asst.log)
发生于文件最后一次肉鸽中

**Comment by MisterCoBen** [comment]
此问题应该发生于希望值不足时，比如0，或1 希望

**Comment by MistEO** [comment]
duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1951

**Comment by WWPXX233** [comment]
目前白给的六星以及五星好用的会拿
