### ISSUE TITLE
水月肉鸽自动战斗干员摆放问题

### ISSUE THREAD

**Issue by MisterCoBen** [MaaAssistantArknights/MaaAssistantArknights#2131]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在第五层发生的第一次肉鸽战斗"蔓延"中，阿米娅的摆放出现了多次失败的情况，怀疑是地块识别错误的原因，也有可能是战斗逻辑本身出错，理由是所有干员都被摆放于地图最上侧，并不能很好地阻挡所有敌人

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9706307/asst.log)
问题发生于最后一次战斗

**Comment by MistEO** [comment]
下次再遇到的话来张图看看咋摆的

**Comment by ABA2396** [comment]
这个问题是不是已经修了，和主线关卡重名那个

**Comment by MistEO** [comment]
修过了
