### ISSUE TITLE
Rogue中对于自选开局干员提高优先级

### ISSUE THREAD

**Issue by NonXZhu** [MaaAssistantArknights/MaaAssistantArknights#2132]
### 说说你遇到的问题？

举例来说如果自选**百炼嘉维尔**或者**泥岩**开局，过程中如果拿到一些低费的干员，比如斑点，很多时候会优先下斑点，然后接着布置各种高台，导致失去了自选干员在前期的强势。

### 有什么好的想法？

至少对于前几层提高自选干员的优先级，敌方没到蓝门前都可以等一等费用，达不到要求的话再下其他单位处理。

**Comment by MistEO** [comment]
cc @DavidWang19
