### ISSUE TITLE
日服材料识别失败

### ISSUE THREAD

**Issue by salenth** [MaaAssistantArknights/MaaAssistantArknights#2133]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

版本号为4.6贝塔2，客户端为日服，使用功能为清体力，使用的模拟器为蓝叠N5
如题，日服关卡完成后材料识别失败（但是信用商店自动购物却是正常的……）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9707211/asst.log)
logs记录时间在下午8~9点之间

### 截图

![image](https://user-images.githubusercontent.com/114795190/193830908-f885ce00-4be3-4a68-aa59-648cfb1ed6d0.png)

**Comment by MistEO** [comment]
日服没支持掉落识别，参考 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1733
