### ISSUE TITLE
蓝叠模拟器和明日方舟客户端可以被启动但脚本不工作。

### ISSUE THREAD

**Issue by Avon499** [MaaAssistantArknights/MaaAssistantArknights#2134]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

MAA可以启动蓝叠模拟器和明日方舟，但会停在唤醒界面。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9707729/asst.log)

### 截图

[MAA错误.docx](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9707863/MAA.docx)

### 还有别的吗？

![image](https://user-images.githubusercontent.com/115003823/193846636-ae18d599-f1c4-4038-8044-561d90fbcad6.png)

**Comment by MistEO** [comment]
日志中报错

```log
[2022-10-04 12:37:22.410][INF][Px3394][Tx23ac] Call ` C:\Program Files\BlueStacks_nxt\HD-Adb.exe connect 127.0.0.1:5555 ` ret 1 , cost 23265 ms , stdout size: 222 , socket size: 0
[2022-10-04 12:37:22.410][TRC][Px3394][Tx23ac] output:
error: Invalid argument: cannot open transport registration socketpair

* daemon not running. starting it now on port 5037 *

could not read ok from ADB Server

* failed to start daemon *

error: cannot connect to daemon
```

我也是第一次见到这个错误，查了下似乎是防火墙问题，可以试试看

https://blog.csdn.net/baidu_41327283/article/details/84927554
https://www.cnblogs.com/dreamyu/p/8032588.html

**Comment by Avon499** [comment]
解决了，就是防火墙的问题，把占用adb的端口杀掉，把防火墙关掉再启动MAA就可以了。
