### ISSUE TITLE
水月肉鸽在第3+次探索后模拟器出现卡顿，Maa出现密集报错

### ISSUE THREAD

**Issue by ANDYWANGTIANTIAN** [MaaAssistantArknights/MaaAssistantArknights#2135]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

maa的肉鸽设置如图：
![image](https://user-images.githubusercontent.com/53755609/193848560-ae681f87-5be7-4fea-991f-89cc4b6daddf.png)
我使用的是雷电模拟器9.0.24版本，在按上图设置并开启自动刷肉鸽之后，在第2或第3次探索开始后，就会出现大量的报错，模拟器内画面会出现掉帧(掉到大约10几帧)，此后自动肉鸽就不可用了，只能点击停止后出现点击“link start”按钮开始刷肉鸽。此bug每次运行都会出现。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9707948/asst.log)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9707956/gui.log)

### 截图

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9707961/debug.zip)

**Comment by fearlessxjdx** [comment]
建议用蓝叠，我刷了二十多把了，都没出错
