### ISSUE TITLE
银灰+精0子+工具人 没有被识别为当前最优解

### ISSUE THREAD

**Issue by fearlessxjdx** [MaaAssistantArknights/MaaAssistantArknights#2136]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

版本是 `v4.6.0-beta.2`

选了3个30%，而没有选106%的”银灰+精0子+工具人“组合。

类似的还有，办公室45%的地灵也没有被认为是当前最优解，而是选了40%的伊桑

### 日志文件

100%复现

**Comment by MistEO** [comment]
心情消耗 + 2 的 debuff 太严重了，故意调低的。另外请带上日志

**Comment by fearlessxjdx** [comment]
> 心情消耗 + 2 的 debuff 太严重了，故意调低的。另外请带上日志

100%复现也需要吗？

**Comment by fearlessxjdx** [comment]
@MistEO 那我通过备选干员来吧，”银灰+精0子+工具人“组合备选干员行得通吗？

**Comment by fearlessxjdx** [comment]
@MistEO 好吧，稍等一下，这工具我还不熟悉

**Comment by zzyyyl** [comment]
`asst.log`，plz

**Comment by fearlessxjdx** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9708812/asst.log)

这次是这样的，第二个贸易站，本来首选应该是孑0组合，但选了 3 个 30%。最后一个交易站选了孑0组合，但最后一个干员选错了，应该选 30% 才是最优
