### ISSUE TITLE
为什么帕拉斯的权重这么高

### ISSUE THREAD

**Issue by sheepzhan** [MaaAssistantArknights/MaaAssistantArknights#2137]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我有点不明白为什么帕拉斯的权重比百嘉还要高。这次肉鸽里牛牛的抓位也不高啊

### 日志文件

帕拉斯的权重是900，百嘉的权重才800

**Comment by MistEO** [comment]
请看软件图标（

**Comment by zzyyyl** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/242da9ba7717e1ca9178ae6c9427f7c4e07871d2 fixed
