### ISSUE TITLE
基建排班配置中建议添加”排除干员“参数

### ISSUE THREAD

**Issue by fearlessxjdx** [MaaAssistantArknights/MaaAssistantArknights#2138]
### 说说你遇到的问题？

有些干员不想让他休息或者工作。

例如 `芳汀` 的心情工具人。。。

再比如一些专精效率高的干员，不希望他们去工作

**Comment by zzyyyl** [comment]
建议自定义基建

**Comment by fearlessxjdx** [comment]
> 建议自定义基建

@zzyyyl 自定义排班？我试过了，里面并没有”排除“参数，自动会把心情低的放入宿舍。

**Comment by zzyyyl** [comment]
你把宿舍排满就完事了，别用 autofill

**Comment by fearlessxjdx** [comment]
> 你把宿舍排满就完事了，别用 autofill

嗯，这我明白，但前面用了 autofill 后，无法确定哪些人需要休息，除非前面也全都不用 autofill 。。。

**Comment by zzyyyl** [comment]
那就都别用 autofill

**Comment by fearlessxjdx** [comment]
> 那就都别用 autofill

我本来就只是建议，并不是 bug 相关。能用排除的话，autofill 不就用起来更方便了嘛

**Comment by zzyyyl** [comment]
那你应该打 `enhancement`

**Comment by fearlessxjdx** [comment]
> 那你应该打 `enhancement`

抱歉，系统打上的，我没注意到。

**Comment by fearlessxjdx** [comment]
@zzyyyl 问一下，相关逻辑在哪个文件附近？我尝试自己改改看

**Comment by zzyyyl** [comment]
@MistEO

**Comment by MistEO** [comment]
duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1683

**Comment by fearlessxjdx** [comment]
@MistEO 请问相关代码逻辑在哪个文件中？想自己试试，但是太菜了没找到。
