### ISSUE TITLE
期待添加红松组等联动体系

### ISSUE THREAD

**Issue by MiSheep** [MaaAssistantArknights/MaaAssistantArknights#2139]

**Comment by zzyyyl** [comment]
建议自定义基建

**Comment by 545426** [comment]
直接来图说明班次和每班的排版，我给你单独写个自定义基建.json算了（闲着也是闲着

**Comment by MistEO** [comment]
可能短期内不会做自动联动了，需要的话使用自定义基建吧。可以参考 https://www.bilibili.com/video/BV1De411L7C9/
