### ISSUE TITLE
不关闭MAA二次启动模拟器异常

### ISSUE THREAD

**Issue by Black1312** [MaaAssistantArknights/MaaAssistantArknights#2140]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

首次使用后关闭模拟器不关MAA，第二次使用时直接点击MAA的开始，无法正常启动模拟器。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9709134/asst.zip)

### 截图

![ARNN7EOMB~%Z9)8FNK5_(0L](https://user-images.githubusercontent.com/64343218/193882035-a305db55-e053-4fab-aa3e-d60efe7f9f58.png)

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/193883489-acbec242-64f2-4870-920b-007d0bd53f28.png)

这个勾上就好了

**Comment by MistEO** [comment]
等一小会，要重试 20 次才会去启动的（这个功能主要是给定时任务用的

**Comment by zzyyyl** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1277
