### ISSUE TITLE
配置文件gui.json按天再备份一两次

### ISSUE THREAD

**Issue by moomiji** [MaaAssistantArknights/MaaAssistantArknights#2145]
### 说说你遇到的问题？

在极端条件（蓝屏）下，配置还是会丢失。
看了下代码，按理启动时读取gui.json发生错误后会再读取gui.json.bak，但不知道为啥又没读取成功。

### 有什么好的想法？

按 **天** 再多备份一两次，并且只在软件 **正常启动时** 对`gui.json.bak`进行备份。

启动后备份过程如下：
第零步（新增）：gui.json.bak1 ---> gui.json.bak2 前天的备份（防止24点前出问题，24点后启动bak1被覆盖）
第一步（新增）：gui.json.bak ---> gui.json.bak1 昨天的备份
第二步（现有）：gui.json　　 ---> gui.json.bak 今天的不断备份

同天的备份只**保留第一份，即同天只在第一次启动时备份**（根据bak1的创建日期 / 文件名加上日期但不一定每天启动）
防止没发现配置丢失多次启动bak1被覆盖，跨天后bak2又被覆盖。

这样发现问题后可以手动 ~~/自动~~ 恢复配置bak1，再不济恢复bak2。

### 其他内容

上次相关commit：https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/57173d02b1fd28cc65fb870cc2978358ceb12635

**Comment by MistEO** [comment]
感觉概率太低了，挺没必要的（

**Comment by moomiji** [comment]
> 感觉概率太低了，挺没必要的（

win正常的话概率是挺低的，经常蓝屏就不一定了（

如果不用软件自动恢复前两天配置而是自己意识到后手动覆盖一下的话，也就加两次条件检测后的copy操作，不用改太多。

要不是这段时间配置经常更新，手动备份一下就行。

不需要的话issue可以直接关
