### ISSUE TITLE
水月肉鸽无法正常进入,  点进主界面后自动选择退出, 无限循环

### ISSUE THREAD

**Issue by HSunSK** [MaaAssistantArknights/MaaAssistantArknights#2148]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽无法正常进入,  点进主界面后自动选择退出, 无限循环

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9711391/asst.log)

**Comment by haohanyuzmx** [comment]
我也一样.jpg

**Comment by cybearfish** [comment]
可以看一下以前的issue，问题解决了回来说一声
（话说这个“彩蛋”什么时候转正或者给个引导啊，这个问题都问了几遍了）

**Comment by UVJkiNTQ** [comment]
水月肉鸽请下载测试版。
你看下标准版的发布日期就知道怎么回事了，当时肉鸽都没开。

**Comment by HSunSK** [comment]
> 水月肉鸽请下载测试版。 你看下标准版的发布日期就知道怎么回事了，当时肉鸽都没开。

原来是这样，领教了

**Comment by MistEO** [comment]
请看置顶

另外这不是“彩蛋”，新模式刚出，不想跳 yj 脸，藏一下，而且藏的也并不深（
