### ISSUE TITLE
自定义基建的period参数工作不正常

### ISSUE THREAD

**Issue by MigdalBavel** [MaaAssistantArknights/MaaAssistantArknights#2153]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我希望在10点定时运行执行“B+Y”组的换班，而我设定的period是这样：
![A](https://user-images.githubusercontent.com/105539375/193965481-4048784c-2a12-45e0-ab4d-5ab8d7d38d24.png)
![B](https://user-images.githubusercontent.com/105539375/193965491-269e81ae-9ed4-4fd0-b0d3-5489a70836bd.png)

发生的情况是这样：
我睡前为了保险还特意先手动切到“B+Y”才去睡觉。在待机过程中，maa倒是正常自动切换到了“A+B”，虽然具体时间点不清楚。
但问题就在于到了9:59的时候，却并没有按预期切到马上需要换的“B+Y”，然后在10:00依然进行的“A+B”的换班。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9712064/asst.log)

### 还有别的吗？

4.6.0 beta2

**Comment by MigdalBavel** [comment]
我在13点观察还是一样的情况，没有自动切换到我period设置12:59 - 15:58的“A+Y”组。
现在period情况就是经常不工作，但是偶尔它又会生效反而造成问题。比如上面讲的我睡前切到“B+Y”希望10点能自动换“B+Y”的班，但是中途属于“A+B”的时间段某刻给我自动切到“A+B”了，但是真正到了“B+Y”的时间段又没有及时切到“B+Y”。

**Comment by kasora** [comment]
日志里有一个自动增加分组的log，大概定位到了这里

**Comment by MistEO** [comment]
看看有没有个 gui.log 文件，也发下看看

**Comment by kasora** [comment]
`
10-06  02:12:10 开始任务：Infrast
10-06  02:12:22 当前设施：Dorm 0
10-06  02:12:32 巫恋, 菲亚梅塔
10-06  02:13:08 干员冲突
10-06  02:13:22 当前设施：Mfg 0
10-06  02:13:44 红云, 稀音, 帕拉斯
10-06  02:14:34 当前设施：Mfg 1
10-06  02:14:40 食铁兽, 断罪者, 槐琥
10-06  02:14:53 当前设施：Mfg 2
10-06  02:15:00 清流, 温蒂, 森蚺
10-06  02:15:29 当前设施：Mfg 3
10-06  02:15:36 砾, 至简, 迷迭香
10-06  02:15:58 当前设施：Trade 0
10-06  02:16:10 巫恋, 龙舌兰, 柏喙
10-06  02:16:48 当前设施：Trade 1
10-06  02:16:55 但书, 空弦, 黑键
10-06  02:17:26 当前设施：Control 0
10-06  02:17:36 阿米娅, 凯尔希, 琴柳, 令, 夕
10-06  02:18:06 当前设施：Power 0
10-06  02:18:13 承曦格雷伊
10-06  02:18:26 当前设施：Power 1
10-06  02:18:30 澄闪
10-06  02:18:39 干员冲突
10-06  02:18:46 当前设施：Power 2
10-06  02:18:50 炎狱炎熔
10-06  02:19:07 当前设施：Reception 0
10-06  02:20:12 当前设施：Office 0
10-06  02:20:17 絮雨
10-06  02:20:33 当前设施：Dorm 0
10-06  02:20:39 爱丽丝, 车尔尼
10-06  02:21:36 当前设施：Dorm 1
10-06  02:21:52 当前设施：Dorm 2
10-06  02:22:03 干员冲突
10-06  02:22:09 当前设施：Dorm 3
10-06  02:22:28 自动保存为下个计划
10-06  02:22:28 A+Y 组


10-06  09:00:57 开始任务：Infrast
10-06  09:01:15 当前设施：Dorm 0
10-06  09:01:25 龙舌兰, 菲亚梅塔
10-06  09:04:26 干员冲突
10-06  09:04:42 当前设施：Mfg 0
10-06  09:05:03 红云, 稀音, 帕拉斯
10-06  09:05:49 当前设施：Mfg 1
10-06  09:05:56 远牙, 野鬃, 灰毫
10-06  09:06:09 当前设施：Mfg 2
10-06  09:06:16 清流, 温蒂, 森蚺
10-06  09:06:45 当前设施：Mfg 3
10-06  09:06:51 水月, 海沫, 多萝西
10-06  09:07:41 当前设施：Trade 0
10-06  09:07:53 巫恋, 龙舌兰, 柏喙
10-06  09:08:31 当前设施：Trade 1
10-06  09:08:37 孑, 银灰, 但书
10-06  09:09:18 当前设施：Control 0
10-06  09:09:27 诗怀雅, 凯尔希, 灵知, 焰尾, 老鲤
10-06  09:09:48 当前设施：Power 0
10-06  09:09:55 承曦格雷伊
10-06  09:10:12 当前设施：Power 1
10-06  09:10:16 雷蛇
10-06  09:10:30 当前设施：Power 2
10-06  09:10:34 炎狱炎熔
10-06  09:10:55 当前设施：Reception 0
10-06  09:12:02 当前设施：Office 0
10-06  09:12:08 艾雅法拉
10-06  09:12:23 当前设施：Dorm 0
10-06  09:12:30 爱丽丝, 车尔尼
10-06  09:13:27 当前设施：Dorm 1
10-06  09:13:42 当前设施：Dorm 2
10-06  09:13:58 当前设施：Dorm 3
10-06  09:14:18 自动保存为下个计划
10-06  09:14:18 B+Y 组
10-06  09:14:18 次高效替补 2 班
下次换班请在约4小时后进行
10-06  09:14:18 完成任务：Infrast



10-06  13:01:05 开始任务：Infrast
10-06  13:01:26 当前设施：Mfg 0
10-06  13:01:47 远牙, 野鬃, 灰毫
10-06  13:02:01 干员冲突
10-06  13:02:03 当前设施：Mfg 1
10-06  13:02:09 食铁兽, 断罪者, 槐琥
10-06  13:02:23 当前设施：Mfg 2
10-06  13:02:29 水月, 海沫, 多萝西
10-06  13:03:07 干员冲突
10-06  13:03:09 当前设施：Mfg 3
10-06  13:03:16 砾, 至简, 迷迭香
10-06  13:03:40 当前设施：Trade 0
10-06  13:03:53 巫恋, 龙舌兰, 卡夫卡
10-06  13:04:30 当前设施：Trade 1
10-06  13:04:37 但书, 空弦, 黑键
10-06  13:05:11 当前设施：Control 0
10-06  13:05:21 阿米娅, 焰尾, 琴柳, 令, 老鲤
10-06  13:05:50 当前设施：Power 0
10-06  13:05:56 正义骑士号
10-06  13:06:14 当前设施：Power 1
10-06  13:06:18 澄闪
10-06  13:06:32 当前设施：Power 2
10-06  13:06:36 雷蛇
10-06  13:06:54 当前设施：Reception 0
10-06  13:07:58 当前设施：Office 0
10-06  13:08:04 絮雨
10-06  13:08:19 当前设施：Dorm 0
10-06  13:08:29 爱丽丝, 车尔尼
10-06  13:08:52 当前设施：Dorm 1
10-06  13:09:08 当前设施：Dorm 2
10-06  13:09:23 当前设施：Dorm 3
10-06  13:09:40 自动保存为下个计划
10-06  13:09:40 A+B 组
10-06  13:09:40 最高效率长班
下次换班请在约16小时后进行
10-06  13:09:40 完成任务：Infrast
`

**Comment by kasora** [comment]
gui.log

https://gist.github.com/kasora/a1f847ed002e17cee9fe97ea2149694a


配置文件

https://gist.github.com/kasora/7bc603afbfdc45bece8e294d3ec88ff6

**Comment by MigdalBavel** [comment]
[gui.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9738726/gui.bak.log)

**Comment by MistEO** [comment]
你俩似乎不是同一个问题

@kasora 我没看到你的日志，暂时不太确定，不过从 gui 的日志和 json 文件来看，你没有定义 period 呀？现在的功能就是没有 period 的时候，当前仅当每次执行完基建，就会自动往后跳一个，有任一 period 就不跳了；清理智应该也不会跳的

**Comment by kasora** [comment]
是定义在这个位置吧。我用这个 https://yituliu.site/riicCal/ 生成了一下然后贴进来的。
https://gist.github.com/kasora/7bc603afbfdc45bece8e294d3ec88ff6#file-config-json-L15

**Comment by MistEO** [comment]
> 是定义在这个位置吧。我用这个 https://yituliu.site/riicCal/ 生成了一下然后贴进来的。 https://gist.github.com/kasora/7bc603afbfdc45bece8e294d3ec88ff6#file-config-json-L15

不太对，你的 json 和 gui.log 对不上，确定是同一个么。我试了下你的 json，起码 period 是能正常解析的（能不能正常按时间切换还不知道，最起码能显示出来），但从你的日志看解析都没能解析到。或者说你用的哪个版本？

![image](https://user-images.githubusercontent.com/18511905/194698513-7242cf5c-bfdb-49ae-b675-7eebeb89ef6d.png)

**Comment by kasora** [comment]
哦哦，不好意思配置发错了，之前为了临时解决问题就copy了一组让他能适配自动+1。
之前应该是v4.6.0-beta.2，我更新到最新版试试。非常感谢。
