### ISSUE TITLE
4点结束肉鸽 不会继续打

### ISSUE THREAD

**Issue by xileii** [MaaAssistantArknights/MaaAssistantArknights#2154]
### 说说你遇到的问题？

不是说支持4点更新能继续肉鸽吗 为什么还是结束了不继续刷了

**Comment by cybearfish** [comment]
我是可以4点继续打的
首先检查更新（虽然看楼主说的应该是最新的）
可能是网络/模拟器（卡死）/电脑（待机停止）问题

**Comment by MistEO** [comment]
是 bug，提下“问题反馈”带下日志和截图吧
