### ISSUE TITLE
自定义基建无人机加速字段问题

### ISSUE THREAD

**Issue by zpw476898033** [MaaAssistantArknights/MaaAssistantArknights#2155]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

自定义基建无人机加速设定了如下，但还是会默认加速第一个房间。
代码中设置的index:4好像并没有生效。
`"drones":{
				"enable":true,
				"index":"4",
				"room":"manufacture",
				"order":"pre"
			}`

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9712895/asst.log)

**Comment by MistEO** [comment]
这个 index 字段需要是 int，一图流导出错了。我们和他们的后端大佬联系了，等他们改（甩锅
