### ISSUE TITLE
会客室在送掉线索之前，需要增加一步挂满线索的过程

### ISSUE THREAD

**Issue by Roseleaves** [MaaAssistantArknights/MaaAssistantArknights#2157]
### 说说你遇到的问题？

![image](https://user-images.githubusercontent.com/77195551/193999772-d2d18788-fecf-4922-93ca-1a7d42eab6bb.png)
如图所示的线索1和线索7原来各有1份但没挂上。接收线索的时候自有库是满的于是送掉一些线索，结果把线索1和线索7的最后1份给送掉了。

**Comment by DreAmVirGo** [comment]
同样的问题，把我最后一张2送出去了。如需logs可以问我要（）
