### ISSUE TITLE
傀影肉鸽地面部署高台医疗导致卡关

### ISSUE THREAD

**Issue by BAnSHao1** [MaaAssistantArknights/MaaAssistantArknights#2158]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

刚开始用这个，不知道这种情况是可以避免的吗还是啥，就傀影肉鸽有地面部署高台位的关卡，然后医疗干员默认放在大部分干员的前面，导致在没有远程干员的情况下，出现小怪被医疗卡在输出范围之外导致卡关的情况，比如像下图那样（不知道能不能看的到图，时间也忘记看了）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9714016/asst.log)

### 截图

![BUG001](https://user-images.githubusercontent.com/115068236/194009141-edac9bc8-0e26-4fd7-8d78-68dc1c46af2d.png)

**Comment by zzyyyl** [comment]
你卡多久了？
卡太久（好像是五分钟）会自动撤的

**Comment by BAnSHao1** [comment]
> 你卡多久了？ 卡太久（好像是五分钟）会自动撤的

噢噢原来如此，可能是运气好，卡住没一会就被我看到了，谢谢！
