### ISSUE TITLE
建议增加一个无条件填满宿舍功能

### ISSUE THREAD

**Issue by youdianfengbao** [MaaAssistantArknights/MaaAssistantArknights#2160]
### 说说你遇到的问题？

迷迭香黑键基建技能需要宿舍满员才能达到最大值。
在自定义基建中设置宿舍autofill，并且勾选自动宿舍空余位置蹭信赖。因为未满信赖的只有极少干员了，遇到计划换班人数较少时会出现宿舍不满员就直接结束的情况。（如图，最后一个宿舍缺一人，就已经结束基建项目了）
![Snipaste_2022-10-05_16-37-02](https://user-images.githubusercontent.com/52135976/194019198-d2cc24f8-75f8-4edd-818c-cc6b46b2be4c.jpg)
![Snipaste_2022-10-05_16-44-23](https://user-images.githubusercontent.com/52135976/194019367-7031b664-eafb-4b62-ab52-01bdfd34f52e.jpg)

### 有什么好的想法？

增加一个用未进驻任意干员将宿舍补满的功能。

**Comment by ShudaoWei** [comment]
一样的情况，已经尝试过修改入住心情阈值，无论是否设置为100，或者0，或者30，或者99，MAA都不会选择未进驻的任意干员填充宿舍。尤其和https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2362#issuecomment-1284748420 这处问题结合，会导致如果该宿舍有已进驻蹭信赖干员，MAA在引用问题的引导下认定无干员可放，会直接轮空这个宿舍，并且停止接下来的宿舍填充，导致不仅没有放满干员，甚至本来能填充的信赖未满干员也没能入住，基建功能运行就已经结束了。

**Comment by MistEO** [comment]
试试测试版，现在就是无条件塞满的
