### ISSUE TITLE
水月肉鸽招募后卡在骰子界面

### ISSUE THREAD

**Issue by yc080713** [MaaAssistantArknights/MaaAssistantArknights#2164]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

群中看到的
10.05晚上18点这30分左右卡住
没有卡住界面截图，描述界面为“就是转楼层低灯火扔骰子  显示山神经退行”

### 日志文件

[asst.log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9716038/asst.log.zip)

### 还有别的吗？

蓝叠32位安卓10，4.6.0
BETA3

**Comment by MistEO** [comment]
截图在 debug/roguelike/ 文件夹里有，发下康康

**Comment by yc080713** [comment]
![Uploading -405d4cf99df6afba.png…]()

**Comment by yc080713** [comment]
![Uploading -405d4cf99df6afba.png…]()

**Comment by yc080713** [comment]
![-405d4cf99df6afba](https://user-images.githubusercontent.com/92996760/194075983-939fd8f8-c318-46ba-bc3b-2e36e968b58a.png)

**Comment by yc080713** [comment]
“找到个相似的”
“就是这个界面显示山神经失调卡住”
“害是神经退行”
![-6d9ba2bc6507dea3](https://user-images.githubusercontent.com/92996760/194077457-0eae9a7c-5818-418f-aff7-b7037263d5e1.jpg)
我还没玩过水月肉鸽，不确定这里对问题有什么帮助

**Comment by genskyff** [comment]
我也遇到了这个问题，也是在这个投骰子界面，就卡住了，需要手动点一下才能继续进行
![2022-10-05_18-57-50 629_raw](https://user-images.githubusercontent.com/43875771/194090255-1aec594a-6f82-4b44-bfa2-d14bcb77668e.png)
