### ISSUE TITLE
一图流自定义基建json导入，无人机使用错误

### ISSUE THREAD

**Issue by DreAmVirGo** [MaaAssistantArknights/MaaAssistantArknights#2165]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在已经确定1-2是赤金，3-4是经验的情况下无人机加速了制造站1号的赤金。刚进基建就加速了。

### 日志文件

第一次在八点多，第二次在21:00:40前一点。（九点的消耗了14个无人机加工了一个赤金，八点多消耗了180+无人机加工了9个赤金）
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9716125/asst.log)
一图流json无法上传，id为1664944390968037

### 截图

![~82PQEAR $}1WM(`})XB~E7](https://user-images.githubusercontent.com/28724211/194075596-c78696a3-9729-4470-ab7a-53c22612edb7.png)![LG2UN}HGJO$T`Y4~%5M9{29](https://user-images.githubusercontent.com/28724211/194075527-84a645fe-52d2-4f0e-a491-89c9836057f8.png)
![73{Z06NX_BJP4L%68T8C693](https://user-images.githubusercontent.com/28724211/194075553-3ae87b8f-5bb3-4668-9183-f1db1f4f08f2.png)
![~82PQEAR $}1WM(`})XB~E7](https://user-images.githubusercontent.com/28724211/194075596-c78696a3-9729-4470-ab7a-53c22612edb7.png)

**Comment by MistEO** [comment]
一图流导出错了，跟他们后端大佬联系了，等他们改（甩锅.jpg

**Comment by MistEO** [comment]
duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2155

**Comment by DreAmVirGo** [comment]
> 一图流导出错了，我和他们后端大佬联系了，等他们改（甩锅.jpg

okay, 如果现在想修正的话，json那边要怎么改设置？把“index”换成“int”就好了嘛

**Comment by MistEO** [comment]
> > 一图流导出错了，我和他们后端大佬联系了，等他们改（甩锅.jpg
> 
> okay, 如果现在想修正的话，json那边要怎么改设置？把“index”换成“int”就好了嘛

把 `"index": "3"` 改成 `"index": 3`

**Comment by DreAmVirGo** [comment]
> > > 一图流导出错了，我和他们后端大佬联系了，等他们改（甩锅.jpg
> > 
> > 
> > okay, 如果现在想修正的话，json那边要怎么改设置？把“index”换成“int”就好了嘛
> 
> 把 `"index": "3"` 改成 `"index": 3`

谢谢，那我这边先close了
