### ISSUE TITLE
仓库识别错误

### ISSUE THREAD

**Issue by DreAmVirGo** [MaaAssistantArknights/MaaAssistantArknights#2166]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

仓库识别beta出现错误，只能识别仓库内一页的内容。

### 日志文件

[depot.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9716185/depot.zip)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9716186/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/28724211/194077968-76490b10-d8cd-4166-aaa7-3f51da40b2db.png)

**Comment by MistEO** [comment]
更新下测试版，修过了

**Comment by DreAmVirGo** [comment]
> 更新下测试版，修过了
一开始更了测试版没能链接到模拟器没有第一时间回复。
现在正常了。谢谢！
