### ISSUE TITLE
傀影肉鸽获得收藏品后会卡着

### ISSUE THREAD

**Issue by WyeJun** [MaaAssistantArknights/MaaAssistantArknights#2169]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

傀影肉鸽获得收藏品后会卡着 不会点选勾继续前进
问题出现的大致时间点是22：24 左右

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9716534/asst.log)

### 截图

![Screenshot_2022 10 05_22 41 50 578](https://user-images.githubusercontent.com/115093698/194089106-145b7780-610d-4aa6-a8ec-40c99e3192da.png)

### 还有别的吗？

1

**Comment by MistEO** [comment]
@zzyyyl 这个是不是也修了？

**Comment by zzyyyl** [comment]
草，这我不知道，最近没测过傀影）

**Comment by zzyyyl** [comment]
好像没有？我甚至没见着类似的 task

**Comment by zzyyyl** [comment]
这玩意应该叫 `剧目集` 不是 `收藏品` 吧
