### ISSUE TITLE
肉鸽挂机中银灰2技能不断切换

### ISSUE THREAD

**Issue by shenFNX** [MaaAssistantArknights/MaaAssistantArknights#2171]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在肉鸽中，银灰得2技能是切换得，然而MAA不停的切换

### 日志文件

[Uploading asst.log…]()

**Comment by zzyyyl** [comment]
日志没传上来

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/6a2f6d1534a70c7e84ed360781bf726beb0c1681 fixed

**Comment by WWPXX233** [comment]
其实我是想回血和嫖伤害在一起的不过还是改一看起来比较好
