### ISSUE TITLE
关于“宿舍空余位置蹭信赖”选项的问题

### ISSUE THREAD

**Issue by pu4ers** [MaaAssistantArknights/MaaAssistantArknights#2175]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

启用了“自定义基建配置”“宿舍空余位置蹭信赖”。
在问题出现的时间段，自定义排班时间表中的宿舍3、4分别设置为“一名固定干员”“两名固定干员”，“autofill”都为true。
在填充第三宿舍干员时，已没有心情未满的未进驻干员，此时脚本在放入固定干员后启用了“信赖排序”。
在填充第四宿舍干员时，由于已启用了“信赖排序”的关系，信赖值遮挡了干员名，导致脚本无法找到所需固定干员，陷入死循环，不断遍历整个干员列表。
建议：在每次进入宿舍进行操作前，先检查排序状态，切换为工作状态排序后再开始操作。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9717798/asst.log)

### 截图

![Screenshot_2022 10 06_01 22 51 682](https://user-images.githubusercontent.com/115104648/194123059-143b4d18-582c-416a-816d-511f9e9d752f.png)

### 还有别的吗？

win10，版本是v4.6.0-beta.2

**Comment by MistEO** [comment]
所以为啥要把他们分开放（
