### ISSUE TITLE
基建换班中识别柏喙和砾发生错误

### ISSUE THREAD

**Issue by portfolio0318** [MaaAssistantArknights/MaaAssistantArknights#2176]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我使用的模拟器是国际版蓝叠模拟器，并且确认已经将分辨率调为320DPI和1280*720.
基建换班中，识别砾不稳定，有时会识别为砾，但是有时会识别为陈；识别柏喙时，只能识别为柏。我已经在log文件中查到了对应的条目，在2022-10-06 02:02:19.745发生了砾的识别错误（实际位置为砾，但是识别为陈）；
2022-10-06 02:02:19.647发生了柏喙识别错误。
我测试了很多次结果均为如此，log只有一次测试结果的原因是我删除了之前的log以方便阅读。
截图分别为正确识别了砾名字的截图，错误识别了砾名字的截图，以及错误识别了柏喙名字的截图。

### 日志文件

[Uploading a
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9717997/asst.log)
sst.log…]()

### 截图

![Screenshot_2022 10 06_02 05 06 561](https://user-images.githubusercontent.com/80657086/194131679-26715304-86b2-42e4-9edd-168256c1773e.png)
![Screenshot_2022 10 06_02 03 30 661](https://user-images.githubusercontent.com/80657086/194131700-775fd5ac-f2bb-49cf-8704-fd5e0973e641.png)
![Screenshot_2022 10 06_02 03 24 595](https://user-images.githubusercontent.com/80657086/194131707-2c2db2d6-429c-4293-b0fa-f96f8e2cf2b2.png)

### 还有别的吗？

使用的模拟器为蓝叠国际版，分辨率为320DPI，1280*720.
模拟器设置配置为60帧，CPU4核心，内存分配4GB，高性能，且开启了垂直同步。

**Comment by portfolio0318** [comment]
上传失败的log已经重新上传

**Comment by zzyyyl** [comment]
柏喙的问题修了，砾修不了（大概

**Comment by cenfusheng** [comment]
2022.12新模型已修复
