### ISSUE TITLE
水月肉鸽中“神经退行”的干员无法识别

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#2177]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

N/A

### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9718525/asst.-.log)

时间点
![image](https://user-images.githubusercontent.com/18511905/194148573-23363950-bd4c-429c-9443-f021978a7a46.png)

### 截图

![Screenshot_2022 10 06_03 40 03 243](https://user-images.githubusercontent.com/18511905/194148413-7a4e3d34-b487-4d8b-b19a-0b9c02ca9cb5.png)
![Screenshot_2022 10 06_03 40 21 810](https://user-images.githubusercontent.com/18511905/194148420-55c79b0c-50c3-4c6f-8a32-382c88cf930c.png)

**Comment by MistEO** [comment]
话说其他几种”排异反应“，是一样的颜色和图标么，还是有差异的？

**Comment by DreAmVirGo** [comment]
> 话说其他几种”排异反应“，是一样的颜色和图标么，还是有差异的？

都是一样的，ui表现为紫色背景。在外面（地图）才能看见具体是什么排异。
