### ISSUE TITLE
新版本后不能打傀影肉鸽的月度小队，并且在取消勾选水月肉鸽以后，还是会自动跳转水月肉鸽

### ISSUE THREAD

**Issue by bkmz888** [MaaAssistantArknights/MaaAssistantArknights#2179]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

1.在取消勾选水月肉鸽以后，不会进入傀影肉鸽。
2.在进入傀影月度小队以后，不会自动作战，而是不停返回主页。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9720668/asst.log)

### 截图

![2022-10-06_10-11-14 097_raw](https://user-images.githubusercontent.com/115127080/194201204-f2bb70a3-1072-4dba-8804-0cb643799cf5.png)
![2022-10-06_10-11-30 426_raw](https://user-images.githubusercontent.com/115127080/194201214-4a9a14a1-6e86-44fb-b5bc-4ccd6851f6db.png)

**Comment by vcfch843875618** [comment]
这个问题也许再下载一个以前版本的MAA就能解决吧……

**Comment by ABA2396** [comment]
取消勾选之后要重启才能生效

**Comment by bkmz888** [comment]
> 取消勾选之后要重启才能生效
啊这 是我的问题

**Comment by ABA2396** [comment]
> > 取消勾选之后要重启才能生效
> > 啊这 是我的问题

重写了这部分，加了个弹窗提示，下个版本应该就可以了）
