### ISSUE TITLE
能不能自动识别屏幕的方向

### ISSUE THREAD

**Issue by neko-para** [MaaAssistantArknights/MaaAssistantArknights#2180]
### 说说你遇到的问题？

> 一些背景
> 更新了Windows11 22H2后HyperV炸了，即使重新安装hyperv相关的若干功能，基于hyperv的蓝叠5还是启动不了，基于原始的又提示hyperv已启动。
> 不过AVD还是能用，但是在尝试了若干次后，每次方舟在下载第一批资源的时候都会不停地网络错误，然后丢失无数进度，进不去
> 最后用usb连接真机，然后用adb tcpip 5555切换成了socket模式，但是maa识别到的分辨率似乎是竖屏的，然后直接提示了分辨率不支持

### 有什么好的想法？

支持竖屏分辨率，自动尝试分析长宽关系旋转截图

---

或者，有没有什么办法能让AVD中的方舟稳定的把数据下下来？

### 其他内容

分辨率信息

![image](https://user-images.githubusercontent.com/26452623/194205938-34c995b9-325d-4a11-8693-7fc775108cfd.png)

![image](https://user-images.githubusercontent.com/26452623/194205970-e64184dc-88c4-43ad-b0bd-338ab119d16c.png)

**Comment by MistEO** [comment]
支持竖屏，不支持非 16:9 / 9:16
