### ISSUE TITLE
无限制内存写入

### ISSUE THREAD

**Issue by gClov** [MaaAssistantArknights/MaaAssistantArknights#2181]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在肉鸽运行过程中，软件会一直无限制的向内存写入内容并且除重启电脑外无解决办法。

### 日志文件

[Uploading asst.log…]()

**Comment by gClov** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9720881/asst.log)

**Comment by MistEO** [comment]
任务管理器 - 详细信息 - 右键排序列 - 选择列- 提交大小，看一下，确定是 MAA 吃的么？

**Comment by gClov** [comment]
看不出来

![a2184e7a6e6ae75dee966dbd9a6864c](https://user-images.githubusercontent.com/115129135/198861558-a1174ed9-098b-42d8-82be-ad1e6b49531b.jpg)
这是刚开机只有微信在后台的的内存占用
![b567a5f9aa0da547e9d50bf7361496a](https://user-images.githubusercontent.com/115129135/198861581-97b9e5e5-dbff-46d4-943e-fa2d344aaa6f.jpg)
这是运行2个半小时后关闭除微信外的所有应用（与上张图片的后台一致）的占用
![image](https://user-images.githubusercontent.com/115129135/198861657-a135b993-6147-4813-b495-6786b148000f.png)

这是打开了一些应用但未开启肉鸽的占用和提交大小
![image](https://user-images.githubusercontent.com/115129135/198861668-cb73c12c-68ae-456e-8d00-c3bfe3d771ef.png)
![image](https://user-images.githubusercontent.com/115129135/198861703-df2196e9-bf06-43c8-9676-fbe6df1c4c45.png)

这是开启肉鸽2个半小时的占用和提交大小（在打开肉鸽时，提交大小已经提升到了1.6g，在肉鸽运行过程中并无明显改变）
![image](https://user-images.githubusercontent.com/115129135/198861767-31c21191-90bf-422f-97ac-66e8220d38f3.png)
![image](https://user-images.githubusercontent.com/115129135/198861770-e234e1f5-e890-4dac-b520-8075a5fa897a.png)

**Comment by zzyyyl** [comment]
雷电模拟器？那建议换一个模拟器

**Comment by gClov** [comment]
比较喜欢用这个模拟器。部落冲突也是用雷电模拟器挂的，一次基本挂一个白天，没出现无法清除的内存占用过

**Comment by zzyyyl** [comment]
雷电的内存溢出是已知问题，至少其它模拟器没那么严重。

而且 maa 并未保证提供对雷电模拟器的稳定支持）

**Comment by zzyyyl** [comment]
按照你的任务管理器截图，占用内存的大头三个都是雷电的进程：）

**Comment by gClov** [comment]
那个提交大小maa肉鸽时就一直是1.6g，雷电模拟器那俩个部落冲突的就是0.7g~1.3g，开肉鸽的明日方舟基本1.3，1.4左右。这个倒没什么，就是那些不知道哪里写出来的不能回收（？的内存很麻烦，之前几次发现部落冲突（我另外模拟器挂的游戏）一直卡在加载界面就知道内存已经写满了，就得重启了

**Comment by gClov** [comment]
排除了指针导致的内存泄露吗

**Comment by MistEO** [comment]
现在换 onnx runtime 了，应该没内存的问题了
