### ISSUE TITLE
傀影肉鸽会被四点数据更新打断

### ISSUE THREAD

**Issue by InfraFour** [MaaAssistantArknights/MaaAssistantArknights#2182]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

深夜挂机，跨四点的一把结束回到肉鸽主界面时，会因为游戏内出现数据已更新的确认弹窗卡死

v4.6.0-alpha.8，在使用该版本运行水月肉鸽/使用过往版本运行傀影肉鸽时没有遇到过此问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9720874/asst.log)

**Comment by MistEO** [comment]
卡在哪个界面了？

**Comment by InfraFour** [comment]
![MuMu20221007042420](https://user-images.githubusercontent.com/110469711/194487118-2814f43c-4c34-4007-bccf-9d804956eb20.png)
![屏幕截图 2022-10-07 042442](https://user-images.githubusercontent.com/110469711/194487134-5bd598b2-1379-4c35-b9e4-02ade4d4a7a5.jpg)

**Comment by MistEO** [comment]
你的日志被冲掉了 orz，下次再遇到的话连 asst.log 和 asst.bak.log 一起发下看看

**Comment by InfraFour** [comment]
抱歉抱歉，界面截图是今早新截的，对应的日志是下面这个，我看bak里有凌晨的时间段
[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9733155/asst.bak.zip)
