### ISSUE TITLE
指定材料的刷取数量失效

### ISSUE THREAD

**Issue by LittleNightmare** [MaaAssistantArknights/MaaAssistantArknights#2184]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如图所示，在刷芯片的过程中，首先第一次就已经达到指定数量，但没有停止。第二次结束后也没停，继续刷了

随后我又测试了1-7的固源岩，在图3上，材料数量已经超过指定数量了，且没有进行跳转（应该是回到开始界面再进一次1-7吧）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9721076/asst.log)

### 截图

![1%RX4DK@9~F$2R ETPUJ@}G](https://user-images.githubusercontent.com/19811879/194210418-b2115fe3-3970-4ef4-9ff4-103291b87e0b.png)
![78{$ )Z(D8U@UJW@UB %$W3](https://user-images.githubusercontent.com/19811879/194210428-9976e5ba-c51a-4c1d-9c22-8bcf2b79eea6.png)
![image](https://user-images.githubusercontent.com/19811879/194211380-9fe477fe-0ab0-4788-ad13-7eb0b5d6ad4c.png)

### 还有别的吗？

蓝叠5 64位
win10
maa-beta3

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/194218570-65cb28e4-b3d3-4b2f-a01c-8c874b6f330f.png)
设置成功的话log里应该有"drops"字段，但是你的日志里没有，所以设置没生效，这种情况应该重启后这一行会变成空

**Comment by ABA2396** [comment]
3b87d39 尝试修了下，不知道好不好使，反正输入没生效会变成请输入，这样至少知道没生效

**Comment by MistEO** [comment]
> 3b87d39 尝试修了下，不知道好不好使，反正输入没生效会变成请输入，这样至少知道没生效

commit id 好像贴错了

**Comment by ABA2396** [comment]
> > [3b87d39](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/3b87d395bbb13251239b0fe72d1580072982463f) 尝试修了下，不知道好不好使，反正输入没生效会变成请输入，这样至少知道没生效
> 
> commit id 好像贴错了

怪事（）我明明之前还点进去检查过了
