### ISSUE TITLE
水月肉鸽第五层紧急作战“机械之灾”似乎无法识别敌方攻击范围

### ISSUE THREAD

**Issue by vcfch843875618** [MaaAssistantArknights/MaaAssistantArknights#2185]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

第五层紧急作战“机械之灾”里似乎无法识别到[帝国炮火中枢先兆者]的攻击范围，干员会被放置到其攻击范围内，推测普通版本的[帝国炮火先兆者]也会有同样的问题。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9721197/asst.zip)

### 截图

<img width="959" alt="屏幕截图 2022-10-06 121859" src="https://user-images.githubusercontent.com/49860324/194214250-95de38a3-6b2f-45ee-8e32-549d69e0a521.png">

**Comment by horror-proton** [comment]
其实所有关卡都不能识别敌方攻击范围

**Comment by fearlessxjdx** [comment]
我都从来没想过这玩意能打到第五层 哈哈
