### ISSUE TITLE
傀影肉鸽与水月肉鸽之间的切换问题，MAA内选择的肉鸽与游戏内固定的不同时，无法进入肉鸽

### ISSUE THREAD

**Issue by LmeSzinc** [MaaAssistantArknights/MaaAssistantArknights#2188]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我正在使用 v4.6.0-beta.3。

复现步骤：
1. 打开 `For Mizuki`，选择水月肉鸽
2. 在肉鸽（集成战略）界面，左侧边栏固定傀影肉鸽
3. 运行 MAA，MAA在以下界面循环切换：主界面 > 终端 > 傀影肉鸽 > 集成战略 > 主界面

反过来，关闭 `For Mizuki`，固定水月肉鸽，也能复现。

### 日志文件

日志文件已清理，这里仅包含复现产生的log。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9721904/asst.log)

### 还有别的吗？

我设想的解决办法：
在肉鸽选择界面（集成战略），点击侧边栏切换到对应的肉鸽

![Screenshot_20221006-144927](https://user-images.githubusercontent.com/37934724/194233494-016f2eb4-4cfa-4c27-829e-388592762967.png)

**Comment by DavidWang19** [comment]
目前beta版还不好做，得等到正式版大概才会做出来

**Comment by Zebartin** [comment]
同版本，MAA不勾选`For Mizuki`，游戏内固定傀影肉鸽，也会出现类似结果

**Comment by zzyyyl** [comment]
等肉鸽重构，不然这个进入了也没有意义，`开始探索` 识别不了

**Comment by zzyyyl** [comment]
这个逻辑在 tasks.json 的 `IntegratedStrategies` 相关任务

**Comment by ABA2396** [comment]
我记得之前写过一个主界面没有傀影肉鸽时通过下面那一行点进集成战略的task，改改应该能用（？）

**Comment by zzyyyl** [comment]
> 我记得之前写过一个主界面没有傀影肉鸽时通过下面那一行点进集成战略的task，改改应该能用（？）

就是我说的那个：）

**Comment by pc-seawind** [comment]
所以，如果现在想要刷傀影肉鸽，就必须要回退到老版本么？

**Comment by zzyyyl** [comment]
pin傀影；for mizuki去掉；重启maa

**Comment by pc-seawind** [comment]
OK，get 原来是少了重启MAA这一步。。。期待后续可以给一个提示~

**Comment by zzyyyl** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/2196 做了
