### ISSUE TITLE
希望肉鸽开关改成下拉菜单，并暴露接口

### ISSUE THREAD

**Issue by LmeSzinc** [MaaAssistantArknights/MaaAssistantArknights#2189]
### 说说你遇到的问题？

我们正在做 [ALAS](https://github.com/LmeSzinc/AzurLaneAutoScript) 的 MAA 插件，现在基本完成了 https://github.com/LmeSzinc/AzurLaneAutoScript/pull/1657 ，但还有一些问题希望得到解决。

1. https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2188
2. 将 `For Mizuki` 选项修改为下拉菜单选择肉鸽，选择傀影肉鸽或水月肉鸽
3. 暴露肉鸽选择的接口

**Comment by zzyyyl** [comment]
core 现在还不支持肉鸽重选，只能通过 load 不同的 resource 来处理。
等之后的肉鸽全重构了再说（已经新建文件夹了

**Comment by ABA2396** [comment]
> core 现在还不支持肉鸽重选，只能通过 load 不同的 resource 来处理。 等之后的肉鸽全重构了再说（已经新建文件夹了

和语言一样呗，弹个窗要求重启

**Comment by MistEO** [comment]
> > core 现在还不支持肉鸽重选，只能通过 load 不同的 resource 来处理。 等之后的肉鸽全重构了再说（已经新建文件夹了
> 
> 和语言一样呗，弹个窗要求重启

有道理，现在连个提示都没有确实不合理，学姐带带。仅在关的时候弹窗就好了，开是实时生效的不用重启

**Comment by MistEO** [comment]
> > core 现在还不支持肉鸽重选，只能通过 load 不同的 resource 来处理。 等之后的肉鸽全重构了再说（已经新建文件夹了
> 
> 和语言一样呗，弹个窗要求重启

有道理，现在连个提示都没有确实不合理，学姐带带。仅在关的时候弹窗就好了，开是实时生效的不用重启

**Comment by MistEO** [comment]
> > core 现在还不支持肉鸽重选，只能通过 load 不同的 resource 来处理。 等之后的肉鸽全重构了再说（已经新建文件夹了
> 
> 和语言一样呗，弹个窗要求重启

有道理，现在连个提示都没有确实不合理，学姐带带。仅在关的时候弹窗就好了，开是实时生效的不用重启
