### ISSUE TITLE
水月肉鸽完成除暴安良后进入紧急运输节点卡住

### ISSUE THREAD

**Issue by sixivanzi** [MaaAssistantArknights/MaaAssistantArknights#2191]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

当通过关卡 `除暴安良` 后进入 `紧急运输` 节点，会进入 `派遣干员` 界面后在**未选择任何干员**的情况下点击 `确认调遣` 然后弹出上图界面卡住

### 日志文件

10-06  15:10:24

[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9727233/asst.bak.zip)

### 截图

![image](https://user-images.githubusercontent.com/115142803/194381624-83602c21-d34a-4d1d-99ed-d7a588fc0e7c.png)

### 还有别的吗？

蓝叠国际版10   32位
4.6.0-beta.3

**Comment by sixivanzi** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9722527/asst.log)
![image](https://user-images.githubusercontent.com/115142803/194257642-8b347d08-07be-472a-a589-0905901ac173.png)

**Comment by sixivanzi** [comment]
10.06  12点55应该也发生了同样问题

**Comment by FrecklySoda** [comment]
我这个版本也遇到了同样的问题

**Comment by sixivanzi** [comment]
刚注册的github不太会用，如果我提肉鸽机器人会自动加入肉鸽标签吗

**Comment by sixivanzi** [comment]
刚注册的github不太会用，如果我提肉鸽机器人会自动加入肉鸽标签吗（
肉鸽肉鸽肉鸽BUGBUGBUG

**Comment by sixivanzi** [comment]
2022-10-06 13:00:49.442出现了相关问题，10-06 15:10:24也是卡在同一个页面

**Comment by sixivanzi** [comment]
对不起我是憨批

**Comment by sixivanzi** [comment]
> 2022-10-06 13:00:49与10-06 15:10:24都出现了此问题

**Comment by sixivanzi** [comment]
另外，在10.04我使用的BETA2版本中似乎并未出现卡住的问题，但系统仍然判定其为BUG
10.04DEBUG文件内出现了多个作战后接紧急运输的图片，但MAA并没有卡住
[作战后紧急运输.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9727344/default.zip)
很遗憾相关log没有了

**Comment by sixivanzi** [comment]
抱歉第一次用github不懂规矩如有高血压操作请见谅
