### ISSUE TITLE
傀影肉鸽“邪异囚笼”关卡存在逻辑错误

### ISSUE THREAD

**Issue by WitherLing** [MaaAssistantArknights/MaaAssistantArknights#2194]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在场上不存在剩余部署位且费用充足的情况下，会不断轮流选择待部署区域干员（在本案例中是梓兰和预备术士），以此造成战斗效率大幅下降（全程慢放）。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9724461/asst.log)
最后一段

**Comment by zzyyyl** [comment]
用 beta3 再试试
