### ISSUE TITLE
制造站和贸易站中，换班较慢，优化操作顺序后可加快

### ISSUE THREAD

**Issue by fearlessxjdx** [MaaAssistantArknights/MaaAssistantArknights#2195]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

制造站和贸易站中，若换班人员不变或变化不大的情况下，他还是会从左到右找一遍，导致换班很慢。

宿舍和中枢存在相同情况

我观察了下主要原因：**脚本先点了 ”清空“ ，然后点了上方的 ”技能“ 键**，导致本来有序的人员变为无序，然后脚本又去一个个找，速度较慢。

---

* 经尝试，只需改为先点 ”技能“ 等，再点 ”清空“ 即可加快找人速度
* 补充一下，又试了几遍，中枢、会客厅、宿舍似乎也存在这个问题，似乎除了供电站都存在这个问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9724933/asst.log)

### 还有别的吗？

版本：v4.6.0-beta.3

**Comment by auroralwy** [comment]
> 

你是说仅换一两个人的时候吗，我遇到的情况比较少。
只有巫恋的时候会有这种情况，具体的话试试candidate能行么，不确定能不能解决。
另外我不动的话前面的人员信息都是用空序列的，似乎不会有问题

**Comment by fearlessxjdx** [comment]
`经尝试，只需改为先点 ”技能“ 等，再点 ”清空“ 即可加快找人速度`

我觉得代码上将这两个逻辑反一下，就能解决这个问题了。而且并不影响本来就要找三四个人的速度，只是加快了较少变化时的换班速度。

很想帮忙，但我根本找不到代码，太不熟悉了- -!

**Comment by zzyyyl** [comment]
你啥系统啊 编译环境不难搭的吧（x

~~怎么能自己没测就提pr呢）~~

**Comment by fearlessxjdx** [comment]
Remove {bug}
Add {perf}

**Comment by fearlessxjdx** [comment]
Remove {bug}
