### ISSUE TITLE
招募券选择第三个时识别位置异常

### ISSUE THREAD

**Issue by WWPXX233** [MaaAssistantArknights/MaaAssistantArknights#2197]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

![image](https://user-images.githubusercontent.com/64907423/194324638-b6282efa-fba7-4819-abed-752d6d0e71bd.png)

### 日志文件

![~J8W OTAFZZ({R IJGB4}U7](https://user-images.githubusercontent.com/64907423/194325086-8e4c4646-832d-43ac-a479-7bb41f5d0e2d.png)

**Comment by zzyyyl** [comment]
这是方舟的 bug，进入招募界面时不在最左边

解决方案是开局前先往左滑几次
