### ISSUE TITLE
肉鸽刷投资能否一层避战，有不期而遇就走不期而遇，以及战斗结束放弃招募节省时间。

### ISSUE THREAD

**Issue by auroralwy** [MaaAssistantArknights/MaaAssistantArknights#2198]
### 说说你遇到的问题？

RT，翻了圈json文件，好像没有地方可以设置，反正初始已经有18块钱可以存了。感恩。
战斗结束翻招募券是有点浪费时间了，如果拿完钱直接离开就行。

**Comment by MistEO** [comment]
现在的策略就是优先走不期而遇的

**Comment by zzyyyl** [comment]
放弃招募maa就打不过了）
