### ISSUE TITLE
关于巫恋组放置基建顺序变化导致效率降低的问题

### ISSUE THREAD

**Issue by snowingwang** [MaaAssistantArknights/MaaAssistantArknights#220]
脚本识别到巫恋组满心情时会按照1.巫恋 2.卡夫卡 3.龙舌兰的顺序放置干员。
当上述三位干员已经在贸易站时运行脚本，会按照1.巫恋 2.龙舌兰 3.卡夫卡的顺序重复放置，造成巫恋和卡夫卡加成时长被清零的问题。
另外当设置无人机不使用时，脚本依然会对巫恋组使用无人机。
模拟器是雷电
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8054911/asst.log)

**Comment by MistEO** [comment]
感谢反馈，无使用使用的问题下个测试版本发布

加成时长被清零，这个问题不太好搞，作为长期计划了

**Comment by MistEO** [comment]
现在用自定义基建可以解决这个问题了
