### ISSUE TITLE
反馈一下maa水月肉鸽bug

### ISSUE THREAD

**Issue by Charlespkuer** [MaaAssistantArknights/MaaAssistantArknights#2201]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

1、maa完全不会用钥匙，建议加一个能用则用
2、maa不期而遇行为逻辑优化（多写点if罢）
3、maa无法识别血肉畸变（等异常状态）干员，技能不会更换（而默认1技能）
4、能不能让maa抓一下随机送的0希望干员啊啊啊

### 日志文件

无

### 截图

无

### 还有别的吗？

无

**Comment by WWPXX233** [comment]
需要完成这些的工作量是在是太大了 目前主要还是以能刷取等级为主
