### ISSUE TITLE
日服肉鸽不期而遇问题

### ISSUE THREAD

**Issue by w1017064903** [MaaAssistantArknights/MaaAssistantArknights#2203]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在这个不期而遇中直接不动了。00：07：04

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9726770/asst.log)

### 截图

![QQ截图20221007003135](https://user-images.githubusercontent.com/98521231/194368613-73151bfc-df54-46d4-ab5e-a70e4e944dea.png)

**Comment by MistEO** [comment]
fixed, similar to https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2208
