### ISSUE TITLE
自定义基建Json文件如果没定义干员的房间可不可以不给换班啊

### ISSUE THREAD

**Issue by MirrorDraw** [MaaAssistantArknights/MaaAssistantArknights#2205]
### 说说你遇到的问题？

就是我有时候不需要换班，只需要换一下休息室，但是我脚本中只写了休息室自动换，但是它会把所有房间都换掉，希望能改进这一点。

### 有什么好的想法？

希望优化成不写的房间不换班。

**Comment by Zebartin** [comment]
参考[基建排班协议](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/3.6-%E5%9F%BA%E5%BB%BA%E6%8E%92%E7%8F%AD%E5%8D%8F%E8%AE%AE.md)，里面的`skip`字段应该就是你想要的

**Comment by fearlessxjdx** [comment]
@Zebartin 我觉得他的建议挺好的，配置文件里没写的设施就应该当作不关心直接跳过。
目前的情况下，假如我只想写一个设施的换班，却要将其他设施的配置文件写全，我觉得完全没必要。直接约定未写明就跳过不是挺好？

**Comment by fearlessxjdx** [comment]
举个极端的例子，想挂个收菜的任务，要写十几个 skip
