### ISSUE TITLE
傀影肉鸽第五层"血月长廊“的"鉴赏家”不期而遇事件存在逻辑错误 

### ISSUE THREAD

**Issue by WitherLing** [MaaAssistantArknights/MaaAssistantArknights#2208]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

遇到该事件时会完全卡死无法进行下一步,也不会放弃肉鸽从头开始.

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9730397/asst.log)

约为五点出头的事件,触发后便一直死循环

### 截图

![Screenshot_20221007-104413](https://user-images.githubusercontent.com/74227748/194459605-935e5d05-af31-4961-b97a-878418de3d10.png)

**Comment by MistEO** [comment]
哪个版本的？

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/194511999-bf637818-a306-43ca-8aa9-a4afe1421877.png)

**Comment by WitherLing** [comment]
版本是beta3

**Comment by WitherLing** [comment]
[asst (2).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9732281/asst.2.zip)
