### ISSUE TITLE
基建选人的时候有时候会爆划导致错过要选的干员

### ISSUE THREAD

**Issue by zackynaty** [MaaAssistantArknights/MaaAssistantArknights#2209]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

基建选人的时候有时候会爆划，导致错过要选的干员。没有特定出现在某个房间或时机。
平时正常选人滚屏的时候，一屏6列干员，滚动一次第6列会滚到原第3列的位置。
爆划的时候滚动一次，第6列都直接错过，原第8/9列会滚到第1列的位置。
然后要选的干员正好在错过的两个列里面。
虽然有兜底的回到开头再来一次，但有时候还是会再次爆划，然后就算成找不到人了，直接空位了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9730808/asst.log)
10-07 12:41:33

### 截图

![Uploading Screenshot_20221007-130509.png…]()

### 还有别的吗？

夜神模拟器。1280*720*320，60帧。

**Comment by zackynaty** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9730830/asst.log)
![Uploading Screenshot_20221007-130509.png…]()

**Comment by MistEO** [comment]
这个是 adb 的 bug，算是已知问题，解决不了，所以才有个兜底策略。后面我们打算把 adb 直接换成 minitouch

**Comment by ntgmc** [comment]
目前您可以尝试更新到内测版来看看这个问题修复没有。
At present, you can try to update to the internal beta to see if this problem is fixed.

**Comment by MistEO** [comment]
已经上线了 minitouch 和 maatouch
