### ISSUE TITLE
肉鸽模式会卡在剧目集页面

### ISSUE THREAD

**Issue by Etherrrr** [MaaAssistantArknights/MaaAssistantArknights#221]
![Snipaste_2022-02-14_02-06-49](https://user-images.githubusercontent.com/20717049/153766356-987ac4bb-22f9-4b0a-aca1-fdb7dff9798f.png)
![image](https://user-images.githubusercontent.com/20717049/153766385-e19d340a-81e3-42a7-ad9a-e15bb1f3da50.png)
如题 经常出现在第一层第一关打完后出现剧目集的情况下
如图所示 卡在剧目集页面时无法自动退出 手动退出后脚本会判定为任务失败（此时刚打完第一关）自动退出重开
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8056176/asst.log)

**Comment by MistEO** [comment]
v3.1.3 fixed
