### ISSUE TITLE
自定义基建换班无法自动选择对应时间段班次

### ISSUE THREAD

**Issue by DemiurgeZ** [MaaAssistantArknights/MaaAssistantArknights#2210]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

使用自定义基建换班功能，设置为一天三换，三班分别为B+C(00:30-04:29), A+C(04:30-08:29), A+B(08:30-00:29).
MAA定时执行时间设置为1，5，9. 按照设置，应分别在以上三个时间点自动执行三个班次的换班任务。

实际情况是，凌晨00:57左右手动启动MAA及模拟器，并于01:00至01:10期间通过定时执行成功完成B+C换班（不得不吐槽一句这换班速度有点感人...)；
之后启用功能“访问好友”“基建换班”“收取信用及购物”“刷理智”，并让MAA挂机等候定时执行任务；
再然后就是早上起床后发现MAA并未执行A+C班次的换班（或者说执行了但失败了），基建内是A+B的班次在上班，但B班干员心情均未恢复。

### 日志文件

日志文件：问题出现时间在5:00AM之后
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9730642/asst.log)

自定义换班配置文件：出现问题的班次为04:30-08:29这一班（即A+C组）
[custom_infrast.json.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9730645/custom_infrast.json.txt)

### 还有别的吗？

MAA：v4.6.0-beta.2
模拟器：蓝叠国际版(Hyper-V) version:5.6.110.1002 N64
操作系统：Win10 22H2

**Comment by MistEO** [comment]
看看有没有个 gui.log 文件，也发下看看
