### ISSUE TITLE
傀影肉鸽频发崩溃问题

### ISSUE THREAD

**Issue by yuantianyuan01** [MaaAssistantArknights/MaaAssistantArknights#2217]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

自动傀影肉鸽的时候运行一段时间后大概率MAA崩溃退出（模拟器照常运行）。发生时间约为自动挂机开始后的1-3小时，一般发生在战斗过程中，目前还没有过稳定运行5小时以上。在4.5.0稳定版、4.6.0-beta3以及4.6.0-rc1均有发生。

### 日志文件

[asstlog-4.6.0-rc1.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9734544/asstlog-4.6.0-rc1.zip)
[asstlog-4.5.0-stable.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9734550/asstlog-4.5.0-stable.zip)

### 还有别的吗？

使用夜神模拟器最新版7.0.3.7

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/194702051-17bfb44a-8bdf-4937-bad5-81e9981cd99e.png)
![image](https://user-images.githubusercontent.com/18511905/194702064-86393a9f-9d65-4edd-a504-d298faed694e.png)

第一行就是截图，日志没打出来，应该是崩里面了，@zzyyyl 来瞅瞅有没有头绪orz

**Comment by yuantianyuan01** [comment]
今天用4.6.1-alpha1刷1-7又遇到了崩溃，看log感觉是不一样的问题。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9740802/asst.log)

**Comment by dantmnf** [comment]
建议检查 `C:\Users\<用户名>\AppData\Local\CrashDumps` 下有没有对应时间的 dump 文件，并且私信或邮件发送给作者方便排查。

**Comment by yuantianyuan01** [comment]
> 建议检查 `C:\Users\<用户名>\AppData\Local\CrashDumps` 下有没有对应时间的 dump 文件，并且私信或邮件发送给作者方便排查。

ok，方便提供一下邮箱吗

**Comment by yuantianyuan01** [comment]
[errors.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9741229/errors.txt)
这是dump文件的分析结果

**Comment by dantmnf** [comment]
尴尬，发包的时候好像把 CI 构建的符号丢了🌚

**Comment by MistEO** [comment]
加了些日志，帮忙用这个版本再复现一下 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/3213808406 （大约等个十分钟包就出来了）

**Comment by yuantianyuan01** [comment]
> 加了些日志，帮忙用这个版本再复现一下 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/3213808406 （大约等个十分钟包就出来了）

好的，我跑一晚上看下能不能复现。

**Comment by yuantianyuan01** [comment]
这样好像会让log有亿点大，大概几分钟就上百M了

**Comment by MistEO** [comment]
> 这样好像会让log有亿点大，大概几分钟就上百M了

复现的话传一下最后的几百行即可

**Comment by yuantianyuan01** [comment]
这是最后1k行
[new.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9741557/new.log)

**Comment by yuantianyuan01** [comment]
可能是越界？我发现它崩的时候会把别的程序也搞崩，比如浏览器啥的

**Comment by dantmnf** [comment]
上面那个包里有符号了，可以用 windbg 看看 stack trace

**Comment by yuantianyuan01** [comment]
长这个样子
[errors.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9741600/errors.txt)

**Comment by dantmnf** [comment]
> ```
> 00000010`5cffbec0 00007ff8`151e2d44     : 00000000`1538e101 0000020c`2ba78290 00007ff8`1538e178 00007ff8`1538e101 : MeoAssistant!AsstLog+0xe60d5
> ```

![image](https://user-images.githubusercontent.com/2252500/194759182-135a8397-5777-4371-9551-42bd3b7d6f5b.png)

`operator new` 里抛出了 `std::bad_alloc`，最近的 user code 在

> ```
> 00000010`5cffbfe0 00007ff8`151eb893     : 00000010`5cffc900 00007ff8`152dfb72 00000010`5cffc928 00000000`00000000 : MeoAssistant!AsstLog+0x1a1c
> ```

![image](https://user-images.githubusercontent.com/2252500/194759226-7eb4a940-f0c6-4ae8-a07c-20d4b17e3975.png)

对应 https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/380f93f4dd630fec3ba819c1e00fa9cbfa84360d/src/MeoAssistant/Controller.cpp#L338

> 我发现它崩的时候会把别的程序也搞崩，比如浏览器啥的

结合这个现象，建议检查是否有异常内存占用增长。

**Comment by yuantianyuan01** [comment]
观察到夜神模拟器的内存确实会周期性增长，从100M慢慢涨到5 6个G，到达峰值后会突然清零。不过还没有直接观察到崩溃时的占用情况。这是不是说明可能是模拟器的问题？
![屏幕截图 2022-10-09 221205](https://user-images.githubusercontent.com/45124314/194761725-0b52199a-e147-43b4-86cb-29a021db5a10.png)

**Comment by dantmnf** [comment]
这里不会显示交换到 page file 的容量，突然清零有可能是交换到硬盘了。同理其他进程也很可能存在类似情况。

实际分配大小需要在详细信息页右键表头调出”提交大小“列查看。

**Comment by yuantianyuan01** [comment]
学到了，观察了一下确实提交大小会持续异常增长而且不会下降，到很大的时候（10+G）就会崩溃。初步可以定位为夜神模拟器问题？
我换了蓝叠国际版没有内存异常增长问题了，可以跑一晚上看看还会不会崩溃。

**Comment by yuantianyuan01** [comment]
换了蓝叠问题解决了，应该是和夜神模拟器有关系。
