### ISSUE TITLE
水月肉鸽紧急运输卡住不动

### ISSUE THREAD

**Issue by najuse** [MaaAssistantArknights/MaaAssistantArknights#2219]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

v4.6.0-beta.3版本的自动肉鸽水月，遇到紧急运输关卡后会一直卡在那，

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9734986/asst.log)
10-07     21：55：40~~22：45：01
最后是手动点掉的

### 截图

![uTools_1665154592059](https://user-images.githubusercontent.com/115262294/194585127-fc7076f4-9fa7-4921-8741-cf9c31273210.png)
![uTools_1665154573216](https://user-images.githubusercontent.com/115262294/194585142-83e258f2-c3f7-4bbf-9830-9117300dffb2.png)

### 还有别的吗？

mumu模拟器

**Comment by najuse** [comment]
需要手动点击干员才行

**Comment by MistEO** [comment]
rc1 修了，试试看
