### ISSUE TITLE
蓝叠模拟器国际版adb接口频繁变动且MAA自动识别失败

### ISSUE THREAD

**Issue by SoudayoWwww** [MaaAssistantArknights/MaaAssistantArknights#2223]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [ ] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

重装了蓝叠模拟器国际版，换成了hyper-v版本，之后每次启动模拟器其adb接口每次都会改变，但是MAA的自动识别连接模式都会错误识别到5555端口。可以手动输入新的端口号后正常连接。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9737587/asst.log)

### 截图

![~K 84HFYCI3F`)`HSEY9@CO](https://user-images.githubusercontent.com/52328223/194659121-c1deab9a-2bc1-4326-af7c-a2a784e4eca9.png)
![E5`4{I@L1FI (UXWW()J2R](https://user-images.githubusercontent.com/52328223/194660501-12a17b79-6415-449c-b9b4-f0c5efd438d4.png)
![MFA DRG7((OF4Y_ 8S699~8](https://user-images.githubusercontent.com/52328223/194659150-f101555c-0219-4210-8ab3-594901645695.png)

### 还有别的吗？

![{6KT4O`LHV ~5FSV_((R}7](https://user-images.githubusercontent.com/52328223/194659506-95d4a22e-db85-4ebe-86ef-3baa36e755eb.png)

**Comment by MistEO** [comment]
文档里有 HyperV 版本的设置方法
