### ISSUE TITLE
基建无人机使用和菲亚换心情同时为pre，应当先加速，再换心情

### ISSUE THREAD

**Issue by TangZH-unity3d** [MaaAssistantArknights/MaaAssistantArknights#2224]
### 说说你遇到的问题？
我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

因为巫恋组技能跟随时间，所以我认为都为 pre 应当先加速，再使用无人机，使效益最大化。
目前都为pre时，会先换心情，再使用无人机时，巫恋组就缺了一个人。只能手动加速，或者无人机使用post字段

### 截图
![code](https://user-images.githubusercontent.com/57781584/194678724-d08131a8-c047-4aeb-b931-01fed391b76b.png)
![t](https://user-images.githubusercontent.com/57781584/194678728-3ba9a5b8-5024-467f-babd-7405f4a1e6f8.png)

**Comment by tio-plato** [comment]
感觉这个确实应该更换一下执行顺序，无人机设置为pre的话应当第一顺位执行，目前应该是没有先菲亚梅塔再无人机更优的情况（按照现在逻辑菲亚梅塔换完再无人机房间里直接少一个人）

**Comment by ShiJi001** [comment]
我也遇到了这个问题，希望开发大佬们改进一下。
