### ISSUE TITLE
主线关卡某一幕未完全开启的情况下无法进入自定义关卡

### ISSUE THREAD

**Issue by JesseGreenWhale** [MaaAssistantArknights/MaaAssistantArknights#2226]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在当前状况下，推测MAA并不能在主线关卡某一幕没有完全开启的情况下进入该幕中的具体关卡。
具体说明：本账号关卡并没有完全开启ACT1幻灭的所有关卡，仅停留在7-1，在自定义指定MAA“刷理智”功能中，指定MAA先执行6-11，再执行剩余理智选项。经过实际运行发现，在没有解开ACT1所有关卡之前，MAA会进入到“主线关卡”的“幕间选择界面”，划到最右边，停留，然后执行剩余理智关卡1-7。仔细观看模拟器操作行为，自认为两种指定模式都是基于同样的识别操作逻辑，对比发现，由于1-7所处的ACT0全部关卡已解锁，可以顺利定位到1-7的位置，而6-11所在的ACT1由于没有完全开启，幕中最右边存在多余图标，造成MAA点击最右侧章节以进入具体关卡的模式失效

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9738289/asst.log)
10:53:01 尝试进入6-11关卡，进入到主线界面幕间选择
10:53:34 任务出错，自动退出
10:53:34 进入剩余理智执行任务
10:54:01 成功导向到1-7并打开编队界面
10:54:01 手动停止

### 截图

![Screenshot_2022 10 08_10 46 51 583](https://user-images.githubusercontent.com/85732087/194684488-3482544f-1283-4f4d-a3f0-d009bd7c1a4b.png)
进入自定义关卡6-11前停留的画面
![Screenshot_2022 10 08_10 47 06 132](https://user-images.githubusercontent.com/85732087/194684511-7fd4ccbf-616f-4507-9dc8-917bf7acec6b.png)
进入剩余关卡1-7前停留的画面，接下来可以顺利进入关卡

### 还有别的吗？

WIN11 22H2
蓝叠模拟器国际版 HYPER-V
（另注，同样遇到无法上报企鹅物流的问题，已正确设置ID等操作）

**Comment by ABA2396** [comment]
这个如果要改的话就得把全部章节的图都截一遍了，应该会很麻烦，还是先演习进出下要打的关卡然后用上一次吧）

**Comment by ABA2396** [comment]
讨论了下准备改成划到最左然后往右去找，但是要改的还是挺多

**Comment by JesseGreenWhale** [comment]
> 讨论了下准备改成划到最左然后往右去找，但是要改的还是挺多

感觉确实，如果真的通过视觉识别来直接进关卡，可以想到大佬们的工作量会变得相当大的（毕竟自己选关卡的时候就挺费劲的啦）=͟͟͞͞(꒪ᗜ꒪ ‧̣̥̇)
弱小无知，只能说谢谢各位大佬了(σ≧︎▽︎≦︎)σ。

**Comment by ABA2396** [comment]
新版本改了导航的方式，用小号测了下应该没问题，更新测试版看看还有没有这个问题

**Comment by JesseGreenWhale** [comment]
> 新版本改了导航的方式，用小号测了下应该没问题，更新测试版看看还有没有这个问题

(⊙o⊙)哇，真的改了，等有空立刻试试。谢谢大佬们的辛勤付出，辛苦了૧(●´৺`●)૭

**Comment by ABA2396** [comment]
> > 新版本改了导航的方式，用小号测了下应该没问题，更新测试版看看还有没有这个问题
> 
> (⊙o⊙)哇，真的改了，等有空立刻试试。谢谢大佬们的辛勤付出，辛苦了૧(●´৺`●)૭

可以用了吗？可以的话这个issue就关了
