### ISSUE TITLE
新版本中的252排班只有4个制造站

### ISSUE THREAD

**Issue by charles037** [MaaAssistantArknights/MaaAssistantArknights#2227]
### 说说你遇到的问题？

排班模板里面的252只有4个制造站，正常不是有5个制造站吗，是我的理解有问题吗

**Comment by Zirun-wang** [comment]
没问题，只是252的还没写出来（

**Comment by MistEO** [comment]
> 没问题，只是252的还没写出来（ 排班表生成器的问题建议在这里反馈 https://github.com/Zirun-wang/yituliuFrontEnd/

不对，我也理解错了，他说的应该是 MAA 内置作业里面少了

**Comment by MistEO** [comment]
@545426 link to https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/2147
