### ISSUE TITLE
水月肉鸽 风雨际会卡住

### ISSUE THREAD

**Issue by maidangdang1** [MaaAssistantArknights/MaaAssistantArknights#2233]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽 风雨际会节点被识别成不期而遇 卡在交换藏品那里，提示“您未选择任何收藏品，确定退出吗”
2022-10-08 20:07:32附近

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9739339/asst.zip)

### 还有别的吗？

4.6.0-rc1

**Comment by MistEO** [comment]
`/debug/roguelike` 下有出错的截图，发下康康

**Comment by zoe4477** [comment]
![Snipaste_2022-10-08_22-53-51](https://user-images.githubusercontent.com/38827851/194713615-be33ce41-7f02-4a11-9d96-7b967c29fa8f.jpg)
我也遇到了好几次，一到风雨际会就卡在这个页面

**Comment by maidangdang1** [comment]
![Screenshot_2022 10 08_22 59 33 374](https://user-images.githubusercontent.com/46847241/194713890-92a95067-0c07-4d41-b28f-bb57483ccd54.png)
![Screenshot_2022 10 08_22 59 41 373](https://user-images.githubusercontent.com/46847241/194713895-ead9d3cd-429b-42b3-9bc0-2d8895710716.png)
就是卡在图2这里
