### ISSUE TITLE
自定义基建换班时宿舍填充干员遇到的问题

### ISSUE THREAD

**Issue by Private233** [MaaAssistantArknights/MaaAssistantArknights#2237]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

1、自己改了个宿舍skip字段，用来放鸿雪和迷迭香相关的联动干员。结果maa到这个宿舍的时候先清空了我宿舍内的人然后不选人而结束了。
2、其他宿舍正常使用autofill，maa设置里也勾选了“宿舍空余位置蹭信赖”，在没有人需要休息的时，maa执行宿舍换班填不满人，只在第一个宿舍选了三个人就不再继续。（我还有很多信赖未满干员）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9740517/asst.log)

### 截图

<img width="307" alt="屏幕截图 2022-10-09 082148" src="https://user-images.githubusercontent.com/108540840/194732112-51aff903-d92e-4a3d-9af6-79173bbe6617.png">

**Comment by Private233** [comment]
呜，我不好说了。现在又试了一次，skip的问题没有了，可能时早上起来用的时候没有及时更新（？
蹭信赖的问题还是有。还有足够人需要休息的时候，休息的干员都是正常放置的。休息的干员少了就有问题。每个宿舍都只会点三个干员，（我最后剩四个干员要休息硬生生给我点掉一个）甚至会点到异格干员导致三个干员变成两个

**Comment by Private233** [comment]
在所有干员都休息完之后又试了一遍，依旧是第一个宿舍选了三个人就结束，而且不进行后续的宿舍
![QQ截图20221009183257](https://user-images.githubusercontent.com/108540840/194751962-ed43c2bb-4a97-453f-85b1-12ea56702eba.png)

**Comment by Private233** [comment]
不是，还有很多干员没有满信赖

**Comment by Private233** [comment]
蹭信赖的问题依旧（

**Comment by Private233** [comment]
> 只要把sort改为true，也就是按顺序入驻就能避免autofill清空人的问题

好像这个也不对，还是会把人全部清掉，还是自己改skip吧

**Comment by MistEO** [comment]
修了
