### ISSUE TITLE
傀影肉鸽无法进入，干员无法按要求选择

### ISSUE THREAD

**Issue by Taky358057881** [MaaAssistantArknights/MaaAssistantArknights#2238]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

选择傀影肉鸽会一直进到水月肉鸽然后退出到主界面，一直循环。手动点击傀影肉鸽依然无法按要求选择开局干员

### 日志文件

[Uploading asst.log…]()

### 还有别的吗？

使用MuMu模拟器

**Comment by Taky358057881** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9740624/asst.log)

**Comment by ABA2396** [comment]
选了傀影肉鸽之后在集成战略页面把傀影pin到终端试试
