### ISSUE TITLE
无法从主界面跳转到傀影肉鸽

### ISSUE THREAD

**Issue by satgo1546** [MaaAssistantArknights/MaaAssistantArknights#2239]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

集成战略主题菜单中，现在初始选项是水月主题。即使在MAA设置中选择了傀影主题，机器仍然只会直接点击“进入主题”按钮，结果进去发现是水月，又退回到主界面，不断循环，无法进入傀影主题。

在游戏中手动打开傀影主题后，自动肉鸽功能正常。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9740614/asst.log)

### 还有别的吗？

Windows 11, BlueStacks Hyper-V, 1280×720
~~看来没有大懒鬼像我一样还没刷完傀影肉鸽的~~

**Comment by satgo1546** [comment]
Duplicate of #2238

啊这，刚提交完就发现有人5分钟前提交了一个同样的issue，慢人一步了属于是

**Comment by ABA2396** [comment]
选了傀影肉鸽之后在集成战略页面把傀影pin到终端试试

**Comment by satgo1546** [comment]
亲测可行👍
