### ISSUE TITLE
使用wsa挂肉鸽时闪退

### ISSUE THREAD

**Issue by SherkeyXD** [MaaAssistantArknights/MaaAssistantArknights#2241]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

大概运行半个小时（以内）maa会崩溃

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9740656/asst.log)
10:06分启动游戏，10:36分来看的时候maa已经闪退了，之后又尝试重启几次，没有效果

### 还有别的吗？

wsa 版本 2208
maa 版本 4.6.1-alpha1
（4.6.0版本一样有问题）

**Comment by SherkeyXD** [comment]
补充：观察到任务栏上图标在跳动，具体原因不明

**Comment by MistEO** [comment]
初步定位了一下，并加了一些日志，帮忙试试这个帮忙是否正常了 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/3213724577 （大约等十分钟就出来了）

**Comment by SherkeyXD** [comment]
> 初步定位了一下，并加了一些日志，帮忙试试这个版本是否正常了 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/3213724577 （大约等十分钟就出来了）

坚持的更久了，之前大概到第三层中间会闪退，现在能打到boss战了
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9741422/asst.log)

**Comment by MistEO** [comment]
不好意思还是没搞清楚崩在哪的，目前看和截图有关系，和第几层没啥关系。再帮忙试一下这个包 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/3214564262 （也是大概过个十分钟就出来了）

**Comment by MistEO** [comment]
上面这个不用试了，有眉目了，试试这个包，应该不会崩了（希望吧 orz 
https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/3214627543

**Comment by SherkeyXD** [comment]
注意到`[ERR][Pxd54][Tx160] home recognition error`反复出现，是否和这个有关呢？

> 上面这个不用试了，有眉目了，试试这个包，应该不会崩了（希望吧 orz https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/3214627543

明天跑，宿舍断电了（
以及看到反复出现一条`[ERR][Px8f4][Tx3350] home recognition error`，与这个有关吗？

**Comment by MistEO** [comment]
ok 感谢，另外看下 C:\Users\<用户名>\AppData\Local\CrashDumps 这里面有崩溃相关的 dump 文件么，有的话也帮忙发一下（这里面可能涉及电脑上的一些数据隐私，方便的话可以发我邮箱 mistereo@hotmail.com

**Comment by SherkeyXD** [comment]
> ok 感谢，另外看下 `C:\Users\<用户名>\AppData\Local\CrashDumps` 这里面有崩溃相关的 dump 文件么，有的话也帮忙发一下（这里面可能涉及电脑上的一些数据隐私，方便的话可以发我邮箱 [mistereo@hotmail.com](mailto:mistereo@hotmail.com)

中午测试版本  [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9743452/asst.log)
crashdump发邮箱了

**Comment by SherkeyXD** [comment]
又测了一次 [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9743550/asst.log)
崩溃后任务栏会变成这个样子
<img width="343" alt="image" src="https://user-images.githubusercontent.com/57581480/194804730-6c9f7a74-7b27-4f7d-8259-fde5716f13bd.png">

**Comment by MistEO** [comment]
今天发的两次日志，崩在了另一个地方，和 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2217 这个很像。

没有崩在昨天那里，挺奇怪的，不知道是真的修掉了还是单纯的没复现。

拒信不知道为啥 orz，换个邮箱试试 aysyxx53@hotmail.com

**Comment by SherkeyXD** [comment]
> 今天发的两次日志，崩在了另一个地方，和 #2217 这个很像。
> 
> 没有崩在昨天那里，挺奇怪的，不知道是真的修掉了还是单纯的没复现。
> 
> 拒信不知道为啥 orz，换个邮箱试试 [aysyxx53@hotmail.com](mailto:aysyxx53@hotmail.com)

dmp发过去了（顺便确认了被拒信是因为压缩成了7z，换zip就好了

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
