### ISSUE TITLE
v4.6.0 Win10 资源管理器, 大图标和超大图标下.exe的icon依旧为旧版

### ISSUE THREAD

**Issue by IchiroArisugawa** [MaaAssistantArknights/MaaAssistantArknights#2243]
### 说说你遇到的问题？

![image](https://user-images.githubusercontent.com/38690785/194738329-64f960d7-ea3b-492f-b4ca-9d1446566734.png)
![image](https://user-images.githubusercontent.com/38690785/194738332-022fc3c1-31ab-4a71-8b30-3c4f883b9b45.png)

**Comment by MistEO** [comment]
清一下你电脑的缩略图缓存

**Comment by satgo1546** [comment]
超大图标正常
![image](https://user-images.githubusercontent.com/5250054/194755997-1d090d96-a5bf-4784-8a9a-f776551fd10b.png)
可爱滴捏🥰
