### ISSUE TITLE
自定义基建配置的skip功能未能正常运行 & 干员进驻出现问题

### ISSUE THREAD

**Issue by DemiurgeZ** [MaaAssistantArknights/MaaAssistantArknights#2244]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

问题一：在自定义基建配置中，设置其中一部分设施换班时skip，但实际情况为不用换班的3号制造站被换上了本应在4号制造站上班的干员组，而4号制造站为空（截图如下）

3号制造站：
![Screenshot_2022 10 09_09 19 44 519](https://user-images.githubusercontent.com/44410173/194739051-e42cde01-9ae5-4819-9c62-c5aebe043ee8.png)
4号制造站：
![Screenshot_2022 10 09_09 19 11 286](https://user-images.githubusercontent.com/44410173/194739057-f07ae4ac-4ce2-4802-b0d2-2f554d1f7799.png)

问题二：换班时，中枢换班干员未能正常进驻，五人中只进驻了三人，夕和令没有进驻（截图如下）
![Screenshot_2022 10 09_09 19 01 119](https://user-images.githubusercontent.com/44410173/194739091-956100d4-8906-43cf-973e-8d8293c54ab2.png)

### 日志文件

日志文件：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9740787/asst.log)
GUI日志：
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9740788/gui.log)
自定义换班配置文件：
[custom_infrast.json.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9740789/custom_infrast.json.txt)

问题出现在9:00AM换A+B组上班时

### 截图

见问题描述

### 还有别的吗？

MAA: v4.6.0
模拟器：蓝叠国际版Hyper-V 5.9.300.1014 N64
操作系统： Win10 22H2

**Comment by MistEO** [comment]
和会客室 or 办公室没有关系，压根就没进去基建。从日志看是卡在某个界面不动了，MAA 尝试了很多种场景，但什么都识别不到，你还记得自己过来看的时候，游戏停在哪个界面么？

如果你是笔记本，我猜可能是进入了某个省电模式，模拟器窗口直接不渲染了，或者降分辨率了。至于开录屏就能执行，可能是因为录屏被判断为活跃软件，不进入省电模式（打个比方看视频几个小时鼠标不动也不会息屏，平时可能十分钟就息屏了一样）

**Comment by MistEO** [comment]
卡在线索交流界面和你前面发的不是同一个问你，可以看到界面上显示的日志也不一样。

不过卡在线索交流这个问题 emm
