### ISSUE TITLE
会客室有参数可以跳过线索选择和开party吗？

### ISSUE THREAD

**Issue by fearlessxjdx** [MaaAssistantArknights/MaaAssistantArknights#2245]
### 说说你遇到的问题？

线索的选择和送出想手动进行，但是我没能找到参数可以只放干员，不做线索相关操作。

**Comment by MigdalBavel** [comment]
附议，同样需要这样的选项。有时候出于各种各样的原因，线索操作有自己另外的计划的，但是现在换班强制操作线索经常就冲突了。
而且观察下来，在进行交流选择线索的时候，好像也不会识别线索是接收来的还是自己的，把自己的挂上去交流也会造成损失。

**Comment by lindsayee** [comment]
附议，比如信用店已经没有好买的，想等第二天再收party。
目前只能手动去掉会客室的选项，单独把在会客室的干员换掉，让MAA处理其他换班。
如果能有这样的选项就好啦。

**Comment by WolfCanglong** [comment]
十分需要这个 其他的实在不行自定义都能解决 就是这个自动开p关不掉

**Comment by BiologyHazard** [comment]
同样需要只换干员不收线索不开party的选项，希望开发者关注
