### ISSUE TITLE
关卡选择都是龙门币却打了上一次执行

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaAssistantArknights#2246]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

选的龙门币莫名其妙打了1-7
我你也没1-7啊

### 日志文件

[Uploading asst.log…]()

### 截图

![image](https://user-images.githubusercontent.com/33809511/194742422-b2d01dea-dda6-4ea2-934f-83a483834dee.png)

**Comment by Shawnsdaddy** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9740921/asst.log)

**Comment by MistEO** [comment]
@zzyyyl 来瞅瞅是不是你的锅！

**Comment by zzyyyl** [comment]
怎么你resource没变的

**Comment by Shawnsdaddy** [comment]
> 

啥resource?不应该和软件自动更新嘛
