### ISSUE TITLE
希望宿舍的“自动填充”能填充信赖满、心情满的干员

### ISSUE THREAD

**Issue by Zebartin** [MaaAssistantArknights/MaaAssistantArknights#2247]
### 说说你遇到的问题？

迷迭香的基建技能是：

1. 进驻制造站时，宿舍内每有1名干员则[感知信息](https://prts.wiki/w/%E6%9C%AF%E8%AF%AD%E9%87%8A%E4%B9%89)+1，同时每1点[感知信息](https://prts.wiki/w/%E6%9C%AF%E8%AF%AD%E9%87%8A%E4%B9%89)转化为1点[思维链环](https://prts.wiki/w/%E6%9C%AF%E8%AF%AD%E9%87%8A%E4%B9%89)
2. 进驻制造站时，每1点[思维链环](https://prts.wiki/w/%E6%9C%AF%E8%AF%AD%E9%87%8A%E4%B9%89)+1%生产力

因此在使用迷迭香时，需要尽可能把宿舍塞满，并尽可能提供更多思维链环。后者好解决，手动配置车尔尼和爱丽丝到宿舍里就可以，但我似乎没能找到前者的配置方法，使用autofill也只能填充心情不满或者蹭信赖的干员。

### 有什么好的想法？

希望改进autofill的逻辑，把无关干员也填充进去，尽可能塞满宿舍

**Comment by ABA2396** [comment]
填充蹭信赖的干员不就填满了吗？

**Comment by Zebartin** [comment]
> 填充蹭信赖的干员不就填满了吗？

个人是只有3个信赖不满的人，很容易出现填不满的情况……

**Comment by auroralwy** [comment]
我也有这个问题...只有三个新干员信赖不满，放信赖的话每次只有那三个会放进去。
取消放信赖干员的话每次换班基建也是换不满的。
有没有自动填充满宿舍的选项？还是说我需要把心情阈值设置成100%？

**Comment by Zebartin** [comment]
> 另外我是设置autofill的，可以设置一些备选实现吗？比如夜莺流明这种宿舍长之类的

目前的话作为原问题的临时解决方式，我是在自定义基建json文件里写死了一部分人常驻在宿舍里，留一些空位来autofill。
宿舍长这种的话也可以这么做，比如
```json
"dormitory":[
	{
		"operators":[
			"流明",
			"闪灵"
		],
		"autofill":true
	}
]
```
具体可以参考[基建排班协议](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/3.6-%E5%9F%BA%E5%BB%BA%E6%8E%92%E7%8F%AD%E5%8D%8F%E8%AE%AE.md)

**Comment by auroralwy** [comment]
> > 另外我是设置autofill的，可以设置一些备选实现吗？比如夜莺流明这种宿舍长之类的
> 
> 目前的话作为原问题的临时解决方式，我是在自定义基建json文件里写死了一部分人常驻在宿舍里，留一些空位来autofill。 宿舍长这种的话也可以这么做，比如
> 
> ```json
> "dormitory":[
> 	{
> 		"operators":[
> 			"流明",
> 			"闪灵"
> 		],
> 		"autofill":true
> 	}
> ]
> ```
> 
> 具体可以参考[基建排班协议](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/3.6-%E5%9F%BA%E5%BB%BA%E6%8E%92%E7%8F%AD%E5%8D%8F%E8%AE%AE.md)

那看来还是得重新写一下，当时嫌麻烦就没这么写了（我一天三换每个宿舍这么搞实在是不太行）不知道阈值调100%能不能自动填充满心情干员...

**Comment by ABA2396** [comment]
我记得之前蹭信赖选项满信赖也是会填进去的，是后来改了么，不过会不会存在填人的时候把肥鸭塞进宿舍导致下一次换心情失效的问题

**Comment by ShiJi001** [comment]
我也是遇到了这个问题，很难受。

**Comment by MistEO** [comment]
修了
