### ISSUE TITLE
战斗中掉线导致卡死

### ISSUE THREAD

**Issue by WitherLing** [MaaAssistantArknights/MaaAssistantArknights#2250]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

战斗中掉线导致卡死,无操作

### 日志文件

[Uploading asst (4).zip…]()

### 截图

![Screenshot_20221009-173557](https://user-images.githubusercontent.com/74227748/194749537-28657265-7580-4df2-8475-cc35b28a62a0.png)

### 还有别的吗？

夜神模拟器

**Comment by WitherLing** [comment]
[asst (4).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9741236/asst.4.zip)

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
