### ISSUE TITLE
使用官方自带的243 3换策略，絮雨没有正常的被换上岗

### ISSUE THREAD

**Issue by lie5860** [MaaAssistantArknights/MaaAssistantArknights#2252]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

之前一直是用默认的基建功能，看到这个顶配配置感觉挺心动的吧。把所有角色都拉到对于精英化阶段后开始尝试使用定时+自定义基建功能beta功能尝试还原极限配置下的基建收益， 根据自身机子运行情况（晚上23.45-早上8点）都处于开机状态，仅在官方的配置文件里增加定时配置。
[极限243.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9741361/243.zip)

从昨晚23点开始挂到今晚8点，发现每一次的运行结果好像都不是很准确。例如今晚8点完成任务后发现办公室没人上班。。。宿舍的人好像也不太对劲？还是有一些干员还需要休息的 但是没放进去。

![QQ截图20221009185354](https://user-images.githubusercontent.com/30894657/194752831-304a3cb5-240e-4d13-9ca8-842b8a28b0e8.png)
![QQ截图20221009185515](https://user-images.githubusercontent.com/30894657/194752883-03e4ffdb-fb3b-4132-abbe-60374dd1ba93.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9741355/asst.log)

### 截图

一些与之相关的设置。
![QQ截图20221009184354](https://user-images.githubusercontent.com/30894657/194752417-9c68644c-24cf-4f5c-8f8b-c6076b7511da.png)
![QQ截图20221009184405](https://user-images.githubusercontent.com/30894657/194752423-8c10b12f-c975-4680-a5be-1ce63382bd37.png)
![QQ截图20221009185031](https://user-images.githubusercontent.com/30894657/194752667-62ace28b-0fea-458d-8cb3-2a0a07107e34.png)

**Comment by lie5860** [comment]
好的 我去掉试一下 我当前版本是v4.6.1-a1，应该没更新的了。

**Comment by lie5860** [comment]
应该是游戏的问题，可能是内存满了导致游戏出现了一些bug，即使是自己去操作也无法选中对应干员，换了台设备就好了。有一个小问题。最新版本的配置为什么会先把两个干员送去宿舍。。但是后面又把这个干员 巫恋 送到别的设备上去。。
![QQ截图20221009195820](https://user-images.githubusercontent.com/30894657/194755822-945969af-63df-472d-9e47-a1d738b2f1c2.png)

**Comment by MistEO** [comment]
你看看菲亚梅塔的基建技能就知道了_(:з」∠)_

如果是设备的问题，issue 我就关掉咯

**Comment by lie5860** [comment]
> 你看看菲亚梅塔的基建技能就知道了_(:з」∠)_
> 
> 如果是设备的问题，issue 我就关掉咯

好嘞~感谢大佬~
