### ISSUE TITLE
雷电模拟器连接错误

### ISSUE THREAD

**Issue by curecc** [MaaAssistantArknights/MaaAssistantArknights#2253]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [ ] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

![image](https://user-images.githubusercontent.com/69534712/194758834-60543cd3-8b18-479f-84ab-fc61ed19880b.png)

无法连接雷电模拟器 用adb是可以命令模拟器的

### 日志文件

[Uploading asst.log…]()

### 截图

![image](https://user-images.githubusercontent.com/69534712/194758944-30cec8c5-c3a2-461a-9c67-4b2e9068d827.png)

### 还有别的吗？

逍遥等其他模拟器是可以正常连接

**Comment by MistEO** [comment]
MAA 不支持雷电，请更换模拟器

**Comment by MistEO** [comment]
之前文档可能说的不够明确，重新补充了一下

![image](https://user-images.githubusercontent.com/18511905/194762727-2a93a5ad-2195-4f62-bb33-defcc14d27c0.png)

**Comment by bingyunhe** [comment]
设置里连接设置的自动连接检测打勾然后再点开始试试

**Comment by bingyunhe** [comment]
> > 设置里连接设置的自动连接检测打勾然后再点开始试试
> 
> 雷电的端口号是会变的，这样的话可能每次启动都要检测一次

之前这样可以的，上周开始彻底不行了。
我已经改用夜神了
