### ISSUE TITLE
挂水月肉鸽导致模拟器内存泄漏

### ISSUE THREAD

**Issue by 6-9FC81** [MaaAssistantArknights/MaaAssistantArknights#2254]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

正常使用模拟器（不开maa）、跑maa其他任务时一切正常
挂水月肉鸽时模拟器内存占用越来越高，最后maa闪退（未测试傀影）
![微信图片_20221009213322](https://user-images.githubusercontent.com/48641295/194759825-1aff936f-6d19-40f3-bbe9-d0728fd670a0.jpg)

### 日志文件

[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9741682/log.zip)

### 还有别的吗？

出问题的时间段大概在8点10分到8点20，雷电模拟器，win10: 

![微信图片_20221009205859](https://user-images.githubusercontent.com/48641295/194760012-950cc183-7e92-4014-8f02-88879a596a7f.png)

**Comment by MistEO** [comment]
模拟器占用高那就是模拟器的锅啊_(:з」∠)_

**Comment by MistEO** [comment]
补充了文档

![image](https://user-images.githubusercontent.com/18511905/194762766-2eaf3b77-e0bb-4e1f-afc4-b2773de6c540.png)

**Comment by 6-9FC81** [comment]
换了蓝叠模拟器，一切正常，感谢回复
