### ISSUE TITLE
修改roguelike_copilot文件代码未生效

### ISSUE THREAD

**Issue by Mutsuki-XJ** [MaaAssistantArknights/MaaAssistantArknights#2257]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

自己修改了roguelike_copilot想改变一下自动肉鸽的关卡部署，但是代码未能生效，发现干员部署按照先锋-重装-近卫-医疗-辅助的顺序部署，求助是什么原因，要怎么改代码

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9742295/asst.log)
最近一场战斗
[roguelike_copilot.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9742299/roguelike_copilot.txt)
这是我修改过后的文件

**Comment by MistEO** [comment]
@DavidWang19 有空瞅瞅

**Comment by DavidWang19** [comment]
设计如此，先用近战阻挡在三个replacement_home的位置，然后逐个放医疗，如果医疗没了或者都覆盖到了，才开始用正常逻辑部署

**Comment by DavidWang19** [comment]
如果你想调整的话，可以删掉俩replacement_home
