### ISSUE TITLE
无法识别“数据已更新，即将同步”的问题

### ISSUE THREAD

**Issue by LeviZhang1996** [MaaAssistantArknights/MaaAssistantArknights#2259]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

当每日4点后数据更新时，如果不是从启动明日方舟进入游戏，而是本身在游戏中，则识别不出来，会陷入无法唤醒而持续游戏掉线重新连接的死循环。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9742931/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/83460341/194788019-83c24836-66a5-42f9-a82d-71f7b6b68281.png)
![image](https://user-images.githubusercontent.com/83460341/194788024-0007642a-bd7a-445c-9caf-60d6d64ab66c.png)

**Comment by MistEO** [comment]
@zzyyyl 这个现在支持了么？

**Comment by ntgmc** [comment]
该功能已经修复，请更新到最新版，若有问题请重发issue，感谢您的反馈！
This function has been repaired. Please update to the latest version. If you have any problems, please re issue. Thank you for your feedback!
