### ISSUE TITLE
想问问软件占用怎么设置可以低一点

### ISSUE THREAD

**Issue by batjoker** [MaaAssistantArknights/MaaAssistantArknights#226]
附log的这台电脑只要开一会就会卡死强退，但是模拟器还可以接着用没崩溃（单用模拟器本身是可以挂一整天的
症状大约表现为挂了一会软件就自己没了需要重新运行，偶尔会把整台电脑带崩需要重启
另一台配置稍好的电脑风扇狂转，软件的CPU和内存占用看起来似乎比模拟器本体都高不少……

请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8065839/asst.log)

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ

**Comment by MistEO** [comment]
有这么吃性能么_(:з」∠)_我自己几台电脑大约都只相当于 1/2 个模拟器的占用，你是使用了 noavx 的版本？

另外看你日志后面好像一直连接错误，这个是雷电的问题，可以换个模拟器试试
