### ISSUE TITLE
自定义基建中菲亚梅塔基建技能可能无法触发

### ISSUE THREAD

**Issue by leosum1030** [MaaAssistantArknights/MaaAssistantArknights#2260]
### 说说你遇到的问题？

菲亚梅塔换心情操作是在一号宿舍进行的，maa会把待恢复心情的干员放在宿舍一号位，菲亚梅塔放在二号位。但如果换班前菲亚梅塔本身就在一号宿舍的二号位上，那么此次换心情操作中菲亚梅塔并不会触发其基建技能，因为菲亚梅塔在宿舍的位置没有变，没有触发“进驻宿舍”这一前提条件，导致换心情失败。
上述情况是有很大概率发生的，因为只要前一次换班结束后菲亚梅塔的心情值在所有干员中排倒数第二，就会被安排在一号宿舍的二号位休息，导致下一次换班时菲亚梅塔基建技能无法触发。

### 有什么好的想法？

建议用菲亚梅塔换心情时判断菲亚梅塔的位置，或者干脆先清空宿舍，再换心情，这样能保证换心情成功。

**Comment by MistEO** [comment]
还有这种问题 orz

**Comment by leosum1030** [comment]
> 还有这种问题 orz

是的，机制类似制造站和贸易站的暖机干员，只要在设施内的位置不变，就不会清空暖机进度，反之视为重新入驻设施，要重新暖机
