### ISSUE TITLE
水月肉鸽-bug反馈-隐秘温床

### ISSUE THREAD

**Issue by SzkEC** [MaaAssistantArknights/MaaAssistantArknights#2262]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽第四层 不期而遇-隐秘温床 选择第一个选项消耗钥匙进入上传图片所在选择支时无法识别，会直接退出并放弃探索

### 日志文件

[Uploading astbkp.txt…]()

### 截图

![Uploading 屏幕截图 2022-10-10 161405.png…]()

### 还有别的吗？

操作系统 win10 21H2 19044.2006
模拟器 nox

**Comment by SzkEC** [comment]
[asstbak.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9744329/asstbak.txt)
log文件过大无法上传，所以截取了出现时间-2h起的log，出现时间为16:12:25

**Comment by MistEO** [comment]
debug/roguelike/ 下的图片也打包发下看看

**Comment by MistEO** [comment]
看起来不太好改，放到下个版本再说了（

**Comment by zzz1324** [comment]
同上，但问题好像不仅出现在第4层，感觉是这个事件的原因
![QQ截图20221013140543](https://user-images.githubusercontent.com/115688705/195516706-439171a9-7891-4f08-9c3c-10cdd10f2d4b.png)
![QQ截图20221013140551](https://user-images.githubusercontent.com/115688705/195516713-f93d8a7e-23e6-47a4-882a-2c53a165a7cb.png)
