### ISSUE TITLE
肉鸽流程优化

### ISSUE THREAD

**Issue by DeparturesNeko** [MaaAssistantArknights/MaaAssistantArknights#2265]
### 说说你遇到的问题？

肉鸽结束后有可能会出现新藏品，导致整个肉鸽进程结束。

### 有什么好的想法？

每次肉鸽结束后增加文字识别“获取新藏品”这一操作，并跳过该页面。

**Comment by MistEO** [comment]
这是 bug，来个 bug 反馈发下日志和图吧~
