### ISSUE TITLE
希望加入阻止休眠的功能

### ISSUE THREAD

**Issue by MisterCoBen** [MaaAssistantArknights/MaaAssistantArknights#2266]
### 说说你遇到的问题？

经常在吃饭时使用MAA，但经常刷到一半电脑自动休眠，希望能加入刷图时阻止休眠的按钮

**Comment by ntgmc** [comment]
各种模拟器可以禁用系统/屏幕休眠

**Comment by pingplug** [comment]
@ntgmc 

> 各种模拟器可以禁用系统/屏幕休眠

经测试，夜神模拟器的禁用系统休眠功能在win11中无法使用（我是因为蓝叠在A卡系统中游戏卡顿用的夜神）。鉴于不同模拟器的类似功能可能出现bug，还是建议MAA加入此功能。
