### ISSUE TITLE
增加明日关卡开放显示

### ISSUE THREAD

**Issue by Genicur** [MaaAssistantArknights/MaaAssistantArknights#2267]
### 说说你遇到的问题？

每天的关卡开放都得去prts看挺麻烦的（

### 有什么好的想法？

如果maa能显示的话刷理智任务也更好分配

**Comment by zzyyyl** [comment]
草？今天的事情今天看不就完了，还管明天干嘛

**Comment by Genicur** [comment]
> 

一天三换的话 有一次在半夜（

**Comment by ABA2396** [comment]
> > 草？今天的事情今天看不就完了，还管明天干嘛
> 
> 一天三换的话 有一次在半夜（

这不是有备选关卡的功能么，一共三个关卡选择还不够用吗
