### ISSUE TITLE
有关于maa连接模拟器一直断开重连的问题

### ISSUE THREAD

**Issue by ldslucky77** [MaaAssistantArknights/MaaAssistantArknights#2268]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

模拟器一直断开连接，然后重连，我试过重启电脑，重新下载，换模拟器，国际服蓝叠模拟器也不行，然后时不时出现未知错误

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9746800/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/115480487/194888441-6926679e-fe2f-4115-8c55-bdcacda353d6.png)
![image](https://user-images.githubusercontent.com/115480487/194888533-ccb08698-afc4-4ad8-8126-a9a827c025f2.png)
![image](https://user-images.githubusercontent.com/115480487/194888584-95fee9c1-30ac-4e7f-b66d-0538094180e7.png)

### 还有别的吗？

![image](https://user-images.githubusercontent.com/115480487/194888732-934353d6-e31d-41d4-a29b-77aa12eb0b03.png)

**Comment by MistEO** [comment]
MAA 连接模拟器依赖的是 adb，看日志就是 adb 报错了，不知道为啥。这种问题靠 MAA 不太好解决，一般只能换个模拟器，或者自己下载个 adb 试试
