### ISSUE TITLE
会客室只进行了换干员, 但没有领线索、送线索等

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaAssistantArknights#2273]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我使用的是自定义基建排班, 然后maa进会客室点了两下线索五, 换了下班就跑了()

(嘶, 看好友送的线索好像已经卡了两天了23333)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9749755/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/72590023/194966534-67fe2382-8db0-4004-8b1d-b71d58c6a5c0.png)

可以稳定复现: (因为上传大小限制, 加了点倍速)

https://user-images.githubusercontent.com/72590023/194967362-72800a7a-6845-434d-b4b2-255e5216a316.mp4

### 还有别的吗？

不如开一个线索数达到x就开始送线索的选项, 这样就再也不会卡线索啦()

**Comment by one-pyy** [comment]
不如开一个线索数达到x就开始送线索的选项, 这样就再也不会卡线索啦()

**Comment by MistEO** [comment]
锅 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/2178
