### ISSUE TITLE
自动启动时遇到验证码

### ISSUE THREAD

**Issue by ZlCr** [MaaAssistantArknights/MaaAssistantArknights#2275]
### 说说你遇到的问题？

自动启动时遇到验证码，会重复尝试启动

### 有什么好的想法？

希望遇到验证码会终止并弹出通知提醒

### 其他内容

![image](https://user-images.githubusercontent.com/76816179/194994867-9b9df85d-1904-41b4-b5c6-6b6be066c7a8.png)
视频 https://www.bilibili.com/video/BV1cR4y1R7ei/

**Comment by MistEO** [comment]
无解

这个是网络异常才会出的
