### ISSUE TITLE
水月肉鸽 蔓延 地图坐标错误

### ISSUE THREAD

**Issue by lyslys2019** [MaaAssistantArknights/MaaAssistantArknights#2277]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

坐标错位了，干员大部分放不上去

### 日志文件

2022-10-10 20:13:16.361
[Uploading asst.zip…]()

### 截图

![Uploading 蔓延.png…]()

### 还有别的吗？

mumu模拟器
B服

**Comment by lyslys2019** [comment]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9752123/asst.zip)
![蔓延](https://user-images.githubusercontent.com/53963644/195022065-4b74fa98-634f-44f6-b6c7-fbfdcf542e5e.png)

**Comment by MistEO** [comment]
草，主线 `1-2` 也叫 `蔓延`，跑成那边的图了
