### ISSUE TITLE
MAA闪退问题，error: device '127.0.0.1:XXXX' not found

### ISSUE THREAD

**Issue by 134820134820** [MaaAssistantArknights/MaaAssistantArknights#2283]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

MAA闪退问题
次数还挺多的。。。一个号一晚上闪了三次
自己看了眼日志,基本上都是会突然端口not found？然后就报错了
能否先让maa在遇到此问题时尝试重试而不是直接error。。。这放着1-7施工到一半就突然挂了，很难受

### 日志文件

[asst-第一次.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9755314/asst-.log)
[asst-第二次.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9755315/asst-.log)
[gui-新版本好像能传gui的log了？.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9755325/gui-.gui.log.log)

### 还有别的吗？

蓝叠国际版，好像在尝试多开时会出现的更加频繁（特别是新的一个刚刚打开时），但一个也会，主要是在刷某一关（1-7为首）或者换基建换到一半时（有可能是因为就这玩意耗时长所以看起来出现的更多）。
另外还有一次闪退，因为端口不能复用给换了一个导致找不到端口导致的？那次日志一下子没找到就先不开问题了

**Comment by MistEO** [comment]
崩溃的问题修过了
