### ISSUE TITLE
关于使用自动肉鸽时正常运行后突然闪退的问题

### ISSUE THREAD

**Issue by Endarmen** [MaaAssistantArknights/MaaAssistantArknights#2286]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

           反正就是非常的神奇，有时候完整的打一轮肉鸽就闪退（程序界面消失，任务管理器查无此人），有时候打了好久才闪退，运行库和环境变量完整，在之前几个版本不会遇上这个问题。                                                                                                                        
           更新之后无论是测试版，正式版，下载了好几遍，把配置文件删除，安装其他路径，重新安装模拟器无济于事，关于闪退的常见问题都已经尝试，未发现和解决问题，其他的所有功能都没问题。
           闪退前还帮忙暂停，而且大多数都出现在关卡一开始，没有怪物出现，没有放置干员的情况，过载了吗？           
           我注意到任务管理器中有关该软件的进程反复蹦迪，有时候会出现一个cmd程序，有时候整个进程消失，有时候出现两个，不知有没有关系

### 日志文件

国庆过后就有这个情况，期间更新了好几次，没有改善

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9756615/asst.log)

### 截图

一般会闪退在关卡开始的时候，下一个干员（能天使）发现没有费用，没脸看就闪退（？）
![5L3WH QBLI{PCUSB{Y(F{MF](https://user-images.githubusercontent.com/112938307/195113015-46889a62-1ca4-497d-a3e6-0e6a36847d80.png)
都是这个状况，没有打着打着中途退出的情况，只有关卡开始就闪退的情况

### 还有别的吗？

蓝叠模拟器，win11，i5 3050，参考资料都是你们的常见问题

**Comment by sur42tur** [comment]
我也是，每次走到这关maa的程序都会关闭，而且挺频繁的，昨晚偶尔看一眼模拟器看看打的怎么样了，就发现maa它走到了第五层（具体第几层不记得了，反正层数很高）的这一关，就想看看maa打的怎么样，刚好就进了这关，结果它识别就出错了，地面干员一直往高台托，高台干员一直往地面放，结果放半天漏了一堆怪都放不出一个干员。就在刚刚我看完电锯人瞄一眼模拟器发现在这关暂停不动了，后台maa也消失了

**Comment by MistEO** [comment]
如果只有 `蔓延` 这关这样的话， 这个问题已经修复了 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2277

**Comment by Endarmen** [comment]
不止，有一些关卡还是会的，包括一些傀影的肉鸽和水月的肉鸽，每次出现的地方都不太一样，今天我就又找到一个，我觉得可能是其他的问题。
![3CY7SVONV@YPB3WEHP{TALU](https://user-images.githubusercontent.com/112938307/195605924-ede42481-820c-45c3-b5aa-7810a50a8baf.png)

**Comment by Endarmen** [comment]
不止，有一些关卡还是会的，包括一些傀影的肉鸽和水月的肉鸽，每次出现的地方都不太一样，今天我就又找到一个，我觉得可能是其他的问题。
 ![3CY7SVONV@YPB3WEHP{TALU](https://user-images.githubusercontent.com/112938307/195606359-d411d800-a7b0-419e-b8fa-c9e61c245197.png)

**Comment by Endarmen** [comment]
今天又找到一个，嘿
![I1BX9W3REVAM EUZ1L4D1ZW](https://user-images.githubusercontent.com/112938307/195791203-725de4a8-b93f-429a-92d1-a3daa4f3236f.png)

**Comment by zzyyyl** [comment]
这些关卡是进去必闪退，还是有概率闪退？

**Comment by Endarmen** [comment]
我之前是看着MAA顺利打过这几关的，这几次闪退的话，我猜是有概率闪退而不是特定关卡闪退

**Comment by Endarmen** [comment]
我之前是看着MAA顺利打过这几关的，这几次闪退的话，我猜是有概率闪退而不是特定关卡闪退
等我多弄点实验数据，这东西出现的频率蛮高的

**Comment by Endarmen** [comment]
哦豁，真是有概率的，我再次遇到这一关是正常的
![3（正常）](https://user-images.githubusercontent.com/112938307/195815118-a8d4ab0f-bfed-40ff-afcf-3ea817587370.png)

**Comment by Endarmen** [comment]
我找到到了可能解决这一问题的方法：
win11更新后（其他版本不知道啊）会有一个hyper-v的功能，这个功能是win11自带的虚拟化技术，蓝叠模拟器因为这个功能的出现，需要重新安装支持该虚拟化的版本或者关闭该功能，我尝试了安装支持该功能的蓝叠模拟器，使用maa的时候会闪退。前几日我因为vmware的原因关闭了hyper-v功能（可以在windows功能找到，假如windows功能里面不存在这个选项，可能需要利用cmd关闭且要关闭内核隔离），目前没有再出现maa闪退的问题，可能和hyper-v或者内核隔离有关（关闭内核隔离风险请看百度）。希望对你们解决这个问题有所帮助，找出问题源头写进常见问题就更好了（笑）

另外，有些肉鸽关卡的运行逻辑有些问题，我将会附上图片（此为最新版本），会直接放置在四个门处，忽略了中间
![这关的逻辑需要改进](https://user-images.githubusercontent.com/112938307/196843788-ef52f532-b0b2-4fb4-bad3-8abbbaacee0d.png)

**Comment by MistEO** [comment]
是因为有能天使，太红了被当成正在 cd 干员了，触发了一个错误的逻辑，这个问题修过了
