### ISSUE TITLE
不下载语音资源的用户会在公开招聘时卡住

### ISSUE THREAD

**Issue by weiby3** [MaaAssistantArknights/MaaAssistantArknights#2287]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如果选择不下载语音资源，那maa在点击公开招募后会出现如下弹窗。
![image](https://user-images.githubusercontent.com/30197106/195126780-af1bc0c1-940c-4b15-9aa4-273ba8afdc9e.png)
此时maa会卡住，后面完成了所有任务，实际一直在这个弹窗界面。
重现的话可以新建一个模拟器，安装明日方舟，不选择下载语音资源。
目前应该是每次更新都会出现一次，点完一次就不会出现了。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9757326/asst.zip)

### 还有别的吗？

mumu模拟器，win11
这个应该所有都能复现？

**Comment by zzyyyl** [comment]
有没有可能这是用户自己的问题（x
