### ISSUE TITLE
2022/10/12 7:49:08 System.Exception: 通知平台不可用。

### ISSUE THREAD

**Issue by gdf159159** [MaaAssistantArknights/MaaAssistantArknights#2290]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

gui.err.log

2022/10/12 7:49:08 System.Exception: 通知平台不可用。

### 日志文件

2022/10/12 7:49:08 System.Exception: 通知平台不可用。

通知平台不可用。

   在 Windows.UI.Notifications.ToastNotificationHistory.Clear(String applicationId)
   在 MeoAsstGui.Bootstrapper.OnExit(ExitEventArgs e)
   在 Stylet.BootstrapperBase.<Setup>b__9_1(Object o, ExitEventArgs e)
   在 System.Windows.Application.OnExit(ExitEventArgs e)
   在 System.Windows.Application.DoShutdown()
   在 System.Windows.Application.ShutdownImpl()
   在 System.Windows.Application.ShutdownCallback(Object arg)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

gui.err.log

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
