### ISSUE TITLE
希望可以在连接失败的时候增加一个杀掉adb.exe进程再次尝试的操作

### ISSUE THREAD

**Issue by MigdalBavel** [MaaAssistantArknights/MaaAssistantArknights#2291]
### 说说你遇到的问题？

![QQ图片20221012123947](https://user-images.githubusercontent.com/105539375/195251677-43db68b3-cfcd-433c-9def-b75be4ab271a.png)
现在想让maa自动换班剩下最大的障碍就是稳定性了。偶尔还是会出现图里这种连接失败的情况，这种没法重试，之前一直是需要重启一遍PC才能解决。
但实际上后来我试验发现，好像用任务管理器杀掉adb.exe再重试执行往往也都能解决，可能重启实际上只是顺带做了这件事？
所以能否对这种连接失败情况增加一个杀掉adb.exe再重试的操作？

**Comment by zzyyyl** [comment]
勾选连接设置-自动检测连接

**Comment by MigdalBavel** [comment]
> 勾选连接设置-自动检测连接

不是常态的连接问题，大部分时候是正常的，也勾的自动检测。只是待机时间久了或者中途模拟器关过再开之类，偶尔就有可能会这样。比如想让maa早上自动换班放那待机一晚上可能就出现这种情况了。重新杀下adb能解决但是这得要人手动操作。

**Comment by zzyyyl** [comment]
杀adb嫌麻烦的话，关maa重启也是一样的（
一般来说，勾选了自动检测连接的话不会出这种问题，你连接失败的时候是没有勾自动检测的吧（这个选项连接成功一次就会自动取消）

**Comment by MigdalBavel** [comment]
> 杀adb嫌麻烦的话，关maa重启也是一样的（ 一般来说，勾选了自动检测连接的话一般来说不会出这种问题，你连接失败的时候是没有勾自动检测的吧（这个选项连接成功一次就会自动取消）

我碰到的这种情况重启maa没用，必须要杀adb或者重启pc才恢复正常。而且不是麻不麻烦的问题...是这些操作都要手操，我是想让maa定时换班，很多时候人不在场的...

**Comment by zzyyyl** [comment]
那连接失败的时候来个日志

**Comment by MistEO** [comment]
> 杀adb嫌麻烦的话，关maa重启也是一样的（ 一般来说，勾选了自动检测连接的话一般来说不会出这种问题，你连接失败的时候是没有勾自动检测的吧（这个选项连接成功一次就会自动取消）

adb kill server 和结束 adb 进程，感觉不一样啊

**Comment by ChildeRolando** [comment]
不可不可，你考虑到多开的需求了吗，这样写还怎么多开

**Comment by zzyyyl** [comment]
这种问题一般是你电脑有不同版本的adb，最好删掉只留一个）

**Comment by ntgmc** [comment]
现在有adb连接失败自动重启模拟器的功能
感谢您的反馈！
