### ISSUE TITLE
国际服愧影肉鸽bug

### ISSUE THREAD

**Issue by HaoMiaoXin** [MaaAssistantArknights/MaaAssistantArknights#2292]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

关键事件不期而遇无法识别

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9762339/asst.log)

### 截图

![Screenshot_2022 10 12_02 55 42 877](https://user-images.githubusercontent.com/115613387/195271875-4112fa92-3288-4b7d-9624-f9692defc1e7.png)
![Screenshot_2022 10 12_02 55 42 877](https://user-images.githubusercontent.com/115613387/195272292-515ecaf4-f264-4614-9e4e-bf39253f0dae.png)

**Comment by MistEO** [comment]
类似问题，简单修了一下 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2304
