### ISSUE TITLE
有关跳过高心情基建设施的建议

### ISSUE THREAD

**Issue by SKIE1** [MaaAssistantArknights/MaaAssistantArknights#2293]
### 说说你遇到的问题？

以某一贸易站为例，若当前贸易站的所有干员心情均高于阈值，仍然会重新检索全部干员

### 有什么好的想法？

若检测到当前贸易站所有干员心情均高于阈值，选择跳过该贸易站

**Comment by cenfusheng** [comment]
再检测一遍是为了寻找有无效率更高的组合（比如上一班换下来的已恢复心情的干员），逻辑较为合理，目前没有修改的计划，感谢建议
