### ISSUE TITLE
（国服）关于v4.6.4更新后无法进入战斗的问题

### ISSUE THREAD

**Issue by GMHiroki** [MaaAssistantArknights/MaaAssistantArknights#2294]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

v4.6.4版本更新后出现该问题，具体表现为：1、清理智无法正常进入战斗，在选择完关卡之后无法点击开始行动，随后显示“任务出错”，回跳看板之后重复该流程。
2、肉鸽模式（水月）在开始任务后，进入角色招募界面无法确认招募干员，约10秒之后自动放弃本轮任务。回跳终端界面，重复该问题流程。

日志时间：10/12  16：09

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9765108/asst.log)

### 截图

图片上传失败#
MAA作业6群有问题录屏文件

### 还有别的吗？

模拟器：blue stacks5 N64
分辨率：1280*720 DPI:300
操作系统：W11 64位

**Comment by zzyyyl** [comment]
日志404了（

**Comment by GMHiroki** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9765108/asst.log)
重新上传

**Comment by zzyyyl** [comment]
你说日志时间 16:09，传上来的最早的也是 16:34 的（
来个 `assk.bak.log` 看看

**Comment by GMHiroki** [comment]
22：30.在删除软件重新下载解压后问题消失，推测问题产生原因可能是自动更新时解压文件出错。目前问题已解决。

**Comment by zzyyyl** [comment]
更新后肉鸽设置变为下拉框，需要重新选择（也许是这个原因？）

无法开始行动应该是 bug，也许应该给 `StartButton1` 加一个 next： `StartButton1Again`（
