### ISSUE TITLE
自动基建排班 班次选择

### ISSUE THREAD

**Issue by ZwkAlex** [MaaAssistantArknights/MaaAssistantArknights#2295]
### 说说你遇到的问题？

班次选择会自动强制根据当前系统时间选择班次  但是我想人工选择班次 却发现不行 希望能有一个选项能人工选择班次

**Comment by MistEO** [comment]
选完马上开始任务就好了，那个下拉框一分钟刷新一次（

**Comment by Private233** [comment]
但是它在执行任务的时候也会自动刷新，这样岂不是需要把基建换班设成第一个任务？
不过我把换班文件里的period字段删掉，它就不会检测时间不会刷新班次了（

**Comment by ZwkAlex** [comment]
> 但是它在执行任务的时候也会自动刷新，这样岂不是需要把基建换班设成第一个任务？ 不过我把换班文件里的period字段删掉，它就不会检测时间不会刷新班次了（

好方法，已解决
