### ISSUE TITLE
水月肉鸽：希望进入商店时先刷新再购买

### ISSUE THREAD

**Issue by lxq-9527** [MaaAssistantArknights/MaaAssistantArknights#2298]
### 说说你遇到的问题？

手动稀有藏品、和指路鳞片太难遇到了
希望可以脚本挂机刷

### 有什么好的想法？

进入商店后先刷新一次再进行购买

**Comment by WWPXX233** [comment]
目前maa的功能主要是进行刷取等级 要做到这个工作量很大而且 跟人刷一样大海捞针
