### ISSUE TITLE
最新版本公开招募遇到高资TAG模拟器卡死

### ISSUE THREAD

**Issue by pointm** [MaaAssistantArknights/MaaAssistantArknights#2299]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

最新版本公开招募遇到高资TAG模拟器卡死

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9770857/asst.log)

### 截图

![SharedScreenshot](https://user-images.githubusercontent.com/49180699/195503471-fd775035-725b-4345-9669-3873c3b594a1.jpg)
![Screenshot_2022 10 13_12 41 15 385](https://user-images.githubusercontent.com/49180699/195503473-17a9e35a-7485-46da-9e1e-4f0e51708d3d.png)

### 还有别的吗？

使用的模拟器是蓝叠模拟器国际版，系统是WIN10，这个bug应该跟我的配置无关吧，，，

**Comment by horror-proton** [comment]
看了下好像确实存在识别错误, 但是模拟器卡死是什么情况

**Comment by MistEO** [comment]
@horror-proton 为啥识别错误还会一直识别，这块有问题么？按理说点一下返回就去后面的任务了

**Comment by pointm** [comment]
> 看了下好像确实存在识别错误, 但是模拟器卡死是什么情况

抱歉，可能是我的描述有误，我的模拟器并没有卡死，应该是脚本卡死_(:з」∠)_
