### ISSUE TITLE
自动战斗，部署时选错干员

### ISSUE THREAD

**Issue by lindsayee** [MaaAssistantArknights/MaaAssistantArknights#2300]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

MAA版本v4.6.4，使用自动战斗功能攻略11-20时（作业id=maa://10627），
作业中要部署星熊，系统选取星熊但是拖拽了隔壁的瑕光放到对应位置，
试了几次都是必现，验证去掉瑕光后可正常部署星熊。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9771409/asst.log)

### 截图

选择星熊时正确
![image](https://user-images.githubusercontent.com/4250090/195517254-7d549512-b785-4abd-91b0-56d10fd398b8.png)
但是拖拽时选了瑕光
![image](https://user-images.githubusercontent.com/4250090/195517411-7a8fff8d-531b-4109-86e5-c178b795067d.png)
队形（星熊和瑕光都是22费）
![image](https://user-images.githubusercontent.com/4250090/195517486-0730fc63-da9b-4dcd-b43b-9a5e0d97d1a2.png)

### 还有别的吗？

MUMU模拟器2.6.20.0
720*1280 320dpi

**Comment by lindsayee** [comment]
附上模拟器截图
![MuMu20221013143244](https://user-images.githubusercontent.com/4250090/195521047-d4d38d85-0859-4b3e-8ae2-821025faaa50.png)
![MuMu20221013143139](https://user-images.githubusercontent.com/4250090/195521061-85cc6eb6-c4fb-4cf8-af5f-958b44dc7765.png)

但后面又验证了几次，把瑕光换成不同干员，又是也会复现（比如选成煌/暴雨），但有时换回瑕光也没复现，应该和瑕光本身的识别无关

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1121 是这个问题，不好解决，下次一定.jpg

**Comment by lindsayee** [comment]
原来是部署列表问题！那感觉好多自动战斗异常的都可以解释了（选错的干员费不够/高台地面不一样导致没放下来，最后崩盘）
很多博士会在打的时候拖信赖，如果系统有默认提供战术道具的话应该就很容易触发这个bug……
而且部署列表会根据剩余的人数动态调整位置，确实不好处理呐……_(:з」∠)_

**Comment by DavidWang19** [comment]
> #1121 是这个问题，不好解决，下次一定.jpg

不能部署前cancel_oper_selection吗

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
