### ISSUE TITLE
从“开始唤醒”执行任务时，没有考虑游戏更新的情况（部分任务还会直接判定成功）

### ISSUE THREAD

**Issue by CharlesChou73** [MaaAssistantArknights/MaaAssistantArknights#2303]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

“开始唤醒”不识别下载进度条，而且会判定任务成功，执行下一任务；
“访问好友”在游戏处于下载界面的情况下，卡了十几秒，然后判定任务成功，执行下一任务；
“刷理智”因为需要识别并点击按钮，报会执行失败；
其他任务未测试。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9772501/asst.log)
16:29:41-16:30:51

### 截图

![image](https://user-images.githubusercontent.com/16950543/195545748-73022f28-7b1b-429c-abab-47326a5d2f59.png)

### 还有别的吗？

模拟器是蓝叠国际版。

**Comment by CharlesChou73** [comment]
看起来是写这俩任务的时候操作都是闭着眼睛点，省了图像识别的步骤

**Comment by MistEO** [comment]
不是闭着眼睛点的，而是这里有 bug，任务失败界面上没显示出来

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
