### ISSUE TITLE
自定义基建换班搓玉 制造站源石碎片补货后无法选人

### ISSUE THREAD

**Issue by KoisatoL** [MaaAssistantArknights/MaaAssistantArknights#2305]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

制造站当前设定生产份数与实际可生产份数不同时 源石碎片补货后 更换进驻干员时 没有进入干员列表(卡在下方截图1的位置)
导致在制造站面板划动寻找干员(实际上根本找不到)
重复30秒左右放弃选人 直接进入下一个制造站

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9776151/asst.log)
19:25:11时出现的问题

### 截图

![Screenshot_2022 10 13_19 42 23 727](https://user-images.githubusercontent.com/115708631/195587287-6d530ebc-a607-4626-b729-2074c99acfb6.png)
![90L0E)F%4F% }4O HAVCK3R](https://user-images.githubusercontent.com/115708631/195587596-427bf151-ec05-4f4d-b099-7e299386e5ec.png)

### 还有别的吗？

模拟器是蓝叠国际版

**Comment by ReoNaYL** [comment]
加1

**Comment by greyglass** [comment]
+1

**Comment by yuanlemon** [comment]
我也出现了这个问题 不补货的话能正常换人

**Comment by ABA2396** [comment]
41cfb6673636d047804fb8001f1d4d0a7e59be60 fixed
