### ISSUE TITLE
关于回调消息协议的消息类型文档不全

### ISSUE THREAD

**Issue by JiHongYuan** [MaaAssistantArknights/MaaAssistantArknights#2308]
### 说说你遇到的问题？

- InternalError
- TaskChainError 
- TaskChainStart
- TaskChainCompleted
- TaskChainExtraInfo
- SubTaskError
- SubTaskStart
- SubTaskCompleted

## 这几个类型文档没写

**Comment by MistEO** [comment]
其实枚举就是依次递增啊，我感觉没啥好写的 orz
不过看你 pr 加上了，到也没啥问题（

**Comment by JiHongYuan** [comment]
类型的字段解释不全（

**Comment by zzyyyl** [comment]
没解释的基本用不上.jpg

另外我看 SubTaskExtraInfo 文档里有解释
