### ISSUE TITLE
请问台服是不支持肉鸽吗？

### ISSUE THREAD

**Issue by zxc173123** [MaaAssistantArknights/MaaAssistantArknights#2311]
### 说说你遇到的问题？

选人点放弃然后卡在招募那了

**Comment by orange890402** [comment]
我也想問是因為剛上線還沒有支持嗎 會卡在招募那裏

**Comment by zzyyyl** [comment]
看文档。 https://github.com/MaaAssistantArknights/MaaAssistantArknights#%E5%A4%96%E6%9C%8D%E6%94%AF%E6%8C%81

尚未支持

**Comment by MistEO** [comment]
没号 + 没时间适配。有兴趣的大佬们可以试着自己适配下，不需要写代码，但需要大量的截图。最好能再给我们提个 PR（

一些可能参考的链接：
美服肉鸽适配 PR: https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1242
日服肉鸽适配 PR: https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1233
肉鸽适配讨论及一些小工具的使用方法: https://github.com/MaaAssistantArknights/MaaAssistantArknights/discussions/1212
PR 教程: https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/2.2-开发相关.md

**Comment by KiyuM1n** [comment]
@MistEO 是修改 resource\global\txwy 下的所有與台服字體不同的圖片嗎?

**Comment by MistEO** [comment]
WIP: https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/2322

**Comment by MistEO** [comment]
gamedata 没更新，现在需要一下肉鸽的关卡名对照表，有没有朋友帮忙整理一下的

下面这个这个是美服的，需要把里面的英文名换成对应的繁中的关卡名

[IS-stages.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9845071/IS-stages.zip)

**Comment by MistEO** [comment]
以及这些分队名对应什么，也需要帮忙整理一下

```json
[
    [
        "As Your Heart Desires",
        "随心所欲"
    ],
    [
        "First Move Advantage",
        "先手必胜"
    ],
    [
        "Slow and Steady Wins",
        "稳扎稳打"
    ],
    [
        "the Race",
        "稳扎稳打"
    ],
    [
        "Overcoming Your",
        "取长补短"
    ],
    [
        "Weaknesses",
        "取长补短"
    ]
]
```

```json
[
    [
        "Leader Squad",
        "指挥分队"
    ],
    [
        "Gathering Squad",
        "集群分队"
    ],
    [
        "Support Squad",
        "后勤分队"
    ],
    [
        "Spearhead Squad",
        "矛头分队"
    ],
    [
        "Tactical Assault",
        "突击战术分队"
    ],
    [
        "Tactical Fortification",
        "堡垒战术分队"
    ],
    [
        "Tactical Ranged",
        "远程战术分队"
    ],
    [
        "Tactical Destruction",
        "破坏战术分队"
    ],
    [
        "Research Squad",
        "研究分队"
    ],
    [
        "First-Class Squad",
        "高规格分队"
    ]
]
```

```json
[
    [
        "Caster",
        "术师"
    ],
    [
        "Medic",
        "医疗"
    ],
    [
        "Vanguard",
        "先锋"
    ],
    [
        "Sniper",
        "狙击"
    ],
    [
        "Specialist",
        "特种"
    ],
    [
        "Supporter",
        "辅助"
    ],
    [
        "Defender",
        "重装"
    ],
    [
        "Guard",
        "近卫"
    ]
]
```

**Comment by Realmajia** [comment]
[
    [
        "Leader Squad",
        "指揮分隊"
    ],
    [
        "Gathering Squad",
        "集群分隊"
    ],
    [
        "Support Squad",
        "後勤分隊"
    ],
    [
        "Spearhead Squad",
        "矛頭分隊"
    ],
    [
        "Tactical Assault",
        "突擊戰術分隊"
    ],
    [
        "Tactical Fortification",
        "堡壘戰術分隊"
    ],
    [
        "Tactical Ranged",
        "遠程戰術分隊"
    ],
    [
        "Tactical Destruction",
        "破壞戰術分隊"
    ],
    [
        "Research Squad",
        "研究分隊"
    ],
    [
        "First-Class Squad",
        "高規格分隊"
    ]
]

**Comment by Realmajia** [comment]
[
    [
        "Caster",
        "術師"
    ],
    [
        "Medic",
        "醫療"
    ],
    [
        "Vanguard",
        "先鋒"
    ],
    [
        "Sniper",
        "狙擊"
    ],
    [
        "Specialist",
        "特種"
    ],
    [
        "Supporter",
        "輔助"
    ],
    [
        "Defender",
        "重裝"
    ],
    [
        "Guard",
        "近衛"
    ]
]

**Comment by Realmajia** [comment]
![image](https://user-images.githubusercontent.com/105563281/197388062-28a43eaa-dbc5-43b1-b95a-89d08e09f9cc.png)
分隊的部分我只有見到4個，無法確定英文部分6個是如何對應，姑且po圖在這裡。

**Comment by Realmajia** [comment]
[
        "Demonic Cage",
        "邪异囚笼"
    ],
    [
        "This Ursus Man",
        "这位乌萨斯人"
    ],
    [
        "Duck Lord's Play",
        "鸭爵的戏剧"
    ],
    [
        "Duck Lord's Party",
        "鸭爵的宴会"
    ],
    [
        "Gopnik's Fist",
        "高普尼克之拳"
    ],
    [
        "'Knights' Duel'",
        "“骑士对决”"
    ]

目前除了這上述幾個關卡打的時候沒留心確認之外，其他的關卡已經由我自己打和參考了部分baha哈拉版攻略確認過了關卡名稱並進行了整理。
不出意外的話，該部分關卡名應該是單純的轉換後的 邪異囚籠、這位烏薩斯人、鴨爵的戲劇、鴨爵的宴會、高普尼克之拳、騎士對決
[IS-stages(221024).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9847398/IS-stages.221024.zip)

**Comment by Realmajia** [comment]
[
    [
        "As Your Heart Desires",
        "隨心所欲"
    ],
    [
        "First Move Advantage",
        "先手必勝"
    ],
    [
        "Slow and Steady Wins",
        "穩扎穩打"
    ],
    [
        "the Race",
        "穩扎穩打"
    ],
    [
        "Overcoming Your",
        "取長補短"
    ],
    [
        "Weaknesses",
        "取長補短"
    ]
]

這部分分隊名稱我找了en服相關界面瞅了一眼，應該是單純的英文隊名需要在ui中顯示兩行產生的區別。那麼也一樣如我之前po圖所示的單純簡繁轉換即可。

**Comment by KiyuM1n** [comment]
run了幾次測試版 初步發現了一些識別問題
![9U8LA$UY1P`PO 6ED@E}QNK](https://user-images.githubusercontent.com/68652201/197596141-a01ff579-4e21-42e1-90d4-b8f4eb7b8024.jpg)
分"贓" 被辨識成 分"臟"

以及不明原因的放棄公招
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9854209/asst.log)

可能必須再擴充一下幹員的替代表?
識別出來的結果錯誤可能就只能找到一個加一次替代了...

**Comment by zzyyyl** [comment]
> 識別出來的結果錯誤可能就只能找到一個加一次替代了...

其实现在官服的干员替代表也是这样慢慢更新出来的：）

**Comment by orange890402** [comment]
欸都那個現在有什麼是可以明確幫上忙的嗎 抱歉我這方面完全是個小白所以不太清楚可以幹嘛...我頂多只能提供截圖...

**Comment by KiyuM1n** [comment]
@orange890402 現在都差不多了 
截圖只差 勝利畫面＆勝利後的劇情跳過按鈕
要截圖記得使用模擬器自帶的

剩下就是多用MAA自動打幾次肉鴿 看看識別有沒有其他bug了

**Comment by orange890402** [comment]
我剛剛有試跑 還是選不了分隊XD

**Comment by AG-0814** [comment]
@KiyuM1n 
您好，這邊剛剛借了個台服號測試了下，使用的模擬器是bluestack5.9.300.1014，現在問題有二
一、開局選人時的職業與開局幹員設定失效，由於這個號沒有山我設定了羽毛筆(取長補短職業卷)跟藍毒(穩扎穩打職業卷)試著開局，若設定非默認職業組的選項時，會卡在選卷的選項上，然後就不動了
二、在選擇默認職業組的時候，近衛卷點進去搜尋一遍後拉回到最前面選上了棘刺，而非設定的羽毛筆，接著另外兩張醫療輔助卷此號測試會直接選擇放棄招募而非拿一個梓蘭與三星奶
![Screenshot_2022 10 25_18 18 20 436](https://user-images.githubusercontent.com/71961174/197750672-7465de74-56c0-495d-a33d-2197f8d12fdc.png)
![Screenshot_2022 10 25_18 16 45 953](https://user-images.githubusercontent.com/71961174/197750683-23de8b1a-be40-435d-b6b7-0dddc0d21527.png)
![Screenshot_2022 10 25_18 18 33 220](https://user-images.githubusercontent.com/71961174/197750685-382e1d6c-fa85-4d63-970d-bb012d559373.png)
![Screenshot_2022 10 25_18 18 25 120](https://user-images.githubusercontent.com/71961174/197750688-68bb7084-10de-4c9f-b440-770a42658b25.png)
![螢幕擷取畫面 2022-10-25 181939](https://user-images.githubusercontent.com/71961174/197750718-8b2293d1-387e-4d80-80fe-7c19358c4ed7.png)
![螢幕擷取畫面 2022-10-25 181706](https://user-images.githubusercontent.com/71961174/197750723-2be3be0e-1c0e-4f3e-a5ea-b6303cf930e2.png)

接著是就算選上棘刺出戰也行吧，但站位實在是有點怪，懷疑站位套的可能是抓山的時候的站位，在下圖此關會站到傳送門門口，而非考慮放到能打大怪的位置上，或乾脆退後一格把大怪全漏掉，謝謝你幫忙適配，有任何需要我可以盡量提供幫助
![Screenshot_2022 10 25_18 19 08 419](https://user-images.githubusercontent.com/71961174/197750950-065c5c1d-5921-4d9f-860b-bcddfbb1baee.png)

**Comment by AG-0814** [comment]
稍後我看一下，我先把這號的月度小隊打完ww

**Comment by AG-0814** [comment]
試一下log傳不傳的上來 大概18:11左右開始測試的
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9859587/asst.log)

**Comment by KiyuM1n** [comment]
> 試一下log傳不傳的上來 大概18:11左右開始測試的 [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9859587/asst.log)
這應該還是舊版 先試試新版的吧

**Comment by Realmajia** [comment]
剛好看到郵件。因為我正好解鎖了相關分隊而且有全卡組，於是我下載了樓上的dev版試圖復現下存在的問題。
![图片](https://user-images.githubusercontent.com/105563281/197755128-017e4fbc-e7d7-4cbe-b6b7-56116cd1ff6e.png)
然後發現如上進行設置後會卡在分隊選擇界面不停的嘗試從左往右拉動。無法繼續進行下去。
![图片](https://user-images.githubusercontent.com/105563281/197755395-060a19f0-d2dc-410d-bedd-b33204867e79.png)
我當前並沒有解鎖全部分隊，但是設置中需要的分隊是解鎖狀態。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9859620/asst.log)

**Comment by Realmajia** [comment]
| raw: [{ 初始目標生命+2，: [ 941, 116, 155, 19 ], score: 0.981550 }, { 初始目標生命值為1，所: [ 371, 115, 223, 22 ], score: 0.897906 }, { 戴門獲: [ 1091, 114, 61, 23 ], score: 0.491981 }, { 招募4星以上的【先锋】: [ 654, 113, 192, 24 ], score: 0.907581 }, { 初始源石锭+20，初始希: [ 87, 114, 205, 23 ], score: 0.956740 }, { 部: [ 2, 116, 14, 19 ], score: 0.994059 }, { 研究分隧: [ 997, 44, 105, 27 ], score: 0.817067 }, { 突擎術分隧: [ 689, 46, 153, 23 ], score: 0.547898 }, { 矛頭分啄: [ 430, 45, 104, 27 ], score: 0.808925 }, { 俊勤分隧: [ 146, 44, 104, 28 ], score: 0.771864 }]

看上去是字體識別誤很大導致的

**Comment by AG-0814** [comment]
@KiyuM1n 您好，這邊用了你提供的win-64x測試了下，與我剛剛測試下來一樣的問題，不過這次他卡在圖片這裡了，[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9859653/asst.log)

![Screenshot_2022 10 25_19 04 00 670](https://user-images.githubusercontent.com/71961174/197757148-7f696d30-88de-437a-b428-54a0845358e9.png)

**Comment by AG-0814** [comment]
話說我看了下log裡面，有這樣一大串的東西，選人的設定上是不是有問題?
_[2022-10-25 19:01:48.386][ERR][Px4e64][Tx27bc] Unknown role 藍毒 0
[2022-10-25 19:01:48.386][TRC][Px4e64][Tx27bc] ready to sleep 500
[2022-10-25 19:01:48.889][TRC][Px4e64][Tx27bc] end of sleep 500_

**Comment by Realmajia** [comment]
![图片](https://user-images.githubusercontent.com/105563281/197760016-f33f6260-70c0-4f1a-baba-04ed93bc66e0.png)
![图片](https://user-images.githubusercontent.com/105563281/197759946-0540ccd2-0870-4269-9747-ab804716956f.png)
設定為默認選項的情況下，可以自動選擇默認小隊和取長補短進入戰鬥，在有滿級棘刺、山、42等近衛的情況下選擇煌、安塞爾和梓蘭。
之後在進入第二層時，如上圖主界面截圖，有一關關卡識別錯誤和緊急作戰落魄騎士識別成普通作戰的問題。於是我當場複製了log在這邊。
[asst - bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9859784/asst.-.bak.log)

**Comment by orange890402** [comment]
> 
![messageImage_1666697316943](https://user-images.githubusercontent.com/115578376/197763059-6ef7b205-e1d7-457f-892e-ece9b3876639.jpg)
我是兩個都默認的時候也是會優先棘刺 而且會一直往右滑

**Comment by Realmajia** [comment]
![Screenshot_20221025-193741](https://user-images.githubusercontent.com/105563281/197764929-615b1e19-18bb-42be-ba75-9d6128396a0b.png)
我這邊沒有優先抓取棘刺的情況，最近的這把如圖的選擇下選了chen。然後其他兩張位置直接放棄，單張chen開打第一個關卡就被入好入滿了。不過我上面po的選煌的那把在我有干擾硬拿一張肉鴿活動送的1級五星重裝進去的情況下也堅持到了第三層boss才掛掉。意外的強力：p
有關上把全程和這把單選chen不選其他輔助治療的log在這裡。麻煩各位大佬了。感激不盡~
[asst - bak2.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9859899/asst.-.bak2.log)

**Comment by KiyuM1n** [comment]
新的測試版在處理中 好了後可以在[這裡](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/3320756555)下載

**Comment by Realmajia** [comment]
![图片](https://user-images.githubusercontent.com/105563281/197786319-07554077-3b2d-40e9-93f9-7806680fd99a.png)
使用最新的测试版以上圖的配置打了一场，全程有3次關卡識別錯誤進場後無操作，我手動操作過關後肉鴿放棄手動操作，maa能自動繼續。打到了4層。提供log如下
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9860721/asst.log)

**Comment by orange890402** [comment]
抱歉我這裡忘記截圖了
剛剛有試了幾把 遇到幾個狀況
首先選擇默認/默認/空白的話是可以正常選擇幹員的，只是不知道為何默認設定是羽毛筆/ff0，且在選擇職業組別/招募幹員的時候會卡很久才選擇，另外選擇幹員的時候還是會向右滑到底再往左滑到最前面才選擇幹員
再來其他分隊的部分不論選擇哪個分隊哪個職業組哪個幹員 都會卡死在選擇分隊的那個頁面左右滑
但開局之後就沒甚麼問題了 我選擇的是刷投資 第二層有退出
再麻煩各位大大了QQ

**Comment by KiyuM1n** [comment]
@orange890402 
會滑到底的原因應該是要先分析所有幹員數據的樣子
其他的分隊好像還是有識別上的問題不能使用

**Comment by MistEO** [comment]
> 全程有3次關卡識別錯誤進場後無操作

关卡名识别错了，有这么几个错误的结果，可能是哪些关？

- 袁是公二
- 永無儘頭
- 一是一非一正正一張一

**Comment by MistEO** [comment]
用 [这个测试版](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/3322431228) 吧，关卡识别错了会自动保存下图片，在 map 文件夹下。上面有两个名字不知道是啥关，有点难猜

**Comment by Realmajia** [comment]
> > 全程有3次關卡識別錯誤進場後無操作
> 
> 关卡名识别错了，有这么几个错误的结果，可能是哪些关？
> 
>     * 袁是公二
> 
>     * 永無儘頭
> 
>     * 一是一非一正正一張一

除了 永無盡頭 是單純明顯的識別錯誤外。我只記得每次都會識別錯誤的有 從眾效應 了。這兩個是真的難猜。。。我換個新的回頭去跑

**Comment by Realmajia** [comment]
![图片](https://user-images.githubusercontent.com/105563281/197829388-8bb59c42-e3b6-446c-a96b-e4376ad8f07e.png)
選擇如圖配置卡分隊選擇的log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9862179/asst.log)

**Comment by Realmajia** [comment]
晚上發現兩個識別錯誤 分贓不均 和 從眾效應

[2022-10-26 01:09:04.203][TRC][Px5e9c][Tx4588] OcrPack::recognize | raw: [{ 分臟不均: [ 0, 0, 0, 0 ], score: 0.934220 }]
[2022-10-26 01:09:04.203][TRC][Px5e9c][Tx4588] OcrPack::recognize | proc: [{ 分臟不均: [ 522, 451, 237, 59 ], score: 0.934220 }]

[2022-10-26 01:25:20.647][TRC][Px5e9c][Tx4588] OcrPack::recognize | raw: [{ 從累效應: [ 0, 0, 0, 0 ], score: 0.878179 }]
[2022-10-26 01:25:20.647][TRC][Px5e9c][Tx4588] OcrPack::recognize | proc: [{ 從累效應: [ 520, 451, 239, 60 ], score: 0.878179 }]

**Comment by AG-0814** [comment]
@MistEO 
目前的狀況是默認分隊(指揮)+默認職業組(近醫輔)+指定幹員(羽毛筆)，可以出發
這裡掛了幾把發現幾個問題
其一是這個指定幹員羽毛筆(+160調香師)似乎需要用簡中(即羽毛笔)才能設定成功，但有機率會失敗，目前只有一場抓上了羽毛筆，其他都變成選上棘刺+155臨時奶出發


其二是這裡的輔助卷無論抓了羽毛筆還是抓了棘刺都默認不會抓上人(至少抓了155臨時術也好?)，會選擇放棄然後換醫療卷開始選人
=這個我覺得大概是預備乾員-術師的設定問題，台服的干員是翻成幹員，不是直接簡轉繁變乾員

```
[2022-10-26 15:18:39.676][TRC][Px3428][Tx4ffc] asst::RoguelikeRecruitImageAnalyzer::analyze | leave, 247 ms
[2022-10-26 15:18:39.676][TRC][Px3428][Tx4ffc] asst::RoguelikeRecruitTaskPlugin::_run | Ignored low level oper: 梓兰 1 15
[2022-10-26 15:18:39.676][INF][Px3428][Tx4ffc] asst::RoguelikeRecruitTaskPlugin::_run | Page 0 oper list: [預備乾員一術師, 梓兰]
[2022-10-26 15:18:39.676][TRC][Px3428][Tx4ffc] asst::RoguelikeRecruitTaskPlugin::_run | Page 0 oper count: 2 - stop swiping
[2022-10-26 15:18:39.676][TRC][Px3428][Tx4ffc] asst::RoguelikeRecruitTaskPlugin::_run | No oper in recruit list.
```

其三是我有次卡在門口進不去，會卡在拿完人後要進入古堡那裡(時間是10-26_14-32)，一直嘗試點進入古堡但都沒點到正確的位置，然後那局就直接退掉了，後來幾次沒有這個問題了

接著是道中部份，在棘刺開局，與蟲為伴(一直失敗)與禮炮小隊(後來打的幾把此關放上去了)關卡出現
了會一直嘗試點下方三星臨時奶但不拖上去的問題，懷疑是可放置格子識別有問題
二層的分贓不均還是會有識別問題，完全不會放人下去打
[debug (2).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9867169/debug.2.zip)
(我有錄影，不過檔案太大傳不上來，有需要我可以再想辦法提供)

**Comment by Realmajia** [comment]
使用96e7b01的dev版，還是存在開局小隊識別和鎖定山等幹員無效的問題。
然後使用默認打了一把，會在有大量滿級6星近衛的情況下選擇羽毛筆和蜜莓開局。
之後順利的推進到4層左右出現了識別錯誤。看了下應該是那張起手六隻中途會出鼠王的圖—— 煙花秀
這個識別可以說是很神秘了。

[2022-10-26 19:13:21.198][TRC][Px334][Tx43b8] OcrPack::recognize | roi: [ 334, 433, 714, 104 ]
[2022-10-26 19:13:21.198][TRC][Px334][Tx43b8] Ocr Rec with asst::WordOcr
[2022-10-26 19:13:21.217][TRC][Px334][Tx43b8] OcrPack::recognize | raw: [{ 本輝火秀是天: [ 0, 0, 0, 0 ], score: 0.471350 }]
[2022-10-26 19:13:21.217][TRC][Px334][Tx43b8] OcrPack::recognize | proc: [{ 本輝火秀是天: [ 334, 433, 714, 104 ], score: 0.471350 }]
[2022-10-26 19:13:21.217][TRC][Px334][Tx43b8] asst::TilePack::calc | enter

順便在翻log的時候在之前看到了不少幹員名的識別錯誤。桑葚——桑基之類的。在19:12附近。
[2022-10-26 19:12:19.535][INF][Px334][Tx43b8] asst::RoguelikeRecruitTaskPlugin::check_char | Oper list: [蜜莓, 桑基, 白面號, 凯尔希, 闪灵, 华法琳, 夜鷲, 黎雨]

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9869033/asst.log)

**Comment by AG-0814** [comment]
上面好像有大佬前幾天說還缺由遊戲通關截圖，我把遊戲結尾的所有圖截下來打包放這裡
[GamePass.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9869301/GamePass.zip)

然後關於樓上回復的開局幹員選擇上問題，我覺得應該是roguelike_recruit裡面羽毛筆的招募優先級拉到了950的原因(因為水月肉鴿非常適合羽毛筆開局)，(我會招不到應該是我這邊圖片識別有問題，但我也不確定是為什麼，我看log裡OCR回覆都滿正常的)，你可以先手動試試把羽毛筆的招募優先級調低或直接調到零讓他不招，這樣應該可以正常開局

**Comment by Realmajia** [comment]
@AG-0814 我又多試過幾局然後發現貌似很神秘的存在很奇特的隨機性。雖然羽毛筆用的比較多，但是我現在看到這把是1技能chen開局。XD

**Comment by KiyuM1n** [comment]
@ABA2396 建議這樣設定
![image](https://user-images.githubusercontent.com/68652201/198049894-ada05faf-5657-4ff5-a857-7138fdb2c0e7.png)

**Comment by AG-0814** [comment]
重打了一把，這裡是通關截圖
[gamepass.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9870912/gamepass.zip)

**Comment by Realmajia** [comment]
今天台服開放了將進酒活動，測試了下4.6.5b3版本。肉鴿的分隊選擇功能之類的尚未恢復正常。抓卡邏輯也還是也怪怪的。
但是代替無聊的刷蠟燭重複勞動整體上已經有了不錯的可用性了。
稍後活動圖刷的差不多了會開著maa去更多的自動推肉鴿看看還有哪些問題。

另外，今天台服開放了將進酒活動，我在刷圖的時候想起來，雖然寫在這邊可能不太合適，台服的日常刷理智過關之後的掉落識別功能一直是報錯的。因為剛看肉鴿錯誤截圖文件夾的時候，看到debug/drops中有上千張圖片XD。
我之前考慮到可能企鵝物流那邊不需要統計台服掉落數據進行收集所以也一直沒有匯報bug，而且也不影響日常使用。不過今天想到或許可以設置一個刷理智功能中是否需要識別掉落物件的功能。反正當前台服也沒有可以規劃設置刷取掉落數數量來刷圖的功能。也許可以降低後台開銷？

**Comment by KiyuM1n** [comment]
@Realmajia 掉落識別會在台版推出第十章的時候修正
因為在第十章推出後掉落結算介面會有改版

**Comment by Realmajia** [comment]
@KiyuM1n rager that。那確實沒有修復的必要。等版本自己追上來就好了XD

**Comment by AG-0814** [comment]
使用 V4.6.5 beta.3，目前配置是默認分隊+取長補短職業組+指定羽毛筆 可以出戰，臨時術師不招的問題也修好了，十分感謝

目前的問題是後勤分隊選不上，因為我asst.log整體太大太多東西所以我只把有問題的這四分鐘的log裁切下來，我翻了下，後勤分隊四個字是有識別出來的，可是不知道為什麼沒選，麻煩大佬們再幫忙調整一下，謝謝啦
[後勤分隊選取問題log.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9885822/log.txt)

**Comment by AG-0814** [comment]
您好，我剛剛掛了一小時因為羽毛筆有個狗狗關他一直會漏狗而戰鬥結束，所以我打算換成藍毒+穩扎穩打試試，結果我發現他並不會選穩扎穩打職業組並且會自己選上取長補短+羽毛筆出戰，這是剛剛那把的log，請大佬們再看看
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9886438/asst.log)

**Comment by MistEO** [comment]
这个 issue 回复太长了，issue 本身的问题（台服肉鸽支持）已经基本解决了，再有肉鸽细节的问题，或者别的问题，重新开贴吧~
