### ISSUE TITLE
水月肉鸽闪退的问题

### ISSUE THREAD

**Issue by Mugealways** [MaaAssistantArknights/MaaAssistantArknights#2313]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽，探索过程中回到主界面后再继续探索，之后进入关卡MAA会闪退，关卡暂停

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9781684/asst.zip)
问题大致出现在2022.10.14 9.18分左右

**Comment by Mugealways** [comment]
补充：截图。就是进入战斗后直接暂停了，MAA也退了
![image](https://user-images.githubusercontent.com/113966605/195746555-cf0e4862-bb17-4cc7-83c4-971b16b27caa.png)

**Comment by MistEO** [comment]
@DavidWang19 是不是头像 ROI 或者那个 offset 越界了（
