### ISSUE TITLE
请问基建和肉鸽的角色优先级是什么呢？

### ISSUE THREAD

**Issue by MurphyZX** [MaaAssistantArknights/MaaAssistantArknights#2314]
### 说说你遇到的问题？

基建可能有点复杂，那请问肉鸽呢？主要是想根据优先级练几个角色。

**Comment by zzyyyl** [comment]
基建建议参考公孙长乐（
我们有自定义基建，你什么配置都问题不大（x

肉鸽优先级在 resource/roguelike_recruit.json ，其它几个 roguelike 开头的文件也是肉鸽相关的
字段含义的话字段名已经很清楚了，英语不好的话可以翻译
