### ISSUE TITLE
基建宿舍自动选取干员时会被信赖值挡住名字无法被识别

### ISSUE THREAD

**Issue by LuckieePig** [MaaAssistantArknights/MaaAssistantArknights#2315]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在我是用MAA宿舍自定义配置：243一天4换的文件中，他的宿舍更换逻辑是一个或多个能加快干员心情回复的干员（如流明，黑等）搭配其他其他心情不满的干员；当我没有心情不满的干员时，他会把我信赖不满的干员进驻；问题就出在他拉取信赖不满的干员时 ，他会在宿舍干员右上角标签中选取“未进驻”并把信赖从大到小排列，当选取信赖标签时，他会将信赖值显示在干员名称上面，导致MAA无法在后续干员选取中无法识别干员名（因为被信赖值挡住了），导致拉取干员失败（因为在前一个宿舍中如果使用了信赖值排列，他在后一个宿舍中也会继续采用信赖值的排列方法）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9781974/asst.log)

### 截图

![微信截图_20221014103112](https://user-images.githubusercontent.com/115762149/195748601-9e4524c6-0986-471c-a179-19ab5e5ba248.png)

**Comment by ReoNaYL** [comment]
我也出现了这个问题，而且主要是出现在爱丽丝和车尔尼上，目前我的解决办法是把他们放在第一个宿舍，因为第一个宿舍肯定会放心情不满的，而不会选择信赖不满的，就不会出现遮挡名字的问题了

**Comment by ReoNaYL** [comment]
如果是宿管出现这个问题的话，我的建议就不上宿管，因为4个小时的恢复心情足够上20个小时的班，还可以腾出位置给更多人换班

**Comment by yuanlemon** [comment]
+1 信赖排序后 名字被遮挡会一直往后滑找干员

**Comment by MistEO** [comment]
尽量把需要进驻的干员放一起+放在靠前的宿舍吧

**Comment by Snow-dash** [comment]
> 尽量把需要进驻的干员放一起+放在靠前的宿舍吧

可是需要每个宿舍来一个对群回心情的技能啊（，我觉得在切换宿舍的时候重新返回心情排序或者技能排序就可以了吧
