### ISSUE TITLE
傀影肉鸽在战斗结束后如果出现剧目或者需要多次点击的页面就会卡住

### ISSUE THREAD

**Issue by DFFHSEVDH** [MaaAssistantArknights/MaaAssistantArknights#2318]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

傀影肉鸽在战斗结束后如果出现剧目或者需要多次点击确认的页面就会卡住，卡住之后会自动放弃本次战斗

### 日志文件

> 
[Uploading asst.log…]()

**Comment by DFFHSEVDH** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9784594/asst.log)

**Comment by MistEO** [comment]
/debug/roguelike/ 下有图，发下看看

**Comment by DFFHSEVDH** [comment]
[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9791648/roguelike.zip)
10月14号出现问题的图，boss卡了一次，剧目卡了一次

**Comment by MistEO** [comment]
你的日志全被冲掉了（日志过大下次启动会自动删掉），下次在遇到及时发一下。

文件夹里的图最晚的一张是 `2022-10-14 17:28:56`，但是日志是从 `2022-10-14 17:29:55` 开始的

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。

Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
