### ISSUE TITLE
肉鸽选人识别错误

### ISSUE THREAD

**Issue by MashiroDD** [MaaAssistantArknights/MaaAssistantArknights#2319]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

每次肉鸽初始都会选择海沫，后续招募券也优先4,5星，导致到后续基本无六星。修改了task里肉鸽的maxtime也未解决。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9786381/asst.log)

**Comment by zzyyyl** [comment]
海沫优先级很高。
修改 maxTime 我不知道你从哪里了解到这个方法（？ 这对肉鸽招募星级没有帮助
肉鸽支持自定义开局，可以在设置里修改
另外肉鸽的干员优先级在 resource/roguelike_recruit.json ，字段具体含义直接翻译字段名。

**Comment by MashiroDD** [comment]
谢谢，我看到相关优先度了，没想到海沫的优先度比六星还要高>_<
