### ISSUE TITLE
仓库识别问题

### ISSUE THREAD

**Issue by SwissRollC** [MaaAssistantArknights/MaaAssistantArknights#2320]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

精炼溶剂数量把38识别为738，log截取开始识别到第一轮识别完成，截图是depot文件夹内的对应截图

### 日志文件

[log.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9786427/log.txt)

### 截图

![2022-10-14_20-16-00 196_raw](https://user-images.githubusercontent.com/114994436/195851507-02550558-2fc7-4cd4-8077-6fd9a111ad68.png)

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
