### ISSUE TITLE
物尽其用队（为了刷指路鱼） 战斗时会一直点击八面的骰子，十分影响效率效率

### ISSUE THREAD

**Issue by hchimyuki** [MaaAssistantArknights/MaaAssistantArknights#2321]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

物尽其用队（为了刷指路鱼） 战斗时会一直点击八面的骰子，十分影响效率效率

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9788842/asst.zip)

**Comment by MistEO** [comment]
八面骰子是啥样的，来个图看看（点开的）

**Comment by hchimyuki** [comment]
> 八面骰子是啥样的，来个图看看（点开的）

![MuMu20221015132924](https://user-images.githubusercontent.com/80308036/195970613-a05a05d4-551c-4322-ad5a-431515e819a4.png)
运行时会反复点击这个八面骰
大佬辛苦了

**Comment by hchimyuki** [comment]
> 八面骰子是啥样的，来个图看看（点开的）

![MuMu20221015132924](https://user-images.githubusercontent.com/80308036/195970743-92a91995-8981-4b21-9429-dd7fde97bd17.png)
运行时会反复点击这个八面骰
大佬辛苦了

**Comment by MistEO** [comment]
修了
