### ISSUE TITLE
刷新到高资时能不能留一张招聘许可给高资？

### ISSUE THREAD

**Issue by kerman123456** [MaaAssistantArknights/MaaAssistantArknights#2323]
### 说说你遇到的问题？

今天我刷出来了高资，但是仅有的招聘许可给普通公招给用了，只能等明天再招募

**Comment by 134820134820** [comment]
我觉得这种事大可不必发一个iusses

**Comment by kerman123456** [comment]
> 我觉得这种事大可不必发一个iusses
没用过这个github，这种问题该发在其他分区吗？

**Comment by zzyyyl** [comment]
合理需求，但有点麻烦，估计会搁置

**Comment by MistEO** [comment]
> 我觉得这种事大可不必发一个iusses

发呗，我感觉算合理需求。只是不一定好做
