### ISSUE TITLE
自动肉鸽负优化（水月肉鸽）

### ISSUE THREAD

**Issue by SnailZq** [MaaAssistantArknights/MaaAssistantArknights#2324]
### 说说你遇到的问题？

版本v4.6.4，之前能打过得关卡现在打不过了，干员放置位置有问题
默认分队，默认职业组，开局干员嘉百炼

挂了一夜，刷了五级，哭哭   日志65m传不上来

**Comment by MistEO** [comment]
你说了这些等于没说，我们什么有用的信息也获取不到
