### ISSUE TITLE
打到某关干员放不下去

### ISSUE THREAD

**Issue by JJZZYJS** [MaaAssistantArknights/MaaAssistantArknights#2325]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

打到这一关的时候干员一直放不下去

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9791138/asst.log)
2022/10/15 12：09左右 放不下去干员

### 还有别的吗？

mumu模拟器

**Comment by MistEO** [comment]
啥意思

**Comment by JJZZYJS** [comment]
就是他在别的关卡能把干员放下去，但是打到这关的时候他就一直试图放干员，但是它就是放不下去

**Comment by xuyuanhao-SK07** [comment]
出现同样的问题，MAA在水月自动肉鸽的时候，我睡一觉回来再看发现它在战斗关卡不再放置干员了，有多少怪漏多少怪，MAA右侧的日志也没有报错

> 就是他在别的关卡能把干员放下去，但是打到这关的时候他就一直试图放干员，但是它就是放不下去
