### ISSUE TITLE
基建选择干员时未检测默认排序的问题

### ISSUE THREAD

**Issue by Misaka2623** [MaaAssistantArknights/MaaAssistantArknights#2326]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

由于点击Link Start（开始执行）时如果当前游戏画面正处在基建页面，且第一个要执行的任务是基建换班，MAA将会直接在此页面执行任务。然而如果之前在此基建页面手动操作的时候修改了干员的排序（比如改成了按信赖排序），那么当MAA开始任务后进入制造站等地方选择干员时看到的干员排序将会是之前修改过的排序，而不是默认的按工作状态排序，导致选择的干员可能不准确。

也许可以在选择干员前先检测一下当前的排序是否为期待的排序？或者直接在开始基建换班时先退回到主界面再进去执行？

### 日志文件

描述得挺清楚应该不需要日志文件？我刚刚在码字的时候已经让MAA执行其他任务了，如果依旧需要我提供日志文件的话请告诉我，我复原一下当时的状况再上传

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
