### ISSUE TITLE
MAA设置退出选项失效导致maa最后闪退

### ISSUE THREAD

**Issue by 134820134820** [MaaAssistantArknights/MaaAssistantArknights#2327]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

MAAgui中设置退出退出MAA和模拟器，（最新版maa），昨天开始突然无效，模拟器不会被关掉，看来一眼日志报warning了，maa直接闪退了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9791436/asst.log)

### 还有别的吗？

蓝叠国际版，最近没有版本更新什么东西，昨天突然出现问题

**Comment by ntgmc** [comment]
关闭模拟器有时候会有问题，另外最新版下次记得打版本号

**Comment by 134820134820** [comment]
> 关闭模拟器有时会有问题，其他最新版下一次记得打版本号

后来重新尝试了一下,发现是开着mumu模拟器时,通过maa无法关闭其连接的蓝叠模拟器,会出现无效,maa直接最后一步报错闪退(我一般用mumu手操,蓝叠挂机)

**Comment by ntgmc** [comment]
关掉mumu就能正常关吗？

**Comment by 134820134820** [comment]
> 关掉mumu就能正常关吗？

是

**Comment by 134820134820** [comment]
后来再试时发现的

**Comment by ABA2396** [comment]
现在改成控制台退出了
