### ISSUE TITLE
关于会客室换班效率问题

### ISSUE THREAD

**Issue by liemark** [MaaAssistantArknights/MaaAssistantArknights#2329]
### 说说你遇到的问题？

由于会客室效率不仅受到技能影响，还受到星级(暂时试了一下6星=5星＞4星)，精英化程度影响，比如精二的远山（三级会客室技能）效率其实是不如精二的守林人（二级会客室技能，但是比远山星级高）的，在这里的细节希望能够改进一下

**Comment by zzyyyl** [comment]
远山是 25+2，守林人是 20+4 吧

**Comment by liemark** [comment]
![Screenshot_20221016_085720_com hypergryph arknights bilibili](https://user-images.githubusercontent.com/115876720/196013042-234905c8-f93e-47fb-8748-c843240771aa.jpg)
![Screenshot_20221016_085726_com hypergryph arknights bilibili](https://user-images.githubusercontent.com/115876720/196013045-de3ee307-7c48-433a-a172-0b133181fe42.jpg)
这是我在会客室单独放守林人和远山的数据，守林人是十小时两分钟那个，明显效率高于远山
