### ISSUE TITLE
肉鸽编队中有砾时，进入作战节点时会卡在编队界面

### ISSUE THREAD

**Issue by 327968** [MaaAssistantArknights/MaaAssistantArknights#2333]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

肉鸽编队中有干员“砾”时，在进入作战节点时，在快捷编队选择技能后，会重新选择砾的1技能，然后卡在编队界面。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9793525/asst.log)

### 截图

![Uploading Screenshot_20221016-110733.png…]()

### 还有别的吗？

夜神模拟器，win10 64位系统

**Comment by 327968** [comment]
![Screenshot_20221016-110733](https://user-images.githubusercontent.com/115909469/196016113-4c475eb5-b155-431e-b4fb-787b4a4665e3.png)

**Comment by TonyPtolemy** [comment]
补充一个我遇到的现象：这个bug在某个时间点会自动解决，可能是因为把砾精二了
这一把是我盯着打的，中途卡在编队界面或识别关卡失败时会接管一下，让maa继续打下去

**日志文件**
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9794906/asst.log)

**Comment by LenKiMo** [comment]
![image](https://user-images.githubusercontent.com/10625080/197343035-21191faf-c8c2-4eba-82c3-b0ec6551ca85.png)

同样遇到该问题。

日志文件
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9844508/asst.log)

**Comment by horror-proton** [comment]
可能是相同的原因 #2385
