### ISSUE TITLE
公招能只刷新联络次数不消耗招募吗

### ISSUE THREAD

**Issue by DawnDJ** [MaaAssistantArknights/MaaAssistantArknights#2334]
### 说说你遇到的问题？

仓鼠玩家想屯着公招票，只想刷新次数不想消耗公招票，但是每次执行最大招募次数设置0会直接出错什么都不做

### 有什么好的想法？

增加一个只刷新招募次数不消耗公招票的可选选项

**Comment by zzyyyl** [comment]
把自动确认三星和自动确认四星全取消就行了

**Comment by DawnDJ** [comment]
不行啊，我这样设置开始自动公招后只会显示”出现错误，已返回“



紧张先生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月16日(星期天) 下午3:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 公招能只刷新联络次数不消耗招募吗 (Issue #2334)





 
把自动确认三星和自动确认四星全取消就行了

**Comment by zzyyyl** [comment]
来个日志？

**Comment by zzyyyl** [comment]
@horror-proton
