### ISSUE TITLE
自定义基建换班中菲亚梅塔的稳定性优化

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#2335]
### 说说你遇到的问题？

菲亚梅塔似乎有bug……我指明日方舟的bug
如果在一个存在心情不满的干员的宿舍，直接在进驻列表里面把五个人改成菲亚目标和菲亚梅塔两个人，有较小的概率菲亚梅塔会判定到之前进驻在宿舍的某个心情不满的干员。
例如：原本宿舍进驻了ABCDE，其中E的心情未满还在休息，菲亚梅塔的使用目标是F，现在MAA的操作是点开干员列表，清空，然后直接选择F和菲亚梅塔（按顺序），这样操作有很小的概率会让菲亚梅塔判定到E，从而和E交换心情
具体原因不详，看起来像明日方舟的bug

### 有什么好的想法？

建议使用菲亚梅塔之前先清空宿舍，然后再正常选择目标和菲亚梅塔

**Comment by ABA2396** [comment]
确实，这个问题之前也遇到过，感觉比较稳得方法就是清空之后确认一下，然后再选肥鸭和要回心情的干员

**Comment by auroralwy** [comment]
昨天发生这个问题了... 龙舌兰的心情没有换上，但是单独放的话宿舍又放不满，头有点大了

**Comment by auroralwy** [comment]
龙舌兰已经两天没换成功了..又要亏5个小时的订单...不知道有什么解决办法，今天晚上再观察一下好了，昨天的log是显示已经替换过了，但是今天早上还是龙舌兰显示没有心情...

**Comment by ABA2396** [comment]
如果是自带的作业的话，肥鸭回满心情要8小时零几分，定时启动可能要推迟一小时启动

**Comment by auroralwy** [comment]
> 如果是自带的作业的话，肥鸭回满心情要8小时零几分，定时启动可能要推迟一小时启动

我隔12小时换一次巫恋龙舌兰的，肥鸭肯定能回满....
