### ISSUE TITLE
增加后台启动功能

### ISSUE THREAD

**Issue by weedi0** [MaaAssistantArknights/MaaAssistantArknights#2338]
### 说说你遇到的问题？

希望可以后台或启动后自动隐藏Gui和模拟器。
（另外不知道是不是个例，win11 22h2下需要权限启动蓝叠，执行完成任务后只推出maa无法退出模拟器。

**Comment by ChildeRolando** [comment]
上班摸鱼是吧

**Comment by ntgmc** [comment]
win10系统下win+tab键可以新建桌面
