### ISSUE TITLE
252布局基建中贸易站空弦优先级过高

### ISSUE THREAD

**Issue by hibikiDaisuki** [MaaAssistantArknights/MaaAssistantArknights#2339]
### 说说你遇到的问题？

目前空弦在贸易站中默认的优先级很高
然鹅在252基建布局中一般都压缩了宿舍等级，导致空弦的实际等效仅有百分之十几

### 有什么好的想法？

希望能够优化选取空弦进驻贸易站的逻辑
例如检查宿舍等级或者数下制造站数量等

**Comment by MistEO** [comment]
特殊的基建布局建议用自定义基建
