### ISSUE TITLE
增加更多模式的支持

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#2340]
### 说说你遇到的问题？

保全派驻又臭又长还得手动刷，啥时候也出个自动保全派驻自动打一下；悖论模拟太多，挨个打过去麻烦，也出个代打。

### 有什么好的想法？

增加保全派驻、悖论模拟等多种刷取功能。

**Comment by martinwang2002** [comment]
悖论模拟请前往 https://maa.plus/

**Comment by MistEO** [comment]
不要催更，除非你自己写（

**Comment by xiaoweiXX** [comment]
> 不要催更，除非你自己写（

没有催更啊，就是提个新功能建议嘛
