### ISSUE TITLE
mumu模拟器连接时，分辨率不是720p连接不上

### ISSUE THREAD

**Issue by RiffraDD** [MaaAssistantArknights/MaaAssistantArknights#2341]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

原来可以连接，现在必须设置为720p才能连接上，大于720p（是16:9）就连接不了，提示分辨率有问题。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9794900/asst.zip)

### 截图

<img width="1280" alt="无标题" src="https://user-images.githubusercontent.com/99302406/196041879-9857c6c8-8f70-4617-b6e1-35f7d30f002a.png">

### 还有别的吗？

win11系统

**Comment by MistEO** [comment]
16 / 9 = 1.77777...
1720 / 968 = 1.77685...

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/cb29b09250713ec70174daac6e4a713d8861bf74/src/MeoAssistant/Controller.cpp#L1202-L1203

~~这比例是不是限制得太死了~~

**Comment by MistEO** [comment]
> https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/cb29b09250713ec70174daac6e4a713d8861bf74/src/MeoAssistant/Controller.cpp#L1202-L1203
> 
> ~~这比例是不是限制得太死了~~

不死不行，以前 mumu 一堆识别问题，后来发现是 mumu 预设的几个分辨率太傻逼（

**Comment by RiffraDD** [comment]
我简单除了下，差不多是16:9，就没仔细算，我的锅 @MistEO
