### ISSUE TITLE
自动肉鸽进行中定时启动是否无法打断进行清体？

### ISSUE THREAD

**Issue by alien-zzy** [MaaAssistantArknights/MaaAssistantArknights#2342]
### 说说你遇到的问题？

设置了八点自启动，昨晚挂着肉鸽就直接睡了。今天下午的时候我进游戏发现早上八点没有清体力，程序还在运行自动肉鸽。
后来我测试了一下，在运行自动肉鸽的时候，似乎设置的定时自启动是没法打断正在进行的肉鸽进行清理体力的。
请问确实如此吗？
![G)K6UGHWP`0%3K2QJRC%$_O](https://user-images.githubusercontent.com/79839078/196054026-7fa4d6e2-9afb-46af-a59b-1b87ecaeed9d.png)
![1](https://user-images.githubusercontent.com/79839078/196054032-51f6be85-216e-4e63-ae56-cfe92f773958.png)

**Comment by zzyyyl** [comment]
确实如此。
定时启动不会打断现有的任务流程。
