### ISSUE TITLE
自动肉鸽无法进入傀影肉鸽

### ISSUE THREAD

**Issue by mindechen** [MaaAssistantArknights/MaaAssistantArknights#2343]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

使用傀影自动肉鸽时，进入了水月肉鸽，然后返回主界面loop

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9795602/asst.log)

### 还有别的吗？

![image](https://user-images.githubusercontent.com/18070701/196056749-02718c72-dbeb-45e9-8a4f-ce67c144de77.png)

https://user-images.githubusercontent.com/18070701/196056896-0cc40ccd-d237-4e87-8582-73e092d7c5e5.mp4

**Comment by 327968** [comment]
将傀影肉鸽添加到终端即可

**Comment by ABA2396** [comment]
在集成战略界面把傀影pin到终端
