### ISSUE TITLE
能否增加肉鸽藏品掉落统计

### ISSUE THREAD

**Issue by CHHC-L** [MaaAssistantArknights/MaaAssistantArknights#2346]
### 说说你遇到的问题？

如题，有没有可能在在自动刷肉鸽的过程中（或者结束的时候）统计一下藏品掉落情况（如记录 `{ 藏品名称 } -> { 掉落时灯火值, 护盾值, 生命值, ... } ` 产生这一类的数据

### 有什么好的想法？

如果工作量太大就算啦
或者别封装那么严实开个底层一点的接口也行…
（我自己写截图统计好像跟maa会冲突没法同时执行我还没de出bug（樂）

### 其他内容

（起因是我在小样本下发觉 遇到某些特定藏品（如老蒲扇）的概率似乎与局内的情况有相关性，想要在更大的样本下检验结论）
（当然我知道这理论上不该发生，但是《术士券》）

**Comment by zzyyyl** [comment]
maa 目前没有储存掉落藏品的数据，只存了商店购买的藏品（好像

**Comment by zzyyyl** [comment]
另外灯火生命护盾这类数据也没有，当前打到第几层也不知道）
