### ISSUE TITLE
重启后不能保存肉鸽勾选

### ISSUE THREAD

**Issue by NCQTqwq** [MaaAssistantArknights/MaaAssistantArknights#2347]
### 说说你遇到的问题？

如题，关机及关闭程序前勾选肉鸽，重启程序后并没有勾选肉鸽

**Comment by MistEO** [comment]
设计如此，带 * 的都是不保存的

**Comment by NCQTqwq** [comment]
自动肉鸽选项没有带* 诶QWW

**Comment by NCQTqwq** [comment]
> 设计如此，带 * 的都是不保存的

自动肉鸽选项没有带* 诶QWW

**Comment by NCQTqwq** [comment]
> 如此设计，带*的都不是保存的

是我*号没加载出来吗QWQ明天早上看看

**Comment by MistEO** [comment]
> > 设计如此，带 * 的都是不保存的
> 
> 但肉鸽确实没带*

那加个 * （
