### ISSUE TITLE
请求在刷理智的时候提供剩余理智量及调整刷理智输出（已合并掉落统计

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#2350]
### 说说你遇到的问题？

在刷理智的时候不知道当前进度，比如还能刷多少次，还有多少理智药，还有多少理智

### 有什么好的想法？

在已开始行动后面，追加当前副本消耗的理智，以及开始之前所持有的理智。单个副本消耗的时间一定，理论上可以计算并提供预期结束时间（材料掉落按照企鹅物流的掉落率来计算

**Comment by status102** [comment]
追加新想法，刷理智的右侧输出信息的内容占空间有点多了。一般来说反复刷同一个副本的时候掉落都是相似的，能否调整成为不再单独输出本次掉落而是合并后的数据。（如果是刷理智任务中的第一次副本，那还是输出本次掉落
```
掉落统计：（包括当前次的累积掉落）
  龙门币：2000 (+1000)
  固源岩：2（+1）
```
![image](https://user-images.githubusercontent.com/102887808/196362356-44ac38d9-48de-4e36-9079-651b90c9d2b0.png)

**Comment by DavidWang19** [comment]
maa不读取当前理智量的，只会判断理智是不是用完了

**Comment by status102** [comment]
> maa不读取当前理智量的，只会判断理智是不是用完了

那有办法提示理智消耗 (剩余理智) 的进度么？

**Comment by DavidWang19** [comment]
> > maa不读取当前理智量的，只会判断理智是不是用完了
> 
> 那有办法提示理智消耗 (剩余理智) 的进度么？

我感觉是没啥简单办法，除非就按这个新写个功能模块
