### ISSUE TITLE
开始唤醒识别出错

### ISSUE THREAD

**Issue by qiutongxue** [MaaAssistantArknights/MaaAssistantArknights#2351]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我设置了「启动后自动开启模拟器」（等待时间 120 秒）以及「启动后直接运行」，MAA 成功打开了游戏，也正常执行「开始换新」任务，但是有时候会因为卡在**游戏里**的「开始唤醒」界面，并错误地认为完成了「开始唤醒」任务，导致后序一系列任务都无法进行。

注：以往是卡在「开始唤醒」界面，这次还不是卡在「开始唤醒」界面，而是再往前那个点击黄色图标的界面，我猜有可能是因为启动游戏时间过长导致的

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9806334/asst.log)

### 截图

![MAA界面](https://user-images.githubusercontent.com/53330358/196332623-218a8813-96b0-4ad8-80ce-71658b1fc373.png)

**Comment by MistEO** [comment]
那把等待时间设长一点（？）

**Comment by MistEO** [comment]
我好像理解错了，是启动游戏到出现黄色 start 图标间隔太久（

**Comment by qiutongxue** [comment]
> 我好像理解错了，是启动游戏到出现黄色 start 图标间隔太久（

对，有可能是启动游戏到黄色 start 太久，也有可能是黄色 start 到开始唤醒太久，应该就是中间哪一步时间过长导致 maa 判断出错了？
