### ISSUE TITLE
图形化界面 `指定材料` 功能存在问题

### ISSUE THREAD

**Issue by Nefelibater** [MaaAssistantArknights/MaaAssistantArknights#2354]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

无法使用指定材料功能，选择某一个材料后框会变空白或不选择，即使再手动输入后再选择也会如此

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9812154/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/116096983/196475305-560d0b1b-2618-4e61-a590-56a1c0320ada.png)
点击选择轻锰矿后变成不选择，选择框变成空白
![image](https://user-images.githubusercontent.com/116096983/196476855-53bc5bf0-307d-4379-bd67-c6c2807602e5.png)

### 还有别的吗？

蓝叠模拟器，win11系统

**Comment by ABA2396** [comment]
不知道咋复现，但是一般重启就解决了

**Comment by DavidWang19** [comment]
> 不知道咋复现，但是一般重启就解决了

选中一个之后backspace清空，然后点其他地方，框里就会变成“不选择”这三个字，此时点下拉框就没东西了，要再backspace把不选择删掉才能点

**Comment by ABA2396** [comment]
> > 不知道咋复现，但是一般重启就解决了
> 
> 选中一个之后backspace清空，然后点其他地方，框里就会变成“不选择”这三个字，此时点下拉框就没东西了，要再backspace把不选择删掉才能点

主要问题不是这个，而是偶尔会出现不管点什么都会变成不选择，但是在debug的时候从来没出现过，而且重启后就没这问题了

**Comment by ABA2396** [comment]
> 选中一个之后backspace清空，然后点其他地方，框里就会变成“不选择”这三个字，此时点下拉框就没东西了，要再backspace把不选择删掉才能点

99eebad4826e7eee64d0fd2e49220fc0dc815850 加了个“不选择”时不筛选材料，但是之前那个问题还是没解决
