### ISSUE TITLE
手动输入第十章主线关卡，找不到关卡

### ISSUE THREAD

**Issue by yokinanya** [MaaAssistantArknights/MaaAssistantArknights#2357]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

手动输入第10章的关卡，会找不到关卡，目测是开启了11章主线影响识别，会卡在这个地方
![image](https://user-images.githubusercontent.com/30362789/196602079-c8a73bea-4640-4138-9160-07d9774fecb0.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9816965/asst.log)

**Comment by ABA2396** [comment]
245692f531a8634370efc13003449816a0629c43 fixed

**Comment by Kevin-Lewis1** [comment]
我也遇到了这样的问题，很多次了，手动输入的关卡，我是10-6，就识别不了然后报错跳过。

**Comment by ABA2396** [comment]
> [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9834653/asst.log) 我也遇到了这样的问题，很多次了，手动输入的关卡，我是10-6，就识别不了然后报错跳过。

dev改了，还没发版

**Comment by yokinanya** [comment]
> > [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9834653/asst.log) 我也遇到了这样的问题，很多次了，手动输入的关卡，我是10-6，就识别不了然后报错跳过。
> 
> dev改了，还没发版

所以我直接下actions编译的了
