### ISSUE TITLE
训练室艾丽妮作为协助者被换下的问题

### ISSUE THREAD

**Issue by msymmd1sc** [MaaAssistantArknights/MaaAssistantArknights#2358]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

本来想用艾丽妮协助过专一和专二两个阶段的，专一之后被MAA 换下宿舍，基建技能也就断了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9817283/asst.log)

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/196738986-11d80e7f-ebad-43ab-8c18-2ff84a302dd2.png)

把这个勾上
