### ISSUE TITLE
关于掉落识别

### ISSUE THREAD

**Issue by zoeyek** [MaaAssistantArknights/MaaAssistantArknights#2359]
### 说说你遇到的问题？

某个关卡大量刷取（没错我指1-7）时是否可以关闭掉落识别？一者企鹅物流数据应该足够丰富，上传造成大量资源浪费；二者1-7一关速刷也就60s，但两次刷取中间识别需要7~8s，对效率影响大了点（好的我知道我暴露了没有3090）。。
仅作建议，毕竟角度比较偏，或者我可以连点器替代

**Comment by MistEO** [comment]
识别和上传本身根本不耗时，这里关掉照样要等这么久。是因为代理指挥时 MAA 为了降低 CPU 占用，不是一直在识别的，识别一帧会等好几秒才进行下次识别，到了掉落界面可能 MAA 还在等时间
