### ISSUE TITLE
能否在向企鹅物流上报掉落时尝试使用镜像站地址

### ISSUE THREAD

**Issue by CharlesChou73** [MaaAssistantArknights/MaaAssistantArknights#2361]
### 说说你遇到的问题？

因为其他问题（上一个issue）翻了下日志，发现有好多penguin-stats.io访问超时的日志，大陆地区用penguin-stats.cn会快不少，感觉可以考虑一下？

**Comment by MistEO** [comment]
这个问题是因为企鹅的国内 cdn 流量费太贵了，我们之前就是发国内域名的（.cn），后面用户激增差点把企鹅打破产，~~在企鹅后台大佬的威逼利诱下~~ 最终才改成发 .io 的。

不过目前失败率确实有点高，后面的版本我们准备改成如果 .io 连续失败 5 次，当次就改为发 .cn

**Comment by CharlesChou73** [comment]
> 这个问题是因为企鹅的国内 cdn 流量费太贵了，我们之前就是发国内域名的（.cn），后面用户激增差点把企鹅打破产，~在企鹅后台大佬的威逼利诱下~ 最终才改成发 .io 的。
> 
> 不过目前失败率确实有点高，后面的版本我们准备改成如果 .io 连续失败 5 次，当次就改为发 .cn

翻了下企鹅物流的后台代码，emmm只能说API还有很大优化空间吧，流量可以压到现在的一半以下的_(:з」∠)_

**Comment by zzyyyl** [comment]
@GalvinGao

**Comment by GalvinGao** [comment]
此前使用的是 .cn 镜像站，但由于 CDN 服务对于动态请求数的收费较贵、且 MAA 每天都能打百万级请求数，导致 .cn 镜像站开销过大，所以才改为了 .io + 实现重试幂等的方案。

对于流量优化来说，我们除 POST 这种本身的动态请求外，通过响应头优化来提升 CDN 对返回资源的 TTL 理解，这些请求的回源率已经可以降至 10% 以下。

对于返回体本身很大的问题，v3 API 事实上已经开始开发大半年了（然而大家都没时间所以进展缓慢qvq）。

对于 Protobuf，企鹅物流内部新业务的服务间通讯是基于 gRPC + Protobuf 实现的、对于外部服务来说，probe 服务是基于 Protobuf + WebSocket 实现的。对于 HTTP API 来说，不管 v2/v3 API，大概率依然不会采用，原因是压缩率与 brotli 的差距、在我们分析后、并不足以补足接入的开发成本与 Protobuf 在 JS 端的生成脚本的下载成本。

欢迎大佬来 [penguin-statistics/backend-next/issues](https://github.com/penguin-statistics/backend-next/issues) 提出优化建议~

**Comment by CharlesChou73** [comment]
> 此前使用的是 .cn 镜像站，但由于 CDN 服务对于动态请求数的收费较贵、且 MAA 每天都能打百万级请求数，导致 .cn 镜像站开销过大，所以才改为了 .io + 实现重试幂等的方案。需要注意的是使用 .io 镜像的原因并非由于流量昂贵、而是由于请求数过大。未来我们可能开放批量上传 API、但由于现在的部分反作弊检测是基于请求级别，公开的批量上传 API 的反作弊部分还仍需考量。
> 
> 对于流量优化来说，我们除 POST 这种本身的动态请求外，通过响应头优化来提升 CDN 对返回资源的 TTL 理解，这些请求的回源率已经可以降至 10% 以下。
> 
> 对于返回体本身很大的问题，v3 API 事实上已经开始开发大半年了（然而大家都没时间所以进展缓慢qvq）。
> 
> 对于 Protobuf，企鹅物流内部新业务的服务间通讯是基于 gRPC + Protobuf 实现的、对于外部服务来说，probe 服务是基于 Protobuf + WebSocket 实现的。对于 HTTP API 来说，不管 v2/v3 API，大概率依然不会采用，原因是压缩率与 brotli 的差距、在我们分析后、并不足以补足接入的开发成本与 Protobuf 在 JS 端的生成脚本的下载成本。
> 
> 欢迎大佬来 [penguin-statistics/backend-next/issues](https://github.com/penguin-statistics/backend-next/issues) 提出优化建议~

反作弊这块是我没考虑到的，Java还可以搭把手，Go水平一般，我先拜读下代码吧

**Comment by MistEO** [comment]
> 不过目前失败率确实有点高，后面的版本我们准备改成如果 .io 连续失败 5 次，当次就改为发 .cn

这个加了，我关！
