### ISSUE TITLE
基建宿舍进驻打断艾丽妮加速技能。

### ISSUE THREAD

**Issue by pu4ers** [MaaAssistantArknights/MaaAssistantArknights#2362]
### 说说你遇到的问题？

艾丽妮辅助干员技能专精完成后（未点击进入专精室），宿舍自动换班会将艾丽妮放入宿舍，打断艾丽妮工作5小时后拥有的下次专精时间减半的buff。

### 有什么好的想法？

建议添加一个勾选项，不将专精室内干员放入宿舍。

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/196739560-0cfe45d0-9cb2-4782-90a7-313171f247b8.png)

duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2358

**Comment by pu4ers** [comment]
我是之前遇到了另一个问题没有勾选这个选项，所以才忘了这个选项可以避免艾丽妮被放回宿舍。
之前遇到的问题：
如果勾选了这个选项同时再开启了宿舍蹭信赖，在宿舍仍有人休息的时候运行基建换班脚本，开启了autofill的宿舍会将原本在休息的干员踢出（因为取消选中宿舍内干员后脚本直接开启了“未进驻”筛选项，这时宿舍内原本干员会不显示），把蹭信赖干员放入。
而如果这个宿舍恰好是最后一个被换班的宿舍，就会出现宿舍外有心情未满干员而宿舍内放的却是蹭信赖干员的情况。
