### ISSUE TITLE
水月肉鸽无法识别误入奇境

### ISSUE THREAD

**Issue by YuhangTom** [MaaAssistantArknights/MaaAssistantArknights#2367]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽第五层误入奇境使用了钥匙（其实不应该进寄境吧） 但是没有进入 一段时间后（~1min）自动退出并放弃作战
MAA v4.6.4稳定版

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9825446/asst.log)
10-19 20:24:29 关卡：不期而遇（误入奇境）
10-19 20:25:24 已放弃本次探索（使用钥匙后退出）

### 截图

<img width="600" alt="1666229673292" src="https://user-images.githubusercontent.com/45880737/196835333-0699ca88-5173-4058-94fa-75ceade11766.png">

### 还有别的吗？

MuMu模拟器
Win11

**Comment by MistEO** [comment]
debug/roguelike/ 下有图，发下看看

**Comment by YuhangTom** [comment]
![2022-10-19_20-25-21 354_raw](https://user-images.githubusercontent.com/45880737/196973023-583188e0-f7d3-4f21-91bf-705a0661e0d8.png)
![2022-10-19_20-25-24 884_raw](https://user-images.githubusercontent.com/45880737/196973026-44b7f6f9-e593-4c0b-80f0-5614d30cae64.png)
只有两张这一次的截图
我能知道细节是因为我想看看0难度它能不能自己打到通关（吃太饱了喂） 看到它打到第五层我还挺激动没想到就卡住自己退了...
