### ISSUE TITLE
双开模拟器连接错误

### ISSUE THREAD

**Issue by bby339** [MaaAssistantArknights/MaaAssistantArknights#2368]
### 说说你遇到的问题？

双开了模拟器，第一个稳定链接，可是开第二个就一直显示连接错误。maa已复制多个，也设置了不同adb。请问应该怎么解决双开连接不上的问题
![image](https://user-images.githubusercontent.com/116248513/196861815-6c1867bc-95b4-4dff-bf19-8d95576ac289.png)
![image](https://user-images.githubusercontent.com/116248513/196861827-9da1c728-6cf8-4baa-8abc-d4cb91241191.png)

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/196964603-b7a017ae-e443-428f-8076-e33e83ab5fea.png)
