### ISSUE TITLE
BlueStacks4 hyper-v adb_port 识别问题

### ISSUE THREAD

**Issue by 617721040** [MaaAssistantArknights/MaaAssistantArknights#2369]
### 说说你遇到的问题？

我在BlueStacks4里面并找不到bluestacks.conf文件，也没有BlueStacks_nxt
BlueStacks4的Data目录是C:\ProgramData\BlueStacks_bgp64_hyperv

**Comment by MistEO** [comment]
用 everything 之类的全局搜搜看，也可能不在 C 盘

（我没用过 BlueStacks 4，不确定

话说为啥不用 5

**Comment by 617721040** [comment]
> 用 everything 之类的全局搜搜看，也可能不在 C 盘
> 
> （我没用过 BlueStacks 4，不确定
> 
> 话说为啥不用 5

用everything搜过了，没有这个文件，不用5是之前玩其他游戏用5内存占用异常大。
其实我就是想知道MAA应该是没支持BlueStacks4 Hyper-V，而不是支持了但我没找到方法，因为模拟器支持文档上写的是[蓝叠模拟器国际版 Hyper-V 版本]，没写版本号，所以我就直接下载了BlueStacks4 Hyper-V

**Comment by MistEO** [comment]
如果 4 没有这个文件的话应该就是没支持了，需要每次手动填一下端口号。

或者不知道 4 有没有什么其他简单的方法可以获取到端口号的

**Comment by 617721040** [comment]
> 如果 4 没有这个文件的话应该就是没支持了，需要每次手动填一下端口号。
> 
> 或者不知道 4 有没有什么其他简单的方法可以获取到端口号的

我查了一下，4没有5的conf文件，但是我再"C:\ProgramData\BlueStacks_bgp64_hyperv\Logs\Player.log"里找到一个“2022-10-21 14:15:54.612 10908:00000001 (HD-Player) INFO: 5555 --> 52958. Protocol: TCP”能获取ADB的端口号

**Comment by 617721040** [comment]
`
import re
import json
def load_adb_port():
    bs4_log = open("C:\ProgramData\BlueStacks_bgp64_hyperv\Logs\Player.log","r",encoding="utf-8")
    for line in bs4_log:
        if "INFO: 5555" in line:
            bs4_adb_line = re.search("\d{5}\.",line).group()
    return bs4_adb_line.strip(".")
def save_adb():
    f =  open("gui.json","r",encoding="utf-8")
    maa_cfg_dict = json.load(f)
    maa_cfg_dict["Connect.Address"] = "127.0.0.1:%s"%load_adb_port()
    f.close
    f = open("gui.json","w",encoding="utf-8")
    gui_json = json.dump(maa_cfg_dict,f,indent=2)
save_adb()
`
我写了小段python代码，可以吧blue4的adb端口号添加到gui_json内

**Comment by 617721040** [comment]
```
import re
import json
def load_adb_port():
    bs4_log = open("C:\ProgramData\BlueStacks_bgp64_hyperv\Logs\Player.log","r",encoding="utf-8")
    for line in bs4_log:
        if "INFO: 5555" in line:
            bs4_adb_line = re.search("\d{5}\.",line).group()
    return bs4_adb_line.strip(".")
def save_adb():
    f =  open("gui.json","r",encoding="utf-8")
    maa_cfg_dict = json.load(f)
    maa_cfg_dict["Connect.Address"] = "127.0.0.1:%s"%load_adb_port()
    f.close
    f = open("gui.json","w",encoding="utf-8")
    gui_json = json.dump(maa_cfg_dict,f,indent=2)
save_adb()

```
我写了一小段python代码可以实现吧bluestacks4的adb端口保存到gui.json

**Comment by LmeSzinc** [comment]
蓝叠4hyperv的端口号在注册表 `HKEY_LOCAL_MACHINE\SOFTWARE\BlueStacks_bgp64_hyperv\Guests\Android\Config` 的 `BstAdbPort` 键下

**Comment by MistEO** [comment]
> > 如果 4 没有这个文件的话应该就是没支持了，需要每次手动填一下端口号。
> > 
> > 或者不知道 4 有没有什么其他简单的方法可以获取到端口号的
> 
> 我查了一下，4没有5的conf文件，但是我再"C:\ProgramData\BlueStacks_bgp64_hyperv\Logs\Player.log"里找到一个“2022-10-21 14:15:54.612 10908:00000001 (HD-Player) INFO: 5555 --> 52958. Protocol: TCP”能获取ADB的端口号

这个文件发下看看，等有空我们写下读取的逻辑

**Comment by 617721040** [comment]
[Player.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9843810/Player.log)

每次开启模拟器都会有个这个log
2022-10-19 13:39:46.140 8868:00000001 (HD-Player) INFO: 5555 --> 51187. Protocol: TCP

**Comment by 617721040** [comment]
> 蓝叠4hyperv的端口号在注册表 `HKEY_LOCAL_MACHINE\SOFTWARE\BlueStacks_bgp64_hyperv\Guests\Android\Config` 的 `BstAdbPort` 键下

谢谢，确实可以

**Comment by 617721040** [comment]
> > > 如果 4 没有这个文件的话应该就是没支持了，需要每次手动填一下端口号。
> > > 或者不知道 4 有没有什么其他简单的方法可以获取到端口号的
> > 
> > 
> > 我查了一下，4没有5的conf文件，但是我再"C:\ProgramData\BlueStacks_bgp64_hyperv\Logs\Player.log"里找到一个“2022-10-21 14:15:54.612 10908:00000001 (HD-Player) INFO: 5555 --> 52958. Protocol: TCP”能获取ADB的端口号
> 
> 这个文件发下看看，等有空我们写下读取的逻辑

读这个文件可能会有问题，日志满了以后Player.log会重命名成Player.log1，再去读Player.log会读不出来。
读注册表应该稳定些，我试了下BstAdbPort这个键值确实OK的。
![image](https://user-images.githubusercontent.com/7239754/197328000-7907677f-87d5-4fe0-bf12-9dc59c502dbb.png)

**Comment by MistEO** [comment]
读注册表不会写_(:з」∠)_

逻辑是在 C# 那边，有兴趣的大佬可以研究研究来个 PR

**Comment by 617721040** [comment]
> 读注册表不会写_(:з」∠)_
> 
> 逻辑是在 C# 那边，有兴趣的大佬可以研究研究来个 PR

然而我只是自学了一个月的python，用python倒是很简单的，我托我朋友帮忙写了个C#的，大佬看看能不能用
```
protected string[] GetRegistryValue(string path, string paramName)
        {
            object? value = string.Empty;
            RegistryKey root = Registry.LocalMachine;
            RegistryKey rk = root.OpenSubKey(path);
            if (rk != null)
            {
                value = rk.GetValue(paramName, null);
            }
            return (string[])value;
        }
var value = GetRegistryValue("SOFTWARE\\CVSM", "CVSM");
            var ob = string.Join(',', value.ToList());

            Console.WriteLine("注册表:" + ob);
```
<img width="341" alt="1" src="https://user-images.githubusercontent.com/7239754/197345061-064d9a0d-ff41-4327-b29b-887021185728.png">
