### ISSUE TITLE
自定义基建有时会错误地让菲亚梅塔无法休息

### ISSUE THREAD

**Issue by ShiJi001** [MaaAssistantArknights/MaaAssistantArknights#2372]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

1.在当前宿舍中，如果菲亚梅塔由于心情不满已经被maa自动选择了，然后结束了对所有心情不满的干员的选择，开始在当前宿舍选择信赖不满且心情满的干员，此时会将已经选择了的菲亚梅塔丢弃。

导致菲亚梅塔心情不满，但是在maa任务完成后不在宿舍中休息。

2.如果在前两个宿舍已经将所有应该放进宿舍的干员（心情不满或信赖不满）全部放进去了，则会直接跳过后面两个宿舍，结束任务。

这会导致迷迭香技能所需的【宿舍满员】无法被满足。

3.另外希望自动填充能够加入心情满和信赖满的干员，以满足迷迭香和黑键的基建技能，这个问题之前已经有人反馈过了：https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2247

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9831012/asst.log)

时间为晚上9-10点。

**Comment by MistEO** [comment]
问题 1 似乎可以通过在指定进驻宿舍的干员中加入肥鸭来解决

即：
![image](https://user-images.githubusercontent.com/18511905/197328556-a5e37f96-2509-451e-ba64-f58adbaa7244.png)

**Comment by MistEO** [comment]
全修了
