### ISSUE TITLE
水月肉鸽增设优先刷任务策略

### ISSUE THREAD

**Issue by YuhangTom** [MaaAssistantArknights/MaaAssistantArknights#2376]
### 说说你遇到的问题？

鹰角这次在蚀刻章中加入了`郁金香的谢礼`，获取方式为

> 在集成战略：水月与深蓝之树主题中完成30次地区委托

因为地区委托比第一层必定会出现的诡意行商更加随机，因此更加难刷，这个章子对于懒人来说就非常煎熬了，个人

1. 手动打完波涛迭起7难度（15把左右）
1. MAA诡意行商500投资
1. MAA探索至认知完备

也才做了12次地区委托。

目前MAA会进入地区委托并接委托，但并不会优先去完成，基本是寄了也还没完成委托的样子，投资模式下即使刷到了也会在进入第二层立即放弃探索，导致任务做不完（不确定有没有领取奖励这一步，没见到过）。

### 有什么好的想法？

在`肉鸽设置`-`策略`中添加`优先刷任务`
在各层遇到地区委托（或者是在第一层疯狂刷）时优先进入，并始终选择`点开看似轻松的委托`（现在好像就是这么选的），根据[PRTS地区委托的记录](https://prts.wiki/w/%E6%B0%B4%E6%9C%88%E4%B8%8E%E6%B7%B1%E8%93%9D%E4%B9%8B%E6%A0%91#.E4.BA.8B.E4.BB.B6.E8.8A.82.E7.82.B9)，有以下选项

> 1. 资金储备：累计消耗10源石锭
> 1. 定点清剿：进入1次作战节点
> 1. 探明前路：累计进入2次不期而遇节点
> 1. 发掘人才：累计招募2名新干员
> 1. 住所确认：进入1次安全屋节点
> 1. 虔诚祈祷：使用一次骰子

除了`资金储备`和`住所确认`需要进入不一定在这一层的节点，可以考虑接到它们立刻放弃探索，其他基本都可以在同层做完或者进入第二层随便打两把，完成委托识别到下方任务进度100%并打开领取之后（血泪教训）立刻放弃探索。

**Comment by zzyyyl** [comment]
为什么你用 MAA 刷不了地区委托呢？因为 MAA 根本没做地区委托完成后的确认（

**Comment by YuhangTom** [comment]
~让我康康你的真面目~
~我就知道~
雀食是随便打毕竟1/3 不知道在分支节点有没有优先进地区委托的设定 如果没有的话还是要刷蛮久
