### ISSUE TITLE
龙舌兰肥鸭的替换似乎有问题，要么不运行，要么没有换上心情

### ISSUE THREAD

**Issue by auroralwy** [MaaAssistantArknights/MaaAssistantArknights#2377]
昨天发生这个问题了... 龙舌兰的心情没有换上，但是单独放的话宿舍又放不满，头有点大了

另外问了下群友，也有发生这种情况，要么log都没显示运行，要么log显示换过了然后实际没换成功。
10-18  21:00:00 正在连接模拟器……
10-18  21:00:07 正在运行中……
10-18  21:00:07 开始任务：Infrast
10-18  21:01:15 当前设施：Mfg 0
10-18  21:01:24 红云, 稀音, 帕拉斯
10-18  21:02:05 当前设施：Mfg 1
10-18  21:02:08 食铁兽, 断罪者, 迷迭香
10-18  21:02:21 当前设施：Mfg 2
10-18  21:02:24 清流, 温蒂, 森蚺
10-18  21:02:48 当前设施：Mfg 3
10-18  21:02:51 砾, 斑点, 夜烟
10-18  21:03:14 当前设施：Trade 0
10-18  21:03:24 巫恋, 龙舌兰, 柏喙
10-18  21:03:58 当前设施：Trade 1
10-18  21:04:02 但书, 空弦, 黑键
10-18  21:04:34 当前设施：Control 0
10-18  21:04:41 阿米娅, 琴柳, 凯尔希, 夕, 令
10-18  21:05:11 当前设施：Power 2
10-18  21:05:17 布丁
10-18  21:05:37 当前设施：Office 0
10-18  21:05:42 絮雨
10-18  21:06:00 当前设施：Dorm 0
10-18  21:06:16 当前设施：Dorm 1
10-18  21:06:29 当前设施：Dorm 2
10-18  21:06:41 当前设施：Dorm 3
10-18  21:07:13 完成任务：Infrast
10-18  21:07:13 任务已全部完成！

（龙舌兰那行没执行是为啥）
对比一下之前的：
10-17  21:00:13 正在连接模拟器……
10-17  21:00:13 正在运行中……
10-17  21:00:13 开始任务：Infrast
**10-17  21:00:30 当前设施：Dorm 0
10-17  21:00:37 龙舌兰, 菲亚梅塔
10-17  21:01:06 干员冲突**
10-17  21:01:22 当前设施：Mfg 0
10-17  21:01:31 红云, 稀音, 帕拉斯
10-17  21:02:13 当前设施：Mfg 1
10-17  21:02:17 食铁兽, 断罪者, 迷迭香
10-17  21:02:31 当前设施：Mfg 2
10-17  21:02:35 清流, 温蒂, 森蚺
10-17  21:02:59 当前设施：Mfg 3
10-17  21:03:02 砾, 斑点, 夜烟
10-17  21:03:25 当前设施：Trade 0
10-17  21:03:34 巫恋, 龙舌兰, 柏喙
10-17  21:04:08 当前设施：Trade 1
10-17  21:04:12 但书, 空弦, 黑键
10-17  21:04:46 当前设施：Control 0
10-17  21:04:53 阿米娅, 琴柳, 凯尔希, 夕, 令
10-17  21:05:24 当前设施：Power 2
10-17  21:05:31 布丁
10-17  21:05:51 当前设施：Office 0
10-17  21:05:56 絮雨
10-17  21:06:14 当前设施：Dorm 0
10-17  21:06:27 当前设施：Dorm 1
10-17  21:06:40 当前设施：Dorm 2
10-17  21:06:52 当前设施：Dorm 3
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9815729/asst.log)

10-17  21:07:24 完成任务：Infrast
10-17  21:07:24 任务已全部完成！

_Originally posted by @auroralwy in https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2335#issuecomment-1283146557_

**Comment by Shawnsdaddy** [comment]
为什么要用菲亚梅塔和龙舌兰充能？？？

订单没刷新的时候把龙舌兰换去宿舍，等快刷新再放进去不就好了？？
他技能不是只在订单刷新时生效？？

**Comment by MistEO** [comment]
> 为什么要用菲亚梅塔和龙舌兰充能？？？
> 
> 订单没刷新的时候把龙舌兰换去宿舍，等快刷新再放进去不就好了？？
> 他技能不是只在订单刷新时生效？？
> 

maa 没支持热插拔，不要在这里秀优越

**Comment by auroralwy** [comment]
现在似乎没有什么有效的解决方法，我还是减少班数和手动基建好了

**Comment by MistEO** [comment]
```log
10-18 21:00:07 开始任务：Infrast
10-18 21:01:15 当前设施：Mfg 0
```

这中间卡了一分钟多，不知道卡在哪了，看日志什么都识别不到，后面随便点了一下才往下一步走的。
下次再遇到这种情况帮忙看下卡在哪了

**Comment by auroralwy** [comment]
> ```
> 10-18 21:00:07 开始任务：Infrast
> 10-18 21:01:15 当前设施：Mfg 0
> ```
> 
> 
>      
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9874949/asst.log)

>   
> 
> 这中间卡了一分钟多，不知道卡在哪了，看日志什么都识别不到，后面随便点了一下才往下一步走的。
> 下次再遇到这种情况帮忙看下卡在哪了（最好有图）

复现了，我看着他卡死了，27号的log，九点第一次没运行成功，24分手动运行，然后发现卡在发电站，一直都不动

**Comment by Shawnsdaddy** [comment]
> 

菲亚梅塔和热插拔没啥关系吧
我只是建议他别给龙舌兰充能。

我脚本的逻辑是仅仅 安排 充能干员+菲亚梅塔 2个人，

充完能再把人放回去。

@MistEO 你可以试试这个

**Comment by ABA2396** [comment]
新版本改了肥鸭换班的方式，会先清空宿舍再换人，应该已经没问题了
