### ISSUE TITLE
基建换班出错+刷理智出错

### ISSUE THREAD

**Issue by MigdalBavel** [MaaAssistantArknights/MaaAssistantArknights#2378]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

这样的自动计划，在今天10点的自动执行换班执行到会客室时出错，紧接着1-7自动理智出错。13点定时执行的1-7自动理智出错。
![B3](https://user-images.githubusercontent.com/105539375/197155696-2e7ae2a4-09df-4799-b59e-c7f7b88293c3.png)
![B1](https://user-images.githubusercontent.com/105539375/197155743-5f982698-2de4-4bf4-a4b6-dda419161aa3.png)
![B2](https://user-images.githubusercontent.com/105539375/197155756-c9da371a-4940-4727-84a5-d15a7c532c89.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9837399/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9837401/gui.log)

**Comment by MistEO** [comment]
应该修了，试试测试版
