### ISSUE TITLE
关卡选择多选芯片组

### ISSUE THREAD

**Issue by miku1958** [MaaAssistantArknights/MaaAssistantArknights#2383]
### 说说你遇到的问题？

这几个职业都不是每天都开的，而我又需要刷很多不同职业的， 希望可以多选，有哪个刷哪个
![image](https://user-images.githubusercontent.com/24806909/197315731-4b49be95-46b2-4e3f-9a8a-b1fde5c3f6bf.png)

**Comment by MistEO** [comment]
请使用“备选关卡”功能

**Comment by miku1958** [comment]
原来剩余理智是备选关卡吗... 才发现
