### ISSUE TITLE
希望能增加“暂停上传企鹅物流”的功能

### ISSUE THREAD

**Issue by Yjun233** [MaaAssistantArknights/MaaAssistantArknights#2384]
### 说说你遇到的问题？

在我看来像1-7、资源收集这种关完全没必要再上传了，关闭上传的话还能减少一些企鹅物流的负担。

### 有什么好的想法？

加个暂停上传企鹅物流的按钮。或者也可以做一个关卡黑名单。

**Comment by horror-proton** [comment]
duplicate of #2359

**Comment by MistEO** [comment]
识别和上传本身根本不耗时，这里关掉照样要等这么久。是因为代理指挥时 MAA 为了降低 CPU 占用，不是一直在识别的，识别一帧会等好几秒才进行下次识别，到了掉落界面可能 MAA 还在等时间

**Comment by MistEO** [comment]
企鹅是欢迎我们传的，所以你说的需求不存在
