### ISSUE TITLE
制造站无法正确识别砾的问题

### ISSUE THREAD

**Issue by SKIE1** [MaaAssistantArknights/MaaAssistantArknights#2385]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

1.制造站在换班时，假设砾原先没有在工作，那么maa可以正确识别出砾并加入该制造站。
2.制造站在换班时，假设砾原先已经在工作，那么maa就无法识别出砾，所以最后该制造站就会只剩下夜烟和槐琥。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9843593/asst.log)
2022/10/22 11：30左右

### 截图

![QQ截图20221022124959](https://user-images.githubusercontent.com/51229771/197320428-2c85451b-97cd-40d4-b924-8b2fac21d8a1.png)
自己做的一点测试

**Comment by zzyyyl** [comment]
可以用 candidate

**Comment by Shawnsdaddy** [comment]
@zzyyyl https://github.com/Konano/arknights-mower/blob/main/arknights_mower/utils/character_recognize.py#L68

看看能不能嫖一个

**Comment by cenfusheng** [comment]
模型2022.12重新炼过了，已修复，感谢测试
