### ISSUE TITLE
有关刷投资的肉鸽战斗结束之后拿什么的建议

### ISSUE THREAD

**Issue by SSLTJH** [MaaAssistantArknights/MaaAssistantArknights#239]
其实个人觉得还是拿钱就够了。
毕竟只是刷投资，速度肯定越快越好，而且开局的人已经够打一层，没有必要再选人。
而且也可以避免因为拿剧目卡死造成的bug。

**Comment by wb871029** [comment]
多余的钱随机买商品开图鉴
