### ISSUE TITLE
基建训练室优化建议

### ISSUE THREAD

**Issue by GoldenShit233** [MaaAssistantArknights/MaaAssistantArknights#2391]
### 说说你遇到的问题？

在设置
- “基建工作心情阈值”为**30%**（默认）
- “不将已进驻的干员放入宿舍”为**否**（默认）
- “宿舍空余位置蹭信赖”为是（应当与本issue无关）
- 左侧开关（含**宿舍**）全部**勾选**（默认）
- 不启用“自定义基建配置”

的情况下，会将心情较低的下班的**艾丽妮自动放到宿舍休息**，而不是留在训练室等着专精二、三。
同时，目前版本（v4.6.4）我并**没有**找到跟训练室相关的外层设置控件。
具体界面见下↓
[![xg3jzQ.png](https://s1.ax1x.com/2022/10/22/xg3jzQ.png)](https://imgse.com/i/xg3jzQ)

### 有什么好的想法？

首先，是否可以在左侧开关加入对训练室的单独控制；
其次，建议（最好在不使用自定义基建配置的基础上（_属实是懒狗了_））新增一个设定自动专精的列表，具体功能如下：
1. 在材料充足的情况下自动专精列表中干员；
2. 在材料不足的情况下跳过任务；
3. 若开启该功能，则在“Link Start！”之后弹出提示窗询问是否准备完毕素材；
4. 提示内容最好加上相应专精材料的计算；
5. 如果能够和仓库识别beta联合那就更好了。

最后，治标不治本但是很迫切的，**给艾丽妮加个默认的特判吧**。

**Comment by zzyyyl** [comment]
艾丽妮的问题很早就讨论过了，把 `不将已进驻的干员放入宿舍` 打开就行（

**Comment by GoldenShit233** [comment]
是的，我看到了，但是“不将已进驻的干员放入宿舍”与“宿舍空余位置蹭信赖”等功能之间存在冲突，相关问题与#2362类似。
主要还是希望能够进一步完善优化训练室相关功能，如果真能有“自动专精列表”之类的新增功能，那就更好了。

**Comment by mouyuu** [comment]
> 艾丽妮的问题很早就讨论过了，把 `不将已进驻的干员放入宿舍` 打开就行（

问个问题，打开`不将已进驻的干员放入宿舍`会不会影响龙舌兰组使用菲亚梅塔

**Comment by ABA2396** [comment]
> > 艾丽妮的问题很早就讨论过了，把 `不将已进驻的干员放入宿舍` 打开就行（
> 
> 问个问题，打开`不将已进驻的干员放入宿舍`会不会影响龙舌兰组使用菲亚梅塔

不会
