### ISSUE TITLE
请求在勾选<设置-界面设置-手动输入关卡名>后，保留刷理智的关卡选择的下拉框（调整为修改每日关卡提示

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#2395]
### 说说你遇到的问题？

芯片本、红票本老是记不得要刷的叫啥，每次都得去设置里调一下或者去游戏里瞅一眼
或者在悬浮提示里面补上这些？可能是最简单的实现，但是会让那玩意变的臃肿

**Comment by ABA2396** [comment]
这玩意不太好改，之前做材料选择的可输入下拉框的时候就一堆问题（现在还有问题），加悬浮提示的话列表里的关卡又太多了

**Comment by status102** [comment]
> 这玩意不太好改，之前做材料选择的可输入下拉框的时候就一堆问题（现在还有问题），加悬浮提示的话列表里的关卡又太多了

![image](https://user-images.githubusercontent.com/102887808/197379907-bb26b98d-e434-4b15-88dc-90317a2a7dce.png)
那下面这个方便加点么，比如
```
钱本 CE
奶/盾芯片 PR-A
```
剿灭比较长Annihilation，没法复制的话可能稍微麻烦一点。或者支持一下特定关卡的中文名？"剿灭"、"钱本"、"龙门币"

**Comment by ABA2396** [comment]
> > 这玩意不太好改，之前做材料选择的可输入下拉框的时候就一堆问题（现在还有问题），加悬浮提示的话列表里的关卡又太多了
> 
> ![image](https://user-images.githubusercontent.com/102887808/197379907-bb26b98d-e434-4b15-88dc-90317a2a7dce.png) 那下面这个方便加点么，比如
> 
> ```
> 钱本 CE
> 奶/盾芯片 PR-A
> ```
> 
> 剿灭比较长Annihilation，没法复制的话可能稍微麻烦一点。或者支持一下特定关卡的中文名？"剿灭"、"钱本"、"龙门币"

![image](https://user-images.githubusercontent.com/99072975/197382004-e5f962e6-66d4-4ab5-b623-8afd1c3e12af.png)
改成了这样，剿灭不是还有全权委托吗.jpg

**Comment by ABA2396** [comment]
8aadb7b0f5c08642147688078de535e719d22692 fixed
