### ISSUE TITLE
希望增加暂停执行的功能

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#2396]
### 说说你遇到的问题？

- 有时候刷关的时候想看看当前某材料有多少，又不想造成模拟器识别错误
- 有时候在访问好友的时候看到有好友申请，想暂停去看看
- ...
<br>
概括起来，就是在执行过程中对某个东西突然感兴趣
<br>
但是点击停止再开始，有部分任务会直接重新开始，浪费挺多时间（比如基建换班）

### 有什么好的想法？

增加个暂停键，把进程挂起，并且可以手动继续
（或许可以增加一个超时自动结束，以防止忘了关此功能造成长期占用）

### 其他内容

-

**Comment by zzyyyl** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/discussions/2091

**Comment by MistEO** [comment]
不好弄，首先是架构本身不好做。其次是，即使暂停恢复，也必须回到原来的位置，差一点都不行，可能会带来很多 bug。

举个例子基建干员列表里滑动识别，你暂停了。点出去弄别的了，过一小会再点回来，1. 干员列表的位置不可能和原先完全一样，一点的偏差可能导致后面的识别全错。2. 可能你过了几十分钟甚至更长时间才回来，干员心情、工作状态等全变了，导致前面识别的后续选了心情不满的干员；或者之前识别到这个干员心情是 1 ，现在红了压根列表中查无此人，导致后续的错误

**Comment by KJH-x** [comment]
> 不好弄，首先是架构本身不好做。其次是，即使暂停恢复，也必须回到原来的位置，差一点都不行，可能会带来很多 bug。
> 
> 举个例子基建干员列表里滑动识别，你暂停了。点出去弄别的了，过一小会再点回来，1. 干员列表的位置不可能和原先完全一样，一点的偏差可能导致后面的识别全错。2. 可能你过了几十分钟甚至更长时间才回来，干员心情、工作状态等全变了，导致前面识别的后续选了心情不满的干员；或者之前识别到这个干员心情是 1 ，现在红了压根列表中查无此人，导致后续的错误

emmm，您陈述的这些问题都是集中在同一个方面，就是遇到选择干员的这个界面，那我想问能不能在不包含选择干员的见面有暂停的功能呢，我在最初的问题表述中也没有包含选择干员的项目（挂机和访问，主要是挂机）。我的设想是可以在能接受暂停的时候使暂停键可用，遇到包含选择干员这样无法处理的复杂事件就不允许暂停。谢谢
