### ISSUE TITLE
疑似运行过久挤占内存

### ISSUE THREAD

**Issue by JelwisForever** [MaaAssistantArknights/MaaAssistantArknights#2398]
### 说说你遇到的问题？

版本maa4.6.4
模拟器：蓝叠国际
硬件：16g内存
![屏幕截图 2022-10-23 113428](https://user-images.githubusercontent.com/52448972/197372185-2e6e58f3-df6f-4fcd-824c-1bcbb77245ae.png)
软件：仅开启浏览器，一个邮箱页面
问题:自动肉鸽，运行一段时间后，模拟器界面会有卡顿现象，关闭maa后，界面恢复正常
可能原因：运行过久，maa刷取记录挤占内存；
![屏幕截图 2022-10-23 113110](https://user-images.githubusercontent.com/52448972/197372089-447d25ce-438c-426d-8758-014436e48255.png)
![屏幕截图 2022-10-23 113205](https://user-images.githubusercontent.com/52448972/197372099-2de15d7c-fa70-4109-a374-dae51e4e001a.png)

**Comment by IT-amateur** [comment]
我这几天通宵挂机肉鸽，也是有卡顿这个问题，但是内存等资源占用也没特别离谱，睡觉前几个小时都挺正常的，但是早上检查的时候就发现蓝叠国际版模拟器卡死了，MAA也是没反应，但有一次很神奇，模拟器卡的死死地，MAA还在正常刷，至少gui.log上是在正常跳动，很难总结出是什么问题

**Comment by MistEO** [comment]
你看看内存是谁占的就好了
