### ISSUE TITLE
自动肉鸽的可每日

### ISSUE THREAD

**Issue by zxmydmug** [MaaAssistantArknights/MaaAssistantArknights#2399]
### 说说你遇到的问题？

每天挂机的时候需要再点击一下自动肉鸽

### 有什么好的想法？

可不可以就设定一个键，把自动肉鸽也包括进每日

### 其他内容

maa支持多开吗？

**Comment by ABA2396** [comment]
1. 我们认为一般用户是没有每天刷肉鸽的需求的，所以全选按钮是排除了肉鸽的选择，且关闭之后不会保存肉鸽的勾选状态（所有带星号选项的都是如此）
2. 多开可以将maa本体复制多份并分别手动设置连接的端口，或者尝试[新ui](https://github.com/MaaAssistantArknights/MaaAsstElectronUI/releases)
