### ISSUE TITLE
掉线重连设置

### ISSUE THREAD

**Issue by Zirun-wang** [MaaAssistantArknights/MaaAssistantArknights#2401]
### 说说你遇到的问题？

多设备同账号登录互相挤下线的问题

### 有什么好的想法？

最简单的办法：三个选项手动选择
1) 自动重连
2) 延迟x分钟后重连(比如电脑在挂机，手机换基建)
3) 不重连

进阶版：识别错误类型，自动选择对应操作
1) "登录认证已失效，请重新登录" - 被顶号，不重连或延时重连
2) 其它错误 - 自动重连

**Comment by Shawnsdaddy** [comment]
可以自行设置重连时间，具体可以参考 #2228

**Comment by Zirun-wang** [comment]
> 可以自行设置重连时间，具体可以参考 #2228

不是很清楚为何close此issue，这和肉鸽自动重连并不是完全相同的需求，而且对于一般用户来说直接修改配置文件显然算不上易用。

**Comment by Shawnsdaddy** [comment]
> > 可以自行设置重连时间，具体可以参考 #2228
> 
> 不是很清楚为何close此issue，这和肉鸽自动重连并不是完全相同的需求，而且对于一般用户来说直接修改配置文件显然算不上易用。

重连用的是相同的task你只要改相同的位置就好了
