### ISSUE TITLE
拿到时光之末藏品导致自动肉鸽停止

### ISSUE THREAD

**Issue by chaoshengyoo** [MaaAssistantArknights/MaaAssistantArknights#2402]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在挂傀影肉鸽时发现的，挂到一半发现不动了，发现是拿到时光之末藏品以后卡在重新进入的页面，水月肉鸽没有碰到过

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9846068/asst.zip)
大概两点到四点的样子，后来很久才想起来反馈...

**Comment by MistEO** [comment]
`debug/roguelike/` 下有错误截图，发下看看

**Comment by chaoshengyoo** [comment]
> `debug/roguelike/` 下有错误截图，发下看看

复活后在这个界面就没有任何操作了
![2022-10-27_02-41-28 620_raw](https://user-images.githubusercontent.com/111118064/198266157-3f65319a-381e-459c-bb60-112aa0e22d60.png)
![image](https://user-images.githubusercontent.com/111118064/198266260-226933c4-d25e-4ff4-89cc-7c8b576618ed.png)
这是今天早上的，又拿到了时光之末，打到第九把之后就停了

**Comment by MistEO** [comment]
测试版修了
