### ISSUE TITLE
日服無法刷理智

### ISSUE THREAD

**Issue by jack61714z** [MaaAssistantArknights/MaaAssistantArknights#2403]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如題

選擇刷理智指定關卡下
會進行程序直到主線畫面後停止

若關卡選擇當前/上次
只會進行到關卡儀表板

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9846070/asst.log)

### 截图

![Snipaste_2022-10-23_16-57-48](https://user-images.githubusercontent.com/81425477/197383540-b0bd2ec2-4778-42c8-8cf7-0fc21e70aefd.png)

**Comment by wallsman** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/resource/global/YoStarJP/readme.md

>刷理智（仅支持选择当前关卡）
