### ISSUE TITLE
建议自动公招增加TAG多选功能降低公招被划概率

### ISSUE THREAD

**Issue by holyluna620** [MaaAssistantArknights/MaaAssistantArknights#2410]
### 说说你遇到的问题？

粥游的TAG是有被划的概率的，如果高星TAG被划，大概率出3星干员，造成收益降低。

### 有什么好的想法？

在识别和选择公招TAG时，如果同时有多组TAG可出高星干员，则尽量选择更多的TAG（或至少选择两组TAG），从而在某一个TAG被划掉时依然保证能出高星。

例如：
TAG：近卫 先锋 治疗 快速复活 重装

识别结果：
4X TAG 快速复活
4X TAG 先锋+治疗

目前公招会直接选择 “快速复活”进行招募，但单TAG有一定概率被划。

如果选择“快速复活”+“先锋”+“治疗”，一般不会全部都划掉，这样可以保证获取4星干员。

例外：
如果有某一TAG能保证5星，而剩下TAG组合最高只有4星时，应只选择5星TAG，而不是4星5星TAG均选择。

例如：
TAG：控场 快速复活 近卫 先锋 治疗

识别结果：
5X TAG :控场
5X TAG :控场+快速复活
5X TAG :控场+先锋
4X TAG 快速复活
4X TAG 先锋+治疗

其中有效的最高星TAG仅为控场，我认为此时单TAG控场是最优解。（如果选多个不冲突的TAG不提高其中单一TAG的被划概率，则最优应为控场+快速复活，保证控场TAG被划时也通过快速复活能确保有4星。）

**Comment by zzyyyl** [comment]
“快速复活”+“先锋”+“治疗”：
~“快速复活”~ ~“先锋”~ “治疗”
~“快速复活”~ “先锋” ~“治疗”~

**Comment by holyluna620** [comment]
> “快速复活”+“先锋”+“治疗”： ~“快速复活”~ ~“先锋”~ “治疗” ~“快速复活”~ “先锋” ~“治疗”~

我个人没有碰到这样的情况，而且也有诸如“快速复活”+“特种”这种。
