### ISSUE TITLE
hyper-v蓝叠无法正常连接

### ISSUE THREAD

**Issue by dv3lood** [MaaAssistantArknights/MaaAssistantArknights#2411]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

从昨天开始便无法正常连接，蓝叠与MAA均未更新过，重启电脑后仍无法连接。而后尝试更新MAA也并未解决此问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9849208/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9849224/asst.bak.log)

### 还有别的吗？

使用的hyper-v蓝叠5 win11

**Comment by MistEO** [comment]
看着像是没开蓝叠的 adb 调试？

**Comment by dv3lood** [comment]
哦哦，不好意思，确实是因为这个原因
