### ISSUE TITLE
关于自动肉鸽中奇怪的干员放置

### ISSUE THREAD

**Issue by BalanceSteelyard** [MaaAssistantArknights/MaaAssistantArknights#2413]
### 说说你遇到的问题？

忘了是哪个关卡了，此刻背包里有拉普兰德280，玫兰莎155，法华琳160，阿米娅170，预备干预近战和预备干员法术。费用是完全充足的，足够放下拉普兰德和阿米娅或者换成法华琳，脚本却把堵蓝门的位置放了预备干员近战和法华琳，随后把主要输出玫兰莎和拉普兰德放在了打不到什么人的地方直接让预备干员被冲烂，然后把预备干员法术和阿米娅放到了没有奶的位置送掉了，最后蓝大门畅通无阻漏怪失败。

**Comment by zzyyyl** [comment]
这种东西不带上关卡名和日志说了等于没说
