### ISSUE TITLE
刷理智任务经常失败 [Skip label]

### ISSUE THREAD

**Issue by RyanSaul** [MaaAssistantArknights/MaaAssistantArknights#2414]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

大概从 v4.6.4 开始，使用 MAA 刷理智（前面的任务包括自定义基建换班）时会经常性在「刷理智」这项任务上失败，模拟器中观察到的情况是开始刷理智任务时先进入了终端页面，然后停了1分钟左右，之后在 log 里显示刷理智任务失败。若单独勾选「刷理智」任务时则不会出现问题。更新至 v4.6.5-beta.1 后问题依旧出现。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9850148/asst.log)
开始战斗任务：16:14:56
战斗任务失败：16:15:45

### 截图

![uTools_1666599982729](https://user-images.githubusercontent.com/16830734/197482240-57a3892c-184c-414b-8b5e-72ca75018f66.png)

### 还有别的吗？

模拟器：蓝叠5国际版（hyper-v）
操作系统：Windows 11 Insider Preview 25227（22H2）

**Comment by zzyyyl** [comment]
你这选的剿灭？那估计是你剿灭打完了

**Comment by RyanSaul** [comment]
刚刚发现了……但问题还是存在的，正在重试

**Comment by RyanSaul** [comment]
本次任务依旧是在「基建换班」后跟随「刷理智」任务时任务失败，表现为未进入终端界面，直接跳到了下一个任务「自动公招」并打开了公招界面，log里显示「任务出错」

![uTools_1666602102804](https://user-images.githubusercontent.com/16830734/197489826-b39092aa-2f83-4740-9af5-77cff647e182.png)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9850357/asst.log)

开始战斗任务：16:58:29
战斗任务失败：16:58:42

**Comment by zzyyyl** [comment]
能否帮忙测测 `上次作战` 会不会出同样的问题？

**Comment by zzyyyl** [comment]
嘶，是不是基建退出的返回时间比较长？那个中间有个三角形的加载画面

**Comment by zzyyyl** [comment]
![Screenshot_20221024-174916](https://user-images.githubusercontent.com/74587068/197499499-4291f322-39a8-4de8-a70d-4580f2d4608d.png)

**Comment by RyanSaul** [comment]
刚刚测试了一下，当前/上次 依然会出现问题
基建退出的时间确实较长，大概有4~5s，而「刷理智」任务在基建退出的返回界面时就已经开始了
