### ISSUE TITLE
水月肉鸽突击战术分队优先抓取随机直升

### ISSUE THREAD

**Issue by YuhangTom** [MaaAssistantArknights/MaaAssistantArknights#2417]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

之前在issue #2408 中写了

> 发现突击战术分队随机直升并没有优先抓取 或许是因为抓取顺序固定？
> 第一张近卫券抓了170羽毛笔之后 第二张券随机直升了290棘刺 抓了180百炼嘉维尔 然后接下来的第三张抓了180棘刺
> 可以在有随机直升的时候优先考虑随机直升 尤其是对于之后要抓的干员

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9852910/asst.log)

### 还有别的吗？

MAA-v4.6.5-beta.1-win-x64
MuMu 2.7.4.0 (x86) (20220901103627)

**Comment by WWPXX233** [comment]
目前来说是按照一定的选取优先级来的
如果当前直升的干员正好是所需要的那回去拿 随机直升的不稳定性还是太难控制了 建议选择以人为本分队
