### ISSUE TITLE
没有剿灭扫荡券时prts自动代理一次之后会出现错误导致任务提前完成

### ISSUE THREAD

**Issue by qianren367** [MaaAssistantArknights/MaaAssistantArknights#2422]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

设置刷理智，没有扫荡券时，prts代理指挥一次之后会出现任务出错提示，导致提前结束任务（如p1）
模拟器界面如图所示（p2）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9853646/asst.log)
[2022-10-24 23:12:48]

### 截图

![image](https://user-images.githubusercontent.com/116583630/197579508-dab3826d-3e39-49f9-8250-2792bcb5cbc2.png)
![Screenshot_20221024-234614](https://user-images.githubusercontent.com/116583630/197579742-ae41f3c9-5892-4560-a80e-d0b4705b9ab2.png)

### 还有别的吗？

模拟器：夜神模拟器

**Comment by zzyyyl** [comment]
看来 71135979d86602eaac12108dda7c566bc9dd1921 还不行，等我有空再换换
