### ISSUE TITLE
MAA最小化后自动退出

### ISSUE THREAD

**Issue by YuhangTom** [MaaAssistantArknights/MaaAssistantArknights#2423]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

MAA最小化后从任务栏消失了，去右下角托盘里找，发现MAA图标的那一瞬间它自己消失了，自动肉鸽正打到一半，不知道是General的问题还是肉鸽的问题，第一次遇到。重新打开新的MAA session是没有连接的最初模样。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9853814/asst.log)

### 还有别的吗？

MAA-v4.6.5-beta.1-win-x64
MuMu 2.7.7.0 (x86) (20220927142932)

**Comment by zzyyyl** [comment]
不出意外的话这是 GUI 的问题，来个 gui.err.log 看看（？

**Comment by zzyyyl** [comment]
另外感觉这个 bug 可能跟 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2379 有些关系。 @gdlcf88

**Comment by gdlcf88** [comment]
请 @YuhangTom 协助提供 GUI 的日志或重现方法。

**Comment by gdlcf88** [comment]
我的本机无法重现问题。

https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/2400 已合并，对 GUI 主窗体做了统一管理。编译此PR合并后的版本，或等待 v4.6.5-beta.2 版本发行后，情况可能还会有变化。

**Comment by YuhangTom** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9854508/gui.log)
没有找到 gui.err.log 捏 具体是出现在10-24  11:58:30没有完成战斗并消失 我也是第一次出现这个问题来着 而且我现在发现我的设置并没有选最小化隐藏到托盘 所以感觉是MAA直接崩了然后无了

**Comment by MistEO** [comment]
试试新版本还这样么？

**Comment by YuhangTom** [comment]
好的 我试试再挂挂

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。

Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
