### ISSUE TITLE
请问 自动更新的压缩包下载到什么路径了   4.64版本进水月肉鸽反复在主界面切换 

### ISSUE THREAD

**Issue by gguardians2** [MaaAssistantArknights/MaaAssistantArknights#2424]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

请问 自动更新的压缩包下载到什么路径了 如何关闭自动更新  4.64版本进水月肉鸽反复在主界面切换 

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9854888/asst.log)

**Comment by KiyuM1n** [comment]
1.直接下載到MAA路徑
2.設定可以關閉自動更新
3.將水月肉鴿釘選應該可以解決

**Comment by gguardians2** [comment]
> 1.直接下载到MAA的路径 关闭压缩档写着OTA的2.设置可以自动更新 3.将水月肉鸽子钉选应该可以解决
没想到这么晚也能得到回复 自己尝试了用笨办法解决了 拔网线 删除新版本重新解压460版本打开然后关闭自动下载

**Comment by gguardians2** [comment]
想不到这么晚也能得到回复 感谢 自己用笨办法解决了 拔网线删除新版本 重新解压460版本打开然后关闭自动下载  另外请教一下  用mumu模拟器多开 如何设置使用 同一个 adb 及 不同的 adb 地址 来进行连接后操作？

**Comment by zzyyyl** [comment]
#2425
