### ISSUE TITLE
请教一下 用mumu模拟器自带的多开是否可以同时自动刷图  如何设置不同adb？

### ISSUE THREAD

**Issue by gguardians2** [MaaAssistantArknights/MaaAssistantArknights#2425]
### 说说你遇到的问题？

请教一下 用mumu模拟器自带的多开是否可以同时自动刷图  如何设置不同adb？

**Comment by MistEO** [comment]
mumu 用不了多开，他的多开 adb 地址全是同一个。换模拟器吧

**Comment by gguardians2** [comment]
那 可以换哪些呢？

MistEO ***@***.***> 于2022年10月25日周二 11:44写道：

**Comment by ntgmc** [comment]
夜神 逍遥 雷电（非常不推荐）都可以
