### ISSUE TITLE
bilibili服隐私政策更新提示无法识别

### ISSUE THREAD

**Issue by BiologyHazard** [MaaAssistantArknights/MaaAssistantArknights#2426]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [ ] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

startup模块中，如遇到游戏开屏画面bilibili服隐私政策更新的提示，则会卡住。
希望可以自动点击“同意”

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9856322/asst.log)

**Comment by MistEO** [comment]
来个卡住的图看看啥样的（需要模拟器自带的截图工具截一下原图）

**Comment by BiologyHazard** [comment]
等下次遇到了我截一下图，这个不是每次都会出现的

**Comment by zzyyyl** [comment]
你是说 `BServerPrivacyPolicy.png` ![BServerPrivacyPolicy.png](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/resource/template/BServerPrivacyPolicy.png?raw=true)么？这玩意我之前改好多次了，好像它大小会变......

**Comment by MistEO** [comment]
> 你是说 `BServerPrivacyPolicy.png` ![BServerPrivacyPolicy.png](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/resource/template/BServerPrivacyPolicy.png?raw=true)么？这玩意我之前改好多次了，好像它大小会变......
> 
> [1ff20bf](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1ff20bf31cd2daaad2ecbcc825965e856fdcd60e)

OCR！

**Comment by zzyyyl** [comment]
OCR 万一其他界面也有个”同意“，可能会串（确信

**Comment by MistEO** [comment]
> OCR 万一其他界面也有个”同意“，可能会串（确信

那做俩，一个识别点协议内容，他的 next 才是 “同意”

**Comment by BiologyHazard** [comment]
大小会变是不是因为这个的大小跟模拟器的dpi相关？
为啥会串，只有当出现“隐私”的时候才是这个页面吧

**Comment by IT-amateur** [comment]
> 你是说 `BServerPrivacyPolicy.png` ![BServerPrivacyPolicy.png](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/resource/template/BServerPrivacyPolicy.png?raw=true)么？这玩意我之前改好多次了，好像它大小会变......
> 
> [1ff20bf](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1ff20bf31cd2daaad2ecbcc825965e856fdcd60e)
![Screenshot_2022 10 26_17 06 31 457](https://user-images.githubusercontent.com/49528044/197984573-6ac24240-e1ad-4288-8d9b-cda7eb56bc9f.png)
我遇到的Bilibili隐私协议是这样的，安装完B服第一次登录的时候出现的

**Comment by BiologyHazard** [comment]
> > 你是说 `BServerPrivacyPolicy.png` ![BServerPrivacyPolicy.png](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/resource/template/BServerPrivacyPolicy.png?raw=true)么？这玩意我之前改好多次了，好像它大小会变......
> > [1ff20bf](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1ff20bf31cd2daaad2ecbcc825965e856fdcd60e)
> > ![Screenshot_2022 10 26_17 06 31 457](https://user-images.githubusercontent.com/49528044/197984573-6ac24240-e1ad-4288-8d9b-cda7eb56bc9f.png)
> > 我遇到的Bilibili隐私协议是这样的，安装完B服第一次登录的时候出现的

我说的卡住的那个界面不是这个诶（
我遇到的界面是bilibili游戏的隐私提示，您这个页面应该是方舟的隐私政策。

**Comment by zzyyyl** [comment]
@BiologyHazard 来张隐私政策确认界面的截图呗

**Comment by BiologyHazard** [comment]
> @BiologyHazard 来张隐私政策确认界面的截图呗

<img width="960" alt="Snipaste_2022-10-27_13-16-34" src="https://user-images.githubusercontent.com/44924110/198419015-10bdd718-ca62-439b-8eb3-ec110db13c34.png">
抱歉不是用模拟器的截图工具截的，但是分辨率没有改，是1920x1080，所以应该效果一样？

**Comment by BiologyHazard** [comment]
这个页面的大小可能和模拟器的dpi有关

**Comment by BiologyHazard** [comment]
已经修复了？

**Comment by MistEO** [comment]
本来是修了，但我们讨论了一下，用户协议有法律风险，不准备帮用户点。回滚了

**Comment by LoserFeng** [comment]
那是否可以在MAA设置里放这样一个开关，选择是否自动同意呢，开关默认关闭，这样行吗QAQ(**如果不行直接无视该issue即可**)
