### ISSUE TITLE
`v4.6.5-beta.1` 无法水月肉鸽

### ISSUE THREAD

**Issue by miku1958** [MaaAssistantArknights/MaaAssistantArknights#2428]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

只勾选水月肉鸽， 也在肉鸽页面里，但没有反应， 隔了一段时间就直接结束了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9857082/asst.log)

**Comment by zzyyyl** [comment]
看上去是资源出问题了，重新下一个吧）

**Comment by miku1958** [comment]
还是不行，我只保留gui.json，然后下载了MAAComponent-Dependency-v4.6.5-beta.1-win-x64.zip和MAA-v4.6.5-beta.1-win-x64.zip和一次解压覆盖

**Comment by zzyyyl** [comment]
看看你的 `resource\tasks.json`

**Comment by zzyyyl** [comment]
是你的gui.json是旧版的文件，
![image](https://user-images.githubusercontent.com/74587068/197711602-3b1879f2-aaea-4ceb-9c31-bc507646be58.png)
这里的肉鸽主题自己重新选一下

**Comment by miku1958** [comment]
ok好了, 谢谢 @zzyyyl
