### ISSUE TITLE
基建方面的疑问

### ISSUE THREAD

**Issue by G111ThUb** [MaaAssistantArknights/MaaAssistantArknights#2429]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在基建换班中，首先maa会一直点击源石碎片制造站的龙门币标识，而不是换人，点到一定次数后就会转到下一个制造站去。还有就是在办公室的时候一直识别不到我想选的干员也就是伊桑，一直在寻找干员

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9857202/asst.log)

### 截图

![捕获22](https://user-images.githubusercontent.com/116619464/197686056-16a76c7d-0213-45cb-8a6a-fd2a5e285d04.PNG)

### 还有别的吗？

模拟器是mumu，操作系统Windows

**Comment by MistEO** [comment]
> 修复 基建 搓玉补货后不换人的问题

前一个问题，beta 版本修过了

**Comment by MistEO** [comment]
后一个问题，你的截图是 `22:50:46` 才开始仅办公室的，但是你发的日志到 `22:50:40` 就结束了，下次再遇到再发下

**Comment by G111ThUb** [comment]
好的，多谢了

**Comment by G111ThUb** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9876187/asst.log)
