### ISSUE TITLE
界面设置中切换是否手动输入关卡后，无法选择指定材料选项

### ISSUE THREAD

**Issue by starwhite-requim** [MaaAssistantArknights/MaaAssistantArknights#2431]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

刷完1-7后想刷干员的晋升材料，于是在界面设置中切换到了手动输入关卡，勾选后，无法再选择指定材料这一选项，不管选择什么材料都会跳回到不选择，重新启动MAA后可以正常选择，但取消勾选后再次出现了无法指定材料的情况

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9859146/asst.log)
时间大概是下午5点20分之后

### 截图

![Snipaste_2022-10-25_17-50-26](https://user-images.githubusercontent.com/55050479/197742306-30954c12-838d-4a1e-bd66-d1a8be408bb4.png)

### 还有别的吗？

MUMU模拟器 B服

**Comment by ABA2396** [comment]
#2354 重启试试
