### ISSUE TITLE
水月肉鸽在作战中不摆放干员，并且在肉鸽中内存占用会异常升高

### ISSUE THREAD

**Issue by Toyro7356** [MaaAssistantArknights/MaaAssistantArknights#2432]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽中从第一关就不摆放干员，这个问题已经出现一段时间，在之前某个版本中提及修复肉鸽摆烂bug上一个版本开始，至今没有解决；尝试过重新安装MAA。
在肉鸽进入作战加载地图的过程中，我发现内存16g会被吃满，有一定概率会出现卡死，资源管理器自动重启。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9859774/asst.log)
时间大约为2022/10/25 19:13

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。

Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.

**Comment by horror-proton** [comment]
我不大明白这是什么情况, 不会是 `run` 那里递归没退出吧, @MistEO

**Comment by zzyyyl** [comment]
@horror-proton 我觉得这里的一长串 screencap 是正常的识别肉鸽关卡名，在黑屏的时候反复截图直到关卡名出来为止
至于为什么内存吃完，大概是之前说的 gzip 内存泄漏的问题（？

**Comment by horror-proton** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10029619/asst.log)

好像确实是这个原因, 我这里可以复现 (并且也迅速吃完了内存)
应该防止这种没有时间间隔的连续截图
~~并且应该在内存泄漏解决之前禁用 gzip 截图~~

**Comment by horror-proton** [comment]
![image](https://user-images.githubusercontent.com/107091537/202403639-6c615986-6af2-4932-a36b-6442498ddd9d.png)
