### ISSUE TITLE
对3.5感谢庆典的适配

### ISSUE THREAD

**Issue by 134820134820** [MaaAssistantArknights/MaaAssistantArknights#2433]
### 说说你遇到的问题？

3.5感谢庆典会有每日的合成玉领取活动还有每日免费一抽,能否在活动上线后增加相应的识别,以便全自动的玩家也不至于浪费

### 有什么好的想法？

可以额外加一个选项或者放唤醒里

**Comment by MistEO** [comment]
抽卡都要脚本抽这游戏还玩个啥.jpg

**Comment by 134820134820** [comment]
> 抽卡都要脚本抽这游戏还玩个啥.jpg

确实是这个道理..就怕太忙没时间登,属于是亏麻,错一个月玉都补不回来没领的
或者说抽卡没必要,但活动的合成玉能领一下

**Comment by ChildeRolando** [comment]
可露希尔是吧（
