### ISSUE TITLE
国际服maa无法进行刷理智任务

### ISSUE THREAD

**Issue by xzqiu0803** [MaaAssistantArknights/MaaAssistantArknights#2434]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [x] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我是个双服玩家，玩的b服和国际服。在我挂完b服后我切换启动国际服maa后选择首次尝试自动刷理智。
原以为会和b服一样能顺利启动，但看着国际服响应了很久后还是没进行任务。再不久就出现任务出错的提示。我也不知道是怎么了，启动客户端也是选的国际服英文版。希望开发组能帮忙看看。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9860784/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/116652638/197788121-63b8313c-b834-4a2d-835e-82dd2bf8b4e0.png)

### 还有别的吗？

用的是夜神模拟器，因为蓝叠模拟器我没法编辑文件夹。
之所以需要编辑文件夹是因为可以把我手机上的应用数据直接传到电脑上就不需要浪费时间再下载了。

**Comment by zzyyyl** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/resource/global/YoStarEN/readme.md#%E5%9B%BD%E9%99%85%E6%9C%8D%E7%BE%8E%E6%9C%8D
