### ISSUE TITLE
关于肉鸽刷源石锭功能的优化建议

### ISSUE THREAD

**Issue by alskdjasld** [MaaAssistantArknights/MaaAssistantArknights#2436]
### 说说你遇到的问题？

选取干员的时间太长，导致整体刷取效率低下

### 有什么好的想法？

建议将**源石锭** 和 刷**肉鸽等级**两个功能分开。
源石锭功能可以尝试单核通过第一层，战斗关卡遇到的招募券全部选择放弃。能够大幅度加快整体进程。

**Comment by ntgmc** [comment]
都是刷，时间成本加一点没关系吧
