### ISSUE TITLE
仓库识别错误

### ISSUE THREAD

**Issue by yd278** [MaaAssistantArknights/MaaAssistantArknights#2437]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

仓库识别中将[技巧概要·卷2]44件识别为0件

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9862913/asst.log)

### 截图

[depot.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9862923/depot.zip)

### 还有别的吗？

要不要考虑新开一个issue或者discussion专门收集仓库识别错误的反馈呢（趴

**Comment by MistEO** [comment]
之前有 PR 专门重写了匹配算法，如果还有问题请再提个 issue，谢谢~
