### ISSUE TITLE
请求添加新功能

### ISSUE THREAD

**Issue by fastboot-rec** [MaaAssistantArknights/MaaAssistantArknights#244]
请求作者大大能够添加模拟器多设备同时控制，这样就能同时开两个号进行挂机了。我现在都是控制一个，换另一个还要自己配置一下文件，好麻烦啊ಥ‿ಥ
还有啊，就是能不能添加肉鸽自选干员的图形界面，我按着教程改文件却不行ಥ‿ಥ
希望作者大大看到能回复，谢谢啦(◍•ᴗ•◍)❤

**Comment by MistEO** [comment]
你可以把文件夹复制一份，手动多开2333

**Comment by MistEO** [comment]
肉鸽自选干员的图形界面，应该是咕咕了（

不行的话具体说下什么现象，发个日志康康
