### ISSUE TITLE
会客室领取每日线索放在了送线索前

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaAssistantArknights#2440]
### 说说你遇到的问题？

会客室领取每日线索放在了送线索前, 这导致如果当前是满线索的话就会领取失败, 然后送线索完不领取

### 有什么好的想法？

送线索前后都领一下

**Comment by MistEO** [comment]
现在就是前后都领，没领可能是 bug，来个日志（

**Comment by one-pyy** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9865631/asst.log)

应该是2022-10-26 07:12:06左右

**Comment by one-pyy** [comment]
[asst - Copy.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9914742/asst.-.Copy.log)

又出现了一次(坏了没录屏), 但前后都做的事情只有点那个线索框

**Comment by one-pyy** [comment]
https://user-images.githubusercontent.com/72590023/201232724-6299d47b-bceb-455c-8ab9-5b9cda728c21.mp4

[asst - Copy.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9985444/asst.-.Copy.log)

(好耶, 是视频)

**Comment by MistEO** [comment]
后面有大佬提 PR 修了，如果还有问题麻烦再重新提个 issue ，谢谢~
