### ISSUE TITLE
4.6.5 beta1版本的自定义换班好像出现了很多奇怪的问题, 譬如菲亚梅塔选项不放菲亚梅塔和打断换班会切换下个班头

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaAssistantArknights#2442]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

菲亚梅塔选项不放菲亚梅塔

打断换班会切换下个班头(原来是只有执行完才会切换)

以及不知道是特性还是bug的: 宿舍选人的时候如果开始时技能排序, 就不会切换心情排序

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9864678/asst.log)

### 截图

https://user-images.githubusercontent.com/72590023/197902785-c1a2061d-999e-4ced-b305-b5c3b5fd45bb.mp4

**Comment by MistEO** [comment]
- 菲亚的问题，是特意改的，现在会对宿舍换两次 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2260
- 停止的问题，caused by https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/2332 , 似乎应该改成停止时强制返回 TaskChainError, 或者专门新增一个 TaskChainStop 之类的，但对集成可能产生一些影响。cc @LittleFall

**Comment by one-pyy** [comment]
好耶

**Comment by one-pyy** [comment]
现在停止之后就直接执行下面的关maa了, (是不是该再改改)
![image](https://user-images.githubusercontent.com/72590023/198157604-59c8aeee-54b0-4a59-afad-701647dd736d.png)

**Comment by one-pyy** [comment]
以及做完任务后好像就卡住了

![image](https://user-images.githubusercontent.com/72590023/198161926-7c42454b-948e-4947-9bda-99ff8d5d6c43.png)

手动按停止也不行

![image](https://user-images.githubusercontent.com/72590023/198161988-4383870b-4094-4059-91b1-814462778a3b.png)

(到16分还没停止成功)
