### ISSUE TITLE
搓合成玉的时候会出现BUG

### ISSUE THREAD

**Issue by MadRouge** [MaaAssistantArknights/MaaAssistantArknights#2444]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如果制造站安排搓合成玉的时候会提示干员冲突和无法打1-7的情况，排班是默认的，没有自定义排班表

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9865853/asst.log)

**Comment by MistEO** [comment]
无法打1-7 是啥情况

**Comment by MadRouge** [comment]
> 不能打1-7是啥情况

我也搞不懂，昨晚上突然出现的问题，报任务错误还是啥的，刚才试了下又可以了

**Comment by zzyyyl** [comment]
全关卡导航目前容错率较低，小心点用（

**Comment by cenfusheng** [comment]
干员冲突已修复，关卡导航已重构，如有复现可重新提issue，感谢反馈。
