### ISSUE TITLE
肉鸽选择错误导致死循环

### ISSUE THREAD

**Issue by HikashiKi** [MaaAssistantArknights/MaaAssistantArknights#2445]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

选择刷取傀影肉鸽主题时进入肉鸽界面后不进行主题切换，导致进入水月肉鸽后退出，产生死循环。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9866485/asst.log)
13:27:10-13：27:44

**Comment by MistEO** [comment]
把你要刷的肉鸽 pin 到终端上

**Comment by MistEO** [comment]
文档已补充，close
