### ISSUE TITLE
doc: 日语文档1.3, 2.1, 3.4的一级Header缺失

### ISSUE THREAD

**Issue by ChingCdesu** [MaaAssistantArknights/MaaAssistantArknights#2449]
### 说说你遇到的问题？

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/ja-jp/1.3-%E3%82%A8%E3%83%9F%E3%83%A5%E3%83%AC%E3%83%BC%E3%82%BF%E3%81%AE%E3%82%B5%E3%83%9D%E3%83%BC%E3%83%88.md
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/ja-jp/2.1-Linux%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB.md
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/ja-jp/3.4-%E3%82%BF%E3%82%B9%E3%82%AFAPI.md

**Comment by MistEO** [comment]
我印象里是时雨还是谁当时弄个什么东西，把所有的文档都改成二级 Header 开头了，后来有些文档逐步改回来了，有些没改回来

@bakashigure 还有印象么？

**Comment by ChingCdesu** [comment]
alisa在maa-website里直接换了个框架，我白配了md
拳头已经硬了，等他俩醒了，我直接👊

**Comment by bakashigure** [comment]
> 

好像是有这么回事 所有文档都改成 ## 开头

**Comment by bakashigure** [comment]
> 我印象里是时雨还是谁当时弄个什么东西，把所有的文档都改成二级 Header 开头了，后来有些文档逐步改回来了，有些没改回来
> 
> @bakashigure 还有印象么？


好像是有这么回事 所有文档都改成 ## 开头

**Comment by ABA2396** [comment]
👊
