### ISSUE TITLE
自动肉鸽能否添加用户自定义抓哪些干员的功能？

### ISSUE THREAD

**Issue by gnayuyuil** [MaaAssistantArknights/MaaAssistantArknights#2450]
### 说说你遇到的问题？

目前maa采取的抓位策略过于保守，希望大量溢出，也不包含本期环境中的优势解（玛恩纳/鸿雪/号角），至于控制对策解也就不提了，所以想知道允许用户自定义抓取策略是否可行？

**Comment by zzyyyl** [comment]
`resource/roguelike_recruit.json`
