### ISSUE TITLE
多显示屏识别问题

### ISSUE THREAD

**Issue by beijuy** [MaaAssistantArknights/MaaAssistantArknights#2452]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

大致概括为：我关闭一个显示屏后无法正确识别另一块显示屏。
推测为：
我现在所用的两块显示屏一块是display连接的2K主显示屏，一块是hdmi连接的1080P显示屏，
当我手动关闭display屏幕时，系统无法得到信号时，hdmi连接的屏幕会变为主显示屏，在此期间出现的bug？
自己很容易复现出问题，因为每天上楼前关显示屏后，第二天发现fight任务和infrast任务会报错，4：00自动刷新也没有启动过，应该是完全没有做任何动作。
git上本人暂时无法提交文件一直报错，若有需要联系zmlrapi123456789@qq.com，git上消息不能及时回复。

### 日志文件

Something went really wrong,and we can't process that file.

**Comment by IT-amateur** [comment]
不能够吧，MAA不是通过ADB调试直接获取的模拟器里的画面的吗？和显示器没关系吧，只要不关模拟器和MAA，随便干嘛都行的
