### ISSUE TITLE
自定义基建宿舍刷信赖策略

### ISSUE THREAD

**Issue by dylanhz** [MaaAssistantArknights/MaaAssistantArknights#2454]
### 说说你遇到的问题？

目前宿舍刷信赖默认是进驻高信赖干员，并且也没有提供低信赖优先的参数。

### 有什么好的想法？

提供低信赖干员优先进驻的参数。

**Comment by MistEO** [comment]
啥意思

**Comment by dylanhz** [comment]
> 啥意思

现在宿舍有空位蹭信赖是按照默认的信赖值排序来选的，也就是从高到底，但是我想按从低到高来选（也就是在排序页面按两次信赖值）
