### ISSUE TITLE
能不能出一个凌晨4点自动让宿舍全体换成信赖低的干员，然后4点一过再秒换下去

### ISSUE THREAD

**Issue by 9lanx1N** [MaaAssistantArknights/MaaAssistantArknights#2457]
### 说说你遇到的问题？

rt。自从开始用Maa基建排班，就几乎停止了刷信赖，这让我这个信赖党感觉很难受。

### 有什么好的想法？

对于想刷信赖的人而言，十分希望有这样一个能帮助刷信赖的功能。就是在每天的凌晨3:59，往宿舍里塞满所有信赖低的干员（甚至于更极端的，把基建所有位置全换成信赖干员），然后4点一过，秒收信赖再换回去。应该实现起来不复杂？但确实是一个需求呢。谢谢大佬们，辛苦了。

**Comment by ABA2396** [comment]
MAA 自带的定时+自定义排班 可以做到在3点的时候换成你排班作业设置的人，然后在4点换成另一批作业里的人
例如：
- 组A：[干员1，干员2，干员3] 生效时间[20:00,11:59],[00:00,2:59],[4:00,6:00]
- 组B：[干员4，干员5，干员6] 生效时间[3:00,3:59]
- 定时时间20:00,3:00,4:00

这样在20:00到3:00都是用于生产的干员，在3点换成了需要刷信赖的干员，在4点又换回了生产的干员。

而如果将 MAA 的启动写入 `windows定时计划` 且开启 `启动后直接运行` 功能可以进一步缩短刷信赖干员的工作时间
例如：
- 组A：[干员1，干员2，干员3] 生效时间[20:00,11:59],[00:00,3:55],[4:00,6:00]
- 组B：[干员4，干员5，干员6] 生效时间[3:56,3:59]
- `windows定时计划` 中 MAA 定时启动时间20:00,3:55,4:00

这样在20:00到3:55都是用于生产的干员，在3:56换成了需要刷信赖的干员，在4点又换回了生产的干员。

当然，换班是需要时间的，具体的时间还需要自己测试，不过相差几分钟的话收益差距也不会很大。
感觉通过这种方式刷信赖的需求人数应该不会很多，活动图/1-7/ 钱本等关卡都有不少少人过关的攻略，一拖十三/二拖十二刷信赖的效率应该比这高不少吧。

**Comment by 9lanx1N** [comment]
> MAA 自带的定时+自定义排班 可以做到在3点的时候换成你排班作业设置的人，然后在4点换成另一批作业里的人 例如：
> 
> * 组A：[干员1，干员2，干员3] 生效时间[20:00,11:59],[00:00,2:59],[4:00,6:00]
> * 组B：[干员4，干员5，干员6] 生效时间[3:00,3:59]
> * 定时时间20:00,3:00,4:00
> 
> 这样在20:00到3:00都是用于生产的干员，在3点换成了需要刷信赖的干员，在4点又换回了生产的干员。
> 
> 而如果将 MAA 的启动写入 `windows定时计划` 且开启 `启动后直接运行` 功能可以进一步缩短刷信赖干员的工作时间 例如：
> 
> * 组A：[干员1，干员2，干员3] 生效时间[20:00,11:59],[00:00,3:55],[4:00,6:00]
> * 组B：[干员4，干员5，干员6] 生效时间[3:56,3:59]
> * `windows定时计划` 中 MAA 定时启动时间20:00,3:55,4:00
> 
> 这样在20:00到3:55都是用于生产的干员，在3:56换成了需要刷信赖的干员，在4点又换回了生产的干员。
> 
> 当然，换班是需要时间的，具体的时间还需要自己测试，不过相差几分钟的话收益差距也不会很大。 感觉通过这种方式刷信赖的需求人数应该不会很多，活动图/1-7/ 钱本等关卡都有不少少人过关的攻略，一拖十三/二拖十二刷信赖的效率应该比这高不少吧。


谢谢你（其实经过过去一天的探索，我也不约而同地像你所说的这样做了……但还是十分感谢你。此外，挂基建刷信赖的效率要比大多数人想象地高得多，真的。）

除此之外，现在我其实更想解决的问题是信赖从低的开始挂，而不是从高的开始挂（这个其他人也提到过）。谢谢大佬，大佬辛苦了。

**Comment by MistEO** [comment]
> 除此之外，现在我其实更想解决的问题是信赖从低的开始挂，而不是从高的开始挂（这个其他人也提到过）。

测试版改过了，可以更新下
