### ISSUE TITLE
自动战斗寻人及关闭模拟器bug

### ISSUE THREAD

**Issue by 545426** [MaaAssistantArknights/MaaAssistantArknights#2459]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

1.自动战斗已寻找并选中“蓝毒”仍继续寻找蓝毒
2.首页设置为“完成后关闭模拟器”的情况下，点击自动战斗的“停止”会提示“任务完成”并自动关闭了模拟器。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9874481/asst.log)

### 截图

![DBS1{ D(ZT4MNB7RYG UV2K](https://user-images.githubusercontent.com/64343218/198158728-a297504a-06f1-4527-a701-35d71f1419d9.png)
![ESK~%IA$J0SB))PJ34 NLZ3](https://user-images.githubusercontent.com/64343218/198158742-1e1289b7-be0e-401c-955c-c37dbcdfb2dd.png)

### 还有别的吗？

蓝叠国际版模拟器，maa  4.6.5 beta2

**Comment by MistEO** [comment]
问题 2 beta.3 应该修了，你试试
