### ISSUE TITLE
任务完成停不下来

### ISSUE THREAD

**Issue by SwissRollC** [MaaAssistantArknights/MaaAssistantArknights#2460]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

最新测试板，单点自动基建，完成后并没有停止下来，无法进行其他任务，手动点击停止，显示正在停止，无反应但不是未响应。关闭重启之后刷理智，完成后依然出现该问题。

### 日志文件

[Uploading asst.log…]()

### 截图

![QQ截图20221027085637](https://user-images.githubusercontent.com/114994436/198167090-e9215afa-8dc4-4435-bce6-df4f40e7a2e3.png)

**Comment by SwissRollC** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9874830/asst.log)
上传失败重新上传日志文件

**Comment by satgo1546** [comment]
+1

**Comment by LittleNightmare** [comment]
+1
