### ISSUE TITLE
使用菲亚梅塔+巫恋组自定义基建换班时混乱/缺失步骤

### ISSUE THREAD

**Issue by RyanSaul** [MaaAssistantArknights/MaaAssistantArknights#2465]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在更新 v4.6.5-beta2 后使用自定义基建换班（包括菲亚梅塔+巫恋组）时出现数个问题：

1. 完成一个设施的换班后经常点击左上角返回按钮退出基建界面，随后再进入基建（该问题在beta1时就存在了，不清楚是不是为了避免某些bug而有意为之，但似乎对换班结果没有影响）；
2. 更换红云、蛇屠箱、刻俄柏时没有成功，换班后对应制造站没有干员进驻（模拟器内具体表现没有观察到）；
3. 在任务最开始使用了无人机、将龙舌兰和菲亚梅塔放入宿舍交换心情后，后续步骤中完全没有涉及到贸易站换班；
4. 第一间发电站换班以后，后续步骤中完全没有给其他贸易站换班；
5. 第一间宿舍进驻完干员后，直接退出了基建并显示基建换班任务完成，此时还有其他心情未满的干员没有进驻宿舍。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9877398/asst.log)

红云、蛇屠箱、刻俄柏换班：16:10:39
疑似进入贸易站但没有换班：16:12:16
进入第一间发电站换班：16:13:49
进入第一间宿舍进驻干员：16:17:10
基建换班任务完成了，但只完成了一点：16:18:01
（如果需要其他时间点可以再补充）

### 截图

![uTools_1666859133513](https://user-images.githubusercontent.com/16830734/198232379-c95f5c24-1527-4102-b142-1dd1255a5b77.png)

### 还有别的吗？

模拟器：蓝叠5国际版（hyper-v）
操作系统：Windows 11 Insider Preview 25227（22H2）

**Comment by MistEO** [comment]
beta.2 bug 很多，准备撤包了。等等 beta.3 或者先换 beta.1 用吧
