### ISSUE TITLE
基建中宿舍人员安排时逻辑可能存在不当

### ISSUE THREAD

**Issue by zayn7lie** [MaaAssistantArknights/MaaAssistantArknights#2466]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

情景：如果在最后一个（第3个，按照程序序号）宿舍中指定肥鸭，且在第一个宿舍勾选了“自动填充”。此时肥鸭心情为0，根据自动填充按照心情排序，肥鸭此时被安排到了第0个宿舍，但是在第三个宿舍安排人员时再次选择肥鸭，导致第0个宿舍会出现空位。

问题：在最后几个宿舍中指定干员后，勾选前面几个宿舍的“自动填充”可能会出现干员冲突

可能的解决方法：在第一次扫描储存所有干员时（第0间宿舍），对指定干员标记

### 日志文件

.

**Comment by MistEO** [comment]
那不要把他放在第三个宿舍。。不要点炒饭.jpg

**Comment by zayn7lie** [comment]
> 那不要把他放在第三个宿舍。。不要点炒饭.jpg

我的前3个宿舍（0-2号宿舍）为5级宿舍，但是第3号宿舍为4级宿舍，而肥鸭心情回复为无论如何都为2心情每小时，所以期望放在等级最低宿舍（第3号宿舍）

**Comment by zayn7lie** [comment]
> 那不要把他放在第三个宿舍。。不要点炒饭.jpg



> > 那不要把他放在第三个宿舍。。不要点炒饭.jpg
> 
> 我的前3个宿舍（0-2号宿舍）为5级宿舍，但是第3号宿舍为4级宿舍，而肥鸭心情回复为无论如何都为2心情每小时，所以期望放在等级最低宿舍（第3号宿舍）

并且此类情况还可能存在于有宿舍技能的干员身上~~所以应该不算要炒饭，只是酒吧有饭还没炒~~
