### ISSUE TITLE
更新后出现未知异常

### ISSUE THREAD

**Issue by nskknns** [MaaAssistantArknights/MaaAssistantArknights#2469]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

更新了新版本后反复报错“出现未知异常”并强制退出。看了一下报错的提醒，从.old里复制一个缺失的文件夹可以正常打开，不知道会不会产生别的问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9880027/asst.log)
10/27 22点49分前后

**Comment by zzyyyl** [comment]
OTA已更新，再次从 beta.2 更新到 beta.3 已不会再出现问题。

非国际服用户直接复制 `resource.old\PaddleOCR` 文件夹可以解决问题，国际服用户再复制一个 `resource.old\global`。
