### ISSUE TITLE
基建排班表在自行修改后无法导入

### ISSUE THREAD

**Issue by bton1** [MaaAssistantArknights/MaaAssistantArknights#2470]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

一图流网站生成的基建排班表，点进去默认的那款可以导入maa，但是在修改后再导入，就会提示红色的“自定义基建配置文件解析错误”

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9880337/asst.log)
每天都在出现（日志只有今天的是因为重装过）

### 截图

![屏幕截图(200)](https://user-images.githubusercontent.com/116821432/198315028-79c76443-b6c7-4262-83d9-b4db1ce5375a.png)

### 还有别的吗？

mumu模拟器
win10

**Comment by Fky2172** [comment]
代码格式错了吧，中文逗号或者多了逗号少了逗号，要改建议下个IDE，而且改一下另存为一下，导入MAA跑一下（必须让MAA执行换班，有时候你少个逗号，能导入但是运行时会显示出现未知错误）

**Comment by IT-amateur** [comment]
你这要不把你修改过后，会报错的那个排班计划JSON文件上传一下，估计是你修改的时候改的有点问题，我昨天也改过，但是能正常使用的

**Comment by bton1** [comment]
啊我修改的是排版生成器里的数据，而不是生成的json文件，没动过都不能用，，

**Comment by MistEO** [comment]
把你排版生成器生成的 JSON 也发出来看下

**Comment by bton1** [comment]
[1666878776423062.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9887475/1666878776423062.zip)

**Comment by MistEO** [comment]
你的排班时间的冒号输入的是全角的 `00：00`

**Comment by bton1** [comment]
可以了，非常感谢，因为我的疏忽占用您的时间很不好意思）
