### ISSUE TITLE
4.6.5-beta.3指定材料无法指定

### ISSUE THREAD

**Issue by AKBOOA** [MaaAssistantArknights/MaaAssistantArknights#2476]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

4.6.5-beta.3指定材料所有材料均无法指定

https://user-images.githubusercontent.com/115134348/198351727-54f402b0-8e92-4ce6-bfd9-e5235cc56d52.mp4

### 日志文件

无

**Comment by ABA2396** [comment]
#2354 重启试试
