### ISSUE TITLE
肉鸽卡住且卡死bug

### ISSUE THREAD

**Issue by lingxinquan** [MaaAssistantArknights/MaaAssistantArknights#2477]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

肉鸽卡住现象，1、银灰会一直卡在这里，一直下不下去。2、芙蓉技能刚好冷却完毕，同时芙蓉被晕住，芙蓉技能变成灰色脚本点击不了一直卡住无法恢复

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9881889/asst.zip)

### 截图

![c300a46d3da00db614411dd521265fa](https://user-images.githubusercontent.com/32209941/198358418-4f928c12-db9d-41bf-8450-ec9ae534c8d1.jpg)

### 还有别的吗？

夜神模拟器

**Comment by HMZyueshen** [comment]
新版本应该修复了此bug，如果还是会卡住再提issue
