### ISSUE TITLE
mac水月肉鸽异常

### ISSUE THREAD

**Issue by l1006986533** [MaaAssistantArknights/MaaAssistantArknights#2479]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

选的肉鸽主题是水月，log里还是Phantom@Roguelike@Begin，模拟器里一个人都不选，直接冲进去白给了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9883545/asst.log)

### 截图

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/74593601/198411720-14e4327a-200f-480c-ac87-79af0b3268dc.png">
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/74593601/198411751-4c6ef759-35a0-4e9f-9547-d22fb427ec2f.png">
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/74593601/198411980-f23c361d-2d67-4ebd-ad79-ac552c4c6943.png">

### 还有别的吗？

版本v4.6.5-beta.3，电脑版本macbook air m1 2020 Ventura 13.0，模拟器是android studio自带的avd

**Comment by MistEO** [comment]
@hguandl 来康康

**Comment by hguandl** [comment]
我之前不知道选主题的方式改了XD，刚刚提交 https://github.com/MaaAssistantArknights/MeoAsstMac/commit/97a549f3f59e3763d4aee5e2af138110deb90b7e 修复了这个问题。

**Comment by MistEO** [comment]
@hguandl 顺便给主仓库提交个更新 mac UI 的 commit 吧，或者我觉得也别子模块了直接挪进来算了（）
