### ISSUE TITLE
剿灭作战卡住

### ISSUE THREAD

**Issue by guojunyu196** [MaaAssistantArknights/MaaAssistantArknights#248]
打开之后没看休息去了，结果卡在这一小时了
![BS_PIC_2022-02-22-13-44-34](https://user-images.githubusercontent.com/76220347/155070698-7ca47372-bc4a-4736-8198-36cf2d8d9904.png)
![RK80~`4 KXCA9Q6~_Z_T)Z5](https://user-images.githubusercontent.com/76220347/155070704-5c5ac071-2dc9-425e-a35b-ee7ff4bcdf5f.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8113953/asst.log)

**Comment by MistEO** [comment]
adb 炸了，应该是蓝叠的问题，先重启下电脑吧

后续可能考虑这种情况加个界面提示啥的

**Comment by guojunyu196** [comment]
好的，谢谢_(:з」∠)_
