### ISSUE TITLE
皮肤识别错误

### ISSUE THREAD

**Issue by Black1312** [MaaAssistantArknights/MaaAssistantArknights#2480]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

无法正常识别可颂的珊瑚海岸皮肤，导致”技能：好了就用“无法正常使用技能，精英2皮肤正常运行。log时间：9：53，作业代码：maa://10938，蓝叠模拟器，maa beta3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9884508/asst.log)

### 截图

![S(B($I~H`2KNGJ9H{F5C)K8](https://user-images.githubusercontent.com/64343218/198453832-598528b7-a101-4d35-bc6d-06c6d3f00aab.png)

**Comment by MistEO** [comment]
现在应该 ok 了吧（
