### ISSUE TITLE
使用自动定时刷的时候模拟器关了会自动停止而不是重启模拟器

### ISSUE THREAD

**Issue by desktop4025** [MaaAssistantArknights/MaaAssistantArknights#2482]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

使用自动定时刷的时候模拟器关了会自动停止而不是重启模拟器

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9886894/asst.zip)

### 截图

![ZRC(@A%TLWHH$ 2Q81N7SV5](https://user-images.githubusercontent.com/107090995/198549039-8c264c7c-093b-47e7-9b0b-88baf96765a4.png)

**Comment by desktop4025** [comment]
但是手动点的时候就可以重启模拟器

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/198582265-0bc3d461-7ee2-42e2-a0de-4dc060adb41c.png)
