### ISSUE TITLE
自动肉鸽模块卡在“源石交易所”界面

### ISSUE THREAD

**Issue by BiologyHazard** [MaaAssistantArknights/MaaAssistantArknights#2483]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如题，使用maa自动肉鸽，多次出现卡在“源石交易所”界面的异常情况。
我没有亲眼看到maa怎么点到这里的，但是这个问题频繁出现，基本上挂的时间长都会出现。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9887232/asst.zip)

### 截图

<img width="960" alt="Snipaste_2022-10-28_15-14-36" src="https://user-images.githubusercontent.com/44924110/198558647-01f31717-6eeb-4022-b69c-4d63f5a22a91.png">

**Comment by zzyyyl** [comment]
maa告诉你该氪金了.jpg

**Comment by BiologyHazard** [comment]
草，，，，
maa怎么点点点点点到氪金界面的，，，而且每次卡住都是卡在这里（（（（（（

**Comment by ABA2396** [comment]
#672 里提到过复现方法，不知道现在还有没有

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue

**Comment by ABA2396** [comment]
这个是公招那儿在四点更新后的问题，已经修过了
