### ISSUE TITLE
Win10_雷电模拟器_GPU内存占用高导致花屏及系统卡死

### ISSUE THREAD

**Issue by c153747477** [MaaAssistantArknights/MaaAssistantArknights#2485]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

经几日观察,使用MAA后GPU内存占用率会随"作战"时的操作,成线性逐步提高
GPU内存满后会开始使用共享GPU内存 此时模拟器帧率下降严重 并感到卡顿
在全部内存满后 模拟器花屏 系统卡死需要重启系统才能恢复

GPU内存满
测试1:退出MAA,GPU内存占用无变化 100%占用

测试2:关闭模拟器,,GPU内存急速降低至1% 

测试3:启动MAA+启动模拟器,GPU内存提升至5%

测试4:
手动开始作战 肉鸽与1-7 多轮下来GPU占用维持在4%-6%之间
进入关卡选择等界面时内存为6% 点击开始行动后会瞬间降低至4%直到战斗结束 
进入结算界面内存会上升回5%

测试5:
打开MAA(仅打开开始唤醒+自动肉鸽) 多轮下来GPU逐步填满
观察到每次进入节点会增加2%-3%GPU内存占用  点击开始行动后会降低2%左右内存占用
随着多次进入非战斗节点 内存会逐步填满 

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9888043/asst.log)

### 截图

![无标题](https://user-images.githubusercontent.com/11987548/198578888-c2f19c03-81fe-43a8-8a67-b40e9beb9303.jpg)

**Comment by MistEO** [comment]
- 雷电吃的 GPU，不关 MAA 的事
- 雷电本身我们也不管（

![image](https://user-images.githubusercontent.com/18511905/198581854-7000b439-03d6-4a50-82b4-35738d894c03.png)
