### ISSUE TITLE
在排班生成器中勾选宿舍“补满空位”选项后，仍然有宿舍出现空位

### ISSUE THREAD

**Issue by Zerohound** [MaaAssistantArknights/MaaAssistantArknights#2486]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在排班生成器中勾选宿舍“补满空位”选项后，仍然有宿舍出现空位。
我测试发现，当所有未进驻干员心情和信赖都是已满时，并不能主动填充心情和信赖已满的干员。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9888508/asst.log)
2022-10-28 20:30

**Comment by MistEO** [comment]
测试版修过了

**Comment by cjyfs** [comment]
> 测试版修过了

您好，我现在又遇到了同样的问题并且发了新的issue，能麻烦看一下吗，谢谢
