### ISSUE TITLE
水月肉鸽逻辑改进

### ISSUE THREAD

**Issue by xuxu9110** [MaaAssistantArknights/MaaAssistantArknights#2487]
### 说说你遇到的问题？

遇到的场景1：在辅助、近卫、术士（不确定）三张券选一张的时候选了辅助券，然后有希望招6星有练度的令、浊蒂、铃兰等干员却直接取消招募。
（我并未修改rougelike_recruit.json，我觉得这个职业券的优先级可能不是那么合理，而且就算不招募六星辅助至少也得招个临时术士吧？）
遇到的场景2：选择升级后的以人为本分队，进入安全屋节点选择一次奖励后，在是否再次选择奖励时选择了否。
（固定选择多拿一个奖励应该更合适？）
以及一个额外建议：拥有某些藏品后调整干员的权重，比如获得爆裂之手后术士里神的优先级提至比羊和澄闪高。
（这个可能做起来比较难了……）

**Comment by MistEO** [comment]
> 然后有希望招6星有练度的令、浊蒂、铃兰等干员却直接取消招募。
>（我并未修改rougelike_recruit.json，我觉得这个职业券的优先级可能不是那么合理，而且就算不招募六星辅助至少也得招个临时术士吧？）

应该是 bug，来个日志

**Comment by xuxu9110** [comment]
[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9893915/log.zip)
我自己试图找了一下没找到……麻烦开发者找找了，只用看前两天不用看今天的

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
