### ISSUE TITLE
强烈需要会客室换班和线索操作分开，发现会客室不仅自动开趴，有时还会莫名其妙送线索

### ISSUE THREAD

**Issue by MigdalBavel** [MaaAssistantArknights/MaaAssistantArknights#2492]
### 说说你遇到的问题？

而且也不是为了腾空间收系统的每日一条线索。今天一次换班后发现9个线索，正在开趴，每日的接受过了的，也被送了两条出去。
线索很多时候另有打算的，跟着自动换班一起操作实在很蛋疼。

**Comment by Genicur** [comment]
对会客室需求不大的话 是否可以考虑取消换班？

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.1-%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md
![image](https://user-images.githubusercontent.com/99072975/215066745-a215ffe8-26be-44d5-9313-ac64b00c9c34.png)
