### ISSUE TITLE
基建宿舍自动填充顺序问题

### ISSUE THREAD

**Issue by DreAmVirGo** [MaaAssistantArknights/MaaAssistantArknights#2493]
### 说说你遇到的问题？

情景如下： 在自动排班时菲亚在1号宿舍给巫恋换心情，单独一人停留在一号宿舍内；排班完成后宿舍开始自动填充，此时自动勾选了未进驻，所以菲亚被排除在外。如果这个时候心情未满的已经选择完毕，则会从信赖度最高的开始选：这个时候接下来的宿舍都会按信赖值选择，所以菲亚不会被选择在内。结果就是菲亚恢复不了心情。

### 有什么好的想法？

如果可以的话先清空宿舍再进行自动填充？清楚可以手动把所有人都排进宿舍但是希望有能代码层面解决的办法orz。谢谢了

### 其他内容

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9892454/asst.log)
07:24 开始排宿舍的班

**Comment by MistEO** [comment]
既然用了自定义换班，把肥鸭填到宿舍里不就好了（

**Comment by DreAmVirGo** [comment]
> 既然用了自定义换班，把肥鸭填到宿舍里不就好了（

所以是想问问有没有除了手动以外的方法_(:з」∠)_。如果麻烦就可以不用做了，我先close啦
