### ISSUE TITLE
基建无人机使用

### ISSUE THREAD

**Issue by DreAmVirGo** [MaaAssistantArknights/MaaAssistantArknights#2494]
### 说说你遇到的问题？

一图流设置无人机使用的时点是在换班前，菲亚换巫恋心情也是在换班前。希望能把无人机加速放在最前面，如果菲亚把巫恋/龙舌兰换走之后再加速会有龙门币上的亏损。

### 有什么好的想法？

把两个换班前（菲亚换心情、无人机加速）的顺序更改一下。

### 其他内容

![image](https://user-images.githubusercontent.com/28724211/198751481-2d39292b-61c9-45c1-a73f-02123bc752a2.png)

**Comment by DreAmVirGo** [comment]
因为不能上传json，留一个一图流的id在这：1665184105517036

**Comment by MistEO** [comment]
beta 版本修过了，请参考 release note
