### ISSUE TITLE
mac上mumu报错 connectionInfo: Uuid , command failed to exec

### ISSUE THREAD

**Issue by miku1958** [MaaAssistantArknights/MaaAssistantArknights#2495]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

x86的mac, 用mumu模拟器跑v4.6.5-beta.3直接报错

### 日志文件

不知道mac版放在哪里

### 截图

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/24806909/198812574-3ad213e6-910c-4776-95db-6e5704f46e08.png">

**Comment by miku1958** [comment]
CC @hguandl

**Comment by miku1958** [comment]
我直接运行自带的adb会报错:
[1]    6807 illegal hardware instruction

**Comment by MistEO** [comment]
获取 uuid 那个命令现在实际没啥用，在 resource/config.json 里随便改个 echo 123456 之类的就行了，等于跳过这个命令

**Comment by l1006986533** [comment]
我又来了(捂脸)
mac端日志路径: /Users/**_username_**/Library/Containers/com.hguandl.MeoAsstMac/Data/Library/Application Support/asst.log, 把username替换成你的名字。ps：在访达用command+shift+G可以跳转目录。建议删掉log文件后再打开程序，然后再提交log，不然log文件体积会很大

**Comment by MistEO** [comment]
@hguandl mac 上可是试试 "Compatible" 连接模式（AsstConnect 的 config 参数）

**Comment by KazeLiu** [comment]
附带一句，开发说的把UUID改成echo 123456 是把

"uuid": "[Adb] -s [AdbSerial] shell settings get secure android_id" 改成
"uuid": "[Adb] -s [AdbSerial] shell echo 111111"

而不是
"uuid": "echo 111111"

我踩了一下这个坑（
