### ISSUE TITLE
肥鸭换心情流程存在漏洞，可能导致失败

### ISSUE THREAD

**Issue by Xzcy** [MaaAssistantArknights/MaaAssistantArknights#2496]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

007巫恋龙舌兰柏喙时，偶有发生换心情失败
经过多次观察，估计主要问题在于：换心情前，肥鸭恰好在宿舍1的2号位休息

按现有流程，肥鸭将一动不动，没有发生“进驻”这一事件，而换心情失败

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9892940/asst.log)

### 截图

模拟开始前，肥鸭恰好在宿舍1的2号位
![image](https://user-images.githubusercontent.com/47129094/198812671-ff6a191e-8ee3-43f8-a062-bc9a779eb360.png)
模拟现有换心情流程：
![image](https://user-images.githubusercontent.com/47129094/198812689-a05e2e6d-97c9-4045-88d3-56a74c039ce7.png)
![image](https://user-images.githubusercontent.com/47129094/198812720-9f61f099-b45a-491b-9e7e-75c41041cdfb.png)
此时，就会发生换心情失败！

考虑：1、使用清空按钮后再换心情；2、禁止肥鸭在宿舍1休息
临时解决办法：自定义排版，把肥鸭指定到其他宿舍

**Comment by MistEO** [comment]
这个问题 beta 版本修过了。就是你说的这个原因没错，现在会强制清空宿舍 1 再上肥鸭
