### ISSUE TITLE
Bot not doing anything

### ISSUE THREAD

**Issue by owlliang4** [MaaAssistantArknights/MaaAssistantArknights#2497]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I spent at least 5 minutes thinking and preparing before raising the issue.
- [ ] I have read the FAQ and the User Manual in the documentation and believe that this is most likely a bug and not designed to be so.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] The screenshots I've uploaded are the original ones taken by the emulator's own screenshot tool (or via adb).

### Description

After starting the application, the bot will show that it has run a task and then an error occurred. However, literally nothing happens.
When the bot gets to starting task infra, it will go to the store, click on orginiums and then wait and leave. It will also go to the skin store and click on angelina for some reason
If I try any manual input, the bot automatically clicks back to the main screen
When the bot gets to visit, it will click friends, then do nothing else, then return to main menu.
After that the bot will finish the task but nothing happens then finish.

### Log files

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9892958/asst.zip)

### Screenshots

![Screenshot 2022-10-29 120805](https://user-images.githubusercontent.com/116906170/198813160-ff17768f-4fca-4a09-b507-2b413dac9218.png)
![Uploading image.png…]()

### Anthing else?

Emulator: Nox

**Comment by MistEO** [comment]
Please read [the documentation](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/README_en-US.md#supports-for-overseas-clients) and set your client version if you are not using CN client.

And now we don't support all features of the overseas clients, plz aslo refer to the docs.

For example, the EN client:

![image](https://user-images.githubusercontent.com/18511905/198814751-9096740d-0e8e-4273-8f3e-f18736e0445c.png)
