### ISSUE TITLE
任务经常卡在某个节点后显示全部任务完成而非失败

### ISSUE THREAD

**Issue by mingruo233** [MaaAssistantArknights/MaaAssistantArknights#2498]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

任务进行到mall的时候，买完龙门币卡在龙门币，开始显示进行award以及fight但没有任何操作。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9892986/asst.log)
发生大概时间点：2022-10-29 00:19:47.299

### 还有别的吗？

模拟器是蓝叠国际版

**Comment by MistEO** [comment]
现在应该没有这个问题了？这地方重构过几次了，如果再出现麻烦重新提一个
