### ISSUE TITLE
自动更新工具箱的素材数量

### ISSUE THREAD

**Issue by miku1958** [MaaAssistantArknights/MaaAssistantArknights#250]
有个网站叫明日方舟工具箱 https://arkn.lolicon.app/#/material 里面有计算干员升级素材的功能，并且它能生成一个云端同步码，我的建议是用户手动复制这个同步码到app里，然后app打完一关可以自动更新增加这个同步码的素材量

**Comment by MistEO** [comment]
有仓库识别了
