### ISSUE TITLE
v4.6.4.beta3 任务运行一半闪退

### ISSUE THREAD

**Issue by Sea-Sheep** [MaaAssistantArknights/MaaAssistantArknights#2500]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

任务跑到一半MAA闪退
beta2应该是没这个问题的

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9893224/asst.log)

### 截图

![8RB2KA46)225SE6} ~( C_Q](https://user-images.githubusercontent.com/72082903/198820496-e358051c-504a-4a70-9a7a-fb663c166c2f.png)
![QW J_VKKL{)VV3MK}~F38HF](https://user-images.githubusercontent.com/72082903/198820516-43c627d0-b517-4149-92bf-7b17c590f9cc.png)

**Comment by zzyyyl** [comment]
资源少了，重新下吧）

**Comment by MistEO** [comment]
> 有可能是资源少了，重新下个试试（

不是资源的问题，似乎是飞桨的 WithData 接口哪里崩了

**Comment by MistEO** [comment]
[ppocr.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9893715/ppocr.zip)

替换下这个文件看看有用不？

**Comment by Sea-Sheep** [comment]
> [ppocr.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9893715/ppocr.zip)
> 
> 替换下这个文件看看有用不？

跑了一遍没出问题

**Comment by MistEO** [comment]
这个问题在一些设备上很容易复现，但另一些设备上怎么也复现不了，不知道为啥。再多帮忙测测，要是没问题我们就放到下个版本中了
