### ISSUE TITLE
水月肉鸽不期而遇(远销海外)卡着不动

### ISSUE THREAD

**Issue by Zorz4** [MaaAssistantArknights/MaaAssistantArknights#2501]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

遇上关卡不期而遇(远销海外)会卡着不动

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9893339/asst.zip)

问题出现的大致时间点："10-29 17:21:44 关卡：不期而遇"

### 截图

MAA 软件截图：
![未命名](https://user-images.githubusercontent.com/21257456/198824213-091718bf-d5d9-4e69-8912-3f3f939b962e.png)
游戏画面截图：
![Screenshot_20221029-172244](https://user-images.githubusercontent.com/21257456/198824054-de4dd4d6-fa43-468d-a7ab-4eeb472168f8.png)

### 还有别的吗？

MAA：v4.6.5-beta.3
模拟器：夜神模拟器 Android 7 (32bit)

**Comment by MistEO** [comment]
@zzyyyl
