### ISSUE TITLE
Mac版maa连接模拟器时报错connectionInfo: Uuid command failed to exec

### ISSUE THREAD

**Issue by W-874** [MaaAssistantArknights/MaaAssistantArknights#2502]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

Intel Mac在macOS13正式版下使用Android Studio的AVD，maa在连接时会报错connectionInfo: Uuid command failed to exec而不能成功运行。ADB地址直接填写的emulator-5554，在尝试连接后执行adb devices会多出一个“emulator-5554:5555 offline”的设备。

### 日志文件

mac端不清楚日志路径

### 还有别的吗？

模拟器：Android Studio的AVD，API 30
系统：macOS 13 Ventura正式版
设备：MacBook Pro 16‘ 2019款（Intel-based）

**Comment by MistEO** [comment]
暂时可以参考 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2495#issuecomment-1295888927 来处理

**Comment by l1006986533** [comment]
mac端日志路径: /Users/**username**/Library/Containers/com.hguandl.MeoAsstMac/Data/Library/Application Support/asst.log, 把username替换成你的名字。ps：建议删掉log文件后再打开程序，然后再提交log，不然log文件体积会很大
