### ISSUE TITLE
为什么自定义基建宿舍autofill不生效呢？

### ISSUE THREAD

**Issue by zoe4477** [MaaAssistantArknights/MaaAssistantArknights#2509]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

MAA 4.6.4 用的默认模板，最后一个宿舍选完固定干员和心情未满干员后，剩余一个空位不会自动填满。

### 日志文件

[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9894900/log.zip)

### 截图

![2](https://user-images.githubusercontent.com/38827851/198858674-c2982512-0e29-4b40-b1f9-6ce80b2e1c38.jpg)
![1](https://user-images.githubusercontent.com/38827851/198858675-c25d6d3d-7416-4a5a-a19d-0c3b1daec039.jpg)

**Comment by MistEO** [comment]
请更新测试版
