### ISSUE TITLE
定时执行自定义基建排班配置会随机出现不能正确执行的问题

### ISSUE THREAD

**Issue by vempx** [MaaAssistantArknights/MaaAssistantArknights#2510]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

NUC设置定时启动，启动后自动运行MAA并打开模拟器启动游戏，执行完任务自动关机。
启动时间分别为 　　　　　　0:55 | 4:55 | 20:55
MAA设置定时执行时间　　　1:00 | 5:00 | 21:00
MAA开始任务后，有几率会出现执行任务异常的情况，由于我设置为全自动运行，所以也没机会看到究竟发生了什么。一般会出现此问题是在5:00的时间段。

GUI的log如下：
10-30  04:55:37 自定义基建配置：
10-30  04:55:37 243极限
10-30  04:55:37 顶配243排班
10-30  04:55:37 A+B 组
10-30  04:55:37 [ 04:59 - 20:58 ]
10-30  04:55:37 最高效率长班，工作16小时
10-30  04:55:37 A+Y 组
10-30  04:55:37 [ 20:59 - 23:59 ]
10-30  04:55:37 次高效替补 1 班，工作4小时
10-30  04:55:37 B+Y 组
10-30  04:55:37 [ 00:59 - 04:58 ]
10-30  04:55:37 次高效替补 2 班，工作4小时
10-30  04:59:47 A+B 组
10-30  04:59:47 [ 04:59 - 20:58 ]
10-30  04:59:47 最高效率长班，工作16小时

10-30  05:00:37 正在连接模拟器……
10-30  05:00:41 正在运行中……
10-30  05:00:41 开始任务：StartUp
10-30  05:01:01 完成任务：StartUp
10-30  05:01:02 开始任务：Infrast
10-30  05:04:18 絮雨
10-30  05:04:26 絮雨
10-30  05:04:34 絮雨
10-30  05:04:43 絮雨
10-30  05:05:54 完成任务：Infrast
10-30  05:05:54 任务已全部完成！

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9894902/asst.log)

### 还有别的吗？

模拟器为蓝叠国际版5.9.300.1014 N64
操作系统Windows 11 22H2 22621.674
硬件NUC8i7BEH
采用安卓的platform-tools自定义链接至127.0.0.1:5555，连接配置选择为蓝叠模拟器

**Comment by zoe4477** [comment]
我也是。遇到过好几次了，且都是同一个班次卡住，也是卡在絮雨这个地方。但是不知道触发条件是啥，重新启动又变正常了。
![Snipaste_2022-10-28_08-42-53](https://user-images.githubusercontent.com/38827851/198859072-6d7d583e-eded-435c-a19a-5e1c4476cd26.jpg)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9894913/asst.log)

**Comment by MistEO** [comment]
- 卡在哪个界面了？
- 试试测试版，这块改了很多，可能修掉了

**Comment by vempx** [comment]
不知道具体是卡在哪个界面了，全自动执行的没有机会看到，如果MAA能有个保留截图功能倒是可以debug一下。
测试版也不行，会出现同样的问题。

**Comment by MistEO** [comment]
我的意思是，当你看到一堆任务报错，MAA 已经停止运行了，（哪怕已经过了很久了），这时候游戏在哪个界面？

**Comment by vempx** [comment]
啊，那我需要调整一下NUC的设置以后看看

**Comment by ABA2396** [comment]
出现多次干员名字的话大概就是没点上按技能排序的按钮，工作状态没切换到按技能排序，感觉应该点完之后检查一下那个按钮的状态 @MistEO

**Comment by MistEO** [comment]
> 出现多次干员名字的话大概就是没点上按技能排序的按钮，工作状态没切换到按技能排序，感觉应该点完之后检查一下那个按钮的状态 @MistEO 

不是，是基建压根就没进去。之前不少都是这个问题，不知道卡在哪个莫名其妙的界面了，啥都识别不到

**Comment by vempx** [comment]
昨天没有复现这个问题……今天我准备全程录像再试试……

**Comment by vempx** [comment]
![签到](https://user-images.githubusercontent.com/7219917/199355592-d60afea9-7efd-4bf0-8271-54e2b8ac00bc.jpg)
![产业合作洽谈](https://user-images.githubusercontent.com/7219917/199355644-db384477-6a2b-4309-8ffa-bf3a6a35b36e.jpg)
呃……3.5周年的签到被MAA关了，但是抽合成玉这里卡住了，之前因为什么卡住不知道但是应该也是类似过了4点以后的新弹出窗口之类的吧

**Comment by ABA2396** [comment]
![Screenshot_2022 11 02_10 14 31 575](https://user-images.githubusercontent.com/99072975/199380170-c51bdb65-431c-48c1-92ef-1b049761c090.png)

**Comment by ABA2396** [comment]
> 我也是凌晨自动基建换班被弹出来的“产业合作洽谈会”界面卡住了，请问能否给这个界面也加一个自动关闭呢？毕竟之后两周时间每天都会弹这个，对自动换班的影响还是比较大的。 @MistEO

新版本修了

**Comment by vempx** [comment]
好的，等3.5周年过了以后我继续测一下非活动时期到底是什么导致卡住的。
