### ISSUE TITLE
关卡选择能否增加一个周计划

### ISSUE THREAD

**Issue by zoe4477** [MaaAssistantArknights/MaaAssistantArknights#2511]
### 说说你遇到的问题？

用了自定排班以后经常连续挂机好几天，但是没开刷材料活动时每天早上都得手动选择今天要刷什么关卡。

### 有什么好的想法？

如果能提前设置好每天刷哪关就更方便了，比如“周一红票、周二龙门币、周三剿灭+1-7……周日红票”这样。

**Comment by zzyyyl** [comment]
你的需求大概可以使用备选关卡

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/198867278-b47e6aa9-50bc-43c6-8eff-de4902d5780a.png)
![image](https://user-images.githubusercontent.com/99072975/198867267-8ae86696-92bf-4e18-8f29-bef045831389.png)
