### ISSUE TITLE
kvm的win10虚拟机，无法正常运行，找不到dll

### ISSUE THREAD

**Issue by haohanyuzmx** [MaaAssistantArknights/MaaAssistantArknights#2515]
### 说说你遇到的问题？

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/57041322/198861967-729416cf-7ddd-425e-946d-369457f2fd4e.png">
尝试了设置path变量，复制dll到win/system32，将项目放在program file

**Comment by zzyyyl** [comment]
什么版本的maa

**Comment by haohanyuzmx** [comment]
最新版

**Comment by zzyyyl** [comment]
缺运行库吧

**Comment by haohanyuzmx** [comment]
具体是哪些运行库

**Comment by zzyyyl** [comment]
看文档
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md

**Comment by haohanyuzmx** [comment]
> 看文档 https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md

解决
