### ISSUE TITLE
水月肉鸽最后一关能否加个提示并自动暂停

### ISSUE THREAD

**Issue by ghost** [MaaAssistantArknights/MaaAssistantArknights#2516]
### 有什么好的想法？

水月肉鸽最后一关能否加个提示功能，可以在设置中开启，然后会在最后一关boss关前自动暂停
这样的话，方便刷结局的角标和解锁收藏品，也方便每月完成可能存在的委托任务
毕竟让ai打最后一关每次都有可能寄

**Comment by MistEO** [comment]
能推到最后一关一般编队都非常给力，挺容易过的

**Comment by zzyyyl** [comment]
顺便说一句，现在的beta4一定会在boss关前跑路，小心

**Comment by zzyyyl** [comment]
以及maa打的结局基本上都是海沫）

**Comment by Charlespkuer** [comment]
> 顺便说一句，现在的beta4一定会在boss关前跑路，小心

有吗？我刚刚看到maa过了一把（本人无操作）

**Comment by zzyyyl** [comment]
嗯？你是beta4？发日志看看（x

**Comment by Charlespkuer** [comment]
![JB)@OD1GFC4ERU U_AV1}XG](https://user-images.githubusercontent.com/112697147/198877319-49f21aea-f059-442b-9c55-13ad19ae2f25.jpg)

**Comment by Charlespkuer** [comment]
> 嗯？你是beta4？发日志看看（x @Charlespkuer

哦抱歉，好像是beta3

**Comment by qthzrv** [comment]
> 能推到最后一关一般编队都非常给力，挺容易过的

maa每次打到最后一关，我就没见过打过。
