### ISSUE TITLE
战斗失败

### ISSUE THREAD

**Issue by haohanyuzmx** [MaaAssistantArknights/MaaAssistantArknights#2519]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

战斗结束后，无法正常返回，结算界面展示失败

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9895554/asst.log)

### 截图

![Screenshot_2022 10 30_17 47 38 930](https://user-images.githubusercontent.com/57041322/198872507-ce657452-9940-48be-9590-07bb61dd3193.png)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/57041322/198872605-ea57f14c-6760-4d1a-a2c9-4ce6f7a5caeb.png">

**Comment by haohanyuzmx** [comment]
![Screenshot_2022 10 30_17 47 38 930](https://user-images.githubusercontent.com/57041322/198872904-ac30c652-ab93-45a8-94f8-7c9a1d64c198.png)

**Comment by MistEO** [comment]
你的模拟器太卡了，从点击橙色的“开始行动”按钮，加载了将近一分钟才进到战斗画面。加载的画面不同关卡五花八门，不好做识别，MAA 这里会等待 40 秒，再没进就会报错。

可以自己把 `resource/tasks.json` - `StartButton2` - `rearDelay` 改大一点（单位毫秒）
但是从日志来看你的电脑不至于卡到这种程度，也可以考虑给模拟器多分一点 CPU 内存啥的

**Comment by haohanyuzmx** [comment]
解决，卡主要是虚拟化层数太多了，233
