### ISSUE TITLE
请问有没有兴趣开发基于网易云游戏的API

### ISSUE THREAD

**Issue by wupco** [MaaAssistantArknights/MaaAssistantArknights#252]
我大概写了一个api的Demo `https://github.com/wupco/netease_cloud_game_sdk`
这样对于我这种开不起模拟器的垃圾电脑也可以用了，而且还可以挂在没有gui的服务器上。
补充一些desc, 如果要做的话，方便做迁移：
```
1. 前面是直接对网易云游戏站的HTTP请求，涉及登录/根据game code搜game信息，然后根据拿到的信息选择接入线路等，应该可以比较容易移植到c++。
2. 网易云游戏用的是双通道通讯实时操控游戏，第一个通道是用websocket以发送msg的形式发送鼠标或键盘的操作以及init阶段的rtcp连接票据信息，第二个通道是利用RTCP协议传输实时画面/音轨，所以可以通过针对第二个通道的ocr来决策操作，向第一个通道发送msg。
```

**Comment by wupco** [comment]
补充一些desc, 如果要做的话，方便做迁移：
```
1. 前面是直接对网易云游戏站的HTTP请求，涉及登录/根据game code搜game信息，然后根据拿到的信息选择接入线路等，应该可以比较容易移植到c++。
2. 网易云游戏用的是双通道通讯实时操控游戏，第一个通道是用websocket以发送msg的形式发送鼠标或键盘的操作以及init阶段的rtcp连接票据信息，第二个通道是利用RTCP协议传输实时画面/音轨，所以可以通过针对第二个通道的ocr来决策操作，向第一个通道发送msg。
```

**Comment by Tokisaki-Galaxy** [comment]
有点像弄了，我可以来试着提pr，维护者对着个有兴趣吗

**Comment by wupco** [comment]
> 有点像弄了，我可以来试着提pr，维护者对着个有兴趣吗

可以啊，但是他们可能协议格式改了，如果确定做，我再去看看

**Comment by Tokisaki-Galaxy** [comment]
@MistEO 请问对这个有兴趣吗

**Comment by MistEO** [comment]
目前 MAA 大部分识别要求图像质量无损，主要是模板匹配那块而不是 OCR，任何有损压缩都会造成大量的识别错误。你们可以试试看，但我觉得效果不会太好

**Comment by wupco** [comment]
> [@MistEO](https://github.com/MistEO) 请问对这个有兴趣吗

https://github.com/wupco/netease_cloud_game_sdk/blob/main/ark-demo.py

我用gpt糊了一个新的。。你试试看呢？ 这个截图质量够不够

**Comment by Tokisaki-Galaxy** [comment]
在做了，不过预期有损压缩确实会造成大量识别错误，可能需要特定的增强识别方法。我先去试试

**Comment by Tokisaki-Galaxy** [comment]
https://github.com/orgs/MaaAssistantArknights/discussions/14404

来这讨论吧
@wupco
