### ISSUE TITLE
肉鸽能否选择性刷结局

### ISSUE THREAD

**Issue by Charlespkuer** [MaaAssistantArknights/MaaAssistantArknights#2520]
### 说说你遇到的问题？

现在的肉鸽优化下，maa通关肉鸽概率已经不容小觑，能否增添一个选择性刷结局章的功能？（比如点了之后遇到骑士和蒂蒂就会优先选择相应线路）

**Comment by ntgmc** [comment]
主要是现在肉鸽看到蒂蒂和骑士的藏品直接不选o(╥﹏╥)o

**Comment by WWPXX233** [comment]
可能以后会但是目前还是以自动刷取等级为主
