### ISSUE TITLE
Mac 虚拟机或BootCamp环境中的Windows无法启动Maa

### ISSUE THREAD

**Issue by Xiyuche** [MaaAssistantArknights/MaaAssistantArknights#2523]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在Mac下使用Parallel Desktop中虚拟化的Windows 10家庭版、专业版无法打开Maa：
打开后Maa页面为空白，片刻后退出并报错

### 日志文件

[gui.err.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9897418/gui.err.log)
抱歉不太清楚log文件在哪里，4.6.5-beta.4报错后根目录下找到一个gui.err.log文件

### 还有别的吗？

我尝试了多个版本，出现了同样的问题：
4.1.2
4.6.4
4.6.5-beta 4
推测是电脑的问题，和群里另一个用户聊天发现有相同问题。

我曾经在今年8月份BootCamp中的Windows正常使用Maa。

Windows版本也尝试了多个，包括Windows10专业版和家庭版。
虚拟机内使用CPU-Z显示支持AVX指令集

**Comment by MistEO** [comment]
可能运行库没装全？

**Comment by Xiyuche** [comment]
> 可能运行库没装全？

确实，问题解决了：

Windows 10专业版
Visual Studio 2022安装C++、.NET选项就可以了（我试了试可能必须要进行这一步？）

另外如果是虚拟机的话最好不要在Mac共享文件中运行（ParallelDesktop）
