### ISSUE TITLE
日服傀影肉鸽特定不期而遇关卡会卡住不动

### ISSUE THREAD

**Issue by b1uemark** [MaaAssistantArknights/MaaAssistantArknights#2525]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在傀影肉鸽不期而遇的以血还血关卡中，MAA会卡住不动

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9899282/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/117070249/198960733-69f1edce-5a1c-41ef-a4c1-96029a2b528b.png)

**Comment by zzyyyl** [comment]
更新一下。
