### ISSUE TITLE
希望自动更新能通过jsonrpc管道指定本机已有的aria2c下载

### ISSUE THREAD

**Issue by MirrorCubeSquare** [MaaAssistantArknights/MaaAssistantArknights#2526]
### 说说你遇到的问题？

现在下载使用的是安装目录下的那个aria2C，但是由于我BT下载需求，我自己布置了一套aria2c
例如dandanplay等支持aria2c下载的软件，一般是会让你填入jsonrpc地址并调用下载，使用内置aria并不符合直觉

### 有什么好的想法？

让用户可以选择填入aria2的jsonrpc地址（同时可选附上类似dandanplay的测试连接功能）
或者修改配置界面明示是使用内置aria2c引擎下载

**Comment by MistEO** [comment]
现在 aria2c 删掉了
