### ISSUE TITLE
基建制造站源石碎片补货后更换人员失败

### ISSUE THREAD

**Issue by dddcm** [MaaAssistantArknights/MaaAssistantArknights#2532]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

基建制造站源石碎片补货后更换人员失败，猜测原因应该是 MAA在执行源石碎片补货后上传数据的卡顿里点击了制造站内干员选择，因此未能成功进入干员选择页面。建议 在源石碎片补货指令后添加一个延迟

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9905465/asst.log)

### 截图

https://user-images.githubusercontent.com/116613044/199124375-a75a71cd-c309-489e-a330-1f317095d80e.mp4

**Comment by dddcm** [comment]
在task文件里修改如下，可以基本解决
`    "ReplenishToMaxConfirm": {
        "action": "ClickSelf",
        "roi": [
            854,
            504,
            192,
            187
        ],
        "rearDelay": 1500	
    }`
建议在以后版本里添加

**Comment by MistEO** [comment]
测试版修过了，更新一下~

**Comment by dddcm** [comment]
哦好的，我还在用4.6.4，不好意思
