### ISSUE TITLE
水月肉鸽不开技能导致打年糕到超时撤退

### ISSUE THREAD

**Issue by YuhangTom** [MaaAssistantArknights/MaaAssistantArknights#2533]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在打年糕阶段不是每个干员的技能都会打开（只开焰尾技能不开百嘉技能，见视频，怀疑是bug），最后导致被重装卡住打不死超时撤退。既然有计打年糕时间的功能的话（因为这关打了9分钟比功能介绍里说的5分钟自动撤退久，所以我默认有了），可以在开始计时后开启轮流开所有干员的技能，并在撤退地面干员时按职业撤退，比如优先重装>先锋>近卫，或者优先撤退正在阻挡的干员，如果1分钟后还卡着再全部撤退，这样应该能提高通关且耗时也不会增加太多。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9905715/asst.log)

### 截图

用模拟器录了视频放在[GDrive](https://drive.google.com/file/d/1rlunDVeQIBngTD4cBDdl4BhS43-fY4gh/view?usp=sharing)上了

### 还有别的吗？

v4.6.5-rc.1
MuMu 2.7.7.0 (x86)

**Comment by MistEO** [comment]
干员技能识别错误的问题，新版本修了
