### ISSUE TITLE
绷不住了，更新到最新版之后日服的肉鸽需要交易的关卡都会卡住不动了

### ISSUE THREAD

**Issue by b1uemark** [MaaAssistantArknights/MaaAssistantArknights#2534]
### 在提问之前...

- [ ] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

更新一点用都没有了属于是

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9906756/asst.log)

**Comment by ABA2396** [comment]
> ### 在提问之前...
> * [ ]  我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区

**Comment by MistEO** [comment]
你来改一下就行了呀，代码不都在这吗

**Comment by CharlesChou73** [comment]
旧版本的程序在[这里](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases)，新版本的代码在[这里](https://github.com/MaaAssistantArknights/MaaAssistantArknights)，对更新不满意的建议是自助
