### ISSUE TITLE
maa能否加一个连接到mumu星云版的办法

### ISSUE THREAD

**Issue by ability66** [MaaAssistantArknights/MaaAssistantArknights#2536]
### 说说你遇到的问题？

装了个window是下的linux的子系统，但是好像因为冲突了所有模拟器都用不了，只有mumu的星云引擎能用，但是星云引擎貌似没有adbserver，自动检测也检测不到

**Comment by MistEO** [comment]
蓝叠国际版可以（HyperV 版本），星云没有 adb 弄不了的
