### ISSUE TITLE
设置保存到系统目录

### ISSUE THREAD

**Issue by hjhjfhjhujhh** [MaaAssistantArknights/MaaAssistantArknights#254]
如题，能不能把设置什么的保存到AppData之类的地方，自动更新经常不管用，下载新版本又得重新改设置...

话说只有我自动更新失败吗？已经连续好几个版本手动更新了。而且能不能给aria2开个日志或者命令窗口啊（是我没找到吗？），我都不知道到底是什么错误....

**Comment by MistEO** [comment]
~~在写了在写了~~

现在 WPF 的前端基本停止维护了，新界面这些都会有，可以关注 https://github.com/MaaAssistantArknights/MeoAsstElectronUI

**Comment by bakashigure** [comment]
> 如题，能不能把设置什么的保存到AppData之类的地方，自动更新经常不管用，下载新版本又得重新改设置...
> 
> 话说只有我自动更新失败吗？已经连续好几个版本手动更新了。而且能不能给aria2开个日志或者命令窗口啊（是我没找到吗？），我都不知道到底是什么错误....

~在写了在写了~
新版本会将设置保存在 `AppData`, 也会有新的自动更新

**Comment by ABA2396** [comment]
古老的问题）不知道现在自动更新还有没有问题，不过现在可以在github下载OTA包然后直接替换文件

**Comment by zzyyyl** [comment]
> ~在写了在写了~
> 
> 现在 WPF 的前端基本停止维护了，新界面这些都会有，可以关注 https://github.com/MaaAssistantArknights/MeoAsstElectronUI

”停止维护“
