### ISSUE TITLE
mac刷理智

### ISSUE THREAD

**Issue by EnmmmmOvO** [MaaAssistantArknights/MaaAssistantArknights#2547]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

macos版本刷理智，勾选指定次数的情况下，只刷去1次后直接停止（有时候会运行2次后停止）。测试了4.66与4.65rc.1都存在此问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9909665/asst.log)

**Comment by MistEO** [comment]
```log
[2022-11-01 23:13:53.240][TRC][Pxabf6][Tx10b7a377d218ff02] OcrPack::recognize | raw: [{ 8-S1: [ 0, 13, 84, 30 ], score: 1.000000 }]
[2022-11-01 23:13:53.240][TRC][Pxabf6][Tx10b7a377d218ff02] OcrPack::recognize | proc: [{ _INVALID_: [ 140, 73, 84, 30 ], score: 1.000000 }]
[2022-11-01 23:13:53.240][INF][Pxabf6][Tx10b7a377d218ff02] analyze_stage_code stage_code _INVALID_
```

关卡名识别错了，以为你在刷 EX 关卡浪费理智，就自动停了。你实际在刷哪关？


```log
SubTaskError 
{"why":"无奖励关卡","taskchain":"Fight","subtask":"CheckStageValid","details":{},"taskid":3,"uuid":"111111\n","class":"asst::StageDropsTaskPlugin"}
```

@hguandl 这有个回调界面可以考虑显示一下


```json
            [
                "^.+-S-?\\d+$",
                "_INVALID_"
            ]
```

@zzyyyl  这个替换规则合理吗？

**Comment by EnmmmmOvO** [comment]
在活动关卡IS-8，之前刷正常的好像没出问题

**Comment by zzyyyl** [comment]
不合理吗？
也许可以把 `"^.+-S-?\\d+$"` -> `"^.+-S-\\d+$"`

**Comment by zzyyyl** [comment]
草，自动旋转180是吧

**Comment by MistEO** [comment]
咋还能旋转 180° 的，等 @hguandl 看看吧

**Comment by hguandl** [comment]
769ce6d79d181ca0ae63f8a53a725038764818fb 调整了 OCR 的版本，起码 IS-8 不会识别错了
