### ISSUE TITLE
水月肉鸽以人为本分队不会选择活用安全屋

### ISSUE THREAD

**Issue by Zorz4** [MaaAssistantArknights/MaaAssistantArknights#2548]
### 说说你遇到的问题？

以人为本分队可以选择两次安全屋，但是第二次的时候会直接选择离开

### 有什么好的想法？

选择活用安全屋

### 其他内容

![Screenshot_20221101-205834](https://user-images.githubusercontent.com/21257456/199238298-5dc69a41-70d7-4026-ae3f-9222095537c4.png)

**Comment by Reeleon** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10008822/asst.log)
发生时间：
2022/11/15 10:48:25 关卡：安全的角落
2022/11/15 10:48:55 关卡：普通作战
MAA版本：
v4.6.13
肉鸽设置：
水月肉鸽，波涛迭起 0，刷等级，以人为本分队，稳扎稳打职业分队，艾雅法拉开局

**Comment by Reeleon** [comment]
内容相似的issue：
#2708

**Comment by zzyyyl** [comment]
更新测试版。
