### ISSUE TITLE
缄默德克萨斯无法识别

### ISSUE THREAD

**Issue by AndyLonly** [MaaAssistantArknights/MaaAssistantArknights#2551]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

新干员里缄默德克萨斯在编队中和实战中均无法识别
GPU和CPU版本均无法识别
目测把缄默德克萨斯识别成减默德克萨斯了

### 日志文件

GPU版本：[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9910285/asst.log)
[2022-11-01 21:27:09.212][TRC][Px39e0][Tx24f4] OcrPack::recognize | raw: [{ 减默德克萨斯: [ 0, 0, 0, 0 ], score: 0.986161 }]
[2022-11-01 21:27:09.212][TRC][Px39e0][Tx24f4] OcrPack::recognize | proc: [{ 减默德克萨斯: [ 798, 596, 103, 21 ], score: 0.986161 }]
[2022-11-01 21:27:09.212][TRC][Px39e0][Tx24f4] OcrPack::recognize | roi: [ 1005, 596, 42, 22 ]
CPU版本: [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9910318/asst.log)
[2022-11-01 21:33:29.249][TRC][Px34e4][Tx2414] OcrPack::recognize | raw: [{ 减默德克萨斯: [ 0, 0, 0, 0 ], score: 0.975571 }]
[2022-11-01 21:33:29.249][TRC][Px34e4][Tx2414] OcrPack::recognize | proc: [{ 减默德克萨斯: [ 825, 596, 104, 21 ], score: 0.975571 }]
[2022-11-01 21:33:29.249][TRC][Px34e4][Tx2414] OcrPack::recognize | roi: [ 1033, 596, 42, 22 ]

### 截图

卡死在这里
![卡死在这里](https://user-images.githubusercontent.com/15814794/199246556-de3e1aa4-2943-422a-8541-905fea3da254.png)
缄默德克萨斯的截图
![缄默德克萨斯的截图](https://user-images.githubusercontent.com/15814794/199246658-cb6839f6-d6c5-4062-b8c2-3f3057425a2e.png)

### 还有别的吗？

蓝叠国际版模拟器
横屏 1280 * 720 分辨率 320 dpi

**Comment by ABA2396** [comment]
182fc61c82284523f730d8c0630c86b61cd0e39f fixed

**Comment by MistEO** [comment]
> 182fc61c82284523f730d8c0630c86b61cd0e39f fixed

改成正则得了（

**Comment by AndyLonly** [comment]
> > [182fc61](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/182fc61c82284523f730d8c0630c86b61cd0e39f) fixed
> 
> 改成正则得了（

改正则后测试通过（之前写的自动战斗也打过xD
```
[
                ".+默德克萨斯",
                "缄默德克萨斯"
            ]
```

**Comment by ABA2396** [comment]
yj越来越喜欢奇奇怪怪的字了（）

**Comment by ABA2396** [comment]
8c331c3e5fa12202d5e4511138bc47556ab3cb9c

**Comment by leo3322** [comment]
作业功能里面的缄默德克萨斯好像还无法识别

**Comment by leo3322** [comment]
is-8那关

**Comment by AndyLonly** [comment]
> 作业功能里面的缄默德克萨斯好像还无法识别

请更新[v4.6.7-beta.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.6.7-beta.1)或者手动更新https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/8c331c3e5fa12202d5e4511138bc47556ab3cb9c

**Comment by leo3322** [comment]
> > 作业功能里面的缄默德克萨斯好像还无法识别
> 
> 请更新[v4.6.7-beta.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.6.7-beta.1)或者手动更新[8c331c3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/8c331c3e5fa12202d5e4511138bc47556ab3cb9c)

大佬你看看你运行下，我修改了你的作业自己用 maa://11143，我maa已经更新了4.6.7了，但是还是没有部署缄默德克萨斯

**Comment by AndyLonly** [comment]
> > > 作业功能里面的缄默德克萨斯好像还无法识别
> > 
> > 
> > 请更新[v4.6.7-beta.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.6.7-beta.1)或者手动更新[8c331c3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/8c331c3e5fa12202d5e4511138bc47556ab3cb9c)
> 
> 大佬你看看你运行下，我修改了你的作业自己用 maa://11143，我maa已经更新了4.6.7了，但是还是没有部署缄默德克萨斯

![unknown](https://user-images.githubusercontent.com/15814794/199659864-530056e2-8dfb-4317-b6bc-d7741400ed33.png)
我这边使用4.6.7测试发现能够部署缄默德克萨斯只不过错轴了emmm
但是4.6.6测试就没问题
![image](https://user-images.githubusercontent.com/15814794/199661524-94d9025b-773f-403e-b0e4-3f5602714e2a.png)
