### ISSUE TITLE
4.66版本B服唤醒失败

### ISSUE THREAD

**Issue by kuroyukino** [MaaAssistantArknights/MaaAssistantArknights#2553]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

4.66版本多次测试在唤醒任务开始BILIBILI国服的时候直接卡顿唤醒不了然后显示任务完成

### 日志文件

[Uploading asst.log…]()

### 截图

![7{1XWGXLN8MV5E@N~H32HG6](https://user-images.githubusercontent.com/117200322/199291952-e47721d6-13f5-4912-b778-e4949f14c281.png)

### 还有别的吗？

蓝叠模拟器 WIN10系统

**Comment by kuroyukino** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9912471/asst.log)

**Comment by zpw476898033** [comment]
一样

**Comment by Reminiserces** [comment]
一样捏

**Comment by Fky2172** [comment]
看图可能是因为无法识别点击到这个界面中的应用图标，在bug解决前我提供一个可能的解决方法：
长按模拟器中的方舟图标，添加桌面快捷方式，在maa的选择模拟器中选择这个快捷方式，而不是模拟器快捷方式，这样maa启动模拟器会直接打开方舟

**Comment by zzyyyl** [comment]
> 看图可能是因为无法识别点击到这个界面中的应用图标，在bug解决前我提供一个可能的解决方法： 长按模拟器中的方舟图标，添加桌面快捷方式，在maa的选择模拟器中选择这个快捷方式，而不是模拟器快捷方式，这样maa启动模拟器会直接打开方舟

别瞎说，maa 启动软件不是用点击，是直接 adb shell am start 启动
这次的问题是B服更新后换了个包名（

**Comment by 134820134820** [comment]
所以解决了吗

**Comment by Reminiserces** [comment]
还没有捏&nbsp; 再等等吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月2日(周三) 晚上8:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 4.66版本B服唤醒失败 (Issue #2553)




 
所以解决了吗

**Comment by Reminiserces** [comment]
等玛丽修复咯



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月2日(周三) 下午5:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 4.66版本B服唤醒失败 (Issue #2553)




  
看图可能是因为无法识别点击到这个界面中的应用图标，在bug解决前我提供一个可能的解决方法： 长按模拟器中的方舟图标，添加桌面快捷方式，在maa的选择模拟器中选择这个快捷方式，而不是模拟器快捷方式，这样maa启动模拟器会直接打开方舟
  
别瞎说，maa 启动软件不是用点击，是直接 adb shell am start 启动
 这次的问题是B服更新后换了个包名（

**Comment by zzyyyl** [comment]
修过了哦，没发版呢

**Comment by zzyyyl** [comment]
可以自己改 resource/config.json ，参照 [cd77bee](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/cd77beee4323d14e488f5654ab2946522ede560a)

**Comment by 134820134820** [comment]
> 可以自己改 `resource/config.json` ，参照 [cd77bee](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/cd77beee4323d14e488f5654ab2946522ede560a)

改完就可以了,谢谢,话说这波是b服总算和其它版本统一了是吧

**Comment by Reminiserces** [comment]
是重新加载文件还是自己进去文件内更改？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月2日(周三) 晚上9:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 4.66版本B服唤醒失败 (Issue #2553)




  
可以自己改 resource/config.json ，参照 cd77bee
  
改完就可以了,谢谢,话说这波是b服总算和其它版本统一了是吧
