### ISSUE TITLE
会客室如果进去后在更换情报到一半的问题 

### ISSUE THREAD

**Issue by CCFF00** [MaaAssistantArknights/MaaAssistantArknights#2554]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

会客室选择情报时，交流结束了，会导致maa直接卡住，之后他会直接进行退出，然后下一步，b服需要增加一个点击确定个人协议的检测，这玩意几乎每天都会跳出来

### 日志文件

手机登的 暂时没有

**Comment by MistEO** [comment]
- 会客室选择情报时，交流结束了，会导致maa直接卡住，之后他会直接进行退出  
    发下日志，难道你 maa 也是手机用的。。
- b服需要增加一个点击确定个人协议的检测，这玩意几乎每天都会跳出来  
    用户协议这种东西有法律风险，我们开发组内部讨论过，不会去点的

**Comment by CCFF00** [comment]
maa不是手机用的 实际上的问题是 如果用maa定时去开会议室 那么必然会遇到会客室交流差几秒结束，如果在更换线索的一半交流结束 跳出那个结束界面 就会导致卡住
&nbsp;


3377638322
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月5日(星期六) 下午5:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 会客室如果进去后在更换情报到一半的问题  (Issue #2554)





  
会客室选择情报时，交流结束了，会导致maa直接卡住，之后他会直接进行退出
 发下日志，难道你 maa 也是手机用的。。
 
b服需要增加一个点击确定个人协议的检测，这玩意几乎每天都会跳出来
 用户协议这种东西有法律风险，我们开发组内部讨论过，不会去点的
