### ISSUE TITLE
MUMU完成任务后报错，MAA闪退

### ISSUE THREAD

**Issue by Nenot233** [MaaAssistantArknights/MaaAssistantArknights#2555]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

完成任务后报错，MAA闪退

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9914866/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/108965579/199367638-33d2175b-5e5b-43e4-b66b-a2a440dd0c9d.png)

**Comment by MistEO** [comment]
用管理员打开 MAA 试试，mumu 是管理员启动的，MAA 没权限的话杀不掉它

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2607 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2606
