### ISSUE TITLE
建议加入更新进度提示

### ISSUE THREAD

**Issue by JesseGreenWhale** [MaaAssistantArknights/MaaAssistantArknights#2557]
### 说说你遇到的问题？

目前的更新是静默更新的，也不知道什么更新完毕应该重启MAA，希望可以加入一下下载更新和安装的进度提示？

**Comment by zzyyyl** [comment]
> 目前的更新是静默更新的，也不知道什么更新完毕应该重启MAA

更新完有消息弹出的，新版甚至有弹窗问你要不要重启

**Comment by xingyu1272** [comment]
> > 目前的更新是静默更新的，也不知道什么更新完毕应该重启MAA
> 
> 更新完有消息弹出的，新版甚至有弹窗问你要不要重启

（）但是新版本昨天开始下 今天下了一天也没下好 加个进度条至少可以判断一下到底是网络问题还是单纯下的慢

**Comment by xingyu1272** [comment]
> > > 目前的更新是静默更新的，也不知道什么更新完毕应该重启MAA
> > 
> > 
> > 更新完有消息弹出的，新版甚至有弹窗问你要不要重启
> 
> （）但是新版本昨天开始下 今天下了一天也没下好 加个进度条至少可以判断一下到底是网络问题还是单纯下的慢

看了眼 每次打开都会出现更新提示（已经开始下载）但是现在甚至才是v4.6.5-beta.1版本（好久没更新成功过了）

**Comment by zzyyyl** [comment]
新版本网络问题会弹消息的，没弹消息就是正在下载，下完了也会弹个消息

**Comment by zzyyyl** [comment]
手动更新一下 v4.6.6 吧）

**Comment by 545426** [comment]
你可以打开MAA目录查看aria2格式和temp格式文件来查看是否成功下载OTA更新包，下载成功后两个文件会合并成zip文件

**Comment by MistEO** [comment]
进度条不是我们不加，是不会加。。Toast 进度条不太好写，解析 aria2 的下载进度也很麻烦
