### ISSUE TITLE
Maa识别不了/识别模糊字体：野鬃

### ISSUE THREAD

**Issue by KagarinoKirie123** [MaaAssistantArknights/MaaAssistantArknights#2559]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在基建抓野鬃的时候找不到，找了三圈看到了都忽略了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9916775/asst.log)
时间点：11-02 13:47:23

### 截图

![Uploading ZUYDIF3NZOY8FRC6W00KM]7.png…]()

### 还有别的吗？

没有了

**Comment by Fky2172** [comment]
日志打开是乱码，截图也没上传成功。
这种问题可能是干员名字打错或者多了个空格导致的，可以再把排班表文件上传吗

**Comment by KagarinoKirie123** [comment]
好的，图片可能是格式原因？我再上传一次试试
[1667365002752076.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9917777/1667365002752076.txt)
![jietu](https://user-images.githubusercontent.com/117255936/199433494-cec699e1-613a-4d21-8699-e54b152dfa66.jpg)

**Comment by Fky2172** [comment]
看了下不是排班文件的问题，你模拟器分辨率和dpi设置的多少

**Comment by KagarinoKirie123** [comment]
1600*900 dpi240

**Comment by KagarinoKirie123** [comment]
我把日志文件压缩发一下试试
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9918924/asst.zip)

**Comment by ABA2396** [comment]
分辨率低了，野鬃识别成野紫了

**Comment by KagarinoKirie123** [comment]
原来是这样...
