### ISSUE TITLE
水月肉鸽-领取地区委托奖励以获得蚀刻章

### ISSUE THREAD

**Issue by xzjjasper** [MaaAssistantArknights/MaaAssistantArknights#2560]
### 说说你遇到的问题？

水月肉鸽蚀刻章中有一项“完成30次地区委托”，希望maa可以在挂机肉鸽时可以顺便完成。

### 有什么好的想法？

目前maa可以接受地区委托，添加 领取完成地区委托后的奖励 功能即可。

**Comment by ntgmc** [comment]
这个只能手动，因为maa没法判断哪个委托更简单，并且也不会领奖励
