### ISSUE TITLE
双开下无法正确退出模拟器

### ISSUE THREAD

**Issue by weedi0** [MaaAssistantArknights/MaaAssistantArknights#2561]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

双开启动、连接、执行、任务结束退出app都能正确执行，尝试任务结束退出模拟器，2个双开窗口都只能结束模拟器的默认窗口，无法正确关闭分身。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9917845/asst.log)

**Comment by MobiusT** [comment]
我是用蓝叠国际版双开 选择完成后关闭模拟器时
会导致其中一个maa完成任务后直接关闭全部模拟器，而不是正在连接的那个

**Comment by ABA2396** [comment]
> 我是用蓝叠国际版双开 选择完成后关闭模拟器时
> 会导致其中一个maa完成任务后直接关闭全部模拟器，而不是正在连接的那个

你把两个模拟器的名字都改一下，名字中不要出现蓝叠或者明日方舟等相关内容试试。

**Comment by MobiusT** [comment]
确实可以了，感谢
