### ISSUE TITLE
更新4.6.6之后日服完成战斗必定变成游戏崩溃,重新启动

### ISSUE THREAD

**Issue by 2314933036** [MaaAssistantArknights/MaaAssistantArknights#2563]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如题,更新前在截图中勾选的功能除启动有bug外基本正常,未勾选功能不可用

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9919436/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/38069007/199466530-8262cf12-a403-45b1-a0e7-44ff0d9f068e.png)

**Comment by 2314933036** [comment]
更新4.6.6前除了上述严重bug外,
1.日服自动公招只能招募3个,设置无效
![image](https://user-images.githubusercontent.com/38069007/199468354-49fe1ff1-bc9e-4f62-827f-abb99e0b3288.png)
2.上述日服启动bug为启动卡住,不会点击登录,不会关闭公告弹窗
3.日服与官服双开情况下,两个maa会互相顶掉对方的模拟器连接
日服 mumu127.0.0.1:7555
官服 蓝叠 127.0.0.1:5555
![image](https://user-images.githubusercontent.com/38069007/199469151-73e1ab1e-952e-4cc6-a62c-373c520d70e5.png)

**Comment by ABA2396** [comment]
其他不知道，第三点那个是因为adb启动的时候会杀掉其他版本的adb，你试试自己下个adb然后两个maa都用那个

**Comment by horror-proton** [comment]
> 1.日服自动公招只能招募3个,设置无效

公招只招募 3 个的情况有日志吗, 好像其他服也有这个问题

**Comment by horror-proton** [comment]
完成战斗可能是因为 v4.6.6 更新可能有点问题, 可以尝试手动下载完整版本, 把软件的 resource 目录整个替换掉

**Comment by 2314933036** [comment]
> 其他不知道，第三点那个是因为adb启动的时候会杀掉其他版本的adb，你试试自己下个adb然后两个maa都用那个

这个可以了

**Comment by 2314933036** [comment]
> 完成战斗可能是因为 v4.6.6 更新可能有点问题, 可以尝试手动下载完整版本, 把软件的 resource 目录整个替换掉

晚上试一下

**Comment by MistEO** [comment]
> > 完成战斗可能是因为 v4.6.6 更新可能有点问题, 可以尝试手动下载完整版本, 把软件的 resource 目录整个替换掉
> 
> 晚上试一下

直接试试 beta 版本，外服任务整个重构了

**Comment by 2314933036** [comment]
> > > 完成战斗可能是因为 v4.6.6 更新可能有点问题, 可以尝试手动下载完整版本, 把软件的 resource 目录整个替换掉
> > 
> > 
> > 晚上试一下
> 
> 直接试试 beta 版本，外服任务整个重构了

不行,已经更新到4.6.7了,更新完resource文件夹也重新手动解压覆盖过了,日服还是完全用不了

**Comment by zzyyyl** [comment]
这不是识别错误。是你战斗结束的黑屏时间太长了 maa 以为你闪退了（

**Comment by 2314933036** [comment]
> 这不是识别错误。是你战斗结束的黑屏时间太长了 maa 以为你闪退了（

不是,他结束到这个页面就1秒不到怎么会太长

**Comment by zzyyyl** [comment]
有可能是资源里 EndOfAction 没删，建议重新下一次：）

**Comment by 2314933036** [comment]
> 有可能是资源里 EndOfAction 没删，建议重新下一次：）

那配置是不是把gui.json再放进去就可以了？
