### ISSUE TITLE
信用商店中卡住

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#2564]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

海外党，信用商店购买后卡在这个界面。
此问题于[#1349](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1349) 提出，问题已被关闭，但我依旧能经常遇到这个问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9919787/asst.log)

### 截图

![MuMu20221102221608](https://user-images.githubusercontent.com/74366156/199476379-d8c5d4e1-bb64-4e9b-807b-c7a025558ccc.png)
![image](https://user-images.githubusercontent.com/74366156/199476554-f88ba911-ed78-422f-9a64-a65999dbd280.png)

![image](https://user-images.githubusercontent.com/74366156/199476966-4bbe13bf-ebe6-4b68-9f9f-0501200305fb.png)

### 还有别的吗？

系统为win11
模拟器mumu模拟器
软件版本号v4.6.6

**Comment by kxdxzr** [comment]
![MuMu20221103132135](https://user-images.githubusercontent.com/74366156/199636487-b3b5fbba-e6a4-4b17-9641-08681a32c7c6.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9925258/asst.log)

**Comment by MistEO** [comment]
看起来是个回归问题，之前应该是修好了的，新版本又被改坏了
