### ISSUE TITLE
更新后水月肉鸽第一关都打不过去，一直重复

### ISSUE THREAD

**Issue by lingxinquan** [MaaAssistantArknights/MaaAssistantArknights#2571]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

更新后第一关都打不过去，一直重复

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9922351/gui.log)

### 截图

![image](https://user-images.githubusercontent.com/32209941/199545603-461714cd-65f1-41b1-89fb-586ced297e70.png)

**Comment by zzyyyl** [comment]
gui.log没用，发asst.log

**Comment by lingxinquan** [comment]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9922503/asst.zip)
@zzyyyl

**Comment by MistEO** [comment]
方便录个屏看看为啥没打过？我看日志都挺正常的，莫名其妙死了。是不是难度选错了（

**Comment by zzyyyl** [comment]
你的模拟器是不是卡的一批
