### ISSUE TITLE
宿舍换班信赖值挡住名字导致无法识别

### ISSUE THREAD

**Issue by Zerohound** [MaaAssistantArknights/MaaAssistantArknights#2572]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

maa中勾选“宿舍空余位置蹭信赖”时，蹭信赖过程中，如果剩下的位置里设置了指定干员进驻指定位置，会被信赖值挡住名字而识别不到人

### 日志文件

日志文件看不出问题我就不传了

### 截图

![Screenshot_20221103-003837](https://user-images.githubusercontent.com/86946902/199548944-0d66fa0e-7bdb-4d6c-8672-8d7557d4fcfb.png)

**Comment by MistEO** [comment]
传下 asst.log

**Comment by Zerohound** [comment]
> 传下 asst.log

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9925705/asst.log)
时间是2022/11/2 23:23:52
