### ISSUE TITLE
承曦格雷伊基建优化

### ISSUE THREAD

**Issue by FrecklySoda** [MaaAssistantArknights/MaaAssistantArknights#2574]
### 说说你遇到的问题？

承曦格雷伊现在已经可以和格雷伊同时上班了，然而自动换班并不会优先选择承曦格雷伊。尽管承曦格雷伊有20%的发电效率脚本仍然会优先选择15%甚至更低的干员。如果能优化一下这个小问题那真是再好不过了。

### 其他内容

![image](https://user-images.githubusercontent.com/115042741/199621293-87b48a18-e6ef-431f-93d2-35b8d0747538.png)

**Comment by MistEO** [comment]
改到是好改，外服的基建适配又要往后推了 orz
