### ISSUE TITLE
当新活动的战斗按钮没有展开时, 不会自动点击

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaAssistantArknights#2575]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

![image](https://user-images.githubusercontent.com/72590023/199622401-7fb2eb8b-d283-4049-ab80-9f08110aab36.png)

如图, 当右下角没有展开时会卡住

![image](https://user-images.githubusercontent.com/72590023/199622455-bf65edf0-703b-4950-a30c-bc226c33a3b1.png)

手动点开后就恢复了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9924806/asst.log)

**Comment by MistEO** [comment]
@ABA2396 这个是不是修过了？

**Comment by ABA2396** [comment]
> @ABA2396 这个是不是修过了？

是的，就在你发完没多久（）
