### ISSUE TITLE
 “信用溢出时无视黑名单” 功能无效

### ISSUE THREAD

**Issue by dddcm** [MaaAssistantArknights/MaaAssistantArknights#2576]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

信用400/300，信用商店剩下的商品全在我的黑名单里，勾选了“信用溢出时无视黑名单”，运行maa信用购物，不会购买任何物品

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9925016/asst.log)

### 截图

https://user-images.githubusercontent.com/116613044/199628948-1420d20c-b35d-44c6-8b6b-17d6adc3c931.mp4

### 还有别的吗？

蓝叠
maa 4.6.6

**Comment by dddcm** [comment]
对不起，我突然发现好像又生效了，可能是修改后没有重启maa的原因，对不起

**Comment by MistEO** [comment]
应该不用重启 maa 的，设置里没提示重启都是实时生效的，这个 bug 可能确实存在
