### ISSUE TITLE
刷肉鸽时显示截屏上传失败，并且打到水第三层闪退

### ISSUE THREAD

**Issue by Cerimy** [MaaAssistantArknights/MaaAssistantArknights#2581]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [ ] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

刷肉鸽时连续出现截图上传失败，然后有时候就会卡死闪退，后来变成开始正常，到水月肉鸽第三层MAA就闪退

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9926488/asst.log)

### 还有别的吗？

雷电模拟器国际版9.0.27.0

**Comment by MistEO** [comment]
截图上传失败？啥意思

**Comment by Cerimy** [comment]
后面就闪退了


不客气
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 刷肉鸽时显示截屏上传失败，并且打到水第三层闪退 (Issue #2581)





 
截图上传失败？啥意思

**Comment by MistEO** [comment]
雷电的问题，换个模拟器

![image](https://user-images.githubusercontent.com/18511905/199688944-e313ccfb-be88-40df-b336-6501f273dffd.png)

**Comment by MistEO** [comment]
参考 [模拟器支持文档](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.md)

**Comment by Cerimy** [comment]
原来如此，感谢回答




不客气
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 刷肉鸽时显示截屏上传失败，并且打到水第三层闪退 (Issue #2581)





 
雷电的问题，换个模拟器
