### ISSUE TITLE
夜神模拟器更新明日方舟B服后无法自动打开

### ISSUE THREAD

**Issue by 3221775697** [MaaAssistantArknights/MaaAssistantArknights#2585]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我设置了开机自启和自动运行MAA，之前一切正常，但昨夜神模拟器更新明日方舟B服后（好像期间自动更新了MAA），MAA自启后无法识别到明日方舟B服启动图标，从昨天到今天一直都这样，但我手动点开明日方舟，后续就能正常刷体力等功能，我删除MAA重新下载也没用了，

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9927606/asst.log)

### 截图

![Screenshot_20221103-184552](https://user-images.githubusercontent.com/117355237/199702334-18b677cb-f953-40d7-b954-0171c698e92f.png)

**Comment by ABA2396** [comment]
> ### 在提问之前...
> * [ ]  我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

[v4.6.7-beta.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.6.7-beta.1) fixed
