### ISSUE TITLE
OTA升级异常

### ISSUE THREAD

**Issue by Fky2172** [MaaAssistantArknights/MaaAssistantArknights#2586]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

把OTA包放进MAA同目录下，打开MAA无法自动升级（设置里更新版本三个都选过了），之前（4.6.5beta1之前）是可以正常OTA更新的
![image](https://user-images.githubusercontent.com/115487706/199702831-70de4c9a-8c32-48f8-9d65-9558e77146fc.png)

### 日志文件

[2022-11-03 18:45:41.052]，用了一个今天没开过的MAA试过了，怎么都更新不了，今天的日志都是反复打开MAA看能不能更新
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9927622/asst.log)

### 还有别的吗？

蓝叠5国际版64位，win10 21H2

**Comment by dddcm** [comment]
原来是这么用的吗，我是直接解压缩ota包覆盖到目录下

**Comment by superybq** [comment]
把MAAComponent-OTA-v4.6.7-beta.1-win-x64.zip改名成MAAComponent-OTA-v4.6.6_v4.6.7-beta.1-win-x64.zip就行了

**Comment by zzyyyl** [comment]
现在的 OTA 要从 MaaRelease 仓库下

**Comment by zzyyyl** [comment]
@horror-proton @MistEO 要不要考虑把主仓库的 OTA 删了）

**Comment by MistEO** [comment]
> @horror-proton @MistEO 要不要考虑把主仓库 CI 的 OTA 删了）

要兼容下老版本，不然没得下了，过段时间删吧？
