### ISSUE TITLE
macOS系统肉鸽开局干员为"山"时设置失效

### ISSUE THREAD

**Issue by Jimmer1993** [MaaAssistantArknights/MaaAssistantArknights#2589]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

mac系统下,自动肉鸽指定开局干员为"山",但设置没有生效。
日志提示"Cannot find oper `山`"

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9929941/asst.log)

### 截图

maa肉鸽设置:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/48347380/199742544-16353fb9-f85d-410a-ad84-d3013239770e.png">

模拟器干员选择界面
<img width="669" alt="image" src="https://user-images.githubusercontent.com/48347380/199745045-e0b836a6-1d06-44d2-bca4-8458d1fc1ed8.png">
<img width="621" alt="image" src="https://user-images.githubusercontent.com/48347380/199745072-a90da5ed-8247-49da-b800-f4f16a97b320.png">

### 还有别的吗？

操作系统:macOS 12.3.1 
模拟器:夜神模拟器 3.8.5.7

**Comment by Jimmer1993** [comment]
补充:模拟器分辨率1600*900

**Comment by MistEO** [comment]
一般来说 OCR 模型对笔画简单的单字的识别效果都不是很好，Windows 上没有这个问题是因为用的和 macOS 不是同一个模型，mac 上我估计是不太好弄

cc @hguandl

**Comment by hguandl** [comment]
@Jimmer1993 请问在 v4.6.12 之后，此问题是否还存在

**Comment by Jimmer1993** [comment]
@hguandl v4.6.13仍然存在。
<img width="708" alt="image" src="https://user-images.githubusercontent.com/48347380/202108828-d927028a-bb86-45b8-9d64-6a56861a1ddf.png">
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/48347380/202108851-766852d8-1b89-40bf-afb5-29b239513ae2.png">

**Comment by hguandl** [comment]
macOS 13.0.1 下是有结果的，应该是 revision 3 的 OCR 模型可以识别，Monterey 用的 rev 2 可能不太擅长识别出这种单字。

**Comment by MistEO** [comment]
maa core 修了，等有 mac 版本就修复了

**Comment by hguandl** [comment]
[v4.8.4](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.8.4) 已修复。
