### ISSUE TITLE
自动更新不显示叙古拉人活动关卡的问题

### ISSUE THREAD

**Issue by 666233j** [MaaAssistantArknights/MaaAssistantArknights#2595]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

用的在线更新可是
刷理智-关卡选择和剩余理智都不会显示最新活动关卡

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9937715/asst.zip)

**Comment by zzyyyl** [comment]
@ABA2396

**Comment by MistEO** [comment]
v4.6.6 没加关卡导航，看发版记录
