### ISSUE TITLE
不能自动更新测试版

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#2597]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

MAA不能自动更新。我的MAA版本是4.6.6，下载了4.7.7beta1的压缩包，放到目录中，不能自动安装更新。更新检测也能检测到更新，但是打开自动下载更新包之后也不能自动下载更新。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9939311/asst.log)

**Comment by MistEO** [comment]
自动更新改版了，直接解压覆盖吧，一样的。后面会有更完善的方案
