### ISSUE TITLE
干员扫描+缺失干员一览

### ISSUE THREAD

**Issue by happyhaddy99** [MaaAssistantArknights/MaaAssistantArknights#2598]
### 说说你遇到的问题？

对于干员缺失较少的老玩家或全图鉴党，希望做一个类似仓库扫描的干员扫描功能，方便得知缺失干员
目前官方只展示已拥有干员总数，人工统计较为困难

### 有什么好的想法？

结果可以按稀有度、职业等维度展示

**Comment by MistEO** [comment]
duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1855
