### ISSUE TITLE
Mac版本刷理智，一次只打一遍关卡

### ISSUE THREAD

**Issue by Themistes** [MaaAssistantArknights/MaaAssistantArknights#2599]
仅勾选刷理智，关卡设置为当前/上一次时（关卡为叙拉古人活动图IS-8）。每次点一键长草后，只刷一次关卡，然后就显示任务完成，自动结束。后续又进行测试，如果刷理智的模式设置为当前/上一次，但是关卡为1-7的话，则可以稳定重复刷图直到理智不够。

**Comment by MistEO** [comment]
测试版修过了
