### ISSUE TITLE
建议不要奶羽毛笔了

### ISSUE THREAD

**Issue by kiponfu** [MaaAssistantArknights/MaaAssistantArknights#2600]
### 说说你遇到的问题？

肉鸽羽毛笔梓兰安塞尔，安塞尔总是朝着羽毛笔，明明不能被奶……

**Comment by WWPXX233** [comment]
因为医疗干员是尽可能的覆盖更多的干员，MAA并不知道该角色是否能被治疗

**Comment by kiponfu** [comment]
这个逻辑我还是很认同的，不过嘛，可能有时候实现的不是很好。比如我有一把看到安塞尔朝着羽毛笔，梓兰部署在在他正后方，正在被射手打，但是奶不到。
“你就这么看着吗，安塞尔……”倒下的梓兰如是说

**Comment by WWPXX233** [comment]
因为在maa看来没有差别的都是干员能23333
