### ISSUE TITLE
(Unknown Item) Cant Upload Event data for Penguin Stats

### ISSUE THREAD

**Issue by wallsman** [MaaAssistantArknights/MaaAssistantArknights#2601]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I spent at least 5 minutes thinking and preparing before raising the issue.
- [X] I have read the FAQ and the User Manual in the documentation and believe that this is most likely a bug and not designed to be so.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] The screenshots I've uploaded are the original ones taken by the emulator's own screenshot tool (or via adb).

### Description

Detected Event Drop for Unknown Item.
I expect the error is probably common to all international clients as well.

Would adding event item data to `Glossary` in the future help?

### Log files

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9941740/gui.log)

### Screenshots

![image](https://user-images.githubusercontent.com/63186641/200067468-3576f86f-e6db-4154-9d3b-a0b3f65326a6.png)

**Comment by MistEO** [comment]
What new levels have been added to the JP client recently?

There are some screenshots under `debug/drops/`, could you send them to see?

**Comment by MistEO** [comment]
> What new levels have been added to the JP client recently?
> 
> There are some screenshots under `debug/drops/`, could you send them to see?

It did update, no need to upload for now.
