### ISSUE TITLE
自定义基建 在点击选择了一次基建计划之后 无法按时间选择相应的配置

### ISSUE THREAD

**Issue by ShudaoWei** [MaaAssistantArknights/MaaAssistantArknights#2602]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

使用自定义基建后，可能是因为手动选择过基建计划，导致现在MAA无法根据系统时间选择相应的自定义基建配置。
即使重新在设置中选择json文件，基建计划栏恢复空白，但运行结果仍保持手动选择过的那个时间段的配置不变。
需要一个恢复的方法，或者MAA硬设置为读取了带时段的json文件后不可手动选择。
辛苦各位建设者。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9942372/asst.log)
简单的测试都在log文件最后，包括直接运行基建换班，重新选取json文件后使用基建换班，点击正确的时间对应配置后再运行基建换班（确认能够正确运行，因此问题确认为基建计划的选项优先覆盖了json文件中的时间，并无法恢复自动选择）

**Comment by MistEO** [comment]
应该不会吧，现在的问题反而是设置的时间会强行覆盖掉手动操作的，即手动操作无效（

时间设置不是立即刷新的，每分钟才会去刷新一次
