### ISSUE TITLE
搓玉制造站错误的摆放了赤金三人组

### ISSUE THREAD

**Issue by qthzrv** [MaaAssistantArknights/MaaAssistantArknights#2603]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

使用的默认的排班，maa却把巫恋，龙舌兰，卡夫卡放到搓玉的制造站中
连续好几天都是这样

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9942656/asst.log)

### 截图

![Snipaste_2022-11-05_09-02-42](https://user-images.githubusercontent.com/110768125/200094727-2f27b297-8706-44af-9c11-571d55b8dd4c.png)

### 还有别的吗？

mumu模拟器，用的是开发版，系统win11

**Comment by MistEO** [comment]
他们三个也加合成玉的吧，好像没毛病啊

**Comment by qthzrv** [comment]
> 他们三个也加合成玉的吧，好像没毛病啊

好像也是，但会浪费赤金的加成，拿这样不如带两个提供订单上限的工具人

**Comment by MistEO** [comment]
MAA 的自动基建是贪心算法，会把效率高的放序号靠前的站。你可以考虑让 1 号站造龙门币，2 号站再造合成玉
