### ISSUE TITLE
水月肉鸽一直卡在分队选择界面

### ISSUE THREAD

**Issue by 327968** [MaaAssistantArknights/MaaAssistantArknights#2604]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

开始以后一直在分队选择界面左右滑动，不会选择分队。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9942856/asst.log)

### 截图

![6KY(`CP{`ALXY6}WW(%AUNS](https://user-images.githubusercontent.com/115909469/200097647-9087f8d0-d5e6-4dcd-82df-5a396b78ab57.png)
![Screenshot_20221105-104444](https://user-images.githubusercontent.com/115909469/200097685-47c40b5c-88a6-4e37-901e-effdaa809d80.png)

### 还有别的吗？

夜神模拟器

**Comment by MistEO** [comment]
有人反馈过相同的问题，OCR 结果完全是乱的，不知道为什么。你试试把 MAA 整个删了，重新下载个完整包，看有没有用
