### ISSUE TITLE
战斗结束退出mumu模拟器和MAA失败

### ISSUE THREAD

**Issue by Realjayden** [MaaAssistantArknights/MaaAssistantArknights#2606]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我使用的是mumu模拟器，MAA版本为4.6.6。晚上睡觉前碎石头换了900+理智，挂上去刷is-8，设定刷完体力后自动关闭模拟器和MAA，并休眠。结果第二天起来发现MAA报错，MAA和模拟器都没有成功退出，电脑也没有休眠。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9942948/asst.log)
报错时间大致为半夜0:00-2:00之间

### 截图

![~QS4NWMU8SSGINL}VY38P~C](https://user-images.githubusercontent.com/89341955/200099440-53c857b4-6869-450e-90c6-b47a9ccc6f1e.png)
![4G1C$3%SR9P45_TNRWDTL)0](https://user-images.githubusercontent.com/89341955/200099517-2e790406-a265-4e64-9e04-eab9e8d73cf2.png)

### 还有别的吗？

模拟器：mumu模拟器
操作系统：Windows11 21H2

**Comment by MistEO** [comment]
用管理员打开 MAA 试试，mumu 是管理员启动的，MAA 没权限的话杀不掉它

**Comment by Realjayden** [comment]
> 用管理员打开 MAA 试试，mumu 是管理员启动的，MAA 没权限的话杀不掉它

谢谢 经测试已解决
