### ISSUE TITLE
完成后自动退出mumu模拟器时报错

### ISSUE THREAD

**Issue by DeathofBrain** [MaaAssistantArknights/MaaAssistantArknights#2607]
在 System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   在 System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   在 System.Diagnostics.Process.get_HasExited()
   在 MeoAsstGui.TaskQueueViewModel.KillEumlatorbyWindow()
   在 MeoAsstGui.TaskQueueViewModel.CheckAfterCompleted()
   在 MeoAsstGui.AsstProxy.ProcTaskChainMsg(AsstMsg msg, JObject details)
   在 MeoAsstGui.AsstProxy.ProcMsg(AsstMsg msg, JObject details)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by DeathofBrain** [comment]
用的是MuMu模拟器

**Comment by MistEO** [comment]
用管理员打开 MAA 试试，mumu 是管理员启动的，MAA 没权限的话杀不掉它

**Comment by MistEO** [comment]
duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2606

**Comment by DeathofBrain** [comment]
感谢，忘了这茬事了
