### ISSUE TITLE
自动公招不会选取多个四星tag减少被划机率

### ISSUE THREAD

**Issue by YuhangTom** [MaaAssistantArknights/MaaAssistantArknights#2608]
### 说说你遇到的问题？

自动公招不会选择多个四星tag减少被划机率 如快速复活+爆发只选择快速复活而不选择爆发 两个一起选能减少被划机率
<img width="144" alt="image" src="https://user-images.githubusercontent.com/45880737/200105733-d6b0aa84-b8bb-46ca-9336-13fbb9c6a9c6.png">

### 有什么好的想法？

当出现稳定四星tag（快速复活、爆发、支援）时一次选取多个

### 其他内容

<img width="144" alt="image" src="https://user-images.githubusercontent.com/45880737/200105733-d6b0aa84-b8bb-46ca-9336-13fbb9c6a9c6.png">

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9943191/asst.log)

MAA v4.6.6

BlueStacks App Player v5.9.300.1018

**Comment by MistEO** [comment]
这个问题之前讨论过，这样会不会有 快速复活 + 近卫 + 减速，结果 快速复活 和 近卫 都被划掉的情况（

**Comment by YuhangTom** [comment]
近卫/减速并不能稳定出4星，只有近卫+减速才会出，我说的是稳定出4星的tag同时出现时选取多个，目前只有

1. 爆发
2. 支援
3. 削弱
4. 快速复活
5. 位移

选择多个划掉也是必出4星，不会出现你所说的情况，当然4星tag和有可能出4星的3星tag同时出现时还是优先4星tag

**Comment by zzyyyl** [comment]
要不来个 PR（

**Comment by YuhangTom** [comment]
太难了我投降（看了眼储存空间装VScode都够呛
