### ISSUE TITLE
肉鸽中由于技能就绪黄色图标被顶部UI遮挡导致无法自动释放干员技能

### ISSUE THREAD

**Issue by Mo-Yuxi** [MaaAssistantArknights/MaaAssistantArknights#2609]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

该现象于傀影肉鸽中发现，大概的发生时间2022-11-05-14:55-14:56期间，位于顶部一排的干员(图中为德狗以及梓兰)被部署后从未自动释放技能，而手动点击干员进入子弹时间也未能让MAA释放干员技能

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9943278/asst.zip)
大概的发生时间2022-11-05-14:55-14:56期间，图中德狗、梓兰技能就绪黄色小闪电图标被顶部统计UI遮挡

### 截图

![Uploading Screenshot_2022.11.05_14.57.01.124.png…]()
截图通过蓝叠自带工具截取，截取时手动暂停了游戏

### 还有别的吗？

模拟器：蓝叠5国际版 5.9.300.1018 N64
MAA版本：4.6.6
系统版本：Win10x64

**Comment by Mo-Yuxi** [comment]
截图重上传
![Screenshot_2022 11 05_14 57 01 124](https://user-images.githubusercontent.com/80117830/200108024-eeeaa539-f3cd-437f-ace9-bef50657f56a.png)

**Comment by MistEO** [comment]
这个问题靠传统图像算法比较难解决，我们在尝试深度学习的方案了，但是开发组里会炼丹的佬太少 ~~太咕~~ 了。所以如果有会炼丹的佬，欢迎加入我们 ✿✿ヽ(°▽°)ノ✿

**Comment by Mo-Yuxi** [comment]
谢邀，算法入门学生一位，深度算法还没学过大概搓不来/搓的整个就是个BUG
不过刚刚尝试叠了个图试想了一个思路：
对于不同地图大小的关卡中，干员血条UI和技能就绪位置图标尺寸和距离是固定的，而且技能就绪后的图标会有闪动效果，一般UI很难遇到完全遮挡整个技能就绪图标的，且技能图标闪动是按固定频率的，且BUG出现位置位于UI周围即画面顶部，不会与下方的各种打斗动画重合。不知是否可以尝试“对统计UI下方一定范围内的可被检测到的血条UI的中轴位置靠上xx像素位置的一个菱形区域内是否有闪动的动画效果”
![result](https://user-images.githubusercontent.com/80117830/200113103-3be125a7-cebc-4ba6-82cb-c02d2612a5fe.png)

当然期望一个深度学习佬一键修补整个bug，祝项目组越办越好

**Comment by horror-proton** [comment]
> 是否可以尝试“对统计UI下方一定范围内的可被检测到的血条UI的中轴位置靠上xx像素位置的一个菱形区域内是否有闪动的动画效果

这个恐怕得积分很长时间才能显现出来, MAA 现在用的是截图, 帧率非常有限, 应该比会较难

我觉得检测这个用直接用 color keying 效果应该就不错, 只需要填进去被遮挡和未被遮挡的两种颜色, 技能图标图层比较搞, 也不容易被渐变什么的干扰

**Comment by MistEO** [comment]
丹练好了，敬请期待（

**Comment by horror-proton** [comment]
![image](https://user-images.githubusercontent.com/107091537/200167511-7505f569-524a-43dd-a8b6-cf045dfe234f.png)

~~说起来还有一些特别糟糕的情况~~

**Comment by Mo-Yuxi** [comment]
> ~说起来还有一些特别糟糕的情况~

~几乎完全遮挡可真是emmm~
期待新版本了ovo

**Comment by horror-proton** [comment]
fixed in v4.8.0
