### ISSUE TITLE
卡死与闪退

### ISSUE THREAD

**Issue by cglcv** [MaaAssistantArknights/MaaAssistantArknights#261]
版本3.0.6，连接的模拟器为蓝叠5.5，后台有其他模拟器运行，使用自定义adb
点击link start后程序UI卡死，但adb操作正常，运行两次后闪退（之前也有闪退的情况）
日志
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8174326/asst.log)
截图
![屏幕截图 2022-03-03 095835](https://user-images.githubusercontent.com/35825310/156483451-bd22334b-9e42-49d6-8493-e1378bb11f93.png)

PS：助手运行过程中其他模拟器（助手不识别的）会对程序运行产生影响吗

**Comment by cglcv** [comment]
感觉程序卡死的原因和#255 一样，连接模拟器卡死之后输了个adb kill-server之后连接掉了，程序活过来了

**Comment by MistEO** [comment]
这种情况是不是 reconnect 就可以了，之后会尝试支持一下

**Comment by cglcv** [comment]
> ~这种情况是不是 reconnect 就可以了，之后会尝试支持一下~
> 
> 理解错了，是正在连接的时候点击了`停止`按钮是吧。这种情况确实有 bug, 先不要这么用，后期交给新 UI 来修（

我没点停止啊

**Comment by MistEO** [comment]
> > ~这种情况是不是 reconnect 就可以了，之后会尝试支持一下~
> > 理解错了，是正在连接的时候点击了`停止`按钮是吧。这种情况确实有 bug, 先不要这么用，后期交给新 UI 来修（
> 
> 我没点停止啊

好怪，反正是 UI 的问题，摆了 _(:з」∠)_

**Comment by MistEO** [comment]
这个修了，忘了啥版本了，总之_(:з」∠)_
