### ISSUE TITLE
建议扩充关卡选择的内容

### ISSUE THREAD

**Issue by ylsy2002** [MaaAssistantArknights/MaaAssistantArknights#2610]
### 有什么好的想法？

建议在关卡选择内增加各种材料刷素材推荐关卡，[https://aog.wiki/](https://aog.wiki/)有统计短期/长期最优（给企鹅物流提供那么多数据总得用起来

**Comment by zzyyyl** [comment]
![image](https://user-images.githubusercontent.com/74587068/200110861-3ca49d69-16cf-49b0-9192-22319a11340c.png)

**Comment by ylsy2002** [comment]
。。。

**Comment by MistEO** [comment]
现在手动输入是支持全部主线关卡+高性价比插曲/别传关卡的。下拉框没有是因为太多了，不知道怎么展示比较好
