### ISSUE TITLE
傀影肉鸽挑选干员策略是否有问题？

### ISSUE THREAD

**Issue by DeepSpace98** [MaaAssistantArknights/MaaAssistantArknights#2614]
### 说说你遇到的问题？

现在刷傀影肉鸽的话，干员的优先选择策略好像是跟水月一样的，都是海沫开局，但是打傀影的话，实际羽毛笔的实用性更高，希望能在优化一下。

**Comment by MistEO** [comment]
@WWPXX233 我也感觉羽毛笔傀影好用（

**Comment by WWPXX233** [comment]
emmm那要不把羽毛笔搞回来海默扔了）
其实我觉得有山哥就能顶住了

**Comment by MistEO** [comment]
> emmm那要不把羽毛笔搞回来海默扔了） 其实我觉得有山哥就能顶住了

假如人家没有山 _(:з」∠)_

**Comment by DeepSpace98** [comment]
> emmm那要不把羽毛笔搞回来海默扔了） 其实我觉得有山哥就能顶住了

确实，山的优先级可以更高些的

**Comment by DeepSpace98** [comment]
> > emmm那要不把羽毛笔搞回来海默扔了） 其实我觉得有山哥就能顶住了
> 
> 假如人家没有山 _(:з」∠)_

有山选山？没山再羽毛笔，没羽毛笔在海沫(:з」∠)

**Comment by WWPXX233** [comment]
目前我把海默和羽毛笔去掉了）

**Comment by MistEO** [comment]
beta.2 刚发，现在不会抓海沫和羽毛笔了。不过我感觉羽毛笔可以加上，后面的版本再说.jpg
