### ISSUE TITLE
Cant reboot Arknights JP

### ISSUE THREAD

**Issue by wallsman** [MaaAssistantArknights/MaaAssistantArknights#2616]
### The problems you have encountered?

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9943552/asst.log)

やっとログが取れましたので共有します。
何か役に立てれば良いのですが。

I finally got the logs and will share them with you.
Hopefully it will be of some use.

**Comment by MistEO** [comment]
Which issue?

**Comment by wallsman** [comment]
The problem is that the game cannot be restarted in MAA after a game crash.

**Comment by wallsman** [comment]
V4.7.1
Same issue.
Task - Crash - Cant reboot - Task end

But use Wakeup can bootuped.

**Comment by MistEO** [comment]
Has this issue been fixed?

**Comment by wallsman** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3864

Seems to be a recurrence ...

**Comment by zzyyyl** [comment]
这应该是 enhancement，我没理解错的话，是说游戏崩了任务继续不了？（我的建议是换模拟器）现在只有 startup 做了游戏启动，其它的崩溃暂时检测不到。

Duplicate of #1200
