### ISSUE TITLE
启动报错找不到指定的模块MeoAssistant.dll

### ISSUE THREAD

**Issue by dhujsi** [MaaAssistantArknights/MaaAssistantArknights#2620]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

重装系统后重新下载了maa，启动时报错
文件夹中有MeoAssistant.dll但是还是报错
尝试了MAA-v4.6.5-beta.3、MAA-v4.6.7-beta.2、MAA-v4.6.6
4.6.5白屏但是日志里是同样的报错
已关闭smartscreen之类的阻止运行的玩意
尝试复制到system32也没有用
win10 22H2

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9943940/gui.log)

### 截图

![image](https://user-images.githubusercontent.com/63281018/200122821-2de1fe1b-2c6a-41a0-855d-b68e20f2f507.png)
![image](https://user-images.githubusercontent.com/63281018/200122828-89d1fd06-d740-4cb0-a097-7dcce7b84b93.png)

**Comment by zzyyyl** [comment]
参考[这里](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#%E8%BD%AF%E4%BB%B6%E4%B8%80%E6%89%93%E5%BC%80%E5%B0%B1%E9%97%AA%E9%80%80)

**Comment by MistEO** [comment]
按文档里闪退的情况处理即可。以前没这个报错弹窗，直接就崩了，所以文档写的是闪退。最近刚加上这个弹窗，文档还没来得及改

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/200127384-52f380e5-5513-4277-ae18-20716ffa7bb3.png)

改了下报错提示，似乎好一点（
