### ISSUE TITLE
MAA无法连接模拟器

### ISSUE THREAD

**Issue by Ekun11** [MaaAssistantArknights/MaaAssistantArknights#2624]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

开发者好，我换过四款模拟器（现在在用蓝叠），也试过用蓝叠的adb替换掉其他模拟器的adb，试过重启，试过管理员权限打开MAA，试过卸载手机助手，试过把占用5037端口的程序干掉后再打开，全都无法连接

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9944161/asst.log)

### 截图

![连接设置](https://user-images.githubusercontent.com/117529554/200127790-f3286b0b-8210-46a2-b2fe-d4085c466077.jpg)
![失败界面](https://user-images.githubusercontent.com/117529554/200127792-b7d7259f-3722-4a31-ac2f-fabc5c3ead9d.jpg)
![adb已打开](https://user-images.githubusercontent.com/117529554/200127797-920598f8-e3a2-4fec-9c05-ffd59a4600bf.jpg)

**Comment by MistEO** [comment]
把代理/游戏加速器等的都关掉，然后重启下电脑，再试试

**Comment by Ekun11** [comment]
> 把代理/游戏加速器等的都关了，然后重启下电脑，再尝试掉

![1](https://user-images.githubusercontent.com/117529554/200128619-ff16a7bf-df52-412c-ac8f-f99180bbfeae.png)


感谢回复！我重启之后依然失败了
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9944189/asst.log)

**Comment by MistEO** [comment]
所有模拟器都连不上的情况我们之前也没遇到过，几种可能，可以都试下

- 自己下载 adb，adb 地址填自己下的那个
- 在任务管理器里把 adb 相关的进程都关掉
- 看看有没有防火墙、杀毒软件之类的，退一下
- 看看是不是别的哪个进程把 5037 端口占了，杀掉试试

这其实还没到 MAA 跑起来，也可以自己直接在 cmd 里 adb connect 127.0.0.1:5555 试试能不能连上，估计会有一样的报错

**Comment by Ekun11** [comment]
> 有可能，我们之前没有遇到过连上的情况，有几种情况都可以试下
> 
> * 自己下载 adb，adb 地址填写自己下的那个
> * 在任务管理器里把 adb 相关的进程都关掉
> * 看看有没有的防火墙、杀毒软件之类，退一下
> * ~看看是不是别的把进程 5037 占了端口，杀掉试试~哦你已经这个了
> 
> 这其实是MAA跑起来，也可以自己直接在cmd里 adb connect 127.0.1:5555 不能连上，估计一样的报错



谢谢回复！

刚刚我尝试下了一个adb，也把它配置了到了环境变量里，把MAA里的连接路径改成了我下载的adb的位置，还是连接失败
于是我又去看了是哪个程序占用5037端口，顺着找过去发现是adb.exe.........
![cmd](https://user-images.githubusercontent.com/117529554/200164818-7a73d903-f73f-49c4-96eb-7f153302691a.jpg)
![任务管理器进程](https://user-images.githubusercontent.com/117529554/200164828-feea6be7-621f-4295-98b8-56246f3f94ba.png)
![蓝叠adb版本](https://user-images.githubusercontent.com/117529554/200164830-4b746c6d-dd68-49fb-8da5-162493710267.png)

（干掉这个占用5037的adb之后我又试着连接，失败）

我现在发现我的adb是41版本，和29版本的连接不上
于是我又去看了蓝叠adb的版本，是41
我想过是不是我电脑里有多个adb的问题，我下载的adb文件就叫adb，而蓝叠的adb文件叫HD-adb，但二者版本相同都是41

连不上也不是软件的问题而是我电脑adb就没绑定好吧...
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9945574/asst.log)

不好意思给你们添麻烦了

**Comment by Ekun11** [comment]
> 所有模拟器都连不上的情况我们之前也没遇到过，几种可能，可以都试下
> 
> * 自己下载 adb，adb 地址填自己下的那个
> * 在任务管理器里把 adb 相关的进程都关掉
> * 看看有没有防火墙、杀毒软件之类的，退一下
> * ~看看是不是别的哪个进程把 5037 端口占了，杀掉试试~ 哦 你已经试过这个了
> 
> 这其实还没到 MAA 跑起来，也可以自己直接在 cmd 里 adb connect 127.0.0.1:5555 试试能不能连上，估计会有一样的报错



你好，我找到了那个29版本的adb，删掉它之后现在已经可以连接MAA了
感谢！
