### ISSUE TITLE
基建排班表的.json文件里的注释导致无法正常读取

### ISSUE THREAD

**Issue by Kingzom** [MaaAssistantArknights/MaaAssistantArknights#2625]
### 说说你遇到的问题？

我尝试直接在3.6里的例子加上时间来到点自动换班但是报错卡死
最后使用排班器进行对比以后发现区别是复制进去的时候带着注释
经过一点测试发现时间段里的任何注释都会导致MAA读取错误然后跳过基建，如果只运行了基建一个任务就会卡死无法停止
![a13e48c4dc72ba2fe3419f2c4b8cb98](https://user-images.githubusercontent.com/79841799/200131206-f78b621c-04a7-474a-a67d-f0be0af2748d.png)
![66ae90044a17fcc9aa6ec5c8c73a7ff](https://user-images.githubusercontent.com/79841799/200131207-d5c6ecad-45e4-43fe-88ca-447e253d3f5c.png)
![59610e42e1d1fb00dcd7d14fbfa6d18](https://user-images.githubusercontent.com/79841799/200131208-c55520e8-429e-4e43-a718-0354c411e35e.png)
![6111f0badd3e767efd3f4e1e0123f68](https://user-images.githubusercontent.com/79841799/200131209-e3804a55-85de-4eab-aab8-acd486e435ed.png)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9944294/asst.log)

### 有什么好的想法？

也许在3.6的文件里标注下需要删掉注释会比较好？

**Comment by MistEO** [comment]
json 本来就是不支持注释的，这是 json 的问题，不是 maa 的问题（确信

**Comment by ABA2396** [comment]
> json 本来就是不支持注释的，只有 jsonc 或者 json5 才支持，这是 json 的问题，不是 maa 的问题（确信
> 
> 可以参考 [json 官方文档](https://www.json.org/json-zh.html)

他的意思是改下文档，说例子里的注释如果用的话要删掉

**Comment by Kingzom** [comment]
> json 本来就是不支持注释的，只有 jsonc 或者 json5 才支持，这是 json 的问题，不是 maa 的问题（确信
> 
> 可以参考 [json 官方文档](https://www.json.org/json-zh.html)

谢谢
以前确实没接触过json
找bug的时候刚打开maa它是能正确读出来三组的组名和时间的，link start以后就会报错
![9e726492ffd3105cc6efc7229532e08](https://user-images.githubusercontent.com/79841799/200132346-672e471a-6e7d-44ee-820a-a770f942af2b.png)
然后我刚开始的亿小会就完全没有意识到问题出在哪里（悲
