### ISSUE TITLE
定时任务出错

### ISSUE THREAD

**Issue by hanzif1** [MaaAssistantArknights/MaaAssistantArknights#2628]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

早上9点的定时任务，显示错误无法运行

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9945091/asst.bak.log)

### 截图

![L19W6ML9~X_$ZCPDJL6RP)M](https://user-images.githubusercontent.com/106012635/200152671-7e567229-94d9-4a0b-be9d-e0e726351d9a.png)

**Comment by MistEO** [comment]
咋关了
