### ISSUE TITLE
自动作战的建议

### ISSUE THREAD

**Issue by nightofknife** [MaaAssistantArknights/MaaAssistantArknights#2630]
### 说说你遇到的问题？

在写作业的时候发现一个问题，如果使用了W带2技能一类有自动释放地雷（会占据格子）的干员，有概率会在下一个应该放置干员的地方放个地雷导致放置干员失败，目前的解决办法是在放干员之前写一个撤退动作 撤退占据格子的召唤物，但是由于撤退动作的时机不一定能对上放干员的时机，如果两个动作中间间隔较大，还是有格子再次被占据导致部署干员失败的可能

### 有什么好的想法？

个人建议可以把条件和动作分开，以上面提到的问题为例，可以把能否部署某干员作为条件，然后把撤退作为动作。这样可以解决这个问题
引申一下：或许可以把目前能检测的都作为条件，（比如费用变换 费用数量 冷却中干员 干员能否部署一类的 【某干员技能转好了 感觉好像目前不太能作为条件】 ） 后面接行为（比如部署 撤退 ）

### 其他内容

需求来源  https://www.bilibili.com/video/BV1HW4y1j7eE     1分22秒处W地雷占据了星熊位置

**Comment by ABA2396** [comment]
等费用够了一起下.jpg

**Comment by cenfusheng** [comment]
加一个到达xx费用的判断吧（），现在只有费用变化

**Comment by MistEO** [comment]
> 加一个到达xx费用的判断吧（），现在只有费用变化

每个人潜能不一样，有些干员有没有模组费用也不一样。加费用会全乱掉的，这就是为什么现在专门搞了个费用变化，因为回费速度是一样的

**Comment by nightofknife** [comment]
> > 加一个到达xx费用的判断吧（），现在只有费用变化
> 
> 每个人潜能不一样，有些干员有没有模组费用也不一样。加费用会全乱掉的，这就是为什么现在专门搞了个费用变化，因为回费速度是一样的

实际上潜能影响不算大，一般MAA的操作延迟也能填补潜能的差距（不会真有全满潜的大佬写作业吧），加入到XX费的判断主要是由于有可能 前面有较多的操作，然后需要攒费同时下干员的时候就会比较难去计算费用，
举例：比如现在预先有10费，然后我进行了开xx干员技能（A操作），开启xx装置（B操作），然后写费用变化20费下xx和yy干员（假设xx和yy干员一共30费）（C操作），这样的由于AB操作的消耗的时间和设备有较大关系，可能在开始C操作的时候已经有14或者15费了，这样在部署xx和yy干员的时候就是34费了，会拖慢部署节奏（此处就不考虑老年机）.如果是要求部署卡的比较死的话可能会有影响，而且要考虑已有的费用加部署干员花费好伤脑子的 ：(

**Comment by MistEO** [comment]
就事论事，延迟靠 minitouch 解决掉就好了

**Comment by cenfusheng** [comment]
> > 加一个到达xx费用的判断吧（），现在只有费用变化
> 
> 每个人潜能不一样，有些干员有没有模组费用也不一样。加费用会全乱掉的，这就是为什么现在专门搞了个费用变化，因为回费速度是一样的

“加费用会全乱掉的”是指要卡轴吧，大部分作业用自动费够放人就能完成，基本无视潜能，没那么多精细操作，需要卡轴的也有很多通过击杀数和延迟解决，剩下的一定要用费用变化的就继续用费用变化好了，是希望另加，不是删掉嘛（）。而“当前现存费用达到xx”是为了在费用足够时一起放人这样的需求，是另外的需求，xx写的高一点就无视潜能模组多等一会儿，（写的少了第二个干员最多慢一点，这就是作业人需要考虑的情况了）

**Comment by cenfusheng** [comment]
> 

猫猫说的对，要考虑已有的费用加费用延迟算费用太烧脑子了（）
