### ISSUE TITLE
繁中服肉鴿 雇用隊員異常

### ISSUE THREAD

**Issue by Sherlote** [MaaAssistantArknights/MaaAssistantArknights#2631]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

Mac版本的MAA繁體服在測試版2時，肉鴿招募隊員沒有選擇隊員進去滑進滑左右滑就放棄招募,3次招募都不會選擇角色目前到beta3還是一樣,肉鴿執行中如影片偶爾會發生記憶體用超多的問題必須強制關閉的問題
<img width="433" alt="截圖 2022-11-06 14 52 49" src="https://user-images.githubusercontent.com/93369556/200158695-3f6273c7-a768-48c5-aaa3-0d719bac041d.png">

https://user-images.githubusercontent.com/93369556/200158699-3bc4e8b3-f6f5-4be8-998a-120a70879093.mp4

### 日志文件

[v4.6.7-beta.2繁中服肉鴿異常.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9945307/v4.6.7-beta.2.log)

**Comment by Sherlote** [comment]
> 你有一些檔案沒有成功上來，請重新上來。
> 
> 您有一些檔案沒有成功上傳，請重新上傳它們。

已重新上傳

**Comment by Sherlote** [comment]
在補充一下影片 用的是beta3的MAA
日誌
[繁中服beta3肉鴿異常記憶體使用完畢.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9945340/beta3.log)

影片:無法識別到隊員後繼續執行到開始戰鬥前停住後約1分鐘跳出用完記憶體

https://user-images.githubusercontent.com/93369556/200159847-42d7bf43-c3c5-4c99-94d9-631eedb64d63.mp4

**Comment by MistEO** [comment]
@hguandl CharOCR 实例似乎没有正常工作，都没有识别结果

**Comment by Sherlote** [comment]
剛更新的beta4版本也有同樣的問題!

**Comment by horror-proton** [comment]
> @hguandl CharOCR 实例似乎没有正常工作，都没有识别结果

奇怪, 公招那里是有识别结果的, 但是肉鸽那边就没了

**Comment by MistEO** [comment]
> > @hguandl CharOCR 实例似乎没有正常工作，都没有识别结果
> 
> 奇怪, 公招那里是有识别结果的, 但是肉鸽那边就没了

公招没用 CharOCR 的实例吧

**Comment by horror-proton** [comment]
> 公招没用 CharOCR 的实例吧

用了, 你搜日志

**Comment by hakula139** [comment]
4.6.7 正式版（macOS）测试后问题仍存在，简中服，附复现日志：

[asst-4.6.7.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9957082/asst.log)

4.6.6 正式版没有遇到此问题，附日志：

[asst-4.6.6.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9957096/asst.log)

**Comment by MistEO** [comment]
v4.6.8 fixed
