### ISSUE TITLE
4.6.7-beta.3无法打开

### ISSUE THREAD

**Issue by Aatrox0** [MaaAssistantArknights/MaaAssistantArknights#2632]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我在活动开启后一直关注含有最新活动的挂机版本，最新的4.6.6正式版使用没有问题，但4.6.7-beta3测试版我先是直接解压到原有文件夹（覆盖），但是无论是普通启动还是管理员启动都无法打开，开启窗口后一直是空白，然后自动关闭，我又解压在新建文件夹里，也是同样情况

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9945312/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/73479327/200158778-ffd6c991-576a-43fe-8924-e90fa0db1ab5.png)

**Comment by zzyyyl** [comment]
你解压覆盖的是OTA？

**Comment by Aatrox0** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9945312/asst.log)

**Comment by Aatrox0** [comment]
![image](https://user-images.githubusercontent.com/73479327/200158867-b64b495a-d97a-43e5-ad56-3c6e876e3ea2.png)

**Comment by zzyyyl** [comment]
看看你下载的压缩包

**Comment by Aatrox0** [comment]
![image](https://user-images.githubusercontent.com/73479327/200158938-77ccf7cc-8348-4ee4-af16-ff163dc7bdef.png)

**Comment by guojunyu196** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9945329/asst.log)
同样的问题，软件空白打不开

**Comment by zzyyyl** [comment]
马上撤版，先用beta2

**Comment by zzyyyl** [comment]
已经下载/更新了 beta.3 的，可以手动修改 gui.json，加入（或修改）以下两行：
```json
  "VersionUpdate.package": "MAAComponent-OTA-v4.6.7-beta.2_v4.6.7-beta.4-win-x64.zip",
  "VersionUpdate.name": "v4.6.7-beta.4",
```
然后下载 OTA： https://github.com/MaaAssistantArknights/MaaRelease/releases/download/v4.6.7-beta.4/MAAComponent-OTA-v4.6.7-beta.2_v4.6.7-beta.4-win-x64.zip 放入 MAA 目录后打开。
