### ISSUE TITLE
挂机完之后弹窗报错，之后软件自动关了

### ISSUE THREAD

**Issue by NULLlnull** [MaaAssistantArknights/MaaAssistantArknights#2634]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)

忘记截图了。挂机结束弹窗报错，然后退出了

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9945316/asst.zip)

**Comment by zzyyyl** [comment]
是不是有完成任务后退出模拟器，然后没开管理员权限？

不是的话传个 gui.log，是的话自己用管理员权限打开再试试

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
