### ISSUE TITLE
关于MAA运行过程中C盘的占用问题

### ISSUE THREAD

**Issue by pikachen-pick** [MaaAssistantArknights/MaaAssistantArknights#2637]
### 说说你遇到的问题？

萌新首次使用MAA，在运行过程中我留意到，MAA一直在往C盘写数据，这让我本就不多的C盘空间再次遭到压榨，直到C盘写满，随后MAA将产生闪退现象导致挂机中断，一番搜寻我并没有找到这个问题的解决办法，除了给C盘扩容以外，我希望官方能有别的解决方法

**Comment by zzyyyl** [comment]
写的很多？
MAA 不是放在 C 盘吧

**Comment by pikachen-pick** [comment]
> 写的很多？ MAA 不是放在 C 盘吧

我放在D盘，然后它往C盘写数据

**Comment by MistEO** [comment]
maa 应该没往 c 盘写东西吧。你看到的是啥文件？咋判断是 maa 写的？

**Comment by pikachen-pick** [comment]
> ### 说说你遇到的问题？
> 萌新首次使用MAA，在运行过程中我留意到，MAA一直在往C盘写数据，这让我本就不多的C盘空间再次遭到压榨，直到C盘写满，随后MAA将产生闪退现象导致挂机中断，一番搜寻我并没有找到这个问题的解决办法，除了给C盘扩容以外，我希望官方能有别的解决方法

我无法定位这个是MAA的问题还是模拟器的问题，但从

> ### 说说你遇到的问题？
> 萌新首次使用MAA，在运行过程中我留意到，MAA一直在往C盘写数据，这让我本就不多的C盘空间再次遭到压榨，直到C盘写满，随后MAA将产生闪退现象导致挂机中断，一番搜寻我并没有找到这个问题的解决办法，除了给C盘扩容以外，我希望官方能有别的解决方法

目前我仍在定位这个问题，不知道是模拟器还是MAA产生的大量数据

**Comment by pikachen-pick** [comment]
> maa 应该没往 c 盘写东西吧。你看到的是啥文件？咋判断是 maa 写的？

说实话我排查了一下午毫无头绪，如果可以能否请求你们的远程支援，联系方式发送到1589878520@qq.com

**Comment by horror-proton** [comment]
你的内存是不是占满了, 系统在往 C 盘写 swap file

**Comment by pikachen-pick** [comment]
> 你的内存是不是占满了, 系统在往 C 盘写 swap file

内存32G没见满过

**Comment by horror-proton** [comment]
也许用 Everything 或者 [WizTree](https://diskanalyzer.com/) 之类的工具索引一下文件, 看看什么最近东西写入的最多 🤔

**Comment by zzyyyl** [comment]
maa 会往 Temp 里写东西的

**Comment by MistEO** [comment]
> maa 会往 Temp 里写东西的

不会吧？写啥啊

**Comment by MistEO** [comment]
问一下，你用的啥模拟器？不会是雷电吧（

**Comment by pikachen-pick** [comment]
> 问一下，你用的啥模拟器？不会是雷电吧（

夜神

**Comment by pikachen-pick** [comment]
接上集，今天用工具查看了一下

![QQ截图20221110084118](https://user-images.githubusercontent.com/76153306/200976073-9fc00840-b8e1-4193-8d8c-f481ff92e145.png)
上图为扫荡前，C盘的状态
![QQ截图20221110090304](https://user-images.githubusercontent.com/76153306/200976222-e188b01a-7c71-4cb9-a1f9-dcac3090a6c2.png)
上图为运行了小一段时间之后，可以看到有文件开始涨空间

![QQ截图20221110090946](https://user-images.githubusercontent.com/76153306/200976394-1d972839-e70a-4499-9565-37d9fcc3f649.png)
上图为实际增长的文件，按名字来看好像是虚拟内存一样的东西

但是我虚拟内存也没动过（？？）
现在还不能判断是谁写进去的，但是可以试试把这个虚拟内存丢到空间更大的盘去 
@MistEO @zzyyyl

**Comment by pikachen-pick** [comment]
我把夜神模拟器换成蓝叠，再次运行，2小时内没见到硬盘空间占用，以此定下初步结论：模拟器的原因，至此锁question。
