### ISSUE TITLE
一点基建干员名识别问题

### ISSUE THREAD

**Issue by cenfusheng** [MaaAssistantArknights/MaaAssistantArknights#2638]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

![WT`U6ZWGWLN MO_~46O0ZR0](https://user-images.githubusercontent.com/52312717/200164996-f0da4fe2-9492-4f86-9bf3-7ca0ac90d8f0.png)
![3HHGZW_ 6M63Q%$HWN9E%C3](https://user-images.githubusercontent.com/52312717/200165004-b59e0086-78ec-4c2e-a8de-d4fbb21c80e7.png)

已经翻到了，直接贴图了

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9945571/asst.zip)

**Comment by zzyyyl** [comment]
野鬃 的问题测试版修过了
