### ISSUE TITLE
拖动任务状态下弹出更新重启提示卡死bug

### ISSUE THREAD

**Issue by weedi0** [MaaAssistantArknights/MaaAssistantArknights#2639]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

启动后提示更新，未在意，正在调整任务顺序，弹出更新完成重启询问，卡死鼠标无法操作，键盘tab选择按钮确认重启后，就报错状态。重启操作系统解决。

### 日志文件

[提示文本.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9945722/default.txt)

### 截图

![QQ截图20221104082435](https://user-images.githubusercontent.com/87680595/200168354-c444ffa2-07d4-4bc1-8dfe-be9f945390a1.png)

**Comment by MistEO** [comment]
@ABA2396  话说这个是不是修过了

**Comment by ABA2396** [comment]
没有，不会修）

**Comment by moomiji** [comment]
v5 版本能复现吗？

**Comment by Constrat** [comment]
Let's close for now. Can be reopened otherwise.
