### ISSUE TITLE
外部组件发生异常。

### ISSUE THREAD

**Issue by CMWLZZ** [MaaAssistantArknights/MaaAssistantArknights#2644]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

   在 MeoAsstGui.AsstProxy.AsstLoadResource(Byte* dirname)
   在 MeoAsstGui.AsstProxy.AsstLoadResource(String dirname)
   在 MeoAsstGui.AsstProxy.LoadResource()
   在 MeoAsstGui.AsstProxy.Init()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MeoAsstGui.RootViewModel.<InitProxy>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9946295/asst.log)

**Comment by MistEO** [comment]
最近自动更新功能有点问题，看起来是资源不完整，重新下载一下完整的包看看
