### ISSUE TITLE
自动肉鸽和定时执行的冲突？

### ISSUE THREAD

**Issue by LeviZhang1996** [MaaAssistantArknights/MaaAssistantArknights#2645]
### 说说你遇到的问题？

设置了三班倒的定时执行，主要是为了基建换班以及清体力，但是自动肉鸽在进行中的时候到了预设的启动时间点好像是不会停下来进行基建换班，而是继续肉鸽，这样就导致基建换班失败以及体力溢出

### 有什么好的想法？

建议在定时执行时加个判定，如果在肉鸽中就退出肉鸽？

**Comment by Minepig** [comment]
确实是个麻烦的东西，之前我也被坑过

**Comment by ntgmc** [comment]
是的，定时执行仅会在当前无任务的情况下开始运行，建议在肉鸽设置中选择探索次数来尝试解决该问题（或不进行自动肉鸽）。


是的，定时执行仅会在当前无任务的情况下开始运行，建议在肉鸽设置中选择探索次数来尝试解决该问题（或不进行自动肉鸽）。

Yes, the scheduled execution will only start when there is no task at present. It is recommended to select the number of explorations in the meat pigeon settings to try to solve the problem (or do not carry out automatic meat pigeons).
