### ISSUE TITLE
日服: Cant FP Change item

### ISSUE THREAD

**Issue by wallsman** [MaaAssistantArknights/MaaAssistantArknights#2646]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I spent at least 5 minutes thinking and preparing before raising the issue.
- [X] I have read the FAQ and the User Manual in the documentation and believe that this is most likely a bug and not designed to be so.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] The screenshots I've uploaded are the original ones taken by the emulator's own screenshot tool (or via adb).

### Description

購買部で購入できない。
多分、ログを見る限りOCRの読み取りミスだと思います。

Cannot purchase in the Purchasing Dept.
Maybe it is an OCR reading error as far as I can tell from the log.

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9946633/asst.log)

### Screenshots

![image](https://user-images.githubusercontent.com/63186641/200190529-e0ef3a2f-f9e6-47ef-bfb4-d21f6163e2b2.png)

**Comment by MistEO** [comment]
Yes, there was an error in the OCR

```log
[2022-11-07 04:14:46.272][TRC][Px28db0][Tx28e84] OcrPack::recognize | raw: [{ 麟買部: [ 38, 29, 117, 52 ], score: 0.738317 }, { イ: [ 121, 5, 43, 29 ], score: 0.739747 }]
```
