### ISSUE TITLE
建议肉鸽增加一个设置：检测到特定收藏品，停止。（这把5元，换我来玩）

### ISSUE THREAD

**Issue by wnight9527** [MaaAssistantArknights/MaaAssistantArknights#2648]
### 说说你遇到的问题？

建议肉鸽增加一个设置：检测到特定收藏品，停止。（这把5元，换我来玩）

### 有什么好的想法？

建议肉鸽增加一个设置：检测到特定收藏品，停止。（这把5元，换我来玩）

**Comment by wnight9527** [comment]
如果需要标注收藏品，可以帮忙

**Comment by ntgmc** [comment]
设想是好的，做这个也简单，但是用处不太大，毕竟你用maa就是为刷蜡烛/投资
（o(╥﹏╥)o）

**Comment by wnight9527** [comment]
主要是升难度或者玩爽局的时候，想要刷一个好的开局，比如6星希望费用-2，神之手之类的开局。

**Comment by wnight9527** [comment]
方便解锁特殊藏品或者职业组

**Comment by WWPXX233** [comment]
目前还是以自动刷取奖励等级为主藏品的话只能随缘了目前
