### ISSUE TITLE
建议刷体力增加1-7选项

### ISSUE THREAD

**Issue by ZhaoGY-N** [MaaAssistantArknights/MaaAssistantArknights#265]
现在刷1-7只能先手动刷一次，然后选上次作战，能不能像CE-5之类的一样，在关卡选择的时候就可以选。

**Comment by pointm** [comment]
> 现在刷1-7只能先手动刷一次，然后选上次作战，能不能像CE-5之类的一样，在关卡选择的时候就可以选。

也可以停留在1-7界面，然后选择当前关卡进行刷图，只不过我还是认为有必要加一个快捷开关

**Comment by MistEO** [comment]
v3.3 fixed
