### ISSUE TITLE
肉鸽中途停止

### ISSUE THREAD

**Issue by wu-aholic** [MaaAssistantArknights/MaaAssistantArknights#2650]
打肉鸽打着打着停住了，我回来点几下才继续
![IMG_20221107_164649](https://user-images.githubusercontent.com/117635573/200271513-fe542b25-a749-435a-beb0-217cb5fbfbaf.jpg)

**Comment by zzyyyl** [comment]
好久没遇到这种卡不期而遇的 issue 了，建议看看是不是最新版
