### ISSUE TITLE
建议更改肉鸽中干员水月优先选择1技能

### ISSUE THREAD

**Issue by RyanSaul** [MaaAssistantArknights/MaaAssistantArknights#2651]
### 说说你遇到的问题？

在肉鸽中水月默认选择的是需要手动开启的2技能，2技能无法像1技能一样提供稳定的常态输出，在识别技能开启的过程中很容易漏怪。

### 有什么好的想法？

建议默认选择1技能，由于1技能为自动开启的技能，倍率也相对较高，能在前期压力较为平均的情况下补充输出，并且由于无需开启技能，容错率会提高不少。

**Comment by MistEO** [comment]
@WWPXX233 你觉得呢？

**Comment by WWPXX233** [comment]
确实一技能比较好 改！
