### ISSUE TITLE
肉鸽莫名停止

### ISSUE THREAD

**Issue by wu-aholic** [MaaAssistantArknights/MaaAssistantArknights#2653]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

为什么打肉鸽打着打着停住了，我回来点几下才继续，画面没有任何问题，maa也没报错，截图忘记截了，但当时看上去没有任何问题，且点几下屏幕它就恢复正常了
![IMG_20221107_164649](https://user-images.githubusercontent.com/117635573/200290373-b89c56fa-9c2f-4dcd-b6b5-130f212e917d.jpg)

### 日志文件

https://share.weiyun.com/hqzu9yy9
文件过大，且无法上传压缩文件，只能用微云链接
看截图应该是15：15停止的

### 还有别的吗？

夜神模拟器，win10，版本4.6.6

**Comment by HMZyueshen** [comment]
应该是修复了的，如果还出错再提issue
