### ISSUE TITLE
肉鸽 机械之灾 逻辑错误导致漏怪过多

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#2655]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [x] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

这关一开始就有很多无人机，但是maa先放泥岩，再发海沫，然后蜜莓，塞雷娅，临时重装，百炼，放完这些飞机都漏了10个了……（maa带的狙击：能天使，黑，肥鸭）

### 日志文件

[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9952500/asst.-.zip)

### 还有别的吗？

希望在这关能改变逻辑，在放完第一个地面和奶后放狙击
对了，这里maa的版本是4.6.7b4

**Comment by zzyyyl** [comment]
@WWPXX233

**Comment by WWPXX233** [comment]
这个已经尽力了 机械之灾开局飞机位置不固定 目前也没有放干员组合的方法没办法吸引火力

**Comment by ntgmc** [comment]
不是那个轰炸机，是小飞机o(╥﹏╥)o

**Comment by WWPXX233** [comment]
就是因为轰炸机开局位置不固定所以才很难搞）

**Comment by ntgmc** [comment]
现在不也一样寄吗QAQ

**Comment by WWPXX233** [comment]
是一样寄没办法的事 毕竟这关算难度比较高的 maa来打的话，，，寄的概率更大）

**Comment by ntgmc** [comment]
好的吧
