### ISSUE TITLE
贸易站无法识别但书

### ISSUE THREAD

**Issue by nicksun2022** [MaaAssistantArknights/MaaAssistantArknights#2657]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

自定义基建换班时，贸易站无法识别但书。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9952881/gui.log)

2022-11-05 22:08:00 至 2022-11-05 22:21:48。
2022-11-06 22:08:11 至 2022-11-06 22:23:07。
2022-11-07 22:10:28 至 2022-11-07 22:30:30。

### 截图

很抱歉未能截图，都是后来登录时发现贸易站没上人

### 还有别的吗？

模拟器：蓝叠5，像素320DPI。分辨率设置试过1920*1080和1280*720
操作系统win10 64位。

**Comment by weedi0** [comment]
同样情况，自定义排班概率出现制造者或交易站没排人的bug，不改动任何设置的情况下，重新执行能正确把人排进去。另外反映个情况，宿舍没满人的情况下会自动填入心情恢复增加干员，会出现2个情况，1、自定义排班每个房间设置了一个心情回复干员会被最后一个宿舍给重新填入。2、会把中枢阿米娅塞到宿舍里
[asst.bak1.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9957191/asst.bak1.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9957194/asst.log)
