### ISSUE TITLE
关于肉鸽中借助干员令通关的建议

### ISSUE THREAD

**Issue by 229265769** [MaaAssistantArknights/MaaAssistantArknights#2659]
### 说说你遇到的问题？

抄作业和肉鸽里面，想要借助没有的干员进行通关，但是暂时未发现能借助战的功能，比如在零级的肉鸽中，如果能使用令这个角色可以很轻松的度过前期，大龙甚至不用合成，只用七级技能的小龙进行堆尸都能很轻易通关。打boss 用一两决胜技能的即可通关。而且已经有比较成熟的攻略进行肉鸽令单人通关了。如果能够实现该功能，应该能让很多人更加高效的刷蜡烛什么的。

### 有什么好的想法？

初级实现方式，使用令这个角色，开局肉鸽点名使用单个干员开局时，如果检测仓库中没有该角色，但是该角色确实没有输入错误，属于明日方舟中存在的干员时，打开助战单位，找到相应的职业，截图寻得该角色。无论是好友没有的角色七级技能的，也可以借过来使用。
如果是借令的话可以用小龙弦惊当做一个普通干员使用，本身当二大二身板能媲美大部分的角色了，不考虑合成情况下一个令能顶替两三个干员。
高级一点的，如果检测到队伍里存在令，没三技能用1，优先放置令，后续抓干员改变一下权重，优先抓取打飞机干员或者拥有决胜技能干员。

### 其他内容

无
地方地方
![image](https://user-images.githubusercontent.com/117697064/200452680-19edc663-d26d-4dae-a096-6c0a901a7584.png)

**Comment by WWPXX233** [comment]
你可以手动进行助战招募来获取令 然后在地图界面运行自动肉鸽 不过可能会出现奇怪的错误
