### ISSUE TITLE
希望可以增加干员升级到某个等级功能

### ISSUE THREAD

**Issue by breathiness** [MaaAssistantArknights/MaaAssistantArknights#266]
目前手动升级太过麻烦，每次只能喂40本书。升个干员要按好久。现在我已经存了3K+的大经验书懒得喂了。

能否添加干员升级的功能：我选中某个干员，然后自动帮我升级到指定等级。

如果可以自动进阶，然后还能根据缺少的材料自动加工站帮忙加工就更好了。我各蓝材料都堆了200个以上懒得用。

**Comment by Shawnsdaddy** [comment]
该功能已经被yj实装

**Comment by ABA2396** [comment]
> 该功能已经被yj实装

玛丽可以心安理得地偷懒了
