### ISSUE TITLE
繁中服基建 製造站 與發電站 無人進駐時無法自動進駐

### ISSUE THREAD

**Issue by Sherlote** [MaaAssistantArknights/MaaAssistantArknights#2661]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

繁中服在基建設施全員為進駐的狀態下啟動MAA,製造站會在下圖4個製造站依序往下不會選擇幹員進行進駐
<img width="872" alt="截圖 2022-11-08 10 44 35" src="https://user-images.githubusercontent.com/93369556/200463000-33564690-2c8f-4249-a33a-a32043e16e80.png">
貿易站可以正常進駐
<img width="865" alt="截圖 2022-11-08 10 49 31" src="https://user-images.githubusercontent.com/93369556/200463138-806b4c81-99c6-4abb-beda-341df39fd0bc.png">
發電站這個很奇怪,這次執行就沒有跑發電站 之前有1次是進駐了1間 還有一次是2間 沒有完全進駐的

<img width="490" alt="截圖 2022-11-08 10 51 12" src="https://user-images.githubusercontent.com/93369556/200463366-454a59a3-cb82-420e-922e-c171580f6e50.png">
MAA的設定如下圖
<img width="893" alt="截圖 2022-11-08 10 51 30" src="https://user-images.githubusercontent.com/93369556/200463475-4a766577-b789-4fa0-b8c0-bd8cd139c77b.png">

### 日志文件

[繁中服基建 製造站 與發電站 無人進駐時無法自動進駐.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9957202/default.log)

**Comment by MistEO** [comment]
我没有繁中服的号，是 @Vincent-2019 帮忙适配的，就目前来看应该不是替换几个 text 这么简单

**Comment by MistEO** [comment]
后面有朋友又帮忙适配了下，现在还有问题吗？

**Comment by 29988122** [comment]
這個bug在新版中依然存在, 挺奇怪的

不知道這是什麼問題
這邊的是我的兩個log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11684379/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11684380/gui.log)

Thanks!
