### ISSUE TITLE
肉鸽走向下一个节点时偶尔会卡住不操作

### ISSUE THREAD

**Issue by hanwu1234** [MaaAssistantArknights/MaaAssistantArknights#2662]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

肉鸽走向下一个节点时偶尔会卡住不操作，需要我手动点几下才能继续

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9957503/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/52276072/200472849-2ac00fa0-fc11-434b-b7c9-edd58f248960.png)

### 还有别的吗？

蓝叠模拟器（hyper-V版）
win11
魁影肉鸽

**Comment by MistEO** [comment]
不期而遇卡在哪个界面了，有图么？

**Comment by hanwu1234** [comment]
> 不期而遇卡在哪个界面了，有图么？

图片没有，当时点了几下接着就往下挂机了没有截图，debug/rouge里面也找了一下，没有那个图片。是一个不期而遇结束了，应该往下一个节点走的时候不动了

**Comment by MistEO** [comment]
没有图只能简单修下了，下次遇到这种情况会自动放弃重开（起码不会卡住），放弃是会自动截图的，下次出现放弃的再提个 issue 吧

**Comment by hanwu1234** [comment]
> 没有图只能简单修下了，下次遇到这种情况会自动放弃重开（起码不会卡住），放弃是会自动截图的，下次出现放弃的再提个 issue 吧

OK
