### ISSUE TITLE
MAA无法导航至新活动关卡

### ISSUE THREAD

**Issue by barry271828-e** [MaaAssistantArknights/MaaAssistantArknights#2667]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

把所有任务点上之后就挂后台了，结果后来才发现战斗被跳过了，然后又就单点刷理智开了一遍，结果发现卡在终端首页不动

看log这个反复出现了好几遍，所以说是ocr错误？
> [{ ?13天: [ 6, 89, 71, 19 ], score: 0.795719 }, { 6/11: [ 35, 64, 27, 12 ], score: 0.768081 }, { “统与秩序“内关卡已开放: [ 109, 42, 208, 18 ], score: 0.825670 }, { 人: [ 391, 34, 46, 66 ], score: 0.892950 }]

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9960805/asst.log)
时间点11/8 ~7点

**Comment by MistEO** [comment]
修过了，更新下

**Comment by barry271828-e** [comment]
> 修过了，更新下

好快的更新迭代
