### ISSUE TITLE
基建逻辑异常

### ISSUE THREAD

**Issue by breathiness** [MaaAssistantArknights/MaaAssistantArknights#267]
这是基建任务完成后的状态。还有几个设备是空的。
而且在过程中也出现了很多槽点，比如把精神涣散的三人换下，然后再把原来的三人换回去；把还有体力的能天使三人组换下又把单独的德克萨斯放回去等等……非常奇怪
这是截图：
![Clip_20220306_142235](https://user-images.githubusercontent.com/11361630/156913122-c9793647-7dc2-4974-af7c-9eadf926a1da.png)
这是日志文件：
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8192123/asst.log)

**Comment by MistEO** [comment]
挺奇怪的问题，日志没看出来什么头绪，换 `1280 * 720` 或者 `2560 * 1440` 分辨率试一下？最好是 `320 DPI`

**Comment by breathiness** [comment]
通过取消过多的任务的方式避开这个问题了。现在不自动换左半边的基建
