### ISSUE TITLE
软件本身弹出窗口报错

### ISSUE THREAD

**Issue by Eminhy** [MaaAssistantArknights/MaaAssistantArknights#2671]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

软件本身弹出窗口报错，闪退
模拟器无异常

### 日志文件

[Uploading asst.log…]()
[Uploading asst.bak.log…]()

### 截图

![QQ图片20221108225624](https://user-images.githubusercontent.com/47178124/200598486-2d5f3b7d-8984-4bb9-a0b5-20aadaf60135.png)

**Comment by Eminhy** [comment]
是在软件完成更新之后马上出现的

**Comment by Eminhy** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9962507/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9962508/asst.bak.log)

**Comment by zzyyyl** [comment]
什么版本更新到什么版本？

**Comment by Eminhy** [comment]
> 什么版本更新到什么版本？

上一个正式版的版本到上上一个正式版的版本
v4.6.9→v4.6.10
