### ISSUE TITLE
水月肉鸽自动战斗卡在难度选择环节

### ISSUE THREAD

**Issue by xinlingheidong** [MaaAssistantArknights/MaaAssistantArknights#2677]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

用maa自动战斗肉鸽的时候它会一直卡在选择难度的位置，必须手动选定难度后它才能正常运行。
![image](https://user-images.githubusercontent.com/94310025/200687679-00fb1222-89e0-4930-a4ca-77bccc2cd7ee.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9965672/asst.log)
大概在这个位置开始是自动肉鸽
[2022-11-08 21:50:45.281][INF][Px4264][Tx1b9c]

### 截图

<img width="800" alt="BS_PIC_2022-11-08-22-22-00" src="https://user-images.githubusercontent.com/94310025/200688744-f8d68b68-3249-48c6-aa33-5f4d134ae21b.png">
这个截图不是及时的截图（但确实是用模拟器截图的，不知道符不符合要求），是我根据印象里坐回电脑前看到程序死循环时模拟器上显示的图像复原的位置，随后我立刻介入了，没有看到其他循环过程中产生的图像。我的最高难度是打到8了。

### 还有别的吗？

蓝叠模拟器，B服，Windows系统

**Comment by zzyyyl** [comment]
难度只用选一次，目前没做）

**Comment by ntgmc** [comment]
自己选啊
