### ISSUE TITLE
肉鸽打到第三层的奖励页面，突然结算了

### ISSUE THREAD

**Issue by 1014670034** [MaaAssistantArknights/MaaAssistantArknights#2678]
### 说说你遇到的问题？

![image](https://user-images.githubusercontent.com/50533791/200722362-92743370-8408-4f95-8cec-87f087d556d5.png)
这个肉鸽还可以继续啊，为啥就突然去结算了呢。我看我还有7点生命。
maa在沙窟风暴的奖励页面，两个藏品一直不选，突然就退出然后结算了。

**Comment by zzyyyl** [comment]
开 bug issue，带上日志 asst.log 和截图（ debug/roguelike/ ）
