### ISSUE TITLE
剩余理智和剿灭合成玉获取进度监测

### ISSUE THREAD

**Issue by ChildeRolando** [MaaAssistantArknights/MaaAssistantArknights#2679]
### 说说你遇到的问题？

不能实时获取当前剩余理智，不能读取合成玉已获取数量，这对想要基于MAA自定义控制台的开发者带来了困难！

### 有什么好的想法？

请求做这个功能点，一个接口即可，不用写进GUI中，拜托了，这对我真的很重要！

**Comment by zzyyyl** [comment]
剩余理智有了，合成玉好像没什么必要了（？

issue有点老先关了，有问题再开
