### ISSUE TITLE
最新稳定版连接mumu模拟器出现未知错误

### ISSUE THREAD

**Issue by ZhouChong123** [MaaAssistantArknights/MaaAssistantArknights#2680]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

4.6.12连接mumu模拟器失败，提示位置未知的错误。但使用4.6.10版本（最后一次更新）一切正常

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9966907/asst.log)

### 截图

![QQ图片20221109105404](https://user-images.githubusercontent.com/113335991/200726185-13b7384a-273c-4d4e-ab52-f9fef7600246.png)
![QQ图片20221109105415](https://user-images.githubusercontent.com/113335991/200726197-a332f27b-d869-45e9-afe9-23c3717586e6.png)

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue，感谢反馈。
Update to the latest version and try again. If there are problems, issue again. Thank you for your feedback.
adb模拟器连接问题请参照使用文档（使用文档：https://maa.plus/docs/）连接，谢谢。
For the connection problem of the adb simulator, please refer to the use document (usage document: https://maa.plus/docs/ ）. Thank you.
