### ISSUE TITLE
明日方舟EN服完全不可用

### ISSUE THREAD

**Issue by Realzhazha** [MaaAssistantArknights/MaaAssistantArknights#2682]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

明日方舟EN服完全不可用，点击Link Start之后除了能打开游戏以外，之后直接卡在登录界面

### 日志文件

时间：11月9月上午 

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9967111/asst.log)

### 还有别的吗？

模拟器: 夜神国际版 Android 7 32bit
系统：Windows10

**Comment by crisike** [comment]
一样的问题。
在蓝叠国际版32位上，win10。
看模拟器界面，可能是外服UI修改。
进入SN-8的当前关卡，MAA的进行流程会退回到主页，然后会报错。
猩红肉鸽同样的会进入界面之后再退出到主页。
访问好友只能进入个人信息页面，然后就不能执行下一步。

**Comment by crisike** [comment]
OK
发现只要把MAA客户端语言换成EN就可以....weird

**Comment by MistEO** [comment]
并没有支持外服的登陆，请看文档
