### ISSUE TITLE
水月肉鸽偶现数据回溯卡住

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#2685]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在刷取水月肉鸽的时候，有时会莫名其妙出现数据回溯，不知道是怎么点出来的。出现数据回溯后，MAA不能识别，会卡住一动不动，没有任何操作。

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9967524/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9967527/asst.log)

### 截图

![2022-11-09_13-06-55 437_raw](https://user-images.githubusercontent.com/92417243/200744226-17b84b73-9df8-4339-9a1e-b83f37f3071b.png)

**Comment by MistEO** [comment]
你上一局打完了但没完全打完，点“开始探索”，就会进到这里

**Comment by vic233333** [comment]
目前版本这个bug依旧存在，不过问题不是很大，手动脱离一下就好了。不过希望卡这个页面的时候至少有个提示。

**Comment by MistEO** [comment]
> 目前版本这个bug依旧存在，不过问题不是很大，手动脱离一下就好了。不过希望卡这个页面的时候至少有个提示。

有提示说明识别到了卡在这里了，那 maa 就直接点掉了

**Comment by vic233333** [comment]
唔我这边卡住了，可能是ADB卡了。
