### ISSUE TITLE
mumu模拟器无法自动启动

### ISSUE THREAD

**Issue by curvit** [MaaAssistantArknights/MaaAssistantArknights#2686]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

版本4.6.12 设置如图，maa打开后无法自动启动mumu模拟器，用管理员权限打开也不行。手动启动mumu模拟器后可以正常使用，所以adb地址应该没问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9967487/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/105404434/200743527-7541ec52-0c37-4978-b7e0-b2e0d68d819a.png)
![image](https://user-images.githubusercontent.com/105404434/200744187-09d5f227-3322-4fc2-89c7-270bc4e68283.png)

**Comment by ABA2396** [comment]
你下面那个模拟器路径选的什么？模拟器是 \MuMu\emulator\nemu\EmulatorShell\NemuPlayer.exe ，要填的不是adb路径

**Comment by curvit** [comment]
> 你下面那个模拟器路径选的什么？模拟器是 \MuMu\emulator\nemu\EmulatorShell\NemuPlayer.exe ，要填的不是adb路径

已解决，是我填成adb路径了
