### ISSUE TITLE
水月肉鸽老是漏几个怪后再放干员。

### ISSUE THREAD

**Issue by shinecrow** [MaaAssistantArknights/MaaAssistantArknights#2687]
### 说说你遇到的问题？

如题，费好了也不下，漏了好几个才下人，是我设置的有问题还是什么原因？

**Comment by shinecrow** [comment]
如果可以的话，写封邮件给我的邮箱——1970732160@qq.com。这个网站不太会用。如果觉得太麻烦了就算了。十分感谢作者对明日方舟的贡献以及对我的帮助！

**Comment by Reeleon** [comment]
遇到了相同的问题。具体来说目击过好几次【第一层 共生】会漏几只狗才会放置第一个干员，而当时已经三十几费了。
我注意到战斗开始后，会点击骰子暂停一下，然后才开始部署干员，是否是因为自动肉鸽每次战斗的“前摇”较长，遇到很快有怪奔向蓝门的关卡会漏怪呢？

**Comment by shinecrow** [comment]
嗯，有时候我看一直在2倍速和1倍速切换，我在线是不是这个原因导致计算费用出错了。多算了1倍的时间。

**Comment by ntgmc** [comment]
1：放日志
2：放maa设置

**Comment by ntgmc** [comment]
请尝试更新到内测版来测试该问题是否仍然存在，谢谢。
Please try to update to the internal beta to test whether the problem still exists, thank you.
请提供日志（和截图）来帮助我们解决该问题，谢谢。
Please provide logs (and screenshots) to help us solve this problem. Thank you.

**Comment by Reeleon** [comment]
我遇到问题那天的日志丢失了，今天我试图在相同设置下复现这个问题，但是相同的关卡、编队下已经能够及时放置干员，也就是当前问题没有再出现。

报告问题时的版本（11月8日）：v4.6.7
当前版本（11月15日）：v4.6,13
操作系统：win-x64

**Comment by Reeleon** [comment]
我遇到问题那天的日志丢失了，今天我试图在相同设置下复现这个问题，但是相同的关卡、编队下已经能够及时放置干员，也就是当前问题没有再出现。

报告问题时的版本（11月8日）：v4.6.7
当前版本（11月15日）：v4.6,13
操作系统：win-x64

**Comment by ntgmc** [comment]
没bug就好了。
感谢反馈。

Thank you for your feedback.

**Comment by LDYang694** [comment]
现在又出现这个问题了 共生关卡50多费还是不下山，怪全漏光了

**Comment by LDYang694** [comment]
![image](https://user-images.githubusercontent.com/62846124/234181297-9d8ec289-b78e-4956-9c7a-ca41566c0b6a.png)

**Comment by LDYang694** [comment]
每次都是暂停之后不放干员，反而打开二倍速
