### ISSUE TITLE
好友助战能否自动选择某个队员

### ISSUE THREAD

**Issue by davidelectricfree** [MaaAssistantArknights/MaaAssistantArknights#2688]
### 说说你遇到的问题？

谢谢大佬的软件，非常好用，萌新刚开始玩这个游戏，因为练度不够然后打活动关只能用好友的角色助战，目前是每次都要重新选完好友的人物，感觉有点不方便。

### 有什么好的想法？

能否让软件识别某个固定的人物，比如说玛恩纳，然后自动识别自动选择。

### 其他内容

谢谢大佬。

**Comment by ChildeRolando** [comment]
好需求，伪代理

**Comment by zzyyyl** [comment]
（现在连好友助战都还没有吧）
