### ISSUE TITLE
水月肉鸽放干员问题

### ISSUE THREAD

**Issue by flygenie** [MaaAssistantArknights/MaaAssistantArknights#2690]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

干员有时好几次放不下去，还乱放，导致漏怪。开了几局第一层必死。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9971294/asst.log)

### 截图

<img width="979" alt="屏幕截图 2022-11-09 210108" src="https://user-images.githubusercontent.com/110892931/200837914-b795ac6b-8fc3-42a6-a13f-3e059b74378a.png">

### 还有别的吗？

夜神模拟器安卓9  
系统win11

**Comment by ntgmc** [comment]
请尝试更新到内测版来测试该问题是否仍然存在，谢谢。
Please try to update to the internal beta to test whether the problem still exists, thank you.

**Comment by gdf159159** [comment]
> 请尝试更新到内测版来测试该问题是否仍然存在，谢谢。 Please try to update to the internal beta to test whether the problem still exists, thank you.

他说的这个问题是识别关卡遇到的问题  我也遇到了 maa会在map下生成一个以时间命名的地图照片 然后就乱放干员 

生成一个以时间命名的地图照片  这个步骤我觉得就有问题  识别关卡异常 生成一个异常的地图还继续了

**Comment by flygenie** [comment]
> 请尝试更新到内测版来测试该问题是否仍然存在，谢谢。 Please try to update to the internal beta to test whether the problem still exists, thank you.

抱歉没有及时回复，这个问题经我自己测试好像是夜神模拟器分辨率的问题，在1280*720下就不会出现这种问题，但分辨率高了，即使还是16:9，还是会出现这个问题。

**Comment by gdf159159** [comment]
> > 请尝试更新到内测版来测试该问题是否仍然存在，谢谢。 Please try to update to the internal beta to test whether the problem still exists, thank you.
> 
> 抱歉没有及时回复，这个问题经我自己测试好像是夜神模拟器分辨率的问题，在1280*720下就不会出现这种问题，但分辨率高了，即使还是16:9，还是会出现这个问题。

那可能确实是分辨率导致的问题 我一直用的1920 1080

**Comment by MistEO** [comment]
试试新版本的 MaaTouch

**Comment by cenfusheng** [comment]
放不下去可能是当时minitouch的延迟太低了，乱放是MAA判定那个位置已经放人了（实际没放下去），后续新版已修复，如仍出现（比如我卡卡的破电脑），可自行稍许增加resource\tasks.json中BattleUseOper与BattleSwipeOper的延迟数据。
