### ISSUE TITLE
Anihilation New UI(JP/EN)

### ISSUE THREAD

**Issue by wallsman** [MaaAssistantArknights/MaaAssistantArknights#2691]
### The problems you have encountered?

Would this be of any use to you?

JP
![Screenshot_2022 11 07_04 12 53 630](https://user-images.githubusercontent.com/63186641/200843968-6214c56f-e60a-4a6f-94ce-5827b88100e2.png)
![Screenshot_2022 11 07_05 20 50 081](https://user-images.githubusercontent.com/63186641/200843980-7d15f5e5-c574-43cf-ab3a-446b8c23d74e.png)
![Screenshot_2022 11 07_05 20 54 913](https://user-images.githubusercontent.com/63186641/200843990-0bf7ed45-6e68-4b7d-8c5a-b9a213922b1b.png)

EN
![image](https://user-images.githubusercontent.com/63186641/200843801-d02047c6-fbaa-40eb-afc8-c10d48817291.png)
![image](https://user-images.githubusercontent.com/63186641/200843828-39eb4d7d-f727-4609-ad3b-314ae271a9e5.png)
![image](https://user-images.githubusercontent.com/63186641/200843856-1eddddf6-110f-44a9-bc93-463ff1b8603d.png)

### Any good ideas?

MAA Ver4.612 Still cant play Anihilation.

**Comment by MistEO** [comment]
Thanks, still need these pictures in JP.

![Screenshot_2022 11 10_22 27 39 559](https://user-images.githubusercontent.com/18511905/201118305-eb78aa0f-9724-4a47-9337-3a0837766354.png)
![image](https://user-images.githubusercontent.com/18511905/201118645-d26abf87-d00f-4e4d-a5f5-d8eb7cb6ca53.png)
![2022-08-02_21-56-07 423_raw](https://user-images.githubusercontent.com/18511905/201118773-88aa9007-de1d-4a24-8802-4b76dccdfcef.png)

**Comment by wallsman** [comment]
Those this
![Screenshot_2022 11 11_00 13 13 183](https://user-images.githubusercontent.com/63186641/201133191-fd902f50-097d-41c6-a208-c2408667108d.png)
![Screenshot_2022 11 11_00 13 33 416](https://user-images.githubusercontent.com/63186641/201133206-71c6966d-3f1c-4d88-929f-73455e9b1493.png)
![Screenshot_2022 11 11_00 14 51 817](https://user-images.githubusercontent.com/63186641/201133219-f9f2144b-5587-492e-ba08-e75ac7e0c9cf.png)

**Comment by wallsman** [comment]
@MistEO 
EN ver.

![image](https://user-images.githubusercontent.com/63186641/202933188-6bd97cae-5810-4733-bad8-84442588cb39.png)
![image](https://user-images.githubusercontent.com/63186641/202933192-d565eaef-bd62-4c33-969d-9206ff80282b.png)
![image](https://user-images.githubusercontent.com/63186641/202933195-f109ad93-9e7b-4b77-92db-f9c9403f7e28.png)
