### ISSUE TITLE
宿舍内sort和autofill同为true时，存在选人bug

### ISSUE THREAD

**Issue by fearlessxjdx** [MaaAssistantArknights/MaaAssistantArknights#2693]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

```json
"dormitory": [
          {
            "operators": ["流明", "断罪者", "德克萨斯"],
            "sort": true,
            "autofill": true
          },
]
```

德狗被选中后，又会取消选择，并且宿舍没排满。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9972132/asst.log)

**Comment by MistEO** [comment]
宿舍为啥要 sort ，炒饭行为（）

**Comment by zzyyyl** [comment]
宿舍 sort，比如肥鸭？

**Comment by ABA2396** [comment]
> 宿舍 sort，比如肥鸭？

肥鸭现在放人也变了，也不用sort
