### ISSUE TITLE
mumu模拟器完成任务后出现未知错误

### ISSUE THREAD

**Issue by curvit** [MaaAssistantArknights/MaaAssistantArknights#2694]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [x] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

任务全部完成后，如果设置为关闭模拟器就会有下图提示，如果设置为无动作则正常结束没有提示，应该和关闭模拟器有关

详细信息
在 System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   在 System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   在 System.Diagnostics.Process.get_HasExited()
   在 MeoAsstGui.TaskQueueViewModel.KillEumlatorbyWindow()
   在 MeoAsstGui.TaskQueueViewModel.CheckAfterCompleted()
   在 MeoAsstGui.AsstProxy.ProcTaskChainMsg(AsstMsg msg, JObject details)
   在 MeoAsstGui.AsstProxy.ProcMsg(AsstMsg msg, JObject details)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9973127/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/105404434/200886989-689a57c3-2a1a-45ec-9a71-6fa1b8d32d06.png)
![image](https://user-images.githubusercontent.com/105404434/200887677-e63f112c-e890-4d31-8cf5-5d4f01694702.png)

**Comment by zzyyyl** [comment]
管理员权限。

**Comment by curvit** [comment]
> 管理员权限。

请问是必须每次都要管理员权限打开才行吗，有没有其他解决办法？

**Comment by curvit** [comment]
抱歉没有看到之前有相同提问
