### ISSUE TITLE
繁中服肉鴿無法正常運作

### ISSUE THREAD

**Issue by wong001023** [MaaAssistantArknights/MaaAssistantArknights#2695]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我選在選擇初始幹員時
會放棄招募輔助券
然後直接卡在這
![Screenshot_2022 11 10_01 27 33 661](https://user-images.githubusercontent.com/56993598/200899372-051f7a3b-7829-4ebf-b97c-406436726260.png)

另外開局分隊如果不用預設
而是指定其他分隊
也會卡在這一直左右滑
![Screenshot_2022 11 10_01 30 33 527](https://user-images.githubusercontent.com/56993598/200899897-0f753447-20e6-412a-8c83-8fa0027b37f8.png)

還有指定其他的開局幹員
仍然會選擇山

### 日志文件

選初始幹員卡住
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9973600/asst.log)

選分隊卡住
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9973644/asst.log)

指定開局幹員無效
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9973777/asst.log)

### 还有别的吗？

模擬器：bluestacks 5.9.12.1003 N32
系統：win10
MAA v4.6.12

**Comment by MistEO** [comment]
看日志你应该没选客户端版本

![image](https://user-images.githubusercontent.com/18511905/201111202-e674b94f-3809-4b4c-be08-79a43bca2753.png)

**Comment by wong001023** [comment]
感謝，切換之後就能正常使用了
