### ISSUE TITLE
会客室在线索多余时不会传递线索

### ISSUE THREAD

**Issue by abbaccadd0** [MaaAssistantArknights/MaaAssistantArknights#2696]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

会客室在线索多余时不会传递线索
我翻了翻过往的issue，有人提到过MAA可以给好友发送线索
因此我认为这是个bug

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9976566/asst.log)

### 截图

![Snipaste_2022-11-10_09-51-29](https://user-images.githubusercontent.com/39579855/200981071-0c6108d1-3d5c-4a14-bcc1-b923097b1a4b.png)

### 还有别的吗？

模拟器：蓝叠Hyper-V版
系统：Windows 11 Build 25236

**Comment by zzyyyl** [comment]
只有 10/10 的时候才会传线索

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.1-%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md

![image](https://user-images.githubusercontent.com/18511905/201112123-5d6ac84e-8b91-447c-87ae-a94e27166b59.png)

**Comment by abbaccadd0** [comment]
> https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.1-%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md
> 
> ![image](https://user-images.githubusercontent.com/18511905/201112123-5d6ac84e-8b91-447c-87ae-a94e27166b59.png)

感谢，非常抱歉，下次我会更仔细的查看说明文档
