### ISSUE TITLE
关于【改进自动肉鸽】的若干建议

### ISSUE THREAD

**Issue by Reeleon** [MaaAssistantArknights/MaaAssistantArknights#2697]
### 说说你遇到的问题？

- 我注意到在某些关卡及当前阵容下**漏怪数量超出预期**。
- 我认为有些策略可以改善以**增加深入层数**。
（没有看过自动肉鸽源码，相关建议是根据对自动肉鸽的观察得出的，如有不当，还请谅解）

### 有什么好的想法？

1. 希望能**在1-3层选择有更多战斗结点的路径**，除非有更好的选择，如有很多源石锭并且某条路径上有诡异行商结点。在前3层经历更多战斗有助于增加生存几率。可以在增加“进行更多战斗”这种选择。
2. **增加可选策略**。目前肉鸽设置->策略中只有刷源石锭和刷等级两种选择，实际上仍有制定针对其他目的的策略的需求，比如刷藏品、刷结局（可指定）、解锁队伍等。
3. 希望能**在自动肉鸽中使用作业**，这不是指用户行为，而是maa的行为，具体来说在战斗开始前自动用关卡名+当前阵容在数据库中搜索是否有匹配的作业。充分利用作业可以免于自行决策，减少漏怪数量，提高完美战斗几率。另外，传统作业有一个限制是无法利用额外的干员，而肉鸽作业模板可以有类似“如果有额外的术士干员，可以部署在某某位置”的机制，总之可以针对肉鸽特别设计作业模板。
4. 希望**增加详细版的肉鸽日志**，参考肉鸽通关后的结算界面，但是希望能更丰富，比如【您遇到了古怪商人坎诺特，它正在出售支援补给站（8源石）、支援轰隆隆（8源石）.....，您消耗8源石锭购买了支援补给站】，也就是能完全用文字展示整个肉鸽过程。详细日志可以使用户更容易观察到某些异常或不完善之处，并将本次探索的日志切片上报，这有助于收集用户反馈、进一步改善自动肉鸽体验。
5. **为“现在还没抓到但很可能会抓到”的干员投资藏品**。可以在肉鸽开始前扫描干员列表，在每个节点都根据已经得到的招募券情况、当前层数、当前阵容等等重新计算某个干员会被招募的概率，然后对于很有可能会被招募到的干员，在诡异行商结点可以购买相关的藏品。听起来要上深度学习了（笑）。

### 其他内容

时间：2022-11-10
版本号：v4.6.12

**Comment by zzyyyl** [comment]
1. 战斗节点的问题，现在 MAA 是直接贪心取当前几个分叉里**没战斗**的节点，并没有往后看节点的逻辑，所以这个不太好做）
    这个逻辑是写在 `tasks.json` 的 `"Mizuki@Roguelike@NextLevel"->next` 里的，没有写在代码里，如果要更改几个节点的优先级可以手动把 next 调换顺序。
2. 刷结局刷分队要求不期而遇有很高的自定义程度，现在的逻辑可以认为对于每个不期而遇 maa 的选项是固定的，新的不期而遇逻辑目前只新建了文件夹；藏品目前应该是只有商店做了识别和优选逻辑，战斗掉落的都没做 
3. 现在的肉鸽战斗其实已经差不多就是作业了，真要搞成 copilot 那种形式的作业工作量太大（？）
4. 可以有
5. 感觉对肉鸽通关率啥的优化不大

**Comment by Reeleon** [comment]
感谢回复！
