### ISSUE TITLE
关于自动定时的代码。。。

### ISSUE THREAD

**Issue by 0osmanthus** [MaaAssistantArknights/MaaAssistantArknights#270]
![image](https://user-images.githubusercontent.com/99315037/156927779-8e78824d-e53d-4c32-8a48-4ad0ad66bd6a.png)
![image](https://user-images.githubusercontent.com/99315037/156927788-6a561b56-92a7-44d9-a7eb-5f8b8309a2d4.png)
大概就是用了那个自动定时的代码，然后它说没有interface的库，然后从pycharm到cmd指令pip下载都试了一遍把能下的interface都下了一遍（？）也没有用。。。
然后看了pip下的interface库的文件夹里没有Asst和Message两个函数。。。
Python没接触过多久，仅停留在高中课本水平，所以到底该怎么办。。。

**Comment by MistEO** [comment]
这两个文件在 `src/Python` 目录下

**Comment by 0osmanthus** [comment]
找了一圈实在没有，资源管理器也搜不到。。。（我真tm是个菜鸡.jpg）
所以要重新下interface库吗

**Comment by 0osmanthus** [comment]
![image](https://user-images.githubusercontent.com/99315037/158017523-7cadcb68-8201-4f4a-a3c9-b0a34c759118.png)
感谢解答，但我是菜鸡.jpg

**Comment by MistEO** [comment]
你截图中的报错已经很明显了，既然是 API 接口本来就不是为纯小白用户提供的，请期待新界面自带的定时功能吧~
