### ISSUE TITLE
希望添加清理即将过期理智选项

### ISSUE THREAD

**Issue by 2314933036** [MaaAssistantArknights/MaaAssistantArknights#2700]
### 说说你遇到的问题？

希望添加清理即将过期理智选项,
现在填写清理个数会受到小理智影响(打一关需要使用两次甚至三次)实际maa计算一次,这样就多使用了很多理智

### 有什么好的想法？

添加清理本周/当天过期的理智选项

**Comment by ABA2396** [comment]
#3684 fixed
