### ISSUE TITLE
关于顶配243一天四换中作战记录制造站自动选择干员出现的问题

### ISSUE THREAD

**Issue by Suprelorry** [MaaAssistantArknights/MaaAssistantArknights#2702]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在这个顶配作业中，A+B组前8小时班次自动更换作战记录制造班次，在第一个制造站选完干员并确定之后，进行第二个制造站换班时，maa仍然选择第一个制造站，并将干员换成第二个制造站所需的干员并确认，跳过了第二个制造站的换班，随后进行赤金制造站的换班流程，导致作战记录的第二个制造站沿用了上一个班次的干员或空置。
此次上传的日志文件中，最近一次发生该问题的记录在2022年11月10日晚上21:28左右。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9981197/asst.log)

**Comment by MistEO** [comment]
现在加入了复查机制，应该修掉了（？）
