### ISSUE TITLE
感觉可以在常见问题中的连接问题中加入检查代理服务器设置

### ISSUE THREAD

**Issue by 2683807278** [MaaAssistantArknights/MaaAssistantArknights#2704]
### 说说你遇到的问题？

刚刚在用MAA的时候始终无法连接蓝叠模拟器
就去看了下日志
![image](https://user-images.githubusercontent.com/77843037/201113707-1b8d5e77-0ff8-44cc-ac8d-d9134940e08f.png)
后来发现是v2ray的自动配置系统代理导致的

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md

![image](https://user-images.githubusercontent.com/18511905/201114803-2ce3c705-7f0f-44b9-85b4-c58fee4d893a.png)

**Comment by 2683807278** [comment]
啊，当时没看到😂
