### ISSUE TITLE
对公招刷黄票结果显示统计结果

### ISSUE THREAD

**Issue by LinYanxi0** [MaaAssistantArknights/MaaAssistantArknights#2707]
### 说说你遇到的问题？

当明显地在公招刷黄票时（50次，100次等）
公招依旧像日常一样分散而非统计结果

### 有什么好的想法？

像掉落统计一样，重复四星（及信物）对应30绿票+1黄票
（默认获得的都是第七次及之后了）

可设置选项，设置为50,100,200或更多时计算（可能）获得的黄票
对中途通过显示的日志看黄票有较大帮助

**Comment by ntgmc** [comment]
这个东西你都不知道你四星多少潜能咋算呢(￣ω￣;)

**Comment by LinYanxi0** [comment]
默认公招四星全满潜（
其实就是想刷公招刷到一半看看有多少黄票了
真要说必要性不大(｀・ω・´)
