### ISSUE TITLE
希望增加iOS真机跑MAA功能

### ISSUE THREAD

**Issue by zhujiajun999** [MaaAssistantArknights/MaaAssistantArknights#2709]
### 说说你遇到的问题？

我目前Mac电脑都需要办公，开虚拟器比较卡，希望通过MAA在iOS手机上刷肉鸽

Mac 的idevicesyslog有点类型adb，获取iOS 的UUID，不知道通过这样类型的方法能不能控制iOS

**Comment by MistEO** [comment]
iOS 在 PC/Mac 端应该都没法控制吧？

**Comment by zhujiajun999** [comment]
我这边目前用xctest+xcode可以对iOS手机label的点击控制，这是基于Mac端的

**Comment by MistEO** [comment]
现在似乎可以通过 mac 来跑 IOS 应用的方式实现了（
