### ISSUE TITLE
MAA占用了Mac100多G内存

### ISSUE THREAD

**Issue by zhujiajun999** [MaaAssistantArknights/MaaAssistantArknights#2710]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

使用Android实机连接Mac电脑跑maa水月，突然弹出Mac提示内存不足

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9987121/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/48372509/201279769-794559a6-d3b5-4bb8-b9d6-c91535201bf0.png)

**Comment by ntgmc** [comment]
这是真6

**Comment by sixivanzi** [comment]
6

**Comment by KazeLiu** [comment]
6

**Comment by Sherlote** [comment]
這個應該也是在打肉鴿的時候出現的吧!
之前大佬是教我這麼改等他們解決這個問題
首先到~/Library/Containers/com.hguandl.MeoAsstMac/Data/Library/Application Support/resource/config.json這個點開
第181行後面改成這樣
![IMAGE 2022-11-15 18:38:38](https://user-images.githubusercontent.com/93369556/201898838-bdbd1298-d889-4337-abee-3116754e9264.jpg)
就行了!剩下的就等大佬們修理解決這個問題先這樣子用!

**Comment by zhujiajun999** [comment]
好的，谢谢
