### ISSUE TITLE
建议增加升级使用镜像的开关

### ISSUE THREAD

**Issue by RyoLee** [MaaAssistantArknights/MaaAssistantArknights#2713]
### 说说你遇到的问题？

我这边的网络可以正常访问github(以及阿妈粽的S3服务) 但是MAA升级下载速度异乎寻常的慢
检查了一下路由器的日志,发现MAA下载是通过99988866.xyz的CF代理服务来进行的,而我直接从github release手动下载OTA压缩包则是正常的速度
能否添加一个checkbox来手动决定是否通过内置镜像列表更新,防止出现反向加速的问题呢?

**Comment by MistEO** [comment]
之前这个镜像非常快，最近大幅度降速了。我们准备直接给 Client 做个测速功能（
