### ISSUE TITLE
肉鸽无法招募助战

### ISSUE THREAD

**Issue by MinGW32-2006** [MaaAssistantArknights/MaaAssistantArknights#2715]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I spent at least 5 minutes thinking and preparing before raising the issue.
- [X] I have read the FAQ and the User Manual in the documentation and believe that this is most likely a bug and not designed to be so.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] The screenshots I've uploaded are the original ones taken by the emulator's own screenshot tool (or via adb).

### Description

在水月肉鸽里令稳通前三层，但我自己没有，只能招助战。但截图显示自动肉鸽根本不进入助战页面，无法开局。

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9990764/asst.log)

### Screenshots

![Screenshot_2022 11 11_21 58 03 890](https://user-images.githubusercontent.com/111475297/201355779-7e038322-fe83-4d6d-a589-7470ca7eb221.png)
![Screenshot_2022 11 11_21 57 26 490](https://user-images.githubusercontent.com/111475297/201355761-860cbccb-2b60-48b6-b9da-cf7380899919.png)
![Screenshot_2022 11 11_21 57 58 390](https://user-images.githubusercontent.com/111475297/201355765-a334919d-c0d3-4b2e-bb5a-a58712136ff2.png)

### Anthing else?

MAA : 4.6.13
模拟器 : Bluestacks 5.9.350.1035
系统 : Windows 7 x64
内存 : 8GiB

**Comment by yc080713** [comment]
本来就不支持助战吧...

**Comment by WWPXX233** [comment]
还是有办法的 你可以先手动进行借助战干员 然后进入地图路线选择界面就可以打啦（不过可能会导致奇怪的错误）
