### ISSUE TITLE
代理刷关时若博士升级则会导致游戏崩溃任务失败

### ISSUE THREAD

**Issue by langdang13** [MaaAssistantArknights/MaaAssistantArknights#2721]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我的号未满120级，在使用MAA连续刷关的时候升级了，升级之后MAA无法识别当前页面然后崩溃了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9994683/asst.log)

时间点为2022/11/12/17：35左右

### 截图

![X`6)ZVJJ}{N82G8D2MN{{69](https://user-images.githubusercontent.com/116178249/201468268-d4ad351a-09aa-49e1-a2ee-20c797ad6847.png)

### 还有别的吗？

逍遥模拟器，win11，12700H，3060Ti，最新版本v4.6.13

**Comment by Black1312** [comment]
请更新maa至最新开发版（建议删除旧版下载完整包重新解压），如果问题仍然存在请更换模拟器试试，我这边4.8.0 beta3 蓝叠国际模拟器是没有问题的
