### ISSUE TITLE
卡公告栏maa无法解决

### ISSUE THREAD

**Issue by zxmydmug** [MaaAssistantArknights/MaaAssistantArknights#2726]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

还是卡公告栏。
可不可以先等他的界面加载出来再点×
我看了下逻辑是直接点活动，一般来说是游戏内的，所以可以返回主界面，但是如果有活动的指向是游戏外就会出现报错

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9996295/asst.log)

### 截图

![Desktop Screenshot 2022 11 13 - 08 45 01 62](https://user-images.githubusercontent.com/102844526/201500364-f8c93d66-c29f-4e54-b2f3-0658b0f3e9d4.png)
![Desktop Screenshot 2022 11 13 - 08 45 10 41](https://user-images.githubusercontent.com/102844526/201500365-f7c6cc62-4ead-4b84-ab27-739422095211.png)

**Comment by ABA2396** [comment]
@MistEO 感觉还是得整个任务失败重启游戏

**Comment by ABA2396** [comment]
老问题了.jpg
现在的红包也会卡死
