### ISSUE TITLE
基建 关于训练室

### ISSUE THREAD

**Issue by ijdisjo** [MaaAssistantArknights/MaaAssistantArknights#2727]
### 说说你遇到的问题？

MAA现在基建换班不能训练室收专精，得手动点进去收，如果专一专二结束以后忘了去继续挂专精，MAA还可能把训练室的艾丽妮调走导致吃不到专精时间减半的buff

### 有什么好的想法？

基建换班收专精的功能，如果不是专三则不会把艾丽妮调走训练室
（以下要求可能稍微有点过分23333）
结合仓库检测功能，收专精以后，如果当前是专一/专二而且材料足够，就自动合成专精材料并续上专精

**Comment by ABA2396** [comment]
设置里有个
![image](https://user-images.githubusercontent.com/99072975/201537689-90b5bf4a-9e79-4b0b-b1a8-bab90e45563c.png)
勾选了就不会选艾丽妮了

**Comment by ntgmc** [comment]
> MAA现在基建换班不能训练室收专精，得手动点进去收
这个考虑在做

> 结合仓库检测功能，收专精以后，如果当前是专一/专二而且材料足够，就自动合成专精材料并续上专精
这个不太可能会做，因为有的人只专一
