### ISSUE TITLE
自动肉鸽进不去关卡

### ISSUE THREAD

**Issue by forgiveme0** [MaaAssistantArknights/MaaAssistantArknights#2728]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

蓝叠模拟器hyper-v版，自动肉鸽进不去关卡，见视频 https://github.com/forgiveme0/BUG/blob/main/Rec%200001.mp4 。（WSA也有一样的问题）
（分辨率已调整为16：9）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9996490/asst.log)

**Comment by WWPXX233** [comment]
你是不是选择了影子的模式而非水月的模式

**Comment by zzyyyl** [comment]
根据日志，你的肉鸽主题选错了。
