### ISSUE TITLE
自动肉鸽如何设置招募和进阶的优先级

### ISSUE THREAD

**Issue by 21721677** [MaaAssistantArknights/MaaAssistantArknights#2729]
### 说说你遇到的问题？

在使用山开局的过程中，脚本碰到近卫券会优先招募羽毛笔而不是进阶山，如何设置优先进阶而不是招募？

### 其他内容
已将roguelike_recruit.json配置文件中山的promote_priority字段设置为1000，但是还是会优先招募羽毛笔，这样看的话设置进阶优先级似乎对招募没有影响，我应该如何设置才能优先进阶山？

**Comment by WWPXX233** [comment]
因为进阶和招募是分开算的 你是有山的情况下去招募 还是都没有的情况下进行招募

**Comment by 21721677** [comment]
用山开的局，战斗掉落近卫券，脚本会招募羽毛笔而不是进阶山，如果我想优先进阶山而不是招募新干员应该如何设置参数？

**Comment by WWPXX233** [comment]
你只需要吧参数调高就可以优先进阶它了 不过可能在拥有其他更值得精英的干员的时候依旧会是他 你改成1200就可以了

**Comment by 21721677** [comment]
可是我把山的招募优先级和进阶优先级都改成1000后还是会优先招募羽毛笔，这是bug吗，或许我应该重启MAA才会重新识别json文件？

**Comment by WWPXX233** [comment]
是因为你设置的太低了 而且你居然没有重启Maa。。。需要保存文件重启才能生效

**Comment by 21721677** [comment]
1000已经比羽毛笔的招募和进阶优先级都高了吧，难道里面还有权重？我设置成1200再试一试。关于重启MAA，其实我也不太记得重没重启了😂

**Comment by WWPXX233** [comment]
是这样的

**Comment by 21721677** [comment]
好的，多谢解答
