### ISSUE TITLE
水月肉鸽出现干员倒下时会反复暂停查看恢复中的干员

### ISSUE THREAD

**Issue by Singularity27** [MaaAssistantArknights/MaaAssistantArknights#2732]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如题，触发条件似乎是部署栏里的干员均处于恢复中状态

### 日志文件

[Uploading asst.log…]()

**Comment by zzyyyl** [comment]
看看谁寄了呗，一般有人刚刚寄了的时候会暂停看看

**Comment by MistEO** [comment]
设计如此，要看下是谁寄了

**Comment by Singularity27** [comment]
我可能没表达清楚，当干员倒下时，查看一遍部署栏看谁倒了，这是合理的我对此没有疑问
但我指出的问题是，当部署栏的干员全部处于倒下状态时，暂停-查看部署栏-继续 这套动作会反复进行，这个动作频率大概1s/次，哪怕没有人部署冷却完毕，没有新的干员倒下

**Comment by Singularity27** [comment]
> 设计如此，要看下是谁寄了
我可能没表达清楚，当干员倒下时，查看一遍部署栏看谁倒了，这是合理的我对此没有疑问
但我指出的问题是，当部署栏的干员全部处于倒下状态时，暂停-查看部署栏-继续 这套动作会反复进行，这个动作频率大概1s/次，哪怕没有人部署冷却完毕，没有新的干员倒下

**Comment by MistEO** [comment]
日志再传下看看，你之前的没传上来

**Comment by Singularity27** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10000649/asst.log)

**Comment by MistEO** [comment]
fixed，现在压根不点（
