### ISSUE TITLE
任务全部完成后出现"拒绝访问"错误

### ISSUE THREAD

**Issue by Skeleton321** [MaaAssistantArknights/MaaAssistantArknights#2733]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

全部任务完成后，弹出拒绝访问的错误提示框。猜测与退出操作有关，但并未复现成功。

### 日志文件

[asst.1.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9997384/asst.1.log)
[asst.2.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9997385/asst.2.log)

### 截图

![image](https://user-images.githubusercontent.com/23263915/201524844-c8163e3b-66a2-45d9-b19a-2b9f6972bb3b.png)
![image](https://user-images.githubusercontent.com/23263915/201524846-ab1db6f5-113c-4066-9a0a-5ea1f51a44c4.png)
![image](https://user-images.githubusercontent.com/23263915/201525671-44fafd9a-e8fd-469d-8d02-129bd0acf2b1.png)
![image](https://user-images.githubusercontent.com/23263915/201525685-b83caddb-db09-4ece-a483-d94bfa3dcbda.png)

### 还有别的吗？

MAA版本：v4.6.13
模拟器：无，使用手机，型号Sony Xperia Premium XZ
操作系统：Windows 11 22H2 22621.819

**Comment by zzyyyl** [comment]
考虑用管理员权限打开maa？

**Comment by ABA2396** [comment]
> 考虑用管理员权限打开maa？

这连得手机，为什么要退出模拟器#
