### ISSUE TITLE
无法加载 DLL“MeoAssistant.dll”: 动态链接库(DLL)初始化例程失败。 (异常来自 HRESULT:0x8007045A)。

### ISSUE THREAD

**Issue by beibei0609** [MaaAssistantArknights/MaaAssistantArknights#2734]
### 说说你遇到的问题？

无法加载 DLL“MeoAssistant.dll”: 动态链接库(DLL)初始化例程失败。 (异常来自 HRESULT:0x8007045A)。

**Comment by ntgmc** [comment]
这个是很多人都有的问题，建议仔细阅读使用文档处理：https://maa.plus/docs/，谢谢反馈
