### ISSUE TITLE
内测版 在特殊条件下，maa无法正常停止&傀影肉鸽无法自选分队

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#2735]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

bug1：点击停止运行后maa无法正常停止
bug2：maa无法正常选择分队（傀影肉鸽），卡在分队界面
测试了一下，该bug暂时无法无限复现，未知触发原因

### 日志文件

[audio_log.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9998555/audio_log.txt)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9998556/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/74061867/201551564-b3c4c3d4-7ac0-4ba7-bfec-e5154b252b80.png)

### 还有别的吗？

模拟器：逍遥模拟器
操作系统：win10
maa版本：4.6.14-alpha.0.43.g4f5d04d7

**Comment by ntgmc** [comment]
1

**Comment by MistEO** [comment]
v4.7.0-alpha.4 fixed
