### ISSUE TITLE
自动战斗bug

### ISSUE THREAD

**Issue by HMZyueshen** [MaaAssistantArknights/MaaAssistantArknights#2737]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

MAA打水月肉鸽的时候开摆了
而且自动抄作业功能寄了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9998841/asst.log)

### 截图

![XYBP@NF_12Q OS`BN%0KWJ5](https://user-images.githubusercontent.com/106477016/201557933-d0dbcb65-f16a-44cd-bf3f-6fa05a98be3f.png)
![FY4GL~{6L0I4SJPCSO R4)6](https://user-images.githubusercontent.com/106477016/201557939-8042082c-99ce-43e5-bb8c-c76018fefaa7.png)
![image](https://user-images.githubusercontent.com/106477016/201558400-10800340-e0dd-4a2a-b287-68caa9b68a80.png)

### 还有别的吗？

win10
maa内测最新版
mumu模拟器

**Comment by HMZyueshen** [comment]
没法执行识别干员这个动作

**Comment by HMZyueshen** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9998903/asst.log)

**Comment by ntgmc** [comment]
肉鸽好像不点进去识别，直接头像（一直都是）
然后版本应该改成内测版（标题也加上最好）

**Comment by MistEO** [comment]
只能替换 adb 了，后面可能搞个自动下载 adb
