### ISSUE TITLE
上传企鹅物流数据错误

### ISSUE THREAD

**Issue by pointm** [MaaAssistantArknights/MaaAssistantArknights#274]
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8202989/asst.log)
![114514](https://user-images.githubusercontent.com/49180699/157171961-ae150ef1-318c-44f6-8737-29c6688f92ab.jpg)

刷图的时候显示上传企鹅数据错误，不知道是啥子原因

**Comment by pointm** [comment]
当然对于单纯的刷图，貌似没有什么影响

**Comment by Bl1tzcrank** [comment]
可能是识别掉落的时候出bug了吗，是刷的活动图

**Comment by MistEO** [comment]
> 模拟器是夜神，今天使用的时候第一次上传失败，然后第二次刷图结算的时候就卡住然后脚本闪退了，不知道啥问题 [asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8280259/asst.log)

v3.0.8 fixed
