### ISSUE TITLE
macOS 版本信用商店购物没有参考黑名单和优先购买列表

### ISSUE THREAD

**Issue by hakula139** [MaaAssistantArknights/MaaAssistantArknights#2745]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

使用当前最新的 v4.6.13 版本（macOS），选择任务【收取信用及购物】，在设置里设置如下：

<img width="835" alt="image" src="https://user-images.githubusercontent.com/9496568/201646573-62ebefd2-1427-470c-bbe0-6b743e7a4763.png">

但实际购买情况如图：

<img width="892" alt="image" src="https://user-images.githubusercontent.com/9496568/201646688-8479ad5e-a505-4e9a-9249-b53ff6793f51.png">

期望购买情况：

购买【招聘许可】，不购买【初级作战记录】和【源岩】。

过去版本同样存在此问题，非 v4.6.13 版本的特定修改造成的 bug。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10002424/asst.zip)

问题出现的时间范围：

2022-11-14 19:05:21 ~ 19:05:54 UTC+8（手动结束）

### 截图

游戏内截屏（如果需要）：

![Screenshot_1668425098](https://user-images.githubusercontent.com/9496568/201648428-f0fcf701-35c3-4934-bc41-0c269429af30.png)

### 还有别的吗？

模拟器：

Android Studio 2021.3.1 Patch 1 (AVD)

AVD 设置：

```ini
AvdId=Nexus_5X_API_33
PlayStore.enabled=true
abi.type=arm64-v8a
avd.ini.displayname=Nexus 5X API 33
avd.ini.encoding=UTF-8
disk.dataPartition.size=64G
fastboot.chosenSnapshotFile=
fastboot.forceChosenSnapshotBoot=no
fastboot.forceColdBoot=no
fastboot.forceFastBoot=yes
hw.accelerometer=yes
hw.arc=false
hw.audioInput=yes
hw.battery=yes
hw.camera.back=virtualscene
hw.camera.front=emulated
hw.cpu.arch=arm64
hw.cpu.ncore=4
hw.dPad=no
hw.device.hash2=MD5:ae200ad6786ec467cb9067f7b46b0fd1
hw.device.manufacturer=Google
hw.device.name=Nexus 5X
hw.gps=yes
hw.gpu.enabled=yes
hw.gpu.mode=host
hw.initialOrientation=Portrait
hw.keyboard=yes
hw.lcd.density=420
hw.lcd.height=1920
hw.lcd.width=1080
hw.mainKeys=no
hw.ramSize=4096
hw.sdCard=yes
hw.sensors.orientation=yes
hw.sensors.proximity=yes
hw.trackBall=no
image.sysdir.1=system-images/android-33/google_apis_playstore/arm64-v8a/
runtime.network.latency=none
runtime.network.speed=full
sdcard.size=512M
showDeviceFrame=yes
skin.dynamic=yes
skin.name=nexus_5x
skin.path=/Users/hakula/Library/Android/sdk/skins/nexus_5x
tag.display=Google Play
tag.id=google_apis_playstore
vm.heapSize=512
```

环境：

Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10

**Comment by hakula139** [comment]
FYI，使用中文分号是因为默认 placeholder 就是使用的中文分号，没有测试过英文分号的情况。

**Comment by MistEO** [comment]
```log
[2022-11-14 10:04:15.927][INF][Px1685a][Txe8ee05c88e4496de] append_task Mall {"blacklist":["招聘许可；龙门币"],"buy_first":["碳；家具；加急许可"],"force_shopping_if_credit_full":false,"shopping":false}
```

分号没解析，试试半角的

@hguandl placeholder 考虑改成半角的？

**Comment by hakula139** [comment]
好的，明天刷新信用了试试。

**Comment by hakula139** [comment]
使用半角分号，依然不符合预期。以下是设置截图：

<img width="835" alt="image" src="https://user-images.githubusercontent.com/9496568/201810211-c12b21c3-4baf-4451-811f-b8eb24518286.png">

以下是日志文件：

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10008529/asst.log)

问题出现的时间范围：

2022-11-15 10:13:25 ~ 10:13:34 UTC+8（手动结束）

注意到以下日志内容：

```text
[2022-11-15 10:13:15.463][INF][Px1685a][Txe8ee05c88e4496de] append_task Mall {"blacklist":["招聘许可","龙门币"],"buy_first":["碳","家具","加急许可","源岩"],"force_shopping_if_credit_full":false,"shopping":true}
```

分词是可以了，是不是 blacklist 和 buy_first 写反了？

**Comment by hakula139** [comment]
另外注意到以下日志内容：

```text
[2022-11-15 10:13:32.511][TRC][Px1685a][Tx4767a40c9a8062e7] OcrPack::recognize | raw: [{ 家具商店: [ 38, 35, 85, 22 ], score: 1.000000 }, { 信用交易所: [ 210, 35, 107, 22 ], score: 1.000000 }, { 加刍红司: [ 162, 95, 85, 16 ], score: 0.300000 }]
```

似乎【加急许可】被识别为了【加刍红司】，虽然跟这个 issue 可能没关系，但不知道会不会影响到流程。
