### ISSUE TITLE
CE-6掉落识别错误

### ISSUE THREAD

**Issue by wanghr2000** [MaaAssistantArknights/MaaAssistantArknights#2747]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

CE-6掉落龙门币1万被识别成17或175，还多了一个furni：2
在日志最下面一部分

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10008197/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/38121020/201800896-2ebdc1d1-9f2b-4983-aa2a-a8159325797b.png)
![Screenshot_2022 11 15_09 06 00 169](https://user-images.githubusercontent.com/38121020/201801608-0c2b451f-e51d-46af-9416-b4ad32a860e9.png)

**Comment by ntgmc** [comment]
补充：之前见过识别成15的
