### ISSUE TITLE
建议增加选择常驻剿灭关卡

### ISSUE THREAD

**Issue by Kagura-Nanaa** [MaaAssistantArknights/MaaAssistantArknights#275]
现在直接选剿灭作战会直接选默认的限时关卡，有时候没打就卡在那里了

**Comment by pointm** [comment]
> 现在直接选剿灭作战会直接选默认的限时关卡，有时候没打就卡在那里了

可以先停在剿灭关卡不进去，然后在模拟器的关卡选择里面选择当前关卡，定义指定次数为想刷取的次数，来完成剿灭。

只不过搞一个当期剿灭或者常驻剿灭的开关也是可以的

**Comment by MistEO** [comment]
短期内不会做的，关卡适配比较麻烦，还有 `1-7` 这种亟待适配的都没弄 orz

非当期关卡感觉不是太强需求，手动点过去使用 `当前关卡` 来进行吧~
