### ISSUE TITLE
基建换人时中卡住

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#2756]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

换班时卡住，前两次在控制中枢中换人时，本次在贸易站0中。
截图2中可知已在该位置等待2分钟。
按下停止按钮显示正在停止但无法回到可开始状态。
尝试单独选择基建换班该问题未出现。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10014306/asst.log)

### 截图

![MuMu20221116031215](https://user-images.githubusercontent.com/74366156/201969771-d8936194-1da9-4046-9753-7af36e9c5ac5.png)
![image](https://user-images.githubusercontent.com/74366156/201970352-c16c7fbf-b4d2-4708-9420-0fa634069cd9.png)

### 还有别的吗？

操作系统：win11。
当前开着向国内的加速器。

**Comment by ntgmc** [comment]
>按下停止按钮显示正在停止但无法回到可开始状态。 尝试单独选择基建换班该问题未出现。
 
这个好像是随机的，和选项没关系？

**Comment by kxdxzr** [comment]
![MuMu20221117173355](https://user-images.githubusercontent.com/74366156/202373734-10e388f0-0d94-4977-a7f2-199b8c5c2ae3.png)
![image](https://user-images.githubusercontent.com/74366156/202373744-aa317a34-f31c-4db2-b7f1-10ab6c84495e.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10028617/asst.log)

**Comment by kxdxzr** [comment]
![MuMu20221117183159](https://user-images.githubusercontent.com/74366156/202384017-0581c501-a2c6-4eee-8650-21425c439d0c.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10028973/asst.log)
![image](https://user-images.githubusercontent.com/74366156/202384113-bd16b585-381b-4ec7-ba5d-c81f0aa23e97.png)

这些事件发生时有一半的情况是我后台挂着明日方舟然后前台打星际，这会和我在打星际有关吗

**Comment by kxdxzr** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10030084/asst.log)
![MuMu20221117205111](https://user-images.githubusercontent.com/74366156/202414027-e08826e8-4edf-434e-be68-7bae9f4fb74a.png)
![image](https://user-images.githubusercontent.com/74366156/202414107-d03655d7-5172-4a19-930f-c9a658133652.png)

**Comment by MistEO** [comment]
更新一下，发版说明里有写

**Comment by MistEO** [comment]
v4.7.0-alpha.4 fixed
