### ISSUE TITLE
由于其他活动的开启导致MAA的UI上直接导向活动关卡“IS-8”“IS-9”和"IS-10"的关卡导航失效

### ISSUE THREAD

**Issue by Mo-Yuxi** [MaaAssistantArknights/MaaAssistantArknights#2757]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在开启危机合约后，游戏内终端界面的活动入口位置发生变化，导致无法使用UI上选定当前SideStory关卡进行刷理智

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10014569/asst.log)
发生时间22-11-16 00:42

### 截图

Null

### 还有别的吗？

2022-11-16下午16:00发生危机合约和SS活动第三部分一起开启

**Comment by ntgmc** [comment]
马上更新新版本，新版本修复了，现在先用着【当前/上次】来解决吧
