### ISSUE TITLE
内测版由于滑动太快导致基建换班的时候识别不到干员

### ISSUE THREAD

**Issue by Suprelorry** [MaaAssistantArknights/MaaAssistantArknights#2760]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在自动换班的过程中，滑动速度过快，导致干员识别不到，一直卡在某一进度。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10016976/asst.log)

### 截图

![QQ浏览器截图20221116075715](https://user-images.githubusercontent.com/95360532/202050382-adb08bd7-3912-44b4-a99d-629c91610c80.png)

**Comment by MistEO** [comment]
v4.7.0-alpha.4 fixed
