### ISSUE TITLE
功能建议：选择执行“一键长草”中的某个项目

### ISSUE THREAD

**Issue by giteeeeee** [MaaAssistantArknights/MaaAssistantArknights#2762]
### 说说你遇到的问题？

有时我想单独运行一键长草中的某个项目(比如刷理智)，但目前的功能全是联动的，想要单独执行只能把其他项挨个点掉，再点link start

### 有什么好的想法？

在每个项目旁边加一个“执行”图标：

![New Project (45)](https://user-images.githubusercontent.com/89521447/202065887-b515c9fb-26ad-4a89-a901-f1661154f28a.png)

如图所示，点击图标后，单独执行“刷理智”项目

**Comment by ntgmc** [comment]
这边建议【清空】+【刷理智】两步解决
单独做一个执行既累赘也没必要
