### ISSUE TITLE
自动公招的延展功能需求

### ISSUE THREAD

**Issue by zhcnlei** [MaaAssistantArknights/MaaAssistantArknights#2765]
### 说说你遇到的问题？

在有很多招募凭证的情况下，想要通过招募凭证刷新Tag，但加急许可的数量少于招募凭证数量。

### 有什么好的想法？

希望可以自动确认三星Tag，但选择招募时间为1小时，确认后再取消招募，从而达到刷新Tag的目的。

**Comment by zhangweijian97** [comment]
玄学不可取啊。正常刷呗

**Comment by zhcnlei** [comment]
> 玄学不可取啊。正常刷呗

不是玄学啊，就是快速消耗招聘凭证而已呢。

**Comment by ABA2396** [comment]
这是浪费吧，大部分用户都不会这么干的，而且就算一天开一次，白票的获取也赶不上4张吧
