### ISSUE TITLE
拖不到正确位置

### ISSUE THREAD

**Issue by EclipseRest** [MaaAssistantArknights/MaaAssistantArknights#2767]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

可能是因为电脑的奇特分辨率，近战拖不到正确位置（如模拟器截图没有堵门导致漏怪），此外还偶尔有部分高台没法正确拖到位置，也许只是我本地需要调整一下分辨率的问题？总之感谢解答，近战拖错位置的时间同截图名称，23：00：06

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10023155/asst.log)
[Uploading asst.log…]()

### 截图

![Screenshot_2022 11 16_23 00 06 569](https://user-images.githubusercontent.com/118370812/202218033-bf532417-0990-45e6-be8d-5ce357c3033b.png)
![桌面分辨率](https://user-images.githubusercontent.com/118370812/202218685-50b4a10e-d993-42ca-ade6-47a8ea4dcf57.jpg)
![模拟器分辨率](https://user-images.githubusercontent.com/118370812/202218877-e3578f1f-90ae-403a-aa4c-1f09b04419da.png)

**Comment by ntgmc** [comment]
试一下改成320dpi看看？

**Comment by WWPXX233** [comment]
你的版本是内测版吗 目前还不稳定 如果想刷取的话建议重新下载稳定版来刷取

**Comment by MistEO** [comment]
试试新的开发版

**Comment by MistEO** [comment]
v4.7.0-alpha.4 fixed
