### ISSUE TITLE
提供一个开关，当设施内有干员体力低于阈值时，将该建筑内的全部干员送入宿舍

### ISSUE THREAD

**Issue by abbaccadd0** [MaaAssistantArknights/MaaAssistantArknights#2769]
### 说说你遇到的问题？

根据观察，现在的更换方法是，当干员心情低于阈值时，将该名干员送入宿舍，并在剩余心情高于阈值的干员中选择组合。
这样做的坏处是，有些干员会增减心情消耗，导致原本应该在一组的三名干员很难再次碰到一起。
这个问题可以通过写排班表来解决，但是因为生活原因，很难定时定点打开模拟器去换干员，并且由于每个人的干员池不同，修改目前已有的排班表也会很麻烦，不如让MAA来算效率。

### 有什么好的想法？

建议提供一个开关，默认关闭。当开关开启时，若设施内干员至少有一名心情低于阈值，则将整个设施的干员都送往宿舍，并在满心情的干员中选择效率最高的干员组合。

**Comment by qingyuns** [comment]
很赞同，我也是一样的情况

**Comment by MistEO** [comment]
对效率有要求建议用自定义基建
