### ISSUE TITLE
4.7.0 alpha.2 抄作业bug

### ISSUE THREAD

**Issue by EXCADOGOD** [MaaAssistantArknights/MaaAssistantArknights#2771]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

抄作业会点几次暂停然后卡住maa://11352

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10027119/asst.log)
10:09-10:10左右

### 截图

![QQ图片20221117101020](https://user-images.githubusercontent.com/45102804/202337332-f8edeaa1-9906-4245-9e34-6d798d3e6fb6.png)

### 还有别的吗？

蓝叠5国际版 WIN11 22H2 11800H 3080LAPTOP 32G内存

**Comment by EXCADOGOD** [comment]
管理员模式启动然后替换ADB提示请打开管理员模式

**Comment by ntgmc** [comment]
Something that may course by #2773

**Comment by EXCADOGOD** [comment]
蓝叠5国际版的问题，我更换蓝叠5国服就正常可以替换了

**Comment by EXCADOGOD** [comment]
替换ADB后又不下人了，再次替换ADB出现之前一样替换不了的BUG

**Comment by EXCADOGOD** [comment]
应该是已经替换成功后无法再次替换，抄作业出现的问题可能是操作太快了或者其他BUG导致的，肉鸽里就是因为太快导致放人失败，已经另外提交issue了

**Comment by ntgmc** [comment]
![image](https://user-images.githubusercontent.com/74061867/202431874-00a5f21c-3607-42f1-9ef3-c949c9d36695.png)
