### ISSUE TITLE
更新之后软件报错

### ISSUE THREAD

**Issue by dieveryyoung** [MaaAssistantArknights/MaaAssistantArknights#2772]
11/17上午将版本更新到内测最新版之后，打开软件就会报错，弹出如附件的窗口。
![SDCVN JW1 M Q%DF884$U5T](https://user-images.githubusercontent.com/54274271/202338346-9b945f6b-7b53-45ee-86fe-b3778fb41559.png)

**Comment by ntgmc** [comment]
疑似下载的ota包被占用，无法解压（或删除），建议手动解压覆盖试试？
