### ISSUE TITLE
4.7.0alpha2无法替换ADB

### ISSUE THREAD

**Issue by EXCADOGOD** [MaaAssistantArknights/MaaAssistantArknights#2773]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

无法自动战斗，按说明使用管理员模式启动无法替换ADB

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10027193/asst.log)
10:26

### 截图

<img width="465" alt="屏幕截图_20221117_102450" src="https://user-images.githubusercontent.com/45102804/202339527-9d434107-064a-4d39-977b-d7b29bc4d2ec.png">

**Comment by ntgmc** [comment]
Similar to #2771
