### ISSUE TITLE
v4.7.0-alpha.2 minitouch版本基建换班经常选不到人

### ISSUE THREAD

**Issue by STONE-Git** [MaaAssistantArknights/MaaAssistantArknights#2774]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

第一次换班的时候一直选不到红云和稀音，第二次点换班的时候划动了几轮之后选到了红云和稀音但又把帕拉斯给取消了，日志文件为第二次换班的情况，大概从10:29起，肉眼看感觉是划过头了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10027234/asst.log)

### 截图

![Snipaste_2022-11-17-10-33-50](https://user-images.githubusercontent.com/63118507/202340910-724e1ae9-6c14-4070-97e1-297e2e51fdc9.png)

**Comment by ntgmc** [comment]
Similar to #2760

**Comment by MistEO** [comment]
v4.7.0-alpha.4 fixed
