### ISSUE TITLE
v4.6.13 关卡选择IS系列时，由于危机合约开放，无法正常导航至关卡

### ISSUE THREAD

**Issue by Divercrow7** [MaaAssistantArknights/MaaAssistantArknights#2775]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

v4.6.13 关卡选择IS系列时，由于危机合约开放，无法正常导航至关卡

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10027590/asst.log)
大致时间11：50，2022/11/17

**Comment by ntgmc** [comment]
该功能已经修复，请更新到最新版（4.7.0-alpha2），感谢您的反馈！

This function has been repaired. Please update to the latest version（4.7.0-alpha2）. Thank you for your feedback!
