### ISSUE TITLE
幽灵鲨可否在肉鸽中使用一技能

### ISSUE THREAD

**Issue by sourbadfish** [MaaAssistantArknights/MaaAssistantArknights#2782]
### 说说你遇到的问题？

幽灵鲨可否在肉鸽中使用一技能，用二技能收益小且大概率漏怪

**Comment by ntgmc** [comment]
可以自行修改，在【maa运行目录\resource\roguelike_recruit.json】里面有每个干员的选择详情
![image](https://user-images.githubusercontent.com/74061867/202439698-19a02306-7b97-49e0-aec4-e697ae5a85dd.png)
如图，2改为1即可
