### ISSUE TITLE
会客厅自动传递线索功能

### ISSUE THREAD

**Issue by KuangYang452** [MaaAssistantArknights/MaaAssistantArknights#2783]
### 说说你遇到的问题？

个人原因，比较喜欢把自己的线索全部传递出去，仅使用别人传来的线索开线索交流会。
但是目前版本的MAA并不会传递线索，这是比较烦恼的地方。

### 有什么好的想法？

这个功能可能会要的配置选项：

传递的线索
  仅溢出——只在线索库存溢出时传递
  仅富余——只在线索富余时传递
  一直——不保留线索，全部用于传递

传递的对象优先级
  今日上线的玩家
  今日和昨日上线的玩家
  最近7天有上线的玩家
  缺少单个线索的玩家
  缺少多个线索的玩家
  指定选择一个玩家
  随机选取一个玩家

**Comment by ntgmc** [comment]
Increase on the basis of #1264
