### ISSUE TITLE
BlueStack5(Hyper-V)随机adb端口导致连接失败

### ISSUE THREAD

**Issue by filwaline** [MaaAssistantArknights/MaaAssistantArknights#2791]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

出于一些特定的原因，我需要使用Hyper-V版本的BlueStack模拟器，然后发现这个版本会在每次启动时随机设定adb端口，导致MAA无法顺利完成连接。

研究了一下，我有了解决方案：
- 从`C:\ProgramData\BlueStacks_nxt\bluestacks.conf`第90行读取新端口号
- 修改MAA的`gui.json`
- 启动MAA

剩下的问题是，怎么让MAA在启动前执行我的script？
（我可以在script最后指定启动MAA，然后每次都执行script，而不是MAA.exe，但是我希望把流程嵌入到MAA，这应该怎么做？）

### 日志文件

不需要

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.md#-%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E5%9B%BD%E9%99%85%E7%89%88-hyper-v-%E7%89%88%E6%9C%AC

**Comment by filwaline** [comment]
呃，居然已经有了，偏偏漏了看这篇文档……
