### ISSUE TITLE
无法选择关卡刷理智，win10，夜神模拟器

### ISSUE THREAD

**Issue by qwertyu544** [MaaAssistantArknights/MaaAssistantArknights#2792]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

开始刷理智，选择关卡后，任务一直失败
![Screenshot_20221118-114126](https://user-images.githubusercontent.com/49260187/202612437-f4b16bf6-2f17-4ae6-8ece-1ba07c7b2fb5.png)
![微信截图_20221118114820](https://user-images.githubusercontent.com/49260187/202612800-1e4db1e0-df77-4901-9db6-b1ef9cfc5be2.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10037543/asst.log)
2022-11-18 11:32左右

### 截图

![微信截图_20221118114820](https://user-images.githubusercontent.com/49260187/202612786-d24db49e-05df-4edc-954c-4015aa490639.png)
![Screenshot_20221118-114126](https://user-images.githubusercontent.com/49260187/202612847-8bfa4b57-cfa8-44a8-aa37-7418807a8d83.png)

### 还有别的吗？

win10，夜神模拟器

**Comment by Black1312** [comment]
请将设置中更新渠道改为开发版并检查更新到最新版。您也可以通过设置界面最下方加入Q群或频道来获取最新版。如果问题仍未解决请回复或再次提issue

**Comment by ntgmc** [comment]
![image](https://user-images.githubusercontent.com/74061867/202634314-c31800ac-0f33-4413-af78-94d85a7a219e.png)

**Comment by ntgmc** [comment]
The same as #2755 #2757 #2763
