### ISSUE TITLE
刷理智并未按照预设关卡刷取

### ISSUE THREAD

**Issue by alon74** [MaaAssistantArknights/MaaAssistantArknights#2793]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

MAA关卡选择IS-8(SS活动8图，掉蓝土)，实际阅读日志后发现并未刷取IS-8，游戏内终端界面“前往上一次作战停留在CE-6”(是MAA关卡选择中的备选关卡)

截图可见最后一次自动刷理智仅识别到掉落175龙门币 并无蓝土，怀疑并未刷取IS-8

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10039160/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/42845804/202648734-d0bc576d-0433-40f8-87ef-c018f620a207.png)

**Comment by ntgmc** [comment]
首先，下次截图的时候请把整个maa截上。
然后，![image](https://user-images.githubusercontent.com/74061867/202659225-0d2fc8b5-cdfb-46c4-a601-14cc58f8da76.png)看看您选的什么？请问现在最新版是啥？请问4.7更新了啥？
接着，请您看看 #2755 #2757 #2763 #2775 #2792，看看他们说了什么好吗？
