### ISSUE TITLE
4.7.0-alpha3 肉鸽模式下屏幕方向识别错误

### ISSUE THREAD

**Issue by Skeleton321** [MaaAssistantArknights/MaaAssistantArknights#2794]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

**已强制替换ADB**

准确来说是在需要拖动的情况下都出现屏幕方向判断错误的情况，肉鸽模式下尤为明显(因为有大量的需要拖动的场景)。已经根据adb确定当前屏幕方向是landscape。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10038937/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/23263915/202644994-16473ded-6611-4bf9-b186-4c37b83cc6ad.png)

> 输出1和3是landscape，0和2是portraits。
> 参考: 
>> https://stackoverflow.com/questions/26955086/android-adb-commandline-tool-get-orientation
>> https://stackoverflow.com/questions/10040624/check-if-device-is-landscape-via-adb

https://user-images.githubusercontent.com/23263915/202650368-13511459-ec64-4097-9c53-1df4e30f1c4e.mp4

### 还有别的吗？

~gh这10M的视频大小限制真的好难压视频~
adb默认录制时长是3分钟，后面有一点没录到，不过无所谓。已暂停的那个继续是手动点的，不是MAA点的。

看起来像是将横屏识别为了竖屏导致的。已经根据adb确定当前屏幕方向是landscape。

环境信息：
MAA版本：4.7.0-alpha3
模拟器：无，使用手机，型号Sony Xperia Premium XZ
操作系统：Windows 11 22H2 22621.819

**Comment by MistEO** [comment]
0, 2 不能混用，1, 3 也不能，都要单独算。还有一个问题是，启动 maa 时获取到的屏幕方向，后面运行时不能改变（不能旋转 180°）

**Comment by Skeleton321** [comment]
我更新到alpha4了，但是还是有点小问题。

这次是在基建换班就观察到这个现象了，肉鸽这边看得更明显所以录的是肉鸽这边的。基建那边也是拖不动。

这是屏幕方向为1的时候：

https://user-images.githubusercontent.com/23263915/202833972-815ec13f-b2e7-4cf5-b313-b953c245c094.mp4


这是屏幕方向为3的时候：

https://user-images.githubusercontent.com/23263915/202833889-b70bd7a4-8130-405f-bf6e-1575087c2a85.mp4


这个是两次的日志，都是先换好屏幕方向再启动maa：

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10046034/asst.log)

- 方向为1的时候在左上拖动的，为3的时候在右下拖动的，像是修了但是没完全修的样子: (

- 根据我自己测试的情况来看，0是竖屏，1是逆时针旋转90°，3是逆时针旋转270°。

- 如果用wm set 720x1280修改分辨率的话，直接就操作不了(这个问题好像一直都有，应该是点到屏幕外面去了)，通过修改缩放是解决不了问题的。
