### ISSUE TITLE
自动放弃任务并结束进程

### ISSUE THREAD

**Issue by MisterCoBen** [MaaAssistantArknights/MaaAssistantArknights#2795]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在我离开电脑无人监视或后台运行的情况下， MAA会自动结束当前进程，并放弃剩余任务。只有我一直盯着才行。如图，我已勾选所有任务，但只进行到基建就结束了，这种情况已经有几个版本了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10039345/asst.log)

### 截图

![Screenshot 2022-11-18 090459](https://user-images.githubusercontent.com/97687476/202652949-9977c098-0679-4f5d-acca-92714cf75b95.png)

### 还有别的吗？

模拟器: 蓝叠国际版 5.9.400.1021 N32

**Comment by NeatCodding** [comment]
+1之前是放弃后闪退，4.7是一直点暂停继续暂停继续

**Comment by ntgmc** [comment]
> 在我离开电脑无人监视或后台运行的情况下， MAA会自动结束当前进程，并放弃剩余任务。只有我一直盯着才行。

我想问一下这是量子力学测不准原理吗？

**Comment by zzyyyl** [comment]
卡什么界面了
