### ISSUE TITLE
抄作业拖动干员过快导致无法放置

### ISSUE THREAD

**Issue by mengxinwuzhong** [MaaAssistantArknights/MaaAssistantArknights#2796]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在抄作业网站选择危机合约作战，复制代码，连接模拟器开始作战，作战开始后拖动干员过快，目测没有拖动到对应位置，初步怀疑为作业问题，于是换了一份作业依旧无法拖动放置，再次更换地图，依旧没有解决；第二步怀疑是模拟器分辨率的问题，于是找到群文件的maa使用帮助，找到了分辨率以及dpi要求，都修改为最低配置要求，问题依旧无法解决，只好反馈bug
使用模拟器为雷电4，maa版本为2.7.0.2以及2.7.0.3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10040285/asst.log)
此为新下载maa，仅执行了抄作业操作

### 截图

![image](https://user-images.githubusercontent.com/74451387/202675039-7a751683-51b4-4f23-bff1-441648ba9ba9.png)
![image](https://user-images.githubusercontent.com/74451387/202675361-9de651aa-dcbd-46eb-8f96-385ba44ac520.png)

**Comment by mengxinwuzhong** [comment]
问题解决了，感谢

**Comment by ntgmc** [comment]
Supplement: delay problem
