### ISSUE TITLE
自动肉鸽 Auto IS (Phantom)

### ISSUE THREAD

**Issue by halohalor** [MaaAssistantArknights/MaaAssistantArknights#2803]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I spent at least 5 minutes thinking and preparing before raising the issue.
- [X] I have read the FAQ and the User Manual in the documentation and believe that this is most likely a bug and not designed to be so.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [ ] The screenshots I've uploaded are the original ones taken by the emulator's own screenshot tool (or via adb).

### Description

当刷到Encounter给免费升级时，一定会卡在角色升级画面。英文版

### Log files

234

**Comment by ntgmc** [comment]
你的日志没有上传成功，请重新上传。

Your log did not upload successfully, please re-upload it.

**Comment by ntgmc** [comment]
另外你的英文版是啥意思，是EN服吗？

In addition, what does your English version mean? Is it an EN server?

**Comment by halohalor** [comment]
国际服。我的MAA界面是英文。ok

**Comment by MistEO** [comment]
所以你的日志呢，234是个啥

**Comment by halohalor** [comment]
https://drive.google.com/file/d/1PAZkJci5InvuUTAeK26OmpNMVTrvmCTv/view?usp=sharing

这儿 文件38MB太大了
![selection stuck1](https://user-images.githubusercontent.com/14927628/202834056-99fd7ee3-f277-4a29-9cc5-a4fde456b4b8.png)
![selection stuck2](https://user-images.githubusercontent.com/14927628/202834061-ad93e500-3748-4ffb-a8af-d15e9632f41b.png)
![selection stuck](https://user-images.githubusercontent.com/14927628/202834063-cf0424dc-b296-42e6-bb87-13d26d8ece64.png)

**Comment by halohalor** [comment]
![error](https://user-images.githubusercontent.com/14927628/202908262-d6869947-071b-4b15-8c2e-8d926607104e.JPG)
更换task.json出现这个error
