### ISSUE TITLE
识别不动了……

### ISSUE THREAD

**Issue by IranksAdral** [MaaAssistantArknights/MaaAssistantArknights#2804]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

自从更新版本后仓库识别功能就只能停在第一页，不会往后拉了，手动可以。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10045580/asst.log)

### 截图

![2022-11-19_08-00-41 019_raw](https://user-images.githubusercontent.com/87361258/202822883-ce590f50-68f3-4967-ae5e-d8985b7d465b.png)

**Comment by horror-proton** [comment]
看日志好像是往后拉了, 但是画面还是没动, 这之后 maa 的其他操作正常吗, 还是也没反应

**Comment by MistEO** [comment]
强制替换 adb 了吗

**Comment by MistEO** [comment]
> 看日志好像是往后拉了, 但是画面还是没动, 这之后 maa 的其他操作正常吗, 还是也没反应

好几个模拟器自带的 adb 版本太老了，没把 stdin 接出来，输入不进去东西。手动敲命令也输入不进去。所以搞了个替换的功能
