### ISSUE TITLE
alpha3与4 自动作战 无法暂停识别，无暂停动作

### ISSUE THREAD

**Issue by cenfusheng** [MaaAssistantArknights/MaaAssistantArknights#2806]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

![1668833331948](https://user-images.githubusercontent.com/52312717/202834819-6f136c03-1c9a-4069-80f4-67b36efd55c7.png)

补充：自动编队可用，正常识别。

### 日志文件

[asst (2).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10046097/asst.2.log)

**Comment by cenfusheng** [comment]
补充：自动编队可用，正常识别，但也有中途卡住不动的现象。

**Comment by cenfusheng** [comment]
[asst (3).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10046106/asst.3.log)

自动编队卡住的日志

**Comment by cenfusheng** [comment]
补充，4.6.13可用，即无minitouch的版本可正常使用

**Comment by cenfusheng** [comment]
![0{L_1SS0EOV2B(1A U1`0HX](https://user-images.githubusercontent.com/52312717/202835120-f8a44f9e-36e7-4180-b230-4da51d889fd2.png)
![OYDTZ{3}P6CM`@6`_$E@U5I](https://user-images.githubusercontent.com/52312717/202835123-4292a8c9-1bcc-417c-a103-d04dd4db87e8.png)
一些模拟器配置数据

**Comment by cenfusheng** [comment]
一些模拟器配置
![0{L_1SS0EOV2B(1A U1`0HX](https://user-images.githubusercontent.com/52312717/202835144-732e0efe-e464-4944-8d10-f6d28b25c77a.png)
![OYDTZ{3}P6CM`@6`_$E@U5I](https://user-images.githubusercontent.com/52312717/202835148-95d2520a-05ed-4d8b-9749-aaae005cd37c.png)

**Comment by MistEO** [comment]
adb 没替换
