### ISSUE TITLE
基建办公室换班异常

### ISSUE THREAD

**Issue by 70CentsApple** [MaaAssistantArknights/MaaAssistantArknights#2807]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

会卡在这个页面，然后无反应
我猜测应该是对 **斥罪** 新干员的支持还没做好
日志显示任务为**Office 0**
![image](https://user-images.githubusercontent.com/63957117/202837145-8c46129c-7785-4e26-8c09-0546ab217cbf.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10046206/asst.log)

### 还有别的吗？
MuMu模拟器
MAA - v4.7.0-alpha.4
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10046207/gui.log)

**Comment by MistEO** [comment]
滑动没生效，是不是没替换 adb
