### ISSUE TITLE
支持一下多开，至少别报错得太频繁

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#2808]
### 说说你遇到的问题？

我现在是直接通过运行多个MAA来分别处理不同模拟器的任务，在某些情况下会出现恰好两个MAA同时访问同一个log文件导致其中一个MAA因为访问失败而报错关闭

### 有什么好的想法？

如果文件访问失败了就隔一两秒再重试一下，失败三次再报错？
当然假如能直接原生支持一下多开那是最好的

**Comment by Minepig** [comment]
另外，最近几次更新之后，多开有时会出现只有一个模拟器正常，其他的模拟器无法拖动之类的原因，以前没有出现过这种情况，尝试过直接换成自定义连接中的ADB，但是反而会导致频繁断开连接
模拟器是蓝叠中国版

**Comment by MistEO** [comment]
你把文件夹复制两份就不会冲突了（

**Comment by Minepig** [comment]
> 你把文件夹复制两份就不会冲突了（

啊，复制五份未免有亿点蠢

**Comment by MistEO** [comment]
每份 adb 都不一样，你咋用。每次都改么？复制的还能用不同的配置
