### ISSUE TITLE
肉鸽遇到不期而遇的疯狂玩偶时卡住

### ISSUE THREAD

**Issue by ping1999** [MaaAssistantArknights/MaaAssistantArknights#281]
![image](https://user-images.githubusercontent.com/20700230/157863525-5717b7ec-b392-42f7-9398-3b63383ae629.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8231653/asst.log)
夜神模拟器

**Comment by MistEO** [comment]
什么时间点卡住了？我看日志最后还是在战斗中呀
