### ISSUE TITLE
爱丽丝识别错误

### ISSUE THREAD

**Issue by helloworldqwer** [MaaAssistantArknights/MaaAssistantArknights#2813]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

采用一天三换,每天第一班爱丽丝固定无法正确进入宿舍,其他两班正常,未提示无法找到爱丽丝,也没有在干员列表反复寻找的表现,爱丽丝为镜中来访皮肤

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10048219/asst.log)

### 还有别的吗？

蓝叠模拟器国际版

**Comment by MistEO** [comment]
识别结果完全不对，没搞懂为什么还有两班能正常 orz

这个是之前自动更新出了点问题，重新下载个完整包看看
