### ISSUE TITLE
检测模拟器出错，请使用管理员权限打开本软件或手动设置连接

### ISSUE THREAD

**Issue by abbaccadd0** [MaaAssistantArknights/MaaAssistantArknights#2814]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

运行MAA，提示：检测模拟器出错，请使用管理员权限打开本软件或手动设置连接
之后提示：连接失败，正在尝试启动模拟器
但是模拟器在MAA开启前就是打开的状态，接下来也能自动连接上
因此我认为这个提示属于Bug

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10048223/asst.log)

### 截图

![Snipaste_2022-11-20_09-01-04](https://user-images.githubusercontent.com/39579855/202877880-ce473afc-dd36-4f65-9457-0e0b75040073.png)

### 还有别的吗？

系统：Windows 11
模拟器：蓝叠模拟器Hyper-V版

**Comment by MistEO** [comment]
端口设置的不对？你填了 Hyper V 自动读取端口那个配置项了吗

**Comment by abbaccadd0** [comment]
> 端口设置的不对？你填了 Hyper V 自动读取端口那个配置项了吗

填写了的，并且可以正常读取  
MAA也是以管理员身份运行的，但是大部分时间都会这么提示
少部分在尝试启动模拟器也失败后会这样提示
![Snipaste_2022-11-21_12-25-55](https://user-images.githubusercontent.com/39579855/202965849-f2effe98-6488-49ee-afef-ded1ea319a29.png)
看，端口是一致的，但就是无法连接
而且这个问题没有确定的解决办法，有时候需要重启模拟器，有时候需要重启MAA，有时候却让MAA假装启动已经启动的模拟器就能连接
我查看了asst.log，没有记录有关这次失败的日志，gui.log则与截图输出一致

**Comment by Akasteria** [comment]
同样是蓝叠国际hyperv，更新4.7.0以后出现自动连接不上的问题。我这提示连接失败，试了很多设置都没能连接成功，
也试过重新下载完整版
gui.json里面加上了bluestacks.conf的目录，出现问题期间也没有更改蓝叠的设置或者更新，所以应该是MAA的问题
![image](https://user-images.githubusercontent.com/60087307/205399264-62eecba4-b9d1-46f5-9cf8-6eb1cfb39de0.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10144717/asst.log)

**Comment by code110** [comment]
我也遇到了这个问题，我记得好像原来gui文件不再config文件夹里面的时候没这个问题。现在只能手动填端口
