### ISSUE TITLE
水月肉鸽 启动的时候会卡在这个界面上

### ISSUE THREAD

**Issue by gdf159159** [MaaAssistantArknights/MaaAssistantArknights#2815]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

水月肉鸽 启动的时候会卡在这个界面上

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10048358/asst.log)

11点左右遇到的

### 截图

![2022-11-20_10-58-25 695_raw](https://user-images.githubusercontent.com/8487256/202880688-2adf80ec-2460-401c-8d72-880f7425ae6a.png)

**Comment by gdf159159** [comment]
切换到720 没在遇到

**Comment by ntgmc** [comment]
这个和分辨率没关系，是要自己选好难度
