### ISSUE TITLE
MAA开启后，模拟器卡顿，CPU使用率暴涨

### ISSUE THREAD

**Issue by gaoysz** [MaaAssistantArknights/MaaAssistantArknights#2816]
### 说说你遇到的问题？

我用的是蓝叠模拟器国际版，版本号5.9.300.1018 N64。比如在挂水月肉鸽的时候，在不开启MAA的时候，帧数可以稳定60帧，但是使用自动肉鸽功能时，帧数只能在50多徘徊，最多下降20帧到40帧左右，于此同时CPU使用率会突然暴涨。想问一下是不是我的设置哪里有问题。（配置是12700H+3070 Laptop）

**Comment by Mustard030** [comment]
我也遇到了同样的问题，曾经使用雷电模拟器的时候我以为是模拟器的问题，于是更换成了蓝叠国际版5.9.610.1005 N32，但是仍有同样的情况。（配置是13600kf+6600xt）并且在使用雷电模拟器的时候内存占用会到达100%，然后卡死闪退。

**Comment by MistEO** [comment]
之前主要是 OCR 吃的厉害，现在全优化了，如果还是这样应该没什么好办法了（
