### ISSUE TITLE
MAA启动连接错误

### ISSUE THREAD

**Issue by Kosicer** [MaaAssistantArknights/MaaAssistantArknights#2817]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

mumu模拟器在使用管理员权限打开后，无论是否替换强制替换adb，都是无法正常连接，显示连接失败，查证adb文件位置也没有出错。连接地址也没有问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10048880/asst.log)

### 截图

![屏幕截图 2022-11-20 124850](https://user-images.githubusercontent.com/107397636/202886160-9a7b6848-b760-4e22-a36b-392f7dbd216f.png)
![屏幕截图 2022-11-20 125039](https://user-images.githubusercontent.com/107397636/202886214-b96c66d8-3cf2-4dff-8141-6a8e59ef7926.png)

**Comment by gdf159159** [comment]
重装mumu 不要使用强制替换   

我夜神用过 强制替换 这个功能之后 夜神的adb就瘫痪了 只能重装夜神

**Comment by Black1312** [comment]
请更新maa到最新开发版检测问题是否存在，如存在，请检查maa连接设置是否勾选adb连接失败自动启动模拟器，maa启动设置是否填写模拟器路径，mumu可能需要管理员打开maa，并且关闭系统的管理员权限询问。因替换过adb，可能需要覆盖安装模拟器来还原adb，未能解决请点击最新开发版设置界面最下方加群咨询或重新提交issue
