### ISSUE TITLE
定时启动在每天9点的时候启动不了

### ISSUE THREAD

**Issue by LeviZhang1996** [MaaAssistantArknights/MaaAssistantArknights#2818]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

最近两周我设置的9点定时启动都不会执行，不知道为什么。MAA在显示基建班次信息之后就没有再显示其他内容，正常如果有启动连接应该会显示连接然后startup啥的对吧？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10048896/asst.log)

### 还有别的吗？

蓝叠5，Windows10

**Comment by zxmydmug** [comment]
也碰到了同样的问题
