### ISSUE TITLE
自动战斗不支持【尚蜀山道】关卡

### ISSUE THREAD

**Issue by Nilou-s-cat** [MaaAssistantArknights/MaaAssistantArknights#2822]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

使用最新版本的自动战斗时，加载【尚蜀山道】关卡的脚本时，开始行动后输出不支持该关卡，使用管理员权限重启maa后问题仍然存在，再次重启模拟器后问题仍然存在。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10049187/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/106463935/202892913-a92c0332-d2df-4410-ae3a-36e0ba46fec2.png)

### 还有别的吗？

使用到的自动战斗json
[MAACopilot_作业 (4).txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10049182/MAACopilot_.4.txt)

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/202894160-99ee33ba-043d-4458-b581-f24a34361b7d.png)

**Comment by cenfusheng** [comment]
更新测试版，稳定版没有危机合约的图

**Comment by Nilou-s-cat** [comment]
对不起，是我的问题，给您添麻烦了
