### ISSUE TITLE
水月肉鸽漂流匣逻辑

### ISSUE THREAD

**Issue by cenfusheng** [MaaAssistantArknights/MaaAssistantArknights#2824]
### 说说你遇到的问题？

![7c7078a5bdd2ed7c](https://user-images.githubusercontent.com/52312717/202895383-ec1dc8f7-d94d-4900-90df-edcfc9824895.png)

### 有什么好的想法？

漂流匣优先点1，1点不通再选2，2点不通再放弃
反正MAA留钥匙和骰子也没什么用

**Comment by ntgmc** [comment]
码好像打了，又好像没有
