### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by Sakuma-Rei** [MaaAssistantArknights/MaaAssistantArknights#2827]
### 说说你遇到的问题？

基建默认有心情未满的直接放进去了 能不能屏蔽掉某些干员（有些是给芳汀这种需要心情多少以下加工材料用的 所以卡心情）
另外是信用商店 能不能增设一个不sale的东西屏蔽掉哪些材料 sale时照常买
其他的就 基建换班这个疑似选择哪组换班要自己设定（？）未来能不能自动三班倒 总之maa本身的定时会覆盖一图流写的时间 然后一图流使用不使用无人机会覆盖maa（）希望能统一一下 无人机也由maa覆盖一图流吧

**Comment by MistEO** [comment]
排版计划也设置时间，maa 定时也设置时间，就行了
