### ISSUE TITLE
IS stuck at safe house

### ISSUE THREAD

**Issue by halohalor** [MaaAssistantArknights/MaaAssistantArknights#2828]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I spent at least 5 minutes thinking and preparing before raising the issue.
- [X] I have read the FAQ and the User Manual in the documentation and believe that this is most likely a bug and not designed to be so.
- [ ] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] The screenshots I've uploaded are the original ones taken by the emulator's own screenshot tool (or via adb).

### Description

Stuck at safe house

### Log files

[asst - safe house stuck.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10049899/asst.-.safe.house.stuck.txt)

### Screenshots

![safe house 2](https://user-images.githubusercontent.com/14927628/202907477-4957e6f8-d93c-43c1-88c1-e6398eec535a.JPG)
![safe house 1](https://user-images.githubusercontent.com/14927628/202907480-a22cccb6-0a72-42ff-9396-773f84942b85.JPG)

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/202909184-5ce894c7-d4ab-40f2-b6e7-1b567a8db634.png)
![image](https://user-images.githubusercontent.com/18511905/202909196-b0f403bc-0ff5-465a-b41a-0ab72bb92cac.png)

**Comment by halohalor** [comment]
> ![image](https://user-images.githubusercontent.com/18511905/202909184-5ce894c7-d4ab-40f2-b6e7-1b567a8db634.png) ![image](https://user-images.githubusercontent.com/18511905/202909196-b0f403bc-0ff5-465a-b41a-0ab72bb92cac.png)

我更新task.json 开启MAA出错误 开不了
重新下载了 现在刷普通关卡也不能了
把屏幕放到开始按钮 MAA会自动点去主页面然后就停了

**Comment by MistEO** [comment]
Please update the full version (or the OTA package), not a particular file.
