### ISSUE TITLE
重新下载过后不能自动 运作 1280*720

### ISSUE THREAD

**Issue by halohalor** [MaaAssistantArknights/MaaAssistantArknights#2829]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I spent at least 5 minutes thinking and preparing before raising the issue.
- [X] I have read the FAQ and the User Manual in the documentation and believe that this is most likely a bug and not designed to be so.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] The screenshots I've uploaded are the original ones taken by the emulator's own screenshot tool (or via adb).

### Description

类似捉错点 我跟着步骤做之前没事
重新下载后 就不能运作

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10050031/asst.log)

**Comment by MistEO** [comment]
It looks like you didn't set the client version. Please go to maa settings - connection settings - YostarEN.

BTW, You can send English directly. Machine translation of Chinese is hard to understand.
