### ISSUE TITLE
b服的开始唤醒会被直接打断

### ISSUE THREAD

**Issue by Tanulav** [MaaAssistantArknights/MaaAssistantArknights#283]
![无标题](https://user-images.githubusercontent.com/83046892/158058964-4f2d3d1b-b562-4afa-815b-af6739e1f104.png)

**Comment by MistEO** [comment]
请附一下日志吧

**Comment by Tanulav** [comment]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8239788/asst.log)

**Comment by MistEO** [comment]
应该和 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/317 是同一个问题，下个版本修复~

**Comment by MistEO** [comment]
v3.0.9 fixed
