### ISSUE TITLE
自动战斗 报错

### ISSUE THREAD

**Issue by xcdlh** [MaaAssistantArknights/MaaAssistantArknights#2830]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

不支持的关卡 请更新maa 和检查作业 
4.6.13和4.7.0bete都不行好奇怪

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10050030/asst.log)

### 截图

![错误截图](https://user-images.githubusercontent.com/118676805/202910575-caf256d0-af83-44dd-8882-f450c7a82d04.png)

**Comment by Black1312** [comment]
![image](https://user-images.githubusercontent.com/64343218/202931969-5e44c4b0-a1a8-4735-bc16-bea674bb197b.png)

**Comment by MistEO** [comment]
> ![image](https://user-images.githubusercontent.com/64343218/202931969-5e44c4b0-a1a8-4735-bc16-bea674bb197b.png)
> 

不是这个问题好像，他说已经更新到 beta 了（我还没看日志

**Comment by MistEO** [comment]
更新开发版，然后替换下 adb，再不行用兼容模式
