### ISSUE TITLE
MAA在执行换班时有概率不会跳转去下一个工作间，导致第一个工作间换班两次，第二个工作间没有人

### ISSUE THREAD

**Issue by qing18233** [MaaAssistantArknights/MaaAssistantArknights#2833]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

MAA在执行换班时有概率不会跳转去下一个工作间，导致第一个工作间换班两次，第二个工作间没有人

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10051159/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/116533598/202935934-363ebf68-5018-4447-beae-5b2a4f575418.png)

### 还有别的吗？

蓝叠国际5

**Comment by Mo-Yuxi** [comment]
同遇到多次这个问题，cy。或者可否新增一个校验功能：使用自定义换班文件时，若在执行完毕一次完整的换班之后回到主界面时识别到基建按钮上的红色警告标志时再次执行一次当前时段的班次换班，亲测二次换班后基本上不会出现上述情况

**Comment by zpw476898033** [comment]
+1，制造站、贸易站都有这种情况出现。

**Comment by Suprelorry** [comment]
我也遇到过同样的问题，好几次了
