### ISSUE TITLE
战斗任务随机出错并跳过

### ISSUE THREAD

**Issue by YuiTH** [MaaAssistantArknights/MaaAssistantArknights#2835]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

刷理智任务随机出现
任务出错：Fight
或
游戏崩溃，重新启动
任务出错：Fight
有可能出现在战斗的结尾或中途

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10053433/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/22416062/202966205-4a90df90-e7b6-402c-ba6d-ef182f989400.png)
![image](https://user-images.githubusercontent.com/22416062/202966559-84245847-422f-4dae-811a-e7f057053ce7.png)

### 还有别的吗？

夜神模拟器，Windows11 22H2

**Comment by zzyyyl** [comment]
你的截图有时候会莫名其妙的黑屏，导致maa以为战斗已经结束。或许可以考虑换个模拟器

**Comment by ellaweeks** [comment]
我也是这个问题，之前不会出错的 更新maa后出错了

**Comment by Soulcrzkc** [comment]
同样问题，卡在关卡的主界面不点上次战斗，雷电模拟器

**Comment by ellaweeks** [comment]
> 同样问题，卡在关卡的主界面不点上次战斗，雷电模拟器

设置---触摸方式---选择ADB兼容模式就能解决了 或者换成MAA触摸 不要用默认的

**Comment by drunkenQCat** [comment]
> 你的截图有时候会莫名其妙的黑屏，导致maa以为战斗已经结束。或许可以考虑换个模拟器
> 
> 时不时出现的 `stdout size: 36230 , socket size: 0` 的 screencap，想必是截图出问题了：）

像我其实就是手机配置特别差，黑屏时间会很长，就会误判。
