### ISSUE TITLE
mac版本 可能存在内存溢出

### ISSUE THREAD

**Issue by EnmmmmOvO** [MaaAssistantArknights/MaaAssistantArknights#2836]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

挂机刷肉鸽大约30分钟左右，maa显示ScreencapFailed，网页无法打开，也无法截图，终端三次中有一次成功打开，但显示prompt_status:5: fork failed: resource temporarily unavailable，但从关闭maa后恢复正常。

P.S. 有的时候点link start直接卡住，必须强制退出才能关闭，有的时候没有。

ios_version: beta 13.1(22C5050e)
maa_version: [v4.7.0-beta.2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.7.0-beta.2)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10053382/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10053435/asst.bak.log)

### 截图

![IMG_0442](https://user-images.githubusercontent.com/77719492/202966309-bc4d4be4-ba9f-49eb-ba45-34245bbc22b7.jpeg)
![IMG_0441](https://user-images.githubusercontent.com/77719492/202966322-9be11dd9-0e1c-4e6f-b495-a10cdc52b1d3.jpeg)

**Comment by MistEO** [comment]
设置里有个禁用 gzip 的选项，试试看

**Comment by EnmmmmOvO** [comment]
> 设置里有个禁用 gzip 的选项，试试看

这个吗，我一这么有勾选过诶
<img width="934" alt="Screenshot 2022-11-21 at 17 08 26" src="https://user-images.githubusercontent.com/77719492/202977577-3c4e30cb-4668-4cea-b75a-6eaf3fe4b3ac.png">

**Comment by MistEO** [comment]
@hguandl 那等佬来瞅瞅（
