### ISSUE TITLE
maa开发版v4.7.0 beta2版本在无线adb手机进行槐影肉鸽时无法招募

### ISSUE THREAD

**Issue by luchi0032** [MaaAssistantArknights/MaaAssistantArknights#2838]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

无线adb链接手机，用maa进行槐影肉鸽时卡在开局选人，无法招募干员 后自行退出重新进入肉鸽重复

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10054227/asst.log)
在2011年11月21日下午2点半之后反复实验出现

**Comment by MistEO** [comment]
v4.7.0-rc.1 加了个兼容模式，试试看
