### ISSUE TITLE
进入刷理智模式战斗界面右上角倍速切换一直在一倍和二倍之间切换有时还会暂停，此外基建会客室无法收集线索

### ISSUE THREAD

**Issue by tomatomelon** [MaaAssistantArknights/MaaAssistantArknights#284]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8241248/asst.log)

![image](https://user-images.githubusercontent.com/101536240/158093625-018e0f3e-1b98-4770-8235-1ed5e0c34251.png)

**Comment by MistEO** [comment]
你电脑实在太卡了 orz

先尝试吧 `resource/tasks.json` 中 `StartButton2` - `rearDelay` 改到 `60000` 试一下

![image](https://user-images.githubusercontent.com/18511905/158140776-15c00864-2126-42b1-a556-aaff825930d0.png)

**Comment by MistEO** [comment]
v3.0.7 fixed

**Comment by MistEO** [comment]
v3.0.9 fixed
