### ISSUE TITLE
自动从开发版退回稳定版，之后除了启动模拟器之外的任务都没有反应

### ISSUE THREAD

**Issue by Kingzom** [MaaAssistantArknights/MaaAssistantArknights#2840]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

刚刚启动MAA以后发现所有设置都初始化了（包括模拟器位置等），版本回到了稳定版
重新设置以后，点start模拟器会自动启动并打开软件，到点击开始的界面就没反应了（之前所有功能都正常）
再之后我手动点进游戏主界面模拟器显示startup成功，但之后的功能全部都没有反应（在主界面不动）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10055554/asst.log)

**Comment by Kingzom** [comment]
刚看到关于mumu模拟器的支持的描述，估计就是那个问题
换了夜神模拟器好像就没问题了
为什么设置会初始化确实没啥头绪

**Comment by ntgmc** [comment]
maa设置保存在【运行目录\gui.json】中，若更换版本/重装可保留该文件并移动至新文件夹
