### ISSUE TITLE
MAA的StartUp任务有时会启动失败

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#2841]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如题，有时游戏会启动失败，原因未知。考虑StartUp对于游戏启动完成的判断再严格一些，并尝试重新启动？

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10056774/asst.zip)

11月21日17点整

### 截图

![image](https://user-images.githubusercontent.com/30530115/203063071-492556cc-548d-4f2a-990f-dc7822cb4fc1.png)

### 还有别的吗？

（debug/roguelike文件夹下图片）
![2022-11-21_17-06-03 013_raw](https://user-images.githubusercontent.com/30530115/203064850-aaef30f5-44e6-46a4-9bf8-1fefe77a894b.png)

**Comment by Minepig** [comment]
注：已经强制替换过adb

**Comment by HowcanoeWang** [comment]
附带一个类似的startup问题，用的是Android studio的模拟器，模拟器启动路径为一个bat脚本文件

```bat
C: && cd C:\Users\hwang\AppData\Local\Android\Sdk\emulator && emulator -avd ark_hdpi
```

有时候手动关闭模拟器后，它的定时任务无法自动启动模拟器

![%~08E`@W1`YJO23FTW1`9B1](https://user-images.githubusercontent.com/19968935/203211271-c99562f0-80f7-49ec-9e15-f660a29ca59c.png)

但是在这种情况下，手动点击 link start，脚本可以被成功调用并启动成功
