### ISSUE TITLE
第十章刷理智不会自动选择磨难难度

### ISSUE THREAD

**Issue by mooline123** [MaaAssistantArknights/MaaAssistantArknights#2846]
### 说说你遇到的问题？

如题，大多数人第十章只有磨难有代理作战，但maa不会去选择，希望能改进下。

**Comment by MistEO** [comment]
@ABA2396 要不要整个磨难的导航？

**Comment by ABA2396** [comment]
> @ABA2396 要不要整个磨难的导航？

切换难度的task写好了，怎么用还是看+什么时候合进去吧，调用的话只要在章节导航后面加上"+Hard"或者"+Normal"就行了

**Comment by ABA2396** [comment]
现在dev已经支持了，例如要进H10-1的磨难难度，就输入H10-1-Hard或者H10-1Hard，标准就是H10-1-Normal或者H10-1Normal
