### ISSUE TITLE
肉鸽中 安塞尔 和 山 的技能识别问题猜测

### ISSUE THREAD

**Issue by TeacherTan** [MaaAssistantArknights/MaaAssistantArknights#2847]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

出现环境：**傀影肉鸽：关卡-大盗当头**
在放下**安塞尔**和**山**并开启山的二技能后，会频繁触发安塞尔的技能使用界面
这里怀疑是将山头上的技能按钮识别成了安塞尔的技能按钮，触发了**释放安塞尔技能**的指令

### 日志文件

[Uploading asst.log…]()

### 截图

![MuMu20221122150242](https://user-images.githubusercontent.com/74801008/203248140-30a862ac-d57f-41f0-8985-918406d21fdb.png)
![MuMu20221122150245](https://user-images.githubusercontent.com/74801008/203248145-5d70afcf-381a-4337-b6b8-58e587d4aef7.png)

### 还有别的吗？

模拟器：MUMU模拟器

**Comment by TeacherTan** [comment]
> ### 在提问之前...
> * [x]  我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
> * [x]  我在提问题之前至少花费了 5 分钟来思考和准备
> * [x]  我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
> * [x]  我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
> * [x]  我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图
> 
> ### 问题描述
> 出现环境：**傀影肉鸽：关卡-大盗当头** 在放下**安塞尔**和**山**并开启山的二技能后，会频繁触发安塞尔的技能使用界面 这里怀疑是将山头上的技能按钮识别成了安塞尔的技能按钮，触发了**释放安塞尔技能**的指令
> 
> ### 日志文件
> 
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10064804/asst.log)

> 
> ### 截图
> ![MuMu20221122150242](https://user-images.githubusercontent.com/74801008/203248140-30a862ac-d57f-41f0-8985-918406d21fdb.png) ![MuMu20221122150245](https://user-images.githubusercontent.com/74801008/203248145-5d70afcf-381a-4337-b6b8-58e587d4aef7.png)
> 
> ### 还有别的吗？
> 模拟器：MUMU模拟器

**Comment by cenfusheng** [comment]
是的，你猜对了。但暂时不知道怎么解决，待修

**Comment by MistEO** [comment]
fixed
