### ISSUE TITLE
macOS Ventura 点击“Link Start"后程序无法响应

### ISSUE THREAD

**Issue by allwh1tesay** [MaaAssistantArknights/MaaAssistantArknights#2851]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

此问题并非永远存在，但是在一定条件下（还没找到理由），当你点击"Link Start!"按钮时，程序会无法响应。
试图解决的方法：
1. 重启 --- 没解决
2. 关机重启 --- 没解决
3. 重装MAA --- 没解决

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10068134/asst.log)

### 截图

<img width="903" alt="截屏2022-11-22 22 16 14" src="https://user-images.githubusercontent.com/111232183/203336624-07735f13-b813-4130-b99c-7a4928c843cd.png">

<img width="166" alt="截屏2022-11-22 22 13 23" src="https://user-images.githubusercontent.com/111232183/203336459-ffc97220-41ca-4d26-9367-3876916f5884.png">

### 还有别的吗？

模拟器：Android Studio Dolphin 2021.3.1 Patch 1 M1 
操作系统：macOS Ventura 13.0 非Beta
配置：Mac Studio M1 Max (意思：性能绝对够）

**Comment by Sherlote** [comment]
我也是同樣的問題有2種情況第一種在ADB地址為127.0.0.1:5555無響應ADB地址為127.0.0.1:5557正常,第二種在ADB地址為127.0.0.1:5555正常ADB地址為127.0.0.1:5557無響應.目前4.613版本正常單開與雙開使用2種地址都是能啟用的.從4.70 alpha.2到4.70正式版都有這個問題
我的Mac配置與樓上一樣!

**Comment by MistEO** [comment]
v4.7.1 fixed
