### ISSUE TITLE
关于蓝叠模拟器中多开后无法识别的问题

### ISSUE THREAD

**Issue by auroralwy** [MaaAssistantArknights/MaaAssistantArknights#286]
多开后，无法识别多开出来的新的模拟器内的方舟。
母程序是可以识别的。
单个开启新的多开就无法识别。
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8245131/asst.log)
。尝试成功过一次，不过很诡异，开着两个窗口（一个大号在最早的窗口，一个小号是多开建的，然后识别到了小号）

**Comment by MistEO** [comment]
现在的版本是不支持多开的，如果需要的话请把助手的整个文件夹复制多份，全都使用自定义连接。

4.0 版本已经支持了，正在开发中~

**Comment by zzyyyl** [comment]
> 现在的版本是不支持多开的，如果需要的话请把助手的整个文件夹复制多份，全都使用自定义连接。
> 
> 4.0 版本已经支持了，正在开发中~

现在支持了吗（？

**Comment by xiaoyv404** [comment]
同问，现在支持了吗

**Comment by auroralwy** [comment]
> 
我用的还是自定义连接，具体就是查找下adb的地址，然后复制两份meo，把地址分别填上去，至于4.0自动多开我也没找着

**Comment by ABA2396** [comment]
> > 
> 
> 我用的还是自定义连接，具体就是查找下adb的地址，然后复制两份meo，把地址分别填上去，至于4.0自动多开我也没找着

4.3也没支持，是新ui支持，现在还是只能复制多分然后自定义连接
