### ISSUE TITLE
信用商店误触进入干员详细简历

### ISSUE THREAD

**Issue by fantasticFJM** [MaaAssistantArknights/MaaAssistantArknights#2862]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

信用商店误触进入干员详细简历

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10072199/asst.log)

### 截图

![MuMu20221123090603](https://user-images.githubusercontent.com/107972977/203451373-c9927249-9a37-411f-8914-220733749807.png)
![MuMu20221123090600](https://user-images.githubusercontent.com/107972977/203451414-fd1c2ec4-4e6b-4f10-bedb-bc4e4b0540d3.png)

### 还有别的吗？

MuMu模拟器2.7.8.0

**Comment by MistEO** [comment]
这个没做识别，自己买一下吧，新入坑的几周应该也就买完了
