### ISSUE TITLE
Python 接口有没有可以更新Maa的？

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaAssistantArknights#2864]
### 说说你遇到的问题？

如果用python 完全不打开maa的话，是不是就不会自动更新了？

### 有什么好的想法？

这样的话开放一个接口自动更新版本会不会好一点，或者已经有接口了？？

**Comment by MistEO** [comment]
不太好更新，如果我 api 变了，你集成代码没变，那不是炸了

**Comment by Shawnsdaddy** [comment]
> 不太好更新，如果我 api 变了，你集成代码没变，那不是炸了
> 
> 不同于 wpf 这边都是同步更新的，py 接口要依赖调用者也跟着变的

接口经常变动嘛，我以为design 都 finalize 了

**Comment by MistEO** [comment]
无论如何作为接口是不应该提供自动升级功能的，比如 python 3.8 咋地也不应该帮你升级到 python 3.11。design 就算短期内没变化，以后万一有点啥变化不还是炸了

**Comment by MistEO** [comment]
而且既然是 python，需要的话自己写一个应该挺简单的

**Comment by Shawnsdaddy** [comment]
python 接口运行良好 支持多开 MAA 太强了
