### ISSUE TITLE
基建换班中菲亚梅塔出现问题

### ISSUE THREAD

**Issue by Nora331** [MaaAssistantArknights/MaaAssistantArknights#2865]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

基建换班时菲亚梅塔经常出现问题，软件内提示表现为选择要与菲亚梅塔交换心情的干员后提示“干员冲突”，然后退出基建后重进并跳过菲亚梅塔环节
我已确认未点选“不将已进驻的干员放入宿舍”选项，且按照协议检查过自定义换班文件未发现问题
[换班脚本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10072480/default.zip)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10072433/asst.log)
8点自动运行换班时交换体力未成功，后9点半手动点击开始，依旧未成功

### 还有别的吗？

蓝叠模拟器国际版

**Comment by MistEO** [comment]
啥现象？如果只是先选了一个人而没有选菲娅梅塔，是正常的，紧接着就会再进一次宿舍把两个人都选上。这是考虑到如果肥鸭一开始就在二号位，选完仍在二号位的情况下，她的技能是不生效的，所以会强制把她先从宿舍里扔下来

**Comment by Nora331** [comment]
> 
我的菲亚梅塔设置是在换班前使用，在弹出报错之后直接跳过菲亚这一步进行后续换班了，没有你说的把两人都选上这一步
按顺序来说就是交换体力的干员入驻宿舍→报错并退出基建→重进基建→不让菲亚入驻而直接进行下一步换班

**Comment by tio-plato** [comment]
> 啥现象？如果只是先选了一个人而没有选菲娅梅塔，是正常的，紧接着就会再进一次宿舍把两个人都选上。这是考虑到如果肥鸭一开始就在二号位，选完仍在二号位的情况下，她的技能是不生效的，所以会强制把她先从宿舍里扔下来

同样问题，我也遇到了
正常情况下是按照你说的流程，但是有时候第一次只选一个人退出后，并不会再进宿舍把两个人都选上，而是直接跳过进行后面的步骤了。但是gui log 里面显示一切正常
![image](https://user-images.githubusercontent.com/60922756/206873530-33b2592c-a7d0-463f-992c-860fd84f66cb.png)

**Comment by MistEO** [comment]
> > 啥现象？如果只是先选了一个人而没有选菲娅梅塔，是正常的，紧接着就会再进一次宿舍把两个人都选上。这是考虑到如果肥鸭一开始就在二号位，选完仍在二号位的情况下，她的技能是不生效的，所以会强制把她先从宿舍里扔下来
> 
> 同样问题，我也遇到了
> 正常情况下是按照你说的流程，但是有时候第一次只选一个人退出后，并不会再进宿舍把两个人都选上，而是直接跳过进行后面的步骤了。但是gui log 里面显示一切正常
> ![image](https://user-images.githubusercontent.com/60922756/206873530-33b2592c-a7d0-463f-992c-860fd84f66cb.png)
> 

日志也发下

**Comment by tio-plato** [comment]
> > > 啥现象？如果只是先选了一个人而没有选菲娅梅塔，是正常的，紧接着就会再进一次宿舍把两个人都选上。这是考虑到如果肥鸭一开始就在二号位，选完仍在二号位的情况下，她的技能是不生效的，所以会强制把她先从宿舍里扔下来
> > 
> > 
> > 同样问题，我也遇到了
> > 正常情况下是按照你说的流程，但是有时候第一次只选一个人退出后，并不会再进宿舍把两个人都选上，而是直接跳过进行后面的步骤了。但是gui log 里面显示一切正常
> > ![image](https://user-images.githubusercontent.com/60922756/206873530-33b2592c-a7d0-463f-992c-860fd84f66cb.png)
> 
> 日志也发下

版本是  v4.8.0-beta.2.50.gec561e6a
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10201768/asst.log)
