### ISSUE TITLE
【抄作业】当“使用技能”脚本触发后，技能用法“好了就用”失效

### ISSUE THREAD

**Issue by tangge233** [MaaAssistantArknights/MaaAssistantArknights#2866]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

当“使用技能”脚本触发后，技能用法“好了就用”失效

此问题不具有偶然性，多次测试皆出现此问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10072894/asst.log)

### 截图

干员技能情况：
![image](https://user-images.githubusercontent.com/50769997/203472183-ba39eec3-b39a-4f5b-b802-dfee76990060.png)
![image](https://user-images.githubusercontent.com/50769997/203472185-f22afaff-55da-4772-840b-a05fff38081e.png)

脚本触发前：
![Screenshot_20221123-125827](https://user-images.githubusercontent.com/50769997/203472229-a8c60c75-34f1-4c49-9f2b-26339397ad9d.png)
脚本触发后：
![Screenshot_20221123-125842](https://user-images.githubusercontent.com/50769997/203472245-bb94eea2-66f0-45cc-b983-339e36c00ed0.png)
干员技能在脚本开启其他干员技能后不自动开启：
![Screenshot_20221123-125852](https://user-images.githubusercontent.com/50769997/203472438-e0731114-9d51-4a33-b038-f0a5c7d84421.png)
![Screenshot_20221123-125903](https://user-images.githubusercontent.com/50769997/203472443-701e4dcf-0df5-45fd-8555-36dbd86e1607.png)

### 还有别的吗？

模拟器：逍遥安卓
操作系统：Windows 11 22H2
使用作业：maa://11335

**Comment by WolfCanglong** [comment]
切换2倍速后面要再加一条开始挂机动作吧

**Comment by ntgmc** [comment]
在全部任务执行完毕后，如果无“开始挂机”动作，则maa结束运行（可以理解成不管了），如果存在“开始挂机”动作，则maa将会继续判断技能【好了就开/只开一次】并在关卡结束（无论成功与否）后自动结束运行。
该问题为作业制作问题，非maa问题，感谢反馈。
