### ISSUE TITLE
代理作战失误时，希望可以默认设置结束作战or以二星评价结算

### ISSUE THREAD

**Issue by LouiseLYF** [MaaAssistantArknights/MaaAssistantArknights#2868]
### 说说你遇到的问题？

代理作战有时候不稳，会漏怪，作战结果只有二星，二星的材料掉率比三星差一大截，还不如消耗一理智直接放弃作战。希望可以增加一个设置，刷理智出现二星结果时，默认消耗一理智放弃作战，还是以二星评价结算

**Comment by MistEO** [comment]
就是放弃作战的呀
