### ISSUE TITLE
蓝叠国际版闪退问题

### ISSUE THREAD

**Issue by PianCat** [MaaAssistantArknights/MaaAssistantArknights#287]
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

蓝叠5国际版
![Snipaste_2022-03-15_17-46-09](https://user-images.githubusercontent.com/50688679/158350948-b1cf21f6-9fb4-4863-b7ee-64a93052a7b2.png)

Log：
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8251980/asst.log)

Thanks♪(･ω･)ﾉ

**Comment by PianCat** [comment]
遇到好几次了，之前是芯片本偶尔会出现，这次是只要掉落没有凝胶就会出现（应该是有识别到不在库里面的内容导致的错误导致的闪退）

**Comment by MistEO** [comment]
更新下 3.0.7 试试

**Comment by MistEO** [comment]
v3.0.8 fixed
