### ISSUE TITLE
更新到4.7.0所有功能无法使用，已强制替换adb但还是没有反应，使用兼容触控模式也是同样出错

### ISSUE THREAD

**Issue by Notofnice** [MaaAssistantArknights/MaaAssistantArknights#2870]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

更新说明中"若更新后可以连接，但完全没反应，请进入 设置 - 连接设置 - 强制替换 ADB"
现在点LinkStart确实完全没反应，已经点过强制替换adb，但是也没有提示，不知道是否生效，而点击兼容触控模式也是直接报错，所有功能都无法使用

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10075409/asst.log)

### 还有别的吗？

maa版本: 4.7.0稳定版 和 4.7.0-rc.1测试版都测试过
模拟器: 夜神模拟器9.0.0.0

**Comment by ntgmc** [comment]
> 而点击兼容触控模式也是直接报错，所有功能都无法使用

请问报错什么呢？能否截图出来？

**Comment by Notofnice** [comment]
模拟器画面一直没反应,没变化过
那我重新补个asst.log吧
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10075615/asst.log)

这是没点兼容触控模式的图↓
![image](https://user-images.githubusercontent.com/63146701/203550817-6b6ce07c-4f19-4204-a974-ba3335462ffa.png)
这是点了兼容的图(中间那一段Infrast要等一段时间我点停止了,一样没有反应)↓
![image](https://user-images.githubusercontent.com/63146701/203551317-69e73a6e-8386-435c-9926-324b325eda08.png)

**Comment by ABA2396** [comment]
试试看根据 [1.2-常见问题.md](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md) 里面的 `自定义连接` 下载的 adb 试试

**Comment by ABA2396** [comment]
maa目录下也有个adb.zip，解压之后adb路径选择解压出的那个看看能不能用

**Comment by MistEO** [comment]
截图图全是黑的，和触控没关系，没搞懂为啥。重启试试，或者换个模拟器。

（看日志发现夜神 9 连 netcat 都不支持，和本次 bug 无关，但这个很影响截图速度）

**Comment by Notofnice** [comment]
群里公告的方法尝试过，下载的adb、MAA目录里的adb替换过去和重启电脑也都试过了，还是没能解决
更新到4.7.1又试了一遍也是一样的问题
(应该就剩换模拟器没试过了，那我还是换个模拟器吧)

**Comment by Notofnice** [comment]
换了群里的蓝叠国际版了，MAA4.7.1稳定版和4.6.13测试版都能用
测试了一下我这夜神9版本9.0.0.0的，MAA4.7.1稳定版不能用，4.6.13测试版能用
（可能就是大佬说的截图黑屏的原因吧，毕竟adb显示是已经连上了的，后续任务出错应该是截图出问题了）

**Comment by Moecg** [comment]
> 换了群里的蓝叠国际版了，MAA4.7.1稳定版和4.6.13测试版都能用
> 测试了一下我这夜神9版本9.0.0.0的，MAA4.7.1稳定版不能用，4.6.13测试版能用
> （可能就是大佬说的截图黑屏的原因吧，毕竟adb显示是已经连上了的，后续任务出错应该是截图出问题了）

+1,遇到同样的问题

**Comment by Moecg** [comment]
> +1,遇到同样的问题
之前用的果壳2021年6月17日的绿色9.0.0.0绿色版，换别的模拟器里
