### ISSUE TITLE
2022/11/23 国服 基建换班 干员识别 夜神模拟器

### ISSUE THREAD

**Issue by mkmdota** [MaaAssistantArknights/MaaAssistantArknights#2872]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我的模拟器是夜神模拟器安卓9 64bit
主要是两个问题：干员见行者没有识别，及其引发无人上班
基建排版是三班倒，16小时的陈+伺夜，4小时陈+见行者，4小时见行者+伺夜。其中凡是涉及见行者的时候，会**发生找不到见行者**。第一轮会_选中班次中另一个干员（比如陈或者伺夜）_。然后再反复3次单独找见行者，未遂。个人观察下来大概是第一次找的时候没找到见行者，找到表底，后面几次并没有准确从底回到头，是从干员表中段往后找。最后确认时却会出现**一个人都没选中**的情况。

其它功能使用OK很流畅很顺利！感谢大佬们不间断的付出！

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10076384/asst.log)
11-23 21:15:46 开始寻找见行者和伺夜
11-23 21:17:40 开始寻找见行者
11-23 21:18:51 开始寻找见行者
11-23 21:20:03 开始寻找见行者
最终结果是会客室无人上班

### 还有别的吗？

windows 10 系统
夜神模拟器9 64bit
模拟器设置为1600*900  2核3072MB内存 平板版

**Comment by MistEO** [comment]
你输入基建配置是 `先行者`

```log
[2022-11-23 21:15:46.020][TRC][Px5804][Tx24c4] Assistant::task_callback | SubTaskExtraInfo {"taskchain":"Infrast","details":{"facility":"Reception","candidates":[],"index":0,"names":["先行者","伺夜"]},"taskid":2,"what":"CustomInfrastRoomOperators","class":"asst::InfrastReceptionTask","subtask":"InfrastReceptionTask","uuid":"b588d27ba686efbe"}
```

**Comment by ntgmc** [comment]
漂亮o(￣▽￣)d

**Comment by mkmdota** [comment]
> 你输入基建配置是 `先行者`
> 
> ```
> [2022-11-23 21:15:46.020][TRC][Px5804][Tx24c4] Assistant::task_callback | SubTaskExtraInfo {"taskchain":"Infrast","details":{"facility":"Reception","candidates":[],"index":0,"names":["先行者","伺夜"]},"taskid":2,"what":"CustomInfrastRoomOperators","class":"asst::InfrastReceptionTask","subtask":"InfrastReceptionTask","uuid":"b588d27ba686efbe"}
> ```

排班用生成器做的，我刚刚去看了一下是不止先行者，id是1669049757077059。
图形化界面里的日志确实它是先找了见行者和另一个干员，然后再找了3次见行者。
以及这个也没解决见行者没识别出来呀。

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/203578224-1b545250-0b27-45bd-bd3b-59fa8a2573db.png)

没理解你的意思，名字不对肯定识别不出来啊

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/203578494-5a1125b9-925a-4457-bf1b-09b2a01839a6.png)

**Comment by mkmdota** [comment]
> ![image](https://user-images.githubusercontent.com/18511905/203578224-1b545250-0b27-45bd-bd3b-59fa8a2573db.png)
> 
> 没理解你的意思，名字不对肯定识别不出来啊

坏了！有笨比。。。issue能删不= =抱歉打扰大佬了。。。。。。
