### ISSUE TITLE
繁中服无法开始唤醒 

### ISSUE THREAD

**Issue by Asgart0916** [MaaAssistantArknights/MaaAssistantArknights#2877]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

可以从载入页面进到"开始唤醒"页面
(若有弹出登入视窗也会卡死)
但进入该页面后却无反应

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10097643/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/53762709/204121718-5a081991-ed83-4813-99c4-81c31cab6ce9.png)
![Screenshot_2022 11 27_14 06 59 461](https://user-images.githubusercontent.com/53762709/204121722-50469c26-c1c6-4b22-a394-0c2b3ddc23eb.png)

### 还有别的吗？

作业系统: Windows 11
模拟器: BS 5.9.410.1001 N32

**Comment by B-2U** [comment]
想請問這個bug如果想幫忙的話應該從何下手? 國服好像沒有類似的登入頁面，因此無法單純的添加適配截圖來解決

**Comment by MistEO** [comment]
> 想請問這個bug如果想幫忙的話應該從何下手? 國服好像沒有類似的登入頁面，因此無法單純的添加適配截圖來解決

tasks 的 next 有点像个链表的感觉，从中间掰开，把流程补上去，然后接上某个和国服一样的 task 就行了

**Comment by liuyifan-eric** [comment]
> 想請問這個bug如果想幫忙的話應該從何下手? 國服好像沒有類似的登入頁面，因此無法單純的添加適配截圖來解決

登入界面是什么样的？每次都要重新登入吗？不用重新登入的界面是什么样的

**Comment by B-2U** [comment]
登入介面
![Screenshot_2023 03 12_01 42 20 711](https://user-images.githubusercontent.com/82710122/224503674-78d48941-86da-4304-bebc-03d5691ffd47.png)
不用重新登入的界面
![Screenshot_2023 03 12_01 44 37 312](https://user-images.githubusercontent.com/82710122/224503680-154bf07c-db58-4484-bead-fc9178d0da1e.png)

**Comment by B-2U** [comment]
在簡單閱讀過任務流程協定doc之後
我嘗試在繁中服的task json中直接添加
```
"GameStart": {
		"algorithm": "OcrDetect", 
        "action": "ClickSelf",
        "text": [ "Google Play" ]
    }
```
但不清楚 MAA的開始喚醒到底對應的是哪個task名

**Comment by liuyifan-eric** [comment]
> 登入介面
> 
> ![Screenshot_2023 03 12_01 42 20 711](https://user-images.githubusercontent.com/82710122/224503674-78d48941-86da-4304-bebc-03d5691ffd47.png)
> 
> 不用重新登入的界面
> 
> ![Screenshot_2023 03 12_01 44 37 312](https://user-images.githubusercontent.com/82710122/224503680-154bf07c-db58-4484-bead-fc9178d0da1e.png)
> 
> 

那应该把第二张图截图放进template里就好了吧

**Comment by B-2U** [comment]
剛剛測試了 目前的MAA是可以成功點擊第二章圖中的`開始喚醒的`
我看了一下asstlog, 應該是直接用了國服的template
```match_templ | StartToWakeUp.png score: 0.844329 rect: [ 538, 480, 202, 65 ] roi: [ 520, 460, 240, 100 ]```

但這個issue想改善的是目前無法處理第一張截圖的登入選擇

**Comment by liuyifan-eric** [comment]
第一种情况无论如何都要手动处理吧？输入密码/跳转确认等等
为什么会有这种需求？不是会保留登入信息吗

**Comment by B-2U** [comment]
使用google play登入的話 平時是會保留登入信息的
但如果在其他裝置登入遊戲(例如手機) 這個裝置就會需要點擊重新登入，但不需要重新認證，單純點擊sign in 就會跳轉到第二截圖了

**Comment by liuyifan-eric** [comment]
这个应该不好处理吧？也有人fb登入，而且即便是google的话如果有多个账号也会需要手动选择。其他伺服器（包括yostar的三个）都不存在这样的问题，应该不会为此专门设计gui。而且我个人觉得登入环节比较敏感，即便只是sign in确认也不应该交由maa处理

**Comment by B-2U** [comment]
確實如果要做好配套的話就也得做一個登入選擇的GUI
目前最簡單粗暴的解法就是加綁FB, 然後用FB登入
