### ISSUE TITLE
copilot是不是还不支持选助战？

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaAssistantArknights#2878]
### 说说你遇到的问题？

如果能助战的话，就能每天自动完成一次助战任务了

可以先支持个任意助战填充刷个1-7

**Comment by ntgmc** [comment]
> copilot是不是还不支持选助战？

是的


> 如果能助战的话，就能每天自动完成一次助战任务了

每日任务真的需要做这个吗……不是随便挂两下就溢出了吗

**Comment by Shawnsdaddy** [comment]
> > copilot是不是还不支持选助战？
> 
> 是的，不支持
> 
> > 如果能助战的话，就能每天自动完成一次助战任务了
> 
> 每日任务真的需要做这个吗……不是随便挂两下就溢出了吗

不是啊每天选一次助战会有信用奖励啊.20点信用

**Comment by ntgmc** [comment]
看玛丽做不做吧。（我是觉得没所谓，因为只有危机合约的时候有，而且120个才换个绿异铁感觉没啥用）

**Comment by Shawnsdaddy** [comment]
一个月600信用也能换挺多东西的 =。=

**Comment by ntgmc** [comment]
危机合约也不开一个月，就半个月，啊这QAQ

**Comment by Shawnsdaddy** [comment]
> 危机合约也不开一个月，就半个月，啊这QAQ

不只是危机合约啊，平常也有啊。。。危机合约一次30，是给别人的，你找别人助战是自己拿的
助战一次自己+20 别人+30

**Comment by Cherrling** [comment]
![image](https://user-images.githubusercontent.com/37233261/213052928-383be026-b805-47d8-941f-c5ee2d560ecb.png)
