### ISSUE TITLE
卡会客室

### ISSUE THREAD

**Issue by Sed66666** [MaaAssistantArknights/MaaAssistantArknights#2879]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在会客室线索交流结束后，会客室会卡在进去的好友访问情况弹窗，没有点返回，最后直接跳过了会客室

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10080413/asst.log)

2022/11/24 10:05:54 当前设施：Reception 0

**Comment by Sed66666** [comment]
![MuMu20221126002119](https://user-images.githubusercontent.com/46131793/204024459-42591b85-8123-46d4-ae31-02724b85e8c2.png)

**Comment by ntgmc** [comment]
看起来这个问题已经被修复了，最新版本 4.16.3 没有出现过这个 BUG。
