### ISSUE TITLE
基建小小的效率问题：贸易站德克萨斯拉普兰德永不上班

### ISSUE THREAD

**Issue by smiledrunk** [MaaAssistantArknights/MaaAssistantArknights#288]
应该是如果没有能天使就不会配这三人的套组，但这俩人配一个月见夜效率也是高于三个30%的

**Comment by smiledrunk** [comment]
没有能天使的博士表示很无奈

**Comment by MistEO** [comment]
如果出现你说的这种情况那是 bug, 发份日志我康康

**Comment by smiledrunk** [comment]
[](
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8255236/asst.log)
u

**Comment by smiledrunk** [comment]
唔。。今天更新了版本这份日志是更新之后的，咱再丢一个3.06的

**Comment by MistEO** [comment]
非常感谢反馈，这个 bug 应该存在很久了，会在之后的版本修复掉

**Comment by MistEO** [comment]
v3.0.8 fixed
