### ISSUE TITLE
肉鸽无法下干员，有拖拽动作但没有效果

### ISSUE THREAD

**Issue by dogther** [MaaAssistantArknights/MaaAssistantArknights#2881]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

傀影肉鸽，跑了一个小时都很正常，然后突然出现无法下干员的情况，打开触碰点显示，发现有拖拽干员的动作，但却没有下下去，然后直接一关漏完，之后重新开始探索仍然有同样问题。重启模拟器和方舟程序之后恢复正常

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10080802/asst.log)
12:19分之前的几把都是，第一关就漏完了

### 还有别的吗？

蓝叠模拟器国际版

**Comment by MistEO** [comment]
录个屏看看啥样的？

**Comment by dogther** [comment]
https://user-images.githubusercontent.com/33522087/203783638-d49f731f-8792-47f1-b2ea-bf0314f9b58a.mp4

因为只能传10M的文件，压缩了一下画质

**Comment by dogther** [comment]
补充一下，这几天试了好几次，都是从第三次探索开始出问题，不知道是巧合还是什么
<img width="162" alt="t11" src="https://user-images.githubusercontent.com/33522087/204087771-4e78603a-ebaa-42e8-ad43-41905df126da.PNG">

**Comment by MistEO** [comment]
新版本参数调整了下，试试有效果没

**Comment by dogther** [comment]
仍然出现了同样的问题
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10243327/asst.log)

**Comment by cenfusheng** [comment]
后续新版本又调整了新参数，现大部分用户可正常使用，如仍出现，可以自行在resource\tasks.json中增加BattleUseOper与BattleSwipeOper的四个延迟（delay）数值，（一般再加一半就够用了，实在不行加一倍）。
