### ISSUE TITLE
自定义基建换班不是定时自动执行的吗

### ISSUE THREAD

**Issue by KuiPer-LTW** [MaaAssistantArknights/MaaAssistantArknights#2883]
### 说说你遇到的问题？

还是说我铸币了？我认真找过，好像是没有这个功能吧，所以做排班表的时间只是让MAA区分换哪一班而已吗，我建议一步到位内置个时钟到点就换班，可以弹个窗，询问是立刻执行还是等5分钟或者10分钟

### 有什么好的想法？

想让MMA来换基建就是为了不要一直惦记着，可能看个视频打把肉鸽就错过时间了，还要定个闹钟去点击执行，这感觉不太好，当然现在把换基建的操作变成了一键已经很方便了只是说能不能再自动一点

**Comment by MistEO** [comment]
设置里有定时功能，结合着用

**Comment by KuiPer-LTW** [comment]
抱歉我铸币了，真不知道在哪设置

**Comment by KuiPer-LTW** [comment]
是去json文件里添加吗，我看示例里有个"duration": 360,        // 工作持续时长（分钟），保留字段，目前无作用。以后可能到时间了弹窗提醒该换班了，或者直接自动换了

**Comment by KuiPer-LTW** [comment]
> 设置里有定时功能，结合着用

抱歉我铸币了，真不知道在哪设置
是去json文件里添加吗，我看示例里有个：
"duration": 360, // 工作持续时长（分钟），保留字段，目前无作用。以后可能到时间了弹窗提醒该换班了，或者直接自动换了
是这个吗？自动生成的排班表里好像没有这段

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/203728237-379aeb03-3bd3-4782-8a51-3eb2f90f3a18.png)

**Comment by KuiPer-LTW** [comment]
> 

这个定时执行是执行的首页勾选的项目吗？而且只能整点执行

**Comment by MistEO** [comment]
是的

**Comment by KuiPer-LTW** [comment]
> 是的，和你在首页点开始是一样的效果

去研究了一下，感觉还是不太方便，我分析了一下原因，感觉应该把基建换班和基建收菜分开来，剩下的我开一篇新的说
