### ISSUE TITLE
自定义基建功能的逐步完善带来小问题

### ISSUE THREAD

**Issue by KuiPer-LTW** [MaaAssistantArknights/MaaAssistantArknights#2884]
### 说说你遇到的问题？

说真的其实是个富贵病，以前没自定义时根本不会考虑这种问题，因为以前我根本就不用基建换班功能（笑）

在首页的选项里，基建换班和基建收菜应该分开来
不然像我设置了两班倒，A组从前一天0点工作到下午4点的，早上起来就不能点基建换班了，不然菲亚梅塔就还没到时间就用了，如果收菜和换班分开来，清完日常之后我只要一键反选，就只有换班被选中了，然后到点了自动执行
说一下收菜的细节，除了点进去收菜收信赖以外，还应该把无人机也用了，一晚上能有一百多点吧，当然应该设置成选项用还是不用，用在贸易站还是制造站的第几号位（这都是自定义排班里有的功能，做到UI里应该不难吧），然后是宿舍，点进去换上心情未满的，然后在此基础上和自定义排版表里保持一致（要不要补满啊，谁必须在宿舍啊，只是为了换人回心情而已），又或者麻烦的话直接做个选项：补满+放入爱丽丝和车尔尼/不用补满（因为现在也就迷迭香组需要操作宿舍了），还有会客室，应该点进去接收线索开始分析（为了去信用商店购物）

### 有什么好的想法？

说了好多废话其实是为了说明我确实是有这样的需求，不是在开玩笑，简单总结一下就是：
是否区分基建收菜和换班：是/否
——是：设施进驻干员将单独在基建换班选项中调整（收菜+情报收集+无人机使用+宿舍换人）
①是否使用无人机：是/否 ——是：无人机使用位置：贸易站/制造站 1 2 3 4 5
②是否补满宿舍：是（补满+放入爱丽丝和车尔尼）/否

这样最终的效果就是当通知我完成后我只需要一键反选，等着定时执行基建换班就OK了

### 其他内容

一点小小的建议，只做讨论，辛苦，感谢你们

**Comment by KuiPer-LTW** [comment]
补充一下，定时不能升级一下精确到分钟吗，哪怕是多分半小时也更好

**Comment by MistEO** [comment]
那你自定义作业里加一班，所有设施都是 skip 不就行了

**Comment by KuiPer-LTW** [comment]
> 那你自定义基建 json 里加一班，所有设施都是 skip 不就行了

偷鸡的方法要多少有多少，我只是想看看正面解决问题

**Comment by KuiPer-LTW** [comment]
> 那你自定义基建 json 里加一班，所有设施都是 skip 不就行了

偷鸡的方法要多少有多少，我只是想看看能不能正面解决问题

**Comment by KuiPer-LTW** [comment]
> 那你自定义基建 json 里加一班，所有设施都是 skip 不就行了

而且你这个办法我光想想就觉得头痛，用MMA就是图方便的，要是折磨自己那还不如不用自定义基建，就当它是个刷图脚本用好了

**Comment by Private233** [comment]
多写一个排班，所有设施都skip，完全可以做到你上述的所有需求。
只是多写一个排班方案，这还不轻松？都不用填写干员名字呢

**Comment by KuiPer-LTW** [comment]
> 多写一个排班，所有设施都skip，完全可以做到你上述的所有需求。 只是多写一个排班方案，这还不轻松？都不用填写干员名字呢

好吧
