### ISSUE TITLE
基建换班不换会客室，只换部分宿舍

### ISSUE THREAD

**Issue by XiaoYueQwQ** [MaaAssistantArknights/MaaAssistantArknights#2886]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

更新了4.7.1后出现的问题

基建换班的时候，跳过了会客室和底下两个宿舍
换完发电站，软件在那里楞了大约30秒，跳过了会客室打开了办公室
换了两个宿舍，直接任务已完成了
感觉宿舍是随机跳过的，毕竟之前只换了一个宿舍
但是会客室每次都跳过

已经确认勾选了所有基建都换

### 日志文件

19:45左右，
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10084300/asst.log)

**Comment by ntgmc** [comment]
看起来这个问题已经被修复了，最新版本 4.16.3 没有出现过这个 BUG。
