### ISSUE TITLE
下载需要用户验证怎么解决

### ISSUE THREAD

**Issue by jiuyunjing** [MaaAssistantArknights/MaaAssistantArknights#2887]
### 说说你遇到的问题？

从官网点好下载后，下了10%左右后显示：下载失败，当前请求需要用户验证

**Comment by ntgmc** [comment]
![image](https://user-images.githubusercontent.com/74061867/203787391-2b6999d4-cbcf-44c2-8c9b-44f3761b140e.png)

**Comment by horror-proton** [comment]
你是怎么下载的, 当前请求需要用户验证是浏览器提示的吗, 能截下图看看吗
