### ISSUE TITLE
卡在宿舍无法进行下一步

### ISSUE THREAD

**Issue by xyxyx718** [MaaAssistantArknights/MaaAssistantArknights#2891]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

卡在宿舍……详情见视频

https://user-images.githubusercontent.com/59339633/203854899-fe01e8ca-1adf-4dac-b963-6896937ece08.mp4

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10086989/asst.zip)
问题出现在11.25的早上3:30左右

### 截图

![Screenshot_2022 11 25_03 44 13 620](https://user-images.githubusercontent.com/59339633/203855668-806eb217-cd27-499f-b912-4615d1194527.png)

### 还有别的吗？

模拟器：蓝叠国际版Hyper-V版本（5.9.0.1061 N64）
操作系统：Win11 专业版 22H2（22623.891）
基建设置如图所示：
![Snipaste_2022-11-25_03-48-23](https://user-images.githubusercontent.com/59339633/203856025-d0178ddc-1186-4ab3-ae93-67bca941c28e.jpg)

**Comment by xyxyx718** [comment]
![Snipaste_2022-11-25_03-54-03](https://user-images.githubusercontent.com/59339633/203856556-8857dabe-1ca2-4ecf-96a5-2a8217ffb864.jpg)
好像筛选了这个选项，不知道怎么勾选上的

**Comment by ReolOwO** [comment]
是的，我繁中服也有这个问题，会卡在筛选画面上，这个是蹭信赖的一个bug，你把设置里面宿舍空余位置自动放干员蹭信赖关掉就可以了，后续等开发组修复

**Comment by MistEO** [comment]
繁中服的基建其实并没有支持。。

**Comment by MistEO** [comment]
> 是的，我繁中服也有这个问题，会卡在筛选画面上，这个是蹭信赖的一个bug，你把设置里面宿舍空余位置自动放干员蹭信赖关掉就可以了，后续等开发组修复

繁中服的基建其实并没有支持。。
