### ISSUE TITLE
公招次数设置为1，免费刷新次数的浪费问题。

### ISSUE THREAD

**Issue by shawnyuan-cn** [MaaAssistantArknights/MaaAssistantArknights#2892]
### 说说你遇到的问题？

每天多次启动时为保持公招券平衡，将公招次数设置为1，此时如果位置上连续出四星就不会刷新，浪费了免费的刷新次数。
希望能此时能打开其他位置保持用完刷新次数。

### 有什么好的想法？

希望能此时能打开其他位置保持用完刷新次数。

**Comment by cenfusheng** [comment]
把最大招募次数改为4、自动确认3星取消勾选、自动刷新3星tag勾选，也可以节省招募券，并且把刷新次数用完（虽然一个三星都不招的话券会溢出，可以定期打勾嘛，三星什么时候招募都一样）
感谢你的建议，目前没有计划，您可以通过上述方法勉强解决。
