### ISSUE TITLE
水月肉鸽频繁放弃

### ISSUE THREAD

**Issue by Tobuyuki** [MaaAssistantArknights/MaaAssistantArknights#2895]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

使用水月肉鸽刷等级选项,经常在遇到不期而遇节点时在选项界面卡住,大约20秒左右会退出放弃.
被迫切换刷源石锭选项,但也有在第一层没到商店节点时碰到不期而遇节点然后退出的情况.
软件版本4.7.1

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10090262/asst.zip)

### 还有别的吗？

模拟器:夜神安卓9
OS:win10 22H2

**Comment by MistEO** [comment]
debug/roguelike 下有图，一起打包发下看看

**Comment by Tobuyuki** [comment]
[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10095628/roguelike.zip)
![image](https://user-images.githubusercontent.com/118970157/204071301-7503cb22-1b98-4c48-8963-ce628f90f165.png)
顺便附了一张今天遇到的在第一层没到商店就退出的情况

**Comment by n12z** [comment]
我也遇到了  4.7.2水月肉鸽遇见不期而遇就不会选择任何选项，然后就超时放弃探索了
