### ISSUE TITLE
自定义基建排班换班时经常出错

### ISSUE THREAD

**Issue by bjvjhf** [MaaAssistantArknights/MaaAssistantArknights#2896]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

自定义基建换班经常出错：
1、例如排班表上制造站3应该是ABC，使用MMA的时候会变成制造站4里的EFG
2、宿舍经常放不满人
3、宿舍规定放入的干员最后会被挪出来，尤其是最后一个宿舍

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10091842/asst.log)

### 还有别的吗？

mumu模拟器

**Comment by MistEO** [comment]
你的日志被刷掉了，下次再出现的话不要重开 maa 然后再发下

**Comment by bjvjhf** [comment]
我用内置的模板改一下排班试试，看看这回会不会出问题，谢谢答复

**Comment by pboymt** [comment]
同样有问题，不停将一个干员在制造站和宿舍来回放……最后不放了，发现制造站全都只有俩人

**Comment by hastune39** [comment]
我也有类似的问题,就是maa排班有概率一个房间里放不满人,有时是制造站,有时是发电站或者办公室,比如贸易站只有巫恋一个人,制造站4全员没放人之类的
都是在我电脑上挂着的时候出现的情况,我自己看着它换班的时候,又不出问题了,很怪,猜测是后台的时候有时候点不到屏幕?(可能是我电脑太渣?
我的想法是,让maa换一个房间的时候,,换完不立即切换到下个房间,而是再点开一次房间里的人,确认是不是换好了,如果没换好,就回到第一步,换好了,就点退出,再切到下一个房间
用时应该不会太长, 可以做成一个按钮(房间干员确认),默认关闭,有需要的人打开这个按钮就好了
主要是有的时候maa犯蠢了,自己点取消,给它手动纠错一下,又要从头开始,要么就等maa全部任务结束了再手动纠正,能不能出个maa进程暂停的按钮

**Comment by zy214** [comment]
最新版本4.7.3下我的排班里能拉德三人组的能会在进驻制造站后被拉进休息室。之前版本不会
