### ISSUE TITLE
能否将信用商店随缘买做个区分？

### ISSUE THREAD

**Issue by inkhalo** [MaaAssistantArknights/MaaAssistantArknights#290]
将碳和家具零件分开，毕竟碳没用，家具还是要买的

**Comment by MistEO** [comment]
请参考 [详细介绍](https://github.com/MistEO/MeoAssistantArknights/blob/master/docs/%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md#%E4%BF%A1%E7%94%A8%E5%95%86%E5%BA%97%E9%9A%8F%E7%BC%98%E4%B9%B0)
