### ISSUE TITLE
希望增加命令行用户界面

### ISSUE THREAD

**Issue by yd278** [MaaAssistantArknights/MaaAssistantArknights#2900]
### 说说你遇到的问题？

电脑在桌上人在床上这种事情也会有的嘛

现在的方案是iPad远程桌面，但是延迟高画质低按钮还那么小

要是能ssh就太好啦！

### 有什么好的想法？

希望能实现如下需求

- 通过命令行新建mma实体并指定配置文件（考虑可能的多开）
- 链接上指定实体后实时输出log，并可执行打开/关闭模拟器，修改设置、开始/停止行动、断开链接后台执行、直接关闭该实体等操作
    - 开关模拟器如果需要管理员模式的话可以让用户自己手动开？（ 毕竟win下sudo不方便
- 仓库识别等可能导出大段json的情况把json保存在本地文件里

**Comment by MistEO** [comment]
有 python 接口的，可以试着自己写下，应该比较容易

**Comment by yd278** [comment]
好嘞找到了谢谢
