### ISSUE TITLE
在特殊情况下【借助战赚信用】功能无效

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#2903]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述
**情况1：编队错误**
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10095695/asst.log)
具体表现为maa执行完访问=>打开of-1界面=>开始行动=>快捷编队=>退出，执行商店购买

**情况2：借人错误**
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10095696/asst.log)
这个是编队只有一个山（2903）的时候，删了山 然后上了个推王 然后没打直接shopping了

**情况3：导航错误**
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10095714/asst.log)
导航进入已经结束的叙拉古人的界面

情况4：无好友助战时无法借助战（用户问题）

情况5：无解锁【火蓝之心】时maa卡住（用户问题）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10095695/asst.log)

**Comment by MistEO** [comment]
为啥没编上（

**Comment by ntgmc** [comment]
就是我先把编队清空 然后maa也不上人也不借

**Comment by ntgmc** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10095696/asst.log)
这个是编队只有一个山（2903）的时候，也是一样

**Comment by ntgmc** [comment]
他删了山 然后上了个推王 然后没打直接shopping了

> [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10095696/asst.log) 这个是编队只有一个山（2903）的时候，也是一样

**Comment by ntgmc** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10095714/asst.log)
也许是因为点太快了？点进去叙拉古人了
![image](https://user-images.githubusercontent.com/74061867/204073369-71412319-d526-4568-903f-18f4818f4089.png)

**Comment by ntgmc** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10095717/asst.log)
这次是编队上了个芬但是没借人然后直接shopping

**Comment by ntgmc** [comment]
> [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10095717/asst.log) 这次是编队上了个芬但是没借人然后直接shopping

好像是因为没有好友的助战造成的

**Comment by MistEO** [comment]
@Hydrogina

**Comment by Hydrogina** [comment]
今天遇到一次，在这个界面copilot模板匹配BattleStartRaid.png的时候score只有0.58442，导致无法开始作战
![BS_PIC_2022-12-01-11-17-58](https://user-images.githubusercontent.com/46482682/204958537-e1bfbc3c-212a-4b53-9704-e6e2321a7ddb.png)
BattleStartRaid.png
![BattleStartRaid](https://user-images.githubusercontent.com/46482682/204958800-0636ebba-f5a6-40ab-816e-ff1f37f320aa.png)


`[2022-12-01 11:07:42.414][TRC][Px265c][Tx42bc] asst::ProcessTask::_run | enter
[2022-12-01 11:07:42.414][INF][Px265c][Tx42bc] {"taskchain":"Copilot","details":{"to_be_recognized":["BattleStartNormal","BattleStartRaid","BattleStartExercise","BattleStartSimulation"],"cur_retry":20,"retry_times":20},"first":["BattleStartNormal","BattleStartRaid","BattleStartExercise","BattleStartSimulation"],"taskid":11,"class":"asst::ProcessTask","subtask":"ProcessTask","pre_task":""}
[2022-12-01 11:07:43.032][INF][Px265c][Tx42bc] Call ` H:\Program Files (x86)\BluestacksCN\Engine\ProgramFiles\.\HD-Adb.exe -s 127.0.0.1:5555 exec-out "screencap | nc -w 3 10.0.2.3 21814" ` ret 0 , cost 619 ms , stdout size: 0 , socket size: 3686412
[2022-12-01 11:07:43.051][TRC][Px265c][Tx42bc] match_templ | BattleStartRaid.png score: 0.58442 rect: [ 1039, 382, 132, 274 ] roi: [ 989, 318, 232, 374 ]
[2022-12-01 11:07:43.062][TRC][Px265c][Tx42bc] asst::ProcessTask::_run | leave, 648 ms`

**Comment by Hydrogina** [comment]
如果把tasks.json里"BattleStartRaid"任务的templThreshold改成0.5可能可以临时解决这个问题 @MistEO

**Comment by MistEO** [comment]
不应该这么低的，低于 0.6 基本就是完全不对了，说明压根不是这个画面。是不是动画还没播放完就识别了，或许可以加点延迟啥的

**Comment by MistEO** [comment]
应该不用加延迟，startbutton的next还是startbutton就行了

**Comment by MistEO** [comment]
fixed
