### ISSUE TITLE
能不能改一下更新检查的逻辑

### ISSUE THREAD

**Issue by 134820134820** [MaaAssistantArknights/MaaAssistantArknights#2904]
### 说说你遇到的问题？

我这情况有俩，一方面是不知道为啥，maa自带的更新，用不用aria现在下载速度都几乎为0，然后被迫来github找更新包，另一方面是因为多开maa，有好几个maa，平时为了稳定，一般统一更新，想要是能够把OTA的包复制进去，打开gui后能像原来一样自动识别更新，但发现它识别的包名和直接从github下载下来的不符，而且更坑的是，现在好像逻辑改了，必须要勾选了自动下载更新包，下载过，才会识别是否有可用的解压包？
导致我将OTA复制到每个文件夹后，必须打开gui，勾选自动下载，下载一次再取消，再打开一次gui，才能完成更新

### 有什么好的想法？

能否在检查过有新版本后，就会在文件夹中检查是否有可用的更新。
还有就是OTA包的更新机制能不能解释一下。
ps：其实是想试试能不能自己改的，但python用太久，c++都忘光了/_ \

### 其他内容

比如说这次我想更新，它下载的包名：MAAComponent-OTA-v4.6.13_v4.7.2-win-x64.zip
github上是不加当前版本号的。。。我也整不明白原理

**Comment by ABA2396** [comment]
GitHub的OTA是给老版本用的，新版本可以去MaaRelease仓库或者ota.maa.plus下载

**Comment by 134820134820** [comment]
> GitHub的OTA是给老版本用的，新版本可以去MaaRelease仓库或者ota.maa.plus下载

我就是老版本升级啊

**Comment by ABA2396** [comment]
> > GitHub的OTA是给老版本用的，新版本可以去MaaRelease仓库或者ota.maa.plus下载
> 
> 我就是老版本升级啊

464之后就是从MaaRelease下了，这个仓库里的OTA你也可以放进文件夹里直接自己解压覆盖。

**Comment by 134820134820** [comment]
> > > GitHub的OTA是给老版本用的，新版本可以去MaaRelease仓库或者ota.maa.plus下载
> > 
> > 
> > 我就是老版本升级啊
> 
> 4.6之后就是从MaaRelease下了，这个仓库里的OTA你也可以放进文件夹里直接自己解压覆盖。

能麻烦详细解释以下吗，maarelease在哪？咋下

**Comment by ABA2396** [comment]
> > > > GitHub的OTA是给老版本用的，新版本可以去MaaRelease仓库或者ota.maa.plus下载
> > > 
> > > 
> > > 我就是老版本升级啊
> > 
> > 
> > 4.6之后就是从MaaRelease下了，这个仓库里的OTA你也可以放进文件夹里直接自己解压覆盖。
> 
> 能麻烦详细解释以下吗，maarelease在哪？咋下

这个仓库是 MaaAssistantArknights/MaaAssistantArknights
你去 MaaAssistantArknights/MaaRelease 看看

**Comment by 134820134820** [comment]
> > > > > GitHub的OTA是给老版本用的，新版本可以去MaaRelease仓库或者ota.maa.plus下载
> > > > 
> > > > 
> > > > 我就是老版本升级啊
> > > 
> > > 
> > > 4.6之后就是从MaaRelease下了，这个仓库里的OTA你也可以放进文件夹里直接自己解压覆盖。
> > 
> > 
> > 能麻烦详细解释以下吗，maarelease在哪？咋下
> 
> 这个仓库是 MaaAssistantArknights/MaaAssistantArknights 你去 MaaAssistantArknights/MaaRelease 看看

![捕获](https://user-images.githubusercontent.com/79043872/204075799-f2031759-9be7-4568-babd-a43478ecfdd7.PNG)
似乎啥都没有？

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/204079549-d95c7cd0-a769-491e-a424-8ec890df0811.png)
![image](https://user-images.githubusercontent.com/99072975/204079560-d4d6b555-69f2-4918-b930-d9c983bc1072.png)

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/204079578-9ad5ed10-a9b0-4ba9-849a-40fa76463399.png)
