### ISSUE TITLE
运行任意功能时，需要花费20秒才能启动

### ISSUE THREAD

**Issue by LmeSzinc** [MaaAssistantArknights/MaaAssistantArknights#2907]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我正在使用 maa 4.7.2，连接蓝叠模拟器5国际版，点击运行后需要等待约20秒钟，maa才会开始运行。

查看日志发现是在这一步花费了20秒
```
[2022-11-27 00:15:47.404][INF][Px4ab8][Tx1c4e8] Try to find the fastest way to screencap
[2022-11-27 00:16:07.405][WRN][Px4ab8][Tx1c4e8] Wait handles: [process_info.hProcess, pipeov.hEvent, sockov.hEvent] timeout.
```

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10096610/asst.log)

**Comment by ABA2396** [comment]
今天我也遇到了，重启电脑之后就好了

**Comment by LmeSzinc** [comment]
找到复现方法和原因了，蓝叠5 5.10.0.1085 N64，安卓9（Pie）实例，只有安卓9实例能复现，蓝叠5的小版本号应该没有影响。

蓝叠安卓9 的 nc 命令似乎有点特别，`screencap | nc ...` 能发送截图，但是截图发送完之后命令不会结束，所以导致了 20s 的超时。`echo 1 | nc ...` 也是一样会接收超时。如果在开始运行的时候进行性能测试，刚好只有 `screencap | nc ...` 这种方式可用，就会出现 #3320 这种每步操作都需要等待到超时的问题。

改成了 `screencap | busybox nc ...` 就解决问题了。Alas目前是这样写的：
https://github.com/LmeSzinc/AzurLaneAutoScript/blob/ab293de103caccf488c6e2f8bdb28927b4bc8aa0/module/device/connection.py#L291-L326

然后是另一个问题的答案，为什么初始化性能测试的时候，只有 `screencap | nc ...` 可用呢？

如果模拟器桌面比较整洁，连广告都没有，在模拟器桌面启动MAA，此时MAA进行性能测试，`screencap -p` 和 `screencap | gzip ...` 都因为图片复杂度低压缩率高，MAA报错 `data is too small!`，认为该方式不可用，只剩下不压缩的 `screencap | nc ...` 过关了。

**Comment by xianguosoul** [comment]
根据你说的，我检查asst.log，确实看到了maa测试screencap -p并返回“data is too small”
但是，我尝试了把分辨率、dpi改为推荐的1280*720、320dpi，没用
再把模拟器桌面多放几个图标，也没用
那应该怎么解决呢？

**Comment by xianguosoul** [comment]
> 找到复现方法和原因了，蓝叠5 5.10.0.1085 N64，安卓9（Pie）实例，只有安卓9实例能复现，蓝叠5的小版本号应该没有影响。
> 
> 蓝叠安卓9 的 nc 命令似乎有点特别，`screencap | nc ...` 能发送截图，但是截图发送完之后命令不会结束，所以导致了 20s 的超时。`echo 1 | nc ...` 也是一样会接收超时。如果在开始运行的时候进行性能测试，刚好只有 `screencap | nc ...` 这种方式可用，就会出现 #3320 这种每步操作都需要等待到超时的问题。
> 
> 改成了 `screencap | busybox nc ...` 就解决问题了。Alas目前是这样写的： https://github.com/LmeSzinc/AzurLaneAutoScript/blob/ab293de103caccf488c6e2f8bdb28927b4bc8aa0/module/device/connection.py#L291-L326
> 
> 然后是另一个问题的答案，为什么初始化性能测试的时候，只有 `screencap | nc ...` 可用呢？
> 
> 如果模拟器桌面比较整洁，连广告都没有，在模拟器桌面启动MAA，此时MAA进行性能测试，`screencap -p` 和 `screencap | gzip ...` 都因为图片复杂度低压缩率高，MAA报错 `data is too small!`，认为该方式不可用，只剩下不压缩的 `screencap | nc ...` 过关了。

根据你说的，我检查asst.log，确实看到了maa测试screencap -p并返回“data is too small”
但是，我尝试了把分辨率、dpi改为推荐的1280*720、320dpi，没用
再把模拟器桌面多放几个图标，也没用
那应该怎么解决呢？

**Comment by xianguosoul** [comment]
> > 找到复现方法和原因了，蓝叠5 5.10.0.1085 N64，安卓9（Pie）实例，只有安卓9实例能复现，蓝叠5的小版本号应该没有影响。
> > 蓝叠安卓9 的 nc 命令似乎有点特别，`screencap | nc ...` 能发送截图，但是截图发送完之后命令不会结束，所以导致了 20s 的超时。`echo 1 | nc ...` 也是一样会接收超时。如果在开始运行的时候进行性能测试，刚好只有 `screencap | nc ...` 这种方式可用，就会出现 #3320 这种每步操作都需要等待到超时的问题。
> > 改成了 `screencap | busybox nc ...` 就解决问题了。Alas目前是这样写的： https://github.com/LmeSzinc/AzurLaneAutoScript/blob/ab293de103caccf488c6e2f8bdb28927b4bc8aa0/module/device/connection.py#L291-L326
> > 然后是另一个问题的答案，为什么初始化性能测试的时候，只有 `screencap | nc ...` 可用呢？
> > 如果模拟器桌面比较整洁，连广告都没有，在模拟器桌面启动MAA，此时MAA进行性能测试，`screencap -p` 和 `screencap | gzip ...` 都因为图片复杂度低压缩率高，MAA报错 `data is too small!`，认为该方式不可用，只剩下不压缩的 `screencap | nc ...` 过关了。
> 
> 根据你说的，我检查asst.log，确实看到了maa测试screencap -p并返回“data is too small” 但是，我尝试了把分辨率、dpi改为推荐的1280*720、320dpi，没用 再把模拟器桌面多放几个图标，也没用 那应该怎么解决呢？

参见常见问题
安装蓝叠的时候选择 Nougat 64 bit即可，不要选择Pie 64-bit版本。
