### ISSUE TITLE
方舟显示数据更新，MAA 直接傻了

### ISSUE THREAD

**Issue by tangge233** [MaaAssistantArknights/MaaAssistantArknights#2909]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如图所示，这个对话框弹出来 MMA 无法正确处理……

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10097314/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/50769997/204114631-aec39b6a-f852-4b72-a6c4-06a9ebd40d73.png)
![image](https://user-images.githubusercontent.com/50769997/204114646-fdd051d2-7bcf-4b71-a9e5-516a23dfaed0.png)

### 还有别的吗？

模拟器：逍遥安卓
系统：Windows 11

**Comment by ntgmc** [comment]
现在支持自动重连这个的好像只有自动肉鸽 其他功能是会愣住的
