### ISSUE TITLE
夜神模拟器公招闪退

### ISSUE THREAD

**Issue by Limiyali** [MaaAssistantArknights/MaaAssistantArknights#291]
游戏进入公招界面后，助手就会卡死，然后闪退。复现概率：100%
其它功能似乎正常
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8262894/asst.log)

<img width="716" alt="image" src="https://user-images.githubusercontent.com/23132904/158609954-f3a98296-49b9-492b-b5d5-577632024df8.png">

**Comment by MistEO** [comment]
outdated, 新版本还有这个问题么，再来个新的日志康康

**Comment by Limiyali** [comment]
> outdated, 新版本还有这个问题么，再来个新的日志康康

新版本没有了
