### ISSUE TITLE
运行完之后就停在那个页面

### ISSUE THREAD

**Issue by aaabiu** [MaaAssistantArknights/MaaAssistantArknights#2910]
### 说说你遇到的问题？

比如我最后要运行的是领取任务奖励，领完奖励之后就停在了任务界面

### 有什么好的想法？

要不加一行返回主页的代码

**Comment by ntgmc** [comment]
返回主页干嘛（）

**Comment by aaabiu** [comment]
我每次mma搞完都自己在游戏里里逛逛 有点参与感




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月27日(星期天) 上午9:48
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 运行完之后就停在那个页面 (Issue #2910)





 
返回主页干嘛（）

**Comment by aaabiu** [comment]
有空也可以搞搞基建副手换人 那个好像能给干员加信赖？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月27日(星期天) 上午9:48
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 运行完之后就停在那个页面 (Issue #2910)





 
返回主页干嘛（）

**Comment by ntgmc** [comment]
> 有空也可以搞搞基建副手换人 那个好像能给干员加信赖？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MaaAssistantArknights/MaaAssistantArknights" ***@***.***&gt;; 发送时间:&nbsp;2022年11月27日(星期天) 上午9:48 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 运行完之后就停在那个页面 (Issue #2910) 返回主页干嘛（） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

内个建议自己来
