### ISSUE TITLE
自动公招bug 一直识别同一个位置的公招 也不进行招募

### ISSUE THREAD

**Issue by ewfdsdf1011** [MaaAssistantArknights/MaaAssistantArknights#2911]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

运行自动公招后，会一直识别同一个位置的公招词条，识别之后会设置时间9小时，然后返回公招界面，然后再进入同一位置识别，循环多次之后报错。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10097408/asst.log)

### 截图

![Screenshot_20221127-104538](https://user-images.githubusercontent.com/72699431/204116976-3a44812e-df5a-46dc-b4f3-012a3947191b.png)
![image](https://user-images.githubusercontent.com/72699431/204116993-bbc2018a-bf12-4273-a1fe-3a4b48f53c2e.png)
![image](https://user-images.githubusercontent.com/72699431/204117152-61efc567-620e-48cd-92ba-d554b0b2d4a7.png)

### 还有别的吗？

模拟器 夜神模拟器 v7.0.3.8002
操作系统 windows10

**Comment by horror-proton** [comment]
似乎是 OCR 问题导致公招时间校验出错了, 正确的识别结果应该是 `09`, 但是被识别成了 `0`
