### ISSUE TITLE
基建换班的选人界面滑动幅度过大

### ISSUE THREAD

**Issue by 996-forever** [MaaAssistantArknights/MaaAssistantArknights#2912]
### 说说你遇到的问题？

基建换班的选人界面，要选的角色可能由于在滑动前和滑动后都只露出了半张图片导致无法识别，然后要一直滑动到底再反过来才能识别，有点花时间（虽然是长草。。。）

### 有什么好的想法？

减小每次滑动的幅度，让每个角色都能完整出现一次

![2](https://user-images.githubusercontent.com/74813527/204118729-2105c5c6-ae73-4703-a6ff-366b1ff42f81.PNG)
![3](https://user-images.githubusercontent.com/74813527/204118733-a9623c41-7e59-4351-9eec-db2527c01eea.PNG)
![4](https://user-images.githubusercontent.com/74813527/204118734-3f01759a-237a-4a79-ae3a-e773e4c7102f.PNG)

**Comment by MistEO** [comment]
是 bug，来个日志

**Comment by 996-forever** [comment]
时间是11-27上午，尝试在制造站中放入刻俄柏和红云，识别失败后，手动控制图片滑到屏幕中心，识别成功

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10098374/asst.zip)

**Comment by KuiPer-LTW** [comment]
> 是 bug，来个日志

确定是bug，我也有这种情况，而且是稳定出现，因为我那个干员的位置就是刚好被挡住了

**Comment by MistEO** [comment]
修过了，是 minitouch 没有正常生效导致的

**Comment by MistEO** [comment]
v4.8.0-alpha.1 fixed
