### ISSUE TITLE
繁中服求更完善的功能

### ISSUE THREAD

**Issue by JeffLiHK** [MaaAssistantArknights/MaaAssistantArknights#2913]
### 说说你遇到的问题？

这个软件真的很好用，感谢各位的努力付出。不过目前繁中服还未支持全部功能，希望开发组可以尽快让未支持的功能也尽快上线。（例如未支持的自动基建还有自动选关卡的刷理智等），如有需要可以找我，我可以提供繁中截图

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/discussions/1212#discussioncomment-3176596
