### ISSUE TITLE
无法打开程序，显示“试图加载格式不正确的程序”

### ISSUE THREAD

**Issue by IreneZ11** [MaaAssistantArknights/MaaAssistantArknights#2914]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

之前一直在用maa没有出过任何问题，昨天日常上线准备摸鱼发现打不开惹
一直用的蓝叠模拟器，重新下载了三次并没有解决
感谢大佬✿✿ヽ(°▽°)ノ✿

### 日志文件

[Uploading asst.log…]()
这个是之前的，新下载的好像没有找到这个TT

### 截图

![e8f4f10c3aa24dd000162f39e11c2fd86a19885c659ee8bbc0431e99d3771893QzpcVXNlcnNcODYxNThcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDExMzk1NDAxMjBfdjJcSW1hZ2VGaWxlc1wxNjY5NTI3MjYxNDYzXzdERTZBOTYxLTZBRkQtNGEyYi1CNTUyLTYxNkNBQ0ZFOTU4Qy5wbmc=](https://user-images.githubusercontent.com/103345965/204120980-cd282ecd-5045-4910-95a3-e5132b7144af.png)

### 还有别的吗？

（MAA真的好好用，谢谢大佬！！）

**Comment by ntgmc** [comment]
问一下maa版本和你是啥系统

**Comment by IreneZ11** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10097613/asst.log)


> 问一下maa版本和你是啥系统

他一直转圈圈好像没有上传 哭了，版本是4.7.1（好像从这里开始不能用了，大概是在，危机合约刚开始的时候？）Windows系统的！

**Comment by IreneZ11** [comment]
找了一圈好像没有其他小伙伴有一样的问题，但我一直都自动更新的也没有碰过它那个文件夹TT 不知道为什么会这样子

**Comment by ntgmc** [comment]
> 找了一圈好像没有其他小伙伴有一样的问题

之前好像在某个群看到过一次 忘了 你如果是重下了完整包，按照[文档](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%BD%AF%E4%BB%B6%E4%B8%80%E6%89%93%E5%BC%80%E5%B0%B1%E9%97%AA%E9%80%80)的做完还不行就不是你的问题了

**Comment by IreneZ11** [comment]
好的！请稍等一下，我再重新装一下研究研究看看！谢谢您！

**Comment by MistEO** [comment]
你的电脑是 32 位的？

**Comment by IreneZ11** [comment]
> 你的电脑是 32 位的？

不是诶，是64的，之前一直用的好好的，突然就这样子了 _(: o)_

**Comment by MistEO** [comment]
重新下载完整包有用吗？
