### ISSUE TITLE
请增加对Android12版本模拟器的支持，如MUMU X

### ISSUE THREAD

**Issue by lintianshi-X** [MaaAssistantArknights/MaaAssistantArknights#2915]
### 说说你遇到的问题？

目前Android12系统的模拟器应该会越来越多，因为可以用Vulkan，所以性能提高很大，MUMU X试验下来不能使用MUMU的通用配置，adb端口是7555，和原来的一样，但是连接上之后不能正常使用，显示出错

**Comment by ntgmc** [comment]
知道为啥mumux不能用吗？不是因为是安卓12，也不是因为不适配，而是因为adb截图出来是透明的，maa没办法执行操作。你要真想要就找mumu客服把这个解决了就能用

**Comment by ABA2396** [comment]
Maa截图用的是 screencap，screencap 是从 Android 2.3 开始提供的一个系统级的截图工具，Android12也是支持的，但是mumu9 和 mumuX 用 screencap 截图出来却都是没数据的，这个问题只能去找mumu解决

**Comment by lintianshi-X** [comment]
那只能等待新的安卓12模拟器了，下个月夜神出12，不知道行不行

**Comment by ABA2396** [comment]
现在MUMU X支持截图了，已经能用了

**Comment by SekiBetu** [comment]
> 现在MUMU X支持截图了，已经能用了

仍然无法使用，截图为黑色

**Comment by LmeSzinc** [comment]
你需要将 Mumu X 模拟器更新到 12.1.6.0 版本或者更高

![image](https://user-images.githubusercontent.com/37934724/226183462-76c6e85d-2bb1-4be4-91a4-30fdff24b7a5.png)

**Comment by SekiBetu** [comment]
> 你需要将 Mumu X 模拟器更新到 12.1.6.0 版本或者更高
> 
> ![image](https://user-images.githubusercontent.com/37934724/226183462-76c6e85d-2bb1-4be4-91a4-30fdff24b7a5.png)

12.1.10够不够新，没用
