### ISSUE TITLE
使用第三方的工具进行截屏是不是对各种模拟器兼容性更好

### ISSUE THREAD

**Issue by gdf159159** [MaaAssistantArknights/MaaAssistantArknights#2916]
### 说说你遇到的问题？

参考fgo的辅助 BBchannel

这种方式采用Windows自带API获取Windows窗口的截屏，并同时采用ADB的方式连接模拟器只用作虚拟点击而不用其截屏。

这个思路的兼容性应该非常好吧

**Comment by ABA2396** [comment]
截图用的是安卓的screencap，安卓版本2.3以上手机和模拟器基本都是能用的，而且maa还有mac端，你说的这个方法只有Windows能用而且还必须保持窗口在前台

**Comment by MistEO** [comment]
win32 api 反而是兼容性不行的，最一开始就是 win32 api。适配各家模拟器太要命了才换 adb 的

**Comment by gdf159159** [comment]
@MistEO @ABA2396 

![微信截图_20221127192154](https://user-images.githubusercontent.com/8487256/204137353-0c99f6d2-0899-4677-8945-019edb64aa1f.png)

他这个工具还有其他的方式

我又看了一遍他写的介绍 他这个win32的api应该是为了用ios虫洞控制iphone真机运行的

模拟器应该是截图的那几种办法 安装一个yosemite的app用他截图的吧

**Comment by MistEO** [comment]
minicap 和 我们自己的 cap，都在日程上了
