### ISSUE TITLE
干员无法识别相关问题

### ISSUE THREAD

**Issue by tianyiwei** [MaaAssistantArknights/MaaAssistantArknights#2919]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

重装系统后重新下载了MMA,但是发现干员识别似乎有问题，昨日晚间时发现自动抄作业的时候发现无法识别山，今日零点左右基建换班时发现无法识别龙舌兰。另外发现识别选择干员时滑动速度相较之前明显变慢了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10098730/asst.log)

**Comment by MistEO** [comment]
fixed
