### ISSUE TITLE
基建新增的基建副手满信赖提示功能会导致卡死

### ISSUE THREAD

**Issue by lhhxxxxx** [MaaAssistantArknights/MaaAssistantArknights#292]
忘了截图了，直接满信赖的放进去也不会再出提示。。。。总之会出现在这个位置导致处理这一步的时候卡死
![2eeee.png](https://user-images.githubusercontent.com/91231470/158740673-99eddf60-e73a-47dc-a53b-63b1fa5923fc.png)

**Comment by hjhjfhjhujhh** [comment]
给你个截图
![` 20TG7 M$%B(Q( Y X%_72](https://user-images.githubusercontent.com/89215821/158980615-564777f9-8221-4418-a78f-a4967a5ccf1f.png)

**Comment by MistEO** [comment]
v3.0.8 fixed
