### ISSUE TITLE
刷完剿灭模式返回途中弹窗导致卡住

### ISSUE THREAD

**Issue by 666233j** [MaaAssistantArknights/MaaAssistantArknights#2920]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

卡在剿灭情报总汇那里，卡之后就直接来上报了

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10099555/asst.zip)

**Comment by 134820134820** [comment]
确实会这样，能不能增加一个对那个页面的识别和关闭

**Comment by unninie** [comment]
我也在这卡住了，能不能把剿灭刷完返回首页的过程改为用跳转回首页而不是返回键，这样应该能跳过剿灭的那个动画

**Comment by MistEO** [comment]
来张原图~

**Comment by 134820134820** [comment]
> 来张原图~

![Screenshot_2022 12 11_19 43 59 737](https://user-images.githubusercontent.com/79043872/206901797-95d006c0-5831-4b17-93e0-74543553fdd4.png)
按返回会卡在这个界面

**Comment by unninie** [comment]
![Snipaste_2022-12-11_20-14-09](https://user-images.githubusercontent.com/64136941/206902985-f0a62efe-31dc-405c-af9d-f0662a47a06f.png)
轮换新图时候会有一个很长的动画

**Comment by unninie** [comment]
![1](https://user-images.githubusercontent.com/64136941/206905271-2978e34c-b504-44cf-a633-0bf5f89c7afe.png)

**Comment by 666233j** [comment]
我发现是扫荡完剿灭后在剿灭页面打开maa刷的话它会自己退出然后到那个红色页面就退不出去了
