### ISSUE TITLE
蓝叠国际版的游戏启动问题

### ISSUE THREAD

**Issue by Kagura-Nanaa** [MaaAssistantArknights/MaaAssistantArknights#2921]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在蓝叠模拟器国际版安装的官服应用名是英语，mma似乎不能正确识别
mma版本为4.7.2
![图片](https://user-images.githubusercontent.com/44108528/204170190-e0cd849c-68a0-421f-adb2-ed52ef64981b.png)
![HD-Player_aWT5H7lvKM](https://user-images.githubusercontent.com/44108528/204170215-4c9e18c0-3e0c-4280-bfff-9df4cb5c9de0.png)

### 日志文件

[Uploading asst.log…]()

**Comment by ntgmc** [comment]
> 你自己点进游戏去了吗？

他现在不就是【开始唤醒】失败吗

**Comment by MistEO** [comment]
你日志还是没传上来
