### ISSUE TITLE
自动公招经常出现错误

### ISSUE THREAD

**Issue by Axeva-star** [MaaAssistantArknights/MaaAssistantArknights#2924]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我的版本是4.7.3-alpha.0.45.g8d50698c自从更新了这个版本就无法自动公招，我的模拟器是蓝叠国际版

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10099800/asst.log)

**Comment by horror-proton** [comment]
fixed in 7c8a7caba13ee34916154291b097418149b06acf

**Comment by MistEO** [comment]
v4.8.0-alpha.1 fixed
