### ISSUE TITLE
制作站识别不出人物

### ISSUE THREAD

**Issue by metaplaxia** [MaaAssistantArknights/MaaAssistantArknights#2929]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

win系统，蓝叠5，版本4.7.2
第一次 自动基建制造站（搓玉）换干员的时候，小羊和炎熔在滑动后的界面边缘，导致maa选中了月见夜但是一直没选剩下两个干员，重复滑动4次之后放弃月见夜选择了效率较低的组合(而且它没用无人机）
第二次 11.12开始 可能因为我手动调整了，它选择的顺序变了但是还是没选小羊那一组，不过效率倒是一样了，但是发生了很多次干员冲突（截图是第二次的）
第三次干员冲突还是存在
第四次没有干员冲突了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10104622/asst.log)

### 截图

![F4B2F942-010C-4B7A-AF1C-C4B63F865581](https://user-images.githubusercontent.com/119327837/204303802-0ab0c1a6-b4f2-4751-81fd-738fb93f0cc0.png)

### 还有别的吗？

无了

**Comment by MistEO** [comment]
修过了，等等新版本吧~

**Comment by MistEO** [comment]
duplicate of 
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2929
