### ISSUE TITLE
开始唤醒错误

### ISSUE THREAD

**Issue by guojunyu196** [MaaAssistantArknights/MaaAssistantArknights#293]
![BS_PIC_2022-03-17-12-45-40](https://user-images.githubusercontent.com/76220347/158741259-7709faa6-456b-4eb9-a436-7e60b6db1fb9.png)

![uTools_1647492329948](https://user-images.githubusercontent.com/76220347/158741251-f0bfa5e4-473d-4c7a-a0fc-cfd69f48a632.png)

[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8281559/asst.log)

**Comment by ABA2396** [comment]
这个不是唤醒界面，这个点了之后有明日方舟的地方才是

**Comment by MistEO** [comment]
奇怪，明明是一样的画面，为啥你这里模板匹配得分这么低_(:з」∠)_

**Comment by MistEO** [comment]
> 这个不是唤醒界面，这个点了之后有明日方舟的地方才是

这个界面就是可以的

**Comment by MistEO** [comment]
已修复，下个版本生效~

**Comment by MistEO** [comment]
v3.0.9 fixed
