### ISSUE TITLE
水月肉鸽 自动放弃探索以及未达到次数停止肉鸽

### ISSUE THREAD

**Issue by ForeverNightmare** [MaaAssistantArknights/MaaAssistantArknights#2933]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在minitouch更新后（4.7.0)，水月肉鸽的各个分队会自动放弃探索(4.7.1,4.7.2,4.7.3版本都存在相同问题)，minitouch更新前则能正常探索直到战斗失败。关闭minitouch启用兼容模式依然出现相同情况。
原因可能出现在 优化 水月肉鸽 安全屋选项，支持安全屋再利用 这一更新上？之前曾经看到在非战斗的事件节点退出了探索，但是忘记截图了。
同时在探索次数是9999999的情况下，探索了5次还是4次后停止了任务，显示任务完成。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10105870/asst.log)

11-28 11:46:22

11-28 11:39:18

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10106471/asst.log)
11-28 13:19:36
### 截图
![image](https://user-images.githubusercontent.com/37356781/204337358-55499c43-daa5-4df0-87f7-536a5e570090.png)

![image](https://user-images.githubusercontent.com/37356781/204336581-8acc778d-ea0a-4f95-b761-198af956c183.png)

![QQ截图20221128132006](https://user-images.githubusercontent.com/37356781/204352526-fa5f59a4-e2a9-491b-871b-c5dcf6d7767e.png)
![QQ截图20221128132013](https://user-images.githubusercontent.com/37356781/204352567-fa9b1650-50b3-43d7-9a07-1e5048edbd8a.png)

### 还有别的吗？

模拟器 mumu模拟器
操作系统 windows11

**Comment by MysteriousHeroineX** [comment]
水月肉鸽：下干员时只反复点羽毛笔，不放下场，导致第一关即战斗失败；过程中看到蓝门亮了，推测可能是部署干员位置识别错误。模拟器不知道怎么录屏
![image](https://user-images.githubusercontent.com/74663297/204503061-4d0bc953-e073-443d-a06f-bb5b1cb13631.png)
![image](https://user-images.githubusercontent.com/74663297/204501569-75ede9d2-4444-4314-90f1-344c567ee209.png)

**Comment by MistEO** [comment]
v4.8.0-alpha.1 fixed
