### ISSUE TITLE
关卡选择1-7时，maa会进入第二章而非第一章

### ISSUE THREAD

**Issue by BigSaltyMan** [MaaAssistantArknights/MaaAssistantArknights#2934]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

选择关卡选1-7 maa会到“觉醒"那里从后往前只点一下 导致进入第二章

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10108708/asst.log)

### 还有别的吗？

使用的mumu模拟器 win11系统

**Comment by yuetieqi-meow** [comment]
same question
just after ver 4.7.3

**Comment by ABA2396** [comment]
32fa9bd98c6c7912c1b8c6d1281a5efabe1866b4 fixed
