### ISSUE TITLE
关于肉鸽模式下技能释放问题

### ISSUE THREAD

**Issue by Aszlkm** [MaaAssistantArknights/MaaAssistantArknights#2936]
### 说说你遇到的问题？

在肉鸽模式下，携带部分技能如艾丽妮二技能裂潮时，因为这类技能为``可充能``的技能，且需要在攻击范围内``有敌人``时才可以释放。又因为该技能只要充能一次后人物模型上方就会出现可以释放技能的标识，而MAA会捕捉到这一标识并且``持续不断``的尝试释放，即使在攻击范围内没有可锁定的目标也会如此。

虽然不能算bug，但会影响其他技能的释放，对使用体验也有影响。

### 有什么好的想法？

建议修改这类技能的释放逻辑或者降低他们的优先级。

**Comment by ntgmc** [comment]
一个刷关的脚本你管他呢，扔到后台不就行了，难不成还看着他开不开技能啊

**Comment by ntgmc** [comment]
目前解决方法：打开resource/roguelike_recruit.json文件，修改干员的“skill”，如艾丽妮改成一技能

**Comment by WWPXX233** [comment]
fixed
