### ISSUE TITLE
关于肉鸽模式下投锋类干员的选择

### ISSUE THREAD

**Issue by Aszlkm** [MaaAssistantArknights/MaaAssistantArknights#2937]
### 说说你遇到的问题？

肉鸽模式下投锋类干员再加上自动回复技力简直就是漏怪的天堂（（（

明明好好的拦着小怪，结果一开技能就给放走了 悲

### 有什么好的想法？

建议降低肉鸽模式下投锋类干员选择的优先级或者降低他们技能使用的优先级。

**Comment by ntgmc** [comment]
这个一样的道理，在resource\roguelike_recruit.json中修改干员的优先级，不想招就改成0

**Comment by WWPXX233** [comment]
不应该啊你是不是没有挡二先锋德狗应该有吧

**Comment by Aszlkm** [comment]
有德狗，但可能是因为希望问题，没招过几次（
