### ISSUE TITLE
关于公招上传企鹅物流的条件

### ISSUE THREAD

**Issue by KumaTea** [MaaAssistantArknights/MaaAssistantArknights#2938]
### 说说你遇到的问题？

我了解到 MAA 会把公招的识别结果上传企鹅物流，
请问是在什么条件下上传的呢 (即我在 `asst.log` 找不到相关描述)

如果是识别即上传，可能导致一个问题：

<img width="411" alt="image" src="https://user-images.githubusercontent.com/36222458/204446878-3911e17f-7778-42b9-86af-9f3a43c62129.png">

我在月底招募券不足的时候经常这么设置，这就会导致1号位用完所有刷新机会后，2/3/4号位在每一次MAA运行公招模块时识别并上传相同数据，造成重复。

如果是这样，建议可以在有实质操作 (招募 / 刷新) 时再上传。

---

~~因为看不懂 C# 没翻源码，如果本来就是这么设计的当我没说~~

**Comment by ABA2396** [comment]
自动上报的，这个不用设置，上报的只有用刷新次数刷出来和公招结束后的第一次的识别，不会上报空着的招募栏
