### ISSUE TITLE
macOS，运行过程中提示connectionlnfo:ScreencapFailed

### ISSUE THREAD

**Issue by JayeGT002** [MaaAssistantArknights/MaaAssistantArknights#2942]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

挂机一段时间后就会出现这样的问题，如截图所示，错误提示connectionlnfo:ScreencapFailed
最后的Unknown message是我停止maa之后出现的
未启用Gzip和触控兼容模式

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10115944/asst.log)

### 截图

<img width="901" alt="image" src="https://user-images.githubusercontent.com/60620843/204612213-865da591-b1c2-4362-9d73-612171d77bc2.png">

### 还有别的吗？

macOS 版本：13.0.1
MAA版本：4.7.2
Android Studio版本：运行时版本:11.0.13+0-b1751.21-8125866 aarch64
Android配置：Android Tiramisu Google APls | arm64

**Comment by WWPXX233** [comment]
#2942
