### ISSUE TITLE
刷理智功能 备选关卡选择会卡在剿灭 不会选择下一个

### ISSUE THREAD

**Issue by anywugn** [MaaAssistantArknights/MaaAssistantArknights#2943]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

![IMG_9717](https://user-images.githubusercontent.com/31065340/204644404-a2e76711-f61b-4283-9c17-6527904f5d38.PNG)

![image](https://user-images.githubusercontent.com/31065340/204644697-bf7fe0a5-0cd5-4600-a2e3-6beb2343fbba.png)

如上两图，**在剿灭刷完之后**，如果备选关卡中有选择剿灭，则排在剿灭之后的【备选关卡】以及【剩余理智】都不会生效，推测在判断剿灭的步骤进入了死循环。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10117200/asst.log)

**Comment by ABA2396** [comment]
这个确实没判断，选择备选关卡的逻辑是判断上一个关卡当日是否开放，而剿灭是常驻的，就像你关卡选择了1-7也不会跑备选一样
