### ISSUE TITLE
我发现一个极其离谱的bug

### ISSUE THREAD

**Issue by zhongmof** [MaaAssistantArknights/MaaAssistantArknights#2944]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在我使用获取信用及购物功能时，他访问完好友基建会莫名其妙点到火蓝之心，第一次我以为是我误操作了，第二次他又非常执着的点了进去
我使用的是开发版

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10117264/asst.log)

**Comment by MistEO** [comment]
这就是那个借助战赚信用的功能

**Comment by ntgmc** [comment]
![image](https://user-images.githubusercontent.com/74061867/204687968-d185537f-8d83-49a3-a3d4-a6862477245e.png)

**Comment by zhongmof** [comment]
> 这就是那个借助战赚信用的功能

但是他会卡在那不动啊
