### ISSUE TITLE
11-11 跳过剧情失败

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#2945]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在跳过的边缘反复试探

### 日志文件

[asst - 副本 (2).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10118574/asst.-.2.log)

### 截图

![image](https://user-images.githubusercontent.com/74061867/204685722-74cbc268-86cc-4f55-b372-63c7c36acedb.png)https://user-images.githubusercontent.com/74061867/204685683-157174b7-2bd2-4408-b587-f8f1b5b274e6.mp4

**Comment by ntgmc** [comment]
具体请看视频https://user-images.githubusercontent.com/74061867/204685683-157174b7-2bd2-4408-b587-f8f1b5b274e6.mp4

**Comment by HydrogenDeuterium** [comment]
> 具体请看视频https://user-images.githubusercontent.com/74061867/204685683-157174b7-2bd2-4408-b587-f8f1b5b274e6.mp4

你这个视频我看了好像是黑屏？
