### ISSUE TITLE
仓库识别问题

### ISSUE THREAD

**Issue by IranksAdral** [MaaAssistantArknights/MaaAssistantArknights#2946]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

好几天我都发现狙击芯片数量7会识别成1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10118768/asst.log)

### 截图

![2022-11-30_08-45-23 840_raw](https://user-images.githubusercontent.com/87361258/204690986-9b4d0bdb-6df6-4fc5-82e7-6186ff38bdcf.png)
![2022-11-30_08-45-18 875_raw](https://user-images.githubusercontent.com/87361258/204691001-a462ad6f-2548-4d87-8ee9-096bd8e739e5.png)

**Comment by MistEO** [comment]
现在算法更新过了， 还有问题的话再开个 issue 吧，谢谢~
