### ISSUE TITLE
借助站刷信用无法进图

### ISSUE THREAD

**Issue by dylanhz** [MaaAssistantArknights/MaaAssistantArknights#2947]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

OF-1在有代理的情况下，会在代理选人界面反复选人，卡住无法进图。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10119052/asst.zip)

### 截图

![Screenshot_2022 11 30_11 09 06 059](https://user-images.githubusercontent.com/53137516/204699084-a2f9db7e-fc2c-4540-83f4-c56525d8199f.png)

### 还有别的吗？

v4.8.0-alpha.1

**Comment by ntgmc** [comment]
@Hydrogina
