### ISSUE TITLE
傀影肉鸽 雪山上的来客 怪被无限冻住导致卡关

### ISSUE THREAD

**Issue by R7v0en** [MaaAssistantArknights/MaaAssistantArknights#2948]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如题

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10119151/asst.zip)

### 截图

![image](https://user-images.githubusercontent.com/100417475/204701676-1a04c37b-60de-4e20-98ef-926b0814270c.png)
![image](https://user-images.githubusercontent.com/100417475/204701710-bd8e08d4-c3c8-4982-88a6-631df525f561.png)

**Comment by MistEO** [comment]
不会无限等的，过十分钟就自动退了

**Comment by R7v0en** [comment]
> 不会无限等的，过十分钟就自动退了

原来如此，之前一直挂后台刷都没啥感觉，就是今天切屏的时候顺便瞟了一眼才发现的
