### ISSUE TITLE
集成战略模式无法完成战斗胜利后的招募识别

### ISSUE THREAD

**Issue by YipKei** [MaaAssistantArknights/MaaAssistantArknights#295]
如题，战斗胜利点了招募券之后卡死，然后自动放弃战斗，试了十几次都是这样。
蓝叠4.280.0.1022
分辨率设置960x540
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8281812/asst.log)

另外提一个关于多分辨率适配的可行性参考：
在长宽比大于16:9时，明日方舟的内容一般是维持高度不变，然后横向拓展。
这意味着在超宽分辨率下，可以考虑根据元素的不同对齐方式，对不同行为采用不同的对齐锚点。
我试过好像不支持20:9分辨率屏幕下的战斗，考虑到战斗地图是居中对齐的，可以尝试将横坐标的判断锚点设置为1/2X，应该就能正确判断地图的位置了。

**Comment by MistEO** [comment]
最低需要 720p, 忘记写了 orz，换 1280*720 试一下

**Comment by YipKei** [comment]
另外提一些关于集成战略通关方面优化的问题：
**一、单一地图**
1、驯兽小屋如果可以实现的话，必须增加对源石祭坛的判断，现在不会正常判断源石祭坛的位置，这张地图翻车率接近100%（也可能是默认起手抓六星近卫的策略在面对这张图的时候有大问题，山不清楚，默认抓煌必翻）
2、第二层的意外这张地图，精一队伍是扛不住双击术师的，现在的站位必翻车，关于这关可能需要优化一下站位逻辑。
**二、整体规划**
1、水陈开局在前两层的稳定性个人感觉要高于近卫开局，起手抓水陈、斑点、史都华德。如果在布局和站位方面遇到了问题需要参考的话我可以提供各个地图的参考站位
2、令1技能开局在前两层的稳定性也相对比较高，对另外两个干员的需求比较少，同样的，如果有相关站位方面的需求，也可以联系我。
**三、其他想法**
是否存在由玩家提供部署截图并按一定格式提供抓取文件，由程序自行学习部署顺序和部署方式的可能性。
如果可以做到这一点，在不增加开发者工作量的前提下，前几层的通关可能性会大幅度提高。
如果不适宜做到客户端里，也可以考虑提供一个训练工具，让玩家可以和其他玩家一起分享自己训练出来的部署方式。

**Comment by YipKei** [comment]
提一些重构思路，仅供参考
提供两种配置模式，模式A是截图配置
输入1~2张布局完成后的截图，根据截图尝试部署干员，不过这个对于特定地图来说不好用
模式B是输入json配置文件，文件结构大致是：
地图名称
 - 部署干员信息列表1
  - 干员ID，部署格坐标，部署时朝向，部署时间/部署顺序，技能开启逻辑（秒开/不开/定时）
 - 部署干员信息列表2
 - ...
通过这种方式手动添加配置。
至少在我的印象中，水陈开局和令开局可以确保前两层都不需要招募任何干员，用稳定的配置通关。
生存这种特殊词条需要进行一次特判，单生存基本不用放干员。
针对性配置可以将前两层的关卡通关率提升到90%以上。

如果有需要的话我可以提供前两层所有地图，部分标准开局的固定摆法截图来帮助生成配置，如果需要考虑反检测的话，也可以对部分地图提出多解。

**Comment by MistEO** [comment]
其实现在已经在弄了（~~指 [画饼](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/%E6%88%98%E6%96%97%E6%B5%81%E7%A8%8B%E5%8D%8F%E8%AE%AE.md)~~

**Comment by YipKei** [comment]
文档中有几点不太明朗的地方，希望能完善一下注释
1、location字段，注释文本中希望能够指出两个数字分别对应PRTS.map的【字母+数字】坐标标记法的对应关系，本身使用的形式不需要改。
2、kills_action字段在说明文档中没找到，是不是前后名称出现了不一致
3、集成战略的作业还需要两个字段，一个是紧急作战的判断，一个是打鸭爵/高普尼克的判断（通过识别关卡敌人数量预估），静态作业一般只能二选一，前者相对重要一些？（不过只是刷源石锭的话好像也用不上鸭爵和高普尼克？）
4、集成战略的作业还需要加入地图要素识别，存在静态要素识别的有好几张地图，一张是驯兽小屋（一层源石祭坛），一张压轴登场（二层传令兵），一张斗兽笼（三层半血），三层boss图的开门请当心和寒渊惜别也需要，不过死作业好像本来就打不过，一张是仪式之夜（好像基本打不到？），然后可能需要的还有二层的巡逻队（开局是提亚卡乌勇士和黄刀哥开局处理起来也有区别）
5、动态要素的支持我不清楚能不能实现，动态要素识别主要指的是从众效应那种无静态要素，但是存在路线不同影响部署顺序的需求。
6、我没看明白，集成战略模式中，默认编队之外后续招募的应变干员，如何区分近战和远程执行不同的部署操作，同时不对进程的推进产生影响。
------
一些从说明文档中暂时还看不出来有没有开发的与集成战略相关的功能：
1、知难而退：死作业过不去的地图直接退出，节省图内浪费的时间。
2、欺软怕硬：在进入一层之后优先选择难度较低的抉择路线。
3、生存词条的判断，存在生存词条的时候部分地图需要用特定的打法只处理毒不死的敌人（指挥分队可能可以直接放掉）
4、根据固定配队选择以覆盖默认干员抓取配置的专用配置，以及根据固定配队自动选择作业子集的功能。
话说开局固定配队选择的支持应该大概有在开发吧？

**Comment by MistEO** [comment]
没有的，肉鸽不会大幅优化了，可能会沾到点这个功能的边顺带着弄一些。

这个功能本质上的目的是为 自动打危机合约 18、活动关卡自动开荒 这种需求准备的

肉鸽一直往后打，打的很高，我理解是伪需求：为了源石锭只打第一层就好；为了刷蜡烛一个月才挂一次（一下午就挂完了），也没必要进一步优化

**Comment by YipKei** [comment]
抛开伪需求的部分，单从刷源石锭的效率来看，仍然需要保留的需求有：
1、驯兽小屋的源石祭坛判断，这个占了一层翻车90%以上的原因，解决这个，刷锭的成功率可以大幅度提升
2、对生存词条的检测，1层生存在非紧急作战的时候可以不用部署干员，提升过图效率
3、独立配置单，包含信息有编队成员，作业选择，甚至还可以考虑加上初始编队选择，相当于提前提供的一个预设，覆盖默认配置文件。
那几个强势固定编队只考虑前两层刷锭的话，不需要招募任何额外成员，直接初始的3人就够了，招募券可以直接全扔了大幅度节省时间。
我多个账号实际体验的感觉就是其实效率受到1和3的影响很大，这两点解决了，效率可以提升一倍不止。
因为进程优先级的问题，事实上多开的压力是很大的，目前助手的进程优先级很低，会被其他的进程直接完全阻塞（7700+16g D3 3200，六开+obs时MAA被完全阻塞），无法做出任何判断。因此对于实际的效率还是存在一定需求的。

**Comment by MistEO** [comment]
outdated
