### ISSUE TITLE
手动输入关卡名输入别传无法正常进行刷理智任务

### ISSUE THREAD

**Issue by mc-xx6** [MaaAssistantArknights/MaaAssistantArknights#2954]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

手动输入关卡名输入RI-8（RI-8是别传 密林悍将归来的关卡）无法正常进行刷理智任务
且只选择刷理智和手动输入RI-8（无法识别的关卡）就会卡在任务执行中，手动停止也会卡在正在停止中

### 日志文件

尝试多次无法上传所以用蓝奏云上传了[https://wwvk.lanzoue.com/iJLD60hb7rfi](url)

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/204824786-9a3d203f-2afd-45e2-b893-bf1238879e63.png)
