### ISSUE TITLE
干员蜜莓1技能被识别成需要手动释放

### ISSUE THREAD

**Issue by l56240560** [MaaAssistantArknights/MaaAssistantArknights#2956]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

干员蜜莓1技能被识别成需要手动释放

### 日志文件

[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10120565/asst.bak.zip)

**Comment by ntgmc** [comment]
啥玩意 能不能说清楚 在啥时候触发的（有没有可能只是点歪了）

**Comment by l56240560** [comment]
> 啥玩意 能不能说清楚 在啥时候触发的（有没有可能只是点歪了）

就是挂机肉鸽的时候,下了蜜莓,无限的去点蜜莓技能

**Comment by l56240560** [comment]
> 啥玩意 能不能说清楚 在啥时候触发的（有没有可能只是点歪了）

就是挂机傀影肉鸽的时候,下了蜜莓,无限的去点蜜莓技能

**Comment by MistEO** [comment]
fixed
