### ISSUE TITLE
长时间刷肉鸽后操作系统卡顿严重

### ISSUE THREAD

**Issue by PixelMiku** [MaaAssistantArknights/MaaAssistantArknights#2958]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

问题概述：从前几个版本就开始挂肉鸽一段时间后电脑非常卡顿，且会越来越卡直至无法操作
具体表现：
> 系统表现：鼠标移动不连贯且间隔大，窗口及其他应用响应速度慢
> 模拟器表现：模拟器帧数降低至10左右且下不去人（下不去人的问题尝试替换adb和启用触控兼容模式暂时解决）
> 卡死后恢复：关闭maa后卡顿得到缓解，但此时模拟器无法正常关闭，强制关闭模拟器后系统恢复正常；全程观察资源管理器占用情况未发现cpu，gpu，内存，硬盘等占用超过50%

发生时间：最近一次为2022年11月30日13:40左右开始的肉鸽挂机
maa版本：v4.7.3

### 日志文件

[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10123111/asst.bak.zip)

### 截图

卡住了截不动~QAQ

### 还有别的吗？

模拟器版本：蓝叠国际版5.9.600.1001 N64
模拟器配置：6c8g 720p 320dpi
操作系统版本：win11专业版 22H2
PC配置：CPU 5800X GPU 6600XT 32GBRAM 全固态 （已安装amd芯片组，显卡驱动程序版本已更新至最新）

**Comment by PixelMiku** [comment]
12月1日更新：更换夜神模拟器后此问题未复现，推测为ryzen5系列CPU与蓝叠兼容性问题；尝试更换渲染为DirectX未解决，尝试更换adb未解决；更换为夜神模拟器后出现长时间挂机模拟器崩溃；

**Comment by MistEO** [comment]
现象描述像是模拟器的锅，试试 MAA beta 版看有效果不

**Comment by vista98** [comment]
夜神的优化如何，帧率和蓝叠比那个高呢，我也去试试

**Comment by ntgmc** [comment]
> 夜神的优化如何，帧率和蓝叠比那个高呢，我也去试试

高端机型随意 低配别用 容易卡死

**Comment by vista98** [comment]
> > 夜神的优化如何，帧率和蓝叠比那个高呢，我也去试试
> 
> 高端机型随意 低配别用 容易卡死

配置5800H/3060
以前我用mumu在基建页面可以达到120帧，蓝叠只能100出头，夜神有无参考数据

**Comment by ntgmc** [comment]
> > > 夜神的优化如何，帧率和蓝叠比那个高呢，我也去试试
> > 
> > 
> > 高端机型随意 低配别用 容易卡死
> 
> 配置5800H/3060 以前我用mumu在基建页面可以达到120帧，蓝叠只能100出头，夜神有无参考数据

我i5-9500+1650夜神经常卡死 你那个算高配吧  我不清楚

**Comment by vista98** [comment]
> > > > 夜神的优化如何，帧率和蓝叠比那个高呢，我也去试试
> > > 
> > > 
> > > 高端机型随意 低配别用 容易卡死
> > 
> > 
> > 配置5800H/3060 以前我用mumu在基建页面可以达到120帧，蓝叠只能100出头，夜神有无参考数据
> 
> 我i5-9500+1650夜神经常卡死 你那个算高配吧 我不清楚

好的，回头我自己试试

**Comment by lzghzr** [comment]
同样蓝叠国际版+a卡+a u+win11，但是夜神支持hyper-v吗？

**Comment by THSLP13** [comment]
TYPE:YOSTAR_JP
都不用长时间,差不多刷20分钟我的雷电模拟器和maa就会把显存吃爆掉，然后模拟器彻底卡死（但还可以重启模拟器

**Comment by reishikou** [comment]
我是挂玩肉鸽关掉模拟器，玩其他游戏的时候开始卡了（以前不卡的）。
有遇到相同问题的小伙伴吗？
