### ISSUE TITLE
v4.8.0-alpha1 更新后刷理智10-11出错

### ISSUE THREAD

**Issue by CCCClaus** [MaaAssistantArknights/MaaAssistantArknights#2959]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

v4.8.0-alpha1 更新后，刷理智填入10-11后，模拟器工作至选择第十章破碎日冕时停住，长时间不进行下一步动作。
重新启动后仍然如此。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10124500/asst.log)

### 截图

<img width="960" alt="Screenshot_2022 11 30_23 13 13 033" src="https://user-images.githubusercontent.com/116964544/204836624-9841eefd-7f05-4432-aa50-5bb0b7328b6a.png">
<img width="640" alt="QQ图片20221130231027" src="https://user-images.githubusercontent.com/116964544/204836800-a66f64da-a35a-4c8b-806c-3934a6d6f18f.png">

### 还有别的吗？

无

**Comment by CCCClaus** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10124590/asst.log)
<img width="807" alt="QQ图片20221130232332" src="https://user-images.githubusercontent.com/116964544/204838655-24511de8-e2bf-4d22-ac4b-0502126dbe68.png">

在更改输入为 10-11-Normal 后仍然停在这

**Comment by CCCClaus** [comment]
当通过选择选择刷关卡（例如通过下拉栏选择1-7）时正常。

**Comment by ABA2396** [comment]
f4cf8ed9d85ba5adc8f07892c270ef009f8c8069
