### ISSUE TITLE
建议肉鸽编队时不优先编入预备干员；「敬奉火焰」节点优先避战

### ISSUE THREAD

**Issue by RyanSaul** [MaaAssistantArknights/MaaAssistantArknights#2960]
### 说说你遇到的问题？

1. 自动肉鸽前期有时会招募一些预备干员，而在招募了一定量干员、超过了携带上限时，MAA依旧会依照默认顺序编入干员，此时容易落下关键干员（如三星医疗干员），或自己练度较高的干员被预备干员挤掉编队位，导致翻车率升高；
2. 不期而遇-「敬奉火焰」节点会默认选择「火焰救不了这片大地」选项，此时会进入关卡「狂信如火」，MAA几乎不可能打过。

### 有什么好的想法？

1. 肉鸽编队时优先编入自己的干员，再用预备干员补位，预备干员优先选择医疗干员及地面阻挡干员；
2. 「敬奉火焰」节点优先避战，建议选择「应付了事」选项（获得15灯火）。

**Comment by et2012** [comment]
芙蓉(80)和安塞尔(100)的招募优先级是远远大于预备干员(5)的，基本上能用上的三星干员都写了优先级的。
毕竟三星白拿，比预备好，没理由不拿的。

**Comment by RyanSaul** [comment]
> 

不是招募，是编队哦

**Comment by RyanSaul** [comment]
> 芙蓉(80)和安塞尔(100)的招募优先级是远远大于预备干员(5)的，基本上能用上的三星干员都写了优先级的。 毕竟三星白拿，比预备好，没理由不拿的。如果不拿三星而是拿了预备干员，看看是不是等级太低，拉到精一50以上。

举个例子：
博士在一局肉鸽的第一层招募了一个预备术师干员，在该局中陆续招募了共计9名干员，其中包含精一55级的安赛尔，此外没有招募其他医疗干员。在之后的一次作战中，因为只有8个携带位，MAA在试图编入第9名干员时因为编队上限无法编入，此时进入快速编队界面重新编队。MAA选择了前8名干员，其中包含了之前招募的预备术师干员，而精一55级的安赛尔因为位于队列末尾没有被编入，此次作战博士吃不下了导致任务失败 (／‵口′)／~ ╧╧

**Comment by et2012** [comment]
> > 芙蓉(80)和安塞尔(100)的招募优先级是远远大于预备干员(5)的，基本上能用上的三星干员都写了优先级的。 毕竟三星白拿，比预备好，没理由不拿的。如果不拿三星而是拿了预备干员，看看是不是等级太低，拉到精一50以上。
> 
> 举个例子： 博士在一局肉鸽的第一层招募了一个预备术师干员，在该局中陆续招募了共计9名干员，其中包含精一55级的安赛尔，此外没有招募其他医疗干员。在之后的一次作战中，因为只有8个携带位，MAA在试图编入第9名干员时因为编队上限无法编入，此时进入快速编队界面重新编队。MAA选择了前8名干员，其中包含了之前招募的预备术师干员，而精一55级的安赛尔因为位于队列末尾没有被编入，此次作战博士吃不下了导致任务失败 (／‵口′)／~ ╧╧

被发牌员制裁（不出医疗券）先不说，都9名干员了，一个4星以上的医疗都没有吗？
水月肉鸽不比傀影肉鸽，三星撑不住场面的，还是得靠高星干员。

**Comment by RyanSaul** [comment]
> > > 芙蓉(80)和安塞尔(100)的招募优先级是远远大于预备干员(5)的，基本上能用上的三星干员都写了优先级的。 毕竟三星白拿，比预备好，没理由不拿的。如果不拿三星而是拿了预备干员，看看是不是等级太低，拉到精一50以上。
> > 
> > 
> > 举个例子： 博士在一局肉鸽的第一层招募了一个预备术师干员，在该局中陆续招募了共计9名干员，其中包含精一55级的安赛尔，此外没有招募其他医疗干员。在之后的一次作战中，因为只有8个携带位，MAA在试图编入第9名干员时因为编队上限无法编入，此时进入快速编队界面重新编队。MAA选择了前8名干员，其中包含了之前招募的预备术师干员，而精一55级的安赛尔因为位于队列末尾没有被编入，此次作战博士吃不下了导致任务失败 (／‵口′)／~ ╧╧
> 
> 被发牌员制裁（不出医疗券）先不说，都9名干员了，一个4星以上的医疗都没有吗？ 水月肉鸽不比傀影肉鸽，三星撑不住场面的，还是得靠高星干员。

在我的观察下十次中有两次出现这样的情况，这还是取长补短分队开局保底安赛尔。MAA的策略是尽量走不期而遇避战，可获取的招募券本来就有限，再加上八个职业，道中没有其他医疗券太常见了。我自己玩是很少会出现这种问题（还能抓其他有治疗能力的干员来弥补，同时也会尽量参与战斗获取资源），但MAA不一样。
不过我就是跟你们尽量描述清楚这个问题，不处理也行，采不采纳全看你们的意思~

**Comment by et2012** [comment]
采不采纳在于 MAA Team 有没有人愿意优化这个逻辑。
我只是建议你在优化做出来之前，暂时先用其他方式避免这种情况。
例如考虑使用以人为本+近卫医疗开局，挂机毕竟不是手打，用稳妥一点的方式比较好。

**Comment by RyanSaul** [comment]
> 采不采纳在于 MAA Team 有没有人愿意优化这个逻辑。 我只是建议你在优化做出来之前，暂时先用其他方式避免这种情况。 例如考虑使用以人为本+近卫医疗开局，挂机毕竟不是手打，用稳妥一点的方式比较好。

或许刚刚我说过了是在用以人为本+取长补短开局 23333

**Comment by MistEO** [comment]
做肉鸽算法的大佬最近比较忙，过段时间可能会优化一波，~~也可能咕咕~~
