### ISSUE TITLE
自动肉鸽：作战无法部署干员

### ISSUE THREAD

**Issue by MysteriousHeroineX** [MaaAssistantArknights/MaaAssistantArknights#2961]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

自动肉鸽模式，第一次任务完成后，后续任务第一关作战无法部署干员，导致战斗失败；同时按设定进行20次自动肉鸽停止后，当天设置的基建换班也没有执行？
MAA版本：4.8.0-alpha1

### 日志文件

[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10129953/asst.bak.zip)

### 截图

![image](https://user-images.githubusercontent.com/74663297/204984527-784a42d6-57ff-40b7-bfe0-3ceee3328900.png)

### 还有别的吗？

模拟器：蓝叠；平台版本号3.1.21.799，引擎版本号4.280.0.3001
操作系统：win10 21H2
配置：联想yoga 27一体机2021版；CPU：AMD Ryzen 5 4600H，16.0 GB RAM，显卡：AMD集显，512 MB显存

上次提交的相同bug（评论区）：https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2933
可能为同一原因引起的系统卡顿：
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2958

**Comment by MistEO** [comment]
兼容模式就是慢慢移动，电脑比较卡的时候移动太快会丢帧的。没啥好办法，升级电脑 or 就用兼容模式凑合（
