### ISSUE TITLE
宿舍换人卡主

### ISSUE THREAD

**Issue by daxiamigogo** [MaaAssistantArknights/MaaAssistantArknights#2965]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在宿舍状态下 有车尔尼和爱丽丝的情况下 不会自动识别已经有的车尔尼和爱丽丝  并且会拖到最右边并卡主重复拖动

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10131398/asst.log)

### 还有别的吗？

建议宿舍换人的时候（如果必须得有车尔尼和爱丽丝）优先进行撤掉所有人再进行更换

**Comment by thehuldra** [comment]
我也出现了“宿舍换人时，屏幕拖到最右边并重复拖动”这个bug，不过我这里好像是由于可选干员全是心情值满的造成的（勾选了宿舍空余位置蹭信赖，且有信赖值未满干员，但是直到卡在重复拖动时仍未做信赖值排序）

<img width="752" alt="截屏2023-04-07 下午6 00 17" src="https://user-images.githubusercontent.com/22200874/230595031-f9ca0e36-1705-42c8-b821-d844bfd32271.png">


<img width="813" alt="截屏2023-04-07 下午6 00 28" src="https://user-images.githubusercontent.com/22200874/230595309-fc32ff0e-4da6-4030-bc29-9bae050160c7.png">

https://user-images.githubusercontent.com/22200874/230595336-426c9bae-6c0d-432d-a56a-3cee1c1ebacc.mov
