### ISSUE TITLE
关闭后仍然驻留于内存中，任务管理器显示有10%的CPU占用

### ISSUE THREAD

**Issue by xxyz30** [MaaAssistantArknights/MaaAssistantArknights#297]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8287615/asst.log)
关闭后看任务管理器仍然有进程在活动，并有10%的CPU占用
偶然发现的这个BUG，但刚刚测试又没有这个问题
不知道是怎么触发的BUG。
![5UBVAYY4_C$ IU_GA2OQ@MR](https://user-images.githubusercontent.com/81208875/158835289-72d76fbb-4a4b-49cb-9182-ca96fb0f22b9.png)

**Comment by MistEO** [comment]
adb 卡住了，已有修复计划，预计 4.0 版本解决

**Comment by MistEO** [comment]
v3.1.0 fixed
