### ISSUE TITLE
仓库识别道具数量不正确

### ISSUE THREAD

**Issue by Black1312** [MaaAssistantArknights/MaaAssistantArknights#2971]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

仓库识别数量错误，maa：4.8 beta1，蓝叠国际版模拟器，win11

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10132543/asst.log)
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10132552/debug.zip)

### 截图

![QQ图片20221201205627](https://user-images.githubusercontent.com/64343218/205059665-3a99a734-4fdc-4050-b002-989aecc343dd.png)
![QQ图片20221201205710](https://user-images.githubusercontent.com/64343218/205059694-98fc0d3d-d574-44aa-9d69-eb4e43eb3567.png)
![QQ图片20221201205719](https://user
![QQ图片20221201205726](https://user-images.githubusercontent.com/64343218/205059755-e9afe2fe-0ad3-4b10-9e2d-50a0c6a63a0a.png)
-images.githubusercontent.com/64343218/205059734-c11672b0-4420-4505-890b-7970ee8cf9bb.png)

**Comment by MistEO** [comment]
fixed
