### ISSUE TITLE
外部组件发生异常，关闭窗口后软件退出

### ISSUE THREAD

**Issue by Iqgniy** [MaaAssistantArknights/MaaAssistantArknights#2972]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

外部组件发生异常，关闭窗口后软件退出。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10132772/asst.log)

### 截图

![Snipaste_2022-12-01_21-34-30](https://user-images.githubusercontent.com/45135587/205066466-a3e2ddb9-6890-4522-85ad-e03d4b022268.png)

### 还有别的吗？

Windows 10  20H2

**Comment by ABA2396** [comment]
换个非中文路径试试
