### ISSUE TITLE
提供的Python接口无法调用MAA

### ISSUE THREAD

**Issue by yokinanya** [MaaAssistantArknights/MaaAssistantArknights#2976]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

v4.8.0-alpha.1更新后，Python接口无法调用Maa
log是Alas的log

### 日志文件

[2022-12-02_maa.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10137831/2022-12-02_maa.txt)

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/205223827-ab409871-a1e1-47ca-9de0-8775c76e11d3.png)

我这里跑 python sample 没有问题，问下 ALAS 咋集成的吧 @LiamSho @SaiCateDoan

**Comment by yokinanya** [comment]
我去alas那边开个issue

**Comment by Shawnsdaddy** [comment]
解决了，谢谢

**Comment by MistEO** [comment]
或许 MAA python api 里可以加个 onnx 版本检查（？
