### ISSUE TITLE
关于肉鸽模式中部分极端情况下无法正常部署干员的问题

### ISSUE THREAD

**Issue by Aszlkm** [MaaAssistantArknights/MaaAssistantArknights#2977]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

在自动肉鸽情况下，处于部分极端情况下，MAA无法部署干员，但可以选中并移到正确的位置。目前无法主动复现bug，但已出现不止一次。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10137896/asst.log)

### 截图

[01.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10137898/01.zip)

本截图为手动演示操作，不为MAA运行时真实情况。MAA运行时，就停留在这一步，无进一步操作，且不取消部署。就会一直卡在这里。

### 还有别的吗？

MuMu模拟器，Win10.

**Comment by Aszlkm** [comment]
使用的是[v4.8.0-beta.2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.8.0-beta.2)版本

**Comment by Aszlkm** [comment]
今日再次出现此bug
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10150315/asst.log)
![MuMu20221205105414](https://user-images.githubusercontent.com/77436169/205539989-f40d6fb1-c06b-44ca-930c-8977c9401c95.png)

**Comment by MistEO** [comment]
内测版改了点，试试看
