### ISSUE TITLE
MAA提示“未知关卡”

### ISSUE THREAD

**Issue by DWin233** [MaaAssistantArknights/MaaAssistantArknights#2978]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

自动挂机刷活动关卡BI-8，MAA中提示“未知关卡，放弃上传企鹅物流”。

个人粗看了一下日志，其中的关卡编号写成了“Bl-8”（大写I->小写l），不知道是不是这个原因？

发现开发版中已更新修复。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10138093/asst.log)
2022-12-02 10:50开始

### 截图

![image](https://user-images.githubusercontent.com/60612754/205214797-dcc526d5-6ce0-48d0-a86b-14db98925774.png)

**Comment by ntgmc** [comment]
和这个没关系 要更新到开发版
