### ISSUE TITLE
4.8.0基建干员有时候会漏 特别是砾

### ISSUE THREAD

**Issue by WolfCanglong** [MaaAssistantArknights/MaaAssistantArknights#2979]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

4.8几个版本都有碰到 不算太频繁但是也有几次了 不知道是不是OCR的问题 比较常见的是砾和龙舌兰 砾特别容易漏
传的这个log是砾漏了放宿舍的 4.8.9 beta2
13:33:23 "红","清流","砾","车尔尼","流明"

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10138376/asst.zip)

**Comment by nightofknife** [comment]
检查为砾识别问题，识别结果为“砾陈”
等ocr改了应该就不会有这个问题了（

**Comment by MistEO** [comment]
fixed
