### ISSUE TITLE
希望增加功能可以保存窗口的屏幕和位置

### ISSUE THREAD

**Issue by superybq** [MaaAssistantArknights/MaaAssistantArknights#2980]
### 说说你遇到的问题？

我喜欢把窗口放在副屏的固定位置,现在每次重新打开都要重新拖一下位置

### 有什么好的想法？

能不能增加功能保存窗口所在的屏幕和位置.

**Comment by MistEO** [comment]
不知道咋写。其实你快捷方式在哪个屏，双击打开就是在哪个屏的

**Comment by moomiji** [comment]
win11显示设置的`多显示器`有个`基于显示器连接记住窗口位置`的功能，符合你的需求
