### ISSUE TITLE
m1 mac 12.6.1 编译碰到错误

### ISSUE THREAD

**Issue by LinSHP** [MaaAssistantArknights/MaaAssistantArknights#2981]
### 说说你遇到的问题？

参考CI编译碰到问题：https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/.github/workflows/dev-build-mac.yml

在最后link的时候
<img width="1383" alt="截屏2022-12-02 19 38 24" src="https://user-images.githubusercontent.com/19932215/205284610-a5f3753e-98f2-4feb-b8e8-c7175bdff39f.png">

**Comment by horror-proton** [comment]
0db99775c722829e485e6d6f49ea5088a8087a66 后暂时还没有支持 macOS, 可以编译 1fbcf09ef45dc7508e55a552337fe15709839950 版本.
@hguandl 已经在搞了

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/205299101-8a7da4c9-dca5-4f74-ab4b-6bd71bbb1b4f.png)

**Comment by MistEO** [comment]
> [0db9977](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/0db99775c722829e485e6d6f49ea5088a8087a66) 后暂时还没有支持 macOS, 可以编译 [1fbcf09](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1fbcf09ef45dc7508e55a552337fe15709839950) 版本. @hguandl 已经在搞了

master 也不行，stable 那边才能编

**Comment by LinSHP** [comment]
明白了，谢谢～
