### ISSUE TITLE
增加模拟器多Instance支持

### ISSUE THREAD

**Issue by fishjump** [MaaAssistantArknights/MaaAssistantArknights#2984]
### 说说你遇到的问题？

有两个小号需要每天清体力，每次切换账号输入密码太麻烦，于是我创建了多个模拟器instance（hyperv蓝叠），但是这样MAA只能够连接到第一个instance，手动该配置切换到连接到别的instance也很麻烦。

### 有什么好的想法？

我阅读了代码，特别是ViewStatusStorage.cs的逻辑。一个尽可能控制影响的方法是为每个模拟器instance分配独立的gui.json，e.g., 想要使用instance1挂机则读取gui_instance1.json, instance2读取gui_instance2.json。或者把gui.json的根节点设为一个json数组，不同的模拟器instance分别存储为不同的数组元素。

不过我阅读了ViewStatusStorage.cs的存储逻辑，一个问题是，如果选择后者，我们同时启动两个MAA且两个MAA都有变更时，后关闭的MAA会覆盖掉前者已经修改但是后者没有修改的配置。因此我觉得分别给每个模拟器instance写不同的配置是更合理的。

如果集成了这项功能，我的想法是在启动时开启一个弹窗要求用户选择他们想要加载的配置，并且我们维护另一个json,例如叫做instances.json,记录所有用户创建的instance。

如果开发组觉得这项功能可以开发，我可以来做这个功能。

**Comment by fishjump** [comment]
btw，一个workaround是复制一份MAA，但是感觉怪怪的，还是把这个功能做进软件比较好

**Comment by MistEO** [comment]
能帮忙写就太好了！其实开发组没有一个人正儿八经会写 c#，基本都是边查边写 orz，所以很多功能死在了 gui 上

一些需求上的问题：
- 大部分人还是单账号，所以每次启动选择有点烦，能不能做到设置里切换？或者跟着一定的自定义规则自动切换。再或者简单点设置里有个 checkbox 勾选了才在启动时弹窗
- 其实终极方案是，直接多实例，core 原生就是为多实例设计的，即创建创建多个 AsstHandle 并支持同时运行。这个如果 gui 这边要支持的话有可能吗？

**Comment by fishjump** [comment]
@MistEO .Net这边有过几个WPF小项目的经验，但是我也不是很熟，主要还是在写C，可能我也需要花点时间研究一下。也许暂时可以根据配置文件来隐式启用多账号支持的功能。

**Comment by fishjump** [comment]
@MistEO 我看了一下AsstHandle是个什么类。我猜你的意思可能是多账户运行在同一个GUI上，通过实例化多个AsstInstance来隔离计算资源。如果这样做的话，可以在GUI某处加个切换账号的按钮就可以查看不同配置下任务执行的情况（也就是说不同账号的挂机任务都可以在后台执行）。我可以尝试一下，最近挺闲的。

**Comment by MistEO** [comment]
WIP: https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/3030

**Comment by KevinT3Hu** [comment]
还有一个更为简便的思路是通过读取命令行cmd来读取所加载的配置json文件，这样就只需要创建不同配置文件对应的多个快捷方式就可以，而且修改起来也很简单，事实上我自己已经做了一版下来（ https://github.com/KevinT3Hu/MaaAssistantArknights/commit/c991dab9bc4fc42b5a6814a9fee8949b45bb0566 ），目前个人使用体验也不错。然而缺点是对于不熟悉命令行操作的人或许比较麻烦？

**Comment by fishjump** [comment]
> 还有一个更为简便的思路是通过读取命令行cmd来读取所加载的配置json文件，这样就只需要创建不同配置文件对应的多个快捷方式就可以，而且修改起来也很简单，事实上我自己已经做了一版下来（ https://github.com/KevinT3Hu/MaaAssistantArknights/commit/c991dab9bc4fc42b5a6814a9fee8949b45bb0566 ），目前个人使用体验也不错。然而缺点是对于不熟悉命令行操作的人或许比较麻烦？

大佬好迅速😂😂，这两天还在外地，想着一月份回来做。

**Comment by infinity-M** [comment]
有没有可能把多个账号密码存在MAA里，然后MAA执行完一个循环后，退出当前账号，登录新账号，继续长草（bushi
