### ISSUE TITLE
肉鸽的暂停部署会导致任务卡死

### ISSUE THREAD

**Issue by qwerdvd** [MaaAssistantArknights/MaaAssistantArknights#2985]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

今天更新了内测版后使用自动肉鸽刷钱
发现在干员部署过程中会出现干员部署完成后才暂停的现象，导致肉鸽一直暂停（
好像是暂停慢了？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10145403/asst.log)

### 截图

录像：

https://user-images.githubusercontent.com/105906879/205418161-3b9cd23b-9d67-43b7-8e99-b9b94e199067.mp4

后面自己去火蓝之心手操了一把

https://user-images.githubusercontent.com/105906879/205418170-2a00bbcd-1dc5-4b59-aec5-68f30bcd90a4.mp4

### 还有别的吗？

蓝叠模拟器 
MAA版本：v4.8.0-beta.2.33.g571440b5

**Comment by MistEO** [comment]
试试抄作业功能也会这样吗？

**Comment by qwerdvd** [comment]
OF-1是可以的
但是去OF-7测试的时候就会卡住（

https://user-images.githubusercontent.com/105906879/205419671-d326df8b-53bf-4561-8ebe-e06575bde98d.mp4

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10145497/asst.log)

**Comment by xiaqunkai** [comment]
同遇到肉鸽卡死，一直在暂停，手动点开始之后也继续暂停，无法正常运行，我也是蓝叠国际版

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/9a54bb1809b240fa60bc5bd4028475d2a9995e8b fixed

**Comment by qwerdvd** [comment]
更新过后，肉鸽的自动暂停仍然会卡死（
