### ISSUE TITLE
建议收取好友线索可以只收需要的，并自动赠送线索

### ISSUE THREAD

**Issue by BiologyHazard** [MaaAssistantArknights/MaaAssistantArknights#2987]
### 说说你遇到的问题？

maa的各项功能都很满意！

### 有什么好的想法？

本人有5个小号给大号送线索，因此我希望增加一个可选项，可以在会客室收线索的时候只收缺的线索，如果没有缺的则收3个。
当前方案全部收取的缺点是在我不登小号送线索的那几天，收好友线索的30信用就收不到了。

同时我也希望可以增加一个可选项，自动赠送出所有自己的线索，因为每送一个自己的线索可以赚20信用嘛，拿自己的线索开party就浪费了。我都是只拿小号的线索开party的。

**Comment by ntgmc** [comment]
Be mentioned in #2783 and duplicate to it

**Comment by BiologyHazard** [comment]
如果还能自动登上小号送线索就好了，不过这个要实现的话配置起来大概比较复杂
