### ISSUE TITLE
基建换班找不到崖心

### ISSUE THREAD

**Issue by IVKylin** [MaaAssistantArknights/MaaAssistantArknights#2989]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

之前用还没问题的，最近几次更新之后基建换班开始找不到崖心了，然后那一间贸易站就直接被跳过了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10145866/asst.log)
今天中午的记录就有基建换班的部分。

### 截图

![image](https://user-images.githubusercontent.com/119723943/205428332-666be0b6-11a2-408d-bd51-fbec247693d1.png)

**Comment by ABA2396** [comment]
上面是不是adb断开连接然后提示重连了，这个滑的时候没用上minitouch，adb划飞了。测试版已经修了
