### ISSUE TITLE
无限刷肉鸽进去选干员的时候卡住不动，没有操作

### ISSUE THREAD

**Issue by Hwwpo** [MaaAssistantArknights/MaaAssistantArknights#299]
请
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8301675/asst.log)
附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ

**Comment by MistEO** [comment]
可以参考 [肉鸽自定义选人方法](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/167) 改一下自己的干员，默认的那几个干员好像你都没有（？也可能是没练，总之没识别到 orz

**Comment by ABA2396** [comment]
> 可以参考 [肉鸽自定义选人方法](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/167) 改一下自己的干员，默认的那几个干员好像你都没有（？也可能是没练，总之没识别到 orz

可以把3星备选干员除了系统给的预备干员都删了，预备干员都是精一满级，但很多人可能3星都没拉满，按现在这样很可能会招募到没练过的干员（如精0芙蓉），还不如预备干员划算_ (:3」∠)。

**Comment by MistEO** [comment]
> > 可以参考 [肉鸽自定义选人方法](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/167) 改一下自己的干员，默认的那几个干员好像你都没有（？也可能是没练，总之没识别到 orz
> 
> 可以把3星备选干员除了系统给的预备干员都删了，预备干员都是精一满级，但很多人可能3星都没拉满，按现在这样很可能会招募到没练过的干员（如精0芙蓉），还不如预备干员划算_ (:3」∠)。

马上就开放界面自定义了_(:з」∠)_
