### ISSUE TITLE
4.8.0beta2 日服肉鸽下了干员就暂停

### ISSUE THREAD

**Issue by Biga3** [MaaAssistantArknights/MaaAssistantArknights#2991]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

刚刚放一个干员就暂停 然后就不动了

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10146043/asst.zip)

**Comment by DoingDog** [comment]
国服出现同样的问题

**Comment by MistEO** [comment]
加了选项，现在默认是关的了。在性能比较差的电脑上这个功能暂时用不了，会出现一直暂停的问题
