### ISSUE TITLE
更新v4.8.0-beta.2-win-x64后自动更新检测到MaaRelease更新包导致重启后崩溃闪退

### ISSUE THREAD

**Issue by IT-amateur** [MaaAssistantArknights/MaaAssistantArknights#2995]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

本来是什么版本已经不清楚了，问题是这样的，MAA自动更新选择的是内测版，打开后自动检测到了更新，但是根据弹出来的消息，跳转到的却是MaaRelease项目的v4.8.0-beta.2.50.gec561e6a发布页面，很快就下载完了更新包，重启后报错找不到文件，再次打开都是闪退，然后MAA目录结构也都乱了。
重新手动下载完整的“MAA-v4.8.0-beta.2-win-x64”，在保留map文件夹或gui.json的前提下进行覆盖，启动后也是一样的问题
gui.log
```
2022/12/3 21:40:09 OnUnhandledException Error: System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   在 MeoAsstGui.VersionUpdateViewModel.CheckAndUpdateNow()
   在 MeoAsstGui.RootViewModel.OnViewLoaded()
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10146502/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10146503/gui.log)
[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10146538/gui.zip)

### 截图

![更新后报错](https://user-images.githubusercontent.com/49528044/205444044-79b5faf2-b26b-4640-bdf0-2db61054592b.png)
![MAA目录文件改变](https://user-images.githubusercontent.com/49528044/205444070-bc33a2b1-5a4f-4733-8be4-570f1d9380ad.png)
![gui_json](https://user-images.githubusercontent.com/49528044/205444329-ae874530-559d-4751-a21e-a076d2487d39.png)

### 还有别的吗？

蓝叠模拟器
MAA-v4.8.0-beta.2-win-x64

**Comment by iiSlash** [comment]
一样，我发现是桌面快捷方式的路径变成.old里的meoasstgui.exe打开会提示资源错误
然后我重新打开父目录里的MAA.exe是正常使用的
不知道是这次更新变的还是以前某次变的，以前都是正常成功更新

**Comment by MistEO** [comment]
因为 exe 改名了，小问题.jpg
