### ISSUE TITLE
能否在肉鸽策略中加入刷指路鳞的方案

### ISSUE THREAD

**Issue by kepler-wang** [MaaAssistantArknights/MaaAssistantArknights#2997]
### 说说你遇到的问题？

刷指路鳞很痛苦，即便采用刷源石锭方案也要盯着商店，很麻烦

### 有什么好的想法？

在肉鸽策略中添加刷指路鳞方案，分队采用物尽其用（骰子队）

**Comment by ntgmc** [comment]
duplicate of #2503
