### ISSUE TITLE
日服  beta最新版少量不期而遇关卡依然存在卡住不动的情况

### ISSUE THREAD

**Issue by Biga3** [MaaAssistantArknights/MaaAssistantArknights#2998]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

如题  时间在00：01：12之后

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10146885/asst.zip)
e

### 截图

![微信图片_20221204001453](https://user-images.githubusercontent.com/119690050/205450655-00cb2c6d-5659-4607-93ae-f13ce5edecc1.png)

### 还有别的吗？

无

**Comment by Biga3** [comment]
再次出现这个问题，疑似只会点第一个

**Comment by MistEO** [comment]
fixed
