### ISSUE TITLE
4.7.3稳定版傀影肉鸽无法放置干员问题

### ISSUE THREAD

**Issue by Iscream713** [MaaAssistantArknights/MaaAssistantArknights#3006]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

4.7.3稳定版，挂傀影肉鸽前几把正常，第三把或者第四把开始出现问题，进入战斗，等费用够了之后，只点选干员，但是不放置干员，直至关卡失败，重启模拟器和MAA后恢复正常，大概三四把后又出现同样问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10148078/asst.log)

### 截图

![205480119-9029c31e-8d16-4179-b13d-e936ea6c8ec2](https://user-images.githubusercontent.com/119780669/205480175-99b5ad22-dfc3-4a32-931c-e02d4e6df34f.png)

### 还有别的吗？

蓝叠国际版模拟器
WIN10系统，已关闭熄屏和系统休眠

**Comment by 1171642391** [comment]
这个我也遇到了，运行时间过长导致的，同时导致的问题还有内存被吃掉一大堆，关闭也没法释放，只能重启电脑

**Comment by Iscream713** [comment]
> 这个我也遇到了，运行时间过长导致的，同时导致的问题还有内存被吃掉一大堆，关闭也没法释放，只能重启电脑

我这边重启模拟器可以，但是只能挂三把左右，整体内存占用一直在70%左右，选择兼容模式不使用minitouch可以解决问题，看来问题出在minitouch上？

**Comment by MistEO** [comment]
试试内测版的 MaaTouch

**Comment by Iscream713** [comment]
> 试试内测版的 MaaTouch

已更新至4.8.0bata2版本，Maatouch还是不行，前四把正常，第五把到战斗节点就不会下干员了，其他节点都正常过
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10152598/asst.log)
17:05:00到17:05:48这里您可以看下吗

**Comment by cenfusheng** [comment]
怀疑当时版本的延迟参数过小导致，后续新版本又调整了新参数，现大部分用户可正常使用，如仍出现，可以自行在resource\tasks.json中增加BattleUseOper与BattleSwipeOper的四个延迟（delay）数值，（一般再加一半就够用了，实在不行加一倍）。
