### ISSUE TITLE
连接问题

### ISSUE THREAD

**Issue by MahiruSu** [MaaAssistantArknights/MaaAssistantArknights#3007]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

总是连接失败，只能手动启动模拟器。但启动后一直在主页没反应，然后点了左下的广告软件，最后报错停止。
原本昨天之前都用的mumu，好好的，昨天晚上就不能用了，不管强制替换adb还是卸载mumu或者maa都没用，今天就下了蓝叠，五点钟还能好好用，结果现在又不能用了。

### 日志文件

十点前的[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10148829/asst.log)
十点后新的[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10148843/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/49871236/205498034-5f88a4c0-ff17-4af7-8559-974034697ccc.png)
![image](https://user-images.githubusercontent.com/49871236/205498054-7403b627-7e16-45de-80f3-332c5d172aa2.png)

**Comment by kk1tsch** [comment]
我也遇到这个问题了，最近每次开蓝叠模拟器的时候，adb的连接地址的端口号都会变，要手动修改端口。

**Comment by MistEO** [comment]
> 我也遇到这个问题了，最近每次开蓝叠模拟器的时候，adb的连接地址的端口号都会变，要手动修改端口。

不是同一个问题，你这个问题看文档，按蓝叠 HyperV 的来

**Comment by MeteorStream** [comment]
> > 我也遇到这个问题了，最近每次开蓝叠模拟器的时候，adb的连接地址的端口号都会变，要手动修改端口。
> 
> 不是同一个问题，你这个问题看文档，按蓝叠 HyperV 的来

那请问大大，我这个问题应该怎么解决呢？我确认了下，当我手动打开模拟器和方舟之后，maa的所有运行都正常。也就是maa无法自动打开模拟器并启动舟游，那么定时启动也就无法生效，即便是管理员模式
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10152745/asst.log)

**Comment by ntgmc** [comment]
> > > 我也遇到这个问题了，最近每次开蓝叠模拟器的时候，adb的连接地址的端口号都会变，要手动修改端口。
> > 
> > 
> > 不是同一个问题，你这个问题看文档，按蓝叠 HyperV 的来
> 
> 那请问大大，我这个问题应该怎么解决呢？我确认了下，当我手动打开模拟器和方舟之后，maa的所有运行都正常。也就是maa无法自动打开模拟器并启动舟游，那么定时启动也就无法生效，即便是管理员模式 [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10152745/asst.log)

![image](https://user-images.githubusercontent.com/74061867/205784874-b3b558e7-2c7d-49cf-bfac-23754e6de31f.png)
![image](https://user-images.githubusercontent.com/74061867/205784955-f84eb72f-4971-4082-844f-0947e07d8ad4.png)

我这是内测版的位置 你的应该在启动设置

**Comment by Black1312** [comment]
maa无法启动模拟器吗？连接设置截图一下，或者搜一下群号786683995找筱竹说明一下问题，远程
