### ISSUE TITLE
更新到3.0.7后软件打开即闪退

### ISSUE THREAD

**Issue by vicasong** [MaaAssistantArknights/MaaAssistantArknights#301]
使用的雷神模拟器，但软件打开还没准备连接，出现主界面后一两秒即自动退出，无法使用。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8305843/asst.log)

**Comment by vicasong** [comment]
操作系统：win11
我尝试使用管理员身份运行，依旧无效

**Comment by MistEO** [comment]
自动更新的么？可能更的有问题，手动重新下载一下试试

**Comment by vicasong** [comment]
重新下载解决了
