### ISSUE TITLE
自定义基建换班中，希望能加入强制更改制造产品和贸易站谈判策略功能

### ISSUE THREAD

**Issue by mlyksuu** [MaaAssistantArknights/MaaAssistantArknights#3011]
### 说说你遇到的问题？

如题
比如我手工操作的情况下，会在金条组下班休息的间隙上搓玉组顶班。
虽然在排班表中能设置产物，但实际使用的时候，遇到和设定的产物不同的情况时，只会红字提示，不会强制更换。

### 有什么好的想法？

如果能加入强制更换那么懒狗如我就能完全撒手了（贸易站可以直接更改，制造站更改生产份数为1，再无人机加速一下，减少浪费，就更好了）

**Comment by Shawnsdaddy** [comment]
不好加，强行切换产物会损失部分产能。

比如说你赤金产了一半，切成源石，那就浪费了一半赤金

如果用无人机切的话，你得识别出具体哪个时间切换 （ 万一无人机不够呢？）

还得做无人机数量识别

**Comment by mlyksuu** [comment]
> 

贸易站切换不损失产能
懒狗不介意这个程度的制造站产能（体感也就20架无人机左右），希望能多个选择

**Comment by MistEO** [comment]
已经有了
