### ISSUE TITLE
宿舍换班时移出心情未满的干员

### ISSUE THREAD

**Issue by Zebartin** [MaaAssistantArknights/MaaAssistantArknights#3012]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [x] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

宿舍换班时，MAA已经点了某个心情未满的干员，然后又把她取消掉了。

使用的是自定义基建，但涉及到这个时间段的宿舍，只是简单的autofill。

勾选了“蹭信赖”和“不将已进驻的干员放入宿舍”的选项。

### 日志文件

时间在12-05 16:15左右，出现异常后没有进行其他任务。

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10152166/asst.log)

### 截图

以视频代替，宿舍3正常，宿舍4异常。

https://user-images.githubusercontent.com/16185081/205589396-318824ea-9dd2-442d-a952-46839b28ae78.mp4

### 还有别的吗？

模拟器是蓝叠5 hyper-v版 国际版

是通过隔壁ALAS来调用的，MAA本体版本是4.7.3

**Comment by chenzhenghuo** [comment]
出现了同样的问题
