### ISSUE TITLE
4.8.0bate3基建未点开干员列表，在订单界面不停滑动

### ISSUE THREAD

**Issue by WolfCanglong** [MaaAssistantArknights/MaaAssistantArknights#3017]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

贸易站，应该是漏点开干员吧，然后会在那边一直狂拖贸易站的订单
MaaTouch模式
就是16:55那段重复的 结果自然是这个贸易站漏换班 反正以前还真没遇到过这个情况漏点的
![屏幕截图 2022-12-07 165708](https://user-images.githubusercontent.com/40590525/206135211-0f71ae01-282b-440c-80fc-bebc995d4d01.png)

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10174427/asst.zip)

**Comment by ABA2396** [comment]
这个之前遇到过，大概就是点击的时候刚好有订单生成/干员满心情等需要联网的事件发生，产生了连接的提示，导致点了没用。应该再加个条件判断有没有进到干员列表里
