### ISSUE TITLE
1-7选关失败 (主线关卡选关

### ISSUE THREAD

**Issue by yc080713** [MaaAssistantArknights/MaaAssistantArknights#3018]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

使用maa在关卡选择时选择主线关卡
导航时滑动失败
试过1-7(手动输入和原先下拉列表)和10-16
活动关的导航没问题,其他功能也没问题
触控模式试过了MaaTouch和Minitouch,开启了暂停下干员

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10174567/asst.log)

### 截图

![Screenshot_2022 12 07_17 14 14 693](https://user-images.githubusercontent.com/92996760/206139141-b75ca338-566d-42f3-b771-51c949e4760e.png)
![image](https://user-images.githubusercontent.com/92996760/206139178-0e035667-241f-4122-a271-b530f8ce1651.png)
![Uploading image.png…]()

### 还有别的吗？

蓝叠国际版
win10 x64
i511400  3060ti 模拟器稳定60帧

**Comment by yc080713** [comment]
![image](https://user-images.githubusercontent.com/92996760/206139952-40382cb0-9000-4d20-b2b4-4c0d0b093a3b.png)
![image](https://user-images.githubusercontent.com/92996760/206139961-0216baa5-c379-477f-83ac-164c1f4a52ec.png)

**Comment by yc080713** [comment]
哦,maa版本是v4.8.0-beta.3

**Comment by ABA2396** [comment]
a57ff81e5e608e3dfac9181447f38c8dfa6ea1de fixed

不知道为啥拖动比原来快了，游戏没反应过来（？）

**Comment by ABA2396** [comment]
> 遇到同样的问题，手动拖到第一章才行

已经修了，等下次更新

**Comment by MistEO** [comment]
v4.8.0-beta.4 fixed
