### ISSUE TITLE
4.8.0 bate3刷图开启需要两次

### ISSUE THREAD

**Issue by spec123321** [MaaAssistantArknights/MaaAssistantArknights#3022]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

点击开始行动后大概率卡在干员选择页面，需要等待sleep完成后下一个taskchain再识别后才能开始。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10181802/asst.log)

### 截图

![MAA](https://user-images.githubusercontent.com/76810153/206349707-20592968-3cc3-4e38-8be0-c81fffd8c0e7.png)

**Comment by Snow-dash** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10199973/asst.log)
因这个bug停留在开始前页面时，手动点击开始按钮有概率maa报错“游戏崩溃”。具体在12月10日19:26:28，游戏停留在作战结束后的结算页面。模拟器是蓝叠国际版。

**Comment by MistEO** [comment]
@ABA2396 这个是不是修过了？

**Comment by ABA2396** [comment]
是的）
