### ISSUE TITLE
4.7.3 基建错点

### ISSUE THREAD

**Issue by masquevil** [MaaAssistantArknights/MaaAssistantArknights#3024]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

当宿舍配置 车尔尼+爱丽丝 时，自动填充，如果没有心情未满的干员，则这个宿舍选择的时候会出错，最终进驻3个人。
具体表现为：
1. 先选中车尔尼+爱丽丝
2. 连着点3个人，但第一个点的是1号位置的爱丽丝（或者车尔尼），从而导致这个人被从宿舍中移除
3. 这个 bug 在还有心情未满的干员时不会触发，仅在全员满心情的时候会触发

配置文件如下图：
![image](https://user-images.githubusercontent.com/3344691/206395806-a9700e5c-8246-4470-97b1-4eefcf70db70.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10183551/asst.log)
时间大约在 2022-12-08 12:30

### 还有别的吗？

windows，蓝叠5中国版

**Comment by Zebartin** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3012
