### ISSUE TITLE
4.7.3 自动肉鸽反复选中干员

### ISSUE THREAD

**Issue by Ti-gersh-ark** [MaaAssistantArknights/MaaAssistantArknights#3025]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

傀影肉鸽打到大盗当头
在下了山和蜜莓之后会不停选中蜜莓一段时间后取消选中

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10183789/asst.log)

注意到这个情况应该是16点四十多快五十分的时候
录屏时间是50分左右

### 截图

https://user-images.githubusercontent.com/50004283/206402580-3a0471c9-591c-4bb6-bd51-cbe29fba38ef.mp4

![2022-12-08 16-50-33 mp4_snapshot_00 01 587](https://user-images.githubusercontent.com/50004283/206403013-1ed6bcf0-5ae8-443c-ad25-cd622079121f.jpg)
![2022-12-08 16-50-33 mp4_snapshot_00 02 803](https://user-images.githubusercontent.com/50004283/206403022-3c5a1cac-50e8-4e52-8842-e734ca2ea624.jpg)

### 还有别的吗？

bluestacks 5（应该是国际版
win10
因为bluestacks没有自带录屏当时直接拿obs顺手录的，画质没调好

**Comment by ntgmc** [comment]
这关好像确实有点问题 ，只要是有蜜莓和山（或其他未知触发条件），maa就会按那两个位置部署，就会产生此bug

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/2869 fixed
