### ISSUE TITLE
4.8.0 beta3 启动报错 无法加载DLL"MaaCore.dll"：找不到指定的模块

### ISSUE THREAD

**Issue by FengYaHe** [MaaAssistantArknights/MaaAssistantArknights#3026]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

下载完MAA-v4.8.0-beta.3-win-x64.zip之后，解压在硬盘根目录下，双击MAA.exe，报错：无法加载DLL"MaaCore.dll"：找不到指定的模块。（异常来自 HRESULT:0x8007007E）  
关闭报错窗口后闪退。  
运行库已按照说明文档安装，尝试过删除重新下载、解压运行，但并未解决问题。4.7.3稳定版MAA使用正常，但是无法更新，点击检查更新按钮后直接弹窗检查更新失败

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10186106/gui.log)

### 截图

![image](https://user-images.githubusercontent.com/93574211/206467923-c3a45df3-24c7-49aa-b26c-16f5a17ef61a.png)
![image](https://user-images.githubusercontent.com/93574211/206468662-d364cc9c-2915-4b42-89d9-3ba148f05c80.png)

### 还有别的吗？

系统是win7 64位旗舰版，已安装c++和.net运行库  
报错详细信息：
   在 MaaWpfGui.VersionUpdateViewModel.AsstGetVersion()
   在 MaaWpfGui.VersionUpdateViewModel..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.RootViewModel.CheckAndUpdateNow()
   在 MaaWpfGui.RootViewModel.OnViewLoaded()
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MistEO** [comment]
看起来 fastdeploy 在 win7 或者某些 cpu 上存在兼容性问题，这个问题可能没有办法解决。。

**Comment by sysxfml** [comment]
> 看起来 fastdeploy 在 win7 或者某些 cpu 上存在兼容性问题，这个问题可能没有办法解决。。

在 Wn11 上遇到了同样的问题，CPU 是 13600K。

**Comment by FengYaHe** [comment]
> 

没有，只有一个gui.log

**Comment by FengYaHe** [comment]
> 有没有生成 gui.err.log？也发下看看

没有，只有一个gui.log

**Comment by Black1312** [comment]
我之前有让你安装运行库合集并重启吗？请在九群找筱竹，谢谢

**Comment by MistEO** [comment]
> > 看起来 fastdeploy 在 win7 或者某些 cpu 上存在兼容性问题，这个问题可能没有办法解决。。
> 
> 在 Wn11 上遇到了同样的问题，CPU 是 13600K。

那就不是兼容性问题了，确认下你的运行库等是不是没装全

**Comment by sysxfml** [comment]
> > > 看起来 fastdeploy 在 win7 或者某些 cpu 上存在兼容性问题，这个问题可能没有办法解决。。
> > 
> > 
> > 在 Wn11 上遇到了同样的问题，CPU 是 13600K。
> 
> 那就不是兼容性问题了，确认下你的运行库等是不是没装全

更新 4.8.0 beta4 以及正式版之后恢复正常了

**Comment by MistEO** [comment]
试试这个解压后放到 MAA 同目录下，运行 Sample.exe，能跑吗，有没有什么报错提示之类的

[Sample.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10242519/Sample.zip)

**Comment by FengYaHe** [comment]
> 试试这个解压后放到 MAA 同目录下，运行 Sample.exe，能跑吗，有没有什么报错提示之类的
> 
> [Sample.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10242519/Sample.zip)

我这边提示缺少
api-ms-win-core-libraryloader-l1-2-0.dll
api-ms-win-core-processtopology-obsolete-l1-1-0.dll
api-ms-win-core-shlwapi-legacy-l1-1-0.dll
api-ms-win-eventing-provider-l1-1-0.dll
api-ms_win_core_heap_l2_1_0.dll
全部dll文件下载并注册之后，运行报错
![Uploading image.png…]()

**Comment by MistEO** [comment]
在 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3083 跟进好了，两边一起回复太累了（）这边我先关了
