### ISSUE TITLE
水月肉鸽出现异常

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#3027]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

我在使用雷电模拟器挂MAA刷肉鸽模式时，遇到了问题。正常模式清理智下，雷电模拟器运行的很好，MAA也能正常刷材料。但是刷肉鸽的时候，雷电模拟器提交的内存（不是占用的内存）会越来越大，游戏画面也会逐渐卡顿，MAA会在某个时间无法从雷电模拟器获得截图，模拟器提交的内存超过物理内存加上虚拟内存上限之后，明日方舟会直接闪退。
我之所以怀疑是MAA的问题，是因为当游戏开始卡顿并且MAA无法获得截图时，这时如果停止使用MAA刷肉鸽，雷电模拟器提交的内存虽然不会显著减少，但是会立即停止卡顿，画面恢复正常。
同时我想问一下MAA对于肉鸽模式是否有所改变。上一次我使用MAA是在上个月（具体时间我忘了）刷完肉鸽等级，之后我就没有再使用MAA刷肉鸽了，清理智是一直正常的，我也一直在更新MAA，所以我不清楚是否是MAA对肉鸽的支持是否有一些更改导致了这些问题。（不过我也有从雷电模拟器4、安卓7版本换到了雷电模拟器9、安卓9版本）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10187305/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10187307/asst.bak.log)

### 截图

![屏幕截图 2022-12-08 230821](https://user-images.githubusercontent.com/92417243/206500119-8fa15a92-29ec-430b-a716-ab939b0fe752.jpg)

### 还有别的吗？

使用雷电模拟器9（安卓9）最新版，电脑系统是Windows11 22H2。电脑配置是CPU 9300H，显卡1650，内存16G。MAA版本是4.8.0beta3

**Comment by MistEO** [comment]
是雷电的问题，文档写的很清楚了，不要用雷电

**Comment by MistEO** [comment]
![Screenshot_2022-12-09-08-56-13-982_com.github.android.png](https://user-images.githubusercontent.com/18511905/206598472-8aea6bb4-0aa2-411f-a127-6d2a198e5b52.png)

**Comment by MistEO** [comment]
补充一下，正常来说，一个不进行 hook 的软件（MAA）是没有能力让另一个软件（雷电）内存泄漏的，内存泄漏只可能是其本身的问题。

只不过触发条件不同，即手动操作无法触发雷电的内存泄漏，而 adb 在某种操作下可以触发。

但内存泄漏说到底终归是雷电的问题，靠 MAA 没有办法解决。还是推荐更换模拟器，如果一定要使用雷电，最好去给雷电官方提 bug

**Comment by xiaoweiXX** [comment]
> 补充一下，正常来说，一个不进行 hook 的软件（MAA）是没有能力让另一个软件（雷电）内存泄漏的，内存泄漏只可能是其本身的问题。
> 
> 只不过触发条件不同，即手动操作无法触发雷电的内存泄漏，而 adb 在某种操作下可以触发。
> 
> 但内存泄漏说到底终归是雷电的问题，靠 MAA 没有办法解决。还是推荐更换模拟器，如果一定要使用雷电，最好去给雷电官方提 bug

我猜是MAA图像识别打肉鸽的时候会不断截图导致的这个问题，普通的清理智并不会大量截图，所以就没有这个问题。另外我觉得雷电模拟器比较好用，这个模拟器支持120帧，哪怕显示器不支持也会比原生60帧感觉要流程（貌似FPS游戏也是这样）。我用过mumu模拟器，用久了会有莫名的卡顿，原因未知。
