### ISSUE TITLE
肉鸽开局自动放弃招募

### ISSUE THREAD

**Issue by Tapir-XII** [MaaAssistantArknights/MaaAssistantArknights#3029]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

肉鸽开局在稳定打层数的模式下，包括预先指定干员在内随机放弃招募，数量在一名以上，原因未知，也不知道是否会全部放弃，两个肉鸽都会出现这种情况。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10192773/asst.log)

**Comment by Tapir-XII** [comment]
更新到4.8.0-beta.3后，兼容模式下开局会卡在放弃招募的确认选项这里，不再做任何操作。手动取消放弃招募后也会重复选择放弃招募。
![Uploading image.png…]()

**Comment by Tapir-XII** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10201730/asst.log)
![image](https://user-images.githubusercontent.com/76720902/206893922-dbd422df-7723-4819-9d19-6c8786dede95.png)

**Comment by horror-proton** [comment]
看上去 MAA 在点击狙击招募后没找到 ![](https://raw.githubusercontent.com/MaaAssistantArknights/MaaAssistantArknights/master/resource/template/RoguelikeRecruitOcrFlag.png)

**Comment by Tapir-XII** [comment]
放弃招募是随机的，数量在一名以上，包括事先在设置中选定的干员。
前两天通过数次清理模拟器内存和重新启动能够解决，但这两天不行了。有解决方法嘛？

**Comment by horror-proton** [comment]
能看下软件目录的 `debug` 文件夹里面有没有对应时间的截图吗

**Comment by Tapir-XII** [comment]
![image](https://user-images.githubusercontent.com/76720902/207008640-3df9f721-72f9-4fb9-bb6d-c9ddb5c08dd2.png)
可能是有...但几乎全部是黑屏，有画面的都是正常的招募界面

**Comment by MistEO** [comment]
@Tapir-XII 打包发一下吧~

**Comment by Tapir-XII** [comment]
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10206913/debug.zip)

**Comment by MistEO** [comment]
mumu9 截图似乎有点问题，那些黑的图都是截屏错误了，最好换个模拟器试试

![image](https://user-images.githubusercontent.com/18511905/207637567-9494e469-ea07-44af-9d7e-90a91d51c30d.png)

**Comment by Tapir-XII** [comment]
我已经换了两个模拟器了…这是第三个。
雷神（雷电的）是abd永远配置不正确，蓝叠则是永远在卡我的鼠标…

**Comment by MistEO** [comment]
咋尽挑不支持的模拟器试。。看文档（
