### ISSUE TITLE
虚空公招

### ISSUE THREAD

**Issue by guojunyu196** [MaaAssistantArknights/MaaAssistantArknights#303]
![BS_PIC_2022-03-20-09-01-15](https://user-images.githubusercontent.com/76220347/159143634-84bbbb7c-4c1c-458f-ac10-2cb0f67660a9.png)
![uTools_1647738096712](https://user-images.githubusercontent.com/76220347/159143637-a3ddecf6-89e1-45f0-875e-9bfaedb5a938.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8310421/asst.log)
貌似每次公招确认时都点到叉了

**Comment by MistEO** [comment]
康康你的设置里，是不是没勾选 `自动确认 3 星`

**Comment by guojunyu196** [comment]
以前会不选择任何tag然后公招，个人觉得只要不是四星就没必要点tag吧，有点浪费龙门币orz

**Comment by MistEO** [comment]
> 以前没勾选自动确认三星会不选择任何tag然后公招，个人觉得只要不是四星就没必要点tag吧，有点浪费龙门币orz

不是的，设置里是点确认_(:з」∠)_不是点 Tag, 三星就是不会点 Tag 的

**Comment by MistEO** [comment]
这个选项主要目的是，有人招募券不多，三星就不招募了，只招募四星的

**Comment by guojunyu196** [comment]
啊这，那好奇怪，我从3.0版本以来都没勾选过这个选项，今天才出问题_(:з」∠)_

**Comment by MistEO** [comment]
没问题我关咯 (*´▽｀)ノノ
