### ISSUE TITLE
（日服）一键长草，自动肉鸽经常卡在不期而遇

### ISSUE THREAD

**Issue by UtsugShinobu** [MaaAssistantArknights/MaaAssistantArknights#3031]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

日服经常卡在30层的不期而遇，会卡在不期而遇和遭遇之间,如截图所示大概卡在12/9号17：32

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10193970/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/120177603/206684347-c9b4514a-8e97-4342-b9f5-02e89992543d.png)
![Uploading image.png…]()

**Comment by UtsugShinobu** [comment]
![MuMu20221209184643](https://user-images.githubusercontent.com/120177603/206685292-33b5b045-a354-4325-b094-51127fe2cd83.png)

**Comment by MistEO** [comment]
你发的日志打不开，网页 403 了，不知道为啥，下次遇到的话再传下看看

**Comment by UtsugShinobu** [comment]
好的

**Comment by UtsugShinobu** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10251007/asst.log)

**Comment by UtsugShinobu** [comment]
12/17 13:47:05 开始出现问题
