### ISSUE TITLE
自动借助战打of-1出错

### ISSUE THREAD

**Issue by LinYanxi0** [MaaAssistantArknights/MaaAssistantArknights#3034]
在借干员时会卡住
手动点了一个后在选先锋页面再一次卡住
选定后反复左滑而不继续
![MuMu20221209234722](https://user-images.githubusercontent.com/117924884/206740502-c0b77295-f456-4ed7-94da-ab2a47da98fc.png)

**Comment by LinYanxi0** [comment]
漏了日志
![图片](https://user-images.githubusercontent.com/117924884/206746596-ebb146f6-a4d9-40fd-8355-741d437f4061.png)

![图片](https://user-images.githubusercontent.com/117924884/206746540-6781a3fb-c935-43a6-887e-ffe9b19c3eb8.png)

![图片](https://user-images.githubusercontent.com/117924884/206746098-38f4ba89-b046-4ec8-8d2d-5c1b2896a05c.png)

![图片](https://user-images.githubusercontent.com/117924884/206745928-c0ef9cbd-0b00-4e4d-a235-2dfa913f2648.png)

**Comment by LinYanxi0** [comment]
12-9 23:41左右始
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10199705/asst.log)
另外辛苦了，感谢~

**Comment by ABA2396** [comment]
> 12-9 23:41左右始 [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10199705/asst.log) 另外辛苦了，感谢~

日志被刷掉了，发一下asst.bak.log

**Comment by LinYanxi0** [comment]
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10200201/asst.bak.log)

**Comment by Black1312** [comment]
请全部删除MAA文件，确保吗模拟器分辨率为16：9，如果问题仍然存在，请再次提交issue，谢谢

**Comment by Black1312** [comment]
请全部删除MAA文件，下载新版重新解压。确保模拟器分辨率为16：9，如果问题仍然存在，请再次提交issue，谢谢
