### ISSUE TITLE
建议在连接模拟器成功之前对“停止”按钮不可用

### ISSUE THREAD

**Issue by gingerbreap** [MaaAssistantArknights/MaaAssistantArknights#3037]
### 说说你遇到的问题？

在打开MAA后点击"Link Start!"到连接模拟器成功期间，点击“停止”后，再次点击"Link Start!"可能出现未知错误，再次尝试点击停止则会卡在“停止中”的状态，无法进行任何操作，必须重启MAA。

### 有什么好的想法？

建议在初次连接模拟器成功之前禁用“停止”按钮。

### 其他内容

![Snipaste_2022-12-10_15-01-21](https://user-images.githubusercontent.com/27958821/206836630-eef1dcc7-d254-465c-b6b7-9019d30101fc.png)
![Snipaste_2022-12-10_15-01-43](https://user-images.githubusercontent.com/27958821/206836632-da9e45af-7b89-4d57-87ca-0ac4f4cde698.png)

**Comment by 134820134820** [comment]
> ### 说说你遇到的问题？
> 在打开MAA后点击"Link Start!"到连接模拟器成功期间，点击“停止”后，再次点击"Link Start!"可能出现未知错误，再次尝试点击停止则会卡在“停止中”的状态，无法进行任何操作，必须重启MAA。
> 
> ### 有什么好的想法？
> 建议在初次连接模拟器成功之前禁用“停止”按钮。
> 
> ### 其他内容
> ![Snipaste_2022-12-10_15-01-21](https://user-images.githubusercontent.com/27958821/206836630-eef1dcc7-d254-465c-b6b7-9019d30101fc.png) ![Snipaste_2022-12-10_15-01-43](https://user-images.githubusercontent.com/27958821/206836632-da9e45af-7b89-4d57-87ca-0ac4f4cde698.png)

那像我有时候就是要直接改设置想停止不想启动模拟器怎么办
我们没有解决未知问题，但是不去碰它就能跑.jpg
