### ISSUE TITLE
sample.py运行报错

### ISSUE THREAD

**Issue by hjhjfhjhujhh** [MaaAssistantArknights/MaaAssistantArknights#304]
下载了[MaaAssistantArknights](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/dev)/[src](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/dev/src)/[Python](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/dev/src/Python) 里的[asst.py](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/src/Python/asst.py)和[sample.py](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/src/Python/sample.py)，扔进了软件目录，直接运行会报错

> \>\>\>
= RESTART: C:\Users\hjhjfhjhujhh\Desktop\MeoAssistantArknights_v3.0.8\sample.py
Traceback (most recent call last):
  File "C:\Users\hjhjfhjhujhh\Desktop\MeoAssistantArknights_v3.0.8\sample.py", line 20, in \<module\>
    Asst.load(path=path)
  File "C:\Users\hjhjfhjhujhh\Desktop\MeoAssistantArknights_v3.0.8\asst.py", line 38, in load
    Asst.\_\_set_lib_properties()
  File "C:\Users\hjhjfhjhujhh\Desktop\MeoAssistantArknights_v3.0.8\asst.py", line 138, in \_\_set_lib_properties
    Asst.\_\_lib.AsstLoadResource.restype = ctypes.c_bool
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\ctypes\_\_init\_\_.py", line 377, in \_\_getattr\_\_
    func = self.\_\_getitem\_\_(name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\ctypes\_\_init\_\_.py", line 382, in \_\_getitem\_\_
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'AsstLoadResource' not found

在第20行的Asst.load(path=path)报错的，因为我直接放到软件目录，经过18行path: str = (pathlib.Path.cwd()).\_\_str\_\_()之后
此时path为'C:\\Users\\hjhjfhjhujhh\\Desktop\\MeoAssistantArknights_v3.0.8'
是这个目录不对吗？还是我缺少DLL？

**Comment by MistEO** [comment]
dev 分支完全改了，和现在的 master 不兼容。直接下载的 Release 的是 master 打包出来的 dll. 你可以尝试

- 自己编译 dev 的 dll
- 或者用 master 的 python 文件

**Comment by hjhjfhjhujhh** [comment]
> dev分支完全改了和现在的大师不改了。直接下载的发布是大师打包出来的dll。你可以尝试
> 
> * 自己编译 dev 的 dll
> * 或者用master的python文件

dll全编译一遍吗？

**Comment by MistEO** [comment]
[这里](https://github.com/MaaAssistantArknights/MaaRelease/releases) 也有一份 dev 分支下的 dll. 不过是金丝雀版本，我们还没怎么测试

**Comment by MistEO** [comment]
> > dev分支完全改了和现在的大师不改了。直接下载的发布是大师打包出来的dll。你可以尝试
> > 
> > * 自己编译 dev 的 dll
> > * 或者用master的python文件
> 
> dll全编译一遍吗？

直接打开 VS 工程即可（如果你装了 VS 的话），项目配置都是 ok 的，点一下就可以了

**Comment by hjhjfhjhujhh** [comment]
OK 我先试试

**Comment by hjhjfhjhujhh** [comment]
哦我原来是切错版本了...mater版本的[README.md](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/master#readme)里放的py接口链接的dev的啊

**Comment by MistEO** [comment]
> 哦我原来是切错版本了...mater版本的[README.md](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/master#readme)里放的py接口链接是dev的啊

好像是，忘记改了2333
