### ISSUE TITLE
水月肉鸽关卡识别错误

### ISSUE THREAD

**Issue by yuyf111** [MaaAssistantArknights/MaaAssistantArknights#3040]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

和板块老哥之前遇到的问题相同,多上传一份log,希望对开发者大大解决问题有帮助

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10199520/asst.log)

### 截图

![QQ图片20221210162528](https://user-images.githubusercontent.com/120033815/206841110-8e0e91ed-8629-40b5-9aad-a633d1512b24.png)

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/207633673-25feaf0a-d5d3-486a-b4c5-dda79edf90c6.png)

你的模拟器有持续很长一段时间截图全失败了，不知道为啥，可能是电脑太卡了（？）等截图成功的时候已经进入关卡了，所以没识别到

**Comment by yuyf111** [comment]
还真可能是卡了..那天同时开了好多软件,后来几天没出现识别错误了,
感谢解答
