### ISSUE TITLE
自定义基建排班制作器

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#3045]
### 说说你遇到的问题？

这个网页式制作器及其难用，不能按照心情换班；也不能提前预设好多组干员组合，在基建内干员心情不足时，按照优先度直接整组替换干员。

### 有什么好的想法？

增加按照干员剩余心情替换，比如剩余心情低于多少时，进行干员替换。
增加干员组合（不止有限的3组或多少组），预先为不同的基建设施预设好多组优先级不同的干员组合，在替换干员时，直接按优先度整组将干员替换入对应的基建设施内。
增加组合关联功能，比如制造站放入清流、温蒂、异客的时候，中枢关联排布森蚺，发电站关联排布医疗小车。再比如贸易站放入孑、银灰、崖心组合时，中枢关联放入灵知。关联功能也可以同时增加优先度，比如中枢放入整个彩虹小队之后，剩余可放置干员只剩下1个，如果遇到上述两组干员同时存在，可以调整中枢剩下这个干员的优先级。
按照缺少线索的种类，选择不同的会客室组合。

**Comment by MistEO** [comment]
你说的这些，把 “自定义基建” 关掉，就是了

**Comment by xiaoweiXX** [comment]
> 你说的这些，把 “自定义基建” 关掉，就是了，而且效率是全自动计算

MAA自带的基建排布我用过，感觉很差劲，所以我想自己编写一套规则，但是自定义基建的编写功能很难用。我在上面提到的这些是对那个网页式自定义基建排布的改进建议

**Comment by MistEO** [comment]
另外这个关联的逻辑太复杂了，不是想象的那么简单的。你画个具体到细节的流程图就明白这里面恐怖的工作量了

**Comment by MistEO** [comment]
因为 maa 不支持关联功能，所以不是网页的问题。maa 支持的网页上都有了

**Comment by xiaoweiXX** [comment]
> 因为 maa 不支持关联功能，所以不是网页的问题。maa 支持的网页上都有了

不支持关联功能其实不是特别重要

**Comment by xiaoweiXX** [comment]
> 因为 maa 不支持关联功能，所以不是网页的问题。maa 支持的网页上都有了

我说的网页缺少的是心情阈值问题

**Comment by Shawnsdaddy** [comment]
> > 因为 maa 不支持关联功能，所以不是网页的问题。maa 支持的网页上都有了
> 
> 我说的网页缺少的是心情阈值问题

你可以去隔壁[Mower ](https://github.com/Shawnsdaddy/arknights-mower/commits/4.8.0)试试，全自动换班，心情阈值都有。
就看玛丽什么时候合到maa来了。

**Comment by Black1312** [comment]
自定义排班不支持阈值检测，组合过少可以通过直接编写json解决，干员联动也可以通过编写json解决。

**Comment by xiaoweiXX** [comment]
> 自定义排班不支持阈值检测，组合过少可以通过直接编写json解决，干员联动也可以通过编写json解决。

有没有编写教程？

**Comment by xiaoweiXX** [comment]
> 我觉得半自动是没有意义的，要追求效率就完全自定义控制，想摆烂就用全自动。半自动效率一定没有完全自定义高，还得花甚至更多的时间去写配置

我重新描述一下我预设中自定义基建吧：

首先是预设：制造站和贸易站可以按用途（比如制造站的赤金、作战记录和合成玉）预先设置好优先度不同的多种三人组合（组合数量不设上限，根据需求增减）

然后是换班：预设好心情阈值，低于某个阈值的设施，触发换班动作。首先清空该低心情干员所在的设施，接着在所有心情满的干员之中，按照优先度，把对应组合的干员放入。全部换班完成之后，就是将换下来的干员依次放入宿舍之中。最后再用掉无人机。

其他设想：
会客室：可以按照缺少的材料，无视优先度放入对应线索的干员（会客室就不一定是组合了），如果长时间还是缺少该线索，可以放入没有效率加成的对应组织的干员，并且在中枢中加入阿。
中枢：有整个彩虹小队的优先放入整个彩虹小队，剩下的干员位由玩家自己选择，基建换班功能可以跳过中枢，说白了就是不需要排班功能参与中枢（仅限于有整组彩虹小队的时候）
发电站（需要关联功能）：制造站放入温蒂、异客和清流的时候，发电站自动将心情最低的干员替换为医疗小车（或者发电站最后一个换班，在制造站换班的时候把小车先放入，之后发电站再自动换班），玩家可以提前一直将森蚺长时间放到基建中。

关联：如果能加入关联功能，自然最好；如果实在是难以实现，不加入也可以。
我想象中的关联功能实现是这样的：关联功能目前我预计能用到的只有两组，一组是制造站温蒂、异客和清流--中枢森蚺--发电站医疗小车，一组是贸易站孑、银灰和崖心--中枢灵知。这样的话，换班只需要按照顺序贸易站→制造站→发电站→中枢→其他→宿舍恢复心情。温蒂组合优先度高一点，所以放在后面，如果两次触发关联判定，温蒂组合就覆盖贸易站的关联判定。如果只有一组关联，就无需覆盖，直接关联就行。
如果有其他人有关联想法，就允许自定义换班顺序，然后触发多组关联时，后方的关联判定就覆盖掉前面的关联判定。后方的关联判定如果涉及到已经完成的换班，就自动失效。

**Comment by Black1312** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/3.6-%E5%9F%BA%E5%BB%BA%E6%8E%92%E7%8F%AD%E5%8D%8F%E8%AE%AE.md
我说的组合不是单独设置的组合，是整个基建的方案。关联是手动写死的。我更推荐你用某up的“极限效率”排班文件

**Comment by xiaoweiXX** [comment]
> 我觉得半自动是没有意义的，要追求效率就完全自定义控制，想摆烂就用全自动。半自动效率一定没有完全自定义高，还得花甚至更多的时间去写配置

你觉得我的想法怎么样？
