### ISSUE TITLE
国际服（EN）无法正常使用长草功能

### ISSUE THREAD

**Issue by kissnature** [MaaAssistantArknights/MaaAssistantArknights#3047]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

国际服（EN）中，已设置版本为国际服，使用的是蓝叠模拟器（也试过夜神模拟器）不过似乎并不能正常运行。分辨率已设置为1280*720，320dpi。
大部分功能无反应，有反应的：信用商店正常，访问好友则是会点进第一个好友随后退出；基建运行的时候会间或点进抽卡界面。
其他功能里，识别公招标签能正常使用，就是长草不能用不知道大大们有没有什么头绪？

### 日志文件

[asst-error.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10202538/asst-error.log)
进行了不同的尝试，全篇都是各种错误。

### 截图

![屏幕截图 2022-12-11 231241](https://user-images.githubusercontent.com/12200362/206912015-eda20dc2-0380-424a-a714-72ea0b385177.png)
![屏幕截图 2022-12-11 231407](https://user-images.githubusercontent.com/12200362/206912020-23d0a4cb-177a-4d94-8783-b5c5d34ee233.png)
![屏幕截图 2022-12-11 231424](https://user-images.githubusercontent.com/12200362/206912022-f204b04f-8e5b-46dc-bd3c-34daba2082e5.png)

### 还有别的吗？

操作系统是Win11 x64，除了自动识别模拟器和设置版本为国际服外没有动过别的设置。
无法运行后强制替换adb和兼容性触控模式都试过，不过并没有解决问题。
麻烦大佬们了～

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/resource/global/YoStarEN/readme.md

很多服适配都还没做好（我们需要更多外服的人手.jpg）

**Comment by kissnature** [comment]
感谢大佬链接，似乎文档里提到的刷理智和领日常奖励这种似乎我的情况下也无法正常执行。
（人手的话需要什么技能么？我可能只具备翻译技能。还是说需要提供一些EN服相关按钮的截图？）

**Comment by kissnature** [comment]
借了一个国服账号试了一下，完全没问题，别的设置没改，就客户端选成了国服。
看来可能确实是版本支持问题，不过我看 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2719 这帖说除了肉鸽选人别的基本正常，就不知道是不是自己这边的设置问题了。

**Comment by MistEO** [comment]
Team 的几位开发没人玩外服，基本是靠大家随缘 PR 出来的，有可能某次更新等之后不能用了也正常。

之后我们打算出个详细的外服适配教程，欢迎更多的朋友帮忙提交。一般只需要一些截图就行，仓库里有现成的工具，应该比较容易上手

**Comment by kissnature** [comment]
非常乐意贡献一点绵薄之力～目前还在搬砖，晚上我去仓库学习一下看需要如何截图提交。

**Comment by kissnature** [comment]
> > Team 的几位开发没人玩外服，基本是靠大家随缘 PR 出来的，有可能某次更新等之后不能用了也正常。
> > 之后我们打算出个详细的外服适配教程，欢迎更多的朋友帮忙提交。一般只需要一些截图就行，仓库里有现成的工具，应该比较容易上手
> 
> 教程的话我可以帮忙写一下，工具我也可以update一下

麻烦大佬了～

楼上提到的版本问题我今晚再试一下～

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/2.5-%E5%A4%96%E6%9C%8D%E9%80%82%E9%85%8D%E6%95%99%E7%A8%8B.md
