### ISSUE TITLE
关于MAA完成工作后自动关机的问题

### ISSUE THREAD

**Issue by 370356449** [MaaAssistantArknights/MaaAssistantArknights#3048]
### 说说你遇到的问题？

可以增加一个在完成后自动关机的常驻版吗，就是下次再启动MAA后还默认是完成后关机，现在是每使用一次需要重新选一次

### 有什么好的想法？

我个人因为电脑不常用，弄了插座定时通电开机，开机以后自动运行MAA，MAA帮忙开模拟器，
MAA完成作业后现在只能选【退出MAA和退出模拟器】，然后等退出之后无动作15分钟自动睡眠，
偶尔会出现中途跳出弹窗影响这个无动作睡眠的过程，然后电脑关不了，影响到下次开机运行MAA了

### 其他内容

本人又懒又傻，表达能力不太行，看不懂就无视退出吧
![QQ图片20221212012126](https://user-images.githubusercontent.com/45316559/206918665-bb4da7d7-f192-4db3-9bfd-e51a87e69e35.jpg)

**Comment by ntgmc** [comment]
[maa检测器.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10204318/maa.zip)

用易语言写了一个 写得不好请见谅（或自行修改或不使用）

**Comment by MistEO** [comment]
去掉不保存了，现在关机和休眠都会保存 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/18d367ee9e18fb67e240be13052bfc74cebc05de
