### ISSUE TITLE
清理智掉落识别错误

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#3049]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

使用MAA刷1-7，掉落识别会有问题，无法识别掉落。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10202883/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10202884/asst.bak.log)

### 截图

![2022-12-12_02-05-04 992_raw](https://user-images.githubusercontent.com/92417243/206921161-5ae8355a-79e7-476b-8a3f-ba8897a99156.png)
![2022-12-12_02-03-29 940_raw](https://user-images.githubusercontent.com/92417243/206921166-15a7aef7-8128-4c7b-a853-8b791c3314b0.png)
![屏幕截图 2022-12-12 021354](https://user-images.githubusercontent.com/92417243/206921213-c8038b2b-afc8-4983-8c4a-f92586990c15.jpg)

### 还有别的吗？

模拟器为雷电模拟器9.0.30，MAA版本为4.8.0beta3.40.g17d0973f，最新内测版

**Comment by xiaoweiXX** [comment]
复测了一下，在之前正常的雷电模拟器4.0.72也出现了无法识别掉落的情况

**Comment by xiaoweiXX** [comment]
> 刚发了480b4，试试新ocr

啊这，我已经退回到4.8.0B3了

**Comment by MistEO** [comment]
新版本试了吗，咋样？

**Comment by xiaoweiXX** [comment]
> 新版本试了吗，咋样？

没试，我为了稳定退回到4.8.0b3了，连带着模拟器都换回雷电4了
