### ISSUE TITLE
刷理智存在模拟器卡死的情况

### ISSUE THREAD

**Issue by This-is-Hehe** [MaaAssistantArknights/MaaAssistantArknights#305]
已多次复现，一般是打到第二局才会出现，偶尔第一局也会挂。卡死以后模拟器的HOME键和后退键也没有反应了，但是听声音后台还是在继续副本，最后强关模拟器以后理智也确实被扣除了。
（不排除是我的模拟器问题，比如核显带不动什么的）

![image](https://user-images.githubusercontent.com/51194325/159283664-7ce359f2-b878-4798-982d-d2a5d98a2b54.png)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8316239/asst.log)

**Comment by MistEO** [comment]
这种是蓝叠的 bug, 可以在蓝叠设置里面把渲染方式等等的改一改，可能会有用（但也不一定）

**Comment by This-is-Hehe** [comment]
> 这种是蓝叠的 bug, 可以在蓝叠设置里面把渲染方式等等的改一改，可能会有用（但也不一定）

问题已解决，感谢
