### ISSUE TITLE
水月肉鸽在进入不期而遇节点后大概率卡住一小段时间然后自动左上角退出重开

### ISSUE THREAD

**Issue by MashiroJL** [MaaAssistantArknights/MaaAssistantArknights#3051]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

最开始使用4.7.3版本的MAA并配合MUMU模拟器刷水月肉鸽，一开始使用尽量刷等级的方式，但是发现经常性/极大概率在进入任意不期而遇节点之后卡住几秒至十几秒不等，然后莫名其妙的自动退出放弃本次冒险。后来切换至刷源石锭，但是现象依旧存在。本人在确认无误所有肉鸽设置均无问题的情况下，换了蓝叠5模拟器，但是现象依旧存在，并且讲MAA版本升级至4.8.0之后也并无好转。猜测可能是因为进入节点之后操作过快，选项还没出来就已经点击了，然后游戏认为没有操作但是MAA认为操作点击之后没反应所以说卡住了然后重开？请朋友帮忙试着挂了一下，没有任何问题，模拟器也重新安装了，MAA也重新安装过，但是现象均无解决

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10204671/asst.log)

### 截图

[Uploading 新建文件夹.zip…]()

### 还有别的吗？

图片过多无法全部上传，但是全部无一例外都是如上传的图片一样，在某个不期而遇的节点莫名其妙的卡死然后重开

**Comment by MashiroJL** [comment]
[新建文件夹.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10204701/default.zip)

**Comment by MistEO** [comment]
你的问题 v4.8.0 修了，如果还遇到的话，发下 v4.8.0 的日志
