### ISSUE TITLE
无法点选战斗关卡

### ISSUE THREAD

**Issue by zzz8307** [MaaAssistantArknights/MaaAssistantArknights#3052]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

执行Fight任务能够进入对应的界面，但是无法选中对应关卡（例如刷红票5，MAA能进入粉碎防御，但无法选中AP-5），然后报任务出错并退出

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10208138/asst.log)
故障发生时间：2022-12-12 20:52, 20:57

### 截图

![Screenshot_2022 12 12_20 59 46 227](https://user-images.githubusercontent.com/25875214/207051267-ecab20da-c690-4032-8171-3ab98ad723cc.png)

### 还有别的吗？

模拟器版本：BlueStacks App Player 5.9.300.1014 N64
MAA版本：v4.8.0-beta.3
OS: Windows 11 Pro 22H2 22621.900

**Comment by MistEO** [comment]
v4.8.0-beta.4 fixed

**Comment by zzz8307** [comment]
更新rc和稳定版后又有这个问题了
