### ISSUE TITLE
自动基建异客组效率计算错误/识别错误

### ISSUE THREAD

**Issue by FrecklySoda** [MaaAssistantArknights/MaaAssistantArknights#3053]
### 说说你遇到的问题？

![image](https://user-images.githubusercontent.com/115042741/207070046-b561ae65-27e1-4860-ac0b-a26f39107a14.png)

### 有什么好的想法？

如图所示，异客组搭配承曦格雷伊的效率能达到1.2，即使在没有承曦格雷伊的情况下也能到1.0。但是软件只会把清流和另外两个30%效率的干员排在一起而不会选择异客和温蒂。如果能够优化一下，识别到同时有清流温蒂和异客/森蚺的时候就排到一个班那样排班的效率就更高了。

**Comment by MistEO** [comment]
做不了多设施联动，技术难度太大了，如果有需要可以用自定义换班

**Comment by MistEO** [comment]
那没上就是 bug，发下日志看看

**Comment by FrecklySoda** [comment]
> 那没上就是 bug，发下日志看看

![image](https://user-images.githubusercontent.com/115042741/207095324-c1cb2ff0-469c-42ef-8b86-838939f76a2f.png)
我现在在已经换好且心情够的情况下貌似程序就直接默认保持不变了，但一旦换下去之后温蒂和异客就再也不会被主动换上来了，和清流搭一组的基本就是斑点夜烟甚至是其他25%效率的干员了
