### ISSUE TITLE
v4.8-beta.4“剩余理智”功能导致卡死

### ISSUE THREAD

**Issue by drunkenQCat** [MaaAssistantArknights/MaaAssistantArknights#3056]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

今日出现问题时，我的指定刷理智任务是龙门币，剩余理智指定的是红票，之前几天一直没改，今天挂机也没有动：
![image](https://user-images.githubusercontent.com/39608175/207286493-db660398-d97e-419a-8acd-8f1fa9539b8a.png)

龙门币的任务完成之后，maa会跳转到剩余理智的任务。但是今天没开放红票关卡，maa会卡在选关的界面一动不动，直到手机锁屏，会一直提示“无法截图”，持续一个多小时，接着自动执行剩余任务，报错报错，然后停止。

在发现这个问题之后，我将“剩余理智”调整为“不选择”，所有任务正常运行了。
![image](https://user-images.githubusercontent.com/39608175/207288158-bd85a0d8-a320-42ff-bf31-a99aa4f71d96.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10216638/asst.log)

### 还有别的吗？

使用的是自己的荣耀畅玩6X，系统是安卓8.0。

**Comment by ABA2396** [comment]
剩余理智是不做任何判断直接刷完体力的，原意是让你设置常驻关如1-7、LS-6等关卡，设置未开放的当然会报错。你这种需求可以试试打开 设置-界面设置-使用备选关卡 ，按照 `关卡选择：龙门币` `备选：红票 红票` `剩余理智：不选择` 的方式设置

**Comment by drunkenQCat** [comment]
> 剩余理智是不做任何判断直接刷完体力的，原意是让你设置常驻关如1-7、LS-6等关卡，设置未开放的当然会报错。你这种需求可以试试打开 设置-界面设置-使用备选关卡 ，按照 `关卡选择：龙门币` `备选：红票 红票` `剩余理智：不选择` 的方式设置

多谢了。
