### ISSUE TITLE
增加一个每天刷一次剿灭的功能

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#3059]
### 说说你遇到的问题？

习惯性剿灭每天打一次来更好的完成每日击杀任务，但是很多时候直接挂刷理智忘记了手动。

### 有什么好的想法？

在设置中增加一个选项可以每日第一次刷理智时自动刷一次剿灭。

**Comment by WWPXX233** [comment]
你可以把指定次数改为1然后关卡选择为剿灭模式 剩余理智去刷别的

**Comment by kxdxzr** [comment]
但是指定次数的设置不保存啊
