### ISSUE TITLE
能否给信用商店随缘买加一个优先名单?

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaAssistantArknights#306]
就譬如公招票算比较重要的资源, 但是如果一个个买过去就可能没信用买了。如果用设置各种材料不买的方式就可能出现买完还剩很多要过期的情况。

**Comment by MistEO** [comment]
4.0 fixed https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/dca63426a6bcfefd8bed9b294095fd41c85ddc19
