### ISSUE TITLE
公招提示未更新（爆发仍显示五星tag

### ISSUE THREAD

**Issue by cenfusheng** [MaaAssistantArknights/MaaAssistantArknights#3062]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

![image](https://user-images.githubusercontent.com/52312717/207506336-211e6857-46f8-4380-bf6c-bf32dcfb5dbb.png)
不知道修了没，看更新内容里没有大概就是没有的（

### 日志文件

无

**Comment by ntgmc** [comment]
貌似不会？我这显示的4星 有可能是远程位+爆发或者狙击+爆发

**Comment by cenfusheng** [comment]
> 貌似不会？我这显示的4星 有可能是远程位+爆发或者狙击+爆发

超，很有道理，issue怎么关来着（
