### ISSUE TITLE
自动战斗支持跳过关卡中途剧情

### ISSUE THREAD

**Issue by yc080713** [MaaAssistantArknights/MaaAssistantArknights#3064]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

号第一次打7-10,使用自动战斗没法跳过关卡内的剧情
剧情是在开启二倍速操作后出现的
触控方式是MaaTouch,没开启暂停下干员

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10224820/asst.zip)

### 截图

![QQ截图20221214135517](https://user-images.githubusercontent.com/92996760/207518815-9443e359-aa1e-4142-8777-6d82714d7870.png)
![Screenshot_2022 12 14_13 53 58 333](https://user-images.githubusercontent.com/92996760/207518821-2cf249ea-930d-416b-a951-73dfbed791ca.png)

### 还有别的吗？

蓝叠模拟器
作业是maa://10719
maa版本是v4.8.0-beta.4.14.g10b9b9c1

**Comment by MistEO** [comment]
暂时没有战斗中跳剧情的功能，只能跳过战斗开始前的剧情
