### ISSUE TITLE
GUI: The displays overlap.

### ISSUE THREAD

**Issue by wallsman** [MaaAssistantArknights/MaaAssistantArknights#3065]
### The problems you have encountered?

中文正常
I thought it would be okay if I shifted it one step.
![image](https://user-images.githubusercontent.com/63186641/207557708-e9e878e6-0f5c-4353-8c8f-a01edba5edb5.png)
![image](https://user-images.githubusercontent.com/63186641/207557400-f7eda986-3156-4abd-bf48-b4a9a6060ca4.png)
![image](https://user-images.githubusercontent.com/63186641/207557437-38c9ad3c-8d90-4547-985a-e749d85c7200.png)
![image](https://user-images.githubusercontent.com/63186641/207558312-d43df931-0dd0-4237-bb85-eda63c39073e.png)

**Comment by ABA2396** [comment]
![FP9{W17@J~K29W8O3@MKE{1](https://user-images.githubusercontent.com/99072975/207627450-cf241fe4-9a5c-4c42-9eb8-b283708e319d.png)
![@~4GEZ`3J3ROTF20J(VURNB](https://user-images.githubusercontent.com/99072975/207627463-e31da965-e7bb-41bb-a35a-75b07af68177.png)
![4}9MB81AHY3E0R}THS(A% 2](https://user-images.githubusercontent.com/99072975/207627484-60fd023b-3854-45c5-8c93-79dd6f9ee9ef.png)
![P2G_)__QO H85N1ZK58LD4](https://user-images.githubusercontent.com/99072975/207627514-9dd8733a-2a62-4596-8b94-43669d01da93.png)

**Comment by MistEO** [comment]
This Japanese sentence is too long, can you shorten it? It is enough to express the basic meaning

**Comment by MistEO** [comment]
BTW, it's also a long Korean sentence. lol
