### ISSUE TITLE
宿舍换人划过头导致找不到人

### ISSUE THREAD

**Issue by Hakuchuu** [MaaAssistantArknights/MaaAssistantArknights#3069]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等

### 问题描述

宿舍换人时，有时要找的人在画面最右边只是被挡住了右边一部分但maa识别不到，而maa一滑人就跑到最左边且被挡住左边一部分，maa依旧识别不到，然后就错过了。。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10230179/asst.zip)
该情况已经出现过多次，最近一次是12月15日0点左右的一次，找不到图耶。

### 还有别的吗？

操作系统是Windows11，用的是雷电模拟器，连接使用“兼容性的触控模式（不使用minitouch）”（否则什么都做不了），连接配置使用过“雷电模拟器”和“MaaTouch”两种，都有这个问题。

**Comment by MistEO** [comment]
- 这个问题在兼容触控模式上不好解决，换开发版的 minitouch 或者 maatouch 试试
- （否则什么都做不了）——你需要强制替换一下 adb
- 建议不要用雷电，各种问题比较多
