### ISSUE TITLE
会客室未换班

### ISSUE THREAD

**Issue by hjhjfhjhujhh** [MaaAssistantArknights/MaaAssistantArknights#307]
非常诡异的问题，基建换班之后再看会客室是空着的，里面没有干员，线索也没收
问题不能复现，貌似是线索交流结束引起的
以前也出现过，可惜都没有截图
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8320501/asst.log)

**Comment by hjhjfhjhujhh** [comment]
可能空着的原因是宿舍换班换走了？但是会客室还是没轮班啊

**Comment by ABA2396** [comment]
会客室空的可能是你公招次数满了，建议把公招放在换基建前面试试，这样就不会导致人在会客室但不工作从而被放进宿舍

**Comment by MistEO** [comment]
> 会客室空的可能是你公招次数满了，建议把公招放在换基建前面试试，这样就不会导致人在会客室但不工作从而被放进宿舍

是会客室不是办公室（

**Comment by MistEO** [comment]
似乎没有识别到会客室，你的会客室是几级的，帮忙截个图康康

**Comment by hjhjfhjhujhh** [comment]
> 似乎没有识别到会客室，你的会客室是几级的，帮忙截个图康康

三级的啊
![image](https://user-images.githubusercontent.com/89215821/160096959-15b3439d-cf8d-4542-90cc-646c0d4a0080.png)

**Comment by MistEO** [comment]
有点怪，这个问题是必现么，每次都这样？

**Comment by hjhjfhjhujhh** [comment]
不是，偶尔，挺少见的

**Comment by MistEO** [comment]
`ffb3842036f3dc1a200829edf9ffecfec595f177` fixed
