### ISSUE TITLE
新版本关卡选择问题

### ISSUE THREAD

**Issue by tio-plato** [MaaAssistantArknights/MaaAssistantArknights#3077]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新4.8后关卡选择不是当期活动的FC系列，还是WE系列，并且提示关卡未开放。无法正常选择关卡。
![image](https://user-images.githubusercontent.com/60922756/207874156-8161e230-9f54-4c7d-ab19-a490a9410c08.png)
尝试删除maa从release重新下载最新版还是显示WE关卡

### 日志文件

无

**Comment by WWPXX233** [comment]
4.8.1修复了
