### ISSUE TITLE
模拟器识别错误问题

### ISSUE THREAD

**Issue by NAMEL1EE** [MaaAssistantArknights/MaaAssistantArknights#3078]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新完v4.8.1后在使用蓝叠模拟器的时候总是会打开蓝叠的多开管理器无法打开游戏本体，然后显示无法连接到模拟器

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10238191/asst.log)

**Comment by ABA2396** [comment]
那你去启动设置里设置下模拟器路径啊

**Comment by Black1312** [comment]
启动设置里面重新选择一下模拟器路径（HD-play.exe）
