### ISSUE TITLE
V4.8.1更新后一直连接失败

### ISSUE THREAD

**Issue by Coriander05** [MaaAssistantArknights/MaaAssistantArknights#3080]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用的夜神模拟器，更新前一切正常，更新完之后无法连接，重启过、设置过管理员模式启动也重新选择过ADB路径还是没办法

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10241429/asst.log)

### 截图

![QQ截图20221216073505](https://user-images.githubusercontent.com/109138784/207989101-50e6b0e2-78ef-4dad-981b-e6ab3ee00ec7.jpg)
![QQ截图20221216073459](https://user-images.githubusercontent.com/109138784/207989106-ff646a3c-b06d-49fd-9503-42db0408468a.jpg)

**Comment by ABA2396** [comment]
`adb: error: cannot stat 'F:\方舟脚本\resource\minitouch\x86\minitouch': No such file or directory`
你文件夹里有这个文件吗，没有的话重新下一下完整包

**Comment by Coriander05** [comment]
ok 已解决，谢谢
