### ISSUE TITLE
新下载4.8.0版本maa启动时报错 无法加载“maacore.dll”

### ISSUE THREAD

**Issue by xzjjasper** [MaaAssistantArknights/MaaAssistantArknights#3083]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

问题同 #3073  ，但提及的解决办法不适用（由于是新下载的package，所以并不是因为尝试打开.old文件夹内的exe时出现的错误），前一个issue已经被标记为invalid，所以新开issue反馈。
4.7.3及之前版本maa可正常运行，更新4.8.0后运行报错，尝试完全下载4.8.0新包仍然出现该情况，[其他人的回答](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3073#issuecomment-1353232486) 也汇报了相同问题。

### 日志文件

在 MaaWpfGui.VersionUpdateViewModel.AsstGetVersion()
在 MaaWpfGui.VersionUpdateViewModel..ctor(IContainer container, IWindowManager windowManager)
在 lambda_method(Closure , IRegistrationContext )
在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
在 StyletIoC.Internal.Container.Get[T](String key)
在 MaaWpfGui.RootViewModel.CheckAndUpdateNow()
在 MaaWpfGui.RootViewModel.OnViewLoaded()
在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
在 System.Windows.Interop.HwndTarget.OnResize()
在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 截图

<img width="1680" alt="207887465-ea49f831-d359-45e2-9385-11759d54c34b" src="https://user-images.githubusercontent.com/67013667/208005120-cee08643-b578-4038-aae9-ceb38c76b74d.png">

### 还有别的吗？

系统为Windows server 2012r2，已遵照 常见问题 中的指南下载所需组件（此前版本可正常运行）。

**Comment by WWPXX233** [comment]
#3073

**Comment by MistEO** [comment]
看起来和 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3026 是同一个问题，v4.8.x 更换了 OCR 库，可能产生新的依赖，感觉还是像某个运行库没装全，但目前并不知道要装啥 orz

**Comment by MistEO** [comment]
试试这个解压后放到 MAA 同目录下，运行 Sample.exe，能跑吗，有没有什么报错提示之类的

[Sample.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10242519/Sample.zip)

**Comment by xzjjasper** [comment]
<img width="1680" alt="截屏2022-12-16 12 34 30" src="https://user-images.githubusercontent.com/67013667/208022986-17ea53d2-b7e7-4ada-b7a6-8d798936ed51.png">

**Comment by xzjjasper** [comment]
![截屏2022-12-16 12 38 34](https://user-images.githubusercontent.com/67013667/208023439-296e7623-acce-420b-9874-bd9facf4a415.png)
尝试添加提到的dll文件到目录中，弹出新的报错

**Comment by hades0v0** [comment]
![4MO$81WQFRS~VT~GHZ67)EV](https://user-images.githubusercontent.com/91709507/208025306-f3808dc9-df29-47da-879a-f9525815c8b3.png)
![078M6{0@FQW~VFW$6H)6XNI](https://user-images.githubusercontent.com/91709507/208025317-4abe8f59-1b4d-435b-88a0-991aac566cc2.png)
和题主同一个原因，运行sample的结果不同，黏贴对应dll到maa文件夹再运行结果为图二

**Comment by Shawn88-ops** [comment]
跟题主同一个原因，运行sample结果不同，sample会弹出一个窗口但在不到0.5s内自动关闭，因此无法截图，不过没有报错显示

**Comment by MistEO** [comment]
如果是这样的话，按照 [这个方法](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#%E5%8F%AF%E8%83%BD%E6%80%A7-2--%E5%85%B6%E5%AE%83%E8%BF%90%E8%A1%8C%E5%BA%93%E9%97%AE%E9%A2%98) 应该是可以解决问题的，装了个大全集，但缺少的是啥暂时还不清楚

**Comment by MistEO** [comment]
> 跟题主同一个原因，运行sample结果不同，sample会弹出一个窗口但在不到0.5s内自动关闭，因此无法截图，不过没有报错显示

可以在 cmd 里运行下

**Comment by MistEO** [comment]
> 跟题主同一个原因，运行sample结果不同，sample会弹出一个窗口但在不到0.5s内自动关闭，因此无法截图，不过没有报错显示

那你遇到的问题可能是 [这个](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3073#issuecomment-1353044728)，我先 hide 了

**Comment by MistEO** [comment]
> 如果是这样的话，按照 [这个方法](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#%E5%8F%AF%E8%83%BD%E6%80%A7-2--%E5%85%B6%E5%AE%83%E8%BF%90%E8%A1%8C%E5%BA%93%E9%97%AE%E9%A2%98) 应该是可以解决问题的，装了个大全集，但缺少的是啥暂时还不清楚

按这个装个 VS 吧（

**Comment by xzjjasper** [comment]
<img width="1680" alt="截屏2022-12-16 19 21 44" src="https://user-images.githubusercontent.com/67013667/208087662-937bc6aa-ae3d-41f4-9dda-9cc5dd9caaa7.png">
<img width="1680" alt="截屏2022-12-16 19 21 56" src="https://user-images.githubusercontent.com/67013667/208087667-6bc1ef15-7c5a-427d-af82-ffe3d7c027c6.png">
默认安装项已经全装了还是不行···

**Comment by MistEO** [comment]
试试再勾上 “通用 windows 平台生成工具”

**Comment by cbuxfoobar** [comment]
同样的问题，但运行sample显示丢失MaaCore.dll

**Comment by MistEO** [comment]
> 同样的问题，但运行sample显示丢失MaaCore.dll

不是一个问题，你的问题是 exe 改名了

**Comment by cbuxfoobar** [comment]
> > 同样的问题，但运行sample显示丢失MaaCore.dll
> 
> 不是一个问题，你的问题是 exe 改名了

试过MAA改MeoAsstGui，同样报错无法加载maacore.dll

**Comment by xzjjasper** [comment]
磁盘空间不足……等待大佬发现原因了

**Comment by MistEO** [comment]
> > > 同样的问题，但运行sample显示丢失MaaCore.dll
> > 
> > 不是一个问题，你的问题是 exe 改名了
> 
> 试过MAA改MeoAsstGui，同样报错无法加载maacore.dll

我的意思是不要改名，重新拖一个快捷方式，参考置顶 Issue

**Comment by cbuxfoobar** [comment]
> > > > 同样的问题，但运行sample显示丢失MaaCore.dll
> > > 
> > > 
> > > 不是一个问题，你的问题是 exe 改名了
> > 
> > 
> > 试过MAA改MeoAsstGui，同样报错无法加载maacore.dll
> 
> 我的意思是不要改名，重新拖一个快捷方式，参考置顶 Issue

对MAA重新生成快捷方式吗，还是不行，而且我一直是在目录里点EXE用的，拖4.6.x的EXE过来就显示缺少MeoAssistant.dll。
不过算了，旧的自动战斗还能用就好

**Comment by MistEO** [comment]
再来uiui试试这个包，解压后放到 MAA 目录下

[win10rt.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10251704/win10rt.zip)

**Comment by MistEO** [comment]
原因找到了

- 如果是 win10 / win11 ，下载我上面发的那个包，把里面的 dll 放到和 maa.exe 同目录下再启动
- 如果是 win7, 8, vista, win server, 也可以试试这个包，但大概率没用。原因是 ONNX Runtime 需要 DX12 支持，win10 以下用不了 DX12。正在尝试解决，但也很有可能解决不了，MAA 可能要放弃对 win10 以下系统的支持了

**Comment by MistEO** [comment]
- 如果是 win10 / win11 ，请下载 [win10rt.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10251704/win10rt.zip)，把里面的 dll 放到和 MAA.exe 同目录下再启动
- 不支持 DX12 的系统（win7, 8, 8.1, vista, win server 等），但 CPU 支持 AVX2，请下载 [NoDX12 Patch  v4.8.1](https://ota.maa.plus/MaaAssistantArknights/MaaRelease/releases/download/v4.8.1/MAAPatch-NoDX12-v4.8.1.zip)，覆盖 MAA 目录下同名文件。但是这个每个版本都要重新打包，链接里是我本地打的，不知道能不能走 CI，可能也很麻烦，如果走不了只能也放弃支持了。等 @horror-proton 佬有空瞅瞅
- 不支持 DX12 的系统，CPU 也不支持 AVX2。也不是完全无解，但是太麻烦了，而且用户太少，放弃支持。请升级系统（v4.8.0 及之后的版本不需要 AVX2），或者用 v4.7.3 或之前的版本 + [NoAVX 补丁包](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/v4.7.3/3rdparty/ppocr_noavx.zip) 

即：

|  \  | Win10, 11 | Win7, 8, Vista, WinServer  |
|  ----  | ----  | ----  |
| AVX2 | [win10rt.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10251704/win10rt.zip) | [NoDX12 Patch v4.8.1](https://ota.maa.plus/MaaAssistantArknights/MaaRelease/releases/download/v4.8.1/MAAPatch-NoDX12-v4.8.1.zip)  |
| NoAVX2  | [win10rt.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10251704/win10rt.zip) | X |

**Comment by cbuxfoobar** [comment]
> * 如果是 win10 / win11 ，请下载 [win10rt.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10251704/win10rt.zip)，把里面的 dll 放到和 MAA.exe 同目录下再启动
> * 不支持 DX12 的系统（win7, 8, 8.1, vista, win server 等），但 CPU 支持 AVX2，请下载 [NoDX12 Patch  v4.8.1](https://ota.maa.plus/MaaAssistantArknights/MaaRelease/releases/download/v4.8.1/MAAPatch-NoDX12-v4.8.1.zip)，覆盖 MAA 目录下同名文件。但是这个每个版本都要重新打包，链接里是我本地打的，不知道能不能走 CI，可能也很麻烦，如果走不了只能也放弃支持了。等 @horror-proton 佬有空瞅瞅
> * 不支持 DX12 的系统，CPU 也不支持 AVX2。也不是完全无解，但是太麻烦了，而且用户太少，放弃支持。请升级系统，或者用 v4.7.3 或之前的版本 + [NoAVX 补丁包](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/v4.7.3/3rdparty/ppocr_noavx.zip)
> 
> 即：
> 
> \	Win10, 11	Win7, 8, Vista, WinServer
> AVX2	[win10rt.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10251704/win10rt.zip)	[NoDX12 Patch v4.8.1](https://ota.maa.plus/MaaAssistantArknights/MaaRelease/releases/download/v4.8.1/MAAPatch-NoDX12-v4.8.1.zip)
> NoAVX2	[win10rt.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10251704/win10rt.zip)	X

谢谢大佬，辛苦了，大势所趋,还是升级WIN10吧

**Comment by MistEO** [comment]
群里的大佬给出了一个新方案，可以尝试自己编一份不带 DX12 的 [onnxruntime](https://github.com/microsoft/onnxruntime)，MAA 用的是 v1.12.0，最好也用这个。有兴趣的可以自己尝试下，我开摆了（

**Comment by xzjjasper** [comment]
感谢Mist大佬！想请问下如果之后maa更新的话 NoDX12 Patch 里的文件是不是只有 MaaCore.dll 和 fastdeploy.dll 会更新替换啊，如果是这样的话是否可以这样，只打包这俩放在release里（只有大更新才有就足够了，感谢！），其他不需要每次更新的文件可以放在[常见问题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md)里，让有需求的人自取

**Comment by hades0v0** [comment]
感谢，解决了

**Comment by MinGW32-2006** [comment]
如果用Win10但显卡不支持DX12怎么办？

**Comment by stn924** [comment]
我是win11也確認過安裝了DX12，載了上述的檔案後也還是閃退。有甚麼方法可以解決呢?

**Comment by WWPXX233** [comment]
@stn924 会不会是你的显卡不支持dx12

**Comment by stn924** [comment]
![image](https://user-images.githubusercontent.com/121281015/209317332-60f1b6fd-5b93-483f-a30e-7b2cdc6ce73c.png)
@WWPXX233 應該是支持的

**Comment by MistEO** [comment]
新进展，直接替换这个 dll 即可。将在下个b版本集成到 release 包里


[onnxruntime.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10308501/onnxruntime.zip)

**Comment by MistEO** [comment]
v4.9.0-alpha.2 fixed
