### ISSUE TITLE
增加自动战斗跳过剧情开关

### ISSUE THREAD

**Issue by john180** [MaaAssistantArknights/MaaAssistantArknights#3087]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

自动战斗现在默认跳过剧情, 而且好像并没有相关开关设置
如果只想开剧情不想打关卡的情况下就比较麻烦, 得先看完剧情然后退出再自动战斗

### 有什么好的想法？

能否给自动战斗是否跳过剧情增加开关选项

**Comment by MistEO** [comment]
直接用剧情回顾怎么样？

![Screenshot_2022-12-16-22-26-00-122_com.hypergryph.arknights.jpg](https://user-images.githubusercontent.com/18511905/208119602-eee2e8ff-ca73-4712-a63b-07c26a6eada4.jpg)

**Comment by john180** [comment]
> 直接用剧情回顾怎么样？
> 
> ![Screenshot_2022-12-16-22-26-00-122_com.hypergryph.arknights.jpg](https://user-images.githubusercontent.com/18511905/208119602-eee2e8ff-ca73-4712-a63b-07c26a6eada4.jpg)
🤔主要是更新后这部分的运行逻辑和之前不一样, 一下子不太习惯.
用回看功能也完全ok, 感谢回复.
