### ISSUE TITLE
避免基建换班时把艾丽妮放进宿舍

### ISSUE THREAD

**Issue by Medbqwer** [MaaAssistantArknights/MaaAssistantArknights#3088]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

艾丽妮专二之后我用自动收菜，结果艾丽妮被放进宿舍，buff断了

### 有什么好的想法？

把干员放进宿舍时检测艾丽妮左上角有没有训练室标志

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/208092523-74b6df45-c52a-4b9f-bd91-f9a5748cd1e8.png)
