### ISSUE TITLE
无法连接WSA

### ISSUE THREAD

**Issue by 192345678Aa** [MaaAssistantArknights/MaaAssistantArknights#3091]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用官方文档对WSA连接的描述，可是无法连接
听群友说可能是配置的问题，放下我的配置
处理器:AMD Ryzen 7 4800H with Radeon Graphics 八核
主板:联想 LNVNB161216 ( 3830 )
内存:16GB 3200MHz ( 8GB + 8GB )
显卡:NVIDIA GeForce RTX 2060 ( 6GB / 17AA )
显示器:DELL S2721DGF [戴尔 DEL41DB] ( 27.2英寸 )
NV156FHM-NY4 [京东方 BOE08DF] ( 15.3英寸 )
硬盘:SKHynix_HFS512GD9TNI-L2A0B ( 512GB )
HP SSD EX900 120GB ( 120GB )
声卡:Realtek High Definition Audio
NVIDIA Virtual Audio Device (Wave Extensible) (WDM)
NVIDIA High Definition Audio
网卡:Realtek PCIe GbE Family Controller
Intel(R) Wi-Fi 6 AX200 160MHz
详细问题见截图所示

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10247326/asst.log)

### 截图

![屏幕截图_20221216_221611](https://user-images.githubusercontent.com/98321536/208141820-e4577742-a4ea-45c1-af2c-c31503655cbf.png)
![屏幕截图_20221216_221556](https://user-images.githubusercontent.com/98321536/208141830-57f39150-0669-475b-a3b4-d3e390e53a31.png)
![屏幕截图_20221217_001752](https://user-images.githubusercontent.com/98321536/208142360-604b6f94-4023-42ee-b46c-d2ea2a037d8f.png)
![屏幕截图_20221217_001759](https://user-images.githubusercontent.com/98321536/208142371-1806ddd8-1f32-47b4-aebd-65e4ae5f8c45.png)
![屏幕截图_20221217_001822](https://user-images.githubusercontent.com/98321536/208142380-efead7f3-3ea7-4c95-b662-3c3e5b6922b5.png)

### 还有别的吗？

WSA，版本2009
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.md
使用这个文档配置的

**Comment by MistEO** [comment]
看起来你的 WSA 没有办法支持 minitouch，试试 adb input

**Comment by 192345678Aa** [comment]
> 看起来你的 WSA 没有办法支持 minitouch，试试 adb input（兼容触控模式）

好的，可以连接了，顺便说一下，我调用了WSA的保持对开发应用的关注

**Comment by SiYuan-Y** [comment]
对了，建议添加黑夜模式，白色的控制面板和我系统的主题色很不搭配的

**Comment by SiYuan-Y** [comment]
1
