### ISSUE TITLE
FC-6有几率上传掉落失败

### ISSUE THREAD

**Issue by IranksAdral** [MaaAssistantArknights/MaaAssistantArknights#3093]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

FC-6结算的时候经常跳出失败不上传的错误提示，不过没自动截图，奇怪

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10250231/asst.log)

**Comment by ABA2396** [comment]
这个FC-6的C太圆了，识别成FO-6了，关卡名错了所以不报
