### ISSUE TITLE
连接失败，出现未知错误，正在停止

### ISSUE THREAD

**Issue by onlyacat** [MaaAssistantArknights/MaaAssistantArknights#3095]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最新版本 4.8.1 有这个问题，之前的 4.7.0 正常。

开始运行任务后直接报错。

之前是升级上来的，这次重装了一次，还是如此。

![image](https://user-images.githubusercontent.com/29370032/208219295-148f91ca-b0b6-4b54-83e6-faa2c2b17201.png)

### 日志文件

整个文件就是，重启之后设置了一下配置，直接跑就报错。

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10250580/asst.log)

**Comment by akiriroll** [comment]
我刚才刚好也在反馈类似的问题，你试一下把触控模式从minitouch改成其他兼容模式

**Comment by onlyacat** [comment]
> 我刚才刚好也在反馈类似的问题，你试一下把触控模式从minitouch改成其他兼容模式

是的，改完后能用了。

保留你那个 issue #3094  我这个先关了吧。
