### ISSUE TITLE
4.8.1 蓝叠 运行一项任务到下一项之间卡住

### ISSUE THREAD

**Issue by linbin9** [MaaAssistantArknights/MaaAssistantArknights#3096]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

截图和日志发了，在10:25:00 刷完理智后就卡住没切换任务执行公招，最新情况到了10:35:13开始公招，中间停了10分钟

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10250604/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/42168523/208219721-4cdc0698-d3d8-4731-89e0-964ba2d99ebf.png)

**Comment by akiriroll** [comment]
非模拟器，adb连接手机也发生同样问题，10：56完成招募之后，等待十分钟在11:06才执行下一个任务基建，基建结束后11:25分，执行商店，但等我发现的时候手机界面停在火蓝之心不动，检查发现没有完成商店的任务
![VOB}KW~TE8)WBFW D(S_(AT](https://user-images.githubusercontent.com/120661226/208221874-b1275a03-78a5-4832-96d2-0cde9ec6452d.png)
![)(WG)C{GLB94O_VNN%NA9 6](https://user-images.githubusercontent.com/120661226/208221868-5c3b15a7-ede0-4b46-8f77-12fa9da7193d.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10250668/asst.log)

**Comment by ABA2396** [comment]
> 非模拟器，adb连接手机也发生同样问题，10：56完成招募之后，等待十分钟在11:06才执行下一个任务基建，基建结束后11:25分，执行商店，但等我发现的时候手机界面停在火蓝之心不动，检查发现没有完成商店的任务 ![VOB}KW~TE8)WBFW D(S_(AT](https://user-images.githubusercontent.com/120661226/208221874-b1275a03-78a5-4832-96d2-0cde9ec6452d.png) ![)(WG)C{GLB94O_VNN%NA9 6](https://user-images.githubusercontent.com/120661226/208221868-5c3b15a7-ede0-4b46-8f77-12fa9da7193d.png) [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10250668/asst.log)

你没解锁火蓝之心，把这个关了
![image](https://user-images.githubusercontent.com/99072975/208230851-63a3e96d-778f-40b0-a11e-b025911bd035.png)
