### ISSUE TITLE
adb连接手机时，在关卡选择界面无法自动进入行动

### ISSUE THREAD

**Issue by Team-Fortuna** [MaaAssistantArknights/MaaAssistantArknights#31]
![Screenshot_20211102_020440_com hypergryph arknights](https://user-images.githubusercontent.com/33023256/139721023-fb0b8bd1-ca68-4097-a62d-7a330a6b440a.jpg)
adb有线连接手机时，无法在关卡选择界面自动进入行动。需要手动点击蓝色的开始行动之后，进入到干员选择界面才会自动点击橙色开始行动，无法连续刷材料

**Comment by Team-Fortuna** [comment]
体力不足时也无法自动磕药和碎石

**Comment by MistEO** [comment]
对宽屏的支持确实不太好，之后会专门优化的  

目前需要的话，`v1.2`及之后版本，可以把`resource\tasks.json`中，`StartButton1`的`roi`字段直接删了
`v1.1`版本是`StartButton1`的`identifyArea`字段

**Comment by Team-Fortuna** [comment]
huawei mate 20开低分辨率模式后，点击开始刷理智MeoAsstGui.exe主程序会闪退

**Comment by MistEO** [comment]
> huawei mate 20开低分辨率模式后，点击开始刷理智MeoAsstGui.exe主程序会闪退

最低支持的分辨率`1280x720`，再低是会有问题的

**Comment by Team-Fortuna** [comment]
分辨率是1496x720

**Comment by Team-Fortuna** [comment]
v1.3删除了resource\tasks.json中，StartButton1的roi字段后依然无法自动开始行动
![image](https://user-images.githubusercontent.com/33023256/139800818-dd16ccfa-87ad-44fc-adea-ecf828803f1a.png)

**Comment by MistEO** [comment]
看来宽屏还是问题比较多，我想简单了_(:з」∠)_之后会想办法优化下

**Comment by MistEO** [comment]
已兼容宽屏下的部分功能，请体验[v1.3.2](https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v1.3.2)版本

**Comment by MistEO** [comment]
请体验最新版本，除基建外，所有功能均已兼容宽屏_(:з」∠)_

**Comment by MistEO** [comment]
不打算进一步兼容宽屏了，工作量比较大，精力有限了 orz

宽屏只勉强保证能用，不进一步适配了_(:з」∠)_

**Comment by MistEO** [comment]
不打算进一步兼容宽屏了，工作量比较大，精力有限了 orz

宽屏只勉强保证能用，不进一步适配了_(:з」∠)_
