### ISSUE TITLE
异格干员在训练室专精，导致宿舍换班时程序崩溃？

### ISSUE THREAD

**Issue by YukimiNan** [MaaAssistantArknights/MaaAssistantArknights#310]
版本3.0.8
从前天开始一到宿舍就崩溃，窗口直接消失没有任何报错。今天突然意识到是这个水陈在专精的问题。（前天正好在精一，今天精三）
不管怎么把其他干员在宿舍里调来调去，只要列表里有这个训练中的老陈，就稳定复现崩溃。老陈结束训练就恢复正常了。

### 水陈在训练室时，崩溃前一瞬间的截图：
![水陈在训练室-游戏](https://user-images.githubusercontent.com/26034392/159657947-ab344a6a-47b7-4d7a-9869-8a7602da926f.png)
![水陈在训练室-助手](https://user-images.githubusercontent.com/26034392/159658012-4e5c55c1-d39b-4450-9605-42fd4b2632f8.png)

### 水陈移出训练室后，正常完成换班：
![水陈移出训练室-游戏](https://user-images.githubusercontent.com/26034392/159658026-7638d03e-4234-48f4-9c46-11ca55673d33.png)
![水陈移出训练室-助手](https://user-images.githubusercontent.com/26034392/159658036-a187a4c3-0314-4d9e-8d0d-81f2e2965d1a.png)

### log
[asst - 水陈在训练室，崩溃.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8331323/asst.-.log)
[asst - 水陈移出训练室，正常换班后手动停止.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8331324/asst.-.log)

**Comment by MistEO** [comment]
找群友借了下号，没借到水陈的，试了试异格蒂蒂复现不了这个问题。_(:з」∠)_

下次再有朋友有专精水陈的借个号试试orz

**Comment by ABA2396** [comment]
https://user-images.githubusercontent.com/99072975/180269950-ad355dfd-9e4e-40d6-88d9-2ad522864a26.mp4
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9161239/asst.log)
复现失败了）

**Comment by ABA2396** [comment]
Uploading bandicam 2022-07-22 01-00-36-799.x264.aac.mp4…
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9161306/asst.log)
3.0.8也没复现

**Comment by zzyyyl** [comment]
太久了，基建也改了好多了，close 吧
