### ISSUE TITLE
宿舍进驻错误

### ISSUE THREAD

**Issue by unersov** [MaaAssistantArknights/MaaAssistantArknights#3102]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在进驻宿舍的时候，勾选了自动填充和自动蹭信赖选项
如果未有心情未满并且未进驻的干员，则会按信赖倒序排序来蹭信赖，如果信赖未满干员不足以填满宿舍，那么会往右划来进驻为处于工作状态下的干员，也就是拥有宿舍技能的干员，这原本没什么问题
但是此时如果开始进驻下一个宿舍，那么选择界面仍然是信赖筛选，即信赖数值会挡住干员名称导致无法识别特定干员（如爱丽丝，车尔尼），会在识别完所有干员后跳过该干员的入驻

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10251682/asst.log)

**Comment by ABA2396** [comment]
那就把爱丽丝车尔尼都放第一个宿舍（）

**Comment by ltc-01** [comment]
这个bug好久了，我现在都是把杜林啊迷迭香组啊这些全放第一间宿舍来解决这个问题的233
