### ISSUE TITLE
一个训练室问题

### ISSUE THREAD

**Issue by XiaoTonghuan** [MaaAssistantArknights/MaaAssistantArknights#3103]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

似乎基建部分不能对训练室单独进行设置。我今天专苇草，maa把我小鸟给我撤了。

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/208245061-c2ea3d81-420f-4286-8e91-f34335200ae0.png)
