### ISSUE TITLE
FC-6刷理智失败，无法进入关卡，疑似拖动距离错误

### ISSUE THREAD

**Issue by CCCClaus** [MaaAssistantArknights/MaaAssistantArknights#3104]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷理智选择FC-6时，界面会拖动过头，导致无法选中FC-6；手动选择FC-6后能正常刷理智。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10251746/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10251747/asst.bak.log)
大致时间点如下方测试截图所示

### 截图

debug文件夹下无相关截图
<img width="1152" alt="QQ图片20221217205659" src="https://user-images.githubusercontent.com/116964544/208243290-aad6dcd0-e175-4f47-9ced-6c82ebb9f7fa.png">
<img width="1152" alt="QQ图片20221217205918" src="https://user-images.githubusercontent.com/116964544/208243307-4d37ab15-27ae-40e1-be7a-9c9d19568c12.png">

### 还有别的吗？

蓝叠模拟器
MAA v4.8.1

**Comment by ABA2396** [comment]
这咋滑一次就能滑这么远，你试试看手动拖一个屏幕的距离能划到这里吗？

**Comment by ABA2396** [comment]
最好来个录屏，我看日志里就划了一次就直接到头了

**Comment by CCCClaus** [comment]
> 
https://www.aliyundrive.com/s/8zCQNinhpfy 提取码：MAAA
最后面是使用minitouch显示拖动位置的情况和我手动拖动的情况，感觉确实滑动距离很远

**Comment by CCCClaus** [comment]
> 最好来个录屏，我看日志里就划了一次就直接到头了

https://www.aliyundrive.com/s/8zCQNinhpfy 提取码：MAAA
最后面是使用minitouch显示拖动位置的情况和我手动拖动的情况，感觉确实滑动距离很远

**Comment by CCCClaus** [comment]
> 这咋滑一次就能滑这么远，你试试看手动拖一个屏幕的距离能划到这里吗？

刚刚测试，之前正常的主线关卡刷取也出现一样的bug了，凡是需要左右滑动选关卡的都滑动太远导致选不上关卡。

**Comment by ABA2396** [comment]
我这里蓝叠设不了这么大的分辨率，你试试把分辨率设成 1280*720，dpi设成320看看还有没有问题，先确定下是不是分辨率引起的

**Comment by ABA2396** [comment]
确实是分辨率的问题，看来滑动的坐标不能直接按分辨率倍数缩放，得想想怎么改 @MistEO

**Comment by CCCClaus** [comment]
> 确实是分辨率的问题，看来滑动的坐标不能直接按分辨率倍数缩放，得想想怎么改 @MistEO

我刚刚测试，720p和1080p都没有问题，说明确实是分辨率的问题。
以及，我之前使用都没有出现过问题，一直都正常，是最近这次更新后才出了问题。
另：会不会是粥在这次更新之后更改了对拖动的判定？

**Comment by ABA2396** [comment]
> > 确实是分辨率的问题，看来滑动的坐标不能直接按分辨率倍数缩放，得想想怎么改 @MistEO
> 
> 我刚刚测试，720p和1080p都没有问题，说明确实是分辨率的问题。 以及，我之前使用都没有出现过问题，一直都正常，是最近这次更新后才出了问题。 另：会不会是粥在这次更新之后更改了对拖动的判定？

我记得之前版本有一个mumu也设了3840*2160划过头，但蓝叠没有，不太清楚这个是咋判定的

**Comment by CCCClaus** [comment]
> > > 确实是分辨率的问题，看来滑动的坐标不能直接按分辨率倍数缩放，得想想怎么改 @MistEO
> > 
> > 
> > 我刚刚测试，720p和1080p都没有问题，说明确实是分辨率的问题。 以及，我之前使用都没有出现过问题，一直都正常，是最近这次更新后才出了问题。 另：会不会是粥在这次更新之后更改了对拖动的判定？
> 
> 我记得之前版本有一个mumu也设了3840*2160划过头，但蓝叠没有，不太清楚这个是咋判定的

目前进一步测试了2560*1440，发现这时候一次拖动之后FC-6已经到视野边上了，FC-7已经出视野了，拖动距离超过了一个屏幕的距离，换言之分辨率越高一次拖动越远是成立的
目前能稳定一次拖动在一屏之内的是1080p
（如果你们不想改这种bug的话就算了，这bug我看着都觉得麻烦，要么你们直接在常见问题里备注不要超过1080p，毕竟也没什么人会在模拟器开4k分辨率）

**Comment by ABA2396** [comment]
我task里的坐标都是按照720p写的，maa的识图也是转成720p的坐标，这么看如果要确保不出问题还得限死1280*720，但如果说之前没问题这次更新之后出现了，说不定之后yj又改回去了x_x

**Comment by MistEO** [comment]
> 我task里的坐标都是按照720p写的，maa的识图也是转成720p的坐标，这么看如果要确保不出问题还得限死1280*720，但如果说之前没问题这次更新之后出现了，说不定之后yj又改回去了x_x

除了关卡滑动应该没这个问题

**Comment by ABA2396** [comment]
> > 我task里的坐标都是按照720p写的，maa的识图也是转成720p的坐标，这么看如果要确保不出问题还得限死1280*720，但如果说之前没问题这次更新之后出现了，说不定之后yj又改回去了x_x
> 
> 除了关卡滑动应该没这个问题

推荐用户用1280*720进行使用是吧.jpg

**Comment by MistEO** [comment]
不是，只有关卡那里滑动是有缩放的，比如你明明只滑了半屏，结果出去了一整屏，其他地方比如干员列表啥的，都是滑多少就走多少
