### ISSUE TITLE
操作执行非常慢

### ISSUE THREAD

**Issue by zlqd123** [MaaAssistantArknights/MaaAssistantArknights#3105]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

adb链接速度正常，但是每两步操作之间需要等待很长时间。
从更新minitouch后的两个测试版左右开始出现
重装maa、更换模拟器无效，
强制替换adb有效，但重启后失效，再次替换adb有效

### 日志文件

[Uploading asst.log…]()

### 还有别的吗？

win11 22H2
蓝叠国际版 安卓9 64bit

**Comment by zlqd123** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10251949/asst.log)
补充日志

**Comment by WWPXX233** [comment]
具体体现在运行什么任务时

**Comment by zlqd123** [comment]
> 
基本上每一步都很慢；
每次战斗结束几分钟才掉落统计，然后开始下次战斗又要几分钟；
基建更是慢中慢
我分析是每一次获取图片并识别都很慢

**Comment by WWPXX233** [comment]
你试试看不勾选开始唤醒重新进行一次

**Comment by zlqd123** [comment]
> 你试试看不勾选开始唤醒重新进行一次

这样不用替换adb也是正常速度了

**Comment by ALisstry** [comment]
这个bug可以通过更新蓝叠模拟器解决，我之前也出现过这个情况，去蓝叠官网下最新安装包更新模拟器就好了

**Comment by zlqd123** [comment]
> 这个bug可以通过更新蓝叠模拟器解决，我之前也出现过这个情况，去蓝叠官网下最新安装包更新模拟器就好了

以前更新不解决，这次解决了

**Comment by zlqd123** [comment]
方舟本次更新之后，蓝叠更新之前，不管是否勾选开始唤醒、替换adb，都非常慢。更新蓝叠后一切恢复正常，可以勾选开始唤醒
