### ISSUE TITLE
使用加速器（切换）加速其他游戏链接 会导致 连接失败 请检查连接设置

### ISSUE THREAD

**Issue by kkujukk** [MaaAssistantArknights/MaaAssistantArknights#3107]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

每次我使用 uu加速器等其他加速器 **切换游戏加速环境** 例如steam商店切换鹅鸭杀或其他游戏 只要存在切换过网络环境 maa就会**提示连接失败 请检查电脑设置或重新启动电脑** 
**只有重启电脑**启动模拟器 maa才能正常使用（重启maa 重启模拟器 等方法均试过） 如果不考虑maa 我基本不关机
希望能修复这个bug 不需要我重启电脑 

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10253123/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/63400627/208279380-1a828c7d-cbf3-475f-9f8f-a72a626f1a60.png)

**Comment by MistEO** [comment]
已知问题，不知道加速器做了什么手脚，目前靠 maa 解决不了

**Comment by MistEO** [comment]
可以给加速器他们提个 bug，最起码保证在停止加速后，电脑的网络配置能恢复到加速前的状态

谁制造谁清理，不应该由 maa 来解决，而且这么多加速器，我们也解决不过来

**Comment by 134820134820** [comment]
> ### 在提问之前...
> * [x]  我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
> * [x]  我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
> * [x]  我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
> 
> ### 问题描述
> 每次我使用 uu加速器等其他加速器 **切换游戏加速环境** 例如steam商店切换鹅鸭杀或其他游戏 只要存在切换过网络环境 maa就会**提示连接失败 请检查电脑设置或重新启动电脑** **只有重启电脑**启动模拟器 maa才能正常使用（重启maa 重启模拟器 等方法均试过） 如果不考虑maa 我基本不关机 希望能修复这个bug 不需要我重启电脑
> 
> ### 日志文件
> [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10253123/asst.log)
> 
> ### 截图
> ![image](https://user-images.githubusercontent.com/63400627/208279380-1a828c7d-cbf3-475f-9f8f-a72a626f1a60.png)
> 
> ### 还有别的吗？
> _No response_

应该是uu自己的问题把
网易的玩意问题多，正常你改网络代理都不会影响到模拟器中的

**Comment by poptree** [comment]
我也有这个问题，一般需要手动把adb.exe给结束了并重启才能恢复正常。

**Comment by 23333233** [comment]
刚刚试了试，如果是uu，在保持连接状态的时候打开uu，然后连接没有断开，之后再连接就没有这个问题了
