### ISSUE TITLE
Screencap failed. If it happens repeatedly, try restarting or changing the emulator

### ISSUE THREAD

**Issue by CallMeChin** [MaaAssistantArknights/MaaAssistantArknights#3108]
![image](https://user-images.githubusercontent.com/77185235/208286679-475914cc-8255-4544-8270-8e8ef25e5563.png)

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/208286684-d5f088a2-0061-462f-aad9-a0171a901074.png)
Please use this module to launch an issue and attach asst.log etc

**Comment by CallMeChin** [comment]
#3109
