### ISSUE TITLE
Login task error in YoStarEN

### ISSUE THREAD

**Issue by CallMeChin** [MaaAssistantArknights/MaaAssistantArknights#3109]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [ ] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Task error: StartUp
The error was "Screencap failed. If it happens repeatedly, try restarting or changing the emulator." But after replacing the touch mode with others, even replacing it back into minitouch, I was not able to replicate the problem.

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10253422/asst.log)

### Screenshots

![image](https://user-images.githubusercontent.com/77185235/208288316-d01d5699-7534-42b7-bc1b-7f8b616b38db.png)

**Comment by MistEO** [comment]
Not all features are supported for non-CN client, see [here](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/resource/global/YoStarEN/readme.md)

**Comment by CallMeChin** [comment]
SO en client are not able to login?
![image](https://user-images.githubusercontent.com/77185235/208291524-42a5454c-9aa2-403c-8ac3-e42cc4f7d048.png)
and supposedly claim reward should work right?
 
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10253540/asst.log)

**Comment by CallMeChin** [comment]
also the title was like that cuz nothing seem to be working
so uhh.... not really just login

**Comment by ABA2396** [comment]
Please check if there is a picture of "Task.png" in the directory "\resource\global\YoStarEN\resource\template", I don't know why it doesn't match
![image](https://user-images.githubusercontent.com/99072975/208297931-3418b6a1-5df9-4e43-81c0-a14ac2f8e103.png)

**Comment by CallMeChin** [comment]
yes, it is there. 
i have the resolution on 1600x900 on 240dpi if that help
<img width="476" alt="image" src="https://user-images.githubusercontent.com/77185235/208298404-066aa047-a5c2-4400-aa56-da8213ab86da.png">
I saw that it said it would work as long as it is larger than 1280x720 than is 16:9 aspect ratio

**Comment by ABA2396** [comment]
I think I know the problem.
Try changing the "roi" in "Award" in "resource\tasks.json" to "700,530,200,130" and restart MAA to see if it works
![image](https://user-images.githubusercontent.com/99072975/208298766-337a65ea-0dd1-4411-86e4-433c807e4c15.png)

**Comment by CallMeChin** [comment]
I am not sure why, but after switching to 200 it just sit there and do nothing?
![image](https://user-images.githubusercontent.com/77185235/208434394-1349dfca-1b0f-483e-98d7-3023ff31105c.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10259502/asst.log)

PS: i switched to using mumu player after trying many android emulator i found this one most stable. It would still error out if i left it on 130, on bluestacks it was stuck like this too without error. The resolution is changed to 1600x900

**Comment by CallMeChin** [comment]
So let me get it straight, 
Login, Recruit, Base, Combat, Auto I.S. does not work, and they are not coded to work?

Also is "Credit Store" suppose to leave it on this screen?
![image](https://user-images.githubusercontent.com/77185235/208438848-97bb0d1e-23ce-4017-9221-28a78a1be7c1.png)

**Comment by ABA2396** [comment]
> So let me get it straight, Login, Recruit, Base, Combat, Auto I.S. does not work, and they are not coded to work?
> 
> Also is "Credit Store" supposed to leave it on this screen? ![image](https://user-images.githubusercontent.com/77185235/208438848-97bb0d1e-23ce-4017-9221-28a78a1be7c1.png)

This may be due to the credit store there is no purchase of cadres, this did not do identification, manually buy the cadres may be good

**Comment by ABA2396** [comment]
> I am not sure why, but after switching to 200 it just sit there and do nothing? ![image](https://user-images.githubusercontent.com/77185235/208434394-1349dfca-1b0f-483e-98d7-3023ff31105c.png) [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10259502/asst.log)
> 
> PS: i switched to using mumu player after trying many android emulator i found this one most stable. It would still error out if i left it on 130. And on bluestacks after changing to 200, it was stuck like this too without error. The resolution is already changed to 1600x900
> 
> Edit: i found that it recognized the picture and tried to send a click signal but it didn't seem to work ![image](https://user-images.githubusercontent.com/77185235/208435302-1c86d12f-9a85-4f34-b762-32e7565dcfed.png)
> 
> replacing the Touch Mode with Adb Input seem to fixed it. Maybe i should've known when i saw this `[2022-12-19 21:12:45.889][INF][Px1c2c][Tx280] pipe str Note: device /dev/input/mouse1 is not supported by libevdev Note: device /dev/input/mice is not supported by libevdev Note: device /dev/input/mouse0 is not supported by libevdev Type B touch device nemuVM Virtual Input (1600x900 with 32 contacts) detected on /dev/input/event5 (score 22231) Note: hard-limiting maximum number of contacts to 10 Reading from STDIN v 1 ^ 10 1600 900 0 $ 2359 `



> I am not sure why, but after switching to 200 it just sit there and do nothing? ![image](https://user-images.githubusercontent.com/77185235/208434394-1349dfca-1b0f-483e-98d7-3023ff31105c.png) [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10259502/asst.log)
> 
> PS: i switched to using mumu player after trying many android emulator i found this one most stable. It would still error out if i left it on 130. And on bluestacks after changing to 200, it was stuck like this too without error. The resolution is already changed to 1600x900
> 
> Edit: i found that it recognized the picture and tried to send a click signal but it didn't seem to work ![image](https://user-images.githubusercontent.com/77185235/208435302-1c86d12f-9a85-4f34-b762-32e7565dcfed.png)
> 
> replacing the Touch Mode with Adb Input seem to fixed it. Maybe i should've known when i saw this `[2022-12-19 21:12:45.889][INF][Px1c2c][Tx280] pipe str Note: device /dev/input/mouse1 is not supported by libevdev Note: device /dev/input/mice is not supported by libevdev Note: device /dev/input/mouse0 is not supported by libevdev Type B touch device nemuVM Virtual Input (1600x900 with 32 contacts) detected on /dev/input/event5 (score 22231) Note: hard-limiting maximum number of contacts to 10 Reading from STDIN v 1 ^ 10 1600 900 0 $ 2359 `

The image size of YoStarEN is much larger than that of ZH-CN, so the range of roi has to be larger

**Comment by ABA2396** [comment]
使用minitouch的话需要推送一个可执行文件到模拟器，mumu如果不强制替换adb的话可能只能用兼容模式（adb点击）

**Comment by ABA2396** [comment]
If you use minitouch, you need to push an executable file to the emulator. mumu may only use compatibility mode (adb click) if you don't force adb to be replaced.

**Comment by ABA2396** [comment]
434dde999b2fa3e3e94279bce58b81a7caef3999 
I added a foreign adaptation of the document, but the English is using the machine flip, not sure if it is accurate. The task of foreign service lacks a large number of template images, the need to modify the roi is very little, mainly to replace the template

**Comment by CallMeChin** [comment]
原来是翻译器翻译过来的 😂，难怪我感觉哪里怪怪的。
所以目前是无法使用的是登录，招募，战斗，基地，和那个什么'Auto I.S.' 我都不知道是什么来的。
