### ISSUE TITLE
增加一个周日自动使用临期理智药设置

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#3116]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我已经不止一次忘记周日要用理智药了……

### 有什么好的想法？

在设置中加入一个周日自动使用临期理智药的设置。

**Comment by 134820134820** [comment]
确实，可以加一个周日把红理智药用了的选项

**Comment by vista98** [comment]
+1，我也忘过，顺带检查一下剿灭有没有打吧

**Comment by ABA2396** [comment]
#3684 fixed
