### ISSUE TITLE
完成战斗后继续开始战斗任务

### ISSUE THREAD

**Issue by askheaven** [MaaAssistantArknights/MaaAssistantArknights#3117]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

完成战斗后继续开始战斗任务，然后卡住了 

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10255702/asst.log)

### 截图

![screenshot](https://user-images.githubusercontent.com/25718012/208342012-ab9a9a64-e29c-4840-b979-15ed8de76b55.jpg)

### 还有别的吗？

mumu模拟器
win10
MAAv4.8.1

**Comment by ABA2396** [comment]
你剩余理智选的啥？
![image](https://user-images.githubusercontent.com/99072975/208606356-da92e513-da23-4a55-895a-54dcc2b846f2.png)

**Comment by askheaven** [comment]
![image](https://user-images.githubusercontent.com/25718012/208606482-32f94d19-7342-4184-8041-6d85b6c6486e.png)
竟然还有这个选项

**Comment by ABA2396** [comment]
这个改成“不选择”就好了，我看看怎么改
