### ISSUE TITLE
肉鸽干员练度识别，减少遍历时间

### ISSUE THREAD

**Issue by LZZBGGBG** [MaaAssistantArknights/MaaAssistantArknights#3118]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

自动肉鸽的时候每次选择干员都要遍历所有干员的状态，很花时间。

### 有什么好的想法？

像仓库识别一样识别干员的练度，肉鸽选干员的时候就不用遍历了

**Comment by MistEO** [comment]
肉鸽肯定要遍历的，每次可招募的都不一样啊，希望也有区别，有时候只有四星能招，有时候又有 4、5、6 都有，有时候甚至只有 4、6 但没有 5，不遍历咋知道招谁

**Comment by MistEO** [comment]
> 当然不强求添加这个功能，但是每次招募能选择的干员应该是确定的，当前的希望，招募券，有无减希望的藏品，选择的难度是否有+1希望等应该都可以在招募之前确定。简单想了一下确实可以做到不用遍历，如果有没考虑到的情况还请谅解

藏品识别太难做了，解决不了。所以没法确定
