### ISSUE TITLE
繁中服不支持購物功能

### ISSUE THREAD

**Issue by jane885511** [MaaAssistantArknights/MaaAssistantArknights#3122]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

"Mall"中的購物功能錯誤，訪問好友完至主介面後，卡住不動(沒有進去採購中心頁面)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10258629/asst.log)

### 还有别的吗？

繁中版
夜神模擬器7.0.5.0

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/208417502-4a4386fd-0556-41d7-a962-db544bd4da2c.png)
繁中的适配还没做完，还不支持Mall任务。
我们正在出一版外服适配的教程，需要根据需求修改添加模板图片、文字、roi等后才能使用，如果有兴趣可以加入我们适配繁中服，或者等待后续更新。
