### ISSUE TITLE
我的MAA在有些情况下会自动打OF-1不知道啥情况

### ISSUE THREAD

**Issue by HamBearGer** [MaaAssistantArknights/MaaAssistantArknights#3129]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

上一次关卡是这次的活动关，但是会自动开of-1，另外今天https://prts.plus/崩溃了2天了，也不知道是不是我在国外所以连接不上
![image](https://user-images.githubusercontent.com/121067236/208547843-310de4ad-8c0f-45f3-9fcc-efa03809b2c2.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10263460/asst.log)

**Comment by ntgmc** [comment]
是这样， 我认为您可能开启了该功能
![image](https://user-images.githubusercontent.com/74061867/208554762-27ae6e33-d994-400d-86f7-5175201d9b8a.png)
![image](https://user-images.githubusercontent.com/74061867/208554777-5661f6aa-fd89-40e2-9858-eea5ce2d0493.png)

**Comment by HamBearGer** [comment]
prts.plus加载失败这个麻烦看看吧哈哈哈

**Comment by HamBearGer** [comment]
okk~祝老哥早日康复吧
