### ISSUE TITLE
基建副手信赖已满导致基建换班的卡顿

### ISSUE THREAD

**Issue by pointm** [MaaAssistantArknights/MaaAssistantArknights#313]
新的方舟在收取信赖的时候，如果基建副手信赖满时会提示干员信赖已满。
使用脚本进行基建换班的时候如果碰到这个信赖满的提示可能会卡住，或者耽误一些换班的时间。

很抱歉忘记保存截图了，如果之后我找到的话会补上来。

**Comment by MistEO** [comment]
3.0.8 已经修复了，更新一下吧~

**Comment by pointm** [comment]
> 3.0.8 已经修复了，更新一下吧~

好的👌，我明天再试一试

**Comment by MistEO** [comment]
没问题我就关掉咯~
