### ISSUE TITLE
回调访问好友和信用购物按钮或进行改进

### ISSUE THREAD

**Issue by 787091034CJX** [MaaAssistantArknights/MaaAssistantArknights#3130]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我（零氪）在游戏的时候通常会使用信用购买打折材料而不是原价材料，但是目前的MAA信用购物功能不支持优先买打折商品，所以目前我只能取消自动访问手动进行操作然后购买材料。

### 有什么好的想法？

在保持现有功能的情况下，建议添加一个购买打折商品的功能，同时配合黑白名单使用。

**Comment by MistEO** [comment]
黑名单就是除了黑名单，其他按打折顺序购买

**Comment by 787091034CJX** [comment]
这样的吗，感谢
