### ISSUE TITLE
v4.8.1使用基建计划功能下拉菜单有两个以上可选项时会自动重置为第一个可选项

### ISSUE THREAD

**Issue by lastxxx2** [MaaAssistantArknights/MaaAssistantArknights#3131]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用基建计划功能时，如果有两个及以上可选项，手动选·第二个，maa执行完成一个任务，下拉栏选择会自动重置为第一个，只能单选基建计划执行，非常影响体验

### 日志文件

[Uploading asst.log…]()

### 截图

<img width="581" alt="image" src="https://user-images.githubusercontent.com/42098228/208582133-8c433389-9547-44c2-8527-a5b84211f4e2.png">

**Comment by lastxxx2** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10265212/asst.log)

**Comment by lastxxx2** [comment]
没有，用的自定义配置，时间设置的24小时全天

**Comment by lastxxx2** [comment]
> 你是不是设置了时间，基建作业里
没有，用的自定义配置，时间设置的24小时全天

**Comment by lastxxx2** [comment]
> 你是不是设置了时间，基建作业里

在正在执行任务的时候，基建计划下拉框没有锁死，执行完一个任务会自动重置成第一个选项

**Comment by ABA2396** [comment]
原来的设计就是这样，执行完之后切换下一个班次

**Comment by lastxxx2** [comment]
> 原来的设计就是这样，执行完之后切换下一个班次

**Comment by lastxxx2** [comment]
> 原来的设计就是这样，执行完之后切换下一个班次

不是的，是开始连接模拟器前，选好基建计划下拉框，点击连接模拟器开始执行任务。执行完第一个开始唤醒（无论什么任务）都会导致基建计划的下拉栏切换回第一个，然后到换班任务的时候就换错班了，不能开始执行第一个任务的时候就锁定基建计划这个下拉框吗

**Comment by lastxxx2** [comment]
> 原来的设计就是这样，执行完之后切换下一个班次

大部分一天二三换，设置好时段的人可能没有这个问题，但是一天一换，时段设置全天，手动选就有问题

**Comment by ABA2396** [comment]
你要是一天一换，两组的话就不要设置指定时间
