### ISSUE TITLE
有关肉鸽自动放弃招募的问题

### ISSUE THREAD

**Issue by minecraftfen** [MaaAssistantArknights/MaaAssistantArknights#3137]
### 说说你遇到的问题？

我不太理解，肉鸽中MAA捡到招募券有时会自动放弃招募，但哪怕是三星的预备干员多招几个都比不招好啊，招募行为又没有副作用，不是多多益善吗？

**Comment by MistEO** [comment]
可能是 bug，来个日志

**Comment by minecraftfen** [comment]
稍等，我去让MAA刷一把肉鸽

**Comment by minecraftfen** [comment]
每次MAA刷肉鸽都只招一个银灰一个预备医疗，初始辅助券直接放弃招募

**Comment by minecraftfen** [comment]
？它又会招了

**Comment by minecraftfen** [comment]
触发问题了
肉鸽设置的开局干员为空才会触发

**Comment by minecraftfen** [comment]
![image](https://user-images.githubusercontent.com/42016099/209038554-6e0f621f-adf7-4b46-9f39-91e3477cd0bc.png)

**Comment by minecraftfen** [comment]
![image](https://user-images.githubusercontent.com/42016099/209038645-782195b9-0412-4937-8fad-a1e3691ac8fc.png)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10283130/asst.zip)

**Comment by minecraftfen** [comment]
我还以为这是你们设置的招募策略，原来是bug吗

**Comment by minecraftfen** [comment]
操作系统Win11 Release Preview 22622.575

**Comment by minecraftfen** [comment]
而且闯肉鸽期间也会放弃掉一部分招募券
