### ISSUE TITLE
借助战刷信用能不能选定上场干员？

### ISSUE THREAD

**Issue by minecraftfen** [MaaAssistantArknights/MaaAssistantArknights#3138]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我的德克萨斯没怎么练，但MAA借助战任务似乎只使用德克萨斯，能给个选项让我换个高练度先锋吗。。。

**Comment by ABA2396** [comment]
打开 \resource\copilot\OF-1_credit_fight.json 文件，修改干员的名字或者排序，但是你这样的话得每个版本改一次

**Comment by MistEO** [comment]
> 打开 \resource\copilot\OF-1_credit_fight.json 文件，修改干员的名字或者排序，但是你这样的话得每个版本改一次

我们直接多赛点先锋进去怎么样（？

**Comment by ABA2396** [comment]
> > 打开 \resource\copilot\OF-1_credit_fight.json 文件，修改干员的名字或者排序，但是你这样的话得每个版本改一次
> 
> 我们直接多塞点先锋进去怎么样（？

就怕有新人先锋少，第一页就有精二和精零1级，这样顺序就会有影响了吧

**Comment by minecraftfen** [comment]
干员名字得全字匹配还是子串匹配？

**Comment by minecraftfen** [comment]
还有skill_usage字段语义是什么

**Comment by minecraftfen** [comment]
又发现一个新问题，如果OF-1之前没打过，那MAA就无法识别处理行动后的剧情演出

**Comment by ABA2396** [comment]
> 干员名字得全字匹配还是子串匹配？

全字匹配

> 还有skill_usage字段语义是什么

技能用法。可选，默认 0
 0 - 不自动使用（依赖 "actions" 字段）
 1 - 好了就用，有多少次用多少次（例如干员 棘刺 3 技能、桃金娘 1 技能等）
 2 - 好了就用，仅使用一次（例如干员 山 2 技能）
 3 - 自动判断使用时机（画饼.jpg）
 如果是全自动的技能，填 0

**Comment by minecraftfen** [comment]
了解啦
