### ISSUE TITLE
MAA执行清理智任务时无响应

### ISSUE THREAD

**Issue by HS7097** [MaaAssistantArknights/MaaAssistantArknights#3140]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA目前是作为Alas的插件运行的

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10274675/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/103177863/208826971-43c06477-140b-4553-a843-9d6a0ef200d4.png)
![image](https://user-images.githubusercontent.com/103177863/208827052-baaf12df-9f1f-46cc-a491-0c25a21cb2ce.png)
![image](https://user-images.githubusercontent.com/103177863/208827108-0d781990-ae8c-4d66-bd95-cfc65d323c89.png)

### 还有别的吗？

除此之外，我还希望大佬能对Alas开放更多接口，以达到7*24H无人值守运行

**Comment by ABA2396** [comment]
自定义只能填原列表的关卡和主线关卡，这个在MAA的ui里有提示，alas里没提到

**Comment by HS7097** [comment]
> 自定义只能填原列表的关卡和主线关卡，这个在MAA的ui里有提示，alas里没提到

那大佬，MAA它有那个自动使用代理指挥的模块吗？本体我没怎么看懂，像半自动的QwQ

**Comment by ABA2396** [comment]
> > 自定义只能填原列表的关卡和主线关卡，这个在MAA的ui里有提示，alas里没提到
> 
> 那大佬，MAA它有那个自动使用代理指挥的模块吗？本体我没怎么看懂，像半自动的QwQ

你打一把CA-3，演习或者作战都行，进去就退也行，然后把关卡导航设置成 `当前/上次` 就可以了
