### ISSUE TITLE
Got stuck in Base

### ISSUE THREAD

**Issue by Nigh** [MaaAssistantArknights/MaaAssistantArknights#3141]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Get stuck there, happens several times a week.

### Log files

[asst - Copy.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10275766/asst.-.Copy.log)

### Screenshots

![Screenshot 2022-12-21 160142](https://user-images.githubusercontent.com/1407471/208852142-6d71fe77-b425-445f-ad5a-279a1621a97f.jpg)

### Anthing else?

- Emulator: Bluestacks 5.9.400.1021 N64
- OS: Windows 11 Pro 21H2 22000.1335

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/208869507-5ed3a556-71e8-41ad-97ea-fb6f033f3c7d.png)
![image](https://user-images.githubusercontent.com/99072975/208869279-ee4015be-8554-4228-b689-abc9adba2c80.png)
Can you reproduce the diagram after clicking off the tip? I haven't seen this look before

**Comment by ABA2396** [comment]
There is a not very good but simple solution to this problem, and that is to turn off the prompt
![image](https://user-images.githubusercontent.com/99072975/208874383-805ec52e-a16b-4fbb-8e4c-ca7d472c7ac9.png)

**Comment by Nigh** [comment]
> There is a not very good but simple solution to this problem, and that is to turn off the prompt !

I will try this solution, thank you.

**Comment by Nigh** [comment]
@ABA2396 reproduced. And I also recorded what happens after clicking the "Cancel" button.

https://user-images.githubusercontent.com/1407471/210163890-920cbc58-4c5a-4f66-aebd-a3ae9a765422.mp4
