### ISSUE TITLE
在进行mall时会出现错误

### ISSUE THREAD

**Issue by zxmydmug** [MaaAssistantArknights/MaaAssistantArknights#3143]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在进行“mall”的时候会去打of-1，还会自己接助战

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10277841/asst.log)

**Comment by MistEO** [comment]
有没有一种可能，这个功能是你自己勾上的（）

**Comment by zxmydmug** [comment]
对不起对不起给你们添麻烦了（双手合十）
