### ISSUE TITLE
今天的新版本, 不是有效的datetime

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaAssistantArknights#3148]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10282512/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/72590023/209024609-c6916d87-8d55-4997-87d6-8a3ccd46c407.png)

**Comment by ABA2396** [comment]
a99f7ddfecb2abace0eb7b5cb013015755df30e6 fixed

**Comment by ABA2396** [comment]
备份一下 MAA.exe，试试看这个 [MAA.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10283838/MAA.zip)
不知道为啥在部分电脑上会出问题（）
