### ISSUE TITLE
肉鸽使用鸿雪时打字机反复当作地面位尝试部署

### ISSUE THREAD

**Issue by KUAPT** [MaaAssistantArknights/MaaAssistantArknights#3149]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题：肉鸽使用鸿雪时打字机反复当作地面位尝试部署

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10283424/asst.log)   时间大概在上午9时往后

### 截图
![YJQ8}8T})P)_A}Q66R G4$F](https://user-images.githubusercontent.com/110989625/209039085-f4e1af4c-a857-453f-8173-a564c3d54290.png)

**Comment by MistEO** [comment]
发下日志

**Comment by KUAPT** [comment]
> 发下日志

已上传
