### ISSUE TITLE
关于maa是否能添加一个选项使模拟器启动时可以选择最小化或后台启动

### ISSUE THREAD

**Issue by 134820134820** [MaaAssistantArknights/MaaAssistantArknights#3151]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

当把maa挂后台做别的事的时候，时常突然弹出一个模拟器还是有点奇怪，能否实现有一个选项是模拟器在最小化（或后台）自动启动运行还是前台

### 有什么好的想法？

启动命令里加一个"/min"?

**Comment by ABA2396** [comment]
对蓝叠试过，但是没用

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/209063733-031d79ab-8d7c-4bd3-ac1b-224fa399d90e.png)

**Comment by ABA2396** [comment]
整了点别的方法，但是会不会有如果窗口句柄无效或者窗口已经被关闭这种情况 @MistEO

**Comment by ABA2396** [comment]
> 启动命令里加一个"/min"?

/min肯定是没用的，模拟器的启动和别的不太一样，现在这个方法蓝叠确定是可用的，但别的模拟器不知道，还得测试一下

**Comment by 134820134820** [comment]
> /min 可以用户自己加啊，不是有附加参数可以填吗（
附加参数试过了没有用，因为没搞C只能猜那个相当于是快捷方式中的参数需要蓝叠内部的配合，所以说想问有没有别的方法，比如说在cmd start命令后添加

**Comment by 134820134820** [comment]
> /min 可以用户自己加啊，不是有附加参数可以填吗（

或者说启动时别的支持方法，像 --instance Nougat64这种附加参数应该时传导到蓝叠内部用的，所以在这填/min无效。
这种肯定是试过了才来问是否能在程序的启动命令有别的方法实现

**Comment by ABA2396** [comment]
> > /min 可以用户自己加啊，不是有附加参数可以填吗（
> 
> 或者说启动时别的支持方法，像 --instance Nougat64这种附加参数应该时传导到蓝叠内部用的，所以在这填/min无效。
> 这种肯定是试过了才来问是否能在程序的启动命令有别的方法实现

没用，最后还是调了win32api给它最小化的，等于就是启动后给它点了最小号按钮，而不是最小化启动

**Comment by 134820134820** [comment]
![12-23](https://user-images.githubusercontent.com/79043872/209265649-b3ca5163-28d3-48e9-ba32-be58e2340579.PNG)


> /min 可以用户自己加啊，不是有附加参数可以填吗（

似乎这样也是不行的

**Comment by 134820134820** [comment]
> > > /min 可以用户自己加啊，不是有附加参数可以填吗（
> > 
> > 
> > 或者说启动时别的支持方法，像 --instance Nougat64这种附加参数应该时传导到蓝叠内部用的，所以在这填/min无效。
> > 这种肯定是试过了才来问是否能在程序的启动命令有别的方法实现
> 
> 没用，最后还是调了win32api给它最小化的，等于就是启动后给它点了最小化按钮，而不是最小化启动

可以做到了吗！会在下个版本更新吗

**Comment by ABA2396** [comment]
> > > > /min 可以用户自己加啊，不是有附加参数可以填吗（
> > > 
> > > 
> > > 或者说启动时别的支持方法，像 --instance Nougat64这种附加参数应该时传导到蓝叠内部用的，所以在这填/min无效。
> > > 这种肯定是试过了才来问是否能在程序的启动命令有别的方法实现
> > 
> > 没用，最后还是调了win32api给它最小化的，等于就是启动后给它点了最小化按钮，而不是最小化启动
> 
> 可以做到了吗！会在下个版本更新吗

484已经发了，更新一下

**Comment by 134820134820** [comment]
> win32api

ok

**Comment by ABA2396** [comment]
但是现在就蓝叠确定是可用的，mumu大概是不行，别的模拟器还有待测试

**Comment by 134820134820** [comment]
> 但是现在就蓝叠确定是可用的，mumu大概是不行，别的模拟器还有待测试

确实已经解决了，谢谢

**Comment by 134820134820** [comment]
> 但是现在就蓝叠确定是可用的，mumu大概是不行，别的模拟器还有待测试

顺便问下更新逻辑问题，似乎不开自动下载更新将更新包拖进去也不会识别？但靠arir2下很容易下不下来，多个maa更新时好累

**Comment by ABA2396** [comment]
> > 但是现在就蓝叠确定是可用的，mumu大概是不行，别的模拟器还有待测试
> 
> 顺便问下更新逻辑问题，似乎不开自动下载更新将更新包拖进去也不会识别？但靠arir2下很容易下不下来，多个maa更新时好累

你下的是这个仓库的 OTA 包还是 [v4.8.4](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v4.8.4) 这里的 OTA 包？得下后面那个里对应版本的更新包

**Comment by 134820134820** [comment]
> > > 但是现在就蓝叠确定是可用的，mumu大概是不行，别的模拟器还有待测试
> > 
> > 
> > 顺便问下更新逻辑问题，似乎不开自动下载更新将更新包拖进去也不会识别？但靠arir2下很容易下不下来，多个maa更新时好累
> 
> 你下的是这个仓库的 OTA 包还是 [v4.8.4](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v4.8.4) 这里的 OTA 包？得下后面那个里对应版本的更新包

仓库中对应的，如果没有勾自动下载似乎不会检测，只有在勾了自动下载的情况下，它自己开始尝试下后，才会识别是否有包以及更新

**Comment by ABA2396** [comment]
> > > > 但是现在就蓝叠确定是可用的，mumu大概是不行，别的模拟器还有待测试
> > > 
> > > 
> > > 顺便问下更新逻辑问题，似乎不开自动下载更新将更新包拖进去也不会识别？但靠arir2下很容易下不下来，多个maa更新时好累
> > 
> > 
> > 你下的是这个仓库的 OTA 包还是 [v4.8.4](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v4.8.4) 这里的 OTA 包？得下后面那个里对应版本的更新包
> 
> 仓库中对应的，如果没有勾自动下载似乎不会检测，只有在勾了自动下载的情况下，它自己开始尝试下后，才会识别是否有包以及更新

下个版本更新之后下下个版本测测.jpg

**Comment by 134820134820** [comment]
彳亍

> > > > > 但是现在就蓝叠确定是可用的，mumu大概是不行，别的模拟器还有待测试
> > > > 
> > > > 
> > > > 顺便问下更新逻辑问题，似乎不开自动下载更新将更新包拖进去也不会识别？但靠arir2下很容易下不下来，多个maa更新时好累
> > > 
> > > 
> > > 你下的是这个仓库的 OTA 包还是 [v4.8.4](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v4.8.4) 这里的 OTA 包？得下后面那个里对应版本的更新包
> > 
> > 
> > 仓库中对应的，如果没有勾自动下载似乎不会检测，只有在勾了自动下载的情况下，它自己开始尝试下后，才会识别是否有包以及更新
> 
> 下个版本更新之后下下个版本测测.jpg

**Comment by qingzhuall** [comment]
问一下，我记得之前开启过这个功能，但是现在找不到这个功能的开关了，用户手册里不知道划分在哪个部分，能否告知一下

**Comment by 134820134820** [comment]
> 问一下，我记得之前开启过这个功能，但是现在找不到这个功能的开关了，用户手册里不知道划分在哪个部分，能否告知一下

![image](https://github.com/user-attachments/assets/49a567d7-a766-4f44-8bd6-3f3c861a5dda)
在这

**Comment by ABA2396** [comment]
> 问一下，我记得之前开启过这个功能，但是现在找不到这个功能的开关了，用户手册里不知道划分在哪个部分，能否告知一下

很遗憾，现在市面上的模拟器都改成了双进程，通过原来的方式已经无法实现最小化了，所以这个功能也就去掉了

**Comment by qingzhuall** [comment]
> > 问一下，我记得之前开启过这个功能，但是现在找不到这个功能的开关了，用户手册里不知道划分在哪个部分，能否告知一下
> 
> 很遗憾，现在市面上的模拟器都改成了双进程，通过原来的方式已经无法实现最小化了，所以这个功能也就去掉了

好的，谢谢答复

**Comment by qingzhuall** [comment]
> > 问一下，我记得之前开启过这个功能，但是现在找不到这个功能的开关了，用户手册里不知道划分在哪个部分，能否告知一下
> 
> ![image](https://github.com/user-attachments/assets/49a567d7-a766-4f44-8bd6-3f3c861a5dda) 在这

现在已经被删掉了，不过还是谢谢回复
