### ISSUE TITLE
借助战赚信用和暂停下干员不能同时使用！

### ISSUE THREAD

**Issue by 809717330** [MaaAssistantArknights/MaaAssistantArknights#3155]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

借助战赚信用和暂停下干员不能同时使用！
这两个功能同时开启，会在刷信用关卡，放干员后立刻暂停，脚本超时任务结束。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10285275/asst.log)

**Comment by ABA2396** [comment]
暂停下干员单独使用正常吗？这个功能现在就Maatouch的支持好点

**Comment by 809717330** [comment]
&nbsp;


&nbsp;不行，刚测试肉鸽，下干员后直接暂停了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月22日(星期四) 晚上6:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 借助战赚信用和暂停下干员不能同时使用！ (Issue #3155)





 
暂停下干员单独使用正常吗？这个功能现在就Maatouch的支持好点

**Comment by 809717330** [comment]
> 暂停下干员单一使用正常吗？这个功能现在就Maatouch的支持好处

点触模式是这个Maatouch
