### ISSUE TITLE
4.8.3版本启动时拉起模拟器时报错，无法进入主界面

### ISSUE THREAD

**Issue by nuclearg** [MaaAssistantArknights/MaaAssistantArknights#3156]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我配置了让MAA启动时拉起蓝叠，同时为了能让蓝叠自动拉起明日方舟，我将MAA的模拟器执行文件路径配到了一个快捷方式上：

"C:\Program Files\BlueStacks_nxt\HD-Player.exe" --instance Pie64 --cmd launchApp --package "com.hypergryph.arknights"

之前的版本一直以来工作的非常完美，但是更新v4.8.3后报错，

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10285823/asst.log)

启动时弹错误框如下：

指定的可执行文件不是此操作系统平台的有效应用程序。

  在 System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   在 MaaWpfGui.SettingsViewModel.TryToStartEmulator(Boolean manual)
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.AsstProxy.<>c__DisplayClass26_0.<<Init>b__1>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by nuclearg** [comment]
[gui.json.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10285933/gui.json.txt)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10285935/gui.log)

**Comment by MistEO** [comment]
看起来是 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/b301825429edbeb9db0f8fe0dd799e4677e1322e 这次提交引入的。@ABA2396 来瞅瞅

**Comment by one-pyy** [comment]
++

**Comment by one-pyy** [comment]
可以先改gui.json中Start.StartEmulator为False()

**Comment by ABA2396** [comment]
5e3740451dcae40d354ea8da1cd1cf5515a95203 fixed
但这种方式引入了新的包，看看有啥办法没 @MistEO
