### ISSUE TITLE
启动时后卡在Fight任务

### ISSUE THREAD

**Issue by Jerr1yz** [MaaAssistantArknights/MaaAssistantArknights#3158]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

1.启动maa第一次执行Fight任务时，无法识别活动入口，导致无法点选关卡，等待几分钟后提示Fight失败并退出。切换“当前/上次”或“1-7”等常规选项可解决
2.偶尔在选择常规关卡选项而非活动关卡时，也会卡住，卡住截图如下
在近一个月内的各个版本经常出现，出现前提暂没有发现规律。

### 日志文件

12-22 18：48：21
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10286338/asst.log)

### 截图

![QQ截图20221222190244](https://user-images.githubusercontent.com/120998459/209120579-056bd967-2a11-4140-bbe2-f3c249168f3f.png)
![QQ截图20221222191233](https://user-images.githubusercontent.com/120998459/209122234-78a9f081-f013-42cc-aa3b-ec944c0bb361.png)

**Comment by ABA2396** [comment]
1bb9c260b88996efa1bfe697e00768b0a056a7a3 fixed
