### ISSUE TITLE
WaitForInputIdle 失败

### ISSUE THREAD

**Issue by 123wangyoujun** [MaaAssistantArknights/MaaAssistantArknights#3161]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新后出现未知错误

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10286876/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/93244408/209134587-ac51c22f-2463-451d-8c08-fd404757f7bd.png)

### 还有别的吗？

使用夜神模拟器 win11

**Comment by ABA2396** [comment]
duplicate to #3156

**Comment by ABA2396** [comment]
[v4.8.4](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.8.4) fixed
