### ISSUE TITLE
更新至v4.8.4后，连接失败尝试启动模拟器后再无响应

### ISSUE THREAD

**Issue by joka325** [MaaAssistantArknights/MaaAssistantArknights#3170]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新至v4.8.4后，开始运行后，连接模拟器失败并尝试启动模拟器后，任务自动停止。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10288960/asst.log)

[2022-12-23 00:53:00.087]

### 截图

![屏幕截图 2022-12-23 005701](https://user-images.githubusercontent.com/119752357/209186966-690d9669-0cf4-41f7-a2a7-a9ceecba85c7.png)

**Comment by spec123321** [comment]
4.8.4等待模拟器启动时间有问题，会直接开始连接模拟器，模拟器还未完全启动，两次连接失败后卡主

**Comment by ABA2396** [comment]
362314c9ab65bb35289cfcbb0ef60dea187bbe63 fixed
