### ISSUE TITLE
同时出现两个任务栏图标

### ISSUE THREAD

**Issue by minecraftfen** [MaaAssistantArknights/MaaAssistantArknights#3171]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我能确定这不是因为系统未清理上一个进程的图标导致的，因为这两个图标在MAA启动时同时出现，关闭时同时消失。应该是系统的相关API被调用了两次。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10290973/asst.zip)

### 截图

![image](https://user-images.githubusercontent.com/42016099/209244132-e9b19f36-e7d4-45bb-90f4-4c68a34fa4b1.png)

**Comment by minecraftfen** [comment]
![image](https://user-images.githubusercontent.com/42016099/209246610-63da5369-9dcd-421f-902b-55e3b1e435e1.png)
MAA启动半小时后任务栏图标恢复正常

**Comment by MistEO** [comment]
这其实更像是 Windows 的 bug（

**Comment by minecraftfen** [comment]
> 这其实更像是 Windows 的 bug（
> 
> 你 hover 一下是不是自动就没了

确认过了，两个都可以右键，都可以操作MAA
但这个问题不是每一次都会出现

**Comment by minecraftfen** [comment]
> 这其实更像是 Windows 的 bug（
> 
> 你 hover 一下是不是自动就没了

我在提问的时候就去确认了

> 我能确定这不是因为系统未清理上一个进程的图标导致的

**Comment by minecraftfen** [comment]
我之前写Electron程序的时候就有过反复调用导致任务栏四五个图标的情况，所以我觉得也有可能是MAA的问题
