### ISSUE TITLE
v4.8.4在MacOS下闪退

### ISSUE THREAD

**Issue by duzx16** [MaaAssistantArknights/MaaAssistantArknights#3172]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA-v4.8.4-macos-arm64在MacOS 13.1下打开后右侧显示“目录设置成功”之后就会自动退出，4.8.3也存在这个问题，4.8.2-beta1可以正常使用

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10291351/asst.log)
问题最后一次在2022-12-23 09:28出现

### 还有别的吗？

操作系统为macOS Ventura 13.1，芯片为Apple M1 Pro

**Comment by hguandl** [comment]
FastDeploy 库的编译出了问题，https://github.com/MaaAssistantArknights/build-fastdeploy/pull/4 正在尝试修复。

**Comment by hguandl** [comment]
@duzx16 已修复。请使用最新 release 里的 v4.8.4-1 版本。
