### ISSUE TITLE
国际服傀影肉鸽不投资

### ISSUE THREAD

**Issue by RiichiTsumo** [MaaAssistantArknights/MaaAssistantArknights#3174]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

进入诡异行商节点后只购买收藏品，不进行投资，即使设置里选择优先投源石锭也是如此

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10294849/asst.log)

### 截图

![mmexport1671796746161](https://user-images.githubusercontent.com/77238633/209333035-1079765b-ba55-4442-ab9d-557bb5747e89.png)
![mmexport1671796784364](https://user-images.githubusercontent.com/77238633/209333107-87839dee-3c5b-4142-b630-807ce52a1540.png)
![微信图片_20221223202131](https://user-images.githubusercontent.com/77238633/209336039-56942276-de63-4930-8ac0-ad2e6953140f.png)
![微信图片_20221223202138](https://user-images.githubusercontent.com/77238633/209336046-1e7868f3-4061-401c-af90-14603b30816b.png)

### 还有别的吗？

模拟器：蓝叠国际版64位
操作系统：windows 11 22H2 25262.1000

**Comment by RiichiTsumo** [comment]
![mmexport1671797849933](https://user-images.githubusercontent.com/77238633/209335174-8c94487a-d674-4a37-b635-5ab86ba0066d.png)
![mmexport1671797854071](https://user-images.githubusercontent.com/77238633/209335187-01f2e4c3-78e4-44f6-9e7b-15b2dacfd1e8.png)
补两张投资界面图

**Comment by pangchewe** [comment]
I got the same problem that bot doesn't invest ingot for me. It's only buy other stuff as you see below
![image](https://user-images.githubusercontent.com/34416808/209476756-f77f1c48-d06f-4cdc-a093-242bfb1f7830.png)
![image](https://user-images.githubusercontent.com/34416808/209476793-9f3650bd-1bed-4c8b-9ca8-9fc9e66c1174.png)

https://user-images.githubusercontent.com/34416808/209476813-d3e38790-3a85-4f45-9550-a2f12a28389b.mp4

**Comment by RiichiTsumo** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/3230
