### ISSUE TITLE
4.8.4等待模拟器启动时间有问题，会直接开始连接模拟器，模拟器还未完全启动，两次连接失败后卡主

### ISSUE THREAD

**Issue by KiligLin** [MaaAssistantArknights/MaaAssistantArknights#3177]
4.8.4等待模拟器启动时间有问题，会直接开始连接模拟器，模拟器还未完全启动，两次连接失败后卡主

_Originally posted by @spec123321 in https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3170#issuecomment-1363695960_

**Comment by KiligLin** [comment]
我也遇到这个问题了，百分百卡住，应该是个bug的

**Comment by ABA2396** [comment]
362314c9ab65bb35289cfcbb0ef60dea187bbe63 fixed
