### ISSUE TITLE
4.8.4 傀影肉鸽 在进入第一层时 无法正常开始行动

### ISSUE THREAD

**Issue by NeedEDD** [MaaAssistantArknights/MaaAssistantArknights#3178]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

傀影肉鸽 在进入第一层时, 系统镜头会向后,  需要人为手动向前滑动, maa才会正常运行自动作战

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10297970/asst.zip)
时间:12月24日 12时左右

### 截图

![PY`2R3T@NW41BR18J{RU7TA](https://user-images.githubusercontent.com/121327886/209420815-980b621a-75b1-4292-9417-f0cc457d53b3.png)
![ZOFXC2TXNY1ZBX $7C7VVES](https://user-images.githubusercontent.com/121327886/209420817-873d84ad-a52e-44c7-b1dd-030f8a6304a5.png)
![8NCE3K @5IB)O3(GFOM MXD](https://user-images.githubusercontent.com/121327886/209420892-1b8e6131-6369-4f18-be87-7966f4989de8.png)

### 还有别的吗？

模拟器:mumu
系统:Windows 10 21H2

**Comment by MistEO** [comment]
MAA 滑的？还是游戏自动滑的，为啥会滑啊

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3178
