### ISSUE TITLE
自动换班优先会客室需求

### ISSUE THREAD

**Issue by HaneRo** [MaaAssistantArknights/MaaAssistantArknights#318]
水月组不要占用杰西卡（3号线索）罗比菈塔也是标准化β

**Comment by MistEO** [comment]
请参考 [详细介绍](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md#%E5%85%B6%E4%BB%96%E4%B9%B1%E4%B8%83%E5%85%AB%E7%B3%9F%E7%9A%84%E8%AF%B4%E6%98%8E)

> 主界面上要执行的任务，是可以拖动改变顺序的。同样设置中基建换班的顺序，也是可以拖动改变的。
