### ISSUE TITLE
助战赚信用 借助战时卡住

### ISSUE THREAD

**Issue by maidangdang1** [MaaAssistantArknights/MaaAssistantArknights#3181]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图，一直点第一个的风笛

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10298115/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10298116/asst.log)
神奇的是这几天都没有对log进行读写，但是gui.log是正常的
![image](https://user-images.githubusercontent.com/46847241/209424853-fc36aacd-4cbf-42ba-8e9a-8c731467cb9a.png)

### 截图

![Screenshot_2022 12 24_14 31 48 220](https://user-images.githubusercontent.com/46847241/209424745-ce076493-0856-4ee5-8e81-e86145e640dc.png)

### 还有别的吗？

v4.8.4

**Comment by ABA2396** [comment]
cc @Hydrogina

**Comment by ABA2396** [comment]
模板匹配估计分不开这个滤镜

**Comment by Hydrogina** [comment]
应该把模板匹配的分调高一点就可以了吧，比如调到0.9

**Comment by ABA2396** [comment]
日志里确实没信息，不知道为啥 @MistEO

**Comment by Shawnsdaddy** [comment]
同卡住，现在都不敢用
