### ISSUE TITLE
“等待模拟器启动时间”设置不起作用

### ISSUE THREAD

**Issue by imaegoo** [MaaAssistantArknights/MaaAssistantArknights#3182]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

该问题是更新4.8.4版本后发现的，老版本没有问题

### 复现步骤

1. 设置-连接设置
2. 打钩“启动后直接运行”
3. 打钩“启动后自动开启模拟器”
4. “等待模拟器启动时间” 输入 30
5. 输入正确的模拟器路径
6. 关闭模拟器和MAA，然后重新打开MAA

### 期望结果（更新4.8.4以前）

MAA立即自动启动模拟器，**30秒后** 开始连接模拟器

### 实际结果（更新4.8.4以后）

MAA立即自动启动模拟器，**立即** 开始连接模拟器，由于模拟器启动需要时间，导致连接失败，需要人工重新点击 Link Start 按钮

```txt
12月25日 周日 9:44:54 正在连接模拟器……
12月25日 周日 9:44:59 连接失败
请检查连接设置或尝试重启电脑
12月25日 周日 9:44:59 连接失败
正在尝试启动模拟器
12月25日 周日 9:44:59 连接失败
请检查连接设置或尝试重启电脑
```

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10299339/asst.log)

问题出现的大致时间点：中国时间 12月25日 9:44:54

### 截图

![image](https://user-images.githubusercontent.com/20182252/209454927-186578d5-914a-4aa5-a6c5-60a4f7a2021b.png)

### 还有别的吗？

使用的模拟器：BlueStacks 5 Android Pie 64
操作系统：Windows 10

**Comment by ABA2396** [comment]
362314c9ab65bb35289cfcbb0ef60dea187bbe63 fixed

**Comment by CCCClaus** [comment]
> [362314c](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/362314c9ab65bb35289cfcbb0ef60dea187bbe63) fixed

目前这个问题是还没推送，等待4.8.5推送这个修复吗？

**Comment by ABA2396** [comment]
> > [362314c](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/362314c9ab65bb35289cfcbb0ef60dea187bbe63) fixed
> 
> 目前这个问题是还没推送，等待4.8.5推送这个修复吗？

嗯，等下个版本就好了

**Comment by imaegoo** [comment]
4.8.5 已确认修复！
