### ISSUE TITLE
使用蓝叠模拟器，MAA连接成功，虽然提示截图失败，但可以执行成功

### ISSUE THREAD

**Issue by 000001919** [MaaAssistantArknights/MaaAssistantArknights#3183]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

操作系统：win10(22h2)
MAA版本：4.8.4
模拟器：蓝叠模拟器
问题出现在自动肉鸽
问题：MAA连接成功，软件操作正常，但会循环先提示截图失败，提示失败后又提示战斗完成，每打一关都会提示一次
该问题已经尝试过重新下载MAA，重新安装模拟器，但均未解决
该问题我尝试用另外一台电脑复现，但未成功

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10299539/asst.log)

### 截图

![屏幕截图 2022-12-25 151137](https://user-images.githubusercontent.com/78247561/209459775-065a51c4-c6e3-49ee-9221-b646c3c8603b.png)

**Comment by 000001919** [comment]
时间在下午2：50分左右

**Comment by MistEO** [comment]
截图失败会自动重试的，只要不是一直报就不用管。这个似乎收电脑性能等影响，没太搞懂
