### ISSUE TITLE
肉鹅放弃招聘后导致卡住的bug（国际服）

### ISSUE THREAD

**Issue by CallMeChin** [MaaAssistantArknights/MaaAssistantArknights#3184]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

这用的是actions里最新的版本
放弃招聘其中一个开局成员后会导致卡住。

### 日志文件

25/12/2022 3:00:08 PM Connecting to emulator...
25/12/2022 3:00:11 PM Running...
25/12/2022 3:00:11 PM If all stuck, plz go to Settings - Connection Settings - Forced Replace ADB File, or turn on Compatibility Touch Mode
25/12/2022 3:00:11 PM Start task: Roguelike
25/12/2022 3:00:24 PM begun to explore 1 times
25/12/2022 3:00:28 PM begun to explore 2 times
25/12/2022 3:03:27 PM Stopping...
25/12/2022 3:03:31 PM Has stopped

### 截图

![image](https://user-images.githubusercontent.com/77185235/209460367-27e38c80-3ad0-4d88-88cd-0e3a6c3ee193.png)
![image](https://user-images.githubusercontent.com/77185235/209460910-800c1cae-d425-4479-9fc8-476877db5805.png)

### 还有别的吗？

还有就是 #3137，#3029 的问题了。我觉得只是认不得角色，因为有些会招聘，有些不会。

**Comment by minecraftfen** [comment]
个人认为我提出的问题(#3137)可能和这个不一样，我的问题情况只是不招人，但是MAA还是能继续运行的，而且我的问题发生在官服
