### ISSUE TITLE
请问图中哪个是OTA更新包？好久没用了，今天点开release发现OTA包没了，不知道增量更新该下哪个

### ISSUE THREAD

**Issue by SunshineboyZj** [MaaAssistantArknights/MaaAssistantArknights#3185]
![-26a90a6cee7895cc](https://user-images.githubusercontent.com/81549837/209466052-0f241620-15e4-4189-83a5-270e381d4957.png)
请问图中**哪个是OTA更新包**呀。好久没用了，今天点开release发现OTA包没了。只能勾上自动更新让软件自己慢慢下

**Comment by ABA2396** [comment]
现在每个版本都有自己对应的 OTA 包，看[这里](https://github.com/MaaAssistantArknights/MaaRelease/releases)
