### ISSUE TITLE
活动的每日领取和周年庆的每日抽奖

### ISSUE THREAD

**Issue by zxmydmug** [MaaAssistantArknights/MaaAssistantArknights#3188]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

什么时候maa可以添加活动的单独的每日签到和周年庆的每日赠送的抽奖？

**Comment by minecraftfen** [comment]
同问
