### ISSUE TITLE
肉鸽提示未知错误

### ISSUE THREAD

**Issue by RiffraDD** [MaaAssistantArknights/MaaAssistantArknights#3196]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用mumu，可以正常连接，刷理智，但是肉鸽连接不了，选肉鸽就提示出现未知错误

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10304070/asst.log)

### 截图

<img width="1280" alt="2022-12-26 (1)" src="https://user-images.githubusercontent.com/99302406/209565995-f5d1ca9e-68d5-418a-8d48-bf2dea789e83.png">
<img width="1280" alt="2022-12-26" src="https://user-images.githubusercontent.com/99302406/209566000-648bb899-7bf7-42b8-ad69-0ae7fda53612.png">

**Comment by ABA2396** [comment]
选一下设置里肉鸽的主题
