### ISSUE TITLE
水月肉鸽无法选关

### ISSUE THREAD

**Issue by liugd18** [MaaAssistantArknights/MaaAssistantArknights#3197]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在进行水月肉鸽时，每进入新一层，会自动向右滑动，导致最左侧关卡离开屏幕范围，进一步导致无法选关

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10304520/asst.log)
凌晨两点多，每次肉鸽都会触发

### 还有别的吗？

mumu模拟器，win11，模拟器1920*1080

**Comment by liugd18** [comment]
补充：今日这个bug并没有复现，猜想可能是本层出现特殊效果（忘了叫什么了，上面那个红色的）时候才会出bug？

**Comment by IvoRacious** [comment]
这个可能是MuMu模拟器本身的问题，把键鼠设置初始化然后退出重进一下就好了

**Comment by MistEO** [comment]
每进入新一层，会自动向右滑动

MAA 滑的？还是游戏自动滑的，为啥会滑啊

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3178
