### ISSUE TITLE
完成后任务执行失败

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#3199]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

执行完成任务后无法正常关闭MAA，模拟器未成功关闭。
执行完成后关机同样失败。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10305509/asst.log)

### 截图

报错
![image](https://user-images.githubusercontent.com/74366156/209602276-67d149c5-b63a-418f-94e7-264c52b7d139.png)
软件
![image](https://user-images.githubusercontent.com/74366156/209602303-54d2a265-6984-4f6a-933f-5629cce9a947.png)

**Comment by kxdxzr** [comment]
![image](https://user-images.githubusercontent.com/74366156/209679562-057cda78-d626-4bc2-8a97-812d5d71cff8.png)
![image](https://user-images.githubusercontent.com/74366156/209679591-6b7c60e8-f2c9-49ea-8d81-362304b4195c.png)
![image](https://user-images.githubusercontent.com/74366156/209679627-61760280-c4fa-4d51-a2ef-6c65db782e3b.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10308648/asst.log)

**Comment by MistEO** [comment]
mumu 是管理员启动的，maa 也要管理员不然关不掉它
