### ISSUE TITLE
指定次数绑定关卡选择

### ISSUE THREAD

**Issue by Rithen** [MaaAssistantArknights/MaaAssistantArknights#320]
比如关卡选择剿灭，指定次数自动跳5（或上次使用值）；选择其他选项跳对应上次使用值

**Comment by MistEO** [comment]
不会去做，考虑这种使用场景：
我已经手动刷了一局，接下来需要 MAA 刷 4 局。先输入了 4, 然后选择了剿灭。结果自动变成了 5, 我没注意直接点开始了，浪费了 25 理智
