### ISSUE TITLE
建议：添加保全抄作业功能

### ISSUE THREAD

**Issue by yltx** [MaaAssistantArknights/MaaAssistantArknights#3200]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

能否添加保全模式的抄作业功能？挂机作业一大把  而人肉肝保全的任务是真的累而且枯燥（

**Comment by ABA2396** [comment]
已经在做了

**Comment by yltx** [comment]
> 已经在做了

好耶！

**Comment by ntgmc** [comment]
duplicate to#1600 #2340
