### ISSUE TITLE
MAA或者ADB模式是否跟UU加速器冲突

### ISSUE THREAD

**Issue by jackxsm** [MaaAssistantArknights/MaaAssistantArknights#3201]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

好几次后天挂着MAA打别的游戏，maa就与模拟器是去链接。而且重启MAA或者模拟器都不行，得重启电脑。想来想去，有可能跟网易UU加速器有关？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10306341/asst.log)

**Comment by ABA2396** [comment]
对的，开uu就要重连，或者你可以先开uu再连接模拟器

**Comment by jackxsm** [comment]
> 对的，开uu就要重连，或者你可以先开uu再连接模拟器

好吧，谢了。

**Comment by MistEO** [comment]
是 UU 的问题，之前已经有很多朋友提到过了。建议都去给 UU 提一下反馈，让他们尽快解决下。起码保证停止加速后，系统的网络配置能恢复到之前的状态，而不是把配置改了就不管了
