### ISSUE TITLE
MAAv4.8.4后直接执行任务无法启动模拟器

### ISSUE THREAD

**Issue by HikashiKi** [MaaAssistantArknights/MaaAssistantArknights#3202]
### 说说你遇到的问题？

前代版本直接执行任务后会自动唤起模拟器，但4.8.4后需手动开启模拟器。

**Comment by ABA2396** [comment]
484启动模拟器之后等待的延迟有问题，但启动模拟器的判断没变。如果是启动模拟器但连接失败485已经修了；如果是不会启动模拟器，
![image](https://user-images.githubusercontent.com/99072975/209659863-5ef649bf-b27f-4600-90ae-1d26cb06c703.png)
