### ISSUE TITLE
点击开始任务后需要手动启动模拟器

### ISSUE THREAD

**Issue by HikashiKi** [MaaAssistantArknights/MaaAssistantArknights#3204]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

点击开始任务后，系统无法唤起模拟器，需要手动启动模拟器

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10307879/asst.log)
2022-12-27 19:32:06.274后

**Comment by Notofnice** [comment]
+1，4.9.0-alpha.1下面选项选了，MAA打开后没有自动启动模拟器，需要手动打开模拟器
![image](https://user-images.githubusercontent.com/63146701/209680336-6206fa78-c8ce-4767-b75a-c0b460e260c7.png)

**Comment by ABA2396** [comment]
之前版本没有启动模拟器的日志，新版本加了点，看看日志里有什么信息

**Comment by ABA2396** [comment]
> +1，4.9.0-alpha.1下面选项选了，MAA打开后没有自动启动模拟器，需要手动打开模拟器 ![image](https://user-images.githubusercontent.com/63146701/209680336-6206fa78-c8ce-4767-b75a-c0b460e260c7.png)

我试了下路径填了 C:\Program Files\BlueStacks_nxt\HD-Player.exe 也是能开的，你试试看 v4.9.0-alpha.2 版本，还有问题的话发下日志
