### ISSUE TITLE
希望刷理智的“指定材料”功能能计入合成

### ISSUE THREAD

**Issue by minecraftfen** [MaaAssistantArknights/MaaAssistantArknights#3209]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

较高级材料合成需要不止一类低级材料(合成高级糖需要用到铁和锰就离谱)，实现逻辑估计会比较复杂，但稍低级的材料应该可以用较简易的逻辑计算合成吧

### 有什么好的想法？

说不定可以联合明日方舟工具箱/企鹅物流数据统计或者直接用自家仓库识别拓展成合成计算器？

**Comment by ntgmc** [comment]
指定材料是指定单个材料在刷到指定数量后停止刷理智，
因为现在刷理智的次数选择（不论是材料还是次数）只能选择第一个关的，  而剩余理智功能是不支持指定次数的（这个功能有待改进），
所以推荐方法是用明日方舟工具箱规划后按顺序刷，每刷完一个材料得手动换一下次数
