### ISSUE TITLE
自动关机导致Windows聚焦失效

### ISSUE THREAD

**Issue by Airthink** [MaaAssistantArknights/MaaAssistantArknights#321]
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8370324/asst.log)
![tmpF1FC](https://user-images.githubusercontent.com/62360056/160589598-7e0f4f00-f4e0-4934-b13f-a603b18f912d.png)
自动关机勾选后Windows的锁屏界面“windows聚焦”消失

**Comment by MistEO** [comment]
这个，，像是 Windows 本身的问题，自动关机就用了一个 `shutdown -s -t 60`, 没有别的东西了。。
