### ISSUE TITLE
肉鸽下完人暂停，需手动点继续

### ISSUE THREAD

**Issue by vista98** [MaaAssistantArknights/MaaAssistantArknights#3210]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，在打肉鸽的时候只要一下一个干员，就会暂停，然后就卡那了，手动点继续才可

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10311791/asst.log)

### 截图

https://user-images.githubusercontent.com/107916926/209751390-a32814a3-9818-40a2-bdf2-139368d02d84.mp4

### 还有别的吗？

模拟器：蓝叠5.9.300.6503 N32
系统：win10 22H2 19045.2364
设备：Redmi G 2021 Ryzen R7-5800H/3060

**Comment by ntgmc** [comment]
非肉鸽问题，部分机型，电脑开启暂停下干员后在全部需要自动战斗的情况都会出现该问题，
解决方法：将下图选项关闭即可
![image](https://user-images.githubusercontent.com/74061867/209753708-c8d9fb11-475a-43e3-bc1b-4798fe0d9366.png)

**Comment by vista98** [comment]
收到，我去试试

**Comment by MistEO** [comment]
暂停下干员 不太稳定，暂时也没找到什么太好的解决方案，之后可能会直接把这个删了
