### ISSUE TITLE
v4.9.0-alpha.2 肉鸽不下干员

### ISSUE THREAD

**Issue by onlookerLi** [MaaAssistantArknights/MaaAssistantArknights#3212]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

抓取干员等一切正常，但是从一关开始就不会下干员。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10312460/asst.log)
14:02-14:05

### 截图

![MuMu20221228140556](https://user-images.githubusercontent.com/96764403/209766220-c7f867ee-8804-4e4f-957a-608a63f9d56a.png)

**Comment by MistEO** [comment]
这个“暂停中”是你手动点的？还是 maa 点的

**Comment by onlookerLi** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by ntgmc** [comment]
> 这个“暂停中”是你手动点的？还是 maa 点的

很明显是他点的（我猜）

**Comment by onlookerLi** [comment]
> 这个“暂停中”是你手动点的？还是 maa 点的

是我手动点的 为了暂停好截图， 直到最后一个点数也没有下干员

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/209952679-530d605f-f6de-4261-bb7b-119f82451e7b.png)

你的模拟器分辨率比较奇葩，换个正常点的
![image](https://user-images.githubusercontent.com/18511905/209952753-f6c5daad-e703-4212-ad44-5d96c275e5c9.png)

**Comment by onlookerLi** [comment]
天..雀食是这个原因,虽然不知道以前为什么没关系，但是顺利解决了，非常感谢！

**Comment by onlookerLi** [comment]
> ![image](https://user-images.githubusercontent.com/18511905/209952679-530d605f-f6de-4261-bb7b-119f82451e7b.png)
> 
> 你的模拟器分辨率比较奇葩，换个正常点的 ![image](https://user-images.githubusercontent.com/18511905/209952753-f6c5daad-e703-4212-ad44-5d96c275e5c9.png)

天..雀食是这个原因,虽然不知道以前为什么没关系，但是顺利解决了，非常感谢！

**Comment by MistEO** [comment]
识别算法改了，现在对开始与否识别的更精确，但可能对分辨率带来的误差容错变低了
