### ISSUE TITLE
能否保留访问好友

### ISSUE THREAD

**Issue by SilenceMorning** [MaaAssistantArknights/MaaAssistantArknights#3216]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

**能否重新划分访问好友以及购物**，不是很缺某些材料，基本上都是刷完体力后自己买，有时候商店刷的东西不理想就会留着300左右的信用

**Comment by ntgmc** [comment]
我没太看懂你的需求的原因 我认为你的需求可以通过关闭【信用购物】功能解决？
![image](https://user-images.githubusercontent.com/74061867/209831551-5dc1b95d-b48c-4dea-89ef-2012522cb85f.png)

**Comment by SilenceMorning** [comment]
感谢作者百忙之中看到我的留言，不好意思没看到设置这边可以关。非常感谢您的回复！
&nbsp;


Elsword
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月28日(星期三) 晚上11:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 能否保留访问好友 (Issue #3216)





 
我没太看懂你的需求的原因 我认为你的需求可以通过关闭【信用购物】功能解决？
