### ISSUE TITLE
为啥会仓库识别天天报错呢？

### ISSUE THREAD

**Issue by IranksAdral** [MaaAssistantArknights/MaaAssistantArknights#3217]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

到底是哪里问题，每天都要占据debug文件夹容量……四个月来都有459M了OTZ就不一一上传了

### 日志文件

[Uploading asst.log…]()

### 截图

![{~}A9AR8K8WD}$M8@3K(GX9](https://user-images.githubusercontent.com/87361258/209888534-df7c230a-ecac-4d06-af90-a31844c50abc.png)

### 还有别的吗？

还有能不能下次带识别红票数量的……总是只能人工打

**Comment by IranksAdral** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10317040/asst.log)
怎么还会上传失败的？

**Comment by MistEO** [comment]
fixed
