### ISSUE TITLE
希望添加“完成任务后睡眠”的功能

### ISSUE THREAD

**Issue by zhongfly** [MaaAssistantArknights/MaaAssistantArknights#3218]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

当前软件支持完成任务后休眠，但尚不支持完成任务后睡眠，而我个人更偏爱使用睡眠(唤醒更方便)，因此希望能添加“完成任务后睡眠”

### 有什么好的想法？

在windows上支持“完成任务后睡眠”

### 其他内容
从官方介绍来看，睡眠是更普遍存在/可用的选项，而休眠“专为笔记本电脑设计，可能并不适用于所有电脑。（例如，具有 InstantGo 的电脑没有休眠选项。）”
https://support.microsoft.com/zh-cn/windows/%E5%85%B3%E9%97%AD%E7%94%B5%E8%84%91-%E6%88%96%E4%BD%BF%E5%85%B6%E8%BF%9B%E5%85%A5%E7%9D%A1%E7%9C%A0%E6%88%96%E4%BC%91%E7%9C%A0%E7%8A%B6%E6%80%81-2941d165-7d0a-a5e8-c5ad-8c972e8e6eff

**Comment by ntgmc** [comment]
@MistEO cmd 执行 rundll32.exe powrprof.dll,SetSuspendState 0,1,0

请注意：如果 Windows 10 激活了休眠功能的话，执行上述命令会直接进入休眠而非睡眠模式。

此时，可以使用如下命令来将休眠功能临时关闭掉，而最后一行表示在系统被唤醒后重新启用休眠功能：

powercfg -h off

rundll32.exe powrprof.dll,SetSuspendState 0,1,0

powercfg -h on
