### ISSUE TITLE
希望能加上当期活动还有几天，活动关卡已关闭的提醒；希望游戏任务执行到已关闭的活动关卡能报错/自动跳过执行下一项

### ISSUE THREAD

**Issue by akiriroll** [MaaAssistantArknights/MaaAssistantArknights#3219]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

今天照我以火关了我不知道，关卡选择FC6之后挂了半天maa没动静，浪费很多时间，maa也不跳过，游戏界面在终端界面空置很久
一般大家使用maa，都是打开到唤醒页，最多是游戏看板那里就开始一键长草，根本看不到终端那里活动还剩几天的提醒，感觉很容易出现不知道活动关了的情况，希望能在maa显示活动提醒。

### 有什么好的想法？

加在一键长草那页“今日关卡小提示”那边就可以

### 其他内容

今天选择FC6，活动关闭，MAA停在fight不报错也不跳过执行下一个任务，只能手动停止MAA的gui. Log截图
![0B89B3AF-107F-4473-9D87-E3ADF7DA88B5](https://user-images.githubusercontent.com/120661226/209904448-970a5320-4bad-4f42-8b36-6e2e9883f1d8.jpeg)

**Comment by ABA2396** [comment]
设置里如果打开了隐藏未开放关卡，在活动结束后会自动变成 当前/上次；如果打开了备选关卡，界面会提示关卡已关闭，并在导航的时候跳过，寻找备选里下一个开放的关卡。

只有都没有打开的时候才没有处理跳过导航，因为如果不更新的话，遇到了全开放等活动的时候就进不了图了。

**Comment by akiriroll** [comment]
> 

我确定我是打钩了“关卡选择隐藏当日不开放关卡”选项了的，没有打钩“使用备选关卡”，我自己手动“关卡选择”里的FC6也没有提醒关卡已关闭，在导航界面也没有跳过而是停在那里

**Comment by ABA2396** [comment]
> > 
> 
> 我确定我是打钩了“关卡选择隐藏当日不开放关卡”选项了的，没有打钩“使用备选关卡”，我自己手动“关卡选择”里的FC6也没有提醒关卡已关闭，在导航界面也没有跳过而是停在那里

那大概是日期设错了，我去看看

**Comment by ABA2396** [comment]
日期设成可领取时间了，应该是活动开放时间

**Comment by akiriroll** [comment]
了解了，谢谢大佬们，辛苦
