### ISSUE TITLE
勾选“使用aria2进行下载”后自动更新失败

### ISSUE THREAD

**Issue by FameOverflow** [MaaAssistantArknights/MaaAssistantArknights#322]
勾选“使用aria2进行下载”后自动更新失败，数次手动更新后，我取消勾选后自动更新成功了，应该考虑取消“使用aria2进行下载”作为默认设置

**Comment by MistEO** [comment]
确实有这个问题，不过解决方向不是取消默认勾选，而是修复 aria2 的 bug, 之后的版本会尝试修一下 aria2 下载不成功的问题
