### ISSUE TITLE
从v4.8开始的版本自定义连接出现问题

### ISSUE THREAD

**Issue by hashrushgo** [MaaAssistantArknights/MaaAssistantArknights#3220]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用cmd扫描adb在正常连接的情况下，MAA显示连接错误
![WWMUPGF5WDK LZRBU2WTB60](https://user-images.githubusercontent.com/92534105/209908600-41c19db0-e0ef-4f5d-9681-774d4aa249bc.jpg)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10317786/asst.log)

### 截图

![WWMUPGF5WDK LZRBU2WTB60](https://user-images.githubusercontent.com/92534105/209908611-2cfaf517-7bf7-4b76-be1e-b0fd51d2c076.jpg)

### 还有别的吗？

v4.7及之前的版本没有这个问题，可以正常使用

**Comment by MistEO** [comment]
试试兼容触控模式

**Comment by hashrushgo** [comment]
> 试试兼容触控模式

已解决，感谢
