### ISSUE TITLE
挂肉鸽必定在一层之内出现模拟器卡死的情况

### ISSUE THREAD

**Issue by shikieikiii** [MaaAssistantArknights/MaaAssistantArknights#3223]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

其他功能都正常，只有挂肉鸽走几步模拟器就会卡死，模拟器界面变透明或黑屏，不确定是模拟器问题还是maa的问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10318939/asst.log)

### 截图

![QQ图片20221229183459](https://user-images.githubusercontent.com/121610755/209939718-a8d02d91-bda0-4678-adb9-65cce26fc297.png)
![QQ截图20221229183506](https://user-images.githubusercontent.com/121610755/209939728-e9bedf28-b959-4efc-9694-041800c0031b.png)
![QQ图片20221229183524](https://user-images.githubusercontent.com/121610755/209939733-c5fb5231-8df9-4434-aceb-7360348c011c.png)

### 还有别的吗？

模拟器是雷电9 系统是win11

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/209944037-45a61980-9219-47ea-87ac-b01b10591260.png)

**Comment by shikieikiii** [comment]
> ![image](https://user-images.githubusercontent.com/18511905/209944037-45a61980-9219-47ea-87ac-b01b10591260.png)

原来如此，我也是刚换的雷电，抱歉没看到这条
