### ISSUE TITLE
希望会客室送线索添加开关

### ISSUE THREAD

**Issue by a342617810** [MaaAssistantArknights/MaaAssistantArknights#3229]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

希望添加一个开关:"会客室仅换班不送线索"
理由如下:方舟的线索生成随机性太大,总是会在某些时间稀缺某条线索,因此我平时保持这存储6条保底线索的习惯,所以希望maa的基建排班不要动我线索,我可以自己考虑线索要留还是要送,只要换人保证会客里的人别红就可以,谢谢.

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/1.1-%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md
![image](https://user-images.githubusercontent.com/99072975/215056306-5fb2be46-8209-4ec3-9c0d-b2942e9cf661.png)
