### ISSUE TITLE
未正确放置宿舍干员

### ISSUE THREAD

**Issue by Sakuma-Rei** [MaaAssistantArknights/MaaAssistantArknights#3232]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

写了宿舍固定一个车尔尼 实际未放置 并且不会放满（）其他没有发现问题 爱丽丝也没事

### 日志文件

https://user-images.githubusercontent.com/55101422/210045731-3ccffc31-9247-4d4e-996a-a54302b77fd9.mp4

### 截图

![Uploading 2022-12-30_152938.png…]()

### 还有别的吗？

蓝叠5国际版（？）就群里那个

**Comment by Sakuma-Rei** [comment]
https://user-images.githubusercontent.com/55101422/210046241-378b4302-cfef-42c1-90dd-58c05213575e.mp4
![2022-12-30_152938](https://user-images.githubusercontent.com/55101422/210046253-475addb9-d098-48f5-84b9-115fa3c0125c.png)
好像没传上 再试试

**Comment by Sakuma-Rei** [comment]
https://user-images.githubusercontent.com/55101422/210047153-81a1cb9f-9d0c-48e8-9d22-6bd6d5e0
![2022-12-30_152938](https://user-images.githubusercontent.com/55101422/210047168-dddf8d75-fad7-491b-9dda-363f137d2091.png)
7d1f.mp4

**Comment by Sakuma-Rei** [comment]
![1672387046815](https://user-images.githubusercontent.com/55101422/210047829-b857a9af-5285-46fb-bc94-6937cb3a6678.gif)
网址怎么还能换行啊（

**Comment by ntgmc** [comment]
> 网址怎么还能换行啊（

你插入图片插到另一个连接去了（

**Comment by ntgmc** [comment]
duplicate to #3102
