### ISSUE TITLE
自定义基建频繁切换

### ISSUE THREAD

**Issue by dundanjiang** [MaaAssistantArknights/MaaAssistantArknights#3234]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用一图流制作的基建排班设定下次换班为第二组，会在几十秒后自动切换回第一组（如图所示，想要设定为8点的排班，总是自动切回20点的），重新生成排班表也没有用，使用内置的排班表就没有问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10325528/asst.log)

### 截图

![1](https://user-images.githubusercontent.com/121685132/210092568-04b4d7a4-933d-41bb-bc6b-209dc904ebfd.png)

**Comment by MistEO** [comment]
因为内置排班表没设定时间。目前的时间设定逻辑近乎是强制的

**Comment by dundanjiang** [comment]
> 因为内置排班表没设定时间。目前的时间设定逻辑近乎是强制的

有什么方法可以解决吗，现在想用一图流的排班表

**Comment by MistEO** [comment]
在一图流里排的班，不要填时间就行了
