### ISSUE TITLE
自动使用加急许可在重启MAA后被取消

### ISSUE THREAD

**Issue by Nqiu97** [MaaAssistantArknights/MaaAssistantArknights#3235]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

设置自动公招中的"自动使用加急许可"此项设置打勾之后重启MAA将会被取消勾选

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10325590/asst.log)

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/210098003-3846a595-f219-4645-9b99-aa99b102234e.png)
既然是自动使用加急许可为什么不一次性全用完而是每次用几个呢

**Comment by MistEO** [comment]
by design
