### ISSUE TITLE
刷理智卡在主界面

### ISSUE THREAD

**Issue by Gehabulisk** [MaaAssistantArknights/MaaAssistantArknights#3238]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

体力尾数低于6导致选1-7刷关时无法进行？。（没传相关日志）
不明原因无法在主页面开刷关上次

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10326734/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/118157094/210122172-a9b71ba9-ad2e-4b45-8bd2-1fd33cba5ea5.png)
![image](https://user-images.githubusercontent.com/118157094/210122184-b6b51985-0174-4322-8a90-5932e3d5b70a.png)
![image](https://user-images.githubusercontent.com/118157094/210122219-8a9ddac9-9758-4365-931c-95af2b83cc85.png)

### 还有别的吗？

逍遥模拟器
曾在满体力135时触发过，121体力时触发过，在主菜单。这次是9x（我没看，等弹任务完成已经99体力了）
101还能触发错误

**Comment by ntgmc** [comment]
好像刷关和理智多少没关系 ，不管你理智多少maa都会尝试开始作战，然后如果理智不够，明日方舟就会弹是否要使用理智药或石头，maa才判断是否要使用

**Comment by MistEO** [comment]
报错的时候，卡在哪个界面了？

**Comment by ntgmc** [comment]
@MistEO 
https://user-images.githubusercontent.com/74061867/210129490-898fda32-75f2-47a9-867b-b4076cb30047.mp4

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/210137101-9b0f437b-03e5-4c3f-b3bb-568916d8b016.png)
不知道为啥这个 `终端` 的匹配得分很低，正常都应该是 0.99 往上。有设过异形屏适配啥的么

**Comment by MistEO** [comment]
和 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3212 是同一个问题

**Comment by ABA2396** [comment]
> 和 #3212 是同一个问题
> 
> ![image](https://user-images.githubusercontent.com/18511905/209952679-530d605f-f6de-4261-bb7b-119f82451e7b.png)
> 
> 你的模拟器分辨率比较奇葩，换个正常点的 ![image](https://user-images.githubusercontent.com/18511905/209952753-f6c5daad-e703-4212-ad44-5d96c275e5c9.png)

那看来也不是mumu才有这些分辨率.jpg
