### ISSUE TITLE
肉鸽不断重复选择难度

### ISSUE THREAD

**Issue by yegbert** [MaaAssistantArknights/MaaAssistantArknights#3239]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

所有功能均关闭，仅使用默认设置的肉鸽，进入选择难度后无反应，然后退出选择难度，探索次数+1，不断重复以上过程

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10326766/asst.log)

### 截图

<img width="592" alt="捕获" src="https://user-images.githubusercontent.com/32406107/210122988-1a5f29ee-f031-488a-ba51-d79a0a6952ce.PNG">
![Screenshot_20221231-105913](https://user-images.githubusercontent.com/32406107/210122990-ec1172ae-2bba-4acf-bca7-f5edf53c2990.png)

### 还有别的吗？

夜神模拟器
模拟器版本: 7.0.5.1001-7.1.2700221109
安卓版本: Android 7(32 bit)
系统版本: Windows10-64bit-16cpu
电脑型号: LENOVO-82JD
CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
总内存: 31.8 GB
可用内存: 23.4 GB
是否开启VT: 开启
渲染模式: OpenGL+
OpenGL版本: 4.6.0 NVIDIA 527.56
OpenGL渲染: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
是否独显: 开启
显卡1: Intel(R) UHD Graphics
显卡2: NVIDIA GeForce RTX 3060 Laptop GPU
防火墙: 开启(推荐关闭)
安装路径: D:\Software\Nox\bin
模拟器磁盘大小: 总共 128G, 剩余 110G

**Comment by ntgmc** [comment]
感谢你提供了这么多信息 但其实这个是要自己选好难度 maa不选难度
