### ISSUE TITLE
水月肉鸽挂机时闪退

### ISSUE THREAD

**Issue by mitu233** [MaaAssistantArknights/MaaAssistantArknights#3243]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

挂机半小时时maa闪退，可以加个闪退自动重启。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10328198/asst.log)

关键点为[2023-01-01 00:29:17.568]

### 还有别的吗？

蓝叠5国际版

**Comment by ntgmc** [comment]
都闪退了咋自动重启（）
除非搞个辅助进程来监控

**Comment by MistEO** [comment]
fixed
