### ISSUE TITLE
肉鸽中令的召唤物摆放优先级低，有其他无用干员时出现令召唤物不释放的情况，导致过关率下降，刷点数效率降低

### ISSUE THREAD

**Issue by qqqxppp** [MaaAssistantArknights/MaaAssistantArknights#3245]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by ntgmc** [comment]
你是否考虑过 maa会不会用小龙 但其实maa甚至不会合成大龙（因为策略的原因） 所以提高了小龙的优先级并不能保证提高胜率 反而还会导致别的干员放不下去 直到全部小龙放完（如果提高了优先级）
