### ISSUE TITLE
经常在完成某项换班的第一项如(power0 dorm0)后 跳出基建换班 并且不报错直接跳过后续换班

### ISSUE THREAD

**Issue by killnight** [MaaAssistantArknights/MaaAssistantArknights#3246]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

经常在完成某项换班的第一项如(power0 dorm0)后 跳出基建换班 并且不报错直接跳过后续换班.
如果无法完成至少应该报错以便手动操作补救.

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10328350/asst.log)

**Comment by ntgmc** [comment]
是自定义吗？还是maa默认

**Comment by killnight** [comment]
是一图流 的自定义

**Comment by killnight** [comment]
> 是一图流 的自定义

是一图流 的自定义

**Comment by ABA2396** [comment]
还没看log，估计是卡返回连按了两次，之前是不是也有一个因为返回卡死的 @MistEO

**Comment by killnight** [comment]
我有两个号 一个用端口 5555 另一个用端口5565
就是5565的经常出bug
5555的那个正常.

**Comment by killnight** [comment]
> 

卡返回连按两次应该可以优化掉吧.就算不能弹出是否要退出基建也不该直接点确认呀.
这问题开发者什么时候可以修一下.

**Comment by killnight** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10330966/asst.log)
连续4次基建换班.3次直接在power0 完成后跳出基建.
第四次终于完成了power1的换班 接下来到的换班又跳出了两次.不过不是成组类的换班所以没有手动干预.最后换班宿舍 dorm0 完成后又跳出了.下面的都没换.
真是无语了.跳出率100%
没有一次换班可以成功完成的.
