### ISSUE TITLE
点开maa显示找不到指定模块，无法打开

### ISSUE THREAD

**Issue by 1588656** [MaaAssistantArknights/MaaAssistantArknights#3247]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

重装了几个版本都不行，看不懂是什么原因QAQ

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10328399/gui.log)

### 截图

![QQED5`SD MW`JETVN~JN}W0](https://user-images.githubusercontent.com/121742186/210162711-0b819b86-cf98-495a-a7e5-89d76bdfe2e8.png)

**Comment by ntgmc** [comment]
What's your maa's version?
It is said that in 4.9.x version this bug have been fixed.
You can try to download the lastest version in beta version.

**Comment by MistEO** [comment]
文档里的方法都试了吗？

还不行ba把这个解压放到 maa 目录下试试
[win10rt.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10394214/win10rt.zip)
