### ISSUE TITLE
识别到是 EX 关卡就不继续刷，作为一个设置选项

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#325]
起因（容我不厚道的笑一会）

![$Y`_70Y4`QG_`Y4NZ5C{_P7](https://user-images.githubusercontent.com/18511905/161412340-c5fc0bfc-353c-4ca6-a42d-b6d25275385c.png)

可以通过 PenguinPack 的识别返回的 StageId 中是否包含 `EX` 字样，来进行操作。最好作为一个参数选项

**Comment by zzyyyl** [comment]
嘤嘤嘤，先让我哭一会儿
昨天电脑打了 EX 关，今天没多想直接上次作战然后就寄了，所以ui什么时候加上 EX 关停止刷的选项
~~（还好我就打了五六次意识到了马上停止）~~

**Comment by zzyyyl** [comment]
寄！今天又不小心刷 EX 去了，浪费一管理智

**Comment by zzyyyl** [comment]
快加个界面选项！

**Comment by zzyyyl** [comment]
来个人给 GUI 上做个本地化，`EX 关卡` -> `无奖励关卡`
