### ISSUE TITLE
将进酒IW-5无法识别掉落

### ISSUE THREAD

**Issue by minecraftfen** [MaaAssistantArknights/MaaAssistantArknights#3252]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://user-images.githubusercontent.com/42016099/210167543-12ace6ac-43da-4dab-baba-c528f6dea962.png)
我觉得这张图应该够说明问题了

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10328615/asst.zip)

**Comment by ntgmc** [comment]
更新到4.9.0了吗？

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/210169240-4956d273-d705-4aaf-83c1-f594cbecdefd.png)
