### ISSUE TITLE
建议加一个定时停止的功能

### ISSUE THREAD

**Issue by minecraftfen** [MaaAssistantArknights/MaaAssistantArknights#3255]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

肉鸽虽然可以限定次数，但是次数固定的情况下其消耗时间非常不确定。而且由于MAA会不停尝试重登，所以MAA运行期间相当于其他设备完全无法操作MAA正在控制的账号。此时如果是在启动到结束完完全全自动化的流程中，而且使用者完全无法控制MAA运行设备的时候，时间段控制就会很重要。加一个定时停止的功能应该能解决问题

**Comment by ntgmc** [comment]
可以通过Windows自带的计划任务来实现该功能 
先写个bat批处理程序，内容如下：
`taskkill /f /im maa.exe`
保存为C:\Users\Administrator\Desktop\1.bat
比如需要今晚8点停止maa运行
那么就使用cmd命令行运行以下命令：
`schtasks /create /sc once /st 20:00 /tn autotaskkillmaa /tr C:\Users\Administrator\Desktop\1.bat`
该命令的其他用法及其他参数请参考[Windows计划任务管理用法](https://blog.csdn.net/baidu_24752135/article/details/125742688)

**Comment by minecraftfen** [comment]
额，我好歹也写过代码，这个我倒是会啦
对这个功能需求较大的是电脑小白用户，这类用户应该在MAA的用户群中也占有不小的比例

**Comment by ABA2396** [comment]
问题就是肉鸽定时停止也是退不出那个界面的）

**Comment by minecraftfen** [comment]
#5575 那边给过答复了，我这边自己关掉吧（
