### ISSUE TITLE
EN 服 自动基建功能卡在宿舍放入干员

### ISSUE THREAD

**Issue by KiriyaXX** [MaaAssistantArknights/MaaAssistantArknights#3258]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

会在第三个宿舍放入干员的时候卡住，可以看截图

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10329342/asst.log)

最底下那行就是了

### 截图

![image](https://user-images.githubusercontent.com/57272409/210182672-6aa6d511-d462-4160-a095-06f000d51e28.png)
试了两个号都是一样的情况。虽然显示完成infrast，但停在这里会影响后续的操作

基建布局
![image](https://user-images.githubusercontent.com/57272409/210182726-d2264a11-e05a-48fe-9b24-52f1de4e404d.png)

MAA 设置
![image](https://user-images.githubusercontent.com/57272409/210182735-c35008db-9465-4ae8-9f30-6d3505f2dc9e.png)

### 还有别的吗？

操作系统：Win 10
模拟器：蓝叠 国际版 5.9.610.1005 Pie64
分辨率：3840x2160

**Comment by MistEO** [comment]
EN 服应该没有适配蹭信赖的功能，可以先把这个关掉凑合用（
