### ISSUE TITLE
肉鸽下不自动滑回关卡路线图最左侧导致无限循环放弃重开

### ISSUE THREAD

**Issue by bytekun** [MaaAssistantArknights/MaaAssistantArknights#3259]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

手动打过几次肉鸽后再开辅助不在选择关卡时自动滑动到最左侧，由于画面中没有可点的关卡会自动无限退出放弃， 目前解决方法是在选关画面时手动拖到左边

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10329697/asst.zip)

### 截图

![Snipaste_2023-01-02_00-53-52](https://user-images.githubusercontent.com/72883292/210187837-6379181b-c14a-40d9-825b-595bc5fad852.jpg)

### 还有别的吗？

MUMU模拟器，WINDOWS11

**Comment by MistEO** [comment]
是一进来就在最右边？还是 maa 莫名其妙滑动到最右边了？
