### ISSUE TITLE
开始肉鸽任务之后不动了

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#326]
![9FSUWEL7K`G _2N(JJHTP0L](https://user-images.githubusercontent.com/18511905/161412405-b4c8465a-69c3-49e8-946f-7ded888a9aa2.png)

![Q_Z19P$DJXSL%}ZOUI61X$K](https://user-images.githubusercontent.com/18511905/161412416-ce7e917f-fb28-4f27-8700-eed0d974cfe3.png)

[asst6-tail.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8403844/asst6-tail.log)

**Comment by zzyyyl** [comment]
看了log，应该是因为`Return.png`没match上，考虑是不是**文件损坏**或者**修改了task.json里与返回相关的任务**，感觉不太可能是代码的问题？
（问题在附件第8201行的所有任务全部failed导致ProcessTask不断retry）

**Comment by MistEO** [comment]
> 看了log，应该是因为`Return.png`没match上，考虑是不是**文件损坏**或者**修改了task.json里与返回相关的任务**，感觉不太可能是代码的问题？ （问题在附件第8201行的所有任务全部failed导致ProcessTask不断retry）

应该是缓存的问题。肉鸽界面的返回按钮和平时的返回按钮位置似乎有点不一样，cache 存了一下
