### ISSUE TITLE
建议增加外服借助战干员功能

### ISSUE THREAD

**Issue by JIENIGUI666** [MaaAssistantArknights/MaaAssistantArknights#3261]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

希望能够增加外服借助助战干员的功能，4.9.1更新助战干员仅支持国服，希望能够增加外服。

### 有什么好的想法？

希望能够增加外服借助助战干员的功能，4.9.1更新助战干员仅支持国服，希望能够增加外服。

### 其他内容

版本：4.9.1
模拟器：mumu（其他功能均正常使用）
忘了说了 我的客户端是日服

**Comment by liuyifan-eric** [comment]
你说的是借助战打OF1还是肉鸽助战还是其他的？
