### ISSUE TITLE
刷水月肉鸽时会卡死在选择难度页面

### ISSUE THREAD

**Issue by 666233j** [MaaAssistantArknights/MaaAssistantArknights#3263]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

好像是每月肉鸽更新的时候或是换号的时候重新打开肉鸽，点击开始探索，就会弹出选难度的页面，然后就卡死了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10330217/asst.log)

**Comment by ntgmc** [comment]
maa需要自己手动选难度，另外我测试【每月肉鸽更新的时候或是换号的时候重新打开肉鸽】都不会要重选难度，不知道你那为啥会这样。
非bug
