### ISSUE TITLE
针对水月肉鸽中招募干员优先顺序的建议

### ISSUE THREAD

**Issue by Ginko11** [MaaAssistantArknights/MaaAssistantArknights#3265]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

比如此时队伍已经同时招募了助战的山和古米 但是古米在游戏中并没有拉到精二 此时却会选择晋升古米而不是山 或者同时有临时招募 却会优先招募其他干员 在干员选择上不够妥当

### 有什么好的想法？

优先选择六星干员和三星干员 当干员本身没有精二的时候不会招募此干员
或是设置自由选项 让玩家提前设置好自己需求的优先顺序 或者提供几个招募模式供玩家选择

**Comment by WWPXX233** [comment]
我们无法了解那些干员是精2过的 但是选取的最低标准是已经精英1 50级
