### ISSUE TITLE
肉鸽卡在选人的界面

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#327]
![RLB1G(RJ$RM9}7S~QKI(P2](https://user-images.githubusercontent.com/18511905/161412517-f0fdaded-726a-452a-9425-3e7ba1f0d8b9.png)

[asst(5).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8403845/asst.5.log)

**Comment by zzyyyl** [comment]
看了log，有部分是`Roguelike1StageEncounterGiveUpRecruit`导致的问题，这个 task 在 `dev` https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/07bad47b0e64f610ee9b3415d486476d9ec0f3c0 已经被取缔。但是`dev`中应该仍有这个问题（因为我用dev的时候也遇到过）。

**发生根本原因可能是掉落物截图早了，点击的时候已经发生位移造成的。**

解决方案（可能）：给`Roguelike1ClickToDrops`加个前置延时。
