### ISSUE TITLE
建议退出时保留当前程序位置和大小

### ISSUE THREAD

**Issue by IranksAdral** [MaaAssistantArknights/MaaAssistantArknights#3270]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

每天都要从中间拖到右下角挺麻烦的，希望和模拟器一样固定位置，谢谢

### 有什么好的想法？

自动更新的按钮也一起移动吧？

**Comment by MistEO** [comment]
不知道咋弄，等个 WPF 大手子带带

**Comment by moomiji** [comment]
自动更新的按钮是指Windows更新通知、MAA的更新通知还是哪个组件吗？
能截个图看看吗？

**Comment by IranksAdral** [comment]
> 自动更新的按钮是指Windows通知、MAA的版本已更新通知（VersionUpdateViewModel）还是哪个组件吗？ 能截个图看看吗？

![H`1J{2}~D85N86( @ V~II](https://user-images.githubusercontent.com/87361258/213038321-e3f92d72-3820-4a3a-8f51-120599b1437e.png)
就是确认按钮

**Comment by moomiji** [comment]
好耶！乱糊，糊出来了！
