### ISSUE TITLE
建议更新软件的时候添加进度条

### ISSUE THREAD

**Issue by zgplunk** [MaaAssistantArknights/MaaAssistantArknights#3271]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前打开软件如果存在更新消息中心会弹出更新通知，但是不知道更新的进度，昨天（2023.1.2）我曾挂机超过一小时，直到我结束挂机也没有提示我更新完成开始安装。今天打开软件又是提示更新但很快就提示安装了，这样的情况会导致我不知道每次下载的情况。

### 有什么好的想法？

建议：
希望在下载更新的模块下实现一个进度条的功能这样便于知道更新下载的情况
或者：
可以在更新弹出的提示框增加一个百分比实时显示当前更新的状态
并且：
希望增加“重新下载”按钮便于重启下载进程

**Comment by ntgmc** [comment]
Duplicate of #2990 #2779 #2557
