### ISSUE TITLE
mumu模拟器执行傀影肉鸽刷取源石锭3小时左右崩溃

### ISSUE THREAD

**Issue by wangshengmianju** [MaaAssistantArknights/MaaAssistantArknights#3273]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

笔记本运行mumu模拟器
执行maa傀影肉鸽刷取源石锭
3小时左右崩溃
两次崩溃记录：
1.2023年1月2日23点-3日6点间
2.2023年1月3日10点-12点间
崩溃点位于任务完成界面

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10334684/asst.zip)

**Comment by MistEO** [comment]
fixed
