### ISSUE TITLE
基建换班BUG：制造站偶然出现未成功换班问题 (附视频)

### ISSUE THREAD

**Issue by AIMOCT** [MaaAssistantArknights/MaaAssistantArknights#3276]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

1. 基建换班：制造站，本应点进“选人界面”，但此时正好出现了加载转圈，导致未能成功进入“选人界面”。出现转圈的原因未知。（有时候，订单完成也会出现短暂转圈，但本次卡顿并非此原因。）
2. 基建换班：制造站，选择角色时，未成功点到相应人员，导致漏放人甚至一个不放的情况。（该问题已出现多次，目前只是顺带一提，等待复现）

### 日志文件

上述问题1，发生时间：1月3号，03::01:54 开始，MAA连续报了四次“砾、至简、槐琥”

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10337291/asst.log)

### 截图

https://user-images.githubusercontent.com/117655226/210378361-4d0c8bd7-ab5c-40b0-a7cc-7fbf226b0919.mp4

### 还有别的吗？

解决方案提议：能否增加一个检查的步骤，在换完所有班次后，再核对一遍当前所放置的干员，尤其是制造战，出问题最多。（只是建议）

**Comment by guozhuyang** [comment]
也有这个问题 但我是贸易站居多 孑和但书经常选不上
