### ISSUE TITLE
希望一键长草-关卡选择里的活动关能像其他材料关一样，在后面标明掉落材料

### ISSUE THREAD

**Issue by akiriroll** [MaaAssistantArknights/MaaAssistantArknights#3279]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题，一个懒人需求，新的ss/故事集/复刻有多个材料关需要刷取的时候，比如这次将近酒，为了确认关卡掉落材料需要点进关卡里面查看，非常的不长草，希望能优化一下

### 有什么好的想法？

像“关卡选择”里的其他材料关那样标明在后面就可以了，比如：
IW-6（装置）
PR-C（先/辅芯片）

**Comment by ntgmc** [comment]
好主意 但是我的建议是背下来（）

**Comment by ABA2396** [comment]
东西太多了，再加这儿几行的话星期天就超出范围了，看看有啥好办法
