### ISSUE TITLE
自动重连的开关

### ISSUE THREAD

**Issue by liu331860** [MaaAssistantArknights/MaaAssistantArknights#3280]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我在挂着MAA出门时想用手机上方舟却总被MAA的自动重连挤掉线。

### 有什么好的想法？

希望添加一个控制自动重连的开关。

**Comment by ntgmc** [comment]
Duplicate of #2780
