### ISSUE TITLE
带命令行参数启动gui

### ISSUE THREAD

**Issue by moomiji** [MaaAssistantArknights/MaaAssistantArknights#3282]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在feat: Support multi profiles and switch profile卫星落地前，我想先把里面的`命令行参数启动gui`的子功能先完善了。

该功能可以让用户通过命令行参数`临时改变` `一键长草`的所有可用参数，以便实现多个游戏串联长草（
同时也可让`一份配置文件保持最新`的同时，`临时改变`某些配置（例如命令行带特定参数时可启动后直接运行）

### 有什么好的想法？

辣么问题来了
1. 是作为隐藏功能还是写入docs
2. --help要本地化吗（输出多语言docs）
3. 如果本地化，能接受[`commandlineparser/commandline`使用的`Resource.resx`](https://github.com/commandlineparser/commandline/wiki/Help-Localization)吗？即卫星正在用的命令行解析器库

第2点否、或第3点是的话，就用commandlineparser/commandline（这个优雅些），否者用巨硬的预发行版System.CommandLine

**Comment by HydrogenDeuterium** [comment]
感觉命令行参数最有用的是希望能直接把adb的目标传进去
