### ISSUE TITLE
基建换班问题：因加载转圈导致漏放人 (附视频)

### ISSUE THREAD

**Issue by AIMOCT** [MaaAssistantArknights/MaaAssistantArknights#3283]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

目前定位到的问题点，和之前反馈的一致，包括漏放人、没放人、没进得去选人界面等等一系列情况，均是因为操作点击的时候正好出现了加载转圈，导致本次点击失效。
出现加载转圈的原因依然不明，也可能只是我的个例……

### 日志文件

[asst.bak 2023-01-04.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10345492/asst.bak.2023-01-04.log)

### 截图

https://user-images.githubusercontent.com/117655226/210594688-4f5ed91a-a4c3-4ad4-a377-bbefd456f894.mp4

**Comment by ABA2396** [comment]
之前猜到了（）推测是选人的时候刚好有干员回满心情或者有订单生成啥的需要联网的操作，然后卡了下。说起来判断干员有没有被选中应该挺好判断的吧？ @MistEO

**Comment by MistEO** [comment]
> 之前猜到了（）推测是选人的时候刚好有干员回满心情或者有订单生成啥的需要联网的操作，然后卡了下。说起来判断干员有没有被选中应该挺好判断的吧？ @MistEO 

缝缝补补，我想重写基建了（

**Comment by AIMOCT** [comment]
> 之前猜到了（）推测是选人的时候刚好有干员回满心情或者有订单生成啥的需要联网的操作，然后卡了下。说起来判断干员有没有被选中应该挺好判断的吧？ @MistEO

据我录到的三次看下来，当时应该没有这些巧合，我更倾向于认为这个卡顿就是因为点击本身造成的，毕竟出错的频率不算低

**Comment by killnight** [comment]
就是运行速度跟不上maa的判断速度.话说为啥要拼命按退出键.按退出键也就算了.弹出判断界面问要不要退出基建.还闪电般点是.
我只好盯着和maa抢点否. 要是点满了就退出基建了后面的活也不干了.这又是一个bug .三个bug缺一个都不可能造成基建中断

**Comment by killnight** [comment]
就是运行速度跟不上maa的判断速度.话说为啥要拼命按退出键.按退出键也就算了.弹出判断界面问要不要退出基建.还闪电般点是.
我只好盯着和maa抢点否. 要是点满了就退出基建了后面的活也不干了.这又是一个bug .三个bug缺一个都不可能造成基建中断

**Comment by killnight** [comment]
就是运行速度跟不上maa的判断速度.话说为啥要拼命按退出键.按退出键也就算了.弹出判断界面问要不要退出基建.还闪电般点是.
我只好盯着和maa抢点否. 要是点慢了就退出基建了后面的活也不干了.这又是一个bug .三个bug缺一个都不可能造成基建中断

**Comment by zzyyyl** [comment]
基建干员有复查了
