### ISSUE TITLE
定时运行时偶发报错

### ISSUE THREAD

**Issue by Nora331** [MaaAssistantArknights/MaaAssistantArknights#3286]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

之前发现早上8点的换班偶尔会没有换成，后来观察发现是会出现下方截图的这样一个报错，但是之后手动点击运行时就能正常运行，并且除了早上8点以外其他时间点的定时运行都没有这种问题，即使早上8点时报错之后也能正常运行。
自己尝试过强制替换ADB，更改触控方式（从MaaTouch改成Minitouch），不确定有没有改善（因为一段时间后又会出现这种情况）。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10348930/asst.log)
1月5日早8点定时运行时出现该情况，之后约10点半时手动点击了一下运行，中间没有重启过软件。

### 截图

![image](https://user-images.githubusercontent.com/85998594/210687841-3474d6bb-0bf2-4c39-8889-bda09473b9ab.png)
![image](https://user-images.githubusercontent.com/85998594/210690805-b12e2011-2acc-4463-86d5-7db7e37fa60d.png)

**Comment by ntgmc** [comment]
@Black1312
