### ISSUE TITLE
无法进行信用购物

### ISSUE THREAD

**Issue by Xzcy** [MaaAssistantArknights/MaaAssistantArknights#3287]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

近期更新后出现，Maa无法进行信用购物（甚至无法打开信用商店）
已经持续数个小版本，未改善

雷电模拟器，分辨率设定：1920*1080，DPI 600

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10349666/asst.log)

### 截图

https://user-images.githubusercontent.com/47129094/210712177-c8673537-6ec2-49eb-a585-ee1a26048721.mp4

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/210779416-16478c30-3cce-4c29-bb3f-d461ebf97383.png)
@MistEO 首页这几个字炼过么

**Comment by Xzcy** [comment]
后来通过移动助理立绘解决了，采购中心是个半透明按钮，识别大概被干员立绘干扰了
建议Mall出错时，提醒下尝试移动下助理立绘

**Comment by Xzcy** [comment]
> ![image](https://user-images.githubusercontent.com/99072975/210779416-16478c30-3cce-4c29-bb3f-d461ebf97383.png) @MistEO 首页这几个字炼过么
后来通过移动助理立绘解决了，采购中心是个半透明按钮，识别大概被干员立绘干扰了
建议Mall出错时，提醒下尝试移动下助理立绘

**Comment by Xzcy** [comment]
后来通过移动助理立绘解决了，采购中心是个半透明按钮，识别大概被干员立绘干扰了
建议Mall出错时，提醒下尝试移动下助理立绘

**Comment by MistEO** [comment]
> ![image](https://user-images.githubusercontent.com/99072975/210779416-16478c30-3cce-4c29-bb3f-d461ebf97383.png) @MistEO 首页这几个字炼过么

这个是模板匹配来着，看看得分改下阈值就好了
