### ISSUE TITLE
优化MAA的启动与加载速度

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#3288]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

把MAA放入机械硬盘，加载速度会很慢。虽然基本上都是秒启动，但是开始按钮是灰色的，需要将近加载1分钟才能才能开始连接模拟器进行各种操作。观察任务管理器，虽然读写压力很大，但是读取速度几乎没有。

### 有什么好的想法？

优化软件，尽量将必须的资源写到一起，提高在机械硬盘中的加载速度。

### 其他内容

![屏幕截图 2023-01-05 162054](https://user-images.githubusercontent.com/92417243/210735131-7870f310-b32a-4196-b5bb-c2ec6bd0aa31.jpg)

**Comment by MistEO** [comment]
写到一起 = OTA 包巨大无比，最近版本特地拆开的。之后可能会试着多线程读

**Comment by xiaoweiXX** [comment]
> 写到一起 = OTA 包巨大无比，最近版本特地拆开的。之后可能会试着多线程读

多线程读应该没什么用，机械硬盘上限就摆在那里了，不过这确实挺矛盾。

**Comment by MistEO** [comment]
或许可以构建个本地 cache，把全打包到一起（

**Comment by xiaoweiXX** [comment]
> 写到一起 = OTA 包巨大无比，最近版本特地拆开的。之后可能会试着多线程读

另外OTA包在哪里啊，Releases页面看不到OTA包，最近我都是MAA里面直接更新。

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaRelease

**Comment by xiaoweiXX** [comment]
> https://github.com/MaaAssistantArknights/MaaRelease

好家伙，这OTA包也不小啊。而且都是4.6或者4.7升级到最新版，也没有4.9.0升级到4.9.1啊

**Comment by xiaoweiXX** [comment]
> 或许可以构建个本地 cache，把全打包到一起（

要不大佬优化优化，给更新程序写个特性，每次更新完了自动打个cache把这些文件全整合到一起，下次更新直接再删掉这个cache然后重新打一个。

**Comment by ABA2396** [comment]
> > 或许可以构建个本地 cache，把全打包到一起（
> 
> 要不大佬优化优化，给更新程序写个特性，每次更新完了自动打个cache把这些文件全整合到一起，下次更新直接再删掉这个cache然后重新打一个。

这样的话大概就是更新时间++，不过每次开的时候等的时间应该是会少一点。多个小文件的读取确实很慢

**Comment by xiaoweiXX** [comment]
> v4.10.0 fixed

今天更新了4.10.0-beta3，实测加载速度还是和以前一样，并没有什么改变
![屏幕截图 2023-01-15 092949](https://user-images.githubusercontent.com/92417243/212533611-2e085b0f-5bed-462a-88e8-60d00c96993f.jpg)
