### ISSUE TITLE
夜神模擬器老闆鍵MAA無效

### ISSUE THREAD

**Issue by Arcelibs** [MaaAssistantArknights/MaaAssistantArknights#3289]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打開方舟後按下Ctrl ALT X老闆鍵隱藏，啟動MAA沒有反應
但是打開方舟後不使用老闆鍵，啟動MAA後正常運作

### 日志文件

2023/1/5 下午 05:35:17 正在連接模擬器……
2023/1/5 下午 05:35:17 正在運行中……
2023/1/5 下午 05:35:17 開始任務：Recruit

### 还有别的吗？

夜神模擬器，Android 7 64位元
我看早期用Win32 Api是沒辦法用老闆鍵的，後來改adb後還是會有這問題嗎?

**Comment by ntgmc** [comment]
不清楚这个老板键的原理 但既然用不了那就别用老板键呗

**Comment by Arcelibs** [comment]
> 不清楚這個老闆鍵的原理但是無論如何用不了那就別用老闆鍵唄

行吧，影響不大，只是遇到想來問下，我先把issue關掉了

**Comment by MistEO** [comment]
maa 窗口处于前台时，并且不打开模拟器，按老板键有没有反应？是不是和别的冲突了

**Comment by Arcelibs** [comment]
先不用這功能了，謝謝
