### ISSUE TITLE
刷理智/材料时连续作战时大概率显示上报失败，放弃上传企鹅物流

### ISSUE THREAD

**Issue by xhmtom** [MaaAssistantArknights/MaaAssistantArknights#3292]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

每次使用MAA的刷理智功能进行刷材料时只要战斗超过2场，后续的战斗有90％以上的概率显示“上报失败，放弃上传企鹅物流”。初步怀疑可能是战斗完成后游戏本体会有一个几秒的黑屏，MAA无法识别黑屏就按照未识别到材料掉落信息处理了。黑屏过后游戏本体会显示真正的结算界面，这时MAA可以识别并显示材料掉落信息，但由于不显示其他信息，不清楚此时识别到的信息有没有再次上传到企鹅物流。如果MAA在识别到材料掉落信息后会再次尝试上传到企鹅物流则本条反馈可以无视，否则因为可能影响到企鹅物流材料掉落信息而希望尽快修复。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10356753/asst.log)
上面的是4.8.1版本的日志。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10356795/asst.log)
上面的是4.9.1版本的日志。
问题从使用MAA以来一直存在，1月3日上午11:00后进行了较大规模的刷理智，此时问题较为明显。上传的截图也是这个时候的。日志中没有当时刷理智的记录，考虑到MAA有概率在运行一段时间后在点击停止按钮时卡死，之后需要手动关闭并且系统会报错，可能当时又发生卡死现象导致MAA未能及时保存信息到日志中，如果日志中有其他时段的刷理智信息也可以作为参考。

### 截图

![捕获](https://user-images.githubusercontent.com/121840468/210913288-f9706081-c9c9-4719-9869-6b5731ee69aa.JPG)
![捕获2](https://user-images.githubusercontent.com/121840468/210913328-288134d7-f680-4284-9f7e-0be2d4bb7437.JPG)
![捕获3](https://user-images.githubusercontent.com/121840468/210913347-c7c438f1-7ba7-49e7-9c36-84a0b4b5966c.JPG)

### 还有别的吗？

使用蓝叠模拟器5.10.0.1085 N32版本。
操作系统为WIN7旗舰版，64位系统。电脑为联想昭阳Y40-70，配置较低，但能较为流畅地在模拟器中运行游戏。
从日志上看，当时使用的MAA版本为4.8.1，但4.9.1版本也会出现这个问题。

**Comment by ABA2396** [comment]
从日志看是上报的时候创建进程失败了，之前也有issue提到过，但不知道是啥原因。在运行的时候内存够用吗？

**Comment by MistEO** [comment]
Win7 没有 curl，现在 maa 是直接调 curl 上传的。等之后改吧，短期内没法支持 win7 的上传
