### ISSUE TITLE
基建优化

### ISSUE THREAD

**Issue by tobiasde** [MaaAssistantArknights/MaaAssistantArknights#3293]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

基建能否丰富下功能

### 有什么好的想法？

能否增加清流、温蒂、异客组，两个都精2了，只有异客偶尔会去发电厂上班。菲亚梅塔如果能增加自动与巫恋换心情就好了。

**Comment by ABA2396** [comment]
可以试试自定义基建功能，如果干员全的话可以用maa自带的换班文件
![image](https://user-images.githubusercontent.com/99072975/210967919-b7801e7d-64e3-479f-b948-a699308bcdd3.png)
