### ISSUE TITLE
信用商店和领取日常奖励失败

### ISSUE THREAD

**Issue by dylanhz** [MaaAssistantArknights/MaaAssistantArknights#3299]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

设定每天早上9点定时执行，但是每次都在最后的信用商店和领取日常奖励出现错误，并且其他时间的定时执行没有此问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10365338/asst.log)

### 截图

![屏幕截图 2023-01-07 102655](https://user-images.githubusercontent.com/53137516/211127470-487d5980-8805-49d1-9213-bcedffb497bd.png)

**Comment by ntgmc** [comment]
你是不是开了《借助战赚信用》然后没有解锁火蓝之心of-1啊
在信用设置里面

**Comment by ntgmc** [comment]
> 你是不是开了《借助战赚信用》然后没有解锁火蓝之心of-1啊 在信用设置里面

这个功能每天只执行一次 所以你的第一次定时会报错

**Comment by dylanhz** [comment]
> > 你是不是开了《借助战赚信用》然后没有解锁火蓝之心of-1啊 在信用设置里面
> 
> 这个功能每天只执行一次 所以你的第一次定时会报错

解锁了的，我貌似看到他会卡在OF-1的结算页面，上次作战也是OF-1

**Comment by ntgmc** [comment]
那就
Duplicate of #3233

**Comment by ABA2396** [comment]
那个问题是中心没识别到，如果不改模型的话就加个replace

**Comment by ABA2396** [comment]
是卡在了OF-1的结算页面，不知道为啥没识别到
![image](https://user-images.githubusercontent.com/99072975/211134901-735b88fe-d43d-4cc6-ac48-b77486dccd06.png)
还有ClickCornerThenStop的位置也得改下
![@_QSA9 B}I~(@BAMECHD$V](https://user-images.githubusercontent.com/99072975/211134934-1877ed43-e85c-44b7-9484-28a0084a709a.jpg)
这样刚好刚好点了没用
