### ISSUE TITLE
模拟器挂肉鸽 电脑自动重启

### ISSUE THREAD

**Issue by Ohanasama** [MaaAssistantArknights/MaaAssistantArknights#3301]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

电脑挂肉鸽必定会重启，挂日常偶尔会重启   我两台电脑 这一台有问题  我希望能找到原因  我也换过模拟器 重装过游戏

### 日志文件

[Uploading asst.log…]()

**Comment by ABA2396** [comment]
你的日志没发上来。既然另一台电脑没事，建议先检查一下这台电脑的配置及运行时的负载情况。

电脑重启的可能性很多，可能会因为多种原因导致崩溃重启。常见的原因包括：
- 硬件故障，例如硬盘、内存或电源故障。
- 软件故障，例如操作系统、应用程序或驱动程序问题。
- 病毒感染，可能会损坏系统文件或破坏系统的稳定性。
- 过度的负载，例如系统中运行的应用程序或进程太多，或者硬件资源不足。

如果电脑经常崩溃重启，建议尝试以下方法：
- 检查并更新硬件驱动程序。
- 扫描并清除病毒。
- 卸载不必要的应用程序和服务。
- 检查内存和硬盘使用情况，如果过高，可能需要升级硬件。

**Comment by Ohanasama** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10365965/asst.log)
我重新上传一下日志  看看有没有帮助

**Comment by MistEO** [comment]
重启是啥现象，直接黑屏了？还是自动关机了

**Comment by Ohanasama** [comment]
突然自动关机重启

**Comment by ABA2396** [comment]
日子里确实没啥信息，因为重启日志记录直接就断了，而之前的信息也是正常的。建议还是先检查电脑配置和运行情况。

**Comment by MistEO** [comment]
> 突然自动关机重启

麻烦不要惜字如金，把你的现象详细描述一下，是突然黑屏死机了，还是出现了 “正在关机……” 界面（就像正常关机一样），还是什么其他现象。

难道要我们猜你的问题是什么吗？

![image](https://user-images.githubusercontent.com/18511905/211186439-cd9a922f-04d8-441e-ac72-f0fd5c5e77f0.png)

**Comment by Ohanasama** [comment]
就是一点开始自动肉鸽，三个干员没选完，电脑直接黑屏关机，然后重启了，没有界面没有提示。有时候自动公招完，到基建弄了几个干员也会这样黑屏重启

**Comment by MistEO** [comment]
讲不清楚就录个视频吧

**Comment by Ohanasama** [comment]
https://user-images.githubusercontent.com/122142695/211186906-d2ed5f88-7144-4724-b09b-e01724989f66.mp4

视频三倍速

**Comment by MistEO** [comment]
感觉像是电脑硬件的问题，可能是显卡 CPU 过热之类的，去售后问问吧
