### ISSUE TITLE
水月肉鸽多触控模式助战及战斗结算界面卡住需要手动点击

### ISSUE THREAD

**Issue by tianfeng1412** [MaaAssistantArknights/MaaAssistantArknights#3302]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

水月肉鸽在选择好干员并勾选使用助战后在识别干员界面会出现卡住的状况，在选择干员后没有按跳过并且没有进入下一步，在关卡中没有正确的选择干员下场（即在有近卫 辅助 奶的情况下在下近卫后即使cost99也没有下下一个干员，本操作仅在mmatouch出现）在通关结算界面不会点击到领取奖励界面（所有触控模式）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10365785/asst.log)1月6日晚上22.00

### 截图

作业八群bluestack app player 2023-1-06 23-35-59（100m太大放不上来）

**Comment by KiriyaXX** [comment]
傀影肉鸽也是有一样的问题
小号用MAA 借助战刷肉鸽，助战干员选择令，选择了令之后会卡在立绘界面
![image](https://user-images.githubusercontent.com/57272409/212462621-1757aa30-021a-4bfb-8f51-230d0f7a41aa.png)

开始作战后也不会下干员
![image](https://user-images.githubusercontent.com/57272409/212462731-a2857472-1f82-4c7c-8f60-e33925c52dce.png)

用的是minitouch
蓝叠模拟器
