### ISSUE TITLE
无法更改连接设置

### ISSUE THREAD

**Issue by Neixfang** [MaaAssistantArknights/MaaAssistantArknights#3304]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

4.9.1版本，自动升级后无法连接mumu模拟器，依据提示想要更改连接设置，然而无法更改连接设置

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10367502/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/8574140/211176085-b4840104-7e6f-4fbd-854e-91f33ab2cc3f.png)
![image](https://user-images.githubusercontent.com/8574140/211176094-419b9f7c-2d2d-48bc-948b-80a916c0c63e.png)

**Comment by Neixfang** [comment]
重新使用了4.6.13 release 可以连接

**Comment by ABA2396** [comment]
看看log里提示的绿字

**Comment by ABA2396** [comment]
你点了开始当然修改不了，要停止之后才能修改

**Comment by ABA2396** [comment]
4.7之后触摸改成了minitouch，mumu原来应该是不支持的，要替换adb或者用兼容触控（就是原来的点击方式）
