### ISSUE TITLE
建议自动公招先看完所有公招再确认公招，以避免公招券少于公招槽位时错过高星Tag的情况

### ISSUE THREAD

**Issue by minecraftfen** [MaaAssistantArknights/MaaAssistantArknights#3305]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

四个公招槽位开满之后，公招券很容易用完，因此规划公招券用在哪个槽位会很重要，否则很可能错过高星Tag。

### 有什么好的想法？

建议先把四个槽位都识别一遍，然后根据结果处理完了再根据星级确定公招投入顺序。

**Comment by ABA2396** [comment]
那你可以在票少的时候取消勾选自动招募3星（）
