### ISSUE TITLE
借用好友助战开局肉鸽时识别干员百炼嘉维尔出现问题

### ISSUE THREAD

**Issue by Zhang-Jia-Qi** [MaaAssistantArknights/MaaAssistantArknights#3307]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽固定开局干员为百炼嘉维尔，并且借助好友助战，此时助战列表中有百炼嘉维尔，但MAA无法识别并刷新，多次刷新如果都恰好无法识别选择自带的五星开局。bug稳定触发，但是没有实验是否对所有助战干员有效。
自己查看log之后发现有时百炼嘉维尔会被识别为“百”，其他干员都正常，仅在借助战时生效，对傀影和水月肉鸽都生效。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10367589/asst.zip)
包含多次开局，举例：上午10：22时那次开局出现了一次无法正确识别的情况，刷新后正常

### 还有别的吗？

夜神模拟器海外版，windows10系统

**Comment by WLLEGit** [comment]
10:22那一次从log上看应该是正确招募了才对。

第一次百炼嘉维尔在列表最右边，只露出一个“百”字。（像素x为1129，很接近1280）

> { 百: [ 1129, 0, 30, 31 ], score: 0.999182 }

刷新之后正确识别了（时间 10:22:20.152）（精二90级百嘉）

> AnalyzeChars append  百炼嘉维尔 [ 976, 569, 100, 23 ] 2 90 0 2 90

然后也正确点击了二次确认界面的“招募助战”按钮（10:22:22.058）

> found { 招募助战: [ 810, 507, 92, 29 ], score: 0.999977 }

**Comment by WLLEGit** [comment]
我再看看log，如果可以的话麻烦在出现百嘉但没有招募的时候截一下图（拿模拟器自带的截图工具），因为我一直用的百嘉助战没有出现这个问题，没图片测试不了bug在哪

**Comment by Zhang-Jia-Qi** [comment]
是的，百炼嘉维尔往往出问题都是显示在助战列表最右边的时候的

**Comment by Zhang-Jia-Qi** [comment]
可以考虑直接屏蔽对离边缘过近的干员名称的识别，翻页以后再看
