### ISSUE TITLE
肉鸽建议直接设置用户可编辑的干员和关卡权重

### ISSUE THREAD

**Issue by Zhang-Jia-Qi** [MaaAssistantArknights/MaaAssistantArknights#3308]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

水月肉鸽有时候抓太多其他干员，导致三层前基本抓不到主C，如果通过手动设置降低一些AI喜欢抓的干员的权重来省希望，或许AI会打到更高层（）

### 有什么好的想法？

观察到log中给每个干员都设计了抓取权重，建议把这个权重存储在哪告诉用户让他们知道到哪里去编辑权重，或者直接开发一个权重编辑页面

**Comment by MistEO** [comment]
在 `resource/roguelike/recruitment.json` 中，但现在每次更新都会被覆盖掉
