### ISSUE TITLE
提几个小建议~~

### ISSUE THREAD

**Issue by yuaowang** [MaaAssistantArknights/MaaAssistantArknights#331]
首先非常感谢各位的工具~  我自己也为了刷舟游做了一个基于python的脚本，您的工具给我带来了很多新的想法，感谢~

下面列出几个试用后的反馈：
1. 每一步执行的较慢。这可能是在速度和准确率上的权衡，也可能是其他一些问题导致的。如果可以优化就很好了。
2. 基建能不能加入优先的固定搭配，比如优先使用二狗+能天使这种固定搭配，以及优先使用迷迭香+絮雨
3. 信用购物能不能加入优先购买的配置项

我也会研究下您的代码，但是因为c++不是我的常用语言，可能需要的时间比较长。

再次感谢

best

**Comment by MistEO** [comment]
感谢反馈  

1. 每一步执行的较慢。  
    没法优化，由于 adb 截图实在是太慢了（最快的设备上也要 200ms），如果操作的很快会导致截图的时候和点击的已经不是同一帧画面，导致出错。后期可能会通过 socket 的方式优化一下 adb 的速度，但并不能解决这个问题
2. 基建能不能加入优先的固定搭配。
    - 优先使用二狗+能天使  
        当前就是支持的，如果没有使用，考虑可能是 bug，或者有其他效率更高的组合
    - 优先使用迷迭香+絮雨
        这是一个跨设施的组合，暂时不支持。不同设施间联动实在太复杂了，后期有可能会弄，也可能弄不出来_(:з」∠)_
3. 信用购物能不能加入优先购买的配置项  
    4.0 版本正在开发中，可能会支持该功能

**Comment by MistEO** [comment]
> 感谢回复~
> 
> 2和3两个问题能够理解。
> 
> 1这个问题我的方案是python通过win32gui对窗口截图进行操作，大概一张截图14毫秒左右。这方面不是我的专长，我的理解adb应该是个服务，如果通过adb截图确实比较统一和简单，但是速度上肯定是要慢很多的。有空的话可以试试看用win层面的接口截图，这样会快很多。不过也会带来一些问题：1. 需要获取窗口句柄。这个有利有弊，利在于便于双开，弊在于可能用户需要在开始之前增加一个鼠标操作去选择当前任务对应的窗口。2. 对于有些模拟器的适配性可能会有问题，目前我试过mumu和蓝叠应该都是可以的，但是必须选择的是模拟器游戏画面的句柄，如果选择模拟器窗体外框的句柄画面就是黑的。
> 
> 自动操作的速度提升不仅可以提高效率，主要是能让这个脚本变得更酷hhhhhh所以提了一下~
> 
> 期待4.0~~

最一开始就是使用 Win32 Api 来操作的，弊端很多，后来才换成了 adb，主要有
- 模拟器窗口不能最小化、不能老板键隐藏（Windows 不渲染最小化的窗口，截出来是黑屏）
- 不同模拟器窗口边框大小不同，需要针对每个模拟器单独适配，工作量很大
- 窗口不能缩小，分辨率变低了，大幅影响识别效果

adb 反而是复杂的方案。Win32 API 几行就写完了（跑

**Comment by yuaowang** [comment]
了解~ 那没问题我关掉这个啦~
