### ISSUE TITLE
误送退坑好友线索问题

### ISSUE THREAD

**Issue by FushengTao** [MaaAssistantArknights/MaaAssistantArknights#3310]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

大功能：基建换班
   小功能：送好友线索

问题1：比如一天刷两次MAA。第一次刷的时候好友A缺线索1，但是他这一天都没上线，晚上刷的时候会继续送线索1
问题2（只是担忧，不确定是否会发生）：就是送退坑好友线索的问题，万一某一天ta回坑了，看见自己像垃圾箱一样塞了这么多线索，会不会很尴尬

### 有什么好的想法？

想法1：将线索的功能从基建的功能里拎出来，单独运行
想法2：当日不会送好友第二遍：每天设置缓存，当天清除（感觉没有啥必要）
想法3：建立额外的数据库，手动设置“豁免名单”，然后排除掉那些退坑的好友，避免尴尬
（还是能力不足看不懂源码，如果有能力的话想直接手搓一个）

**Comment by ABA2396** [comment]
退坑的应该不会在你列表前面吧，这个好像是别人送你了就会往前排（？），线索本来也是会过期的，一直不上线上线看得到也就这几天的

**Comment by FushengTao** [comment]
odkodk，感谢
