### ISSUE TITLE
借助战打信用时，会出现过快点击进入被借干员预览界面，导致流程卡住的情况

### ISSUE THREAD

**Issue by akiriroll** [MaaAssistantArknights/MaaAssistantArknights#3312]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，偶尔会遇到的偶发情况，maa操作会快速点击到被借干员界面（根本看不到上一级竖条的好友干员界面），然后停在那里无法自行解决，自行之后maa报错导致mall任务失败
![屏幕截图_20230108_132725](https://user-images.githubusercontent.com/120661226/211181863-bde91d33-7041-450d-b870-b57888ae364c.png)
会卡在如上面一样的预览界面中，而且过程飞速，看不到选择好友干员界面比如下面这种界面
![屏幕截图_20230108_132836](https://user-images.githubusercontent.com/120661226/211181891-7028fa0e-775e-4ccb-8cf4-3f2589754249.png)
这次观察到的情况是在借桃金娘的时候出bug，之前一次观察到有一样情况是借极境的时候，不知道会不会和借投锋有关？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10367789/asst.log)
![屏幕截图_20230108_132420](https://user-images.githubusercontent.com/120661226/211181808-cbaf51f7-8fa1-4f09-9d28-a8bcced0c8b3.png)
问题出现的时间点，但是后续任务失败是我自己操作退出预览界面让战斗进行，然后自行暂停导致的
之前最近一次的mall任务也报错，不清楚是不是这个原因

### 还有别的吗？

模拟器：蓝叠5
操作系统：win11

**Comment by akiriroll** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10367797/asst.log)
![屏幕截图_20230108_134026](https://user-images.githubusercontent.com/120661226/211182236-8170ca3b-b559-4e0e-92fc-1fb4bf06ebdc.png)
这次出现了正常借助战，正常进图，在战斗正常进行的情况下，无任何干涉，maa报错mall失败

**Comment by HydrogenDeuterium** [comment]
和借谁没关系 我今天卡在白铁上的
