### ISSUE TITLE
雷电模拟器打肉鸽卡死

### ISSUE THREAD

**Issue by voice-317418365** [MaaAssistantArknights/MaaAssistantArknights#3313]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

雷电模拟器使用MAA打肉鸽大概10分钟就会卡死
![image](https://user-images.githubusercontent.com/35912159/211184586-c7254d5c-24e9-4d0b-a5eb-1f58dd30c24c.png)
![image](https://user-images.githubusercontent.com/35912159/211184590-2c9f1644-fbe9-4888-b061-aca0fa6d34d4.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10367869/asst.log)

### 还有别的吗？

雷电模拟器9.0.33
win10

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/211186267-65d26f58-4840-4a3c-b675-c94b8e280ba6.png)

**Comment by xiaoweiXX** [comment]
雷电9.0有问题，MAA刷肉鸽要不停用adb截图，估计是这个操作让雷电9.0申请的内存越来越多，最后达到或者超过物理与虚拟内存的上限，让雷电卡住甚至是直接崩溃。建议退到雷电4.0，这个版本没问题

**Comment by sophielong2002** [comment]
> 



> 雷电9.0有问题，MAA刷肉鸽要不停用adb截图，估计是这个操作让雷电9.0申请的内存越来越多，最后达到或者超过物理与虚拟内存的上限，让雷电卡住甚至是直接崩溃。建议退到雷电4.0，这个版本没问题

对 我也是
![image](https://user-images.githubusercontent.com/93809259/211711137-f82a7485-ce59-45ce-9bd0-f6dfe344f895.png)
