### ISSUE TITLE
电脑高占用自启动会导致连接失败

### ISSUE THREAD

**Issue by 23333233** [MaaAssistantArknights/MaaAssistantArknights#3317]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打游戏时自动启动模拟器有时会连接失败，重启maa和蓝叠都无法连接，需要重启才能解决

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10368494/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/119745162/211198200-47596cf6-ef2f-41a3-9be2-6354be849272.png)

### 还有别的吗？

系统是win11，模拟器是蓝叠国际版

**Comment by MistEO** [comment]
网易的问题，建议给他们提个 BUG https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3107
