### ISSUE TITLE
日服刷理智任务出错

### ISSUE THREAD

**Issue by take010** [MaaAssistantArknights/MaaAssistantArknights#3318]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

日服刷一次或几次后就提示游戏崩溃，重新启动，然后就任务出错，直接提示完成任务了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10370299/asst.log)
2023/1/9 11：59左右

### 截图

![图片](https://user-images.githubusercontent.com/122247476/211238990-c3ad1ecd-8d34-4671-9772-6488cc40b3be.png)

**Comment by take010** [comment]
![图片](https://user-images.githubusercontent.com/122247476/211239440-4c9e6c0a-5d49-49be-b28f-9e01e7f56739.png)
补充

**Comment by MistEO** [comment]
把 `resource\global\YoStarJP\resource\template\EndOfAction.png` 这个文件删一下
