### ISSUE TITLE
昨天突然爆内存卡死了

### ISSUE THREAD

**Issue by SUPCGY** [MaaAssistantArknights/MaaAssistantArknights#332]
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8408638/asst.log)
昨天晚上开着两个蓝叠国际64版，不知道什么时候电脑突然卡死，按软件平时吃内存情况（内存占用高，随着时间推移越来越高）推测可能是爆内存了，过了一两分钟系统把卡死的应用关了就恢复正常了，事发突然无法判断到底是谁爆的，还是同时爆的

**Comment by MistEO** [comment]
maa 吃内存主要是因为第三方库 `PaddleOCR` 存在比较严重的内存泄漏问题，但是其他 OCR 库的识别效果确实又比不上飞桨，所以这个问题短期内可能没有办法解决
