### ISSUE TITLE
开机后第一次进游戏时有概率卡死或响应速度异常慢

### ISSUE THREAD

**Issue by CottePutman** [MaaAssistantArknights/MaaAssistantArknights#3320]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

当电脑开机后**第一次打开模拟器**和maa时，有一定概率会卡住或长时间无操作，已经碰到过很多次了。
个人的解决方法是重启模拟器，大概率可以解决该问题。
重启maa无法解决该问题。
下述的日志文件里应该记载了两次启动模拟器和maa的记录。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10370317/asst.log)

### 还有别的吗？

模拟器：BlueStack 5.10.0.1085 P64 （4核 4GBRAM 60FPS 1920x1080 240DPI OpenGL）
操作系统：Win 11 
电脑配置：R9000K

**Comment by MistEO** [comment]
MAA 卡住了，还是模拟器卡住了？卡在哪了

**Comment by ABA2396** [comment]
第一次卡住很可能就是在找截图方式，那玩意能不能加个超时时间

**Comment by CottePutman** [comment]
> MAA 卡住了，还是模拟器卡住了？卡在哪了

这里是log与发生时对应的视频，不过这次MAA还在操作，但是操作间隔很长

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10412692/asst.log)

https://user-images.githubusercontent.com/39736063/212354420-62c296ad-a78b-4225-8c91-495f8892dd59.mp4
