### ISSUE TITLE
关于选定自定义基建排班后由于没有部分干员导致放弃填充该设施内干员的建议

### ISSUE THREAD

**Issue by 0O0o0oOoO00** [MaaAssistantArknights/MaaAssistantArknights#3322]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我在选定333_layout_for_Orundum_3_times_a_day.json后，由于没有但书和灵知，maa在长时间(约30min)寻找后放弃填充该设施的干员

### 有什么好的想法？

1. 降低再次寻找的次数
2. 在自定义基建排班的设置中增加“若缺少部分干员则自动填充”的选项，建议默认开启

### 其他内容

本次日志如下，由于我后续自己修改json并重启maa导致未能记下准确的时间，问题大约发生在19:30-20:00间
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10373093/asst.log)

**Comment by ABA2396** [comment]
内置的都是对应基建比较极限的配置，干员要求都比较高，其他的文件里倒是写了提示，333的文件是后加的，估计是忘了
![image](https://user-images.githubusercontent.com/99072975/211358571-c2446178-0b8a-4b41-a89e-e2eb60f34e22.png)

**Comment by MistEO** [comment]
这些组合换任一个人都是没意义的，比如巫恋组没巫恋随机上一个，那还不如整个组都别上。而且如果随机上一个，用户还不容易看出来有问题，不如报个错
