### ISSUE TITLE
日服傀影肉鸽无法识别卡住

### ISSUE THREAD

**Issue by 466895132** [MaaAssistantArknights/MaaAssistantArknights#3324]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在刷日服肉鸽时候   这几个界面会无法识别导致任务卡住     除了这两个还有一个背景是带帽子的商人的不期而遇   也会卡  没截到图

### 日志文件

看日志就是截图匹配不到结果 一直重试

### 截图

![1](https://user-images.githubusercontent.com/11262966/211348267-bf28c636-5f99-4a4e-9c53-11d06d23d0d8.png)
![2](https://user-images.githubusercontent.com/11262966/211348317-b4ab8e7c-b909-47b9-a877-6c91f4bf11a4.png)

**Comment by MistEO** [comment]
所以发下日志

**Comment by 466895132** [comment]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10378661/asst.zip)
补个日志    这个是卡在雕刻师那个截图的日志   从9:10分之后

**Comment by 466895132** [comment]
![3](https://user-images.githubusercontent.com/11262966/211573206-dfc20ae5-8079-417f-a9ed-109214f23c5b.png)
补截图
这个界面也会卡
