### ISSUE TITLE
没办法自动刷理智

### ISSUE THREAD

**Issue by MeteorStream** [MaaAssistantArknights/MaaAssistantArknights#3326]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

下午运行的时候还很正常，更新之后基建也可以正常运作，但是刷理智的时候，maa点了下终端，之后就没有任何反应了。iw-6也还没有关闭，不知道为什么

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10381188/asst.log)
时间为17：00后

### 截图

![image](https://user-images.githubusercontent.com/49871236/211516368-3fe43c6b-468b-4a86-b2c6-0675229343f1.png)

### 还有别的吗？

蓝叠，win11

**Comment by ABA2396** [comment]
#3327
