### ISSUE TITLE
同时开启多个活动导致无法在将进酒关卡正常刷理智

### ISSUE THREAD

**Issue by gingerbreap** [MaaAssistantArknights/MaaAssistantArknights#3327]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

开启领航者#2后，终端置顶的活动变成了新开的领航者试炼，导致MAA无法正常导航进入将进酒活动。即使在终端界面自行选择将进酒活动进入，MAA也无法继续执行任务。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10381312/asst.log)

### 截图

![Snipaste_2023-01-10_17-50-41](https://user-images.githubusercontent.com/27958821/211518672-dc571298-8d2e-4de0-b6c9-d917b5480363.png)

### 还有别的吗？

模拟器：蓝叠国际版 5.10.10.1013 P64
操作系统：Windows 10 22H2 (19045.2364)

**Comment by ABA2396** [comment]
这个没啥办法，只有一个活动的之后只有左下角有文字信息，而开了新活动又只有中间有图片信息，这个图标也拿不到，现在只能通过更新资源文件去改（发新版本）。反正就不到一天了，不管了）
