### ISSUE TITLE
日服基建森蚺识别错误，公招资深标签识别结果

### ISSUE THREAD

**Issue by nightofknife** [MaaAssistantArknights/MaaAssistantArknights#3328]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

群友反馈的部分干员识别问题，公招资深标签识别错误

### 日志文件

[asst.part01.rar.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10382404/asst.part01.rar.zip)
[asst.part02.rar.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10382407/asst.part02.rar.zip)

日志太大了
打个压缩包
我用winrar分卷压的

### 截图

![I4@Q@3}Z5GSZJU4G137_UH5](https://user-images.githubusercontent.com/73384329/211545517-da82d62e-4913-43d3-b04b-ecaa15d0aed0.png)
森蚺的错误识别
![SGCQIK01~ N}3U{D~T$57W8](https://user-images.githubusercontent.com/73384329/211545877-0938bf9e-24e8-4d70-a89a-4d0fa718b23f.png)
![(HG5@DRA~O)(C$HO$UZ`CS](https://user-images.githubusercontent.com/73384329/211545957-afc2a27b-f178-4b8c-9894-2d6d5632152f.png)
资深词条的错误识别

### 还有别的吗？

还有些其他的识别替换问题
我再去确认一下吧
话说
这个替换直接写
resource\global\YoStarJP\resource\task里面？

**Comment by MistEO** [comment]
似乎修过了？最近有几个日服识别相关 PR （但我没仔细看x

**Comment by cat122802501** [comment]
已经修复资深和高资公招tag识别问题了，森蚺和其他一些干员排班的识别率也提高了。更新一下maa应该就能用了。
