### ISSUE TITLE
夜神模擬器執行一段時間後遊戲崩潰

### ISSUE THREAD

**Issue by Arcelibs** [MaaAssistantArknights/MaaAssistantArknights#3331]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

夜神模擬器，執行一段時間後遊戲崩潰腳本停止

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10387765/asst.zip)

出錯時間點 : 1/10晚上11點後

### 还有别的吗？

夜神模擬器，安卓7 64位元，四核心4G記憶體

系統資訊參照如下
![image](https://user-images.githubusercontent.com/49543451/211690470-5f8e7e23-54d2-45ee-a6d3-eb3d299d292a.png)

**Comment by MistEO** [comment]
夜神崩了给夜神提个bug吧。。

**Comment by jane885511** [comment]
是模擬器、遊戲還在運行，但MAA報遊戲崩潰?
