### ISSUE TITLE
对于在训练室中的【艾丽妮】单独判断

### ISSUE THREAD

**Issue by LollipopGeneral** [MaaAssistantArknights/MaaAssistantArknights#3333]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在使用【艾丽妮】对其他干员进行专精技能的途中，某一等级技能专精已结束，第二次还没开始的时候。
使用基建换班的功能，会使得【艾丽妮】进入宿舍休息，从而导致专精BUFF时长失效。

### 有什么好的想法？

对于在训练室中的【艾丽妮】单独判断，不要单纯的丢入宿舍。

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/211746745-c1fbd4df-33b2-4911-b4cd-383867ea38e8.png)
