### ISSUE TITLE
【WSA】成功连接，但是 MAA 在  2k 以及 1080p 分辨率下均运行失败

### ISSUE THREAD

**Issue by Nova-Noir** [MaaAssistantArknights/MaaAssistantArknights#3334]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

根据几个相关的 Issue #3285 等进行了测试，发现无法解决。

一开始使用的是 2560x1440 的分辨率，观察 `asst.log` 推测是 `OCR` 识别失败，所以更换了 1920x1080 测试。更换后查看 `asst.log`，发现 `OCR` 识别成功，但是似乎 input 指令没有运行成功（全程游戏为全屏前台且无遮挡）

# 做出的尝试
- 更换 `adb.exe`
- 重新安装 `arknights`
- 重新安装 `MAA`
- 管理员模式打开 `MAA`

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10389430/asst.log)

重新生成了 `asst.log` 以方便检查，不过更换分辨率之后出现失败需要很久，所以没有运行到那里。

### 截图

# 配置界面
![image](https://user-images.githubusercontent.com/68760718/211732391-f91a219a-4986-4485-88f3-3be82f18fc81.png)
![image](https://user-images.githubusercontent.com/68760718/211732372-7e8b60a1-d0f3-468c-b73d-e96a83d2f1e6.png)

# `adb` 截图
![screen](https://user-images.githubusercontent.com/68760718/211734599-79672e17-5012-4ac1-a17f-a9c48b186aac.png)

### 还有别的吗？

# 运行环境
**windows 版本:** Windows 11 Pro22H2 22621.963
**WSA 版本:** Version 2211.40000.11.0
**MAA 版本:** V4.9.1

**Comment by Nova-Noir** [comment]
在偶然的情况下我发现：1920\*1080 分辨率下，使用 `MaaTouch` 和 `ADB Input` 模式，在反复按下 F11 在全屏以及窗口化全屏切换的情况下，点击可以正常运行？？？ 暂时不清楚这到底是 wsa 的原因还是

**Comment by ntgmc** [comment]
> 在偶然的情况下我发现：1920*1080 分辨率下，使用 `MaaTouch` 和 `ADB Input` 模式，在反复按下 F11 在全屏以及窗口化全屏切换的情况下，点击可以正常运行？？？ 暂时不清楚这到底是 wsa 的原因还是

![image](https://user-images.githubusercontent.com/74061867/211736025-6e79a045-87a7-4e93-8095-32bcb9515675.png)
这个可能是原因

**Comment by Nova-Noir** [comment]
是的，所以我尝试更换了 1080p。
这个的具体表现是每按一次 f11 就会成功执行一个 input 操作，但是也只会执行一个。

**Comment by Nova-Noir** [comment]
我尝试了在唤醒界面执行 `adb.exe -s 127.0.0.1:58526 shell input tap 1138 897` 也没有成功
之后，我在开发者选项中打开了 `Pointer Location` 并且获取了 `任务` 的位置，尝试使用 `adb.exe shell input tap 1572 1114`，仍然没有成功打开界面。

推测是 wsa 的问题？
![my_touch](https://user-images.githubusercontent.com/68760718/211740498-db7a049f-ce89-47ff-8f21-cc889f5cc943.png)
![adb_touch](https://user-images.githubusercontent.com/68760718/211740681-8a7dbba7-2dda-4dc3-9e64-5d273d5b4339.png)

**Comment by Nova-Noir** [comment]
> 我尝试了在唤醒界面执行 `adb.exe -s 127.0.0.1:58526 shell input tap 1138 897` 也没有成功 之后，我在开发者选项中打开了 `Pointer Location` 并且获取了 `任务` 的位置，尝试使用 `adb.exe shell input tap 1572 1114`，仍然没有成功打开界面。
> 
> 推测是 wsa 的问题？ ![my_touch](https://user-images.githubusercontent.com/68760718/211740498-db7a049f-ce89-47ff-8f21-cc889f5cc943.png) ![adb_touch](https://user-images.githubusercontent.com/68760718/211740681-8a7dbba7-2dda-4dc3-9e64-5d273d5b4339.png)

在经过我进一步的测试后（分辨率是 2560\*1440），刚启动游戏时窗口大小为 1600\*938 ，此时我按 F11 全屏后会出现一个图标（见右下角），按了之后提示因为程序不能自动调整分辨率所以要重启游戏，点击之后游戏会以全屏模式重启，此时进行 adb input 操作是可行的。
（然而这个操作的逆过程，即从这个全屏再按 F11 回到窗口化，此时同样有右下角的图标，但是按了这个图标之后重启游戏，adb input 操作仍然是不可行的。且在我关闭所有 wsa 相关的东西，仅通过 MAA 执行唤醒操作时，也只会生成一个不可以进行  adb input 操作的 arknights 应用）
![image](https://user-images.githubusercontent.com/68760718/211745158-3c405ccd-9b01-48c1-90ea-20c355e2e3d6.png)

这让我推测是不是 adb input 存在一个焦点的问题？然而全程我都是仅开启 arknights 一个应用的，所以不知道具体是什么原因。

**Comment by schwarzichet** [comment]
我可以汇报一次成功的案例。在我按下F11全屏运行WSA明日方舟之后，MAA自动招募任务成功运行。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10396637/asst.log)
时间点：2023-01-11 18:06:05~2023-01-11 18:06:39
在 2023-01-11 18:06:12 的时候有一次失败，但是接下来的重试是成功的。好像是我一开始没有在主界面的问题。
此时使用`adb.exe -s  exec-out screencap -p > screen.png`截图出来如下
![screen](https://user-images.githubusercontent.com/15522755/211939012-31d9d546-714d-4712-9fe5-d493ea7858a8.png)
完全没有黑边


但是接下来我按下F11回到最大化窗口化运行的，MAA自动招募任务就会失败。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10396661/asst.log)
时间点：2023-01-11 18:13:21~2023-01-11 18:13:46
此时使用`adb.exe -s  exec-out screencap -p > screen.png`截图出来如下
![screen](https://user-images.githubusercontent.com/15522755/211938795-3b4544e5-1d91-4900-be42-8296c22262ca.png)

我只有一个屏幕，分辨率 3840×2160。我也只开启了明日方舟一个应用。截图时明日方舟是否在前台似乎没有区别。

推测应该是黑边问题占主要因素。使用WSA时adb截屏默认会对应Windows本机屏幕分辨率，为app界面自动补上黑边，导致失败。

```
adb shell
wm size
```
结果是
```
Physical size: 3840x2160
```

不知道能否在ocr的阶段做出适配忽视黑边

**Comment by Nova-Noir** [comment]
你这个应该是黑边问题。

我的问题应该是由于没有开启DeveloperOptions 下的 一个选项导致的。

详情可以见 https://github.com/microsoft/WSA/issues/205#event-8204915097

**Comment by Nova-Noir** [comment]
同时，我的问题出现的原因主要是由于有两块屏幕导致的焦点变化（我在测试 tap 命令的时候它实际上点了另一块 1080x1920 的屏幕）

这导致了点击的错误（然而在截图阶段完全看不出来）

所以，针对使用 wsa 的用户提出以下建议：

1. 在使用单屏幕时，要求 16：9 比例 720p 以上，推荐使用全屏模式。
2. 在使用多屏幕时，打开 WSA 选项里的 `Single machine UI automation` 并在最后开启你的主屏幕。

![](https://user-images.githubusercontent.com/27746781/211851165-682ebe9a-4dd5-4861-b5f3-ef96a5391863.png)
