### ISSUE TITLE
日服肉鸽模式特定关卡无响应

### ISSUE THREAD

**Issue by cat122802501** [MaaAssistantArknights/MaaAssistantArknights#3335]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽模式下进行到雕匠与石像会进行不下去，MAA变成无响应状态。
环境：日服

### 日志文件

日志文件太大压缩后github无法识别分卷后缀，所以压缩了两次。

[分卷2.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10390260/2.zip)

[分卷1.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10390255/1.zip)

**Comment by cat122802501** [comment]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10391641/asst.zip)

补个日志

**Comment by MistEO** [comment]
看日志里好像都是 `天翔ける怪盗・劇団篇` 这个识别错了，没看到石匠与雕像，话说这个是后面一批的关卡，日服已经上线了吗？

**Comment by MistEO** [comment]
gamedata 的日服 json 里没找到这个关卡。等个有缘的大佬手动补充下 https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/global/YoStarJP/resource/tasks.json#L1977

**Comment by cat122802501** [comment]
![B81J8ED{0T0EW}F}F5FOTRX](https://user-images.githubusercontent.com/10574556/221108536-39780436-349c-4d7a-91c3-59bae827433a.png)

肉鸽这个月更新之后出的新bug
皇帝争论这个事件会无限自动消费原始锥直到消耗完 然后卡关

**Comment by cat122802501** [comment]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10821276/asst.zip)

日志文件

**Comment by liuyifan-eric** [comment]
麻烦你注意观察一下，卡关的几个不期而遇是不是都有不能选的背景是源石锥的选项

雕匠那关我怀疑有没有可能是文字描述太长进入关卡的按钮位置不一样？你可以也观察一下吗

**Comment by cat122802501** [comment]
> 麻烦你注意观察一下，卡关的几个不期而遇是不是都有不能选的背景是源石锥的选项
> 
> 雕匠那关我怀疑有没有可能是文字描述太长进入关卡的按钮位置不一样？你可以也观察一下吗

那应该是写的逻辑判定出问题了，ocr识别源石锥然后不停的选，直到把源石锥耗光无法选变成死循环，应该改逻辑判定
