### ISSUE TITLE
逍遥模拟器在退出模拟器时会报错，并且退出失败

### ISSUE THREAD

**Issue by Zetros090** [MaaAssistantArknights/MaaAssistantArknights#3338]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用逍遥模拟器选择完成任务后“退出maa和模拟器”，会在退出时报错，弹出错误窗口，并且无法关闭模拟器

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10394783/asst.log)

### 截图

![QQ截图20230112014711](https://user-images.githubusercontent.com/74809363/211880839-b7ab8e29-3444-4cae-a71b-87ecf48f1e45.png)

**Comment by Zetroles** [comment]
和另一个无法正常启动多开的问题一样，都是因为需要管理员启动
但是在4.7.x（之前说错了不是4.8）不需要
更新后不知道为什么需要管理员权限才能启动和退出模拟器
