### ISSUE TITLE
v3.1.0 唤醒功能会卡在月卡每日领取界面

### ISSUE THREAD

**Issue by miyouzi** [MaaAssistantArknights/MaaAssistantArknights#334]
模拟器：蓝叠 Hyper V

系统：Windows 10 21H2 19044.1586

[asst_20220405.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8417276/asst_20220405.log)

![maa_error](https://user-images.githubusercontent.com/24269465/161737100-40d0ce97-be8b-4b7a-a153-4952f16e58c0.png)

**Comment by MistEO** [comment]
为什么自动登录了呀，没有出现 `开始唤醒` 的按钮，然后我看通知栏还弹出了个啥，是装了什么插件么

卡住的原因就是 `开始唤醒` 按钮没识别到

**Comment by MistEO** [comment]
> 为什么自动登录了呀，没有出现 `开始唤醒` 的按钮，然后我看通知栏还弹出了个啥，是装了什么插件么
> 
> 卡住的原因就是 `开始唤醒` 按钮没识别到

哦 这个不是官服？

**Comment by miyouzi** [comment]
> > 为什么自动登录了呀，没有出现 `开始唤醒` 的按钮，然后我看通知栏还弹出了个啥，是装了什么插件么
> > 卡住的原因就是 `开始唤醒` 按钮没识别到
> 
> 哦 这个不是官服？

B服
