### ISSUE TITLE
刷傀影肉鸽时卡在选择难度页面

### ISSUE THREAD

**Issue by 666233j** [MaaAssistantArknights/MaaAssistantArknights#3340]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

一直弹出请选择探索难度的提示，水月肉鸽之前也会这样，不想修的话可以直接在maa设置上整个提示要求选难度就好了，和添加终端一样

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10397825/asst.log)

**Comment by ntgmc** [comment]
你好 详细介绍看了吗？
![image](https://user-images.githubusercontent.com/74061867/212205430-bb3e4275-31da-47e1-bdf0-0a91510a6c80.png)
