### ISSUE TITLE
WSA 允许多显示器用户手动选择显示器

### ISSUE THREAD

**Issue by D3adEr1c** [MaaAssistantArknights/MaaAssistantArknights#3341]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

#3285 
#3334 
WSA 多显示器的开启顺序影响
`adb.exe -s 127.0.0.1:58526 shell "dumpsys window displays | grep -o -E cur=+[^\ ]+ | grep -o -E [0-9]+"`
的输出顺序，会导致 MAA 点击错误的位置

### 有什么好的想法？

允许 WSA 用户自行选择显示器

**Comment by D3adEr1c** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3285#issuecomment-1379809163

**Comment by Nova-Noir** [comment]
尝试了包括修改注册表 `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\` 、更改线缆顺序等方法，均没有成功修改显示器编号

在多显示器的情况下，`adb.exe -s 127.0.0.1:58526 shell "dumpsys window displays | grep -o -E cur=+[^\ ]+ | grep -o -E [0-9]+` 的顺序是由显示器编号从高到低排列的。
> 在我的例子里，我的主屏 2560x1440 显示器编号为 1 ，副屏 1080x1920 显示器编号为 2；
> 该命令的输出结果为
> > 1080
> > 1920
> > 2560
> > 1440

这个问题只影响 `adb shell input tap` 而不影响截图 OCR 操作，每个人显示器编号不同也不能直接固定写死 [:-1] 或是 [0]，所以选择显示器的功能对于 WSA 用户是较为有用的

推荐在`设置->连接设置->连接配置` 中添加一个 `WSA 模式`，设置后在开始连接时增加一个判断，如果 `adb.exe -s 127.0.0.1:58526 shell "dumpsys window displays | grep -o -E cur=+[^\ ]+ | grep -o -E [0-9]+"` 获取的结果多于 1 个，则弹出一个窗口选择序号或根据配置项添加一个序号（可以在 `连接配置` 中单独增加一个输入框）

具体逻辑伪代码大概是
```python
screen_size = result_of_adb("dumpsys window displays | grep -o -E cur=+[^\ ]+ | grep -o -E [0-9]+")
if connection.type == ConnectionMode.WSA and len(screen_size_list := parse_each_two_line(screen_size)) > 1:
    screen_size = screen_size_list[config.wsa_screen_idx if config.wsa_screen_idx is not None else choose(screen_size_chooser)]
else:
    screen_size = screen_size_list[0]
```
由于我暂时没有阅读过 MAA 的代码，所以对 MAA 的语法规范以及实际实现不甚了解，也无法就此提一个 PR，抱歉❤️

**Comment by MistEO** [comment]
> 浅浅扫了一下，好像目前的实现是通过 displayFormat="%d%d" 来获取的分辨率，可否更改成正则结果数组以方便实现？

是个好主意

**Comment by D3adEr1c** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/5c7372c6db1ee2265ade72e4633d459f720560ab
Close
