### ISSUE TITLE
在启动Maa时出现外部组件异常的提示

### ISSUE THREAD

**Issue by PianCat** [MaaAssistantArknights/MaaAssistantArknights#3342]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启动Maa时出现外部组件异常的提示并且卡住闪退

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10398192/asst.log)

### 截图

![Snipaste_2023-01-12_12-26-38](https://user-images.githubusercontent.com/50688679/211976220-9336273f-3b09-4359-9af8-52885bf48911.png)

### 还有别的吗？

版本是4.10.0-Alpha1

**Comment by 983464425** [comment]
我也出现这问题了，5次大概有一次不报错

**Comment by U98de** [comment]
v4.10-a2出现这个问题，a1正常，把文件路径中的中文删掉就好了）

**Comment by 983464425** [comment]
> 

我所有路径不存在中文的，不是中文路径问题
