### ISSUE TITLE
将不同渠道服的资源（关卡数据、ocr预训练数据等）作为单独下载的模块

### ISSUE THREAD

**Issue by RadonTRD** [MaaAssistantArknights/MaaAssistantArknights#3347]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前所有渠道服的资源文件都是包含在maa中的，但往往不会同时具有所有渠道服的使用需求。

没有使用需求的渠道服的资源文件就带来了不必要的空间占用。

### 有什么好的想法？

是否能将不同渠道服的资源文件制作成单独下载的模块，只下载有需求的资源。

比如只有官服和日服需求，就只下载官服和日服的资源；若追加了台服需求，则可以追加下载台服资源。

**Comment by MistEO** [comment]
一两百 M，其实无所谓吧（

**Comment by RadonTRD** [comment]
> 一两百 M，其实无所谓吧（

100多M确实不大，说占空间我自己也觉得多少有些牵强，所以只是提一个建议，没有多强烈的要求，如果不考虑做直接close掉也无妨。

**Comment by ABA2396** [comment]
多语言的翻译有用到对应的客户端文件（比如指定材料的内容），比如日本人玩国服，界面语言是日语，那就得下国服和日服的文件，如果要改的话还得改下这玩意

**Comment by RadonTRD** [comment]
> 多语言的翻译有用到对应的客户端文件（比如指定材料的内容），比如日本人玩国服，界面语言是日语，那就得下国服和日服的文件，如果要改的话还得改下这玩意

那确实有点麻烦了，就不考虑了吧。
