### ISSUE TITLE
更新v4.10.0-alpha.2后无法运行，提示外部组件发生异常

### ISSUE THREAD

**Issue by YRFBK** [MaaAssistantArknights/MaaAssistantArknights#3348]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

v4.9.1使用正常，更新v4.10.0-alpha.2后无法运行
尝试使用完整包覆盖，依旧无法运行
直接解压完整包打开，亦无法运行

电脑系统为 Windows 11 专业版 22H2 , AMD 5700X + AMD Vega 64

报错信息如下：
 在 MaaWpfGui.AsstProxy.AsstLoadResource(Byte* dirname)
   在 MaaWpfGui.AsstProxy.AsstLoadResource(String dirname)
   在 MaaWpfGui.AsstProxy.LoadResource()
   在 MaaWpfGui.AsstProxy.Init()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.RootViewModel.<InitProxy>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10406029/asst.log)
问题出现的大致时间点为2022/1/13 05:00

### 截图

![image](https://user-images.githubusercontent.com/72265872/212181566-da108f29-9e46-4f46-9f7c-2dbecb3d7ae2.png)

**Comment by ntgmc** [comment]
![image](https://user-images.githubusercontent.com/74061867/212205098-65946031-e440-4f0b-b534-f61240c74efc.png)
请检查一下您是否含有中文路径，如果有，请更改它或等待下一次的更新修复

**Comment by MambaStill** [comment]
更改为英文路径后就不报错了。

**Comment by chy5301** [comment]
同样的问题，改为英文路径后解决，等一个修复

**Comment by YRFBK** [comment]
改为英文路径后解决，感谢
