### ISSUE TITLE
下载时百分比出现错误 v4.10.0-alpha.1

### ISSUE THREAD

**Issue by alphagocc** [MaaAssistantArknights/MaaAssistantArknights#3349]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

下载时百分比出现错误

### 日志文件

日志中无有关内容

### 截图

<img width="201" alt="image" src="https://user-images.githubusercontent.com/28982331/212215596-bf0d72f1-0bde-4c42-9fa0-1e9c6328ff72.png">

**Comment by moomiji** [comment]
@MistEO 你那直接commit，我就不pr了
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/d989739981db071e80df1c66e473c729b50e8073/src/MaaWpfGui/Main/VersionUpdateViewModel.cs#L848
改成
```
100 * value / maximum,
```
改了没保存到，pr里的GIF也有这个错误，疏忽了
