### ISSUE TITLE
每天第一次启动时会无法自动进入战斗

### ISSUE THREAD

**Issue by SilnaMasiro** [MaaAssistantArknights/MaaAssistantArknights#3351]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

设置的是脚本自动打开模拟器，等待60秒后自动刷取日常，但是每天第一次唤醒时疑似会误触导致刷理智失败，最近几个版本经常出现这种问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10407836/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10407838/asst.bak.log)

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3365 修了
