### ISSUE TITLE
v4.10.0-alpha.2 启动时崩溃，报错“外部组件发生异常”

### ISSUE THREAD

**Issue by pangbo13** [MaaAssistantArknights/MaaAssistantArknights#3352]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

v4.10.0-alpha.2版本更新后，在启动时弹出报错“外部组件发生异常”，已尝试删除后重新下载，依然报错

![image](https://user-images.githubusercontent.com/51732678/212230841-78e9a4cb-f998-4b6b-a5ac-29b0fd7f821f.png)

详细信息如下
```
 在 MaaWpfGui.AsstProxy.AsstLoadResource(Byte* dirname)
   在 MaaWpfGui.AsstProxy.AsstLoadResource(String dirname)
   在 MaaWpfGui.AsstProxy.LoadResource()
   在 MaaWpfGui.AsstProxy.Init()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.RootViewModel.<InitProxy>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10407930/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/51732678/212230841-78e9a4cb-f998-4b6b-a5ac-29b0fd7f821f.png)

### 还有别的吗？

Windows 10 专业版 19045.2486
Windows Feature Experience Pack 120.2212.4190.0

和模拟器应该无关，还没有开始连接模拟器

**Comment by ntgmc** [comment]
Duplicate of #3348 
请查看该issue来解决。
