### ISSUE TITLE
自动肉鸽的时候，游戏如果闪退，无法自动启动游戏的bug

### ISSUE THREAD

**Issue by Dryhten-tech** [MaaAssistantArknights/MaaAssistantArknights#3353]
### 在提问之前...

- [x]  我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x]  我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述
目前使用的是maa4.10.0。自动肉鸽的时候，游戏如果闪退（也就是大退回模拟器主页），会出现无法自动启动游戏的bug，已经测试过好几次了确实存在这个bug
情景还原很简单，开个自动肉鸽，然后等脚本随便打一点，手动把游戏叉了，然后maa就不会自动开游戏了
### 日志文件
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10422099/asst.log)
直接看最新的那一段就是了
### 截图
![image](https://user-images.githubusercontent.com/27950494/212587175-57c3a5dc-1cd3-4a4b-baad-6ab0aceb5764.png)
### 还有别的吗？
模拟器是蓝叠国际版
win10系统
分辨率是1920*1080

**Comment by s1771915465** [comment]
情景还原很简单，开个自动肉鸽，然后等脚本随便打一点，手动把游戏叉了，然后maa就不会自动开游戏了

**Comment by s1771915465** [comment]
Add {bug}

**Comment by s1771915465** [comment]
Add bug
