### ISSUE TITLE
领航者试炼自动战斗作业坐标偏移

### ISSUE THREAD

**Issue by youdianfengbao** [MaaAssistantArknights/MaaAssistantArknights#3354]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在制作领航者试炼的自动战斗作业时发现一些边角坐标会经常出现难以放下干员的情况，例如第一屏的[1,1][10,5]这种超远坐标
以及在移动到第三屏时坐标出现明显偏移，如TN-2的[18,4]部署会部署到[18,3]上但点击使用技能还是需要点击[18,4]才能点击选中干员，导致作业制作难度较大，且作业顺利运行的成功率很低

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10408195/asst.log)

### 还有别的吗？

模拟器是BlueStacks App Player 5.9.10.1008 P64 分辨率1600*900 dpi 320

**Comment by MistEO** [comment]
上游仓库问题，https://github.com/yuanyan3060/Arknights-Tile-Pos ，暂时解决不了，等个佬来看看

**Comment by youdianfengbao** [comment]
alpha 3.5这个修复好像可以，就是第二次镜头偏移变成需要填整体偏移值，之前是第一次写4.5第二次写5，现在第一次写4.5第二次9.5。TN-2的作业正常运行了。确定一下按哪种写？我再试试看后面的作业

**Comment by youdianfengbao** [comment]
TN-4的第一屏和第二屏没问题，移动到第三屏的时候出现了一点问题。部署的坐标是正常的，但是平时的选中坐标偏移了1格多，如开技能，撤退。json不给加附件，改成txt格式发了。
[引航者试炼_TN-4 恢弘+最终 - 副本.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10414548/_TN-4.%2B.-.txt)
[asst.log]
(https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10414605/asst.log)

**Comment by MistEO** [comment]
总之下次引航者再说.jpg

**Comment by Xtzdd** [comment]
Mumu模拟器也遇到了这个问题。
