### ISSUE TITLE
刷取术狙小芯片关卡时掉落统计出错

### ISSUE THREAD

**Issue by VisibleOB** [MaaAssistantArknights/MaaAssistantArknights#3355]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷狙术芯片本的时候，想看一下刷了多少，发现掉落统计出错

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10408673/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/69883616/212249532-cdaef0da-96a3-449f-bec2-2ec5c5062dd1.png)

**Comment by MistEO** [comment]
debug/drops 文件夹里有图吗？一起发下看看

**Comment by VisibleOB** [comment]
额，没图。。。
