### ISSUE TITLE
刷理智选择的关卡未开放时，会一直卡住

### ISSUE THREAD

**Issue by moomiji** [MaaAssistantArknights/MaaAssistantArknights#3357]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://user-images.githubusercontent.com/35213527/212268634-f6f7604d-874e-41bd-8df0-639c329ba524.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10409395/asst.log)

### 截图

卡在这
![screenshot](https://user-images.githubusercontent.com/35213527/212269165-2a881859-b893-4fdb-8682-f7efd262f6e6.png)

**Comment by moomiji** [comment]
还有个类似的bug
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10409564/asst.log)

![image](https://user-images.githubusercontent.com/35213527/212272482-43b410a2-b42f-4e71-9604-e280a9c63fb8.png)

卡这
![screenshot](https://user-images.githubusercontent.com/35213527/212272580-f470886a-1203-4b88-b32c-c04257fee73c.png)

**Comment by ABA2396** [comment]
这个是判断你选择的关卡是否开放，未开放就找下一个；
第一个放了剿灭，但是剿灭是全天开放的，所以不会去找备选，而你这周的剿灭已经打完了，也不会去打（没有剿灭入口）；
第二个全都选了都没开的关卡，传给 core 的就是 stage1（关卡选择的第一个），导航就走的红票的导航，所以就卡住了（估计等个几个小时之后就去打剩余理智的1-7了）

**Comment by moomiji** [comment]
原来是GUI判断的关卡是否开放（；´д｀）ゞ
