### ISSUE TITLE
公招先刷新词条之后才报告高资tag（然后错过）

### ISSUE THREAD

**Issue by GrakePch** [MaaAssistantArknights/MaaAssistantArknights#336]
遇见高资tag了，但是程序似乎先选择了刷新，然后才识别到高资tag

![image](https://user-images.githubusercontent.com/21063261/162332689-7739f4d3-6a6a-43a6-bc78-15bc3fc0736f.png)
![image](https://user-images.githubusercontent.com/21063261/162332718-9dc709cc-9f2f-489f-a200-8ffbb19b2f58.png)

蓝叠国际版5.6.100.1026 N64

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8447294/asst.log)

**Comment by ABA2396** [comment]
这不是6星不会自己招募然后跳过识别的下一个吗（？）你6星tag还有没有

**Comment by GrakePch** [comment]
> 这不是6星不会自己招募然后跳过识别的下一个吗（？）你6星tag还有没有

没……没太读懂？
但是我的六星tag确实是刷没了的。
我那天在后台挂着，然后就收到了六星的提醒，点开模拟器一看发现刷新掉了

**Comment by MistEO** [comment]
非常抱歉，确实是把六星 Tags 刷掉了。

问题原因是，点完刷新确认后，Tags 不是一瞬间会变成新的的，有一个小渐变动画，持续约几百毫秒。如果这个动画播放期间有卡顿，或网络有波动等的时候，此时截图到的还是刷新前的 Tags

下个版本会修复这个问题，再次表示抱歉_(:з」∠)_

**Comment by GrakePch** [comment]
辛苦了，所幸作为一个老玩家我的公招六星没有遗憾了，放走一个就放走一个吧。我这边确实网络不稳定。
