### ISSUE TITLE
.net提示错误

### ISSUE THREAD

**Issue by desktop4025** [MaaAssistantArknights/MaaAssistantArknights#3362]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

程序能运行但会跳出.net错误弹窗

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10412288/asst.zip)

### 截图

![T2CEAB`IQ4_P75% V2G%(4](https://user-images.githubusercontent.com/107090995/212341320-c435b1a4-9c44-48f6-bbd4-15241410ba53.png)

**Comment by MistEO** [comment]
修过了，更新下
