### ISSUE TITLE
adb input滑动过头了，抄作业功能自动编队中选择干员个别条件下无法识别

### ISSUE THREAD

**Issue by weakcontrol0214** [MaaAssistantArknights/MaaAssistantArknights#3369]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

抄作业功能中拖拽页面自动选择干员 拖拽一次后最左端页面边缘干员无法识别
版本是4.10beta1 雷电4模拟器 720p分辨率

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10417359/asst.log)

时间段 20:57到20:59

### 截图

![bug](https://user-images.githubusercontent.com/122678557/212473010-864a5b2d-cf56-401d-9495-687039f666d4.png)

例如 拖拽一次页面后 夜莺 无法选择识别 然后maa自动划到页底就开始死循环了

**Comment by MistEO** [comment]
adb input 在滑动方面问题比较多，不好修，建议换 minitouch 或者 maatouch
