### ISSUE TITLE
公招页面容易崩溃

### ISSUE THREAD

**Issue by dichigo** [MaaAssistantArknights/MaaAssistantArknights#337]
夜神模拟器 
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8447920/asst.log)

**Comment by dichigo** [comment]
顺带提点别的 雷电模拟器链接不稳定貌似是因为端口5555容易被其他的程序占用 例如UU加速器 有些时候都已经连接上然后再开加速器就会被直接挤掉

**Comment by MistEO** [comment]
日志似乎被刷掉了。发下 asst.bak.log 康康

**Comment by dichigo** [comment]
昨天挂了一天肉鸽 日志文件有100多M传不上来

**Comment by dichigo** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8451942/asst.log)
看看这个里面有没有

**Comment by MistEO** [comment]
> [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8451942/asst.log) 看看这个里面有没有

没有_(:з」∠)_

**Comment by dichigo** [comment]
那没办法了 我只记得
![image](https://user-images.githubusercontent.com/98818071/162441701-6b3f420a-c046-43b1-b4f4-911ffea5da6c.png)
是这个组合让他崩溃的 重开在同页面重新开始立马就崩溃 最后我自己手点跳过
