### ISSUE TITLE
集成文档变量名错误

### ISSUE THREAD

**Issue by 134820134820** [MaaAssistantArknights/MaaAssistantArknights#3370]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刚刚在翻集成文档的时候发现了个拼写错误
![错误](https://user-images.githubusercontent.com/79043872/212475232-960e782a-9989-40f0-b42e-79674aef813e.JPG)
在基建任务流程的最后面，dorm变成了drom，因为不知道是不是内部接口也写错了就没有直接pr~~也不会~~

### 日志文件

。

**Comment by MistEO** [comment]
感谢提醒。确实写错了，估计其他地方也是复制的都跟着错了

@hguandl @bakashigure @SaiCateDoan
 帮忙检查下其他 UI 要不要跟着改下 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/ce8a6c338180d7036b0a75e4dae70302ef806a85
