### ISSUE TITLE
Python 接口是否还没完善

### ISSUE THREAD

**Issue by 134820134820** [MaaAssistantArknights/MaaAssistantArknights#3371]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

试了一下python接口，一个是好像不能启动模拟器（也根本没有路径和附加命令选项），第二个是如果中间断开adb的话，是不是也并不会像GUI中一样自动重连？还不知道如果断线的话又会怎么样。

### 有什么好的想法？

同步MAAGUI中那些方法（~~要是能搞明白C++部分就我来写了~~我似乎能写但不清楚MAAGUI中的逻辑，做不到一样）

**Comment by ABA2396** [comment]
启动模拟器这些功能都是ui实现的，和core没啥关系吧

**Comment by MistEO** [comment]
这是都是 GUI 自己实现的，不是 MaaCore 做的

**Comment by 134820134820** [comment]
> 这是都是 GUI 自己实现的，不是 MaaCore 做的

原来如此，但从使用的角度的话是不是还是需要的（）

**Comment by MistEO** [comment]
启动模拟器要分平台的，core 只负责跨平台的通用逻辑，做这些不太合理。或者该有个分平台的逻辑层，但是工作量太大了所以

**Comment by 134820134820** [comment]
> 启动模拟器要分平台的，core 只负责跨平台的通用逻辑，做这些不太合理。或者该有个分平台的逻辑层，但是工作量太大了所以

有没有方法能使外部程序可以改变MAAGUI的参数，这样的话配上MAA的自启动，似乎便能实现更加好用？
