### ISSUE TITLE
基建赤金不足后，不会使用无人机

### ISSUE THREAD

**Issue by StrayTurtle03** [MaaAssistantArknights/MaaAssistantArknights#3373]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

现有的无人机使用逻辑似乎是直接使用到贸易战，但是赤金不足后，应该要使用到金条制造站中，可是并没使用，直接退出基建了，无人机是满的

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10419294/asst.log)

2023.1.15 大概9：15吧

### 截图

无

### 还有别的吗？

BlueStacks App Player v5.9.300.1018 N32
Windows11 22H2

**Comment by ABA2396** [comment]
如果你用的是自定义基建，应该修改自定义文件内的无人机使用方式。如果你用的是默认的基建设置，应该修改这个
![image](https://user-images.githubusercontent.com/99072975/212523889-7b8cde85-27b0-4602-8b7a-647851a7f447.png)

**Comment by StrayTurtle03** [comment]
感谢您的答复，是我没有注意设置当中有这一选项
1. 不过我仍然认为逻辑上有错误，虽然我赤金不足，但我订单数量并不满，此时仍可以将无人机用于订单加速，但MAA并没有这样做
2. 是否考虑在主界面加入显示：无人机使用失败，以便用户发现问题
3. 是否考虑在未来加入自动识别的选项，在赤金充足时将无人机用于赤金->龙门币，不足时用于赤金生产

**Comment by StrayTurtle03** [comment]
> 如果你用的是自定义基建，应该修改自定义文件内的无人机使用方式。如果你用的是默认的基建设置，应该修改这个 ![image](https://user-images.githubusercontent.com/99072975/212523889-7b8cde85-27b0-4602-8b7a-647851a7f447.png)
