### ISSUE TITLE
刷肉鸽功能初始选人错误

### ISSUE THREAD

**Issue by 666233j** [MaaAssistantArknights/MaaAssistantArknights#3375]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

设置了初始选助战百炼嘉维尔，然而实际选了自己有的拉普兰德，有时候会这样，有时候不会，时间点在最后一次探索

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10419546/asst.zip)

**Comment by WLLEGit** [comment]
刷新3次找不到需要的干员就会返回招募自己的干员，log里最后一次就是这样的情况。

**Comment by MistEO** [comment]
> 刷新3次找不到需要的干员就会返回招募自己的干员，log里最后一次就是这样的情况。

或许可以把这个 3 次改大一点？

**Comment by WLLEGit** [comment]
> > 刷新3次找不到需要的干员就会返回招募自己的干员，log里最后一次就是这样的情况。
> 
> 或许可以把这个 3 次改大一点？

刚刚上线试了下，刷新30次还是3秒cd。要不设置里再加一个刷新次数的输入框？
