### ISSUE TITLE
【吃理智药】和【指定材料刷取数量+剩余理智】的逻辑不够直觉

### ISSUE THREAD

**Issue by yd278** [MaaAssistantArknights/MaaAssistantArknights#3376]
### 说说你遇到的问题？

![图片](https://user-images.githubusercontent.com/23385935/212524967-2cc02a95-9764-4e21-92cb-1619fc04ee6e.png)
虽然在说明中有解释过这里的勾选框之间是逻辑或关系，所以右边log里的行为（吃3个药，刷到俩大芯片，然后停止吃药把剩下60点理智刷两次红票）是可以理解的；但设置的的时候我的预期其实是吃完10个理智药，先刷到俩芯片之后再全刷红票的。

能否考虑通过调整逻辑或者优化UI介绍来让用户直觉和实际逻辑相一致？

**Comment by ABA2396** [comment]
说实话我几乎没怎么用过这个剩余理智，而且剩余理智的导航是不判断该关卡是否开放的，如果今天写了红票结果第二天不开，那第二天执行的时候就会卡住。最开始的想法大概是在刷完钱本芯片本之类的剩了十几点理智，然后去刷几把1-7这样。这个页面加太长的标题也不太方便，还是加个悬浮提示说明一下，比如说“执行完刷理智任务后剩余理智刷取的关卡”？感觉这个描述也不是很明白的样子

**Comment by satgo1546** [comment]
不如就加个悬浮提示具体地说“此功能用于在刷完钱本芯片本之类的剩了十几点理智后去刷几把1-7”，简单易懂 :rofl:
