### ISSUE TITLE
优化资源加载速度

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#3377]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

4.10.0-alpha1版本优化了资源加载速度，我今天更新了4.10.0-beta2，实测使用机械硬盘加载速度还是和以前一样，没有什么明显变化。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10419860/asst.log)

### 截图

![屏幕截图 2023-01-15 092949](https://user-images.githubusercontent.com/92417243/212533548-2b9b6e94-a098-4e34-ae91-539f532b145f.jpg)

**Comment by MistEO** [comment]
就是做了之前说的多线程加载，你IO速度瓶颈了，没办法

**Comment by xiaoweiXX** [comment]
> 就是做了之前说的多线程加载，你IO速度瓶颈了，没办法

不是说每次更新完了做个本地cache吗？那样也就更新的时间长一点

**Comment by MistEO** [comment]
可能没法做，更新是 UI 处理的，UI 并不负责这些 json 的解析逻辑，所以这个缓存不能由 UI 做。如果由 core 做，core 不知道有没有更新，如果每次启动都去检查下所有文件的更新时间，那就失去做 cache 的意义了

**Comment by MistEO** [comment]
而且现在是允许用户自行修改这些文件的（

**Comment by xiaoweiXX** [comment]
> 可能没法做，更新是 UI 处理的，UI 并不负责这些 json 的解析逻辑，所以这个缓存不能由 UI 做。如果由 core 做，core 不知道有没有更新，如果每次启动都去检查下所有文件的更新时间，那就失去做 cache 的意义了

有个想法，再专门做个打包器，每次更新自动触发或者用户在需要的时候手动触发

**Comment by xiaoweiXX** [comment]
> 可能没法做，更新是 UI 处理的，UI 并不负责这些 json 的解析逻辑，所以这个缓存不能由 UI 做。如果由 core 做，core 不知道有没有更新，如果每次启动都去检查下所有文件的更新时间，那就失去做 cache 的意义了

另外明日方舟这游戏实际上很吃硬盘IO，虽然这游戏本身不怎么消耗硬盘IO，但是如果后台的硬盘IO满了游戏就会掉帧很卡，如果MAA读取要1分钟并且还吃满了硬盘，那么等加载的这段时间基本上啥都干不了。

**Comment by MistEO** [comment]
机械硬盘其实都算 corner case 了，在我自己电脑上 maa 平均加载时间 600~800 ms

**Comment by xiaoweiXX** [comment]
> 机械硬盘其实都算 corner case 了，在我自己电脑上 maa 加载时间大概 600~800 ms
> 
> 2023 年了，该把所有软件全放到固态了（

我固态只有128，放不开。目前只装了系统，放了几个常用软件，还有真的很吃加载的东西（比如novel ai）。现在固态只剩下20G不到，还要腾出10G给虚拟内存。

**Comment by MistEO** [comment]
内测版资源全惰性加载了，可以试试看

**Comment by xiaoweiXX** [comment]
> 内测版资源全惰性加载了，可以试试看

确实，快很多了
