### ISSUE TITLE
引航者试炼，MoveCamera 后直接完成战斗了，不再进行后续action

### ISSUE THREAD

**Issue by ZhaoGY-N** [MaaAssistantArknights/MaaAssistantArknights#3380]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MoveCamera 后直接完成战斗了，不再进行后续action，目前使用4.10.0-beta2。测试了开启暂停下干员和不开启，都是一样的
使用的作业json如下。（json上传不了，改成txt了）
[TN-4 定向+恢宏+最终(作业) by luckyluke.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10420398/TN-4.%2B.%2B.by.luckyluke.txt)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10420406/asst.log)
大概就是22点10分，基本是最后了，之前也有几次一样的情况。

### 截图

![MuMu20230115221912](https://user-images.githubusercontent.com/62810902/212546419-9f1d8990-2578-4b0c-ba76-b3385df5dd58.png)
![MuMu20230115222311](https://user-images.githubusercontent.com/62810902/212546420-30556d2f-4468-48cc-ac63-dec07f04fd27.png)

### 还有别的吗？

mumu模拟器，win10，5800U+3050笔记本

**Comment by MistEO** [comment]
摆了，下次再出再修（
