### ISSUE TITLE
JP: Cant Reboot Arknights

### ISSUE THREAD

**Issue by wallsman** [MaaAssistantArknights/MaaAssistantArknights#3382]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Cannot restart after crash.
I was able to do this with a previous fix, but this time the logs show that the app name is not readable, is this the cause?

### Log files

2023/01/15 19:11:20
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10421357/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10421360/gui.log)

**Comment by MistEO** [comment]
The `asst.bak.log` you uploaded stopped on January 16, maybe you should upload `asst.log` instead of `asst.bak.log`

**Comment by wallsman** [comment]
The relevant log section is around 2023/01/15 19:11:20 as stated, so I think this is the correct one.
I think the problem is that the OCR is "クナイツ".

```
[2023-01-15 19:11:20.178][TRC][Px77040][Tx1a924] OcrPack::recognize | raw: [{ クナイツ: [ 12, 119, 67, 16 ], score: 0.999922 }, { Bluestacksx: [ 200, 120, 82, 14 ], score: 0.989614 }]
[2023-01-15 19:11:20.178][TRC][Px77040][Tx1a924] OcrPack::recognize | proc: []
[2023-01-15 19:11:20.188][TRC][Px77040][Tx1a924] asst::ProcessTask::_run | leave, 557 ms
```
