### ISSUE TITLE
maa启动错误，外部组件出现异常

### ISSUE THREAD

**Issue by hechuxielianli** [MaaAssistantArknights/MaaAssistantArknights#3383]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

1.16的新版本更新后无法打开maa软件，显示外部组件出现异常

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10421566/asst.log)

重新下载后的日志文件

### 截图

![image](https://user-images.githubusercontent.com/122757769/212574293-acee450d-b115-41fe-ae2e-a8b32cd2ee6d.png)

### 还有别的吗？

详细信息：在 MaaWpfGui.AsstProxy.AsstLoadResource(Byte* dirname)
   在 MaaWpfGui.AsstProxy.AsstLoadResource(String dirname)
   在 MaaWpfGui.AsstProxy.LoadResource()
   在 MaaWpfGui.AsstProxy.Init()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.RootViewModel.<InitProxy>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MistEO** [comment]
依赖的第三方库 fastdeploy 那边文件夹不能有中文，你换个文件夹试试

**Comment by hechuxielianli** [comment]
> 依赖的第三方库 fastdeploy 那边文件夹不能有中文，你换个文件夹试试

谢谢，解决了！
