### ISSUE TITLE
关于信用的自动购物问题

### ISSUE THREAD

**Issue by ilikecongee** [MaaAssistantArknights/MaaAssistantArknights#3385]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

出现了自动信用购物未完全按优先级来购物的情况
![1](https://user-images.githubusercontent.com/97867349/212599900-3103b1c9-cfa3-4b03-aed7-8d7f1a4751c8.png)
MAA设置如下图
![2](https://user-images.githubusercontent.com/97867349/212599999-08212823-23a0-47c1-8932-bc5d9ff19780.png)
日志如下
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10422559/asst.log)

### 有什么好的想法？

希望能优化优先级

**Comment by MistEO** [comment]
没看出来为啥，这块日志不够。加了一些，之后的版本如果再遇到帮忙再发个看看

**Comment by ABA2396** [comment]
之后还有发现类似问题吗

**Comment by ilikecongee** [comment]
> 之后还有发现类似问题吗

那次后到现在没有出现过了
