### ISSUE TITLE
收取信用及购物中赚取助战点数时会喊一些会让战斗失败的支援

### ISSUE THREAD

**Issue by HS7097** [MaaAssistantArknights/MaaAssistantArknights#3386]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10422909/asst.log)
同时还有
![image](https://user-images.githubusercontent.com/103177863/212596346-79276230-104c-4e61-a7d7-348d7270b6f9.png)
![image](https://user-images.githubusercontent.com/103177863/212596474-e6ce9b9e-7b39-43dd-b47c-0d61513519d2.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10422909/asst.log)

### 还有别的吗？

蓝叠Pie 64位 
Alas图形界面。

**Comment by MistEO** [comment]
不建议把下游项目的截图直接扔过来，我们并不清楚发生了什么 ALAS 才会报这种错误，或许应该先给他们提个 issue 看看怎么回事。

另外会让战斗失败的支援是啥？

**Comment by HS7097** [comment]
> 不建议把下游项目的截图直接扔过来，我们并不清楚发生了什么 ALAS 才会报这种错误，或许应该先给他们提个 issue 看看怎么回事。
> 
> 另外会让战斗失败的支援是啥？

请求的支援是桃金娘，我也不清楚是怎么部署的；
同时，三个错误发生时间为，今日凌晨4点，今日凌晨5点32分，以及提交issues时

**Comment by ABA2396** [comment]
支援的干员是不会上场的

**Comment by HS7097** [comment]
> 支援的干员是不会上场的

那么是否是王小姐漏怪导致的？我看MAA只编了王小姐进去

**Comment by Shawnsdaddy** [comment]
和支援应该没关系，就是作业战斗失败

**Comment by HS7097** [comment]
> 和支援应该没关系，就是作业战斗失败

希望能改进一下，毕竟是固定的地图，只在固定的地点下干员就行了，希望可以自定义干员

**Comment by akiriroll** [comment]
> 支援的干员是不会上场的
但是观察到好几次会……比如昨天打的时候借了好友的嵯峨，因为双方潜能或者模组关系嵯峨比风笛低一费，结果maa上场选择了嵯峨，嵯峨和最后一只虫子同归于尽了
一直以为支援也会上场是设定，这算bug吗？

**Comment by MistEO** [comment]
似乎是作业的问题，借到的干员也在干员组里面

**Comment by Hydrogina** [comment]
虽然没测试过，但近卫肯定也能打，因为试过只上芬也能过
