### ISSUE TITLE
4.10.0版本打开软件报错闪退

### ISSUE THREAD

**Issue by XonlookerX** [MaaAssistantArknights/MaaAssistantArknights#3387]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

   4.10.0版本打开软件报错闪退

  在 MaaWpfGui.AsstProxy.AsstLoadResource(Byte* dirname)
   在 MaaWpfGui.AsstProxy.AsstLoadResource(String dirname)
   在 MaaWpfGui.AsstProxy.LoadResource()
   在 MaaWpfGui.AsstProxy.Init()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.RootViewModel.<InitProxy>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10424851/asst.log)

### 截图

![7WXTVF}`$1V Z8$~638)L0T](https://user-images.githubusercontent.com/61648955/212656795-df2815bd-cd51-465e-819b-4e141f83d66f.png)

**Comment by ntgmc** [comment]
Duplicate of #3348 
![image](https://user-images.githubusercontent.com/74061867/212658611-d3dd6296-ae10-446b-80b4-be3b96a1e801.png)
