### ISSUE TITLE
4.10.0版本更新后无法正常启动

### ISSUE THREAD

**Issue by jumpinggalaxy** [MaaAssistantArknights/MaaAssistantArknights#3388]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动更新至4.10.0后，启动MAA显示为外部组件发生异常，后程序自动关闭，删除原文件夹至官网重新下载压缩包后情况不变

详细信息:
在 MaaWpfGui.AsstProxy.AsstLoadResource(Byte* dirname)
   在 MaaWpfGui.AsstProxy.AsstLoadResource(String dirname)
   在 MaaWpfGui.AsstProxy.LoadResource()
   在 MaaWpfGui.AsstProxy.Init()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.RootViewModel.<InitProxy>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10424880/asst.log)
问题出现时间 18:20~30间

### 截图

![image](https://user-images.githubusercontent.com/106938196/212657598-32d90236-71b9-4bfc-9296-f04bf9debb26.png)

**Comment by ntgmc** [comment]
Duplicate of #3348 
![image](https://user-images.githubusercontent.com/74061867/212658519-95d2fa7a-ee19-4cb2-86de-e7f102e64b4e.png)
