### ISSUE TITLE
基建识别出错，交易站/制造站 重复点击同一个

### ISSUE THREAD

**Issue by AlexYangCong** [MaaAssistantArknights/MaaAssistantArknights#339]
夜神模拟器 
有一天突然发现任务结束后基建红了一个制造一个贸易，然后没太在意手动补了，今天亲眼所见，点进贸易站然后点三个最上面那个，完成。然后点下一个的时候又跳到最上面那个（贸易站左上不是有快捷跳转嘛）重复三次，没报错就去制造了，我估计制造之前也是这样
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8457124/asst.log)
![image](https://user-images.githubusercontent.com/49122848/162578517-94622761-ad76-450f-8642-05a22185657e.png)

**Comment by MistEO** [comment]
你描述的有点模糊，我没搞懂是什么现象。。麻烦描述清楚一些_(:з」∠)_

另外你说贸易站然后去制造了，但是我看你截图是先制造站后贸易站的？

**Comment by MistEO** [comment]
这个 bug 太久了，也没搞明白问题怎么出现的，这块也来来回回改了不少，总之先关了（
