### ISSUE TITLE
更新之后出现的问题

### ISSUE THREAD

**Issue by keysboy** [MaaAssistantArknights/MaaAssistantArknights#3391]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

提示更新之后重启就提示错误了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10425432/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/104134191/212670393-3cf17dbc-2d7e-4d5c-85ba-f9d019409a10.png)

**Comment by ntgmc** [comment]
Duplicate of #3348 
请查看该issue解决

**Comment by keysboy** [comment]
改英文路径已解决，谢谢
