### ISSUE TITLE
更新后启动显示外部组件发生异常

### ISSUE THREAD

**Issue by moumoumou12138** [MaaAssistantArknights/MaaAssistantArknights#3392]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动更新重启后显示外部组件发生异常

### 日志文件

[Uploading asst.log…]()

### 截图

![图片](https://user-images.githubusercontent.com/122792027/212671418-22313724-d519-45b4-92cf-8eae26b54f87.png)

**Comment by moumoumou12138** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10425505/asst.log)

**Comment by ntgmc** [comment]
Duplicate of #3348 
请查看该issue解决
![image](https://user-images.githubusercontent.com/74061867/212672215-e4034887-5402-47dc-bb2a-94e02e88687b.png)
