### ISSUE TITLE
启动时报错：外部组件发生异常

### ISSUE THREAD

**Issue by SakuraSora39** [MaaAssistantArknights/MaaAssistantArknights#3394]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启动时弹窗报错，点叉后闪退

详细信息
 在 MaaWpfGui.AsstProxy.AsstLoadResource(Byte* dirname)
   在 MaaWpfGui.AsstProxy.AsstLoadResource(String dirname)
   在 MaaWpfGui.AsstProxy.LoadResource()
   在 MaaWpfGui.AsstProxy.Init()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.RootViewModel.<InitProxy>d__4.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10426534/asst.log)

### 截图

![Snipaste_2023-01-16_22-14-46](https://user-images.githubusercontent.com/115397142/212698468-bb2c99be-66b5-48cd-81fd-6dfaa11e2ab8.jpg)

### 还有别的吗？

模拟器：mumu
系统：Windows 10 家庭中文版 21H2 19044.2486

**Comment by ntgmc** [comment]
Duplicate of #3348 
请查看该issue解决。
![image](https://user-images.githubusercontent.com/74061867/212698908-348a1405-e841-4df2-97e2-6a46ea598071.png)

**Comment by ntgmc** [comment]
我Reopen一下让其他没发issue的看到（）

**Comment by ydh2003** [comment]
我使用蓝叠模拟器也遇到了同样的问题

**Comment by MistEO** [comment]
fixed
