### ISSUE TITLE
打开直接报错，外部组件发生异常

### ISSUE THREAD

**Issue by planeone1** [MaaAssistantArknights/MaaAssistantArknights#3395]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

之前用的好好的，但是今天更新到4.10之后就报错了，麻烦大佬们看看！！感谢！！

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10426601/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/122803456/212700349-40074246-043a-4a6f-b17d-284649ef3dd8.png)
![image](https://user-images.githubusercontent.com/122803456/212700375-c96bbd3d-054b-4b01-a479-009ef4225b85.png)

**Comment by ntgmc** [comment]
Duplicate of #3348 
请查看该issue解决。
![image](https://user-images.githubusercontent.com/74061867/212698908-348a1405-e841-4df2-97e2-6a46ea598071.png)
