### ISSUE TITLE
mumu模拟器更新到最新后，原先设置的adb无法正常连接模拟器

### ISSUE THREAD

**Issue by bbyyxx2** [MaaAssistantArknights/MaaAssistantArknights#3396]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

图一为更新完模拟器后模拟器版本。更新完最新的模拟器后就卡截图二，三行文字一直不动，模拟器也没有任何反应。重启两个应用多次和重启电脑多次，测试多次设置后怀疑是adb的问题，由于正好会一点安卓，所以我自己有adb，切换了之后正常使用。可以确定更新前后没有动过MAA设置。不知道是不是bug或者只有我一个人有这个问题，看了近期的issue和更新没发现有这个问题，所以来问一下。这是之前MAA的adb设置的MUMU的adb地址。\MuMu\emulator\nemu\vmonitor\bin\adb_server.exe

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10426604/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/46420421/212697972-b633de99-9374-4046-8281-0b4e7e43af09.png)
![image](https://user-images.githubusercontent.com/46420421/212699062-2b75fc22-3b3d-4247-a554-2dcdbe3fc677.png)
![image](https://user-images.githubusercontent.com/46420421/212700557-6051862d-2632-485c-b5e5-d11d3a10ed32.png)

**Comment by ntgmc** [comment]
你好 这是因为mumu更新了导致替换的adb失效了
请重新点击【强制替换ADB】

如果替换失败的 报错的 占用的 要管理员的
看下面链接教程：
https://shimo.im/docs/473Qyd7B7Nh1w23w
