### ISSUE TITLE
仓库识别功能中材料数量以xx万显示时，数量识别异常

### ISSUE THREAD

**Issue by Him392** [MaaAssistantArknights/MaaAssistantArknights#3397]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图，中级作战记录数量显示为1.5万，却被识别为1。
![image](https://user-images.githubusercontent.com/50799666/212727757-d92ac329-5eb2-4f52-905b-4d6e9dad8385.png)

![image](https://user-images.githubusercontent.com/50799666/212727817-45224fc3-c143-4601-9fb8-e7f1988d4ea6.png)
![image](https://user-images.githubusercontent.com/50799666/212728362-abf383c1-f088-4399-9025-cf9fe6269359.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10427722/asst.log)

### 截图

![MuMu20230117004158](https://user-images.githubusercontent.com/50799666/212728601-13afe721-9c56-4cf8-98d3-168b579f9047.png)

### 还有别的吗？

非偶发问题，在4.10.0版本可稳定复现（其他材料及其他数量暂未测试）。
猜测是由于未对以1.5万这类方式显示的数量进行特定识别造成的。

**Comment by ABA2396** [comment]
1.5万本来也识别不准确）

**Comment by Him392** [comment]
点开能看见具体数值（）

**Comment by Him392** [comment]
[depot.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10481011/depot.zip)
