### ISSUE TITLE
定时任务启动失败

### ISSUE THREAD

**Issue by Sakuma-Rei** [MaaAssistantArknights/MaaAssistantArknights#3399]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自己点开始没问题 但是到定时就运行不了 最新版稳定版4.10

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10430353/asst.log)

### 截图

![2023-01-16_160101](https://user-images.githubusercontent.com/55101422/212790134-be50b1f4-a8c6-4fdd-ab08-6a3b639fe0ae.png)

### 还有别的吗？

蓝叠国际5 群里那个

**Comment by ABA2396** [comment]
program files文件夹要的权限比较高吧，试试管理员启动或者换个文件夹？

**Comment by MistEO** [comment]
不要把绿色软件放在这种系统文件夹里，除非每次都用管理员启动
