### ISSUE TITLE
肉鸽打完一关后直接自动放弃

### ISSUE THREAD

**Issue by IreneZ11** [MaaAssistantArknights/MaaAssistantArknights#340]
肉鸽选的尽可能往后打但是打完一关后直接自动放弃了·-·不知道是不是因为投资已经过200的缘故？
用的bluestacks模拟器
![5bf7939bc487a0ec802e560f168d269](https://user-images.githubusercontent.com/103345965/162600152-48ef6841-8c85-4c31-8847-23fa7a631f98.png)
![9c7113ffea66f6297a05b6a0a2acc06](https://user-images.githubusercontent.com/103345965/162600153-d32dbedb-76e6-4194-b684-6a76bb01012b.png)

**Comment by IreneZ11** [comment]
版本是v3.1.0滴 感谢大大

**Comment by IreneZ11** [comment]
![Screenshot_2022 04 10_11 31 05 857](https://user-images.githubusercontent.com/103345965/162600297-117b1c10-658e-4d73-9620-19fbbf22562e.png)
![Screenshot_2022 04 10_11 31 30 089](https://user-images.githubusercontent.com/103345965/162600299-31297fa4-dd4c-410d-9d62-cabe83f5f098.png)
似乎是遇到选人阶段就直接放弃了……

**Comment by IreneZ11** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8458187/asst.log)

**Comment by IreneZ11** [comment]
换了个账号还是这样，似乎不是投资那个的问题

**Comment by IreneZ11** [comment]
好像是点剧目的时候会卡住，然后就直接放弃了

**Comment by zzyyyl** [comment]
可能有以下三个问题：
1. 点快了卡住（这个问题在 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/5ef2016e7c09ab0d6bf04b0ad99333bfafe3f4c0 已经尝试修复了）
2. 看图上掉的是剧目（`Roguelike1GetDrop3`），在log里发现所有的掉落物都识别成源石锭（`Roguelike1GetDrop1`），有的score是0.95有的是0.80，大概是识别错了。可能要给增加肉鸽的掉落物匹配的阈值。
3. 如果是选人的问题，可以参照 #167 进行配置。

**Comment by IreneZ11** [comment]
谢谢您……但我是个笨蛋文科生，很难理解这些！_(:_」∠)_不过我明天醒来会尝试理解一下的！会敲代码真是太厉害了感谢您深夜还在发电呜呜 打扰了！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zzyyyl ***@***.***&gt;
发送时间: 2022年4月11日 00:08
收件人: MaaAssistantArknights/MaaAssistantArknights ***@***.***&gt;
抄送: IreneZ11 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽打完一关后直接自动放弃 (Issue #340)





 
可能有以下三个问题：
  
点快了卡住（这个问题在 5ef2016 已经尝试修复了） 

看图上掉的是剧目（Roguelike1GetDrop3），在log里发现所有的掉落物都识别成源石锭（Roguelike1GetDrop1），有的score是0.95有的是0.80，大概是识别错了。可能要给增加肉鸽的掉落物匹配的阈值。 

如果是选人的问题，可以参照 #167 进行配置。

**Comment by IreneZ11** [comment]
对不起……我还是没有明白我应该做什么！真的很抱歉TT辜负您的一片好意了

**Comment by zzyyyl** [comment]
我上面说的第二点已经在 #342 尝试修复了，1、2你可以不用管了（期待一下新版本？）
另外你也许可以看看第三点里提到的issue，也许对你在肉鸽选人阶段遇到的问题有所帮助

**Comment by IreneZ11** [comment]
好啊好啊！！谢谢你！！期待ing🤩


------------------ 原始邮件 ------------------
发件人: zzyyyl ***@***.***&gt;
发送时间: 2022年4月12日 19:40
收件人: MaaAssistantArknights/MaaAssistantArknights ***@***.***&gt;
抄送: IreneZ11 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽打完一关后直接自动放弃 (Issue #340)
