### ISSUE TITLE
内置自定义基建无人机使用情况

### ISSUE THREAD

**Issue by ffzhao123** [MaaAssistantArknights/MaaAssistantArknights#3408]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

内置243一天四换基建中，无人机总是固定使用于订单贸易，导致赤金消耗巨大

### 有什么好的想法？

建议内置自定义基建变更为两个模式，一个为无人机用于订单贸易，一个用于无人机生产赤金，虽然清楚自定义基建可以通过自行修改文件调整，但对我这种程序小白还是有点难度，烦请考虑一下，谢谢！

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/c5edeb7a6231003419a17dc4a232cab8e28ffc3e fixed
