### ISSUE TITLE
保全派驻中塞雷娅技能识别错误

### ISSUE THREAD

**Issue by Cherrling** [MaaAssistantArknights/MaaAssistantArknights#3409]
### 说说你遇到的问题？

版本v4.10.3
自动战斗-保全派驻-官方内置作业-阿卡胡拉丛林
作战第二关，自动战斗不断频繁点击已经放下去的塞雷娅，保持 点击-等待几秒-返回-立刻点击 的循环，怀疑是把塞妈急救的充能圆圈识别成了技能准备好的图标，一直尝试手动开启
此种情况一直持续到作战后，其余关卡未出现此异常
![QQ截图20230118082624](https://user-images.githubusercontent.com/37233261/213049358-a9df027e-8d96-4359-979e-7748827fe822.png)

**Comment by MistEO** [comment]
是 bug 请附上日志

**Comment by Cherrling** [comment]
[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10452718/log.zip)
上传了log文件
bug首次出现在2023/1/18 8：16左右的一次保全作战-阿卡胡拉丛林

**Comment by MistEO** [comment]
加了个兜底策略。图像识别的问题等 @horror-proton 佬看看

**Comment by horror-proton** [comment]
嘶, 有未被选中时的截图吗, 我拿自己截图的跑了下好像没看到识别错误, 不过我的没专只能充能两次, 3 我猜也不会差很多 :thinking:
(阈值是 130, 注意截图需要缩放
![Screenshot_2023 01 24_00 07 42 761](https://user-images.githubusercontent.com/107091537/214105733-dfdbf80f-a109-423b-8828-6d6791d50722.png)
![temp](https://user-images.githubusercontent.com/107091537/214105774-229b13f2-836a-4495-83ec-4f990054a760.png)
