### ISSUE TITLE
3个建议

### ISSUE THREAD

**Issue by FredB-mine** [MaaAssistantArknights/MaaAssistantArknights#341]
1.增加剿灭的自动切换功能(理智缺失时有bug,不会切换)
2.剿灭结束时的记录信息不会自动跳过
3.肉鸽有时候会选取等级较低的干员,从而导致失败

**Comment by FredB-mine** [comment]
还有 能否最小化到托盘?

**Comment by zzyyyl** [comment]
对于第3点，考虑是不是干员配置没有写好，可以参照 #167，如果觉得麻烦也可以等等下一版的全新肉鸽（

**Comment by MistEO** [comment]
剿灭现在应该没必要了，等支持了全权委托再说（
