### ISSUE TITLE
"自动换班"建议,增加将个别干员放入训练室/加工站

### ISSUE THREAD

**Issue by sunyink** [MaaAssistantArknights/MaaAssistantArknights#3411]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

MAA自动换班 目前没有加工站和训练室的选项;
目前基建干员的后勤技能存在，效率加成按某些特定干员进驻的总人数计算(比如:鸿雪4杜林、重岳4岁兽)，当这些组合用于替班时，宿舍是很紧张的，根本分不出位置给这些挂件；手动是有一种解决办法，就是把空出来的加工站1位、空出来的训练室辅助位1位，给这些挂件，但MAA目前无法自动化这个。
而如果手动永远放进去，则会影响排班或训练加工计划(比如，夕就不能永远放在辅助位)。

### 有什么好的想法？

构思场景：加工站与训练室辅助位，都空着没有使用计划时。
1、增加 加工站、训练室辅助位 的特定干员放入功能；实际不会减挂件心情。
2、细节，需要检查训练室训练位是否有人，有可能说明正在专精，要跳过放到辅助位的操作。

**Comment by anywugn** [comment]
附议，现在极限换班需要年在AB班和BC班放入加工站，只有AC班可以让年进宿舍回体力，故需要自定义换班【加工站】

**Comment by MistEO** [comment]
#4610

**Comment by MistEO** [comment]
fixed
