### ISSUE TITLE
日服肉鴿自動選取煌後不會自動放下幹員

### ISSUE THREAD

**Issue by Goshe-nite** [MaaAssistantArknights/MaaAssistantArknights#3417]
日服肉鴿自動選取煌並進入關卡後不會自動放下幹員, 導致關卡直接失敗, 並且關卡失敗後不能自動退出, 日誌出現以下字句:
[2023-01-18 22:03:19.879][INF][Pxbc88][Txc750] best oper is 煌プード
[2023-01-18 22:03:19.879][ERR][Pxbc88][Txc750] No available locations
[2023-01-18 22:03:19.879][INF][Pxbc88][Txc750] Tiles full while calc best plan.

**Comment by Goshe-nite** [comment]
補個日誌
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10451822/asst.log)

**Comment by MistEO** [comment]
不懂日语，这个是不是识别错了？`煌プード` 煌的日语是这么写吗

**Comment by Goshe-nite** [comment]
版本v4.10.4-beta.1似乎不會優先選煌了, 不過如果指定煌的話, 還是無法部署任何幹員。需要新的日誌的話我可以再上傳。

**Comment by Goshe-nite** [comment]
v4.10.4-beta.1日誌(只跑了一次帶煌的肉鴿)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10508909/asst.log)
再跑了一次好像還是有這個奇怪的プド。之前也試過重新下載, 沒有變化。
