### ISSUE TITLE
MAA选取傀影肉鸽时，游戏内选择肉鸽主题时不会自动将主题更改为傀影肉鸽

### ISSUE THREAD

**Issue by RunrunXi** [MaaAssistantArknights/MaaAssistantArknights#3419]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

游戏内如果发生从主菜单进入肉鸽的情况，例如凌晨四点自动弹出签到、游戏闪断更新等。就会出现进入肉鸽选择主题时不会自动选取傀影肉鸽（游戏默认选择水月肉鸽）从而导致MAA卡住，显示任务已全部完成。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10453717/asst.zip)
出现时间大致为2023年1月19日凌晨4点

### 还有别的吗？

MuMu模拟器，Windows11操作系统，模拟器1600*900分辨率，60帧

**Comment by ABA2396** [comment]
![eb67b10a552bf4c.jpg](https://user-images.githubusercontent.com/99072975/213373196-0f519213-acfa-4007-99de-ecd996fd60c5.jpg)

**Comment by RunrunXi** [comment]
> 

真是不好意思，我没有看见这个说明，还以为是改了主题就好，不过也可以建议把这个说明放在显眼的位置，以防我这样的玩家不知道，谢谢你告诉我
