### ISSUE TITLE
傀影肉鸽无法正常自动进入

### ISSUE THREAD

**Issue by AjinKimxu** [MaaAssistantArknights/MaaAssistantArknights#3424]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动肉鸽模式启用的时候，如果选择打的是傀影肉鸽，且傀影肉鸽没有正在进行的话会无限重复执行尝试进入肉鸽的操作（卡在截图界面），可能是被水月肉鸽挡住了进不去，需要手动点进傀影肉鸽才能开打

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10459102/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/121613686/213512598-5dcff95c-9a97-4cf1-88b0-2d751156b9cf.png)

### 还有别的吗？

蓝叠国际版5 win10 MAA版本：v4.10.3

**Comment by ABA2396** [comment]
#3419

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/214064935-7fa7ba6c-ba46-43c4-8867-3dfd0b35b497.png)

傀影刷的人少，没单独做导航的逻辑，自己 pin 一下吧
