### ISSUE TITLE
水月肉鸽无法部署干员白金

### ISSUE THREAD

**Issue by rohanyanya** [MaaAssistantArknights/MaaAssistantArknights#3425]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

模拟器为夜神模拟器，使用1600*900分辨率，使用4.10.3版本Maa，在水月肉鸽中无法正确部署干员白金，具体表现为干员无法放在高台位，貌似maa一直想放在地面或者干脆不放。发生在1月20日6点30分左右。

### 日志文件

[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10461690/asst.-.zip)

**Comment by MistEO** [comment]
看下 `cache/avatars` 下 有没有 `白金.png` 和 `预备干员-重装.png` 这俩文件，一起发一下看看
