### ISSUE TITLE
刷完理智后，没有反应，进入下一步

### ISSUE THREAD

**Issue by huangbang123** [MaaAssistantArknights/MaaAssistantArknights#3428]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷完理智后，没有反应，进入下一步

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10463233/asst.log)

**Comment by huangbang123** [comment]
请尽快答复

**Comment by ntgmc** [comment]
你倒是说清楚啥叫没反应进入下一步啊 啥东西没反应

**Comment by ABA2396** [comment]
文件不存在，是手动删了还是更新没更上，重新下个完整包覆盖一下
