### ISSUE TITLE
肉鸽放置错误

### ISSUE THREAD

**Issue by FredB-mine** [MaaAssistantArknights/MaaAssistantArknights#343]
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
自动刷肉格式有时会不停放置干员到不存在的方格上 例如酒商运输队

**Comment by FredB-mine** [comment]
并且有时候技能的自动选择有问题

**Comment by MistEO** [comment]
发下日志吧~
