### ISSUE TITLE
倉庫識別報錯

### ISSUE THREAD

**Issue by vonnoq** [MaaAssistantArknights/MaaAssistantArknights#3430]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

識別結果看起來數量都沒問題
但是都報錯
![Depot](https://user-images.githubusercontent.com/121179930/213662157-2fa4d1fc-c832-4adf-9f63-81c95e7bc4c9.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10464998/asst.log)

### 截图

![2023-01-20_13-38-55 081_raw](https://user-images.githubusercontent.com/121179930/213662498-96243c99-0ff8-49e5-874e-539b7494ec97.png)
![2023-01-20_13-38-56 150_raw](https://user-images.githubusercontent.com/121179930/213662512-749d0911-2fc1-4749-b2af-0d4cb6dd0329.png)
![2023-01-20_13-38-56 851_raw](https://user-images.githubusercontent.com/121179930/213662518-ea140cd7-ddb9-4efd-a713-c670495bb31c.png)
![2023-01-20_13-47-53 299_raw](https://user-images.githubusercontent.com/121179930/213662529-d30343f4-c196-4fc4-a381-348c947eb4b8.png)
![2023-01-20_13-47-57 074_raw](https://user-images.githubusercontent.com/121179930/213662531-d21cc1c9-a8a3-42cd-b401-e62b40773388.png)
![2023-01-20_13-47-59 684_raw](https://user-images.githubusercontent.com/121179930/213662532-c29433d4-df77-4fc5-b0ce-315bdcfa1d61.png)
![2023-01-20_13-48-00 658_raw](https://user-images.githubusercontent.com/121179930/213662535-15b3288d-ac0e-41a6-9948-f819cb1b27fa.png)
![2023-01-20_13-48-01 823_raw](https://user-images.githubusercontent.com/121179930/213662539-f50b3650-78ca-4ce7-8a5f-db6964ac1d3f.png)
![2023-01-20_16-48-32 344_raw](https://user-images.githubusercontent.com/121179930/213662545-5d278a2c-f008-4edf-9f94-11bc333c28dc.png)
![2023-01-20_16-48-36 013_raw](https://user-images.githubusercontent.com/121179930/213662547-7a873c4f-793d-4f7d-8d6f-82c5d4c53dc9.png)
![2023-01-20_16-48-38 774_raw](https://user-images.githubusercontent.com/121179930/213662556-7d2bec00-09c6-4529-9b1a-9dc37059217f.png)
![2023-01-20_16-48-39 713_raw](https://user-images.githubusercontent.com/121179930/213662560-f151e9f1-490a-4868-b7fe-5eacc42f3a8f.png)
![2023-01-20_16-48-40 576_raw](https://user-images.githubusercontent.com/121179930/213662562-2473064c-57ee-4751-83e4-2a0cb1737c52.png)
![2023-01-20_16-52-02 187_raw](https://user-images.githubusercontent.com/121179930/213662571-25f0dfef-0e07-4858-8eb7-f2909227e386.png)
![2023-01-20_16-52-06 273_raw](https://user-images.githubusercontent.com/121179930/213662577-2ec77c18-377c-4e92-873c-08d11b5b3c1e.png)
![2023-01-20_16-52-08 801_raw](https://user-images.githubusercontent.com/121179930/213662580-08a276c3-5fcd-4ddb-94a8-33eaa3002b08.png)
![2023-01-20_16-52-09 598_raw](https://user-images.githubusercontent.com/121179930/213662584-ce34ebe1-66cc-4a77-b3c8-da406a8741f2.png)
![2023-01-20_16-52-10 638_raw](https://user-images.githubusercontent.com/121179930/213662588-bfe1c363-b48d-4de8-a729-ee5f2c3b66f5.png)

### 还有别的吗？

模擬器: BlueStacks 5.10.0.1085 N32
作業系統: Windows 10 Pro 22H2
遊戲伺服器: 繁中服

**Comment by MistEO** [comment]
繁中服没有支持这个功能，要适配的话应该是 
![image](https://user-images.githubusercontent.com/18511905/213866726-758b1788-a955-46d8-915f-411c234e737a.png)
加一下这个就可以了

**Comment by vonnoq** [comment]
先謝謝您在過年期間仍抽空回覆。
新年快樂

加入以下圖檔後
![DepotMaterialTabClicked](https://user-images.githubusercontent.com/121179930/213874941-71df0475-2059-4603-9c50-faa775fc930a.png)
很可惜一樣報錯。
不過我注意到asst.log都有以下這段
roi is out of range 1066 599 [ -7, 250, 162, 132 ]
這個有可能是倉庫識別報錯的原因嗎？

**Comment by MistEO** [comment]
除了最终的报错外，识别结果整体正确并正常显示吗？
