### ISSUE TITLE
使用自动战斗官方保全作业任务出错SSS:Copilot

### ISSUE THREAD

**Issue by LYwyc** [MaaAssistantArknights/MaaAssistantArknights#3431]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用官方保全作业无论如何都没有反应，连接正常除了官方保全作业别的所有任务一切正常包括自动战斗OF-1

模拟器是蓝叠国际版N64最新版，替换过ADB无效，兼容模式无效，管理员启动MAA无效

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10466645/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/97736099/213705236-b744fe73-7583-4375-95cc-6fbf669d6836.png)

**Comment by MistEO** [comment]
在 “开始部署” 界面开始

**Comment by LYwyc** [comment]
> 

好的，我看下面的小提示写的是在“开始行动”界面，没往这方面想，感谢！麻烦了~
