### ISSUE TITLE
最新beta1疑似连接出现问题

### ISSUE THREAD

**Issue by H-XZ** [MaaAssistantArknights/MaaAssistantArknights#3438]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新前4.10.3可以正常连接蓝叠模拟器国际版并使用，更新后无法连接，同样的配置重新下载4.10.3可以正常使用

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10472622/asst.log)

**Comment by hguandl** [comment]
看日志应该是把 minitouch 传输到模拟器的时候出了问题，可能是因为beta版用了新的 adb 连接方式。请先试试看不把 MAA 放到带有中文的目录下

**Comment by yuanlemon** [comment]
> 看日志应该是把minitouch传到模拟器的时候出了问题，可能是因为beta版使用了新的adb连接方式。请先试看不把MAA放下有中文的目录

试了一下 改成英文路径就可以连接了
