### ISSUE TITLE
建议适配 7x24 小时造玉情景

### ISSUE THREAD

**Issue by miyouzi** [MaaAssistantArknights/MaaAssistantArknights#344]
主要是有几个需求：
 - 源石碎片制造站自动补货（一个源石制造站就能消耗理智all in 1-7的土，因此只需要补货一个源石制造站即可，多的不管）
 - 能够定位到 1-7 （可通过制造站或者加工站点选固源岩跳转）
 - 每天定时刷1-7以及日常。其中每周一或周日先刷满5把剿灭，再去1-7
 - 适配意外退出或闪断更新重新登陆

**Comment by a78239636** [comment]
同求，对1-7单独加个选项吧，对搓玉来说相当实用

**Comment by MistEO** [comment]
- `1-7` v3.3 已新增
- 搓玉自动补货 v3.3 已新增

**Comment by miyouzi** [comment]
> * `1-7` v3.3 已新增
> * 搓玉自动补货 v3.3 已新增

玛丽，你还有定时运行没有做，还不能休息哦（

**Comment by MistEO** [comment]
> > * `1-7` v3.3 已新增
> > * 搓玉自动补货 v3.3 已新增
> 
> 玛丽，你还有定时运行没有做，还不能休息哦（

定时 core 不打算做，快去催 @ChingCdesu !
