### ISSUE TITLE
在获取信用及购物板块运行时会错误的进入火蓝之心OF-1关卡

### ISSUE THREAD

**Issue by Smartisanoo** [MaaAssistantArknights/MaaAssistantArknights#3442]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在获取信用及购物板块运行时会错误的进入火蓝之心OF-1关卡

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10473478/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10473485/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10473486/gui.log)

### 截图

![屏幕截图_20230122_090514](https://user-images.githubusercontent.com/53090048/213895961-5edac5cf-a294-49f5-abe6-8929341e1e94.png)
![屏幕截图_20230122_090533](https://user-images.githubusercontent.com/53090048/213895964-7f49e36d-37d7-4297-98cf-6538248771a0.png)
bug录屏：https://www.aliyundrive.com/s/gSfbYdsvWhB

https://user-images.githubusercontent.com/53090048/213896063-af5dd05f-7f31-41d4-9e89-fc3b71b9f64d.mp4

### 还有别的吗？

无

**Comment by SnowParaselene** [comment]
这个不是bug吧，设置里信用相关关掉借助战赚信用就没了，OF关卡不消耗理智
