### ISSUE TITLE
MAA 4.10.4-beta.1 无法连接到蓝叠模拟器

### ISSUE THREAD

**Issue by KUAPT** [MaaAssistantArknights/MaaAssistantArknights#3443]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 4.10.4-beta.1 无法连接到蓝叠模拟器  一直卡在“正在连接模拟器”

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10473582/asst.log)

### 截图

![1111](https://user-images.githubusercontent.com/110989625/213897590-e567d1a1-cb34-4eb1-a8d0-224529e274e8.png)

### 还有别的吗？

更新前处首次连接时间很长以外一切正常

**Comment by MistEO** [comment]
```log
[2023-01-22 10:08:27.459][TRC][Px991c][Txb384] asst::Controller::call_command_tcpip | enter
[2023-01-22 10:12:17.047][TRC][Px991c][Txa1f8] asst::Assistant::~Assistant | enter
```

等 @hguandl 佬瞅瞅咋回事
