### ISSUE TITLE
实体手机在重新拔插后无法进行操作，必须重启MAA才可以进行操作

### ISSUE THREAD

**Issue by liyu-kun** [MaaAssistantArknights/MaaAssistantArknights#3444]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

破笔记本带不动模拟器，使用实体机进行游戏。偶尔会有需要断开USB连接进行充电的情况，此时如果之前使用过MAA，在不重启MAA的情况下断开USB之后再次连接，将无法对手机进行操作。使用的触控模式是MaaTouch。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10473948/asst.log)

### 还有别的吗？

使用的是红米Note10 Pro实体手机，MIUI13.0.11。

**Comment by ABA2396** [comment]
连接成功后会默认adb为连接状态（即使断开之后还是判断为连接），不这样的话在执行完任务后再使用单独的功能（如单次的公招、自动战斗等）会花费大量的时间在重新连接设备上。按现在的逻辑现在好像是重试失败20次后（大概5分钟）会再次启动设备并连接，不知道手机会不会这样。感觉这个逻辑是该改改，但是有些设备不重试会连不上，不知道有啥好办法

**Comment by liyu-kun** [comment]
测试了一次，好像并不会在5分钟之后重连。另外感觉即使是5分钟可能等待的时间也相当比较长。以下是测试的日志。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10474158/asst.log)

**Comment by liyu-kun** [comment]
更新4.10.4版本后好像仍然无法实现重连

![QQ截图20230128223707](https://user-images.githubusercontent.com/13912598/215272555-03561971-7c68-4705-845a-17260f61d0eb.png)


[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10527487/asst.log)

**Comment by sino1641** [comment]
尝试下开手机的无线adb 
那就可以一边充电一边挂机
刷日常的话对延迟也没什么要求

**Comment by liyu-kun** [comment]
之前也尝试过无线调试，但是好像每次开启它都会设置一个新端口，以至于每次都要重新配置MAA的连接，相当麻烦，所以后来还是换成有线连接了

**Comment by sino1641** [comment]
> 之前也尝试过无线调试，但是好像每次开启它都会设置一个新端口，以至于每次都要重新配置MAA的连接，相当麻烦，所以后来还是换成有线连接了

先连接 
然后指定 `adb tcpip 5555` 
手机重启前都可以用这个端口。

**Comment by liyu-kun** [comment]
感谢！虽然成功了，但是确实是慢，我还是去研究一下自动重连吧【
