### ISSUE TITLE
建议刷理智功能增加一个只刷石头不刷理智液的功能

### ISSUE THREAD

**Issue by 4573qu** [MaaAssistantArknights/MaaAssistantArknights#3446]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

主要的问题是
1.理智液存在且刷理智液勾选且数量为0时会自动停止任务：之前挂机刷好几天材料都是一到4点就断，每次都得在睡前把理智液需求改成1重新开始挂理智，剩下的刷的数量就得手动算，很麻烦而且很烦
2.不能不刷取理智液只刷石头：尤其是过年送了几个特别的理智液之后，领了又暂时不想用，我还有好几十颗石头的材料没有刷，这时候maa就完全用不了只能手动来了（理智液数量设置为0则在理智不足时直接停止任务）

### 有什么好的想法？

直接取消绑死刷石头和刷理智就可以解决问题
选择石头时默认勾上刷理智液，但用户可以手动取消勾选
如果选择刷石头不选择刷理智液或者理智液刷取数量为0的时候点击花费源石获得理智的按钮并直接碎石

### 其他内容

貌似还有一个刷理智液栏填写数字大于理智液实际拥有数量时会在使用理智液界面直接停止任务。
这个记不太清了，但是最近全是过年特殊理智液，我也测试不了

**Comment by MistEO** [comment]
理智药比源石没有优势啊，为啥要优先吃石头

**Comment by 4573qu** [comment]
> 理智药比源石没有优势啊，为啥要优先吃石头

正如我所说的 比如说这次过年送的五个理智液，比较有纪念意义，我就想留着不想很快用掉（想等快过期）

**Comment by ABA2396** [comment]
做材料规划难道不是根据材料数量么，有刷指定材料数量的指定数量功能，设置里还有一个开关是等当前理智恢复一点后再碎石。

**Comment by ABA2396** [comment]
做材料规划难道不是根据材料数量么，有刷指定材料数量的指定数量功能，设置里还有一个开关是等当前理智恢复一点后再碎石。

**Comment by 4573qu** [comment]
> 做材料规划难道不是根据材料数量么，有刷指定材料数量的指定数量功能，设置里还有一个开关是等当前理智恢复一点后再碎石。

应该是按数量的多
但是我一般是按石头来的
就是根据我现在总的石头数量（或者要刷的石头数量）和活动关卡单件出率之比将石头分成2或者3堆，然后把石头刷完为止
