### ISSUE TITLE
自动公招数大于1导致电脑重启

### ISSUE THREAD

**Issue by GQQTai** [MaaAssistantArknights/MaaAssistantArknights#3447]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

自动公招数大于1导致电脑重启
4.10.3之前的版本没有这种情况

### Log files

[1.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10475957/1.txt)

**Comment by GQQTai** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10475978/gui.log)

**Comment by MistEO** [comment]
发下 asst.log 文件看看

**Comment by GQQTai** [comment]
[Uploading asst.log…]()
