### ISSUE TITLE
水月肉鸽更快速自动刷取原石锭的建议

### ISSUE THREAD

**Issue by ysjyx7** [MaaAssistantArknights/MaaAssistantArknights#3448]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我目前的需求是用Maa自动肉鸽刷取原石锭，目前的问题是速度比较慢，下面是对这个问题的分析。

### 有什么好的想法？

实际运行中Maa的一些决策会导致这个过程比较慢，具体有如下几个原因：
1. 获得招募券的时候需要滑动干员列表来获取当前可以招募的干员信息，但是这个过程比较慢
2. 获得藏品的时候似乎也有明显的停顿来识别这个藏品是什么
3. 战斗掉落的招募券似乎会重复这个选择的过程，这会进一步拉低效率。

事实上，对于用最低难度快速刷取原石锭应该**可以只用一个干员单刷**？初始可以默认选择**后勤分队**（目前Maa的策略应该是指挥+海沫刷），然后仅在初始选择一个核，战斗掉落的东西可以直接舍弃，尽量求速度，并且我认为商店投资的效率应该最多一次能投十几个hh。
当然，我猜测自动刷取原石锭可能是把自动在肉鸽刷分的逻辑复用过来了，我上述的想法可能需要增加一些额外的code（我不了解C#，很抱歉）？
希望您们可以考虑增加这个功能:)

**Comment by Emperor-of-Fortune** [comment]
我知道你需要更快速的源石锭刷取策略，你可以在软件的目录中resource文件内的config.json里修改MAA的截图延迟、滑动距离以及adb的滑动倍数．
而开局干员完全可以在MAA软件的设置更改，开局分队也是如此．
干员的舍弃我没有好的建议，或许你可以在resource\roguelike\recruitment.json中删除大部分的干员，但是这样同时会影响刷分数时的干员选择策略．
希望的回答对你能有帮助．

**Comment by MistEO** [comment]
这些逻辑是 c++ 写的（）

**Comment by ysjyx7** [comment]
> 这些逻辑是 c++ 写的（）

抱歉抱歉，没有看过Maa的文档，只是拿过来就用了hh

**Comment by ysjyx7** [comment]
> 这些逻辑是 c++ 写的（）

抱歉我没有认真看过Maa文档，只是拿过来就用了hh

**Comment by ysjyx7** [comment]
> 我知道你需要更快速的源石锭刷取策略，你可以在软件的目录中resource文件内的config.json里修改MAA的截图延迟、滑动距离以及adb的滑动倍数． 而开局干员完全可以在MAA软件的设置更改，开局分队也是如此． 干员的舍弃我没有好的建议，或许你可以在resource\roguelike\recruitment.json中删除大部分的干员，但是这样同时会影响刷分数时的干员选择策略． 希望的回答对你能有帮助．

感谢，我会尝试一下

**Comment by ysjyx7** [comment]
我想我的疑问已经解决了，感谢两位大佬的回复:)
以后必然多读文档hh
