### ISSUE TITLE
建议记住上一次关闭时的窗口位置。

### ISSUE THREAD

**Issue by Yue-plus** [MaaAssistantArknights/MaaAssistantArknights#3450]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

MAA **每次** 启动时会在屏幕中间显示。

### 有什么好的想法？

我每次习惯把MAA拖到屏幕边角，既能看到 Log 也不挡住模拟器窗口。
所以建议记住上一次关闭时的窗口位置，这样就不用每次开都要拖动一下了。

——究极懒癌。Orz

### 其他内容

![image](https://user-images.githubusercontent.com/33195150/214137436-da607421-3a2d-4385-b85c-76876accadc7.png)

**Comment by MistEO** [comment]
pr 已经有了，还没来得及合
