### ISSUE TITLE
MAA v4.10.4 beta.1无法连接蓝叠模拟器

### ISSUE THREAD

**Issue by Ark-Schwarz** [MaaAssistantArknights/MaaAssistantArknights#3451]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

蓝叠模拟器版本Pie64，adb也可以正常连接，MAA v4.10.4 beta.1连接大概7秒后出现连接失败，强制替换adb与管理员启动均无用

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10485985/asst.log)
问题时间大概在[2023-01-24 10:40:24.222]这地方

### 截图

<img width="591" alt="屏幕截图_20230124_105653" src="https://user-images.githubusercontent.com/46624134/214203432-3e9b8fd4-98e6-43bc-905e-db1ea805e672.png">

**Comment by UVJkiNTQ** [comment]
同样配置，我遇到的是提示截图失败。
但自动重试后正常。

**Comment by Baiyuqiao0416** [comment]
同样问题，把触控模式改成ADB Input可以暂时解决问题。
也可以参考 #3438 的回复，把路径改成全英文试试

**Comment by chy5301** [comment]
同样问题，我遇到的是一直提示正在连接，如果点停止也会一直提示正在停止

**Comment by fatefate0727** [comment]
同样的问题。
我这边排查了包括无空格全英文路径；重启模拟器、MAA、电脑；手动修改连接地址；更新模拟器至最新版本；切换触控模式均未解决。
然后抱着尝试一下的态度再次重启电脑，好了。。。。稀里糊涂的好了

**Comment by MistEO** [comment]
内测版默认把 adb-lite 禁用掉了，试试看有没有效果

**Comment by luoke233** [comment]
好的，谢谢

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月25日(周三) 中午12:28
收件人: ***@***.***&gt;;
抄送: "Ark ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] MAA v4.10.4 beta.1无法连接蓝叠模拟器 (Issue #3451)




 
同样问题，把触控模式改成ADB Input可以暂时解决问题。
 也可以参考 #3438 的回复，把路径改成全英文试试

**Comment by Baiyuqiao0416** [comment]
刚更新了4.10.4-beta1.31，解决了这个问题，谢谢
