### ISSUE TITLE
自动战斗报“请求网络服务错误”

### ISSUE THREAD

**Issue by BiologyHazard** [MaaAssistantArknights/MaaAssistantArknights#3452]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗输入神秘代码报“请求网络服务错误”

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10489984/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/44924110/214300879-2d3ab83f-4271-4e74-b3ad-d5918f2a82b9.png)

**Comment by ntgmc** [comment]
你好，
目前作业站暂未修复，该功能尚不可用。
请下载群文件的json作业使用。

**Comment by BiologyHazard** [comment]
了解了，谢谢帮助
