### ISSUE TITLE
瑕光皮肤头像识别错误

### ISSUE THREAD

**Issue by Zetros090** [MaaAssistantArknights/MaaAssistantArknights#3458]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗中，使用皮肤的瑕光会被头像识别为耀光
![image](https://user-images.githubusercontent.com/74809363/214497590-5877ae0c-a5be-4e12-b034-5716092a5924.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10496812/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/74809363/214497638-54344a94-5db0-4e59-a294-316b866ecf9e.png)

**Comment by Zetroles** [comment]
版本是最新的测试版
另外，还出现了桃金娘有时仍然开不出技能的情况，位置如图
![image](https://user-images.githubusercontent.com/74809363/214497844-56692943-995d-4851-9142-faf5499fdcd2.png)
