### ISSUE TITLE
剿灭增加一个打满1800后自动停止的选项

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantArknights#346]
昨天剿灭没打满，今天打了两局后，打第三局的时候突然想起来应该满了，断线重连后果然如此（

**Comment by ABA2396** [comment]
> 

没打完之前的剿灭的人上限不是1800.jpg

**Comment by MistEO** [comment]
鹰角要出剿灭扫荡啦，我摆！

**Comment by MistEO** [comment]
扫荡模式下，打满 1800 后，无法继续任务，好耶

![image](https://user-images.githubusercontent.com/18511905/188464474-6ef8328e-13ac-422b-b9fd-27679521dbf2.png)
![image](https://user-images.githubusercontent.com/18511905/188464506-8ec653fe-bdad-4eba-89e3-39173caff2f1.png)

**Comment by zzyyyl** [comment]
草，建议加一个 YJ-fixed 的 label
