### ISSUE TITLE
[建议]当识别不出现在状态时，尝试在屏幕上点一下

### ISSUE THREAD

**Issue by sunyink** [MaaAssistantArknights/MaaAssistantArknights#3465]
### 说说你遇到的问题？

你好。举例：23年初的国服23年新春签到，接下来还会在初七、十五，服务器4点刷后首登 送一个 合成玉红包。这是一个全屏的界面。类似这种突然出个全屏界面的情况，maa就会无法识别目前状态卡住，自动排班啥的都完蛋了。虽然这个界面没有关闭按钮的“x”号，但其实只需要屏幕上随便点下就能过去。

这种情况不罕见。故，建议加个排错措施：当出现模拟器无法识别当前游戏情况时，可以尝试在屏幕点一下后重新识别状态，重复个2-3论，该就能解决。

**Comment by Snow-dash** [comment]
然后点到抽卡怎么办？点到碎石怎么办？

**Comment by ABA2396** [comment]
有些时候的活动是一个链接，你点的话直接转跳到浏览器去了。

**Comment by HydrogenDeuterium** [comment]
> 然后点到抽卡怎么办？点到碎石怎么办？

感觉可以找一个角落的位置点一下，比如左侧助理位置。
顺便我上次不知道为啥maa把通知栏给我拉下来了，然后也寄了

**Comment by 134820134820** [comment]
> ### 说说你遇到的问题？
> 你好。举例：23年初的国服23年新春签到，接下来还会在初七、十五，服务器4点刷后首登 送一个 合成玉红包。这是一个全屏的界面。类似这种突然出个全屏界面的情况，maa就会无法识别目前状态卡住，自动排班啥的都完蛋了。虽然这个界面没有关闭按钮的“x”号，但其实只需要屏幕上随便点下就能过去。
> 
> 这种情况不罕见。故，建议加个排错措施：当出现模拟器无法识别当前游戏情况时，可以尝试在屏幕点一下后重新识别状态，重复个2-3论，该就能解决。

觉得还是不能随便乱点，有些可能是网页链接，有的更有可能点到抽卡碎石，其实最好的办法是能给maa加一个短信/邮件的提醒功能

**Comment by 134820134820** [comment]
或者说其实自己会搞的话可以在任务流程里自己做配饰，我就是自己搞的
