### ISSUE TITLE
内存占用过大

### ISSUE THREAD

**Issue by 1164844282** [MaaAssistantArknights/MaaAssistantArknights#347]
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8478040/asst.log)
最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_
![图片](https://user-images.githubusercontent.com/52785205/163096099-46254b46-4405-4cae-b50c-acc41dc56b59.png)
![图片](https://user-images.githubusercontent.com/52785205/163096110-467ef22c-d4e4-4307-8ed7-3471fd1a4b12.png)

Thanks♪(･ω･)ﾉ

**Comment by ABA2396** [comment]
正常大小.jpg

**Comment by Huang-LM** [comment]
确实也遇到类似的问题，关了重开又正常了

**Comment by MistEO** [comment]
wont fix
