### ISSUE TITLE
公招结束无法立刻进入下一步骤，间隔5分钟左右才会继续

### ISSUE THREAD

**Issue by happyhaddy** [MaaAssistantArknights/MaaAssistantArknights#3470]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

一键长草中公招步骤结束无法立刻进行下一步骤，模拟器画面停在公招界面，maa没有当期步骤提示，5分钟后才会继续步骤

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10516263/asst.log)
 2023年1月27日14:40:26 到 2023年1月27日14:45:48

### 截图

![image](https://user-images.githubusercontent.com/22446056/215026284-e909886a-c0fb-4fd2-908c-314d99207ebe.png)

**Comment by hifuclub** [comment]
![image](https://user-images.githubusercontent.com/47740858/215283034-58a4574a-ea74-4e3b-8a33-9b0a84b45d61.png)
应该是卡在这一句了五分钟,这是个共性问题,我也卡在这里
![image](https://user-images.githubusercontent.com/47740858/215283209-56457657-6b53-4f20-be5c-052901eb9cbd.png)

**Comment by hifuclub** [comment]
![image](https://user-images.githubusercontent.com/47740858/215283235-00788bde-913a-4d06-b086-c2c7a29570ac.png)
应该是卡在这里了五分钟,这是一个共性问题,我也卡在这里
![image](https://user-images.githubusercontent.com/47740858/215283241-259e9aa7-de7c-4bc4-af0d-6e0f16639e96.png)
