### ISSUE TITLE
关于基建换班流程的问题和公招建议

### ISSUE THREAD

**Issue by Private233** [MaaAssistantArknights/MaaAssistantArknights#3472]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

近期都没怎么上github，有点懒，也就把自己发现的问题放一起提出了
1、在每个功能站选人上班的时候，会先点右上角“技能”标签选人，选完人之后会再点一次"工作状态"，是为什么，后面这一步是多余的吗
2、宿舍自动填充干员休息的时候会先点“未进驻”的标签，当后面无人需要休息时会导致当前仍在休息中的干员落选被踢出宿舍
3、在公孙佬的视频评论区了解到，想要公招出小车的话可以点无tag1h，因此是否可以考虑出一个不选tag1h的选项让用户选择（类似3星7h40min的一个选项

![QQ截图20230127174955](https://user-images.githubusercontent.com/108540840/215072361-4c364e8b-63c5-4c4d-9ba1-edd8956bde6c.png)

**Comment by ABA2396** [comment]
1是因为有些人的技能需要暖机，所以要按顺序入住，切换了选择模式后已选择的人会排在前面，这样就可以拉到最前面排序了

**Comment by BiologyHazard** [comment]
还可以酱紫赌吗，不缺黄票的话倒是可以试试

**Comment by Private233** [comment]
> 还可以酱紫赌吗，不缺黄票的话倒是可以试试
个人感觉有四星及以上的话就正常拿黄票，没有锁词条的话就去赌小车，这样比较好吧（毕竟大部分时间都是出3星的）

**Comment by BiologyHazard** [comment]
> > 还可以酱紫赌吗，不缺黄票的话倒是可以试试
> 
> 个人感觉有四星及以上的话就正常拿黄票，没有锁词条的话就去赌小车，这样比较好吧（毕竟大部分时间都是出3星的）

是嘛，我个人觉着1小时出两星的概率不小，哦前面的回复应该把黄票改成绿票

**Comment by HydrogenDeuterium** [comment]
话说我有点好奇 为啥要点进去设施里换人，感觉点左上进驻总览快多了

**Comment by francis-zhao** [comment]
> 话说我有点好奇 为啥要点进去设施里换人，感觉点左上进驻总览快多了

会客室要看线索，制造站、贸易站需要点进去看当前生产、交易的是什么再上对应加成干员。
控制中枢、发电站、办公室确实没必要一个一个点，现在这样可能是为了操作统一吧，时间可能也就多一两分钟，挂机其实也无所谓。
