### ISSUE TITLE
[繁中服&日服]自動肉鴿不開始BUG

### ISSUE THREAD

**Issue by orange890402** [MaaAssistantArknights/MaaAssistantArknights#3474]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

下載了最新的版本 結果不論繁中服還是日服 自動肉鴿都出現不斷跳已開始探索1次2次3次但卻不開始的情況

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10518930/asst.log)

### 截图

https://user-images.githubusercontent.com/115578376/215089926-7eb57636-e5c1-4342-bae2-b5347112d4f1.mp4

**Comment by MistEO** [comment]
那行绿字试了吗

**Comment by orange890402** [comment]
是說換adb那個嗎?
