### ISSUE TITLE
更新公告中的中文文本未使用大陆简体中文字形

### ISSUE THREAD

**Issue by BiologyHazard** [MaaAssistantArknights/MaaAssistantArknights#3475]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

截图中，更新公告中的”修复了若干bug“中的中文文本使用的字形不是大陆简体中文字形。
具体地说，”修“这个字右上角的反文旁，与大陆的简体中文字形不一致。

### 日志文件

应该不需要吧

### 截图

![image](https://user-images.githubusercontent.com/44924110/215108073-67c9601c-d9f1-42ed-9a6b-07836a3ac4f7.png)

### 还有别的吗？

操作系统地区设置为中国大陆，应该没有问题

**Comment by BiologyHazard** [comment]
v4.10.4正式版更新仍未解决

**Comment by BiologyHazard** [comment]
修了？高效啊

**Comment by zzyyyl** [comment]
话说这个东西要做本地化吗（？

**Comment by horror-proton** [comment]
> 话说这个东西要做本地化吗（？

应该不用, 现在 changelog 肯定是 zh-cn, 不会有日语韩语之类的吧 (

**Comment by MistEO** [comment]
> > 话说这个东西要做本地化吗（？
> 
> 应该不用, 现在 changelog 肯定是 zh-cn, 不会有日语韩语之类的吧 (

说不定，现在都自动生成了，假如下次人家用日语写 commit message（

**Comment by BiologyHazard** [comment]
这问题又出现了（

**Comment by BiologyHazard** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44924110/4a322cf8-39d1-4b72-a588-14b4f5433162)

**Comment by BiologyHazard** [comment]
又出现了
