### ISSUE TITLE
完全无法连接

### ISSUE THREAD

**Issue by dongmeng123** [MaaAssistantArknights/MaaAssistantArknights#3477]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://user-images.githubusercontent.com/110719782/215258251-4b08beea-e7e8-4b74-b46d-44e6cff3e0c7.png)
下载了这个版本的maa，按照指引下载了夜神模拟器，但是一打开就显示无法连接
![image](https://user-images.githubusercontent.com/110719782/215258289-702b0ec0-400c-401f-9ae1-e9790fb813de.png)
但是我看连接设置那边是正常的
![image](https://user-images.githubusercontent.com/110719782/215258324-ce6f88bb-a7a8-4c5d-bd1f-6c6dc7fbd25c.png)
不知道为什么会这样，就完全用不了
但是感觉下载的安装包没有问题欸，电脑看起来是64位的qaq
![image](https://user-images.githubusercontent.com/110719782/215258409-a82fe26d-3028-4d04-9989-3ee3feb9f073.png)
求帮助qaq

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10526865/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/110719782/215258456-9e57de6f-6417-4ff6-bfdf-befa81a82584.png)
![image](https://user-images.githubusercontent.com/110719782/215258489-f70a1c90-b989-47d8-8798-dad4e523fedd.png)

### 还有别的吗？

使用的是夜神模拟器
![image](https://user-images.githubusercontent.com/110719782/215258558-394ddecb-a60c-46e3-a229-7976c02fdc50.png)
电脑系统和配置如图（大概截全了）
![image](https://user-images.githubusercontent.com/110719782/215258581-e2ac71ff-f652-4536-9c6e-ca2b11cbb35b.png)

**Comment by dongmeng123** [comment]
![image](https://user-images.githubusercontent.com/110719782/215258854-fb587b2c-d1d0-444a-a696-bb7ba3642d8c.png)
模拟器保存在zhe'ge这个文件夹下面

**Comment by ntgmc** [comment]
问一下 你在某个用户群吗 我让管理联系你

**Comment by dongmeng123** [comment]
![image](https://user-images.githubusercontent.com/110719782/215258876-1ecc5f31-be3e-4062-a078-eb175ffce149.png)
模拟器保存在这里

**Comment by dongmeng123** [comment]
> 问一下 你在某个用户群吗 我让管理联系你

不在的 我现在可以去添加群www

**Comment by ntgmc** [comment]
> 

加11群：536038978

**Comment by dongmeng123** [comment]
> > 
> 
> 加11群：536038978

已经添加十群进群了www 
![image](https://user-images.githubusercontent.com/110719782/215259023-f30427ed-bcf5-40ab-8680-e7fa3df989a5.png)

**Comment by horror-proton** [comment]
```
[2023-01-28 17:20:17.714][GUI][Pxdae4][Tx10cd0] D:\Program Files\Nox\bin\.\nox_adb.exe devices | output:
List of devices attached

* daemon not running. starting it now on port 5037 *


[2023-01-28 17:20:17.717][TRC][Pxdae4][Tx10cd0] asst::Assistant::connect | enter
[2023-01-28 17:20:17.717][TRC][Pxdae4][Tx10cd0] asst::Controller::connect | enter
[2023-01-28 17:20:17.717][TRC][Pxdae4][Tx10cd0] asst::Controller::release_minitouch | enter
[2023-01-28 17:20:17.717][TRC][Pxdae4][Tx10cd0] asst::Controller::release_minitouch | leave, 0 ms
[2023-01-28 17:20:17.717][TRC][Pxdae4][Tx10cd0] asst::Controller::make_instance_inited | 0 , pre m_inited = 0 , pre m_instance_count = 0
[2023-01-28 17:20:17.717][ERR][Pxdae4][Tx10cd0] Call ` D:\Program Files\Nox\bin\.\nox_adb.exe connect 127.0.0.1:62001 ` create process failed, ret 0
[2023-01-28 17:20:17.717][INF][Pxdae4][Tx10cd0] Assistant::append_callback | ConnectionInfo {"uuid":"","details":{"adb":"D:\\Program Files\\Nox\\bin\\.\\nox_adb.exe","address":"127.0.0.1:62001","config":"Nox"},"what":"ConnectFailed","why":"Connection command failed to exec"}
[2023-01-28 17:20:17.717][TRC][Pxdae4][Tx10cd0] asst::Controller::connect | leave, 0 ms
```
CreateProcess 失败了? 这有点神奇

**Comment by MistEO** [comment]
试试用管理员打开 maa 再连？或者试试强制替换下 adb（连接设置里的按钮）

**Comment by dongmeng123** [comment]
> 试试用管理员打开 maa 再连？或者试试强制替换下 adb（连接设置里的按钮）

这个怎么操作啊，电脑小白有点不会操作

**Comment by dongmeng123** [comment]
> 

不过我也看不明白（） 是按理说这里不会错误吗

**Comment by Feng-HelloWorld** [comment]
蓝叠国际版也碰到了这个问题，我看了一下，发现是自动检测出的ADB.exe在路径前多了一层/.，手动删掉就就好了。没有注意更新前有没有这个点。
之前：C:\Program Files\BlueStacks_nxt\.\HD-Adb.exe
修改后：C:\Program Files\BlueStacks_nxt\HD-Adb.exe

**Comment by dongmeng123** [comment]
> 蓝叠国际版也碰到了这个问题，我看了一下，发现是自动检测出的ADB.exe在路径前多了一层/.，手动删掉就就好了。没有注意更新前有没有这个点。 之前：C:\Program Files\BlueStacks_nxt\ .\HD-Adb.exe 修改后：C:\Program Files\BlueStacks_nxt\HD-Adb.exe

感谢您的回复~这边将路径：D:\Program Files\Nox\bin\.\nox_adb.exe
修改为：D:\Program Files\Nox\bin\nox_adb.exe
（即删掉了中间的\.）后依旧显示无法链接，就有一些苦恼
![image](https://user-images.githubusercontent.com/110719782/215410762-ef42135d-bec3-4a45-b7bd-9bb067932c1c.png)

**Comment by dongmeng123** [comment]
> 蓝叠国际版也碰到了这个问题，我看了一下，发现是自动检测出的ADB.exe在路径前多了一层/.，手动删掉就就好了。没有注意更新前有没有这个点。 之前：C:\Program Files\BlueStacks_nxt\ .\HD-Adb.exe 修改后：C:\Program Files\BlueStacks_nxt\HD-Adb.exe

感谢您的回复~这边将路径：D：\Program Files\Nox\bin.\nox_adb.exe
修改为：D：\Program Files\Nox\bin\nox_adb.exe
（即删掉了中间的.\）后依旧显示无法链接，就有一些苦恼
![image](https://user-images.githubusercontent.com/110719782/215411258-b3a79ba2-3485-47a2-89e4-a313d7c89832.png)

**Comment by dongmeng123** [comment]
> 蓝叠国际版也碰到了这个问题，我看了一下，发现是自动检测出的ADB.exe在路径前多了一层/.，手动删掉就就好了。没有注意更新前有没有这个点。 之前：C:\Program Files\BlueStacks_nxt\ .\HD-Adb.exe 修改后：C:\Program Files\BlueStacks_nxt\HD-Adb.exe

感谢您的回复~这边将路径：D：\Program Files\Nox\bin\.\nox_adb.exe
修改为：D：\Program Files\Nox\bin\nox_adb.exe
（即删掉了中间的.\）后依旧显示无法链接，就有一些苦恼（已更新最新版本）
![image](https://user-images.githubusercontent.com/110719782/215411924-dc67a3c5-d2e1-45b5-8840-44679885b0b9.png)

**Comment by dongmeng123** [comment]
> 我的蓝叠国际版也有这个问题，不知道是不是因为用的PIE64引擎的原因。什么修改路径啥的都试过了，没用

主要是……之前我还用maa顺畅过一两个月，后来脑抽删了电脑模拟器和maa，就再也好不起来了！！可恶！！！

**Comment by Thinker152** [comment]
> 我的蓝叠国际版也有这个问题，不知道是不是因为用的PIE64引擎的原因。什么修改路径啥的都试过了，没用

重启试试

**Comment by 1127626014** [comment]
夜神模拟器一样的问题，请问解决了吗

**Comment by lxl1374** [comment]
有解决吗？我也遇到了一样的问题，之前是无法截图现在跟楼主一样。我用mumu没问题，夜神连不上

**Comment by Sunazumi** [comment]
已收到

**Comment by 1127626014** [comment]
我不知道重新连了个啥，好像是路径改了下，就可以了




我
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月27日(星期一) 中午11:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 完全无法连接 (Issue #3477)





 
有解决吗？我也遇到了一样的问题，之前是无法截图现在跟楼主一样。我用mumu没问题，夜神连不上

**Comment by MistEO** [comment]
> 试试用管理员打开 maa 再连？或者试试强制替换下 adb（连接设置里的按钮）

上面都已经说了，试下这个方法。和什么 .\ 没关系，不是那个问题。

还不行的不要光说不行，把日志发上来

**Comment by Sunazumi** [comment]
已收到

**Comment by dongmeng123** [comment]
> 

很抱歉这么晚回复！之前做了多次尝试（包括更换adb、试图寻找并关闭含有adb字样的进程、更换模拟器），仍然无法正常运行
这里为您附上最新的日志！
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12440616/gui.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12440618/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12440620/asst.log)

**Comment by Sunazumi** [comment]
已收到
