### ISSUE TITLE
更新v4.10.4後無法開啟，輸入字串格式不正確

### ISSUE THREAD

**Issue by vonnoq** [MaaAssistantArknights/MaaAssistantArknights#3479]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

v4.10.3正常
更新v4.10.4後無法開啟(如圖)
已試過重新解壓一個乾淨的v4.10.4跟重新開機

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10527419/gui.log)

### 截图

![123](https://user-images.githubusercontent.com/121179930/215270558-98650e9b-f205-4e17-88e1-6548d6b53c68.png)

### 还有别的吗？

作業系統: Windows 10 Pro 22H2

**Comment by MistEO** [comment]
炸在了看不懂的地方，等别的大佬来瞅瞅

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/4032375786/jobs/6932215249 试下这个版本有用吗（大约等个十几分钟就能下载了）

**Comment by MistEO** [comment]
![ALAJ$J6ADQ5D~JJZ%NVN81T](https://user-images.githubusercontent.com/18511905/215275089-c6dd3181-9989-421c-aec4-3f5c66080098.png)

繁中解析不了 NaN，fixed

**Comment by ABA2396** [comment]
打开 \config 文件夹下的 gui.json ，把里面的
"GUI.Monitor.Width":
"GUI.Monitor.Height":
"GUI.Position.Left":
"GUI.Position.Top":
删了
