### ISSUE TITLE
打開MAA後反饋輸入字串格式不正確。

### ISSUE THREAD

**Issue by Chengen0429** [MaaAssistantArknights/MaaAssistantArknights#3480]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![螢幕擷取畫面 2023-01-28 214535](https://user-images.githubusercontent.com/123816772/215270441-49a2d343-91fb-4d36-a28f-713d44cbae4c.png)
已經刪除重裝過了還是遇到這個問題 
我是在MAA官網下載的

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10527414/gui.log)

### 还有别的吗？

![螢幕擷取畫面 2023-01-28 220419](https://user-images.githubusercontent.com/123816772/215270741-ed2faf86-e777-4ff7-a27e-b319956cf5cc.png)
![螢幕擷取畫面 2023-01-28 220637](https://user-images.githubusercontent.com/123816772/215270789-8f40fcf4-2d15-47c8-a31e-a6bd71f09cd4.png)

**Comment by MistEO** [comment]
炸在了看不懂的地方，等别的大佬来瞅瞅

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/4032375786/jobs/6932215249 试下这个版本有用吗（大约等个十几分钟就能下载了）

**Comment by MistEO** [comment]
![ALAJ$J6ADQ5D~JJZ%NVN81T](https://user-images.githubusercontent.com/18511905/215275089-c6dd3181-9989-421c-aec4-3f5c66080098.png)

繁中解析不了 NaN，fixed

**Comment by HamBearGer** [comment]
我更新了一次还是不得彳亍

**Comment by HamBearGer** [comment]
我是繁體中文的系統也遇到了這個問題，在看開發進度完成後我重下了下
還是不可以，有沒有修復的補丁包

**Comment by MistEO** [comment]
再试试这个版本 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/4032479075/jobs/6932378808

**Comment by ABA2396** [comment]
打开 \config 文件夹下的 gui.json ，把里面的  
"GUI.Monitor.Width": 
"GUI.Monitor.Height": 
"GUI.Position.Left": 
"GUI.Position.Top": 
删了

**Comment by HamBearGer** [comment]
辛苦了程序員老哥們

**Comment by HamBearGer** [comment]
![image](https://user-images.githubusercontent.com/121067236/215276251-5800fc3e-c8d3-4c74-ae0c-7f12c2a20f74.png)


> 打开 \config 文件夹下的 gui.json ，把里面的 "GUI.Monitor.Width": "GUI.Monitor.Height": "GUI.Position.Left": "GUI.Position.Top": 删了                    可惜找不到

**Comment by Chengen0429** [comment]
> > 再試這個版本https://github.com/MaaAssistantArknights/MaaAssistantArknights/suites/10637970290/artifacts/531262680
> 
> 這個好了，試試看？

![螢幕擷取畫面 2023-01-29 012615](https://user-images.githubusercontent.com/123816772/215281201-4678731c-1cdd-498a-a21a-41e7d52a0c27.png)
可以了 謝謝大佬
