### ISSUE TITLE
2023/1/28 自动更新后应用启动报错退出

### ISSUE THREAD

**Issue by G-MCCF** [MaaAssistantArknights/MaaAssistantArknights#3481]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

2023/1/28 晚，今日首次开启 MAA 应用并连接，出现自动更新。
更新完成后重新启动，出现未知错误，关闭报错窗口后应用自动退出，其间无任何界面加载成功。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10527430/asst.log)
双击开启程序后，尚未加载出首页即报错。

### 截图

![image](https://user-images.githubusercontent.com/61048957/215270584-58cafdab-e591-4229-8ec7-a668d764e1ef.png)

### 还有别的吗？

操作系统：Windows 10 非最新版本。
模拟器：MuMu 模拟器非最新版本。
更新设置维持 1 月中旬首次安装时默认状况。

**Comment by MistEO** [comment]
炸在了看不懂的地方，等别的大佬来瞅瞅

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/4032375786/jobs/6932215249 试下这个版本有用吗（大约等个十几分钟就能下载了）

**Comment by MistEO** [comment]
试试重新下载完整包还有这个问题吗，有的话发下 gui.log 康康

**Comment by G-MCCF** [comment]
> 试试重新下载完整包还有这个问题吗，有的话发下 gui.log 康康

没有问题，但是 Wb 不适配了（）

**Comment by ABA2396** [comment]
> > 试试重新下载完整包还有这个问题吗，有的话发下 gui.log 康康
> 
> 没有问题，但是 Wb 不适配了（）

wb导航是所有版本一起关的，因为更新了新活动得下新的资源，但就剩一天就懒得改了
