### ISSUE TITLE
建议添加自动重连开关

### ISSUE THREAD

**Issue by AjinKimxu** [MaaAssistantArknights/MaaAssistantArknights#3484]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

人在外面，电脑在家里挂着清理智
想上线打打肉鸽，被一直顶号
虽然可以远控电脑关掉，但好麻烦;(

### 有什么好的想法？

增加自动重连开关/自动重连时间间隔

**Comment by sino1641** [comment]
现场改密码作为workaround也不是不行
反正maa重试10+次之后就会自动停掉
不过同样希望最好能加上自动重连开关
（或者能不能通过是否勾选开始唤醒作为重连与否的逻辑）
