### ISSUE TITLE
关于肉鸽的开局

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#3485]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

1. 从方舟主界面开启自动肉鸽后进入肉鸽界面，会自动结束以往没完成的肉鸽进度。

### 有什么好的想法？

1. 既然已经支持肉鸽中途暂停，而且肉鸽无法在有存档的情况下开新的一局，那么能否直接接着未完成的继续打

**Comment by BiologyHazard** [comment]
是不是因为maa在打肉鸽的时候是“有记忆”的，所以做不到从半中间开始打（？

**Comment by status102** [comment]
> 是不是因为maa在打肉鸽的时候是“有记忆”的，所以做不到从半中间开始打（？

这两种状态都是能够接手的，每次都是重新启动MAA后再开始自动肉鸽，不太认为有保存肉鸽状态到内存。
![image](https://user-images.githubusercontent.com/102887808/215383093-ecef5765-fc34-4e7c-8703-5105197a6d3e.png)
![image](https://user-images.githubusercontent.com/102887808/215383166-b39c1a87-151e-4e64-ac26-36afb8ac023d.png)
