### ISSUE TITLE
信用购物时无法购买讯使、嘉维尔

### ISSUE THREAD

**Issue by Genicur** [MaaAssistantArknights/MaaAssistantArknights#3489]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

rt
在练小号的时候发现的
无法购买 会点进查看干员详细简历里面

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10529295/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10529296/gui.log)

### 截图

![Screenshot_2023 01 29_15 51 48 961](https://user-images.githubusercontent.com/93466263/215313092-31766198-803d-47d8-913c-7fa938b67cc0.png)

### 还有别的吗？

蓝叠国际安卓7

**Comment by ABA2396** [comment]
这两个没做识别，而且不买完会卡住，新号就先把这俩买完吧

**Comment by BiologyHazard** [comment]
这个之前提过，不会修复
