### ISSUE TITLE
在mac上用parallel虚拟机无法运行maa

### ISSUE THREAD

**Issue by baizzzzzzz** [MaaAssistantArknights/MaaAssistantArknights#3493]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在macbook pro （系统版本 Ventura 13.1）上用parallel虚拟机无法运行maa，显示 "\\mac\Home\Downloads\MAA-v4.10.5-win-x64\MAA.exe"的值对于"filePath"无效。
请求解决~因为感觉windows版的maa比mac版的功能更多更好用QAQ。

<img width="654" alt="Screenshot 2023-01-29 at 9 22 14 pm" src="https://user-images.githubusercontent.com/123867524/215321084-d01aefb6-dce9-44fa-bb23-8b4971d8acc0.png">

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10529584/gui.log)
debug文件夹中只有gui一个文件

### 截图

<img width="654" alt="Screenshot 2023-01-29 at 9 22 14 pm" src="https://user-images.githubusercontent.com/123867524/215321267-fef74ed5-b093-435d-b027-74d1a5098187.png">

**Comment by l1006986533** [comment]
这题我会，移到C盘，别放在\\mac\Home\Downloads文件夹

**Comment by baizzzzzzz** [comment]
啊啊啊打开了！真的太感谢啦🥹

**Comment by l1006986533** [comment]
不用谢😊记得close issue哦
