### ISSUE TITLE
能否增加对生息演算的支持（哪怕是比较基本的）

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#3494]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

新的生息演算模式比较复杂，想要摸清楚规则掌握策略之后再打过太麻烦与困难了。好在我看了一下蚀刻章的要求，前三个蚀刻章只需要堆次数，注意一下打猎或者拿材料合成食物与设施，哪怕每次只能撑三到五天，靠堆次数也能拿出来。

### 有什么好的想法？

可以先做一下最基本的适配，注意一下打猎或者拿材料合成食物与设施，靠堆次数能把奖励与蚀刻章拿出来，天赋什么的也可以点一下。

**Comment by Cherrling** [comment]
已经有摆烂玩法了，开局随便选，进一关马上退出，完全不放干员不操作，几分钟刷到第五天左右敌人就冲家了，此时直接结算，能得五六十分，纯刷分还是挺快的

**Comment by xiaoweiXX** [comment]
> 已经有摆烂玩法了，开局随便选，进一关马上退出，完全不放干员不操作，几分钟刷到第五天左右敌人就冲家了，此时直接结算，能得五六十分，纯刷分还是挺快的

我看了，确实是邪道玩法并且有用，就是效率奇低，算上操作冗余大概1分半钟1把，1把有4个证章，并且每把不一定掉建设点数。

**Comment by Cherrling** [comment]
> > 已经有摆烂玩法了，开局随便选，进一关马上退出，完全不放干员不操作，几分钟刷到第五天左右敌人就冲家了，此时直接结算，能得五六十分，纯刷分还是挺快的
> 
> 我看了，确实是邪道玩法并且有用，就是效率奇低，算上操作冗余大概1分半钟1把，1把有4个证章，并且每把不一定掉建设点数。

https://www.bilibili.com/video/BV14G4y1S7sB
四分钟55证章，效率感觉还行

**Comment by xiaoweiXX** [comment]
> > > 已经有摆烂玩法了，开局随便选，进一关马上退出，完全不放干员不操作，几分钟刷到第五天左右敌人就冲家了，此时直接结算，能得五六十分，纯刷分还是挺快的
> > 
> > 
> > 我看了，确实是邪道玩法并且有用，就是效率奇低，算上操作冗余大概1分半钟1把，1把有4个证章，并且每把不一定掉建设点数。
> 
> https://www.bilibili.com/video/BV14G4y1S7sB 四分钟55证章，效率感觉还行

这个方法普通的脚本不行，地图好像是随机的不一定能点到正确的位置，要是点到奇遇之类的更是会打断。不过MAA可以增加一个摆烂模式，精准识别地图，进去然后秒退出，这样效率能比脚本强不少。

**Comment by Cherrling** [comment]
> > > > 已经有摆烂玩法了，开局随便选，进一关马上退出，完全不放干员不操作，几分钟刷到第五天左右敌人就冲家了，此时直接结算，能得五六十分，纯刷分还是挺快的
> > > 
> > > 
> > > 我看了，确实是邪道玩法并且有用，就是效率奇低，算上操作冗余大概1分半钟1把，1把有4个证章，并且每把不一定掉建设点数。
> > 
> > 
> > https://www.bilibili.com/video/BV14G4y1S7sB 四分钟55证章，效率感觉还行
> 
> 这个方法普通的脚本不行，地图好像是随机的不一定能点到正确的位置，要是点到奇遇之类的更是会打断。不过MAA可以增加一个摆烂模式，精准识别地图，进去然后秒退出，这样效率能比脚本强不少。

地图随机的，真要这么弄就得精准点的OCR了，看大佬们怎么考虑的吧

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/3504
