### ISSUE TITLE
[Feature] 生息演算速刷思路？

### ISSUE THREAD

**Issue by nullqwertyuiop** [MaaAssistantArknights/MaaAssistantArknights#3495]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前生息演算暂无可用的速刷脚本

#### Source
[Bilibili](https://www.bilibili.com/video/av863505926)

#### TL;DR
1. 开局随机选择干员
2. 任意进行战斗节点
3. 开始后直接退出结算
4. 重复操作

### 其他内容

无

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/3504
