### ISSUE TITLE
生息演算-自动刷烂分-夜神模拟器操作录制

### ISSUE THREAD

**Issue by chnhi** [MaaAssistantArknights/MaaAssistantArknights#3496]
在开始演算那个界面开始运行就行，一路跳过到第五天紧急撤退。

**Comment by chnhi** [comment]
夜神模拟器可用操作录制：[http://hivii.ysepan.com](url)
照着视频自己录制也一样：http://hivii.ysepan.com

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/3504
