### ISSUE TITLE
增加插件or扩展功能？

### ISSUE THREAD

**Issue by DuskXi** [MaaAssistantArknights/MaaAssistantArknights#3497]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

作者有没有考虑过加入插件或者扩展功能？

**Comment by MistEO** [comment]
没听懂

**Comment by MinGW32-2006** [comment]
@MistEO 就是类似于浏览器插件那样的吧，可以选择不要这个功能的这种，MAA现在的完整包是有点大

**Comment by DuskXi** [comment]
> @MistEO 就是类似于浏览器插件那样的吧，可以选择不要这个功能的这种，MAA现在的完整包是有点大

对

**Comment by DuskXi** [comment]
而且不只是某些功能可选，就是对于一些开发者而言，读API文档以后直接写扩展，和MAA项目之间是独立开发的，这样可能对于部分的开发者而言会方便许多，因为可能很多东西并不需要MAA的API做出一些什么改变。

**Comment by MistEO** [comment]
要写的话直接合进来就好了。现在是基础的模型和图像库大，具体到每个功能的业务代码和资源平均一下可能几百k都没有。而且总体积压缩包 100M，在这年头应该谈不上大吧
