### ISSUE TITLE
希望可以加入生息验算挂机作业

### ISSUE THREAD

**Issue by Smartisanoo** [MaaAssistantArknights/MaaAssistantArknights#3498]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

希望可以加入生息验算挂机作业

### 有什么好的想法？

![bili_poster-1675041924824](https://user-images.githubusercontent.com/53090048/215370874-c7bbb26d-a090-4926-8885-5861ea34687f.png)
【生息演算 440分钟拿完奖励？低配？萌新也能速刷！ 因为没干员！-哔哩哔哩】 https://b23.tv/AlmsbSr

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/3504
