### ISSUE TITLE
阿卡胡拉第三关 选择导能单元的时候不动了，手动选择后才正常

### ISSUE THREAD

**Issue by WSMTBG** [MaaAssistantArknights/MaaAssistantArknights#3499]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

阿卡胡拉第三关 选择导能单元的时候不动了，手动选择后才正常，两次选择都是一样的问题

### 日志文件

/

### 还有别的吗？

蓝叠5.9.300.1014 ，maa4.10.5

**Comment by MistEO** [comment]
日志发下

**Comment by WSMTBG** [comment]
> 日志发下
123盘可以吗，git提示我不能传25M以上的
https://www.123pan.com/s/MRY9-96UaA

**Comment by 12dora** [comment]
同样的问题, 第三关可稳定复现

**Comment by MeteorStream** [comment]
多索雷斯也一样，选道具稳定卡住。b站通关视频最新的评论有好几个其他人也这样QAQ

**Comment by WSMTBG** [comment]
那看来不是我的问题...

**Comment by WSMTBG** [comment]
![图片](https://user-images.githubusercontent.com/32087250/216506102-d269496e-e294-4087-98e6-4e99e2f17915.png)
这是多索雷斯的，好像是吧选道具界面识别成开局那个了

**Comment by WSMTBG** [comment]
[日志.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10575302/default.zip)

**Comment by zhongfly** [comment]
同样问题
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10712785/asst.zip)
![image](https://user-images.githubusercontent.com/11155705/218244120-e1b56f3d-3c6a-4480-9339-f04286ca65e4.png)

**Comment by MistEO** [comment]
内测版修复了，试试看

**Comment by WSMTBG** [comment]
> 内测版修复了，试试看

多索雷斯第三关正常了
