### ISSUE TITLE
是否可以增加一个新版本下载进度条

### ISSUE THREAD

**Issue by RWoxiN** [MaaAssistantArknights/MaaAssistantArknights#350]
如题，每次后台更新新版本的时候总是过了没多久就等不及了，然后直接任务管理器关掉aria进程，自己上github下新包放进目录。

主要是不确定程序能否正常满网速下载，有时候一个账号的一套流程都挂完了新版本还没下载好，自己上github十几秒就下好了。

PS. 这次 v3.1.2 更新完之后应用设置界面还是显示的 v3.1.1，不确定是更新失败还是单纯的忘改版本号了（

**Comment by MistEO** [comment]
哦草，是忘记改版本号了_(:з」∠)_

**Comment by MistEO** [comment]
进度条加不了，可能要重定向 aria2 的输出然后解析，有点麻烦（其实是我懒）_(:з」∠)_

期待一下 4.0 版本吧，应该会有（？
