### ISSUE TITLE
生机演算版本更新后python接口调用asst.connect()会卡住

### ISSUE THREAD

**Issue by ChildeRolando** [MaaAssistantArknights/MaaAssistantArknights#3500]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述
MAA可以正常使用，但是python接口在代码不变的情况下变得无法使用了。
Debug发现程序在执行到connect()方法的return语句时不会继续执行，不报错也不卡死，但是不执行返回也不执行下一条语句。
```    
def connect(self, adb_path: str, address: str, config: str = 'General'):

        return Asst.__lib.AsstConnect(self.__ptr,
                                      adb_path.encode('utf-8'), address.encode('utf-8'), config.encode('utf-8'))
```

我的调用语句为：
`asst.connect(adbPath, '127.0.0.1:' + port, "Nox")`
这个脚本一直正常运行，生机演算版本后突然出问题，急求指教，感谢🙇‍

### 日志文件

没有日志

### 还有别的吗？

使用夜神模拟器
win10

**Comment by MistEO** [comment]
日志发下 debug/asst.log

**Comment by ChildeRolando** [comment]
> 日志发下 debug/asst.log

不是MAAGUI的bug呀，是关于core的问题，我应该怎么生成这个日志

**Comment by MistEO** [comment]
> 日志发下 debug/asst.log

这个就是 core 的日志

**Comment by ChildeRolando** [comment]
> > 日志发下 debug/asst.log
> 
> 这个就是 core 的日志

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10536458/asst.log)

**Comment by ChildeRolando** [comment]
还出现了Asst.start()失败返回false的情况，任务如常，但是无法开始，是接口改写了吗？

> > 日志发下 debug/asst.log
> 
> 这个就是 core 的日志

**Comment by ChildeRolando** [comment]
解决了，路径中存在中文，虽然不知道为什么突然出这个问题，但是现在可以成功连接adb了
