### ISSUE TITLE
关卡选择异常

### ISSUE THREAD

**Issue by PianCat** [MaaAssistantArknights/MaaAssistantArknights#3501]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

明明之前支持WB关卡导航，现在突然不支持了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10531824/asst.log)

### 截图

![Snipaste_2023-01-30_11-04-37](https://user-images.githubusercontent.com/50688679/215378952-dc68b1f3-2e32-4bb0-ab74-6d952a4e63c6.png)

### 还有别的吗？

好像是MAA相关问题

**Comment by HeimaoLST** [comment]
我也遇到了相同的问题 更新新版本后就不能刷WB的关卡了

**Comment by bigqiao** [comment]
我分析一下是https://ota.maa.plus/MaaAssistantArknights/api/StageActivity.json
这里的关卡最低等级要求变成了v4.10.6，之前是v4.10.1
原因应该是生息演算更新以后入口位置被挤占了，要重新适配吧，然而v4.10.6还未release……

**Comment by Yus-git** [comment]
开了生息演算之后终端的左下角变了，而OCR没有识别中间的那个活动入口，自己手动改成当前/上次就好了，毕竟活动最后一天了

**Comment by MistEO** [comment]
就一天了，不打算适配了
