### ISSUE TITLE
生息演算增加建造功能

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#3507]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

生息演算增加建造功能，提高一点点效率。

### 有什么好的想法？

生息演算在花费建造点数获得一定建设之路的建设进度后，每轮开始会自带30木材、15石材与6铁矿石，用这些材料建造对应的建设设施与支援道具（6监控塔与5支援补给站），能够提高生息演算的评价（大概有37点，换算成证章大概是7个），增加一点点效率。对于目前还没有对应建设进度的玩家，可以增加开关来选择是否开启这项功能。

**Comment by xiaoweiXX** [comment]
这样同时还能刷一下建造数量的那个蚀刻章

**Comment by Emperor-of-Fortune** [comment]
奥,我想你知道的,在初始资源点满的情况下,我们可以合成5个支援线圈以及1个应急修理车就可以得到45分

**Comment by xiaoweiXX** [comment]
> 奥,我想你知道的,在初始资源点满的情况下,我们可以合成5个支援线圈以及1个应急修理车就可以得到45分

比我找的这俩还快一点

**Comment by xiaoweiXX** [comment]
生息演算都结束了（
