### ISSUE TITLE
没找到生息演算和保全的设置呀

### ISSUE THREAD

**Issue by MilkyWayFisher** [MaaAssistantArknights/MaaAssistantArknights#3509]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

MAA已经更新到了4.10.5，请问保全和生息演算的自动刷取在哪里设置呀

**Comment by ntgmc** [comment]
生息演算请更新4.10.6-beta1 保全请
![image](https://user-images.githubusercontent.com/74061867/215432992-92b94530-6172-4373-9007-29d0205fcef6.png)
使用该文件在【自动战斗】界面

**Comment by MilkyWayFisher** [comment]
> 生息演算请更新4.10.6-beta1 保全请 ![image](https://user-images.githubusercontent.com/74061867/215432992-92b94530-6172-4373-9007-29d0205fcef6.png) 使用该文件在【自动战斗】界面

感谢
