### ISSUE TITLE
【自动生息演算】bug汇总

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#3511]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

问题1：未知原因（可能是因为默认有干员？）第一次战斗时任务出错（图1）【日志1】
问题2：开始编队时第一次干员未设置导致无法开始（建议增加提示或使用教程）
问题3：有概率选完人全队补充后maa任务出错（第二次概率较大？）（无法点击【演算开始】，可能延迟不够？）（图2）【日志2，日志3，日志4，日志5，日志6，日志7，日志8】
问题4：演算开始后卡在某天日报（图3，图7）【日志9，日志13】
~~问题5：看图4【日志10】~~
问题6：遇见狮蝎卡住（图5）【日志11】
问题7：战斗开始前卡住（图6）【日志12】

### 日志文件

[日志1.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10534052/1.log)
[日志2.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10534007/2.log)
[日志3.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10534008/3.log)
[日志4.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10534119/4.log)
[日志5.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10534146/5.log)
[日志6.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10534166/6.log)
[日志7.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10534167/7.log)
[日志8.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10534198/8.log)
[日志9.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10534269/9.log)
[~~日志10.log~~](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10534370/10.log)
[日志11.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10534432/11.log)
[日志12.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10534712/12.log)
[日志13.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10541870/13.zip)

### 截图

![image](https://user-images.githubusercontent.com/74061867/215432036-4d151ab7-9d02-4c68-896f-15e0a5573b3e.png)
![I0NKUGX4 I6WKQR AJSNG`J](https://user-images.githubusercontent.com/74061867/215433991-eefdc6bf-df70-4409-9fbf-bfbd383763a9.jpg)
![DL(I8QL$0T %78)Q77MJ BT](https://user-images.githubusercontent.com/74061867/215438032-1478452b-2501-41b9-bdad-d98016866cd5.jpg)
~~![GSGU%}LSI8}HU T%$4DVNI](https://user-images.githubusercontent.com/74061867/215441196-e6eb2ea3-6948-458a-8d72-a9d129bb1a5f.jpg)~~
![O_ON15NW3OHAPZ PG415TGX](https://user-images.githubusercontent.com/74061867/215442684-aac97d2e-8bd1-460c-8870-5be1374cb332.png)
![image](https://user-images.githubusercontent.com/74061867/215449869-ea8832c1-14f0-4832-9f0d-7b51c4695e5b.png)
![image](https://user-images.githubusercontent.com/74061867/215641247-52d0356e-f462-4a58-b8b9-eded6e02926e.png)

**Comment by xiaoweiXX** [comment]
生息演算这次活动有很多动画，应该多留一些操作冗余的

**Comment by xiaoweiXX** [comment]
> 同样有问题三，挂三轮必会触发此bug，但原作者说了鲁棒性不强，等等之后大佬优化一下吧

我也是遇到了问题3，看来这里点击之前留的时间有点不够

**Comment by df4d** [comment]
刚刚遇到问题3，也是卡着不动，还好看了眼这里，要不又重复上报了

**Comment by mingkeeper** [comment]
坐等大佬解决

**Comment by BlizzArdHE** [comment]
![1](https://user-images.githubusercontent.com/51075350/215462488-a32e0455-6a9c-43f0-95ca-acd2e69daef1.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10535215/asst.log)
自动生息演算卡奇遇，有不断点击的声音

**Comment by WLLEGit** [comment]
> ![1](https://user-images.githubusercontent.com/51075350/215462488-a32e0455-6a9c-43f0-95ca-acd2e69daef1.png) [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10535215/asst.log) 自动生息演算卡奇遇，有不断点击的声音
> 
> 另附一个问题3的解决办法，在点击全队补充之后直接点左上角的返回按钮可以直接进入天数那个页面，不用等待补充完成的动画

这个问题能复现吗？log里面没有多余的点击命令，不太分析出来为什么。

关于问题3，点左上角不能保证补给按键正确按下了，可能因为网络问题没成功。这种情况按左上角会返回上级，逻辑比较乱。可以等下新版看看效果。

**Comment by yokinanya** [comment]
> ![1](https://user-images.githubusercontent.com/51075350/215462488-a32e0455-6a9c-43f0-95ca-acd2e69daef1.png) [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10535215/asst.log) 自动生息演算卡奇遇，有不断点击的声音
> 
> 另附一个问题3的解决办法，在点击全队补充之后直接点左上角的返回按钮可以直接进入天数那个页面，不用等待补充完成的动画

我加了点延迟，现在在测试，再跑一会看看有没有问题

**Comment by 6654d** [comment]
使用夜神模拟器和mumu
第一次进入正常完成。自动开启第二次时在点击全队补充后不再有任何操作，哪怕手动点击进入网图也无法自动接上点击
使用连接模式：夜神：默认
                         mumu：兼容
                        4.10.6-beta1

**Comment by ntgmc** [comment]
> 使用夜神模拟器和mumu 第一次进入正常完成。自动开启第二次时在点击全队补充后不再有任何操作，哪怕手动点击进入网图也无法自动接上点击 使用连接模式：夜神：默认 mumu：兼容 4.10.6-beta1

更新b2

**Comment by df4d** [comment]
4.10.6-beta2新问题：在一键长草页面顺序执行任务，到了“生息演算”就会出错，目前只能取消所有的任务，单独点“生息演算”，并且要手动按到生息演算活动页面内按开始才能执行。这个问题需要单独再开个issue么？

**Comment by ntgmc** [comment]
补充一个b2仍然存在的bug：
当开始战斗的界面点击后（进战斗前）出现网络卡顿，会直接结束
![image](https://user-images.githubusercontent.com/74061867/215530510-9e9a677e-589c-4050-a471-6e8dca4da12b.png)
（点击下图以后）
![image](https://user-images.githubusercontent.com/74061867/215530694-8ee44887-7501-4551-a018-e776fecdfd9f.png)
[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10537544/asst.-.log)

**Comment by beckham360012** [comment]
问题5在更新beta2后仍未解决，在出现编队受限的情况下报错

**Comment by ntgmc** [comment]
> 问题5在更新beta2后仍未解决，在出现编队受限的情况下报错

问题5划掉的原因是自己带了不合适的干员 非MAA问题 建议自行清空战斗干员

**Comment by beckham360012** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10537963/asst.log)
每次编入无心情的干员就会触发此bug，清空后第六轮仍触发，此时无法补充满心情干员

**Comment by WLLEGit** [comment]
> [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10537963/asst.log) 每次编入无心情的干员就会触发此bug，清空后第六轮仍触发，此时无法补充满心情干员

你这弹出了一个识别率0.5的确认窗口，记得是什么样子的不？
我这只能触发两种弹窗，无干员图1，有心情为空的图2

> 清空后第六轮仍触发，此时无法补充满心情干员
无法补充满心情是什么意思，是后期心情可以集成到下一局吗，应该只有开局有一次心情补充的。

![Screenshot_2023 01 30_18 52 32 861](https://user-images.githubusercontent.com/71222785/215624371-2d8c2bc6-2189-451c-8ab0-f403ae36e2da.png)
![Screenshot_2023 01 30_18 52 52 627](https://user-images.githubusercontent.com/71222785/215624312-e8d3c2d6-8374-470a-95e1-798b52ad8f74.png)

**Comment by ntgmc** [comment]
> > [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10537963/asst.log) 每次编入无心情的干员就会触发此bug，清空后第六轮仍触发，此时无法补充满心情干员
> 
> 你这弹出了一个识别率0.5的确认窗口，记得是什么样子的不？ 我这只能触发两种弹窗，无干员图1，有心情为空的图2
> 
> > 清空后第六轮仍触发，此时无法补充满心情干员
> 
> 无法补充满心情是什么意思，是后期心情可以继承到下一局吗，应该只有开局有一次心情补充的。
> 
> ![Screenshot_2023 01 30_18 52 32 861](https://user-images.githubusercontent.com/71222785/215624371-2d8c2bc6-2189-451c-8ab0-f403ae36e2da.png) ![Screenshot_2023 01 30_18 52 52 627](https://user-images.githubusercontent.com/71222785/215624312-e8d3c2d6-8374-470a-95e1-798b52ad8f74.png)

据我所知他说的是你发的图一 卡住了

**Comment by Olld47** [comment]
![Screen Shot 2023-01-31 at 10 09 43](https://user-images.githubusercontent.com/22239747/215641945-afaaa78c-cb83-4a46-bbb3-fcb8b467202f.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10541891/asst.log)
mac版beta2在生息演算开始界面运行无反应（会把之前没结束的生息演算结束掉，然后结束任务），在主界面也是

**Comment by ntgmc** [comment]
> ![Screen Shot 2023-01-31 at 10 09 43](https://user-images.githubusercontent.com/22239747/215641945-afaaa78c-cb83-4a46-bbb3-fcb8b467202f.png) [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10541891/asst.log) mac版beta2在生息演算开始界面运行无反应（会把之前没结束的生息演算结束掉，然后结束任务），在主界面也是

手动先结束了 等到按钮变绿再maa开始 这样行吗 主界面是不支持开始的

**Comment by Olld47** [comment]
> > ![Screen Shot 2023-01-31 at 10 09 43](https://user-images.githubusercontent.com/22239747/215641945-afaaa78c-cb83-4a46-bbb3-fcb8b467202f.png) [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10541891/asst.log) mac版beta2在生息演算开始界面运行无反应（会把之前没结束的生息演算结束掉，然后结束任务），在主界面也是
> 
> 手动先结束了 等到按钮变绿再maa开始 这样行吗 主界面是不支持开始的

好像又可以了，在开始演算这里可以开始。但是如果中途点会直接出错

**Comment by WLLEGit** [comment]
> > > ![Screen Shot 2023-01-31 at 10 09 43](https://user-images.githubusercontent.com/22239747/215641945-afaaa78c-cb83-4a46-bbb3-fcb8b467202f.png) [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10541891/asst.log) mac版beta2在生息演算开始界面运行无反应（会把之前没结束的生息演算结束掉，然后结束任务），在主界面也是
> > 
> > 
> > 手动先结束了 等到按钮变绿再maa开始 这样行吗 主界面是不支持开始的
> 
> 好像又可以了，在开始演算这里可以开始。但是如果中途点会直接出错

是不是上次作战刚进就退了，没有奖励。这样子是会卡住的，在修复计划中。

**Comment by 502y** [comment]
第五天紧急事态稳定任务出错
![image](https://user-images.githubusercontent.com/53784463/216018611-e2230bb3-4066-4f9a-bd55-2e57012137c7.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10555995/asst.log)
版本为4.10.6-b3，使用蓝叠模拟器（国版）官服。

**Comment by 502y** [comment]
> ### 紧急事态稳定任务出错
>  另：偶发不会在任务开始界面选择结束任务另开一局而是选择继续上局。

问题一疑似与另中提到的问题有关系，出现紧急事态后选择退出回到主界面，但是不会自动选择结束演算，右侧的按钮是“继续演算“而不是”开始演算”，可能导致问题发生。

**Comment by WLLEGit** [comment]
> 

beta3没有中断继续功能，该功能已经上传pr了，下个版本会更新。还有其余几个功能，具体可以看下pull request

**Comment by WLLEGit** [comment]
> > ### 紧急事态稳定任务出错
> > 另：偶发不会在任务开始界面选择结束任务另开一局而是选择继续上局。
> 
> 问题一疑似与另中提到的问题有关系，出现紧急事态后选择退出回到主界面，但是不会自动选择结束演算，右侧的按钮是“继续演算“而不是”开始演算”，可能导致问题发生。

beta3没有中断继续功能，该功能已经上传pr了，下个版本会更新。还有其余几个功能，具体可以看下pull request
