### ISSUE TITLE
“环境难度兼容” 提示弹出后 Fight 任务无法进行

### ISSUE THREAD

**Issue by NsCrosu** [MaaAssistantArknights/MaaAssistantArknights#3515]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

新安装的游戏，MAA 无法识别“环境难度兼容”的提示。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10535556/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/68761240/215472278-d7b2af6f-1688-48c0-98ce-8880d31c4f4d.png)

### 还有别的吗？

MuMu X 模拟器

**Comment by NsCrosu** [comment]
回顾了 issue，结果发现是未修复 closed （x

**Comment by ABA2396** [comment]
所有的新界面都没加识别，不是重新安装的话只会遇到一次，自己选了就好了
