### ISSUE TITLE
基建换班工作中的异格干员被强制下班

### ISSUE THREAD

**Issue by yyyy52** [MaaAssistantArknights/MaaAssistantArknights#352]
![屏幕截图 2022-04-15 203638](https://user-images.githubusercontent.com/53691794/163566508-50c97e86-4b98-4698-9cc8-cb5fdb57d797.png)
![屏幕截图 2022-04-15 203654](https://user-images.githubusercontent.com/53691794/163566521-3d314a53-f140-4d20-a662-2579566281dd.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8495703/asst.log)

**Comment by MistEO** [comment]
这个问题没有办法解决。从游戏界面上看不出来谁是谁的异格，只有选完人才有提示。所以 maa 上才会提示干员冲突。

如果一直使用 maa, 应该比较少会有这个问题，异格的优先级我们放到最低了
