### ISSUE TITLE
刷术狙芯片组时掉落识别错误

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#3525]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

话不多说 看图

### 日志文件

[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10542671/asst.-.zip)

### 截图

![image](https://user-images.githubusercontent.com/74061867/215661581-e64e811e-8222-476c-bec4-6cc6c53f9626.png)

**Comment by MistEO** [comment]
debug/drops 里的图片发下

**Comment by ntgmc** [comment]
![2023-01-31_12-12-29 067_raw](https://user-images.githubusercontent.com/74061867/215709425-2097ffd8-fd9d-4634-bd71-b15464f7517a.png)
![2023-01-31_12-14-45 265_raw](https://user-images.githubusercontent.com/74061867/215709436-301fbd57-ca9b-46d8-9c60-a25dab29f7b0.png)
![2023-01-31_12-17-00 973_raw](https://user-images.githubusercontent.com/74061867/215709440-1b4cb1b7-6186-4035-9db4-1579f5d6732b.png)

**Comment by ntgmc** [comment]
[drops.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10544371/drops.zip)

**Comment by horror-proton** [comment]
理论上仓库识别也会出问题, 但不知道为啥那边是正常的
