### ISSUE TITLE
reclamation algorithm报错

### ISSUE THREAD

**Issue by MilkyWayFisher** [MaaAssistantArknights/MaaAssistantArknights#3529]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

任务出错导致了运行终止
时间大致在 2023-01-31 16:45:57.779

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10544482/asst.log)
时间大致在 2023-01-31 16:45:57.779

**Comment by MilkyWayFisher** [comment]
![image](https://user-images.githubusercontent.com/104665931/215713044-23d5ad95-169b-4e13-9ac7-bee68212e261.png)
图片在这里

**Comment by WLLEGit** [comment]
截至beta2的使用方式：在生息演算界面执行生息演算任务

**Comment by WLLEGit** [comment]
截至beta2
使用方式：在生息演算界面开始执行生息演算任务。
前置要求：开始编队不为空，最好战斗编队为空
