### ISSUE TITLE
无法开启（闪退），可能1可能2都尝试过

### ISSUE THREAD

**Issue by BrightYao001** [MaaAssistantArknights/MaaAssistantArknights#353]
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ

https://user-images.githubusercontent.com/103753842/163656304-b10dc81b-078e-4d81-a7f5-9cbe1b082531.mp4

**Comment by MistEO** [comment]
使用的是最新的 3.1.2 版本吗？

**Comment by BrightYao001** [comment]
是的 @MistEO

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/828 可以按这个尝试一下

**Comment by MistEO** [comment]
v4.0.4 修复了一个可能的崩溃问题，再试试看
