### ISSUE TITLE
自动傀影肉鸽通关后报错“截图失败”

### ISSUE THREAD

**Issue by leirunze119** [MaaAssistantArknights/MaaAssistantArknights#3531]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

傀影肉鸽通关后卡住，并提示“截图失败，如反复出现请尝试重启或更换模拟器！”
卡住的位置是傀影肉鸽“覆水难收”关卡作战成功，肉鸽通关后的剧情开始处，此时MAA无法继续自动运行，但可以手动点击skip跳过剧情进入谢幕与结算界面。
用MAA也通关过几次水月肉鸽，从未出现过类似的问题。然而用MAA总共通关过两次傀影肉鸽，但两次都卡在同一个地方。

图形界面中出现的报错内容如下：
（1）
2023/1/30 7:22:40 关卡：险路恶敌
2023/1/30 7:23:03 开始战斗：覆水难收
2023/1/30 7:31:41 截图失败，如反复出现请尝试重启或更换模拟器！
2023/1/30 7:31:48 截图失败，如反复出现请尝试重启或更换模拟器！
（2）
2023/1/31 5:05:19 关卡：险路恶敌
2023/1/31 5:05:42 开始战斗：覆水难收
2023/1/31 5:09:23 截图失败，如反复出现请尝试重启或更换模拟器！
2023/1/31 5:09:31 截图失败，如反复出现请尝试重启或更换模拟器！

### 日志文件

asst.log见下，问题出现时间点为2023/1/30 7:31:41以及2023/1/31 5:09:23
（由于完整版体积太大，压缩后也超过允许上传文件大小上限了，所以只好截取了一部分……不过两次遇到问题时的log从启动到退出都完整保留了）
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10546658/asst.zip)

### 截图

debug/roguelike目录下生成的截图，但只有一片纯黑色
[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10546437/roguelike.zip)

**Comment by cenfusheng** [comment]
已修复
