### ISSUE TITLE
增加生息演算自动刷粗制赤金功能

### ISSUE THREAD

**Issue by bald-fu** [MaaAssistantArknights/MaaAssistantArknights#3532]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

希望能增加生息演算自动刷粗制赤金功能

### 有什么好的想法？

视频演示：BV1C84y1L7kD
需求物品：太阳谷名片+冶铸台+初始自带木头石头拉满
简要思路：开局在联络员处低价买到水，再用水初始携带的铁矿石在冶铸台合成粗制赤金赚差价

**Comment by zhongfly** [comment]
不用这样…你想办法拿到信物“老伊辛的水晶球”，每一张地图结算都会随机给东西，大概率是赤金。
我靠这个+maa 已经赤金上千了…

**Comment by bald-fu** [comment]
命运的水晶球效果为关卡结算时有小概率获得额外的食材，不会增加关卡结算时获得的赤金量
赤金增加是因为关卡结算时会固定+1赤金，陈旧的藏宝图的效果才是获得额外的赤金

在没有藏宝图的情况下，maa演算一次能存活5天，结算关卡8次，获得8赤金，如果增加使用冶铸台刷赤金功能，
1级冶铸台演算一次获得35赤金，3级冶铸台演算一次获得60赤金，每演算一次获得的赤金能增加337%~650%
综上，我认为还是可以考虑增加刷赤金功能

**Comment by zhongfly** [comment]
不过这是限时活动，不见得开发者会开发这样有难度的操作…

**Comment by HS7097** [comment]
主要是这种不消耗理智的活动，全跑路拿到低保也就已经够了，角色养成材料都是有上限的，只要MAA可以在活动时间内拿到所有奖励/大部分奖励，就让MAA慢慢刷就好了

**Comment by bald-fu** [comment]
是的，最后还是得看开发者的意愿，

不过我可以提供一部分逻辑思路：
因为此功能对玩家的进度有一定要求，所以最好在设置页面做一个开关（像借助战赚信用那样）；

1、开始演算后先不放大地图，先定位并点击地图左上角的亮点（即黑市），此时地图会放大并移动至黑市；
2、点击黑市，识别黑市中登场的人物，若有联络员，则点击开始行动；
     若无，则点击画面左下角的缩小地图按钮，结束刷赤金任务，进行现有的生息演算速刷任务；
     （联络员不在黑市应该是触发剧情了，可以考虑在maa页面上给用户弹个报错）
接下来就是买水造赤金，然后就能接现有的生息演算速刷任务了

**Comment by bald-fu** [comment]
> 主要是这种不消耗理智的活动，全跑路拿到低保也就已经够了，角色养成材料都是有上限的，只要MAA可以在活动时间内拿到所有奖励/大部分奖励，就让MAA慢慢刷就好了

我玩生稀盐酸不完全是为了奖励，我是真的喜欢这个模式
我想要在基地里布阵，但却没有那么多时间和精力去刷材料
如果有足够的赤金，那我只需要采集铁矿石就能做大量建筑，降低在基地布阵的时间成本

**Comment by bald-fu** [comment]
> 主要是这种不消耗理智的活动，全跑路拿到低保也就已经够了，角色养成材料都是有上限的，只要MAA可以在活动时间内拿到所有奖励/大部分奖励，就让MAA慢慢刷就好了

我玩生稀盐酸不完全是为了奖励，我是真的喜欢这个模式
我想要在基地里布阵，但却没有那么多时间和精力去刷材料
如果有足够的赤金，那我只需要采集铁矿石就能做大量建筑，降低在基地布阵的时间成本
