### ISSUE TITLE
愚人號刷理智異常

### ISSUE THREAD

**Issue by saunpcnaye** [MaaAssistantArknights/MaaAssistantArknights#3533]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

繁中服愚人號活動無法使用刷理智功能

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10547748/asst.log)
01-31 23:03

**Comment by Realmajia** [comment]
估计是繁中服活动中开始战斗按钮无法识别产生的错误。这边提供模拟器截图一张。

![Screenshot_20230131-213935](https://user-images.githubusercontent.com/105563281/215808982-5858c0ee-92f6-4dee-9af8-e078ccb80550.png)

**Comment by vonnoq** [comment]
我也是繁中服．
不過我運行了幾次都蠻正常的，
不用添加任何圖檔就能完成自動勾選代理/開始行動/離開回主畫面

**Comment by yuanlk** [comment]
嘗試用 ‘當前/上次’ 選著關卡後發現有兩個問題：
1. 繁中的 tasks.json 沒有 GoLastBattle (前往上一次作戰) 與 StartButton1 (開始戰鬥按鈕) 的相關適配文本。
2. OCR會把 “開始行動” 錯辨成 “開始衛動”。

通過修改繁中的 tasks.json 後，可以以 ‘當前/上次’ 在愚人號活動使用刷理智功能。
文件地址：
`MAA\resource\global\txwy\resource\tasks.json`
修改內容（在第二行添加以下即可）：
~~~
    "GoLastBattle": {
        "text": [
            "前往上一次作戰"
        ]
    },
    "StartButton1": {
        "text": [
            "開始衛動"
        ]
    },
~~~

**Comment by saunpcnaye** [comment]
目前變成關卡結束後 會自動跳出進入關卡的介面 然後就卡住了

**Comment by Realmajia** [comment]
> 

按你之前po的代码修正了一下还是有问题，自己排查了一下，task.json里还有两处关于开始战斗按钮的ocr结果修正，现在用了几个小时貌似没问题了。

	"BattleStartPre": {
        "text": [
            "開始行動",
            "開始突襲",
            "開始衛動",
            "開始試煉"
        ]
    },

        "GoLastBattle": {
        "text": [
            "前往上一次作戰"
        ]
    },
    "StartButton1": {
        "text": [
            "開始行動",
            "開始衛動"
        ]
    },

    "StartButton1": {
        "text": [
            "開始行動",
            "開始衛動"
        ]
    },
[tasks.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10557444/tasks.zip)

**Comment by saunpcnaye** [comment]
> > 目前變關卡結束後 會自動跳出進入關卡的界面 然後就卡住了
> > 更不知道怎麼地 錄到半恢復正常了 再更目前是時好時壞 具體原因我不清楚了
> 
> 會不會是你的理智不夠進入下一次， 同時又只是勾選刷理智？

有勾選吃理智藥 
理智不足時仍會補充

**Comment by saunpcnaye** [comment]
> > 
> 
> 按你之前po的代码修正了一下还是有问题，自己排查了一下，task.json里还有两处关于开始战斗按钮的ocr结果修正，现在用了几个小时貌似没问题了。
> 
> ```
> "BattleStartPre": {
>     "text": [
>         "開始行動",
>         "開始突襲",
>         "開始衛動",
>         "開始試煉"
>     ]
> },
> 
>     "GoLastBattle": {
>     "text": [
>         "前往上一次作戰"
>     ]
> },
> "StartButton1": {
>     "text": [
>         "開始行動",
>         "開始衛動"
>     ]
> },
> 
> "StartButton1": {
>     "text": [
>         "開始行動",
>         "開始衛動"
>     ]
> },
> ```
> 
> [tasks.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10557444/tasks.zip)

使用後情況仍一樣 平均2場發生一次
