### ISSUE TITLE
水月肉鸽追忆映射分队选择失败

### ISSUE THREAD

**Issue by dylanhz** [MaaAssistantArknights/MaaAssistantArknights#3536]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

2月的追忆映射无法选中分队，一直拖动查看。普通模式正常。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10552495/asst.zip)

### 截图

![Screenshot_2023 02 01_09 49 45 771](https://user-images.githubusercontent.com/53137516/215925341-fad5a5d0-f835-437b-af1b-1e466090f77e.png)

### 还有别的吗？

v4.10.6-beta.3

**Comment by ABA2396** [comment]
设置里选的啥分队
