### ISSUE TITLE
MAA连接模拟器时和网银U盾一同使用会报连接失败

### ISSUE THREAD

**Issue by lindehongdao** [MaaAssistantArknights/MaaAssistantArknights#3538]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

 2月1日的09:52:47，在插入网银U盾的时候，输入密码时，MAA提示连接失败，有弹窗提示应用软件进程暂停。
弹窗界面受保护无法使用截图工具截图。
拔除网银重新尝试连接，MAA正常运行。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10552988/asst.log)

### 还有别的吗？

模拟器是蓝叠5，5.9.0.6502 N32 版本
操作系统信息如下：
版本	Windows 11 专业工作站版 Insider Preview
版本	22H2
安装日期	‎2023/‎1/‎30
操作系统版本	25284.1000
体验	Windows Feature Experience Pack 1000.25284.1000.0
使用的网银是浙江农信丰收宝

**Comment by cenfusheng** [comment]
网银U盾与ADB之间的问题，与防火墙问题同理，暂无修复计划，不建议同时使用。
