### ISSUE TITLE
刷理智-关卡选择-龙门币-5无法自动运行

### ISSUE THREAD

**Issue by YorigamiPL** [MaaAssistantArknights/MaaAssistantArknights#354]
如题所述，个人怀疑是龙门币5的关卡UI位置变化的问题
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8499147/asst.log)
![image](https://user-images.githubusercontent.com/37739947/163658934-61853a05-dd37-4294-973b-ae80c4dc5bfc.png)
![image](https://user-images.githubusercontent.com/37739947/163658942-ce3a6a56-1fab-4e17-afea-6adfee472d8c.png)

**Comment by YorigamiPL** [comment]
补充：模拟器版本-蓝叠国际版
![image](https://user-images.githubusercontent.com/37739947/163658996-fdd93f28-6515-413e-b60f-f3a9cfba5d07.png)

**Comment by MistEO** [comment]
资源应该会自动更新（如果能连的上 github 的话）。不行的话请期待下次的版本吧~

**Comment by MistEO** [comment]
v3.1.3 fixed
