### ISSUE TITLE
生息演算如果进入的关卡里有剧情会卡住失败

### ISSUE THREAD

**Issue by 1522027679** [MaaAssistantArknights/MaaAssistantArknights#3541]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

v4.10.6-beta.3，生息演算如果进入的关卡里有剧情会卡住失败

### 日志文件

无

**Comment by df4d** [comment]
v4.10.6-beta.4 mumu 2.7.15.0 win10-21H2 B站服  也遇到该同样问题,而且还比较频繁
![微信图片_20230204181443](https://user-images.githubusercontent.com/88201634/216761521-7eb3c9b3-546e-4e60-a848-487f0124488b.png)

**Comment by cenfusheng** [comment]
对话问题因没有统一的识别点而难以修复，无计划。
