### ISSUE TITLE
新功能：外部Task加载和启动

### ISSUE THREAD

**Issue by Yanstory** [MaaAssistantArknights/MaaAssistantArknights#3542]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

刚才想写一个刷生息演算金条的Task，但是这个Task是需要一定条件才能启动和正常使用的（例如：需要玩家具备设施“冶铸台”，需要玩家能够在黑市买到水，需要玩家点亮铁条节点才能造等等），初次游玩的玩家并不能正常使用
目前MAA只能以**集成**任务代码，有什么方法能够载入和启动一些临时Task么（或者我可能没发现哪里有办法这么做），这样也比较方便开发调试<del>（绝对不是我VS有一点拖不动也不会弄依赖）</del>

### 有什么好的想法？

可以设置一个taskSandbox文件夹存放Task需要的东西（比如图像、数据源之类的）
似乎会有一些安全性问题？:thinking:

**Comment by WLLEGit** [comment]
修改StartUpBegin的next为你的入口task，会替换掉GUI上的”开始唤醒“。修改Reclamation@Begin的next，会替换生息演算。这两个任务启动的时候比较干净，没有多余操作，所以能替换。临时用一用没问题。

（刷金条的pr速来，我摆了写不动，看群里还有挺多人想要的

**Comment by Yanstory** [comment]
> （刷金条的pr速来，我摆了写不动，看群里还有挺多人想要的
基本想法是在原来的基础上：

1. 点击左上角区域
2. 点击“黑市”（OCR）
3. 点击开始行动
4. 左右滑屏图片检测联络员位置
5. 点击联络员
6. 点击启动技能
7. OCR识别选项
8. 退出关卡
9. 从左侧边栏进入控制中枢
10. 左滑找到赤金
11. 点击进入冶铸
12. 点击5次加号
13. 点击开始冶炼
14. 退出至地图
15. 重置缩放

即可回到原来的任务流程
当然因为这个过于特化所以实际应该整合不起来，我现在卡在4的滑屏这里

**Comment by Yanstory** [comment]
Remove module:infrast

**Comment by Yanstory** [comment]
Remove infrast
