### ISSUE TITLE
“基建换班”功能不被执行

### ISSUE THREAD

**Issue by 04linshi** [MaaAssistantArknights/MaaAssistantArknights#3548]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用的版本号是v4.10.6-beta.3。
多任务“Link Start”后“基建换班”任务不被执行，
单独“基建换班”运行时提示“出现未知错误”，并且点击“停止”停止不了

### 日志文件

2023-02-01 22:46
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10558178/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/106676717/216076212-843004ae-e5df-48b9-a48a-146dcfc03ee5.png)
![image](https://user-images.githubusercontent.com/106676717/216076688-905ed3a7-8ddf-460c-8db3-160069858330.png)

### 还有别的吗？

使用的模拟器是 蓝叠 5.4.100.1026 N64

**Comment by ABA2396** [comment]
设置里开了自定义换班但没选
![image](https://user-images.githubusercontent.com/99072975/216112749-0d208d50-cf8a-4702-93f4-02423d12f0e1.png)
