### ISSUE TITLE
生息演算因未知原因卡住后的兜底方案

### ISSUE THREAD

**Issue by SirCM** [MaaAssistantArknights/MaaAssistantArknights#3553]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

由于算法的特性（bug），在自动生息演算时总有可能由于未知原因而卡在某一步。

### 有什么好的想法？

可以让程序记录下天数。若在进行了若干操作后，演算天数仍没有增长（比如卡在了剧情或是某个选项），为了保证长时间的挂机不因该原因而中断，可直接退出本次演算，重开下一把。
好处是玩家刷材料不会因未知bug而中断，坏处大概是玩家无法准确知道哪里出的问题，无法准备上报，开发者也难以针对性debug。
或许可以在出现【重开】情况时把日志上传，如果不涉及隐私的话。

**Comment by WLLEGit** [comment]
beta4已经加入了出错重试机制，理论上不存在由于任务报错卡住的问题了。

如果仍有卡住可以反馈下bug。
