### ISSUE TITLE
朋友的MAA无法连接至模拟器

### ISSUE THREAD

**Issue by Aszlkm** [MaaAssistantArknights/MaaAssistantArknights#3555]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，朋友使用v4.10.3版本的MAA，在某次更新后无法使用，即使使用管理员权限也无法连接至模拟器

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10566570/asst.log)

因故无法提供更多信息，仅有asst.log文件

### 截图

![QQ图片20230202160103](https://user-images.githubusercontent.com/77436169/216267141-3fcfed43-c67d-412e-8ccf-b345c06377f3.png)
![QQ图片20230202160109](https://user-images.githubusercontent.com/77436169/216267153-cd145bbe-36c1-4441-a4be-00aeb3659133.png)

### 还有别的吗？

MuMu模拟器，win10系统，因故无法提供更多信息，仅有asst.log文件

**Comment by ntgmc** [comment]
这边建议加个用户群解决

**Comment by Aszlkm** [comment]
已向本人转达

**Comment by Aszlkm** [comment]
已向本人转达
