### ISSUE TITLE
能否为任务添加一个自动放弃/自动推迟/尝试排除问题的功能？

### ISSUE THREAD

**Issue by HS7097** [MaaAssistantArknights/MaaAssistantArknights#3557]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

Alas在调用MAA执行自动公开招募与剿灭时会出现一些错误
自动公开招募时若票/钱不够会直接卡住导致报错退出托管
剿灭是默认打当期的剿灭，但是有些时候没开代理指挥，MAA还是会去打，同样也会导致错误

### 有什么好的想法？

在自动公开招募中添加检查右上角弹窗的功能
若出现弹窗，自动向Alas反馈推迟任务
剿灭默认打最古早的龙门外环或者龙门市区，
这两个一般都是打过的~~绝大多数人应该都打了~~

**Comment by ChildeRolando** [comment]
是的，如果剿灭可以选图就好了，当期/往期(龙门)
