### ISSUE TITLE
希望可以增加开机自动启动MAA后, MAA自动隐藏到任务栏托盘

### ISSUE THREAD

**Issue by hifuclub** [MaaAssistantArknights/MaaAssistantArknights#3561]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前每次开机自动启动MAA后, 会弹出来MAA窗口,需要手动最小化.

希望增加启动之后不弹出MAA主界面,自动隐藏到任务栏托盘的选项.

**Comment by moomiji** [comment]
我的pr合并后，把这三项勾上开启。
![image](https://user-images.githubusercontent.com/35213527/230378135-b2aa772e-bbe1-4c7e-ae76-42520aa35e60.png)
