### ISSUE TITLE
仅使用即将过期的理智药

### ISSUE THREAD

**Issue by bigqiao** [MaaAssistantArknights/MaaAssistantArknights#3563]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

很多人平时理智药留着用，但是快过期的药应该可以帮吃了免得浪费。

### 有什么好的想法？

在吃理智药的界面识别剩余的时长，时长短于阈值就吃。

### 其他内容

![Screenshot_20230202-231157](https://user-images.githubusercontent.com/4958948/216363041-9202e3a3-0c51-45ec-bd8e-b5ac6c4f5b5b.png)

**Comment by Starry-Wind** [comment]
理智药的排序都是按保质期来排序的，快过期的理智药都会排在前面，只要你设置了吃理智药刷图都会优先用快过期的理智药。

**Comment by bigqiao** [comment]
意思就是就算没设置吃理智药，也可以将即将过期的理智药吃掉。

这个可以做独立选项。能使全自动挂机更加方便。

**Comment by ABA2396** [comment]
#3684 fixed
