### ISSUE TITLE
自动公招最大招募次数与实际招募次数不匹配

### ISSUE THREAD

**Issue by 666233j** [MaaAssistantArknights/MaaAssistantArknights#3564]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

填了70次，自动加急，实际只用了40多张

### 日志文件

招募完就关了
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10570726/asst.zip)

**Comment by Toby-Shi-cloud** [comment]
估计是 #7266 的原因（使用加急许可选项仅会尝试对第一格进行加急招募，但如果第一格的招募内容需要手动确认，MAA就不再会加急剩下三格）
