### ISSUE TITLE
刷理智关卡导航失败

### ISSUE THREAD

**Issue by zzz8307** [MaaAssistantArknights/MaaAssistantArknights#3565]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

之前提过一次故障相似的Issue，但是后面某次正式版更新之后就又无法导航了 #3052 

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10571081/asst.log)
故障出现时间点：
1. 2023/2/3 0:16:36
2. 2023/2/3 0:24:11
3. 2023/2/3 0:24:45
4. 2023/2/3 0:25:17

### 截图

![Screenshot_2023 02 03_00 22 32 152](https://user-images.githubusercontent.com/25875214/216382036-87733a63-40a7-41aa-9871-794227e23cd2.png)
![Screenshot_2023 02 03_00 25 43 338](https://user-images.githubusercontent.com/25875214/216382815-ebad3863-f770-47c1-9f27-9fffd7f65e7e.png)
![Screenshot_2023 02 03_00 25 47 949](https://user-images.githubusercontent.com/25875214/216382837-909e43a6-8096-4679-b624-fcd5731c9168.png)

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/216391269-e00a57ca-93c0-4262-b557-32264992f592.png)
按日志看是已经识别到了AP5并且点击了guanqia关卡，不知道为啥没点上

**Comment by zzz8307** [comment]
会不会是点太快了？或许可以增加点延迟或者加一个重试机制试一下
