### ISSUE TITLE
python 接口启动陷入死循环

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaAssistantArknights#3566]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

python 接口启动陷入死循环

### 日志文件

[error.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10573382/error.log)

**Comment by Shawnsdaddy** [comment]
貌似返回点击卡死。。可是不太清楚为什么

**Comment by Shawnsdaddy** [comment]
1080 P mumu和夜神都有同样问题。

**Comment by Shawnsdaddy** [comment]
多开core的情况只会有一个maa生效，其他instance会卡住点击失败

**Comment by Shawnsdaddy** [comment]
第一次启动3开运行良好，当任务完成定时再次启动的时候卡住

**Comment by HS7097** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2213#issue-1571210914
同样遇到了，但是我不太清楚咱们两个的状况是否一样
我是2C 4GB，1080p在跑

**Comment by Shawnsdaddy** [comment]
出现了新问题，自动刷关失败卡死，后续任务失败
[error.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11276430/error.log)
