### ISSUE TITLE
手机无法使用MAA内测版4.10.6-beta.4

### ISSUE THREAD

**Issue by Cheresting** [MaaAssistantArknights/MaaAssistantArknights#3569]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用数据线连接手机想用MAA刷日常，按照官网教程设置后连接不上手机

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10575568/asst.log)

### 截图

MAA报错
![216482672-2521df61-e534-4130-a3d8-c41975c4ec0b](https://user-images.githubusercontent.com/66453643/216513720-9aef759c-7353-4a37-89ce-52650e4852bd.png)
![216483045-9ca5765f-9f54-40a9-845a-beecded6bc44](https://user-images.githubusercontent.com/66453643/216513734-7c15e8b5-7a9e-44ff-b5c3-e70eb2accdae.png)
MAA设置
![216482707-3ef3b110-e6b6-4310-aaee-7a1fb86b1f76](https://user-images.githubusercontent.com/66453643/216513762-82a70583-f45c-4554-a168-787fcf84a4e4.png)
adb设置
![216483109-a2c87139-2f0d-40ca-883f-00206847aa2e](https://user-images.githubusercontent.com/66453643/216513793-c9b4a75e-83f4-4df8-a7a4-6d79aed1e1ac.png)

### 还有别的吗？

手机型号是小米9，adb是教程的链接下的，MAA是最新的内测版

**Comment by Modilay** [comment]
触控模式改成adb input应该就可以了

**Comment by Cheresting** [comment]
谢谢大佬！触控模式改成adb input之后可以正常使用了
