### ISSUE TITLE
生息演算功能在运行一段时间后速度变慢

### ISSUE THREAD

**Issue by SchwarzXia** [MaaAssistantArknights/MaaAssistantArknights#3571]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

生息演算功能在刚开始运行的时候，每次进图后立刻就会退出地图，但是在运行了一段时间后（具体多久不明），进入地图后不再立刻退出，而是等待约20秒后才会退出，点击退出确认按钮的延迟也有些许增大。其他菜单点击速度无变化。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10575756/asst.log)
问题发生在log最后一段时间
在log中可以看到有奇怪的ocr识别结果，不知道是否有关

### 还有别的吗？

模拟器为mumu国际版

**Comment by WLLEGit** [comment]
从log上看更像是在任务结算界面卡住了20s？
推测是网络不好导致点击确认退出后没有立刻黑屏，而是停留在了连结神经网络的界面上。

如果是这个bug那刚刚修了，如果确定是20s没有点退出键的话可以再详细地描述一下情况。

**Comment by SchwarzXia** [comment]
并不是结算页面，我看到的就是在打开图之后20s没有动作，然后才退出

我人在美国，所以确实时不时的会有网络连接不好的情况，可能是由于某次连接不好所以造成了之后每次打开图都会错误的等待？

**Comment by SchwarzXia** [comment]
最新版中暂时未发现该问题，closing
