### ISSUE TITLE
大概是任务优先级问题

### ISSUE THREAD

**Issue by WSMTBG** [MaaAssistantArknights/MaaAssistantArknights#3572]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

由于肉鸽和生息演算是无限循环的，在肉鸽/生息演算的时候如果存在定时任务（比如基建什么的）就会报错，昨天有一次但我没截图

### 有什么好的想法？

能不能加一个功能（？）到定时任务的时候直接停止当前正在运行的任务并识别屏幕内容，结算之后就转去定时任务

**Comment by ABA2396** [comment]
继续比较麻烦，我感觉直接重启游戏可能还比较好操作一点

**Comment by WSMTBG** [comment]
> 继续比较麻烦，我感觉直接重启游戏可能还比较好操作一点

也不是不行
