### ISSUE TITLE
仓库识别beta功能，遇到超过1万的数量，无法正确识别

### ISSUE THREAD

**Issue by waateer** [MaaAssistantArknights/MaaAssistantArknights#3574]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在仓库识别beta功能模块中，本人的基础作战记录显示为1.6万，但是识别出来的结果为1

识别对象：![image](https://user-images.githubusercontent.com/123763483/216564202-12acffd7-4b17-4db7-956d-79f227a5f4da.png)
识别结果：![image](https://user-images.githubusercontent.com/123763483/216564456-53f418cb-bde7-4c6d-939e-cc921905effd.png)

### 有什么好的想法？

应该是没考虑1万以上数量的情况，加上去应该就能解决了。
如果要严谨一点的话，就加上一个，每当识别到数量超过1万数量的材料时，就点进去，然后识别其具体数量的操作。

**Comment by Air111** [comment]
这个问题仍然存在（4.15.0）
