### ISSUE TITLE
无法加载软件，提示缺失DLL

### ISSUE THREAD

**Issue by acaqc** [MaaAssistantArknights/MaaAssistantArknights#3576]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

系统为WIN11家庭版，无法打开MAA，显示错误内容为“无法加载 DLL“MaaCore.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。”
详细信息
  在 MaaWpfGui.VersionUpdateViewModel.AsstGetVersion()
   在 MaaWpfGui.VersionUpdateViewModel..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.RootViewModel.CheckAndUpdateNow()
   在 MaaWpfGui.RootViewModel.OnViewLoaded()
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

系统升级前为WIN10专业版，无上述问题

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10579788/gui.log)

### 截图

![image](https://user-images.githubusercontent.com/124373772/216629408-6a36c7da-3dd2-4532-9a4d-35b44871fb72.png)

**Comment by ntgmc** [comment]
![image](https://user-images.githubusercontent.com/74061867/216630383-ed7664a8-e332-49f0-b355-a9e3f14f0aca.png)
各个群文件都有

**Comment by yyn19951228** [comment]
同遇到这个问题，请问解决了么
