### ISSUE TITLE
希望可以添加一个“只吃快过期的药”的选择

### ISSUE THREAD

**Issue by HS7097** [MaaAssistantArknights/MaaAssistantArknights#3581]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

比如只吃剩余1天的药以方便囤理智用于做其他的

### 有什么好的想法？

比如只吃剩余1天的药以方便囤理智用于做其他的

**Comment by ABA2396** [comment]
#3684 fixed
