### ISSUE TITLE
基建换班功能设置无效

### ISSUE THREAD

**Issue by AndyBlocker** [MaaAssistantArknights/MaaAssistantArknights#3582]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述
MAA版本：MAA-v4.10.6-beta.4-macos-arm64
在设置-基建设置中取消勾选了控制中枢和发电站两项，但基建换班时仍然会给发电站和控制中枢换班

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10593850/asst.bak.log)

9:58左右开始基建换班

### 截图

<img width="894" alt="image" src="https://user-images.githubusercontent.com/13509530/216744170-c591b162-2db5-43dd-847d-123f4ce97507.png">
已取消勾选两项，但换班

### 还有别的吗？

设备：MacBookPro 16, M1 Pro, 16G
系统：MacOS 13.2

这个版本加入的生息演算功能在界面上无法选中，也不知道如何触发自动生息演算功能，但有时会自动在所有勾选任务完成后进行生息演算挂机（log中10:14）

生息演算和肉鸽挂机一段时间后都会出现ScreencapFailed的问题，在log的末尾可以看到

主界面的每日轮换提示不会变更，一直保持在周日且显示不完整

2.12编辑：
肉鸽会出现放一个人后一直暂停然后有概率程序退出报错的问题，4.10.7现在稳定进入生息演算，但是界面中仍然没有勾选的地方

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10715276/asst.bak.log)

**Comment by ABA2396** [comment]
cc @hguandl

**Comment by Olld47** [comment]
这几个问题我这里也可以复现，同样是m1mac

**Comment by ABA2396** [comment]
现在还有问题吗？应该已经修了

**Comment by AndyBlocker** [comment]
已修复，希望mac端的基建自定义功能能快一些上线，现在会自动往制造站里放几个相互清空加成的干员😂
