### ISSUE TITLE
刷理智的时候如果“当前/上次”的关卡没有解锁代理指挥，或者遇到了非三星作战的情况，希望系统能够直接结束刷理智的任务。

### ISSUE THREAD

**Issue by Rx1351177684** [MaaAssistantArknights/MaaAssistantArknights#3586]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10605932/gui.log)
文件末尾

**Comment by ABA2396** [comment]
CE-6没代理会去打CE-5，LS同理，~其他关卡选择是自己选的这个就不管了~
我记得代理失败会放弃，多次失败直接会不打的吧 @MistEO
