### ISSUE TITLE
公招出现多个4星tag时可否都选上

### ISSUE THREAD

**Issue by miku1958** [MaaAssistantArknights/MaaAssistantArknights#3589]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我已经看到好几次出现了多个4星tag，比如快速复活/支援/爆发，结果MAA只勾选了一个，然后就被划掉了

### 有什么好的想法？

4星tag都选上，如果存在2个绑定的tag则优先级降低，以尽量多的4星为目的来算，穷举一下其实也就以下这几种情况：
3个四星tag = 3
2个四星tag = 2
1个四星tag+2个绑定四星tag = 2
1个四星tag = 1
2个绑定四星tag = 1

**Comment by ntgmc** [comment]
Duplicate of #92
