### ISSUE TITLE
求给“生息演算”加个刷钱功能

### ISSUE THREAD

**Issue by xiulu0** [MaaAssistantArknights/MaaAssistantArknights#3596]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

求给“生息演算”加个刷钱功能，就是铁和水合成合金的功能，建基地需要花的太多了，鄙人又懒🐕

**Comment by CottonCandy2004** [comment]
Duplicate of #3532

**Comment by cenfusheng** [comment]
隐藏功能开启方式→ #3763
