### ISSUE TITLE
v4.10.6-beta.4版本无法自动更新蓝叠hype-v的端口号

### ISSUE THREAD

**Issue by wycgi520** [MaaAssistantArknights/MaaAssistantArknights#3597]
### 说说你遇到的问题？

我已经在gui.json配置了路径:
![image](https://user-images.githubusercontent.com/45585284/216770675-c4854dcc-379f-4452-96fb-27791e53d495.png)

但连接地址还是维持默认的5555, 需要手动配置:
![image](https://user-images.githubusercontent.com/45585284/216770714-63998000-84e5-4c0b-beac-44fba7c80c44.png)

**Comment by konataks** [comment]
是否改了这个
`  "Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port", `

**Comment by Ravenightwing** [comment]
> 是否改了这个 ` "Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port",`

没有更改，版本v4.10.5，已经在gui.json中更改过了；但是仍然无法连接

**Comment by FSPaul2498** [comment]
同蓝叠Hyper-V，正在使用v4.10.6-beta.5，可以正常识别到端口号，尝试升级到beta5呢？
相关环境信息供参考：
Windows 11 专业版 22H2，版本号22621.1105，Hyper-V等相关功能均开启
蓝叠5 Hyper-V，版本号`5.9.300.1014 N64`，默认安装位置，使用管理员身份运行（否则我这里会报错）
MAA v4.10.6-beta.5，仅修改`gui.json`添加 `"Bluestacks.Config.Path": "C:\\ProgramData\\BlueStacks_nxt\\bluestacks.conf" `这一条目

**Comment by wycgi520** [comment]
> "Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port",

确实加这个可以

**Comment by wycgi520** [comment]
需要再加这个配置"Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port",

**Comment by wycgi520** [comment]
需要再加这个配置"Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port",
