### ISSUE TITLE
[API][Maa-HTTP]编译jar出现报错

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#3600]
### 说说你遇到的问题？

1. 为什么会遇到问题：不太懂java，看到有http接口符合需求，故尝试使用
2. 做了哪些操作：
  - 下载了MaaAssistantArknights/src/Java/ 并放入了本地 ...\MAA-xxx.xxx\Java-HTTP\ 文件夹
  - 按照文档说明使用.\gradlew.bat jar试图编译jar包
3. 出现的问题:
  - 如图：
  - ![截图_20230205103336](https://user-images.githubusercontent.com/53437291/216798542-0435bf9a-ca51-4f91-a822-8d28e3e2b00d.png)
故开issue请教大佬如何使用此功能

**Comment by MistEO** [comment]
@BTreeNewBee 龟龟快来看看！

**Comment by gylove1994** [comment]
@KJH-x 我也遇到了相同的问题，问题似乎是由于缺少`gradle wrapper`文件所导致的。

可以先使用我编译好的jar包进行开发，随后我将尝试提交一个pr试图修复这个问题。

[Maa-HTTP-0.0.1.jar.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12705264/Maa-HTTP-0.0.1.jar.zip)

**Comment by Constrat** [comment]
I'm guessing this can be closed @KJH-x

**Comment by KJH-x** [comment]
虽然我还没有时间测试，但看起来没问题，后续有问题再重开。

Although I haven't had time to test this recently, it looks great. I will reopen this Issue if necessary
