### ISSUE TITLE
生息演算进行时卡在了曼提柯杀手的对话界面

### ISSUE THREAD

**Issue by heixiaoou** [MaaAssistantArknights/MaaAssistantArknights#3601]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用了maa v.4.10.6bata5 版本中的生息演算代理功能 但是总是卡在曼提柯杀手的对话界面，必须要手动选择跳过，否则maa一直显示截图失败，如反复出现请尝试重启或更换模拟器，跳过后一切功能正常，知道下一次遇到曼提柯杀手（不是黑市的那个，是在关卡里的曼提柯杀手）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10610144/asst.log)
卡住的开始时间大概在2023.2.5 10:57左右 并持续到11:02无行动，过了一会我手动停止了

### 截图

![image](https://user-images.githubusercontent.com/106435645/216799670-ea8fa704-76c5-4ead-b3a5-2b2178c0c98e.png)
卡在这个界面

### 还有别的吗？

模拟器：雷电模拟器5
操作系统：Microsoft Windows 10 64位  22H2
CPU型号：Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
主板：LENOVO_20KNA003CD
总内存：15.9 GB
可用内存：6.7 GB
显卡型号：Intel(R) UHD Graphics 620 (20210624)
显卡型号：Radeon (TM) RX 550 (20220125)
OpenGL：4.6.14802 Compatibility Profile Context 21.40.30 30.0.14030.0
IE版本：11.0
模拟器版本：5.0.38(32)
模拟器路径：F:\leidian\LDPlayer4
日志路径：C:\Users\22786\AppData\Roaming\leidian\log
vt:开启
运行参数：CPU(4核) 内存：(6144M) 正在运行(1) 高速(1)
分辨率：1280x720 dpi 240 fps 60
总大小32 G，剩余15 G

**Comment by WLLEGit** [comment]
这个暂时没精力解决，因为不同的剧情对话不一样，也没有统一的跳过的方法
