### ISSUE TITLE
生息演算模式中出现“重复点击 ‘开始演算’ ”的bug

### ISSUE THREAD

**Issue by Aszlkm** [MaaAssistantArknights/MaaAssistantArknights#3607]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用MAA自动刷演算的时候，出现多次点击“开始演算”的问题，重启后该bug仍会出现，暂不明确对正常运行及刷去效率是否有较大影响。
同样，前两天刷肉鸽的时候同样出现了这个问题，但当时未保存log或截图。

### 日志文件

bug出现在16：45左右
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10610554/asst.log)

### 截图

bug出现在16：45左右
![01](https://user-images.githubusercontent.com/77436169/216810523-60d2921c-fd87-4c8e-a708-2e4b24f42ba3.jpg)

### 还有别的吗？

win10
Mumu模拟器

**Comment by WLLEGit** [comment]
开始演算就是有多次点击，因为有的时候出现了这个按钮但按了没反应。

**Comment by WLLEGit** [comment]
开始演算就是有多次点击的，因为有的时候出现了这个按钮但按了没反应，或者界面跳转慢。按一次就会弹一次log是正常现象，反正有了掉落统计了，也不用太关心具体的开始次数。

最近没时间调细枝末节的小问题，所以这个GUI 的log有点重复凑合用吧，
