### ISSUE TITLE
基建换班时会客室见行者已经0心情还是选中继续加班了 最后宿舍成功休息但会客室少人 版本3.1.2

### ISSUE THREAD

**Issue by DavidHhhh** [MaaAssistantArknights/MaaAssistantArknights#361]
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8512032/asst.log)

**Comment by DavidHhhh** [comment]
补充 刷理智lmb刷取有问题 可能跟新版本lmb本ce-5位置调了有关系

**Comment by MistEO** [comment]
见行者是谁_(:з」∠)_

**Comment by zzyyyl** [comment]
[见行者](https://prts.wiki/w/%E8%A7%81%E8%A1%8C%E8%80%85#.E5.90.8E.E5.8B.A4.E6.8A.80.E8.83.BD)

~（你真的玩明日方舟？）~

**Comment by MistEO** [comment]
没搞懂为啥，加了点日志，3.2.2 或者之后的版本再遇到的话再帮忙发一下吧_(:з」∠)_

**Comment by MistEO** [comment]
ffb3842036f3dc1a200829edf9ffecfec595f177 fixed
