### ISSUE TITLE
希望在肉鸽的左侧日志里添加更详细的信息，比如这次的得分和挂机开始累计的得分

### ISSUE THREAD

**Issue by daoistplus** [MaaAssistantArknights/MaaAssistantArknights#3610]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by MistEO** [comment]
得分有啥用呀，感觉就图一乐 _(:з」∠)_

**Comment by daoistplus** [comment]
> 得分有啥用呀，感觉就图一乐 _(:з」∠)_

言之有理，当时想的是不用退出去就能看到现在得分情况怎么样了
