### ISSUE TITLE
MAA报错截图失败

### ISSUE THREAD

**Issue by Olld47** [MaaAssistantArknights/MaaAssistantArknights#3615]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

mac版MAA，肉鸽挂机一段时间后，MAA报错截图失败，mac系统系统自带截图也不能用。关闭MAA后恢复正常
MAA版本v4.10.6-beta4

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10659682/asst.bak.log)

### 截图

debug里面的rougelike文件夹截图
[Archive.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10659712/Archive.zip)
系统截图无效，手机拍的
![2023-02-06 13:32:36](https://user-images.githubusercontent.com/22239747/216891617-da9ae948-9337-4452-8144-d77ca68eca82.jpeg)

### 还有别的吗？

![Screen Shot 2023-02-06 at 12 25 30](https://user-images.githubusercontent.com/22239747/216883452-46c6492e-2faf-4f2d-a09d-9f439fbcfe65.png)
模拟器：avd
系统：macos 12.6.3 
配置：m1max

**Comment by Leslie-ClClCl** [comment]
一样的问题，求解决～～～

**Comment by HerrCai0907** [comment]
可能是由于僵尸进程过多导致的, #3623修复了这个问题, 可以试一下[v4.10.7](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.10.7-beta.1)

**Comment by HerrCai0907** [comment]
新版本跑了四个多小时，bug没有复现，应该是修复了。

**Comment by Olld47** [comment]
> 新版本跑了四个多小时，bug没有复现，应该是修复了。

我跑了一下午，没有问题
