### ISSUE TITLE
自动剿灭完成后无法接着运行后续的任务

### ISSUE THREAD

**Issue by MilkWind** [MaaAssistantArknights/MaaAssistantArknights#3617]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如标题，似乎有个界面不再MAA的识别范围内，这导致MAA在从剿灭退出来时会因这个不在识别范围的图片而卡住，后续任务无法执行，直接显示执行失败。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10660386/asst.log)

时间点大概在2023/2/6 14:36:00 左右

### 截图

![MuMu20230206145134](https://user-images.githubusercontent.com/115831439/216902771-8e88ef4c-c669-4495-9dd8-3d759d5818f6.png)

让MAA卡住的页面截图

### 还有别的吗？

MuMu模拟器
![image](https://user-images.githubusercontent.com/115831439/216903387-0ce0d6e2-a217-44f5-ba65-349064d7fbc9.png)

**Comment by ChildeRolando** [comment]
一样的问题，不过是python调用，导致没法用MAA打剿(?)
