### ISSUE TITLE
增加公招功能：遇到4星tags自动使用加急许可，以及选择多个4星tag减少被划概率

### ISSUE THREAD

**Issue by Cdkgfp** [MaaAssistantArknights/MaaAssistantArknights#3618]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

加急许可不用越积越多...

**Comment by ntgmc** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/92
