### ISSUE TITLE
任务点击位置错误

### ISSUE THREAD

**Issue by qaz1qazlol2** [MaaAssistantArknights/MaaAssistantArknights#3619]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

完成上一步操作后（例如自动公招，刷理智）执行下一步操作无反应，等一会儿后任务出错跳转到下一个任务，仍然没反应

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10661318/asst.log)

### 截图

![SharedScreenshot](https://user-images.githubusercontent.com/115929847/216931294-626770c7-f530-4b3d-86b1-8f9a4278e324.jpg)

### 还有别的吗？

模拟器：Aliyun Cloudplone
System: Android 9 原生
配置：4C8G32GB硬盘
建议的修复方法：每一次完成任务后使用左上角的选项直接回到主界面之后进行下一步操作

**Comment by qaz1qazlol2** [comment]
> 你的分辨率太低了，导致了返回按钮被挡住了，如果不开指针模式这个分辨率是可以的
把分辨率改成1020x1980会修复这个问题吗
顺便一提，我如果不使用兼容模式的触屏会出现点歪的现象

**Comment by ABA2396** [comment]
一般来说调高分辨率就挡不住了，但是最好的办法还是把指针模式关了。
点歪是什么意思，是指点不到要点的东西吗

**Comment by qaz1qazlol2** [comment]
> 一般来说调高分辨率就挡不住了，但是最好的办法还是把指针模式关了。 点歪是什么意思，是指点不到要点的东西吗

对，就比如点开始唤醒结果点到正右边的空白区域了
