### ISSUE TITLE
检查更新添加立即更新按钮

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#3624]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

自动OTA下载更新包只有在每次启动自动检查更新时才会进行

### 有什么好的想法？

检查到更新版本后在通知处额外添加一个`立即更新`按钮 或弹出对话框

**Comment by Rbqwow** [comment]
Remove labels

**Comment by Rbqwow** [comment]
Add GUI

**Comment by MistEO** [comment]
设置里有 检查更新 的按钮呀

**Comment by ABA2396** [comment]
> 设置里有 检查更新 的按钮呀

那玩意也就是检查更新，你不开自动下载检查了也不会更新
