### ISSUE TITLE
关卡选择-剿灭模式识别出错

### ISSUE THREAD

**Issue by lormalduss** [MaaAssistantArknights/MaaAssistantArknights#3626]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

 当[关卡选择]设置为[剿灭模式]，同时本周剿灭作战任务完成（即剿灭不显示在游戏内关卡选择页面的肉鸽上方）时，[刷理智]任务会直接报错，而非执行[备选]任务。类似于     #2943 

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10668853/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/51875656/217076520-b2dae596-83a5-4da4-b9cb-d37d3f6b9654.png)

**Comment by ABA2396** [comment]
本来是不推荐在备选里放剿灭
现在加了个如果选的是剿灭，会把后面开放的关卡也放到任务里，但是 使用源石数量 刷取次数 指定掉落 和 指定掉落数量设置将无效
