### ISSUE TITLE
关于剿灭的一些bug收集和优化建议

### ISSUE THREAD

**Issue by ChildeRolando** [MaaAssistantArknights/MaaAssistantArknights#3627]
### 在提问之前...

- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

 - 2.在每周剿灭已经打完但是仍有未400杀的剿灭时，导航面板仍有剿灭图标，若此时用户选择执行剿灭，就会在未400杀的地图中浪费体力和时间
![屏幕截图 2023-02-06 214424](https://user-images.githubusercontent.com/43607124/217082710-cb834f77-87fb-4b08-aede-568af52b6c70.png)

### 有什么好的想法？

1.添加对该页面的识别
2.添加对已四百杀但模拟战未打满图标和未打满四百杀图标的识别和区分
3.添加对不同剿灭地图的导航

**Comment by HydrogenDeuterium** [comment]
其实这个bug 已经有人提交过了：
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3617

**Comment by ChildeRolando** [comment]
> 其实这个bug 已经有人提交过了： #3617

第一个bug一样，后面两个bug和那个不一样
