### ISSUE TITLE
手动输入关卡，到关卡页面就不动了

### ISSUE THREAD

**Issue by winterstay** [MaaAssistantArknights/MaaAssistantArknights#3628]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

手动输入关卡名，能自动找到关卡，但不执行，再关卡页面没有动静

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10670915/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/73685462/217130991-c8465cf8-b250-491f-8150-a1be27bee9d3.png)

### 还有别的吗？

夜神，win11

**Comment by ABA2396** [comment]
S识别成s了）
