### ISSUE TITLE
无法连接手机

### ISSUE THREAD

**Issue by Misaka19327** [MaaAssistantArknights/MaaAssistantArknights#3629]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用的adb如下：
![图片](https://user-images.githubusercontent.com/115413714/217132720-85be221b-5a7a-49d6-b465-2bbd4fd9b59b.png)
然后手机上也显示已经通过无线调试连接了：
![图片](https://user-images.githubusercontent.com/115413714/217132877-ae32183a-6cfe-4907-bedc-4dc98235ab82.png)
仍然显示无法连接 或者说分辨率不对：
![图片](https://user-images.githubusercontent.com/115413714/217132952-e853816c-2740-4199-a32b-13ca502a966e.png)
![图片](https://user-images.githubusercontent.com/115413714/217132964-41a5aea5-0407-44ea-8346-83042a62ecfb.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10670992/asst.log)

### 还有别的吗？

电脑是Windows11 启动MAA时已经以管理员权限启动了 手机是红米k40

**Comment by fatinghenji** [comment]
遇到相似问题，补充下额外的操作：
- 使用镧·工具箱更改了手机的分辨率，更改为1080*1920
- 重新链接，报错如下：
![image](https://user-images.githubusercontent.com/37131177/217529379-02ebbfac-753e-4103-b675-c321c7e34d91.png)

**Comment by HydrogenDeuterium** [comment]
maa 用的 adb 和终端里是同一个吗？

**Comment by Pommissarzhu** [comment]
遇到过类似问题，可以尝试将**连接配置**更改为``通用模式``，并将**触控模式**更改为``Adb Input（兼容模式）``后再尝试。

手机可能不兼容Minitouch？虽然Minitouch速度很快

顺带一提官方文档里没有提到更改触控模式为Adb Input这件事，希望后续能加上
![QQ截图20230209000819](https://user-images.githubusercontent.com/51729975/217586277-138eea7e-eef8-4e5d-9731-23effd05831b.png)

**Comment by fatinghenji** [comment]
> 遇到过类似问题，可以尝试将**连接配置**更改为`通用模式`，并将**触控模式**更改为`Adb Input（兼容模式）`后再尝试。
> 
> 手机可能不兼容Minitouch？虽然Minitouch速度很快
> 
> 顺带一提官方文档里没有提到更改触控模式为Adb Input这件事，希望后续能加上
> 
> 补一个官方文档的链接
> 
> [传送门](https://maa.plus/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.html#%E2%9A%99%EF%B8%8F-%E6%89%8B%E6%9C%BA%E3%80%81%E5%B9%B3%E6%9D%BF%E7%AD%89%E9%9D%9E-16-9-%E5%88%86%E8%BE%A8%E7%8E%87%E8%AE%BE%E5%A4%87)
> 
> ![QQ截图20230209000819](https://user-images.githubusercontent.com/51729975/217586277-138eea7e-eef8-4e5d-9731-23effd05831b.png)

按照上面的说法更改设置后，出现新报错
![image](https://user-images.githubusercontent.com/37131177/217589581-3aa2643e-06a0-472e-8345-8a07e8cad8af.png)

**Comment by fatinghenji** [comment]
我的问题解决了，MIUI需要在开发者里面再开一个安全调试。

**Comment by Misaka19327** [comment]
> maa 用的 adb 和终端里是同一个吗？
是同一个
![图片](https://user-images.githubusercontent.com/115413714/217678515-c85d4c8e-8515-4479-b38d-ade34223dc4e.png)

**Comment by Misaka19327** [comment]
解决了 应该是这个minitouch的问题 多谢 希望开发者在文档里加一句（

**Comment by ArkURL** [comment]
感谢！之前按照文档将分辨率设置成`720x1080`无法正常进行任务，看了下上面的回答将分辨率调整成`1080x1920`后可以正常运行任务了。终于可以手机挂机生稀盐酸了，感谢！

**Comment by ArkURL** [comment]
> 

回过头又看了眼文档，发现是要将分辨率调成`720x1280`，草，错怪文档了。😂
