### ISSUE TITLE
自动战斗技能释放异常

### ISSUE THREAD

**Issue by az09px** [MaaAssistantArknights/MaaAssistantArknights#3630]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗干员释放技能异常，打开触摸反馈后发现脚本点击位置与技能实际位置严重偏移

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10671265/asst.log)

### 截图

[屏幕截图_20230207_104101.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10671264/_20230207_104101.zip)

### 还有别的吗？

[QQ录屏20230207103313(1).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10671268/QQ.20230207103313.1.zip)
[MAACopilot_CE-6速刷1.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10671329/MAACopilot_CE-6.1.zip)

**Comment by MistEO** [comment]
fixed
