### ISSUE TITLE
关于自定义排班

### ISSUE THREAD

**Issue by WSMTBG** [MaaAssistantArknights/MaaAssistantArknights#3631]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

懒得换班但自定义排班哪怕是一天两换的也有点浪费了，能否读取自定义排班文件，然后根据心情值（比如到10%以下）+自定义配置换人，比如贸易站能德拉10%以下了，自定义配置写的是银崖孑就换银崖孑这样

### 有什么好的想法？

根据心情值（比如到10%以下）+自定义配置换班

**Comment by WSMTBG** [comment]
> 你这个需求太复杂了，而且maa可以定时执行，不懂为什么会“懒得换班但自定义排班哪怕是一天两换的也有点浪费了”？

我两天一换..但我也懒得去换...

**Comment by HydrogenDeuterium** [comment]
> maa可以设定时间自动执行换班啊

但是不能保证到了那个时间有运行脚本的条件……
我现在一直就不敢用maa自动换都是手换（

**Comment by Shawnsdaddy** [comment]
> > maa可以设定时间自动执行换班啊
> 
> 但是不能保证到了那个时间有运行脚本的条件…… 我现在一直就不敢用maa自动换都是手换（

那就手动换呗，电脑都不开想让Maa换，实在有点强人所难了
Maa基建可以设置心情阈值的好像

**Comment by WSMTBG** [comment]
> > > maa可以设定时间自动执行换班啊
> > 
> > 
> > 但是不能保证到了那个时间有运行脚本的条件…… 我现在一直就不敢用maa自动换都是手换（
> 
> 那就手动换呗，电脑都不开想让Maa换，实在有点强人所难了 Maa基建可以设置心情阈值的好像

如果开了自定义好像就不管心情阈值了
