### ISSUE TITLE
基建换班无人机没有全部用来加速

### ISSUE THREAD

**Issue by YuhangTom** [MaaAssistantArknights/MaaAssistantArknights#3632]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建换班无人机没有全部用来加速，换完还有无人机剩余

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10671954/asst.log)
02-06 23:47:35 ~ 02-06 23:54:41

### 截图

![Screenshot_2023 02 06_23 58 20 342](https://user-images.githubusercontent.com/45880737/217161331-34d30d7d-e646-40be-8ba7-0ccb853a69cd.png)
换班后模拟器截图

### 还有别的吗？

BlueStacks App Player 5.10.150.1016 N64
Win11 10.0.22621 Build 22621
MAA v4.10.6-rc.1

**Comment by ABA2396** [comment]
是不是加速了贸易站但是没赤金了

**Comment by YuhangTom** [comment]
不是哦 有好多赤金 和MAA基建设置一并附上
![Screenshot_2023 02 07_02 30 24 321](https://user-images.githubusercontent.com/45880737/217192367-6111b053-1c8b-4486-9665-335069a73a8e.png)
<img width="392" alt="image" src="https://user-images.githubusercontent.com/45880737/217192479-6d6b2a35-bde1-46d2-b7d0-63947925d472.png">

**Comment by YuhangTom** [comment]
刚刚梅开二度了
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10673102/asst.log)
02-07 02:33:00 ~ 02-07 02:43:48

![Screenshot_2023 02 07_02 44 20 387](https://user-images.githubusercontent.com/45880737/217195580-856b43a1-9160-4167-b994-74af9fcd0da4.png)
![Screenshot_2023 02 07_02 45 42 037](https://user-images.githubusercontent.com/45880737/217195650-f9f87f44-3f72-4c92-b9e7-e05b3d7acc89.png)

**Comment by ABA2396** [comment]
cc @MistEO

**Comment by YuhangTom** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10677400/asst.log)
02-07 10:28:31 ~ 02-07 10:34:54
GDrive补个[视频](https://drive.google.com/file/d/1-4muLtHx_TIRjKzIQsl8Hsqk7kZTtFaF/view?usp=sharing)

**Comment by sunyink** [comment]
对，附议。我也发现这个问题。自定义配置文件，编成时候测试没问题，无人机字段一直没有更改过；这段时间经常200个溢出需要人工加速。

**Comment by bell1sperennis** [comment]
我也发现了相似的问题，基建配置文件内如果index为1的话可以正常使用无人机，如果改4的话则直接跳过这一步进行换班了。`"drones":{"room": "manufacture","index": 1},`

**Comment by gnaw6403400** [comment]
这个问题还没解决，附上跑基建的视频和log

https://github.com/user-attachments/assets/fbc1fc95-aacf-4a52-86a8-5a62244f0a00

[gui.log](https://github.com/user-attachments/files/16327242/gui.log)
[asst.log](https://github.com/user-attachments/files/16327243/asst.log)
