### ISSUE TITLE
艾丽妮基建 可选 是否手动放入宿舍

### ISSUE THREAD

**Issue by soulmisty1** [MaaAssistantArknights/MaaAssistantArknights#3641]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

艾丽妮专精技能时需要待在训练室不出来，但是识别体力的时候MAA有时候会自动拉她去休息，导致艾丽妮基建技能失效

### 有什么好的想法？

建议添加类似 肥鸭/无人机加速 类似的按钮，设置 **是否自动让艾丽妮休息**
例如勾上的时候在宿舍换低心情的干员休息时候无视艾丽妮

### 其他内容

不清楚该反馈给 一图流还是MAA，但是一图流好像没有意见提交的入口，只能提交在这了

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/217535029-d9dfd102-00d1-477c-a1b8-58dc486c670f.png)

**Comment by Diaosi1111** [comment]
该项设置表意不清，并且应该默认开启吧
