### ISSUE TITLE
自动肉鸽时出现卡顿

### ISSUE THREAD

**Issue by LET-max** [MaaAssistantArknights/MaaAssistantArknights#3642]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动肉鸽在第一次探索时可以正常探索但过了几关之后就会出现轻微卡顿，在第二次以上的探索时卡顿将非常明显（甚至会影响至操作系统）并导致MAA无法正确放置干员探索失败。正常刷理智时则无此问题。卡顿只有在关闭模拟器与MAA后重启软件才能恢复正常，但是继续自动肉鸽将会复现该问题。已经尝试了重新下载MAA但并未解决，模拟器配置调整后也未解决卡顿问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10684886/asst.log)
时间点大概是已经结束第一次探索并开启第二次探索时，2023-02-08 18:59。

### 还有别的吗？

使用蓝叠模拟器国际版，操作系统为WIN11 22H2，配置是R5 3600+16G+RX6700XT，模拟器帧率为20帧，使用4核心与4G内存（之前使用2核2G内存是可以随便挂自动肉鸽的）

**Comment by z2690108** [comment]
我也会出现这个问题，也是au。不过我是核显 5800G。lz解决了吗
