### ISSUE TITLE
4.10.7 连接不上

### ISSUE THREAD

**Issue by WSMTBG** [MaaAssistantArknights/MaaAssistantArknights#3644]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

4.10.7 连接不上蓝叠模拟器（pie64），重启电脑后提示【出现未知错误】

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10686159/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10686161/gui.log)

**Comment by Black1312** [comment]
此问题在最新公测版应已被修复，如正常使用请close issue，如有异常请说明问题
