### ISSUE TITLE
MAA首次使用蓝叠Hyper-V模式，非管理员启动MAA无法正确切换模式

### ISSUE THREAD

**Issue by FSPaul2498** [MaaAssistantArknights/MaaAssistantArknights#3646]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，MAA 首次使用蓝叠 Hyper-V 模式（在 `gui.json` 中加入对应条目），非管理员启动 MAA ，虽然能够正确获取蓝叠 Hyper-V 端口，但仍然为`通用模式`，导致无法连接蓝叠 Hyper-V ，报告`检测模拟器出错请使用管理员权限打开本软件或手动设置连接`，需要改用管理员权限启动 MAA 一次后正常，再用非管理员启动 MAA 同样正常。
经测试，MAA v4.10.5 和 v4.10.7 均存在此问题。

具体复现步骤：
1，解压 `MAA-v4.10.7-win-x64.zip` 得到全新的 MAA 副本；
2，直接启动 MAA （非管理员），等待其生成 `gui.json` 后关闭；
3，修改 `gui.json` ，加入 `Bluestacks.Config.Path": "C:\\ProgramData\\BlueStacks_nxt\\bluestacks.conf` 条目；
4，直接启动 MAA （非管理员），标题显示能够正确获取蓝叠 Hyper-V 端口，但仍然为`通用模式`，点击 `Link Start1` ，报错`检测模拟器出错请使用管理员权限打开本软件或手动设置连接`两次；
5，关闭 MAA 后，重复第4步，问题持续复现；
6，关闭 MAA 后，改为使用管理员启动 MAA ，此时标题显示能够正确获取蓝叠 Hyper-V 端口，且正确切换到`蓝叠模拟器`模式，点击 `Link Start!` 后工作正常；
7，关闭 MAA 后，改为直接启动 MAA （非管理员），此时标题显示能够正确获取蓝叠Hyper-V端口，且正确使用`蓝叠模拟器`模式，点击 `Link Start!` 后工作正常。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10688131/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10688132/gui.log)

### 截图

![4 10 7首次非管理员无法连接](https://user-images.githubusercontent.com/35190475/217601252-44399d1e-e29f-4e6b-b0c1-5d8a8a63dab4.png)
![4 10 7管理员正常连接](https://user-images.githubusercontent.com/35190475/217601274-4bebd16d-9934-4fdc-9de3-f10fc2faab21.png)

### 还有别的吗？

Windows 11 专业版 22H2，版本号22621.1105，Hyper-V等相关功能均开启
蓝叠5 Hyper-V，版本号5.9.300.1014 N64，默认安装位置，使用管理员身份运行（否则无法启动蓝叠）
MAA v4.10.7，仅修改gui.json添加 "Bluestacks.Config.Path": "C:\\ProgramData\\BlueStacks_nxt\\bluestacks.conf" 这一条目

**Comment by FSPaul2498** [comment]
此外，在2月5日提交的[PR 文档更新#3605](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/3605)中，我也提到了类似的问题，但当时并没有经过详细测试，于是在未能成功复现的情况下（因为我下载的历史版本MAA已经被我用管理员权限执行过，故未能复现）删去了对应的文档更新条目。
今日更新4.10.7后，发现此问题复现，故深入尝试摸清复现步骤并提交此issue，辛苦开发团队及时排查修复，或对文档进行进一步的补充更新。

**Comment by MistEO** [comment]
应该是 GUI 的 bug，没走到 core 这层来
