### ISSUE TITLE
打开网易UU加速器后模拟器断连

### ISSUE THREAD

**Issue by Mashiro173** [MaaAssistantArknights/MaaAssistantArknights#3648]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题 MAA挂机时打开加速器后工具断开与模拟器的连接 提示连接失败 请检查连接设置或尝试重启电脑
日志文件已上传 大约在最近几日晚8点左右或以后 打开加速器时断开
重启过后可以解决
是否是加速器占用了端口？有无可以不重启电脑的解决方法，感谢作者

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10690194/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/98558933/217660022-b277f6dd-9326-4458-88db-d159c182b3d8.png)

### 还有别的吗？

模拟器为蓝叠国际版
使用系统为win10

**Comment by ABA2396** [comment]
看看这个 #3201

**Comment by MistEO** [comment]
是 UU 的问题，之前已经有很多朋友提到过了。建议都去给 UU 提一下反馈，让他们尽快解决下。起码保证停止加速后，系统的网络配置能恢复到之前的状态，而不是把配置改了就不管了

**Comment by Mashiro173** [comment]
> 是 UU 的问题，之前已经有很多朋友提到过了。建议都去给 UU 提一下反馈，让他们尽快解决下。起码保证停止加速后，系统的网络配置能恢复到之前的状态，而不是把配置改了就不管了

OK了解了 我去给UU方反馈一下问题 不过估计是很难解决了。。

**Comment by Mashiro173** [comment]
> 看看这个 #3201

了解
