### ISSUE TITLE
开始剿灭作战失败

### ISSUE THREAD

**Issue by chenjie1234567890** [MaaAssistantArknights/MaaAssistantArknights#365]
![image](https://user-images.githubusercontent.com/39559452/164367584-373a38e0-3972-46aa-8964-e2506ce68414.png)
![image](https://user-images.githubusercontent.com/39559452/164367656-f7fd0715-4e58-401d-bd58-7e1259033f85.png)
[相关日志.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8527061/default.txt)

**Comment by zzyyyl** [comment]
@MistEO 剿灭的开始行动跟普通关的开始行动不在一个位置（

**Comment by MistEO** [comment]
v3.1.3 fixed
