### ISSUE TITLE
购物时进入终端界面的sidestory

### ISSUE THREAD

**Issue by qaz1qazlol2** [MaaAssistantArknights/MaaAssistantArknights#3650]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，这导致啥都操作不了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10693478/asst.log)

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/217732929-f673df32-5b2a-4afb-98ed-8195495fe3e2.png)
是自己开的吗

**Comment by qaz1qazlol2** [comment]
对，我的of-1已经解锁了，而且关卡选择不是上次（美国服）

**Comment by ABA2396** [comment]
美服界面不一样，得换下图片和ocr的内容
![image](https://user-images.githubusercontent.com/99072975/217741641-da87a53d-c041-4ee6-a1c5-5a55d342501a.png)
![image](https://user-images.githubusercontent.com/99072975/217741667-f881275e-68b9-4ff6-b72d-81defc0640ac.png)

**Comment by qaz1qazlol2** [comment]
我应该在哪里改这些识别内容

> 美服界面不一样，得换下图片和ocr的内容 ![image](https://user-images.githubusercontent.com/99072975/217741641-da87a53d-c041-4ee6-a1c5-5a55d342501a.png) ![image](https://user-images.githubusercontent.com/99072975/217741667-f881275e-68b9-4ff6-b72d-81defc0640ac.png)

**Comment by ABA2396** [comment]
在\resource\global\YoStarEN\resource\task.json中添加以下字段
```
"StageEpisodeToOF": {
    "text": [
        "火蓝之心"
    ]
 },
"OFToOF-Chapter": {
    "text": [
        "进入",
        "活动"
    ]
},
```
我没有外服的客户端，不知道具体文本内容是什么，根据显示内容修改对应的text

**Comment by ABA2396** [comment]
如果能用的话可以发一个pr  ~我们这里基本没什么人玩EN服~

**Comment by qaz1qazlol2** [comment]
> 如果能用的话可以发一个pr ~我们这里基本没什么人玩EN服~

我明天安装一下环境

**Comment by RiichiTsumo** [comment]
我也美服的，ss全解锁了信用商店功能也一切正常，试试更新到最新版本吧

**Comment by ABA2396** [comment]
> 我也美服的，ss全解锁了信用商店功能也一切正常，试试更新到最新版本吧

美服的助战刷信赖的功能确实还没支持

**Comment by qaz1qazlol2** [comment]
> 如果能用的话可以发一个pr ~我们这里基本没什么人玩EN服~

现在卡在这张图片上
![SharedScreenshot3](https://user-images.githubusercontent.com/115929847/218245886-d2b46d42-7cd8-4f59-8ef0-70b87bd23025.jpg)

**Comment by qaz1qazlol2** [comment]
手动点击start后正常下一步

**Comment by ABA2396** [comment]
> 手动点击start后正常下一步

在国服的task.json(\resource\task.json)中的"StartButton1"的"next"最后添加"#self"
![image](https://user-images.githubusercontent.com/99072975/218249720-da587063-1d15-410a-946b-8cfb954b230e.png)

**Comment by qaz1qazlol2** [comment]
> > 手动点击start后正常下一步
> 
> 在国服的task.json(\resource\task.json)中的"StartButton1"的"next"最后添加"#self" ![image](https://user-images.githubusercontent.com/99072975/218249720-da587063-1d15-410a-946b-8cfb954b230e.png)

报错资源缺失了

**Comment by ABA2396** [comment]
> 报错资源缺失了

啥，发个日志看看

**Comment by qaz1qazlol2** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10713131/asst.log)

**Comment by qaz1qazlol2** [comment]
添加“#self”后报错，删掉就没事

**Comment by ABA2396** [comment]
你好像写错了，标点啥的没问题吗

**Comment by ABA2396** [comment]
"AnnihilationConfirm",
"#self"

**Comment by qaz1qazlol2** [comment]
等一下，我再看看

**Comment by ABA2396** [comment]
> “#self”

你这里用的是中文的引号，要用英文的逗号和引号才行

**Comment by qaz1qazlol2** [comment]
其实是我落了一个逗号（

**Comment by qaz1qazlol2** [comment]
现在没法触发刷关，我试了在刷理智里手动输入OF-1，一切正常

**Comment by ABA2396** [comment]
你在它点确认后立马返回就可以了）

**Comment by qaz1qazlol2** [comment]
哪个确认啊（我现在顺便做一些翻译的工作，到时候一并pull上来

**Comment by ABA2396** [comment]
> 现在没法触发刷关，我试了在刷理智里手动输入OF-1，一切正常

在\config\gui.json中有个"Visit.LastCreditFightTaskTime"，你把这段删掉或者改成之前的时间就能再触发这个功能了

**Comment by ABA2396** [comment]
> 哪个确认啊（我现在顺便做一些翻译的工作，到时候一并pull上来

就maa点start的时候你马上按一下返回或者esc就回到了上个界面，看它会不会再点start进去

**Comment by qaz1qazlol2** [comment]
> > 哪个确认啊（我现在顺便做一些翻译的工作，到时候一并pull上来
> 
> 就maa点start的时候你马上按一下返回或者esc就回到了上个界面，看它会不会再点start进去

它太快了，我按返回时它直接点击了

**Comment by qaz1qazlol2** [comment]
[2023-02-11 18:59:35.690][INF][Px2ea0][Tx15e0] {"taskchain":"Copilot","details":{"to_be_recognized":["BattleQuickFormation"],"cur_retry":10,"retry_times":20},"first":["BattleQuickFormation"],"taskid":1,"class":"asst::ProcessTask","subtask":"ProcessTask","pre_task":""}

**Comment by qaz1qazlol2** [comment]
没反应

**Comment by qaz1qazlol2** [comment]
真让人摸不着头脑（

**Comment by ABA2396** [comment]
点慢了，已经当做战斗开始了）能跑就不用管了

**Comment by qaz1qazlol2** [comment]
> 点慢了，已经当做战斗开始了）能跑就不用管了

借助战刷信赖还是卡在这一步，日志里是这个

**Comment by ABA2396** [comment]
嘶，那再发下日志

**Comment by qaz1qazlol2** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10713549/asst.log)

**Comment by ABA2396** [comment]
发下截图，这个功能是要借助战的，回去点右上角的蓝色小人

**Comment by qaz1qazlol2** [comment]
> 发下截图，这个功能是要借助战的，回去点右上角的蓝色小人

最近有点忙，截图的话和上面的一样

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/218375811-4b0ac2a0-559d-41d8-9ffb-a8b0f42c62fc.png)
像是卡在了这个地方，en服有啥不一样吗

**Comment by qaz1qazlol2** [comment]
没有卡在这里，我连选干员的界面都没进去，但是我手动进入选择干员的时候maa就正常了

**Comment by ABA2396** [comment]
哦，那还有个要加
```
"BattleStartPre": {
        "text": [
            "开始行动",
            "开始突袭",
            "开始试炼"
        ]
    },
```
得改成en对应的

**Comment by qaz1qazlol2** [comment]
ok,完美修复，我重新投一下pr

**Comment by liuyifan-eric** [comment]
可以用tools里面的OverseasClients看看缺少哪些翻译
