### ISSUE TITLE
使用MAA启动mumu模拟器和游戏会导致帧率极大下降

### ISSUE THREAD

**Issue by sakana155** [MaaAssistantArknights/MaaAssistantArknights#3651]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

模拟器:mumux最新版12.1.6.0(x64)(20230117204837)
MAA：内测版最新v4.10.7
触控模式无论是默认兼容还是实验功能均存在此问题帧率在60-15浮动，画面卡顿明显，断开ADB链接帧率好转。手动打开模拟器和游戏不存在此问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10694448/asst.log)

**Comment by MistEO** [comment]
像是 mumu 本身的问题，我去找他们的开发大佬看看。你用别的模拟器有这个问题吗

**Comment by sakana155** [comment]
> 像是 mumu 本身的问题，我去找他们的开发大佬看看。你用别的模拟器有这个问题吗

我只用mumu别的没试过
