### ISSUE TITLE
怎么运行Linux版本？

### ISSUE THREAD

**Issue by GuangDai** [MaaAssistantArknights/MaaAssistantArknights#3654]
### 说说你遇到的问题？

已经查看相关Issue，没有头绪。

无论是自己编译还是打包好的，最下面都是资源文件，没有一个作为入口的二进制文件。

请问是如何运行的？

**Comment by MistEO** [comment]
需要自己集成下接口，几行代码就搞定。可以参考  python sample 或者 c sample 等，我们有 c python go rust java 等的 APIs，也有 http api

**Comment by GuangDai** [comment]
> 需要自己集成下接口，几行代码就搞定。可以参考 python sample 或者 c sample，我们有 c python go rust java 等的 APIs，也有 http api

好的，我理解了，谢谢你。

**Comment by GuangDai** [comment]
> 需要自己集成下接口，几行代码就搞定。可以参考 python sample 或者 c sample，我们有 c python go rust java 等的 APIs，也有 http api

好的，我理解了，谢谢你。
