### ISSUE TITLE
建议手动输入关卡设置放在一键长草页面

### ISSUE THREAD

**Issue by HauKuen** [MaaAssistantArknights/MaaAssistantArknights#3655]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

手动输入关卡名这个选项放在设置里面切换起来太繁琐了，指定图刷完之后想要切换回来还要重新进入设置界面来取消勾选。

### 有什么好的想法？

把**手动输入关卡名**这个设置放在**一键长草**页面的**关卡选择**里作为一个下拉选项，选择了这个选项后就把下拉框改成文本框来接受用户输入。

**Comment by ABA2396** [comment]
那这样换回来不也要去设置（？）

**Comment by HauKuen** [comment]
就地在文本框旁边加一个选项呢（
