### ISSUE TITLE
生息演算挂机死循环

### ISSUE THREAD

**Issue by Shadowsorrow** [MaaAssistantArknights/MaaAssistantArknights#3656]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

生息演算遇到上面一格是“被毁的家园“”时无有效选项会一直卡在这里反复选择

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10708110/asst.log)
2月10日晚10点左右

### 截图

![BS_PIC_2023-02-10-22-02-06](https://user-images.githubusercontent.com/55953222/218111255-4ba17204-9e00-4020-89c0-08f00281dd73.png)

**Comment by WLLEGit** [comment]
Duplicate of #3601 

对话卡住暂时不准备处理
