### ISSUE TITLE
肉鸽模式无法自动启动

### ISSUE THREAD

**Issue by Sherlock-Lynn** [MaaAssistantArknights/MaaAssistantArknights#366]
逍遥模拟器，无限刷肉鸽无法使用，开始后干员不会部署，失败后不会退出

**Comment by zzyyyl** [comment]
发下日志`asst.log`吧~

**Comment by Sherlock-Lynn** [comment]
![image](https://user-images.githubusercontent.com/86522384/164676405-7d8bef0a-674e-4c21-aff0-dc9bb4218c57.png)
这里有相关的截图

**Comment by Sherlock-Lynn** [comment]
这边尝试上传日志中，可能是网络或者是其他原因，短时间内可能暂时上传会失败

**Comment by Sherlock-Lynn** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8540371/asst.log)

**Comment by zzyyyl** [comment]
日志里显示模拟器分辨率是`16:10`，可以考虑改成`16:9`类型的分辨率，如`1280x720`再次尝试。参见[使用说明](https://github.com/MaaAssistantArknights/MaaAssistantArknights#使用说明)。

根本原因在于分辨率比例不同会导致`opers_analyze`识别不出职业图标。（这个问题第一次出现在日志中1039-1042行）
