### ISSUE TITLE
Compile error on ARM

### ISSUE THREAD

**Issue by jackjieYYY** [MaaAssistantArknights/MaaAssistantArknights#3662]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

os: ubuntu 22.04 LTS
architecture: AArch64
error diagnostics and reproduction:
-------------------------------------------------------------------------
apt update && apt upgrade -y
apt install git gcc-12 g++-12 zlib1g-dev ccache cmake -y
git clone --recurse-submodules https://github.com/MaaAssistantArknights/MaaAssistantArknights
cd MaaAssistantArknights
export CC="ccache gcc-12"
export CXX="ccache g++-12"
mkdir -p build
cmake -B build -DINSTALL_THIRD_LIBS=ON -DINSTALL_RESOURCE=ON -DINSTALL_PYTHON=ON
cmake --build build --parallel $(nproc --all)   ----------->error crash

-------------------------------------------------------------------------

### Log files

[100%] Linking CXX shared library libMaaCore.so
/usr/bin/ld: third_libs/install/fastdeploy/lib/libfastdeploy.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/MaaCore.dir/build.make:1829: libMaaCore.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/MaaCore.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
root@ubuntu:~/MaaAssistantArknights# 

### Screenshots

![_)@(7C~}1B8R}O67RBU9A_T](https://user-images.githubusercontent.com/53422254/218229055-ab3e4d95-10e5-4738-9a2a-86001b6e3ec4.png)

### Anthing else?

![30W_GC(92N)7@(8ULR5W$HI](https://user-images.githubusercontent.com/53422254/218229382-a4fa916d-9686-4f10-93bb-04de87323b8b.png)

**Comment by horror-proton** [comment]
The default commandline option will download precompiled x86 library from https://github.com/hguandl/adb-lite, https://github.com/MaaAssistantArknights/build-fastdeploy, https://github.com/MaaAssistantArknights/build-opencv.

You can install or compile them and use options like `-DOPENCV_DIRECTORY`, `-DFASTDEPLOY_DIRECTORY`, (note that fastdeploy depends on opencv).

A better alternative is using
- https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/3346
