### ISSUE TITLE
信用购物不买有折扣的吗

### ISSUE THREAD

**Issue by devtint** [MaaAssistantArknights/MaaAssistantArknights#3663]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

信用购物是设定了不优先买有折扣的？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10712325/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/28558522/218232471-a6847b4d-1bc7-4de3-8f7b-39b416a98703.png)

### 还有别的吗？

mumu模拟器X V12.1.6.0
win11 22h2

**Comment by ABA2396** [comment]
优先购买白名单，再排除黑名单从前往后购买。两个干员没买完可能会有问题，可以试试把坚雷也写到黑名单里

**Comment by HydrogenDeuterium** [comment]
> 优先购买白名单，再排除黑名单从前往后购买。两个干员没买完可能会有问题，可以试试把坚雷也写到黑名单里

感觉不是这个问题，不然要是剩60信用，100的酯排在50的铁前面也应该买铁啊

**Comment by SoniaStarry** [comment]
希望增加第一顺序优先购买打折商品的功能。谢谢

**Comment by MistEO** [comment]
“优先购买”可以理解成“无脑买”，现在的黑名单模式就是会买打折的的
