### ISSUE TITLE
基建换班直接按照当前系统时间自动选择基建计划问题

### ISSUE THREAD

**Issue by jsoangiaonog** [MaaAssistantArknights/MaaAssistantArknights#3664]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在设置好基建换班的情况下（因为不同班组会有不同的时间区间设定），因为我不是每次都严格按照当时设定的时间周期进行换班，但MAA总是会根据当前时间自动更改我手动更改过的基建计划所选择的组别。

### 有什么好的想法？

基建换班能否改为按照我手动调整的班组进行换班，而不是根据当前时间进行选择。

### 其他内容

无

**Comment by ABA2396** [comment]
你可以在基建配置文件中删除所有的
```
"period": [
    [
        "时间1",
        "时间2"
    ]
]
```
这样每次换班结束后会自动切换到下一个配置，而不是通过时间来切换

**Comment by jsoangiaonog** [comment]
刚才试了下，确实解决了，谢谢！
