### ISSUE TITLE
借助战嫖信用的时候卡在助战界面

### ISSUE THREAD

**Issue by Deli-kkcs** [MaaAssistantArknights/MaaAssistantArknights#3668]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa v4.10.7稳定版 + 雷电模拟器；
卡在了借助战界面不动，处于第三个编队，队伍中已经编入的干员是风笛，准备进入的关卡是火蓝之心OF-1；手动点借助战
![image](https://user-images.githubusercontent.com/113994598/218287609-719a13d7-1785-4555-b6c6-0678af3d8046.png)
即恢复正常。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10715041/asst.log)

翻了下日志文件，时间大约在[2023-02-12 08:37:00.027]~[2023-02-12 08:39:21.611]

### 截图

![image](https://user-images.githubusercontent.com/113994598/218287498-99da4eb5-e38a-4c4f-826f-997bfdc4eac8.png)
卡在了这个界面

**Comment by DeliGitee** [comment]
后来截的图，当时就手动点了一次就好了
