### ISSUE TITLE
两间贸易战不换班，不收取每日信用

### ISSUE THREAD

**Issue by cuthx** [MaaAssistantArknights/MaaAssistantArknights#367]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8541932/asst.log)
![image_22_看图王](https://user-images.githubusercontent.com/99347811/164740268-16de7df4-4411-471c-b092-895bf1cc05ac.png)

**Comment by zzyyyl** [comment]
可能是分辨率引起的问题，你的分辨率过低，建议调高分辨率后重试。参见[使用说明](https://github.com/MaaAssistantArknights/MaaAssistantArknights#使用说明)。
