### ISSUE TITLE
ClashX Pro 的增强模式会导致 MAA 连接失败

### ISSUE THREAD

**Issue by derbalkon** [MaaAssistantArknights/MaaAssistantArknights#3671]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在开启了 ClashX Pro 的增强模式后，MAA 会报错 "connectionInfo: ConnectFailed Uuid command failed to exec"。
注：已按照 [#2495(comment)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2495#issuecomment-1295888927)将 config 中的 uuid 字段进行修改。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10715334/asst.log)

时间点：
[2023-02-12 13:02:56.299] ClashX Pro 仅为系统代理模式，MAA 可以成功连接模拟器；
[2023-02-12 13:03:24.682] ClashX Pro 打开了增强模式（FakeIP），MAA 报错 "connectionInfo: ConnectFailed Uuid command failed to exec"；
[2023-02-12 13:04:03.534] ClashX Pro 关闭了增强模式，还原为仅系统代理模式，MAA 依然报错 "connectionInfo: ConnectFailed Uuid command failed to exec"。

### 还有别的吗？

机型：M1 Macbook Pro

模拟器：Android Studio Emulator

重启系统并保证不开启 ClashX Pro 的增强模式，就没有问题发生。

**Comment by MistEO** [comment]
你已经发现问题了，即 Clash 的增强模式修改了某些系统设置，即使关闭后，这些系统配置也没有被还原到最初状态。建议给他们提个 bug

**Comment by derbalkon** [comment]
Solved in Clash Core Premium v2023.02.16 and ClashX Pro v1.97.0.4.
