### ISSUE TITLE
无法正确识别 Hyper-V 版本蓝叠模拟器的 ADB 端口

### ISSUE THREAD

**Issue by MegaOwIer** [MaaAssistantArknights/MaaAssistantArknights#3673]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

根据 [文档](https://maa.plus/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.html#%E2%9C%85-%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E5%9B%BD%E9%99%85%E7%89%88-hyper-v-%E7%89%88%E6%9C%AC) 完成 MAA 配置之后重启，MAA 识别到的 ADB 端口是 5555 而非 Bluestacks 设置中给出的 2360。手动更改端口为 2360 后可正常连接。

翻了翻 `bluestacks.conf`，发现 5555 端口对应的字段名称是 `bst.instance.Pie64.adb_port`，而 2360 端口对应的字段名称是 `bst.instance.Pie64.status.adb_port`。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10715382/asst.log)

### 截图

<img width="645" alt="image" src="https://user-images.githubusercontent.com/31935672/218295503-316e922b-fdb8-4ba5-a2b4-09bba2bb76b6.png">

### 还有别的吗？

模拟器版本为 `5.10.210.1003 P64`

**Comment by MegaOwIer** [comment]
顺带一提 `gui.json` 似乎已经挪到了 `config/` 目录下而非 MAA 根目录，这一点与文档不符，建议更新一下文档。

**Comment by ABA2396** [comment]
官网的文档比较落后，好几个版本没更新了，GitHub已经加上了

~不过路径好像还是没改~

**Comment by horror-proton** [comment]
可以增加一项 `Bluestacks.Config.Keyword` 设为对应的 `bst.instance.Pie64.status.adb_port`

**Comment by MegaOwIer** [comment]
> 可以增加一项 `Bluestacks.Config.Keyword` 设为对应的 `bst.instance.Pie64.status.adb_port`

fixed. thx.

**Comment by MegaOwIer** [comment]
不对...好像是我本地设置有问题...打扰了= =
