### ISSUE TITLE
会客室卡住，不能正确退出

### ISSUE THREAD

**Issue by onlookerLi** [MaaAssistantArknights/MaaAssistantArknights#3675]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

会客室会卡在传递线索的页面，貌似是因为完成基建之后没有正确退出到战斗页面等其他页面导致直接任务出错，直接任务完成。
时间:13.35.37-13.37.01

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10715428/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/96764403/218297101-682bb559-c9a6-4701-81fa-6f2e13a60f0e.png)

### 还有别的吗？

MuMu模拟器，分辨率 1280x72 dpi 240

**Comment by MistEO** [comment]
后面修过一个类似的问题，更新下版本看看
