### ISSUE TITLE
Hyper-V开启情况下无法分别连接蓝叠多开模拟器

### ISSUE THREAD

**Issue by kk-235** [MaaAssistantArknights/MaaAssistantArknights#3676]
### 说说你遇到的问题？

MAA版本         v4.10.7
蓝叠版本         5.10.210.1103
Windows版本  Windows10专业版 22H2    开启Hyper-V

使用两个MAA文件夹对应两个Pie64模拟器

根据docs内文档为两个gui.json都添加两个字段
`"Bluestacks.Config.Path": "E:\\BlueStacks_nxt\\bluestacks.conf"`
`"Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port"`

MAA在管理员模式打开后能正常连接（还挺快的bushi
但是在两个模拟器都开的情况下两个MAA都只能连接到第一个模拟器，请问有什么办法解决吗？

**Comment by ABA2396** [comment]
bst.instance.模拟器编号.status.adb_port

**Comment by ABA2396** [comment]
如果都是pie的话，第一个编号如果是Pie，那后一个应该就是Pie_1，这个你可以在模拟器的文件夹里或者模拟器快捷方式的路径中看到

**Comment by kk-235** [comment]
> 如果都是pie的话，第一个编号如果是Pie64，那后一个可能就是Pie64_1，这个你可以在模拟器的文件夹里或者模拟器快捷方式的路径中看到

可行！十分感谢
我的是在 BlueStacks_nxt\Engine 文件夹下有三个引擎
![image](https://user-images.githubusercontent.com/61037611/218300615-b3dc25f2-48ce-4bf9-a488-ecb0a505ac53.png)
在gui中分别更改为
<img width="406" alt="7b0f4845986baefc023e0bf8d4952fe" src="https://user-images.githubusercontent.com/61037611/218300726-11db902e-5c12-4112-a130-18fbf5f7c8ef.png">
与
<img width="419" alt="6905d3fcee32150e230d0cd91e243c4" src="https://user-images.githubusercontent.com/61037611/218300730-a73d1530-c308-4787-ae43-9c58a17cb9ab.png">
再配合自动开启模拟器，开启MAA后即可开启MAA后自动连接了
