### ISSUE TITLE
Python接口，公招没有按配置刷新三星tag

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#3677]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如日志383行的，确认导入配置是
```json
{
    "enable": "True",
    "refresh": "True",
    "times": 1,
    "expedite": "True",
    "select": [3,4],
    "confirm": [3,4],
    "skip_robot": "True",
    "recruitment_time": {"3": 540,"4": 540},
    "report_to_penguin": "True",
    "penguin_id": "34004401"
}
```
但是没有自动刷新三星tag，也许这是个特性（？），使用MaaGui是会自动刷新的，可能是select包括了3的缘故吗？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10715590/asst.log)

### 还有别的吗？

夜神模拟器30fps 1920x1080 
Win10 21H1

**Comment by ABA2396** [comment]
"refresh"

**Comment by MistEO** [comment]
这个的值不是 string，而是 bool，即需要是 `true` 而非 `"True"`

**Comment by KJH-x** [comment]
原来没关issue吗（）是我笨了
