### ISSUE TITLE
仓库识别界面按照材料等级显示

### ISSUE THREAD

**Issue by SherkeyXD** [MaaAssistantArknights/MaaAssistantArknights#3678]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前的仓库识别结果看起来略显凌乱

### 有什么好的想法？

同类型材料放在同一行（比如石头类的一行铁类的一行）

### 其他内容

加上材料图标可能更直观

**Comment by cenfusheng** [comment]
目前仓库识别功能更多的是配合其它工具箱使用的，建议导出查看。
感谢建议，短期内没有这方面的计划。
