### ISSUE TITLE
肉鸽干员放置失败

### ISSUE THREAD

**Issue by dichigo** [MaaAssistantArknights/MaaAssistantArknights#368]
木木模拟器
![2I2W6XW}CWPNDP1LQ2$N%B1](https://user-images.githubusercontent.com/98818071/164742518-013718d1-3b27-4472-9029-94a7fb24fb60.jpg)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8542069/asst.log)

**Comment by zzyyyl** [comment]
可能是分辨率引起的问题，可以尝试将分辨率调整为`1600x900`。参见[使用说明](https://github.com/MaaAssistantArknights/MaaAssistantArknights#使用说明)。
