### ISSUE TITLE
自动肉鸽进入关卡后mma无法放置干员且战斗失败后无法识别

### ISSUE THREAD

**Issue by Extant126** [MaaAssistantArknights/MaaAssistantArknights#3681]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动肉鸽进入关卡后无法放置干员，且肉鸽失败后mma还停留在第一次战斗中无法识别该次肉鸽已经失败。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10716139/asst.log)
2-12 21:23:02到21:24:46

### 截图

<img width="1208" alt="df3d5ef4fa69a4f8ae1b1006c166c4a" src="https://user-images.githubusercontent.com/121878839/218313832-ce0da249-2275-4a14-9df5-43fb57e9eda3.png">

**Comment by MistEO** [comment]
不知道为什么 mumu 的匹配得分这么低，你是 320 dpi 吗？

**Comment by Extant126** [comment]
是1920*1080 360dpi

**Comment by Extant126** [comment]
dpi调到600也没用
