### ISSUE TITLE
基建 宿舍 识别不到心情未满干员时陷入循环

### ISSUE THREAD

**Issue by Mooncywing** [MaaAssistantArknights/MaaAssistantArknights#3682]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在**选择**“宿舍空余位置蹭信赖”的情况下
如果当前所有干员心情已满，则在**识别完全部干员后**陷入尝试继续拖动以获取更多干员信息的循环。

（陷入循环时已经连续运行约3.5个小时，但这应该没关系吧？）

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10716208/asst.zip)
[2023-02-12 20:21:28.107]左右进入宿舍，
[2023-02-12 20:23:05.284]已经进入循环

### 截图

问题截图
<img width="1137" alt="屏幕截图_20230212_215630" src="https://user-images.githubusercontent.com/118897010/218316042-e749d5ff-75a4-4e07-b3fa-b7611eaba4c1.png">

基建设置
<img width="591" alt="屏幕截图_20230212_222101" src="https://user-images.githubusercontent.com/118897010/218316648-045eb416-ba41-4caa-9a2a-9760cfc0c7c0.png">

### 还有别的吗？

MuMu模拟器  2.7.16.0(x64)
MAA  4.10.7  正式版

**Comment by MistEO** [comment]
v4.11.0-beta.2 fixed, 试试有没有用
