### ISSUE TITLE
4.10.7版本无法正常使用，出现未知错误

### ISSUE THREAD

**Issue by sam199711** [MaaAssistantArknights/MaaAssistantArknights#3683]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

  maa版本为首页下载的最新版（非增量版），系统是win10，运行库包括C++ 和.NET 都更新过了，打开时已用管理员身份，保存路径没有中文，打开软件后立刻报错，无法正常使用，下面是报错页面详情：
  显示错误：未能从程序集“mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089”中加载类型“System.ValueTuple`2”。
  解决方案：出现未知错误  
  详细信息：在 MaaWpfGui.VersionUpdateViewModel.<>c__DisplayClass34_0.<CheckAndDownloadUpdate>b__0()
   在 MaaWpfGui.VersionUpdateViewModel.CheckAndDownloadUpdate(Boolean force)
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.RootViewModel.<ShowUpdateOrDownload>d__7.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10716463/asst.log)

### 截图

![1](https://user-images.githubusercontent.com/125109287/218320855-cdd9b4c6-aefa-4f42-9019-c756743b9cca.PNG)

**Comment by ABA2396** [comment]
应该已经修了，还有这个问题吗
