### ISSUE TITLE
版本v4.10.8-beta1在使用自动连接时无法连接，切换手动后相同地址可以连接

### ISSUE THREAD

**Issue by RICE114** [MaaAssistantArknights/MaaAssistantArknights#3686]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

版本v4.10.8-beta1在使用自动连接时无法连接，切换手动后没有修改任何内容，相同地址可以连接。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10723871/asst.log)

**Comment by MistEO** [comment]
试试新版本，还有这个问题吗
