### ISSUE TITLE
每天第一次运行MAA 点开始会报错

### ISSUE THREAD

**Issue by TraceurCN** [MaaAssistantArknights/MaaAssistantArknights#3689]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

每天第一次运行MAA 点开始会报错 关掉再开就好了

错误弹窗内容如下：
**错误**
该类型的 CollectionView 不支持从调度程序线程以外的线程对其 SourceCollection 进行的更改。

**解决方案**
出现未知错误

**详细信息**
在 System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   在 System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   在 System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   在 MaaWpfGui.SettingsViewModel.set_ConnectAddress(String value)
   在 MaaWpfGui.SettingsViewModel.TryToSetBlueStacksHyperVAddress()
   在 MaaWpfGui.AsstProxy.AsstConnect(String& error)
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.TaskQueueViewModel.<LinkStart>d__68.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10727458/asst.log)

**Comment by Promisery** [comment]
我在【连接配置】设为【蓝叠模拟器】的时候有这个问题，而且关掉再开问题仍然存在，改成【通用模式】后就没问题了

**Comment by MistEO** [comment]
试试最新的内测版，还有这个问题吗

**Comment by TraceurCN** [comment]
> 

4.11.0-beta.1没有问题了
