### ISSUE TITLE
用久了以后需要重新解压才能正常进行fight任务

### ISSUE THREAD

**Issue by KlNon** [MaaAssistantArknights/MaaAssistantArknights#369]
目前由于我重新解压了,再用几天等错误再次发生再截图.
目前出现这个错误两次了.

**Comment by KlNon** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8546944/asst.log)
<img width="591" alt="Snipaste_2022-04-23_20-42-52" src="https://user-images.githubusercontent.com/58141387/164895002-fe239c7c-2d24-42b7-8029-fb7240b520fc.png">

**Comment by zzyyyl** [comment]
@MistEO 通过“上一次作战”前往关卡的时候，“开始行动”按钮会有一个向上的动画，如果中途卡了一下会导致以后的cache都是偏下的位置从而识别不到开始行动，但是不开cache会比开cache慢几十倍，这个代价有些大。
另外，这个问题跟 #365 比较类似，应该可以一起解决（

**Comment by zzyyyl** [comment]
@KlNon 当前版本要处理这个问题，其实不需要重新解压，重启一下软件就行了，然后暂时不要用“上次作战”的选项。

**Comment by KlNon** [comment]
好的,我去试试

**Comment by KlNon** [comment]
> 

可以了

**Comment by MistEO** [comment]
> @MistEO 通过“上一次作战”前往关卡的时候，“开始行动”按钮会有一个向上的动画，如果中途卡了一下会导致以后的cache都是偏下的位置从而识别不到开始行动，但是不开cache会比开cache慢几十倍，这个代价有些大。 另外，这个问题跟 #365 比较类似，应该可以一起解决（

摆了，我直接进行一个 cache 的关_(:з」∠)_

**Comment by MistEO** [comment]
v3.1.3 fixed
