### ISSUE TITLE
点击开始直接报错

### ISSUE THREAD

**Issue by Sea-Sheep** [MaaAssistantArknights/MaaAssistantArknights#3690]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

未将对象引用设置到对象的实例。

### 日志文件

 在 MaaWpfGui.SettingsViewModel.get_CreditFightTaskEnabled()
   在 MaaWpfGui.TaskQueueViewModel.appendMall()
   在 MaaWpfGui.TaskQueueViewModel.<LinkStart>d__68.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 还有别的吗？

mumu win10 v4.10.8-beta1

**Comment by Sea-Sheep** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10727502/asst.log)

**Comment by WSMTBG** [comment]
4.10.8-beta1  一样的问题

**Comment by WSMTBG** [comment]
没报错的时候去把更新切到稳定版再检查一下更新就不会报错了，不知道为什么

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/ed8702cc220f2203284d44f908c55c716349fd25 fixed
