### ISSUE TITLE
4.10.8错误：未将对象引用设置到对象的实例

### ISSUE THREAD

**Issue by Cowjiang** [MaaAssistantArknights/MaaAssistantArknights#3691]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新至4.10.8 Beta1后发生

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10727831/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/57822554/218616588-b12e1ee1-9ddc-4766-b455-f401ce3c7170.png)

### 还有别的吗？

Bluestack 5.10, Windows 11

**Comment by WSMTBG** [comment]
趁着没报错的时候去把更新切到稳定版，再点一下检查更新就不会报错了，不知道为什么...临时凑合一下吧

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/ed8702cc220f2203284d44f908c55c716349fd25 fixed
