### ISSUE TITLE
Maa beta 版无法连接到模拟器

### ISSUE THREAD

**Issue by EricWangxy** [MaaAssistantArknights/MaaAssistantArknights#3692]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Maa beta 版有时无法连接到模拟器

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10728119/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10728120/asst.log)

### 还有别的吗？

MAA-v4.10.8-beta.1
蓝叠国际版
处理器	Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz   2.11 GHz
机带 RAM	16.0 GB
系统类型	64 位操作系统, 基于 x64 的处理器
版本	Windows 11 家庭中文版

**Comment by cenfusheng** [comment]
试试新版本，还有这个问题吗
