### ISSUE TITLE
v4.10.8-beta.1 未将对象引用设置到对象的实例错误

### ISSUE THREAD

**Issue by virdmark** [MaaAssistantArknights/MaaAssistantArknights#3693]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

-错误-
未将对象引用设置到对象的实例。
-解决方案-
出现未知错误
-详细信息-
   在 MaaWpfGui.SettingsViewModel.get_CreditFightTaskEnabled()
   在 MaaWpfGui.TaskQueueViewModel.appendMall()
   在 MaaWpfGui.TaskQueueViewModel.<LinkStart>d__68.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10728250/asst.log)
设置完成任务之后点击开始就会出现错误。

### 截图

![J94V EZC$9RLWS6C7R8AM_M](https://user-images.githubusercontent.com/94534273/218626866-96109d4b-1f84-4d66-afe2-ca3a73c28169.png)

### 还有别的吗？

夜神模拟器 7.0.3.7
版本	Windows 10 家庭中文版
版本号	22H2
安装日期	‎2021/‎6/‎29
操作系统内部版本	19045.2486

设备名称	A750NIM
处理器	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
机带 RAM	32.0 GB (31.9 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	笔支持

**Comment by virdmark** [comment]
不勾选获取信用及购物就不会出现错误

**Comment by RoggeOhta** [comment]
![image](https://user-images.githubusercontent.com/19422794/218929990-b16876d2-5a9f-4871-9b6f-442f3d9052e7.png)
4.10.10同样有这个问题，同样是不勾选信用购物就能进去了
模拟器平台：蓝叠HyperV版本5.10.110.1002
系统：Win10专业版22H2

**Comment by ABA2396** [comment]
dev已经修了，等下个版本
