### ISSUE TITLE
解析作业文件错误

### ISSUE THREAD

**Issue by minarrr** [MaaAssistantArknights/MaaAssistantArknights#3696]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

作业路径打开后显示解析作业文件错误，目前只有多索雷斯在建地块以及阿卡胡拉丛林正常运行，原因不明

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10728515/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/125332676/218632340-bb81ad74-fcf3-4903-b12d-f2d82654c62b.png)
![image](https://user-images.githubusercontent.com/125332676/218632388-3b8c9016-92e3-4e70-a1e7-dcdfccf2b691.png)
![image](https://user-images.githubusercontent.com/125332676/218632448-71ed1b42-8831-4417-a7f3-4d01feed386d.png)

### 还有别的吗？

夜神模拟器 7.0.5.0
maa v4.10.8-beta.1

**Comment by ABA2396** [comment]
你选的这几个都不是作业文件
custom_infrast里的是自定义基建的配置文件
Arknights-Tile-Pos是关卡信息
只有copilot里的是自动战斗的作业文件

**Comment by minarrr** [comment]
大佬能不能讲解一下为什么copliot里只有3个文件呢？
![image](https://user-images.githubusercontent.com/125332676/218640189-2d8db5e2-d0f0-4e7c-b6ee-e78e97c20d76.png)

**Comment by minarrr** [comment]
我应该去哪里找作业文件呢大佬

**Comment by nightofknife** [comment]
copliot文件夹是作战相关的
基建文件在custom_infrast文件夹
找作业去作业网找
www.抄作业.com

**Comment by ABA2396** [comment]
https://prts.plus/
或者
点击设置-关于我们-[QQ群](https://jq.qq.com/?_wv=1027&k=YrqAYqyC)

**Comment by minarrr** [comment]
好的我会加qq群的谢谢大佬
