### ISSUE TITLE
MAA 退出后导致 adb 连接异常

### ISSUE THREAD

**Issue by HydrogenDeuterium** [MaaAssistantArknights/MaaAssistantArknights#3697]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa 完成任务退出后，adb 无法正常工作。

```
adb devices
> * daemon not running; starting now at tcp:5037
> * daemon started successfully
```
然后 adb 卡死，等待多时也没有反应。

我使用实体机进行连接，并使用 [AutoMAA](https://github.com/HydrogenDeuterium/AutoMAA) 辅助进行运行前后的设备分辨率、宽高比调整操作。

我发现在关闭 MAA 后分辨率无法正常回调。尝试手动回调时，发现 adb 工作异常。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10728552/asst.log)

具体出问题的时点大约在 11：40 这样。

**Comment by MistEO** [comment]
MAA 退出时是会 kill adb server 的，因为之前有人反馈过说 MAA 退出了还残留了 ADB 子进程。或许之后可以作为一个选项来决定是否要 kill adb

简单的方法你可以监控回调来决定是否要调整分辨率
