### ISSUE TITLE
希望定时执行可以单独设定每次待执行动作

### ISSUE THREAD

**Issue by DemiurgeZ** [MaaAssistantArknights/MaaAssistantArknights#3699]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在每天晚上用定时执行功能实行自动换班，但还得手动勾选需要执行的动作，偶尔忘了勾选就会让换班失败，导致第二天还得手动换，比较麻烦。
而且有时候想每个时间点的定时执行做不一样的动作，比如第一次自动换班+刷理智，第二次只刷理智这样。目前只能每次做同样的动作，想换还得手动换。

### 有什么好的想法？

或许可以每个定时后面有个下拉菜单，可以单独设置待执行动作？然后作为可选功能。没有需求的可以关闭单独设置。

**Comment by status102** [comment]
可以试试定时执行的自定义配置
