### ISSUE TITLE
多吃了一个药

### ISSUE THREAD

**Issue by ZhaoGY-N** [MaaAssistantArknights/MaaAssistantArknights#370]
用的mumu模拟器，设置了吃一个药，但是吃了两个。。。。

log已附上

![image](https://user-images.githubusercontent.com/62810902/164893319-9708b46b-d684-432b-9850-4ec561f28405.png)
![image](https://user-images.githubusercontent.com/62810902/164893334-b3da6297-e4dc-45cc-95d5-b827324a7c34.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8546859/asst.log)

PS. 三周年快乐

**Comment by ZhaoGY-N** [comment]
好的，暂时没有遇到了

**Comment by MistEO** [comment]
review 代码脑补了一下，可能是 `LinkStart!` 按钮快速被点了两下，实际上添加了两个刷理智的任务（内部实现是任务队列的形式），然后每个任务都吃了一个理智药。

之后的版本会尝试给这个按钮加个锁之类的，其他的可能性就等下次遇到我们再分析看看了

**Comment by MistEO** [comment]
昨天太晚了，日志看岔了。_(:з」∠)_看成了另一份日志

重新看了一下确实是按钮点了两次的问题，下个版本修复~

![image](https://user-images.githubusercontent.com/18511905/165687924-b1d47c50-7e06-4978-bf32-71eaae5e20e9.png)

**Comment by MistEO** [comment]
v3.2 fixed
