### ISSUE TITLE
maa稳定版4.10.10版本资源损坏问题

### ISSUE THREAD

**Issue by bingxuelingq** [MaaAssistantArknights/MaaAssistantArknights#3707]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa稳定版4.10.10版本无论是自动更新还是手动下载压缩包更新，或是删除所有maa文件重新解压maa使用，都会弹出资源损坏请重新下载安装包的问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10733850/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10733852/gui.log)

### 截图

![N (2YV6 7RZ$_BS8K5KB~IU](https://user-images.githubusercontent.com/104126227/218779050-fda5cc65-0510-42bc-9251-13d60612dc0b.png)

### 还有别的吗？

用的蓝叠模拟器电脑和下载的maa都是win64.

**Comment by ABA2396** [comment]
文件加载失败了，换个英文路径或者管理员权限打开试试
