### ISSUE TITLE
自动更新失败

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#371]
我有一段时间没有更新了，旧的版本号是3.0.6。今天想要使用，顺带更新一下，软件的自动更新又慢的要死还不一定成功，于是就从GitHub上面直接下载了压缩包。我把压缩包放到软件的文件夹里面，打开软件之后弹了个通知，说重启软件更新，我急着用，于是把通知关了点窗口右上角的叉号把软件关了，再手动打开了一遍。软件却没有更新，设置里看还是3.0.6，而且软件也不再提示更新，重启电脑之后也不再提示。我不想删除后再解压压缩包，那样会丢失一些数据（比如具体的设置之类的）
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8548971/asst.log)

**Comment by MistEO** [comment]
老版本更新功能有点问题，`v3.1.2` 修了一下，只有如果还出现再看看吧~

**Comment by xiaoweiXX** [comment]
> 老版本更新功能有点问题，`v3.1.2` 修了一下，只有如果还出现再看看吧~

问题又出现了，我又开了个新的issue，详情在那里

**Comment by xiaoweiXX** [comment]
> 老版本更新功能有点问题，`v3.1.2` 修了一下，只有如果还出现再看看吧~

问题又出现了，我又开了个新的issue，详情在#493
