### ISSUE TITLE
v4.10.10,生息演算中渗透区域新增对话情况，流程无法继续

### ISSUE THREAD

**Issue by Celephaises** [MaaAssistantArknights/MaaAssistantArknights#3712]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

不知道是不是鹰角新加的逻辑，月初时使用4.10.6没有该问题出现，更新到4.10.10出现该异常情况

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10740343/asst.log)

### 截图

![uTools_1676445624141](https://user-images.githubusercontent.com/68450141/218959333-67d962ee-e7f8-4831-8caa-bdde6288beb8.png)

**Comment by Celephaises** [comment]
标题我写的渗透区，怎么变成了尿透区，麻了

**Comment by WLLEGit** [comment]
Duplicate of #3601 

剧情是随机触发的，每种应该只会触发一次。遇到强制对话的要手动跳过下

**Comment by Celephaises** [comment]
> 

emm，我碰到这段剧情有七八次了。每次都是狮蝎

**Comment by ZetsuLAM** [comment]
我也遇到了这个问题，并且手动跳过一次之后当局内还是会重复遇到

**Comment by ABA2396** [comment]
摆！
