### ISSUE TITLE
日服傀影肉鸽遇到「雕匠与石像」关卡卡住无法进行

### ISSUE THREAD

**Issue by zzzzkyx** [MaaAssistantArknights/MaaAssistantArknights#3714]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

日服傀影肉鸽把「雕匠与石像」关卡识别为不期而遇，卡住无法进行
再现次数3/3

### 日志文件

问题出现的大致时间点[2023-02-15 16:52:32]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10740841/asst.zip)

### 截图

![屏幕截图(8)](https://user-images.githubusercontent.com/35620305/218972200-4f2cc045-d6dc-4335-ae1e-7da1662173a1.png)

### 还有别的吗？

游戏设置中客户端类型使用的是日服

**Comment by zzzzkyx** [comment]
> 前面一个节点就是落魄骑士吗？还是遇到过不期而遇了？

昨天的前面的节点不记得了

今天又再现了一次，先把这次的结果贴上来，前一个节点是安全的角落
![MuMu20230216124120](https://user-images.githubusercontent.com/35620305/219263250-fb193cb2-2a8c-4a52-bc59-1eb59e8ea301.png)
![MuMu20230216124415](https://user-images.githubusercontent.com/35620305/219263260-03acfc0b-7173-418f-9b4a-68ed6ff6d3a9.png)

> debug 文件夹下有一些自动截图的错误图片，若有相关的，请一并打包上传

看了一下只有一些黑屏的截图，没有相关的

**Comment by zzzzkyx** [comment]
发生时间[2023-02-16 12:38:55]之后
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10751969/asst.zip)

**Comment by zzzzkyx** [comment]
目前使用了一天多，其他的战斗关卡不会卡住，无类似问题，每次卡住都是在雕刻师这关，只能手动重开。
我看了下 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3559 似乎也是雕刻师关卡

**Comment by ABA2396** [comment]
> 

他那个没日志，没办法看。不知道为啥这个探索按钮匹配的分数特别低

**Comment by ABA2396** [comment]
看看和分辨率有没有关系，试试720或者其他的看看还会不会卡这里

**Comment by zzzzkyx** [comment]
把模拟器分辨率从1920 * 1080换成了1600 * 900还是会卡在这关，晚点试试别的分辨率
![MuMu20230217105105](https://user-images.githubusercontent.com/35620305/219529882-a6511ba4-a4d7-46ef-9915-5844b984d79a.png)
发生时间[2023-02-17 10:47:24]之后
[asst_20230217104724.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10762488/asst_20230217104724.zip)

另外，这个关卡也卡了两次
![MuMu20230216225639](https://user-images.githubusercontent.com/35620305/219530091-ce652236-142c-47bd-98f5-e29145d11228.png)
发生时间[2023-02-16 22:45:27]之后
[asst_20230216224527.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10762502/asst_20230216224527.zip)
