### ISSUE TITLE
使用“一键肉鸽”功能时反复出现“截图失败”的提示

### ISSUE THREAD

**Issue by guoyj-thu** [MaaAssistantArknights/MaaAssistantArknights#3716]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽情况下反复出现“截图失败”的提示，如果将界面放在桌面上则会好转，但之后仍会提示“截图失败”，最终导致模拟器断开

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10741086/asst.log)
大致时间：2.15 16：38

### 截图

![1676450584172](https://user-images.githubusercontent.com/125445065/218976935-c9d2f516-fe15-43fd-9ab6-e359015d2d9c.png)
![1676450624817](https://user-images.githubusercontent.com/125445065/218977113-5886931a-255a-4892-9a2f-932a457c7ffd.png)

### 还有别的吗？

模拟器：雷电模拟器
操作系统：Win11
截图失败似乎总是发生在干员招募时，有时影响进程，有时可以继续下一节点。

**Comment by ABA2396** [comment]
log没了
![image](https://user-images.githubusercontent.com/99072975/218980181-a6ff3b4a-7302-4bc3-acae-bf050759ae63.png)
雷电的话可以试试最新版本
https://lddl01.ldmnq.com/downloader/ldplayerinst9.exe?n=ldplayer9_ld_999_ld.exe
