### ISSUE TITLE
之前都可以正常运行4.10.10更新后运行出现未知错误且无法停止

### ISSUE THREAD

**Issue by a1024484966** [MaaAssistantArknights/MaaAssistantArknights#3717]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA:v4.10.10
模拟器:BlueStacks 5.10.0.6513
之前都可以正常运行 更新后运行出现未知错误且无法停止
![QQ截图20230215194716](https://user-images.githubusercontent.com/106376411/219006517-21a18a67-0f82-4e09-a148-0fbbd3c59b56.png)

### 日志文件

2023年2月15日19:48:20左右
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10742070/asst.log)

### 截图

![QQ截图20230215194210](https://user-images.githubusercontent.com/106376411/219005882-0ae080e9-1dd9-411f-bd94-1a9764566db1.png)

**Comment by ABA2396** [comment]
你选了自定义基建但没选文件和配置

**Comment by a1024484966** [comment]
> 你选择了自定义基础但没有选择文件和配置

谢谢大佬已解决
