### ISSUE TITLE
测试版基建换班出现问题

### ISSUE THREAD

**Issue by lancelotgx** [MaaAssistantArknights/MaaAssistantArknights#3721]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA V4.11.0测试版更新后基建所有设施出现干员冲突，换班时出现卡在设施内不断选人的情况。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10744488/asst.log)

### 截图

![QQ拼音截图20230215231423](https://user-images.githubusercontent.com/101645625/219068556-eb48cc02-a552-46aa-90be-0fc53a9b6a0e.png)

### 还有别的吗？

蓝叠，WINDOS。

**Comment by LingYi520** [comment]
我也是
