### ISSUE TITLE
v4.11.0-alpha.2基建换班宿舍空放

### ISSUE THREAD

**Issue by rjsq** [MaaAssistantArknights/MaaAssistantArknights#3727]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

v4.11.0-alpha.2基建换班过程中宿舍会空放，会选中低心情干员，但是似乎没点击确认，直接返回了基建主页面。

在0号宿舍循环四次后会直接进入下一个任务（出现问题的时候是进入了访问好友）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10750954/asst.log)
出现问题时间2023年2月16日，上午8：55分开始-8：56分结束

### 截图

![image](https://user-images.githubusercontent.com/20448641/219232630-766531ec-975d-4f55-8ae7-08e0c867bf63.png)

### 还有别的吗？

模拟器：mumux 12.1.7.0
操作系统：Windows 11 专业版22621.1265

**Comment by rjsq** [comment]
> 

![image](https://user-images.githubusercontent.com/20448641/219251089-5ad4c7da-5852-4253-8c25-476dd10cc298.png)

**Comment by rjsq** [comment]
日志从bug发生前截取
[asst.cropped.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10751513/asst.cropped.log)

**Comment by rjsq** [comment]
> 是选了一个人，但是不点确定吗？ 选了1个还是选了5个？

是选了5个，但是不点确定

**Comment by rjsq** [comment]
> 或者你看看还能复现的话，发个从点 "link strat“ 开始的日志。

19：30左右进行了尝试，这次宿舍正常入住了，未复现bug。

**Comment by rjsq** [comment]
> 你是不是原先有0心情干员？现在0心情干员的识别好像有点问题

是的，印象中有不只一个干员心情为0
下次可以试试复现

**Comment by rjsq** [comment]
有两个0心情干员，成功复现bug
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10763084/asst.log)

**Comment by rjsq** [comment]
[新建视频录制 [360p].webm](https://user-images.githubusercontent.com/20448641/219548755-6e73ba49-aea9-4b2e-aa0d-9a600f976f30.webm)
模拟器分辨率1280X720，视频缩小为360p

**Comment by MistEO** [comment]
v4.11.0-beta.2 fixed, 试试有没有用
