### ISSUE TITLE
抄作业代码 无法使用

### ISSUE THREAD

**Issue by heixiui** [MaaAssistantArknights/MaaAssistantArknights#3728]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

下载文件可以正常使用，但复制代码会出现请求网络服务错误，读取文件失败

### 日志文件

。

**Comment by MistEO** [comment]
开发版修过了
