### ISSUE TITLE
v4.11.0-alpha.2基建宿舍无法正常换班以及0心情干员无法正常入驻

### ISSUE THREAD

**Issue by shallow-breeze** [MaaAssistantArknights/MaaAssistantArknights#3732]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述
1、问题时间为2月16日中午12点左右发现
2、我排班表上写死了使用0心情的医疗小车，但是在这次更新后无法正常入驻（图1、2）我自己的排班方案ID为：1676520439049664
3、干员无法正常地进驻宿舍，包括使用菲亚梅塔换心情（图3）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10752207/asst.log)

### 截图

![6OF~P6 GG$M2I 8K5$TXSO](https://user-images.githubusercontent.com/125531907/219269703-74c153db-0df3-42b8-b152-805efecb08af.png)
![QQ截图20230216124609](https://user-images.githubusercontent.com/125531907/219271063-428aa7e3-4560-4902-b4e6-0068123eeb05.png)
![QQ截图20230216124705](https://user-images.githubusercontent.com/125531907/219271150-3fbd5b26-3ab4-42db-85b7-77139f957de8.png)

**Comment by shallow-breeze** [comment]
选中了又取消，然后又重新选中，数次后该发电站就空着换下一间了

**Comment by shallow-breeze** [comment]
啊这，那就等优化了，QAQ

**Comment by LingYi520** [comment]
默认自带的排班也放不进去，还好这个手动也能知道放谁进去

**Comment by MistEO** [comment]
v4.11.0-beta.2 fixed, 试试有没有用
