### ISSUE TITLE
信用商店没有优先购买打折商品

### ISSUE THREAD

**Issue by SoniaStarry** [MaaAssistantArknights/MaaAssistantArknights#3733]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天偶然观察到的，先买的未打折的龙门币，然后是打折的装置和赤金。

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10753267/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10753270/asst.log)
时间点在asst.bak.log中、2023-02-16 10:04左右。

### 截图

![微信图片_20230216152802](https://user-images.githubusercontent.com/12095580/219298223-5adb6cb8-1e9d-482a-a897-a75d7d992848.png)

### 还有别的吗？

蓝叠模拟器，win10

**Comment by SoniaStarry** [comment]
又讨论了一下，maa的逻辑是白名单优先。而我的理解是打折优先。

**Comment by MistEO** [comment]
白名单是无脑购买，白名单全部买完之后执行黑名单模式，就是按照打折优先的
