### ISSUE TITLE
肉鸽错误：不放置干员（策略选择为稳定打层数）

### ISSUE THREAD

**Issue by Fillianore** [MaaAssistantArknights/MaaAssistantArknights#3734]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽开始几次探索还会正常放置干员进行战斗，从某次探索开始就会停止放置干员导致战斗失败，我提取了日志中几场战斗（包含成功放置干员和不成功的）放在附件里。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10753229/gui.log)
[asst1.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10753308/asst1.log)

### 还有别的吗？

蓝叠模拟器 win11 
Intel(R) Core(TM) i7-9700 CPU@ 3.00GHz
16GB memory
Radeon RX550

**Comment by Fillianore** [comment]
补充：MAA版本为4.10.10，asst1.log中约8309行开始的战斗异常。

**Comment by MistEO** [comment]
看日志是识别正常并且正常往场上拖动了的，是没拖上去吗，还是压根没反应，方不方便录个屏看看

**Comment by Fillianore** [comment]
那台电脑的性能很差，不适合录频。是模拟器里压根没反应。我仔细观察过后是后期CPU温度过高，模拟器出现卡顿引起的问题，这个问题估计无解，不过还是谢谢回复了。
