### ISSUE TITLE
自动战斗 出现未知错误

### ISSUE THREAD

**Issue by trswygg** [MaaAssistantArknights/MaaAssistantArknights#3737]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗页面选择神秘代码(maa://20746)后点击开始按钮出现以下错误弹窗
如何复现: 不知道
## 错误
该类型的 CollectionView 不支持从调度程序线程以外的线程对其 SourceCollection 进行的更改。
## 解决方案
出现未知错误
## 详细信息
   在 System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   在 System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   在 System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   在 MaaWpfGui.SettingsViewModel.set_ConnectAddress(String value)
   在 MaaWpfGui.SettingsViewModel.TryToSetBlueStacksHyperVAddress()
   在 MaaWpfGui.AsstProxy.AsstConnect(String& error)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10754563/gui.log)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10754624/asst.log)

### 还有别的吗？

Windows 10 19045.2311
BlueStacks 5 wth Hyper-V

**Comment by ABA2396** [comment]
更新
