### ISSUE TITLE
v4.11.0-alpha.2基建换班宿舍无法入住

### ISSUE THREAD

**Issue by zpw476898033** [MaaAssistantArknights/MaaAssistantArknights#3739]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建换班，人都是能正常换下来的，到最后进宿舍休息时候，选中了低心情的干员，但是没有点确定，而是直接返回了，然后又会重复进第一个宿舍。重复以上操作4次，然后结束基建任务，没有休息成功。

日志19:06:22开始 单独执行的基建换班任务。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10755265/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/22017658/219349766-07531ffc-4537-4578-9c29-98a0bdd571ea.png)

**Comment by zpw476898033** [comment]
> 

是的

**Comment by HydrogenDeuterium** [comment]
遇到同样的情况。

**Comment by Jerry-JRZhang** [comment]
+1
