### ISSUE TITLE
肉鸽获取初始收藏品后卡死

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantArknights#374]
![屏幕截图 2022-04-25 201719](https://user-images.githubusercontent.com/74587068/165089073-247a7efc-27ca-46f9-a25f-ca655ac80471.png)
![Screenshot_20220425-201622](https://user-images.githubusercontent.com/74587068/165089110-8380ad15-7082-436d-8c9f-7772d5dca1f9.png)
模拟器截图时间：2022-04-25-20:16:22
相关日志：[bug.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8554501/bug.log)

ps.虽然不修也不会造成影响（退一次再进就没收藏品了）但是好可惜！

顺带一提，对初次进肉鸽的提示没有处理也会导致卡死，如下

![Screenshot_20220425-201733](https://user-images.githubusercontent.com/74587068/165090022-04d71d4b-d93d-4d6a-a9fe-11ffbe6c28d7.png)
模拟器截图时间：2022-04-25-20:17:33

**Comment by MistEO** [comment]
v3.1.3 fixed
