### ISSUE TITLE
希望增加版本切换功能

### ISSUE THREAD

**Issue by Nefelibater** [MaaAssistantArknights/MaaAssistantArknights#3740]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有时内测版遇到问题暂时无法解决，希望能切回稳定版

### 有什么好的想法？

增加一个版本切换功能，或回退至上一个版本

**Comment by AkiraChisaka** [comment]
+1同感，

现在在更新版本上，就算想要切换回稳定版，如果本地版本比稳定版更新，也没有办法更新回到稳定版去。

**Comment by AkiraChisaka** [comment]
> 虽然只是一个workaround，但是如果暂时有需要的话可以下多个maa（毕竟现在硬盘容量都很大了），一个稳定版，一个内测版，其他设置可以直接把config文件夹复制过去

感谢这个建议！
