### ISSUE TITLE
基建换班执行异常

### ISSUE THREAD

**Issue by Nefelibater** [MaaAssistantArknights/MaaAssistantArknights#3741]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

制造站0与制造站1查看后未执行任何操作，跳过了制造站0和2贸易站，宿舍0死循环后报错。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10755564/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/116096983/219358507-7ac90224-82b0-4063-af96-48d8d2563831.png)

**Comment by Nefelibater** [comment]
另外发现其他组换班正常，异常的是A+B前8h(243一天4换)，在巫恋进驻宿舍时不会选择确定，从而反复试图把巫恋放进宿舍。

**Comment by Private233** [comment]
我发现了相关的bug，
我指定了无人机加速第一个制造站（赤金），但是无人机没有被使用，
我另一时间的换班中加速贸易站的无人机则是被正常使用

**Comment by saddestboy** [comment]
+1
几乎有一模一样的bug（仅宿舍）
Dorm0123都不会点确定，选完人之后点两下上面的“心情”就返回了
试了试，如果在点两下心情的同时把选人界面拖动到最左边Maa就能点确定（猜一下，似乎是漏了拖到最左边这一步，Maa检测不到选中的干员导致的？）
第一个失败的宿舍会导致死循环，不过执行一段时间后似乎会跳过换宿舍这一步？

**Comment by AkiraChisaka** [comment]
我也报告一下类似的问题。

我的版本是`v4.11.0-alpha.2`，似乎是最近的更新导致的问题。

目前基建没法把没心情的角色扔进宿舍里了呢。

**Comment by RimuruChan** [comment]
本来没这个问题，更新了v4.11.0-alpha.2之后出现了

**Comment by XiaoJoker** [comment]
相同的问题，换回v4.10.10稳定版后解决

**Comment by StellarHe** [comment]
相同问题，v4.11.0-alpha.2出现

**Comment by AkiraChisaka** [comment]
> 你们再试试 [v4.11.0-beta.1版](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.11.0-beta.1)

似乎没有问题了呢，谢谢！

**Comment by Nefelibater** [comment]
新版本已解决
