### ISSUE TITLE
请问要回退版本怎么操作？

### ISSUE THREAD

**Issue by zoe4477** [MaaAssistantArknights/MaaAssistantArknights#3744]
### 说说你遇到的问题？

![image](https://user-images.githubusercontent.com/38827851/219389120-fa736948-f4fb-48d7-9fcc-7d61519b5102.png)
下载哪一个版本覆盖呢？
新版基建完全换不了班了

**Comment by cenfusheng** [comment]
下载115M的-win-x64，解压覆盖即可
