### ISSUE TITLE
自动战斗 保全派驻作战中干员准备好的技能在某些情况下不被识别

### ISSUE THREAD

**Issue by Ding-Joe** [MaaAssistantArknights/MaaAssistantArknights#3745]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

具体如下：多索雷斯在建地块保全派驻的第四关“同流合污”，战斗路线为地图最上方一行。MAA在此部署干员后，干员技能准备好时顶上的黄色爆炸图标被界面顶部的危机等级+敌人数量+目标生命值的灰色栏遮盖了一部分，此时MAA不会自动触发干员技能。

### 日志文件

22:30左右的一把保全派驻
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10757208/asst.zip)

**Comment by MistEO** [comment]
炼丹解决.jpg

等 @horror-proton 佬看看有没有更好的法子

**Comment by horror-proton** [comment]
有截图吗, MAA 普通作战里面, MAA 应该能处理一部分这种被挡住的情况, 但不是全部(
话说保全派驻的那个栏和普通作战有啥区别吗

**Comment by MistEO** [comment]
fixed
