### ISSUE TITLE
基建换班错误

### ISSUE THREAD

**Issue by RizukiJI** [MaaAssistantArknights/MaaAssistantArknights#3747]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

换班一直卡在Dorm 0，整体过程好像是，选择疲劳的干员就直接退出了，重复执行了四次

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10762875/asst.log)

### 截图

![Snipaste_2023-02-17_11-20-40](https://user-images.githubusercontent.com/112483213/219541368-351746c0-9aa8-4de1-8e53-ae1a07aa3322.png)
![Snipaste_2023-02-17_11-21-35](https://user-images.githubusercontent.com/112483213/219541481-aa304ff2-d905-4665-b1a4-dbf6f5a3861d.png)

**Comment by huoxianribao** [comment]
版本号: v4.11.0-alpha.2.9.gf9ddbb4b

**Comment by 704299448** [comment]
是自定义换班的问题，默认的换班则正常

**Comment by RizukiJI** [comment]
可我这个就是默认的啊……



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月17日 18:45 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [MaaAssistantArknights/MaaAssistantArknights] 基建换班错误 (Issue #3747) |

是自定义换班的问题，默认的换班则正常

**Comment by weedi0** [comment]
蓝叠模拟器 自定义排班同样遇到问题，不启用自定义排班正常。出问题前未修改过排班内容，并且一直正常执行。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10766452/asst.log)

**Comment by 704299448** [comment]
之前是正常的，2天前更新后，自定义排班就出问题了。

**Comment by MisterCoBen** [comment]
同上，蓝叠国际模拟器，我观察了一下，好像是宿舍选完干员后没有点击确定键,不知道是不是识别的问题还是别的bug
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10771480/asst.log)

**Comment by Cherrling** [comment]
版本号: v4.11.0-alpha.2.17.ge1c113d8
mumu模拟器，问题复现
使用默认换班
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10772948/debug.zip)

**Comment by HHuive** [comment]
版本号: v4.11.0-alpha.2
mumu模拟器出现同一错误
![image](https://user-images.githubusercontent.com/119830020/220008026-e8b78f2d-83bd-4537-9472-9c45253af193.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10779504/asst.log)

**Comment by MistEO** [comment]
v4.11.0-beta.2 fixed, 试试有没有用
