### ISSUE TITLE
在刷理智完成后会卡在"完成任务:Fight"步骤

### ISSUE THREAD

**Issue by Notofnice** [MaaAssistantArknights/MaaAssistantArknights#3748]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最近两次测试版更新出现的bug,昨天也出现了这个bug,今天复现了反馈一下
在刷理智结束时MAA不进行下一步,在"完成任务:Fight"卡住
同时也无法停止,在点击停止按钮后卡在"正在停止..."步骤

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10763340/asst.log)
2月17日 11:18:27左右出现的问题

### 截图

![image](https://user-images.githubusercontent.com/63146701/219553958-451605be-f8b8-44df-81a1-c9c8771852a6.png)

### 还有别的吗？

版本:MAA v4.11.0-alpha.2.9.gf9ddbb4b
模拟器:蓝叠5.9.300.1014 P64 (群里下载的)

**Comment by Notofnice** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10766824/asst.log)
2月17日 20点30分左右
这次在自动公招结束后卡住，在显示完成任务后MAA没有进行下一步操作
点击停止还是卡在"正在停止..."

**Comment by LFWQSP2641** [comment]
和 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3824 一样的问题
第1104行`[2023-02-17 20:30:27.977][INF][Px3a8c][Tx5714] request:`没有对应的response
