### ISSUE TITLE
保全派驻自动战斗会卡住

### ISSUE THREAD

**Issue by canbingzt** [MaaAssistantArknights/MaaAssistantArknights#3750]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用**SSS_多索雷斯在建地块.json**挂机过程中，会突然卡住，不继续战斗

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10764131/asst.zip)

时间点大概是14:59

### 截图

![微信截图_20230217145950](https://user-images.githubusercontent.com/3953700/219572321-e1221a00-ccb5-418d-95d9-b9cfe2ba9455.png)

### 还有别的吗？

模拟器： BlueStacks 5
操作系统： win11 22H2

**Comment by Cheresting** [comment]
估计是选择掉落装备之后的问题
