### ISSUE TITLE
adb重连失败时自动重启模拟器更改为真正重启

### ISSUE THREAD

**Issue by FrothierNine346** [MaaAssistantArknights/MaaAssistantArknights#3753]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

adb重连失败时自动重启模拟器实际仅为启动模拟器，有时模拟器抽风启动失败又还在运行，在挂自动任务时就必须人工处理。

### 有什么好的想法？

adb重连失败时自动重启模拟器更改为真正重启，先尝试杀死模拟器进程再尝试启动。

**Comment by zzyyyl** [comment]
是说重启电脑？

**Comment by FrothierNine346** [comment]
> 是说重启电脑？

是重启模拟器，具体有写。

**Comment by ABA2396** [comment]
连关都做不好，别说重启了（）

**Comment by cenfusheng** [comment]
你说得对，但是做不到，“先尝试杀死模拟器进程”首先就做不到（参考 #3960 ）
