### ISSUE TITLE
刷理智过程中博士等级提升导致MAA无法继续

### ISSUE THREAD

**Issue by dklurker** [MaaAssistantArknights/MaaAssistantArknights#3758]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

设置MAA刷理智后，期间博士等级提升，在博士等级提升的界面MAA无法识别，故卡死，后提示”游戏崩溃，重新启动“。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10772864/asst.log)
时间：02-18 10:16

**Comment by HydrogenDeuterium** [comment]
感觉是偶发问题，刷理智的时候升级我遇到好几次了 没遇到崩溃的情况
