### ISSUE TITLE
StartUp阶段无法识别并启动游戏

### ISSUE THREAD

**Issue by XiaoJoker** [MaaAssistantArknights/MaaAssistantArknights#3761]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

版本是v4.10.10 稳定版，模拟器版本是蓝叠5国际版，安卓7（Nougat 64位）。
StartUp阶段卡住，尝试手动进入发现后续功能均正常。
adb是从第三方下载（常见问题文档中的链接）的，换成alas的adb也是同样的问题。
触控模式从minitouch改为adb input兼容模式，未解决。
勾选adb lite，未解决。
切换分辨率，未解决。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10773988/asst.log)

### 截图

![QQ截图20230218191553](https://user-images.githubusercontent.com/37894974/219857662-2c0b343d-c4e1-4569-888a-cad3ca4d61fb.png)

### 还有别的吗？

昨天折腾了很长一段时间一直连接后无反应，或者一两分钟才能执行一次点击，根据之前看到的issue说是卡在了截图识别那里，所以把模拟器从安卓9换安卓7后才算解决。这部分如果无法解决的话建议把方法加到常见问题中供其他人参考。
#2907

**Comment by ntgmc** [comment]
你好 
![image](https://user-images.githubusercontent.com/74061867/219857926-0318f23d-9645-4733-afe2-81c2438a5d5b.png)
你不选择服务器MAA怎么开游戏呢？
![image](https://user-images.githubusercontent.com/74061867/219857950-63d5917d-7939-4d52-96b2-9266b7e6a52b.png)

**Comment by XiaoJoker** [comment]
好吧，我以为是默认官服的。
