### ISSUE TITLE
生息演算刷赤金的开启在哪里

### ISSUE THREAD

**Issue by puzi12138** [MaaAssistantArknights/MaaAssistantArknights#3763]
### 说说你遇到的问题？

在release里看到了这个功能，但是找不到入口

**Comment by WLLEGit** [comment]
em后端支持了刷赤金但UI还没做，似乎更新日志没写这点。

如果你有Python环境的话，可以去MAA目录下python/sample.py里通过这段代码启动刷赤金功能：
`asst.append_task("ReclamationAlgorithm", {
        "mode": 1
    })`

**Comment by migong13** [comment]
如果你有Python环境的话，可以去MAA目录下python/sample.py,按这步打开文件，显示：FileNotFoundError: Could not find module 'C:\WINDOWS\MaaCore.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by WLLEGit** [comment]
> 如果你有Python环境的话，可以去MAA目录下python/sample.py,按这步打开文件，显示：FileNotFoundError: Could not find module 'C:\WINDOWS\MaaCore.dll' (or one of its dependencies). Try using the full path with constructor syntax.

在sample.py所在目录执行python sample.py，或者修改`path = pathlib.Path.cwd().parent`为MaaCore.dll的绝对路径
