### ISSUE TITLE
GUI上添加一下水月肉鸽难度选择提示

### ISSUE THREAD

**Issue by hanyuwei70** [MaaAssistantArknights/MaaAssistantArknights#3764]
RT
玩家第一次使用的时候会发现卡在难度选择界面，需要在GUI或者手册里提醒一下选择难度

**Comment by cenfusheng** [comment]
感谢反馈，已写入。
![image](https://user-images.githubusercontent.com/52312717/225517715-e387d440-c18b-44d3-81c3-de652590bfbf.png)
