### ISSUE TITLE
信用相关-自动借助战

### ISSUE THREAD

**Issue by Soso6666** [MaaAssistantArknights/MaaAssistantArknights#3765]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

勾选自动借助战后，自动进入别传界面后无法进入火蓝之心里，需要手动点击进入活动，才能继续。另外，我想重of复试验，但第二次maa会自动跳过借助战环节，不知是否是因为已经识别到我已经借过一次助战的原因了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10775137/asst.log)
大约在2月19号4点30分左右吧。出现问题后我又点了一次想复刻验证一下，但是是是maa直接跳过借助战环节了，不知是否是bug

### 还有别的吗？

mumu模拟器 win10系统

**Comment by ABA2396** [comment]
在 \config\gui.json 文件中有一个"Visit.LastCreditFightTaskTime"字段，把它的值改成前一天或者直接删除整行就行了

**Comment by ABA2396** [comment]
如果确定还有bug的话就再开一个issue吧
