### ISSUE TITLE
能否增加防止多开/单例模式选项？

### ISSUE THREAD

**Issue by yd278** [MaaAssistantArknights/MaaAssistantArknights#3767]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

用了windows计划任务和maa自带的定时运行来实现定时换班/收菜，但有时候自己开的忘记关了，会出现两个maa一起控制一个模拟器，导致各种操作都出问题。

### 有什么好的想法？

设置中增加一个防止多开的勾选项（或者先仅在win平台下加），若勾选，则每次启动maa时先检查一下是否已有maa正在运行

**Comment by WSMTBG** [comment]
maa设置-连接设置-右边连接地址（这个有唯一性的）和下面的启动设置看下，都填对了就一个没什么问题
当然我是蓝叠国际版，其他模拟器我不确定

**Comment by WSMTBG** [comment]
> maa设置-连接设置-右边连接地址（这个有唯一性的）和下面的启动设置看下，都填对了就一个没什么问题 当然我是蓝叠国际版，其他模拟器我不确定

艹打错了，【都填对了就一个没什么问题】--【都填对了就应该没什么问题】

**Comment by yd278** [comment]
> > maa设置-连接设置-右边连接地址（这个有唯一性的）和下面的启动设置看下，都填对了就一个没什么问题 当然我是蓝叠国际版，其他模拟器我不确定
> 
> 艹打错了，【都填对了就一个没什么问题】--【都填对了就应该没什么问题】

似乎不行，依然是两个MAA都能通过同一个地址连接到同一个模拟器实例然后争抢操作

**Comment by THSLP13** [comment]
我有个主意
MAA在开启或Link Start之后,依据adb地址生成一个hash
在系统提供的local/temp中写入一个诸如MAA_xxxxxxhash.lock的文件
然后占用这个文件,这样在其他相同adb地址的maa在检查到这个hash锁的时候可以尝试判断lock文件是否被占用
这样lock如果不存在/存在但不被占用,则认为没有maa在使用这个adb地址
如果存在被占用则认为这个地址正在被使用
然后maa更改地址/退出的时候删除这个lock
..
作为一个可行性探讨
