### ISSUE TITLE
设置中展开二级菜单滚动会导致整个页面回顶

### ISSUE THREAD

**Issue by FSPaul2498** [MaaAssistantArknights/MaaAssistantArknights#3769]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

当在设置选项卡内 展开一个较长的可滚动的二级菜单时（例如水月肉鸽的开局分队菜单、连接设置的连接配置菜单等），如果试图对这个菜单进行滚动，会导致整个设置页面回到顶部。不影响正常选择，选择后会自动向下回到选项焦点，仅属于GUI显示bug，可考虑修复优化一下

### 日志文件

GUI显示bug，无需日志。

**Comment by ABA2396** [comment]
这玩意不太好改，所以之前只能把这个显示长度设的尽可能大让他没有滚动条）

**Comment by ABA2396** [comment]
尝试失败了，等个大腿子（）

**Comment by ABA2396** [comment]
因为改了设置所以一级页面动不了了，也算是解决了.jpg
