### ISSUE TITLE
会客室技能识别错误

### ISSUE THREAD

**Issue by HeroTch** [MaaAssistantArknights/MaaAssistantArknights#377]
梅的基建技能是线索搜集beta和皇家探员，但是翻了一下log好像被识别成线索搜集alpha和皇家探员了
BlueStacks 5.6.110.1002(Hyper-V) 1600*900的分辨率
线索搜集（meet_spd）这个技能可能都识别错误了（？）
log 从2022/4/27 19:55:01 开始
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8571873/asst.log)

**Comment by MistEO** [comment]
确实有这个问题，感谢反馈。问题原因是以前线索搜集最高只有三级，不知道从什么版本改到四级了。~~鹰角坏事做尽！~~

之前的 `线索搜集beta`
![image](https://user-images.githubusercontent.com/18511905/165688798-1f290155-67dc-4f21-8b03-15bf1a1fcc1b.png)

现在的 `线索搜集 beta`
![image](https://user-images.githubusercontent.com/18511905/165689082-d367a386-1ff2-43f9-89d2-bb35b028f396.png)


会在之后的版本修复掉

**Comment by HeroTch** [comment]
> 确实有这个问题，感谢反馈。问题原因是以前线索搜集最高只有三级，不知道从什么版本改到四级了。~鹰角坏事做尽！~
> 
> 之前的 `线索搜集 beta` ![image](https://user-images.githubusercontent.com/18511905/165688798-1f290155-67dc-4f21-8b03-15bf1a1fcc1b.png)
> 
> 现在的 `线索搜集 beta` ![image](https://user-images.githubusercontent.com/18511905/165689082-d367a386-1ff2-43f9-89d2-bb35b028f396.png)
> 
> 会在之后的版本修复掉

提醒一下，风丸的线索搜集技能图标和`线索搜集 beta`相同（我暂时没有风丸，看prts两张图是一样的）
 | 化影 | 进驻会客室时，线索搜集速度提升15% | 
|  ----  | ----  |

但风丸只有15%的线索搜集速度，不知道有没有判断过

**Comment by MistEO** [comment]
v3.1.3 fixed

**Comment by MistEO** [comment]
> > 确实有这个问题，感谢反馈。问题原因是以前线索搜集最高只有三级，不知道从什么版本改到四级了。~鹰角坏事做尽！~
> > 之前的 `线索搜集 beta` ![image](https://user-images.githubusercontent.com/18511905/165688798-1f290155-67dc-4f21-8b03-15bf1a1fcc1b.png)
> > 现在的 `线索搜集 beta` ![image](https://user-images.githubusercontent.com/18511905/165689082-d367a386-1ff2-43f9-89d2-bb35b028f396.png)
> > 会在之后的版本修复掉
> 
> 提醒一下，风丸的线索搜集技能图标和`线索搜集 beta`相同（我暂时没有风丸，看prts两张图是一样的）
> 
> 化影	进驻会客室时，线索搜集速度提升15%
> 但风丸只有15%的线索搜集速度，不知道有没有判断过

现有的逻辑判断不了orz

只差 5%, 不打算弄了_(:з」∠)_
