### ISSUE TITLE
win mumu MAA进行生息演算无反应

### ISSUE THREAD

**Issue by Sagiri777** [MaaAssistantArknights/MaaAssistantArknights#3770]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在通过MAA进行生息演算刷取任务时无法正常开启任务，无正常点击操作

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10776506/asst.zip)
北京时间17：06分以后

### 截图

![MuMu20230219170824](https://user-images.githubusercontent.com/57796392/219939150-fda3852b-2d8e-44bd-a348-c429ace4b040.png)

**Comment by ntgmc** [comment]
![image](https://user-images.githubusercontent.com/74061867/219939240-1c447883-fd36-407b-a1de-c0b9374dc913.png)
