### ISSUE TITLE
关于appium的使用设想

### ISSUE THREAD

**Issue by ghost** [MaaAssistantArknights/MaaAssistantArknights#3772]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我还没使用过MAA，但是我也是一个脚本编写者，我没看到你们使用appium来进行操作

### 有什么好的想法？

我写了一套appium的操作脚本，但是没投入使用，我不确定appium server的adb命令操作是否会封号，所以大概来问问，本人只会python帮不了大伙忙，想抄代码也抄不了（不会C啊）

**Comment by Shawnsdaddy** [comment]
MAA不是有python 接口嘛，直接用？

**Comment by horror-proton** [comment]
MAA 可以使用多种控制方法, "adb" 指使用安卓的 `input` 命令, "[minitouch](https://github.com/DeviceFarmer/minitouch)" 工具操作 evdev 设备, "[MaaTouch](https://github.com/MaaAssistantArknights/MaaTouch)" 使用安卓的 `InputDevice`.
暂时没有迹象表明使用这些方法会提高封号的概率, 另外为了防止探测 MAA 的点击位置也包含有一定的随机性, (可能不是必要的). 

Appium 不是很了解, 它用的似乎是安卓的 `UiDevice`.
