### ISSUE TITLE
基建换班出现死循环

### ISSUE THREAD

**Issue by Zetros090** [MaaAssistantArknights/MaaAssistantArknights#3775]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建换班会来回在几个制造站循环

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10777356/asst.log)

### 截图

![QQ截图20230220001347](https://user-images.githubusercontent.com/74809363/219960455-dd1f5c13-fe1b-461a-beac-25bd864a20cf.png)

**Comment by m3gaf0rce** [comment]
我也偶尔会出现这样的情况，有一次我特意观察了一下是某个基建设施中只有一个对应技能的干员，心情14/24，已经在工作状态了，但就反复一直在选择进驻干员、返回里面循环。解决方法是停止当前任务，重新Start Link开始就恢复了。

**Comment by m3gaf0rce** [comment]
我也偶尔会出现这样的情况，有一次我特意观察了一下是某个基建设施中只有一个对应技能的干员，心情14/24，已经在工作状态了，但就反复一直在选择进驻干员、返回里面循环。解决方法是停止当前任务，重新Start Link开始就恢复了。

**Comment by MistEO** [comment]
v4.11.0-beta.2 fixed, 试试有没有用
