### ISSUE TITLE
Python自动抄作业接口可以支持神秘代码吗？

### ISSUE THREAD

**Issue by wuqs-net** [MaaAssistantArknights/MaaAssistantArknights#3776]
### 在提问之前...

- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

```python
asst.append_task('Copilot', {
    'filename': './GA-EX8-raid.json',
    'formation': False
})
```

在用Python接口调用抄作业的时候，好像只能指定本地json文件。

### 有什么好的想法？

能否支持在参数里直接指定神秘代码？像这样

```python
asst.append_task('Copilot', {
    'filename': 'maa://20312',
    'formation': False
})
```

**Comment by yd278** [comment]
可以自己写个函数去get `https://prts.maa.plus/copilot/get/{神秘代码数字}`

**Comment by MistEO** [comment]
好像确实可以支持一下
