### ISSUE TITLE
基建制造站和宿舍无法上人，上人卡死循环回到mfg0重新开始

### ISSUE THREAD

**Issue by LingYi520** [MaaAssistantArknights/MaaAssistantArknights#3778]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建制造站和宿舍无法上人，上人卡死循环回到mfg0重新开始，当没有合适干员时mfg0陷入死循环，即进入退出再进入再退出
（替maa作业一群群友1687571524代传）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10786869/asst.log)
日志文件

**Comment by MistEO** [comment]
v4.11.0-beta.2 fixed, 试试有没有用

**Comment by IT-amateur** [comment]
> v4.11.0-beta.2 fixed, 试试有没有用

宿舍换班还是在卡
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10796570/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10796571/gui.log)

**Comment by trustype** [comment]
模拟器内存太小就会卡 我刚遇到了 把模拟器内存调大就好了 不知道你是什么问题
