### ISSUE TITLE
水月肉鸽前几次战斗会自动暂停

### ISSUE THREAD

**Issue by weiamchen** [MaaAssistantArknights/MaaAssistantArknights#3779]
### 说说你遇到的问题？

水月肉鸽大约前三次战斗
都会在战斗开始后连续点击三次暂停
然后开启2倍速
之后就一直保持在暂停状态
手动取消暂停后会正常运行继续战斗
从约第四次战斗开始不再连续点击暂停

**Comment by MistEO** [comment]
提个 bug 发下日志
