### ISSUE TITLE
希望能添加对“支援机械”的特殊识别

### ISSUE THREAD

**Issue by yltx** [MaaAssistantArknights/MaaAssistantArknights#378]
如题  小车不比4星珍贵多了？
建议加上特殊识别  刚刚测试的时候出现了这个情况：
![image.png](https://s2.loli.net/2022/04/28/xCXZvJmLrqpdHkR.png)
软件选择了“快速复活”，但其实大部分更想要支援机械吧。

**Comment by Anonywp** [comment]
直接把支援机械列入五星TAG

**Comment by cglcv** [comment]
> 直接把支援机械列入五星TAG

z这样不行，五星tag会直接把时间拉满，然后支援机械必被划掉
还是得做一个一星tag的单独识别

**Comment by HansBug** [comment]
> z这样不行，五星tag会直接把时间拉满，然后支援机械必被划掉
> 还是得做一个一星tag的单独识别

是这样，支援机械建议单独做一个选项。
或者更复杂些的话，可以考虑允许设置一个优先度，比如机械、四星、五星、六星（考虑到六星齐全的玩家）的优先级分别是咋样的。
当然，还可以更更复杂一些，甚至引入仓检机制，结合预定策略来自动决策。
