### ISSUE TITLE
希望增加复刻活动自动遍历所有关卡的功能

### ISSUE THREAD

**Issue by H-XZ** [MaaAssistantArknights/MaaAssistantArknights#3783]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

复刻活动经常需要把所有关卡打一遍，希望可以增加一个功能使maa自动遍历一遍，出现失误自动退出进行下一关，全部完成后提示哪关需要重新打。

**Comment by WSMTBG** [comment]
突袭EX8不是要手动吗

**Comment by mathlover** [comment]
不如说让自动战斗支持若干个关卡组成的一个队列(
