### ISSUE TITLE
增加活动关卡中，非最终关卡的自动作战及汇报（如搓玉关卡

### ISSUE THREAD

**Issue by Eziodeng** [MaaAssistantArknights/MaaAssistantArknights#3786]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

rt，活动复刻时还在继续搓玉。
完成复刻关重打一遍之后掉落材料还有很多，想接着刷GA-4这种搓玉关
但是刷图时无法选择相应关卡，汇报时也提示无法识别
手动输入关卡名称也无法识别

### 有什么好的想法？

增加一些非最终关卡但有其他用途的关卡的关卡识别等

### 其他内容

![image](https://user-images.githubusercontent.com/49717931/220335685-810410db-6f28-4a10-9019-43c893858b9f.png)

**Comment by ABA2396** [comment]
活动关卡需要更新资源后才能上报，导航的话是只有后三关。这些都需要在更新版本之后才能用。
