### ISSUE TITLE
MAA Copilot报错：“请求网络服务错误！”

### ISSUE THREAD

**Issue by HeavanDine** [MaaAssistantArknights/MaaAssistantArknights#3788]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

当使用MAA Copilot的神秘代码时，MAA客户端会报告错误：“请求网络服务错误！”

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10794639/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/80468654/220378493-84cf16be-bb9d-4298-a117-39d9d434bbfd.png)

**Comment by ABA2396** [comment]
作业端存的位置变了，要v4.11.0-beta.1之后才能正常使用，更新测试版或者尝试下载文件后直接导入

**Comment by MistEO** [comment]
更新下
