### ISSUE TITLE
选择“退出 模拟器”报错

### ISSUE THREAD

**Issue by df4d** [MaaAssistantArknights/MaaAssistantArknights#3789]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选择完成后“退出 模拟器”，就会复现如下的报错提示框。

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10795109/debug.zip)

### 截图

![20230221233401](https://user-images.githubusercontent.com/88201634/220391732-d203c313-c0b2-46c4-a76a-3a0b1112d999.png)

### 还有别的吗？

模拟器：mumu 2.7.15.0（x64）
系统：Windows 10 企业版 LTSC 21H2

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/220408994-9ff8437a-bc2e-4408-a54a-733668b21bb1.png)

**Comment by weedi0** [comment]
> ![图像](https://user-images.githubusercontent.com/18511905/220408994-9ff8437a-bc2e-4408-a54a-733668b21bb1.png)

 蓝叠模拟器 Hyper-V 使用管理员权限打开maa可以正常拉起模拟器，但是无法完成退出模拟器。

**Comment by cenfusheng** [comment]
> > ![图像](https://user-images.githubusercontent.com/18511905/220408994-9ff8437a-bc2e-4408-a54a-733668b21bb1.png)
> 
> 蓝叠模拟器 Hyper-V 使用管理员权限打开maa可以正常拉起模拟器，但是无法完成退出模拟器。

参考在 #3960 中的答复，这是模拟器的问题，MAA暂无修复计划

**Comment by cenfusheng** [comment]
感谢反馈，玛丽说得对。
