### ISSUE TITLE
国际服肉鸽选择不了好友辅助干员

### ISSUE THREAD

**Issue by Frogepoge** [MaaAssistantArknights/MaaAssistantArknights#3790]
### 在提问之前...

- [ ] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选择了使用好友辅助干员也不行

### 日志文件

None

**Comment by searchcat** [comment]
这个功能在其他语言版本的软件包中也是不可用的
我认为RoguelikeRecruitImageAnalyzer的语言改变功能没有正常工作。
