### ISSUE TITLE
开始任务后无反应

### ISSUE THREAD

**Issue by Kagura-Nanaa** [MaaAssistantArknights/MaaAssistantArknights#3791]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa成功连接到模拟器,但是模拟器无动作,等待一段时间后显示任务出错.尝试切换其它两种触控模式均无效.mumux和蓝叠国际版都是一样的问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10798823/asst.log)

### 截图

![MAA_Ygi9oeipUS](https://user-images.githubusercontent.com/44108528/220487610-345ba4ea-8178-448f-a4de-995c5b823a8f.png)
![MAA_ra1ln0wnh6](https://user-images.githubusercontent.com/44108528/220487708-0da7d217-9c38-4355-8214-0904543cbef5.png)

**Comment by Kagura-Nanaa** [comment]
> 强制替换ADB试过了吗

替换的话maa会闪退,用管理员运行后打开仍然会闪退

**Comment by ABA2396** [comment]
要先关闭模拟器才能替换
