### ISSUE TITLE
增加公招只刷新功能

### ISSUE THREAD

**Issue by Snow-dash** [MaaAssistantArknights/MaaAssistantArknights#3792]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

在公招卷低于自定义数量时，只刷新tag消耗刷新次数，不进行三星公招。以此预留一些公招卷应对突发情况例如高级资深等情况。

**Comment by zzyyyl** [comment]
你是否需要：
![image](https://user-images.githubusercontent.com/74587068/220495477-03c4339f-49e4-443b-aa46-2f85e2096b06.png)

**Comment by WSMTBG** [comment]
自动确认关了就行
【设置】-【自动公招】

**Comment by Snow-dash** [comment]
> 你是否需要： ![image](https://user-images.githubusercontent.com/74587068/220495477-03c4339f-49e4-443b-aa46-2f85e2096b06.png)

。。。很有道理，如果能自动化当然还是比较好，这个issue我还是关了吧
