### ISSUE TITLE
V4.11.0-beta.2版本关卡选择中没有

### ISSUE THREAD

**Issue by mkyO513** [MaaAssistantArknights/MaaAssistantArknights#3793]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新到最新版本的公测版后，选择关卡界面没有吾导先路的相关关卡。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10799203/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/48001545/220497449-35e20388-477f-43aa-842b-9b2cef5a15b3.png)

### 还有别的吗？

模拟器：蓝叠5国际版

**Comment by ABA2396** [comment]
关卡是网上下载的，要是开的时候网络不畅会下不下来，重启一下试试。

**Comment by ABA2396** [comment]
关卡是网上下载的，要是开的时候网络不畅会下不下来，重启一下试试。

**Comment by mkyO513** [comment]
非常感谢，我去尝试一下
