### ISSUE TITLE
EN服刷理智选择当前/上次后任务出错

### ISSUE THREAD

**Issue by SeeleC** [MaaAssistantArknights/MaaAssistantArknights#3794]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

EN服开始刷理智后日志出现两次任务出错，然后直接提示任务完成。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10800219/asst.zip)
时间：2023-02-22 12:59:00.409至2023-02-22 13:00:40.514

### 还有别的吗？

模拟器：mumu模拟器2.7.17.0
系统：windows11 22h2 build22621.1265

**Comment by ABA2396** [comment]
我看日志里关卡选择的是1-7啊

**Comment by SeeleC** [comment]
> 我看日志里关卡选择的是1-7啊

MAA更新到v4.11.0后问题已解决
