### ISSUE TITLE
使用 Android 虚拟显示以更好地适配分辨率

### ISSUE THREAD

**Issue by Mufanc** [MaaAssistantArknights/MaaAssistantArknights#3797]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

Android 提供了一个 [VirtualDisplay](https://developer.android.com/reference/android/hardware/display/VirtualDisplay) 功能用于创建虚拟显示，已经有一些应用（[如米窗](https://github.com/sunshine0523/Mi-FreeForm/blob/e81c2791029feccd7d657fca4bd23d1e0dfd638e/app/src/main/java/com/sunshine/freeform/ui/freeform/FreeformView.kt#L304-L311)）利用这一特性来实现特殊功能，由于创建时可以任意指定虚拟显示的尺寸，所以或许能够借此绕过设备本身分辨率的限制，实现所有设备上的统一。此外 scrcpy 也 [支持](https://github.com/Genymobile/scrcpy#display) 指定 `displayId`，所以预览屏幕应该也不成问题（？

### 其他内容

我对 MAA 的架构还不太了解，希望各位佬们看看这套方案是否可行

**Comment by AnnAngela** [comment]
看起来这玩意似乎必须在app里才能使用，adb是不能调用的，难不成需要写个helper app？

**Comment by AnnAngela** [comment]
那能麻烦大佬写个pr吗，感激不尽

**Comment by Mufanc** [comment]
抱歉我的电脑是 Manjaro 系统，没法走正常流程编译了，另外对 C++ 也不是很熟悉 (╥﹏╥)，不过如果需要做成像 MaaTouch 那样的子模块我可以尽力提供帮助

**Comment by AnnAngela** [comment]
> 抱歉我的电脑是 Manjaro 系统，没法走正常流程编译了，另外对 C++ 也不是很熟悉 (╥﹏╥)，不过如果需要做成像 MaaTouch 那样的子模块我可以尽力提供帮助

对的，就是希望能有个子模块提供调用，如果可以的话麻烦大佬了

**Comment by Mufanc** [comment]
简单封装了一下，调用示例在 [这里](https://github.com/Mufanc/MaaScreen/blob/master/scripts/demo.py)，把 `deploy_apk` 里的内容换成直接 push 编译好的 apk 就行了，apk 可以在 [Actions](https://github.com/Mufanc/MaaScreen/actions) 里边下载到。另外模拟输入部分 `InputEvent` 的 `setDisplayId()` 是在 [这个提交](https://cs.android.com/android/_/android/platform/frameworks/base/+/91fa08ff1bd85ae41d71e1ed5ee72357c975ee3b) 才引入的，所以把支持的版本定在了 Android 10+ ，不知道对模拟器来说是否太过先进了

**Comment by AnnAngela** [comment]
> 简单封装了一下，调用示例在 [这里](https://github.com/Mufanc/MaaScreen/blob/master/scripts/demo.py)，把 `deploy_apk` 里的内容换成直接 push 编译好的 apk 就行了，apk 可以在 [Actions](https://github.com/Mufanc/MaaScreen/actions) 里边下载到。另外模拟输入部分 `InputEvent` 的 `setDisplayId()` 是在 [这个提交](https://cs.android.com/android/_/android/platform/frameworks/base/+/91fa08ff1bd85ae41d71e1ed5ee72357c975ee3b) 才引入的，所以把支持的版本定在了 Android 10+ ，不知道对模拟器来说是否太过先进了

emmm，现在好多模拟器还在 7 和 9，得先测试一下。

**Comment by AnnAngela** [comment]
Close as not planned.

**Comment by Mufanc** [comment]
https://www.bilibili.com/video/BV1fNcBz4EfF/
放一个 reference，已经实现
