### ISSUE TITLE
无法清理智

### ISSUE THREAD

**Issue by zlqd123** [MaaAssistantArknights/MaaAssistantArknights#380]
蓝叠5国际版，pie64客户端，nougat64引擎。
除清理智外，其他功能均正常。
清理智时不管是上次作战还是当前关卡，显示正常但不进入关卡，过段时间会报错。

[上次作战.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8584012/default.log)
[当前关卡.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8584013/default.log)

Thanks♪(･ω･)ﾉ

**Comment by zlqd123** [comment]
顺带一提，蓝叠国际版需要adb输端口

**Comment by MistEO** [comment]
和 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/365 是同一个问题，已经修复了，下一个版本提现~

**Comment by MistEO** [comment]
v3.1.3 fixed
