### ISSUE TITLE
MacBook一直显示无法连接但是系统显示能识别

### ISSUE THREAD

**Issue by CCria** [MaaAssistantArknights/MaaAssistantArknights#3801]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

一直显示无法连接，但是并不是macbook没有adb环境的原因并且terminal里面是可以识别mumu模拟器的(虽然不知道为什么有两个）。

### 日志文件

/

### 截图

这个地方没有可以选择路径的地方，但感觉可能是因为macbook本来就没有？
<img width="899" alt="Screenshot 2023-02-22 at 23 15 04" src="https://user-images.githubusercontent.com/72633443/220667088-16fd18ab-0a38-44e8-ac79-c4cd16f8b355.png">

一直显示无法连接
<img width="300" alt="Screenshot 2023-02-22 at 23 14 54" src="https://user-images.githubusercontent.com/72633443/220667100-719f46b3-1e45-480b-ae6b-4c3d6de2c336.png">

但是terminal里面是可以识别adb的（用的是homebrew，模拟器是mumu）
<img width="198" alt="Screenshot 2023-02-22 at 23 15 48" src="https://user-images.githubusercontent.com/72633443/220667189-0af25a07-5c2e-44ac-971d-e1ad03a03986.png">

**Comment by ABA2396** [comment]
mumu不是7555吗？或者试试那个emulator-5554的缺省端口

**Comment by CCria** [comment]
我刚才重启了一下mumu然后就识别不到了，所以估计是adb的问题（但是csdn上面确实是说mumu识别出来是emulator-5554），然后就这样了。。。
<img width="459" alt="Screenshot 2023-02-22 at 23 53 40" src="https://user-images.githubusercontent.com/72633443/220679643-5770a70b-f803-47cb-a689-8695c69e57c2.png">

然后我尝试重启了一下homebrew结果又可以了，有点抽象
<img width="510" alt="Screenshot 2023-02-22 at 23 54 17" src="https://user-images.githubusercontent.com/72633443/220679657-03a0c3a1-f65d-499a-8313-421bc47acc35.png">

（以及dalao，缺省端口要怎么查啊）

**Comment by ABA2396** [comment]
emulator-5554就是 Android 模拟器的默认端口。adb devices 命令是不会显示没用过的端口的，所以你得先知道mumu的端口号，然后再 adb connect，去mumu那里找找有没有文档说明吧
