### ISSUE TITLE
刷理智时卡在战斗结算界面

### ISSUE THREAD

**Issue by sustainably-momomo** [MaaAssistantArknights/MaaAssistantArknights#3803]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷理智时多次出现游戏停留在战斗结算界面，MAA提示“游戏崩溃，重新启动”，之后显示任务失败，后面的所有任务都会失败。模拟器可以正常点击，重新运行MAA可以正常完成任务，无法稳定触发bug。

尝试过更换触控模式，一开始使用的是adb input，几次出现问题后换成了maaTouch，没有发现该问题，但有时会出现基建换班跳过某一个制造站的问题，所以换成了miniTouch，使用了一段时间后又发现了该问题。

通常在我电脑息屏挂机时出现，有人在守着的时候没出现过。

### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10810228/asst.-.log)
MAA报错时间为02-23 06：44：39

### 截图

![E5 )IWTJ(L%$MQE67N)EWAE](https://user-images.githubusercontent.com/126134725/220821431-391594ee-fa37-477e-aa75-bfb9ef329021.png)

### 还有别的吗？

使用mumu模拟器，win10系统，触控方式miniTouch（adb input也出现过，maaTouch暂时未发现）MAA版本v4.11.0-beta-2

**Comment by zzyyyl** [comment]
看起来跟 #3758 差不多，大概是 #3773 里修的问题
