### ISSUE TITLE
增加多开实例管理功能

### ISSUE THREAD

**Issue by IntangibleW** [MaaAssistantArknights/MaaAssistantArknights#3804]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我使用的是 Bluestacks Hyper-V support Pie 核心模拟器
单个MAA进程只能管理一个模拟器实例，在有多开需求时只能开多个MAA分别指定端口连接模拟器实例

### 有什么好的想法？

在MAA管理面板中增加多实例管理功能，能根据不同实例指定不同的任务列表

**Comment by ABA2396** [comment]
新ui支持了，老ui不准备做多实例了，等新版本吧（）
