### ISSUE TITLE
狗粮本刷取错误

### ISSUE THREAD

**Issue by yltx** [MaaAssistantArknights/MaaAssistantArknights#381]
BlueStacks5 国际版 5.7.0.1065 N64
如果我先自己挂一局LS-5，然后选择“上次作战”，就可以正常挂机；
如果直接选择“经验-5”，就会挂机失败；
如果选择“技能-5”，也能正常挂机。
推测为版本更新后，经验本的关卡曲线下调，导致原来的位置识别不到“LS-5”了。

**Comment by yltx** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8587417/asst.log)
里面掺和了一些基建之类的内容，但我实在是不想一条条翻了（

**Comment by MistEO** [comment]
是因为留第 6 关留了空，位置变了。这个问题已经修复了，但还没有发版。预计这几天会发布~

**Comment by MistEO** [comment]
v3.1.3 fixed
