### ISSUE TITLE
复刻活动自动做通关任务

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#3810]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在复刻活动的时候增加一个选项自动导航完成通过关卡任务。

### 有什么好的想法？

因为复刻活动是保留之前自律的所以可以直接一个一个点过去就行。

**Comment by lastxxx2** [comment]
没必要，ex8突袭也有紫票，做个半成品不如不做

**Comment by ChildeRolando** [comment]
> 没必要，ex8突袭也有紫票，做个半成品不如不做

ex8突袭不也可以代理吗

**Comment by cenfusheng** [comment]
隔壁明日方舟速通有对非ex关的按顺序通关，具体见那边的文档 https://arklights.pages.dev/guide.html 。
maa这边由于实现方法不同，不会去做那么大量的寻路。
