### ISSUE TITLE
肉鸽开局选干员扫描时有几率会跳过一列导致无法找到部分干员

### ISSUE THREAD

**Issue by SaarChaffee** [MaaAssistantArknights/MaaAssistantArknights#3811]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我肉鸽的设置是近卫队-取长补短-百嘉，但maa读了两次干员列表后选了羽毛笔

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10813316/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/53519746/220901721-488f1a84-0da3-4d70-8253-0e3d5f2697e8.png)

### 还有别的吗？

模拟器：mumu12

**Comment by zzyyyl** [comment]
日志显示 maa 没找到百嘉

日志里依次找到的干员如下：
赫拉格, 杰克, 星极, 史尔特尔, 山, 耀骑士临光, 布洛卡, 鞭刃
玛恩纳, 棘刺, 煌, 重岳
柏喙, 银灰, 陈, 斯卡蒂
拉普兰德, 阿米娅, 海沫, 芙兰卡, 炎客, 幽灵鲨, 羽毛笔, 暴行
战车, 赤冬, 达格达, 龙舌兰

**Comment by SaarChaffee** [comment]
> 日志显示 maa 没找到百嘉
> 
> 日志里依次找到的干员如下： 赫拉格, 杰克, 星极, 史尔特尔, 山, 耀骑士临光, 布洛卡, 鞭刃 玛恩纳, 棘刺, 煌, 重岳 柏喙, 银灰, 陈, 斯卡蒂 拉普兰德, 阿米娅, 海沫, 芙兰卡, 炎客, 幽灵鲨, 羽毛笔, 暴行 战车, 赤冬, 达格达, 龙舌兰

我的百嘉在默认排序下是这个位置
![image](https://user-images.githubusercontent.com/53519746/220911811-d340169d-792a-4b46-8a23-290c682a134c.png)

**Comment by SaarChaffee** [comment]
> 日志显示 maa 没找到百嘉
> 
> 日志里依次找到的干员如下： 赫拉格, 杰克, 星极, 史尔特尔, 山, 耀骑士临光, 布洛卡, 鞭刃 玛恩纳, 棘刺, 煌, 重岳 柏喙, 银灰, 陈, 斯卡蒂 拉普兰德, 阿米娅, 海沫, 芙兰卡, 炎客, 幽灵鲨, 羽毛笔, 暴行 战车, 赤冬, 达格达, 龙舌兰

我试试把mumu12的高刷关掉，不知道是不是这个原因引起的

**Comment by SaarChaffee** [comment]
> > 日志显示 maa 没找到百嘉
> > 日志里依次找到的干员如下： 赫拉格, 杰克, 星极, 史尔特尔, 山, 耀骑士临光, 布洛卡, 鞭刃 玛恩纳, 棘刺, 煌, 重岳 柏喙, 银灰, 陈, 斯卡蒂 拉普兰德, 阿米娅, 海沫, 芙兰卡, 炎客, 幽灵鲨, 羽毛笔, 暴行 战车, 赤冬, 达格达, 龙舌兰
> 
> 我试试把mumu12的高刷关掉，不知道是不是这个原因引起的

问题没解决。
但刚刚有个情况，如果百嘉出现在临时干员里面，它是能正常选的，之后我又开了一把，这次百嘉不在临时干员里面，maa又不认了。

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10813712/asst.log)

**Comment by zzyyyl** [comment]
方便测试么？
我觉得可能是滑动距离过长了，可以试试把 `resource\tasks.json` 中的
`"RoguelikeRecruitOperListSlowlySwipeToTheLeft" - "specificRect"` 的第一项改成 600 然后重启 maa 试试

**Comment by SaarChaffee** [comment]
> 方便测试么？ 我觉得可能是滑动距离过长了，可以试试把 `resource\tasks.json` 中的 `"RoguelikeRecruitOperListSlowlySwipeToTheLeft" - "specificRect"` 的第一项改成 600 然后重启 maa 试试
> 
> ![image](https://user-images.githubusercontent.com/74587068/220915397-a3b00f42-4619-4919-8083-6ddad3437dd3.png)

试了下，还是不行。百嘉的框没有完整出现过，是这个原因吗
![image](https://user-images.githubusercontent.com/53519746/220917027-1a0bcae5-7978-488f-a62a-3449c1db2fd6.png)

**Comment by zzyyyl** [comment]
那再改小点（

``` json
        "specificRect": [
            620,
            340,
            20,
            20
        ],
        "rectMove": [
            1100,
            340,
            20,
            20
        ]
```

> 是因为百嘉的框没有完整出现过吗

是的，如果左边的等级和他的名字没有出现在同一次识别中，他就会被跳过

**Comment by zzyyyl** [comment]
为了保证每次滑动至少多出一列 且 不能跳过一列，应保证滑动距离在400-500之间。（上面的红线是应保证的最短距离≈400，下面的红线是应保证的最长距离≈500）
![image](https://user-images.githubusercontent.com/74587068/220917755-0c3eaf7b-49f1-4d0c-b3d5-e097165e9d0c.png)

**Comment by SaarChaffee** [comment]
我用排列表最后面的人试了下，没有跳过了一列的情况出现了，但是maa不会滑到最后面去
