### ISSUE TITLE
'MaaWpfGui.SettingsViewModel' 的類型初始設定式發生例外狀況。

### ISSUE THREAD

**Issue by 520firewire520** [MaaAssistantArknights/MaaAssistantArknights#3813]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

版本信息是win10专业版，64位元，x64处理器
解压缩完成后就一直无法开启，出现这个介面，重开机也不行

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10815465/gui.log)

### 截图

![bug](https://user-images.githubusercontent.com/126182822/220956699-bbfbaa9c-2992-409f-a2a9-c2671dc2e10a.png)

### 还有别的吗？

无

**Comment by ABA2396** [comment]
DllNotFoundException，看看是不是缺少运行库文件，[文档](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html)中有对应的链接

**Comment by 520firewire520** [comment]
两个运行库的东西都下载好了，问题同样没有解决QAQ
