### ISSUE TITLE
似乎《生息演算》模式进行一段时间以后一定会卡主的样子

### ISSUE THREAD

**Issue by AkiraChisaka** [MaaAssistantArknights/MaaAssistantArknights#3814]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

似乎自动刷生息演算的话，一定会进行一段时间以后自动卡主的样子。

不太知道为什么会卡主。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10816847/asst.zip)

### 截图

![image](https://user-images.githubusercontent.com/47231500/220993443-32c111ef-03df-4f69-9608-78b95c5fb1d1.png)

### 还有别的吗？

模拟器是蓝叠。

**Comment by WLLEGit** [comment]
应该是两点半左右方舟闪退了，闪退确实是没做处理，等会儿看看好不好加上。

**Comment by AkiraChisaka** [comment]
> 应该是两点半左右方舟闪退了，闪退确实是没做处理，等会儿看看好不好加上。

的确，应该只是模拟器崩溃了。
