### ISSUE TITLE
基建换班过程中掉线，自动重连后跳过了部分设施

### ISSUE THREAD

**Issue by liuyifan-eric** [MaaAssistantArknights/MaaAssistantArknights#3815]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://user-images.githubusercontent.com/44556003/221046646-d1b38b99-65cf-4e77-8ea0-80a9e2bc9985.png)
如图，掉线后重连跳过了Power 2（以及power 1其实也没换上）

用的是日服，基于4.11.0的有修改过的版本（但是应该不影响换班逻辑），应该可以通过手动顶号复现

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10819108/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10819118/gui.log)

**Comment by NicholasYZ** [comment]
今天也碰到了，可以考虑优化成掉线重连后重新执行基建任务之类的，用的是官服

**Comment by qiopgh** [comment]
我也是这样,只能设置多运行几次maa减少因为掉线导致无法换班的情况
