### ISSUE TITLE
建议公开招募四星tag选中多个

### ISSUE THREAD

**Issue by NickerGrylls** [MaaAssistantArknights/MaaAssistantArknights#3819]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在公招出四星时，有不小的概率同时出现两个及以上的四星tag
目前MAA只会选择1个四星tag
此时其是有概率被划掉的，造成博朗台的损失
而若是同时选择两个（及以上）的四星tag，至少我还没见过全部被划掉的情况

### 有什么好的想法？

建议识别到出四星时，选中所有的四星tag（不含组合tag）

### 其他内容

![image](https://user-images.githubusercontent.com/120347871/221332899-bcf5fd05-824b-4b1c-a5ce-7104a4b822c2.png)

**Comment by zzyyyl** [comment]
First mentioned in #92, see also #2410

**Comment by zzyyyl** [comment]
总结一下：
现在 MAA Team 应该近期不会做这个 #2410
如果有人愿意做的话可以开放为一个选项 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/92#issuecomment-1004940487
另外建议只对单个就能出高星干员Tag执行此操作 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2410#issuecomment-1288454046 ，https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2608#issuecomment-1304542258

相关 issue：
#92, #2410(closed), #2608, #2112(closed), #3589

**Comment by zzyyyl** [comment]
> 多选确实能极大降低划4星的情况，我每次都多选，一年只出现过一次3个tag都被划掉。且并没有出现过划掉4星留3星的情况，这可能是有什么机制在的。

划掉4星留3星并不是没有，而且应该也不少见（
下次我遇到了截个图

**Comment by HydrogenDeuterium** [comment]
> > 多选确实能极大降低划4星的情况，我每次都多选，一年只出现过一次3个tag都被划掉。且并没有出现过划掉4星留3星的情况，这可能是有什么机制在的。
> 
> 划掉4星留3星并不是没有，而且应该也不少见（ 下次我遇到了截个图

感觉可以让maa收集一下数据，看看收公招的时候选中tag与实际出来结果的关系？

**Comment by liuyifan-eric** [comment]
> > > 多选确实能极大降低划4星的情况，我每次都多选，一年只出现过一次3个tag都被划掉。且并没有出现过划掉4星留3星的情况，这可能是有什么机制在的。
> 
> > 
> 
> > 划掉4星留3星并不是没有，而且应该也不少见（ 下次我遇到了截个图
> 
> 
> 
> 感觉可以让maa收集一下数据，看看收公招的时候选中tag与实际出来结果的关系？

那也得先支持了这个功能才能收集吧，而且企鹅物流没有的话如何收集也是个大问题吧（
