### ISSUE TITLE
这个项目支持手操打代理吗？

### ISSUE THREAD

**Issue by yltx** [MaaAssistantArknights/MaaAssistantArknights#382]
如题，看b站上全自动OD-EX-8突袭的视频过来的，结果我尝试让他打“标准 10-2”的代理（我“磨难 10-2”都有代理，没道理抄不到作业，选的是“当前关卡”），结果他直接尝试点“代理指挥”，提示没解锁之后管都没管就直接开始战斗了……是我打开方式错了吗？

**Comment by MistEO** [comment]
还没有上线正式版本，敬请期待~

**Comment by yltx** [comment]
> 还没有上线正式版本，敬请期待~

那没事了（

**Comment by yltx** [comment]
> 还没有上线正式版本，敬请期待~

快端上来罢，或者起码指一下是4.0.0-beta还是啥版本啊，大不了我自己编译去（
等着这玩意儿开荒3周年活动呢

**Comment by MistEO** [comment]
supported

**Comment by yltx** [comment]
> supported

什么时候更新肉鸽啊  现版本的肉鸽看着真的让人血压上升
