### ISSUE TITLE
繁中服傀影肉鸽在使用非adb input的触摸方式时无法正常进行肉鸽战斗

### ISSUE THREAD

**Issue by Realmajia** [MaaAssistantArknights/MaaAssistantArknights#3821]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

其实这个问题从4.9.X左右版本就有出现了。我一直因为是我使用夜神模拟器导致的问题。但是最近改换了bluestacks5和使用最新版maa该问题依然存在。
具体表现为正常开局一场肉鸽后，在第一场战斗开始后部署干员“山”时会不停的点按界面左上角的齿轮按钮导致游戏暂停和游戏恢复，最终在不停的暂停恢复中未能部署干员的情况下结束战斗。

我自己尝试过各种更改分辨率和dpi等方法，问题依然存在，直到刚才我把maa设置中的touch mode切换为了adb input之后能够顺利的在战斗中部署干员并正常推进肉鸽进程了。

不过adb input的操作效率和反应速度确实慢的多。还请有能力的大佬帮忙排查错误。感谢！
[asst - kyrgbug.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10831146/asst.-.kyrgbug.log)

### 日志文件

[asst - kyrgbug.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10831148/asst.-.kyrgbug.log)

### 截图

![image](https://user-images.githubusercontent.com/105563281/221357198-1cc708e2-3bdc-4b32-8f0e-baf440f30d60.png)
![2023-02-25_19-52-41-731_raw](https://user-images.githubusercontent.com/105563281/221357206-8ba18c28-c203-4442-8f04-ffad557f662b.png)

**Comment by liuyifan-eric** [comment]
你打开暂停部署干员了吗？没记错的话貌似外服本身就不能暂停部署干员来着

**Comment by Realmajia** [comment]
> 你打开暂停部署干员了吗？没记错的话貌似外服本身就不能暂停部署干员来着

![image](https://user-images.githubusercontent.com/105563281/221367268-2eb20238-bdcf-4aed-8eee-5d60eb1b6ccd.png)
原来是这样！我一直想当然的认为和国服一样是按右上角的暂停可以布置。这下盲点了！XD
