### ISSUE TITLE
有机会因为医疗干员阻挡小怪导致无法通关

### ISSUE THREAD

**Issue by 520firewire520** [MaaAssistantArknights/MaaAssistantArknights#3823]
### 说说你遇到的问题？

在一些关卡因为高台干员可以部署于地面，又因医疗干员放置于输出干员前面，且输出干员无攻击至小怪的能力，可能导致卡关，导致游戏无法持续进行
![20230226_035635](https://user-images.githubusercontent.com/126182822/221377299-4f84fef6-158f-47ba-8579-9c2aced326f2.jpg)
改善建议:这种关卡可以禁止医疗干员

**Comment by MistEO** [comment]
超过 8 分钟就自动全撤了，不会卡的
