### ISSUE TITLE
调用外部命令时卡住

### ISSUE THREAD

**Issue by LFWQSP2641** [MaaAssistantArknights/MaaAssistantArknights#3824]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

当上传请求过稳定性不好的代理,可能因为没有相应的response,会一直卡在
Assistant::append_callback | TaskChainCompleted {"taskchain":"Fight","taskid":8,"uuid":"664f474c91eb22ef"}

日志中17791行的request好像没有对应的response

### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10831723/asst.-.log)

**Comment by LFWQSP2641** [comment]
也有可能找错了,SLT不熟,没看源码

**Comment by LFWQSP2641** [comment]
也有可能是我问题找错了,SLT不熟,没看源码

**Comment by LFWQSP2641** [comment]
不过当代理使用"GWF"路由时,几乎没出现过这个BUG
使用"绕过大陆"路由有一成左右的几率出现这个BUG

**Comment by liuyifan-eric** [comment]
这就是你代理的问题吧？相当于你代理出问题的时候加载网页不会404而是一直加载中
我不是很懂这方面说错了请无视

**Comment by LFWQSP2641** [comment]
但是也不应该一直开在
Assistant::append_callback | TaskChainCompleted {"taskchain":"Fight","taskid":8,"uuid":"664f474c91eb22ef"}
这里啊

**Comment by LFWQSP2641** [comment]
> 这就是你代理的问题吧？相当于你代理出问题的时候加载网页不会404而是一直加载中 我不是很懂这方面说错了请无视

≡(▔﹏▔)≡但是也不应该一直卡在Assistant::append_callback | TaskChainCompleted {"taskchain":"Fight","taskid":8,"uuid":"664f474c91eb22ef"}

**Comment by LFWQSP2641** [comment]
> 这就是你代理的问题吧？相当于你代理出问题的时候加载网页不会404而是一直加载中 我不是很懂这方面说错了请无视

如果卡在"一直加载中"的话,最后应该判定为超时并放弃吧

**Comment by LFWQSP2641** [comment]
上传应该是卡在了master\src\MaaCore\Task\ReportDataTask.cpp的第[203](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/src/MaaCore/Task/ReportDataTask.cpp#L203)行
`std::string response = utils::call_command(cmd_line);`

**Comment by LFWQSP2641** [comment]
主线程是卡在Assistant::working_proc()了?

**Comment by liuyifan-eric** [comment]
咱就是说，有没有一种可能，是你的代理有问题，哪怕你手动打开浏览器输入企鹅物流也会卡加载？

**Comment by LFWQSP2641** [comment]
> 然后你发的这卡住的地方毫无意义……

确实,就是看看源码玩玩

**Comment by LFWQSP2641** [comment]
> 咱就是说，有没有一种可能，是你的代理有问题，哪怕你手动打开浏览器输入企鹅物流也会卡加载？

但是我还是认为,即使代理有问题,也不应该导致整个MaaCore卡住

**Comment by liuyifan-eric** [comment]
你看看你打开个境外网站是404还是卡加载？别纠结了，把你代理关了就行

**Comment by LFWQSP2641** [comment]
> GFW就是防火长城，企鹅物流不在这个名单里，你的请求都不会经过代理，当然不会有问题 你用绕过大陆，那你的请求经过vpn，然后你的vpn又挂了，那当然就会这样。不信你这时候随便开个境外网站看看能不能打开？

我的问题不是为什么上传失败,而是会卡住MaaCore主线程

**Comment by MistEO** [comment]
不是卡住，是有限的等待，企鹅要求的。。

**Comment by LFWQSP2641** [comment]
好吧╮(╯-╰)╭

**Comment by MistEO** [comment]
他们要求做个退避策略。第一次失败后，等待 10s，再失败，等待 15 秒，每次 1.5 倍增长，最多重试 10 次（还是 8 次，忘了），如果一直失败总的会等十多分钟

**Comment by MistEO** [comment]
这段逻辑在 ReportData.cpp 里

**Comment by LFWQSP2641** [comment]
> 他们要求做个退避策略。第一次失败后，等待 10s，再失败，等待 15 秒，每次 1.5 倍增长，最多重试 10 次（还是 8 次，忘了），如果一直失败总的会等十多分钟

为什么不失败次数过多就放弃呢,有一次vpn挂了,卡了两个小时

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/222507457-c41bc797-98e1-4014-b699-c80e29224739.png)

另外你说的 response 在下面，这个是异步的来着，可以按线程号看下

**Comment by MistEO** [comment]
哦不对，17791，看错了，我以为 17991 _(:з」∠)_

**Comment by MistEO** [comment]
确实有问题，调用外部命令死在这里了，curl 我们是带了 10 秒超时参数的，死在里面是不符合预期的

**Comment by LFWQSP2641** [comment]
> 他们要求做个退避策略。第一次失败后，等待 10s，再失败，等待 15 秒，每次 1.5 倍增长，最多重试 10 次（还是 8 次，忘了），如果一直失败总的会等十多分钟

最多重试20次,一直失败会等12个半小时

**Comment by LFWQSP2641** [comment]
时间太长了吧,建议减小retryTime

**Comment by LFWQSP2641** [comment]
看戳了,是5次

**Comment by LFWQSP2641** [comment]
> 确实有问题，调用外部命令死在这里了，curl 我们是带了 10 秒超时参数的，死在里面是不符合预期的

所以说只有这个bug吧. 并且我看了下,卡住的时候curl.exe并没有运行

**Comment by LFWQSP2641** [comment]
BUG被触发时,[asst::platform::call_command(const std::string& cmdline, bool* exit_flag)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/f18fc27972b765b8be1b45218c294f7133480bc8/src/MaaCore/Utils/Platform/PlatformWin32.cpp#L123)的process_info.hProcess总是比pipeov.hEvent先完成,然后pipeov.hEvent完成之后,再循环一次就卡在[WaitForMultipleObjectsEx](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/f18fc27972b765b8be1b45218c294f7133480bc8/src/MaaCore/Utils/Platform/PlatformWin32.cpp#L173)这里了

**Comment by LFWQSP2641** [comment]
正常情况下应该是pipeov.hEvent比process_info.hProcess先完成

**Comment by LFWQSP2641** [comment]
> BUG被触发时,[asst::platform::call_command(const std::string& cmdline, bool* exit_flag)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/f18fc27972b765b8be1b45218c294f7133480bc8/src/MaaCore/Utils/Platform/PlatformWin32.cpp#L123)的process_info.hProcess总是比pipeov.hEvent先完成,然后pipeov.hEvent完成之后,再循环一次就卡在[WaitForMultipleObjectsEx](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/f18fc27972b765b8be1b45218c294f7133480bc8/src/MaaCore/Utils/Platform/PlatformWin32.cpp#L173)这里了

等效代码
```
WaitForSingleObjectEx(process_info.hProcess, INFINITE, TRUE);
WaitForSingleObjectEx(pipeov.hEvent, INFINITE, TRUE);
GetOverlappedResult(pipe_parent_read, &pipeov, &len, FALSE);
WaitForSingleObjectEx(pipeov.hEvent, INFINITE, TRUE);    // 卡在这里
```
