### ISSUE TITLE
建议新增识别box并分类指出缺哪个干员，我现在想找缺哪个5星得翻挺长时间wiki

### ISSUE THREAD

**Issue by shiguang2016** [MaaAssistantArknights/MaaAssistantArknights#3825]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在我241干员，缺哪些6星我自己基本清楚，但是至于哪些5星没有就非常麻烦，关系网也不是很好用

### 有什么好的想法？

因为本身的ocr技术识别干员就已经实现了，识别全部干员指出哪个没有应该也比较容易实现吧
比如生成报告之后就可以顺便帮对照一下周年6星自选的列表，还是非常方便的
如果能导出清单，附带等级潜能等内容，就可以实现和别的养成数据站联动了

**Comment by MistEO** [comment]
现在有了
