### ISSUE TITLE
关于真机运行时触控模拟被 SELinux 拦截的问题

### ISSUE THREAD

**Issue by Mufanc** [MaaAssistantArknights/MaaAssistantArknights#3829]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

AOSP 在 [这个提交](https://android-review.googlesource.com/c/platform/system/sepolicy/+/740561) 中修改了 SELinux 规则，阻止 shell 直接向 `/dev/input/*` 写入数据，在启用了 SELinux 的真机运行时，会导致 avc：

```
type=1400 audit(0.0:51988): avc: denied { write } for name="event9" dev="tmpfs" ino=1621 scontext=u:r:shell:s0 tcontext=u:object_r:input_device:s0 tclass=chr_file permissive=0
```

然而 [文档](https://maa.plus/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.html#%E2%9A%99%EF%B8%8F-%E6%89%8B%E6%9C%BA%E3%80%81%E5%B9%B3%E6%9D%BF%E7%AD%89%E9%9D%9E-16-9-%E5%88%86%E8%BE%A8%E7%8E%87%E8%AE%BE%E5%A4%87) 中并未提及相关信息，可能会导致一些人在真机运行时出现问题（比如我在 Arch Linux 运行时，控制台只会报「连接失败」，日志也只有 `Permission Denied`，很不明朗）

### 有什么好的想法？

大概想到几个方案：

* 上策：重构模拟输入的部分，使用 [系统提供的 API](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/hardware/input/InputManager.java#1140) 来模拟输入，而不是直接读写 `/dev/input` 下的字符设备 ~~（好像工作量太大了）~~

* 中策：对于有 Magisk 的设备，可以添加一条 SELinux 规则：

```bash
magiskpolicy --apply <(echo 'allow shell input_device chr_file { write }') --live
```

* 下策：临时禁用 SELinux（不推荐，会带来很大的安全问题）：

```bash
setenforce 0
```

### 其他内容

~~然而似乎没几个用户用真机来跑（？~~

**Comment by horror-proton** [comment]
MAA 现在有三种控制方式, 应该只有 minitouch 是通过 evdev 控制的, 试试换成 maatouch, 那个用的是 InputManager 的, 如果还是不行那就换成 adb, 那个是用 input 命令操作的, 精度差一些

**Comment by Mufanc** [comment]
感谢提醒，换成 maatouch 确实可用了
