### ISSUE TITLE
宿舍进驻时因bug而卡住

### ISSUE THREAD

**Issue by Suimukill** [MaaAssistantArknights/MaaAssistantArknights#3832]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在宿舍进驻时，勾选了“补满空位”的选项后，脚本将会打开“未进驻”干员筛选，从而无法找到基建排班时设定的干员，然后他会重复尝试很久，最终卡在这个进度

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10833747/asst.log)
问题出现在20点59到21点01

### 截图

![QQ截图20230226210712](https://user-images.githubusercontent.com/126396049/221412283-07cd260f-4fb2-45d0-b121-228b3ae4ed65.png)

### 还有别的吗？

模拟器为蓝叠 WIN10六十四位操作系统，我的基建排班代码：1677225023633899

**Comment by MistEO** [comment]
把指定的干员放第一个宿舍就好了，这个问题不怎么好改（其实是我懒得改
