### ISSUE TITLE
建议添加图像识别的外部接口

### ISSUE THREAD

**Issue by diamond82908** [MaaAssistantArknights/MaaAssistantArknights#3833]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

能否在开放给python和其他语言的api中开放一些关于图像识别的接口？我想要一些接受游戏图像输入，返回游戏内物体坐标的函数。
我期望的新api接口大概是这样的：
`x, y = asst.recognize_object(game_screen_shoot, "SkillButton")`

**Comment by zzyyyl** [comment]
不能直接用 cv 么（

**Comment by liuyifan-eric** [comment]
用的就是opencv的matchTemplate，代码在MatchImageAnalyzer.cpp，用的是TM_CCOEFF_NORMED

**Comment by diamond82908** [comment]
> 

是这样么？是我孤陋寡闻了，一直不了解opencv之类的东西。
我会了尝试一下这个建议的
