### ISSUE TITLE
用夜神连不上，手动自动都不行

### ISSUE THREAD

**Issue by lxl1374** [MaaAssistantArknights/MaaAssistantArknights#3836]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用mumu没问题但是要双开又下了个夜神9，一开始说分辨率不够，换了分辨率说连接失败。没用夜神成功过，只能选择mumu先挂一个再挂一个，最近一次发生问题是2023.02.27。./问题试了去掉，也是一样的结果。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10835831/asst.log)
一直都没法用夜神连接上，之前都是用mumu但是mumu无法双开

### 截图

![MAA_2nfD2ORXCW](https://user-images.githubusercontent.com/39314248/221467809-eeb72ea5-30fb-40f4-84ec-8cb0825174f1.png)

![MAA_0uSrq8VhBE](https://user-images.githubusercontent.com/39314248/221468858-65dc1ad0-aa70-41f9-ad0c-854a7812244d.png)

### 还有别的吗？

![Nox_FEteT3IVRW](https://user-images.githubusercontent.com/39314248/221468691-cec1cdaf-e11f-4106-85ed-a536dd652199.png)
电脑操作系统为win10专业版

**Comment by MistEO** [comment]
试试强制替换 adb，（MAA 连接设置里那个按钮）

**Comment by MistEO** [comment]
应该是夜神的问题，最近不少人说，我去问问他们

**Comment by WSMTBG** [comment]
为什么不试试蓝叠呢 /doge

**Comment by ntgmc** [comment]
刚刚远程解决了一个，你试试下载
[platform-tools_r33.0.3-windows.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10888871/platform-tools_r33.0.3-windows.zip)
这个，解压后直接放到D盘，然后MAA选择文件夹里面的adb.exe
方法2：把adb放到没有空格的文件夹？
方法3：文件名加个“”
方法2、3是我想的，没有测试过，3个都不行就当我没说

**Comment by lxl1374** [comment]
> 

谢谢你的方法，我试了一下还是不行，只能放弃了
