### ISSUE TITLE
备选关卡与手动输入关卡名兼容

### ISSUE THREAD

**Issue by liuyifan-eric** [MaaAssistantArknights/MaaAssistantArknights#3837]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前打开手动输入关卡名后就不能使用备选关卡了，遇到类似“优先刷钱本，钱本不开刷刺球”这样的需求不太方便

### 有什么好的想法？

开启手动输入关卡名后，依然有多个备选关卡可以填入

**Comment by ABA2396** [comment]
有剩余理智功能（将就用）
