### ISSUE TITLE
希望可以解决WSA截图错误的问题

### ISSUE THREAD

**Issue by ProblemFactory** [MaaAssistantArknights/MaaAssistantArknights#3838]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前因为WSA的逻辑和其它模拟器不同，用screencap直接截图会出现黑边导致无法识别，以及还可能存在多个Android窗口互相遮挡以及多屏幕的问题。 https://github.com/microsoft/WSA/issues/206

### 有什么好的想法？

这个问题是可以解决的，在  `dumpsys SurfaceFlinger`  的结果中可以看到类似如下内容（节选）：
<pre><code>  Display 100 (active) HWC layers:
---------------------------------------------------------------------------------------------------------------------------------------------------------------
 Layer name
           Z |  Window Type |  Comp Type |  Transform |   Disp Frame (LTRB) |          Source Crop (LTRB) |     Frame Rate (Explicit) (Seamlessness) [Focused]
---------------------------------------------------------------------------------------------------------------------------------------------------------------
 com.microsoft.windows.homeapp/com.microsoft.windows.home.Home#433
  rel      0 |            1 |     DEVICE |          0 |    0    0 3840 2160 |    0.0    0.0 3840.0 2160.0 |                                              [ ]
---------------------------------------------------------------------------------------------------------------------------------------------------------------

Display <b>101</b> (inactive) HWC layers:
---------------------------------------------------------------------------------------------------------------------------------------------------------------
 Layer name
           Z |  Window Type |  Comp Type |  Transform |   Disp Frame (LTRB) |          Source Crop (LTRB) |     Frame Rate (Explicit) (Seamlessness) [Focused]
---------------------------------------------------------------------------------------------------------------------------------------------------------------
 com.microsoft.windows.homeapp/com.microsoft.windows.home.SecondaryHome#439
  rel      0 |            1 |     DEVICE |          0 |    0    0 3840 2160 |    0.0    0.0 3840.0 2160.0 |                                              [ ]
---------------------------------------------------------------------------------------------------------------------------------------------------------------
 com.taptap/com.taptap.infra.page.core.activity.MainProxyActivity#509
  rel      0 |            1 |     DEVICE |          0 | 2442  508 3258 1778 |    0.0    0.0  816.0 1270.0 |                                              [ ]
---------------------------------------------------------------------------------------------------------------------------------------------------------------
 SurfaceView[<b>com.hypergryph.arknights</b>/com.u8.sdk.U8UnityContext](BLAST)#484
  rel      0 |            0 |     DEVICE |          0 | 1263  509 3503 1769 |    0.0    0.0 2240.0 1260.0 |                                              [*]
---------------------------------------------------------------------------------------------------------------------------------------------------------------

</code></pre>

可以看到，通过检索`com.hypergryph.arknights`所处的Display（例子中是101，我特地把窗口放在副屏测试的），根据表格顺序可知其是否是最后一个渲染的，以及是否是当前焦点所处的窗口，还可以读取出窗口的位置和大小（1263  509 3503 1769）。在确保`com.hypergryph.arknights`之后没有窗口遮挡，以及读取到对应的displayId和位置之后，只要将`screencap -d {displayId}`拿到的截图稍作裁切即可继续使用正常工作流处理。唯一的需求就是明日方舟窗口不能最小化（最小化之后会从这个表格中消失），以及必须是处于最上端的（最后一次拿到焦点）的Android窗口。

**Comment by DarkCWK** [comment]
同样遇到这个问题，希望尽快适配

**Comment by M1Screw** [comment]
> 还可以读取出窗口的位置和大小（1263 509 3503 1769）

不用這麽麻煩的，直接用 OpenCV 灰階轉換功能裁掉黑邊然後用輸出的圖像去喂 MAA 本身的識圖模組就可以了，參考這個問題 https://stackoverflow.com/questions/13538748/crop-black-edges-with-opencv。

順便這樣做也可以解決部分物理機輸出圖像自帶黑邊的問題（異形屏，打孔屏 etc.）

至於 displayId 可以默認 100 然後讓用戶手動輸入 offset，多螢幕用戶的話一個個試過去就行（家用機一般3-4個最多了）

**Comment by WendaoLee** [comment]
如果半年后没有人做WSA的相关优化的话，我应该会在过年有空的时候提交相关pr（but not sure :）

**Comment by SherkeyXD** [comment]
https://github.com/MaaAssistantArknights/libWSAController
等待集成（
