### ISSUE TITLE
非满配基建换班异常

### ISSUE THREAD

**Issue by yltx** [MaaAssistantArknights/MaaAssistantArknights#384]
如题，看起来这个项目不能识别已经没有心情工作的干员……
于是就出现了先把已经心情涣散的干员选进设施，然后再选进宿舍，导致设施确认的弱智操作……
![image.png](https://s2.loli.net/2022/04/29/82Unjzb4wTSYXLC.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8587645/asst.log)

**Comment by MistEO** [comment]
问一下，确定是先把没心情的干员放进设施工作，然后再选进宿舍的吗？是你看到的，还是换完班之后看基建好多空的猜测是这样的

**Comment by yltx** [comment]
确定是这样的……我亲眼看着它干的这下饭操作

**Comment by yltx** [comment]
> 问一下，确定是先把没心情的干员放进设施工作，然后再选进宿舍的吗？是你看到的，还是换完班之后看基建好多空的猜测是这样的

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/361

跟这个应该是一个bug

**Comment by miku1958** [comment]
我也有遇到类似的问题，先把休息室填满再去分配工作应该就能解决这个问题？

**Comment by MistEO** [comment]
没搞懂为啥，加了点日志，3.2.2 或者之后的版本遇到的话再帮忙发一下吧_(:з」∠)_
