### ISSUE TITLE
战斗过程中任务出错程序中断

### ISSUE THREAD

**Issue by hanaboob** [MaaAssistantArknights/MaaAssistantArknights#3841]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

夜神模拟器，还有体力，显示出错，卡在战斗结算界面不动

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10839156/asst.log)
2-27 19:29:31

### 截图

![无标题](https://user-images.githubusercontent.com/123377840/221553617-e068a846-f1c0-496c-abb2-c5de7e941d0c.png)

**Comment by zzyyyl** [comment]
显示检测到了代理失误，但试图放弃当前行动的时候没有找到按钮就卡住了。你有没有在maa运行期间点击模拟器？
