### ISSUE TITLE
I.S. Stuck at Combat Dps Enter

### ISSUE THREAD

**Issue by y3nly** [MaaAssistantArknights/MaaAssistantArknights#3842]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

MAA seems to get stuck when both Emergency Ops and Combat Ops is shown on the screen. It'll repeatedly click on Combat Ops, instead of clicking on Enter.

Likely because of the low ocr score `Phantom@Roguelike@StageCambatDpsEnter.png score: 0.611675`

### Log files

[truncated.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10840020/truncated.log)

### Screenshots

![image](https://user-images.githubusercontent.com/16805265/221574844-2a958a01-3fbe-4769-bfa0-e3df0adf8162.png)

**Comment by liuyifan-eric** [comment]
This is a known issue

**Comment by ABA2396** [comment]
所以为什么分这么低还是不知道（）

**Comment by y3nly** [comment]
Fix has been running well, thanks!
