### ISSUE TITLE
基建自定义排版过慢

### ISSUE THREAD

**Issue by DreAmVirGo** [MaaAssistantArknights/MaaAssistantArknights#3843]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最近频发的情况，maa在执行自定义基建时用时过长，不知道原因，想请大佬帮忙看一下。
版本：内测版v4.11.1-alpha.0.16
模拟器：蓝叠国际
触控模式：MaaTouch+Adb Lite开启，其中不开启Adb Lite也会发生此情况（所以想开了看看会不会改善但是没有）
已强制替换Adb多次

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10840140/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/28724211/221577646-3551da2d-ce09-4436-b663-973e3d1a3939.png)
![image](https://user-images.githubusercontent.com/28724211/221577763-6642c2be-9e42-4af1-a81d-214c602fb18a.png)
![image](https://user-images.githubusercontent.com/28724211/221578228-2f974871-5542-4dc2-a496-3e7f839ed92e.png)

**Comment by zzyyyl** [comment]
```
[2023-02-27 18:55:26.413][ERR][Px92c0][Tx91d0] adb-lite does not support receiving data from socket
[2023-02-27 18:55:46.414][WRN][Px92c0][Tx91d0] Wait handles: [process_info.hProcess, pipeov.hEvent, sockov.hEvent] timeout.
[2023-02-27 18:55:46.414][INF][Px92c0][Tx91d0] Call ` C:\Program Files\BlueStacks_nxt\.\HD-Adb.exe -s 127.0.0.1:5555 exec-out "screencap | nc -w 3 10.0.2.3 51214" ` ret 0 , cost 20000 ms , stdout size: 0 , socket size: 5760016
```

截图超时了，但其实收到了数据，好像是建立的 socket 没关（不太懂

另外我看好像基本上超时的时候都是 adb-lite 开着的时候（？关掉试试

**Comment by DreAmVirGo** [comment]
> ```
> [2023-02-27 18:55:26.413][ERR][Px92c0][Tx91d0] adb-lite does not support receiving data from socket
> [2023-02-27 18:55:46.414][WRN][Px92c0][Tx91d0] Wait handles: [process_info.hProcess, pipeov.hEvent, sockov.hEvent] timeout.
> [2023-02-27 18:55:46.414][INF][Px92c0][Tx91d0] Call ` C:\Program Files\BlueStacks_nxt\.\HD-Adb.exe -s 127.0.0.1:5555 exec-out "screencap | nc -w 3 10.0.2.3 51214" ` ret 0 , cost 20000 ms , stdout size: 0 , socket size: 5760016
> ```
> 
> 截图超时了，但其实收到了数据，好像是建立的 socket 没关（不太懂
> 
> 另外我看好像基本上超时的时候都是 adb-lite 开着的时候（？关掉试试

这几天下来关了确实有一些用，但是有时候还是会卡。想问一下三种触控模式（minitouch、maatouch和adb input）到底有什么区别？什么情况下用哪个会好一点。。。

**Comment by MistEO** [comment]
- adb input，安卓原生的触控方式，兼容性最好，但比较慢
- minitouch，一个第三方库，很快，有些设备不兼容
- maatouch，大佬自己写的给 maa 用的，和 minitouch 一样快，兼容性也更好，但测的比较少不知道有没有奇怪的 bug

**Comment by DreAmVirGo** [comment]
最近又被我碰上了同样的情况，而且更离谱了hhh
![image](https://user-images.githubusercontent.com/28724211/224544485-eef9ea7b-2b5c-42d7-873d-de63a55e99ff.png)
![image](https://user-images.githubusercontent.com/28724211/224544500-f7ec5594-e607-4ae1-92a2-53378a73a35f.png)
![image](https://user-images.githubusercontent.com/28724211/224544516-cdbba7e3-60e7-4565-8c4b-06004467886c.png)
卡在宿舍选完人界面之后不点确定
![image](https://user-images.githubusercontent.com/28724211/224544585-40a9b10e-ab9c-471c-993f-09a53060d94b.png)

强制替换过adb。不过每一次打开maa都需要强制替换吗？还是一次性就好。
日志：[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10950811/asst.log)

**Comment by ABA2396** [comment]
蓝叠Pie特有的问题，可以换Nougat实例
