### ISSUE TITLE
设置属性“System.Windows.ResourceDictionary.DeferrableContent”时引发了异常。

### ISSUE THREAD

**Issue by aoki-rin** [MaaAssistantArknights/MaaAssistantArknights#3845]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

双击MAA.exe后直接跳出此页面，以管理员身份运行也一样

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10840613/gui.log)

### 截图

![image](https://user-images.githubusercontent.com/88824899/221591126-14aa7baa-bcce-4c4c-9c63-61054d300ca0.png)

### 还有别的吗？

操作系统：win10

**Comment by ABA2396** [comment]
重新下载能解决吗，看着像是资源文件出问题了。但是测试版中只有日语的资源文件出了问题，参考下https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3831

**Comment by JohnSmith177013** [comment]
我的windows区域格式是日语，出现了同样的异常，切换成中文后恢复正常

**Comment by ABA2396** [comment]
> 我的windows区域格式是日语，出现了同样的异常，切换成中文后恢复正常

那就没问题了，这个版本日语资源有重复数据然后解析炸了，等下个版本就好了

**Comment by fangundeboll** [comment]
我碰到了同样的问题，在个性化-时间与语言-语言与区域中将首选语言列表中的“日文”删除后成功解决

**Comment by ABA2396** [comment]
> 我碰到了同样的问题，在个性化-时间与语言-语言与区域中将首选语言列表中的“日文”删除后成功解决。感谢你的提问和解决方法

4.12.0-beta.1已经解决了这个问题，可以更新测试版或等待正式版更新
