### ISSUE TITLE
打开时报错“MaaWpfGui.SettingsViewModel的类型初始值设定“项引发异常。

### ISSUE THREAD

**Issue by JUNGLEjiangjianghao** [MaaAssistantArknights/MaaAssistantArknights#3846]
解决方案 出现未知错误
详细信息
   在 MaaWpfGui.SettingsViewModel..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.AsstProxy..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.RootViewModel..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 Stylet.Bootstrapper`1.get_RootViewModel()
   在 Stylet.Bootstrapper`1.Launch()
   在 Stylet.BootstrapperBase.Start(String[] args)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/221623387-6754f691-7ae2-4fbe-b39e-b7a183d5fafe.png)
