### ISSUE TITLE
在游戏主界面无法运行刷理智

### ISSUE THREAD

**Issue by 2683807278** [MaaAssistantArknights/MaaAssistantArknights#3848]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在游戏主界面运行刷理智会点击干员处

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10845473/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/77843037/221722486-8d8c5c24-b6f1-418e-af7f-e2912f33cac9.png)
![Screenshot_2023 02 28_08 42 32 802](https://user-images.githubusercontent.com/77843037/221722527-eabf252e-011e-44fb-8c91-3b7992bf9baf.png)

### 还有别的吗？

2023-02-28 08-43-01.mp4
https://www.aliyundrive.com/s/ExwVkDZiCt7
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by 2683807278** [comment]
在触摸模式中改成兼容模式就能用了

**Comment by Black1312** [comment]
请先核对maa路径是否有中文，如果路径中没有中文字符且问题依然存在。请执行下述步骤：
加群：786683995，群文件下载platform-tools_r33.0.3-windows后解压该文件，在maa的连接设置的adb路径中选择解压文件中的adb.exe
本issue关闭，如有问题请再发issue或群内询问管理员
