### ISSUE TITLE
关于默认端口的问题，我也不知道应该怎么简单解释

### ISSUE THREAD

**Issue by WSMTBG** [MaaAssistantArknights/MaaAssistantArknights#3849]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我用的是蓝叠Nougat最新版，MAA 4.11.0
有时候模拟器关闭后被maa打开后，模拟器的ADB连接地址会从本来的“127.0.0.1:5555”变成“127.0.0.1:5556”，导致无法连接模拟器，因为我有时候会模拟器多开所以手动填的地址，

### 日志文件

暂无

**Comment by ABA2396** [comment]
模拟器异常关闭可能会导致端口变动，重启就恢复了。问题是之前是怎么关的

**Comment by WSMTBG** [comment]
> 模拟器异常关闭可能会导致端口变动，重启就恢复了。问题是之前是怎么关的

手动点右上角红叉，然后点是否确认关闭的提示框，应该算是正常关闭吧

**Comment by MistEO** [comment]
蓝叠的问题，他关完没把端口释放掉，下次再启动发现端口被占了，就自动跳到下一个端口了
