### ISSUE TITLE
肉鸽选人异常

### ISSUE THREAD

**Issue by yltx** [MaaAssistantArknights/MaaAssistantArknights#385]
就离谱，这软件就跟赫默干上了吧，明明白咕咕排名在她前面它不选，我额外加的“预备干员-后勤”也不选？？？？（尝试了“预备干员”和“预备干员-后勤”两种名称，它完全不管的……）
附上tasks.json:
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8588701/asst.log)
```json
    "Roguelike1ChooseOper": {
        "algorithm": "OcrDetect",
        "action": "clickSelf",
        "cache": false,
        "Doc": "所有肉鸽可能招募的干员，不在列表里的不会则被招募，可以手动修改，在前面的会优先招募",
        "Doc2": "画面中如果既有低星又有高星，说明希望不够（高星是灰的不让选，但也被识别到了），所以尽量把低星的放前面，优先招募",
        "text": [
            "---三星备选干员---",
            "芬",
            "玫兰莎",
            "香草",
            "梓兰",
            "芙蓉",
            "安赛尔",
            "预备干员",
            "---近卫---",
            "羽毛笔",
            "幽灵鲨",
            "棘刺",
            "煌",
            "帕拉斯",
            "银灰",
            "陈",
            "---先锋---",
            "凛冬",
            "德克萨斯",
            "风笛",
            "嵯峨",
            "推进之王",
            "---重装---",
            "古米",
            "蛇屠箱",
            "临光",
            "泥岩",
            "塞雷娅",
            "星熊",
            "---狙击---",
            "白金",
            "能天使",
            "假日威龙陈",
            "黑",
            "---术士---",
            "阿米娅",
            "天火",
            "艾雅法拉",
            "异客",
            "---治疗---",
            "预备干员",
            "白面鸮",
            "赫默",
            "凯尔希",
            "闪灵",
            "夜莺",
            "---辅助---",
            "梅尔",
            "巫恋",
            "初雪",
            "真理",
            "安洁莉娜",
            "铃兰",
            "麦哲伦",
            "令",
            "---特种---",
            "水月",
            "狮蝎"
        ],
```

**Comment by yltx** [comment]
还有一个问题就是会间歇性出现卡在放人界面的情况（就是等待确认方向的那个界面），具体规律不明

**Comment by zzyyyl** [comment]
问题出在OCR把`赫默`识别成了`赤赤黑大`，然后当成`黑`选上了（
`预备干员`没选上应该是你干员太多第一页没有，现在暂时只支持识别第一页的干员
卡在选人界面就不知道了，什么时候复现了发个日志看看？
@MistEO 快来修bug！

**Comment by MistEO** [comment]
> 问题出在OCR把`赫默`识别成了`赤赤黑大`，然后当成`黑`选上了（ `预备干员`没选上应该是你干员太多第一页没有，现在暂时只支持识别第一页的干员 卡在选人界面就不知道了，什么时候复现了发个日志看看？ @MistEO 快来修bug！

草，这怎么修（）

我直接一个 replace

**Comment by yltx** [comment]
> > 问题出在OCR把`赫默`识别成了`赤赤黑大`，然后当成`黑`选上了（ `预备干员`没选上应该是你干员太多第一页没有，现在暂时只支持识别第一页的干员 卡在选人界面就不知道了，什么时候复现了发个日志看看？ @MistEO 快来修bug！
> 
> 草，这怎么修（）
> 
> 我直接一个 replace

这个作息，是程序员石锤了（

**Comment by zzyyyl** [comment]
> > 问题出在OCR把`赫默`识别成了`赤赤黑大`，然后当成`黑`选上了（ `预备干员`没选上应该是你干员太多第一页没有，现在暂时只支持识别第一页的干员 卡在选人界面就不知道了，什么时候复现了发个日志看看？ @MistEO 快来修bug！
> 
> 草，这怎么修（）
> 
> 我直接一个 replace

我记得`红豆`和`红`也会搞错，这个是不是不好修（？

**Comment by MistEO** [comment]
v3.1.3 fixed

**Comment by MistEO** [comment]
> > > 问题出在OCR把`赫默`识别成了`赤赤黑大`，然后当成`黑`选上了（ `预备干员`没选上应该是你干员太多第一页没有，现在暂时只支持识别第一页的干员 卡在选人界面就不知道了，什么时候复现了发个日志看看？ @MistEO 快来修bug！
> > 
> > 
> > 草，这怎么修（）
> > 我直接一个 replace
> 
> 我记得`红豆`和`红`也会搞错，这个是不是不好修（？

修不了，摆烂了（

**Comment by yltx** [comment]
> > > > 问题出在OCR把`赫默`识别成了`赤赤黑大`，然后当成`黑`选上了（ `预备干员`没选上应该是你干员太多第一页没有，现在暂时只支持识别第一页的干员 卡在选人界面就不知道了，什么时候复现了发个日志看看？ @MistEO 快来修bug！
> > > 
> > > 
> > > 草，这怎么修（）
> > > 我直接一个 replace
> > 
> > 
> > 我记得`红豆`和`红`也会搞错，这个是不是不好修（？
> 
> 修不了，摆烂了（

草
