### ISSUE TITLE
 自定义基建会客室换班失败

### ISSUE THREAD

**Issue by dylanhz** [MaaAssistantArknights/MaaAssistantArknights#3850]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

按照我的自定义基建，会客室应该在13:00将陈和伺夜替换掉红和远山来上班，但有时候并没有完成，而其他设施换班正常。
今早检查时发现心情异常，似乎是昨天13:06左右会客室换班失败，而前天又是正常的，这期间基建策略并无改动。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10845949/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10845950/asst.bak.log)
[base.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10845952/base.zip)

### 还有别的吗？

v4.11.1-alpha.0.16.g86d2a91d

**Comment by Resurgam-Leaf** [comment]
我也是会客室换班一直失败,轮回转了左右几趟明明看到了远山和暗锁但是就是不选,不知道为什么识别不了
