### ISSUE TITLE
基建有精1孑精2银灰精2但书精2灵知，贸易站仍会使用能天使月见夜（空爆）但书

### ISSUE THREAD

**Issue by tobiasde** [MaaAssistantArknights/MaaAssistantArknights#3853]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

基建有精1孑精2银灰精2但书精2灵知，贸易站仍会使用能天使月见夜但书

### 其他内容

MAA排班和box
![34](https://user-images.githubusercontent.com/33055550/221842724-00e81564-fcf6-481c-ade3-8df6f3eccedb.png)
![01](https://user-images.githubusercontent.com/33055550/221842739-eae5345d-b7cd-473b-b525-f5fd964f6012.png)
![02](https://user-images.githubusercontent.com/33055550/221842744-603e83c1-629f-497a-b507-de85610fe02d.png)
![03](https://user-images.githubusercontent.com/33055550/221842745-757e045a-aa2f-4146-b0fa-0162b435c101.png)
![04](https://user-images.githubusercontent.com/33055550/221842748-bb4ed90b-b804-4a41-978f-304fb35fec5c.png)
![05](https://user-images.githubusercontent.com/33055550/221842754-947dcf4a-9b93-4435-9237-1e7926c148cd.png)
![box1](https://user-images.githubusercontent.com/33055550/221842758-be8633a1-0b95-4861-8b71-76cc6236f9dd.png)
![3](https://user-images.githubusercontent.com/33055550/221842768-bbdb35db-b4b9-4b6e-84cb-044fa6244a92.png)
![32](https://user-images.githubusercontent.com/33055550/221842777-b07212d4-88bb-4dfe-a122-f4952b87f24d.png)
![33](https://user-images.githubusercontent.com/33055550/221842789-f7c4345a-48c1-4bf4-a709-1ea11a120eb1.png)

**Comment by liuyifan-eric** [comment]
自动的排班没有这么智能，有需求可以利用(一图流)[https://yituliu.site/riicCal/]设置自定义排班

**Comment by Minepig** [comment]
自动排班不能处理跨设施联动，建议用自定义排班
