### ISSUE TITLE
关于关卡选择剿灭模式会卡住导致接下来的任务都失败的情况

### ISSUE THREAD

**Issue by QYream** [MaaAssistantArknights/MaaAssistantArknights#3855]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选择剿灭模式后显示“任务出错：Fight”“剿灭任务失败，将尝试使用剩余备选关卡，部分战斗设置将不生效”，接着下面的任务都出错，由于选择了任务完成后关机，当时以为是完成任务了并未发现也不知道卡在哪个界面。猜测可能是卡在了剿灭模式各地区地图左上角i键里面（information）。（因为曾经在那里卡过）

### 日志文件

大概在2.28 上午7点左右出现的问题
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10855795/asst.bak.log)
gui.log里面是这样的
2023/2/28 7:46:28 开始任务：Fight
2023/2/28 7:46:39 已开始行动 1 次
2023/2/28 7:46:54 任务出错：Fight
2023/2/28 7:46:54 剿灭任务失败，将尝试使用剩余备选关卡，部分战斗设置将不生效
2023/2/28 7:46:55 开始任务：Fight
2023/2/28 7:47:00 任务出错：Fight
2023/2/28 7:47:00 剿灭任务失败，将尝试使用剩余备选关卡，部分战斗设置将不生效
2023/2/28 7:47:00 开始任务：Mall
2023/2/28 7:47:32 任务出错：Mall
2023/2/28 7:47:32 开始任务：Recruit
2023/2/28 7:47:48 出现错误，已返回
2023/2/28 7:47:48 任务出错：Recruit
2023/2/28 7:47:48 开始任务：Award
2023/2/28 7:48:04 任务出错：Award
2023/2/28 7:48:04 任务已全部完成（摆烂）！

**Comment by ABA2396** [comment]
应该是的，用剩余理智回回主界面，说明卡在了一个没返回键的地方

**Comment by Rbqwow** [comment]
🤔重装或者剿灭刷新时从剿灭关卡返回会有个剿灭一览表 那个确实会卡住

**Comment by QYream** [comment]
emmm,我想了一下，如果游戏找不到返回键，可以尝试使用三大金刚那个返回键

**Comment by unninie** [comment]
![Snipaste_2023-03-15_08-50-00](https://user-images.githubusercontent.com/64136941/225175886-5b177829-3395-46f7-a104-2dd8bd18f0c9.png)
错误截图
