### ISSUE TITLE
希望可以增加一个刷新公招tag的功能

### ISSUE THREAD

**Issue by R5M4** [MaaAssistantArknights/MaaAssistantArknights#3856]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

通过手动一小时公招然后取消掉刷新tag实在太精污了，而且刷多了容易错把4星以上的招募取消掉

### 有什么好的想法？

在没有4星以上tag时选一小时公招然后取消刷新tag直到刷到4星以上为止

**Comment by ABA2396** [comment]
一天招两次白票的获取速度也赶不上消耗的吧

**Comment by MistEO** [comment]
直接用加急券刷呗？

**Comment by cenfusheng** [comment]
不建议取消招募，maa没有这方面的计划
