### ISSUE TITLE
日服肉鸽勾选开局助战无法使用。

### ISSUE THREAD

**Issue by SnowLancelot** [MaaAssistantArknights/MaaAssistantArknights#3857]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

勾选了开局干员使用助战，但是选择的时候并不会进入助战选择j界面，而是使用临时招募干员，在不勾选使用助战时是能正常选择自己的干员的。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10857663/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/86610515/222059374-97912e5d-fc17-4268-a2fe-0a77bfee614c.png)

### 还有别的吗？

模拟器：蓝叠模拟器国际版
MAA版本：稳定版v4.11.0

**Comment by ABA2396** [comment]
试试在resource\global\YoStarJP\resource\tasks.json添加
```
    "RoguelikeChooseSupportBtnOcr": {
        "algorithm": "OcrDetect",
        "text": [
            "选择助战"
        ],
        "roi": [
            1011,
            9,
            177,
            47
        ]
    },
```
text改成日服对应的
![image](https://user-images.githubusercontent.com/99072975/222068035-54dbdb3f-8355-4912-9437-21f4c8bc230f.png)
看看能不能解决

**Comment by SnowLancelot** [comment]
改成日文是吗？我试试

**Comment by SnowLancelot** [comment]
> 试试在resource\global\YoStarJP\resource\tasks.json添加
> 
> ```
>     "RoguelikeChooseSupportBtnOcr": {
>         "text": [
>             "选择助战"
>         ]
>     }
> ```
> 
> text改成日服对应的 ![image](https://user-images.githubusercontent.com/99072975/222068035-54dbdb3f-8355-4912-9437-21f4c8bc230f.png) 看看能不能解决

没反应，就感觉像是跳过助战这个功能了

**Comment by ABA2396** [comment]
改成
![image](https://user-images.githubusercontent.com/99072975/222081442-ec6c8db1-cf2b-4bf0-9dc8-19c8869aebfd.png)
也没反应吗

**Comment by ABA2396** [comment]
看着是识别错了，识别成了 "サボーⅠ"

**Comment by ABA2396** [comment]
试试text改成:"サボー"或者"サボ"
应该是能跑起来了

**Comment by SnowLancelot** [comment]
> 试试text改成:"サボー"或者"サボ" 应该是能跑起来了

他点进助战了，识别了一下又退出来了
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10858581/asst.log)
这是刚刚运行的日志

**Comment by SnowLancelot** [comment]
> 进入助战界面之后先要识别右上角的刷新按钮，但这个图片目前是中文的。可以搜搜task里面包含Rougelike和Support两个词的都有哪些适配下，时间久了我有点忘
好的我看看

**Comment by WLLEGit** [comment]
> > 进入助战界面之后先要识别右上角的刷新按钮，但这个图片目前是中文的。可以搜搜task里面包含Rougelike和Support两个词的都有哪些适配下，时间久了我有点忘
> > 好的我看看

RoguelikeRefreshSupportBtnOcr
RoguelikeChooseSupportBtnOcr
Roguelike@RecruitSupportConfirm
应该还有这三个，是点击干员之后出现的几个界面

**Comment by SnowLancelot** [comment]
> Roguelike@RecruitSupportConfirm

![image2](https://user-images.githubusercontent.com/86610515/222101684-9f38b46a-fbf3-41ba-b332-d8f6f9820af2.png)
![image](https://user-images.githubusercontent.com/86610515/222101770-0855ceba-6b1e-4f06-be1b-8df663450b0d.png)

**Comment by SnowLancelot** [comment]
> > > 进入助战界面之后先要识别右上角的刷新按钮，但这个图片目前是中文的。可以搜搜task里面包含Rougelike和Support两个词的都有哪些适配下，时间久了我有点忘
> > > 好的我看看
> 
> RoguelikeRefreshSupportBtnOcr RoguelikeChooseSupportBtnOcr Roguelike@RecruitSupportConfirm 应该还有这三个，是点击干员之后出现的几个界面

我已添加了三个按钮的适配了，现在能点进助战并且能识别出右上角的刷新按钮，但是无法识别设置的干员，一直在刷新和寻找
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArkni
![image](https://user-images.githubusercontent.com/86610515/222114731-866d31c0-c41c-4dde-88b3-2f6226c5d55a.png)
ghts/files/10859969/asst.log)

**Comment by SnowLancelot** [comment]
> > > 进入助战界面之后先要识别右上角的刷新按钮，但这个图片目前是中文的。可以搜搜task里面包含Rougelike和Support两个词的都有哪些适配下，时间久了我有点忘
> > > 好的我看看
> 
> RoguelikeRefreshSupportBtnOcr RoguelikeChooseSupportBtnOcr Roguelike@RecruitSupportConfirm 应该还有这三个，是点击干员之后出现的几个界面

我已添加了三个按钮的适配了，现在能点进助战并且能识别出右上角的刷新按钮，但是无法识别设置的干员，一直在刷新和寻找
![image](https://user-images.githubusercontent.com/86610515/222114966-50ff6c55-41b7-4eb5-bb53-88b8f0f12321.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10859975/asst.log)

**Comment by WLLEGit** [comment]
Roguelike@RefreshSupportBtn.png这个图片应该还没换成日文的，不过这不是主要问题。

主要问题是识别干员名的函数只支持中文，这个是Core里的，我不太懂怎么做多语言转换

**Comment by SnowLancelot** [comment]
> [Roguelike@RefreshSupportBtn.png](mailto:Roguelike@RefreshSupportBtn.png)这个图片应该还没换成日文的，不过这不是主要问题。
> 
> 主要问题是识别干员名的函数只支持中文，这个是Core里的，我不太懂怎么做多语言转换

好吧谢谢！

**Comment by liuyifan-eric** [comment]
> Roguelike@RefreshSupportBtn.png这个图片应该还没换成日文的，不过这不是主要问题。
> 
> 
> 
> 主要问题是识别干员名的函数只支持中文，这个是Core里的，我不太懂怎么做多语言转换

识别干员名的已经转换过了，gui输入中文不行吗？你试试看dev上面的

**Comment by SnowLancelot** [comment]
> > [Roguelike@RefreshSupportBtn.png](mailto:Roguelike@RefreshSupportBtn.png)这个图片应该还没换成日文的，不过这不是主要问题。
> > 主要问题是识别干员名的函数只支持中文，这个是Core里的，我不太懂怎么做多语言转换
> 
> 识别干员名的已经转换过了，gui输入中文不行吗？你试试看把你的修改rebase到dev上面

dev是指？

**Comment by WLLEGit** [comment]
我懂了，应该是RoguelikeRecruitSupportAnalyzer.cpp:35那里要加一个

`
analyzer.set_replace(Task.get<OcrTaskInfo>("CharsNameOcrReplace")->replace_map,
                     Task.get<OcrTaskInfo>("CharsNameOcrReplace")->replace_full);
`

但我没有日服游戏测不了（逃

**Comment by SnowLancelot** [comment]
> 我懂了，应该是RoguelikeRecruitSupportAnalyzer.cpp:35那里要加一个
> 
> `analyzer.set_replace(Task.get<OcrTaskInfo>("CharsNameOcrReplace")->replace_map, Task.get<OcrTaskInfo>("CharsNameOcrReplace")->replace_full);`
> 
> 但我没有日服游戏测不了（逃

等有空我试试

**Comment by liuyifan-eric** [comment]
> > > [Roguelike@RefreshSupportBtn.png](mailto:Roguelike@RefreshSupportBtn.png)这个图片应该还没换成日文的，不过这不是主要问题。
> > > 主要问题是识别干员名的函数只支持中文，这个是Core里的，我不太懂怎么做多语言转换
> > 
> > 
> > 识别干员名的已经转换过了，gui输入中文不行吗？你试试看把你的修改rebase到dev上面
> 
> dev是指？

dev branch 没事你不用管了，我们来处理


> 我懂了，应该是RoguelikeRecruitSupportAnalyzer.cpp:35那里要加一个
> 
> `analyzer.set_replace(Task.get<OcrTaskInfo>("CharsNameOcrReplace")->replace_map, Task.get<OcrTaskInfo>("CharsNameOcrReplace")->replace_full);`
> 
> 但我没有日服游戏测不了（逃
> 
> 总结一下的话应该是这几个地方：
> 
> * RoguelikeRefreshSupportBtnOcr, RoguelikeChooseSupportBtnOcr, Roguelike@RecruitSupportConfirm 这几个task的text部分
> * [Roguelike@RefreshSupportBtn.png](mailto:Roguelike@RefreshSupportBtn.png)这张图片（不知道为什么当时这张图没有一起改成ocr）
> * 上面提到的cpp代码

你要改吗？要不你改了push上来我来测一下

**Comment by SnowLancelot** [comment]
> 我懂了，应该是RoguelikeRecruitSupportAnalyzer.cpp:35那里要加一个
> 
> `analyzer.set_replace(Task.get<OcrTaskInfo>("CharsNameOcrReplace")->replace_map, Task.get<OcrTaskInfo>("CharsNameOcrReplace")->replace_full);`
> 
> 但我没有日服游戏测不了（逃
> 
> 总结一下的话应该是这几个地方：
> 
> * RoguelikeRefreshSupportBtnOcr, RoguelikeChooseSupportBtnOcr, Roguelike@RecruitSupportConfirm 这几个task的text部分
> * [Roguelike@RefreshSupportBtn.png](mailto:Roguelike@RefreshSupportBtn.png)这张图片（不知道为什么当时这张图没有一起改成ocr）
> * 上面提到的cpp代码
[Roguelike@RefreshSupportBtn.png在日服的截图文件里并没有放，我已经添加了，日志里也能识别出刷新按钮和干员的位置，但好像是找不到目标干员一直在刷新

**Comment by WLLEGit** [comment]
> 你要改吗？要不你改了push上来我来测一下
> 
> サポート
> 
> サポート更新
> 
> サポート招集

要不你来改吧，我没改过外服的task。

**Comment by SnowLancelot** [comment]
> > > > [Roguelike@RefreshSupportBtn.png](mailto:Roguelike@RefreshSupportBtn.png)这个图片应该还没换成日文的，不过这不是主要问题。
> > > > 主要问题是识别干员名的函数只支持中文，这个是Core里的，我不太懂怎么做多语言转换
> > > 
> > > 
> > > 识别干员名的已经转换过了，gui输入中文不行吗？你试试看把你的修改rebase到dev上面
> > 
> > 
> > dev是指？
> 
> dev branch 没事你不用管了，我们来处理
> 
> > 我懂了，应该是RoguelikeRecruitSupportAnalyzer.cpp:35那里要加一个
> > `analyzer.set_replace(Task.get<OcrTaskInfo>("CharsNameOcrReplace")->replace_map, Task.get<OcrTaskInfo>("CharsNameOcrReplace")->replace_full);`
> > 但我没有日服游戏测不了（逃
> > 总结一下的话应该是这几个地方：
> > 
> > * RoguelikeRefreshSupportBtnOcr, RoguelikeChooseSupportBtnOcr, Roguelike@RecruitSupportConfirm 这几个task的text部分
> > * [Roguelike@RefreshSupportBtn.png](mailto:Roguelike@RefreshSupportBtn.png)这张图片（不知道为什么当时这张图没有一起改成ocr）
> > * 上面提到的cpp代码
> 
> 你要改吗？要不你改了push上来我来测一下
> 
> サポート
> 
> サポート更新
> 
> サポート招集

我昨天改过的task是这样的不知道有没有问题
![222114966-50ff6c55-41b7-4eb5-bb53-88b8f0f12321](https://user-images.githubusercontent.com/86610515/222328399-308fa984-d5ad-4aef-8e0f-1880a37d0575.png)

**Comment by liuyifan-eric** [comment]
@WLLEGit 刷新助战的代码改了吗

**Comment by WLLEGit** [comment]
我以为你改了来着，我现在改下
