### ISSUE TITLE
Crash after Cant Reboot / and stop Morning Arknights JP

### ISSUE THREAD

**Issue by wallsman** [MaaAssistantArknights/MaaAssistantArknights#3864]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

I thought it was working fine after the previous fix, but it seems to be recurring.
And, same 4:00am Dialog stop.

### Log files

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10874451/asst.zip)

**Comment by zzyyyl** [comment]
#1200
