### ISSUE TITLE
自定义基建换班处理宿舍时有时会陷入死循环

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#3866]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自定义基建换班在处理宿舍时，如果排班表里使用了autofill，同时在设置里打开“不把已进驻的干员放入宿舍”，会自动打开“未进驻”选项，此时如果排班表里的某个干员在另一个宿舍休息，MAA就会因为找不到该干员陷入死循环。
我观察了一下MAA的行为，它似乎会固定在换完第一个宿舍时就开启“未进驻”（不确定使用菲亚梅塔的时候是不是也会打开），即使我的换班表中，只有最后一个宿舍写了autofill=true，前三个宿舍显式写了autofill=false，MAA还是会在选完第一个宿舍的五个人的时候就把“未进驻”打开。
考虑到不能让MAA把训练室里心情未满的艾丽妮或者合成站里的年拉到宿舍里来，在处理autofill时“不把已进驻的干员放入宿舍”是必然需要打开的，所以还是需要调整一下自定义换班与autofill之间的协调。
我的建议是，MAA在按照排班表往宿舍放人的时候先确认一下“未进驻”选项是不是已经关上，没有关的话就关掉，之后在处理autofill逻辑的时候再打开“未进驻”选项。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10880524/asst.log)
2023.3.3 17：00

**Comment by swy2018** [comment]
遇到同样问题。4.10之后不知道是不是重构了基建逻辑，bug特别多，一个是这，一个是如果不写满就不会自动蹭信赖，现在自定义几乎没法用，每一班宿舍都要手动换。

**Comment by Minepig** [comment]
> 哪个版本？你们去试下游戏，打开了本来就会找不到，要通过自定义把其他房间的人放进来就不能选这个选项。

对，所以我的意思就是优化一下逻辑：自定义排班使用autofill以后，在处理宿舍时，先处理非autofill部分，关闭筛选，选好人，然后打开筛选，autofill

**Comment by Minepig** [comment]
现在的逻辑（如果设置里启用了“不把已进驻的干员放入宿舍”）：
（保持“未进驻”筛选打开）→照着自定义排班表选人→处理sort逻辑→按心情排序autofill→按信赖排序autofill→确认

我认为可以改为：
关闭“未进驻”筛选→照着自定义排班表选人→处理sort逻辑→打开“未进驻”筛选→按心情排序autofill→按信赖排序autofill→确认

**Comment by Minepig** [comment]
另外就是，即使是进驻在本宿舍的干员，在取消选择后打开“未进驻”筛选，也会找不到，所以不仅仅是跨宿舍拉人的问题

**Comment by Minepig** [comment]
> 你可以调整下配置，或者按照建议说明里的，把autofill放到最后个房间。 开关一次选项要5秒，多数人不喜欢降低换班速度

我现在就是这么做的，我只给第四个宿舍加了autofill，但是MAA依旧会在第一个宿舍把“未进驻”打开

**Comment by Minepig** [comment]
> 你可以调整下配置，或者按照建议说明里的，把autofill放到最后个房间。 开关一次选项要5秒，多数人不喜欢降低换班速度

不降低换班速度的话我觉得有另一个方案，就是加一个判断让MAA只会在需要autofill的时候再打开筛选，比如像我表里只有第四个宿舍autofill，那就等第四个宿舍排完了，还剩几个空位的时候再开筛选，这样也只开一次，速度应该一样的

**Comment by Minepig** [comment]
> 因为这个选项就是单纯要不要打开筛选开关.. 他一定会在第一个房间就选好 一次开关要至少5秒，5秒可以翻快两页选干员了，短时间不会修改这个逻辑

目前看下来是只要开了这个玩意，如果本宿舍有没休息好的干员就必会陷入死循环，因为在本宿舍休息也算进驻了，也会被筛掉

**Comment by Minepig** [comment]
> 你现在是哪个版本？

v4.11.0

**Comment by Minepig** [comment]
> 你先更新到内测版看下是不是还是这样

一样的

**Comment by Minepig** [comment]
> 另外就是，即使是进驻在本宿舍的干员，在取消选择后打开“未进驻”筛选，也会找不到，所以不仅仅是跨宿舍拉人的问题

需要补充一下就是，并不是只有在宿舍休息的人在开筛选以后找不到，满心情在宿舍闲逛的人开了筛选也会找不到

**Comment by Minepig** [comment]
还有一种解决方案就是每次换班宿舍之前把5个人先全下了再说……但我认为从时间成本上考虑这个方案和每次开关一次筛选一样费时间

如果不增加换班时间那最好就是把开启筛选的时间点，从第一个宿舍的自定义换班结束以后，移到第一个autofill=true的宿舍的自定义换班结束以后（这样的话前几个autofill=false的宿舍就不会因为开了筛选找不到人）
