### ISSUE TITLE
I.S. JP Stuck on StageEncounterOptionUnknown

### ISSUE THREAD

**Issue by y3nly** [MaaAssistantArknights/MaaAssistantArknights#3867]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

IS consistently gets stuck on this particular encounter. Looks like it's clicking the wrong area.

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10883237/asst.log)

### Screenshots

![stuck](https://user-images.githubusercontent.com/16805265/222754959-fb292ad6-aae6-44b0-b90a-b617be7a228b.png)

**Comment by liuyifan-eric** [comment]
This is also an known issue but we have not yet figured out how to fix it

**Comment by qaz1qazlol2** [comment]
> This is also an known issue but we have not yet figured out how to fix it

I also encounter this problem in my EN client(when enter the event of entering the big sad lock ending while having no hope)
我在那个取下玩偶时没有希望的时候也会出现类似问题
