### ISSUE TITLE
刷理智异常

### ISSUE THREAD

**Issue by wiknzylix** [MaaAssistantArknights/MaaAssistantArknights#387]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8595535/asst.log)
![image](https://user-images.githubusercontent.com/102891311/166087705-706d78a0-dff6-4c44-952e-db5d465e069b.png)
理智是满的，但是就是不开始刷，是我操作问题吗（

**Comment by aysyxx53** [comment]
和 #381 是一个问题，修复了还没release

**Comment by MistEO** [comment]
先用 `当前关卡` 来刷吧，明后天应该就发版了

**Comment by MistEO** [comment]
v3.1.3 fixed
