### ISSUE TITLE
清平和弦惊在cache里存的头像是一样的，自动战斗时候会认错

### ISSUE THREAD

**Issue by yd278** [MaaAssistantArknights/MaaAssistantArknights#3870]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

就……那么大一个弦惊放在那里 asst.log硬说这是清平然后不上

删了cache\avatars里的两个头像再重启maa就好了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10887415/asst.log)

时间是3-3 19:36左右

**Comment by cenfusheng** [comment]
cache是maa运行时自动存的，具体方法为自动战斗时在cache里寻找有无头像→遇到cache里没有的头像→点一下识别名字→保存头像与名字。道理我都懂，但是maa怎么会把弦惊当成清平存进缓存啊（）不明bug

**Comment by yd278** [comment]
> cache是maa运行时自动存的，具体方法为自动战斗时在cache里寻找有无头像→遇到cache里没有的头像→点一下识别名字→保存头像与名字。道理我都懂，但是maa怎么会把弦惊当成清平存进缓存啊（）不明bug

dbq我去检查了一下它们仨的图标发现右上角还是有一些细微的区别的

我这边的情况是带一技能打过一次（所以存了清平，蓝色背景）
然后带三技能打过一次（存了弦惊，白色背景）
然后去打了一关蓝色背景的图然后就识别错了……

**Comment by cenfusheng** [comment]
> > cache是maa运行时自动存的，具体方法为自动战斗时在cache里寻找有无头像→遇到cache里没有的头像→点一下识别名字→保存头像与名字。道理我都懂，但是maa怎么会把弦惊当成清平存进缓存啊（）不明bug
> 
> dbq我去检查了一下它们仨的图标发现右上角还是有一些细微的区别的
> 
> 我这边的情况是带一技能打过一次（所以存了清平，蓝色背景） 然后带三技能打过一次（存了弦惊，白色背景） 然后去打了一关蓝色背景的图然后就识别错了……

感谢反馈，明白了，等待开发组修复。
