### ISSUE TITLE
要不要搞个自动抽卡，自己抽太非

### ISSUE THREAD

**Issue by VectorKlmons** [MaaAssistantArknights/MaaAssistantArknights#3871]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by Minepig** [comment]
快进到源石全抽没了去B站诉苦（doge

**Comment by SnowLancelot** [comment]
快进到MAA抽的也歪了石头还清空了
