### ISSUE TITLE
吃体力药选项要是能吃一次自动取消做成一次性的就好了

### ISSUE THREAD

**Issue by 7i7iqaqa** [MaaAssistantArknights/MaaAssistantArknights#3879]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

就是这次啃完几个后完成或停止任务会自动取消勾选恰体力，放在设置里可以更改就好了
一不注意又把攒给活动的体力药给啃了呜呜呜

**Comment by WSMTBG** [comment]
复议

**Comment by ABA2396** [comment]
现在右键点选就可以了
