### ISSUE TITLE
关于任务开始后一直无反映

### ISSUE THREAD

**Issue by Gedminer** [MaaAssistantArknights/MaaAssistantArknights#388]
使用设备k30pro.已经按要求手动调成1280x720 dpi320了。但是依然无任何操作。
![屏幕截图(394)](https://user-images.githubusercontent.com/59013843/166094764-a5d2c314-9bfe-4f2c-993c-2d1707a85641.png)
游戏截图
![Screenshot_2022-04-30-14-32-55-081_com hypergryph arknights](https://user-images.githubusercontent.com/59013843/166095179-77e9eb5e-ab54-4094-b886-baf0d2eb6aca.jpg)

软件截图
![屏幕截图(395)](https://user-images.githubusercontent.com/59013843/166095084-4d85cac6-17a8-45b5-be4a-2576895d0529.png)
********************************
日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8596286/asst.log)

**Comment by MistEO** [comment]
日志里
```
init=1080x2400 440dpi base=1280x720 320dpi cur=1280x720 app=1280x626 rng=720x556-1280x1116
```

软件是按 `init` 算的，后面可能可以调整下（

**Comment by MistEO** [comment]
或许可以试试把 `resource\config.json` 里面的 `Custom` 改成

```
                "display": "[Adb] -s [Address] shell dumpsys window displays | grep init= | awk ' { print $3 } '",
                "displayFormat": "cur=%dx%d",
```

**Comment by Gedminer** [comment]
改完之后试了下，提示这个，但是手机上提示已连接到无线调试。
![屏幕截图(519)](https://user-images.githubusercontent.com/59013843/166104969-387d4940-9a7e-4f41-9aee-980ade048669.png)
*********************
日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8596861/asst.log)

**Comment by MistEO** [comment]
你的手机输出多了两项，那试试改成 print $5
```
                "display": "[Adb] -s [Address] shell dumpsys window displays | grep init= | awk ' { print $5 } '",
                "displayFormat": "cur=%dx%d",
```

**Comment by Gedminer** [comment]
感谢大佬，已经能够正常运行了。
![image](https://user-images.githubusercontent.com/59013843/166133630-21cae1d3-66b6-4a4c-a8c5-a8b2e6c87a4f.png)
