### ISSUE TITLE
想问下配置文件里能否修改让刷理智中止需要的的“代理指挥失误“次数？

### ISSUE THREAD

**Issue by MigdalBavel** [MaaAssistantArknights/MaaAssistantArknights#3885]
### 说说你遇到的问题？

虽然不常见，但是偶尔一些特殊情况会出现老代理失误。刚遇到了一次，观察发现maa默认是出现4次才停止刷理智。
个人比较抠和谨慎，希望可以出现一次就直接停止，比如设置里提供这个次数选项，最好右下角还能弹窗提醒一下。
但在这个需求被采纳以及实装之前，想问下是否在配置文件里可以直接改这个参数，先让我可以临时应对一下？

**Comment by MistEO** [comment]
在 `resource/tasks.json` 中搜 `"FightMissionFailed"` 修改它的 `maxTimes` 值

**Comment by MigdalBavel** [comment]
> 在 `resource/tasks.json` 中搜 `"FightMissionFailed"` 修改它的 `maxTimes` 值

感谢

**Comment by ABA2396** [comment]
这个在版本更新之后会被覆盖掉，到时如果还要的话得重新改

**Comment by MigdalBavel** [comment]
> 这个在版本更新之后会被覆盖掉，到时如果还要的话得重新改

好的谢谢
