### ISSUE TITLE
能不能写一个其他平台（比如mac和Linux）的教程

### ISSUE THREAD

**Issue by ghg6666678** [MaaAssistantArknights/MaaAssistantArknights#3887]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题，本人新购置了一台mac打算用来挂机用，但是我下载了mac版的MAA，可是所有教程都是Windows的，而且我安装了adb之后也连接不上mac的MuMu模拟器，提示是这样的
<img width="1280" alt="截屏2023-03-05 22 26 41" src="https://user-images.githubusercontent.com/97784469/222966471-40eee495-67f0-4c02-aa82-c9603957aaca.png">

### 有什么好的想法？

在教程中加入多个平台的教程

**Comment by ABA2396** [comment]
~写教程的人都是用的windows~

**Comment by MistEO** [comment]
发下日志看看，~~另外用 mac/Linux 我们会默认你有一定的动手能力的~~

**Comment by ghg6666678** [comment]
> 发下日志看看，~另外用 mac/Linux 我们会默认你有一定的动手能力的~

通过更改ADB地址就成功了，希望开发者像适配夜神和蓝叠一样可以一键连接（~~因为这两个大厂全部摆烂，macOS12.5之后都会崩溃，2021年之后都没有更新~~，只有网易还能用）

**Comment by ghg6666678** [comment]
> 发下日志看看，~另外用 mac/Linux 我们会默认你有一定的动手能力的~

通过改连接地址已经成功了，但是希望开发者能手动适配一下网易模拟器，夜神和蓝叠新系统已经用不了了，都还是2021年的最新版本，只有网易能用了

**Comment by oracle91** [comment]
> > 发下日志看看，~另外用 mac/Linux 我们会默认你有一定的动手能力的~
> 
> 通过改连接地址已经成功了，但是希望开发者能手动适配一下网易模拟器，夜神和蓝叠新系统已经用不了了，都还是2021年的最新版本，只有网易能用了

您好，请问怎么修改连接地址？我也是用MuMu模拟器，一直连不上

**Comment by Dlinuigh** [comment]
:)用mac的考虑到了Linux的，多么贴心呀，但是Maa在Linux上运行挺正常的
