### ISSUE TITLE
mumu模拟器x连不上

### ISSUE THREAD

**Issue by fangdanxiongjia** [MaaAssistantArknights/MaaAssistantArknights#3889]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我在官网下了最新的mumu模拟器x 
但是一直提示连接失败  
请检查连接设置或常识重启电脑
我是试过重启 强制替换adb 兼容模式 通用模式均不行

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10892054/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/41151503/222967216-a90d31de-e497-4f97-86c1-9439e051715b.png)
![image](https://user-images.githubusercontent.com/41151503/222967238-d17c70fe-d866-4244-be61-1e23c6e56e2a.png)

**Comment by ABA2396** [comment]
端口不是emulator-5554，查查mumux的端口然后用手动填上链接地址试试

**Comment by ABA2396** [comment]
127.0.0.1:7555

**Comment by fangdanxiongjia** [comment]
> 127.0.0.1:7555

确实是这个问题 谢谢
