### ISSUE TITLE
“MaaWpfGui.SettingsViewModel”的类型初始值设定项引发异常。

### ISSUE THREAD

**Issue by TouKenka** [MaaAssistantArknights/MaaAssistantArknights#3891]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Win10系统首次启动MAA弹出如题错误。解决方案显示”出现未知错误“。
详细错误信息如下：
 在 MaaWpfGui.SettingsViewModel..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.AsstProxy..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.RootViewModel..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 Stylet.Bootstrapper`1.get_RootViewModel()
   在 Stylet.Bootstrapper`1.Launch()
   在 Stylet.BootstrapperBase.Start(String[] args)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10892255/gui.log)

**Comment by ABA2396** [comment]
缺少运行库文件，参考 [常见问题](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html)

**Comment by zzyyyl** [comment]
> 缺少运行库文件，参考 [常见问题](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html)

有没有可能把这句话写到弹窗的解决方案里（？

**Comment by ABA2396** [comment]
> > 缺少运行库文件，参考 [常见问题](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html)
> 
> 有没有可能把这句话写到弹窗的解决方案里（？

不知道为啥，在更改注入方式后，部分的dllNotFound问题就变成了这个提示。正常的话弹窗就是写参考文档

**Comment by ABA2396** [comment]
> > 缺少运行库文件，参考 [常见问题](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html)
> 
> 有没有可能把这句话写到弹窗的解决方案里（？

加了
