### ISSUE TITLE
【自动肉鸽】卡在选择初始三位干员的第一位

### ISSUE THREAD

**Issue by suitus** [MaaAssistantArknights/MaaAssistantArknights#3892]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在肉鸽模式中，自定义开局助战干员为“棘刺”时，有可能会卡在棘刺招募成功的画面；MAA不会继续选择下一位干员，会一直停留在开局。已复现3次。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10892466/asst.log)
问题出现的大致时间点：3.6 01:34:53

### 截图

![MuMu20230306013621](https://user-images.githubusercontent.com/82707940/222976649-7b775dcb-28fb-4323-b790-5fea938f949d.png)

### 还有别的吗？

模拟器：MuMu X
操作系统：Win 11

**Comment by WLLEGit** [comment]
看上去招募后弹出的Skip按钮没及时识别到，但3.5 23点又有成功招募的助战煌的记录。莫非是棘刺皮肤的问题？

**Comment by ABA2396** [comment]
> 看上去招募后弹出的Skip按钮没及时识别到，但3.5 23点又有成功招募的助战煌的记录。莫非是棘刺皮肤的问题？

我记得不是有不检测直接点右上角的那个吗

**Comment by WLLEGit** [comment]
> > 看上去招募后弹出的Skip按钮没及时识别到，但3.5 23点又有成功招募的助战煌的记录。莫非是棘刺皮肤的问题？
> 
> 我记得不是有不检测直接点右上角的那个吗

好像没加进ChooseOper的next，这个just return任务不知道会不会导致其他问题。

**Comment by WLLEGit** [comment]
ok
d4dcc466bc83b23326aae206e12dc85e9e05e18c
