### ISSUE TITLE
mumu12 自动肉鸽战斗时经常点了暂停后无操作，一直暂停着，10 分钟后自动结束战斗

### ISSUE THREAD

**Issue by qianxu2001** [MaaAssistantArknights/MaaAssistantArknights#3896]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

rt

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10894824/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/62287903/223030364-45b52c9d-d71e-4d83-b87a-fab09e10183f.png)

**Comment by liuyifan-eric** [comment]
战斗中暂停吗？你开了暂停部署吗？

**Comment by qianxu2001** [comment]
> 战斗中暂停吗？你开了暂停部署吗？
> 

是的，开了暂停放人，此前使用其他模拟器(蓝叠/雷电)是也开了这个功能，在这俩模拟器上没遇到这个问题，我关了这个再试试

**Comment by WSMTBG** [comment]
> > 战斗中暂停吗？你开了暂停部署吗？
> 
> 是的，开了暂停放人，此前使用其他模拟器(蓝叠/雷电)是也开了这个功能，在这俩模拟器上没遇到这个问题，我关了这个再试试

设置-连接设置里面用maa开头那个触控模式试试，听说的，不一定管用

**Comment by qianxu2001** [comment]
> > > 战斗中暂停吗？你开了暂停部署吗？
> > 
> > 
> > 是的，开了暂停放人，此前使用其他模拟器(蓝叠/雷电)是也开了这个功能，在这俩模拟器上没遇到这个问题，我关了这个再试试
> 
> 设置-连接设置里面用maa开头那个触控模式试试，听说的，不一定管用

连接设置里我全用的实验性的选项，包括 maatouch 和 adb lite，目前只在 mumu12 上遇到暂停的问题，我观察到的是在一直暂停之前会反复暂停/取消暂停查看同一个没有 cd 好的角色，次数多了就暂停不取消了，直到 10 分钟超时放弃战斗

**Comment by cenfusheng** [comment]
非极限作业不建议开暂停下干员，延迟稍微高一点就会卡在暂停，mumu12似乎是因为支持截图方法的问题延迟稍高一点，不是maa目前可以优化的。
