### ISSUE TITLE
自动战斗连接模拟器提示读取文件失败

### ISSUE THREAD

**Issue by RAYWRYY** [MaaAssistantArknights/MaaAssistantArknights#3898]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗连接模拟器提示读取文件失败。但是其他日常一键长草没有问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10897280/asst.log)
2023-03-06 18:43:29.913

### 截图

![F 3Q L6% SJR2938{BS{G{8](https://user-images.githubusercontent.com/104955072/223089817-8b05bf34-75c2-44ec-a05d-fbd6f80a6e06.png)

**Comment by ABA2396** [comment]
文件解析错误了，发一下这个文件看看

**Comment by RAYWRYY** [comment]
> 

[MAACopilot_龙门商业街摆完挂机.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10897375/MAACopilot_.zip)
就是在作业网站下的，应该和文件没关系，我找了好几个作业都提示这个错误。

**Comment by ABA2396** [comment]
试试把文件放在没有中文的路径下，再不行试试看重下MAA能不能解决

**Comment by RAYWRYY** [comment]
> 
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10897655/asst.log)
![)0H K}HI%OHBC@PK4$08WH7](https://user-images.githubusercontent.com/104955072/223099713-fac8e0d1-9661-4419-bf8d-5813840172c7.png)


把路径名字全改了，重启了电脑也还是不行

**Comment by Neteraxe** [comment]
[2023-03-06 19:35:33.308][ERR][Px3720][Tx3724] Json parse failed E:\111.json invalid unordered_map<K, T> key
提供下111.json文件
文件的json格式不正常

**Comment by RAYWRYY** [comment]
> [2023-03-06 19:35:33.308][错误][px3720][TX3724]Json 解析失败 E：\111.json 无效 unordered_map<K， T> key 提供下111.json文件 文件的 json格式不正常

[111.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10897744/111.zip)
这是我自己改了名字，原来名字是有中文的，而且没改之前我也试过了，也是不行

**Comment by Neteraxe** [comment]
map没有对应的key，应该是没有读到文件
我不是这个组织里的人，这块要看他们的经验了

**Comment by RAYWRYY** [comment]
> map没有对应的key，应该是没有读到文件 我不是这个组织里的人，这块要看他们的经验了

怎么会所有的作业都没key呢，我还以为是我的问题呢...

**Comment by ABA2396** [comment]
这个文件我是能用的，不知道为啥你那里解析失败了

**Comment by shangxing312** [comment]
我也有这种情况

**Comment by chip-away34** [comment]
这个问题我也遇到了，原因是识别关卡名的代码不一样，正常应该是stage_name，如果是网站上下载的是stageName，自己手动修改一下就能用了

**Comment by Black1312** [comment]
读取文件失败，请使用“神秘代码”此问题属于作业站bug。提示“不支持的关卡”需要更新maa版本，如最新版仍提示该问题，请前往https://github.com/yuanyan3060/Arknights-Bot-Resource/blob/main/levels.json下载levels.json将其放至MAA\resource\Arknights-Tile-Pos目录中，重启MAA再试（MAA要求高于4.12.3版本）

**Comment by Black1312** [comment]
补充：作业站该bug已修复
