### ISSUE TITLE
肉鸽选干员时异格与原干员不分

### ISSUE THREAD

**Issue by drway** [MaaAssistantArknights/MaaAssistantArknights#390]
在config.json中配置肉鸽招募选择有异格的干员，
且同时拥有原干员和异格干员，会出现选择异格干员而不是原干员的情况
如配置为：克洛丝
实际会选到：寒芒克洛丝
炎熔也会出现同样问题

**Comment by zhongfly** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/194 作者还没处理

**Comment by zzyyyl** [comment]
[#385](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/385#issuecomment-1114010173) 玛丽已经放话摆烂了，估计短期内不会处理了（
