### ISSUE TITLE
请问MAA支持自动通过 永恒愤怒 这一关吗?

### ISSUE THREAD

**Issue by zero27613** [MaaAssistantArknights/MaaAssistantArknights#3902]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题,想着用MAA自动刷出永恒愤怒并通过解锁捕鳞蓑.
使用MAA挂了两周水月肉鸽0难度,累积探索超过100-200把,仍旧未解锁捕鳞蓑,不知道是我的运气太差还是MAA不支持永恒愤怒这关?

我对此提出疑问是因为有几次看到MAA日志显示 险路恶敌 险路恶敌  ,然后直接重开了.

### 有什么好的想法？

肉鸽设置加一个新的策略.
类似于刷源石锭的策略, 目标设置为: 进入第三层时识别是否为永恒愤怒, 是的话继续打直到通过第三层BOSS, 不是的话直接重开.
如果遇到迷雾, 就继续打直到打过三层关底.
或者简化一点,任何情况下都直接打通第三层后退出重开.

### 其他内容

![L6(5@_MYRG3{B~$W_7)6BRW](https://user-images.githubusercontent.com/59275169/223140412-fe218877-232f-4dc2-b8d6-5bd8befe4bca.png)

**Comment by MistEO** [comment]
日志发下

**Comment by zero27613** [comment]
> 日志发下
em,当时没截,我再遇到再截吧

**Comment by MistEO** [comment]
@WWPXX233 有没有空写下这关（

**Comment by zero27613** [comment]
> @WWPXX233 有没有空写下这关（

不好写通关策略的话,可以试试进入第三层后识别是否为永恒愤怒,是的话弹提示,不是的话直接重开

**Comment by zero27613** [comment]
> @WWPXX233 有没有空写下这关（

另外提一嘴, 日志里完全没看到过订正(纠错的变异关, 延命塑路者), 不知道这个是确实没遇到,还是直接连识别都没识别.

**Comment by WWPXX233** [comment]
@MistEO 我很久之前就写了 是有的不过这个直接重开emmmm不知道怎么回事

**Comment by MistEO** [comment]
> @MistEO 我很久之前就写了 是有的不过这个直接重开emmmm不知道怎么回事
> 

没重开，你看他发的是战斗了两分钟失败了

**Comment by zero27613** [comment]
> @MistEO 我很久之前就写了 是有的不过这个直接重开emmmm不知道怎么回事
重开的也是有的
![image](https://user-images.githubusercontent.com/59275169/225855495-60db6be8-3301-45f6-935c-3f06cafbbd82.png)

**Comment by zero27613** [comment]
> @MistEO 我很久之前就写了 是有的不过这个直接重开emmmm不知道怎么回事

重开也是有的
![Y06PW%K_IOL_ TGBW_$H{(K](https://user-images.githubusercontent.com/59275169/225855690-c3b28d9e-465b-4348-899b-98743fb50111.png)

**Comment by zero27613** [comment]
> @MistEO 我很久之前就写了 是有的不过这个直接重开emmmm不知道怎么回事

那能不能加个策略, 打到第三层时识别一下BOSS是不是永恒愤怒, 不是的话重开,是的话弹个提示然后停止.

**Comment by MistEO** [comment]
> > @MistEO 我很久之前就写了 是有的不过这个直接重开emmmm不知道怎么回事
> 
> 重开也是有的
> ![Y06PW%K_IOL_ TGBW_$H{(K](https://user-images.githubusercontent.com/59275169/225855690-c3b28d9e-465b-4348-899b-98743fb50111.png)
> 

日志不是这个，是 debug/asst.log

**Comment by zero27613** [comment]
> > > @MistEO 我很久之前就写了 是有的不过这个直接重开emmmm不知道怎么回事
> > 
> > 
> > 重开也是有的
> > ![Y06PW%K_IOL_ TGBW_$H{(K](https://user-images.githubusercontent.com/59275169/225855690-c3b28d9e-465b-4348-899b-98743fb50111.png)
> 
> 日志不是这个，是 debug/asst.log

那我不清楚了, 我的asst.log打不开, asst.bak.log是3月15的

**Comment by MistEO** [comment]
不是，你把它发出来。。

**Comment by zero27613** [comment]
> 不是，你把它发出来。。

这里只能传最大25M的文件, 去哪里传给你们啊?

**Comment by WWPXX233** [comment]
> > 不是，你把它发出来。。
> 
> 这里只能传最大25M的文件, 去哪里传给你们啊?

可以分卷压缩一下
