### ISSUE TITLE
能不能在基建设置里加上训练室选项？

### ISSUE THREAD

**Issue by Obsidian105** [MaaAssistantArknights/MaaAssistantArknights#3904]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

自动基建总是撤回在训练室专精的培训干员，尤其是艾丽妮，一旦撤回加成将会被取消

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/223219290-f6a36d9f-b6d4-4f14-b999-777ffd8a95f0.png)
