### ISSUE TITLE
抄作业干员组没有优先级

### ISSUE THREAD

**Issue by lai10000ting** [MaaAssistantArknights/MaaAssistantArknights#3905]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

干员组没有优先级

### 有什么好的想法？

希望可以设置优先级，优先选攻略里的干员

**Comment by MistEO** [comment]
现在是按练度排序的
