### ISSUE TITLE
新活动sn刷理智失败

### ISSUE THREAD

**Issue by pearhield** [MaaAssistantArknights/MaaAssistantArknights#391]
活动风格ui的问题？希望适配一下~

**Comment by MistEO** [comment]
请附上日志，谢谢

**Comment by pearhield** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8598749/asst.log)
杀进程重试后，好像又可以愉快的挂机了，嘿嘿

**Comment by MistEO** [comment]
v3.2 fixed
