### ISSUE TITLE
活动【落叶逐火】关卡选择

### ISSUE THREAD

**Issue by DreAmVirGo** [MaaAssistantArknights/MaaAssistantArknights#3911]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

刷理智时关卡选择只有CF-8

### 有什么好的想法？

虽然掉落相同，但是也希望能加一下6和7。在时间效率方面7比8快不少

**Comment by mon030** [comment]
在MAA战斗设置里勾选[手动输入关卡名]即可自行选择作战关卡。

**Comment by ABA2396** [comment]
> 在MAA战斗设置里勾选[手动输入关卡名]即可自行选择作战关卡。

只有八做了导航，其他两个找不到的。

**Comment by DreAmVirGo** [comment]
> 在MAA战斗设置里勾选[手动输入关卡名]即可自行选择作战关卡。

导航不到。
现在只能通过当前/上次来刷理智，但是这样就需要自己手动关闭刷信赖借助战（无限OF-F1警告）

![image](https://user-images.githubusercontent.com/28724211/223627992-ded3c14a-4256-44f6-b2e3-89565739f436.png)
![image](https://user-images.githubusercontent.com/28724211/223628036-aee262fc-5c3c-432a-8910-0aee48509ad5.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10917503/asst.log)

**Comment by ABA2396** [comment]
> > 在MAA战斗设置里勾选[手动输入关卡名]即可自行选择作战关卡。
> 
> 导航不到。 现在只能通过当前/上次来刷理智，但是这样就需要自己手动关闭刷信赖借助战（无限OF-F1警告）
> 
> ![image](https://user-images.githubusercontent.com/28724211/223627992-ded3c14a-4256-44f6-b2e3-89565739f436.png) ![image](https://user-images.githubusercontent.com/28724211/223628036-aee262fc-5c3c-432a-8910-0aee48509ad5.png) [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10917503/asst.log)

关卡选择是当前上次的话不会去打刷信赖的关卡的
