### ISSUE TITLE
adb修改分辨率后仍然无法识别

### ISSUE THREAD

**Issue by YiyangWilliam** [MaaAssistantArknights/MaaAssistantArknights#3914]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

设备rock pi5b 安卓版本12 已经设置了分辨率，仍然无法识别

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10917517/asst.log)

### 截图

![bug1](https://user-images.githubusercontent.com/52186336/223628617-987de9f5-7495-4e48-9d7a-4f073050229c.png)
![bug2](https://user-images.githubusercontent.com/52186336/223628622-ea349e4c-4973-4134-950d-9c6d4f01e651.png)

**Comment by MistEO** [comment]
```log
[2023-03-08 13:23:43.608][INF][Px5f0c][Tx1b94] Call ` C:\Users\19795\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 10.40.53.153:46393 shell dumpsys window displays | grep -o -E cur=+[^\ ]+ | grep -o -E [0-9]+ ` ret 0 , cost 109 ms , stdout size: 23 , socket size: 0
[2023-03-08 13:23:43.608][TRC][Px5f0c][Tx1b94] stdout output:
1200

1920

1280

720


```

不知道这个输出怎么来的，你可以试试自己手动改下这个正则，在 resource/config.json 里

**Comment by YiyangWilliam** [comment]
[输出.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10921184/default.txt)
这是dumpsys window displays的输出，看起来好像有两个display id，我应该用哪个模式或者在哪里加限制让他在指定的地方运行？
