### ISSUE TITLE
Python接口无法正常导航至活动【落叶逐火】的关卡

### ISSUE THREAD

**Issue by yokinanya** [MaaAssistantArknights/MaaAssistantArknights#3916]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

通过Python接口调用MAA的情况下，在Alas手动输入活动【落叶逐火】的关卡名会在执行到刷理智任务時直接原地卡住，包括输入MAA本体已经适配的CF-8也无法正常导航，上传的Log是Alas的Log。

补充：
在不使用Alas，使用Maa文件夹下的sample.py，只保留开始唤醒和刷理智，并把关卡改为CF-8后，会在运行到刷理智的任务时直接退出，没有任何报错提示

### 日志文件

[2023-03-08_maa.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10918912/2023-03-08_maa.txt)

**Comment by ABA2396** [comment]
活动的导航放在[web](https://ota.maa.plus/MaaAssistantArknights/api/resource/)上，需要ui自己下载

**Comment by ChildeRolando** [comment]
下载之后自己添加到\resource\tasks.json中即可解决，但这是为何？为何这次更新要手动添加了？

**Comment by ABA2396** [comment]
新版本会加到release的，只是新版本没发版的时候老版本可以通过web下载。只做导航不容易出问题，而活动一出就发版本可能会炸
