### ISSUE TITLE
活动ui不会自动勾选代理

### ISSUE THREAD

**Issue by ABA2396** [MaaAssistantArknights/MaaAssistantArknights#392]
![Screenshot_2022 05 01_18 58 20 661](https://user-images.githubusercontent.com/99072975/166143005-6570249d-91d5-4b44-9751-6c08f0cd2da8.png)
![Screenshot_2022 05 01_18 58 26 444](https://user-images.githubusercontent.com/99072975/166143016-ea814319-4a3c-4b12-b1fe-9faf68136504.png)

**Comment by ABA2396** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8598760/asst.log)
掉落识别也有问题）
![image](https://user-images.githubusercontent.com/99072975/166143309-b4faf959-924c-4218-88ad-4b014390d5f9.png)

**Comment by ABA2396** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8598764/asst.log)
掉落识别也有问题，识别到无掉落

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/166143417-c55bf16f-e1b9-4e31-92e2-1d40f2bdd47d.png)

**Comment by MistEO** [comment]
v3.2 fixed
