### ISSUE TITLE
自定义基建换班发电机站和宿舍换班失败

### ISSUE THREAD

**Issue by nodks** [MaaAssistantArknights/MaaAssistantArknights#3922]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

1.发电站换班有时会跳过第三个发电站或者同时跳过第二第三个发电站，如今早8：00跳过了第三个发电站。
2.大多数时候只有第一个宿舍会换班。如8：03开始的宿舍换班。
夜神模拟器和蓝叠模拟器均有此bug.

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10926419/asst.log)

### 截图

![屏幕截图(19)](https://user-images.githubusercontent.com/127360125/223882995-15ebfaa2-c578-4bc5-bb0d-c09be8df0571.png)

**Comment by ABA2396** [comment]
出现多次名字是人没找到

**Comment by MistEO** [comment]
> 版本？很奇怪，按道理会尝试3次，你才失败了2次

版本 log 开头就有
