### ISSUE TITLE
StartUP失败

### ISSUE THREAD

**Issue by Nefelibater** [MaaAssistantArknights/MaaAssistantArknights#3923]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

后续自动长草功能正常，但无法启动明日方舟，手动点击游戏图标进入加载界面后才能执行后续过程，adb也正常。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10927015/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/116096983/223898339-eca95539-2715-4e2c-ae38-fd3fc774fbb2.png)

### 还有别的吗？

蓝叠模拟器最新版本(国内)

**Comment by zzyyyl** [comment]
选择一下客户端（
