### ISSUE TITLE
借助战嫖信用不工作

### ISSUE THREAD

**Issue by MigdalBavel** [MaaAssistantArknights/MaaAssistantArknights#3924]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![QQ截图20230309122608](https://user-images.githubusercontent.com/105539375/223916885-33b8b94f-7064-494c-85c7-82a4c8a547a2.png)
![QQ截图20230309122615](https://user-images.githubusercontent.com/105539375/223916894-bf8db34d-b1e7-440c-b93c-d188fdb8eb02.png)

之前版本工作正常的。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10927756/asst.log)

**Comment by zzyyyl** [comment]
关卡选择是 当前/上次 的时候不会去嫖的（不然导航就寄了）

**Comment by zzyyyl** [comment]
不过好像你也没点刷理智（
问问 @ABA2396

**Comment by ABA2396** [comment]
鼠标放助战刷信用上就有提示了）

**Comment by MigdalBavel** [comment]
> 鼠标放助战刷信用上就有提示了）

原来还有这种保险机制。之前一直没试过这种组合。
