### ISSUE TITLE
需加载一次“设置”选项卡后热键才生效

### ISSUE THREAD

**Issue by xjr353171020** [MaaAssistantArknights/MaaAssistantArknights#3929]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我在C++中使用以下语句唤起MAA并模拟键盘按键link start

`WinExec("F:\\Program Files\\MAA-1\\MAA.exe",SW_NORMAL);`
`Sleep(5000);`
`keybd_event(VK_LMENU,0x12,0,0);`
`keybd_event(VK_NUMPAD1,0x61,0,0);`
`	keybd_event(VK_NUMPAD1,0x61,KEYEVENTF_KEYUP,0);`
`	keybd_event(VK_LMENU,0x12,KEYEVENTF_KEYUP,0);`

若不在发送热键前点击设置选项卡，则无任何反应。
后用键盘测试，问题仍存在。

### 日志文件

[Uploading asst.log…]()

### 还有别的吗？

Win11，夜神模拟器

**Comment by MistEO** [comment]
问题存在，不过可以先试试这两个选项

![image](https://user-images.githubusercontent.com/18511905/224211863-0c92b0b0-6c61-4d22-b56b-ec78cf87cce8.png)
