### ISSUE TITLE
连接模拟器失败 

### ISSUE THREAD

**Issue by drway** [MaaAssistantArknights/MaaAssistantArknights#393]
![image](https://user-images.githubusercontent.com/78285587/166151514-9f633538-a247-4660-8e5a-958756ce1930.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8599156/asst.log)
模拟器：蓝叠国际（Hyper-V）
cmd手动连adb似乎没问题

**Comment by MistEO** [comment]
adb 路径不对
