### ISSUE TITLE
4.12.0Beta3还是无法识别CE-6的技能

### ISSUE THREAD

**Issue by yd278** [MaaAssistantArknights/MaaAssistantArknights#3931]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

和https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3551 一样的情况，反复点开棘刺然后退出来

有没有可能是因为CE-6地图比较小，所以技能框位置和其他地图有一些偏差？
（反正每次我用蓝叠的键盘映射在CE-6想开技能都会点歪来）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10934883/asst.log)

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/224211545-302c9df9-7801-450d-b066-847be5cb76c0.png)

已修复的是这个的识别，点开之后的还没处理
