### ISSUE TITLE
是否可以做一个反复刷保全派驻第一二关卡的功能，现在真的很不想玩保全，非常无聊

### ISSUE THREAD

**Issue by Obsidian105** [MaaAssistantArknights/MaaAssistantArknights#3932]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

将保全派驻加入日常长草，只刷一二关的话随便带个基石就可以

**Comment by ABA2396** [comment]
\resource\copilot

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/224212007-2b9cf2bd-0231-4126-aa15-5df10e8fdcaf.png)

https://www.bilibili.com/video/BV1c8411w7DX
