### ISSUE TITLE
简化设置界面，将不常用/小众的设置从界面上移除，用户通过手动修改 gui.json 处理，并补充详细文档

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#3934]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3879

**Comment by MigdalBavel** [comment]
支持，就是得让修改的能更新后也保存

**Comment by ABA2396** [comment]
> 支持，就是得让修改的能更新后也保存

更新不影响gui.json

**Comment by liuyifan-eric** [comment]
直接移出gui手动改json吗？要不弄个“高级...”按钮？

**Comment by MistEO** [comment]
> 直接移出gui手动改json吗？要不弄个“高级...”按钮？

不会写.jpg

**Comment by moomiji** [comment]
#4556
