### ISSUE TITLE
maa新版无法打开

### ISSUE THREAD

**Issue by akikocc** [MaaAssistantArknights/MaaAssistantArknights#3936]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

https://imgloc.com/i/oetBo
https://imgloc.com/i/oeWJN

上一个版本可以正常运行，新活动更新了一下之后就再也打不开了/悲
原本想着等修复，过了几天还是这样，就自己来提交一下bng

### 日志文件

没有生成对应的日志文件

### 还有别的吗？

版本	Windows 10 专业版
版本号	21H2
安装日期	‎2022/‎10/‎25
操作系统内部版本	19044.2130
体验	Windows Feature Experience Pack 120.2212.4180.0

**Comment by MistEO** [comment]
之前自动更新出 bug 了，重新下载下吧

~~另外都无法打开了，等有啥用x~~

**Comment by Black1312** [comment]
请删除全部文件，重新下载最新版完整包解压，如还有问题请再次提交issue
