### ISSUE TITLE
雷电及蓝叠国际刷肉鸽时游戏卡死

### ISSUE THREAD

**Issue by yuanel** [MaaAssistantArknights/MaaAssistantArknights#3939]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷水月肉鸽时会整个游戏卡死，一开始用雷电模拟器出现这个问题在问题反馈里看别人说是内存占用满了，就换了蓝叠国际，但也出现了同样的问题。只是游戏卡死，模拟器并未卡死，使用其他功能时一切正常

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10939459/asst.log)
时间大概是3.10的14：49左右

### 还有别的吗？

雷电模拟器及蓝叠模拟器国际版，win11

**Comment by liuyifan-eric** [comment]
模拟器分配的内存不够？

**Comment by yuanel** [comment]
> 模拟器分配的内存不够？

目前分配是4GB内存，需要多少哇

**Comment by WWPXX233** [comment]
是游戏卡死还是MAA卡死

**Comment by WWPXX233** [comment]
那看来是游戏的问题
