### ISSUE TITLE
企鹅物流上传异常

### ISSUE THREAD

**Issue by LuxuriantHuang** [MaaAssistantArknights/MaaAssistantArknights#394]
愚人号关卡出现识别为无掉落并提示上传企鹅数据错误（不管是否存在材料掉落都可能触发）

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8599182/asst.log)
图中已完成的两次提示无当次掉落的作战实际均掉落材料
![QQ截图20220501230518](https://user-images.githubusercontent.com/58197458/166152033-0fb39ca3-5ca1-4a2a-bf6c-ab4585a6b544.png)

**Comment by MistEO** [comment]
v3.2 fixed
