### ISSUE TITLE
希望支持蓝叠国际在Hyper-V的Pie引擎模式下的随机端口号读取

### ISSUE THREAD

**Issue by muyuanjin** [MaaAssistantArknights/MaaAssistantArknights#3946]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在启用了windows虚拟机Hyper-V时，蓝叠模拟器将只支持随机端口号

### 有什么好的想法？

随机端口号等配置数据默认存储在`C:\ProgramData\BlueStacks_nxt\bluestacks.conf`文件
如多开引擎创建了引擎实例 `A` 和 `B`
那么在`bluestacks.conf`文件中，`A` 和 `B`的端口号如下：
```
bst.instance.A.adb_port="5555" # 固定端口号，普通引擎模式下生效，在Hyper-V模式下无效
bst.instance.A.status.adb_port="50606" #在模拟器启动后会被修改为该实例的此次启动的随机端口号
...
bst.instance.B.adb_port="5585" 
bst.instance.B.status.adb_port="50446"
```
通常来说`A`和`B`以` Nougat64`、`Nougat32`、`Pie64`、`Rvc64`开头的字符串，并且Hyper-V模式下`Pie`引擎必须使用管理员权限启动，也就是说如果MAA需要使用自动开启模拟器功能时，MAA也必须是管理员权限启动（或可增加相对应的提示）

idea:
`读取bluestacks.conf文件，筛选出instance名`——>`文件中或当前启动设置中instance名是否Pie开头`——>`检测是否为管理员权限，不是则提醒`——>**`使用附加命令--instance <实例名> 启动蓝叠多开实例` ——>`读取bluestacks.conf`——>`找到bst.instance.<实例名>.status.adb_port="<端口号>"`——>`以该端口号连接adb`**

**Comment by horror-proton** [comment]
https://maa.plus/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.html#%E2%9C%85-%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8-hyper-v-%E7%89%88%E6%9C%AC

**Comment by muyuanjin** [comment]
> [蓝色仿真器 Hyper-V 版本](https://maa.plus/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.html#%E2%9C%85-%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8-hyper-v-%E7%89%88%E6%9C%AC)

原来在这里，眼瞎了，感谢
