### ISSUE TITLE
截图识别出错

### ISSUE THREAD

**Issue by StellAr117** [MaaAssistantArknights/MaaAssistantArknights#395]
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8599185/asst.log)
mumu模拟器 1920*1080分辨率，打活动第八关的时候掉落识别一直识别为空，没截到图
Thanks♪(･ω･)ﾉ

**Comment by MistEO** [comment]
v3.2 fixed

**Comment by StellAr117** [comment]
![image](https://user-images.githubusercontent.com/104726749/166153726-99f38ffa-d5fc-464e-a429-92031af1a18b.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8599249/asst.log)
![image](https://user-images.githubusercontent.com/104726749/166153765-89d98926-c682-4721-9b11-3cf547ae11e0.png)

已经更新3.2版本后仍然存在问题

**Comment by MistEO** [comment]
> ![image](https://user-images.githubusercontent.com/104726749/166153726-99f38ffa-d5fc-464e-a429-92031af1a18b.png) [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8599249/asst.log) ![image](https://user-images.githubusercontent.com/104726749/166153765-89d98926-c682-4721-9b11-3cf547ae11e0.png)
> 
> 已经更新3.2版本后仍然存在问题

第9关么？再来个日志康康

**Comment by StellAr117** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8599256/asst.log)
第八关，

**Comment by lulu666lulu** [comment]
同mumu，选择上次作战时活动第八关无法自动进入，需要手动点关卡才可以

**Comment by MistEO** [comment]
v3.2.1 fixed
