### ISSUE TITLE
MAA4.12-RC1 更新后无法打开GUI界面

### ISSUE THREAD

**Issue by Luminphantom** [MaaAssistantArknights/MaaAssistantArknights#3950]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新最新的 4.12-RC1版本后，无法打开GUI界面

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10947449/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10947450/gui.log)

### 截图
图1：![image](https://user-images.githubusercontent.com/52663268/224461722-d2d2c68b-753c-4f6b-926f-f4961020f730.png)
图2：![image](https://user-images.githubusercontent.com/52663268/224461727-8dcc1073-b301-4654-bde8-77ca6d6ce993.png)
图3：![image](https://user-images.githubusercontent.com/52663268/224461732-0734965a-107e-4b7c-8e04-8bd99100b271.png)
图1：官网下载的4.11版，gui界面能打开；图2：显示更新完成，但无法点击图中的两个框；图3：点击MAA图标无法打开gui界面，只有右键能显示页面

**Comment by ntgmc** [comment]
给一个解决方法：任务管理器把maa taskkill掉重新打开就行，会重新解压更新包

**Comment by Luminphantom** [comment]
> 

感谢你的回复，但我试过了这样没有用。我尝试过：1.如你所述，Kill task重新打开；2.重新安装4.11版本，然后替换当前gui.json等自动更新，依旧无法打开

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/224468537-d483d6e5-3e28-4c44-8d78-ac76279f183a.png)
4.11更新4.12-RC1没有复现成功，先试试重启电脑）

**Comment by Luminphantom** [comment]
刚刚尝试在4.11版本下选择公测版更新4.12-RC1成功。我怀疑是此前的GUI.json文件出现了问题，直接安装4.11版本，并且替换GUI.JSON后的自动下载会出现4.12-RC1中GUI界面无法打开的问题，附上GUI文件如下（转成了TXT）：
[GUI.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10947783/GUI.txt)

**Comment by MistEO** [comment]
感觉是生息演算开关去掉导致的

**Comment by ABA2396** [comment]
> 感觉是生息演算开关去掉导致的

这不是弹窗没显示出来吗

**Comment by MistEO** [comment]
> > 感觉是生息演算开关去掉导致的
> 
> 这不是弹窗没显示出来吗

他说重新下载新版，能用了，但是把老的 gui.json 放进去，就又白屏了

**Comment by ABA2396** [comment]
> > > 感觉是生息演算开关去掉导致的
> > 
> > 这不是弹窗没显示出来吗
> 
> 他说重新下载新版，能用了，但是把老的 gui.json 放进去，就又白屏了

我试了下也打开了

**Comment by mojerro** [comment]
我也遇到这个问题了，或者说是不同版本遇到过好几次了，现在是`v4.12.3`，删除`gui.json`后恢复正常

**Comment by mojerro** [comment]
我觉得这不是啥大问题，但是建议官方在文档或者应用页面比较醒目的位置提示一下，因为只要配置改的多一点，好像就会遇到

**Comment by Luminphantom** [comment]
> > > > 感觉是生息演算开关去掉导致的
> > > 
> > > 
> > > 这不是弹窗没显示出来吗
> > 
> > 
> > 他说重新下载新版，能用了，但是把老的 gui.json 放进去，就又白屏了
> 
> 我试了下也打开了

总结：结合楼下mojerro的情况。1）：bug可能的原因。出现这个bug的原因是gui.json文件导致的，大概配置比较多的时候会出现这个bug。2）：解决方法。不要用原先的gui.json配置，直接下载官方最新的更新上去后手动重配gui.json吧。3）：建议。可以在官网手册QA中提示下该问题。
