### ISSUE TITLE
通关肉鸽之后，经常不会自动跳过剧情

### ISSUE THREAD

**Issue by SaumYY** [MaaAssistantArknights/MaaAssistantArknights#3951]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我用maa通关傀影肉鸽之后，仅有一次脚本会跳过剧情，然后提示“肉鸽通关”。后面全是打完最终关卡不会跳过剧情，maa提示截图失败，重启或更换模拟器。这两我都试过，然并卵。

### 日志文件

时间是。2020-03-11 11：54：40左右
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10947607/asst.log)

### 截图

![2023-03-11_11-55-19-670_raw](https://user-images.githubusercontent.com/127578969/224465124-278f1af5-2864-4f5c-b671-73c2b49efca1.png)
![2023-03-11_11-55-22-985_raw](https://user-images.githubusercontent.com/127578969/224465141-e5995b70-f4c3-46c8-a470-350a6e45a4a1.png)

### 还有别的吗？

使用的是蓝叠，国际版。系统是win 10，电脑是拯救者r7000p

**Comment by SaumYY** [comment]
![Uploading 屏幕截图 2023-03-11 123059.png…]()

**Comment by SaumYY** [comment]
脚本没跳过剧情的时候，maa的提示是这个
![屏幕截图 2023-03-11 123059](https://user-images.githubusercontent.com/127578969/224465283-3ac5ccd0-a66a-4272-8516-b2836623d8a2.png)

**Comment by MistEO** [comment]
用挂的不要来反馈，出问题血也不要溅到我们身上
