### ISSUE TITLE
肉鸽打通过后，请增加相关的点击脚本

### ISSUE THREAD

**Issue by 2727658361** [MaaAssistantArknights/MaaAssistantArknights#3955]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

肉鸽打通过后会出现几个界面，脚本没有识别并点击，就停止在那个界面了，我希望能增加点击跳过的脚本，并自动开启新的肉鸽

**Comment by 2727658361** [comment]
<img width="1259" alt="360截图17001016456445" src="https://user-images.githubusercontent.com/79258319/224474722-dcdf5e82-bbdb-4295-ab79-10bf011b1857.png">
<img width="1259" alt="360截图18430701304834" src="https://user-images.githubusercontent.com/79258319/224474726-05fda3e0-8041-4d34-bbad-f89619242104.png">
<img width="1259" alt="360截图184702026176107" src="https://user-images.githubusercontent.com/79258319/224474728-b26d38f8-dadd-47e8-8dc3-2376343ee4b0.png">
<img width="1259" alt="360截图178606028812675" src="https://user-images.githubusercontent.com/79258319/224474731-e9ca4f87-a798-4056-bfec-6d6543141be4.png">
<img width="1259" alt="360截图18280503104122134" src="https://user-images.githubusercontent.com/79258319/224474735-bdc864f7-d4da-4b3a-9a6c-9aeb419bfef2.png">
<img width="1259" alt="360截图16720405554541" src="https://user-images.githubusercontent.com/79258319/224474736-9b0a123a-21ff-4569-be22-cafa05e7f477.png">
<img width="1259" alt="360截图18720122204715" src="https://user-images.githubusercontent.com/79258319/224474737-0feb7c90-3873-43ec-b2a6-70c153a04cec.png">
<img width="1259" alt="360截图167204016983107" src="https://user-images.githubusercontent.com/79258319/224474738-7afce78d-3f01-4556-8edf-48bab8c83b62.png">
<img width="1259" alt="360截图18770522717859" src="https://user-images.githubusercontent.com/79258319/224474742-b3d6a593-4f81-45f9-a4b8-35aa9b4eea4a.png">

**Comment by ABA2396** [comment]
估计是太黑了压缩之后图片太小认为截图失败了

**Comment by liuyifan-eric** [comment]
这应该是bug吧？卡在了哪个界面？可以传下log吗

**Comment by skzidan** [comment]
> <img alt="360截图17001016456445" width="1259" src="https://user-images.githubusercontent.com/79258319/224474722-dcdf5e82-bbdb-4295-ab79-10bf011b1857.png">
> 
> <img alt="360截图18430701304834" width="1259" src="https://user-images.githubusercontent.com/79258319/224474726-05fda3e0-8041-4d34-bbad-f89619242104.png">
> 
> <img alt="360截图184702026176107" width="1259" src="https://user-images.githubusercontent.com/79258319/224474728-b26d38f8-dadd-47e8-8dc3-2376343ee4b0.png">
> 
> <img alt="360截图178606028812675" width="1259" src="https://user-images.githubusercontent.com/79258319/224474731-e9ca4f87-a798-4056-bfec-6d6543141be4.png">
> 
> <img alt="360截图18280503104122134" width="1259" src="https://user-images.githubusercontent.com/79258319/224474735-bdc864f7-d4da-4b3a-9a6c-9aeb419bfef2.png">
> 
> <img alt="360截图16720405554541" width="1259" src="https://user-images.githubusercontent.com/79258319/224474736-9b0a123a-21ff-4569-be22-cafa05e7f477.png">
> 
> <img alt="360截图18720122204715" width="1259" src="https://user-images.githubusercontent.com/79258319/224474737-0feb7c90-3873-43ec-b2a6-70c153a04cec.png">
> 
> <img alt="360截图167204016983107" width="1259" src="https://user-images.githubusercontent.com/79258319/224474738-7afce78d-3f01-4556-8edf-48bab8c83b62.png">
> 
> <img alt="360截图18770522717859" width="1259" src="https://user-images.githubusercontent.com/79258319/224474742-b3d6a593-4f81-45f9-a4b8-35aa9b4eea4a.png">

can you send me yous IS setting screenshot ?

**Comment by 2727658361** [comment]
> 这应该是bug吧？卡在了哪个界面？可以传下log吗
卡在那个全黑的界面
<img width="960" alt="360截图17860603115922" src="https://user-images.githubusercontent.com/79258319/224527858-191e5910-8b90-4185-a1be-43a9903f
<img width="600" alt="360截图1820042681104130" src="https://user-images.githubusercontent.com/79258319/224527861-44504209-c862-4356-b85a-976179768e81.png">
56dd.png
<img width="1278" alt="360截图1769062590117109" src="https://user-images.githubusercontent.com/79258319/224527864-0fe7345a-28d7-4816-be1f-644d3913b0c5.png">
">

**Comment by 2727658361** [comment]
> 这应该是bug吧？卡在了哪个界面？可以传下log吗

卡在那个全黑的界面
<img width="1278" alt="360截图1769062590117109" src="https://user-images.githubusercontent.com/79258319/224527924-8b4bce67-1318-4f58-a3ee-317a151f7628.png">
<img width="600" alt="360截图1820042681104130" src="https://user-images.githubusercontent.com/79258319/224527926-7c240a4f-6192-4bbb-acd7-c606cbd14d29.png">
<img width="960" alt="360截图17860603115922" src="https://user-images.githubusercontent.com/79258319/224527928-c1c04578-b658-4597-8098-59a36a2bc09d.png">

**Comment by 2727658361** [comment]
> 这应该是bug吧？卡在了哪个界面？可以传下log吗

确实应该是bug，就傀影肉鸽会卡在那个黑色的界面，水月肉鸽没有那个黑色的界面所以不会卡
