### ISSUE TITLE
在进入肉鸽商店时购买自动进阶道具而没有使用

### ISSUE THREAD

**Issue by dustmirror** [MaaAssistantArknights/MaaAssistantArknights#3956]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如标题，在进入肉鸽商店时购买了无需希望就可以进阶的道具，但在有可进阶的百炼嘉维尔的情况下MAA选择不进阶并且直接退出，浪费了源石锭，出现此BUG的位置在2023-03-11  17:21:34进入诡意行商开始，直到03-11  17:22:29之前结束，没来得及阻止，也没截上图

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10948160/asst.log)

### 还有别的吗？

夜神模拟器
win7系统

**Comment by ABA2396** [comment]
看错了）是说买了但没用然后直接浪费了？

**Comment by dustmirror** [comment]
> 看错了）是说买了但没用然后直接浪费了？

对，买了，能用，没有用，浪费了，这是一点。另外还有一个建议和一个错误，错误是局内时MAA会时不时点撤退以后在冷却的干员，另一个建议是现在的MAA挑干员不成体系，战斗掉落的招募卷只招募干员，而且拿的都不一定是体系内的干员，比如寒芒克罗斯百嘉炼老爷子这类配合某些藏品很强的干员或者对策干员MAA永远不拿，15级的水月，棘刺什么的反而拿的特别频繁，打也打不动，咔咔死，打图的时候有阻挡的干员亮了，硬是要下高费或者CD中的干员，就像这个干员不站在那个地块朝向某个方向MAA就难受似的，过图思路太捞了，不知道能不能用AI训练什么的试试，智能太低了

**Comment by dustmirror** [comment]
> 看错了）是说买了但没用然后直接浪费了？

这个做的很牛的，但还有错误，也是麻烦您了

**Comment by ABA2396** [comment]
这个只是拿来刷等级的，一般打三四级就差不多了，思路也是按低层通关排的

**Comment by SnowLancelot** [comment]
刷等级就是无脑刷的，不是拿来通关的，虽然确实有人挂通关了
