### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by MicardoF** [MaaAssistantArknights/MaaAssistantArknights#3958]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开弹窗报错

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10948520/asst.log)

### 截图

![QQ截图20230311203316](https://user-images.githubusercontent.com/108394285/224484742-5ce70081-8cb3-4277-8ade-ffcd76d1e516.png)

### 还有别的吗？

网易umu
BlueStacks都不行

**Comment by ABA2396** [comment]
[1.2-常见问题.html#可能性-1-运行库问题](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E5%8F%AF%E8%83%BD%E6%80%A7-1-%E8%BF%90%E8%A1%8C%E5%BA%93%E9%97%AE%E9%A2%98)
