### ISSUE TITLE
肉鸽刷源石锭 可以在第一层商店关闭后进入第二层再重开游戏

### ISSUE THREAD

**Issue by Spiritas5618** [MaaAssistantArknights/MaaAssistantArknights#396]
与第一层直接重开相比，多耗费几秒钟，但可以获得很多蜡烛

**Comment by chinesepyanyue** [comment]
反正是挂机，一般我就选尽可能往后打，虽然说基本上打到第二层就会G，但有时运气好甚至能打到第三层。

**Comment by zzyyyl** [comment]
为了获得蜡烛就尽可能往后打呗
刷源石锭就是为了快速刷到源石锭啊，早点退出没问题（
