### ISSUE TITLE
关闭模拟器出现问题，关闭了不相关的模拟器

### ISSUE THREAD

**Issue by charles037** [MaaAssistantArknights/MaaAssistantArknights#3960]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我是双开模拟器，一个夜神模拟器和一个蓝叠模拟器，用蓝叠模拟器运行方舟，每次运行完将模拟器关闭，但是每次关闭模拟器时会把夜神模拟器完全关闭以及蓝叠模拟器的部分进程，单独运行蓝叠就能够完全关闭蓝叠

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10949038/asst.log)

### 截图

![Snipaste_2023-03-12_01-09-37](https://user-images.githubusercontent.com/74855320/224502269-44fb5ea9-4ef7-42ee-8f53-def952edfe52.png)

### 还有别的吗？

夜神模拟器和中国蓝叠模拟器，win10，
![image](https://user-images.githubusercontent.com/74855320/224502357-a93de7b5-38fe-4877-bfba-780c07f03047.png)

**Comment by ABA2396** [comment]
很多国产模拟器都是双进程的，只关adb相关的进程会导致里面关了但模拟器外面的框还在，只能尝试用窗口名去关，这样就会有关错的问题。现在没有什么好的解决方法

**Comment by ABA2396** [comment]
蓝叠国际版是单进程的可以直接关，国内版的之前好像没找到

**Comment by WSMTBG** [comment]
> 蓝叠国际版是单进程的可以直接关，国内版的之前好像没找到

啊这...0.0我MAA把所有模拟器(蓝叠国际版)都关了

**Comment by ABA2396** [comment]
> > 蓝叠国际版是单进程的可以直接关，国内版的之前好像没找到
> 
> 啊这...0.0我MAA把所有模拟器(蓝叠国际版)都关了

对，会根据窗口名关，你可以把模拟器窗口改个名字，不带蓝叠和明日方舟的话就只会关掉连接的那个

**Comment by ABA2396** [comment]
只有蓝叠中国受伤的世界达成了（）
