### ISSUE TITLE
CE-6技能还是识别不到

### ISSUE THREAD

**Issue by yd278** [MaaAssistantArknights/MaaAssistantArknights#3962]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3931

看了log， BattleSkillReadyOnClick 和BattleSkillReadyOnClick-SquareMap的识别score都只有0.5左右

时间点在13:35:04附近

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10949690/asst.log)

### 截图

![Screenshot_2023 03 11_15 23 30 410](https://user-images.githubusercontent.com/23385935/224516172-5c7f36e6-2cb4-443e-b406-99d78d4436af.png)
这是原截图 蓝叠模拟器自己截的

**Comment by MistEO** [comment]
有这个 json 吗，或者作业站编号，发下我测测（

**Comment by yd278** [comment]
[MAACopilot_CE-6.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11185834/MAACopilot_CE-6.zip)
这是json
