### ISSUE TITLE
Can't start IS2 (roguelike mode)

### ISSUE THREAD

**Issue by skzidan** [MaaAssistantArknights/MaaAssistantArknights#3963]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

The screen stuck at this MAA cant press explore button and go to homepage then it loops going back roguelike screen but cant press explore. If I press manually MAA go to homepage then it loops and stuck at roguelike screen. 
![image](https://user-images.githubusercontent.com/37244053/224525805-e728c6f4-3002-454f-bb60-1c524ddbd9f5.png)

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10950028/asst.log)

2023-03-12 11:13

### Screenshots
MAA Debug Folder image
![2023-03-12_11-05-22-952_raw](https://user-images.githubusercontent.com/37244053/224525957-83b0071c-9a8f-480c-a7d7-de7b936820d8.png)

MAA Settings
![image](https://user-images.githubusercontent.com/37244053/224526042-60b83d0c-cf26-4fe6-aac2-e6d074cb028f.png)
![image](https://user-images.githubusercontent.com/37244053/224526049-95ca0268-c4d0-4cfe-bb33-67642cd6d2dd.png)
![image](https://user-images.githubusercontent.com/37244053/224526062-fed8c679-2c52-4c02-ae34-f2a1d8ab4f39.png)

### Anthing else?

Emulator used, operating system, 
![image](https://user-images.githubusercontent.com/37244053/224525871-de9c1b5c-858a-4e7b-a639-3cd16acf4f30.png)

**Comment by MistEO** [comment]
Is this red picture saved by MAA? It shouldn't be red, I don't know why, maybe you can try another emulator.

**Comment by skzidan** [comment]
> Is this red picture saved by MAA? It shouldn't be red, I don't know why, maybe you can try another emulator.

yes it is from Maa>debug>roguelike folder

**Comment by skzidan** [comment]
well what ever using bluestacks now , u can delete this issue
