### ISSUE TITLE
任务卡死在设置界面

### ISSUE THREAD

**Issue by MigdalBavel** [MaaAssistantArknights/MaaAssistantArknights#3965]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![QQ截图20230312152454](https://user-images.githubusercontent.com/105539375/224530563-611fcee4-7498-49a4-9906-cd253ea3166e.png)
查看的时候发现一直卡在设置菜单
4.12.0

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10950229/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10950230/asst.log)

**Comment by ABA2396** [comment]
估计是太卡了，点返回没反应点第二次的时候才刚好返回了，导致点到了主界面的设置

**Comment by MigdalBavel** [comment]
> 

这种情况能不能加个失败后回到主界面重来的处理？

**Comment by MigdalBavel** [comment]
> 估计是太卡了，点返回没反应点第二次的时候才刚好返回了，导致点到了主界面的设置

这种情况能不能加个回到主界面重来的处理？

**Comment by liuyifan-eric** [comment]
这个界面的返回键居然是白的
