### ISSUE TITLE
希望自动换班可以识别到产物不对应时自动将产物变更（仅贸易站即可）

### ISSUE THREAD

**Issue by Tec-El** [MaaAssistantArknights/MaaAssistantArknights#3972]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在搓玉的时候，由于贸易站的效率过高，一制造站对应一贸易站搓玉会导致订单堆积，因此有贸易站仅两班搓玉，剩余一班正常产龙门币的需求，制造站方面不需要变动。且制造站产物变更会导致之前的产物进度丢失，贸易站方面变更产物则不会丢失进度。

### 有什么好的想法？

仅增加贸易站的谈判策略自动选择功能即可，制造站方面的产物选择过于复杂，并且没有需求，可以不增加功能。

**Comment by Tec-El** [comment]
或者可以把贸易站原本的识别报错步骤直接改成重复确认，就是每次换班都点击改变谈判策略，这样如果策略一样的话就没影响，策略不一样就可以改成目标策略，省去了原本的识图阶段，只是多点击了三次，也不会太影响总体换班时长，制造站目前没有需求就完全不变。
不是很懂代码，感觉上是可行的。

**Comment by liuyifan-eric** [comment]
自定义排班不可以吗

**Comment by Tec-El** [comment]
> 自定义排班不可以吗？[一图流](https://yituliu.site/riicCal/)是支持不同房间不同产物的

我说的就是自定义排版了，目前排班文件是支持标记房间产物的，但实际运行的时候只是识别到产物没有对应报个错，并不会自动更换。

**Comment by Shawnsdaddy** [comment]
狗粮你造了99%去换成别的不血亏？？？换产物图个啥

**Comment by Tec-El** [comment]
> 狗粮你造了99%去换成别的不血亏？？？换产物图个啥

麻烦你去试了再来回复，前面已经说得很明白贸易站换产物是不影响当前订单的，当前提的issue也说了是针对贸易站无关制造站。

**Comment by Shawnsdaddy** [comment]
> > 狗粮你造了99%去换成别的不血亏？？？换产物图个啥
> 
> 麻烦你去试了再来回复，前面已经说得很明白贸易站换产物是不影响当前订单的，当前提的issue也说了是针对贸易站无关制造站。

说实话不太懂换产物的人的需求在哪里。
一般基建就一套表一直用，如果有新干员就更新一下就好了。

订单堆积？你切2制造？会堆积嘛？

**Comment by Tec-El** [comment]
> > > 狗粮你造了99%去换成别的不血亏？？？换产物图个啥
> > 
> > 
> > 麻烦你去试了再来回复，前面已经说得很明白贸易站换产物是不影响当前订单的，当前提的issue也说了是针对贸易站无关制造站。
> 
> 说实话不太懂换产物的人的需求在哪里。 一般基建就一套表一直用，如果有新干员就更新一下就好了。
> 
> 订单堆积？你切2制造？会堆积嘛？

有需求就是有需求，上面已经写得很清楚了，而且要实现也不复杂，你再这样重复无意义的问题我就不回复了。

**Comment by MistEO** [comment]
这个现在已经支持了（其实支持了有一阵子了
