### ISSUE TITLE
本次更新后未弹出更新内容的简介

### ISSUE THREAD

**Issue by hydra24-njus** [MaaAssistantArknights/MaaAssistantArknights#3973]
### 说说你遇到的问题？

可能是个bug。
从 4.12.0 升级到 4.12.1 时，重启进程后未弹出本次更新的信息。环境是 x86 win11.

**Comment by ABA2396** [comment]
可以之后更新的时候注意下还有没有这个问题，现在的更新日志可以在 设置-软件更新-更新日志里查看
