### ISSUE TITLE
小号刷LS-3这种关卡会报未知错误

### ISSUE THREAD

**Issue by SCP6789** [MaaAssistantArknights/MaaAssistantArknights#3976]
小号在刷LS-3这种关卡会报未知错误而且点停止会卡正在停止，是不是目前只能识别LS-6，不支持前面低等级的关卡？

**Comment by MistEO** [comment]
发个bug反馈来个日志

**Comment by ABA2396** [comment]
只支持输入 LS-6 ，在打不了 LS-6 的时候会去打 LS-5, LS-5 都代理不了的话还是用 当前/上次 吧
