### ISSUE TITLE
bot freeze in maintence screen

### ISSUE THREAD

**Issue by xczsonn** [MaaAssistantArknights/MaaAssistantArknights#3979]
![Screenshot_2023 03 13_13 40 03 627](https://user-images.githubusercontent.com/12751277/224609896-5439a89a-5795-412a-ae8d-0d47ebce25ef.png)

yes let's go
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10953621/asst.log)

**Comment by MistEO** [comment]
What else can be done in maintenance, the bot stops and gives an error, does that make sense?

**Comment by xczsonn** [comment]
@MistEO This is a notice of maintenance, not during maintenance. Maintenance is tomorrow.

**Comment by liuyifan-eric** [comment]
It looks like there is no such announcement on YostarJP until the maintenance actually starts. I don't know if it's only on KR. Does it happen every time?

**Comment by xczsonn** [comment]
> It looks like there is no such announcement on YostarJP until the maintenance actually starts. I don't know if it's only on KR. Does it happen every time?

Always give a day's notice before the maintence.
