### ISSUE TITLE
SN8 SN9 无法使用“上次作战”跳转功能

### ISSUE THREAD

**Issue by misakiycy** [MaaAssistantArknights/MaaAssistantArknights#398]
试了两个活动图，“当前作战”跳转正常，“上次作战”会跳转到作战界面，然后取消，然后就卡住了

模拟器为蓝mumu

请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8599312/asst.log)

Thanks♪(･ω･)ﾉ

**Comment by MistEO** [comment]
v3.2.1 fixed

**Comment by misakiycy** [comment]
现在在愚人号界面里面使用“上次作战”还是会卡住，都做了要不再优化一下（
