### ISSUE TITLE
MAA会额外上报每日猫饭的加成

### ISSUE THREAD

**Issue by Karonheaven** [MaaAssistantArknights/MaaAssistantArknights#3981]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如标题所述，MAA可能会识别并上报包含猫饭加成的掉落结果（每日首次）
截图和日志如下

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10954043/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10954046/gui.log)

### 截图

![PrtSc 2023-03-13 13-49-46](https://user-images.githubusercontent.com/23610722/224618444-bacb5af8-76b9-4b66-bc24-d034fabe9b76.png)

**Comment by MistEO** [comment]
v4.12.2 fixed
