### ISSUE TITLE
添加对蓝叠Pie 64bit的支持

### ISSUE THREAD

**Issue by HS7097** [MaaAssistantArknights/MaaAssistantArknights#3983]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

Alas下的MAA插件在运行时会出现卡住或者任务完成时间过长的问题
这是原issue
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2907#issue-1465196206
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2360#issue-1620739751

### 其他内容

个人感觉是Pie比默认版本要流畅，与雷电，MumuX算同一个级别的

**Comment by Black1312** [comment]
一直都支持吧？我自己用的蓝叠国际版pie和安卓11内核

**Comment by HS7097** [comment]
@Black1312 已经确定支持了吗？请参照issue检测一下，麻烦了

**Comment by MistEO** [comment]
我一直是蓝叠 pie，没啥问题。有问题请发下 log
