### ISSUE TITLE
自动战斗 无法识别塞雷娅坚城皮肤

### ISSUE THREAD

**Issue by yc080713** [MaaAssistantArknights/MaaAssistantArknights#3984]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我在使用塞雷娅“坚城”皮肤运行7-18的作业时，发现皮肤没有识别
将皮肤换成精英2后的皮肤可正常识别
我已尝试将cache\avatars下的干员头像缓存删除但无果

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10954754/asst.log)

### 还有别的吗？

MAA版本v4.12.2
蓝叠模拟器 pie 64-bit核心
模拟器1280*720 320dpi

**Comment by cenfusheng** [comment]
![image](https://user-images.githubusercontent.com/52312717/225499057-d89cc8d7-5778-4bb0-8a41-592d407869be.png)
为开发组省流，怀疑是识别范围问题，将塞雷娅识别为了122k7

**Comment by yc080713** [comment]
经群友提醒，该问题在v4.12.3版本中未出现
模拟器测试环境：1080*1920 320dpi
