### ISSUE TITLE
如何在MAA作业网上面写作业?

### ISSUE THREAD

**Issue by Arcelibs** [MaaAssistantArknights/MaaAssistantArknights#3985]
### 说说你遇到的问题？

有看过一些文档跟写作业的编辑器，但不是很清楚要怎么设定
有没有相关的图文教学或者影片参考怎么写作业

**Comment by cenfusheng** [comment]
[maa作业编辑器（新）教程.pdf](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10986117/maa.pdf)

【明日方舟MAA作业编辑器（网页）演示-哔哩哔哩】 https://b23.tv/ccRZ67s

教程与粗略的演示视频见上方。更详细的问题可以进作业编辑群问 1169188429
