### ISSUE TITLE
游戏相关可以正常试用，但是所有网络相关的操作都会报错

### ISSUE THREAD

**Issue by spriteQi** [MaaAssistantArknights/MaaAssistantArknights#3986]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

包括点击【检查更新】按钮，上传掉落数据。
关闭时也总会非正常退出，不知道是否跟此有关。
在所有版本包括最新版本上可复现。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10956837/asst.log)

### 截图

![ota](https://user-images.githubusercontent.com/127581076/224690940-a2a73a85-386c-41b0-9928-3e6005b311f0.jpg)
![exit](https://user-images.githubusercontent.com/127581076/224690945-fb48b20f-69fe-47eb-a730-475403348727.jpg)
![upload](https://user-images.githubusercontent.com/127581076/224690952-7517c21f-7332-4a65-8ed3-00e7194d490b.jpg)

### 还有别的吗？

运行环境：64位win7，蓝叠模拟器国际版,已安装.net4.8及C++库。

**Comment by ABA2396** [comment]
win7没有curl，装一个试试？

**Comment by MistEO** [comment]
> win7没有curl，装一个试试？

现在不依赖 curl 了
