### ISSUE TITLE
肉鸽问题

### ISSUE THREAD

**Issue by quiqabc** [MaaAssistantArknights/MaaAssistantArknights#3987]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽这里会一直放着
求解决

### 日志文件

无

### 截图

![Snipaste_2023-03-13_21-41-38](https://user-images.githubusercontent.com/82311098/224719322-99d95188-2d50-4016-a7ae-4ff660683b65.png)

### 还有别的吗？

1

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/224722661-0cad2d8f-f8c0-491d-a553-8e63d8a74862.png)
