### ISSUE TITLE
mumu模拟器 SN8 掉落物品识别错误

### ISSUE THREAD

**Issue by misakiycy** [MaaAssistantArknights/MaaAssistantArknights#399]
mumu模拟器 SN8掉落了铁块但识别为无掉落

请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8599345/asst.log)

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ

**Comment by MistEO** [comment]
v3.2.1 刚修复了，更新一下~
