### ISSUE TITLE
建议新增“定时检测更新”功能

### ISSUE THREAD

**Issue by AnnAngela** [MaaAssistantArknights/MaaAssistantArknights#3991]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我有台电脑7×24小时开机挂模拟器和 MAA，配置 MAA 定时执行收基建，这样我就不用去管基建。但是有个问题，像是遇到游戏版本更新后，MAA 通常也会更新，但开着 MAA 就不会自动检测更新，导致我需要时不时去手动在设置中检测更新，比较麻烦。

### 有什么好的想法？

希望能引入定时检测更新功能，且发现更新后可以弹出一个不消失的弹窗，这样我下次回到电脑前就能看到有更新了。

**Comment by ABA2396** [comment]
这个功能倒是容易做，但现在在搞 #3934 ，等这个整完了之后再加吧
