### ISSUE TITLE
希望能够统计肉鸽战斗结束后在主界面显示掉落数

### ISSUE THREAD

**Issue by Ghost-Sun** [MaaAssistantArknights/MaaAssistantArknights#3994]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

统计肉鸽战斗结束后在主界面显示掉落

**Comment by status102** [comment]
- #7276
