### ISSUE TITLE
Maa在部分情况下未正常初始化minitouch造成无法正常点击

### ISSUE THREAD

**Issue by yyjdelete** [MaaAssistantArknights/MaaAssistantArknights#3995]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

测试版本: Maa v4.12.2, mumu 2.7.19 x64

mumu模拟器在设置为720*1280, 240dpi的分辨率时, 冷启动(由maa启动模拟器和方舟), 如果设置为minitouch或maatouch模式, 会卡死在唤醒这步的登录界面, 一直去点击中上方区域(图中开了开发者选项的点击小圆点显示)

测试了停止并重新启动maa的任务, 重启adb, 重启模拟器均无效, 只能通过重新启动maa来恢复, 因此应该不是模拟器的bug.
测试切换到adb模式或者修改分辨率为1280*720也能解决下面的问题1

(设置这个分辨率(竖屏)是因为模拟器上装的另外一个游戏的适配问题, 没啥特殊原因)

#### 观察日志的时候怀疑存在以下两个问题:
1. 怀疑是Maa把读取模拟器分辨率的任务放在了唤醒(启动方舟)之前, 因此造成了模拟器分辨率(横竖屏状态)读取出错;
2. 重启模拟器后, 开始Maa任务时, Maa不会去重新读取分辨率和初始化minitouch;
> 2的具体操作步骤是: 1. 正常停止MAA的任务; 2. 退出模拟器; 3. 自己启动模拟器; 4. 等待模拟器启动完成; 5. 启动MAA的任务;

### 日志文件

[asst.log.gz](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10967607/asst.log.gz)
19:03:06唤醒卡死后手动停止了任务
19:03:38的时候模拟器重启完成, 然后启动了Maa的任务, 在日志中可观察到重复的报错`Failed to write to minitouch, err 232`, 且Maa由于未知原因没有去启动minitouch(进程列表和日志中都没有)

### 截图

![MuMu20230314140037](https://user-images.githubusercontent.com/1819074/224983252-a036c8d3-da55-49c3-a804-3fde513f69f0.png)
重复点击位置位于中上方小圆点区域(小圆点是开发者选项里的点击显示)

**Comment by MistEO** [comment]
> 怀疑是Maa把读取模拟器分辨率的任务放在了唤醒(启动方舟)之前, 因此造成了模拟器分辨率(横竖屏状态)读取出错;

应该是这个原因，试试直接把模拟器设置为 1280 * 720 吧（而不是反过来的

**Comment by yyjdelete** [comment]
> > 怀疑是Maa把读取模拟器分辨率的任务放在了唤醒(启动方舟)之前, 因此造成了模拟器分辨率(横竖屏状态)读取出错;
> 
> 应该是这个原因，试试直接把模拟器设置为 1280 * 720 吧（而不是反过来的

分辨率改了之后是问题1正常的, 只是问题2是独立的, 仍然存在(重启了模拟器之后无法点击, maa也没提示信息, 就一直卡在那)
