### ISSUE TITLE
自动战斗识别问题 见行者会识别成艾雅法拉

### ISSUE THREAD

**Issue by Jack4936** [MaaAssistantArknights/MaaAssistantArknights#3998]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

见行者与艾雅法拉同时在编队里, 会识别成艾雅法拉进行操作

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10972083/asst.log)
倒数第二次部署艾雅法拉时选择了见行者

**Comment by cenfusheng** [comment]
这是由于某次战斗携带人数过多引起的偶发bug，暂无修复计划。
作为临时的解决方案，可以在maa主文件夹\cache\avatars中删除错误的.png
