### ISSUE TITLE
日服基建找不到承曦格雷伊

### ISSUE THREAD

**Issue by akari3089** [MaaAssistantArknights/MaaAssistantArknights#3999]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

日服更新后排班找不到承曦格雷伊跟杜林

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10970714/asst.zip)

### 截图

![image](https://user-images.githubusercontent.com/43425391/225061585-68603a35-174d-46e9-8bb3-9c81aff723b1.png)
![image](https://user-images.githubusercontent.com/43425391/225061632-1716e78f-711f-4b0a-807b-16b31e8fb9c3.png)

### 还有别的吗？

蓝叠国际版
win10
最新内测版，在更新前也出现过相同问题

**Comment by cenfusheng** [comment]
承曦格雷伊已修复，预计下个版本可用。杜林日志未见文字识别异常，等大佬修复。
