### ISSUE TITLE
建议贸易站龙门币使用无人机加速时优先选择但书值班设施

### ISSUE THREAD

**Issue by uzhao** [MaaAssistantArknights/MaaAssistantArknights#4000]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by cenfusheng** [comment]
建议使用自定义基建达成此项需求，参考 https://www.bilibili.com/video/av261149407/
