### ISSUE TITLE
4.12.3在刷理智时吃源石选项无法勾选

### ISSUE THREAD

**Issue by LinYu1174** [MaaAssistantArknights/MaaAssistantArknights#4002]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

吃源石选项无法勾选，重启依旧无法解决

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10975735/asst.log)
在3月15号11.20分首次发现

**Comment by ABA2396** [comment]
理智药数量设置为0时不能勾选
