### ISSUE TITLE
MAA连续跨关卡完成“自动战斗”功能

### ISSUE THREAD

**Issue by Heart-of-engine** [MaaAssistantArknights/MaaAssistantArknights#4003]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前未遇到问题

### 有什么好的想法？

作者您好，我自去年11月了解到MAA后，一直在进行使用，但每次遇到新活动时，每一关都要选择一份作业并粘贴一份“神秘代码”，这样导致**只要有新活动，每一关都要看完整个作战流程，才能到下一关卡自动作战**，所以想请您添加一个“连续跨关卡自动作战”的功能，用户通过**选定不同的神秘代码并指定其顺序后，依次对每份作战记录进行自动战斗**

### 其他内容

无

**Comment by ChildeRolando** [comment]
这样要对每个EX关做导航，按我的理解这个功能是不会做的

**Comment by Heart-of-engine** [comment]
> 这样要对每个EX关做导航，按我的理解这个功能是不会做的

好的，那也感谢您的耐心答复，谢谢！
