### ISSUE TITLE
[基建] 礫 識別bug

### ISSUE THREAD

**Issue by yuanlk** [MaaAssistantArknights/MaaAssistantArknights#4004]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

宿舍裡找到幹員礫了可是MAA不會點確認。
![image](https://user-images.githubusercontent.com/79469484/225219042-8d7b3aa5-5b63-4879-898f-c91b03d5e9b0.png)
日誌裡礫 會變成 礫樂，導致 [存在自定义干员未选中]
![image](https://user-images.githubusercontent.com/79469484/225218999-b2958cd9-5b58-47a6-8d59-588672a4b1a7.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10976467/asst.log)

2023-03-15 13:43:09.452 - 2023-03-15 13:43:14.069

**Comment by cenfusheng** [comment]
已修复，预计下个版本可正常使用。
