### ISSUE TITLE
support for ultrawide

### ISSUE THREAD

**Issue by Artcul** [MaaAssistantArknights/MaaAssistantArknights#4005]
### Before raising the issue...

- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I'm probably sure this is a new feature/suggestion and not a bug encountered (please attach logs if you're not sure)

### The problems you have encountered?

I'm using the app player in ultra-wide, not landscape mode, but it's inconvenient to use it in landscape mode because it doesn't support the ultra-wide feature. I would appreciate it if it could be improved.

### Any good ideas?

This is all great, but I wish there was also support for ultrawide.

**Comment by cenfusheng** [comment]
考虑到maa与alas在运行上的相似，你也可以参考这份教程：
Considering that maa and alas are similar in operation, you can also refer to this tutorial:
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Emulator_cn
