### ISSUE TITLE
No one in the power station (YostarKR)

### ISSUE THREAD

**Issue by xczsonn** [MaaAssistantArknights/MaaAssistantArknights#4007]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

한국어 클라이언트에서, 업데이트 후 기반시설의 '발전소'에서 오퍼레이터를 배치하지 않습니다. Grey의 alternate 캐릭터가 업데이트 돼서 그런 것 같습니다.

The Korean client does not deploy operators at the 'power plant' of the infrastructure after the update. I think it's because Grey's alternate character has been updated.

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10981731/asst.log)

### Screenshots

![image](https://user-images.githubusercontent.com/12751277/225358889-f48e4214-ee8e-4d83-8adb-a8a1d4a9d48e.png)

### Anthing else?

yes let's go

**Comment by xczsonn** [comment]
In Korean servers, grey and alternate grey cannot be placed in power plants at the same time, so they crash.

**Comment by xczsonn** [comment]
In addition to Grey, all alternate operators collide.

**Comment by xczsonn** [comment]
maa does not recognize the first refinement of the bubble. (Including both automatic and manual)

**Comment by 178619** [comment]
Alternate operators now can be placed at the same time
