### ISSUE TITLE
能不能将完成后关闭模拟器更改为根据adb端口号关闭

### ISSUE THREAD

**Issue by lastxxx2** [MaaAssistantArknights/MaaAssistantArknights#4008]
### 在提问之前...

- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用maa的完成后关闭模拟器功能时，如果该模拟器有多开的进程在运行，maa是随便关闭一个模拟器进程，挺影响体验的，比如我想同时挂方舟和碧蓝，maa方舟刷完了自动把碧蓝关了

**Comment by cenfusheng** [comment]
与 #3960 相似，可以参照那边的回答。对标题的回答：从程序角度，不能。
