### ISSUE TITLE
繁中服无法启动LS-6刷经验

### ISSUE THREAD

**Issue by oracle91** [MaaAssistantArknights/MaaAssistantArknights#4010]
**在提问之前...**
 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

**问题描述**
点击link start后显示已连接，但是会自动停止，不会进入fight步骤。

**日志文件**
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10988029/asst.log)

**Comment by oracle91** [comment]
繁中服关卡选择选的是LS-6

**Comment by ABA2396** [comment]
tag写错了，等下改改
