### ISSUE TITLE
肉鸽模拟完全卡死

### ISSUE THREAD

**Issue by wenjj4** [MaaAssistantArknights/MaaAssistantArknights#4012]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用过mumuX，蓝叠，雷电，夜神，全部都会在肉鸽卡死，电脑都卡死的那种

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10990610/asst.log)
3月16 20:12:47

### 还有别的吗？

win11  笔记本1050ti

**Comment by cenfusheng** [comment]
请提供电脑运存，不建议8G及以下电脑同时运行模拟器与MAA，不建议16G及以下用户同时运行其它大型软件。
