### ISSUE TITLE
maa自动战斗、自动编队会漏点干员分支的图标，导致一直寻找某个干员

### ISSUE THREAD

**Issue by UNscientific-9** [MaaAssistantArknights/MaaAssistantArknights#4013]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选择作业进行自动战斗时，会在自动编队的时候，会漏过点击干员职业分支，导致一直识别某个干员

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10991521/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/128057826/225638903-188b471a-0d83-480c-b09e-59b3d2aab1c2.png)

### 还有别的吗？

模拟器：夜神模拟器7.0.5.2
系统：Windows10 22h2 19045.2728

**Comment by LDYang694** [comment]
同样的，我也卡在了保全一直重复选人的界面
