### ISSUE TITLE
考虑利用硬件资源为opencv 加速

### ISSUE THREAD

**Issue by TeemoKill** [MaaAssistantArknights/MaaAssistantArknights#4016]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

MAA 在活跃执行图像识别任务时cpu 占用率高，在多开时cpu 资源消耗尤为明显，但似乎没有使用可用的gpu 设备。
建议opencv 优先利用gpu 或核显（自动检测或手动配置使用gpu）

### 有什么好的想法？

如上，建议opencv 优先利用gpu 或核显（自动检测或手动配置使用gpu）

**Comment by horror-proton** [comment]
其实 MAA 开销最大的在 onnxruntime (主要是 OCR 用到), 而不是 opencv

**Comment by MistEO** [comment]
GPU == 快 != 不吃 CPU != 不吃内存

相反使用 GPU 版本可能要额外多吃 3G 左右的内存，另外还需要下载 cuda 包，实际也并不能快多少（因为大部分时间消耗在了截图 IO 上），所以是不合算的

**Comment by MistEO** [comment]
需要的话直接将 MAA 目录下的 onnxruntime.dll 替换为 gpu 版本的 onnxruntime 即可，可以去 [官方 repo](https://github.com/microsoft/onnxruntime/releases) 下载
