### ISSUE TITLE
求添加一个肉鸽刷指路鳞的功能,非常简单就在刷钱的基础上点击一下刷新然后购买就行

### ISSUE THREAD

**Issue by rei2211** [MaaAssistantArknights/MaaAssistantArknights#4019]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

指路鳞太难刷了

### 有什么好的想法？

指路鳞太难刷了

### 其他内容

指路鳞太难刷了

**Comment by cenfusheng** [comment]
maa没有此项计划，可以考虑寻找其它已实现的脚本。例如 BV1ZM41187Cq （本次推荐仅个人行为，任何问题请在他们的群里提问）
