### ISSUE TITLE
正常运行刷理智时，MAA提示[掉落识别错误]&[游戏崩溃，重新启动]

### ISSUE THREAD

**Issue by 610807421** [MaaAssistantArknights/MaaAssistantArknights#4022]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

关卡选择“CF-8”，仅选择“刷理智”功能，同时仅勾选“吃理智药5次”。
前面正常运行，正常运行至吃第三次药后，提示”已开始行动12次“。然后提示”掉落识别错误“，”游戏崩溃，重新启动”，“任务出错：Fight”，“任务已全部完成！”。从正常开始代理，到MAA停止任务，过程中，模拟器始终在正常代理CF-8。当我注意到提示时，一局代理尚未结束。

根据debug文件夹内的截图，刚好截到了开始作战时确认阵容的画面……然后ocr就飞了。

### 日志文件

日志文件 [asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11005376/asst.zip)

### 截图

图片来自/debug/drops 文件夹 2023-03-18_03-18-27-069_raw.png
![2023-03-18_03-18-27-069_raw](https://user-images.githubusercontent.com/49870924/226013309-9b869cf0-627e-41f3-b160-879b10433812.png)
MAA界面
![QQ截图20230318034320](https://user-images.githubusercontent.com/49870924/226014437-dde515e0-f40e-4e2e-b9f3-fec276622b78.png)

**Comment by deepin-pointer** [comment]
这个问题非常严重，一开始还能刷几把，后来不管是当前/上次还是CF-8刷这一关，基本每把都崩溃，看debug里图片很少，基本都是截到了开始作战前或者结束作战后的黑屏

**Comment by deepin-pointer** [comment]
@MistEO 经过反复测试，回滚至v4.12.0可以正常运行，在此版本会出现“截图失败，如反复出现请尝试重启或更换模拟器！”的错误，但是会重新尝试截图并成功识别掉落。自v4.12.1之后的版本不再出现上述提示，而是变成频繁随机出现”掉落识别错误“错误，掉落识别为空，”游戏崩溃，重新启动“警告等，刷理智任务大概率会提前结束，导致完全无法挂机只能手刷。

测试环境：夜神模拟器7.0.5.5
（模拟器黑屏时间会比手机长很多）

**Comment by DrunkenPCat** [comment]
我也会出现这样的问题。因为机器性能的原因，打完之后黑屏时间太长，会直接提示“游戏崩溃，重新启动”，之后刷理智就会停止。这样的问题已经持续了起码三四个版本了。我觉得可以在设置里加一个选项，调整黑屏多久判定崩溃。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11217291/asst.log)
