### ISSUE TITLE
关于增加指定资源刷取个数

### ISSUE THREAD

**Issue by BigSaltyMan** [MaaAssistantArknights/MaaAssistantArknights#4023]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在maa好像只能指定刷关次数，刷芯片本的时候总有些麻烦，有没有兴趣加个指定资源刷取个数的功能呢？

**Comment by ABA2396** [comment]
![Uploading image.png…]()
