### ISSUE TITLE
mac再次出现ConnectFailed Uuid command failed to exec的问题

### ISSUE THREAD

**Issue by llsx05** [MaaAssistantArknights/MaaAssistantArknights#4025]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天突然出现无法连接的问题，尝试过之前issue里的办法，没能解决。config.json中Compatible的uuid已经设置成echo 111111了。又尝试了重启、重装maa和mumu，还是无法连接。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11008315/asst.log)

### 截图

<img width="895" alt="Screenshot 2023-03-18 at 12 05 54 PM" src="https://user-images.githubusercontent.com/75969848/226101576-8f3522d9-2928-442e-b4d1-571ff47719ad.png">

### 还有别的吗？

模拟器：mumu模拟器
操作系统：macos Ventura
设备：macbook pro 13-inch 2019

**Comment by llsx05** [comment]
现在突然好了，也不知道是什么原因。

**Comment by wxhwen** [comment]
我也遇到了这个问题。
mac 版本：12.6.3
MAA版本：v4.13.0
MuMu版本：1.9.58

*主要是其他模拟器连游戏都打不开。感觉推荐的mac下的模拟器不太靠谱：
1）蓝叠：没有mac版本
2）蓝叠国际版本：打开报错
3）夜神：报错

现在活动只能用mumu录制先，有没有其他在mac下成功用上的朋友？

**Comment by alonewhitex** [comment]
> 我也遇到了这个问题。 mac 版本：12.6.3 MAA版本：v4.13.0 MuMu版本：1.9.58
> 
> *主要是其他模拟器连游戏都打不开。感觉推荐的mac下的模拟器不太靠谱： 1）蓝叠：没有mac版本 2）蓝叠国际版本：打开报错 3）夜神：报错
> 
> 现在活动只能用mumu录制先，有没有其他在mac下成功用上的朋友？

如果你有安卓手机的话，可以试一下用[scrcpy](https://github.com/Genymobile/scrcpy)连接，然后adb devices就可以查看到adb地址了，具体可以参照[手机、平板等实体安卓设备](https://maa.plus/docs/1.3-模拟器支持.html#⚙%EF%B8%8F-手机、平板等实体安卓设备)，使用scrcpy库的话Mac也可以实现。
