### ISSUE TITLE
可以设置不使用但书吗，赤金消耗有点快

### ISSUE THREAD

**Issue by xyxyx718** [MaaAssistantArknights/MaaAssistantArknights#4026]
### 说说你遇到的问题？

比如直接手动把  .\resource\infrast.json 里面但书的技能删掉可行吗？

**Comment by ABA2396** [comment]
可以，但是更新之后可能会被覆盖，如果用的是自动的话为什么不把无人机用在赤金的加速呢

**Comment by ABA2396** [comment]
那干脆找到但书技能的图标然后用画图把它涂掉反而来的更好，因为更新不会覆盖）
