### ISSUE TITLE
登录小号送线索的需求建议

### ISSUE THREAD

**Issue by BiologyHazard** [MaaAssistantArknights/MaaAssistantArknights#4027]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

本人B服，有很多小号来给大号送线索，保证每天开趴
但是切账号登录送线索好麻烦呀

### 有什么好的想法？

要是MAA能完成这个操作真的太棒啦！

**Comment by ntgmc** [comment]
Duplicate of #1870
