### ISSUE TITLE
自定义基建排班格式错误

### ISSUE THREAD

**Issue by JadeLiang17** [MaaAssistantArknights/MaaAssistantArknights#4028]
### 说说你遇到的问题？

这里编程门外汉，想写一个5班次的自定义基建排班，（是在原有三班长短班的基础上额外加入两班的肥鸭换心情的思路），但是基建一图流并不支持三班以上的排班。
所以目前想法是先用一图流写出三班（原有的长短班）和两班（中间插入两次肥鸭换心情）两个文件，然后再打开json文件，通过复制粘贴的方式插入两段班次的代码，然后操作完之后导入牛牛无法解析了x_x 。
可能听起来有点蠢但这确实是我想到的比较简单的办法了，当然也有看过“常见问题”里的基建排班协议模板，但想要彻底看明白还是太吃力，还需要删注译更没有把握照着写出来。
因为这里不能发json文件，所以以度盘的形式把文件发出来，如果有大佬愿意抽空看一下给一些指点意见就再好不过了
链接：https://pan.baidu.com/s/1Dg6njAbma4Mg8iWLiVSz0A?pwd=alnq 
提取码：alnq

**Comment by ABA2396** [comment]
498行后面少了一个英文逗号
```
			},
			"name":"15时30肥鸭换龙舌兰",
			"description":"描述2"
		},
		{
			"rooms":{
				"trading":[
					{
```

**Comment by JadeLiang17** [comment]
> 498行后面少了一个英文逗号
> 
> ```
> 			},
> 			"name":"15时30肥鸭换龙舌兰",
> 			"description":"描述2"
> 		},
> 		{
> 			"rooms":{
> 				"trading":[
> 					{
> ```

成功了，大佬感激不尽
