### ISSUE TITLE
愚人号活动不点代理直接进

### ISSUE THREAD

**Issue by cglcv** [MaaAssistantArknights/MaaAssistantArknights#403]
3.2.1版本，刚更新
如题，可能是UI大改导致没识别出来
下附log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8601033/asst.log)

**Comment by zzyyyl** [comment]
@MistEO 日志里显示代理指挥的`score=0.58`。给`UsePrts-StageSN`加个`"templThreshold": 0.5`应该能解决问题

**Comment by MistEO** [comment]
> @MistEO 日志里显示代理指挥的`score=0.58`。给`UsePrts-StageSN`加个`"templThreshold": 0.5`应该能解决问题

感觉不能这么干，0.5 太低了，会匹配上些别的错误的东西_(:з」∠)_

话说这个分怎么这么低，我这里试都是 0.99+，得想想怎么整

**Comment by zzyyyl** [comment]
（我这里分数都是0.80上下，有时候就寄了）

**Comment by zzyyyl** [comment]
可能是背景的特效引起的？加点mask？

**Comment by MistEO** [comment]
> 可能是背景的特效引起的？加点mask？

已经是带了 mask 的了，这个线条太细了，可能和 cv::resize 的压缩方式有关系，但要是改的话影响有点大了

**Comment by zzyyyl** [comment]
那不如用个黑块匹配，匹配上再来个OCR，OCR也匹配上了再点（

**Comment by zzyyyl** [comment]
> 那不如用个黑块匹配，匹配上再来个OCR，OCR也匹配上了再点（

欸这样是不是也能适配普通关卡？快整一个

**Comment by MistEO** [comment]
直接一个 mask 的删！

**Comment by MistEO** [comment]
v3.3 fixed
