### ISSUE TITLE
使用MAA尝试连接WSA时无法手动设置使用正确的端口连接

### ISSUE THREAD

**Issue by NyankoSong** [MaaAssistantArknights/MaaAssistantArknights#4033]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

你好！
按照操作指引设置为通用模式后，尝试按照WSA中给出的adb端口进行设置，但不论如何都会在开始连接后自动变成另一个毫不相干的端口（8512），即便是我在列表里把这个“8512”删掉，也会自己再改回这个错误的端口，无法让其用正确的端口连接。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11010255/asst.log)

### 还有别的吗？

Windows版本：Windows 11 专业版 22621.674
WSA版本：2301.40000.7.1

**Comment by ABA2396** [comment]
是开了自动检测吗？关掉之后应该不会变。

**Comment by NyankoSong** [comment]
> 是开了自动检测吗？关掉之后应该不会变。

感谢回复！

如果是说连接设置中的“自动检测连接“的话，选中之后下面的输入框就禁止输入了，我肯定是没有打开这个的。

**Comment by MistEO** [comment]
自动改端口的逻辑，除了 “自动检测”，就只剩蓝叠的 HyperV config 了，是不是之前配置过

**Comment by NyankoSong** [comment]
> 自动改端口的逻辑，除了 “自动检测”，就只剩蓝叠的 HyperV config 了，是不是之前配置过

感谢回复！

我重装系统之前确实用过蓝叠Hyper-V版本，现在的系统上没有安装任何模拟器，所以我也就继续用之前的了。

我现在删掉配置重新下载，确实没有再自动改端口了，算是解决了。

虽然还是未知错误连不上= =。实在不行还是不倒腾了，用回蓝叠罢。
