### ISSUE TITLE
只有基建换班提示未知错误，其余功能均没问题

### ISSUE THREAD

**Issue by innoseeker** [MaaAssistantArknights/MaaAssistantArknights#4034]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11010304/asst.log)
下面截图有时间

### 截图

![image](https://user-images.githubusercontent.com/128277030/226156115-a70ed84e-008a-40ae-b8a7-0ae1f3d0d19c.png)

**Comment by ABA2396** [comment]
#3717

**Comment by innoseeker** [comment]
> #3717

thanks!
