### ISSUE TITLE
宿舍无法自动放入干员

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#4035]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

该问题已经多次出现。

软件设置和发生时间可见于截图1和截图2。该设置是最后一次尝试的设置，第一次尝试是全选，该bug同样存在。截图3可知宿舍1,2,3 并未被放满无心情干员。截图4可知大量干员心情未满。

这里运行3次，4个宿舍仅访问前2个，且仅第一个宿舍真正放入干员。第二个宿舍尝试放入两次，选好干员但未点确定，可能是点的返回，导致未放入干员。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11010378/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/74366156/226157456-5b2e562e-3f5f-485a-ab38-a0a0a739a6db.png)
![image](https://user-images.githubusercontent.com/74366156/226157460-7d53866b-b4e7-4b6b-828a-b9ab04135e0c.png)
![MuMu20230319172354](https://user-images.githubusercontent.com/74366156/226157485-54ad0318-c45b-4199-999d-e23a7a15087c.png)
![MuMu20230319172609](https://user-images.githubusercontent.com/74366156/226158118-7feb6708-a06c-46d6-a1e0-67d9a489ffa5.png)

### 还有别的吗？

本人目前位于海外。模拟器mumu，电脑系统win11。

**Comment by mysir-lin** [comment]
遇到相同问题 maa在宿舍选取之后 没有确认放入

**Comment by mysir-lin** [comment]
版本号4.12.3 之前未见相同问题

**Comment by Cowjiang** [comment]
遇到同样问题，4.12.3前一切正常，4.12.3多开MAA，100%触发，一直重复Dorm0或者直接就只处理Dorm0一次结束
![image](https://user-images.githubusercontent.com/57822554/226325870-6c41f3b1-9d82-4c4a-a0ac-107664fa9e08.png)
