### ISSUE TITLE
定时执行自动重置

### ISSUE THREAD

**Issue by dylanhz** [MaaAssistantArknights/MaaAssistantArknights#4037]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最新的两个内测版本更新后，都出现了定时执行时间被重置的问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11011559/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/53137516/226187977-4e13e3df-f253-4673-88c1-c7a5c597dc2c.png)

**Comment by ABA2396** [comment]
a7d0d6b81a1766950efe4b5ab480eb13bfae669a fixed

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/4461510180
等这个出来应该就行了
