### ISSUE TITLE
建议增加基建宿舍不让医疗小车回复心情

### ISSUE THREAD

**Issue by RaMoozy** [MaaAssistantArknights/MaaAssistantArknights#4041]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

森蚺体系最高效率是配合发电站0心情Lancet-2和承曦格雷伊。
若使用森蚺体系最高效率的排班，使用MAA自动填满宿舍的话，一定会让Lancet恢复心情。
目前只能用手动选择宿舍进驻人员，以达到Lancet-2 保持0心情的结果。

### 有什么好的想法？

建议增加宿舍Lancet-2不进驻的选项。

**Comment by ABA2396** [comment]
既然是自定义基建的话，宿舍自己写满就好了）

**Comment by cenfusheng** [comment]
既然是自定义基建的话，关掉宿舍自动填充，自己写要恢复心情的人。MAA目前没有基建黑名单计划。
