### ISSUE TITLE
繁中服適配 task 編輯問題

### ISSUE THREAD

**Issue by B-2U** [MaaAssistantArknights/MaaAssistantArknights#4046]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

為了解決maa無法處理繁中服特有的登入畫面
我試著在startupThemes中插入task, 把如下json放入了繁中服的task.json中
```json
"StartUpThemes": {
        "algorithm": "JustReturn",
        "next": [
            "GameStart",
            "TwxyLogin",
            "StartToWakeUp",
            "StartLoginBServer",
            "StartUpConnectingFlag",
            "#back",
            "CloseAnnos#next",
            "TodaysSupplies",
            "OfflineConfirm"
        ]
    },
    "TwxyLogin": {
        "action": "ClickSelf",
        "roi": [360, 220, 550, 200],
        "next": [
            "StartUpThemes#next",
            "TwxyLogin@LoadingIcon"
        ]
    }
```
但經過不斷嘗試還是卡在了這個登入介面, log中也沒有找到關鍵資訊

因此想請問正確的編輯方式應該如何操作
兩張附件截圖是應對的畫面跟template

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11020350/asst.log)

### 截图

![TwxyLogin](https://user-images.githubusercontent.com/82710122/226399045-35fff592-72cc-413c-b46a-e8e7fd342bff.png)
![Screenshot_2023 03 20_21 52 58 627](https://user-images.githubusercontent.com/82710122/226399081-90820a8a-61f8-4066-9fd1-86863d467f01.png)

**Comment by vonnoq** [comment]
我是直接拿StartLoginBServer來用

**Comment by vonnoq** [comment]
> > 我是直接拿StartLoginBServer來用
> 
> 我試著模仿了你在 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/3175/commits 的更動 但還是失敗了 log的情形看起來跟我的嘗試一樣

我剛試過是沒問題的
重抓task再試試？

**Comment by ABA2396** [comment]
图片大小看着不对，你这个图是怎么截出来的？
在 [MaaAssistantArknights](https://github.com/MaaAssistantArknights/MaaAssistantArknights)/[tools](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/dev/tools)/CropRoi/ 文件夹下有截图工具，用那个

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/226431749-3b40a4dc-7e8d-4c45-b681-29186b79daf3.png)

**Comment by ABA2396** [comment]
[2.5-外服適配教程](https://maa.plus/docs/zh-tw/2.5-%E5%A4%96%E6%9C%8D%E9%81%A9%E9%85%8D%E6%95%99%E7%A8%8B.html)

**Comment by B-2U** [comment]
> 图片大小看着不对，你这个图是怎么截出来的？ 在 [MaaAssistantArknights](https://github.com/MaaAssistantArknights/MaaAssistantArknights)/[tools](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/dev/tools)/CropRoi/ 文件夹下有截图工具，用那个

用附帶的截取工具後可以正常運作了，先前我自作聰明自己裁減再等比縮放到720p
好奇這兩種的差異是?

**Comment by ABA2396** [comment]
> > 图片大小看着不对，你这个图是怎么截出来的？ 在 [MaaAssistantArknights](https://github.com/MaaAssistantArknights/MaaAssistantArknights)/[tools](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/dev/tools)/CropRoi/ 文件夹下有截图工具，用那个
> 
> 用附帶的截取工具後可以正常運作了，先前我自作聰明自己裁減再等比縮放到720p
> 好奇這兩種的差異是?

如果是720p直接用画图裁剪也是可以的，自己缩放的话又麻烦又容易错。估计就是缩放的比例不对吧

**Comment by B-2U** [comment]
了解 謝謝兩位幫助！
