### ISSUE TITLE
希望能增加对 兆懿模拟器 的支持

### ISSUE THREAD

**Issue by Afurete233** [MaaAssistantArknights/MaaAssistantArknights#4047]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

最近发现了一个可以在win10下就能运行的安卓子系统，希望能对这个模拟进行支持。
模拟器官网：https://www.wndroid.com/index/

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/227526847-bd3f8477-c927-47d0-8df8-f3666e4c5ff5.png)
只要是支持adb，能用adb截图并导出的模拟器一般都能支持吧

**Comment by Afurete233** [comment]
> ![图像](https://user-images.githubusercontent.com/99072975/227526847-bd3f8477-c927-47d0-8df8-f3666e4c5ff5.png)只要是支持adb，能用adb截图并导出的模拟器一般都能支持吧

这东西其实算是跟wsa差不多的安卓子系统，它是支持adb的，但是我在MAA里怎么都连接不上他，用adb工具去连接却是可以连接的

**Comment by Afurete233** [comment]
我研究了一下，发现使用adb input模式就可以进行连接了

**Comment by Afurete233** [comment]
我研究了一下发现用adb input模式就可以进行连接了，不过和wsa一样需要全屏使用
