### ISSUE TITLE
希望剩余理智选项,跟随今日开放关卡变化

### ISSUE THREAD

**Issue by IZUMI-Zu** [MaaAssistantArknights/MaaAssistantArknights#4048]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

剩余理智选项不会跟随今日开放关卡变化

### 有什么好的想法？

使剩余理智选项,跟随今日开放关卡变化

### 其他内容

![image](https://user-images.githubusercontent.com/23271676/226502088-8ddd6511-1c92-4832-9c15-b03c9460f20f.png)

**Comment by ABA2396** [comment]
设置 - 战斗设置 - 使用备选关卡
