### ISSUE TITLE
雷电模拟器更新了一个雷电模拟器9的版本，希望更新一下支持

### ISSUE THREAD

**Issue by JaqenS** [MaaAssistantArknights/MaaAssistantArknights#4049]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by ABA2396** [comment]
![IMG_20230321_130356.jpg](https://user-images.githubusercontent.com/99072975/226523096-62abc370-2730-497a-8fd9-1fe63f584e36.jpg)
