### ISSUE TITLE
希望增加掉线重连。

### ISSUE THREAD

**Issue by Moon1995cn** [MaaAssistantArknights/MaaAssistantArknights#405]
代理掉线后返回主界面无作为，希望增加检测到掉线了/返回到唤醒（登录）环节自动重新唤醒。

**Comment by Moon1995cn** [comment]
![image](https://user-images.githubusercontent.com/97240574/166204847-1f588180-f0b0-4b39-ba45-d81a968164c6.png)
59掉线之后就卡住了。

**Comment by zzyyyl** [comment]
之前应该修过，用的是最新版本吗？官服/B服？

**Comment by Moon1995cn** [comment]
官服

**Comment by zzyyyl** [comment]
发个日志看看？

**Comment by Moon1995cn** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8601871/asst.log)

**Comment by Moon1995cn** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8602062/asst.log)
第二次中断

**Comment by Moon1995cn** [comment]
![image](https://user-images.githubusercontent.com/97240574/166219134-3cedde94-dc2a-4f3b-b524-220bcd47079b.png)
3断
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8602207/asst.log)

**Comment by zzyyyl** [comment]
看日志是卡在`StartUpConnectingFlag`
![这个地方](https://raw.githubusercontent.com/MaaAssistantArknights/MaaAssistantArknights/master/resource/template/StartUpConnectingFlag.png)
这个界面按理来说是会自动登录的吧？
我没怎么掉线过，不知道卡在这个地方应该要怎么登录（
可以的话传个卡住的界面看看？

**Comment by Moon1995cn** [comment]
我看到是卡在开始唤醒按钮那一步
![image](https://user-images.githubusercontent.com/97240574/166230374-cf7a1946-868a-481e-9d44-8d14e95afe26.png)

**Comment by Moon1995cn** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8602634/asst.log)

**Comment by zzyyyl** [comment]
可以看看[这个临时版本](https://github.com/zzyyyl/MaaAssistantArknights/actions/runs/2258000973)能不能正常使用，或者等作者发版（
