### ISSUE TITLE
危机合约版本更新无法刷钱本等物质搜寻关

### ISSUE THREAD

**Issue by Alirea10** [MaaAssistantArknights/MaaAssistantArknights#4051]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图，在今日版本更新后，maaV4.12.3（最新稳定版本）在刷理智选择龙门币（仅测试龙门币）时无法正常打开“物资搜寻”界面。细节如下
选择刷理智，选择龙门币6/5，linkstart，maa开始操作，回到首页，点击作战，发呆，报错结束fight。
初步推测由于此次更新让“物资搜寻”全部开启，让作战界面的物资搜寻变为金色导致ocr错误

### 日志文件

*由于不在电脑前不好操作，无法发送
**我以为有人已经提交bug，第一时间发现所以没管，现在来看才发现还没有

### 还有别的吗？

全部推荐配置，Win11，蓝叠国际，最新稳定版本maa4.12.3，检查更新为最新

**Comment by ABA2396** [comment]
我测了下是可以正常运行的，如果还有问题的话发下日志

**Comment by Alirea10** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11029285/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11029289/gui.log)
我使用其他账号测试，发现的确可以再次运行。
不过，我在当时已经在同一界面反复测试，确认了他可以被稳定的复现，但是现在又不行了。
以上是一个日志，bug发生在3/21的17:10分，GUI中的fight失败。由于asst过长，我手动删减了一部分，所以您看到的是一个不完整的asst，但是足够了。
值得一提的是，我回忆起当时好像由于危机合约的更新，战斗关卡选择界面的下面有两个红点，不知道是不是红点的原因，如果有可能找到一个完全没有上过的账号，或许可以复现？我应该还有相关的账号，我每日去尝试复刻
