### ISSUE TITLE
肉鸽开局干员选择助战不会触发

### ISSUE THREAD

**Issue by cwhypt** [MaaAssistantArknights/MaaAssistantArknights#4060]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刚开始上手肉鸽，maa在招募干员页面似乎会跳过选择助战的逻辑，看log似乎跳过了check_support_char 只运行了check_core_char
确认设置里勾选了使用助战，重启模拟器和maa也没有帮助，不知道是不是我哪里设置有错误

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11054752/asst.log)

时间2023-03-23 11:28:13.777

### 截图

![image](https://user-images.githubusercontent.com/22641706/227315447-d568fcf1-a70e-4066-b624-3460dd90fd4a.png)
![image](https://user-images.githubusercontent.com/22641706/227317565-7213ab86-e0e4-469f-b895-f5f4a1ab10c8.png)

### 还有别的吗？

台服，蓝叠模拟器5 Pie 64-bit

**Comment by ABA2396** [comment]
参考一下 #3857 繁中服应该是助战按钮的文本识别没适配，加一下text就行了

**Comment by cwhypt** [comment]
感谢回复，试了一下[#3857](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3857) 里面的text，貌似改成 
選擇助戰，選擇 或者 助戰 都不会进入助战界面，不知道和WLLEGit大佬的[提交](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/6f4fc8fa912d3887bb76ee0552c657c10ea79a9d) 有没有关系

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11064271/asst.log)

![image](https://user-images.githubusercontent.com/22641706/227581816-9ece9212-af11-451c-89f3-fb8193a0ea97.png)

**Comment by ABA2396** [comment]
对了，默认的编队组合就是 `取长补短`，因为一般都是近卫开局，而开局使用助战功能也是要手动指定开局干员的（）

**Comment by cwhypt** [comment]
我犯傻了，三个按钮都加进去现在能进助战页面了，不过右划两次就退出了，我看看是不是OCR的问题

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11064639/asst.log)

**Comment by ABA2396** [comment]
识别到了"、更新助戰列表"，但没匹配上。RoguelikeRefreshSupportBtnOcr的Text改过了吗

**Comment by ABA2396** [comment]
其实我感觉全写 `助戰` 也没毛病（x）这个刷新就算匹配上的话也只会刷两次还是几次，要是没刷到的话就是正常选自己的干员开局

**Comment by cwhypt** [comment]
改过了，是不是需要微调一下

![image](https://user-images.githubusercontent.com/22641706/227595984-013140a7-6389-43db-a6ad-237f7089ad29.png)

**Comment by cwhypt** [comment]
哈哈我试试

**Comment by cwhypt** [comment]
加上备选识别词条之后能识别到刷新按钮了，不过干员名字还是识别不了，估计是文字被遮挡的原因，大佬有建议怎么调整吗

![image](https://user-images.githubusercontent.com/22641706/227598154-81a5131d-72c3-4a8d-a6f2-fcde2e52569b.png)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11064910/asst.log)

**Comment by ABA2396** [comment]
那试试别的开局呢？比如开局借个 山 煌 百炼嘉维尔 什么的开局试试

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/227606714-601402ce-b58e-435b-8af5-1a6f69ffd2ac.png)
国服是这样的（）
@WLLEGit 有啥想法

**Comment by cwhypt** [comment]
扎心了，我就知道事情不会这么简单（

**Comment by WLLEGit** [comment]
繁中服是列表那种格式的助战的话确实是识别不了，现在roi是一个横条。而且列表里面干员名还会被背景颜色干扰，不太好处理

**Comment by cwhypt** [comment]
OK感谢大佬，之后有什么繁中的适配或者测试的话可以喊我，今天刚调试好visual studio 2333

**Comment by cwhypt** [comment]
> ![image](https://user-images.githubusercontent.com/99072975/227606714-601402ce-b58e-435b-8af5-1a6f69ffd2ac.png) 国服是这样的（） @WLLEGit 有啥想法

台服更新完ui也是这种形式了，测试了一下现在助战可以正常使用了，感谢大佬！
