### ISSUE TITLE
设置里面增加一个“自动使用X小时内的理智药水”

### ISSUE THREAD

**Issue by zhhq255762** [MaaAssistantArknights/MaaAssistantArknights#4062]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

由于上班挂机常常没时间手动玩，经常忘记吃药

### 有什么好的想法？

设置里面增加一个“自动使用X小时内的理智药水”，比如剩余12小时内的理智药自动吃

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/227432708-52638eac-829f-4fc4-81c2-daf8d6148f51.png)
