### ISSUE TITLE
仓库识别错误：D32钢7识别成1

### ISSUE THREAD

**Issue by Double-Lie** [MaaAssistantArknights/MaaAssistantArknights#4068]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最近的一次识别，有七个D32钢识别成一个。

### 日志文件

[depot.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11068100/depot.zip)

### 还有别的吗？

蓝叠国际

**Comment by horror-proton** [comment]
fixed in b7e026ea197e82d7ac1aac08fdc4acf183e29455
![2023-03-25_17-18-29-854_draw](https://user-images.githubusercontent.com/107091537/227708765-8be1cf3c-b214-4ee9-a219-c5f777ec810e.jpg)
