### ISSUE TITLE
DarkMode显示不完全符合预期

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#4069]
### 说说你遇到的问题？

<img width="590" alt="截图_20230325155228" src="https://user-images.githubusercontent.com/53437291/227704871-b42d320a-fea9-4723-9cf1-e8aa854b988a.png">
据观察所有输入框都有这个问题：两侧的线没有正确显示，看起来比较诡异

**Comment by ABA2396** [comment]
研究了一下午，没搞懂为啥
