### ISSUE TITLE
关卡中开局挂机放怪进家

### ISSUE THREAD

**Issue by CLanNT** [MaaAssistantArknights/MaaAssistantArknights#4070]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用MAA打水月肉鸽，进入关卡后MAA无任何操作，当怪走过半场时MAA开始进行暂停检查干员，随后开启2倍速放怪进家，当漏了两三只怪时才放下第一个干员，这样下来只要进两到三个战斗节点就稳定翻车。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11068766/asst.zip)

### 截图

![image](https://user-images.githubusercontent.com/74392382/227715084-2942459d-7719-4c16-b386-205437aab6be.png)

### 还有别的吗？

使用mumu模拟器x，使用DX渲染（用vulkan时独显不动很卡），触控使用兼容模式（默认模式没反应），也许是识别频率的问题，没找到对应选项（
QAQ

**Comment by yc080713** [comment]
（非专业回答）
1.下载图片后查看分辨率为2560*1440（符合16：9分辨率）。然后dpi设置了吗？符合maa所需的320dpi吗？
2.“触控使用兼容模式（默认模式没反应）”这一点，请参考[https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%BF%9E%E6%8E%A5%E6%AD%A3%E5%B8%B8-%E5%AE%8C%E5%85%A8%E6%B2%A1%E5%8F%8D%E5%BA%94-%E4%B8%80%E7%82%B9%E4%B8%8D%E5%8A%A8](url)

**Comment by MistEO** [comment]
你电脑太卡了，截一张图要 3 秒，不知道是不是 mumu 的问题，把分辨率降低点，或者换个模拟器

另外兼容触控模式本来就慢，默认没反应需要强制替换下 adb 的
