### ISSUE TITLE
关于自动关闭意外窗口的想法

### ISSUE THREAD

**Issue by kwa0035** [MaaAssistantArknights/MaaAssistantArknights#4072]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

众所周知，maa不能识别意外弹出窗口（比如博士资历升级），会直接愣住接着一连串报错

### 有什么好的想法？

最近注意到方舟客户端本体可以响应安卓系统导航三键的返回键，或许可以想办法让maa再碰到意外窗口时，向模拟器发送安卓返回指令。

**Comment by MistEO** [comment]
不处理就是 bug，发下日志

**Comment by ghg6666678** [comment]
等级提升的窗口不能识别？好像没遇到……
