### ISSUE TITLE
“MaaWpfGui.SettingsViewModel”的类型初始值设定项引发异常

### ISSUE THREAD

**Issue by illusive-B** [MaaAssistantArknights/MaaAssistantArknights#4074]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开MAA时，出现未知错误。
详细信息：
在 MaaWpfGui.SettingsViewModel..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.AsstProxy..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.RootViewModel..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 Stylet.Bootstrapper`1.get_RootViewModel()
   在 Stylet.Bootstrapper`1.Launch()
   在 Stylet.BootstrapperBase.Start(String[] args)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11070557/gui.log)

### 截图

![image](https://user-images.githubusercontent.com/78690876/227750509-199a787b-1f09-4387-bd43-48097c044d6d.png)

### 还有别的吗？

最近重装了最新的win10系统，重装后就出现未知错误。

**Comment by ntgmc** [comment]
![image](https://user-images.githubusercontent.com/74061867/227755954-3e294dad-2928-4664-8d0b-f9019f642ca5.png)
![image](https://user-images.githubusercontent.com/74061867/227755966-2812347f-941d-48c1-bf5a-2f2256775172.png)
![image](https://user-images.githubusercontent.com/74061867/227755971-e83198b1-3c45-4048-9609-64be0e79cc83.png)
