### ISSUE TITLE
v4.13.0-beta.1 新功能Darkmode(beta)的bug

### ISSUE THREAD

**Issue by virdmark** [MaaAssistantArknights/MaaAssistantArknights#4076]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在“一键长草”主界面拖动任务标签顺序会使被移动的标签变回lightmode。

### 日志文件

无

### 截图

![image](https://user-images.githubusercontent.com/94534273/227753316-0c419f79-2c1f-47fb-ab9e-44cb7b62fbff.png)
![image](https://user-images.githubusercontent.com/94534273/227753325-70a2394e-c726-4538-928c-d028c2a3200c.png)
![image](https://user-images.githubusercontent.com/94534273/227753326-d5bddd76-d36a-42b0-b0fb-f57cfb9e7e0f.png)
![image](https://user-images.githubusercontent.com/94534273/227753330-f7d0083d-f716-49a3-bdfd-8f68074b902a.png)

### 还有别的吗？

版本	Windows 10 家庭中文版
版本号	22H2
操作系统内部版本	19045.2728
序列号	PF30QW03
体验	Windows Feature Experience Pack 120.2212.4190.0

**Comment by ABA2396** [comment]
这玩意只是第一次显示的时候给染黑的，抓个会wpf的大佬来看看（）

**Comment by Cryolitia** [comment]
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit

可以考虑使用这套主题系统，可以支持运行时切换日夜模式
