### ISSUE TITLE
关闭蓝叠模拟器不完全

### ISSUE THREAD

**Issue by Hydrogina** [MaaAssistantArknights/MaaAssistantArknights#4079]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

这个问题曾经在pr #1878 修复了，现在因为最近改了蓝叠模拟器的关闭方式，问题又出现了
TaskQueueViewModel.cs：1006："BlueStacks" => KillEmulator(),
现在蓝叠只调用了KillEmulator()，没有调用killEumlatorbyWindow()，所以留下了一个窗口关不掉
![屏幕截图 2023-03-26 224038](https://user-images.githubusercontent.com/46482682/227784129-4f5f5818-65f9-4156-8501-c2227f595775.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11071978/asst.log)

### 截图

如上

### 还有别的吗？

建议先调用killEumlatorbyWindow()再调用killEmulator()

**Comment by ABA2396** [comment]
奇怪，我这里测试都能全部关掉，你用的是哪个版本的蓝叠

**Comment by JeBoome** [comment]
增加一个关闭失败的DP
我用的是Bluestacks 5 China，同时MAA的版本是v4.13.0-beta.1
没有找到更丰富的log信息（对不起），但测试中多次出现“模拟器关闭失败”，但可以在关闭失败之后正常执行休眠
![image](https://user-images.githubusercontent.com/30909579/227811959-aa347096-9f33-4df0-b408-9519341f5c53.png)

**Comment by Hydrogina** [comment]
蓝叠中国
平台版本号3.1.21.799
引擎版本号4.280.0.3001

**Comment by ABA2396** [comment]
看样子是蓝叠中国才有这个问题。但是根据窗口名关很容易关错模拟器，有啥办法获取到对应的进程么

**Comment by ABA2396** [comment]
我看了下蓝叠中国好像有控制台，国际版我没找到，你搜搜文件夹下有没有bsconsole.exe

**Comment by Hydrogina** [comment]
有，就在安装目录下

**Comment by ABA2396** [comment]
> 有，就在安装目录下

那应该好办，根据文件存不存在就能判断国际版还是国内版了，国内版用控制台关方便吗？（我看pie和nougat的端口号是一样的，这样根据端口用控制台关是不是不好指定模拟器）。还是说国际版就直接kill，国内版就killbywindows再kill

**Comment by Hydrogina** [comment]
> 还是说国际版就直接kill，国内版就killbywindows再kill

我觉得这样还ok，主要是我不太懂控制台的操作(

**Comment by ABA2396** [comment]
先试试能不能用）

**Comment by imaegoo** [comment]
自从最近改了蓝叠模拟器的关闭方式，我也遇到了模拟器关闭失败的问题。但我使用的并不是蓝叠中国版。

蓝叠国际版 HyperV 5.11.20.1010 P64
MAA 4.13.0-beta.1

```txt
3月31日 周五 14:04:23 任务已全部完成！
3月31日 周五 14:04:23 模拟器关闭失败
```

以下是完整的 asst.log 和 gui.log：[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11118821/debug.zip)

**Comment by ABA2396** [comment]
> 自从最近改了蓝叠模拟器的关闭方式，我也遇到了模拟器关闭失败的问题。但我使用的并不是蓝叠中国版，文件夹下没有bsconsole.exe
> 
> 蓝叠国际版 HyperV 5.11.20.1010 P64 MAA 4.13.0-beta.1
> 
> ```
> 3月31日 周五 14:04:23 任务已全部完成！
> 3月31日 周五 14:04:23 模拟器关闭失败
> ```
> 
> 以下是完整的 asst.log 和 gui.log：[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11118821/debug.zip)
> 
> 我使用Windows任务计划功能来定时运行MAA，无法关闭模拟器并不会影响使用，MAA会在下次启动时重新连接上模拟器。

蓝叠在任务管理里看看叫啥，现在蓝叠是进程名中找"HD-Player"，只有没找到才会报错

**Comment by imaegoo** [comment]
我的是蓝叠国际版 HyperV 5.11.20.1010 P64

在“进程”标签页中的名字是

* BlueStacks
* BlueStacks App Player

![image](https://user-images.githubusercontent.com/20182252/229391805-7704c93c-fe96-4e1e-966c-76396ea4fe33.png)

在“详细信息”标签页中的名字是

* HD-Player.exe

![image](https://user-images.githubusercontent.com/20182252/229391863-1c09240e-77e4-4ff5-9ce0-53875b512910.png)

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/4592797740
试试看能不能用）

**Comment by imaegoo** [comment]
> https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/4592797740 试试看能不能用）

@ABA2396 验证通过，模拟器可以自动关闭，日志信息

```txt
[2023-04-03 14:12:03.918][GUI][Px518][Tx6e4c] Info: `C:\Program Files\BlueStacks_nxt\bsconsole.exe` not found. This may be the BlueStacks International emulator, try to kill the emulator by the port.
[2023-04-03 14:12:04.011][GUI][Px518][Tx6e4c] Info: Failed to kill emulator by the port, try to kill emulator process with PID.
```
