### ISSUE TITLE
如图，之前一直用mumu甚至特意换成夜神还是不行

### ISSUE THREAD

**Issue by fnsix01** [MaaAssistantArknights/MaaAssistantArknights#408]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8602335/asst.log)
![{C6`{G S}}%GUC5R6{TIWQV](https://user-images.githubusercontent.com/58368369/166222570-06686c62-58f1-41a1-87ac-82958e8cb4d2.png)

**Comment by zzyyyl** [comment]
看了日志，你的分辨率是`720x1280`（？
难道是竖屏玩方舟？应该不是吧（
可能是雷电模拟器的问题？（我也是雷电，用着没问题啊）

**Comment by MistEO** [comment]
分辨率比较奇怪，是 `720x1280`，在模拟器分辨率设置里改成`平板版`试试（而非`手机版`）

**Comment by fnsix01** [comment]
我明白了，是我的锅（
我一直都是开着雷电模拟器挂着赛马娘的。。。
刚刚把雷电关了行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月2日(星期一) 晚上10:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 如图，之前一直用mumu甚至特意换成夜神还是不行 (Issue #408)





 
看了日志，你的分辨率是720x1280（？
 难道是竖屏玩方舟？应该不是吧（
 可能是雷电模拟器的问题？（我也是雷电，用着没问题啊）
