### ISSUE TITLE
能否增加后台运行/老板键的功能

### ISSUE THREAD

**Issue by cicada-kiru** [MaaAssistantArknights/MaaAssistantArknights#4081]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

想在公司电脑上挂机捏

**Comment by ABA2396** [comment]
设置里有个最小化到托盘，热键里也有展开/收起界面

**Comment by zzXan** [comment]
模拟器的话可以试试win+tab扔去其他桌面。

**Comment by cicada-kiru** [comment]
> 设置里有个最小化到托盘，热键里也有展开/收起界面

感谢，找到了
