### ISSUE TITLE
关于蓝叠5 hyper-v 版本的 adb 随机端口问题

### ISSUE THREAD

**Issue by SHIINASAMA** [MaaAssistantArknights/MaaAssistantArknights#4082]
### 说说你遇到的问题？

问题：
- 新版 MAA 对于蓝叠5 hyper-v 版本的文档是否已经过时？
- 这个问题是由于配置文件的错误还是 MAA 自身所致，我应该如何解决？

前提：
- 版本 v4.13.0-beta.1
- 已以管理员方式运行
- 连接设置中 ”自动检测连接“、”始终检测” 勾选，选择官服，其他选项无修改。
- 以下使用 **相关字段** 表示 Bluestacks.Config.Path 和 Bluestacks.Config.Keyword 等
- **相关字段** 的值在本机分别为 （按照文档在本机找到的）
  ```
  C:\\ProgramData\\BlueStacks_nxt\\bluestacks.conf
  bst.instance.Nougat64.status.adb_port
  ```

尝试与结果：
- 以往 issue 提示在 MAA 关闭的情况下往 gui.json 里直接添加**相关字段**即可
  实际存在 gui.json 这个文件，尝试新建 gui.json，如下所示
  ```json
  {
    "Bluestacks.Config.Path", "C:\\ProgramData\\BlueStacks_nxt\\bluestacks.conf",
    "Bluestacks.Config.Keyword": "bst.instance.Nougat64.status.adb_port"
  }
  ```
  启动后该文件会自动删除，且依然无法拿到 adb 端口，标题栏显示 127.0.0.1:5555。

- 修改 resource/config.json，尝试在根元素、options、BlueStacks 配置等添加**相关字段**，依然无法拿到 adb 端口，标题栏显示 127.0.0.1:5555。
  ```json
  {
    "configName": "BlueStacks",
    "Bluestacks.Config.Path": "C:\\ProgramData\\BlueStacks_nxt\\bluestacks.conf",
    "Bluestacks.Config.Keyword": "bst.instance.Nougat64.status.adb_port",
    "baseConfig": "General",
    "comment": "BlueStacks 配置"
  }
  ```

**Comment by MistEO** [comment]
看文档，模拟器支持里面写了

**Comment by MistEO** [comment]
存在 gui.json 直接就往里面加呀，为啥要新建

**Comment by ABA2396** [comment]
自动删除就是文件写错了。你那个里面冒号打成了逗号。

**Comment by SHIINASAMA** [comment]
> 自动删除就是文件写错了。你那个里面冒号打成了逗号。

不好意思，是打 issue 时打错了，我本地文件没写错这个的

**Comment by SHIINASAMA** [comment]
> 存在 gui.json 直接就往里面加呀，为啥要新建

不存在这个文件（resource 下也不存在），我记得以前用旧版本的时候是有的，不知道什么时候就没了，我在官网看的文档 [模拟器支持](https://maa.plus/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.html)

**Comment by MistEO** [comment]
![Screenshot_2023-03-27-14-25-45-207_com.android.chrome-edit.jpg](https://user-images.githubusercontent.com/18511905/227857997-e5cfcf03-7c78-42d3-a629-7e0eea6ecdf6.jpg)

改到 config 文件夹里了

**Comment by SHIINASAMA** [comment]
> 

谢谢你的帮助，看起来是我自己看错了，问题已经解决
