### ISSUE TITLE
启动后闪退

### ISSUE THREAD

**Issue by BiologyHazard** [MaaAssistantArknights/MaaAssistantArknights#4087]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新至版本4.13.0-beta1.29后，打开maa后无反应，过几秒后直接闪退。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11076923/asst.log)

**Comment by BiologyHazard** [comment]
重新下载稳定版之后按照更新提示更新至beta版后仍不可用。

**Comment by userchild00** [comment]
我今天更新相同版本后遇到相同问题，重启或回滚未解决

**Comment by ABA2396** [comment]
Controller 重构 出了点问题，先用之前的版本吧

**Comment by ABA2396** [comment]
已经撤包了

**Comment by MistEO** [comment]
修过了，试下最新的内测版
