### ISSUE TITLE
概率性的 点击一两次后就会报错

### ISSUE THREAD

**Issue by sailfishpoi** [MaaAssistantArknights/MaaAssistantArknights#4089]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

概率性的  出现 该症状   ， 现象为  
开始任务：Fight  后直接提示  任务出错：Fight    /  关卡仍在进行中时 ，提示 游戏崩溃，重新启动    /     关卡后识别失败  提示 任务出错：Fight  ，然后也不会继续下一步的公招等操作

### 日志文件

[26asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11079037/26asst.log)
[28asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11079042/28asst.log)
----
[26asst1.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11079064/26asst1.log)

### 截图

![屏幕截图 2023-03-27 204510](https://user-images.githubusercontent.com/42857487/227950396-afadcd8b-a642-4270-b2c5-ac90e5b10d3a.jpg)
![屏幕截图 2023-03-27 204533](https://user-images.githubusercontent.com/42857487/227950423-7034591e-612b-4957-9f18-2d71d1216e7e.jpg)
-----
![26asst1](https://user-images.githubusercontent.com/42857487/227950570-c7d10c0d-19df-45db-b078-7e6fc01fdeab.jpg)
----
![2023-03-26_21-21-47-627_raw](https://user-images.githubusercontent.com/42857487/227952312-a0a06206-fb86-4303-b359-fa74b8a9e372.png)

### 还有别的吗？

模拟器：夜神  7.0.3.5  安卓9
win10 22h2
cpu   5800x  32g  3060ti  522.25驱动

ps  从log中看出   执行数步后提示 
OcrPack::recognize | raw: [{ : [ 0, 0, 409, 151 ], score: 0.000000 }]
是模拟器自带的adb导致的问题吗

**Comment by ABA2396** [comment]
最后那个是debug文件夹下的图片么，估计是自带的截图出问题了，试试强制替换adb

**Comment by sailfishpoi** [comment]
> 最后那个是debug文件夹下的图片么，估计是自带的截图出问题了，试试强制替换adb

 是的 ，  最后一张图 是 位于 .\debug\drops 里面

**Comment by MistEO** [comment]
模拟器问题，换个模拟器试试
