### ISSUE TITLE
MAA窗口最小化后更新窗口点不开

### ISSUE THREAD

**Issue by vista98** [MaaAssistantArknights/MaaAssistantArknights#4091]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，今天我打开maa后最小化了，更新完毕之后弹出的“新版本下载完成的”的窗口就点不开了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11080468/asst.log)

### 截图

![屏幕截图 2023-03-27 233409](https://user-images.githubusercontent.com/107916926/227991496-18a9f97f-89ae-4b2c-af6e-f4da354c088c.png)

### 还有别的吗？

系统win10

**Comment by ABA2396** [comment]
这个好像和最小化没啥关系，正常运行也有几率打不开，但是没找到为什么会炸）

**Comment by moomiji** [comment]
> 这个好像和最小化没啥关系，正常运行也有几率打不开，但是没找到为什么会炸）

这个弹窗位置是根据主窗口的位置计算的，所以直接炸了（大概）
