### ISSUE TITLE
内测版4.13.0-beta.1.37.g24493835，start，在模拟器中动作后过几秒卡死

### ISSUE THREAD

**Issue by deYangar** [MaaAssistantArknights/MaaAssistantArknights#4092]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

内测版4.13.0-beta.1.37.g24493835，start，在模拟器中动作后过几秒卡死

### 日志文件

这是126k那台电脑的log [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11080684/asst.log)
这是6700hq那台笔记本的log [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11080936/asst.log)

### 截图

![IT7EI)6HTP@2 1277V~ LCH](https://user-images.githubusercontent.com/70438628/227997699-19e36492-6356-47af-90d9-cf0f4cddc6ab.png)

### 还有别的吗？

两台电脑，都遇到这个问题，同样版本。模拟器分别是蓝叠国际版和雷电5，更新前最后一次能正常使用
一台是6700hq+980m+16g
一台是12600kf+4090+32g

**Comment by cuthx** [comment]
同版本同模拟器同样问题，i5 8300h+gtx1060

**Comment by zzXan** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11083729/asst.log)
蓝叠5 国内版
Version v4.13.0-beta.1.37.g24493835
同样的问题

**Comment by SchwarzXia** [comment]
同版本，MUMU国际版，5800x，显示“开始任务：fight”后立刻卡死
触控模式修改为ADB Input后可正常运行

**Comment by WSMTBG** [comment]
同版本同模拟器，点开始后maa卡死闪退，拯救者R7000 2021

**Comment by Danny00002** [comment]
内测版4.13.0-beta.1.39.g7e74084e
蓝蝶国际
开始任务后连接完成闪退

**Comment by zzXan** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11084886/asst.log)
蓝叠5 国内版
v4.13.0-beta.1.39.g7e74084e
Minitouch闪退
ADB Input可以运行

**Comment by MistEO** [comment]
修过了，试下最新的内测版

**Comment by deYangar** [comment]
> 修过了，试下最新的内测版

可以了，感谢

**Comment by huiti** [comment]
> 修过了，试下最新的内测版

最新内测测试已经修复，不会闪退。
