### ISSUE TITLE
Is there a way where I can put a delay before facing the operators to whichever direction when deploying?

### ISSUE THREAD

**Issue by iSpaghetti** [MaaAssistantArknights/MaaAssistantArknights#4094]
### The problems you have encountered?

Is there a way where I can put a delay before facing the operators to whichever direction when deploying?

For example:
_**put the operator on a certain tile > wait for a sec or some millisecond > then face it to the right**_

There are times where it will get stuck there and need to manually face the operator if it missed the input when I use it for IS. Sure, I can just use ADB Input but it feels clunky and slow, and I also use MAA on my phone so adding that slowness to the latency of the connection from pc to phone, well it works but the other input types feels better.

**Comment by MistEO** [comment]
You can modify `resource/tasks.json` - `BattleUseOper` and `BattleSwipeOper`, It has Chinese comments in it, maybe you can use translation software to understand what each value does.

**Comment by iSpaghetti** [comment]
Oh, I see. That is a lifesaver, and I could just make a script to change it every time it gets overwritten for my lazy ass self.

Oh, I don't know if I should make another issue for this, but I will ask here anyway. I notice that when I use MAA on my phone with ADB Input and MaaTouch, it seems that it doesn't collect Ingots or Collectibles and use Recruitment Vouchers, it just exits right away, unlike when I use it with an emulator, it collects and uses them. I don't know about Minitouch because it gives errors when I use it on my phone, It works well with an emulator, though.

**Comment by MistEO** [comment]
You can open another issue with a log :)
