### ISSUE TITLE
最新内测版打开后无法恢复上次窗口位置

### ISSUE THREAD

**Issue by WSMTBG** [MaaAssistantArknights/MaaAssistantArknights#4096]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开以后在默认的左上，以前都是能恢复在关闭时的位置的（我是放屏幕右边的）

### 日志文件

/

**Comment by MistEO** [comment]
@LiamSho ——
