### ISSUE TITLE
MAA内测版闪退

### ISSUE THREAD

**Issue by dylanhz** [MaaAssistantArknights/MaaAssistantArknights#4098]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

执行基建换班前闪退，未进行任何操作

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11085626/asst.log)

### 还有别的吗？

v4.13.0-beta.1.39.g7e74084e

**Comment by pangbo13** [comment]
相似的情况，但是在开始刷理智之后崩溃，唯一的操作是点击开始按钮（配置和更新前一样）
[gui-20230328.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11085789/gui-20230328.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11085791/asst.log)

**Comment by Ptilopsis01** [comment]
相同的情况，我这里只要开始执行并且有操作就会闪退，直接完成的任务倒是没问题
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11085962/asst.log)
[gui-20230328.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11085964/gui-20230328.log)

**Comment by MistEO** [comment]
修过了，试下最新的内测版
