### ISSUE TITLE
清理智正常运行一关后在结束界面程序自动退出

### ISSUE THREAD

**Issue by Strive12138** [MaaAssistantArknights/MaaAssistantArknights#410]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8603208/asst.log)
活动关和资源关都会出现
逍遥模拟器8.0

**Comment by zzyyyl** [comment]
看样子是卡在了企鹅物流数据上报？

**Comment by MistEO** [comment]
帮忙提供一张软件崩溃后的游戏画面截图看下，需要模拟器自带的截图工具截取的原图~

**Comment by Strive12138** [comment]
目前填上了企鹅物流的ID仍旧会闪退
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8603533/asst.log)
![Screenshot_20220502-222554](https://user-images.githubusercontent.com/32629895/166251205-e0522401-b5cf-42a3-b441-87081c4e5e06.png)

**Comment by Strive12138** [comment]
测试LS-6
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8603571/asst.log)
![Screenshot_20220502-153204](https://user-images.githubusercontent.com/32629895/166252189-a3c2676e-5431-47b0-a69a-fc2f7e973979.png)

**Comment by Strive12138** [comment]
LS-5
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8603611/asst.log)
![Screenshot_20220502-153701](https://user-images.githubusercontent.com/32629895/166253032-195b0290-ec4d-4d20-acdb-ebc0eb3f787f.png)

**Comment by MistEO** [comment]
这个图片直接送进企鹅物流网站上的截图识别里，也出现了 crash, 企鹅的大佬们在帮忙分析了_(:з」∠)_

我感觉可能和左边那个 `10%` 的小悬浮窗有关，关了试试？

**Comment by Strive12138** [comment]
还真是悬浮球的问题，感谢
