### ISSUE TITLE
MuMu模拟器连接失败

### ISSUE THREAD

**Issue by grandassassinx** [MaaAssistantArknights/MaaAssistantArknights#4101]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MuMu模拟器连接失败（电脑重启后仍无法连接模拟器）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11090447/asst.log)

### 截图

<img width="585" alt="微信截图_20230328221251" src="https://user-images.githubusercontent.com/62973865/228266493-ed80aee3-2691-4385-b6b6-03c69a337aad.png">

### 还有别的吗？

MuMu模拟器版本：2.7.19.0 (x86)
MAA版本：v4.11.3.0-beta.1.44.gcd38cec8

**Comment by MistEO** [comment]
adb-lite 关了试试，maa 的连接设置里

**Comment by D9Lose** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11140610/asst.log)
[gui-20230404_001.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11140612/gui-20230404_001.log)
![QQ图片20230404005133](https://user-images.githubusercontent.com/39555559/229575946-1b224f71-627e-46eb-a0db-3e57c80bd1af.png)
![QQ图片20230404004710](https://user-images.githubusercontent.com/39555559/229575975-d1b3e9b4-d992-45f6-a33a-6b5e1c90c18f.png)

首次使用 无法链接adb

但是alas里又能调用

maa 4.13 b324
mumu12 3.2.18.1242

**Comment by Black1312** [comment]
关闭模拟器和MAA，管理员权限启动MAA后点击连接设置中的“替换ADB”是否可以正常连接？

**Comment by D9Lose** [comment]
> 关闭模拟器和MAA，管理员权限启动MAA后点击连接设置中的“替换ADB”是否可以正常连接？

尝试过，两个管理员运行后点击替换会显示mumu模拟器已被占用然后报错maa闪退。具体截图我没截下来
