### ISSUE TITLE
自动战斗拖放干员断触

### ISSUE THREAD

**Issue by SPFA-newbie** [MaaAssistantArknights/MaaAssistantArknights#4103]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗时在某些情况下（触发条件未确定），干员会放置失败
具体表现为：将干员拖出一段距离后断触，导致干员未被放置

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11091976/asst.bak.log)

### 还有别的吗？

使用的模拟器为逍遥模拟器
出现问题的关卡均为怪猎联动活动中的关卡，但是不确定在其他关卡中不会发生

**Comment by MistEO** [comment]
试试用 minitouch 或者 maatouch，在 设置 - 连接设置 - 触控模式 里
