### ISSUE TITLE
肉鸽连续失误

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#411]
这两天偶尔出现的连续肉鸽bug，怎么都过不了第一关
蓝叠国际版
显示设置如图，有可能是使用了低帧率模式？但是低帧率也试过完全没问题的时候。
![截图_20220502234929](https://user-images.githubusercontent.com/53437291/166264737-5b10f20b-bb74-47be-bd7b-1a59fb546e46.png)
![截图_20220502234531](https://user-images.githubusercontent.com/53437291/166264201-0a5ca56c-dcc6-4b58-99dc-a762284bc6f8.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8604079/asst.log)

**Comment by MistEO** [comment]
低帧率不行，会有问题，原因不明。总之需要 60 帧或更高_(:з」∠)_

**Comment by KJH-x** [comment]
收到🫡
