### ISSUE TITLE
蓝叠5连接失败

### ISSUE THREAD

**Issue by Chocomilk-Leo** [MaaAssistantArknights/MaaAssistantArknights#4115]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

之前一直使用正常，近一周开始出现连接失败问题
BlueStacks 5.10.0.6513 P64
MAA v4.12.3

已尝试：重装蓝叠模拟器

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11104732/asst.log)

### 截图

<img width="591" alt="image" src="https://user-images.githubusercontent.com/44537691/228646104-db1b9912-2d14-4a12-8044-627098a723fc.png">
<img width="591" alt="image" src="https://user-images.githubusercontent.com/44537691/228646136-36faabaa-3512-4a94-860e-5894921521c2.png">
<img width="591" alt="image" src="https://user-images.githubusercontent.com/44537691/228646793-1e1cf26c-bdf5-435f-ac2a-0676199a151a.png">

**Comment by Chocomilk-Leo** [comment]
<img width="591" alt="image" src="https://user-images.githubusercontent.com/44537691/228646404-cf1d071f-4fa9-46d8-a070-c00805614e75.png">

**Comment by Notofnice** [comment]
我也是一模一样的情况，MAA也停止不了

**Comment by Chocomilk-Leo** [comment]
我MAA可以停止，但大概需要半分钟左右（时间较长

**Comment by 1289183863** [comment]
请问现在问题解决了吗？

**Comment by Chocomilk-Leo** [comment]
还没

**Comment by Chocomilk-Leo** [comment]
尝试了一下打开MAA后等待几分钟开始操作，结果还是不行，MAA报错和之前一样，模拟器窗口会跳到顶层

**Comment by Black1312** [comment]
此问题已修复，请更新至最新公测版再试
