### ISSUE TITLE
Doesn't collect Ingots or Collectibles, use Recruitment Vouchers and gets stuck at Trader when using MAA on phone

### ISSUE THREAD

**Issue by iSpaghetti** [MaaAssistantArknights/MaaAssistantArknights#4116]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

I notice that when I use MAA on my phone with ADB Input and MaaTouch, it seems that it doesn't collect Ingots or Collectibles and use Recruitment Vouchers, it just exits right away, unlike when I use it with an emulator, it collects and uses them.

 It also wasn't buying any Collectibles when it was on the Trader stage, it tries to buy but it will just get stuck, then restarts the IS run.

I don't know about Minitouch because it gives errors when I use it on my phone and it will get stuck at "Stopping..." so  I need to restart MAA (You can see this pretty much at the top of the log). All of the input types works well with an emulator, though.

### Log files

Kept it running for an hour or so and it made 10 runs of IS.
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11105731/asst.log)
### 

### Screenshots

This are my settings when I use it for IS on my phone.
![image](https://user-images.githubusercontent.com/64988843/228659891-35ed828b-1d63-4110-abcc-68baf70a2d4b.png)
![image](https://user-images.githubusercontent.com/64988843/228659595-5731bfe2-fdb6-48fa-8a2c-85cf1a2b5753.png)

These are the screenshots from roguelike debug folder. Pretty much where my problems are occurring.
[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11105857/roguelike.zip)

### Anthing else?

The phone I used here is a rooted J7 Pro (Android 9). if it helps. It runs AK well despite being almost a 6yr old phone, just spare it with bloatwares.

**Comment by qaz1qazlol2** [comment]
You can try "adb input" method in the "Touch Mode",it might work(for me it works,I once used minitouch but it has some bugs,and I changed to "adb input"shortly after it)

**Comment by MistEO** [comment]
try "adb input"

**Comment by qaz1qazlol2** [comment]
I've menthio

**Comment by qaz1qazlol2** [comment]
I've mention the same problem in this issue #3619 .I think this is a problem of minitouch and maatouch(this problem in my phone even made everything cannot complete)

**Comment by iSpaghetti** [comment]
I used adb input and it still happens though.

Correct me if I'm wrong but from what I can understand after google translating the issue you mentioned is that it's a resolution issue, but the phone I used has a native 1080x1920 (9:16) screen, I also thought that it is a resolution issue so I downsized it to 720p and it still happens.

**Comment by iSpaghetti** [comment]
I'm sorry but I can't quite understand what you meant. By debug mode you mean like usb debugging?

**Comment by qaz1qazlol2** [comment]
maybe it is called 'pointer mode'

**Comment by iSpaghetti** [comment]
Oh, I see, the pointer location.

I don't really have that enabled when I use MAA because I know it might introduce new elements to the screenshots that MAA is taking and cause problems in the process when it goes through the ocr.

Although I did enable the pointer location to try and debug it since, just like I said, I thought it was a resolution problem that causes misclicks, but the clicks were spot on and there were no misclicks. It still just exits right away without collecting anything, and it will just abort the IS run if it didn't clearly see the exit (you can check the roguelike screenshots from the debug folder I provided above, where it can only see half of the exit). I think it's an ocr issue, though don't quote me on that.
