### ISSUE TITLE
自动公招问题

### ISSUE THREAD

**Issue by TaoMingxuan** [MaaAssistantArknights/MaaAssistantArknights#4118]
无论在公招设置中设置多少的最大招募次数，只会公招四次

**Comment by ABA2396** [comment]
就四个栏，难不成还能招8次

**Comment by ABA2396** [comment]
招4次以上的前提是勾上自动使用加急凭证，还有你是怎么做到这么多个模板不用又不提供详细信息来提issue的

**Comment by TaoMingxuan** [comment]
> 招4次以上的前提是勾上自动使用加急凭证，还有你是怎么做到这么多个模板不用又不提供详细信息来提issue的
*附上了公招设置的截图
![D0Y )TGR7O8L~FN Y9Q{TJX](https://user-images.githubusercontent.com/114936310/228827526-c203b846-a01f-4ff7-8a5a-92041dc8c7d3.png)

“还有你是怎么做到这么多个模板不用又不提供详细信息来提issue的” 对于这个问题 我也无法理解 实在抱歉

**Comment by ABA2396** [comment]
在debug文件夹下有个asst.log.那个文件也发下。

**Comment by TaoMingxuan** [comment]
> 在debug文件夹下有个asst.log.那个文件也发下。
*附上asst.log文件
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11111142/asst.log)

**Comment by MistEO** [comment]
我也好奇，你怎么提这个 issue 的，能不能截个图看下。按理说我们的模板应该是不让提空白 issue 的

**Comment by TaoMingxuan** [comment]
> 我也好奇，你怎么提这个 issue 的，能不能截个图看下。按理说我们的模板应该是不让提空白 issue 的

嘶  我也不知道了，我按照我昨天提issue的步骤现在也要模板了，当时是直接空白的。

**Comment by horror-proton** [comment]
似乎你的模拟器比较卡, 每次点完确认使用加急许可都卡了一段时间才成功, 导致 MAA 点了第二次确认点到右下角的公招栏位了
