### ISSUE TITLE
MAA在启动数小时后会出现未知错误卡死

### ISSUE THREAD

**Issue by Buntaqin** [MaaAssistantArknights/MaaAssistantArknights#4119]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA版本为内测最新版，使用模拟器是蓝叠国际版。在启动MAA并完成一次定时任务后，不关闭MAA和模拟器，会在下一次（或再下一次）定时任务启动时发生未知错误，并提示NET Framework 4.8错误，具体错误信息在下方bug.txt。此时整个MAA无法点击，只能在任务栏的小窗或任务管理器关闭

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11112090/asst.zip)

**Comment by CCCClaus** [comment]
我也是定时执行出现问题，（间隔8小时）定时执行卡死，定时执行无法正常启动。但是我没有弹出NET Framework 4.8错误。

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11120755/asst.log)


[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11120756/asst.bak.log)


在3.31 16：10发现卡死问题
