### ISSUE TITLE
“出现未种错误”，或卡死

### ISSUE THREAD

**Issue by cuthx** [MaaAssistantArknights/MaaAssistantArknights#4120]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最新内测版
link start后，执行至游戏启动界面后，maa断开连接，再link start显示出现未知错误，重启maa后恢复正常。
但是8个小时后（设置了定时）再看maa不是卡死就是又出现上述问题

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11113741/asst.zip)

### 还有别的吗？

蓝叠4
win10
i58300h+gtx1060

**Comment by CCCClaus** [comment]
我也是定时执行出现问题，（间隔8小时）定时执行卡死，不启动。

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11120755/asst.log)


[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11120756/asst.bak.log)


在3.31 16：10发现卡死问题

**Comment by cuthx** [comment]
[v4.13.0-beta.3]依然有这个问题
