### ISSUE TITLE
copilot：H11-4 retreat failed

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#4126]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用作业：maa://22009
无论是填写【撤退Mon3tr】还是【撤退7,3】都无法正常撤退

### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11120808/asst.-.log)

### 截图

录了个视频：https://wwvm.lanzouh.com/iY9yc0ro1kyh
测试过是能无限复现的

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/230766620-5d2f1b3d-4286-4427-be04-5ff821babc93.png)


之前改了点，我刚试了下应该下修掉了，close
