### ISSUE TITLE
日服基建找不到但书

### ISSUE THREAD

**Issue by akari3089** [MaaAssistantArknights/MaaAssistantArknights#4129]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

日服更新后排班找不到但书

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11124054/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/43425391/229178397-f688b64b-b59b-4b95-bf95-dd2e2d49e590.png)

### 还有别的吗？

蓝叠国际版
win10
最新内测版，在更新前也出现过相同问题

**Comment by hiyokrenli** [comment]
该程序似乎在内部将但书识别为 "プロヴァイン"。
重写json的工作。

**Comment by Black1312** [comment]
/resource/global/YoStarJP/resource/task.json中仿写ocrReplace字段写入但书测试是否可以正常编队和放入基建。测试通过后欢迎pr帮助我们完善MAA
