### ISSUE TITLE
宿舍使用autofill时重复Dorm3，日志里说选中干员与期望不符

### ISSUE THREAD

**Issue by CorleoneSong** [MaaAssistantArknights/MaaAssistantArknights#4132]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

上午的指定干员入驻没问题，中午时段宿舍使用的是autofill，第一次完成后四个宿舍一个休息干员都没有，我单独再用了一下基建换班，发现maa点进宿舍后点好入驻干员不点确定，而是退出去，再进这个宿舍，重复了3次才确定。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11128580/asst.log)

### 截图

![`$43ZAMJJCDL$0V25CU) 8O](https://user-images.githubusercontent.com/65541053/229268609-4d01f954-9094-4d62-8412-53d16f68c0e9.png)

**Comment by MistEO** [comment]
公测版改过了，更新一下

**Comment by CorleoneSong** [comment]
好好好，玛丽suki
