### ISSUE TITLE
自动肉鸽下干员阵亡，maa会试图部署已阵亡干员

### ISSUE THREAD

**Issue by Petertan303** [MaaAssistantArknights/MaaAssistantArknights#4139]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，自动肉鸽下干员阵亡，maa会试图部署已阵亡干员，具体表现就是反复拖动、暂停、失败，然后重复，直到干员再部署转好。

### 日志文件

并非异常情况，日志内无记录

### 还有别的吗？

模拟器是蓝叠X
![image](https://user-images.githubusercontent.com/63529504/229299406-810207b1-0b90-44eb-b7c4-3b2422aba2de.png)
按照要求配置

**Comment by MistEO** [comment]
发下日志

**Comment by Petertan303** [comment]
看了日志，意识到跑的还是旧版本
前几天下载更新的版本未更新成功，再次更新后问题消失

不好意思、添麻烦了。

另外，issue的回复里似乎不能上传文件？
![image](https://user-images.githubusercontent.com/63529504/229301691-23ef7e97-b832-4c61-92cd-75ada6c2ee67.png)

**Comment by ABA2396** [comment]
> 看了日志，意识到跑的还是旧版本
> 前几天下载更新的版本未更新成功，再次更新后问题消失
> 
> 不好意思、添麻烦了。
> 
> 另外，issue的回复里似乎不能上传文件？
> ![image](https://user-images.githubusercontent.com/63529504/229301691-23ef7e97-b832-4c61-92cd-75ada6c2ee67.png)

可以传的，估计是网络不好
