### ISSUE TITLE
肉鸽在选人界面卡住。

### ISSUE THREAD

**Issue by Yuzurucchi** [MaaAssistantArknights/MaaAssistantArknights#414]
开肉鸽的时候，无论哪个设置（尽量往后打，第一层退出，投资后退出）都会卡在第一个选近卫干员画面。过几分钟后会自动退出显示”已放弃本次探索“然后重开，无限循环。
![image](https://user-images.githubusercontent.com/102873696/166318401-85b88d36-9bfe-4540-b4a2-a4cd1d8e2334.png)
有幽灵鲨，而且tasks那里咱也没改过
![image](https://user-images.githubusercontent.com/102873696/166318672-23c5c520-3dbc-4c51-b936-b53abc3abc8a.png)

**Comment by MistEO** [comment]
附一下 asst.log 这个日志吧_(:з」∠)_

**Comment by zzyyyl** [comment]
让我来猜猜，应该是新干员`艾丽妮`引起的bug（

**Comment by MistEO** [comment]
[asst(12).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8611635/asst.12.log)

**Comment by MistEO** [comment]
`幽灵鲨` 识别成了 `灵鲨` 。。把你常用的干员多加几个吧，这一页上有的

**Comment by MistEO** [comment]
v3.3 fixed
