### ISSUE TITLE
启动MAA后，第一次运行提示连接失败，第二次运行提示未知错误

### ISSUE THREAD

**Issue by joka325** [MaaAssistantArknights/MaaAssistantArknights#4141]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启动MAA后，第一次运行提示连接失败，并启动模拟器。模拟器启动后仍提示连接失败，第二次运行后立刻提示出现未知错误，点击停止无响应，关闭并重启MAA后可正常运行一次，下一次运行依旧重复上述问题。问题出现于近至少三个内测版本(包括4.13.0-beta.2)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11130098/asst.log)
[gui-20230402.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11130100/gui-20230402.log)
全新安装的4.13.0-beta.2，log为安装后所有记录

**Comment by ntgmc** [comment]
补充几个情况
1，打开模拟器，未打开maa，使用adb devices能正常获取
2，重新打开模拟器，重新打开maa后，在勾选自动检测时开始运行，提示连接错误，此时使用adb devices获取不到任何端口
3，再次重新打开模拟器，重新打开maa后，maa不勾选自动检测，直接输入正确端口，连接正常，能正常获取端口

**Comment by YottaHub** [comment]
我也有类似情况，我以为是maa版本或者模拟器问题，把maa beta版本退回到通用版本，模拟器从mumu更改成蓝叠模拟器。依旧存在问题，两次连接失败，`HD-Adb.exe  connect 127.0.0.1:5555` 显示连接成功
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11131122/asst.log)

**Comment by ABA2396** [comment]
> 我也有类似情况，我以为是maa版本或者模拟器问题，把maa beta版本退回到通用版本，模拟器从mumu更改成蓝叠模拟器。依旧存在问题，两次连接失败，`HD-Adb.exe connect 127.0.0.1:5555` 显示连接成功 [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11131122/asst.log)

b2之后好像是有这个问题，试试看4.13.0-beta.1会不会遇到

**Comment by Black1312** [comment]
最新公测版是否仍有此问题？

**Comment by joka325** [comment]
> 最新公测版是否仍有此问题？

v4.13.0后问题未再次出现
