### ISSUE TITLE
增加用户自定义config.json

### ISSUE THREAD

**Issue by yd278** [MaaAssistantArknights/MaaAssistantArknights#4143]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

更新版本之后之前的config被覆盖掉了

### 有什么好的想法？

像vscode那样用多层config.json 优先找用户自定义的，没有则找默认的

（甚至可以分工作区的、用户的和默认的

**Comment by zzyyyl** [comment]
是不是指 tasks.json（

**Comment by yd278** [comment]
就是config …因为之前网络延迟比较大导致自动基建经常出问题所以在config里把扫描延迟调到1000ms但是发现每次更新之后又会回到500ms

不过最近几个月都没出现过这个问题了

**Comment by MistEO** [comment]
在 cache/resource/ 里放一份你自己的就可以了
