### ISSUE TITLE
会客厅会使用尤里卡

### ISSUE THREAD

**Issue by Nqiu97** [MaaAssistantArknights/MaaAssistantArknights#4145]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

会客厅会使用尤里卡,但明显这个基建技能并不适合

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11130863/asst.log)

**Comment by inCloudRain** [comment]
the same.
这个规避应该作成默认，还有贸易站。

**Comment by MistEO** [comment]
公测版更新过了
