### ISSUE TITLE
maa启动时提示Uuid command failed to exec

### ISSUE THREAD

**Issue by oracle91** [MaaAssistantArknights/MaaAssistantArknights#4146]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用的是x86的Mac，模拟器是mumu模拟器。重启系统后maa连接时就会提示Uuid command failed to exec
尝试了：
1、让电脑睡眠两小时，以前通过这样就能恢复正常，这次也没有用
2、将"uuid": "[Adb] -s [AdbSerial] shell settings get secure android_id" 改成"uuid": "[Adb] -s [AdbSerial] shell echo 111111"，也没有效果
目前无法使用，麻烦看一下

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11130943/asst.log)

[2023-04-02 09:20:38.858][INF][Px576][Txd08d0d33e5f4bb5f] Assistant::append_callback | ConnectionInfo {"uuid":"","details":{"address":"127.0.0.1:5555","config":"CompatMac","adb":"/Applications/MAA.app/Contents/MacOS/adb"},"why":"Uuid command failed to exec","what":"ConnectFailed"}

### 截图

<img width="900" alt="截屏2023-04-02 09 32 23" src="https://user-images.githubusercontent.com/24630854/229325952-cdb7d12a-17cf-4363-a6de-ec96150b9023.png">

### 还有别的吗？

系统MacOS 13.3，Intel芯片
MAA版本v4.13.0-beta.3，最近的几个版本都试了一下，都有该问题
模拟器网易mumu

**Comment by MistEO** [comment]
```log
adb shell failed: device offline
```

不知道为啥，重启模拟器/电脑有用吗

**Comment by oracle91** [comment]
重启模拟器/电脑都没有用。以前能正常连接的时候重启了电脑也变得不能连接。

**Comment by wxhwen** [comment]
我也遇到了这个问题。
mac 版本：12.6.3
MAA版本：v4.13.0
MuMu版本：1.9.58

*主要是其他模拟器连游戏都打不开。感觉推荐的mac下的模拟器不太靠谱：
1）蓝叠：没有mac版本
2）蓝叠国际版本：打开报错
3）夜神：报错

现在活动只能用mumu录制先，有没有其他在mac下成功用上的朋友？

**Comment by qwwwpp** [comment]
提供一个思路，Uuid command failed to exec 大概率是 adb 连接有问题，那要么模拟器没打开 adb，要么 MAA 连错了。

1. 如果模拟器没打开 adb， 查找一下自己用的模拟器在对应平台上怎么打开 adb，比如我用的是 mac 版的 夜神，Google 出来第一个回答就是：
https://stackoverflow.com/questions/55094680/how-to-set-adb-connections-for-nox-player-on-mac-os

2. 如果 MAA 连错了， 看一下MAA 设定里的 adb 地址对不对。adb 地址应该和模拟器的 adb 地址相同。Mac 版的夜神就是 127.0.0.1:62001

**Comment by soundofautumn** [comment]
模拟器改用avd后启动成功，能正常使用
应该是模拟器的问题，跟maa没啥关系

**Comment by wxhwen** [comment]
我已经解决了这个问题，参考：https://github.com/orgs/MaaAssistantArknights/discussions/4602

1、准备好MAC（intel）、MAA（保持最新版本呢）、MuMu模拟器，并且打开
2、进入命令行/终端
2.1 执行adb kill-server && adb server
2.2 执行 adb devices
--->这时候应该能看到“emulator-5554 device”
3、进入MAA，点击设置，链接地址改成“emulator-5554”
4、点击开始
