### ISSUE TITLE
MAA v4.13.0-beta3 链接手机闪退

### ISSUE THREAD

**Issue by yebing233** [MaaAssistantArknights/MaaAssistantArknights#4148]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

通过数据线链接手机运行MAA v4.13.0-beta3 点击 Link Start 后 闪退

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11131668/asst.log)

**Comment by MistEO** [comment]
@aa889788 看起来 minitouch 又炸了（

**Comment by aa889788** [comment]
> @aa889788 看起来 minitouch 又炸了（

android 10以上selinux会禁止shell对于input evdev的写入，要么用root，要么用adb或者maatouch

**Comment by MistEO** [comment]
> > @aa889788 看起来 minitouch 又炸了（
> 
> android 10以上selinux会禁止shell对于input evdev的写入，要么用root，要么用adb或者maatouch

可以报个错，return false，但最好不要 crash

**Comment by aa889788** [comment]
> > > @aa889788 看起来 minitouch 又炸了（
> > 
> > 
> > android 10以上selinux会禁止shell对于input evdev的写入，要么用root，要么用adb或者maatouch
> 
> 可以报个错，return false，但最好不要 crash

看了一下，有个error忘判断了

**Comment by MistEO** [comment]
@aa889788 #4151 是这个吗？

**Comment by aa889788** [comment]
> @aa889788 #4151 是这个吗？

对
