### ISSUE TITLE
使用理智小样时未识别数量

### ISSUE THREAD

**Issue by ManUtdLove** [MaaAssistantArknights/MaaAssistantArknights#415]
![image](https://user-images.githubusercontent.com/56555925/166335025-adb00377-8e5a-4458-84ff-4910864eea57.png)
理智小样会一次使用复数份，但设定使用份数时只会记录使用次数

**Comment by ABA2396** [comment]
再过4天就不会再有这个问题了.jpg

**Comment by MistEO** [comment]
这个没法改_(:з」∠)_不好意思
