### ISSUE TITLE
【国际服EN肉鸽】无法开局/自动放弃招募/无法好友招募

### ISSUE THREAD

**Issue by Tokii1** [MaaAssistantArknights/MaaAssistantArknights#4153]
使用过的模拟器：蓝叠国际版，逍遥模拟器。均有此问题
maa版本：MAA-v4.12.3-win-x64，MAA-v4.13.0-beta.3-win-x64，均有此问题。
不管是使用自己有的干员开局/删除留空白保持默认/借好友开局，全部都是在左右划两下然后放弃招募，包括勾选借好友时也并未点开好友助战列表。
因为国际服是新号，只有精1干员，不知道是否与无法识别精1立绘有关，但是感觉也不应该是放弃招募，而且也不点好友招募。

![11](https://user-images.githubusercontent.com/109557254/229356395-5ad02c8f-d336-411e-a0f3-56ad34af3383.png)
![22](https://user-images.githubusercontent.com/109557254/229356414-d2d52dde-1c98-4292-b68f-c6529a154644.png)
![33](https://user-images.githubusercontent.com/109557254/229356437-37412881-2285-4ac1-b039-21ff4ad6579e.png)

**Comment by Tokii1** [comment]
开局选令的话，可以识别并选出令（自己的），但是还是其他的一个预备干员都不选直接放弃。也同样无法使用好友助战。

**Comment by BlackNorton** [comment]
试过1280x720，320dpi吗？

**Comment by Tokii1** [comment]
> 试过1280x720，320dpi吗？

试过了，还是一样

**Comment by qaz1qazlol2** [comment]
英文名试一下，我开局用山直接输入mountain的

**Comment by Tokii1** [comment]
> 英文名试一下，我开局用山直接输入mountain的

山试了，可以，百嘉不行。现在问题比较重要的问题是 ：
1.会直接放弃识别不了的卡（就是连免费的预备都不选），也就是说除了开局那一个能识别的干员（例如山or令），剩下的所有票全是放弃（包括开局剩下的两票+后面关卡所有得到的新票），【导致全程一个干员单走到底】
2.没办法借好友的干员，目测是识别不到借干员的橙色按钮了。

**Comment by qaz1qazlol2** [comment]
百嘉的名字实在是太长了，可能会导致识别的问题(我猜的

**Comment by wuzhengreen** [comment]
我MuMu模拟器国际服也有这个问题，直接全部弃掉了，不能自动肉鸽好痛苦

**Comment by qaz1qazlol2** [comment]
> 我MuMu模拟器国际服也有这个问题，直接全部弃掉了，不能自动肉鸽好痛苦

我拿个人的山开局还是很香的(

**Comment by pein0saga** [comment]
> 百嘉的名字实在是太长了，可能会导致识别的问题(我猜的

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/4224#issuecomment-1500753542_

模仿这个解决方案，把
resource/global/YoStarEN/resource/tasks.json里的代码改一下可能就行了

```
           [
                "Gavial the Invincible",
                "Gavial the ",
                "百炼嘉维尔"
            ],
```

[967149a](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/967149abc648097525b758b42fbbd656f3512f6f)

**Comment by ABA2396** [comment]
> > 百嘉的名字实在是太长了，可能会导致识别的问题(我猜的
> 
> https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/4224#issuecomment-1500753542_
> 
> 模仿这个解决方案，把
> resource/global/YoStarEN/resource/tasks.json里的代码改一下可能就行了
> 
> ```
>            [
>                 "Gavial the Invincible",
>                 "Gavial the ",
>                 "百炼嘉维尔"
>             ],
> ```
> 
> [967149a](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/967149abc648097525b758b42fbbd656f3512f6f)
> 
> 找@ABA2396确认下可行性
>             

这是ocrReplace吧，那应该写
´´´
[
    "Gavial the",
    "Gavial the Invincible"
],
[
    "Gavial the Invincible",
    "百炼嘉维尔"
]
´´´
这种形式

**Comment by pein0saga** [comment]
> 许多长的名字和识别错误的都可以这样子改，比如鸿雪，她的英文识别是pozemka，没有e的第二声部

长见识了 代号“Позёмка”（拉丁拼写：Pozëmka），即为俄语中的“暴风雪”或“低吹雪

**Comment by pein0saga** [comment]
> > > 百嘉的名字实在是太长了，可能会导致识别的问题(我猜的
> > 
> > 
> > [#4224 (comment)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/4224#issuecomment-1500753542)_
> > 模仿这个解决方案，把
> > resource/global/YoStarEN/resource/tasks.json里的代码改一下可能就行了
> > ```
> >            [
> >                 "Gavial the Invincible",
> >                 "Gavial the ",
> >                 "百炼嘉维尔"
> >             ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [967149a](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/967149abc648097525b758b42fbbd656f3512f6f)
> > 找@ABA2396确认下可行性
> 
> 这是ocrReplace吧，那应该写
> 
> ```
> [
>     "Gavial the",
>     "Gavial the Invincible"
> ],
> [
>     "Gavial the Invincible",
>     "百炼嘉维尔"
> ]
> ```
> 
> 这种形式

是的,谢谢. 应该是
前置"text"才能合并一起写(不知道能不能三个合并,逗号分割)
前置"ocrReplace"必须用成对两两替换的格式
