### ISSUE TITLE
建议基建换班中ban掉艾丽妮

### ISSUE THREAD

**Issue by FSeagle** [MaaAssistantArknights/MaaAssistantArknights#4155]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

艾丽妮的基建技能决定了她需要持续停留在训练室中，即使干员没有处于专精过程，她不在工作状态，也需要停留在训练室。
但基建换班时会把她自动丢进宿舍里回复体力。（刚碰到一次专三，12小时没了。血亏QAQ）

就现有的可用的设置，感觉只有自定义基建能防止这个问题

### 有什么好的想法？

从实现的角度，单独去识别训练室的干员也挺烦。训练室其他干员的基建技能都是需要进宿舍回复体力的。
反正只有艾丽妮的技能需要这么做，干脆在换班的时候ban掉艾丽妮，识别到这个干员名字就跳掉她
艾丽妮需要回复体力的时候，肯定是人工手操：开始了一次专精，基建技能生效后，换下艾丽妮换上新干员。那回复体力也手操就行

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/229361450-9bc3f57c-452e-4b22-b1a4-f37dbe060cd5.png)
