### ISSUE TITLE
在mma工作结束后来一个自定义回调如何

### ISSUE THREAD

**Issue by Mr-oy** [MaaAssistantArknights/MaaAssistantArknights#4157]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我将mma部署在了自家的服务器上,通过某种很神奇的手段,它跑起来了,但是容易出现错误和卡死(表现为GUI不动,模拟器不动)
我需要一个自定义的回调来实现以下功能:
1. 当mma运行超过2小时(认为出错),重启mma和模拟器
2. 邮件通知我错误发生了
我的计划是实现一个类似看门狗的程序实现该功能,在启动mma时启动该程序,在mma结束时运行自定义的程序来终止该看门狗

### 有什么好的想法？

我希望MMA的GUI界面在结束时能支持自定义回调,比如打开某一个程序,传入某个参数一类的
![image](https://user-images.githubusercontent.com/69334528/229367617-963d71f3-4581-4007-ae3a-91e7f8bb5dc8.png)
或者不在这里,在设置里也可以

我尝试过使用python调用api,调用完api之后再执行相应的程序。但是效果并不理想,python的callback并没有给到我某一个任务是成功还是失败,详细的日志倒是给了不少,但这些我并不需要

如果可以的话谢谢大大了,感激不尽

**Comment by MistEO** [comment]
既然 UI 能实现，那 python api 就一定是能实现并且实现的更好的。

不过这个确实可以做一下，感觉还挺实用。

另外是 MAA 而不是 MMA（

**Comment by Mr-oy** [comment]
如果可以的话是否可以使用类似:.\sample.exe -i $log来传递某些信息比如$log 日志（gui右侧的日志）$adbInfo adb连接信息$setting 设置信息等等比较容易放进去的信息谢谢大大，捧花

**Comment by Mr-oy** [comment]
大大,目前已用python api 实现所需功能,是我眼睛瞎没找找文档 = =
但是还是希望能实现这个功能:
在GUI的某个位置能提供自定义回调的接口,在运行完maa后(所有的任务链完成后)执行该自定义回调
其中替换某些关键词:
$log         -->   GUI右侧的日志信息
$adbInfo  -->    adb连接信息
等比较容易放进去的信息

谢谢大大

**Comment by qaz1qazlol2** [comment]
的确挺有用的，我在服务器里挂maa结果云手机时不时给我整个花活（我开了自动肉鸽来获取报错截图，有官服的给我开美服的应用，有屏幕直接花了，还有美服肉鸽卡死（这东西还截不了图），很离谱）
