### ISSUE TITLE
麻烦给maa自动公招添加缺少没有招聘许可就自动跳过

### ISSUE THREAD

**Issue by WAP2080560553** [MaaAssistantArknights/MaaAssistantArknights#4159]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

因为挂上了之后招聘许可，由于最近比较黑信用那边好几次都买不到，从而招聘许可不断的在减少，然后今天用alas的maa插件挂上的时候自动流程，走到招募时卡住了，从而整个流程卡住直接发生错误

### 有什么好的想法？

给maa自动公招添加缺少没有招聘许可就自动跳过

### 其他内容

alas那边反馈需要maa能自动处理这个问题才能其他出错的情况区分开，https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2429#issuecomment-1492813048

**Comment by ABA2396** [comment]
MAA这边报错是不会影响后续运行的，估计alas那里是做了遇到TaskChainError就直接停止运行了。现在他们有做处理吗？

**Comment by SakuyaSaki** [comment]
> MAA这边报错是不会影响后续运行的，估计alas那里是做了遇到TaskChainError就直接停止运行了。现在他们有做处理吗？

应该是没有的 我在昨天还会遇到这个情况

**Comment by horror-proton** [comment]
#6569
