### ISSUE TITLE
【不那么重要】关于凌晨四点小助手无法继续进行的问题

### ISSUE THREAD

**Issue by YorigamiPL** [MaaAssistantArknights/MaaAssistantArknights#416]
呃，就是游戏会因为数据更新等问题，通常在凌晨四点会回到登录界面，但小助手会卡在数据更新的页面，直接出错停止运行了
![待机界面](https://user-images.githubusercontent.com/37739947/166394462-305207da-ff8a-4972-8d87-9eff53f15e59.png)
![任务出错](https://user-images.githubusercontent.com/37739947/166394469-442ade82-6c76-4ebc-8705-a17e143ac929.png)

以前这个页面应该是游戏领取每日登录奖励后的那个，奖励领取跳出页面，类似于下面这种的
![Q(~103EHGI I%AQE0H23% D](https://user-images.githubusercontent.com/37739947/166395431-31c76f3b-c812-431c-bee5-3c194ee9f7eb.jpg)
这次不知道为什么会卡在“即将同步”那里

下面的图是模拟器版本，和我做的ADB设置；我只打开了那个ADB调试，模拟器其他的地方我没动，小助手的调试设置我也没动
![模拟器版本](https://user-images.githubusercontent.com/37739947/166394687-a33ceb15
![ADB开关](https://user-images.githubusercontent.com/37739947/166394691-fe8d5b81-b87d-43be-a7ac-b51486a07998.png)
-bf5d-4164-a264-b67f8c6e1790.png)
![调试设置](https://user-images.githubusercontent.com/37739947/166394695-9ba1aca1-dad7-4320-939b-edd79961f020.png)
下面的是日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8607936/asst.log)

额外：我写到这里的时候，我想起以前如果只点了“开始唤醒”和“无限刷肉鸽”，小助手是可以四点过后继续运行的。所以在刷理智的那个页面，我也许应该选“上次作战”而不是“当前关卡”？因为即便解决了凌晨四点的问题，即可以回到游戏主界面，“当前关卡”也无法从主页面跳转到关卡界面，但“上次作战”可以
我还没试“开始唤醒”和“上次作战”能不能在四点跳到主界面，如果能这就不是个问题了，只要我睡觉记得前选“上次作战”就行

**Comment by MistEO** [comment]
这个问题已经修复过了 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/a05191fb5ec7e5eb417a8b04f212adf56bd3d562 ，还没有发版，预计今天或者明天发

**Comment by YorigamiPL** [comment]
好哦
