### ISSUE TITLE
[Bug from crash dump] Unchecked use of std::optional

### ISSUE THREAD

**Issue by dantmnf** [MaaAssistantArknights/MaaAssistantArknights#4163]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Crash dump from Telegram user `@Rbqwow`:

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/f1772ccd590b2a3df09b426acb178671b023e194/src/MaaCore/Task/Roguelike/RoguelikeBattleTaskPlugin.cpp#L204

![image](https://user-images.githubusercontent.com/2252500/229485383-cda768e4-e13a-43fe-a0fa-d9e545aff239.png)

### Log files

N/A

**Comment by dantmnf** [comment]
duplicate of #4160

**Comment by MistEO** [comment]
@LingXii please help to fix, thx
