### ISSUE TITLE
多开maa时关闭其中一个会结束全部adb进程

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#4165]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题 会导致未被关闭的另一个maa进行重新连接且耗时较长

- 导致minitouch卡死 需要重启maa
- ~严重影响自动战斗相关任务~

_v4.13.0-beta.3.24.g8d6ffde5_
_使用不同maa相同adb_

### 日志文件

((这问题用不上日志吧

### 截图

见了个鬼
![1](https://user-images.githubusercontent.com/55343783/229521780-30a464c7-0b56-46f6-8ce9-9505f27b4056.png)

### 还有别的吗？

_本来只知道会卡上个几十秒想扔到建议分类但是突然发现又会卡死触控就改到这边了_
原建议：
maa启动的adb进程是自己的子进程
可尝试识别子进程并结束
~本来想的是启动adb时记录pid然后结束~
~但是发现maa好像会不时启动停止好几个adb~

**Comment by Rbqwow** [comment]
Remove {copilot}
Add {gui}

**Comment by Rbqwow** [comment]
Remove {module: copilot}

**Comment by Rbqwow** [comment]
remove {copilot}

**Comment by Rbqwow** [comment]
Skip {copilot}

**Comment by Rbqwow** [comment]
Remove labels

**Comment by Rbqwow** [comment]
Remove copilot

**Comment by Rbqwow** [comment]
Remove {copilot}

**Comment by Rbqwow** [comment]
remove module: copilot

**Comment by Rbqwow** [comment]
remove `module: copilot`

**Comment by Rbqwow** [comment]
remove module labels

**Comment by Rbqwow** [comment]
remove `copilot`

**Comment by Rbqwow** [comment]
remove `copilot1`

**Comment by Rbqwow** [comment]
remove copilot

**Comment by Rbqwow** [comment]
remove copilot1

**Comment by zzyyyl** [comment]
> (草了这个copilot的label怎么死活删不掉

想起来了，issue_comments 不能触发删除标签，你可以改issue描述：）
