### ISSUE TITLE
关闭模拟器异常

### ISSUE THREAD

**Issue by C-YuLong** [MaaAssistantArknights/MaaAssistantArknights#4170]
### 说说你遇到的问题？

我使用的是夜神模拟器，MAA退出模拟器的时候会留下一个模拟器的窗口，但是在之前的版本是没有这个问题的。

**Comment by MistEO** [comment]
提个 bug 发下 gui.log

**Comment by C-YuLong** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11144460/gui.log)

**Comment by ABA2396** [comment]
新版本是用夜神的控制台关的，如果是最新版本还遇到这个问题的话那就是夜神的问题了）
