### ISSUE TITLE
水月肉鸽中 MAA携带奶盾临光技能导致的卡关

### ISSUE THREAD

**Issue by PieceOfFall** [MaaAssistantArknights/MaaAssistantArknights#4171]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

版本号: v4.13.0-beta.3
maa给临光带的一技能，但一直停留在临光属性面板处，执着于手动释放一个自动释放的技能，导致卡关问题。

### 日志文件

发生时间：2023-04-04 16:15:35
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11146234/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/85009059/229729768-e663f523-820c-46fb-8e67-0630c3ec1de4.png)

**Comment by Outsider225** [comment]
4.13.0-beta.3版本，同样是海窟沙暴这关，海沫1技能也会出现相同的选中海沫，等待释放技能的情况
