### ISSUE TITLE
MAA工作一天后罢工

### ISSUE THREAD

**Issue by kuruxi86** [MaaAssistantArknights/MaaAssistantArknights#4172]
### 说说你遇到的问题？

概括来说，就是MAA工作一天后第二天不在正常工作（但不确定一定是maa的问题）
详细缘由如下：
我在上周由于需求变更，将原本的24h内定时启动5次更改为一天3次，从4月2日开始运行，4月2日（在家），4月3日（不在家）均正常运行，但4月3日俩个maa均罢工，原因不明。附上日志
版本为4.10.3（秉持着遇事不决调版本的道理，所以4.12.3我也试过）
所以我怀疑可能不是maa的锅
[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11148410/asst.-.zip)

**Comment by koscos** [comment]
我也遇到了同样的错误(4.12.3)，无法启动，但昨天、前天和大前天都很好。
所以这是今天发生的第一个错误。
这不是使用后一天出现的错误。

**Comment by kuruxi86** [comment]
> 我也遇到了同样的错误(4.12.3)，无法启动，但昨天、前天和大前天都很好。 所以这是今天发生的第一个错误。 这不是使用后一天出现的错误。

我是定时启动出的问题，我在电脑前的话还是不会罢工的
