### ISSUE TITLE
在水月肉鸽模式里，maa在藏品界面卡住，不能继续进行

### ISSUE THREAD

**Issue by luo-luo-o** [MaaAssistantArknights/MaaAssistantArknights#4175]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

version：v4.13.0-beta.3
昨天（2023,4,5 03:27:21左右）在水月肉鸽模式（3难）中，maa在藏品界面卡住，在打完第三层进入第四层时发生，之后就一直卡住不动了

### 日志文件

[asst.log](https://musetransfer.com/s/wwbnjkthm)
bug时间点：2023.4.5 03:27:21
(不会压缩只能用第三方传输工具，若文件过期可联系我重新上传

### 截图

![image](https://user-images.githubusercontent.com/129922074/229976415-41d8985e-24a6-4f08-9684-44622adcd4bd.png)
![MuMu20230405110112](https://user-images.githubusercontent.com/129922074/229976485-69698147-952b-4eab-927b-78f22a75c206.png)

### 还有别的吗？

![image](https://user-images.githubusercontent.com/129922074/229981687-07d8ffac-6919-4b5f-b1e7-406de90f8c7d.png)
![image](https://user-images.githubusercontent.com/129922074/229981826-77e1efdf-6d8c-49b1-b43a-a5703392c12f.png)

**Comment by MistEO** [comment]
[asst (26).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11155661/asst.26.zip)

暂时没空看，我先压一下传上来

**Comment by Lancarus** [comment]
duplicate of #5892
