### ISSUE TITLE
肉鸽模式下成功通关跳过剧情

### ISSUE THREAD

**Issue by HeartyYF** [MaaAssistantArknights/MaaAssistantArknights#4179]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在如果在肉鸽下成功通关好像就卡住不动了

**Comment by ABA2396** [comment]
成功通关会跳过剧情的，如果卡住了发下日志提个bug反馈
