### ISSUE TITLE
最新版关闭模拟器情况下开始执行任务，会成功打开模拟器但是连接失败

### ISSUE THREAD

**Issue by zoe4477** [MaaAssistantArknights/MaaAssistantArknights#4180]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

设置了定时任务和执行完成后关闭模拟器，原先定时任务启动时会自动打开蓝叠模拟器并连接，现在启动（不管是在定时任务还是手动启动），都只会打开模拟器但是连接失败
![image](https://user-images.githubusercontent.com/38827851/230047756-dbcdd798-c11f-43a5-b49b-078664524c2f.png)
并且停止任务再重新执行后，还会出现未知错误。只能关闭MAA再打开才能执行成功
![image](https://user-images.githubusercontent.com/38827851/230048406-b2993284-808d-4dc2-b507-34e08ce6a63d.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11157541/asst.log)

**Comment by ABA2396** [comment]
dev修了还没发版
