### ISSUE TITLE
在设置中点击检查更新按钮MAA卡死

### ISSUE THREAD

**Issue by moomiji** [MaaAssistantArknights/MaaAssistantArknights#4184]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

rt

### 日志文件

[gui-20230405_001.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11160684/gui-20230405_001.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11160698/asst.log)

**Comment by MistEO** [comment]
新版本修了，试试看

~~很矛盾要升级就得先检查更新但检查更新卡死了~~

**Comment by moomiji** [comment]
> 新版本修了，试试看
> 
> ~很矛盾要升级就得先检查更新但检查更新卡死了~

我已经升到最新了

~看commit没看出是在什么时候修的，还得发包后才能试试~
