### ISSUE TITLE
日服：自动基建在上干员的时候会有很多空位

### ISSUE THREAD

**Issue by AkiraChisaka** [MaaAssistantArknights/MaaAssistantArknights#4186]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我用MAA处理日服账号，但是基建里上干员的时候会有很多房间，明明还可以上干员，但是是空的。

可能是因为没有足够的有技能的干员，但是按理说就算没有技能，每一个部屋里也应该放干员才对。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11162721/asst.log)

### 截图

![Screenshot_2023 04 05_13 13 18 065](https://user-images.githubusercontent.com/47231500/230199226-082bf3b9-8c45-4c15-9ddf-aeb6b8aae0ef.png)
![Screenshot_2023 04 05_13 13 09 682](https://user-images.githubusercontent.com/47231500/230199228-e79656b9-a841-4a62-8801-ddc52ade2e7e.png)
![Screenshot_2023 04 05_13 13 13 182](https://user-images.githubusercontent.com/47231500/230199230-a903f120-6530-434e-a1d4-706f5125fa6f.png)

**Comment by pein0saga** [comment]
可能是外服翻译适配不完全导致的识别问题,挺普遍的
