### ISSUE TITLE
日服：输入关卡名并试图刷理智会出现未知错误。

### ISSUE THREAD

**Issue by AkiraChisaka** [MaaAssistantArknights/MaaAssistantArknights#4187]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我在用MAA玩日服，输入关卡名并试图刷理智会出现未知错误。

游戏一点反应都没有，MAA卡死。

似乎是因为输入了LS-5，CE-5，SK-5这些关卡。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11162922/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/47231500/230206267-7ff46d00-23c3-4539-ab5a-46a18870af4e.png)

**Comment by ABA2396** [comment]
SK-5没做导航，龙门币记录这些要输入CE-6，LS-6，6没开会去找5的

**Comment by AkiraChisaka** [comment]
> SK-5没做导航，龙门币记录这些要输入CE-6，LS-6，6没开会去找5的

了解了，那么想刷SK-5，空置就可以了吧？

![image](https://user-images.githubusercontent.com/47231500/230248717-92469bc5-89cb-4d56-b23d-4e573f6a6c19.png)

这样的话MAA应该就会自动去刷上一次刷过的本了。

**Comment by AkiraChisaka** [comment]
好了，看起来没问题了，谢谢[ABA2396](https://github.com/ABA2396)！

我把这个Issue关掉了。

**Comment by ABA2396** [comment]
> > SK-5没做导航，龙门币记录这些要输入CE-6，LS-6，6没开会去找5的
> 
> 了解了，那么想刷SK-5，空置就可以了吧？
> 
> ![image](https://user-images.githubusercontent.com/47231500/230248717-92469bc5-89cb-4d56-b23d-4e573f6a6c19.png)
> 
> 这样的话MAA应该就会自动去刷上一次刷过的本了。

对的，空字符串对应的就是 当前/上次
