### ISSUE TITLE
国际服基建换班无法识别红松组合

### ISSUE THREAD

**Issue by BlackNorton** [MaaAssistantArknights/MaaAssistantArknights#4192]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用国际服153排班表，MAA无法识别红松干员，就是远牙，灰毫，野鬃组合
看了下issue貌似有人在日服也发现类似问题了，如果是图片不适配，我可以帮助提供

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11166200/asst.zip)

### 截图

![2023-04-05 20_29_50-MAA - v4 13 0-beta 1 - 蓝叠模拟器 (127 0 0 1_5555) - 国际服 (YoStarEN)](https://user-images.githubusercontent.com/65427501/230265247-280506cd-fb7a-4f64-b505-8ddaaeb3a36d.png)
![Screenshot_2023 04 05_20 31 02 212](https://user-images.githubusercontent.com/65427501/230265359-8959d445-0b27-433f-960e-7df007242677.png)

### 还有别的吗？

蓝叠国际版5.0.230.1001 N32，1280x720，320dpi，MAA v4.13.0-b1

**Comment by Constrat** [comment]
After latest the commits for version v4.20.0 for infrastructure operatore awareness, all operators get recognized correctly, if you still have issues feel free to let me know and reopening this issue.
