### ISSUE TITLE
刷理智在特定情况下会卡在选章节界面，无法自动跳转到1-7

### ISSUE THREAD

**Issue by xxuurruuii** [MaaAssistantArknights/MaaAssistantArknights#4194]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11170676/asst.log)
时间：4月6日晚20:33:58

### 截图

![image](https://user-images.githubusercontent.com/73776500/230380954-2e9dd99e-fe2b-4c8d-976f-b15e550db97f.png)
![Screenshot_20230406-203940](https://user-images.githubusercontent.com/73776500/230381203-2528b91f-aadb-4f43-904b-831b4f64b707.png)

### 还有别的吗？

模拟器：雷电
操作系统：win11

**Comment by MistEO** [comment]
应该是新出的第十二章影响了识别 @ABA2396

**Comment by ABA2396** [comment]
还有这个问题么
