### ISSUE TITLE
MAA v4.13.0-beta.3 新版本下载失败

### ISSUE THREAD

**Issue by wycgi520** [MaaAssistantArknights/MaaAssistantArknights#4196]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Win11 系统
MAA v4.13.0-beta.3 - 公测版

新版本下载失败

### 日志文件

04-06 23:11:16 新版本下载失败
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11171995/asst.log)
[gui-20230406_002.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11172005/gui-20230406_002.log)

### 截图

![image](https://user-images.githubusercontent.com/45585284/230423500-b6752bdf-1d88-4fa6-a20b-fc5fee9d3b52.png)

![image](https://user-images.githubusercontent.com/45585284/230423537-ec13b23d-01f1-49c5-bcf3-8a5582654ced.png)

### 还有别的吗？

蓝叠模拟器 Hyper-v 版本

**Comment by Black1312** [comment]
请手动前往[ota.maa.plus](https://ota.maa.plus/)更新
