### ISSUE TITLE
宿舍换班保留干员

### ISSUE THREAD

**Issue by Blind-Guess-Senior** [MaaAssistantArknights/MaaAssistantArknights#42]
作者大大你好
今天用了一下基建换班的功能，是直接换掉心情高的干员。那种在宿舍给回心情的干员也会被换掉（留着这种干员应该是效率更高的...吧？），大大有没有考虑加一个干员不换下的功能（比如每个宿舍的第一号位不换）
不过我一学生党好像全换反而更好_(:з」∠)_
算是有点强迫症？
快进到全自动高定制方舟长草机XD 作者大大辛苦了

**Comment by MistEO** [comment]
是的，是还没来得及做_(:з」∠)_下次一定！

**Comment by MistEO** [comment]
现在似乎可以用自定义基建功能来实现了，closed！
