### ISSUE TITLE
基建换班有bug，漏换发电站、贸易站

### ISSUE THREAD

**Issue by zhazha405** [MaaAssistantArknights/MaaAssistantArknights#420]
模拟器：BlueStacks 5 Nougat 64 位 (Hyper-V)
有一次使用，发电站没人，不会换班，今天又遇到贸易战没人，不会换班
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8609689/asst.log)

![MJIH(W@~% A~73FGQAOZZQW](https://user-images.githubusercontent.com/13600095/166434453-347b29af-7504-4df5-9963-d276a1c2687a.png)
![{95(~E(}R%21YCEKFEQRN93](https://user-images.githubusercontent.com/13600095/166434624-683ee7fb-140a-497c-b2cd-b30102e48898.png)

**Comment by zhazha405** [comment]
> 问一下 maa 在你这边是不是无人机一直都不加速_(:з」∠)_
> 
> 问题是由于无人机卡住了导致的 orz

我试了一下，一直盯着他换班，发现确实在加速时卡在取消/确定的弹窗上了，我自己手动点过去后就正常了

**Comment by MistEO** [comment]
> > 问一下 maa 在你这边是不是无人机一直都不加速_(:з」∠)_
> > 问题是由于无人机卡住了导致的 orz
> 
> 我试了一下，一直盯着他换班，发现确实在加速时卡在取消/确定的弹窗上了，我自己手动点过去后就正常了

试试 3.2.2 有没有效果，理论上应该修掉了

**Comment by zhazha405** [comment]
> > > 问一下 maa 在你这边是不是无人机一直都不加速_(:з」∠)_
> > > 问题是由于无人机卡住了导致的 orz
> > 
> > 
> > 我试了一下，一直盯着他换班，发现确实在加速时卡在取消/确定的弹窗上了，我自己手动点过去后就正常了
> 
> 试试 3.2.2 有没有效果，理论上应该修掉了

3.2.2正常了，谢谢开发者！辛苦了

**Comment by MistEO** [comment]
v3.3 fixed
