### ISSUE TITLE
关于作业视频识别功能的使用和说明（疑问）

### ISSUE THREAD

**Issue by yc080713** [MaaAssistantArknights/MaaAssistantArknights#4201]
我在翻过了
https://github.com/MaaAssistantArknights/MaaAssistantArknights/
下的文档和issues后没看见关于作业视频识别功能的说明（可能是我没翻到，抱歉我不会使用GitHub）

在询问 @ABA2396 后同意了创建issue的想法
以下是使用疑问：

1.作业识别的入口？
2.作业识别功能的使用方式？
3.对于视频编码、分辨率、格式的要求？
4.视频识别时的编码要求？（最后使用的是哪一种？）
5.对于视频内容的要求？（如是否能识别模拟器边框、异形屏设置等）
6.对于电脑性能的要求（主要是写一些例子，比如某某配置某某时长某某分辨率、码率所需的识别时间）
7.对于识别失败的所有可能性（包括识别到一半报错）

**Comment by Black1312** [comment]
敬告各位作业人：
视频不可有边框、黑边等（包括模拟器边框等）
暂不支持召唤物、道具使用（仅支持干员部署）
画质建议720p即可,如果生成失败可尝试其他画质，此问题原因未知，已反馈
MAA默认为不更改技能、不会自动选择二倍速、干员方向可能会有问题，请注意核查！请注意核查！请注意核查！
使用方法：将符合条件的作业视频拖放入自动战斗“选择作业”按钮上，点击“开始”等待即可
最后，关注@MAA-Official ，谢谢喵~​
如有问题请另行提交issue或加群询问管理员
