### ISSUE TITLE
iOS playcover运行肉鸽时会换下6星角色

### ISSUE THREAD

**Issue by uesakayou** [MaaAssistantArknights/MaaAssistantArknights#4209]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

快速编队中将6星干员换下了，发生节点17:26
顺带一提现在三星会优先选择临时招募而不是已练三星干员，不确定时feature还是bug姑且提一下

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11177815/asst.log)

### 截图

<img width="756" alt="image" src="https://user-images.githubusercontent.com/86504999/230584317-c69ec6fd-9da9-41f8-b220-9582b9c95acd.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/86504999/230584356-3174cf4f-fa6a-4e8b-91d4-9528304d8419.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/86504999/230584394-6da61357-a3b1-4701-8fe1-364afb650dea.png">

**Comment by horror-proton** [comment]
fixed in #4246
