### ISSUE TITLE
自动肉鸽在拥有时光之末时战斗失败后卡住

### ISSUE THREAD

**Issue by AsterNighT** [MaaAssistantArknights/MaaAssistantArknights#421]
开太久了log有点大，压缩后上传。
似乎在 #214 中已进行修复，但依然存在这一问题。
![image](https://user-images.githubusercontent.com/22937027/166445359-c4ae0070-1ac2-4bb1-9914-9ad85712f2a3.png)
![image](https://user-images.githubusercontent.com/22937027/166445376-d4402568-0fcd-43d8-a85f-092e572a39ab.png)
![image](https://user-images.githubusercontent.com/22937027/166445384-6a9c12d8-1676-4cbb-a4d0-65b589d7285e.png)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8610142/asst.zip)

**Comment by MistEO** [comment]
修是修了，但没验证_(:з」∠)_出现的概率有点低。。现在重新又修了一下，应该ok了，下个版本发布

**Comment by zzyyyl** [comment]
> 修是修了，但没验证_(:з」∠)_出现的概率有点低。。现在重新又修了一下，应该ok了，下个版本发布

可以用`深入调查-逢生`来测

**Comment by MistEO** [comment]
v3.3 fixed
