### ISSUE TITLE
关于宿舍补满空位的机制

### ISSUE THREAD

**Issue by SYuanLUV** [MaaAssistantArknights/MaaAssistantArknights#4211]
补满空位会把在训练室协助专精完成的艾丽妮放去休息。如果是专二(一)完成但没来得及继续专精，被自动补位换下的话，延长了专3完成时间。自动补位能否加个直接跳过艾丽妮，或者是补位时识别到在训练室B305而跳过协助位干员？

**Comment by ABA2396** [comment]
设置里有 不将已进驻的干员放入宿舍
