### ISSUE TITLE
OcrPack滚动识别到主线第六篇的时候识别为“FPISODE 06”导致无法匹配tasks.json条目（美服）

### ISSUE THREAD

**Issue by pein0saga** [MaaAssistantArknights/MaaAssistantArknights#4216]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

一直想自动代理刷理智美服的1-7这个重要关卡，但是不成功，必须手动滚动然后用“当下关卡“来执行（所以没法自动运行消耗”剩余理智“）

首先怀疑是 ROI 范围的问题导致无法前进到1-7，卡在主线第六篇，asst.log中显示错误的字段“FPISODE 06”

似乎YoStarEN\resource\template里面也不需要补充什么涉及相关文字的图片（EnterEpisode0/4/9.png都是不涉及文字的）
如果要调整ROI 范围的话在关联字段上不知道从何下手，因为要滚动好多区域才能到1-7。

而且对于tasks.json已有内容大多数都是对应的名词翻译，不会编程看到复用派生继承虚函数无从下手
（明明安利的时候说可以不会编程，只要opencv）

如果不是bug，希望外服的实用关卡1-7能够官方直接匹配好。

```
[TRC][Px130][Tx6fbc] OcrPack::recognize | raw: [{ ct: [ 116, 2, 51, 25 ], score: 0.898722 }, { Shatter of A Vision: [ 188, 6, 140, 19 ], score: 0.946644 }, { Partial Necrosis: [ 74, 62, 165, 25 ], score: 0.980346 }, { FPISODE 06: [ 235, 70, 80, 23 ], score: 0.934058 }]
[2023-04-07 21:48:42.920][TRC][Px130][Tx6fbc] OcrPack::recognize | proc: []
[2023-04-07 21:48:42.920][TRC][Px130][Tx6fbc] OcrPack::recognize | roi: [ 16, 219, 409, 151 ]
[2023-04-07 21:48:42.920][TRC][Px130][Tx6fbc] Ocr Pipeline with asst::CharOcr | enter
[2023-04-07 21:48:42.993][TRC][Px130][Tx6fbc] Ocr Pipeline with asst::CharOcr | leave, 72 ms
```

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11179805/asst.log)

### 截图

![Screenshot_2023 04 07_22 23 17 567](https://user-images.githubusercontent.com/2074641/230632968-cdaa38d2-ef6c-403f-b247-21257bb0d108.png)

**Comment by ABA2396** [comment]
看这个提交就知道了）

**Comment by ABA2396** [comment]
目标是匹配"EPISODExx"，可能是美服这个字体比较细，E识别成F了，只要在"ocrReplace"（文字替换）中把错误的文本改回来就行
