### ISSUE TITLE
建议在更新后保持对于基建的设置

### ISSUE THREAD

**Issue by chesha1** [MaaAssistantArknights/MaaAssistantArknights#4217]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

MAA更新后，基建设置还原为默认状态，建议有一个什么配置文件，每次关闭（更新）后从中读取上次的设置

**Comment by MistEO** [comment]
不会还原的，是 bug，发下 gui.log 日志

**Comment by chesha1** [comment]
> 不会还原的，是 bug，发下 gui.log 日志

gui.log的链接：https://virworks-my.sharepoint.com/:u:/g/personal/chesha1_virworks_onmicrosoft_com/EVxwyNW4AP9BmOt6z_YiK44BPXEPBH84-7AVrxpf97wKUg?e=9kVhj7  
MAA的具体更新时间我忘记了，为了方便你在日志中定位相关内容，应该发生在 4/7 18:00:00 到 4/8 03:00:00 之间

**Comment by MistEO** [comment]
这次是因为界面设置重构了，后面应该不会有这种问题了

**Comment by chesha1** [comment]
感谢解答
