### ISSUE TITLE
有游戏内更新时StartUp任务失败

### ISSUE THREAD

**Issue by Cryolitia** [MaaAssistantArknights/MaaAssistantArknights#4218]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在没有运行明日方舟的情况下启动StartUP任务，明日方舟自动打开，明日方舟检测到更新后自动下载，明日方舟更新下载完毕前，过一段时间后MAA提示StartUP任务失败

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11180159/asst.log)

04-08 00:28:31 任务出错

**Comment by zzyyyl** [comment]
自己动手丰衣足食.jpg

我记得还看到了好几个一样的 issue

**Comment by status102** [comment]
- resolved #10680
