### ISSUE TITLE
肉鸽选择干员的时候会自动选择预备干员

### ISSUE THREAD

**Issue by TakanashiShiro** [MaaAssistantArknights/MaaAssistantArknights#4227]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动肉鸽时选择干员时，在满希望的情况下仍然会选择预备干员，导致肉鸽连第一关都打不过去

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11182452/asst.log)

### 截图

![Screenshot_2023 04 08_11 43 42 401](https://user-images.githubusercontent.com/121703351/230701721-fe426b8a-4611-4b97-8336-6b63665bf0d7.png)
![QQ截图20230408114220](https://user-images.githubusercontent.com/121703351/230701724-ef896663-2ae8-40ea-9573-4748f702381c.jpg)

**Comment by Mzcczycle** [comment]
after the nearly upgrade, the problem happened
