### ISSUE TITLE
1、我也出现了开局如果不指定干员情况下，都是预备干员，而且希望没被使用的，更新前是没有出现过问题的；

### ISSUE THREAD

**Issue by dajdn** [MaaAssistantArknights/MaaAssistantArknights#4228]
1、我也出现了开局如果不指定干员情况下，都是预备干员，而且希望没被使用的，更新前是没有出现过问题的；
2、刚才又测试了一下，发现通过一个关卡后，给的任意一个招募券，在希望充足的情况下，依旧选择放弃招募干员，这个也需要解决；

_Originally posted by @xiaoshubin-os in https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/4223#issuecomment-1500752585_

**Comment by uesakayou** [comment]
+1，之前反馈了第一点，刚刚发现第二点也有

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/4241

**Comment by FusionJack1** [comment]
我也是，好像是debug文件夹里的肉鸽图片识别出问题了？？初始干员那里的先锋是no info

**Comment by MistEO** [comment]
内测版修了，试试看
