### ISSUE TITLE
日常无法挂机经验本第五关

### ISSUE THREAD

**Issue by Black1312** [MaaAssistantArknights/MaaAssistantArknights#4229]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

狗粮本没有打第六关，日常无法挂机第五关，会自动进入第六关

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11182640/asst.log)

### 截图

![A) SQF3TWDD0 %4Q1VJ04J7_tmb](https://user-images.githubusercontent.com/64343218/230706012-fd00a183-0e92-40e6-b12b-ad07a3377f90.png)

**Comment by ABA2396** [comment]
为啥会没匹配上 UnableToAgent ，点一下 LS-6 看看
![image](https://user-images.githubusercontent.com/99072975/230706273-f8ffc0e5-6d0b-406b-bb07-b507ed9b7512.png)

**Comment by ChildeRolando** [comment]
相同的问题，似乎是最近更新后出现本问题

**Comment by Black1312** [comment]
> 相同的问题，似乎是最近更新后出现本问题

ls6的首次通关原石有没有拿到？

**Comment by ChildeRolando** [comment]
> > 相同的问题，似乎是最近更新后出现本问题
> 
> ls6的首次通关原石有没有拿到？

没有

**Comment by Black1312** [comment]
> > ls6的首次通关原石有没有拿到？
> 没有

@ABA2396

**Comment by Black1312** [comment]
麻烦关卡选择ls-6后截图发上来，示例参考附图
![Uploading Screenshot_2023-04-08-20-04-47-322_com.hypergryph.arknights.jpg…]()

**Comment by Black1312** [comment]
> 相同的问题，似乎是最近更新后出现本问题

麻烦关卡选择ls-6后截图发上来

**Comment by Black1312** [comment]
> 相同的问题，似乎是最近更新后出现本问题

麻烦游戏内关卡选择ls-6后截图发上来，谢谢，示例如图

**Comment by ChildeRolando** [comment]
> > 相同的问题，似乎是最近更新后出现本问题
> 
> 麻烦游戏内关卡选择ls-6后截图发上来，谢谢，示例如图
![Screenshot_20230408-142150](https://user-images.githubusercontent.com/43607124/230720794-0e63fcc8-51b0-47d8-bf9a-54cf64c97546.png)
实测钱本也有这个问题

**Comment by ABA2396** [comment]
dev已经改过了，现在只识别石头，应该是可以了

**Comment by MistEO** [comment]
草，活动一开挤到后面去了（

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/374756e126ed6f0d8a15cb09062f13d73acd50d7 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/c7cc7f84539943610f3dd39ceed5247bb54f9985 fixed

**Comment by MistEO** [comment]
@ABA2396 下次修了标个 commit ，或者 fixed，好多 issue 修了都没关_(:з」∠)_

**Comment by ABA2396** [comment]
> @ABA2396 下次修了标个 commit ，或者 fixed，好多 issue 修了都没关_(:з」∠)_

这个是修完之后发的）
