### ISSUE TITLE
水月肉鸽异常失败

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#4230]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

水月肉鸽多次出现异常失败，甚至第一场战斗就失败，按照以往的经验应该至少打到第三层。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11182759/asst.zip)

### 截图

![屏幕截图 2023-04-08 153726](https://user-images.githubusercontent.com/92417243/230709816-c3d3b6e8-b5a8-4c8d-8200-31954a6ef108.png)

**Comment by SamZhou-2019** [comment]
我的也是这样，第一关就结束了。复现一次发现MAA选了马恩纳（这种应该是后期采用的），波登可（一级）和医疗预备干员。第一关直接放怪入蓝门😂4.12.0-beta3版本选的是海沫（精一70），梓兰（精一55）和蜜梅（精一60），甚至可以打到第五层。
![image](https://user-images.githubusercontent.com/53434814/230713748-0071e9f3-ff84-40a9-b87b-eefa81a48aeb.png)
![image](https://user-images.githubusercontent.com/53434814/230713766-e6ca96a4-b696-49c2-9f40-077c11e84ed8.png)
模拟器是联想模拟器（MAA识别为逍遥模拟器，但是这个问题跟模拟器应该没有关系）
