### ISSUE TITLE
关卡导航支持的关卡，缺少文档

### ISSUE THREAD

**Issue by Mr-oy** [MaaAssistantArknights/MaaAssistantArknights#4234]
### 说说你遇到的问题？

maa的文档里没有提及关卡名也没有包含关卡名列表
我这部想用python api 实现每周剿灭,请问剿灭作战的关卡名(stage)是多少

**Comment by ABA2396** [comment]
Annihilation

**Comment by Mr-oy** [comment]
请问,怎么去查这个关卡名呢,集成文档里说参照C#的,但是C#里却没有

**Comment by ABA2396** [comment]
我也不知道这个文档里说的 c#集成 是啥
具体是在 [StageManager.cs](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/src/MaaWpfGui/Services/StageManager.cs#L271)
除此之外还有 [api](https://ota.maa.plus/MaaAssistantArknights/api/gui/StageActivity.json) 中提到的活动关卡名，和主线大部分关卡（应该是都支持的，只是没测过）
主线的处理是在[StageNavigationTask.cpp](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/src/MaaCore/Task/Fight/StageNavigationTask.cpp)

**Comment by MistEO** [comment]
文档缺失.jpg

**Comment by Mr-oy** [comment]
大佬缺人写文档吗，我可以帮忙写文档（但是会的不多）-------- 原始邮件 --------发件人： MistEO ***@***.***>日期： 2023年4月9日周日 16:51收件人： MaaAssistantArknights/MaaAssistantArknights ***@***.***>抄送： ouyang ***@***.***>, Author ***@***.***>主    题： Re: [MaaAssistantArknights/MaaAssistantArknights] 剿灭作战 关卡名 (Issue #4234)
文档缺失.jpg

**Comment by ABA2396** [comment]
缺啊，但更缺的是翻译罢）

**Comment by ABA2396** [comment]
~我们需要一个好的翻译~我们需要一个会熟练使用ChatGPT的技术文档撰写者.jpg

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/maa-website/commit/b80edc637bc6d4559b5a6c8741b6c758f1a9639d 加了支持导航的关卡
