### ISSUE TITLE
应该添加一个启动模拟器按钮在主界面。

### ISSUE THREAD

**Issue by ReFranxx** [MaaAssistantArknights/MaaAssistantArknights#4235]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

应该添加一个启动模拟器按钮在主界面。

### 有什么好的想法？

应该添加一个启动模拟器按钮在主界面。

### 其他内容

应该添加一个启动模拟器按钮在主界面。

**Comment by Black1312** [comment]
模拟器没有启动时，点击maa的开始后，会尝试链接并启动模拟器，但必须在连接设置中勾选adb连接失败启动模拟器和启动设置中正确选择模拟器的启动程序
