### ISSUE TITLE
视频转json闪退

### ISSUE THREAD

**Issue by HMZyueshen** [MaaAssistantArknights/MaaAssistantArknights#4236]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

视频转json闪退
![S{$G T482Y86({X JLVY`LY](https://user-images.githubusercontent.com/106477016/230717822-4dcec144-73ef-42c5-a427-d6cbd8b30c07.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11183052/asst.log)

**Comment by MistEO** [comment]
哪个视频，发下链接

**Comment by HMZyueshen** [comment]
我自己录的

**Comment by HMZyueshen** [comment]
都会闪退
