### ISSUE TITLE
任务完成后自动关闭maa出错

### ISSUE THREAD

**Issue by RobustWYX** [MaaAssistantArknights/MaaAssistantArknights#4237]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

   在 System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.KillEmulatorXYAZ()
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.KillEmulatorModeSwitcher()
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.CheckAfterCompleted()
   在 MaaWpfGui.Main.AsstProxy.ProcTaskChainMsg(AsstMsg msg, JObject details)
   在 MaaWpfGui.Main.AsstProxy.ProcMsg(AsstMsg msg, JObject details)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11183215/asst.log)

**Comment by ABA2396** [comment]
在关模拟器的时候出问题了，试试看管理员权限启动

**Comment by RobustWYX** [comment]
好的谢谢
&nbsp;


2367679611
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月8日(星期六) 晚上10:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 任务完成后自动关闭maa出错 (Issue #4237)





 
在关模拟器的时候出问题了，试试看管理员权限启动

**Comment by MistEO** [comment]
模拟器用管理员启动的，MAA 没管理员，关不掉
