### ISSUE TITLE
能不能新增商店自动掷骰子刷指定藏品?

### ISSUE THREAD

**Issue by 520firewire520** [MaaAssistantArknights/MaaAssistantArknights#4238]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我现在是用maa骰子队开挂机到商店后，取消挂机并自己掷骰子，看有没有指路鳞，沒有就重新挂机并重复步骤

### 有什么好的想法？

希望可以新增自动掷骰子加搜索想要的藏品，如果没有就重复源石锭投资，达成无人工的自动回圈

### 其他内容

無

**Comment by TangZH-unity3d** [comment]
[（优先用MAA）水月肉鸽脚本-羽毛笔或海沫刷藏品和事件（自动精灵app）v1.1.5.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11196241/MAA.-.app.v1.1.5.zip)

这是之前根据群里大佬的自动精灵改写的针对某藏品（指路鳞）和事件（愚人之志刷教堂拼图）写的自动精灵脚本，挂了两个星期刷到了，也可以修改词条刷别的，还有疑惑可以加我问 931121041
