### ISSUE TITLE
界面配置可能会重置

### ISSUE THREAD

**Issue by starrin** [MaaAssistantArknights/MaaAssistantArknights#424]
偶然发现界面配置可能会在应用关闭并重新打开后所有配置项重置为初始状态，包括自定义adb连接、任务执行顺序、企鹅物流上报ID等全部回到初始状态
打开gui.json之后发现所有内容都回到了初始状态，怀疑是recruit.json和stages.json更新导致的其他配置项被一并覆盖
能否把这两个配置项独立出来放到别的文件里保证别的配置项不被经常覆盖掉呢？其实别的重新配置一遍也不难，就是企鹅物流ID这个每次重写就很烦了

**Comment by MistEO** [comment]
gui.json 是不随版本更新的，可能是 bug

**Comment by starrin** [comment]
原来如此，那还请定位一下，这个我最近隔三岔五就会遇到一次，已经有点遭不住了
log里完全看不出毛病

**Comment by zzyyyl** [comment]
看看是不是 #429 提到的问题（？

**Comment by starrin** [comment]
哦对，就是自动关机后特别容易出现
但不是一定出现

**Comment by ABA2396** [comment]
Duplicate of #264
