### ISSUE TITLE
在肉鸽中闪退

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [MaaAssistantArknights/MaaAssistantArknights#4240]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在<code>WSA</code>模拟器中运行游戏挂肉鸽时会出现MAA闪退现象，MAA的版本是今日<code>（23.04.08）</code>的最新开发版，WSA的版本是<code>2302.40000.9.0</code>，之前也曾出现过MAA的闪退现象，但是不在战斗中。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11183556/asst.log)
闪退出现时间点大约：23.04.08 22:50~23:00，出现记录断层的时间点为22:55

### 截图

[debug_roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11183562/debug_roguelike.zip)
内含一张今日<code>（23.04.08）</code>的MAA截图。

### 还有别的吗？

模拟器：WSA（版本号见描述）
操作系统：win11 22h2
配置：MAA主页的（仅）自动肉鸽，水月，刷等级，配置基本保持默认

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/4248

应该是一样的问题，刚修了，更新一下试试（内测版）

**Comment by lingfengyu-dreaming** [comment]
已更新，目前挂肉鸽中，无闪退，issue应该可关
