### ISSUE TITLE
v4.13.0下连接设置中的开始前脚本和结束后脚本应如何使用？

### ISSUE THREAD

**Issue by inCloudRain** [MaaAssistantArknights/MaaAssistantArknights#4247]
### 说说你遇到的问题？

我想用bark实现完成后通知，但尝试填写bat脚本位置和curl命令本身都没有用。
命令已测试正常工作。

**Comment by inCloudRain** [comment]
另外建议新增功能能写个简单的文档或者描述详细一点，不然有的真不会用啊。

**Comment by MistEO** [comment]
只支持可执行文件路径，bat 和 exe 应该都可以

**Comment by 050644zf** [comment]
> 只支持可执行文件路径，bat 和 exe 应该都可以
我觉得应该改个名字叫开始前/结束后脚本路径，我打了个命令发现用不了才过来这里找issue

**Comment by moomiji** [comment]
脚本使用了相对地址的，请填写脚本的快捷方式
