### ISSUE TITLE
自动战斗部署干员时闪退

### ISSUE THREAD

**Issue by zzXan** [MaaAssistantArknights/MaaAssistantArknights#4248]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

地图：9-4
作业：maa://21978
到部署银灰那步就直接就闪退了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11184980/asst.log)

### 截图

![QQ录屏20230409172714 00_00_00-00_00_30](https://user-images.githubusercontent.com/99358986/230760475-96a42aa9-460a-4103-ac39-c70cb4bba3b7.gif)

**Comment by MistEO** [comment]
内测版？刚修了，试一下新的还有没有问题了

**Comment by zzXan** [comment]
已测试，没闪退了
