### ISSUE TITLE
基建排班多余了“选择技能，选择工作状态”两步

### ISSUE THREAD

**Issue by lzckira** [MaaAssistantArknights/MaaAssistantArknights#4249]
### 说说你遇到的问题？

制造厂里的步骤在最后已经选完人有个多余的动作，麻烦看一下，如果是为了稳定性什么的请无视

**Comment by MistEO** [comment]
麻烦问题描述清楚一点

**Comment by lzckira** [comment]
我理解每个子场景需要做的逻辑是
打开子场景，进入选择干员列表，清除选择，向右拉扫描拥有当前子场景技能的干员列表，选择干员，确认结束
然而目前的逻辑是
打开子场景，进入选择干员列表，清除选择，向右拉扫描拥有当前子场景技能的干员列表，选择干员，选择技能，选择工作状态，确认结束
结束前多了“选择技能，选择工作状态”两步  每个子场景大概会多2秒钟  全部子场景加起来就浪费挺多时间的了

**Comment by ABA2396** [comment]
有些组合是要按顺序入驻的，这样是为了保证入驻顺序避免重新暖机
