### ISSUE TITLE
基建宿舍换班时如果人数未满选择加速回心情的干员进宿舍

### ISSUE THREAD

**Issue by ABA2396** [MaaAssistantArknights/MaaAssistantArknights#425]
可以和其他设施的方式一样，先扫一遍有多少心情未满要进宿舍的，平均分配一下宿舍，如果还有空位的话就塞几个会心情的干员

**Comment by MistEO** [comment]
不好弄，~~有时候会把在控制中枢永动的阿米娅扔进宿舍~~

**Comment by ABA2396** [comment]
~~那就把阿米娅踢出休息名单.jpg~~

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/166500814-36af0f21-84f2-409e-8e4f-90f893c3bf40.png)
![image](https://user-images.githubusercontent.com/99072975/166500830-31126a6f-4213-4e62-940f-b47b49de67c4.png)
![image](https://user-images.githubusercontent.com/99072975/166500864-7187687e-732f-45ad-be93-5f60b3ae4c86.png)
现在好像除了本宿舍的休息中的人都在最后了，不会影响阿米娅上班）

**Comment by MistEO** [comment]
会的，比如我这里举例子的 临光，你截图中不会是因为他们体力都没满

![image](https://user-images.githubusercontent.com/18511905/166508251-7d34185f-d513-4385-9a86-722d534a7466.png)

![image](https://user-images.githubusercontent.com/18511905/166508339-81e5b46b-2123-48a6-b5ed-ebdcf892e498.png)

**Comment by ABA2396** [comment]
~~那就塞指定干员(bushi)~~这个简单，点右上角更多，选未进驻

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/166511947-feb0909b-ceec-4668-b123-3c1a26448eaf.png)
比如我这里最后一个是凯尔希，那我选上之后按右上角
![image](https://user-images.githubusercontent.com/99072975/166512017-15a5a5fa-5dfa-43bd-9106-cc6a280c35d3.png)
选未进驻
![image](https://user-images.githubusercontent.com/99072975/166512089-5fb7f714-2687-4be6-9900-e65b613bd528.png)
这里面就不会有在中枢的了
![image](https://user-images.githubusercontent.com/99072975/166512247-09658e6a-5e50-40b5-9d1d-b5f5ab27d572.png)
