### ISSUE TITLE
水月肉鸽紧急运输节点无法正确响应

### ISSUE THREAD

**Issue by feena-fel** [MaaAssistantArknights/MaaAssistantArknights#4252]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

水月肉鸽紧急运输节点，进入【未选择任何干员，确认离开吗？】界面后，无法正常响应，停留在该界面。

看日志应该是在 L44581 进入了紧急运输（`StageEmergencyTransportation`），然后识别就乱掉了，在节点退出确认界面上 L44657 一直识别成 `StageEncounterOptionUnknown`，然后卡在这里。

### 日志文件

大概出问题位置：L44657
关键字：`match_templ | Mizuki@Roguelike@StageEncounterOptionUnknown.png score: 0.910524`

[log.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11185450/log.txt)

### 截图

没有截图，不过和 #2191 中的界面一致。

### 还有别的吗？

- AVD：`system-images;android-33;google_apis;arm64-v8a:9`
- 横屏 1920x1080
- Apple M1 Ventura 13.3.1 (22E261)

**Comment by MistEO** [comment]
时间和线程号留一下吧，这增加看日志的难度啊

**Comment by feena-fel** [comment]
> 时间和线程号留一下吧，这增加看日志的难度啊

log 已经切掉了，看上去是全程单线程。而且这个界面手动点【黑色叉】取消的话，MAA 会立即再把这个界面点出来。

这个 case 如果觉得看着困难就算了，看能不能接着挂一个复现。出事的那段时间可能涉及其它交互，不好说有没有干扰到 avd 屏幕。

要是复现了再开回来。

**Comment by feena-fel** [comment]
Reproduced. 

[asst.log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11187051/asst.log.zip)

**Comment by feena-fel** [comment]
@MistEO 更新到 v4.14.1（308）后问题疑似已经解决，希望确认
