### ISSUE TITLE
建议加入多设备连接配置切换功能

### ISSUE THREAD

**Issue by FSPaul2498** [MaaAssistantArknights/MaaAssistantArknights#4255]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

因为近期开启理智小样掉落活动，我有多个设备多个账号需要使用MAA进行挂机刷取，每次切换模拟器或者实体机的时候，都需要修改连接配置，比较麻烦。
是的，我知道我可以拷贝多个MAA副本，使用不同的配置分别执行，但这样会占用更多的硬盘空间，并且除了连接配置以外，其他的配置项都是相同的，每次升级MAA需要重新进行配置多个MAA副本，也会比较麻烦，所以希望能够加入如题所说的功能。

### 有什么好的想法？

希望能够加入多设备连接配置切换功能，在MAA主页可以直接选择某个设备的连接配置，连接到指定的设备，例如：

选择设备：（展开下拉列表）
默认配置：自动检测
蓝叠A机：localhost:5555
蓝叠B机：localhost:5565
我的手机：adb a1b2c3d4
添加新连接配置……

如果这个功能的大众使用频率不高的话，也可以默认关闭，在设置里手动开启此设置项的显示（就像使用备选关卡功能那样）

**Comment by ABA2396** [comment]
新ui好像是支持多开的吧，看看 [MaaAsstElectronUI](https://github.com/MaaAssistantArknights/MaaAsstElectronUI)
