### ISSUE TITLE
执行完所有任务后闲置一段时间就会出现未知错误

### ISSUE THREAD

**Issue by MeguminKato** [MaaAssistantArknights/MaaAssistantArknights#4258]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

执行完所有任务后闲置一段时间就会出现未知错误

未将对象引用设置到对象的实例

 在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<>c__DisplayClass339_0.<ManualUpdate>b__0()
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ManualUpdate>d__339.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11185616/asst.log)
[gui-20230409.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11185617/gui-20230409.log)

### 截图

![image](https://user-images.githubusercontent.com/2605195/230777369-9d947953-b03b-4738-86d0-572e8c11cee6.png)

### 还有别的吗？

蓝叠5.9国际版，maa 4.1.13 beta1.44.gcd38cec8

**Comment by ABA2396** [comment]
我记得新版本好像已经解决了？这已经是两个星期前的内测版了吧
