### ISSUE TITLE
升级会导致卡在升级界面

### ISSUE THREAD

**Issue by wuxinHome** [MaaAssistantArknights/MaaAssistantArknights#426]
刷本如果升级了，这时候就会卡在升级界面不动，因为我是晚上挂着然后选了自动关机，结果早上来看，软件已经闪退，模拟器上显示着升级画面。
模拟器是雷电4，分辨率是1280*720，忘记截图了，因为升级卡过好多次了，可能是雷电的问题吧。
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8617431/asst.log)

**Comment by zzyyyl** [comment]
以前讨论过 #330 ，并且修了https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/0c50e00f65e8fd7dd9d12e4ac64438ee49fe61e6 ，大概是方舟新ui又寄了（
可以的话传个升级界面的截图？~~（满级博士没有的烦恼）~~

**Comment by wuxinHome** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月4日(星期三) 中午1:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 升级会导致卡在升级界面 (Issue #426)





 
以前讨论过 #330 ，并且修了0c50e00 ，大概是方舟新ui又寄了（
 可以的话传个升级界面的截图？（满级博士没有的烦恼）

**Comment by MistEO** [comment]
> 以前讨论过 #330 ，并且修了[0c50e00](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/0c50e00f65e8fd7dd9d12e4ac64438ee49fe61e6) ，大概是方舟新ui又寄了（ 可以的话传个升级界面的截图？~（满级博士没有的烦恼）~ 这次好像更严重？上次是企鹅汇报寄了，这次闪退（

修了，但是新版本我又改回去了（

等我再修修_(:з」∠)_
