### ISSUE TITLE
老咸鱼搓玉爆仓调整

### ISSUE THREAD

**Issue by tianhe31** [MaaAssistantArknights/MaaAssistantArknights#4261]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

连井两个人元气大伤，搓搓玉，算了一下，默认容量的三级基建搓玉一般是八小时爆仓，十二点打完睡了一觉就爆了，已经是很短的时间了，一天登录两次的早七晚八必爆，maa默认的最高效率组反而因为爆仓停止工作而成品减少。

### 有什么好的想法？

加一个按钮区分一天上线两次的咸鱼和勤奋的玩家，调整不同的基建干员优先级，例如制造站火神泡泡褐果，贸易站银崖孑，增大仓库储量，使爆仓时间延长。

**Comment by ABA2396** [comment]
不是有自定义基建吗.jpg

**Comment by tianhe31** [comment]
> 

确实是这样啦，所以只是提一下
