### ISSUE TITLE
内置基建333策略一图流id与json内容不符

### ISSUE THREAD

**Issue by MisakaNA** [MaaAssistantArknights/MaaAssistantArknights#4264]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

根据resource/custom_infrast内333_layout_for_Orundum_3_times_a_day.json的代码末尾：
"author": "面包猫南北",
    "description": "长期搓玉333排班协议",
    "id": 1664692636351064,
    "title": "333长期搓玉，具体干员配置参考公孙长乐大佬，使用换班时间为6-6-12组，要求有菲亚\n若缺少干员请自行拷贝文件并修改（请勿直接修改，以免更新后被覆盖）",
    "buildingType": "333"

而将此id输入到https://yituliu.site/riicCal/得到的是如截图所示

### 日志文件

N/A

### 截图

![image](https://user-images.githubusercontent.com/51569785/230830239-6779b1e5-beed-4c63-81da-309be12a3be9.png)

**Comment by MistEO** [comment]
@nightofknife

**Comment by 1551599784** [comment]
内置的333能用吗？稳不稳定？
