### ISSUE TITLE
无法连接mumu模拟器

### ISSUE THREAD

**Issue by MoRIOGASAWARA** [MaaAssistantArknights/MaaAssistantArknights#4269]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

无法连接模拟器，在勾选自动检测连接的情况下一直处于正在连接模拟器的状态不动，在取消勾选吗自动检测连接时则会显示连接失败，无论是模拟器重启还是电脑重启都没有用，包括重新下载MAA也依然出现这种情况

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11189968/asst.log)
大致在下午五六点左右

### 截图

![屏幕截图(5)](https://user-images.githubusercontent.com/130361597/230887783-40641903-9eca-4ab2-9aaf-81c4c0c2cc90.png)

**Comment by YoYueze** [comment]
手动选择adb应该就好了

**Comment by Superexboom** [comment]
确认不是无adb支持的mumu版本的话，手动去设置里选择adb，开uu加速会导致自动检测的adb找不着地，手动指向就行

**Comment by Black1312** [comment]
问题如未解决，请加群912322156私聊筱竹聽雨说明情况
