### ISSUE TITLE
希望手机顶号之后maa不要再自动重新登陆

### ISSUE THREAD

**Issue by YoYueze** [MaaAssistantArknights/MaaAssistantArknights#4270]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

如题，希望手机顶号之后maa不要再自动重新登陆，或者增加一个开关，可以自己设置被顶号之后是否自动重新登陆.有的时候出门挂上maa之后因为一些原因回来的晚的话，手机上玩会方舟会来回被顶号

**Comment by horror-proton** [comment]
duplicate of #4231
