### ISSUE TITLE
水月肉鸽部分地图不下人

### ISSUE THREAD

**Issue by Superexboom** [MaaAssistantArknights/MaaAssistantArknights#4276]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我在刚开水月肉鸽的时期也提过类似的issues，这回就是在多个地图上都出现了不下人的情况；在昨晚的内测版本中未被我观测到相关情况，在今天更新的beta版中出现了多次不下人。
卡下人的log节点在最末段（也就是最后一次肉鸽的失败），gui的log输出我也一并打包了，在倒数第二轮肉鸽失败结算前（4-11 10:15-10:18）也出现了不下人导致失败；中段也有不下人的情况但是不好定位就算了。
看了下肉鸽的截图并没有相关的输出，只能提供下当时没下人时候的debug里的map，刚好是倒数第二趟肉鸽失败前的图

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11195950/debug.zip)

### 截图

![好梦在何方](https://user-images.githubusercontent.com/54000348/231046461-926a6e03-46ed-4450-8114-47d64b3e8063.png)

### 还有别的吗？

夜神模拟器 7.0.5.5
MAA 4.14.0-beta.1

**Comment by MistEO** [comment]
```log
[2023-04-11 10:17:37.522][INF][Px3390][Tx4538] Call ` D:\Nox9\Nox\bin\.\nox_adb.exe -s 127.0.0.1:62025 exec-out "screencap | gzip -1" ` ret 0 , cost 102 ms , stdout size: 25179 , socket size: 0
[2023-04-11 10:17:37.522][WRN][Px3390][Tx4538] data is too small!
```

夜神动不动就会返回一张完全不对的图，影响 MAA 的识别和后续逻辑，重启试试，不行建议换个模拟器

**Comment by Superexboom** [comment]
> ```
> [2023-04-11 10:17:37.522][INF][Px3390][Tx4538] Call ` D:\Nox9\Nox\bin\.\nox_adb.exe -s 127.0.0.1:62025 exec-out "screencap | gzip -1" ` ret 0 , cost 102 ms , stdout size: 25179 , socket size: 0
> [2023-04-11 10:17:37.522][WRN][Px3390][Tx4538] data is too small!
> ```
> 
> 夜神动不动就会返回一张完全不对的图，影响 MAA 的识别和后续逻辑，重启试试，不行建议换个模拟器

这也太奇怪了，只能试试重启能不能好点吧，其他模拟器我这有点古怪，跑方舟时常崩，只有夜神还可以，感谢回复

**Comment by Superexboom** [comment]
草 手欠点错了
