### ISSUE TITLE
MAA无法识别没有代理的关卡

### ISSUE THREAD

**Issue by EricWangxy** [MaaAssistantArknights/MaaAssistantArknights#4278]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

当关卡选择经验-6/5时，MAA无法识别到LS-6没有代理，并且会进入作战。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11196370/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11196371/asst.log)
2023-04-10 23:08:55.195开始的作战

### 还有别的吗？

蓝叠国际版，win11

**Comment by ABA2396** [comment]
是拿了首通源石但是没代理吗

**Comment by EricWangxy** [comment]
在关卡没有解锁代理的情况下，maa会识别不到关卡没有解锁代理。我不知道是只有资源本这样还是其他都是这样。

**Comment by ABA2396** [comment]
只有龙门币和记录做了6打不了打5，其他都没做判断。然而这次是没识别到不可代理的标志（首通源石），之前用源石不用🔒就是因为识别有问题。这次加长了点等待时间和两个标志都识别一次，不知道有没有用
