### ISSUE TITLE
信用商店 想剔除掉加急许可

### ISSUE THREAD

**Issue by pearhield** [MaaAssistantArknights/MaaAssistantArknights#428]
感觉加急许可比家具还没没用
或者可以自定义各类商品的购买优先级吗

**Comment by zzyyyl** [comment]
参考[这个链接](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md#%E4%BF%A1%E7%94%A8%E5%95%86%E5%BA%97%E9%9A%8F%E7%BC%98%E4%B9%B0)

**Comment by pearhield** [comment]
> 参考[这个链接](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md#%E4%BF%A1%E7%94%A8%E5%95%86%E5%BA%97%E9%9A%8F%E7%BC%98%E4%B9%B0)

好耶！之前没看到
