### ISSUE TITLE
请在文档中说明手动输入关卡名模式下的特殊命名规则

### ISSUE THREAD

**Issue by TobyLi223** [MaaAssistantArknights/MaaAssistantArknights#4282]
### 说说你遇到的问题？

我只打了突袭/磨难关卡，在手动输入关卡名模式下不知道输入什么才会让MAA选择突袭模式，如果没有这种功能，请做出补全，谢谢

**Comment by MistEO** [comment]
鼠标 hover 上去就有提示

![image](https://user-images.githubusercontent.com/18511905/231174363-65e92fd0-668b-43e3-bf57-aa1309b484d8.png)

**Comment by MistEO** [comment]
但是为什么要打突袭（

**Comment by TobyLi223** [comment]
众所周知在第九章之后迎来突袭改版为磨难，磨难只需要研究一次关卡就可以收获两份源石，不用多打一次，也可以用来代理刷材料，但这时普通关卡是代理不了的，然而MAA似乎不支持在主线中切换难度选择，鹰角设计每一次进入的时候都会进入普通模式

MistEO ***@***.***> 于2023年4月11日周二 21:16写道：

**Comment by TobyLi223** [comment]
是每一次登录首次进入关卡选择页时

Toby LI ***@***.***> 于2023年4月11日周二 21:35写道：

**Comment by TobyLi223** [comment]
谢谢 从 Windows 版邮件发送 发件人: MistEO发送时间: 2023年4月11日 23:01收件人: MaaAssistantArknights/MaaAssistantArknights抄送: TobyLi223; Author主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 请在文档中说明手动输入关卡名模式下的特殊命名规则 (Issue #4282) 鼠标 hover 上去就有提示—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
