### ISSUE TITLE
在debug.txt存在时每一次的maa截图都保存到debug中的screencap文件夹里

### ISSUE THREAD

**Issue by qaz1qazlol2** [MaaAssistantArknights/MaaAssistantArknights#4284]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

如题，更好测试哪里出了问题

**Comment by MistEO** [comment]
确实可以，但这个截图爆炸多（比如战斗的时候 1 秒大概 5 张，每张 1M 左右），或许可以单独做一个文件而不是 debug.txt

**Comment by qaz1qazlol2** [comment]
也行，也可以整一个压缩包来存储每一次运行的截图文件，更好分类

**Comment by qaz1qazlol2** [comment]
行的话也可以把ocr识别结果用红色或者绿色代表成功状态来标记后在输出，更好定位是哪里的问题

**Comment by MistEO** [comment]
其实你想定位的话直接用 debug 模式本地调试就好了，所有的识别结果都是画出来的
