### ISSUE TITLE
日服关卡导航问题：无法导航到4-2

### ISSUE THREAD

**Issue by AkiraChisaka** [MaaAssistantArknights/MaaAssistantArknights#4289]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用MAA玩日服，“刷理智”的导航似乎还是有不少问题。

目前我遇到的是，无法导航到4-2。

感觉可能是因为日文汉字对不上，或者是因为我没有开第六章。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11205108/asst.log)

### 截图

会卡在这个页面：
![Screenshot_2023 04 11_14 33 11 862](https://user-images.githubusercontent.com/47231500/231293092-7f1e05de-e652-4ef7-a2af-5cd00b23cd5c.png)

MAA：
![image](https://user-images.githubusercontent.com/47231500/231293130-0ce16ba4-d612-42cb-88d6-eb6db0498a68.png)

**Comment by ABA2396** [comment]
没有日服测试，跟着commit改下这两个文件看看好不好使

**Comment by AkiraChisaka** [comment]
> 没有日服测试，跟着commit改下这两个文件看看好不好使
@ABA2396 
了解了，我最近再试试，如果还有问题我写个新的Issue。
