### ISSUE TITLE
“MaaWpfGui.ViewModels.UI.SettingsViewModel”的类型初始值设定项引发异常。

### ISSUE THREAD

**Issue by LeYouJJ** [MaaAssistantArknights/MaaAssistantArknights#4292]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

debug文件夹里面没有asst.log文件，只看见了gui.log文件。是MAA在新电脑上第一次打开出现的未知错误，画面见截图。

错误
“MaaWpfGui.ViewModels.UI.SettingsViewModel”的类型初始值设定项引发异常。

详情信息
在 MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.Main.AsstProxy..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.ViewModels.UI.RootViewModel..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 Stylet.Bootstrapper`1.get_RootViewModel()
   在 Stylet.Bootstrapper`1.Launch()
   在 Stylet.BootstrapperBase.Start(String[] args)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11206175/gui.log)

### 截图

![image](https://user-images.githubusercontent.com/40951254/231322540-7a98d9e4-7ea3-4785-a886-955c34327718.png)

### 还有别的吗？

![image](https://user-images.githubusercontent.com/40951254/231322750-2fd26e50-5eb2-4c45-8f97-0910daf54d14.png)

**Comment by MistEO** [comment]
看看是不是 .net 的运行库没装

**Comment by LeYouJJ** [comment]
> 

是的，新电脑没安装运行库，解决了，谢谢
