### ISSUE TITLE
完全无法启动

### ISSUE THREAD

**Issue by drunkenQCat** [MaaAssistantArknights/MaaAssistantArknights#430]
我已经把软件路径放在没有特殊符号的地方（D:\MaaAssistant），但是无论是普通双击还是以管理员权限运行，都是一样的闪退。
![image](https://user-images.githubusercontent.com/39608175/166632498-f01ceef2-e8e1-4165-9a1d-617dfbb0f17d.png)

下面贴出我的系统信息：
![image](https://user-images.githubusercontent.com/39608175/166632703-f98af424-b0ff-4d38-8119-2b07b5093b99.png)
lk

另外我试着下载源码想要生成，一直会提醒有关.net 4.8的相关错误，但实际上我已经安装好了.net 4.8的sdk和runtime。
![image](https://user-images.githubusercontent.com/39608175/166632835-40fbec01-4546-4da7-a1dd-d9cffabd92ca.png)

**Comment by MistEO** [comment]
闪退的话参考 [常见问题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#%E8%BD%AF%E4%BB%B6%E4%B8%80%E6%89%93%E5%BC%80%E5%B0%B1%E9%97%AA%E9%80%80) 这个看看

**Comment by drunkenQCat** [comment]
> 闪退的话参考 [常见问题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#%E8%BD%AF%E4%BB%B6%E4%B8%80%E6%89%93%E5%BC%80%E5%B0%B1%E9%97%AA%E9%80%80) 这个看看

解决了！是Paddleocr 的问题。我的CPU垂垂老矣。
