### ISSUE TITLE
[Bug] 4.14.0更新后 UI Theme 跟随系统错误

### ISSUE THREAD

**Issue by OwlHowlinMornSky** [MaaAssistantArknights/MaaAssistantArknights#4303]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新之前跟随系统是正确跟随应用模式的
更新后跟随的是Windows模式

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11217574/asst.log)
4月13日首次启动即更新，更新后即出现问题

### 截图

![屏幕截图 2023-04-13 101407](https://user-images.githubusercontent.com/43873149/231631124-37f0ff3e-a0ef-4759-a685-c5764b10fadd.png)
![屏幕截图 2023-04-13 101415](https://user-images.githubusercontent.com/43873149/231631133-98be0900-7b62-4c25-8682-a0795975f717.png)
![屏幕截图 2023-04-13 101421](https://user-images.githubusercontent.com/43873149/231631135-f4d095e9-ff73-439d-84c7-a97380de948d.png)
![屏幕截图 2023-04-13 101447](https://user-images.githubusercontent.com/43873149/231631140-ab0376fa-1e9c-45e4-a538-38014ee694ac.png)

**Comment by ABA2396** [comment]
这个模式好像是win11从开始区分的，改了的话估计win10就不好做的

**Comment by ABA2396** [comment]
更新之前是对的吗？
cc @moomiji

**Comment by OwlHowlinMornSky** [comment]
> 这个模式好像是win11从开始区分的，改了的话估计win10就不好做的

错误的，Win10也这样
![屏幕截图 2023-04-13 104216](https://user-images.githubusercontent.com/43873149/231634520-268adf91-3a3e-4483-a09b-61ee768b23fa.png)
![屏幕截图 2023-04-13 104228](https://user-images.githubusercontent.com/43873149/231634537-dc5e19fc-d120-4352-964b-d5b8e6efca17.png)

**Comment by OwlHowlinMornSky** [comment]
> 更新之前是对的吗？ cc @moomiji

我在更新前就设置的跟随系统，所以4.14.0之前应该没这问题

**Comment by moomiji** [comment]
之前不知道win存在自定义选择模式，已修
