### ISSUE TITLE
基建中应当优先使用伊内丝替代20%效率线索

### ISSUE THREAD

**Issue by HeartyYF** [MaaAssistantArknights/MaaAssistantArknights#4304]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

应该是因为聚影缺乏一个对应的efficient，
```
"efficient": {
    "all": 21,
},
```
类似于这样应该就work？

### 日志文件

无

**Comment by MistEO** [comment]
伊内丝是啥技能来着，可以直接给我们提一个 PR ~

**Comment by ABA2396** [comment]
> 伊内丝是啥技能来着，可以直接给我们提一个 PR ~

20-30，每小时+2%，5小时追平25效率

**Comment by MistEO** [comment]
那可以按 29 算？之前其他的效率都是按 8 小时的
