### ISSUE TITLE
若没有兑换完信用商店干员，MAA会在卡进信用商店干员的精二阶段预览并无法退出

### ISSUE THREAD

**Issue by yingmiait** [MaaAssistantArknights/MaaAssistantArknights#4306]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Maa版本:v4.14.0

没有换完信用商店干员，Maa就直接点了这个（下图）
然后就又会点进详细简历，最后就退不出来了，已经遇到过几次这种情况了

### 日志文件

从[2023-04-13 11:36:48.979]开始
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11218099/asst.log)

### 截图

![Screenshot_20230413-120959](https://user-images.githubusercontent.com/89168964/231651011-2b1b3ed0-ab44-472c-83e8-1f03b214c255.png)
![Screenshot_20230413-121214](https://user-images.githubusercontent.com/89168964/231651019-77189f9a-aada-4b72-9e2f-037589fe82d5.png)

### 还有别的吗？

模拟器:逍遥模拟器
操作系统:win10

**Comment by ABA2396** [comment]
自己换完就能用了，先取消自动商店购物吧

**Comment by yingmiait** [comment]
因为是小号，就一直没换
