### ISSUE TITLE
主界面最小化后不能恢复&无法在win11多桌面切换下自动跳转

### ISSUE THREAD

**Issue by yishifengyin** [MaaAssistantArknights/MaaAssistantArknights#4315]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

主界面最小化后，只有第一次能正常恢复，后续将无法恢复。此时如果直接退出，则下次启动时窗口直接被最小化且无法显示。查看gui.json文件发现窗口启动设置为最小化状态，即
  "GUI.Position.Left": "-32000",
  "GUI.Position.Top": "-32000",

然后第二个问题，无法在win11多桌面下跳转，
例如：我在桌面1上打开了MAA，在桌面2上点击MAA小图标，则不会自动转至桌面1。

建议：
1. 检查在窗口最小化时保存当前窗口位置的代码，估计是被后续错误初始化赋值之类覆盖了
2. 关闭程序时，如果窗口位置是非主屏幕内位置，包括但不限于第二块屏幕/最小化，则强制初始化为主屏幕内位置。按现在这个逻辑，假如我用笔记本，把窗口拖到扩展的外接显示器上，关闭后单独使用笔记本，应该会同样导致窗口显示不出来。

### 日志文件

[asst - 副本 (2).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11224169/asst.-.2.log)

**Comment by moomiji** [comment]
关于第一个问题，4.14.1已经ban掉了`最小化时保存当前窗口位置`

**Comment by ABA2396** [comment]
> @ABA2396 把目前的currentScreen.Bounds.Width换成SystemParameters.VirtualScreenWidth怎样？
> 
> 1. 像建议2提到的，因为目前是虚拟坐标-实际屏幕大小的相对坐标，这个数值是有可能刚好让窗口显示不出来
> 2. 方便虚拟坐标和虚拟屏幕大小进行比较，检查在当前窗口位置是否合理；目前的保存的相对坐标是无法进行检查的

之前不是因为可能在虚拟屏幕的死角所以换的相对坐标吗，当前屏幕的相对坐标不应该会到外面去啊

**Comment by moomiji** [comment]
> 之前不是因为可能在虚拟屏幕的死角所以换的相对坐标吗，当前屏幕的相对坐标不应该会到外面去啊

确实是考虑死角换的，但currentScreen.Bounds返回的值在多屏下不一定正确

![image](https://user-images.githubusercontent.com/35213527/231980473-fb76c07c-ba90-4479-9f2b-6e498917d712.png)
![image](https://user-images.githubusercontent.com/35213527/231980524-63f2c623-64b1-4f31-80c5-42f1475dfa43.png)

所以考虑使用虚拟屏幕绝对坐标，同时存下SystemParameters.VirtualScreenWidth×Height、currentScreen.Bounds.Location用于检查

出现在死角的情况为：
- 虚拟屏幕的大小改变
- 虚拟屏幕的大小不变，但屏幕的坐标发生改变
- 用户把MAA拖入死角

**Comment by ABA2396** [comment]
草，好奇怪，那改改（）

**Comment by ABA2396** [comment]
> 确实是考虑死角换的，但currentScreen.Bounds返回的值不一定正确
> 
> ![image](https://user-images.githubusercontent.com/35213527/231980473-fb76c07c-ba90-4479-9f2b-6e498917d712.png)
> ![image](https://user-images.githubusercontent.com/35213527/231980524-63f2c623-64b1-4f31-80c5-42f1475dfa43.png)
> 

所以是因为屏幕缩放的原因导致的吗

**Comment by moomiji** [comment]
> 所以是因为屏幕缩放的原因导致的吗

不是，有时候调缩放这个值是不变的

**Comment by winerchan** [comment]
win11系统同样出现了类似的问题，还没有找到触发原因，但是打开maa后桌面看不到GUI 
打开config文件夹的gui.json发现如下内容
`"GUI.Position.Left": "-21333.3333333333",
  "GUI.Position.Top": "-21333.3333333333",`
估计也是这个错误，改成0就出来了

**Comment by moomiji** [comment]
> win11系统同样出现了类似的问题，还没有找到触发原因，但是打开maa后桌面看不到GUI 打开config文件夹的gui.json发现如下内容 `"GUI.Position.Left": "-21333.3333333333", "GUI.Position.Top": "-21333.3333333333",` 估计也是这个错误，改成0就出来了

速速更新4.15，保存位置现已加入校验

**Comment by winerchan** [comment]
> > win11系统同样出现了类似的问题，还没有找到触发原因，但是打开maa后桌面看不到GUI 打开config文件夹的gui.json发现如下内容 `"GUI.Position.Left": "-21333.3333333333", "GUI.Position.Top": "-21333.3333333333",` 估计也是这个错误，改成0就出来了
> 
> 速速更新4.15，保存位置现已加入校验

牛的！看issue还是open我以为还没开始弄，结果已经修完了。看来以后遇到问题得先看看提交版本时候的更新日志是不是修过了

**Comment by ABA2396** [comment]
现在还加了个右键点图标强制显示的功能，转跳估计不会做了）
