### ISSUE TITLE
一更新到4.13.0beta.1.62以上就报错

### ISSUE THREAD

**Issue by fisifoe** [MaaAssistantArknights/MaaAssistantArknights#4318]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

报错  MaaWpfGui.ViewModels.UI.SettingsViewModel”的类型初始值设定项引发异常。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11226844/gui.log)

### 截图

![360截图16720330193031](https://user-images.githubusercontent.com/130447342/231894584-d008f251-7981-43ef-ba6a-22f70f49d316.png)

### 还有别的吗？

mumu模拟器  Windows 10 企业版

**Comment by pein0saga** [comment]
这类报错可以先试一下重启系统删掉全新安装MAA比如文件被占用更新不完整之类各种复杂情况，
如果和系统变动有关或者缺失依赖可以升级下DOTNET运行库

**Comment by ABA2396** [comment]
maa.plus/docs/1.2-常见问题.html

**Comment by fisifoe** [comment]
> 这类重启系统全新全新全新安装比如文件被被更新更新完整完整完整完整完整完整完整之类之类之类之类之类各各各各各各，如果种各各各各各种完整 完整

所以是系统出了问题嘛？

**Comment by fisifoe** [comment]
> maa.plus/docs/1.2-常见问题.html

除了可能性2前两个我都试了

**Comment by ABA2396** [comment]
报这个错最大的可能就是运行库有问题，先确定下有没有下错maa版本（如Win64下成了arm64），再确定c++和.net库版本（覆盖安装），再不行就只能下完整库了。但是如果老版本能打开的也不应该会报这个来着

**Comment by pein0saga** [comment]
你的问题和他重复了吧？

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/4292
“MaaWpfGui.ViewModels.UI.SettingsViewModel”的类型初始值设定项引发异常。 #4292

    > 是的，新电脑没安装运行库，解决了，谢谢

_Originally posted by @LeYouJJ in https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/4292#issuecomment-1504501060_

**Comment by pein0saga** [comment]
duplicate with #4292

**Comment by fisifoe** [comment]
> 

是这样但是我覆盖安装了运行库也没有用

**Comment by fisifoe** [comment]
> 报这个最大的错误的可能就是运行库有问题，先确定下没有下错maa版本（如Win64下成arm64），再确定c++和.net库版本（覆盖安装），再不能下只能犯错库了。但是如果老版本能打开的也不应该报这个来

**Comment by fisifoe** [comment]
> 报这个最大的错误的可能就是运行库有问题，先确定下没有maa版本（如Win64下成arm64），再确定c++和.net库版本（覆盖安装了），再不能下只锴。但是如果老版本能打开的也不应该报告这个来

没下错版本运行库也覆盖安装了但是我想用新版实在不行我就用老版本吧

**Comment by pein0saga** [comment]
> > 报这个最大的错误的可能就是运行库有问题，先确定下没有maa版本（如Win64下成arm64），再确定c++和.net库版本（覆盖安装了），再不能下只锴。但是如果老版本能打开的也不应该报告这个来
> 
> 没下错版本运行库也覆盖安装了但是我想用新版实在不行我就用老版本吧

系统事件查看器里面有没有报错？；有没有试过全新安装MAA（不是覆盖）？
