### ISSUE TITLE
可不可以自动更换基建副手

### ISSUE THREAD

**Issue by Koitoyuuu** [MaaAssistantArknights/MaaAssistantArknights#432]
玛丽大大好
关于这个我是这么想的
基建副手这五个角色，可以根据角色星级、好感度自动选择，我有这么几种思路，希望能给大佬参考和灵感
1.最简洁的是，完全根据好感度从小到大
2.基建副手中任意一个大于100好感度时，会把这位干员换成其他干员里好感度最低的干员（不过我发现，干员选择页面都不会完整显示干员的名称，副手界面甚至只有立绘和好感度百分比数值。如果要用这些信息来辨别干员，就可能会有多个干员无法相互区分的情况，从而引发一些小问题）
3.好感小于100%的6星最优先，其次是五星，全部都达到100%后则选择好感度大于100%的干员（如果有大量干员小于100%好感度的话，可能就会有亿些慢？）
4.头牌花魁达到200%前不更换（我也不知道，可能可以方便真爱党拉满羁绊？或者用来拉强力五星？）
总之如果能给玛丽大大提供一些灵感就好了，希望牛牛越做越好（？）

**Comment by ABA2396** [comment]
现在宿舍有填充干员刷信赖了，可以更新后去设置里开启
