### ISSUE TITLE
无法正常完成刷理智任务

### ISSUE THREAD

**Issue by Suimukill** [MaaAssistantArknights/MaaAssistantArknights#4326]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新了主线关点两次确认的功能以后，确实能自己用免费券了，然而由于点两次会取消吃理智液的界面，所以它永远都不会知道理智已经没了，反复在空理智的情况下点击开始作战。不仅是12章，不能使用免费券的其他关卡也会点击两次。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11233441/asst.log)
19点44开始的刷理智任务，执行了16次1-7，一直到21点多还在卡

### 还有别的吗？

蓝蝶模拟器

**Comment by ABA2396** [comment]
是模拟器比较卡吗？照理点开了吃理智药的时候是识别不到开始按钮的

**Comment by ABA2396** [comment]
我本次测不出来，试试这样能不能用
