### ISSUE TITLE
干员U-Official无法被正常识别于会客室排班中

### ISSUE THREAD

**Issue by 1292620933** [MaaAssistantArknights/MaaAssistantArknights#4327]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

u-official在被选取于会客室时maa无法识别，随后进入寻找u-official的搜索循环，循环多次后maa自动跳过选取会客室干员，排班表由maa的工作排班表，干员名由prts复制而来

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11233471/asst.zip)

### 截图

![图片1](https://user-images.githubusercontent.com/130767367/232060715-477354ed-5116-4ce1-b018-19593e91b043.png)

### 还有别的吗？

使用mumu模拟器最新版本

**Comment by ABA2396** [comment]
虽然这样，为啥要用 u-official ）
