### ISSUE TITLE
肉鸽无法二倍速战斗

### ISSUE THREAD

**Issue by Mr-13th** [MaaAssistantArknights/MaaAssistantArknights#433]
模拟器MuMu2.5.19
肉鸽开启一倍速有点慢
小助手版本3.2.1

**Comment by MistEO** [comment]
附一下日志吧~

**Comment by MistEO** [comment]
分辨率太低了

> 目前仅对 16:9 分辨率支持较好，最低支持 1280 * 720，更高不限。非 16:9 分辨率可能会有奇奇怪怪的问题，正在进一步适配中_(:з」∠)_

话说这么低的分辨率居然基本能跑（

**Comment by Mr-13th** [comment]
解决问题了，谢谢玛丽
