### ISSUE TITLE
水月肉鸽MAA日志出现重复探索

### ISSUE THREAD

**Issue by 00722D** [MaaAssistantArknights/MaaAssistantArknights#4330]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

挂机水月肉鸽，日志显示进行多次探索。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11235550/asst.zip)

### 截图

![1681492385830](https://user-images.githubusercontent.com/130785670/232114817-5a32b6f9-2f25-4c17-89fa-207438d68d26.png)

### 还有别的吗？

MUMU模拟器

**Comment by HMZyueshen** [comment]
你没选择肉鸽难度吗
