### ISSUE TITLE
【ios】使用playcover连接的mac版maa只能自动公招3次，无视第四个格子

### ISSUE THREAD

**Issue by ceramshaw** [MaaAssistantArknights/MaaAssistantArknights#4332]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用playcover连接的mac版maa只能自动公招3次，无视右下角的第四个格子
在自动公招里已经设置了最大次数为4次
但每次自动公招都会漏掉右下角的格子，不管它是空着的还是已完成，也排除了因为要手动确认tag的可能

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11236742/asst.log)
4月15日5:00（日本时间）左右

### 截图

<img width="574" alt="截屏2023-04-15 5 24 04" src="https://user-images.githubusercontent.com/73752856/232148751-80f3f3bd-a6b2-4ae1-8554-6d4191dc0a32.png">
自动公招设置截图

**Comment by pein0saga** [comment]
看你是日本时间，是日服有这个问题吗？

**Comment by ceramshaw** [comment]
不是的，是国服，不过我在日本所以是日本时间，刚又试了一下还是复现了这个问题，无视右下角

**Comment by ceramshaw** [comment]
@hguandl 更新v16.3版本后此问题解决，谢谢！
