### ISSUE TITLE
偶见基建换班时恰逢需要连接服务器导致的换人失败

### ISSUE THREAD

**Issue by yd278** [MaaAssistantArknights/MaaAssistantArknights#4333]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

换人时基建里正好有任务完成，触发了「正在提交反馈至神经」（视频里13秒处），然后就没点上

[调试.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11237930/default.zip)

### 日志文件

问题出现在16:02:00附近

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11237935/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11237941/gui.log)

**Comment by Kenton1989** [comment]
我也遇到了同一个问题。不过我的不是进入基建的时候，而是在使用无人机加速贸易站订单之后。
同理可得，会客室、人事部、发电站都会有这个问题（即选人界面因短时间UI冻结而进不去）。
进一步扩展的话，就是在基建时，因连接服务器，导致UI短时间冻结，进而导致一个操作被吞掉的事件随时都可能发生。要完美解决这个问题的话，需要考虑在执行任意一步操作后，如何验证这个操作已经执行，以及若未执行该如何挽回。
感觉工程量会很大，希望开发组头发没事。
