### ISSUE TITLE
自动使用理智药时反复关闭理智药界面又打开

### ISSUE THREAD

**Issue by GrassWorkshop** [MaaAssistantArknights/MaaAssistantArknights#4335]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

当开始行动理智不够时MAA尝试自行使用理智药（已开启理智药剩余时间不足两天自动使用），此时弹出理智不足需要使用理智药窗口，MAA自动关闭该窗口然后继续尝试开始行动，进入死循环，并且不会停止尝试刷理智任务

注:关闭自动使用两天内理智药或仓库没有短期理智药依然会循环

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11238122/asst.zip)

### 还有别的吗？

夜神模拟器 7.0.1.3070-7.1.2701210628
安卓7（64bit）
电脑系统:Windows11 64bit

**Comment by ABA2396** [comment]
#4326

**Comment by GrassWorkshop** [comment]
感谢
