### ISSUE TITLE
有没有自动保存每次使用的记录啊

### ISSUE THREAD

**Issue by wuxinHome** [MaaAssistantArknights/MaaAssistantArknights#434]
每次选了自动关机后，都看不见刷的记录，然后就是想看看之前每次刷的记录，可以做个保留的数据吗
还有就是换班这里的记录能不能也显示一下每次换班每个设施更换的干员名称，自动公招获得的干员名称，发现5，6星tag的提示

**Comment by MistEO** [comment]
@bakashigure 4.0 有这个么，或许可以加个 sqlite 存一下啥的？

**Comment by bakashigure** [comment]
> @bakashigure 4.0 有这个么，或许可以加个 sqlite 存一下啥的？

~~什么 sqlite ,我们都是直接用 json 的~~

**Comment by zhangweijian97** [comment]
同需要！或者玛丽能不能指个路，怎么把GUI界面右边那一串东西保存下了，我想试试看
