### ISSUE TITLE
客户端启动失败

### ISSUE THREAD

**Issue by sk0071103** [MaaAssistantArknights/MaaAssistantArknights#4343]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

'MaaWpfGui.ViewModels.UI.SettingsViewModel' 的類型初始設定式發生例外狀況。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11239092/gui.log)

### 截图

<img width="484" alt="螢幕擷取畫面 2023-04-15 181712" src="https://user-images.githubusercontent.com/130834831/232207974-ab2bc838-0522-4654-aa00-44e1bccbde51.png">

**Comment by ABA2396** [comment]
[可能性 1 : 執行庫問題](https://maa.plus/docs/zh-tw/1.2-%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C.html#%E5%8F%AF%E8%83%BD%E6%80%A7-1-%E5%9F%B7%E8%A1%8C%E5%BA%AB%E5%95%8F%E9%A1%8C)
