### ISSUE TITLE
SK-5 无法识别

### ISSUE THREAD

**Issue by CCCClaus** [MaaAssistantArknights/MaaAssistantArknights#4344]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

手动输入SK-5关卡名后无法自动跳转

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11239129/asst.log)

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11239130/asst.bak.log)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11239131/gui.log)

[gui.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11239132/gui.bak.log)

### 有什么好的想法？

增加SK-5的导航

### 其他内容

我要还好久的房贷，，，

**Comment by ABA2396** [comment]
e4454b97dc949df430c819edb7f645b93e2959cf fixed
