### ISSUE TITLE
为什么MAA空闲状态下也会占很高的内存呢

### ISSUE THREAD

**Issue by zoe4477** [MaaAssistantArknights/MaaAssistantArknights#4348]
### 说说你遇到的问题？

![image](https://user-images.githubusercontent.com/38827851/232219445-19b52d90-3e9d-401b-8917-7260348ea626.png)

**Comment by pein0saga** [comment]
这是win11的任务管理器吗？

**Comment by MistEO** [comment]
空间换时间啊，难道把所有资源全部释放掉，下次再运行又花时间重新加载资源吗（
