### ISSUE TITLE
理智用完了会一直在 开始行动 - 检查理智 循环

### ISSUE THREAD

**Issue by SanLuGuiGui** [MaaAssistantArknights/MaaAssistantArknights#4350]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

理智用完了会一直在 开始行动 - 检查理智 循环，不会进行其它任务，不会退出，是个死循环

MuMU模拟器2.7.21.0（x64） maa 4.14.1 

CPU J1900  用的是旧的指令集替换包

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11239595/asst.log)

### 截图

![1](https://user-images.githubusercontent.com/80374528/232227017-ab5f1d16-f04e-4ae3-9170-6a359de24ad2.png)
![2](https://user-images.githubusercontent.com/80374528/232227020-41a3b85e-5f12-4632-ae5b-5a2a5082e062.png)
![3](https://user-images.githubusercontent.com/80374528/232227022-a857b296-999d-468c-9017-a7bb50597b22.png)
![4](https://user-images.githubusercontent.com/80374528/232227090-2bbb39df-e399-437e-8c0e-f63f3b964d44.png)

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/4326
