### ISSUE TITLE
一键长草界面刷理智选项中，请明确吃理智药需求需要的数量指的是理智药数量

### ISSUE THREAD

**Issue by SanZekin** [MaaAssistantArknights/MaaAssistantArknights#4355]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用了一键长草界面刷理智选项，在吃理智药需求数量中，填写了想要使用的即将到期的理智药的理智总和（240理智，两个大理智药），但在脚本运行中，一共吃了七次理智药，使用理智药的理智总和远大于240理智

### 有什么好的想法？

建议明确吃理智药需求的数量为脚本自动使用的理智药数量，否则很容易让使用者认为理智药需求的数量为理智药理智总和。

### 其他内容

![image](https://user-images.githubusercontent.com/130878617/232261597-3e34348f-ba70-40dc-88b3-7ca839e86925.png)

**Comment by pein0saga** [comment]
用反证法：吃理智药和吃源石是并列的，“假设”填入内容是等价理智值，那吃一个源石也要换算成160, “吃源石” 160, 怎么想都不太可能（而且填的不是160的倍数呢？难道直接报错？），所以假设不成立。

**Comment by Potter-Lee** [comment]
这个我倒是没理解错，毕竟理智药有好几种，不是你想开多少理智就开多少理智的，所以这里既然让你填数字而不是下拉来选，就表示一定是要吃的理智药数量而不是理智数量。（虽然我都是设置999直接吃完就是了）

**Comment by ABA2396** [comment]
> 这个我倒是没理解错，毕竟理智药有好几种，不是你想开多少理智就开多少理智的，所以这里既然让你填数字而不是下拉来选，就表示一定是要吃的理智药数量而不是理智数量。（虽然我都是设置999直接吃完就是了）

其实不是数量而是次数）yj会自动给你选上能打完这把的理智药，如36理智本要吃4个理智小样，那一次就会吃4个

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/233763541-942b426d-60bf-40b0-8b19-3f7cab6879f1.png)
突然想到这里是有写的）

**Comment by pein0saga** [comment]
> ![image](https://user-images.githubusercontent.com/99072975/233763541-942b426d-60bf-40b0-8b19-3f7cab6879f1.png) 突然想到这里是有写的）

这年头用户难得能遇到好好写文档的开发人员，但他们都不珍惜 ）
