### ISSUE TITLE
mumu模拟器12，无法获取分辨率

### ISSUE THREAD

**Issue by lmp1051738469** [MaaAssistantArknights/MaaAssistantArknights#4357]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

3.3.5版本的mumu模拟器12，MAA无法获取模拟器分辨率。已经使用了管理员权限打开MAA。MAA版本是内测最新版v4.14.2-alpha0.14.g9414bd22

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11241100/asst.log)
时间点2023/4/16 10:37分

**Comment by MistEO** [comment]
需要填入的是 adb 的路径，不是 mumu 的路径
