### ISSUE TITLE
GUI在自动挂机一段时间后卡死

### ISSUE THREAD

**Issue by MisterCoBen** [MaaAssistantArknights/MaaAssistantArknights#4363]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

GUI在自动挂机时一段时间后无法被选中或拖拽，完全卡死(如截图所示)，只能从任务栏关闭，但挂机任务正常运行，运行完后不会自动关闭MAA，但会关机

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11241668/asst.log)
[gui-20230416.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11241669/gui-20230416.log)

### 截图

![grafik](https://user-images.githubusercontent.com/97687476/232284024-8f8636ee-5f2f-4eea-8921-cfc635715bb9.png)

### 还有别的吗？

MuMu模拟器

**Comment by MistEO** [comment]
更新下试试，内测版建议一直用最新的；否则最好用稳定版或者公测版

**Comment by MisterCoBen** [comment]
怪事了，明明一直使用的，可能是更新BUG，我更新好了试试
