### ISSUE TITLE
打开软件之后，底层任务栏只有图标，且无法打开

### ISSUE THREAD

**Issue by NIWA-HOJI** [MaaAssistantArknights/MaaAssistantArknights#4365]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

当打开软件时候，最下方任务栏会出现软件图标，但是你不管等多久均不弹出窗口，切点击该图标之后无任何反应

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11246369/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/92297190/232382822-b3f4a161-42c5-4ce6-85f3-01db0a296a89.png)

### 还有别的吗？

nox模拟器 模拟器正常（但是现在maa打开都打不开）
win11 22H2

**Comment by ABA2396** [comment]
看看 debug/gui.json 文件中的 "GUI.Position.Left" 和 "GUI.Position.Top" 是否为负数，如果是的话把这两行删了。是不是开了打开 maa 后直接最小化？如果是的话在 #4309 已经修了

**Comment by moomiji** [comment]
看日志的版本应该是没完全修到

**Comment by MistEO** [comment]
要不加个小于 0 自动置 0 ？

**Comment by moomiji** [comment]
> 要不加个小于 0 自动置 0 ？

这个值是可以小于0的

我使用了一种稳定得到离谱位置的方法
在保存到离谱位置的时候，`mainWindow.WindowState == WindowState.Normal`
所以只能检查主界面是否和虚拟屏幕相交啦：https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/4352/commits/63f24cf35910fce1c7bf9f4e4e2b61e6d214f6ce

~~看了半天提交内容，还是不知道发生了甚么~~

**Comment by NIWA-HOJI** [comment]
> 看看 debug/gui.json 文件中的 "GUI.Position.Left" 和 "GUI.Position.Top" 是否为负数，如果是的话把这两行删了。是不是开了打开 maa 后直接最小化？如果是的话在 #4309 已经修了

是负的，删除了就变好了
