### ISSUE TITLE
启动后会自动重置配置，并弹出已更新窗口

### ISSUE THREAD

**Issue by Winches** [MaaAssistantArknights/MaaAssistantArknights#4369]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA：v4.14.1
模拟器：BlueStack 5.10.210.1003 P64(HyperV Version)
版本	Windows 11 专业版
版本	22H2
操作系统版本	22621.1555

由于使用MAA时一直无法自动检测模拟器的ADB地址，所以我一直使用脚本运行模拟器和MAA，一直稳定运行。自从自动更新（多次）后便一直出现重置的情况，具体情况表现为 `gui.json` 在运行后会自动重置，并且弹出更新说明窗口。启动脚本为 `powershell` ，具体方式为 `Start-Process -Verb RunAs "C:\Program Files\MAA\MAA.exe"` 。
ps:要是能够解决不能自动识别adb地址的问题就更好了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11249439/asst.log)
问题首次出现约为1周前，约 `2023-04-10` 。

### 截图

![image](https://user-images.githubusercontent.com/7054776/232468356-57f2185d-76a8-47f6-b5c4-b625df4f29cc.png)
![image](https://user-images.githubusercontent.com/7054776/232468588-ac705fa1-db69-4110-b997-fc9269623b15.png)

**Comment by pein0saga** [comment]
天！HyperV 和 win11双buff！

**Comment by ABA2396** [comment]
@moomiji 确实有这个问题，今天在切换语言的时候发现的，切换到之前没用过的语言时会自己点上 `自动肉鸽`  ，但是之后切换就不会遇到，感觉很奇怪）

**Comment by Winches** [comment]
> 天！HyperV 和 win11双buff！

没办法，win11预装的，又要用wsl……

**Comment by moomiji** [comment]
> @moomiji 确实有这个问题，今天在切换语言的时候发现的，切换到之前没用过的语言时会自己点上 `自动肉鸽` ，但是之后切换就不会遇到，感觉很奇怪）

 我遇到的是`自动战斗`里点开始，开始的是一键长草（

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/4373 try to fix
