### ISSUE TITLE
自动肉鸽：打倒最后一关时，无法识别对话并继续

### ISSUE THREAD

**Issue by 1044636576** [MaaAssistantArknights/MaaAssistantArknights#4374]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

傀影，不晓得是不是最后一关（基本没动过肉鸽）但是有人物对话。

能打到最后一关也是我没想到的a.a

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11259199/asst.zip)

### 截图

![Snipaste_2023-04-18_15-41-11](https://user-images.githubusercontent.com/30854771/232707422-d17fb0e4-459b-4978-9c8c-89602b835475.png)

### 还有别的吗？

mumux
12600kf 3070

**Comment by snowballls** [comment]
第一次打才有，点一下下次就不会了
