### ISSUE TITLE
训练室功能增加：可以选择不对训练室干员变动

### ISSUE THREAD

**Issue by ShinyCook** [MaaAssistantArknights/MaaAssistantArknights#4375]
### 说说你遇到的问题？

我经常没有材料去专三，这时候专精干员和艾丽妮就留在里面了，结果maa自动给我换下去，导致我的减时间没了，希望可以加这个功能，不能就算了

**Comment by MuLInGRui** [comment]
其实可以选择不将已入驻干员放入宿舍，然后将基建设置中的宿舍放到最后

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/232777262-21f6f64a-c4d5-4d88-96d9-01fc10148b45.png)

**Comment by ShinyCook** [comment]
原来如此，是我疏忽了，非常感谢，/鞠躬.jpg
