### ISSUE TITLE
使用自定义基建配置时，建议可以让maa在宿舍还有空位时自行选择非满心情干员和信赖干员进宿舍

### ISSUE THREAD

**Issue by MuLInGRui** [MaaAssistantArknights/MaaAssistantArknights#4378]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用自定义基建配置时，如果没有填入宿舍的排班内容，会将宿舍清空；填入宿舍排班内容后会完全安装排班来，我的空位无法用来给其他干员蹭信赖和回复加工训练干员的心情

### 有什么好的想法？

因为可能会出现加工训练等消耗心情的额外情况，这就导致宿舍的安排不一定会完全按照排班表进行，所以我建议在使用自定义基建配置的基础上，在宿舍步骤完成后再加入两个步骤，即宿舍空位放非满心情干员和宿舍空位蹭信赖（已有的功能）

**Comment by MuLInGRui** [comment]
其实把原有的宿舍功能单拎出来放到排班后就可以，十分感谢

**Comment by MistEO** [comment]
> 其实把原有的宿舍功能单拎出来放到排班后就可以，十分感谢

没理解，那和把宿舍放到最后换班有什么区别？

**Comment by MuLInGRui** [comment]
按照自定义配置的话，宿舍中的排班会完全按照配置表的来，不会再进行内置的宿舍安排，比如我最后一个宿舍设置的是只有远山，那么就只会选择远山进宿舍，不会再有信赖干员；因为可能还有加工站和训练室的干员需要休息，和需要蹭信赖的干员，所以我想的是把配置表中没有的空位也利用上，比如把原本内置的宿舍安排给再加进来-------- 原始邮件 --------发件人： MistEO ***@***.***>日期： 2023年4月18日周二 晚上8:02收件人： MaaAssistantArknights/MaaAssistantArknights ***@***.***>抄送： MuLInGRui ***@***.***>, Author ***@***.***>主    题： Re: [MaaAssistantArknights/MaaAssistantArknights] 使用自定义基建配置时，建议可以让maa在宿舍还有空位时自行选择非满心情干员和信赖干员进宿舍 (Issue #4378)

其实把原有的宿舍功能单拎出来放到排班后就可以，十分感谢

没理解，那和把宿舍放到最后换班有什么区别？

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/232778551-acf6853c-2edc-4cdb-a4f1-74061a86cd0e.png)
这个（autofill）选上的话会在选完指定的人之后按原来默认的换班逻辑选剩下的人，如果你设置里选了 `宿舍空余位置蹭信赖` 的话应该就可以了啊

**Comment by MuLInGRui** [comment]
我试了一下，确实可以，是我没能完全理解补满空位的意思，十分抱歉，谢谢-------- 原始邮件 --------发件人： uye ***@***.***>日期： 2023年4月18日周二 晚上8:35收件人： MaaAssistantArknights/MaaAssistantArknights ***@***.***>抄送： MuLInGRui ***@***.***>, Author ***@***.***>主    题： Re: [MaaAssistantArknights/MaaAssistantArknights] 使用自定义基建配置时，建议可以让maa在宿舍还有空位时自行选择非满心情干员和信赖干员进宿舍 (Issue #4378)

这个（autofill）选上的话会在选完指定的人之后按原来默认的换班逻辑选剩下的人，如果你设置里选了 宿舍空余位置蹭信赖 的话应该就可以了啊
