### ISSUE TITLE
关于加速换基建干员的建议

### ISSUE THREAD

**Issue by qw1642190428** [MaaAssistantArknights/MaaAssistantArknights#4385]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在每次换基建都需要20分钟到半小时不等

### 有什么好的想法？

如果是单个账号的练度box扫描转换成数据保存到本地从而加速找到指定的干员的过程 另一方面是肉鸽让他更深度的参考抓牌的规律  就是突发奇想不知道有没有帮助

**Comment by Saratoga-Official** [comment]
无计划
