### ISSUE TITLE
移动文件位置后报错

### ISSUE THREAD

**Issue by wk521463** [MaaAssistantArknights/MaaAssistantArknights#4386]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

移动文件位置后无法打开MAA

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11263744/gui.log)

### 截图

![image](https://user-images.githubusercontent.com/130361027/232831854-b71ae790-b29f-4c9f-9188-4463c1155474.png)

**Comment by ABA2396** [comment]
什么叫 `移动文件位置后报错` ？是只动了 `maa.exe`？
