### ISSUE TITLE
[Feature Request] 按照日期决定刷什么

### ISSUE THREAD

**Issue by hechuan9** [MaaAssistantArknights/MaaAssistantArknights#4387]
长草期太懒了，1-7已经被我刷爆了。

求开发以下两种功能：
1. 非活动期间，根据星期几决定刷不同的材料。比如135红票，24经验之类的
或者
2. 按照一个特定的顺序刷理智：比如有红票刷红票，没红票刷经验

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/232863411-65ceea82-68ef-416e-a132-db17c72941aa.png)
![image](https://user-images.githubusercontent.com/99072975/232863538-dcee80e1-5690-4f93-be13-9982ba81b22d.png)

**Comment by hechuan9** [comment]
啊~~居然已经有这个功能了！感激感激！
