### ISSUE TITLE
还需要【中止时脚本】

### ISSUE THREAD

**Issue by Potter-Lee** [MaaAssistantArknights/MaaAssistantArknights#4388]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我编写了自动修改和恢复分辨率的脚本，但是当我点【停止任务】时，不会执行【结束时脚本】，导致分辨率没有被恢复

### 有什么好的想法？

手动停止时不执行【结束时脚本】是合理的，执行完成与终止是两个决策分支。所以希望增加【中止时脚本】

**Comment by Rbqwow** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55343783/a2fbe3a9-a9cf-4fa2-81aa-5c74b3263d17)
新版本加了俩选项 虽然和中止时脚本不太一样 不过好像不拆开也没事(
