### ISSUE TITLE
【开始前脚本】和【结束后脚本】增加支持bat格式

### ISSUE THREAD

**Issue by Potter-Lee** [MaaAssistantArknights/MaaAssistantArknights#4389]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

鼓捣了一个小时没研究明白这俩脚本是怎么执行的，怎么写都没用，fork代码又试了好久才发现是只能执行exe且不能添加参数（神奇的注释），明明是轻量的脚本，却要求编译成exe，成本较高

### 有什么好的想法？

执行时考虑下各个平台的主流脚本格式，如windows的bat、mac、linux的sh等。鉴于体量，可以优先做bat。
或者可能换个别的调用方法可能直接就兼容了吧？不是很了解C#的库

### 其他内容

其实我用前后脚本就是为了调整平板的分辨率而已，如果考虑内置分辨率调整功能的话（根据最长边推算16:9之类的，或者直接配置项让用户自己填之类的），那我对脚本功能也不是在意2333

**Comment by ABA2396** [comment]
填可执行文件的路径就可以了啊
![image](https://user-images.githubusercontent.com/99072975/232865217-0b70dce0-dc89-4762-a79d-5f0ef97a8efc.png)

**Comment by MistEO** [comment]
就是支持 bat 的

**Comment by Potter-Lee** [comment]
我的锅，估计是别的因素干扰到了，bat也是能用的
