### ISSUE TITLE
版本更新后原有配置会被清除

### ISSUE THREAD

**Issue by drway** [MaaAssistantArknights/MaaAssistantArknights#439]
包括 #424 中的所有问题
以及肉鸽自定义干员和自定义adb路径
是不是tasks.json和config.json 覆盖更新啊（
蓝叠hyperv版落泪，每次重配（

**Comment by qianxu2001** [comment]
因为有时更新就是改这些文件，建议把干员那一段保存一份被覆盖后粘贴回去

**Comment by wlwxj** [comment]
我也遇到这个问题了，之前的肉鸽配置全白写了
