### ISSUE TITLE
吃理智药的个数与次数

### ISSUE THREAD

**Issue by dylanhz** [MaaAssistantArknights/MaaAssistantArknights#4392]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

建议将吃理智药的数量由次数改为个数。
因为理智小样一次可能不止吃一个，例如0体打红票会一下吃3个。如果有打算使用多少体力，计算个数比次数要方便许多。

**Comment by ABA2396** [comment]
这个问题之前有讨论过，现在吃药是没有识别吃的什么药吃了几个，而一般的药都肯定是够一次关卡的，只有理智小样会遇到这种问题。而为这个活动单独写一个又比较麻烦，就看有没有人乐意写了）
