### ISSUE TITLE
仓库识别不了晶体电路和晶体元件

### ISSUE THREAD

**Issue by IranksAdral** [MaaAssistantArknights/MaaAssistantArknights#4395]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最近一直发现复制的时候漏掉晶体电路和元件，反复试了几次都一样，更新版也没有修复的样子

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11272211/asst.log)

### 截图

![%3O(E)$VZD5FK E 8J}R (B](https://user-images.githubusercontent.com/87361258/233053925-6002efc6-f15c-4c38-bfc9-bc2dbf60eb34.png)
![AXP}WG6(G})8(6E{9R%569T](https://user-images.githubusercontent.com/87361258/233053940-83ff9488-611e-4707-a4e4-c35c1dbc3ac0.png)
![2023-04-19_18-51-19-369_raw](https://user-images.githubusercontent.com/87361258/233054204-624d7e7f-0a58-4553-9dea-9795b96b6194.png)

**Comment by horror-proton** [comment]
没能复现出问题, 而且这张图位置不对不能用来识别左边一列, 去 debug/depot 文件中看看

**Comment by IranksAdral** [comment]
[2023-04-20.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11278278/2023-04-20.zip)
![N4L2H}D4IQ$5XCFP{6}0M5J](https://user-images.githubusercontent.com/87361258/233222244-d89400ea-9b44-438d-80b0-5d35e6588160.png)
追加图片，确实是这一排都识别不上，难道是分辨率错误？

**Comment by MistEO** [comment]
像是滑动的问题？滑的太多了
