### ISSUE TITLE
完成任务后自动退出MAA和模拟器失败

### ISSUE THREAD

**Issue by JKKJ9204** [MaaAssistantArknights/MaaAssistantArknights#4397]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动退出MAA和模拟器失败，模拟器设置了以管理员启动，MAA没有设置。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11274782/asst.log)
4.19晚上11点附近吧

### 截图

![68191774928](https://user-images.githubusercontent.com/119020178/233127242-4e208a90-399c-4555-9931-4f387a2dbb4b.jpg)

**Comment by JKKJ9204** [comment]
没了

**Comment by MistEO** [comment]
你没给 MAA 管理员权限，关不掉管理员的模拟器
