### ISSUE TITLE
拉狗过劳死配置

### ISSUE THREAD

**Issue by Stargazer020** [MaaAssistantArknights/MaaAssistantArknights#441]
基建贸易站的企鹅物流三人组不能被正确识别，可能是由于拉狗注意力涣散的原因？
不知可否优化

**Comment by MistEO** [comment]
看起来是 bug, 贴一下日志吧~

**Comment by Stargazer020** [comment]
> 看起来是 bug, 重开个 bug 讨论, 贴一下日志吧~
我觉得应该不算bug，情况是脚本看到一个注意力涣散的拉狗时，不会把物流组直接放进去，而是优先把拉狗丢宿舍休息
能不能加一个识别涣散拉狗的功能（用物流组和巫恋组轮班）
