### ISSUE TITLE
刷理智打愚人号的复刻关，能不能优化不要每刷一次就退出活动重进

### ISSUE THREAD

**Issue by piaofengliuer** [MaaAssistantArknights/MaaAssistantArknights#4412]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

刷理智打愚人号的复刻关，每关打完都游戏崩溃重新启动，再回愚人号刷，能不能优化不要每刷一次就退出活动重进

### 有什么好的想法？

能不能优化成不要每刷一次就退出活动重进，感觉不算bug但是这样有点不太正常

### 其他内容

![AG `)2B(@%53P)@7Z% NWMP](https://user-images.githubusercontent.com/29629899/233523479-577c6c58-2ad2-49fa-88b8-673f999543ab.png)

**Comment by ABA2396** [comment]
正常是不会报游戏崩溃的，带上日志发个bug反馈
