### ISSUE TITLE
Maa关卡选择出现“不支持的关卡”

### ISSUE THREAD

**Issue by 0O0o0oOoO00** [MaaAssistantArknights/MaaAssistantArknights#4413]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Maa关卡选择出现“不支持的关卡”，重启Maa多次后依旧无法解决

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11291766/asst.log)

### 截图

![16](https://user-images.githubusercontent.com/11174151/233526265-193fc80f-4b30-47ce-8059-d3aefea1638a.png)

### 还有别的吗？

![17](https://user-images.githubusercontent.com/11174151/233526352-5ec9556d-3615-4599-a561-55277d8db4c8.png)
![18](https://user-images.githubusercontent.com/11174151/233526467-21e25c82-f0c7-444a-b326-092e50c2ac8f.png)

**Comment by ABA2396** [comment]
更新

**Comment by 0O0o0oOoO00** [comment]
> 更新

maa提示说已经是最新版了

**Comment by ABA2396** [comment]
![IMG_20230421_103740.jpg](https://user-images.githubusercontent.com/99072975/233527456-ac6b056d-11b5-4ee3-a2a3-553c30d45629.jpg)
之后的版本加了个提示

**Comment by 0O0o0oOoO00** [comment]
将maa切换到公测版后更新后解决
