### ISSUE TITLE
基建中枢换班失败

### ISSUE THREAD

**Issue by zzXan** [MaaAssistantArknights/MaaAssistantArknights#4415]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

<img width="977" alt="微信截图_20230421172149" src="https://user-images.githubusercontent.com/99358986/233568902-2b821576-f3e7-4e8d-bf29-27d15a7a5ae8.png">
我注意到的时候是在这个界面一直往右划，尝试几次失败后就跳过中枢换人了。其实宿舍换人的时候也发生过这个问题。
（干员是之后我手动换的）

### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11293234/asst.-.log)
只截取了基建那部分的log，原文件300M+

### 截图

<img width="600" alt="微信截图_20230421171612" src="https://user-images.githubusercontent.com/99358986/233568671-824c0181-2dba-4326-a9ed-9301d27e8bdb.png">

**Comment by zzXan** [comment]
#4333 应该是跟这个issue类似的问题

**Comment by incloud02** [comment]
我出现了类似的问题：
在宿舍换人时，切换成了按照心情从高到低排序，一直向左划无法停止，且只选中了心情未满的干员（我设置了蹭信赖选项）
