### ISSUE TITLE
刷理智时总显示游戏崩溃，重新启动

### ISSUE THREAD

**Issue by TrishSpiceGirl** [MaaAssistantArknights/MaaAssistantArknights#4416]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MuMu模拟器（安卓12），b服刷SN-9，每刷完一次MAA就会显示“游戏崩溃，重新启动”，然后模拟器就会一步一步返回游戏主页面，然后再点进SN-9，才开始再刷一遍，不断重复。重启过模拟器和MAA，没有用

### 日志文件

7点左右

**Comment by pein0saga** [comment]
贴一下log，我以前试过删掉重装就好了（个人情况）
