### ISSUE TITLE
肉鸽增加购买道具功能

### ISSUE THREAD

**Issue by T-Chaos** [MaaAssistantArknights/MaaAssistantArknights#442]
肉鸽在刷完投资或者没有刷出投资时一般都会剩下原石锭，可以购买收藏品来增加分数 /蜡烛获取

**Comment by zzyyyl** [comment]
这个好像dev里已经做了（？

**Comment by MistEO** [comment]
> 这个好像dev里已经做了（？

确实

**Comment by T-Chaos** [comment]
> > 这个好像dev里已经做了（？
> 
> 确实

刚才试了一下，无论哪种策略都会在投资完之后直接退出商店，不会购买藏品

**Comment by MistEO** [comment]
> > > 这个好像dev里已经做了（？
> > 
> > 确实
> 
> 刚才试了一下，无论哪种策略都会在投资完之后直接退出商店，不会购买藏品

dev 里做的，开发分支，还没有推送到正式版本上~
