### ISSUE TITLE
水月肉鸽 “饥渴” 关卡无法释放技能

### ISSUE THREAD

**Issue by abgnwl** [MaaAssistantArknights/MaaAssistantArknights#4420]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

水月肉鸽关卡“饥渴”中，干员无法使用技能

MAA版本：MAA-v4.15.0-beta.1.42.g52f32c13-win-x64

### 日志文件

时间点 23:26
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11297220/asst.zip)

### 截图

![不开技能](https://user-images.githubusercontent.com/9429734/233677575-576977e8-f09d-47b2-ba9c-4b7992140346.png)

### 还有别的吗？

搜到一个类似的issue，也提到了这个关卡的问题
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/4345

**Comment by tang000ck** [comment]
我也有
