### ISSUE TITLE
MAA无法正常连接到模拟器

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#4426]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在近期的某次内测版更新之后，MAA在每次启动后都无法连接至模拟器，需要手动在设置-连接设置里点击自动检测连接，才能正常连接。在更新之前，是没有这个问题的，直接点开始就会自动正常连接。出现问题之后我点了退出时释放ADB，也没有用。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11300158/asst.log)

### 截图

![屏幕截图 2023-04-22 112236](https://user-images.githubusercontent.com/92417243/233759317-673eab01-84ae-4300-b99b-530e04d4a2c9.png)
这个截图不是出错时的截图，是我连接设置的截图，现在我每次启动MAA都需要手动选取自动检测连接才能正常连接。

### 还有别的吗？

MAA版本在图里

**Comment by ABA2396** [comment]
自动检测连接勾选后在右边会有一个一直检测连接，检测完之后就不会自动取消了
但我看日志里尝试了很多次连接emulator-5554的操作但都失败了，然后在等待模拟器启动的时候直接把maa关了？

**Comment by xiaoweiXX** [comment]
> 自动检测连接勾选后在右边会有一个一直检测连接，检测完之后就不会自动取消了 但我看日志里尝试了很多次连接emulator-5554的操作但都失败了，然后在等待模拟器启动的时候直接把maa关了？

但是勾选上每次都检测连接那每次就都太慢了，比如我要是识别一个公招，本来一秒的事要等个好几秒。而且只有每次启动会连接失败，第一次成功后就不需要再检测连接，也能直接成功。
直接关MAA是因为模拟器是正常开启的（甚至是MAA启动的），等MAA再连接要好久，因此我就会直接关掉MAA。重启MAA比等着快。

**Comment by ABA2396** [comment]
现在加了连接失败自动重启adb服务，应该可以解决这个问题了

**Comment by xiaoweiXX** [comment]
> 现在加了连接失败自动重启adb服务，应该可以解决这个问题了

问题依旧存在，我已经提交了新的issue

**Comment by zxfvb7c** [comment]
我也有一样的问题， 我整了个开机自动启动nox 就ok了。


写了个batch script
1.打开一个txt， 写入以下
timeout \t 30
start "" D:\Android_emulator\Nox\bin\Nox.exe          -》你的nox模拟器exe的位置

2. 重命名名字为 start_nox.bat
3.win + R 打开run窗口
4.输入shell:start 打开启动文件夹
5. 把这个 start_nox.bat 拷贝进去
6. 重启以后每次开机就会自动启动nox 也就是夜神
