### ISSUE TITLE
有时会误识别游戏崩溃

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#4427]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA有时会误识别到游戏崩溃，但实际上游戏并没有崩溃，只是停留在某个界面。我推测是识别问题导致的，在提示崩溃之后MAA会自动退回到游戏首界面，然后再一步步继续点回关卡自动刷。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11300178/asst.log)

### 截图

![屏幕截图 2023-04-22 113320](https://user-images.githubusercontent.com/92417243/233760110-4efc0cf3-a5ea-41f4-aeaa-26c0d4936431.png)

### 还有别的吗？

MAA版本在截图中

**Comment by saber65535** [comment]
我也遇到了这个问题，版本号4.15.0-beta.1.42.g52f32c13。在刷SN-8（SN-9）的时候，每刷完一次都会出现“游戏崩溃，重新启动”的报错。但是游戏本身没有崩溃，就是需要退回到主界面，然后再重新进入关卡。

**Comment by Wingein** [comment]
我也，但是不影响使用（笑

**Comment by saber65535** [comment]
> 

就是刷的效率变慢了 2333

**Comment by MistEO** [comment]
fixed, 刚发了个内测版，正在打包，等下试试

**Comment by xiaoweiXX** [comment]
> fixed, 刚发了个内测版，正在打包，等下试试

兄啊，为什么这个版本我现在找不到了，更新都没法更新
