### ISSUE TITLE
保全派驻新作业（约翰、雷神）无法识别

### ISSUE THREAD

**Issue by Wingein** [MaaAssistantArknights/MaaAssistantArknights#4429]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

下载新保全派驻作业的json文件后，在MAA自动战斗模块下选择作业路径弹出“解析作业文件错误”。又尝试了导入上次保全派驻的作业发现可以正常识别

### 日志文件

无

### 截图

![image](https://user-images.githubusercontent.com/76738856/233764995-47350563-e836-43d6-bf6a-659b45b29e8a.png)

### 还有别的吗？

配置：mumu模拟器，windows10

**Comment by ABA2396** [comment]
这个保全的格式作业站不支持，下载的格式是错的，更新测试版之后在原来的位置有新的保全作业文件

**Comment by Wingein** [comment]
需要重新下载MAA的测试版本对吗

**Comment by ABA2396** [comment]
在 设置-软件更新-更新版本里 选公测版然后检查更新就可以了

**Comment by Wingein** [comment]
非常感谢!已解决
