### ISSUE TITLE
asst::WordOcr偶发性耗时异常问题

### ISSUE THREAD

**Issue by Xiaodx912** [MaaAssistantArknights/MaaAssistantArknights#4430]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在运行过程中，MAA有时会停住不动。经检查日志发现`asst::WordOcr`的用时出现异常，怀疑与系统环境有关。
具体故障表现参考日志。

可否开启OCR部分性能profile，给出详细耗时？
BUG出现期间两个CPU核心满载，正常运行时无此情况。可能是错误地仅使用CPU进行OCR？

### 日志文件

选取表现出问题的一次`asst::InfrastAbstractTask::order_opers_selection`，其中前半部分耗时正常，后半部分异常。
值得注意的是此BUG的出现通常是连续的，一旦触发后续数次OCR耗时均会异常。
[ocr.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11300445/ocr.log)

### 截图

触发BUG时的CPU占用
![20230422144958](https://user-images.githubusercontent.com/22424478/233768046-35fb376f-afcf-4ad4-b7bf-7da8549e4f13.jpg)
正常运行占用
![20230422145150](https://user-images.githubusercontent.com/22424478/233768053-f46f0d19-1fb5-4dff-8e30-55954a8aa31f.jpg)

### 还有别的吗？

运行使用QEMU Q35虚拟机，显卡为vGPU，或许是BUG的触发因素
系统 Windows11 22H2，分配64vCPU 32GvRAM
GPU为P40-8Q，驱动528.24 CUDA12.0

**Comment by horror-proton** [comment]
这太怪了, 一个 OCR 居然能跑 5 分多钟, 这个问题容易复现吗.
MAA 自带的 onnxruntime.dll 并没有打开 GPU 相关的选项 (编译脚本在 [MaaDeps](https://github.com/MaaAssistantArknights/MaaDeps)), 正常就是用 CPU 推理的, 应该和显卡关系不大 :thinking:

问问 @dantmnf 应该怎么 debug 这种情况 (

~~在 Win 虚拟机上面运行 MAA 也有点怪, 上面还跑了一个模拟器吗~~

**Comment by dantmnf** [comment]
~~我先盲猜一个跨 NUMA 同步问题~~

[MaaDeps](https://github.com/MaaAssistantArknights/MaaDeps) 的 releases 里面是有 onnxruntime 的 pdb 的，可以直接上 VS profiler

**Comment by Xiaodx912** [comment]
> 这太怪了, 一个 OCR 居然能跑 5 分多钟, 这个问题容易复现吗
目前没有找到主动复现方式，这次是正好碰上了。
但是如果触发了一次似乎就会高频出现。那一段两天内五次定时任务的日志里，WordOcr耗时10s+的次数是522/3718

> ~在 Win 虚拟机上面运行 MAA 也有点怪, 上面还跑了一个模拟器吗~
是。宿主系统是Proxmox VE，虚拟机系统Windows，然后上面运行MAA和安卓模拟器

> ~我先盲猜一个跨 NUMA 同步问题~
宿主机是单路CPU，所有核都划进了同一个NUMA node，应该不是这部分的问题

这两天的耗时都是正常的，我先持续跟踪一下后续情况
