### ISSUE TITLE
识别工具中的干员识别beta，存在识别出现错误的问题

### ISSUE THREAD

**Issue by saber65535** [MaaAssistantArknights/MaaAssistantArknights#4431]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

识别工具中的干员识别beta，存在识别出现错误的问题
![image](https://user-images.githubusercontent.com/67904052/233769361-36ed5b46-c1c2-46c9-875b-e32718b845ea.png)

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11300509/asst.zip)

**Comment by MistEO** [comment]
fixed, 刚发了个内测版，正在打包，等下试试
