### ISSUE TITLE
运行后无法显示maa窗口界面

### ISSUE THREAD

**Issue by alien-zzy** [MaaAssistantArknights/MaaAssistantArknights#4432]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

运行后无法显示maa窗口，在下方的小图标处预览是空白的，右下角工具栏处小图标右键一键长草能正常运行
更新到v4.15.0也无法解决
我是双开的，另一个maa能正常运行

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11300543/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/79839078/233769820-e561d417-800e-4633-86a4-43c421ebcf4d.png)

### 还有别的吗？

windows系统

**Comment by alien-zzy** [comment]
重新下载并解压了一份maa，将源文件的config文件夹替换过去后能复现同样的问题
[config.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11300558/config.zip)

**Comment by alien-zzy** [comment]
![image](https://user-images.githubusercontent.com/79839078/233770657-0f0beef7-5c97-44a8-a795-48678a75e66b.png)
找到问题了 这两个值不知道为什么被改成-32000了

**Comment by ABA2396** [comment]
新版本加了位置检查，应该不会有这个问题了
