### ISSUE TITLE
蓝叠Hyper-V版本连接失败

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#4436]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

按照模拟器支持中的项目进行了设置，但还是连接不上蓝叠Hyper-V版本

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11301364/asst.log)

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/233788105-92fa1699-5f71-4a48-afe5-bf06e3a9a9cd.png)
这些加了吗，我看你日志里连的还是默认的端口

**Comment by xqgg** [comment]
一样的问题，按文档上的操作了还是不行，MAA上显示5555端口

**Comment by hanyuwei70** [comment]
如果开了加速器之类的东西关掉加速器，然后重启电脑看能不能连上

**Comment by ASC8384** [comment]
一样的问题，但是手动制定端口号可以链接

**Comment by xqgg** [comment]
> 一样的问题，但是手动制定端口号可以链接

我也是，不能自动读取，只能手动填写才能连接

**Comment by qew4476** [comment]
請問port怎么看呢？ mma上寫藍疊模擬器(127.0.0.1:5555) - 繁中服
代表port是5555嗎？我填了也連不上
![螢幕擷取畫面 2023-04-29 063425](https://user-images.githubusercontent.com/81016471/235264802-2bad8804-377c-46a4-932c-9aceb7f7b2ca.png)

**Comment by misaka10078** [comment]
一样的问题，bluestack.conf脚本似乎没有作用

**Comment by SherkeyXD** [comment]
#4616
-  不要启用“自动检测连接”功能
-  确认你的bluestack.conf路径正确，如果你的蓝叠模拟器安装在非默认位置，请使用你目前安装位置下的bluuestack.conf
- 检查使用的核心名称，如果为pie64核心请按照文档中的指示添加配置项

**Comment by MikuAlice** [comment]
一样的问题。在bluestack.conf里修改bst.instance.Pie64.adb_port到5557但MAA依旧显示连接到5555， 看起来是MAA没有读取bluestack.conf文件。 bluestack.conf路径为安装实际文件路径。（不知道log里能不能看到MAA是否有尝试读取bluestack.conf文件？）

**Comment by SherkeyXD** [comment]
> 一样的问题。在bluestack.conf里修改bst.instance.Pie64.adb_port到5557但MAA依旧显示连接到5555， 看起来是MAA没有读取bluestack.conf文件。 bluestack.conf路径为实际文件路径。（不知道log里能不能看到MAA是否有尝试读取bluestack.conf文件？）

bluestack.conf 中的 bst.instance.Pie64.adb_port 是蓝叠模拟器启动时自动生成的，不需要手动更改

请检查你是否已经按照 [MAA官方文档](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7-hyper-v) 中的步骤完成设置，尤其是以下两点：
- 斜杠是否转义？
- 蓝叠模拟器是否安装有不止一个核心？

**Comment by MikuAlice** [comment]
> > 一样的问题。在bluestack.conf里修改bst.instance.Pie64.adb_port到5557但MAA依旧显示连接到5555， 看起来是MAA没有读取bluestack.conf文件。 bluestack.conf路径为实际文件路径。（不知道log里能不能看到MAA是否有尝试读取bluestack.conf文件？）
> 
> bluestack.conf 中的 bst.instance.Pie64.adb_port 是蓝叠模拟器启动时自动生成的，不需要手动更改
> 
> 请检查你是否已经按照 [MAA官方文档](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7-hyper-v) 中的步骤完成设置，尤其是以下两点：
> 
> * 斜杠是否转义？
> * 蓝叠模拟器是否安装有不止一个核心？

- 已按照文档中的步骤更改了gui.json文件
- 添加在Default下的项目为： 
```
         "BlueStacks.Config.Path": "D:\\Game\\android\\BlueStacks_nx\\bluestacks.conf",
         "BlueStacks.Config.Keyword": "bst.instance.Pie64.status.adb_port",
 ```
- Engine目录下只有Pie64一个核心文件夹：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137120035/d0151982-ee35-4c5c-abf6-bf3d585848a2)

**Comment by ArkURL** [comment]
同样的问题，也尝试了FAQ里的解决方案，但和上面一样没有解决
