### ISSUE TITLE
信用相关（借助战赚信用）：有时候卡在别传界面，不进入活动火蓝之心与模拟器分辨率低有关

### ISSUE THREAD

**Issue by liuyunxinghen** [MaaAssistantArknights/MaaAssistantArknights#4437]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

WIN11系统，AMD5600X+微星B550迫击炮主板。
雷电模拟器9.0.42【原本分辨率设置为1280*720（DPI 240）】

本次愚人号活动，在MAA更新后经常卡在活动界面，不点击失落旗舰&无名之海进去刷活动关卡
在一系列巧合下，我发现我设置模拟器分辨率为1920*1080（dpi 280）时，能稳定进入活动关卡
在之前我也很苦恼MAA刷火蓝之心赚信用时，无法稳定进入活动关卡OF-1

在设置分辨率为1920*1080(dpi 280)之后，能稳定进入关卡OF-1了，反复测试了5次之后
我确定之前进不去OF-1关卡是因为我模拟器分辨率设置低了，希望能提高识别率一下
MAA运行，进不去OF-1时，不会提示错误，会在卡主延迟一段时间后显示完成。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11301521/asst.log)

**Comment by ABA2396** [comment]
不对啊，这个活动的图我当时是在1280*720的环境下截图的，而且图片处理也是缩放成720p的，为啥会1920*1080更稳）

**Comment by liuyunxinghen** [comment]
> 不对啊，这个活动的图我当时是在1280_720的环境下截图的，而且图片处理也是缩放成720p的，为啥会1920_1080更稳）

我不到啊，但我这里是这样的1280*720大多数是进不去的，然后我手动打
愚人号这次也进不去，我才试着改了下分辨率，结果就是1920*1080最稳定...都能进了

**Comment by liuyunxinghen** [comment]
> 不对啊，这个活动的图我当时是在1280_720的环境下截图的，而且图片处理也是缩放成720p的，为啥会1920_1080更稳）

我补充下截图，是卡在外传进入活动这个界面
![image](https://user-images.githubusercontent.com/42022829/233792048-8ae719d6-bddc-4efe-9e73-297dade15dcb.png)

**Comment by ABA2396** [comment]
改了识别方式，应该没问题了

**Comment by liuyunxinghen** [comment]
> 改了识别方式，应该没问题了

是的，已经没问题了，我试了三次，谢谢Thanks♪(･ω･)ﾉ
