### ISSUE TITLE
公开招募的数据源没有更新风笛

### ISSUE THREAD

**Issue by tsctsc6** [MaaAssistantArknights/MaaAssistantArknights#444]
要不要考虑换一个数据源呢

**Comment by zzyyyl** [comment]
风笛在`v3.1.3`的时候应该加过了（？
具体到commit应该是https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1689a5dcf0c19871175c7cc1832e19e45f8f2ca0
有没有可能是你的版本没有更新？

**Comment by tsctsc6** [comment]
哦，我是单看那个明日方舟工具箱是没有的。
那么这个公招识别时是按照本地数据库检索的，而不是直接链接那个工具箱的，是吗

**Comment by zzyyyl** [comment]
现在好像用的是prts的数据（？
确实是本地检索

**Comment by MistEO** [comment]
> 哦，我是单看那个明日方舟工具箱是没有的。 那么这个公招识别时是按照本地数据库检索的，而不是直接链接那个工具箱的，是吗

是的，最一开始是用的他们的数据源，后来他们弃坑了，我们就自动手动写数据了
