### ISSUE TITLE
v4.15.0-beta.2 on Mac can't start with EN client because resource path not exists

### ISSUE THREAD

**Issue by HuyNguyenA** [MaaAssistantArknights/MaaAssistantArknights#4440]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Can't start EN client because resource path not exists

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11301732/asst.log)

### Screenshots

<img width="889" alt="image" src="https://user-images.githubusercontent.com/54949136/233795127-a282d7ef-c389-4651-97fe-021649633922.png">

**Comment by MistEO** [comment]
@hguandl AsstLoadResource 现在不能无脑传了，目录不存在时会报错

**Comment by MistEO** [comment]
As a temporary solution, you can build the path that was not found at the end of the log, and an empty directory is fine.
