### ISSUE TITLE
v4.15.0-beta.2 繁中服提示資源包損毀

### ISSUE THREAD

**Issue by jane885511** [MaaAssistantArknights/MaaAssistantArknights#4443]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如題，原本在程式內更新後報錯，全刪重灌後選擇繁中服後報錯

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11302144/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/89138038/233802816-2ccec4be-84bc-4776-be4f-2d135d036df2.png)
![image](https://user-images.githubusercontent.com/89138038/233802829-3fd4da26-62cb-4d31-843c-efa3e7db6816.png)

### 还有别的吗？

夜神 windows10

**Comment by MistEO** [comment]
临时解决方法可以建一下这个路径，空目录即可
