### ISSUE TITLE
v4.14.1正式版之后的版本均会出现【“MaaWpfGui.ViewModels.UI.SettingsViewModel”的类型初始值设定项引发异常。】的闪退情况

### ISSUE THREAD

**Issue by rrrwing** [MaaAssistantArknights/MaaAssistantArknights#4445]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在版本号为v4.14.1之前的版本使用一切正常，但只要更新到最新的公测版或内测版本均会出现【“MaaWpfGui.ViewModels.UI.SettingsViewModel”的类型初始值设定项引发异常。】的闪退框；就算是重新下载14以上的包，一样无法正常运行；但v4.14.1稳定版本之前都不会出现这个问题。

### 日志文件

[新建文件夹.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11302626/default.zip)

### 截图

![123](https://user-images.githubusercontent.com/86699835/233814484-b479ac84-c13e-4473-b2b4-44d5c687f606.png)

**Comment by ABA2396** [comment]
重新下一下两个运行库试试，常见问题里有链接

**Comment by MistEO** [comment]
如果还不行，更新到内测版看下，现在会有详细的报错，看看是什么问题

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1d3a6ab9a2648daa3c3872ae81e084fa7cccdaf8 fixed
