### ISSUE TITLE
最近才出现的，最近数个版本打开GUI后卡死

### ISSUE THREAD

**Issue by yunfengT12** [MaaAssistantArknights/MaaAssistantArknights#4446]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

1个星期前是正常的，某一次卡死之后再也没正常过，win7，已经尝试过4.12.3到4.14.1的正式版，和4.15的最新测试，试过重启电脑，都是卡在主界面，只能结束进程

感觉是我电脑的问题，但解决不了（悲）

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11302661/debug.zip)
这是重装最新正式版4.14.1后运行一次时强制结束进程后的log

### 截图

![QQ拼音截图20230423101423](https://user-images.githubusercontent.com/109748793/233815837-321b6a55-f4bf-419f-a0f4-6d316728faa1.png)

### 还有别的吗？

mumu（但应该不关mmu的事）
win7

**Comment by LiamSho** [comment]
试试看在浏览器中打开 https://ota.maa.plus/
看看这个位置是不是显示 “连接是安全的”

<img width="384" alt="image" src="https://user-images.githubusercontent.com/28832398/233831935-1af45dcc-12ba-4785-97b6-f522cd553546.png">

**Comment by yunfengT12** [comment]
> 试试看在浏览器中打开 https://ota.maa.plus/ 看看这个位置是不是显示 “连接是安全的”
> 
> <img alt="image" width="384" src="https://user-images.githubusercontent.com/28832398/233831935-1af45dcc-12ba-4785-97b6-f522cd553546.png">

是正常的
![QQ拼音截图20230423174046](https://user-images.githubusercontent.com/109748793/233832176-70f373c0-3311-495d-bb84-9a0ca476f153.png)
