### ISSUE TITLE
开局会选择1希望换藏品的选项导致卡在借人界面

### ISSUE THREAD

**Issue by fangundeboll** [MaaAssistantArknights/MaaAssistantArknights#4447]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题

### 有什么好的想法？

希望优化选择开局选项的逻

**Comment by incloud02** [comment]
好像这位已经提过了#4346
