### ISSUE TITLE
版本4.15.0-beta.2识别工具-干员识别 识别不出某些干员

### ISSUE THREAD

**Issue by RedMercury1022** [MaaAssistantArknights/MaaAssistantArknights#4448]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

版本4.15.0-beta.2识别工具-干员识别 假日威龙陈无法识别

### 日志文件

[oper1.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11302833/oper1.zip)
[oper2.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11302834/oper2.zip)

### 截图

![Snipaste_2023-04-23_12-17-18](https://user-images.githubusercontent.com/131571559/233819704-e098730d-20cb-4bf4-870f-cac59c4564b5.png)

**Comment by GD-GK** [comment]
请上传一下asst.log文件
