### ISSUE TITLE
使用mumu模拟器12时，使用maa退出模拟器选项时会导致模拟器报错并无法关闭

### ISSUE THREAD

**Issue by sakuhoya** [MaaAssistantArknights/MaaAssistantArknights#4449]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用mumu模拟器12时，使用maa退出模拟器选项时会导致模拟器报错并无法关闭

**Comment by MistEO** [comment]
发下 gui.log

**Comment by ABA2396** [comment]
管理员权限启动了没

**Comment by sakuhoya** [comment]
抱歉让你们久等了，管理员权限启动了，但是当退出时依旧会显示模拟器运行异常，无法正常关闭模拟器

**Comment by sakuhoya** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303811/gui.log)

**Comment by sakuhoya** [comment]
![微信图片_20230423211325](https://user-images.githubusercontent.com/104946800/233841851-c7708e33-e2ce-473f-97a3-3f06ce746468.png)

**Comment by AnnAngela** [comment]
@MistEO @ABA2396 我之前已经发过这个问题了…… #4045 可以看一下

**Comment by ABA2396** [comment]
估计其他版本的mumu也有这个这个问题，但是通过窗口名的方法关掉了，mumu12的窗口名叫什么？

**Comment by AnnAngela** [comment]
> 估计其他版本的mumu也有这个这个问题，但是通过窗口名的方法关掉了，mumu12的窗口名叫什么？

![image](https://user-images.githubusercontent.com/9762652/236361728-f2be58a5-b458-433f-b293-b875df3bdc93.png)

`明日方舟 - MuMu模拟器`，应该是这个。

**Comment by ABA2396** [comment]
> > 估计其他版本的mumu也有这个这个问题，但是通过窗口名的方法关掉了，mumu12的窗口名叫什么？
> 
> ![image](https://user-images.githubusercontent.com/9762652/236361728-f2be58a5-b458-433f-b293-b875df3bdc93.png)
> 
> `明日方舟 - MuMu模拟器`，应该是这个。

这是12吗，那按道理用窗口名是能关掉的啊）管理器的情况下不能自动退出模拟器吗

**Comment by AnnAngela** [comment]
> > > 估计其他版本的mumu也有这个这个问题，但是通过窗口名的方法关掉了，mumu12的窗口名叫什么？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/9762652/236361728-f2be58a5-b458-433f-b293-b875df3bdc93.png)
> > `明日方舟 - MuMu模拟器`，应该是这个。
> 
> 这是12吗，那按道理用窗口名是能关掉的啊）管理器的情况下不能自动退出模拟器吗

是的，这个是12：
![image](https://user-images.githubusercontent.com/9762652/236593233-c40f86e5-4ca0-4a27-b62b-f382a5cb89b0.png)

**Comment by ABA2396** [comment]
> 是的，这个是12： ![image](https://user-images.githubusercontent.com/9762652/236593233-c40f86e5-4ca0-4a27-b62b-f382a5cb89b0.png)

X 和 12 是两个版本）

**Comment by ABA2396** [comment]
10bc322ff077b5dae5d40d208a0e58f0de998c50 fixed
