### ISSUE TITLE
无法更新

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#4451]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

每次检察更新，不是提醒我检查网络（不管我是否使用了代理），就是提示检测到更新但是找不到增量包。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303100/asst.log)

### 截图

![屏幕截图 2023-04-23 153049](https://user-images.githubusercontent.com/92417243/233826288-3d736119-3579-40c0-8b06-e9d615af1800.png)

**Comment by xiaoweiXX** [comment]
直接下载最新版原地解压即可，但是还是希望开发者不要随便撤包，或者至少保留OTA到最新版的增量包。这条我就先不关了，等开发者注意到再自己关。

**Comment by ABA2396** [comment]
内测版是不会撤的，炸了也就炸了）这个估计是打包出问题了
