### ISSUE TITLE
maatouch 和 minitouch 连接手机报错 TouchModeNotAvailable

### ISSUE THREAD

**Issue by ZhaoZuohong** [MaaAssistantArknights/MaaAssistantArknights#4452]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用 MAA-v4.14.1-linux-x86_64 时，对 `Python/sample.py` 稍做修改：

[sample.py.gz](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303200/sample.py.gz)

输出“连接失败”。

### 日志文件

TouchMode 使用 maatouch：

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303189/asst.log)

使用 minitouch：

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303239/asst.log)

### 截图

无

### 还有别的吗？

- 手机型号：motorola edge S30
- 使用出厂自带的 MYUI 4.0，Android 版本是 12
- 使用 `adb` 时正常

**Comment by MistEO** [comment]
高版本的手机确实是用不了的，可以用 adb input 模式，具体原因 @aa889788 可以帮忙解释下

**Comment by aa889788** [comment]
> 高版本的手机确实是用不了的，可以用 adb input 模式，具体原因 @aa889788 可以帮忙解释下

他这个maatouch不正常，我去试一下

**Comment by aa889788** [comment]
```
adb -s 192.168.1.2:43453 shell "export CLASSPATH=/data/local/tmp/e74245d0b5eda2c3; app_process /data/local/tmp com.shxyke.MaaTouch.App"
```
看一下输出

**Comment by ZhaoZuohong** [comment]
@aa889788 

我用 `adb shell` 连接手机，进入 shell：

```bash
xpeng:/data/local/tmp $ ls
app-release-unsigned.apk  e74245d0b5eda2c3
xpeng:/data/local/tmp $ export CLASSPATH=/data/local/tmp/e74245d0b5eda2c3
xpeng:/data/local/tmp $ app_process /data/local/tmp com.shxyke.MaaTouch.App
Aborted 
134|xpeng:/data/local/tmp $ 
```

**Comment by aa889788** [comment]
> @aa889788 
> 
> 我用 `adb shell` 连接手机，进入 shell：
> 
> ```bash
> xpeng:/data/local/tmp $ ls
> app-release-unsigned.apk  e74245d0b5eda2c3
> xpeng:/data/local/tmp $ export CLASSPATH=/data/local/tmp/e74245d0b5eda2c3
> xpeng:/data/local/tmp $ app_process /data/local/tmp com.shxyke.MaaTouch.App
> Aborted 
> 134|xpeng:/data/local/tmp $ 
> ```

看一下logcat

**Comment by ZhaoZuohong** [comment]
> 看一下logcat

[logcat.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303400/logcat.log)

**Comment by aa889788** [comment]
> > 看一下logcat
> 
> [logcat.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303400/logcat.log)

明白了，minitouch文件推送过之后，改用maatouch, 没有检测，直接尝试使用minitouch的elf,导致出错，你把那个文件删了之后重新用maatouch模式连接就可以了
@MistEO 看看该怎么改，要不每次退出都删除？

**Comment by ZhaoZuohong** [comment]
我把 `/data/local/tmp` 下的 `app-release-unsigned.apk` 和 `e74245d0b5eda2c3` 都删除后，maatouch 正常了。

然而，我之后又尝试在手机的 Termux 里 proot-distro archlinuxarm 容器中，运行 `MAA-v4.14.1-linux-aarch64`，第一次连接正常，我按了 `Ctrl-C`，又试了一次，就提示连接失败了。然后又回来试了试 x86-64 的 MAA，也无法连接，`/data/local/tmp`  下只有 `e74245d0b5eda2c3`，删掉也不行。重启手机后， x86-64 都无法连接了。

以下是在 x86-64 的尝试：

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303481/asst.log)

直接复制 log 中的命令，是有输出的：

```plaintext
zhao@sid:~/Downloads/MAA-v4.14.1-linux-x86_64/Python$ ~/Downloads/platform-tools/adb -s 192.168.1.2:43431 shell "export CLASSPATH=/data/local/tmp/e74245d0b5eda2c3; app_process /data/local/tmp com.shxyke.MaaTouch.App"
^ 10 1920 1080 255
$ 255
^C
```

同一分钟内 logcat 的输出：

[logcat.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303487/logcat.log)

然后试了一下 aarch64，没有删 `/data/local/tmp/e74245d0b5eda2c3`，第一次成功，第二次失败了：

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303494/asst.log)

此时运行 asst.log 中的那条命令，仍然有输出：

```plaintext
[root@localhost Python]# /usr/bin/adb -s localhost:43431 shell "export CLASSPATH=/data/local/tmp/e74245d0b5eda2c3; app_process /data/local/tmp com.shxyke.MaaTouch.App"
^ 10 1920 1080 255
$ 255
^C
```

**Comment by ZhaoZuohong** [comment]
我多次在 x86-64 和 aarch64 下进行试验，x86-64 又一直成功，aarch64 下有时成功有时失败

**Comment by ZhaoZuohong** [comment]
在 x86-64 和 aarch64 下又各试验了十余次，都失败了，虽然各自运行 `~/Downloads/platform-tools/adb -s 192.168.1.2:43431 shell "export CLASSPATH=/data/local/tmp/e74245d0b5eda2c3; app_process /data/local/tmp com.shxyke.MaaTouch.App"` 或 `/usr/bin/adb -s localhost:43431 shell "export CLASSPATH=/data/local/tmp/e74245d0b5eda2c3; app_process /data/local/tmp com.shxyke.MaaTouch.App"` 都有输出。

**Comment by MistEO** [comment]
> > > 看一下logcat
> > 
> > [logcat.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303400/logcat.log)
> 
> 明白了，minitouch文件推送过之后，改用maatouch, 没有检测，直接尝试使用minitouch的elf,导致出错，你把那个文件删了之后重新用maatouch模式连接就可以了
> @MistEO 看看该怎么改，要不每次退出都删除？

新的 push 进去不会覆盖老的吗？

**Comment by horror-proton** [comment]
? 为啥会用同一个, 这是怎么做到的 (

**Comment by aa889788** [comment]
很奇怪，报错说`NullPointerException`
```
04-23 18:55:36.958 11606 11606 D app_process: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
04-23 18:55:36.958 11606 11606 D app_process: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt68l.dat
04-23 18:55:36.963 11606 11606 W app_process: Failed to determine odex file name: Dex location /data/local/tmp/e74245d0b5eda2c3 has no extension.
04-23 18:55:36.990 11606 11606 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
04-23 18:55:36.990 11606 11606 D AndroidRuntime: Calling main entry com.shxyke.MaaTouch.App
04-23 18:55:36.996 11606 11636 E AndroidRuntime: FATAL EXCEPTION: Thread-1
04-23 18:55:36.996 11606 11636 E AndroidRuntime: PID: 11606
04-23 18:55:36.996 11606 11636 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
04-23 18:55:36.996 11606 11636 E AndroidRuntime: 	at com.shxyke.MaaTouch.InputThread.run(InputThread.java:142)
```
关键这一部分用的是readline, 理论上如何也不应该是个nullpointer啊
![图片](https://user-images.githubusercontent.com/16019986/233879538-8c4b8c43-820d-4e2f-a5ed-281605fe4620.png)

**Comment by aa889788** [comment]
现在仍然找不到问题出现在哪，目前我们手头的设备都能正常工作，怀疑可能是MYUI的bug, 你试一下scrcpy能不能呢跟在你的手机上工作

**Comment by ZhaoZuohong** [comment]
scrcpy正常。

如果真是MYUI的bug，那我运气属实有点差，还好adb input还能用
