### ISSUE TITLE
干员识别功能未识别到水陈

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#4453]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

试用了一下干员识别功能，发现未识别到水陈。

### 日志文件

以下为oper文件夹内图片：
[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303340/oper.zip)
[oper (2).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303339/oper.2.zip)

log文件：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303341/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/74366156/233831561-817bbe5b-6d0e-4962-a67a-b2d08a1fb578.png)

### 还有别的吗？

模拟器：mumu
系统：win11

**Comment by ABA2396** [comment]
估计是特别关注影响到识别了
