### ISSUE TITLE
触控出现问题，疑似错位

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#4454]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

触控输入存在问题，包括但不限于开始唤醒和刷理智。MAA确实有触控输入，但是会有一定的错位，导致无法形成有效点击。具体log看下面，上面的这个log是旧的。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303507/asst.log)

### 截图

![屏幕截图 2023-04-23 190942](https://user-images.githubusercontent.com/92417243/233836475-b5712889-7323-4077-8338-dc975479655c.png)

**Comment by xiaoweiXX** [comment]
使用三种触控模式均会卡住

**Comment by ABA2396** [comment]
进去之后其他任务能点吗？不能就是触控无效，去设置里点一下强制替换adb

**Comment by xiaoweiXX** [comment]
勾选ADB Lite也会卡住

**Comment by xiaoweiXX** [comment]
> 进去之后其他任务能点吗？不能就是触控无效，去设置里点一下强制替换adb

强制替换过ADB。我试试清理智

**Comment by xiaoweiXX** [comment]
> 进去之后其他任务能点吗？不能就是触控无效，去设置里点一下强制替换adb

清理智也会出错，我手动切换到SN 9界面，MAA会点不知道哪里，从SN 9退回到地图界面。

**Comment by xiaoweiXX** [comment]
> 进去之后其他任务能点吗？不能就是触控无效，去设置里点一下强制替换adb

看起来像是触控错位

**Comment by xiaoweiXX** [comment]
更新一下错误描述：
疑似触控错位，存在触控输入但是位置错了，有点击，但是位置不对，导致了问题出现
下面是最新的log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303526/asst.log)

**Comment by MistEO** [comment]
为啥模拟器有个黑边

**Comment by xiaoweiXX** [comment]
> 为啥模拟器有个黑边

雷电模拟器就这样，这黑边是雷电的，不是模拟器里面的

**Comment by xiaoweiXX** [comment]
> 为啥模拟器有个黑边

另外MAA之前都是正常的，升级到4.15.0beta2之后出了问题。最近MAA问题好多，你看看我最近写的这几个。

**Comment by xiaoweiXX** [comment]
> 为啥模拟器有个黑边

你看看取消全屏之后的样子
![屏幕截图 2023-04-23 193756](https://user-images.githubusercontent.com/92417243/233837553-21ee3412-d8ec-4e17-84c6-7ca5191b909b.png)

**Comment by xiaoweiXX** [comment]
突然就正常了，也不知道为啥。。。

**Comment by xiaoweiXX** [comment]
问题依然存在，每次启动MAA都有小概率触控错位，重启MAA能解决，但是还是希望能修复一下。
