### ISSUE TITLE
“MaaWpfGui.ViewModels.UI.SettingsViewModel”的类型初始值设定项引发异常。

### ISSUE THREAD

**Issue by DurianBBQ** [MaaAssistantArknights/MaaAssistantArknights#4455]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

   在 MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor(IContainer container)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)

### 日志文件

文件夹内无asst.log文件
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11303508/gui.log)

### 截图

![image](https://user-images.githubusercontent.com/131534771/233836458-da4d6e27-f473-49ce-9f53-daa64adfebdc.png)

### 还有别的吗？

mumu模拟器，WIN11系统

**Comment by ABA2396** [comment]
右下角常见问题，情况1，安装运行库

**Comment by DurianBBQ** [comment]
> 右下角常见问题，情况1，安装运行库

已重新安装了运行库，问题依然存在。

**Comment by ABA2396** [comment]
两个运行库都安装完重启了吗？截个maa所在文件夹的图看看

**Comment by ABA2396** [comment]
> 应该是[Visual C++ Redistributable]的问题

单独把exe放一个地方也会报这个错

**Comment by MistEO** [comment]
作业群里说有个 Win10RT 要自己解压放下，我们文档还没来得及更新

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10394075/win10rt.zip 试试看，解压到所有 dll 和 maa.exe 同目录下
