### ISSUE TITLE
启动MAA后所有已设置的配置被重置为全新配置

### ISSUE THREAD

**Issue by joka325** [MaaAssistantArknights/MaaAssistantArknights#4457]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA长时间后台运行后，所有自定义设置全部被重置，变为全新，而与其同时运行的另外两个MAA程序无问题，已出现于多个版本。由于用于运行的电脑为无屏幕远程操控，无法即时直接观察到问题发生，猜测与定时检查更新有关

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11304136/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11304139/gui.log)
提供了两个log，问题发生时间段必定介于23日13:00-23:30之间

### 截图

![image](https://user-images.githubusercontent.com/119752357/233849952-e564171d-438d-492e-bcda-eb5c73016ae2.png)
![image](https://user-images.githubusercontent.com/119752357/233849985-933e46ce-d7f1-4b62-a3d0-b9487a0041bc.png)

### 还有别的吗？

此电脑每天开机时自动启动三个MAA，但仅其中一个反复出现此问题。

**Comment by joka325** [comment]
第一张截图为问题发生之后，第二张为之前的备份

**Comment by joka325** [comment]
更新：发现三个MAA中另外一个在刚刚尝试更新4.15.0.rc1重新启动后发生相同问题。附它的log。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11304163/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11304166/gui.log)

**Comment by MistEO** [comment]
三个 MAA 你用的是在同一个路径下的？有没有可能是同时写配置导致文件冲突了（

**Comment by moomiji** [comment]
应该对gui.json有做备份吧？

把备份改名为gui.json.bak放gui.json同一目录，目前版本在gui.json解析失败后会自动读取gui.json.bak。

缺点就是改一次配置就得重新复制一次gui.json至gui.json.bak。
