### ISSUE TITLE
莫名的任务出错：Fight

### ISSUE THREAD

**Issue by hanyuwei70** [MaaAssistantArknights/MaaAssistantArknights#4458]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA突然提示Fight任务出错，但是log没有任何错误日志，也在正常刷关

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11304350/gui.log)
2023/4/24 1:13
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11304349/asst.log)

**Comment by Dilrevx** [comment]
我也遇到了这个错误，并且今天更新版本 15 后依然存在

感觉像是随机的，自动战斗正常刷随机 n 次之后，会在进入关卡的刚开始报错。

**Comment by ABA2396** [comment]
卡在哪个界面了？来个截图，看日志是要点击“开始行动”，但是没识别到
![image](https://user-images.githubusercontent.com/99072975/234071136-3283555a-674c-49b7-afd4-16f51a5603cf.png)
或是
![image](https://user-images.githubusercontent.com/99072975/234071226-b00e5a6c-e97e-4a59-b1c6-59cbaf175d9e.png)

**Comment by Dilrevx** [comment]
> 卡在哪个界面了？来个截图，看日志是要点击“开始行动”，但是没识别到 ![image](https://user-images.githubusercontent.com/99072975/234071136-3283555a-674c-49b7-afd4-16f51a5603cf.png) 或是 ![image](https://user-images.githubusercontent.com/99072975/234071226-b00e5a6c-e97e-4a59-b1c6-59cbaf175d9e.png)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11321594/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11321596/asst.log)

这是我的log，最后一轮错误在18:27

**Comment by MistEO** [comment]
不是的，你看这两次，识别到的是同一个坐标，可能是点了一下，画面卡了，或者网络连接。过一小会又点了第二下，但是碰巧在点之前，进到 startbutton2 的界面了，就把 2 点了

**Comment by ABA2396** [comment]
> 不是的，你看这两次，识别到的是同一个坐标，可能是点了一下，画面卡了，或者网络连接。过一小会又点了第二下，但是碰巧在点之前，进到 startbutton2 的界面了，就把 2 点了

对啊，但是“行动”两个字的坐标是没有和第二个按钮重合的

**Comment by ABA2396** [comment]
那点第二次改成固定位置好了
