### ISSUE TITLE
自动肉鸽费用足够不下干员，延迟很久

### ISSUE THREAD

**Issue by kkjj116** [MaaAssistantArknights/MaaAssistantArknights#4460]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动肉鸽费用够了，但是不会立即下干员，等好久才会下

22号更新后出的问题，之前是稳定运行的

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11304784/asst.log)

### 截图

35费才下第一个干员
![QQ截图20230424034815](https://user-images.githubusercontent.com/31801024/233862667-082386e1-0cc7-40b8-9758-82989133804c.jpg)
42费才下第一个干员
![QQ截图20230424035405](https://user-images.githubusercontent.com/31801024/233862700-104acf7b-b1b8-4908-a1ca-3710b4e26cfa.jpg)

**Comment by adolaria** [comment]
我也出现了同样的情况

**Comment by LDYang694** [comment]
我也出现了同样的情况

**Comment by junzhi-cn** [comment]
抄作业也出现了
