### ISSUE TITLE
自动更新4.15.0后程序打不开

### ISSUE THREAD

**Issue by xionglin4646** [MaaAssistantArknights/MaaAssistantArknights#4468]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动更新4.15.0程序无法打开，报错，详见截图

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11310522/asst.log)

### 截图

![QQ截图20230424204044](https://user-images.githubusercontent.com/131675869/233999260-bc29c95b-ce26-4dae-8701-63beb0c0ab83.jpg)

### 还有别的吗？

模拟器MUMU，操作系统windows 10

**Comment by fatsnk** [comment]
同样有此问题，报错和楼主一样。4.14.1版本无问题，之后的版本包括测试版和稳定版都会报错。从releases下载完整版重新安装也不行。
操作系统win10家庭版，模拟器：夜神模拟器

**Comment by ABA2396** [comment]
点右下角常见问题看过了吗？这种情况基本就是运行库不全

**Comment by pengzij** [comment]
同样问题，我测试分别使用4.14.1版本和4.15版本，4.14.1及之前版本均可以正常运行无问题。但是4.15出现同样报错。操作系统win10专业版，模拟器UU，但是和模拟器没有关系，因为软件根本无法启动。

**Comment by pengzij** [comment]
加群 重新安装一遍环境库就可以了

**Comment by MistEO** [comment]
按 [常见问题](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%BD%AF%E4%BB%B6%E6%97%A0%E6%B3%95%E8%BF%90%E8%A1%8C-%E9%97%AA%E9%80%80-%E6%8A%A5%E9%94%99) 试试，尤其是 可能性 2

![image](https://user-images.githubusercontent.com/18511905/234444882-89a38443-77de-4a8f-ac01-4ae30fb805c9.png)

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1d3a6ab9a2648daa3c3872ae81e084fa7cccdaf8 fixed
