### ISSUE TITLE
使用精1鸿雪时会不断进入技能使用界面

### ISSUE THREAD

**Issue by fangundeboll** [MaaAssistantArknights/MaaAssistantArknights#4470]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

鸿雪会使用2技能。但是2技能充能好后前方有敌方目标才能使出，于是会卡住。

**Comment by MistEO** [comment]
感觉没什么好的解决办法啊_(:з」∠)_

要不使用一次之后隔多少秒不再使用（？

**Comment by Yukari316** [comment]
我这也出现了，考虑用一技能？
