### ISSUE TITLE
美服干员无法识别

### ISSUE THREAD

**Issue by xvzhenduo** [MaaAssistantArknights/MaaAssistantArknights#4472]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

开始干员识别会自动回到主界面，然后过一会提示出错，显示已拥有0名干员(见下面截图)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11311304/asst.log)
我是退出删完了日志后复现的问题

### 截图

![image](https://user-images.githubusercontent.com/74353173/234022072-64776f5c-34b2-44e0-829a-c375e15ea989.png)
![image](https://user-images.githubusercontent.com/74353173/234022142-a7526e12-94d7-411e-9e22-695ece06c03b.png)

### 还有别的吗？

用的是实体手机，win11电脑，adb和触控模式都没有问题(可以正常刷理智)

**Comment by MistEO** [comment]
> 外服还没做呢吧）

应该加个导航就行了，其他通用的（暗示）

**Comment by xvzhenduo** [comment]
就是抄作业的时候比较痛苦，得手动编队

**Comment by Constrat** [comment]
As of v4.20.0 OperBox detection for EN has been working "decently". If you still have problems, feel free to reopen this issue.
