### ISSUE TITLE
使用视频识别生成作业后，在抄作业时第一步会先将二倍速调为一倍速，但完成之后不会调回来

### ISSUE THREAD

**Issue by Yus-git** [MaaAssistantArknights/MaaAssistantArknights#4475]
### 说说你遇到的问题？

如题，使用的是摆完挂机的作业，在提示完成作战后，实际还要挂机一段时间，但目前默认是一倍速挂机
![image](https://user-images.githubusercontent.com/61584378/234045638-8bf07e83-bd5b-4f49-862e-31e548c28dad.png)

**Comment by MistEO** [comment]
没理解，现在应该是一直一倍速不会切的

**Comment by zzXan** [comment]
“第一步会先将二倍速调为一倍速”
不理解，第一步不是从一倍速切到二倍吗？你的意思是视频识别的作业不会自动切到二倍速？

**Comment by MistEO** [comment]
是的，现在视频识别的作业应该完全没有切二倍速的功能，除非是写作业的人手动加的

**Comment by Yus-git** [comment]
> 
是的，目前是全程一倍速，因为游戏设置里【二倍速保持】所以进关卡会先切成一倍速，然后一直保持到作战结束
另外佬都1点了还不睡😘
