### ISSUE TITLE
出现闪退、无法识别的问题

### ISSUE THREAD

**Issue by wrch926** [MaaAssistantArknights/MaaAssistantArknights#4477]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在windows更新后，突然出现闪退、识别错误的问题。在使用开始唤醒、自动公招、刷理智等功能时均发生了闪退的现象。退回之前版本、重新下载完整安装包均无法解决。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11315794/asst.log)

### 截图

![2023-04-23_00-06-02-295_raw](https://user-images.githubusercontent.com/131730148/234156179-74ed3511-e435-4d3b-acfe-c4158c071a64.png)

### 还有别的吗？

使用夜神模拟器，win11操作系统

**Comment by ABA2396** [comment]
发下 gui.json

**Comment by wrch926** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11317730/gui.log)

**Comment by wrch926** [comment]
> 发下 gui.log

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11321369/gui.log)

**Comment by MistEO** [comment]
C:\Users\<用户名>\AppData\Local\CrashDumps

看看这里面有没有 dmp 文件？也发下康康

**Comment by wrch926** [comment]
> CrashDumps

没有对应的文件夹

**Comment by MistEO** [comment]
不可能没有文件夹的，把 `%APPDATA%/../Local/CrashDumps` 粘贴到文件管理器里试试

![image](https://user-images.githubusercontent.com/18511905/234339234-d774d4d5-017a-4bf5-9563-be5652f560e6.png)

**Comment by wrch926** [comment]
> 不可能没有文件夹的，把 `%APPDATA%/../Local/CrashDumps` 粘贴到文件管理器里试试
> 
> ![image](https://user-images.githubusercontent.com/18511905/234339234-d774d4d5-017a-4bf5-9563-be5652f560e6.png)

[AcerRegistrationBackGroundTask.exe.876.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11327648/AcerRegistrationBackGroundTask.exe.876.zip)

**Comment by wrch926** [comment]
> 不可能没有文件夹的，把 `%APPDATA%/../Local/CrashDumps` 粘贴到文件管理器里试试
> 
> ![image](https://user-images.githubusercontent.com/18511905/234339234-d774d4d5-017a-4bf5-9563-be5652f560e6.png)

[AcerRegistrationBackGroundTask.exe.6728.zip
[AcerRegistrationBackGroundTask.exe.8120.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11327658/AcerRegistrationBackGroundTask.exe.8120.zip)
](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11327657/AcerRegistrationBackGroundTask.exe.6728.zip)
[AcerRegistrationBackGroundTask.exe.10836.zip](https://github.com/MaaAssistantArknights/MaaAssistantArk
[AcerRegistrationBackGroundTask.exe.11260.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11327661/AcerRegistrationBackGroundTask.exe.11260.zip)
nights/files/11327660/AcerRegistrationBackGroundTask.exe.10836.zip
[AcerRegistrationBackGroundTask.exe.11724.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11327664/AcerRegistrationBackGroundTask.exe.11724.zip)
)

**Comment by MistEO** [comment]
你发的链接混在一起了，点不开

**Comment by wrch926** [comment]
> 你发的链接混在一起了，点不开。只发 maa 相关的就可以了

[AcerRegistrationBackGroundTask.exe.876.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11329085/AcerRegistrationBackGroundTask.exe.876.zip)
[AcerRegistrationBackGroundTask.exe.6728.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11329086/AcerRegistrationBackGroundTask.exe.6728.zip)
[AcerRegistrationBackGroundTask.exe.8120.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11329087/AcerRegistrationBackGroundTask.exe.8120.zip)
[AcerRegistrationBackGroundTask.exe.10836.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11329089/AcerRegistrationBackGroundTask.exe.10836.zip)
[AcerRegistrationBackGroundTask.exe.11260.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11329091/AcerRegistrationBackGroundTask.exe.11260.zip)
[AcerRegistrationBackGroundTask.exe.11724.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11329092/AcerRegistrationBackGroundTask.exe.11724.zip)

**Comment by MistEO** [comment]
只有这些吗？挺奇怪的，从日志里没看到哪里闪退了，都是正常结束退出的。你说的是 MAA 闪退还是明日方舟游戏闪退了？倒是看到几个突然从粥游戏画面崩到模拟器桌面的

**Comment by wrch926** [comment]
> 只有这些吗？挺奇怪的，从日志里没看到哪里闪退了，都是正常结束退出的。你说的是 MAA 闪退还是明日方舟游戏闪退了？倒是看到几个突然从粥游戏画面崩到模拟器桌面的

抱歉，可能是我没说清楚，是明日方舟闪退了。我自己手动的话都是正常的，但是使用maa时会出现突然闪退，回到模拟器桌面或者无法识别的情况
