### ISSUE TITLE
无法启动，闪退。

### ISSUE THREAD

**Issue by WhereNoOneArrive** [MaaAssistantArknights/MaaAssistantArknights#4479]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新至4.15.0后，启动时立刻弹出错误并无法启动，这之前的版本没有出错。
大概跟模拟器无关，当时怀疑是直接更新的问题，所以重新下载，还没有配置过。
模拟器：夜神模拟器 版本：4.15.0-win-x64

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11320433/gui.log)

### 截图

![VCRW(8$YQB1A)89T$DB37 K](https://user-images.githubusercontent.com/62683315/234221028-87054aec-b24b-4b17-a827-6b5e938c2017.png)

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10394075/win10rt.zip 试试看，解压到所有 dll 和 maa.exe 同目录下

**Comment by WhereNoOneArrive** [comment]
试过了，仍然无法打开。
弹窗报错内容大概是相同，但粗略看了一下log之后，发现dll的问题确实没了，问题变成了另一个。
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11321831/gui.log)
![image](https://user-images.githubusercontent.com/62683315/234258583-1889619f-864d-4dd8-ac78-9fd0696c697a.png)

**Comment by WhereNoOneArrive** [comment]
> 这个报错比较奇怪，确定下载的是 x64 的而不是 arm64 吗？

我确定
![image](https://user-images.githubusercontent.com/62683315/234259749-94f46a0a-7b25-4b64-98bd-c4bc4eac8097.png)

**Comment by MistEO** [comment]
再看下环境装的是不是对的，可以参照 [常见问题](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E5%8F%AF%E8%83%BD%E6%80%A7-1-%E8%BF%90%E8%A1%8C%E5%BA%93%E9%97%AE%E9%A2%98) 装一下运行库，如果还不行我也不知道是啥问题了（

**Comment by WhereNoOneArrive** [comment]
> 另外再问下，你是什么系统？

win10，x64

**Comment by WhereNoOneArrive** [comment]
> 另外再问下，你是什么系统？

WIn10，x64
另外，启动了，是VC++的问题，已解决，非常感谢

**Comment by MistEO** [comment]
如果还不行，更新到内测版看下，现在会有详细的报错，看看是什么问题
