### ISSUE TITLE
v4.15.1-alpha.1.00015.g67bb5261 自动更新后报错

### ISSUE THREAD

**Issue by CCCClaus** [MaaAssistantArknights/MaaAssistantArknights#4480]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

v4.15.1-alpha.1.00015.g67bb5261 自动更新后报错

该类型的 CollectionView 不支持从调度程序线程以外的线程对其 SourceCollection 进行的更改。

在 System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   在 System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   在 System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.AddLog(String content, String color, String weight)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.TryToStartEmulator(Boolean manual)
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.Main.AsstProxy.<<Init>b__30_1>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

![}UIA BQ%Y9T6)MY9H1T1KL0](https://user-images.githubusercontent.com/116964544/234231661-683750c0-522f-47fe-8fba-a06d896569c3.png)

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11320850/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11320852/asst.log)
[gui.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11320853/gui.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11320854/gui.log)

### 还有别的吗？

蓝叠国际版
win11

**Comment by ABA2396** [comment]
修了，把 gui.json 里的  "Start.StartEmulator": "True", 删了更新下
