### ISSUE TITLE
干员认识漏识别了

### ISSUE THREAD

**Issue by 809717330** [MaaAssistantArknights/MaaAssistantArknights#4481]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

附件太大分开上传的，全干员，未识别出干员：炎熔，泰拉大陆调查团，巡林者。

### 日志文件

[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11321769/oper.zip)
[oper1.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11321773/oper1.zip)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11321788/asst.log)

**Comment by MistEO** [comment]
试试最新内测版，还有问题吗

**Comment by 809717330** [comment]
> 
没问题了，扫了两次，都识别到了。
