### ISSUE TITLE
ADM/Windows11更新到4.15后打开报错了

### ISSUE THREAD

**Issue by cenyuyan** [MaaAssistantArknights/MaaAssistantArknights#4482]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://user-images.githubusercontent.com/111888212/234266705-36de8575-d39e-4646-b10a-b1247cd7e073.png)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11322124/gui.log)

### 截图

![image](https://user-images.githubusercontent.com/111888212/234266910-73a8204d-c4f6-42bd-94fc-0f1b0e3cb373.png)

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1d3a6ab9a2648daa3c3872ae81e084fa7cccdaf8 fixed
