### ISSUE TITLE
MAA不会下令的召唤物

### ISSUE THREAD

**Issue by ScatteredHeartSkadi** [MaaAssistantArknights/MaaAssistantArknights#4488]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在作业站里尝试了多份作业，也试过用视频攻略做的作业，发现MAA都无法使用令的召唤物

### 日志文件

无

### 截图

![image](https://user-images.githubusercontent.com/111683109/234311217-fa0af453-6673-4e28-bf8b-1962c901e9e7.png)

### 还有别的吗？

无

**Comment by lenwu1234567890** [comment]
同遇到此问题，令的召唤物和活动的特殊部署物不会部署。
