### ISSUE TITLE
肉鸽模式碰到无限回血的怪，我方干员输出又不够将其解决的情况下，无限刷肉鸽功能卡死的问题

### ISSUE THREAD

**Issue by luckythk** [MaaAssistantArknights/MaaAssistantArknights#449]
![无限循环gif](https://user-images.githubusercontent.com/104560777/167134078-d96b2fc4-eb34-4c63-bb49-6f5fa35d1199.gif)
↑ 如图，应该简单易懂，已经卡住快半小时了

战斗开始时间：
<img width="188" alt="战斗开始时间" src="https://user-images.githubusercontent.com/104560777/167134225-1740bcdd-bd19-4d53-a77a-cc5ace55432e.png">

当前提报问题时间：
<img width="63" alt="当前时间" src="https://user-images.githubusercontent.com/104560777/167134291-951e79d5-a0ed-4462-a710-fd580045819b.png">
---------------------------------------------------------------------------------------------------------------------------------------------
气死我了，
![QQ图片20220506204857](https://user-images.githubusercontent.com/104560777/167134474-42481423-e871-4805-8be0-5c743103edff.jpg)
---------------------------------------------------------------------------------------------------------------------------------------------
建议无限刷肉鸽功能加入当此战斗时间超过5 / 10分钟自动退出本次肉鸽的分支条件

**Comment by zzyyyl** [comment]
有人提过 #213，三个月了还没解决（？

**Comment by zzyyyl** [comment]
卡在同一关，容我笑一会儿（

**Comment by MistEO** [comment]
下次 ~~也不~~ 一定（

**Comment by zzyyyl** [comment]
光速修复，赞了
