### ISSUE TITLE
版本更新后无法及时获取活动关卡信息

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#4490]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

看似每次版本更新之后都会舍弃上一版本的热更新关卡信息
但是它并不能及时获取，而且没有手动拉取
在更新频繁的内测版分支上影响极大

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11323827/gui.log)

**Comment by Rbqwow** [comment]
add gui

**Comment by MistEO** [comment]
因为是这几个内测版独有的 bug，试试刚发的最新的

**Comment by Rbqwow** [comment]
> 因为是这几个内测版独有的 bug，试试刚发的最新的

修好力修好力
