### ISSUE TITLE
建议在自动肉鸽模式里可以自动切换合适的技能

### ISSUE THREAD

**Issue by kcsocrat** [MaaAssistantArknights/MaaAssistantArknights#4497]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

每次打肉鸽的时候他都默认一技能不能切换技能，这样很容易翻车

### 有什么好的想法？

我希望自动肉鸽模式里添加个自动切换技能的功能，把技能切换成那些常用的技能

### 其他内容

![image](https://user-images.githubusercontent.com/126746580/234476929-97df28e1-55af-469f-b1f1-0e494e0f095d.png)

**Comment by ABA2396** [comment]
会自动换技能点，能天使精二就换3了）

**Comment by kcsocrat** [comment]
> 会自动换技能点，能天使精二就换3了）

好的，谢谢
