### ISSUE TITLE
MAA无法启动，提示闪退

### ISSUE THREAD

**Issue by HS7097** [MaaAssistantArknights/MaaAssistantArknights#4498]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

已尝试重新安装C++，.NET Framework运行库以及在根目录中添加dll文件

### 日志文件

![image](https://user-images.githubusercontent.com/103177863/234487674-25589500-bcee-4a5a-97c5-004140d5b78a.png)

**Comment by HS7097** [comment]
> 我目前的解决方式是：
> 
> 1. 安装v4.14.1版本（即解压缩）
> 2. 启动软件（此时会自动下载更新包并提示重启软件并更新；不要按提示做）
> 3. 删除更新包
> 4. 重启软件
> 5. （在v4.14.1版本中）手动取消自动下载更新包。

退回旧版本的方法是有效的

**Comment by duan-mapleRain** [comment]
遇到的同样的问题，gui的日志如下:
[2023-04-26 20:01:04.149] <1><> ===================================
[2023-04-26 20:01:04.162] <1><> MaaAssistantArknights GUI started
[2023-04-26 20:01:04.162] <1><> Maa ENV: Production
[2023-04-26 20:01:04.164] <1><> ===================================
[2023-04-26 20:01:04.174] <1><> Failed to load configuration file, creating a new one
[2023-04-26 20:01:04.248] <1><> Unhandled exception
System.TypeInitializationException: “MaaWpfGui.ViewModels.UI.SettingsViewModel”的类型初始值设定项引发异常。 ---> System.DllNotFoundException: 无法加载 DLL“MaaCore.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.AsstGetVersion()
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor(IContainer container)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.Main.AsstProxy..ctor(IContainer container, IWindowManager windowManager)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.ViewModels.UI.RootViewModel..ctor(IContainer container)
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 Stylet.Bootstrapper`1.get_RootViewModel()
   在 Stylet.Bootstrapper`1.Launch()
   在 Stylet.BootstrapperBase.Start(String[] args)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by duan-mapleRain** [comment]
> * 下载 [win10rt.zip](https://ota.maa.plus/MaaAssistantArknights/api/binaries/win10rt.zip)，将所有 .dll 文件解压到与 MAA.exe 同目录下（要散开解压到文件夹哦，不能再套文件夹）
> 
> 这个解决方法试过了吗

试过了，并不行

**Comment by HS7097** [comment]
> * 下载 [win10rt.zip](https://ota.maa.plus/MaaAssistantArknights/api/binaries/win10rt.zip)，将所有 .dll 文件解压到与 MAA.exe 同目录下（要散开解压到文件夹哦，不能再套文件夹）
> 
> 这个解决方法试过了吗

已在问题描述中注明

**Comment by HS7097** [comment]
Operating System: Windows 10 专业工作站版 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
这是操作系统版本

**Comment by MistEO** [comment]
更新到内测版看下，现在会有详细的报错，看看是什么问题

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1d3a6ab9a2648daa3c3872ae81e084fa7cccdaf8 fixed
