### ISSUE TITLE
无掉落物识别和企鹅物流上传失败

### ISSUE THREAD

**Issue by guojunyu196** [MaaAssistantArknights/MaaAssistantArknights#451]
![uTools_1651848880571](https://user-images.githubusercontent.com/76220347/167172671-e1b99453-f465-4abf-91c3-456d2a0fcc2e.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8642132/asst.log)
3.2.1就存在，更新到最新版本也还是这样

**Comment by MistEO** [comment]
这在刷哪关，每关都这样么_(:з」∠)_

另外来张掉落识别错的界面截图（模拟器自带的截图工具的原图）

**Comment by guojunyu196** [comment]
应该是哪关都一样
![BS_PIC_2022-05-07-09-37-21](https://user-images.githubusercontent.com/76220347/167232971-a020e0fb-d554-4b51-bf76-1b2bba204da1.png)
![uTools_1651887457638](https://user-images.githubusercontent.com/76220347/167232979-575d67a4-3a58-4b48-b66c-4965073517e2.png)
![BS_PIC_2022-05-07-09-40-24](https://user-images.githubusercontent.com/76220347/167232980-a648e33f-ed0b-404a-b2d3-8bc4def82b1a.png)
![uTools_1651887633805](https://user-images.githubusercontent.com/76220347/167232981-a3d960dc-fbec-4f77-b6da-928ebfe4287d.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8644228/asst.log)

**Comment by MistEO** [comment]
左上角那个头像是啥，干扰到识别了，去掉试试~

**Comment by guojunyu196** [comment]
奥，解决了，我的问题，不好意思_(:з」∠)_
