### ISSUE TITLE
EN国际服 傀影肉鸽 开局未按设置借助战 放弃招募临时干员的问题

### ISSUE THREAD

**Issue by Joyce-Ethene** [MaaAssistantArknights/MaaAssistantArknights#4510]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![QQ图片20230427125348](https://user-images.githubusercontent.com/131970654/234854163-36629036-d536-4879-a405-11510bb1ca9a.png)
![QQ图片20230427125354](https://user-images.githubusercontent.com/131970654/234854223-f70f7a75-ca2b-4e76-9d25-c7af8d7479e3.png)

问题与肉鸽设置如上两图所示。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11343125/asst.log)

大致时间点：2023-04-27 12:51:02.943

**Comment by nguyenta1993** [comment]
I have the same issue ...

**Comment by Lancarus** [comment]
#5824
