### ISSUE TITLE
4.15版本在 Windows10 启动报错

### ISSUE THREAD

**Issue by IcyWu2023** [MaaAssistantArknights/MaaAssistantArknights#4512]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

点击MAA.exe后反馈报错，具体如图：
![图片](https://user-images.githubusercontent.com/131979748/234875985-6e53625c-9531-4ada-831b-8a325711cdf1.png)

### 日志文件

未见到生成的asst.log 文件，只有下面这一个文件。

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11343995/gui.log)

**Comment by Mo0nXc** [comment]
同样的问题，自动更新后报这个错。
删除旧版本，重新下载4.15版本，依旧报这个错。
重启系统，还是报这个错。

**Comment by Mo0nXc** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11344699/gui.log)
看了一下更新，4.15是全新UI设计，是不是UI相关资源或者代码在部分环境中有问题。

**Comment by MistEO** [comment]
按这个试试，[常见问题](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E5%8F%AF%E8%83%BD%E6%80%A7-2-%E7%B3%BB%E7%BB%9F%E7%BB%84%E4%BB%B6%E9%97%AE%E9%A2%98)

![image](https://user-images.githubusercontent.com/18511905/234907771-db22ca6e-ba84-4350-9f83-673aba404ee0.png)

**Comment by MistEO** [comment]
如果还不行，更新到内测版看下，现在会有详细的报错，看看是什么问题

**Comment by MistEO** [comment]
> 我也遇到了这个问题，目前关闭了自动更新保持了4.14版本使用。 换成内测版并放入dll文件后并没有什么变化，debug文件的报错跟楼主一致。

一筹莫展.jpg

帮忙确认下具体是哪个版本引入的问题？比如 v4.14.1 还能用，v4.15.0-beta.1 就不行了，还是说后面哪个 beta 才炸的

**Comment by moomiji** [comment]
一筹莫展.jpg+1

帮忙4.14的exe和4.15的exe互换一下看看哪个exe会报错？

**Comment by ABA2396** [comment]
> 看了一下更新，4.15是全新UI设计，是不是UI相关资源或者代码在部分环境中有问题。

自动更新的还是原来的ui，新ui是另外下的，和这个没关系

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1d3a6ab9a2648daa3c3872ae81e084fa7cccdaf8 fixed
