### ISSUE TITLE
切换干员识别界面时错误(不是识别问题)

### ISSUE THREAD

**Issue by Yoraka** [MaaAssistantArknights/MaaAssistantArknights#4513]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在进行干员识别（连接模拟器开始识别后）时切换到"一键长草"界面再切换回"识别工具"界面会显示"公招识别"界面而非"干员识别"界面

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11345050/asst.log)
2023/4/27 22:44

### 截图

![32S05T1%H}PJB2)JY4~2W19](https://user-images.githubusercontent.com/69870298/234897333-463ead51-17f2-4088-8de7-501715790a67.png)

### 还有别的吗？

蓝叠模拟器(emulator-5564)
Windows 11
MAA-v4.15.1-alpha

**Comment by ABA2396** [comment]
在识别的时候按钮被 disable 掉了，整个标签页失去了焦点，所以这个时候切换的话会自动回到第一个标签页）
