### ISSUE TITLE
干员识别数据还可以再细分一点

### ISSUE THREAD

**Issue by warningme** [MaaAssistantArknights/MaaAssistantArknights#4515]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

输出信息只有拥有和未拥有，一眼望去1-6星的干员混在一起

### 有什么好的想法？

分个类吧，至少把6星挑出来，方便周年跟半周年干员自选

**Comment by MistEO** [comment]
现在按稀有度排序了
