### ISSUE TITLE
干员识别功能出错，缺少已有干员

### ISSUE THREAD

**Issue by SHMiris** [MaaAssistantArknights/MaaAssistantArknights#4516]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

拥有239名干员，仅识别到238名，未识别到三星干员翎羽

### 日志文件

2023.4.27 23:23左右
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11345782/asst.log)

### 截图

![2023-04-27_23-23-55-018_raw](https://user-images.githubusercontent.com/131992167/234921014-37995564-25a2-497e-9145-97c0770ed50a.png)
![2023-04-27_23-23-58-350_raw](https://user-images.githubusercontent.com/131992167/234921032-37acf371-5376-42a7-9067-92b4be193a6a.png)
![2023-04-27_23-24-01-707_raw](https://user-images.githubusercontent.com/131992167/234921039-112cab12-df02-4ffd-840a-7cc858d882be.png)
![2023-04-27_23-24-05-073_raw](https://user-images.githubusercontent.com/131992167/234921045-d56efad4-4ae9-4801-b0b6-706efef7cff5.png)
![2023-04-27_23-24-08-424_raw](https://user-images.githubusercontent.com/131992167/234921052-4cdea3bb-b844-4e35-9002-27726bda1384.png)
![2023-04-27_23-24-11-740_raw](https://user-images.githubusercontent.com/131992167/234921061-114c6cd6-41c2-4f07-8259-fcce33bbb2f8.png)
![2023-04-27_23-24-15-071_raw](https://user-images.githubusercontent.com/131992167/234921066-5a6190d9-cf0b-47d5-80af-e218a6eb61b9.png)
![2023-04-27_23-24-18-394_raw](https://user-images.githubusercontent.com/131992167/234921072-6de69a80-3ce4-4c20-8099-8bad112b8749.png)
![2023-04-27_23-24-21-724_raw](https://user-images.githubusercontent.com/131992167/234921078-0dbc142c-169a-4024-aeeb-6d60a559b2f6.png)
![2023-04-27_23-24-25-023_raw](https://user-images.githubusercontent.com/131992167/234921086-3b27af1a-bad6-4769-8b74-8bca1a433df7.png)
![2023-04-27_23-24-28-341_raw](https://user-images.githubusercontent.com/131992167/234921092-e88c5b9b-f1cf-4533-9a52-6006b42f3147.png)
![2023-04-27_23-24-31-656_raw](https://user-images.githubusercontent.com/131992167/234921096-7cda9a5a-d32b-4f7c-8395-bcc05e6c9b28.png)
![2023-04-27_23-24-34-976_raw](https://user-images.githubusercontent.com/131992167/234921099-015d6986-cc08-4911-9760-c51d96fa27b9.png)
![2023-04-27_23-24-38-280_raw](https://user-images.githubusercontent.com/131992167/234921102-fb07e2f6-0da5-400c-9e4b-f9c95133b9b2.png)
![2023-04-27_23-24-41-638_raw](https://user-images.githubusercontent.com/131992167/234921106-f79a77be-2ab1-4369-8968-fef5489ef5e0.png)
![2023-04-27_23-24-44-995_raw](https://user-images.githubusercontent.com/131992167/234921112-b3bb835b-72ea-45a6-92ce-a5823f951bdb.png)
![2023-04-27_23-24-48-331_raw](https://user-images.githubusercontent.com/131992167/234921116-a5a16be2-2c5b-4750-8885-2249a808d1f1.png)
![2023-04-27_23-24-51-661_raw](https://user-images.githubusercontent.com/131992167/234921120-e6971954-d7d3-4c88-a655-f6f4420564d9.png)
![2023-04-27_23-24-54-963_raw](https://user-images.githubusercontent.com/131992167/234921126-dd84f54c-8eb8-4ca2-a9b6-9dcf863c9248.png)
![2023-04-27_23-24-58-282_raw](https://user-images.githubusercontent.com/131992167/234921129-cbbd5530-43fd-46fa-a07a-461a7b9fc4e2.png)

### 还有别的吗？

雷电模拟器9.0.37
win10 x64

**Comment by MistEO** [comment]
干员识别内测版修了一个很严重的bug，再下一个正式版如果还有问题麻烦再提一下
