### ISSUE TITLE
悖论模拟无法自动战斗

### ISSUE THREAD

**Issue by yukinatsu** [MaaAssistantArknights/MaaAssistantArknights#4520]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

拖入悖论模拟的自动文件之后显示文件错误 请更新版本 更新内测版后依旧存在问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11347428/asst.log)
26日下午或晚上

### 截图

![图片](https://user-images.githubusercontent.com/132012930/234978289-efb7ce4c-d8d5-442a-b708-5f5e816dae37.png)

### 还有别的吗？

mumu模拟器 win11 22h2 9750h+1660ti laptop

**Comment by MistEO** [comment]
这个文件也发下看看，可以压缩下
