### ISSUE TITLE
基建宿舍bug

### ISSUE THREAD

**Issue by HMZyueshen** [MaaAssistantArknights/MaaAssistantArknights#4525]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建宿舍只进驻一个人

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11349878/asst.log)

### 截图

https://user-images.githubusercontent.com/106477016/235055267-688886be-a42b-43bf-a1bd-906dccb9a649.mp4

**Comment by MistEO** [comment]
内测版的 bug，修过了，更新一下
