### ISSUE TITLE
保全派驻卡住

### ISSUE THREAD

**Issue by 809717330** [MaaAssistantArknights/MaaAssistantArknights#4526]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图卡在这不动了，怎么重开都没反应，前面3关还能停止脚本 再开始接着打的，到这关撤底不动了。
替换过 ADB也是一样。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11351042/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/121223842/235083220-d603fc0b-1473-4bc8-9067-855afb8a10e7.png)

**Comment by MistEO** [comment]
内测版的 bug，修过了，更新一下
