### ISSUE TITLE
基建训练室换班问题

### ISSUE THREAD

**Issue by Cyric5** [MaaAssistantArknights/MaaAssistantArknights#4532]
### 说说你遇到的问题？

基建训练室是否能够单独设置不换班，有时候没素材了把艾妮丽换下去休息了时间减半就没了。

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/235197656-6af244f1-6e8e-41a3-b10c-d7624d907749.png)
![image](https://user-images.githubusercontent.com/99072975/235197806-c90cbff8-8f68-4029-b569-1e3c7a5ad4b0.png)
