### ISSUE TITLE
任务还未结束时就显示Link Start按钮而非停止

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#4533]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题 如图
大抵是内测版问题 此时点击会提示未知错误 再点击正常开始任务
v4.15.2-alpha.1.d103.g781bf240

### 日志文件

见了鬼了怎么传不上来
看看下面的comment

### 截图

![X1L9A3 4NS)6~X@Q_P`RA{X](https://user-images.githubusercontent.com/55343783/235196113-9e17d78d-a768-48f7-a5e9-f0ace878d0cc.png)

**Comment by Rbqwow** [comment]
add gui

**Comment by Rbqwow** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11355268/gui.log)
[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11355278/asst.-.log)
o想起来了 任务还没结束 应该是被占用了

**Comment by Rbqwow** [comment]
🤔前一个或者几个ci应该就有这个问题了
没注意是具体哪个版本

**Comment by ABA2396** [comment]
启动设置里有开什么吗

**Comment by Rbqwow** [comment]
> 启动设置里有开什么吗

复选框都没选 模拟器路径和参数填了

**Comment by ABA2396** [comment]
写漏了.jpg
果然内测版还是有用的（）
