### ISSUE TITLE
基建第二宿舍自动换班失败

### ISSUE THREAD

**Issue by zzXan** [MaaAssistantArknights/MaaAssistantArknights#4535]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

一天4换，前2班为同样的基建干员。第2宿舍换班的时候，选上爱丽丝或者车尼尔还会再选上Lancer-2（不知道为什么会选上）之后往右划到最后也不会停。就这样卡在滑动过程中

后续测试中发现第二宿舍干员排序设置没有重置，可能导致这个问题
解决方法是排班把车尼尔和爱丽丝进驻同一宿舍
![image](https://user-images.githubusercontent.com/99358986/235319185-db180e8c-69f3-4b62-953f-61793c32e164.png)
![image](https://user-images.githubusercontent.com/99358986/235318136-d00966ee-729d-415d-a804-96c30716872f.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11355470/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/99358986/235318193-1656e111-4f62-4c29-8647-34619f939f1b.png)

**Comment by MistEO** [comment]
这个版本有问题，已经修过了，更新下试试~

**Comment by zzXan** [comment]
看来最新版没解决，如果需要排班的json测试我再发群里
