### ISSUE TITLE
MAA更新后闪退

### ISSUE THREAD

**Issue by mzldyt** [MaaAssistantArknights/MaaAssistantArknights#4536]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述
更新后MAA报错并闪退，版本号V4.15.2-alpha
MAA 遇到了问题
外部组件发生异常。
解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.SEHException (0x80004005): 外部组件发生异常。
   在 MaaWpfGui.Main.AsstProxy.AsstLoadResource(Byte* dirname)
   在 MaaWpfGui.Main.AsstProxy.AsstLoadResource(String dirname)
   在 MaaWpfGui.Main.AsstProxy.LoadResource()
   在 MaaWpfGui.Main.AsstProxy.Init()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.RootViewModel.<InitProxy>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11355966/asst.log)

**Comment by mzldyt** [comment]
> ### 在提问之前...
> * [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
> * [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是"一个建议"、"卡住了"等
> * [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
> 
> ### 问题描述
更新后MAA报错并闪退，版本号V4.15.2-alpha
> MAA 遇到了问题 外部组件发生异常。 解决方案 出现未知错误 详细信息 System.Runtime.InteropServices.SEHException （0x80004005）： 外部组件发生异常。 在 MaaWpfGui.Main.AsstProxy.AsstLoadResource（Byte* dirname） 在 MaaWpfGui.Main.AsstProxy.AsstLoadResource（String dirname） 在 MaaWpfGui.Main.AsstProxy.LoadResource（） 在 MaaWpfGui.Main.AsstProxy.Init（） 在 System.Threading.Tasks.Task.Execute（） --- 引发异常的上一位置中堆栈跟踪的末尾 --- 在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw（） 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification（Task task） 在 MaaWpfGui.ViewModels.UI.RootViewModel.d__2.MoveNext（） --- 引发异常的上一位置中堆栈跟踪的末尾 --- 在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw（） 在 System.Windows.Threading.ExceptionWrapper.InternalRealCall（Delegate callback， Object args， Int32 numArgs） 在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen（Object source， Delegate callback， Object args， Int32 numArgs， Delegate catchHandler）
> 
> ### 日志文件
> [助理.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11355966/asst.log)
> 
> ### 截图
> _无响应_
> 
> ### 还有别的吗？
> _无响应_

**Comment by MistEO** [comment]
修过了，试试更新下，但可能得手动下载了（
