### ISSUE TITLE
adb连接成功但无法正常执行任务，初步判断应该是adb截图命令处出错了

### ISSUE THREAD

**Issue by A-n-k-a** [MaaAssistantArknights/MaaAssistantArknights#4539]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

运行MAA的设备：Windows11
用于连接的设备：vivo手机
安卓版本：5.1
连接方式：usb
adb版本信息：
```
Android Debug Bridge version 1.0.41
Version 34.0.1-9680074
Installed as C:\Users\20742\Downloads\MAA-v4.15.1-win-x64\platform-tools\adb.exe
```
问题的具体表现：
点击“Link Start”后，MAA成功命令手机启动了明日方舟游戏主程序，但之后就没有操作了，再过一会儿就显示任务出错。
我又尝试过使用仓库识别，能连接成功，但过了很久，MAA滑动了一下屏幕，之后就显示任务出错。
我大致看了一下日志，发现
`C:\Users\20742\Downloads\MAA-v4.15.1-win-x64\platform-tools\adb.exe -s AYYSU8PZ99999999 exec-out "screencap | gzip -1"`
在执行时可能出现了未知错误，因为日志显示`OcrPack::recognize | proc: []`表明Ocr没有识别出任何结果，而后我在depot和roguelike文件夹中发现了输出的截图：
![2023-04-29_02-56-02-428_raw](https://user-images.githubusercontent.com/47747022/235236107-b7f1efd9-ef9c-4e80-a9d1-b56e74cd3600.png)depot文件夹中的截图2023-04-29_02-56-02-428_raw.png

![2023-04-29_02-49-14-196_raw](https://user-images.githubusercontent.com/47747022/235236435-86adab66-4bec-459e-af93-c5472c715494.png)roguelike文件夹中的截图2023-04-29_02-49-14-196_raw.png

可以推测，这应该就是出错的截图，而截图的问题导致了之后的任务无法进行。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11356773/asst.log)

### 截图

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11356795/debug.zip)
![屏幕截图 2023-04-29 025033](https://user-images.githubusercontent.com/47747022/235242090-201a0d5b-c5c3-4e34-a7e6-f0f36ca6c819.png)

### 还有别的吗？

我有尝试过adb截图，但结果令人意外。
在cmd中执行`adb exec-out screencap -p > 1.png`可以正常输出截图：
![1](https://user-images.githubusercontent.com/47747022/235238963-ebf07cc6-c85f-40c9-ab6c-5b0c7b60bc37.png)
上面这张图是仓库识别之前我手动用cmd截的图
进行仓库识别之后，虽然显示任务出错，但MAA确实滑动了屏幕：
![2](https://user-images.githubusercontent.com/47747022/235239261-e0233278-d122-4440-b6b8-6dba223690e6.png)
这张图是仓库识别显示任务出错后我手动用cmd截的图
然而在PowerShell中执行同样的命令，得到的图片有大小，但打不开，和这个issue里面的情况基本一致：https://github.com/mzlogin/awesome-adb/issues/33

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/235246615-9dcc9fdc-1ee0-4fe3-860d-6d8760103c64.png)

左边是出错的第一张图，右边是正常的第一张图，我不知道这两张图对应的画面是不是一模一样，但是从数据来看文件头似乎没什么问题。

可以试试把 `resource/config.json` 里对应的使用 gzip 截图的那行命令改成空字符串或者别的什么错误的命令（会自动 fallback 到 screencap -p 的截图方式），这样看看能不能用

**Comment by horror-proton** [comment]
我记得之前出现过这种情况, 当时是 dumpsys 输出的屏幕大小和实际的截图大小不一样 (比如行列颠倒了)

**Comment by A-n-k-a** [comment]
> ![image](https://user-images.githubusercontent.com/18511905/235246615-9dcc9fdc-1ee0-4fe3-860d-6d8760103c64.png)
> 
> 左边是出错的第一张图，右边是正常的第一张图，我不知道这两张图对应的画面是不是一模一样，但是从数据来看文件头似乎没什么问题。
> 
> 可以试试把 `resource/config.json` 里对应的使用 gzip 截图的那行命令改成空字符串或者别的什么错误的命令（会自动 fallback 到 screencap -p 的截图方式），这样看看能不能用

似乎有点效果，但没完全好，截图的方向不对。请看debug中输出的截图：
![2023-04-29_21-34-28-005_raw](https://user-images.githubusercontent.com/47747022/235305789-ee9e27cc-4a69-4192-aae1-4f3821ba2acc.png)
而且，我的手机屏幕原生分辨率是1920×1080，但这个截图是1280×720的
我修改后的`resource/config.json`是这样的（GitHub居然不允许上传json文件，我只好打包成zip）您看看有没有问题
[config.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11359290/config.zip)
另外，日志我也上传一下，您重点看看2023年4月29日21点以后的部分
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11359300/asst.log)

**Comment by A-n-k-a** [comment]
> 我记得之前出现过这种情况, 当时是 dumpsys 输出的屏幕大小和实际的截图大小不一样

我这确实发生了debug输出截图的大小和手机屏幕分辨率大小不同的情况
debug输出截图：1280×720
cmd中执行`adb exec-out screencap -p > 1.png`的截图：1920×1080
手机屏幕分辨率大小：1920×1080

**Comment by MistEO** [comment]
720p 是 maa 压的，这个无所谓。

横屏可能是分辨率解析错了，试一下这个命令看看会输出什么

```cmd
C:\Users\20742\Downloads\MAA-v4.15.1-win-x64\platform-tools\adb.exe -s AYYSU8PZ99999999 shell dumpsys window displays
```

**Comment by A-n-k-a** [comment]
> 720p 是 maa 压的，这个无所谓。
> 
> 横屏可能是分辨率解析错了，试一下这个命令看看会输出什么
> 
> ```batchfile
> C:\Users\20742\Downloads\MAA-v4.15.1-win-x64\platform-tools\adb.exe -s AYYSU8PZ99999999 shell dumpsys window displays
> ```

`Dump time : 2023年4月29日 下午10:03:03
WINDOW MANAGER DISPLAY CONTENTS (dumpsys window displays)
  Display: mDisplayId=0
    init=1080x1920 480dpi cur=1920x1080 app=1920x1080 rng=1080x1011-1920x1851
    deferred=false layoutNeeded=false
  mStacks[1]1
    mStackId=1
    mDeferDetach=false
    {taskId=1267 appTokens=[AppWindowToken{14a18402 token=Token{25d0914d ActivityRecord{2c6b511 u0 com.tencent.mobileqq/.activity.SplashActivity t1267}}}] mdr=false}
    {taskId=1268 appTokens=[AppWindowToken{1fa07872 token=Token{bb9d17d ActivityRecord{74b5241 u0 com.tencent.mobileqq/.mini.appbrand.ui.AppBrandUI t1268}}}] mdr=false}
    {taskId=1269 appTokens=[AppWindowToken{892570a token=Token{26542b75 ActivityRecord{d1e32ac u0 com.baidu.homework/.activity.index.IndexActivity t1269}}}, AppWindowToken{11c2551d token=Token{1a39d9f4 ActivityRecord{9b19fc7 u0 com.baidu.homework/.activity.search.whole.PicManySearchActivity t1269}}}] mdr=false}
    {taskId=1277 appTokens=[AppWindowToken{3f23cb84 token=Token{bcd1d97 ActivityRecord{3d7630bb u0 com.hypergryph.arknights/com.u8.sdk.U8UnityContext t1277}}}] mdr=false}
  mStacks[0]0
    mStackId=0
    mDeferDetach=false
    {taskId=1243 appTokens=[AppWindowToken{3c599886 token=Token{17a9d561 ActivityRecord{ef21fe5 u0 com.bbk.launcher2/.Launcher t1243}}}] mdr=false}

  Application tokens in top down Z order:
  mStackId=1
    mTaskId=1277
    Activity #0 AppWindowToken{3f23cb84 token=Token{bcd1d97 ActivityRecord{3d7630bb u0 com.hypergryph.arknights/com.u8.sdk.U8UnityContext t1277}}}:
      windows=[Window{1a3d8f8 u0 com.hypergryph.arknights/com.u8.sdk.U8UnityContext}]
      windowType=2 hidden=false hasVisible=true
      app=true voiceInteraction=false
      allAppWindows=[Window{1a3d8f8 u0 com.hypergryph.arknights/com.u8.sdk.U8UnityContext}, Window{34da4e2f u0 SurfaceView}]
      groupId=1277 appFullscreen=true requestedOrientation=0
      hiddenRequested=false clientHidden=false willBeHidden=false reportedDrawn=true reportedVisible=true
      numInterestingWindows=1 numDrawnWindows=1 inPendingTransaction=false allDrawn=true (animator=true)
      startingData=null removed=false firstWindowDrawn=true mDeferRemoval=false
    mTaskId=1269
    Activity #1 AppWindowToken{11c2551d token=Token{1a39d9f4 ActivityRecord{9b19fc7 u0 com.baidu.homework/.activity.search.whole.PicManySearchActivity t1269}}}:
      windows=[]
      windowType=2 hidden=true hasVisible=true
      app=true voiceInteraction=false
      groupId=1269 appFullscreen=true requestedOrientation=1
      hiddenRequested=true clientHidden=true willBeHidden=false reportedDrawn=false reportedVisible=false
      numInterestingWindows=1 numDrawnWindows=1 inPendingTransaction=false allDrawn=true (animator=true)
    Activity #0 AppWindowToken{892570a token=Token{26542b75 ActivityRecord{d1e32ac u0 com.baidu.homework/.activity.index.IndexActivity t1269}}}:
      windows=[]
      windowType=2 hidden=true hasVisible=true
      app=true voiceInteraction=false
      groupId=1269 appFullscreen=true requestedOrientation=1
      hiddenRequested=true clientHidden=true willBeHidden=false reportedDrawn=false reportedVisible=false
      numInterestingWindows=1 numDrawnWindows=1 inPendingTransaction=false allDrawn=true (animator=true)
    mTaskId=1268
    Activity #0 AppWindowToken{1fa07872 token=Token{bb9d17d ActivityRecord{74b5241 u0 com.tencent.mobileqq/.mini.appbrand.ui.AppBrandUI t1268}}}:
      windows=[]
      windowType=2 hidden=true hasVisible=true
      app=true voiceInteraction=false
      groupId=1268 appFullscreen=true requestedOrientation=1
      hiddenRequested=true clientHidden=true willBeHidden=false reportedDrawn=false reportedVisible=false
      numInterestingWindows=1 numDrawnWindows=1 inPendingTransaction=false allDrawn=true (animator=true)
    mTaskId=1267
    Activity #0 AppWindowToken{14a18402 token=Token{25d0914d ActivityRecord{2c6b511 u0 com.tencent.mobileqq/.activity.SplashActivity t1267}}}:
      windows=[]
      windowType=2 hidden=true hasVisible=true
      app=true voiceInteraction=false
      groupId=1267 appFullscreen=true requestedOrientation=1
      hiddenRequested=true clientHidden=true willBeHidden=false reportedDrawn=false reportedVisible=false
      numInterestingWindows=1 numDrawnWindows=1 inPendingTransaction=false allDrawn=true (animator=true)
  mStackId=0
    mTaskId=1243
    Activity #0 AppWindowToken{3c599886 token=Token{17a9d561 ActivityRecord{ef21fe5 u0 com.bbk.launcher2/.Launcher t1243}}}:
      windows=[Window{11fdd772 u0 com.bbk.launcher2/com.bbk.launcher2.Launcher}]
      windowType=2 hidden=true hasVisible=true
      app=true voiceInteraction=false
      allAppWindows=[Window{11fdd772 u0 com.bbk.launcher2/com.bbk.launcher2.Launcher}]
      groupId=1243 appFullscreen=true requestedOrientation=1
      hiddenRequested=true clientHidden=true willBeHidden=false reportedDrawn=false reportedVisible=false
      numInterestingWindows=1 numDrawnWindows=0 inPendingTransaction=false allDrawn=false (animator=false)
      startingData=null removed=false firstWindowDrawn=true mDeferRemoval=false`

**Comment by MistEO** [comment]
这个是你打开明日方舟然后输出的？还是说在桌面竖屏状态下。

试试在这个状态先连接，开始执行了再点开明日方舟行不行

**Comment by A-n-k-a** [comment]
明日方舟在前台，只是像QQ这些应用后台没清。
现在我把后台全部清完再执行一次。
Dump time : 2023年4月29日 下午10:21:13
WINDOW MANAGER DISPLAY CONTENTS (dumpsys window displays)
  Display: mDisplayId=0
    init=1080x1920 480dpi cur=1920x1080 app=1920x1080 rng=1080x1011-1920x1851
    deferred=false layoutNeeded=false
  mStacks[1]1
    mStackId=1
    mDeferDetach=false
    {taskId=1277 appTokens=[AppWindowToken{3f23cb84 token=Token{bcd1d97 ActivityRecord{3d7630bb u0 com.hypergryph.arknights/com.u8.sdk.U8UnityContext t1277}}}] mdr=false}
  mStacks[0]0
    mStackId=0
    mDeferDetach=false
    {taskId=1243 appTokens=[AppWindowToken{3c599886 token=Token{17a9d561 ActivityRecord{ef21fe5 u0 com.bbk.launcher2/.Launcher t1243}}}] mdr=false}

  Application tokens in top down Z order:
  mStackId=1
    mTaskId=1277
    Activity #0 AppWindowToken{3f23cb84 token=Token{bcd1d97 ActivityRecord{3d7630bb u0 com.hypergryph.arknights/com.u8.sdk.U8UnityContext t1277}}}:
      windows=[Window{1a3d8f8 u0 com.hypergryph.arknights/com.u8.sdk.U8UnityContext}]
      windowType=2 hidden=false hasVisible=true
      app=true voiceInteraction=false
      allAppWindows=[Window{1a3d8f8 u0 com.hypergryph.arknights/com.u8.sdk.U8UnityContext}, Window{34da4e2f u0 SurfaceView}]
      groupId=1277 appFullscreen=true requestedOrientation=0
      hiddenRequested=false clientHidden=false willBeHidden=false reportedDrawn=true reportedVisible=true
      numInterestingWindows=1 numDrawnWindows=1 inPendingTransaction=false allDrawn=true (animator=true)
      startingData=null removed=false firstWindowDrawn=true mDeferRemoval=false
  mStackId=0
    mTaskId=1243
    Activity #0 AppWindowToken{3c599886 token=Token{17a9d561 ActivityRecord{ef21fe5 u0 com.bbk.launcher2/.Launcher t1243}}}:
      windows=[Window{11fdd772 u0 com.bbk.launcher2/com.bbk.launcher2.Launcher}]
      windowType=2 hidden=true hasVisible=true
      app=true voiceInteraction=false
      allAppWindows=[Window{11fdd772 u0 com.bbk.launcher2/com.bbk.launcher2.Launcher}]
      groupId=1243 appFullscreen=true requestedOrientation=1
      hiddenRequested=true clientHidden=true willBeHidden=false reportedDrawn=false reportedVisible=false
      numInterestingWindows=1 numDrawnWindows=0 inPendingTransaction=false allDrawn=false (animator=false)
      startingData=null removed=false firstWindowDrawn=true mDeferRemoval=false

**Comment by MistEO** [comment]
这两次输出和之前 asst.log 日志里看到的不一致。那日志是在竖屏的时候连接，再切到游戏里横屏的？_(:з」∠)_

**Comment by A-n-k-a** [comment]
> 这两次输出和之前 asst.log 日志里看到的不一致。那日志是在竖屏的时候连接，再切到游戏里横屏的？_(:з」∠)_

是的，手机在竖屏桌面状态下，在MAA里点link start之后，MAA自动启动了明日方舟

**Comment by A-n-k-a** [comment]
这样说的话，是不是应该先切换横屏再启动MAA。
我再试试。

**Comment by A-n-k-a** [comment]
额，看来还是不行。
这次我就是手动登录游戏，再点link start，MAA里面的报错不变，debug输出的截图还是这样：
![2023-04-29_23-10-02-991_raw](https://user-images.githubusercontent.com/47747022/235310168-2dc6bab7-ed85-4922-b8de-33591c6b3079.png)

这是日志：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11359490/asst.log)

**Comment by A-n-k-a** [comment]
我突然发现一个问题：无论手机是竖屏模式还是横屏模式，adb得到的截图总是竖屏的，或许这就是出现上面图中那个现象的原因。
请问这个有没有解决办法呢？

**Comment by MistEO** [comment]
解决就是硬编码加一段判断，但我不理解为什么图是横的_(:з」∠)_

**Comment by A-n-k-a** [comment]
我在cmd中执行`adb exec-out screencap -p > 1.png`时，得到的截图其实是竖着的，就像这样：
![1](https://user-images.githubusercontent.com/47747022/235312571-9a2e91db-5a95-4ebf-be19-b7fb657bad0a.png)
之前我忽略了这个问题，我上传图片之前把图片手动旋转到了正确的方向。
至于为什么MAA截出来的图虽然是横的，但很别扭，我想是因为MAA判断了屏幕方向，它认为屏幕现在是横的，事实上屏幕确实是横的，但是adb截图无论横屏竖屏均为竖向的，这就导致了矛盾，而MAA并不知道，所以它就像在PowerPoint里面拉伸图片一样，强制把竖着的图片拉伸成了横屏的比例（即把9:16硬拉成16:9），于是就出现了bug。
就像这样：
![image](https://user-images.githubusercontent.com/47747022/235313109-b82765e1-3b1e-46b2-91d1-758c4628edba.png)
左侧是adb截图原图，右侧是MAA得到的图

**Comment by A-n-k-a** [comment]
您看能不能添加一个设置项来手动设置截图的旋转方向，或者您看您还有什么更好的解决方案

**Comment by A-n-k-a** [comment]
有这样一个方法可以在adb截图后旋转图片：
`adb exec-out screencap -p > 1.png && magick convert 1.png -rotate 90 1.png`
请问能不能通过修改`resource/config.json`达到这样的效果呢？

**Comment by MistEO** [comment]
因为图片本身是错误的（方向不对），如果仅看长宽来判断旋转，也没法知道是要顺时针转还是逆时针转，还要再多加一些识别等的逻辑。个例问题，我们暂时不打算针对性适配。

config 的话讲简单点我就就是 system(cmd), 然后获取了一下输出。如果能做到一行命令旋转之后再把图片走 stdout 打印出来，应该可以做到，或许可以试试？

**Comment by A-n-k-a** [comment]
`adb exec-out screencap -p > 1.png && magick convert 1.png -rotate 90 1.png`
cmd中，这个命令就是获取截图并旋转（后面还可以通过加&&来在同一行执行更多命令）

那个stdout我不太了解，可以指点一下吗？

我已做了以下尝试：
将原版config中的`"screencapEncode": "[Adb] -s [AdbSerial] exec-out screencap -p"`
改为`"screencapEncode": "[Adb] -s [AdbSerial] exec-out screencap -p > screenshot.png && magick convert screenshot.png -rotate 90 screenshot.png"`
依旧没有效果，甚至还发生了MAA程序异常退出。

magick旋转图片需要指定目标文件，而原版config中的`[Adb] -s [AdbSerial] exec-out screencap -p`没有指定目标文件夹和输出名称，所以我不知道该如何插入旋转图片的指令，您看看应该怎么做
magick提供的图片旋转指令用法：
`magick convert input.jpg -rotate 90 output.jpg`
其中，`input.jpg`表示原始图片文件名，`output.jpg`表示旋转后的图片文件名。`-rotate`参数指定旋转角度。

**Comment by MistEO** [comment]
stdout 可以理解就为就是 printf 的内容，直接输出就行。原版的 `adb exec-out screencap -p` 你可以试下效果，会在控制台里输出一大堆乱七八糟的内容（其实就是图片的原始数据），不走磁盘 IO 的

**Comment by A-n-k-a** [comment]
呃...查了很多资料，也试过很多方法，都没能把图片转到stdout...最终还是去用模拟器了
不过还是谢谢你～

**Comment by horror-proton** [comment]
`screencap -p | magick convert PNG:- -rotate 90 PNG:-` 可以吗, ~~或者直接 && cat 1.png 也不是不行~~ (

**Comment by A-n-k-a** [comment]
> `screencap -p | magick convert PNG:- -rotate 90 PNG:-` 可以吗, ~或者直接 && cat 1.png 也不是不行~ (

magick convert这个命令我试过，似乎会卡住（不是卡成未响应那种，而是很长时间都没有文件输出，cmd中没有回显，也不接受下一条指令）

至于cat命令，Windows原生不是不支持嘛，再者，Linux中的cat好像是会以二进制数据模式输出图片数据，而不是那个stdout输出吧（具体我也不了解）

**Comment by MistEO** [comment]
> Linux中的cat好像是会以二进制数据模式输出图片数据

就是要这样的，这个命令是跑在手机里的，安卓里应该有 cat
