### ISSUE TITLE
基建换班将龙舌兰，巫恋，卡夫卡换成了柏喙，巫恋，卡夫卡

### ISSUE THREAD

**Issue by s726-star** [MaaAssistantArknights/MaaAssistantArknights#454]
！！！请尽可能详细的描述你遇到的问题，并附上助手软件目录下的 `asst.log` 日志文件！！！

！！！日志文件是可以直接拖拽进来的，没有日志文件的 bug 反馈我会直接关掉！！！

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8644201/asst.log)

龙舌兰心情值是高于宿舍入驻心情阈值的，但是龙舌兰去了宿舍，贸易站换成了柏喙

**Comment by MistEO** [comment]
是偶尔会这样么，还是每次都是？

**Comment by s726-star** [comment]
基本上一天一次，我一天基建换班好几次

**Comment by charles037** [comment]
同样的问题，偶尔就会发现（也有可能发现了没留意）
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8839847/asst.log)
)

**Comment by yyyy52** [comment]
心情都大于30%时经常将(龙舌兰，巫恋，柏喙）换成(空弦，巫恋，柏喙）
[asst_0605.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8840197/asst_0605.log)
