### ISSUE TITLE
繁中服基建無法換班

### ISSUE THREAD

**Issue by qew4476** [MaaAssistantArknights/MaaAssistantArknights#4541]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建無法換班，只能自動收菜，而且會無止盡地循環。
收菜->進入製造站->點開幹員頁面->退出->收菜
(重複四次)
到貿易站開始，之後的流程卻又是正常換班了

繁中服、Hyper-V版本

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11357828/asst.log)
2023-04-29 07:23:04.681

**Comment by quark-mac** [comment]
干员心情阈值有调好吗？心情足够不会换班的
调10%一般没有瞎换的问题，快没心情了才换

**Comment by qew4476** [comment]
> 干员心情阈值有调好吗？心情足够不会换班的 调10%一般没有瞎换的问题，快没心情了才换

之前是三個幹員疲勞0，他都沒換，今天試不曉得為什麼突然好了。謝謝。
這個程式真的幫助我很大……如果要自己換基建我是沒力氣回坑的……
