### ISSUE TITLE
设置界面添加搜索框

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#4542]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

设置项越来越多 不利于查找

### 有什么好的想法？

侧边栏上面塞个小框框
最好支持首字母 拼音啥的(

**Comment by Rbqwow** [comment]
add gui

**Comment by ABA2396** [comment]
~~猪脑过载~~

**Comment by Rbqwow** [comment]
设置拆分了 基本用不上力
