### ISSUE TITLE
手动输入关卡识别错误

### ISSUE THREAD

**Issue by Inkpear** [MaaAssistantArknights/MaaAssistantArknights#4543]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

手动输入关卡名字识别错误，经过个人测试，若是在备选关卡中的手动输入的关卡名，那么会无法识别，例如我首选是剿灭模式，备选了11-7-HARD，剩余理智为1-7，那么略过了剿灭后，会直接进入1-7或者我关闭了剩余理智使用，那么略过剿灭模式后就会直接显示任务完成， 之后我又在首选的关卡中输入了11-7，可以正常识别。测试完成后就发现，在首选和剩余理智的关卡选择中，输入手动关卡名都可以被正确的识别到，但是若是在备选关卡中手动输入关卡名，就无法得到正确识别，从而直接被略过。
MAA版本号为4.15.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11358334/asst.log)

### 还有别的吗？

蓝叠模拟器国际版，Windows11

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/235301074-8d5bd57c-47f0-4526-b540-f6cecdd57cd4.png)
![image](https://user-images.githubusercontent.com/99072975/235301155-d4d705a6-d13e-4461-a156-3a00da2acb79.png)
我这里都是预期行为啊，有什么问题吗

**Comment by Inkpear** [comment]
但我这里确实是直接转跳1-7， 我试着重新下载一遍MAA试试
![image](https://user-images.githubusercontent.com/91143440/235307640-837a8bb9-6507-4668-a054-dca040d3633c.png)

@ABA2396

**Comment by Inkpear** [comment]
我重新下载了MAA测试，在备选关卡中输入11-7-HARD 依旧不会转跳， 但是输入12-17-HARD却会转跳到12-17 ,我也尝试了同为12章的其他关卡，同样不会转跳, 12-17是备选的关卡中预设关卡之一, 似乎是只有预设中的关卡才会转跳。@ABA2396

**Comment by ABA2396** [comment]
还真没想到会有这个问题）
