### ISSUE TITLE
偶尔公招识别错误加异常跳过任务

### ISSUE THREAD

**Issue by JiGe-indigo** [MaaAssistantArknights/MaaAssistantArknights#4544]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![IRVT9MA5P ~5J N0 7~RJQ2](https://user-images.githubusercontent.com/131613347/235286115-223893b3-ca88-41fd-a9ed-87e70f77ea1c.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11358475/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11358476/asst.bak.log)

**Comment by MistEO** [comment]
内测版的 bug，修过了，更新下试试
