### ISSUE TITLE
打开[MAA.exe]运行程序时报错[System.OutOfMemoryException]，无法正常启动

### ISSUE THREAD

**Issue by zZlackZz** [MaaAssistantArknights/MaaAssistantArknights#4549]
## 问题描述：
在打开MAA.exe时弹出错误提示[System.OutOfMemoryException]，见下图
![image](https://user-images.githubusercontent.com/44299454/235293743-ae751172-2a9e-4315-b159-a8c264c61051.png)

## 补充说明
1. 本机物理内存16G，启用前内存仅占用42%
![image](https://user-images.githubusercontent.com/44299454/235293894-fbad7eed-0c5f-47f1-999c-09a6179d3999.png)
2. debug仅生成[gui.log]文件
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11358728/gui.log)
3. 下载的版本为[MAA-v4.15.0-win-x64], 启动目录无中文
4. 已经安装VC和NET4.8
5. win10rt文件夹下所有文件均已复制到maa主文件夹下

**Comment by Black1312** [comment]
https://ghpym.lanzoui.com/iOa9I0rzat2j解压，运行，安装，无需重启电脑，再次尝试打开MAA。请告知操作后结果

**Comment by zZlackZz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zZlackZz** [comment]
> [https://ghpym.lanzoui.com/iOa9I0rzat2j解压，运行，安装，无需重启电脑，再次尝试打开MAA。请告知操作后结果](https://ghpym.lanzoui.com/iOa9I0rzat2j%E8%A7%A3%E5%8E%8B%EF%BC%8C%E8%BF%90%E8%A1%8C%EF%BC%8C%E5%AE%89%E8%A3%85%EF%BC%8C%E6%97%A0%E9%9C%80%E9%87%8D%E5%90%AF%E7%94%B5%E8%84%91%EF%BC%8C%E5%86%8D%E6%AC%A1%E5%B0%9D%E8%AF%95%E6%89%93%E5%BC%80MAA%E3%80%82%E8%AF%B7%E5%91%8A%E7%9F%A5%E6%93%8D%E4%BD%9C%E5%90%8E%E7%BB%93%E6%9E%9C)

您好，上述文件安装后，重新打开MAA，提示无变化，更新后的log与截图建下方，谢谢
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11358925/gui.log)
![image](https://user-images.githubusercontent.com/44299454/235297968-9782174a-b0a3-4cdf-97e0-2c5e6e4900a9.png)

**Comment by MistEO** [comment]
第一次见到 oom 的，挺奇怪的，内测版会有更详细的报错，可以下一个再帮忙发下看看提示啥

**Comment by zZlackZz** [comment]
> 第一次见到 oom 的，挺奇怪的，[内测版](https://github.com/MaaAssistantArknights/MaaRelease/releases) 会有更详细的报错，可以下一个再帮忙发下看看提示啥

您好，下载的内测版本与log见下方
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11358977/gui.log)
![image](https://user-images.githubusercontent.com/44299454/235299464-0827be7c-55dd-47f9-b3c2-0185cf5ba5f1.png)

**Comment by MistEO** [comment]
试试这个版本有没有修复 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/4839105157 正在构建，等个半小时左右就有下载链接了

**Comment by zZlackZz** [comment]
> 试试这个版本有没有修复 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/4839105157 正在构建，等个半小时左右就有下载链接了

最新运行结果见下log
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11359557/gui.log)

**Comment by MistEO** [comment]
没头绪，怎么一直报 OOM， @dantmnf dant 佬有没有空帮忙瞅瞅

**Comment by zzyyyl** [comment]
修了么（？

**Comment by zZlackZz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
