### ISSUE TITLE
希望在更新时能区别一下Avx与非Avx的机子

### ISSUE THREAD

**Issue by drunkenQCat** [MaaAssistantArknights/MaaAssistantArknights#455]
昨天更新之后，我的非Avx机子又不能运行了。如果每次更新都需要手动替换掉软件里的dll，还是比较麻烦的。建议在更新的时候还是能辨认一下CPU型号。

**Comment by MistEO** [comment]
我们计划推出 OTA 包，自动更新的时候下载 OTA 包，其中不包括飞桨相关的文件，在做了.jpg

**Comment by MistEO** [comment]
v3.9.9-beta.1 fixed
