### ISSUE TITLE
maa内测版刷理智按钮问题

### ISSUE THREAD

**Issue by p2218** [MaaAssistantArknights/MaaAssistantArknights#4555]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，内测版在刷理智这一功能上会间歇性没反应

### 日志文件

![image](https://user-images.githubusercontent.com/132145249/235304978-5ad5fa27-1592-49b4-a0f7-73267e18fcea.png)

### 截图

![image](https://user-images.githubusercontent.com/132145249/235304940-cc4c56c2-490f-4e16-acf1-5555e6fe3c01.png)

**Comment by MistEO** [comment]
发下日志，debug/asst.log

**Comment by MistEO** [comment]
另外没反应是个什么现象？

**Comment by p2218** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11360316/asst.log)

**Comment by p2218** [comment]
没反应就是任何触控模式都没反应....替换adb也没反应，点开之后说是在执行任务但是实际上并没有任何操作

**Comment by p2218** [comment]
另外补充一下 ，现阶段只有仅勾选刷理智选项，刷理智这个功能才会生效，跟其他功能一起勾选的时候就不会有任何反应@MistEO
