### ISSUE TITLE
电脑关机启动后显示资源损坏

### ISSUE THREAD

**Issue by zichusml** [MaaAssistantArknights/MaaAssistantArknights#4558]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

电脑关机启动后显示资源损坏

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11360703/asst.log)

### 截图

![图片](https://user-images.githubusercontent.com/132187565/235338697-40ef6a54-f953-4cee-b962-a1c5c205e6e1.png)

**Comment by MistEO** [comment]
公测版修过了，可以先更新一下。正式版这两天会发

**Comment by ABA2396** [comment]
打不开怎么更新.jpg
点这个下
https://ota.maa.plus/MaaAssistantArknights/MaaRelease/releases/download/v4.16.0-beta.1/MAA-v4.16.0-beta.1-win-x64.zip

**Comment by pein0saga** [comment]
前两天有这个问题，手动更新后OK,再自动升级到4.164ALPHA依然有这个问题

**Comment by ABA2396** [comment]
> 前两天有这个问题，手动更新后OK,再自动升级到4.164ALPHA依然有这个问题

再来个日志看看

**Comment by pein0saga** [comment]
> > 前两天有这个问题，手动更新后OK,再自动升级到4.164ALPHA依然有这个问题
> 
> 再来个日志看看

强行关掉MAA，再重启MAA、用到现在没问题了
