### ISSUE TITLE
自动战斗识别视频时无法识别助战干员

### ISSUE THREAD

**Issue by infinity-M** [MaaAssistantArknights/MaaAssistantArknights#4564]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在使用视频分析抄作业的时候，maa无法识别出助战干员，导致生成的作业json无法正常使用，非助战干员也无法部署。
尽管有时在部署过程中识别出了助战干员，但是会出现其他干员unknown Deployment的状态，也导致整个json无法使用。

同时，在进行主线抄作业的时候，maa并不会跳过或点击进入关卡前的剧情，以及进入关卡后的剧情，导致无法正常战斗。

### 日志文件

          "actions": [
        {
            "name": "UnknownDeployment",
            "location": [
                3,
                2
            ],
            "kills": 0,
            "type": "Deploy",
            "direction": "Right"
        },
        {
            "name": "克洛丝",
            "location": [
                8,
                3
            ],
            "kills": 0,
            "direction": "Down",
            "cost_changes": 14,
            "type": "Deploy"
        },
——————————————————————————————————————————
#这里使用的是[半禺心]的主线挂机视频https://www.bilibili.com/video/BV1Jv4y1G7U9中的R8-4
#第一个部署的干员为助战山，未检测到，出现Unknown Deployment

    "actions": [
        {
            "name": "UnknownDeployment",
            "location": [
                5,
                4
            ],
            "kills": 1,
            "type": "Deploy",
            "direction": "Up"
        },
        {
            "name": "羽毛笔",
            "location": [
                4,
                6
            ],
            "kills": 1,
            "type": "Deploy",
            "direction": "Left"
        },
——————————————————————————————————————————
#同上，这里使用的是R8-5，助战干员为羽毛笔，虽然编队中没有检测到，但是部署中检测到了
#但本应为第一个部署的克洛丝成为了unknown Deplyment，导致整个json无法运行

    "actions": [
        {
            "name": "芬",
            "location": [
                5,
                4
            ],
            "kills": 0,
            "type": "Deploy",
            "direction": "Right"
        },
        {
            "name": "古米",
            "location": [
                5,
                3
            ],
            "kills": 0,
            "direction": "Right",
            "cost_changes": 12,
            "type": "Deploy"
        },
        {
            "name": "UnknownDeployment",
            "location": [
                6,
                5
            ],
            "kills": 2,
            "direction": "Up",
            "cost_changes": 32,
            "type": "Deploy"
        },
————————————————————————————————————————————
#这里是R8-7，第三个干员为助战水陈，成为了unknown deployment

### 截图

![image](https://user-images.githubusercontent.com/80324152/235350313-1545decc-eafd-4b11-8b6c-b4ef902719dc.png)
这些为检测到干员的图片，皆没有助战干员，而且没有检测到干员携带技能，全部干员skill都显示0
        {
            "skill": 0,
            "name": "古米",
            "skill_usage": 0
        },

### 还有别的吗？

辛苦了，但萌新真的很想自动抄主线（磕头

**Comment by MistEO** [comment]
什么版本的，日志发一下

**Comment by MistEO** [comment]
另外测试版刚刚优化了视频识别，如果不是测试版可以更新下试试

![image](https://user-images.githubusercontent.com/18511905/235352190-c113cc5a-4488-435b-a53c-6a057e0013cb.png)

**Comment by infinity-M** [comment]
使用的一直是公测版内置自动更新

再次试图在公测版v4.16.0-beat.1中复刻战斗识别时间出现以下错误

`MAA 遇到了问题
OpenClipboard 失败 (异常来自 HRESULT:0x800401D0 (CLIPBRD_E_CANT_OPEN))
解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard 失败 (异常来自 HRESULT:0x800401D0 (CLIPBRD_E_CANT_OPEN))
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Windows.Clipboard.Flush()
   在 System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   在 MaaWpfGui.Views.UI.ErrorView.CopyToClipboard()
   在 MaaWpfGui.Views.UI.ErrorView.<CopyErrorMessage_Click>d__25.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

生成的作业json中仍没有助战干员，debug\video_export\formation中也没有助战干员的图片，本次复现log如下：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11361627/asst.log)
得到作业如下：
[MaaAI_寒冷，来自知觉_821977464-1-30077_2023-04-30_16-25-54-214.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11361639/MaaAI_._821977464-1-30077_2023-04-30_16-25-54-214.log)
[MaaAI_牵引的炮火_821977557-1-30077_2023-04-30_16-18-27-601.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11361640/MaaAI_._821977557-1-30077_2023-04-30_16-18-27-601.log)

本次复现使用视频为之前提到过得R8-5和R8-7
本机时间为UTC+1，故日志时间会有时差
