### ISSUE TITLE
活动关闭后关卡选择自动跳转到“当前、上次”，导致无限刷OF-1

### ISSUE THREAD

**Issue by RainWinding** [MaaAssistantArknights/MaaAssistantArknights#4567]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

活动关闭后活动关卡从关卡选择自动跳转到“当前、上次”，导致无限刷OF-1，比如今天我没时间碰电脑就刷了一下午、240次......在外面我手机登录被卡掉就知道又遇到这个了，希望能优化下

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11361336/asst.log)

### 还有别的吗？

uu模拟器 win10

**Comment by ABA2396** [comment]
关卡选择为 `当前/上次` 的时候是不会打 OF-1 的，除非上次作战就是 OF-1。如果没开备选关卡，那活动关了变成 `当前/上次` 应该是没问题的；而如果开了备选关卡，在活动结束后也不会直接变成 `当前/上次`  ，而是保持原来的状态，并在下方显示 `关卡未开放`，并在下次启动的时候才会从关卡列表中删除活动关，让关卡选择重置成 `当前/上次`
![image](https://user-images.githubusercontent.com/99072975/235356277-a767f20c-951f-4150-9c55-89f51ff0bb08.png)
![image](https://user-images.githubusercontent.com/99072975/235356309-55ae91bf-1ddb-4f41-b4e0-5fc33f65881a.png)

**Comment by RainWinding** [comment]
感谢解答，上次作战是OF-1是因为开了借助战赚信用。之前没开备选关卡，现在学会了，谢谢您！

**Comment by ccmail** [comment]
![IMG_0037](https://user-images.githubusercontent.com/49861575/235574022-cc49c7a0-fb58-4a4d-8ecd-a0ee8e20af00.png)
我也有差不多的问题，不过是昨晚将“当前/上次”覆盖为cw-10后，今天（活动关卡开放第二天）查看maa打的是of-1。并且关卡选择上呈现空白。
之前这个账号应该是一直在刷1-7，如果需要日志的话要等一下，现在是移动端，远程复制文件不方便。

**Comment by ABA2396** [comment]
没搞懂，现在关卡选择不应该会出现null的情况了

**Comment by ccmail** [comment]
> 没搞懂，现在关卡选择不应该会出现null的情况了

这是我这两天的日志, 全部的debug文件在最下面的onedrive连接中, 下面是四个日志文件
[gui.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11371369/gui.bak.log)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11371370/gui.log)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11371367/asst.log)

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11371365/asst.bak.log)

https://1drv.ms/f/s!AjRJnm16CDBPlNBJGEPN5GYz_YU3Hg?e=w7c1S9
