### ISSUE TITLE
MAA執行新版保全派駐雷神工業(濁蒂版本) 外部出現例外情況

### ISSUE THREAD

**Issue by Berry85** [MaaAssistantArknights/MaaAssistantArknights#4574]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA執行新版保全派駐雷神工業(濁蒂版本) 顯示錯誤
問題Title為外部元件傳回例外情況
UU模擬器2.7.24.0(x64)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11361851/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/51792299/235366279-492e1d27-746c-4ce6-83eb-c4741625541e.png)

### 还有别的吗？

UU模擬器2.7.24.0(x64)
MAA版本 V4.16.0-rc.1

**Comment by MistEO** [comment]
挺奇怪的，你用别的保全文件正常吗？

**Comment by junyihan233** [comment]
我是该脚本的作者，脚本应该是没问题的，我测试了三个号，加起来测试了一百多次，甚至官方号录的视频也是用的这个脚本。
理论来讲应该不是脚本的问题，为排查问题，我建议这样做：
1.重启电脑，试试是否正常
2.运行其他保全脚本，试试是否正常
3.完全删除或卸载maa，重新下载后再尝试
4.关闭杀软的开机启动，关闭windows防火墙，然后右键此电脑-属性-系统高级设置-高级页面-性能对应的“设置”-数据执行保护-未除下列选定程序之外的所有程序和服务启用DEP，然后将maa添加到此路径，然后再尝试

**Comment by Berry85** [comment]
1. 重啟MAA執行, 一樣報錯
2. 重啟電腦, 連接完後一樣報錯
3. 其他保全派駐. 約翰老媽和另一份雷神工業的也錯誤
4. 我重新從release中下載v4.16.0-rc.1版本, (MAA-v4.16.0-rc.1-win-x64.zip)一樣報錯
5. 關於第4個添加進DEP, 提示無法添加x64位元的執行檔案的DEP屬性

**Comment by Lutra-Fs** [comment]
Same Error at 4.16.rc

**Comment by MistEO** [comment]
试试把这个 json 的文件名改成英文的，看看有没有用

**Comment by Lutra-Fs** [comment]
在更新，我等下试

**Comment by Berry85** [comment]
剛開服, 試了文件名改成英文, 不會報錯了,
