### ISSUE TITLE
MAA内测版本更新时出现未知错误

### ISSUE THREAD

**Issue by PokeMon3tr** [MaaAssistantArknights/MaaAssistantArknights#4579]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

5.1开服后，公测版更新完毕，发现还是用不了新图的作业，于是尝试更新内测版，重启MAA直接跳出这个错误，并且关闭后依然启动报错

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11364614/asst.log)
17：00左右

### 截图

![微信图片_20230501171807](https://user-images.githubusercontent.com/59350704/235433961-31a5e3d9-9c10-4a10-b5d7-b65055b7736b.png)

### 还有别的吗？

雷电模拟器，win10

**Comment by MistEO** [comment]
进程没结束掉，重启下电脑就行了
