### ISSUE TITLE
掉落识别有小bug

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#458]
批量刷图时，掉落识别不识别活动代币，会识别为未知材料。但是对于代币数量的识别有问题，有一定概率会吧sn9/sn10的代币掉落数量由应该的21误识别为1，原因未知。其他掉落数量没注意，应该没问题。在这里汇报一下，怕之后某次更新再出什么问题，希望开发者检查一下。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8644956/asst.log)

**Comment by MistEO** [comment]
掉落识别的问题，在重写了 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/507
