### ISSUE TITLE
掉落不识别，错误识别及上传企鹅物流失败

### ISSUE THREAD

**Issue by cglcv** [MaaAssistantArknights/MaaAssistantArknights#459]
3.3.1测试版，WSA
类似#458，掉落识别全是未知材料，有时异铁组也识别不出来，甚至有时候识别为无或不显示识别信息直接开始下一次行动，偶尔出现上传企鹅物流失败
WSA帧率和画质感觉都偏低，是否可能造成识别出错？
![屏幕截图 2022-05-07 204659](https://user-images.githubusercontent.com/35825310/167255350-5e28f718-7bb1-4fd6-bae2-7303cadc7848.png)

![屏幕截图 2022-05-07 204653](https://user-images.githubusercontent.com/35825310/167255375-f171ed5b-16b5-4751-af2d-300f393f313d.png)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8645188/asst.log)

**Comment by cglcv** [comment]
![屏幕截图 2022-05-07 205713](https://user-images.githubusercontent.com/35825310/167255437-ebc14d4b-a61d-438c-a080-5397352fa380.png)
再补一张

**Comment by MistEO** [comment]
帮忙用 adb 截个原图康康_(:з」∠)_

```bash
 adb -s 127.0.0.1:58526 shell screencap -d 1 -p /sdcard/xx.png
```

**Comment by cglcv** [comment]
> 帮忙用 adb 截个原图康康_(:з」∠)_
> 
> ```shell
>  adb -s 127.0.0.1:58526 shell screencap -d 1 -p /sdcard/xx.png
> ```

截不出来图
截出来的文件打不开，显示文件已损坏
是我WSA出问题了吗……

**Comment by cglcv** [comment]
可能是之前displayid变化了导致之前截图失败
但目前截出来的东西非常奇怪
![050803](https://user-images.githubusercontent.com/35825310/167289621-2fec9b6d-aa4a-4087-a26c-b94fba5b306c.png)
![050802 (7)](https://user-images.githubusercontent.com/35825310/167289631-bf302748-77d8-488e-8596-98703949a34f.png)
（上图对应的均为游戏登录前的世界观介绍界面）

**Comment by cglcv** [comment]
好的不知道什么原因现在又截出来了
![1](https://user-images.githubusercontent.com/35825310/167290274-35559414-0034-4ee4-b16b-9f694088abf3.png)

**Comment by cglcv** [comment]
然后我又试着截了个结算图，如图
![1](https://user-images.githubusercontent.com/35825310/167290730-69e208f1-8bdb-4423-8038-df8bcfd3a1fc.png)
然后按
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/669
中的方法写了个脚本
`setlocal enabledelayedexpansion 
set /a a=0 
for /l %%c in (1 1 100) do ( 
set /a a+=1 
adb shell screencap -p -d 10 /sdcard/pictures/!a!screen.png
adb pull /sdcard/pictures/!a!screen.png ./
 ) 
pause`
试着截了100张图，可以说是时好时坏了
![屏幕截图 2022-05-08 174744](https://user-images.githubusercontent.com/35825310/167290779-0f07fae3-3014-4697-9b3d-c627104489d1.png)

**Comment by Rainwolfai** [comment]
3.3.2 WSA 类似的问题，截图时好时坏，助手完全无法正常工作，试了很多遍一次都没有成功运行过，每次都卡死在startup了

**Comment by MistEO** [comment]
> 同样的问题，无材料掉落就会导致上传错误，有掉落的能正常上传，会影响企鹅物流的掉率准确性

上传错误就是没上传的意思（

**Comment by zzyyyl** [comment]
> > 同样的问题，无材料掉落就会导致上传错误，有掉落的能正常上传，会影响企鹅物流的掉率准确性
> 
> 上传错误就是没上传的意思（

无材料掉落没上传会导致企鹅那边统计的掉率偏高吧（？
~~我没理解错吧~~

**Comment by MistEO** [comment]
> > > 同样的问题，无材料掉落就会导致上传错误，有掉落的能正常上传，会影响企鹅物流的掉率准确性
> > 
> > 上传错误就是没上传的意思（
> 
> 无材料掉落没上传会导致企鹅那边统计的掉率偏高吧（？
> ~~我没理解错吧~~

这个问题看起来和有没有掉落没关系（？

**Comment by cglcv** [comment]
> 如果是截图是好是坏，那问题就可以解释了。
> 
> maa 会先截一张图判断是仍在代理作战，还是已经到了掉落界面了，如果是掉落界面就会再去截一张图进行掉落识别。应该是第一张图正常，第二张图有问题，就会出现这种情况
> 
> 但是我也不知道为啥 WSA 截图会这样（

那些空白图大小都非常小，要不加一个小于多大的图片重新截图的功能？

顺便我自己感觉截一张图存在sdcard然后pull发过来比直接命令行输出成功的概率高一点……一会儿试试命令行输出100张的效果

**Comment by MistEO** [comment]
另外我重新看了下日志，你用 WSA 的时候分辨率有点低，是 1054x596 这个分辨率太低了，而且也不是 16:9 的

**Comment by cglcv** [comment]
测了一下命令行输出，上来的成功率也不低
![屏幕截图 2022-05-10 191200](https://user-images.githubusercontent.com/35825310/167616970-35e5cf41-1add-4147-b348-157a1ce00cc2.png)

**Comment by cglcv** [comment]
> 另外我重新看了下日志，你用 WSA 的时候分辨率有点低，是 1054x596 这个分辨率太低了，而且也不是 16:9 的

调高倒不难，调成16:9挺费劲……毕竟靠手拖窗口大小调节分辨率

**Comment by cglcv** [comment]
把窗口拖大了一些，能正常工作，但掉落识别还是有bug（估计就是识别到空白图了）
目前分辨率1390*851，手拖16:9还是不太现实
结算图
![1screen](https://user-images.githubusercontent.com/35825310/167620462-56dfe858-2d21-4897-9e41-1a4eb9895ecd.png)
日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8661171/asst.log)
屏幕截图
![屏幕截图 2022-05-10 194246](https://user-images.githubusercontent.com/35825310/167620724-58582fcc-bc1c-4722-b568-926392f22ad4.png)
（其实上传失败那两次都有异铁组掉落，所以应该不会导致企鹅物流的数据发生波动……吧）

**Comment by MistEO** [comment]
掉落识别的问题，在重写了 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/507
