### ISSUE TITLE
希望能自动识别周年庆期间的采矿和签到

### ISSUE THREAD

**Issue by GSOR1008** [MaaAssistantArknights/MaaAssistantArknights#4591]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

maa不能在登录游戏时识别采矿和签到

### 有什么好的想法？

建议加入，以后应该也用得上，能加上的话maa就很完美了！

### 其他内容

如果可以希望大佬们加入此功能，真的会对大伙有很大的帮助！
（如果可以能把每日周年庆池子免费的一发抽了就更好了）
还有感谢maa制作团队，真的在这半年给没时间肝的doctor带来了特别大的帮助，但感觉美中不足的就是在签到这方面，加上的话那真的太好了，感谢！

**Comment by Rbqwow** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55343783/5a5f1535-3a08-48ef-b5a9-2b99fc97c68f)
忘了什么时候加的 总之是加了√
