### ISSUE TITLE
线索收集效率其实不止技能提升的百分比

### ISSUE THREAD

**Issue by Konecos** [MaaAssistantArknights/MaaAssistantArknights#46]
我遇到的情况：基建换班**会客室**换成`12F`和`梅`了

期望情况：基建换班**会客室**换成`红`和`陈`

会客室还要注意星级和精英化级别的提升
![](https://img.nga.178.com/attachments/mon_202001/30/-klbw3Q5-8vnjK2hT1kShs-h1.jpg)
参见链接[干员基建技能整理 及排班推荐](https://ngabbs.com/read.php?tid=20189817)

**Comment by MistEO** [comment]
会客室是会优先高星干员的，专门做了的，你遇到的情况可能是bug，帮忙发下日志看看，目录下asst.log文件

**Comment by Konecos** [comment]
[asst.log](https://github.com/MistEO/MeoAssistance-Arknights/files/7599608/asst.log)

今天重现了一下
红陈都去宿舍了
宿舍入驻心情阈值特意调为了0，（是心情耗尽了才住宿舍的意思吧？）（难道说我搞错了？）
这是图片
![Snipaste_2021 11 25_09 55 50 792_逍遥模拟器](https://user-images.githubusercontent.com/35402364/143364519-f83682ef-55f2-4875-8a58-74133b2653ee.png)
![Snipaste_2021 11 25_09 55 56 736_逍遥模拟器](https://user-images.githubusercontent.com/35402364/143364525-81e05463-2906-44e2-b570-539914829277.png)

**Comment by MistEO** [comment]
emmm，心情阈值说是这么说，但其实干员只选择工作状态排序在前面的这部分（就是你图中风笛右边的都不考虑了）

然后按技能来说，12F的技能是比星级技能等级高的，同技能才会考虑干员精英化和星级_(:з」∠)_
不过即使这样12F的效率也比星级低，我确实没想到orz，感觉这块逻辑得重写下，感谢反馈，~~下次一定~~

**Comment by ABA2396** [comment]
估计默认的基建换班最近是不会改了，可以看看自定义基建
https://yituliu.site/riicCal
