### ISSUE TITLE
[问题汇总]2Bugs report

### ISSUE THREAD

**Issue by TimothyChan44** [MaaAssistantArknights/MaaAssistantArknights#460]
！！！请尽可能详细的描述你遇到的问题，并附上助手软件目录下的 `asst.log` 日志文件！！！

！！！日志文件是可以直接拖拽进来的，没有日志文件的 bug 反馈我会直接关掉！！！

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ

- 设备及环境/Envs&Services：
```
PC：win11专业版
Mobile：MI6X Android 9 MIUI12.0.2 分辨率2160x1080像素 实体设备
```
- 问题/Problems:
```
问题1/P1:
账号等级提升时会卡住无法执行任务；

问题2/P2：
基建换班时只执行了信赖收取等操作，到换班时只进行了“右上角点击然后发呆”循环，不会执行换班；
```
- 日志/log:
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8646150/asst.log)

**Comment by MistEO** [comment]
> 目前仅对 16:9 分辨率支持较好，最低支持 1280 * 720，更高不限。非 16:9 分辨率可能会有奇奇怪怪的问题，正在进一步适配中_(:з」∠)_

**Comment by MistEO** [comment]
手机的话可以参考 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/388 硬改一下分辨率，用完再改回来（
