### ISSUE TITLE
MAA更新V4.16.3版本时解压出错

### ISSUE THREAD

**Issue by tea1time1** [MaaAssistantArknights/MaaAssistantArknights#4600]
/### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA更新4.16.3版本时，下载完毕后提示重启MAA，然后在解压的时候出现以下问题。
![image](https://user-images.githubusercontent.com/82923105/235650854-65ce50d7-e7b7-4e38-a423-c5d5155e5e55.png)
MAA 遇到了问题
对路径“D:\下载\MAA-v4.6.6-win-x64\.old\MAA.exe”的访问被拒绝。
解决方案
出现未知错误
详细信息
System.UnauthorizedAccessException: 对路径“D:\下载\MAA-v4.6.6-win-x64\.old\MAA.exe”的访问被拒绝。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalDelete(String path, Boolean checkHost)
   在 MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndUpdateNow()
   在 MaaWpfGui.ViewModels.UI.RootViewModel.OnViewLoaded()
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11372543/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/82923105/235650964-5c0ee964-e8ba-43a2-8d30-11fb3ce73e4f.png)

### 还有别的吗？

模拟器：蓝叠模拟器
操作系统：win11

**Comment by ABA2396** [comment]
重启下

**Comment by MistEO** [comment]
重启下，之后的版本不会有这个问题了

**Comment by tea1time1** [comment]
> 重启下，之后的版本不会有这个问题了

今天打开正常了，更新到4.16.3啦，感谢

**Comment by yuqikksk** [comment]
win10今天上午打开时提示我更新，更新后一打开就提示这个
解决办法：任务管理器里关闭maa进程，然后就能正常打开了
