### ISSUE TITLE
牛牛抽卡添加警示语

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#4603]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

牛牛抽卡是真抽卡啊😥我以为是模拟抽卡，就点了个十连，没想到真抽了个十连。建议这种真要抽卡的功能添加足够的警示语并且加大加粗标红来提示用户。另外那个第一次点进去的提示语说实在我都忘了是啥了，当时一点寻访就提示连接失败（详情见 #4426 ），后来我就把这项功能的所有情况都忘干净了，现在在点开也忘了那些提示啥的。

### 有什么好的想法？

添加警示语，加大加粗标红，提示这是真抽卡而非模拟抽卡。

**Comment by MistEO** [comment]
怎么加都有人看不见，我觉得现在的提示已经够大了

**Comment by xiaoweiXX** [comment]
> 怎么加都有人看不见，我觉得现在的提示已经够大了

只有第一次点开才有提示吧，附上我现在的截图
![屏幕截图 2023-05-02 203700](https://user-images.githubusercontent.com/92417243/235668089-38d05773-92d6-4b3c-af9d-9aeb45a08b16.png)
另外你看看我写的详情，第一次点开牛牛抽卡之后MAA没有连接上我的模拟器，所以我完全把第一次打开显示的啥忘了，要是第一次打开配上使用的经历我多少也会记住，加深印象。

**Comment by xiaoweiXX** [comment]
> 怎么加都有人看不见，我觉得现在的提示已经够大了

可以在我红圈圈出来的这个地方写警示，下面再写文案
![屏幕截图 2023-05-02 203700](https://user-images.githubusercontent.com/92417243/235668817-1b116179-1dde-4ba4-bca1-6127926e66bd.png)

**Comment by MistEO** [comment]
不会加的，正常使用这个功能的人每次都会看到警示，我觉得是糟糕的体验

**Comment by tang000ck** [comment]
> 不会加的，正常使用这个功能的人每次都会看到警示，我觉得是糟糕的体验

只有第一次打开才会有，后续再打开就不会有了，也不会有警示

**Comment by pein0saga** [comment]
> > 不会加的，正常使用这个功能的人每次都会看到警示，我觉得是糟糕的体验
> 
> 只有第一次打开才会有，后续再打开就不会有了，也不会有警示

<img width="747" alt="Snipaste_2023-05-25_14-31-12" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/2074641/be093e09-1ac7-4614-8b9b-06670e673f28">
