### ISSUE TITLE
 BUG：自动肉鸽时在便捷编队后选择技能时不会选择第九个干员的技能（第二列最下面一个）

### ISSUE THREAD

**Issue by DrSenkin** [MaaAssistantArknights/MaaAssistantArknights#4605]
版本：4.16.2，win10
公测版
出错时间：5月3日
肉鸽为水月肉鸽
未尝试傀影
mumu模拟器
maa touch
未使用：maa lite和暂停下干员
使用了：退出时释放adb

**Comment by ABA2396** [comment]
请用bug反馈模板提issue
