### ISSUE TITLE
maa无法更新

### ISSUE THREAD

**Issue by mmy792** [MaaAssistantArknights/MaaAssistantArknights#4607]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我现在版本是4.13.0没法正常更新了，不管我是选择内测版还是公测版还是稳定版都不会自动更新，点击检察更新也没有反应

### 日志文件

..

### 截图

![2SGFPFB`7 H 3_VLMTF89{N](https://user-images.githubusercontent.com/132417680/235820524-f2fcaa23-bbf3-4ca2-8e7d-db7fbe4a7bbd.png)

### 还有别的吗？

雷电模拟器，win10

**Comment by ABA2396** [comment]
太久没更新了，只会留最近10个版本的更新包。直接下完整包覆盖就行了
