### ISSUE TITLE
牛牛抽卡无法抽赠送寻访

### ISSUE THREAD

**Issue by Qingmuc** [MaaAssistantArknights/MaaAssistantArknights#4608]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在使用牛牛抽卡抽每日赠送一次时，会卡在
**是否使用1次赠送寻访机会招募干员？√ ×**
页面

### 日志文件

文字描述已详尽

**Comment by Prurite** [comment]
夏活时遇到了同样的问题。

**Comment by status102** [comment]
领取奖励-赠送单抽
