### ISSUE TITLE
自定义基建排班增加加工站换班支持

### ISSUE THREAD

**Issue by tio-plato** [MaaAssistantArknights/MaaAssistantArknights#4610]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前基建的重岳体系和莱茵体系都有基于在基建内非宿舍房间上班的阵营干员数量的加成技能，因此需要在加工站挂一个阵营干员，需要按时更换加工站里的干员。看了下doc现在好像不支持加工站换班

### 有什么好的想法？

希望能增加自定义排班对于加工站换班的支持，就算不用重岳/莱茵体系也可以换班的时候挂一个低信赖的人进去蹭一下信赖

**Comment by MistEO** [comment]
fixed
