### ISSUE TITLE
内测版公招识别显示潜能，程序崩溃

### ISSUE THREAD

**Issue by yukinatsu** [MaaAssistantArknights/MaaAssistantArknights#4611]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 遇到了问题
值不能为 null。
参数名: source
解决方案
出现未知错误
详细信息
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.Cast[TResult](IEnumerable source)
   在 MaaWpfGui.ViewModels.UI.RecognizerViewModel.get_OperBoxPotential()
   在 MaaWpfGui.ViewModels.UI.RecognizerViewModel.procRecruitMsg(JObject details)
   在 MaaWpfGui.Main.AsstProxy.ProcSubTaskExtraInfo(JObject details)
   在 MaaWpfGui.Main.AsstProxy.ProcMsg(AsstMsg msg, JObject details)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

这是bug信息复制下来的

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11381286/asst.log)
时间为5.3日下午17:40

**Comment by MistEO** [comment]
那个潜能显示，要先识别一次干员。之后版本会修一下崩溃问题
