### ISSUE TITLE
蓝叠模拟器国际版Hyper-V 版本连接

### ISSUE THREAD

**Issue by yy35959199** [MaaAssistantArknights/MaaAssistantArknights#4616]
### 已解决：
如果安装时选择了“自定义安装路径”，则bluestacks.conf配置文件的路径会在自己选定的安装路径下，比如我的配置是：
`"Bluestacks.Config.Path": "E:\\Game\\Android\\BlueStacks_nxt\\bluestacks.conf",`
原因：
蓝叠模拟器安装时，如果没有选择默认的安装路径，则蓝叠会在电脑上分成两个部分，比如我现在的路径是：
E:\Game\Android\BlueStacks_nxt（已安装明日方舟后，大小15.7GB）
C:\Program Files\BlueStacks_nxt（启动器的可执行文件所在路径，大小281MB）
文件bluestacks.conf的所在位置是自定义安装的那个路径下，所以直接用文档里的配置会出错OTZ
（没办法，我C盘只有150G空间……现在就剩几个G的剩余空间了OTZ）

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

模拟器：蓝叠模拟器国际版Hyper-V，引擎Pie64，今天新装的最新版
已在gui.json中配置了如下两项，配置文件路径+keyword内容已人为确认无误：
  "Bluestacks.Config.Path": "C:\\ProgramData\\BlueStacks_nxt\\bluestacks.conf",
  "Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port",
已开ADB：
![image](https://user-images.githubusercontent.com/37442303/235925928-360e6686-4aa4-4d89-b33f-47c26f2f64b1.png)
MAA：最新稳定版和最新内测版都试过
已尝试过“强制替换ADB”和修改ADB为本地下载的ADB；

现象：因为文档里没写蓝叠模拟器国际版Hyper-V需要在MAA的连接地址里填什么，就设置的自动检测连接，启动的结果是：连接失败，请检查连接设置
猜测的原因：自动识别成蓝叠模拟器，然后读取的bst.instance.Pie64.adb_port=5555而非bst.instance.Pie64.status.adb_port的值：
![image](https://user-images.githubusercontent.com/37442303/235926880-262a720f-a157-427d-b48e-a25e9d389140.png)

连接设置的“连接配置”里也没有蓝叠Hyper-V版这一项……大概是自动识别没认出来，也不知道怎么手动配置OTZ
因为开了windows沙盒，Hyper-V好像是必须的前置项？
没查到除了蓝叠Hyper-V版之外还有哪家模拟器和Hyper-V兼容了……OTZ

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11382919/asst.log)

### 截图
![image](https://user-images.githubusercontent.com/37442303/236111095-304ead88-db2e-48a7-afa2-ba46f132420d.png)
![image](https://user-images.githubusercontent.com/37442303/235927986-f6abb368-906d-42e4-89ae-0e5c249e5044.png)
![image](https://user-images.githubusercontent.com/37442303/235928066-64b6e849-02df-4ba2-a86d-327e894933c2.png)
![image](https://user-images.githubusercontent.com/37442303/235928171-b7f84050-84c5-421f-94da-488c2fdadba0.png)
![image](https://user-images.githubusercontent.com/37442303/235929690-6767ba14-fd4a-440f-80e9-5d49ca4e13fb.png)

（截图中的ADB是使用模拟器自带ADB无果后尝试使用本地ADB，失败；使用模拟器自带ADB时的ADB路径确认无误）

### 还有别的吗？

Windows10专业版系统；酷睿i5十一代CPU
（不过感觉就是识别成蓝叠原版然后用了5555端口连接ADB失败……）

**Comment by ABA2396** [comment]
"Bluestacks.Config.Path":"C:\ProgramData\BlueStacks_nxt\bluestacks.conf",中的 '\' 需要转义，即使用 '\\'

**Comment by yy35959199** [comment]
> "Bluestacks.Config.Path":"C:\ProgramData\BlueStacks_nxt\bluestacks.conf",中的 '' 需要转义，即使用 '\'
json里配置的带转义了啊……
![image](https://user-images.githubusercontent.com/37442303/236111118-380ca6d9-5f80-4a5d-a8e9-94e50018942b.png)

**Comment by ABA2396** [comment]
写了这个就不用自动检测了

**Comment by yy35959199** [comment]
> 写了这个就不用自动检测了

也不行，GUI的连接设置里好像不能是空的，最后还是用的5555端口号进行连接然后连接失败……
![image](https://user-images.githubusercontent.com/37442303/236114472-8ceeec82-1f2d-4791-bc3e-e589ce14268b.png)
![image](https://user-images.githubusercontent.com/37442303/236114500-0ee4af3c-2d17-4610-b998-449ff7f9490f.png)

**Comment by ABA2396** [comment]
没搞懂，用管理员启动试过了么

**Comment by yy35959199** [comment]
> 没搞懂，用管理员启动试过了么

那肯定是试过了啊……但启动结果就是title上显示蓝叠模拟器：127.0.0.1:5555，所以我怀疑就是没调用Hyper-V版本的端口号参数……

**Comment by warningme** [comment]
有试过手动连接吗，就是在连接地址里改成127.0.0.1:55957（这个是你在开模拟器adb的地方显示的端口），我多开自动识别adb会紊乱就用这个方法解决的

**Comment by SherkeyXD** [comment]
我的蓝叠模拟器Hyper-V版本没有问题
我的设置：
<img width="421" alt="image" src="https://user-images.githubusercontent.com/57581480/236423107-445aa697-eb59-4af5-8020-da14d26c824a.png">
连接地址那一块随便填的

**Comment by yy35959199** [comment]
> 我的蓝叠模拟器Hyper-V版本没有问题 我的设置： <img alt="image" width="421" src="https://user-images.githubusercontent.com/57581480/236423107-445aa697-eb59-4af5-8020-da14d26c824a.png"> 连接地址那一块随便填的
> 
> **不要使用自动检测**，使用自动检测会导致无法连接

好的，取消自动连接后已解决……
终于发现了问题所在，关键问题在于：我在安装蓝叠的时候，选的路径是E盘，但是蓝叠会强制将大部分组件装在E盘，少部分内容强制装在C盘（200MB），这样蓝叠在PC上是分为两个部分的，而那个配置文件的路径是E盘……所以改成这样就可以了：
"Bluestacks.Config.Path": "E:\\Game\\Android\\BlueStacks_nxt\\bluestacks.conf",

**Comment by ASC8384** [comment]
![图片](https://user-images.githubusercontent.com/29878345/236633272-317116d0-14e8-45a3-94f0-a74dd8ad70c4.png)
![图片](https://user-images.githubusercontent.com/29878345/236633278-ceae334a-9a57-43b8-871c-b67b1e0d5fa4.png)
我确保`gui.json`文件填写正确，但依旧出现这个错误，只有手动指定端口才能链接

**Comment by yy35959199** [comment]
> ![图片](https://user-images.githubusercontent.com/29878345/236633272-317116d0-14e8-45a3-94f0-a74dd8ad70c4.png) ![图片](https://user-images.githubusercontent.com/29878345/236633278-ceae334a-9a57-43b8-871c-b67b1e0d5fa4.png) 我确保`gui.json`文件填写正确，但依旧出现这个错误，只有手动指定端口才能链接

你确定吗……你顺着那个配置的路径，看看能不能找到bluestacks.conf这个文件……
你安装的时候是用的默认路径还是自己改了路径？

**Comment by ASC8384** [comment]
> 

添加`"Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port"`后成功了。。。

我不需要多开，但无法判断使用的是蓝叠 Pie 核心 Hyper-V 模拟器

> > ![图片](https://user-images.githubusercontent.com/29878345/236633272-317116d0-14e8-45a3-94f0-a74dd8ad70c4.png) ![图片](https://user-images.githubusercontent.com/29878345/236633278-ceae334a-9a57-43b8-871c-b67b1e0d5fa4.png) 我确保`gui.json`文件填写正确，但依旧出现这个错误，只有手动指定端口才能链接
> 
> 你确定吗……你顺着那个配置的路径，看看能不能找到bluestacks.conf这个文件…… 你安装的时候是用的默认路径还是自己改了路径？

**Comment by SherkeyXD** [comment]
> > 
> 
> 添加`"Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port"`后成功了。。。
> 
> 我不需要多开，但无法判断使用的是蓝叠 Pie 核心 Hyper-V 模拟器
> 
> > > ![图片](https://user-images.githubusercontent.com/29878345/236633272-317116d0-14e8-45a3-94f0-a74dd8ad70c4.png) ![图片](https://user-images.githubusercontent.com/29878345/236633278-ceae334a-9a57-43b8-871c-b67b1e0d5fa4.png) 我确保`gui.json`文件填写正确，但依旧出现这个错误，只有手动指定端口才能链接
> > 
> > 你确定吗……你顺着那个配置的路径，看看能不能找到bluestacks.conf这个文件…… 你安装的时候是用的默认路径还是自己改了路径？
> 
> 

似乎对于安装有hyper-v的机器，蓝叠默认启用pie64核心（需要考证）

**Comment by yy35959199** [comment]
> > > 
> > 
> > 
> > 添加`"Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port"`后成功了。。。
> > 我不需要多开，但无法判断使用的是蓝叠 Pie 核心 Hyper-V 模拟器
> 
> 似乎对于安装有hyper-v的机器，蓝叠默认启用pie64核心（需要考证）

不清楚……反正我从官网下载的hyper-v的蓝叠现在好像只能是pie64……
具体这个配置你能在bluestacks.conf文件中搜到

**Comment by fy0** [comment]
> > > 
> > 
> > 
> > 添加`"Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port"`后成功了。。。
> > 我不需要多开，但无法判断使用的是蓝叠 Pie 核心 Hyper-V 模拟器
> 
> 似乎对于安装有hyper-v的机器，蓝叠默认启用pie64核心（需要考证）

同配置成功。只配置路径并不能自动识别端口

**Comment by 200433zc** [comment]
方法可行，注意不是要等待到60秒就是有问题，我之前理解错了以为是60秒内会检测是否启动，电脑好可以调到等10秒

**Comment by ziyouzhidh** [comment]
> ## 已解决
> ### 解决方案：
> 如果安装时选择了“自定义安装路径”，则bluestacks.conf配置文件的路径会在自己选定的安装路径下，比如我的配置是： `"Bluestacks.Config.Path": "E:\\Game\\Android\\BlueStacks_nxt\\bluestacks.conf",`
> 
> ### 原因：
> 蓝叠模拟器安装时，如果没有选择默认的安装路径，则蓝叠会在电脑上卸载两个部分，比如我现在的路径是：文件 `E:\Game\Android\BlueStacks_nxt（已安装明日方舟后，大小15.7GB）` `C:\Program Files\BlueStacks_nxt（启动器的可执行文件所在路径，大小281MB）` bluestacks.conf的所在位置是自定义安装的那个路径下，所以直接用文档里的配置会出错OTZ （没办法，我C盘只有150G空间……现在就剩下几个G的剩余空间了OTZ）
> 
> ### 在提问之前...
> * [x] 我理解问题是用于反馈和解决问题的，而不是吐槽评论区，将问题提供更多信息帮助问题解决
> * [x] 我填写了简单且清晰的标题，以便开发者在阅读问题列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
> * [x] 我已查看最新测试版本的更新内容，反映该bug已被修复的情况
> 
> ### 问题描述
> 模拟器：蓝叠模拟器国际版Hyper-V，引擎Pie64，今天新装的最新版本 已在gui.json中配置了如下两个，配置文件路径+关键字内容已人为确认无误： "Bluestacks.Config.Path ": "C:\ProgramData\BlueStacks_nxt\bluestacks.conf", "Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port", 已开ADB： MAA：最新稳定版和最新内测版都试过 已尝试过“强制替换ADB”并修改ADB为本地下载的ADB； ![图像](https://user-images.githubusercontent.com/37442303/235925928-360e6686-4aa4-4d89-b33f-47c26f2f64b1.png)
> 
> 现象：因为文档里没写蓝叠模拟器国际版Hyper-V需要在MAA的连接地址里填什么，就设置的自动检测连接，启动的结果是：连接失败，请检查连接设置猜测的原因 ：自动识别成蓝叠模拟器，然后读取bst.instance.Pie64.adb_port=5555而不bst.instance.Pie64.status.adb_port的值： ![图像](https://user-images.githubusercontent.com/37442303/235926880-262a720f-a157-427d-b48e-a25e9d389140.png)
> 
> 连接设置的“连接配置”里也没有蓝叠Hyper-V版这一项……大概是自动识别没认出来，也不知道怎么手动配置OTZ 因为开了windows沙盒，Hyper-V好像是必须的前置项？ 没查到除了蓝叠Hyper-V版之外还有哪家模拟器和Hyper-V兼容了……OTZ
> 
> ### 日志文件
> [辅助日志](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11382919/asst.log)
> 
> ### 截图
> ![图像](https://user-images.githubusercontent.com/37442303/236111095-304ead88-db2e-48a7-afa2-ba46f132420d.png) ![图像](https://user-images.githubusercontent.com/37442303/235927986-f6abb368-906d-42e4-89ae-0e5c249e5044.png) ![图像](https://user-images.githubusercontent.com/37442303/235928066-64b6e849-02df-4ba2-a86d-327e894933c2.png) ![图像](https://user-images.githubusercontent.com/37442303/235928171-b7f84050-84c5-421f-94da-488c2fdadba0.png) ![图像](https://user-images.githubusercontent.com/37442303/235929690-6767ba14-fd4a-440f-80e9-5d49ca4e13fb.png)
> 
> （截图中的ADB是使用模拟器自带的ADB无果后尝试使用本地ADB，失败；使用模拟器自带的ADB时的ADB路径确认无误）
> 
> ### 还有其他吗？
> Windows10专业版系统；酷睿i51代CPU （不过感觉就是识别成蓝叠原版用了5555端口连接ADB失败……）

您好  "Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port",这个模拟器编码是从哪里得到，我也把模拟器一部分安装到d盘，这个模拟器编码找不到请教下

**Comment by ziyouzhidh** [comment]
> > ## 已解决
> > ### 解决方案：
> > 如果安装时选择了“自定义安装路径”，则bluestacks.conf配置文件的路径会在自己选定的安装路径下，比如我的配置是： `"Bluestacks.Config.Path": "E:\\Game\\Android\\BlueStacks_nxt\\bluestacks.conf",`
> > ### 原因：
> > 蓝叠模拟器安装时，如果没有选择默认的安装路径，则蓝叠会在电脑上卸载两个部分，比如我现在的路径是：文件 `E:\Game\Android\BlueStacks_nxt（已安装明日方舟后，大小15.7GB）` `C:\Program Files\BlueStacks_nxt（启动器的可执行文件所在路径，大小281MB）` bluestacks.conf的所在位置是自定义安装的那个路径下，所以直接用文档里的配置会出错OTZ （没办法，我C盘只有150G空间……现在就剩下几个G的剩余空间了OTZ）
> > ### 在提问之前...
> > 
> > * [x]  我理解问题是用于反馈和解决问题的，而不是吐槽评论区，将问题提供更多信息帮助问题解决
> > * [x]  我填写了简单且清晰的标题，以便开发者在阅读问题列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
> > * [x]  我已查看最新测试版本的更新内容，反映该bug已被修复的情况
> > 
> > ### 问题描述
> > 模拟器：蓝叠模拟器国际版Hyper-V，引擎Pie64，今天新装的最新版本 已在gui.json中配置了如下两个，配置文件路径+关键字内容已人为确认无误： "Bluestacks.Config.Path ": "C:\ProgramData\BlueStacks_nxt\bluestacks.conf", "Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port", 已开ADB： MAA：最新稳定版和最新内测版都试过 已尝试过“强制替换ADB”并修改ADB为本地下载的ADB； ![图像](https://user-images.githubusercontent.com/37442303/235925928-360e6686-4aa4-4d89-b33f-47c26f2f64b1.png)
> > 现象：因为文档里没写蓝叠模拟器国际版Hyper-V需要在MAA的连接地址里填什么，就设置的自动检测连接，启动的结果是：连接失败，请检查连接设置猜测的原因 ：自动识别成蓝叠模拟器，然后读取bst.instance.Pie64.adb_port=5555而不bst.instance.Pie64.status.adb_port的值： ![图像](https://user-images.githubusercontent.com/37442303/235926880-262a720f-a157-427d-b48e-a25e9d389140.png)
> > 连接设置的“连接配置”里也没有蓝叠Hyper-V版这一项……大概是自动识别没认出来，也不知道怎么手动配置OTZ 因为开了windows沙盒，Hyper-V好像是必须的前置项？ 没查到除了蓝叠Hyper-V版之外还有哪家模拟器和Hyper-V兼容了……OTZ
> > ### 日志文件
> > [辅助日志](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11382919/asst.log)
> > ### 截图
> > ![图像](https://user-images.githubusercontent.com/37442303/236111095-304ead88-db2e-48a7-afa2-ba46f132420d.png) ![图像](https://user-images.githubusercontent.com/37442303/235927986-f6abb368-906d-42e4-89ae-0e5c249e5044.png) ![图像](https://user-images.githubusercontent.com/37442303/235928066-64b6e849-02df-4ba2-a86d-327e894933c2.png) ![图像](https://user-images.githubusercontent.com/37442303/235928171-b7f84050-84c5-421f-94da-488c2fdadba0.png) ![图像](https://user-images.githubusercontent.com/37442303/235929690-6767ba14-fd4a-440f-80e9-5d49ca4e13fb.png)
> > （截图中的ADB是使用模拟器自带的ADB无果后尝试使用本地ADB，失败；使用模拟器自带的ADB时的ADB路径确认无误）
> > ### 还有其他吗？
> > Windows10专业版系统；酷睿i51代CPU （不过感觉就是识别成蓝叠原版用了5555端口连接ADB失败……）
> 
> 您好 "Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port",这个模拟器编码是从哪里得到，我也把模拟器一部分安装到d盘，这个模拟器编码找不到请教下
![屏幕截图 2023-12-11 000321](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149868656/465a2627-e53a-455c-8955-f70a6b787b9c)
![屏幕截图 2023-12-11 000633](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149868656/7d06c6ea-9ec6-4da4-979d-02274737e01d)
查找出两项，都要修改吗？

**Comment by ziyouzhidh** [comment]
> > > ## 已解决
> > > ### 解决方案：
> > > 如果安装时选择了“自定义安装路径”，则bluestacks.conf配置文件的路径会在自己选定的安装路径下，比如我的配置是：`"Bluestacks.Config.Path": "E:\\Game\\Android\\BlueStacks_nxt\\bluestacks.conf",`
> > > ### 原因：
> > > 蓝叠模拟器安装时，如果没有选择默认的安装路径，则蓝叠会在电脑上卸载两个部分，比如我现在的路径是：文件`E:\Game\Android\BlueStacks_nxt（已安装明日方舟后，大小15.7GB）` `C:\Program Files\BlueStacks_nxt（启动器的可执行文件所在路径，大小281MB）`bluestacks.conf的所在位置是自定义安装的那个路径下，所以直接用文档里的配置会出错OTZ（没办法，我C盘只有150G空间……现在就剩下几个G的剩余空间了OTZ）
> > > ### 在提问之前...
> > > 
> > > * [x]   我理解问题是用于反馈和解决问题的，而不是吐槽评论区，将问题提供更多信息帮助问题解决
> > > * [x]   我填写了简单且清晰的标题，以便开发者在阅读问题列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
> > > * [x]   我查看最新测试版本的更新内容已，反映该bug已被修复的情况
> > > 
> > > ### 问题描述
> > > 模拟器：蓝叠模拟器国际版Hyper-V，引擎Pie64，今天新装的最新版本已在gui.json中配置了如下两个，配置文件路径+内容关键字已人为确认无误： "Bluestacks.Config. Path ": "C:\ProgramData\BlueStacks_nxt\bluestacks.conf", "Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port", 已开ADB： MAA：最新稳定版和最新内测版都试过已尝试过“强制替换ADB”并修改ADB为本地下载的ADB；
> > > 现象：因为文档里没写蓝叠模拟器国际版Hyper-V需要在MAA的连接地址里填什么，就设置的自动检测连接，启动的结果是：连接失败，请检查连接设置猜测的原因：自动识别成蓝叠模拟器，然后读取bst.instance.Pie64.adb_port=5555而不是bst.instance.Pie64.status.adb_port的值：
> > > 连接设置的“连接配置”里也没有蓝叠Hyper-V版这一项……大概是自动识别没认出来，也不知道怎么手动配置OTZ因为打开了windows沙盒，Hyper-V想要是必须的前置项吗？ 没查到除了蓝叠Hyper-V版之外还有哪家模拟器和Hyper-V兼容了……OTZ![图像](https://user-images.githubusercontent.com/37442303/235925928-360e6686-4aa4-4d89-b33f-47c26f2f64b1.png)![图像](https://user-images.githubusercontent.com/37442303/235926880-262a720f-a157-427d-b48e-a25e9d389140.png)
> > > ### 日志文件
> > > [辅助日志](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11382919/asst.log)
> > > ### 截图
> > > ![图像](https://user-images.githubusercontent.com/37442303/236111095-304ead88-db2e-48a7-afa2-ba46f132420d.png) ![图像](https://user-images.githubusercontent.com/37442303/235927986-f6abb368-906d-42e4-89ae-0e5c249e5044.png) ![图像](https://user-images.githubusercontent.com/37442303/235928066-64b6e849-02df-4ba2-a86d-327e894933c2.png) ![图像](https://user-images.githubusercontent.com/37442303/235928171-b7f84050-84c5-421f-94da-488c2fdadba0.png) ![图像](https://user-images.githubusercontent.com/37442303/235929690-6767ba14-fd4a-440f-80e9-5d49ca4e13fb.png)
> > > （截图中的ADB是使用模拟器自带的ADB无果后尝试使用本地ADB，失败；使用模拟器自带的ADB时的ADB路径确认无误）
> > > ### 还有其他吗？
> > > Windows10专业版系统；酷睿i51代CPU（不过感觉就是识别成蓝叠原版用了5555端口连接ADB失败……）
> > 
> > 
> > 您好 "Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port",这个模拟器编码是从哪里得到的，我也把模拟器部分安装到d盘，这个模拟器编码找不到请教
> > 修改下出三个，要吗？
> > ![屏幕截图 2023-12-11 000321](https://private-user-images.githubusercontent.com/149868656/289371036-465a2627-e53a-455c-8955-f70a6b787b9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMjUwNTUsIm5iZiI6MTcwMjIyNDc1NSwicGF0aCI6Ii8xNDk4Njg2NTYvMjg5MzcxMDM2LTQ2NWEyNjI3LWU1M2EtNDU1Yy04OTU1LWY3MGE2Yjc4N2I5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxNjEyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjQ1OWFiZjI0Njc5OWRlODdmYzMzYTI0MTdlNDU3ZDZlOTZlOTg3NmNmMmY4NTRjMDJmY2RkNmY3YmQwNmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U4Fz5hQ_5AzUsQow4OmlOWMRYJHSehXF-ZNVre7xf4g)
> > ![屏幕截图 2023-12-11 000633](https://private-user-images.githubusercontent.com/149868656/289371086-7d06c6ea-9ec6-4da4-979d-02274737e01d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMjUwNTUsIm5iZiI6MTcwMjIyNDc1NSwicGF0aCI6Ii8xNDk4Njg2NTYvMjg5MzcxMDg2LTdkMDZjNmVhLTllYzYtNGRhNC05NzlkLTAyMjc0NzM3ZTAxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxNjEyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTk3YmNkYTBjNWM4MmQ2YjhlMDY5ZTY4YmI2OGU0NzAzMDVkOWU1YWI3NDEwNTMxNDE4MzBjMmU4MDA4ZTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zhm9OB7ygS0w6R-e7BRY2cFqq5YRpRZmEMuv0F5AcSs)

然后“Bluestacks.Config.Keyword”，按照帮助文档帮助，在c盘没有显示Engine文件夹，在d盘Engine内容如下请教下模拟器编码是？
![Uploading 屏幕截图 2023-12-11 001221.png…]()
