### ISSUE TITLE
识别用的缓存图像命名or图标错误

### ISSUE THREAD

**Issue by Yilia-Hana** [MaaAssistantArknights/MaaAssistantArknights#4622]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

并没有留意是否放错人,因为这是在第一次使用MAA打保全时在安装路径文件夹缓存的图片

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11384813/asst.zip)

第一次记录
[2023-05-03 20:54:07.366][INF][Px3f8c][Tx3fbc] 桃金娘.png
[2023-05-03 20:54:17.942][INF][Px3f8c][Tx3fbc] 山.png

### 截图

![Snipaste_2023-05-04_00-10-21](https://user-images.githubusercontent.com/88221645/235976438-beaf6184-14fc-4faa-b1f6-d78393277edb.png)

**Comment by ntgmc** [comment]
目前缓存错误的原因大概率是如果待部署区域人数超过14-15个，会导致生成的缓存偏移成隔壁的干员
