### ISSUE TITLE
希望 设置-信用相关-借助战赚信用 可以指定使用的编队.

### ISSUE THREAD

**Issue by hifuclub** [MaaAssistantArknights/MaaAssistantArknights#4624]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前如果打完本忘记改回去,maa会把其他编队都设置到只有嵯峨

### 有什么好的想法？

希望 设置-信用相关-借助战赚信用 功能可以指定编队.

### 其他内容

![image](https://user-images.githubusercontent.com/47740858/236024484-9bffc86b-ca40-464d-8da5-a361b83057ca.png)

**Comment by Constrat** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/754297c0-d17a-4e4e-bab5-0cf0ebae6471)
Maybe something like this? And there shouldn't be any OCR / detection as MAA just needs to click on 1 of the 4 formations which are ALWAYS fixed. We would just need the click coordinates.

**Comment by zzyyyl** [comment]
> @zzyyyl Maybe something like this? And there shouldn't be any OCR / detection as MAA just needs to click on 1 of the 4 formations which are ALWAYS fixed. We would just need the click coordinates.

I think it's okay. For simplicity you could just use the first (or last) formation without additional UI, I think.

Also, if you click on a selected formation, a dialogue box pops up to change the formation name, so we maybe need some TemplateMatch to handle (or avoid) it.

![Screenshot_20230919-125405](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/a77206ee-7d37-4637-84c3-f748322a72fc)
