### ISSUE TITLE
孤星隐藏关解锁后CW-8识别bug

### ISSUE THREAD

**Issue by YLin55** [MaaAssistantArknights/MaaAssistantArknights#4625]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

孤星的隐藏关卡解锁之后，自动刷理智设置成CW-8会在进入活动地图之后右划过头导致屏幕里没有CW-8从而识别失败。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11391917/asst.log)
bug出现于5-4 0:21:55左右

### 截图

![image](https://user-images.githubusercontent.com/69593380/236072077-4dcb05e9-4dd2-4d2d-8f45-6a9be243d1db.png)
![image](https://user-images.githubusercontent.com/69593380/236072145-dfcbe36f-ecab-47c7-ba76-e5f5511d2364.png)

**Comment by ABA2396** [comment]
草（）回去改

**Comment by OwlHowlinMornSky** [comment]
CW-9也不行（

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaRelease/commit/39be1aed6eddbd7db6cf9552177351056e8246d3 fixed

**Comment by ABA2396** [comment]
重启下应该就好了

**Comment by YLin55** [comment]
变成左滑到底卡死了xD

**Comment by YLin55** [comment]
> 重启下应该就好了

变成左滑到底卡死了xD

**Comment by ABA2396** [comment]
> xD

XD来个日志

**Comment by YLin55** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11394014/asst.log)
5-4 6:41

**Comment by YLin55** [comment]
> > xD
> 
> XD来个日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11394018/asst.log)
5-4 06:41

**Comment by ABA2396** [comment]
太怪了，只滑动一次之后会到哪个界面？能截个图吗

**Comment by YLin55** [comment]
> 太怪了，只滑动一次之后会到哪个界面？能截个图吗

![Screenshot_2023 05 04_07 06 46 507](https://user-images.githubusercontent.com/69593380/236124008-2a02a561-3779-4d32-b486-c4e784fd8d01.png)
一次滑动是到这里，但是没识别出来就继续划了

**Comment by ABA2396** [comment]
现在试试

**Comment by YLin55** [comment]
> 

可以识别到了，好耶
