### ISSUE TITLE
MuMu12完成后退出明日方舟和退出模拟器功能异常

### ISSUE THREAD

**Issue by LeavingEbb** [MaaAssistantArknights/MaaAssistantArknights#4633]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MuMu12模拟器选择完成后退出明日方舟，则游戏进程完全没有变化；选择完成后退出模拟器，则MAA显示任务正常全部完成，但模拟器会未响应而不能完全退出，如果不手动关闭模拟器程序，MAA将不再能启动模拟器，导致下一轮定时执行无法正常完成。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11397584/asst.log)
20:31 ~ 20:32：完成后退出明日方舟的报错
20:34 ~ 20:35：完成后退出模拟器，MAA正常退出，但模拟器未响应。
在20:36和20:38分别再次点击Link Start尝试启动模拟器（以模拟定时执行），无法正常启动。

### 截图

完成后退出明日方舟时，MAA主界面：
![image](https://user-images.githubusercontent.com/58244893/236204998-e02eafc7-52d4-4a76-964c-b1b0c05b59d6.png)
完成后退出模拟器时，模拟器未响应：
<img width="959" alt="QQ图片20230504205608" src="https://user-images.githubusercontent.com/58244893/236211649-33a3aca6-c4de-4803-860b-48952b63cf45.png">
若没有手动杀死未响应的模拟器进程，MAA再也不能启动模拟器：
![image](https://user-images.githubusercontent.com/58244893/236208402-740f60e5-3e0f-41df-8dba-1ca7ce690536.png)

### 还有别的吗？

[MAA及基建设置文件.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11397495/MAA.zip)
模拟器设置：Vulkan，4核/4G内存，画面表现更好，强制使用独显，1920*1080，最高60帧，动态调整帧率，开启Root权限。
配置：Win11，i9 13900HX，16G，RTX 4060（独显直连）

**Comment by ABA2396** [comment]
10bc322ff077b5dae5d40d208a0e58f0de998c50 fixed
