### ISSUE TITLE
MAA-V4.16.3 获取好友信用异常

### ISSUE THREAD

**Issue by hibikiypa** [MaaAssistantArknights/MaaAssistantArknights#4634]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

获取好友信用结束后没有自动停止进入下一项任务，而是继续遍历好友宿舍，一直在访问下位好友的宿舍
出现问题的日志时间点在2023-05-04 21:02:53.007这一条之后

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11397830/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/13904828/236215681-deab6c43-3c1d-4616-ab16-ddc6d3bca913.png)

### 还有别的吗？

模拟器为MUMU模拟器X（Android12）

**Comment by MistEO** [comment]
@hguandl 看起来 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/aded35c3d493fda916bf9f3509e63aae853f67ef 这个得回滚了（

**Comment by MistEO** [comment]
你好友太少了，如果好友比较多应该不会出这个问题（

**Comment by ABA2396** [comment]
> 你好友太少了，如果好友比较多应该不会出这个问题（

加个次数限制也不是不行）
