### ISSUE TITLE
肉鸽每次都需要手动关闭剧情

### ISSUE THREAD

**Issue by xvzhenduo** [MaaAssistantArknights/MaaAssistantArknights#4635]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

(美服)自动肉鸽每次都会在这个界面停住需要手动关闭不然就不停的放弃探索
![2023-05-04_21-47-32-349_raw](https://user-images.githubusercontent.com/74353173/236227861-08a8c770-ca5e-4c54-a7da-67210595f6f4.png)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11398133/asst.log)

**Comment by niuden** [comment]
这是傀影肉鸽里月度小队探索才有的剧情，不是常规行动，看样子需要加个识别。
