### ISSUE TITLE
雷电模拟器9，MAA挂肉鸽无法连接，或连接后进入选择分队页面后蓝屏

### ISSUE THREAD

**Issue by lms97** [MaaAssistantArknights/MaaAssistantArknights#4637]
蓝屏代码watchdog timeout
![1D4D00B9E293AB45606AB38AC4D6A3AD](https://user-images.githubusercontent.com/89146077/236281102-d7b7ad28-f2fb-4c14-8b84-685dd00e63e6.jpg)

**Comment by niuden** [comment]
我记得雷电模拟器有不支持文字识别的情况出现，可能会导致这个问题。如果不是刚需，可以换MuMuX，丝滑的一批。

**Comment by lms97** [comment]
谢谢，问题已经解决，问题出在bios超频里，防掉电等级调错



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月7日(周日) 中午12:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 雷电模拟器9，MAA挂肉鸽无法连接，或连接后进入选择分队页面后蓝屏 (Issue #4637)




 
我记得雷电模拟器有不支持文字识别的情况出现，可能会导致这个问题。如果不是刚需，可以换MuMuX，丝滑的一批。
