### ISSUE TITLE
肉鸽进入关卡后不下干员

### ISSUE THREAD

**Issue by HC-Fan** [MaaAssistantArknights/MaaAssistantArknights#464]
！！！请尽可能详细的描述你遇到的问题，并附上助手软件目录下的 `asst.log` 日志文件！！！

！！！日志文件是可以直接拖拽进来的，没有日志文件的 bug 反馈我会直接关掉！！！

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ

肉鸽刷投资，选完干员进入第一关关卡后不会进行任何操作。MUMU模拟器。
![Screenshot 2022-05-08 134020](https://user-images.githubusercontent.com/71550302/167283557-cb7dc9c9-6b11-4c18-97b1-f792251b83ec.jpg)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8646394/asst.log)

**Comment by MistEO** [comment]
> 目前仅对 16:9 分辨率支持较好，最低支持 1280 * 720，更高不限。非 16:9 分辨率可能会有奇奇怪怪的问题，正在进一步适配中_(:з」∠)_
