### ISSUE TITLE
无意间刷到，想问这repo是个啥？

### ISSUE THREAD

**Issue by bigcash** [MaaAssistantArknights/MaaAssistantArknights#4640]
### 说说你遇到的问题？

哪位大佬给科普一下！
查了一下，明日方舟是像原神一样的游戏吗？然后伟大的本项目是这个游戏的助手工具，或者外挂？

**Comment by MistEO** [comment]
有没有一种可能，我们的简介是中文的

**Comment by GalvinGao** [comment]
[请](https://github.com/MaaAssistantArknights/MaaAssistantArknights#readme)

**Comment by haven2world** [comment]
![image](https://user-images.githubusercontent.com/17299418/236396146-e098a747-ce2a-45b5-8079-4dfc1fc7860d.png)

**Comment by NumberSir** [comment]
😅玩原神玩的
