### ISSUE TITLE
在电脑换了个大屏幕后可以链接到模拟器但是无法挂机

### ISSUE THREAD

**Issue by threestone666** [MaaAssistantArknights/MaaAssistantArknights#4641]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

本来是2个24寸1080p的屏幕，现在是单个27寸2k另一个还是老屏幕，然后发现maa就无法挂机了，开始任务后一直没反应，重启电脑也没用

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11403517/asst.log)

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/236388841-1c48f133-963e-471c-88ca-f1b72c204599.png)
这个问题？
