### ISSUE TITLE
求助Deepin下如何安装？

### ISSUE THREAD

**Issue by overmindb4** [MaaAssistantArknights/MaaAssistantArknights#4642]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

deepin下载了MAA Linux64的tar.gz包，不会安装，网络搜索各种教程也毫无作用

### 有什么好的想法？

基于不想用Windows而转Deepin的小白，希望能出个比较适合小白的安装教程或者提供个安装视频链接

### 其他内容

目前使用deepin 20.9稳定版

**Comment by horror-proton** [comment]
Linux 版本暂时没有 GUI 可以用, 你可以用里面的 Python/sample.py 脚本来运行.
把 Release 里面的包解压到某个目录就行了
具体可以参考
https://github.com/orgs/MaaAssistantArknights/discussions/3241

**Comment by SherkeyXD** [comment]
https://github.com/MaaAssistantArknights/maa-cli/
