### ISSUE TITLE
不能吃源石 刷理智了

### ISSUE THREAD

**Issue by Tension727** [MaaAssistantArknights/MaaAssistantArknights#4648]
可以勾选，但是吃理智药也会被强制选中，开始任务后，执行完理智药次数后就停止了。没有吃源石

**Comment by ntgmc** [comment]
请提供一下你的log文件，位于debug\asst.log

**Comment by Tension727** [comment]
727111007
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 不能吃源石 刷理智了 (Issue #4648)





 
请提供一下你的log文件，位于debug\asst.log
