### ISSUE TITLE
吃理智药功能在吃理智小样时的小问题

### ISSUE THREAD

**Issue by Magnetogenerator** [MaaAssistantArknights/MaaAssistantArknights#4651]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在刷关时使用吃理智药功能是按照次数进行的，理智小样一个只有10理智，在刷21理智的关卡时，游戏中会直接默认吃两个理智小样，但是MAA会认为是吃了一次理智药。所以MAA中设置吃10次，游戏中会吃掉20个小样。但如果刷的关不到10理智就不会有这个问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11411258/asst.log)

**Comment by ABA2396** [comment]
![Screenshot_2023-05-06-12-29-52-861_com.tencent.mtt.jpg](https://user-images.githubusercontent.com/99072975/236599837-46a82e20-6843-40b9-8f69-c865e4494d4d.jpg)
是这样的（）

**Comment by Magnetogenerator** [comment]
这个问题现在就这样保留着不解决了吗（

**Comment by ABA2396** [comment]
就理智小样会有这个问题吧？反正我用的时候都是理智药写999，然后用指定次数的（）

**Comment by Magnetogenerator** [comment]
好吧（
