### ISSUE TITLE
最新的国际版Hyper-V蓝叠5.11.56.1003 P64ADB不能自动识别了

### ISSUE THREAD

**Issue by PeterPan0106** [MaaAssistantArknights/MaaAssistantArknights#4653]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

之前按照Hyper-V步骤操作过，一直可以自动识别端口号，更新完之后可能是路径变了，不识别了，只能手动输入了。请核实后优化调整

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11411635/asst.log)
5.6下午两点左右第一次打开时

**Comment by SherkeyXD** [comment]
bluestack.conf路径正确吗
检查一下bluestack.conf里面`bst.instance.{instance_name}.status.adb_port`一项是否还在

**Comment by ToumaLover** [comment]
新使用的国际版Hyper-V蓝叠，按文档向`gui.json`添加`"Bluestacks.Config.Keyword":"bst.instance.Nougat64.status.adb_port",`，无法识别模拟器，尝试添加`"Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port",`，成功自动识别模拟器端口，供参考

**Comment by lllllv** [comment]
亲测楼上有效

**Comment by SherkeyXD** [comment]
蓝叠Hyper-V版本默认使用Pie64核心，而maa的默认值是Nogat64核心，所以会出现无法读取的现象

**Comment by PiscesSoda** [comment]
> 新使用的国际版Hyper-V蓝叉，将文档向`gui.json`添加`"Bluestacks.Config.Path":"C:\\ProgramData\\BlueStacks_nxt\\bluestacks.conf", `，无法识别模拟器，尝试添加`"Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port",`，成功自主识别模拟器端口，提供考

有效，帮大忙啦
