### ISSUE TITLE
完成一次关卡后软件退出

### ISSUE THREAD

**Issue by david4958606** [MaaAssistantArknights/MaaAssistantArknights#466]
日志: 
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8647638/asst.log)

遇到的问题是刷理智时，完成一次关卡后本软件就自动退出了，关卡为10-4，但是1-7就没这个问题。

模拟器是蓝叠hyperv，系统 win11 22000.613

![image](https://user-images.githubusercontent.com/16517322/167311378-fe0d4d07-2f05-4d0a-9c4f-20dea72473b9.png)

**Comment by MistEO** [comment]
MAA 崩溃之后的游戏界面，帮忙截一张原图看看（需要用模拟器自带的截图工具）~

**Comment by david4958606** [comment]
> MAA 崩溃之后的游戏界面，帮忙截一张原图看看（需要用模拟器自带的截图工具）~
![Screenshot_2022 05 09_12 36 53 716](https://user-images.githubusercontent.com/16517322/167341551-94205366-c75b-41f5-a516-a7b77627bc61.png)

**Comment by MistEO** [comment]
掉落识别的问题，在重写了 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/507
