### ISSUE TITLE
连接真机使用时触控偏移

### ISSUE THREAD

**Issue by aixx999** [MaaAssistantArknights/MaaAssistantArknights#4663]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

连接真机时maa的模拟触控会出现偏移，导致很多操作无法进行。**据我观察，左边的触控会向左边偏移，右边的触控会往右边偏移。**我个人猜测可能和触摸点确定的方式有关。

可能的原因：用root的方式修改了手机的分辨率。
默认分辨率：1080*2400
当前分辨率：1080*1920

当我使用 wm size 1080x1920 修改分辨率时，adb会报错。
Exception occurred while executing 'size':
java.lang.SecurityException: Must hold permission android.permission.WRITE_SECURE_SETTINGS

当我使用 wm density 480 修改dpi时，adb也会报错。
Exception occurred while executing 'density':
java.lang.SecurityException: Must hold permission android.permission.WRITE_SECURE_SETTINGS

所以我更换方法，使用镧·系统工具箱app，更改分辨率。
但是分辨率更改成功后，仍然不能正常使用。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11412226/asst.log)
2023/5/6 19:20 开始执行基建换班操作，因为触控偏移无法完成。

### 还有别的吗？

**设备情况**
MAA版本：4.16.4（提交时已经为最新版本）
操作系统：Windows 10 21H2 19044.2846
真机设备：Oneplus 8
安卓版本：11
系统：MIUI 13
分辨率：1920*1080
dpi：480,440,240均能稳定复现本问题。
_注：240dpi时系统无圆角，480dpi，440dpi时系统有圆角。_

**MAA相关配置**
连接配置：兼容模式
触控模式：Minitouch
_注：选择此maa设置是因为其他设置有概率无法触控，经过测试在我的设备上此方式每次都稳定触控。_

**Comment by D3adEr1c** [comment]
参考：https://www.jianshu.com/p/da563d019053
开启 USB 调试（安全设置）

**Comment by aixx999** [comment]
我猜测跟分辨率更改方式有关，但是我手里的设备无法开启USB调试（安全设置），一般人可能用不到这种方式。感谢 @D3adEr1c的解答。
