### ISSUE TITLE
更新出错

### ISSUE THREAD

**Issue by Kevin-Lewis1** [MaaAssistantArknights/MaaAssistantArknights#4665]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新后重启报错
MAA 遇到了问题
另一个进程正在使用此文件，因此该进程无法访问此文件。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11412329/asst.log)
MAA 遇到了问题
另一个进程正在使用此文件，因此该进程无法访问此文件。
解决方案
出现未知错误
详细信息
System.IO.IOException: 另一个进程正在使用此文件，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   在 MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndUpdateNow()
   在 MaaWpfGui.ViewModels.UI.RootViewModel.OnViewLoaded()
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by junzhi-cn** [comment]
+1

**Comment by SevenChars** [comment]
在MAA连接模拟器的状态下是会出现更新错误的，检查一下是否有勾选“设置-启动设置-启动MAA后直接运行”，取消勾选后重新启动MAA再尝试更新

**Comment by junzhi-cn** [comment]
仅勾选自动开启模拟器仍出现该状况，全部取消勾选仍有改状况

**Comment by SevenChars** [comment]
有试过取消勾选之后重启一下电脑，再开MAA更新嘛

**Comment by junzhi-cn** [comment]
取消勾选然后给所有用户文件夹权限然后重启之后就好了，不确定是哪一步解决的

**Comment by Kevin-Lewis1** [comment]
我确实是在连接模拟器的情况下更新后重启在解压的过程报错的，我之前没有勾选“设置-启动设置-启动MAA后直接运行”，因为报错提示有进程冲突，我关掉了模拟器的所有进程（包括一个HD-Adb.exe的进程，蓝叠国际版），然后手动解压更新MAA文件夹里面的更新压缩包，再启动MAA就没有问题了

**Comment by geassyah** [comment]
感谢老哥，手动更新压缩包后可以正常使用了。取消勾选的方法用不了，MAA界面直接一片白，按都没法按。
