### ISSUE TITLE
干员识别结果有误

### ISSUE THREAD

**Issue by IDSir** [MaaAssistantArknights/MaaAssistantArknights#4667]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

干员识别功能识别结果错误：
粗略看了一下 未拥有中 阿 凯尔希 羽毛笔 巫恋（都是已拥有的）等没有识别到 后面已拥有的没有去看 估计也有识别错的

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11412581/asst.log)

### 截图

[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11412584/oper.zip)

**Comment by MistEO** [comment]
干员识别内测版修了一个很严重的bug，再下一个正式版如果还有问题麻烦再提一下
