### ISSUE TITLE
干员识别错误

### ISSUE THREAD

**Issue by 1173739248** [MaaAssistantArknights/MaaAssistantArknights#4669]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

穿皮肤的归溟幽灵鲨未能成功识别

### 日志文件

[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11412771/oper.zip)

### 截图

![QQ截图20230507000704](https://user-images.githubusercontent.com/63721507/236634905-d34f9a2e-01bc-4879-a384-dfd9ae6afd6a.png)

**Comment by MistEO** [comment]
干员识别内测版修了一个很严重的bug，再下一个正式版如果还有问题麻烦再提一下
