### ISSUE TITLE
MAA强制替换ADB失败

### ISSUE THREAD

**Issue by IvoRacious** [MaaAssistantArknights/MaaAssistantArknights#4670]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MuMu模拟器更新至内测最新版后连接出错，无法进行操作但未显示“连接失败”等字样
之前遇到类似情况强制替换ADB即可解决，但这次提示无法强制替换ADB，需要用管理员身份打开，但用管理员身份打开了也无法替换

MAA 遇到了问题
文件“E:\emulator\nemu\vmonitor\bin\adb_server.exe”正由另一进程使用，因此该进程无法访问此文件。
解决方案
请使用管理员权限打开 MAA 进行操作
详细信息
System.IO.IOException: 文件“E:\emulator\nemu\vmonitor\bin\adb_server.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ReplaceADB>b__415_1()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ReplaceADB>d__415.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11412765/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/121108792/236635703-08fc59e3-05f7-4302-b3a1-e02792bb2e56.png)
一直卡在这

### 还有别的吗？

MuMu模拟器

**Comment by ABA2396** [comment]
文件“E:\emulator\nemu\vmonitor\bin\adb_server.exe”正由另一进程使用，因此该进程无法访问此文件。

想办法把它关了，任务管理器里退了也行，找不到重启也行
