### ISSUE TITLE
水月肉鸽总在第一关暂停到放弃/干员选择无练度波登可

### ISSUE THREAD

**Issue by TizzureOne** [MaaAssistantArknights/MaaAssistantArknights#4675]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，本次反馈两个问题。
第一，水月肉鸽时，大概率在第一关战斗（或者说第一场战斗）（或者是任何战斗关卡）时直接进入暂停、不放置干员或进行其它操作，然后直接拖到超时放弃。
第二，水月肉鸽时，总是选择无任何练度的波登可作为首发干员使用。尝试修改recruitment文件中波登可的priority为0，没有用。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11413724/asst.zip)

### 截图

![QQ截图20230507094850](https://user-images.githubusercontent.com/55474420/236653599-c1ad83d2-762b-45c3-ad8b-39bae4f10837.png)
![QQ截图20230507094908](https://user-images.githubusercontent.com/55474420/236653604-1b6122d6-ea32-4a70-b308-8adea100c40e.png)
![QQ截图20230507095654](https://user-images.githubusercontent.com/55474420/236653747-9dcbe3fa-88ab-41f2-95c3-acae22b10fab.png)

### 还有别的吗？

使用模拟器：蓝叠国际版5.11.1.1002 N32
操作系统：Win10专业版

**Comment by 000191750** [comment]
我也有同样的问题，经常挂肉鸽挂着回头一看游戏被关闭了，然后打开游戏没多久游戏又被关了

**Comment by Clazex** [comment]
翻了下，低练干员招募优先度本身就会[视为 0](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2af4e1cc9adc6518ff10cfa65d4f800859447f47/src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp#L259)，选波登可是因为队伍未满时非关键干员优先度 [-1000](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2af4e1cc9adc6518ff10cfa65d4f800859447f47/src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp#L304)，而[波登可](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2af4e1cc9adc6518ff10cfa65d4f800859447f47/resource/roguelike/recruitment.json#L920)、[夏栎](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2af4e1cc9adc6518ff10cfa65d4f800859447f47/resource/roguelike/recruitment.json#L899)不知道为什么设定为了关键干员

**Comment by joshua0blake** [comment]
> 翻了下，低练干员招募优先度本身就会[视为 0](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2af4e1cc9adc6518ff10cfa65d4f800859447f47/src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp#L259)，选波登可是因为队伍未满时非关键干员优先度 [-1000](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2af4e1cc9adc6518ff10cfa65d4f800859447f47/src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp#L304)，而[波登可](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2af4e1cc9adc6518ff10cfa65d4f800859447f47/resource/roguelike/recruitment.json#L920)、[夏栎](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2af4e1cc9adc6518ff10cfa65d4f800859447f47/resource/roguelike/recruitment.json#L899)不知道为什么设定为了关键干员（可能是在久久拿不到医疗券后的备选，但明明已经设定了 啊）`recruit_priority_offsets`

这个有办法解决吗
