### ISSUE TITLE
主界面左下选择“完成任务后退出模拟器”，第二次连接时显示连接错误（定时自动执行或手动启动都会出现该问题）

### ISSUE THREAD

**Issue by LeonSlight** [MaaAssistantArknights/MaaAssistantArknights#4679]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

本人按标题描述设置完成后重启了maa，maa在06:00的时候是可以正常启动模拟器并完成任务，最后关闭模拟器；**但中午12:00自动执行的时候两个MAA都没有正常启动模拟器，或者说根本没启动模拟器**，只是显示红色的“模拟器断开，正在尝试重连”，重连了5次之后直接显示“重连失败，连接断开！”然后任务停止

本人平时有多开需求，因为蓝叠在打开多个模拟器窗口的时候会占用较多显存，导致显卡和整机耗电提高（常态待机45W以下，窗口全开不低80W）
我觉得太费电了就想着改成平时不执行任务就关掉模拟器省电；于是就引发了这些问题
有想过开启自动检测连接，但是多个模拟器窗口时自动检测连接不可用，把所有号都调整时间错开启动又不现实（加之其中一个模拟器开肉鸽延长任务执行时间会影响其它模拟器启动）
所以就跑来这求助开发组了qwq

个人的优化思路是**在连接设置里新增“任务开始时重新连接模拟器”的选项，或者把该功能绑定到完成任务自动关闭模拟器里面**，这样应该能解决第二次开启时maa还老惦记着原来的连接不放的问题

### 日志文件

由于12:00启动之后被我重启了一次，我担心没有记录在log里面所以又在13:30-13:40时间段内以同条件复现了一下状况，还是以复现的log为准
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11414020/asst.log)

### 截图

![MAA-问题复现截图](https://user-images.githubusercontent.com/132803457/236660061-5610de15-8140-4af3-9441-391f852dcf2b.jpeg)

### 还有别的吗？

模拟器为蓝叠中国版，目前创建了5个多开窗口（每个maa若未连接到模拟器则都可以正常启动每个多开窗口）

操作系统Windows10 已安装目前最新补丁
主板技嘉B85-HD3-A
CPU i7-4790；运行内存28GB(8+8+4+8)
GPU 七彩虹 RTX 3050 8GB
所有文件均存储在固态硬盘内

**Comment by ABA2396** [comment]
连接设置里那个 “adb 重连失败时自动重启模拟器” 开了吗

**Comment by LeonSlight** [comment]
开了，没用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: uye ***@***.***&gt;
发送时间: 2023年5月7日 15:52
收件人: MaaAssistantArknights/MaaAssistantArknights ***@***.***&gt;
抄送: LeonSlight ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 主界面左下选择“完成任务后退出模拟器”，第二次连接时显示连接错误（定时自动执行或手动启动都会出现该问题） (Issue #4679)





 
连接设置里那个 “adb 重连失败时自动重启模拟器” 开了吗

**Comment by LeonSlight** [comment]
重新勾选了一下，可以了


------------------ 原始邮件 ------------------
发件人: uye ***@***.***&gt;
发送时间: 2023年5月7日 15:52
收件人: MaaAssistantArknights/MaaAssistantArknights ***@***.***&gt;
抄送: LeonSlight ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 主界面左下选择“完成任务后退出模拟器”，第二次连接时显示连接错误（定时自动执行或手动启动都会出现该问题） (Issue #4679)





 
连接设置里那个 “adb 重连失败时自动重启模拟器” 开了吗
