### ISSUE TITLE
干员识别有干员没有识别到

### ISSUE THREAD

**Issue by wsyz5467** [MaaAssistantArknights/MaaAssistantArknights#4681]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题
干员是麒麟夜刀

### 日志文件

![QQ截图20230507173816](https://user-images.githubusercontent.com/52782369/236669790-56f84056-9faa-4832-90da-b358227b88a1.png)
[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11414470/oper.zip)
[oper2.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11414471/oper2.zip)
[oper3.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11414472/oper3.zip)

**Comment by MistEO** [comment]
debug/asst.log 也发一哈看看

**Comment by wsyz5467** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11415236/asst.log)
