### ISSUE TITLE
干员识别未识别到归溟幽灵鲨

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#4684]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用干员识别功能未识别到归溟幽灵鲨

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11414964/asst.log)

### 截图

[oper (2).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11414965/oper.2.zip)
[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11414966/oper.zip)
![image](https://user-images.githubusercontent.com/74366156/236677744-4c247429-7a05-47fa-a086-faadfe900020.png)

**Comment by Tec-El** [comment]
问题相同，经过反复测试后确认，这个问题应该是由于干员星标影响名称识别导致的，其余干员在星标状态下也有小概率识别不成功，而归溟幽灵鲨在星标状态下识别不成功的概率则是接近100%。

**Comment by MistEO** [comment]
干员识别内测版修了一个很严重的bug，再下一个正式版如果还有问题麻烦再提一下
