### ISSUE TITLE
关于基建

### ISSUE THREAD

**Issue by Nemeisi** [MaaAssistantArknights/MaaAssistantArknights#4687]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

单纯说我的需求：我希望我能自己设定好每种房间的干员组合，然后MAA能自行选择心情最高的组合置入。
确认干员技能训练，排列技能训练队列，自动练成材料并训练。（感觉这要求一步比一步难）
提高基建换班的效率。（自己设定点击延迟？）有些时候MAA翻干员页全翻了一遍（设定了指定干员的时候？），很耗时间

**Comment by tsctsc6** [comment]
特别是当某个干员专精时，就会反复寻找这个干员，就无法完成基建换班了

**Comment by MistEO** [comment]
> 我希望我能自己设定好每种房间的干员组合，然后MAA能自行选择心情最高的组合置入。

只考虑单个房间，你设置的组合效率应该是不如自动换班的

**Comment by Shawnsdaddy** [comment]
可以试试全自动动态基建换班啊，绝对高效率（用的人多了，就可以移植来maa了）
