### ISSUE TITLE
牛牛抽卡功能增加抽指定次数以及抽到某位干员停止功能

### ISSUE THREAD

**Issue by kxdxzr** [MaaAssistantArknights/MaaAssistantArknights#4689]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

既然做了牛牛抽卡功能，做点扩展功能让他更有用吧（）

**Comment by cenfusheng** [comment]
有识别错误的风险，暂不予考虑。
