### ISSUE TITLE
希望增加活动每日免费一抽的功能

### ISSUE THREAD

**Issue by LmeSzinc** [MaaAssistantArknights/MaaAssistantArknights#469]
自动长草之后，经常忘记使用每日免费一抽。虽然不指望抽到什么，但是不嫖白不嫖啊（

**需要添加的功能**

使用活动每日免费一抽

**需要考虑的情况**

每日一抽已经使用的时候，需要避免重复抽卡
有多个活动池的时候，需要检查
没有活动池的时候，需要避免抽错池子

**可能有用的截图**
![ak_pull](https://user-images.githubusercontent.com/37934724/167340417-15d4d8cf-3b58-4546-89da-e90db376286b.png)
![ak_pulled](https://user-images.githubusercontent.com/37934724/167340532-12081bcf-9403-44be-a426-7c9b807a47a0.png)

**Comment by MistEO** [comment]
不敢加，假如识别错了咋整（）

**Comment by ABA2396** [comment]
加，顺便把开矿加了（bushi）

**Comment by zzyyyl** [comment]
> 不敢加，假如识别错了咋整（）

高资刷掉都不怕，多浪费点合成玉有什么关系（bushi
