### ISSUE TITLE
关于完成后动作

### ISSUE THREAD

**Issue by wuqhly** [MaaAssistantArknights/MaaAssistantArknights#4690]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用蓝碟模拟器，任务结束后cpu内存资源占用任然居高不下
发现只要点击首页按钮，在不退出游戏和模拟器的情况下，就能节省大量系统资源占用，
切换游戏界面和模拟器连接也很方便

### 有什么好的想法？

因此建议在任务完成后动作里面增加一个切换到模拟器主界面功能

**Comment by MistEO** [comment]
退出明日方舟不是一样吗（

**Comment by ABA2396** [comment]
> 退出明日方舟不是一样吗（

退出之后还有个登录）不过这个功能做出来不就是为了不关模拟器但减少占用吗

**Comment by MistEO** [comment]
> > 退出明日方舟不是一样吗（
> 
> 退出之后还有个登录）不过这个功能做出来不就是为了不关模拟器但减少占用吗

登陆就登陆呗，反正下次有开始唤醒？直接退出占得内存应该会更少吧
