### ISSUE TITLE
我的需求三星TAG一小时，四星拉满9小时，速刷高资。

### ISSUE THREAD

**Issue by GUZHUYAXIAN** [MaaAssistantArknights/MaaAssistantArknights#4693]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

MAA目前无论三星还是四星TAG都是9小时拉满，除了高资和资深会保留。理论上三星TAG拉满可以避免出现2星和一星亏龙门币，但是对于老玩家而言，9小时拉满更亏龙门币，1小时和9小时差了440龙门币。一小时只需要160龙门币没记错的话。

### 有什么好的想法？

我的想法是在三星招募TAG的傍边加上另外一个选项，是否选择三星一小时速刷。老玩家可以点了速刷高资，新玩家可以不点，保留原来的配置，这样老咸鱼和萌新互不干扰。

**Comment by MistEO** [comment]
三星 tags 可以拉 7:40，是有小概率出 四、五星 的，黄票应该比龙门币值钱

**Comment by GUZHUYAXIAN** [comment]
OK




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月9日(星期二) 下午4:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 我的需求三星TAG一小时，四星拉满9小时，速刷高资。 (Issue #4693)





 
三星 tags 可以拉 7:40，是有小概率出 四、五星 的，黄票应该比龙门币值钱
 
如果是为了刷高资，我感觉大伙的加急许可都是溢出的吧（？，你可以用 MAA 一次性刷完的
