### ISSUE TITLE
OF-1借助战蹭信用没有考虑到借到无法出战干员的情况，导致卡死

### ISSUE THREAD

**Issue by MigdalBavel** [MaaAssistantArknights/MaaAssistantArknights#4694]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图所示，似乎是没考虑到这种情况，出现后就一直卡在这里后续的定时任务也不执行了。目前已经遇到过两次。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11419897/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11419908/gui.log)

### 截图

![QQ截图20230508165712](https://user-images.githubusercontent.com/105539375/236788609-aa6e78ab-5986-41c5-81b4-ae1c516c20fc.png)

**Comment by MigdalBavel** [comment]
有没有好哥哥受理一下（

**Comment by Constrat** [comment]
Fixed with 6c1da94b3ce77f5decf3e8f5262da455985ddffc
