### ISSUE TITLE
基建宿舍车尔尼

### ISSUE THREAD

**Issue by 04linshi** [MaaAssistantArknights/MaaAssistantArknights#4696]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建宿舍车尔尼被选择后依旧在寻找车尔尼

### 日志文件

23:13:51
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11422423/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/106676717/236863114-10e1d676-d4d1-4cb6-8c9c-c76f8cc7229c.png)
![MuMu20230508232338](https://user-images.githubusercontent.com/106676717/236864206-4efb0ff1-f774-41e1-9fea-17c69b551aba.png)
![MuMu20230508232329](https://user-images.githubusercontent.com/106676717/236864219-de402f1e-0aba-43e7-9272-0dde52bb1bfe.png)

**Comment by 04linshi** [comment]
今天早上并没有出现这个问题

**Comment by WSMTBG** [comment]
我也是，会选小车
