### ISSUE TITLE
保全派驻建议像肉鸽一样加入到主界面任务

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaAssistantArknights#4697]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

保全派驻作为一个长期的任务，不想蹲在电脑面前看着它打，
希望能加入到主任务链中，具体抄哪个作业可以在设置中选择。

这样完成了日常任务可以自动刷保全

**Comment by MistEO** [comment]
保全两三个小时就全刷完了啊

**Comment by Shawnsdaddy** [comment]
没有导航就得一直守着，，不然就可以直接脚本调用了随时启动（岂不美哉

**Comment by Shawnsdaddy** [comment]
目前Mower 的逻辑循环是

执行换班任务，-->>换班任务间隙每隔4小时调用maa清体力，做日常,开impart。等等

如果有肉鸽就是换班间隙无限刷肉鸽/生息演算。。

可是由于保全派驻maa没有导航，所以就无法用脚本调用直接自动刷  :( 就拴住了

希望支持一下导航

**Comment by Shawnsdaddy** [comment]
发现了只要选好队伍，保全是可以自己打的。。我自己加一个导航就OK了
