### ISSUE TITLE
win11系统安装docker之后无法连接模拟器

### ISSUE THREAD

**Issue by MC57348** [MaaAssistantArknights/MaaAssistantArknights#4698]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

由于个人原因需要用到docker，在安装完docker和liunx子系统后发现启动MAA无法连接至模拟器，更新或是删除重新安装模拟器亦或者调整管理员模式皆无法解决。自动检测链接也测试过了，不论开关都不行

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11424396/asst.log)

### 截图

![image](https://user-images.githubusercontent.com/52664742/236912227-694f8f81-101d-4f2c-a8f1-4bc0dfca2a83.png)
![image](https://user-images.githubusercontent.com/52664742/236912361-d046824e-b0fa-4928-9bce-42cb4a2364de.png)
![image](https://user-images.githubusercontent.com/52664742/236912532-f6bcc145-48d0-498f-9483-fcffc72c5eb5.png)
![image](https://user-images.githubusercontent.com/52664742/236912648-f2d706fc-b6d8-441c-931c-d28ea9eb4eba.png)

### 还有别的吗？

使用的是蓝叠模拟器（5.11.56.1003 N64），Win11

**Comment by MC57348** [comment]
自启动模拟器正常

**Comment by MC57348** [comment]
p64版本依旧无法解决
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11424620/asst.log)

**Comment by MC57348** [comment]
感觉像是蓝叠5和WSL2冲突了，就算开了hyper-v也解决不掉

**Comment by MC57348** [comment]
将链接地址修改为模拟器的ADB地址恢复正常

**Comment by MistEO** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/75f4bb24-d404-4d64-9402-a0749f45bd89)
https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7-hyper-v

**Comment by hxs0612** [comment]
我遇到了同样的问题，现已解决，当前连接设置为：

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/1966623/279089d6-accb-4ea4-bf59-c52c60c17340)

安装 docker 之前，连接地址的值为 `emulator-{port}`，我不太确定这个值是从哪来的，猜测是 MAA 自动设置的。在设置完 `Bluestacks.Config.Keyword` 和 `Bluestacks.Config.Path`，并且手动将连接地址改为 `localhost:{port}` 后可以正常连接蓝叠模拟器，重启后 MAA 也会自动更新 `port`。

猜测：

- 是否自动检测连接的功能只匹配了冒号的格式？
- 我是从 `v4.10.5` 版本开始使用的，连接地址的格式是否在版本更新时发生过变化？
