### ISSUE TITLE
识别不了铃兰的皮肤

### ISSUE THREAD

**Issue by yuetieqi-meow** [MaaAssistantArknights/MaaAssistantArknights#4700]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

铃兰的罗小黑联动皮肤在自动战斗自动编队中无法被识别、选中。
~~下面的上传显示是something went really wrong (我这边也只有edge和chorme用，都不太行)，截图似乎是可以的，暂时不知道怎么解决。~~

### 日志文件

出现问题的时间大约是6.45，后来6.52在提交前我又试了一次
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11425756/asst.log)

### 截图

![MuMu20230509065114](https://user-images.githubusercontent.com/44973544/236954934-06b3cbf9-36f1-41ba-8c63-a8df992593cc.png)
会卡在这里反复拖动

### 还有别的吗？

win10 经过检查更新为最新版本内测版 v4.16.5-alphaxxxx。模拟器是mumu，关卡是CW-EX-3，用的prts.plus搜索的作业。
> 准确来讲识别不了铃兰的皮肤只是我的猜测，没有经过严谨的验证orz。

>7.10补充。我换了铃兰的原皮，还是识别不了。每次窗口滑动会直接滑过，我手动把窗口滑回来是能点上并且更换技能的。

**Comment by ABA2396** [comment]
adb touch的问题不太好修，mumu的话还是点强制替换adb之后触控模式用minitouch或者maatouch吧
