### ISSUE TITLE
开始唤醒没有效果

### ISSUE THREAD

**Issue by kys321** [MaaAssistantArknights/MaaAssistantArknights#4701]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

雷电模拟器9。
记得一两周前的某个版本开始，开始唤醒任务就不能直接从模拟器初始页面自动点击明日方舟，然后开始唤醒了，需要手动打开mrfz才能执行唤醒操作。本来以为过一段时间就修复了，不过似乎现在还是没有解决，就还是提一下这个问题，辛苦各位了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11426309/asst.log)

### 截图

[https://p.sda1.dev/11/8437d2674fd920c81f6507cf14fdbf6a/RG2WU@KTG7P64R_3P__12`8.png](url)

[https://p.sda1.dev/11/9b0519ba6e59ac29eb5c82ca47601120/P@0_WZ_V9ZLP~9Y_PB_E29E.png](url)

![P@0 WZ V9ZLP~9Y{PB)E29E](https://user-images.githubusercontent.com/40566808/236969949-b2e6cb
![RG2WU@KTG7P64R$3P%}12`8](https://user-images.githubusercontent.com/40566808/236969960-12cecef1-421d-431a-a691-8da818c14c9a.png)
2b-4109-44f7-bbbe-c0a0608a88b1.png)

**Comment by kys321** [comment]
![P@0 WZ V9ZLP~9Y{PB)E29E](https://user-images.githubusercontent.com/40566808/236970102-6b9e2971-f94a-405b-a5c7-2839f560483c.png)

**Comment by MistEO** [comment]
设置里没选客户端版本

**Comment by kys321** [comment]
> 设置里没选客户端版本

感谢！，以前好像是默认官服的，就一直没在意过设置，更新以后重新下了一个就忘记改设置了
