### ISSUE TITLE
失败任务重复次数是不是太多了

### ISSUE THREAD

**Issue by stevetrs** [MaaAssistantArknights/MaaAssistantArknights#4703]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

比如说保全失败20次才确定失败退出；拜访好友任务中，没有集齐线索的好友的情况会重复5分钟才会失败退出

### 其他内容

拜访好友失败的log节选
2023.05.09 09:56:54     VisitNextOcr    action:ClickSelf
2023.05.09 09:56:54     VisitNextOcr    action:ClickSelf
2023.05.09 09:56:56     VisitNextOcr    action:ClickSelf
2023.05.09 09:56:56     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:03     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:03     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:04     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:04     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:06     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:06     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:12     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:12     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:14     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:14     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:15     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:16     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:18     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:18     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:22     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:22     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:24     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:24     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:26     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:26     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:34     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:34     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:36     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:36     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:38     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:38     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:44     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:45     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:47     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:47     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:49     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:49     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:55     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:55     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:56     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:56     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:58     VisitNextOcr    action:ClickSelf
2023.05.09 09:57:58     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:05     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:06     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:08     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:08     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:10     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:10     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:19     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:19     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:21     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:21     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:23     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:23     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:24     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:24     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:29     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:29     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:30     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:30     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:36     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:36     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:37     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:37     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:39     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:39     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:41     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:41     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:43     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:43     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:48     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:48     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:50     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:50     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:54     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:54     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:56     VisitNextOcr    action:ClickSelf
2023.05.09 09:58:56     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:01     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:01     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:02     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:02     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:04     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:04     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:05     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:05     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:10     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:10     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:12     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:12     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:13     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:13     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:18     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:18     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:19     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:19     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:21     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:21     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:25     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:25     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:27     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:27     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:28     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:28     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:32     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:32     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:34     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:34     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:35     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:35     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:40     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:40     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:41     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:41     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:43     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:43     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:48     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:48     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:50     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:50     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:51     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:51     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:56     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:56     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:58     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:58     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:59     VisitNextOcr    action:ClickSelf
2023.05.09 09:59:59     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:05     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:05     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:07     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:07     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:09     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:09     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:12     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:12     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:14     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:14     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:15     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:16     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:20     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:20     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:22     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:22     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:27     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:27     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:29     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:29     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:30     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:30     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:35     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:36     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:37     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:37     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:39     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:39     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:43     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:44     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:45     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:45     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:47     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:47     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:52     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:52     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:53     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:53     VisitNextOcr    action:ClickSelf
2023.05.09 10:00:59     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:00     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:01     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:01     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:03     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:03     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:07     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:07     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:09     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:09     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:13     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:13     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:15     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:15     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:16     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:16     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:21     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:21     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:23     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:23     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:25     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:25     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:33     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:33     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:35     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:35     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:36     VisitNextOcr    action:ClickSelf
2023.05.09 10:01:37     VisitNextOcr    action:ClickSelf

**Comment by ABA2396** [comment]
保全失败多少次是作业里写的，自己改成一次都行
