### ISSUE TITLE
繁中,日服 基建肉鴿自動戰鬥無法運作

### ISSUE THREAD

**Issue by lillhot** [MaaAssistantArknights/MaaAssistantArknights#4707]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

繁中服基建不會識別潔西卡
會一直左右滑但是不選她 換了皮膚也一樣

繁中服抄作業點了開始，它會顯示開始行動遊戲內卻沒反應(有換ADB了 也嘗試不同的觸控模式)

日服自動肉鴿會停在選擇肉鴿的頁面不會點進去

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11430357/asst.log)

**Comment by lillhot** [comment]
> 

無法自動戰鬥問題已解決
更新模擬器之後就好了
現在的問題是其他服沒辦法時停下幹員
所以會導致無法抄作業

**Comment by liuyifan-eric** [comment]
不同的issue可以分开来发

日服肉鸽选难度了吗
