### ISSUE TITLE
刷理智功能无法单独使用源石

### ISSUE THREAD

**Issue by DiscLRx** [MaaAssistantArknights/MaaAssistantArknights#471]
在还有剩余理智药的情况下，单独勾选吃石头选项，会直接判定为已完成刷理智任务

**Comment by DiscoIoR** [comment]
https://user-images.githubusercontent.com/91141853/167414689-67d459bf-99fb-4063-80e9-7a828e8243b4.mp4

**Comment by zzyyyl** [comment]
目前的设计上就是不能的单独吃源石的（

**Comment by zzyyyl** [comment]
这个问题在 #427 已经讨论过了
