### ISSUE TITLE
滑动寻找干员时减少单次滑动的长度

### ISSUE THREAD

**Issue by LinYanxi0** [MaaAssistantArknights/MaaAssistantArknights#4711]
### 说说你遇到的问题？

rt，假如说把现在的滑动长度定义为1，有时候要找的干员会在0.9的位置，滑动后只剩下部分可视，而maa无法识别，导致继续向后滑动，最后卡住
或者查找一段时间超时后向前按0.7的长度查找
（感觉不算bug又算bug，最后还是没放在bug里面）

**Comment by LinYanxi0** [comment]
佐证，此处在寻找星熊，建议考虑第二个倒找方案
![佐证](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/117924884/ff16b59b-ff72-4a72-af1a-11e54de0b5ae)

**Comment by LinYanxi0** [comment]
好的，感谢~
（顺便真的不考虑解决吗（

**Comment by LinYanxi0** [comment]
悲报，minitouch点不了（总之就是没反应）
换成adb并且重启就可以

**Comment by MistEO** [comment]
要强制替换下 adb （那行绿字

**Comment by MistEO** [comment]
> 好的，感谢~ （顺便真的不考虑解决吗（

这个问题是因为同样的参数 minitouch 滑动的又快又准，adb 又慢又错位。adb 现在就是完全没有任何优势的，所以才叫“兼容模式”

如果要解决需要所有滑动的地方给 adb 单独调参数，工作量巨大，而且 adb 又不好，用的人也少，干嘛要花这么大精力适配呢（

**Comment by LinYanxi0** [comment]
adb替换了一次后以后不用替换了是吗
辛苦解答了
