### ISSUE TITLE
水月肉鸽开局时，优先招募了预备干员，而非同职业3星干员

### ISSUE THREAD

**Issue by lighte42** [MaaAssistantArknights/MaaAssistantArknights#4712]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题
具体来说，是在我指定了异客开局的情况下，选择重术狙分队，maa会在开局招募狙击干员时招募预备狙击，而没有招募同为0希望的三星干员克洛斯。
我查看了resource/roguelike中的recruitment文档，发现克洛斯的recruitment priority是高于预备狙击的，因此认为这可能是一个bug。我也尝试了通过修改recruitment文档的方式来解决这一问题，但并没有成功。
我查看了历史issue，发现之前也有人提出过类似的问题，而随后的更新中也已做出相应优化。
但从我今天遇到的情况来看，问题似乎并没有完全解决？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11434895/asst.log)
我今天晚上的每把肉鸽开局都是这样的，如果要具体时间点的话，大概2点左右？

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129712871/12e0d525-a61e-455b-83dd-bdd5e230a367)
如图

### 还有别的吗？

雷电9模拟器

**Comment by lighte42** [comment]
补充一下，开局时的重装干员招募并没有出现这个问题，正常招募了斑点

**Comment by whatss7** [comment]
看了一圈代码，似乎是因为如果没有招募到一个“适合开局”的干员，则只能招募预备干员；而在第3次招募时，会因为太久没有招募到开局干员而强制取消上面的限制，所以斑点能正常招募。相关的逻辑在 `src\MaaCore\Task\Roguelike\RoguelikeRecruitTaskPlugin.cpp` 中。临时的解决方法大概就是在 `resource\roguelike\recruitment.json` 中给自己开局的干员加上 `"is_start": true`

**Comment by SherkeyXD** [comment]
现在还有这个问题吗
