### ISSUE TITLE
让新UI默认只能开一个MAA实例(allow single instance only)

### ISSUE THREAD

**Issue by pein0saga** [MaaAssistantArknights/MaaAssistantArknights#4713]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

1. 新UI MAA很容易开出来一堆多实例实在难受（特别是自己电脑做多件事情的时候），有时候改完设置才发现还有一个实例在托盘里
2. 大多数人都用不到多实例的情景，很多程序都是默认单实例，都是加个选项才能多实例
3. 两个不同模拟器运行多实例是小众需求；像我非流水线正经玩游戏，2个不同服务器客户端，都是装在同一个模拟器里。其他模拟器装其他游戏（因为有些时候需要一个模拟器锁1280分辨率）

**Comment by MistEO** [comment]
是个好主意，但涉及到 RPC 还挺复杂的，等一个有缘的佬来写（

**Comment by MC57348** [comment]
emmmm同时刷两个号的人今天更新完内测版感觉这个建议好难受

**Comment by pein0saga** [comment]
> emmmm同时刷两个号的人今天更新完内测版感觉这个建议好难受

1. 功能都是可选的（又不是永久关闭多实例功能），点一下就能永久切换的事情。

2. 我把它关了吧，只要不选中最小化到托盘，就还能接受

**Comment by MistEO** [comment]
这个功能不做了，带来的问题有点多。准备换个思路，弄成同一个程序多开配置的方案，若仅有一个配置，则只启动那一个实例

**Comment by ATFmxyl** [comment]
> emmmm同时刷两个号的人今天更新完内测版感觉这个建议好难受

加一,我也是挂着两个号,同一个模拟器开分身,然后不同端口来连接的

**Comment by pein0saga** [comment]
只要不选中"最小化时隐藏到托盘"，我觉得还行。之前主要是没看见任务栏运行的图标所致。

提出的建议会造成过多不必要的工作量，影响部分架构设计，甚至要考虑很多复杂场景，同时带来稳定性风险。

**Comment by pein0saga** [comment]
> 这个功能不做了，带来的问题有点多。准备换个思路，弄成同一个程序多开配置的方案，若仅有一个配置，则只启动那一个实例

因为各种原因，我现在也用上多开了。MaaX的多任务界面太香了！

https://github.com/MaaAssistantArknights/MaaX

**Comment by pein0saga** [comment]
> > 这个功能不做了，带来的问题有点多。准备换个思路，弄成同一个程序多开配置的方案，若仅有一个配置，则只启动那一个实例
> 
> 因为各种原因，我现在也用上多开了。MaaX的多任务界面太香了！
> 
> https://github.com/MaaAssistantArknights/MaaX

不知道为什么今天MAA-X界面涌现了巨量界面bug（版本没变），好在MAA主力还是很好用的，今天更新了配置功能，点赞！

**Comment by pein0saga** [comment]
> 多开配置的方案

多开配置的方案现在很成熟，基本上实现了所有梦想。外服适配也越来越完善了！~ o(^o^)o
