### ISSUE TITLE
国际服信用购物黑名单无效（可能大小写敏感导致未识别）

### ISSUE THREAD

**Issue by pein0saga** [MaaAssistantArknights/MaaAssistantArknights#4714]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

比如截图中的黑炭

看过别人的描述：

> 输错名字不行，但是你可以少输入几个字，比如 `加急凭证` 可以就输入 `加急`，甚至就一个 `急` 估计也没问题（
> 
> Although entering the wrong name can cause problems, substrings are allowed. For example, `加急凭证` can be expressed as `加急` , or even as `急`.
> 
> 信用商店目前的识别是有用 `replace_map`（`CreditShop-ProductName`，虽然就只有一个 _龙门币_ ）来避免一些识别错误的。
> 我目前为止还没有出现识别错误的情况，如果有发现识别错误可以提一个 issue。

_Originally posted by @zzyyyl in https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1021#issuecomment-1168723874_

我姑且先改成Carbon试试这两天行不行

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11438333/asst.log)

### 截图

<img width="689" alt="Snipaste_2023-05-10_13-05-25" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/2074641/03b7ac4c-d079-4367-bd72-e6645d10cc7b">

**Comment by MistEO** [comment]
填游戏客户端的语言（英文），大小写敏感
