### ISSUE TITLE
自动战斗无法识别神秘代码关卡（软件已经更新到最新版）

### ISSUE THREAD

**Issue by Nicholls01** [MaaAssistantArknights/MaaAssistantArknights#4716]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗时，通过神秘代码进行自动战斗显示“不支持的关卡，请更新软件版本”；但是软件更新显示已经是最新版

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11439993/asst.zip)

### 截图

<img width="821" alt="MAA" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92327881/ffda096c-98a7-412a-8435-61eebf233fa9">

### 还有别的吗？

使用MUMU模拟器，系统配置：
处理器	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
机带 RAM	8.00 GB (7.88 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入
版本	Windows 10 家庭中文版
版本号	22H2
安装日期	‎2021/‎6/‎15
操作系统内部版本	19045.2846
体验	Windows Feature Experience Pack 120.2212.4190.0

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/567c6021-ae3a-48cd-9617-fccab6900fa9)

**Comment by MistEO** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/9a2591b4-070f-4d42-8577-e79d5606d7e1)
