### ISSUE TITLE
关卡内无法识别塞雷亚【铁律】皮肤

### ISSUE THREAD

**Issue by helloIris415** [MaaAssistantArknights/MaaAssistantArknights#4717]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗编队界面可抓取塞雷亚铁律皮肤。
战斗关卡内无法识别铁律皮肤头像，导致无法放置。
实测换成坚城皮肤即可正常被识别放置。
asst指路，2023/5/10  18:32铁律无法放置;18:34坚城正常放置;18:38铁律无法正常放置。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11440932/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63986965/0b54c816-12c7-4257-a900-a0de267088ce)

### 还有别的吗？

已测试蓝叠，雷神，MUMU安卓6，MUMU安卓12。均发生相同问题

**Comment by ntgmc** [comment]
大概率（99%）缓存错误
