### ISSUE TITLE
能否新增 运行时将maa的日志同步发送至某网址（服务器） 这一功能？

### ISSUE THREAD

**Issue by saddestboy** [MaaAssistantArknights/MaaAssistantArknights#4719]
### 在提问之前...

- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

人不在电脑边，电脑上打的时候在手机上看不到进度

### 有什么好的想法？

这样可以远程知道电脑上maa的运行状况（比如利用自建ntfy服务器就可以查看当前maa打到了哪里）

**Comment by MistEO** [comment]
都可以自建 server 了，写个脚本每隔一分钟上传一次就行吧。 asst/gui.log
