### ISSUE TITLE
基建-贸易站换班卡住

### ISSUE THREAD

**Issue by teiume** [MaaAssistantArknights/MaaAssistantArknights#472]
问题描述：在基建换班时候，当贸易站中是【卡夫卡】【龙舌兰】【巫恋】3人时，会一直停留在贸易站页面不会继续下去。
使用模拟器：BlueStacks 5
版本：3.3.1和3.3.2均发现此问题
截图：
【卡夫卡】【龙舌兰】【巫恋】3人时，会一直停留在如下的页面。
![image](https://user-images.githubusercontent.com/28856455/167434901-b256b4d7-da5e-4b76-8f99-4b085cb1f18e.png)
当手动停止MAA后，模拟器页面则跳转为选择更换干员。
![image](https://user-images.githubusercontent.com/28856455/167435306-2488ede6-5270-47eb-913e-f5bc2e4b4744.png)

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8652663/asst.log)

**Comment by MistEO** [comment]
卡住的原因是没有赤金了却选择了无人机加速贸易站。之后的版本会尝试修复一下，但这个优先级可能不高（
