### ISSUE TITLE
干员识别错误

### ISSUE THREAD

**Issue by WangYiWallis** [MaaAssistantArknights/MaaAssistantArknights#4727]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

大量拥有干员识别失败

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11447483/asst.log)

出现在末尾

### 截图

[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11447497/oper.zip)

由于文件大小限制，将oper问价夹中的中间过程的截图拆分成两部分，另一部分在【还有别的吗？】栏目中

### 还有别的吗？

[oper2.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11447498/oper2.zip)

**Comment by MistEO** [comment]
干员识别内测版修了一个很严重的bug，再下一个正式版如果还有问题麻烦再提一下
