### ISSUE TITLE
MAC版MAA滑动速度过快

### ISSUE THREAD

**Issue by EricWangxy** [MaaAssistantArknights/MaaAssistantArknights#4728]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，自动战斗cw-8时自动化的时候滑动过快导致识别问题，但是windows版没有这个问题

### 日志文件

mac找不到这个debug文件夹或者asst.log

### 截图

滑动前
<img width="1478" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43486704/1b48512c-8ef0-435a-8231-51ff9f00d220">
滑动后
<img width="1478" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43486704/d685395a-07f9-4464-ac6a-8084619218f7">

### 还有别的吗？

m2芯片 playcover版maa

**Comment by ABA2396** [comment]
@hguandl
