### ISSUE TITLE
肉鸽放置干员老是卡住或者失败

### ISSUE THREAD

**Issue by Jseca666** [MaaAssistantArknights/MaaAssistantArknights#4729]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图所示打肉鸽的时候，放置干员时经常无法正常部署方向，而卡住，尝试更新过公测版，内侧版，稳定版，最新版本，更换过minitouch，maatouch，adb input等各种点击方式，因为是多开，也尝试过只开一个，依然有这样的情况，使用的是蓝叠模拟器，均有这个问题，很频繁，完整的正常部署一轮很难

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11448333/asst.log)

### 截图

![Screenshot_2023 05 11_13 14 59 165](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75114030/e598e46c-3a57-4fbf-8b97-39460997f820)
![Screenshot_2023 05 11_13 14 45 296](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75114030/0f797330-2248-45d5-9ab2-5c86a6a7cec1)
![Screenshot_2023 05 11_13 14 59 165](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75114030/bc17c5d7-94c6-4dee-aadd-97c04e89d7b6)

### 还有别的吗？

设备名称	LAPTOP-HF2EA0OH
处理器	Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz   2.11 GHz
机带 RAM	16.0 GB (15.8 GB 可用)
设备 ID	645A5B2C-93AA-42AD-BB25-4150E121D350
产品 ID	00342-35659-29736-AAOEM
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

**Comment by MistEO** [comment]
卡在哪了，图二？图一和三是什么，你手动点了暂停还是啥

**Comment by Jseca666** [comment]
> 卡在哪了，图二？图一和三是什么，你手动点了暂停还是啥
 就是和图中一样卡住，单开一个模拟器也一样，有时候是因为莫名其妙的暂停，不会自己点继续，有时候是因为部署不下干员

**Comment by MistEO** [comment]
你开了“暂停下干员”吗，这个不太稳定，关掉试试

**Comment by Jseca666** [comment]
> 你开了“暂停下干员”吗，这个不太稳定，关掉试试

没有呀没有呀，我没开那个

**Comment by popcat-popcat** [comment]
日服魁影肉鴿也是同樣的問題
投資源石錐選擇刷第一層之後退出
刷了一段時間會造成幹員放置失敗因此探險失敗
