### ISSUE TITLE
新版MuMu模拟器12选“开始唤醒”不能自动打开游戏，手动打开后MAA可以正常操作登录

### ISSUE THREAD

**Issue by Nothing1031** [MaaAssistantArknights/MaaAssistantArknights#4730]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用的MuMu模拟器12，MAA也是更新到了最新版本，勾选了“开始唤醒”任务之后开始执行，不会自动打开明日方舟，需要手动模拟器内点开游戏，之后MAA的操作都正常

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11450909/asst.log)

文件里最新的日志应该都是尝试唤醒的操作；实际在5/11 18:00 之后还有过操作，但是日志文件没有更新修改

**Comment by ABA2396** [comment]
设置里选了游戏客户端吗

**Comment by Nothing1031** [comment]
> 设置里选了游戏客户端吗

啊这...没选，选了类型之后可以打开了；我刚换了电脑，之前用MAA的时候不记得要设置客户端类型啊

**Comment by ABA2396** [comment]
没设置只能在游戏的“开始唤醒”界面开始任务，而选了客户端类型才能在桌面开始执行，是不是之前填的是应用的快捷方式所以打开模拟器后直接启动应用了

**Comment by Nothing1031** [comment]
> 没设置只能在游戏的“开始唤醒”界面开始任务，而选了客户端类型才能在桌面开始执行，是不是之前填的是应用的快捷方式所以打开模拟器后直接启动应用了

MAA不能记住之前选过的客户端类型吗？我能确定的是之前模拟器打开肯定只到桌面，游戏是MAA打开的，有可能是之前无意中设置过客户端类型；但是现在看MAA每次打开又不会记住之前的客户端类型...有点迷

**Comment by Nothing1031** [comment]
> > MAA不能记住之前选过的客户端类型吗？我能确定的是之前模拟器打开肯定只到桌面，游戏是MAA打开的，有可能是之前无意中设置过客户端类型；但是现在看MAA每次打开又不会记住之前的客户端类型...有点迷
> 
> 啥版本？我这里试了下重启都能保存的啊

v4.16.4

**Comment by Nothing1031** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11451424/gui.log)

发现了，要管理员运行才能保存设置的客户端类型，连日志都是管理员运行之后才更新的

**Comment by Nothing1031** [comment]
> [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11451424/gui.log)
> 
> 发现了，要管理员运行才能保存设置的客户端类型，连日志都是管理员运行之后才更新的

17:56 到19:09之间一直有在用的
