### ISSUE TITLE
maa是用管理员权限打开的，但是依旧显示错误，无法与mumu模拟器连接成功。

### ISSUE THREAD

**Issue by xc330816003** [MaaAssistantArknights/MaaAssistantArknights#4733]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa是用管理员权限打开的，但是依旧显示错误，无法与mumu模拟器连接成功。
MAA 遇到了问题
文件“D:\mumu\emulator\nemu\vmonitor\bin\adb_server.exe”正由另一进程使用，因此该进程无法访问此文件。
解决方案
请使用管理员权限打开 MAA 进行操作
详细信息
System.IO.IOException: 文件“D:\mumu\emulator\nemu\vmonitor\bin\adb_server.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ReplaceADB>b__415_1()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ReplaceADB>d__415.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

大约5月10号之前就这样了，重新下载也没有解决。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11453908/asst.log)

**Comment by ABA2396** [comment]
> 文件“D:\mumu\emulator\nemu\vmonitor\bin\adb_server.exe”正由另一进程使用，因此该进程无法访问此文件。

把mumu先关了，在任务管理器里把 adb_server.exe 进程结束了再替换
