### ISSUE TITLE
使用雷电模拟器时，一个进程有时会占满cpu，导致很卡

### ISSUE THREAD

**Issue by gotomoon1999** [MaaAssistantArknights/MaaAssistantArknights#4736]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Virtualbox headless frontend进程
但不用maa，这个进程就只会占30左右，用了之后有时候会直接爆cpu

### 日志文件

1

### 还有别的吗？

雷电模拟器9，win10，i5-8300H

**Comment by MistEO** [comment]
雷电的问题，这个是雷电的进程
