### ISSUE TITLE
实体安卓设备似乎无法完全正常工作

### ISSUE THREAD

**Issue by KJZH001** [MaaAssistantArknights/MaaAssistantArknights#4739]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

设备为 vivo真机，系统为安卓11

按照文档中的说明步骤手动配置好连接设置后，大部分时候会返回`截图失败/打开客户端失败/连接模拟器失败`的log，请参见下下个环节的截图1、2

其中有过一次程序能够正常打开游戏，但是后续依然没有反应，也有过一次提示分辨率异常，不过总的来说基本上都是没有正常工作过

在启动MAA前使用adb修改过屏幕分辨率，并且在adb shell中能够正常的和手机的安卓内核进行通讯，因此我确定我的adb工作应当正常

后续重置为原始分辨率后我使用`adb exec-out screencap -p > 1.png`测试，能够正常的捕获屏幕截图，请参见下下个环节的截图3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11462968/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11462969/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29683578/22d4b9dd-f5b3-4c11-8055-52bab20cbb3a)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29683578/9e173f86-2c1c-4720-9ce8-d7b04f8b0b15)
![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29683578/1e9a968e-cb5f-4bc6-8cd3-3059297fcec5)

### 还有别的吗？

windows 11家庭版，[ADB]Android-platform-tools_r33.0.3-windows

看起来和 #4539 情况类似，但是我的比较严重，且我们都是使用vivo设备产生的问题，个人推测可能与此厂商的系统魔改有关

这个问题我还尝试过使用`taskkill /im adb.exe /f`杀掉adb进程让MAA来自行启动，但是没有什么作用

ps.所有的触控模式都尝试过

**Comment by HydrogenDeuterium** [comment]
强制替换adb试试看呢

**Comment by MistEO** [comment]
触控模式用 Adb input 兼容模式
连接配置用 `兼容模式` / `通用模式（屏蔽异常输出）`
试试看

日志有点乱，方便的话最好分一下，每种 case 对应一个日志文件，不然不太好翻

**Comment by MistEO** [comment]
连接配置 `第二分辨率` 这个也可以试一下

**Comment by KJZH001** [comment]
> 强制替换adb试试看呢

因为我的adb是之前从developer.android.com获取用于开发的，而且adb通常都是来自于这里，我不太认为我现有的adb工具和程序内置的替换程序有所差别
所以我会把**强制替换**这个作为备选方案，如果别的办法不行的话我会尝试一下的，但不是现在

**Comment by KJZH001** [comment]
> 连接配置 `第二分辨率` 这个也可以试一下

好的，我会尝试一下，并且会把log单独分出来

另外有个比较奇怪的地方我想问一下，我为了调用方便之前就把adb写到环境变量去了，但是为什么MAA好像没有自动识别到呢？手动配置之后倒是可以正常使用

**Comment by KJZH001** [comment]
```
C:\Users\MoeSakura>adb shell wm size
* daemon not running; starting now at tcp:5037
* daemon started successfully
Physical size: 1080x2408

C:\Users\MoeSakura>adb shell wm size 1080x1920
```
兼容模式+Adb input 返回 分辨率不支持
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11487929/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11487932/gui.log)

**Comment by KJZH001** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29683578/bb18b02d-961b-4ad0-b64d-e91d2fb36937)
通用模式（屏蔽异常输出）+Adb input
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11487973/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11487974/gui.log)
能够正常从桌面拉起游戏，然后就没有然后了，返回了无法获取截图

**Comment by MistEO** [comment]
不用了，这几个模式就是专门给手机或者云手机之类的设备准备的，之前有人提过类似的问题。

不过这几个选项描述不够直观，或许之后我们会改改文档或者这个名字

**Comment by HydrogenDeuterium** [comment]
> > 连接配置 `第二分辨率` 这个也可以试一下
> 
> 好的，我会尝试一下，并且会把log单独分出来
> 
> 另外有个比较奇怪的地方我想问一下，我为了调用方便之前就把adb写到环境变量去了，但是为什么MAA好像没有自动识别到呢？手动配置之后倒是可以正常使用

我的adb也是在环境变量里，adb地址填写“adb”就可以用

**Comment by KJZH001** [comment]
> 不用了，这几个模式就是专门给手机或者云手机之类的设备准备的，之前有人提过类似的问题。
> 
> 不过这几个选项描述不够直观，或许之后我们会改改文档或者这个名字

改文档确实是个不错的主意，因为文档中似乎也没有对于各个不同的选项的差别之处写的足够明白

另外我建议修改一下程序界面中`模拟器`这个称呼，既然现在已经不仅仅是支持模拟器了，那么趁早将它修改一下比较好
比如说修改为`目标设备`，这个词称呼实体设备和虚拟机都没有什么问题，也可以防止引起误解

**Comment by KJZH001** [comment]
以及我昨天尝试了一下自动作业功能，我发现了一些问题
在自动识别选择干员的时候偶尔会卡住。一直在滑动屏幕但是找不到干员，然后手动切换到全部干员的分类去就能够找到了
另外能否考虑一下增加个这方面的辅助功能，在日志里输出一下当前在找哪个干员，而不是已经选了才打印出来
这样卡住了也不知道是哪个干员的造成的问题

而且考虑到比较容易在选干员的时候卡住，不妨给个干员的选择顺序的列表，允许用户按照顺序手动选好干员直接跳过强制选择的环节，这样可以在一定程度上保证程序的可用性

这些是我的一些建议，希望可以起到一些参考的上的帮助

**Comment by HydrogenDeuterium** [comment]
我今天在新电脑上也遇到了“打开客户端失败，请检查配置文件”这个问题。
特征是删掉gui.json之后第一次只会报错连不上，第二次之后报这个错然后疯狂截图失败。
我用旧电脑的 gui.json 复制到新电脑上，第一次可以正常工作，第二次就打开客户端失败

**Comment by HydrogenDeuterium** [comment]
> 我今天在新电脑上也遇到了“打开客户端失败，请检查配置文件”这个问题。 特征是删掉gui.json之后第一次只会报错连不上，第二次之后报这个错然后疯狂截图失败。 我用旧电脑的 gui.json 复制到新电脑上，第一次可以正常工作，第二次就打开客户端失败

版本一致都是4.17.1

**Comment by KJZH001** [comment]
> > 我今天在新电脑上也遇到了“打开客户端失败，请检查配置文件”这个问题。 特征是删掉gui.json之后第一次只会报错连不上，第二次之后报这个错然后疯狂截图失败。 我用旧电脑的 gui.json 复制到新电脑上，第一次可以正常工作，第二次就打开客户端失败
> 
> 版本一致都是4.17.1

不妨试一下按照 @MistEO 此前回复我的步骤？我的设备在修改到第二分辨率模式后工作目前看起来基本功能没有什么问题，已经稳定用了好几天了

**Comment by KJZH001** [comment]
> 以及我昨天尝试了一下自动作业功能，我发现了一些问题 在自动识别选择干员的时候偶尔会卡住。一直在滑动屏幕但是找不到干员，然后手动切换到全部干员的分类去就能够找到了 另外能否考虑一下增加个这方面的辅助功能，在日志里输出一下当前在找哪个干员，而不是已经选了才打印出来 这样卡住了也不知道是哪个干员的造成的问题
> 
> 而且考虑到比较容易在选干员的时候卡住，不妨给个干员的选择顺序的列表，允许用户按照顺序手动选好干员直接跳过强制选择的环节，这样可以在一定程度上保证程序的可用性
> 
> 这些是我的一些建议，希望可以起到一些参考的上的帮助

emmn...好吧，今天注意到似乎已经支持手动编队了（针不戳）
