### ISSUE TITLE
干员技能无法释放

### ISSUE THREAD

**Issue by NiuHK** [MaaAssistantArknights/MaaAssistantArknights#4741]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

干员令部署在左上角时出现进入技能释放页面但是释放不了的情况，通过测试上传的cw-8正常，cw-10出错，大概可以确定是点击位置有问题了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11464594/asst.log)
这log应该帮助不大（）

### 截图

![屏幕截图_20230512_212645](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129147116/86ced5e5-4623-4f9b-9cae-dbfa4cc73d53)
cw-8正常运行的位置
![屏幕截图_20230512_212520](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129147116/70d7c8cd-0c05-4e21-b030-d236a95c5940)
cw-10有问题的位置

### 还有别的吗？

自己翻了翻感觉可以在这个位置先调一调，但是不太清楚这个坐标是怎么算的，flag又是哪个
.\MAA-v4.16.4-win-x64\resource\tasks.json
10088行
    "RoguelikeSkillSelectionMove3": {
        "algorithm": "JustReturn",
        "rectMove_Doc": "技能3相对flag的坐标",
        "rectMove": [
            300,
            -40,
            30,
            30
        ]
    },

**Comment by ntgmc** [comment]
Duplicate of #4345

**Comment by NiuHK** [comment]
emmm能不能麻烦告知下这个flag是个啥，坐标在哪儿，我现自己修修用上，主要maa模拟点击不显示点击的地方自己没的调试

**Comment by ntgmc** [comment]
> emmm能不能麻烦告知下这个flag是个啥，坐标在哪儿，我现自己修修用上，主要maa模拟点击不显示点击的地方自己没的调试

你这个是肉鸽编队选择三技能相对flag坐标

**Comment by ABA2396** [comment]
用minitouch，模拟器打开触摸显示，是有点击位置显示的

**Comment by NiuHK** [comment]
> > emmm能不能麻烦告知下这个flag是个啥，坐标在哪儿，我现自己修修用上，主要maa模拟点击不显示点击的地方自己没的调试
> 
> 你这个是肉鸽编队选择三技能相对flag坐标

好的多谢多谢，我说怎么咋算咋不对🥲

**Comment by HydrogenDeuterium** [comment]
> 用minitouch，模拟器打开触摸显示，是有点击位置显示的

是开发者选项里那个“显示触控反馈”吗？我开了那个，还是看不到maa的点击位置显示。
