### ISSUE TITLE
晚上挂机打自动肉鸽，每天凌晨4点更新后就会在签到页面卡住

### ISSUE THREAD

**Issue by yellowbill** [MaaAssistantArknights/MaaAssistantArknights#4745]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我用的是内测版本MAA，晚上设置自动打肉鸽，每次都会卡在4点的签到界面，一直挂机没有反应，早上起来时截图如下，最近好像都这样

### 日志文件

[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11468509/asst.-.zip)

### 截图

![捕获](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90031085/b55ae988-6664-4a0b-83d1-02a2153b9220)
![捕获1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90031085/92371eaa-1a86-43a0-b2c4-bb87b163ca26)

**Comment by SherkeyXD** [comment]
Move to #5273
