### ISSUE TITLE
需要一个保全派驻的干员击倒检测和处理功能

### ISSUE THREAD

**Issue by pingplug** [MaaAssistantArknights/MaaAssistantArknights#4746]
### 说说你遇到的问题？

保全中干员被击倒后到撤退之间还有一段时间，理论上通过叠干员还有机会救一下，但是目前抄作业的时候似乎会不管，导致阵线崩溃。

1. 现在是否支持识别保全的干员击倒状态？
2. 现在的作业API是否支持对干员击倒的处理？
3. 现在的作业是否有支持处理此情况的？

**Comment by Constrat** [comment]
1. No, there is no code to identify when an operator has been knocked
2. The copilot.json does not support the option of what to do if an operator has been knocked
3. Same as 2., we currently do not have any type of algorithm / task to detect it, so all other options are ~~off~~
