### ISSUE TITLE
读取文件失败

### ISSUE THREAD

**Issue by CoronaAustralis** [MaaAssistantArknights/MaaAssistantArknights#4748]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

孤星ex关卡自动作业不能使用
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73533338/04441794-bff4-4cbd-b0a6-18b2e8125b08)
同时在所有的json文件中也找不到ex关卡的信息，最新的只有cw-10的
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73533338/351cba82-fbff-420a-8dfb-bcdae4b76154)

### 日志文件

log文件无异常，maa版本为4.16.4，并且这是我今天5.13才在官网下载的

**Comment by ABA2396** [comment]
更新内测版。

**Comment by MistEO** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/29849d2b-359a-41c0-be34-c6f643be320e)

**Comment by mai1015** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/5039212/fd06b154-9f83-4b5b-8fc6-8c6c09e6e815)
@MistEO 确实还是相同问题，不管是下载文件还是使用神秘代码。

**Comment by MistEO** [comment]
不是一个问题，提示都不一样。重新提个 Issue 发下日志看看

**Comment by MistEO** [comment]
@mai1015 你是不是用了作业站的保全派驻作业，作业站后端有 bug，传下来的就是错的。保全有内置的，用这个，一模一样的

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/b2e7897b-042e-4f1e-b8a4-6a73da4f2f0d)
