### ISSUE TITLE
保全派驻开局干员的替换处理

### ISSUE THREAD

**Issue by pingplug** [MaaAssistantArknights/MaaAssistantArknights#4750]
### 说说你遇到的问题？

保全派驻开局可以选择四名干员进行替换，这相当于多了四个抽牌机会，提升主C或T被抽出的概率，但是目前的作业里并没有处理。

1. 抄作业的API是否提供干员重要性权重的选项，便于选择替换的干员？
2. 对于现有作业，能否提供一个自动设置干员权重的算法？（比如主C或主T权重为1，素材干员为0.5，其他干员为0，甚至再加上干员费用等因素）

**Comment by Constrat** [comment]
Too much work to implement and not needed:
with a good copilot json you can clear SSS towers without major issues with some levelled operators.
