### ISSUE TITLE
为使用hyper-v版蓝叠修改gui.json后修改ip地址无效，无法连接其他地址

### ISSUE THREAD

**Issue by ToumaLover** [MaaAssistantArknights/MaaAssistantArknights#4752]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

按照[文档](https://maa.plus/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.html)向gui.json中添加了
`"Bluestacks.Config.Path":"C:\\ProgramData\\BlueStacks_nxt\\bluestacks.conf",`
`"Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port",`
两行，可以自动识别蓝叠的adb地址

在连接设置中修改模式为通用模式并填写局域网手机地址后，切换回一键长草页，标题为局域网地址，点击link start后，标题变为127.0.0.1的蓝叠adb地址，同时maa向蓝叠地址连接，无法连接局域网手机adb地址

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11470191/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11470192/gui.log)

asst.log内没有出现局域网ip，可能问题出现在gui，但gui.log也没有相关内容

### 还有别的吗？

maa版本1.16.4 平台windows

复现步骤:新解压maa的zip
启动一次并设置adb地址
关闭maa，修改gui.json
启动maa，连接设置内地址不填，模式选择蓝叠，link start正常
连接设置内地址填写，模式选择通用，切换回一键长草页，标题为局域网地址，点击link start后，标题变为127.0.0.1的蓝叠adb地址，同时maa向蓝叠地址连接

**Comment by MC57348** [comment]
要不你先试试不按照文档先跑一下呢？

**Comment by ABA2396** [comment]
写了蓝叠的这个就强制变了

**Comment by ToumaLover** [comment]
> 写了蓝叠的这个就强制变了

明白了，那可以请您修改一下文档吗？注明添加蓝叠conf位置之后，连接设置里的地址和模式都会失效，避免我这样的误解

**Comment by ABA2396** [comment]
> > 写了蓝叠的这个就强制变了
> 
> 明白了，那可以请您修改一下文档吗？注明添加蓝叠conf位置之后，连接设置里的地址和模式都会失效，避免我这样的误解

还是改下逻辑吧，改成写了这个字段且模拟器选择为蓝叠才变？ @MistEO

**Comment by MistEO** [comment]
要不发现设置过 conf，就把界面上的配置和地址都 disable 掉

**Comment by ABA2396** [comment]
> 要不发现设置过 conf，就把界面上的配置和地址都 disable 掉

现在不是说要蓝叠和其他模拟器或手机换着连吗

**Comment by MistEO** [comment]
现在改成需要勾选“自动检测连接”才检测 config 了
