### ISSUE TITLE
自动编队因职业tab切换问题导致无法选择干员

### ISSUE THREAD

**Issue by sileence114** [MaaAssistantArknights/MaaAssistantArknights#4756]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

这个是游戏的问题：选择干员时切换特种职业tab，然后拉到底。然后再去点重装tab，重装页面并没有回到页首……

如果作业里面选了一个一级的高速再部署特种，然后再去重装页面选了个满配的重装，就会直接寄在这一步。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11471193/asst.log)

### 截图

屏幕录像在[`MAA作业裙/使用问题/Issue#4756 的录像`](https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&appChannel=share&inviteCode=204jmYKouL8&contentID=1lba0a&businessType=2&from=181074&biz=ka&mainSourceId=share&subSourceId=others&jumpsource=shorturl)。录像超过了10M传不上来。有稳定版和测试版的录像。

update: 浏览器上打开QQ频道的帖子链接后发现能把视频链接扒下来……

稳定版：在1:08找到砾后就找不到塞雷娅了。
http://qchannelvideo.photo.qq.com/50154_0bc37bvbycia7uagxp3aansov6gddtbaa3ca.f104002.mp4?dis_k=8cccb0ee668066a9dc95f06009de736c&dis_t=1684058772

测试版：复现了这个问题。 
http://qchannelvideo.photo.qq.com/50154_0bc37bvbycia7uagxp3aansov6gddtbaa3ca.f104002.mp4?dis_k=8cccb0ee668066a9dc95f06009de736c&dis_t=1684058772

**Comment by ABA2396** [comment]
感觉像是方舟的bug，我还没试出稳定的不返回第一页的情况）

**Comment by sileence114** [comment]
> 感觉像是方舟的bug，我还没试出稳定的不返回第一页的情况）

方舟那边咱管不到……或许可以在切换tab之后再执行一下滚动到页面头部的操作？

**Comment by sileence114** [comment]
我尝试复现了一下方舟的这个bug，有以下要点：
1. 选5个干员，不包括重装、特种。
2. 切到特种tab拉到底，然后第六个选最后一页的特种。
3. 然后再切到重装，就寄了。
