### ISSUE TITLE
希望能增加一键回到默认(出厂)设置的功能

### ISSUE THREAD

**Issue by MisterCoBen** [MaaAssistantArknights/MaaAssistantArknights#4757]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在更换模拟器时，无法自动更换adb路径或模拟器类型 (手动也不行), (也可能是我格式错了)， 顺便防止手动负优化及快速排查问题

**Comment by ABA2396** [comment]
把文件夹下的 config 删了就重置了
