### ISSUE TITLE
麒麟X夜刀无法识别

### ISSUE THREAD

**Issue by HNHYJ** [MaaAssistantArknights/MaaAssistantArknights#4758]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在干员识别中两次无法识别麒麟X夜刀

### 日志文件

2023-05-15 11:11~2023-05-15 11:15
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11473916/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/133621423/c0fc785a-dce4-4607-a4bf-cafa6fdf3cf5)

### 还有别的吗？

MuMu模拟器

**Comment by pein0saga** [comment]
我这边可以成功识别（右下角）

<img width="381" alt="Snipaste_2023-05-18_05-17-31" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/2074641/16ce50fc-b55e-44f1-8837-603dbb4488ec">

**Comment by pein0saga** [comment]
你的日志里面，麒麟X夜刀 false，麒鳞X夜刀 true

“麟”被识别成了“鳞”， 临时解决就用ocr replace

**Comment by MistEO** [comment]
没赶上发版，下个版本修复
