### ISSUE TITLE
水月肉鸽会在藏品界面卡住，无法返回

### ISSUE THREAD

**Issue by exgarburner** [MaaAssistantArknights/MaaAssistantArknights#4759]
### 说说你遇到的问题？

水月肉鸽在自动战斗的过程中会偶然点到藏品界面，maa无法识别并一直执行退出肉鸽的指令，触发方式不明。

**Comment by ovcc** [comment]
同样遇到、感觉下来是 低难度下 难度2、3的情况下， 打到4、5层 藏品多了就会 高概率点到藏品界面 ，然后就无法识别 并一直执行退出肉鸽的指令。难度上到4的情况 我练度一般通不过 3、4层 就没有触发过了。

**Comment by 10969qaq** [comment]
用的mumu 宽1280  高720 dpi240 也会遇到这个问题 刷肉鸽mma会莫名其妙点藏品然后卡在这个画面然后mma显示已放弃本次探索卡个几个小时也是停在这个画面

**Comment by pein0saga** [comment]
> 用的mumu 宽1280 高720 dpi240 也会遇到这个问题 刷肉鸽mma会莫名其妙点藏品然后卡在这个画面然后mma显示已放弃本次探索卡个几个小时也是停在这个画面

我用ALAS mumu也是容易频繁出各种问题，之前夜神就少一些。

**Comment by BirdBoss50** [comment]
跟楼上一模一样，mumu模拟器6， 1280 * 720分辨率，心胜于物百嘉开局藏品一多就会点开藏品界面然后卡死，日志里一直显示已放弃本次探索。如果基于图像识别的话这个应该好修...？我暂时还没明白为什么会有这个bug，盲猜是藏品界面选项长得太像得偿所愿，点进去又不符合得偿所愿的界面直接傻眼，超过6分钟触发防卡死机制尝试退出，但是藏品界面把登出键覆盖了所以找不到登出键...

**Comment by icescotch** [comment]
6.24 mumu模拟器同样有这个问题

**Comment by Diamond01010111** [comment]
我用的雷电模拟器也有这个问题

**Comment by Lancarus** [comment]
duplicate of #5892
