### ISSUE TITLE
建议增加自定义基建排班

### ISSUE THREAD

**Issue by AshHuangQ** [MaaAssistantArknights/MaaAssistantArknights#476]
只要可以设置2套固定组合就好了

**Comment by lider8403** [comment]
不一定非要两套固定组合。人工指定：办公室1、办公室2；会客厅1、会客厅2；制造所1、2、3、4……；贸易站1、2、3、4……；发电站1、2、3……；有体力的情况下，优先选择排名靠前的组合上场。

**Comment by MistEO** [comment]
不会去做，目前的计划是做全局最优解。但即使是现在局部最优解的情况下，我感觉大部分用户自己排的班效率压根不如算出来的

**Comment by lider8403** [comment]
> 

我自己试了几天，通过基建报告确定，目前的局部最优解比我自己243三班倒效率低一些，所以现在已经切回手动换班了。
而且对休息室的利用有些问题，有很多空置的位置没有使用，本来放在休息室吃信赖的干员却被移走了。
期待你们的全局最优解。
