### ISSUE TITLE
如果游戏停在主页吃药界面，开始刷理智会报任务出错

### ISSUE THREAD

**Issue by CharlesChou73** [MaaAssistantArknights/MaaAssistantArknights#4760]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天也充当了一把在酒吧里点炒饭的用户~ 应该是返回主页的逻辑没有覆盖这种情况

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11475169/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16950543/f598dbad-76ae-431b-871e-9a1789c409cb)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16950543/99d3d457-771a-45a2-8b7e-483d8c49836f)

**Comment by MistEO** [comment]
开摆（

**Comment by liuyifan-eric** [comment]
其实有很多地方返回主页的逻辑没做（
