### ISSUE TITLE
刷理智时，如果”指定次数“和”指定材料“都不选择，则隐藏”剩余理智“一栏

### ISSUE THREAD

**Issue by CharlesChou73** [MaaAssistantArknights/MaaAssistantArknights#4761]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

偶尔会出现选关卡时点到”剩余理智“上，结果按”关卡选择“的默认值刷了一大堆。

### 有什么好的想法？

不需要“剩余关卡”时隐藏掉，减少误操作。

**Comment by Rbqwow** [comment]
有没有一种可能 设置里可以关闭剩余理智功能

**Comment by CharlesChou73** [comment]
> 有没有一种可能 设置里可以关闭剩余理智功能

如果我需要用再去设置里点开，用完再关掉么，这个设计我觉得可以改进。

**Comment by Rbqwow** [comment]
但是指定次数&指定材料与剩余理智之间并没有关联 这两种功能相互独立 应用场景也并不重合 仅仅因为「手误」而添加一个会给更多人带来困扰的容错型功能看起来并不适合
**当然这只是我个人看法** 毕竟这个因用户操作错误而带来的问题非常容易被发现并修复

**Comment by MistEO** [comment]
我想刷 CE-6，能刷几次刷几次，剩余的 34 点再去刷 1-7。就和这个需求冲突了
