### ISSUE TITLE
[借助战刷信用] 死循环于 OF-1，提示“掉落识别错误”

### ISSUE THREAD

**Issue by GalvinGao** [MaaAssistantArknights/MaaAssistantArknights#4763]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

于 OF-1 出现“掉落识别错误”，导致死循环一直在刷 OF-1
开启了“借助战刷信用”

模拟器：BlueStacks 国际版 5.10.0.1085 x64
运行环境：Windows 11 Pro (21H2), x64
MAA 版本：v4.16.4 (稳定版更新通道)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11476928/gui.log)

## 屏幕截图 (Snipaste)
<img width="598" alt="Snipaste_2023-05-15_06-41-14" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12567059/7e0e8009-f71d-4482-a9fb-03ba92606016">

## 模拟器自带工具截图
![Screenshot_2023 05 15_06 41 30 139](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12567059/987692a1-a03a-4836-83bd-5557f9ec5e6a)

## `debug/drops` 下的最后 3 张图片
![2023-05-15_06-29-58-098_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12567059/22db78f7-9483-479e-b444-fee71050af7f)
![2023-05-15_06-27-55-032_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12567059/b94690b9-0982-4550-ad72-8e98afb28a56)
![2023-05-15_06-25-52-133_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12567059/60d5b3d8-4fc0-46d4-826e-6c095ff740f1)

**Comment by GalvinGao** [comment]
> 因为没识别到东西所以是掉落识别错误，很合理（
> 
> 至于为什么一直打这个是因为你选了
> 
> ![image](https://user-images.githubusercontent.com/18511905/238338616-07495eb1-f73f-4f3b-8e98-9eb42393e622.png)

草 好像也河里
但是感觉还是怪怪的 理论上助战是不是只用强制刷仅一次

**Comment by ABA2396** [comment]
选了当前上次甚至不会跑自动刷信赖这个功能（

**Comment by GalvinGao** [comment]
> > 但是感觉还是怪怪的 理论上助战是不是只用强制刷仅一次
> 
> 是，但是刷助战赚信用，和 刷理智，是两个功能
> 
> 主界面这个是刷理智设置，你选了上次关卡，且吃十个药，那自然是一直刷个不停（

草 原来是这样，我完全了解了（
