### ISSUE TITLE
显存爆炸

### ISSUE THREAD

**Issue by Sail-wang** [MaaAssistantArknights/MaaAssistantArknights#4765]
在使用wsa的情况下，使用自动战斗，会导致一定时间后，显存爆炸。然后，maa和wsa闪退，重新打开就恢复正常。

**Comment by Sail-wang** [comment]
但是在不使用自动战斗的情况下，显存就不会爆炸。

**Comment by MistEO** [comment]
你弄个 nvidia-smi 或者别的能看显存占用的工具看一下是谁吃的就知道了。谁炸的就是谁的问题。MAA 一跑起来就 WSA 就炸了，也不代表是 MAA 的问题
