### ISSUE TITLE
无法正常使用保全派驻的相关作业

### ISSUE THREAD

**Issue by SYREB** [MaaAssistantArknights/MaaAssistantArknights#4769]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我使用了“自动战斗”的 保全派驻 的作业，并且将游戏画面停放到了如图的位置
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/42509569/dd788b1e-c820-4dc7-aeda-9262513772db)
然后点击了“自动战斗”页面下的“开始”按钮
然后显示出错

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11479188/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/42509569/6c6b52c6-3582-4105-91ca-2782ddd77f27)

### 还有别的吗？

模拟器：BlueStacks by new.gg APP Player(Version:2.11.40.1004 P64)
操作系统：Windows11 64位 专业版
CPU:AMD Ryzen7 3700X
GPU:GTX 1050Ti
时间：2023年5月15日10点56分

**Comment by MistEO** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/c92293fa-2bf7-4f27-a057-561ee5e6c12e)

**Comment by cenfusheng** [comment]
请再往后点一下，直至出现关卡名与“开始部署”
