### ISSUE TITLE
[Bug] 刷图时出现等级提升页面疑似导致闪退

### ISSUE THREAD

**Issue by GalvinGao** [MaaAssistantArknights/MaaAssistantArknights#477]
所使用模拟器：BlueStacks 5.6.0.1127 N64
操作系统：Windows 11 Pro 21H2 (22000.556)
MAA 版本：v3.2.2

出现等级提升（下附截图；截图并非原生分辨率）页面时会直接闪退（不确定是不是真的闪退，但是我后台挂着MAA好像确实直接消失了）
![FFF4FA4A20FDABAD1F28394EF2428E29](https://user-images.githubusercontent.com/12567059/167617422-d2f41765-de5d-457d-9acb-9163fce77bca.jpg)

所附的log文件为截取和脱敏后的，如果需要完整的来私戳我（
[asst-trimmed.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8661085/asst-trimmed.log)

---

Edit: 忘记说了，使用的关卡选择模式为「当前关卡」

**Comment by MistEO** [comment]
更新版本！
