### ISSUE TITLE
[iOS] 保全作战中途出现识别错误后自动退出作战

### ISSUE THREAD

**Issue by FredLin5** [MaaAssistantArknights/MaaAssistantArknights#4772]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

问题发生在10:11:49时，MAA正常结束作战后提示“识别错误或JSON不支持”，之后自动退出保全作战，但日志里可以看到已经识别到下一关标题及开始作战的按钮了
希望能修复一下识别错误的问题，或者调整一下识别错误后的逻辑，比如增加几次自动重新识别的机会而非直接退出作战

### 日志文件

[asst_副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11483521/asst_.log)

### 截图

<img width="500" alt="截屏2023-05-16 上午10 49 40" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38588690/3490f515-cfa6-4279-bb45-a49274ee53fe">

### 还有别的吗？

使用PlayCover 3.0.0.maa.2版本，MAA版本为v4.17.0-beta.1（331），macOS版本13.3.1 (a)

**Comment by MistEO** [comment]
```log
[2023-05-16 10:11:49.597][TRC][Pxc032][Txa34d] asst::WordOcr [{ 消息传递.: [ 0, 0, 150, 29 ], score: 0.866921 }] by OCR Rec , cost 35 ms
[2023-05-16 10:11:49.598][TRC][Pxc032][Txa34d] Proced [{ 消息传递.: [ 128, 275, 150, 29 ], score: 0.866921 }]
```

@cenfusheng 也带带（

**Comment by cenfusheng** [comment]
> ```
> [2023-05-16 10:11:49.597][TRC][Pxc032][Txa34d] asst::WordOcr [{ 消息传递.: [ 0, 0, 150, 29 ], score: 0.866921 }] by OCR Rec , cost 35 ms
> [2023-05-16 10:11:49.598][TRC][Pxc032][Txa34d] Proced [{ 消息传递.: [ 128, 275, 150, 29 ], score: 0.866921 }]
> ```
> 
> @cenfusheng 也带带（

马上改
