### ISSUE TITLE
傀影肉鸽，一个蜜莓卡住了一关。。

### ISSUE THREAD

**Issue by ccskying** [MaaAssistantArknights/MaaAssistantArknights#4773]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图，蜜莓的站位，刚好挡住一个小怪，刚好没人打的到。。如果不手动操作的话就卡那了

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11483589/asst.zip)
大致是最后两关，忘了看叫啥了

### 截图

![_(X@O5}BC`QW21CJ_X~HD53](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/22491084/da3cd425-84a1-4eef-bda2-bdf18cbe51ef)

**Comment by cenfusheng** [comment]
不可避免的问题，目前卡到一定时间会自动放弃作战。

**Comment by ABA2396** [comment]
卡几分钟会全撤，再卡就放弃退出了，不会卡死的
