### ISSUE TITLE
【特性需求】借助战赚信用时，使用最后一个编队

### ISSUE THREAD

**Issue by HydrogenDeuterium** [MaaAssistantArknights/MaaAssistantArknights#4774]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

开启了“借助战赚信用”功能后，会覆盖当前编队。而且每天都会覆盖一次。
一般被覆盖的是推图的12人主力队，这样每次要推图都要重新编队一次，很蛋疼。
即使我想专门留一个编队给这个功能，由于默认使用上一次的编队，结果就是四个编队全部只剩一个挡二先锋。

### 有什么好的想法？

在使用此功能时，指定最后一个编队，如果当前编队不满足条件再重新编队，以免出现多个编队都被覆盖的情况出现。

**Comment by zzyyyl** [comment]
duplicate of #4624
