### ISSUE TITLE
new feature: 本地化自动脚本

### ISSUE THREAD

**Issue by UniMars** [MaaAssistantArknights/MaaAssistantArknights#4777]
可以放 tools 里面（？

可以写一个调用chatgpt的自动翻译本地化资源的脚本

_Originally posted by @MistEO in https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/4776#issuecomment-1548996832_

**Comment by MistEO** [comment]
能不能再整个 CI 自动跑（）

**Comment by UniMars** [comment]
是不是不同语言的文案数量理论上要求是一样多的？

**Comment by MistEO** [comment]
> 是不是不同语言的文案数量理论上要求是一样多的？@MistEO

是的

**Comment by UniMars** [comment]
> 能不能再整个 CI 自动跑（）

关于ci能不能给一些具体的说明，我回去研究研究

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/dev/.github/workflows 这里面的东西，会在提交的时候自动跑的。如果没弄过可能不好上手，到也没关系，有翻译脚本了剩下都是小问题，不行到时候我们再加一下

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/e6d51730-2bc3-4930-900a-a48ce6dc45d0)

**Comment by UniMars** [comment]
最后一个问题，xaml里面的东西只能通过注释来区分不同模块吗，能不能调整下xaml的结构？@MistEO

**Comment by MistEO** [comment]
不清楚， @ABA2396 @moomiji 有别的方法调整结构吗（？

**Comment by moomiji** [comment]
这是一个例子，有没其他方法得问另一位佬（：https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/src/MaaWpfGui/Res/Style.xaml

大概是出于什么样的需求需要调整结构？调整成什么样的结构？

**Comment by UniMars** [comment]
> 这是一个例子，有没其他方法得问另一位佬（：https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/src/MaaWpfGui/Res/Style.xaml
> 
> 大概是出于什么样的需求需要调整结构？调整成什么样的结构？

主要是出于维护可读性的角度，不然更新翻译之后全堆在一块，分不清哪个是哪个部分的了，注释也很难翻译过去
如果能在结构层面分好不同的部分的话，注释同步起来就比较方便了 @moomiji

**Comment by ABA2396** [comment]
> 这是一个例子，有没其他方法得问另一位佬（：[`dev`/src/MaaWpfGui/Res/Style.xaml](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/src/MaaWpfGui/Res/Style.xaml?rgh-link-date=2023-05-16T16%3A25%3A20Z)
> 
> 大概是出于什么样的需求需要调整结构？调整成什么样的结构？

大概这个意思？
```
<!-- 显示部分 -->
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:system="clr-namespace:System;assembly=mscorlib">
    <!-- 显示 -->
    <system:String x:Key="Display">显示</system:String>
    <!-- 其他显示相关内容 -->
</ResourceDictionary>

<!-- 设置部分 -->
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:system="clr-namespace:System;assembly=mscorlib">
    <!-- 设置 -->
    <system:String x:Key="Settings">设置</system:String>
    <!-- 其他设置相关内容 -->
</ResourceDictionary>
```

所以现在这种样子直接翻译会有什么问题吗

**Comment by UniMars** [comment]
> > 这是一个例子，有没其他方法得问另一位佬（：[`dev`/src/MaaWpfGui/Res/Style.xaml](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/src/MaaWpfGui/Res/Style.xaml?rgh-link-date=2023-05-16T16%3A25%3A20Z)
> > 大概是出于什么样的需求需要调整结构？调整成什么样的结构？
> 
> 大概这个意思？
> 
> ```
> 
> <ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
>                     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>                     xmlns:system="clr-namespace:System;assembly=mscorlib">
>     
>     <system:String x:Key="Display">显示</system:String>
>     
> </ResourceDictionary>
> 
> 
> <ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
>                     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>                     xmlns:system="clr-namespace:System;assembly=mscorlib">
>     
>     <system:String x:Key="Settings">设置</system:String>
>     
> </ResourceDictionary>
> ```
> 
> 所以现在这种样子直接翻译会有什么问题吗

比如说中文增加了中间的一行，同步过去的话会直接堆在底下，时间一长就全乱了，那些注释什么的也不好同步，可读性比较差@ABA2396

**Comment by moomiji** [comment]
这种嘞@ABA2396

```xaml
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:system="clr-namespace:System;assembly=mscorlib">
    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary x:Uid="显示">
            <system:String x:Key="Display">显示</system:String>
            <!-- 其他显示相关内容 -->
        </ResourceDictionary>

        <ResourceDictionary x:Uid="设置">
            <system:String x:Key="Settings">设置</system:String>
            <!-- 其他设置相关内容 -->
        </ResourceDictionary>
    </ResourceDictionary.MergedDictionaries>
</ResourceDictionary>
```

**Comment by ABA2396** [comment]
> 这种嘞@ABA2396
> 
> ```xaml
> <ResourceDictionary
>     xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
>     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>     xmlns:system="clr-namespace:System;assembly=mscorlib">
>     <ResourceDictionary.MergedDictionaries>
>         <ResourceDictionary x:Uid="显示">
>             <system:String x:Key="Display">显示</system:String>
>             
>         </ResourceDictionary>
> 
>         <ResourceDictionary x:Uid="设置">
>             <system:String x:Key="Settings">设置</system:String>
>             
>         </ResourceDictionary>
>     </ResourceDictionary.MergedDictionaries>
> </ResourceDictionary>
> ```

可以吧，就是要改的是不是有点多）

**Comment by UniMars** [comment]
蹲一个

**Comment by moomiji** [comment]
> > 这种嘞@ABA2396
> > ```xaml
> > <ResourceDictionary
> >     xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
> >     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
> >     xmlns:system="clr-namespace:System;assembly=mscorlib">
> >     <ResourceDictionary.MergedDictionaries>
> >         <ResourceDictionary x:Uid="显示">
> >             <system:String x:Key="Display">显示</system:String>
> >             
> >         </ResourceDictionary>
> > 
> >         <ResourceDictionary x:Uid="设置">
> >             <system:String x:Key="Settings">设置</system:String>
> >             
> >         </ResourceDictionary>
> >     </ResourceDictionary.MergedDictionaries>
> > </ResourceDictionary>
> > ```
> 
> 可以吧，就是要改的是不是有点多）

坏了，这样做重复键是合法的，检查该不会要交给 ci 吧？

**Comment by moomiji** [comment]
试试这个结构：https://github.com/moomiji/MaaAssistantArknights/tree/chore/localizations

自动本地化有几点要求看看能不能做到：
1. 不要破坏缩进（包括空行不带空格）
2. `<ResourceDictionary x:Uid="KeyName">` 如果能在资源字典找到Uid对应的Key，把对应的Value作为注释写入，像这样（注意注释中的空格）：
```xaml
        <!--  设置  -->
        <ResourceDictionary x:Uid="Settings">
```

3. 由于字典被拆分了，重复的键要交给脚本检查
4. 因为zh-cn可能会混入一些中文梗，所以ja-jp、ko-kr尽量由en-us翻译

```
check duplicate Key()
if exist duplicate Key:
    throw (or raise) an exception

zh-cn -> zh-tw
if exist en-us:
    en-us -> ja-jp
    en-us -> ko-kr
else:
    zh-cn -> ja-jp
    zh-cn -> ko-kr
    zh-cn -> en-us
```

**Comment by UniMars** [comment]
> 试试这个结构：https://github.com/moomiji/MaaAssistantArknights/tree/chore/localizations
> 
> 自动本地化有几点要求看看能不能做到：
> 
> 1. 不要破坏缩进（包括空行不带空格）
> 2. `<ResourceDictionary x:Uid="KeyName">` 如果能在资源字典找到Uid对应的Key，把对应的Value作为注释写入，像这样（注意注释中的空格）：
> 
> ```
>         
>         <ResourceDictionary x:Uid="Settings">
> ```
> 
> 3. 由于字典被拆分了，重复的键要交给脚本检查
> 4. 因为zh-cn可能会混入一些中文梗，所以ja-jp、ko-kr尽量由en-us翻译
> 
> ```
> check duplicate Key()
> if exist duplicate Key:
>     throw (or raise) an exception
> 
> zh-cn -> zh-tw
> if exist en-us:
>     en-us -> ja-jp
>     en-us -> ko-kr
> else:
>     zh-cn -> ja-jp
>     zh-cn -> ko-kr
>     zh-cn -> en-us
> ```

空行和空格好办，这个缩进能不能通过commit前自动格式化代码来处理？

**Comment by moomiji** [comment]
格式化用的这个工具，不冲突就行：https://marketplace.visualstudio.com/items?itemName=TeamXavalon.XAMLStyler2022
这工具不是人人都装了，估计玛丽会支持自动格式化的（

**Comment by UniMars** [comment]
@MistEO @moomiji @ABA2396 基本写好了，还差一个调git api获取文档历史版本和写一个git hook来在本地commit之前同步更新到其他语言，因为chatgpt翻译api比较私密，所以似乎不太方便上传到github，但可以在本地部署。
大家先测试下，看下有什么问题
[自动翻译脚本](https://github.com/UniMars/auto_localization)

**Comment by UniMars** [comment]
更新了调用git对比更新同步的部分。
现在有个问题是，中文文档里节点的更新要不要完全同步到英文上？文档维护的逻辑是中英文并行，还是中文为主？
我目前采用的逻辑是只将中文新增的节点同步到英文上，但对英文已有同key字段的节点则选择跳过

**Comment by UniMars** [comment]
然后目前调用git是把当前的更新和当前分支最新的commit进行对比

**Comment by UniMars** [comment]
开了一个discussion 讨论翻译的逻辑 #4886
