### ISSUE TITLE
干员识别检测不到添加了特别关注的正义骑士号

### ISSUE THREAD

**Issue by sporz** [MaaAssistantArknights/MaaAssistantArknights#4784]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

经实验，取消特别关注后能够正常识别。日志显示识别为“义骑士号”
归溟幽灵鲨也有类似问题，日志显示识别为“灵鲨”或“鲨”，但取消特别关注识别成功后，再添加特别关注能够识别成功。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11485149/asst.log)
15:24:25开始的干员识别
归溟幽灵鲨相关：15:10开始的干员识别

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52434074/3b244c36-91e1-400b-9a31-f3740dafeb64)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52434074/db36bed2-c9d6-48d6-8651-bf0a2b864baf)
[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11485246/oper.zip)
[oper1.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11485247/oper1.zip)

### 还有别的吗？

MuMu模拟器

**Comment by MistEO** [comment]
干员识别内测版修了一个很严重的bug，再下一个正式版如果还有问题麻烦再提一下
