### ISSUE TITLE
程序内触控无反应且强制替换adb时出现进程冲突报错

### ISSUE THREAD

**Issue by Meteorite1014** [MaaAssistantArknights/MaaAssistantArknights#4787]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

内测版模拟器更新后重连mumu模拟器，可在startup阶段正确点击图标，但在进入明日方舟程序界面后触控无反应。
进行强制替换adb操作后报错为进程占用，重启模拟器与maa且maa以管理员身份启动后照旧
asst.log已上传，报错界面信息如下

MAA 遇到了问题
文件“D:\Program Files\MuMu\emulator\nemu\EmulatorShell\..\vmonitor\bin\adb_server.exe”正由另一进程使用，因此该进程无法访问此文件。
解决方案
请关闭模拟器与 ADB 或重启电脑后使用管理员权限打开 MAA 进行操作
详细信息
System.IO.IOException: 文件“D:\Program Files\MuMu\emulator\nemu\EmulatorShell\..\vmonitor\bin\adb_server.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ReplaceADB>b__420_1()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ReplaceADB>d__420.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11488733/asst.log)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f7110776-e7f9-403c-ba84-d584bf5eb355)
