### ISSUE TITLE
干员识别缺失

### ISSUE THREAD

**Issue by 404limbo** [MaaAssistantArknights/MaaAssistantArknights#4790]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在使用maa的干员识别时，似乎所有六星特种都被识别为未拥有，五星术士有部分被识别为未拥有。我使用的是蓝叠模拟器

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11493310/asst.log)

**Comment by MistEO** [comment]
特别关注开了就容易识别错，先关掉试试。后续优化下

**Comment by MistEO** [comment]
干员识别内测版修了一个很严重的bug，再下一个正式版如果还有问题麻烦再提一下
