### ISSUE TITLE
MAC版MAA运行保全作战不自动调配干员

### ISSUE THREAD

**Issue by Zer0zaki** [MaaAssistantArknights/MaaAssistantArknights#4792]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题：MAC版MAA运行保全作战不自动调配干员
视频录像见：https://www.bilibili.com/video/BV1H24y1T7MG/

### 日志文件

[asst (1).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11494089/asst.1.log)
时间戳2023-05-06 22:00前后

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/133838829/8738e857-d614-4dd4-a3ed-ff5f6ce4128d)

**Comment by MeDiablo** [comment]
这个问题解决了吗？怎么解决的？

**Comment by Olld47** [comment]
截止到7月16号还没有解决，同样是playcover版

**Comment by Olld47** [comment]
@hguandl

**Comment by xzjjasper** [comment]
出现了相同问题
