### ISSUE TITLE
水月肉鸽骑士局无法正确识别，关卡名“命运的宠儿”

### ISSUE THREAD

**Issue by fastboot-rec** [MaaAssistantArknights/MaaAssistantArknights#4794]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在水月肉鸽骑士局无法正确识别，关卡名“命运的宠儿”。
asst.log里有看到“命运的宠儿”字样，时间节点为2023-05-17 17:07:44.761，在135648行开始的。
gui.log在2023-05-17 17:08:27.386输出“关卡识别错误”，在2596行
debug目录下没看到有这一关的截图。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11496262/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11496417/gui.log)

### 还有别的吗？

模拟器：Bluestacks 5 5.11.100.1063 N32
系统：Windows 10 22H2 操作同内部版本19045.2913
MAA版本：v4.17.0-beta.1
MAA使用MaaTouch，开启暂停下干员

ADB相关：
  Android Debug Bridge version 1.0.41
  Version 34.0.1-9680074
  Installed as C:\Android\adb.exe

**Comment by LingXii** [comment]
@MistEO 这个关卡有时候识别带引号有时候不带引号，可不可以配置一下关卡ocr的模糊识别

**Comment by MistEO** [comment]
@LingXii 在 tasks.json - BattleStageName - ocrReplace 里加一下就可以了

**Comment by MistEO** [comment]
copilot 里好像也写错了，我一起改了
