### ISSUE TITLE
启动MAA后自动扫描局域网所有设备的5555端口

### ISSUE THREAD

**Issue by 128CoresALL10GHz** [MaaAssistantArknights/MaaAssistantArknights#4795]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

因为现在一般都是DHCP所以手机的IP地址可能在局域网内会变化，如果每次都要重新配置会很麻烦，希望可以在启动后自动扫描局域网内所有设备的5555端口，这样对于使用网络adb的人来说会方便一些，不用每次查看设备IP再手动填写

**Comment by pein0saga** [comment]
不建议做这种瓜田李下的事情，带来安全隐患，MAA没有必要冒这种险，免得背锅。

“5555端口是安卓adb服务默认监听的端口，由于早期版本缺乏认证过程，导致其成为了僵尸网络热衷利用的目标，目前安全团队对5555端口上相关攻击的研究通常集中在adb服务。近期我们对5555端口上的恶意流量进行了深入分析，发现除针对adb服务的探测和攻击活动依然活跃外，还存在多种针对其他漏洞和服务的攻击：5555端口上针对adb服务的探测和攻击非常稳定，没有明显的上升下降趋势，说明攻击者已经将adb服务纳入常规的攻击目标。”
