### ISSUE TITLE
任务选择吃8个理智药，但是吃完第8个理智药，没有用掉理智就完成了任务

### ISSUE THREAD

**Issue by yamasakura** [MaaAssistantArknights/MaaAssistantArknights#4798]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA版本版本是v4.17.0-beta.1    系统是window10

![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/84258011/9369220c-601e-4b99-9143-e556fcc9b6cd)
如上图选择了8个理智药
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/84258011/451f958e-1336-4cce-bccd-dad172f5ba6d)
2023-05-17 22:29:58.103  吃了第8个就显示完成了任务

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11499776/asst.log)

**Comment by yamasakura** [comment]
版本是v4.17.0-beta.1

**Comment by MistEO** [comment]
这个药应该没吃，看日志点了吃药的确定，弹出了 `正在提交反馈至神经`，等了好一会，结果还在吃药的界面。。

~~总感觉是鹰角的问题~~

**Comment by yamasakura** [comment]
药确实吃了，我是下班的时候发现他理智是90多，那看来应该就是卡住太久了，导致直接结束了，但是之后药又吃成功了？

**Comment by liuyifan-eric** [comment]
嗯应该是网络问题，如果网络不稳定你可以多定时几个自动执行这样理智也不会溢出。这个issue先关了
