### ISSUE TITLE
刷理智使用copilot编入信赖队

### ISSUE THREAD

**Issue by liuyifan-eric** [MaaAssistantArknights/MaaAssistantArknights#4801]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

每次新的信赖队都要重新手打一遍1-7, CE-6之类的关卡

### 有什么好的想法？

刷理智的时候第一次先让copilot自己编信赖队打一遍（或者干脆每一遍都copilot手打算了）

### 其他内容

先占个坑，看看有没有人要写的

**Comment by MistEO** [comment]
信赖排序比较麻烦的问题是，名字是被信赖值挡住的，不知道选了谁，可能会和编队中的人冲突

**Comment by MobiusT** [comment]
能否提供配置手动输入信赖队干员名称列表，copilot时有多余的空位就按照列表顺序补满12人？
