### ISSUE TITLE
基建宿舍无法正确识别干员

### ISSUE THREAD

**Issue by grandcaster3054** [MaaAssistantArknights/MaaAssistantArknights#4802]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在基建换班时，每次在识别某些干员（爱丽丝、夜莺）时，maa不能识别到这些干员，而是一直往后拉，但是明明这些干员就在第一个，而且这个流程一卡住，除非有人点，不然不会停止，往后的流程也不会继续，望修复

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11504625/asst.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/133943322/fba787d6-5177-4f9c-8847-8bb0e1ad18e0)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/133943322/2cc7aefa-d1cf-4fd1-88fd-1bae6a8f5f10)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/133943322/c447b433-43d0-4293-8291-08e34a4d3e51)

### 还有别的吗？

模拟器：夜神模拟器V7.0.5.7002
操作系统：WIN10家庭中文版22H2

**Comment by CCCClaus** [comment]
我也是，问题出现在我的日志的2023.5.18 3：50-7：50
[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11506646/asst.bak.zip)
