### ISSUE TITLE
4.17版蓝叠（Hyper-V）连接失败，4.16正常使用

### ISSUE THREAD

**Issue by inhalc** [MaaAssistantArknights/MaaAssistantArknights#4806]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

4.17公测版蓝叠（Hyper-V）无法连接，
倒退回4.16.4正常使用，后来更新稳定版的4.17又无法连接了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11508254/asst.log)

### 还有别的吗？

蓝叠（Hyper-V）,Windows 11 Insider Preview 10.0.22624.1680。maa更新前后未更新系统

**Comment by DavidWang19** [comment]
在连接设置中勾选“自动检测连接”和“每次重新检测”即可。

**Comment by MistEO** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/13284830-89cd-4723-9e67-d8714f85f760)

**Comment by MistEO** [comment]
好像有不少朋友没留意这条，置顶一段时间
