### ISSUE TITLE
为什么github下载页面不再提供OTA包了呢？

### ISSUE THREAD

**Issue by NetatioAl** [MaaAssistantArknights/MaaAssistantArknights#4807]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

MAA内置的升级介于我的网络原因，总是下载失败，现在我想在github上面自行下载OTA包，却发现已经没有OTA的下载选项了

**Comment by soundofautumn** [comment]
OTA在这 https://github.com/MaaAssistantArknights/MaaRelease/releases
