### ISSUE TITLE
使用mumu12模拟器，运行“完成后退出MAA和模拟器”，模拟器无法正常退出，模拟器会弹出“虚拟机异常退出，请重启模拟器”，关闭窗口或点击按钮会重启模拟器

### ISSUE THREAD

**Issue by wxp203** [MaaAssistantArknights/MaaAssistantArknights#4808]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用mumu12模拟器，运行“完成后退出MAA和模拟器”，模拟器无法正常退出，模拟器会弹出“虚拟机异常退出，请重启模拟器”，关闭窗口或点击按钮会重启模拟器

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11509636/asst.log)

### 截图

![屏幕截图 2023-05-19 003101](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/77116287/b53a60a5-81db-4cf6-a808-59342ab9715d)

### 还有别的吗？

mumu12模拟器，windows11

**Comment by MistEO** [comment]
请参考 [文档](https://maa.plus/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.html#%E2%9A%A0%EF%B8%8F-mumu-%E6%A8%A1%E6%8B%9F%E5%99%A8-12-%E6%9C%80%E6%B5%81%E7%95%85%F0%9F%91%8D)

**Comment by wxp203** [comment]
> 请参考 [文档](https://maa.plus/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.html#%E2%9A%A0%EF%B8%8F-mumu-%E6%A8%A1%E6%8B%9F%E5%99%A8-12-%E6%9C%80%E6%B5%81%E7%95%85%F0%9F%91%8D)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/77116287/50d91240-0063-4aed-b62f-d366ebc1ffc3)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/77116287/2c8b3755-12fa-4264-8471-a77c04c9b3c6)
是最新版本

**Comment by Kagura-Nanaa** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11512659/asst.log)
同为338版本模拟器 相同的问题

**Comment by MistEO** [comment]
@ABA2396 mumu 那边咋说的来着

**Comment by ABA2396** [comment]
MAA 设置里选了啥？没选MUMU12选了MUMU吗

**Comment by Kagura-Nanaa** [comment]
> MAA 设置里选了啥？没选MUMU12选了MUMU吗

是mumu12

**Comment by Kagura-Nanaa** [comment]
> > MAA 设置里选了啥？没选MUMU12选了MUMU吗
> 
> 是mumu12

重装模拟器后已解决

**Comment by wxp203** [comment]
我模拟器更新至3.3.9版本后仍有此问题出现，连接配置是mumu模拟器12

**Comment by ABA2396** [comment]
> 我模拟器更新至3.3.9版本后仍有此问题出现，连接配置是mumu模拟器12

关闭失败后来个日志看看

**Comment by wxp203** [comment]
> > 我模拟器更新至3.3.9版本后仍有此问题出现，连接配置是mumu模拟器12
> 
> 关闭失败后来个日志看看

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11516870/asst.log)

**Comment by ABA2396** [comment]
不知道是不是这个原因，等 [这个](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/5024813012) 出来试试看能不能用 @wxp203

**Comment by wxp203** [comment]
> 不知道是不是这个原因，等 [这个](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/5024813012) 出来试试看能不能用 @wxp203

MAA更新了最新内测版，没有解决
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11517718/asst.log)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/77116287/bec7dba3-6653-4332-82d3-2fa69bb2b65e)

**Comment by wxp203** [comment]
经测试，运行一次asls会导致7555端口可以正常连接，连接使用7555端口会导致退出模拟器bug
现在MAA会自动检测连接正确的端口

**Comment by ABA2396** [comment]
只有mumu12才是16384端口啊，你之前用的啥版本的mumu？mumu x也是安卓12

**Comment by wxp203** [comment]
> 只有mumu12才是16384端口啊，你之前用的啥版本的mumu？mumu x也是安卓12

以前用mumu x用了几个月，前天换成mumu12出现bug才开了议题，昨天重装了mumu12就好了

**Comment by ABA2396** [comment]
> > 只有mumu12才是16384端口啊，你之前用的啥版本的mumu？mumu x也是安卓12
> 
> 以前用mumu x用了几个月，前天换成mumu12出现bug才开了议题，昨天重装了mumu12改了端口号才好的

mumu x是12的过渡版本，现在直接就下了，控制台是12出的，x都没这玩意来着
