### ISSUE TITLE
日常奖励任务执行时卡住

### ISSUE THREAD

**Issue by BTreeNewBee** [MaaAssistantArknights/MaaAssistantArknights#481]
日常奖励任务执行时卡住死循环，最后是手动暂停的。
![图片](https://user-images.githubusercontent.com/18378664/167647880-2004d3f3-bd97-4d5f-98a3-79d0c11afed3.png)

勾选任务列表
![图片](https://user-images.githubusercontent.com/18378664/167649734-ba360966-d22f-4942-be8a-cb4f5f3067a3.png)

最终停留界面在周常，未领取奖励我手动给他领取了。
![图片](https://user-images.githubusercontent.com/18378664/167649082-18416dcf-45a0-4548-b577-569cbcc1eff7.png)

开始卡住部分的日志。
![图片](https://user-images.githubusercontent.com/18378664/167648950-48373c93-485d-49a2-86fa-21db754c5e53.png)

另附当日完整日志压缩包。
[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8662253/asst.-.zip)

**Comment by MistEO** [comment]
你另一个号这里是不是有不止三栏，有个新手任务还是什么的

maa 识别过一次后会建立缓存的（非持久化），两个号`周常任务`位置不一致，第二个号识别仅在第一个号`周常任务`出现的位置处识别，就没识别到_(:з」∠)_
