### ISSUE TITLE
小工具—干员识别—没有识别出归溟幽灵鲨

### ISSUE THREAD

**Issue by Ozzz-cainiao** [MaaAssistantArknights/MaaAssistantArknights#4813]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

干员识别，没有识别出归溟幽灵鲨，导致识别到的干员数量少于预期数量。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11512924/asst.log)

**Comment by MistEO** [comment]
干员识别内测版修了一个很严重的bug，再下一个正式版如果还有问题麻烦再提一下
