### ISSUE TITLE
依照更新日誌操作後仍然無法使用blue stacks模擬器

### ISSUE THREAD

**Issue by Ma3terbait** [MaaAssistantArknights/MaaAssistantArknights#4817]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

已經將自動檢測連接及每次重新檢測設定打開

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11513912/asst.log)
大致时间点:19/5

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/86555573/5fe3e5ad-7f8d-4f15-bee9-02cf61f81e6d)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/86555573/3025ac43-830b-4ec0-b3d5-a0667ceb74a3)

**Comment by MistEO** [comment]
你是 hyperv？conf 之前设置过吗，看看现在还在不在了

**Comment by Ma3terbait** [comment]
沒設置過，我也是前幾天才用的blue stacks，不太懂

**Comment by MistEO** [comment]
参考 https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7-hyper-v

**Comment by Ma3terbait** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/86555573/cad6aac8-4026-4948-8e09-6d1f1a1c01d8)

**Comment by Ma3terbait** [comment]
{
  "Bluestacks.Config.Path": "C:\\ProgramData\\BlueStacks_nxt\\bluestacks.conf",
  "TaskQueue.WakeUp.IsChecked": "False",
  "TaskQueue.Recruiting.IsChecked": "False",
  "TaskQueue.Base.IsChecked": "False",
  "TaskQueue.Combat.IsChecked": "True",
  "TaskQueue.Visiting.IsChecked": "False",
  "TaskQueue.Mall.IsChecked": "False",
  "TaskQueue.Mission.IsChecked": "False",
  "TaskQueue.AutoRoguelike.IsChecked": "False",
  "Infrast.Mfg.IsChecked": "True",
  "Infrast.Trade.IsChecked": "True",
  "Infrast.Control.IsChecked": "True",
  "Infrast.Power.IsChecked": "True",
  "Infrast.Reception.IsChecked": "True",
  "Infrast.Office.IsChecked": "True",
  "Infrast.Dorm.IsChecked": "True",
  "GUI.Localization": "zh-tw",
  "AutoRecruit.IsLevel3UseShortTime": "True",
  "Start.ClientType": "Bilibili",
  "MainFunction.Drops.ItemId": "3232",
  "MainFunction.Drops.ItemName": "\u91CD\u88DD\u6676\u7247\u7D44",
  "MainFunction.Drops.Enable": "False",
  "MainFunction.Stage1": "",
  "MainFunction.Drops.Quantity": "6",
  "TaskQueue.Order.WakeUp": "0",
  "TaskQueue.Order.Recruiting": "1",
  "TaskQueue.Order.Base": "2",
  "TaskQueue.Order.Combat": "3",
  "TaskQueue.Order.Visiting": "4",
  "TaskQueue.Order.Mall": "5",
  "TaskQueue.Order.Mission": "6",
  "TaskQueue.Order.AutoRoguelike": "4",
  "Infrast.Order.Mfg": "0",
  "Infrast.Order.Trade": "1",
  "Infrast.Order.Control": "2",
  "Infrast.Order.Power": "3",
  "Infrast.Order.Reception": "4",
  "Infrast.Order.Office": "5",
  "Infrast.Order.Dorm": "6",
  "Connect.ConnectConfig": "BlueStacks",
  "Connect.AdbPath": "C:\\Program Files\\BlueStacks_nxt\\.\\HD-Adb.exe",
  "Connect.Address": "127.0.0.1:5555",
  "Connect.AutoDetect": "True",
  "Start.StartEmulator": "True",
  "Start.EmulatorWaitSeconds": "10",
  "Start.EmulatorPath": "C:\\Users\\user\\Desktop\\Games\\Arknights.lnk",
  "MainFunction.UseMedicine": "False",
  "Penguin.Id": "047580656",
  "Roguelike.RoguelikeTheme": "Mizuki",
  "VersionUpdate.package": "",
  "VersionUpdate.name": "v4.17.1",
  "VersionUpdate.body": "## v4.17.1\n\n### Breaking changes\n\n- **\u82E5\u51FA\u73B0 HandyControl \u76F8\u5173\u62A5\u9519\uFF0C\u8BF7\u91CD\u65B0\u5B89\u88C5 [.NET Framework 4.8](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-offline-installer) \u6216\u53C2\u8003 [\u5E38\u89C1\u95EE\u9898](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%BD%AF%E4%BB%B6%E6%97%A0%E6%B3%95%E8%BF%90%E8%A1%8C-%E9%97%AA%E9%80%80-%E6%8A%A5%E9%94%99) \u89E3\u51B3**\n- **\u82E5\u914D\u7F6E\u8FC7 Hyper-V \u84DD\u53E0\u7684 conf \u5730\u5740\u68C0\u6D4B\u4F46\u65E0\u6CD5\u8FDE\u63A5\u6A21\u62DF\u5668\uFF0C\u8BF7\u52FE\u9009 \u0060\u81EA\u52A8\u68C0\u6D4B\u0060 \u002B \u0060\u6BCF\u6B21\u68C0\u6D4B\u0060**\n\n### \u6539\u8FDB\n\n- \u4F18\u5316\u8FDE\u63A5\u524D\u7684\u8D44\u6E90\u52A0\u8F7D\u903B\u8F91 @MistEO\n- HandyControl \u76F8\u5173\u62A5\u9519\u6DFB\u52A0\u63D0\u793A @MistEO\n- \u589E\u91CF\u5305\u627E\u4E0D\u5230\u65F6\u5219\u4E0B\u8F7D\u5168\u91CF\u5305 @MistEO\n- \u7E41\u4E2D\u754C\u9762\u7684\u7B2C\u4E8C\u8BED\u8A00\u4F7F\u7528\u7B80\u4E2D @moomiji\n\n### \u4FEE\u590D\n\n- \u4FEE\u590D hyperv \u84DD\u53E0\u6BCF\u6B21\u90FD\u91CD\u65B0\u8FDE\u63A5\u7684\u95EE\u9898 @MistEO\n- \u4FEE\u590D \u0060\u9E92\u9E9FX\u591C\u5200\u0060 \u8BC6\u522B\u9519\u8BEF @MistEO\n\n### \u5176\u4ED6\n\n- \u8C03\u6574\u8BBE\u8BA1\u65F6\u8BED\u8A00\u8D44\u6E90\u7684\u5F15\u7528\u65B9\u5F0F @moomiji\n- \u66F4\u65B0\u6587\u6863 @MistEO\n\n## v4.17.0\n\n### \u6539\u8FDB\n\n- \u8BBE\u7F6E\u5E03\u5C40\u5927\u91CD\u6784 \u273F\u273F\u30FD(\u00B0\u25BD\u00B0)\u30CE\u273F @moomiji @ABA2396 @MistEO\n- \u7248\u672C\u66F4\u65B0\u5927\u4F18\u5316 \u273F\u273F\u30FD(\u00B0\u25BD\u00B0)\u30CE\u273F @MistEO\n- \u8C03\u6574 Hyper-V \u84DD\u53E0 \u5730\u5740\u68C0\u6D4B\u903B\u8F91\uFF0C\u9700\u52FE\u9009 \u0060\u81EA\u52A8\u68C0\u6D4B\u0060 \u002B \u0060\u6BCF\u6B21\u68C0\u6D4B\u0060 @MistEO @ABA2396 @SherkeyXD\n- ADB \u66FF\u6362\u5931\u8D25\u5219\u4E34\u65F6\u7528\u672C\u5730\u7684 @MistEO\n- \u6DFB\u52A0 MuMu12 \u68C0\u6D4B\u8FDE\u63A5\u4E0E\u63A7\u5236\u53F0\u9000\u51FA\u6A21\u62DF\u5668 @ABA2396 @MistEO\n- \u6807\u9898\u680F\u663E\u793A\u5361\u6C60\u4FE1\u606F @MistEO @ABA2396\n- UI improvements (#4582) @dantmnf\n- \u4F18\u5316\u4FDD\u5168\u6D3E\u9A7B\u5185\u7F6E\u4F5C\u4E1A SSS_\u7EA6\u7FF0\u8001\u5988\u5728\u5EFA\u5730\u5757_\u6D4A\u8482\u6C34\u9648\u7248.json (#4686) @junyihan233\n\n### \u4FEE\u590D\n\n- \u4FEE\u590D\u5173\u5361 \u0060\u6D88\u606F\u4F20\u9012\u0060\u3001\u0060\u7A92\u606F\u0060\u3001\u0060\u201C\u547D\u8FD0\u7684\u5BA0\u513F\u201D\u0060 \u8BC6\u522B\u9519\u8BEF (#4781) @cenfusheng @MistEO\n- \u4FEE\u6B63 Android 12 \u4E0A\u65E0\u6CD5\u7ED3\u675F\u6E38\u620F\u8FDB\u7A0B\u7684\u95EE\u9898 (#4685) @AnnAngela\n- \u4FEE\u590D\u788E\u77F3\u540E\u52A0\u8F7D\u65F6\u95F4\u8FC7\u957F\u5BFC\u81F4\u4EFB\u52A1\u63D0\u524D\u4E2D\u6B62\u7684\u95EE\u9898 @zzyyyl\n- \u89E3\u51B3\u6284\u4F5C\u4E1Aguard\u548Csupporter\u5B57\u6BB5\u4E0D\u8BC6\u522B\u7684\u95EE\u9898 (#4735) @AnnoyingFlowers\n- XAML Intellisense unable to load resources stored in ResourceDictionary @moomiji\n- avatar saved at wrong path in set_avatar() (#4724) @lengyanyu258\n- \u66F4\u65B0\u81EA\u52A8\u6218\u6597\u70B9\u8D5E\u53CD\u9988\u63D0\u793A\u8BED (#4776) @UniMars\n- \u4E3A Resource loader \u6DFB\u52A0\u91CD\u5165\u9501 @MistEO\n- \u4FEE\u590D CI release \u4E0D\u66F4\u65B0 version api \u7684\u95EE\u9898 @MistEO\n\n### \u5176\u4ED6\n\n- ~~\u5C0F\u6C34\u7BA1\u7206\u4E86~~ \u4E0D\u518D\u4ECE OTA \u7AD9\u4E0B\u8F7D\u66F4\u65B0\u5305 @MistEO\n- \u4F18\u5316\u5E76\u4FEE\u590D\u4E00\u4E9B CI \u7684\u9519\u8BEF @MistEO @horror-proton\n- \u5192\u70DF\u6D4B\u8BD5\u6DFB\u52A0\u6240\u6709\u5916\u670D\u8D44\u6E90\u68C0\u67E5 @MistEO\n- \u5192\u70DF\u6D4B\u8BD5\u7684 nuget \u6DFB\u52A0\u91CD\u8BD5 @MistEO\n- \u66F4\u65B0\u6587\u6863\u3001\u754C\u9762\u6587\u5B57\u7B49 @MistEO\n- \u6587\u6863\u8865\u5145 maadeps-download.py \u4F4D\u7F6E (#4672) @niuden\n- \u6DFB\u52A0\u5173\u4E8E MuMu \u6A21\u62DF\u5668 12 \u7684\u8BF4\u660E (#4793) @AnnAngela\n- Doc : JP \u30B7\u30E9\u30AF\u30B6\u30FC\u30CE (#4782) @wallsman\n\n### For overseas\n\n#### YostarKR\n\n- Fix getting stuck in RIIC for KR (#4749) @178619\n\n### For develops\n\n- update linux tutorial @horror-proton\n- \u8BA9VS\u53EF\u4EE5\u8865\u5168\u5934\u6587\u4EF6 @MistEO\n- \u65B0\u589E [version api](https://ota.maa.plus/MaaAssistantArknights/api/version/) @MistEO\n\n**Full Changelog**: [v4.17.0 -\u003E v4.17.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/compare/v4.17.0...v4.17.1)\n",
  "VersionUpdate.UpdateBeta": "True",
  "VersionUpdate.UseAria2": "False",
  "HotKeys": "{\u0022ShowGui\u0022:{\u0022Key\u0022:56,\u0022Modifiers\u0022:7},\u0022LinkStart\u0022:{\u0022Key\u0022:55,\u0022Modifiers\u0022:7}}",
  "Fight.RemainingSanityStage": "1-7",
  "MainFunction.TimesLimited.Quantity": "0",
  "Timer.Timer1": "False",
  "Timer.Timer1Hour": "0",
  "Timer.Timer1Min": "0",
  "Timer.Timer2": "False",
  "Timer.Timer2Hour": "3",
  "Timer.Timer2Min": "0",
  "Timer.Timer3": "False",
  "Timer.Timer3Hour": "6",
  "Timer.Timer3Min": "0",
  "Timer.Timer4": "False",
  "Timer.Timer4Hour": "9",
  "Timer.Timer4Min": "0",
  "Timer.Timer5": "False",
  "Timer.Timer5Hour": "12",
  "Timer.Timer5Min": "0",
  "Timer.Timer6": "False",
  "Timer.Timer6Hour": "15",
  "Timer.Timer6Min": "0",
  "Timer.Timer7": "False",
  "Timer.Timer7Hour": "18",
  "Timer.Timer7Min": "0",
  "Timer.Timer8": "False",
  "Timer.Timer8Hour": "21",
  "Timer.Timer8Min": "0",
  "Roguelike.Squad": "",
  "Connect.AddressHistory": "[\u0022127.0.0.1:5555\u0022,\u0022emulator-5554\u0022]",
  "Guide.StepIndex": "4",
  "GUI.Placement": "{\u0022Length\u0022:44,\u0022Flags\u0022:0,\u0022ShowCmd\u0022:1,\u0022MinPosition\u0022:{\u0022X\u0022:-1,\u0022Y\u0022:-1},\u0022MaxPosition\u0022:{\u0022X\u0022:-1,\u0022Y\u0022:-1},\u0022NormalPosition\u0022:{\u0022Left\u0022:149,\u0022Top\u0022:521,\u0022Right\u0022:949,\u0022Bottom\u0022:1122}}",
  "GUI.Placement.SaveOnClosing": "True",
  "GUI.Placement.Load": "True",
  "Connect.AlwaysAutoDetect": "True",
  "TaskQueue.ReclamationAlgorithm.IsChecked": "False",
  "MainFunction.Stage2": null,
  "MainFunction.Stage3": null,
  "TaskQueue.Order.ReclamationAlgorithm": "7",
  "VersionUpdate.isfirstboot": "False"
}

**Comment by 178619** [comment]
Have you turned on Android Debugging? I am not sure but it seems like you didn't turn it on.
你打开了安卓调试功能吗？我不确定，但看起来你没有打开。

> 完美支持。需要在模拟器 `设置` - `引擎设置` 中打开 `允许ADB连接`。
https://maa.plus/docs/1.3-模拟器支持

**Comment by Ma3terbait** [comment]
原來是我沒有打開安卓調試設置,現在打開了就可以了,謝謝你!
