### ISSUE TITLE
建议增加关闭窗口时最小化至托盘选项

### ISSUE THREAD

**Issue by Ptilopsis01** [MaaAssistantArknights/MaaAssistantArknights#4818]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题，有时候挂着maa随手就把窗口关了，非常尴尬

### 有什么好的想法？

增加一个关闭窗口时最小化至托盘的选项，防止误操作关闭maa

**Comment by ABA2396** [comment]
现在有最小化时隐藏至托盘的设置选项，需要再加个关闭窗口隐藏只托盘吗？我感觉有点重复了

**Comment by Ptilopsis01** [comment]
> 现在有最小化时隐藏至托盘的设置选项，需要再加个关闭窗口隐藏只托盘吗？我感觉有点重复了

我觉得这两个不太一样，最小化隐藏至托盘只是最小化的时候放在后台，点了关闭窗口还是会把窗口直接关了
其实我主要是觉得需要一个防止误操作关闭窗口的机制

**Comment by i4P1** [comment]
赞同，特别是想在24小时开机的mini PC上挂机的时候经常误操作到关闭窗口的按钮，结果可能过了一两天才能发现MAA不在后台

**Comment by moomiji** [comment]
MAA有关闭/重启自身的行为，这个功能实际上蛮难搞的

改为`不显示关闭按钮`如何，关闭只能从托盘或者任务栏里右键关闭？

**Comment by Ptilopsis01** [comment]
> MAA有关闭/重启自身的行为，这个功能实际上蛮难搞的
> 
> 改为`隐藏关闭按钮`如何，关闭只能从托盘或者任务栏里右键关闭？

这个可以，或者关闭时有个提示弹窗也行

**Comment by ABA2396** [comment]
> MAA有关闭/重启自身的行为，这个功能实际上蛮难搞的
> 
> 改为`隐藏关闭按钮`如何，关闭只能从托盘或者任务栏里右键关闭？

现在在运行的时候关掉就会有弹窗问你要不要退出，可以看看那个

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/e2da2192f6f6d67e70d74d52b0405453e6ce65c6/src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs#LL160C9-L160C34

**Comment by MistEO** [comment]
> > MAA有关闭/重启自身的行为，这个功能实际上蛮难搞的
> > 改为`隐藏关闭按钮`如何，关闭只能从托盘或者任务栏里右键关闭？
> 
> 现在在运行的时候关掉就会有弹窗问你要不要退出，可以看看那个

这个不是说不好吗，特别是牛牛抽卡，误点了都没法停了 （

**Comment by ABA2396** [comment]
> > > MAA有关闭/重启自身的行为，这个功能实际上蛮难搞的
> > > 改为`隐藏关闭按钮`如何，关闭只能从托盘或者任务栏里右键关闭？
> > 
> > 现在在运行的时候关掉就会有弹窗问你要不要退出，可以看看那个
> 
> 这个不是说不好吗，特别是牛牛抽卡，误点了都没法停了 （

那不也是自己不看提示~停个屁）~

**Comment by moomiji** [comment]
> > > MAA有关闭/重启自身的行为，这个功能实际上蛮难搞的
> > > 改为`隐藏关闭按钮`如何，关闭只能从托盘或者任务栏里右键关闭？
> > 
> > 
> > 现在在运行的时候关掉就会有弹窗问你要不要退出，可以看看那个
> 
> 这个不是说不好吗，特别是牛牛抽卡，误点了都没法停了 （

~又忘记这茬了~

**Comment by moomiji** [comment]
> > > MAA有关闭/重启自身的行为，这个功能实际上蛮难搞的
> > > 改为`隐藏关闭按钮`如何，关闭只能从托盘或者任务栏里右键关闭？
> > 
> > 
> > 现在在运行的时候关掉就会有弹窗问你要不要退出，可以看看那个
> 
> 这个不是说不好吗，特别是牛牛抽卡，误点了都没法停了 （

这关闭按钮肯定是做成可选功能，关闭过程不会被阻碍
~就是没关闭按钮得拼右键手速~

**Comment by ABA2396** [comment]
那感觉还是做成叉掉就是最小化到托盘来着常见正常一点）

**Comment by moomiji** [comment]
> 那感觉还是做成叉掉就是最小化到托盘来着常见正常一点）

不会啊（

照着轮子抄不知道为啥捕获不了SC_CLOSE消息，不用SC_CLOSE就得把现有的各个关闭行为打上标签，又没找到如何订阅关闭按钮的事件（微软没给），还是用轮子吧（
