### ISSUE TITLE
开了自动编队无法自动选角色

### ISSUE THREAD

**Issue by TianyaoPRC** [MaaAssistantArknights/MaaAssistantArknights#4819]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗开了自动编队在快捷编队界面无限右滑，不会自动选择角色

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11515873/asst.log)
在18.50分左右

### 还有别的吗？

win10专业版，蓝叠模拟器国际版

**Comment by MistEO** [comment]
这个问题其实是明日方舟的 bug，编队选职业的时候有一定概率列表不会弹回来

**Comment by TianyaoPRC** [comment]
好的感谢回答
