### ISSUE TITLE
4.17版本高dpi下窗口大小错误

### ISSUE THREAD

**Issue by Ptilopsis01** [MaaAssistantArknights/MaaAssistantArknights#4822]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

4.17版本从公测版到正式版都有这一问题，我的设备设置了dpi缩放，我一般习惯将maa的窗口缩到最小操作，但4.17版本后每次重新打开maa窗口都不是最小的状态，疑似经过了系统的dpi缩放，然而即使在属性中将高dpi缩放设置为“应用程序”仍然会存在这一问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11516970/asst.log)

### 截图

图一为关闭前的窗口大小，图二为重新打开的窗口大小，系统dpi缩放为主屏幕125%，副屏幕150%，图中窗口始终在副屏幕上
![屏幕截图 2023-05-19 205027](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/93318731/f516aa28-f9f5-4f85-a9d7-cf2e7159d8f4)
![屏幕截图 2023-05-19 205054](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/93318731/896eac9f-6e8a-41f2-8cbb-e143ea54f78e)

**Comment by moomiji** [comment]
我这复现不出来...
麻烦发一下`gui.log`，然后用`SaveWindowState.exe`重新截下图

[SaveWindowState.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11517989/SaveWindowState.zip)

**Comment by moomiji** [comment]
```json
  "GUI.Placement.SaveOnClosing": "True",
  "GUI.Placement.Load": "True",
  "GUI.Placement": ""
```

`MAA\config\gui.json`中的这三行，配置的是记住窗口位置功能，不需要可以改为`"GUI.Placement.Load": "False"`
或者，固定一个位置启动:
```json
  "GUI.Placement.SaveOnClosing": "False",
  "GUI.Placement.Load": "True",
  "GUI.Placement": ".....{Left:1000,Top:1000,Right:1000,Bottom:1000}......"
```
把Right、Bottom的值改成和Left、Top一样应该可以强制最小窗口窗口启动

**Comment by Ptilopsis01** [comment]
> 我这复现不出来... 麻烦发一下`gui.log`，然后用`SaveWindowState.exe`重新截下图
> 
> [SaveWindowState.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11518081/SaveWindowState.zip)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11518425/gui.log)
这软件咋用啊，没看明白（）

**Comment by moomiji** [comment]
> 
> [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11518425/gui.log) 这软件咋用啊，没看明白（）

[SaveWindowStateNew.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11518458/SaveWindowStateNew.zip)

重新发了一下，用这个新的
打开后，像截图那样
> 图一为关闭前的窗口大小，图二为重新打开的窗口大小，系统dpi缩放为主屏幕125%，副屏幕150%，图中窗口始终在副屏幕上

复现一次，然后把截图发过来就OK

**Comment by Ptilopsis01** [comment]
> > [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11518425/gui.log) 这软件咋用啊，没看明白（）
> 
> [SaveWindowStateNew.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11518458/SaveWindowStateNew.zip)
> 
> 重新发了一下，用这个新的 打开后，像截图那样
> 
> > 图一为关闭前的窗口大小，图二为重新打开的窗口大小，系统dpi缩放为主屏幕125%，副屏幕150%，图中窗口始终在副屏幕上
> 
> 复现一次，然后把截图发过来就OK

这个我打开窗口大小是正常的，不会出现提到的问题

**Comment by Ptilopsis01** [comment]
> > [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11518425/gui.log) 这软件咋用啊，没看明白（）
> 
> [SaveWindowStateNew.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11518458/SaveWindowStateNew.zip)
> 
> 重新发了一下，用这个新的 打开后，像截图那样
> 
> > 图一为关闭前的窗口大小，图二为重新打开的窗口大小，系统dpi缩放为主屏幕125%，副屏幕150%，图中窗口始终在副屏幕上
> 
> 复现一次，然后把截图发过来就OK

奇怪，我发现我把maa的属性里“更改高dpi设置”的选项取消了之后反而恢复正常了，有点懵（）

**Comment by moomiji** [comment]
> 奇怪，我发现我把maa的属性里“更改高dpi设置”的选项取消了之后反而恢复正常了，有点懵（）

应该是这个问题了，这相当于禁用缩放了（
>在 Windows 版本 1703 10 和更高版本的 Windows 中，禁用显示缩放在高 DPI 设置选项的文本更改为覆盖高 DPI 缩放行为，通过执行缩放： 应用程序。

测试也可以复现，上面是启动后的位置，下面是启用“更改高dpi设置”前的位置
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35213527/d7b60bc5-a9bf-49f2-a501-029ef7bc51da)
