### ISSUE TITLE
日服主线相关关卡无法打

### ISSUE THREAD

**Issue by 2959349732** [MaaAssistantArknights/MaaAssistantArknights#4828]
### 说说你遇到的问题？

日服主线选择关卡时没反应
![1684547696453](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134115980/fbcf0376-23dd-4d56-96f9-24aee6270b23)
以前是可以的，最近一直在章节选择方面无法识别或者识别错误

**Comment by ABA2396** [comment]
发下日志

**Comment by 2959349732** [comment]
?

**Comment by 2959349732** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11523589/asst.log)

**Comment by Constrat** [comment]
This has been fixed in the latest versions. IIRC update MAA to around 4.26.beta
