### ISSUE TITLE
新版本打不开，提示设置 connectionId 时引发了异常，字段丢失

### ISSUE THREAD

**Issue by spoosn** [MaaAssistantArknights/MaaAssistantArknights#4829]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打不开程序，提示设置 connectionId 时引发了异常。
“HandyControl.Controls.NumericUpDown”的类型初始值设定项引发异常。
找不到字段:“System.Windows.Controls.Primitives.TextBoxBase.SelectionTextBrushProperty”。
只有这次更新出现，之前从未有过。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11521374/asst.log)

**Comment by ABA2396** [comment]
右下角 常见问题 下运行库

**Comment by MistEO** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/d1e8f157-8c87-4f11-a358-f2b700b6fadf)
