### ISSUE TITLE
累计已刷关次数在手动结束代理失败的作战时，出现了异常值

### ISSUE THREAD

**Issue by NtskwK** [MaaAssistantArknights/MaaAssistantArknights#483]
~~我恨死活动里的闪避怪啦~~
代理失败后，MAA有一定概率卡在结算界面，手动结束后，MAA继续进行自动刷图。此时MAA的累计刷关次数有一定概率会变成一个不正常的负数。

设备：蓝叠模拟器国际版  1920*1080  240DPI

MAA挂了一天，生成的80w行log就不发了QAQ
只截了一段比较重要的出来orz
[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8663297/asst.-.log)

**Comment by MistEO** [comment]
日志信息太少了，可以的话尽量把日志发出来。或者发个 tail -100000 之类的（

**Comment by NtskwK** [comment]
这里是二十分钟以内的
[asst.-.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8668996/asst.-.log)
感觉再往前就是上一次肉鸽的了，不知道中间那一段是不是就是重新开始新的```一键长草```。因为MAA一直都没关，只是换了游戏帐号而已quq
然后这里是一个小时以内的
[asst.bak - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8669036/asst.bak.-.log)
