### ISSUE TITLE
OF-1错误地多次行动，提示为掉落识别错误

### ISSUE THREAD

**Issue by mouyuu** [MaaAssistantArknights/MaaAssistantArknights#4830]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

开启了“借助战打OF-1赚信用”，然后发现程序一直在重复进行OF-1的行动，提示掉落识别错误，实际也只是单纯的代理作战，并没有借好友助战

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11521478/asst.log)

### 截图

![QQ截图20230520110906](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34743678/d6906de3-2edb-4321-b05e-61da9ce05213)

**Comment by mouyuu** [comment]
![OF-1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34743678/12f22671-8045-4485-8b29-51279645c0ef)
补充一下，看了debug/map里有一张图好像是之前借了助战，但是我发现的时候并没有助战，可能只是单纯的掉落识别错误导致程序重复运行

**Comment by mouyuu** [comment]
我发现问题了，应该不是bug，我是因为把“刷理智”放到了最后并且没有指定关卡，又因为OF-1行动不耗理智导致“刷理智”一直在循环运行。建议程序设置优化一下选择借助战刷信用后强制要求刷理智下指定关卡，如果不指定的话无论顺序如何最后总会出错

**Comment by MistEO** [comment]
新版本改了，刷理智如果检测到是 OF-1 会强制结束任务

**Comment by ABA2396** [comment]
> 我发现问题了，应该不是bug，我是因为把“刷理智”放到了最后并且没有指定关卡，又因为OF-1行动不耗理智导致“刷理智”一直在循环运行。建议程序设置优化一下选择借助战刷信用后强制要求刷理智下指定关卡，如果不指定的话无论顺序如何最后总会出错

借助战功能本来就不会在关卡选择为 当前/上次 的时候跑，是之前选了关卡的时候执行了借助战打OF-1，导致上次关卡变成了OF-1，虽然这次没跑但进的上次的关卡还是这个

**Comment by mouyuu** [comment]
> > 我发现问题了，应该不是bug，我是因为把“刷理智”放到了最后并且没有指定关卡，又因为OF-1行动不耗理智导致“刷理智”一直在循环运行。建议程序设置优化一下选择借助战刷信用后强制要求刷理智下指定关卡，如果不指定的话无论顺序如何最后总会出错
> 
> 借助战功能本来就不会在关卡选择为 当前/上次 的时候跑，是之前选了关卡的时候执行了借助战打OF-1，导致上次关卡变成了OF-1，虽然这次没跑但进的上次的关卡还是这个

我发现了，即使进行了关卡选择，还是会清除所选择的关卡执行OF-1，然后执行”刷理智“时循环执行上次的关卡OF-1，我今天又刷了三十多次，等这个功能修复吧

**Comment by ABA2396** [comment]
没看懂，啥叫清除下载？你开了隐藏未开放关卡吗？
