### ISSUE TITLE
使用无线连接平板会导致MAA进程异常退出 版本号v4.17.0-beta.1

### ISSUE THREAD

**Issue by wdnmd15968** [MaaAssistantArknights/MaaAssistantArknights#4832]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

平板为小米平板5，然后根据MAA官网的无线连接平板的教程，设置了无线连接，可以连接上，但是无线连接进行开始唤醒后，MAA进程异常退出。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11521536/asst.log)
2023/5/20 12:05

**Comment by MistEO** [comment]
你分辨率没改吗？

**Comment by wdnmd15968** [comment]
分辨率按照教程里的的bat来，但是没改成功
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94177713/bf8f76bb-b375-4a96-9467-806ad741e99f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94177713/478931fb-59e2-4cfe-909c-1d3ed1bc4452)
按照教程是放在MAA的目录下，还是说要放在adb的目录下？

**Comment by wdnmd15968** [comment]
抱歉，找到问题了，应该将adb解压到MAA的目录下，而不是单独成一个目录。不好意思，麻烦你了

**Comment by wdnmd15968** [comment]
> 你分辨率没改吗？

抱歉，找到问题了，应该将adb解压到MAA的目录下，而不是单独成一个目录。不好意思，麻烦你了。
目前没有运行成功，且暂时没有出现BUG
