### ISSUE TITLE
水月肉鸽职业队刷取指定精二开局

### ISSUE THREAD

**Issue by zxxsmart** [MaaAssistantArknights/MaaAssistantArknights#4833]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

指定一个需要精二的开局干员，直接重开刷，不需要到第三层拿开局奖励

**Comment by MistEO** [comment]
没明白，啥意思。指定干员不行吗

**Comment by liuyifan-eric** [comment]
> 没明白，啥意思。指定干员不行吗

水月的职业队（比如术特、重辅）不像傀影，初始干员是抽取几个直升精二，其他的都是精一。比如用重辅，开局令刷出来的可能是精一

**Comment by Lancarus** [comment]
#4791
