### ISSUE TITLE
无人机用途无法切换

### ISSUE THREAD

**Issue by Adrian145** [MaaAssistantArknights/MaaAssistantArknights#4835]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建高级设置内 无人机用途无法切换

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11521924/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/14179667/b86849ac-e32b-4c7c-985d-268c89895b62)

**Comment by ABA2396** [comment]
都开了 `自定义基建配置` 了，走的都是 `基建计划` 里的设置，改这个又有啥用

**Comment by MistEO** [comment]
这个只在非 自定义基建 时有效

**Comment by Adrian145** [comment]
> 这个只在非 自定义基建 时有效
是否UI配置错误？ 如果如上的化自定义时这里应该不需要这个显示
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/14179667/272fc18a-063b-44f5-b13d-69046cbc1fdc)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/14179667/b8f74b79-0b47-4879-9752-d26718ed3bee)
