### ISSUE TITLE
基建换班相关：对加工站和训练室添加换人功能

### ISSUE THREAD

**Issue by zqzhang1996** [MaaAssistantArknights/MaaAssistantArknights#4837]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

年作为人间烟火组件不能放置于宿舍，一般放在加工站，但是本身是顶级合成材料技能，经常会有合成之后放进宿舍然后忘记好几天的情况。

### 有什么好的想法？

考虑到这次缪缪发电也是需要5莱茵在基建，需求的位置较多，如果训练室闲置的话可以考虑利用，将来可能会有更多类似情况，因此希望对加工站和训练室都添加换人功能，做到全设施可定义。
另外若添加训练室换人功能，应当提供检测到协助位为艾丽妮则跳过训练室的选项并默认开启，以避免打断其技能效果。

**Comment by zqzhang1996** [comment]
补充，对这两个设施应采用默认skip的形式以兼容旧的配置文件

**Comment by MistEO** [comment]
#4610

**Comment by MistEO** [comment]
fixed
