### ISSUE TITLE
版本热更新后热键设置被清除

### ISSUE THREAD

**Issue by xjr353171020** [MaaAssistantArknights/MaaAssistantArknights#4838]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

公测版，自动更新完后热键设置回归<not set>。截至目前发生了两次或三次

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11522402/asst.log)

**Comment by moomiji** [comment]
麻烦发一下 gui.log

**Comment by xjr353171020** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11522848/gui.log)
[gui.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11522849/gui.bak.log)
