### ISSUE TITLE
是不是不支持蓝叠5？

### ISSUE THREAD

**Issue by tyx776** [MaaAssistantArknights/MaaAssistantArknights#4839]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

就是无法连上蓝叠5。设置手动设置蓝叠5 adb也没有作用。尝试过重启电脑模拟器都没有用。蓝叠4可以正常使用。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11522453/asst.log)
5.20 21：35左右

**Comment by ABA2396** [comment]
maa.plus/docs

**Comment by MistEO** [comment]
看文档
