### ISSUE TITLE
用理智药刷理智时检查会不会超出理智上限

### ISSUE THREAD

**Issue by 9lanx1N** [MaaAssistantArknights/MaaAssistantArknights#4847]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

方舟在几个月前将大理智药的理智回复数从100添加到了120。这样的话，就有可能出现加完理智药后，理智溢出的情况。其实这没什么大不了的，因为很快就会刷一个关卡，让理智不再溢出。但作为方舟葛朗台，还是感觉亏了，还是希望MAA**尽可能**杜绝这种情况的发生（不强求，因为在极端情况下这是杜绝不了的）。

### 有什么好的想法？

把用理智药的逻辑改为：

设理智上限为N，当前理智数为n；
* 若 n < N - 120，则优先用大理智药；
* 若 n >= N - 120，则优先用小理智药，如果没有小理智药，那再用大理智药

（更新：有人已经提到了博朗台碎石模式，尚不清楚它对于刷理智有没有效，但这一功其实能和我的建议并不冲突，可一并存在）

### 其他内容

八个建议其七

在任务完成栏加入仅返回主屏幕功能、公招券仅剩n时停止招募3星、任务进行时的退出弹窗可选择不开启、基建会客室自动赠送线索、识别“战斗中”和“战斗完成”的截图、代理失败时可选择继续刷还是停止任务、**用理智药刷理智时检查会不会超出理智上限**、增加“任务暂停”功能

又想到一个建议：吃理智药不按次数吃而按剩余天数吃，所以其实是九个建议其七

**Comment by ABA2396** [comment]
方舟不是自动给你吃到够这一关的理智吗？
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/fcf0d480-7324-4846-8059-a11e739e2b31)
不过这个不能满足要求吗

**Comment by ABA2396** [comment]
好像确实 @MistEO 这玩意是不是只有碎石才做了，要不给理智药也加个）

**Comment by 9lanx1N** [comment]
> 方舟不是自动给你吃到够这一关的理智吗？ ![image](https://user-images.githubusercontent.com/99072975/239699160-fcf0d480-7324-4846-8059-a11e739e2b31.png) 不过这个不能满足要求吗

“不碎石时该选项不影响正常运行”，我的理解是这个功能只有在碎石时有用，在吃理智药时没有用，所以从来就没管过这个选项。现在我并没有能力去确认吃理智药时它到底有没有用（因为理智药已经用完了），如果没有用，那只能烦请各位大佬扩大它的适用面积了；如果有用的话，那说明这句话描述不准确，需要修改措辞。

**Comment by MistEO** [comment]
> 好像确实 @MistEO 这玩意是不是只有碎石才做了，要不给理智药也加个）

改了，UI 交给你了（

**Comment by 9lanx1N** [comment]
谢谢MistEO佬和ABA2396佬！
