### ISSUE TITLE
增加“任务暂停”功能

### ISSUE THREAD

**Issue by 9lanx1N** [MaaAssistantArknights/MaaAssistantArknights#4848]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有时在MAA任务进行时需要临时暂停MAA进行一些手动操作，但MAA只有停止功能没有暂停功能，于是在手动操作完毕后只能让MAA从头开始所有操作，感觉浪费了许多时间和不必要的操作。

### 有什么好的想法？

增加“任务暂停”功能，以可以从当前任务继续MAA的自动化操作。

### 其他内容

九个建议其八

在任务完成栏加入仅返回主屏幕功能、公招券仅剩n时停止招募3星、任务进行时的退出弹窗可选择不开启、基建会客室自动赠送线索、识别“战斗中”和“战斗完成”的截图、代理失败时可选择继续刷还是停止任务、用理智药刷理智时检查会不会超出理智上限、**增加“任务暂停”功能**、吃理智药不按次数吃而按剩余天数吃

**Comment by MistEO** [comment]
架构上做不到

**Comment by 9lanx1N** [comment]
好的qaq

**Comment by hifuclub** [comment]
可惜不能实现,经常因为忘了吃理智药重新看20分钟换基建,不关了基建直接战斗是因为打完大概率忘记点回去,导致好几天没换基建qaq
不过有个解决办法就是在复制一份maa,这样两套maa可以执行不同的设置,准备一个专门用来清体力的maa

**Comment by 9lanx1N** [comment]
> 可惜不能实现,经常因为忘了吃理智药重新看20分钟换基建,不关了基建直接战斗是因为打完大概率忘记点回去,导致好几天没换基建qaq 不过有个解决办法就是在复制一份maa,这样两套maa可以执行不同的设置,准备一个专门用来清体力的maa

这样的话，你必须得等清体力的MAA完成之后再打开清基建的MAA（要不然两边会打架），于是你又忘了<(＿　＿)>。我觉得目前最好的解决方案就还是等MAA把方舟启动后马上停止MAA，然后手动打一关再开启MAA，不过这就要说到我刚刚问的另一个问题了，MAA它没法识别战斗中和战斗完成，导致战斗也和MAA打架，因此必须等战斗打完后再开启MAA，这会浪费不少时间……

**Comment by hifuclub** [comment]
> 
> 这样的话，你必须得等清体力的MAA完成之后再打开清基建的MAA（要不要两边会打架），于是你又忘了<(＿＿)>。我觉得得目前最好的解决方案还是等等MAA把方舟启动后马上停止MAA，然后手动打一关再启动MAA，不过这就要说到我刚问的另一个问题了，MAA它没法识别战斗中和战斗完成，导致战斗也和MAA打架，因此必须等战斗打完后再开启MAA，这会浪费不少时间……

我有一个设置在计划任务里的maa,那个maa是不会轻易更改设置的.然后又准备了一个手动操作的maa,如果计划任务的maa出错的话,我会终止它,然后设置剩下的任务给手动maa执行.这样计划任务的maa下次还能正常执行.
当然吃体力药还有个办法,就是等maa进战斗以后以迅雷不及掩耳盗铃之势退出战斗回主页吃一口然后再回战斗,我试过maa刚进战应该会休眠一段时间(逃

**Comment by 9lanx1N** [comment]
> > 这样的话，你必须得等清体力的MAA完成之后再打开清基建的MAA（要不要两边会打架），于是你又忘了<(＿＿)>。我觉得得目前最好的解决方案还是等等MAA把方舟启动后马上停止MAA，然后手动打一关再启动MAA，不过这就要说到我刚问的另一个问题了，MAA它没法识别战斗中和战斗完成，导致战斗也和MAA打架，因此必须等战斗打完后再开启MAA，这会浪费不少时间……
> 
> 我有一个设置在计划任务里的maa,那个maa是不会轻易更改设置的.然后又准备了一个手动操作的maa,如果计划任务的maa出错的话,我会终止它,然后设置剩下的任务给手动maa执行.这样计划任务的maa下次还能正常执行. 当然吃体力药还有个办法,就是等maa进战斗以后以迅雷不及掩耳盗铃之势退出战斗回主页吃一口然后再回战斗,我试过maa刚进战应该会休眠一段时间(逃

你的这一套听上去很有道理的样子……战斗退出那个应该会消耗1点理智吧，本葛朗台表示还是算了（

**Comment by hifuclub** [comment]
> 你必须得等清体力的MAA完成之后再打开清基建的MAA（要不然两边会打架），于是你又忘了<(＿　＿)>。我觉得目前最好的解决方案就还是等MAA把方舟启动后马上停止MAA，然后手动打一关再开启MAA，不过这就要说到我刚刚问的另一个问题了，MAA它没法识别战斗中和

我日常手打突袭翻车,翻了的体力可能也有一两千了,不差那一点(

**Comment by 9lanx1N** [comment]
> 架构上做不到，而且也没法保证暂停回来还是原来的界面，一点点的偏差都可能导致后续任务全部失败

我突然想到隔壁[有一个方舟自动化工具](https://github.com/tkkcc/ArkLights)就实现了暂停功能，不知道有没有参考性（

**Comment by 9lanx1N** [comment]
> > 你必须得等清体力的MAA完成之后再打开清基建的MAA（要不然两边会打架），于是你又忘了<(＿　＿)>。我觉得目前最好的解决方案就还是等MAA把方舟启动后马上停止MAA，然后手动打一关再开启MAA，不过这就要说到我刚刚问的另一个问题了，MAA它没法识别战斗中和
> 
> 我日常手打突袭翻车,翻了的体力可能也有一两千了,不差那一点(

但我是葛朗台（）

**Comment by hifuclub** [comment]
> > > 你必须得等清体力的MAA完成之后再打开清基建的MAA（要不然两边会打架），于是你又忘了<(＿　＿)>。我觉得目前最好的解决方案就还是等MAA把方舟启动后马上停止MAA，然后手动打一关再开启MAA，不过这就要说到我刚刚问的另一个问题了，MAA它没法识别战斗中和
> > 
> > 
> > 我日常手打突袭翻车,翻了的体力可能也有一两千了,不差那一点(
> 
> 但我是葛朗台（）

我忽然想到一个办法,等你退出405次以后,就给游戏充六块钱,我考虑等到游戏关服都未必能攒够405次,这样你也不用给游戏充钱了,我真是天才XD

**Comment by hifuclub** [comment]
> > 架构上做不到，而且也没法保证暂停回来还是原来的界面，一点点的偏差都可能导致后续任务全部失败
> 
> 我突然想到隔壁[有一个方舟自动化工具](https://github.com/tkkcc/ArkLights)就实现了暂停功能，不知道有没有参考性（

maa一开始时候没考虑要做这个功能,毕竟暂停就像越狱一样会带来不可控因素,所以等以后想加上去可能比较困难?我猜的,而且还会增加微不足道的计算量.
主要原因我觉得还是不可控且没必要.
