### ISSUE TITLE
开始运行后卡死未响应

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#4852]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

开始运行后卡死未响应

### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11523478/asst.-.log)

### 截图

![K@S3@98VZ8MI@YO{ KQ}`AJ](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/b7437e70-f291-44c2-9ca1-6cd69f86d8d3)

**Comment by vingues** [comment]
我更新了v4.17.1后也有这种情况，我是每天设置8：30和14：35定时重启电脑，电脑重启自动启动MAA，MAA启动后能正常启动模拟器，但MAA主程序白屏卡死，程序无响应。两天复现了三次，每次定时启动都会卡死，但卡死后重启MAA就能正常运行。
MAA - v4.17.1-真理孑然–蓝叠模拟器(emulator-5554) - Bilibili服

**Comment by imaegoo** [comment]
同样的问题+1，概率复现。模拟器为蓝叠国际版

**Comment by Dilrevx** [comment]
+1, 大概 20% 的出现频率，蓝叠国际版。关了再开就正常
