### ISSUE TITLE
minitouch错误

### ISSUE THREAD

**Issue by dylanhz** [MaaAssistantArknights/MaaAssistantArknights#4853]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新4.17.1正式版后，minitouch无法正常工作。
昨天出问题后，我尝试切换为adb input，可以正常使用，后面又切回minitouch，也能够正常使用，但今早9点还是出现了和之前一样的问题。
在本次更新之前从未出现过这方面的故障。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11523602/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11523603/gui.log)
[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11523618/asst.bak.zip)

**Comment by vonnoq** [comment]
我應該也是遇到一樣的問題
定時啟動後會卡在gamestart

時間在 [2023-05-21 18:01:15.095] 
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11524319/asst.log)

**Comment by MistEO** [comment]
模拟器更新了吧，强制替换一下 adb
