### ISSUE TITLE
借助战打OF-1赚信用显示掉落识别错误

### ISSUE THREAD

**Issue by QsRive** [MaaAssistantArknights/MaaAssistantArknights#4854]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

借助战打OF-1赚信用显示掉落识别错误然后一直循环该项目

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11523715/asst.zip)
自5月21日上午8：00到下午12:30之间

**Comment by ABA2396** [comment]
关卡选择选的是啥
