### ISSUE TITLE
基建只进驻第一个发电站和宿舍

### ISSUE THREAD

**Issue by nodks** [MaaAssistantArknights/MaaAssistantArknights#4855]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

只会进驻第一个发电站和宿舍
发电站15:00-15:01
宿舍15:03-15:04

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11523876/asst.log)

### 截图

![屏幕截图(35)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/127360125/82ba46fd-89d8-4fee-a80f-a3e0d0a16ca2)
![屏幕截图(36)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/127360125/a2799091-a869-4556-baf4-f617109fb861)

**Comment by lantianlwm** [comment]
请问解决了吗?我也是这样(v.v)

**Comment by nodks** [comment]
> 请问解决了吗？我也是这样（v.v）

没有，不过不用自定义换班只会偶尔出现问题
