### ISSUE TITLE
傀影肉鸽 不会自动下干员 第一关就任务失败了

### ISSUE THREAD

**Issue by 10969qaq** [MaaAssistantArknights/MaaAssistantArknights#4860]
### 在提问之前...

- [ ] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

傀影肉鸽 不会自动下干员 第一关就任务失败了

### 日志文件

傀影肉鸽 不会自动下干员 第一关就任务失败了

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f63c3140-79f1-4ddd-91e7-edcc870b2b21)
