### ISSUE TITLE
maa肉鸽关卡内不执行放置干员

### ISSUE THREAD

**Issue by Asculture** [MaaAssistantArknights/MaaAssistantArknights#4861]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa肉鸽关卡内不放置干员，编队选择与干员编队都正常

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11524252/asst.log)
时间2023.5.21   17：20左右

**Comment by MistEO** [comment]
[`924fc64` (#4902)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/4902/commits/924fc64302cbf4e7f1b5c7ae6cc971ebeb43b04e) fixed
