### ISSUE TITLE
MAA自动肉鸽功能关卡内没有执行摆放干员

### ISSUE THREAD

**Issue by Asculture** [MaaAssistantArknights/MaaAssistantArknights#4862]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动肉鸽功能关卡内没有执行摆放干员，分队的选择与干员的编队都是正常执行

### 日志文件

开始时间2023-05-21  18:37:14.872
[Uploading asst.7z…]()

### 截图

![Uploading image.png…]()

### 还有别的吗？

mumu模拟器12
操作系统win64

**Comment by FroZzzzzen** [comment]
一样的问题，自动肉鸽的时候可以正常选人编队开始，但是一进作战就不会放干员，漏怪漏到没血了直接下一把肉鸽
模拟器也是 MuMu模拟器12（X）
系统windows 11 25357.1
模拟器分辨率1280*720
三种触控方式都试过了
昨天晚上（5.21）挂机的时候才出现的问题，此前一切正常
![屏幕截图(122)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134297042/ab68cb5c-9a0d-4d7e-82ad-bdf764043f7c)

**Comment by FroZzzzzen** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11533020/asst.log)
我的日志文件在这里

**Comment by MistEO** [comment]
[`924fc64` (#4902)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/4902/commits/924fc64302cbf4e7f1b5c7ae6cc971ebeb43b04e) fixed
