### ISSUE TITLE
小工具中的牛牛抽卡，希望增加一个自己选择是否抽卡功能

### ISSUE THREAD

**Issue by skyesing** [MaaAssistantArknights/MaaAssistantArknights#4864]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134205255/5c280b12-ff8d-4beb-9f17-1e7b5ff58046)

1.今天更新后出现个牛牛抽卡功能，以为模拟抽卡。点了下十连，结果直接去到自动跳转到游戏抽卡了，当我反应过来已经抽完了，希望这个抽卡可以有个关闭，以免平时使用有误触现象
2.抽卡也没卡池选择项，可能默认第一个卡池

**Comment by ABA2396** [comment]
1. ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7480790f-e51b-4e30-a579-99c74a206019)
2. 没在抽卡界面是抽第一个卡池，在抽卡界面就抽当前卡池

**Comment by skyesing** [comment]
好的，那没啥问题了，感谢

**Comment by skyesing** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134205255/4cf7ad9b-70a8-41a8-a79c-38789fd864b3)
我去看了下我的，我这版本不是最新？

**Comment by ABA2396** [comment]
> ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134205255/4cf7ad9b-70a8-41a8-a79c-38789fd864b3)
> 我去看了下我的，我这版本不是最新？

每次启动显示一次，你已经确认了

**Comment by skyesing** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134205255/1b68c2fa-c7fd-4c1d-9b90-0926d67f4f05

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134205255/25885aef-9153-4320-93e9-fc4948b16e14)我这边重新退出再进来没有发现不是模拟抽卡的提示，录制了一个视频，帮忙看下

**Comment by ABA2396** [comment]
那看样子是只会显示一次，改改好了

**Comment by skyesing** [comment]
好的，感谢
