### ISSUE TITLE
关卡名OCR识别大小写出错导致掉落上传失败

### ISSUE THREAD

**Issue by SherkeyXD** [MaaAssistantArknights/MaaAssistantArknights#4867]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷CW-8时出现掉落上传失败的现象
查看日志发现原因是关卡名字大小写识别错误，识别成了cW-8（见日志）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11524766/asst.log)
时间点 2023-05-21 21:54:21.484
问题在这里
`[2023-05-21 21:54:21.484][INF][Px34a4][Tx189c] Assistant::append_callback | SubTaskError {"details":{"stage_code":"cW-8"},"taskchain":"Fight","taskid":8,"why":"UnknownStage","class":"asst::StageDropsTaskPlugin","subtask":"ReportToPenguinStats","uuid":"35ca683adbb4aab3"}`

### 截图

![QQ图片20230521222739](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57581480/9ae52370-8a91-4d27-897c-1a1d0852fb8e)

### 还有别的吗？

考虑一下上传的时候加个大小写转换？
不过ocr居然能把这个识别错也是够神奇的

**Comment by ABA2396** [comment]
好像也没问题，关卡名没有带小写的吧

**Comment by ABA2396** [comment]
> 就我印象中是没有小写关卡名的 可关键是ocr识别错了啊）

对，我的意思是可以直接换成大写的（）

**Comment by SherkeyXD** [comment]
> 对，我的意思是可以直接换成大写的（）

我也这么想的）
