### ISSUE TITLE
MAA更新后出现问题

### ISSUE THREAD

**Issue by hashrushgo** [MaaAssistantArknights/MaaAssistantArknights#4869]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Maa V4.17.0更新到V4.17.1时更新出现问题，弹出窗口如下
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92534105/2078c1fe-94d9-4321-a41e-3041650eb310)
同时本人同目录下另一个Maa从V4.16.4更新到V4.17.0时也有这个弹窗
本人同目录下倒是有另一个Maa和MaaX，有没有可能是这方面的问题

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11525927/asst.zip)

### 截图

![DOPS_S 4RO`IR0RA6 B$ZS6](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92534105/0a567e83-fd7e-4108-bbc0-063617c38c3e)

### 还有别的吗？

Windows系统

**Comment by pein0saga** [comment]
每个星期都会出现一次的提问，不知道是不是和微软更新库机制出现了相关bug

**Comment by ABA2396** [comment]
4.17.1修过了，手动把.old文件夹里的东西删了就好了吧

**Comment by hashrushgo** [comment]
已解决，谢谢
