### ISSUE TITLE
没有勾选的情况下无限打OF-1，并且必须自己手动停止

### ISSUE THREAD

**Issue by rainocean** [MaaAssistantArknights/MaaAssistantArknights#4871]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

没有勾选的情况下每天第一次运行的时候无限打OF-1，并且必须自己手动停止。
版本4.17.2 alpha，不过这个好像是上一个版本就开始有这种表现，更新之后没有改变。
另外我记得我把关卡选择固定在CW-10，活动即使结束了，关卡选择自动跳到没选择的情况下为什么会自动打OF-1呢？

### 日志文件

[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11525955/asst.-.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16640966/d12aa167-ff28-49b3-8083-869b56e02958)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16640966/ce2da56a-a43d-4a2e-bfd5-6dd1087583b4)

**Comment by ABA2396** [comment]
关卡选择为空的时候是打上一次的关卡吧？之前的上次关卡是啥

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/30301d1c-8898-4ad8-811b-89e242b41688)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f8ffc8cf-1eaa-4683-9379-040083531216)

**Comment by MorphineA** [comment]
> 关卡选择为空的时候是打上一次的关卡吧？之前的上次关卡是啥

上次大更新后就有这问题了，关卡选择会在4点刷新后自动变成空，无论之前选择的什么关卡，后面都是重复打0F-1，然后一直重复OF-1掉落错误，只能手动停止。

**Comment by ABA2396** [comment]
没搞懂，我刚刚测了下4点更新都是符合预期的行为，也没出现变空的情况。你刷理智的高级设置选了哪些？

**Comment by MorphineA** [comment]
> 没搞懂，我刚刚测了下4点更新都是符合预期的行为，也没出现变空的情况。你刷理智的高级设置选了哪些？

MAA版本4.17.1      雷电模拟器
高级设置勾选了     无限吃48小时内过期的理智药、隐藏当日不开放关卡  这两项，
刷理智常规设置一直都是关卡选择1-7，剩余理智1-7。
UI界面大更新之前没有这样的问题，之后每天凌晨4点后第一次运行都会出现OF-1的问题，我是24小时挂机，明天抓个日志

**Comment by ABA2396** [comment]
改本地时间就行了，改到3.59看看会有什么情况

**Comment by ABA2396** [comment]
@MistEO 快来测测

**Comment by MorphineA** [comment]
> @MistEO 快来测测



> 改本地时间就行了，改到3.59看看会有什么情况

刚刚换了个号 ，复现了这个BUG，从 16点16分开始的，
只要每天第一次用MAA，_获取信用和购物_  里面勾选了 助战打OF-1
就会出现自动清空关卡选择，然后重复OF-1掉落识别错误。

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11530175/asst.log)

**Comment by ABA2396** [comment]
```
[2023-05-22 16:09:28.570][INF][Px1964][Tx5ea8] asst::ResourceLoader::load ret 1
[2023-05-22 16:09:28.570][TRC][Px1964][Tx5ea8] asst::ResourceLoader::load | leave, 2 ms
[2023-05-22 16:09:28.573][INF][Px1964][Tx340c] asst::Assistant::set_task_params 27 {"stage":null,"medicine":0,"stone":0,"times":2147483647,"report_to_penguin":true,"client_type":"Official","penguin_id":"551643174","DrGrandet":false,"expiring_medicine":9999,"server":"CN"}
[2023-05-22 16:09:28.573][TRC][Px1964][Tx340c] asst::FightTask::set_params | enter
[2023-05-22 16:09:28.573][TRC][Px1964][Tx340c] asst::FightTask::set_params | leave, 0 ms
```
看日志初步判断是在
`private void Timer1_Elapsed(object sender, EventArgs e)`中的异步更新出现问题
```
_ = Task.Run(async () =>
{
    await Task.Delay(delayTime);
    await _stageManager.UpdateStageWeb();
    UpdateDatePrompt();
    UpdateStageList(false);
});
```
16:09分符合在4/16点延迟0~10分钟（delayTime）的范围内，
`_stageManager.UpdateStageWeb();`会触发`asst::ResourceLoader::load`，
`UpdateStageList(false);`中因为开启了隐藏未开放关卡，所以会导致`StageList`被重新赋值，而依赖`StageList`的`Stage1(关卡选择)`的值可以会被置空，
但此情况在`public void UpdateStageList(bool forceUpdate)`中有过处理
```
if (Instances.SettingsViewModel.HideUnavailableStage)
{
    // update available stage list
    var stage1 = Stage1 ??= string.Empty;
    StageList = new ObservableCollection<CombinedData>(_stageManager.GetStageList(_curDayOfWeek));

    // reset closed stage1 to "Last/Current"
    if (!CustomStageCode)
    {
        Stage1 = _stageManager.IsStageOpen(stage1, _curDayOfWeek) ? stage1 : string.Empty;
    }
}
```
会在更新列表前存一下关卡的值，在更新列表后重新赋值回去
我测试了几次各种组合都没触发选项变成null的情况，不知道有没有条件打个断点看看是不是这里的问题

**Comment by heassa** [comment]
[asst+录屏.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11549475/asst%2B.zip)
1. 这个位置雀食会变成空的，然后它会自己默认打上一次的关卡。
2. 昨天折腾一顿之后无限OF1的情况已经不会发生，虽然我不是昨天才取消勾选OF1，这个选项我没动过
3. 高级设置选择了隐藏当日不开放关卡，不过孤星时期CW关卡活动期内都可用的情况下，也会每天自动跳到啥都没选的状态，于是就变成了无限OF1，感觉是更新列表之后重新赋值回去没成功?

**Comment by ABA2396** [comment]
复现不出来，发个内测版测测

**Comment by rainocean** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11560390/asst.log)
v4.18.2-alpha.1.d009.g38168bf9   2023-5-25  这个问题没有再次出现，附一个log
