### ISSUE TITLE
蓝叠模拟器国际版卡在StartUp

### ISSUE THREAD

**Issue by xibaibaibai** [MaaAssistantArknights/MaaAssistantArknights#4872]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

蓝叠模拟器国际版会卡在StartUp，只有重新打开MAA之后的第一次是正常的，第二次以及之后的都会卡死在这，如下面的截图9：19开始执行startup，直到9：22仍在卡着。这就直接导致定时执行不能正常使用了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11526112/asst.log)

### 截图

![屏幕截图 2023-05-22 092655](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76211797/25b5d0df-c15c-4f13-becd-a594950f6883)

**Comment by dionyang25** [comment]
我夜神也有这问题。。第二次打开到startUp就不动了。第一次正常

**Comment by MistEO** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/9ed66421-2f57-45d7-80b4-df2dd78b474b)
 
这不是蓝叠的地址，你连错了

**Comment by xibaibaibai** [comment]
> ![图像](https://user-images.githubusercontent.com/18511905/240348485-9ed66421-2f57-45d7-80b4-df2dd78b474b.png)
> 
> 这不是蓝叠的地址，你连错了

是的，这是问题所在，但问题发生的原因是我勾选了自动检测连接选项之后MAA便自动将连接地址改为这个emulator-5554，而之前并不会
![屏幕截图 2023-05-24 080841](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76211797/fa785e05-12e0-4b9f-b01c-1192075d2384)

**Comment by pein0saga** [comment]
> 

可能和打开顺序方式有关，有时候我同时开ALAS就会串线连接到舟游的模拟器上

**Comment by pein0saga** [comment]
> > ![图像](https://user-images.githubusercontent.com/18511905/240348485-9ed66421-2f57-45d7-80b4-df2dd78b474b.png)
> > 这不是蓝叠的地址，你连错了
> 
> 是的，这是问题所在，但问题发生的原因是我勾选了自动检测连接选项之后MAA便自动将连接地址改为这个emulator-5554，而之前并不会 ![屏幕截图 2023-05-24 080841](https://user-images.githubusercontent.com/76211797/240445359-fa785e05-12e0-4b9f-b01c-1192075d2384.png)

> 

可能和打开顺序方式有关，有时候我同时开ALAS就会串线连接到舟游的模拟器上
