### ISSUE TITLE
Mac无法选择借助战赚信用，无法保存企鹅物流ID

### ISSUE THREAD

**Issue by YuhangTom** [MaaAssistantArknights/MaaAssistantArknights#4875]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，无法选择借助战赚信用这一选项，无法保存企鹅物流ID，输入之后会立刻消失

### 日志文件

刚入的Mac没找到在哪...而且不太需要的样子...

### 还有别的吗？

Macbook Pro M2 Pro chip
macOS v13.4
PlayCover
MAA v4.17.1

**Comment by ABA2396** [comment]
@hguandl
