### ISSUE TITLE
MuMu模拟器12自动肉鸽不下干员

### ISSUE THREAD

**Issue by FroZzzzzen** [MaaAssistantArknights/MaaAssistantArknights#4896]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动肉鸽功能执行时能正常开局和重开，但是在战斗中不会放干员，导致在第一层的第一个战斗中就漏怪直到生命耗尽
期间有发现自动点击宝箱的行为
模拟器是 mumu模拟器12
目前发现不少人的mumu模拟器12都遇到了同样的不下干员问题
其他功能正常（他人反馈还有保全派驻不下干员的问题）
我首次发现这个问题在5.21凌晨，是MAA某个版本更新后才出现的新BUG

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11545784/asst.log)
大致时间是5/23 23:01开始

### 截图

![屏幕截图(122)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134297042/bd69f97f-588c-481c-bc3b-ba7f1d51b4ea)

### 还有别的吗？

模拟器是  mumu模拟器12（X）
系统是 windows11 Build 25357.1
AMD 5800H 和 RTX3060
录屏链接
https://www.bilibili.com/video/BV1zh411F7db

**Comment by MistEO** [comment]
试试强制替换 adb

**Comment by MistEO** [comment]
[`924fc64` (#4902)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/4902/commits/924fc64302cbf4e7f1b5c7ae6cc971ebeb43b04e) fixed
