### ISSUE TITLE
升级到18.0版本后，进行自动作战时，进入作战后无部署动作。

### ISSUE THREAD

**Issue by xf22cn** [MaaAssistantArknights/MaaAssistantArknights#4899]
如题。能点击作战按钮进入作战，进入作战后有个暂停动作，解除暂停后，无任何动作，不进行部署。
但是MAA右侧有显示作战输出，在极端的时间内显示MAA完成了部署，最后显示作战结束。
日志文件已经上传到MAA作业生产基地，群号：1169188429。
能自动编队。

**Comment by MistEO** [comment]
[`924fc64` (#4902)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/4902/commits/924fc64302cbf4e7f1b5c7ae6cc971ebeb43b04e) fixed
