### ISSUE TITLE
制造站暖机角色换班时会被打断

### ISSUE THREAD

**Issue by curvit** [MaaAssistantArknights/MaaAssistantArknights#490]
清空干员再选中的操作会打断暖机工具人，可以取消清空这个步骤吗？

**Comment by ABA2396** [comment]
我的想法是判断如果是原来三个人就按返回而不是确认，但我不知道怎么写.jpg

**Comment by Shawnsdaddy** [comment]
> 清空干员再选中的操作会打断暖机工具人，可以取消清空这个步骤吗？

并不是清空干员造成的，而是换班后的顺序必须和换班前一样。不然就会重置。 
比如说巫恋体系，巫恋1，柏喙2，龙舌兰3
要换下巫恋用菲亚梅塔恢复的话。
换上的工具人必须要在1号位置，柏喙必须保持在2号位置，不然柏喙的工作时长会重置。

**Comment by horror-proton** [comment]
类似 #1954

**Comment by ABA2396** [comment]
现在自定义基建里有字段控制是否按顺序选择干员，详细看https://yituliu.site/riicCal
