### ISSUE TITLE
I cannot run MAA.

### ISSUE THREAD

**Issue by SPBLAZE** [MaaAssistantArknights/MaaAssistantArknights#4900]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

After updating to 4.18.0 version, I have this error message whenever I run MAA. Below is the error message.

MAA has encountered an error
속성 'System.Windows.ResourceDictionary.DeferrableContent' 설정에서 예외가 throw되었습니다.
항목이 이미 추가되었습니다. 사전에 있는 키: 'GeneralWithoutScreencapErr'  추가되는 키: 'GeneralWithoutScreencapErr'
Solution
Unknown error occurred
Details
System.Windows.Markup.XamlParseException: 속성 'System.Windows.ResourceDictionary.DeferrableContent' 설정에서 예외가 throw되었습니다. ---> System.ArgumentException: 항목이 이미 추가되었습니다. 사전에 있는 키: 'GeneralWithoutScreencapErr'  추가되는 키: 'GeneralWithoutScreencapErr'
   위치: System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   위치: System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)
   위치: System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__297_0(Object target, Object value)
   위치: MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   위치: System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   위치: System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   위치: System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   위치: System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   위치: MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   위치: MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   위치: System.Windows.ResourceDictionary.set_Source(Uri value)
   위치: MaaWpfGui.Helper.LocalizationHelper.Load()
   위치: MaaWpfGui.Main.Bootstrapper.OnStart()
   위치: Stylet.BootstrapperBase.Start(String[] args)
   위치: System.Windows.Application.OnStartup(StartupEventArgs e)
   위치: System.Windows.Application.<.ctor>b__1_0(Object unused)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Log files

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11546395/gui.log)

### Anthing else?

Bluestacks, Windows 10.

**Comment by 178619** [comment]
For now you can either manually set "GUI.Localization" to other languages (such as "en-us") in the `config/gui.json` file or [download the nightly version](https://github.com/MaaAssistantArknights/MaaAssistantArknights/suites/13093123586/artifacts/710668381) and replace `MAA.exe`. This happens because the file I uploaded was invalid, I'm sorry!
#4898
