### ISSUE TITLE
M1电脑开始唤醒任务出错

### ISSUE THREAD

**Issue by Git-zhoujunjie** [MaaAssistantArknights/MaaAssistantArknights#4901]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我是B服，且电脑是M1，导致我服务使用电脑模拟器连接MAA，因此我一直使用一部旧手机通过adb的方式连接MAA，之前一直用的4.13.0版本的MAA，可以正常连接，今天更新到新版的4.17.0后，MAA再也打不开手机上的方舟了，我单独用终端验证adb是可以连接上手机的

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11546392/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/42195439/22439125-7e02-430a-9d67-8cf16ad00ccf)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/42195439/77ed38c8-b025-4db1-a652-3dba0f765d4b)

### 还有别的吗？

系统：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/42195439/377ace45-5c33-47e2-96a7-9eb9329337da)

**Comment by Git-zhoujunjie** [comment]
重新替换为4.13.0版本的MAA后就能正常连接了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/42195439/8ebf07c3-d535-4ab0-b08d-08e755f33b6b)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11546481/asst.log)

**Comment by MistEO** [comment]
连上了啊，是任务出错了。试试其他任务能跑吗

cc @hguandl

**Comment by Git-zhoujunjie** [comment]
没有开启，以前是直接用MAA启动方舟的，升级后就启动不了了，还没试过其他任务，我晚上再试试看

**Comment by Git-zhoujunjie** [comment]
感谢，原来如此，没问题了，脑抽了没有细看
