### ISSUE TITLE
关卡选择手动输入关卡名时，第二天关卡名丢失

### ISSUE THREAD

**Issue by MuLInGRui** [MaaAssistantArknights/MaaAssistantArknights#4905]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

关卡选择设置为手动输入关卡名，首选为CA-5，备选为11-13-NORMAL和10-12-NORMAL，第一天会正常选择CA-5，但是第二天CA-5会消失（从输入框里消失），改刷11-13-NORMAL，昨天和今天CA-5都正常开放。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11549870/asst.log)

**Comment by MuLInGRui** [comment]
这两天都有更新，我也怀疑可能跟更新有关

**Comment by MuLInGRui** [comment]
这次是手动关闭MAA一段时间后再打开，关卡选择CA-5消失

**Comment by ABA2396** [comment]
试试这个版本https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/5065261690

**Comment by MuLInGRui** [comment]
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11552425/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11552429/asst.log)

**Comment by MuLInGRui** [comment]
今天上午关卡选择为CA-5，备选AP-5和11-13-NORMAL剩余理智10-12-NORMAL，上午时刷理智正常，结束时刷到了10-12-NORMAL（正常）；下午再开机自启时CA-5和AP-5都消失了
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11563750/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11563752/asst.bak.log)

**Comment by moomiji** [comment]
gui.log 也发一下吧（

**Comment by MuLInGRui** [comment]
[gui.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11573143/gui.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11573145/gui.log)
昨晚更新的内测版，目前今天未出现该情况
