### ISSUE TITLE
水月肉鸽卡在出发前往

### ISSUE THREAD

**Issue by 702165405** [MaaAssistantArknights/MaaAssistantArknights#4909]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

水月肉鸽自动进入、选人没有问题，但是在出发页面卡主了，分辨率是1920*1080。
而且除了水月肉鸽外，其他功能经常报错，ADB连接没有问题，主要是肉鸽进行不下去。

### 日志文件

asst.log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11551627/asst.log)

### 截图

![1671684912391_ pic](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129164549/44195025-cbf2-4078-b2c6-fa4bbe3fbd95)
![1681684912391_ pic](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129164549/71744864-3ea1-4d88-bda6-d9a51b5ac439)
![1691684912391_ pic](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129164549/f70ce325-1d00-4ec8-802f-1881b959d601)
![1701684912391_ pic](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129164549/aceab522-3e1a-4052-971b-c59e88ea73e2)

### 还有别的吗？

模拟器：蓝叠国际版5.11.100 
操作系统：win11
MAA：v4.18.0.1

**Comment by MistEO** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/430035a5-79d4-4c67-9d86-1096374d26d5)

把这玩意关了
