### ISSUE TITLE
每次开机后设置选项都会重置

### ISSUE THREAD

**Issue by helloIris415** [MaaAssistantArknights/MaaAssistantArknights#491]
每次重新开机后，基建的无人机用途选项跟自动公招的选项就会被重置为默认选项。【如：赤金》龙民币，确认5星》4星，公招次数4》3】希望能让系统能够持续记忆上次的选项

**Comment by MistEO** [comment]
每次都会重置的话，考虑是不是把 maa 放在了没有写权限的路径下？
