### ISSUE TITLE
火哨的基建技能视为+30%

### ISSUE THREAD

**Issue by ZauberViolino** [MaaAssistantArknights/MaaAssistantArknights#4913]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

火哨第二基建技能「代为说项」在贸易站满人且均在工作时效率为+30%，但是MAA不会优先选择，而会选择「供应管理」（效率+25%，上限+1）。

### 有什么好的想法？

希望火哨能在一定情况下被视作+30%的干员，优先放入贸易站。

### 其他内容

当然如果贸易站里的干员迅速红脸的话还是亏，但火哨还有全员心情消耗-0.1的技能，可能抵消一点点（）

**Comment by liuyifan-eric** [comment]
用自定义排班吧（
