### ISSUE TITLE
借助战赚信用借到天火导致卡住

### ISSUE THREAD

**Issue by satgo1546** [MaaAssistantArknights/MaaAssistantArknights#4917]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

OF-1自带天火和普罗旺斯，借到普罗旺斯大概也会导致此问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11560084/asst.log)

### 截图

![OF-1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/5250054/48744996-45c2-427d-9cca-bd1ae6ee3d41)

### 还有别的吗？

MAA版本4.18.1

**Comment by MistEO** [comment]
OF-1 这功能没人维护了，bug 也很多，我觉得后面要不把这功能删了吧（

**Comment by ABA2396** [comment]
其实只要加个点确认就好了吧）

**Comment by CCCClaus** [comment]
> 

不借狙击和术士就行了吧（）借人前在左边选一下

**Comment by Constrat** [comment]
Fixed with 6c1da94b3ce77f5decf3e8f5262da455985ddffc
