### ISSUE TITLE
在修复OF-1后仍会出现反复刷此关的情况.

### ISSUE THREAD

**Issue by WitherLing** [MaaAssistantArknights/MaaAssistantArknights#4918]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在修复重复刷OF-1后仍会出现反复刷此关的情况.

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11560343/asst.log)

### 截图

![A{@9FZ7OO 1Y(G3A4X7E(ZJ](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74227748/831227a2-48ca-46d5-b98e-4a3065cf125a)

**Comment by WitherLing** [comment]
补充:
log时间点约为8点开始.

**Comment by MistEO** [comment]
@ABA2396 OTA 那边没更新，本地的 task 被覆盖掉了（
