### ISSUE TITLE
基建卡会客室线索界面无法正常替换干员

### ISSUE THREAD

**Issue by Morocoshi-0817** [MaaAssistantArknights/MaaAssistantArknights#4919]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建换班功能在会客室的线索界面有时会卡住无法正确识别，导致无法正常替换干员，maa重试几次替换干员失败后就会直接跳过宿舍摆放的阶段完成基建换班任务。具体出现在送线索界面还是线索交流结束的结算界面并不清楚，日志内发生该问题的时间点在2023.05.25的05.10左右

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11560747/asst.log)

### 还有别的吗？

使用蓝叠国际版，Windows11系统，maa版本为4.16.4

**Comment by Winmer** [comment]
同样的问题 我重复试了几次并录了视频 卡住前最后一次操作是连点取消选中干员 之后便卡住无法选中或取消任何干员 显示的基建页面的干员也不会改变 怀疑是连点太快把app卡出了bug...
