### ISSUE TITLE
maa可否有一个不自动更新降级后的版本

### ISSUE THREAD

**Issue by ouddaierdaoge** [MaaAssistantArknights/MaaAssistantArknights#4920]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有时候maa可能会突然连不上模拟器什么的，又或者其他的什么问题。对于我这种没时间折腾收集日志的，降级是最快解决的办法。不过降级之前如果不设置关闭自动更新，降级之后会立刻自动更新

### 有什么好的想法？

记录一个版本号，如果用户降级了，低于了这个版本号，自动更新程序暂时不运行，不更新这个对于用户有问题的版本，直到下一个版本发布

**Comment by ABA2396** [comment]
关掉自动下载更新包不行吗

**Comment by liuyifan-eric** [comment]
> 关掉自动下载更新包不行吗

我觉得ta的意思可能是，下载旧版本后，一打开程序就会自动更新到最新版，没有机会去关闭自动更新？

我以前有这种问题，是通过断网启动再关闭自动更新解决的
