### ISSUE TITLE
适配外服肉歌(水月)

### ISSUE THREAD

**Issue by z31997684** [MaaAssistantArknights/MaaAssistantArknights#4924]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我是使用夜神模擬器，在國際服使用自動肉歌(水月)時，他會重複進入水月肉歌畫面，不按開始探索就跳回主畫面，重複無限循環，請問我改怎麼辦QQ

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11563009/asst.log)

**Comment by zxchinam** [comment]
日服蓝叠模拟器也是这样的

**Comment by MistEO** [comment]
还没做呢，欢迎帮忙适配，可以参考 [文档](https://maa.plus/docs/2.5-%E5%A4%96%E6%9C%8D%E9%80%82%E9%85%8D%E6%95%99%E7%A8%8B.html) 和 [韩服的 PR](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/4894)
