### ISSUE TITLE
建议maa干员识别界面增加“隐藏已无法获取的干员”选项

### ISSUE THREAD

**Issue by Ks-luow** [MaaAssistantArknights/MaaAssistantArknights#4925]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用这个功能主要是想看看距离全干员还有多久，如果能有个隐藏已无法获取的干员，看起来会清爽一点

### 有什么好的想法？

增加“隐藏已无法获取的干员”选项或者“隐藏联动干员”“隐藏限定干员”

**Comment by ntgmc** [comment]
个人认为该需求无用
