### ISSUE TITLE
建议自动战斗的作业里添加循环动作功能

### ISSUE THREAD

**Issue by Xinweigh** [MaaAssistantArknights/MaaAssistantArknights#4926]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

这次尖灭+1000%的大机甲如果不放生的话，几乎必须用打年糕的方式，就算使用决战技都要反复开。模拟器脚本也可以，但是由于时间很难设计精确，模拟器只是按照时间模拟点击，循环次数多了很容易乱轴。

### 有什么好的想法？

希望能在作业里面增加一个循环功能，打年糕时可以循环一个动作组合（比如“部署42，开钙质化，开狐火，开黄昏，撤退42”）直到打完，最好能允许指定循环次数。

**Comment by MistEO** [comment]
json 下载到本地，把这段复制粘贴一百遍（
