### ISSUE TITLE
不能更新

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#493]
软件版本是3.3.1，今天我看到有3.3.2版本了，就想着更新一下。我直接在GitHub上面下载了3.3.2的压缩包，把压缩包拖到软件根目录下面，却没有任何更新提示，没有在线下载更新也没有本地更新，数次重启软件也没有更新，软件内部显示版本依旧为3.3.1
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8684780/asst.log)

**Comment by xiaoweiXX** [comment]
之前我也遇到过一次不能自动更新，作者说是3.1.2的遗留问题。这次貌似更加恶劣一些，因为上次好歹还检测到了更新，给出了提示，这次连检测到更新的提示都没有，把新版拖到软件文件夹根目录下也没有自动本地更新。

**Comment by zzyyyl** [comment]
这个问题是由于你勾选了测试版本更新，正式版本就不会更新了，是bug，但还没修

**Comment by zzyyyl** [comment]
主动更新可以去掉测试版本更新的复选框试试

**Comment by xiaoweiXX** [comment]
> 主动更新可以去掉测试版本更新的复选框试试

取消勾选之后好像确实没问题了，但这依旧是个bug，我就不close了。我看根目录下面好像有一些缓存文件，比如MeoAssistantArknights_v3.3.2.zip.temp之类的，老哥知道哪些可以清理吗？

**Comment by zzyyyl** [comment]
一般只要是你第一次下载的时候没有的都能删除。比如`*.temp`，`*.old`之类的。
