### ISSUE TITLE
干员识别有误

### ISSUE THREAD

**Issue by tiyamikatto** [MaaAssistantArknights/MaaAssistantArknights#4933]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

存在大量的干员未能识别出的问题，比如已经拥有了澄闪，假日威龙陈等，包括红云红豆杜林等干员也未能识别（非全部，我只能讲出一些我注意到我确实拥有的干员）。
同时注意到在“debug/oper”文件中，保留的截图只有干员列表最后一页的截图。
（由于上传文件大小限制，我无法上传全部的该文件中的截图，只保留了那些今日的截图）

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11567436/debug.zip)

### 截图

![VUW82NQ4$MXCGFDGBWZ4~~Q](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104922165/3af445bd-e6b2-4e8e-90ef-2632d2324e61)
![O% GI9N0WXR{YYCQ2Q9_D7](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104922165/f05e0344-649a-4a2f-a8d2-0a36cd9a4dee)

### 还有别的吗？

模拟器：夜神模拟器 7.0.5.0
操作系统：Windows 10 家庭版
触控模式：Minitouch

**Comment by MistEO** [comment]
试试最新的内测版有用吗

**Comment by tiyamikatto** [comment]
在今天更新的内测版（v4.18.2-alpha.1.d044.g40cd147b）中，该问题依旧存在。澄闪，水陈，杜林等人均未能识别（60到59的原因是识别了昨天刚刚抽到的小僧）。同时oper文件夹中并没有这次识别时的截图文件。
![`R~UG1B75@M)HHZXOH60L)6](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104922165/a2160d1f-2390-40c7-b70b-bc469a111cd0)
![ACEVY9_4}JWZ(4FBWG~ E$P](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104922165/81f954fc-0bfe-4d6e-a209-c3bca8cec8af)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11571421/asst.log)

**Comment by MistEO** [comment]
修了一下，再试试最新的内测版有没有用 d062

**Comment by tiyamikatto** [comment]
抱歉回复晚了，在今晚自动更新的内测版（v4.1 8.2-alpha.1.d054.gbe8a6dad）后，问题得到解决。
也对刚刚更新的版本（v4.1 8.2-alpha.1.d062.gc37e2cc0）试了下，也没有产生问题。
感谢！
