### ISSUE TITLE
YostarEN - IS3 Stuck Encounters 

### ISSUE THREAD

**Issue by GL1TCH3D** [MaaAssistantArknights/MaaAssistantArknights#4935]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

I hope this is okay. I've been using the most up to date build with the nightly update on.
I'm very happy to see the IS3 is working for the most part, I just wanted to report specific encounters that freeze the MAA system.
In particular that I've seen: Encounter Devouring Dust, Encounter Wish Fulfilled (boon)

 I've provided the screenshots

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11567785/asst.log)

### Screenshots

![stuck screen](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16604425/a2ae416f-e8f8-4463-8151-0585e1fa2b30)
![Stuck screen](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16604425/84e333c3-dae2-4587-af93-4011748b27fe)

### Anthing else?

Using bluestacks 5.11 with Android 11

**Comment by GL1TCH3D** [comment]
![stuck decision](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16604425/c156a479-203f-48df-a6ea-7104f1509e12)
It also seems that when MAA faces a decision voucher, it gets stuck on this screen until it times out and resets the run.

**Comment by GL1TCH3D** [comment]
![Stuck screen3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16604425/57c55ecc-be03-47ff-830b-3affaccf4a7b)
This one seemed to get stuck too. So far these are the only ones I've encountered while watching the MAA

**Comment by etasbyjh** [comment]
I am also having the same issue with the first one. It doesn't do anything for the selection screen with "Hurry up and put on protective clothing" text

**Comment by liuyifan-eric** [comment]
I guess this is again (as in Phantom IS) caused by the text being too long.

**Comment by Pitiedwzr** [comment]
> ![stuck decision](https://user-images.githubusercontent.com/16604425/241003417-c156a479-203f-48df-a6ea-7104f1509e12.PNG) It also seems that when MAA faces a decision voucher, it gets stuck on this screen until it times out and resets the run.

For the recruit, please make sure you use the latest task.json, because YoStarEN use different templates for decision(Recruit) and other(Recruitment).

**Comment by cookie223** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/template/Mizuki%40Roguelike%40StageEncounterOptionUnknown.png

Probably because when text is too long MAA can't find this part. I wonder if change it to something all the way to the right would help
