### ISSUE TITLE
一键长草页面拖动左侧任务顺序后，无法保存修改后的顺序

### ISSUE THREAD

**Issue by KaronGH** [MaaAssistantArknights/MaaAssistantArknights#4937]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

一键长草页面拖动左侧任务顺序后，无法保存修改后的顺序。排查流程如下：
1. 检查gui.log未发现异常
2. 检查gui.json后，发现任务顺序的修改未能保存到gui.json
3. 手动修改gui.json中任务顺序相关的键值以调整顺序，重启后可以反映到界面中
4. 降级MAA，发现自v4.16.4版本便已经出现此问题（再往前的版本未测试）

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11570381/gui.log)

### 截图

![手动拖动修改测试](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/23610722/132ba9f5-31cd-4c9b-b147-873e6f812530)

![重启后恢复为默认顺序](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/23610722/9657a658-b88d-44b0-94b6-00bb599ddfa8)

### 还有别的吗？

MaaAssistantArknights/src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
里面的TaskItemSelectionChanged()应该是用来保存任务顺序的
原本设计的是实时保存，但没有查到相应的调用，仅在LinkStart()时调用一次，造成无法实时保存。可能是忘记加调用了？
测试点击GUI中的“Link Start”是可以触发保存的，说明应该是成功调用了

不懂CSharp，只能看到这里了

**Comment by MistEO** [comment]
那个 changed 好像一秒会进来几百次。可能是 by design @ABA2396

**Comment by bepluvia** [comment]
最近打开MAA总提示”资源损坏，请重新下载安装包“，然后点确定会自动关闭，但是再次打开是可以正常运行的，不知道是不是软件的问题。
