### ISSUE TITLE
首次进入肉鸽在难度选择页面无限循环

### ISSUE THREAD

**Issue by ZauberViolino** [MaaAssistantArknights/MaaAssistantArknights#4939]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天想看看maa怎么打水月肉鸽的，学习一个！我点进肉鸽界面发现没有熟悉的「波涛迭起」难度选择。

然后让maa运行打肉鸽，发现点击「开始探索」后会进入难度选择界面。推测一个帐号在新设备上首次进入水月肉鸽会强制先选择难度。maa点进去之后就退出，然后再点进去再退出，以此循环。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11573167/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/67864718/5774996a-77d1-421d-8862-3bdf1b2828b3)

### 还有别的吗？

其实可以不用修的（）可以在设置界面提醒一下先手动进入肉鸽，把难度设置好

**Comment by ZauberViolino** [comment]
手动操作，选择完难度之后会重返水月肉鸽首页。

**Comment by RyanWangxr** [comment]
我跟你这个情况一样，我是国际服，就首页和水月肉鸽来回切

**Comment by ABA2396** [comment]
> 我跟你这个情况一样，我是国际服，就首页和水月肉鸽来回切

国际服和这个不是一个问题
