### ISSUE TITLE
增加更新选项

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#494]
希望能增加一个更新选项，只提醒不下载更新。软件内的自动下载貌似不太稳定，所以我更倾向于在GitHub上面手动下载更新再拖到文件夹里面本地更新。然而每次检测到又不得不下载更新，貌似会产生一部分缓存文件，我又不知道哪些能够删除哪些不能；取消勾选自动下载我不知道能不能收到更新提示，如果能我希望作者能够改一改描述（比如“只提醒不下载”之类的）

**Comment by MistEO** [comment]
取消勾选 自动下载更新 即可

**Comment by xiaoweiXX** [comment]
> 取消勾选 自动下载更新 即可

那能否更改一下描述？

**Comment by zzyyyl** [comment]
取消了`自动下载更新`就是「只提醒不下载更新」。MAA没有不提醒更新的功能，除非网络太差（

**Comment by xiaoweiXX** [comment]
> 取消了`自动下载更新`就是「只提醒不下载更新」。我觉得没有必要更改描述。 MAA没有不提醒更新的功能，除非网络太差（

你看我，就不知道（
最好还是改改。
