### ISSUE TITLE
JP服水月肉鸽一个奇遇会无法选择选项

### ISSUE THREAD

**Issue by QCCJ** [MaaAssistantArknights/MaaAssistantArknights#4946]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

会反复的在三个选项中来回选，但是就是选出出来

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11580693/asst.log)

### 截图

![Screenshot_2023 05 27_09 35 33 670](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104538447/60082e56-5abc-44ce-aec1-4aa21573dae8)

**Comment by HUAZIB** [comment]
所有奇遇都是一样的，无法进行选择

**日志文件**
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11582464/asst.log)

**Comment by liuyifan-eric** [comment]
修过了，新版beta2的再测测看？

**Comment by HUAZIB** [comment]
还是不行

**Comment by liuyifan-eric** [comment]
> [log.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11599577/log.txt)
> 
> 多个选项来回横跳
> 
> 单个选项卡住不动

发完整的asst.log

**Comment by HUAZIB** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11601092/asst.log)
重置log开了一把  骑士3选1卡住

**Comment by HUAZIB** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11601214/asst.log)
更新一个获得3护盾单选项的奇遇
