### ISSUE TITLE
增加清理缓存功能

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#495]
希望作者能够增加一下缓存清理功能，我看每次更新都会产生一些诸如“MeoAssistantArknights_v3.3.2.zip.temp”之类的缓存文件，还有一些像“MeoAsstGui.exe.old”之类的文件。我不知道这些文件能不能删除或者清理，因此希望作者能够增加一个清理缓存的功能，或者告诉我们哪些能够清理哪些不能。

**Comment by ABA2396** [comment]
.temp是下载的缓存，.old是更新完之后的旧文件备份，如果更新完了就可以直接删了

**Comment by MistEO** [comment]
fixed
