### ISSUE TITLE
Maa does not use expedited plans after detecting a Robot tag

### ISSUE THREAD

**Issue by 178619** [MaaAssistantArknights/MaaAssistantArknights#4950]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Maa stops using expedited plans despite the option is turned on, after it detects a Robot tag. 

### Log files

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11581115/asst.zip)

### Screenshots

![Screenshot_2023 05 27_15 07 12 617](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61264540/9d8189f8-bd49-42dd-bbf2-91b9f917306a)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61264540/d14e45e5-3ef0-4485-9c62-d6932d291538)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61264540/187bcf55-586c-4ad5-b5e1-1082d6fe47ee)

**Comment by 178619** [comment]
It seems it continues to use expedited plans when the other slots were occupied. However, when the slots are empty, Maa only uses recruit recruitment permits then stop working without using expedited plans.

**Comment by MistEO** [comment]
Does maa click the top left slot again and again and cancel?

@horror-proton please help to check.

**Comment by 178619** [comment]
It doesn't click it, it just does not use the plans on other slots.

Before starting the task, there were 4 completed recruitments. Maa successfully recruited them all so they became all empty. Then It started to repeat recruiting on the 1st slot. It eventually got a robot tag, so it stopped using the slot and sent a notification.

However Maa did not use the plans after filling out the other empty slots. It just told me the task ended.

Then when I restarted the task, it restarted using the plans and recruiting. But this time the slots were not empty (except for the first one which was ignored at the beginning) and it did use the plans even after moving to other slots.

**Comment by 178619** [comment]
#4982

**Comment by Toby-Shi-cloud** [comment]
#7263 
it seems that MAA only uses expedited plans in the top left slot...
