### ISSUE TITLE
肉鸽第一关费用完全溢出情况下漏怪（AU+A卡）

### ISSUE THREAD

**Issue by BIGCATORCA** [MaaAssistantArknights/MaaAssistantArknights#4952]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最近回坑粥，发现诸位大佬搞的MAA，经过学习准备用来挂一挂肉鸽，然后发现无论如何，在肉鸽第一关都会出现费用溢出但是不下干员，漏第一只怪之后才下干员的情况。经过各种搜索自查都没有发现问题根源，在QQ群跟群友交流之后群里大佬说AU+A卡的组合会出现这种情况，只是现在样本不是很多，所以过来把自己遇到的情况分享一下。个人能力有限，代码只能看懂一点点，所以只能靠这种给大家添麻烦的方式给MAA添砖加瓦了，希望MAA越来越好。

### 日志文件

传文件一直报错，一群的管理员大佬也说这个情况的样本你们有一些，我这边先不传了，如果需要的话我可以从QQ那边传

### 还有别的吗？

模拟器：蓝叠、夜神、mumu12均有此情况
操作系统：win10专业版
CPU:AMD Ryzen 5 3600 6-Core Processor 3.60 GHz
显卡：RX 590

**Comment by ABA2396** [comment]
日志文件可以打成压缩包之后传上来

**Comment by RiichiTsumo** [comment]
看看是这样的吗
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/4938

**Comment by MistEO** [comment]
74055b2f4bf0eb2924e45df8f916621f6846815c 修了，试试内测版
