### ISSUE TITLE
JP服，傀影肉鸽在奇遇卡主不选择

### ISSUE THREAD

**Issue by QCCJ** [MaaAssistantArknights/MaaAssistantArknights#4954]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

傀影肉鸽在一个奇遇事件会卡住，无法选择

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11582372/asst.zip)

### 截图

![N`JWY D%F)}ZN(V90WT~7GY](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104538447/c12df967-d89a-4b81-b127-789f4c6c5a60)

**Comment by xvzhenduo** [comment]
美服也这样,每次都直接跳过，貌似是干员识别没有适配
