### ISSUE TITLE
内置保全作业  约翰老妈在建地块  最后一关不识别

### ISSUE THREAD

**Issue by 466895132** [MaaAssistantArknights/MaaAssistantArknights#4955]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗  保全作战  约翰老妈在建地块  最后一关无法识别   日志末尾就是

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11582730/asst.log)

### 截图

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/11262966/47ef5952-444b-48dc-8989-b78d7a237b43)

**Comment by ABA2396** [comment]
这个作业最后一关没写

**Comment by MistEO** [comment]
看日志你切过几次日服的资源，现在会有问题。选国服然后重启下 MAA 就行，之后版本会修一下
