### ISSUE TITLE
希望可以定义信用商店接助战功能,使用哪个编队

### ISSUE THREAD

**Issue by hifuclub** [MaaAssistantArknights/MaaAssistantArknights#4957]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

开启信用商店借助战后会把当前的队伍改成只有嵯峨的队伍后进图, 会把我用来标记等待升级的队伍和刷信用的队伍都变成只有嵯峨一个人的队伍

### 有什么好的想法？

希望可以定义借助战使用队伍几

**Comment by pighungter** [comment]
对，我也是把几个要升级的人编在队伍三，每天看一眼确定要刷的图。结果每次会被借助战清空，希望固定选择编队一，这样不用每次都让我重新挑选要升级的干员
