### ISSUE TITLE
斥罪干员在maa日常显示干员冲突

### ISSUE THREAD

**Issue by livzsoo** [MaaAssistantArknights/MaaAssistantArknights#4959]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

斥罪干员从办公室放入宿舍会在maa显示干员冲突。该操作的目的是把斥罪和菲亚梅塔互换心情，由此达成斥罪24h不间断在办公室上班。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11583419/asst.log)
我的设置是优先处理基建排班，办公室换班放在第一个。

### 截图

![Snipaste_2023-05-28_09-44-07](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/128603350/27621b50-148d-4caf-926f-f2f0e8a4346f)

### 还有别的吗？

模拟器：蓝叠国际版5.9.300.1018 N32  操作系统：win10 相关配置：i5 960m

**Comment by ABA2396** [comment]
在别的地方工作就会显示这个，不用管
