### ISSUE TITLE
能否在使用加急许可和吃理智药添加可选的重启后保存和不保存选项

### ISSUE THREAD

**Issue by livzsoo** [MaaAssistantArknights/MaaAssistantArknights#4960]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

吃理智药：这个选项更偏向需要重启后不保存，因为经常会在第二天忘记取消选项而使用过多的理智药。
使用加急许可：这个选项因为加急许可比较多，所以可以选择重启后保存。

### 有什么好的想法？

对于上述的两个功能能否实现像下图那样有两种选项：重启后保存、重启后不保存。

### 其他内容

![Snipaste_2023-05-28_09-56-45](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/128603350/27eedeb7-5a49-4103-9997-e6ece64a8c31)

**Comment by ABA2396** [comment]
加急许可不打算做了，毕竟是可以一次性全招完的，而且每天就算运行两次公招券的获取速度都是赶不上消耗的
