### ISSUE TITLE
基建贸易站出现不合理排班

### ISSUE THREAD

**Issue by Viottery** [MaaAssistantArknights/MaaAssistantArknights#4961]
### 说说你遇到的问题？

今天上线发现在精一的卡夫卡与龙舌兰均满心情的情况下，精二巫恋组使用了巫恋+尤里卡+玫兰沙的组合，个人理解技能矛盾收益不高。建议检查。

![G%KH1UCV7)MIQ7WWW1EVAZ1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52962187/15c83d40-481c-489b-8393-07a574c1d678)

**Comment by Shawnsdaddy** [comment]
可能是选错人了吧？我猜，，就一张截图也没法调查
