### ISSUE TITLE
刷肉鸽时干员技能充能完毕时头顶的黄色菱形标志如被其他UI挡住似乎就不会被识别到

### ISSUE THREAD

**Issue by minecraftfen** [MaaAssistantArknights/MaaAssistantArknights#4962]
水月肉鸽，第二层“海神的信者”关卡中，MAA把凯尔希放在了从左往右第五格，从上往下第一列，她头顶的黄色菱形标志被显示歼灭数和目标生命的UI挡住了，MAA部署凯尔希后就再也没点开过，即便是带了有群攻的2技能且M3挡住一堆小怪的情况下也没开技能。
以下是PRTS.wiki中的关卡图片
![海神的信者](https://prts.wiki/images/3/3a/ISW-NO_%E6%B5%B7%E7%A5%9E%E7%9A%84%E4%BF%A1%E8%80%85_%E5%9C%B0%E5%9B%BE.png)

**Comment by minecraftfen** [comment]
又遇到了，这次更明显，我截图下来了，德狗技能转完半天了都不开，至少回个费啊
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/42016099/8de48640-4480-4c96-ab98-24c5bbbf8b81)

**Comment by SherkeyXD** [comment]
训练集中被ui遮挡的图标数量不够多，所以没法正常识别
这是一个长期性的工作，短期内可能无法修复

**Comment by Clazex** [comment]
可以确认寒克部署在“互助”中上方高台时也有相同情况

目前可否通过避免将干员部署在靠近屏幕顶部中间的格子来规避这个问题？
