### ISSUE TITLE
希望肉鸽出一个半自动模式或者监督模式 招募干员时候的问题

### ISSUE THREAD

**Issue by kcsocrat** [MaaAssistantArknights/MaaAssistantArknights#4965]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

1.模式建议：
希望设置一个半自动模式或者监督模式：我的意思就是有时候他摆阵的时候瞎摆，想自己摆的时候他自己又捣乱摆不好，希望让它识别到我正在操作的时候不要来操作
2.招募干员的问题：
建议不要招募2星干员以上的非精一满级以上的干员，临时招募如果要选择三星干员(同满级的情况)优先选择自己的三星干员。
3.开局招募好友助战的时候：
我觉得可以随机招募招募哪个都可以，我也不需要特定的什么干员

### 有什么好的想法？

1.比如选定干员的时候的界面或者我觉的可以设置一倍速的时候说明我再操作，二倍速的时候说明让它可以操作。
2.建议不要招募2星干员以上的非精一满级以上的干员，临时招募如果要选择三星干员(同满级的情况)优先选择自己的三星干员。
3.我个人比较喜欢用随心所欲的阵容打法，所以我很喜欢随机的可能性，举个例子（在开局三个招募卡中随机挑取一个招募卡使用好友助战，然后随机招募好友助战的干员）。

**Comment by MistEO** [comment]
直接停掉，下一个节点再开就行了

**Comment by kcsocrat** [comment]
> 直接停掉，下一个节点再开就行了

好的也行
