### ISSUE TITLE
开局下干员反应很慢

### ISSUE THREAD

**Issue by kcsocrat** [MaaAssistantArknights/MaaAssistantArknights#4966]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有时经常开局先漏几个怪才放干员，反应很慢（明明费用早就满了），这点希望尽快修复

**Comment by SherkeyXD** [comment]
有日志吗

**Comment by ABA2396** [comment]
> Duplicate of #4952 fixed in [74055b2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/74055b2f4bf0eb2924e45df8f916621f6846815c) 如果急的话可以试试内测版，不急的话等待v4.19正式版更新

公测版已经更新了

**Comment by kcsocrat** [comment]
> > Duplicate of #4952 fixed in [74055b2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/74055b2f4bf0eb2924e45df8f916621f6846815c) 如果急的话可以试试内测版，不急的话等待v4.19正式版更新
> 
> 公测版已经更新了

谢谢大佬们，问题解决了，刚看到

**Comment by kcsocrat** [comment]
> Duplicate of #4952 fixed in [74055b2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/74055b2f4bf0eb2924e45df8f916621f6846815c) 如果急的话可以试试内测版，不急的话等待v4.19正式版更新

谢谢大佬们，问题解决了，刚看到
