### ISSUE TITLE
日服自動肉鴿功能無法開始探索

### ISSUE THREAD

**Issue by ocars665** [MaaAssistantArknights/MaaAssistantArknights#4968]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在開始MAA自動肉鴿功能後無法開始探索, 已選擇伺服、主題、難度
已嘗試過切換觸控模式、強制替換ADB

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11584078/asst.log)
 5月27-28日

### 截图

![MAA_1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92812729/63f09f27-94cb-444e-8015-2171e6e1f53a)

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92812729/dc2d6b3a-7c35-46dd-b978-70ec40a9dc6b

### 还有别的吗？

使用Bluestack 5 P64版本, windows 10 64位元

**Comment by 178619** [comment]
This happened because v4.18.1 does not support Mizuki theme. It's already done, Please wait for the next update or download the beta version.
发生这种情况是因为v4.18.1不支持Mizuki主题。已经完成了，请等待下一次更新或下载测试版本。
