### ISSUE TITLE
请问是否支持从环境变量识别adb？

### ISSUE THREAD

**Issue by pboymt** [MaaAssistantArknights/MaaAssistantArknights#497]
RT，还没开始用，我看说明里提到蓝叠HyperV模拟器需要解压adb到程序目录。

不过我PC上有`ANDROID_HOME`这种环境变量，里面就是platform-tools目录和adb的执行文件，是装Android Studio时生成的标准目录，助手能识别码？

**Comment by MistEO** [comment]
> 环境变量中已有 adb, 可以不再下载一份么？
> 可以！请手动修改 resource\config.json - Custom - adb - path 为 adb.exe, 或其他 adb 的路径
