### ISSUE TITLE
4.18.1版本OF1打完就退出，然后我需要这个做每周任务，因而需要一个无奖励掉落但持续刷的开关。

### ISSUE THREAD

**Issue by ZzzHe2333** [MaaAssistantArknights/MaaAssistantArknights#4970]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

4.18.1版本**只要一打OF1打完就退出**，然后我需要这个做**每周任务、模组任务**。
这出发点是好的，但是我需求反复打OF1，刷杀怪/关卡，以前打得好好的，现在一改，刷模组任务/每周任务都受到影响了，虽然更新这个本意是好的，但是确实影响到我了。
举个例子吧，以前我只需要打一个，然后OF关挂机刷模组/每周任务就行了，现在我需要刷那个“合约”，要么就消耗理智，不如OF-1打得快速还好挂机.....
哭了，还我OF-1。或者改个开关吧！满足一下我们的需求。

### 有什么好的想法？
我需要一个开关，用于无奖励掉落情况下是否自动断掉的开关，或者判断无奖励的次数达到多少次才断掉。
判定：是否无奖励
-----如果无奖励，则判断是否开关
---------如果开了，则继续刷。
---------如果没开，则断掉并提示。
----如果有奖励
..........

_No response_

### 其他内容
改回去吧，我的MAA
_No response_

**Comment by ZzzHe2333** [comment]
需求是加一个无奖励的挂机开关，默认是无奖励断掉。

**Comment by status102** [comment]
如果需要做每周任务，可以考虑使用自动战斗执行一个没有步骤的作业
