### ISSUE TITLE
[Bug] Stop at a specific event

### ISSUE THREAD

**Issue by ABA2396** [MaaAssistantArknights/MaaAssistantArknights#4973]
### Discussed in https://github.com/orgs/MaaAssistantArknights/discussions/4969

<div type='discussions-op-text'>

<sup>Originally posted by **rosmontisu** May 28, 2023</sup>
### My environment
Korean client
Windows 11 Pro    

### Bug Description
Phantom & Crimson Solitaire   
When i encounter the event(attached screenshot) mma stops.    
If I manually hand over the event, it will proceed normally again.    

### Log files
[logs.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11584848/logs.zip)

### Screenshots
![StoppedImage1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/107000683/541ef4a3-89de-4c68-bfcb-7cfac5c785f3)
![StoppedImage2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/107000683/b3cfbead-eb4f-4cdc-b847-8195758343db)
</div>

**Comment by 178619** [comment]
It is very likely that it happens because of getting low score with `Phantom@Roguelike@StageEncounterOptionUnknown.png`

**Comment by MistEO** [comment]
Chinese is very short, so we can use ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/d9a8b11d-273f-49de-82b3-73911452d124) and it works fine. 

However, most of the other languages are relatively long, and there may not be such a large blank in the options (sometimes the entire line is full of words), we may need to think of another way for the overseas clients.
