### ISSUE TITLE
建议增加功能：活动结束后关卡选择默认选项自动恢复为当前/上次

### ISSUE THREAD

**Issue by rat233** [MaaAssistantArknights/MaaAssistantArknights#4974]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

今天启动MAA后发现连接正常，但是在游戏内终端页面卡住，大概十几秒后提示任务出错：fight，开始以为是adb连接的问题，后来查看日志后才发现是上次默认刷了活动关，现在活动关关闭后，程序无法进入活动关导致了出错。虽然说手动修改为刷上一次很方便，但是不注意的话确实可能无法一下子发现原因。希望开发者未来能添加 活动结束后关卡选择自动恢复为当前/上次 的功能。

**Comment by ABA2396** [comment]
如果你开了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/8be8e85a-5554-4045-bafb-ce3ccc133a2a)
在活动结束后会自动变成 当前/上次
如果你开了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7b991283-6ee5-4a4c-a35a-1f833e216a2c)
活动结束后会自动寻找下一个开放的关卡，并在下方提示活动已关闭，且在下一次启动的时候会重新变成 当前/上次
如果都没选，那日期更新后不会更新关卡列表，之后在下次启动后才会重置为 当前/上次

**Comment by rat233** [comment]
> 

第一个我看了是默认开启状态，没变。
