### ISSUE TITLE
第二次linkstart时开始任务环节中断，步骤卡在startup，游戏卡在CG更换处

### ISSUE THREAD

**Issue by MuLingMing** [MaaAssistantArknights/MaaAssistantArknights#4976]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启动后在开始任务环节中断，无法继续。在下午时出现了该情况，尝试“停止、Link Start”三次，均发生了该情况，重启MAA后正常执行；期间MAA未关闭，晚上时又发生了该情况，同样“停止、Link Start”均会这样，重启才能解决。
<img width="521" alt="联想截图_20230528180833" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114294439/1a88244f-1fd0-4c02-a7ea-42c6e964208f">
<img width="538" alt="联想截图_20230528223457" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114294439/b13ae582-fc1b-4edb-a23d-389dc137d187">

### 日志文件

下午6点，晚上10点半
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11584865/asst.bak.log)
[gui.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11584868/gui.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11584869/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11584872/asst.log)

### 截图

<img width="521" alt="联想截图_20230528180833" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114294439/a26d9f97-c5b3-466c-a108-39de8d98fcc2">
<img width="538" alt="联想截图_20230528223457" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114294439/4e97e44a-4e39-4450-8aab-eeb29ce97bfd">

**Comment by MuLInGRui** [comment]
第一次时，我拖拽过模拟器（可能与之有关）；第二次时我选择了”最小化启动模拟器“选项

**Comment by MistEO** [comment]
adb 有替换过吗？

**Comment by MuLInGRui** [comment]
adb选择的是：自动检测连接、每次重新检测、adb重连失败自动重启、掉线重连
<img width="274" alt="联想截图_20230528235118" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114294439/cf2a4370-7413-4e5b-bd9a-df0363214d41">

**Comment by SherkeyXD** [comment]
蓝叠是 Hyper-V 版本吗？

**Comment by MuLInGRui** [comment]
> 蓝叠是 Hyper-V 版本吗？

蓝叠5国际版
<img width="215" alt="联想截图_20230529115800" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114294439/c65aa2c2-cc7b-460b-bb3d-8c24f3ea3032">

**Comment by Rengexx** [comment]
我也遇到这个问题好久了，maa任务执行完过后再点link start就会卡在那里动不了，我maa设置定时执行，就会卡在start up任务上

**Comment by Rengexx** [comment]
> 我也遇到这个问题好久了，maa任务执行完过后再点link start就会卡在那里动不了，我maa设置定时执行，就会卡在start up任务上

不光是启动时会卡住，执行完任务后再点执行的话什么任务都会卡住，只能重启maa解决

**Comment by vonnoq** [comment]
取消自動檢測連接，然後連接地址手動選擇127.0.0.1:5555試試？

**Comment by MuLInGRui** [comment]
目前仅当天出现了问题，这两天该情况未复现，我也不知道触发条件

**Comment by MuLInGRui** [comment]
今天下午该情况再次发生，尝试“设置-连接设置-强制替换ADB”也无效
MAA版本：
<img width="67" alt="联想截图_20230530184359" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114294439/5e777421-77e8-45e5-9ec7-6fcf2bcced29">
蓝叠5版本：
<img width="113" alt="联想截图_20230530184617" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114294439/8c4aa711-7ae4-4bfa-b06c-96258bc7aa82">

**Comment by MuLInGRui** [comment]
今晚又出现了该情况，我这次尝试自己点击游戏进行登录唤醒，然后发现MAA在我进到主页一段时间后显示完成唤醒任务，但是接下来下一个公招的任务又会卡住，我怀疑可能是触控（？）ADB（？）之类的连接方面出了问题，即模拟器关闭之后MAA不能更换ABD之类的连接（？）
22：30的MAA启动
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11615448/asst.log)

**Comment by MuLInGRui** [comment]
我取消了自动检测连接之后，手动修改了连接地址，之后再勾选自动检测连接，这样之后连接地址就是127.0.0.1:5555然后问题解决，可能是内在的ADB连接出了问题

**Comment by MuLInGRui** [comment]
手动修改连接地址为127后，勾选自动检测连接，第二天连接地址还是会变成emulator-5554，然后就报错
MAA 遇到了问题
集合已修改；可能无法执行枚举操作。
解决方案
出现未知错误
详细信息
System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   在 Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   在 Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   在 MaaWpfGui.Helper.ConfigurationHelper.Save()
   在 MaaWpfGui.Helper.ConfigurationHelper.SetValue(String key, String value)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.set_ConnectConfig(String value)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.DetectAdbConfig(String& error)
   在 MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<LinkStart>d__77.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
