### ISSUE TITLE
Mizuki Roguelike: The bot can't choose between two recruit permits

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#4978]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

I've been using the 19.0 beta1 and beta2. When you finish the stage and the game gives you the option to choose between two recruits the bot holds gets stuck, doesn't choose any of them and drops the run, just to run again.

### Log files

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11585495/asst.zip)
16:06:29, 16:22:44, 16:53:43, 17:09:20, 19:37:14, 20:11:29, 20:27:57, 20:38:22, 20:52:24, 21:06:54. Here are the timestamps of the images in the `debug` `roguelike` folder.

### Screenshots

![2023-05-28_16-06-29-332_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/755b620c-4c48-4433-a52a-796f833535bd)
16:06:29
![2023-05-28_21-06-54-263_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/2e7c0cc0-2a79-4593-a370-32f60e7bf7a3)
21:06:54
![2023-05-28_16-22-44-259_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/49de1992-5357-4c26-8996-41be864a208a)
16:22:44

Here are two examples of where it gets stuck. I have at least 10 other debug screenshots (that happened between this two) that MAA created automatically in the `debug` folder.

### Anthing else?

Another thing that I'm noticing is: in a lot of these screens you can notice that at the 3rd floor of the run I still have the default comp composed of the first 3 recruitments. Sometimes if lucky it will E2 my Gavial Alter (which is the only >3* operator, so the only upgradable one) I'm guessing that it skips every other recruitment option.

**Comment by 178619** [comment]
> [2023-05-28 21:02:34.832][TRC][Px2324][Tx222c] match_templ | Mizuki@Roguelike@GetDropRecruit.png score: 0.7479 rect: [ 75, 505, 168, 40 ] roi: [ 0, 471, 1280, 157 ]

>[2023-05-28 21:06:53.363][TRC][Px2324][Tx222c] match_templ | Mizuki@Roguelike@GetDropSelectRecruit.png score: 0.812 rect: [ 720, 488, 168, 40 ] roi: [ 0, 420, 1280, 175 ]

Setting `templThreshold` probably will fix it.

**Comment by Constrat** [comment]
I dug a little deeper: the `Mizuki@Roguelike@GetDropRecruit.png` is wrong.
![Mizuki@Roguelike@GetDropRecruit](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/658b2f1a-c876-4ca6-9963-9d687c0a7f25)
As you can see it says `Recruitment`, but the screens I provided clearly show `Recruit`

**Comment by Constrat** [comment]
Nevermind... It seems there's a bit of a problem. When no choice is given, the text says `Recruitment` (the bot still skips this).  When multiple choices are given it's `Recruit`. In this last case, the bot drops the run.

**Comment by MistEO** [comment]
For the CN client, these two buttons have the same word, both are "招募", so there is only one picture of "招募" in the resource folder of CN.

We can solve this problem by adding the following to YostarEN's tasks.json (and add this picture to template):

```json
    "Mizuki@Roguelike@GetDropSelectRecruit": {
        "template": "Mizuki@Roguelike@GetDropSelectRecruit.png"
    },
```

**Comment by MistEO** [comment]
Oh, looks like it was there before, just a threshold error...

**Comment by Constrat** [comment]
Closed with Update tasks.json (EN, #4978) #4985
