### ISSUE TITLE
[编译问题][文件缺失] 在Windows+VS下编译时报出了如下的错误

### ISSUE THREAD

**Issue by sasaliuxingyu** [MaaAssistantArknights/MaaAssistantArknights#4979]
### 说说你遇到的问题？

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'D:\code\MaaAssistantArknights\src\SyncRes\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	SyncRes	C:\Program Files\dotnet\sdk\7.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	266

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'D:\code\MaaAssistantArknights\src\MaaWpfGui\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	MaaWpfGui	C:\Program Files\dotnet\sdk\7.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	266

希望有人能帮助解决，谢谢

**Comment by SherkeyXD** [comment]
> 'D:\code\MaaAssistantArknights\src\SyncRes\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. 

跑一下 `dotnet restore` 试试
