### ISSUE TITLE
刷理智SN10,导航会卡在活动主入口

### ISSUE THREAD

**Issue by zhazha405** [MaaAssistantArknights/MaaAssistantArknights#498]
模拟器：BlueStacks 5 Nougat 64 位 (Hyper-V)
情况如题
![)@RS31W_P3$) LU2~(P K`9](https://user-images.githubusercontent.com/13600095/168280625-b89d12bb-d750-45e1-b50e-da49f303dfb0.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8686904/asst.log)

**Comment by MistEO** [comment]
新版本修了，还没上线~
