### ISSUE TITLE
公招识别自动使用加急许可会被支援机械词条冲突掉

### ISSUE THREAD

**Issue by sunshinemo** [MaaAssistantArknights/MaaAssistantArknights#4982]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我设置了20次公招，自动使用加急许可，然后在第一个公招栏出了支援机械的词条，然后maa就像正常公招一样把剩下三个公招栏招募玩就结束了，没有自动使用加急许可，也没有完成20次公招。只公招了3次。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11588031/asst.log)
大致时间在2023年11点29分

### 截图

无

### 还有别的吗？

夜神模拟器，win10,MAA-v4.19.0-beta.2-尖灭测试作战-夜神模拟器(127.0.0.1：62001)-官服-Default

**Comment by Toby-Shi-cloud** [comment]
估计是 #7266 的原因（使用加急许可选项仅会尝试对第一格进行加急招募，但如果第一格的招募内容需要手动确认，MAA就不再会加急剩下三格）
