### ISSUE TITLE
日服傀影肉鸽不期而遇事件“以血还血”无动作

### ISSUE THREAD

**Issue by Loria618** [MaaAssistantArknights/MaaAssistantArknights#4987]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在日服傀影肉鸽中不期而遇事件如果是“以血还血”就会停止不动，如果手动点击可以继续代理，但是如果没操作就会一直卡在事件界面。可以确定上一次遇到此问题的时间为2023-05-29 01:34:12，一直到7:34时我手动选择了选项才继续。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11591507/asst.zip)

### 截图

![屏幕截图 2023-05-29 073813](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44400421/e2e21af2-1477-4110-bfa3-19222ff5f908)
![Screenshot_2023 05 27_12 11 08 718](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44400421/8b7c8b05-49f2-4fef-a95c-8ce0e31d412b)

### 还有别的吗？

模拟器：BlueStacks 5.11.100.2102 P64
OS：Windows 10 专业版 
处理器：AMD Ryzen 7 3700X 8-Core Processor                3.59 GHz
RAM：32.0 GB
64 位操作系统, 基于 x64 的处理器

**Comment by 178619** [comment]
#4954
