### ISSUE TITLE
蓝叠模拟器仍然无法正确识别端口

### ISSUE THREAD

**Issue by neo284** [MaaAssistantArknights/MaaAssistantArknights#4989]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

蓝叠5国际hyper-V版，按更新说明勾选每次重新检测后，仍然无法正确识别端口。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129248612/55301c9f-a092-492c-ae1a-a41e99bff4dc)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129248612/96ecad0e-8acc-4e8b-aefd-b0693cb39dac)
必须关闭自动检测后，手动输入127.0.0.1:端口号之后才能正常工作
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129248612/38f2784c-8515-4038-af42-7b8c3db72929)

我看MAA代码里找的conf文件是存在的
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129248612/7cc4a732-2d61-4a2f-ae11-56ef7da28711)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11593130/asst.log)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/0cdae8d3-3b32-47a6-8cbc-0e2f267f8672)
这个加了吗

**Comment by neo284** [comment]
说明里说是只有多开或者多核心才要改。我只有这一个核心，也没有多开，这也要改嘛？
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129248612/236cd631-d83f-4d22-ab36-a73ff058eb96)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129248612/6eb6f9ed-dd40-42e5-85f9-9b6968eff6c4)

**Comment by neo284** [comment]
> 听你的描述是不是没改过 gui.json？

确实，之前都用的夜神，装了wsl2才换的蓝叠，我以为一样能自动检测。
话说gui.json是不是改过格式，好像没有说明里的这两层
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129248612/9655c3fe-73b3-4c41-a951-78efdcb19088)

**Comment by MistEO** [comment]
文档中对应内容，已作为正式版发布

**Comment by liz8998** [comment]
我加了之后还是不能连接，然后再打开gui，加的词条消失了

**Comment by miyouzi** [comment]
> 我加了之后还是不能连接，然后再打开gui，加的词条消失了

要先关闭MAA，再改配置，不然配置会被盖掉
