### ISSUE TITLE
MAA每次关闭后都会重置我所有设置

### ISSUE THREAD

**Issue by LUOFUBAI** [MaaAssistantArknights/MaaAssistantArknights#4995]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

每次用完MAA我的设置，例如：启动设置，连接设置，游戏设置全部都变为默认的了，每次MAA都要重新设置一遍

### 日志文件

每次启动都会

**Comment by ABA2396** [comment]
放在哪个路径下了

**Comment by MistEO** [comment]
不要放在没有写权限的文件夹里

**Comment by LUOFUBAI** [comment]
> 



> 放在哪个路径下了
放在了d盘

**Comment by LUOFUBAI** [comment]
> 不要放在没有写权限的文件夹里

看不出来哪种是没写权限的文件夹

**Comment by ABA2396** [comment]
那就试试放在d盘根目录，然后管理员权限启动
