### ISSUE TITLE
刷理智功能自动打1-7但结算界面等待时间相当长是为什么呀

### ISSUE THREAD

**Issue by QsRive** [MaaAssistantArknights/MaaAssistantArknights#4999]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

开启刷理智功能后自动打1-7，但打完关卡结束在结算界面等待时间相当长，每把将近8-10分钟是为什么呀？

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11599383/asst.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134185663/58860824-6581-4c61-b9c6-69e911351a35)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/450c93b7-90db-41c4-b94e-c8557532f9dd)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/8e9313db-7fde-4374-89fb-2aad735b0f1e)
