### ISSUE TITLE
关于自定义脚本运行时机的建议

### ISSUE THREAD

**Issue by ngc7331** [MaaAssistantArknights/MaaAssistantArknights#5005]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用 MAA 连接实体设备，利用“开始前”和“结束后”脚本自动设置手机分辨率，但：

- 手动停止任务，比如肉鸽刷一半不想刷了时
- 任务出错，比如截图失败需要手动重启时
- 未选择任何任务就 Link Start 时

三种情况下不会触发”结束后“脚本的运行，不得不手动运行脚本重置分辨率

### 有什么好的想法？

在”开始前“和”结束后“以外增加“中止时”及“出错时”脚本，或在上述异常情况发生时同样执行”结束后“脚本

(for issue-checker, please label it as module: GUI)

**Comment by psi-cmd** [comment]
+1，对应情况为 UI 逻辑中 `CheckAfterCompleted`（负责运行结束脚本）仅在 `AllTasksCompleted` 时运行。
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/c07873bf102f3770e623babea7d5d5b26372e788/src/MaaWpfGui/Main/AsstProxy.cs#LL586-L596
故请求在 stop 状态下也运行结束脚本。

(for issue-checker, please label it as module: GUI)

**Comment by ngc7331** [comment]
另外关于开始前脚本的运行时机，如果我没理解错的话现在是在连接模拟器之前

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/3213c38c7814de8e5eeff66458651838f2c36a84/src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs#L710-L719

在我的使用场景中（自动设置设备分辨率），如果没有提前连接adb，那么第一次link start时开始前脚本就会失败，进而导致分辨率不支持而出错，第二次再跑就没事（因为adb已自动连接）

虽然不太影响使用吧，但还是希望大佬考虑一下这个问题

可能的解决方案比如：
- 支持脚本传递参数，例如“开始前脚本”栏填入`startup.bat ${ConnectAddress}`，这样我可以在脚本中连接好adb，而不需要依靠maa自动连接
- 将开始前脚本的运行时机移到连接成功后
- 增加“连接后脚本”设置，和前面的加起来总共需要“开始前”、“连接后”、“中止时”、“结束后”四个运行自定义脚本的时机

**Comment by ngc7331** [comment]
注意到 #9153 增加了手动停止时执行脚本的选项，以及没注意什么时候开始“未选择任何任务”的情况也会正常执行结束后脚本了。个人感觉目前的设计对“自动设置物理机分辨率”这个需求已经足够，故close issue🎉
