### ISSUE TITLE
YostarEN Copilot can't Auto Squad

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#5009]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

When using 
- [x] Autosquad in Copilot the bot hangs here.
![Screenshot_20230530-215701](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/f997a88c-65d3-4d51-af6c-587963533bd5)

The problem is that `template\BattleQuickFormationClear.png` has the Roguelike version of the "Clear Formation" button (which is correct and works fine)
### ROGUELIKE ONE:
![BattleQuickFormationClear](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/5e81559a-22ae-44e3-b64a-a64079092e8f)

The "normal stage" one has a new line. I've already cropped the **new**  `BattleQuickFormationClear.png` which should work with the Auto Squad option of the Copilot _(note: this is from 2560x1440 so it might be a bit bigger. If downscale needed just let me know.)_
### NORMAL STAGE ONE:
![BattleQuickFormationClear](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/bb6c1098-7aa2-4b6f-955e-30590b4bcaf6)

### Suggestion:
Changing the **OLD** `BattleQuickFormationClear.png` to something along the lines of `Roguelike@BattleQuickFormationClear.png`, as to keep the nomeclature of the other Roguelike png's.
Adding a **NEW** `BattleQuickFormationClear.png` for the Normal Copilot one.

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11605006/asst.log)
From line _misstype_ ~~21423~~  21342 Copilot tries again multiple times in vain.

**Comment by liuyifan-eric** [comment]
YoStar lol
My suggestion is to crop the image to include only the trash can icon (i.e. do not include the text), such that we don't have to modify other parts of the program etc.. Can you test it for us?

**Comment by Constrat** [comment]
> YoStar lol My suggestion is to crop the image to include only the trash can icon (i.e. do not include the text), such that we don't have to modify other parts of the program etc. (Hopefully the icon is the same for both lol) Can you test it for us?

I honestly hope that just the trashcan works... I'm thinking that If the text was considered, maybe there was a reason

**Comment by Constrat** [comment]
Ok I just noticed this. The Roguelike one and the "Normal" one are completely different.
### This is the one in the Roguelike of YostarEN 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/823c1c42-e035-4f06-8bda-ed4b035ecdde)

### Meanwhile this is the one in the Quick Select of the Squad menu. 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/a747a7b7-30f9-4132-b047-19c513d4ed6e)

Not only the text is new line'd, the trashcan icon is also different.... I have no idea how in the Roguelike it works (the ocr might do very well with the "Clear Selection" and doesn't care about the different icon.

### The one in `YostarEN\resource\template` is this:
![BattleQuickFormationClear](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/3289b23f-de89-4ed2-a884-e2813d8dd12c)
It's a mix of the two.

**Comment by Constrat** [comment]
I've temporarily changed the `BattleQuickFormationClear.png` to this 
![BattleQuickFormationClear](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/5a8f571d-7dc8-4410-a43d-ad2ed20c2382)

Copilot still gets stuck. I don't think it's an image issue after all.

**Comment by Constrat** [comment]
Fixed with #5085
