### ISSUE TITLE
刷关卡时，如果吃药会卡在吃药界面

### ISSUE THREAD

**Issue by Yubeiqi** [MaaAssistantArknights/MaaAssistantArknights#5012]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

吃药的时候会等待体力自然回复一点再吃
可以在截图里面看到，第14次行动到吃药的时候卡住了大概3分钟多，这期间就是在等待体力自然回复

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11607798/asst.log)

### 截图

![图片1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49139699/3a34be40-7d0f-47c2-bb22-af3a443944bd)

### 还有别的吗？

win10家庭版系统 64位，蓝叠模拟器国际版5.11.40.1003 32位
体感是更新了ui的那次更新后才出现这个问题的

**Comment by MistEO** [comment]
> 高级设置里选了博朗台模式么

不对啊，吃药为什么要加这个来着，吃药体力又不会溢出

**Comment by ABA2396** [comment]
> > 高级设置里选了博朗台模式么
> 
> 不对啊，吃药为什么要加这个来着，吃药体力又不会溢出

35+120=155

**Comment by KJH-x** [comment]
吃小药的时候15，80都不会溢出，前几天发现卡住以为坏了，今天特意看了看日志才发现是在等待
建议改回仅碎石头 或者 增加逻辑切换选项

**Comment by ABA2396** [comment]
正常就算碎石也不会等这几分钟的吧（）
