### ISSUE TITLE
win7系统,MAA刚点开就显示已停止运行,怎么解决~?

### ISSUE THREAD

**Issue by w20131251** [MaaAssistantArknights/MaaAssistantArknights#5013]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

RT,每次点开都是停止运行.C++ .net,以及文档中提及的WIN7要注意的补丁都检查过了,不知道咋回事

### 日志文件

.

### 截图

![1685535006488](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38577229/ba067d53-0443-434f-97d9-360e913e714e)

**Comment by MistEO** [comment]
发下 gui.log 和 asst.log
