### ISSUE TITLE
【自动公招】招聘许可不足时会判定为任务出错

### ISSUE THREAD

**Issue by gracale** [MaaAssistantArknights/MaaAssistantArknights#5017]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天起来发现联络次数已满3次，复现了一遍自动公招，发现MAA执行步骤如下。
发现4星Tag-点击tag-点击勾-提示招聘许可不足-关闭招募栏回到公招界面-MAA提示任务失败
可否改成当招聘许可不足时，依次检查四个公招栏标签是否为4星，否则自动刷新？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11620978/asst.log)

**Comment by horror-proton** [comment]
#6569
