### ISSUE TITLE
定时任务修改不了时间

### ISSUE THREAD

**Issue by yanxi22** [MaaAssistantArknights/MaaAssistantArknights#5021]
好像把修改时间的那个空设置成 不可填入 了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94839803/49fde106-6c76-4f13-863b-e14a8142aa96)

**Comment by ABA2396** [comment]
你勾上就能改了

**Comment by oracle91** [comment]
这个定时执行功能是win版有的吗？mac版好像没找到这个功能
