### ISSUE TITLE
MAA刷水月选取絮雨卡在备战页面

### ISSUE THREAD

**Issue by eractTOT** [MaaAssistantArknights/MaaAssistantArknights#5025]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用MAA刷水月的时候会有一个问题，就是医疗选到絮雨的时候maa选技能会点错进入选人界面，然后就会卡住不动（大多数第一次会自动选1技能但是第二次选技能的时候会有偏差直接进入选人界面卡死没有动作）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11628164/asst.log)
大约在01:46:41前后

### 还有别的吗？

win10 蓝叠国际版
R9 5900HX
RTX3080

**Comment by fushufu** [comment]
我也遇到了，会识别到絮雨而不是点开始战斗

**Comment by 771630220** [comment]
我今天也遇到了，临时招募给的絮雨，之后进入战斗选人界面，选到絮雨技能就会卡死不动，不会点击开始战斗
