### ISSUE TITLE
EN服 macOS playcover 基地换班好像识别不了能天使皮肤还有点错筛选按钮

### ISSUE THREAD

**Issue by Argonautes0607** [MaaAssistantArknights/MaaAssistantArknights#5026]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

一图流自定义基建换班，筛选的时候点了右上角的那个filter按钮卡住，还有好像认不出能天使皮肤卡住

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11630859/asst.log)

### 截图

<img width="1590" alt="截屏2023-06-02 08 46 28" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106745133/5e3ddfcb-4ef4-4dd2-8b73-d4cac04cab32">
<img width="1012" alt="截屏2023-06-02 08 43 51" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106745133/120054f0-0603-48b9-97f7-af33a46b3654">

### 还有别的吗？

m1 mac mini (MacOS 13.4)
MAA v4.19.0

**Comment by Constrat** [comment]
Fixed with 9f2c748

**Comment by Constrat** [comment]
(By the way. It's not a problem of skins / models, the detection is made only by text and unfortunately in infrastructure, `I`, `i` and `l` seem to have issues: https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5549)
