### ISSUE TITLE
EN服傀影肉鸽会卡在特定的不期而遇界面

### ISSUE THREAD

**Issue by NonArrendertiMai** [MaaAssistantArknights/MaaAssistantArknights#5028]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

模拟器：雷电模拟器9.0.42
MAA：4.19.0
明日方舟：YoStarEN

参照附图，每次肉鸽挂机会卡在同样的事件上，选项1需要扣除1希望，且拥有希望值为0时便会卡住无后续操作。
事件时间节点大致为06:21:40。

### 日志文件

[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11632507/asst.bak.zip)

### 截图

![屏幕截图(365)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45807542/d58f1fb5-f7db-4512-add1-481d851eebe4)

### 还有别的吗？

MAA肉鸽设置

肉鸽主题：傀影
策略：第二层后退出
开局分队：默认分队

投资源石锭 √
开局职业组：取长补短
开局干员：羽毛笔
开局干员使用助战 √
使用非好友助战 √

**Comment by Loos1n** [comment]
蓝叠模拟器相同情况

**Comment by Constrat** [comment]
Duplicate of #3433
