### ISSUE TITLE
关于使用maa电脑自动黑屏重启的反馈

### ISSUE THREAD

**Issue by Ohanasama** [MaaAssistantArknights/MaaAssistantArknights#5029]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

之前反馈过运行maa会不定时黑屏重启。最近贴吧找到方法，把cpu睿频关掉（电源设置处理器最大99%），这样用maa就不会再黑屏重启，希望能反馈给制作组，找到一些相关原因。

### 日志文件

无文件

**Comment by bakashigure** [comment]
有可能你的`CPU`过热导致重启
