### ISSUE TITLE
4.0 加入专精自动收获及界面提示

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#503]
![Screenshot_2022 05 13_20 30 54 977](https://user-images.githubusercontent.com/18511905/168385087-b973da9b-22ca-4a60-9425-640780adfa90.png)

![Screenshot_2022 05 13_20 30 59 260](https://user-images.githubusercontent.com/18511905/168385089-b31ec1e8-f018-4c64-822b-41e8b3ee0cd9.png)

![Screenshot_2022 05 13_20 31 05 277](https://user-images.githubusercontent.com/18511905/168385093-65196de8-7df2-4945-99fb-dc2ceebbe141.png)

**Comment by zzyyyl** [comment]
加了吗（？

**Comment by ntgmc** [comment]
没加（发邮件催玛丽）

**Comment by BigSaltyMan** [comment]
4.21.0 依然没加，警钟长鸣

**Comment by ABA2396** [comment]
警钟长鸣
