### ISSUE TITLE
mumu模拟器更新后自动检测ADB路径错误导致无法替换ADB和操作无响应

### ISSUE THREAD

**Issue by SaintNut** [MaaAssistantArknights/MaaAssistantArknights#5032]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

问题：mumu模拟器更新后，adb_server.exe文件位置发生变动，从原路径变动为mumu\emulator\nemu\vmonitor\bin\adb_server.exe ，因为mumu模拟器需要强制替换ADB，导致自动检测ADB位置时提示替换失败，从而出现能连上但不能操作的问题
玩家暂时的解决方案：手动选择正确的ADB路径之后强制替换ADB

### 日志文件

无需日志文件

**Comment by ABA2396** [comment]
为什么会“导致自动检测ADB位置时提示替换失败”？强制替换不会检测adb路径，更新之后自动检测路径功能能用吗

**Comment by SaintNut** [comment]
> 为什么会“导致自动检测ADB位置时提示替换失败”？强制替换不会检测adb路径，更新之后自动检测路径功能能用吗

这个问题出现在mumu模拟器6.0
自动检测路径功能可以使用，会自动检测到mumu模拟器文件夹，但自动填写的路径是adb_server.exe在mumu模拟器更新前所在的位置，mumu模拟器更新之后这个路径实际上已经不存在了，更改到了mumu\emulator\nemu\vmonitor\bin\adb_server.exe，但自动检测后填写的路径仍然是更新前的老位置
在自动检测填写错误路径的情况下，强制替换ADB会提示替换失败，在我手动选择正确路径之后再强制替换就成功了
猜想MAA的自动检测填写路径功能可能不是根据adb_server.exe的实际位置，而是根据模拟器安装目录和对应模拟器adb所在位置自动填写的，mumu模拟器6.0的自动填写目录可能需要更新为正确的mumu\emulator\nemu\vmonitor\bin\adb_server.exe

**Comment by ABA2396** [comment]
更新之后再使用自动检测，是否能正确检测到对mumu的两种路径的支持？如果模拟器已更新但未重新检测，导致替换时使用的路径并非更新后的路径，那就没必要修了。

**Comment by SaintNut** [comment]
> 自动检测对mumu的两种路径都是支持的。模拟器更新之后再使用自动检测，是否能正确检测到更新后路径？如果模拟器已更新但未重新检测，导致替换时使用的路径并非更新后的路径，那就没必要修了。

因为恰好mumu6的这次更新导致碧蓝航线打不开了所以我换成mumu12了，无法复现当时的场景，不过当时我确实是重新检测了多次仍然是mumu6的老路径，甚至彻底重装过MAA都是只能自动检测填写老路径所以才来发帖反馈的，当时MAA的版本是v4.19.0，更新版本选的稳定版

**Comment by ABA2396** [comment]
说起来还记得当时改过连接配置吗？
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/a61a17b9-0c46-4ffe-ab77-ae8d340089aa)
mumu和mumu12是两个单独的配置

**Comment by SaintNut** [comment]
> 说起来还记得当时改过连接配置吗？ ![image](https://user-images.githubusercontent.com/99072975/246341908-a61a17b9-0c46-4ffe-ab77-ae8d340089aa.png) mumu和mumu12是两个单独的配置

当时是“mumu模拟器”这个我很确定，而且出现问题的时候我没有安装过mumu12和其他模拟器，更换mumu12是之后的事情了

**Comment by scshtyk** [comment]
我也遇到了这个问题， 升级了mumu模拟器   重启电脑后必须手动设置adb路径再强制替换

**Comment by ABA2396** [comment]
> 我也遇到了这个问题， 升级了mumu模拟器 重启电脑后必须手动设置adb路径再强制替换

```
"MuMuEmulator",  new List<string>
{
"..\\vmonitor\\bin\\adb_server.exe",
"..\\..\\MuMu\\emulator\\nemu\\vmonitor\\bin\\adb_server.exe",
".\\adb.exe",
}
```
这三种路径都是支持的来着，手动改的和原来的路径有什么区别吗
