### ISSUE TITLE
小工具添加自动公招功能（清理公招票）

### ISSUE THREAD

**Issue by liyangyuan** [MaaAssistantArknights/MaaAssistantArknights#5035]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

本咸鱼积攒了大量的公招资源实在不想手动清理

### 有什么好的想法？

能一直公招直到4个都是五星以上再停止，那最好不过了。

提前蟹蟹!!!!!!!!!

### 其他内容

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/135389310/8d9d59e8-e907-46ba-8197-728af28c1f91)

**Comment by ABA2396** [comment]
每天开两次公招票都会越来越少吧，或者勾上自动使用加急许可一次用完

**Comment by liyangyuan** [comment]
> 每天开两次公招票都会越来越少吧，或者勾上自动使用加急许可一次用完

好的谢谢
