### ISSUE TITLE
建议增加功能：基建换班在多个自定义班次中选择心情合适的班次

### ISSUE THREAD

**Issue by AKPRTS** [MaaAssistantArknights/MaaAssistantArknights#5037]
玩家自定义了5个生产经验书的制造站的班次 分别是 A B C D E 优先级A最高  B最低
假如换班时三个制造站所进驻的干员班次分别为  B C D
B C 低于心情阈值  D高于心情阈值 
A组在宿舍心情尚未恢复完毕  E组心情已经回满
此时 会将B C 中心情较低的班次更换为E

**Comment by hifuclub** [comment]
我的解决方案是,挂两个maa,一天六换

**Comment by ABA2396** [comment]
> 我的解决方案是,挂两个maa,一天六换

那你为什么不把两份方案写在一个文件里呢

**Comment by hifuclub** [comment]
> > 我的解决方案是,挂两个maa,一天六换
> 
> 那你为什么不把两份方案写在一个文件里呢

1.因为网页版排班生成器只能维护最多三班,我基建有点复杂直接修改代码不太方便.
2.其中一个maa执行完后我设定了重启电脑,六班全重启电脑影响电脑使用
3.我有一个maa只开了换基建,另一个开的比较多
4.多开一个也不会额外增加电脑负担(我使用计划任务需要时才开启maa),但是更容易维护

**Comment by Shawnsdaddy** [comment]
太复杂了，我选择动态换班，收益还高
