### ISSUE TITLE
借助战打OF1时，建议默认选中某个编队(如：编队4)

### ISSUE THREAD

**Issue by 111seier** [MaaAssistantArknights/MaaAssistantArknights#5038]
### 在提问之前...

- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

步骤：借助战打OF1

结果：会在**当前编队**选中干员打OF1

期望：MAA可以**默认选中编队4**，再选中干员打OF1

### 有什么好的想法？

提这个需求的目的是，借助战打OF1会打乱玩家自身的编队，让玩家游玩时需要重新编排干员

**Comment by status102** [comment]
- #7061
