### ISSUE TITLE
建议在定时执行中增加可选项（如定时1执行基建换班，定时2执行刷理智）

### ISSUE THREAD

**Issue by xiaom-hwj** [MaaAssistantArknights/MaaAssistantArknights#5039]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前设置了定时基建换班，但是有的时候用maa刷完理智后，忘记勾选基建换班，导致没有定时执行。

### 有什么好的想法？

希望能够在定时执行中添加任务勾选功能，比如定时1执行开始唤醒和基建换班，获取信用及购物；定时2执行刷理智；定时3执行基建换班等。

**Comment by status102** [comment]
可以试试使用自定义配置，并为每个定时执行设置对应配置
