### ISSUE TITLE
基建收取的时候如果会客室有未领取线索会陷入死循环

### ISSUE THREAD

**Issue by pboymt** [MaaAssistantArknights/MaaAssistantArknights#504]
应该是纯逻辑问题，没有考虑到会客室会有未领取的线索（我忘了别人送的会不会有这个提示了，但是每天早上刷新的肯定有提示）。

截图：
![截图](https://user-images.githubusercontent.com/10893582/168409341-2d27c757-a351-4df5-aab7-7881c74aae31.jpg)

**Comment by MistEO** [comment]
请附上日志，谢谢~

**Comment by pboymt** [comment]
不是，本来代码就没有这个判断逻辑，GUI上的日志就卡在收取基建产品这里啊😰

**Comment by MistEO** [comment]
你是看了代码发现没有收线索的逻辑么。。正常肯定是能收的，怎么可能会有这么容易复现的死循环呢

**Comment by MistEO** [comment]
看你截图应该多半是分辨率问题，maa 对非 16:9 的支持不是很好，也不太支持有异形屏的那个黑边

> 目前仅对 16:9 分辨率支持较好，最低支持 1280 * 720，更高不限。非 16:9 分辨率可能会有奇奇怪怪的问题，正在进一步适配中_(:з」∠)_

有兴趣可以考虑使用 adb shell wm 来强改分辨率，用完再改回去，参考 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/388

**Comment by pboymt** [comment]
> 看你截图应该多半是分辨率问题，maa 对非 16:9 的支持不是很好，也不太支持有异形屏的那个黑边
> 
> > 目前仅对 16:9 分辨率支持较好，最低支持 1280 * 720，更高不限。非 16:9 分辨率可能会有奇奇怪怪的问题，正在进一步适配中_(:з」∠)_
> 
> 有兴趣可以考虑使用 adb shell wm 来强改分辨率，用完再改回去，参考 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/388

原来是这样吗？16+:9屏幕下，贴图高度不会有比例变化的，边缘元素是贴靠策略，其他的都在视野内（也就是居中视野变阔），ArknightsAutoHelper就没有做太复杂的适配（我去看看代码看看能不能帮着改🧐
