### ISSUE TITLE
[奇特的问题] 删除maa重新下载后  无法随着开机自启动

### ISSUE THREAD

**Issue by Theusinuel** [MaaAssistantArknights/MaaAssistantArknights#5043]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

之前MAA出现了启动时会一直显示“开始任务：START”，并卡在游戏登录界面（淡黄色棱形）的问题
删除文件，官网重新下载后，该问题解决，但又出现了maa**无法随着开机自启动**的情况
试着使用了批处理，快捷方式拖入shell:startup，“我的电脑”中的任务处理程序等方式，皆无法自启动
在任务处理器-启动中发现，maa显示的一栏变灰，且**无法打开文件位置**，怀疑是初始下载的maa仍在盘中某个地方留有残余，并占用了自启动程序，导致系统唤起的自启动是已被删除的MAA，新下载的MAA无法被唤起
如果maa文件中直接有unistall或许会好一些，能保证每次卸载都是完全卸载

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11644562/asst.log)

### 截图

![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/95957130/0b1209a5-969d-4b5b-b5fc-f90cf2fe0b30)

**Comment by Theusinuel** [comment]
注册表删了，也没成功

**Comment by ntgmc** [comment]
> 之前MAA出现了启动时会一直显示“开始任务：START”，并卡在游戏登录界面（淡黄色棱形）的问题
这可能是因为MUMU模拟器需要强制替换adb，所以不替换会无法进行操作
关于自启动我不清楚

**Comment by Theusinuel** [comment]
现在已经完全无法连接模拟器了（蓝叠国际）
我注意到的问题是，可能因为我一次次删除maa文件夹并重新下一个新的开始用，导致每次都是饮鸩止渴，新的maa第二天也会陷入无法自启动的情况。而且不只是自启动失效，是系统任务都无法调用启动的境地。导致我每天都要手动打开maa才能运行。
强烈建议maa出unistall或其他的可以删除以往数据的功能

**Comment by octopusYan** [comment]
我尝试了下没有复现出来无法自启的问题。
不过你可以检查下注册表
- `计算机\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`
- `计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`

看是否有`MAA`开头的项，删除后在MAA内重新设置一遍开机自启

**Comment by Theusinuel** [comment]
之前已通过清理注册表解决问题，不过还是谢谢答复&nbsp;


L&#39;?tranger
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "octopus ***@***.***&gt;; 
发送时间: 2024年8月12日(星期一) 下午2:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] [奇特的问题] 删除maa重新下载后  无法随着开机自启动 (Issue #5043)














 
我尝试了下没有复现出来无法自启的问题。
 不过你可以检查下注册表
  
计算机\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run
 
计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
  
看是否有MAA开头的项，删除后在MAA内重新设置一遍开机自启
