### ISSUE TITLE
开启hyperv连接失败

### ISSUE THREAD

**Issue by liz8998** [MaaAssistantArknights/MaaAssistantArknights#5046]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

按照官网上操作后，gui.json添加行每次打开软件都会消失

### 日志文件

1

**Comment by ABA2396** [comment]
消失是因为格式写错了，看看标点有没有写成中文的或者没用转义
