### ISSUE TITLE
明日方舟新登录ui适配

### ISSUE THREAD

**Issue by U98de** [MaaAssistantArknights/MaaAssistantArknights#5050]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa无法登录新ui

### 日志文件

应该是这一份，3号晚上变得ui，然后抛了一串任务出错出来
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11644894/asst.bak.log)

今天的log（感觉没什么用
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11644893/asst.log)

### 截图

蓝叠模拟器内截屏
1080P
![Screenshot_2023 06 04_13 46 29 831](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91559690/da4416f6-91e4-40af-8269-fd4c1eb50e8c)

720P
![Screenshot_2023 06 04_13 49 54 157](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91559690/196cddae-2a9b-454f-884e-bf420644244d)

**Comment by ABA2396** [comment]
我这儿登录界面还没变，测不了

**Comment by ABA2396** [comment]
现在重启maa就可以支持登录了
