### ISSUE TITLE
挂机保全派驻时出现蓝屏情况

### ISSUE THREAD

**Issue by ChenqiangH** [MaaAssistantArknights/MaaAssistantArknights#5051]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

4.16版本之后每次挂机保全派驻都会出现蓝屏状况

基本都是挂一关，下一关就蓝屏。

模拟器版本是蓝叠国际 5.10.110.1002 N64

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11645208/asst.log)

**Comment by MistEO** [comment]
考虑散热或硬件问题，maa 没能力让电脑蓝屏（

**Comment by ChenqiangH** [comment]
> 考虑散热或硬件问题，maa 没能力让电脑蓝屏（
散热的话没问题的，硬件应该不至于出问题
CPU 13900K
内存64g
显卡4090

我看着任务管理器 CPU 内存 GPU 连50%都没有，我看贴吧也有反馈 电脑重启状况。
