### ISSUE TITLE
鹰角新登录界面无法被识别

### ISSUE THREAD

**Issue by TobyLi223** [MaaAssistantArknights/MaaAssistantArknights#5053]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

见标题和视频BV1Tu4y1Z7K2

### 有什么好的想法？

请求适配

### 其他内容

无

**Comment by ABA2396** [comment]
c3761e868c57a18665932cfd91cc4f8173c712a1 fixed

**Comment by ABA2396** [comment]
现在重启maa就可以支持登录了
