### ISSUE TITLE
肉鸽一直放弃探索

### ISSUE THREAD

**Issue by zerocak** [MaaAssistantArknights/MaaAssistantArknights#5056]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

官服，在后台挂了一晚上发现一直写放弃探索

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11646012/asst.log)
2023/6/4 21:42:54~

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/47045527/a78944e1-5d7e-4ec0-8f6a-97ba83738b98)

### 还有别的吗？

模拟器：Mumu 2.7.26.0(x64)(20230517174917)
官服
MAA：v4.19.1-alpha.1.d008.g78b4ec31

**Comment by MistEO** [comment]
卡在哪个界面了？debug/roguelike 里面有图，也发一下

**Comment by zerocak** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/47045527/34f81a33-d8b4-49dc-83e2-16ca812f3e63)
![2023-06-04_21-42-49-937_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/47045527/9a65a9bc-6538-421d-9995-37bf2db3e064)
