### ISSUE TITLE
[KR] Credit supply and demand and store bugs

### ISSUE THREAD

**Issue by haletaleila** [MaaAssistantArknights/MaaAssistantArknights#5057]
### Before raising the issue...

- [x] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

 Credit supply and demand and store progress, stopped on the following screen after a friend visit.

### Log files

 Credit supply and demand and store progress, stopped on the following screen after a friend visit.

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/133977188/430e3c59-0f2a-41a2-bc3d-d4114a80cec5)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/133977188/07af4364-69fb-48f8-a6b6-1d2ffded82c8)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/3d02e708-b9f5-4a3e-a767-a6ef2df157a3)

**Comment by ABA2396** [comment]
It seems that the international version of the game does not support this feature yet. You can try adding the following code to the "tasks.json" file on the corresponding server:

```
  "StageEpisodeToOF": {
        "text": [
            "火蓝之心"
        ]
    },
```

Make sure to modify the content in the "text" section to the name of the OF-1 event.

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/2867f817-2f46-4b51-9a12-3e754873f063)
You can refer to the practices on other servers for guidance.

**Comment by ABA2396** [comment]
If feasible, could you please submit a pull request or provide me with the corresponding text? I don't have access to the Korean server client, so I am unable to test it myself.

**Comment by haletaleila** [comment]
korean text : 파란 불꽃의 마음

**Comment by ABA2396** [comment]
I'm not sure if this will work correctly on the Korean client. You can try modifying the corresponding file based on the changes in the commit to see if it runs correctly.
