### ISSUE TITLE
夜神模拟器问题

### ISSUE THREAD

**Issue by EECBA** [MaaAssistantArknights/MaaAssistantArknights#5058]
### 在提问之前...

- [ ] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在使用夜神模拟器运行MAA刷水月肉鸽的时候游戏可能会闪退，不是模拟器闪退，是游戏直接回到模拟器菜单，我不清楚是模拟器问题或者是MAA的问题，因为之前在用模拟器的时候没遇过这样问题

### 日志文件

无

### 截图

无

### 还有别的吗？

夜神模拟器

**Comment by ntgmc** [comment]
你好 是模拟器的问题，并且只有夜神模拟器有这个问题。
