### ISSUE TITLE
MAA Does Not Recognize Adverse Environment Battle Start Button

### ISSUE THREAD

**Issue by SpinalWrithe** [MaaAssistantArknights/MaaAssistantArknights#5060]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

When using MAA perform the fight task in Chapter 10 missions on the "Adverse Environment" difficulty MAA recognizes the initial "start battle" button, but when it gets to the squad selection screen with the "operation start" button it hangs for about 30 seconds. Then MAA sends back "Task: error Fight" and then stops the task.

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11646781/asst.log)

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/135544700/ffe81cdd-302a-4076-904d-487ee149e65d)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/135544700/eb62290b-5d17-492b-a0de-ed2737418ec5)

### Anthing else?

Emulator: Blues Stacks
OS: Windows 10
Client/Server Type: YoStarEN
MAA Version: v4.19.0

**Comment by Constrat** [comment]
Fixed in #5020.

**Comment by ABA2396** [comment]
@Constrat By the way, if it only involves modifying 'tasks.json', it can be achieved through modifications in [MaaRelease](https://github.com/MaaAssistantArknights/MaaRelease/tree/main/MaaAssistantArknights/api/resource/) for hot updates. Users just need to restart the client or wait for the automatic update at 4 or 16 o'clock to resolve it. However, it's important to note that updates that involve pictures or other files cannot be achieved through this method of hot updates.

**Comment by Constrat** [comment]
> @Constrat By the way, if it only involves modifying 'tasks.json', it can be achieved through modifications in [MaaRelease](https://github.com/MaaAssistantArknights/MaaRelease/tree/main/MaaAssistantArknights/api/resource/) for hot updates. Users just need to restart the client or wait for the automatic update at 4 or 16 o'clock to resolve it. However, it's important to note that updates that involve pictures or other files cannot be achieved through this method of hot updates.

Thank you, I still didn't know that. I just recently started contributing. Unfortunately for the Battle Adverse I had to add a .png both for the CN and the EN.

So for quick hotfixes I can just go to MaaAssistantArknights/api/resource/global/YoStarEN/resource/tasks.json and directly commit in that file?

**Comment by ABA2396** [comment]
> Thank you, I still didn't know that. I just recently started contributing. Unfortunately for the Battle Adverse I had to add a .png both for the CN and the EN.
> 
> So for quick hotfixes I can just go to MaaAssistantArknights/api/resource/global/YoStarEN/resource/tasks.json and directly commit in that file?

The best approach is to submit a copy to both repositories, as the tasks in the API will actually override the locally named tasks or add tasks that don't exist locally. If it only involves modifications to tasks.json, this method is the fastest way to go live.

**Comment by SpinalWrithe** [comment]
Testing the new "nightly" release version (v4.19.1-rc.1) that is stated in the changelog that fixed this issue is still occurring. 
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11689795/asst.log)

**Comment by Constrat** [comment]
I think I see the problem.
The fix that I did mentioned in the changelog fixed the copilot one. I haven't noticed that the "Fight" task uses a different naming scheme from the one I added.
@MistEO why are the same images being used under different names between the Fight task and the Copilot task?

**Comment by Constrat** [comment]
I'm wondering if the best course of action is to just patch the fight/tasks.json adding a new BattleAdverseStartButton.png named as StartButton3 and adding it in the tasks.json wherever the StartButton2 appears, to make it like an else if or if changing completely the fight task structure, making it call the BattleStartButton that already exist.

**Comment by MistEO** [comment]
Refactoring is a good idea but it brings too many risks, I think it's better to use button3 to tinker with it for the time being. (btw, should it be called StartButton2-Adverse?)

@ABA2396 What do you think?

**Comment by Constrat** [comment]
StartButton2-Adverse looks good for me. So that it makes a bit more sense (If we go and change the nomeclature I would change `StartButton2` to `StartButton2-Normal` to make it homogeneus. At the end of the day it's just a change in the file name / tasks.json.

I was scrolling through the CN tasks.json, refactoring everything isn't easy. I'm still getting used to the task scheme but there are at least 8 mentions of the StartButton2 task, isn't it possible to give him two templates in the task? It tries to detect one, if it doesn't reach the threshold it tries with the next one.

The log says that the score is 0.72... Maybe just lowering to 0.7 would fix the problem, but I feel like that's no decent solutions.
Let me know what you think.

**Comment by Constrat** [comment]
So with #5169 this shoule be fixed @SpinalWrithe as soon as the new update rolls out let me know if the differences I made work or not. Sorry if I trouble you again after almost two weeks, but I've been a bit busy with exams so I couldn't give that much time to MAA.

**Comment by SpinalWrithe** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11790509/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11790510/asst.log)
Issue is still occurring in the newest "nightly" release.

**Comment by Constrat** [comment]
You are using the Version v4.19.2-beta.1.d011.g26b3d5f5, extracted from the asst.log file you sent.

In this version the Adverse Fight still hasn't been implemented, please wait for the next release. About 2 hours ago the [v4.19.2-rc.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.19.2-rc.1) has been released.
It's a non-compiled version meaning there's only the source code (you could build it yourself)

I suggest you waiting for the v4.19.2 which should drop in these days, correct me if I'm wrong @MistEO

**Comment by ABA2396** [comment]
> You are using the Version v4.19.2-beta.1.d011.g26b3d5f5, extracted from the asst.log file you sent.
> 
> In this version the Adverse Fight still hasn't been implemented, please wait for the next release. About 2 hours ago the [v4.19.2-rc.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.19.2-rc.1) has been released. It's a non-compiled version meaning there's only the source code (you could build it yourself)
> 
> I suggest you waiting for the v4.19.2 which should drop in these days, correct me if I'm wrong @MistEO

macos-gui was compiled with an error before, so the version was not sent, I'll run it again.

**Comment by Constrat** [comment]
If you don't mind, sure!

**Comment by SpinalWrithe** [comment]
Issue has been resolved as of version v4.19.12.

**Comment by Constrat** [comment]
Perfect
