### ISSUE TITLE
[JP]Cant Longletter OCR for Toolbox Operators

### ISSUE THREAD

**Issue by wallsman** [MaaAssistantArknights/MaaAssistantArknights#5061]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

OCR of operators from the toolbox is not recognizing operators with a certain number of characters.

The most notable are as follows.
シルバーアッシュ（100％）
エイヤフィヤトラ（100％）
アンジェリーナ（100％）
カンタービレ（100％）
イクゼキュター（100％）
濯塵ハイビスカス（100％）
エフイーター（60％）
プロヴァイゾ（100％）
ワイルドメイン（100％）
パインコーン（100％）
アーススピリット（100％）
チェストナット（100％）
パフューマー（100％）
ハイビスカス（100％）
12F（100％）
ジャスティスナイト（100％）

There are no recognition problems in Rogue as far as I can see in the logs, so I assume it is a display problem in the Operator screen.

### Log files

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11647676/asst.zip)

### Screenshots

![2023-06-05_09-34-13-109_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63186641/227a43b1-866d-4f70-9258-3d17b0f04953)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63186641/2cfa1352-0973-4b9c-8af6-93a2fbcfb0cc)

### Anthing else?

This is a personal request, but I think it would be easier to understand if operators could be displayed with names that match the language in which they are displayed.

**Comment by Constrat** [comment]
You might wanna take a look at #5059 to try playing around with the specialParams, for EN's long names, I just had to bump from 4 -> 6 the 3rd parameter.

**Comment by wallsman** [comment]
Ver4.19.2

12F is OK
but longnames same issue.
