### ISSUE TITLE
maa运行时模拟器cpu占用异常提高直至死机

### ISSUE THREAD

**Issue by KoisatoL** [MaaAssistantArknights/MaaAssistantArknights#5071]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题
任务管理器内显示的对应进程名为BlueStacks Android Host

bug已经出现多次 均为maa运行期间出现 但不是每一次都会出现（不过我平时玩舟用的不是同一个模拟器 不清楚自己玩的时候会不会出现同样的问题）
模拟器卸载重装后依然出现同样的问题
issue提交后会尝试更换模拟器

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11659246/asst.log)
导致死机的那一次的具体时间记得不太清楚 看日志(不过我只看得懂gui.log)是6月3日17:30的一次定时执行
应该也是第一次出现问题的时间点

最近出现的时间点为6月6日01:30之后 和6月6日09:30之后
但由于我当时还在电脑面前 在明显感到电脑卡顿后提前结束了占用异常提高的进程

### 截图

当明显感到电脑卡顿的时候我应该不会第一时间想到截图()

### 还有别的吗？

使用模拟器为蓝叠4国际版
maa版本为4.19.0
操作系统为win10

**Comment by lijianwei-inChina** [comment]
我的电脑打肉鸽会打着打着出现反应慢 然后就死机了 鼠标动不了 操作无响应 就是一直一个画面不动了 只能强制关机

mumu12 最新版maa
