### ISSUE TITLE
基建排班中干员无法被识别

### ISSUE THREAD

**Issue by Yingge02** [MaaAssistantArknights/MaaAssistantArknights#5072]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在会客室更换干员为哓歌时出现无法正确识别并选中哓歌干员的情况，手动选择哓歌干员后MAA会取消选中并再次开始识别。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11659684/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76812811/02053a86-811a-4d0c-9161-909cc64f9541)

### 还有别的吗？

雷电模拟器
安卓7.1
画面比例：1920x1080(16:9)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/ac6b8d9a-f496-4b8f-96a2-e520d9bdfcc7)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/3a475470-b584-4908-a0fe-d2956d1b933c)
"哓歌"->"晓歌"

**Comment by Yingge02** [comment]
啊这……原来是我输错字了吗……
所以为什么输入法输晓歌出现的却是哓歌啊……无语……

**Comment by HCO168** [comment]
我也遇到了这种情况，每次都只能手动把晓哥选中，望修复：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134460467/d39df444-7181-433c-bed2-fa9e083e7d29)
[图]我发现之后手动把晓歌选中了

**Comment by ABA2396** [comment]
…… "晓哥"->"晓歌"

**Comment by HCO168** [comment]
> …… "晓哥"->"晓歌"

啊这，没注意
