### ISSUE TITLE
macOS下，MAA提示TouchModeNotAvaiable，无法使用三种触控模式

### ISSUE THREAD

**Issue by laffylaffyla** [MaaAssistantArknights/MaaAssistantArknights#5074]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在macOS（M1芯片）下使用AVD模拟器以及MAA，在正确设置连接地址后，无法使用minitouch、maatouch、adb中的任意一个触控方式开始任务，均提示TouchModeNotAvaiable。
使用ChatGPT分析日志信息如下：
根据提供的日志，可以分析出以下信息：

1、日志记录了一系列的函数调用过程和时间戳。
2、日志中涉及的类和函数有：asst::Assistant::async_connect、asst::Assistant::append_async_call、asst::Assistant::ctrl_connect、asst::Controller::connect、asst::AdbController::AdbController、asst::PosixIO::PosixIO、asst::MinitouchController::connect等。
3、首先，开始执行asst::Assistant::async_connect函数，然后调用asst::Assistant::append_async_call函数。
4、日志中涉及到通过adb命令与设备建立连接的操作，比如使用adb connect命令连接到emulator-5556设备，但是连接失败，输出了错误消息"failed to resolve host: 'emulator-5556': nodename nor servname provided, or not known"。
5、成功连接后，通过adb命令获取了设备的分辨率信息，分辨率为2560x1440。
6、继续执行其他操作，包括获取设备的ARP表信息、初始化socket等。
7、接下来，尝试使用adb命令推送minitouch程序到设备，并修改文件权限。
8、最后，执行了adb shell命令启动minitouch程序，但是在检测触摸设备时遇到了错误，输出了相关错误信息"Unable to find a suitable touch device"。
9、由于连接失败和触摸设备不可用的问题，最终连接过程失败，记录了相应的错误信息。
总体来说，该日志记录了与设备连接过程中的各种操作和错误，主要涉及到adb命令的执行、设备连接、分辨率获取、触摸设备检测等操作。根据日志中的错误信息，可能需要进一步排查adb连接问题和触摸设备的可用性。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11662289/asst.log)

### 还有别的吗？

AVD配置：
设备模板：Nexus 6P（2560X1440）
系统镜像：Android 12.0 arm64-v8a
Device Frame：关闭

**Comment by laffylaffyla** [comment]
<img width="1012" alt="截屏2023-06-06 19 39 02" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/25323079/2898089c-57e4-4052-8dea-f3efec07b62d">

**Comment by ABA2396** [comment]
@hguandl

**Comment by pein0saga** [comment]
AVD不是标准生产用游戏环境（而是灵活的开发环境），应该和你各种环境设置有关联，影响因素太多。
