### ISSUE TITLE
MAA增加账户管理功能

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#5077]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

这几天鹰角给明日方舟官服的客户端更新了登陆界面，增加了多账号管理功能。

### 有什么好的想法？

利用鹰角刚刚更新的多账户管理功能，给MAA也添加多账户管理功能，实现在同一个客户端同一个adb连接，按照一定的计划表，给不同的账号实现清理智、基建收菜、自动公招、刷肉鸽保全等功能。

**Comment by pein0saga** [comment]
可以多开实现，如果超过三四个账号的话属于商业需求了。建议以私人定制商单的形式寻求与项目组的合作 ）

**Comment by MistEO** [comment]
> 可以多开实现，如果超过三四个账号的话属于商业需求了。建议以私人定制商单的形式寻求与项目组的合作 ）

我明白你是在吐槽+开玩笑，但是听者有意。声明一下，maa 项目组之前、现在、和以后，从来都没有也不会接受任何商单，或者所谓的私人定制

**Comment by MistEO** [comment]
不过他说的没错，这个需求属于给工作室打工，不会做的

**Comment by xiaoweiXX** [comment]
> 不过他说的没有错，这个需求属于给工作室打工，不会做的

主要是我感觉多开会逻辑混乱，而且连接功能一直有问题，我现在如果不点自动检测连接，每次启动MAA都有小概率连不上模拟器，必须得重启MAA才有概率能连上；如果能连接，之后的使用倒是一直正常。我之前也反馈过这个bug，但是一直没修复。

**Comment by xiaoweiXX** [comment]
> 不过他说的没有错，这个需求属于给工作室打工，不会做的

#4426
