### ISSUE TITLE
国际服开启任务时会失败

### ISSUE THREAD

**Issue by Pluto0614** [MaaAssistantArknights/MaaAssistantArknights#508]
如果将template里图片全删除换成国际服的那三张图片会显示目录有中文，发现未知错误，如果只是将图片替换到到template可以开启但会显示任务出错（之前我记得需要对config.json进行覆盖，现在外服资源文件里没有了不知道是不是因为这个问题导致的）
p1是删除换成国际服里的三张图片后
p2是替换
![$L%X6O)A1PYPI KA61P(E9M](https://user-images.githubusercontent.com/105011997/168438822-587bc2bc-c8d1-47f7-a15d-45f013661799.png)
![VZ$SIHP~5UA~JDY2)94$T83](https://user-images.githubusercontent.com/105011997/168438823-6eb2e566-8284-4204-ab48-92d3d327fffc.png)

**Comment by MistEO** [comment]
国际服暂时没支持了，敬请期待吧~（~~指新建文件夹~~

**Comment by MistEO** [comment]
v3.9.6 重新支持了，后续功能逐步适配，请参考[文档](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/master/resource/global/YoStarEN)
