### ISSUE TITLE
自动更新后乱改设置

### ISSUE THREAD

**Issue by zeroheng** [MaaAssistantArknights/MaaAssistantArknights#5083]
### 说说你遇到的问题？

这次自动更新后把我的设置全都改的一塌糊涂 点上了吃理智药的选项 还让选了1-7 还让基建换班的自定义设置莫名其妙的失效了 定时启动后搞得我的基建全涣散 还把理智药吃完了 还刷了我现在根本不需要的1-7 浪费了大量资源 希望以后自动更新别再出现这种傻逼情况

**Comment by MistEO** [comment]
不欢迎吐槽，提 bug 请选择 bug 反馈并带上日志。既然觉得傻逼可以直接删了别用

**Comment by MistEO** [comment]
补充一句，有问题可以提，但要带上日志，issue 是用来跟踪解决问题的，不是来接收抱怨的。
