### ISSUE TITLE
逍遥模拟器连接时卡死

### ISSUE THREAD

**Issue by Ptilopsis01** [MaaAssistantArknights/MaaAssistantArknights#5089]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，点击开始后右侧信息栏出现“正在连接模拟器”字样，此后一直无后续动作，有时重启maa后会正常，这一问题概率发生

问题持续时模拟器可正常使用，而maa若进行“停止”操作，则会一直卡在“正在停止”步骤

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11674806/asst.log)

### 还有别的吗？

逍遥模拟器版本9.0.0，使用安卓9；maa版本为4.19.0

**Comment by pein0saga** [comment]
最近蓝叠国际也遇到了，强制重启MAA有概率可以解决。不行就再重启一遍或者干掉所有adb进程试试

**Comment by xiaoweiXX** [comment]
连接是个老问题了，我用的雷电，很早之前就出现过连接问题，只不过是MAA识别不到雷电报错并尝试启动雷电（实际已经启动）
#4426

**Comment by Ptilopsis01** [comment]
> 连接是个老问题了，我用的雷电，很早之前就出现过连接问题，只不过是MAA识别不到雷电报错并尝试启动雷电（实际已经启动） #4426

但我之前并没有碰到过这个问题，所以要么是逍遥新版本的原因，要么是maa更新的原因
