### ISSUE TITLE
v3.3.2 MAA异常闪退

### ISSUE THREAD

**Issue by Criogaid** [MaaAssistantArknights/MaaAssistantArknights#509]
MAA正常挂机时闪退，主机无性能问题
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8693769/asst.log)
![](https://cdn.jsdelivr.net/gh/Criogaid/PhotoBucket/img/20220515040708.png)
![](https://cdn.jsdelivr.net/gh/Criogaid/PhotoBucket/img/20220515040733.png)
[系统日志.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8693777/default.zip)

Thanks♪(･ω･)ﾉ

**Comment by MistEO** [comment]
掉落识别有点问题，在重写了 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/507
