### ISSUE TITLE
访问好友奖励没到上限，已经没有剩下的好友开启线索交流时，继续访问会无限循环。

### ISSUE THREAD

**Issue by trTvT** [MaaAssistantArknights/MaaAssistantArknights#5090]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

访问好友每天获取10次信用，但是好友里不够10个人开启线索交流的话，脚本会无限访问下一个好友。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11674921/asst.log)

### 截图

![11](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131618264/9baa6fa7-18f5-4afd-8621-734a986e1f61)

**Comment by WSMTBG** [comment]
官服留ID我加你（doge）
