### ISSUE TITLE
公共招募部分，添加”是否招募小车“的可选项

### ISSUE THREAD

**Issue by coccustbb** [MaaAssistantArknights/MaaAssistantArknights#5091]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

新的重装小车需要公招来加潜能，而maa拉到9小时或7小时40分招不到一星，希望提供一个可选开关，遇到“重装”词条时，拉到3小时50分以下进行招募

### 有什么好的想法？

如上

### 其他内容

无

**Comment by ABA2396** [comment]
小车没有单独写招募的逻辑，但是在高级设置里加了个 `手动确认“机械支援”`

**Comment by pein0saga** [comment]
遇到“重装”词条的概率太高了，我觉得完全没必要。否则会导致界面太过凌乱复杂。而且开了先河人家萌新想刷医疗小车、远程小车etc.都要申请加了。

可以先手动检查手动0-3:50，确认完重装词条以后再让MAA自动招余下的

**Comment by coccustbb** [comment]
> 遇到“重装”词条的概率太高了，我觉得完全没必要。否则会导致界面太过凌乱复杂。而且开了先河人家萌新想刷医疗小车、远程小车etc.都要申请加了。
> 
> 可以先手动检查手动0-3:50，确认完重装词条以后再让MAA自动招余下的

加开关的时候当然要把其他小车也加进去呀，提个建议而已，加不加我没权力发言，但说可以”先手动检查“这种话，真的是sb发言

**Comment by pein0saga** [comment]
> 先手动检查

还没开始运行的时候“先手动检查”重装，有的话就3:50，有的话就公招，就是单纯中文字面意思。哪里惹到你了吗？你是不是误解了什么？难道还有什么伤害你的弦外之音不成？

**Comment by ABA2396** [comment]
36acdc89440aef004ab9832856440e1908960c9d 加了个只有3星tag时选择1小时无词条，单选tag做起来就比较麻烦了

**Comment by coccustbb** [comment]
> > 先手动检查
> 
> 我是说“可以”手动，没说命令你必须手动。我也是和你一样平等提建议、发布用户感想而已，和最终决定一点关系都没有。
> 
> 还没开始运行的时候“先手动检查”有没有重装，有的话就3:50公招，就是单纯中文字面意思。你是不是误解了什么？难道还有什么伤害你的弦外之音不成？“手动”和“自动”还有高低贵贱之分？（当然也可能你要运营很多个账号，所以手动非常麻烦引起了你的恼怒。）
> 
> 希望你能维护社区和谐不要人身攻击

我说你家烤肉店里的烤肉分量太少了，吃不饱；你跟我说，你”可以“去隔壁买两个馒头垫垫肚子再来吃烤肉?
我说你家产品质量有问题，用不了多久就坏了；你跟我说，你”可以“多买几个坏了就换着用？
你可以不加量不降价，不是你的目标客户群不做，但不能跟他说这种话

**Comment by coccustbb** [comment]
> > 先手动检查
> 
> 我是说“可以”手动，没说命令你必须手动。我也是和你一样平等提建议、发布用户感想而已，和最终决定一点关系都没有。
> 
> 还没开始运行的时候“先手动检查”有没有重装，有的话就3:50公招，就是单纯中文字面意思。你是不是误解了什么？难道还有什么伤害你的弦外之音不成？“手动”和“自动”还有高低贵贱之分？（当然也可能你要运营很多个账号，所以手动非常麻烦引起了你的恼怒。）
> 
> 希望你能维护社区和谐不要人身攻击

我说你家烤肉店里的烤肉分量太少了，吃不饱；你跟我说，你”可以“去隔壁买两个馒头垫垫肚子再来吃烤肉?
我说你家产品质量有问题，用不了多久就坏了；你跟我说，你”可以“多买几个坏了就换着用？
我说现在环境太差了，找不到好工作赚不到钱；你跟我说，你”可以“把空余的房子车子租出去搞点钱？

提供次一步的解决方案在你看来是好心，别人看起来就是为了忽略他的主要诉求，避重就轻

**Comment by coccustbb** [comment]
> > 先手动检查
> 
> 我是说“可以”手动，没说命令你必须手动。我也是和你一样平等提建议、发布用户感想而已，和最终决定一点关系都没有。
> 
> 还没开始运行的时候“先手动检查”有没有重装，有的话就3:50公招，就是单纯中文字面意思。你是不是误解了什么？难道还有什么伤害你的弦外之音不成？“手动”和“自动”还有高低贵贱之分？（当然也可能你要运营很多个账号，所以手动非常麻烦引起了你的恼怒。）
> 
> 希望你能维护社区和谐不要人身攻击

我说你家烤肉店里的烤肉分量太少了，吃不饱；你跟我说，你”可以“去隔壁买两个馒头垫垫肚子再来吃烤肉?

你说的对，但我是来吃烤肉的还是来吃馒头的？

手动这种方案，来提建议的我是自己想不到吗？

提出来需求可能是解决起来性价比太低，所以不好解决；亦或是非目标客群，所以没必要解决

但这些都不是提一个说了跟没说区别不大的”退而求次”方案的理由
