### ISSUE TITLE
日服适配问题：无法下召唤物“弦惊”，需要适配

### ISSUE THREAD

**Issue by DeanXBH** [MaaAssistantArknights/MaaAssistantArknights#5093]
尝试了国服能够使用的作业，在日服环境下MAA对召唤物“弦惊”无法识别，不会部署

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7067a5f8-0f90-4cc3-93fd-0f54f6c3870c)
