### ISSUE TITLE
内置链接跳转问题

### ISSUE THREAD

**Issue by langlixiaohei** [MaaAssistantArknights/MaaAssistantArknights#5097]
### 说说你遇到的问题？

因为有在使用steam302的本地反代，在302里面设置了GitHub访问的代理，但是之后通过maa的win弹窗查看页面的那个按钮跳转GitHub页面会报非安全链接。自己手动可以进入GitHub。

**Comment by ntgmc** [comment]
没听懂，能详细解释一下吗

**Comment by langlixiaohei** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104672953/25ebd59a-76c9-4de7-a286-b349941fd8e6)
就是这中弹窗，点进去会提示非安全链接
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104672953/86717550-7501-4eb2-a0fe-0eb398a8279a)
就像这样
但是我是可以直接进GitHub的
