### ISSUE TITLE
[iOS]mac方舟版本更新之后maa失效

### ISSUE THREAD

**Issue by EricWangxy** [MaaAssistantArknights/MaaAssistantArknights#5100]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

之前提过一个相同的 今天更新完了之后又出现同样的问题了，重新装了playcover，方舟的ipa，和maa都没法解决，现在maa完全用不了

### 日志文件

找不到

### 截图

<img width="900" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43486704/d8fb356c-57cd-4571-a165-318806b9cc8f">

### 还有别的吗？

m2芯片

**Comment by EricWangxy** [comment]
请务必告诉我mac的asst.log在哪里 我一直找不到

**Comment by EricWangxy** [comment]
刚刚又试了一下maa，发现实用工具和自动战斗都能正常使用，只是一键长草毫无反应

**Comment by 12dora** [comment]
一键长草直接点开始, 同卡在正在运行中, 模拟器无触控操作. 后来去实用工具里选择仓库材料, 点了开始, 又自动继续执行一键长草了

**Comment by EricWangxy** [comment]
确实是这个问题 感谢解答
