### ISSUE TITLE
MAA任务中若过长时间无反应则自动停止任务

### ISSUE THREAD

**Issue by liuyifan-eric** [MaaAssistantArknights/MaaAssistantArknights#5101]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44556003/876df400-947f-4320-98d5-e1a18669a2ac)
如图，00:00的定时任务因各种原因失败，但是任务一直没有停止，导致之后03:00 06:00 等其他时间的定时任务也无法正确开始，导致一天的理智/基建全部浪费

### 有什么好的想法？

如果能在任务卡死一定时间后自动取消任务，那么在下次定时任务中如果成功启动还可挽回部分损失

如果能够尝试重启模拟器进程、重启maa、重试任务则更好，毕竟大多数问题都能靠重启解决

**Comment by ABA2396** [comment]
8f1ac2023cbbbc4662999ea20065b111b41e5555 加了，不知道好不好使）
