### ISSUE TITLE
希望将MAA中的碎文件打包成资源包提高性能

### ISSUE THREAD

**Issue by ModerRAS** [MaaAssistantArknights/MaaAssistantArknights#5102]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在maa里带的模版图片还有任务Json（特指Arknights-Tile-Pos文件夹）太多太碎了，不管是搬运还是解压都很慢。

### 有什么好的想法？

建议将模版图片还有那些任务用Json整合成精灵图或者资源包之类的形式，减少碎文件影响性能的可能。

**Comment by MistEO** [comment]
之前就是整个的 json，20M+，解析太慢了，并且没法增量更新，特地拆开的。而且现在是惰性加载的，基本是最佳性能状态

**Comment by ModerRAS** [comment]
行吧，就是单纯感觉文件太碎了，不管是搬还是删都挺费劲的，看到这种情况我觉得学习一下游戏的资源包的结构挺合适的，增量更新再加个包就行了，不过也无伤大雅就是了，一般也不会没事来回挪，就是第一次下载的时候难受了。
