### ISSUE TITLE
令的弦惊识别不出来

### ISSUE THREAD

**Issue by Noechofu** [MaaAssistantArknights/MaaAssistantArknights#5103]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在自动战斗复制的作业里面一直不放弦惊，看到作业评论区也有类似的问题

### 日志文件

2023-06-09 11:10:51.077
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11701870/asst.log)

**Comment by MistEO** [comment]
看看 cache\avatars 里图是不是错了，先删一下。这个算已知问题，但不知道怎么出现的

**Comment by Noechofu** [comment]
> 看缓存\头像里图不是错了，先删一下。这个算已经知道问题了，但不知道怎么出现的

好的好的，感谢
