### ISSUE TITLE
使用MAA时模拟器CPU占用异常，adb进程疯狂占用上传流量

### ISSUE THREAD

**Issue by a546109781** [MaaAssistantArknights/MaaAssistantArknights#5108]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/7327840/598a014f-a562-42fb-84ee-7200f767d550)
执行的任务是内置保全作业
CPU 12490f 几乎全程占满所有线程线程，停止MMA任务后恢复正常（占用10%-20%）
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/7327840/abe3a61a-86f4-432e-83b1-6f4e6abf28cb)
执行任务时adb一直在上传，不知道是不是正常现象
版本[v4.19.1-rc.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.19.1-rc.1)

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11705372/asst.zip)
之前有没有没注意，今天体感后台挂机浏览器逛B站都变卡才发现

**Comment by ABA2396** [comment]
和模拟器通讯走的本地网络端口，比如把截图什么的传出来也是算上传流量的
