### ISSUE TITLE
完成关卡后卡在选关界面

### ISSUE THREAD

**Issue by qiutongxue** [MaaAssistantArknights/MaaAssistantArknights#511]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8694403/asst.log)

版本：3.3.2 （其实之前的版本在刷***周年活动图***时也遇到过同样的问题）

位置大概在 2022-05-15 13:37 左右，打完 SN-8 后回到了选择关卡界面，就一直不动了：

正常来说打完回到这个界面后会选择进行下一次战斗：

![屏幕截图 2022-05-15 140550](https://user-images.githubusercontent.com/53330358/168459801-0f9f7b7f-867d-41f4-b74d-1759b1a5197e.png)

但是接下来发生的是返回到了选关界面：

![选关界面](https://user-images.githubusercontent.com/53330358/168459573-d51f5344-1173-407d-b71f-c57a46369c77.png)

手动点击关卡后，还是会返回到上图的界面，并一直保持不动。大概 13:45 左右又手动尝试了下（这次是先选了 SN-8，在返回到选关界面后立刻再点一次 SN-8）总算进入战斗了

然而打了两把后，在 13:50 分之后又出了同样的问题

![屏幕截图 2022-05-15 135836](https://user-images.githubusercontent.com/53330358/168459347-8ba121eb-65a1-47e1-b2dd-aa6aa4c44c58.png)

**Comment by MistEO** [comment]
愚人号明天就结束了，摆烂了_(:з」∠)_

**Comment by ABA2396** [comment]
> 愚人号明天就结束了，摆烂了_(:з」∠)_

7 days ago 的 comment 摆到今天——
