### ISSUE TITLE
台服傀影肉鸽开局无法选择助战

### ISSUE THREAD

**Issue by Yesra0506** [MaaAssistantArknights/MaaAssistantArknights#5110]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在设置了“开局干员使用助战”、“可以使用非好友助战”并指定了某个干员如“棘刺”后开启肉鸽，发现并没有使用助战，而是照常执行肉鸽，选择自己的干员。 肉鸽运行期间全程正常运行，没有收到类似无法识别助战等的任何错误信息。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11706515/asst.log)

问题大约从2023/6/9/20:10后出现

### 截图

![A2162A69-EBB7-49DB-9203-EA51C04574E9](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136087653/65dbf54d-bfcd-427d-a8d5-7a1e96f1d9ac)
![4CDBA3F9-ACDB-4AD7-8E61-54471FCD6259](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136087653/9d050874-2727-4503-afef-01b2f93410c8)
![6FB97EFF-180A-4B8A-9311-2DE6032202F6](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136087653/0d31c44e-6772-4eda-802e-5690ab71aae3)
![BEF41C9C-6407-4C27-A44E-C41A49495763](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136087653/c8075989-a641-45f8-9acf-f9820d3b0f4e)

### 还有别的吗？

使用蓝叠模拟器5
windows10系统

**Comment by stupidegg8576** [comment]
請問這個問題修復了嗎?
v4.19.2繁中服自動肉鴿無法使用好友助戰，指定初始幹員也失敗
看了一下之前日服也有人遇到相同問題
似乎是task.json中沒有RoguelikeChooseSupportBtnOcr, RoguelikeRefreshSupportBtnOcr

目前繁中服 \resource\global\txwy\resource\task.json 沒有上面幾個task
如果要把這些功能搬到繁中服
把\resource\task.json對應的RoguelikeChooseSupportBtnOcr之類的項目修改至\resource\global\txwy\resource\task.json就可以了嗎?
