### ISSUE TITLE
*强烈建议*增加防止系统休眠的功能

### ISSUE THREAD

**Issue by pingplug** [MaaAssistantArknights/MaaAssistantArknights#5114]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

虽然大家都说模拟器已经实现了防止系统休眠的功能，但是确实有部分模拟器在部分系统环境下无法实现该功能，且系统设置也出现问题。下面是log（不知道为什么没有gui的log）
![系统设置](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6712475/71129829-c85e-4b1d-be0d-9072adc84512)
![模拟器设置](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6712475/346e1957-47e3-4422-a706-2c466d0cad5e)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11710730/asst.log)
可以看到在凌晨3点40分左右系统进入休眠，且在第二天手动启动电脑时继续，这排除了自动更新造成的重启等可能性。

### 有什么好的想法？

我不太清楚这是怎么实现的，但是现有的一些模拟器和系统设置确实不起作用。

**Comment by pingplug** [comment]
系统信息如下：
零刻 SER5
  CPU：R5-5600H
  内存：16GiB
  系统：Windows 11 专业版 22H2
模拟器：夜神模拟器 V7.0.5.7（当前最新版，因为其他模拟器有掉帧bug所以无法换）
明日方舟为B服版本

**Comment by pingplug** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1550#issuecomment-1214159641
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2266#issuecomment-1312919095

由于这两个设置在特殊环境下失效，强烈建议Maa来实现这个功能

**Comment by liuyifan-eric** [comment]
个人意见，如果模拟器的防止休眠都会有bug，那又怎么才能保证maa写的就不会失效呢？是否太为难大佬们了

**Comment by SherkeyXD** [comment]
#7218
