### ISSUE TITLE
Hyper-V 蓝叠初次启动无法连接

### ISSUE THREAD

**Issue by yoooowi** [MaaAssistantArknights/MaaAssistantArknights#5118]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Windows 10 / Bluestacks 5.9.350.1035 N64 （国际版）/ MAA v4.19.1

之前一直能顺利使用。在某次MAA更新后开始出现连接问题。

启动设置：
启动MAA后自动运行
启动MAA后自动开启模拟器

前提条件1：
模拟器已经启动，游戏正在运行中

问题现象1：
启动MAA，一键长草自动运行。左上角能正确显示模拟器端口号。
GUI log 显示“等待模拟器启动时间（秒）: 60s”，并进入倒数。
选择停止任务并重新开始，MAA能够正确连接模拟器并开始任务。

前提条件2：
关闭模拟器，杀死ADB进程

问题现象2：
启动MAA，一键长草自动运行。模拟器被唤醒。左上角显示的是模拟器上次启动时的端口号。
停止任务并重新开始后MAA依旧无法检测到连接。

进入连接设置勾选自动检测连接并开始任务后左上角端口号更新为当前模拟器ADB端口，能够正常开始任务。

### 日志文件

问题1发生时间：2023-06-10 01:15:59

问题2发生时间：2023-06-10 01:27:30

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11711598/asst.log)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11711601/gui.log)

**Comment by yoooowi** [comment]
关于第2个问题，文档中有提到勾选自动检测和每次重新检测，但#4616提到不要勾选。不论是否勾选，MAA启动时左上角的端口号都是模拟器上次使用的端口号，而不是该次唤醒的端口号。

**Comment by SherkeyXD** [comment]
> 关于第2个问题，文档中有提到勾选自动检测和每次重新检测，但 #4616 提到不要勾选。不论是否勾选，MAA启动时左上角的端口号都是模拟器上次使用的端口号，而不是该次唤醒的端口号。

#4616 中提到的做法已经过时，请以最新文档为准，即同时勾选 `自动检测连接` 和 `每次重新检测`

第一个问题貌似是因为 MAA 不会检测是否有已经启动的模拟器进程，而是直接启动一个新的

关于第二个问题，试试同时勾选 `自动检测连接` 和 `每次重新检测` ，如果还是出现问题再发一次log
