### ISSUE TITLE
自动战斗无法部署 山

### ISSUE THREAD

**Issue by yuanze31** [MaaAssistantArknights/MaaAssistantArknights#5119]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗是部署山直接略过，作业站已有多人反映出现此问题

### 日志文件

14：40左右
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11711780/asst.log)

### 还有别的吗？

Mumu模拟器 Android 6.0.1
Windows 10 版本22H2(操作系统内部版本19045.2965)
MAA v4.19.1 内测版检查无更新（2023.6.10 2:50）
使用作业：maa://23854 ， maa://23863

**Comment by hifuclub** [comment]
主要问题是maa把山和杏仁搞混了，目前有个应急的办法，把补充低信赖干员关了，然后清空avatars文件夹，保险起见再给山换个皮肤，亲测有效

**Comment by hifuclub** [comment]
> 主要问题是maa把山和杏仁搞混了，目前有个应急的办法，把补充低信赖干员关了，然后清空avatars文件夹，保险起见再给山换个皮肤，亲测有效
关补充低信赖干员的原因是，杏仁是刚出的角色，如果开启这个功能，大概率会被选进队伍里

**Comment by hifuclub** [comment]
主要问题是maa把山和杏仁搞混了，目前有个应急的办法，把补充低信赖干员关了，然后清空avatars文件夹，亲测有效
或者给山换个皮肤，亲测“读者”不会识别错
关“补充低信赖干员”的原因是，杏仁是刚出的角色，如果开启这个功能，大概率会被选进队伍里
