### ISSUE TITLE
基建制造站干员选择出问题了？

### ISSUE THREAD

**Issue by UITZhang** [MaaAssistantArknights/MaaAssistantArknights#5122]
### 说说你遇到的问题？

不知道发生什么事，制造站里断罪夜烟这种只加书/金的都不上了，宁愿上个+15%的

刚刚发现，四舍五入这几天亏了一个亿

**Comment by ABA2396** [comment]
![IMG_20230610_205229.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/6f15d89a-b878-4ada-877a-66fe04861898)
