### ISSUE TITLE
制造站干员自动选择有问题？

### ISSUE THREAD

**Issue by UITZhang** [MaaAssistantArknights/MaaAssistantArknights#5123]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

不知道发生什么事，制造站里断罪这种只加书都不上了，宁愿上铅踝泡普卡kkdy这种

而且圣葬跟红云组的计算有问题，宁愿用豆苗都不用他

血亏，速修

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11712465/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115169661/dd2ccfb2-df42-4926-849c-df3594362d76)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115169661/b676a3c7-da88-4a2f-97a0-a3a45f5228a1)

**Comment by YASIN-e** [comment]
除了制造站录像不使用录像组外，目前对于红云组和泡泡组的识别也比较差。

**Comment by pengyang7881187** [comment]
我红云组用于经验卡也不会自动用帕拉斯，它宁愿用黑角；然后经验卡其他制造站也不会用断罪者，它宁愿用标准化

**Comment by MistEO** [comment]
找到问题了，YJ 不干人事，新出了个 Bskill_man_exp4 ![Bskill_man_exp4](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/964eda09-c1d7-4400-a32c-4498cfd76a83) 效率反而是最低的

这是以前的 1 2 3

![Bskill_man_exp1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/62e049fd-d024-4b03-89a1-8809a86bc621)
![Bskill_man_exp2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/174318fa-4f17-4932-9377-cd5383fab049)
![Bskill_man_exp3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/d72a0d17-7093-4bae-b9a1-4ce18e78b987)
