### ISSUE TITLE
日服：水月肉鸽“不期而遇”节点事件识别有问题

### ISSUE THREAD

**Issue by 1ou6x1n7** [MaaAssistantArknights/MaaAssistantArknights#5126]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

图1这类单选项的，直接没有任何操作。日志时间大概是2023年6月11日01:30左右。

图2这类多选项的，它会几个选项反复横跳就是不选择。日志时间大概是在2023年6月11日 01:38分左右。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11712992/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11712993/gui.log)

### 截图

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46951316/aff3630e-80dd-41c6-9217-7ec5e9ccbb97)
![4](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46951316/fa5ab063-9c44-429c-9797-baac1881a166)

**Comment by liuyifan-eric** [comment]
按理说这个已经修过了我这里也没有问题。你重装下MAA试试？（可以保留config文件夹这样之前的配置就都还在）

**Comment by 1ou6x1n7** [comment]
> 按理说这个已经修过了我这里也没有问题。你重装下MAA试试？（可以保留config文件夹这样之前的配置就都还在）
重新下载[v4.19.2-alpha.1.d030.g00135751]版本测试后还是一样的，不知道什么情况了。
日志大概在17:10:40

![QQ截图20230615171224](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46951316/13176652-0d0a-4f70-8cf9-dc3f44cafca7)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11755460/asst.log)

**Comment by 1ou6x1n7** [comment]
> 按理说这个已经修过了我这里也没有问题。你重装下MAA试试？（可以保留config文件夹这样之前的配置就都还在）

顺便测了下国服，国服是没问题的。

**Comment by HUAZIB** [comment]
我试了一下也是一样的情况  重新下也是一样

**Comment by estiyerhard** [comment]
夜神模拟器和国际版蓝叠尝试过之后也是无法选择不期而遇，尝试了完全重装4.19.2 beta1版也没有解决

**Comment by Ryoj1** [comment]
JP服 MUMU模擬器也嘗試過 不期而遇一定會卡選擇
已重裝4.20.0版也沒有解決

**Comment by wallsman** [comment]
This issue
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/5749

Ver 4.21.0
Can select and go choice.
I use Bluestacks.
