### ISSUE TITLE
希望mac繁中服能够自动选择登陆方式

### ISSUE THREAD

**Issue by oracle91** [MaaAssistantArknights/MaaAssistantArknights#5129]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

繁中服开始唤醒会卡在登陆界面，需要手动选择登陆方式。

### 有什么好的想法？

希望能在设置里选择登陆方式，自动执行“开始唤醒”任务。

### 其他内容
![screenshot_20230611_093455](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/24630854/ce0e3fa0-c588-45f1-8c72-aa41ae79da25)

**Comment by liuyifan-eric** [comment]
繁中服不会保留登录信息吗？每次都需要重新选择吗？

**Comment by oracle91** [comment]
在其他客户端登录过之后就会需要重新选择，有的时候时间长了也需要重新选

**Comment by vonnoq** [comment]
> 在其他客户端登录过之后就会需要重新选择，有的时候时间长了也需要重新选

請問你是選擇用哪個方式登入？google？
