### ISSUE TITLE
链接地址输入后无法清除已输入内容

### ISSUE THREAD

**Issue by NeoArcadia** [MaaAssistantArknights/MaaAssistantArknights#5132]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

操作步骤：
1、设置-链接设置-链接地址输入框内输入内容后，选择任意其他控件自动提交内容
2、清除链接地址输入框内容，选择任意其他控件
现象：链接地址输入框中的内容恢复到之前填写的状态
预期：链接地址输入框中的内容清除并保存

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11714603/asst.log)

**Comment by ABA2396** [comment]
所以为啥要清除
