### ISSUE TITLE
ADB链接失败

### ISSUE THREAD

**Issue by yukihana111** [MaaAssistantArknights/MaaAssistantArknights#5133]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 遇到了问题
对路径“adb.exe”的访问被拒绝。
解决方案
出现未知错误
详细信息
System.UnauthorizedAccessException: 对路径“adb.exe”的访问被拒绝。
   在 System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   在 System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ReplaceADB>d__445.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11714903/asst.log)

### 还有别的吗？

WIN11,MUMU12

**Comment by ABA2396** [comment]
这是点了强制替换adb吧，mumu是管理员权限启动的，你得用管理员权限启动maa或者关了模拟器再替换
