### ISSUE TITLE
希望在没有勾选使用理智药剂时，也可以消耗源石刷取材料

### ISSUE THREAD

**Issue by Derekzhym** [MaaAssistantArknights/MaaAssistantArknights#5135]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前刷理智的“吃源石“选项必须要在”吃理智药“的选项打钩、且数量至少为1时，才能勾选。但是实际使用时，完全存在没有理智药，只是单纯想碎石刷取副本的情况。带来了一些操作上的不方便

### 有什么好的想法？

将”吃源石“和”吃理智药“二者的关联取消。游戏本身就自带了有理智药先吃理智药的机制，吃理智药也并不是吃源石的先决条件

**Comment by ABA2396** [comment]
这样就会有人在有理智药的情况下想只用源石不用理智药，然后因为先打开的界面是理智药所以就直接结束了。没有理智药的时候随便填个数就行了

**Comment by Derekzhym** [comment]
好吧，我以为先消耗理智药是常识。理解了，感谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月12日 00:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [MaaAssistantArknights/MaaAssistantArknights] 希望在没有勾选使用理智药剂时，也可以消耗源石刷取材料 (Issue #5135) |

这样就会有人在有理智药的情况下想只用源石不用理智药，然后因为先打开的界面是理智药所以就直接结束了。没有理智药的时候随便填个数就行了
