### ISSUE TITLE
基建排班中晓歌干员无法被识别

### ISSUE THREAD

**Issue by HCO168** [MaaAssistantArknights/MaaAssistantArknights#5137]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在自定义基建自动排班中，晓哥干员无法被正常识别并选中，不管是在会议室中还是在宿舍中。这个时候MAA会重复的在干员列表中从头划到尾，并一直卡在那一步。最后只得自己选择。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11716868/asst.zip)
问题出现时间：2023.6.11每一次执行自动排班的时候（尤其是0点和12点以及22点的时候）

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134460467/c5b60d78-91fa-4029-a54f-bcff1aa4b3b2)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134460467/c5ad3822-b42e-48ac-b32f-85b992b73f45)
这个游戏截图可能不太准确，是我在运行后的示意图
在当时截图的晓哥并没有在基建中休息
请谅解

### 还有别的吗？

模拟器：蓝叠5
游戏：官服
操作系统：Windows11
版本：v4.19.1
连接配置：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134460467/dbb084f5-6f22-4cce-aec1-b16f0e116e6b)
基建配置：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134460467/4aac2ce3-53d0-4742-a9cb-2dfe0d8615cf)

**Comment by ABA2396** [comment]
你看看她叫啥

**Comment by HCO168** [comment]
> 

有晓哥的地方就有你是吧

**Comment by HCO168** [comment]
> 你看看她叫啥

你别关问题啊

**Comment by ABA2396** [comment]
> > 你看看她叫啥
> 
> 你别关问题啊

你看看她叫啥

**Comment by neko-para** [comment]
@HCO168 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/26452623/1df3b62a-aec5-479b-ae19-904cd8022d7d)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/26452623/9ccdc5fc-c746-4db2-b0fa-88bf6829608c)

**Comment by HCO168** [comment]
好吧，所以说原来是我打错字了啊

**Comment by neko-para** [comment]
你不是都看过前面的问题了...一样的问题还能再问两次

**Comment by HCO168** [comment]
我以为你是说他的问题打错字了，所以我又把晓哥改成晓哥又发了一遍，对不起

**Comment by HCO168** [comment]
> 你不是都看过前面的问题了...一样的问题还能再问两次
真的对不起了，因为自己的疏忽大意浪费了你们的时间
