### ISSUE TITLE
MuMu模拟器12 v3.4.4 (1632)「完成后退出模拟器」功能失效

### ISSUE THREAD

**Issue by RyanSaul** [MaaAssistantArknights/MaaAssistantArknights#5141]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MuMu模拟器12 最新版本「完成后退出模拟器」功能失效，出现运行失败的弹窗，影响下一次定时任务
模拟器及 MAA（公测版）均已升级到最新版，模拟器版本高于文档-模拟器支持中使用「完成后退出模拟器」功能的最低版本3.3.7
该模拟器版本的上一个版本没有出现该bug
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16830734/1e1df856-63a8-4d0a-89a7-0e6b27c0524a)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11720196/asst.log)
日志末尾即为结束自动任务的时间点

### 还有别的吗？

操作系统：Windows 11 专业版 Insider Preview 23475
模拟器：MuMu模拟器 12 v3.4.4 (1632)
MAA：v4.19.1

**Comment by ABA2396** [comment]
发下gui.log

**Comment by RyanSaul** [comment]
> 发下gui.log

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11721068/gui.log)

**Comment by ABA2396** [comment]
没啥有用的信息，这里加了点日志，可以看看哪儿出了问题
https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/5242420044

**Comment by sakuhoya** [comment]
我也是这个问题，这是内测版加了日志后的gui，请大佬看看是什么问题
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11728593/gui.log)

**Comment by RyanSaul** [comment]
> 没啥有用的信息，这里加了点日志，可以看看哪儿出了问题 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/5242420044

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11729808/gui.log)

**Comment by ABA2396** [comment]
看日志是正常调了mumu的控制台api，可能是他们那里的问题，我去问问

**Comment by MistEO** [comment]
是 mumu 的问题，之前和他们沟通过，可以直接在模拟器里反馈给 mumu

**Comment by RyanSaul** [comment]
最新版 v3.4.7 (1681) 已修复该问题
