### ISSUE TITLE
【bug】最新内测版肉鸽干员练度识别有问题，会招募完全没有练度的1级干员。

### ISSUE THREAD

**Issue by Angelenx** [MaaAssistantArknights/MaaAssistantArknights#5143]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在自动肉鸽中，招募时有时候会选择完全没有练度的1级干员。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11720898/asst.log)

**Comment by RiseFive0** [comment]
确实，辅助能直接选白板波登可
