### ISSUE TITLE
增加一个下载新版本之后,MAA自动解压安装的选项.

### ISSUE THREAD

**Issue by kiritoxie** [MaaAssistantArknights/MaaAssistantArknights#5145]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前我使用windows的计划任务，配和电脑的自动睡眠，来达到每隔几个小时MAA就在后台运行的效果，同时不会打扰我正常使用电脑，但是如果出现新版本的话，MAA会卡在是否安装新版本的窗口提示，需要我手动去确认，有时候我会没有及时看到这个选项,导致MAA无法继续运行.

### 有什么好的想法？

在软件更新的界面新增一个选项，让MAA自行安装新版本，而不是询问我是否进行安装.

**Comment by ABA2396** [comment]
自动安装还可能会遇到正在执行任务或者安装后重启因为选了启动后直接运行等功能再次开启任务，感觉不是很好处理。现在这个弹窗询问应该是异步的，应该不会卡住任务的执行吧？不手动确认会无法继续运行吗？

**Comment by kiritoxie** [comment]
经过几天的尝试,MAA在下载更新之后, 到下一次再运行时会进行自动安装, 没什么问题了.
