### ISSUE TITLE
希望基建换班可以加入加工站

### ISSUE THREAD

**Issue by 2vch** [MaaAssistantArknights/MaaAssistantArknights#5148]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

基建换班时加工站不能换班，想触发缪缪和大哥的基建技能的话，宿舍位置比较紧张，最好是可以放到加工站内

### 有什么好的想法？

希望基建换班"rooms"取值加入加工站，这对我真的很重要！

**Comment by MistEO** [comment]
#4610

**Comment by MistEO** [comment]
fixed
