### ISSUE TITLE
助手崩溃

### ISSUE THREAD

**Issue by IceWindy233** [MaaAssistantArknights/MaaAssistantArknights#515]
![`WR9O{`%L1D1X4_1B) 4NJ1](https://user-images.githubusercontent.com/40712698/168563460-67e117a1-26f2-4727-b328-29dd19599c44.png)

点开出现这样界面，然后就崩溃，目录下没有出现log文件。

![9R)@W4KV5`IYI V(5%} $VT](https://user-images.githubusercontent.com/40712698/168562829-c5ce9c4f-f29e-456f-84cc-b09e1d77f450.png)
![image](https://user-images.githubusercontent.com/40712698/168562847-d94d9015-0f80-4daa-b5c5-488e32180254.png)

C++运行库和.NET运行库都已经安装了，CPU为i7-11800H，指令集没有问题。
系统版本Windows11 22616.100。

**Comment by IceWindy233** [comment]
好的，我有空尝试一下。
个人感觉有可能是C++运行库的版本原因，我在之前是可用的，在我更换了C++运行库版本后就崩溃了，可用到崩溃期间，运行环境的改变似乎只有C++运行库，但是我试图安装过mircosoft官网最新的C++运行库，没有效果（（

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/828 可以按这个尝试一下

**Comment by IceWindy233** [comment]
> #828 可以按这个尝试一下

前两个方式尝试了并没有效果，第三个方法没找到`gui.json`文件，重新下载解压后依然看到这个文件。断网那个方法试了，好像从白屏到崩溃更快了（（（
