### ISSUE TITLE
制造站换班时 不选取作战记录效率加成类干员而优先选择标准化技能干员 导致效率偏低

### ISSUE THREAD

**Issue by Joyce-Ethene** [MaaAssistantArknights/MaaAssistantArknights#5152]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最近一两天发现基建技能图标带EXP的干员不会被抓去上班了
国服、日服、国际服都是这样的情况
如果是单个房间效率最高原则，EXP标签的干员组合应该是效率最高的，现在会被换下来

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11735145/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11735147/gui.log)

时间：13:59-14:01

### 截图

换班前：
![QQ图片20230613140219](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131970654/2a52bb4d-f907-45ff-a920-797708a54d5c)

换班后：
![QQ图片20230613140223](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131970654/65419155-640d-4216-81c6-c328aa204e77)

时间：
![QQ图片20230613140226](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131970654/a2cac4c1-e2ec-4f12-9982-0b60a32c229d)

**Comment by MistEO** [comment]
找到问题了，YJ 不干人事，新出了个 4 ![Bskill_man_exp4](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/964eda09-c1d7-4400-a32c-4498cfd76a83) 效率反而是最低的

这是以前的 1 2 3

![Bskill_man_exp1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/62e049fd-d024-4b03-89a1-8809a86bc621)
![Bskill_man_exp2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/174318fa-4f17-4932-9377-cd5383fab049)
![Bskill_man_exp3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/d72a0d17-7093-4bae-b9a1-4ce18e78b987)

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5123

**Comment by Joyce-Ethene** [comment]
果然是因为圣葬hhh
