### ISSUE TITLE
夜神模拟器安卓9 连接不成功 替换adb也出现问题

### ISSUE THREAD

**Issue by virdmark** [MaaAssistantArknights/MaaAssistantArknights#5155]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 遇到了问题
对路径“adb.exe”的访问被拒绝。
解决方案
出现未知错误
详细信息
System.UnauthorizedAccessException: 对路径“adb.exe”的访问被拒绝。
   在 System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   在 System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ReplaceADB>d__445.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11736363/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11736364/asst.log)

### 截图

不使用adb时![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94534273/1094c723-3fca-49a2-ad84-34e060bc9ab3)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94534273/c139d0b0-7f51-4cad-a90b-1b8d7af755b7)

### 还有别的吗？

模拟器版本: 7.0.5.7023-9.0900230424
安卓版本: Android 9(64 bit)
系统版本: Windows10-64bit-16cpu
电脑型号: LENOVO-82JQ
CPU: AMD Ryzen 7 5800H with Radeon Graphics         
总内存: 31.9 GB
可用内存: 19.7 GB
是否开启VT: 开启
渲染模式: OpenGL+
OpenGL版本: 4.6.0 NVIDIA 532.03
OpenGL渲染: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
是否独显: 开启
显卡1: NVIDIA GeForce RTX 3060 Laptop GPU
显卡2: AMD Radeon(TM) Graphics
防火墙: 开启(推荐关闭)
安装路径: D:\Nox\bin
日志文件路径: C:\Users\kililenko\AppData\Local\Nox
模拟器磁盘大小: 总共 128G, 剩余 111G

**Comment by SherkeyXD** [comment]
![Screenshot_2023-06-14-09-32-12-984_com.microsoft.emmx-edit.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57581480/8820ac00-c2d6-47f0-a737-0a58788a691c)

这里应该填 adb 路径而不是模拟器路径
