### ISSUE TITLE
傀影肉鸽-鲍勃酒品关卡干员摆放逻辑

### ISSUE THREAD

**Issue by Ghost1496** [MaaAssistantArknights/MaaAssistantArknights#5158]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

远程干员在左路朝右摆放这个完全不合理啊。。。虽然本质上也是挂机并不是一定要打过，但是还是希望能够检查一下

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11744939/gui.log)
[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11744951/asst.-.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/130331821/9915563f-76d9-4ac3-8d97-8869c4469ecb)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/130331821/2096d56f-1c93-4322-a6be-775a0c3c02e0)

**Comment by Lancarus** [comment]
已修复[v4.21.1-alpha.1.d031.g7d3e7a443](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v4.21.1-alpha.1.d031.g7d3e7a443)
