### ISSUE TITLE
mumu12模拟器，运行“完成后退出模拟器”，模拟器无法正常退出

### ISSUE THREAD

**Issue by waooooooooooo** [MaaAssistantArknights/MaaAssistantArknights#5164]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

显示虚拟机异常退出，请重启模拟器

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11752740/asst.zip)
在最后

### 截图

![ju7iu31d](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136671400/733b1075-d38f-4508-82ba-a0b46c9ffacd)

**Comment by ABA2396** [comment]
#5141
