### ISSUE TITLE
信用商店可否选择跳过加急许可

### ISSUE THREAD

**Issue by curvit** [MaaAssistantArknights/MaaAssistantArknights#517]
从不加速的老咸鱼表示仓库这东西比招募券还多

**Comment by ABA2396** [comment]
详细介绍有说

从左到右依次买，但不会买 碳 和 家具零件 。有需要的同学可自行修改 resource/tasks.json 中 CreditShop-NotToBuy - text 字段，自定义不买的物品。后续版本会尝试开放界面选项

新版本已经加了，还没开放

**Comment by ABA2396** [comment]
好像新版本已经发了（x）更新看下

**Comment by curvit** [comment]
已解决，感谢

**Comment by curvit** [comment]
> 详细介绍有说
> 
> 从左到右依次买，但不会买 碳 和 家具零件 。有需要的同学可自行修改 resource/tasks.json 中 CreditShop-NotToBuy - text 字段，自定义不买的物品。后续版本会尝试开放界面选项
> 
> 新版本已经加了，还没开放
已解决，感谢
