### ISSUE TITLE
建议加入阻止重复启动的功能

### ISSUE THREAD

**Issue by MisterCoBen** [MaaAssistantArknights/MaaAssistantArknights#5171]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

启动时可能因为误操作多次点击导致重复开启多个MAA的GUI界面，可能导致卡死或其它错误

### 有什么好的想法？

建议运行前加入是否已启动的检测

**Comment by SherkeyXD** [comment]
maa 本身就是支持多开的，这样可以方便需要同时挂多个模拟器的人
