### ISSUE TITLE
台服基建無法識別幹員

### ISSUE THREAD

**Issue by lillhot** [MaaAssistantArknights/MaaAssistantArknights#5177]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

台服基建突然找不到自定義好的幹員了
自定義配置沒有變過 以前可以正常運行

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11766100/asst.log)

**Comment by yuanlk** [comment]
我也遇到同樣問題
