### ISSUE TITLE
部分已有干员无法识别

### ISSUE THREAD

**Issue by evanxyf** [MaaAssistantArknights/MaaAssistantArknights#5178]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

实际上除洋灰外，其余干员全部都有。
耀骑士临光、归溟幽灵鲨、寒芒克洛丝无法识别

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11766107/debug.zip)

### 截图

![识别结果](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/5361796/b1ef9e09-f4d9-4b2d-a3dd-e92e1ec0c65a)
[已有干员截图.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11766127/default.zip)

### 还有别的吗？

模拟器：Bluestacks 5.11.42 P64 国际版

**Comment by ABA2396** [comment]
特别关注的标会影响识别，没啥好办法
