### ISSUE TITLE
干员识别功能存在缺陷

### ISSUE THREAD

**Issue by zl-zhou20** [MaaAssistantArknights/MaaAssistantArknights#5179]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

当在干员列表中开始该功能时，将只能识别从右向左滑动之后的干员，无法识别之前的干员。此外，出现无法识别归溟幽灵鲨的问题，此前issue已经提到过。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11767340/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11767341/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/132467867/b9a3168d-a677-4ea3-8140-3dd6072a6d1b)

**Comment by RimuruChan** [comment]
不只是此功能，自动战斗的干员识别也出现问题，无法选中部分干员
