### ISSUE TITLE
国际服无法开始肉鸽，两个主题都是

### ISSUE THREAD

**Issue by Tr-AIL** [MaaAssistantArknights/MaaAssistantArknights#5181]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

开始之后，选水月肉鸽一直在主界面和肉鸽主界面来回跑就是不开始，选傀影肉鸽一直在肉鸽选择界面和主界面来回跑（傀影肉鸽无法切换，会直接卡在水月肉鸽页面十几秒然后回到主界面

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11768405/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11768412/gui.log)

**Comment by lusensama** [comment]
是不是没有选择难度？你试试帮它选择一次难度再进看看？

**Comment by todanielwang** [comment]
我也遇到了同样的bug，不管是水月肉鸽还是傀影肉鸽，不管是刷等级，源石锭，还是烧开水，都会在选择分队之后卡在选择初始干员的页面，过一段时间之后自动退出并关闭肉鸽后再开第二把。盲猜是选择干员界面干员识别出了问题，但在尝试使用助战干员选项后还是同样的卡死，并没有进入选择助战干员的页面。
