### ISSUE TITLE
明日方舟新版登录ui下防沉迷账号在登录时会卡死

### ISSUE THREAD

**Issue by 2298353346** [MaaAssistantArknights/MaaAssistantArknights#5187]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天我用MAA挂方舟时，发现卡死在防沉迷界面，而不是像以前一样会不断进行重登。卡死在这个界面会导致我不能为了节约时间提前打开MAA让它登录，必须要20：00之后。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11779068/gui.log)

### 截图

![Screenshot_2023 06 17_19 43 34 683](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90997386/1e3414e8-2081-4585-9506-9717bb0aa45a)

**Comment by ntgmc** [comment]
草，防沉迷账号还要用maa

**Comment by 2298353346** [comment]
> 额，那建议去设置里加上八点的定时启动

谢谢，才知道有定时启动
