### ISSUE TITLE
自动战斗无法选择已收藏干员

### ISSUE THREAD

**Issue by junzhi-cn** [MaaAssistantArknights/MaaAssistantArknights#5188]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗开始是无法识别已收藏的干员，会反复滑动试图识别，当我把需要的干员从收藏中移除时就能正确识别了，怀疑是干员名称左侧的收藏符号干扰

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11779502/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11779503/gui.log)
大约在12点前后

**Comment by ntgmc** [comment]
这个没办法修复，ocr尽力了

**Comment by MistEO** [comment]
谁说修不了的。。
