### ISSUE TITLE
在识别掉落物时会闪退。

### ISSUE THREAD

**Issue by Skady42** [MaaAssistantArknights/MaaAssistantArknights#519]
关卡结束后再识别掉落材料时会崩溃，直接关掉界面。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8708995/asst.log)

**Comment by MistEO** [comment]
已知问题，正在重写了 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/507

**Comment by zzyyyl** [comment]
挑一个issue pin一下？这两天好多人说这个
