### ISSUE TITLE
自动更新问题

### ISSUE THREAD

**Issue by Eziodeng** [MaaAssistantArknights/MaaAssistantArknights#5190]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

似乎自动更新出现问题，反复下载并解压失败

### 日志文件

时间点大致位于 2023-06-18 11:52:35 开始，尝试下载OTA包并反复询问重启更新
但是更新失败，加proxy更新也失败
之后我手动解压OTA包覆盖文件更新成功
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11780608/gui.log)

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49717931/a6fa72fb-33a5-484c-b263-c7e1061324e1)
上图是对应的更新配置

**Comment by AnnAngela** [comment]
经验证，是由于更新服务其中一家CDN提供商配置出错导致无法返回正确的更新包，现已修复。
