### ISSUE TITLE
增加账号切换功能

### ISSUE THREAD

**Issue by hzz66229** [MaaAssistantArknights/MaaAssistantArknights#5193]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有一个大号和小号，希望能在登陆时根据手机号切换

### 有什么好的想法？

识别手机后四位定位账号

### 其他内容

无

**Comment by SherkeyXD** [comment]
Dulplicate of #5077
