### ISSUE TITLE
保全卡住不动

### ISSUE THREAD

**Issue by zoe4477** [MaaAssistantArknights/MaaAssistantArknights#5197]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

保全一直卡在这个界面不动
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38827851/0fee261c-2cc8-4c80-b474-aeb269f48940)

### 日志文件

[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11781828/log.zip)

**Comment by MistEO** [comment]
缓存错了，搞不懂为啥会发生，重启下 maa 应该就行了
