### ISSUE TITLE
作业自动编组在极端的需求情况下会无限循环卡死

### ISSUE THREAD

**Issue by MirrorCubeSquare** [MaaAssistantArknights/MaaAssistantArknights#5199]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

作业例：本期活动的EX8攻略
表现：会在选取十名干员之后，第11名干员是唯一一个术士羊
然后自动编组无限循环（见截图）
=============以下是个人推测===============
BUG原因：第一屏10个选完的干员占满，导致自动编组在初始判定时全屏没有一个有效的干员，
默认自动编组逻辑是通过切换干员类别尝试刷出来，但在选满十人的情况下无法满足）
于是会无限在切换干员类别上卡死

解决方案：
根除方法我觉得是应该是在选取了10人以上后，下一个类别的干员强制向左拖屏
缓解方法是自动编组时按照每一类别需求干员数量由低到高决定编组顺序，但是遇到极度极端的作业（例如6种类别干员各2名的12人满编作业）时应该还会无限循环

### 日志文件

[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11782001/asst.-.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11782002/gui.log)
涉及到这次BUG的时间节点
23：36：29左右开始

然后不晚于23：38：28，因为这个时间点是我手动编队以后重开的记录

### 截图

![Screenshot_20230618-235542](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/1549131/071dc3df-ea9f-4462-973b-9af6baa2553a)
![Screenshot_20230618-235548](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/1549131/fbfdcf0e-df58-4b2b-b1f7-4ffae62f6a5e)
以上是无限循环的两个画面

**Comment by MirrorCubeSquare** [comment]
[【当前活动-EX更新】空想花庭.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11782057/-EX.zip)
（忘记扔触发BUG的作业了，是这个包里的EX8突袭）

**Comment by hifuclub** [comment]
同样的问题

**Comment by Rbqwow** [comment]
同作业 可复现
缓解方案为收起右侧职业分类

**Comment by MirrorCubeSquare** [comment]
> 

想了一想这样确实可以，但是现在自动编组应该是依赖职业分类进行选人的吧？
怎么感觉没啥简单清爽的解决方案呢

**Comment by MistEO** [comment]
新版修了
