### ISSUE TITLE
点赞接口序列化两次导致后端报错

### ISSUE THREAD

**Issue by dragove** [MaaAssistantArknights/MaaAssistantArknights#5201]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/30338f7d3021d4baf41b5c5556293287b00a63b6/src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs#LL574C1-L574C1

@ABA2396 

不会C#，代码看起来是一个对象序列化成json字符串后调用的方法里有序列化了一次，导致传给后端的是一个字符串而不是json

**Comment by ABA2396** [comment]
我看了下应该只是把双引号转成了\u0022，要的是怎么样的格式？

**Comment by MistEO** [comment]
草那之前是怎么跑起来的.jpg
