### ISSUE TITLE
国际服可在标题和备选理智处选择当期活动关卡，但选择关卡中没有

### ISSUE THREAD

**Issue by RiichiTsumo** [MaaAssistantArknights/MaaAssistantArknights#5205]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，详见截图

### 日志文件

大概不需要

### 截图

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/77238633/a91e1390-bb3f-4710-b2fa-dfad66d8e78d)
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/77238633/392166f6-c0f9-4484-a5d7-1c63ed7ad040)

**Comment by MistEO** [comment]
没适配，在 [这里](https://github.com/MaaAssistantArknights/MaaRelease/blob/main/MaaAssistantArknights/api/gui/StageActivity.json)

**Comment by MistEO** [comment]
不对，看错了

@ABA2396 来瞅瞅（

**Comment by ABA2396** [comment]
是被 "隐藏未开放关卡" 给藏起来了，我看看咋改

**Comment by ABA2396** [comment]
api里开放时间写错了）重启下就好了
