### ISSUE TITLE
Debug模式资源加载问题

### ISSUE THREAD

**Issue by ABA2396** [MaaAssistantArknights/MaaAssistantArknights#5208]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在Debug模式下，偶现在 `\resource\tasks.json` 和 `\cache\resource\tasks.json` 中存在同名任务时仍加载 `\resource\tasks.json` 中的任务，Release模式正常。

 `\resource\tasks.json`:
```
    "LE-Open": {
        "action": "ClickSelf",
        "roi": [
            471,
            0,
            530,
            711
        ]
    },
```

 `\cache\resource\tasks.json`:
```
    "LE-Open": {
        "action": "ClickSelf",
        "algorithm": "OcrDetect",
        "text": [
            "复刻",
            "已开放"
        ],
        "postDelay": 2000,
        "roi": [
            0,
            500,
            500,
            150
        ]
    },
```

### 日志文件

Debug:
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11798124/asst.log)

Release:
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11798135/asst.log)

### 截图

Debug:
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/a5fba4f9-4210-4e3f-ac50-017cf7fbb92a)

Release:
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/2286083f-fc8f-4fbf-9716-6b6726499e95)

**Comment by MistEO** [comment]
和之前发现的日服资源 debug 模式下不覆盖是同一个问题，[这段]删掉就不出问题了，且是必现的。看不懂 zyl 的魔法，等他有空瞅瞅（ @zzyyyl

**Comment by zzyyyl** [comment]
有个笨方法，在 ASST_DEBUG 里的那段使用的 `get` 不展开到 `m_all_tasks_info` 里，而是用一个 `get_dbg`（我随便起的名字） 展开到 `m_all_dbg_tasks_info` 里然后检查：）

**Comment by zzyyyl** [comment]
忽然想到一个简单的办法，在 `ASST_DEBUG` 段的最后面加一句：`m_all_tasks_info.clear()` 好像就行了
