### ISSUE TITLE
水月肉鸽一直放弃探索

### ISSUE THREAD

**Issue by icescotch** [MaaAssistantArknights/MaaAssistantArknights#5216]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

水月肉鸽开始之后选人就直接放弃探索或者卡再开始界面
![无标题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137243476/fec5b2b6-3f13-4cc4-8f7c-e5f19d9b0b80)

### 日志文件

![2023-06-21_09-46-01-470_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137243476/ae411302-310f-45d4-93f5-71dfe758aa95)

### 截图

![2023-06-21_09-48-54-955_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137243476/f7cbf7fc-57ae-4a69-be28-709a16fd3995)
没有放弃探索的话是直接卡在这里

### 还有别的吗？

模拟器：mumu
maa版本：4.19.2
操作系统：windows11

**Comment by MistEO** [comment]
这里正常应该是在最左边的，（即画面中有一个可以点的节点，而不是现在这样全是灰色的），感觉是明日方舟的 bug，有概率不再最左边，你手动划一下试试

**Comment by icescotch** [comment]
> 这里正常应该是在最左边的，（即画面中有一个可以点的节点，而不是现在这样全是灰色的），感觉是明日方舟的 bug，有概率不再最左边，你手动划一下试试

确实是这样
