### ISSUE TITLE
按照常见问题说明方法操作实行后肉鸽依然没法自动

### ISSUE THREAD

**Issue by 7cat** [MaaAssistantArknights/MaaAssistantArknights#5217]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开自动肉鸽后出现直接在界面显示无限重开的情况，尝试选择难度进入后发生无限放弃却没退出的情况

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11811717/asst.log)

### 截图

![F7O{L2U(_)$CFB}GX6V JTE](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39822619/0baaf580-6802-4d52-9be1-97b1855004d5)
![3%IXGSDBR(E3VLU2~MZG @4](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39822619/1a7e1589-9e28-465f-85b3-ac02e19f1324)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39822619/bdff9e49-fb97-449a-b2df-7ad01057dd2c)

### 还有别的吗？

模拟器：蓝叠模拟器5
maa版本：4.19.2
操作系统：windows11

**Comment by MistEO** [comment]
重启下，还不行在设置里强制替换下 adb
