### ISSUE TITLE
针对设置项的优化意见

### ISSUE THREAD

**Issue by Ek1ero** [MaaAssistantArknights/MaaAssistantArknights#5219]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

1. 当前版本的设置分为 设置选项卡、首页任务设置 - 常规设置/高级设置 共计十二个页面，层级较多，且其中存在重叠部分。
2. 首页下方关卡小提示仅有六行文字的空间，需要二次滚动，无法直观查看信息。

### 有什么好的想法？

将设置合并为单一设置选项卡，并增加搜索功能。由于设置选项卡左侧存在类目窗格，不会出现由于页面内容过多而无法找到对应设置的情况。

### 其他内容

~~亦或者移除设置选项卡，将设置全部迁移至首页。~~

**Comment by MistEO** [comment]
之前就是单一选项卡，然后经常有人问有没有 xxx 功能，告诉他们设置里就有之后，他们的回复往往都是 ”设置里选项太多了，我看不懂，就直接关了“，为此特地拆开的

**Comment by MistEO** [comment]
现在相当于按任务分类了，我觉得挺好找的吧（确信

**Comment by Ek1ero** [comment]
其实主要的问题是不够直观，点几次按键和滑几次滚轮带来的感受完全不同。
设置选项卡内的左侧窗格也是一种分类，搬回去唯一的缺点大概也就是“不能拖动排序”了。
而且老兄你是爱发电啊，文档不看设置不翻张口就问的顶级用户完全可以直接甩开的。这里是米诺斯，而不是罗德岛能养得起这么多小刻。
所谓看不懂的本意带来的结果在拆开之后理应也是看不懂 ~~，而非醍醐灌顶茅塞顿开恍然大悟~~。

**Comment by MistEO** [comment]
每种设计有每种的优势，我觉得现在这样更清爽直观

**Comment by MistEO** [comment]
现在的设计理念是，常用设置：我可能每天都要改，甚至每次运行前我都要改成不同的。
高级设置及设置界面：第一次用的时候调整一次，或者某天在想maa有没有某个功能的时候翻一次，以后就再也不动了。

全混在一起非常乱，即使有搜索找起来很麻烦，而且实现不了上面常用设置的设计需求
