### ISSUE TITLE
自动战斗任何作业无法识别并部署 煌

### ISSUE THREAD

**Issue by Nothingness-Void** [MaaAssistantArknights/MaaAssistantArknights#5220]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在自动战斗中，煌使用的精二原皮 无法被正确识别并部署，每次都会点一下，取消点一下取消。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11818168/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11818170/gui.log)
触发BUG前已清空日志，日志为本次触发BUG的自动战斗完整日志

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55913486/e9a79294-642e-48c5-9435-f09bb1ae6cef)

### 还有别的吗？

模拟器为mumu12，配置如下
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55913486/d1e43264-be0e-405c-b178-6c9a28378d58)

**Comment by lianggexp** [comment]
@Nothingness-Void 
主线6-7，编队是固定的，干员形象也不可更换。
使用作业 maa://21143 ，请问会有无法部署煌的问题吗？

**Comment by Black1312** [comment]
请问最新版MAA中是否仍存在此问题，如仍然存在，请将MAA路径改成非中文名称再试，还存在问题请前往https://dl.google.com/android/repository/platform-tools-latest-windows.zip下载谷歌adb解压到MAA目录（示例：C:\MAA\platform-tools），在MAA-设置-连接设置-adb路径选择解压后文件夹内“adb.exe“再试。最后还有问题请加群912322156发送问题相关说明并@1542550326

**Comment by Black1312** [comment]
请问最新版MAA中是否仍存在此问题，如仍然存在，请将MAA路径改成非中文名称再试，还存在问题请前往[https://dl.google.com/android/repository/platform-tools-latest-windows.zip]  下载谷歌adb解压到MAA目录（示例：C:\MAA\platform-tools），在MAA-设置-连接设置-adb路径选择解压后文件夹内“adb.exe“再试。最后还有问题请加群912322156说明问题发送issue链接并@1542550326

**Comment by jjw777805** [comment]
同见，将mumu12换成中性能可以解决
