### ISSUE TITLE
自动更新故障问题，System.IO.IOException: 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。 ---> System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。

### ISSUE THREAD

**Issue by wingshi** [MaaAssistantArknights/MaaAssistantArknights#5221]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

从空想花庭开始好像MAA的自动更新被DNS污染了？我本身不开梯子也是能上github的，但是近期不开梯子就无法更新了，会显示获取更新信息失败。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11818641/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137306253/60b60482-c0d8-4df0-beab-ec496153237d)

**Comment by mikechen-ruohan** [comment]
是的，我也是同样问题，好像开全局也解决不了

**Comment by MistEO** [comment]
最近版本把更新源换到了 https://ota.maa.plus/MaaAssistantArknights/api/version/ 试试能直接打开吗

**Comment by wingshi** [comment]
> 最近版本把更新源换到了 https://ota.maa.plus/MaaAssistantArknights/api/version/ 试试能直接打开吗

无梯子情况下，显示web页面文字如下，昨晚好像一次更新是能直接正常更新了，这几周来第一次更新，是您这边处理了？

Index of /MaaAssistantArknights/api/version/
[../](https://ota.maa.plus/MaaAssistantArknights/api/)
[alpha.json](https://ota.maa.plus/MaaAssistantArknights/api/version/alpha.json)                                         22-Jun-2023 04:49     53K
[beta.json](https://ota.maa.plus/MaaAssistantArknights/api/version/beta.json)                                          22-Jun-2023 04:49     55K
[stable.json](https://ota.maa.plus/MaaAssistantArknights/api/version/stable.json)                                        22-Jun-2023 04:49     55K

**Comment by MistEO** [comment]
没有，没动过

**Comment by MistEO** [comment]
```log
[2023-06-21 22:07:47.857] <88><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/api/version/stable.json"
System.Net.Http.HttpRequestException: 发送请求时出错。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。 ---> System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
```

日志里有不少这个报错，不知道为啥，感觉本地网络的问题

**Comment by herclyon1** [comment]
所以应该是什么情况？我现在也出现了这个问题
