### ISSUE TITLE
自动战斗增加允许上下位代替功能

### ISSUE THREAD

**Issue by yige-yigeren** [MaaAssistantArknights/MaaAssistantArknights#5223]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有时候账号上没有作业所需的非刚需干员（例如非核心能天使等）
导致无作业可用，下载修改又太麻烦了

### 有什么好的想法？

上下位替代功能，分为自动和手动
手动可以在开始前直接在gui页面选择作业中的干员，并直接设置为另一干员替代其
例如可以直接手动选择作业中的2技能澄闪，手动选择以艾雅法拉2技能替代
自动可以在box中没有或练度不足的情况下选择可替代的同分支干员（例如能天使=》空弦=》寒克等）

### 其他内容

不是什么要紧事，但是修改json对于很多人来说学习成本太高了，时间成本也已经超过去抄大部分作业的情况

**Comment by MistEO** [comment]
这是现在的“干员组”功能，作业作者添加后即可支持。

我不认为自动使用下位替代是一个好选择，到时候就会有一堆人去作业下面评论，“怎么打不过”，然后问了半天现象发现是自动使用了下位替代导致的

**Comment by yige-yigeren** [comment]
> 这是现在的“干员组”功能，作业作者添加后即可支持。
> 
> 我不认为自动使用下位替代是一个好选择，到时候就会有一堆人去作业下面评论，“怎么打不过”，然后问了半天现象发现是自动使用了下位替代导致的

我希望的这个功能是手动gui平替，例如我只有小羊，但可以平替澄闪2
修改json太麻烦了（）

**Comment by WSMTBG** [comment]
> > 这是现在的“干员组”功能，作业作者添加后即可支持。
> > 我不认为自动使用下位替代是一个好选择，到时候就会有一堆人去作业下面评论，“怎么打不过”，然后问了半天现象发现是自动使用了下位替代导致的
> 
> 我希望的这个功能是手动gui平替，例如我只有小羊，但可以平替澄闪2 修改json太麻烦了（）

json里面搜索替换就行了，比如ctrl+h 搜索推王，替换成凛冬，当然是打个比方，二技能推王有时候不太好换
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/7738f7f3-43b2-48f0-8c97-e6856a72bc6f)

**Comment by yige-yigeren** [comment]
> 这是现在的“干员组”功能，作业作者添加后即可支持。
> 
> 我不认为自动使用下位替代是一个好选择，到时候就会有一堆人去作业下面评论，“怎么打不过”，然后问了半天现象发现是自动使用了下位替代导致的

在载入后加个自己手动修改的功能？比如打开json
