### ISSUE TITLE
希望加入「执行任务时保持屏幕常亮」功能

### ISSUE THREAD

**Issue by RyanSaul** [MaaAssistantArknights/MaaAssistantArknights#5225]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

最近基建自动换班时总是跳过某些步骤（比如菲亚梅塔没生效、后几间发电站和宿舍没塞人等等，这些跳过的设施不会出现在应用内日志里），而盯着看 MAA 换班时又不会出现问题，因此产生了屏幕熄灭后换班会出现问题的猜想（也许是想专门复现 bug 时很难抓到出问题的原因）
背景：利用 Windows 计划任务使 MAA 定时自启动，并关闭了 Windows 自动睡眠

### 有什么好的想法？

希望能加入「执行任务时保持屏幕常亮」功能，或许可以解决基建换班的问题？

**Comment by Shawnsdaddy** [comment]
不会。。和屏幕亮一点关系都没有。。。

**Comment by Shawnsdaddy** [comment]
个人猜想：不是maa跳过某些步骤，因为在基建页面，会随机出现连接网络的情况，这个时候任何操作都是无效的。
不知道maa在应对这种情况的时候有没有验证或者纠错机制 @MistEO

**Comment by RyanSaul** [comment]
> 不会。。和屏幕亮一点关系都没有。。。

这两天用 PowerToys Awake 保持亮屏，六次换班中没有一次出现过问题，而关掉 Awake 后在某个班次让屏幕自然熄灭，该次换班问题就出现了（甚至是熄屏后下一个设施就立刻出现跳过的问题），很难不让人怀疑是跟熄屏有关

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16830734/ac30b1af-9ed0-4c25-8302-d7b21aaf0d02)
00:15 左右熄屏后，Dorm 3 直接被跳过了
log 如下：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11857722/asst.log)

**Comment by sunyink** [comment]
> > 不会。。和屏幕亮一点关系都没有。。。
> 
> 这两天用 PowerToys Awake 保持亮屏，六次换班中没有一次出现过问题，而关掉 Awake 后在某个班次让屏幕自然熄灭，该次换班问题就出现了（甚至是熄屏后下一个设施就立刻出现跳过的问题），很难不让人怀疑是跟熄屏有关
> 
> ![image](https://user-images.githubusercontent.com/16830734/248501075-ac30b1af-9ed0-4c25-8302-d7b21aaf0d02.png) 00:15 左右熄屏后，Dorm 3 直接被跳过了 log 如下： [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11857722/asst.log)

复议，我也发现这个问题，很奇怪，目前我还在搜集错误阶段。推测可能因为 电脑性能改变（各种节能黑技术影响）或网络慢之类，导致每一步操作需要等更久，maa直接超时跳过。

**Comment by xtsang** [comment]
MAA可以在任务开始前和完成后各执行一次脚本，所以你只需开始时将关闭屏幕时间设为从不，完成时再设置为常用值即可解决

**Comment by status102** [comment]
link to #7218
