### ISSUE TITLE
高分辨率下无法选择战斗关卡

### ISSUE THREAD

**Issue by yuhuangdq** [MaaAssistantArknights/MaaAssistantArknights#5228]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最新几个版本在刷理智-关卡选择时，总是不能选择到关卡，在关卡页面一直向左拉动，最终报错

### 日志文件

[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11829094/log.zip)

### 截图

![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59633224/9f144060-7f9a-437b-bc9b-063f92f43623)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59633224/0d5c1129-550a-47d5-8296-24f82b112ced)

### 还有别的吗？

蓝叠国际版 win11

**Comment by ABA2396** [comment]
我看日志好像只拖了一次就看不见LE-6了，直接到了LE-2到LE-5那里，感觉是方舟在高分辨率下的问题，改成720p或者1080p试试

**Comment by yuhuangdq** [comment]
> 我看日志好像只拖了一次就看不见LE-6了，直接到了LE-2到LE-5那里，感觉是方舟在高分辨率下的问题，改成720p或者1080p试试

换成1080P后确实正常了，这让我们4K玩家咋办啊，能不能优化   :(

**Comment by ABA2396** [comment]
@MistEO 瞅瞅

**Comment by ABA2396** [comment]
> 换成1080P后确实正常了，这让我们4K玩家咋办啊，能不能优化 :(

现在看暂时只能用2K了。然而方舟的立绘分辨率本来就不高，传输和压缩又会占用更多的时间，4K有什么额外收益吗）

**Comment by MistEO** [comment]
这算是方舟的 bug，不同分辨率下，手指滑动同样的距离，界面移动的距离不一样，比如你试试高分和低分下同样速度从屏幕最右滑动到最左。没法整

**Comment by seuqo** [comment]
> > 换成1080P后确实正常了，这让我们4K玩家咋办啊，能不能优化 :(
> 
> 现在看暂时只能用2K了。然而方舟的立绘分辨率本来就不高，传输和压缩又会占用更多的时间，4K有什么额外收益吗）

我剛剛在照我以火和之前的銀心湖列車刷6関遇到同樣的問題，分辨率是按屏幕設置的，看到這裏才知道4k并沒有收益，謝謝
