### ISSUE TITLE
希望增加活动商店自动购买功能

### ISSUE THREAD

**Issue by cglcv** [MaaAssistantArknights/MaaAssistantArknights#523]
如题，刷完理智之后获得不少活动代币，希望在刷完理智后可以自动转到活动商店购买物品
默认从左往右，同一列从上往下买即可，但考虑到不同人对活动商店的选择不同，建议增加购买顺序调整的方案（工作量估计不小）

**Comment by ntgmc** [comment]
由于活动代币具有一次性，限时性，选择性，建议您自己兑换，maa无法执行该操作，同时对于每个账号所需的材料不一样，并且有可能会因为该功能误选导致活动代币兑换错误，综合上述考虑，该功能不予实现
