### ISSUE TITLE
无法打开最新版本的MAA

### ISSUE THREAD

**Issue by Heqipeng** [MaaAssistantArknights/MaaAssistantArknights#5232]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

无法打开
重新安装了运行库也无法打开

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11843503/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11843504/gui.log)

两周前更新新版本出现的

### 截图

![QQ截图20230623105156](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/51855834/46713915-13bf-4c48-bd6a-bffcf0435074)
![QQ截图20230623105219](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/51855834/32d20516-b11f-4b37-a9f2-1e0e5a14702a)

**Comment by ABA2396** [comment]
这个要装的是.net的那个运行库，不是vc的

**Comment by Heqipeng** [comment]
> 这个要装的是.net的那个运行库，不是vc的，点报错信息下面的常见问题里有链接

![QQ截图20230623132254](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/51855834/473fde7e-1874-4197-b026-59a56868d7c1)

这种情况该怎么办？

**Comment by yc080713** [comment]
~~看来有必要加一个最低windows版本提示了😂~~

**Comment by ABA2396** [comment]
安装程序可能无法正常运行，因为 Windows Update 服务在此计算机上不可用。 | 可将计算机配置为使用 Windows Server Update Services (WSUS) 而非 Microsoft Windows Update。 有关详细信息，请参阅 [.NET Framework 3.5 安装错误：0x800F0906、0x800F081F、0x800F0907](https://support.microsoft.com/help/2734782/net-framework-3-5-installation-error-0x800f0906-0x800f081f-0x800f0907) 中的错误代码 0x800F0906 部分。另请参阅 Microsoft 支持网站上的[如何将 Windows 更新代理更新至最新版本](https://support.microsoft.com/help/949104/how-to-update-the-windows-update-agent-to-the-latest-version)。
-- | --
