### ISSUE TITLE
StageAnnihilation.png recognition error in YostarEN Fight task (and probably other servers)

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#5234]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Image in /resource/YostarEN/:
![StageAnnihilation](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/e877df0b-f797-4cd5-ba78-866218aef060)
The other servers' images are the same as this one, the language is the only difference
Image in /resource/:
![StageAnnihilation](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/a5f8775d-20d9-4aa6-8810-d8f702756fa9)

Image cropped with ROI tool from Bluestacks Emulator's screenshot:
![Screenshot_2023 06 23_14 34 49 446 png_906,55,374,199](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/26bbc388-c9c0-4c99-8975-e74379f90141)
Annihilation banner with progress
![Screenshot_2023 06 23_14 59 04 184 png_905,54,375,202](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/090b5c76-8324-4699-bd17-96ab78ab0fb4)

- Try 1
asst::PipelineAnalyzer::analyze Annihilation
asst::TemplResource::get_templ lazy load StageAnnihilation.png
match_templ | StageAnnihilation.png score: ***0.595904*** rect: [ 958, 106, 294, 99 ] roi: [ 900, 70, 380, 400 ]
- Try 2
asst::PipelineAnalyzer::analyze Annihilation
match_templ | StageAnnihilation.png score: ***0.594088*** rect: [ 958, 106, 294, 99 ] roi: [ 900, 70, 380, 400 ]

Does anyone have any knowledge if the interface has been changed? (I have my doubts considering EN is 6 months behind the CN server?)
The images are a bit different and the log shows only a 0.59 score. The ROI is correct and is the same. I'm noticing a huge difference in the image.

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11848546/asst.log)
At [2023-06-23 14:29:42.709]

### Version:

BlueStacks 5.12.1.1001 Pie64 - MAA v4.19.2
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/f8b9a6c5-c6b2-4f7a-8475-e6591b4bde1b)

**Comment by Constrat** [comment]
I would easily fix this myself, just by changing the image but I want to make sure that everyone has this issue / new interface before making any sudden changes. I have access to a CN account but unfortunately it doesn't have the 400/400 kills and it's already at the 1800/1800 Weekly Orundum limit.

**Comment by ABA2396** [comment]
This image on the cn client has been like this from the start, presumably because other client have recently updated the display

**Comment by Constrat** [comment]
Fixed with https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/9866e72dac6a0f66a25c6c686ce98bd78dc3339f
