### ISSUE TITLE
AutoSquad Copilot Operator's name Detection in YostarEN

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#5235]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

The Auto Squad task uses the default CharsNameOcrReplace but (thanks Yostar) the way the names are handled is completely different. I've been testing this afternoon something a bit strange:

### First Issue:
Depending on the display resolution of the emulator "Skadi the Corrupting Heart" can either have a "\n" or not in the name
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/David/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/David/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>
<body link="#0563C1" vlink="#954F72">

Resolution | "Operators" | "Squads"
-- | -- | --
720P | ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/23c0317a-7bc3-41c0-a667-f1f7ff78af63) | ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/6cb09727-996c-4afc-aa90-eafc09c6f39f)
1080P | ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/5a645d11-4e4b-40bc-a675-28c0b46e1b4d) | ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/abfdcbd4-0bd5-4a31-88a0-de5c252919f3)
1440P | ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/354e294a-3426-448a-8ca0-ff7c4c227e20) | ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/8abd78f8-dbfa-4710-96f0-8f63f3c3f2dc)
</body>
</html>

### Second Issue:
Long name operators are not detected correctly:
h'en the Holungday
learl the Radiant Knight
avial the Invincible
Sskai the Crrpting
exas the Omertosa
ecter the Unchained
Justice Knight'
roos the Keen Glint
ava the Purgatory
ine-Colored Deer
ibiscus the Purifier
Greyy the Lightningbearer NOT DETECTED

Sometimes more operator's names are not detected. The "Squads" interface has a much lower font => in low resolutions it makes it difficult to recognize the chars.
@MistEO is it possible to implement some other specialParams like you did for the "Normal" OperBoxNameOCR task.
From the logs I noticed that the ROI [2] was never getting above 105.
In every instance where the name is cut, the ROI shows this: [ 0, 0, 105, 15 ]
Meanwhile Skadi the Corrupting heart shows [ 0, 0, 92, 24 ] considering it needs to be capable to receive a new line I don't think [3] = 24 is enough.

### Solutions:
Easy way: tweaking the OCR replace task by addind more regex like 
```
".*earl the Radiant Knight",
"Nearl the Radiant Knight"
```
I think this could create more problems in the future.
Hard way: _I'm not confident enough that I can pull this off on my own_ expanding the OCR detection range.

In low res Skadi the Corrupting Heart is too long and the bot misses a lot of the chars, this one might need both the range increase and the added regex in the tasks.json.

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11850898/asst.log)

**Comment by MistEO** [comment]
Adding regular expressions is a good idea. If the name is two lines, the ocr that adds the detection range will treat them as two strings, which will cause many problems.

**Comment by Constrat** [comment]
Closing this for now as the alter / long names get patched as they get released. I'm trying my best to use as much as text as possible, trying to use the least regex possible as to remove ambiguities.
