### ISSUE TITLE
完成任务：Fight 后卡顿

### ISSUE THREAD

**Issue by broken-paint** [MaaAssistantArknights/MaaAssistantArknights#5237]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在刷理智完之后有接近1分钟的卡顿，
从日志文件中看疑似连接企鹅物流超时？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11854215/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11854216/gui.log)

### 截图

![微信图片_20230624095911](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131476796/92000780-79b5-48c9-b9e0-e37a7fe26bbd)

### 还有别的吗？

MuMu模拟器 2.7.26.0

**Comment by spriteQi** [comment]
我也遇到了 你看看是不是cpu跑满了

**Comment by ABA2396** [comment]
虽然上报是异步的，但还是算在fight里，所以切换任务的时候会等待结束）这个之后再看看咋办

**Comment by SherkeyXD** [comment]
同样遇到此问题，看了日志发现也是卡在上报
