### ISSUE TITLE
定时执行允许设定更详细的操作

### ISSUE THREAD

**Issue by HS7097** [MaaAssistantArknights/MaaAssistantArknights#5238]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

默认的定时执行在使用内置的基建换班策略时并无大碍，
但启用自订的基建换班后若按照排班表的换班设置，会导致理智溢出，
若直接按照现在设定的每6小时定时执行一次，那么排班表会被打乱

### 有什么好的想法？

若启用自定义基建配置，定时执行时将不再执行基建换班任务；基建换班将在由高级设置内设定的时间执行
或在定时执行下的所有时间设定框下面都添加所有的任务复选框

**Comment by WSMTBG** [comment]
+1，定时执行能不能只在自定基建排班表换班时间去换基建（可以的话不包括休息室），其他时间只去刷理智或者肉鸽

**Comment by ABA2396** [comment]
我的做法是加了个排班表，所有的设施全部skip

**Comment by HS7097** [comment]
> 我的做法是加了个排班表，所有的设施全部skip
如果是这样的话，那能否将其独立为一个名称为“仅收菜"的任务？不论是自订的基建策略与默认基建策略，都允许通过定时执行调用

**Comment by WSMTBG** [comment]
> 我的做法是加了个排班表，所有的设施全部skip

请问下怎么加排班表

**Comment by ABA2396** [comment]
参考 [基建排班协议](https://maa.plus/docs/3.6-%E5%9F%BA%E5%BB%BA%E6%8E%92%E7%8F%AD%E5%8D%8F%E8%AE%AE.html)
或者用生成器生成一个全是跳过的班次然后复制到原来的里面

**Comment by WSMTBG** [comment]
> 参考 [基建排班协议](https://maa.plus/docs/3.6-%E5%9F%BA%E5%BB%BA%E6%8E%92%E7%8F%AD%E5%8D%8F%E8%AE%AE.html) 或者用生成器生成一个全是跳过的班次然后复制到原来的里面

请问下有办法在自定义排班表里加入仅动休息室的排班吗

**Comment by WSMTBG** [comment]
> ```
>         {
>             "name": "仅宿舍",
>             "description": "仅宿舍",
>             "drones": {
>                 "enable": true,
>                 "index": 1,
>                 "room": "manufacture",
>                 "order": "pre"
>             },
>             "rooms": {
>                 "control": [
>                     {
>                         "skip": true
>                     }
>                 ],
>                 "trading": [
>                     {
>                         "skip": true
>                     }
>                 ],
>                 "manufacture": [
>                     {
>                         "skip": true
>                     },
>                     {
>                         "skip": true
>                     },
>                     {
>                         "skip": true
>                     },
>                     {
>                         "skip": true
>                     },
>                     {
>                         "skip": true
>                     }
>                 ],
>                 "power": [
>                     {
>                         "skip": true
>                     },
>                     {
>                         "skip": true
>                     },
>                     {
>                         "skip": true
>                     }
>                 ],
>                 "hire": [
>                     {
>                         "skip": true
>                     }
>                 ],
>                 "meeting": [
>                     {
>                         "skip": true
>                     }
>                 ],
>                 "dormitory": [
>                     {
>                         "skip": false,
>                         "autofill": true
>                     },
>                     {
>                         "skip": false,
>                         "autofill": true
>                     },
>                     {
>                         "skip": false,
>                         "autofill": true
>                     },
>                     {
>                         "skip": false,
>                         "autofill": true
>                     }
>                 ]
>             }
>         },
> ```

是在“这里加”这里粘贴吗
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/2ea40104-ce77-43d8-b506-380d4d000291)

**Comment by WSMTBG** [comment]
> 

提示错误(´ﾟДﾟ`)佬你要不帮我加一下，副本是我自己加的，另一个是原版
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/78177b0c-f272-45c5-a0fd-321e4a2df15c)
[全自动搓玉243没那么极限.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11955512/243.txt)
[全自动搓玉243没那么极限 - 副本.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11955511/243.-.txt)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/6d646be9-0104-46e0-bf47-8b16d95c0b7f)
你这原版的都有问题啊
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/2eeefd6a-96d1-49e0-b1f2-86c579bfb36b)
把括号改过来

**Comment by WSMTBG** [comment]
> ![image](https://user-images.githubusercontent.com/99072975/251126213-6d646be9-0104-46e0-bf47-8b16d95c0b7f.png) 你这原版的都有问题啊 应该是之前复制粘贴的时候删多了 ![image](https://user-images.githubusercontent.com/99072975/251126339-2eeefd6a-96d1-49e0-b1f2-86c579bfb36b.png) 把括号改过来
> 
> 还有文件的后缀是.json，不是.txt

谢谢，txt是因为没法传json，“仅宿舍”还是每个房间都换了一遍...我下午再试下

**Comment by ABA2396** [comment]
房间会进，无人机会用，但是不会换人

**Comment by ABA2396** [comment]
主要是界面不知道怎么做比较好）

**Comment by WSMTBG** [comment]
> 主要是界面不知道怎么做比较好）

基建换班-高级设置-启用自定义配置下面加一个“非换班时间点仅变更宿舍人员”？
还有个问题，排班文件里按那样加了以后，如果我宿舍里要求固定人员的，比如车尔尼爱丽丝放第一间，那把休息室第一间skip后面改成true是不是可以解决问题
"dormitory": [
                    {
                        "skip": true,
                        "autofill": true
                    },
                    {
                        "skip": false,
                        "autofill": true
                    },
                    {
                        "skip": false,
                        "autofill": true
                    },
                    {
                        "skip": false,
                        "autofill": true
                    }
                ]

**Comment by ABA2396** [comment]
"skip": true就不用写"autofill": true了（虽然写了也没用）

**Comment by WSMTBG** [comment]
> "skip": true就不用写"autofill": true了（虽然写了也没用）

好的谢谢，我这个思路是对的吧？
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/3ab70470-81a1-4803-84b2-e44f0662923a)
这里加个勾选框怎么样，【没到换班时间点只换宿舍】之类的

**Comment by ABA2396** [comment]
那就像上面说的这样，第一个宿舍有指定干员怎么办呢

**Comment by WSMTBG** [comment]
> 那就像上面说的这样，第一个宿舍有指定干员怎么办呢

emmm再加小选项？是否有指定干员，有的话“第X间宿舍不参与更换”？

**Comment by WSMTBG** [comment]
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/7bc89391-c170-4d94-974b-3b42226d2bae)
[全自动搓玉243没那么极限 - 测试.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11966176/243.-.txt)
佬能帮我看下问题在哪吗

**Comment by WSMTBG** [comment]
> 房间会进，无人机会用，但是不会换人

懂了帮忙看下，还是一个个房间换人换过去的
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/4700151e-e79b-4ed6-8bfc-89f059ce9ba7)
[全自动搓玉243没那么极限 - 测试 - 副本.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11966503/243.-.-.txt)
东西没错吧应该...

**Comment by WSMTBG** [comment]
> 房间会进，无人机会用，但是不会换人

大佬，我这边还是一个房间一个房间换过去的...
附录屏
[全自动搓玉243没那么极限 - 测试 - 副本.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11966524/243.-.-.txt)

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/7ea02fae-8d47-4be1-8bb1-b51c96308fac

**Comment by ABA2396** [comment]
时间你得自己改啊，只有配置里没时间才能手动选配置

**Comment by WSMTBG** [comment]
> 时间你得自己改啊，只有配置里没时间才能手动选配置

啊...是这个意思吗：
正常排班时间改成：10:00-10:59  14:00-14:59  18:00-18:59
然后添加空排班：11:00-13:59  15:00-17:59  19:00-09:59

**Comment by HS7097** [comment]
新版本问题已解决

**Comment by WSMTBG** [comment]
> 新版本问题已解决

请问下是怎么用的，我切换配置那边新建了两个配置，区别仅在自定义排班的文件不同，但好像切换配置了使用的还是原来的排班

**Comment by HS7097** [comment]
可能仅仅是定时执行的bug，我这边定时执行也会出问题

WSMTBG ***@***.***> 于 2023年7月25日周二 下午2:40写道：

**Comment by ABA2396** [comment]
能详细描述下问题吗

**Comment by HS7097** [comment]
> 能详细描述下问题吗

比如定时执行连接失败，定时执行时打开新的MAA实例，基本上就是这个issue提到的https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5594#issue-1816659031

**Comment by ABA2396** [comment]
> > 能详细描述下问题吗
> 
> 比如定时执行连接失败，定时执行时打开新的MAA实例，基本上就是这个issue提到的[#5594 (comment)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5594#issue-1816659031)

新实例是因为开了自定义基建配置选择吧，鼠标放上去会有提示的
