### ISSUE TITLE
能加一个大号做完日常之后 然后自动切换小号再自动做日常的动作吗？（知道方便了工作室了，感谢回复）

### ISSUE THREAD

**Issue by kongxiangyuTEST** [MaaAssistantArknights/MaaAssistantArknights#5239]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

![dongzuo](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73773070/7fe3bec4-b531-4ebf-b6fd-5a5dd4b0e74a)

**Comment by Fldicoahkiin** [comment]
#5077

**Comment by MistEO** [comment]
这种功能做了基本就是给工作室打工，不会做的。两三个号多开一下就好了

**Comment by yige-yigeren** [comment]
我有一个思路，是自己写一个插件，用maa退出的时候可以启动脚本的功能，自动通过adb模拟器内切换账号和maa配置文件
参考我的一个暂废弃项目，使用batchfile编写。修改少许点击逻辑和补全载入账号密码部分就可以使用了，如果有意向欢迎合作
https://github.com/yige-yigeren/Maa-account-switch-plugin

**Comment by kongxiangyuTEST** [comment]
> 这种功能做了基本就是给工作室打工，不会做的。两三个号多开一下就好了

好的 是我考虑不周 谢谢

**Comment by kongxiangyuTEST** [comment]
> 我有一个思路，是自己写一个插件，用maa退出的时候可以启动脚本的功能，自动通过adb模拟器内切换账号和maa配置文件 参考我的一个暂废弃项目，使用batchfile编写。修改少许点击逻辑和补全载入账号密码部分就可以使用了，如果有意向欢迎合作 https://github.com/yige-yigeren/Maa-account-switch-plugin

不用了 谢谢
