### ISSUE TITLE
多实例崩溃

### ISSUE THREAD

**Issue by zhangweijian97** [MaaAssistantArknights/MaaAssistantArknights#524]
> ！！！请尽可能详细的描述你遇到的问题，并附上助手软件目录下的 `asst.log` 日志文件！！！
> ！！！日志文件是可以直接拖拽进来的，没有日志文件的 bug 反馈我会直接关掉！！！
> 最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_
> Thanks♪(･ω･)ﾉ

先占个坑，回头补材料

**Comment by zhangweijian97** [comment]
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8715421/asst.bak.log)

时间的话，如下图所示

![image](https://user-images.githubusercontent.com/52686008/169018395-cabc6fdd-4a01-4de4-97d2-421ec53bc9fc.png)

一个是17号晚上7点，这个运行了16分钟之后爆炸。另一个是18号早上8点半，这个才运行几秒钟就寄了。不懂

**Comment by helloIris415** [comment]
确实，我这周也发生了多次崩溃事件。特别离谱。现在出门之前还要手动设个自动关机。关键是这周也没更新插件吧

**Comment by helloIris415** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8747699/asst.log)

**Comment by helloIris415** [comment]
帮我对象刚入坑的号挂活动图，一下午崩溃了4次

**Comment by MistEO** [comment]
> 帮我对象刚入坑的号挂活动图，一下午崩溃了4次

楼主跟你说的不是一个问题，你这个问题 v3.9.0 已经修复掉了，不过还是测试版

**Comment by MistEO** [comment]
看起来是飞桨崩了，如果不是经常遇到，我就摆烂了（
