### ISSUE TITLE
蓝叠模拟器4「完成后退出模拟器」功能失效

### ISSUE THREAD

**Issue by 2247ds** [MaaAssistantArknights/MaaAssistantArknights#5241]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

完成任务后只是结束了方舟的进程，没有关闭模拟器

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11855601/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11855641/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46276428/4bc6293d-af96-40ca-be1c-1792cf4bda51)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46276428/73ed3842-3be8-4621-9548-5f0bde13158b)

### 还有别的吗？

maa v4.19.2
Bluestacks v4 .280 .4 .4002
Windows 10 22h2

**Comment by MistEO** [comment]
老模拟器没适配，建议升级蓝叠 5
