### ISSUE TITLE
部分情况下傀影肉鸽棘刺技能自动选择错误

### ISSUE THREAD

**Issue by RiseFive0** [MaaAssistantArknights/MaaAssistantArknights#5242]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选择队伍后选择技能，其他干员都有动作，棘刺没有选技能的动作，默认1技能，棘刺在1号位，bug触发频率不确定

### 日志文件

大概2023/6/24 18:00
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136883323/25a60186-d00e-4ad5-b043-9a237e2a8a3a)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136883323/2be250f2-996f-4c2d-aaba-66bd9d48420e)
7z软件已选极限压缩文件大小依旧过大，有无其他上传方式

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136883323/ce3a6bc8-b61a-4fc9-9cd6-d93a0809d6d9)

### 还有别的吗？

MuMu模拟器12，win10

**Comment by MistEO** [comment]
想办法发下 log，不然问题没法查

**Comment by RiseFive0** [comment]
链接：https://pan.baidu.com/s/17O_OfiYS7K_vdKHHpuwf5w?pwd=9e6n 
提取码：9e6n
百度网盘
一次确定发生的bug时间为2023/6/24 19:21:30
另外我已经看到有人反馈肉鸽开具在希望正好够的情况下会选择没有练度的波登可，不会选择3星的满练安赛尔，这个问题我也有遇见，可惜没有确切时间，希望能一并处理

**Comment by RiseFive0** [comment]
> 想办法发下 log，不然问题没法查，用网盘或者别的也行

已发
