### ISSUE TITLE
玩家容易忘记取消勾选“吃理智药”选项

### ISSUE THREAD

**Issue by badadibadabo** [MaaAssistantArknights/MaaAssistantArknights#5244]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我在周末想一次性刷完要过期的理智药，周一打开时忘记上次已勾选吃理智药的选项，使用时不小心把这周的也全用了。

### 有什么好的想法？

若勾选刷理智药选项再启动挂机，希望出现一个询问是否忘记取消勾选此选项。或者把刷理智药改为一次性的，这次选上，刷完后自动取消勾选。

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/844100c9-75cc-43fd-8f14-61673e3f03c5)

**Comment by badadibadabo** [comment]
> ![image](https://user-images.githubusercontent.com/99072975/248531454-844100c9-75cc-43fd-8f14-61673e3f03c5.png)

感谢，我没看到这个
