### ISSUE TITLE
关于基建无人机使用

### ISSUE THREAD

**Issue by CCFF00** [MaaAssistantArknights/MaaAssistantArknights#5247]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

希望增加制造站使用无人机但不会更换干员。

**Comment by status102** [comment]
Duplicate of #5243
