### ISSUE TITLE
刷关途中闪退

### ISSUE THREAD

**Issue by lzh004** [MaaAssistantArknights/MaaAssistantArknights#525]
夜神模拟器7.0.1.9
软件版本是3.3
大概就是这两天回出错

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8716556/asst.log)

Thanks♪(･ω･)ﾉ

https://user-images.githubusercontent.com/52206798/169048989-9a50703f-01a6-4858-9ca9-57838f24a403.mp4

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/507 已经修复了，还没上线，敬请期待吧~
