### ISSUE TITLE
蓝叠5「完成后退出模拟器」gui日志有误，模拟器成功关闭，但右侧日志显示「模拟器关闭失败」以及启动模拟器的逻辑问题

### ISSUE THREAD

**Issue by SunShineJF** [MaaAssistantArknights/MaaAssistantArknights#5254]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

问题1：蓝叠5「完成后退出模拟器」功能，可以正常用，任务完成后确实模拟器成功关闭，但右侧日志显示「模拟器关闭失败」

问题2：启动作业时候，由于之前退出模拟器，并不会检测模拟器是否启动，而是会直接尝试重连5次，重连失败才会启动模拟器，是否可以优化启动模拟器逻辑？具体日志详见gui.log

### 日志文件

[gui_25、26日.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11862889/gui_25.26.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11862915/asst.log)

### 截图

![QQ截图20230626113023](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49141302/1c8f35f3-48d8-48a7-8fb4-80382f611d78)

### 还有别的吗？

maa v4.19.2
Bluestacks 5.1111002 N64
Windows 11 22H2 23419.1000

**Comment by ABA2396** [comment]
问题2 dev上已经改过了
