### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by qw1642190428** [MaaAssistantArknights/MaaAssistantArknights#5258]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我是软件白天一直开着 它自动更新问我要不要解压 我选好的但是它不自动重启  只是自动更新这样 手动更新不这样

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11870217/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11870218/asst.log)

**Comment by ABA2396** [comment]
没搞懂，自动手动调用的都是AskToRestart()来着。意思是自动的更新点了确定后没反应吗？

**Comment by qw1642190428** [comment]
是的

**Comment by qw1642190428** [comment]
这个问题已经好长时间了
