### ISSUE TITLE
关于肉鸽选取干员配置文件的详细说明和建议改进之处（recruitment.json文件的一些修改建议）

### ISSUE THREAD

**Issue by Blearycatv** [MaaAssistantArknights/MaaAssistantArknights#5259]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

**1. 自我情况说明**
在下萌新刀客塔，目前只有50级，因为资源十分紧缺，所以想用MAA来挂挂肉鸽，先把里面的等级奖励提出来发育。但是本身练度不够，就几个能打的干员，能作为基石打肉鸽的就一个羽毛笔。其余高星高等级的干员就归鲨，42，银灰，星熊，赫默，白面鸮，桃子，其余的基本就拉到精一40。同时本身有点强迫症，有时候看着MAA打肉鸽那操作血压就噌噌地往上升（点名批评每次开局必拿的0级波登可）。所以就想能不能改改配置文件让肉鸽更适合我的配置，本来配置就不够，结果每次下面羽毛笔带着一排的预备干员，人都麻了。
**2.遇到的问题**

- recruitment.json没有一点注释，字段作用只能靠猜，具体招募逻辑，各个字段在招募时怎么用也没有。（可能开发组还没计划让这个文件给大家自由修改吧QAQ）
- 在肉鸽进行的过程中，有时候会遇到频繁点击一个干员，感觉像是识别出干员技能冷却完毕出错。有点浪费时间，不过无伤大雅。
- 肉鸽的时候小概率会卡在干员放下但没选方向的时候，或者卡在暂停界面。不过有超时退出，也是浪费了点效率。

### 有什么好的想法？

> 就是简单写一下翻了一两个小时源码翻出来的招募文件中各个字段的作用吧，如果开发组没有这个计划的话，先给其他人做个参考，json文件地址："MAA-v4.19.0-win-x64\resource\roguelike\recruitment.json"

**首先里面的各个group就不说了，对应着干员的类型。**
- 每个干员中的词条大概如下（个人推测，可能有错误）：
   `"name"               干员名称`
    `"skill"              干员选择的技能`
    `"recruit_priority"   干员招募优先级权重（越大优先级越高）`
    `"promote_priority"   干员进阶优先级权重`
    `"is_start"                是否是start干员`
    `"is_key"                  是否是key干员`
    `"promote_priority_when_team_full"    ???当队伍满员时权重???`
    `"recruit_priority_offsets" 招募优先级修改偏置`
        `    "groups"       需要判断的组别`
        `    "threshold"   组别数量阈值`
        `    "is_less"        大于阈值生效还是小于阈值生效`
        `    "offset"         偏置的值（直接和优先级权重相加）`

**大致的招募干员判断过程：**
- 首先，查看已有阵容，判断阵容中是否有初始干员，没有前仅招募start干员或预备干员，判断阵容是否完备，否则仅招募key干员或预备干员。其中，如果第10次招募还没拿到半队key干员，放开招募限制，有啥用啥；如果第3次招募还没拿到start干员，放开招募限制，有啥用啥。阵容完备性判断是根据json文件中的team_complete_condition判断，干员数需大于等于其数值。
- 然后，识别待招募干员，判断干员是否已经拥有。如果已拥有，判断是否为预备干员，如果是，为防止重复招募预备干员占用编队位置，将其权重设为“promote_priority_when_team_full”（**但是我看了一下json文件中好像只有近战和狙击这一项有值**）。不是预备干员则按照"promote_priority"权重进阶。
- 如果未拥有，优先招募精二干员，权重为"recruit_priority"加上"promote_priority"。对于其他干员，**精一50级以下不考虑，直接排除**，**精一50级以下不考虑，直接排除**，**精一50级以下不考虑，直接排除**。（所以我一堆精一40级的干员改了个寂寞）。同时，如果无start干员且此干员不是start干员，则权重-1000，如果阵容不完备且此干员不是key干员，则权重-1000。随后权重大于0的干员加入候选名单，最后取权重最大的干员。

**总结**
这套配置感觉对于大佬们而言可能问题不大，因为大佬的配置都比较高，干员比较全。但是对于萌新就很痛苦，本来干员不全就不好打肉鸽，想打打肉鸽整点资源，但如果不根据自己的配置调整干员，就真的会变成全预备干员硬打，导致层数很低，效率很低。
希望上面写的能帮到大家，上面仅仅是我自己根据部分源码推测出来的，如果有不对希望大家指出，当然如果开发组能把说明完善一下就更好了:)

**Comment by ABA2396** [comment]
总体上没啥问题，但是萌新可以用开局干员去借一个好友的，比如傀影选山，水月选百嘉，前两层就基本能过了）

**Comment by MagakiReimu** [comment]
这个需求挺好的，萨米想用圣约送葬人2技能开局，MAA默认只会用1技能，然后开局各种死

**Comment by Atashun** [comment]
我有的时候水月用6星高台开局的但是只抓一个预备近战另一张特种券放掉也不用 请问怎么解决orzorz

**Comment by opink** [comment]
对于其他干员，精一50级以下不考虑，直接排除，

这个逻辑在哪改？
