### ISSUE TITLE
MAA作战失败 然后崩溃

### ISSUE THREAD

**Issue by xingyu1272** [MaaAssistantArknights/MaaAssistantArknights#5260]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 遇到了问题
拒绝访问。
解决方案
出现未知错误
详细信息
System.ComponentModel.Win32Exception (0x80004005): 拒绝访问。
   在 System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   在 System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   在 System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   在 System.Diagnostics.Process.get_MainModule()
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.KillEmulatorXYAZ()
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.KillEmulatorModeSwitcher()
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.CheckAfterCompleted()
   在 MaaWpfGui.Main.AsstProxy.ProcTaskChainMsg(AsstMsg msg, JObject details)
   在 MaaWpfGui.Main.AsstProxy.ProcMsg(AsstMsg msg, JObject details)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11870202/gui.log)

**Comment by xingyu1272** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11870321/asst.log)

**Comment by ABA2396** [comment]
这个是完成任务后退出模拟器的报错啊，应该是模拟器用的管理员权限开启，然后maa没用，权限不够然后就拒绝访问了

**Comment by xingyu1272** [comment]
> 

怎么处理（） 但是任务也没完成）

**Comment by xingyu1272** [comment]
显示作战失败

**Comment by ABA2396** [comment]
> 怎么处理（） 

用管理员权限启动maa

>但是任务也没完成）显示作战失败

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7d42402e-3364-4ef2-96ce-263590c5496e)

**Comment by ABA2396** [comment]
> 怎么处理（） 

用管理员权限启动maa

>但是任务也没完成）

看日志你是关卡选择选了剿灭但是剿灭已经打完了吧？打完之后就没有导航了
