### ISSUE TITLE
另一个进程正在使用此文件，因此该进程无法访问此文件。

### ISSUE THREAD

**Issue by DeathofBrain** [MaaAssistantArknights/MaaAssistantArknights#5261]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 遇到了问题
另一个进程正在使用此文件，因此该进程无法访问此文件。
解决方案
文件被占用，请重启电脑后重试
详细信息
System.IO.IOException: 另一个进程正在使用此文件，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   在 MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndUpdateNow()
   在 MaaWpfGui.ViewModels.UI.RootViewModel.OnViewLoaded()
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
怀疑是自动更新出了问题，还未尝试重启电脑，但以前从未出现此情况，并且我已尝试restart程序

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11871007/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11871017/gui.log)

**Comment by DeathofBrain** [comment]
最后针对到了resource/stages.json文件，显示被HD-Adb.exe占用

**Comment by ABA2396** [comment]
啊？adb为啥会占用）

**Comment by KumaTea** [comment]
我也是这样，持续几次更新了

排查后发现是由于开启了启动 MAA 时自动启动模拟器，在没退出模拟器的情况下关闭重新打开 MAA 就会报错，先关掉模拟器就可以了

**Comment by jarryben** [comment]
NewVersionExtract/resource/stages.json，这是路径不排除其他原因导致maa占用更新失败
