### ISSUE TITLE
使用自动战斗时性能占用过高

### ISSUE THREAD

**Issue by Ptilopsis01** [MaaAssistantArknights/MaaAssistantArknights#5263]
### 说说你遇到的问题？

<img width="529" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/93318731/6f8a78ba-a3c8-4985-abed-fb1503a97abc">

如图，最高的时候cpu占用能到40%，此时模拟器的占用也不到20%，maa甚至会引起模拟器的严重掉帧（因为关闭maa即可恢复正常），目前只在自动战斗时发现有这个问题
cpu是12500h，我觉得应该不是我的问题（）

**Comment by MistEO** [comment]
自动战斗要跑神经网络的，就是这样的（

**Comment by Ptilopsis01** [comment]
> 自动战斗要跑神经网络的，高占用是合理的。模拟器不吃是因为他去吃 GPU 了。
> 
> > maa甚至会引起模拟器的严重掉帧
> 
> 你啥模拟器，没日志怎么查
> 
> 换蓝叠或者 mumu

[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11878764/asst.bak.zip)
但我之前用自动战斗的时候没有这么夸张，起码不至于让模拟器都掉帧（而且安卓模拟器也不咋吃gpu性能啊）
