### ISSUE TITLE
基建换班功能里 不会进入宿舍界面 不会让干员休息 时间长了没有可用干员

### ISSUE THREAD

**Issue by Balablue666** [MaaAssistantArknights/MaaAssistantArknights#5264]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建换班功能里 不会进入宿舍界面 不会让干员休息 时间长了没有可用干员

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11877253/debug.zip)

### 截图

![企业微信截图_20230627105648](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137852400/c3642541-9504-4004-a32b-01875170be37)
![企业微信截图_20230627105641](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137852400/4bd17880-23b1-4827-a7a3-9a9fbfd62418)
![Screenshot_2023 06 27_10 56 48 660](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137852400/d4bdd0d2-a203-4144-951c-81e4cf469920)
![Screenshot_2023 06 27_10 56 14 577](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137852400/3e1aab2c-ff51-4c9c-915c-2b5a637151fd)
![Screenshot_2023 06 27_10 56 20 128](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137852400/67be2d9d-b2d8-4898-9a3e-a29170e6e46c)
![Screenshot_2023 06 27_10 56 24 560](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137852400/5208168d-90ba-4711-b4e1-93d14d1ea1cd)
![Screenshot_2023 06 27_10 56 31 343](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137852400/a99df5c7-662d-424f-bfbe-85540da3c9aa)
![Screenshot_2023 06 27_10 56 37 376](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137852400/3556f6af-bba1-4e18-86bc-b7ff1e48d7fe)
![Screenshot_2023 06 27_10 56 43 626](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137852400/9c26041c-a3df-42f6-ab64-bd233fcee50b)

### 还有别的吗？

蓝叠模拟器国际版 配置在截图

**Comment by Balablue666** [comment]
最近出现问题的时间是2023/6/27上午10点半到11左右 试了好几次  
这种情况持续了很久了 几乎所有有工作技能的干员心情都下降到30%以下

**Comment by WSMTBG** [comment]
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/c277d9fe-42f4-431a-a4c1-ac49565a8f8b)
会不会是你宿舍在第二个的原因...

**Comment by WSMTBG** [comment]
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/a8ef1050-a9b6-40c0-8ceb-d781f0a65eb0)
会不会是你宿舍不在最下面的原因

**Comment by ABA2396** [comment]
> ![图片](https://user-images.githubusercontent.com/32087250/249032651-a8ef1050-a9b6-40c0-8ceb-d781f0a65eb0.png) 会不会是你宿舍不在最下面的原因

这个是会有影响，但也不至于宿舍也不去），而且控制中枢也应该在发电站前面进才是，应该是其他问题

**Comment by Balablue666** [comment]
之前试过调整顺序 没有用 甚至只开宿舍也没用

**Comment by Balablue666** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137852400/e54db399-24d0-4fc1-99c7-23a343b6d481)
只选宿舍 当场完成 在基建界面一动没动

**Comment by ABA2396** [comment]
![OD`TY17Z5O {((BYCDVZH28](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/093e464a-8924-44fd-8c39-6087a95166f6)
我这里复现不出来，看图片你是开了异形屏UI适配
![4{{J~{O1}YB00RDN4RGNX51](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/e0a2cc5d-1402-4791-ada7-f6cf95c8824d)
把这个关掉试试，再不行就尝试下重新下载完整包
