### ISSUE TITLE
mumu模拟器开始后仅可启动无法进行任务

### ISSUE THREAD

**Issue by LinYanxi0** [MaaAssistantArknights/MaaAssistantArknights#5265]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

rt，点击开始后可以启动方舟，但不能进行startup
期间出现过截图失败的报错

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11877313/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11877314/gui.log)
今天（27号）的都是
其中截图失败在9:30，32，34，36

**Comment by ABA2396** [comment]
有更新过模拟器吗？
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/ed21b213-84da-4072-8afe-b7b7e499e887)

**Comment by LinYanxi0** [comment]
更新过，今天刚更新（2.7.29.0）
替换显示失败

**Comment by ABA2396** [comment]
> 更新过，今天刚更新（2.7.29.0） 替换显示失败

替换的时候应该把模拟器和adb关了，不过替换失败会用本地的adb路径，应该是能用了

**Comment by LinYanxi0** [comment]
嗯可用了，感谢，辛苦了
