### ISSUE TITLE
新版本经常连接不上，换回旧版本后正常

### ISSUE THREAD

**Issue by Mike1117** [MaaAssistantArknights/MaaAssistantArknights#5270]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用的模拟器为：蓝叠模拟器国际版 P64
更新到[v4.19.3-alpha.1.d027.g18e48b29]后频繁连接不上，在前天更新完[v4.19.3-alpha.1.d028.gcae40709]后几乎完全连接不上模拟器，不然就是连接成功后，执行StartUP时点开游戏就直接卡死，需要反复重开十几次后才有机会连接成功并正常运行
已尝试过:
①手动选择模拟器ADB/自行下载的ADB
②强制替换ADB（直接失败）
③下载v4.19.3不同版本的完整包
以上方法均未解决，也检查过ADB端口无占用
后下载v4.19.2完整包后便能正常连接

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11896179/debug.zip)
出现时间：6/25左右至今天

### 截图

![f29ccf2e13b8c3ec2a47a6f10dc8e1c](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/86037002/b3654a6e-4d8b-4ce3-9790-f755cdef3148)

### 还有别的吗？

操作系统:Windows 10 专业版
相关的配置:
CPU: i7-13700k
GPU:3080

**Comment by WSMTBG** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11995577/asst.log)
+1 8:50-9:10都没连上

**Comment by Rbqwow** [comment]
现在还有问题吗(
~~不是没人理 是真的没人看懂为什么~~
