### ISSUE TITLE
4点更新会卡在签到奖励的界面

### ISSUE THREAD

**Issue by Juicerum** [MaaAssistantArknights/MaaAssistantArknights#5272]
### 说说你遇到的问题？

挂肉鸽到每天4点更新签到奖励的界面就不动了 每次一起来都还是卡在领签到奖励
同期我一个朋友也有这个问题... 我俩用的都是mumu 其他条件也都一样

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/new?assignees=&labels=bug&projects=&template=cn-bug-report.yaml
