### ISSUE TITLE
4点更新会卡在签到奖励的界面

### ISSUE THREAD

**Issue by Juicerum** [MaaAssistantArknights/MaaAssistantArknights#5273]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

4点更新会卡在签到奖励的界面
挂肉鸽到每天凌晨4点更新签到奖励的界面就不动了 maa会继续运行重启但会卡在领签到奖励 
其他功能运行都正常

### 日志文件

[Desktop.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11901888/Desktop.zip)
大概在[2023-06-29 04:08:50.570] 前后

### 还有别的吗？

同期一个朋友也遇到了这个问题 我们用的都是mumu 其他功能都正常 就是4点更新后会停在签到奖励

**Comment by Juicerum** [comment]
更新后解决了 现版本没在遇到过了

**Comment by SherkeyXD** [comment]
确定修复了吗？这边又看到一个新的相关 issue

**Comment by Juicerum** [comment]
嗯 我自己没有再遇到这种情况了 我用的4.20.0稳定版 模拟器是mumu没升12 4点断了线重连后可以自动执行任务 上周一直在刷肉鸽都没问题
