### ISSUE TITLE
MAA in AE operations activates too fast after the initial drop is recorded in stages.

### ISSUE THREAD

**Issue by SpinalWrithe** [MaaAssistantArknights/MaaAssistantArknights#5275]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

The bug is that MAA will record the first set of drops in a series battles as put into the GUI, but after the first battle MAA will just click too fast past the drops to record them.

### Log files

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11903032/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11903033/asst.log)

### Screenshots
Video showing the issue.
https://www.youtube.com/watch?v=21ajmZqKDfo

### Anthing else?

OS: Windows 10
Emulator: BlueStacks
Client Type: YostarEN
Module: Fight

**Comment by SpinalWrithe** [comment]
This issue is still present as of v4.21.0.

**Comment by Constrat** [comment]
Apart from rerun events during july - august that had some issues regarding penguin reports, I've never encountered a case where the screen was taken.
