### ISSUE TITLE
请问基建的逻辑是改了吗？

### ISSUE THREAD

**Issue by MadRouge** [MaaAssistantArknights/MaaAssistantArknights#5276]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

你好，请问基建的排班逻辑是改了吗？为什么会出现心情不是满的情况下却不将干员放进宿舍恢复？这个问题好像有个几天了，今天上线看的时候发现很多干员心情都是不满的，但是基建排班并没有将这些不满的干员放入宿舍恢复

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11905032/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11905035/gui.log)
问题应该从27日左右就开始出现，不确定是不是和系统语言不是简体中文有关系

**Comment by 1oneZhi** [comment]
我也一直有这个问题，
