### ISSUE TITLE
无法加载dll，常见问题也无法点进去

### ISSUE THREAD

**Issue by rexlonglongrin** [MaaAssistantArknights/MaaAssistantArknights#5278]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

重置电脑后MAA就无法正常打开了，一直这样显示：“MaaWpfGui.ViewModels.UI.SettingsViewModel”的类型初始值设定项引发异常。
无法加载 DLL“MaaCore.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。

### 日志文件

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/138131110/31991364-8fb9-4435-82d6-c9b8225ab19e)

### 截图

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/138131110/be15c413-6a76-48b2-a326-469af7054394)

**Comment by ABA2396** [comment]
啥叫常见问题无法点进去？
[常见问题](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/c9ec6029-69de-4563-bd7e-dda657208b6c)
