### ISSUE TITLE
危机合约开启后愚人号SN关卡导航失效

### ISSUE THREAD

**Issue by cglcv** [MaaAssistantArknights/MaaAssistantArknights#528]
如题，危机合约开启后愚人号活动入口位置发生变化导致SN关卡的导航失效
相关日志[asst.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8729122/asst.txt)

~其实不修也无所谓毕竟活动没几天就关了用上次作战或当前作战也能对付过去~

**Comment by ABA2396** [comment]
说的也是 ~~要不把这个入口删了.jpg~~
