### ISSUE TITLE
无法进行自动战斗

### ISSUE THREAD

**Issue by Tythla** [MaaAssistantArknights/MaaAssistantArknights#5284]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在使用定时执行功能时，自动战斗总是报错，其他功能均可正常执行。该问题在夜神，bluestack，mumu模拟器上均可稳定复现，手动没有此问题。问题发生时，计算机处于关闭屏幕状态，但没有休眠。
win10与win11均有发生。
PS：已将日志更新，不存在选定“上次作战”的问题了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11917103/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11917105/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32760749/82d4a4ac-d34d-4919-8b2c-eeb66542951e)

**Comment by ABA2396** [comment]
看日志你的上次作战是 剿灭 啊，打满之后全权代理就点不进去，自然就卡住报错了

**Comment by Tythla** [comment]
> 

那是因为今天刚更新的缘故，之前开活动的时候选择特定关卡也会出现这个问题

**Comment by Tythla** [comment]
将显示器改为永不关闭且将战斗设在非第一位可有效解决此问题
