### ISSUE TITLE
关于mumu12模拟器基建选人问题

### ISSUE THREAD

**Issue by kitee11** [MaaAssistantArknights/MaaAssistantArknights#5286]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建功能在mumu6版本是全部正常的。但新换了mumu12模拟器以后，在基建选人界面会出现这样的问题：maa无法成功选择他想要的干员——欲选的干员头像有被点击的高亮提示但无法选中，造成的结果就是在选人界面一直划拉。划拉一段时间后在maa提示栏出现“干员冲突”字样。 站内我也看到了和我类似问题的issue，详见（ 使用mumu模拟器切换基建时出现干员显示bug #5285 ）

问题主要出现于trade control 和power部分，制造站和dorm能正常使用

更换模拟器后我修改了模拟器路径 修改了ADB路径  对端口号按mumu12的进行了修改，确认这三项无误
三种触控模式我也都试了一遍，对问题的解决没有帮助

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11923896/gui.log)

asst文件上传失败 提示“something went really wrong,and we cant process that file”  因此上传zip文件
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11923899/asst.zip)

### 还有别的吗？

模拟器MuMu12   win10

**Comment by J1mmyQi** [comment]
相同的问题我今天在手操的时候也遇到了，不过我今天尝试了一下把mumu从本来的低性能调整为中性能似乎没有出现这个问题。你要不也试试看。
