### ISSUE TITLE
周任务中有挑战boss和关卡数杀敌数的任务，想要多设一个小的选项周一完成

### ISSUE THREAD

**Issue by onenewbird** [MaaAssistantArknights/MaaAssistantArknights#5289]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有些活动周二下午四点开，然后过两个星期之后的周一关闭，葛朗台玩家想要周一就把所有的每周任务做完，拿到相应的体力，投入到这个关卡中，收获更多的资源，所以能不能让maa能设定一个额外的选项，帮助玩家完成每周任务。
关卡中我观察了一下，貌似OF-8挺不错的，有boss，有很多的怪，关卡难度中等，攻略使用一个夜莺加煌就过了。
我不知道哪里有这个功能，尝试了其他的方法
1、我看了一下另外一个关卡关于6-7固定队伍击杀浮士德的，作业跳转的页面是写着每周任务，但是有个问题：必须从开始任务编队的页面进入才能正常启动，本来打算循环十次，结果打完一次之后就退出到选关卡的页面了，无法继续循环。
2、然后maa第一页刷取固定次数的某关卡，我手动输入关卡OF-8，无法识别出来，直接combaterror，然后输入OF-1的话确实能成功识别的，但是选择循环时候，每次做完一次任务之后返回无掉落关卡，然后就没法循环了。

### 有什么好的想法？

我觉得新设定一个按钮能够删除掉无掉落不进行循环这个行为，该按钮默认不开启，藏在刷体力的高级设置里
新增of-8的关卡识别
新增检测每周任务按钮，没有完成就自动完成
如果监测到玩家未自律该关卡，可以抄作业或者设置条件玩家需先自律通过of-8

### 其他内容

另外还有一些无伤大雅的小问题，maa的第一页任务栏可以调节任务顺序，但是还没有一个顺序能实现，我先刷体力，之后领取每日每周任务奖励，领到了体力药，之后再继续刷体力。
选择菲亚梅塔的操作可否优化？宿舍选择技能会找的快一点，不然菲亚梅塔再二号宿舍的时候要找一整天。
还有一个对贸易战使用基建无人机的时候不够葛朗台。

**Comment by status102** [comment]
如果需要刷任务，可以尝试使用自动战斗执行一个没有步骤的作业，能设置重复次数
