### ISSUE TITLE
为什么更新后不支持夜深模拟器了

### ISSUE THREAD

**Issue by wushendutang** [MaaAssistantArknights/MaaAssistantArknights#529]
！！！请尽可能详细的描述你遇到的问题，并附上助手软件目录下的 `asst.log` 日志文件！！！

！！！日志文件是可以直接拖拽进来的，没有日志文件的 bug 反馈我会直接关掉！！！

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8736009/asst.log)

就是打开模拟器，点击你那个开始。和平常一样，今天更新后就出现链接模拟器失败

**Comment by ABA2396** [comment]
填一下adb的路径，把那个adb.exe填进去

**Comment by MistEO** [comment]
请参考 [更新日志](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases)

> 金丝雀版本，日常使用请勿更新。并需要在设置中手动设置连接
