### ISSUE TITLE
lol玩着玩着来个版本更新弹窗

### ISSUE THREAD

**Issue by Diaosi1111** [MaaAssistantArknights/MaaAssistantArknights#5290]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我在打游戏后台开着maa然后给我来个有新版本的弹窗

### 有什么好的想法？

我不知道是是不是我版本的问题，有没有办法弹窗不打断我游戏

### 其他内容

不知道

**Comment by ntgmc** [comment]
可以关闭【重要信息弹出系统通知】
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/5b94b752-c3a8-49ba-8931-563ba1b94a10)
