### ISSUE TITLE
MAAbug 无法识别adb，识别任务

### ISSUE THREAD

**Issue by ikeafish** [MaaAssistantArknights/MaaAssistantArknights#5294]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

为蓝叠模拟器

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11928368/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11928370/gui.log)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11928369/asst.log)

### 截图

![75e5e557828b06ee5c437fa6697e11aa](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/132639792/ae8d8459-a20e-4ca5-b245-f6f881b19381)

**Comment by ocGuang** [comment]
+1

**Comment by WhovianZyh** [comment]
+1
