### ISSUE TITLE
蓝叠模拟器每次启动都会随机一个adb端口，导致自动连接失败

### ISSUE THREAD

**Issue by CharlesChou73** [MaaAssistantArknights/MaaAssistantArknights#5297]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

其实不太清楚这个算不算bug，或者说能不能解决：

蓝叠国际版，每次启动时adb调试端口是随机的，这时如果再用MAA连接，会因为端口错误连接失败。
勾选“自动检测连接”、“每次重新检测连接”不能解决问题。
在连接设置里手动修改端口，则可以正常使用。

这个问题貌似是最近更新后出现的，之前一直按手动启动游戏、手动启动MAA的顺序，没有出现过连接不上的问题。

### 日志文件

完整日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11928848/asst.log)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/3baf8231-3f49-4791-9ba7-4a23ecd5f863)

**Comment by MistEO** [comment]
https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7-hyper-v
