### ISSUE TITLE
使用旧的模拟器时无法连接maa

### ISSUE THREAD

**Issue by BalanceSteelyard** [MaaAssistantArknights/MaaAssistantArknights#5298]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自己有个老电脑，蓝叠5无法使用。发现蓝叠3可以使用。BSTweaker5显示这个版本有adb连接（顺便这个工具可以跳过蓝叠3的谷歌强制登陆），也可以下载并安装明日方舟（安卓4.4.4系统）。但是maa无法连接，连接选择蓝叠模拟器会提示连接失败，正在尝试启动模拟器。选择通用模式会提示截图失败。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11928989/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11928990/asst.log)

### 截图

![屏幕截图 2023-07-02 162205](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114338244/77a37503-6c5e-4b68-9f8c-fdf4a653168c)

### 还有别的吗？

模拟器蓝叠3.7.21.2305
模拟器设置1280x720 dpi240 
旧版本蓝叠3来源https://bestim.org/download.html?dlm-dp-dl=6668
BSTweaker5来源https://bstweaker.tk/zip/BSTweaker%205/BSTweaker51610.zip

**Comment by BalanceSteelyard** [comment]
自己不会adb相关的内容，但是还是靠着搜索和尝试硬试了出来。模拟器的adb为远古版本，无法直接截图，导致maa报错截图。这个版本的adb只能控制其截图在设备上然后输出这个文件到电脑。触控什么的都是可用的，毕竟没有变过。模拟器的版本是安卓4.4.4。劳烦一下开发人员可以添加这个版本的支持吗，这是自己尝试并确定在蓝叠3上可用的证明，它的链接依旧是127.0.0.1：5555.并且adb shell input tap这个基础触控指令也是可用的（好像也只能用这个）
![屏幕截图 2023-07-03 0131155](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114338244/ac56e30e-78ac-421a-be63-488a946c8e19)
![屏幕截图 2023-07-03 014258](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114338244/6a54ef04-28b8-48a9-a1a6-c52abba6f885)

**Comment by ABA2396** [comment]
不能直接强制替换adb吗？

**Comment by BalanceSteelyard** [comment]
> 不能直接强制替换adb吗？
强制替换adb是失败的，因为maa没认出来这个模拟器。即使挂在那里也提示等待开启模拟器。

**Comment by ABA2396** [comment]
https://dl.google.com/android/repository/platform-tools-latest-windows.zip

手动下载adb选择不行吗

**Comment by BalanceSteelyard** [comment]
再试了一圈貌似是因为安卓4的锅不是adb的锅，安卓4没有exec-out，只能使用adb shell screencap然后adb pull扔出去。maa是用exec-out截图的吗还是

**Comment by BalanceSteelyard** [comment]
> https://dl.google.com/android/repository/platform-tools-latest-windows.zip
> 
> 手动下载adb选择不行吗

电脑上肯定是装的34.0版本啊，但是一些新的指令在安卓4上不起作用

**Comment by ABA2396** [comment]
会检测最快的截图方式，用不了exec-out应该是会用adb shell screencap的吧？

**Comment by BalanceSteelyard** [comment]
> 会检测最快的截图方式，用不了exec-out应该是会用adb shell screencap的吧？

现在用的就是通用模式，其它模式都是连不上模拟器或者触控方式不可用。触控模式只能用ADB input。连上了还是显示无法截图到最后
