### ISSUE TITLE
更新3.9后模拟器连接失败

### ISSUE THREAD

**Issue by andiyeki** [MaaAssistantArknights/MaaAssistantArknights#530]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8736075/asst.log)
之前是用手动配置连接地址的方法连接MuMu模拟器的，同样环境下3.3连接正常，3.9提示”连接模拟器失败，请检查连接设置“
![image](https://user-images.githubusercontent.com/105046583/169454873-d6000393-ee4a-407d-8b42-43e3d7f5ad85.png)

![image](https://user-images.githubusercontent.com/105046583/169454900-22466047-ad54-4feb-baf7-05915ced666d.png)

**Comment by TeoZler** [comment]
大概是因为没配置adb路径

**Comment by MistEO** [comment]
adb 路径也是需要填写的，现在暂时没法识别了，还没来得及写。

可以在之前的日志里翻翻，把之前版本识别的 adb 路径复制上去；并且将链接配置改为 `MuMuEmulator`

**Comment by andiyeki** [comment]
解决了，路径要写到adb.exe为止，一开始以为只要写到adb.exe所在的文件夹就行了
