### ISSUE TITLE
任务完成后，下一次启动时，关卡选择会变为null

### ISSUE THREAD

**Issue by MuLInGRui** [MaaAssistantArknights/MaaAssistantArknights#5300]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在之前出现过，后来更新修复了该BUG（不确定），现在在最新内测版本中又出现了该情况，具体是发生在我勾选“手动输入关卡名”后；
今天中午是一切正常，下午再开机自启MAA后发现“关卡选择”一栏的关卡名变为null，
即“关卡选择”AP-5，“备用关卡”9-10、CA-5变为“关卡选择”（空），“备用关卡”9-10、CA-5

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11929297/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11929298/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11929299/gui.log)
时间在下午18：20左右

**Comment by MuLInGRui** [comment]
#4905

**Comment by ABA2396** [comment]
gui.json 好像不是最新的
不过看日志好像只是显示错误，实际传的内容还是对的

**Comment by MuLInGRui** [comment]
哦，这个是因为我当时注意到了手动填上去的AP-5发自我的手机-------- 原始邮件 --------发件人： uye ***@***.***>日期： 2023年7月2日周日 晚上7:23收件人： MaaAssistantArknights/MaaAssistantArknights ***@***.***>抄送： MuLInGRui ***@***.***>, Author ***@***.***>主    题： Re: [MaaAssistantArknights/MaaAssistantArknights] 任务完成后，下一次启动时，关卡选择会变为null (Issue #5300)
gui.json 好像不是最新的
不过看日志好像只是显示错误，实际传的内容还是对的

**Comment by MuLInGRui** [comment]
在出现该情况之后我又尝试将原来的删除，重下一个最新版本，然后同样出现了该情况

**Comment by MuLInGRui** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11929398/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11929399/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11929396/gui.log)
[gui.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11929397/gui.bak.log)
这是删除前的文件，大概在6月30，7月1又出现过
