### ISSUE TITLE
建议在MAA使用手册中补充说明

### ISSUE THREAD

**Issue by ilikecongee** [MaaAssistantArknights/MaaAssistantArknights#5302]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

模拟器使用蓝叠hyper-v版本，在gui.json配置中，我的"Configurations"中有"Default"和"test"两套配置，当前使用的是"test"配置，而只有将"Bluestacks.Config.Path"和"Bluestacks.Config.Keyword"增加到"test"配置中才能生效，而增加到"Default"是无效的。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97867349/762ef94f-18a4-409f-aeca-3bc32b0a9701)

### 有什么好的想法？

希望在手册中提醒大家要将"Bluestacks.Config.Path"和"Bluestacks.Config.Keyword"两个键值增加到MAA当前使用的配置中。
https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7-hyper-v

**Comment by ABA2396** [comment]
说起来这个新增配置是复制当前配置的，如果再default里就加好在新增的话应该就没这个问题了吧？还是说是给不同的模拟器用的

**Comment by ilikecongee** [comment]
> 说起来这个新增配置是复制当前配置的，如果再default里就加好在新增的话应该就没这个问题了吧？还是说是给不同的模拟器用的

我是default里没配置，新增了test配置后才加的
