### ISSUE TITLE
模拟器连接依旧有问题

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#5307]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA连接依旧存在问题，提示连接失败尝试启动模拟器（但此时模拟器早已启动），然后提示重启ADB，就卡住不动了。每次仅在启动时自动检测链接或许有用（每次启动点开这个选项就没有出错过），我也提交过issue，但是从来没有被修复过，有一个类似的issue在昨天还是前天还刚刚被关闭了。这个问题已经存在很久了！

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11943965/asst.log)

### 截图

![屏幕截图 2023-07-04 111002](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92417243/be1591fa-d466-49ed-89d6-428c4ad6fb4b)

### 还有别的吗？

模拟器是雷电模拟器4.0.72（64）一直没变过，系统是Windows11。

**Comment by WSMTBG** [comment]
+1，印象中近期（大概是4.19开始）这个问题有点频繁，我是win11+蓝叠国际版510.220.1008 N64+4.19.3 beta2

**Comment by ABA2396** [comment]
是雷电4还是雷电9？我看你两个issue的端口号是不一样的，如果是老版本的雷电是存在端口号变动的，所以会存在不自动检测就连不上，甚至之前版本的雷电都是直接不推荐使用的。新版本雷电才固定了端口，解决了连接问题
![IMG_20230704_171345.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/5df4f59d-ba20-42e3-b6a2-eceae33d3c99)

**Comment by xiaoweiXX** [comment]
> 是雷电4还是雷电9？我看你两个issue的端口号是不一样的，如果是老版本的雷电是存在端口号变动的，所以会存在不自动检测就连不上，甚至之前版本的雷电都是直接不推荐使用的。新版本雷电才固定了端口，解决了连接问题 ![IMG_20230704_171345.jpg](https://user-images.githubusercontent.com/99072975/250832318-5df4f59d-ba20-42e3-b6a2-eceae33d3c99.jpg)

雷电4，我看端口号一直是5554，但是连接地址有时候是127.0.0.1，有时候是emulator。雷电9用过，拿MAA刷肉鸽有bug，会内存爆炸然后卡死（个人推测是MAA高频截图导致的），之后就退回雷电4了。之前MAA一直没有问题，大概是今年的某一次更新之后才出现的问题，我很肯定至少去年秋天是没有这个问题的，我的雷电版本也一直没有变过。

**Comment by dylanhz** [comment]
连接的问题起码两个月之前就出现过了，后面我一直用adb input来避免连接失败的情况，虽然慢一点但是很稳定。
期间只要用minitouch隔三岔五就会连不上，最近试了下关闭自动检测并更换adb，稳定了两天刚刚又崩了，不清楚到底哪个地方有问题。
log的报错位置是7.4 18:00。
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11949984/asst.bak.log)

**Comment by WSMTBG** [comment]
> 是雷电4还是雷电9？我看你两个issue的端口号是不一样的，如果是老版本的雷电是存在端口号变动的，所以会存在不自动检测就连不上，甚至之前版本的雷电都是直接不推荐使用的。新版本雷电才固定了端口，解决了连接问题 ![IMG_20230704_171345.jpg](https://user-images.githubusercontent.com/99072975/250832318-5df4f59d-ba20-42e3-b6a2-eceae33d3c99.jpg)
8:50-9:10都没连上...
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11973654/asst.log)
