### ISSUE TITLE
无法保存软件设置的问题和对软件的一些建议

### ISSUE THREAD

**Issue by SunshineboyZj** [MaaAssistantArknights/MaaAssistantArknights#531]
具体表现为如果不以管理员身份就启动软件，那么对设置做的任何修改在下次启动后又会恢复原样
并且**设置-自动公招-自动使用加急许可**此设置无论是否以管理员身份启动，都会在重新打开软件后恢复成未勾选的状态
另外还有些建议：
1.希望基建设置里的入驻心情阈值可以手动输入数字，滑块调整灵敏度太高想调整到具体某个数字不太方便。
2.公招增加小车等一星干员的特殊词条选项（支援机械+**），支援机械也是比较稀有的，满潜小车还是挺不容易的
3.似乎固定煌+芙蓉？能不能优先选练度高的呀，精0一级的芙蓉。。。。
Thanks♪(･ω･)ﾉ

**Comment by ABA2396** [comment]
- 如果不能保存设置的话先看下是不是把MAA放在了没有`写入`权限的地方 ~如果还有问题就是bug~
- ~入驻心情阈值以为识别的准确率问题存在一定的幅度，不能精确到数值，只是个大概~
- 支援机械确实是个问题 ~下次一定~
- 肉鸽选人可以看`Pinned issues`里的方法 手动修改`resource/task.json` 文件中 `"Roguelike1ChooseOper"` 字段 把你要选的人放前面 ~~但是只会识别第一页有的~~

**Comment by zzyyyl** [comment]
整理了一下相关的 issue 如下：

- 软件设置  
#424  
#439  
#491
- 支援机械  
#105  
#131  
#263  
#378  
#467

**Comment by MistEO** [comment]
> 整理了一下相关的 issue 如下：
> 
> * 软件设置
>   [界面配置可能会重置 #424](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/424)
>   [版本更新后原有配置会被清除 #439](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/439)
>   [每次开机后设置选项都会重置 #491](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/491)
> * 支援机械
>   [自动公招相关功能建议 #105](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/105)
>   [自动公招时识别出支援机械tag但仍当作普通三星tag #131](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/131)
>   [公招添加优先词条 #263](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/263)
>   [希望能添加对“支援机械”的特殊识别 #378](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/378)
>   [建议自动公招加入对支援机械的支持 #467](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/467)

不带这么催更的 (╯‵□′)╯︵┻━┻

**Comment by zhangweijian97** [comment]
顺便反馈一下，v3.9，部分设置不能保存，也就是，连接地址，这个在重启maa之后就清空了，但是其他设置正常保存了。

**Comment by SunshineboyZj** [comment]
![image](https://user-images.githubusercontent.com/81549837/169679489-858f846d-9749-4394-8dae-843244f74b9c.png)
![image](https://user-images.githubusercontent.com/81549837/169679493-2929bda8-c531-449c-add4-9994986f602e.png)
还有个小问题，运行日志中应该是是诡意行商而不是诡异行商哦（错别字）
