### ISSUE TITLE
新版本中, 后台自动战斗时, 电脑掉帧严重

### ISSUE THREAD

**Issue by SHthemW** [MaaAssistantArknights/MaaAssistantArknights#5310]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

版本v4.19.2, CPU是12700H
旧版本是没有这个问题的. 新版本的CPU占用会时不时激增到60以上, 并引发严重的卡顿, 甚至鼠标指针都会掉帧.
.
在选择干员界面该故障触发的尤为频繁, 作为参考.
下面的附图是CPU占用率, 那个明显的波峰就是卡顿现象发生的时候.

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11947146/gui.log)
[Uploading asst.log…]()

### 截图

<img width="684" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97659151/712306e6-b26b-44ec-9a79-30b258ecac8e">

### 还有别的吗？

没有

**Comment by entrok** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11953367/asst.log)
同样存在这个问题，7700X, 4.19.3-alpha-1.d028-gcae40709，蓝叠 5.9.300 N64
在自动战斗中出现，具体表现就是显示输出存在滞涩感，模拟器中可见明显卡顿
需要运行一段时间后出现，多次复现，关闭MAA后依旧存在影响（未启用退出释放ADB），关闭模拟器后恢复正常。

**Comment by NorthanX** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12045540/asst.log)
同上，CPU是i5-10200H，模拟器是MUMU12。在启动MAA之后，模拟器的画面就会出现卡顿，平均帧数维持在10-12帧。
启用了退出释放ADB，关闭MAA后程序仍然卡顿，需要重启模拟器。

**Comment by seraphim424** [comment]
我也是一样的问题 
通过流量监视 可以看到MAA突然40多M/s的下载  MUMU模拟器40多M/s上传 然后MAA的CPU占用也突破40%

**Comment by muyuanjin** [comment]
13700K 4090 水月肉鸽后台会卡住整个电脑并且有明显的的蜂鸣报警音

**Comment by Rbqwow** [comment]
内测版已提供GPU加速功能 同时添加了最小截图间隔 已经成功优化
