### ISSUE TITLE
输入LS-5并启动后，打的却还是LS-6

### ISSUE THREAD

**Issue by aierxiya** [MaaAssistantArknights/MaaAssistantArknights#5313]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在MAA里面输入LS-5，但是启动后打的却是LS-6（模拟器使用的MuMu12 1920x1080）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11953323/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11953324/gui.log)
10：26左右？

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/c825f725-20bd-4c92-aa6e-3612fc060fa8)
