### ISSUE TITLE
关于鹰角通行证更新后的登录识别问题

### ISSUE THREAD

**Issue by 415050203** [MaaAssistantArknights/MaaAssistantArknights#5315]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在鹰角上线通行证之后，在登录界面会卡住停止操作，原本没有通行证的时候是可以顺利登录的（应该是软件没有做相应画面的识别）（应该不是很麻烦的改动拜托了呜呜呜）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11956247/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11956251/gui.log)
在7月5日下午4点55-5点05是最后一次尝试

### 截图

![QQ图片20230705171916](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/138664564/9a8bac7f-4986-4855-8473-6359c51d6164)

**Comment by ABA2396** [comment]
没选开始唤醒？

**Comment by 415050203** [comment]
> 没选开始唤醒？

我的意思就是能不能让他自动开始唤醒，我学生党平时在学校，家里电脑挂着自动清体力，现在就会停在登录界面

**Comment by ABA2396** [comment]
“开始唤醒”的功能就是登录，新界面的登陆好几个版本之前就做了。

**Comment by xiaoweiXX** [comment]
关了MAA重新打开，MAA会有小概率出现点击错位的情况，反馈了一直没改，估计也不会修。

**Comment by xiaoweiXX** [comment]
有可能是 #4454 的问题

**Comment by ABA2396** [comment]
今天更新之后通行证又没了）
