### ISSUE TITLE
剿灭模式检测与执行存在不完善之处

### ISSUE THREAD

**Issue by RimuruW** [MaaAssistantArknights/MaaAssistantArknights#5317]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

剿灭如果默认代理可获取合成玉数量为 0，游戏会拒绝进行代理，此时 MAA 无法正确处理。

### 日志文件

虽然但是，感觉不需要日志吧。

### 截图

<img width="935" alt="屏幕截图 2023-07-05 215409" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59136309/23e9b3e2-5329-4db1-b83b-4da3d054cad3">

**Comment by ABA2396** [comment]
黄字说的就是这种情况

**Comment by RimuruW** [comment]
可能是我表述没到位，我是认为这种情况下应该有更聪明的解决办法的。
比如剿灭关卡这么多，可以试试别的关卡是否能正常代理。
目前的处理方式是过于粗暴了，一旦无法代理直接结束。可能是为了方便，不过功能上确实不够细化了。

**Comment by ABA2396** [comment]
因为现在有了扫荡，只要之前存过一周的票子任何一天都能直接刷完。所以一开始都没准备做剿灭的来着，还是套的之前的逻辑（直接进终端右上角）
