### ISSUE TITLE
定时执行功能细化

### ISSUE THREAD

**Issue by 2247ds** [MaaAssistantArknights/MaaAssistantArknights#5318]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在的 定时执行 不能指定具体任务，只能到点启动。
希望可以指定定时启动时执行的任务，如 9：00 启动时完成 开始唤醒 和 自动公招，10：00启动时完成 刷理智。

### 有什么好的想法？

对 定时执行 细化，增加如 定时1 下的具体任务

**Comment by ABA2396** [comment]
#5323 fixed
