### ISSUE TITLE
雷电模拟器更新至9.051后出现无法正常运行bug

### ISSUE THREAD

**Issue by NagasawaWM** [MaaAssistantArknights/MaaAssistantArknights#5319]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在之前使用的是雷电9，版本可能是9.03几，maa正常运行，今天更新到9.051后maa从开始唤醒出现运行bug无法正常执行操作，尝试更新maa从稳定版到测试版没有解决问题，尝试回退雷电9到9.037版本后运行正常

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11960442/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11960444/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/138709547/151b4c8e-10a2-4f16-97eb-101e68b6e9d4)
在9.051版本下运行maa能抬起唤醒方舟到如图界面，右侧列表卡在下图，之后便无法正常执行操作
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/138709547/b1fb7957-287f-4bc9-a4aa-65eb018d5860)
手动进入游戏界面后打开刷关，换基建等操作也没有反应

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/138709547/46ba2b39-6eb6-4c27-9fa2-29444ffe9ab4)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/138709547/cb8f0887-030b-48e3-bcb9-ff061b687c80)
应当与操作系统无关，但使用了win11体验版还是附上系统版本

**Comment by ABA2396** [comment]
有试过强制替换adb吗

**Comment by NagasawaWM** [comment]
试过的，没反应

**Comment by NagasawaWM** [comment]
三种touch模式也都选过，也没反应

**Comment by NagasawaWM** [comment]
> 有试过强制替换adb吗
三种touch模式都试过的，没反应,

**Comment by joeization** [comment]
雷电9.053強制替換adb失敗，但是手動替換之後minitouch正常使用
