### ISSUE TITLE
更新3.9后连接不上雷电模拟器

### ISSUE THREAD

**Issue by AratoAnge** [MaaAssistantArknights/MaaAssistantArknights#532]
翻log复制了之前的设置还是不行

[QQ截图20220520182505](https://user-images.githubusercontent.com/105919441/169508808-a5a86854-6003-4cf4-9f04-201385f1ddc0.png)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8738622/asst.log)

**Comment by ABA2396** [comment]
看了下日志 是不是你模拟器端口写错了 我看你之前连的是5554

**Comment by AratoAnge** [comment]
不行，5554还是连不上

**Comment by AratoAnge** [comment]
草好像不小心把问题关了

**Comment by zzyyyl** [comment]
还有，雷电用3.9要把连接配置改成`LDPlayer`

**Comment by AratoAnge** [comment]
LDPlayer是改了的，上面截图可以看到
![QQ截图20220520212351](https://user-images.githubusercontent.com/105919441/169537392-64c715e6-52f4-44c3-a481-a0e85e594d1d.png)
顺便想问一下这个问题，我没在C盘个人文件夹下找到adb

**Comment by zzyyyl** [comment]
adb你要到你的模拟器文件夹下面找，看你的是在`E:\leidian\`，那么也可以用`E:\leidian\adb.exe devices`

**Comment by zzyyyl** [comment]
雷电的地址一般是`emulator-5554`或者`127.0.0.1:5555`

**Comment by AratoAnge** [comment]
哦可以，问题解决了，谢谢大佬
