### ISSUE TITLE
不停自动检测更新

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#5320]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA会不停的自动检测更新，弹出已经是最新版的通知，即使我并没有点击检测更新按钮。不清楚这个问题是自发的还是我手动点击一次检测更新引起的（自动检测更新的次数远远大于我点击检测更新的次数）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11966307/asst.log)

**Comment by xiaoweiXX** [comment]
弹通知后log并没有跟着更新，所以log可能无法反馈我的问题。

**Comment by ABA2396** [comment]
设置里有个定时检查更新，选了的话每天4/16点到4.30/16.30会检查一次更新

**Comment by xiaoweiXX** [comment]
> 设置里有个定时检查更新，选了的话每天4/16点到4.30/16.30会检查一次更新

不是定时更新，一直弹个不停，五六点都弹跟这个没关系。

**Comment by xiaoweiXX** [comment]
确切的说，不是一直不停的检测更新，是点一下检测更新，就会弹好几个通知。

**Comment by LiamSho** [comment]
更新检查是 UI 做的，asst.log 是 MaaCore 的日志，debug\gui.log 才是 UI 的日志。如果这几天还有发生，或者发生时候的 UI 日志还在的话请上传一下 gui.log
