### ISSUE TITLE
maa的内测版已是最新版本，自动战斗的作业没法使用

### ISSUE THREAD

**Issue by rwcups** [MaaAssistantArknights/MaaAssistantArknights#5329]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa的内测版已是最新版本，自动战斗的作业没法使用。一直提示我要更新版本。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11974210/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11974211/asst.log)

**Comment by rwcups** [comment]
还有是好友送了线索，但是maa只领取不使用。

**Comment by MistEO** [comment]
更新一下

**Comment by MistEO** [comment]
今天中午1点才发的版本，作业站的是他们盲写的，压根没地图数据
