### ISSUE TITLE
自动刷肉鸽运行一段时间后CPU被模拟器的某个进程占满

### ISSUE THREAD

**Issue by xc01** [MaaAssistantArknights/MaaAssistantArknights#533]
使用的是雷电模拟器，肉鸽大概累计跑六层之后就会有一个"VirtualBoxHeadless Fronted"进程占满CPU，然后帧数降到3
怀疑是交互的时候占用了一定资源导致模拟器没法完成图像界面的计算，也有可能是图像识别占用了一定的GPU
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8739034/asst.log)

**Comment by ABA2396** [comment]
这个可能是显卡驱动的问题，试试更新模拟器和显卡驱动。virtualbox headless frontend占cpu过高是雷电的老问题了，真的不行换个模拟器试试

**Comment by xc01** [comment]
> 

google了一下还真是雷电的老问题，暂且更新驱动试一下。
