### ISSUE TITLE
希望能在关卡选择中添加装置的最佳效率关卡9-10

### ISSUE THREAD

**Issue by JohnSmithDW** [MaaAssistantArknights/MaaAssistantArknights#5336]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by ntgmc** [comment]
如果添加这个那不就得把全部材料的图都加上，
你勾选手动输入关卡名，然后关卡选择输9-10就行
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/fec9ebc2-3b11-4995-b663-f03f403a24f7)
