### ISSUE TITLE
最新版本关卡选择中没有活动关

### ISSUE THREAD

**Issue by superybq** [MaaAssistantArknights/MaaAssistantArknights#5337]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最新版本关卡选择中没有活动关

### 日志文件

1

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/20632962/8fcacce4-3598-44c0-968f-098c4ea95f01)

**Comment by MistEO** [comment]
故事集啊，刷个啥

**Comment by superybq** [comment]
> 故事集啊，刷个啥

正好缺装置,所以就刷FD-8了
