### ISSUE TITLE
建议增加加工站和训练室的基建设置，或增加干员黑名单，以便特殊的干员排班

### ISSUE THREAD

**Issue by celestialckn** [MaaAssistantArknights/MaaAssistantArknights#5338]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有些特殊组合需要干员在红脸状态下上班，如医疗小车。可以增加加工站和训练室的位置，以便临时放置干员。

**Comment by WSMTBG** [comment]
复议

**Comment by WSMTBG** [comment]
+1

**Comment by MistEO** [comment]
#4610

**Comment by MistEO** [comment]
fixed
