### ISSUE TITLE
[Bug]自动战斗中的内置的保全派驻战斗——雷神工业测试平台出现运行错误

### ISSUE THREAD

**Issue by PianCat** [MaaAssistantArknights/MaaAssistantArknights#5339]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在运行至LT-6时弹出提示：
`Recognition error or JSON does not support this. `
随后会自动结束当前保全派驻

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11990516/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11990517/gui.log)

### 截图

![Snipaste_2023-07-08_19-12-55](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50688679/1db53183-c703-4ee6-9e29-1ecff5b306e3)

### 还有别的吗？

模拟器是雷电模拟器9

**Comment by ntgmc** [comment]
是否设置了定时启动？然后打到那里刚好启动了，就会无法执行自动战斗

**Comment by PianCat** [comment]
> 是否设置了定时启动？然后打到那里刚好启动了，就会无法执行自动战斗

无，貌似是因为识别问题，不过后续好像可以了
