### ISSUE TITLE
队伍存在强力击类型的干员时会保持0.1倍速

### ISSUE THREAD

**Issue by Tamamonomae233** [MaaAssistantArknights/MaaAssistantArknights#5340]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

强力击技能在蓄满之后就立刻被识别然后选中导致整局游戏一直以超慢速运行，希望能优化一下

### 有什么好的想法？

在战斗中不选中携带强力击的干员

**Comment by ABA2396** [comment]
技能识别用的是头上的标，强力击是没有的，不是这个原因

**Comment by Tamamonomae233** [comment]
目前在傀影里遇见的开了永续的棘刺和史都华德会出现这种情况
