### ISSUE TITLE
战斗错误

### ISSUE THREAD

**Issue by vandark-9527** [MaaAssistantArknights/MaaAssistantArknights#5342]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

已打开模拟器，模拟器正常显示 明日方舟 主界面
右击“以管理员身份运行”MAA
勾选“开始唤醒”“刷理智”“获取信用及购物”“领取日常奖励”
显示
正在连接模拟器
CombatError
正在运行中
开始任务：StartUp
完成任务：StartUp
开始任务：Mail
完成任务：Mail
开始任务：Award
完成任务：Award
任务已全部完成

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11990917/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11990919/gui.log)
问题大致时间：2023-07-08  22：59：57

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55657824/c7e3b2f7-423f-402c-9328-e1fd02b4ac7b)

### 还有别的吗？

使用模拟器 MUMU

**Comment by ntgmc** [comment]
如果运行无反应多半是mumu没有强制替换adb，可以参考https://shimo.im/docs/473Qyd7B7Nh1w23w设置
CombatError是因为导航不支持FD关卡，所以你填这个他无法刷理智
