### ISSUE TITLE
MAA自动技能专精需求

### ISSUE THREAD

**Issue by Emperor-of-Fortune** [MaaAssistantArknights/MaaAssistantArknights#5345]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前自动提升方面的技术已经接近成熟，我们有着多种的数据库以适应明日方舟的各个版本的更新,而MAA作为一个全日常长草应用,为什么不再长草之余可以让博士们设置好目标自动的完成呢?

### 有什么好的想法？

1.准备：在小工具内增加干员提升功能，该功能需要与仓库识别、干员识别、刷理智（指定材料）、定时启动、明日方舟工具箱(其他的材料计算api也可以),等等。
2.功能流程(每一步都会保存内容，重新启动MAA后从②开始,需要手动开启,可随时停止并重置需求,重置需求后由①处开始)：
	①博士填写需求并开启，例如：
	{
		{
			琴柳,
			支援号令·γ型专三(一技能),
			模组3级
		},
		{
			夜莺,
			精2,
			90级
		}
	}
	②MAA进行数据获取(包含干员当前的状态，仓库材料数量，训练室占用状态等），并将已有与需求发送至明日方舟工具箱返回具体材料缺失，于一图流内查询具体的刷取关卡并选择符合当前账号条件的最佳关卡，检测是否可行,并列出表格(材料|材料需求|刷取关卡）
	③执行刷理智（指定材料）
	④完成可完成的需求，需求的优先度需要详细的设定并考虑需求的成本
	⑤待理智恢复（或使用理智药）重复②~④，直到全部需求完成或所有刷取均不可用(比如研磨石要求的关卡全部未解锁什么的)
3.消息通知： 可要可不要，不会有人真的MAA一连开着7天吧.jpg

**Comment by Black1312** [comment]
消息通知：https://github.com/yokinanya/MaaNotify

**Comment by wuqi** [comment]
其实可以先弄个简单版的,准备好所有材料的情况下自动排班专三
