### ISSUE TITLE
模拟器内尚无运行中的游戏程序时，强制启动定时任务失败

### ISSUE THREAD

**Issue by DemiurgeZ** [MaaAssistantArknights/MaaAssistantArknights#5346]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

勾选强制启动定时任务后，若模拟器内无正在运行的游戏程序，定时任务会启动失败。
具体表现为模拟器连接断开，然后尝试重连失败，尝试重启模拟器时会被模拟器错误弹窗卡住，从而任务失败。
此时若是手动关闭并重启，任务才可以继续进行。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11994631/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11994632/gui.log)

### 还有别的吗？

MAA版本：v4.19.3
模拟器：MuMu12 v3.4.10(1723)
操作系统：Win10 20H2

**Comment by ABA2396** [comment]
模拟器错误弹窗显示的是什么内容？
