### ISSUE TITLE
手贱更新了3.9.0betahhhhhhhhhh无法连接模拟器辽

### ISSUE THREAD

**Issue by AlexYangCong** [MaaAssistantArknights/MaaAssistantArknights#535]
深夜弹窗 更新 然后蓝叠国际版在设置选择后，下拉确认ip端口是5555那个，仍旧提示无法连接，重启确认后手动定位ABD.exe暂时解决？
迷惑

**Comment by MistEO** [comment]
现在就是要手动定位 adb.exe 的，暂时没有自动获取的功能了（

**Comment by AlexYangCong** [comment]
啊，好的，我的，自动更新直接跳beta，没看见alpha的更新公告
