### ISSUE TITLE
OF-1刷信用时，选择普罗旺斯助战，卡死在干员禁用界面

### ISSUE THREAD

**Issue by Heart-of-engine** [MaaAssistantArknights/MaaAssistantArknights#5351]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在使用MAA进行“获取信用及购物”操作时，跳转到OF-1关卡刷取信用，但一直卡死在普罗旺斯的干员禁用界面

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11995418/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11995419/gui.log)
问题出现时间点为进行“获取信用及购物”操作时

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71398110/aed96ddf-e696-43f0-9b5a-c2bdcda00132)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71398110/5e522124-7dab-44ec-bfa9-e54c8a66970d)

### 还有别的吗？

MUMU模拟器
Windows10操作系统

**Comment by ntgmc** [comment]
Duplicate of #4694

**Comment by Constrat** [comment]
Fixed with 6c1da94b3ce77f5decf3e8f5262da455985ddffc
