### ISSUE TITLE
制造站不识别精二淬羽赫墨和多萝西组合

### ISSUE THREAD

**Issue by pengyang7881187** [MaaAssistantArknights/MaaAssistantArknights#5353]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

制造站在淬羽赫墨和多萝西都空闲时，不会安排同时入住，怀疑多萝西不能识别莱因科技γ

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11996520/gui.log)
[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11996521/asst.-.zip)
见任意一次换班

**Comment by Shawnsdaddy** [comment]
maa普通基建应该是不能识别套组的。如果想用套组请用自定义基建
