### ISSUE TITLE
肉鸽开启使用助战 一直刷新干员

### ISSUE THREAD

**Issue by Pinng999** [MaaAssistantArknights/MaaAssistantArknights#5354]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

挂肉鸽时 已确认干员名字填写正确且有好友拥有干员
使用win+l锁屏后经过一段时间后发现一直在刷新助战干员

检查maa设置后未发现异常，且“电源计划”已将“使计算机进入休眠状态”的“接通电源”修改为”从不“

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11997009/asst.zip)
*肉鸽开始时间大约为7：00，亮屏查看大约在8：26

### 截图

![Uploading QQ图片20230710084120.png…]()

**Comment by Pinng999** [comment]
![QQ图片20230710084120](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108909863/c6a132a8-1bb8-4329-9416-fa698db28a45)

**Comment by Pinng999** [comment]
> ![QQ图片20230710084120](https://user-images.githubusercontent.com/108909863/252190550-c6a132a8-1bb8-4329-9416-fa698db28a45.png)

**该图片截于8:26:09

**Comment by Pinng999** [comment]
再补充一下，截图中第2、3、4次探索开始战斗和战斗失败间隔太久，是因为开局后一直停留在放干员状态的低倍速过程中

**Comment by Kongjian8238** [comment]
我是设置后直接没有借助战，选了三个干员就上了，不知道什么情况（捂脸哭）
问下你们都是怎么设置的才可以借助战啊

**Comment by Pinng999** [comment]
> 我是设置后直接没有借助战，选了三个干员就上了，不知道什么情况（捂脸哭） 问下你们都是怎么设置的才可以借助战啊

/
/

**Comment by Pinng999** [comment]
> 我是设置后直接没有借助战，选了三个干员就上了，不知道什么情况（捂脸哭） 问下你们都是怎么设置的才可以借助战啊

写上开局干员的名字，再把下边两个勾上

**Comment by Kongjian8238** [comment]
我是这样设置的啊 但是就是没有借助战这个步骤 正在看外服适配尝试改代码（头秃）
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139445451/b814b709-c316-47ac-9df0-3921cb11f559)
