### ISSUE TITLE
AVD无法使用Minitouch

### ISSUE THREAD

**Issue by YiyangWilliam** [MaaAssistantArknights/MaaAssistantArknights#5355]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

avd创建模拟器无法使用Minitouch，调用minitouch返回下面内容
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52186336/d22456fe-14a3-41b8-b32a-676c9739023a)
安卓版本
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52186336/873f8ad9-071b-4b08-85b6-1518b27994dc)
两个都试过

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11997353/asst.zip)

**Comment by aa889788** [comment]
改用MaaTouch

**Comment by YiyangWilliam** [comment]
maatouch无法正常识别截图,现更换安卓版本到安卓9,能成功调用minitouch
