### ISSUE TITLE
3.9beta连接WSA后不工作

### ISSUE THREAD

**Issue by cglcv** [MaaAssistantArknights/MaaAssistantArknights#536]
日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8746937/asst.log)
连接之后毫无操作，然后显示任务完成，似乎一直在截图但没有任何动作
![image](https://user-images.githubusercontent.com/35825310/169634733-adbfa451-e16f-4ab0-adb1-a04ca944a03b.png)
![image](https://user-images.githubusercontent.com/35825310/169634738-ed06b79b-56c2-441f-8176-8c91cbe5c5cd.png)
![79screen](https://user-images.githubusercontent.com/35825310/169634744-c28a761d-8568-465a-a995-acdd94a6cb64.png)

**Comment by zzyyyl** [comment]
应该是分辨率的原因，分辨率要调整到`16:9`
[基本说明](https://github.com/MaaAssistantArknights/MaaAssistantArknights#%E5%9F%BA%E6%9C%AC%E8%AF%B4%E6%98%8E)

**Comment by cglcv** [comment]
> 应该是分辨率的原因，分辨率要调整到`16:9` [基本说明](https://github.com/MaaAssistantArknights/MaaAssistantArknights#%E5%9F%BA%E6%9C%AC%E8%AF%B4%E6%98%8E)
确实是这个问题，手动一顿乱拖窗口大小跑起来了
但WSA这东西没法用adb调分辨率就有点麻烦……
> wsa会记录应用窗口大小Physical size，在应用重启时使用，无法通过adb shell wm size 1280x720来指定分辨率
