### ISSUE TITLE
小助手执行“获取信用及购物时”，直接关闭了明日方舟

### ISSUE THREAD

**Issue by xinlingheidong** [MaaAssistantArknights/MaaAssistantArknights#5360]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94310025/74f51c0c-f2f7-4adb-bade-bcb207ef29d3)
更新后发现的错误，基建任务完成后执行信用任务时明日方舟被直接关闭。而后手动打开明日方舟并重新运行小助手信用任务则可以正常运行。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12006378/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12006379/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94310025/b60c4630-9850-48ff-b696-9f00c6d5c398)

**Comment by ABA2396** [comment]
有没有一种可能是游戏闪退了

**Comment by xinlingheidong** [comment]
> 有没有一种可能是游戏闪退了

应该不是，这个“闪退”太稳定了，三天了都这样

**Comment by xinlingheidong** [comment]
补充
我人在海外，每天只会使用两次maa，第一次是在晚上（北京时间凌晨4点后）运行maa，第二次是次日早上（北京时间15点左右）。仅在每天的第一次（即北京时间凌晨4点后，当地时间的晚上）使用maa后会出现这个情况，第二天早上则不会出现这个问题，而到了当天晚上又会出问题。这个规律很稳定。
