### ISSUE TITLE
昨晚上挂了红票，四点一过刷起了经验

### ISSUE THREAD

**Issue by Endless-dream** [MaaAssistantArknights/MaaAssistantArknights#5364]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![QQ图片20230711092825](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38717508/ffa72122-a499-4370-aa41-7681ff3dd9e0)
基础设置如图，高级设置里没有打勾

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12009811/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12009813/gui.log)

### 还有别的吗？

雷电模拟器，ADB input

**Comment by ABA2396** [comment]
掉线重连是直接进上次关卡的，但是今天红票没开

**Comment by Endless-dream** [comment]
> Member

我上次选择龙门币就没有出现这种情况，四点以后就不刷了。所以这不算bug吗？

**Comment by MistEO** [comment]
四点以后就不刷了 才是 bug

**Comment by Endless-dream** [comment]
> 四点以后就不刷了 才是 bug

哦，可以多来点这种bug吗

**Comment by Kaze-maru** [comment]
> > 四点以后就不刷了 才是 bug
> 
> 哦，可以多来点这种bug吗

《我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决》

**Comment by Endless-dream** [comment]
> > > 四点以后就不刷了 才是 bug
> > 
> > 
> > 哦，可以多来点这种bug吗
> 
> 《我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决》

好的，我来补充一下问题细节：
我在使用MAA（MaaAssistantArknights)进行辅助游戏时，从未指定MAA刷取除“红票-5”以外的任何游戏关卡，并允许MAA碎源石进行刷取。睡醒以后，我发现MAA对别的关卡进行了刷取，并且碎了我几十颗源石，我感到非常心痛。希望你们能够尽快帮我解决这个问题。

**Comment by Kaze-maru** [comment]
收到。【自动回复，勿回】
