### ISSUE TITLE
自动公招识别tag后不确认招募直接完成

### ISSUE THREAD

**Issue by emptyailen** [MaaAssistantArknights/MaaAssistantArknights#5365]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，不是第一次发生，仅保留了此次bug的截图

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12009815/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12009816/gui.log)
7-11 8:50:28处

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139189053/910ae5e8-2e72-4146-9fa8-255451088fae)

**Comment by horror-proton** [comment]
你是不是勾选了 `手动确认「支援机械」`

**Comment by emptyailen** [comment]
> 你是不是勾选了 `手动确认「支援机械」`

我并没有更改过公招的的设置，我在maa的设置界面里也没找到过手动确认【支援机械】，如果需要取消勾选，我应该在哪找到这个设置？
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139189053/cd8010ac-92c5-4eaa-85ad-f7f35fb57d4d)

**Comment by MistEO** [comment]
高级设置里
