### ISSUE TITLE
希望【自动招募】功能可以增加一个刷新到【高级资深干员】后【自动停止】的功能

### ISSUE THREAD

**Issue by HatobaMio** [MaaAssistantArknights/MaaAssistantArknights#5366]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我的六星！变成空爆了！呜呜呜呜呜呜呜呜。明明我勾选上了，结果自动招募给我取消了，然后我按下了招募键，六星没了

**Comment by ABA2396** [comment]
高级资深干员 本来就不会自动招募，都是识别到之后直接结束的，而且 `资深干员`、`高级资深干员` 未选中就招募的话游戏也会有弹窗提示

**Comment by HatobaMio** [comment]
我希望添加的是直接停止所有任务的功能。
我也不知道这次是怎么回事，我点进去后并没有停止，他可能是要退出界面，进行下一项任务。
我在公招界面用鼠标点中【高级资深干员】后，直接就按我在模拟器预设的快捷键招募了，但也许是因为MAA要退出界面，刚好和我按鼠标冲突了，导致我实际上并没有勾选上，但我按的快捷键可能没冲突，于是没勾选上就招募了。
没注意弹窗和预设了快捷键这点确实是我的问题。
