### ISSUE TITLE
10-3掉落物凝胶数量识别为0

### ISSUE THREAD

**Issue by a322655** [MaaAssistantArknights/MaaAssistantArknights#537]
没有游戏内截图（因为助手会跳过结算画面），但是掉落统计里没有凝胶，如下图所示：
![image](https://user-images.githubusercontent.com/17927678/169635337-082f0db8-8595-4ad1-9b09-9e73d5b523f8.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8746955/asst.log)

**Comment by zzyyyl** [comment]
v3.9在debug文件夹下会有掉落截图，麻烦找一下对应的截图上传一下

**Comment by a322655** [comment]
![2022-05-21_00-08-55 478_draw](https://user-images.githubusercontent.com/17927678/169637177-6366d1fc-2556-4524-b708-c051b844b55d.png)
![2022-05-21_00-14-53 689_draw](https://user-images.githubusercontent.com/17927678/169637184-2d117968-6355-4215-81ba-69206b2dbda8.png)
![2022-05-21_00-20-43 668_draw](https://user-images.githubusercontent.com/17927678/169637191-24442685-0b29-4d7c-b1e3-71b19cd08256.png)
"31013": {"name_i18n": {"en": "Coagulating Gel", "ja": "人工ゲル", "ko": "젤", "zh": "凝胶"}}
识别没有问题，但是掉落统计里不显示

**Comment by zzyyyl** [comment]
数字识别错了（

**Comment by zzyyyl** [comment]
@MistEO

**Comment by zzyyyl** [comment]
顺带把原图（没有红框框的）也传一下吧，玛丽应该需要

**Comment by a322655** [comment]
![2022-05-21_00-08-55 478_raw](https://user-images.githubusercontent.com/17927678/169637606-62634d4b-ccb7-4f0e-9f37-7cfc9aeaefe7.png)
![2022-05-21_00-14-53 689_raw](https://user-images.githubusercontent.com/17927678/169637608-a91ecc4c-012f-44fb-8502-69f627a39246.png)
![2022-05-21_00-20-43 668_raw](https://user-images.githubusercontent.com/17927678/169637614-f5d85234-e53e-4071-9b4b-0026ad5b9aa8.png)

**Comment by MistEO** [comment]
原因居然是 OCR 把 `1` 认成了 `I` 。。。

**Comment by zzyyyl** [comment]
> 原因居然是 OCR 把 `1` 认成了 `I` 。。。

草，那`10`是不是还能认成`IO`（

**Comment by MistEO** [comment]
v3.9.0-beta.2 fixed
