### ISSUE TITLE
明日方舟换回旧ui

### ISSUE THREAD

**Issue by ZiChuanShanFeng** [MaaAssistantArknights/MaaAssistantArknights#5376]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

换回旧ui了
开始唤醒又双叒叕报错了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12023369/asst.log)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/bd26e971-f82e-412b-8932-28862c1fd6aa)
没看懂，为啥你这个模板这么大？有自己改过图片吗

**Comment by ZiChuanShanFeng** [comment]
重新安装了一遍maa就好了，感谢大佬解惑
