### ISSUE TITLE
为什么水月肉鸽遇到辅助卷总是会选波登可？

### ISSUE THREAD

**Issue by wufenghuonb** [MaaAssistantArknights/MaaAssistantArknights#5379]
### 在提问之前...

- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题，我的波登可一点没练，精一一级，明明有满练的红蒂、巫恋、铃兰，哪怕希望不够，选个满级的梓兰也好，结果他老是选波登可，我也不想耗资源练她，毕竟要备战夏活，作者铁暗恋（

### 有什么好的想法？

可以加个禁用干员或必选干员吗，那样感觉会方便很多

### 其他内容

每局都如此，每次我看都有波登可

**Comment by wufenghuonb** [comment]
说错了，我的波登可精0一级，真正意义上的没碰过

**Comment by Clazex** [comment]
dup #5143，[原因](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/4675#issuecomment-1585735265)

**Comment by joshua0blake** [comment]
我0练度波灯可一直选
