### ISSUE TITLE
更新到3.9 beta之后连不上模拟器了

### ISSUE THREAD

**Issue by maidangdang1** [MaaAssistantArknights/MaaAssistantArknights#538]
！！！请尽可能详细的描述你遇到的问题，并附上助手软件目录下的 `asst.log` 日志文件！！！

！！！日志文件是可以直接拖拽进来的，没有日志文件的 bug 反馈我会直接关掉！！！

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8747200/asst.log)
![image](https://user-images.githubusercontent.com/46847241/169641594-1c784438-97b2-4e55-a3e0-025519b01231.png)
![image](https://user-images.githubusercontent.com/46847241/169641599-3d7b9e0b-4dd1-46ca-a0eb-7a07dd98e9f0.png)
看了下日志，好像一直连到了2970端口，不知道为啥
模拟器是蓝叠hyper-v版

**Comment by Nagico** [comment]
![image](https://user-images.githubusercontent.com/25633151/169650776-cb6c9966-2836-4636-8ff1-593a4cf3db1c.png)
设置里配置有没有问题呢？我这边可以正常连到Hyper-V版本的bluestacks

**Comment by Szrso** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8747873/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8747874/asst.bak.log)
换了好几个模拟器都是链接失败，逍遥，蓝叠，夜神都不行

**Comment by ABA2396** [comment]
先用之前的版本吧

**Comment by MistEO** [comment]
问题原因是 wpf 中 editable 的 combbox, 当你填入不存在的选项时，实际的值会是 null 

感觉这玩意设计有问题（~~微软罪大恶极~~

**Comment by MistEO** [comment]
v3.9.0-beta.2 fixed
