### ISSUE TITLE
雷电模拟器：对路径“adb.exe”的访问被拒绝。

### ISSUE THREAD

**Issue by 124376a** [MaaAssistantArknights/MaaAssistantArknights#5382]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

对路径“adb.exe”的访问被拒绝。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12026901/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12026902/gui.log)
7/12/18:XX

### 截图

![微信图片_20230712190535](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/25455076/f212fa9d-d2f2-42fa-a052-a03b3ee3fa50)

### 还有别的吗？

雷电模拟器 win10 21H2 企业版LTSC

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7a557934-beb1-469a-8db9-a98ab8b635e0)
连接地址写的要是模拟器端口，不是adb路径，不知道的话就用自动检测
