### ISSUE TITLE
希望能在像"自动战斗"页面增加一个清空头像缓存(cache\avatars目录)的功能按钮

### ISSUE THREAD

**Issue by LonelyWindG** [MaaAssistantArknights/MaaAssistantArknights#5384]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

切换多个账号使用自动战斗功能时, 不同账号的干员皮肤不一样导致头像不同, 影响自动战斗下干员(不确定是不是因为头像缓存)

### 有什么好的想法？

功能需求如标题所述

**Comment by ntgmc** [comment]
如果是头像不同不会影响 因为检测到不同的头像会重新缓存一次

**Comment by LonelyWindG** [comment]
> 如果是头像不同不会影响 因为检测到不同的头像会重新缓存一次

那就怪了, 有时候不知道为什么不下干员

**Comment by LonelyWindG** [comment]
> 如果是头像不同不会影响 因为检测到不同的头像会重新缓存一次

请问头像缓存是每次战斗开始时加载本地目录缓存还是缓存驻留内存(每次启动后需要识别时加载本地缓存到内存)?
夏活这几个版本总是出现干员识别不到或者识别错乱的问题(看了下缓存目录发现这个干员的头像是另一个的), 这时候我都是删了头像缓存或者删了识别错乱的干员, 然后再重启MAA(因为不知道缓存是不是驻留内存)的;
