### ISSUE TITLE
夜神模拟器游戏闪退

### ISSUE THREAD

**Issue by joshua0blake** [MaaAssistantArknights/MaaAssistantArknights#5387]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我在多开夜神模拟器时，最初的模拟器使用maa运行时官服游戏会闪退u

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12036917/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12036918/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125282918/5b9a6166-65d2-46e2-975e-894c5575041c)

**Comment by joshua0blake** [comment]
我另一个多开的模拟器能正常运行

**Comment by ntgmc** [comment]
这个是夜神模拟器的问题，非MAA问题，请联系夜神客服/更换模拟器
