### ISSUE TITLE
自动安装更新包导致的未响应

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#5391]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/5495374e-5dfd-4d2a-bcf8-81115b31db53)
未响应的是右边的，左边的正常下完之后更新了，ota实际上应该下完了
关掉重启之后正常解压更新，应该还是自动安装更新包的问题

### 日志文件

[asst (2).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12041475/asst.2.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12041476/gui.log)

**Comment by ABA2396** [comment]
自动安装更新包要任务结束后才会安装
