### ISSUE TITLE
任务完成后报错更新包被占用

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#5392]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/c680f8f9-50af-4f1e-954f-b758747f1e90)
这个报错是任务结束之后弹的
重新打开maa仍然报错
任务管理器关闭adb.exe重新打开后正常解压更新
不清楚是bug还是特性

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12041621/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12041622/gui.log)

**Comment by arashi-knight** [comment]
我也存在这个问题，可能是先打开模拟器后开maa的问题？
