### ISSUE TITLE
雷电模拟器 MAA对路径“adb.exe”的访问被拒绝

### ISSUE THREAD

**Issue by DualEgo** [MaaAssistantArknights/MaaAssistantArknights#5395]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

雷电模拟器版本：9.0.50
运行MAA时出现模拟按键位置偏移导致无法正常“一键长草”（分辨率1920x1080和1080x1920均使用过）
遂试图强制替换ADB使用 minitouch, maatouch 等高效的触控模式，出现BUG
详细信息：System.UnauthorizedAccessException: 对路径“adb.exe”的访问被拒绝。
   在 System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   在 System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ReplaceADB>d__454.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12045331/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12045332/gui.log)
出现时间 北京时间2023/7/14 8:20-8:30左右

### 还有别的吗？

雷电模拟器9.0.50
Windows 11 22H2家庭中文版
ROG魔霸7plus （AMD 7845HX+RTX 4060）

**Comment by xiaoweiXX** [comment]
你重启MAA试试，我用雷电4是小概率碰到这种问题，一般重启MAA就行（但是这个bug一直没修复）

**Comment by ntgmc** [comment]
任务管理器强制结束进程就行
或者打开cmd输入`taskkill /f /im adb.exe`
