### ISSUE TITLE
建议增加自动换号功能

### ISSUE THREAD

**Issue by doctor318** [MaaAssistantArknights/MaaAssistantArknights#5397]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有时候存在很多号要玩，但又不想手动换号，所以填了这个issue

### 有什么好的想法？

基于图像识别，先检测当前账号并记录，通过让使用者预输入账号（该账号已存有在客户端），识别一个与原先记录的账号不同的在MAA存储的对应账号。

**Comment by xiaoweiXX** [comment]
怎么还有人发这个（
开发者说了这是商业化需求不会去做
