### ISSUE TITLE
在使用MAA连接到夜神模拟器时，MAA闪退

### ISSUE THREAD

**Issue by abbaccadd0** [MaaAssistantArknights/MaaAssistantArknights#540]
## 问题版本
3.9.0-beta

## 问题描述
在使用MAA连接到夜神模拟器时，MAA闪退

## 软件截图
![Snipaste_2022-05-21_21-08-03](https://user-images.githubusercontent.com/39579855/169652941-a87430d4-ec3d-4a4e-96ff-e9a507c9a622.png)
点击Likn Start后
![Snipaste_2022-05-21_21-08-21](https://user-images.githubusercontent.com/39579855/169652984-63aab2f3-f702-459f-8b83-f610128109d7.png)
消失了

## asst.log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8747646/asst.log)

**Comment by qianxu2001** [comment]
蓝叠 64 位版同问题

**Comment by MistEO** [comment]
v3.9.0-beta.2 fixed
