### ISSUE TITLE
死囚之夜中干员的部署位置和方向有问题

### ISSUE THREAD

**Issue by percy4** [MaaAssistantArknights/MaaAssistantArknights#5403]
### 说说你遇到的问题？

包括但不限于羽毛笔和百嘉部署朝上打不到下面的怪海，水陈也放在上面的位置。
<img width="431" alt="ea757a7cc52ead6395550d06a7139d1e" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/65449779/01e309db-4797-4c49-a638-c8630c2b2cd6">

**Comment by AkiTsukii** [comment]
臣附议

**Comment by NanChenSAMA** [comment]
使用后勤分队刷钱，时常会在这个地方战斗失败，直接结束一局游戏
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/51527705/3aad0555-01cb-48c0-b419-d3e116df6194)

**Comment by TobyLi223** [comment]
你以为死囚是谁

**Comment by tayasu9801** [comment]
设置均是按照说明设置的情况下，有几率出现死囚之夜摆放随从时卡死，即无法在摆放随从后选择随从朝向，卡在选择随从朝向的慢速界面

**Comment by luhuo** [comment]
似乎是萨米战斗的配置文件没有写，所以等等吧……

**Comment by luhuo** [comment]
> ### 说说你遇到的问题？
> 
> 包括但不限于羽毛笔和百嘉部署朝上打不到下面的怪海，水陈也放在上面的位置。 <img alt="ea757a7cc52ead6395550d06a7139d1e" width="431" src="https://user-images.githubusercontent.com/65449779/253621848-01e309db-4797-4c49-a638-c8630c2b2cd6.png">
似乎是萨米战斗的配置文件没有写，所以等等吧……

**Comment by ArtOriation** [comment]
百嘉放石头上面等碎一个柱子一轮技能就过了
现在站位太抽象了
凯尔希的m3也放门口了，怪全部打柱子激活强化冲家

**Comment by WeCanLandHere** [comment]
附议，投钱，这个地图日常战败

**Comment by c-x-b** [comment]
我在#5414里提供了一个默认百嘉开的临时措施~其他干员开等更新吧 这个应该挺快的

**Comment by SherkeyXD** [comment]
fixed in #5430

**Comment by SherkeyXD** [comment]
Fixed in b637f7b

**Comment by SherkeyXD** [comment]
Fixed in b637f7b2b89e1e29d2deaee3ee9ef18a1ee06eac
