### ISSUE TITLE
萨米肉鸽会卡在节点： 鲍勃杂货店

### ISSUE THREAD

**Issue by yc080713** [MaaAssistantArknights/MaaAssistantArknights#5404]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

rt

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12052567/asst.log)

### 截图

![鲍勃杂货店](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92996760/e7686e05-8d58-4b17-83bb-c7decfeb8aed)

### 还有别的吗？

图为模拟器内置截图，分辨率为1280*720 320dpi

**Comment by douyacai312** [comment]
同样卡在鲍勃杂货店，模拟器为蓝叠国际版，分辨率1920*1080
<img width="980" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131654380/647eba06-958a-4868-bac1-3cb19faed24f">

**Comment by liangs333** [comment]
同样，必现，只要出现三个选项的节点就会卡住。

**Comment by SherkeyXD** [comment]
为方便管理，后续讨论移至 #5418
