### ISSUE TITLE
萨米肉鸽：部分不期而遇节点大概率长时间不作选择，造成卡死

### ISSUE THREAD

**Issue by ldcivan** [MaaAssistantArknights/MaaAssistantArknights#5405]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，当运行到不期而遇节点（鲍勃杂货铺以及沼泽里的抽泣声）时，程序大概率长时间不作选择，造成流程卡死

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12052732/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12052748/asst.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/69411867/0dc43e4f-462f-43da-b447-d2f3c9f15746)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/69411867/9513d458-99a3-458d-bd46-5c02b17ba5da)

### 还有别的吗？

Win10  雷电模拟器

**Comment by ldcivan** [comment]
怀疑是选中选项时，点击动作坐标未对准选项。因为当手动选中某一个选项时，程序马上就会确认选项。

**Comment by MuuuShin** [comment]
附议，不期而遇主要为"沼泽中的抽泣声"不进行选择导致的卡死

**Comment by KUAPT** [comment]
不是不做选择，而是一直选一个不能被选择的选项，例如所有要求抗干扰指数的选项

**Comment by SherkeyXD** [comment]
更新到最新内测版试试

**Comment by SherkeyXD** [comment]
相关讨论移至 #5418，该 issue 先关闭
