### ISSUE TITLE
萨米肉鸽停留在得偿所愿

### ISSUE THREAD

**Issue by bzbbm** [MaaAssistantArknights/MaaAssistantArknights#5406]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽停留在得偿所愿，不会选择藏品

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12052789/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12052799/asst.zip)

### 截图

![Screenshot_2023 07 15_01 50 03 293](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139579987/e78b6f53-dc32-46d4-8fd6-df9bab6e43fd)

**Comment by SherkeyXD** [comment]
讨论移至 #5418，该 issue 先关闭
