### ISSUE TITLE
萨米肉鸽停在不期而遇

### ISSUE THREAD

**Issue by NekoVicky** [MaaAssistantArknights/MaaAssistantArknights#5407]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

不期而遇不会自己打哭狗或者逃战

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12054018/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12054020/gui.log)

### 截图

![Y P)T%NNHDD40(}HR CN5OU](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40619465/6d635366-082c-477f-88f0-8a7156d3b3d0)

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40619465/b52d1632-f129-4453-b91e-618b9b8a3c15)

**Comment by NekoVicky** [comment]
群友反应鸭子也卡

**Comment by surrengtwwy** [comment]
刷源石锭模式在第一层商店不投资，直接退了

**Comment by SherkeyXD** [comment]
更新到最新内测版试试

**Comment by SherkeyXD** [comment]
相关讨论移至 #5418，该 issue 先关闭
