### ISSUE TITLE
萨米肉鸽 有利可图关卡 抗干扰小于三会一直点大于抗干扰三的选项

### ISSUE THREAD

**Issue by Wjh2577** [MaaAssistantArknights/MaaAssistantArknights#5410]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽 有利可图关卡 抗干扰小于三会一直点大于抗干扰三的选项

### 日志文件

7.15日9.35左右
[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12060030/asst.-.log)

**Comment by yc080713** [comment]
来补充一下
![有利可图](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92996760/51988301-ae43-4b2f-a2d2-76f1c0d1cd01)

**Comment by Loxer2023** [comment]
![QQ图片20230715154609](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139615772/2403a51b-169a-4596-9ac6-e04c81703a1a)
不知道这个是不是同样的原因，总之一直停在这里了

**Comment by xiaoweiXX** [comment]
> ![QQ图片20230715154609](https://user-images.githubusercontent.com/139615772/253728037-2403a51b-169a-4596-9ac6-e04c81703a1a.jpg) 不知道这个是不是同样的原因，总之一直停在这里了

也有可能🤔我一直听到有点按钮的声音

**Comment by challot** [comment]
他会一直反复点击那个选不了的选项，电脑会一直发出点按钮的声音，然后一直卡在这里

**Comment by MagakiReimu** [comment]
内测版可以先加一个简单逻辑规避一下类似的不期而遇，如果30秒内点选最后一个选项没有反应，就点击倒数第二个，依此类推

**Comment by SherkeyXD** [comment]
更新到最新内测版试试

**Comment by SherkeyXD** [comment]
相关讨论移至 #5418，该 issue 先关闭
