### ISSUE TITLE
萨米肉鸽死囚之夜战术优化建议

### ISSUE THREAD

**Issue by Nobi-kamo** [MaaAssistantArknights/MaaAssistantArknights#5414]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

萨米肉鸽死囚之夜里会吧干员摆在靠近蓝门的位置，等怪打碎石头冲出来的时候数量太多栏不下来，会扣大量生命值，还可能直接导致作战失败

### 有什么好的想法？

建议优化一下MAA的战术，把干员集中在两个石头附近，提高完美作战概率，至少到目前我的MAA都没完美作战过死囚之夜

**Comment by c-x-b** [comment]
在MAA目录的resource/rougelike/copilot.json最后的']'之前加上以下内容，在默认的百嘉开情况下应该就能完美打
```json
    {
        "stage_name": "死囚之夜",
        "replacement_home": [
            {
                "location": [
                    4,
                    2
                ],
                "direction": "down"
            }
        ]
    }
```

注意上一行的的'}'后面要补个英文逗号，改完之后最后应该是这样的
```json
...
    {
        "stage_name": "斗兽笼",
        "replacement_home": [
            {
                "location": [
                    5,
                    3
                ]
            }
        ]
    },
    {
        "stage_name": "死囚之夜",
        "replacement_home": [
            {
                "location": [
                    4,
                    2
                ],
                "direction": "down"
            }
        ]
    }
]
```

但是我不太清楚如果没百嘉开默认是用什么，可能用不了

**Comment by DokiDokiAyashi** [comment]
可以把位置改成下面的石头的左边，怪分波来敲石头都会被清掉

**Comment by c-x-b** [comment]
[copilot.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12061135/copilot.zip)
我看到有人写了个 应该是能用的 直接解压替换resource\roguelike\中对应的文件就行

**Comment by cloudinmind** [comment]
现在已经是稳定选择嘉维尔了，但在死囚之夜这张图里摆放的位置还是有问题，朝向反而是正确的。
挪到石头下面正正好好。

**Comment by 24082569** [comment]
没有百嘉会默认用山，每次遇到这一关都会跪TAT
希望能有一个令开局选项，只能刷源石锭也行

**Comment by SherkeyXD** [comment]
fixed in #5430
