### ISSUE TITLE
手动输入关卡优化为可选择可输入

### ISSUE THREAD

**Issue by KawausoJyou** [MaaAssistantArknights/MaaAssistantArknights#5417]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前「刷理智」切换选择关卡、输入关卡需要在「常规设置」「高级设置」反复开关切换，可以优化。

### 有什么好的想法？

输入框既可以选择，也可以输入。

**Comment by ABA2396** [comment]
已开放的关卡下面都有关卡提示，而且手动输入的情况下常驻的资源关只需要输入下方提示的两个首字母就能直接转成关卡名

**Comment by KawausoJyou** [comment]
> 已开放的关卡下面都有关卡提示，而且手动输入的情况下常驻的资源关只需要输入下方提示的两个首字母就能直接转成关卡名

那是否可以增加显示下一天开放的关卡？方便睡前挂机修改好（我是本笔，120级了也记不住周几开放什么🤦‍♂️

**Comment by ABA2396** [comment]
> > 已开放的关卡下面都有关卡提示，而且手动输入的情况下常驻的资源关只需要输入下方提示的两个首字母就能直接转成关卡名
> 
> 那是否可以增加显示下一天开放的关卡？方便睡前挂机修改好（我是本笔，120级了也记不住周几开放什么🤦‍♂️

这种情况更建议用备选关卡，提前设置好想要刷的关卡，会寻找第一个匹配上的已开放关卡
