### ISSUE TITLE
[萨米肉鸽] 因抗干扰指数要求卡在不期而遇/得偿所愿等节点

### ISSUE THREAD

**Issue by BigSaltyMan** [MaaAssistantArknights/MaaAssistantArknights#5418]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa有时候会在鲍勃杂货店选藏品的时候呆住不动

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12061068/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12061071/asst.log)
在17:35左右

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119373376/65272394-4172-40e1-9fff-e5d613069d25)

### 还有别的吗？

用的mumu12 win11系统

**Comment by xiaoweiXX** [comment]
遇到了同样的问题，我听到了点击按钮的声音，但是不知道为什么藏品的选项没出来，我手点选项才出来🤔用MAA打了两三把了，没把都是这样

**Comment by ZiChuanShanFeng** [comment]
点击任意一个选项，maa仍然可以继续，估计是程序的识别图片大小或者点击位置出现问题

**Comment by xiaoweiXX** [comment]
> 点击任意一个选项，maa仍然可以继续，估计是程序的识别图片大小或者点击位置出现问题

应该不是，到商店这里你听听有没有按按钮的声音，如果有的话应该是方舟的问题（因为MAA已经点了按钮了）

**Comment by SherkeyXD** [comment]
fixed in #5408

**Comment by ZiChuanShanFeng** [comment]
![Snipaste_2023-07-15_19-28-31](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139305401/cc1f7c15-7d01-484a-9eb0-83f3d4353de2)
![Snipaste_2023-07-15_19-29-32](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139305401/2cf912d4-ecb0-4806-bc12-18f899f43cf5)
是这样的吗？

**Comment by nssssfw** [comment]
额，更新完了我这里还是回卡住，不知道为什么，是要等很长一段时间才会正常嘛？还是怎么。感觉不会选择上面的选项来回避下面那个选项

**Comment by xiaoweiXX** [comment]
说实在的可以改一下鲍勃商店的逻辑，可以先点三五下最下面的选项，如果没反应就改点中间选项三五下，还不行就点最上面的。最好的办法还是检测图片、颜色之类的选项，检测到选项不能点就直接选能点的。

**Comment by zengshuyu** [comment]
更新到测试版的[alpha/v4.19.4-alpha.1.d070.g76f4ed3df]之后，依然有遇到这个问题
模拟器为夜神，分辨率1920*1080，截图如下
<img width="960" alt="微信截图_20230715222026" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46372839/510096c6-8dbc-425e-8093-45cd95e73c52">

**Comment by SherkeyXD** [comment]
> 说实在的可以改一下鲍勃商店的逻辑，可以先点三五下最下面的选项，如果没反应就改点中间选项三五下，还不行就点最上面的。最好的办法还是检测图片、颜色之类的选项，检测到选项不能点就直接选能点的。

有个问题是，高抗干扰度要求的藏品不一定比上面的藏品好

以及最新测试版的逻辑已经改为直接点击最上面选项了

**Comment by ChihayaCyo** [comment]
最新版本还是遇到了，和这个描述一模一样

**Comment by HYY1116** [comment]
更新至最新版本maa后仍然存在这个问题

**Comment by yyjdelete** [comment]
重新传一张`Sami@Roguelike@StageEncounterOptionUnknown.png`会不会好点, 现在那张有点太偏左下了, 大概有1/8~1/4的区域都和藏品图标重叠了, 我看了下我的log上面的两个按钮都没识别到

**Comment by SherkeyXD** [comment]
> 更新至最新版本maa后仍然存在这个问题
是最新内测版吗

**Comment by wordly123** [comment]
还是卡在这里了 mumu12 版本号如下
![1689514082768](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/21117763/ad7abb47-b9bc-41b4-b706-cc41193ad629)

![1689513964701](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/21117763/d9461f82-ff18-4319-95eb-189b7cc9281e)
@SherkeyXD

**Comment by SherkeyXD** [comment]
> ![1689513964701](https://user-images.githubusercontent.com/21117763/253806514-d9461f82-ff18-4319-95eb-189b7cc9281e.png) 

发个日志看看

**Comment by MistEO** [comment]
@wordly123 d104 修的

**Comment by RheniumMOX** [comment]
找到一种解决方法，至少目前两个小时了没被卡住
打开MAA安装目录\resource\roguelike\stage_encounter.json，按Ctrl+F搜鲍勃杂货店，下面的"choose": 1改成2，好像就不会卡住了，我再挂一晚上试试
好像这句话的意思是默认选择第几项，我看好像没有“选择他手中的货品”这个选项，所以就在想是不是这个原因
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/22649820/dd1911d4-c14f-4062-8bcd-c837e2ea0c5a)

**Comment by whylj1527** [comment]
> 

怎么样，问题解决了吗

**Comment by ZiChuanShanFeng** [comment]
只要是三个选项的基本都卡住

**Comment by SherkeyXD** [comment]
为方便管理，所有卡在不期而遇/得偿所愿的讨论移到此 issue 下

已知问题列表
- 鲍勃杂货铺
- 打鸭子/打狗狗

最新内测版已经尝试修复此问题，可以更新测试一下

**Comment by ZiChuanShanFeng** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139305401/5576b26e-c0af-4835-acd9-6655ab4a3c36)
这个也卡住了

**Comment by SherkeyXD** [comment]
> ![image](https://user-images.githubusercontent.com/139305401/253939251-5576b26e-c0af-4835-acd9-6655ab4a3c36.png) 这个也卡住了

先行一步问题已在 737e66f 中修复

**Comment by SherkeyXD** [comment]
f

**Comment by Constrat** [comment]
@SherkeyXD This has been happening in the global pretty much every time.
- #8613

**Comment by Heacatew** [comment]
MAA在最新的公测5.81版本连接mumu12模拟器，刷萨米肉鸽时遇到鲍勃杂货铺节点依旧会卡住不动，无法选择有效的选项且一直卡在选择界面，严重影响挂机萨米肉鸽效率，求解决方法或更新解决此问题

![萨米卡住](https://github.com/user-attachments/assets/6855e3bd-8f90-481d-8b99-134d4630c9ce)
![卡死](https://github.com/user-attachments/assets/52a59caa-517a-489d-aa0c-9cec99acd50a)


[gui.log](https://github.com/user-attachments/files/17592425/gui.log)（卡住问题出现在3:11处）

**Comment by gsxgmpkt9020** [comment]
怎么关掉了？确认鸭爵主演还是过不了

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/7128#issue-1967876437
