### ISSUE TITLE
萨米肉鸽未适配高规格分队开局

### ISSUE THREAD

**Issue by cybearfish** [MaaAssistantArknights/MaaAssistantArknights#5419]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在招募界面停留一段时间后没有招募就放弃探索了，应该还没做高规格分队开局的相关适配（右边那个是随机的）
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/112690111/b24ec7d7-be20-4da7-9887-3f4717fe9e40)

### 有什么好的想法？

（多一个人刷源石锭的时候会不会稳定一点）

**Comment by SherkeyXD** [comment]
如果只是刷源石锭的话建议指挥分队开局
至于是否适配了高规格分队开局，给个日志会好分析很多

**Comment by cybearfish** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12061238/asst.log)
19点过的，最新的那几个部分，开了几次都不行
