### ISSUE TITLE
关于基建换人方式的建议

### ISSUE THREAD

**Issue by CoffeeRong** [MaaAssistantArknights/MaaAssistantArknights#542]
目前基建换人方式是从基建界面开始，点击每一间房间，在对房间进行跟换人员。
优点，emmm层次分明？顺序性强？
缺点，感觉慢了，每次都要重新识别挺费劲

希望改进，从基建界面左上角“进驻总览”选择，可以很方便的修改进驻干员
优点，快速，简介明了？
缺点，要改大堆代码

最后，感谢码主的付出与奉献，希望未来更美好

**Comment by MistEO** [comment]
不行的，从总览进去没有办法知道每一个站在造什么。。

**Comment by dhujsi** [comment]
进驻总览那里分层和房间排列顺序很明确，如果提前点进去看一眼（隔壁另外一个助手是这么干的）或者手动输入第几层第几个房间是造什么的，可以一一对应
这样选中房间的时候左下角会给出心情的具体数值，还有进入换干员的界面不需要等待动画效果。只是有点多此一举，感觉确实没必要为了这一点大改

**Comment by MistEO** [comment]
> 进驻总览那里分层和房间排列顺序很明确，如果提前点进去看一眼（隔壁另外一个助手是这么干的）或者手动输入第几层第几个房间是造什么的，可以一一对应
> 这样选中房间的时候左下角会给出心情的具体数值，还有进入换干员的界面不需要等待动画效果。只是有点多此一举，感觉确实没必要为了这一点大改
> 

提前点进去看一眼就和现在没有区别了。手动输入就是效果下降了（

**Comment by MistEO** [comment]
或许控制中枢，发电站，这些干员与产品无关的设施，可以从进驻总览进去换
