### ISSUE TITLE
萨米肉鸽-低空行动-干员摆放建议

### ISSUE THREAD

**Issue by Pinng999** [MaaAssistantArknights/MaaAssistantArknights#5420]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

<img width="570" alt="Snipaste_2023-07-15_18-35-57" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108909863/7f987567-b8f0-43cb-9b0f-59feca272072">

### 有什么好的想法？

虽然我没什么好的通关思路，但是我觉得近战单位不应该放下边

**Comment by R2004258** [comment]
中间那个高台也能放个单位吸引飞行兵让其掉坑吧

**Comment by Pinng999** [comment]
> 中间那个高台也能放个单位吸引飞行兵让其掉坑吧

飞行兵的机制是无外界影响一直加速，到达指定速度起飞，但是攻击不会减速，所以高台只能用减速或者其它控制才能掉坑（沉默好像也可以）

**Comment by KawausoJyou** [comment]
在蜜莓左边三格的高台部署一个干员吸引火力，好像就飞不起来了。（存疑

**Comment by ArtOriation** [comment]
下面吹风机吹到的高台摆个干员，飞行兵就飞不起来了
