### ISSUE TITLE
roguelike 处在继续页面不断退出重进

### ISSUE THREAD

**Issue by ZiChuanShanFeng** [MaaAssistantArknights/MaaAssistantArknights#5422]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![Snipaste_2023-07-15_20-48-40](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139305401/f1a20821-fb8a-4032-9317-894983a4bebd)
在这个页面时不断退出重进，需要手动结束探索后才能继续

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12061422/asst.zip)

### 截图

![Snipaste_2023-07-15_20-48-40](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139305401/f1a20821-fb8a-4032-9317-894983a4bebd)

**Comment by testpaper007** [comment]
因为这个界面没有放弃按钮吧，你上一次肉鸽手动退出了，卡在结算界面就这结果

**Comment by Shawnsdaddy** [comment]
遇到了同样的情况

**Comment by SherkeyXD** [comment]
From #5489
放弃按钮消失的问题可由肉鸽中途掉线/闪退触发
