### ISSUE TITLE
希望保全派驻开局能替换掉“超重绝缘水泥"

### ISSUE THREAD

**Issue by morikumappa** [MaaAssistantArknights/MaaAssistantArknights#5423]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

跑了很多次保全作业，发现开局 ”超重绝缘水泥“ 十分影响保全作业的通过率

### 有什么好的想法？

希望在读图完成后先判断是否有”水泥“，如有选择替换，没有直接跳过

**Comment by status102** [comment]
link to #7347
