### ISSUE TITLE
蓝叠模拟器无法连接

### ISSUE THREAD

**Issue by KUAPT** [MaaAssistantArknights/MaaAssistantArknights#5428]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

蓝叠模拟器无法连接，昨天突发。（发生时间大概从15日晚10点往后至今）
已尝试更换稳定版，最新内测版，强制替换ADB，使用本地ADB，自动检测连接
均无法连接到模拟器，且点击停止时MAA会卡死

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12063137/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12063138/asst.log)

### 还有别的吗？

蓝叠模拟器
WIN11 
联想R9000P AMD R9 7945HX    NV RTX4060laptop

**Comment by t111111111** [comment]
同

**Comment by ICraZY-EE** [comment]
也有这个问题，我是从六月底就偶发，中间有段时间正常，最近一次更新后又出现，需要重启MAA才能成功连接

**Comment by t111111111** [comment]
已解决，关闭ADB后触控模式使用ADB input

**Comment by jiangbian51** [comment]
另外使用自动存钱功能时运行一段时间后会发生卡顿和操作失误，不确定是电脑性能问题还是兼容性问题

**Comment by yc080713** [comment]
是否已开启adb调试选项？
![QQ截图20230716123059](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92996760/951a609b-1140-4a7e-93d1-a39347297c60)
是否尝试过[自定义连接](https://maa.plus/docs/1.1-%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%9E%E6%8E%A5)？

**Comment by KUAPT** [comment]
> 是否已开启adb调试选项？ ![QQ截图20230716123059](https://user-images.githubusercontent.com/92996760/253785075-951a609b-1140-4a7e-93d1-a39347297c60.png) 是否尝试过[自定义连接](https://maa.plus/docs/1.1-%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%9E%E6%8E%A5)？

全都检查过，均已开启和尝试

**Comment by SherkeyXD** [comment]
在你的 gui.json 中发现一个规律：当 MAA 的安装路径为 `..\AUTO` 时可以运行，而为 `..\AUTO(稳定版)` 时运行错误

因此，我建议你把 MAA 安装目录名称中的中文去掉试试

**Comment by huoxianribao** [comment]
怀疑：maa设置界面的adb路径多了一个/./
今天我新装了蓝叠，也遇到了这个问题，手写地址才解决的

**Comment by SherkeyXD** [comment]
现在的版本还有此问题吗？如果有的话可以提交新的日志，这会有助于我们分析

**Comment by ICraZY-EE** [comment]
公测版上午刚遇到
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12211156/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12211157/gui.log)
![tmpC7DD](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57562450/bbd2fcde-8d85-4ed4-89ad-bc05e8e3e498)

**Comment by zhongfly** [comment]
最新内测版又遇到了，一直停在“连接模拟器”这一步2分钟，然后我点停止，也没有停止。最后只能关闭maa窗口。
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12214379/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12214380/asst.log)

**Comment by Jonesau** [comment]
可以尝试手动结束adb任务进程
操作路径
关闭蓝叠+maa -> 打开windows任务管理器 -> 搜索HD-Adb -> 结束进程 ->  重启蓝叠+maa
