### ISSUE TITLE
自动公招时能将识别到的5星Tags组合用特殊颜色标出来

### ISSUE THREAD

**Issue by SovietBall** [MaaAssistantArknights/MaaAssistantArknights#5429]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

当我使用自动公招并识别到5星Tags时，可能会出现以下情况：
“公招识别结果：
近战位
远程位
爆发
输出
群攻”
此时并不能第一时间在脑海里想到相对应的5星Tags组合 往往会在手动处理时遗漏。

### 有什么好的想法？

希望自动公招时能将识别到的5星Tags组合用特殊颜色标出来。

### 其他内容

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43679747/1a9b35dd-800f-4946-a03c-66c2f5ae6250)

**Comment by ABA2396** [comment]
小工具里也有个公招识别，那个会自动选tag但不招募

**Comment by SovietBall** [comment]
> 小工具里也有个公招识别，那个会自动选tag但不招募

好哦 目前情况下咱也想不到什么其他的改良界面的点子（x）
非常抱歉打扰啦——
