### ISSUE TITLE
添加一个暂停键，使得当需要干别的事情时不结束正常的maa进程

### ISSUE THREAD

**Issue by qaz1qazlol2** [MaaAssistantArknights/MaaAssistantArknights#5434]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

每一次都需要重新走maa的流程，尤其是在肉鸽里，挺麻烦的

### 有什么好的想法？

标题

**Comment by ABA2396** [comment]
暂停在现在的构架下基本不太可能。但是肉鸽你停止之后在大地图里重新开始任务是可以继续打下去的

**Comment by qaz1qazlol2** [comment]
这样啊，我在之前的版本里是无法这么干的，之后试一下
