### ISSUE TITLE
萨米肉鸽第一层不投资源石锭

### ISSUE THREAD

**Issue by e0kt** [MaaAssistantArknights/MaaAssistantArknights#5439]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽第一层不投资源石锭，会买右边的起重机/补给站等支援道具
问题出现时间：2023/07/15 22:11

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12063329/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12063330/gui.log)

### 截图

![I H {NB_~XM1QR0Z %SS($X](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/23226657/7599113b-af62-46a2-a08a-d4117781e79b)
![Y~8SI GO0A)68`S4F`}7 SP](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/23226657/cf39c41c-0880-423e-8103-003c64f91104)
模拟器的截图是后面复现了一下再截的，因为第一层打完MAA自动重开所以第一次没来得及截

### 还有别的吗？

模拟器：夜神模拟器
操作系统：win11

**Comment by SherkeyXD** [comment]
Duplicate of #5437
