### ISSUE TITLE
萨米肉鸽会卡在节点： 沼泽里的抽泣声

### ISSUE THREAD

**Issue by yc080713** [MaaAssistantArknights/MaaAssistantArknights#5440]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

rt

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12063374/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12063376/asst.log)
卡住的地方手点了一下，操作后我才想起保存（麻烦往上翻翻）

### 截图

![Screenshot_2023 07 16_13 37 39 516](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92996760/d2380f24-2ee9-4e94-a7fe-dca1dfd6b52f)

### 还有别的吗？

图为模拟器内置截图，分辨率为1280*720 320dpi

**Comment by SherkeyXD** [comment]
Duplicate of #5407
