### ISSUE TITLE
保全约翰老妈第六层进入选人界面后停止

### ISSUE THREAD

**Issue by dmpld** [MaaAssistantArknights/MaaAssistantArknights#5441]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如标题

### 日志文件

[1.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12063378/1.zip)

### 截图

![Screenshot_20230716-134642](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87512811/b6d28d9f-ec03-4774-8784-7336fd5cf8c1)

### 还有别的吗？

雷电模拟器

**Comment by Rbqwow** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55343783/9d26a18e-4678-4e19-875a-090ae6690202)
