### ISSUE TITLE
更改萨米肉鸽在遇到三个选项时的逻辑

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#5442]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用内测版MAA刷萨米肉鸽的时候，只要是遇上带有三个选项的节点（不论是鲍勃商店这种得偿所愿节点，还是鸭爵等可以变化成战斗的不期而遇节点），都会有概率碰到有选项要求抗干扰指数，而MAA试图去点这些选项。

### 有什么好的想法？

这种情况可以试着改变一下逻辑，比如得偿所愿优先点击可选的选项（而非更好的藏品），不期而遇直接点第三个离开（不明白这里为什么会卡住，但是我确实遇到过这种不期而遇卡住的情况）。
当然，如果能够直接识别选项是否可选那自然更好，这样可以挑选更合适的藏品。

**Comment by xiaoweiXX** [comment]
亦或者还是按照优先选择更好的选项（比如藏品和战斗），但是检测到带有三个选项的节点，并且在几次点击选择点击之后，画面依旧不变，可以改变逻辑，选择另外的选项（得偿所愿选择第一项，不期而遇选择离开）

**Comment by zzd2674437069** [comment]
我也是，我的鲍勃商店和鸭爵会无法识别和选择选项，手动点击某个选项后才会继续进行探索，似乎对于三选项节点的判断逻辑有问题

**Comment by 0212Infinity** [comment]
I've encountered the same issue.
