### ISSUE TITLE
萨米肉鸽-鲍勃杂货店-卡住

### ISSUE THREAD

**Issue by Leeyukcong** [MaaAssistantArknights/MaaAssistantArknights#5443]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽-鲍勃杂货店-卡住
![cc13498e00271db06192cf4752e19f0](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44392766/5c9ebd3f-1031-4973-9304-222875b7bebe)

### 日志文件

1

### 截图

/
![cc13498e00271db06192cf4752e19f0](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44392766/ffea5a1d-aef3-4bc7-98cd-e24c64817f95)

### 还有别的吗？

mumu模拟器

**Comment by SherkeyXD** [comment]
Duplicate of #5418

**Comment by kkss01** [comment]
![MuMu12-20230716-160319](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/109894565/184e01d4-846f-4f5c-9ba0-9c9c1b4de55d)

**Comment by KyonCN** [comment]
确实 我用的蓝叠国际版也100%卡住

**Comment by shiqiemo** [comment]
我使用的蓝叠（不是国际版）也会卡，在随便选择一个选项后（选项点两下，即进入该不期而遇的结算界面后）恢复正常，程序会继续运行

**Comment by shiqiemo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by SherkeyXD** [comment]
后续讨论转移到  #5418
