### ISSUE TITLE
加强萨米肉鸽地图中顶部干员技能状态的识别

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#5445]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

刷萨米肉鸽的过程中，地图上最顶部的一排干员的技能准备状态会被关卡详情挡住，导致MAA无法识别。即使这排干员的技能好了，MAA也不会开启这些干员的技能。

### 有什么好的想法？

增强MAA对于地图顶部这一排干员的识别能力，不至于浪费这排干员的技能。

**Comment by SherkeyXD** [comment]
这个问题不是萨米肉鸽独有的 
参看 #4962
