### ISSUE TITLE
【选关卡死】不期而遇-树篱之途

### ISSUE THREAD

**Issue by zengshuyu** [MaaAssistantArknights/MaaAssistantArknights#5446]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

当一条线路上仅有树篱之途一个前进选项时，进程会卡死
等待几分钟后会放弃本次探索，从新开始
同类型情况已经发生过多次

日志记录在17:14:21左右

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12063686/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12063687/gui.log)

### 截图

![2023-07-16_17-30-29-966_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46372839/dabdee9a-03d7-4e51-ab9d-6d1f8ab5d42a)
![2023-07-16_09-07-14-155_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46372839/609957ae-97ad-4f3a-bc1b-4aaed2648338)
![2023-07-16_02-27-22-699_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46372839/880585b8-ecbc-4a4f-af69-a78a4970af8f)

### 还有别的吗？

模拟器：夜神模拟器7.0.5.5
maa版本：alpha/v4.19.4-alpha.1.d098.g23b23ef17（最新版）

**Comment by mathlover** [comment]
resource\addition\Roguelike2\resource\template 下面根本就没有树篱之途的图片(毕竟这是萨米肉鸽专属的新节点)，所以没法识别出来前面的节点是啥...于是MAA选择跑路(还好起码不是像鲍勃一样一直卡在那

**Comment by zengshuyu** [comment]
> resource\addition\Roguelike2\resource\template 下面根本就没有树篱之途的图片(毕竟这是萨米肉鸽专属的新节点)，所以没法识别出来前面的节点是啥...于是MAA选择跑路(还好起码不是像鲍勃一样一直卡在那

（鲍勃商店卡死和哭泣狗狗卡死我现在还一直遇到）

**Comment by DavidWang19** [comment]
另外，你日志开始时就在17:14:21之后了，这我啥也看不了啊（

**Comment by mathlover** [comment]
> > resource\addition\Roguelike2\resource\template 下面根本就没有树篱之途的图片(毕竟这是萨米肉鸽专属的新节点)，所以没法识别出来前面的节点是啥...于是MAA选择跑路(还好起码不是像鲍勃一样一直卡在那
> 
> 有的，我截了，StageBoskyPassage.png
我这边的template下没有包含StageBoskyPassage.png的文件
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/11253634/a3ed0493-6fd7-4e5b-a4b2-6c293462a389)

然后我这边的Log大概是这样 https://pastebin.com/KBndUxfT
看起来最后匹配了个
Sami@Roguelike@StageEncounterOptionUnknown.png score: 0.841058 rect: [ 1113, 554, 63, 35 ] roi: [ 1100, 0, 180, 700 ]
最后保留的2023-07-16_17-43-05-843_raw.png 就是遗言
![2023-07-16_17-43-05-843_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/11253634/f36b26a9-8796-4067-926e-1d062707dec5)

**Comment by mathlover** [comment]
哦，在https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/dev/resource/template 下面确实找到了
但是似乎没有放到用户的template下，是不是增量更新漏了...
我把这个图片放到我本地看看会不会就好了

**Comment by DavidWang19** [comment]
> 哦，在https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/dev/resource/template 下面确实找到了 但是似乎没有放到用户的template下，是不是增量更新漏了... 我把这个图片放到我本地看看会不会就好了

我这边增量更新的包里是有的，不知道是怎么回事。你不如把template里的所有文件都下下来覆盖一遍。

**Comment by DavidWang19** [comment]
哦得，是我写错了，下个版本修

**Comment by DavidWang19** [comment]
已修复
