### ISSUE TITLE
强制替换adb提示解码时找到无效数据。

### ISSUE THREAD

**Issue by JaqenS** [MaaAssistantArknights/MaaAssistantArknights#5448]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

重装系统之后，MAA和雷电模拟器均重装了。
手选adb文件后，没有提示链接错误，但是停在startup阶段然后无响应。
于是想强制替换adb文件，但是会报错。

### 日志文件

MAA 遇到了问题
解码时找到无效数据。
解决方案
出现未知错误
详细信息
System.IO.InvalidDataException: 解码时找到无效数据。
   在 System.IO.Compression.InflaterZlib.Inflate(FlushCode flushCode)
   在 System.IO.Compression.InflaterZlib.ReadInflateOutput(Byte[] outputBuffer, Int32 offset, Int32 length, FlushCode flushCode, Int32& bytesRead)
   在 System.IO.Compression.InflaterZlib.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   在 System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   在 System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   在 System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   在 System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   在 System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ReplaceADB>d__454.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ABA2396** [comment]
网络连接波动导致下的adb.zip内容错误，删掉重新下一遍应该就行了
