### ISSUE TITLE
萨米肉鸽开始界面继续探索进入死循环

### ISSUE THREAD

**Issue by Gunggnir** [MaaAssistantArknights/MaaAssistantArknights#5449]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在萨米肉鸽的开始界面中，如图所示，如果是继续探索且没有放弃此次行动的按钮，会进入一个返回主菜单、重新打开肉鸽的循环

### 日志文件

发生的时间点是2023-07-16 17:31:06.264到2023-07-16 18:37:38.001
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12063797/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12063798/gui.log)

### 截图

![Screenshot_20230716-184718](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57777906/1c1c1720-f95c-4246-8877-a704ae1c2a5b)

### 还有别的吗？

使用的是夜神模拟器，系统是Windows 11 专业版，版本23H2，操作系统版本25393.1

**Comment by KUAPT** [comment]
我也发现了这个问题

**Comment by SherkeyXD** [comment]
Duplicate of #5422
