### ISSUE TITLE
希望肉鸽能添加对游戏闪退的适配

### ISSUE THREAD

**Issue by hchimyuki** [MaaAssistantArknights/MaaAssistantArknights#5452]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

游戏闪退后会一直卡住

### 有什么好的想法？

希望能添加对闪退的对策

**Comment by DavidWang19** [comment]
fixed by #5494
