### ISSUE TITLE
【不期而遇】在鸭爵不期而遇

### ISSUE THREAD

**Issue by smilingdevilkill** [MaaAssistantArknights/MaaAssistantArknights#5453]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/51026883/2140648f-f81b-4bcf-af13-13902a5c00af)
在当前不期而遇界面卡死

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12064489/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12064490/gui.log)
问题出现时间点 2023/7/16 23：53

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/51026883/2140648f-f81b-4bcf-af13-13902a5c00af)

### 还有别的吗？

mumu模拟器

**Comment by SherkeyXD** [comment]
相关讨论移至 #5418，该 issue 先关闭
