### ISSUE TITLE
萨米肉鸽三选一收藏品那个节点，会卡住不进行选择。

### ISSUE THREAD

**Issue by longteng2003** [MaaAssistantArknights/MaaAssistantArknights#5456]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

具体原因应该是选择逻辑是选最下面一个，但是最下面的需要高抗干扰指数导致没有开启。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12064625/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12064626/gui.log)

**Comment by SherkeyXD** [comment]
Duplicate of #5418
