### ISSUE TITLE
萨米肉鸽有时卡主长时间不动，能否添加一个检测到长时间没有行动自动退出当前肉鸽重开的功能？

### ISSUE THREAD

**Issue by beng003** [MaaAssistantArknights/MaaAssistantArknights#5457]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

萨米肉鸽有时卡主长时间不动，大部分情况下是三选一的时候

### 有什么好的想法？

能否添加一个检测到长时间没有行动自动退出当前肉鸽重开的功能？

### 其他内容

无

**Comment by SherkeyXD** [comment]
三选一卡住的问题已经在 #5471 中修复
