### ISSUE TITLE
萨米肉鸽选后勤分队会选择调香师做奶，然后经常出现奶不到人的情况

### ISSUE THREAD

**Issue by ft2182910** [MaaAssistantArknights/MaaAssistantArknights#5459]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽选后勤分队会选择调香师做奶，然后经常出现奶不到人的情况，因为开局多了2点希望选调香师，但使用的方法还是当单奶的范围使用

### 日志文件

无

**Comment by DavidWang19** [comment]
你说得对，可以到resource/roguelike/recruitment.json下把调香师的权重调低，或者把苏苏洛之类的权重调高，这样就不招募了

**Comment by frankchenfu** [comment]
或者把copilot.json里面群奶的逻辑改一改。萨米里面好像群奶默认位置都和单奶一样，但是实际上很多时候奶不到。可以手动把群奶这个group的部署位置改到别的地方。
举个例子，苔手默认群奶在 $(4,2)$ 朝右，奶不到近卫默认位置 $(7,3)$，就可以把群奶这个group放到 $(6,4)$ 向上保证奶得到。
