### ISSUE TITLE
希望显示关卡内计时

### ISSUE THREAD

**Issue by lzayoiss** [MaaAssistantArknights/MaaAssistantArknights#546]
简述：一个关卡内计时器
详情：
攻略新关卡时总是需要手动记忆出怪的时间轴。因为操作时游戏时间流逝速度不同，以及部分怪物会等待前一波 怪物死亡后 才出现 。手动记轴较麻烦和有偏差。希望在关卡内显示计时器。
额外需求：
计时器提示下波敌人出现时间倒计时和种类。

**Comment by zzyyyl** [comment]
其实我觉得maa计时误差会比手动记轴误差更大

**Comment by MistEO** [comment]
误差很大，比较难做到精确。短期内不会做的
