### ISSUE TITLE
有没有圆神的，嘿嘿嘿。

### ISSUE THREAD

**Issue by dforel** [MaaAssistantArknights/MaaAssistantArknights#5460]
### 说说你遇到的问题？

RT。

**Comment by ntgmc** [comment]
20201223版《原神》用户协议相关摘要
米哈游用户协议
重要须知：

·  《米哈游游戏使用许可及服务协议》由您（下文亦称为“用户”或“玩家”）与上海米哈游影铁科技有限公司共同缔结，本协议具有合同效力。

·  用户在使用米哈游提供的游戏软件(下文亦称为“米哈游游戏”）及相关服务（“游戏软件及相关服务”下文亦称为“米哈游游戏服务”）之前，米哈游特别提醒用户认真阅读本协议的全部条款，特别是其中免除或者限制米哈游责任的条款（该等条款通常含有“不负任何责任”、“无义务”、“不保证”等词汇）、限制用户权利的条款（该等条款通常含有“不得”、“不应”、“无权”等词汇）、法律适用和争议解决条款，这些条款应在中华人民共和国法律所允许的范围内最大程度地适用，该类条款通常使用颜色标记或加粗字体标注。

·  如用户不同意本协议的任何条款，则不得安装、使用米哈游游戏软件，不得享用米哈游游戏服务。用户一旦点击“接受”并安装米哈游游戏软件，或者注册、开始使用及/或继续使用米哈游游戏服务，即视为用户同意并已经接受本协议中全部条款。此后您不得以未阅读/未同意本协议内容或类似理由提出任何形式的抗辩。

十    不正当游戏行为

2    用户不得通过不正当的手段或其他不公平的手段使用米哈游游戏、米哈游游戏服务或参与米哈游游戏活动，除非中华人民共和国法律允许或米哈游事先书面许可，用户不得从事下列行为：
（6）    通过非米哈游开发、授权的第三方软件、插件、外挂、系统，使用米哈游游戏及米哈游游戏服务，或制作、发布、传播非米哈游开发、授权的第三方软件、插件、外挂、系统；

用户不得干扰米哈游正常地提供软件和服务，包括但不限于：攻击、侵入米哈游的网站服务器或使网站服务器过载；破解、修改米哈游提供的米哈游游戏软件程序；攻击、侵入米哈游的游戏服务器/游戏服务器端程序或使游戏服务器过载；制作、发布、传播、使用任何形式的妨碍游戏公平性的辅助工具或程序(包括但不限于“外挂”, **“外挂”是指独立于游戏软件之外的，能够在游戏运行的同时影响游戏操作的所有程序，包括但不限于**模拟用户操作**、改变操作环境、修改数据、伪造设备信息、伪造IP信息等一切类型）。用户不得：利用程序的漏洞和错误(Bug)破坏游戏的正常进行或传播该漏洞或错误(Bug)；不合理地干扰或阻碍他人使用米哈游所提供的软件和服务；通过异常或者非法的方式使用米哈游的软件(包括但不限于利用米哈游游戏软件登录游戏私服)；使用异常的方法登录游戏（包括但不限于使用非米哈游开发、授权或认可的第三方软件、系统登录游戏）、使用网络加速器等外挂软件或机器人程序等恶意破坏服务设施、扰乱正常服务秩序的行为；修改、翻译、注释、整理、汇编、演绎米哈游游戏软件；利用本软件或者线上游戏系统可能存在的技术缺陷或漏洞而以各种形式为自己及他人牟利（包括但不限于复制游戏虚拟物品等）或者从事其他不正当行为等。**
