### ISSUE TITLE
萨米肉鸽经常卡在第二层得偿所愿

### ISSUE THREAD

**Issue by wanqian-windrunner** [MaaAssistantArknights/MaaAssistantArknights#5461]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

昨日晚上开始挂机，期间MAA与模拟器全程保持开启，电源计划调整为息屏但不睡眠，之后多次发现肉鸽卡在第二层的得偿所愿

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12065624/asst.zip)
[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12065625/gui.zip)

如下图，问题时间在晚上11:56、凌晨1:25和上午7:14以及正在反馈时的9:49（7月16日凌晨1点多也发生过相同问题）

### 截图

<img width="595" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119412909/e01f4252-4649-4784-9487-9d27d4cda1cb">
<img width="597" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119412909/32df9cc1-9063-483c-b28e-2b8f300c8037">
<img width="614" alt="屏幕截图 2023-07-17 095409" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119412909/a0f54100-e1f1-4677-a1f4-937959fc2838">

<img width="1033" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119412909/38d94c5e-ad1d-47a9-b432-6e5de895b4d9">
<img width="627" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119412909/6c619ce3-7319-4659-a9d8-ad8321db1861">

### 还有别的吗？

刷等级策略   取长补短职业组   mumu模拟器  win11系统  电脑为暗夜精灵9

**Comment by DavidWang19** [comment]
最新版本更新解决了这个问题
