### ISSUE TITLE
萨米肉鸽所有关卡都现实关卡识别错误

### ISSUE THREAD

**Issue by YMSDHJ** [MaaAssistantArknights/MaaAssistantArknights#5463]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽所有的关卡都是关卡识别错误，没有摆放干员

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12065679/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12065680/gui.log)
7.17 10：08之后

### 截图

![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139728481/d77647f0-7ebf-4a96-ad07-8ba1ecf5f823)

**Comment by DavidWang19** [comment]
重新下载完整包即可
