### ISSUE TITLE
MAA自动战斗运行一小时后无法自动摆放干员

### ISSUE THREAD

**Issue by Astesia-poi** [MaaAssistantArknights/MaaAssistantArknights#5464]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用MAA自动战斗时，起初能正常运行，但是在运行大约1小时之后，在战斗界面就会无法摆放干员。

### 日志文件

问题出现在10:46:10之后
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12065690/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12065691/asst.log)

### 截图

![)(WNB3VVVHEG2FE4IVQ1Q9L](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/85828572/70766b1a-4141-4772-ba7a-d98fe3990988)
![XOXFB@E67JMG83`311X8~2H](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/85828572/70a768a7-976f-417a-8041-fe7057b438dd)

### 还有别的吗？

模拟器：蓝叠5.7.100.1036 N32
系统：Win11
CPU：3600X
内存：32G
模拟器分配资源：4核/4G

**Comment by SherkeyXD** [comment]
从 gui.log 来看，战斗失败出现在 `2023-07-17 06:16:15-08:28:01` 这一时间段，但是你的 asst.log 是从 `09:50:53` 开始的
这怎么分析啊（
传个 asst.log.bak 看看

**Comment by Astesia-poi** [comment]
gui.log中的记录时间是按本机时间计算还是按北京时间？我在UTC+10:00可能有时差，另外我看gui.log的修改时间是2023-07-17 09:51:01 ，应该是我开启这次自动战斗的时间，另外记录中的战斗失败也是相同的情况 
asst.bak.log 见附件
[asst.bak.log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12067443/asst.bak.log.zip)

**Comment by SherkeyXD** [comment]
> gui.log中的记录时间是按本机时间计算还是按北京时间？

应该是按照本机时间

---

日志显示 MAA 已经尝试执行了部署干员的操作，如：
> [2023-07-17 06:30:37.511][TRC][Px3330][Tx1f20] asst::BattleHelper::deploy_oper | enter
[2023-07-17 06:30:37.511][TRC][Px3330][Tx1f20] asst::BattleHelper::get_oper_rect_on_deployment | enter
[2023-07-17 06:30:37.511][TRC][Px3330][Tx1f20] asst::BattleHelper::get_oper_rect_on_deployment | leave, 0 ms
[2023-07-17 06:30:37.511][TRC][Px3330][Tx1f20] minitouch swipe (1834, 987) (1296, 370) 218 0 2 0
[2023-07-17 06:30:37.831][TRC][Px3330][Tx1f20] ready to sleep 200
[2023-07-17 06:30:38.032][TRC][Px3330][Tx1f20] end of sleep 200
[2023-07-17 06:30:38.032][TRC][Px3330][Tx1f20] minitouch swipe (1296, 370) (696, 370) 100 0 1 1
[2023-07-17 06:30:38.233][TRC][Px3330][Tx1f20] ready to sleep 150
[2023-07-17 06:30:38.383][TRC][Px3330][Tx1f20] end of sleep 150
[2023-07-17 06:30:38.383][TRC][Px3330][Tx1f20] asst::BattleHelper::deploy_oper | leave, 871 ms

但是从结果来看没能部署成功

**Comment by Astesia-poi** [comment]
> > gui.log中的记录时间是按本机时间计算还是按北京时间？
> 
> 应该是按照本机时间
> 
> 日志显示 MAA 已经尝试执行了部署干员的操作，如：
> 
> > [2023-07-17 06:30:37.511][TRC][Px3330][Tx1f20] asst::BattleHelper::deploy_oper | enter
> > [2023-07-17 06:30:37.511][TRC][Px3330][Tx1f20] asst::BattleHelper::get_oper_rect_on_deployment | enter
> > [2023-07-17 06:30:37.511][TRC][Px3330][Tx1f20] asst::BattleHelper::get_oper_rect_on_deployment | leave, 0 ms
> > [2023-07-17 06:30:37.511][TRC][Px3330][Tx1f20] minitouch swipe (1834, 987) (1296, 370) 218 0 2 0
> > [2023-07-17 06:30:37.831][TRC][Px3330][Tx1f20] ready to sleep 200
> > [2023-07-17 06:30:38.032][TRC][Px3330][Tx1f20] end of sleep 200
> > [2023-07-17 06:30:38.032][TRC][Px3330][Tx1f20] minitouch swipe (1296, 370) (696, 370) 100 0 1 1
> > [2023-07-17 06:30:38.233][TRC][Px3330][Tx1f20] ready to sleep 150
> > [2023-07-17 06:30:38.383][TRC][Px3330][Tx1f20] end of sleep 150
> > [2023-07-17 06:30:38.383][TRC][Px3330][Tx1f20] asst::BattleHelper::deploy_oper | leave, 871 ms
> 
> 但是从结果来看没能部署成功
刚才又试了下，确实有类似部署的动作，但是没摆下去，然后战斗时的帧数会越来越低，关闭MAA后就会恢复

**Comment by Fillianore** [comment]
同样的问题我也碰到过 有部署行为但未成功操作 我这边是因为机器的散热不太行 导致模拟器帧数过低无法正常执行操作 只有在性能更好的机器上流畅运行长时间 这个只能期待以后效率的优化了 #3734

**Comment by Astesia-poi** [comment]
> 同样的问题我也碰到过 有部署行为但未成功操作 我这边是因为机器的散热不太行 导致模拟器帧数过低无法正常执行操作 只有在性能更好的机器上流畅运行长时间 这个只能期待以后效率的优化了 #3734
但是CPU和内存倒是也没吃多少（如图
![DBSINX9RC7C5CS`P(Q~ NXA](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/85828572/1f7bc044-58f9-419d-b931-ecd50783bcad)
不过长时间运行后好像确实存在这个DH-Adb.exe占用资源没多少但是导致整台电脑掉帧的情况

**Comment by Astesia-poi** [comment]
> > gui.log中的记录时间是按本机时间计算还是按北京时间？
> 
> 应该是按照本机时间
> 
> 日志显示 MAA 已经尝试执行了部署干员的操作，如：
> 
> > [2023-07-17 06:30:37.511][TRC][Px3330][Tx1f20] asst::BattleHelper::deploy_oper | enter
> > [2023-07-17 06:30:37.511][TRC][Px3330][Tx1f20] asst::BattleHelper::get_oper_rect_on_deployment | enter
> > [2023-07-17 06:30:37.511][TRC][Px3330][Tx1f20] asst::BattleHelper::get_oper_rect_on_deployment | leave, 0 ms
> > [2023-07-17 06:30:37.511][TRC][Px3330][Tx1f20] minitouch swipe (1834, 987) (1296, 370) 218 0 2 0
> > [2023-07-17 06:30:37.831][TRC][Px3330][Tx1f20] ready to sleep 200
> > [2023-07-17 06:30:38.032][TRC][Px3330][Tx1f20] end of sleep 200
> > [2023-07-17 06:30:38.032][TRC][Px3330][Tx1f20] minitouch swipe (1296, 370) (696, 370) 100 0 1 1
> > [2023-07-17 06:30:38.233][TRC][Px3330][Tx1f20] ready to sleep 150
> > [2023-07-17 06:30:38.383][TRC][Px3330][Tx1f20] end of sleep 150
> > [2023-07-17 06:30:38.383][TRC][Px3330][Tx1f20] asst::BattleHelper::deploy_oper | leave, 871 ms
> 
> 但是从结果来看没能部署成功

换成MUMU12后问题消失了，一口气把坎诺特挂满了不带卡的，尝试重装蓝叠之后依旧会复现之前的问题，可能是模拟器连接出啥问题了
