### ISSUE TITLE
萨米肉鸽，添加首次进入识别。

### ISSUE THREAD

**Issue by Steven-DD** [MaaAssistantArknights/MaaAssistantArknights#5465]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

前置条件：没主动点开过萨米肉鸽，或没有手动进行过一次萨米肉鸽

出现问题：没主动点过的话，用MAA直接进行自动肉鸽，会卡在前面的选择难度页面和引导页面，导致MAA识别错误，一直增加探索次数

![Uploading Snipaste_2023-07-17_11-04-38.png…]()

### 有什么好的想法？

识别一下首次进入的问题，跳过引导页面，自动选择难度1进入游戏。

**Comment by DavidWang19** [comment]
一次性的操作一般是不考虑加入maa识别的

**Comment by Steven-DD** [comment]
好的呢
