### ISSUE TITLE
萨米肉鸽地图识别错误

### ISSUE THREAD

**Issue by wdpend** [MaaAssistantArknights/MaaAssistantArknights#5467]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

前面选人是正常的，进地图之后什么都不做，二倍速也不会启动，然后就漏怪到死开下一把
开始关卡约35s后maa内会报错 “关卡识别错误”
问题全部发生于2023.7.17更新内测版后

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12065841/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12065842/gui.log)

### 截图

![CB8$(_ X}B)}Q 4MTO W~JK](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139730544/40395e00-d5df-403b-a177-b547eff871b5)
![Screenshot_2023 07 17_11 17 07 990](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139730544/ad1f7671-f587-4c51-975a-34ff3963480d)

### 还有别的吗？

BlueStacks 5
Windows11
模拟器1920x1080 240DPI OpenGL

**Comment by SherkeyXD** [comment]
Duplicate of #5463

**Comment by wdpend** [comment]
补充：重新下载之后好了（

**Comment by SherkeyXD** [comment]
> 补充：重新下载之后好了（

重新下载指的是下最新内测版吗

**Comment by wdpend** [comment]
> > 补充：重新下载之后好了（
> 
> 重新下载指的是下最新内测版吗

删掉了整个maa的目录，然后重新下载+更新内测版

**Comment by SherkeyXD** [comment]
已经确定是增量更新引起的问题，你的做法是对的
