### ISSUE TITLE
没法识别便携式补给站

### ISSUE THREAD

**Issue by wumai1** [MaaAssistantArknights/MaaAssistantArknights#5468]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

便携式补给站会被当成干员用来阻挡敌人，不会用来给干员加技力。
然后注意到在囚徒关卡里，治疗干员的攻击范围不会覆盖地面干员。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12065945/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12065946/gui.log)

### 截图

![OU(VVVT{~1DEK$6JBEPY0G0](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139732498/dd06d9a1-f17d-4001-b155-e8025b77a855)
![V~KL{VOWYXCXS JI(B_O)RP](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139732498/f48caf95-15b1-4711-a9b5-67766629cd4e)

**Comment by DavidWang19** [comment]
囚徒的在#5466修了

**Comment by DavidWang19** [comment]
便携式补给站的话，得等肉鸽战斗重构才能解决了
