### ISSUE TITLE
掉落有时不识别

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#547]
有时候关卡结束后会不识别掉落，在结算统计前直接跳过开始下一关。每次关卡结束后软件会暂停几秒以识别掉落并上传，但是今天我观察到有时候会跳过这几秒的识别，直接开始下一关。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8749114/asst.log)

**Comment by xiaoweiXX** [comment]
版本是3.3.2，不是测试版

**Comment by MistEO** [comment]
测试版已经修过啦，过一段时间稳定了就会发布正式版本~
