### ISSUE TITLE
自动肉鸽鲍勃杂货店的识别问题

### ISSUE THREAD

**Issue by zzd2674437069** [MaaAssistantArknights/MaaAssistantArknights#5470]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在自动肉鸽进行到鲍勃杂货店项目的时候maa无法正常进行下一步动作，手动选择任意一个选项之后maa会继续进行下一步动作，疑似为该页面无法正常识别或做出判断
maa主界面日志停留在了12：30：08 ，截图时间为12：43 ，日志文件中这一段及之后一直在重复某个动作

### 日志文件

[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12066123/log.zip)

### 截图

![微信截图_20230717124348](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105783832/42e00850-50fa-481d-947e-81a49b3fbbbe)
![微信截图_20230717124355](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105783832/47de5323-af7a-49a2-a2b2-0ca181a25a8d)

### 还有别的吗？

maa版本号 v4.19.4-alpha.1.d102.g765a5eb4b
模拟器版本 BlueStacks App Player  5.9.410.1001N64

**Comment by SherkeyXD** [comment]
Duplicate of #5418
