### ISSUE TITLE
萨米肉鸽低空机动 不放令和召唤物

### ISSUE THREAD

**Issue by Yumi0606** [MaaAssistantArknights/MaaAssistantArknights#5472]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

不知是关卡未收录还是识别问题，关卡未收录的话，其他干员又能下，百嘉打法也能过

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12066536/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12066538/asst.log)

### 截图

![Snipaste_2023-07-17_14-24-29](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136778556/0f70d168-6ad6-4836-a71e-6bbb65177f07)
![Snipaste_2023-07-17_14-24-42](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136778556/d77de3ef-beae-4c00-a45c-9285dd1b3e2c)

**Comment by KawausoJyou** [comment]
萨米太落后，没见过令和的召唤物，只接受明治召唤物

**Comment by SherkeyXD** [comment]
MAA 的自动肉鸽暂时没有实现对召唤物的支持，所以目前招募策略内没有填入令

**Comment by mathlover** [comment]
神奇，我用令打这关会下召唤物，虽然下得很别扭，但是好歹能打过去...

**Comment by midsummer03** [comment]
> 



> ~MAA 的自动肉鸽暂时没有实现对召唤物的支持，所以目前招募策略内没有填入令，自然也就没有令的部署逻辑~
> 
> Edited 2023-07-17 18:14:
> 
> 我是铸币，MAA会放召唤物 但是 recruitment.json 和 copilot.json 里面确实没有令的相关逻辑

能不能把小鬼卡比令单核的操作加入到自动肉鸽里？
