### ISSUE TITLE
4.49.4版本 萨米肉鸽进入战斗卡住

### ISSUE THREAD

**Issue by kkujukk** [MaaAssistantArknights/MaaAssistantArknights#5473]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新4.49.4后，自动萨米肉鸽后经常会卡在关卡干员进入战斗界面

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12067240/debug.zip)

**Comment by SherkeyXD** [comment]
你是不是没有选择难度

**Comment by kkujukk** [comment]
在道中，已经进入游戏中1或者2层了，不是每次都卡，偶尔会卡，进入关卡选人进入关卡界面不动，卡了好几次了

**Comment by SherkeyXD** [comment]
该错误消息多次出现
> Failed to write to minitouch

换 maatouch/adbiput 试试

**Comment by kkujukk** [comment]
ok

**Comment by kkujukk** [comment]
还是会卡啊 @SherkeyXD 
![QQ图片20230717183118](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63400627/a694cf07-5bd3-4185-ac57-2a289b3623e9)

**Comment by SherkeyXD** [comment]
> 还是会卡啊

新日志来一份

**Comment by kkujukk** [comment]
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12068574/debug.zip)

**Comment by SherkeyXD** [comment]
现在版本还有这个问题吗

**Comment by kkujukk** [comment]
没有了 上次传完日志你们第二天更新后就再也没遇到了
