### ISSUE TITLE
萨米肉鸽在稳定度为6的时候不会继续，会在卡住之后直接放弃探索

### ISSUE THREAD

**Issue by interfacew** [MaaAssistantArknights/MaaAssistantArknights#5474]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选择打更多层数的时候若是以6稳定度进入第三层会卡死，在一段时间后放弃探索，似乎是因为全面勘察后图标的变换导致的无法识别   
还没有试过在中途达到6是什么情况

### 日志文件

大约14:47的时候出现的问题，于16:13手动打出并启动后复现（不知道maa能不能接着手打的打，如果不能就当没复现）
[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12067260/asst.-.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12067261/gui.log)

### 截图

这是手打出来的截图，手动点击不期而遇也不会进入
![screen](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131514634/f93ff7a7-39e8-4666-a9e1-e4f844a85ff7)
![screen2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131514634/dc2647d1-0752-428b-a2c5-0a68358a3d93)

### 还有别的吗？

maa版本4.19.4-alpha.1.d112.gc4e200a5e
蓝叠hyperv 5.12.3.1001 N64 1280x700

**Comment by interfacew** [comment]
似乎推了个更新，我去尝试再来一次

**Comment by SherkeyXD** [comment]
抗干扰指数为6时，不期而遇的图标底下会出现一层白底，干扰 MAA 识别了

**Comment by interfacew** [comment]
版本更新到d116问题仍然存在
[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12067706/asst.-.zip)
17:14左右

**Comment by SherkeyXD** [comment]
别急，在修了（
