### ISSUE TITLE
自动肉鸽功能，在抓取絮雨后，在战斗调整队伍界面会卡住

### ISSUE THREAD

**Issue by firmount** [MaaAssistantArknights/MaaAssistantArknights#5476]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如果有絮雨的话，开始战斗之前，技能调整的时候似乎会点到絮雨而进入到选人界面，然后会自动又回到调整界面，然后就不动了，会一直卡住。似乎是技能调整的点击出了问题？别的干员都是点技能图标直接调整的，调整絮雨的技能的时候似乎会点到技能图标之外的范围，导致调整出现错误。
不仅是萨米肉鸽有这个问题，水月肉鸽和傀影肉鸽也有这个问题，所以似乎是絮雨这个干员的问题？

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12067717/debug.zip)

### 截图

![VK8RO(SACQGRGXX}JLHCRLN](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113492604/109ae1f1-c119-4b43-a46b-a35c4ed9f674)

图上两个圈起来的部分时间显然是有问题的，第一次是我发现了手动开始的，第二次还是卡住我就直接结束了

它会从这个界面
![BF`O$)@JIXTI}A{UMPB}@0G](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113492604/1f578cd4-c615-4861-8062-5e5df3199f0e)
进入这个界面
![(EXXC(J6D%2(PKXVAZI YFG](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113492604/f8b4c5e1-e75f-43f6-9654-ed14f0d5a08b)

而其他干员是没有这个问题的，只有在有絮雨的情况下会出现这个问题

出现了这种情况，在maa点 开始探索 的时候会点到确认，所以指令执行了，但是没有开始，所以卡住了

### 还有别的吗？

用的MuMu12模拟器

**Comment by firmount** [comment]
虽然说是不要用qq截图，但是mumu12似乎没有截图功能。。。所以我还是用了qq截图

**Comment by mathlover** [comment]
用絮雨开局能复现
在选技能前后的log如下
https://pastebin.com/aJz22ULc
后面就是每隔0.5秒的死循环RoguelikeWaitForStartButtonClicked

**Comment by SherkeyXD** [comment]
原因是尝试选择絮雨的三技能，但是她没有

**Comment by SherkeyXD** [comment]
fixed in 6e00f57a407e4be07e3d121826d8e21057bcd855
