### ISSUE TITLE
萨米肉鸽在遇到先行一步关卡（运输干员）的时候选择运输然后卡死放弃

### ISSUE THREAD

**Issue by interfacew** [MaaAssistantArknights/MaaAssistantArknights#5478]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

遇到先行一步关卡（运输干员）的时候选择运输然后不选择干员，一段时间后放弃该次探索  

### 日志文件

[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12068071/asst.-.zip)
17:58左右

### 截图

![screen2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131514634/9f1e72de-57d9-4bef-a0ff-f0ef5bb7e4f2)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131514634/fb7c3875-764c-4e14-8183-a99698d72726)

### 还有别的吗？

maa v4.19.4-alpha.1.d116.ga810467fe
蓝叠hyperv 5.12.3.1001 N64 1280x720

**Comment by interfacew** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12068107/gui.log)

**Comment by SherkeyXD** [comment]
fixed in 737e66f012f9bb35c225e2c009a62b1c2145a2ea
