### ISSUE TITLE
保全派驻，中途选取干员的时候会一直等待

### ISSUE THREAD

**Issue by LollipopGeneral** [MaaAssistantArknights/MaaAssistantArknights#5479]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

保全派驻，中途选取干员的时候会一直等待
不知道是识别出来了，作业没有支持这些干员的选择情况；或者是其他情况
应该模拟器没有断开

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12068406/asst.log)

### 截图

![QQ图片20230717182230](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45588935/96b0b511-a94c-4176-b2ad-fc570a3a0e88)

**Comment by Rbqwow** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55343783/6802cb29-589c-46f2-8d6a-118fcfac031b)
