### ISSUE TITLE
周期性不明原因作战失败，并且卡死在联系中断页面

### ISSUE THREAD

**Issue by llkjhgllkjhg** [MaaAssistantArknights/MaaAssistantArknights#5481]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

第二次探索作战失败后卡住 在联系中断页面，不自动进行下一步，彻底卡死，很少能成功投资原石锭，在雷电模拟器上失败很少发生，mumu12就经常失败

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12069523/debug.zip)

### 还有别的吗？

MUMU12 
win11 22H2

**Comment by SherkeyXD** [comment]
现在版本还有这个问题吗？

**Comment by llkjhgllkjhg** [comment]
没有了，用蓝叠没啥毛病，刷完500锭也没试过mumu了，有机会试试，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月20日(周日) 中午1:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 周期性不明原因作战失败，并且卡死在联系中断页面 (Issue #5481)




 
现在版本还有这个问题吗？
