### ISSUE TITLE
截图失败

### ISSUE THREAD

**Issue by CoazMoxuan** [MaaAssistantArknights/MaaAssistantArknights#5484]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

软件版本v4.19.3
使用模拟器WSA 版本：2305.40000.6.0
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139780386/1f9f8fa7-ced7-409e-bd87-c266ee19bca0)
使用实体安卓设备 系统版本：MIUI41.0.2
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139780386/4ddd8b12-7b60-49b7-8d41-7e67cbd6e43e)

### 日志文件

上传失败
https://note.youdao.com/s/FWwDGEV6

### 截图

游戏画面没有变化

### 还有别的吗？

没有

**Comment by MistEO** [comment]
https://maa.plus/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.html#%E2%9A%A0%EF%B8%8F-%E9%83%A8%E5%88%86%E6%94%AF%E6%8C%81

WSA，看文档

**Comment by CoazMoxuan** [comment]
https://note.youdao.com/s/FWwDGEV6
并没有什么用

**Comment by ABA2396** [comment]
wsa 触控模式只能用adb input吧

**Comment by CoazMoxuan** [comment]
问题解决了

**Comment by glimjoe** [comment]
> 问题解决了

你好，我也遇到了相同的问题，请问是怎么解决的呢？
