### ISSUE TITLE
萨米肉鸽进去，关卡开始，然后显示识别错误，除了这个肉鸽其他的功能一点问题没有，我应该做什么来解决这个问题呢，是bug还是我设置问题啊

### ISSUE THREAD

**Issue by yunmgr** [MaaAssistantArknights/MaaAssistantArknights#5487]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽进去，关卡开始，然后显示识别错误，除了这个肉鸽其他的功能一点问题没有，我应该做什么来解决这个问题呢，是bug还是我设置问题啊

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12071332/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12071333/asst.log)
最后面时间

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/65292972/622e8327-aae6-44f3-8134-53325e0d4b12)

### 还有别的吗？

蓝叠模拟器分辨率和dpi按咱们的教程设置的检查了没有问题

**Comment by DavidWang19** [comment]
我的建议是，重下一个完整的包试试

**Comment by yunmgr** [comment]
重新下载了现在好使了感谢

**Comment by SunShineJF** [comment]
抱歉回复已关闭的issues。
我也遇到与楼主一样的问题，下载了完整包，对比了一下，发现\resource\Arknights-Tile-Pos\文件夹下，我本地缺少如图右侧的文件。希望对你们有用。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49141302/82e8a428-9aa5-428b-aa60-f10bdf6104c3)
