### ISSUE TITLE
maa无法更新，版本停滞在v4.11，

### ISSUE THREAD

**Issue by cyl233** [MaaAssistantArknights/MaaAssistantArknights#5488]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等

### 问题描述

我的maa好像很长时间都没有更新了，以前它一直能够自动更新的，现在它已经不会更新了，一直是v4.11，我看最新版的好像都到4.19了。我把所有更新的选项都点过了，不断点击检查更新没有任何反应。无论是点公测，内测还是稳定版都没有任何用。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12071786/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12071789/gui.log)

### 截图

![Y( 1WUSEKGB55%XQ7WC FG](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87838391/60959951-f331-41ab-8f1b-71eacaeca124)

**Comment by cyl233** [comment]
而且我看maa好像没有卸载程序？是免安装的吗？

**Comment by DavidWang19** [comment]
直接删掉文件夹，然后下一个最新版的完整包就行

**Comment by ABA2396** [comment]
跨的版本太多了更新包就删了，直接下新版本把config文件夹放进去就好了

**Comment by testpaper007** [comment]
直接下载，覆盖掉就行
