### ISSUE TITLE
刷肉鸽过程中掉线重连后不会继续肉鸽

### ISSUE THREAD

**Issue by e0kt** [MaaAssistantArknights/MaaAssistantArknights#5489]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷萨米肉鸽过程中掉线重连后不会重新进入肉鸽，在用户主界面和萨米肉鸽的主界面来回切换

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12074211/debug.zip)
问题出现时间点：07/17 15:25

### 还有别的吗？

模拟器：夜神
操作系统：win11

**Comment by SherkeyXD** [comment]
Duplicate of #5422
手动进入并结束此次探索即可
