### ISSUE TITLE
提几点建议

### ISSUE THREAD

**Issue by hanzif1** [MaaAssistantArknights/MaaAssistantArknights#549]
1.点击速度可以稍微加快
2.基建换班：控制中心要重复进入4次才能换
3.肉鸽：
（1）希望增加助战选项
（2）战斗逻辑优化
（3）战略前瞻投资直接退出
（4）干员技能无法选择
作者已经做的非常好了，希望继续改进！

**Comment by ABA2396** [comment]
- 速度主要是adb截图比较慢
- 战略前瞻投资直接退出可以在肉鸽设置里改，把`尽可能往后打` 改成 `刷源石锭投资,投资过后退出` 或者 `刷源石锭投资,第一层商店后直接退出`
- 干员技能选择新版本已经写了 ~等4.0~

**Comment by hanzif1** [comment]
> * 战略前瞻投资直接退出可以在肉鸽设置里改，把`尽可能往后打` 改成 `刷源石锭投资,投资过后退出` 或者 `刷源石锭投资,第一层商店后直接退出`

我这样设置后也不会投资，会在投资页面直接退出

**Comment by ABA2396** [comment]
> > * 战略前瞻投资直接退出可以在肉鸽设置里改，把`尽可能往后打` 改成 `刷源石锭投资,投资过后退出` 或者 `刷源石锭投资,第一层商店后直接退出`
> 
> 我这样设置后也不会投资，会在投资页面直接退出

你用的是测试版吗，现在的好像用不了~用之前的~

**Comment by hanzif1** [comment]
> > > * 战略前瞻投资直接退出可以在肉鸽设置里改，把`尽可能往后打` 改成 `刷源石锭投资,投资过后退出` 或者 `刷源石锭投资,第一层商店后直接退出`
> > 
> > 
> > 我这样设置后也不会投资，会在投资页面直接退出
> 
> 你用的是测试版吗，现在的好像用不了~用之前的~

我用的3.3.2
