### ISSUE TITLE
自动肉鸽, 特殊情况下的死循环

### ISSUE THREAD

**Issue by zero27613** [MaaAssistantArknights/MaaAssistantArknights#5491]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽战斗中强退游戏( 例如游戏闪退, 模拟器崩溃 ), 再次进入肉鸽, 会显示以下界面, 这时如果设置了定时任务自动肉鸽, 会进入死循环

进入肉鸽页面, 返回主页面, 进入肉鸽页面, 返回主页面, 如果往复循环.

解决方法: 加入此页面的识别, 点击继续探索即可进入失败结算页面, 再开始即可

### 日志文件

无

### 截图

![BN@AM)RKWZ4CTG9(YZ)UU1B](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59275169/bb2c68cb-03d1-4f62-9dfd-da920a6d6466)

### 还有别的吗？

mumu12
win11

**Comment by HYY1116** [comment]
同样的问题，有日志文件，7月18日8点以后[
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12075554/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12075556/asst.log)
](url)
