### ISSUE TITLE
进入肉鸽界面时若前次失败未结算,则会循环主页面-肉鸽

### ISSUE THREAD

**Issue by whyXVI** [MaaAssistantArknights/MaaAssistantArknights#5495]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题
失败未结算就退出的过程未知

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12076020/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12076021/gui.log)

### 还有别的吗？

使用默认配置+自定义干员山,ADB Input等多种触控模式下均会出现该问题
夜神模拟器7.0.5.8  分辨率1920x1080 DPI320 OpenGL+ 性能设置为高,60fps  系统android7 32bit

**Comment by DavidWang19** [comment]
fixed by #5494
