### ISSUE TITLE
MAA异常闪退多次

### ISSUE THREAD

**Issue by Guducat** [MaaAssistantArknights/MaaAssistantArknights#5496]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

多次异常闪退

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12077240/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12077243/gui.log)

### 还有别的吗？

运行于Windows服务器，32GB运存，E5-2666 V3,GPU为P106，理论性能足够

**Comment by Guducat** [comment]
还有一个问题是MAA会时不时和Alas的ADB对冲，然后MAA对冲不过Alas直接任务失败

**Comment by ABA2396** [comment]
adb启动会关闭其他版本的adb，所以要用同一个
