### ISSUE TITLE
经常出现捕捉模拟器失败的情况

### ISSUE THREAD

**Issue by Cloaco** [MaaAssistantArknights/MaaAssistantArknights#55]
第一个号打的时候没啥问题，换下个号打的时候运行脚本就出现捕捉失败的情况，但模拟器和脚本都未曾重开过

**Comment by Cloaco** [comment]
挺离谱的，三个号试来试去，就一个b服号用不了，其他一个b服一个官服倒是能用

**Comment by MistEO** [comment]
帮忙发下日志吧，目录下的`asst.log`文件

**Comment by Cloaco** [comment]
[asst.log](https://github.com/MistEO/MeoAssistance-Arknights/files/7664973/asst.log)

**Comment by MistEO** [comment]
使用的不是同一个模拟器么？还是说使用了模拟器的多开功能？

**Comment by Cloaco** [comment]
使用了多开功能

**Comment by MistEO** [comment]
软件本身是不支持多开的，短期内也没有支持多开功能的计划。

可以参考[使用自定义连接](https://github.com/MistEO/MeoAssistance-Arknights#%E5%85%B6%E4%BB%96%E6%A8%A1%E6%8B%9F%E5%99%A8%E5%AE%89%E5%8D%93%E6%89%8B%E6%9C%BA%E5%B9%B3%E6%9D%BF%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AE%BE%E5%A4%87)的方式来尝试连接第三个号。
