### ISSUE TITLE
萨米肉鸽，采用刷源石锭策略时，在第一层遇到兴致盎然节点，改为不投注

### ISSUE THREAD

**Issue by CharlesChou73** [MaaAssistantArknights/MaaAssistantArknights#5501]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

看之前的讨论串，目前的策略貌似是所有选项事件都选第一个？

兴致盎然这里如果把钱都败完了，还是有点影响效率的。

**Comment by DavidWang19** [comment]
其实本身这几个节点就是选直接退出的，原来有bug所以没退出，最新版应该是好了
