### ISSUE TITLE
萨米肉鸽出错，将罗比菈塔的全自动造型仪视作有阻挡近战单位部署

### ISSUE THREAD

**Issue by MoXiaoX** [MaaAssistantArknights/MaaAssistantArknights#5502]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动萨米肉鸽会在可以招募五星辅助的情况下，招募四星的罗比菈塔并在战斗中将其召唤物视作近战单位部署在需要阻挡位的地面。我在检查log文件后，发现可以看到在识别了可招募干员列表后，选择并点击了罗比菈塔。在后续战斗过程中频繁输出’best oper is 全自动造型仪‘并不断将召唤物部署在远离其他干员的地块，不能起到提供护盾和防御力的效果，完全不能理解。所以我后来介入了关卡，可能会生成一些奇怪的识别结果。
版本号：v4.19.4-alpha.1.d133.ge745f03ad

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12079241/asst.log)

**Comment by huijihuiyang** [comment]
我观察到的maa还会将罗比菈塔的装置当作高台干员使用

**Comment by SherkeyXD** [comment]
fixed in #5621
