### ISSUE TITLE
希望MAA出一个一键刷复刻活动功能

### ISSUE THREAD

**Issue by EricWangxy** [MaaAssistantArknights/MaaAssistantArknights#5503]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

通过识别复刻活动任务列表里面的通关 ”XY-Z"或者“XY-EX-Z"然后代理对应的关卡 （e.g. 这次绿野幻梦复刻 在数据采集里面识别到”通关DV-8或者 DV-EX-8 然后再代理对应的关卡）

**Comment by Deo-777** [comment]
附议，还可以加上按照任务列表选择未刷取任务，以及添加只刷普通1~8和ex-8的功能！

**Comment by 1522027679** [comment]
附议，希望添加刷普通1~8和ex-8的功能

**Comment by WSMTBG** [comment]
+1
