### ISSUE TITLE
肉鸽在下干员时会在待部署状态长时间停留（已解决）

### ISSUE THREAD

**Issue by 2586248878** [MaaAssistantArknights/MaaAssistantArknights#5507]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽模式下干员时会停留在待部署状态（也就是十分之一倍速慢放的状态）长时间停留，并且干员未下成功导致关卡作战失败。在20点14分更新模拟器，截止至20点24分运行了两把肉鸽均出现如上情况。日常模式一切正常。
请问一下能不能对此作出相应的优化，或者是我的游戏设置出现问题，需要修改设置或者是换一个模拟器，谢谢。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12080357/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12080358/asst.log)

### 截图

![ZUGAC~R%I8JEG_0~1CRD85B](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/82018782/95fd31ff-a6e8-4e82-9427-5bee955cd44a)

### 还有别的吗？

模拟器夜神模拟器最新版，maa版本v4.19.4-alpha.1.d133.ge745f03ad。
之前看问题有人说过如下情况得到的建议是触控模式改成minitouch，可我现在就用的是该模式。

**Comment by SherkeyXD** [comment]
应该不是夜神的问题，我用的蓝叠也碰到了

**Comment by testpaper007** [comment]
以前水月肉鸽页出现过这种情况，应该是帧率太低了
