### ISSUE TITLE
自动战斗选择“克洛丝”时会选择“寒芒克洛丝”

### ISSUE THREAD

**Issue by guojunyu196** [MaaAssistantArknights/MaaAssistantArknights#551]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8749751/asst.log)

**Comment by xc01** [comment]
或许可以试试在 `resource/task.json` 文件中` "Roguelike1ChooseOper"` 字段的`ocrReplace`字段中添加
`[
                "寒芒.+",
                "养乐多"
            ],` 养乐多也可以改成别的总之不是干员名字就行。但是希望溢出的时候是不会选低星的，脚本逻辑问题

**Comment by guojunyu196** [comment]
我指的是这个自动战斗orz
![屏幕截图 2022-05-23 224324](https://user-images.githubusercontent.com/76220347/169845159-cb337aa2-d49a-4ee8-b082-c9377a75b8f0.png)

**Comment by MistEO** [comment]
beta.5 fixed
