### ISSUE TITLE
台服傀影肉鸽无法部署干员问题

### ISSUE THREAD

**Issue by ms200tswd** [MaaAssistantArknights/MaaAssistantArknights#5518]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

台服用MAA挂机傀影肉鸽，6星开局干员永远无法部署（已实验令和煌），会暂停反复查看干员详情，费用够但是不部署，其他3星4星干员没有问题，MAA设置里没有开启暂停部署功能

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12083932/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12083933/gui.log)
大概在2023/07/18 13:00 ~ 13:40之间，但是一直都有这个问题

### 截图

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43395375/47534da4-94b1-49e3-b579-cd5663f0fd65)

### 还有别的吗？

模拟器都实验过：MUMU12 雷电 蓝叠 夜神，都会出现同样问题
操作系统：WIN10

**Comment by Arcelibs** [comment]
也遇到了同樣問題

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49543451/e617f863-2560-4d56-976a-687b565bb044

**Comment by SherkeyXD** [comment]
OCR 把煌的名字识别错了

**Comment by ms200tswd** [comment]
> 也遇到了同樣問題
> 
> 使用環境 : Win11 Pro 模擬器 : 夜神Android 9 x64 [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12093204/asst.log) [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12093206/gui.log)
> 
>  default.mp4

哈哈哈，我刚看到你问开局的帖子，还想问问你有没有同样的问题

**Comment by ms200tswd** [comment]
感谢大大们的修补，最新版本(4.20 BETA2)，实验已经可以正常使用令和煌开局部署，再次感谢
