### ISSUE TITLE
基建换班不会换指挥中心

### ISSUE THREAD

**Issue by zhazha405** [MaaAssistantArknights/MaaAssistantArknights#552]
模拟器：BlueStacks 5 Nougat 64 位 (Hyper-V)
MAA：V3.9.0-beta.3
情况如题
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8750195/asst.log)
![H~GPS2Y$O(YO6WMJ OKLYA](https://user-images.githubusercontent.com/13600095/169713987-372e9ecc-393d-44f0-8f75-31325075398f.png)

**Comment by MistEO** [comment]
没识别到控制中心，不知道为啥，下次在遇到这种情况帮忙截一张这个界面的原图看看（用模拟器自带的截图工具）

点右上角蓝色的通知，基建缩到最小，这个时候的

![Screenshot_2022 06 03_03 06 20 982](https://user-images.githubusercontent.com/18511905/171717771-1252b57e-2c55-4c6a-8e71-fae651aff026.png)

**Comment by zhazha405** [comment]
> 没识别到控制中心，不知道为啥，下次在遇到这种情况帮忙截一张这个界面的原图看看（用模拟器自带的截图工具）
> 
> 点右上角蓝色的通知，基建缩到最小，这个时候的
> 
> ![Screenshot_2022 06 03_03 06 20 982](https://user-images.githubusercontent.com/18511905/171717771-1252b57e-2c55-4c6a-8e71-fae651aff026.png)

好的

**Comment by zhazha405** [comment]
![Screenshot_2022 06 05_04 59 47 377](https://user-images.githubusercontent.com/13600095/172025290-8dc2c057-19cb-44a9-a537-90cdf570e57a.png)

**Comment by MistEO** [comment]
> ![Screenshot_2022 06 05_04 59 47 377](https://user-images.githubusercontent.com/13600095/172025290-8dc2c057-19cb-44a9-a537-90cdf570e57a.png)

不是暗下来的，就是你再点一下随便一个空白位置

**Comment by zhazha405** [comment]
> > ![Screenshot_2022 06 05_04 59 47 377](https://user-images.githubusercontent.com/13600095/172025290-8dc2c057-19cb-44a9-a537-90cdf570e57a.png)
> 
> 不是暗下来的，就是你再点一下随便一个空白位置
![Screenshot_2022 06 05_05 05 52 708](https://user-images.githubusercontent.com/13600095/172025483-fb99d83f-450b-41ed-945e-50c93bead09b.png)

**Comment by MistEO** [comment]
ok, 感谢

等有空我来看看咋回事

**Comment by zhazha405** [comment]
> ok, 感谢
> 
> 等有空我来看看咋回事

谢谢，辛苦了

**Comment by zzyyyl** [comment]
> ok, 感谢
> 
> 等有空我来看看咋回事

有空看看.jpg
