### ISSUE TITLE
萨米肉鸽-策略-纵向通路选取

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#5520]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

积极选择纵向通路（抗干扰点数>1时）能提高分数收益
理由如下：
1. 打不过的关卡自然会打不过，然而若能在进入下一层前打更多的关卡，则可以提高配队稳定程度；
2. 关卡是开始战斗之后识别的，自然不用担心过低抗干扰导致“瞎了”的；
3. 经历的步数越多、行为越多，最终得分也会越高，后勤点数增加更快。

### 有什么好的想法？

积极选择纵向通路，尤其是纵向通路为不期而遇的时候，应该能增大自动战斗存活和推进的成功率
实现策略应该不会太复杂，将当前关卡的上下部分识别，将纵向选择纳入判断
有可能需要（或可用于）避免紧急作战

**Comment by Lancarus** [comment]
fixed in #6140
