### ISSUE TITLE
MAA v4.20-beta1 （mac os）更新后，自动肉鸽里还是没有萨米肉鸽

### ISSUE THREAD

**Issue by TPL1992** [MaaAssistantArknights/MaaAssistantArknights#5521]
### 说说你遇到的问题？

更新成功，已经是最新版本，更新说明说了适配萨米肉鸽，不过更新成功之后还是只有傀影和水月。

**Comment by TPL1992** [comment]
<img width="260" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/127443401/c177d298-91d2-445c-b34c-0fe272f0667a">
<img width="728" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/127443401/99400008-95e5-4937-85f8-184d8098f98e">

**Comment by MistEO** [comment]
mac 的开发者最近太忙了，没人维护，还没适配，等个佬带带

**Comment by TPL1992** [comment]
好的，大佬辛苦，加油，期待~

**Comment by MistEO** [comment]
beta.3 fixed
