### ISSUE TITLE
定时功能设置无法更新

### ISSUE THREAD

**Issue by MuLInGRui** [MaaAssistantArknights/MaaAssistantArknights#5524]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

界面设置相关
”定时执行“的时间设置无法更新，关闭后下次启动都会是更新前的设置内容
尝试过以下方法进行时间设置的更新：
开始行动，即完成一整轮任务（选择全选并完整完成任务）
直接关闭
完成部分任务
完成空任务（即全部不选择）
不勾选自动唤醒，完成后续部分任务，即任务失败快速结束

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12089858/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12089862/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12089863/gui.log)

### 还有别的吗？

发现的时间大概发生在游戏的萨米肉鸽更新之后

**Comment by MuLInGRui** [comment]
我注意到拉取请求中有给强制启动选项的保存BUG修复，不知道是否与该BUG相关

**Comment by ABA2396** [comment]
只有小时不能改）之前改漏了

**Comment by MuLInGRui** [comment]
> 只有小时不能改）之前改漏了

阿哲，虽然但是我的意思是定时执行设置这块全都不能更新，而不是只有小时，更新之后我发现强制启动的选项和小时可以保存，但是分钟和时间设置的对勾选项依旧不能保存

**Comment by MuLInGRui** [comment]
昨天不确定是否是全部修复所以没有回复，今天发现小时可以修改才确定没有完全修复

**Comment by ABA2396** [comment]
但分钟之前就是可以保存的啊

**Comment by MuLInGRui** [comment]
我记得最开始是小时分钟和选项都可以修改保存的。强制启动和配置功能增加以后，这次是第一次修改，才发现小时分钟选项都无法修改了，其他时候因为没有修改所以不是很清楚

**Comment by ABA2396** [comment]
好像逻辑确实有点问题，我再看看

**Comment by MuLInGRui** [comment]
这次更新以后，定时功能都可以正常使用了，包括小时、分钟、选择和强制、配置
