### ISSUE TITLE
萨米肉鸽 无法正常使用

### ISSUE THREAD

**Issue by Jack4936** [MaaAssistantArknights/MaaAssistantArknights#5525]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用萨米肉鸽进行源石锭刷取 分别在2023-07-18使用雷电模拟器和2023-07-19凌晨开始使用MuMu模拟器12,都同样出现正常刷取几盘后,一直进入重复退出进入操作,导致检测运作时正常,无人值守时无法刷取

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12089922/debug.zip)

### 截图

![MAA图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36751516/3ceafe43-3bdb-493c-af2e-b4548be05086)

### 还有别的吗？

使用的模拟器:2023-07-18 雷电模拟器9 使用3-4小时 2023-07-19 MuMu12模拟器使用8小时
操作系统:Windows10
配置信息:基础信息
UUID :  212ca16c-97af-4c0b-807f-3b8fa2a897ec
模拟器版本 :  3.5.0.1790
模拟器磁盘（可用/总）空间 :  117.4GB/126GB
日志路径 :  D:\Program Files\Netease\MuMuPlayer-12.0\vms\MuMuPlayer-12.0-0\logs\

运行环境
VT :  开启
Hyper-V :  关闭
网络环境检测 :  正常
以管理员运行方式 :  否
DirectX 11是否安装 :  是
防火墙 :  关闭

电脑配置
主板型号 :  Manufacturer: Clevo  Product: W65KJ1_KK1
CPU :  Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz
系统版本 :  Windows 10 64-bit Kernel 10.0.19045
显卡驱动 :  正常
显卡驱动型号 :  512.15 (20220317)
所有显卡 :  NVIDIA GeForce GTX 1050 Ti  |  Intel(R) UHD Graphics 630  |  Microsoft Basic Render Driver
当前使用显卡 :  NVIDIA GeForce GTX 1050 Ti
安装磁盘(可用/总)空间 :  55.3GB/731.1GB
可用内存/总内存 :  8.6GB/15.9GB

模拟器设置
Root :  关闭
显卡渲染模式 :  Vulkan 模式（独家）
性能设置 :  3核/4GB
手机型号 :  Xiaomi 12S
分辨率 :  1600 * 900
高帧率 :  开启

连接设备
音频输入 :  已连接
音频输出 :  已连接

网络信息
MuMu DNS :  192.168.1.1
电脑DNS :  192.168.1.1
Rom MAC地址 :  08:ae:df:2a:80:00

ADB调试端口 :  16384
MuMu出口IP地址 :  *
电脑出口IP地址 :  *

其它信息
其它版本信息 :  vm: 120.1.19.006 hyperv: 6.3.13.0 renderer: 0.0.107.0
Vendor :  NetEase
OpenGL Renderer :  MuMu GL (Vulkan 1.3.194 NVIDIA GeForce GTX 1050 Ti 512.15 _A_)
OpenGL Version :  OpenGL ES 3.2
运行时间 :  0 : 0 : 11

**Comment by 2586248878** [comment]
同样的问题，夜神模拟器。一开始是帧率过低导致一盘都刷不了，现在60帧之后刷了一盘就出现如上情况，

**Comment by Astesia-poi** [comment]
感觉和我这也是类似的问题 #5464

**Comment by 2586248878** [comment]
之前失败了两次，目前第二次还算正常，不知道什么情况。

**Comment by SherkeyXD** [comment]
这个问题确实会由过低的帧率触发

**Comment by 2586248878** [comment]
昨晚我的60帧出现以上情况，调成120帧maa无响应，调回60帧一切正常了，目前正常运行了4次探索。不能稳定复现的问题就很麻烦。

**Comment by Jack4936** [comment]
看了上面, 好像是打开屏幕正常, 然后关闭屏幕就会导致帧率低 从而无法战斗, 从前的刷取水月源石锭也是这么操作的 现在就行不通了.设置60帧或者120帧都是这样
