### ISSUE TITLE
mac更新之后还是没有萨米肉鸽

### ISSUE THREAD

**Issue by uesakayou** [MaaAssistantArknights/MaaAssistantArknights#5526]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刚刚更新了之后发现还是没有萨米可选

### 日志文件

无

### 截图

<img width="284" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/86504999/efb49ec8-75f4-4faa-8dee-4b59cc3153bf">
<img width="897" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/86504999/5e31d837-175f-4c20-9b26-eeca87bca8de">

### 还有别的吗？

mac os

**Comment by MistEO** [comment]
mac 的开发者最近太忙了，没人维护，还没适配，等个佬带带

**Comment by uesakayou** [comment]
这样啊，了解了，那我先用windows挂吧

**Comment by Black1312** [comment]
v4.20.0-beta.2
新增
macOS GUI 添加萨米肉鸽选项 
请更新至beta2版本后检查选项
