### ISSUE TITLE
网易UU加速器一启动MAA就断链

### ISSUE THREAD

**Issue by DoctorKoKoDaYo** [MaaAssistantArknights/MaaAssistantArknights#5528]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

之前启动加速MAA才断开链接，最近一启动就断开链接，UU设置如下，当前UU版本4.58，当前MAA版本4.20.0-beta1

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12090682/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12090683/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/67793712/f7ebc44d-0a14-47c0-a5b0-9b85c5dba480)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/67793712/6846d508-15d9-4613-b713-973c9f82e734)

### 还有别的吗？

蓝叠5国际N64

**Comment by SherkeyXD** [comment]
出于某种原因，使用加速器会影响对 127.0.0.1 的连接，因此 adb 连接会断开
对此我们给出的建议是不要在使用 MAA 的同时使用加速器，如果有加速需求尝试在模拟器内启动加速器

**Comment by ABA2396** [comment]
也可以在开了加速器之后再开maa)
