### ISSUE TITLE
linux使用maa错误

### ISSUE THREAD

**Issue by nullnuo** [MaaAssistantArknights/MaaAssistantArknights#5529]
### 说说你遇到的问题？

deepin20.9，运行sample.py出错
![IMG_20230719_120154](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139941495/d473f48c-e77d-41a2-88d8-860518eabe1f)
显示没有libmaacore.co但实际上有

**Comment by horror-proton** [comment]
在 `asst.py` 57 行 print 一下 `Asst.__libpat` 看看, 正常情况下这应该是一个完整的路径
