### ISSUE TITLE
水月肉鸽会卡在检视藏品

### ISSUE THREAD

**Issue by Deo-777** [MaaAssistantArknights/MaaAssistantArknights#5530]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

水月肉鸽会卡在选关时查看收藏品的界面，并反复“先点击某个位置的藏品，然后退出该藏品（同时仍在检视所有藏品）”这一循环。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12091138/asst.log)
gui没内容，我看过了。
大致时间点是14：40前，反复点击藏品。

**Comment by Lancarus** [comment]
#5892
