### ISSUE TITLE
便携式补给站部署方向没有干员

### ISSUE THREAD

**Issue by KawausoJyou** [MaaAssistantArknights/MaaAssistantArknights#5531]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

便携式补给站部署方向没有干员

### 日志文件

[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12091562/log.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92703641/058f582d-f10c-4a0d-afd1-56e90895464a)

**Comment by MoXiaoX** [comment]
我这边遇到了招募罗比菈塔并且乱丢全自动造型仪的bug，应该是没有正确设定这些辅助单位的权重，把它们当作普通的有阻挡近战单位扔地上了
