### ISSUE TITLE
增加刷取源石锭的效率的几个建议

### ISSUE THREAD

**Issue by kepler-wang** [MaaAssistantArknights/MaaAssistantArknights#5533]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

遇到一些抉择会导致刷取源石锭效率不高

### 有什么好的想法？

1. 战斗掉落只选择源石锭
2. 多走不期而遇，且尽量选择直接离开的选项（比如遇到巫师竞技直接离开）
3. 商店里只存钱，且投资完后不选择离开而是退出到主界面放弃（可以跳过二层的开始动画）

### 其他内容

无

**Comment by SherkeyXD** [comment]
> 战斗掉落只选择源石锭

不差那几秒，但可以获取更多点数
> 多走不期而遇，且尽量选择直接离开的选项（比如遇到巫师竞技直接离开）

多走不期而遇已在 #5454 中提出，此外目前 MAA 除了第一层的打狗关卡都是直接离开的
> 商店里只存钱，且投资完后不选择离开而是退出到主界面放弃（可以跳过二层的开始动画）

见 #1555
