### ISSUE TITLE
肉鸽关闭游戏后无法重启

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaAssistantArknights#5535]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

就莫名其妙关了游戏，然后就无法自动重启，然后就卡住了

[2023-07-18 23:58:27 往后 过了12点左右就游戏没了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12092181/asst.log)

**Comment by SherkeyXD** [comment]
MAA 不会关游戏，这种情况大概率是方舟闪退了

**Comment by SherkeyXD** [comment]
Move to #5535
