### ISSUE TITLE
萨米肉鸽，狡兽九窟关卡，会卡在慢动作界面导致失败

### ISSUE THREAD

**Issue by CharlesChou73** [MaaAssistantArknights/MaaAssistantArknights#5536]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

RT，之前挂机没看，翻日志感觉这关遇到就失败，以为是难度太高了

这次看到是卡在讯使的慢动作界面，导致无法下人和放技能

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12092167/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12092175/gui.log)

日志时间如图
![Snipaste_2023-07-19_15-16-09](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16950543/1ec09b61-8c63-4fd4-b1d2-15102f06990a)

之前得日志太多就删了，抱歉不能提供更多线索

### 截图

![Screenshot_2023 07 19_15 09 31 324](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16950543/bdf42246-9983-4db0-b4ca-eaf192ebb676)

**Comment by SherkeyXD** [comment]
目前已知低帧数会导致还问题的发生，检查一下你的帧数是否正常

**Comment by cenfusheng** [comment]
请检查模拟器是否为60帧，是否掉帧严重，可考虑将maa文件夹resource文件夹tasks.json中的以下四个延迟数值改为以下值临时解决（之后的MAA每次更新都需要重新改）。

 "BattleUseOper": {
        "algorithm": "JustReturn",
        "preDelay": 250,
        "postDelay": 500,
        "Doc": "pre 是从点击干员，到干员信息弹出来等待的时间；post 是干员上场，到设置朝向之间等待的时间"
    },
    "BattleSwipeOper": {
        "algorithm": "JustReturn",
        "preDelay": 600,
        "postDelay": 200,
