### ISSUE TITLE
適用MAA的傀影肉鴿幹員推薦?

### ISSUE THREAD

**Issue by Arcelibs** [MaaAssistantArknights/MaaAssistantArknights#5537]
### 说说你遇到的问题？

座標台版，感覺現在常用的幾組傀影肉鴿幹員打個兩三關就過不去了

來問問有沒有MAA大佬推薦初始選啥分隊+指定哪些幹員配合MAA可以刷比較多層甚至全通的

大概以鴻雪版本以前的推薦我幾組試試看

**Comment by ABA2396** [comment]
山 煌 羽毛笔 默认或者近卫开局就行

**Comment by Arcelibs** [comment]
> 山 煌 羽毛笔 默认或者近卫开局就行

沒有山的話有啥其他選擇

**Comment by oneNess2022** [comment]
> 



> > 山 煌 羽毛笔 默认或者近卫开局就行
> 
> 沒有山的話有啥其他選擇

百炼嘉维尔之类的能挡多的近卫就行，第一层需要一定的阻挡数量。

**Comment by Black1312** [comment]
棘刺近卫队

**Comment by CharlesChou73** [comment]
近卫队棘刺开局，一般可以保送到第四层

**Comment by Lancarus** [comment]
棘刺开局，已经专门优化过了
