### ISSUE TITLE
希望可以添加一个肉鸽凹开局的功能

### ISSUE THREAD

**Issue by Extreme1206** [MaaAssistantArknights/MaaAssistantArknights#5539]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

希望可以增加凹精二开局功能，梦先做上了

**Comment by SherkeyXD** [comment]
很有意思的想法

**Comment by SherkeyXD** [comment]
Duplicate of #4791
