### ISSUE TITLE
肉鸽功能建议

### ISSUE THREAD

**Issue by xc01** [MaaAssistantArknights/MaaAssistantArknights#554]
因为看到issue区很多人说要支持更加“聪明”的肉鸽打法，是不是可以推出一个接口客制化每一关的打法。这样工程量或许会更小
等研究下代码后试试加功能（其实肉鸽次数选择的支持也挺需要的

**Comment by MistEO** [comment]
其实已经在写了 [feat/roguelike_copilot](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/feat/roguelike_copilot) ~~指两个月没有更新了~~
