### ISSUE TITLE
macOS环境v4.20.0-beta.2萨米肉鸽点击无反应

### ISSUE THREAD

**Issue by CottnCor** [MaaAssistantArknights/MaaAssistantArknights#5547]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，macOS环境下使用刚刚更新的v4.20.0-beta.2版本，选择萨米肉鸽后点击开始，软件立刻退出运行状态，变为待机状态，无任何有效行为，文字表达可能不清晰，稍微录了个视频附带在下方。

maa日志已经上传，可直接查看最新的几条2023-07-20 00:58分的相关日志记录。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12098326/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12098328/asst.bak.log)

### 截图

<img width="277" alt="截屏2023-07-20 00 49 36" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/17594299/6b59f225-7b34-4835-9369-e71dbf1ffa3a">
<img width="257" alt="截屏2023-07-20 01 00 01" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/17594299/6a09a618-5b96-46b8-acf0-f970fd22d628">

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/17594299/8067f7b3-6367-4386-b7a8-965307d16a54

### 还有别的吗？

补充：游戏App环境使用的是maa文档中推荐的`fork 版本的 PlayCover`

_No response_

**Comment by YuhangTom** [comment]
没反应+1

**Comment by BruceWu03** [comment]
同样无反应，开始按钮闪了一下就变回去了
水月和魁影都能正常开局。开局：从主界面打开终端-选择肉鸽-选择分队-选择干员-进入第一关。
猜测：有些数据没更新？
```
[2023-07-20 00:58:46.777][ERR][Pxe712][Txe515] Unknown roguelike theme Expeditioner
[2023-07-20 00:58:46.777][TRC][Pxe712][Txe515] asst::RoguelikeTask::set_params | leave, 0 ms
[2023-07-20 00:58:46.777][ERR][Pxe712][Txe515] append_task | invalid params: {"investment_enabled":true,"enable":true,"roles":"取长补短","theme":"Expeditioner","squad":"指挥分队","use_support":false,"use_nonfriend_support":false,"starts_count":9999999,"refresh_trader_with_dice":false,"mode":1,"investments_count":999,"core_char":"","stop_when_investment_full":false}
```

**Comment by BruceWu03** [comment]
猜测：肉鸽
[‎src/MaaCore/Task/Interface/RoguelikeTask.cpp‎](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/ef909a0e2f653d8f4616bad583226b4013fd104c/src/MaaCore/Task/Interface/RoguelikeTask.cpp#L52)
```c++
if (theme != RoguelikePhantomThemeName && theme != RoguelikeMizukiThemeName && theme != RoguelikeSamiThemeName) {
Log.error("Unknown roguelike theme", theme);
return false;
```
[src/MaaCore/Common/AsstTypes.h‎](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/ef909a0e2f653d8f4616bad583226b4013fd104c/src/MaaCore/Common/AsstTypes.h#L419)
```c++
 inline static constexpr std::string_view RoguelikeSamiThemeName = "Sami";
```
MeoAsstMac/Configuration Views/RoguelikeSettingsView.swift
```
        case .Expeditioner:
             return NSLocalizedString("萨米", comment: "")
         }
```
将 .Expeditioner改为 .Sami

**Comment by MistEO** [comment]
beta.3 fixed
