### ISSUE TITLE
maa操作有延迟和强制替换ADB失败

### ISSUE THREAD

**Issue by huijihuiyang** [MaaAssistantArknights/MaaAssistantArknights#5555]
### 说说你遇到的问题？

因为我在使用maa时maa的操作会有5-10秒的延迟,尝试强制替换adb但失败,重启过电脑还是不行,三种触控模式都无法替换
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139624880/8914450e-972a-4fbb-a660-c9017081c163)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139624880/2afb8f51-3416-458a-9d7a-8f962ae8cc3b)
在这里问一下有什么解决办法

**Comment by SherkeyXD** [comment]
日志，请

**Comment by huijihuiyang** [comment]
> 日志，请

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12105358/asst.-.log)
[gui - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12105360/gui.-.log)

**Comment by SherkeyXD** [comment]
试试把 adb 的路径换成绝对路径

**Comment by cenfusheng** [comment]
https://shimo.im/docs/473Qyd7B7Nh1w23w
