### ISSUE TITLE
希望能给定时执行指定不同的配置

### ISSUE THREAD

**Issue by Outsider225** [MaaAssistantArknights/MaaAssistantArknights#5557]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

定时执行只能执行首页的配置。比方说我定时执行只想换班和领奖励，则我手动修改首页刷本之后必须要把首页配置还原回去，否则定时执行就变成刷本了

### 有什么好的想法？

希望能给每一条定时执行都指定一个配置，这样就可以在不同的时间做不同的事，而不是所有的定时都是同一流程

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/9505b883-bef6-4acd-b96f-e65b1df4f5aa)

**Comment by Outsider225** [comment]
@ABA2396 明白了，我现在用的是稳定版，等这个功能加入
