### ISSUE TITLE
小时、分和秒参数描述无法表示的 DateTime。

### ISSUE THREAD

**Issue by KriaQueen** [MaaAssistantArknights/MaaAssistantArknights#5559]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 遇到了问题
小时、分和秒参数描述无法表示的 DateTime。
解决方案
出现未知错误
详细信息
System.ArgumentOutOfRangeException: 小时、分和秒参数描述无法表示的 DateTime。
   在 System.DateTime.TimeToTicks(Int32 hour, Int32 minute, Int32 second)
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<Timer1_Elapsed>d__37.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12102172/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12102173/asst.log)

**Comment by ABA2396** [comment]
定时任务写的几点？

**Comment by cenfusheng** [comment]
定时任务不要写24:00哦，只有00:00
