### ISSUE TITLE
萨米肉鸽无法正确部署安塞尔

### ISSUE THREAD

**Issue by clark1091** [MaaAssistantArknights/MaaAssistantArknights#5562]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

现内测版本运行萨米肉鸽时MAA无法准确识别高台站位，拉着泳装安塞尔满屏幕乱飞，也不排除将安塞尔识别成了地面单位试图往地上放，因为同一张图里在上个版本运行时本应堵门的百嘉不明原因向前放了一格，直接空门一条路，但梓兰和史都华德能放到正确的高台上

### 日志文件

截取时问题正在发生，应该不会超过最后三分钟，另外日志截取后在其他节点安塞尔依然未能正常部署
[MAA-v4.12.3-win-x64.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12102944/MAA-v4.12.3-win-x64.zip)

**Comment by cenfusheng** [comment]
检查模拟器是否为60帧，如果是MUMU12请关闭动态帧率。
