### ISSUE TITLE
自动保全失败

### ISSUE THREAD

**Issue by Malgranda** [MaaAssistantArknights/MaaAssistantArknights#5563]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动保全报错 公测 稳定 内测三个版本都试过了 在[开始行动]的界面使用功能
然后就卡住
开始:SSSCopilot
过一分钟半分钟 
就是 
任务出错: SSSCopilot

强制替换ADB就本地报错
选择ADB Input（不推荐）
也没有用 
甚至我还重下的MAA
换了四个模拟器 雷神 夜神 蓝叠 MUMU12
都是这样 可能是我电脑的问题？

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12103031/debug.zip)
在7.20号 下午三点 拉到最下面就是了

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140050788/08d3d1f0-580c-41f1-9955-68562aff121f)

### 还有别的吗？

目前使用蓝叠 (Pie64版本 Hyper-V)
别的功能 没有异常

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/5e0d88b7-7d83-445a-8366-10a7d8a5b8b7)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/32c7ecf6-f805-48d3-8f6d-3034120400e1)

强制替换ADB失败会用本地的adb，那个不是报错
