### ISSUE TITLE
【建议】萨米肉鸽刷源石锭逻辑优化

### ISSUE THREAD

**Issue by geekzorro008** [MaaAssistantArknights/MaaAssistantArknights#5565]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前自动肉鸽时，选择刷源石锭到第二层退出，在实际体验中，v4.20.0-beta 2 版本的逻辑和之前有所不同。遇到不期而遇触发的战斗，又或者是路径上可以避开的战斗，目前的ai都会选择战斗而不是避开。这和玩家想要尽快刷取源石锭的初衷是相悖的。

### 有什么好的想法？

希望能优化刷源石锭模式下的逻辑，让ai尽量避开非必要的战斗，尽快存钱提高刷源石锭的效率

**Comment by SherkeyXD** [comment]
Duplicate of #5454
