### ISSUE TITLE
ubuntu下maa连接成功后报错

### ISSUE THREAD

**Issue by nullnuo** [MaaAssistantArknights/MaaAssistantArknights#5568]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

ubuntu连接成功后报错，图像识别的问题？libpng太老？

### 日志文件

截图里

### 截图

![IMG_20230720_233642_069](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139941495/91e89991-81f6-49d1-934b-430e92d20492)
这样

### 还有别的吗？

ubuntu版本22.04，x11，maa文件夹权限给足了

**Comment by dfigj** [comment]
大佬，请问adb路径怎么填，我的py文件运行出错
