### ISSUE TITLE
干员识别功能识别错误

### ISSUE THREAD

**Issue by tuanzi12** [MaaAssistantArknights/MaaAssistantArknights#5574]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

干员识别功能识别干员错误，有归溟幽灵鲨却未识别到

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12115822/asst.log) 7/21 10:46
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12115831/gui.log) 7/21 10:46

### 截图

[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12115842/oper.zip)

**Comment by cenfusheng** [comment]
感谢反馈，已尝试修复，将在后续一到两个版本内实装，如仍有问题可继续反馈。
