### ISSUE TITLE
为任务添加超时选项

### ISSUE THREAD

**Issue by TiSpH** [MaaAssistantArknights/MaaAssistantArknights#5575]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前的 `asst::TaskInfo` 中只有
```cpp
int max_times = INT_MAX;                // 任务最多执行多少次
```
这在大部分时间可以良好的工作，但是有些时候任务还是陷入死循环无法结束：
* #5538 会一直等待当前任务直到手动启动明日方舟并进入肉鸽
* #5536 #5530 偶尔卡住不动

用户想要在规定时间内结束：
* #3255 若使用外部定时手段则MAA无法触发结束脚本

### 有什么好的想法？

添加一个
```cpp
int timeout = INT_MAX;                // 任务最多执行多少秒
```
完善相应逻辑并使用户可以在 [`tasks.json`](https://maa.plus/docs/3.4-%E4%BB%BB%E5%8A%A1%E6%B5%81%E7%A8%8B%E5%8D%8F%E8%AE%AE.html) 中为任务添加类似以下选项
```json
"timeout": 60,
"timeoutNext": [
    "Stop"
]
```

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaFramework/blob/main/docs/zh_cn/3.3-%E4%BB%BB%E5%8A%A1%E6%B5%81%E6%B0%B4%E7%BA%BF%E5%8D%8F%E8%AE%AE.md

新坑里有了，老坑不打算填了（bushi

**Comment by TiSpH** [comment]
新坑有就好！

**Comment by SherkeyXD** [comment]
好多人提想要这个功能
~~所以什么时候迁移(x~~
