### ISSUE TITLE
MAA視頻自動辨識功能的完善化

### ISSUE THREAD

**Issue by Arcelibs** [MaaAssistantArknights/MaaAssistantArknights#5577]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

現在視頻自動辨識有幾個問題，分別是

1. 不太適合單核低配打法
這類需要很多低配3* 4*幹員，高複雜性的部屬與撤離
但沒有一個很好參考的數值可以重現原本視頻的打法

參考視頻
[https://www.bilibili.com/video/BV1Sa411G7mK/](https://www.bilibili.com/video/BV1Sa411G7mK/?vd_source=2db211bbeb762a1cf8eecdef99002fc9)

2. 辨識出來的技能都是0，需要手動自行更改，數量多有些麻煩
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49543451/0581bd41-fa70-4b71-b6f3-e1f5c45c1718)

3. 會有部分幹員或者召喚物無法辨識
參考上面的視頻，這個單位應該是桃金娘卻被識別為UnknownDeployment
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49543451/f9e3d7d9-3869-4aee-af9d-ed728039df0a)

**Comment by MistEO** [comment]
需要 log

**Comment by Arcelibs** [comment]
早上生成了另外一個

視頻是
https://www.bilibili.com/video/BV1jW4y1t7yT/

生成出來的Json是
[MaaAI_伦蒂尼姆边缘区块_尘环行动18.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12116562/MaaAI_._.18.zip)

log是
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12116565/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12116566/asst.log)
