### ISSUE TITLE
maa自动肉鸽功能进战斗节点后无操作且报识别错误

### ISSUE THREAD

**Issue by AKCX2002** [MaaAssistantArknights/MaaAssistantArknights#5579]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa其他功能一切正常，仅在进入战斗节点后不下干员，然后报关卡识别错误。肉鸽均有此情况。

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12116669/debug.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40179128/bc440301-58af-4cde-a33a-25289a4884a8)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40179128/ef858d3e-330f-40ea-ab4d-10b922e16f23)
ADB截图：
![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40179128/697bbdaa-3add-4ea0-bf37-b7ef8116d059)

### 还有别的吗？

操作系统:win11 22621.1992
蓝叠模拟器国际版 安卓11 5.12.100.1023

**Comment by Fon509** [comment]
mumu12和雷神一样会出现这个问题

**Comment by misakey-zz** [comment]
mumu12同样问题

**Comment by AKCX2002** [comment]
备份配置后重装MAA解决
