### ISSUE TITLE
关于肉鸽精二问题

### ISSUE THREAD

**Issue by gameNeed** [MaaAssistantArknights/MaaAssistantArknights#5582]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

萨米肉鸽好像用艾雅法拉开局很强，但是好像不会优先精二艾雅法拉，而且选射手时也是优先选的是临时干员而不是克洛斯

### 有什么好的想法？

对于特定输出，希望可以优先精二，而不是抓新的输出。

### 其他内容

。

**Comment by Saratoga-Official** [comment]
现在ew精二率已经拉最高了，可以使用ew，比小羊强多了
