### ISSUE TITLE
已经勾选了投资源石锭，还是不进行存钱

### ISSUE THREAD

**Issue by kid520** [MaaAssistantArknights/MaaAssistantArknights#5583]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图，无论是否勾选投资源石锭，也不会在商店存钱
在其他电脑没问题，但是复制过来该电脑仍然不会存钱

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12122166/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12122168/asst.log)

### 截图

![9a58f8a6455d980a6877143e3c79e01b](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/42537002/47e04ab2-3f02-4787-a509-24c8d6ba452a)

### 还有别的吗？

都是WIN10系统和MUMU12模拟器V3.5.0

**Comment by SherkeyXD** [comment]
貌似是因为刷新事件卡住导致的投资失败
