### ISSUE TITLE
支持同时代理运行在不同环境的方舟

### ISSUE THREAD

**Issue by xfrqh** [MaaAssistantArknights/MaaAssistantArknights#5585]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我的环境：
<img width="826" alt="2023-07-21_15-08-12" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73733485/4214a91d-104f-462e-821c-6702959063f0">

如果Windows中有2个MAA同时在工作，且它们的代理目标分别是手机和模拟器，那么它们就会失去和目标的连接。
可以的操作：仅有一个MAA处于工作状态。或多个MAA连接的目标都是蓝叠的模拟器

演示视频
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73733485/69034f39-3641-419a-ac17-9f0746577823

### 有什么好的想法？

MAA可以同时连接运行在安卓模拟器和手机上的方舟。

**Comment by ABA2396** [comment]
不同版本的adb一起开会互相干扰的，试试用同一个

**Comment by xfrqh** [comment]
> 不同版本的adb一起开会互相干扰的，试试用同xx一个

谢谢大佬。在统一了ADB之后，连接断开的问题就解决了。
