### ISSUE TITLE
一直显示连结失败，已尝试最新版本以及回退版本的maa

### ISSUE THREAD

**Issue by shenlany1973** [MaaAssistantArknights/MaaAssistantArknights#5593]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

无法连接上服务器，，显示连结失败。尝试强制替换过ADB 仍然不行 选择模拟器adb连结不上 选择本地adb显示替换失败 临时使用本地adb

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12135704/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12135706/gui.log)

### 截图

![QQ截图20230722121443](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140226432/fa879760-ac92-40e5-8331-e0b26dd9c8b2)

### 还有别的吗？

雷电模拟器，之前一直正常使用，7月20日开始出现问题

**Comment by aleck099** [comment]
waydroid连接失败
但adb shell能直接打开
adb devices可看到设备

**Comment by defEdYs** [comment]
同样问题
模拟器为蓝叠p64 5.9.135.1001，maa版本为4.20.0beta3

有时可以通过“重启maa”或“重启模拟器”解决，而有时不行

**Comment by ABA2396** [comment]
试试去任务管理器里把adb给杀了
