### ISSUE TITLE
b服，识别相关问题，“开始唤醒”过程在特定情况下会卡住

### ISSUE THREAD

**Issue by wenwuji** [MaaAssistantArknights/MaaAssistantArknights#5595]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

b服在切换账号登录，后续把明日方舟叉掉，再次启动时会有显示“bilibili游戏隐私政策提示”界面，如果是用MAA的“开始唤醒”操作则会卡在这里
（模拟器：MuMu12）

### 日志文件

我觉得不需要，如果需要请留言

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140260199/9afb2fb1-31ed-488c-967c-2dfff48f0992)

**Comment by ABA2396** [comment]
点隐私政策这种肯定是不会去做的
