### ISSUE TITLE
关于MuMu12萨米肉鸽放置干员出错的问题

### ISSUE THREAD

**Issue by 1848296863666** [MaaAssistantArknights/MaaAssistantArknights#5596]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用MuMu12（V3.5.0-1790）和Maa（V4.2.0-Bata-win64）版本运行B服萨米肉鸽，但出现了干员部署不上的问题。
具体表现为：初始一切正常，但进入关卡后部署干员时大概率部署不下去，可以看到有部署动作，将干员拖动至待部署位后直接取消部署，干员死亡后会再部署但仍旧无法实际部署下去。可以观察到maa也没有实际观察部署位是否存在干员，甚至会出现全场没有干员，且干员可部署但maa就看着。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12136768/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12136777/asst.log)

### 截图

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12136782/debug.zip)

### 还有别的吗？

系统：Windows10家庭中文版，已激活的正版Windows
模拟器：MuMu12（V3.5.0），编码为1790
Maa版本：内测Bata版（V4.2.0-Bata-win64），官方github下载，解压包名：MAA-v4.20.0-beta.3.d019.g6125f5d91-win-x64
配置：MuMu：Vulkan模式中性能，平板1280*720，机型预设，开启root。
           Maa：自动检测adb，自动唤醒和自动肉鸽。

**Comment by HongHuangTY** [comment]
我也是，MUMU12能正常进入关卡，但是不会下干员，版本是v4.20.0-beta.3.d019
