### ISSUE TITLE
更新把定时执行顶掉了，更新日志提醒一下好吗，基建计划乱掉了啊

### ISSUE THREAD

**Issue by MoXiaoX** [MaaAssistantArknights/MaaAssistantArknights#5598]

**Comment by ABA2396** [comment]
没太看懂，什么叫 更新把定时执行顶掉了

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f8f504d3-436b-467a-887f-1bbbe31d03b3)
是说的这个问题吗

**Comment by MoXiaoX** [comment]
> 没太看懂，什么叫 更新把定时执行顶掉了

更新前我勾选了三个定时自动运行，是到时间自动换班的。但是更新之后这三个勾没了——定的时间点倒是还保存着——我是第二天基建全红才发现定时启动没了的

**Comment by MoXiaoX** [comment]
哦，没事儿了，rc1修了
