### ISSUE TITLE
macOS+PlayCover环境下，收取信用不完全，访问一两个好友就停了，实际仍可继续访问并获取信用

### ISSUE THREAD

**Issue by FlyGinger** [MaaAssistantArknights/MaaAssistantArknights#5599]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

- 环境
  - macOS 13.4.1 (c)
  - PlayCover 3.0.0.maa.3 (3)
  - MAA 4.20.0-beta.3 (374)
- 问题
  - 收取信用不完全，访问一两个好友就停了，实际仍可继续访问并获取信用

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12137520/asst.log)

没有找到`gui.log`文件。

### 截图

<img width="1838" alt="截屏2023-07-23 09 26 31" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38899898/64c09d20-28f4-4231-a0a0-a90d3cbf200d">
<img width="1838" alt="截屏2023-07-23 09 26 40" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38899898/1b05eb6e-3d96-4c82-97ef-4a74d06b1250">

访问到第二个好友时突然停止。

**Comment by MistEO** [comment]
是已知问题，PlayCover 渲染出来的和安卓模拟器上有差别，需要使用不同的资源文件。mac 的开发者最近比较忙，等他之后有空弄弄吧。

或者有没有其他大佬带带，大致做法是单独弄一个 mac 的增量 tasks.json，内容是

```json
{
    "VisitNextBlack": {
        "templThreshold": 0.9
    }
}
```

MaaCore 这边是支持增量加载的，需要 mac gui 在使用 PlayCover 时额外加载一下这个
