### ISSUE TITLE
mma基建功能问题反馈——没有的人一直找

### ISSUE THREAD

**Issue by ShimotsukiH** [MaaAssistantArknights/MaaAssistantArknights#5600]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我没有琴柳 它一直在找琴柳 找了一个小时（大概）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12137560/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12137561/gui.log)

### 截图

![faf13b6d2347f7111c067a48854faf1f](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/33424662/35645d48-45b8-4306-8158-46897611fa46)

### 还有别的吗？

mumu12
windows11
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/33424662/86967888-9939-482d-84f1-563ed2c3f08a)

**Comment by ABA2396** [comment]
没有肯定会去找啊，要么复制一份基建配置自己修改，要么用制作器重新写一份适合自己基建的配置
