### ISSUE TITLE
与UU加速器之间的联动问题

### ISSUE THREAD

**Issue by Char11ew** [MaaAssistantArknights/MaaAssistantArknights#5601]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

bug为近日发现的，在MAA稳定版和内测版都有出现（逍遥模拟器9.0.3）。在开启UU加速器加速steam任意游戏会导致MAA无法连接模拟器，处理方法为重启电脑；如果先开启UU加速器则会导致MAA卡在正在连接模拟器，这时关闭加速器再重启MAA可以解决。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12137940/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12137941/gui.log)

**Comment by ABA2396** [comment]
uu加速器加速时会更改本地计算机的网络设置，以确保游戏数据流量通过加速通道，但这也会导致通过网络端口通讯的adb出现问题。如果要是用加速器的话，可以在任务管理器中手动结束adb再开始任务，或启动加速器后再开启maa
