### ISSUE TITLE
关于萨米肉鸽提丰开的问题

### ISSUE THREAD

**Issue by RizukiJI** [MaaAssistantArknights/MaaAssistantArknights#5604]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

死囚之夜提丰会乱放

### 有什么好的想法？

提丰开局可以抓炎熔和斑点，而不是史都华德和预备干员-重装，抓炎熔通过率更高一点
死囚之夜直接先放炎熔再放提丰

### 其他内容

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/112483213/5485c138-5a0c-44a8-b311-7ec681689935)

**Comment by huge3286** [comment]
是啊，不知道为啥有斑点卡提不抓。
