### ISSUE TITLE
傀影肉鸽选人问题及提问

### ISSUE THREAD

**Issue by jthyh** [MaaAssistantArknights/MaaAssistantArknights#5609]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

傀影肉鸽中开局选的是稳扎稳打，助战羊，但在选狙击的时候不是选克洛斯或者空爆而是选了一个预备干员，重装干员正常的选择了斑点。（没有修改过任何文件）
按照maa\resource\roguelike里的recruitment.json文件来看，在傀影模式中克洛斯优先级是150，斑点是100，预备干员是5，重装干员有优先度偏移而狙击干员没有。maa能正常选择斑点而不能正常选择克洛斯。
我用maa的时候除了肉鸽模式其他完全没有问题，想同时请教一下是哪个地方使得优先度偏移选择了预备干员。
其实还有相同的情况，在选择近卫干员的时候不选择满级玫兰莎和泡普卡，而是选择预备干员。

后话：还有一点就是在“正义”这一关斑点会被放到最左上角然后全部漏怪，不仅如此，很多图的放干员的逻辑也很怪，不过还没研究copilot.json，先不在此处发起疑问。
（有些情况没截图当时没想着反馈）

### 日志文件

无文件

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140314963/4040df2d-6003-411c-a716-0a48589ac671)
![)KW58UPY9{TC4V9(@TC $4G](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140314963/0614d5db-4dc8-45a3-bfe1-fa1902133a06)
![P@IZZ`5TR~U20_UBW1VPE@O](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140314963/33106d45-be64-4466-a818-5e1069d67143)
![F`F1B6PZ66$65O~75UEVQ(2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140314963/ac3c89f4-4d04-4ec0-b2e0-2590ae6c91cd)
![X$O91ZEJR 0KGCKP B)0QT1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140314963/ba537b9f-34ea-421f-92fb-687203e1b65f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140314963/7baac318-4d85-494d-8a7c-ce61c3ce2ff1)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140314963/4a2cffda-b2ad-42ad-9f17-67bc39c02afd)

### 还有别的吗？

模拟器：雷电模拟器

**Comment by Lancarus** [comment]
[v4.21.1-alpha.1.d031.g7d3e7a443](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v4.21.1-alpha.1.d031.g7d3e7a443)
