### ISSUE TITLE
后台运行时自动更新至4.20.0会导致MAA卡死

### ISSUE THREAD

**Issue by passerbyzhao** [MaaAssistantArknights/MaaAssistantArknights#5613]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

从4.19.3升级至4.20.0时发生。

**系统**：Windows
**maa设置**：定时检查更新、自动下载安装包、自动安装安装包、启动MAA后直接最小化、最小化时隐藏至托盘
**发生条件**：启动4.19.3版本MAA
**Bug表现**：MAA无反应，无法唤起主界面，右键无反应。重启电脑后重启MAA则自动更新完成。

在两台电脑上均发生此Bug，未测试能否由任务管理器关闭MAA。

### 日志文件

[logs.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12138637/logs.zip)

### 大致时间
***-1.log** 启动于18：03，重启大致于19：00之前

***.log** 大致启动与重启在7：30左右

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/115ca0c9-479b-4d59-b9da-4e0752d0f034)
4.9.3版本是会有这个问题，原因是在运行时开了自动安装更新包，等待任务结束的时候阻塞了ui运行，已经在之后的版本修复了
