### ISSUE TITLE
萨米肉鸽疑似识别或点击位置出错

### ISSUE THREAD

**Issue by 342123993** [MaaAssistantArknights/MaaAssistantArknights#5615]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

1.在肉鸽当前页面无动作（或者不知道点在了哪里），有几率打开收藏品页面，并且不断切换收藏品，切换一次记作一次探索，在选择分队页面一直向右滑动，在开局选择干员页面点击一次“随心所欲”后无动作（或者不知道点在了哪里）
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61654408/f78ffdcd-54bc-43fd-adb1-faaea00911b7)
2.在终端页面会点击进入肉鸽，然后重复如上
3.在主页面会进入“干员”，并选择卡缇并试图点击技能升级，有概率切换到下一位干员

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12138797/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12138798/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61654408/79814390-02b8-4baa-8e9f-416b09145825)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61654408/786ebe75-94a8-49a8-98e3-0f553df91e6d)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61654408/3f1a932a-cd3a-4102-ba4f-5c231545b176)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61654408/dccc41ec-218d-4e97-845e-3ba421d77b37)

**Comment by SherkeyXD** [comment]
出于某种原因，MAA 一直在试图匹配 empty.png
> match_templ | empty.png score: 1

**Comment by 342123993** [comment]
> 出于某种原因，MAA 一直在试图匹配 empty.png
> 
> > match_templ | empty.png score: 1

所以应该是代码的问题咯？

**Comment by SherkeyXD** [comment]
试试重下完整包

**Comment by 342123993** [comment]
> 试试重下完整包

谢谢，解决了
