### ISSUE TITLE
对稀有tag刷新提示的识别

### ISSUE THREAD

**Issue by Auxotaku** [MaaAssistantArknights/MaaAssistantArknights#5616]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在使用MAA公开招募时刷新出现了高级资深干员tag
MAA通过消息栏提醒我“公招出六星了”
我在没有关停MAA的情况下打开了公招界面（刷新出高资的窗口）
MAA快速地执行了“刷新”按钮的点击，在系统弹出“含有稀有tag，是否要确定刷新时”
我试图阻止，但MAA快速的点击了确认，我不清楚这是如何发生的，可能是原操作未被中断，导致“确认”按钮位置的点击操作没能终止

### 有什么好的想法？

虽然这种情况确实较为少见，但影响较大
希望能对于游戏UI给出的“高级资深刷新”这一危险行为的提醒作出识别，中止点击操作
避免惨案的发生

### 其他内容

由于刷新已经进行，所以没有办法提供UI提示危险操作的截图

![惨案现场](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91819146/bb532f8c-4e04-4092-9db8-87004a1f672a)

**Comment by ABA2396** [comment]
感谢您向我们报告这个问题。我们理解您所描述的情况，并希望能够帮助您解决这个困扰。

根据您提供的信息，似乎问题的根本原因在于与软件的交互方式。我们强烈建议在使用maa时，尽量避免与鼠标抢占控制权。在软件内部，它已经完成了一个动作并进入了新的游戏界面，而在新界面中只识别到三星词条。在此后的行为中，软件会试图寻找刷新按钮，然后再寻找确认刷新的按钮（和稀有tag的刷新按钮样式是相同的），但是由于手动操作返回了之前有六星的页面，导致软件执行了错误的刷新行为。

值得注意的是，我们的游戏界面在maa眼中并不是实时的，而是通过操作前的截图来进行分析和交互，例如本次事件中，maa并不会重新判断tag。因此，当用户手动改变页面的行为时，可能会导致一系列不确定的后果。

为了避免类似问题的发生，建议在使用软件时尽量按照预期的交互方式进行操作，避免与软件的自动化交互产生冲突。此外，如果您遇到了类似的问题，您可以尝试暂停软件，并确保在软件的操作过程中不进行手动页面改动；或在整个任务流程结束后再进行手动操作。

**Comment by Auxotaku** [comment]
感谢您的及时回复，应该确实是非实时交互方式问题，我的惨案供大家避坑吧
