### ISSUE TITLE
使用萨米肉鸽功能挂机时内存泄漏问题

### ISSUE THREAD

**Issue by XIAOYIHUI** [MaaAssistantArknights/MaaAssistantArknights#5619]
### 说说你遇到的问题？

在晚上挂机萨米肉鸽时候早上发现内存消失了10G

**Comment by XIAOYIHUI** [comment]
使用的是MuMu12模拟器

**Comment by GripenANM** [comment]
Also experience this, the gpu memory will not un-allocate after quitting MAA

**Comment by ABA2396** [comment]
看看任务管理器里maa的已提交内存有多少，感觉应该是模拟器漏的

**Comment by chnhi** [comment]
谎报军情，请更新模拟器，显卡驱动，maa版本。
