### ISSUE TITLE
水月与萨米肉鸽关卡识别问题

### ISSUE THREAD

**Issue by shangxinliangpi** [MaaAssistantArknights/MaaAssistantArknights#5622]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

mumu模拟器和夜神模拟器都存在此问题。在自动肉鸽（水月和萨米），前期都正常，但是识别不到关卡，不摆放干员，然后显示关卡识别错误。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12142295/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12142298/gui.log)

### 截图

![屏幕截图 2023-07-24 140641](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140327989/f7378770-3a18-45fe-8254-c3ddd4b64b5d)
![屏幕截图 2023-07-24 140702](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140327989/3d22af28-fdb6-419a-b5d5-52bda4a3d669)

**Comment by shangxinliangpi** [comment]
频率的话，一开就有。会不会是我电脑坏了。

**Comment by SherkeyXD** [comment]
Duplicate of #5463
重新下载完整包即可
