### ISSUE TITLE
挂机肉鸽时电脑总是自动重启

### ISSUE THREAD

**Issue by mopssis** [MaaAssistantArknights/MaaAssistantArknights#5627]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

每次挂肉鸽时都会自动重启，差不多挂30分钟之后就会出现，是正常的重启流程，会显示正在关闭电脑......的画面，不是硬件问题电脑嘎嘎好

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12143763/asst.log)

### 截图

截图没有bug画面

### 还有别的吗？

用的是夜神模拟器，系统是win11

**Comment by mopssis** [comment]
它会摸鱼啊，我盯了6个多小时没崩，我出去上个厕所回来就崩了，是不是有些智能过头了？

**Comment by midsummer03** [comment]
> 它会摸鱼啊，我盯了6个多小时没崩，我出去上个厕所回来就崩了，是不是有些智能过头了？

是这样的，我盯半天他不崩，我一走就崩，而且单独挂一宿模拟器和maa不运行肉鸽的时候电脑一点事情没有，cpu是amd5800x

**Comment by zqyoi** [comment]
一樣問題，把CPU降頻後就沒事了，我5800x降成3750mhz之後沒死機過

**Comment by ADMIPO** [comment]
我的电脑是挂上MAA有几率直接电脑黑屏（类似于直接断电）重启，没找到原因

**Comment by oracleless** [comment]
我的情况是禁用集显的一个多月，所有自动化程序（maa、alas、bbchanel）运行期间都有概率导致Win10黑屏重启。最近才想起启用集显，没有再黑屏重启过了。
黑屏重启的问题与散热无关，与CPU、GPU负载无关。同时玩其他大型游戏+开直播+后台运行模拟器，都从未黑屏重启过，唯独跑自动化脚本会重启，单独跑都会重启。
与模拟器无关，alas对应的夜神模拟器，maa对应的mumu12，都在单独运行期间黑屏重启过。其中maa黑屏重启最为频繁，而且在“获取信用及购物”阶段重启概率最大。

还有一种特殊情况，系统运行一段时间后关闭外接显示屏，MAA再定时重启，这时也有概率黑屏重启，哪怕不黑屏重启也会卡成PPT。可能是系统自动禁用了核显，目前手动改N卡设置和电源管理选项都没用，可能要改BIOS设置。

**Comment by Rbqwow** [comment]
内测版已提供GPU加速功能 同时添加了最小截图间隔 已经优化CPU占用
大概率是运气不好 cpu品质买到差的了 还会复现就带个事件查看器再reopen吧
