### ISSUE TITLE
使用时出现错误

### ISSUE THREAD

**Issue by Dinald-unix** [MaaAssistantArknights/MaaAssistantArknights#5628]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 遇到了问题
索引超出范围。必须为非负值并小于集合大小。
参数名: index

### 日志文件

MAA 遇到了问题
索引超出范围。必须为非负值并小于集合大小。
参数名: index
解决方案
出现未知错误
详细信息
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.IncreaseCustomInfrastPlanIndex()
   在 MaaWpfGui.Main.AsstProxy.ProcTaskChainMsg(AsstMsg msg, JObject details)
   在 MaaWpfGui.Main.AsstProxy.ProcMsg(AsstMsg msg, JObject details)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by SherkeyXD** [comment]
日志，请
