### ISSUE TITLE
萨米自动肉鸽无法正常战斗，会暂停

### ISSUE THREAD

**Issue by kinkin97** [MaaAssistantArknights/MaaAssistantArknights#5631]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选择自动肉鸽萨米主题刷取源石锭，从最开始开始战斗后大概打了一会就会自动暂停，并且无法继续，有观察过一直暂停了几十分钟；也出现过部署干员时一直选中但不落地部署的情况，导致一直处于部署操作界面。因此基本就在第一场战斗就卡死了，但没有出现什么报错信息。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12147134/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12147138/gui.log)

### 截图

![KNBL @Z@`WC@IB0%R@1{OGK](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140416048/24c02a26-5e4b-4644-b0b4-a3ca6e97fd77)

**Comment by SherkeyXD** [comment]
注意到你的帧数过低，这会影响 MAA 的部署以及其他操作

**Comment by kinkin97** [comment]
> 注意到你的帧数过低，这会影响 MAA 的部署以及其他操作

今天早上又用了一下，自动公招，刷理智，获取信用及购物和领取日常奖励都正常，帧率都维持在60左右。但自动肉鸽还是会自动暂停，肉鸽的时候帧率掉到40+到50+，但是也不至于过低吧，反正就肉鸽刷钱有问题，其他都可以正常运行的

**Comment by ntgmc** [comment]
你模拟器要关闭动态调整帧率 不然就会掉帧
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/bc8b3da4-68ec-458c-8d46-48b14e9e5a5e)

**Comment by hkp1995** [comment]
我也遇到了这个问题，我用的蓝叠。单开，也没有开动态帧率，默认是60，但是确实战斗过程中经常低于60，大概30.40。然后萨米肉鸽刷钱，人就走了，结果回来发现刷了一下午都只刷了6块钱，看记录就是不断地重开肉鸽但是每次就打一局或者根本没战斗。于是就人盯着看，发现总是暂停。估计是误触了暂停，长时间没结束战斗就自己终止了。这个问题确定是跟帧率有关吗

**Comment by kinkin97** [comment]
> 我也遇到了这个问题，我用的蓝叠。单开，也没有开动态帧率，默认是60，但是确实战斗过程中经常低于60，大概30.40。然后萨米肉鸽刷钱，人就走了，结果回来发现刷了一下午都只刷了6块钱，看记录就是不断地重开肉鸽但是每次就打一局或者根本没战斗。于是就人盯着看，发现总是暂停。估计是误触了暂停，长时间没结束战斗就自己终止了。这个问题确定是跟帧率有关吗

我目前还是不知道这个问题时什么原因。之前我用的是mumu12出现了这个问题，我是普通刷理智的时候帧不会掉，但肉鸽就会偶尔掉帧，然后一直重装模拟器重装maa等都试过不行。然后后面就一直换模拟器试，目前我反倒是换到蓝叠之后可以正常刷肉鸽了。我刚浏览了一下issue发现这两天多了很多同样的issue提交，都是肉鸽自动暂定或者不下干员。
