### ISSUE TITLE
macOS maa无法更新到最新版本

### ISSUE THREAD

**Issue by YuhangTom** [MaaAssistantArknights/MaaAssistantArknights#5633]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12148362/asst.log)

### 截图

<img width="1512" alt="Screenshot 2023-07-25 at 01 08 49" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45880737/792b7ded-9d54-443d-890e-0e9778fdb236">
<img width="1512" alt="Screenshot 2023-07-25 at 01 08 57" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45880737/9c56e1af-9cc3-4526-b8aa-67e8413c9f5d">
<img width="1512" alt="Screenshot 2023-07-25 at 01 09 04" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45880737/e58f8a68-654a-4302-8628-fa1f5482a2bf">

### 还有别的吗？

PlayCover
Maa v4.20.0-beta.3（374）
macOS Ventura 13.4.1(c)

**Comment by YuhangTom** [comment]
翻不翻都试了好几次 都不行

**Comment by AnnAngela** [comment]
上传脚本没有报错：<https://github.com/MaaAssistantArknights/MaaRelease/actions/runs/5635525848/job/15266627857#step:7:1>

**Comment by YuhangTom** [comment]
可以了 泪目 谢谢大佬
<img width="1512" alt="Screenshot 2023-07-25 at 09 38 28" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45880737/8662e487-1441-4e83-97ac-c34488f988b9">
