### ISSUE TITLE
版本最新，一直占用网络

### ISSUE THREAD

**Issue by XieQIYUE** [MaaAssistantArknights/MaaAssistantArknights#5634]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

间断性频繁占用网络，是不是被注入病毒了？

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12156096/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12156106/asst.log)

### 截图

<img width="656" alt="屏幕截图 2023-07-25 085637" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/109218545/bca13e59-6f73-4dfa-bb66-bff6c8be589d">

**Comment by ABA2396** [comment]
adb用的是本地网络通讯，这个软件把本地通讯也算进去了。

**Comment by XieQIYUE** [comment]
收到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月25日(星期二) 中午11:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 版本最新，一直占用网络 (Issue #5634)





 
adb用的是本地网络通讯，这个软件把本地通讯也算进去了。
