### ISSUE TITLE
萨米肉鸽自动挂机经常闪退

### ISSUE THREAD

**Issue by SCP-668** [MaaAssistantArknights/MaaAssistantArknights#5638]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

这两天挂了十几次机，每次都是过一段时间，软件就闪退了，也没有什么提示之类的，之前挂水月也没有这种问题

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12160059/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12160061/asst.log)

### 还有别的吗？

win10,  夜神模拟器， 默认配置拉满

**Comment by SherkeyXD** [comment]
方舟的问题，萨米肉鸽版本更新完 bug 多了一堆

**Comment by chnhi** [comment]
换mumu12
