### ISSUE TITLE
增加每日抽一发免费的单抽（夏活等）任务

### ISSUE THREAD

**Issue by oEthan2333o** [MaaAssistantArknights/MaaAssistantArknights#5639]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

增加每日抽一发免费的单抽（夏活等）任务，这样在学校自动挂机就不用担心了

### 有什么好的想法？

增加每日抽一发免费的单抽（夏活等）任务，这样在学校自动挂机就不用担心了

### 其他内容

无

**Comment by WSMTBG** [comment]
我自己抽全三星怪不了别人

**Comment by MagicianStarSky** [comment]
同求
