### ISSUE TITLE
关于wsa的连接错误问题

### ISSUE THREAD

**Issue by 1qazxsw23edc13597** [MaaAssistantArknights/MaaAssistantArknights#5641]
先是提升打开客户端失败，再然后是无限循环的截图失败
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102916992/c6d5e9bd-1f68-4473-b4a7-a73a9286a447)
相关的配置如图
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102916992/c9b1fb0f-fbb2-4911-9df0-6ba123c7793c)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102916992/837f0f90-5191-42f2-8f99-3e5cceb6b935)
请问可能是哪里的问题呢？

**Comment by 1qazxsw23edc13597** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102916992/60863018-bdfb-4f6a-8a0b-ee48bcdc0f31)
以及使用的版本

**Comment by SherkeyXD** [comment]
> m_controller  is not inited
大量出现该错误

**Comment by 1qazxsw23edc13597** [comment]
请问可以通过什么办法处理呢？

**Comment by undefined-moe** [comment]
WSA 版本 2309 仍能复现改问题，尝试切换模式无法解决。
