### ISSUE TITLE
繁中服基建換班異常

### ISSUE THREAD

**Issue by yl170512** [MaaAssistantArknights/MaaAssistantArknights#5642]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如題
本人測試基建換班時發現程式執行到最後貌似忽略了控制中樞的部分

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124447739/df0abab2-cf9f-447e-b35f-850ef2ab54ce)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124447739/554048aa-042a-49e5-8e43-6fd4b524ec95)

而本人的所有設定中並未刻意設定跳過控制中樞的部分

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124447739/2ede4884-bfaa-43c8-8cbd-e6212597492b)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124447739/2f827bc9-beee-4049-938b-9fd7221deef8)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12163490/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12163499/gui.log)

### 截图

此為利用模擬器本身的截圖功能所擷取的基建畫面

![Screenshot_20230726-001448](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124447739/9879ad79-7818-48d6-bfe8-369c9ca6e7ed)

### 还有别的吗？

另外本人還發現幹員識別功能貌似無法識別繁中服的部分幹員

以我的部分為例:
百煉嘉維爾、耀騎士臨光、假日威龍陳和鞭刃並未被辨識出來

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124447739/6e03a4a1-5939-4896-b159-05afa09800bc)

以下為模擬器截圖 : 

![Screenshot_20230726-002308](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124447739/1627819d-7c5b-459e-a075-e919b1a52a2e)

**Comment by ms200tswd** [comment]
是的，我也發現百煉嘉維爾、耀騎士臨光、假日威龍陳識別不了，我是在傀影肉鴿裡面
