### ISSUE TITLE
在自动公招功能中，如果招聘许可不足，MAA会返回识别错误

### ISSUE THREAD

**Issue by wei-dh** [MaaAssistantArknights/MaaAssistantArknights#5643]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在自动公招功能中，如果招聘许可不足，MAA会返回识别错误，同时自动结束自动公招过程

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12164127/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12164129/gui.log)
2023-07-26 1:41

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140543831/6e64cbbf-564e-487c-9763-07b39dc5e4dc)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140543831/3e918144-d240-4981-88d4-f921864b3dcd)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140543831/3475b60f-39dc-41e2-ae2a-930309845cef)

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140543831/3c3d3bb1-e816-42f6-85bb-3fc1cfec2946)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140543831/ee6931ef-5c64-4d8c-9833-aefa770ca112)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140543831/c9365bc5-7947-429d-b8c1-3ceb9c3710e1)

**Comment by KawausoJyou** [comment]
不然该怎么做？没有招聘许可自然应该结束

**Comment by wei-dh** [comment]
可以直接在MAA操作界面右侧的日志，返回提醒招聘许可不足，不跳出弹窗吗？直接返回识别错误会跳出弹窗（只是建议现在这样也不会有影响使用的bug）

**Comment by wei-dh** [comment]
> 可以直接在MAA操作界面右侧的日志，返回提醒招聘许可不足，不跳出弹窗吗？直接返回识别错误会跳出弹窗（只是建议现在这样也不会有影响使用的bug）

**Comment by wei-dh** [comment]
> 不然该怎么做？没有招聘许可自然应该结束

可以直接在MAA操作界面右侧的日志，返回提醒招聘许可不足，不跳出弹窗吗？直接返回识别错误会跳出弹窗（只是建议现在这样也不会有影响使用的bug）

**Comment by wei-dh** [comment]
> > 不然该怎么做？没有招聘许可自然应该结束
> 
> 可以直接在MAA操作界面右侧的日志，返回提醒招聘许可不足，不跳出弹窗吗？直接返回识别错误会跳出弹窗（只是建议现在这样也不会有影响使用的bug）

第一次用github不太熟悉怎么回复comme不好意思

**Comment by SherkeyXD** [comment]
> 可以直接在MAA操作界面右侧的日志，返回提醒招聘许可不足，不跳出弹窗吗？直接返回识别错误会跳出弹窗（只是建议现在这样也不会有影响使用的bug）

招聘许可不足会被判定为任务失败，所以会有弹窗
