### ISSUE TITLE
雷电模拟器虚拟机内存泄漏

### ISSUE THREAD

**Issue by HKiro17** [MaaAssistantArknights/MaaAssistantArknights#5644]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

程序似乎引发了虚拟机的内存泄露，在22分钟的运行时间里虚拟机使用的内存增加了约10G。停止程序会使虚拟机使用的内存缓慢减少。持续运行会导致模拟器最终卡死。在此过程中有时会出现无法启动adb.exe的报错窗口和程序闪退（闪退造成了系统卡顿与桌面窗口管理器的重启）。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12165589/asst.zip)
[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12165592/gui.zip)
MAA程序于05：01：30左右发生崩溃，重启后继续运行，模拟器于05：06左右发生崩溃

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/100775732/f35fd1c3-5281-4287-9b64-4e45556649c7)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/100775732/e019128a-4499-4183-8c82-1fa045831978)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/100775732/bde35aa4-043f-415a-be27-c79e978960a9)
事件查看器的记录：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/100775732/9f966860-009b-4c42-a1e9-0c49e55c28ec)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/100775732/0055873c-02ed-4900-bf85-bd90cc60f3de)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/100775732/c65c9553-9f05-4699-bc7e-c3b3799c321b)

### 还有别的吗？

操作系统：Microsoft Windows 10 64位  22H2
CPU型号：AMD Ryzen 5 5600X 6-Core Processor             
主板：Micro-StarInternationalCo.,Ltd._MAGB550MMORTAR(MS-7C94)
总内存：31.9 GB
可用内存：8.9 GB
显卡型号：AMD Radeon RX 6750 XT (driver 20221130)
OpenGL：4.6.0 Compatibility Profile Context 22.11.2.221130
IE版本：11.0
模拟器版本：9.0.19(9)
模拟器路径：E:\leidian\LDPlayer9
日志路径：C:\Users\Administrator\AppData\Roaming\leidian9\log
vt:开启
运行参数：CPU(4核) 内存：(4096M) 正在运行(1) 高速(1)
分辨率：720x1280 dpi 320 fps 60
模拟器日志
[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12165788/log.zip)
若有其他需要提供的信息请联系此邮箱：787939460@qq.com

**Comment by HKiro17** [comment]
其他需要提供的数据通过此邮箱联系：787939460@qq.com

**Comment by clark1091** [comment]
同出现类似bug，我这边是虚拟机以及MAA本体闪退，隔壁的Alas报内存无法分配，不过我技术力不足不知道该怎么查找和上报

**Comment by SherkeyXD** [comment]
与 #5619 为同类问题
> 看看任务管理器里maa的已提交内存有多少，感觉应该是模拟器漏的
> https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5619#issuecomment-1647524586

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/41cdefbb-9f22-4160-acda-6e5209cb367e)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/899b2f4c-7b11-4a69-8506-d26cf2656b34)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/37912846-8a69-4ff7-b744-41d5558b31ea)

**Comment by ABA2396** [comment]
感觉可能是模拟器截图处理的不是很好（？）或许可以和雷电反映下

**Comment by HKiro17** [comment]
MAA未运行时：


运行7分钟后：

此后仍在增加
GitHub上也已回复
有急事所以无法做更长时间的监测


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月26日(星期三) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 雷电模拟器虚拟机内存泄漏 (Issue #5644)

**Comment by GripenANM** [comment]
https://www.reddit.com/r/BlueStacks/comments/rsgl57/bluestacks_5_memory_leak/
应该是类似的问题-->Open-GL

**Comment by GripenANM** [comment]
For me instead of RAM usage, mine was GPU memory. Since Emulators will cache the screenshots in the GPU memory/Ram (I think only when using ADB ???? Not sure), when MAA is running, I saw the GPU Ram usage will accuminate unrestrictively during one mission such as Changing Infrastructure/Base(Speed of accumulation is proportional to your FPS), it will not release the RAM/GPUmem until the current mission is complete. And if MAA is stopped, the memory used in RAM/ GPUmeme will not be released. This happens to me with both NOX and Bluestack with Direct X, causing issues when I am running auto 肉鴿.

**Comment by chnhi** [comment]
雷电一直有截图多了会显存泄漏的bug，bug已经有两年了。9.0.37号称修复了这个bug。
还不如用mumu12，升级到vulkan，流畅多了。

**Comment by HKiro17** [comment]
> 雷电一直有截图多了会显存泄漏的bug，bug已经有两年了。9.0.37号称修复了这个bug。 还不如用mumu12，升级到vulkan，流畅多了。

确实，0.54没有出现这个问题
