### ISSUE TITLE
自动肉鸽进入战斗时的CPU占用异常过高

### ISSUE THREAD

**Issue by snowly233** [MaaAssistantArknights/MaaAssistantArknights#5645]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在肉鸽进入战斗之后MAA的CPU占用运行会达到极高，超过绝大部分的3A游戏的CPU占用（i5-13500hx的CPU占用瞬间达到80% 4.3Ghz并将在5-10秒内保持50%CPU占用左右），个人怀疑是高频ocr图像识别导致该现象的发生。
且问过部分玩家，这是属于少部分人会出现的一种bug

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12166624/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12166542/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75160294/d28e1208-76bd-49ec-a3fe-293bf6ea190f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75160294/9b6ac56b-64f0-49e8-a212-60b1af9f2c43)
甚至在非战斗状况下识别干员的时候也会出现这样的高占用CPU的情况
### 还有别的吗？
CPU：i5-13500hx
电脑型号为七彩虹x15 AT 23

**Comment by SherkeyXD** [comment]
在日志中没有看到高频 ocr 识别的迹象

**Comment by snowly233** [comment]
> 在日志中没有看到高频 ocr 识别的迹象

那我不知道为什么会出现这么高的CPU占用原因了

**Comment by SherkeyXD** [comment]
萨米肉鸽有出现类似现象吗

**Comment by snowly233** [comment]
我是用水月肉鸽发现这种状况的

**Comment by Kaze-maru** [comment]
> 萨米肉鸽有出现类似现象吗

我挂的萨米肉鸽，也有这种情况。正常挂图和保全都是正常的。

**Comment by snowly233** [comment]
顶一下，我觉得这个bug还是比较重要的，希望重视一下

**Comment by Add2seconds** [comment]
用的13700k
挂萨米肉鸽战斗时cpu占用率一直在30%左右，时不时也会冲到40%或更高

**Comment by Rbqwow** [comment]
内测版已提供GPU加速功能 同时添加了最小截图间隔 已经成功优化
~~有问题再reopen~~
