### ISSUE TITLE
水月肉鸽

### ISSUE THREAD

**Issue by cjcxj** [MaaAssistantArknights/MaaAssistantArknights#5647]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

挂水月肉鸽时经过凌晨4点就不会继续进行，一直停留在签到界面

### 日志文件

[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12167114/gui.zip)

**Comment by SherkeyXD** [comment]
Duplicate of #5273
