### ISSUE TITLE
希望增加一个小工具，可以在集成战略中刷取职业队的精二干员

### ISSUE THREAD

**Issue by letdawn** [MaaAssistantArknights/MaaAssistantArknights#5648]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

希望能提供一个小工具，来刷集成战略职业队精二干员。例如萨米肉鸽选择狙击医疗分队并指定提丰，当在初始招募券位置找到精二提丰时，显示完成任务，若无则退出，等待重新探索。直至招募到精二提丰

**Comment by SherkeyXD** [comment]
Duplicate of #5539
