### ISSUE TITLE
优化maa刷源石锭策略的逻辑，提升运行效率

### ISSUE THREAD

**Issue by Traveler2591** [MaaAssistantArknights/MaaAssistantArknights#5649]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

从萨米肉鸽开始用maa刷源石锭，发现一些运行过程中的可优化方向
· 一层偶尔出现的特殊关卡“半吊子之旅”，maa会直接进去打而不是直接跑路
· maa在一层存完钱之后会用剩下的钱买东西
以及一个不知道是不是bug的情况（测试版）：在源石锭策略下maa仍有可能在进入第二层之后继续游戏

### 有什么好的想法？

考虑到使用该策略应当优先考虑时间效率，可能可以作出如下改动：
· 进入一层商店存完钱之后立刻退出
· 在不期而遇中遭遇一层的特殊关卡时，直接选择跑路

**Comment by SherkeyXD** [comment]
> 进入一层商店存完钱之后立刻退出
 
#1555
> 在不期而遇中遭遇一层的特殊关卡时，直接选择跑路

目前 MAA 缺乏根据选择的战斗模式更改不期而遇选项的逻辑，如果你有兴趣欢迎帮我们修改

**Comment by CharlesChou73** [comment]
购物是为了在结算时多拿藏品分数，兼顾刷等级，进第二层再退出也是一样的目的，这些都是很久之前一个版本加的，其实都挂机刷钱了不差这一分半分钟的，要么就像楼上说的一样细化不同策略。
