### ISSUE TITLE
在MAA上的自动肉鸽功能 在战斗时自动暂停并等待到游戏结束

### ISSUE THREAD

**Issue by Ayearr** [MaaAssistantArknights/MaaAssistantArknights#5651]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

模拟器mumu12,
无论是古堡，水月还是萨米都会在战斗时自动暂停，大概率在第一关战斗（或者说第一场战斗）（或者是任何战斗关卡）时直接进入暂停、不放置干员或进行其它操作，然后直接拖到超时放弃。
保证全程fps没有低于45

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12168130/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140581873/085c2e3d-b133-49a7-9562-2d8f6dd5d727)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140581873/8457a0a5-052e-475e-81c8-cc88ddbd05bb)

### 还有别的吗？

Mumu12,windows 10 22H2,Intel core i5-13400f,Nvidia geforce rtx 2060.

**Comment by SherkeyXD** [comment]
mumu12 建议关闭动态帧率调整
详见 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5631#issuecomment-1649136355
