### ISSUE TITLE
台服不能抽卡牛牛

### ISSUE THREAD

**Issue by Arcelibs** [MaaAssistantArknights/MaaAssistantArknights#5652]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

台服不能抽卡牛牛

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49543451/ffd9ca4a-72c1-48ad-ae38-baaec0c4f116)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12170726/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12170727/gui.log)

### 还有别的吗？

台服 Android9 pie x64 藍疊國際版

**Comment by ABA2396** [comment]
试试在resource/global/txwy/resource/tasks.json的末尾加上
```
     ,
    "GachaOncePrefix@DoGacha": {
        "text": [
            "尋訪一次",
            "訪一次"
        ]
    },
    "GachaTenTimesPrefix@DoGacha": {
        "text": [
            "尋訪十次",
            "訪十次"
        ]
    }
```
看看能不能执行
