### ISSUE TITLE
肉鸽通关后保存结算界面截图

### ISSUE THREAD

**Issue by Miuzarte** [MaaAssistantArknights/MaaAssistantArknights#5656]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

挂了两天水月昨天通了一次刚刚连着通了两次，很好奇拿到了什么藏品能通关，想看看结算界面

### 有什么好的想法？

保存通关的结算界面截图，或许顺便还能加个MAA的水印

### 其他内容

![9350d082198db0da1ae1fc0d7042452c](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66856838/3d6e8a8c-9d13-4447-a4b5-996e5deaccfd)
![953f992a1593c450fe6ec374c9440624](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66856838/37e046bf-b07b-4a8c-af92-27e2985830a2)
![22e9a5dc624394ff010b0695c9dafdf2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66856838/a7f09906-6be1-473f-a1df-154094f98ea3)

**Comment by ABA2396** [comment]
看看debug/roguelike里有没有

**Comment by MistEO** [comment]
现在就有的，debug/roguelike 里

加水印是好主意

**Comment by status102** [comment]
- #7276 已实现保存截图并输出结算信息到Gui，不过没加水印
