### ISSUE TITLE
基建换人会卡住

### ISSUE THREAD

**Issue by qudaodian** [MaaAssistantArknights/MaaAssistantArknights#5659]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建换人会卡死，然后游戏换不了人，要重启游戏才可以换人，但是maa重启后还是会有这样的问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12179142/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12179143/gui.log)
7/27 早上8点和9点

### 截图

[f69059f4f4627d919d322d03181d17f2.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12179191/f69059f4f4627d919d322d03181d17f2.zip)

### 还有别的吗？

模拟器是mumu12，操作系统win11，显卡4060，maa版本v4.20.00

**Comment by waooooooooooo** [comment]
一样的bug，一样的win11，一样的4060，一样的拯救者
