### ISSUE TITLE
在萨米肉鸽中，maa经常不下人

### ISSUE THREAD

**Issue by luo-luo-o** [MaaAssistantArknights/MaaAssistantArknights#5667]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，在萨米肉鸽中，maa经常不下人。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12181584/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12181598/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12181600/asst.bak.log)
时间：15时之后一直有这种情况

### 截图

[Uploading 新建视频录制2.zip…]()

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129922074/fcef3778-521a-4ad1-beb5-ee51092d4192)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129922074/ba778653-1ce4-438f-a52e-3937b8e74bf0)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129922074/1c45766b-13f1-40da-a6a6-c0b7746604d3)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129922074/f5824cc7-07f6-40c3-866b-5f594a22fb4e)

用的是mumu6。

**Comment by luo-luo-o** [comment]
视频上传不了（太大了，压缩了还是太大了），就是maa进入战斗后搁那发呆不下人的录屏

**Comment by luo-luo-o** [comment]
还有一个问题，maa经常自己暂停，然后就一直暂停，在上面的asst里偶尔也有体现
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129922074/fc644146-0f04-49ae-956b-a5aac481c05f)

**Comment by avw621314** [comment]
MaaTouch理論速度最快，但有時候會觸控不良(個人實測體驗)，推薦使用MiniTouch更穩定。

**Comment by luo-luo-o** [comment]
> MaaTouch理論速度最快，但有時候會觸控不良(個人實測體驗)，推薦使用MiniTouch更穩定。

这样子的吗，我之前一直用maatouch都没问题，就这几天出了问题。。。在执行其他任务时也没问题的，就萨米肉鸽有这个问题。。谢谢解答啦

**Comment by chnhi** [comment]
我感觉是因为没有用16:9的分辨率。
