### ISSUE TITLE
台服适配水月肉鴿

### ISSUE THREAD

**Issue by MUMEI1** [MaaAssistantArknights/MaaAssistantArknights#5668]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

台服水月肉鴿中不下人 然後顯示關卡識別錯誤

### 日志文件

[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12181891/log.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105075833/b1e6b379-8810-4fe0-a1e3-688a909f2b89)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105075833/31459bfd-8d61-492b-84c1-215bde5ce560)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105075833/ea8f0d06-70bc-4bcc-af03-aaa0b519d07f)

### 还有别的吗？

模擬器使用BlueStacks

**Comment by Arcelibs** [comment]
很正常，水月今天剛出，MAA自然沒有台服水月的資料
歡迎一同加入截圖的行列共同建設MAA

**Comment by avw621314** [comment]
您好，tw服水月肉鴿目前已能支持一層商店自動投幣循環，請下載最新版本MAA使用。
源碼版使用方法: 在MAA官網https://maa.plus/下載程式，並於本庫下載ZIP檔案解壓，找到resource資料夾並替換成ZIP包內的最新版本資源即可使用。

**Comment by ms200tswd** [comment]
> 您好，tw服水月肉鴿目前已能支持一層商店自動投幣循環，請下載最新版本MAA使用。 源碼版使用方法: 在MAA官網 https://maa.plus/ 下載程式，並於本庫下載ZIP檔案解壓，找到resource資料夾並替換成ZIP包內的最新版本資源即可使用。 ![image](https://user-images.githubusercontent.com/140728867/256758574-ecd7e802-b061-4e12-ba68-f683950532dc.png) ![image](https://user-images.githubusercontent.com/140728867/256758694-40a62142-f05c-46fb-a537-ddcdbf3ed142.png)

感谢感谢大佬，繁中服+1
