### ISSUE TITLE
无法连接waydroid,直接用adb命令连的上,maa连不上

### ISSUE THREAD

**Issue by xiaowu-PRC** [MaaAssistantArknights/MaaAssistantArknights#5669]
### 说说你遇到的问题？

![Screenshot_20230727_180920](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96490847/ddb7013f-a1e6-4c61-98af-80a852f6dd5c)
![Screenshot_20230727_180959](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96490847/c18416c8-79be-4208-9703-6a38c4c24bde)
![Screenshot_20230727_181334](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96490847/d6e043b5-6d7c-442e-9166-d847de211b75)
以上三张图分别为：
1、报错内容、adb文件路径及waydroid ip地址
2、sample.py文件内容
3、系统版本

**Comment by horror-proton** [comment]
工作目录下应该有个 debug 文件夹, 里面的 asst.log 发下看看
(另外 MAA 不需要也不应该用 sudo 运行)

**Comment by xiaowu-PRC** [comment]
> 工作目录下应该有个 debug 文件夹, 里面的 asst.log 发下看看 (另外 MAA 不需要也不应该用 sudo 运行)

谢谢大佬提醒，检查了下是我做软连接的时候忘了把resource一并连接过来了，maa报找不到resource,但看到报连接失败我就没往那方面想，谢谢大佬一语点醒梦中人。(那个sudo是手滑打多了，现在已经去掉了)

**Comment by xiaowu-PRC** [comment]
> 工作目录下应该有个 debug 文件夹, 里面的 asst.log 发下看看 (另外 MAA 不需要也不应该用 sudo 运行)

大佬我提个意见，我记得就是那个arch系的linux用yay安装maa后会有做软连接到自己目录的示例，我记得里面貌似没写软连接resource,能把resource的软连接提示也加上吗，没记错的话我就是按照那个提示做结果忘了软连接resource

**Comment by horror-proton** [comment]
如果你正确设置了 `path='/usr/share/maa-assistant-arknights'`, maa 应该能自己找到 resource 文件吧

**Comment by xiaowu-PRC** [comment]
> 如果你正确设置了 `path='/usr/share/maa-assistant-arknights'`, maa 应该能自己找到 resource 文件吧

抱歉，我的锅，下面还有一行，对不起打扰大佬了。
