### ISSUE TITLE
操作异常 任务链跑完了 但是实际上部分任务没做

### ISSUE THREAD

**Issue by zhangweijian97** [MaaAssistantArknights/MaaAssistantArknights#567]
先上日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8758744/asst.log)

场景是，用定时任务设置了早上8点（今天5月24号，方便找asst），任务链包括 理智 公招 基建 好友 商店 奖励

然后我打开电脑的时候已经八点半多了。我打开模拟器，仔细看了看，

- 理智没执行，因为是满的
- 公招没执行
- 基建应该是做了一半，菜收了，无人机没用，换班换了一半，控制中枢有看到满心情的干员，但是最底下的制造站，有干员心情接近于0，比如看到了霜叶和史都华德。
- 好友访问，执行了
- 商店没执行
- 奖励执行了

会是什么原因呢？

**Comment by zzyyyl** [comment]
看起来是有些 adb 点击指令失效了？

**Comment by zzyyyl** [comment]
> 看起来是有些 adb 点击指令失效了？

看你的日志里面好多`正在提交`，也有可能是网络太差导致（网络差也会导致点击失效）

**Comment by MistEO** [comment]
> 还有，有没有更人性化一点的log。看的眼睛疼。还看不出表达了啥

log 当然不是给用户看的。。是用来追调用栈和调试信息的（
