### ISSUE TITLE
您好，請問外服(尤其台服)肉鴿的自動作業進度? 不知能否幫上忙?

### ISSUE THREAD

**Issue by avw621314** [MaaAssistantArknights/MaaAssistantArknights#5672]
### 说说你遇到的问题？

[台服]包括水月以及傀影肉鴿，目前我個人使用也出現了如同https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5668
中出現的相關問題，請問貴團隊有需要幫忙的地方嗎? 我可以提供資源截圖、繁簡翻譯等基礎工作，有教程的話也能自行上傳資料。
目前希望能盡快啟動原石錠掛機流程，之後再展望全關卡推圖。

**Comment by avw621314** [comment]
關卡辨識錯誤後，如果繼續手動操作通關，MAA可以接手通過除戰鬥外所有節點，並且自動投幣進第二層退出重開且再度卡在首輪戰鬥辨識。

個人推測是關卡辨識的繁簡文本問題，如可優化的話還請麻煩了，感謝!

**Comment by avw621314** [comment]
大致了解了，帶字的圖是吧，我嘗試提交一些，常規關卡優先，緊急再說。

**Comment by avw621314** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140728867/bebaccb3-acd4-41fb-b0c9-87aa434cbff5)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140728867/b31bcbc9-2bd4-46e1-93c0-0b17219cdc3b)

**Comment by avw621314** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140728867/e85fe825-8308-4c48-9fe4-92f281230f00)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140728867/33761843-7332-4db6-9732-0b0cfc8ac8ae)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140728867/fd6bce84-c214-4964-b3cc-4e9848e1f3f7)

**Comment by avw621314** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140728867/fa3bd1b9-436b-421a-a889-a4eebb1a8596)
下面是兩個第二層的關卡，一層緊急還在roll
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140728867/64c56605-bed6-497d-930e-f238005ac4a1)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140728867/dd48c5d9-e409-4ac1-af5a-f7d0408ab858)

**Comment by avw621314** [comment]
其餘部分在https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/5670中繼續更新。

**Comment by avw621314** [comment]
了解，等刷到緊急射手一並上傳~

**Comment by MistEO** [comment]
需要 [这里](https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/dev/resource/template) 的 肉鸽相关的 有字的图片 的繁中版本

**Comment by avw621314** [comment]
了解，我去看看

**Comment by avw621314** [comment]
剛剛更新了一下MAA，結果連肉鴿都開不進去了(會一直跳到主頁)，排查中

**Comment by avw621314** [comment]
請問一下要怎麼上傳圖片，比如我在tw服沒找到 Mizuki@[Roguelike@StartExplore.png](mailto:Roguelike@StartExplore.png) 文件，想要創建一個文件要怎麼做?

**Comment by avw621314** [comment]
能不能用另說，緊急射手先留檔
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140728867/a7d64834-11a7-42ac-92da-c9821b5b0acd)

**Comment by SherkeyXD** [comment]
目前 MAA 对节点类型的识别不依赖文字，而是对关卡图标进行模板匹配，所以现有的资源是可以直接挪用的

**Comment by avw621314** [comment]
看到了，目前補充了部分所需截圖，已經上傳pull等待審核。

**Comment by ms200tswd** [comment]
感謝大佬支持
