### ISSUE TITLE
B服（？）新增同意协议弹窗导致开始唤醒任务出错

### ISSUE THREAD

**Issue by Him392** [MaaAssistantArknights/MaaAssistantArknights#5675]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50799666/a74cac9f-c6f9-40d5-9ba6-5dd67880be85)
如图，20230728闪断更新后，在游戏登录过程中新增同意个人信息相关协议的弹窗，导致无法正确进行任务。

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12185774/debug.zip)

### 截图

![MuMu20230728002150](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50799666/7b6dcf25-40a0-430b-b72d-25f678e64462)
![2023-07-27_18-21-14-814_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50799666/c48c944b-16a2-4817-9511-f399d1f819f4)

### 还有别的吗？

发现MAA截了一堆弹窗的图，乐
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50799666/d8c0a448-c047-4e1e-9456-dae8d93d2857)

**Comment by SherkeyXD** [comment]
不止是b服的问题，今天所有人都有这个弹窗
应该是因为鹰角的隐私协议更新了

**Comment by SherkeyXD** [comment]
该问题也只能手动关闭来解决 —— 毕竟我们不可能帮用户同意隐私协议
