### ISSUE TITLE
锁屏状态之后无法正确进行刷理智的动作

### ISSUE THREAD

**Issue by yanyurua** [MaaAssistantArknights/MaaAssistantArknights#5676]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

进入锁屏（win+L）之后，当执行到刷理智的动作时，会无法继续进行下去，使用的模拟器是mumu12。
在不锁屏的情况下是能够正常运行的。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12186517/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12186518/gui.log)
出现问题的时间在： 7-28   01：56：27至 01：57：14

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64131648/ca0dbdbb-0519-4744-b8b8-c6357d955890)

### 还有别的吗？

使用的mumu12，ver3.5.3
操作系统是 win11
之前好像是没有这个问题的，但是今天更新了模拟器，就出现了这个问题。

**Comment by yanyurua** [comment]
隔天重启以后已经无法复现，也许是电脑出了什么bug吧。

**Comment by ABA2396** [comment]
锁屏是不影响的，电脑降性能的话可能会卡死。不过你这个情况是ocr识别有问题
3dd14b373c1cf45924529d9ea4a68c460c440d51 修了下，不知道有没有用
