### ISSUE TITLE
无法保存adb连接地址

### ISSUE THREAD

**Issue by abbaccadd0** [MaaAssistantArknights/MaaAssistantArknights#568]
## 问题版本
v3.9.0 - beta3

## 问题描述
模拟器无法保存adb连接地址，每次重新打开后都需要再次手动输入地址

## 软件截图
输入连接地址
![Snipaste_2022-05-24_11-45-19](https://user-images.githubusercontent.com/39579855/169944834-b681a1b2-6aab-4795-93dc-7861041a58e7.png)
可以正常连接
![Snipaste_2022-05-24_11-45-30](https://user-images.githubusercontent.com/39579855/169944847-1b4920c0-51ba-4dd5-8b1b-d8b5be5d9c6a.png)
重新打开MAA，可以看到地址已经消失
![Snipaste_2022-05-24_11-45-49](https://user-images.githubusercontent.com/39579855/169944857-7975a9b7-683b-47f8-ae77-982471a8947c.png)

## asst.log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8759406/asst.log)

**Comment by zzyyyl** [comment]
确实，而且改了`连接配置`的话每次打开都会回到默认值。

**Comment by wb871029** [comment]
我也学楼主填FGO BB的adb路径，但是还是一直连接失败。。。

**Comment by zzyyyl** [comment]
> 我也学楼主填FGO BB的adb路径，但是还是一直连接失败。。。

FGO BB是啥？
adb 路径填了连接失败可能是连接配置选的不对

**Comment by wb871029** [comment]
> > 我学也不过填FGO BB的adb路径，还是一直连接失败。。。
> 
> adb 路径填写了连接失败 可能是连接配置选择的错误

就是FGOautomation，里面带了adb，选的也是雷电

**Comment by zzyyyl** [comment]
如果用的是 nox_adb 的话应该是要选夜神的配置（？
还有就是 adb 路径要填到 exe 文件为止

**Comment by zzyyyl** [comment]
> 我也学楼主填FGO BB的adb路径，但是还是一直连接失败。。。

如果还有问题开个新 issue，这个问题不在这个 issue 的讨论范围
