### ISSUE TITLE
增加“活动图时间期限”功能以避免活动结束后刷理智功能错误

### ISSUE THREAD

**Issue by TarringFox** [MaaAssistantArknights/MaaAssistantArknights#5682]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

是这样的，因为现在maa已经拥有足够多能让它挂在那里就可以自动运行的功能了（谢天谢地，定时器真的很好用），所以在活动快结束的也不会再过多的投入精力关注游戏，而如果活动结束时刷理智还选择活动图时，运行到刷理智时就会出错，如果人没注意到的话就会造成理智浪费。因此希望能够增加一个类似于“活动图期限”的设计，到达这个时间设定后自动回退刷理智关卡为提前设置好的其他常驻关卡。

### 有什么好的想法？

例如我们可以提供一个可填写的内容，允许用户设置“本次活动结束的日期”，一般是yyyy-mm-dd之类的格式，具体时分秒可以是该服务器的3:59或者3:55（预留冗余避免临结束活动时仍去刷取活动图）。在时间超过期限后，将“刷理智”功能中刷取的关卡调整为另一个常驻关卡（钱本？1-7？不要恐慌？也许可以由用户进行设置，但这样最好有防呆措施以避免用户将备选关卡调整为活动图）。以此避免活动结束后maa无法找到活动图的入口从而报错。

### 其他内容

关于提到的这个运行错误问题：
没有log，但用现在版本的maa，调整刷理智关卡为DV-X（6，7，8），运行应该会复现。

另外一件事，我注意到maa其实是有“备选关卡”这个设计的，但我本人习惯一般是刷一个图就一直刷，所以从来没有用过。如果“备选关卡”这个功能实际上是可以满足“活动结束后刷取常驻图”的需求的话，我为我莽撞的提出issue表示歉意。（如果能加上“这个功能究竟能干什么”的说明就好了）

**Comment by ABA2396** [comment]
如果你开了隐藏未开放的关卡，活动图结束后会自动变成当前/上次；如果你开了备选关卡，会提示你关卡未开放，然后找下一个开放的关卡，并在下次启动时重置成当前/上次；如果你都没开，就当你偏要打这个，然后就卡住了

**Comment by TarringFox** [comment]
> 如果你开了隐藏未开放的关卡，活动图结束后会自动变成当前/上次；如果你开了备选关卡，会提示你关卡未开放，然后找下一个开放的关卡，并在下次启动时重置成当前/上次；如果你都没开，就当你偏要打这个，然后就卡住了

非常感谢，之后我会再去调整一下设置
