### ISSUE TITLE
Tw服水月肉鴿戰鬥掉落招募券無法辨識/卡住解決方案 (圖片替換)

### ISSUE THREAD

**Issue by avw621314** [MaaAssistantArknights/MaaAssistantArknights#5683]
### 说说你遇到的问题？

**此條為緊急解決方案，圖片替換已申請pull審核中。

方法:

將 resource\global\txwy\resource\template\Mizuki@Roguelike@GetDropRecruit 替換為以下圖片檔案。

![Mizuki@Roguelike@GetDropRecruit](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140728867/6aa07618-7048-4c36-ab63-c6be573da3c2)

重啟MAA。

**Comment by jeff567t** [comment]
很多關卡信息丟失，加回來就正常
