### ISSUE TITLE
OTA发生“资源已损坏”的错误

### ISSUE THREAD

**Issue by Moss-Tony** [MaaAssistantArknights/MaaAssistantArknights#5687]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

由4.19.3软件内OTA至4.20时发生资源损坏的弹窗
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/22862955/85ed8349-7438-47f8-9127-affd66b6f6a2)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12194058/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12194059/gui.log)

**Comment by SherkeyXD** [comment]
疑似增量更新出现问题，尝试重新下载完整包
