### ISSUE TITLE
自动肉鸽时，建议Link Start后可以继续之前的肉鸽进度，而非每次从头开始

### ISSUE THREAD

**Issue by nowing** [MaaAssistantArknights/MaaAssistantArknights#5688]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

当长草时间不足一局肉鸽、或者中途需要暂时中断肉鸽后，再开始Link Start，会自动中断上次的肉鸽进度，从头开始打。

### 有什么好的想法？

可以继续上次的肉鸽进度打下去

**Comment by ABA2396** [comment]
在大地图里开的话会继续，在外面开就从头打
