### ISSUE TITLE
蓝叠模拟器多开时有一个maa无法和其他maa同时连接

### ISSUE THREAD

**Issue by YeZhiShang** [MaaAssistantArknights/MaaAssistantArknights#5689]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

多开时其中一个maa连接对应的多开模拟器会导致其他maa与对应模拟器连接断开，反之亦然
蓝叠5，启用Hyper-V

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12194880/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12194882/gui.log)

### 还有别的吗？

蓝叠5，启用Hyper-V，win11 version 22H2，未修改gui.json（每次手动修改连接地址），连接配置使用通用模式，adb路径均一致

**Comment by SherkeyXD** [comment]
参照 https://maa.plus/docs/用户手册/常见问题.html#指定-bluestacks-config-keyword 为不同的 MAA 设置 `Bluestacks.Config.Keyword`
