### ISSUE TITLE
TW 緊急運輸卡住

### ISSUE THREAD

**Issue by jeff567t** [MaaAssistantArknights/MaaAssistantArknights#5690]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

TW 水月肉鴿每次遇到緊急運輸都會卡住 

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12195079/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12195080/gui.log)

**Comment by yl170512** [comment]
+1
我也遇到一樣的問題
幾乎都會卡在這個介面
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124447739/94a0e793-03dd-4b84-bb1d-d983085905bc)

**Comment by jeff567t** [comment]
漩渦無法識別
