### ISSUE TITLE
最新测试版maa刷完自动关机后,远程开机失败

### ISSUE THREAD

**Issue by Emokable** [MaaAssistantArknights/MaaAssistantArknights#5692]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我在宿舍的台式机上使用maa挂机,设置了主板来电开机并通过远程桌面软件操作
以上正常使用了十几天
但是,最近两天更新的maa自动关机后,均出现了无法开机的现象,昨天晚上我叫留在学校的同学帮我开了机,测试了一下不使用maa的情况下是可以正常远程开关机的.
今天早上也可以用,但是maa又更新了一次,挂在那里我就没管了(因为设置了自动关机),晚上再想连上就又开不了机了
如果能排除硬件问题,也有可能是测试版bug

### 日志文件

暂时开不了机

### 还有别的吗？

使用mumu12模拟器
电脑配置;r5 5600 +3070,主板微星b450m 迫击炮max

**Comment by Emokable** [comment]
叫同学帮忙看了,估计还是硬件问题,从此微星黑

**Comment by WSMTBG** [comment]
> 叫同学帮忙看了,估计还是硬件问题,从此微星黑

618时候19块买的的向日葵开机插座至今在用（）
