### ISSUE TITLE
TW 幹員識別

### ISSUE THREAD

**Issue by jeff567t** [MaaAssistantArknights/MaaAssistantArknights#5697]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

幹員字數超過5個字之後識別率幾乎為0，特別是水陳 百嘉 耀光 濁蒂 歸鯊

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12206326/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12206327/gui.log)

### 截图

![MuMu12-20230729-131656](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59712267/c0b87b32-973d-4621-94e1-5e773c09af61)

**Comment by cenfusheng** [comment]
感谢反馈，已尝试修复，将在后续一到两个版本实装，如仍有问题可继续反馈。

**Comment by ms200tswd** [comment]
> 感谢反馈，已尝试修复，将在后续一到两个版本实装，如仍有问题可继续反馈。

感謝，之前打傀影肉鴿就出現這種問題，嘗試修復也沒辦法
