### ISSUE TITLE
自动公招结束后，执行领取日常奖励出错

### ISSUE THREAD

**Issue by Jonesau** [MaaAssistantArknights/MaaAssistantArknights#5698]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动公招结束后，执行领取日常奖励出错，时间在截图里边

### 日志文件

[copy_last_line.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12206354/copy_last_line.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12206356/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59149009/d5bd62db-818f-4ab5-9193-34ea74c66489)

**Comment by ABA2396** [comment]
不是招募出错吗？招募券还有吗

**Comment by Jonesau** [comment]
> 不是招募出错吗？招募券还有吗

确实，小号挂的时候没招募券了
