### ISSUE TITLE
给“开始唤醒”步骤添加重启游戏客户端的功能

### ISSUE THREAD

**Issue by WallBreakerNO4** [MaaAssistantArknights/MaaAssistantArknights#5699]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

背景：本人长期使用一台不用的旧手机挂着明日方舟客户端，并通过虚拟机里的MAA程序实现半自动日常
我发现有时候会因为游戏客户端卡在奇怪的位置（如肉鸽里），导致MAA做日常时所有任务都失败。
经典例子：挂完肉鸽任务，未退出肉鸽界面导致MAA所有任务都失败

### 有什么好的想法？

给”开始唤醒“任务添加重启游戏客户端的功能

### 其他内容

~~~
adb shell am force-stop com.hypergryph.arknights.bilibili
~~~

**Comment by ABA2396** [comment]
定时任务里的强制执行定时任务就是这个功能，但是在游戏还没开的时候会出错，之后再改改
