### ISSUE TITLE
无法识别

### ISSUE THREAD

**Issue by scyphozoax** [MaaAssistantArknights/MaaAssistantArknights#570]
_log文件以及其他信息我放在了最下面。_
# 问题具体内容：
蓝叠模拟器（CN）打开`ADB`之后，仍然不能识别，。
![1J2KCS(8DJF5%MYP(DEF~@F](https://user-images.githubusercontent.com/50261377/169953177-c7f75903-9e87-4c3b-be9c-4c78b5d48164.png)
![E _RT@YR`F)NE6L@U(SAPVQ](https://user-images.githubusercontent.com/50261377/169953170-7d547e25-4ed5-44b1-8bab-958ceecdd4ac.png)
以上是设置的截图，我已经阅读了`readme.md`，不过还是出现了无法识别的问题
![image](https://user-images.githubusercontent.com/50261377/169953273-9d6dcfa1-61ae-49b9-876d-ed6c207d2cf6.png)
希望作者大大能尽早解决问题，如果是我这里出现了设置上的错误，也烦请能点拨我一下，谢谢！><;;
# Log文件、游戏截图以及模拟器信息
## asst.log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8759654/asst.log)
## 模拟器信息
![image](https://user-images.githubusercontent.com/50261377/169952326-ae12dc9a-758d-4a30-aacb-c9c2e96cc3d4.png)
## 运行时模拟器所在页面的截图（由于ID和UID信息需要保密，所以作打码处理，打码位置没有异常的情况，故作特别说明）
![0QJ6WVDZQ%AVJKY%E{$V0](https://user-images.githubusercontent.com/50261377/169952844-79fc96e5-7f37-4650-9ce7-eb5a7c27e6cf.png)

**解决问题之后记得`Close`！！！**

**Comment by scyphozoax** [comment]
就是说一安装脚本软件之后就没法识别来着。

**Comment by zzyyyl** [comment]
分辨率。

**Comment by zzyyyl** [comment]
> 分辨率。[基本说明](https://github.com/MaaAssistantArknights/MaaAssistantArknights#%E5%9F%BA%E6%9C%AC%E8%AF%B4%E6%98%8E)

对不起我就看到了第一个，后面改了（

**Comment by scyphozoax** [comment]
> 分辨率。[基本说明](https://github.com/MaaAssistantArknights/MaaAssistantArknights#%E5%9F%BA%E6%9C%AC%E8%AF%B4%E6%98%8E)

https://user-images.githubusercontent.com/50261377/169953170-7d547e25-4ed5-44b1-8bab-958ceecdd4ac.png

**Comment by zzyyyl** [comment]
换模拟器之后重启maa了没？

**Comment by scyphozoax** [comment]
> 换模拟器之后重启maa了没？

看起来是我没重启的问题，抱歉><;;
