### ISSUE TITLE
刷取肉鸽职业队直升

### ISSUE THREAD

**Issue by Narcissus1st** [MaaAssistantArknights/MaaAssistantArknights#5705]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

肉鸽职业队直升需要凹，且中间有cd

### 有什么好的想法？

重复选取职业队和开局配置，再识别有无需要的直升，有则该任务完结，没有就重开继续

**Comment by SherkeyXD** [comment]
Duplicate of #5539
