### ISSUE TITLE
增加对模拟器的简单控制（如音量调节）

### ISSUE THREAD

**Issue by ImYiFeng** [MaaAssistantArknights/MaaAssistantArknights#5711]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用MAA在模拟器上刷东西时，想要关闭模拟器声音，但一打开模拟器的音量调节选项，就会被MAA的操作覆盖

### 有什么好的想法？

在MAA主界面加入对模拟器的简单控制功能（目前我个人最需要的就是音量调节），通过ADB指令对模拟器进行控制

**Comment by SherkeyXD** [comment]
大部分模拟器都提供了独立于安卓系统外的音量调节按钮
如蓝叠：
<img width="798" alt="23ea075dd33f69e6dcff04203bf3a8b7" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57581480/646361cc-dbdb-4489-b8f0-c0fd2e24430b">
如果你的模拟器没有这一功能，你也可以在启动 MAA 之前关闭音量，或是在 Windows 音量合成器中关闭模拟器的音量
