### ISSUE TITLE
MAA信用商店自动购买物品时增加优先购买加急许可功能

### ISSUE THREAD

**Issue by LemonTeeeea** [MaaAssistantArknights/MaaAssistantArknights#5713]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

MAA在信用商店自动购买物品功能中加急许可是在自动购买黑名单中的 希望能增加自动购买加急许可的功能

**Comment by KawausoJyou** [comment]
自己修改一下不就行了？

**Comment by tangge233** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50769997/49a15a08-c7cd-433c-a7eb-6e1de46b4fa6)
