### ISSUE TITLE
刷1-7的时，掉落统计出现的furni是啥

### ISSUE THREAD

**Issue by wanqian-windrunner** [MaaAssistantArknights/MaaAssistantArknights#5714]
### 说说你遇到的问题？

<img width="183" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119412909/a0dcb6a7-e62b-47a7-9888-eaffa2d664df">

**Comment by ABA2396** [comment]
家具

**Comment by JueHua131C** [comment]
furniture的缩写
