### ISSUE TITLE
无法进入萨米肉鸽

### ISSUE THREAD

**Issue by Sigel2080** [MaaAssistantArknights/MaaAssistantArknights#5715]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启动MAA后，MAA不进入肉鸽界面，直接点进干员界面选取塞雷亚或者泥岩看技能。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12208631/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12208632/gui.log)

**Comment by SherkeyXD** [comment]
疑似增量更新错误，在 MAA 尝试更新的时候直接直接退出进程可能引发此问题
重新下一个完整包试试
