### ISSUE TITLE
令的召唤物弦惊识别错误

### ISSUE THREAD

**Issue by ala-404** [MaaAssistantArknights/MaaAssistantArknights#5716]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗中令的召唤物弦惊被识别为清平

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12208636/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12208637/gui.log)

时间在[2023-07-30 14:46:29.318]之后

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139619533/4c277546-4b38-4147-9fa6-fdc9dea95d82)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139619533/ebc7cf42-52eb-45c6-be85-4b1e2a8fe419)

**Comment by SherkeyXD** [comment]
尝试删除 cache/avatars 文件夹，让 MAA 重新生成一遍干员/召唤物头像看看能不能行
