### ISSUE TITLE
建议：允许挂机火蓝之心OF-1等无奖励关卡

### ISSUE THREAD

**Issue by HanareTen** [MaaAssistantArknights/MaaAssistantArknights#5718]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

部分玩家会在火蓝之心的关卡中完成模组任务，而MAA会因为该关卡无掉落而停止任务
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61415058/0019ac26-68b2-407d-9332-57e937e7c75c)

### 有什么好的想法？

建议允许“刷理智”功能打无奖励关卡

**Comment by ABA2396** [comment]
然后就会因为无奖励又无消耗，刷理智任务刷这关就出不去了

**Comment by HanareTen** [comment]
> 然后就会因为无奖励又无消耗，刷理智任务刷这关就出不去了

可以设定次数吧，重复个五六次也可以啊

**Comment by ABA2396** [comment]
原来是支持的，但就是很多人会因为刷信赖或者模组上次关卡变成了OF-1，关卡选择选的又是 当前/上次，导致刷理智任务卡住，所以才改成了无奖励关卡直接停止。刷模组这种要打的次数不多，还是手动完成一下吧

**Comment by SherkeyXD** [comment]
我怎么记得好久之前有人提过这个）

**Comment by status102** [comment]
如果需要刷任务，可以考虑使用自动战斗执行一个没有步骤的作业
