### ISSUE TITLE
请让B服可以正常使用定时执行

### ISSUE THREAD

**Issue by bxyyyyy** [MaaAssistantArknights/MaaAssistantArknights#5720]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

虽然定时执行功能能很好的解放双手。但在凌晨4点时游戏服务器重启后，到了早上我发现maa卡在一个界面。在这个界面卡死的事经常发生，我不得不为了挂肉鸽在凌晨四点左右使用闹钟醒来手动操作，这令人非常失望。这是一个会必然发生的错误，定时执行完全失去了效果。

### 有什么好的想法？

添加B服弹窗识别识别

### 其他内容

![Cache_-2f54e17b766a9cdd](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140943481/759f54d7-b03f-49d0-afb0-3e516bf85ca1)

**Comment by ABA2396** [comment]
B服一直是可以正常使用定时执行的。帮用户点隐私策略这种事情是不肯能做的。正常来说隐私策略在确认并没有更新的情况下是不会弹的。
