### ISSUE TITLE
开机启动MAA失效

### ISSUE THREAD

**Issue by SwallowInRain** [MaaAssistantArknights/MaaAssistantArknights#5721]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

版本更新为v4.20.0后，开机启动MAA失效，不确定是否是bug

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12208799/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12208800/gui.log)
最后一次开启电脑自动启动MAA失败，手动启动MAA的大致时间点为2023.7.30 16：48-16：50

### 还有别的吗？

操作系统是Win10

**Comment by SherkeyXD** [comment]
检查一下 `设置 > 应用 > 启动` 中是否允许了 MAA 启动

**Comment by SwallowInRain** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115250895/d8eca606-fdec-465f-944c-1a008737b1f5)
应该是打开了的 您说的开机时间指什么？

**Comment by SherkeyXD** [comment]
> 您说的开机时间指什么？
就是你电脑的启动时间 这样我们可以分析maa进程是否正常启动
以及不用叫您，太怪了（

**Comment by SwallowInRain** [comment]
启动的时间 应该就是2023.7.30 16：45分左右吧，我重启就是为了看MAA是否启动，最开始说的手动开启的时间是MAA上面显示出来的，但是没有截图了，17点自动工作就刷掉了手动启动的时间记录

**Comment by SherkeyXD** [comment]
MAA 的日志记录从16:38 直接跳到了 16:49，说明出于某些未知 MAA 进程确实没有开机启动
我去问问

**Comment by SherkeyXD** [comment]
这个问题能稳定复现吗

**Comment by SwallowInRain** [comment]
应该是可以的 因为我重复了很多次都无法开机启动

**Comment by wufenghuonb** [comment]
我也尝试了反复重新启动，发现与楼主的问题一模一样，其他功能完好，唯独在开机时不会自启动，我怀疑这是一个普遍的问题

**Comment by 000191750** [comment]
我知道问题的原因了，不要在属性里勾选管理员启动，因为Win10开机自启他不会弹窗确认用户账户控制，就无法启动了

**Comment by ABA2396** [comment]
测试班改了一下，改成了注册表启动，现在的正式版只能启动非管理员权限的。

**Comment by SwallowInRain** [comment]
感谢大佬拯救我的MAA~
