### ISSUE TITLE
【IOS】Mac playcover 肉鸽无法自动购买藏品

### ISSUE THREAD

**Issue by maodaoOvo** [MaaAssistantArknights/MaaAssistantArknights#5722]
### 说说你遇到的问题？

Mac playcover 肉鸽均无法自动购买藏品

**Comment by SherkeyXD** [comment]
请上传日志，否则我们无法分析问题所在

**Comment by maodaoOvo** [comment]
@SherkeyXD 我应该上传哪部分的日志 且如何在mac端查看（。

**Comment by maodaoOvo** [comment]
> 
我应该上传哪部分的日志 且如何在mac端查看（。

**Comment by maodaoOvo** [comment]
> 请上传日志，否则我们无法分析问题所在

@SherkeyXD 我应该上传哪部分的日志 且如何在mac端查看（。

**Comment by maodaoOvo** [comment]
> 请上传日志，否则我们无法分析问题所在

@SherkeyXD 
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12208857/asst.log)

**Comment by SherkeyXD** [comment]
> [ERR][Px10a52][Txbf3c] Cannot get screencap: invalid image size

尝试在 PlayCover 内将分辨率设置为 1080P

**Comment by maodaoOvo** [comment]
> > [ERR][Px10a52][Txbf3c] Cannot get screencap: invalid image size
> 
> 尝试在 PlayCover 内将分辨率设置为 1080P

使用的分辨率是1080p

**Comment by maodaoOvo** [comment]
<img width="511" alt="截屏2023-07-30 17 50 24" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140944955/4c33b8bb-f1d1-4a1d-9684-16fa26b3a1ca">


> > [ERR][Px10a52][Txbf3c] Cannot get screencap: invalid image size
> 
> 尝试在 PlayCover 内将分辨率设置为 1080P

**Comment by SherkeyXD** [comment]
这得问 mac 那边的开发者了 
我不大熟（

**Comment by maodaoOvo** [comment]
> 这得问 mac 那边的开发者了 我不大熟（

这个怎么问（。

**Comment by maodaoOvo** [comment]
> 这得问 mac 那边的开发者了 我不大熟（

救一下，佬（（

**Comment by maodaoOvo** [comment]
> 

@SherkeyXD 可以帮助联系一下吗
