### ISSUE TITLE
程序崩溃问题

### ISSUE THREAD

**Issue by xxloger** [MaaAssistantArknights/MaaAssistantArknights#5728]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

强制替换adb时，maa主程序崩溃

以下是报错信息：
MAA 遇到了问题
对路径“adb.exe”的访问被拒绝。
解决方案
出现未知错误
详细信息
System.UnauthorizedAccessException: 对路径“adb.exe”的访问被拒绝。
   在 System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   在 System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ReplaceADB>d__462.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12209463/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12209464/gui.log)

### 截图

<img width="448" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104882702/4a44169c-cb31-4fc3-895d-a9c2c73102e3">

### 还有别的吗？

mumu12模拟器
win11
<img width="577" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104882702/9c600335-1d44-4333-a38b-cec2cd36b9ad">

**Comment by ABA2396** [comment]
mumu的程序都是管理员权限的，要用管理员权限启动maa，然后替换的时候把模拟器和adb关了（或者可以重启电脑后直接替换）

**Comment by xxloger** [comment]
好的。感谢回复

**Comment by xxloger** [comment]
> 

好的，感谢回复

**Comment by xxloger** [comment]
> mumu的程序都是管理员权限的，要用管理员权限启动maa，然后替换的时候把模拟器和adb关了（或者可以重启电脑后直接替换）
好的，感谢回复
