### ISSUE TITLE
在基建换班时任务出错，完成了几个但直接到了设置界面，如截图所示。

### ISSUE THREAD

**Issue by rnzfgm** [MaaAssistantArknights/MaaAssistantArknights#573]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8761955/asst.log)

截图：
![image](https://user-images.githubusercontent.com/73269504/170017850-c9f69002-064c-4aba-86f6-60cb0100a477.png)
使用的雷电模拟器。

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/579

应该是同一个问题，困惑的点在于，在基建里操作的时候，确定 MAA 没有点击返回按钮，但在某个时候突然跑到主界面去了。暂时没搞清楚啥原因，弹公告之类的会有这种情况么？

**Comment by rnzfgm** [comment]
公告之类的没有过，这个十天来我也没再遇到过了，感觉可以不修，不影响（

**Comment by MistEO** [comment]
~~这么说了我就不跟你客气了~~
