### ISSUE TITLE
【肉鸽】 检测是否放弃成功的建议 与 存款效率模式的几条优化建议

### ISSUE THREAD

**Issue by YueZheng-Sea-angle** [MaaAssistantArknights/MaaAssistantArknights#5730]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

1.设置的策略：存钱，到达第二层就退出。
2.遇到的问题：
①maa在第二层尝试放弃探索三次后就会认为放弃成功，如果因为网络或其他原因导致并未放弃探索，maa无法检测到这一点。然后就会试图开始下一次新的探索（其实并未开始新的探索），并继续打第二、三层，直到通关或联系中断。
②maa在萨米肉鸽中存款时，主要耽误的时间在于招募新干员，通常maa会彻底检索整个干员列表，然后进行招募，还有一定概率放弃招募。但在到达第二层就退出的策略下，仅靠初始招募的3个干员就可以通过第一层，因此这样的招募干员可能是没有必要的，可以考虑直接拒绝招募，进一步提升存款效率。以及，文化比较/认知塑造刷满后，对于关卡得分也没有要求，因此战后藏品、各类物品的掉落以及干员的招募都不能给存款带来帮助，可以考虑进一步增加优化策略。
![QQ图片20230731023337](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62352027/24a2becc-f876-44b1-9eeb-bfecd8e99258)

### 有什么好的想法？

[层数检测]
1.对关卡名称/层数偶尔进行一次检测,当遇见非一层的信息时,直接放弃探索

[存款效率优化](均考虑文化比较已经点满的背景,且执行仅存款,到达第二层直接退出的策略)
2.仅招募初始干员,后续不再进行干员招募,这是最大头的时间优化
3.避免拾起关卡其他掉落物
4.在遇见不期而遇中的战斗节点时,选择避战选项(目前的策略选择的是迎战选项)
5.检测到第一层出现必经的三次作战时,考虑直接重开(这个难度可能有点高,毕竟萨米添加了很多上下节点)

**Comment by Lancarus** [comment]
#6140
