### ISSUE TITLE
ADB重启失败后自动重启模拟器功能失效

### ISSUE THREAD

**Issue by MuLInGRui** [MaaAssistantArknights/MaaAssistantArknights#5732]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

内测更新前正常，自动更新后发生ADB连接失败后不能重启模拟器的情况，
即连接模拟器失败后，不能重启模拟器，该设置选项失效

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12210729/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12210730/gui.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12210732/asst.bak.log)
今天早上9点

### 截图

![屏幕截图(1)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114294439/b8f30f9f-7370-435e-87a4-649a76cb5f8d)

**Comment by MuLInGRui** [comment]
然后手动打开模拟器之后运行正常

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7b0f0b51-6b3d-4093-9424-34f8633a46fd)
如果勾了这个应该会有提示“正在尝试启动模拟器”，看看这个设置有没有打开

**Comment by MuLInGRui** [comment]
就是因为勾选了这个我才确定这个功能失效了

**Comment by CircleRuler** [comment]
我今天也遇到了这样的问题，完全一样的现象，在昨天更新完就出现了

**Comment by qin-xi** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56617250/1ec37855-9c2c-488f-bd42-f252b2f1bc00)
在昨天更新之后，我也出现了这个问题，重启电脑也无法解决

**Comment by ABA2396** [comment]
> ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56617250/1ec37855-9c2c-488f-bd42-f252b2f1bc00)
> 在昨天更新之后，我也出现了这个问题，重启电脑也无法解决

你这都没打开模拟器的动作

**Comment by qin-xi** [comment]
> > ![image](https://user-images.githubusercontent.com/56617250/271743345-1ec37855-9c2c-488f-bd42-f252b2f1bc00.png)
> > 在昨天更新之后，我也出现了这个问题，重启电脑也无法解决
> 
> 你这都没打开模拟器的动作
我的MMA每次模拟器都需要手动打开才能链接之前，但是更新之后就出现这个无法连接adb问题了
