### ISSUE TITLE
添加关卡选择

### ISSUE THREAD

**Issue by qw1642190428** [MaaAssistantArknights/MaaAssistantArknights#5733]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

是不是应该把孤星第六关添加到关卡选择里面了 毕竟那一关是现在的搓玉最优的关卡

**Comment by ABA2396** [comment]
https://www.bilibili.com/read/cv25348503
