### ISSUE TITLE
开局没有热水壶/希望+2时，选择希望-1，导致希望不足无法选择对应助战而卡死

### ISSUE THREAD

**Issue by Mushroom-YM** [MaaAssistantArknights/MaaAssistantArknights#5734]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

官服
模拟器：mumu12
自动肉鸽设置：水月肉鸽，刷等级，指挥分队，存储源石锭，近卫券棘刺开局，选择助战
已经出现过两次，都是挂在后台因此没有看到具体过程，试图复现第三次但至今没出现。
我看到的时候maa在不停刷新助战，根据maa内记录看这局已经开始一小时了，一直都卡在这里开不了局。观察发现是希望只有5导致借不到六星，只能一直刷新助战，推测是开局选了希望-1导致的。
能否修改开局buff选择优先级，改为不选择希望-1这条buff？虽然后勤/职业队开也可以解决这个希望不足的问题，但这两个分队单局得分远远不如指挥分队，效率比较低，还是希望能用指挥分队刷。

### 日志文件

因为上次产生类似情况时以为是偶然事件没记录时间点，现在两三天过去也没复现成功，所以无法上传日志文件

**Comment by SherkeyXD** [comment]
Duplicate of #5413
