### ISSUE TITLE
日服肉鸽相关问题

### ISSUE THREAD

**Issue by qwer753159456** [MaaAssistantArknights/MaaAssistantArknights#5737]
### 说说你遇到的问题？

您好 想请问后续还会对日服的水月肉鸽及未来的萨米肉鸽进行相关适配吗?

**Comment by Constrat** [comment]
Mizuki I.S. has already been adapted for the Global YostarJP server.
Sami I.S. will probably get adapted in the future, around the time it releases (Roguelikes take a lot more time to adapt because they are much more complex gamemodes)
