### ISSUE TITLE
夜神模拟器连接异常

### ISSUE THREAD

**Issue by MyRai1gun** [MaaAssistantArknights/MaaAssistantArknights#5738]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

夜神模拟器连接失败，重启、更新maa、安装ADB都没有解决

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12211935/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12211936/gui.log)
2023.7.31 14:00

### 截图

![QQ图片20230731140603](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/100457435/a1ea9053-83ae-4f43-923d-624677fe7ec8)

### 还有别的吗？

夜神模拟器
win10

**Comment by chnhi** [comment]
设置不对。[请对照常见问题自行修改设置](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E6%96%B9%E5%BC%8F-1-%E7%A1%AE%E8%AE%A4-adb-%E5%8F%8A%E8%BF%9E%E6%8E%A5%E5%9C%B0%E5%9D%80%E6%AD%A3%E7%A1%AE) ，正确设置还是异常，模拟器关机，管理员运行maa强制替换adb。不行就换成mumu12模拟器，删掉旧的maa，重新下载完整版maa。

**Comment by Shawnsdaddy** [comment]
出现相同问题，已经换 了mumu12运行良好
