### ISSUE TITLE
maa异常退出

### ISSUE THREAD

**Issue by Emokable** [MaaAssistantArknights/MaaAssistantArknights#5739]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 遇到了问题
拒绝访问。
解决方案
出现未知错误
详细信息
System.ComponentModel.Win32Exception (0x80004005): 拒绝访问。
   在 System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   在 System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   在 System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   在 System.Diagnostics.Process.get_MainModule()
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.KillEmulatorLDPlayer()
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.KillEmulatorModeSwitcher()
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.CheckAfterCompleted()
   在 MaaWpfGui.Main.AsstProxy.ProcTaskChainMsg(AsstMsg msg, JObject details)
   在 MaaWpfGui.Main.AsstProxy.ProcMsg(AsstMsg msg, JObject details)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12212967/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12212968/gui.log)

### 截图

![2023-07-31_16-05-42-768_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/93334525/f94d16cf-a402-4a51-a787-8177e1f5ae13)

### 还有别的吗？

操作系统：Microsoft Windows 11 64位  23H2
CPU型号：AMD Ryzen 7 5700U with Radeon Graphics         
主板：LENOVO_LNVNB161216
总内存：13.9 GB
可用内存：5.5 GB
显卡型号：AMD Radeon(TM) Graphics (20210714)
OpenGL：4.6.14822 Compatibility Profile Context 20.50.26.08 27.20.15026.8004
IE版本：11.0
模拟器版本：4.0.81(32)
模拟器路径：C:\LeiDian\LDPlayer4.0
日志路径：C:\Users\xx\AppData\Roaming\leidian\log
vt:开启
运行参数：CPU(3核) 内存：(4096M) 正在运行(1) 高速(1)
分辨率：1440x810 dpi 240 fps 60
总大小16 G，剩余12 G

**Comment by ABA2396** [comment]
你的雷电是用管理员权限打开的，如果maa不是管理员权限开启的话是无权关闭模拟器的
