### ISSUE TITLE
肉鸽有概率在模拟器断开连接后向硬盘中写入大量图片

### ISSUE THREAD

**Issue by horror-proton** [MaaAssistantArknights/MaaAssistantArknights#5740]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打肉鸽的时候模拟器断意外开连接了, 导致任务错误后回落到 `Roguelike@ExitThenAbandon` 并反复执行, 向 debug 文件夹中写入了大量一模一样的截图

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12213058/asst.log)

### 截图

模拟器断开后所有截图都是这一张

![2023-07-31_01-33-04-684_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/107091537/7f2a774e-6a16-48db-b572-133b16c3142b)

**Comment by horror-proton** [comment]
可能造成 #4953 的情况
相关 pr #5325

**Comment by ABA2396** [comment]
这不是因为开了指针然后识别不到左上角的返回按钮了吗？

**Comment by horror-proton** [comment]
> 这不是因为开了指针然后识别不到左上角的返回按钮了吗？

不是吧, 它是可以识别到的
```
match_templ | Roguelike@ExitThenAbandon.png score: 0.846327 rect: [ 178, 9, 48, 49 ] roi: [ 0, 0, 320, 160 ]
```

**Comment by MistEO** [comment]
> 可能造成 #4953 的情况 相关 pr #5325

现在的图应该是在 controller 里有个 cache，要不连接断开之后就把 cache 清掉？
