### ISSUE TITLE
MAA能不能推出肉鸽烧水的功能

### ISSUE THREAD

**Issue by YuXingRen** [MaaAssistantArknights/MaaAssistantArknights#5741]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

刷到第三层就退出肉鸽，然后弹窗烧水完成。现在每次用MAA烧水还得盯着MAA打到哪里了

**Comment by arvyanh** [comment]
顺便可以低难刷初始， 然后切到高难看初始/直升，如果高难maa3层不稳定的话？ （也不知道这样会不会写起来很麻烦）
