### ISSUE TITLE
刷理智关卡错误

### ISSUE THREAD

**Issue by haohanyuzmx** [MaaAssistantArknights/MaaAssistantArknights#5742]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

7.31-9点的时候手动指定关卡为1-7，电脑没关，没有操作maa，在7.31-18点的时候，刷理智的关卡变为了of-1，导致刷理智失败

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12214732/asst.zip)

**Comment by ABA2396** [comment]
@moomiji 来瞅瞅）
```
[2023-07-31 18:00:11.297][INF][Px8294][Tx71b4] asst::Assistant::append_task Fight {"stage":null,"medicine":999,"stone":0,"times":2147483647,"report_to_penguin":true,"client_type":"Official","penguin_id":"030588225","DrGrandet":false,"expiring_medicine":0,"server":"CN"}
```
关卡选择又变成null了

**Comment by jeff567t** [comment]
搞定了，OTA不給力

**Comment by Constrat** [comment]
@haohanyuzmx a patch was made for this. Have you noticed any differences?
(Close the issues if it did)

**Comment by haohanyuzmx** [comment]
not sure, i think can close it now, and if i reproduce it, i will open a new issue
