### ISSUE TITLE
Fail MaaCore.dll

### ISSUE THREAD

**Issue by eskana77** [MaaAssistantArknights/MaaAssistantArknights#5743]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

I tried to run mma using Latte Panda, but MaaCore.dll could not be loaded

### Log files

MAA에서 오류가 발생했습니다
'MaaWpfGui.ViewModels.UI.SettingsViewModel'의 형식 이니셜라이저에서 예외를 Throw했습니다.
DLL 'MaaCore.dll'을(를) 로드할 수 없습니다. 지정된 모듈을 찾을 수 없습니다. (예외가 발생한 HRESULT: 0x8007007E)
해결 방법
FAQ 문서의 크래시 관련 문단을 참고하세요.
세부 정보
System.TypeInitializationException: 'MaaWpfGui.ViewModels.UI.SettingsViewModel'의 형식 이니셜라이저에서 예외를 Throw했습니다. ---> System.DllNotFoundException: DLL 'MaaCore.dll'을(를) 로드할 수 없습니다. 지정된 모듈을 찾을 수 없습니다. (예외가 발생한 HRESULT: 0x8007007E)
   위치: MaaWpfGui.ViewModels.UI.SettingsViewModel.AsstGetVersion()
   위치: MaaWpfGui.ViewModels.UI.SettingsViewModel..cctor()
   --- 내부 예외 스택 추적의 끝 ---
   위치: MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   위치: lambda_method(Closure , IRegistrationContext )
   위치: StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   위치: StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   위치: StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   위치: StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   위치: StyletIoC.Internal.Container.Get[T](String key)
   위치: MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   위치: Stylet.BootstrapperBase.Start(String[] args)
   위치: System.Windows.Application.OnStartup(StartupEventArgs e)
   위치: System.Windows.Application.<.ctor>b__1_0(Object unused)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by arvyanh** [comment]
Looks like a dll not found exception.
Probably some dependency isn't on the Latte Panda's windows, so try dependency walker?

**Comment by ABA2396** [comment]
Is Latte Panda an x86 system? If so, it won't work. maa is x64 software.

**Comment by ABA2396** [comment]
For x64, please refer to [자주 묻는 질문](https://maa.plus/docs/ko-kr/1.2-FAQ.html), but for Korean, since not many people in the project team know Korean, the documentation will be a bit outdated, so you can read the English documentation if you are able to [Frequently Asked Questions](https://maa.plus/docs/en-us/1.2-FAQ.html)
