### ISSUE TITLE
繁中服的水月肉鴿bug

### ISSUE THREAD

**Issue by sadeer2014** [MaaAssistantArknights/MaaAssistantArknights#5746]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在不期而遇的緊急運輸節點，如果maa選擇讓幹員離開的選項，maa並不會選擇任何幹員並且會僵在系統提醒未選擇幹員的頁面，需要手動關掉才會繼續行動，選擇+3希望則不會有任何問題。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12222351/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12222353/asst.log)

04:54:22開始
05:02:13則是我開始手動關掉

**Comment by jeff567t** [comment]
居然是這種問題...，那這樣子的話我在國際服跟日服都沒有看到，TW再把魁影肉鴿的也加上應該就沒問題了，等更新
