### ISSUE TITLE
由4.20.0到4.21.0-beta.1的自动OTA更新无法进行

### ISSUE THREAD

**Issue by SteveXu9102** [MaaAssistantArknights/MaaAssistantArknights#5759]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Bug如标题，在设置内尝试进行更新时无法下载OTA包，提示“请检查网络连接或代理”，但对gui.log中的部分镜像源尝试直接在浏览器（Chrome）访问时可在浏览器内正常下载。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12229551/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12229554/asst.log)

### 截图

![QQ图片20230801211431](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/68725147/3ff286b9-a0e3-481d-99a9-53f69dd70630)
（此图为游戏讨论群内出现相同问题的人的截图。对应操作系统：Windows 10 x64）

### 还有别的吗？

模拟器：MuMu模拟器12
操作系统：Windows 11 x64 23H2
未开启http代理
网络环境可正常访问github

**Comment by 1oneZhi** [comment]
遇到相同问题

**Comment by ABA2396** [comment]
测速有问题，不更新解决不了，但不解决就不能自动更新.jpg
这次得手动下载安装包了

**Comment by ms200tswd** [comment]
遇到一样问题，重新下了整个安装包OK了

**Comment by Tastror** [comment]
可以下载 OTA，放入 MAA 所在文件夹打开 MAA 后自动解压。  
[链接](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v4.21.0-beta.1)  
正常情况下公测版 OTA 包如图，如果你是别的版本就下别的 OTA  
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74226084/2ead7f46-2bb5-40ad-8806-7a5e5b5c43c7)

**Comment by Versirity** [comment]
一样的问题，我还以为我网络炸了

**Comment by SacribethGrass** [comment]
same problem

**Comment by SteveXu9102** [comment]
已通过手动下载OTA包解决问题。感谢！

**Comment by Aowae** [comment]
夜神模拟器也一样，不过重新下了就好了
