### ISSUE TITLE
v3.3.2版本肉鸽没有二倍速

### ISSUE THREAD

**Issue by Thtuy** [MaaAssistantArknights/MaaAssistantArknights#576]
日志文件太大了所以整了压缩包
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8768499/asst.zip)
软件界面一直很正常但每次窥屏的时候都只有一倍速，用的夜神模拟器
![image](https://user-images.githubusercontent.com/34420092/170195825-ea237deb-ee5c-4b98-bb10-1bd6f208c122.png)

**Comment by aishan224** [comment]
3.9.0-Beta4 + mumu模拟器同样只有一倍速

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8770528/asst.-.log)
