### ISSUE TITLE
TW 刷錢關錯誤

### ISSUE THREAD

**Issue by jeff567t** [MaaAssistantArknights/MaaAssistantArknights#5760]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

手動指定關卡CE-6

8/1 21:24:10 開始任務
8/1 21:25:25 失敗

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12229654/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12229685/gui.log)

### 截图

![MuMu12-20230801-212721](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59712267/4cd62adf-5c45-4433-adb8-7b017182bc30)

**Comment by ms200tswd** [comment]
你更新或者重新下最新版本beta1試試看，我這邊可以刷錢的
![Screenshot 2023-08-01 112111](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43395375/01899dd7-24d2-4b73-9c76-4f82e12add8c)

**Comment by jeff567t** [comment]
搞定了，OTA不給力
