### ISSUE TITLE
mumu模拟器12新出的后台保活使MAA无法正常运行

### ISSUE THREAD

**Issue by xiaowu-PRC** [MaaAssistantArknights/MaaAssistantArknights#5767]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96490847/c0b4e2d6-d18a-4ab1-8079-d67c56ec2a36)
当开启此选项后，即使明日方舟在前台也无法正确识别。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96490847/c96f0abe-019a-43a6-9297-d07db0cbfd97)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12233071/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12233073/gui.log)
大概时间点是02:47左右

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96490847/dcd11bb1-9a82-49d8-8987-ef0539d1b7f1)

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96490847/cb6c46d5-4b14-4394-9269-dcde8cae4144)

**Comment by SherkeyXD** [comment]
启用该功能会导致 adb 截到的图是 mumu 的主页，自然无法识别
是时候改文档了）
以及问一下这东西是默认启用的吗

**Comment by xiaowu-PRC** [comment]
> 

非默认启用，只是我看到了想试一下结果发现了这个问题。

**Comment by alonefaquir** [comment]
mumu官方文档中已经说明，试用后台保活功能会导致使用截图功能的脚本失效，请不要开启该选项。[mumu官方文档](https://mumu.163.com/help/20230802/35047_1102450.html)

**Comment by 957176113** [comment]
> > 
> 
> 非默认启用，只是我看到了想试一下结果发现了这个问题。

怎么不按现在我取消了这个功能 MAA无法控制模拟器了 一直任务出错

**Comment by yc080713** [comment]
mumu在3.5.8版本修复了这个问题

![{E98DD734-192D-18A1-6307-D2DE527C7CB6}](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92996760/44c144bd-7d0b-44fc-b832-9741d7a1a943)
