### ISSUE TITLE
傀影肉鸽中选到 红 在选技能时会点进去从而无法开始战斗

### ISSUE THREAD

**Issue by ybh11767** [MaaAssistantArknights/MaaAssistantArknights#5768]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![b23adc348a76b234104e5226740dcc18](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55701188/2500d922-6777-4720-9b47-525d7a0dbb99)
以多次测试确认为红的问题
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55701188/9891040f-fe50-4b22-a72e-7aaca37a7419)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55701188/b7d0224e-59c4-429f-9821-9d220eb2710a)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55701188/61e612b3-123c-47f6-9cb7-363350f66714)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12233527/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12233529/gui.log)

### 还有别的吗？

win11蓝叠模拟器

**Comment by nowing** [comment]
我也发现这个问题，傀影肉鸽里无法“开始行动”，队伍里有 红。

**Comment by ybh11767** [comment]
> 我也发现这个问题，傀影肉鸽里无法"开始行动"，队伍里有 红。

使用4.20.0可以正常"开始行动"，应该是新增的bug

**Comment by Lancarus** [comment]
不小心把红设置成3技能了

**Comment by Lancarus** [comment]
recruitment.json里3000多行左右
![Screenshot_2023-08-03-11-31-26-71_22d2f3c2df26fdc9c879008859bd486f](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/17cfa8c6-428a-4a24-962f-5dcc2ca28ffd)
把这个skill的3改成1或者2

**Comment by cenfusheng** [comment]
已修复，将在后续版本实装。
