### ISSUE TITLE
MacOS Beta (14.0 beta 1-4) AVD和Playcover连不上

### ISSUE THREAD

**Issue by haoruizhou** [MaaAssistantArknights/MaaAssistantArknights#5770]
### 说说你遇到的问题？

没有在13.0版本在mac上用过MAA，不知道大家有beta版测试成功的案例吗？目前显示运行中但是不会进行任何操作。
谢谢！

![20230802103149eYh2zJ](https://raw.githubusercontent.com/haoruizhou/image_host/main/uPic/20230802103149eYh2zJ.png)
![202308021032183SezzM](https://raw.githubusercontent.com/haoruizhou/image_host/main/uPic/202308021032183SezzM.png)

**Comment by MistEO** [comment]
请提 bug 反馈
