### ISSUE TITLE
萨米肉鸽自动结束探索失败

### ISSUE THREAD

**Issue by shiramineS** [MaaAssistantArknights/MaaAssistantArknights#5771]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选择策略刷投资第二层直接退出，但maa未正常退出结束探索，并在之后继续打到了3层boss。
发现时已经开始boss关。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12235450/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12235452/gui.log)

### 截图

![capture_20230802102603021](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/127011696/9bb03ca2-dadf-47f5-9d8d-a33cd3da22c8)

### 还有别的吗？

mumu12 模拟华为mate50BNE-AL00

**Comment by SherkeyXD** [comment]
你是不是在启动自动肉鸽任务后才改的策略

**Comment by shiramineS** [comment]
> 你是不是在启动自动肉鸽任务后才改的策略

不，一直用的这个，bug也只触发了这一次

**Comment by SherkeyXD** [comment]
能稳定复现吗

**Comment by shiramineS** [comment]
只出现过一次，复现不了
