### ISSUE TITLE
萨米肉鸽辅助招募逻辑

### ISSUE THREAD

**Issue by thefox1107** [MaaAssistantArknights/MaaAssistantArknights#5774]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在萨米肉鸽内不知为啥辅助招募券在可以招募梓兰的情况下优先招募临时干员-术师

### 日志文件

[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12235786/asst.bak.zip)
时间大概是在：2023-08-01 11:56:01.339

**Comment by SherkeyXD** [comment]
你的梓兰是精一55级吗
