### ISSUE TITLE
刷理智任务任务出错

### ISSUE THREAD

**Issue by DerectN1** [MaaAssistantArknights/MaaAssistantArknights#5777]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

模拟器为MuMu模拟器12，执行开始唤醒任务后可以正常开启明日方舟，但后续没有任何操作，一段时间后提示“任务出错: StartUp”，手动登录游戏后执行刷理智任务，无任何操作，然后报错“任务出错: Fight”
已多次尝试重启MAA和模拟器；以管理员身份运行MAA；强制替换ADB；重启电脑，均无效果
大致时间20230802 14:30左右

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12237018/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12237020/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141213700/48111cbc-632d-4bfb-b6b5-997388497cb2)

**Comment by ABA2396** [comment]
能开游戏但是不能操作基本就是adb问题了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/625f1a9d-6269-470d-8a50-7a684b841ece)
日志里看你的替换并没有成功，建议在关闭模拟器和adb的情况下替换，或重启后未开启模拟器的时候替换

**Comment by DerectN1** [comment]
今天重试替换ADB成功了，但任务依旧失败，启动明日方舟后无反应，刷理智任务报错

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12245718/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12245719/gui.log)

**Comment by cenfusheng** [comment]
请检测MUMU12是否开启了后台保活功能
该功能会使MAA的截图功能失效
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52312717/07871889-a0f3-4692-9ba0-919bab2dcc60)
