### ISSUE TITLE
我想问下为啥刷理智-关卡选择时不时就会重置选择好的选项，然后导致去刷剿灭

### ISSUE THREAD

**Issue by zyd100** [MaaAssistantArknights/MaaAssistantArknights#5779]

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/87bc3c86-21d5-4bdf-9b6d-94d534987c85)
有开这个吗

**Comment by ABA2396** [comment]
信息这么少谁看的出来问题，如果感觉是bug就选这个
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/0a662157-011b-4e46-9570-8d7f542c887e)

**Comment by zyd100** [comment]
> 



> ![image](https://user-images.githubusercontent.com/99072975/257756709-87bc3c86-21d5-4bdf-9b6d-94d534987c85.png) 有开这个吗

开了，但以前关卡选择1-7的时候也出现过。今天早上选了SL-7，下午定时任务开启后SL-7也被重置成空，跑去刷剿灭了
