### ISSUE TITLE
[3.9.0-beta4] 适配新版本的WSA……

### ISSUE THREAD

**Issue by Temptationee** [MaaAssistantArknights/MaaAssistantArknights#578]
WSA的fast通道已经更新至2204.4000.15.0，屏幕管理方式也发生了改变，现在只有一个默认ID为0的屏幕，也没有原来的mUniqueId字段了，所以助手获取displayId会卡住导致连接失败。

现在随便改了个无障碍功能的字符串给助手读倒是临时能用了（笑）

```
adb -s 127.0.0.1:58526 shell settings put secure enable_accessibility_services "mUniqueId=virtual:com.microsoft.windows.systemapp:com.hypergryph.arknights:0"
// 然后把config.json中WSA的displayId改成这样
"displayId": "[Adb] -s [Address] shell \"settings get secure enable_accessibility_services | grep mUniqueId=virtual:com.microsoft.windows.systemapp:com.hypergryph.arknights\"",
```

顺便提一嘴，这个新的WSA安卓版本从11升到了12.1，而且流畅了不少，起码是能50帧玩明日方舟了，估计不久后应该就放到正式版了，不过这资源利用效率还是跟个⑨一样就是了……

嘛，不过一顿折腾后发现直接用通用连接方案然后F11全屏就能用了，郁闷。(T_T)

**Comment by MistEO** [comment]
emm 所以是我把通用的配置复制粘贴到 WSA 的配置里就可以了？

**Comment by Temptationee** [comment]
> emm 所以是我把通用的配置复制粘贴到 WSA 的配置里就可以了？

是的，这样做是可行的。但是明日方舟的窗口必须全屏，不然OCR很大概率卡住，因为只有一个默认屏幕，窗口化的话会有很多奇怪的黑边，而且不能有其他安卓应用在前台，不然会遮挡屏幕（不过任务在后台本来就会被暂停所以其实不会遇到这样的问题）。ADB的截图大概长这个样子，图像位置都是随窗口的改变而改变的，并不是固定在某一个角落。

![screen](https://user-images.githubusercontent.com/54263335/170538841-b9905f53-7cb0-47f6-b2c8-1d0edf53fed3.png)
