### ISSUE TITLE
自动战斗 视频识别 无效

### ISSUE THREAD

**Issue by 2572190756** [MaaAssistantArknights/MaaAssistantArknights#5784]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在w11系统下，雷电模拟器，MAA(视屏识别失败  
除此之外其他功能玩还可以用

### 日志文件

21点左右
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12240858/asst.log)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12240867/gui.log)

### 截图

<img width="486" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74443980/e66a97e2-b4ce-4ea1-901e-2d02f862a90d">
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74443980/e54198c9-0002-44df-95f0-![无标题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74443980/c2fc4e73-3fd1-4af4-a7d0-d1818a82d51f)

### 还有别的吗？

在w11系统下，雷电模拟器，
视频：https://www.bilibili.com/video/BV1tM4y1H7g1/?spm_id_from=333.788.top_right_bar_window_history.content.click

**Comment by 2572190756** [comment]
<img width="485" alt="屏幕截图 2023-08-02 215921" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74443980/827849e5-e2cc-4c86-975d-21a5e05a68c8">
上面没有显示的无显示的截图

**Comment by MistEO** [comment]
日志截取了，看不到你的版本号。v4.21.0 才支持新地图
