### ISSUE TITLE
开始执行之后锁定基建计划选择或关闭maa自动选择

### ISSUE THREAD

**Issue by AlearXS** [MaaAssistantArknights/MaaAssistantArknights#5787]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

某些时候需要提前或滞后基建换班的执行，这时候需要手动选择基建计划，但是maa会在执行基建换班的前会自动更换基建计划

### 有什么好的想法？

开始执行之后锁定基建计划或关闭maa自动选择

**Comment by status102** [comment]
fixed
8950d2c
