### ISSUE TITLE
基建换班的时候卡住了

### ISSUE THREAD

**Issue by maidangdang1** [MaaAssistantArknights/MaaAssistantArknights#579]
！！！请尽可能详细的描述你遇到的问题，并附上助手软件目录下的 `asst.log` 日志文件！！！

！！！日志文件是可以直接拖拽进来的，没有日志文件的 bug 反馈我们会直接关掉！！！

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
版本号3.3.2 模拟器蓝叠hyper-v版
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8771450/asst.log)
![image](https://user-images.githubusercontent.com/46847241/170271272-1d7eaefa-6fd6-4e2a-88f1-78e3148c9bf7.png)
卡在这里了 不知道为啥
![Screenshot_2022 05 25_21 14 57 287](https://user-images.githubusercontent.com/46847241/170271378-eae7cdba-9de7-4794-b457-51fb0d3c7692.png)

**Comment by ABA2396** [comment]
很多第一次进入的提示都没有自动关闭，比如第一次进肉鸽的提示，这种都是点过一次就不会再出现的。

**Comment by maidangdang1** [comment]
> 很多第一次进入的提示都没有自动关闭，比如第一次进肉鸽的提示，这种都是点过一次就不会再出现的。

和这种情况还是不太一样的吧我感觉
应该是不小心点到了左下角的主线 这个提示无论点多少次都会出现的
![Screenshot_2022 05 28_01 28 22 615](https://user-images.githubusercontent.com/46847241/170761879-c42da683-0ddd-4c65-91b6-e3ed9a6b772c.png)

**Comment by MistEO** [comment]
v4.2.2-beta.1 修了一个基建滑动失效的问题，可能是这个原因，不过现在也没啥头绪总之先关了，之后再出现再来个日志看看（
