### ISSUE TITLE
傀影肉鸽开局放弃招募辅助干员、战斗时山没有切换到二技能

### ISSUE THREAD

**Issue by KyleChoy** [MaaAssistantArknights/MaaAssistantArknights#5792]
### 在提问之前...

- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等

### 问题描述

开傀影肉鸽刷蜡烛，配置如下图，MAA在开局时放弃辅助券，只招山和安赛尔。
进入战斗时，山默认使用一技能，技能那里仍有高光，感觉是没有成功点到切换技能。
![Snipaste_2023-08-03_09-22-43](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40708094/1c07bb03-0e40-41b0-9075-da5d994d04ee)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12245961/asst.log)
时间大概在09:13

### 截图

放弃招募辅助干员：
![辅助干员](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40708094/ca4e40de-57fa-445b-8831-3e74fe0e1a1b)
山没有成功切换技能：
![山](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40708094/1bcfb6d7-919a-494b-8611-3db1fc25ef59)

### 还有别的吗？

设备：Apple M2，macOS 13.5
MAA版本：4.21.0

**Comment by MistEO** [comment]
@Lancarus 来瞅瞅_(:з」∠)_

**Comment by Lancarus** [comment]
因为搬作业的时候把山给删了，导致山不在is start 干员里面，后面招募也会出问题，先暂时用助战的棘刺顶着吧，等我晚上回去修

**Comment by Lancarus** [comment]
如果非要用就暂时把山加到棘刺后面去 ,

![-562999a5e582db7f](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/a398113d-944e-4e4f-846d-81e1e5134101)

                {
                    "name": "山",
                    "skill": 2,
                    "skill_usage": 2,
                    "recruit_priority": 600,
                    "promote_priority": 350,
                    "is_start": true,
                    "recruit_priority_offsets": [
                        {
                            "groups": [ "凯尔希", "地面阻挡", "棘刺" ],
                            "threshold": 1,
                            "offset": -400
                        }
                    ]
                }

**Comment by cenfusheng** [comment]
已修复，将在后续版本实装。
