### ISSUE TITLE
v4.21.0肉鸽没有萨米选项

### ISSUE THREAD

**Issue by YOIMIYA-xiaogong** [MaaAssistantArknights/MaaAssistantArknights#5793]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动肉鸽高级设置里面没有萨米选项

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12246106/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12246107/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110796464/ac92068b-68ef-4542-b7ce-98c4235d4c92)

**Comment by MistEO** [comment]
神奇，看样子似乎 GUI 没更新上。重新下个完整的包看看

**Comment by YOIMIYA-xiaogong** [comment]
> 神奇，看起来好像 GUI 没有更新上。重新下个完整的包看看

试试先

**Comment by YOIMIYA-xiaogong** [comment]
建议卸了重装
