### ISSUE TITLE
MAA自动更新出错

### ISSUE THREAD

**Issue by ilovevanillacoke** [MaaAssistantArknights/MaaAssistantArknights#5795]
### 说说你遇到的问题？

尝试在设置页面选择检查更新，然后开始下载新版本的时候显示错误，请检查网络连接或代理。

**Comment by Danny00002** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/128702856/193f4d11-6c5f-4f08-9a8e-460bfa8c0d05)
重启无法解决

**Comment by SherkeyXD** [comment]
Duplicate of #5759
