### ISSUE TITLE
不能识别萨米肉鸽关卡“巍峨银凇”

### ISSUE THREAD

**Issue by cenfusheng** [MaaAssistantArknights/MaaAssistantArknights#5796]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![4C2ND0H@~2H5LUI D3H7$VU]
![YG0883JU1CO`XZQFJ85ACDB](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52312717/a4324120-fbe3-492f-a623-401904e511dc)

差一点，就差一点MAA就能通关了啊！YJ谁让你用四个多笔画的字，欠我的你拿什么赔！

### 日志文件

(https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52312717/6dab4b19-580e-44a2-9a11-c71b9ce82187)
[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12246681/asst.-.log)

**Comment by cenfusheng** [comment]
![4C2ND0H@~2H5LUI D3H7$VU](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52312717/c1f77b77-60d2-4f06-ba08-1c32e0a2a95a)

**Comment by cenfusheng** [comment]
对了，是满抗干扰（MAA又不用抗干扰，必满），白光一闪一闪

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/d8a4b4e07dad43343b50d7a0b0df6ba60d5ac0ff fixed 试试新模型
