### ISSUE TITLE
“仓库识别”中鼠标指针放置在展示区域时不能使用滚轮

### ISSUE THREAD

**Issue by BiologyHazard** [MaaAssistantArknights/MaaAssistantArknights#5797]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

“仓库识别”中鼠标指针放置在展示区域时不能使用滚轮
“展示区域”指的是图中红色区域
（也许是设计如此？
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44924110/ce389d21-f01b-43f2-b57c-e575d36bdf1a)

### 日志文件

不需要

### 还有别的吗？

Windows11

**Comment by ABA2396** [comment]
改了，但现在只能红框内滚了）
