### ISSUE TITLE
稳定版v3.3.2刷第十章时在结算页面闪退

### ISSUE THREAD

**Issue by Glazed-Frost** [MaaAssistantArknights/MaaAssistantArknights#580]
在勾选吃理智药的情况下，刷第十章时在结算页面闪退
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8772455/asst.log)

**Comment by Glazed-Frost** [comment]
模拟器是蓝叠5 5.7.0.1064 N32

**Comment by MistEO** [comment]
用测试版本吧~

除了肉鸽还不能用，已经全方面稳定了，也就是因为肉鸽拖着所以一直发不了正式版 orz
