### ISSUE TITLE
台服水月BUG

### ISSUE THREAD

**Issue by zxc173123** [MaaAssistantArknights/MaaAssistantArknights#5801]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

卡图上这地方了，手动关闭可继续挂

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12247770/gui.log)

### 截图

![1}VW7_{PHEOD{H{MX_(XO05](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56154254/42e97fc8-8efd-4f1b-b6d9-c019eb452f0b)

### 还有别的吗？

无 #

**Comment by samwang7027** [comment]
太棒了 我也是卡在這裡 想發文結果看到一樣問題 幫推~

**Comment by I-am-zeroZ** [comment]
#5790 
應該修了，等更新吧
