### ISSUE TITLE
無法連接至蓝叠模擬器

### ISSUE THREAD

**Issue by 4lpaca1023** [MaaAssistantArknights/MaaAssistantArknights#5803]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

繁中服
mma v4.21.0
藍疊 v5.12.102.1001

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12249396/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12249397/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/112741934/2b8750e5-3903-4fef-a4c5-b0d7b9bad9c5)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/112741934/31efe291-06aa-4ffe-87e0-f17f8975fa31)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/112741934/791b7839-d118-4ded-8423-8ffa939be290)

**Comment by ABA2396** [comment]
是否创建过不止一个模拟器实例？我看端口和自动检测到的不一致，如果开多个的话还需要指定实例，参考 [藍疊模擬器國際版 5 Hyper-V 版本](https://maa.plus/docs/zh-tw/1.3-%E6%A8%A1%E6%93%AC%E5%99%A8%E6%94%AF%E6%8F%B4.html#%E2%9C%85-%E8%97%8D%E7%96%8A%E6%A8%A1%E6%93%AC%E5%99%A8%E5%9C%8B%E9%9A%9B%E7%89%88-5-hyper-v-%E7%89%88%E6%9C%AC)
填入
```
"Bluestacks.Config.Keyword":"bst.instance.Nougat64.status.adb_port",
```
并把 `Nougat64` 替换成当前实例代号

**Comment by 4lpaca1023** [comment]
以解決，感謝!
我還真忘記我有多開了
