### ISSUE TITLE
resource\roguelike\recruitment.json中傀影部分的红的"skill"应该为2，目前是3

### ISSUE THREAD

**Issue by MoeChiya1** [MaaAssistantArknights/MaaAssistantArknights#5804]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

现在挂傀影肉鸽招募了红以后会因为没法选3技能导致无法进入战斗

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12249491/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12249493/gui.log)

**Comment by Lancarus** [comment]
#5768

**Comment by cenfusheng** [comment]
已修复，将在后续版本实装。
