### ISSUE TITLE
mac版公招次数设置

### ISSUE THREAD

**Issue by terryz-4779** [MaaAssistantArknights/MaaAssistantArknights#5805]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

Mac上公招最多只能设置四次，建议调高。版本为4.21.0

### 其他内容

![14231691062259_ pic](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140965578/94771798-cb88-4d71-a2f8-d60708a30ce3)

**Comment by zzyyyl** [comment]
- https://github.com/MaaAssistantArknights/MaaMacGui/pull/12
