### ISSUE TITLE
刷理智无法选择关卡SL-4等

### ISSUE THREAD

**Issue by AldousShou** [MaaAssistantArknights/MaaAssistantArknights#5808]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用MAA刷理智时，手动输入关卡"SL-4"，无法识别关卡

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12251212/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12251213/gui.log)

**Comment by ABA2396** [comment]
![IMG_20230803_212347.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7bfd3f83-4774-49d3-ac71-4e74fd52e91e)

**Comment by cenfusheng** [comment]
小众关卡请使用“上一次”
