### ISSUE TITLE
卡在领取登录奖励界面

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaAssistantArknights#581]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8774784/asst.log)

![image](https://user-images.githubusercontent.com/33809511/170375034-714c3e44-5f02-4d2c-b446-16f4640c872f.png)

**Comment by Shawnsdaddy** [comment]
copilot 识别困难的干员： 
山，
夜莺,
浊心斯卡蒂

**Comment by guojunyu196** [comment]
同样的问题，我也有
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8779526/asst.log)
