### ISSUE TITLE
maa在使用蓝叠模拟器时无法自动启动模拟器进程

### ISSUE THREAD

**Issue by ZK-0001** [MaaAssistantArknights/MaaAssistantArknights#5811]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa在启动时显示adb连接失败而不启动模拟器但在手动启动模拟器后恢复正常。
已经配置了模拟器的adb路径和模拟器启动快捷方式路径。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12256149/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12256150/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110654054/e1419dd9-0121-49ed-91ac-310a6b8e6333)

### 还有别的吗？

模拟器版本5.11.100.6501 N32 和5.12.0.6504 N32

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/0f96abd1-28d5-44d7-a2c8-26ff303ace7d)
有开这个吗

**Comment by Ydzui** [comment]
我也是这个问题，换了模拟器和电脑都有存在这个现象，Win11，夜神和mumu12，勾选重启模拟器之后，每次linkstart会弹出一个看不清的进程然后无事发生
