### ISSUE TITLE
增加肉鸽自动月度小队功能

### ISSUE THREAD

**Issue by dnancheng** [MaaAssistantArknights/MaaAssistantArknights#5813]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

增加肉鸽自动月度小队功能

**Comment by MistEO** [comment]
你在月底小队界面开始就行了

**Comment by SherkeyXD** [comment]
> 你在月度小队界面开始就行了

剧情那个页面挡住会关吗
不会的话不是就卡死了（

**Comment by MistEO** [comment]
> > 你在月度小队界面开始就行了
> 
> 剧情那个页面挡住会关吗 不会的话不是就卡死了（

会
