### ISSUE TITLE
自动肉鸽 傀影 选干员全是预备干员，有的甚至就没选干员

### ISSUE THREAD

**Issue by lmst2** [MaaAssistantArknights/MaaAssistantArknights#5816]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

好久没玩方舟了，号才十几集，看到maa打算拿来玩玩的，费了半天劲打完了3-8，开了肉鸽。
但是好家伙，开幕雷击。一开始选了两个预备干员，还有一张券啥都没选。
看了下issue四月份有相同问题的但是底下说已经修复，还要open的issue底下没有回复。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12257198/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12257199/gui.log)
时间点的话就是最后一段，我看到错误就停止了

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29498103/fb032635-7fd1-4c42-b743-750bf67f84e8)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29498103/9e44f3ba-fd8e-4cca-af69-dddcf1a47717)

组合选的是 取长补短

自动操作的时候我没有截图，以下截图是我自己操作的时候截的图
第一次使用第一张券选的这个
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29498103/8023b9a5-1506-4fef-b7be-080e5c18c18d)

第二次使用第三张券选的这个
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29498103/2fea56a3-69b1-47fc-a327-543709e05da3)

第三次使用第二张券然后啥也没选
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29498103/f1ac7970-892c-4c9e-a1a7-1c9c87d1eb9d)

### 还有别的吗？

模拟器，蓝叠国际版，win10
然后对于debug log提个建议
`SubTaskError {"class":"asst::CombatRecordRecognitionTask","details":{},"subtask":"CombatRecordRecognitionTask","taskchain":"VideoRecognition","taskid":24,"uuid":"790c0c521600cdc"}`
这个error咋就一个taskid呢，我知道他是识别错误，但是具体呢？视频的第几秒，什么位置识别错误，当时在识别什么，识别结果实啥。这一个没显示。这我咋debug呀。

我分析了以下，这个会不会是因为临时干员等级比我正式的高？那第二个没选又是因为什么？然后我看了一下我这些干员的攻击防御都比临时的好啊，所以正常来讲应该是选我的干员才对，所以这个判断逻辑还要改。

**Comment by 1ouloum** [comment]
我也出现这种情况，尤其是开局选人的时候，近卫和治疗都正常选择，只有辅助100%不选人直接放弃。

**Comment by lmst2** [comment]
> 已修复，将在后续版本实装。

效率好高！
顺便问一下这个他应该不会随随便便选预备干员了吧。我等级没预备干员高的情况下，如果我的干员实际战力比预备干员高的话，应该还是会选我的干员对吧

**Comment by cenfusheng** [comment]
> > 已修复，将在后续版本实装。
> 
> 效率好高！ 顺便问一下这个他应该不会随随便便选预备干员了吧。我等级没预备干员高的情况下，如果我的干员实际战力比预备干员高的话，应该还是会选我的干员对吧

不，还是需要干员等级到精一55级，但适配了更多干员，你可以考虑使用助战开局。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52312717/7fc804d0-3da6-4e2d-a4ef-37858131ce71)

**Comment by lmst2** [comment]
> > > 已修复，将在后续版本实装。
> > 
> > 
> > 效率好高！ 顺便问一下这个他应该不会随随便便选预备干员了吧。我等级没预备干员高的情况下，如果我的干员实际战力比预备干员高的话，应该还是会选我的干员对吧
> 
> 不，还是需要干员等级到精一55级，但适配了更多干员，你可以考虑使用助战开局。 ![image](https://user-images.githubusercontent.com/52312717/258322364-7fc804d0-3da6-4e2d-a4ef-37858131ce71.png)

可以，这就避开了等级差，另外还反应一个bug。这个好友。因为我好长时间没玩了，好友列表空了。然后他给我换班找线索的时候估计要跟好友交换线索还是什么的就卡住了。因为我的好友为空。你这边这些个好友助战有考虑过添加一个检测没好友的情况吗

**Comment by cenfusheng** [comment]
> > > > 已修复，将在后续版本实装。
> > > 
> > > 
> > > 效率好高！ 顺便问一下这个他应该不会随随便便选预备干员了吧。我等级没预备干员高的情况下，如果我的干员实际战力比预备干员高的话，应该还是会选我的干员对吧
> > 
> > 
> > 不，还是需要干员等级到精一55级，但适配了更多干员，你可以考虑使用助战开局。 ![image](https://user-images.githubusercontent.com/52312717/258322364-7fc804d0-3da6-4e2d-a4ef-37858131ce71.png)
> 
> 可以，这就避开了等级差，另外还反应一个bug。这个好友。因为我好长时间没玩了，好友列表空了。然后他给我换班找线索的时候估计要跟好友交换线索还是什么的就卡住了。因为我的好友为空。你这边这些个好友助战有考虑过添加一个检测没好友的情况吗

勾选上使用非好友助战就可以解决借不到助战的问题。交换线索卡住这个问题，建议你另提issue反馈 或者借助战时随意加个好友。

**Comment by lmst2** [comment]
> > > > > 已修复，将在后续版本实装。
> > > > 
> > > > 
> > > > 效率好高！ 顺便问一下这个他应该不会随随便便选预备干员了吧。我等级没预备干员高的情况下，如果我的干员实际战力比预备干员高的话，应该还是会选我的干员对吧
> > > 
> > > 
> > > 不，还是需要干员等级到精一55级，但适配了更多干员，你可以考虑使用助战开局。 ![image](https://user-images.githubusercontent.com/52312717/258322364-7fc804d0-3da6-4e2d-a4ef-37858131ce71.png)
> > 
> > 
> > 可以，这就避开了等级差，另外还反应一个bug。这个好友。因为我好长时间没玩了，好友列表空了。然后他给我换班找线索的时候估计要跟好友交换线索还是什么的就卡住了。因为我的好友为空。你这边这些个好友助战有考虑过添加一个检测没好友的情况吗
> 
> 勾选上使用非好友助战就可以解决借不到助战的问题。交换线索卡住这个问题，建议你另提issue反馈 或者借助战时随意加个好友。

欧克问过了。谢了

**Comment by lmst2** [comment]
> > > 已修复，将在后续版本实装。
> > 
> > 
> > 效率好高！ 顺便问一下这个他应该不会随随便便选预备干员了吧。我等级没预备干员高的情况下，如果我的干员实际战力比预备干员高的话，应该还是会选我的干员对吧
> 
> 不，还是需要干员等级到精一55级，但适配了更多干员，你可以考虑使用助战开局。 ![image](https://user-images.githubusercontent.com/52312717/258322364-7fc804d0-3da6-4e2d-a4ef-37858131ce71.png)

更新一下bug情况，刚刚试了一下打开开局干员选择助战。但是它还是选择了那个预备干员2333
这边是log，最底下那一部分
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12259306/gui.log)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12259305/asst.log)

**Comment by Amadeus-mk** [comment]
我这边也有同样的问题，选了使用助战干员但是不生效，maa不会进去看。

蓝叠国际版
EN服务器
maa版本：v4.24.0-beta.3.d011.g2102fd1e6
