### ISSUE TITLE
一键长草 获取信用及购物 意外进入干员页面卡住

### ISSUE THREAD

**Issue by lmst2** [MaaAssistantArknights/MaaAssistantArknights#5819]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

信用商城购买东西如果第一个商品是雇佣干员的话，他会直接点到干员头像，并且打开详细信息，而我观察到的行为的话，maa是没有预料到这一点的，它还会接下来继续点击本该是第二个物品的地方，然后点击进入到了干员信息里面去了，实际上可能是想购买另一件东西的。然后就意外进入了干员的详情页之后就卡住了。然后开始领取奖励和肉鸽，但是实际上画面没有变换，卡住了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12258196/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12258198/gui.log)
日志最后一部分就是它

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29498103/2790c142-70ee-4acc-aa44-e1a3b010a533

这个是我的录屏，已经买过一次了所以没有完全复现出来，实际上如果不是已售完的话他会点击画面中部，
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29498103/918024d5-9071-455f-8db2-436ae5cd3391)
这样的话在打开的购买物详情界面就会进入到这个干员的详情页，然后其余点击都没有点到返回键，于是就卡住了，包括后面的领取奖励还有肉鸽都没有执行（执行了但是没有效果）

**Comment by ABA2396** [comment]
这个没做识别，试试把干员名字写到黑名单里去？

**Comment by lmst2** [comment]
> 



> 这个没做识别，试试把干员名字写到黑名单里去？

可以，也算是一个解决方法
