### ISSUE TITLE
Copilot issue 

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaAssistantArknights#582]
1. copilot 识别困难的干员：

- 山，
- 夜莺,
- 浊心斯卡蒂

2. Bug: 有时候无法启动
    复现步骤： 1， 选择一个作业json 打任意一关。
                        2,任务完成后停止
                        2. 切换一个作业json 打另外一关（同时带上助战）
                        3. 启动不能 :(  
                
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8775159/asst.log)
![image](https://user-images.githubusercontent.com/33809511/170386349-26a66867-8468-4fac-ac8d-168c57eb70fc.png)

 3. 优化：

**Comment by ABA2396** [comment]
夜莺被识别成了夜营
