### ISSUE TITLE
对路径“adb.exe”的访问被拒绝。

### ISSUE THREAD

**Issue by ChenAiLaoYe** [MaaAssistantArknights/MaaAssistantArknights#5821]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 遇到了问题
对路径“adb.exe”的访问被拒绝。
解决方案
出现未知错误
详细信息
System.UnauthorizedAccessException: 对路径“adb.exe”的访问被拒绝。
   在 System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   在 System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ReplaceADB>d__467.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

MAA 遇到了问题
对路径“adb.exe”的访问被拒绝。
解决方案
出现未知错误
详细信息
System.UnauthorizedAccessException: 对路径“adb.exe”的访问被拒绝。
   在 System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   在 System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ReplaceADB>d__467.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ABA2396** [comment]
在任务管理器里把adb关了再替换

**Comment by cenfusheng** [comment]
出现该问题：
1.mumu12，不要点强制替换adb，如果点过，再勾选一次自动检测，即可
2.mumu/mumux等旧版mumu，所有版本的雷电，在强制替换adb时出现该问题，请根据https://shimo.im/docs/473Qyd7B7Nh1w23w 操作。
3.其它模拟器，特别是夜神，可能是adb炸了，重启电脑，还不行就按顺序试试1和2。
