### ISSUE TITLE
肉鸽近卫券招募异常

### ISSUE THREAD

**Issue by zxmydmug** [MaaAssistantArknights/MaaAssistantArknights#5826]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽选取干员界面翻了几次就取消了
在选择百炼嘉维尔助战后；没有选依旧取消（

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12260703/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12260704/gui.log)

### 还有别的吗？

mumu12
win10

**Comment by zxmydmug** [comment]
我水月萨米都有这种问题

**Comment by SherkeyXD** [comment]
现在还有这个问题吗
