### ISSUE TITLE
明日方舟专版mumu模拟器

### ISSUE THREAD

**Issue by Sourceofflood** [MaaAssistantArknights/MaaAssistantArknights#5827]
### 说说你遇到的问题？

明日方舟专版mumu模拟器现在对于maa的支持如何？是否跟其他模拟器（如蓝叠等完美支持模拟器）一样？是否会出现官方查封使用maa的账号？

**Comment by ABA2396** [comment]
你不如去问问明日方舟专版mumu模拟器和mumu模拟器有什么区别

**Comment by cenfusheng** [comment]
明日方舟专版mumu12模拟器和普通mumu12模拟器目前对maa没有已知的区别，当作mumu12看待即可。
