### ISSUE TITLE
MAA自动退出后有adb进程残留

### ISSUE THREAD

**Issue by LAi-lsp** [MaaAssistantArknights/MaaAssistantArknights#5828]
### 说说你遇到的问题？

<img width="545" alt="adb残留" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76437134/0c1e0a60-4e0d-4524-a9d4-5b97cdc50357">

**Comment by SherkeyXD** [comment]
Duplicate of #5704
