### ISSUE TITLE
自定义基建排班bug

### ISSUE THREAD

**Issue by Nightingalelyy** [MaaAssistantArknights/MaaAssistantArknights#5829]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我的自定义基建排班在最后一间宿舍固定选择车尔尼，爱丽丝，以及留下三个空格用于摆放回心情干员。

但是执行排班的时候会出现先选中了车尔尼以及爱丽丝，然后取消选择二人，并无法补满宿舍的问题

偶发MAA处理最后一间宿舍时不断右滑至干员列表尽头并无法选中干员入驻宿舍导致无限循环操作的问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12264603/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12264605/gui.log)

**Comment by MorphineA** [comment]
我和你一模一样的问题
