### ISSUE TITLE
无限刷肉鸽进入关卡前选干员的时候卡住不动，没有操作

### ISSUE THREAD

**Issue by Chen-wwd** [MaaAssistantArknights/MaaAssistantArknights#5830]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

会卡在进入关卡前的准备选干员阶段，一直不选人也不开始作战

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12265254/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12265314/gui.log)

### 还有别的吗？

win10，蓝叠x，配置为i7-11700H+3060，模拟器肉鸽配置为傀影、刷等级、指挥分队、其余默认，连接方式如图
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/88320482/06747c04-4910-4856-9f7b-18c9f5f9cdc4)

**Comment by Chen-wwd** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/88320482/48b8a194-5ed5-4d28-b41e-f82782105196)
会卡在这个页面

**Comment by ReAgainO** [comment]
有同样问题，不过区别是用的mumu12模拟器

**Comment by tsuki-z1** [comment]
![G5HV9~7NE}UR~H7UP ~ILUH](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141479674/00d63c54-491b-416e-86c2-6f2b4d91d666)
我也碰上这个问题，他会在配完队选技能的时候，不给红点技能，而是点进去红的角色界面，然后返回接着就停在这个界面。

**Comment by Despair21** [comment]
有同样问题，换了3个模拟器还是会卡住不动

**Comment by ouxinlixue** [comment]
一样一样的问题，感觉是红识别的问题。

**Comment by APhragmites** [comment]
应该是红的问题，拿了红以后选技能时会点击一下红再返回，然后就停在开始行动的界面了。

**Comment by SherkeyXD** [comment]
红的问题已经修复
