### ISSUE TITLE
建议添加肉鸽刷开局功能

### ISSUE THREAD

**Issue by guyishuo** [MaaAssistantArknights/MaaAssistantArknights#5832]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题

**Comment by ntgmc** [comment]
请具体解释你需要的功能

**Comment by cenfusheng** [comment]
大概是烧开水或者刷密文版刷藏品的意思，都已有相关issue，这个标题不明确关了
