### ISSUE TITLE
关于肉鸽自动战斗的干员安放位置提议

### ISSUE THREAD

**Issue by lmst2** [MaaAssistantArknights/MaaAssistantArknights#5833]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29498103/044996aa-9422-4563-8985-d84c131893e6)
咱就来看这一张它自动选择的位置。
我认为他的干员选择位置应该优先计算一下所有路径，并把盾兵安置在一个可以堵住所有与蓝色box相通的路径点上。这样才不会又兵线被漏掉

### 有什么好的想法？

可以使用类似迷宫找出口的算法。应用一种寻路算法，虽然我不知道，但是应该很常见的，明日方舟本身敌人就有寻路算法。放置箱子不能堵住入口。那我只需要反过来，找出放置盾兵可以堵住路口的那个点，然后其他的狙击手啥的再以此为基点计算放置位置。

**Comment by Lancarus** [comment]
应该修复了，用这两天发的新版看看

**Comment by lmst2** [comment]
> 应该修复了，用这两天发的新版看看

我用的就是这两天发的4.21.0
需要我上传log吗，这几天一直挂机让它打，不太清楚这个到底在log哪部分233

**Comment by Lancarus** [comment]
[v4.21.1-alpha.1.d031.g7d3e7a443](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v4.21.1-alpha.1.d031.g7d3e7a443)

**Comment by lmst2** [comment]
> [v4.21.1-alpha.1.d031.g7d3e7a443](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v4.21.1-alpha.1.d031.g7d3e7a443)

ohhh 可以，辛苦了
