### ISSUE TITLE
自动肉鸽 布置干员不懂得避开地图上的危险装置

### ISSUE THREAD

**Issue by lmst2** [MaaAssistantArknights/MaaAssistantArknights#5834]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

地图上有一些对敌方和己方都有伤害的装置时不懂得避开攻击区域放置干员。
理应先检测一下有无这些装置，然后点击展开攻击区域。识别完成之后部署干员时排除这些区域。

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12265910/debug.zip)
日志在最后一部分

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29498103/296d4547-c08e-4dd3-b382-764e73952db1)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29498103/c0c6aa50-2009-4d52-9eb3-fd0cc7507e97)

**Comment by ntgmc** [comment]
无法检测
