### ISSUE TITLE
自动肉鸽增加更多可自定义选择（比如干员和购买藏品的优先级，事件选择优先级）

### ISSUE THREAD

**Issue by Zichen3317** [MaaAssistantArknights/MaaAssistantArknights#5835]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

MMA现有的自动肉鸽功能的可自定义选项太少了。有时候因为box太小，导致MMA在自动肉鸽时很多干员都不选，但是希望是够的。

### 有什么好的想法？

增加一个可编辑可排序的干员、购买藏品、事件选择的优先级设置。
可以做成类似流程图那样，当开始招募干员时，先按照已经编辑的优先级进行判断，然后根据判断结果进行处理。
为了方便理解，以下是一段基于python的简单易懂的代码:
`
def Select(Name):
    '''选择干员'''
    pass
def PeopleSelect(Point:int,PeopleList:list):
    '''
    干员选择自定义
    参数:
    Point 希望点数
    PeopleList 当前可招募的干员列表
    '''
    if '棘刺' in PeopleList:
        #如果池子里有可选的棘刺，则优先选棘刺
        Select('棘刺')
    elif '玛恩纳' in PeopleList and Point in range(3,6):
        #如果玛恩纳在池子里且希望在指定范围内，则选择
        Select('玛恩纳')
`
比如干员识别的时候也可以分为要进阶和没进阶的

**Comment by cenfusheng** [comment]
目前的resource/rougelike中的几个json已经很清晰好改，干员优先级比你说的方法更好，商品事件也很好改。
暂不考虑做改动，有需求可自行改动。

**Comment by cenfusheng** [comment]
目前的resource/rougelike中的几个json已经很清晰好改，干员优先级比你说的方法更好，商品事件也很好改。
暂不考虑在表达形式上做改动，有需求可自行改动json。

**Comment by Zichen3317** [comment]
> 目前的resource/rougelike中的几个json已经很清晰好改，干员优先级比你说的方法更好，商品事件也很好改。 暂不考虑在表达形式上做改动，有需求可自行改动json。

好的好的，感谢感谢！
