### ISSUE TITLE
开局时自动选择减1希望换藏品，导致希望不够无法招募到设置的开局干员

### ISSUE THREAD

**Issue by bond166** [MaaAssistantArknights/MaaAssistantArknights#5836]
### 说说你遇到的问题？

水月肉鸽连续探索后，maa会在开局时选择减1希望换藏品，导致无法招募到预设的开局6希望助战干员，因此卡在招募助战干员的界面，不断刷新。
如果用自己的干员，它会选择5希望干员，那这个开局6星的设置就形同虚设了。。。
希望哪个大佬能改进这个开局优先级，让maa不要选择减希望的选项。

**Comment by SherkeyXD** [comment]
Duplicate of #5413
