### ISSUE TITLE
关于信用购物的建议

### ISSUE THREAD

**Issue by maodaoOvo** [MaaAssistantArknights/MaaAssistantArknights#5839]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

由于优先级的原因 会跳过次一级优先级的道具 购买不降价的商品

### 有什么好的想法？

期望可以增添折扣商品优先

### 其他内容

无

**Comment by Shawnsdaddy** [comment]
折扣商品永远是从左上到右下排列的。maa扫描也是这个逻辑
