### ISSUE TITLE
肉鸽选择干员红之后会卡在选干员界面不动，无法开始战斗

### ISSUE THREAD

**Issue by kozmo9** [MaaAssistantArknights/MaaAssistantArknights#5842]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽每次遇到红这个干员，在选择干员的时候就会卡着不动，导致无法开始战斗，必须手动点开始战斗才会进入关卡战斗

### 日志文件

[新建文件夹.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12266769/default.zip)

### 截图

![微信图片_20230805172936](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/132199022/74db1c74-7e1f-4feb-951b-8621bfa3ea6d)
![微信图片_20230805174410](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/132199022/3da949c8-b96e-418c-aeed-34038a6bcfe3)

### 还有别的吗？

win11，配置为AMD Ryzen 5 5600H +3050Ti，肉鸽配置是突击战术分队，锁棘刺，其余默认

**Comment by kozmo9** [comment]
asst被adb占用着我不知道如何操作，只能复制全部文本放进一个新的txt里面，请见谅，如果可以提供压缩asst方法的话不胜感激

**Comment by ABA2396** [comment]
这个问题已经修过了，等下个版本更新。现在可以搜下 `\resource\roguelike\recruitment.json` 里的 `红` ，把 `"skill": 3,` 改成 `"skill": 2,`

**Comment by kozmo9** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kozmo9** [comment]
> 这个问题已经修过了，等下个版本更新。现在可以搜下 `\resource\roguelike\recruitment.json` 里的 `红` ，把 `"skill": 3,` 改成 `"skill": 2,`

收到，目前运行正常，谢谢你
