### ISSUE TITLE
视频识别

### ISSUE THREAD

**Issue by qmzzhennan** [MaaAssistantArknights/MaaAssistantArknights#5843]
### 说说你遇到的问题？

视频识别：在“以管理员身份启动”的情况下，无法通过拖动视频到“浏览文件按钮（路径栏边上的小按钮，我不确定是不是叫这个名字）”开启视频识别功能。

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/5a5a20f1-29cd-42db-b1c6-7a8a318b7996)
试试这样
