### ISSUE TITLE
傀影开局招募只选预备干员+放弃招募

### ISSUE THREAD

**Issue by hywx1** [MaaAssistantArknights/MaaAssistantArknights#5845]
### 说说你遇到的问题？

傀影开局招募只选预备干员+放弃招募
![媒体播放器 2023_8_5 23_10_28](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141505583/3acde04b-6041-46b2-9df5-f82464aeba6a)

**Comment by Lancarus** [comment]
用最新版试试

**Comment by hywx1** [comment]
> 

确实是最新的，4.21.0

**Comment by hywx1** [comment]
> 



> 

是最新的4.21.0

**Comment by Lancarus** [comment]
最新的不是昨晚的[v4.21.1-alpha.1.d031.g7d3e7a443](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v4.21.1-alpha.1.d031.g7d3e7a443)么

**Comment by hywx1** [comment]
检查更新显示的就是最新版

**Comment by Lancarus** [comment]
那个是公测版，正式版没推，下载解压后覆盖原文件

**Comment by hywx1** [comment]
> 那个是公测版，正式版没推，下载解压后覆盖原文件

还不行，依旧会放弃招募，不过之选预备解决了
