### ISSUE TITLE
傀影肉鸽选中红之后不不开启战斗

### ISSUE THREAD

**Issue by Frank06170** [MaaAssistantArknights/MaaAssistantArknights#5846]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在傀影肉鸽选中红更改2技能之后不会进入战斗， 会卡在选人界面。截图中显示10：21进入战斗关选人，11：10我手动进入战斗，之间一直卡在选人界面

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12267590/debug.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141509062/829fcf14-e6b0-487c-a8a0-735c0b90f38e)

**Comment by Frank06170** [comment]
使用的是Mumu12模拟器

**Comment by ABA2396** [comment]
#5842
