### ISSUE TITLE
萨米肉鸽关卡识别错误

### ISSUE THREAD

**Issue by yhdds** [MaaAssistantArknights/MaaAssistantArknights#5848]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽进入作战后提示关卡识别错误，不部署干员

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12268520/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12268522/gui.log)

### 截图

<img width="603" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141533930/d4f302b0-a6c4-4382-a663-02f84eb3a116">

**Comment by yhdds** [comment]
模拟器mumu模拟器，2.7.29.0（x64）

**Comment by SherkeyXD** [comment]
试试重新下载完整包

**Comment by Black1312** [comment]
识别错误的关卡名称给一下。建议将MAA放置在非中文目录，如：D:\MAA
