### ISSUE TITLE
肉鸽第一关-开局就跪了，医疗干员芙蓉摆放的朝向有问题

### ISSUE THREAD

**Issue by huananbeef** [MaaAssistantArknights/MaaAssistantArknights#585]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8785818/asst.log)

在肉鸽第一关的时候，因为落地医疗干员芙蓉的摆放位置朝向发生了问题，导致开局就跪了。目前尚不清楚是医疗干员皮肤导致，还是其他原因。

![QQ图片20220527180801](https://user-images.githubusercontent.com/39019480/170679257-ea687265-8739-4ea9-9c5f-7dcc4eb2c323.png)

**Comment by MistEO** [comment]
肉鸽的目标是长时间稳定挂机，本来就不是很智能，有些关卡是大概率过不了的，但是大部分关卡还是能正常打过的，不过我们有计划去优化了。

**Comment by huananbeef** [comment]
> 

好的，了解了，因为这边第一次用这个东西，肉鸽开局连续两次都是猎人小屋，都是同样的神秘摆位，导致我以为出了什么bug_(:з)∠)_
