### ISSUE TITLE
挂机时间过长之后出现的放干员时卡主现象

### ISSUE THREAD

**Issue by deathkeft** [MaaAssistantArknights/MaaAssistantArknights#5851]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

挂机时间过长之后出现的放干员时卡主现象，本来是想挂机刷肉鸽刷钱的，但是每次都发现，时间一长就会在放干员的时候卡主，具体可能是上一个干员拖到了对应位置，但是没有选择方向，导致没有放下去，但是又想要放第二个 干员，导致一直卡在那里，然后一直漏怪。如此循环。

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12268692/debug.zip)

### 还有别的吗？

mumu12，win11，mumu12中性能模式。笔记本电脑，1050显卡

**Comment by cenfusheng** [comment]
长时间挂机导致的掉帧，请检查MUMU12是否已关闭动态帧率。如该问题经常出现，可考虑人工调整MAA的延迟（每次MAA版本更新后会被覆盖，需重新调整），位置如下：

maa文件夹/resource/tasks.json

    "BattleUseOper": {
        "algorithm": "JustReturn",
        "preDelay": 150,
        "postDelay": 200,
        "Doc": "pre 是从点击干员，到干员信息弹出来等待的时间；post 是干员上场，到设置朝向之间等待的时间"
    },
    "BattleSwipeOper": {
        "algorithm": "JustReturn",
        "preDelay": 400,
        "postDelay": 100,

以上四个数字+100即可。
