### ISSUE TITLE
傀影开局选人辅助招募券会跳过

### ISSUE THREAD

**Issue by hywx1** [MaaAssistantArknights/MaaAssistantArknights#5853]
### 说说你遇到的问题？

傀影开局选人辅助招募券会跳过
![MAA (Default) - v4 21 1-alpha 1 d031 g7d3e7a443 - 火山旅梦 - MuMu 模拟器 12 (127 0 0 1_16384) - 官服 2023_8_6 14_35_03](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141505583/abe355a7-546f-4245-ba42-00442003b2ed)
![媒体播放器 2023_8_5 23_10_28](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141505583/699b08bd-be4f-4714-9d2a-fff666d3d276)

**Comment by pgp2023** [comment]
我也是这个问题，版本是最新的内测版
