### ISSUE TITLE
没有maadeps-build.py

### ISSUE THREAD

**Issue by aleck099** [MaaAssistantArknights/MaaAssistantArknights#5855]
### 说说你遇到的问题？

https://maa.plus/docs/2.1-Linux%E7%BC%96%E8%AF%91%E6%95%99%E7%A8%8B.html#%E7%BC%96%E8%AF%91%E8%BF%87%E7%A8%8B

文中指出运行maadeps-build.py
但这个文件在 528b4a63d5d43cd6d42c4fbf0bc89088ce7d6edf 已被删除

**Comment by MistEO** [comment]
文档没改，调下 MaaDeps/build.py 就可以了
