### ISSUE TITLE
“一键长草”设置的优化建议

### ISSUE THREAD

**Issue by lin-junliang** [MaaAssistantArknights/MaaAssistantArknights#5857]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前使用中出现每次都需要微调或者检查的问题，希望可以提高自动化程度

### 有什么好的想法？

一、“获取信用及购物”
该选项通常一天只会需要执行一次，如果检测到当天已经执行过了，则自动关闭，否则恢复打开。可以避免不必要的操作，加速完成任务
二、“刷理智”
“关卡选择”新增“按优先度选择”
选择该项后增加一个设置按钮设置优先度，和一个活动选项框选择活动
例如优先度可以设置 剿灭 > 活动 > 龙门币 > 经验书
1、检测到本周剿灭已完成1800后跳过，周一恢复，避免频繁尝试剿灭
2、活动选项框的内容包含“未选择”，未选择的情况泽跳过活动

这样就无需理会轮换，对我来说基本可以做到全自动

**Comment by ABA2396** [comment]
要是剩余信用为120，剩下材料最低价是200，要是之后收了个200的party就超过上限了；设置-高级设置-实
使用备选关卡 功能

**Comment by hifuclub** [comment]
有可能晚上时候因为会客室又多了200信用，所以额外购物一次我觉得是有必要的

**Comment by Shawnsdaddy** [comment]
> 有可能晚上时候因为会客室又多了200信用，所以额外购物一次我觉得是有必要的

我一般是无缝开party + 收信用+购物的
