### ISSUE TITLE
MAA能否做到划火柴放干员（零帧部署）

### ISSUE THREAD

**Issue by aleck099** [MaaAssistantArknights/MaaAssistantArknights#5858]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

waydroid不能绑按键
按Esc不能在极短时间内连续多次暂停游戏
MAA能否做到划火柴放干员（零帧部署）

### 有什么好的想法？

初始：游戏为暂停状态

点击一个干员，进入子弹时间
*取消暂停
*拖出干员
*暂停
将刚刚拖出的干员放到指定位置

以上加*号的步骤要在1/60秒（一帧）内完成

**Comment by avw621314** [comment]
可以參考此帖: https://forum.gamer.com.tw/C.php?bsn=33651&snA=2758
部分模擬器不支持幀操，個人不建議大規模應用。
