### ISSUE TITLE
日服水月肉鸽 不期而遇多选一节点 死循环

### ISSUE THREAD

**Issue by Joyce-Ethene** [MaaAssistantArknights/MaaAssistantArknights#5862]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

遇到某些选择一项之后才能继续的节点，会上下不断浏览，但不做出选择，导致无法继续探索。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12270466/gui.log)

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12270471/asst.zip)

时间点：08-06 22:27:09

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131970654/62cbd232-6104-4aa7-a7d1-252a10119db6

**Comment by Joyce-Ethene** [comment]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12270517/asst.zip)
08-06 23:17:39


https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131970654/a6323bd8-ea95-415c-9d47-2b6f2cc003bc

**Comment by Joyce-Ethene** [comment]
补充：
单一选项（获得3点护盾值）也会卡住。

**Comment by Manicsteiner** [comment]
根据您的asst.log，每当尝试识别Mizuki@Roguelike@StageEncounterLeaveConfirm.png时，OCR得分仅为0.75左右。
如果您在4.20.x版本及以前正常，请删除 \resource\global\YoStarJP\resource\task.json 的 "Mizuki@Roguelike@StageEncounterLeaveConfirm" 节点，并用旧版本中的 \resource\global\YoStarJP\resource\template\Mizuki@Roguelike@StageEncounterOptionUnknown.png 替换掉新版本的。
如果仍不能正常使用，请参考 [外服适配](https://maa.plus/docs/2.5-%E5%A4%96%E6%9C%8D%E9%80%82%E9%85%8D%E6%95%99%E7%A8%8B.html) 自行调整该节点的roi。

**Comment by Joyce-Ethene** [comment]
非常感谢！我试一下:)

**Comment by zzyyyl** [comment]
下次遇到的时候上传日志以及**卡住节点的截图**，谢谢
