### ISSUE TITLE
萨米肉鸽不进行部署，显示关卡识别错误

### ISSUE THREAD

**Issue by rozenzhao** [MaaAssistantArknights/MaaAssistantArknights#5864]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽开始后，进入关卡无任何操作，显示“关卡识别错误”

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12271039/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12271040/gui.log)

### 截图

![微信截图_20230807083516](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141595364/d176de4d-1653-4300-8144-1ffb68afdc92)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141595364/162d3a3f-dce5-402d-9a47-b0bb72f64077)

### 还有别的吗？

已经尝试过替换ADB或者更改链接模式，均无效！

**Comment by SherkeyXD** [comment]
试试重新下载完整包
