### ISSUE TITLE
(台服) 部分R6系列干员无法识别

### ISSUE THREAD

**Issue by Jimmy8870** [MaaAssistantArknights/MaaAssistantArknights#5865]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用自定义基建排班(id:1691383430583343),于控制中心放置R6干员部分出现无法识别问题,长时间卡在来回寻找干员步骤( 于gui.log [2023-08-07 06:55:19.268] )

想说是不是因为台服R6干员名字是英文所以才有问题,所以自己将名字该掉,结果问题仍然发生( 于gui.log [2023-08-07 11:05:26.164] ) ,而Castle-3也有未正确视别纪录( 于gui.log [2023-08-05 11:02:55.088] 和 [2023-08- 04 11:05:28.409] )

之后进行干员识别,结果发现未正确识别的也有包含R6干员 (THRM-EX 闪击 鞭刃)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12271892/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12271914/gui.log)

### 截图

![Inkedbandicam 2023-08-07 12-03-16-545](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/c46d0106-c39a-4240-879b-93447b0af538)
![2023-08-07_12-02-36-639_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/8e2c1c27-d24e-4a79-ad5a-e62ebc4e1a7f)
![2023-08-07_12-02-37-782_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/8e4bda6e-d6f7-49fc-8b4f-16d498903e3a)
![2023-08-07_12-02-39-013_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/6280c8dd-560a-454e-9d27-9143456e92e6)
![2023-08-07_12-02-44-897_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/16cbe0ff-c2cb-4350-835f-3b17a2af5582)
![2023-08-07_12-02-46-099_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/2a6c689c-6f27-4b7e-93ae-bb510cc6932c)

### 还有别的吗？

![bandicam 2023-08-07 12-11-09-731](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/583eb4f6-7294-4c54-882d-8c25688e26e8)
![bandicam 2023-08-07 12-25-15-645](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/ad0e32f1-73ea-478f-81bd-e564b40caf59)
![bandicam 2023-08-07 12-26-12-758](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/00cc8228-89de-44cf-9b11-44363420bb2c)
![bandicam 2023-08-07 12-26-16-527](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/3626e601-82e5-4453-81df-0ab83ac25659)

![bandicam 2023-08-07 12-17-10-977](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/f400c5f9-397d-4a23-8db3-375fb3140ffc)
![bandicam 2023-08-07 12-17-30-173](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/ddcd03fa-20c9-4292-8d8e-aafb27204274)

處理器:Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
GPU:GTX 1660 Super

Windows 10 企業版 22H2

**Comment by cenfusheng** [comment]
感谢您提供的日志，已尝试修复，将在后续版本实装，如仍有问题可继续反馈。
