### ISSUE TITLE
傀影肉鸽山的技能选择错误

### ISSUE THREAD

**Issue by yanshe666** [MaaAssistantArknights/MaaAssistantArknights#5866]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

傀影肉鸽开局选择取长补短分队（含近卫）之后选择干员山，但为山默认选择的是一技能而非二技能，导致实战中难以发挥山的最大价值

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12272348/gui.log)

### 截图

 [
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141607429/324e0cff-e373-42f2-b4a9-1be2d32b92ce)
](url)

**Comment by SherkeyXD** [comment]
请将你的 asst.log 一起发上来

**Comment by BruceS509** [comment]
同，今天我也遇到这个问题了，测试了煌、耀骑士临光等干员，发现在作战编队界面，选择干员正常，但是跳过了调整技能环节，直接开始作战了

**Comment by Lancarus** [comment]
试一下最新的公测版看看
