### ISSUE TITLE
linux gui或完整的参数设置参考

### ISSUE THREAD

**Issue by DILIU899** [MaaAssistantArknights/MaaAssistantArknights#5870]
### 说说你遇到的问题？

不知道这个是不是应该在issue里提还是应该直接去discussion orz
想请问一下现在有没有linux的gui可以使用，或者替代方案是是否有提供比较完整的脚本运行的时候的参数设置的参考文档（请问这个现在有吗，如果有在哪里呢？）

目前在网站上的document的参数设置应该还停留在水月时代 orz，所以有一些设置找不到参考不知道怎么设置，求帮助

(目前比较想知道的是怎么关闭刷剿灭，以及萨米肉鸽的参数设置和之前的有什么区别，是否有改变过API之类的)

**Comment by SherkeyXD** [comment]
没有gui（瘫
> 目前比较想知道的是怎么关闭刷剿灭，以及萨米肉鸽的参数设置和之前的有什么区别，是否有改变过API之类的
这得问万能的玛丽（ @MistEO

**Comment by MistEO** [comment]
文档没更新，参数没啥区别，萨米是 `Sami`
