### ISSUE TITLE
每次更新能否保留之前设置的（收起/展示）热键

### ISSUE THREAD

**Issue by gew5251** [MaaAssistantArknights/MaaAssistantArknights#5871]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

每次更新之后要重新设置热键，因为是多开，所以有点麻烦，所以希望更新时保留之前设置的热键，望采纳，感谢！
![Snipaste_2023-07-20_00-45-09](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99937172/37287010-b977-42ff-9a95-0066b53aad83)

**Comment by ABA2396** [comment]
热键应该是保留的，检查下是否有软件热键冲突
