### ISSUE TITLE
双开mumu12模拟器，两个端口分别同时连接MAA和FGOPY,会冲突导致互相断联

### ISSUE THREAD

**Issue by zhhq255762** [MaaAssistantArknights/MaaAssistantArknights#5872]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

双开mumu12模拟器，两个端口分别同时连接MAA和FGOPY,会冲突导致互相断联。
以前用安卓7可以，但是也是先FGOPY先开刷，再MAA开刷就可以，否则FGOPY会让MAA断联，但是现在好像都不行了。
不知道是扫描端口冲突还是怎么样。是不是现在在开刷的时候会扫描连接一遍端口？

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12279894/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12279895/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/48901967/73dd9b8b-f7f5-4671-b9c3-eec52c17fab2)

**Comment by Shawnsdaddy** [comment]
别的脚本问题建议联系fgo.py作者

Maa 是支持多开的

**Comment by Lancarus** [comment]
目测是抢adb了

**Comment by zhhq255762** [comment]
好的。谢谢
