### ISSUE TITLE
关于连接mumu模拟器 adb的路径问题

### ISSUE THREAD

**Issue by mainlove** [MaaAssistantArknights/MaaAssistantArknights#5878]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

很久以前在mumu 6 填写路径时候就遇到问题
本次更新mumu12 发现问题仍旧存在
具体表现为，我将adb路径设置为D:\\Program Files\\Netease\\MuMuPlayer-12.0\\shell\\adb.exe
发现无法连接，根据我的经验，怀疑是路径问题，于是把adb.exe复制到D:\bin\adb.exe下
填写这个路径，一切正常！

之前的mumu6，很久之前我也是如此操作，最近更新mumu12 发现这个路径问题仍旧存在！
我不清楚为何其他人没有遇到这个问题，并没有搜索到相关信息。

### 日志文件

{"details":{"adb":"D:\\Program Files\\Netease\\MuMuPlayer-12.0\\shell\\adb.exe","address":"127.0.0.1:16384","config":"MuMuEmulator12"},"uuid":"","what":"ConnectFailed","why":"Connection command failed to exec"}

**Comment by SherkeyXD** [comment]
强制替换adb能正常使用吗
