### ISSUE TITLE
萨米肉鸽在自动刷钱任务中无法正常进入萨米肉鸽界面，手动进入后无法正常开始探索

### ISSUE THREAD

**Issue by ivyand** [MaaAssistantArknights/MaaAssistantArknights#5879]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在萨米肉鸽的刷钱任务中发现maa无法正常进入萨米肉鸽界面，如在主界面会一直点击干员位置但是不点进去（就像点击后又移开的表现一致）；如在难度选择界面会尝试点击“冬夜展览馆”位置；如在终端会尝试点击本次夏活的活动界面；肉鸽探索功能在水月肉鸽可以正常探索，只有萨米肉鸽会出现问题。然后不管它一阵子它会自动完成探索，并且在第一次完成探索后后续的探索完成会很快。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12288791/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12288794/gui.log)

### 还有别的吗？

使用的是mumu6的模拟器，window10专业版的操作系统。
说实话，既然水月肉鸽是可以的，那么应该不会是操作系统或者模拟器的问题吧，会不会是图像识别少了哪张图片

**Comment by ivyand** [comment]
再补充一点，如果手动进入探索，maa会在选择分队时在“后勤分队”和其它分队之中反复横跳，然后任务会报错，再次执行时会迅速跳完成探索。

**Comment by SherkeyXD** [comment]
疑似资源缺失
试试重新下载完整包

**Comment by MistEO** [comment]
难度不会帮你选的，要自己选一下
