### ISSUE TITLE
傀影肉鸽，最后该点战斗的时候，多点一次干员而不进入战斗

### ISSUE THREAD

**Issue by TYYearn** [MaaAssistantArknights/MaaAssistantArknights#5880]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

傀影肉鸽，默认开局，棘刺精二，当队内有 红 时，最后调整技能后，棘刺技能未调整，另外会多点一次 红 ，并且不进入战斗，后续无任何操作。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12289354/gui.log)

### 截图

![奎影肉鸽](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34617892/7af3b961-5da7-46ac-9b8c-bff49082846b)

### 还有别的吗？

MUMU12；Win10

**Comment by Lancarus** [comment]
更新到内测版
