### ISSUE TITLE
macOS MAA 访问好友收信用 仅访问两名好友就退出

### ISSUE THREAD

**Issue by FSPaul2498** [MaaAssistantArknights/MaaAssistantArknights#5884]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

macOS版本MAA在访问好友 收取信用时，每次执行任务 仅访问*两*名好友 就直接退出访问 然后去商店进行购物了
补充：具体操作为 在好友列表点击任意一次“访问基建”，然后点击一次“访问下位”，然后就会立刻退出访问 前往商店，实际上是访问两次好友。

### 日志文件

macOS版本MAA的debug文件夹位置我没找到，如果能提供路径我可以再补充上传

### 还有别的吗？

macOS Sonoma 14.0 Beta版(23A5301h)
Mac mini M2 8+256
最新版PlayCover（文档提供的fork）
最新版明日方舟（脱壳）客户端
MAA 4.21.0 最新macOS正式版
（以上最新指本条issue时间2023/8/8）

**Comment by MistEO** [comment]
已知问题，等个有 mac 的佬带带，https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5599

**Comment by Sputnik103** [comment]
想问下uu你的mac版本运行“开始唤醒”任务成功吗？我这里一直不成功，需要自己手动打开舟的应用后才能运行“开始唤醒”

**Comment by Sputnik103** [comment]
> 你说的是正常现象，“开始唤醒”指的是点击游戏界面的开始唤醒按钮登录游戏，并非打开游戏客户端。macOS MAA没有启动游戏应用的功能，需要自己启动游戏。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Sputnik103 ***@***.***&gt; 发送时间: 2023年8月11日 07:13 收件人: MaaAssistantArknights/MaaAssistantArknights ***@***.***&gt; 抄送: MGee ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [MaaAssistantArknights/MaaAssistantArknights] macOS MAA 访问好友收信用 仅访问两名好友就退出 (Issue #5884) 想问下uu你的mac版本运行“开始唤醒”任务成功吗？我这里一直不成功，需要自己手动打开舟的应用后才能运行“开始唤醒” — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

感谢，因为我之前某个版本是可以自动打开的我以为已经增加了自动打开的功能

**Comment by Sputnik103** [comment]
> 呃啊 刚刚发现是我孤陋寡闻了，我亲自试了下，在设置里选择游戏客户端为官服，MAA就可以自动启动游戏应用了。你检查一下MAA设置里是否填写了正确的游戏客户端呢？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Sputnik103 ***@***.***&gt; 发送时间: 2023年8月11日 08:58 收件人: MaaAssistantArknights/MaaAssistantArknights ***@***.***&gt; 抄送: MGee ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [MaaAssistantArknights/MaaAssistantArknights] macOS MAA 访问好友收信用 仅访问两名好友就退出 (Issue #5884) 你说的是正常现象，“开始唤醒”指的是点击游戏界面的开始唤醒按钮登录游戏，并非打开游戏客户端。macOS MAA没有启动游戏应用的功能，需要自己启动游戏。 … ------------------ 原始邮件 ------------------ 发件人: Sputnik103 @.&gt; 发送时间: 2023年8月11日 07:13 收件人: MaaAssistantArknights/MaaAssistantArknights @.&gt; 抄送: MGee @.&gt;, Author @.&gt; 主题: Re: [MaaAssistantArknights/MaaAssistantArknights] macOS MAA 访问好友收信用 仅访问两名好友就退出 (Issue #5884) 想问下uu你的mac版本运行“开始唤醒”任务成功吗？我这里一直不成功，需要自己手动打开舟的应用后才能运行“开始唤醒” — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 感谢，因为我之前某个版本是可以自动打开的我以为已经增加了自动打开的功能 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

是的我已正确设置了客户端，这个问题困扰了我蛮久了，我在某次版本更新后突然不行了，也试了重装maa客户端和playcover，都没有解决

**Comment by EricWangxy** [comment]
回复一下mac版的debug路径 maa界面 屏幕最上面有个文件选项 点击打开日志文件夹
