### ISSUE TITLE
希望肉鸽刷源石锭时道中可以不抓干员

### ISSUE THREAD

**Issue by mmy1043** [MaaAssistantArknights/MaaAssistantArknights#5886]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在使用maa刷源石锭时，由于第二层就退，首抓的干员就够用，道中点开招募券招募干员的过程会浪费不少时间。

### 有什么好的想法？

肉鸽设置里添加一个道中掉落的招募券直接放弃掉的选项。

**Comment by SherkeyXD** [comment]
Duplicate of #1555
