### ISSUE TITLE
【Win 10/MAA 4.21/夜神模拟器 7.0.5.8】萨米肉鸽+自动战斗功能，提示截图失败，如反复出现请尝试重启或更换模拟器！

### ISSUE THREAD

**Issue by JokerDoflamingo** [MaaAssistantArknights/MaaAssistantArknights#5887]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

运行环境：
- Win 10
- MAA 4.21
- 夜神模拟器 7.0.5.8

bug描述：
升级4.21后，萨米肉鸽和自动战斗功能反复出现【解图失败，如反复出现请尝试重启或更换模拟器！】，刚开局时能正常运行一段时间，但随后就提示截图失败，重启夜神模拟器和MAA后能稳定复现上述bug。
望修复，谢谢。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12297255/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12297256/gui.log)

**Comment by SherkeyXD** [comment]
你的 asst.log 不包含关键信息，把 asst.log.bak 传上来看看

**Comment by JokerDoflamingo** [comment]
> 你的 asst.log 不包含关键信息，把 asst.log.bak 传上来看看

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12361521/asst.bak.log)
