### ISSUE TITLE
傀影肉鸽只要选了红，就卡在开始行动界面一动不动

### ISSUE THREAD

**Issue by loveushawn** [MaaAssistantArknights/MaaAssistantArknights#5888]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽抓了红以后，换完技能就不动了，可以卡一个晚上

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12297460/gui.log)
asst.log文件1个G了，实在传不上来，大概在8.9上午9.30以后

**Comment by Lancarus** [comment]
用内测版

**Comment by IMFRainI** [comment]
卡的原因是把红当成三个技能的干员点击第三个技能图标位置吞掉了开始关卡的点击动作 
 只要将/MAA/resourse/roguelike/recruitment.json 中对应傀影肉鸽下的地面单切下的红 skill值从3改成2   保存重启 应该就可以了

**Comment by kwuaaa** [comment]
实测内测版可以
