### ISSUE TITLE
MUMU12 水月肉鸽每隔一段时间随机出现点开收藏品浏览界面导致MAA一直“已放弃本次探索”

### ISSUE THREAD

**Issue by Sixsunsl** [MaaAssistantArknights/MaaAssistantArknights#5892]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

就像标题说的  刚刚已经是第三次了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12303396/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12303397/gui.log)
asst.log过大 压缩后也有75M 无法上传   这一次问题出现在今天·也就是9号21:18到21:20之间  我就截了这一段  如果还需要更多请再要求

### 截图

![forbalabala](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56469802/a33b99ed-e6c1-4e02-947f-c4b013a7baf9)

### 还有别的吗？

MUMU12
WIN10 22H2 X64

**Comment by Yumi0606** [comment]
me too,遇到过此问题，卡了3个小时才发现，只能手动关

**Comment by chocosaj** [comment]
卡在這邊+1 已經卡了快20次了，崩潰

**Comment by Sixsunsl** [comment]
> 卡在這邊+1 已經卡了快20次了，崩潰

你看我上面回复  脚本去点掉箭头可以凑合用  不过还是希望能修复吧

**Comment by Yumi0606** [comment]
我现在1270*720分辨率开60帧基本不会有这种情况，不知道模拟器参数是多少？改变模拟器大小可能会改善

**Comment by Sixsunsl** [comment]
> 我现在1270*720分辨率开60帧基本不会有这种情况，不知道模拟器参数是多少？改变模拟器大小可能会改善

这样 我晚上睡前试试  现在是1600*900 240帧  谢谢提供思路

**Comment by chocosaj** [comment]
> 我现在1270*720分辨率开60帧基本不会有这种情况，不知道模拟器参数是多少？改变模拟器大小可能会改善

感謝，我試試看

**Comment by chocosaj** [comment]
> 我现在1270*720分辨率开60帧基本不会有这种情况，不知道模拟器参数是多少？改变模拟器大小可能会改善

我現在用的是1280x720 60fps 
改成1270嗎?

**Comment by Yumi0606** [comment]
是1280x720,打错了哈

**Comment by chocosaj** [comment]
> 复 脚本去点掉箭头可以凑合用 不过还是希望能修复吧

請問是用觸動精靈嗎? 能否分享一下Lua腳本呢? 感謝

**Comment by MaybeHibiki** [comment]
我的解决方法是后台时调高帧数，从15调到30问题频率明显降低了。感觉是截图的问题。大伙们可以去试一下

**Comment by MaybeHibiki** [comment]
update一下，调完后一直到现在没复发过

**Comment by xiaofeiTM233** [comment]
![img](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55832499/b1b1e622-27de-4bd0-8a2c-8ab47e7c37a7)
MuMu12
MAA是最新版本，使用时有**开启迷你窗口**，从下午四点到刚刚（七点，持续将近3个小时未恢复正常，手动停止的）
不知道是不是这个的原因

**Comment by xiaofeiTM233** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55832499/699146a4-53ce-413b-b8dc-c9b6ec6b84c6)
现在一直在点香水
gui日志已经拉到最底了
