### ISSUE TITLE
自动战斗界面显示借助战刷信用步骤的日志

### ISSUE THREAD

**Issue by MeowMeow-Neko** [MaaAssistantArknights/MaaAssistantArknights#5896]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，当进行任务：借助战刷信用时，自动作战界面无法隐藏log，
在之前的版本中，进行此任务后不会显示此任务产生的log
而从未知版本开始，自动战斗界面会显示log
![1691591649643](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/128003229/50247f97-0445-4ca6-b2e1-efb51e79e01f)

### 日志文件

此issue应该不需要log

### 截图

![1691591649643](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/128003229/50247f97-0445-4ca6-b2e1-efb51e79e01f)

**Comment by status102** [comment]
并不认为这是bug，且此处的log并不会进入到gui.log，似乎并不会产生任何问题
