### ISSUE TITLE
刷理智的关卡选择里无当期活动后三关的选项

### ISSUE THREAD

**Issue by LzsHongye** [MaaAssistantArknights/MaaAssistantArknights#5897]
### 说说你遇到的问题？

我使用的是MAA-v4.22.0-beta.1-win-x64版本，下载之后发现没有当期活动的后三关选项，尝试检查更新但是显示获取更新信息失败，于是手动更新了最新的内测版还是没有解决，请问这种情况有什么办法可以解决呢，非常感谢

**Comment by ABA2396** [comment]
每次启动和每天4/16点会访问确定 [是否是最新关卡数据](https://ota.maa.plus/MaaAssistantArknights/api/lastUpdateTime.json)，如果不是会去 [ota服务器](https://ota.maa.plus/MaaAssistantArknights/api/gui/StageActivity.json) 下载关卡数据。要是网不好或者没下下来就没有活动关卡显示了

**Comment by LzsHongye** [comment]
> 每次启动和每天4/16点会访问确定 [是否是最新关卡数据](https://ota.maa.plus/MaaAssistantArknights/api/lastUpdateTime.json)，如果不是会去 [ota服务器](https://ota.maa.plus/MaaAssistantArknights/api/gui/StageActivity.json) 下载关卡数据。要是网不好或者没下下来就没有活动关卡显示了

了解了，感谢回复，至于您说的下载不了关卡数据可能是因为网不好，是不是和我检查更新但是显示获取更新信息失败是同性质的问题？

**Comment by ABA2396** [comment]
检查更新同样走的是ota服务器，应该是同一个问题
