### ISSUE TITLE
萨米肉鸽干员站位完全错误，甚至无法正常通过一个普通关卡

### ISSUE THREAD

**Issue by sola000** [MaaAssistantArknights/MaaAssistantArknights#5898]
### 说说你遇到的问题？

![XE8RR4HWKV{2~GNUM5N{J5J](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/112229099/3c3b0407-1144-49f8-bd3d-47bbc3b18892)
这是部分情况的截取
![VT%`_)SC1(ASA~5}J%4AYU8](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/112229099/7eaef9a4-4e12-4765-aeef-a679c700848c)

![_`%WQ5$_E261PMV01%) 3M0](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/112229099/3f918a4b-4863-4076-b748-9a4ea91af366)
干员的站位和朝向都存在问题，测试了提丰和水陈的站位
在之前曾使用过提丰开局，当时站位属于正常站位，但现在站位只能说是离谱了

**Comment by sola000** [comment]
补一下，用的是内测版的最新版本；
个人认为这也不能算bug，但是之前提丰的站位是很正常的，就想进行一下反馈

**Comment by Lancarus** [comment]
fix in #5946
