### ISSUE TITLE
关于搓玉在基建换班时遇到的问题

### ISSUE THREAD

**Issue by Tomato-cxk** [MaaAssistantArknights/MaaAssistantArknights#590]
基建换班时 只要该制造站生产的产品为源石碎片，那么入驻人员就只会入驻两名，导致供不应求，搓玉收益有所下降（当然不是因懒得手动添人）

**Comment by ABA2396** [comment]
这应该是bug吧，把软件目录下的 `asst.log` 发下看看

**Comment by MistEO** [comment]
从日志看第一个搓玉的站选择了 `源石工艺·β; 源石工艺·β; 源石工艺·α;`
第二个站造赤金选择了 `[ 温蒂-2; 再生能源; 森蚺-2; ]`
第三个站造赤金选择了 `[ 金属工艺·β; 金属工艺·α; 金属工艺·α; ] `

都是选满了三个人的，下次再遇到这个问题的话帮忙截个图吧，包括游戏里制造站的情况，和 maa 界面的截图_(:з」∠)_

**Comment by MistEO** [comment]
v4.2.2-beta.1 修了一个基建滑动失效的问题，可能是这个原因，不过现在也没啥头绪总之先关了，之后再出现再来个日志看看（
