### ISSUE TITLE
活动关卡选择丢失

### ISSUE THREAD

**Issue by Black1312** [MaaAssistantArknights/MaaAssistantArknights#5900]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

关卡选择为活动关后，次日打开MAA后变为“当前/上次”，不关闭MAA，次日变为空白，提供的日志是关闭MAA再打开后变为“当前/上次”

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12307367/asst.bak.log)

### 截图

![{51EA3D52-536D-4dd5-A3BF-91107BA26DF2}](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64343218/5d7e0054-8750-47b6-8efc-f5d5613efb35)
![{4C39845E-CB82-44a1-B349-D7272E020160}](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64343218/6215d087-ba6c-4e2b-b24f-cadf91f9aee9)

### 还有别的吗？

MAA版本：v4.21.1-alpha.1.d060.gd0dc2946d（最新内测的上一个内测版）
模拟器：蓝叠国际pie64
win11

**Comment by IberianCabbage** [comment]
我也经常遇到这种问题，好多次了，挂完MAA回头一看理智还是满的，结果发现是清理智的关卡选项被自动置空了导致直接跳过了这个环节

**Comment by Black1312** [comment]
打开备选关卡可解决这个问题，原因未知
