### ISSUE TITLE
挂机时截图失败，更换模拟器没用

### ISSUE THREAD

**Issue by yang414380863** [MaaAssistantArknights/MaaAssistantArknights#5902]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

提示截图失败，肉鸽挂机(傀影、水月)超过1小时容易复现，表现是模拟器回到桌面，MAA无限循环截图失败，也没有重启

- 时间 2023-08-10 04:03
- 模拟器：雷电9、夜神、BlueStacks5 都是最新版
- win10
- MAA：公测v4.21.0，内测版v4.22.0.xxx也试过

看了一下不知道为什么游戏进程被杀了，已经更换了几个模拟器了，还是有问题，麻烦看下。
另外如果无法解决，能不能给个方案怎么让他提示截图失败的时候自动重启一下？

### 日志文件

体积过大，截了前后两个小时的log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12308407/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12308410/gui.log)

### 截图

![2023-08-10_04-03-37-181_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/9532560/1787dbde-802f-43c4-b173-b86c300d1bde)

**Comment by MistEO** [comment]
> 表现是模拟器回到桌面

明日方舟游戏崩了

**Comment by yang414380863** [comment]
> 

已经是每个模拟器最高档的，至少都是4G了 - -我准备用AVD跟实体手机再试试
