### ISSUE TITLE
日服“获取信用及购物”任务 剩下购物部分未完成

### ISSUE THREAD

**Issue by Joyce-Ethene** [MaaAssistantArknights/MaaAssistantArknights#5907]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![QQ截图20230810220952](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131970654/3900dd9b-e495-4be1-b25b-a9fb25500f78)

访问好友结束后即显示任务完成，不进入信用商店。
（截图中右上角信用领取和购买是我手动）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12317186/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12317187/gui.log)

时间点 22:00:30-22:02:23

**Comment by AmemiyaMiomy** [comment]
日服这个问题好久了，访问完好友连商店都不会点开，也不知道是不是脚本没找到商店图标
