### ISSUE TITLE
特别关注的四字干员无法被OCR识别（特别关注图标被识别为其他字符）

### ISSUE THREAD

**Issue by ShanshanHY** [MaaAssistantArknights/MaaAssistantArknights#5908]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

无法识别被标记的“艾雅法拉(《艾雅法拉)”，伊芙利特(必伊芙利特)，但三字干员可正常识别(刻俄柏)

此bug曾在 #1617 提到过，并标明已修复，但MAA最新版仍可复现

### 日志文件

[Debug记录](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12317816/asst.log)

### 截图

Debug Log 截图：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29966961/d1bb8ed6-1de8-4edf-bc39-c737248ebe00)

游戏内干员界面截图：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29966961/067c7458-da75-4bbd-bead-22b3a46c787e)

MAA主界面截图：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29966961/4fd0adde-61e9-4c18-99af-d7c39fa20bd6)

### 还有别的吗？

操作系统：Win10 22H2
模拟器：MuMu12最新
adb：Google官方最新platform-tools

**Comment by cenfusheng** [comment]
《 的问题已修复，必 不知道该怎么修，等待大佬决定

**Comment by MistEO** [comment]
8ca76de6f89a88ea9a817f9b30644315f5df0e16 fixed
