### ISSUE TITLE
无法进入萨米肉鸽流程线，表现为不选择难度

### ISSUE THREAD

**Issue by AldousShou** [MaaAssistantArknights/MaaAssistantArknights#5912]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

**已在issue中找到类似bug，表现类似于#5879，但有差异**，因此开一个新的issue

萨米肉鸽无法自动选择难度进行对局，需要手动点选
（如果需要手动点选，那为什么还要maa的自动肉鸽刷等级呢）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12321371/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12321373/gui.log)

**Comment by SherkeyXD** [comment]
> 如果需要手动点选，那为什么还要maa的自动肉鸽刷等级呢

选等级手动点一下的事，为什么还要maa代劳呢
