### ISSUE TITLE
自动战斗作业，煌无法部署，手动部署后作业卡死

### ISSUE THREAD

**Issue by 780753368** [MaaAssistantArknights/MaaAssistantArknights#5916]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，mumu12模拟器win11，最新内测版MAA，在EX-7和EX-8中均出现此问题，反复在待部署区的煌上点击但不部署

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12322923/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12322924/gui.log)

**Comment by 780753368** [comment]
作业地址：maa://25287，maa://25302，评论区无类似问题反馈

**Comment by cenfusheng** [comment]
煌的文字识别问题，已修复
