### ISSUE TITLE
ADB进程有时候无法启动

### ISSUE THREAD

**Issue by xxyz30** [MaaAssistantArknights/MaaAssistantArknights#5917]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

点击开始后，有时候MAA进程下没有adb子进程，此时无法连接模拟器，会卡住。
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/81208875/5d793185-1251-4e78-a22b-295631f1328b)
然后点击停止也要卡好久才能停止掉。
设置里的强行替换adb会这样
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/81208875/111d39c4-4a53-45f2-ba53-472f008aa21c)
但是如果把进程杀掉重启就会好。
这是间歇性会有这种问题，不知道为啥

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12323264/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12323265/gui.log)
时间点就在最后23：56

### 还有别的吗？

蓝叠国际版

**Comment by xxyz30** [comment]
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/81208875/7a1d1025-76e2-4400-a01f-49e793eae9e7)
预期肯定这样的，这是任务管理器杀掉后重新开的，就好了（

**Comment by a78239636** [comment]
有遇到类似情况，启动后一直在连接adb, 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34701894/b375f965-6b65-4aae-976f-c73d36be4ecf)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34701894/b2835535-8756-4cfd-b82b-c2526c42cab8)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34701894/184332b3-0ce8-4b2e-9470-05b7a3e8dbf8)
