### ISSUE TITLE
Integrated Strategies: Trader shopping Multi-Template detection issue

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#5919]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

The trader store currency:   ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/621ac2db-7222-468d-8777-8a22e5d0cd22) is the starting point for the multi-template matcher that tries to detect the name of the item.

ISSUE: when an item is discounted or has a higher price, the currency is shifted which means that the detection RECT of the PluginTask is also shifted. From the image we can easily see this. The "Extra-Pungent Coffee Beans" are not getting detected correctly, because the currency is not in the expected spot.

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/4215d2aa-0dfa-4d1e-91b3-d2b1337ea9e7)
This screenshot is made with the help of the Coordinate Tool.

As a kind-of-quick-fix-try I've added some pretty heavy regex such-as: 
```
                ".*Life Point.*",
                "目标生命"
```
so that even if it gets overlapped like: OTHER_ITEMLife Point, the OcrReplace will still work, disregarding what was before.
The remaining issue is that for short names there's no problem, for longer names they won't get detected.

SUGGESTION / FIX:
Instead of looking for: ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/621ac2db-7222-468d-8777-8a22e5d0cd22) why not look for: ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/ca8c41e1-0efc-40e8-969e-315819df17bb), obviously adapting the different RECT.

### Log files

Line: 876
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12323393/asst.log)
7

**Comment by Constrat** [comment]
Bad news: thanking the devs... when there's a discount or an overprice ALSO the "Price" doesn't stay the same. It moves a little bit which is not a huge issue, but it changes the dimension of "Price" by a small 15%... This doesn't seem much I don't think the template matcher understands it... Also because there's a background, I've tried using the maskRange but I can't manage to find a solution.

**Comment by Constrat** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/350875b6-1fc1-40ed-b207-c0d74cf05fc5)
This has to be some sort of joke... Anyway, I've been trying some methods to detect the new "Price" but nothing really works...
I think the only thing left is having two different tasks (This is not that tragic because in a way it makes sense)
Considering the BIGGER "Price" the OCR ROI should be changed (even a small bit) so this would hit two things with one stone... But I have no idea how to make it detect two different images, as I can't see any task calling these two with "next": [""]... I think this is controlled from the .cpp MaaCore counterpart.

@ABA2396 any suggestion is greatly welcomed as I'm getting to a dead end.

**Comment by ABA2396** [comment]
Can the term "Price" be recognized accurately by OCR? If it's possible, perhaps the corresponding "algorithm" for the server task can be adjusted separately.
for instance:
tasks.json
```
"RoguelikeTraderShopping": {
    "template": "Roguelike@TraderRandomShopping.png",
    "templThreshold": 0.7,
    "roi": [
        480,
        240,
        750,
        280
    ],
    "maskRange": [
        1,
        255
    ]
},
"RoguelikeTraderShoppingOcr": {
    "algorithm": "OcrDetect",
    "text": [],
    "roi": [
        -120,
        -160,
        190,
        35
    ],
    "ocrReplace": [
        [
            "指路.*",
            "指路鳞"
        ]
    ]
},
```
global\YoStarEN\resource\tasks.json
```
"RoguelikeTraderShopping": {
	"algorithm": "OcrDetect",
	"text": [
		"[Pp]rice" 
	],
    "roi": [
        new roi A
    ]
},
"RoguelikeTraderShoppingOcr": {
    "roi": [
        new roi B
    ],
    "ocrReplace": [
		...
    ]
},
```
By the way, if the inherited "algorithm" field is different, then the parameters of the derived class are not inherited (only the parameters defined by TaskInfo are inherited).
I'm not sure if this can solve the problem, but I think it's an approach worth considering.

**Comment by ABA2396** [comment]
Of course, if this problem exists on all servers, just change it all to ocr.

**Comment by Constrat** [comment]
I've tried before using the OcrDetect algorithm... It crashed my MAA without any exception. I'll try it again (maybe I've missed something)



> Of course, if this problem exists on all servers, just change it all to ocr.

I think it does because the currency shift symbol shouldn't depend just on the language used. If I can fix it for sure on the EN I'll be sure to take a look at other servers. I can only check with a CN account as I don't have the others, but I can ask some contributors here for the chars needed. If you could comment these chars it would help me a lot ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/e722d2c5-0560-4caa-b73a-2e9380ef4563)

**Comment by ABA2396** [comment]
cc @MistEO

**Comment by Constrat** [comment]
When OcrDetect is used. The detected text new ROI starts from the top left ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/3dc9f004-fc12-40f8-8d94-d05b6ad3efca) as [0,0]?

**Comment by ABA2396** [comment]
We have a new discussion results: by matching the triangle of the picture to give the digital coordinates, and then regular matching digital coordinates to calculate the lower right corner coordinates to find the text coordinates, in this case should be able to avoid a large area of ocr looking for price leads to inaccurate results, that is, to change the content will be more.

**Comment by Constrat** [comment]
About 30 minutes ago I was desperated and I tried looking for just this: ![Roguelike@TraderRandomShopping](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/f2e185a5-3ac7-4180-9e78-7980658dbb6a) which could have worked but then I noticed it tried to detect after every battle ending because it was searching for every "e" possible XD. I'm trying the OcrDetect as I had some issues calculating the new roi b to make sure every combination would work.

**Comment by Constrat** [comment]
I've just tried using the OcrDetect... Still crashes without any warnings 
```
[2023-08-12 20:19:08.956][TRC][Px8524][Tx8638] asst::PipelineAnalyzer::analyze Mizuki@Roguelike@TraderRandomShopping
[2023-08-12 20:19:09.033][TRC][Px8524][Tx8638] match_templ | Roguelike@TraderRandomShopping.png score: 0.936544 rect: [ 943, 259, 34, 20 ] roi: [ 480, 240, 750, 280 ]
[2023-08-12 20:19:09.033][INF][Px8524][Tx8638] Assistant::append_callback | SubTaskStart {"class":"asst::RoguelikeShoppingTaskPlugin","details":{},"subtask":"RoguelikeShoppingTask","taskchain":"Roguelike","taskid":2,"uuid":"040a9c4eade48df9"}
[2023-08-12 20:19:09.033][TRC][Px8524][Tx8638] asst::RoguelikeShoppingTaskPlugin::_run | enter
```

**Comment by Constrat** [comment]
Ok so... It still crashes but... Goodnews (The detection looks a bit wonky because I couldn't screenshot it in time so I have this image as 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/cc464174-d1d4-40d6-8893-ee97a07b985d)
 To get to this point I had to copy this from tasks.json
```
    "Roguelike@TraderRandomShopping": {
        "Doc": "该任务注册了 RoguelikeShoppingTaskPlugin，若是点完了仍在当前界面，说明没啥要买的，直接离开商店（next 里的 PhantomStageTraderLeave）",
        "action": "ClickSelf",
        "templThreshold": 0.7,
        "cache": false,
        "roi": [
            480,
            240,
            750,
            280
        ],
        "rectMove": [
            -40,
            -100,
            20,
            60
        ],
        "next": [
            "Roguelike@TraderRandomShoppingConfirm",
            "Roguelike@TraderRandomShoppingCancel",
            "Roguelike@ChooseOperFlag",
            "Roguelike@StageTraderLeave",
            "Roguelike@StageTraderLeaveConfirm"
        ],
        "maskRange": [
            1,
            255
        ]
    },
```
To this in global/YostarEN/resources/tasks.json
```
    "Roguelike@TraderRandomShopping": {
        "algorithm": "OcrDetect",
        "text": [
            "Price"
        ],
        "action": "ClickSelf",
        "templThreshold": 0.7,
        "cache": false,
        "roi": [
            564,
            238,
            657,
            229
        ],
        "rectMove": [
            -40,
            -100,
            20,
            60
        ],
        "next": [
            "Roguelike@TraderRandomShoppingConfirm",
            "Roguelike@TraderRandomShoppingCancel",
            "Roguelike@ChooseOperFlag",
            "Roguelike@StageTraderLeave",
            "Roguelike@StageTraderLeaveConfirm"
        ]
    },
```
Still crashes calling the .cpp task
```
[2023-08-12 20:58:28.747][TRC][Px8d40][Tx9934] asst::PipelineAnalyzer::analyze Mizuki@Roguelike@TraderRandomShopping
[2023-08-12 20:58:28.937][TRC][Px8d40][Tx9934] asst::WordOcr [{ Price: [ 416, 0, 32, 18 ], score: 0.997799 }, { Price: [ 622, 2, 33, 17 ], score: 0.998039 }, { 8: [ 211, 16, 30, 37 ], score: 0.999273 }, { Price: [ 212, 3, 30, 15 ], score: 0.998597 }, { 4: [ 409, 18, 36, 32 ], score: 0.999953 }, {  16: [ 572, 14, 82, 44 ], score: 0.922749 }, { ciency: [ 0, 81, 43, 21 ], score: 0.995679 }, { Bend Spears-Advancement: [ 68, 84, 175, 15 ], score: 0.975515 }, { Rusted Blade- Training: [ 273, 82, 177, 19 ], score: 0.948648 }, { Fatal Bolts- Advancemer: [ 481, 84, 174, 15 ], score: 0.959753 }, { : [ 343, 158, 28, 23 ], score: 0.000000 }, { Price: [ 1, 210, 37, 18 ], score: 0.997387 }, { Price: [ 209, 212, 33, 15 ], score: 0.998033 }, { Price: [ 418, 213, 31, 14 ], score: 0.998230 }, { Price: [ 624, 213, 32, 14 ], score: 0.998105 }] by OCR Pipeline , cost 189 ms
[2023-08-12 20:58:28.937][TRC][Px8d40][Tx9934] Proced [{ Price: [ 980, 238, 32, 18 ], score: 0.997799 }, { Price: [ 1186, 240, 33, 17 ], score: 0.998039 }, { Price: [ 776, 241, 30, 15 ], score: 0.998597 }, { Price: [ 565, 448, 37, 18 ], score: 0.997387 }, { Price: [ 773, 450, 33, 15 ], score: 0.998033 }, { Price: [ 982, 451, 31, 14 ], score: 0.998230 }, { Price: [ 1188, 451, 32, 14 ], score: 0.998105 }]
[2023-08-12 20:58:28.937][INF][Px8d40][Tx9934] Assistant::append_callback | SubTaskStart {"class":"asst::RoguelikeShoppingTaskPlugin","details":{},"subtask":"RoguelikeShoppingTask","taskchain":"Roguelike","taskid":1,"uuid":"040a9c4eade48df9"}
[2023-08-12 20:58:28.937][TRC][Px8d40][Tx9934] asst::RoguelikeShoppingTaskPlugin::_run | enter
```
The **189ms** definetly isn't great... Considering this is just the Coordinate detection...

I'm starting to think that for Overseas servers we could just detect everything and try to OcrReplace directly...

**Comment by ABA2396** [comment]
> I've just tried using the OcrDetect... Still crashes without any warnings

My bad, I looked at the source code and the plugin is registered to look for an OcrDetect based on the MatchTemplate, I'll have to figure out how to change that.

**Comment by Constrat** [comment]
![Screenshot 2023-08-13 104943](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/5f2371db-227e-4198-9235-6438e6f619ef)

This looks good, actually very good because now for items that go to a new line don't get picked up together so it's just a question of regexing the max chars. One small issue is the ROI for the detection of the "Price" is a bit too small 

While this 
```
    "RoguelikeTraderShoppingOcr": {
        "algorithm": "OcrDetect",
        "text": [],
        "roi": [
            388,
            65,
            871,
            304
        ],
        "ocrReplace": [
            [
                "指路.*",
                "指路鳞"
            ]
        ]
    },

```
`388,65,871, 304` is a bit too big

**Comment by ABA2396** [comment]
Triangles were previously used because ppocr's model detection wasn't particularly well adapted, and after re-training it has been able to largely meet the requirements. The approach now is to recognise the text and then use an offset to identify if a triangle exists below the text, and if it doesn't it means that a purchase has been made or something else is recognised (e.g. selling price and "price"). The bottom is not recognised because it is only framed below the second line ([388,65,871,304]), But there's no need to identify anything else to judge now, is there?.

**Comment by Constrat** [comment]
No, not really it's just that `406, 90, 825, 263` for example could lower the timings as it's tighter and doesn't try to detect the top row of debuffs 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/115e9a17-11be-47e3-aae5-b3df2791a476)
