### ISSUE TITLE
萨米肉鸽无法识别关卡

### ISSUE THREAD

**Issue by t1075885574** [MaaAssistantArknights/MaaAssistantArknights#5921]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽进入战斗后无法识别关卡，不部署干员，debug文件夹未找到相关截图

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12326657/asst.log)

### 截图

![捕获](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38479367/189938b3-718a-4f8c-b98e-42f536e25de4)

### 还有别的吗？

mumu12，4.22.0-beta1

**Comment by Roland125** [comment]
13:25:20.725 ocr识别结果是个 “{ _"
后续自然是调不出对应的作战协议，导致无操作。
这种可能是偶然发生的卡顿造成的，没办法百分百避免
可以观察一下出现频率，如果频繁出现的话，尝试调高模拟器性能设置，或者在游戏里设置降低方舟的性能
