### ISSUE TITLE
自动战斗一个干员组内如果有多个不同职业分支的干员，且未拥有某种职业干员的时候无法选中干员

### ISSUE THREAD

**Issue by RimuruChan** [MaaAssistantArknights/MaaAssistantArknights#5928]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗一个干员组内如果有多个不同职业分支的干员，且未拥有某种职业干员的时候无法选中干员。
比如我的干员组内有灵芝和能天使，如果我没有能天使，而maa先去寻找能天使，就会找不到干员卡死，而不是切换到辅助分支再找干员。

### 日志文件

无

**Comment by Lancarus** [comment]
更新到最新内侧版,昨天下午修复了
