### ISSUE TITLE
是否可以开发自动喂经验书的功能，一个个点的好累

### ISSUE THREAD

**Issue by sweetasaki** [MaaAssistantArknights/MaaAssistantArknights#593]
可以设置几个级别，喂满，60级等等。

**Comment by aa889788** [comment]
经验书是能长按的啊

**Comment by zhongfly** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/88

我之前提过了，作者之后可能会做

> 经验书是能长按的啊

但最多一次40个啊，要反复长按操作，特别是升到精二90级，真是要重复很多次

**Comment by ABA2396** [comment]
这还要考虑升到几级，经验溢出啥的问题

**Comment by sakuraxp** [comment]
用模拟器录个操作，循环放几次就好了。

**Comment by lhhxxxxx** [comment]
fixed by yj
