### ISSUE TITLE
繁中基建

### ISSUE THREAD

**Issue by sadeer2014** [MaaAssistantArknights/MaaAssistantArknights#5931]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

繁中基建找不到鴻雪

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12328816/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12328817/gui.log)
12:29的那個位置

**Comment by Roland125** [comment]
见 12:29:12.258 识别结果是 嗚雪 
如果这个识别结果是稳定的 添加一个等价规则应该就行了
PR合进去之前可以自行修改自定义基建协议里的 鸿雪 为 嗚雪 
应该就能正常跑起来了

**Comment by Roland125** [comment]
或者可以是自行在繁中服的resource文件夹下新建一个ocr_config文件 也能正常用 不碍事

**Comment by Roland125** [comment]
@MistEO 这样应该对了？

**Comment by Constrat** [comment]
I'll change it for you.

**Comment by Roland125** [comment]
thanks. @Constrat
