### ISSUE TITLE
mumu12 maa 操作了错误的页面

### ISSUE THREAD

**Issue by 1152316061** [MaaAssistantArknights/MaaAssistantArknights#5932]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

- 操作系统：win10 22h2
- 模拟器版本：mumu12 版本v3.5.6(1899)
- maa版本：4.21.0，4.22.0-beta1，4.22.0-beta.1.d041.g9747ac6f6
- 问题：
     - maa卡在开始任务：StartUp
     - 翻阅asst.log，发现maa ocr的页面是mumu12的首页，并非游戏页面
     - 此时模拟器是处于游戏页面，并没有切换到首页上
- 采取过的措施：
   - 重启电脑
   - 重装MAA
   - 强制替换adb
   - 切换触控模式

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12328854/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12328855/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29331166/d5275036-1054-4224-82fd-afeb83f8413a)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29331166/ef8449c1-3b6a-4367-886f-aa4ca0760816)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29331166/c57278c8-c80f-420b-a1cb-0767c5d2c850)

**Comment by Roland125** [comment]
这可能是一个已知的冲突
Mumu12的设置里有个后台模式 需要关掉 
启用的话就会导致只能截图到mumu的桌面
可以先检查一下是不是这个原因

**Comment by 1152316061** [comment]
后台模式关闭+强制替换adb已解决
