### ISSUE TITLE
纯烬艾雅法拉自动编队失败

### ISSUE THREAD

**Issue by Black1312** [MaaAssistantArknights/MaaAssistantArknights#5934]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

作业代码：maa://25515
必须放在干员列表上面一排且未特别关注才可以正常编队，其余情况全部“查无此人”

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12328976/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64343218/0a288b00-8dcc-47df-8c3f-42aa708ad1c3)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64343218/174ff12f-f8cb-4b4e-8b0f-f2e79f1a0182)

### 还有别的吗？

MAA版本：v4.22.0-beta.1.d041.g9747ac6f6
蓝叠安卓P 64位

**Comment by SherkeyXD** [comment]
特别关注已经修了

**Comment by Lixuhuilll** [comment]
同问题，纯艾根本不识别，就算没特别关注也一样，原来是必须在上面那排才能被识别吗。

**Comment by Lancarus** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12387256/asst.log)

**Comment by Constrat** [comment]
Similar to: #5235 .
Unfortunately the longer the names the harder it is to detect them.
Usually removing the first character does the job but it looks this isn't enough. (I'm scared as to what the official EN name will be)

**Comment by Lancarus** [comment]
#6005 应该是一个问题
