### ISSUE TITLE
adb错误

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#5937]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

点击开始运行后adb报错，强制替换adb后报如下错误：
MAA 遇到了问题
文件“C:\Users\zz\Desktop\Ark\MAA-v4.10.5-win-x64\adb-windows.zip.temp”正由另一进程使用，因此该进程无法访问此文件。
解决方案
出现未知错误
详细信息
System.IO.IOException: 文件“C:\Users\zz\Desktop\Ark\MAA-v4.10.5-win-x64\adb-windows.zip.temp”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalDelete(String path, Boolean checkHost)
   在 MaaWpfGui.Services.Web.HttpService.<DownloadFileAsync>d__11.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.<ReplaceADB>d__467.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12329295/asst.log)

**Comment by Black1312** [comment]
MAA全部删除，下载最新版重新解压，管理员权限运行，首次启动后点击替换ADB，如果提示无法替换，adb已被占用，请重启电脑，不打开模拟器，管理员启动MAA点击替换ADB
