### ISSUE TITLE
基建伊内斯识别bug

### ISSUE THREAD

**Issue by lbsdyy** [MaaAssistantArknights/MaaAssistantArknights#5938]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa基建换班识别不到伊内斯 使用精一立绘

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12329477/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12329478/gui.log)

### 截图

![S0(ECC)B9WZ88GE~@H_SG0M](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71543484/65b612d6-7094-4dab-bffd-1b793d7210a7)

![TOKEH{$8)}XF@2LUKM3%{(M](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71543484/96515f87-8632-45f9-8efd-5e1bc564465b)

### 还有别的吗？

蓝叠模拟器

**Comment by ABA2396** [comment]
是伊内丝不是伊内斯
