### ISSUE TITLE
alpha/v4.22.0-beta.1.d065.g0fc5374c3 Shutdown Emulator failed

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#5939]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/19f28488-63c2-4f23-8444-ef15518e00c8)

### Log files

Looking at gui.log `Failed to close emulator: Index was outside the bounds of the array.` Similar to #5930?

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12329515/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12329523/gui.log)

### Anthing else?

Win10, BlueStacks 5.12.1.1001 P64, MAA alpha/v4.22.0-beta.1.d065.g0fc5374c3. Latest beta was working fine.

**Comment by ABA2396** [comment]
fcc8f84290e4589157ef85e6ec6d22ace1421070 fixed

**Comment by Constrat** [comment]
Just tried it, looks good! Thanks.
