### ISSUE TITLE
希望能依据仓库刷理智

### ISSUE THREAD

**Issue by why002** [MaaAssistantArknights/MaaAssistantArknights#5941]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

仓库识别材料，与用户设置比较，自动规划如何刷关

### 有什么好的想法？

企鹅物流不是有刷图规划器吗，MAA不是有仓库识别（尽管还在测试）
能不能添加设置设定我想获得的材料数量，MAA自动获取刷图规划器的数据帮我刷对应关卡

**Comment by cenfusheng** [comment]
暂无该计划。
