### ISSUE TITLE
萨米肉鸽选择高规格分队，无法招募

### ISSUE THREAD

**Issue by ygfeg** [MaaAssistantArknights/MaaAssistantArknights#5943]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽选择高规格分队，会出现四张招募券（屏幕截图 2023-08-14 135251），maa似乎识别不了四张招募券的情况，会自动放弃本次探索（屏幕截图 2023-08-14 135402），无法运行

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12331812/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12331816/gui.log)

### 截图

<img width="946" alt="屏幕截图 2023-08-14 135251" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110211480/43e76f78-8486-4b89-8a62-a62caf69bc51">
<img width="639" alt="屏幕截图 2023-08-14 135402" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110211480/72f46909-b814-47ee-a5ca-3a659c3aebd6">

**Comment by SherkeyXD** [comment]
尚未适配

**Comment by SherkeyXD** [comment]
Duplicate of #5419
