### ISSUE TITLE
与模拟器链接出现问题，无法正常启动，提示分辨率获取失败

### ISSUE THREAD

**Issue by netofill** [MaaAssistantArknights/MaaAssistantArknights#5949]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

提示链接失败后模拟器被关闭，并且无法再打开模拟器，重启电脑后能打开模拟器但依然无法链接。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12336072/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12336076/gui.log)
8.14  晚上9:00左右

### 截图

![屏幕截图 2023-08-14 222757](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142239306/57d71656-53b6-4403-800e-ee45bc3823cf)

### 还有别的吗？

我不太懂代码，如果有什么说的不清楚我会尽量补充，希望问题可以解决。之前都是正常使用的，今天8.14下午9:00左右发现的情况。ADB路径和地址应该都对

**Comment by wxmtt** [comment]
xd，有办法了吗
