### ISSUE TITLE
任务完成后增加选项的建议

### ISSUE THREAD

**Issue by deepsea666** [MaaAssistantArknights/MaaAssistantArknights#5950]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

希望可以增加一个任务完成后切换配置的选项，昨天上午我在定时任务自动更换基建后忘记把方案切换为默认，直接在基建方案中开始一键长草，导致昨天下午和晚上本该自动换班的基建变成了自动一建长草，早上起来基建一半红脸了

### 有什么好的想法？

我希望增加一个选项，可以让定时执行的方案完成后自动切换至指定方案（不要直接执行方案中打钩的任务）

### 其他内容

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/21211204/45a7bff0-0b61-4eaa-9747-c04bb9f4046b)

**Comment by WSMTBG** [comment]
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/d63636ab-e720-4fde-93ee-86650b7ada82)
这个吗（）

**Comment by deepsea666** [comment]
用这个功能切换回指定配置的话会执行该配置里已经打了勾的任务，比如自动肉鸽，我刚才在测试用这个的时候损失了一把打到一半的N15，他自动给我放弃探索存源石锭去了

**Comment by ABA2396** [comment]
> 用这个功能切换回指定配置的话会执行该配置里已经打了勾的任务，比如自动肉鸽，我刚才在测试用这个的时候损失了一把打到一半的N15，他自动给我放弃探索存源石锭去了

就是这样设计的啊）你要不想打肉鸽就把那个配置里的肉鸽取消掉
