### ISSUE TITLE
信用商店购物时如有干员合同无法购物

### ISSUE THREAD

**Issue by why002** [MaaAssistantArknights/MaaAssistantArknights#5953]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

信用商店累计消费满一定信用会出现干员合同（讯使、嘉维尔、坚雷），MAA在打开购买时会点到其他地方（例如进干员详情界面）

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12341710/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12341711/asst.log)

### 还有别的吗？

MuMu12 v3.5.3
Windows 10 家庭版 22H2

**Comment by ABA2396** [comment]
把这仨人写到黑名单里吧
