### ISSUE TITLE
可否为刷源石锭提供一套额外的通关逻辑以提升刷取效率？

### ISSUE THREAD

**Issue by haoxiongliu** [MaaAssistantArknights/MaaAssistantArknights#5955]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

maa要8~10min一轮，而人手动刷可以做到平均4~6min一轮
可优化的差距主要在：
1. 人可以优先选择打架少的路径
2. 人可以不管所有战斗后掉落品，直接走人
3. 人不会投资完之后买道具并进入下一层看预知，而是直接左上角退出
其余还有战斗内不点技能、不上多余干员等小策略，但影响较小
作为maa在肉鸽最为常用的功能，可否辛苦优化？

### 有什么好的想法？

在刷源石锭时
1. 制定特殊路径选择逻辑
2. 战斗后选择直接走人
3. 投资完直接左上角退出

**Comment by Yumi0606** [comment]
1.关于直接退出:
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136778556/189ec633-147d-4641-80af-11b368126abb)
2.maa暂不支持多种配置文件的切换,但是你可以手动修改或者找改好的encounter.json替换
3.战斗后直接走人的逻辑还没有

**Comment by haoxiongliu** [comment]
> 1.关于直接退出: ![image](https://user-images.githubusercontent.com/136778556/260882599-189ec633-147d-4641-80af-11b368126abb.png) 2.maa暂不支持多种配置文件的切换,但是你可以手动修改或者找改好的encounter.json替换 3.战斗后直接走人的逻辑还没有

1. 我指的是可以在一层商店直接点左上角退出，不用等买其他藏品以及进入第二层
2. 只找到stage_encounter.json，看起来只是配置节点内选项的文件

**Comment by SherkeyXD** [comment]
> 1. 我指的是可以在一层商店直接点左上角退出，不用等买其他藏品以及进入第二层

进入第二层而不直接退出的逻辑是在 #1555 确定的，这段时间也很多人提到这个问题，我们会考虑要不要改

> 2. 只找到stage_encounter.json，看起来只是配置节点内选项的文件

那个是配置不期而遇所选择的节点的，而且也不能根据选择的策略进行更改

**Comment by Lancarus** [comment]
已适配
