### ISSUE TITLE
MacOS M1版使用保全派驻作业时无法自动调配干员

### ISSUE THREAD

**Issue by Zhou1zheng2** [MaaAssistantArknights/MaaAssistantArknights#5958]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

实验了多个保全派驻的json作业，均没法自动调配干员，感觉应该不是json的问题，麻烦大大们修下，保全太坐牢了。

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12346240/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12346246/asst.log)

时间在8月15日23:10之后应该都是

### 截图

<img width="1485" alt="Screenshot 2023-08-16 at 00 19 27" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/37805117/96095465-a7fd-4285-a40f-2960fc3d2ef4">

### 还有别的吗？

使用Playcover；M1 MacOS 13.4.1；日常功能都正常

**Comment by MistEO** [comment]
和 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5599 类似的问题，mac 上需要单独对这个按钮截图并加载配置文件，开发组现在没人弄，等个佬带带

**Comment by MistEO** [comment]
麻烦提供一张 mac 上这个界面的原图（使用 adb 截图而不是基于窗口的截图）

**Comment by Zhou1zheng2** [comment]
> 麻烦提供一张 mac 上这个界面的原图（使用 adb 截图而不是基于窗口的截图）

多谢大佬关注到。是需要调配界面的截图吗，以及如何使用adb进行截图呢，我使用的mac
