### ISSUE TITLE
是否可以在剿灭模式的选择中细化选项，比如可以选择任意一个剿灭

### ISSUE THREAD

**Issue by Farewell-Elysia** [MaaAssistantArknights/MaaAssistantArknights#5959]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by SherkeyXD** [comment]
Duplicate of #5317
