### ISSUE TITLE
feat: 启动明日方舟支持

### ISSUE THREAD

**Issue by bakashigure** [MaaAssistantArknights/MaaAssistantArknights#596]
催催玛丽，什么时候做从模拟器启动明日方舟的支持，包括但不限于国服、B服、日服、国际服以及四个服务器在WSA中的版本
![image](https://user-images.githubusercontent.com/33803916/170820395-e980fcf6-9e9f-4a1d-b58f-a1d73e80cc41.png)

**Comment by MistEO** [comment]
WSA 有什么不一样的啊

~~来个命令~~

**Comment by MistEO** [comment]
韩服呢，气冷抖！

**Comment by bakashigure** [comment]
> 来个命令

我不到啊

**Comment by aa889788** [comment]
> WSA 有什么不一样的啊
> 
> ~来个命令~

`adb shell am start com.hypergryph.arknights/com.u8.sdk.U8UnityContext`

**Comment by aa889788** [comment]
不同服务器应该是包名不同，可以考虑修改startup任务，传入服务器启动activity，也可以考虑在增加一个`launch`任务，在startup之前执行

**Comment by one-pyy** [comment]
(做成启动执行自定义命令+结束执行自定义命令?)
