### ISSUE TITLE
萨米肉鸽商店不买任何东西离开

### ISSUE THREAD

**Issue by Yumi0606** [MaaAssistantArknights/MaaAssistantArknights#5961]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最新版本,刷等级模式,有东西可买,但是还是直接离开了,看了log文件,这次连招募券跳过的英文原因都没有
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136778556/26d39d86-db89-4ef2-b642-5b2aeeaa9137)
就拿光谱分析仪举例,shopping里面有这个商品,没有理由不买的
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136778556/7d345fb6-bb2b-4488-97bc-b2536df8508b)
就算这个不买,招募券优先级比它高,可还是不买(队伍里是有白面鸮的)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12354872/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12354874/asst.log)

### 还有别的吗？

Mumu12
Win10

**Comment by Lancarus** [comment]
fixed in #6321
