### ISSUE TITLE
自动编队干员组不同职业时切进近卫翻找而不是全部

### ISSUE THREAD

**Issue by cenfusheng** [MaaAssistantArknights/MaaAssistantArknights#5962]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

比如干员组：铃兰、仇白
MAA现在会优先去近卫里选仇白，哪怕它等级很低是精零的，而不会去对比铃兰的练度，这个行为是损害“干员组兼容不同box”的初衷的，反而会降低作业的兼容性。
建议改为“干员组内职业不同时取消职业选择，在所有干员内寻找该干员组成员，并选择练度最高的”。

（ps.如果改为【干员组内职业不同时，按干员组首次出现该职业的顺序，寻找该职业等级最高干员】也很好，是对另一个方向的优化，因为写在第一个的一般是首选、有更多同职业的选项，写在末尾的一般是“勉强可替换”。但我觉得没有所有职业对比练度好用。

总之现在干员组的选法很不符合作业人想法，救救————————

### 日志文件

如题

**Comment by cenfusheng** [comment]
@MistEO 玛丽考虑考虑【打滚】现在的不同职业的干员组好难用【打滚】

**Comment by cenfusheng** [comment]
我超，标题应该是“无法找更合适的/练度更高的”干员，我字呢，怎么改啊，我不会

**Comment by Yumi0606** [comment]
> 我超，标题应该是“无法找更合适的/练度更高的”干员，我字呢，怎么改啊，我不会

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136778556/fa256f32-2ecd-4db5-ac4f-e1fd8c08d684)

**Comment by cenfusheng** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12356289/asst.log)
现在真的有bug了，真的“无法找到干员了”了，标题不用改了。
maa://25675 干员组假日威龙陈/林/焰影苇草，它在近卫里翻了两遍，我手动切到全干员后才顺利选了 假日威龙陈

**Comment by cenfusheng** [comment]
> > 我超，标题应该是“无法找更合适的/练度更高的”干员，我字呢，怎么改啊，我不会
> 
> ![image](https://user-images.githubusercontent.com/136778556/260915602-fa256f32-2ecd-4db5-ac4f-e1fd8c08d684.png)

谢谢，原来edit是编辑

**Comment by cenfusheng** [comment]
> 内测版修过了啊，e 佬之前提的

就是内测版，根据e佬的思路修过之后出现的问题，玛丽再读一遍呜呜呜，现在这个实现不好————

**Comment by cenfusheng** [comment]
> 内测版修过了啊，e 佬之前提的

以及现在浊心斯卡蒂/阿米娅优先去近卫翻，假日威龙陈/林/焰影苇草还是先去近卫翻【挠挠头】
