### ISSUE TITLE
能天使午夜邮差皮肤识别有误

### ISSUE THREAD

**Issue by LyeeH** [MaaAssistantArknights/MaaAssistantArknights#5964]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

能天使装备了午夜邮差皮肤之后，经常选中了之后继续找能天使，感觉是个bug

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12356491/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12356492/gui.log)

看不太懂log，有点冗长还有很多重复的信息，但是大概估计是在23:37左右。

具体是抄作业 maa://25589 打SL-S-2
1. 第一次发现失败了
2. 以为是桃子的模组没开，就去打了下桃子的模组
3. 然后再一次打SL-S-2的时候就一直卡在选完能天使继续找人的情况
4. 换另外一个皮肤之后，打了一次打过了
5. 然后把皮肤换回午夜邮差，打突袭又失败了

大概的时间线就是这样把，希望能帮你们定位到bug的地方。之前其实出现过同样的问题，也是能天使的这个皮肤，换了一个就不会了。

### 还有别的吗？

模拟器是bluestack 5.11.16513 P64
操作系统版本号是22000.2295 windows 11

**Comment by cenfusheng** [comment]
日志显示找能天使了，可排除文字识别错误，不知道为什么，等佬看

**Comment by LyeeH** [comment]
删了avatar里的图片之后能识别成功了，截图里是把夜莺当成能天使放下去了
多谢
