### ISSUE TITLE
基建无法选择上干员

### ISSUE THREAD

**Issue by QIHEYEER** [MaaAssistantArknights/MaaAssistantArknights#5965]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建无法选择上干员，maa操作在制造站还可以选择上，到了贸易站选择了一个干员后就卡住在只选择的那一个干员上，maa操作选择其他干员选择不上，手动操作也选择不上，打开其他基建选择干员时也会卡在maa选择的那个卡住的干员界面，手动退出基建再进基建才又能选上

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12362067/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12362074/gui.log)
2023.8.17，1：12

### 截图

![MuMu12-20230817-014801](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134895267/cad7bfb0-5bd7-435a-bc33-86d41e275174)
在maa选择这个干员后就选择不上其他干员了

### 还有别的吗？

mumu12，win10

**Comment by QIHEYEER** [comment]
maa操作栏提示：干员冲突

**Comment by dylanhz** [comment]
同样的问题，日志在8.17的1点和9点，之前用的蓝叠一切正常，，mumu12是不是有什么问题？
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12364721/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12364722/gui.log)
