### ISSUE TITLE
日服战斗卡在选择章节界面

### ISSUE THREAD

**Issue by chydbd** [MaaAssistantArknights/MaaAssistantArknights#5968]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在日服选择刷关1-7时会在卡在选择章节界面一段时间后报错

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12364274/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12364275/gui.log)

### 截图

![QQ图片20230817075726](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142459480/b0694c97-b37d-42a6-acd4-1738566fa87c)

### 还有别的吗？

若是手动进入章节则会卡在选关界面不动，一段时间后报错

**Comment by chydbd** [comment]
#5251

**Comment by Constrat** [comment]
I've noticed this issue in EN as well. Yesterday I've changed some parameters so it should be fixed with the next version.
Updae

**Comment by ABA2396** [comment]
@Constrat 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/76e8702b-f120-4eda-b7cb-f6c7ea34a775)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/82474c99-9746-4bc5-b6bc-7069e3225352)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/c0d864f7-5ab4-455f-bc5a-bb725c8a2d25)

**Comment by Constrat** [comment]
:O Interesting. I had an idea that was the way to go but I didn't want to try, I was scared fucking up something.

**Comment by Constrat** [comment]
@chydbd In 30 mins the new alpha / nightly version should arrive. Tell me if it works.
d4776da

**Comment by Constrat** [comment]
Fixed with https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/d4776da391db01e3190ebce8dce3a1e7799af3fd
