### ISSUE TITLE
perf: 优化一下`AsstGetImage`

### ISSUE THREAD

**Issue by bakashigure** [MaaAssistantArknights/MaaAssistantArknights#597]
催催玛丽，啥时候优化一下`AsstGetImage`，改成调用时立刻获取一张截图。
同步截图需要的时间较长，在等待过程中有可能会阻塞住UI？能通过回调返回么

**Comment by MistEO** [comment]
回调似乎是好主意？就是不知道其他已经集成了的会不会鲨了我（好像也没有人

**Comment by bakashigure** [comment]
回调塞图片会不会太长了；或者做成两个接口，第一个请求截图，第二个获取？会不会太屎了

**Comment by MistEO** [comment]
> 回调塞图片会不会太长了；或者做成两个接口，第一个请求截图，第二个获取？会不会太屎了

可！那就，请求——回调通知完成——获取

获取接口还是现在的，不变，新增请求和回调。好耶甚至兼容

**Comment by MistEO** [comment]
那请求你得自己限制速率了啊，core 不管了（

**Comment by MistEO** [comment]
请求返回个 requestId, 回调里包含这个。好！先把文档整出来（画饼
