### ISSUE TITLE
无法强制替换adb

### ISSUE THREAD

**Issue by Metana1375** [MaaAssistantArknights/MaaAssistantArknights#5970]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa能定时自行启动，但无法运行任务，试图用“强制替换adb”解决问题时失败

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12364443/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12364444/gui.log)
在8月17日上午4:30至9:00期间

### 截图

![捕获](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/132066126/6230a657-6c17-448e-bf94-314fad3149c8)

### 还有别的吗？

模拟器：蓝叠5 china
操作系统：windows10 22H2（x64）

**Comment by ABA2396** [comment]
权限给的不够，用管理员权限开

**Comment by Black1312** [comment]
请关闭“启动设置”中五个选项后重启电脑，不要打开模拟器，管理员权限打开MAA，使用强制替换ADB。问题解决后请关闭本ISSUE

**Comment by Metana1375** [comment]
问题又出现了，用管理员权限打开也不行

**Comment by ABA2396** [comment]
新遇到的报错和这个一样？

**Comment by Metana1375** [comment]
> 新遇到的报错和这个一样？

是的
