### ISSUE TITLE
定时执行的自定义配置功能存在缺陷

### ISSUE THREAD

**Issue by AnnAngela** [MaaAssistantArknights/MaaAssistantArknights#5971]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

复现步骤：
1、在设置页【切换配置】处创建两个配置 A 和 B，并切换到配置 A；
2、在设置页【定时执行】处勾选“自定义配置选择”，勾选定时 1 ，将其设置为 07:30，并将其配置改为 B，然后取消勾选“自定义配置选择”。

期望行为：
在 07:30 时自动执行配置 A。

实际行为：
无事发生，连日志都没有。

### 日志文件

[asst.log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12364494/asst.log.zip)

好几天的 07:30 处一点日志没有=。=

**Comment by ABA2396** [comment]
定时是全局配置，你在 B 取消就代表你不需要自定义配置选择

**Comment by AnnAngela** [comment]
> 定时是全局配置，你在 B 取消就代表你不需要自定义配置选择

对，但我期望的是此时用的是全局的 A 配置而不是什么都不做完全不触发

**Comment by ABA2396** [comment]
是同时打开了强制定时执行吗

**Comment by AnnAngela** [comment]
> 是同时打开了强制定时执行吗

没开，但 bc32eb6 看起来应该能解决问题

**Comment by ABA2396** [comment]
那不应该啊）这个判断是在强制执行里面的

**Comment by ABA2396** [comment]
我这边复现不出来不开强制的时候不开始的情况，等下发个内测版测测

**Comment by AnnAngela** [comment]
装了最新的内测版，这个 bug 修复了，那这是为什么呢.jpg
