### ISSUE TITLE
MAA操作延迟高

### ISSUE THREAD

**Issue by broken-moon233** [MaaAssistantArknights/MaaAssistantArknights#5973]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

所有操作通常都有5-10s的延迟，操作显示在MAA界面后过许多秒才进行
已经尝试过替换ADB，更改触控模式，更新和降级版本，重启设备，模拟器以及软件等均无效

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12366728/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12366729/gui.log)
以上为一次自动战斗的日志文件

### 还有别的吗？

使用蓝叠模拟器

**Comment by ABA2396** [comment]
用的是蓝叠Pie实例吗？这个版本截图好像是有问题

**Comment by broken-moon233** [comment]
> 用的是蓝叠Pie实例吗？这个版本截图好像是有问题

的确是这个，之前用的时候似乎正常，我换成Nougat试一下

**Comment by broken-moon233** [comment]
> 用的是蓝叠Pie实例吗？这个版本截图好像是有问题

疑似蓝叠的问题，换成Nougat64位还有一样的问题，换成mumu12之后解决了
