### ISSUE TITLE
mumu12定时执行识别错误

### ISSUE THREAD

**Issue by dylanhz** [MaaAssistantArknights/MaaAssistantArknights#5980]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我给maa设置了每天四次定时执行，mumu12模拟器一直识别错误。
手动执行任务，或者到点时点开maa监视其执行，或者之前使用的蓝叠模拟器，都不会出现此问题。
我设置的笔记本永不睡眠，定时执行时一般只是处于锁屏状态。

### 日志文件

错误时间可以参考8.17的1点、9点，8.18的9点。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12374696/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12374697/gui.log)

### 还有别的吗？

v4.22.0-beta1
win10 22H2

**Comment by ABA2396** [comment]
你说的错误是指Recruit还是换班？Recruit的话如果公招券没了也会报错的

**Comment by dylanhz** [comment]
> 你说的错误是指Recruit还是换班？Recruit的话如果公招券没了也会报错的

貌似是全都有问题，基建放的干员和自定义配置不符，放错放不满都有，后面战斗公招什么的都直接报错跳过了，基本上啥也没干。
我现在换回蓝叠了，同样的配置完全正常，估计还是mumu12的问题。

**Comment by ABA2396** [comment]
mumu倒是有人遇到过卡在基建里无法点击的情况，只有重开游戏才能跑，到时候找mumu的人瞅瞅
