### ISSUE TITLE
maa无法识别基建宿舍等

### ISSUE THREAD

**Issue by kkkkkrl** [MaaAssistantArknights/MaaAssistantArknights#5984]
### 说说你遇到的问题？

扫描基建宿舍的时候只会扫描第一个或第二个，有时候换干员明明心情只有2了，依然不换
![430ceac7f3f5d5f0d03cc08cd7726d1d](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142640217/59515623-780b-4b3e-9cf0-4cb6b55dbd13)

**Comment by Constrat** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/e922df95-188b-4b45-bab3-0e05abc3fbb8) --> ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/26ba0370-57ea-4044-bb3f-5ece76946e54)

Also without asst.log there is nothing we can do.

**Comment by kkkkkrl** [comment]
Hello


this is the asst.log，can you help me?




Regards
Rui Lyu




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月19日(星期六) 下午5:07
***@***.***&gt;;
抄送:&nbsp;"rui ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] maa无法识别基建宿舍等 (Issue #5984)





 
 --&gt; 
 
Also without asst.log there is nothing we can do.

**Comment by Constrat** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/49620b0b-3f49-41cb-9f07-935d193483db)
asst.log is in this folder.
maa installation\debug\asst.log

**Comment by kkkkkrl** [comment]
I have put the file in the attachment of the email, can you see it？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月19日(星期六) 晚上9:49
***@***.***&gt;;
抄送:&nbsp;"rui ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] maa无法识别基建宿舍等 (Issue #5984)





 

 asst.log is in this folder.
 maa installation\debug\asst.log

**Comment by Constrat** [comment]
I cant' see it unfortunately. I don't think attaching files to mail replies works

**Comment by kkkkkrl** [comment]
Hello


I tried to send it to you through another mailbox, can you see it？

**Comment by Constrat** [comment]
No.
I don't think discord allows email with attachments at all.

**Comment by kkkkkrl** [comment]
I sent it to you from another mailbox, have you seen it?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月19日(星期六) 晚上10:07
***@***.***&gt;;
抄送:&nbsp;"rui ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] maa无法识别基建宿舍等 (Issue #5984)





 
I can't see it unfortunately. I don't think attaching files to mail replies works

**Comment by Constrat** [comment]
I don't think changing mailboxes does anything. Best way is to use the browser and send it from here.
Here is the link of this discussion: [THIS DISCUSSION](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5984)

**Comment by kkkkkrl** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12386120/asst.log)
got it, can you see it?

**Comment by Constrat** [comment]
> [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12386120/asst.log) got it, can you see it?

Perfect! Thank you.

**Comment by Constrat** [comment]
Could you try updating to the latest nightly release and testing if you still have issues? I've looked at the logs and I'm having difficulties recreating your issue.

**Comment by kkkkkrl** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142640217/8c5a0256-ddca-4fda-a3f3-01a91b965f3a)
I updated the program and tried it your way, and the dorm looks fine, but the power station can only detect one.

**Comment by Constrat** [comment]
What resolution are you using for playing? Can you send a screen of your base layout
(screen from emulator ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/050af596-6504-4f48-b401-05c4a682990e))
As usual the log with the time of the error. It seems strange that it can only read only one power plant considering they all get detected the same way.

**Comment by kkkkkrl** [comment]
The resolution of my desktop is 2560 x 1440 and the resolution of the simulator is 1920 x 1080.
![MuMu12-20230820-182728](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142640217/937c66e5-6ef2-48b9-91a1-7ddb656bb3d2)

**Comment by Constrat** [comment]
Does the error always show up or sometimes it works? because I also Use a 1440 monitor with 1080 emulator and both the EN and the CN have no issues for me.

Could you send me the log of trying to enter the power plant? Maybe isolated

**Comment by kkkkkrl** [comment]
This problem started in the last few weeks. Basically, the dormitory can only scan one, and sometimes there is a problem with the power plant. where is the log of entering the power plant?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月20日(星期天) 晚上6:32
***@***.***&gt;;
抄送:&nbsp;"rui ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] maa无法识别基建宿舍等 (Issue #5984)





 
Does the error always show up or sometimes it works? because I also Use a 1440 monitor with 1080 emulator and both the EN and the CN have no issues for me.
 
Could you send me the log of trying to enter the power plant? Maybe isolated

**Comment by Constrat** [comment]
> This problem started in the last few weeks. Basically, the dormitory can only scan one, and sometimes there is a problem with the power plant. where is the log of entering the power plant?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MaaAssistantArknights/MaaAssistantArknights" ***@***.***&gt;; 发送时间:&nbsp;2023年8月20日(星期天) 晚上6:32 ***@***.***&gt;; 抄送:&nbsp;"rui ***@***.******@***.***&gt;; 主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] maa无法识别基建宿舍等 (Issue #5984) Does the error always show up or sometimes it works? because I also Use a 1440 monitor with 1080 emulator and both the EN and the CN have no issues for me. Could you send me the log of trying to enter the power plant? Maybe isolated — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

By log of power plant I meant. Clearing the asst.log (deleting it) and tasking JUST the Base + Power plant and stopping after some failed attempts.

**Comment by kkkkkrl** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12387965/asst.log)

**Comment by Constrat** [comment]
I can't seem to find the issue. 
The infrastructure logs don't seem to have a lot information of something that seems broken. With both EN and CN I can't reproduce the issue.
