### ISSUE TITLE
增加登陆界面换账号功能

### ISSUE THREAD

**Issue by Alexandra-milay** [MaaAssistantArknights/MaaAssistantArknights#5985]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

鹰角已经对登录界面进行了优化，方便多账号登录，因此希望maa也能有对应的功能，实现在收完一个账号菜之后，自动退出登录，选择下一个账号收菜。

**Comment by Lancarus** [comment]
可以多开maa啊

**Comment by SherkeyXD** [comment]
Duplicate of #5077
