### ISSUE TITLE
SSSCopilot: 保全作战中的core设置为“只用一次”，但效果为“好了就用”，指定技能开启方式失效

### ISSUE THREAD

**Issue by AnnoyingFlowers** [MaaAssistantArknights/MaaAssistantArknights#5991]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89131639/a443b598-40fc-4d58-9615-9e6186c92fb1)
如图，我设置山为只用一次，但是实际效果却是好了就用。

有趣的是，我将下图的SkillUsage::Possibly改为SkillUsage::NotUse之后，core确实只开一次了，不过tool_men不开技能了。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89131639/1637d6a5-9976-4f46-9d5f-bea01a3ce608)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12385962/asst.log)

**Comment by MistEO** [comment]
你的 json 发一下

**Comment by AnnoyingFlowers** [comment]
> 你的 json 发一下

[SSS_保全荒废灯塔.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12388216/SSS_.zip)
