### ISSUE TITLE
肉鸽设置中增添“保守”选项以避免不期而遇中的战斗和消耗目标生命

### ISSUE THREAD

**Issue by ixsd5r** [MaaAssistantArknights/MaaAssistantArknights#5994]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题，傀影肉鸽中不期而遇观察到如下现象：
1.选择进入战斗选项（例如偷听囚犯或面斥鸭子等）
2.选择消耗x目标生命值换取y（例如命换锭或命换希望等）

### 有什么好的想法？

1.战斗仅10~20分且可能失败，而多走一层至少30分。不知哪个期望更高
2.获得物品数每个5分不包含源石锭和招募券。可能降低容错
综上，希望在肉鸽设置中增添“保守”选项以避免进入不必要的战斗和消耗目标生命值
感谢您的阅读

### 其他内容

MAA v4.22.0-beta.1
Bluestacks5国际版
傀影肉鸽刷等级默认分队

**Comment by Lancarus** [comment]
fixed in #6102
