### ISSUE TITLE
手动选择语言

### ISSUE THREAD

**Issue by yige-yigeren** [MaaAssistantArknights/MaaAssistantArknights#5995]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

默认使用系统语言是一个不错的主意
但是我最近在切换电脑语言为英文后遇上maa也成英文了233333333

### 有什么好的想法？

设置添加语言选项

**Comment by ABA2396** [comment]
手动切换过语言就不会跟着系统变了。看看界面设置或者右键点托盘图标

**Comment by Black1312** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64343218/06bd512f-2639-4c07-a23d-e59b9046805c)

**Comment by yige-yigeren** [comment]
> 

哦哦，是我没看见了，平时没注意这个选项
