### ISSUE TITLE
类型初始值设定项引发异常,无法加载 DLL“MaaCore.dll”

### ISSUE THREAD

**Issue by PYCHBI** [MaaAssistantArknights/MaaAssistantArknights#5998]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开MAA时提示
MAA 遇到了问题
“MaaWpfGui.ViewModels.UI.SettingsViewModel”的类型初始值设定项引发异常。
无法加载 DLL“MaaCore.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。

不是缺少运行库，已经试过常见问题里的Microsoft C++ 生成工具安装过了，常见运行库也装过了，DirectX修复工具也用过了，RestoreHealth指令也试过了，微软的Media Creation Tool无损重装过系统了，都没有用。内测版本和稳定版本的报错都一样，无法运行，所以也不是MAA版本的问题。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12387043/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/77482879/8a5ab87a-5710-44d2-8db5-dad02142f114)

### 还有别的吗？

跟模拟器没有关系，Win10 X64就报错，升级到Win11也是一样报错

**Comment by ABA2396** [comment]
看日志一直在尝试创建配置文件但是失败了，把maa解压在了什么路径？又或者是否把MAA.exe单独拖到其他位置了？来个文件夹的图看看

**Comment by Black1312** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64343218/5f4e1a3c-9c02-4a95-a9ab-fa3d08e18b1a)
MAA解压位置参考，除运行库外，还需要安装.net4.8，不要拖动（copy）exe图标来创建快捷方式
