### ISSUE TITLE
繁中服刷關卡（Fight）時無法進入指定關卡

### ISSUE THREAD

**Issue by bliOrz030** [MaaAssistantArknights/MaaAssistantArknights#5999]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

無法辨識進入先/輔晶片關卡

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12387866/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12387868/gui.log)

### 截图

![Screenshot_20230820-112725](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142703985/213ed59e-ea00-47c5-8f6d-02d1dfba6918)

### 还有别的吗？

雷電模擬器

**Comment by Constrat** [comment]
Without .log there is nothing we can do.

**Comment by bliOrz030** [comment]
> Without .log there is nothing we can do.

Sorry about that, I've added it

**Comment by Constrat** [comment]
I've confirmed that it's not detecting correctly 
```
[2023-08-20 17:49:38.510][TRC][Px3890][Tx28f0] asst::PipelineAnalyzer::analyze PR-C-1@StagePR-C
[2023-08-20 17:49:39.379][TRC][Px3890][Tx28f0] asst::PipelineAnalyzer::analyze PR-C-1@SwipeToTheRight
```
What resolution are you using?
Can you try with the latest nightly if you still have issues?

**Comment by ABA2396** [comment]
似乎是这张图的大小不对
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/74a5c39a-33af-42d2-a073-72e0668f4593)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/4d1cfac8-a49e-48ab-bcf8-7f10a0c0667f)
这样看起来SK可能也有问题
@momomochi987 能帮忙再看看吗

**Comment by Constrat** [comment]
His original image is 1600x900. MAA should downscale it no?

**Comment by bliOrz030** [comment]
感謝各位，確實是圖的大小不對，更換圖檔後已可正常執行!!
@Constrat
Thanks dude, you made my day. 
The way you taught and the pic you sent works fine for me .

**Comment by Constrat** [comment]
Ok that should work for everyone else. If you want / have time. You can do the exact same thing for the other templates.
1 method: use the https://github.com/MaaAssistantArknights/MaaAssistantArknights/tree/dev/tools/CropRoi and crop the template to make it similar to the other servers
OR
2 method: open something like paint, downscale the image (I suggest using bicubic algorithm)
Manually cut around leaving only the wanted image.

I just checked the templates that are already in MAA:
PR-C had issues, SK has issues, all the other should be fine.

**Comment by momomochi987** [comment]
先感謝兩位大佬的幫忙 !  。･ﾟ･(つд`ﾟ)･ﾟ･

上次更新的時候圖不小心放錯了 ( ´•̥̥̥ω•̥̥̥` )
等明天 SK 開了、我試過都沒問題了
我會再發 PR 更新圖檔 

I didn't noticed that PR-C and SK have wrong size :(
But SK isn't open today, I'll try new SK picture and create a Pull Request tomorrow (maybe...?
Thanks for you help, @Constrat and @ABA2396 !
