### ISSUE TITLE
希望增加 “启动游戏” 和 “关闭游戏” 的任务

### ISSUE THREAD

**Issue by LmeSzinc** [MaaAssistantArknights/MaaAssistantArknights#60]
明日方舟游戏客户端启动有点慢，登录主界面之后的各种弹窗也很烦。
希望 MAA 可以完成 启动游戏 - 登录 - 长草 - 关闭游戏 的一整个流程。

可能需要解决的问题和我设想的解决办法：
- 启停游戏客户端。这个用 ADB 命令就可以了，加上 B 服支持也不会太麻烦。
- 帐号登录。不做帐号切换，默认只有一个帐号，客户端会自动登录。
- 游戏更新。有热更的时候帮点确定，整包更新不管。
- 弹窗处理。公告关掉，月度签到和获得物品点掉。一些活动会有另外的签到和活动界面，比如矿区开采，处理这些会增加维护成本，但应该也可以接受。

**Comment by MistEO** [comment]
- 帐号登录。不做帐号切换，默认只有一个帐号，客户端会自动登录。
- 弹窗处理。公告关掉，月度签到和获得物品点掉。

这些其实现在就是支持的_(:з」∠)_不过仅限刷理智任务
