### ISSUE TITLE
CE-6 自动战斗出现问题

### ISSUE THREAD

**Issue by soundofautumn** [MaaAssistantArknights/MaaAssistantArknights#600]
写作业的时候发现识别出来的map有点歪
(1,3)的位置能放上去，(2,1)就放不上去了
![map](https://user-images.githubusercontent.com/62000745/170832296-1f958cc7-edbb-40ec-befc-6d37378c47be.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8791405/asst.log)
[CE_6.json.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8791406/CE_6.json.txt)

**Comment by MistEO** [comment]
@yuanyan3060 泰——迪——

**Comment by Alexzz96** [comment]
我也触发了这个问题，但是似乎是概率性的，第二把的坐标就正常了。
