### ISSUE TITLE
水月肉鸽开局藏品希望-1导致借助战卡住

### ISSUE THREAD

**Issue by Ncexce** [MaaAssistantArknights/MaaAssistantArknights#6002]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

水月肉鸽开局有时会选择希望-1藏品而导致借助战时希望不足而卡住，影响效率

### 有什么好的想法？

加入自定义开局藏品黑名单配置

**Comment by SherkeyXD** [comment]
Duplicate of #5413
