### ISSUE TITLE
无法识别干员

### ISSUE THREAD

**Issue by LyeeH** [MaaAssistantArknights/MaaAssistantArknights#6005]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用了maa://25612
找不到铃兰
稍微看了下log，估计是某个指针的问题，选完白面鸮之后开始切辅助选铃兰，但是却最多只能读到令的位置
有可能是桃金娘的位置被选了之后程序跳过了识别下置位干员？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12387659/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12387660/gui.log)

### 截图

https://www.loom.com/share/b176a34c11b94244a15e7633be61ccee
录了个视频，这软件只能share链接，不能上传，无语

**Comment by LyeeH** [comment]
还有就是同一个作业，放橙闪的时候老放成艾雅法拉，是不是她们两的新皮肤太像了识别错误啊？
我怕是皮肤问题就换回来普通皮肤了。

**Comment by Constrat** [comment]
> 还有就是同一个作业，放橙闪的时候老放成艾雅法拉，是不是她们两的新皮肤太像了识别错误啊？ 我怕是皮肤问题就换回来普通皮肤了。

Do you mean in the fight while waiting deployment or in the squad creation

**Comment by SherkeyXD** [comment]
> 还有就是同一个作业，放橙闪的时候老放成艾雅法拉，是不是她们两的新皮肤太像了识别错误啊？
> 我怕是皮肤问题就换回来普通皮肤了。

这个问题可以试试删除 cache/avatars 文件夹
maa会对干员的头像做缓存，但换了皮肤干员头像会变，也就有了这个问题

**Comment by LyeeH** [comment]
> > 还有就是同一个作业，放橙闪的时候老放成艾雅法拉，是不是她们两的新皮肤太像了识别错误啊？
> > 我怕是皮肤问题就换回来普通皮肤了。
> 
> 这个问题可以试试删除 cache/avatars 文件夹 maa会对干员的头像做缓存，但换了皮肤干员头像会变，也就有了这个问题

没有用，我试过了，po了个录制视频，log显示放橙闪但是把小绵羊拉下去了
https://www.loom.com/share/6f25174161f9446093ab205d070b929f

**Comment by LyeeH** [comment]
> > 还有就是同一个作业，放橙闪的时候老放成艾雅法拉，是不是她们两的新皮肤太像了识别错误啊？ 我怕是皮肤问题就换回来普通皮肤了。
> 
> Do you mean in the fight while waiting deployment or in the squad creation

deployment
