### ISSUE TITLE
连接不到模拟器，概率性会重启ADB服务后恢复，但有时候十几分钟还在连接就是不重启ADB

### ISSUE THREAD

**Issue by AlexYangCong** [MaaAssistantArknights/MaaAssistantArknights#6006]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

一直显示正在连接 然后有大概三分之一的概率会重启adb后恢复正常，但大多数就一直连接下去，十分钟不带重启的。重启MAA无效，重启模拟器小概率恢复，重启电脑一定恢复。建议是给一个手动的重启adb的快捷选项

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12387733/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12387734/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49122848/10e49b06-3acc-46c1-b248-57ed0a88b893)
已经快三分钟了，以往十几分钟都有，

### 还有别的吗？

WIN11 蓝叠国际HyperV 拯救者r9000p2021

**Comment by AlexYangCong** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49122848/fda0e616-e8c2-493b-aa72-9d961744ab18)
它来了，洗澡之前点上去，十分钟不带重连的

**Comment by MistEO** [comment]
我本地又复现了，看来没修对 QAQ

**Comment by AlexYangCong** [comment]
是这样的，俺刚挂上又出现了哈哈哈哈哈哈，玛丽加油捏

**Comment by MistEO** [comment]
27124c65beb85797e4b42cfa5ebc510692c667cc 这次应该修复了

**Comment by AlexYangCong** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49122848/879cfa3c-a348-4e64-a0ff-dc1592aa7b79)
它......
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12466265/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12466267/gui.log)

**Comment by MistEO** [comment]
v4.23.2 fixed
