### ISSUE TITLE
希望能增加兩個操作之間的時間調整的功能。

### ISSUE THREAD

**Issue by Xmh20070642** [MaaAssistantArknights/MaaAssistantArknights#6015]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

海外用戶在使用maa的時候，有時由於網絡延遲的問題，會影響到操作的準確性。導致在清理智時候會重複操作or未完成上一步操作。

### 有什么好的想法？

是否可以添加一個設置，讓兩個動作之間人爲設定一個值，來確保動作不會過快or過慢發生。

### 其他内容

![QQ图片20230820235602](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142739083/61452a40-4f92-4113-b809-593fbb2bb440)

**Comment by status102** [comment]
这个应该通过代码解决而不是用户自定延迟
