### ISSUE TITLE
掉线重连因为不明原因失败，导致刷理智任务出错

### ISSUE THREAD

**Issue by SchwarzXia** [MaaAssistantArknights/MaaAssistantArknights#6016]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在执行较长的刷理智任务途中，发生了掉线重连，然而maa没有成功重连，而是直接任务失败，游戏停留在登录界面

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12389353/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12389354/gui.log)

问题发生在8/20 13:29

### 还有别的吗？

模拟器为mumu，游戏没有发生闪退，最后停留于登录界面

掉线的原因大概率是单纯的网络问题（因我人在美国，连国内网络有时会不畅）

该问题在过去一年内多个版本的maa发生过数次，但在我回国的几个月内并没有发生过

**Comment by qiopgh** [comment]
我也遇到了,基建换班的时候因为网络问题掉线也不会重连,直接任务失败
