### ISSUE TITLE
大批量干员编队异常（去除下划线后仍不能正常选择）

### ISSUE THREAD

**Issue by Black1312** [MaaAssistantArknights/MaaAssistantArknights#6017]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

很多干员ocr结果前多了下划线，导致自动编队查找不到对应干员

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12389968/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64343218/ee76ec47-761a-40e0-928d-96c3a13dcc2f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64343218/5f7457d3-3573-4047-897f-4e377b8ee46c)

### 还有别的吗？

MAA：v4.22.0-beta.1.d176.g8ca76de6f
蓝叠国际模拟器

**Comment by Lancarus** [comment]
补充一下1080x1920和720×1280都多下划线。。。

**Comment by cenfusheng** [comment]
已修复，将在后续版本实装

**Comment by cenfusheng** [comment]
![QQ图片20230821133618](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52312717/6f6dac32-4cb1-4c82-85eb-db26c6444204)
![QQ图片20230821133623](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52312717/29ef8fd4-9515-49ec-80db-cbc8a80894bf)

**Comment by MistEO** [comment]
#6022 fixed
