### ISSUE TITLE
排班功能加入，加工站

### ISSUE THREAD

**Issue by BGLX** [MaaAssistantArknights/MaaAssistantArknights#6019]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

自动挂机，排班表里，需要在加工站里，轮换 年 与 麦哲伦。

**Comment by MistEO** [comment]
#4610

**Comment by MistEO** [comment]
fixed
