### ISSUE TITLE
掉线重连功能不生效

### ISSUE THREAD

**Issue by a322655** [MaaAssistantArknights/MaaAssistantArknights#602]
无论是在基建换班还是刷理智的时候掉线都无法自动重连，日志如下：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8792447/asst.log)

**Comment by ABA2396** [comment]
试试新版本，应该已经没问题了_(:з」∠)_

**Comment by a322655** [comment]
已修复，可以closed了
