### ISSUE TITLE
建议把令的小龙头像复用

### ISSUE THREAD

**Issue by nightofknife** [MaaAssistantArknights/MaaAssistantArknights#6024]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

抄作业的时候令的小龙有两个形态，区别只在于右上角是剑还是灯笼，但是识别的区域分辨不出来，会导致如果cache里面存的和用的对不上就放不下去

### 有什么好的想法？

建议把两种龙当作一个对待，直接叫令的龙

### 其他内容

令的两种龙图标：
![VUCEV@R~UA)C{LB7C9~~3 O](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73384329/ac70d899-b238-4d0f-bf98-e0e47842c2f4)
![C`OQAY%$RF3PP6073MHHRGM](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73384329/4409923a-801e-4805-8927-25f093334330)
ccache里面存的
![“弦惊”](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73384329/6a0d70ac-efe0-4084-ad17-29511ade76dd)

**Comment by nightofknife** [comment]
补一句，这样改了可能肉鸽里面会放不下去，建议直接把令拉黑名单

**Comment by Incredible556** [comment]
补充一点，在使用令的皮肤“崖高梦远”后，小龙无法被正常识别
