### ISSUE TITLE
关于挂机傀影肉鸽的问题，有时会无法开始战斗

### ISSUE THREAD

**Issue by wiit101** [MaaAssistantArknights/MaaAssistantArknights#6030]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在挂机看傀影肉鸽时，会经常发生因为不期而遇所触发的战斗，触发的战斗会自动的选择干员但是不会自动的开始战斗。而maa界面也无任何的反应，就会一直在不期而遇

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12395602/gui.log)
[asst (3).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12395660/asst.3.zip)
问题发生在8月17日12：30，那时我刚开始刷傀影肉鸽，往后经常发生
[asst (4).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12395684/asst.4.zip)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12395698/asst.zip)
[asst (2).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12395711/asst.2.zip)

### 截图

![(PI2D3%(XSQM HA_AO7EP L](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142763856/aeae2c14-8101-45bc-8fe5-4db85eb52c62)
![))X`YK0(F{RROXA5ZBAYNMA](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142763856/aa42164f-ecb6-494f-8ed0-f302dfb49836)

### 还有别的吗？

模拟器为mumu12

**Comment by lancelee00** [comment]
试试修改红为1技能

**Comment by Constrat** [comment]
Hasn't this already been addressed about a week ago?

**Comment by Lancarus** [comment]
请更新到最新内测版
