### ISSUE TITLE
雷电模拟器9连接失败：adb server version (18363) doesn't match this client (41)

### ISSUE THREAD

**Issue by SpiritedAwayCN** [MaaAssistantArknights/MaaAssistantArknights#6031]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

雷电模拟器由4更新至9后连接失败（自动检测，手动均失败）
已尝试过：重启MAA/模拟器/电脑、强制替换adb、重装雷电模拟器、两种连接地址（`127.0.0.1:5555`和`emulator-5554`）

手动测试ADB，报错如下：
```sh
G:\leidian\LDPlayer9>adb.exe devices
adb server version (18363) doesn't match this client (41); killing...
could not read ok from ADB Server
* failed to start daemon
adb.exe: failed to check server version: cannot connect to daemon
```

类似文本可在log中找到。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12396182/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12396184/gui.log)

### 截图

暂无，gui.log包含了报错信息

### 还有别的吗？

操作系统：Windows 10 教育版
模拟器：雷电模拟器9.0.57(9)
模拟器设置：
* ADB连接：允许本地连接/允许远程连接（均已尝试）
* ROOT权限：开启

**Comment by MistEO** [comment]
手动都连不上那就是雷电的问题了（
