### ISSUE TITLE
System.ArgumentException: 已添加了具有相同键的项。

### ISSUE THREAD

**Issue by keylazy** [MaaAssistantArknights/MaaAssistantArknights#6034]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

v4.22.0.-beta.1->alpha/v4.22.0_beta.1.d186.g7430884e3
System.ArgumentException: 已添加了具有相同键的项。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 MaaWpfGui.ViewModels.UI.RecognizerViewModel.get_OperBoxPotential()
   在 MaaWpfGui.ViewModels.UI.RecognizerViewModel.procRecruitMsg(JObject details)
   在 MaaWpfGui.Main.AsstProxy.ProcSubTaskExtraInfo(JObject details)
   在 MaaWpfGui.Main.AsstProxy.ProcMsg(AsstMsg msg, JObject details)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12398491/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12398496/asst.zip)

**Comment by MistEO** [comment]
可能和这个有关 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6009/files#diff-650efabc182a56d85193cb544d79575a12389ce45b2705db7cebe48990d97fc1R537

**Comment by 178619** [comment]
> 可能和这个有关 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6009/files#diff-650efabc182a56d85193cb544d79575a12389ce45b2705db7cebe48990d97fc1R537
> 
> @178619 please help to check, thx!

Theoritically `own_opers` should have neither duplicate ids nor names. Wouldn't there be the same issue even if I didn't change it? In gui.log you can find write failure so it could be related. Of course I could be just wrong. It would be nice if we could look into `config/gui.json`.

**Comment by 178619** [comment]
#6040

**Comment by 178619** [comment]
The same issue is present in pre-#6009 versions, it's just that it happens when there are duplicate names instead of duplicate ids. It looks like that `OperBox.Data` in `gui.json` is just broken. Although, I wonder how it even happened.

**Comment by 178619** [comment]
Thanks, I have to admit I knew nothing about C#, I tried to fix it myself in my fork but I couldn't make it work myself.

I guess at some point operator recognizer returned only names and not ids? I really have to be more careful before messing with the codes.
