### ISSUE TITLE
红米K30 pro，miui14.0.4启动报截图失败

### ISSUE THREAD

**Issue by glimjoe** [MaaAssistantArknights/MaaAssistantArknights#6045]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用红米K30 pro，miui14.0.4，首次使用maa，按照手册配置完成后启动游戏，正常执行了启动前脚本，然后报了六次截图失败，接着就是任务结束和结束后脚本
尝试过更改连接模式，强制替换ADB，三个触控模式也都尝试过了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12406315/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12406316/gui.log)

### 还有别的吗？

笔记本是thinkbook16+，操作系统是win11，版本号10.0.22621.2134
issue里面有一个相同的问题，提交者最后说了一句已解决，但是没说怎么解决的，issue也关闭了没法回复，只能新开一帖

**Comment by SherkeyXD** [comment]
> issue里面有一个相同的问题
这个指的是？

**Comment by glimjoe** [comment]
> > issue里面有一个相同的问题
> 
> 这个指的是？ 此外关闭的issue应当是可以回复的

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5484 是这个
我以为关闭了就不能回复了，我先问一下

**Comment by ABA2396** [comment]
他那个是wsa，和实体机不是一个问题吧

**Comment by glimjoe** [comment]
> 他那个是wsa，和实体机不是一个问题吧

他第二个截图用的实体机，也是红米，miui版本也一样，机型就算不一样应该也是差不多的思路。。。可惜没有回复

**Comment by MistEO** [comment]
minitouch 在实体机上应该是用不了的，换 adb input ，再抓个日志看看

**Comment by glimjoe** [comment]
> minitouch 在实体机上应该是用不了的，换 adb input ，再抓个日志看看

我之前试过adb input但还是同样的报错，但是日志没有保留下来，于是我刚刚又试了一下adb input，居然能正常运行了，好神奇
