### ISSUE TITLE
傀影肉鸽中抓取招募券错误引发的问题

### ISSUE THREAD

**Issue by Sam-0324** [MaaAssistantArknights/MaaAssistantArknights#6046]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题，设置中选择刷等级策略，且选择后勤分队；
MAA在选择取长补短（近卫+辅助+医疗券）后，近卫券选择棘刺，医疗券选择预备干员-医疗，但在辅助券放弃招聘机会，这可能会在遇到诸如[礼炮小队](https://prts.wiki/w/ISW-NO_%E7%A4%BC%E7%82%AE%E5%B0%8F%E9%98%9F)等关卡时因为输出不够而在一层失败。

在战斗结束后，队伍里没有法术输出时，哪怕希望足以进阶/招聘6星近卫，MAA仍然在选择术师券/近卫券时选择术师券，并选择放弃招聘机会（可能是因为没有强力术师干员？）

### 有什么好的想法？

如果开局希望不足以抓取强力干员，辅助券抓取梓兰或预备干员-术师；
在希望足够时，考虑优先进阶六星干员而不是招募其他干员。

**Comment by Lancarus** [comment]
#5946
