### ISSUE TITLE
MAA在更新成新内测版后出现了无法双开的问题

### ISSUE THREAD

**Issue by MadRouge** [MaaAssistantArknights/MaaAssistantArknights#6048]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题今天更新MAA后出现了无法双开的问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12408091/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12408092/gui.log)

**Comment by ChildeRolando** [comment]
python接口会在第二个实例执行到asst.py第76行时直接退出，即Asst.load()方法的这一行:
`ret &= Asst.__lib.AsstLoadResource(str(path).encode('utf-8'))`

**Comment by MistEO** [comment]
3029e6d9b9466ec89c825190bc572cba5723666e fixed
