### ISSUE TITLE
beta6更新后闪退

### ISSUE THREAD

**Issue by StellAr117** [MaaAssistantArknights/MaaAssistantArknights#605]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8792658/asst.log)
mumu模拟器，win10 21H2，

https://user-images.githubusercontent.com/104726749/170852695-31e39817-807a-4d16-bdc8-3be97634f969.mp4

**Comment by MistEO** [comment]
看日志没啥头绪，重新下载解压试试

**Comment by StellAr117** [comment]
> 看日志没啥头绪，重新下载解压试试

重新安装过了还是这样，已经退回老版本了 XD

**Comment by MistEO** [comment]
哦我想起来了，你用管理员权限打开试试

**Comment by zzyyyl** [comment]
怪了，我更新完beta6，打开gui白屏一会儿就闪退了，日志都没有

**Comment by zhongzi26** [comment]
> > 看日志没啥头绪，重新下载解压试试
> 
> 重新安装过了还是这样，已经退回老版本了 XD

请问你用的快速打开文件软件是什么？看着是Listary，但是Listary怎么做到透明的？

**Comment by ABA2396** [comment]
> ~怪了，我从beta3更新到beta6，打开gui白屏一会儿就闪退了，日志都没有~ 文件夹下出现了个 `NewVersionExtract` 文件夹，新版本在里面。是改更新规则了（？

我今天更新也是，打开就说新实例崩溃，然后直接把自动下好的压缩包拿出来解压替换了

**Comment by MistEO** [comment]
~~反正我没改，赶紧查 commit!~~

**Comment by StellAr117** [comment]
> > > 看日志没啥头绪，重新下载解压试试
> > 
> > 重新安装过了还是这样，已经退回老版本了 XD
> 
> 请问你用的快速打开文件软件是什么？看着是Listary，但是Listary怎么做到透明的？

是wox啦

**Comment by MistEO** [comment]
是 mumu 的管理员权限问题，新版本修了
