### ISSUE TITLE
希望在肉鸽模式的高级设置上添加一些临时招募和正常招募的星级优先。

### ISSUE THREAD

**Issue by leserfeng** [MaaAssistantArknights/MaaAssistantArknights#6051]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

每次用这个都已经设置好了，用的是稳扎稳打的队伍，重装都会选斑点，术士选择澄闪，每次到狙击这里我还以为他会选择克洛丝，空爆等三星干员，而是选择了临时招募的预备干员-狙击，还有就是，在选择星级和临时招募的情况下他会选择临时招募，但是前期选干员时，重装因该也是临时招募的预备干员，每次获得招募券，希望足够去换，临时招募五星干员和六星干员但是他选择了临时招募五星干员，还有一点就是本该要精二的干员却选择了三星干员。

### 有什么好的想法？

因该多一个选项是星级和临时招募的优先级，比如我可以正常招募里多了一个临时招募，这样我可以选择这个临时招募的星级优先级，优先级不够就优先六星更好一些，但是虽然这样要增加一些工作量，但是每次看到这个东西给我乱选一通，就导致伤害不足，过不了第一层。

### 其他内容

<img width="1202" alt="屏幕截图 2023-08-22 225833" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/135349386/5cbe1b76-9f73-4fca-bc9c-413b35a8baa8">

**Comment by SherkeyXD** [comment]
![ed8ac5ca78d6829414882c0541c393a9](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57581480/6b5ed61d-5aca-4feb-86ba-566b3a1c6f62)
