### ISSUE TITLE
萨米肉鸽存钱频繁出现战斗10分钟后战斗失败（都是之前正常通关过的图、试过多个开局干员）（可能是自动暂停导致的）

### ISSUE THREAD

**Issue by Raine330** [MaaAssistantArknights/MaaAssistantArknights#6059]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

您好，想问一下萨米肉鸽存钱经常进图10分钟以后战斗失败，推测是刮痧太久自动退了，用山送葬人迷迭香煌开局都会出现这种情况。往往是刚开始的几盘正常运行，之后基本都是开局第一战就寄（明明是之前正常通关过的图），偶尔能正常运行一把。挂9小时存了50块，其中40块是刚开始半小时内存的，这种情况怎么办呢

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12415156/debug.zip)

### 截图

<img width="226" alt="存钱战斗失败 (1)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129166161/511e4e43-9ece-4188-ac8e-1b39ac2b555d">
<img width="189" alt="存钱战斗失败 (2)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129166161/ae8fc682-18ae-452b-a0ee-8e9e929ce93b">
<img width="194" alt="存钱战斗失败 (3)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129166161/3c4340f3-d63c-4e88-a78d-c4f58a65f02a">
<img width="197" alt="存钱战斗失败 (4)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129166161/a576f190-26fb-4eca-b5b5-faba9cff86da">
<img width="191" alt="存钱战斗失败 (5)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129166161/e7adca29-8113-41bf-a264-c9ba9848b014">
<img width="185" alt="存钱战斗失败 (6)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129166161/7512ac24-e02d-408c-87e8-692ec89821ee">
<img width="174" alt="存钱战斗失败 (7)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129166161/55bf2cac-ceb2-4dea-b029-bb71aa15e1f4">
<img width="182" alt="存钱战斗失败 (8)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129166161/aa916d88-d32a-4477-8ce7-19e2007b29a5">
<img width="190" alt="存钱战斗失败 (9)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129166161/bd7348ae-2aa3-4b1a-a314-56055c4bf2cc">
<img width="184" alt="存钱战斗失败 (10)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129166161/e0c309d3-7d6d-4ac4-9340-d368ea020481">
<img width="195" alt="存钱战斗失败 (11)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129166161/5bd8b049-e702-408b-b07c-deed5fd33432">
<img width="192" alt="存钱战斗失败 (12)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129166161/12f236d6-4a5b-4dac-a086-9fbe1436008e">
<img width="179" alt="存钱战斗失败 (13)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129166161/8f240769-cd26-4bbf-bc01-36d49709366a">

### 还有别的吗？

模拟器：雷电模拟器9.0.44
模拟器设置：1600*900 dpi240 4核 4096M
操作系统：win11家庭中文版 22621.2134

**Comment by Raine330** [comment]
补充：刚才又挂了一会儿，偶然发现在度假村开局几秒还未部署任何干员的情况下游戏暂停了，无任何动作，不知道那些10分钟战斗失败的局是不是也是这种情况

**Comment by SherkeyXD** [comment]
你的帧率稳定吗？过低的帧率会导致maa操作失败

**Comment by Raine330** [comment]
> 你的帧率稳定吗？过低的帧率会导致maa操作失败

自己玩的时候稳定，挂maa的时候确实会观察到明显掉帧，请问要怎么解决呀

**Comment by Constrat** [comment]
Unfortunately MAA takes a bit of resources, especially in Integrated Strategies.
To keep more stable frame rates I suggest lowering the resolution of the emulator. For the CN server going to 1280x720 shouldn't create many problems. 
That should help your framerates a bit more.

**Comment by nnnniiiiaaaa** [comment]
试过不是因为刮痧，也存在这种情况，而且时间也不稳定，有时候不止十分钟，我是大概半个小时左右会碰到这种问题
