### ISSUE TITLE
萨米肉鸽建议跳过夙愿将偿的不期而遇

### ISSUE THREAD

**Issue by Gk1146** [MaaAssistantArknights/MaaAssistantArknights#6061]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

MAA刷肉鸽等级基本上都在夙愿将偿关卡翻车

### 有什么好的想法？

建议直接跳过这个不期而遇，通关的概率会高一些

**Comment by SherkeyXD** [comment]
更好的解决方案也许是写一个对应的战斗逻辑

**Comment by Lancarus** [comment]
https://docs.qq.com/sheet/DUVlRU1F2Q3FjYU1M?tab=BB08J2
请到这里反馈

**Comment by Lancarus** [comment]
已优化改关卡作战逻辑
