### ISSUE TITLE
连接错误

### ISSUE THREAD

**Issue by Ga1en70** [MaaAssistantArknights/MaaAssistantArknights#607]
![image](https://user-images.githubusercontent.com/98802522/170853102-6b5b05c1-d736-4fd1-afd0-0007aa457ff8.png)
![image](https://user-images.githubusercontent.com/98802522/170853109-fb6f3511-9b79-4516-9230-b35b6e2c78cc.png)
新版本后连接错误，这里需要填吗？

**Comment by MistEO** [comment]
你用管理员权限打开，会自动填上的

如果还是有问题，找找你模拟器安装路径文件夹里（也可能不和模拟器一个文件夹，反正在附近），有个叫名字带 adb 的 exe, 选那个

**Comment by Ga1en70** [comment]
ok解决了，管理员权限打开没自动填，在模拟器文件夹里找到adb
