### ISSUE TITLE
获取信赖及购物中的借助站打OF-1未生效

### ISSUE THREAD

**Issue by Thoars** [MaaAssistantArknights/MaaAssistantArknights#6071]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

借助战打OF-1会改变编队，这两天编队没变过，确认勾选了这个选项，今天盯着发现没有去打OF-1，访问完好友直接去商店了

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12429345/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12429348/asst.log)
时间在这两三天的晚上七点之后

**Comment by ABA2396** [comment]
你关卡选择选的是 当前/上次，这种情况是不会执行这个任务的，不然下次运行的话上次关卡就跑到 OF-1 去了
