### ISSUE TITLE
招聘许可用完执行招募会通知【识别错误】【任务出错：Recruit】，希望能优化下

### ISSUE THREAD

**Issue by MODEMINGZ** [MaaAssistantArknights/MaaAssistantArknights#6073]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

招聘许可用完的情况下，maa点击招聘页面招聘按钮，在明日方舟游戏提示【招聘许可不足】的同时，maa会通知【识别错误】【任务出错：Recruit】，不过会自动返回不影响后续流程，希望能优化下

### 有什么好的想法？

对游戏内招聘页面的招聘预算进行识别，招聘许可为0自动返回跳过

### 其他内容

![搜狗截图20230825013453](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108219118/c2ff568f-c2a4-4f8e-bf13-783434b5b27e)
![搜狗截图20230825013324](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108219118/70da9981-c4b9-4887-a442-7fb93e43b7e0)

**Comment by broken-paint** [comment]
fixed by #6569
