### ISSUE TITLE
魅影肉鸽干员选择异常，摆放异常

### ISSUE THREAD

**Issue by drog111** [MaaAssistantArknights/MaaAssistantArknights#6075]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽自动时，系统总会少选第二个干员并且只选预备干员，导致每次第一次战斗就失败

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12435216/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12435219/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143152912/d526e479-9a19-49ab-8268-844a16890bfa)

**Comment by Lancarus** [comment]
试一下更新到内测版

**Comment by Lancarus** [comment]
#5946

**Comment by drog111** [comment]
> 试一下更新到内测版

OK了
