### ISSUE TITLE
傀影肉鸽，选干员技能的时候只有两个技能的干员点到第三个技能的位置导致卡住

### ISSUE THREAD

**Issue by Sainalu** [MaaAssistantArknights/MaaAssistantArknights#6076]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选干员技能的时候，一些只有两个技能的干员比如红，点到第三个技能的位置，进入上下干员界面，随后由于这部分流程应该算是做完了，点击开始作战实际上点到的是确认干员。

最终导致卡住在了干员选择界面

- 选择技能

![KFKW7XX4I06Z96_6_3{@Z_D](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46802703/4f92b34f-186c-4169-bc3f-ac27298727a0)

- 点到红第三个技能位置

![OU%5I%}P $9F8A4ACJNKHT](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46802703/c58c067f-f227-48ec-96a9-16b2d9b93797)

- 确认出来，不再开始行动，卡住

![KER9300395N{0)J}(ABT7Z5](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46802703/0e98a2cc-8c05-4f2b-8875-2ee1bcd74ed3)

望解决，应该是干员识别的问题，五六星需要区分

### 日志文件

2023-08-25 13:07
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12435809/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12435810/gui.log)

**Comment by ABA2396** [comment]
这个测试版已经修过了

**Comment by Sainalu** [comment]
好滴谢谢

**Comment by Sainalu** [comment]
已解决
