### ISSUE TITLE
使用令的皮肤“濯缨”后，会把令3技能的龙识别为1技能的龙“清平”，导致无法抄作业

### ISSUE THREAD

**Issue by MejiroSilence** [MaaAssistantArknights/MaaAssistantArknights#6079]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用自动战斗功能抄作业，然后发现无法放置令的小龙，查询log后发现似乎将3技能的龙“弦惊”识别为了1技能的龙“清平”，将作业的json文件中的”弦惊”全部替换为“清平”后也确实可以正常运行。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12437272/asst.zip)

**Comment by SherkeyXD** [comment]
试一下删除 cache/avatars 文件夹
