### ISSUE TITLE
干员识别功能无法识别耀骑士临光

### ISSUE THREAD

**Issue by Chengjpg** [MaaAssistantArknights/MaaAssistantArknights#6080]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用干员识别功能进行干员统计时，如果耀骑士临光被加入了特别关注并且使用复现荣光皮肤时，有概率无法被识别；取消特别关注则能正常识别；更换皮肤能正常识别；使耀骑士临光开始识别的位置改变也可以正常识别。如果耀骑士临光被加入了特别关注并且使用复现荣光皮肤时并且处于如图当前位置，BUG能够稳定触发。

### 日志文件

[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12438599/oper.zip)

### 截图

![未识别](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/84609228/67541523-b10d-41f1-842a-a93edd360745)
![已识别](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/84609228/f33880a3-2e88-4d4a-836d-d5c10cfd8298)

### 还有别的吗？

使用MuMu模拟器12，分辨率采用1920*1080(DPI 280)设置，MAA版本WIin-x64-4.21.0。

**Comment by Constrat** [comment]
4.21.0
Update to latest MAA version
