### ISSUE TITLE
夜神模拟器配置新abd后无法正常连接maa

### ISSUE THREAD

**Issue by dongmeng123** [MaaAssistantArknights/MaaAssistantArknights#6081]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

因无法正常自动配置abd后又重新装了abd，但是仍然无法连接到模拟器（也没有保存进中文路径）
![CMPMS3WG0WA52VZ9~$UD26R](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110719782/757ec09a-7983-4469-b886-b5c0f2d56ffa)
 

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12439040/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12439041/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110719782/792e6eac-8fd3-48c3-b242-8574029e8c68)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110719782/6c3e1c7b-35f0-4cf6-a5f5-2be77426d396)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110719782/4d341d19-72ad-48e3-a8f4-eb5beb11c420)

### 还有别的吗？

使用的是这个版本的夜神模拟器
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110719782/fb4ddb69-ec0f-4533-afcb-41f8bc42bf66)

**Comment by ABA2396** [comment]
报了Connection command failed to exec，看着像是adb崩溃了，试试看手动在任务管理器里把adb给关了。如果有开过代理或者加速器这种改变网络环境的话都有可能遇到

**Comment by dongmeng123** [comment]
> 报了Connection command failed to exec，看着像是adb崩溃了，试试看手动在任务管理器里把adb给关了。如果有开过代理或者加速器这种改变网络环境的话都有可能遇到

因为刚刚找不到有adb后缀的进程所以重启了电脑，以尽可能多的结束进程！然后好像更糟糕了！
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110719782/c0c01bb1-6f1b-4547-b931-6666908b248f)
甚至多了一个名为 asst.bak.log的文件！为您附上最新的文件！

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12440507/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12440508/gui.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12440510/asst.bak.log)

**Comment by dongmeng123** [comment]
这个会和我之前 
有下载过maa然后删掉 / 使用过其他模拟器但是删掉了
这些行为有关系吗 会不会是没有删除干净之类的情况~
