### ISSUE TITLE
关于测试版的肉鸽刷热水壶新功能

### ISSUE THREAD

**Issue by DIEANYWAY** [MaaAssistantArknights/MaaAssistantArknights#6084]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在刷到第三层后就退出没有问题，但结束动作的画面是停在新开一次肉鸽到热水壶阶段……这样我就不能更改肉鸽难度了，想要打N15也没法换……？

### 有什么好的想法？

希望能多加个设置，选择重开肉鸽时的难度和分队？或者就让脚本结束在刷到第三层退出，玩家能手动调等级开启新一轮。

**Comment by ABA2396** [comment]
这个有讨论过，之后看看怎么改

**Comment by SherkeyXD** [comment]
最好的解决方案其实是做个难度选择功能，但是傀影肉鸽和水月/萨米的难度选择又不一样，有点麻烦

**Comment by Lancarus** [comment]
#6094
