### ISSUE TITLE
GUI是否能带参数启动

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#6086]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

希望能带参数启动maa.exe 以在启动时直接切换配置，选择是否直接启动，在多开时比较有用

### 有什么好的想法？

start ...\maa.exe --config gui01 --start_instantly 1
start ...\maa.exe --config ...\gui02.json --start_instantly 0

### 其他内容

谢谢各位贡献者

**Comment by ABA2396** [comment]
改配置文件路径应该是不行，现在的做法是直接读当前目录下的，而且都用一个maa跑的话日志什么的也会有问题。启动时切换配置我看看能不能改改

**Comment by KJH-x** [comment]
> 改配置文件路径应该是不行，现在的做法是直接读当前目录下的，而且都用一个maa跑的话日志什么的也会有问题。启动时切换配置我看看能不能改改

嗯，能明白当前的逻辑，我第一条建议我没表述清楚，意思是想切换gui.json里的不同配置

**Comment by ABA2396** [comment]
94d6eb00ffdf76780ed293b398bad365d8dcd03e fixed
发个内测版试试
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/b3c99996-1345-4a4e-b807-593467522894)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/cfaf179f-f8d5-43b3-bfdd-edea37bd629b)

如果配置原先就带引号的话就用转义，如果配置名有空格就用引号包起来

**Comment by ABA2396** [comment]
等这个跑完 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/5983142063

**Comment by ABA2396** [comment]
直接启动的话和界面的一些选择就有冲突了，感觉不是很好整
