### ISSUE TITLE
内置作业阿尔斯特甜品制作平台有问题

### ISSUE THREAD

**Issue by WSMTBG** [MaaAssistantArknights/MaaAssistantArknights#6087]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

SSS_阿尔斯特甜品制作平台_浊蒂版.json最上排高台频繁放置失败，感觉是在把高台干员往不能放的格子拖上去

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12444626/debug.zip)

### 截图

![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/3563c256-a653-471f-a81b-011c55f6d76d)

**Comment by ABA2396** [comment]
yj的问题，第六关和第五关的名字一样，拿到的还是第五关的坐标，所以有错位
