### ISSUE TITLE
v4.23.0-beta.1模拟器关闭失败

### ISSUE THREAD

**Issue by 2247ds** [MaaAssistantArknights/MaaAssistantArknights#6089]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新到4.23.0-beta.1后，完成后关闭模拟器 的功能无法使用，提示模拟器关闭失败
模拟器是BlueStacks 5.12 .100.1023 N32

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12445080/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12445081/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46276428/bcdb04de-6a31-4f6b-882c-829ace0dd58e)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46276428/d45e0e6f-aacb-4bd5-9d98-caf79f1543fc)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/47dbd364-7779-45c1-8385-9a4bc893bb30)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/ae226f4f-cdbc-45fb-b604-892510d2cf7c)
权限不够，如果模拟器是管理员权限打开且不给maa管理员权限的话是拿不到关联进程的主模块的，试试用管理员权限启动maa

**Comment by 18272908616** [comment]
逍遥模拟题出现相同问题，管理员权限启动MAA没效果。

**Comment by 2247ds** [comment]
管理员权限启动不行，模拟器是BlueStacks 5.12.115.1001 N32
这是新的日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12445767/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12445768/gui.log)

**Comment by ABA2396** [comment]
没搞懂，我这里复现不出来
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/8b1f428e-d06b-4709-a19d-37fa36ec0a69)
看报错是只有获取不到主模块才会遇到，加个日志看看啥情况

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/5985605056
等这个跑完更新下内测版

**Comment by 2247ds** [comment]
对不起打错字了，管理员权限可以启动，但是依旧关不了模拟器
这是新的日志，maa版本v4.23.0-beta.1.d007 .g020701351
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12446607/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12446608/gui.log)

**Comment by ABA2396** [comment]
捕获到的异常信息是
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/b8bfea87-9082-4a21-9d37-61dd710f7dfc)
这一般就是访问权限问题，等别人看看吧)

**Comment by ABA2396** [comment]
这个问题还是有吗
