### ISSUE TITLE
在水月肉鸽中选择关卡有时会打开藏品页面然后卡住不动

### ISSUE THREAD

**Issue by asbdfgh** [MaaAssistantArknights/MaaAssistantArknights#6090]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在海月肉鸽中选择关卡有时会打开藏品页面然后卡住不动

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12445828/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12445829/gui.log)
23：18：59

### 还有别的吗？

mumu模拟器，win10
（无法上传图片使用压缩在下面的安装包里了）
[图片.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12445838/default.zip)

**Comment by asbdfgh** [comment]
[屏幕截图 2023-08-28 225317.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12455677/2023-08-28.225317.zip)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12455692/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12455693/gui.log)

**Comment by Lancarus** [comment]
#5892
