### ISSUE TITLE
maa连接不上mumu12模拟器（已解决），但maa无法自动启动mumu12模拟器，需手动打开（未解决）

### ISSUE THREAD

**Issue by Keiye** [MaaAssistantArknights/MaaAssistantArknights#6091]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在以管理员打开maa方式下，选择路径之后一直无法连接到mumu12模拟器，打开模拟器再点link start提示连接adb失败，尝试过群里的改adb接口改成7555，依然连接失败，关了adb重启之后，依然连接失败

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12447111/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12447112/gui.log)
最新时间点

**Comment by Keiye** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143302808/a600e56e-72c9-4eaf-88ec-a33f4e3b4da1)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143302808/c532b225-203b-48a4-b1c7-d369781e00c9)

**Comment by ABA2396** [comment]
这任务管理器里手动把adb关了试试。mumu12的端口早就不是7555了，可以在设置里看到，不过自动检测应该是能用的

**Comment by Keiye** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143302808/51960453-69c1-4c91-bf11-0a8a0f9c9f05)
开了自动检测以后，又在任务管理器里把adb关了，再尝试之后依然失败了

**Comment by Keiye** [comment]
不过为什么自动检测出来的端口还是7555
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143302808/68c80ef0-9a2b-4494-9715-f87ad8de71f6)

**Comment by Keiye** [comment]
尝试了将adb路径更换（maa群中提供软件）并把自动检测关掉以后，maa能成功连接mumu12模拟器。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143302808/99d5de56-e5f1-4609-9abe-ff4b92673beb)
但启动时依旧有连接不上模拟器的情况发生，需手动打开模拟器才能正常使用maa

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/42f72ff3-061d-49b6-b4d3-4580013ec299)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/8bd0b087-4abb-4109-a29c-15a24569e311)

**Comment by Sputnik103** [comment]
求助，我也遇到了相同的问题

**Comment by Sputnik103** [comment]
+1遇到了相同的问题，但是我自动检测在模拟器打开的情况下是可以运行的，当模拟器不打开时则都无法运行

**Comment by ABA2396** [comment]
> +1遇到了相同的问题，但是我自动检测在模拟器打开的情况下是可以运行的，当模拟器不打开时则都无法运行

没开模拟器怎么检测
