### ISSUE TITLE
肉鸽初始招募页面无法识别

### ISSUE THREAD

**Issue by green-bacon** [MaaAssistantArknights/MaaAssistantArknights#6092]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽启动时，招募页面如果出现三个以上干员招募档案，maa会无法正常进行招募，等待一段时间后直接结束本次探索。
使用MUMU12模拟器，minitouch。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12447116/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12447117/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66951334/3f96d3c2-1710-49b0-8c04-ab3fff08d3d1)
![MuMu12-20230827-103808](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66951334/78f8432a-ec2e-4217-847d-996918669273)

**Comment by Lancarus** [comment]
暂时不支持高规格分队
