### ISSUE TITLE
繁中服十一章主线导航手動輸入關卡名无法刷理智

### ISSUE THREAD

**Issue by vonnoq** [MaaAssistantArknights/MaaAssistantArknights#6095]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

選完關卡後只會不斷點擊上方關卡名

而不會點擊下方代理指揮跟開始行動

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12447235/asst.zip)

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121179930/c0bba473-a677-4680-91eb-7c451dd3ae36

**Comment by Constrat** [comment]
This was a present issue on the EN server. Let me remember how I fixed it.
