### ISSUE TITLE
萨米肉鸽刷钱中战斗卡死

### ISSUE THREAD

**Issue by nnnniiiiaaaa** [MaaAssistantArknights/MaaAssistantArknights#6099]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽，后勤分队百嘉开，在3/9/10（只运行了这三个难度）都碰到了战斗卡死的问题，其中两次在**待宰的兽群**。

最多一次存钱120+，其他都在大约40-50这样卡住。整个游戏像截屏贴图一样无法操作，重开后不影响刷理智，但刷钱仍有此问题。

使用逍遥模拟器，win11，MAA内测版v4.23.0-beta.1。

不太清楚具体发生了什么，这是我能想到的全部信息，如果被您注意到并解决的话不胜感激！

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12447474/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12447485/gui.log)

### 截图

只保留了最后一次的，前面几次除了存钱数不同其他情况没有区别。
<img width="595" alt="maa截图" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143314946/0e15d0b5-ed6f-4ffb-b7cf-c75314f5aef5">
<img width="833" alt="游戏截图" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143314946/687d4af1-8339-4ea6-b9b9-ec364ecfb19b">

### 还有别的吗？

逍遥模拟器，win11系统更新保持最新，MAA内测版v4.23.0-beta.1

**Comment by nnnniiiiaaaa** [comment]
补充：发现#6059反馈过类似问题，但刮痧/战斗10分钟均不符，我出现这种情况大概在挂机30-40分钟左右，百嘉技能期间。

**Comment by ABA2396** [comment]
> 整个游戏像截屏贴图一样无法操作

你这是模拟器卡了吧？试试换个模拟器，比如 蓝叠 mumu12，有些模拟器挂的时间长一点就卡了

**Comment by nnnniiiiaaaa** [comment]
之前试过mumu，也有同样的问题但是不像逍遥这么集中，我再换雷电试试！
非常感谢！



VOLCANO
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月27日(星期天) 下午5:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 萨米肉鸽刷钱中战斗卡死 (Issue #6099)





  
整个游戏像截屏贴图一样无法操作
  
你这是模拟器卡了吧？试试换个模拟器，比如 蓝叠 mumu12，有些模拟器挂的时间长一点就卡了
