### ISSUE TITLE
按使用说明中多开模拟器设置，复制的MAA无法识别到蓝叠多开的模拟器

### ISSUE THREAD

**Issue by akiriroll** [MaaAssistantArknights/MaaAssistantArknights#6103]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

问题同#5689，不同于#5847，看了一下这两个问题下面都没有解决办法
win11,蓝叠模拟器（非国际版），按使用说明设置了多开路径和附加命令[模拟器路径: C:\Program Files\BlueStacks_nxt\HD-Player.exe,附加命令: --instance Nougat32_1 --cmd launchApp --package "com.hypergryph.arknights"]，MAA副本可以正常运行命令，但link start时多开模拟器画面无反应，MAA识别不到画面空置运行后报错；MAA副本运行有概率与正常运行的原MAA冲突导致原MAA也空置

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12447978/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12447979/gui.log)

### 还有别的吗？

win11,蓝叠模拟器（非国际版）

**Comment by SherkeyXD** [comment]
参照 https://maa.plus/docs/用户手册/常见问题.html#指定-bluestacks-config-keyword 为不同的 MAA 设置 `Bluestacks.Config.Keyword`
