### ISSUE TITLE
maa连接蓝叠失败

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#6104]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

adb一直有问题，按照教程都试了，模拟器也试过雷电，mumu，蓝叠了，都不行

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12448042/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12448043/asst.log)

**Comment by SherkeyXD** [comment]
你的连接设置是什么样的

**Comment by ChengJie-tech** [comment]
我之前使用蓝叠5国际版也遇到了问题，尝试了更换ADB等一系列操作无果。
你在“模拟器 设定 - 进阶 中打开 Android调试桥”了吗，我启动后可以正常运行。

**Comment by aliezlo** [comment]
已解决
