### ISSUE TITLE
MAA双开时互相冲突，单独运行任一模拟器/MAA都可运行

### ISSUE THREAD

**Issue by zyqOUC** [MaaAssistantArknights/MaaAssistantArknights#6105]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

【背景】
本人有双开需求，之前使用蓝叠国际版&MuMu6可以稳定运行（之前行）。
近日升级MuMu12后出现相互冲突的问题，后多次重启、重装模拟器、重装MAA、管理员运行各软件均无效。

【详细描述】
模拟器1与模拟器2与对应的MAA同时运行时，单独运行任一MAA都可正常工作。
同时运行两个MAA时，两个都显示模拟器断开（见附图1）。
其中一个MAA正常运行时，启动另一个MAA，两个都会断开。
MAA的连接设置是由单独运行时自动获取（见附图2）。
强制替换ADB没成功过。
【控制变量】
模拟器测试了MuMu6、MuMu12、蓝叠国际版、夜神9，任意两款模拟器组合都会复现上述冲突问题。运行单一任务都正常。

【软件版本】
MAA版本：v4.21.0稳定版。已独立区分文件夹单独运行。MAA1与MAA2的debug都已上传。
模拟器1：MuMu12 V3.5.15(2018)
模拟器2：蓝叠国际版 5.12.115.1002 P64

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12448739/debug.zip)

### 截图

![bug](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90266493/9ec93ea4-98ee-47de-97b4-660055ab94f8)
![set](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90266493/db0177ef-f95a-4b60-801f-357318b11bcc)

### 还有别的吗？

Win10 64位 i5-8400 32g RAM

**Comment by ABA2396** [comment]
要用同一个adb

**Comment by Lancarus** [comment]
第一个自动获取到adb地址后，把这个地址复制到第二个maa里面，不要用自动

**Comment by zyqOUC** [comment]
已经OK了。谢谢各位。
ps如果可以的话希望这一个小tip可以加到用户手册里。谢谢。
