### ISSUE TITLE
使用带令的自动作业无法自动放置小龙

### ISSUE THREAD

**Issue by Maikouun** [MaaAssistantArknights/MaaAssistantArknights#6106]
### 说说你遇到的问题？

在这次tn-2的作业中使用带令的自动作业无法自动放置小龙

**Comment by SherkeyXD** [comment]
试试删除 cache/avatars 文件夹

**Comment by Lcy-NightLight** [comment]
> 试试删除 cache/avatars 文件夹

同这个问题，无法部署召唤物”弦惊“
avatars文件夹下无弦惊图片，删除后仍然无法部署召唤物”弦惊“，
Maa版本为v4.23.0-beta.1.d007.g020701351
模拟器为mumu模拟器6，adb(127.0.0.1:7555)
触控模式minitouch

**Comment by Constrat** [comment]
> Try deleting the cache/avatars folder

Unfortunately that is not enough. I've tried various MAA://2xxxx copilot's. The problem is with the identification of the avatar itself. Basically when you don't have enough deployment points DP, the image is darkened, usually MAA is not picky with normal operators because the avatars are more complicated, but with lLing' summons they have simpler avatars and are differentiated between darkened and lightened.
In my tests, MAA was still able to detect and place the summon, but every time it screen capped, it had to redetect the avatar (unless the DP >= 18)

**Comment by Lcy-NightLight** [comment]
> > Try deleting the cache/avatars folder
> 
> Unfortunately that is not enough. I've tried various MAA://2xxxx copilot's. The problem is with the identification of the avatar itself. Basically when you don't have enough deployment points DP, the image is darkened, usually MAA is not picky with normal operators because the avatars are more complicated, but with lLing' summons they have simpler avatars and are differentiated between darkened and lightened. In my tests, MAA was still able to detect and place the summon, but every time it screen capped, it had to redetect the avatar (unless the DP >= 18)

Thank you for your reply(or answer? i am not good at English) ,but i have a problem in avartars folder , there's no summon avatar called "弦惊 Xuanjing" but only a avatar called "清平 Qingping" Is that the same ? or some other reason?
And during the execution of Copilot , the Cost (DP) just have about 10 , then reach 18 , but the summon was not deployed correctly.
If i take a shot and put it into the avatars folder ,will this be useful?
Thank you :）

**Comment by Constrat** [comment]
Unfortunately it's not really an answer. It's just another point of view of the issue.

> If i take a shot and put it into the avatars folder ,will this be useful?
You could try taking a custom avatar but I have little to no clue in which part of the screen is used.

**Comment by MejiroSilence** [comment]
我的解决方案是把作业json文件里的弦惊全部改成清平将错就错(

**Comment by Lcy-NightLight** [comment]
> 我的解决方案是把作业json文件里的弦惊全部改成清平将错就错(
收到，已测试可以使用，万分感谢(^_^)

**Comment by SherkeyXD** [comment]
草

**Comment by Constrat** [comment]
Honestly, it's a "multiple" bug. The main issue is the different skill => different avatars => different names. Increasing the range for the avatar detection could be a way to approach this problem. But this means having to do the same thing for every operator, and usually this creates problems.

The other issue is the different avatars, but SAME skill / name, because of the DP cost, everytime the avatar becomes gray it screencaps it registers it again and again and again.

**Comment by Lcy-NightLight** [comment]
> Honestly, it's a "multiple" bug. The main issue is the different skill => different avatars => different names. Increasing the range for the avatar detection could be a way to approach this problem. But this means having to do the same thing for every operator, and usually this creates problems.
> 
> The other issue is the different avatars, but SAME skill / name, because of the DP cost, everytime the avatar becomes gray it screencaps it registers it again and again and again.

Anyway, I am just a user who uses this program to enhance the gaming experience.It would be enough to know how to fix this bug for me. But what about write a tip in MAA Copilot website(or other website else) to avoid this bug?(just a advice) :>

**Comment by Constrat** [comment]
This is definitely doable, especially considering Ling solo stages are pretty famous and used.
@MistEO

**Comment by negotyann** [comment]
成功了，请问一下大佬为什么我的maa延迟特别厉害，不管是实际切二倍速还是下干员都慢于maa自动战斗页面出现指令（泪目）

**Comment by Lcy-NightLight** [comment]
> 成功了，请问一下大佬为什么我的maa延迟特别厉害，不管是实际切二倍速还是下干员都慢于maa自动战斗页面出现指令（泪目）

我感觉自动页面出现的当前步骤是MAA准备执行的下一个动作(大概？)

**Comment by negotyann** [comment]
> > 成功了，请问一下大佬为什么我的maa延迟特别厉害，不管是实际切二倍速还是下干员都慢于maa自动战斗页面出现指令（泪目）
> 
> 我感觉自动页面出现的当前步骤是MAA准备执行的下一个动作(大概？)

没有，几乎所以战斗任务都会因为这个导致失败（泪目）
请问一下大佬有没有遇到过这样的情况，或者大佬用的是哪个模拟器qaq（我是mumu12）

**Comment by Constrat** [comment]
I found the best compatibility with bluestacks (nougat 32 seems the most stable)

**Comment by Lcy-NightLight** [comment]
> > > 成功了，请问一下大佬为什么我的maa延迟特别厉害，不管是实际切二倍速还是下干员都慢于maa自动战斗页面出现指令（泪目）
> > 
> > 
> > 我感觉自动页面出现的当前步骤是MAA准备执行的下一个动作(大概？)
> 
> 没有，几乎所以战斗任务都会因为这个导致失败（泪目） 请问一下大佬有没有遇到过这样的情况，或者大佬用的是哪个模拟器qaq（我是mumu12）

我是mumu6 不过楼上大佬说蓝叠模拟器好用 正好我回头也试试

**Comment by negotyann** [comment]
> > > > 成功了，请问一下大佬为什么我的maa延迟特别厉害，不管是实际切二倍速还是下干员都慢于maa自动战斗页面出现指令（泪目）
> > > 
> > > 
> > > 我感觉自动页面出现的当前步骤是MAA准备执行的下一个动作(大概？)
> > 
> > 
> > 没有，几乎所以战斗任务都会因为这个导致失败（泪目） 请问一下大佬有没有遇到过这样的情况，或者大佬用的是哪个模拟器qaq（我是mumu12）
> 
> 我是mumu6 不过楼上大佬说蓝叠模拟器好用 正好我回头也试试

那我这就去试试看蓝叠~感谢大佬~

**Comment by MistEO** [comment]
没看到日志，那我只好给你们算一卦了.jpg

**Comment by ABA2396** [comment]
[蓝叠模拟器每次启动端口号都不一样（Hyper-V）](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7-hyper-v)

**Comment by negotyann** [comment]
> [蓝叠模拟器每次启动端口号都不一样（Hyper-V）

原来如此~感谢大佬~

**Comment by negotyann** [comment]
为啥“感谢大佬”会被划掉（大雾

**Comment by SherkeyXD** [comment]
> 为啥“感谢大佬”会被划掉（大雾

因为\~在markdown语法中有特殊含义，被两个\~包起来的~中间会被画上删除线
如果想要正常使用\~，需要写成\\\~

**Comment by negotyann** [comment]
> > 为啥“感谢大佬”会被划掉（大雾
> 
> 因为~在markdown语法中有特殊含义，被两个~包起来的~中间会被画上删除线 如果想要正常使用~，需要写成\~

原来如此（doge
