### ISSUE TITLE
MAA无法连接MuMu12模拟器

### ISSUE THREAD

**Issue by Imipenem1265** [MaaAssistantArknights/MaaAssistantArknights#6107]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

从8月22日开始至今一直如此，**尝试重装MAA、重装模拟器、更换触控模式、重启电脑、强制替换ADB、反复尝试自动连接、回退至老版本MAA**均无效，下载QQ群内提供的工具包替换ABD也无效.手动在自动连接后在任务管理器中结束adb.exe再尝试连接仍然显示连接失败。换用蓝叠5中文版重复上述尝试，结果故障依旧。期间一直是通过管理员权限启动MAA。
<img width="600" alt="屏幕截图 2023-08-28 163209" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143390409/9c4d724d-d3a7-4914-8245-300a49976753">

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12452438/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12452464/gui.log)

### 截图

<img width="603" alt="屏幕截图 2023-08-22 111951---10-11" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143390409/2de74fe8-22c5-4cd1-a32c-0b875f444a9a">
<img width="600" alt="屏幕截图 2023-08-28 163209" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143390409/323d457f-796c-4bf1-8dd5-fefe8a0f4175">
图片一截图于11:19:21,Aug22th,2023
图片二截图于16:32:09,Aug28th,2023

### 还有别的吗？

模拟器：mumu12.0

> 模拟器配置：
基础信息
UUID :  db50faeb-fee7-4d01-a898-2a7767c69685
模拟器版本 :  3.5.4.1866
模拟器磁盘（可用/总）空间 :  117.1GB/125GB
日志路径 :  d:\Program Files\Netease\MuMuPlayer-12.0\vms\MuMuPlayer-12.0-0\logs\

运行环境
VT :  开启
Hyper-V :  关闭
网络环境检测 :  正常
以管理员运行方式 :  是
DirectX 11是否安装 :  是
防火墙 :  开启（建议关闭）

电脑配置
主板型号 :  Manufacturer: CML  Product: Sneezy_WC
CPU :  Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
系统版本 :  Windows 10 64-bit Kernel 10.0.19045
显卡驱动 :  正常
显卡驱动型号 :  31.0.101.2111 (20220719)
所有显卡 :  Intel(R) UHD Graphics  |  Microsoft Basic Render Driver
当前使用显卡 :  Intel(R) UHD Graphics
安装磁盘(可用/总)空间 :  53.5GB/237.9GB
可用内存/总内存 :  975.5MB/7.8GB

模拟器设置
Root :  开启
显卡渲染模式 :  DirectX 模式
性能设置 :  4核/3GB
手机型号 :  Xiaomi 12S
分辨率 :  1600 * 900
高帧率 :  开启

连接设备
音频输入 :  已连接
音频输出 :  已连接

网络信息
MuMu DNS :  182.254.116.116
电脑DNS :  182.254.116.116
Rom MAC地址 :  08:ae:df:2a:80:00

ADB调试端口 :  16384
MuMu出口IP地址 :  10.0.2.15
电脑出口IP地址 :  1.62.202.24

其它信息
其它版本信息 :  vm: 120.1.22.005 hyperv: 6.3.14.0 renderer: 0.0.115.0
Vendor :  NetEase
OpenGL Renderer :  MuMu GL (Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0)
OpenGL Version :  OpenGL ES 3.1

> 操作系统：Windows10 22H2

**Comment by Imipenem1265** [comment]
细节补充：22日上午还运行正常，关机后吃个午饭的功夫再开机就开始报错

**Comment by aliezlo** [comment]
同，我的也是

**Comment by Maikouun** [comment]
同mumu12 今天刚开始报错

**Comment by ntgmc** [comment]
我的大致方法是：
1.任务管理器关闭ADB.exe
2.确保ADB.exe的全路径无中文
3.使用CMD命令`adb devices`获取端口，如果获取成功再连就能连上，获取失败就需要重启adb进程
4.尝试使用退出时释放ADB和使用ADB Lite

**Comment by Imipenem1265** [comment]
> 

1.我上面已经试过了，无效；
2.无论是mumu12还是MAA的adb.exe都是全英文的目录，路径上没有英文之外的字符；
3.这个有一点问题一会再说；
4.”退出时释放ADB“我一直在选的，‘使用ADB Lite“除了徒劳的延长等待时间外起不到任何作用……

> 

> 3.我在CMD里输这个指令一直提示"ADB不是文件或命令”，想问一下3.该如何实现？

**Comment by Imipenem1265** [comment]
好消息，**重启完电脑后进MAA开ADB LITE**，再连接mumu12，一次成功了。
<img width="600" alt="屏幕截图 2023-08-29 190239" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143390409/bb9d67ff-498d-4523-92c2-87e684395b29">
<img width="600" alt="屏幕截图 2023-08-29 190310" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143390409/a7d915fb-f7f7-4f9e-a2f0-8150ade67ea4">
<img width="600" alt="屏幕截图 2023-08-29 190757" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143390409/52170d75-fde9-4af1-b535-ecb7f79f34c6">

**不过现在还不能确定故障是否完全解除**，等理想城活动复刻了我再看看，如果没问题了我再移动到“已解决”里面去。

**Comment by Imipenem1265** [comment]
不过我也想不通：为什么我两天前（27日）也像今天一样重启之后进MAA开ADB LITE，为什么两天前那次直接卡死而这一次却成功了……明明是一样的连接设置啊……

**Comment by Zhuym07** [comment]
另一种解决方法
来自 https://segmentfault.com/q/1010000043163421

打开 Control Panel > System and security > Windows defender firewall > Allowed applications 并添加 adb.exe（私人和公共网络）。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34023479/8564b0de-bf5d-4511-a762-6a8d014d3f4e)

或在每次运行前使用管理员CMD运行
adb start-server
