### ISSUE TITLE
算术运算导致溢出。

### ISSUE THREAD

**Issue by leslie-lw** [MaaAssistantArknights/MaaAssistantArknights#6116]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 遇到了问题
算术运算导致溢出。
解决方案
出现未知错误
详细信息
System.OverflowException: 算术运算导致溢出。
   在 MaaWpfGui.Main.AsstProxy.AsstConnect(IntPtr handle, String adb_path, String address, String config)
   在 MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<LinkStart>d__74.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12454799/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12454800/gui.log)

### 还有别的吗？

模拟器为Mumu模拟器12，系统为Win11

**Comment by ABA2396** [comment]
9bb3c878f841c3cb5d765627be6d93dc369e4709 fixed
