### ISSUE TITLE
无法连接模拟器

### ISSUE THREAD

**Issue by Ns2Kracy** [MaaAssistantArknights/MaaAssistantArknights#6117]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用内测版更新到最新的v4.23.0-beta.1.d014.gde01df6af版本后无法连接到mumu模拟器

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12454818/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12454823/gui.log)

### 截图

![01b76db8135427f4bca082c1b7e6fbcc](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89824014/8712df6a-08eb-4112-99ad-e76d2efd8e45)

**Comment by ABA2396** [comment]
9bb3c878f841c3cb5d765627be6d93dc369e4709 fixed
