### ISSUE TITLE
System.TypeInitializationException: “System.Windows.Automation.Peers.AutomationPeer”的类型初始值设定项引发异常。 ---> System.TypeLoadException: 程序集“PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”中的类型“MS.Internal.Automation.SelectionProviderWrapper”的方法“GetSelection”没有实现。

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#6125]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

报错的ui都加载不出来 只能在gui.log中查看到相关问题

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12460347/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12460349/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/0805b22f-69c0-4080-b00e-d457369bcd98)
我确认过他运行库都是安装过的
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/a1fe8f60-6a14-4386-a750-6ddf93528fbb)

**Comment by cuiliang** [comment]
我在其它软件里遇到类似现象，是某个系统补丁造成的，可以参考这里试试 https://getquicker.net/KC/Kb/Article/1092 我目前还不确定具体是哪个补丁，如果你有验证，也请告知。

**Comment by ABA2396** [comment]
这个之前就提到过，也是我们准备上.net8的原因之一了）

**Comment by ntgmc** [comment]
> 我在其它软件里遇到类似现象，是某个系统补丁造成的，可以参考这里试试 https://getquicker.net/KC/Kb/Article/1092 我目前还不确定具体是哪个补丁，如果你有验证，也请告知。

![1694243997901](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/630e0a04-5fcc-4d86-98ac-6e4685e39990)解决了
