### ISSUE TITLE
萨米肉鸽中令始终使用一技能

### ISSUE THREAD

**Issue by raevoioj** [MaaAssistantArknights/MaaAssistantArknights#6127]
### 说说你遇到的问题？

精二后也一直使用的是一技能，请问是没有设置使用三技能吗

**Comment by Imipenem1265** [comment]
好像是OCR的模块认不出来带时装的“弦惊”，导致用不了3技能。
你看一下用初始/精二立绘的令会不会用3技能，如果会就是OCR的问题，若还是用不了那应该是MAA把令的3技能给禁止识别了。

**Comment by Imipenem1265** [comment]
[https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6079](url)
或者也可以看看这个链接里面的解决方法

**Comment by SherkeyXD** [comment]
正常情况下令是会使用三技能的
可以发个日志看看吗

**Comment by raevoioj** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12470700/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12470701/gui.log)

**Comment by Lancarus** [comment]
版本过老，请更新到内测版
