### ISSUE TITLE
水月肉鸽中的若干站位问题

### ISSUE THREAD

**Issue by Sam-0324** [MaaAssistantArknights/MaaAssistantArknights#6128]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

大君遗脉中把桃金娘放在(3,3)，且未在(3,4)和(3,5)放置干员，导致战斗失败。
![大君遗脉](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70825063/bb51b574-3685-4496-b184-e8d49fe8dfb6)

饥渴中，开局在(3,2)朝下放置了两次起重机，第一个怪漏怪后才在(3,3)放置百炼嘉维尔。
![饥渴](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70825063/1b4bc8d1-692c-40b1-8ab9-2f5045e2fbb3)

据险固守中，于(5,3)放置干扰地雷。（注：我手动开启了**一次**百炼嘉维尔的技能，不知道是不是这个的问题）
![据险固守](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70825063/319e7de5-f58e-49c0-983f-22b9581fd1f8)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12463213/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12463217/gui.log)

大君遗脉 - 18:14:30
饥渴 - 18:05:53
据险固守 - 17:07:31
*时间点可能不准确，误差约一分钟

**Comment by Lancarus** [comment]
@Yumi0606 看下？

**Comment by Yumi0606** [comment]
回复:
1.大君遗脉的部署逻辑确实有问题,对于少地面的极端情况可能漏怪.现在3,3只下投锋.maa并不会因为骑士在右边就优先在左边放干员,目前固定以4,4→3,4→4,5→3,5的顺序放.
2&3.是因为支援道具不在recruitment中,maa不认识会自己放,现在提交修复.
