### ISSUE TITLE
公招识别没有棘刺

### ISSUE THREAD

**Issue by A-Magic-Cube** [MaaAssistantArknights/MaaAssistantArknights#6132]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

公招识别没有棘刺

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12471123/asst.log)
2023-08-30 08:32:31.307附近

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96335643/71ca1919-1e32-4985-8d0e-4afa78702809)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96335643/141d81e0-8955-4411-bb9a-856d1892aeff)

**Comment by MistEO** [comment]
你的日志不知道为什么打不开，再发下。

另外检查下版本，是不是版本太老了，棘刺是刚加入的

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/recruitment.json#L1425
