### ISSUE TITLE
蓝叠(hypev)无法识别吃药界面,无限重复弹出吃药界面

### ISSUE THREAD

**Issue by WantChane** [MaaAssistantArknights/MaaAssistantArknights#6134]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在刷理智任务下,无论是否设置吃药,包括无限制吃48小时内过期的理智药,都无法识别当前理智补充界面,以及点击对勾,导致无限重启,直到理智回复到满足下次进入关卡.
但有时可以识别到理智清空,进行下次任务,但仍然无法进行吃药

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12472818/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12472822/gui.log)
问题出现时间集中在每天四点之后,8月30日无限重启至7点左右,由我手动停止后继续任务.
另外问题还出现过在周末,当时由我自己完成吃药操作

### 还有别的吗？

模拟器:蓝叠国际版 Hype-V
操作系统:win10
MAA版本:经我个人测试,从云间清醒梦开始,包括稳定版,公测版,内测版均有该问题

**Comment by WantChane** [comment]
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12480930/debug.zip)
现场 8.31 早晨

**Comment by drunkenQCat** [comment]
我这里也遇到了同样的问题。

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12734897/gui.log)
[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12734895/asst.bak.zip)

使用的版本是的4.20.0-rc.1

**Comment by zzyyyl** [comment]
> 我这里也遇到了同样的问题。
> 
> [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12734897/gui.log) [asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12734895/asst.bak.zip)
> 
> 使用的版本是的4.20.0-rc.1

更新一下再试试（

**Comment by drunkenQCat** [comment]
我解决了。是手机太卡了，点“开始行动”三秒钟才出下一个界面。只要把ocr间隔时间调成3000就好了。

**Comment by drunkenQCat** [comment]
> > 我这里也遇到了同样的问题。
> > [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12734897/gui.log) [asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12734895/asst.bak.zip)
> > 使用的版本是的4.20.0-rc.1
> 
> 更新一下再试试（


我解决了。是手机太卡了，点“开始行动”三秒钟才出下一个界面。只要把ocr间隔时间调成3000就好了。

**Comment by zzyyyl** [comment]
时间久了，还有问题开新 issue
