### ISSUE TITLE
VideoRecognition任务出错

### ISSUE THREAD

**Issue by wasfl** [MaaAssistantArknights/MaaAssistantArknights#6136]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗无法使用

### 日志文件

2023-08-30 18:14:11.689
2023-08-30 18:24:38.343
2023-08-30 1
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12475285/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12475287/gui.log)

8:33:11.682

**Comment by MistEO** [comment]
视频识别？视频链接来一个

**Comment by wasfl** [comment]
https://www.bilibili.com/video/BV1r94y167gV?p=3&vd_source=5cd434f4f7cacf4942d20dd97f85accd
视频已缓存，分辨率1080p.

**Comment by MistEO** [comment]
没法识别定向试炼，镜头移动就直接搞不定了

**Comment by wasfl** [comment]
哦，谢谢了
