### ISSUE TITLE
萨米肉鸽选择刷等级无论什么关都是不放角色不停失败

### ISSUE THREAD

**Issue by 17817468559** [MaaAssistantArknights/MaaAssistantArknights#6138]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽选择刷等级无论什么关都是不放角色不停失败

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12477171/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12477178/asst.zip)

### 截图

没截到...

### 还有别的吗？

蓝叠模拟器5
win10
CPU：R5 3600x
显卡：6800XT

**Comment by Lancarus** [comment]
更新内测版试试
