### ISSUE TITLE
再增加一个备选关卡选项

### ISSUE THREAD

**Issue by ATFmxyl** [MaaAssistantArknights/MaaAssistantArknights#6139]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在已经有两个备选关卡可供选择，
是否考虑再增加一个选项，以实现对常规活动材料关卡和日常材料关卡的完整覆盖，
这样就能在关卡中选择进入剿灭模式，
备选项如下：
备选1：常规活动材料关卡
备选2：红票5
备选3：技能5

**Comment by ABA2396** [comment]
这样就只有剿灭打完了报错（没有入口）之后才会进后面的关卡，而且吃理智药等功能是不生效的。现在有了剿灭扫荡还需要放在关卡选择里刷吗

**Comment by ATFmxyl** [comment]
我测试的时候没注意过,吃48小时内过期理智药功能好像是生效的,后续我观察一下看看
,主要还是懒得自己每周手刷或者切换maa的剿灭模式来刷一次剿灭,放关卡选择里面我就等着每天每次定时执行的时候等着找不到剿灭入口报错后走备选关卡了
