### ISSUE TITLE
MAA无法获取检查更新v4.23.0-beta.2

### ISSUE THREAD

**Issue by YuhangTom** [MaaAssistantArknights/MaaAssistantArknights#6145]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA卡在v4.23.0-beta.1无法检查更新v4.23.0-beta.2 内测公测都显示已是最新版本

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12482473/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12482474/gui.log)

### 截图

<img width="878" alt="Untitled" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45880737/d85dcf75-469d-4151-ac7f-22138f57a861">

### 还有别的吗？

夜神7.0.5.8
win11

**Comment by wangl-cc** [comment]
API里面的版本信息没有更新，应该不是客户端的问题。

**Comment by YuhangTom** [comment]
现在又可以更v4.23.0了
