### ISSUE TITLE
水月肉鸽卡在藏品列表之后不动

### ISSUE THREAD

**Issue by Kiaschme** [MaaAssistantArknights/MaaAssistantArknights#6148]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

水月肉鸽第四层，点开藏品界面并持续显示“已放弃本次探索”，此后无操作，我手动关闭藏品界面后真的给我放弃了😭😭😭😭

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12483277/debug.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111210702/53d60676-2c17-4245-b007-a90642e84bcf)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111210702/f3bef037-e5cc-41c7-ab52-b292b3ec269b)

### 还有别的吗？

雷电 9.0.46(9)  win11 22H2   刷等级  以人为本分队

**Comment by Lancarus** [comment]
#5892
