### ISSUE TITLE
mumu12更新之后游戏界面没反应

### ISSUE THREAD

**Issue by raging888** [MaaAssistantArknights/MaaAssistantArknights#6153]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

中午刚开电脑,网易mumu12更新了,版本号3.5.15,然后刚开始还正常,打开游戏后在游戏启动界面就开始没反应了,直接没有任何操作

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12483769/gui.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12483775/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12483776/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143695189/2102ccc5-878b-4503-8102-7a5f199dce98)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143695189/dc8be8f7-ae1d-47bf-bf72-7a13f44a82d3)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143695189/49f7b5f3-c7dd-4233-9f07-8e0bb56ab458)

**Comment by ABA2396** [comment]
设置里有开后台保活吗

**Comment by A-Pupils-form-china** [comment]
同样遇到了这个问题，更新前正常，更新后就不行了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36190484/f0f5654f-d876-4948-a936-7498ce65bf9f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36190484/d5e4ffa2-576b-4061-b850-e9850fbed354)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12486023/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12486024/gui.log)

**Comment by ABA2396** [comment]
https://t.bilibili.com/835724859701985289#reply183951659664

**Comment by raging888** [comment]
> 设置里有开后台保活吗

开了，但就是没反应，不知道啥原因

**Comment by ABA2396** [comment]
关了然后重启

**Comment by gdf159159** [comment]
> 关了然后重启

不需要关 先启动mumu多开器 用他启动模拟器 就可以截屏到游戏窗口  我最近一直这面用的可以说100%成功

直接启动模拟器 有概率出现截屏的问题 adb截屏出来的画面一直是桌面

**Comment by ABA2396** [comment]
> 不需要关 先启动mumu多开器 用他启动模拟器 就可以截屏到游戏窗口 我最近一直这面用的可以说100%成功
> 
> 直接启动模拟器 有概率出现截屏的问题 adb截屏出来的画面一直是桌面

是 mumu 更新了 3.5.15 之后遇到的吗

**Comment by gdf159159** [comment]
> > 不需要关 先启动mumu多开器 用他启动模拟器 就可以截屏到游戏窗口 我最近一直这面用的可以说100%成功
> > 直接启动模拟器 有概率出现截屏的问题 adb截屏出来的画面一直是桌面
> 
> 是 mumu 更新了 3.5.15 之后遇到的吗

3.5.12的时候我就用这个办法 
后台挂机保活功能就可以用

反复重启模拟器 也有概率 可以直接成功
