### ISSUE TITLE
建议添加公招只刷新不招募的功能

### ISSUE THREAD

**Issue by Deo-777** [MaaAssistantArknights/MaaAssistantArknights#6155]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

您好，

建议添加公招的新功能，使其能在公招不出4*+tag时不使用招募券。

谢谢。

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/425ede84-c884-43f9-9ffc-cfda354fbbae)

**Comment by Deo-777** [comment]
喔原来还能这样解决！谢谢
