### ISSUE TITLE
TN-3地图出现变动

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#6156]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

TN-2、4没变，1没保留截图

### 日志文件

无

### 截图

旧：
![act3bossrush_tm03](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/752740d6-b555-4df7-8213-ca23a8bb1a05)
20230831下午更新之后：
![act3bossrush_tm03](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/1396d7fe-67ae-4308-9618-55c909c3c730)

**Comment by gdf159159** [comment]
同样的问题 4.23正式以后不知道改动了什么 地图坐标识别 跟之前对不上 导致干员下不去

4.23 b1是好使的

**Comment by status102** [comment]
> 同样的问题 4.23正式以后不知道改动了什么 地图坐标识别 跟之前对不上 导致干员下不去
> 
> 4.23 b1是好使的

其实是游戏里的地图变了（指TN-3）

**Comment by gdf159159** [comment]
> > 同样的问题 4.23正式以后不知道改动了什么 地图坐标识别 跟之前对不上 导致干员下不去
> > 4.23 b1是好使的
> 
> 其实是游戏里的地图变了（指TN-3），MAA继续往之前的位置放，就对不上了

是这样 哦 我早上用的23b1刷的 下午更新23就不好使 手动刷了几把弄完了
