### ISSUE TITLE
萨米肉鸽中使用羽毛笔建议选择二技能

### ISSUE THREAD

**Issue by rikumi** [MaaAssistantArknights/MaaAssistantArknights#6157]
### 在提问之前...

- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在 MAA macOS 版，萨米肉鸽中使用羽毛笔开局，发现会自动选择羽毛笔的一技能，强度十分一般。不知道大多数玩家都是练的哪个技能，感觉用二技能会好一些，至少不会在一些比较简单的关卡暴毙。

### 有什么好的想法？

为羽毛笔选择二技能，或者可以自选每个干员（至少是开局干员）带的技能。

### 其他内容

MAA 版本：v4.23.0（389）

**Comment by SherkeyXD** [comment]
要自选干员的技能，你可以修改 resource\roguelike\Sami\recruitment.json 中对应干员的 skill 值
不选用二技能的原因主要是减少操作成本，避免卡顿
