### ISSUE TITLE
(台服) 部分干员仍无法识别

### ISSUE THREAD

**Issue by Jimmy8870** [MaaAssistantArknights/MaaAssistantArknights#6159]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

接之前 #5865 问题
MMA更新到4.23.0后仍然有部分干员于自定义基建排班中无法找到(自己测试发现的有霜华: 于gui.log[2023-08-31 20:20:31.876] 明椒: 于gui.log[2023-08-31 20:31:33.572])
其中霜华后面有找到,但MAA最后只选择了霜华,导致原本设定应放5人的中枢只有一人
而干员识别也仍有部分干员无法识别 (明椒 THRM-EX)

最后提个其它小问题,设定脚本结束时退出明日方舟无法生效,而其它关闭MMA和模拟器则皆正常

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12486174/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12486175/gui.log)

### 截图

![Inkedbandicam 2023-08-31 20-16-29-358](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/516fdf21-3fd1-4f73-9b62-2b07973709bf)
![2023-08-31_20-15-38-821_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/d402c369-9812-41a0-9dcb-055fbbc19763)
![2023-08-31_20-15-40-074_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/05ba1c48-8ddd-4530-9e2b-b11dfff5be6f)
![2023-08-31_20-15-51-040_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/17ad3893-bc01-4586-8502-03a9b430e96d)
![2023-08-31_20-15-58-368_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/079348a0-e1e7-40bd-bfb4-5075a9990965)
![2023-08-31_20-15-59-546_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/cba8d7bd-6097-4dad-be76-2596c6430a44)
![2023-08-31_20-16-00-672_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141603152/8031955c-7958-4132-9e52-e14c15855813)

### 还有别的吗？

除雷电模拟器版本(9.0.57)皆同 #5865

**Comment by Constrat** [comment]
Looked at the logs, for THRM-EX the issue seems to be the "preferred" unit selection. It reads a "C" when there is none, I suggest removing favourite operators...
