### ISSUE TITLE
开局错误技能，并且不会更改

### ISSUE THREAD

**Issue by huazhizjie** [MaaAssistantArknights/MaaAssistantArknights#6160]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用战术突击小队，开局找的角色，比如棘刺银灰只带一技能不改变

### 日志文件

****

**Comment by SherkeyXD** [comment]
请发日志，没有日志我们无法分析
