### ISSUE TITLE
更新4.23版本后用默认的minitouch连接不上模拟器，无反应，用ADB input可以连上，但隔一段时间会导致明日方舟卡死，无法重连

### ISSUE THREAD

**Issue by ABA2396** [MaaAssistantArknights/MaaAssistantArknights#6165]
### Discussed in https://github.com/orgs/MaaAssistantArknights/discussions/6164

<div type='discussions-op-text'>
Originally posted by **SakuraMonster1** September  1, 2023
</div>

### 问题描述

更新4.23版本后用默认的minitouch连接不上模拟器，无反应，用ADB input可以连上，但隔一段时间会导致明日方舟模拟器卡死，无法重连，之前用的4.21版本没有这个问题

**Comment by SakuraMonster1** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/67091292/47bee267-4661-4e62-8ab3-b6ea8a7c0397)
昨天我两个电脑都更新了，出了问题之后我把之前的4.21版本替换了，debug depot的文件夹没了，我试试看能不能复现这个问题，等会再重新提交下

**Comment by SakuraMonster1** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12492310/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12492311/asst.log)
![苔手](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/67091292/0151f920-fea5-449f-9eea-e583fdc2a74e)
![违和](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/67091292/452df2d7-de32-470b-bca6-8bf40cb7050f)

**Comment by MistEO** [comment]
v4.23.3 fixed
