### ISSUE TITLE
需求: 森空岛自动签到功能

### ISSUE THREAD

**Issue by Luoxcat** [MaaAssistantArknights/MaaAssistantArknights#6167]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by SherkeyXD** [comment]
目前的问题主要是森空岛的 app 无法在大部分模拟器上安装

**Comment by xxyz30** [comment]
> 目前的问题主要是森空岛的 app 无法在大部分模拟器上安装

直接走http请求，只需要用户手动输入一个cred即可~

**Comment by SherkeyXD** [comment]
> 直接走http请求，只需要用户手动输入一个cred即可~

那已经有了，没必要再造轮子
https://github.com/Maojuan-lang/SenKongDao

**Comment by xxyz30** [comment]
> 那已经有了，没必要再造轮子 https://github.com/Maojuan-lang/SenKongDao
顺便推一下我的，有详细教程（x
https://github.com/xxyz30/skyland-auto-sign

**Comment by WSMTBG** [comment]
> > 那已经有了，没必要再造轮子 https://github.com/Maojuan-lang/SenKongDao
> > 顺便推一下我的，有详细教程（x
> > https://github.com/xxyz30/skyland-auto-sign

进不去

**Comment by SherkeyXD** [comment]
> 进不去

现在已由 MaaAssistantArknights/MaaSkland 实现

**Comment by xxyz30** [comment]
> > > 那已经有了，没必要再造轮子 https://github.com/Maojuan-lang/SenKongDao
> > > 顺便推一下我的，有详细教程（x
> > > https://github.com/xxyz30/skyland-auto-sign
> 
> 进不去

之前那个白嫖被github删了，用这个https://gitee.com/FancyCabbage/skyland-auto-sign
