### ISSUE TITLE
添加在萨米肉鸽刷隐藏坍缩范式的功能

### ISSUE THREAD

**Issue by unique9464** [MaaAssistantArknights/MaaAssistantArknights#6171]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

隐藏坍缩概率太低，手刷太难了

### 有什么好的想法？

是否可以设定在每一关先漏一个怪再下干员，这样能比较轻松地涨坍缩值，可以帮助刷隐藏坍缩。

### 其他内容

看之前水月肉鸽有刷指路鳞的功能，不知道这次肉鸽能不能加个刷隐藏坍缩的功能

**Comment by Saratoga-Official** [comment]
#9172 已增加
