### ISSUE TITLE
Mumu12不打开模拟器时连接失败

### ISSUE THREAD

**Issue by Sputnik103** [MaaAssistantArknights/MaaAssistantArknights#6172]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开模拟器主界面后maa正常运行没有问题（打开模拟器但不打开游戏也可以正常运行开始唤醒功能），但是在不打开模拟器时运行maa开始唤醒功能，会出现一个应用的框一闪而过，出现之后马上消失，然后无法正常连接客户端，显示连接失败，正在尝试启动模拟器

### 日志文件

9月1日13:56附近
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12494820/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12494821/gui.log)

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91364589/80793aa8-6863-4cb9-9831-29cac5ffac25

录屏文件

### 还有别的吗？

windows11，Mumu12

**Comment by Sputnik103** [comment]
> 



> 启动设置里的模拟器路径填的啥

现在在外面没法截图，模拟器路径之前选的都是自动检测，并且自动检测后显示的路径已经检查过是mumu里正确的adb路径，且路径不包含中文内容

**Comment by ABA2396** [comment]
自动检测检测的是adb路径，模拟器路径是要自己填的

**Comment by Sputnik103** [comment]
> 

哦感谢提醒，我自己填的是和adb路径相同的，请问是否正确？就是adb.exe文件的路径

**Comment by ABA2396** [comment]
要填模拟器路径啊，你点什么开的模拟器就填那个图标的路径
