### ISSUE TITLE
当自动战斗携带了作业中不需要的麒麟X夜刀时，会反复暂停查看干员

### ISSUE THREAD

**Issue by Lixuhuilll** [MaaAssistantArknights/MaaAssistantArknights#6173]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我平时喜欢多带一个麒麟X夜刀好手操补救，本次更新后，只要作业不要求带麒麟X夜刀，MAA就会反复暂停查看干员。
已尝试清理缓存，无效果。尝试将额外带的麒麟X夜刀换成其他干员后，不再反复暂停。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12494887/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12494889/gui.log)

**Comment by ABA2396** [comment]
现在改名了，人现在加麒麟R夜刀，之后文件要改改
