### ISSUE TITLE
网络波动所带来的问题与解决建议

### ISSUE THREAD

**Issue by CCFF00** [MaaAssistantArknights/MaaAssistantArknights#6175]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

<img width="824" alt="mmexport1693552745468" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56722154/3d2324d4-e81f-41ac-8a87-d9a12b150407">
由于网络波动导致的卡顿，希望maa增加长时间未响应中断任务的功能。

### 日志文件

上一个问题发过

**Comment by SherkeyXD** [comment]
Duplicate of #6175
