### ISSUE TITLE
定时启动等待模拟器开启后就不动了

### ISSUE THREAD

**Issue by LeviZhang1996** [MaaAssistantArknights/MaaAssistantArknights#6179]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

 情况是这样的，我设置了定时任务，按照基建JSON进行。MAA拉起模拟器之后，会等待模拟器loading完成，但是等待结束后就不动了。
![WJ{K``}X%{TVFXFLMWGNVR9](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/83460341/f5b52cb0-da29-4868-accb-8a83d0090a32)

根据我的观察，似乎与ADB路径有关。我需要强制替换ADB，然后就能定时执行成功（比如我15:30强制替换ADB，然后把定时任务设置成15:31，15:31就能正确执行）如下图。
![}Y_~%0GZPNDIG{Q_1~AI12Q](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/83460341/b09a7e38-95e6-40c4-9ba9-cad2fed59c16)

不光是定时任务，link start方式启动也会出现ADB连接失败必须强制替换ADB的问题。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/83460341/86535e27-f905-4239-91bc-8041d5c6c2f7)

但是ADB的路径会被替换成模拟器ADB路径（C:\Program Files\BlueStacks_nxt\HD-Player.exe）。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/83460341/d7b59a37-2b7d-459b-80b8-44489c1956c4)

此外，这个问题似乎是**自从我使用了多个全局配置功能之后出现的。**

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12497086/debug.zip)
压缩包内包含asst.log和gui.log

### 还有别的吗？

蓝叠5国际，Win10

**Comment by ABA2396** [comment]
看日志停住不动是资源加载问题，这个新版本已经改掉了。

> 但是ADB的路径会被替换成模拟器ADB路径（C:\Program Files\BlueStacks_nxt\HD-Player.exe）。

你点强制替换的时候adb还开着，所以替换失败了用了临时路径（maa文件夹下的adb），临时路径里的adb已经是能用了，但是你开了自动检测+始终检测，每次启动都会自动去找模拟器的adb，这样临时路径又被你替换成模拟器路径了，既然你用的不是hyperv版本的蓝叠，那就没必要开这两个检测
