### ISSUE TITLE
3.9.0-Beta7 无法打开程序

### ISSUE THREAD

**Issue by jtyuan** [MaaAssistantArknights/MaaAssistantArknights#618]
版本：3.9.0-Beta7
运行环境：夜神模拟器

问题描述：
打开助手程序后窗口内容一片空白，再弹出数声错误音效后程序终止。
尝试过下载压缩包覆盖安装，以及以管理员身份运行程序，均无法解决该问题。
而将压缩包解压到全新的目录后，可顺利打开。并且将 `gui.json` 配置文件拷贝过来后，即可使用之前的配置。（说明应该不是某些设置导致的问题）

问题视频：
https://user-images.githubusercontent.com/4654051/170887288-7e50f23b-f497-4a4f-b796-dad90482127b.mp4

程序日志：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8794091/asst.log)

导出的windows系统日志：
[events.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8794094/events.txt)

gui.json (因为github不支持json格式，加了txt后缀)
[gui.json.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8799684/gui.json.txt)

**Comment by wb871029** [comment]
同样无法打开，和模拟器环境无关，都没开始连

**Comment by wb871029** [comment]
不用更新和覆盖方式，直接解压新文件夹夹能打开了

**Comment by zzyyyl** [comment]
对的，之前我在 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/605#issuecomment-1140408889 提到的也是这个问题，现在 beta6 到 beta7 也不行了，并且文件夹下还是出现了个 `NewVersionExtract` 文件夹......

**Comment by zzyyyl** [comment]
[gui.json.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8797058/gui.json.txt)
姑且传一个 `gui.json` 以供测试
