### ISSUE TITLE
建议博朗台碎石模式在倒计时时间较长时直接碎石

### ISSUE THREAD

**Issue by pingplug** [MaaAssistantArknights/MaaAssistantArknights#6180]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

博朗台碎石模式在倒计时还有4分多甚至5分多的时候仍然等到理智+1再碎石，对于直接连手机的使用模式下很可能直接等到黑屏。。。

### 有什么好的想法？

对于绝大多数关卡，二倍速下不会超过3分钟，识别到倒计时在3分钟以上时完全可以直接碎石，不用等理智+1。（当然这个时间也可以让用户设置）

**Comment by status102** [comment]
碎石直接溢出体力，导致浪费了理智恢复时间
