### ISSUE TITLE
Windows7系统v4.23.1版本无法加载理想城IC关卡、无法检测更新、自动战斗无法请求网络服务

### ISSUE THREAD

**Issue by HertsLeon** [MaaAssistantArknights/MaaAssistantArknights#6181]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![IMG_20230901_202633](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66908081/badf7966-b0f0-4672-a84c-2f8235e12080)
![IMG_20230901_203141](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66908081/13f318fc-36fa-40e9-bf77-b17a1cfede4f)
![f1e3b717ee93f181936b8b36f0bd4fb8](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66908081/a2bc0702-c8b3-43d6-b0f0-3e9936bfc553)
大概从v20.0之前就开始无法正常自动更新，到现在v23.1都是手动从正常更新的电脑覆盖maa更新到Windows7，无法访问自动作业的神秘代码，从官网上下载新版本压缩包也一直是检测更新失败

### 日志文件
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12506115/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12506117/gui.log)

**Comment by SherkeyXD** [comment]
请上传日志文件，不是截图

**Comment by HertsLeon** [comment]
> 请上传日志文件，不是截图

已经上传

**Comment by SherkeyXD** [comment]
> System.Net.Http.HttpRequestException: 发送请求时出错。 ---> System.Net.WebException: 请求被中止: 未能创建 SSL/TLS 安全通道。

感觉是你的网络环境有问题，换个网络试试？

**Comment by HertsLeon** [comment]
> > System.Net.Http.HttpRequestException: 发送请求时出错。 ---> System.Net.WebException: 请求被中止: 未能创建 SSL/TLS 安全通道。
> 
> 感觉是你的网络环境有问题，换个网络试试？

以前必须要挂代理才能更新，v20.0之后完全脱机，一直都是从正常更新的Windows10电脑上复制完整包在覆盖更新

**Comment by Rbqwow** [comment]
因为.net8 maa已经放弃win7支持 抱歉啦
