### ISSUE TITLE
希望mac版本自动公招开放更大招募次数

### ISSUE THREAD

**Issue by FSPaul2498** [MaaAssistantArknights/MaaAssistantArknights#6182]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

mac版本MAA目前自动公招功能，“每次执行时最大招募次数”上限为4（范围0到4），不能进行大量公招

### 有什么好的想法？

希望能够开放自定义招募次数，自己填写需要的招募次数（比如500次），以便快速进行大量公招（攒了好几百公招券，真的想尽快兑成大量黄票）
还可以同时加入一个判断逻辑，当自定义招募次数大于4的时候，自动勾选“自动使用加急许可”

**Comment by noni102** [comment]
很需要这个功能，希望开发者能加入这个功能，非常感谢！
