### ISSUE TITLE
mumu模拟器12，能连接、能启动，但是不点击

### ISSUE THREAD

**Issue by andiyeki** [MaaAssistantArknights/MaaAssistantArknights#6187]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

问题表现为能连接模拟器，能启动明日方舟，但是没有后续点击动作，停在明日方舟加载完成界面，手动点击模拟器操作正常，但是MAA无法继续自动点击

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12502612/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12502613/asst.log)

### 还有别的吗？

MAA版本4.23.2，mumu模拟器12版本3.5.15，操作系统为WIN11

**Comment by MistEO** [comment]
把mumu的后台保活功能关了试试

**Comment by andiyeki** [comment]
试了试可以了，非常感谢！
