### ISSUE TITLE
v4.23.2 点开始连接后卡死

### ISSUE THREAD

**Issue by keytears** [MaaAssistantArknights/MaaAssistantArknights#6188]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

可以开启客户端，能自动启动模拟器，但是一点开始就会卡死，一开始以为是模拟器问题后来试了mumu12和新下载的雷电都会复现，问题是今早更新完4.23.2版本以后出现的。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12502688/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12502696/gui.log)
问题出现的时间大概是10.20-30分期间

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12216760/b899f99f-bd61-4d85-b233-470df849e621)

### 还有别的吗？

用的是win1122h2，最新版的mumu12和雷电模拟器

**Comment by 2455DD** [comment]
发现相同情况，使用模拟器为BlueStacks 5.12.102.1001

**Comment by KJH-x** [comment]
相同情况，启动任务，连接时卡死，重启模拟器/GUI无法解决问题，重启电脑后仅第一个GUI可连接（同Maa程序多次启动，之前的版本没有问题），asst.log、gui.log未见卡死前后相关记录
Win10 Pro 22H2，夜神模拟器7.0.5.7

**Comment by SherkeyXD** [comment]
都是 v4.23.2 出现的问题吗

**Comment by KJH-x** [comment]
> 都是 v4.23.2 出现的问题吗

我是4.23.2出现的，目前已经回滚4.23.1使用

**Comment by SherkeyXD** [comment]
回滚至 v4.23.1 应该能正常运行

**Comment by xxyz30** [comment]
4.23更新后感觉响应比原来慢了好多（

**Comment by QB233** [comment]
使用mumu12模拟器，MAA 4.23.2可以正常使用

**Comment by DreamBroke** [comment]
使用mumu12模拟器，我也出现了同样的问题，在启动MAA 4.23.2，点击开始之后，如果点击MAA GUI上的任意一处，很容易出现卡死的情况。而如果此时放置不动，不进行点击，等到mumu12模拟器开始自动进入明日方舟之后，再点击MAA GUI上的任意一处，也不会出现卡死的情况了。
感觉像是等待adb连接的操作放在了主线程里，阻塞了ui操作导致的？

**Comment by lianxiaoyan233** [comment]
相同情况，win1122h2,mumu v3.5.15, maa 4.23.2，点击开始后maa卡死（13：07点击开始，13：10看到没有反应，再点一下就变成停止工作了）

**Comment by lianxiaoyan233** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12503218/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12503219/asst.log)

**Comment by MistEO** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/bceb094e-8cc4-4c29-831c-a689ef46dbc1)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/1064b030-8c6b-4c85-88c0-b1a3a0dc9b93)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/db8d413f-b315-438e-9ff1-c591820b1862)

打开个文件都能卡住，完全不知道为什么，这里是单线程加载的，像是 syscall 死锁了。等个大佬带带

**Comment by MistEO** [comment]
描述一下问题

1. A 线程去open a 文件，同时 B 线程异步 open b文件，等 A+B 全都跑完之后，C 线程再去 open c 文件，crt 死锁
2. 只 A 线程去 open a + b 文件，等 A 跑完之后，C 线程再去 open c 文件，正常


 a, b, c 完全是独立文件，确定 A + B 线程已经跑完了，且所有文件正常 close 了。而且这个锁也不是maa加的，是 crt 的死锁_(:з」∠)_

**Comment by MistEO** [comment]
总之先规避掉了，但我还是想不通为什么，不同的文件也不能异步 open 吗？再说线程都跑完了呀

**Comment by 1ZUMIKun** [comment]
我蓝叠国际版的要回退到v4.21.0才能正常使用，v4.23.0和v4.23.2都有问题
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/68433151/0b9c0e03-f2b3-4d23-b450-d6eaec2c50b3)

**Comment by lattefish** [comment]
我两台win10电脑一个用的蓝叠5国际版，一个用的国内版，从v4.23.0开始，v4.23.1，v4.23.2，v4.23.3 都出现了卡死，无法连接模拟器等相同问题，请问回滚至4.21后如何让它不自动更新？每次刚装好一点开立马就更新成最新了
