### ISSUE TITLE
自动战斗有时候会卡在编队界面

### ISSUE THREAD

**Issue by HMZyueshen** [MaaAssistantArknights/MaaAssistantArknights#619]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8794278/asst.log)

**Comment by HMZyueshen** [comment]
不是自动编队的问题，是我在写作业调试的时候会卡死在编队界面，我自动编队是关了的

**Comment by HMZyueshen** [comment]
重启脚本后又没问题了

**Comment by MistEO** [comment]
fixed
