### ISSUE TITLE
非常感谢大佬们开发maa这么好用的工具，希望大佬们如果有空的话能加入一个森空岛自动签到功能

### ISSUE THREAD

**Issue by LosewaySama** [MaaAssistantArknights/MaaAssistantArknights#6192]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by SherkeyXD** [comment]
Duplicate of #6167

**Comment by cenfusheng** [comment]
毕竟森空岛签到是yj为了社区活跃做的，MAA打算避开这种敏感地带，所以不会自己做。
可以使用其它脚本，例如：
https://github.com/Maojuan-lang/SenKongDao
或
https://github.com/xxyz30/skyland-auto-sign
