### ISSUE TITLE
"干员识别"识别不出麒麟R夜刀

### ISSUE THREAD

**Issue by 291301** [MaaAssistantArknights/MaaAssistantArknights#6195]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用win10系统, mumu12模拟器, 麒麟R夜刀始终不识别

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12503798/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12503799/gui.log)

### 截图

![8GD1DHM4 B30TN9 NDNULX](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96360489/6e97d24c-70fc-4e72-8075-6ead64f0662d)
![88A839N1HBI(OQI1FG@O{ G](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96360489/9e8e10c1-9672-463e-8eba-b2351b56aa35)
![VVV @ _@QI(8GAO51TXD{PV](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96360489/e818b6e8-ffc1-481e-b21f-58e1705cf295)

**Comment by Lancarus** [comment]
#6202 #6178
