### ISSUE TITLE
MAA可以读取并识别模拟器打开的明日方舟窗口，但是只会在初始首页窗口执行对应操作

### ISSUE THREAD

**Issue by Mmy117** [MaaAssistantArknights/MaaAssistantArknights#6197]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用模拟器为MuMu模拟器12，版本3.5.16，MAA版本为4.23.3，MAA能连接上模拟器也能操作模拟器，在打开明日方舟的游戏窗口之后虽然能正常识别到明日方舟的游戏界面，但是操作却全发生在MuMu模拟器刚打开时的首页窗口里，就算保证模拟器一直显示在明日方舟窗口的界面上MAA也会在首页窗口里进行对应的操作。这几天我尝试运行MAA无反应之后都会莫名其妙地发现MuMu自动下了好几个游戏，之前一直没有把两件事联系到一起。今天我在手动打开了基建界面再运行MAA的基建换班后意外点到了MuMu首页的窗口才发现MAA一直在那里反复拖拽点击，点到游戏广告就开始下载了。 

我怀疑“mumu模拟器12，能连接、能启动，但是不点击 #6187”反应的问题其实和我是同一个，MAA在连接成功后因为只会在首页窗口操作，它在从首页点击并打开明日方舟之后就无法在明日方舟的窗口上继续点击了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12504295/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12504296/gui.log)

问题在8月31日前出现在我几个小版本前的MAA上，为了解决问题我重装了MAA，但是问题一直没解决，这些日志文件是我新装的MAA的。这个问题在我尝试的次数中让MAA运行任何一个任务都会发生，在截图部分我举了一个例子，它是我在上传日志文件前在MAA上进行的最后一次操作，MAA开始连接时间为09-03 00:03:13，停止时间为09-03 00:03:18

### 截图

这个问题在我尝试的次数中让MAA运行任何一个任务都会发生，下图只是举了一个较为直观的例子：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91801556/213c8094-a7c4-48e5-9b69-99e3607f83e9)
先打开明日方舟并手动进入上图显示的开始唤醒界面，然后运行MAA的开始唤醒任务，MAA会点击并未显示的首页窗口里和“开始唤醒”按钮对应位置的下图中红圈圈出的“应用分身”，使模拟器在一直显示着明日方舟窗口的状态下（上图所示的状态）直接跳到新的“应用分身”的窗口，如下下图所示
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91801556/067b5d2e-39d7-4f9b-b9c5-329715b813bf)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91801556/c5fe2921-5d82-4682-8cb5-ae9cce3603a4)
下图为我在该问题发生时停止MAA时MAA显示的画面
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91801556/6252c16d-8a89-4a64-aa53-4d4bb1222610)

**Comment by ABA2396** [comment]
这个问题mumu那边在帮着解决。你看看mumu的设置里有开后台保活吗？把那个关了试试

**Comment by Mmy117** [comment]
> 这个问题mumu那边在帮着解决。你看看mumu的设置里有开后台保活吗？把那个关了试试

关闭后我重启了模拟器和MAA，问题成功解决了

**Comment by Mmy117** [comment]
> 这个问题mumu那边在帮着解决。你看看mumu的设置里有开后台保活吗？把那个关了试试

非常感谢！
