### ISSUE TITLE
增加肉鸽职业队刷直升功能

### ISSUE THREAD

**Issue by wuyu8512** [MaaAssistantArknights/MaaAssistantArknights#6203]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

刷直升有点烦

### 有什么好的想法？

在低难度烧开水
然后切换到高难度选职业队刷直升(指定干员)+(指定开局资源)

**Comment by Lancarus** [comment]
#4791
