### ISSUE TITLE
山反复开启关闭横扫架势

### ISSUE THREAD

**Issue by Realms61** [MaaAssistantArknights/MaaAssistantArknights#6204]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

山的横扫架势为永续技能，开启之后无需关闭，但是在萨米肉鸽中会反复开启关闭此技能导致山暴毙

### 有什么好的想法？

将山的横扫架势技能修改为仅需开启一次

**Comment by Lancarus** [comment]
#6206
