### ISSUE TITLE
链接错误

### ISSUE THREAD

**Issue by myzsw** [MaaAssistantArknights/MaaAssistantArknights#6212]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

无法链接上模拟器

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12506087/asst.log)
__
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12506088/gui.log)

### 截图

<img width="944" alt="屏幕截图 2023-09-03 210648" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120544856/0c5d74cf-3493-45a7-841e-004f091119d7">

### 还有别的吗？

使用mumu模拟器，win11操作系统

**Comment by ABA2396** [comment]
看红字
