### ISSUE TITLE
麒麟X夜刀已经改名为“麒麟R夜刀”

### ISSUE THREAD

**Issue by goyewell** [MaaAssistantArknights/MaaAssistantArknights#6217]
### 说说你遇到的问题？

目前MAA无法识别基建内的麒麟R夜刀，导致无法正常基建换班。推测是因为MAA选择的是麒麟X，但名字实际上已经更换为麒麟R。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124797583/e33dbace-7dfd-4094-a511-851253415f98)

**Comment by zzyyyl** [comment]
cea3467512de60c41697b0cf07da171ed5201b2a fixed
