### ISSUE TITLE
[iOS]MAA无法启动明日方舟

### ISSUE THREAD

**Issue by EricWangxy** [MaaAssistantArknights/MaaAssistantArknights#6218]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

mac版maa在一次运行完成之后突然不能自动启动明日方舟，期间并无maa或者playcover更新。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12509194/asst.log)

### 截图

<img width="260" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43486704/b609b95a-8cfa-44ed-ade7-1cdd6cdef252">

### 还有别的吗？

m2 ventura13 
maa v4.23.3

**Comment by ABA2396** [comment]
cc @hguandl
