### ISSUE TITLE
一层商店刷铁锤

### ISSUE THREAD

**Issue by puzi12138** [MaaAssistantArknights/MaaAssistantArknights#6219]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

铁锤作为一个商店神器，如果在一层刷到可以让玩家体验一个爽局，然而自己刷实在是过于繁琐

### 有什么好的想法？

在一层商店时检测是否商店/背包里有铁锤，有的话则提示玩家，没有则继续

**Comment by wuyu8512** [comment]
感觉起码按周来算（
