### ISSUE TITLE
mumu模拟器自动作战编队选择干员不全

### ISSUE THREAD

**Issue by ability66** [MaaAssistantArknights/MaaAssistantArknights#622]
！！！请尽可能详细的描述你遇到的问题，并附上助手软件目录下的 `asst.log` 日志文件！！！

！！！日志文件是可以直接拖拽进来的，没有日志文件的 bug 反馈我们会直接关掉！！！

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
![image](https://user-images.githubusercontent.com/106503132/170913142-4ad2b5fb-6196-4350-81ec-6880f6a7cf4c.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8795259/asst.log)

**Comment by ABA2396** [comment]
现在自动编队是有问题，先用手动编队
