### ISSUE TITLE
干员识别无法识别麒麟R夜刀（已修复），以及识别干员后导出格式优化

### ISSUE THREAD

**Issue by Private233** [MaaAssistantArknights/MaaAssistantArknights#6224]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用小工具干员识别时发现无法识别麒麟R夜刀（是否跟夜刀改名有关）
另外，干员识别这块是不是可以做一个内容导出，目前也就在公招识别里面可以看到识别过的干员潜能。
可以专门导出到一个excel表格，方便需要的时候自己查阅。（或者这个东西一直就有，但是我不知道在哪，跪了）

### 日志文件

debug/oper 文件好大，压缩了也传不上来（

### 截图

![QQ截图20230905091823](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108540840/664ff32f-acd7-41ca-9957-8d1e966bd9d5)
![QQ截图20230905091854](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108540840/2ff81e8f-cce7-4585-8695-791a7d27320c)

### 还有别的吗？

mumu12
maa v4.23.3

**Comment by MistEO** [comment]
复制到剪切板就是导出。

debug/asst.log 发一下

**Comment by ABA2396** [comment]
> 复制到剪切板就是导出，有包括等级、精英化、潜能等信息
> 
> debug/asst.log 发一下

加个小工具解析下json怎么样？有些人可能只在意是否拥有或者只要看潜能什么的

**Comment by Private233** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12520002/asst.log)

**Comment by MistEO** [comment]
> > 复制到剪切板就是导出，有包括等级、精英化、潜能等信息
> > debug/asst.log 发一下
> 
> 加个小工具解析下json怎么样？有些人可能只在意是否拥有或者只要看潜能什么的

啥样的小工具，我感觉如果不是像仓库识别那样同步到别的工具上，我们不如在界面上显示了（

**Comment by MistEO** [comment]
哦内测版改过了，还没上正式版，等等吧

https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/cea3467512de60c41697b0cf07da171ed5201b2a

**Comment by Private233** [comment]
我是在想，导出的话做一个excel表，一列名称一列潜能一列等级这样的，类似这样的话自己使用查询会方便一点吧。
感觉目前这json文件看着有点不方便（

**Comment by Private233** [comment]
然后还有就是在界面上显示没有的干员是比较明晰的，复制出去之后再看就看不出什么没有了。
（把没有的干员排序到队尾/队首 这样？）

**Comment by ABA2396** [comment]
这个做起来应该不难，不过现在这个显示的内容是一整个string存的，我感觉挺奇怪的）之后看看怎么改

**Comment by wangl-cc** [comment]
如果你想导出Excel的话，现在森空岛开放之后，可以用森空岛的API来导出的练度了，一图流网站提供了导出Excel的功能，你可以试一下。当然这仅作为建议，不保证安全性。
<img width="1192" alt="截屏2023-09-05 23 04 37" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40141251/c6d01020-d08f-4fa7-bbda-27720b35e3ec">

**Comment by ABA2396** [comment]
> 如果你想导出Excel的话，现在森空岛开放之后，可以用森空岛的API来导出的练度了，一图流网站提供了导出Excel的功能，你可以试一下。当然这仅作为建议，不保证安全性。
> 
> 截图
> 不过这个导出的好像没有未拥有的干员。

这个第二行的未知干员是什么）

**Comment by wangl-cc** [comment]
> 这个第二行的未知干员是什么）

看了一下表，应该是剑兔

**Comment by sausagechen** [comment]
一图流没更新夜刀的改名，导致基建换班找不到人

**Comment by Deo-777** [comment]
之前这个干员叫麒麟X夜刀，在游戏里改名了
