### ISSUE TITLE
MAA基建换班，在笔记本关闭屏幕时容易大范围出错

### ISSUE THREAD

**Issue by sunyink** [MaaAssistantArknights/MaaAssistantArknights#6225]
### 说说你遇到的问题？

Rt，一台thinkpad的win10中，使用小工具手动让电脑屏幕黑屏而不进入锁定、睡眠状态时候，

Maa的运行基建换班会出错，最终结果很多房间空了另一些房间只放了一个错误干员，有时候还会卡界面在换干员确认框和退出基建的确认框上。

请问这种情况应该如何着手排错？

**Comment by MistEO** [comment]
不要让电脑进入省电模式，这种问题一般是游戏帧率过低导致的
