### ISSUE TITLE
在作业的详细内容添加指向PRTS.Map对应的地图

### ISSUE THREAD

**Issue by AEDELSTAN** [MaaAssistantArknights/MaaAssistantArknights#6227]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我在使用MAA Copilot 作业时，发现有自己没有的干员，同时作业没有同级干员替换，给的坐标不知道在什么位置

### 有什么好的想法？

希望可以在作业的详细内容添加指向PRTS.Map对应的地图查看干员位置

**Comment by ABA2396** [comment]
@MistEO 关卡id 从哪儿拿？作业里的 stage_name 填的可能是 关卡中文名、code、stageId、levelId，不能直接拿来用

**Comment by MistEO** [comment]
直接指向作业站对应作业就好了吧，剩下的交给作业站处理（

前端佬们已经在做 url 打开对应作业了
