### ISSUE TITLE
基建内干员“伊内丝”无法识别（已解决）

### ISSUE THREAD

**Issue by sryhm123456** [MaaAssistantArknights/MaaAssistantArknights#6229]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

运行“基建换班”功能时，更换会客室干员的步骤，MAA无法识别到干员“伊内丝”，会一直翻来覆去的找，无法进行后面的步骤，只能手动选中伊内丝。

### 日志文件

[Uploading asst.bak.log…]()
[Uploading gui.log…]()
09-05 17:02:11

### 截图

![Uploading 1.png…]()

### 还有别的吗？

MuMu模拟器
Windows 10 家庭版
64 位操作系统, 基于 x64 的处理器

**Comment by sryhm123456** [comment]
[Uploading asst.bak.log…]()
[Uploading asst.log…]()
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12521801/gui.log)

**Comment by sryhm123456** [comment]
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12534090/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12534092/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12534096/gui.log)

**Comment by sryhm123456** [comment]
09-05 17:02:11 MuMu12模拟器出现这个问题
![mumu12](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144112930/78eed698-b054-42a5-b768-254005020102)

09-06 14:19:30 更换雷电9模拟器之后还是会出现这个问题
![雷电9](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144112930/a7cc75dd-0aa8-4d48-8666-777bf30f16a2)
![Screenshot_20230906-035628](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144112930/c7e8a53c-43f1-433f-8c77-de7994a5d24a)

**Comment by sryhm123456** [comment]
![MAA](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144112930/38099107-c0ba-440e-8ffd-1edac678430a)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/2d8b7f0e-d634-46d9-a7bf-08fb5b43f538)
你这配置文件写错了吧，看看自定义基建文件里是不是把“伊内丝”多加了个空格

**Comment by sryhm123456** [comment]
是的！不好意思比较粗心给您添麻烦了！
