### ISSUE TITLE
python调用maa自动战斗使用中文文件名出现问题

### ISSUE THREAD

**Issue by soundofautumn** [MaaAssistantArknights/MaaAssistantArknights#623]
python 控制台输出
Message.ConnectionInfo {'uuid': '', 'details': {'adb': 'D:\\Program Files\\MeoAssistantArknights\\platform-tools\\adb.exe', 'address': '127.0.0.1:9434', 'config': 'General', 'uuid': 'c72cf0bde58e707a'}, 'what': 'UuidGetted', 'why': ''} None
Message.ConnectionInfo连接成功
 {'uuid': '', 'details': {'adb': 'D:\\Program Files\\MeoAssistantArknights\\platform-tools\\adb.exe', 'address': '127.0.0.1:9434', 'config': 'General', 'width': 1600, 'height': 900}, 'what': 'ResolutionGetted', 'why': ''} None
Message.ConnectionInfo {'uuid': '', 'details': {'adb': 'D:\\Program Files\\MeoAssistantArknights\\platform-tools\\adb.exe', 'address': '127.0.0.1:9434', 'config': 'General'}, 'what': 'Connected', 'why': ''} None
Traceback (most recent call last):
  File "C:\Users\Qjming\source\repos\MaaAssistantArknights\tools\CopilotDesinger\SV-9.py", line 24, in <module>
    sv_9.test()
  File "C:\Users\Qjming\source\repos\MaaAssistantArknights\tools\CopilotDesinger\CopilotDesinger.py", line 455, in test
    asst.append_task('Copilot', {
  File "C:\Users\Qjming\source\repos\MaaAssistantArknights\src\Python\asst.py", line 87, in append_task
    return Asst.__lib.AsstAppendTask(self.__ptr, type_name.encode('utf-8'), json.dumps(params, ensure_ascii=False).encode('utf-8'))
OSError: [WinError -529697949] Windows Error 0xe06d7363

怀疑是中文文件名问题
![image](https://user-images.githubusercontent.com/62000745/170932819-4f1a79e7-b9d5-49f0-a53c-5a383ad73226.png)
完整日志文件
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8796107/asst.log)

**Comment by MistEO** [comment]
现在用中文名确实有问题，没空整。 现在 UI 侧的策略是把文件拷贝一份再传入

**Comment by MistEO** [comment]
不知道啥时候修了 @zzyyyl

**Comment by MistEO** [comment]
v4.4.0-beta.2 fixed
