### ISSUE TITLE
关于MAA界面输出信息中不显示日期（太占空间）

### ISSUE THREAD

**Issue by 1021263881** [MaaAssistantArknights/MaaAssistantArknights#6231]
### 说说你遇到的问题？

![265694000-4700eb51-a732-45e0-897c-a2504a29a06f](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35693827/ed411abd-4127-4022-aaf7-86840db440f6)

对于非常开MAA的用户来说，一天一关MAA日期显示没用。
对于常开MAA的用户来说，扔后台一挂，平时应该也不会闲着去翻？

感觉输出日期有点占空间了

**Comment by MistEO** [comment]
@ABA2396 去掉日期怎么样？

**Comment by ABA2396** [comment]
还是加个选项吧，我之后看看

**Comment by status102** [comment]
或许可以将最后一条消息更新的时间显示到标题栏？

**Comment by ABA2396** [comment]
83f0a1f64c0464ca9f98f9429d6bbe362216a981 fixed
