### ISSUE TITLE
MAA无法“正常”启动MUMU

### ISSUE THREAD

**Issue by asxzq** [MaaAssistantArknights/MaaAssistantArknights#6234]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA版本4.23.3
（1）在不勾选“启动MAA 后自动开启模拟器”选项时，点击linkstart不能自动开启MUMU12模拟器，而之前的版本是可以做到的。 
（2）在勾选“启动MAA 后自动开启模拟器”选项时，开启MAA后可以直接自动启动MUMU 模拟器。
问题：
（2）可以证明我填的adb地址和MUMU12地址均正确的前提下，（1）反映出4.23.3版本MAA存在开启模拟器的bug，有没有可能是linkstart按键后，绕过了模拟器开启的动作。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12526121/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12526123/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/67899948/56e6aaf2-293d-4971-ba7a-361cdbeb8793)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/67899948/ecb4f4fa-a3a7-4ae3-8a8d-9be783a2f6ee)

### 还有别的吗？

MAA4.23.3+WIN11+MUMU12

**Comment by ABA2396** [comment]
你勾了连接设置里的那个连接失败重启模拟器吗？那个才是管link start启动模拟器的

**Comment by asxzq** [comment]
哦哦哦，感谢，我的锅

> 你勾了连接设置里的那个连接失败重启模拟器吗？那个才是管link start启动模拟器的
