### ISSUE TITLE
在开始唤醒界面不会自动进行下一步操作

### ISSUE THREAD

**Issue by Expiationx** [MaaAssistantArknights/MaaAssistantArknights#6238]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开MAA后可以自我启动模拟器 打开《明日方舟》后运行到“开始唤醒”界面后 不会在自动进行下一步操作

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12534174/debug.zip)

### 截图

![f4a67c33144c7285870b80306aee712e](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144208329/c028eba5-7650-4546-b134-cad95a1260a9)
![441248aa9e02170b777a5789f4d5d7e0](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144208329/6f0890b8-c88b-4aba-aea9-5d135ad5d7b0)

### 还有别的吗？

模拟器：mumu模拟器 操作系统：win11 相关配置：AMD Ryzen 7 5800H with Radeon Graphics

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/811b20eb-6322-4827-b441-ed295a083b58)

**Comment by Expiationx** [comment]
我关闭了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月06日 15:28 |
| 收件人 | MaaAssistantArknights/MaaAssistantArknights ***@***.***> |
| 抄送人 | Expiationx ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [MaaAssistantArknights/MaaAssistantArknights] 在开始唤醒界面不会自动进行下一步操作 (Issue #6238) |

**Comment by Expiationx** [comment]
无效

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月06日 15:28 |
| 收件人 | MaaAssistantArknights/MaaAssistantArknights ***@***.***> |
| 抄送人 | Expiationx ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [MaaAssistantArknights/MaaAssistantArknights] 在开始唤醒界面不会自动进行下一步操作 (Issue #6238) |

**Comment by ABA2396** [comment]
看日志是有识别到内容并点击操作的，关了这个之后有试过重启吗

**Comment by Expiationx** [comment]
重启了的

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月06日 15:40 |
| 收件人 | MaaAssistantArknights/MaaAssistantArknights ***@***.***> |
| 抄送人 | Expiationx ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [MaaAssistantArknights/MaaAssistantArknights] 在开始唤醒界面不会自动进行下一步操作 (Issue #6238) |

看日志是有识别到内容并点击操作的，关了这个之后有试过重启吗

**Comment by zimuyanghua** [comment]
+1，最近同样出现这个问题，更新后出现的，之前还可以，现在不仅登录界面点不进去，每日奖励也识别不了没反应，其他任务也不进行，只有把maa关闭重新打开才开始工作
