### ISSUE TITLE
maa运行异常，无法打开界面

### ISSUE THREAD

**Issue by zimuyanghua** [MaaAssistantArknights/MaaAssistantArknights#6239]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

经常会遇到maa最小化后再点击任务栏图标无法显示界面，点右下角图标栏也是如此，只能右键强制显示maa。

### 日志文件

[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12535218/log.zip)

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46125819/1e4875f8-f894-4e86-9c38-3c7d54b58846

### 还有别的吗？

> 模拟器：mumu12
>操作系统：win11
>maa版本：V4.23.4-alpha.1.d115.gcac2b6105

**Comment by SherkeyXD** [comment]
这感觉看着像 Windows 的 bug（

**Comment by zimuyanghua** [comment]
> 这感觉看着像 Windows 的 bug（

其他软件都没遇到过，因为别的软件点击右下角图标只能显示界面，不能隐藏界面，这个maa点一下隐藏界面点一下显示界面，多点几次就崩了

**Comment by zzyyyl** [comment]
确实，我复现了

**Comment by zimuyanghua** [comment]
> 确实，我复现了
> 
> 大概是在点击右下角的小图标，Windows 显示窗口的动画没放完的时候再次点击，让它最小化；接下来就卡成上面录屏的那样了
> 
> [b80f827](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/b80f8275de86d33adc273c1fdc5739bc5c81500e)

maa界面显示的时候，双击一下右下角图标就百分百复现了

**Comment by ABA2396** [comment]
奇怪的问题增加了，要不干脆把点一下最小化给去掉）
