### ISSUE TITLE
在肉鸽中maa选择大哥的技能不是三技能而是一技能（以及其他的问题）

### ISSUE THREAD

**Issue by Kaphtz** [MaaAssistantArknights/MaaAssistantArknights#6244]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题，这让我有点困扰。我认为在maa中可以高效的开启大哥的技能，结果在大哥精二之后发现maa根本就不会选三技能造成了不必要的联系中断。另外maa抓叔叔这个问题也困扰了我很久，每次抓近卫的时候我都得看着避免抓到叔叔防止下一关暴毙。还有maa购买战术装备之后会把它看做正常干员来放置。

### 有什么好的想法？

把叔叔的阻挡数看做是零，然后将战术装备独立出来

### 其他内容

额希望maa越做越好
牛牛爱你
![QQ图片20230906223316](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/132883669/421cc2a6-b53a-484c-94c4-37bc4d14fd8b)

**Comment by Lancarus** [comment]
之前重岳没写默认技能，已经在 #6213 中适配。
抓叔叔是因为目前的肉鸽打法主要是围绕苇草和叔叔来的，优先级很高，只要有地面阻挡就尽可能抓叔叔
