### ISSUE TITLE
自动战斗点击开始运行会直接报错，无法开始运行（git pull后出现的问题）

### ISSUE THREAD

**Issue by CloudButterly** [MaaAssistantArknights/MaaAssistantArknights#625]
日志如下
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8796847/asst.log)
一些截图
![图片](https://user-images.githubusercontent.com/106486744/170951826-2c283b58-b48c-4bec-918e-00b401e8e3f6.png)
![图片](https://user-images.githubusercontent.com/106486744/170951897-ee2f2c40-dd96-45a3-beab-d3b6060ccc9c.png)

**Comment by MistEO** [comment]
JSON 作业文件也发一下吧
