### ISSUE TITLE
MAA无法启动或启动后link start无法亮起

### ISSUE THREAD

**Issue by HL-Light** [MaaAssistantArknights/MaaAssistantArknights#6250]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启动后进程直接死掉，无界面弹出，或弹出后link start长时间灰色，测试为五分钟时间，仍为灰色

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12540932/asst.log)
yu
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12540933/gui.log)
2023.9.7凌晨后记录

### 还有别的吗？

win10家庭版
gtx1650
i3 9300H
夜神模拟器 内核为安卓7

**Comment by HL-Light** [comment]
有考虑过是否为下错架构，但有时候又可以启动，如重启电脑多次尝试后或者重装可以正常使用，应该不是手滑下错了

**Comment by gdf159159** [comment]
解决办法是需要反复的关闭打开maa   不需要重启电脑

我怀疑是maa启动请求数据的网站  加载太慢了

**Comment by HL-Light** [comment]
好像确实是这样，每次在更新请求完后确实没有再出现，但是请求数据慢会杀掉进程吗，很多次maa的进程一出就没了

**Comment by qiannm** [comment]
这个问题好像是在大水坑复刻后才有的，之前夏活的时候没有遇到过。

**Comment by ABA2396** [comment]
卡在资源加载了。问题就是这部分的逻辑根本就没改过，不知道为啥就卡住了

**Comment by HL-Light** [comment]
应该不是我网络的问题，目前这个情况非常严重，每次启动都能复现

**Comment by HL-Light** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/116658416/10431a97-b230-42ba-a202-47b10e3669ff)
在今日早晨九点覆盖更新v4.24.0-beta.1版本后，发现maa页面无法操作，点击无反应，但无未响应摆错，在任务管理器中发现仍在运行，但无法杀掉进程

**Comment by lxflxf56** [comment]
我的也一样，这个有解决办法了吗
