### ISSUE TITLE
mumu12最新版模拟器使用最新公测版MAA运行肉鸽模式烧开水会卡在热水壶界面

### ISSUE THREAD

**Issue by CirillaFionaElenRiannon** [MaaAssistantArknights/MaaAssistantArknights#6251]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，烧开水模式在探索一次开始第二次之后卡在热水壶选项界面

### 日志文件

[filelist.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12543251/filelist.txt)

**Comment by AnnoyingFlowers** [comment]
有没有一种可能，烧水模式就只是用来烧开水的
