### ISSUE TITLE
有考虑做一个森空岛每日签到功能吗

### ISSUE THREAD

**Issue by kkujukk** [MaaAssistantArknights/MaaAssistantArknights#6254]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题 不一定加在maa上 做成类似油猴插件也行

**Comment by sunyink** [comment]
已经有类似项目了 py语言的。但我今天去看发现项目已经被禁用了。

**Comment by IA20201** [comment]
> 已经有类似项目了 py语言的。但我今天去看发现项目已经被禁用了。

https://gitee.com/FancyCabbage/skyland-auto-sign

**Comment by SherkeyXD** [comment]
Duplicate of #6192
