### ISSUE TITLE
20230907-4.23.3版本maa较高概率无法启动

### ISSUE THREAD

**Issue by agfhi** [MaaAssistantArknights/MaaAssistantArknights#6255]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa版本4.23.3
这几天应该算是高频复现了，表现为打开maa.exe无法启动程序，任务管理器查看进程反复挂起后崩溃

出现时间9.7 10:57，日志往前翻四五次基本都是这样的

就见过一次link start常灰，很难复现无法录屏

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12544199/debug.zip)

压缩包中有简单录屏一段
最后一次即录屏时间是2023.9.7 10:57，9.7的尝试均是如此

### 还有别的吗？

操作系统版本 Windows 10 专业版 22H2
处理器 AMD Ryzen 5 2600 Six-Core Processor
maa版本 MAA-v4.23.3-win-x64
模拟器 mumu12 V3.5.16(2056)

**Comment by HL-Light** [comment]
我和你一样的问题，多次反复重启能启起来，不知道什么bug

**Comment by clark1091** [comment]
同上，并且基本上同时伴随出现mumu12卡死/严重帧率不稳等问题

**Comment by SherkeyXD** [comment]
Duplicate of #6239

**Comment by SherkeyXD** [comment]
草 标错了
疑似同 #6250

**Comment by zzyyyl** [comment]
`v4.24.0-beta.2` fixed
