### ISSUE TITLE
刷理智，吃完原石以后直接结束任务

### ISSUE THREAD

**Issue by mdzzii** [MaaAssistantArknights/MaaAssistantArknights#6256]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题，刷理智选择吃原石，如6个，吃完第6个原石以后显示任务完成，而不会刷完第6个原石的理智。

### 有什么好的想法？

刷完理智以后再结束任务，而不是吃完石头直接结束

**Comment by zzyyyl** [comment]
发 log 文件，开 bug issue

**Comment by zzyyyl** [comment]
相关 issue #6162 

`v4.23.4-alpha.1.d130.ga87095e8d` fixed

**Comment by mdzzii** [comment]
目前使用4.23.3，抱歉没有看完issue

**Comment by zzyyyl** [comment]
新版我猜也没人测，有问题的话再来提就行^_^
