### ISSUE TITLE
出现未知错误-索引超出了数组界限, OpenClipboard失败

### ISSUE THREAD

**Issue by whyXVI** [MaaAssistantArknights/MaaAssistantArknights#6259]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA打开后报错无法运行

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12544506/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12544507/gui.log)
今天出现的问题, 昨天使用wired XDisplay连接过matepad, 也使用过华为手机助手连接过. 在此之后的0.00自动运行第一次出现了该问题

### 截图

<img width="450" alt="c5511486383eadc60c7e067cc5a6e747" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139840508/3ad67a9f-084e-4809-9920-a6775eb29f4d">

### 还有别的吗？

win11 MAA最新版本 mumu模拟器12最新版本V3.5.16(2056)

**Comment by MistEO** [comment]
公测版修了，试试
