### ISSUE TITLE
基建工作心情阈值设置失效

### ISSUE THREAD

**Issue by 610807421** [MaaAssistantArknights/MaaAssistantArknights#6260]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

未启用“自定义基建配置”功能
未勾选“不将已进驻的干员放入宿舍”

当基建工作心情阈值设置为30%时，MAA在运行基建换班功能时，将制造站内心情高于30%的干员进行换班，导致部分基于工作时长可以获得额外加成的干员技能无法获得最高生产力

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12545544/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12545546/gui.log)

**Comment by ABA2396** [comment]
高于阈值但效率低于其他干员也是会被换下来的
