### ISSUE TITLE
借助战刷OF-1获取信用任务未执行

### ISSUE THREAD

**Issue by IberianCabbage** [MaaAssistantArknights/MaaAssistantArknights#6261]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

这次版本更新以后，“获取信用及购物”选项中的“借助战打OF-1赚信用”突然无法执行了，勾选了以后似乎是自动跳过了这一步，既没有报错也没有进行对应操作，连续好几天一直是这种情况
报错时间点：14点之后

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12545707/asst.log)

### 截图

![QQ截图20230907150111](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96757630/09536a86-a62e-4dd2-a6e1-79e89be5bd3e)

### 还有别的吗？

使用模拟器为蓝叠5国际版，系统为win10
以及虽然反馈的时候勾选了“已查看最新测试版本的更新内容”，但实际上我找了好久也没找到哪里有公布测试版本的信息，只在MAA本体里找到了稳定版的更新日志，不确定是不是在上次稳定版更新以后还没有更新过测试版，如果有人知道哪里能看的话麻烦指点我一下，感谢

**Comment by zzyyyl** [comment]
看日志显示，早上八点已经打过 OF-1 了，我记得一直勾选时每天只会打一次：）

**Comment by zzyyyl** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6071#issuecomment-1692652940

**Comment by IberianCabbage** [comment]
> [#6071 (comment)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6071#issuecomment-1692652940)
> 
> ![image](https://user-images.githubusercontent.com/74587068/266261206-814566aa-9405-4343-a618-b56fc73d1062.png)

原来是这个原因，感谢解答。但是我这边用户端里勾选框旁边没有这个提示，运行的时候也没有相关报错，希望能加一下吧，不然都不知道发生了什么_(:з」∠)_最近活动重叠，复刻活动没有导航只能选“当前/上次”，我还特意留心想着刷完这个任务以后手动切一下关卡，没想到是直接任务无效了

**Comment by zzyyyl** [comment]
提示在鼠标悬停时会出现

**Comment by zzyyyl** [comment]
@ABA2396 也许可以在 “当前/上次” 的时候把这个变灰（？

**Comment by ABA2396** [comment]
> @ABA2396 也许可以在 “当前/上次” 的时候把这个变灰（？

那你不如把文本变红）不然又有人问为什么不能改了

**Comment by status102** [comment]
> > @ABA2396 也许可以在 “当前/上次” 的时候把这个变灰（？
> 
> 那你不如把文本变红）不然又有人问为什么不能改了

点开始的时候加个检测，有冲突就不给开始（划去

**Comment by ABA2396** [comment]
> 点开始的时候加个检测，有冲突就不给开始（划去

现在就是这样的啊

**Comment by status102** [comment]
> 现在就是这样的啊

是有哪里要调么，刚试了下 4.23.4-a.1好像没触发
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/c96ba310-5fc3-4966-a888-22f78af7654c)

**Comment by ABA2396** [comment]
你把获取信用放在刷理智前面呗

**Comment by status102** [comment]
> 你把获取信用放在刷理智前面呗

想起来了，有个检测无掉落的打断

**Comment by ABA2396** [comment]
> > 你把获取信用放在刷理智前面呗
> 
> 想起来了，有个检测无掉落的打断

不是，无掉落打断是刷理智遇到OF-1时候停止，这个是在选了当前/上次的时候取消刷信用任务，虽然都是为了避免这种情况的发生
