### ISSUE TITLE
荣耀magicbooc14 AMD R7 3700U MUMU模拟器12 显卡崩溃问题

### ISSUE THREAD

**Issue by 321QQQ** [MaaAssistantArknights/MaaAssistantArknights#6264]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

荣耀magicbooc14 AMD R7 3700U MUMU模拟器12 显卡崩溃问题

### 有什么好的想法？

在显卡崩溃的时候自动尝试重启模拟器

### 其他内容

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144362601/d6550bba-d5be-4b1f-b14d-ab18f89a5bb1)

**Comment by SherkeyXD** [comment]
单独启动 mumu12 而不启动 maa 会有这个问题吗？
