### ISSUE TITLE
外服需要上线生息演算功能谢谢

### ISSUE THREAD

**Issue by delishalita** [MaaAssistantArknights/MaaAssistantArknights#6265]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

日服和国际服上线了生息演算但暂时无法使用maa来刷该副本

### 有什么好的想法？

针对外服的可以在主界面设置不同选择，避免国内玩家一头雾水

**Comment by Argonautes0607** [comment]
确实开荒好坐牢，希望只要内置一个慢慢挂着刷满结算点数的作业就行了

**Comment by Constrat** [comment]
We are working on it.

**Comment by foxwhite25** [comment]
现在只是c井前端隐藏了，Core的功能还是在的，现在应该就需要截图匹配一下就可以用了

**Comment by delishalita** [comment]
感谢，找到对应图了，等有时间再一点点对应添加修改



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月8日(星期五) 晚上7:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 外服需要上线生息演算功能谢谢 (Issue #6265)




 
现在只是c井前端隐藏了，Core的功能还是在的，现在应该就需要截图匹配一下就可以用了

**Comment by Constrat** [comment]
Don't worry, I've already done most of it

**Comment by Constrat** [comment]
If you want to try it you can clone the repository, open the .sln with Visual Studio and build the Reclamation algorithm branch

**Comment by XuTingyi** [comment]
请问适配生息演算的版本出来了吗？4.24.0-beta4没有找到生息演算的入口但beta3更新日志有提到？

**Comment by Constrat** [comment]
Ok so what happened is: 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/631473dd-f768-4855-b145-cc2bc97ab0af)
Because that event ended. It's now in the location.
If you give me some time I can prepare the new UI detection. Shouldn't take that long.

**Comment by XuTingyi** [comment]
> Ok so what happened is: ![image](https://user-images.githubusercontent.com/56174894/269595742-631473dd-f768-4855-b145-cc2bc97ab0af.png) Because that event ended. It's now in the location. If you give me some time I can prepare the new UI detection. Shouldn't take that long.

Appreciate it~

**Comment by Constrat** [comment]
> Appreciate it~

For the time being you can Link Start in the Reclamation Scree.

**Comment by delishalita** [comment]
感谢你的好意，现在maa已经有生息演算的功能，十分感谢您的好心肠

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月21日(星期四) 晚上7:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 外服需要上线生息演算功能谢谢 (Issue #6265)




  
Ok so what happened is:  Because that event ended. It's now in the location. If you give me some time I can prepare the new UI detection. Shouldn't take that long.
  
Appreciate it~

**Comment by delishalita** [comment]
我看已经有人帮忙把那个已经解决掉了，应该是6267，我的问题应该是已经解决掉的，我上次看。十分感谢您的好意。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月21日(星期四) 晚上7:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 外服需要上线生息演算功能谢谢 (Issue #6265)




 
Ok so what happened is:
 
 Because that event ended. It's now in the location.
 If you give me some time I can prepare the new UI detection. Shouldn't take that long.

**Comment by Constrat** [comment]
I've been tinkering on this for a bit: in 5 hours, the Guiding Ahead rerun will drop so I have no idea how the menu will change. I think the banner will go back as it was before so it will fix itself. If it doesn't I will change it manually at a later date.

For now, please just go manually in the Reclamation screen and start MAA from there.

**Comment by Constrat** [comment]
> 我看已经有人帮忙把那个已经解决掉了，应该是6267，我的问题应该是已经解决掉的，我上次看。十分感谢您的好意。

Yes, that was me. #6267 is the Pull Request for the needed changes changes.

**Comment by XuTingyi** [comment]
> I've been tinkering on this for a bit: in 5 hours, the Guiding Ahead rerun will drop so I have no idea how the menu will change. I think the banner will go back as it was before so it will fix itself. If it doesn't I will change it manually at a later date.
> 
> For now, please just go manually in the Reclamation screen and start MAA from there.

I'm using macOS MAA and couldn't find the entrance for Reclamation, what should I do?

**Comment by ABA2396** [comment]
cc @hguandl
