### ISSUE TITLE
活动界面返回按钮识别失败

### ISSUE THREAD

**Issue by ABA2396** [MaaAssistantArknights/MaaAssistantArknights#627]
活动界面的返回按钮因为活动背景图遮盖变黑了，模板匹配不上
![4Q)~2%)C}ZL}@G2RBD8%) P](https://user-images.githubusercontent.com/99072975/170972564-73b8c381-c245-4086-9d99-ea380ecd79a6.jpg)
![ITM5YWKGB}S`W KC7`8E}%9](https://user-images.githubusercontent.com/99072975/170972572-b4766381-1d57-46d5-92fd-d0676560df94.jpg)

**Comment by helloIris415** [comment]
说起来夜神不知道支不支持esc转换成返回的输入。mumu模拟器是可以按esc自动返回上一页的。能不能吧返回上一页的操作变成输入esc啊
