### ISSUE TITLE
MAA软件无法启动

### ISSUE THREAD

**Issue by butterjust** [MaaAssistantArknights/MaaAssistantArknights#6279]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

win11系统，vb、net4.8均已安装，正常打开与管理员运行均无法打开软件（无UI界面）

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12564472/gui.log)
拉到最下既为问题所在点

**Comment by niyikaowo** [comment]
我也有类似情况，你尝试改变一下网络环境（开关梯子，更换节点，更换DNS）再启动试试

**Comment by ABA2396** [comment]
似乎是windows的更新补丁带来的问题，最近有更新过系统或者下过补丁吗

**Comment by butterjust** [comment]
> Member

有的，9月1号的时候更新过，期间没使用过MAA今天才发现问题，补丁代号是KB4023057

**Comment by butterjust** [comment]
> 我也有类似情况，你尝试改变一下网络环境（开关梯子，更换节点，更换DNS）再启动试试



> 似乎是windows的更新补丁带来的问题，最近有更新过系统或者下过补丁吗

有的，9月1号的时候更新过，期间没使用过MAA今天才发现问题，补丁代号是KB4023057

**Comment by a1640727878** [comment]
我也遇过这种情况,但是用火绒的垃圾清理清理一下后重启电脑,又可以打开了,就很迷...

**Comment by ABA2396** [comment]
> 有的，9月1号的时候更新过，期间没使用过MAA今天才发现问题，补丁代号是KB4023057

这也是我们准备上.net8的原因之一了。现在能提供的方法也就只有卸载那次的补丁，不过这毕竟会带来安全隐患，还是自己取舍吧。

**Comment by butterjust** [comment]
> > 有的，9月1号的时候更新过，期间没使用过MAA今天才发现问题，补丁代号是KB4023057
> 
> 这也是我们准备上.net8的原因之一了。现在能提供的方法也就只有卸载那次的补丁，不过这毕竟会带来安全隐患，还是自己取舍吧。

好的，感谢解答
