### ISSUE TITLE
作业制作器导出的jons被maa选择作业后无法显示

### ISSUE THREAD

**Issue by u81668899** [MaaAssistantArknights/MaaAssistantArknights#628]
{
    "stage_name": "炽热溶洞",
    "title": "5.30日替，tag：2-3；3-1；3-2",
    "details": "能天使3903，山3903，群奶调香师白面夜莺随意",

此处写的title与details都有内容但不被显示，不输入内容则会卡死在进入关卡后的识别干员前

后续增加
    "doc": {
        "title": "5.30日替，tag：2-3；3-1；3-2",
        "details": "能天使3903，山3903，群奶调香师白面夜莺随意"
在被选择作业后会正常显示该部分的title与details（但这样一份作业里会有2个title与details）

**Comment by MistEO** [comment]
@LYZhelloworld 大佬这个字段写错了_(:з」∠)_

**Comment by LYZhelloworld** [comment]
@MistEO `title`和`details`放在`doc`里是吧。

我之前可能看了旧版本的文档。

**Comment by MistEO** [comment]
> @MistEO `title`和`details`放在`doc`里是吧。
> 
> 我之前可能看了旧版本的文档。

是的，参考最新的文档
