### ISSUE TITLE
MAA4.23.3/夜神7.0.5.8001/萨米肉鸽闪退/截图失败，如反复出现请尝试重启或更换模拟器！

### ISSUE THREAD

**Issue by JokerDoflamingo** [MaaAssistantArknights/MaaAssistantArknights#6284]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，最后一次出现2023-09-09 18:26。
代理刷理智的常规任务关卡时，从来没问题。只有在自动萨米肉鸽时，会不定时地闪退到模拟器桌面，导致截图失败。
以前的版本代理傀影、水月肉鸽从未出现此状况，此bug在4.23.0就稳定复现，望修复。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12565672/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12565676/gui.log)
[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12565679/asst.bak.zip)

**Comment by ABA2396** [comment]
游戏闪退就找找模拟器客服吧

**Comment by JokerDoflamingo** [comment]
> 游戏闪退就找找模拟器客服吧

1.请问是项目组测试过夜神7.0.5.8001发现该版本有问题吗，是的话我就换个模拟器。我记得官网文档说完美支持夜神来着，从一开始就没换过。

2.代理非肉鸽关卡啥错都没有，萨米肉鸽就闪退报错，这点比较奇怪。

**Comment by ABA2396** [comment]
自动战斗和肉鸽的截图会更加频繁，对性能的要求就会更高。也需要检查下模拟器是否有内存泄漏的情况

**Comment by JokerDoflamingo** [comment]
> 自动战斗和肉鸽的截图会更加频繁，对性能的要求就会更高。也需要检查下模拟器是否有内存泄漏的情况

换了MUMU12 v3.5.17，MAA仍然用4.23.3，萨米肉鸽代理正常。
看来的确是夜神7.0.5.8001版本的问题，之前的夜神从未出现此问题。
至于你说的内存泄漏，我不是程序员，不会查 :(
