### ISSUE TITLE
领取日常奖励出现问题

### ISSUE THREAD

**Issue by fzj-official** [MaaAssistantArknights/MaaAssistantArknights#6286]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在选择了领取日常奖励的选项的前提下仍然没有领取任务奖励

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12565893/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12565894/gui.log)
最新一次就是时间，9月9日

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144503397/d3a5f038-148a-4b36-bc7a-6f0709009413)

**Comment by starrin** [comment]
+1，这个问题我这最近几乎每天都会出现

**Comment by status102** [comment]
问问用自动战斗的时候会不会感觉模拟器有明显的卡顿、掉帧等类似现象，看log是匹配到了，但是匹配程度没超过阈值。在想会不会比较卡顿截到一半黑屏

```
[2023-09-09 21:27:01.870][INF][Px6cd4][Tx1620] Call ` D:\mumu12\MuMuPlayer-12.0\shell\.\adb.exe -s 127.0.0.1:16384 exec-out "screencap | gzip -1" ` ret 0 , cost 973 ms , stdout size: 3970486 , socket size: 0
[2023-09-09 21:27:01.929][TRC][Px6cd4][Tx1620] asst::PipelineAnalyzer::analyze Award
[2023-09-09 21:27:01.932][TRC][Px6cd4][Tx1620] match_templ | Task.png score: 0.760736 rect: [ 711, 556, 90, 85 ] roi: [ 700, 530, 130, 130 ]
```

**Comment by mm317670** [comment]
![B4_@2CY3A_U KO6QCQ`ZI45](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142766247/81fc7923-82a4-4f5d-8c37-705af601c91f)
[asst.log（片段.txt](https://github.com/MaaAssistantArknig
![S3T~NR_52TXY1%1~G67L}3E](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142766247/88c7d1d0-6485-4899-9ba7-a1abc69108ed)
hts/MaaAssistantArknights/files/12572391/asst.log.txt)
没有明显卡顿，掉帧等现象，也出现了该问题

**Comment by mm317670** [comment]
[asst.log（片段.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12572405/asst.log.txt)

**Comment by mm317670** [comment]
![B4_@2CY3A_U KO6QCQ`ZI45](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142766247/f627f4c2-1511-4d98-b6a1-56c500e7217c)
![S3T~NR_52TXY1%1~G67L}3E](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142766247/60c82d58-78bc-4661-9a09-aa33288ba18b)
[asst.log（片段.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12572409/asst.log.txt)
没有卡顿，掉帧等现象也出现了该情况，并且不止一次（前面的版本也有出现过，好多次了

**Comment by anywugn** [comment]
这个状况我持续了好久了，直到最近才发现，血亏一个亿（

**Comment by MistEO** [comment]
YJ 最近是不是改了这个 “任务” 的字体，感觉不一样了

**Comment by mm317670** [comment]
从5月（今年）就开始出现有这问题了，就是没在意那时候，是YJ改了的问题吗？（不知道YJ啥时候改的..

**Comment by status102** [comment]
刚刚翻了翻B站，以前这个UI都是不透明的。不过之前拿自己的号测了下，匹配得分也不低

![Screenshot_2023-09-15-20-04-40-477_com.bilibili.app.in.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/010f8540-edff-446c-9391-9731b0adeaf9)

![Screenshot_2023-09-15-20-04-55-930_com.bilibili.app.in.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/60540fed-9a60-4592-ad48-35c108e197b8)

**Comment by ABA2396** [comment]
我这一直能跑，感觉像是模拟器或者分辨率的问题。

**Comment by mm317670** [comment]
MUMU12和雷电9都有这情况，分辨率的话都是1920*1080

**Comment by zzyyyl** [comment]
> 从5月（今年）就开始出现有这问题了，就是没在意那时候，是YJ改了的问题吗？（不知道YJ啥时候改的..

**Comment by MistEO** [comment]
> > 从5月（今年）就开始出现有这问题了，就是没在意那时候，是YJ改了的问题吗？（不知道YJ啥时候改的..
> 
> [589fb9d](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/589fb9d1b3334fecde71f620004332271d53924e)
> 
> 时间点对上了（~是万恶的玛丽！~

啥玩意，你看他 log，就是得分低了没匹配上啊 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/403f57fb2d274bde5a30bdfd935099e246575199
