### ISSUE TITLE
当存在复数MAA时，开机自启功能疑似冲突失效

### ISSUE THREAD

**Issue by KokuraSona** [MaaAssistantArknights/MaaAssistantArknights#6291]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

多开用户，设置了两个maa开机自启，但实际只能生效一个，经测试，生效的那个均为在时间上后勾选开机自启项的maa，疑似冲突导致失效。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12567040/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12567041/gui.log)
09-10 10点26分左右

### 还有别的吗？

maa版本：v4.2.0-beta.1
系统：Windows 11

**Comment by ntgmc** [comment]
因为这个设置的开机自启是通过注册表实现的 所以只能设置一个 我建议你用启动文件夹设置
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/90fd3af0-24a3-4741-9230-54ee015ce3fc)
我这的目录是`C:\Users\Administrator.Arknights-WZXKT\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`

**Comment by KokuraSona** [comment]
> 因为这个设置的开机自启是通过注册表实现的 所以只能设置一个 我建议你用启动文件夹设置
> ![image](https://user-images.githubusercontent.com/74061867/266813876-90fd3af0-24a3-4741-9230-54ee015ce3fc.png)
> 我这的目录是`C:\Users\Administrator.Arknights-WZXKT\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`

目前用的就是这种方法，提issue主要是希望不能解决的话可以在文档里提一嘴
