### ISSUE TITLE
升级4.23之后启动时频繁出现错误

### ISSUE THREAD

**Issue by Tatooinish** [MaaAssistantArknights/MaaAssistantArknights#6296]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新4.23之后频繁出现启动错误的情况，已经按照文档把所有方式都试过了

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12567560/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12567563/asst.log)
9.10 04:31

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/132362968/0f054d0a-206c-446a-be52-dee4f0930caf)

### 还有别的吗？

mumu12 win10专业版 i7-8700 GTX1660

**Comment by ShiinaStar** [comment]
确实有这个问题，我在Win11开始菜单里启动，往往第一次点击无响应，点击第二次才弹出启动
平台蓝叠中国；Win11专业版 i5-12500H RTX3060

**Comment by 1178165149** [comment]
我也遇到了，每次跟抽卡似的，运气好了一次打开，运气不好一直打不开

**Comment by Black1312** [comment]
请尝试更新内测后再试，如无问题麻烦关闭issue

**Comment by zzyyyl** [comment]
`v4.24.0-beta.2` fixed

**Comment by Tatooinish** [comment]
> 请尝试更新内测后再试，如无问题麻烦关闭issue

解决了，感谢
