### ISSUE TITLE
傀影肉鸽技能选择错误

### ISSUE THREAD

**Issue by shuhangzou** [MaaAssistantArknights/MaaAssistantArknights#6298]
### 说说你遇到的问题？

在傀影肉鸽中，选择棘刺干员后，在精英二阶段会默认使用1技能而不是3技能

**Comment by mm317670** [comment]
棘刺不选3技能是精二之后的所有战斗的吗，而不是只在精二之后的第一场战斗（我尝试复现问题，发现只有精二之后第一场战斗是这样）
