### ISSUE TITLE
强制替换ADB无法删除目录

### ISSUE THREAD

**Issue by Value33** [MaaAssistantArknights/MaaAssistantArknights#6299]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA能正常连接，但部分功能使用不了，有时显示连接成功开始任务但长时间无反应，于是尝试强制替换ADB，但发现无法删除目录，在尝试关闭模拟器、重启电脑后均无效果

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12567910/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12567911/gui.log)
问题时间点为2023年9月10日17点左右

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143505230/9b74ed0a-ed7e-4559-8b0e-91918a6832d4)

### 还有别的吗？

使用的是MUMU模拟器12，之前使用的是MUMU模拟器6，问题基本上是在换完模拟器后开始出现，但最近变得更严重，频繁了

**Comment by ABA2396** [comment]
在最新的公测版改了下，更新下公测版的试试

**Comment by Value33** [comment]
更新完后还是存在问题
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143505230/a04382d5-5c4b-4d98-b585-38bf4118d980)

**Comment by Value33** [comment]
> 在最新的公测版改了下，更新下公测版的试试

请问还有什么方法可以尝试吗

**Comment by ABA2396** [comment]
管理员启动maa，并在mumu和adb关闭后（保证任务管理器里没有mumu和adb的进程）再点替换，然后把mumu设置里最后的后台保活功能关了

**Comment by Value33** [comment]
问题已解决，Thanks♪(･ω･)ﾉ
