### ISSUE TITLE
基建休息是否考虑可选排除艾丽妮？

### ISSUE THREAD

**Issue by noneoneone** [MaaAssistantArknights/MaaAssistantArknights#630]
艾丽妮的基建技能需要在训练室内连续工作，专精过一级后在下一级发挥作用，期间不能离开训练室。
但是现在的换班会导致暂时无工作的艾丽妮被送进宿舍，造成技能失效。

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/763

**Comment by MistEO** [comment]
新增了按 `未进驻` 过滤进驻宿舍，fixed
