### ISSUE TITLE
定时执行失效

### ISSUE THREAD

**Issue by Black1312** [MaaAssistantArknights/MaaAssistantArknights#6301]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

windows任务计划提前五分钟启动MAA后，到点后MAA没有执行任务，log时间9月10日上午4：55及下午16：55。MAA版本4.24beta2及前一个内测版开始出现此问题。未关闭的MAA定时任务正常

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12567978/asst.log)

### 还有别的吗？

win11 蓝叠国际模拟器 MAA4.24beta2

**Comment by status102** [comment]
v4.24.0-beta.2，定时任务执行成功。操作流程，勾选+填写时间，关闭并重启MAA。

[自启log.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12568145/log.log)

**Comment by ABA2396** [comment]
定时任务这部分应该只涉及gui吧？把那个日志发一下。最好再来个定时的截图。

**Comment by Black1312** [comment]
> 定时任务这部分应该只涉及gui吧？ 把那个日志发一下。 最好再来个定时的截图。

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12580059/gui.log)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64343218/4010d32b-6021-4c47-ae41-beb9adc64ee8)

**Comment by ABA2396** [comment]
之前那个资源加载问题修完之后就没这个问题了吧
