### ISSUE TITLE
12-19与12-20无法正确在位置部署干员

### ISSUE THREAD

**Issue by littlewhite29** [MaaAssistantArknights/MaaAssistantArknights#6304]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

12-19与12-20的作业无法正常部署干员。位置会偏差，导致干员无法部署下去。而MAA中仍然显示是正常运行

### 日志文件

在21-45-42时截图，问题出现时应该在45分内
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12568311/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12568318/asst.log)

### 截图

![Snipaste_2023-09-10_21-45-42](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139008619/229b6914-1b76-4a64-973e-240b95f69fa4)
![Snipaste_2023-09-10_21-45-52](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139008619/8363d4b4-a49b-4a07-bccd-95ea8b5adc23)
![Snipaste_2023-09-10_21-46-44](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/139008619/1d6e81d1-de3a-44c3-8456-6652fc7208cf)

**Comment by status102** [comment]
你使用的作业是12-20磨难难度，但是选的关卡却是12-20普通难度。不同难度地图不一样

**Comment by littlewhite29** [comment]
的确。切回忘记检查难度。
