### ISSUE TITLE
自带基建策略没有正确检查贸易站的谈判策略

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#6305]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA自带的换班策略似乎没有正确检查贸易站的谈判策略，例如在搓玉卖玉的时候用巫恋三人组

### 日志文件

[Uploading asst.log…]()
[Uploading gui.log…]()

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30530115/35500f33-180a-4b46-95a7-7653cdc962e6)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30530115/674fa290-a3ac-4143-8a86-0a46c6461d92)

**Comment by Minepig** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12568877/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12568878/gui.log)

**Comment by ABA2396** [comment]
@MistEO 瞅瞅

**Comment by yyyy52** [comment]
出现同样问题
