### ISSUE TITLE
MAA在定时启动并设置了切换配置时大概率白屏卡死导致无法继续运行

### ISSUE THREAD

**Issue by clark1091** [MaaAssistantArknights/MaaAssistantArknights#6307]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，我的MAA设置了这样的定时策略，但是经常会白屏卡死，看时间点大概就是换完配置后
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134053964/0557e199-5cb7-4278-9cc0-a162cc475e5d)

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12571419/asst.zip)
[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12571420/gui.zip)
大概就在9.11的上午九点左右

### 还有别的吗？

win11，蓝叠5国际版hyper-v

**Comment by ABA2396** [comment]
.4-beta.2改了下，更新下公测版试试

**Comment by clark1091** [comment]
更新了，今天又白屏卡死一次

**Comment by ABA2396** [comment]
再发下日志，并说下时间点
