### ISSUE TITLE
Mac 版挂机萨米肉鸽，maa经常闪退

### ISSUE THREAD

**Issue by WindStill** [MaaAssistantArknights/MaaAssistantArknights#6311]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Mac 版挂机萨米肉鸽的时候，maa经常闪退。
傀影、水月肉鸽连续挂机一到两天的情况下，maa均未出现闪退情况。

v4.24.0-beta.2
v4.24.0-beta.1

以上两个版本都有这个情况 v4.23.3 未测试

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12573896/asst.log)
问题出现的时间点即为日志最后时间

Mac版未找到gui.log 文件

### 还有别的吗？

macOS 12.6
MacBook Pro (14-inch, 2021)
Chip Apple M1 Pro
Memory 16GB

**Comment by JokerDoflamingo** [comment]
用的什么模拟器？
我win10/夜神模拟器7.0.5.8001/MAA 4.23.3，运行萨米肉鸽经常闪退到模拟器桌面，报截图失败错误。
更换MUMU12模拟器，一切正常。

**Comment by WindStill** [comment]
> 用的什么模拟器？ 我win10/夜神模拟器7.0.5.8001/MAA 4.23.3，运行萨米肉鸽经常闪退到模拟器桌面，报截图失败错误。 更换MUMU12模拟器，一切正常。

M1芯片的Mac只能用 playcover，目前没有支持的第三方模拟器可用。playcver之前用过一段时间AVD，但是使用起来比较麻烦。
