### ISSUE TITLE
MAA在刷理智时选择关卡错误

### ISSUE THREAD

**Issue by Sam-0324** [MaaAssistantArknights/MaaAssistantArknights#6312]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，版本为最新版（v4.24.0-beta.2.d007.g4fdf09f4d）在刷理智的设置页面选择指定材料-采购凭证，设置了刷取数量
关卡选择为上次/当前，未设置“剩余理智”选项

问题：MAA进入了上次刷取的关卡（CV-7），而不是自动进入AP-5并刷取采购凭证。

### 日志文件

gui.log没写进去，不知道为啥
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12574150/asst.log)
*16:36:00左右打开的进程

**Comment by zzyyyl** [comment]
鼠标悬停小提示：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/86b29e50-84cd-4976-a562-5a4f3cc17814)
