### ISSUE TITLE
建议在复刻活动开启后关卡导航中增加一键进行所有普通关和EX关的扫荡

### ISSUE THREAD

**Issue by inCloudRain** [MaaAssistantArknights/MaaAssistantArknights#6325]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

这样可以便于完成任务

**Comment by status102** [comment]
普通关有了，#6230

**Comment by ABA2396** [comment]
> 普通关有了，#6230
> EX关除了突袭8其他的需要打嘛

只有突袭八要打，其他的不用（Ex只有代币，效率很低），我觉得没必要做。

**Comment by ABA2396** [comment]
普通关的导航会在之后的复刻活动加在关卡列表里的。

**Comment by inCloudRain** [comment]
> > 普通关有了，#6230
> > EX关除了突袭8其他的需要打嘛
> 
> 只有突袭八要打，其他的不用（Ex只有代币，效率很低），我觉得没必要做。

我认为是需要的，我想扫荡的初衷就是完成任务拿代币

**Comment by status102** [comment]
EX主要是缺导航，普通关有之前每次活动都攒了图，EX好像没

**Comment by ABA2396** [comment]
ex给的代币换钱还不如打ce呢）一般商店都能搬完的啊

**Comment by Constrat** [comment]
In RERUN scenario. You should NEVER farm EX stages.

You could eventually farm EX-8 Raid but it's only if you don't have enough: 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/2d02d66b-e15f-4b46-b4d1-2cfd5ef738bf)

**Comment by inCloudRain** [comment]
> In RERUN scenario. You should NEVER farm EX stages.
> 
> You could eventually farm EX-8 Raid but it's only if you don't have enough: ![image](https://user-images.githubusercontent.com/56174894/267614675-2d02d66b-e15f-4b46-b4d1-2cfd5ef738bf.png)
> 
> Also Raid stages usually don't allow Auto Deploy, so even after adding all the necessary navigation it would still be useless.
> 
> This enhancement would only be useful for a very small % of MAA users. For the other % it would be a waste of sanity.

为什么不应该在复刻活动中打ex关完成任务拿代币呢？是否有依据？

**Comment by Constrat** [comment]
> 为什么不应该在复刻活动中打ex关完成任务拿代币呢？是否有依据？

1. Replica tokens are only given with the Special Furniture which is only present in EX-8 RAID.
2. Completing the EX stages to get the additional store points are always less efficient than just farming the normal stages, as ABA said 
<details><summary>ABA2396</summary>
<p>

ex给的代币换钱还不如打ce呢）一般商店都能搬完的啊
</p>
</details> 

In conclusion:
1. Could be an interesting enhancement BUT: every replica event ALWAYS gives more replica currency than the new items in the store. This means that you DON'T have to complete all the replica currency related stasks.
2. is useless.

**Comment by ABA2396** [comment]
正常玩的话，就算不打ex关，每天的理智是足够换完商店并且溢出的，所以ex关那些任务的奖励你可以当做一点等于10龙门币算，ce6的效率都比这个高很多倍。
