### ISSUE TITLE
开荒不义之财的EX关时无法正常放置干员

### ISSUE THREAD

**Issue by 0O0o0oOoO00** [MaaAssistantArknights/MaaAssistantArknights#6327]
### 说说你遇到的问题？

在使用 maa://27846 开荒 普通CV-EX-3 时无法正常放置干员，在尝试替换adb，清除cache\avatars，重启模拟器和maa，重启电脑，使用MaaTouch后均无效果或者好转的迹象

Logs：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12585879/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12585880/gui.log)

其他：
![MaaVersion](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/11174151/2748eb92-9da5-4224-a49e-b7fa7240fcf4)
![WindowsVersion](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/11174151/f063e7f0-4e9b-4bac-9570-7e42b16b42f5)
![MumuVersion](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/11174151/c28470e4-b907-487d-9bf2-9aa5beeabaa7)

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/669ff378f89543bf703fafa6d1d1dfbb8569def3 fixed
