### ISSUE TITLE
定时执行-自定义配置选择无效果

### ISSUE THREAD

**Issue by zeto1979** [MaaAssistantArknights/MaaAssistantArknights#6328]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我在定时执行中选择了自定义配置选择，确定是选择了五个选项，但是当时间到达设定的时间时直接开始了运行而未重启并更换配置

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12585956/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12585960/gui.log)

### 截图

![QQ截图20230912194149](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144797799/e32f20f2-fe4b-42d7-86f1-75936d0f24c3)
![QQ截图20230912194140](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144797799/47926226-cfc1-4bcb-8df0-be4e11d19a18)

### 还有别的吗？

mumu12，win10

**Comment by ABA2396** [comment]
什么时候选择的？这个的话是提前五分钟重启切换，如果是在五分钟内勾选的话是不会换的（这个可能要加一个处理），先确定下是不是这个问题。

**Comment by ABA2396** [comment]
鼠标放在那个自定义的上面，是会有提示的

**Comment by zeto1979** [comment]
目前来看只有第一次可以，后面自定义就失效了

**Comment by ABA2396** [comment]
定六分钟之后的时也不行吗？

**Comment by zeto1979** [comment]
> 定六分钟之后的时也不行吗？

我是试了第一次之后直接把时间调到10分钟后，然后到时候就直接开始运行了

**Comment by ABA2396** [comment]
因为现在的逻辑是把显示的时间-5分钟去做匹配的，等于说是设定的时间-5分钟的时候有一个重启的定时任务，一定要到负五分钟那个点才能执行重启）

**Comment by zeto1979** [comment]
> 因为现在的逻辑是把显示的时间-5分钟去做匹配的，等于说是设定的时间-5分钟的时候有一个重启的定时任务，一定要到负五分钟那个点才能执行重启）

哦哦

**Comment by zeto1979** [comment]
> 因为现在的逻辑是把显示的时间-5分钟去做匹配的，等于说是设定的时间-5分钟的时候有一个重启的定时任务，一定要到负五分钟那个点才能执行重启）

那我再试一次看看明天早上的能不能行

**Comment by zeto1979** [comment]
那我再试一次然后看看明天早上能不能行

**Comment by zeto1979** [comment]
> 因为现在的逻辑是把显示的时间-5分钟去做匹配的，等于说是设定的时间-5分钟的时候有一个重启的定时任务，一定要到负五分钟那个点才能执行重启）
![QQ截图20230913185538](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144797799/66346d74-df12-4a81-886b-48d73b62dcd5)
![QQ截图20230913185546](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144797799/4f863d30-2a6a-4121-ab40-dd0cdd56da74)

今天早上的应该是因为我一直没有碰过电脑所以明日方舟没有更新数据导致没有连上

**Comment by zeto1979** [comment]
> 因为现在的逻辑是把显示的时间-5分钟去做匹配的，等于说是设定的时间-5分钟的时候有一个重启的定时任务，一定要到负五分钟那个点才能执行重启）

但是我刚刚又试了一次发现确实第二次进行任务不会重启改变配置
![QQ截图20230913192852](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144797799/accb9660-deab-4f9c-88e1-284cacd05fb9)

**Comment by zeto1979** [comment]
> 因为现在的逻辑是把显示的时间-5分钟去做匹配的，等于说是设定的时间-5分钟的时候有一个重启的定时任务，一定要到负五分钟那个点才能执行重启）

我又试了一下同个配置换一个定时执行栏，发现也没有重启配置
![QQ截图20230913193933](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144797799/574a3619-5ca1-41f3-9a69-54be79f863bb)

**Comment by zeto1979** [comment]
> 因为现在的逻辑是把显示的时间-5分钟去做匹配的，等于说是设定的时间-5分钟的时候有一个重启的定时任务，一定要到负五分钟那个点才能执行重启）

确定了每次设定和执行的时间至少10分钟

**Comment by ABA2396** [comment]
没太看明白）能用配置A/B/C/D和执行时间来举个例子吗？
如果现在的配置和定时要求的配置是一样的话是不会重启的

**Comment by zeto1979** [comment]
> 没太看明白）能用配置A/B/C/D和执行时间来举个例子吗？ 如果现在的配置和定时要求的配置是一样的话是不会重启的

我的自定义选择了ABCD，第一次：设置在30分钟后执行，然后我取消了ABC只选择了D，30分钟后重启并启用ABCD。
第二次：确定重启后我停止运行，并且再次设置在30分钟并且不改变自定义一栏，然后我取消ABC保留D，30分钟后没有重启和改变配置并且直接开始进行配置D的运行。
如果我第一次不主动取消结果也一样

**Comment by ABA2396** [comment]
意思是，
第一次：原来选的是ABCD四个配置，然后手动取消了ABC，在当前配置和定时配置D不同的时候跑了定时D，这个时候ABC又被重新选上了
第二次：原来选的是ABCD四个配置，然后手动取消了ABC，在当前配置和定时配置D相同的时候跑了定时D，这个时候不会重启并直接执行了

**Comment by ABA2396** [comment]
还是说你说的ABCD是指
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/2bd5a702-c29f-4e5c-82e1-b15a0a36723c)
这里的任务？

**Comment by ABA2396** [comment]
如果你说的是主界面里的任务的话，是要通过
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/1e206b07-e02d-4167-b922-e4056476c87b)
来切换到对应的配置来设置那个定时的任务
比如A配置是
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/a47a31a2-03e0-40e5-beea-8b85fe3afd4d)
B配置是
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/8a42a49c-4e4d-49cc-ae34-f11e84104f78)
C配置是
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/18f59f08-6d04-49b6-b130-2b3f0d167b18)
D配置是
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/19f58e1e-9621-4b09-a722-debc3b18f7a3)
那这样的定时才代表到点之后分别重启并执行 开始唤醒、自动公招、基建换班、刷理智
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/ffe09f18-e210-4aec-b632-6e6f6c02a000)

**Comment by zeto1979** [comment]
> 如果你说的是主界面里的任务的话，是要通过 ![image](https://user-images.githubusercontent.com/99072975/268331566-1e206b07-e02d-4167-b922-e4056476c87b.png) 来切换到对应的配置来设置那个定时的任务 比如A配置是 ![image](https://user-images.githubusercontent.com/99072975/268331774-a47a31a2-03e0-40e5-beea-8b85fe3afd4d.png) B配置是 ![image](https://user-images.githubusercontent.com/99072975/268331876-8a42a49c-4e4d-49cc-ae34-f11e84104f78.png) C配置是 ![image](https://user-images.githubusercontent.com/99072975/268331922-18f59f08-6d04-49b6-b130-2b3f0d167b18.png) D配置是 ![image](https://user-images.githubusercontent.com/99072975/268331968-19f58e1e-9621-4b09-a722-debc3b18f7a3.png) 那这样的定时才代表到点之后分别重启并执行 开始唤醒、自动公招、基建换班、刷理智 ![image](https://user-images.githubusercontent.com/99072975/268332156-ffe09f18-e210-4aec-b632-6e6f6c02a000.png)

是这样啊

**Comment by zeto1979** [comment]
我今晚试试

**Comment by zeto1979** [comment]
辛苦了
