### ISSUE TITLE
自动战斗无法读取JSON文件

### ISSUE THREAD

**Issue by Kevinxzk** [MaaAssistantArknights/MaaAssistantArknights#6329]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用自动战斗时读8月中之后的作业会提示读取文件失败，读之前的作业都没问题；
使用的是雷电模拟器，MAA稳定版和内测版最新都试过，都不行。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12585978/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12585979/asst.log)

### 还有别的吗？

雷电模拟器 Win10

**Comment by Black1312** [comment]
问题原因：overview.json文件ota更新异常
手动将最新overview.json文件覆盖即可暂时解决
此issue保留，待修复bug
