### ISSUE TITLE
自动战斗无法部署干员

### ISSUE THREAD

**Issue by aioi50** [MaaAssistantArknights/MaaAssistantArknights#6331]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗，可以自动编队，开始关卡后也有暂停和调倍速的操作，但是部署干员的操作一瞬间就全部结束，实际上干员都没部署

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12586295/asst.zip)
[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12586296/gui.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/65849197/8e1a3615-ca10-4f67-8425-f7a29610f5cb)

### 还有别的吗？

模拟器版本mumu12，MAA版本：[alpha/v4.24.0-beta.2.d024.ge7fd011cc]

**Comment by pavocritatus** [comment]
我也是同样的问题，试过删除那些干员头像的文件，并不能解决问题，很伤心

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/669ff378f89543bf703fafa6d1d1dfbb8569def3 fixed
