### ISSUE TITLE
基建排班里麒麟R夜刀识别不上

### ISSUE THREAD

**Issue by drtsbgnhk** [MaaAssistantArknights/MaaAssistantArknights#6335]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12587349/gui.log)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12587343/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144815122/11f706fc-6be8-4dd4-9bd2-bbfa6294478e)

### 还有别的吗？

MAA-v4.23.3-win-x64

**Comment by Lancarus** [comment]
请更新版本
