### ISSUE TITLE
Mac版本无法识别sidestory不义之财的关卡，疑似未更新最新的活动信息

### ISSUE THREAD

**Issue by V-sion-V** [MaaAssistantArknights/MaaAssistantArknights#6337]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我在使用Mac版的过程中，发现刷理智中不包含最新的活动关卡，即使使用“当前关卡”，也会因为无法识别掉落物而卡在战斗成功界面，Win版本不存在此问题，更新至最新beta版本后依然未解决。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12589916/asst.log)

### 截图

<img width="345" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71446327/110f6aed-9853-4f87-94d5-dc5a9057cc43">

**Comment by hguandl** [comment]
[v4.24.0-beta.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.24.0-beta.1) 应该已经支持了
