### ISSUE TITLE
【已解决】疑似误触导致抽卡【需求】主界面在运行的时候，把抽卡按钮 disable

### ISSUE THREAD

**Issue by joty7845** [MaaAssistantArknights/MaaAssistantArknights#6338]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

亲爱的牛牛，我在使用你的mma当中出现了疑似误触导致抽卡的这种BUG，损失的不多只有十发，于不义之财卡池出现的问题，具体时间9月7号

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12591549/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12591550/gui.log)

### 截图

无法提供照片，因为当时不在家

### 还有别的吗？

无

**Comment by MistEO** [comment]
```log
[2023-09-07 18:38:43.823][INF][Px5bf8][Tx5bf4] asst::Assistant::append_task Custom {"task_names":["GachaTenTimes"]}
```

你自己点的 “牛牛抽卡”

**Comment by zzyyyl** [comment]
> 你自己点的 “牛牛抽卡”。MAA 是任务队列，当时正在执行其他任务（看 log 是正在刷理智），点的时候没反应不代表就不会去抽了（

试了一下，这玩意居然不能 stop，一旦开始就没有回头路辣！（所以要不要做个 stop）

**Comment by Minepig** [comment]
你把MAA关了不就stop了（乐）

**Comment by MistEO** [comment]
> > 你自己点的 “牛牛抽卡”。MAA 是任务队列，当时正在执行其他任务（看 log 是正在刷理智），点的时候没反应不代表就不会去抽了（
> 
> 试了一下，这玩意居然不能 stop，一旦开始就没有回头路辣！（所以要不要做个 stop）

我觉得可以主界面在运行的时候，就把抽卡按钮 disable 了？

**Comment by SherkeyXD** [comment]
> 我觉得可以主界面在运行的时候，就把抽卡按钮 disable 了？

好主意

**Comment by ABA2396** [comment]
> > > 你自己点的 “牛牛抽卡”。MAA 是任务队列，当时正在执行其他任务（看 log 是正在刷理智），点的时候没反应不代表就不会去抽了（
> > 
> > 
> > 试了一下，这玩意居然不能 stop，一旦开始就没有回头路辣！（所以要不要做个 stop）
> 
> 我觉得可以主界面在运行的时候，就把抽卡按钮 disable 了？

快读读 RunningState 的 Idle

**Comment by joty7845** [comment]
哦哦，所以我点了一次抽卡会一直运行下去嘛？（

**Comment by SherkeyXD** [comment]
> 哦哦，所以我点了一次抽卡会一直运行下去嘛？（
> 

不是，意思是你点的抽卡会在 maa 的任务结束后再执行，也就是延迟执行

可能是你看没反应点了好几次，所以导致抽了好几次

**Comment by joty7845** [comment]
啊这，我明白了（
