### ISSUE TITLE
希望Mac版增加支持外服生息演算

### ISSUE THREAD

**Issue by Argonautes0607** [MaaAssistantArknights/MaaAssistantArknights#6339]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

看到beta3更新支持了EN的生息演算，发现Mac版本没有选项出现，希望能够增加刷生息演算的任务,谢谢各位大佬

**Comment by hguandl** [comment]
4102f9727ee437a3371e68635b556f5edbe59e34
