### ISSUE TITLE
小车被划了

### ISSUE THREAD

**Issue by sunshinemo** [MaaAssistantArknights/MaaAssistantArknights#634]
图上传失败，我简单说一下。公招识别结果：支援机械/削弱/狙击干员/近卫干员/治疗，自动选择了4星tag，希望可以提高小车的优先级

**Comment by zzyyyl** [comment]
已经有很多 issue 提过这个了， https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/531#issuecomment-1132920134 有个汇总
