### ISSUE TITLE
自动编队选不到白面鸮或错选为其他干员

### ISSUE THREAD

**Issue by AnnoyingFlowers** [MaaAssistantArknights/MaaAssistantArknights#6341]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12593536/asst.log)

没选到白面鸮的时间点为12:43:20（我怀疑是没点上，因为有选二技能的操作）
错选为焰影苇草的时间点为12:45:48

### 截图

只录到了没选上的情况，选错的没录上

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89131639/8200215c-a4c9-4136-9175-51ad396f1f73

### 还有别的吗？

mumu12
win10
v4.24.0-beta.3
maa://27848

**Comment by status102** [comment]
有用maaTouch么（会不会和maaTouch有关

**Comment by AnnoyingFlowers** [comment]
> 有用maaTouch么（会不会和maaTouch有关

是minitouch捏_(:з」∠)_

**Comment by zzyyyl** [comment]
现在还有没有问题（？

> 有用maaTouch么（会不会和maaTouch有关

现在修了其实 maaTouch 应该比 minitouch 更稳定！

**Comment by zzyyyl** [comment]
仔细看了一下，没选上是因为初始的时候不在列表开始（？

大概要加一个往前的滑动（这是yj的bug吧）
