### ISSUE TITLE
4.24.0-beta.3 Microsoft Defender 报毒

### ISSUE THREAD

**Issue by govizlora** [MaaAssistantArknights/MaaAssistantArknights#6342]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天MAA自动更新后被Microsoft Defender检测说有病毒
我自己下载了一份，还是说有毒
用beta2就没事。。。

MAA-v4.24.0-beta.3-win-x64.zip 文件SHA256：
F98B88267872AFA0FEE973AB8E430793A435512C1917704739CFBE9A50B3CFF3

### 日志文件

Microsoft Defender Antivirus has detected malware or other potentially unwanted software.
 For more information please see the following:
https://go.microsoft.com/fwlink/?linkid=37020&name=Trojan:Win32/Prowloc.A!cl&threatid=2147727733&enterprise=0
 	Name: Trojan:Win32/Prowloc.A!cl
 	ID: 2147727733
 	Severity: Severe
 	Category: Trojan
 	Path: containerfile:_C:\Users\xxx\Downloads\MAA-v4.24.0-beta.3-win-x64.zip; file:_C:\Users\xxx\Downloads\MAA-v4.24.0-beta.3-win-x64.zip->MAA.exe
 	Detection Origin: Local machine
 	Detection Type: FastPath
 	Detection Source: User
 	User: xxx\xxx
 	Process Name: Unknown
 	Security intelligence Version: AV: 1.397.865.0, AS: 1.397.865.0, NIS: 1.397.865.0
 	Engine Version: AM: 1.1.23080.2005, NIS: 1.1.23080.2005

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/de9f9809-f79f-4b11-8a76-90f132f65b34)
