### ISSUE TITLE
MAA无法识别百嘉夏皮

### ISSUE THREAD

**Issue by mogemogeko** [MaaAssistantArknights/MaaAssistantArknights#6343]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA无法识别百嘉夏皮导致开局无法选人，换成原皮立马好了

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12594445/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12594448/asst.zip)
问题出现于9/13 15:00左右

**Comment by SherkeyXD** [comment]
删除 maa 目录下 cache/avatars 文件夹即可
