### ISSUE TITLE
可以加个森空岛签到吗

### ISSUE THREAD

**Issue by WSMTBG** [MaaAssistantArknights/MaaAssistantArknights#6344]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在模拟器或者其他设备安装了森空岛设备加个森空岛签到功能吗，我已经好几天忘记签到了...

### 有什么好的想法？

adb打开森空岛什么的

**Comment by zzyyyl** [comment]
Duplicate of #6167
