### ISSUE TITLE
开始唤醒时账号切换功能 运行时出错 未正确切换账号

### ISSUE THREAD

**Issue by dupontjoy** [MaaAssistantArknights/MaaAssistantArknights#6346]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启用了开始唤醒时账号切换功能，每次运行时第一遍会出错，卡在截图1界面，如果先进入截图2界面，再开启maa任务，才能正常切换账号

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12596087/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12596090/gui.log)

可以检查一下17:30左右的时间点

### 截图
![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/4965288/3f978e6b-c071-4226-bb1f-0db777641fa4)
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/4965288/621d0df8-d82b-4655-97d7-e4014a5cb34f)

**Comment by dupontjoy** [comment]
![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/4965288/9f8c4c0b-ffcf-4137-a8b6-28699ff8be0b)
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/4965288/04759c73-8fa9-4613-b0b5-4437546f9d1f)

**Comment by status102** [comment]
已提交PR，尝试进行修复

**Comment by status102** [comment]
v4.24.0-beta.4已推送，可以试试新版本还有没有问题

**Comment by dupontjoy** [comment]
> v4.24.0-beta.4已推送，可以试试新版本还有没有问题

多谢，更新试了几次，可以正常切换了
