### ISSUE TITLE
外部推送导致MAA卡死

### ISSUE THREAD

**Issue by Black1312** [MaaAssistantArknights/MaaAssistantArknights#6349]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA版本：v4.24.0-beta.3.d011.g2102fd1e6
使用smtp推送时，测试正常，但开启推送时执行一键长草任务时最后会卡死
log时间：9月13日下午7:18

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12596831/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12596838/gui.log)

### 截图

图片发不上来，链接：https://postimg.cc/Wq4XdpHd
https://postimg.cc/HrWsjqpf

**Comment by IbukiFuko** [comment]
我用的Server酱也会卡死
