### ISSUE TITLE
萨米肉鸽自然之怒”识别错误“

### ISSUE THREAD

**Issue by Holmium3133** [MaaAssistantArknights/MaaAssistantArknights#6351]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽的关底，maa识别错误且不满编人数（无刀舞类藏品）
*因为人在准备看maa大战冰锁所以有以下第一张截图
*asst.log过大，故只上传临近关底的部分日志

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12597552/gui.log)
[asst.log.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12597674/asst.log.txt)

### 截图

![L@RC6W3DG4A3I6F}V6MGH}D](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144914820/9e4ba36f-b5d8-41f3-8cba-551d9a524bf0)
![QQ图片20230913203546](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144914820/695a852d-7b87-4536-97e0-179d0a971d05)

**Comment by Lancarus** [comment]
已在内测版修复，请更新内测版或者等待公测版或稳定版更新
