### ISSUE TITLE
(繁中服)(水月肉鴿)初始開局幹員名稱只能識別簡體字，繁體字無法識別。

### ISSUE THREAD

**Issue by Nisaseku** [MaaAssistantArknights/MaaAssistantArknights#6352]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

時間：約2023/09/13 20:57
模式：水月肉鴿
問題：自動肉鴿，高級設定內的開局幹員，原本打上【鴻雪】，但在任務開始之後
選穩扎穩打，開局首選號角，並非鴻雪；選先手必勝，除了不會選鴻雪之外，會放棄第三張招募券(?)
在同日約2023/09/13 22:19，改用簡體【鸿雪】後，開局會正常選擇該名幹員。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12598914/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12598920/gui.log)

### 截图

[MAA.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12599066/MAA.zip)

### 还有别的吗？

模擬器：雷電_9.0.53版本

**Comment by Constrat** [comment]
If I'm understanding what you mean. It's intended and is not a bug.
The starting operator NEEDS to be in Simplified Chinese.

**Comment by Nisaseku** [comment]
> If I'm understanding what you mean. It's intended and is not a bug. The starting operator NEEDS to be in Simplified Chinese.

ohh!!  I got it, thanks your answer :)
