### ISSUE TITLE
希望能够增加森空岛的自动签到功能

### ISSUE THREAD

**Issue by Heart-of-engine** [MaaAssistantArknights/MaaAssistantArknights#6354]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

暂无

### 有什么好的想法？

如题，希望能够增加一个针对森空岛的自动签到功能，这样使用起来也能够更加方便（像我们社畜很多时候晚上十一二点才到家，挂上MAA就睡觉了，很容易忘记森空岛的签到），辛苦了！

### 其他内容

暂无

**Comment by zzyyyl** [comment]
:eyes:你的模拟器能装森空岛吗

**Comment by Heart-of-engine** [comment]
> 👀你的模拟器能装森空岛吗

MUMU12模拟器是可以的

**Comment by status102** [comment]
夜神模拟器
v7.0.5.1003
森空岛可用

**Comment by zzyyyl** [comment]
所以之前谁说模拟器装不了森空岛（

有哪个模拟器装不了吗

**Comment by SherkeyXD** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantSkland

**Comment by Heart-of-engine** [comment]
> https://github.com/MaaAssistantArknights/MaaAssistantSkland

收到，谢谢！
