### ISSUE TITLE
 启动mumu12模拟器时 弹出this application failed to start because no qt platform plugin报错

### ISSUE THREAD

**Issue by lemxlg** [MaaAssistantArknights/MaaAssistantArknights#6355]
### 说说你遇到的问题？

我使用python中的subprocess.Popen方法来启动mumu12模拟器时会遇到这个问题，触发条件为程序打包后。
当我使用未打包的程序执行上述命令时能够正常启动mumu12模拟器。
我被这个问题困扰了很久，希望能够在此寻求答案，请帮帮我。

**Comment by ABA2396** [comment]
这个问题报错不是已经说明了吗，要么指定一下QT_QPA_PLATFORM，要么修改下打包配置，要么干脆把这玩意给打包进去）
