### ISSUE TITLE
借助战刷OF1的功能，能否使用固定的某个编队

### ISSUE THREAD

**Issue by fcbarcareer** [MaaAssistantArknights/MaaAssistantArknights#6358]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

没有

### 有什么好的想法？

借助战刷OF1的功能，能否使用固定的某个编队，而不是选择上次使用的分队，不然我每次推关卡配的队伍都会因此被打散。

### 其他内容

RT

**Comment by status102** [comment]
duplicate of #4624

**Comment by Constrat** [comment]
iirc it will only change the last used formation. You are suggesting to ALWAYS use one of the four formations?

**Comment by fcbarcareer** [comment]
> iirc it will only change the last used formation. You are suggesting to ALWAYS use one of the four formations?

Yes

**Comment by Constrat** [comment]
Duplicate of #4624

**Comment by Constrat** [comment]
We will work on the existing issue #4624
