### ISSUE TITLE
MAA工作异常，基建公招等任务循环卡死，人工介入操作之后扔下做到一半的任务跳过

### ISSUE THREAD

**Issue by clark1091** [MaaAssistantArknights/MaaAssistantArknights#6359]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，触发条件不明，我以为是由于模拟器和MAA在后台，但即使窗口始终保留在前台依旧有概率出现，会留在宿舍选人界面一直向右划干员重复找人，如果无人介入甚至会一直划上几个小时

### 日志文件

我去，删临时文件手一滑把asst.log删了......
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12605334/gui.log)

**Comment by ABA2396** [comment]
光有gui.json也没用啊）

**Comment by clark1091** [comment]
[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12615049/asst.bak.zip)
这个不知能不能用，似乎是自动备份
