### ISSUE TITLE
[Bug 反馈][肉鸽相关] 投资源石碇选项失效

### ISSUE THREAD

**Issue by harvey1995** [MaaAssistantArknights/MaaAssistantArknights#6362]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

背景：在刷水月肉鸽藏品时（说的就是你指路鳞），我按照预想的配置开始了任务
具体配置为：常规设置中 -- 策略选择了[刷源石碇]；高级设置中 -- 关闭了[投资源石碇]选项、打开了[刷新商店]选项

实际开始运行之后，发现到第1层关底时，MAA依然进行了投资源石碇的操作

后来为了验证是否是选项本身的问题，我试着更新到了最新的内测版本（v4.24.0-beta.3.d011.g2102fd1e6）、在水月和傀影肉鸽进行了不同的配置并开始任务，对应的结果如下：
1. 策略选择[刷源石碇]或[烧开水]、关闭[投资源石碇]选项：依然继续投资
2. 策略选择[刷等级]、关闭[投资源石碇]选项：**没有**继续投资
3. 策略选择[刷源石碇]或[烧开水]、关闭[投资源石碇]选项、[投资N个源石碇后停止任务]配置0：依然尝试继续投资、且会在打开投资界面后**直接结束任务**（注：此时[投资N个源石碇后停止任务]的配置其实是置灰无法编辑的，是先配置0之后再关闭的[投资源石碇]选项）

所以猜测可能是在特定策略下，[投资源石碇]选项的配置没有生效，导致继续投资、甚至出现[投资0个源石碇后停止任务]的情况
还有一种可能是，在所有策略下，[投资源石碇]选项的配置都没有生效，[刷等级]没有继续投资是因为要往下打买道具

辛苦大佬啦

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12607321/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12607323/gui.log)
今天刚开始用所以日志不长，从16点50多开始

### 截图

————————————————
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145001893/77a2b5dc-9194-4cdb-ba36-9cf401a20326)
第3条测试条件下水月肉鸽测试配置如图
————————————————
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145001893/1c1e6034-5986-4e46-be1f-4dde6ee544a5) ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145001893/d6a28083-8b7c-4bd2-b31f-ac4bff3bf4ab)
傀影肉鸽测试配置如图

**Comment by SherkeyXD** [comment]
因为之前有很多人选刷源石锭模式的时候没勾选高级设置中的投资源石锭，所以我们设置了使用源石锭模式默认开启投资

**Comment by harvey1995** [comment]
> 因为之前有很多人选刷源石锭模式的时候没勾选高级设置中的投资源石锭，所以我们设置了使用源石锭模式默认开启投资

 好嘞，感谢答复，想问一下如果想自己想通过改文件把这个默认开启投资的功能关闭的话，可以修改哪个文件呢，自己没能找到相应的代码_(:°з」∠)_

**Comment by SherkeyXD** [comment]
相关代码修改后得重新构建，没有开发环境的话很麻烦（

**Comment by harvey1995** [comment]
> 相关代码修改后得重新构建，没有开发环境的话很麻烦（

好的，我先用另外的策略刷刷看_(:°з」∠)_

**Comment by ABA2396** [comment]
> 因为之前有很多人选刷源石锭模式的时候没勾选高级设置中的投资源石锭，所以我们设置了使用源石锭模式默认开启投资

那还不如直接界面做处理，给这个勾选框给屏蔽了）

**Comment by SherkeyXD** [comment]
好主意 一会写了（

**Comment by harvey1995** [comment]
> > 因为之前有很多人选刷源石锭模式的时候没勾选高级设置中的投资源石锭，所以我们设置了使用源石锭模式默认开启投资
> 
> 那还不如直接界面做处理，给这个勾选框给屏蔽了）

是的，现在有点混淆，UI是可选未选择的状态，但代码是默认开启的
