### ISSUE TITLE
打开MAA 时遇到了问题 ，下载最新的全量包替换后依然报错

### ISSUE THREAD

**Issue by SuperAc** [MaaAssistantArknights/MaaAssistantArknights#6365]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天开机后，打开MAA提示
MAA 遇到了问题
The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
解决方案
出现未知错误
详细信息
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0. ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   在 System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   在 System.Text.Json.Utf8JsonReader.Read()
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   在 System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   在 MaaWpfGui.Helper.ETagCache.Load()
   在 MaaWpfGui.Main.Bootstrapper.OnStart()
   在 Stylet.BootstrapperBase.Start(String[] args)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

asst.log无时间节点相关日志
gui.log:
[2023-09-15 09:25:24.257] <1><> ===================================
[2023-09-15 09:25:24.280] <1><> MaaAssistantArknights GUI started
[2023-09-15 09:25:24.280] <1><> Maa ENV: Production
[2023-09-15 09:25:24.286] <1><> User Dir D:\Apps\Relax\tools\MeoAssistantArknightsB
[2023-09-15 09:25:24.286] <1><> ===================================
[2023-09-15 09:25:25.556] <1><> Unhandled exception
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0. ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   在 System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   在 System.Text.Json.Utf8JsonReader.Read()
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   在 System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   在 MaaWpfGui.Helper.ETagCache.Load()
   在 MaaWpfGui.Main.Bootstrapper.OnStart()
   在 Stylet.BootstrapperBase.Start(String[] args)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2023-09-15 09:25:31.861] <1><> ===================================
[2023-09-15 09:25:31.880] <1><> MaaAssistantArknights GUI started
[2023-09-15 09:25:31.881] <1><> Maa ENV: Production
[2023-09-15 09:25:31.886] <1><> User Dir D:\Apps\Relax\tools\MeoAssistantArknightsB
[2023-09-15 09:25:31.886] <1><> ===================================
[2023-09-15 09:25:32.677] <1><> Unhandled exception
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0. ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   在 System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   在 System.Text.Json.Utf8JsonReader.Read()
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   在 System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   在 MaaWpfGui.Helper.ETagCache.Load()
   在 MaaWpfGui.Main.Bootstrapper.OnStart()
   在 Stylet.BootstrapperBase.Start(String[] args)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2023-09-15 09:25:42.870] <1><> ===================================
[2023-09-15 09:25:42.889] <1><> MaaAssistantArknights GUI started
[2023-09-15 09:25:42.889] <1><> Maa ENV: Production
[2023-09-15 09:25:42.893] <1><> User Dir D:\Apps\Relax\tools\MeoAssistantArknightsB
[2023-09-15 09:25:42.893] <1><> ===================================
[2023-09-15 09:25:43.729] <1><> Unhandled exception
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0. ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   在 System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   在 System.Text.Json.Utf8JsonReader.Read()
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   在 System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   在 MaaWpfGui.Helper.ETagCache.Load()
   在 MaaWpfGui.Main.Bootstrapper.OnStart()
   在 Stylet.BootstrapperBase.Start(String[] args)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2023-09-15 09:30:45.207] <1><> ===================================
[2023-09-15 09:30:45.222] <1><> MaaAssistantArknights GUI started
[2023-09-15 09:30:45.222] <1><> Maa ENV: Production
[2023-09-15 09:30:45.224] <1><> User Dir D:\Apps\Relax\tools\MeoAssistantArknightsB
[2023-09-15 09:30:45.226] <1><> ===================================
[2023-09-15 09:30:45.979] <1><> Unhandled exception
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0. ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   在 System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   在 System.Text.Json.Utf8JsonReader.Read()
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   在 System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   在 MaaWpfGui.Helper.ETagCache.Load()
   在 MaaWpfGui.Main.Bootstrapper.OnStart()
   在 Stylet.BootstrapperBase.Start(String[] args)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 截图

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/23373139/175356ac-38cf-4f05-8a90-8f3a240d7d0a)

**Comment by ABA2396** [comment]
现在好像在更新的时候手动把maa关掉，就遇到这个问题。先把完整包解压在一个新的文件夹里，然后把config文件夹移到这个新的文件夹里。
