### ISSUE TITLE
水月肉鸽卡藏品

### ISSUE THREAD

**Issue by JT8001** [MaaAssistantArknights/MaaAssistantArknights#6366]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

挂水月肉鸽，maa有时候会误点藏品查看界面，之后就卡死不会进行下一步操作，同时提示已放弃本次探索

### 日志文件

[filelist.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12614814/filelist.txt)

### 截图

<img width="1207" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145080865/0cb57de9-60ff-494f-8b3a-598324aafa81">

**Comment by zimuyanghua** [comment]
+1，最近更新出现，maa误点到藏品界面然后就无法识别一直返回放弃探索
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46125819/ff8c62cf-8db9-4cf6-a16c-f8b6f6721e2d)

**Comment by Lancarus** [comment]
duplicate of #5892
