### ISSUE TITLE
日服 傀影肉鸽 某不期而遇节点刷取异常

### ISSUE THREAD

**Issue by WanKafka** [MaaAssistantArknights/MaaAssistantArknights#6369]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

遇到如图的不期而遇节点会卡住

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12615323/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12615325/gui.log)

时间在上午10点50多分

### 截图

![Uploading )MV3RG5SKRD6[8R@)@Y$VI2.png…]()
![QQ 3{BPA2)`1($0ZN67`8_Y](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104065679/541d2d59-d6b7-4d9b-8a93-4f54bcd7ffba)

### 还有别的吗？

mumu12，win10

**Comment by WanKafka** [comment]
![)MV3RG5SKRD6 8R@)@Y$VI2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104065679/1fcf7e82-0f98-4cca-868b-af78ef749d22)
图片没有上传成功，重新上传一下

**Comment by mikage3miya** [comment]
目前的v4.25.1-alpha.1.d068.gf49c5e963还是会卡在这个地方

**Comment by zzyyyl** [comment]
日志和截图对不上啊，日志里显示识别到的是 “扎营”，图给的是 “以血还血”
