### ISSUE TITLE
账号切换功能出错

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#6371]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

目前的账号切换功能只能处理停留在游戏主界面的时候，主动退出登录切换账号，如果是MAA直接启动游戏是没法使用的，会卡在这个页面：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30530115/cac79da6-789e-406c-9b94-a95b6df7e714)
应该是逻辑不太完善

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12615973/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12615975/gui.log)

**Comment by status102** [comment]
已提交PR

**Comment by status102** [comment]
v4.24.0-beta.4已推送，可以试试新版本还有没有问题
