### ISSUE TITLE
The input does not contain any JSON tokens

### ISSUE THREAD

**Issue by GrainRR** [MaaAssistantArknights/MaaAssistantArknights#6373]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
这个报错在打开MAA后出现，在打开之前MAA进行了自动更新，我原本的版本是4.23.3

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12616028/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12616029/asst.log)

**Comment by ABA2396** [comment]
f2d37627f1edc45a2a885980413eae5b955d7634 fixed
如果还打不开的话发下 /cache/etag.json

**Comment by GrainRR** [comment]
> [f2d3762](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/f2d37627f1edc45a2a885980413eae5b955d7634) 固定 如果还打不开的话发下 /cache/etag.json

尝试多次无法打开后删了重下，然后一模一样的设置又连接不上了

**Comment by GrainRR** [comment]
最后的解决方式是换成ADB input然后换成Maatouch

**Comment by GrainRR** [comment]
现在只有ADBInput模式能够连接模拟器

**Comment by SherkeyXD** [comment]
该改动目前还没有进入内测版，等下一次内测版更新再试试

**Comment by Constrat** [comment]
Should we just run a nightly? Considering how many issues are getting opened?

**Comment by SherkeyXD** [comment]
遇到该问题可以先尝试删除 cache 文件夹下的 etag.json，然后重启 maa

**Comment by GrainRR** [comment]
> 遇到该问题可以先尝试更新 maa 到 b4 版本
> 
> 还不行的话可以尝试删除 cache 文件夹下的 etag.json，然后重启 maa

仍然无法解决“除了ADBInput外的触控模式无法使用”的问题

**Comment by SherkeyXD** [comment]
> 仍然无法解决“除了ADBInput外的触控模式无法使用”的问题

这和 json token 问题无关，最好新开一个 issue

**Comment by GrainRR** [comment]
> > 仍然无法解决“除了ADBInput外的触控模式无法使用”的问题
> 
> 这和 json token 问题无关，最好新开一个 issue

好的，谢谢你的回复
