### ISSUE TITLE
利用火蓝之心刷模组任务时因为是无奖励关卡被停止

### ISSUE THREAD

**Issue by puzi12138** [MaaAssistantArknights/MaaAssistantArknights#6374]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，模组任务中有很多可以使用火蓝之心的无理智关卡来刷次数或者伤害，但是maa会认为这是无奖励关卡而停止任务

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12616095/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12616097/asst.log)

**Comment by MistEO** [comment]
可以刷 OF-2 或者后面的（
