### ISSUE TITLE
活动关刷理智，刷两次就不刷了

### ISSUE THREAD

**Issue by rwcups** [MaaAssistantArknights/MaaAssistantArknights#6377]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

理智很充足，活动关刷理智，刷两次就不刷了。其他关卡没试过。关卡选择是cv6，不是上一次。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12618124/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12618127/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/122712111/85bdb8ee-d768-41e2-9ea3-4a0a5dd28f3c)

**Comment by status102** [comment]
设定了指定次数为2，当然只打两次了

**Comment by MistEO** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/1338d580-c1ec-45cc-a8ea-c24f756d3b9b)

**Comment by rwcups** [comment]
不好意思，我太逆天了
