### ISSUE TITLE
Windows7系统v4.24.0-beta.1无法获取关卡数据和更新信息

### ISSUE THREAD

**Issue by HertsLeon** [MaaAssistantArknights/MaaAssistantArknights#6381]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![IMG_20230915_204456](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66908081/d1585809-1565-4421-bb5f-a03ec91973f3)
之前有反应过这个问题，但没能解决。https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6181
我手动更新到24.0beta之后反而跳出来一个关卡数据获取成功的提示，但并没有获取成功，主界面没有活动关卡。
不是网络的问题，我不知道是什么情况，除了maa其他时候网络都是正常的。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12619424/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12619426/gui.log)

**Comment by HertsLeon** [comment]
人呢。。

**Comment by HertsLeon** [comment]
人呢？

**Comment by Rbqwow** [comment]
因为.net8 maa已经放弃win7支持 抱歉啦
