### ISSUE TITLE
更新后仍无法识别本次活动货币

### ISSUE THREAD

**Issue by sevennamesia** [MaaAssistantArknights/MaaAssistantArknights#6382]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

版本号v4.23.3
更新时文档显示已更新此次识别，但现在仍显示unknown

### 日志文件

看不到提示中具体的文件夹和文件指示，因此没有上传

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/117713731/52d50757-1cc1-4f7f-979c-5530b849e065)

**Comment by ABA2396** [comment]
还没推到正式版，现在只有公测版和内测版有

**Comment by Constrat** [comment]
![Screenshot_20230915-173410__01](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/14c23229-7182-40a3-9aa7-a1c98f84b2f0)
