### ISSUE TITLE
建议修改宿舍“补满空位”功能的逻辑

### ISSUE THREAD

**Issue by cjyfs** [MaaAssistantArknights/MaaAssistantArknights#6383]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

假设其他干员全为满心情满信赖状态，在自定义排班表中指定杜林在2号宿舍，2、3号宿舍需要“补满空位”，那么maa在补满3号宿舍时，会将杜林从2号宿舍换至3号宿舍导致2号宿舍出现空位

### 有什么好的想法？

建议将“补满宿舍”的逻辑优先级调整为心情未满干员→信赖未满干员→不在任何设施（包括宿舍）内的其他干员

**Comment by MistEO** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/fa566e22-93e9-4c2e-aa94-2f3076415080)

这个勾上试试

**Comment by cjyfs** [comment]
> ![image](https://user-images.githubusercontent.com/18511905/268575745-fa566e22-93e9-4c2e-aa94-2f3076415080.png)
> 
> 这个勾上试试

我担心这个选项会和菲亚梅塔冲突

**Comment by MistEO** [comment]
这个自适用于自动填充（和非自定义基建），对指定的人没影响

**Comment by cjyfs** [comment]
> 这个只适用于自动填充（和非自定义基建），对指定的人没影响

好的我试一下，谢谢
