### ISSUE TITLE
MAA无法启动

### ISSUE THREAD

**Issue by woui003woui** [MaaAssistantArknights/MaaAssistantArknights#6386]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启动模拟器后打开MAA，弹出错误窗口且MAA本体无法运行
此前MAA运行正常

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12629498/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12629499/gui.log)

### 截图

![9(BOPV(MW}}$8QNKBI RBN](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/60837515/bf5b4ffc-504d-4a8d-83f0-092738fd7009)

### 还有别的吗？

WIN10系统、蓝叠国际版模拟器

**Comment by woui003woui** [comment]
补充，重新下载4.23.3版本（windows-x64）后替换安装，可以正常启动
自动更新4.23.4版本客户端后再次出现同样的报错，关闭自动更新MAA可正常运行

**Comment by SherkeyXD** [comment]
Duplicate of #6373
