### ISSUE TITLE
使用定时启动时无法正常启动模拟器

### ISSUE THREAD

**Issue by hijack114514** [MaaAssistantArknights/MaaAssistantArknights#6387]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

不知道是bug还是特性，MAA只有在刚打开时才能开启模拟器，如果不是bug，希望可以加上这个功能

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12631400/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12631427/gui.log)

**Comment by ABA2396** [comment]
设置里有连接失败重启模拟器

**Comment by hijack114514** [comment]
好的，谢谢

**Comment by hijack114514** [comment]
好的，谢谢
