### ISSUE TITLE
战斗完成后卡在覆潮之下页面了

### ISSUE THREAD

**Issue by xinlingheidong** [MaaAssistantArknights/MaaAssistantArknights#639]
如图
![image](https://user-images.githubusercontent.com/94310025/171115871-6d919e0a-e3b4-4356-9f04-deb9e6631235.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8802979/asst.log)
蓝叠模拟器

**Comment by MistEO** [comment]
新版本已经修复了，更新一下吧~
