### ISSUE TITLE
无法打开MAA

### ISSUE THREAD

**Issue by flytiny** [MaaAssistantArknights/MaaAssistantArknights#6390]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开MAA会有报错， 重装之后ok了，但是过了两天问题又出现了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12639718/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12639719/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6790396/717883c4-3a5b-462f-9fe7-d8e094c76ea6)

### 还有别的吗？

win10

**Comment by ABA2396** [comment]
f2d37627f1edc45a2a885980413eae5b955d7634 fixed
正式版还没有推送更新，现在是在更新的时候关闭maa的话会遇到这个问题。

**Comment by GrainRR** [comment]
我也是我也是
我每次更新完成后自动重启MAA就这样

**Comment by SherkeyXD** [comment]
#6373
