### ISSUE TITLE
麒麟X夜刀改名之后，基建换班无法识别

### ISSUE THREAD

**Issue by brusselss** [MaaAssistantArknights/MaaAssistantArknights#6392]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我是第一次反馈问题，可能问题描述的不是很好，请谅解（擦汗）
我最近新练了一批干员，然后从新定了排班表，但是新的排班表进驻夜刀总是失败（maa翻半天，就是无法选中，然后她就在那里，并且不报错），我又用了之前的基建排班表，结果夜刀进驻成功了，但其他干员总是进驻失败，（而且我没法提高我的基建收益了）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12639912/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12639913/gui.log)

**Comment by ABA2396** [comment]
改名之后配置表也改了吗？maa现在要更新到公测版才能之别r夜刀

**Comment by brusselss** [comment]
> 改名之后配置表也改了吗？maa现在要更新到公测版才能识别R夜刀
是排班表上的角色名称显示吗?新版的名字变了。我一直在用稳定版，我现在就去试试

**Comment by brusselss** [comment]
谢谢你，已经可以了

**Comment by brusselss** [comment]
啊啊，那个，公测版是不是有选中干员不进驻的bug啊，我这里出现了这种情况...（我这种只会给人添麻烦的人还是去死吧...）

**Comment by status102** [comment]
> 啊啊，那个，公测版是不是有选中干员不进驻的bug啊，我这里出现了这种情况...（我这种只会给人添麻烦的人还是去死吧...）

看看是不是#6378 或者 #6133 这种，如果没有类似issue的话可以试着填一个。没有用户出来反馈问题，不少bug注意不到的

**Comment by brusselss** [comment]
> > 啊啊，那个，公测版是不是有选中干员不进驻的bug啊，我这里出现了这种情况...（我这种只会给人添麻烦的人还是去死吧...）
> 
> 看看是不是#[6378 或者 #6133](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6378) 这种，如果没有类似issue的话可以试着填一个。 没有用户出来反馈问题，不少bug注意不到的

和#6133相似，而且是概率触发，我每个宿舍都放了一个固定干员，一般是第3，4宿舍会出现问题（现在的解决方案是把固定进驻干员放一起，然后不点填充空位，不会出错）

**Comment by brusselss** [comment]
但是如果固定干员事先未进驻的话还是会出错，我把干员放出来后从新试了下，现在又卡死了（悲）

**Comment by brusselss** [comment]
> 但是如果固定干员事先未进驻的话还是会出错，我把干员放出来后从新试了下，现在又卡死了（悲）

对不起！对不起！我看错了，我又从新检查了一下我的排班表，出问题的原因就是因为固定部分干员和填充空位，只固定干员然后啥都不点是不会出错的，真的非常抱歉
