### ISSUE TITLE
Anticheat suggestions; humanlike simulation, Add input delay / random interact within area,  "item viewing"

### ISSUE THREAD

**Issue by nullBroken** [MaaAssistantArknights/MaaAssistantArknights#6393]
### Before raising the issue...

- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I'm probably sure this is a new feature/suggestion and not a bug encountered (please attach logs if you're not sure)

### The problems you have encountered?

Please add a way to have the interactions delayed randomly to simulate humanlike behavior ; and when clicking a menu, have it select within an area randomly to perform the action. 
Adding a simulated form of inaccuracy to clicking within a Start box (to initiate a stage) would make detection harder.

"item viewing" in the title refers to the commonly done chain of "Operator -> Promotion -> clicking on the item needed for promotion", or "Base -> Workshop -> Item -> Clicking item to complete the item"; to 'look' at how many would need.
This simulates what a real person would do possibly. 
I would like it to perform this as a pause doing a few reclears of a stage; randomly.

With the recent announcement of "noticing been using 3rd party" announcement on their twitter
https://twitter.com/ArknightsEN/status/1702577992021733397
I believe some form of anti cheat may be helpful ; and these are my suggestions.

**Comment by Constrat** [comment]
The EN twitter account is famous for releasing every 6 months that bullshit message that says in-game data modifications won't be tolerated.
I've been using MAA in multiple accounts and nothing ever happened. 
As for your points: random interaction is already implemented. MAA will chose a rectangle area in which it can click. It won't click in the same area twice.
As for adding random timeouts, Arknights works server-side so there will always be random timeouts in-between.
