### ISSUE TITLE
选人界面塞雷娅识别有问题

### ISSUE THREAD

**Issue by Nothing1031** [MaaAssistantArknights/MaaAssistantArknights#6395]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用的公测版本v4.24.0，作战选人界面一直识别不到塞雷娅，看日志好像是识别结果的塞雷娅名字前面多了一个c，和作业没对上（没自己编辑过作业 ，不确定，猜的）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12640795/asst.log)

**Comment by SherkeyXD** [comment]
是不是加了特别关注

**Comment by Nothing1031** [comment]
> 是不是加了特别关注

确实是加了特别关注。这个也会影响识别吗？很奇怪，就是有几关作业能正常选到塞雷娅，日志里识别结果的名字不带c
