### ISSUE TITLE
【台服】MAA操作時亂點

### ISSUE THREAD

**Issue by ethan940726** [MaaAssistantArknights/MaaAssistantArknights#6397]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我是台服的玩家，平常電腦內就有3套的模擬器+MAA分別配對。台服更新敘拉古人以後突然有其中一組出現了問題，MAA啟動之後只會不斷點擊模擬器左下角之位置，不會執行程序。
我已嘗試過自行排解，adb確認連接沒有問題，硬體效能也完全足夠，也已經更新到最新版本。同時也看過"常見問題-連接正常，但是無操作"與"連接正常，但是操作卡頓、異常或頻繁出錯"並根據步驟重新設定過，但依然無法解決，想請問這是甚麼問題呢?
(出現異常前並沒有更改任何設定，之前也未出現過此問題。同時，另二模擬器(台服)依舊能正常運行)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12640899/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12640900/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71484388/e813b35d-aceb-4da8-8c18-ff0665e642b4)
abd設定狀態

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71484388/75932ded-5449-48ae-a9d2-132cd37ba222)
MAA與模擬器運行時狀況

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71484388/ac558a75-c7c5-48be-bb37-af0e66aaf9c4)
點擊位置

**Comment by ABA2396** [comment]
@MistEO 瞅瞅是不是传进去的图反了

**Comment by MistEO** [comment]
看看模拟器显示设置里，分辨率设置选的是不是“平板版”，不确定是不是这个原因。另外也可以试试触控模式改成 maatouch 和 adb input 有没有用

**Comment by ethan940726** [comment]
> 看看模拟器显示设置里，分辨率设置选的是不是“平板版”，不确定是不是这个原因。另外也可以试试触控模式改成 maatouch 和 adb input 有没有用

檢查過了，模擬器設置為1920*1080為手機版比例。兩種觸控模式都嘗試過，但還是沒有用。

**Comment by MistEO** [comment]
选“平板版”试试

**Comment by ethan940726** [comment]
> 选“平板版”试试

謝謝，解決了
