### ISSUE TITLE
自动肉鸽优化后不拿藏品了，这好吗，这不好

### ISSUE THREAD

**Issue by KuiPer-LTW** [MaaAssistantArknights/MaaAssistantArknights#6398]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

之前还能顺路刷刷收藏品的，我坎诺特印记就是刷源石锭的时候给我刷出来的

### 有什么好的想法？

不拿人很好理解，掉落的藏品拿一下不过分吧，我之前水月肉鸽的时候就提过能不能识别一下指路鳞，后来肉鸽要完结了，我也刷到了这个功能终于有了，那能不能拓展一下，输入藏品名，进入商店后看到了优先购买，没看到刷新商店，然后再存钱呢

### 其他内容

顺便问问MAA打算做森空岛自动签到吗，是不打算做还是正在做还是之后会做？

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantSkland 已经有了，群里的佬写的

**Comment by SherkeyXD** [comment]
要刷收藏品建议用刷等级模式

刷源石锭模式就是为了刷源石锭的
