### ISSUE TITLE
无公招许可时，报告识别错误

### ISSUE THREAD

**Issue by CainXCain** [MaaAssistantArknights/MaaAssistantArknights#6399]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

白票用完了每次公招都报错一次，提醒和提示音挺烦的
加个识别无白票不作为错误的处理（另外希望无白票时也会使用刷新次数刷掉3星，避免刷新次数攒满）

### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12641227/asst.-.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74123674/90303937-370d-4c73-bbbc-b52331116bca)

**Comment by GrainRR** [comment]
这倒无所谓吧，不想听到“叮咚”一声的话可以关闭提示的

**Comment by ABA2396** [comment]
没票子还要招募报错不是挺合理的吗）

**Comment by CainXCain** [comment]
> 没票子还要招募报错不是挺合理的吗）

不太能觉得合理，每日8招必然消耗完白票，然后天天报错，难到每次看省几个白票改设置的次数吗？

（两个问题）写个开关的话给不给合并

**Comment by broken-paint** [comment]
fixed by v4.25.0
