### ISSUE TITLE
使用带有processing字段的基建配置后，MAA闪退

### ISSUE THREAD

**Issue by GodotR** [MaaAssistantArknights/MaaAssistantArknights#6400]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我尝试在原有基建配置中加入processing字段相关内容
经过json校验后，MAA能够正常读取，并正常开始进行基建换班操作
但是进行至加工站时，模拟器打开了加工站界面后，MAA闪退

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12641573/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12641575/gui.log)
bug出现时间：2023-09-17 05:02:04.133

### 还有别的吗？

模拟器：蓝叠国际版 5.10.230.1003 P64
操作系统：win10专业版 22H2
也许MAA被我存放在D:\Program Files\MAA下会有部分win系统权限问题？
尝试修改的基建配置json文件：(txt格式）
[json.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12641581/json.txt)

**Comment by GodotR** [comment]
值得一提的是，在另一台笔记本上，MAA使用更新processing字段后的配置文件没有出现崩溃问题，功能正常。因此该bug可能与我台式机的操作系统有关。

**Comment by MistEO** [comment]
从日志看，你是不是用了自动填充之类的，没写加工站干员名，加工站不支持自动填充（
