### ISSUE TITLE
运行MAA时出现未知错误

### ISSUE THREAD

**Issue by EvelynSdy** [MaaAssistantArknights/MaaAssistantArknights#6406]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

运行MAA会和电脑起冲突，联想电脑管家会提示有可疑程序，点击信任后会弹窗说存在不支持的16位应用程序，这是什么原因呢？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642008/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642009/gui.log)

### 截图

<img width="354" alt="屏幕截图 2023-09-17 101529" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/116476485/68f913d7-8648-4acf-b6ff-e5bec340e600">
<img width="273" alt="屏幕截图 2023-09-17 113247" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/116476485/5c733a4f-32d2-4e3c-9cd7-28d69a8b8f2e">

### 还有别的吗？

无

**Comment by ABA2396** [comment]
没看懂，看日志不是11点跑起来了吗

**Comment by EvelynSdy** [comment]
maa是可以运行，但电脑会一直出现不支持的16位应用程序那个弹窗，只要运行maa就会不停的弹出那个弹窗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月17日(星期天) 下午3:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 运行MAA时出现未知错误 (Issue #6406)





 
没看懂，看日志不是11点跑起来了吗

**Comment by SherkeyXD** [comment]
这似乎不是 maa 的问题

建议检查一下你的电脑是不是中毒了什么的

**Comment by EvelynSdy** [comment]
好像确实是这样..把电脑上的风灵月影卸了问题似乎就解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月17日(星期天) 下午3:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 运行MAA时出现未知错误 (Issue #6406)





 
这似乎不是 maa 的问题
 
建议检查一下你的电脑是不是中毒了什么的
