### ISSUE TITLE
自动战斗队列缓存文件错误

### ISSUE THREAD

**Issue by XonlookerX** [MaaAssistantArknights/MaaAssistantArknights#6407]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

1.正常使用队列功能，如图添加了EX-7、8和突袭4关
2.正常自动打完了EX7的两关之后，7的队列已自动取消勾选
3.想开始打EX8，但此时点开始会继续从一开始队列的顶部开始读取而不是现勾选的队列（如图右侧）

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642011/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642012/asst.log)

2023.9.17，11:25-11:35之间

### 截图

![I0K8J A Z1~1U063)E70RQ](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61648955/3a099aad-3acf-4dd4-b34b-47e6f32c02cd)

### 还有别的吗？

蓝叠国际版，Win10

**Comment by status102** [comment]
检查一下cache/copilot/CV-EX-8.json的修改时间，然后上传一下内容

**Comment by XonlookerX** [comment]
> 检查一下cache/copilot/CV-EX-8.json的修改时间
> 
> 如果在发生issue所述问题之后没有再添加cv-ex-8到任务列表的话，上传一下上面那个文件

不是只发生在EX-8，这只是个举例，任意不同的关卡都会出现这个情况，至少我从EX-5打到8一直是这样

**Comment by status102** [comment]
> 不是只发生在EX-8，这只是个举例，任意不同的关卡都会出现这个情况，至少我从EX-5打到8一直是这样

先截图一下copilot文件夹，然后上传一下EX-8的文件

数据不全没法分析

**Comment by XonlookerX** [comment]
![SXLSMVHLJAO$5I R`834NZP](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61648955/23ca229f-38dd-41aa-be74-dbb5edff911a)
[copilot.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642119/copilot.zip)

**Comment by status102** [comment]
> ![SXLSMVHLJAO$5I R`834NZP](https://user-images.githubusercontent.com/61648955/268484174-23ca229f-38dd-41aa-be74-dbb5edff911a.png) [copilot.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642119/copilot.zip)

感谢，目前已经查到导航有点问题，然后关卡错误是缓存的作业文件错了，原因不明

**Comment by status102** [comment]
可能存在文件读写问题。CV-6、CV-7、CV-8的文件内容均为上一个关卡的（分别为CV-5、CV-6、CV-7），且修改时间存在疑点
