### ISSUE TITLE
日服生息演算关卡撤退失败

### ISSUE THREAD

**Issue by delishalita** [MaaAssistantArknights/MaaAssistantArknights#6408]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

与网络连接中断无关，该bug出现两三回，具体为点击进入采集关卡后点击撤退然后就卡在提示是否撤退的界面，手动撤退后不管还有几天一律为退出此次行动、开始下一次行动。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642055/gui.log)
asst.log原文件和rar文件无法上传，都是拖拽、uploading一闪而过
[asst (2).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642065/asst.2.zip)

问题出现时间点
2023-09-16 16:35:14.607] <1><> 已开始行动 24 次
2023-09-16 22:48:47.093] <1><> 已开始行动 1 次
[2023-09-17 00:52:06.554] <1><> 已开始行动 34 次

**Comment by haaddii** [comment]
你的能动吗？我这边连接的是Mumu12，连进都不会进去，卡在配队的那个界面。
