### ISSUE TITLE
建议添加萨米肉鸽策略“凹密文板 在生活至上分队开局获得特定密文板” 

### ISSUE THREAD

**Issue by iTheCreep** [MaaAssistantArknights/MaaAssistantArknights#6409]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

动机是，我一直希望玩一把憧憬（绿色下板，此处获得的源石锭翻倍）+北地巫师竞技（兴致盎然，付出源石锭抽取奖励）开局的爽局（如果能双憧憬甚至可以电表倒转），并且达成在北地巫师竞技连输五次的经历。

手刷了50+轮，憧憬一次没有；固定点击脚本刷了200+轮，刷到了两次（用肉眼看到憧憬后停止脚本开打），这两次都遇上了北地巫师竞技，但是都没有能激活憧憬的上板，很难受。

我希望能有一个含有图像识别的脚本帮助我在生活至上分队开局凹特定密文板，让我也不用在脚本运行时一直盯着。

### 有什么好的想法？

“等科考队重建”和“选择特定分队”都是MAA已经有的功能。

在识别上只需要添加：“识别选择生活至上分队后的符文板”的功能。

在逻辑上需要添加：如“包含希望获得的符文板”（可以用一个“与或”的字符串表达用户愿望），则停留在选择分队界面即可；否则左上角退出重开。

### 其他内容

密文板的截图或许只能通过重复刷取生活至上分队开局后的弹出消息框才能获得，手刷不易。

**Comment by Rbqwow** [comment]
策略选择刷开局 分队选生活至上 高级设置里就会有凹密文板了

~~忘了什么时候加的了~~
