### ISSUE TITLE
更新v.3.9.0-beta.8后链接夜神需要手动选择adb路径无法自动启动

### ISSUE THREAD

**Issue by WhiteKame** [MaaAssistantArknights/MaaAssistantArknights#641]
![image](https://user-images.githubusercontent.com/46062213/171120819-d334a9aa-0059-43df-ad72-b3754d68bbd6.png)
如图所示，今天从v3.3.2更新到v3.9.0-beta.8后无法链接原本自动链接的夜神模拟器，显示需要设置adb路径

**log文件**
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8803169/asst.log)

**Comment by MistEO** [comment]
请参考更新说明  
> 从 v3.3.2 更新上来之后，第一次启动请使用管理员打开，或自己在连接设置中选择 adb 路径~

及常见问题文档：[adb 路径怎么填写](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#%E8%BF%9E%E6%8E%A5%E9%94%99%E8%AF%AF%E4%B8%8D%E7%9F%A5%E9%81%93-adb-%E8%B7%AF%E5%BE%84%E6%80%8E%E4%B9%88%E5%A1%AB%E5%86%99)
