### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by raging888** [MaaAssistantArknights/MaaAssistantArknights#6410]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

一共出现两个错误,都是更新4.24beta4之后出现的

### 日志文件

MAA 遇到了问题
未将对象引用设置到对象的实例。
解决方案
出现未知错误
详细信息
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 MaaWpfGui.Helper.ETagCache.Get(String url)
   在 MaaWpfGui.Models.ResourceUpdater.<UpdateFileWithETage>d__9.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 MaaWpfGui.Models.ResourceUpdater.<updateSingleFiles>d__6.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.Models.ResourceUpdater.<Update>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.<CheckAndDownloadUpdate>d__40.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.<ShowUpdateOrDownload>d__39.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

MAA 遇到了问题
OpenClipboard 失败 (异常来自 HRESULT:0x800401D0 (CLIPBRD_E_CANT_OPEN))
解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard 失败 (异常来自 HRESULT:0x800401D0 (CLIPBRD_E_CANT_OPEN))
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Windows.Clipboard.Flush()
   在 System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   在 MaaWpfGui.Views.UI.ErrorView.CopyToClipboard()
   在 MaaWpfGui.Views.UI.ErrorView.<CopyErrorMessage_Click>d__25.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642192/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642195/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143695189/e168fc6b-6d21-4d7c-b00c-7d9664a91710)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143695189/edbf5ab0-6136-49ec-b7a7-1f9660f5b7ff)

### 还有别的吗？

之前的beta2 3都用不了来着

**Comment by SherkeyXD** [comment]
删除 cache/etag.json 试试

**Comment by ABA2396** [comment]
没懂 @MistEO _cache = JsonConvert.DeserializeObject<Dictionary<string, string>>(jsonStr);之后 _cache 还能是 null 的吗

**Comment by SherkeyXD** [comment]
我之前 etag.json 为空的时候也触发这 bug 了

**Comment by MistEO** [comment]
> 没懂 @MistEO _cache = JsonConvert.DeserializeObject<Dictionary<string, string>>(jsonStr);之后 _cache 还能是 null 的吗

好像有可能，json 解析错误是不是就 null 了（？

**Comment by ABA2396** [comment]
> > 没懂 @MistEO _cache = JsonConvert.DeserializeObject<Dictionary<string, string>>(jsonStr);之后 _cache 还能是 null 的吗
> 
> 好像有可能，json 解析错误是不是就 null 了（？

解析错直接进catch了
