### ISSUE TITLE
多开蓝叠模拟器时MAA无法正常连接

### ISSUE THREAD

**Issue by hijack114514** [MaaAssistantArknights/MaaAssistantArknights#6415]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我多开了蓝叠模拟器，第二个MAA无法正常连接，而且两个MAA中开机自启动这个功能也有冲突

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642560/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642561/asst.log)

### 还有别的吗？

蓝叠多开
Window10

**Comment by MistEO** [comment]
日志被刷掉了，再操作一下重新发一下
