### ISSUE TITLE
打开maa报错了

### ISSUE THREAD

**Issue by cwaydhsndi** [MaaAssistantArknights/MaaAssistantArknights#6416]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开了一个windows提示的防护之后重启电脑就开始报错了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642563/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642564/gui.log)
2023.9.17 18:00之后大概

### 截图

MAA 遇到了问题
未将对象引用设置到对象的实例。
解决方案
出现未知错误
详细信息
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 MaaWpfGui.Helper.ETagCache.Get(String url)
   在 MaaWpfGui.Models.ResourceUpdater.<UpdateFileWithETage>d__9.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 MaaWpfGui.Models.ResourceUpdater.<updateSingleFiles>d__6.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.Models.ResourceUpdater.<Update>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.<CheckAndDownloadUpdate>d__40.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.<ShowUpdateOrDownload>d__39.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ABA2396** [comment]
先把 cache文件夹里的etag.json删了试试

**Comment by cwaydhsndi** [comment]
> 先把 cache文件夹里的etag.json删了试试

能用了，谢谢。
