### ISSUE TITLE
基建换班的干员编组 运行会莫名无法匹配所有分组

### ISSUE THREAD

**Issue by sunyink** [MaaAssistantArknights/MaaAssistantArknights#6417]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我自写了基建配置文件，参照排版协议，对贸易站1使用了干员编组功能，共2组。经测试，有时能正确运作，但另一些情况会**秒回一个全部编组无匹配**的情况；更气地是，故障班次重启maa后可能会变，导致排错难度好大。
一些观察发现，它这个全部编组无匹配的guilog结论是进入干员列表后秒回的，甚至都没扫一遍他就知道不匹配0.0？正常流程是全部干员扫一遍然后下结论匹配成功，再出一个最佳编组放上去。
下面我附上我的排班文件，并节选关键文段。排班目的是贸易站1 巫恋组自己判定裁缝B暖机是否需要替换（因为使用极端迷迭香后24心情能50h干活，我是2天共10班循环，最大化暖机无法固定个人写在班组里）
` 
{
	"plans":[
		{
			"groups":[
                {
                    "name":"巫恋1组",
                    "operators":[
                        "柏喙",
                        "巫恋",
                        "龙舌兰"
                    ]
                },
                {
                    "name":"巫恋2组",
                    "operators":[
                        "卡夫卡",
                        "巫恋",
                        "龙舌兰"
                    ]
                }
            ],
			"rooms":{
				"trading":[
					{
						"use_operator_groups":true,
						"product":"LMD",
						"operators":[
							"巫恋1组",
							"巫恋2组"
						],
						"sort":true,
						"autofill":false
					},
					{
						"product":"LMD",
						"operators":[
							"但书",
							"空弦",
							"黑键"
						],
						"sort":false,
						"autofill":false
					}
				],
 `

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12642737/debug.zip)
上传整个debug，特地删干净后再启动maa，把10个班组都跑了一遍。自定义配置的参数，每班都是复制第1班的，故完全一样（第1班正常运作）。但实操有些班次就是会无法匹配，据观察它甚至都不滚动干员列表，秒出无匹配所有编组的结论，然后按照固有逻辑随便放了几个上去。

**Comment by status102** [comment]
看上去两次匹配成功都是MAA开启后第一次，可能是缓存的数据没有被清除，但是又无法复现（
