### ISSUE TITLE
仅ADBInput一个触控模式可用

### ISSUE THREAD

**Issue by GrainRR** [MaaAssistantArknights/MaaAssistantArknights#6419]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用MAAtouch和minitouch都会出现点击连接后无任何反应且点击停止无反应的问题

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12643089/gui.log)

**Comment by GrainRR** [comment]
另一个日志文件怎么也无法上传啊，一定需要的话再告诉我一下吧

**Comment by MistEO** [comment]
把MAA关了再传，或者把日志复制一遍再传

**Comment by GrainRR** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12644007/asst.log)

**Comment by MistEO** [comment]
这份日志里啥都没有_(:з」∠)_你再运行一下再传呢

**Comment by GrainRR** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12656124/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12656125/asst.log)


> 这份日志里啥都没有_(:з」∠)_你再运行一下再传呢

**Comment by GrainRR** [comment]
> ```
> [2023-09-19 13:17:12.577][ERR][Px525c][Tx26dc] adb connect failed: connect: ����Ŀ�����������ܾ����޷����ӡ�
> [2023-09-19 13:17:12.577][WRN][Px525c][Tx26dc] adb-lite command: " E:\MuMu模拟器\MuMu12\MuMuPlayer-12.0\shell\adb.exe connect 127.0.0.1:16384 "run failed
> [2023-09-19 13:17:12.577][WRN][Px525c][Tx26dc] fallback to NativeIO
> ```

目前有解决进度了吗

**Comment by MistEO** [comment]
关掉 adb-lite 试试？这个功能在 Windows 上支持的不是很好

**Comment by GrainRR** [comment]
> 关掉 adb-lite 试试？这个功能在 Windows 上支持的不是很好

adb-lite关闭会影响什么
我关闭后确实MAAtouch可用了，但是连接速度慢了很多

**Comment by Constrat** [comment]
Adb-lite is experimental => it can have issues.
Maatouch is also highly experimental.
I suggest using normal adb and minitouch.

What do you mean by slow connection speed? Do you mean the first connection to the emulator?

**Comment by Constrat** [comment]
But no one said to use ADB input. Actually it's not suggested, it's deprecated technology.

**Comment by GrainRR** [comment]
> But no one said to use ADB input. Actually it's not suggested, it's deprecated technology.

所以我一直在设法换用其他的连接方式
这个issue应该结束了
