### ISSUE TITLE
日服信用点购物优先购买识别不到白票

### ISSUE THREAD

**Issue by Zzzzzzzyk** [MaaAssistantArknights/MaaAssistantArknights#6425]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

rt

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12643977/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12643978/gui.log)
时间点：2023-09-18 07:42:09.732

### 截图

![MuMu12-20230918-080703](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/69119281/3f41e488-ded1-4528-8360-230bd2563bb8)
![QQ截图20230918080749](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/69119281/82fe2b74-b8d8-4371-a5ec-70187feaed48)

**Comment by zzyyyl** [comment]
有没有可能你应该输入：`求人票`

**Comment by Constrat** [comment]
> Maybe you should type:`求人票`

Just whitelist the Recruitment Voucher (`求人票`) in the list. It will always buy them first even if they are not discounted. Efficiency-wise it's always better to buy every recruit possible, than all the other items starting from the discounted ones.

**Comment by Zzzzzzzyk** [comment]
> 也许你应该输入：`求人票`
好的，我以为跟肉鸽里借助战一样做了不同语言的适配来着就没考虑这个原因。
