### ISSUE TITLE
定时执行有概率全部任务报错跳过

### ISSUE THREAD

**Issue by HS7097** [MaaAssistantArknights/MaaAssistantArknights#6427]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

定时执行错误发生在今日6时

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12644079/asst.zip)

**Comment by ABA2396** [comment]
连接设置里的adb连接失败重启模拟器开了吗？这些都是ui做的，发gui.log

**Comment by HS7097** [comment]
> 连接设置里的adb连接失败重启模拟器开了吗？这些都是ui做的，发gui.log

好的，我以为这个是检测到模拟器没启动自己会再去启动的

**Comment by HS7097** [comment]
现在好像怎么都连不上
检查了端口和代理，都没写错
