### ISSUE TITLE
建议修改无法刷取无掉落关卡的设定

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#6429]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有时候需要不花理智地完成“消灭1000敌人”的周任务，来帮助在周一获得大体力药，因为有的活动在周二凌晨结束

**Comment by status102** [comment]
现在自动战斗有战斗列表，试试用这个？

**Comment by zzyyyl** [comment]
现在屏蔽的就只有：`-EX`, `-S`, `-MO`, `OF-1`，其它应该能刷吧）

**Comment by ABA2396** [comment]
除了of-1其他of都行）
