### ISSUE TITLE
开始唤醒的“账号切换”功能添加多个账号选择，并附近快捷“切换登录”按钮

### ISSUE THREAD

**Issue by TangZH-unity3d** [MaaAssistantArknights/MaaAssistantArknights#6431]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前切换账号确实是一个很好的功能，但是无法保存多个账号，只能使用配置切换，也无法快捷切换别的账号

### 有什么好的想法？

1.将“账号切换”做成类似配置一样，可以自己下拉选择其他账号ID
2.并附加“切换登录”按钮，快捷切换为当前选择的账号

**Comment by status102** [comment]
关于第二条：MAA不会记录当前登录了哪个账号，所以就算快捷切了，开始唤醒执行的时候还是会切

**Comment by TangZH-unity3d** [comment]
> 关于第二条：MAA不会记录当前登录了哪个账号，所以就算快捷切了，开始唤醒执行的时候还是会切

我的意思是，当前我登录着账号1，想通过MAA可以直接切换为账号2
或者不管我当前登录着哪个，我选择账号2，并点“切换登录”，
1.判定是否在游戏内，如果没有唤醒游戏，单独走“开始唤醒”功能的流程，唤醒并切换账号
2.在游戏内切换成账号2

**Comment by status102** [comment]
第二条等会写，第一条的话，配置可以通过启动参数来切换，感觉不太有需求

**Comment by TangZH-unity3d** [comment]
> 第二条等会写，第一条的话，配置可以通过启动参数来切换，感觉不太有需求
非常感谢您的付出。
因为我是经常会切换两个账号来操作的人，如果没有下拉选择，只有第二条的话，每次想切换朋友的账号，都需要去复制账号id，再来点“切换账号”
有下拉选择，对于有登录多个账号的人应该更为方便
当然这条可以放久一点，或许等有比较多跟我一样需求的人，再做不迟。

**Comment by status102** [comment]
第一条等久一点吧，还有一个办法就是，因为切换是查找而不是匹配，可以考虑输入你朋友账号中独有的一部分来作为切换目标

**Comment by TangZH-unity3d** [comment]
> 第一条等久一点吧，还有一个办法就是，因为切换是查找而不是匹配，可以考虑输入你朋友账号中独有的一部分来作为切换目标

谢谢你，刚刚试了，确实很有用，没想到是查找   )：

**Comment by status102** [comment]
刚去看了眼，可能后来我写提示文本的时候写漏了（

**Comment by status102** [comment]
因为有些时候总会带点奇奇怪怪的字符进来，干脆就查找了

**Comment by TangZH-unity3d** [comment]
> 刚去看了眼，可能后来我写提示文本的时候写漏了（

说明已经蛮详细了，一般写说明，也不会把文本匹配方法写在说明书的，hhh

**Comment by status102** [comment]
> 说明已经蛮详细了，一般写说明，也不会把文本匹配方法写在说明书的，hhh

又去看了眼，[文档](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/1.1-%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md#%E5%88%87%E6%8D%A2%E8%B4%A6%E5%8F%B7)里写了
