### ISSUE TITLE
maa打开后意外崩溃

### ISSUE THREAD

**Issue by pavocritatus** [MaaAssistantArknights/MaaAssistantArknights#6432]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

弹出一个窗口：maa遇到了问题，未将对象引用设置到对象的实例。然后关闭这个的话maa随之关闭。

### 日志文件

MAA 遇到了问题
未将对象引用设置到对象的实例。
解决方案
出现未知错误
详细信息
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 MaaWpfGui.Helper.ETagCache.Get(String url)
   在 MaaWpfGui.Models.ResourceUpdater.<UpdateFileWithETage>d__9.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 MaaWpfGui.Models.ResourceUpdater.<updateSingleFiles>d__6.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.Models.ResourceUpdater.<Update>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.<CheckAndDownloadUpdate>d__40.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.<ShowUpdateOrDownload>d__39.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106642957/ad574b9d-3f4e-4152-b8a1-3767d55820dc)

### 还有别的吗？

mumu模拟器，win11

**Comment by ABA2396** [comment]
把 cache/etag.json 删了

**Comment by Constrat** [comment]
> 解决了，感谢

**Comment by Andy23333** [comment]
解决了，感谢
