### ISSUE TITLE
双开时完成任务后关闭了错误的模拟器

### ISSUE THREAD

**Issue by MejiroSilence** [MaaAssistantArknights/MaaAssistantArknights#6437]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用蓝叠国际版进行双开，一个官服一个日服。选择任务完成后关闭MAA以及模拟器，官服的先完成任务后，官服的MAA和日服的蓝叠被关了，留下日服的MAA和官服的蓝叠。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12654053/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12654054/gui.log)

**Comment by ABA2396** [comment]
通过端口关失败了，就按照进程名关了个。蓝叠的端口填127.0.0.1:5555这种形式，别写emulator-5554

**Comment by MejiroSilence** [comment]
> 通过端口关失败了，就按照进程名关了个。蓝叠的端口填127.0.0.1:5555这种形式，别写emulator-5554

没手动写过这个，因为蓝叠端口会变，而且我还是双开，都是指定Bluestacks.Config.Keyword，然后自动检测的

**Comment by ABA2396** [comment]
我手头没有hyperv的蓝叠，先改个有多个蓝叠的情况下要是通过端口关失败就报个错先先不关，等别人来看看什么情况
