### ISSUE TITLE
保全派驻部分任务提示 Recognition error or JSON does not support this 报错退出

### ISSUE THREAD

**Issue by 12dora** [MaaAssistantArknights/MaaAssistantArknights#6439]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

保全派驻自动站斗, 选择部分作业开始时提示Recognition error or JSON does not support this, 并退出. 部分作业可以正常执行, 部分作业无法执行, 更新 MAA 版本后原可以执行的也有概率报错, 报错原因不明
开始任务：SSSCopilot.
Recognition error or JSON does not support this.
完成任务：SSSCopilot

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12655602/asst.log)
debug 文件夹内未找到gui.log

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/11296313/3d5a91ff-ecee-457a-b9b7-e39ed5cb3836)
例如SSS_荒废灯塔_浊蒂纯艾版.json在该界面点击开始自动战斗, 即报上述错误退出

### 还有别的吗？

Android Studio自带模拟器
MacOS 13.5
MAA v4.24.0-beta.4（403）=> 旧版也有该问题

**Comment by 12dora** [comment]
截图上传出了问题, 重传一次
<img width="500" alt="WeChatd48463afacaa6b262632134e163e700e" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/11296313/48417904-f992-4458-9be8-367f40c07597">

**Comment by sake23** [comment]
遇到了同样的问题，我也是macos，用的网易mumu 1.9.57，maa版本v4.26.0-beta.2（421）

**Comment by status102** [comment]
```
[2023-09-19 11:26:35.281][INF][Px1646][Txa66d] append_task SSSCopilot {"enable":true,"filename":"/Applications/MAA.app/Contents/Resources/resource/copilot/SSS_保全阿尔斯特甜品制作平台-澄闪铃兰核v1.3（不兼容应急）.json","loop_times":1}
```
看上去是选择了错误的作业，可能是鼠标经过下拉框的时候错误触发了滚轮
