### ISSUE TITLE
希望加入若当前选择不可刷，则改为刷1-7的功能

### ISSUE THREAD

**Issue by MouseWhite** [MaaAssistantArknights/MaaAssistantArknights#644]
用定时启动任务的时候，由于很多时候关卡未开放或者其他原因，刷理智战斗失败，希望能够加入一个若当前关卡战斗失败，则刷指定常驻关卡（如1-7和资源本）的功能，多谢玛丽

**Comment by hjhjfhjhujhh** [comment]
你如果用脚本的话，日常任务里上次作战后面加一个刷1-7就行了，如果上次作战打完了程序在打1-7的时候会识别理智耗尽然后执行下一项任务
不过，你有没有想过，你打一次1-7之后，你的上次作战就变成1-7了？

**Comment by ABA2396** [comment]
新版本添加了备选关卡，可以在设置里选择是否使用
