### ISSUE TITLE
增加自定义基建配置中龙舌兰组的无人机检测规则

### ISSUE THREAD

**Issue by MuLingMing** [MaaAssistantArknights/MaaAssistantArknights#6441]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

MAA启动设置为一天两次，间隔12小时；
[24-24*(1-0.1-0.25)]/24=0.35,36*0.65=23.4,
[24-24*(1-0.25)]/24=0.25,36*0.75=27,
设为25-35%的心情阈值则可以让一般情况下的制造站、贸易站工作36小时再休息，其余设施工作24小时再休息

而一些有+0.5心情消耗的干员就会出现破坏该轮换循环的情况，例如斥罪
斥罪+45%的效率会使她在基建中具有高优先级，但是同时会有+0.5心情的debuff
[24-12*(1+0.5-0.25)]/24=0.375,0.375>0.35
就会导致斥罪不能按照设定的25-35%心情阈值进行提前休息，而是会继续工作然后红温

所以我希望可以将斥罪加入黑名单，排班时将斥罪的优先级下降或者不录用

### 有什么好的想法？

增加一个基建干员黑名单的功能，在名单上的干员优先级下降n个等级或者永不录用

**Comment by MuLingMing** [comment]
主要还是因为基建排班方案不支持两天为单位的排班方案

**Comment by MuLingMing** [comment]
中枢配置为5异格永续，所以最大休息数为19

**Comment by zzyyyl** [comment]
试试自定义基建？

**Comment by MuLingMing** [comment]
自定义基建的话，不支持两天为单位的基建排班

**Comment by MuLingMing** [comment]
刚刚尝试自己修改了json文件，将斥罪"法为正典"的优先级下调了5，大概可以满足我的需求了，就是不知道下次更新会不会还需要再次修改

**Comment by Constrat** [comment]
Unless there are major changes in the infrastructure json parser (which aren't happening, for now) nothing should happen.
You should only keep YOUR custom json updated to the latest operators, if you have them, to keep the base efficient.

**Comment by ABA2396** [comment]
自定义基建的话，你要是不写时间字段就是换完一次自动切下一班，想写几天都是可以的）

**Comment by MuLingMing** [comment]
![IMG](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114294439/fd56a0a7-878c-454e-b96f-b031b24a3a30)
如果自己排班的话就会太久，而将消耗额外心情的基建技能优先级再下调一级（即5，原先为0.1，该种技能的性价比不一定高但对排班心情阈值杀伤力巨大），即可达到同样的效果，将36小时（制造站、贸易站）和24小时（其他设施）的组区分开（即心情阈值设为25-35%）。
所以我建议将额外消耗心情的基建技能优先度再下调一级，或者增加一个优先度下调的选择项（可以用两种不同json文件来简单实现，内容仅特定基建技能的优先度不同），或者增添一个搜索json中技能名并调低优先度的名单（即搜索json文件中的技能名，修改该技能名同一类型效果的优先度，（PS：我不确定MAA更新是否会直接替换json文件抑或是在本地文件基础上增加新的json内容））

**Comment by ABA2396** [comment]
出新干员之后的更新是会替换的。

**Comment by Shawnsdaddy** [comment]
> ![IMG](https://user-images.githubusercontent.com/114294439/269012661-fd56a0a7-878c-454e-b96f-b031b24a3a30.jpg) 如果自己排班的话就会太久，而将消耗额外心情的基建技能优先级再下调一级（即5，原先为0.1，该种技能的性价比不一定高但对排班心情阈值杀伤力巨大），即可达到同样的效果，将36小时（制造站、贸易站）和24小时（其他设施）的组区分开（即心情阈值设为25-35%）。 所以我建议将额外消耗心情的基建技能优先度再下调一级，或者增加一个优先度下调的选择项（可以用两种不同json文件来简单实现，内容仅特定基建技能的优先度不同），或者增添一个搜索json中技能名并调低优先度的名单（即搜索json文件中的技能名，修改该技能名同一类型效果的优先度，（PS：我不确定MAA更新是否会直接替换json文件抑或是在本地文件基础上增加新的json内容）） 目前我是通过直接修改infrast.json文件中的efficient.all来实现该需求

为啥不试试动态换班呢

**Comment by MuLingMing** [comment]
动态换班是哪个，在哪里，我去看一看尝试一下-------- 原始邮件 --------为啥不试试动态换班呢

**Comment by Constrat** [comment]
> 动态换班是哪个，在哪里，我去看一看尝试一下，我只看到了排班生成器和示例排班json文件 哦哦动态排班那个是不是那个“补全空位”的选项，这个的话也算是可行吧，大概也可以用，我去试试

With a custom infrastructure json, there is an option: `"autofill": true`. With this MAA will choose best operators (in dorm it will choose the lower morale first)

**Comment by MuLingMing** [comment]
我使用autofill之后可以变相实现我所需要的优先度的改变需求；
但是我这两天在使用自定义基建计划时又发现一个新的需求点，有关于贸易站的龙舌兰组的无人机问题；

在基础的基建配置中，配备了龙舌兰组的单独判定，即当前为龙舌兰组时，会直接使用无人机，即drones.order="pre"；当前不为龙舌兰组时，会换班后再使用无人机，即drones.order="post"；
在自定义基建配置中就只会根据drones的配置进行无人机的使用，哪怕我在drones配置中省略order，在rooms的配置中不写贸易站的配置，也会只按照drones中的默认order:"pre"来使用无人机，不会按照基础配置的龙舌兰组的检测来使用

所以我建议，如果可以的话，可以将drones.order默认设为post然后增加一个room="trading"的判定，检测当前是否是龙舌兰组，如果是则直接使用无人机；或者将基础配置中的龙舌兰组的检测机制直接加在drones里，即rule

**Comment by MuLingMing** [comment]
突然想到将无人机配置order设置成post也能实现这个功能，刚刚试了一下发现可以，那就结束了
