### ISSUE TITLE
每次结束任务后崩溃

### ISSUE THREAD

**Issue by yida12345** [MaaAssistantArknights/MaaAssistantArknights#6445]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

每次完成任务后窗口卡死，从右下角进入会报错，只能从任务管理器退出，应该是从之前一次报告文件缺失开始，那次文件缺失从新下的完整完整版覆盖修好的

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12662635/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12662637/gui.log)
2023-09-19 22:56

### 截图

![1695135762543](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111366962/8add1a50-aabf-40b9-8a0c-b282f57fc1e4)

### 还有别的吗？

如果在开始前运行脚本那里写mas的exe文件也会有类似的卡死

**Comment by VIPArcher** [comment]
尝试关闭外部通知试试

**Comment by zzyyyl** [comment]
- #6414 

`v4.24.0-beta.5` fixed
