### ISSUE TITLE
建议以出怪数量解决关卡卡轴不准确的功能建议

### ISSUE THREAD

**Issue by TeseVar** [MaaAssistantArknights/MaaAssistantArknights#6449]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前的关卡自动战斗JSON，存在各个玩家练度不均。导致出怪的时间长短不一。
所以现在以时间为单位的放置或者下干员，会提前放或者干员放的过晚。
导致关卡任务失败。

### 有什么好的想法？

建议能读取怪的数量，跟据怪的数量来选择下干员的时机
也可以跟据这个选项来释放技能
（该选项不是必填）

### 其他内容

暂无

**Comment by MistEO** [comment]
可以以 击杀数 / 费用变化 来判断的，这两个是比较准的

出怪数量识别难度太大
