### ISSUE TITLE
自动战斗开始前/结束后自动执行开始前/结束后脚本

### ISSUE THREAD

**Issue by LaviniaFalcone** [MaaAssistantArknights/MaaAssistantArknights#6450]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有时候我只是想执行指定关卡的自动战斗，但是这个行为不会触发执行开始前/结束后脚本。
我使用的是物理安卓设备，所以我需要在开始前执行
```shell
adb shell wm size 1080x1920
```
然后在结束后执行
```shell
adb shell wm size reset
```

### 有什么好的想法？

如果可以的话，请内置一个可选的分辨率调整开关。

**Comment by ABA2396** [comment]
那小工具里的那些是不是都要加一个）

**Comment by Rbqwow** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55343783/68e95a05-dfee-42fe-acb3-acda533e3886)
自动战斗倒是已经加了
