### ISSUE TITLE
刷水月肉鸽时总是停留在藏品界面无法识别与退出

### ISSUE THREAD

**Issue by Liren552** [MaaAssistantArknights/MaaAssistantArknights#6452]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa在刷肉鸽时经常性的打开藏品界面，在藏品较少无法铺满屏幕时可以识别与退出，在藏品较多铺满屏幕时无法识别与退出

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12669044/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12669045/gui.log)

### 截图

![MuMu12-20230920-134903](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71498704/82b5b159-4406-41c7-9d4b-dedfea17ad59)
![屏幕截图 2023-09-20 135035](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71498704/0b8c0661-aeda-4e76-a8fd-aac718582cf9)

**Comment by Lancarus** [comment]
duplicate of #5892
