### ISSUE TITLE
无奖励关卡建议手动开关“停止自动刷取”

### ISSUE THREAD

**Issue by 666ppp86** [MaaAssistantArknights/MaaAssistantArknights#6457]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在干员需要开模组的时候，由于模组的第一任务通常为要求干员部署次数/造成攻击量/开技能次数等可在任意关卡完成的简单任务，通常为了减少不必要的理智消耗，我大多在火蓝之心即OF-X关卡完成——这些关卡不需要理智，也对应没有任何奖励
但最近我在使用MAA刷这些关卡时发现MAA会认为这是无奖励掉落关卡从而停止继续运行

### 有什么好的想法？

希望能够在“刷理智”的高级设置中额外加入“允许刷无奖励关卡”，以便进行上述操作

**Comment by status102** [comment]
duplicate of #6429

**Comment by zzyyyl** [comment]
只有 OF-1 会被停止，OF-2 等不会（
