### ISSUE TITLE
Mac 萨米肉鸽不断选择待部署区的夜刀，但又不进行部署，导致效率低下

### ISSUE THREAD

**Issue by KyleChoy** [MaaAssistantArknights/MaaAssistantArknights#6461]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽，刷源石锭模式（配置如下图），道中如果抓到夜刀，会不断暂停选中夜刀，但是又不进行部署，无限循环导致对局大幅度延长。

![Snipaste_2023-09-20_21-22-27](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40708094/d1d70aa7-cb32-4413-87a1-c424ea23a141)

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12673481/asst.bak.log)
9月20日17:58左右

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40708094/c49d18c4-da9f-4db0-95fe-fcc49e734109

### 还有别的吗？

设备：MacBook Pro M2
系统：macOS 13.5.2
MAA：4.23.3
PlayCover：v3.0.0.maa.3

**Comment by Lancarus** [comment]
版本过旧

**Comment by ABA2396** [comment]
这玩意改名叫R夜刀了，原来是X夜刀，点开发现还是不认识
