### ISSUE TITLE
水月肉鸽，使用焰影苇草开局，选择焰影苇草后会卡在立绘位置

### ISSUE THREAD

**Issue by EnderOre** [MaaAssistantArknights/MaaAssistantArknights#6462]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

水月肉鸽，使用焰影苇草开局，选择焰影苇草后会卡在立绘位置。翻看识别图片，发现卡了两个小时左右，初步判定为无此图片无法选择
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66881284/26cfd0b9-c4d6-4214-9230-2031aac7ff43)

下为立绘
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66881284/0cc0e77f-1a14-41b1-a132-4792b59b046a)

下为MAA界面
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66881284/162e4592-6322-4a8c-b16a-8195f39d225d)

### 日志文件

文件太大，打包上传
[Desktop.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12674077/Desktop.zip)

### 截图

截图好像放问题描述里了。

### 还有别的吗？

使用的是蓝叠模拟器5国际版，Nougat64内核。MAA版本为v4.24.0-beta.4.d053.g9100a0041

**Comment by Lancarus** [comment]
#3302

**Comment by JT8001** [comment]
我也出现了这个问题
