### ISSUE TITLE
MAA无法正常打开

### ISSUE THREAD

**Issue by hijack114514** [MaaAssistantArknights/MaaAssistantArknights#6466]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天已经弹过一次这个了，我尝试下载最新的MAA并替换原MAA中的文件后正常使用了一次，但是过一段时间后又弹出了该错误（不过好像功能可以正常运行？）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12682917/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12682921/gui.log)

### 截图

![屏幕截图 2023-09-21 172949](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142242356/d48c3f99-b61a-462d-ab5a-d30c2b89b599)

### 还有别的吗？

win10专业版

**Comment by ABA2396** [comment]
更新到内测版还会有这个问题么？这个已经改过了，先把cache/etag.json删掉就能打开了
