### ISSUE TITLE
通过DLL调用时没有处理加工站

### ISSUE THREAD

**Issue by Zebartin** [MaaAssistantArknights/MaaAssistantArknights#6468]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在使用ALAS运行MAA时，自定义基建不会处理加工站。直接使用MAA本体正常。

看了一下[ALAS代码](https://github.com/LmeSzinc/AzurLaneAutoScript/blob/e5fa28d4a19b26e92515ec09140453ff482a5d4a/submodule/AlasMaaBridge/module/handler/handler.py#L325-L386)，只是把相应参数交给MaaCore的DLL来处理，个人判断是DLL的问题，所以提在这边的issue里。

### 日志文件

因为不是本体出的问题，所以没有`gui.log`。出现问题的时间点在`11:02`和`19:00`左右。

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12683950/asst.log)

**Comment by MistEO** [comment]
新增了一个 processing 的值，要 alas 处理下

**Comment by Zebartin** [comment]
打扰了，之前以为`facility`参数不会影响到自定义，加上之后没问题了
