### ISSUE TITLE
国际服生息演算的功能目前还没有适配MacOS版MAA

### ISSUE THREAD

**Issue by XuTingyi** [MaaAssistantArknights/MaaAssistantArknights#6470]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

国际服生息演算的功能目前还没有适配MacOS版MAA，不知道是否有进度？

**Comment by ABA2396** [comment]
core是支持的，应该就是缺个界面

**Comment by ABA2396** [comment]
cc @hguandl

**Comment by Constrat** [comment]
ref: #6265

**Comment by hguandl** [comment]
macOS 这边是在 4102f9727ee437a3371e68635b556f5edbe59e34 加上的，目前好像还没发版

**Comment by MistEO** [comment]
公测版更新了
