### ISSUE TITLE
水月肉鸽低难度开局选人必定少选一个

### ISSUE THREAD

**Issue by HoshinoAyako** [MaaAssistantArknights/MaaAssistantArknights#6471]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

0难度的水月肉鸽，心胜于物分队，稳扎稳打开局选黑键

每次开MAA都少选一个开局干员，甚至这个干员0希望都不选。

用的版本是最新内测版

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12685149/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12685151/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/33ea0956-f6b5-4c3d-9136-61c488d2b9bc)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/9a2cd2d3-86e9-4865-b744-e9a2b0d09d5c)

### 还有别的吗？

MuMu12模拟器

WIN10

**Comment by Lancarus** [comment]
先尝试助战干员开吧？

**Comment by HoshinoAyako** [comment]
> 先尝试助战干员开吧？

开局助战就不少人了。神奇的

**Comment by HoshinoAyako** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/f52fd2c7-97cf-4940-a26a-26eae9d06f2e)

**Comment by HoshinoAyako** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/98efcfd4-eb41-4294-bcb7-32c66aa2ef2b

**Comment by HoshinoAyako** [comment]
而且我发现，用稳扎稳打职业组，只要不是指定重装先选，只要是狙击或者术士先选，必定出这个BUG。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/7dc0710b-922d-475d-acd5-cc9c45645d73)

**Comment by HoshinoAyako** [comment]
[@](https://github.com/Lancarus)

**Comment by HoshinoAyako** [comment]
@Lancarus 前辈

**Comment by Lancarus** [comment]
给每个职业找个三星打上is start就行，克洛丝和史都华德应该没打
