### ISSUE TITLE
连接问题。在某些情况下无法正常运行。

### ISSUE THREAD

**Issue by xiaocheng-bili** [MaaAssistantArknights/MaaAssistantArknights#6472]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用MacBook M1芯片；系统版本：MacOS14.0；MAA版本：v4.24.0-beta.4（403）具体问题是在MAA中按下开始任务按钮之后，转几圈直接复原，没有其他的反应。如图
<img width="882" alt="截屏2023-09-21 23 34 02" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74574034/b2b1a9b2-9a14-45e6-abbc-6037c0fb0538">
我看不懂日志盲猜是连接问题，所有的配置都是按照使用说明进行设置，并且今天下午[2023-09-21 14:26:50.513]左右，见日志）正常运行了，但是晚上[2023-09-21 23:51:38.240] 见日志）又无法连接了。总的来说就是今天下午可以运行但是晚上又运行不了了，尝试过改端口等操作无果，日志如下。

ps.在MacOS系统中的 debug 文件夹中没有找到gui.log日志文件，下方只有找到的asst.log日志文件。
pss.希望有大佬可以指点一下，感谢！

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12686783/asst.log)

### 截图

MAA软件设置截图：
<img width="315" alt="截屏2023-09-22 00 05 12" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74574034/c13c9bbd-9334-492a-9518-312f36a090fd">
<img width="303" alt="截屏2023-09-22 00 05 23" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74574034/b42e51b8-0a43-4c08-938d-984ce7f75890">
<img width="308" alt="截屏2023-09-22 00 05 34" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/as
<img width="318" alt="截屏2023-09-22 00 05 41" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74574034/a785a71d-9920-42be-b487-56f4a1b0bcf0">
sets/74574034/b982cab8-e833-4e9f-b3e7-54c02077d338">

### 还有别的吗？

使用playcover进行运行，操作按照使用说明进行设置。虽然之前有成功运行过，不过不排除有设置问题，所有在playcover中的明日方舟设置截图如下：
<img width="695" alt="截屏2023-09-22 00 02 02" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74574034/25aa8f95-e028-414d-85de-6d400e11e64a">
<img width="507" alt="截屏2023-09-22 00 02 27" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74574034/37e00bbf-429e-434f-aad9-18ab3347e8b9">
<img width="513" alt="截屏2023-09-22 00 02 33" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74574
<img width="517" alt="截屏2023-09-22 00 02 42" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74574034/b3c897d4-0ba9-41f7-ba51-1d95766108f5">
034/e33c5368-419c-4bce-ac0c-5d23d5dab276">

**Comment by isaacveg** [comment]
我遇到过类似的问题，我的log里报错显示connection refused，在系统设置--通用--共享--高级三个选项重新打开关闭后恢复正常。合理怀疑是macOS14导致的

你的log里显示无法解析localhost，可以按照这个关键词在搜索引擎里搜索一下试试；或者试试把localhost换成127.0.0.1
