### ISSUE TITLE
日服生息演算不可用，卡在选角界面

### ISSUE THREAD

**Issue by haaddii** [MaaAssistantArknights/MaaAssistantArknights#6473]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图，会卡在选取角色的界面。
疑似OCR模型对日文的识别还是不行或者识别文本设置依旧存在漏洞？
目前感觉是OCR识别错误导致的。

另外吐槽一句傀影肉鸽挂机也有点问题，偶尔会卡在选取肉鸽（即选取傀影还是水月的位置（目前日服只有这俩）），以及偶尔会出现突然不对干员进行操作的情况。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12687801/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12687901/asst.log)

>大概是在最后一行

### 截图

![MuMu12-20230922-001702](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/98678113/d8d01640-d7e1-4102-9c6b-1295597a5247)

### 还有别的吗？

Mumu12 win11 不清楚Hyper-V是否影响了Mumu的性能。
设置：屏幕：1920x1080 ppi280 自动调优
在ADB Input、Mini Touch、MAA Touch下均进行了尝试，无法进入关卡。

**Comment by haaddii** [comment]
基本上是一直在反复识别，迷。

**Comment by SnowLancelot** [comment]
编队一个人没有别说maa，你手动点都不能开始行动，而且这个界面只需要编一次队就行了
