### ISSUE TITLE
使用蓝叠国际版时将MAA设为开机自启动，会一直连接ADB失败

### ISSUE THREAD

**Issue by Astrophel-Y** [MaaAssistantArknights/MaaAssistantArknights#6474]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

开机自动启动MAA与模拟器时，极大概率连接失败（目前还没有连接成功的情况），重启MAA和模拟器都无法解决问题，但如果不设为开机自启动（或者重启电脑后，不稳定）则连接失败的概率就比较小。
Bug一直存在，此前复现频率较低，大概从蓝叠模拟器国际版更新到5.13.0.1074后复现频率变为极高。
**系统开启了Hyper-V，Bluestacks.Config.Path与Bluestacks.Config.Keyword是已经正确配置的，不存在无法抓取已改变的port号的情况。**
netstat -ano | findstr “5037” 扫描5037以及模拟器开放的port（如日志中为8881），发现并没有其他进程在占用这两个端口。
查看asst.log，大概定位了问题发生时的日志记录，有这些信息：
```
[2023-09-22 08:25:08.216][INF][Px44a4][Tx2d24] Call ` C:\Program Files\BlueStacks_nxt\.\HD-Adb.exe connect 127.0.0.1:5554 ` ret 1 , cost 4729 ms , stdout size: 142 , socket size: 0
[2023-09-22 08:25:08.216][TRC][Px44a4][Tx2d24] stdout output:
* daemon not running; starting now at tcp:5037

could not read ok from ADB Server

* failed to start daemon

error: cannot connect to daemon


[2023-09-22 08:25:08.217][INF][Px44a4][Tx2d24] Assistant::append_callback | ConnectionInfo {"details":{"adb":"C:\\Program Files\\BlueStacks_nxt\\.\\HD-Adb.exe","address":"127.0.0.1:5554","config":"BlueStacks"},"uuid":"","what":"ConnectFailed","why":"Connection command failed to exec"}
```
Maa会进行多次连接的尝试，前几次会尝试连接模拟器的port（日志中为8881），失败后尝试连接的端口会跳到5555-5595左右，都没有效果。
尝试了各种解决方案，包括替换adb、使用adb lite、重启adb-server等方式皆无法解决问题。
目前状况就是无法开机自动一键长草，必须开机后手动启动MAA和模拟器才能正常使用。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12694366/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12694384/asst.log)

### 还有别的吗？

模拟器：蓝叠国际版5.13.0.1074
安卓版本：安卓7 Nougat64
系统：
Windows 10 专业版
版本号	22H2
操作系统内部版本	19045.3448

**Comment by Astrophel-Y** [comment]
> 不知道是不是同個問題，但我每次手動去找C:\ProgramData\BlueStacks_nxt\bluestacks.conf 這個檔案中的adb_port，更新到MAA的設定上就可以成功連接了，看起來是它不會自動抓port的問題。

我看了下日志，是成功抓了port的。目前测试是一旦将Maa设为开机自启动，就极大概率会发生连接失败的问题，而不设为自启动时，问题发生的概率就很小

**Comment by MistEO** [comment]
> 不知道是不是同個問題，但我每次手動去找C:\ProgramData\BlueStacks_nxt\bluestacks.conf 這個檔案中的adb_port，更新到MAA的設定上就可以成功連接了，看起來是它不會自動抓port的問題。

https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7-hyper-v
