### ISSUE TITLE
模拟器分辨率获取失败

### ISSUE THREAD

**Issue by Juaner1550** [MaaAssistantArknights/MaaAssistantArknights#6475]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

**我的MAA启用雷电模拟器时提示模拟器分辨率获取失败，随后就一直开始重启模拟器**，两三次之后就显示连接失败了。
我没有开:”ADB重启失败时自动重启模拟器”。
**事情的起因是看一些攻略没仔细看，在选择雷电模拟器后，连接地址填写了127.0.0.1后启动了一次MAA，在此之前MAA是可以用的**。大概情况如下图所示，**后面将链接地址改为emulator-5554，依旧一样的报错**
重新下载模拟器，换MUMU12模拟器，重新下载MAA都没有用

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12694487/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12694488/gui.log)

### 截图

![1695344356497](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145729845/57db0dc1-1ac5-4751-98d8-394049c7d594)
![1695311708728](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145729845/11f7f509-35ee-46d7-ac9d-7be43dca5ccb)

### 还有别的吗？

最新的Windows系统

**Comment by yc080713** [comment]
adb路径填错了
重读常见问题文档[常见问题](https://maa.plus/docs/1.2-常见问题.html)

**Comment by Juaner1550** [comment]
> adb路径填错了 重读常见问题文档[常见问题](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html)
你好，我把雷电的那个链接路径改回emulator-5554（如图二）还是一样报错

**Comment by ABA2396** [comment]
你把模拟器路径填到了adb路径里面了

**Comment by Juaner1550** [comment]
> 你把模拟器路径填到了adb路径里面了

谢谢哥，已解决，感恩。

**Comment by Juaner1550** [comment]
> adb路径填错了 重读常见问题文档[常见问题](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html)

谢谢您

**Comment by Juaner1550** [comment]
是我的链接地址填错了，ADB路径可以直接选择图标链接过去，但是连接地址应该是填的127.0.0.1:5555 而不是 emulator-5554 (雷神9模拟器）![Uploading 1695352627470.jpg…]()
