### ISSUE TITLE
WpfGui主界面完成后项目拆分

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#6477]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

WpfGui完成后 下拉框项目太多，似乎有优化空间

### 有什么好的想法？

关机、睡眠、关机（仅一次）、无其他MAA则关机 这6条感觉可以从完成后选项里面拆出来，单独放一个CheckBox在下拉框下面。

做成 关机 / 睡眠 的下拉框，若无其他MAA 和 下拉框做两个CheckBox来激活

**Comment by ABA2396** [comment]
但是这个拉出来之后主界面显示的就更多了吧）看看有啥好办法没

**Comment by status102** [comment]
若无其他MAA这个应该可以直接合并到一起

**Comment by status102** [comment]
这样就是增加一个复选框+一个下拉
' [✓] [ 关机 / 休眠] '

**Comment by status102** [comment]
再提供一个新方案，横置三个可以处于按下/弹起的按钮，分别为` 关MAA | 关模拟器 | 关机 `

关机还是休眠，在设置里面变更。无论关机还是休眠一律检测有无其他MAA。
激活关机时，另外俩设为disabld

**Comment by status102** [comment]
再提供一个新方案，横置三个可以处于按下/弹起的按钮，分别为` 关MAA | 关模拟器 | 关机 `

关机还是休眠，在设置里面变更。无论关机还是休眠一律检测有无其他MAA。激活关机时，另外俩设为disabld。

这样做出来就还是一行

**Comment by Cryolitia** [comment]
您好，这里有主界面完成后优化方案的相关讨论
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6488#issuecomment-1732573793

**Comment by status102** [comment]
CheckComboBox

![CheckComboBox.png](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/25a64588-c8f5-44af-8eab-104b4b952d55)

**Comment by Cryolitia** [comment]
这个方案看上去不错，但是怎么解决部分选项互斥的问题，如（关机|休眠）

> CheckComboBox
> 
> ![CheckComboBox.png](https://private-user-images.githubusercontent.com/102887808/290089134-25a64588-c8f5-44af-8eab-104b4b952d55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTczMzYsIm5iZiI6MTcwMjQ1NzAzNiwicGF0aCI6Ii8xMDI4ODc4MDgvMjkwMDg5MTM0LTI1YTY0NTg4LWM4ZjUtNDRhZi04ZWFiLTEwNGI0Yjk1MmQ1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwODQzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMThlZTMzMTkxMjE3NGY4ODEzY2IxMjMxZDMxZDBmN2Y2ZTRlNjJjOGZmNDk0YWZlYWEyMTEyOGFmMmE4MTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oP-bBtee0f1Sy38xj_rcpl4-MKUewNjXgOo3mNI9Yrs)

**Comment by status102** [comment]
> 这个方案看上去不错，但是怎么解决部分选项互斥的问题，如（关机|休眠）

只能看看有没有changed，changed时候启用/禁用互斥

**Comment by Cryolitia** [comment]
CC @uye 你觉得怎么样，我觉得整挺好

**Comment by ABA2396** [comment]
可以吧，但要不之后在做）

**Comment by Cryolitia** [comment]
之后是指的（？

**Comment by ABA2396** [comment]
.net8合了之后吧
