### ISSUE TITLE
sv-9掉落识别错误

### ISSUE THREAD

**Issue by CloudButterly** [MaaAssistantArknights/MaaAssistantArknights#648]
所使用模拟器为蓝叠国际版64位，dpi240，分辨率为1600 900，帧数60
如图
![_T$S00%2I5V)EZ7L~8)5DT7](https://user-images.githubusercontent.com/106486744/171157881-06e2f219-c26d-4030-9aa1-b6ef4b29b9e6.png)
日志如下
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8804438/asst.log)

**Comment by YorigamiPL** [comment]
不是，beta.8还是识别错误啊(
![image](https://user-images.githubusercontent.com/37739947/171175332-094298e9-f61a-4110-8b34-f528317268e8.png)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8805159/asst.log)

**Comment by MistEO** [comment]
修了，还没发版，大概是 beta 9

**Comment by YorigamiPL** [comment]
好哦
