### ISSUE TITLE
日服无法刷傀影肉鸽

### ISSUE THREAD

**Issue by MejiroSilence** [MaaAssistantArknights/MaaAssistantArknights#6489]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

傀影肉鸽会卡在截图所示界面，需要手动点击进入傀影肉鸽才能进行任务

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12705365/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12705366/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59904337/42a3ac04-9435-4efb-b354-ca61cc909b6e)

**Comment by MejiroSilence** [comment]
而且会出现和 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6486 相似的问题，借用角色后卡在立绘

**Comment by zzyyyl** [comment]
卡立绘的问题应该修复了

导航问题需要适配，给 `resource/global/YoStarJP/resource/tasks.json` 增加如下内容（其中 text 按照日服 UI 修改）：
```json
    "Roguelike@FromIntegratedStrategies": {
        "text": [
            "进入主题"
        ]
    },
    "Phantom@Roguelike@SelectTheme": {
        "text": [
            "傀影"
        ]
    },
    "Mizuki@Roguelike@SelectTheme": {
        "text": [
            "水月"
        ]
    },
    "Sami@Roguelike@SelectTheme": {
        "text": [
            "探索"
        ]
    },
```

可以参考 YostarEN 的适配。
