### ISSUE TITLE
自动战斗功能改进

### ISSUE THREAD

**Issue by soundofautumn** [MaaAssistantArknights/MaaAssistantArknights#650]
现在这作业太难写了（
计时什么的都不知道从哪开始，只能多了往低调，少了往多调，能不能在每次计时前都加个暂停什么的，或者给个提示什么的（可以开发个debug模式）
还有既然都用模拟器了，时停部署能不能搞得定（

**Comment by ABA2396** [comment]
现在写作业的基本都是参考击杀数来计时的吧，前置后置时间还有cost只是补充
