### ISSUE TITLE
希望使用【自动战斗】时可以更及时地更新MAA\cache\avatars的头像图片

### ISSUE THREAD

**Issue by Dayheart117** [MaaAssistantArknights/MaaAssistantArknights#6503]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在切换皮肤后，MAA并不会即时更新角色头像信息，而是有概率的更新头像信息，导致有时候局内角色皮肤和MAA\cache\avatars的图片不一致，从而导致闪灵泳装皮，拉普兰德皮肤等出现找不到干员而阻塞作业进程的情况。
同时局内由于费用原因，也会导致开局更新的干员头像有的是亮的有时候是暗的，也有概率出问题，比如较高费用的棘刺和拉普兰德在开局时更新头像为没费用的暗色，但作业要部署时费用足够变为亮色导致卡住（截图替换后该问题消失，但过一阵子又会出现）

### 有什么好的想法？

思路1：增加更新头像问题的次数。
建议1:在【自动战斗】界面新增一个【更新头像】选项。手动在编队界面基于角色名称更新一次头像信息；或者勾选该选项后在自动编队完成时更新一次头像信息。
建议2:在局内自动战斗时，如果找不到干员，那么暂停后挨个选取可放置角色即时更新一次头像信息。

思路2：同时存储一位干员的多个皮肤的头像文件
如：拉普兰德-skin1-light.png，拉普兰德-skin1-black.png，拉普兰德-skin2-black.png
或：拉普兰德\skin1.png

### 其他内容

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89849559/ad82936f-3e6d-4eca-a3f8-345fde724955)

**Comment by ABA2396** [comment]
部署栏里遇到不认识的干员是会重新识别的啊）

**Comment by Dayheart117** [comment]
我又排查了一下问题，是重新识别的时候有把拉普兰德原皮识别为拉普兰德，然后拉普兰德教会皮识别为其他干员，棘刺联动皮也会有这个情况，如图
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89849559/dda9772f-6c3e-46b1-b56e-b9a19c05492f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89849559/2dd77bad-4bed-41f7-8b0e-68459ee547ed)
这个是直接把这些图删掉就不用管了吗，还是反映了当前识别程序有一定的问题。

**Comment by Dayheart117** [comment]
基于这个错误识别的情况，会导致MAA识别到正确头像却认为是其他干员。
从而在局内需要部署角色的时候找不到该角色。

或许可以做一个识别按钮来在编队界面看看MAA认为这些都是谁，有助于人工排查

**Comment by Dayheart117** [comment]
我悟了，每次抽风我就直接把头像信息全删掉就是了，全重新识别，省的一个一个找头像看哪个不对了（）

**Comment by hifuclub** [comment]
> 我悟了，每次抽风我就直接把头像信息全删掉就是了，全重新识别，省的一个一个找头像看哪个不对了（）

这里建议加一个一键清空截图，省的经常去MAA\cache\avatars删了

**Comment by SherkeyXD** [comment]
fixed in #6967
