### ISSUE TITLE
WpfGui任务完成-理智恢复时间格式紊乱

### ISSUE THREAD

**Issue by Boss1412** [MaaAssistantArknights/MaaAssistantArknights#6506]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如图，我120满级，当前已经清空理智，按照5分钟一理智，理论上不可能再下午1点就回复满理智？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12707625/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12707626/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/135352662/95ee04be-aaa6-4561-a987-213f2fd8fcfd)

**Comment by status102** [comment]
WpfGui理智预测目前的格式为 具体时间（时间间隔），回满时间是22:47（13小时后）。设备的长时间格式可能被修改掉了，等会看看定成强制格式吧

**Comment by zzyyyl** [comment]
怎么改都还是有人看不懂.jpg
