### ISSUE TITLE
自动战斗中使用战斗列表打不带摆完挂机的作业会任务出错

### ISSUE THREAD

**Issue by s-yh-china** [MaaAssistantArknights/MaaAssistantArknights#6507]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用战斗列表时会报任务失败然后退出列表的执行
阅读日志后发现可能是因为未知原因导致maa认为战斗已完成并尝试退出20次后失败而报错

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12707761/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12707762/asst.log)

尝试退出发生于 2023-09-24 12:05:10.828

**Comment by status102** [comment]
- #6497 
已提交PR

**Comment by status102** [comment]
OF-EX-4突袭，能详细描述一下嘛

**Comment by s-yh-china** [comment]
> OF-EX-4突袭，能详细描述一下嘛 以及看看使用的作业？(是maa://22936嘛

是maa://22936 需要什么详细描述?

**Comment by status102** [comment]
> 是maa://22936 需要什么详细描述?

是下完所有干员时候就当任务结束了嘛

**Comment by status102** [comment]
目前推断是没有摆完挂机选项，直接就下完就当结束了

**Comment by s-yh-china** [comment]
的确是这样的 但这种作业并不少见 可能需要让maa自动在最后加入摆完挂机操作
