### ISSUE TITLE
能不能给maa的抽卡加一个选择卡池的功能

### ISSUE THREAD

**Issue by Eggtall** [MaaAssistantArknights/MaaAssistantArknights#6511]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用抽卡功能时会自动跳转第一个卡池 没有提示 容易抽错池子

### 有什么好的想法？

让抽卡功能加一个选择的地方

**Comment by ABA2396** [comment]
抽卡优先抽当前页面的，如果不在抽卡界面就是第一个池子
