### ISSUE TITLE
肉鸽刷源石锭模式下开局招募干员会意外卡死，并在很长一段时间后自动结束刷肉鸽任务

### ISSUE THREAD

**Issue by Cipolla123** [MaaAssistantArknights/MaaAssistantArknights#6513]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽刷源石锭模式下，有时会出现选完开局干员之后直接摆烂的操作。
根据日志判断，maa似乎并没有停止工作，只是好像在不断检测什么东西。
另外12：09分的停止任务，我也理解不了为什么会出现这样的情况。（这段时间一直都是maa自动，没有人工干预）
我当时以为可能是当时电脑正好卡了，maa的点击没有生效。但根据日志判断（时间08：31：14），maa在找到助战稀音后，只点过两次minitouch（理论上要点三次），不知道是哪里判断出问题了。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12707987/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12707989/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145891386/decda75f-7860-472f-800a-93d1fcca2f2d)
以下为游戏界面，我来看的时候就卡在这个界面。
![MuMu12-20230924-145754](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145891386/4403be59-2742-442f-97f1-8781681a9490)

以下为maa的相关设置
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145891386/ea16716f-86af-49e4-80a0-c8c11bcbda17)
勾选了使用好友助战

### 还有别的吗？

使用的是MuMu12模拟器
分辨率1280*720

**Comment by Lancarus** [comment]
bug已知，内测版已尝试修复，试用一下看看

**Comment by HoshinoAyako** [comment]
目前这个BUG仍然存在。[@lancarus](https://github.com/Lancarus)
部分Beta4、Beta5正常使用不会卡的更新到RC1都卡了。

**Comment by Black1312** [comment]
> bug已知，内测版已尝试修复，试用一下看看

最新内测仍然卡死，6星干员正常，但预备干员卡死。
MAA版本号：4.24.0-rc.1.d004.g055abcfef
log时间：2023-09-25 10:28:25
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12710578/asst.log)

**Comment by Lancarus** [comment]
> > bug已知，内测版已尝试修复，试用一下看看
> 
> 最新内测仍然卡死，6星干员正常，但预备干员卡死。 MAA版本号：4.24.0-rc.1.d004.g055abcfef log时间：2023-09-25 10:28:25 [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12710578/asst.log)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/47da4148-1622-4f45-bd8c-383389bb65e8)
把这个再调低点试试，调0.6看看

**Comment by ABA2396** [comment]
为啥改成三颗星的图了？那小车啥的会炸吗）原来用的就是这个三颗星的图吗

**Comment by Lancarus** [comment]
> 为啥改成三颗星的图了？那小车啥的会炸吗）原来用的就是这个三颗星的图吗

肉鸽里面不招二星一下的啊，本来是justreturn任务

**Comment by HoshinoAyako** [comment]
@Lancarus 前辈。![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/e494cf32-ea88-480e-b351-8b29223a6fb8)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/55798580-27d0-44ab-aff8-0d652688efed)
这两处改了以后就没在卡了。

**Comment by wenkai0225** [comment]
能不能帮我也看一下我也是这个问题 但是我用的是mac m1 设置什么的都按照指示调好了 也是卡在初始招募界面 招募完第一个六星第二个三星就一直卡在这里了 求助大佬 谢谢了
<img width="1440" alt="Screenshot 2023-09-26 at 4 31 27 am" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146024443/f573b685-7c70-4658-866e-edb03beeca94">
<img width="1440" alt="Screenshot 2023-09-26 at 4 31 31 am" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146024443/205648c5-ff0f-4ceb-8086-691335eabd0b">

**Comment by SherkeyXD** [comment]
正式版已修复
