### ISSUE TITLE
萨米肉鸽刷源石锭模式下招募干员会卡住

### ISSUE THREAD

**Issue by lllfy0911** [MaaAssistantArknights/MaaAssistantArknights#6515]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽刷源石锭模式中反复多次出现卡在招募干员界面的情况（在开局和商店使用招募券时均会出现，卡在完成招募后展示干员立绘的地方）。
如果手动离开这个场景，maa会自动结束当次探索。
已确认不是模拟器杀后台的原因，也尝试把maa和模拟器都放在最前端运行，但似乎也不能解决。
有的时候会卡住，但有的时候可以正常运行。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12708078/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12708079/gui.log)

### 截图

以下为游戏卡住的位置（这里是开局招募干员的地方）
![游戏截图](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145896453/a2c80ebe-50d0-478e-8dd3-87911fb48bc3)
以下两张是maa的相关设置和记录
![maa](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145896453/88e7cadb-173e-4c9c-b8f7-26993076262d)
![22](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145896453/a1089f7a-ec06-44f8-9fc3-9579a0ff9ab1)

### 还有别的吗？

模拟器：mumu12
操作系统：win11
分辨率：1920*1080

**Comment by lllfy0911** [comment]
换了一下其他的刷取策略，在刷等级模式中也遇到同样的问题qwq

**Comment by Constrat** [comment]
@Lancarus Is this the same issues as all the other that get stuck in the recruiting state of the operator?

**Comment by lllfy0911** [comment]
您好，您的来信已经收到，非常感谢，祝好?7?8(?1?1ω?1?1)?1?7

**Comment by Lancarus** [comment]
> @Lancarus Is this the same issues as all the other that get stuck in the recruiting state of the operator?

Yes，I thought I‘ve already fixed it in #6502. But now it seems not...

**Comment by HoshinoAyako** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6513

**Comment by wenkai0225** [comment]
能不能帮我也看一下我也是这个问题 但是我用的是mac m1 设置什么的都按照指示调好了 也是卡在初始招募界面 招募完第一个六星第二个三星就一直卡在这里了 求助大佬 谢谢了
<img width="1440" alt="Screenshot 2023-09-26 at 4 31 27 am" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146024443/d82b12f2-da0b-4ecb-8927-607b8c1e6de2">
<img width="1440" alt="Screenshot 2023-09-26 at 4 31 31 am" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146024443/c138a929-8f52-45bf-85e7-ccaccf2f95c3">

**Comment by Constrat** [comment]
It's being worked on #6528

**Comment by zzyyyl** [comment]
`v4.24.0` fixed
