### ISSUE TITLE
关于明日方舟萨米肉鸽出现BUG问题

### ISSUE THREAD

**Issue by undiyone** [MaaAssistantArknights/MaaAssistantArknights#6522]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

版本：v4.24.0-rc.1
关于明日方舟萨米肉鸽出现BUG问题：游戏在招募干员中招募成功后无法跳过角色动画。
游戏在进行中，从右侧选择一名干员来运输物资时，卡在该界面。
游戏在进行中频繁出现放置干员时，无法放置。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12710285/gui.log)

### 截图

![2023-09-25_08-54-59-300_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145853805/46685973-78a6-40c9-9a29-2d138b506147)
![2023-09-25_09-14-30-324_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145853805/3557a66e-2bf2-42ce-9fb9-8f8bada30593)
![2023-09-25_09-24-45-180_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145853805/b471b46a-f6b5-40ac-9a49-eb7041b61f47)

### 还有别的吗？

模拟器MUMU12
操作系统windows10

**Comment by HoshinoAyako** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6513

**Comment by KuiPer-LTW** [comment]
一样的问题，刷源石锭直接卡在开局了

**Comment by zzyyyl** [comment]
有没有 asst.log

**Comment by undiyone** [comment]
> 有没有 asst.log

没有asst.log  都删了

**Comment by HoshinoAyako** [comment]
@undiyone 
先行一步事件，解决方法可以参考https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6460
干员招募卡立绘界面，解决方法可以参考https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6513
频繁出现放置干员无法放置问题，请上传asst.log和gui.log再详细分析解决。

**Comment by hifuclub** [comment]
> @undiyone 先行一步事件，解决方法可以参考#6460 干员招募卡立绘界面，解决方法可以参考#6513 频繁出现放置干员无法放置问题，请上传asst.log和gui.log再详细分析解决。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12713725/asst.log)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12713727/gui.log)
