### ISSUE TITLE
利用当前理智判断是否执行Fight

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#6524]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

例如：
关卡选择、备选：[剿灭, CE-6, 1-7] 会在理智<25的情况下访问剿灭，会在理智<36(30)的情况下访问CE-6，会在理智<6情况下访问1-7，并失败返回，会额外消耗资源和时间

### 有什么好的想法？

既然已知当前理智，是否可以根据关卡理智消耗数据，直接跳过重复执行的Fight，
比如在上述例子中，执行到Fight任务时，检测到理智只有5，那么三段Fight都跳过。

**Comment by ABA2396** [comment]
理智不足不会进下一个备选啊，只会进‘剩余理智’，不会一个个试过去的

**Comment by KJH-x** [comment]
那可能是我恰好观测到了偶发的bug，下次如果复现我再开

**Comment by KJH-x** [comment]
再次观测到并复现成功：
文字描述：开始->startup->（理智5/135）->Fight剿灭、失败->（理智5/135）->CE-6、失败->1-7、失败->Infrast->...
环境信息：夜神模拟器1280x720@60fps，MAA V4.24.0-rc.1，Windows 10 专业版 22H2 19045.3324
文件描述：关键截图(28p, zip)，asstlog，guilog
[keyframe.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12725771/keyframe.zip)
[report.asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12725775/report.asst.log)
[report.gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12725777/report.gui.log)

**Comment by ABA2396** [comment]
只有剿灭失败了是会去执行下一个备选的，因为如果你剿灭打完了的话，是没有那个入口的，那个是报错而不是没有理智，所以这次任务的关卡是ce-6，但是因为你的理智不足以打ce-6，所以进了剩余理智。剩余理智跟前面的都已经不是一个任务了

**Comment by ABA2396** [comment]
你那个1-7是第二个备选关卡，还是剩于理智？

**Comment by KJH-x** [comment]
> 你那个1-7是第二个备选关卡，还是剩于理智？

是第二备选，剩余理智未启用

```json
      "MainFunction.Stage2": "CE-6",
      "MainFunction.Stage3": "1-7",
      "Fight.UseRemainingSanityStage": "False",
```

**Comment by ABA2396** [comment]
我等下回去看看

**Comment by KJH-x** [comment]
似乎没有进一步需要在这个议题下讨论的内容，故关闭
