### ISSUE TITLE
MAA启动随机闪退或报错

### ISSUE THREAD

**Issue by CainXCain** [MaaAssistantArknights/MaaAssistantArknights#6529]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

1 启动时概率闪退，（设置了自动打开模拟器）有时能打开模拟器再闪退有时直接闪退；
反复启动两、三次可以成功启动
2 启动时较小概率报错“资源损坏，请重新下载”，重新启动可以正常运行

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12712051/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12712070/gui.log)
28158行，这行下面的启动是成功的启动，上面是 1 中的闪退

2出现较少没保留log

### 还有别的吗？

似乎都是加载出错，但一种是直接闪退一种是报错，由于都能重启解决，考虑一下加载错误的错误处理？（反复加载之类的）

**Comment by Constrat** [comment]
Resource damaged is not normal. Did you edit any of the files in /resource?

**Comment by CainXCain** [comment]
> Resource damaged is not normal. Did you edit any of the files in /resource?↳

No

And i suspect the resource isn't really damaged (since restart can solve it), but MAA went wrong when loading resource

**Comment by Tsuk1ko** [comment]
+1，我也会碰到闪退或提示资源损坏的问题，但是重启又正常

刚才刚好发生了一次提示资源损坏，2023-09-26 20:08 启动的，不过貌似资源损坏不会有日志体现

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12727492/asst.log)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12727494/gui.log)

**Comment by zzyyyl** [comment]
修过了，正式版 4.24.0 刚刚也发了
