### ISSUE TITLE
基建自动排班

### ISSUE THREAD

**Issue by ability66** [MaaAssistantArknights/MaaAssistantArknights#653]
能设置成能天使 拉狗 德狗一起吗，不要拆散他们三个啊

**Comment by ABA2396** [comment]
~~因为他们三个一起的效率没有拆开高~~

**Comment by zhongzi26** [comment]
> 能设置成能天使 拉狗 德狗一起吗，不要拆散他们三个啊

基建效率是图像识别后算出来单间效率最高的组合了，能拉德 放在一起效率并没有拆开高所以没有放在一起

**Comment by MistEO** [comment]
~~无情的效率机器~~
