### ISSUE TITLE
希望可以在 完成后 选项里加入 退出 MAA 和 明日方舟 的选项，有时候在挂完粥之后会继续肝其他游戏

### ISSUE THREAD

**Issue by Garyllis** [MaaAssistantArknights/MaaAssistantArknights#6531]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by Constrat** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/b9ae774d-0c4f-4e01-84f1-231b838b14f0)
You mean a Exit MAA and Exit Arknights, instead of Emulator?

**Comment by Cryolitia** [comment]
您好，这里有主界面完成后优化方案的相关讨论
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6488#issuecomment-1732573793

**Comment by Constrat** [comment]
Then we can link this issue to that PR.
