### ISSUE TITLE
肉鸽中部分干员技能携带错误

### ISSUE THREAD

**Issue by HoshinoAyako** [MaaAssistantArknights/MaaAssistantArknights#6532]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

按照肉鸽Mizuki的recruitment里的设定
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/59a5c2bf-ddf5-4d19-a66a-7c4e37802424)
应该在精二以后选择3技能。但是实际在关卡自动编队选技能的时候选择了1技能。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/15c4ae1d-a2ff-46ef-8f86-5c77bb4339ca)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/8bce17d2-1eba-4f33-8467-7170e991d70f)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12715096/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12715097/asst.log)

### 还有别的吗？

MUMU12模拟器
WIN10专业版22h2

**Comment by HoshinoAyako** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/392206f0-ea4d-4841-9efb-f93a6f5217bf)
凯尔希精2自动选了2技能。按理说应该选1技能的

**Comment by HoshinoAyako** [comment]
@Lancarus 前辈麻烦有空来看看。这些BUG目前RC1版本都能复现。

**Comment by HoshinoAyako** [comment]
我把Mizuki的recruitment里头所有alternate_skill与skill调换顺序以后。就都能正确选择对应的技能了。

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/a28858ba-beb2-4804-b767-3b031c1b603b)

但是这又产生了一个新的问题。凯尔希如果上一次战斗中正确选择2技能，那下一次战斗选择技能的界面就会抽风选1技能了。
![c725aaf0afbec19f080d55974bfc4214](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/315e4c2a-b71e-42a3-8bc2-7fff37e66db2)
![3fb2f998100d710c5a9ce3e3a797348c](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/d49ceaa8-7a1b-43e9-8192-c949914a5df7)

**Comment by HoshinoAyako** [comment]
还有一件事就是。水月肉鸽中干员畸变后，技能选都不选了。根本没有点击的反应。

**Comment by Lancarus** [comment]
@AnnoyingFlowers 佬来看看？

**Comment by HoshinoAyako** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/11955be1-3a5d-4906-97f0-73147ee7da72
前辈。傀影肉鸽，棘刺精2不选3技能这问题和水月肉鸽凯尔希精2的问题一样啊

**Comment by HoshinoAyako** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/8baf7a4a-6048-4474-9c42-361130848f2a)
