### ISSUE TITLE
自定义基建识别异常

### ISSUE THREAD

**Issue by loyunemo** [MaaAssistantArknights/MaaAssistantArknights#6535]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建中枢干员首选麒麟R夜刀时无法识别，会一直来回寻找夜刀而卡住

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12717093/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12717100/asst.log)
[2023-09-25 23:24:12.807] <1><> 首选干员: 阿米娅, 玛恩纳, 灵知, 麒麟X夜刀, 火龙S黑角
[2023-09-25 23:26:45.937] <1><> 首选干员: 麒麟X夜刀
[2023-09-25 23:26:52.674] <1><> 首选干员: 麒麟X夜刀
[2023-09-25 23:26:59.421] <1><> 首选干员: 麒麟X夜刀

### 还有别的吗？

模拟器：Mumu12明日方舟专版 Win系统采用自定义基建配置

**Comment by HoshinoAyako** [comment]
改名之后配置表也改了吗？
maa现在要更新到公测版才能识别R夜刀

**Comment by ABA2396** [comment]
把你配置表里的X改成R。

**Comment by loyunemo** [comment]
> 把你配置表里的X改成R。

感谢，已解决
