### ISSUE TITLE
日服自动肉鸽无法正常使用

### ISSUE THREAD

**Issue by AldousShou** [MaaAssistantArknights/MaaAssistantArknights#6537]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

傀影肉鸽无法开启（无法进入任务线的那个开启）
水月肉鸽无法下干员

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12717304/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12717306/gui.log)

### 截图

无	

### 还有别的吗？

无

**Comment by zzyyyl** [comment]
1. 没有看到傀影肉鸽的任何相关日志，考虑是不是没选肉鸽主题；
2. 是不是开了什么暂停下干员之类的？关掉试试
