### ISSUE TITLE
自动肉鸽刷源石锭无法退出

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#6541]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动肉鸽在刷源石锭时，投资完之后有可能会买招募券，然后在选完人之后卡死。
见截图，在人员页面卡了两分钟

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12722248/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12722252/gui.log)

### 截图

<img width="960" alt="2023-09-26" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90097743/3b63dbeb-17ed-45a8-8210-4a4c8320c999">

**Comment by Yingge02** [comment]
遇到同样问题+1，不过不止是购买招募券，在作战结束后获得招募券招募干员后也会卡在这个地方。手动点击退出这个界面后MAA会直接选择结束探索并重新开局，但依然会遇到同样的情况。

**Comment by MistEO** [comment]
修掉了，更新一下
