### ISSUE TITLE
4.24.0beta3, 夜神模拟器, 自动启动模拟器期间，如果模拟器几率卡死，判断再次重启

### ISSUE THREAD

**Issue by MXS2514** [MaaAssistantArknights/MaaAssistantArknights#6543]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

已经设置好模拟器路径，adb端口，adb重启等参数后，maa自动唤起模拟器，
当模拟器几率吊死（无限卡99%）时，60过后，maa判断失败，任务停止

![G(SD_NP9F4W_DT2LU`85ANQ](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/14242157/02929a54-eb2e-4f39-adb1-54d409489483)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/14242157/36c5aaf0-3ca8-4bd2-86ee-eee6963b59c2)

### 有什么好的想法？

结束模拟器进程并尝试重新启动（重试3次），使得流程得以继续

**Comment by ABA2396** [comment]
卡99%的时候再开有用吗？那个时候adb都没开起来也关不掉模拟器吧

**Comment by MXS2514** [comment]
> 卡99%的时候再开有用吗？那个时候adb都没开起来也关不掉模拟器吧

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/14242157/86d9006e-f272-4957-afb9-b0ae55810f38)
就是在这中间加tasklist,taskkill掉全部adb以及模拟器进程，在重新启动任务流程，重复1-3次

**Comment by ABA2396** [comment]
连接设置里有连接失败尝试重启adb的选项
adb都没开起来咋通过adb去关模拟器

**Comment by MXS2514** [comment]
> 连接设置里有连接失败尝试重启adb的选项 
我说的是重启模拟器，不是ADB，已经勾选了相关选项，在本ISSUE中并不好用，推测只有启动功能，没有重启功能


> adb都没开起来咋通过adb去关模拟器
启动模拟器必须得用ADB？

**Comment by Cryolitia** [comment]
模拟器卡死为什么不去找模拟器那边反馈……

**Comment by MXS2514** [comment]
> 模拟器卡死为什么不去找模拟器那边反馈……

我说的是有几率，你每次都能100%成功启动模拟器？

**Comment by Cryolitia** [comment]
> > 模拟器卡死为什么不去找模拟器那边反馈……
> 
> 我说的是有几率，你每次都能100%成功启动模拟器？

1. 模拟器有几率卡死为什么不去找模拟器那边反馈
2. 您好，能的

**Comment by MXS2514** [comment]
> > > 模拟器卡死为什么不去找模拟器那边反馈……
> > 
> > 
> > 我说的是有几率，你每次都能100%成功启动模拟器？
> 
> 1. 模拟器有几率卡死为什么不去找模拟器那边反馈
> 2. 您好，能的

1,我反馈的是MAA启动模拟器期间的判定流程优化，你不要总强调模拟器本身
2,不要觉得什么都能100%，没人反馈就等于没有了

少一些浮躁，于公于私都有好处

**Comment by Cryolitia** [comment]
> 1,我反馈的是MAA启动模拟器期间的判定流程优化，你不要总强调模拟器本身
> 2,不要觉得什么都能100%，没人反馈就等于没有了
> 
> 少一些浮躁，于公于私都有好处


计算机领域可复现性是一个极其严重的问题，我们没有理由认为某个软件**应该**是一个黑箱，坏了踢两脚就好了，今天不好明天用就好了。如果你坚称你的模拟器一定会出现这样的幽灵事件，并且想要解决他，请你查看模拟器启动日志自行寻找原因并尝试修复或向模拟器官方反馈。


**屎喷点巧克力香精就变成巧克力了吗，我的建议是你最好不要吃它。**

**Comment by MXS2514** [comment]
好家伙，没说两句snp都喷出来了，某些这三脚猫选手就这素质？

算了，被狗咬我也不能咬回去，只能报以同情

**Comment by MXS2514** [comment]
本来一个挺简单的需求，对MAA印象也不错，结果扯这么一出
要是确实实现有难度或者有其他解决办法，就不能好好提出来？非得呛一下

**Comment by ChingCdesu** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/41897540/99078303-0aec-4813-8997-fa4ab2a40958)
你真的有好好看文字吗？

**Comment by ABA2396** [comment]
关模拟器是用模拟器自己的控制台关的，不如试试在卡住的时候能不能用控制台关掉

NoxConsole.exe quit -index:模拟器编号

国产的模拟器基本都是双进程的，外面的壳子和里面的虚拟机是分开的，强行关掉的话虚拟机损坏都是有可能的。而且要是多开的话也分不清哪个进程是当前的模拟器，最稳妥的方法就是通过adb端口推模拟器编号用控制台关，或者用adb关

**Comment by x151973** [comment]
同夜神路过，也遇见过类似问题，贴个粗py自用可以参考下，大神们轻喷

```
import process_uptime, subprocess, psutil, time

maa_name = "MAA.exe"
process_name = "NoxVMHandle.exe"
maa = 0

while 1:
    time.sleep(1)
    try:
        pid = 1
        pidtime = 0
        maa = 0

        for proc in psutil.process_iter():
            if process_name in proc.name():
                pid = proc.pid
        if 'MAA.exe' not in [x.name() for x in psutil.process_iter()]:
            print('maa not start')
            maa = 1

        if maa == 1:
            maa = 0
            print('start maa')
            subprocess.Popen(['Y:\maa\MAA.exe'])

        pidtime = process_uptime.getuptime(pid)
        print(pidtime)
        if pidtime > 3600:
            print('kill')
            subprocess.Popen(['taskkill',r'/FI','''IMAGENAME eq nox*'''],shell=1)
            subprocess.Popen(['taskkill',r'/FI','''IMAGENAME eq MAA*'''],shell=1)
    except:
        print ('err')


```
由于每日长草时间小于1小时，如果监测模拟器运行超过1小时就全干掉重新开启maa，这样就不用傻等着了
