### ISSUE TITLE
MAA现有的多账号处理方式不太便捷

### ISSUE THREAD

**Issue by Yingge02** [MaaAssistantArknights/MaaAssistantArknights#6545]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现有的MAA解决两个以上多账号的方法是直接复制MAA本体外加多个模拟器本体，这种处理方法在之前明日方舟没有比较便捷的账号切换功能时确实比一次次的输入账号更加方便，但现在明日方舟已经加入了更快捷的账号切换功能，旧方法造成相当大的磁盘空间占用，换来的便捷程度却并不如在单个模拟器内直接切换账号。

### 有什么好的想法？

希望在单个MAA界面中管理多个用户配置，可以以类似标签页的形式进行呈现。用户可以自行添加新的标签页以实现多个账号的配置。这样既可以像旧有方案一样多开模拟器同时处理多个账号，也可以在手动更换游戏账号后更便捷的切换到对应账户的配置执行。

### 其他内容

在写完之后才发现现在已经加入了账号切换功能，但仅限于两个账号的切换。不如直接把账号自动切换部分直接独立出来，以切换账户对应标签页的形式进行切换，这样还可以解决不同账户使用不同基建排班方案的问题。

**Comment by status102** [comment]
直接多做一份配置就能解决你的问题

**Comment by ABA2396** [comment]
设置-切换配置

**Comment by Yingge02** [comment]
好家伙，我基本每次更新日志都看就是没注意到什么时候加的……

**Comment by Yingge02** [comment]
但是我还是觉得做成可以热切换的标签页放在首页比较快捷……不过实施起来可能有一些难度？

**Comment by status102** [comment]
直接用启动参数切配置更方便

**Comment by status102** [comment]
直接用启动参数切配置更方便
