### ISSUE TITLE
肉鸽模式满钱后烧不了水

### ISSUE THREAD

**Issue by pandorabeats** [MaaAssistantArknights/MaaAssistantArknights#6548]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

999钱之后烧水到商店就自动结束了，不会往下一层走了。

### 有什么好的想法？

一个是改进这个，另一个是希望可以自己选择难度，比如像有的人就想在难度10刷分队章，方便凹直升啥的

**Comment by T-Chaos** [comment]
取消勾选【储备源石锭达到上限时停止】试试
