### ISSUE TITLE
自动战斗中战斗列表里拖拽更改顺序时会崩溃

### ISSUE THREAD

**Issue by s-yh-china** [MaaAssistantArknights/MaaAssistantArknights#6550]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

尝试把一个任务拖拽来改变顺序，然后就崩溃了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12732518/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12732519/gui.log)

**Comment by status102** [comment]
b2f9f258f1cb949a13a518a91035164d4bfdfe30
