### ISSUE TITLE
可能无法正常识别先行一步节点

### ISSUE THREAD

**Issue by Xanadium** [MaaAssistantArknights/MaaAssistantArknights#6551]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽在道中选择先行一步节点时会在派遣干员界面挂机然后直接重开

### 日志文件

2023-09-27 09:12:51
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12733750/debug.zip)

**Comment by Xanadium** [comment]
使用的模拟器是雷电

**Comment by HoshinoAyako** [comment]
手动解决方法移步：https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6460

**Comment by ETOgaosion** [comment]
> 手动解决方法移步：#6460

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6460中说的是探寻前路，是直接改这个词条吗，还是再加一个先行一步

**Comment by Constrat** [comment]
Just modify option_num exactly as you see from
- #6940
