### ISSUE TITLE
外部通知使用SMTP配置时完成后如果选择退出MAA发不出邮件

### ISSUE THREAD

**Issue by Mo1moYi** [MaaAssistantArknights/MaaAssistantArknights#6553]

**Comment by Mo1moYi** [comment]
也不是什么大事就是了，毕竟好像很少人用这个功能，网上找不到教程，就在这里提一下吧。
server chan倒是没问题

**Comment by ZGLinus** [comment]
有一个间接实现的办法，使用外部脚本退出MAA。因为脚本执行在外部通知前面，所以需要两个脚本，一个给MAA调用，一个退出MAA

给MAA调用，也就是填入连接设置里面的结束后脚本的bat脚本这样行
```bat
start maa_off.bat
exit 0
```
结束MAA，也就是上面的`maa_off.bat`，这样写
```bat
timeout /T 3
taskkill.exe /f /im MAA.exe 2>&1 1>null
```

我测试是没有问题的，不过如果多开MAA，所有MAA进程都会退出。
