### ISSUE TITLE
maa打开后没反应有解决方法吗

### ISSUE THREAD

**Issue by Mustdoing** [MaaAssistantArknights/MaaAssistantArknights#6554]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa打开后没反应，界面不弹，错误日志也没，一看任务管理器就是maa自动挂起后关闭。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12734730/gui.log)

[Uploading asst.7z…]()

### 还有别的吗？

我这里找到的解决方法是：将maa所在的文件夹将resource文件夹移除，然后打开maa，等待maa的ui界面启动后关闭maa，然后重新将resource文件夹放回原来的位置再打开maa就能打开ui界面了

**Comment by zzyyyl** [comment]
俩日志都没传上来（
顺便，如果版本 <= v4.23.3 的话，更新到最新版试试
