### ISSUE TITLE
肉鸽助战招募干员会一直卡住并且手动确认干员后会放弃探索

### ISSUE THREAD

**Issue by jzhan183** [MaaAssistantArknights/MaaAssistantArknights#6556]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽设定了刷等级百嘉开并且也定了可以助战&可以借非好友干员，MAA识别出了百嘉也借了，但是就卡在干员展示界面没有后续的动作了，我人为点了一下结果系统直接放弃本次探索了

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12735636/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12735638/asst.log)

### 还有别的吗？

mumu模拟器，版本号4.24.0

**Comment by jzhan183** [comment]
并且如果我已经选好了三个干员再开启MAA也会放弃探索

**Comment by mm317670** [comment]
模拟器分辨率调720看看

**Comment by HoshinoAyako** [comment]
这个已经在4.24修了。你确定一下版本是不是最新的

**Comment by MistEO** [comment]
@Lancarus _(:з」∠)_

**Comment by Lancarus** [comment]
> @Lancarus _(:з」∠)_

这我也不知道为啥啊

**Comment by SamZhou-2019** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/53434814/d1387d8d-bc37-4461-a6a0-eaf36f4e0120)
可以试一下更改触控设置：**设置-连接设置-触控设置**
我之前也遇到了同样的问题（甚至更严重，会选择我完全没有练过的干员然后第一关都过不去，或者直接放弃招募），然后我改成了MaaTouch，问题解决了

**Comment by Tythla** [comment]
> ![image](https://user-images.githubusercontent.com/53434814/271807457-d1387d8d-bc37-4461-a6a0-eaf36f4e0120.png) 可以试一下更改触控设置：**设置-连接设置-触控设置** 我之前也遇到了同样的问题（甚至更严重，会选择我完全没有练过的干员然后第一关都过不去，或者直接放弃招募），然后我改成了MaaTouch，问题解决了

MaaTouch和MultiTouch都没有用，表现和主楼完全一致，为4.24版本

**Comment by zzyyyl** [comment]
各位遇到的问题是不是只有助战招募才有？

**Comment by jzhan183** [comment]
是的是的

**Comment by jzhan183** [comment]
谢谢！我试试看
