### ISSUE TITLE
萨米肉鸽MAA无法使用先行一步

### ISSUE THREAD

**Issue by jzhan183** [MaaAssistantArknights/MaaAssistantArknights#6558]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

进入先行一步节点时会卡住不动，人为操作后恢复正常
版本4.24，mumu模拟器

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12737697/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12737700/asst.log)

**Comment by HoshinoAyako** [comment]
手动解决方法移步：https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6460

**Comment by broken-paint** [comment]
duplicate of #6551
