### ISSUE TITLE
肉鸽

### ISSUE THREAD

**Issue by y7desu** [MaaAssistantArknights/MaaAssistantArknights#6564]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

棘刺静二后，总是是不是点一技能，而不是使用三技能

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12740233/gui.log)

**Comment by MistEO** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/93cedcb3-9086-4e72-8d4c-2895b4e63dc0)
