### ISSUE TITLE
理智回满预计时间计算错误问题

### ISSUE THREAD

**Issue by CheungChingYin** [MaaAssistantArknights/MaaAssistantArknights#6568]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

版本号
v4.24.0-rc.1.d030.g83b0206f8

MAA在完成任务后会提供理智回满时间，但是在体力不满的情况下，提示在0h 0m后回满，一开始以为是偶然识别错误问题，但实际上这个问题已经出现2~3次。

### 日志文件

时间开始在 `09-28 09:54:06` ~ `09-28 10:13:28` 结束

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12744883/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12744885/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/20316736/0af72b77-811f-4680-bedc-832219b9c8cc)

**Comment by ABA2396** [comment]
更新

**Comment by zzyyyl** [comment]
`v4.24.0` fixed
