### ISSUE TITLE
更新WSA后MAA无法正常工作

### ISSUE THREAD

**Issue by cglcv** [MaaAssistantArknights/MaaAssistantArknights#657]
类似于#578，但即使是WSA在全屏模式下MAA也无法正常工作，看日志个人感觉确实是OCR识别不出来了
版本3.9.0.beta8
屏幕截图：
![屏幕截图(47)](https://user-images.githubusercontent.com/35825310/171195385-589db721-1cf5-4667-b9d0-cf2e8bfa0fd7.png)

模拟器内截图：
![1](https://user-images.githubusercontent.com/35825310/171195428-edf5e7af-12fc-428c-b66c-825aff05f12d.png)

日志：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8805954/asst.log)

~实在不行我回退旧版本WSA了~

**Comment by cglcv** [comment]
草，一通操作之后全屏下正常了，不知道是什么bug……

**Comment by Rainwolfai** [comment]
问题来了，3:2的屏幕怎么办
