### ISSUE TITLE
使用蓝叠模拟器多开自动链接配置不生效，以管理员模式启动maa才生效

### ISSUE THREAD

**Issue by Cloudwisever** [MaaAssistantArknights/MaaAssistantArknights#6570]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

环境：windows11 maa version：MAA-v4.24.0-win-x64

遇到的问题，调查以及后续部分解决的过程：
按照操作指南的[指定 Bluestacks.Config.Keyword](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E6%8C%87%E5%AE%9A-bluestacks-config-keyword)部分进行了配置，但是自动链接仍然不生效。
gui.json:
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/33148017/ca8ef2e0-c4e6-499d-85b6-01426d522c5d)
> 
      "Bluestacks.Config.Path": "D:\\Program Files (x86)\\BlueStacks_nxt_cn\\bluestacks.conf",
      "Bluestacks.Config.Keyword": "bst.instance.Nougat64.status.adb_port",
去检查了bluestacks.conf中的内容，可以看到Nougat64的配置没问题，按理可以读取到adb_port
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/33148017/5bfdb9fa-adcf-4b9a-820b-4aae684db166)

但是目前日志看起来一开始尝试的AsstConnect方法中address为空，看代码这应该代表前面自动获取hvperV的TryToSetBlueStacksHyperVAddress这部分逻辑没能拿到对应的地址。

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/33148017/5f0c8fe8-374f-40b1-b792-32ceec3cbe87)
目前怀疑是前面这个拒绝访问导致的，但是不清楚这个是读取哪个文件时的错误。怀疑是bluestacks.conf

使用管理员模式开启maa，就可以正常连接了

想请教下
1. 为什么非管理员权限就会拒绝访问？看bluestacks.conf的文件信息，应该所有组都有读取的权限（见截图）
2. 如果不想每次启动maa都以管理员方式，这个问题有什么可能的解决方案？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12745265/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12745274/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/33148017/ca8ef2e0-c4e6-499d-85b6-01426d522c5d)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/33148017/5f0c8fe8-374f-40b1-b792-32ceec3cbe87)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/33148017/285cd19d-3b8d-4af9-9c6f-31fc094622e6)

**Comment by ABA2396** [comment]
1. Hyper-V是要管理员权限的，所以蓝叠的Hyper-V版本也是管理员权限启动的，maa不用管理员启动的话是访问不了管理员权限启动的蓝叠的信息。
2. 右键MAA.exe-属性-兼容性-以管理员身份运行此程序
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/990a1e82-5713-43c1-a249-001b42bb68c3)

**Comment by zzyyyl** [comment]
不想管理员启动 MAA 可以换模拟器（x
