### ISSUE TITLE
肉鸽新增购买或选择指定藏品的建议

### ISSUE THREAD

**Issue by ZJHeht2000** [MaaAssistantArknights/MaaAssistantArknights#6586]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

本人是入坑半年的萌新，比较喜欢玩肉鸽，是全藏品收集党。希望maa能新增获取指定藏品的功能。

### 有什么好的想法？

在水月肉鸽，有刷新商店找指路鳞的功能。请问是否可以进行泛化，在每个肉鸽中参考获取信用及购物的高级设置中的优先购买功能，让玩家指定数种藏品，若商店中出现则优先购买，没有则优先刷新一次商店，仍然没有再进行存钱等后续操作。
如果这个功能可行，还有两个优化建议。一是若源石锭不够则取钱进行购买。二是在以打尽可能多层数策略开局时，战斗结束后若可二选一或三选一藏品，优先选择指定藏品。
当然，即使能实现基础功能也会很满意，希望大佬能帮忙试着做一下。

**Comment by Lancarus** [comment]
duplicate of #6367
