### ISSUE TITLE
刷理智指定材料沒有在達到指定的個數後停止

### ISSUE THREAD

**Issue by PowwerTW** [MaaAssistantArknights/MaaAssistantArknights#6587]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

預想刷到6個狙擊晶片後會停止，但是沒有停止而是將所有理智用完
附上LOG，請幫忙查看謝謝

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12773477/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12773478/asst.log)

### 截图

![MAA (Default) - v4 24 0 - 敘拉古人 - 藍疊模擬器 (127 0 0 1_5555) - 繁中服 (txwy) 2023_9_30 上午 10_36_31](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131727274/7ac0411f-da2c-4149-b3b1-5bf3c913d4fc)
![MAA (Default) - v4 24 0 - 敘拉古人 - 藍疊模擬器 (127 0 0 1_5555) - 繁中服 (txwy) 2023_9_30 上午 10_40_39](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131727274/c49679f5-314d-460a-ab42-ddc081d4dbcc)

**Comment by ABA2396** [comment]
这四个都是短路开关，任意一个达到了都停止，你要把吃药也选上，没理智又不吃药没理智就结束了。

**Comment by PowwerTW** [comment]
並非這個問題 是已設定了達到6個狙擊晶片後停止
但看右邊紀錄，都已經打到了15個晶片了，還是一直執行，一直到最後沒理智停止

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/d012deb4-750d-45f4-8e1d-21955aeeb2da)

**Comment by PowwerTW** [comment]
好的 只是我以為指定材料在刷關卡的途中，只要達到數量就會停止
而不用管關卡是主要還是備選
畢竟現在設定主要是剿滅，沒有剿滅就跳到備選刷其他關是最方便的設定

**Comment by ABA2396** [comment]
正常来说到了指定数量就停了。备选关卡的逻辑是进第一个开放的关卡，但是剿灭是全天开放的，所以选了剿灭的话进的肯定是剿灭，但剿灭打完了的话会报错。按照原来的逻辑的话剿灭报错了任务就结束了，也不会去后面的备选关卡。后来加了个要是关卡是剿灭但任务失败的话会尝试进下一个开放的关卡，但是用理智药、源石、指定次数和材料这些设置就没用了

**Comment by zzyyyl** [comment]
是不是应该把这些设置同步给备选关卡？

**Comment by ABA2396** [comment]
> 是不是应该把这些设置同步给备选关卡？

但你也不能确认那些是要同步的啊，我看了下之前的写法，剿灭不管是正常完成还是报错都是会进备选的，如果你就想打五把剿灭，但实际上还是会进五次下一个开放的关卡

**Comment by PowwerTW** [comment]
是不是可以不用那麼複雜，關卡歸關卡，短路開關歸短路開關
關卡就 關卡1 關卡2 關卡3 (也就是主要 備選1 備選2)
若前一個無法執行(如缺理智、或剿滅已完成沒有按鈕了) 
就選擇下一個關卡 依此類推到最後一個關卡3

而短路開關(吃藥和吃石)滿足次數後就不吃
一直刷到滿足次數或指定材料個數或沒理智就停止

但你說的應該不會有人已滿1800合成玉後還是要再打剿滅

**Comment by ABA2396** [comment]
ui只能知道今天开放的关卡（根据星期），而不知道游戏内具体发生了什么（是否打完了剿灭，有没有入口，是否卡在哪个界面），所以传给core的任务就是第一个开放的关卡加上对应的参数。
但是因为剿灭比较特殊，所以在剿灭关卡后加上了下一个开放的关卡，但是ui是不会知道剿灭都没打完的，这个参数到底是给剿灭还是后面的关卡是不明确的。举个特殊点的例子，比如说有人碎石去打剿灭，如果把这个参数给下一个关卡的话，就会碎两颗了。
现在剿灭有扫荡了，其实按照我的想法都是想去的剿灭这个选项的

**Comment by ABA2396** [comment]
core和ui是分开的，所有的任务是一个任务链，刷理智后面有任务的话是不能在运行的时候再往中间插任务的，就算是解决了参数这个问题，添加任务也只能在运行前一起加，或者添加到当前任务链的最后面，这样就太奇怪了。

**Comment by ABA2396** [comment]
现在在重构配置，之后大概能出一个新增任务（就是左边的任务栏里有多个刷理智），这样估计就可以了。现在要用的话可以看看 MaaX，就是这样的实现方式。
