### ISSUE TITLE
莫名其妙跳转森空岛

### ISSUE THREAD

**Issue by WSMTBG** [MaaAssistantArknights/MaaAssistantArknights#6588]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

脚本栏我都不填了还给我跳到森空岛，然后就大片截图失败，没法正常挂机
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/e39601e8-7b3b-4f2e-90fd-1629c0da0ce6)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/cc73fc14-d550-4073-bd70-8af114017198)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12774058/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12774060/gui.log)

### 截图

![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/54487463-dc26-4dd3-93a1-ecfdba422378)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/34969ebd-ffca-442c-9bab-83cd41d54ee2)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/cca459a9-d9ad-40f3-8f66-1f36d0219fe0)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/d60208c6-5391-43c4-8012-f95c86e19663)

**Comment by Constrat** [comment]
First suggestion: change MaaTouch to MiniTouch. I've noticed that sometimes MaaTouch is slower than Minitouch.

**Comment by ABA2396** [comment]
看日志倒不是因为打开了森空岛，是因为游戏在掉落界面点击跳过的时候闪退了，而森空岛的图标刚好就在那个点击的位置就打开了森空岛
```
[2023-09-30 13:20:52.280][TRC][Px4c30][Tx8c30] maatouch click: (1722, 67)
```
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/28314014-79f6-4200-a7d0-65ca2439e709)
```
[2023-09-30 13:20:53.306][INF][Px4c30][Tx8c30] Call ` C:\Program Files\BlueStacks_nxt\HD-Adb.exe -s 127.0.0.1:5555 exec-out "screencap | gzip -1" ` ret 0 , cost 424 ms , stdout size: 40423 , socket size: 0
[2023-09-30 13:20:53.323][ERR][Px4c30][Tx8c30] Size from image header 1080 1920 does not match the size of screen 1920 1080
```
之后就一直报错了
