### ISSUE TITLE
建议获取信用与购物中打OF-1赚信用时选人能固定在4编队选

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#6594]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

每次编队时看见4个编队中有3个单德狗都很难绷住

**Comment by zzyyyl** [comment]
duplicate of #4624
