### ISSUE TITLE
“仓库识别”不出双极纳米片

### ISSUE THREAD

**Issue by Black1312** [MaaAssistantArknights/MaaAssistantArknights#6598]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

仓库识别功能识别不到纳米片，其他材料正常
日志时间：9月30日，下午九点左右

### 日志文件

[bug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12774729/bug.zip)

### 截图

![d2d1e5f8ef45295fa6b74b91e64078d9](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64343218/9631177e-ad58-4064-9c2e-1be435d93c19)
![dfebff44e3dcd018db8647af30c3d245](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64343218/c2add0a1-28c9-4b2e-a4e8-70a63dd35c3c)

### 还有别的吗？

MAA：4.24
蓝叠国际模拟器

**Comment by horror-proton** [comment]
好像 #5586 也是双极纳米片数量为 2 的时候识别成了 "2/", 我看看怎么搞 🤔
