### ISSUE TITLE
关于更新的建议

### ISSUE THREAD

**Issue by LengmoAngel** [MaaAssistantArknights/MaaAssistantArknights#660]
### 内容：

GitHub的releases的分发渠道实在是太慢了 基本速度在10k-30k/s速度实在不佳，是否ui可以取消关闭强制勾选
建议加入手动按钮 “立即更新” 我不是很明白C#写的ui 所以不敢轻易进行改动 没发用爱发电了 只能提出此commit了

### 建议改进措施：

github pages的速度可能比release快 或者考虑国内的gitee等作为备选的一些分发渠道，或者考虑osdn等开源软件分发渠道作为备选项，可以提高速度，国内也有tuna等镜像提高osdn速度 虽然可能只是一天一同步

**Comment by LengmoAngel** [comment]
> 



> gitee 下载 release 会随缘需要验证码，目前已经用了 fastgit 了但这货同步的很慢所以大部分时候还是走 github的。
> 
> 建议用代理下。
> 
> 我们已经在搭自己的服务器了，但是目前进展比较咕（

linux运维和后端我略知一二 前端就不是很懂了 
如果有需要 我可以来帮忙（

**Comment by MistEO** [comment]
好呀，快来 [发电](https://jq.qq.com/?_wv=1027&k=9vTNeziR) ！✿✿ヽ(°▽°)ノ✿
