### ISSUE TITLE
蓝叠模拟器多开ADB连接问题

### ISSUE THREAD

**Issue by cayww** [MaaAssistantArknights/MaaAssistantArknights#6604]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

通过maa官网的文档进行对gui.json里添加对应字段后重新进入maa后会删除新添加的字段

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12776068/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12776069/gui.log)

### 还有别的吗？

蓝叠模拟器国际版 WIndows10专业版 https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7-hyper-v

**Comment by ABA2396** [comment]
1. 关了maa再改
2. 注意使用英文标点和格式

**Comment by cayww** [comment]
保存前(下面两张图)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76549651/387bef77-16d2-4f7d-b548-9a98f0f7ebcb)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76549651/a089d3ee-ea0f-49a2-9503-572313d0ae20)
保存后(已经保存成功了，后台没有MAA运行，再次进入json文件的样子，一张图)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76549651/5eeefa7e-77c1-41f7-86ea-65300fe61c38)
这是启动MAA后（启动MAA后进入json文件的样子，两张图）
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76549651/c5eafe14-c6b7-4dd7-bb91-6ff1a879f278)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76549651/7c752e8b-77f5-4761-a28c-2658fcadd053)

**Comment by ABA2396** [comment]
发下改完的json看看

**Comment by cayww** [comment]
[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12776247/gui.zip)
219行

**Comment by ABA2396** [comment]
键名重复了，415行把空字符串改了就好了

**Comment by cayww** [comment]
原来是这个原因

**Comment by MTKmin** [comment]
你们是英雄！！！
我没在说假话 我说我怎么每次新增都会被删除  试过了好多次 甚至以为是添加的方式不对  再不行我也要提交BUG了QAQ
[Snipaste_2023-10-03_15-28-34](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/100497697/2291553a-52a6-43eb-94b3-5c82f5f234c5)
