### ISSUE TITLE
夜间/银凇首页主题不识别 | New Dark Mode not Recognized

### ISSUE THREAD

**Issue by pingplug** [MaaAssistantArknights/MaaAssistantArknights#6605]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

首页换成暗色的夜间主题后MAA会卡在主页不动

### 日志文件

之前几把都是在肉鸽界面内启动，没有问题；11:30分左右从主页开始任务，四分钟后发现不对手动点入终端。
[pingplug.tar.gz](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12776077/pingplug.tar.gz)

**Comment by ABA2396** [comment]
是的

**Comment by Bugouyou** [comment]
肉鸽新主题【银凇】也识别不了

**Comment by Lancarus** [comment]
为啥要pin，等更新就好了。。。
又不是影响使用的bug。难道每次游戏更新了有人跳出来叫为什么没适配，就要连夜去适配？

**Comment by Constrat** [comment]
I have the templates ready. But I need to understand if we can use #6608
