### ISSUE TITLE
입력 문자열의 형식이 잘못되었습니다

### ISSUE THREAD

**Issue by ilustrated** [MaaAssistantArknights/MaaAssistantArknights#6606]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

maa를 뮤뮤를 통해 실행하려 하면 입력 문자열의 형식이 잘못되었다며
예기치못한 오류가 발생하였다 나오며 실행이 되지 않습니다

### Log files

System.FormatException: 입력 문자열의 형식이 잘못되었습니다.
   위치: System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   위치: System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   위치: MaaWpfGui.Main.AsstProxy.IfPortEstablished(String address)
   위치: MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
   위치: System.Threading.Tasks.Task`1.InnerInvoke()
   위치: System.Threading.Tasks.Task.Execute()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<ConnectToEmulator>d__74.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<LinkStart>d__75.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146612586/6190d57b-09c1-4478-90d4-2569701dc7ef)

**Comment by zzyyyl** [comment]
MuMu Emulator?

**Comment by ilustrated** [comment]
yes


2023년 10월 1일 (일) 오후 2:38, zzyyyl ***@***.***>님이 작성:

**Comment by zzyyyl** [comment]
`gui.log` 및 `asst.log`를 제공할 수 있나요?

Can you provide `gui.log` and `asst.log`?

**Comment by ilustrated** [comment]
where can i see that?


2023년 10월 1일 (일) 오후 2:42, zzyyyl ***@***.***>님이 작성:

**Comment by zzyyyl** [comment]
`debug/` in MAA folder

**Comment by ilustrated** [comment]
here it is

2023년 10월 1일 (일) 오후 2:43, zzyyyl ***@***.***>님이 작성:

**Comment by ilustrated** [comment]
yes. you need gui.log and asst.log too?

2023년 10월 1일 (일) 오후 3:10, MistEO ***@***.***>님이 작성:
