### ISSUE TITLE
cmd中adb可以连接，软件中连接失败

### ISSUE THREAD

**Issue by SunshineboyZj** [MaaAssistantArknights/MaaAssistantArknights#662]
![image](https://user-images.githubusercontent.com/81549837/171243430-5acede78-218f-4f2e-b6fe-dc289ff61359.png)
![image](https://user-images.githubusercontent.com/81549837/171246768-3fb5f702-333b-450e-89ce-c83395d96cc1.png)
![image](https://user-images.githubusercontent.com/81549837/171247764-ec363a92-729d-4efb-ad45-1c9f60276ab9.png)

**Comment by MistEO** [comment]
雷电么，其实文档中有写的。。

**Comment by SunshineboyZj** [comment]
> 雷电么，其实文档中有写的。。

雷神，和雷电有千丝万缕的关系
