### ISSUE TITLE
2023.10.1下午更新的内测版启动后直接闪退

### ISSUE THREAD

**Issue by Orirock** [MaaAssistantArknights/MaaAssistantArknights#6621]
### 在提问之前...

- [ ] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12777016/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12777017/asst.log)

### 截图

![捕获](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111337161/9bb6d4b0-272a-438b-8661-7d7f8ae6f208)

**Comment by zzyyyl** [comment]
duplicate of #6610
