### ISSUE TITLE
版本自动更新导致启动问题

### ISSUE THREAD

**Issue by QLHW** [MaaAssistantArknights/MaaAssistantArknights#6622]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Maa内测版本自动更新后出现错误

### 日志文件

MAA 遇到了问题
“MaaWpfGui.Configuration.ConfigFactory”的类型初始值设定项引发异常。
未能加载文件或程序集“System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
解决方案
请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.TypeInitializationException: “MaaWpfGui.Configuration.ConfigFactory”的类型初始值设定项引发异常。 ---> System.IO.FileLoadException: 未能加载文件或程序集“System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
   在 ObservableCollections.ObservableDictionary`2.set_Item(TKey key, TValue value)
   在 MaaWpfGui.Configuration.RootConfig.set_CurrentConfig(SpecificConfig value)
   在 MaaWpfGui.Configuration.ConfigFactory.<>c.<.cctor>b__18_0()
   在 System.Lazy`1.CreateValue()
   在 System.Lazy`1.LazyInitValue()
   在 MaaWpfGui.Configuration.ConfigFactory..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.SwitchDarkMode()
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   在 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   在 Stylet.BootstrapperBase.Start(String[] args)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Constrat** [comment]
Duplicate of #6610
