### ISSUE TITLE
使用新UI时无法刷1-7

### ISSUE THREAD

**Issue by byht11** [MaaAssistantArknights/MaaAssistantArknights#6627]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我不确定是不是只有1-7，夜晚没试过，但是银松主题无法识别

### 日志文件

[Uploading MAA.lnk…]()

### 截图

![Uploading KJE}N6EMCT5B2J0W8F2ZT$C.png…]()

**Comment by zzyyyl** [comment]
duplicate of #6605
