### ISSUE TITLE
日服主线导航失效

### ISSUE THREAD

**Issue by MejiroSilence** [MaaAssistantArknights/MaaAssistantArknights#6629]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷取主线1-7卡在如图所示界面
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59904337/9ca57580-5509-4829-a48b-3ae43febfebc)
查看log后发现一直在识别01@SwipeLeftToEpisode以及01@EnterEpisode
期待的识别结果为EPISODE03，实际识别为EPISODE 03
对比国服运行结果，也是识别为EPISODE 03，但是能正确进行导航。
查看task,json 作为basetask的EpisodeOcrReplace中确实有定义
```
        "ocrReplace": [
            [
                " ",
                ""
            ]
        ]
```
但很奇怪地在日服运行时该替换规则未生效，识别失败

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12777365/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12777366/gui.log)

### 还有别的吗？

蓝叠5
windows11

**Comment by zzyyyl** [comment]
这是 baseTask 的实现问题，#6478 合了之后已经修了，但还没发版

**Comment by zzyyyl** [comment]
`v4.24.1-alpha.1.d175.gaaafed51a` fixed

**Comment by MejiroSilence** [comment]
试了下还是不行, 其实感觉可能不太属于 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6478 的情况？
因为在JP的文件里并没有对这几个任务的定义

**Comment by ABA2396** [comment]
再来个日志看看

**Comment by MejiroSilence** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12865401/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12865403/gui.log)
