### ISSUE TITLE
自动战斗一点开始就闪退

### ISSUE THREAD

**Issue by HMZyueshen** [MaaAssistantArknights/MaaAssistantArknights#663]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8808160/asst.log)

**Comment by MistEO** [comment]
这个作业 json 文件也一起发一下吧~

**Comment by HMZyueshen** [comment]
没事了，之前不知道是bug还是怎么回事，json文件里没有doc
