### ISSUE TITLE
MMA打不開

### ISSUE THREAD

**Issue by eason101036** [MaaAssistantArknights/MaaAssistantArknights#6631]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

一打開就跳出這個，想請大老幫忙看一夏是什麼問題

MAA 遇到了問題
'MaaWpfGui.Configuration.ConfigFactory' 的類型初始設定式發生例外狀況。
Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
解決方法
請參考文件: 常見問題 - 閃退 進行操作。
詳細資訊
System.TypeInitializationException: 'MaaWpfGui.Configuration.ConfigFactory' 的類型初始設定式發生例外狀況。 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   於 ObservableCollections.ObservableDictionary`2.set_Item(TKey key, TValue value)
   於 MaaWpfGui.Configuration.RootConfig.set_CurrentConfig(SpecificConfig value)
   於 MaaWpfGui.Configuration.ConfigFactory.<>c.<.cctor>b__18_0()
   於 System.Lazy`1.CreateValue()
   於 System.Lazy`1.LazyInitValue()
   於 MaaWpfGui.Configuration.ConfigFactory..cctor()
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 MaaWpfGui.ViewModels.UI.SettingsViewModel.SwitchDarkMode()
   於 MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   於 lambda_method(Closure , IRegistrationContext )
   於 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   於 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   於 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   於 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   於 StyletIoC.Internal.Container.Get[T](String key)
   於 MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   於 Stylet.BootstrapperBase.Start(String[] args)
   於 System.Windows.Application.OnStartup(StartupEventArgs e)
   於 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   於 System.Windows.Application.<.ctor>b__1_0(Object unused)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12777390/asst.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12777391/asst.log)
2023-10-01 22:38:52.564

**Comment by zzyyyl** [comment]
Refer to https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6610#issuecomment-1742047409

**Comment by Constrat** [comment]
Duplicate of #6610
