### ISSUE TITLE
UU加速器疑似与MAA冲突

### ISSUE THREAD

**Issue by snowonfinger** [MaaAssistantArknights/MaaAssistantArknights#6636]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启动MAA与模拟器后，启动UU加速器会直接导致模拟器与MAA断开连接

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12778660/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12778661/gui.log)
时间：10.2早八

### 还有别的吗？

模拟器：Mumu12（V3.5.15）
系统：Windows11专业版（22H2，22624.1755）

**Comment by snowonfinger** [comment]
追加：若先启动UU加速器再启动MAA则不会发生冲突

**Comment by ABA2396** [comment]
是的，你得和uu说

**Comment by ntgmc** [comment]
Duplicate of #1010 #2530 #3107 #3201 #3648 #5528 #5601
