### ISSUE TITLE
mumu12模拟器 startup出现错误后其余功能均无法正常工作

### ISSUE THREAD

**Issue by Myrimirai** [MaaAssistantArknights/MaaAssistantArknights#6638]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

- maa与模拟器似乎链接正常，但startup无法执行，**除了自动公招**以外的操作均无法正常工作
- 尝试重新解压一份maa，问题没有解决，仍然是startup出现错误后无法继续工作
- 今天早上自动更新测试版后出现该问题，但手动回滚到正式版后问题仍存在
- adb链接端口正确

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12779746/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12779749/gui.log)

### 截图

<img width="598" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115166593/5fa88ec7-1a10-47fc-999d-fb3e131aff56">

### 还有别的吗？

mumu12模拟器
Windows 11 Pro 22H2

**Comment by zzyyyl** [comment]
你是不是换主题了

**Comment by Myrimirai** [comment]
> 你是不是换主题了

在昨晚到今天早上这个时间段我没有做出什么更改，到昨晚为止还可以正常使用

**Comment by Myrimirai** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781412/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781413/gui.log)
重新装了一遍，还是一样的情况
<img width="601" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115166593/238a1644-c283-4d8a-9bc9-77e12f7142a7">
一直停在主界面没有动作

**Comment by Myrimirai** [comment]
用另一台电脑也出现同样的情况，是maa更新到4.24以后与mumu12产生了兼容性问题吗？

**Comment by Myrimirai** [comment]
这里附上另一台设备的log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781551/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781552/gui.log)

**Comment by Myrimirai** [comment]
> 你是不是换主题了

了解了，应该是游戏内主题的问题
