### ISSUE TITLE
MAA 内测版(v4.24.1-alpha.11.d164.g37332ee0d) 运行时闪退

### ISSUE THREAD

**Issue by cubesky** [MaaAssistantArknights/MaaAssistantArknights#6639]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在内测版 v4.24.1-alpha.11.d164.g37332ee0d 运行基建换班时，会卡住一段时间后 MAA 闪退。

期间 MAA 会一直反复尝试点击基建右上角的蓝色通知选项但无法正确执行(会客室线索已满)

Update: MAA 在运行任何 Task 时，运行一段时间都会崩溃。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12780066/gui.log)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12780067/asst.log)

### 还有别的吗？

模拟器 Bluestack App Player 5.9.350.1035 N32

操作系统 Windows 11

**Comment by Mitsuha-LYB** [comment]
同遇到此类问题，模拟器为mumu12

**Comment by qianxuu** [comment]
同问题，蓝叠国际 pie hyper-v，同时自动识别模拟器/端口也识别不到了

**Comment by zzyyyl** [comment]
后面除基建外还遇到此问题是发日志，不用复读，谢谢
