### ISSUE TITLE
macOS MAA 自动肉鸽 萨米后期 闪退

### ISSUE THREAD

**Issue by FSPaul2498** [MaaAssistantArknights/MaaAssistantArknights#6641]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在macOS上使用MAA自动肉鸽萨米，玩到第三层后期，进入战斗后操作几秒便出现闪退，即使手动通过本关后，自行重启MAA冲击后续关卡，依然会在再次进入战斗后迅速闪退

### 日志文件

[asst.log归档.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12780353/asst.log.zip)
[MAA的问题报告.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12780366/MAA.log)

### 截图

<img width="1000" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35190475/40b7f7d0-f8d5-48ad-b261-35f344365e97">

### 还有别的吗？

Mac mini M2
macOS Sonoma 14.0
MAA v4.24.0（409）
Playcover mode

**Comment by zzyyyl** [comment]
#6241 
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/466be7766d6191fee2135d3e484062f9aad2c16c/src/MaaCore/Task/Roguelike/RoguelikeBattleTaskPlugin.cpp#L415-L426

asst::BattleHelper::retreat_oper 会导致 m_battlefield_opers 改变

**Comment by zzyyyl** [comment]
@AnnoyingFlowers

**Comment by VioletCoding** [comment]
这个问题什么时候发版？

**Comment by zzyyyl** [comment]
> 这个问题什么时候发版？

内测版：v4.24.1-alpha.1.d226.g9dd131517
