### ISSUE TITLE
在今天更新后MUMU12模拟器无法正常使用MAA

### ISSUE THREAD

**Issue by goyewell** [MaaAssistantArknights/MaaAssistantArknights#6643]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

能正常进行《开始唤醒》这一步，
但进入《基建换班》这一步时，
有时候会卡在基建界面不进行下一步，
有时候MAA会卡死然后闪退。
PS：今天上午的时候还是能正常运行MAA的。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12780653/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12780656/gui.log)

### 截图

![MAA不进行下一步](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124797583/8848e206-3eb4-4921-b9b0-579c65820970)

**Comment by Constrat** [comment]
- duplicate of #6639

**Comment by zzyyyl** [comment]
我看不懂基建的 analyzer 是怎么 cache 的，但总之是 cache 出了问题，等玛丽修 @MistEO
