### ISSUE TITLE
今天更新后清理智闪退

### ISSUE THREAD

**Issue by emptyailen** [MaaAssistantArknights/MaaAssistantArknights#6644]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新后每打完一次关，在识别掉落时就会闪退，今天两点多和四点多各发现好几次闪退

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12780899/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12780912/gui.log)

**Comment by Ptilopsis01** [comment]
同，我也出现了这个问题

**Comment by cccchen06** [comment]
加一，蓝叠5国际版也是。

**Comment by Am2333** [comment]
同闪退，MUMU12，打完一把1-7就会闪退

**Comment by zzyyyl** [comment]
`v4.24.1-alpha.1.d175.gaaafed51a` 正在打包，等半小时左右
