### ISSUE TITLE
基建换班异常

### ISSUE THREAD

**Issue by Ptilopsis01** [MaaAssistantArknights/MaaAssistantArknights#6645]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最新测试版本中maa在基建换班时，若右上角蓝标存在则会反复点击右上角蓝标而不继续进行下一步操作，导致无法正常完成换班

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781122/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781125/gui.log)

### 还有别的吗？

模拟器为mumu12

**Comment by joshua0blake** [comment]
基建换班这个是不是选干员会卡死？
要是这样的话那应该是mumu12的锅，我这两天也是这样，在基建点干员时有概率直接卡住

**Comment by shinozhu** [comment]
> 基建换班这个是不是选干员会卡死？ 要是这样的话那应该是mumu12的锅，我这两天也是这样，在基建点干员时有概率直接卡住

蓝叠5也出现这个问题了，而且同时也出现另一个清体力maa闪退的bug，所有bug都是今天测试版更新后出现的

**Comment by joshua0blake** [comment]
> > 基建换班这个是不是选干员会卡死？ 要是这样的话那应该是mumu12的锅，我这两天也是这样，在基建点干员时有概率直接卡住
> 
> 蓝叠5也出现这个问题了，而且同时也出现另一个清体力maa闪退的bug，所有bug都是今天测试版更新后出现的

可能是模拟器的问题？我这两天不用maa自己手动换班也会遇到这种卡住的情况

**Comment by zzyyyl** [comment]
`v4.24.1-alpha.1.d175.gaaafed51a` 正在打包，等半小时左右

**Comment by joshua0blake** [comment]
> > > > 基建换班这个是不是选干员会卡死？ 要是这样的话那应该是mumu12的锅，我这两天也是这样，在基建点干员时有概率直接卡住
> > > 
> > > 
> > > 蓝叠5也出现这个问题了，而且同时也出现另一个清体力maa闪退的bug，所有bug都是今天测试版更新后出现的
> > 
> > 
> > 可能是模拟器的问题？我这两天不用maa自己手动换班也会遇到这种卡住的情况
> 
> 我是雷电模拟器，也有同样的问题，狂点右上角的铃铛 [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781845/asst.log) [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781846/gui.log)
> 
> ![image](https://user-images.githubusercontent.com/87610169/271946031-b9985ad3-ceec-4f01-aecc-8ad200f91b35.png)

刚刚在手机点基建没啥问题，但我换到模拟器上多点几下立马卡住了

**Comment by zzyyyl** [comment]
更新！@joshua0blake

**Comment by joshua0blake** [comment]
> 更新！@joshua0blake

[问一下大佬你更新完后就不会卡基建了吗，我的还是会出现干员冲突 
[img](https://raw.githubusercontent.com/joshua0blake/1/main/QQ%E6%88%AA%E5%9B%BE20231011012104.png?token=GHSAT0AAAAAACIKYA6JKTBU3AOA2UJTGT5IZJFRNFA)
