### ISSUE TITLE
关于萨米肉鸽

### ISSUE THREAD

**Issue by RizukiJI** [MaaAssistantArknights/MaaAssistantArknights#6648]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选完干员直接停住了，不自动选择关卡

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781304/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781311/asst.log)

### 还有别的吗？

雷电模拟器，分辨率1280*720

**Comment by malthae** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781484/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781485/asst.log)
今天碰到同样的问题

**Comment by xxccpp** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781671/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781672/gui.log)
一样的问题 分辨率1280*720 dpi320
