### ISSUE TITLE
自定义基建换班异常

### ISSUE THREAD

**Issue by JavELinf61** [MaaAssistantArknights/MaaAssistantArknights#6649]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

执行自定义基建换班时，如果房间内前一班干员与后一班干员一致（如制造站中，断罪者、至简、食铁兽换为断罪者、至简、食铁兽），maa无法识别这三名正在工作中的干员。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781558/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12781560/gui.log)
10-02 17:43.32-17:45.07

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/107357586/52d9cec5-6bd2-41e5-9922-f088b2a691fb)
这三名干员就在最前面，可是无法识别。基建内其他房间也有这种情况。

**Comment by JavELinf61** [comment]
使用mumu12，2560x1440分辨率

**Comment by XingHaiHuShen** [comment]
> 使用mumu12，2560x1440分辨率

不行，我改成这个分辨率之后，甚至无法完成截图和进行操作
