### ISSUE TITLE
更换背景主题后maa不能识别

### ISSUE THREAD

**Issue by aknyzsd** [MaaAssistantArknights/MaaAssistantArknights#6651]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

近期更新的主题更换之后maa不能正确识别会在主界面报错并继续下一进程，（加一个对暗夜和萨米主题的识别应该就行了）

### 日志文件

抱歉，现在不在设备旁边没法提供

**Comment by zzyyyl** [comment]
`v4.24.1-alpha.1.d175.gaaafed51a`
