### ISSUE TITLE
基建换班异常

### ISSUE THREAD

**Issue by yfzj** [MaaAssistantArknights/MaaAssistantArknights#6652]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在基建换班的时候，领取完右上角的通知后，如果有干员疲劳，就会一直反复领取通知而不是进入换班环节。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12782150/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12782153/gui.log)

### 还有别的吗？

MuMu12 ，win11

**Comment by MobiusT** [comment]
我更新到alpha/v4.24.1-alpha.1.d175.gaaafed51a版本后重启模拟器及adb、maa进程后可以正常进入，但是基建部署依然和别的iss一样有选人问题

**Comment by zzyyyl** [comment]
try d183
