### ISSUE TITLE
更新最新版后萨米肉鸽中途会停止操作

### ISSUE THREAD

**Issue by SacribethGrass** [MaaAssistantArknights/MaaAssistantArknights#6653]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最新版本（目前为止）可以进行萨米肉鸽的第一局了（今天第一次更新的时候甚至开不了第一关），但依然再后续突然终止操作了，无法自动肉鸽。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12782178/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12782179/gui.log)

### 截图

<img width="632" alt="屏幕截图 2023-10-02 193315" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89343472/2f828dd9-3af8-4217-b08a-c8b7d34c30a3">
<img width="593" alt="屏幕截图 2023-10-02 193302" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/89343472/bda28d2a-1d40-4c88-ac21-2a335dd5997c">

### 还有别的吗？

模拟器为mumu12

**Comment by Lancarus** [comment]
duplicate of #6655

**Comment by zzyyyl** [comment]
更新 v4.24.1-alpha.1.d183.g5f106ab0a 试试

**Comment by Constrat** [comment]
- #6655 resolved
