### ISSUE TITLE
maa win10 闪退

### ISSUE THREAD

**Issue by Liudegloire** [MaaAssistantArknights/MaaAssistantArknights#6654]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷理智打完一关之后结算界面闪退

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12782195/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12782196/gui.log)

### 还有别的吗？

mumu12模拟器
win10系统
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39121540/5e066e16-4dd5-4893-8c16-75fedada1c23)

**Comment by cl296850295** [comment]
我也是，win11雷电模拟器也在闪退，刷一次1-7闪退一次，还以为电脑出问题了重启了几次

**Comment by 1035480524** [comment]
我也是，刷一次就闪退

**Comment by LiuShujushi** [comment]
我也是，mumu12模拟器

**Comment by cl296850295** [comment]
我换了稳定版能挂了，内测版等更新再看看吧

**Comment by huangqiabc4** [comment]
WIN11，同样闪退
也是结算界面闪退
还是剿灭的结算界面。。。

**Comment by haibara-brownie** [comment]
我也是，打一关红票就闪退了
