### ISSUE TITLE
MAA运行到一半出错

### ISSUE THREAD

**Issue by hijack114514** [MaaAssistantArknights/MaaAssistantArknights#6657]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用两个MAA，其中一个定时执行时fight事件运行到一半就出错，不过手动再运行一次又能正常运行，另一个一切正常

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12782774/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12782775/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142242356/9ad7da68-87a3-4440-ad88-e900f881d544)

### 还有别的吗？

cn蓝叠模拟器
win10系统
e52666v3  32g ddr3双通道 rx580显卡

**Comment by zzyyyl** [comment]
`v4.24.1-alpha.1.d183.g5f106ab0a` fixed
