### ISSUE TITLE
Alpha版运行过程中出错[v4.24.1-alpha.1.d175.gaaafed51a]

### ISSUE THREAD

**Issue by HisAtri** [MaaAssistantArknights/MaaAssistantArknights#6658]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

10.1 18:00最后一次挂机后出现错误并结束进程，此后手动启动，卡在刷理智结算界面

### 日志文件

[MeoAssistantArknights.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12783053/MeoAssistantArknights.zip)

### 还有别的吗？

使用此版本的包另行测试，问题复现。
模拟器为蓝叠

**Comment by zzyyyl** [comment]
`v4.24.1-alpha.1.d183.g5f106ab0a` fixed
