### ISSUE TITLE
设置/软件更新/版本号 控件增加点击复制当前版本号的功能

### ISSUE THREAD

**Issue by HisAtri** [MaaAssistantArknights/MaaAssistantArknights#6659]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有些时候需要提供具体的版本号，缺少一个可以复制版本号的渠道。

### 有什么好的想法？

设置/软件更新/版本号 控件点击后会显示彩蛋，其实可以加个行为，点击后将当前程序的版本号复制到剪贴板。这个功能应该挺有用的。~~___尤其是alpha版___~~。

**Comment by Constrat** [comment]
Since we are talking about touching Version Update GUI, is it possible to disable the Startup Update Check for DEBUG VERSION editions?
