### ISSUE TITLE
自动作战时游戏闪退-夜神模拟器

### ISSUE THREAD

**Issue by NeonLA** [MaaAssistantArknights/MaaAssistantArknights#666]
描述：最新版本助手在自动作战正常运作一定次数（18~19次）后游戏会自动闪退。

模拟器：夜神模拟器 7.0.2.6 

日期: 5/31/2022

Log文件：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8810077/asst.log)

截图：
![image](https://user-images.githubusercontent.com/50752627/171302085-18628ccd-53f4-4d44-a62a-60106f13c5f1.png)

**Comment by NeonLA** [comment]
补充：该问题是活动复刻开启后发现的，此时小助手还是上个版本。

**Comment by MistEO** [comment]
游戏闪退是游戏的问题。。

**Comment by NeonLA** [comment]
那只能看看游戏后续优化了_(:з」∠)_
