### ISSUE TITLE
UI Theme "Sync with OS" not working

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#6663]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Choosing "Sync with OS" does nothing.
I've noticed @Cryolitia d6d163d and @ABA2396 6c52650 did some modifications on something related to that logic. 

### Log files

.

### Screenshots

Sync with OS should be Dark Theme + Red accent color.

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/dfea379d-2bd6-4b35-b45b-96f904797eec)

**Comment by Constrat** [comment]
Win10 10.0.19045

**Comment by zzyyyl** [comment]
Win11 also

**Comment by Constrat** [comment]
Yes, I don't have the win11 build version iobme right now

**Comment by zzyyyl** [comment]
我记得最开始好像是可以的，切换几下 暗色 - 与系统同步 就失效了

**Comment by Cryolitia** [comment]
1. Check `Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme` in `Registry` and paste below.
2. Check `config\gui.new.json` and paste below.
3. Specify exactly which version of MAA you are using

Appreciate with honest.

**Comment by Constrat** [comment]
1. `0`
2. `config\gui.new.json` does not exist.
3. `d183.g5f106ab0a

**Comment by Cryolitia** [comment]
> 1. `0`
> 2. `config\gui.new.json` does not exist.
> 3. `d183.g5f106ab0a`

What about `gui.test.json` ?

**Comment by Constrat** [comment]
I've seen it only once. It disappeared and never reappeared after that.

**Comment by Constrat** [comment]
I have it. Wait a min

**Comment by Constrat** [comment]
```
{
  "Configurations": {
    "Default": {
      "GuiConfig": {
        "DarkMode": "Dark",
        "UseNotify": true
      }
    }
  },
  "Cur
```

**Comment by Cryolitia** [comment]
My apologies https://github.com/Cryolitia/MaaAssistantArknights/commit/0833cc1019681f21c377b12ba91fea0de7edfec0#diff-36c75f83140bc44df90233c9c18fa86d157ce94b19f15290a13b72dff0fa5e03L3260
