### ISSUE TITLE
WpfGui启动后，通知过多以及弹窗意义混乱

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#6666]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

1. 启动后更新游戏资源：
    - 是否有更新失败/异常检测
    - 更新进度、更新速度 不明
2. 更新游戏资源后：
    - 如果有更新失败、更新文件异常检测，更新前后两个Toast是否多余（或者说并不需要这么高等级的通知（Wpf内显一行log就行
3. 弹窗标题为新版本下载完毕，与MAA本体更新时弹窗存在语义混淆 (？)
    - 以及弹窗可能存在（尚未验证
        - #6154
        - #6085
        - #5653
        - 等问题

### 有什么好的想法？

- [X] 1. 制作热更进度显示（就像本体OTA
- [X] 2. 调整更新弹窗
~~3. 若已开始任务链，则不执行热更 / 不弹重启窗~~

### 其他内容

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/1e635e6d-a624-4122-ae47-8e798181742e)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/fa0b59f0-b453-48dd-bb79-dccc10138c7e)

**Comment by zzyyyl** [comment]
@ABA2396

**Comment by ABA2396** [comment]
热更能知道要下多少吗）第二个改个弹窗标题应该就好了吧）

**Comment by status102** [comment]
其实也不一定要是真实的下载进度（x
也可以是检查进度（假装？
而且有些时候并不是第一时间就需要更新掉资源，属于是可有可无的状态

- #6938 
也许要考虑提升处理这个的优先级了

**Comment by ABA2396** [comment]
现在更新的时候不会炸来着）要不更新完就不让你选择是否重启而是只弹一个吐司得了

**Comment by status102** [comment]
> 现在更新的时候不会炸来着）要不更新完就不让你选择是否重启而是只弹一个吐司得了

如果手点检查更新就弹个重启窗，其余就打一条日志？

**Comment by ABA2396** [comment]
可以吧

**Comment by MobiusT** [comment]
本来想新开iss的，想了下这个iss没关就跟在下面吧

关于【游戏资源更新】信息不明确的疑问

背景：
1、我希望自动战斗完成ex关卡，但是maa提示：不支持的关卡，请检查关卡名！
2、我检查软件更新，得到资讯：Resource Version: 崔林特尔梅之金+UI Version: DEBUG VERSION+Core Version: v4.26.2-alpha.1.d047.g3c504e5fd
3、点击检查更新按钮，依次获得以下通知【游戏资源正在更新】【已是最新版本】，后续5分钟内无任何通知
4、再次点击检查更新按钮，通知内容完全一致，无变化
4、自动战斗依然无法使用

对于这个过程我有以下疑问/建议：
1、根据我的理解Resource Version代表游戏资源版本，但凭借【崔林特尔梅之金】我无法判断现有版本是否是ex更新后的内容，还是上周的版本，只能从自动战斗中获知还不支持ex关卡，能否增加更新时间or版本号（maa标题的活动不变，仅在Resource Version中额外展示版本信息）
2、现在想要手动更新游戏资、maa版本均只能通过【检查更新】按钮实现，但是弹出的通知混淆在一起；根据我这里弹出的通知我的分析是：
      a)游戏资源需要更新，且正在更新
      b)游戏资源或者游戏版本可能是最新版本，但根据以前经验我更倾向于【已是最新版本】是告知游戏版本最新
      c)我无法通过任何信息获得【游戏资源正在更新】的后续，基于分析b)，我不能确定游戏资源是否有新版本可以更新，或是因为网络问题没有更新完毕，或是更新进度信息，对我而言除了每次弹出【游戏资源正在更新】以外，似乎maa无任何动作。 

基于以上的混乱，我希望能有以下改进：
     a)优化maa的通知描述明确通知主体，如【MAA已是最新版本】
     b)是否有必要提供游戏资源和版本单独更新的功能？（我也不确定）
     c)考虑到更新通知较多，是否可以将更新前通知合并，如【MAA已是最新版本；游戏资源有更新版本，正在更新】
     d)游戏资源更新速度、更新状态结果等信息是否能和MAA版本更新一样在日志栏展示

这样我可以通过明确的信息知道maa正在做or做了什么，我需要做什么

**Comment by ABA2396** [comment]
@status102 是不是之前把更新完成的提示改成ui内的提示了？那个是没有驻留的吧

**Comment by status102** [comment]
> @status102 是不是之前把更新完成的提示改成ui内的提示了？那个是没有驻留的吧

我没理解错的话，那个是关卡导航的更新，不是地图的这块更新

**Comment by ABA2396** [comment]
所以这些个通知是做成吐司还是Growl

**Comment by ABA2396** [comment]
怪事，正常更新因该是这样的来着
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/fc1705d4-1e46-4e27-b597-75967835949b)
为啥会报正在更新又报已是最新版本

**Comment by MobiusT** [comment]
需要我提供什么吗，我看了下asst.log日志似乎没有游戏更新方面的记录，刚才重试了下检查更新依然是相同情况，是否是我游戏资源一直没能正常更新？
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62053271/dc1bfb75-e285-4999-b8d8-2aeef1e4d2bb)

**Comment by ABA2396** [comment]
看看gui.log里有没有啥报错

**Comment by ABA2396** [comment]
这些通知都是手动点更新出来的吗

**Comment by MobiusT** [comment]
[gui.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13303209/gui.bak.log)
检查了gui.log，似乎有两个资源请求不正常  【HTTP: NotModified GET】的这条浏览器可以正常访问，【HTTP: NotFound GET】浏览器访问404 You are not authorized to view this object
10.40这条是手动更新出来的， 第一条根据日志应该是凌晨1点自动执行的？

**Comment by status102** [comment]
> 所以这些个通知是做成吐司还是Growl

目前想的是
无更新、开始更新：Growl
更新成功：Toast

主要问题还是更新中没有相应的提示，比如进度

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/13d63041-6014-4766-ac9c-dc5583cbbcce)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/cca539ea-48d2-4141-9735-b72e6ebbaae2)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/58238f80-2a2b-4959-92f6-aa26e3dcf722)
照理说这两个通知只会是二选一出现的
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/e76ac521-f956-4824-83ee-40b54ce4184b)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/49d530e0-599f-4f03-94b8-8c6824575c62)
现在的逻辑是只有版本更新成功了才不会去更新资源，弹窗内容为版本更新信息，只有版本没更新（已是最新、报错、没开更新等）才会去下资源，而其弹窗内容只会是资源更新情况，两个都是最新的时候会提示已是最新版本

**Comment by ABA2396** [comment]
> 3、点击检查更新按钮，依次获得以下通知【游戏资源正在更新】【已是最新版本】，后续5分钟内无任何通知

我看了下，现在只有更新成功的提示，更新失败了就直接返回了，之后加个弹窗，提示下再次尝试，更新进度这个不一定好整，每次的更新数量不太固定，我看看怎么改

**Comment by MobiusT** [comment]
另外请问一下，现在是否是能确定我游戏资源没能正常更新，我是否需要新开一个iss排查这一问题呢
![4JA_JVR 5X(0(RO)$~6BC U](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62053271/e6426b28-d07d-46e2-b93b-af33dbd74962)

![7JCV(%)9TA28LWEX{NNV3MX](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62053271/e2df4485-2761-4a5a-baa5-7f213f05fb76)

**Comment by ABA2396** [comment]
> > 所以这些个通知是做成吐司还是Growl
> 
> 目前想的是 无更新、开始更新：Growl 更新成功：Toast（因为有个重启要求
> 
> 主要问题还是更新中没有相应的提示，比如进度

感觉开始更新这些放到Growl 里感知就太弱了，maa很有可能一直在后台，没看到的话就完全不知道现在是否在更新了

**Comment by ABA2396** [comment]
> 另外请问一下，现在是否是能确定我游戏资源没能正常更新，我是否需要新开一个iss排查这一问题呢 ![4JA_JVR 5X(0(RO)$~6BC U](https://user-images.githubusercontent.com/62053271/281604116-e6426b28-d07d-46e2-b93b-af33dbd74962.png)
> 
> ![7JCV(%)9TA28LWEX{NNV3MX](https://user-images.githubusercontent.com/62053271/281604106-e2df4485-2761-4a5a-baa5-7f213f05fb76.png)

ex的数据刚出来，镜像站还没同步过去吧，过会儿再试试

**Comment by MobiusT** [comment]
好的，感谢，因为看您的有【游戏资源已更新....】通知，我以为是我个人问题导致更新失败，我晚点再试试看看

**Comment by status102** [comment]
> 感觉开始更新这些放到Growl 里感知就太弱了，maa很有可能一直在后台，没看到的话就完全不知道现在是否在更新了

不知道能不能持续显示一个带progress bar的Growl

**Comment by ABA2396** [comment]
@status102 瞅瞅还有啥没

**Comment by status102** [comment]
> @status102 瞅瞅还有啥没

我得想个办法干掉弹窗！（怨念（好吵

**Comment by ABA2396** [comment]
cache/etags.json 里的 dynamic_list 删了，然后随便删几条 resource\Arknights-Tile-Pos 里的文件测测 ~~多删点的话估计可以遇到下载报错了~~

**Comment by ABA2396** [comment]
先发个内测版
