### ISSUE TITLE
MAA无法识别萨米主题界面

### ISSUE THREAD

**Issue by Sh4B11** [MaaAssistantArknights/MaaAssistantArknights#6667]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天在更换了萨米肉鸽送的主题界面之后，我启动MAA，发现任务不能被正常识别。
所有需要从主页按钮进入的任务因为无法识别界面而无法进行。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12787756/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12787757/gui.log)

问题从[2023-10-03 08:48:26.443]我早上启动MAA开始；
直到[2023-10-03 09:23:00.916]我发现程序没有正常运作结束。

**Comment by HoshinoAyako** [comment]
最新内测版可以用

**Comment by Diamond01010111** [comment]
> 最新内测版可以用
我用的内测版 v4.24.1-alpha.1.d183.g5f106ab0a
在使用萨米肉鸽主题时**自动公招**会出现识别错误，其他任务我试了都没问题

**Comment by 184812** [comment]
不使用主题以解决问题

**Comment by Constrat** [comment]
> 我用的内测版 v4.24.1-alpha.1.d183.g5f106ab0a 在使用萨米肉鸽主题时**自动公招**会出现识别错误，其他任务我试了都没问题

Strange, I've tested all of them. I'll have a look at it this afternoon

**Comment by SK-Xiaohan** [comment]
夜间模式同样无法识别。
目前解决方案是不使用主题。

**Comment by Constrat** [comment]
> 夜间模式同样无法识别。 目前解决方案是不使用主题。

All tasks???

**Comment by SherkeyXD** [comment]
> 夜间模式同样无法识别。 目前解决方案是不使用主题。

你的版本是？我这边最新内测版(d200)可以正常使用

**Comment by Diamond01010111** [comment]
内测版 v4.24.1-alpha.1.d201.g5858a6196
在使用萨米肉鸽主题时**自动公招**依旧出现识别错误，其他任务我试了都没问题

**Comment by zzyyyl** [comment]
提供一张萨米主界面 1280x720 的截图，谢谢

**Comment by Diamond01010111** [comment]
> 提供一张萨米主界面 1280x720 的截图，谢谢

![主页](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113214463/aede724b-668f-41af-8d88-cdec6143aedb)
↑主界面

![出错](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113214463/8191a00b-bc4d-41e5-9ae9-3efa86426302)
↑ 内测版 v4.24.1-alpha.1.d224.g0f444ac92 依旧出错

**Comment by zzyyyl** [comment]
你试试除了萨米公招，其它的能不能用（

**Comment by Diamond01010111** [comment]
> 你试试除了萨米公招，内测版其它的能不能用（

除了公招，其他的都能用

**Comment by zzyyyl** [comment]
cf348d7a19e8c12a37e943e615a091c5c988c4cf fixed.

**Comment by Constrat** [comment]
Wait I've never added that? @zzyyyl

**Comment by zzyyyl** [comment]
haha

**Comment by Constrat** [comment]
But only the recruit. All the others were there . Pepega

**Comment by Constrat** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/43c41bd287a52fc2c3b5639c9b60031707aec506
I really didn't. Only six templates were added, when I created 7 templates. My bad XD
