### ISSUE TITLE
MAA异常运行

### ISSUE THREAD

**Issue by hijack114514** [MaaAssistantArknights/MaaAssistantArknights#6668]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用两个MAA，其中一个定时执行时fight事件时就出错
昨天其实也提过这个issue，但是更新到v4.24.1-alpha.1.d183.g5f106ab0a后问题依旧没有解决，反而两个MAA都出现问题了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12788011/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12788012/gui.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12788013/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142242356/831d6f07-0f9b-4bde-a0f3-962a70b6aa61)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142242356/c28cf31c-fbc2-4ec9-8384-59ffc5bbb39c)

### 还有别的吗？

蓝叠模拟器
win10

**Comment by wicast** [comment]
一样win10，蓝叠
我测试下来基建换班之后刷理智必定出错，把这两的顺序分开暂时能绕过问题

**Comment by zzyyyl** [comment]
2ce48e5bcf643ef674e4231bb578918c05a22eff fixed.
