### ISSUE TITLE
MAA 内测版(v4.24.1-alpha.1.d183.g5f106ab0a) 唤醒Task 闪退

### ISSUE THREAD

**Issue by cubesky** [MaaAssistantArknights/MaaAssistantArknights#6669]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 在执行唤醒 Task 时闪退，闪退后 MAA 主程序消失

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12788542/asst.log)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12788544/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/8038511/cb8918ba-72a5-46ad-be65-2c9d99cdb026)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/8038511/b1f13c7a-70d6-470f-bedf-82101bfac244)

### 还有别的吗？

模拟器 Bluestack App Player 5.9.350.1035 N32

关联问题 #6639

**Comment by wh934** [comment]
你看看是不是用的windows defender杀毒，我最新的v4.24.1-alpha.1.d183.g5f106ab0a上会被误报，过一会就自动被结束进程并删除了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64349705/cc6d58f4-2d36-46f6-b01a-fd80be815c85)

**Comment by zzyyyl** [comment]
Duplicate of #6662
