### ISSUE TITLE
MAA挂着机把自己删了？

### ISSUE THREAD

**Issue by Myon61** [MaaAssistantArknights/MaaAssistantArknights#6671]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

挂着肉鸽，模拟器和maa都最小化然后开别的玩过一会出来看maa窗口没了，想再开一下发现软件的整个文件夹都没了

### 日志文件

全没了

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96328906/d72833bd-d9eb-4ec1-bb75-3839e5dd01f0)

### 还有别的吗？

Mumu12模拟器

**Comment by zzyyyl** [comment]
Duplicate of #6669

**Comment by Myon61** [comment]
不好意思看错了，只是exe没了
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistan
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12789699/asst.log)
tArknights/files/12789696/gui.log)
10月3日下午1点到3点这段时间

**Comment by zzyyyl** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6669#issuecomment-1744293308

**Comment by Myon61** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96328906/4578f84b-5da8-48d9-be9c-61af11174d0a)
没事了，是被win10自带的安全防护删了
