### ISSUE TITLE
无法进行基建换班-并会闪退

### ISSUE THREAD

**Issue by WhiseNT** [MaaAssistantArknights/MaaAssistantArknights#6673]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/107616400/b86c4759-f03b-4fc2-81ed-987b7376009b)
在进行基建换班的时候只会打开消息通知界面并关闭消息通知界面  一直循环
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/107616400/4b07f45f-c1c2-4f70-8329-c739c3243b6d)
并有闪退问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12791758/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12791759/gui.log)
问题在10月3号的18点40左右

**Comment by zzyyyl** [comment]
更新试试

**Comment by zzyyyl** [comment]
Duplicate of #6645

**Comment by WhiseNT** [comment]
> 更新试试

解决
