### ISSUE TITLE
未完成刷龙门币次数就自动退出MAA

### ISSUE THREAD

**Issue by HengxiZ** [MaaAssistantArknights/MaaAssistantArknights#6677]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

点选了刷50此龙门币进程，但每次都只能刷一次就自动退出MAA，也未提示完成任务。无论是只勾选刷理智还是和其他功能一起勾选都会出现这个问题。如图所示，我勾选了50次龙门币，但只完成一次就退出，且未关闭模拟器，游戏界面停留在龙门币关卡结算界面。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12793898/gui.log)

### 截图

![联想截图_20231003204846](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146842833/2ee896b4-e19c-452c-a338-1bfa9cd3a874)
![联想截图_20231003204903](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146842833/10ff52cc-f560-47a9-af7a-177f03eb1231)

**Comment by HengxiZ** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12793991/asst.log)

**Comment by zzyyyl** [comment]
日志最早时间在2023-10-03 22:58:36，你可能需要上传 asst.bak.log

```
[2023-10-03 23:09:07.600][TRC][Px48ec][Tx329c] asst::WordOcr [{ 或应用: [ 1, 17, 38, 17 ], score: 0.999962 }] by OCR Pipeline , cost 22 ms
```

另外整个日志文件中没有一个 match_templ，即一次模板匹配都没成功，考虑是不是连错模拟器了（

**Comment by SherkeyXD** [comment]
最新内测版应该修了 可以试试

**Comment by HengxiZ** [comment]
我今天下午刚下的，就是不行 折腾了一天
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月04日 01:01 |
| 收件人 | MaaAssistantArknights/MaaAssistantArknights ***@***.***> |
| 抄送人 | HengxiZ ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [MaaAssistantArknights/MaaAssistantArknights] 未完成刷龙门币次数就自动退出MAA (Issue #6677) |

最新内测版应该修了 可以试试

**Comment by SherkeyXD** [comment]
最新的内测版是 d120 最近为了修bug发了一堆内测版（

**Comment by HengxiZ** [comment]
原来是这样谢谢！
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月04日 01:08 |
| 收件人 | MaaAssistantArknights/MaaAssistantArknights ***@***.***> |
| 抄送人 | HengxiZ ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [MaaAssistantArknights/MaaAssistantArknights] 未完成刷龙门币次数就自动退出MAA (Issue #6677) |

最新的内测版是 d120 最近为了修bug发了一堆内测版（
