### ISSUE TITLE
MAA无线连接实体安卓设备成功但无操作

### ISSUE THREAD

**Issue by IT-amateur** [MaaAssistantArknights/MaaAssistantArknights#6678]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在同一个局域网下通过无线调试连接，adb连接成功，但MAA在执行开始脚本并启动游戏后，在登录确认界面无任何操作，部分连接模式报错无法截图，使用第二分辨率无报错，但是也没有动作。
另一部nova 6无线调试可用，且代理无问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12793915/asst.log)
[asst-第二分辨率.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12793916/asst-.log)
[asst-通用模式(屏蔽异常输出).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12793917/asst-.log)
[asst-通用模式.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12793918/asst-.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12793919/gui.log)

### 还有别的吗？

失败手机信息：
- 型号：nova 3e
- 系统：EMUI-9.1.0
- Android版本：9

MAA版本：v4.24.0

**Comment by Rbqwow** [comment]
有试过触控模式换 MaaTouch 或者 Adb Input 吗

**Comment by IT-amateur** [comment]
> 有试过触控模式换 MaaTouch 或者 Adb Input 吗

再次尝试了一遍，切换连接模式和触控模式，都没有反应。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840845/asst.log)
