### ISSUE TITLE
mumu模拟器 更新到3.9.2后无法连接模拟器

### ISSUE THREAD

**Issue by hckkk** [MaaAssistantArknights/MaaAssistantArknights#668]
！！！请尽可能详细的描述你遇到的问题，并附上助手软件目录下的 `asst.log` 日志文件！！！

！！！日志文件是可以直接拖拽进来的，没有日志文件的 bug 反馈我们会直接关掉！！！

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8810296/asst.log)

mumu模拟器 更新到3.9.2后无法连接模拟器
回滚到3.3.2后可以正常连接，尝试过换端口号和用adb自定义连接都不彳亍

**Comment by MistEO** [comment]
连接的底层逻辑是没有修改的，只是上层识别 adb 路径和端口号可能不太对。

看日志使用 v3.3.2 的时候使用的是 `D:\tool\arknights/platform-tools\adb.exe`, 连接地址是 `127.0.0.1:7555`；使用 v3.9.2 的时候并没有尝试过这种组合，试试看

**Comment by hckkk** [comment]
可以了，之前3.3.2用的是`D:\Program Files\MuMu\emulator\nemu\EmulatorShell\..\vmonitor\bin\adb_server.exe`
v3.9.2自动识别的是 `D:\Program Files\MuMu\emulator\nemu\vmonitor\bin\adb_server.exe`
之前更新过一次mumu感觉大概率是mumu的锅
