### ISSUE TITLE
Operator Formation dirty OCR 

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#6680]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

YostarEN is back with OCR issues (should be lighter)
Kroos can't be recognized because of the "RHODES ISLAND" logo in the background.
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/faa2b960-0796-437f-8123-0e8d8249fc51)
```
asst::WordOcr [{ ISLAN KroOs: [ 0, 0, 113, 21 ], score: 0.688967 }] by OCR Rec , cost 207 ms
Proced [{ ISLAN KroOs: [ 538, 320, 113, 21 ], score: 0.688967 }]
```
I was wondering if there is a way to implement `maskRange` to help the OCR read only WHITE text:
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2a2c137d827e0f03c8645b397fe012e05e2216f0/src/MaaCore/Vision/Battle/BattleFormationAnalyzer.cpp#L23-L32

@MistEO this brings back the good old times

I've started noticing this issue after the nightly of 4.24.1 (but it may be that I never chose Kroos before)
Everything that happened after this has been a complete nightmare.

**Comment by MistEO** [comment]
You can try `oper_names_analyzer.set_bin_threshold`, or replace ISLAN with empty?

**Comment by Constrat** [comment]
Unfortunately it's not always ISLAN , sometimes it's RHOD. A combination of those.

**Comment by Constrat** [comment]
@MistEO Do you think giving the BattleFormationAnalyzer the same params as the OperBoxImageAnalyzer could do the trick?

**Comment by Constrat** [comment]
I'm trying to understand what do these 3 functions do, but I can't find any doc on it.
 - `OCRerConfig::set_bin_threshold(int lower, int upper)`
 - `OCRerConfig::set_bin_expansion(int expansion)`
 - `asst::OCRerConfig::set_bin_trim_threshold(int left, int right)`

**Comment by Constrat** [comment]
I'm guessing threshold is basically a `maskRange`, `lower `meaning from what gray scale analyzing, and `upper` at what scale stop.

**Comment by Constrat** [comment]
I'm dumb asf, I've been working and debugging the wrong file for the past hour. It's not battleformationanalyzer.cpp but battleformationtask.cpp
