### ISSUE TITLE
连不上模拟器

### ISSUE THREAD

**Issue by 1445251174** [MaaAssistantArknights/MaaAssistantArknights#6681]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

连不上模拟器 换过好几个 mma软件也重下了好几次 什么设置都试了 就是死活连不上了 最近的事情

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12796993/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12796997/gui.log)

**Comment by zzyyyl** [comment]
重启电脑试试。

**Comment by 1445251174** [comment]
> 重启电脑试试。

当然试过 了

**Comment by 1445251174** [comment]
> 重启电脑试试。

我就差换电脑了

**Comment by SherkeyXD** [comment]
> adb server version (19045) doesn't match this client (41); killing...

**Comment by zzyyyl** [comment]
可以先试试 `taskkill /im adb.exe /f` 再跑（
另外单看你传上来的日志你没重启过电脑，建议把重启前后的日志都传传（

**Comment by SherkeyXD** [comment]
看看你的连接设置 感觉是端口号错误了

**Comment by 1445251174** [comment]
> 可以先试试 `taskkill /im adb.exe /f` 再跑（ 另外单看你传上来的日志在这期间你没重启过电脑，建议把重启前后的日志都传传（

因为删了又下，重复了很多次

**Comment by 1445251174** [comment]
> 看看你的连接设置 感觉是端口号错误了

是突然不行的之前好好的，端口什么的也改过很多次 没有效果

**Comment by 1445251174** [comment]
> > 可以先试试 `taskkill /im adb.exe /f` 再跑（ 另外单看你传上来的日志在这期间你没重启过电脑，建议把重启前后的日志都传传（
> 
> 因为删了又下，重复了很多次



> 看看你的连接设置 感觉是端口号错误了



> > 
> 
> 是突然不行的之前好好的，端口什么的也改过很多次 没有效果



> 看看你的连接设置 感觉是端口号错误了



> 可以先试试 `taskkill /im adb.exe /f` 再跑（ 另外单看你传上来的日志在这期间你没重启过电脑，建议把重启前后的日志都传传（

因为删了很多次 所以之前的日志也没了 我重启是不管用的

**Comment by 1445251174** [comment]
> > adb服务器版本(19045)与此客户端(41)不匹配；谋杀...
> 
> 强制替换（同AsianDevelopmentBank）亚洲开发银行试过了吗

试过

**Comment by 1445251174** [comment]
> > adb server version (19045) doesn't match this client (41); killing...
> 
> 强制替换 adb 试过了吗

![QQ浏览器截图20231005185851](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134245301/191bca34-6324-4052-9875-74d85b073695)

**Comment by SherkeyXD** [comment]
> ![QQ浏览器截图20231005185851](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134245301/191bca34-6324-4052-9875-74d85b073695)
>

**Comment by 1445251174** [comment]
> > ![QQ浏览器截图20231005185851](https://user-images.githubusercontent.com/134245301/272880666-191bca34-6324-4052-9875-74d85b073695.png)
> 
> 删除连接地址 然后试试

一样然后他会自动填，然后填的也是一样的

**Comment by 1445251174** [comment]
> > ![QQ浏览器截图20231005185851](https://user-images.githubusercontent.com/134245301/272880666-191bca34-6324-4052-9875-74d85b073695.png)
> 
> 删除连接地址 然后试试

有没有可能是模拟器版本问题？但是我换过3种模拟器了都一样

**Comment by SherkeyXD** [comment]
自动检测连接能连上吗

**Comment by 1445251174** [comment]
> 自动检测连接能连上吗

不行，我连卸载win更新 更新win都试过 不行，要不然你远程看一下？、、

**Comment by SherkeyXD** [comment]
这样 你先删除之前的日志 然后启用自动检测连接跑一次 然后把这一次的日志传上来看看

**Comment by 1445251174** [comment]
你等一下哦

**Comment by 1445251174** [comment]
> 这样 你先删除之前的日志 然后启用自动检测连接跑一次 然后把这一次的日志传上来看看
![QQ浏览器截图20231005192252](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134245301/1b4b9a30-5d84-411e-84b4-682251fe2ca3)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12817767/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12817770/gui.log)
这是完完全全新解压的最新版本mma重启之前，我现在重启

**Comment by 1445251174** [comment]
> 这是完完全全新解压的最新版本mma重启之前，我现在重启



> 这样 你先删除之前的日志 然后启用自动检测连接跑一次 然后把这一次的日志传上来看看

![QQ浏览器截图20231005192252](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134245301/8f26d3cf-bd1b-44de-aeb1-0b1ec78dc2ef)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12817795/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12817797/gui.log)
这是完完全全新解压的最新版本mma重启之前，我现在重启

**Comment by SherkeyXD** [comment]
https://blog.csdn.net/wolfqong/article/details/132687082

你是不是装了360手机助手啥的

**Comment by 1445251174** [comment]
> https://blog.csdn.net/wolfqong/article/details/132687082
> 
> 你是不是装了360手机助手啥的

我曹原来是这玩意的问题？

**Comment by 1445251174** [comment]
> https://blog.csdn.net/wolfqong/article/details/132687082
> 
> 你是不是装了360手机助手啥的

谢谢 十分感谢 好像没问题了

**Comment by SherkeyXD** [comment]
> 我曹原来是这玩意的问题？

360手机助手自带了一个 adb，而一个版本的 adb 启动会干掉其他版本的 adb
估计是360手机助手一直在重启 adb 导致 maa 的 adb 一直被干掉
在关闭360手机助手的情况下运行应该就可以了

**Comment by 1445251174** [comment]
> 了一个 adb，而一个版本的 adb 启动会干掉其他版本的 adb

之前好像关过，不过无所谓 我直接进行一个载的卸，不过真没想到是这个的原因
