### ISSUE TITLE
萨米肉鸽烧不了水

### ISSUE THREAD

**Issue by Liudegloire** [MaaAssistantArknights/MaaAssistantArknights#6682]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽烧水进入第三层退出之后自动新开一把，不管有没有热水壶都直接退出
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39121540/b2ab0951-1945-4f19-94a9-4b0b704d66b1)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12798465/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12798466/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39121540/1d4420fa-a90a-49d9-b242-c6fb4100a385)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39121540/73a73d0f-ecc7-4dc8-b2a4-84f6a6a2ba2a)

### 还有别的吗？

mumu12
win10

**Comment by oscarchen666** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74868097/03e24552-805f-40d3-8434-fde0f67b3e9a)
我也是同样的问题，给我整不会了

**Comment by zzyyyl** [comment]
v4.25.1-alpha.1.d012.gc64e161df fixed.
