### ISSUE TITLE
希望优化自动肉鸽运行速度

### ISSUE THREAD

**Issue by xxccpp** [MaaAssistantArknights/MaaAssistantArknights#6683]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

在肉鸽中，每次点击都要等待一段时间，在选择战利品，选择关卡都会等一段时间，希望能优化一下速度

**Comment by Constrat** [comment]
The waiting times are there to allow template recognition,  OCR recognition and adding various delays to make sure it works for everyone. You might have a powerful machine that has no loading times, but it's not the same for everyone.
