### ISSUE TITLE
更换完水月肉鸽及夜间的主题页后，自动识别好像出问题了

### ISSUE THREAD

**Issue by Canvey57** [MaaAssistantArknights/MaaAssistantArknights#6684]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

感觉问题可能出现在画面识别这方面，夜间主题模式可以进行公开招募，但是水月主题的什么都不能自动运行

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12798723/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12798725/gui.log)
时间大概是2023年10月4日北京时间上午9点到10点30之间

**Comment by old-winter-sun** [comment]
+1，我排查了半天错误，最后才发现是我把主题换了...

**Comment by zzyyyl** [comment]
银淞是萨米主题吧（

**Comment by zzyyyl** [comment]
想要适配提供一下萨米主界面 1280x720 的截图，谢谢

**Comment by ElgoogUdiab** [comment]
> 想要适配的话提供一下萨米主界面 1280x720 的截图，谢谢

![夜间主题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/28426666/e6e926dd-481d-4a92-b2ef-bd0f1d693cad)
![萨米主题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/28426666/c591f785-9ed4-408f-9d03-709055ba6a2d)
