### ISSUE TITLE
肉鸽挂机达成永控无法结束关卡的建议

### ISSUE THREAD

**Issue by epicipepic** [MaaAssistantArknights/MaaAssistantArknights#6685]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

部分肉鸽关卡会达成永控，导致打不死怪/怪无法进点，一直停留在该关卡，严重浪费时间。如傀影肉鸽中拿到悬丝傀儡等加冰冻时间的藏品在雪山上的来客中容易导致部分小怪被永控；或是水月肉鸽中煤气罐/花癫疯等怪被防爆桩挡住，桩子不会被攻击消失达成永控，且mma不会检测到此情况并部署干员打破永控

### 有什么好的想法？

建议时刻扫描地图侦查此类情况，该情况出现时更改策略部署干员打破永控，或是在藏品选择策略上降低对增加控制时长的藏品、支援道具防爆桩的选择比率

**Comment by Constrat** [comment]
@Lancarus is something like this even doable?

**Comment by MistEO** [comment]
不会卡住吧，十分钟没动静就自动放弃了。有 log 看看吗

**Comment by epicipepic** [comment]
我没有翻过mma的源码不知道逻辑，目前我发现的几次情况都被我手动解决了，大概是卡了几分钟，期间mma一直在重复触发干员技能但是技能没打破永控，况且能继续战斗的话没必要放弃战斗，有损于收益吧，如果mma的逻辑是自动退出战斗希望能把策略修改一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月4日(星期三) 晚上8:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽挂机达成永控无法结束关卡的建议 (Issue #6685)





 
按照逻辑的话卡住几分钟之后是会自动撤退和放弃战斗的，是过了很久都没撤吗？

**Comment by zzyyyl** [comment]
策略没有你想象的那么好改，你有想法也可以来提pr（

**Comment by zzyyyl** [comment]
或者你可以说明一下关卡名，可以改改关卡作业

**Comment by zzyyyl** [comment]
> 我没有翻过mma的源码不知道逻辑，目前我发现的几次情况都被我手动解决了，大概是卡了几分钟，期间mma一直在重复触发干员技能但是技能没打破永控，况且能继续战斗的话没必要放弃战斗，有损于收益吧，如果mma的逻辑是自动退出战斗希望能把策略修改一下

“有损于收益”：其实肉鸽不像基建，肉鸽损失收益你多打几次就好了，反正收益有上限（

btw，希望提 issue 的时候说对 MAA 的名字 :eyes:

**Comment by Lancarus** [comment]
> is something like this even doable

It's hard to achieve now. Maa can't recognize the enemy. The logic is just like a blind man playing chess，he can only do the actions one by one or according to the number enemy dies.

**Comment by epicipepic** [comment]
maa名字打错了我是错字受orz，我觉得“有损于收益”的意思是拿奖励的效率会变低，资源提前都拿到了便于自己把想练的干员尽早练出来打关或是做别的XP


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月5日(星期四) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽挂机达成永控无法结束关卡的建议 (Issue #6685)





  
我没有翻过mma的源码不知道逻辑，目前我发现的几次情况都被我手动解决了，大概是卡了几分钟，期间mma一直在重复触发干员技能但是技能没打破永控，况且能继续战斗的话没必要放弃战斗，有损于收益吧，如果mma的逻辑是自动退出战斗希望能把策略修改一下
  
“有损于收益”：其实肉鸽不像基建，肉鸽损失收益你多打几次就好了，反正收益有上限（
 
btw，希望提 issue 的时候说对 MAA 的名字 👀

**Comment by epicipepic** [comment]
目前我知道的能达成永控的关卡就是傀影肉鸽 普通 雪山上的来客，带加控制时间的藏品会永控；水月肉鸽有奇趣蛋和花癫疯的关卡有防暴桩都可以拿桩子卡怪，这个作业是要手动改还是会在策略里统一优化呢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月5日(星期四) 下午3:41
***@***.***&gt;;
抄送:&nbsp;"heartForAngelina("⁧⁧ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽挂机达成永控无法结束关卡的建议 (Issue #6685)





 
或者你可以说明一下关卡名，可以改改关卡作业

**Comment by epicipepic** [comment]
Okay I understand now, but if Maa just recognize a small plot of land around the riot piles and the ice crystal(I'm not a foreign server so my spelling may be wrong, sorry)? That may solve this question.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月5日(星期四) 下午3:47
收件人: ***@***.***&gt;; 
抄送: "heartForAngelina(&quot;⁧⁧ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽挂机达成永控无法结束关卡的建议 (Issue #6685)





  
is something like this even doable
  
It's hard to achieve now. Maa can't recognize the enemy. The logic is just like a blind man playing chess，he can only do the actions one by one or according to the number enemy dies.

**Comment by zzyyyl** [comment]
@Lancarus 你看看能不能怎么改改

**Comment by epicipepic** [comment]
我目前的想法就是maa只检测源石冰晶和防暴桩周围一定半径的地块，达成永控条件一段时间了再尝试下干员（因为考虑到可能有干员有扩大攻击范围的技能等专好了能能打到怪自行打破永控）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月5日(星期四) 下午3:40
***@***.***&gt;;
抄送:&nbsp;"heartForAngelina("⁧⁧ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽挂机达成永控无法结束关卡的建议 (Issue #6685)





 
策略没有你想象的那么好改，你有想法也可以来提pr（

**Comment by Lancarus** [comment]
> @Lancarus 你看看能不能怎么改改

这个问题自古以来.jpg 没哟太好的办法，反正10分钟就自动重开了。。。

**Comment by epicipepic** [comment]
不会用github我有账号但是基本用不到的，能教一下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月5日(星期四) 下午3:58
收件人: ***@***.***&gt;; 
抄送: "heartForAngelina(&quot;⁧⁧ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽挂机达成永控无法结束关卡的建议 (Issue #6685)





 
@Lancarus 你看看能不能怎么改改

**Comment by Constrat** [comment]
Last problem is GitHub. If you can create code, that's all we need. You can literally just copy paste it here saying what file/from what lines it modifies.

**Comment by Constrat** [comment]
You just need to prepare a VS environment. Cloning the repo. That's it.

**Comment by Constrat** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/2.2-%E5%BC%80%E5%8F%91%E7%9B%B8%E5%85%B3.md

**Comment by epicipepic** [comment]
OK, thanks. If I can solve it I'll try.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月5日(星期四) 下午4:13
***@***.***&gt;;
抄送:&nbsp;"heartForAngelina("⁧⁧ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 肉鸽挂机达成永控无法结束关卡的建议 (Issue #6685)





 
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/2.2-%E5%BC%80%E5%8F%91%E7%9B%B8%E5%85%B3.md
