### ISSUE TITLE
肉鸽烧水功能个人建议

### ISSUE THREAD

**Issue by linjie421** [MaaAssistantArknights/MaaAssistantArknights#6689]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用肉鸽烧水功能，烧水后选择的难度不是我想要的，难度会选择能选的最大难度。

### 有什么好的想法？

希望能够设定烧水后难度。

**Comment by linjie421** [comment]
> 分队应该就是自己设的那个吧

分队这个我主要是怕科学分队睁眼瞎烧水不稳，不过刚试了一把问题不是很大。

**Comment by zzyyyl** [comment]
Duplicate of #6494
