### ISSUE TITLE
关于方舟新主题

### ISSUE THREAD

**Issue by puhit** [MaaAssistantArknights/MaaAssistantArknights#6690]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用银凇主题maa停在界面不动了

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12802515/gui.log)
10月4号19：00

**Comment by Constrat** [comment]
Please upload asst.log.
Without it we can't help.
