### ISSUE TITLE
使用“银凇”界面主题时“自动公招”功能无法使用

### ISSUE THREAD

**Issue by MinYXn** [MaaAssistantArknights/MaaAssistantArknights#6693]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用“银凇”主题时“自动公招”功能会显示识别错误，无法使用。
用resource\template下的"RecruitSami.png"文件替换掉同路径下的"Recruit.png"即可正常识别，推测是识别时调用了错误的图片。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12802979/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12802982/gui.log)
最后测试的时间大致为10/4 19:56左右。

### 截图

![Screenshot_20231004-195733](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113080762/04a730ec-65c4-4c52-acc9-78173cf29761)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113080762/9a4bd433-f1b2-49ea-8ac4-85d15f6080de)

### 还有别的吗？

版本为最新内测版v4.24.1-alpha.1.d201.g5858a6196，模拟器为雷电9

**Comment by Constrat** [comment]
Duplicate of #6667
