### ISSUE TITLE
基建排版协议增加顺序换班功能

### ISSUE THREAD

**Issue by eadric13** [MaaAssistantArknights/MaaAssistantArknights#6695]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现基建排版协议是按系统时间自动选择排班计划（无法跨天执行），对换班次数较少、无法以24h为周期循环的换班计划不友善

例如以下情况：
一天仅用MAA换班一次，想实现今天A组，下次启动（第二天）换B组
一天换班两次（三班倒），想实现早上用A组，晚上换B组，第二天早上换C组，晚上换A组

### 有什么好的想法？

在基建排班协议里增加顺序换班功能，让用户写入共有几组顺序轮换，用一个计数器记录每次启动换班的组号。如用户输入有三组，则在组号0 1 2中循环，每次启动自动选择下一个组号。

一天用MAA清两次体力、同时换两次班应该比较符合很多人的游玩方式，该优化（顺序换班）可能能满足很多人的日常需求。

**Comment by status102** [comment]
如果不填写时间的话，执行完一次换班会自动切换到下一个排班

**Comment by eadric13** [comment]
> 如果不填写时间的话，执行完一次换班会自动切换到下一个排班
> 
> 进阶：可以尝试用干员组进行排班，能更好适配3组人1天两换

原来如此，感谢。我昨天应该是看过了所有文档也没看到有这个功能，是不是可以在https://maa.plus/docs/这里的用户手册基建部分，或者基建排班协议这里加行注释说明一下？

**Comment by status102** [comment]
> 原来如此，感谢。我昨天应该是看过了所有文档也没看到有这个功能，是不是可以在https://maa.plus/docs/ 这里的用户手册基建部分，或者基建排班协议这里加行注释说明一下？

你是指干员编组？有写，不过那边注释都渲染成深色和背景混一起不好看了。
直接在GitHub这边看可能更好https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/3.6-%E5%9F%BA%E5%BB%BA%E6%8E%92%E7%8F%AD%E5%8D%8F%E8%AE%AE.md

**Comment by eadric13** [comment]
> > 原来如此，感谢。我昨天应该是看过了所有文档也没看到有这个功能，是不是可以在https://maa.plus/docs/ 这里的用户手册基建部分，或者基建排班协议这里加行注释说明一下？
> 
> 你是指干员编组？有写，不过那边注释都渲染成深色和背景混一起不好看了。 直接在GitHub这边看可能更好https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/3.6-%E5%9F%BA%E5%BB%BA%E6%8E%92%E7%8F%AD%E5%8D%8F%E8%AE%AE.md

不不，我指的是您说的，json内不写入换班时间段就能按编组顺序换班的这个功能，这个功能我昨天翻了半天文档确实也没有看见相关描述。
至于干员编组的问题，一图流那边的排班生成器已经做的很方便易读了，我想也无需赘述。

**Comment by status102** [comment]
> 不不，我指的是您说的，json内不写入换班时间段就能按编组顺序换班的这个功能，这个功能我昨天翻了半天文档确实也没有看见相关描述。
> 至于干员编组的问题，一图流那边的排班生成器已经做的很方便易读了，我想也无需赘述。

我也不用那个自动+1，印象中之前uye在开发群里说的。刚看了眼，一图流好像还没适配干员编组

**Comment by eadric13** [comment]
> 我也不用那个自动+1，印象中之前uye在开发群里说的。刚看了眼，一图流好像还没适配干员编组

https://yituliu.site/tools/maa 这个排班表生成器已经实现编组了吧？我昨天写好了一套A组12hB组12hC组12h轮转的排版，因为没看到有顺序换班遂作罢，晚点心情转好了尝试一下

**Comment by status102** [comment]
不一样的东西，去看基建协议的groups字段

**Comment by ZhaoZuohong** [comment]
@status102 有没有兴趣支持四个干员轮替3个位置，比如苍苔、砾、斑点、夜烟轮替一个3级制造站

**Comment by status102** [comment]
> @status102 有没有兴趣支持四个干员轮替3个位置，比如苍苔、砾、斑点、夜烟轮替一个3级制造站

没懂，细说

**Comment by ZhaoZuohong** [comment]
中枢放满干员时，3 级制造站的心情消耗速率是 0.65，干员的心情上限是 24，干员可以工作 $\frac{24}{0.65} \approx 36.92$ 小时。如果每 12 小时换一次班，可以连干 3 班。最差的宿舍（1 级满氛围）每小时恢复 2 点心情，休息 1 班可以回满。四个干员轮替一个 3 级制造站，工作时间比例可以达到 75%。三班轮替两个站，主力的工作时间比例只有 $\frac{2}{3}$ 。使用这种方案，高效主力的工作时间更长，也节省了替换干员的数量。

具体来说：

| 班次 | 干员1 | 干员2 | 干员3 | 效率 | 宿舍 |
|--|--|--|--|--|--|
| 1 | 苍苔 | 砾 | 斑点 | 110% | 夜烟 |
| 2 | 夜烟 | 砾 | 斑点 | 95% | 苍苔 |
| 3 | 苍苔 | 夜烟 | 斑点 | 105% | 砾 |
| 4 | 苍苔 | 砾 | 夜烟 | 110% | 斑点 |

平均效率为 105%

对于干员配置较高的情况，这个技巧的用处不是很大，但对于干员配置较低的基建，能显著提升收益。

在编写 Maa 的自定义基建文件时，一天两换、使用四个干员轮替三个位置，一轮需要四个班次。有些位置，如 1 级或 2 级的制造站、发电站、中枢、会客室、办公室等，一般干员只能连续工作 2 个班次，一轮需要三个班次。如果要完整地组合一轮，需要写 12 班。如果能用一“组”来表示这个站的换班方案，就可以减轻编写排班文件的工作量了。

**Comment by status102** [comment]
但是怎么启动这个轮换？可能是个问题

现在支持以组来表示任意个干员在一起的组合
比如:
| 组别 | 干员 |
| --- | --- |
| A组 | 苍苔 、 砾 、 斑点 |
| B组 | 夜烟 、 砾 、 斑点 |

然后在设施将干员设置为 ` ["A组", "B组"] `，MAA会根据干员的心情值在设施的干员内从上到下尝试匹配可用编组

**Comment by ZhaoZuohong** [comment]
> 但是怎么启动这个轮换？可能是个问题

如果允许一个组内有4个干员，比如 `"苍苔组": ["苍苔", "砾", "斑点", "夜烟"]`，设施内干员只设 `["苍苔组"]`，在换班时，将正在工作的心情最低的干员安排休息、换上组内不在工作的干员，应该就可以了。

组是否有希望用于其它场景呢？。以[公孙长乐黑钢版本243中枢永动](https://www.bilibili.com/video/BV1FN411i7RQ)为例：

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34163622/079774ea-7ae3-4b96-8c32-0a68cd681cd4)

* 贸易站：作为主力的龙舌兰组需要暖机，心情消耗为 0.65，可连续干三班；但书组也可连续干三班。适合的换班轮次为四班，两组主力错开休息，共用能天使一组替换。
* 赤金制造：一天两换时，苍苔组平均效率为 $1.1 \times \frac{2}{3} + 0.93 \times \frac{1}{3} \approx 1.0433$，不如四替三的 105%；自动化组受承曦格雷伊在发电站 0.75 的心情消耗速率影响，只能连上两班后休息一班。
* 经验制造：红云组的稀音需要暖机，可连续干三班，休息时使用红豆、霜叶、Castle-3替换。至简一站都是散件，可以把食铁兽加进来四换三。

对于跨站的组合，如自动化，有好的主意吗？

**Comment by status102** [comment]
目前设计的场景是，ABC三组，然后两个站同时设为ABC，一天两换每次换一个站。

散件可以放进备选列表，那边还是老逻辑

**Comment by ZhaoZuohong** [comment]
> 一天两换每次换一个站

这个做法是有问题的，以上面贸易站的方案为例，每次都换会导致高效率的龙舌兰、但书组的工作时间占比只有 $\frac{2}{3}$、缩短了裁缝的持续工作时长，浪费暖机时间。应该在两组主力心情比较健康时**不换**，龙舌兰、但书组的工作时间占比可以提升到 $\frac{3}{4}$。

**Comment by ZhaoZuohong** [comment]
> 两个站同时设为ABC

自动化这种跨站的组合怎么写？

**Comment by status102** [comment]
> 自动化这种跨站的组合怎么写？

没懂你意思

**Comment by ZhaoZuohong** [comment]
> create a custom infrastructure json

现在低频率的排班表特别难写。以上面的方案为例，一个普通的一天两换方案需要写 12 班才能实现。这不是因为换班方案本身复杂，而是协议设计得不好。

> I don't think for now, this is one of the most important enhancement that we will be working on.

好吧

**Comment by status102** [comment]
@ZhaoZuohong 目前完全是基于一天两换这种低频换班，裁缝-0.25之后感觉坚持不到下一轮换班了

**Comment by ZhaoZuohong** [comment]
> 感觉坚持不到下一轮换班了

巫恋、龙舌兰、柏喙都带“心情每小时消耗-0.25”效果，与巫恋的“全体心情每小时消耗+0.25”抵消，心情消耗速率还是 0.65，仍然可以工作 $24 \div 0.65 \approx 36.923$ 小时，能干三班

**Comment by status102** [comment]
想起来了，我中枢没得永动就一直空置的。加上两次换班并非准点，存在±1.5小时的误差
