### ISSUE TITLE
建议添加每日轮换关卡的预选择刷取

### ISSUE THREAD

**Issue by buzhezhixin** [MaaAssistantArknights/MaaAssistantArknights#6696]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

每次在关卡关闭后都会刷上一次刷的关卡，有时会导致理智的浪费或花费不符预期。就我本人而言，平时一般电脑都会处于待机状态，并不会关闭maa的，因此采用了8、14、20点每天3次运行。有时会因为活动结束之类的导致活动结束后8点会出现一些意外的错误。

### 有什么好的想法？

添加一个次日刷理智的首要关卡预选择功能或者是基于每日关卡轮换的一种排班。以便于活动-长草期之间交替的排班，以免引起不必要的理智浪费和长草期的每日轮换关卡每次都需要切换的麻烦。

### 其他内容

维护更新，辛苦了！！！

**Comment by ABA2396** [comment]
设置里有备选关卡，会打关卡列表里第一个开放的关卡

**Comment by zzyyyl** [comment]
> 设置里有备选关卡，会打关卡列表里第一个开放的关卡

他的意思可能是，上次作战是活动关卡的时候，活动关了的话，上次作战会变成其他关卡

**Comment by ABA2396** [comment]
> > 设置里有备选关卡，会打关卡列表里第一个开放的关卡
> 
> 他的意思可能是，上次作战是活动关卡的时候，活动关了的话，上次作战会变成其他关卡，这时候没有报错也没提示

上次作战是活动并且关了的话是会当做不开放关卡对待的，只有下次启动的时候才会变成 当前/上次 ，不重启的话就是一个不开放的关卡

**Comment by ABA2396** [comment]
> > > > 设置里有备选关卡，会打关卡列表里第一个开放的关卡
> > > 
> > > 
> > > 他的意思可能是，上次作战是活动关卡的时候，活动关了的话，上次作战会变成其他关卡，这时候没有报错也没提示
> > 
> > 
> > 上次作战是活动并且关了的话是会当做不开放关卡对待的，只有下次启动的时候才会变成 当前/上次 ，不重启的话就是一个不开放的关卡
> 
> 我的意思是，MAA 是当前/上次，游戏内的上次作战在活动结束会变

对啊，所以用备选关卡啊）开了备选就算活动结束了也不会马上变成 当前/上次 的
