### ISSUE TITLE
[iOS]MAA萨米肉鸽借助战之后卡住不动

### ISSUE THREAD

**Issue by ericwxy1** [MaaAssistantArknights/MaaAssistantArknights#6698]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

借百炼嘉维尔之后会卡在干员立绘界面

### 日志文件

[asst.log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12811979/asst.log.zip)

### 截图

[maa截图.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12811985/maa.zip)

### 还有别的吗？

M2芯片, MacOS sonoma 14.0

**Comment by ericwxy1** [comment]
windows 同样有这个问题，而且所有干员都识别不到了

**Comment by ericwxy1** [comment]
windows内测版解决这个问题了 希望mac也尽快修复一下 谢谢~

**Comment by zzyyyl** [comment]
#6630 修的，mac 没内测版要等下一个公测/稳定版了
