### ISSUE TITLE
每次打开maa后关卡选择都是当前/上次

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#6699]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我记得maa是会记住上次选择的，但是我今天（10.5）上午设置了红票-5后，晚上（）再打开时又变成当前/上次了

### 日志文件

[Uploading asst.log…]()
[Uploading gui.log…]()

**Comment by Constrat** [comment]
If AP-5 closes, it won't be in the available stages, hence it will choose Cur/Last if no older stages were selected.
