### ISSUE TITLE
Attempting to save configuration file after release, this is not allowed+自动删除客户端

### ISSUE THREAD

**Issue by EricWangxy** [MaaAssistantArknights/MaaAssistantArknights#6701]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

点开始之后就没管了，再看的时候maa.exe没了，在文件夹里面找不到了，并且在gui.log里面出现了Attempting to save configuration file after release, this is not allowed

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12817916/gui.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12817917/asst.bak.log)
时间戳是10-5 1：10开始的

### 还有别的吗？

windows 11 22H2， 雷电模拟器

**Comment by SherkeyXD** [comment]
自动删除客户端应该是windows defender的锅 这阵子挺多人被误报的 我们正在排查
