### ISSUE TITLE
“获取信用及购物“会导致MAA卡死的情况

### ISSUE THREAD

**Issue by Terror03** [MaaAssistantArknights/MaaAssistantArknights#6706]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在“获取信用及购物“-”借助战打OF-1赚信用“被勾选的情况下，如果借不到满级德克萨斯，会永久卡在借助战画面
步骤逻辑存在问题
建议改成使用自己的德克萨斯

### 日志文件

无

**Comment by SherkeyXD** [comment]
`使用自己的德克萨斯` 就不是 `借助战赚信用` 了
卡死问题我们在检查）
