### ISSUE TITLE
肉鸽选择第一个开局角色后立刻结束探索

### ISSUE THREAD

**Issue by DrSenkin** [MaaAssistantArknights/MaaAssistantArknights#6707]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在使用刷肉鸽等级期间到选择第一个6星的开局助战角色后卡死数秒并尝试将角色立绘往右边拉，然后maa会退出肉鸽并开启下一次探索，循环往复。
在尝试了用了动态的立绘或者静态立绘的角色后，可以初步排除是立绘导致识别错误。
我换了v4.24.1的内测版后就好了

### 日志文件

[Desktop.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12823180/Desktop.zip)

### 还有别的吗？

版本：v4.24.0 （公测版）
肉鸽：萨米
系统：win11_22H2
模拟器：mumu12

**Comment by Lancarus** [comment]
fixed in #6630
