### ISSUE TITLE
基建换班中找不到麒麟R夜刀，而是去找麒麟X夜刀

### ISSUE THREAD

**Issue by muyishuihan** [MaaAssistantArknights/MaaAssistantArknights#6709]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建换班中找不到麒麟R夜刀，而是去找麒麟X夜刀

### 日志文件

![找不到麒麟R夜刀2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16174537/5ed143fe-eb45-44cd-acf7-8beb6fca4f57)

### 截图

![找不到麒麟R夜刀](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16174537/040d0719-2e87-4efb-a814-a3006dd25275)
![找不到麒麟R夜刀2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16174537/32f79bc2-509d-4635-bba2-61844c7e2829)
![找不到麒麟R夜刀3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16174537/af87e7f3-2d06-4583-a148-a86d92e6f316)

**Comment by status102** [comment]
看看自定义的基建作业里面写的是X还是R

**Comment by Constrat** [comment]
No logs, no settings info, no custom infrastructure job. There is nothing we can do.
Like Status said, this is most likely an issue of the custom infrastructure job, as we have Refactored 麒麟X夜刀 to 麒麟R夜刀 a long time ago

**Comment by SherkeyXD** [comment]
应该是你的基建配置文件当中写的还是麒麟X夜刀，改一下试试

**Comment by muyishuihan** [comment]
谢谢MAA项目组成员解答，确实是我的问题。在我自定义基建中写的是麒麟X夜刀。XD
