### ISSUE TITLE
新待机界面，会导致任务识别失败

### ISSUE THREAD

**Issue by RicardoYue** [MaaAssistantArknights/MaaAssistantArknights#6712]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如果在游戏里开启最新主题，肉鸽成就获取的主题，maa会识别不到，导致任务无法进行。

### 日志文件

无

**Comment by zzyyyl** [comment]
更新最新内测版
