### ISSUE TITLE
冬隐归路开播礼包导致任务失败

### ISSUE THREAD

**Issue by AnnAngela** [MaaAssistantArknights/MaaAssistantArknights#6713]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

冬隐归路开播礼包导致需要识别主界面的任务失败（比如 `startup`）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12826123/asst.log)

### 截图

![d1d317f8fc1d0614eaf4f6a10cefc22a](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/9762652/f13bc4b9-5b37-4fa9-a94f-64322aa8f943)

**Comment by Lancarus** [comment]
给startup加个超时没到主页后重启的逻辑？

**Comment by AnnAngela** [comment]
> 给startup加个超时没到主页后重启的逻辑？

这个不解决问题，如果用户不手动介入（比如领取礼包）的话，重启后仍然会显示这个界面

**Comment by Lancarus** [comment]
> > 给startup加个超时没到主页后重启的逻辑？
> 
> 这个不解决问题，如果用户不手动介入（比如领取礼包）的话，重启后仍然会显示这个界面
> 
> 有证实说重启后不显示这个界面吗？

你说的对，试了一下，要领了之后重启或者点×才不出现

**Comment by Constrat** [comment]
Can confirm.
Tried this yesterday. MAA tasks crashed on me. Collected the rewards and MAA worked fine. This morning no notifications were alerted, MAA continued correctly as it always did.

In my opinion I don't think it's necessary to release an update just for this notification (it should happen only once)

**Comment by AnnAngela** [comment]
感谢老哥，那我将该问题标记为 wontfix 好了。
