### ISSUE TITLE
启动进入主界面后无法正常点击与识别，频繁提示错误

### ISSUE THREAD

**Issue by DrFx200522** [MaaAssistantArknights/MaaAssistantArknights#6720]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA无法进行预定的任务，

### 日志文件

[asst_gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12829710/asst_gui.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/117508566/376d0746-72ab-48d3-9c5c-5a39bf6f56cc)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/117508566/e8b54a76-d2cf-4a32-9c23-a684f8ccd4b9)

### 还有别的吗？

mumu12，win10 22h2,e3 1231v3+1660

**Comment by DrFx200522** [comment]
点到其他界面会一直往主界面退

**Comment by Constrat** [comment]
That's obvious. The dark mode for Arknights client has not yet been implemented in the 4.24.0 version. Update to the latest nightly/alpha!
