### ISSUE TITLE
api.prts.plus Invalid SSL certificate

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#6724]
As of october 2023, [docs/glossary/operators.md](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/6d5f3971a415650902123922bf54dd73ae3dcaea/docs/glossary/operators.md) is outdated and there is no way to use the [python script](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/6d5f3971a415650902123922bf54dd73ae3dcaea/docs/glossary/operators_generator.py) to update it because the API website has an invalid SSL certificate.

I need an accessible operators list with different languages because I'm trying to implement 
- #6664

**Comment by Rbqwow** [comment]
api.maa.plus 用了 ota.maa.plus 的证书 然后开了 HSTS 上不去 草
(所以说为什么不用 *.maa.plus

**Comment by Constrat** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/6d5f3971a415650902123922bf54dd73ae3dcaea/docs/glossary/operators_generator.py#L5-L7

**Comment by Rbqwow** [comment]
Bombing MistEO with calls and emails XD
@MistEO

**Comment by Constrat** [comment]
Fair enough xD

**Comment by MistEO** [comment]
use [this magic](https://github.com/MaaAssistantArknights/MaaRelease/blob/main/MaaAssistantArknights/api/binaries/arknights_rs.exe) like [this](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/tools/ResourceUpdater/main.cpp#L155). You can also download and use this binary in python.

Tips: It uses some hacks and is not open source, so use it with caution.
