### ISSUE TITLE
开始唤醒明日方舟正常登录至初始界面但MAA报错

### ISSUE THREAD

**Issue by Nemo0223** [MaaAssistantArknights/MaaAssistantArknights#6725]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在按照指示设置完成后，在一键长草界面选择开始唤醒和自动肉鸽，然后MAA可以正常启动明日方舟，也可以自动登录至初始界面，但随后MAA显示任务出错：startup

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12832413/gui.log)
2023.10.06 22：43分

### 截图

![`1 L2KR})_O)D)G2R T%2BC](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75009684/be353b42-57ad-4532-8363-bf86cfce01d8)

### 还有别的吗？

mumu12模拟器，win64

**Comment by ABA2396** [comment]
我先来猜：换了主题
