### ISSUE TITLE
StartUp可能需要优化流程

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#6728]
### 说说你遇到的问题？

编队页、干员页启动StartUp 大约3~4秒走完
首页 大约10s走完

仅留作记录，检查后自行关闭

**Comment by zzyyyl** [comment]
startup在主界面到时候有个延时等弹窗的逻辑

**Comment by status102** [comment]
startup本身就postDelay: 1000，然后startup任务又设置了双倍的操作延迟，会不会重复了
