### ISSUE TITLE
刷理智覆巢之下连续20次后游戏闪退

### ISSUE THREAD

**Issue by lancelotgx** [MaaAssistantArknights/MaaAssistantArknights#673]
覆巢之下刷材料。更新了MAA之后，不管如何碎石，每次只能刷约20次（我设定碎石远超过20次）。测试过3次均在20次刷图时闪退游戏。
20次左右之后模拟器明日方舟游戏会闪退。我使用雷电、mumu、夜神均是该情况。
后来在群里推荐使用蓝叠模拟器，20次之后明日方舟游戏返回唤醒界面。依旧无法大量连续刷图。
![QQ拼音截图20220601120537](https://user-images.githubusercontent.com/101645625/171326768-18c00006-e445-4680-a602-6f54d17db3ef.png)
MAA里看起来是没有显示，就是20次之后就没反应了。一直停在这里。烦请指导一下如何解决。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8811001/asst.log)

**Comment by MistEO** [comment]
游戏崩溃是游戏问题，200 合成玉警告（

maa 无能为力的，有计划支持游戏崩溃后自动重启游戏，~~但目前还是新建文件夹~~

**Comment by ABA2396** [comment]
> 游戏崩溃是游戏问题，200 合成玉警告（
> 
> maa 无能为力的，有计划支持游戏崩溃后自动重启游戏，~但目前还是新建文件夹~

可以试试任务失败或者长时间未操作的时候重启游戏，然后执行一遍开始唤醒和当次任务

**Comment by ABA2396** [comment]
这次刷SV-9崩溃是挺严重的，我刷了两天已经崩溃十几次了

**Comment by ABA2396** [comment]
只有装置这一关有问题，或许是教主没进化出闪避却进化出了闪退。不只是模拟器，手机也是）
