### ISSUE TITLE
吃48小时内过期的理智药没有日志输出

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#6732]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题 maa主页右侧日志不会打印因“无限吃48小时内过期的理智药”吃的理智药次数
看着满级号莫名其妙多出来的一管理智懵逼

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12836804/gui.log)
2023-10-07 12:22:18.674

### 还有别的吗？

🤔为什么是48小时而不是24小时
OCR识别“1天”吗

**Comment by Rbqwow** [comment]
add fight

**Comment by ABA2396** [comment]
OCR识别
```
"text": [
    "分钟",
    "小时",
    "1天"
],
```

**Comment by MistEO** [comment]
等个佬带带
