### ISSUE TITLE
无法识别夜间主题

### ISSUE THREAD

**Issue by Maverick-Y** [MaaAssistantArknights/MaaAssistantArknights#6733]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

明日方舟目前有三个主题，日间，夜间和萨米肉鸽主题

目前我的MAA无法识别夜间主题（字是黑色的），导致夜间主题下领取奖励和刷理智功能不可用，切换回日间主题可以解决。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12836886/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12836887/gui.log)

**Comment by ElgoogUdiab** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6684#issuecomment-1748279661

急的话更新内测版，不急的话等更新

**Comment by SherkeyXD** [comment]
内测版已经做了适配 公测版也快发了
