### ISSUE TITLE
刷理智时关卡失败后不能识别, 持续刷失败关卡

### ISSUE THREAD

**Issue by mayii2001** [MaaAssistantArknights/MaaAssistantArknights#6734]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

版本4.24.0 稳定版 不是在刷剿灭, 日常使用的素材关不开放, "当前\上次"直接跳转到主线关卡了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/88707940/f1ec12c8-e94e-4114-bc53-0d171a60dab9)

建议识别失败后跳转到设置的备选关卡

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12836935/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12836936/gui.log)

**Comment by Constrat** [comment]
This is not an MAA error... Looking at the gui.log, your auto deploy is not 3 stars, simple as that. The error also says that.
Your sanity is going down by 1 at a time and you are receiving 20 sanity back every time.

**Comment by mayii2001** [comment]
> This is not an MAA error... Looking at the gui.log, your auto deploy is not 3 stars, simple as that. The error also says that. Your sanity is going down by 1 at a time and you are receiving 20 sanity back every time.

The reason why I jump to a non-triple star mission because the last used material mission was not open and MAA's default use of "current/last" will directly tap into the earlier mission, which is difficult to control and often happens. The fundamental reason for this is that there is only one candidate mission, and running "clearing the sanity" but returning most of the sanity is itself conflicting and abnormal, and there needs to be a mechanism to recognize that it is wrong

**Comment by Constrat** [comment]
If you don't want MAA to use Cur/Last you can implement alternative stages.
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/fd8f39b2-45c0-44ff-84ff-e57596b98e2f)
Also, I don't suggest using the material options.

**Comment by mayii2001** [comment]
> If you don't want MAA to use Cur/Last you can implement alternative stages. ![image](https://user-images.githubusercontent.com/56174894/273375723-fd8f39b2-45c0-44ff-84ff-e57596b98e2f.png) Also, I don't suggest using the material options.

I found the alternative stages, but I feet it is necessary to fix the issue that it didn't recognize if a mission had failed
And the material option seems don't work at all....

**Comment by zzyyyl** [comment]
![PrtsErrorConfirm](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/5275122d-f323-41b2-aa9d-02487686598c)

这个界面现在还有没有

**Comment by zzyyyl** [comment]
等一下，你这是一直在刷剿灭吧

**Comment by zzyyyl** [comment]
之前只有非三星结算的判断，看样子你是直接任务失败了（
