### ISSUE TITLE
maa报错之后把自己删了

### ISSUE THREAD

**Issue by Otonahi-Mirai** [MaaAssistantArknights/MaaAssistantArknights#6735]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题
今天早上打开发现maa自己报错之后把软件删了
之后重下了一次
运行正常一次，之后又开始报错把自己删了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12836964/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12836970/gui.log)

### 截图

![微信图片_20231007142444](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62061255/8ad8e965-7fae-485f-a4a6-c33bcca9aefd)

### 还有别的吗？

使用Win11 MUMU12

**Comment by SherkeyXD** [comment]
Duplicate of #6662
