### ISSUE TITLE
MAA被win10误报木马病毒并删除

### ISSUE THREAD

**Issue by suzuka1221** [MaaAssistantArknights/MaaAssistantArknights#6737]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

10月4日开始数次启动maa后Windows安全中心弹通知显示发现木马病毒，随后整个软件就被Microsoft defender直接删了，不是每次都会，概率大概70%会被误报，有时还是可以使用的。已经删干净重新下载很多次，但还是会出现相同的状况，版本号是内测版v4.24.0（64位）
截图是系统误报；最后的文本是maa曾出现过的一次报错，在之后又被整个被删了，maa自己的报错只弹了这一次。
第一次在这里写问题反馈，如有描述不清或者提供信息不足请见谅（＞人＜；）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12837204/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12837210/gui.log)

### 截图

![F2Q@2P5Q64~Y9OBCJ1@KSV](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147239005/f5397952-5a27-4c70-b2df-043b8e8641a3)
![{6W$@5{{$)9V9)FL145BCZW](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147239005/21e115ab-fc66-4252-b8b6-ab746b5b3f9b)

### 还有别的吗？

[文本(2023-10-07 140535).txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12837211/2023-10-07.140535.txt)

**Comment by Fland22** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46626706/81676b08-9fc1-4d6c-b832-063aef2cac1f)
同样遇到此问题

**Comment by MaoYouSi** [comment]
同遇到了这个情况，复制下错误报告
MAA 遇到了问题
无法成功完成操作，因为文件包含病毒或潜在的垃圾软件。
解决方案
出现未知错误
详细信息
System.ComponentModel.Win32Exception (0x80004005): 无法成功完成操作，因为文件包含病毒或潜在的垃圾软件。
   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   在 MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndUpdateNow()
   在 MaaWpfGui.ViewModels.UI.RootViewModel.OnViewLoaded()
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by zzyyyl** [comment]
Duplicate of #6662
