### ISSUE TITLE
添加肉鸽自定义抓位设置

### ISSUE THREAD

**Issue by yiexinrou** [MaaAssistantArknights/MaaAssistantArknights#6738]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我的账号练度不高，已有的六星干员在MAA的设定中抓位均不高，导致肉鸽难以打到三层以上

### 有什么好的想法？

可以添加一个自定义干员抓位优先级的功能，以更好适应不同练度的账号

**Comment by Lancarus** [comment]
[肉鸽协议](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/3.5-%E8%82%89%E9%B8%BD%E8%BE%85%E5%8A%A9%E5%8D%8F%E8%AE%AE.md)
自己看完文档之后改吧

**Comment by Constrat** [comment]
To change priorities:
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2d03e9ac5b357b9a3bf85318e9e1391e350bdc60/resource/roguelike/Mizuki/recruitment.json#L45-L56
you can custom manually optimize what's best for you in the various recruitment.json files

- [resource/roguelike/Mizuki/rescruitment.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2d03e9ac5b357b9a3bf85318e9e1391e350bdc60/resource/roguelike/Mizuki/recruitment.json)
- [resource/roguelike/Phantom/rescruitment.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2d03e9ac5b357b9a3bf85318e9e1391e350bdc60/resource/roguelike/Phantom/recruitment.json)
- [resource/roguelike/Sami/rescruitment.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2d03e9ac5b357b9a3bf85318e9e1391e350bdc60/resource/roguelike/Sami/recruitment.json)

**Comment by Lancarus** [comment]
@Constrat  Can you understand the [doc 3.5](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/3.5-%E8%82%89%E9%B8%BD%E8%BE%85%E5%8A%A9%E5%8D%8F%E8%AE%AE.md) ?

**Comment by Constrat** [comment]
Definitely not in chinese xD.
Let me ML really quick

**Comment by Constrat** [comment]
@Lancarus I'm slowly translating it, but it looks good

**Comment by yiexinrou** [comment]
> @Lancarus I'm slowly translating it, but it looks good

If it's in English，this means that we can set the priority recruitment staff for MAA based on the different situations of our own accounts.

**Comment by yiexinrou** [comment]
> [肉鸽协议](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/3.5-%E8%82%89%E9%B8%BD%E8%BE%85%E5%8A%A9%E5%8D%8F%E8%AE%AE.md) 自己看完文档之后改吧

没学过编程，不会改啊

**Comment by Constrat** [comment]
Fortunately it's not programming, it's just a question of opening the file and changing the number to something else.

Answering your previous question. Unfortunately we are able to "understand" the "level of your account" as there are too many variables to consider and interpret.
What YOU can do is optimize MAA for your needs. If you notice a low leveled operator getting picked too many times you can lower its recruit priority.

The doc that @Lancarus linked is very easy and exhaustive

**Comment by yiexinrou** [comment]
> Fortunately it's not programming, it's just a question of opening the file and changing the number to something else.
> 
> Answering your previous question. Unfortunately we are able to "understand" the "level of your account" as there are too many variables to consider and interpret. What YOU can do is optimize MAA for your needs. If you notice a low leveled operator getting picked too many times you can lower its recruit priority.
> 
> The doc that @Lancarus linked is very easy and exhaustive

Thank you for your answer,I will try to solve the problem by myself.
By the way, if there were a feature that could help me increase the recruit priority of high leveled operator, it couldn't be better.

**Comment by Constrat** [comment]
Just identify what are your "main" levelled operators and search them in the json
Increse its priority recruit AND upgrade

**Comment by yiexinrou** [comment]
> Just identify what are your "main" levelled operators and search them in the json Increse its priority recruit AND upgrade

Thank you for your advice,I will try it tomorrow.
