### ISSUE TITLE
雷电模拟器使用MAA无法识别干员

### ISSUE THREAD

**Issue by Chenxin2** [MaaAssistantArknights/MaaAssistantArknights#674]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8811129/asst.log)
模拟器分辨率为1600*9000
自动战斗选取干员时无法识别史尔特尔以及棘刺
刷肉鸽时不选取干员

**Comment by ABA2396** [comment]
更正，是1600x900

**Comment by MistEO** [comment]
是两个不同的问题，你的日志中只有肉鸽的

- 肉鸽卡在哪个界面了？来张图
- 自动战斗再发一份日志吧~

**Comment by Chenxin2** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by T-Chaos** [comment]
> 是两个不同的问题，你的日志中只有肉鸽的
> 
> * 肉鸽卡在哪个界面了？来张图
> * 自动战斗再发一份日志吧~

遇到过一样的问题，雷电模拟器，肉鸽选人界面直接退出招募然后进入关卡

**Comment by Chenxin2** [comment]
> 
重新连接后恢复正常了，连接地址为127.0.0.1:5555后能正常识别
之前出现的肉鸽异常出现在选人界面，未选择干员就直接退出了
![image](https://user-images.githubusercontent.com/44183274/171383396-e13d8c92-8e20-4ea2-a7ba-be3417d9279b.png)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8813234/asst.log)

**Comment by strand818** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
