### ISSUE TITLE
任务全部完成后有概率在最后一个任务完成时卡住，不进行"任务已全部完成"的输出及完成任务后的后续动作

### ISSUE THREAD

**Issue by MuLingMing** [MaaAssistantArknights/MaaAssistantArknights#6740]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

任务全部完成后有概率在最后一个任务完成时卡住，不进行"任务已全部完成"的输出及完成任务后的后续动作

![gui错误发生](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114294439/6f9cd923-9076-4314-a4ac-8e0fa09aedbc)

如图在19:30时任务全部完成，但是后续没有输出”任务已全部完成！“的提示，并且没有进行后续动作，即任务完成后的后续动作
![完成后](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114294439/914fb6c3-d70e-4b78-8fd9-6b7cdf341f2c)

33分时测试，结果正常
![gui正常情况](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114294439/ffbff423-7676-4602-aa54-8902bbc28571)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12837596/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12837597/asst.bak.log)
asst.log不知道为什么就保存为了ANSI的格式，utf8打开显示正常
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12837599/gui.log)

**Comment by MuLingMing** [comment]
重新上传一遍utf8的非乱码日志
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12837609/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12837610/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12837612/gui.log)

**Comment by CCCClaus** [comment]
同现象。
[image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/116964544/8df7f939-de23-42a2-bcce-cfc88b8710c7)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12837651/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12837652/asst.zip)
