### ISSUE TITLE
水月肉鸽在事件界面无法选取选项

### ISSUE THREAD

**Issue by sxj81192** [MaaAssistantArknights/MaaAssistantArknights#6742]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![PT 4~STK5$VHNFVJQM3{`8S](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/48231175/ef10407a-e1e2-4f10-aff8-edb966908bb8)
如图，在该界面反复点击几个选项，但无法选择并进行下一步

### 日志文件

问题时间点
 从该时间点后进入事件界面[2023-10-07 20:55:45.190] <1><> 关卡: 安全的角落 
至该时间点为止手动点击选项结束卡顿[2023-10-07 21:29:54.370] <1><> 关卡: 不期而遇  
[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12837944/log.zip)

### 还有别的吗？

模拟器为mumu12，其他功能使用正常

**Comment by Manicsteiner** [comment]
这个问题一直有 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5862
目前最靠谱的方法还是自己改一遍roi。请根据[外服适配](https://maa.plus/docs/2.5-%E5%A4%96%E6%9C%8D%E9%80%82%E9%85%8D%E6%95%99%E7%A8%8B.html)教程，自行根据截图获取roi，图片替换至 \resource\global\YoStarJP\resource\template\Mizuki@Roguelike@StageEncounterOptionUnknown.png ，roi数据替换至 \resource\global\YoStarJP\resource\task.json 的 "Mizuki@Roguelike@StageEncounterLeaveConfirm" 节点。
或者，如果您在4.20.x版本及以前正常，请删除 \resource\global\YoStarJP\resource\task.json 的 "Mizuki@Roguelike@StageEncounterLeaveConfirm" 节点，并用旧版本中的 \resource\global\YoStarJP\resource\template\Mizuki@Roguelike@StageEncounterOptionUnknown.png 替换掉新版本的。

**Comment by sxj81192** [comment]
> 这个问题一直有#5862 目前最靠谱的方法还是自己改车roi。请根据[外服转发](https://maa.plus/docs/2.5-%E5%A4%96%E6%9C%8D%E9%80%82%E9%85%8D%E6%95%99%E7%A8%8B.html)教程，自行根据截图获取roi，图片替换至\resource\global\YoStarJP\resource\template\Mizuki@ [Roguelike@ StageEncounterOptionUnknown .png](mailto:Roguelike@StageEncounterOptionUnknown.png)，roi数据替换至 \resource\global\YoStarJP\resource\task.json 的 "Mizuki@Roguelike@StageEncounterLeaveConfirm" 节点。或者， 如果您在4.20.x版本及之前正常，请删除 \resource\global\ YoStarJP \resource\task.json 的 "Mizuki@Roguelike@StageEncounterLeaveConfirm" 节点，并用旧版本中的 \resource\global\YoStarJP\resource\template\Mizuki@ Roguelike@StageEncounterOptionUnknown.png 替换掉新版本[的](mailto:Roguelike@StageEncounterOptionUnknown.png)。

感谢解答
