### ISSUE TITLE
制造站生产源石碎片时，应先放人，再补货

### ISSUE THREAD

**Issue by nc7s** [MaaAssistantArknights/MaaAssistantArknights#6743]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

前提是我比较随意，偶尔想起来才跑一轮。然后（默认？）配置中宿舍是排在制造站前面的，导致安排完休息后制造站无人，使游戏在补充份数时提示“至少需要配置一名干员后才能执行制造计划”，然后停留在确认执行更改的界面，导致后续任务全部出错。

建议将逻辑改为先换人再补满。

### 日志文件

似乎无需日志，确实需要请告知。

### 截图

<img width="1478" alt="至少需要配置一名干员后才能执行制造计划" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/4474501/6ec1a46f-1137-478e-9eb5-4e51f0709e01">

**Comment by MistEO** [comment]
宿舍排在最后就好了

**Comment by bnoctis** [comment]
是的，但在这里调整逻辑似乎也无不妥，且更严密

**Comment by MistEO** [comment]
没有人改（耸肩，欢迎 PR_(:з」∠)_

**Comment by bnoctis** [comment]
好我看看怎么个改法(｀・ω・´)

**Comment by bnoctis** [comment]
比较玄妙的是，我为了解决肉鸽崩溃的问题编译了 dev 分支（具体是 c483d09e 提交），现在这个问题倒是没提示了，因为只换人不补满了……

制造站上轮制造完成且无人的状态可以通过换人、计划设置为1个、撤人、无人机加速并收取来复现。

我看看怎么个事

**Comment by bnoctis** [comment]
从交流来看，默认设置下宿舍已经在最后，这一问题还需要手动调整过排班顺序（取消勾选再勾选）才会出现。

https://github.com/MaaAssistantArknights/MaaMacGui/blob/dc0dbe35742293a58bc710729d9613fcf90106d4/MeoAsstMac/Configuration Views/InfrastSettingsView.swift#L145-L161

这里，取消勾选时是直接 filter 出来的，会按照既定顺序排列；勾选时却是 append，会加入队尾。

这是另一个问题，和主题的逻辑顺序不冲突。
