### ISSUE TITLE
关于内测版maa会使maa.exe文件消失问题

### ISSUE THREAD

**Issue by Liu2005** [MaaAssistantArknights/MaaAssistantArknights#6744]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

不确定触发条件，maa.exe文件在运行后单独消失了，任务仅执行一次唤醒和战斗，没有任何弹窗显示的情况下maa.exe消失了，在10月7日晚上八点四十触发的，有尝试过重新安装maa

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12838172/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12838173/gui.log)

### 还有别的吗？

mumu12模拟器，win10操作系统，minitouch配置

**Comment by Constrat** [comment]
Check Windows Defender

**Comment by Constrat** [comment]
Duplicate of #6662
