### ISSUE TITLE
使用萨米肉鸽奖励的冰原主题后刷理智报错失败

### ISSUE THREAD

**Issue by 59xiashanle** [MaaAssistantArknights/MaaAssistantArknights#6745]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

4.24.0稳定版
如题描述，把主界面更换成萨米肉鸽95级奖励冰原主题后刷理智无法识别，需要切换回原始主题才行

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12838470/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12838484/asst.log)
大致时间是2023-10-08 02:03:13前后

**Comment by Constrat** [comment]
Check latest alpha version.
If problem persists, reopen the issue
