### ISSUE TITLE
WpfGui设置-界面设置-UI Theme修改无法应用至下一次打开

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#6752]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

UI Theme 修改为 `亮色` / `暗色` ，重启后恢复为与系统同步

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12839771/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12839772/asst.log)

12:20前后开关MAA并尝试调整UI Theme

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/6085e8d6-2485-4a9d-930d-a48b0143b515)

### 还有别的吗？

v4.25.0-beta.1
文件夹限制访问已打开，已添加至白名单，使用时未触发拦截通知
从v4.24.0更新完打开一会就报毒了，后来重启MAA修改UI Theme也不行

（好亮，要瞎啦

**Comment by Cryolitia** [comment]
fix in #6672

**Comment by Cryolitia** [comment]
检查是否存在 `config/gui.new.json`及其内容

**Comment by status102** [comment]
{
  "Configurations": {
    "Default": {
      "GUI": {
        "DarkMode": "Light",
        "UseNotify": true
      }
    }
  },
  "Current": "Default"
}

**Comment by Constrat** [comment]
@Cryolitia Noticed the same after updating. Before it was working properly like we fixed, but then it started not saving like Status said.

**Comment by Constrat** [comment]
```
{
  "Configurations": {
    "Default": {
      "GUI": {
        "DarkMode": "Dark",
        "UseNotify": true
      }
    }
  },
  "Current": "Default"
}
```
Here's mine. If I choose only "Dark" (not sync with OS) at the next startup it will go again with Sync with OS

**Comment by Cryolitia** [comment]
caused by https://github.com/Cryolitia/MaaAssistantArknights/commit/42e9542cd1914193f49afdd6435c2b1a8b6eef22#diff-8f68e6988b089efca72b7954862a47442ec7eb08b37bde5a0c0f072cf4488dd3L9

cc @ABA2396 

setter都没了当然坏掉了…………无语

**Comment by status102** [comment]
每次修qodana总会改出点事（乐
