### ISSUE TITLE
支持自定义更新下载源

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#6753]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

https://t.me/c/1657785089/49531
github raw suki

**Comment by ABA2396** [comment]
现在还有这个问题吗？~~可以改 gui.json 里的 "VersionUpdate.ResourceApi"~~

**Comment by Rbqwow** [comment]
> 现在还有这个问题吗？~~可以改 gui.json 里的 "VersionUpdate.ResourceApi"~~

一直都有 在用host 0000

**Comment by Rbqwow** [comment]
小————水————管————

#9384
