### ISSUE TITLE
自动换班宿舍和发电站均只换了其中一个

### ISSUE THREAD

**Issue by tiyamikatto** [MaaAssistantArknights/MaaAssistantArknights#6755]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104922165/25ff9cd0-d5e8-45cc-93fc-6500fb5efe67)
如图，自动换班执行后，宿舍的换班只执行了第一个宿舍，后续宿舍并没有进行换班操作。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840403/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840404/gui.log)

### 还有别的吗？

模拟器：夜神模拟器7.0.5.0
MAA版本号：v4.25.0-beta.1.d046.gc8d97f58a
换班设置
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104922165/4b427df7-c55d-41e5-8d46-48966ce0d124)

**Comment by tiyamikatto** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104922165/09c02903-37bb-4fce-ab89-9ddd7733ddd0)
如图，发电站亦只更新了第一个，后面的2个发电站并没有被换班

**Comment by skjXvdidbiw** [comment]
加1，从发电站开始，后面所有设施都只换班了第一个

**Comment by status102** [comment]
Duplicate of #6795
