### ISSUE TITLE
自动肉鸽时触发定时执行强制启动不会切换基建计划

### ISSUE THREAD

**Issue by zoe4477** [MaaAssistantArknights/MaaAssistantArknights#6757]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

背景：
设置了强制定时启动和基建自定义排班表（排班表按时间段切换）。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38827851/cee54801-dfc8-4e45-9b43-10cb52bf55a2)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38827851/553779ea-8d90-4920-a0d0-55eb57bd9e2c)

问题：
想要持续整天运行自动肉鸽，且在指定时间强制定时启动进行基建换班和体力消耗。但是发现肉鸽过程中触发定时任务后，使用的排班表还是上一次启动任务时的排班表，基建计划没有按自定义排版表中的时间段进行切换。

### 日志文件

在10.7晚手动启动了任务，定时任务设置在1:30和5:30，但是这两次定时任务使用的排班表都还是启动时那个时间段的。
（日志700多M实在太大了压缩后也无法上传，就截了10.7晚开始的）
[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840507/log.zip)

**Comment by ABA2396** [comment]
排版切换时间和切换配置没啥关系来着，两个基建的时间段分别是什么时候？

**Comment by zoe4477** [comment]
> 排版切换时间和切换配置没啥关系来着，两个基建的时间段分别是什么时候？
基建计划是这样的（log.zip里也上传了基建自定义配置文件）：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38827851/4fc5dd50-5700-4582-804d-9560f5a82473)

手动启动任务的时候是晚上，那时候的基建计划是[A+B]，触发定时任务强制启动的时间是第二天1:30和5:30，本来这两个时间都应该切换成新的基建计划的，但是我看了日志都还是按照最开始启动时的[A+B]计划来排班的
![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38827851/ad288efe-9b27-45bd-845a-445fe9d4694b)
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38827851/d4f8da4f-fc00-47b7-bffb-87b0f856329e)

**Comment by ABA2396** [comment]
奇怪，基建的切换应该是定时器强制的来着）等下看看
