### ISSUE TITLE
从传输流收到意外的 EOF 或 0 个字节

### ISSUE THREAD

**Issue by AtErSi02** [MaaAssistantArknights/MaaAssistantArknights#6759]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

2023.10.8 自动更新后 （v4.24.0）刷1-7时，跳出错误窗口
**不管该错误，依旧正常运作**，但MAA窗口卡死，无法最小化
关闭错误窗口后，windows提示无响应，MAA进程结束

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840541/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840544/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73993198/c4575406-7731-4062-9c56-43a9ea7528f8)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73993198/767e5282-e665-4872-8b2a-1eb675ce4ee4)

### 还有别的吗？

模拟器：BlueStack 4.280.4.4002
操作系统：Windows10

**Comment by zzyyyl** [comment]
Duplicate of #6561

**Comment by zzyyyl** [comment]
v4.25.0-beta.1 fixed
