### ISSUE TITLE
连接手机问题

### ISSUE THREAD

**Issue by tsctsc6** [MaaAssistantArknights/MaaAssistantArknights#676]
v3.3可以通过127.0.0.1:5555连接手机
而v3.9.2不行
![Screenshot 2022-06-01 164343](https://user-images.githubusercontent.com/93368014/171366403-77afe7ee-eae6-4e6d-bd85-215cbe1ee612.png)
![Screenshot 2022-06-01 164416](https://user-images.githubusercontent.com/93368014/171366414-5d0464e9-2f9f-497b-b723-8a7898d25a34.png)
![Screenshot 2022-06-01 164622](https://user-images.githubusercontent.com/93368014/171366417-a7f528b5-cde0-4b0d-b478-e5ac7413802f.png)
![Screenshot 2022-06-01 164657](https://user-images.githubusercontent.com/93368014/171366422-19a8a076-4b58-493f-8581-a6f9d3685e1e.png)
![Screenshot 2022-06-01 164714](https://user-images.githubusercontent.com/93368014/171366428-04217e73-c15c-4521-a09d-ea82c8bb4a36.png)
[asst(v3.9.2).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8812622/asst.v3.9.2.log)
[asst(v3.3).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8812624/asst.v3.3.log)

**Comment by MistEO** [comment]
你地址填的不对，填 `11a0940f` （就是你在命令行敲出来的那个）

**Comment by tsctsc6** [comment]
![image](https://user-images.githubusercontent.com/93368014/171386404-a98ec625-b7ba-446c-b898-65e05bf00cac.png)
这就......不动了！

**Comment by tsctsc6** [comment]
我的手机分辨率2400*1080
不过旧版本还是可以刷理智和公招识别的

**Comment by tsctsc6** [comment]
经测试，v3.3里输入`11a0940f`可以公招识别

**Comment by MistEO** [comment]
因为新版本改了很多东西，都是重写的，短期内没有精力再适配非 16:9 了。有兴趣可以试试用 adb shell wm 来强改分辨率

**Comment by MistEO** [comment]
话说可以试试隔壁 [AAH](https://github.com/ArknightsAutoHelper/ArknightsAutoHelper), 他们是支持宽屏的

**Comment by tsctsc6** [comment]
好的

**Comment by tsctsc6** [comment]
我使用`adb shell wm`改分辨率，分辨率是改了，不过还是不行。

**Comment by tsctsc6** [comment]
我使用`adb shell wm`改分辨率，分辨率是改了，不过还是不行。

**Comment by tsctsc6** [comment]
那我先去用隔壁的[AAH](https://github.com/ArknightsAutoHelper/ArknightsAutoHelper)了，谢谢大佬指点（抱拳）
