### ISSUE TITLE
自动战斗的自动编队无法识别”夜莺“干员

### ISSUE THREAD

**Issue by sur42tur** [MaaAssistantArknights/MaaAssistantArknights#6760]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刚刚打这次纷争演绎s-3出现的bug，明明选择了夜莺3技能，却一直向右滑动，然后又返回最左边，再无限循环。不义之财活动也遇到过一次医疗干员的识别错误，但那次是将夜莺识别成白面鸮，将闪灵识别成了赫默，问了作者说不是作业的问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840558/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840561/gui.log)

**Comment by zzyyyl** [comment]
删 cache/avatars

**Comment by sur42tur** [comment]
> 删 cache/avatars

并没有用

**Comment by sur42tur** [comment]
> > 删 cache/avatars
> 
> 并没有用

重启了一下电脑又可以了，十分的神奇？
