### ISSUE TITLE
v4.25.0-beta.1.d060.g669801ed7 | 测试版更新后软件不启动 

### ISSUE THREAD

**Issue by HKL2580** [MaaAssistantArknights/MaaAssistantArknights#6761]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

内测版更新后无法启动，观察不到程序进程，有”Windows问题报告“进程启动

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840611/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840613/asst.log)

**Comment by Constrat** [comment]
Check #6662
Is this a duplicate?

**Comment by HKL2580** [comment]
> Check #6662 Is this a duplicate?

I've disabled the wdf, the windows issue report is only for when programs encountered fatal issues

**Comment by Constrat** [comment]
You're not on the latest version:
`v4.24.1-alpha.1.d226.g9dd131517`

**Comment by HKL2580** [comment]
> You're not on the latest version: `v4.24.1-alpha.1.d226.g9dd131517`

but the issue arose after I checked update, my maa preference was always on the Alpha test

**Comment by Constrat** [comment]
Seems like it wasn't extracted correctly.
I can see the OTA getting downloaded and extracted

**Comment by HKL2580** [comment]
maybe the update program bugged, deleting the current version files while failing to copy the files of the newer version in

**Comment by aioi50** [comment]
我有相同的问题

**Comment by HKL2580** [comment]
> Seems like it wasn't extracted correctly. I can see the OTA getting downloaded and extracted

yeah it seems so, I'm bad at programming so I'm not intend to look at the logs and dumps

**Comment by aioi50** [comment]
[MAA.exe.14500.dump.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840652/MAA.exe.14500.dump.zip)

**Comment by LengmoAngel** [comment]
I have same problem for it night ota.

**Comment by Kaze-maru** [comment]
> 我也有同样的问题。

俺也一样

**Comment by Constrat** [comment]
### Everyone, we understand, there's no need to repeat it, it just bloats the comments if we need some discussions

**Comment by Lancarus** [comment]
下载这个内测包并取消更新先 https://github.com/MaaAssistantArknights/MaaAssistantArknights/suites/16998774354/artifacts/970995179

**Comment by wu-sv** [comment]
同样的问题，急急急

**Comment by SacribethGrass** [comment]
i met the same issue

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/e779a3ed2bfb9aa20496b4b1bc18f3f44976910d fixed

新版本正在构建

**Comment by wu-sv** [comment]
为什么我回退到4.25.0 beta1 依旧无法打开MAA啊

**Comment by Vvta7** [comment]
> 为什么我回退到4.25.0 beta1 依旧无法打开MAA啊

4.24可以用，但是不能识别新主题

**Comment by SherkeyXD** [comment]
最新的 d63 版本已经更新 可以试试手动下载 d60 到 d63 的 ota 包，然后手动解压替换

**Comment by wangguidong1999** [comment]
> 最新的 d63 版本已经更新 可以试试手动下载 d60 到 d63 的 ota 包，然后手动解压替换

好使，可以用了

**Comment by rwcups** [comment]
我也更新了最新的内测版也不能打开软件
