### ISSUE TITLE
更新至v4.25.0-beta.1.d060.g669801ed7版本后Windows版本无法启动

### ISSUE THREAD

**Issue by inpachi18** [MaaAssistantArknights/MaaAssistantArknights#6763]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新至v4.25.0-beta.1.d060.g669801ed7后Windows版本无法启动，尝试重新下载并清除缓存文件等文件后仍然复现。

### 日志文件

未产生日志文件

**Comment by Constrat** [comment]
Duplicate of #6761
