### ISSUE TITLE
maa资源损坏

### ISSUE THREAD

**Issue by pavocritatus** [MaaAssistantArknights/MaaAssistantArknights#6766]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa在打开后弹窗显示“资源损坏，请重新下载安装包”，但在重新安装后使用一次maa并关闭再打开就又出现这个弹窗，又无法使用了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840701/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106642957/27c23b20-2e39-47a7-9e03-a5465bf6d830)

### 还有别的吗？

mumu模拟器，windows11

**Comment by Constrat** [comment]
Issue is because of a missing template from the auto updater
@MistEO `31083.png`

**Comment by crisike** [comment]
v4.25 被windows识别成木马了，现在只能用4.24的版本

**Comment by Constrat** [comment]
> v4.25 被windows识别成木马了，现在只能用4.24的版本

The Windows Defender problem has already been mentioned in #6662, it's even pinned, there's no need to comment in other random issues

**Comment by MistEO** [comment]
> Issue is because of a missing template from the auto updater @MistEO `31083.png`

这是由于更新了一半退出 MAA 导致的 | This is caused by exiting MAA while updating.

https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/d2bfd50ba4f7c28a7ca155ada694298174c0aac6

**Comment by MistEO** [comment]
![}33({3@@Y%( 6`L$HOURZ(1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/92df5fab-eb14-457c-93c8-ae0a579fa98c)

**Comment by Constrat** [comment]
I've never received any notifications since February xD

**Comment by pavocritatus** [comment]
> ![}33({3@@Y%( 6`L$HOURZ(1](https://user-images.githubusercontent.com/18511905/273451056-92df5fab-eb14-457c-93c8-ae0a579fa98c.png)

原来如此，刚刚重装之后解决了，感谢

**Comment by ABA2396** [comment]
> 资源更新加个进度条和下载速率会不会更好，而且现在资源总是等半天没能自动更新成功，我这几个活动都是手动从GitHub拉的资源，而且资源更新这种无法打断的东西，最好检测到新版本后弹窗让用户手动点确定，并且更新期间禁用关闭窗口按钮

现在更新的时候关掉已经不会报错了，你maa的路径是什么

**Comment by Lixuhuilll** [comment]
> > 资源更新加个进度条和下载速率会不会更好，而且现在资源总是等半天没能自动更新成功，我这几个活动都是手动从GitHub拉的资源，而且资源更新这种无法打断的东西，最好检测到新版本后弹窗让用户手动点确定，并且更新期间禁用关闭窗口按钮
> 
> 现在更新的时候关掉已经不会报错了，你maa的路径是什么

不是报错，是等半天始终没能下载最新的数据，资源文件一直是旧的
