### ISSUE TITLE
招聘许可与加急许可都充足的情况下，自动公招运行一段时间后显示识别错误

### ISSUE THREAD

**Issue by HerrMura** [MaaAssistantArknights/MaaAssistantArknights#6768]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动公招选择使用加急许可，运行一段时间就会遇到报错并返回，然后提示任务完成。
招聘许可和加急许可都充足。
目测是在招聘开始以后没有自动点击加急完成，而是点进了另一个招聘位置，导致的操作顺序错乱。
每一次自动公招都会以这样的方式结束，稳定复现的bug。
在测试版更新里没有找到相关词条，issue检索也都是问的许可不充足的情况，没有看到许可都充足的时候遇到的这种情况

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840688/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840689/gui.log)

出现问题是在14:44:58这个时间

### 截图

![img1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106559052/fff6660f-a2d5-417e-afa0-aa854297a97c)
![MuMu12-20231008-205724](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106559052/bf1030a0-7750-40f0-9e18-19600f9c34c3)
大概是触发了这样的情况，上一个公招没有加急，同时点到了另一个，出现这个界面等几秒就会关闭这个选词条界面，回去加急并完成上一个公招以后MAA就提示错误

### 还有别的吗？

模拟器为Mumu12
操作系统为win11

**Comment by HerrMura** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12841712/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12841713/gui.log)
复现了一下相同情况，这次是在22:38:01出现的

**Comment by horror-proton** [comment]
应该和一个远古问题差不多, 选完职业需求点击 ☑ 之后可能网络有问题或者模拟器卡了, 没有马上完成确认, 这个按钮又被识别到了, 就又点了一次, 然后点到右下角的公开招募位去了 #1491
