### ISSUE TITLE
自动战斗中不能部署空弦

### ISSUE THREAD

**Issue by bronzitro** [MaaAssistantArknights/MaaAssistantArknights#6774]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗中不能部署空弦，好像没有识别到空弦。
作业文件：
[ls4.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840792/ls4.txt)

### 日志文件

2023-10-08 18:49:22.624 左右
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840789/asst.log)

### 截图

使用队伍：
![members](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/4899212/39fba3e8-d360-4b7e-ab12-43497ee74648)
在部署空弦时卡住：
![stuck](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/4899212/35a49c99-7006-4596-847b-4e428547f392)

**Comment by bronzitro** [comment]
蓝叠国际版 5.13.200.1026

**Comment by Constrat** [comment]
Strange, it detects the Mission Start button and clicks it but it doesn't leave the team build interface?

**Comment by bronzitro** [comment]
> Strange, it detects the Mission Start button and clicks it but it doesn't leave the team build interface?
> 
> ```
> [2023-10-08 18:49:13.190][TRC][Px53754][Tx54014] match_templ | BattleStartNormal.png score: 0.999327 rect: [ 1039, 370, 131, 272 ] roi: [ 989, 318, 232, 374 ]
> [2023-10-08 18:49:13.190][INF][Px53754][Tx54014] Assistant::append_callback | SubTaskStart {"class":"asst::CopilotListNotificationPlugin","details":{},"subtask":"asst::CopilotListNotificationPlugin","taskchain":"Copilot","taskid":10,"uuid":"f007ccf5872a3f7d"}
> [2023-10-08 18:49:13.190][INF][Px53754][Tx54014] Assistant::append_callback | SubTaskExtraInfo {"class":"asst::CopilotListNotificationPlugin","details":{},"subtask":"asst::CopilotListNotificationPlugin","taskchain":"Copilot","taskid":10,"uuid":"f007ccf5872a3f7d","what":"CopilotListEnterSuccess"}
> [2023-10-08 18:49:13.190][INF][Px53754][Tx54014] Assistant::append_callback | SubTaskCompleted {"class":"asst::CopilotListNotificationPlugin","details":{},"subtask":"asst::CopilotListNotificationPlugin","taskchain":"Copilot","taskid":10,"uuid":"f007ccf5872a3f7d"}
> [2023-10-08 18:49:13.190][INF][Px53754][Tx54014] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"task":"BattleStartNormal"},"first":["BattleStartAll"],"pre_task":"BattleStartAll","subtask":"ProcessTask","taskchain":"Copilot","taskid":10,"uuid":"f007ccf5872a3f7d"}
> [2023-10-08 18:49:13.190][TRC][Px53754][Tx54014] minitouch click: (1393, 652)
> ```

前一次可能手动点了开始导致脚本没有执行

**Comment by Constrat** [comment]
You can't do that. When MAA is executing, nothing has to be touched.

**Comment by bronzitro** [comment]
> You can't do that. When MAA is executing, nothing has to be touched. If this is why you wrote this issue, I'm closing it.

Please ignore the first execution.
