### ISSUE TITLE
新版本4.25.0不能保持暗色模式，每次开启都需要重新设置

### ISSUE THREAD

**Issue by SacribethGrass** [MaaAssistantArknights/MaaAssistantArknights#6776]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开maa后设置暗色模式，退出maa，再次打开后依然默认“与系统相同”的亮色模式

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840854/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840855/asst.log)

### 还有别的吗？

mumu12模拟器 win11系统

**Comment by Cryolitia** [comment]
caused by https://github.com/Cryolitia/MaaAssistantArknights/commit/42e9542cd1914193f49afdd6435c2b1a8b6eef22#diff-8f68e6988b089efca72b7954862a47442ec7eb08b37bde5a0c0f072cf4488dd3L9

cc @ABA2396

**Comment by Cryolitia** [comment]
duplicate #6752

**Comment by ABA2396** [comment]
草）删了我还测了下能跑来着

**Comment by status102** [comment]
Duplicate of #6752

**Comment by Cryolitia** [comment]
> 草）删了我还测了下能跑来着

反射访问那当然是能编译的（扶额）
