### ISSUE TITLE
MAA 报错：从传输流收到意外的 EOF 或 0 个字节

### ISSUE THREAD

**Issue by MChello1990** [MaaAssistantArknights/MaaAssistantArknights#6780]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

报错弹窗:
MAA 遇到了问题
从传输流收到意外的 EOF 或 0 个字节。
解决方案
出现未知错误

此问题之前从未出现过 直到今天 两次启动后不久均会出现此报错 疑似更新检查程序出错? 使用是正常的 关闭报错弹窗后MAA会自动关闭

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840894/debug.zip)
Log出错时间[2023-10-08 21:55:00.626]

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30387541/eabb0b05-fac6-47fd-9a29-f212b8159d01)

### 还有别的吗？

模拟器:MUMU12
系统:Windows 10 21H2 build 19044.3086
网络环境:WLAN

**Comment by shadow150519** [comment]
我也遇到了这个错误

**Comment by Constrat** [comment]
Duplicate of #6561 update to latest version
