### ISSUE TITLE
自动作战部署桃金娘时会错选维荻

### ISSUE THREAD

**Issue by aioi50** [MaaAssistantArknights/MaaAssistantArknights#6789]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗桃金娘和维狄同时存在的情况下，部署桃金娘时会错选维荻

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12841031/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12841033/gui.log)
发生时间：23:20至23:22

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/65849197/ae12706d-59d7-4b47-8ff9-5630f29b24f2)

### 还有别的吗？

模拟器mumu12
maa版本v4.25.0-beta.1.d063.ge779a3ed2

**Comment by Constrat** [comment]
Have you tried deleting `cache/avatars`

**Comment by aioi50** [comment]
> Have you tried deleting `cache/avatars`

Thank you, the problem is solved.
