### ISSUE TITLE
远程控制协议增加"强制执行某任务"任务和"强制停止当前任务"任务

### ISSUE THREAD

**Issue by s-yh-china** [MaaAssistantArknights/MaaAssistantArknights#6791]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

maa有时会在某些位置卡住无法执行下个内容，这时使用远程控制协议也无法下发新任务
在这时用户可能想查看maa或模拟器当前状态，截图任务被之前的任务卡住无法运行，我们就无法得知截图的结果

### 有什么好的想法？

增加"强制执行某任务"的任务，比如截图
同时添加"强制停止当前任务"或"强制清空当前任务列表"的任务，来便于我们终止卡死的任务或更换新任务

**Comment by s-yh-china** [comment]
> 既然这样，那为什么不再加一个任务，立即执行，汇报当前正在执行的任务ID呢（

这部分应该是远程端应该考虑的东西(?
maa的远程控制是顺序执行的，所以只要上一个任务没有发回报告就可以说明还在运行这个任务(maa运行任务时离线另外考虑)

**Comment by hsyhhssyy** [comment]
既然你要强制终止，那得有个任务可以用来心跳吧，比如MAA死机了，你可以每个几秒十几秒问一下他当前任务，心跳失败通知用户啥的。

**Comment by s-yh-china** [comment]
> 既然你要强制终止，那得有个任务可以用来心跳吧，比如MAA死机了，你可以每个几秒十几秒问一下他当前任务，心跳失败通知用户啥的。

如果maa完全卡死了，getTask也会跟着卡死 ~大概~ 
但是如果是其他原因进入了循环，我们并不知道正在运行的任务是否是卡死还是正常运行，这时候只能是获取一个截图让用户自己判断了
~C#好难写~

**Comment by s-yh-china** [comment]
这个怎么没关
