### ISSUE TITLE
基建排班运行bug | Infrast only 1 Dorm fix

### ISSUE THREAD

**Issue by MUzyx** [MaaAssistantArknights/MaaAssistantArknights#6795]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建换人时跳过某些设施，更新前无此项BUG，更新为此版本后出现该BUG，已重装MAA三次、重启系统一次、重启模拟器两次，均可复现此BUG

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12841265/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12841266/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125632753/07340963-7d08-43ef-8482-1c5bb97a68ad)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125632753/9c0f5ee1-50ab-4833-8b62-9f927c153ef7)

### 还有别的吗？

系统版本：Windows 10 Version 22H2
MAA版本：v4.25.0-beta.1.d063.ge779a3ed2
模拟器版本：雷电9.0.44
基建换班配置文件编号：1696784340996147

**Comment by Constrat** [comment]
Duplicate of #6794 
We are working on it.

**Comment by MUzyx** [comment]
那么该怎么做呢？

**Comment by Constrat** [comment]
> 那么该怎么做呢？

Wait

**Comment by MUzyx** [comment]
> > 那么该怎么做呢？
> 
> Wait

OK

**Comment by Constrat** [comment]
If you want to try, you can revert the changes of this [PR](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6741/files)

**Comment by Constrat** [comment]
Ok I've tested with the new tasks.json and it works correctly

**Comment by Constrat** [comment]
Ok I've tested with the new tasks.json and it works correctly

**Comment by MUzyx** [comment]
> Ok I've tested with the new tasks.json and it works correctly

thank
