### ISSUE TITLE
4.25版本打不开

### ISSUE THREAD

**Issue by You-Qin** [MaaAssistantArknights/MaaAssistantArknights#6796]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最新4.25beta版本自动更新之后打不开，双击没有反应

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12841286/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12841287/gui.log)

### 还有别的吗？

使用操作系统win11 台式机和笔记本都出现了 应该不是个例

**Comment by Constrat** [comment]
This has already been fixed
Update to `alpha/v4.25.0-beta.1.d063.ge779a3ed2`

**Comment by Constrat** [comment]
Duplicate of #6761
