### ISSUE TITLE
新界面主题无法识别

### ISSUE THREAD

**Issue by Lihuayy** [MaaAssistantArknights/MaaAssistantArknights#6798]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

新的界面主题识别错误，只有日间的主题可以识别

### 日志文件

不方便上传

**Comment by SherkeyXD** [comment]
什么版本

**Comment by ccz97663** [comment]
> 什么版本
4.24.0 稳定版  我刚试了一下夜间确实不行  日间没问题

**Comment by SherkeyXD** [comment]
4.24 没有适配 现在的公测版 4.25-beta1 适配了 如果急的话可以试试

**Comment by Lihuayy** [comment]
好的，谢谢指路




bilibili
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月9日(星期一) 上午10:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 新界面主题无法识别 (Issue #6798)





 
4.24 没有适配 现在的公测版 4.25-beta1 适配了 如果急的话可以试试

**Comment by Lihuayy** [comment]
感谢各位的帮助
&nbsp;


bilibili
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月9日(星期一) 上午10:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 新界面主题无法识别 (Issue #6798)





 
Closed #6798 as completed.
 
&mdash;
