### ISSUE TITLE
MAA频繁报System.IO.IOException

### ISSUE THREAD

**Issue by WeebOwO** [MaaAssistantArknights/MaaAssistantArknights#6799]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在噩兆湍流版本更新过后MAA频繁报System.IO.IOException

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12842262/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50624245/ae25aa8f-9b97-46fe-817c-dc48ab5b3420)

### 还有别的吗？

模拟器: MuMu12 V3.5.20
OS: win11 22h2
MAA: 4.24.0

**Comment by broken-paint** [comment]
Duplicate of #6561

**Comment by WeebOwO** [comment]
Thank you,  I will close this issue.
