### ISSUE TITLE
自动肉鸽时会持续点着某个干员准备释放技能

### ISSUE THREAD

**Issue by HerrMura** [MaaAssistantArknights/MaaAssistantArknights#680]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8813377/asst.log)
模拟器：bluestacks 5 64位
MAA版本：3.9.2
在自动肉鸽的时候，发现有两次会一直点着干员准备释放技能。其他干员技能冷却结束以后会正常地过去释放干员技能，然后接着点回来待命。并非每次都是在同一个干员身上出现这个问题，第一次是安塞尔，第二次是梓兰。并非每一局都会这样，不知道具体是这样设计的还是bug。

如图所示
<img width="928" alt="82e3016bf1006f9b7bed6443104e698" src="https://user-images.githubusercontent.com/106559052/171388234-f5c671cd-84ce-475d-83f9-5bc113b45518.png">
<img width="928" alt="1f165c883c5aa34bc8cc5d138a48247" src="https://user-images.githubusercontent.com/106559052/171388286-78f997ce-f169-47a6-9b01-9bddd53c27ab.png">
<img width="928" alt="71c8306e872324419e40615981b8a34" src="https://user-images.githubusercontent.com/106559052/171388326-5ac3d22c-a905-4ec2-a543-8fb624b72dc0.png">

**Comment by HerrMura** [comment]
就算开了技能以后也会一直点着，前面没有截图到，并非是技能cd的时候才这样

**Comment by infstellar** [comment]
确实，我也遇到了

**Comment by MistEO** [comment]
v3.9.4 肉鸽改了释放技能的一些逻辑，可能修了这个 bug (也可能没修)，再遇到的话再帮忙发下吧~

**Comment by MillionBones** [comment]
新版出现了，可能是16:9分辨率选定之后，拉伸窗口导致的
