### ISSUE TITLE
点击某个任务后maa崩溃

### ISSUE THREAD

**Issue by yutuer** [MaaAssistantArknights/MaaAssistantArknights#6801]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 遇到了问题
拒绝访问。
解决方案
出现未知错误
详细信息
System.ComponentModel.Win32Exception (0x80004005): 拒绝访问。
   在 System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   在 MaaWpfGui.Helper.WinAdapter.GetAdbAddresses(String adbPath)
   在 MaaWpfGui.ViewModels.UI.SettingsViewModel.DetectAdbConfig(String& error)
   在 MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<ConnectToEmulator>d__74.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<LinkStart>d__75.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

System.ComponentModel.Win32Exception (0x80004005): 拒绝访问。

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/4254461/cb670f35-58b8-43f1-9745-b38be37a0d82)

**Comment by ABA2396** [comment]
没日志看不了  拒绝访问一般是权限不够，试试管理员权限启动
