### ISSUE TITLE
ota更新后无法打开4.25.0，回滚4.24.0后报告错误 无法访问已释放的对象，对象名SslStream

### ISSUE THREAD

**Issue by GloomyBee** [MaaAssistantArknights/MaaAssistantArknights#6802]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

ota更新后无法打开4.25.0，回滚4.24.0后报告错误 无法访问已释放的对象，对象名SslStream

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12842369/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12842370/gui.log)
2023-10-9 10:34:00左右

### 截图

<img width="450" alt="Snipaste_2023-10-09_10-42-26" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142166433/03acc64f-ee8f-41d8-86dd-4209b9f884ad">

**Comment by SherkeyXD** [comment]
试试最新的内测版

**Comment by oracleless** [comment]
打开v4.25.0-beta.1稳定版MAA提示资源损坏，重启windows后同样提示，重新安装稳定版后同样提示，更改安装路径也同样提示。
打开明日方舟后，发现9:00am的基建换班正常完成，大概率是早上九点后的稳定版更新出了问题。

**Comment by MistEO** [comment]
试试最新的内测版
