### ISSUE TITLE
自动战斗携带干员过多时会因干员头像位置移动导致识别错误

### ISSUE THREAD

**Issue by LonelyWindG** [MaaAssistantArknights/MaaAssistantArknights#6803]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

前置条件: 携带干员过多(没详细测试几个以上, 至少12/13个是会出现的)时部署栏头像会变窄,  点击头像时点击干员头像变宽, 其他干员头像位置发生移动
问题: 此时未识别干员的点击位置应该是刚开局时识别到的位置吧? 选中干员后头像原位置发生变化, 会导致实际识别到的未识别干员头像是其他干员的头像

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12842393/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12842394/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46588195/9b076e58-7395-4d5c-b3ed-bbff76cc6cdb)

**Comment by Constrat** [comment]
We are aware of this issue.
Try bringing less operators and delete cache/avatars
