### ISSUE TITLE
使用无人机加速订单时，如果无人机不足以加速一个订单会卡住

### ISSUE THREAD

**Issue by zaiziw** [MaaAssistantArknights/MaaAssistantArknights#681]
在trade0卡了十分钟之后发现，MAA一直在试图加速订单，但是我已经没有无人机了，所以没法继续了。直到贸易站自然恢复下一个订单之后，才继续执行下一个任务（更换贸易站干员）
![~HV7CI@4P`3_5DN XYI2}7A](https://user-images.githubusercontent.com/27818332/171389679-0592ebba-90f0-42b9-8a50-c4cf39f9fe3b.png)

**Comment by MistEO** [comment]
麻烦附一下日志文件，谢谢
