### ISSUE TITLE
无法打开MAA

### ISSUE THREAD

**Issue by johhnykk** [MaaAssistantArknights/MaaAssistantArknights#6811]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天内测版更新完之后MAA就不见了，之后也都无法开启

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12843231/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12843232/asst.log)

**Comment by MistEO** [comment]
刚发了一版，再更新一下
