### ISSUE TITLE
远程控制功能文档跳转网址404

### ISSUE THREAD

**Issue by warningme** [MaaAssistantArknights/MaaAssistantArknights#6817]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

设置里的“远程控制功能开发者文档”跳转网址是404的，具体看截图

### 日志文件

这个是网站问题，就不用log了吧

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46251540/4e1489ec-0ce7-4aae-a777-17a553cc11c3)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46251540/e145bb98-2fc2-43ba-b2e8-330210a0f76b)

**Comment by ABA2396** [comment]
官网文档是对应正式版的内容，测试版的在主仓库看 [3.8-远程控制协议.md](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/3.8-%E8%BF%9C%E7%A8%8B%E6%8E%A7%E5%88%B6%E5%8D%8F%E8%AE%AE.md) 等下我给区分下

**Comment by broken-paint** [comment]
fixed by v4.25.0-beta.2
