### ISSUE TITLE
4.25 beta版触发windows杀毒软件？

### ISSUE THREAD

**Issue by jackxsm** [MaaAssistantArknights/MaaAssistantArknights#6821]
### 说说你遇到的问题？

昨天和今天连续碰到两次，直接把maa主程序删了。昨天捡回来后设了白名单，今天不知道是不是更新后又被杀了。因为是远程操作的，不确定今天被杀之前有没有更新。贴一个截图
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/13896165/39aaa8fd-bdbd-4465-8e28-d601a71cce57)

**Comment by Constrat** [comment]
Duplicate of
-#6662

**Comment by Constrat** [comment]
Duplicate of 
- #6662
