### ISSUE TITLE
干员识别存在缺漏

### ISSUE THREAD

**Issue by FadingTime** [MaaAssistantArknights/MaaAssistantArknights#6823]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

干员识别识别不出来红蒂,归痧和维荻

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12845680/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12845685/gui.log)
[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12845686/oper.zip)

### 截图

[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12845690/oper.zip)

**Comment by Constrat** [comment]
There is no flaw. MAA can't read operators that are "favourites"
