### ISSUE TITLE
开始任务出错

### ISSUE THREAD

**Issue by xmanthony** [MaaAssistantArknights/MaaAssistantArknights#6825]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147403590/46aed384-5b68-4ea7-8e03-8cde91ec5d84)
最近不管是家里还是公司的电脑，都无法自动刷离职，不知道怎么回事

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12845999/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12846000/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147403590/2ddd01f4-c8f6-4598-8ded-ed4f635391b5)

**Comment by broken-paint** [comment]
```
{"class":"asst::ProcessTask","details":{"cur_retry":5,"retry_times":5,"to_be_recognized":["Fight@ReturnTo","Fight","Fight@CloseAnno","Fight@CloseAnnoTexas","Fight@TodaysSupplies","Fight@NotDownloadVoice","Fight@StartUp","Fight@FromStageSN"]},"first":["StageBegin"],"pre_task":"StageBegin","subtask":"ProcessTask","taskchain":"Fight","taskid":2}
[2023-10-09 20:19:24.367][INF][Px6aa8][Tx61f8] Call ` adb/platform-tools/adb.exe -s 127.0.0.1:16384 exec-out "screencap | nc -w 3 10.0.2.2 55816" ` ret 0 , cost 319 ms , stdout size: 0 , socket size: 8294416
[2023-10-09 20:19:24.374][TRC][Px6aa8][Tx61f8] asst::PipelineAnalyzer::analyze Fight@ReturnTo
[2023-10-09 20:19:24.375][TRC][Px6aa8][Tx61f8] asst::PipelineAnalyzer::analyze Fight
[2023-10-09 20:19:24.377][TRC][Px6aa8][Tx61f8] asst::PipelineAnalyzer::analyze Fight@CloseAnno
[2023-10-09 20:19:24.380][TRC][Px6aa8][Tx61f8] asst::PipelineAnalyzer::analyze Fight@CloseAnnoTexas
[2023-10-09 20:19:24.381][TRC][Px6aa8][Tx61f8] asst::PipelineAnalyzer::analyze Fight@TodaysSupplies
```
是不是换主题了？

**Comment by broken-paint** [comment]
> > ```
> > {"class":"asst::ProcessTask","details":{"cur_retry":5,"retry_times":5,"to_be_recognized":["Fight@ReturnTo","Fight","Fight@CloseAnno","Fight@CloseAnnoTexas","Fight@TodaysSupplies","Fight@NotDownloadVoice","Fight@StartUp","Fight@FromStageSN"]},"first":["StageBegin"],"pre_task":"StageBegin","subtask":"ProcessTask","taskchain":"Fight","taskid":2}
> > [2023-10-09 20:19:24.367][INF][Px6aa8][Tx61f8] Call ` adb/platform-tools/adb.exe -s 127.0.0.1:16384 exec-out "screencap | nc -w 3 10.0.2.2 55816" ` ret 0 , cost 319 ms , stdout size: 0 , socket size: 8294416
> > [2023-10-09 20:19:24.374][TRC][Px6aa8][Tx61f8] asst::PipelineAnalyzer::analyze Fight@ReturnTo
> > [2023-10-09 20:19:24.375][TRC][Px6aa8][Tx61f8] asst::PipelineAnalyzer::analyze Fight
> > [2023-10-09 20:19:24.377][TRC][Px6aa8][Tx61f8] asst::PipelineAnalyzer::analyze Fight@CloseAnno
> > [2023-10-09 20:19:24.380][TRC][Px6aa8][Tx61f8] asst::PipelineAnalyzer::analyze Fight@CloseAnnoTexas
> > [2023-10-09 20:19:24.381][TRC][Px6aa8][Tx61f8] asst::PipelineAnalyzer::analyze Fight@TodaysSupplies
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 是不是换主题了？
> 
> 是的，不能换主题吗？

目前好像只对原色，深色和萨米做了适配，如果是新主线的现在可能还用不了 :(

**Comment by Constrat** [comment]
You are still on the 4.24.0. How do you expect MAA to understand a new theme when that version is older than the introduction? Update MAA and you'll see that it works.

**Comment by xmanthony** [comment]
> You are still on the 4.24.0. How do you expect MAA to understand a new theme when that version is older than the introduction? Update MAA and you'll see that it works.

But 4.25.0 is not officially released. I check for updates several times but it still stays at 4.24.0.

**Comment by broken-paint** [comment]
在公测版 `v4.25.0-beta.1` 里面更新了这个内容，你需要在设置里切换到公测版然后重新启动
或者等到稳定版发布 qwq

**Comment by Constrat** [comment]
We are having major issues with ota updates. 
But just checking for stable releases is not an excused solution. We release, almost daily, nightly version with usually major bug fixes. Before opening issues, ALWAYS check if the latest version (even a nightly) has already been fixed.
Having to check every issue takes time. Time that can be used fixing other things. Please be mindful of this in the future ^_^
