### ISSUE TITLE
無法使用開機自動開啟功能

### ISSUE THREAD

**Issue by eason101036** [MaaAssistantArknights/MaaAssistantArknights#6831]
### 说说你遇到的问题？

殺毒軟體刪了，但是依舊無法自動開啟，MAA是可以正常開啟的，但是「開機自動開啟」這個功能無法開啟，我只要一打開，關閉MAA後再次開啟該功能依舊是未開啟狀態

**Comment by Constrat** [comment]
Have you checked in Windows Defender? We've been having some false positives with Windows particurarly
- Check out  #6662

**Comment by eason101036** [comment]
> 您檢查過 Windows Defender 嗎？特別是在 Windows 上我們遇到了一些錯誤報告
> 
> * 看  [Windows Defender誤報木馬 |](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662)[木馬誤報](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662)[ #6662](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662)[](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662)

檢查過了，但沒有效果

**Comment by Constrat** [comment]
Then you might want to change this from `question` to `bug` and send your asst.log and gui.log when the issue happens.

**Comment by eason101036** [comment]
> 然後您可能需要將其更改為`question`並`bug`在問題發生時發送您的 asst.log 和 gui.log。

K

**Comment by eason101036** [comment]
[](url)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12848984/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12848985/gui.log)

debug

**Comment by ABA2396** [comment]
按下【win+R】打开运行输入：【shell:Startup】，里面没有maa的快捷方式吗

**Comment by WSMTBG** [comment]
> 按下【win+R】打开运行输入：【shell:Startup】，里面没有maa的快捷方式吗

那什么，我以前直接在启动里加了maa快捷方式，开机的时候也起不来，，现在是用的任务计划程序勾选最高权限运行

**Comment by ABA2396** [comment]
搞不懂，用管理员权限启动试过了吗？

**Comment by eason101036** [comment]
> 搞不懂，用管理员权限启动试过了吗？

有，沒效
沒辦法直接用工作排程器排了

**Comment by ABA2396** [comment]
现在估计可以了)
