### ISSUE TITLE
刷理智吃源石功能无法触发

### ISSUE THREAD

**Issue by maxanmps** [MaaAssistantArknights/MaaAssistantArknights#6833]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷理智吃源石功能无法触发，吃理智药可以正常吃
账号内还有源石，尝试过右键的选择（方框选）和增加理智药数量之后吃源石选项变为对勾选，均无法正常触发吃源石

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12848410/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12848411/gui.log)

### 截图

有录屏但是穿不上来
![MAA截图](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/41883384/7d2a8684-6183-4539-b112-bd36947a5cae)

### 还有别的吗？

MUMU12
WINDOWS10
MAA v.4.24.0

**Comment by Constrat** [comment]
have you waited enough time?
You have `"DrGrandet":true` this means that it will wait the change of sanity (+1) before using sanity medicine and / or Originium Stones

**Comment by ABA2396** [comment]
日志只到2023-10-10 00:24:40.929，你后面的没传上来

**Comment by zzyyyl** [comment]
理智药没吃完吧

**Comment by maxanmps** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12855995/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12855996/gui.log)


> Have you waited long enough? You have `"DrGrandet":true` this means that it will wait the change of sanity (+1) before using sanity medicine and / or Originium Stones

I have make DrGrandet off for testing this bug, and also in screenshot, it shows all missions complete, which is not waiting for any further action and the button from "stop" to "link start!" again which i believe is the sign of all program is ending.



> 日志只到2023-10-10 00:24:40.929，你后面的没传上来

之前传完之后又自己测试了两遍，但没传最新的，现在重新传了



> 理智药没吃完吧

现在理智药没吃完不给碎石吗，我记得以前好像不是这样的

**Comment by Constrat** [comment]
MAA won't use originium stones until you ended all your potions.

**Comment by maxanmps** [comment]
> MAA won't use originium stones until you ended all your potions.

OK, thanks

**Comment by zzyyyl** [comment]
> > 理智药没吃完吧
> 
> 现在理智药没吃完不给碎石吗，我记得以前好像不是这样的

一直说这样的）
