### ISSUE TITLE
自动作战中无法识别到艾雅法拉

### ISSUE THREAD

**Issue by inpachi18** [MaaAssistantArknights/MaaAssistantArknights#6834]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动作战中无法识别到艾雅法拉，查看日志文件后发现艾雅法拉位置被识别为重复的前一个干员。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12849219/asst.log)

### 截图

![tough_13-11](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/60968460/ae381f0c-df09-4f7f-9b81-169894c32672)

**Comment by HoshinoAyako** [comment]
关掉maa，清空Cache\avatars
