### ISSUE TITLE
更换主题之后maa无法进行任务

### ISSUE THREAD

**Issue by Wdaisuku** [MaaAssistantArknights/MaaAssistantArknights#6837]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题

### 有什么好的想法？

尽管我也知道是因为换了主题之后maa无法识别新主题的图片（应该是这样吧），所以我只是来催一下更新

**Comment by Wnky6457** [comment]
同，但仅有新实装的迷城主题无法开始任务，之前的日间/夜间/银凇则没有问题

**Comment by SherkeyXD** [comment]
能提供一张迷城主题的截图吗 最好是1280x720的

**Comment by WSMTBG** [comment]
> 能提供一张迷城主题的截图吗 最好是1280x720的

1920可以吗
![Screenshot_2023 10 10_13 56 06 541](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/62c10253-522a-46c0-a4b1-0eced55339db)

**Comment by WSMTBG** [comment]
> 能提供一张迷城主题的截图吗 最好是1280x720的

1920可以吗
![Screenshot_2023 10 10_13 56 06 541](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/66d60db2-36bd-4cb7-9e59-cb96f2f63350)

**Comment by Constrat** [comment]
With1920 we just need to downscale with bicubic.
@SherkeyXD I'll be out the entire day, I won't be able do add this

**Comment by WSMTBG** [comment]
@Constrat @SherkeyXD 1280
![Screenshot_2023 10 10_14 41 07 726](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/c89a6caa-989b-461b-88aa-beea83c89ec7)

**Comment by Wdaisuku** [comment]
啊 下午上课了，没看见，抱歉捏，也谢谢发了图片的兄弟

**Comment by Wdaisuku** [comment]
啊 下午上课了，没看见，谢谢作者们以及发图片的兄弟

**Comment by SherkeyXD** [comment]
已经适配完毕
