### ISSUE TITLE
希望账号切换能增加切换后能自动留空和下拉选择功能

### ISSUE THREAD

**Issue by LonelyWindG** [MaaAssistantArknights/MaaAssistantArknights#6838]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

希望账号切换能有的新功能:
1.类似保存连接地址并可以下拉选择的功能
2.开始任务: StartUp开始时, 如果输入了切换账号, 直接输出已输入的切换账号
3.增加一个每次切换账号成功后自动留空
4.在游戏内登出时, 用户中心界面识别当前登入的账号, 与要切换账号一致时不再重登而是直接回到主界面(没有影响不大)

两个号同时玩切来切去, 有1功能的话不需要每次重新输入会方便一些;
2,3是MAA启动后自动显示"刷理智"的页面, 没注意检查"开始唤醒"页面的账号有没有清空或选对账号, 可能没注意进错账号;
2功能能在开始唤醒任务开始时直接看到要切换的账号正不正确;

**Comment by status102** [comment]
做两份配置能解决1、3

**Comment by status102** [comment]
4似乎是本地数据，暂不考虑调整流程
