### ISSUE TITLE
蓝叠模拟器5（Hyper-V）连接问题

### ISSUE THREAD

**Issue by MikeQu223** [MaaAssistantArknights/MaaAssistantArknights#684]
蓝叠模拟器5（hyper-v）的adb 端口在每次重启时都会随机化（如图）
而且安装目录下没有bluestacks.conf文件
建议使用 https://github.com/eviltik/evilscan 扫描adb端口：）

![3](https://user-images.githubusercontent.com/63991532/171405778-61d72e7e-17ad-42fa-a3fd-5a96346147ab.png)
![1](https://user-images.githubusercontent.com/63991532/171405794-56706a82-a801-4d0c-bd13-17988e46acf9.png)
![2](https://user-images.githubusercontent.com/63991532/171405805-89529021-1dca-441c-9747-274ffa10b25f.png)
![file](https://user-images.githubusercontent.com/63991532/171405813-2bd0efe6-4029-4db2-a2e0-cd84f778dbbc.png)

连接日志：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8814081/asst.log)

**Comment by hexsix** [comment]
conf 默认路径在 C:\ProgramData\BlueStacks_nxt

你找找？

**Comment by MikeQu223** [comment]
感谢，能正常连接了
"Bluestacks.Config.Path":"C:\\ProgramData\\BlueStacks_nxt\\bluestacks.conf",
![bsconf](https://user-images.githubusercontent.com/63991532/171432404-a22cffe9-41ea-47b5-8025-294c1f12b296.png)
