### ISSUE TITLE
增加新的截图方式切换功能以解决WSA中adb截图功能缺陷不能使用MAA问题

### ISSUE THREAD

**Issue by SSG233** [MaaAssistantArknights/MaaAssistantArknights#6842]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

增加除adb截图外的其他截图方式
听说已经支持win32但还没有上线GUI 请求尽快上线谢谢谢谢（

**Comment by MistEO** [comment]
没有，没人集成（

https://github.com/MaaAssistantArknights/libWSAController 库在这里
