### ISSUE TITLE
4.25.0正式版被win11报毒

### ISSUE THREAD

**Issue by caoyuan5113** [MaaAssistantArknights/MaaAssistantArknights#6848]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

10/10日18：00左右启动，提示更新，自动更新后整个文件夹消失。回github重新下载解压后报毒。
怀疑自动更新后消失是被defender抄家清掉了。说实话不好说这是不是bug，不过maa以前从未报毒过。
win11版本：“2023-08 用于 .NET Framework 3.5 和 4.8.1 的累积更新，适合基于 x64 的 Windows 11, version 22H2 (KB5028948)”

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12855937/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12855941/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124412622/074336b0-56fc-4c46-b76b-08ac99a4adbf)

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.H!ml&threatid=2147814524
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124412622/222f3ba8-9cc8-4cc9-a3cc-53cdb004a53e)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124412622/b2080983-1034-45ad-94bc-973be2e3511f)
不懂程序，可能有帮助。

**Comment by JRYKoishi** [comment]
+1 我的maa也被报毒干掉了

**Comment by wotaoyanh** [comment]
+1

**Comment by zzyyyl** [comment]
Duplicate of #6662
