### ISSUE TITLE
自动战斗闪退

### ISSUE THREAD

**Issue by 04linshi** [MaaAssistantArknights/MaaAssistantArknights#685]
![QXQ_YU$ KRL9{ 6(~@THPA](https://user-images.githubusercontent.com/106676717/171410912-7fdebeee-8ff0-4eb4-ab77-8285d52b459f.png)
![VWT1H~@_ F@D R$5}M2_BUN](https://user-images.githubusercontent.com/106676717/171411040-602dc7fd-2ae4-49bf-a7ce-be4b65817dc6.png)

在连接模拟器的时候闪退

**Comment by MistEO** [comment]
日志文件直接发一下吧，截图信息太少了

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/692 可能是这个问题

**Comment by 04linshi** [comment]
> #692可能是这个问题

完整的作业可以运行，并且生成了map。可能是没有添加干员的原因。
