### ISSUE TITLE
能不能自动借助战干员？

### ISSUE THREAD

**Issue by SaltedX** [MaaAssistantArknights/MaaAssistantArknights#6850]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在自动编队时如果没有干员就会停止编队，而手动加入干员也不行

**Comment by HoshinoAyako** [comment]
手动加入干员，就不需要自动编队了。
不过可以提建议让MAA TEAM弄个自动编队编队助战干员

**Comment by status102** [comment]
- duplicate of #6023
