### ISSUE TITLE
MAA自动升级版本后闪退

### ISSUE THREAD

**Issue by AKPRTS** [MaaAssistantArknights/MaaAssistantArknights#6851]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

每次MAA自动升级之后自动打开就会丢配置一段时间后闪退  然后MAA.exe会自动删除掉 
问题必现  今天晚上9.30分自动升级左右又出现了一次 

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12857796/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12857812/gui.log)

**Comment by AKPRTS** [comment]
我重新解压了一个 MAA.exe启动过  日志好像不全  但根据我这几天的情况来看  每次升级都会出现这个问题

**Comment by Constrat** [comment]
Check #6662

**Comment by SherkeyXD** [comment]
看看你的电脑是否启用了 Windows Defender

**Comment by tuyangsheng** [comment]
是的windows defender报毒了，
类别：特洛伊木马

**Comment by ABA2396** [comment]
#6662
