### ISSUE TITLE
maa.exe被windows defender识别为病毒

### ISSUE THREAD

**Issue by Qzjv2** [MaaAssistantArknights/MaaAssistantArknights#6852]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

windows版本win 10Pro，maa版本为更新至v4.25.0，之前更新公测版的同样版本是没事的，其他看截图吧，报错不好复制

### 日志文件

无

### 截图

![maa error](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144880272/ef6a9af5-827b-47ac-aab5-4b0d8396c360)

**Comment by Constrat** [comment]
Duplicate of #6662
