### ISSUE TITLE
更换界面主题后MAA无法识别界面继续执行任务

### ISSUE THREAD

**Issue by soulhowing** [MaaAssistantArknights/MaaAssistantArknights#6853]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更换界面主题后MAA无法识别界面继续执行任务

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12857971/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12857981/gui.log)

### 截图

![MuMu12-20231010-215136](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147522429/b71dc178-28cf-49da-935d-6f9d62a196a5)

**Comment by Constrat** [comment]
This has already been fixed

**Comment by Constrat** [comment]
Fixed in 860b978
