### ISSUE TITLE
希望延长StartUp失败判定时长

### ISSUE THREAD

**Issue by NickerGrylls** [MaaAssistantArknights/MaaAssistantArknights#6854]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

本人的电脑配置为12100+5600，算是带得动大部分游戏，但模拟器中方舟启动的速度比较玄学，从10秒以内到超时触发MAA的“任务失败”判定均有可能
由于StartUp是最先进行的，当任务失败时，很显然整个整个流程都将无法进行。由于有过教训，我在进行重要的刷取（例如周日时将即将过期的理智药用完）前必须亲自盯着程序运行，并在启动较慢的情况下手动中止MAA任务并再次开始

### 有什么好的想法？

延长StartUp任务失败的判定时长

**Comment by NickerGrylls** [comment]
> 在「啟動設定」內自行設置「等待模擬器時間」應該就能解決了？

你提到的设置针对的是“模拟器的启动”，这实际上不是StartUp任务的一部分
我指的是“从MAA点开方舟图标到下一个需要点击的画面”的过程（即下面的图一到图二的加载过程）（繁中服或许有所区别，但大体应该是一样的
![2023-10-11_00-18-49](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120347871/97ae4302-6fda-4ccc-95b1-56157603cdd3)
![2023-10-11_00-18-55](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120347871/ec9116b3-5caa-4b2e-8798-91a7e4207e07)
）

**Comment by vonnoq** [comment]
你直接讓MAA去啟動方舟，而不是只啟動模擬器讓它在app頁面待機的話，它就會在你設定的等待時間內先載入到圖二了

**Comment by NickerGrylls** [comment]
> 你直接讓MAA去啟動方舟，而不是只啟動模擬器讓它在app頁面待機的話，它就會在你設定的等待時間內先載入到圖二了

能否请问一下具体操作呢？是需要用到 连接设置-开始前脚本 或是 启动设置-附加命令 吗？
还是说你们使用的模拟器能够将“启动模拟器，然后启动方舟”这一操作打包为一个exe程序？

**Comment by NickerGrylls** [comment]
Remove {Client: ZH_TW}

**Comment by ABA2396** [comment]
> > 你直接讓MAA去啟動方舟，而不是只啟動模擬器讓它在app頁面待機的話，它就會在你設定的等待時間內先載入到圖二了
> 
> 能否请问一下具体操作呢？是需要用到 连接设置-开始前脚本 或是 启动设置-附加命令 吗？
> 还是说你们使用的模拟器能够将“启动模拟器，然后启动方舟”这一操作打包为一个exe程序？

 你在模拟器里把应用添加到桌面快捷方式，然后在地址里填这个快捷方式就可以了。

**Comment by ABA2396** [comment]
不同模拟器的启动包的方式不一样，如果你知道附加命令的话，填进去也是可以的。

**Comment by NickerGrylls** [comment]
> 你在模拟器里把应用添加到桌面快捷方式，然后在地址里填这个快捷方式就可以了。

感谢，我个人的这个问题算是得到了解决
但我仍然坚持我的建议，理由有下：

1. 我使用的雷电模拟器官方是不提供这一方式的，必须自己折腾一下
2. 我刚刚试用了mumu12模拟器，实验证明安装方舟后需手动手动创建快捷方式（这设计本身挺合理）。或许方舟mumu专版会提供？但我不想再试了
3. MAA启动设置中的提示字为“模拟器路径”，所以即便是对于市面上提供这一方式的模拟器，我相信大部分人也会选择模拟器本身的exe
4. 私以为该调整对其他用户并没有显著坏处：
对于启动速度每次都足够快的用户而言，这一调整只是改变了最大容忍时长，对他们毫无影响
对于和之前的我一样会遇到这一状况的用户而言，这显然是一种优化

此外，基于上面的分析，我建议优化启动设置中的提示文字 或/且 引导用户创建并在MAA中选择方舟的快捷方式

**Comment by ABA2396** [comment]
这个等待时间是会跑满的，不是最大等待时间。其实那个附加命令才是用来打开方舟的，只不过是使用快捷方式比较方便，这个文档里应该有提过

**Comment by zzyyyl** [comment]
> 这个等待时间是会跑满的，不是最大等待时间。其实那个附加命令才是用来打开方舟的，只不过是使用快捷方式比较方便，这个文档里应该有提过

我记得之前有说识别 适龄提示 作为判断正在加载的依据（
现在 Startup 失败是在没有标志的界面停留太久导致的

**Comment by ABA2396** [comment]
> > 这个等待时间是会跑满的，不是最大等待时间。其实那个附加命令才是用来打开方舟的，只不过是使用快捷方式比较方便，这个文档里应该有提过
> 
> 我记得之前有说识别 适龄提示 作为判断正在加载的依据（ 现在 Startup 失败是在没有标志的界面停留太久导致的

现在更新下载支持了吗

**Comment by zzyyyl** [comment]
> 现在更新下载支持了吗

没有吧：）
