### ISSUE TITLE
干员组成员可自动编队但在战斗中无下干员

### ISSUE THREAD

**Issue by snowly233** [MaaAssistantArknights/MaaAssistantArknights#6858]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如干员组速狙包括能天使3和空弦3，后编队空弦3出现没有放下干员的情况，但脚本仍继续运行，初步判断为maa识别到空弦，但空弦的头像位置是错误的
（这是情况1，但debug里面没有记录）

干员组先锋编队推王2和风笛2，maa并没有放出风笛而是卡住整个脚本停止不动（这是情况2）

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12859671/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12859673/asst.log)

**Comment by snowly233** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75160294/32147e08-7b11-4bac-94bb-e6510e1c570f)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12859742/asst.log)
这是情况1的log和截图

**Comment by zzyyyl** [comment]
检查 cache/avatars 相关干员
