### ISSUE TITLE
3.9雷电连接不上

### ISSUE THREAD

**Issue by linbin9** [MaaAssistantArknights/MaaAssistantArknights#686]
雷电模拟器3.9版本后按照教程设置连接不上，下回3.3.2连接正常
3.3.2正常连接log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8815367/asst.log)
3.9.2异常连接log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8815371/asst.log)

**Comment by MistEO** [comment]
把连接地址改成 `127.0.0.1:5555` 试试

**Comment by jizix** [comment]
我也有这种情况,,更新好后第一次没事之后,按照教程在127.0.0.1:5555   ,   emulator-5554切换但连接不上模拟器,
就下回3.3.2用了

**Comment by jizix** [comment]
我2个号,用雷电切换到第二个模拟器的第二个号的时候,就连接不上,两个都连不上

**Comment by MistEO** [comment]
雷电的端口就是奇奇怪怪的，文档里已经写了这点，搞不定就建议换模拟器
