### ISSUE TITLE
系统识别MAA为“特洛伊木馬病毒”

### ISSUE THREAD

**Issue by FeliumMata** [MaaAssistantArknights/MaaAssistantArknights#6863]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题
然后解压缩后的档案也会没有MAA.exe

### 日志文件

没有

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125759352/8186a6aa-d7eb-4740-be8b-337cbf760b05)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125759352/fb069ee1-9063-46f9-91c8-66862e1e43e3)

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125759352/c9f4e89b-3c75-420c-8e06-f09dd0403180)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125759352/20a45e98-9e3d-40dd-8041-8201cb260c2b)

**Comment by FeliumMata** [comment]
注：4.24.0之前的版本没有此问题

**Comment by HoshinoAyako** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662
