### ISSUE TITLE
MAA使用卡顿，水月肉鸽无反应

### ISSUE THREAD

**Issue by SIN-36** [MaaAssistantArknights/MaaAssistantArknights#6866]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开MAA基建换班和做每日任务时发现动作卡顿，每一个事件间有1-2分钟的卡顿（eg:打开每日任务页面之后，要卡顿1-2分钟才会点击“全部领取”按钮，然后再卡顿1-2分钟后才退出），尝试minitouch和MAAtouch均有该问题，我的电脑上该问题大约从月初的4.24.0的某个内测版本开始，现在重装模拟器及MAA均未解决。
今天打水月肉鸽初始选人正常，进入关卡后完全无反应，查看asst.log发现MAA一直在重复这一段代码，似乎在识别某区域
代码如下：
[2023-10-11 13:43:25.812][TRC][Px1330][Tx8b0] asst::WordOcr [{ z: [ 0, 0, 630, 104 ], score: 0.465470 }] by OCR Rec , cost 11 ms
[2023-10-11 13:43:25.812][TRC][Px1330][Tx8b0] Proced [{ z: [ 248, 433, 630, 104 ], score: 0.465470 }]
[2023-10-11 13:43:34.927][INF][Px1330][Tx8b0] Call ` C:\Program Files\BlueStacks_nxt\HD-Adb.exe -s 127.0.0.1:5108 exec-out screencap -p ` ret 0 , cost 9114 ms , stdout size: 2574061 , socket size: 0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12865471/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12865475/gui.log)

### 截图

![屏幕截图 2023-10-11 134144](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62893249/46501836-57ab-4276-b5ae-ba0e25b1d3f6)
![屏幕截图 2023-10-11 134219](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62893249/dc9bec5b-7798-4660-b233-d803e7ba7308)

### 还有别的吗？

使用MAA正式版4.25.0
Bluestacks国际版N64版本5.13.200.1028
模拟器分辨率1920*1080
系统Win11家庭中文版21H2
CPU:AMD5800HS

**Comment by ABA2396** [comment]
这截一次图都要9秒）要不试试重装下模拟器

**Comment by SIN-36** [comment]
重新装过两次了，要换个模拟器吗

**Comment by ABA2396** [comment]
试试看吧，正常这个截图耗时应该得在 300ms 以内

**Comment by SIN-36** [comment]
OK

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/5889e2e3-9229-4458-a71f-5e11088c8435)
不对啊，蓝叠为啥用不了 nc 转发
cc @MistEO

**Comment by Constrat** [comment]
Similar:
- #3854
- #5184
- #5426
- #6064

**Comment by MistEO** [comment]
> ![image](https://user-images.githubusercontent.com/99072975/274162528-5889e2e3-9229-4458-a71f-5e11088c8435.png) 不对啊，蓝叠为啥用不了 nc 转发 cc @MistEO

蓝叠 HyperV 一直都用不了 nc

**Comment by Constrat** [comment]
nc also doesn't work for Pie64 versions

**Comment by SIN-36** [comment]
该问题似乎在关闭了Hyper-V和Windows Defender的内核隔离后得到解决，持续观察中。
可能是某些代码触发了Windows Defender的内核隔离？
Microsoft支持中与内核隔离有关的描述：
https://support.microsoft.com/zh-cn/windows/%E6%A0%B8%E5%BF%83%E9%9A%94%E7%A6%BB-e30ed737-17d8-42f3-a2a9-87521df09b78

**Comment by datpo-channel** [comment]
> 该问题似乎在关闭了Hyper-V和Windows Defender的内核隔离后得到解决，持续观察中。 可能是某些代码触发了Windows Defender的内核隔离？ Microsoft支持中与内核隔离有关的描述： https://support.microsoft.com/zh-cn/windows/%E6%A0%B8%E5%BF%83%E9%9A%94%E7%A6%BB-e30ed737-17d8-42f3-a2a9-87521df09b78

我认为是内核隔离的问题，在昨天我打开内核隔离后就出现MAA操作卡顿和模拟器运行掉帧的情况了，今日关闭后已经解决
