### ISSUE TITLE
模拟器分辨率和maa所需分辨率相同却提示模拟器分辨率不支持

### ISSUE THREAD

**Issue by V587plus** [MaaAssistantArknights/MaaAssistantArknights#6869]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

mumu模拟器使用分辨率为1280:720（DPI 240）；启动maa后执行Link Start开关，显示“模拟器分辨率不支持，请设置为720p或更高，且为16:9比例”；此后分别尝试1600:900和1920:1080分辨率、重启计算机和模拟器、检查连接配置、执行开始前脚本调整模拟器分辨率等方法依旧无法解决。

### 日志文件

[{61b8396a-2ba2-49ce-96ae-703b27e428d6}.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12866858/61b8396a-2ba2-49ce-96ae-703b27e428d6.zip)

### 截图

![屏幕截图 2023-10-11 162723](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147595848/166d0a1e-d966-4580-a784-f02d22dfd273)
![屏幕截图 2023-10-11 162746](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147595848/ace272ae-48a3-4f88-9f54-3a6881c8b696)

### 还有别的吗？

基础信息
UUID :  b1f27c9b-0b46-4d50-8385-a5971a9c671d
模拟器版本 :  3.5.21.2169
模拟器磁盘（可用/总）空间 :  90.9GB/125GB

运行环境
VT :  开启
Hyper-V :  关闭
网络环境检测 :  正常
以管理员运行方式 :  否
DirectX 11是否安装 :  是
防火墙 :  开启（建议关闭）

模拟器设置
Root :  开启
显卡渲染模式 :  Vulkan 模式（独家）
性能设置 :  6核/6GB
手机型号 :  vivo IQOO 10 Pro
分辨率 :  1280 * 720
高帧率 :  开启

连接设备
音频输入 :  已连接
音频输出 :  已连接

其它信息
其它版本信息 :  vm: 120.1.33.002 hyperv: 6.3.15.0 renderer: 0.0.125.0
Vendor :  NetEase
OpenGL Renderer :  MuMu GL (Vulkan 1.3.236 NVIDIA GeForce RTX 3060 Laptop GPU 532.09 _SO)
OpenGL Version :  OpenGL ES 3.2
运行时间 :  0 : 37 : 27

**Comment by V587plus** [comment]
补充maa日志文件：
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12866973/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12866974/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12866975/gui.log)

**Comment by ABA2396** [comment]
把adb-lite关了试试，还有mumu的端口是不会变的，不用每次都检测连接
