### ISSUE TITLE
使用蓝叠模拟器，方舟卡死卡没后，无法手动停止活动

### ISSUE THREAD

**Issue by zht04** [MaaAssistantArknights/MaaAssistantArknights#6870]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用蓝叠模拟器，刷源石锭，勾选了“中止行为等待至当前战斗结束后”，然后模拟器方舟应用卡死，我想手动点击停止按钮，因为勾选了“中止行为等待至当前战斗结束后”，所以点了两次，第一次点完没问题，第二次点完就一直显示正在停止，停止按钮也是灰的。然后就一直卡在这个状态，必须重启maa。
我尝试手动复刻这个bug，想要在打关打一半手动关闭方舟或者回退到模拟器主页面，但这些操作后停止按钮就只需要点一次就可以停止了，所以不太能复刻这个bug。
![d4afc91f4761fb441264258f24973bb6](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/e1f2c8f6-2b94-4546-bbc3-41ec96b6b85f)

### 日志文件

10月11日16:02:04我手动点击停止，卡掉线时间大致是15:02：39开始战斗之后
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12866891/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12866895/gui.log)

### 截图

![d4afc91f4761fb441264258f24973bb6](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/a94a46af-1d5b-456d-9cef-768a218522c4)

**Comment by zzyyyl** [comment]
@status102 #6591
