### ISSUE TITLE
增加下一次打开maa后理智恢复情况

### ISSUE THREAD

**Issue by LspColor** [MaaAssistantArknights/MaaAssistantArknights#6873]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前的maa是完成任务后会显示理智在何时恢复完毕

### 有什么好的想法？

提议在完成任务后将本次理智回复完毕信息储存，并显示在下一次maa打开后的右侧日志中（或者弹窗显示）
这样可以不登录明日方舟得知理智情况且明白什么时候应该使用maa

**Comment by 2497162852** [comment]
灰常资瓷

**Comment by smellqony** [comment]
支持

**Comment by amber2022-sea** [comment]
⑧致辞
