### ISSUE TITLE
两个问题，一是界面主题如果选择非日间和夜间两种就无法识别，新出的银淞和迷城都无法识别。二是在自动换班时，带皮肤的Lancet-2会出现明明找到了选择了也会继续找几遍的问题

### ISSUE THREAD

**Issue by callmep** [MaaAssistantArknights/MaaAssistantArknights#6874]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

两个问题，
一是界面主题如果选择非日间和夜间两种就无法识别，新出的银淞和迷城都无法识别。
二是在自动换班时，带皮肤的Lancet-2会出现明明找到了选择了也会继续找几遍的问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12868267/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12868268/gui.log)

**Comment by zzyyyl** [comment]
首先两个完全不相关的问题建议提两个issue。

回答第一个问题：银淞可以识别，不行的话建议发日志，明确一下时间段；迷城已经适配，暂时没有发版

**Comment by Constrat** [comment]
Infrastrutture detection is not made with images, but with OCR.
