### ISSUE TITLE
萨米肉鸽刷水壶无法正确识别

### ISSUE THREAD

**Issue by Zhang-Jia-Qi** [MaaAssistantArknights/MaaAssistantArknights#6876]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在4.24.0和4.25.0均稳定触发，萨米肉鸽刷水壶即便有2希望或者水壶藏品也会选择放弃重开，无限循环。

### 日志文件

我看asst.log里写报错了，然后保存了截图，我就一块把截图也发上来了，比较典型的一次误判发生在19:39
[Uploading debug.zip…]()

### 还有别的吗？

win10，MUMU模拟器12

**Comment by Zhang-Jia-Qi** [comment]
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12869591/debug.zip)

**Comment by Zhang-Jia-Qi** [comment]
但是刷到奖励热水壶奖励或者2希望奖励了不应该停止等人来操作吗

**Comment by Zhang-Jia-Qi** [comment]
因为我记得之前有几个版本确实会停在水壶界面

**Comment by zzyyyl** [comment]
> 但是刷到奖励热水壶奖励或者2希望奖励了不应该停止等人来操作吗

是的，确实应该停在水壶界面（
你有没有点”凹精二“的选项？
