### ISSUE TITLE
通用模式链接模拟器失败`Uuid command failed to exec`

### ISSUE THREAD

**Issue by Zhongwb95** [MaaAssistantArknights/MaaAssistantArknights#688]
### 通用模式链接模拟器失败
- MAA版本: 3.9.2
- 模拟器: 逍遥模拟器
- 系统: win10
- 问题现象:
  - 使用通用模式链接模拟器，显示连接失败。 但是`adb devices` 由不存在变到存在  
   ![image](https://user-images.githubusercontent.com/42909153/171440467-e22e8c3b-966f-4d83-9d29-f25a81f683f5.png)
  - 如果连接配置使用其他模式(逍遥模拟器/其他)并且填上地址软件会闪退
- 日志文件
  - [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8815493/asst.log)
  - 日志提示 `Uuid command failed to exec`

**Comment by MistEO** [comment]
所以为什么不用逍遥模拟器的模式呢

**Comment by MistEO** [comment]
闪退那就看一下闪退的问题，来个日志

**Comment by Zhongwb95** [comment]
这个是 换蓝叠模拟器 使用自动战斗的闪退
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8829841/asst.log)

**Comment by MistEO** [comment]
和模拟器没有关系，这个是已知问题，计划 v3.9.3 版本修复。

在作业制作器里面随便添加个`战斗流程`就好了，现在版本`战斗流程`为空的时候就会闪退

**Comment by Zhongwb95** [comment]
大佬 端午安康 

换了电脑(估计是这台电脑的逍遥新一点,显示的7.1 64bit)用逍遥模拟器也可以连接了 

还有一个问题就是 开机时间长的情况下 链接所有模拟器都连不上  日志里显示 的是 5037端口响应超时 重启电脑 又可以了

**Comment by MistEO** [comment]
> 大佬 端午安康
> 
> 换了电脑(估计是这台电脑的逍遥新一点,显示的7.1 64bit)用逍遥模拟器也可以连接了
> 
> 还有一个问题就是 开机时间长的情况下 链接所有模拟器都连不上 日志里显示 的是 5037端口响应超时 重启电脑 又可以了

那是模拟器/adb 的问题，没啥好办法_(:з」∠)_
