### ISSUE TITLE
肉鸽烧水时自动关闭 “储备源石锭达到上限时停止”

### ISSUE THREAD

**Issue by dhujsi** [MaaAssistantArknights/MaaAssistantArknights#6887]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

商店999时，如图设置去烧开水会在投资后直接停止在商店界面，不继续烧开水。虽然说符合逻辑但是感觉算是个漏洞（
或许可以给烧开水进程一个防打断用的豁免
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63281018/955d4e79-3a33-4c14-b6bf-0fc225557890)
以下非bug
是否可以有烧开水的循环？现在商店攒满之后想打还要多走一遍烧开水。
如果烧开水进行循环去攒钱或者干脆在攒够某个数值的时候把攒钱循环换成烧开水感觉会更好些

### 日志文件

在10-12 16:15:15左右
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12879160/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12879163/gui.log)

**Comment by zzyyyl** [comment]
你关掉“储备源石锭达到上限后停止”不就好了（
既能投资也不会打断烧水

**Comment by Zhang-Jia-Qi** [comment]
好好好，我刚想反应这个

**Comment by zzyyyl** [comment]
你们的意思是，烧开水的时候自动关闭 “储备源石锭达到上限后停止” ？

**Comment by dhujsi** [comment]
是的，不过确实问题不大。
不知道为什么，我一直觉得开着这个“达到上限时停止”会导致达到上限时会卡在投资栏，所以一直没关。
妄想症了属于是（

**Comment by ABA2396** [comment]
> 是的，不过确实问题不大。 不知道为什么，我一直觉得开着这个“达到上限时停止”会导致达到上限时会卡在投资栏，所以一直没关。 妄想症了属于是（

开了是回到桌面，没开是继续打）

**Comment by SherkeyXD** [comment]
改个描述吧（？
