### ISSUE TITLE
部分模板图可能有误

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantArknights#6889]
### 说说你遇到的问题？

这张图应该只是图片大小上的问题

|name|official|global|
|---|---|---|
| `global/txwy/resource/template/Mizuki@Roguelike@Continue.png` | ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/template/Mizuki@Roguelike@Continue.png?raw=true) | ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/global/txwy/resource/template/Mizuki@Roguelike@Continue.png?raw=true) |

**Comment by Constrat** [comment]
@zzyyyl it's this one correct?
Ignore the non-16:9. I have the band
![Screenshot_20231012-115213_39a08d986496c6659356f005305ed773](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/bb27bbf3-a0f0-4fa8-a6f6-a47d25e5a06a)

**Comment by zzyyyl** [comment]
I think it is just too large (probably cropped from a 1920x1080 image). It should be the black one here: ![](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/global/YoStarEN/resource/template/PrtsErrorConfirm.png?raw=true)

**Comment by Constrat** [comment]
But it's different. This was one is not from Roguelike, but a failed autodeploy run

**Comment by zzyyyl** [comment]
This template is not from Roguelike, it's just from Fight. The two below are from Roguelike XD

**Comment by Constrat** [comment]
I'm stupid. I didn't notice xD they are basically identical and I read Roguelike@AbandonAction xD

**Comment by momomochi987** [comment]
> ### 说说你遇到的问题？
> 
> 
> 
> 这张图应该只是图片大小上的问题
> 
> 
> 
>

想說怎麼又開啟來了

哦原來是台服啊 (x


那除了這張還有其他要一起調整的嗎？

晚點有空一起用一用

感謝大佬幫忙整理
