### ISSUE TITLE
增加无人值守时间段

### ISSUE THREAD

**Issue by vincywindy** [MaaAssistantArknights/MaaAssistantArknights#6892]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我用公司的电脑挂MAA，有时候MAA莫名其妙自己退了，尤其节假日，搞的很尴尬，似乎是自动更新需要手动操作导致的，关掉自动下载安装依旧会退出，原因不明

### 有什么好的想法？

增加无人值守模式或者时间段，在这个时间段内，即便检测到更新也不会安装

### 其他内容

我有时候怀疑是MAA什么问题导致的闪退

**Comment by starrin** [comment]
我这里maa也偶尔会在即将启动自动执行任务时闪退，并且这个闪退不会留下任何日志，就突然程序就没了
所以我现在每天都要连上去看个一两眼

**Comment by ABA2396** [comment]
现在还有这个问题吗
