### ISSUE TITLE
maa在进行基建时，部分设施人员放置有问题

### ISSUE THREAD

**Issue by Ravenightwing** [MaaAssistantArknights/MaaAssistantArknights#6895]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在电脑关闭显示器，但是不睡眠的模式下执行maa定时启动。会发现贸易站没有被放上干员。目前遇到的大多数情况是在贸易站下，其他设施也会有这个问题。除了没摆上人的设施 宿舍人员摆放也有问题。其他设施正常。使用的是自己定义的配置。

### 日志文件

上一次问题出现是10.13 00:00开始执行的任务。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12887907/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12887908/gui.log)

### 截图

`debug`文件夹下没有相关图片。游戏截图
![Screenshot_20231013-074046](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73371424/49f6c735-26ab-4609-8f38-1c2045e2cd29)

### 还有别的吗？

雷电模拟器
操作系统: Windows 11
基建配置
[1697103225969194.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12887925/1697103225969194.json)

**Comment by goyewell** [comment]
我也出现了这个问题，只不过我卡在制造站的选人界面，出问题的时间是14：00，用的MUMU12模拟器

**Comment by Ravenightwing** [comment]
换成了蓝叠模拟器，问题仍然存在。

**Comment by ABA2396** [comment]
现在还有这个问题吗？

**Comment by Ravenightwing** [comment]
> 现在还有这个问题吗？

没有了

**Comment by Ravenightwing** [comment]
这个问题突然又出现了。尝试重装了maa，问题依然存在。这次出现在了贸易站和宿舍，已经勾选了不将已进驻人员放入宿舍，但训练室的艾丽妮被放进去了。
模拟器是 mumu （之前一段时间是好的）。

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14814153/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14814154/gui.log)

**Comment by Ravenightwing** [comment]
这个问题突然又出现了。尝试重装了maa，问题依然存在。这次出现在了贸易站和宿舍，已经勾选了不将已进驻人员放入宿舍，但训练室的艾丽妮被放进去了。
模拟器是 mumu （之前一段时间是好的）。

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14814153/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14814154/gui.log)
