### ISSUE TITLE
[Enhancement]肉鸽的更多设置参数

### ISSUE THREAD

**Issue by lhhxxxxx** [MaaAssistantArknights/MaaAssistantArknights#690]
![3db4a4a2eb4fb655.jpg](https://user-images.githubusercontent.com/91231470/171453809-b996dfc6-1243-461c-b3e6-29f3da569a65.jpg)
也许可以和肉鸽作业json绑定之类的（）

**Comment by MistEO** [comment]
现在压根就不识别藏品的，是闭眼瞎买（

**Comment by et2012** [comment]
既然提到了，说一下我的想法（我提的我写.jpg）：

### 肉鸽招募：
- roguelike_recruit.json （或建一个新的 json）改为只定义干员信息：职业、名字、星级、所需希望等
- 新增一个可以根据分队变化的、跨职业的干员优先级列表
  - 例如：近锋队：棘刺 > xxx > 水陈 > 蜜莓 > ...
  - 兰登队：空弦 > 陨星 > 菲亚梅塔 > ...
- (optional) 为每个职业定义干员数量下限和上限，达到上限时优先招募其他职业的干员
  - 例如已经有5个近卫了，就别再招近卫了，招点高台吧
- 上述优先级会影响商店购买和战斗掉落招募券的选择

### 肉鸽战斗：
- 格子重用：检测所有格子是否有部署的干员可能有点难。那么这样是否可行：
干员部署（选择朝向）时记录所处的格子，再次部署时，说明TA撤退了，置空上次部署的格子。
- 可用格子数 < 可部署干员数时的判断。例如鲍勃那一关只有3个高台位。
- 每种编队的战斗风格应该是不一样的，也应该定义一个干员放置优先级
  - 例如：近锋棘刺队我希望第一个下棘刺，令重辅队我希望第一个放令，然后放龙
- (optional) 每张图可能会有一些专属职业/干员的最佳部署位
  - 例如：放棘刺能打2~3路，就别下个重装占坑了

**Comment by lhhxxxxx** [comment]
> 既然提到了，说一下我的想法（我提的我写.jpg）：
> 
> ### 肉鸽招募：
> - 现在的问题：默认先判断职业、再判断干员，会出现：明明我现在更需要先锋/医疗，但一直招近卫
> - roguelike_recruit.json （或建一个新的 json）改为只定义干员信息：职业、名字、星级、所需希望等
> - 新增一个可以根据分队变化的、跨职业的干员优先级列表
>   - 例如：近锋队：棘刺 > xxx > 水陈 > 蜜莓 > ...
>   - 兰登队：空弦 > 陨星 > 菲亚梅塔 > ...
> - (optional) 为每个职业定义干员数量下限和上限，达到上限时优先招募其他职业的干员
>   - 例如已经有5个近卫了，就别再招近卫了，招点高台吧
> - 上述优先级会影响商店购买和战斗掉落招募券的选择
> - 商店支持购买招募券（用于补充干员或晋升）
> 
> ### 肉鸽战斗：
> - 格子重用：检测所有格子是否有部署的干员可能有点难。那么这样是否可行：
> 干员部署（选择朝向）时记录所处的格子，再次部署时，说明TA撤退了，置空上次部署的格子。
> - 可用格子数 < 可部署干员数时的判断。例如鲍勃那一关只有3个高台位。
> - 每种编队的战斗风格应该是不一样的，也应该定义一个干员放置优先级
>   - 例如：近锋棘刺队我希望第一个下棘刺，令重辅队我希望第一个放令，然后放龙
> - (optional) 每张图可能会有一些专属职业/干员的最佳部署位
>   - 例如：放棘刺能打2~3路，就别下个重装占坑了
> 
> ### 肉鸽藏品：
> - 还没想好，可能类似招募券，也做一个优先级列表
> 
> ### 不期而遇：
> - 支持预期结局，遇到相关节点时自动选择
> - 骰子进不进、故事听不听、鸭爵、仙人跳等打不打，都支持设置
> - 要不要卖血换希望 、花源石锭买希望/招募券/藏品等
> 

也可以做成权重系统，比如一开始近卫500权重，医疗400权重，狙击300权重，近卫招一个减100权重，医疗招一个减400权重类似这样，每次选权重最高的，也可以按星级分配权重

**Comment by lhhxxxxx** [comment]
藏品优先级可以参考商店购买的逻辑，目前问题是状态机太简单了，只有一个攻速藏品阻断后续购买（而且在非商店场合获得攻速藏品不会阻断）

我的想法是加一个vector实时维护当前拥有的藏品，这样也方便实现刷指定藏品的功能

**Comment by et2012** [comment]
喜讯，打通覆水难收了。棘刺 蜜梅 yyds

![Screenshot_2022 08 11_22 12 40 787](https://user-images.githubusercontent.com/1037590/184154806-5e5f7612-7888-4521-bf2a-40edd372252a.png)

**Comment by lhhxxxxx** [comment]
水月肉鸽出来前先摸了（）

傀影肉鸽凌晨随手开了一把，把藏品图鉴全点亮了（）
