### ISSUE TITLE
遇到日服水月肉鸽的某些不期而遇会上下横跳

### ISSUE THREAD

**Issue by Azumagata** [MaaAssistantArknights/MaaAssistantArknights#6905]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

日服水月肉鸽的某些不期而遇，如果有两个选项的话，Maa会点一下上面，点一下下面，如此重复

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12891386/debug.zip)

### 截图

![305c6f70cb4f5b301477c0a28fc5ec2c](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71043421/b05db541-fb5a-406f-9f0b-db9b555c82b4)
![51ad5849b28e214369804779e5d41907](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71043421/e9d06db0-9702-432c-bc8d-1d1d22f68eb2)

**Comment by Manicsteiner** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6742 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5862 问题一直存在
我也不明白为什么了，都是“识别Mizuki@Roguelike@StageEncounterLeaveConfirm.png时，OCR得分仅为0.75左右”，我改这个之前也是，但我改成自己的截图后就能0.98，别人还是有这个问题。只能复读老方案了。

请根据外服适配教程，自行根据截图获取roi，图片替换至 \resource\global\YoStarJP\resource\template\Mizuki@Roguelike@StageEncounterOptionUnknown.png ，roi数据替换至 \resource\global\YoStarJP\resource\task.json 的 "Mizuki@Roguelike@StageEncounterLeaveConfirm" 节点。
或者，如果您在4.20.x版本及以前正常，请删除 \resource\global\YoStarJP\resource\task.json 的 "Mizuki@Roguelike@StageEncounterLeaveConfirm" 节点，并用旧版本中的 \resource\global\YoStarJP\resource\template\Mizuki@Roguelike@StageEncounterOptionUnknown.png 替换掉新版本的。

**Comment by zzyyyl** [comment]
能否上传一下你们 0.98 的截图参考参考（

**Comment by zzyyyl** [comment]
@MistEO 有没有可能把这玩意改成 OCR？

**Comment by zzyyyl** [comment]
刚才修的是不期而遇节点名称的识别，可以避免 OptionUnknown，不过没有解决上面提到的 LeaveConfirm 的**图像匹配**得分过低的问题

**Comment by Manicsteiner** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/5749 上次修改图像匹配还是我干的
刚开了一把肉鸽，ocr得分能到0.93，要求应该是默认的0.9以上
[2023-10-14 21:24:05.372][INF][Px1324][Tx3460] asst::TemplResource::get_templ lazy load Mizuki@Roguelike@StageEncounterLeaveConfirm.png
[2023-10-14 21:24:05.386][TRC][Px1324][Tx3460] match_templ | Mizuki@Roguelike@StageEncounterLeaveConfirm.png score: 0.930199 rect: [ 1113, 406, 167, 58 ] roi: [ 1063, 0, 217, 700 ]
