### ISSUE TITLE
萨米肉鸽有时会出现卡在开始探索的初始招募的情况

### ISSUE THREAD

**Issue by 1193946** [MaaAssistantArknights/MaaAssistantArknights#6907]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

连续两天在萨米肉鸽遇到，会卡在初始的招募界面，并且没有报错，也没有继续进行下一步，如截图所示。截图时间为16:50左右，而在13:11就已经卡住了。我给电脑设置了不会自动进入睡眠状态，仅关闭屏幕，所以应该不会是这类的原因。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12892555/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12892599/asst.zip)

### 截图

![V_8)E_`5(Q K5N 1}H%X6RS](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147597879/002a94c0-4ac0-4a92-9be6-eba7c36a96d9)

### 还有别的吗？

模拟器为mumu12，win10系统，maa版本为4.25.0

**Comment by 1193946** [comment]
刚刚查看了asst文件，我理解是从13:11到16：50之间maa一直在识别招募劵，不知道为什么卡了

**Comment by zzyyyl** [comment]
> 刚刚查看了asst文件，我理解是从13:11到16：50之间maa一直在识别招募劵，不知道为什么卡了

模拟器有没有卡？手动点能动吗

**Comment by 1193946** [comment]
> > 刚刚查看了asst文件，我理解是从13:11到16：50之间maa一直在识别招募劵，不知道为什么卡了
> 
> 模拟器有没有卡？手动点能动吗

印象中点了停止是有反应的，显示了已停止

**Comment by 1193946** [comment]
![)66E SLI9402M@6V6BOAH1K](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147597879/0131cd49-068e-429e-8b32-c86482e19737)
补充一张图，是11号的，也是一样的情况，时间是11:57到16:17左右
