### ISSUE TITLE
肉鸽在费用攒到30多之后仍然不放干员，存在漏怪现象，技能也会开晚

### ISSUE THREAD

**Issue by BlakeLee6** [MaaAssistantArknights/MaaAssistantArknights#6910]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我用的是稳定版，刷水月肉鸽，用海沫，但是开始让maa刷水月的时候，每次关卡攒费到三十几了，仍然不放干员，开局的几个怪已经到蓝门了，才下海沫，导致每次每关都得漏几个怪，感觉本来还能刷的更远的，但是就是在第三层左右没到boss关就over了，挺难受，希望能修复一下。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12894020/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12894021/gui.log)

### 截图

![0ad20a128e73391939ead9368e6be04](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/109645410/f1ad451b-8fa0-4c67-aef9-ec391033a8b0)
![e10efd344cee94ea1f30464d9d0dd4d](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/109645410/cbcb34ed-92f9-4082-b87c-23010672653b)
![fc5449b35abee38ad6b04e793dc316e](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/109645410/b4d655ef-e885-4c19-b567-890e40200c0b)

### 还有别的吗？

用的是MuMu模拟器12，操作系统是windows 11

**Comment by zzyyyl** [comment]
别用 adb 触控模式（

**Comment by zzyyyl** [comment]
fcbecb31028bc386722746dae8da658fdd5b526a 尝试修了一下，不过根本原因是你的模拟器截图有点慢（

**Comment by BlakeLee6** [comment]
那怎么解决这个？现在用的是minitouch，但还是会漏

**Comment by zzyyyl** [comment]
参考 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6866#issuecomment-1757782047 ？ 虽然你的情况好像没那边那么严重

**Comment by zzyyyl** [comment]
也可以等之后的内测版，上面说修了，但是还没发版

**Comment by BlakeLee6** [comment]
OKOK，谢谢
