### ISSUE TITLE
基建换班忽略艾丽妮

### ISSUE THREAD

**Issue by s-yh-china** [MaaAssistantArknights/MaaAssistantArknights#6912]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

maa当着我的面把艾丽妮换出去了，痛失8小时专精加速

### 有什么好的想法？

在基建换班时应该忽略艾丽妮

**Comment by s-yh-china** [comment]
> ![image](https://user-images.githubusercontent.com/99072975/274945456-582c7b7f-7884-450c-b715-5ebe1317a772.png) 这玩意是默认勾的吧

在勾选的情况下它依然换了出去 不知道发生了什么

**Comment by zzyyyl** [comment]
日志plz
