### ISSUE TITLE
mumu11   mumu12模拟器自动战斗13章问题

### ISSUE THREAD

**Issue by mtgaaae** [MaaAssistantArknights/MaaAssistantArknights#6913]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用maa 自动功能正常 自动战斗功能在使用攻略站内的13-2会出现 自动编队，调二倍速都可以进行，但是下干员的时候 屏幕虚空划过无法正常放置干员 
测试其他老作业 如7-8的作业 可以正常运行 
（已经测试4.5.0稳定版，4.5.1内测版）和对mumu11,12的排列组合

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12895722/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12895724/asst.log)

**Comment by HoshinoAyako** [comment]
试着删掉MAA\Cache文件夹，重新开始自动战斗是否还会复现

**Comment by mtgaaae** [comment]
> 试着删掉MAA\Cache文件夹，重新开始自动战斗是否还会复现

删除了cache的整个文件夹 依旧是自动战斗的第13章作业无法使用 老作业可以正常运行（其他功能继续正常）

**Comment by Constrat** [comment]
Implemented in e2ca6dbdf8e498c728c0e1b1b15bab5a817a50a4

**Comment by Constrat** [comment]
@ABA2396 I'm pushing a nightly for this
