### ISSUE TITLE
切换为第十三章奖励的新主题后无法识别

### ISSUE THREAD

**Issue by CBMisha** [MaaAssistantArknights/MaaAssistantArknights#6915]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

切换为第十三章奖励的新主界面主题后无法开始任务，切换回原始的日间主题后恢复正常

### 有什么好的想法？

希望添加对新主题的识别

**Comment by HoshinoAyako** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/alpha%2Fv4.25.1-alpha.1.d068.gf49c5e963
