### ISSUE TITLE
在理智恢复满时会推送信息

### ISSUE THREAD

**Issue by youlan2333** [MaaAssistantArknights/MaaAssistantArknights#6919]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在的推送功能非常棒，但是是被动推送，我想如果是主动推送呢？
我经常上线就是满理智状态，感觉有些理智都浪费了，如果给个提醒的话，会好很多。

### 有什么好的想法？

建议：maa在理智恢复满时会推送信息，这个理智余量可以手动设置也可以自动识别。

**Comment by ABA2396** [comment]
这个推送指的是 外部通知 还是windows弹个吐司通知

**Comment by youlan2333** [comment]
> 这个推送指的是 外部通知 还是windows弹个吐司通知

感觉都不错，我的意思是在软件内实时显示理智，并且可以在恢复满时推送通知
