### ISSUE TITLE
基建换班时无法自选基建计划

### ISSUE THREAD

**Issue by MUzyx** [MaaAssistantArknights/MaaAssistantArknights#6921]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建计划当我切换到我想要安排的那套排班后点击运行软件后，无法像以前那样可执行我主动选择的排班计划，而是会强制自动更换为基建配置表规定的对应时间的排班表，目前不知道这是bug还是新版本的规定，不过这确实有些影响到了我这种偶尔才上线收菜的咸鱼玩家......

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12903089/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12903090/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125632753/a940555e-e17f-4035-9bd4-d4cb9822e41b)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125632753/c8fba9ac-4394-45c5-85f1-dde987b364a6)

### 还有别的吗？

模拟器：雷电9.0.44
系统：WIN10专业版22H2
游戏版本：B服
基建排班配置编号：1697117485510109
MAA版本号：V4.25.1-alpha.1.d068.gf49c5e963

**Comment by Constrat** [comment]
When MAA is running you can't change any settings. It has always been like this.

**Comment by MUzyx** [comment]
> When MAA is running you can't change any settings. It has always been like this.

是在运行之前切换的配置，在前面的版本里可以在运行之前自行切换到基建配置排班表中的上午或者下午时间段的排班，然后以那个排班表来换人，现在只能是按照固定时间段的排班表来的

**Comment by Constrat** [comment]
I see what you mean, I've just checked and it's as described.

**Comment by MUzyx** [comment]
> I see what you mean, I've just checked and it's as described.

这是新版本的特性还是一个bug？因为之前版本可以自行决定要使用基建配置排班表中的上午或者下午时间段的排班这个功能，对于我这样偶尔起晚了导致没按照排班时间来的玩家类型来说还是挺方便的wwww

**Comment by Constrat** [comment]
> 这是新版本的特性还是一个bug？因为之前版本可以自行决定要使用基建配置排班表中的上午或者下午时间段的排班这个功能，对于我这样偶尔起晚了导致没按照排班时间来的玩家类型来说还是挺方便的wwww

It should not be a feature, I'm checking for changes

**Comment by Constrat** [comment]
cc @ABA2396

**Comment by ABA2396** [comment]
这个排班表是你自己做的吗？如果里面有时间字段的话是根据时间去看的。如果你要手动选择的话，就把那个时间段给删了。

**Comment by Constrat** [comment]
So it was a bug before? That you could start a plan with the wrong time because you overrode manually?

**Comment by ABA2396** [comment]
之前是在你点击开始的时候不会改变，但每分钟的定时还是会切这个选择，你要是一直看着它一分钟也会变回去，现在是在点开始按钮的时候会立刻切换一次。

**Comment by Constrat** [comment]
But with the older method if I wanted to I could start a different plan and iirc it wouldn't get overridden by the auto timer if I was already running task no?

**Comment by MUzyx** [comment]
> But with the older method if I wanted to I could start a different plan and iirc it wouldn't get overridden by the auto timer if I was already running task no?

之前的版本就是可以这样的，在运行之前选择自己想要运行的基建计划，可以不被自动计时器覆盖，这个功能说实话特别方便，我不明白为啥现在要改成这样....

**Comment by MUzyx** [comment]
> 之前是在你点击开始的时候不会改变，但每分钟的定时还是会切这个选择，你要是一直看着它一分钟也会变回去，现在是在点开始按钮的时候会立刻切换一次。

是这样的，之前可以在上午的时候手动更改成下午的排班表，然后点击开始，就会按照下午的排班表进行自动排班，现在则是不管怎么切，总会跳转到对应时间段的排班表去了，反而失去了这种选择权

**Comment by ABA2396** [comment]
那是因为你的任务列表里排班排在第一个，可能没跑到定时的时候就开始基建了，不过这个行为实在是太不明确了，因为你不知道这个定时器到底是什么时候运行的，很有可能就遇到了执行的和开始的不是一个任务。想想看有啥好办法

**Comment by ABA2396** [comment]
既然上线时间不确定，其实我是更推荐就不要用这个时间字段了。直去json里面把这个字段给删了就可以，只手动选，运行完了基建任务会自动切换下一个

**Comment by MUzyx** [comment]
> 那是因为你的任务列表里排班排在第一个，可能没跑到定时的时候就开始基建了，不过这个行为实在是太不明确了，因为你不知道这个定时器到底是什么时候运行的，很有可能就遇到了执行的和开始的不是一个任务。想想看有啥好办法

不不不，我的排班表是上午思维感知队、下午替班组，然后我在下午就算切换为上午的感知队，一按下运行按钮，就会立马切回时间顺序的下午的替班组了，这是现在版本MAA的运行情况；而在前面版本的MAA，我可以在下午的时候选择上午的感知队排班，然后运行，这样即便是下午也能按照我选择的上午的感知队的排班来更换基建人选

**Comment by ABA2396** [comment]
对，我的意思就是原来的版本你切换但不开始任务，过一分钟之后也是会变回去的，之前能运行的原因是在每分钟的切换前开始了基建任务，这个切换在开始了基建任务时就锁定了，运行但未到基建任务时仍然是会变的，而你是不会知道下次每分钟的定时是什么时候开始执行的

**Comment by MUzyx** [comment]
> 对，我的意思就是原来的版本你切换但不开始任务，过一分钟之后也是会变回去的，之前能运行的原因是在每分钟的切换前开始了基建任务，这个切换在开始了基建任务时就锁定了，运行但未到基建任务时仍然是会变的，而你是不会知道下次每分钟的定时是什么时候开始执行的

这个我知道，所以我说的是这个切换在开始了基建任务时就锁定时的功能很好用，不知道现在为什么要取消这个功能...如果能把这个功能实装就好了，这样严格按照排班表上号的玩家打开软件就能直接运行，而像我这种不是特别严格按照时间表来的，就可以自己手动改了后再运行了

**Comment by ABA2396** [comment]
不严格就不写时间啊，直接删了时间跑完自动切换下一班。内置的作业也都是没写时间的

**Comment by MUzyx** [comment]
> 不严格就不写时间啊，直接删了时间跑完自动切换下一班。内置的作业也都是没写时间的

可是在排班生成器那边不是必须自带时间的吗....
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125632753/6b9bd39c-2d5b-4c7c-946d-fa2b77652974)

**Comment by ABA2396** [comment]
把时间删了变成灰的字就行了，这个我和一图流那边提过了

**Comment by MUzyx** [comment]
> 把时间删了变成灰的字就行了，这个我和一图流那边提过了

哦哦哦哦哦，这样就能自己切换了吗？

**Comment by MChello1990** [comment]
同样的问题 之前能自己手动换的 换完之后立即执行就是更换的 现在无论怎么样都会强制使用第一个方案

**Comment by MChello1990** [comment]
更新最新测试版之后出现的

**Comment by MChello1990** [comment]
目前手动的话直接进json删除"period":[],中的字段就不会有时段影响了

**Comment by ABA2396** [comment]
8950d2ceaffb9934e77677ec4b64fd71fff1ff5f fixed
