### ISSUE TITLE
吃理智药功能与实际使用理智药数量不符

### ISSUE THREAD

**Issue by gClov** [MaaAssistantArknights/MaaAssistantArknights#6923]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用一次理智药不一定只消耗一个理智药

一个应急理智小样为10理智
一个30理智的关卡,自动补充的时候可能一次使用1个,2个或者3个理智药,但maa只算使用一个理智药
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115129135/677fe20c-7b0f-4bbd-9ee0-358d3ba8d98b)

选择
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115129135/dadfc17e-b695-4c08-a69e-f8ae01205e95)
可能使用了12个小理智药

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12903472/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12903473/asst.log)

**Comment by ABA2396** [comment]
@![Screenshot_2023-10-14-16-00-42-963_com.android.chrome.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/458ba5f9-d4e9-479a-97d6-59c899be5453)

这玩意儿做起来比较麻烦，所以现在这个是次数而不是个数
