### ISSUE TITLE
基建排班协议.md看不到了

### ISSUE THREAD

**Issue by KuiPer-LTW** [MaaAssistantArknights/MaaAssistantArknights#6925]
### 说说你遇到的问题？

我想自己在json上加上加工站的，想看看字段是什么，结果怎么没了，之前是有我还记得

**Comment by ABA2396** [comment]
![Screenshot_2023-10-14-18-15-48-727_com.android.chrome.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/e5385fe1-dde9-487d-924a-2d1ba5d21bd6)

**Comment by KuiPer-LTW** [comment]
> ![Screenshot_2023-10-14-18-15-48-727_com.android.chrome.jpg](https://user
![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/103661658/5394f7c8-7b00-454b-8d50-8d78b06a0527)
-images.githubusercontent.com/99072975/275192636-e5385fe1-dde9-487d-924a-2d1ba5d21bd6.jpg)

**Comment by KuiPer-LTW** [comment]
> ![Screenshot_2023-10-14-18-15-48-727_com.android.chrome.jpg](https://user-images.githubusercontent.com/99072975/275192636-e5385fe1-dde9-487d-924a-2d1ba5d21bd6.jpg)

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/103661658/5e10c907-c5f8-4ca0-b0b4-1753115b26aa)

**Comment by ABA2396** [comment]
在/docs里啊

**Comment by KuiPer-LTW** [comment]
> 在/docs里啊

找到了，我记起来了上次也是在那看的，所以为什么github这里不放上来呢

**Comment by ABA2396** [comment]
你这是哪里点进去的

**Comment by ABA2396** [comment]
![Screenshot_2023-10-14-18-39-20-819_com.android.chrome.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7c496b9a-3cf5-4427-b2f3-d4a3bc0cefa4)

**Comment by KuiPer-LTW** [comment]
> 你这是哪里点进去的

![QQ图片20231014184042](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/103661658/ac5b9116-7a03-451b-91ca-81790e4b70e8)

**Comment by ABA2396** [comment]
估计是链接写错了，等下看看

**Comment by KuiPer-LTW** [comment]
> 估计是链接写错了，等下看看

估计一直都是错的，反正我之前也是没看到过
