### ISSUE TITLE
无法自动连接蓝叠模拟器

### ISSUE THREAD

**Issue by HaneRo** [MaaAssistantArknights/MaaAssistantArknights#693]
![image](https://user-images.githubusercontent.com/26104114/171510634-b7fa024d-9670-4fa1-bd54-7d8a202e267c.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8819086/asst.log)

![image](https://user-images.githubusercontent.com/26104114/171510793-161f7ecb-859d-4819-96d7-1610bb17c15a.png)
![image](https://user-images.githubusercontent.com/26104114/171510802-87a6605b-5fa3-4713-98db-8cad4b704917.png)
连接地址无法自动更新（指定蓝叠配置文件的旧版本可以使用）

**Comment by MistEO** [comment]
请参考文档 模拟器支持情况.md~

**Comment by holzora** [comment]
> 请参考文档 模拟器支持.md~

按照说明gui.json文件添加字段和路径之后保存，之后重新打开maa程序再打开gui.json文件之前添加的字段被清除，而且我手动选择的adb路径点击连接模拟器后为什么又默认成“C:\\Program Files\\BlueStacks_nxt\\.\\HD-Adb.exe”？我adb文件并不在这里

**Comment by BombaxCeiba** [comment]
可能是你的gui.json格式错了，导致这个文件被重置了。

**Comment by holzora** [comment]
> 可能是你的gui.json格式错了，导致这个文件被重置了。

我找到原因了，因为旧版的gui文件连接蓝叠配置文件的字段是“Connect.BluestacksConfPath”，更新后没有默认清除这个字段，需要手动清除，更改工具是vscode，格式没有问题
