### ISSUE TITLE
美服肉鸽过一段时间就会卡在这个界面

### ISSUE THREAD

**Issue by xvzhenduo** [MaaAssistantArknights/MaaAssistantArknights#6931]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

美服每次挂肉鸽都会卡在这个界面
日志的时间在最后
![Screenshot_2023 10 15_07 32 32 637](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74353173/09f45d01-bb03-45ae-a0cc-de6e961247a4)
每次开局选干员有会卡住，然后重新进肉鸽
日志里面每次开始肉鸽的时候

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12908230/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12908231/gui.log)

### 还有别的吗？

BlueStack 5 android9 64位
触控方式minitouch

**Comment by zzyyyl** [comment]
RoguelikeBattleAbandonConfirm 有误，应该是图里的那张（"Retreat"）
