### ISSUE TITLE
已经勾选借助战打OF-1赚信用，没有执行

### ISSUE THREAD

**Issue by freelytomorrow9** [MaaAssistantArknights/MaaAssistantArknights#6932]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

获取信用及购物环节没有执行借助战打OF-1赚信用

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12908440/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12908441/asst.log)

**Comment by Manicsteiner** [comment]
> 访问好友后借助战打一把OF-1赚30信用。
> 一日只执行一次。
> 关卡选择为「当前/上次」时此功能无效。
> 别传「火蓝之心」关卡OF-1未解锁时请勿勾选。

请描述该功能要求的两个条件是否符合。

**Comment by zzyyyl** [comment]
- #6071 
- #6261
