### ISSUE TITLE
GUI界面鼠标划过的区域渲染错误

### ISSUE THREAD

**Issue by xmanthony** [MaaAssistantArknights/MaaAssistantArknights#6935]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA打开之后，只要鼠标划过的区域就大概会乱码或者选项消失不显示，但实际点击能生效

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12908576/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12908577/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147403590/66b618fb-91e2-442c-896e-c1476050da60)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147403590/d2d075f9-b752-4a38-8149-637f9295882e)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147403590/1b8631ad-d0dc-4c41-bc9a-529bc7c53242)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147403590/94885697-43cb-42a4-a777-2bf21f0b7ef3)

### 还有别的吗？

WIN11系统

**Comment by SherkeyXD** [comment]
这个问题经常发生吗

**Comment by xmanthony** [comment]
> 这个问题经常发生吗

基本必现，每次打开都能遇到。而且即使更新了版本依然会出现这个问题。

**Comment by SherkeyXD** [comment]
日志看不出什么问题 可能是你的显卡驱动问题？

**Comment by xmanthony** [comment]
> 日志看不出什么问题 可能是你的显卡驱动问题？

我晚上回去把MAA重装一次试下吧，驱动我也更新下试试

**Comment by SherkeyXD** [comment]
#8197 原因在这
