### ISSUE TITLE
提高对非16：9分辨率下WSA的支持性

### ISSUE THREAD

**Issue by HfSrJun** [MaaAssistantArknights/MaaAssistantArknights#6937]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

MAA要求游戏的分辨率至少为720p以上，且比例必须为16：9。
这导致在非16：9比例的屏幕上，WSA连接MAA使用时遇到麻烦。因为WSA并不能自定义分辨率，其分辨率为电脑屏幕的分辨率（即adb shell wm size的结果）。此“分辨率”实际上只是限定了WSA窗口的显示区域。

### 有什么好的想法？

我的临时解决方案为先利用adb修改分辨率，使其绕过MAA的检测。再编程修改明日方舟的窗口大小，因为实际分辨率大小是根据窗口而定的。
如果MAA能够添加特殊的“非16：9WSA模式”应该会方便许多。让MAA实现修改窗口大小的操作，然后在截取到的画面中把多余的黑色背景裁剪掉
感觉这个功能实现起来可能会有些困难

### 其他内容

![screen](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96952179/9b7f4be9-9554-49ee-ba82-9e5a9a5befea)
WSA截取到的画面大致如上图。
先将窗口大小改变为16：9，再整屏截图，最后将多余黑底裁剪掉应该就能得到16：9的游戏画面了

**Comment by Manicsteiner** [comment]
考虑过这个问题，感觉难点在于图片裁剪过程估计会很费时，而且效果可能也不好
找chatGPT写了段python代码
```
# 请为我写一段代码，使用Python3和PIL，实现以下图片处理功能的需求。
# 输入一张长宽比不定的PNG图片，底色必定为不透明的纯黑色，通常其中有一个16：9的矩形区域为彩色，需要将其裁切出来。
# 考虑到“彩色部分”也可能部分甚至全部为黑色，算法实现可以是“在图片中截取一个最大矩形，长宽比为16：9，包含所有非纯黑色像素，并使非纯黑色像素的图案尽量居中”，并且“在图片所有像素为黑色时，改为截取最大矩形，长宽比为16：9”。
from PIL import Image
import time, sys

def crop_image(image_path):
    # 读取图像
    image = Image.open(image_path)
    # 获取图像宽度和高度
    width, height = image.size
    # 将图像转为RGBA模式，方便操作透明通道
    image = image.convert('RGBA')
    # 遍历所有像素点，寻找非纯黑色像素点的最大矩形区域
    left, top, right, bottom = width, height, 0, 0
    for x in range(width):
        for y in range(height):
            # 获取像素点的RGBA值
            r, g, b, a = image.getpixel((x, y))
            # 如果不是纯黑色，更新最大矩形区域
            if r != 0 or g != 0 or b != 0:
                left = min(left, x)
                top = min(top, y)
                right = max(right, x)
                bottom = max(bottom, y)
    # 如果所有像素点都是纯黑色，直接截取最大矩形区域
    if left == width:
        left = (width - height*16//9) // 2
        right = left + height*16//9
        top = 0
        bottom = height
    # 否则根据最大矩形区域裁切图像
    else:
        # 计算最大矩形区域的宽度和高度
        rect_width = right - left + 1
        rect_height = bottom - top + 1
        # 如果最大矩形区域的长宽比不符合要求，调整左右边界位置
        if rect_width / rect_height != 16 / 9:
            target_width = rect_height * 16 // 9
            delta = (target_width - rect_width) // 2
            if left >= delta:
                left -= delta
            else:
                left = 0
            if right + delta < width:
                right += delta
            else:
                right = width - 1
    # 裁切图像并保存
    image = image.crop((left, top, right+1, bottom+1))
    image.save('output.png')

# 示例：裁切图片test.png
if __name__ =="__main__":
    time_start = time.time()
    if len(sys.argv) < 2 :
        crop_image('test.png')
    time_end = time.time()
    print("time cost (second) " + str(time_end - time_start))
```
CPU 12600k，从4k分辨率裁剪到大概720p，花了2.32秒。我觉得这个功能不太现实。

**Comment by Manicsteiner** [comment]
https://github.com/Manicsteiner/MaaAssistantArknights/tree/WSAcrop
OpenCV的处理效率比PIL高多了，只用大概0.3~0.5秒，图片裁剪（大概）解决了。
然后的问题是该怎么把点击范围从全屏幕缩小映射到窗口范围……

**Comment by HfSrJun** [comment]
> https://github.com/Manicsteiner/MaaAssistantArknights/tree/WSAcrop OpenCV的处理效率比PIL高多了，只用大概0.3~0.5秒，图片裁剪（大概）解决了。 然后的问题是该怎么把点击范围从全屏幕缩小映射到窗口范围……

能不能只“剪裁”一次，也就是保留窗口坐标，之后只需直接取对应坐标的图像而无需查找范围。

**Comment by Manicsteiner** [comment]
> > https://github.com/Manicsteiner/MaaAssistantArknights/tree/WSAcrop OpenCV的处理效率比PIL高多了，只用大概0.3~0.5秒，图片裁剪（大概）解决了。 然后的问题是该怎么把点击范围从全屏幕缩小映射到窗口范围……
> 
> 能不能只“剪裁”一次，也就是保留窗口坐标，之后只需直接取对应坐标的图像而无需查找范围。

饶了我这点入门级的c++水平吧……我没这水平
