### ISSUE TITLE
水月肉鸽中，进入收藏品界面后会反复点击一个收藏品无限循环导致卡死

### ISSUE THREAD

**Issue by 1193946** [MaaAssistantArknights/MaaAssistantArknights#6939]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

水月肉鸽中，进入收藏品界面后会反复点击一个收藏品无限循环导致卡死。
但是按说maa不会进入收藏品界面查看藏品，我想不通为什么一开始会误入藏品界面。
我在出门前设置好自动肉鸽然后就出门了，所以不存在误触的可能
时间如截图所示，应该是13：41战斗完成后就开始循环，直到15:10左右我回来手动退出藏品界面，才继续向下进行
建议：虽然maa自动肉鸽没有进入藏品界面的必要，但还是建议增加识别藏品界面的功能，避免因为误触或其他原因进入此界面后的无限循环导致卡顿

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12908943/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12908944/asst.zip)

### 截图

![QQ图片20231015155533](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147597879/883f8455-7756-49eb-b360-928f410d944d)
![Y1QVZ0703024XS$9S$OWRMJ](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147597879/f11f592e-220c-4637-a753-5ef586e12e75)

### 还有别的吗？

mumu12模拟器，win10系统

**Comment by shanbuzaigao** [comment]
蓝叠模拟器国际版遇到相似问题，到不是一开始就出现，而是突然出现之后下次继续出现，一般会在打完第一个boss之后出现此问题~
