### ISSUE TITLE
希望增加2项新功能

### ISSUE THREAD

**Issue by weedi0** [MaaAssistantArknights/MaaAssistantArknights#694]
既然定点自动执行功能上线了，希望增加错误信息推送到邮箱或者其他途径的功能，另外能否考虑在自动执行之前重启游戏进程以重置状态，碰到错误状态也可以同理操作。

**Comment by weedi0** [comment]
仔细想了下，其实核心是希望提升无人值守情况下自动任务完成率，大部分情况下错误且无法继续结束任务都是网络波动造成，maa会点完错误提示并停留在游戏开始界面结束任务，不过因为提供了4个定时选项，全部启用并缩小时间间隔来一定程度代替重启功能。

**Comment by ntgmc** [comment]
目前最新版本已经修复了绝大多数由于网络波动造成的卡顿，错误。
同时由于模拟器卡死导致运行错误的问题可以通过【设置-连接设置-adb重连失败时自动重启模拟器】解决
![image](https://user-images.githubusercontent.com/74061867/201553019-320de49b-dc7d-4812-8825-d21b94f55ecf.png)
