### ISSUE TITLE
maa无法识别迷城主界面主题

### ISSUE THREAD

**Issue by hcm426759** [MaaAssistantArknights/MaaAssistantArknights#6940]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

新的迷城主界面主题无法被正确识别，导致任何任务都无法正常进行，显示任务出错而提前结束

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12909116/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12909117/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90763790/dba366e5-66e2-4dbf-ba91-dc48dc422514)

**Comment by Constrat** [comment]
As of 4.25.0 the feature was not implemented. Update to a nightly.
