### ISSUE TITLE
maa未能正确识别红脸L2小车

### ISSUE THREAD

**Issue by cjyfs** [MaaAssistantArknights/MaaAssistantArknights#6942]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

情况简述：
up主公孙常乐的基建排班表中使用了红脸的L2小车，但maa未能正确识别红脸小车，而是选中了隔壁的干员。

### 日志文件

[asst-cut.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12909373/asst-cut.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12909269/gui.log)
问题出现在六点后

### 截图

![Image_1697365249686](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120154447/6f5f0116-a2c2-4cf6-801f-b007d58348ea)
这张图中本来肥鸭在L2的左边，而maa会选中肥鸭（手速不够快肥鸭被选中之后到前面去了）
![Image_1697365255332](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120154447/019ad2b0-5cf4-41b4-9d07-29eb40273cb0)
四次尝试之后maa会把错误的干员放入基建

### 还有别的吗？

模拟器：蓝叠5.13.0
操作系统：Win10 x64
maa:v4.25.0

**Comment by zzyyyl** [comment]
日志被刷掉了，发一下.bak

**Comment by cjyfs** [comment]
> 日志被刷掉了，发一下.bak

[gui.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12909303/gui.bak.log)

能加个qq吗，我不知道为什么没法把asst.bak发出去

**Comment by zzyyyl** [comment]
打个压缩包（？
或者发我邮箱 aysyxx53@hotmail.com

**Comment by cjyfs** [comment]
[Uploading asst.bak.log…]()


> 打个压缩包（？ 或者发我邮箱 [aysyxx53@hotmail.com](mailto:aysyxx53@hotmail.com)

发到邮箱里了，感谢帮忙

**Comment by cjyfs** [comment]
> 打个压缩包（？ 或者发我邮箱 [aysyxx53@hotmail.com](mailto:aysyxx53@hotmail.com)

发到邮箱里了，感谢帮忙

**Comment by zzyyyl** [comment]
[asst-cut.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12909373/asst-cut.log)

裁剪了一下有效信息，传上来先

看起来像是 maatouch 的 bug，可以先换 minitouch 试试

**Comment by cjyfs** [comment]
> 打个压缩包（？ 或者发我邮箱 [aysyxx53@hotmail.com](mailto:aysyxx53@hotmail.com)

发到邮箱里了，感谢帮忙

> [asst-cut.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12909373/asst-cut.log)
> 
> 裁剪了一下有效信息，传上来先
> 
> 看起来像是 maatouch 的 bug，可以先换 minitouch 试试

我现在用的就是默认的Minitouch

**Comment by zzyyyl** [comment]
日志里显示你当时用的是 maatouch

**Comment by cjyfs** [comment]
啊我刚刚换了配置，没想到连触控模式一起改了，我用minitouch再试试

**Comment by cjyfs** [comment]
minitouch模式下第一次选错了第二次选对了

**Comment by cjyfs** [comment]
刚刚被顶号了，又开一次能选到红脸L2了

**Comment by zzyyyl** [comment]
那先用着 minitouch 吧：）

**Comment by cjyfs** [comment]
> 那先用着 minitouch 吧：）

好的，谢谢

**Comment by cjyfs** [comment]
> 那先用着 minitouch 吧：）

![Image_1697537449634](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120154447/827df789-ef25-4019-a1d3-7c9e209421b2)
Minitouch也出现一样的问题了，要多次才能选到正确结果

**Comment by zzyyyl** [comment]
等 #6960 合了之后 maatouch 表现应该会比 minitouch 好：）

**Comment by cjyfs** [comment]
> 等 #6960 合了之后 maatouch 表现应该会比 minitouch 好：）

你们辛苦啦
