### ISSUE TITLE
博朗台使用理智药不超过体力上限时跳过等待步骤

### ISSUE THREAD

**Issue by runswell** [MaaAssistantArknights/MaaAssistantArknights#6943]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

刷理智的博朗台模式，现在会在任意使用理智药的场景到剩余回复理智时间5.55以上才会使用理智药。而实际上，当使用理智药且使用后不会超过体力上限时，并不需要做此判断，使用理智药不超过体力上限不会亏损剩余回复理智时间。

### 有什么好的想法？

优化博朗台模式，使得使用理智药不超过体力上限时跳过等待步骤，可有效加快刷理智效率，并且兼顾博朗台模式

**Comment by ABA2396** [comment]
现在还不知道吃的是啥药）

**Comment by status102** [comment]
Duplicate of #5578
