### ISSUE TITLE
希望用老版本的作业制作器的UI

### ISSUE THREAD

**Issue by HMZyueshen** [MaaAssistantArknights/MaaAssistantArknights#695]
新UI用起来不是很舒服

**Comment by Shawnsdaddy** [comment]
最快下个星期会上线抄作业服务器，会有网页版的UI，会从老UI移植

**Comment by Shawnsdaddy** [comment]
http://100.24.67.201/home
已经悄咪咪上线
[https://github.com/MaaAssistantArknights/MaaCopilotDesigner/tree/angular](url)
