### ISSUE TITLE
maa无法打开（无任何提示）

### ISSUE THREAD

**Issue by Sissi0907X** [MaaAssistantArknights/MaaAssistantArknights#6953]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

下载符合系统及位数的文件包后无法打开程序
系统是win10 64位
下载的文件包名称“MAA-v4.25.0-win-x64”
（无法提供截图因为什么东西都没显示）
用管理员身份运行试过了，重启也试过了
点击过以后打开任务管理器以后里面的进程是没有显示maa的
点击有加载的反应，鼠标会变成加载的样子1-2s然后就没其他反应了
没有开启任何防火防火墙程序
debug文件夹内没有名为asst.log的文件

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12913035/gui.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12913036/gui.log)

**Comment by Manicsteiner** [comment]
[可能性 2 : 运行库问题](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E5%8F%AF%E8%83%BD%E6%80%A7-2-%E8%BF%90%E8%A1%8C%E5%BA%93%E9%97%AE%E9%A2%98)
请安装 [Visual C++ Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe)、[.NET Framework 4.8](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-offline-installer) 并重新启动计算机后再次尝试运行本软件。

**Comment by ABA2396** [comment]
压缩包也发下看看

**Comment by Sissi0907X** [comment]
> [可能性 2 : 运行库问题](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E5%8F%AF%E8%83%BD%E6%80%A7-2-%E8%BF%90%E8%A1%8C%E5%BA%93%E9%97%AE%E9%A2%98) 请安装 [Visual C++ Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe)、[.NET Framework 4.8](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-offline-installer) 并重新启动计算机后再次尝试运行本软件。

用这个方法已解决问题
