### ISSUE TITLE
添加在肉鸽三层刷稀有boss的功能

### ISSUE THREAD

**Issue by lost-idea** [MaaAssistantArknights/MaaAssistantArknights#6954]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

希望添加刷肉鸽3层稀有boss的选项，只需要在进入第三层时候识别关底boss是不是稀有boss，如果是就弹窗提醒并且暂停脚本，不是就重开。

**Comment by Saratoga-Official** [comment]
duplicate of #2464
