### ISSUE TITLE
雷电模拟器连接后出现助手说分辨率太低无法代理的情况

### ISSUE THREAD

**Issue by Yuzy0612** [MaaAssistantArknights/MaaAssistantArknights#696]
！！！请尽可能详细的描述你遇到的问题，并附上助手软件目录下的 `asst.log` 日志文件！！！

！！！日志文件是可以直接拖拽进来的，没有日志文件的 bug 反馈我们会直接关掉！！！

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8819608/asst.log)

Thanks♪(･ω･)ﾉ
<img width="600" alt="2dddf4428067f6cc879a114d60eb5be" src="https://user-images.githubusercontent.com/95695364/171524270-147f8bfe-405e-452e-964d-a5e0657f54bc.png">

**Comment by Yuzy0612** [comment]
<img width="800" alt="ef5eac54c772bcc35bfa5fdec58304b" src="https://user-images.githubusercontent.com/95695364/171524584-f83431c8-cd21-47a6-bcfb-dbc3c1f5afd6.png">
我还是和往常一样打开模拟器和助手，但是链接错误了。我找到链接地址后，又说我分辨率太低了，我怎么调模拟器调游戏都不行，很奇怪

**Comment by MistEO** [comment]
重启试试，不行换模拟器。不建议用雷电，小问题很多
