### ISSUE TITLE
挂的时间太长导致内存永久爆炸

### ISSUE THREAD

**Issue by protossxs** [MaaAssistantArknights/MaaAssistantArknights#6961]
### 说说你遇到的问题？

联想y7000p内存16g笔记本开了将近12个小时maa与mumu刷肉鸽，回来的时候发现电脑死机，mumu黑屏，maa最小化打不开也无法右键关闭，重启后电脑变得很卡，蓝叠，mumu，雷电全部打不开，卸载重装也一样，最后发现内存占用永远爆满，不知道是不是挂的时间太长吧内存整坏了（不懂电脑），如果可以的话希望up能优化一下这个问题，或者把我当一个警告让别人用的时候注意点，多谢

**Comment by Constrat** [comment]
As @jyc001 said we need logs / screens / anything that can help.
Just reading the question doesn't do much, actually it makes me think that it's not MAA, but most likely the emulator, I'm not really sure.
Closing as incomplete until more debug info

**Comment by touchinglie** [comment]
很奇怪，我的天选4锐龙版也是，更新以前不会出现这种问题，任务管理器查看后发现16G内存占用99%，但MAA和MuMu模拟器内存占用加起来也才1.5G左右，我会尝试复现问题并截图与debug文件一同上传 @jyc001 请问我需要新开Issue还是在此补充？
<img width="616" alt="屏幕截图 2023-10-17 231914" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/101508197/8b31a166-b9b0-4291-9a26-559a0c1fe941">

**Comment by jyc001** [comment]
> 不仅仅是肉鸽，包括刷理智1-7也是，过一段时间会自动闪退无提示，模拟器也会报错（已尝试模拟器重装并未解决问题）

@touchinglie 要不新开一个issue？

**Comment by jyc001** [comment]
> > > 不仅仅是肉鸽，包括刷理智1-7也是，过一段时间会自动闪退无提示，模拟器也会报错（已尝试模拟器重装并未解决问题）
> > 
> > 
> > @touchinglie 要不新开一个issue？
> 
> 都可以谢谢，我现在在重下（不用之前旧版的热更新）尝试复现问题，要挂一会才会有报错所以可能明天早上整理出来，我尽可能排除其它干扰因素

let‘s follow @Constrat ’s. direction

**Comment by touchinglie** [comment]
> > > > 不仅仅是肉鸽，包括刷理智1-7也是，过一段时间会自动闪退无提示，模拟器也会报错（已尝试模拟器重装并未解决问题）
> > > 
> > > 
> > > @touchinglie 要不新开一个issue？
> > 
> > 
> > 都可以谢谢，我现在在重下（不用之前旧版的热更新）尝试复现问题，要挂一会才会有报错所以可能明天早上整理出来，我尽可能排除其它干扰因素
> 
> let‘s follow @Constrat ’s. direction

好的

**Comment by touchinglie** [comment]
> 你用的应该是mumu12模拟器吧，我也遇到很多次。开着maa挂机一两天，突然发现明日方舟就自动被关闭了，但模拟器还运行着。我个人认为这是模拟器的问题，无论切换哪种渲染模式或者加内存等等都解决不了。后来我换成了mumu6模拟器，重新安装了模拟器和明日方舟，maa稳定挂机一周至今没遇到任何问题。

可能是的，但是我还没试过

**Comment by touchinglie** [comment]
@jyc001 @Constrat 刚刚复现成功了，总时长应该有3小时左右，我用OBS窗口采集录制了最后一小时刷肉鸽的错误，刚好发生在我起床上厕所的时候：）不得不说很凑巧。OBS突然检测不到窗口，我重新打开时也发现整个进程像是直接被中断了；剪辑仅用于加速和压缩视频大小。

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/101508197/4d5b45d0-aebd-43a2-9f19-1ff4446ab2c7

**Comment by Constrat** [comment]
iirc something similar was happening a while back.
In Roguelike, when recruiting operators, MAA would stop working. I think this was already fixed. Try the latest 4.26.beta and (take your time) let me know if this still happens

**Comment by touchinglie** [comment]
但是这次因为是全新下载的MAA内存占用不高（尽管MAA还是闪退无提示），MAA总体积只有247MB，之前用了三星期后内存占用过多时MAA体积为800多MB，可能也有缓存或碎片文件过多的问题？还有就是上面另一位遇到同样问题的朋友说的使用低版本MuMu模拟器不会有问题，会不会是模拟器兼容适配的问题？

**Comment by touchinglie** [comment]
> iirc something similar was happening a while back. In Roguelike, when recruiting operators, MAA would stop working. I think this was already fixed. Try the latest 4.26.beta and (take your time) let me know if this still happens

好的我试试，谢谢！

**Comment by touchinglie** [comment]
不幸的是，MAA-v4.26.0-beta.1-win-x64只坚持了不到两分钟，它还是闪退了

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/101508197/372a5db0-cb53-4183-b37e-1a19bc019dff

**Comment by touchinglie** [comment]
@Lancarus 好的我上传了，先睡了，我熬了七小时了
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12955447/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12955459/gui.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12955462/asst.bak.log)

**Comment by HoshinoAyako** [comment]
mumu12在问题诊断有日志导出。
你可以把导出压缩包发一下

**Comment by Lancarus** [comment]
这块我搞不太懂..
I'm using lightning simulator with v25 beta，and haven't been like this yet

**Comment by touchinglie** [comment]
> mumu12在问题诊断有日志导出。 你可以把导出压缩包发一下

好的
[{baf8d4a0-2434-4ce2-9e7d-a6bba2286304}.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12981554/baf8d4a0-2434-4ce2-9e7d-a6bba2286304.zip)

**Comment by touchinglie** [comment]
> 这块我搞不太懂.. I'm using lightning simulator with v25 beta，and haven't been like this yet

一楼也试过用了闪电，也不能打开，我翻了debug，好像是模拟器着色器Texture2D的问题
Error: 0x00000505, in E:\build-nemu-full-vcpkg\vcpkg\buildtrees\renderer\src\edc3297fab-2fd5c20bbb.clean\mumu-angle\src\libANGLE\renderer\d3d\d3d11\ResourceManager11.cpp, rx::ResourceManager11::allocate:404. Internal D3D11 error: HRESULT: 0x8007000E: Error allocating Texture2D

**Comment by touchinglie** [comment]
> 这块我搞不太懂.. I'm using lightning simulator with v25 beta，and haven't been like this yet

一楼也试过用了闪电，也不能打开，我翻了debug，好像是模拟器着色器Texture2D的问题
Error: 0x00000505, in E:\build-nemu-full-vcpkg\vcpkg\buildtrees\renderer\src\edc3297fab-2fd5c20bbb.clean\mumu-angle\src\libANGLE\renderer\d3d\d3d11\ResourceManager11.cpp, rx::ResourceManager11::allocate:404. Internal D3D11 error: HRESULT: 0x8007000E: Error allocating Texture2D

**Comment by HoshinoAyako** [comment]
> > 这块我搞不太懂.. I'm using lightning simulator with v25 beta，and haven't been like this yet
> 
> 一楼也试过用了闪电，也不能打开，我翻了debug，好像是模拟器着色器Texture2D的问题 Error: 0x00000505, in E:\build-nemu-full-vcpkg\vcpkg\buildtrees\renderer\src\edc3297fab-2fd5c20bbb.clean\mumu-angle\src\libANGLE\renderer\d3d\d3d11\ResourceManager11.cpp, rx::ResourceManager11::allocate:404. Internal D3D11 error: HRESULT: 0x8007000E: Error allocating Texture2D

Failed to decompressed the texture using GPU...说明你系统内存吃满了。

**Comment by touchinglie** [comment]
> > > 这块我搞不太懂.. I'm using lightning simulator with v25 beta，and haven't been like this yet
> > 
> > 
> > 一楼也试过用了闪电，也不能打开，我翻了debug，好像是模拟器着色器Texture2D的问题 Error: 0x00000505, in E:\build-nemu-full-vcpkg\vcpkg\buildtrees\renderer\src\edc3297fab-2fd5c20bbb.clean\mumu-angle\src\libANGLE\renderer\d3d\d3d11\ResourceManager11.cpp, rx::ResourceManager11::allocate:404. Internal D3D11 error: HRESULT: 0x8007000E: Error allocating Texture2D
> 
> Failed to decompressed the texture using GPU...说明你系统内存吃满了。

但是很奇怪的是上面视频电脑内存都保持在60%，还是会闪退就很奇怪

**Comment by HoshinoAyako** [comment]
> > > > 这块我搞不太懂.. I'm using lightning simulator with v25 beta，and haven't been like this yet
> > > 
> > > 
> > > 一楼也试过用了闪电，也不能打开，我翻了debug，好像是模拟器着色器Texture2D的问题 Error: 0x00000505, in E:\build-nemu-full-vcpkg\vcpkg\buildtrees\renderer\src\edc3297fab-2fd5c20bbb.clean\mumu-angle\src\libANGLE\renderer\d3d\d3d11\ResourceManager11.cpp, rx::ResourceManager11::allocate:404. Internal D3D11 error: HRESULT: 0x8007000E: Error allocating Texture2D
> > 
> > 
> > Failed to decompressed the texture using GPU...说明你系统内存吃满了。
> 
> 但是很奇怪的是上面视频电脑内存都保持在60%，还是会闪退就很奇怪

不应该这样看。在Win+R输入perfmon，然后打开资源监视器。
分辨根据下面条件检查你内存与CPU的占用为多少。
不开启模拟器，MAA
开启模拟器，不开MAA
开启模拟器，开启MAA

**Comment by HoshinoAyako** [comment]
而且你视频里，模拟器占用内存都比正常占用高了

**Comment by touchinglie** [comment]
那我再试试（可能要点时间）

> 而且你视频里，模拟器占用内存都比正常占用高了

**Comment by MistEO** [comment]
@Lancarus 哪里crash了，可以给最近写的会在这两个界面进行识别/处理的代码，多加点 Log
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/63a5eeeb-24ff-4a80-95f5-61e0deee20e8)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/5155756c-1b09-4c4f-956b-2117de907d69)

**Comment by Lancarus** [comment]
没动过这里的代码啊

**Comment by MistEO** [comment]
> 没动过这里的代码啊

最近没改过招募相关的吗，这个应该是 MAA crash 了，不是他电脑的问题

**Comment by touchinglie** [comment]
按上面的复现后电脑发热严重，我先关机冷却上高数了

**Comment by touchinglie** [comment]
这次模拟器有报错
<img width="641" alt="屏幕截图 2023-10-18 203714" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/101508197/7882b99a-5471-45a0-b281-5d76365de303">
<img width="1280" alt="屏幕截图 2023-10-18 203509" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/101508197/7303593c-b2b8-4b10-a6cf-b53d49078eee">


https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/101508197/c44da538-878d-41df-b835-18d498f65906

**Comment by touchinglie** [comment]
#Issue6966同时在此前也遇到了这个Issue里反复点击单个藏品退出并再点击的问题，被个人退出藏品页面后重新选择关卡，应当是进入下一关时误点导致的

**Comment by Constrat** [comment]
Wait, if the crash happens because the computer overheates there's nothing we can really do. Emulation is resource heavy and MAA (Roguelike) is also heavy ok the CPU

**Comment by ABA2396** [comment]
这个电脑的性能不应该有问题的，感觉是别的问题

**Comment by touchinglie** [comment]
> Wait, if the crash happens because the computer overheates there's nothing we can really do. Emulation is resource heavy and MAA (Roguelike) is also heavy ok the CPU

这不应该，因为我所用的笔记本已经是游戏本里的顶配之一了，它的配置足够进行python人工智能深度学习。这是我现在的学习科目之一。

**Comment by touchinglie** [comment]
> Wait, if the crash happens because the computer overheates there's nothing we can really do. Emulation is resource heavy and MAA (Roguelike) is also heavy ok the CPU

所用的CPU是AMD的R9-7940H， CPU的资源占用在70%，是完全没有问题的，内存是16G

**Comment by touchinglie** [comment]
> > 按上面的复现后电脑发热严重，我先关机冷却上高数了
> 
> 方舟、模拟器全部设置30FPS行不行？这个应该纯粹就是电脑性能问题。模拟器本身就是极其占用资源的，就算是中端台式机都很紧张别说笔记本了

这不是纯粹的电脑性能问题，如果是性能问题应该开始就因内存紧张而崩溃，这是在长时间运行同一应用情况下，出现的内存不断过度占用。

**Comment by ABA2396** [comment]
按模拟器的提示更新过显卡驱动吗？感觉应该打包个日志给模拟器也送一份

**Comment by touchinglie** [comment]
> > > Wait, if the crash happens because the computer overheates there's nothing we can really do. Emulation is resource heavy and MAA (Roguelike) is also heavy ok the CPU
> > 
> > 所用的CPU是AMD的R9-7940H， CPU的资源占用在70%，是完全没有问题的，内存是16G
> 
> 笔记本长时间运转70%难道不会降频？笔记本散热设计就不是让你长时间拷机用的。深度学习吃显卡但是相对没这么吃CPU，而且还涉及到资源优化和调度问题。

不会降频，自定义锁频了

**Comment by touchinglie** [comment]
> 按模拟器的提示更新过显卡驱动吗？感觉应该打包个日志给模拟器也送一份

更新过，模拟器用的是N卡，驱动一直按最新更，但GPU占用不过30%

**Comment by touchinglie** [comment]
> > 按模拟器的提示更新过显卡驱动吗？感觉应该打包个日志给模拟器也送一份
> 
> 我觉得就是模拟器资源调度问题，特别是新版本内核的模拟器很容易资源爆炸、闪退

过会儿我看看怎么导出显卡的驱动日志，N卡的设置我不是很了解

**Comment by touchinglie** [comment]
散热是做好的，电脑有外挂散热风扇，电源适配器上有手机用的散热背夹，温度都不高

**Comment by Constrat** [comment]
Considering how hard to reproduce this is I feel like it's only a specific problem that doesn't depend on MA. There are too many variables at play that still haven't been removed.

**Comment by touchinglie** [comment]
> Considering how hard to reproduce this is I feel like it's only a specific problem that doesn't depend on MAA. There are too many variables at play that still haven't been removed.

That's truth at least now.

**Comment by LoveYourEnemy** [comment]
我也遇到同样的问题了。mumu模拟器12，方舟闪退，模拟器还在运行但是退到了主页。maa右侧状态也没有显示报错。但每次我发现方舟闪退时，maa右侧最后一条消息是进入关卡。

**Comment by jinghuashang** [comment]
我也一样，翻遍了全网，总结了下就是模拟器的问题，不够退回mumu6还没试过，但能肯定的是mumu12对方舟的优化有问题

**Comment by ouhongtao2024** [comment]
我遇到的问题是MAA在运行期间，主存逐渐上升，从一开始的400MB变成1.8GB，就很诡异，不知道是不是内存泄漏了。同时我观察到这个CPU占用非常高

<img width="1583" height="216" alt="Image" src="https://github.com/user-attachments/assets/09e10992-2721-481e-bfa5-26b94aff6947" />
