### ISSUE TITLE
自动战斗抄作业的时候，干员识别错误

### ISSUE THREAD

**Issue by tiyamikatto** [MaaAssistantArknights/MaaAssistantArknights#6964]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我使用了“maa://29102”的作业时，借用了好友的苇草。
作业进行时，本应下铃兰的步骤，会下纯艾。
脑测是因为借了助战导致的（）

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12919160/debug.zip)
时间点在2023.10.17 01:09 (JST)

### 截图

![QQ截图20231017010817](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104922165/b3174920-2156-417f-a38c-097586dc191a)

### 还有别的吗？

夜神模拟器7.0.5.0
版本号 v4.25.0

**Comment by tiyamikatto** [comment]
重新下载了一个v4.25.0客户端，并没有遇到相同问题...

**Comment by SherkeyXD** [comment]
尝试删除 cache/avatars 文件夹

**Comment by tiyamikatto** [comment]
> 尝试删除 cache/avatars 文件夹

感谢，问题已解决
