### ISSUE TITLE
增加一个MAA的使用统计信息

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#6968]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

more issue !

### 有什么好的想法？

增加一个本地保存的统计文件记录使用信息
比如：
1. MAA使用时长（单纯打开放着不算
    1. 总时长
    2. copilot时长
    3. 刷理智时长
    4. 肉鸽时长
2. 推关卡次数
3. 公招各类统计
    - 总次数
    - 5 6星次数
4. 使用信息
    - 经常使用的时间段
    - 截图延迟（分布情况

### 其他内容

- Skip labels

**Comment by Constrat** [comment]
Just imagine how much data has already been lost

**Comment by status102** [comment]
> Just imagine how much data has already been lost

既往不咎（

**Comment by status102** [comment]
目前除了截图延迟延迟，其余全都可以wpf做完

**Comment by SherkeyXD** [comment]
在每个任务开始和结束时记录时间戳，计算得出该任务所用时长（？

但是感觉得加个让用户同意的开关

**Comment by Constrat** [comment]
3. Already exists on Penguin logistics. They've added not quite a long ago the viewer of the recruitment dat

**Comment by martinwang2002** [comment]
请问统计这些数据的意义是什么？

**Comment by status102** [comment]
> 请问统计这些数据的意义是什么？

类似于Word中的字数统计

**Comment by Constrat** [comment]
👀

**Comment by status102** [comment]
> 👀

也许我们需要的是一个遥测
