### ISSUE TITLE
图片尺寸可能不合适

### ISSUE THREAD

**Issue by 100210110** [MaaAssistantArknights/MaaAssistantArknights#6969]
### 说说你遇到的问题？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104227884/0d7566cf-528f-4f9b-a574-a0f477ebeab9)
这个表情包太小了（

**Comment by Constrat** [comment]
https://github.com/MaaAssistantArknights/MaaRelease/blob/7948dd8d6bc49b650bf1fc9adc6965543a2852b1/MaaAssistantArknights/api/announcements/img/NoSkland.jpg
Size is correct,`C#` code maybe?
cc @MistEO

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6828 fixed
