### ISSUE TITLE
希望可以增加自由选择是否需要通知提示音

### ISSUE THREAD

**Issue by BlitheDou** [MaaAssistantArknights/MaaAssistantArknights#697]

**Comment by usaginya** [comment]
目前只有通知有提示音、如果不想通知时发出提示音、可以用下面的设置方法关闭声音

1. 系统声音图标上右键
2. 打开声音合成器
3. 到 maa 设置页面左边的通知显示设置、点一下 `测试通知` 按钮
4. 把声音合成器里出现的 maa 音量设成静音

这样就不会在通知的时候发出提示音了

**Comment by cglcv** [comment]
话说为什么不把maa的通知做成系统推送或者托盘呢……

**Comment by usaginya** [comment]
> 话说为什么不把maa的通知做成系统推送或者托盘呢……

从 win10 开始、原本的托盘提示被改为 toast 弹出通知、这个是微软默认改的、要恢复成 win10 以下那种托盘通知就必须对系统进行设置修改、所以只靠软件实现很难、顶多是加了个托盘图标而已（努力方向错了） 

还有没明白系统推送是指哪一种、如果使用 windows 提供的通知接口、默认会弹通知还有通知音、也要通过设置来屏蔽、是能把通知推送到通知中心和锁屏界面通知上、但这种方式对 win10 以下的系统有闪退的兼容问题（除非完全没有 win7 使用者了）虽然可能有某个现有的通知扩展可以做到兼容性、但 maa 界面以后就要换成 web 了、重做通知功能就有点小题大做了。。
