### ISSUE TITLE
[傀影肉鸽]战斗AI不会打悦耳杀机boss在上路的图

### ISSUE THREAD

**Issue by lirao** [MaaAssistantArknights/MaaAssistantArknights#6974]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

boss关悦耳杀机，有时候boss在上路，然后我看到maa把斑点和泡普卡凯尔希部署在了左路，即使左路空空荡荡。截图1之前斑点被部署到了左下角，然后被地图掉血死了。截图1里的M3还是漏了好几个小兵以后才放下去的。看我还是10费的夜刀就知道她在我停maa前没被动过

只在英文服见过这个情况，别的还没见过这个boss在上面的情况（不排除afk的时候遇到过）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12968317/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12968318/gui.log)
log tail

### 截图

![Screenshot_2023 10 17_15 44 54 664](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6883412/b5ead7cd-39df-4930-92e0-fa6cb12f1198)
![Screenshot_2023 10 17_15 45 21 231](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6883412/831ea623-0fe8-489c-9b63-f12f0244f26c)

debug/map 里截到了这张图
![悦耳杀机](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6883412/34090178-2ae8-4d38-a1ab-f2a69398e2bb)

### 还有别的吗？

bluestacks 5 1920x1080
MAA v4.25.0

**Comment by Lancarus** [comment]
Maa无法判断地图内的随机元素，只能写一个相对通用的策略
