### ISSUE TITLE
EN傀影不期而遇遇上鸭爵，会选择战斗可是不会进入战斗

### ISSUE THREAD

**Issue by lirao** [MaaAssistantArknights/MaaAssistantArknights#6975]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

英文服，傀影肉鸽
不期而遇遇上鸭爵，会选择战斗选项（第一个），可是进入不了战斗，就这样卡住了

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12972772/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12972775/asst.log)
17:21 遇到的不期而遇

刚看到17:12还有个关卡识别错误，可惜debug里没有这个的截图

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6883412/503f9561-cfe8-4a16-ab15-1aba4770d368)
模拟器自带截图：
![Screenshot_2023 10 17_17 35 22 700](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6883412/ed838364-e103-4463-a6a6-8d67763f9126)

### 还有别的吗？

1920x1080 bluestacks 5
4.25.0

**Comment by zzyyyl** [comment]
那个识别错的关卡是 “A Cold Separation”（寒渊惜别）， 3d6b4e1b97c869735769bea871b1cd9c09359974 修了

**Comment by lirao** [comment]
![Screenshot_2023 10 18_09 46 16 865](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6883412/1c60cf22-f320-4adf-9920-3888b3e42550)
这关卡也有同样问题

**Comment by lirao** [comment]
![Screenshot_2023 10 19_11 18 42 995](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6883412/e9979331-7a67-44e5-ad51-4b54bac91ec5)
应该是task.json什么的问题，可是那文件太长也不知道去哪找

**Comment by Constrat** [comment]
@zzyyyl I can't understand this.
The issues is not in the operation names, as hey are all correct AND they do not get recognized in this ^ screen but during the loading.

This is completely off-topic but we could use the same algorithm / idea for SSS stage detections (It would make EN adaptation 10× easier and without fails, as of now I have to compensate for names that have a \n in the display, which could fail at any moment)

**Comment by lirao** [comment]
Right, the logs show that the encounter names are OCRed correctly, is the task workflow config different in the EN tasks.json for this type of Encounter->Combat nodes? Don't know what this is called internally in-code, can't find it in the task.json file

These kinds of encounter doesn't get stuck on the TW server (which also needs different OCR) or rather, I never saw it getting stuck

**Comment by Constrat** [comment]
What happens:
Everything depends on the resource/tasks.json (zh_cn one)
If there's a duplicate task in the EN one OR there's a "different task in EN" it will follow that one.

For these operations, usually it's just a matter of OCR. The task is executed from CN Tasks.jjson but uses EN OCR parameters (same thing for JP, KR, tw)

**Comment by Constrat** [comment]
The problems are not the stage names (as I expected) but this:
`Phantom@Roguelike@StageCombatDpsEnter.png`
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/407cc6bb-8b2f-420c-9738-f18f4f623de4)
Somehow it's not getting detected correctly.
@Lancarus @zzyyyl

**Comment by THSLP13** [comment]
追加:美服在Bound by Self(不期而遇引发的作战关卡)时maa也会卡住，目测同样也是识别问题，我暂时还没有检查这一次的日志

**Comment by zzyyyl** [comment]
我推测这个问题是美服的 UnknownOption 导致的，之前已经在遇到UnknownOption 时增加截图，你可以看看 debug/roguelike

**Comment by Constrat** [comment]
@THSLP13 @lirao we need the screens from `debug/roguelike`.
The issue is not in detecting "Gun Salute" and / or "Demonic Cage", but in detecting the name of the encounter before (the blue node). When MAA does not understand the Encounter Stage name it will select a default option, in this case it will choose to fight, but we have no algorithm that allow this type of behaviour. So MAA will try to go to a new node but it can't because it's stuck in fight.

**Comment by THSLP13** [comment]
@Constrat OK,I will collect the shots when I'm idle then.

**Comment by THSLP13** [comment]
@Constrat 我发现有相当一部分不期而遇事件都像上图一样有个Join the fray,可能依据这一点添加对应事件
![2023-10-30_19-44-41-675_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62548119/72b4a717-534a-4a82-bb9d-0f973a8c3186)
![2023-10-30_19-44-51-231_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62548119/f7ea8ea1-3b7d-4747-9325-200e29e3e666)

**Comment by zzyyyl** [comment]
能否把 `debug/Roguelike` 文件夹打包上传（

**Comment by THSLP13** [comment]
At today,19:10:15.796 and 19:44:41.675
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13204952/asst.log)
Sorry for large file,but I'm using a remote console.
或许需要再过一会了，roguelike文件夹里面除了这些特挑的截图以外就没有其他有用的信息了
@zzyyyl @Constrat

**Comment by Constrat** [comment]
Ok I found one of them for now: `3Reprieve?` very ugly.
```js
[2023-10-30 19:17:08.171][TRC][Px3594][Tx2f3c] asst::WordOcr [{ 3Reprieve?: [ 78, 89, 126, 32 ], score: 0.913211 }, { You reach a hall with an oil painting in a most conspicuous location. The painting depicts t: [ 115, 126, 607, 19 ], score: 0.945911 }, { of a tragic story. At the end of the storv,the protagonist discovers that his entire life is a: [ 115, 149, 604, 14 ], score: 0.934943 }, { conspiracy.In his grief,he leaps off a tall tower as a last-ditch effort to break free of the: [ 113, 167, 610, 18 ], score: 0.949490 }] by OCR Pipeline , cost 1234 ms
[2023-10-30 19:17:08.173][TRC][Px3594][Tx2f3c] Proced [{ 解脱?: [ 78, 494, 126, 32 ], score: 0.913211 }]
[2023-10-30 19:17:08.173][INF][Px3594][Tx2f3c] Event: 解脱? choose option 2
```
