### ISSUE TITLE
基建换班功能无法选人入驻

### ISSUE THREAD

**Issue by Astrophel-Y** [MaaAssistantArknights/MaaAssistantArknights#6976]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建换班功能出现难以描述的bug，大致表现是无法根据排班表选定干员入驻，目前该功能完全无法正常使用。
该bug仅在更新至4.26.0-beta1后出现。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12972899/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12972906/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49133151/bb25f669-d3bb-4c01-a32c-79fcbd0aa365)
该图为换班后结果。

### 还有别的吗？

蓝叠国际版 5.13.0.1074 Hyper-V

**Comment by status102** [comment]
MiniTouch or MaaTouch or adbinput？

**Comment by HoshinoAyako** [comment]
这个问题很诡异，不知道是不是改了触控拉条的原因。
明显与4.25的拉条找干员有很大差别

**Comment by HoshinoAyako** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/1b75bff7-64a4-46d7-8454-c0f60b44f218

明显MAA找干员的时候，这种拉条很奇怪。

**Comment by HoshinoAyako** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12974591/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12974592/gui.log)

**Comment by GreatDianna** [comment]
自动战斗没法放人，看起来是也是这个问题

**Comment by Astrophel-Y** [comment]
> 操控是MiniTouch or MaaTouch or adbinput？

我用的是MaaTouch

**Comment by HoshinoAyako** [comment]
只要是拉条找干员，无论是自动编队还是在基建，都会错误识别选择错误的干员。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/e7234f87-666a-4ec1-86b0-042a34be3d46)


https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/f530848c-a31f-4b0d-a987-6cd44d153010

**Comment by HoshinoAyako** [comment]
我怀疑是task.json里头这个delay的问题。去掉这段delay就正常了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/5fa898d8-0ad2-4087-90a3-3fdaf6366397)

**Comment by zzyyyl** [comment]
`v4.26.0-beta.1.d005.ge30d872bb` fixed
