### ISSUE TITLE
一次性勾选多个作业文件导入战斗列表时出现错误和闪退

### ISSUE THREAD

**Issue by github123520** [MaaAssistantArknights/MaaAssistantArknights#6978]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

一次性多选择几个作业文件进行战斗列表任务时，会出现闪退/提示错误的行为，导致无法抄作业，只能一个个选择，请修复

### 日志文件

MAA 遇到了问题
未能找到路径“cache/copilot/MAACopilot_主线十三章 恶兆湍流 13-2（磨难） 萧然攻略.json”的一部分。
解决方案
出现未知错误
详细信息
System.IO.DirectoryNotFoundException: 未能找到路径“cache/copilot/MAACopilot_主线十三章 恶兆湍流 13-2（磨难） 萧然攻略.json”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   在 MaaWpfGui.ViewModels.UI.CopilotViewModel.<ImportFiles>d__33.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by HoshinoAyako** [comment]
更新4.26.0-beta1

**Comment by status102** [comment]
看看你战斗列表里面怎么设的，看上去文件名不对

**Comment by status102** [comment]
是批量添加作业是么
