### ISSUE TITLE
基建滑动选人十分卡顿

### ISSUE THREAD

**Issue by WSMTBG** [MaaAssistantArknights/MaaAssistantArknights#6979]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

找半天找不到人，就在后一页，但就是划不过去，好像就是4.26，之前没这个问题

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12976820/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12976837/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12976853/gui.log)

### 截图

![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/56a630c8-de8f-4ad6-ae6e-be51092eaf75)

### 还有别的吗？

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/234bc889-5b11-44bc-bd53-3ca3a6a68f3e

**Comment by HoshinoAyako** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6976

**Comment by WSMTBG** [comment]
视频好像没发成功

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/50ae7d2b-9878-402c-99f9-f47f2fb28885

**Comment by zzyyyl** [comment]
`v4.26.0-beta.1.d005.ge30d872bb` fixed
