### ISSUE TITLE
界面识别

### ISSUE THREAD

**Issue by Yuuki-ATRI** [MaaAssistantArknights/MaaAssistantArknights#6980]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

鹰角更新了主题界面，但是MAA不识别新的主题界面，会卡在主界面

### 有什么好的想法？

你懂得

### 其他内容

加油

**Comment by HoshinoAyako** [comment]
更新4.26.0-beta1

**Comment by Constrat** [comment]
Mist city theme has already been adapted. Before opening issues, check the latest version
