### ISSUE TITLE
水月肉鸽ISW-NO 好梦在何方 稳定漏怪12+

### ISSUE THREAD

**Issue by Yiserk** [MaaAssistantArknights/MaaAssistantArknights#6982]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

这一关不是两条路吗，上面有个钻头哥会钻一条路，但是maa只在下面守，上面完全不管，导致钻头哥钻通之后怪全从上面进蓝点了，基本上都是12+，太多次寄在这里了，满科技树挂了一整天n1一次都没过，后来是有次我手操过了这关打通海沫结局了。

### 有什么好的想法？

切一下？我也不太懂maa是什么操作逻辑，总之抓到异德也不会去切钻头哥。

### 其他内容

![AKIT~0%$I~YNF@MN%5)T4CE](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94718737/d9501f9c-8d0b-48f9-90e5-f35f28a16876)

**Comment by Constrat** [comment]
If you have copilot ideas... Feel free to post them
Creating scalable JSON fights Is not easy.
