### ISSUE TITLE
希望界面右侧log“已使用理智药x次”能与其他提示区分颜色

### ISSUE THREAD

**Issue by akiriroll** [MaaAssistantArknights/MaaAssistantArknights#6983]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在使用多理智药挂机时候，有需要翻看已使用理智药的情况，但因为“已使用理智药x次”与“已开始行动x次”和“理智：？？”颜色相同，翻看时很难区分。即使log显示时候“使用理智药”有与其他条目分时间分行，区分度还是太低。

### 有什么好的想法？

把“已使用理智药x次”从绿色改为其他颜色区分一下就可以了。

### 其他内容

![屏幕截图 2023-10-15 125419](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120661226/311ea75f-18a1-4f17-926d-e7db2530f78f)

**Comment by status102** [comment]
试试最新测试版
格式like:
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/22fb3dfe-457b-44af-8782-4d7aecef23f7)

直接不用滑上去找了（感觉设置太多颜色并没用从根本上解决问题，以后可能会变成眼花缭乱的一堆各种颜色

**Comment by akiriroll** [comment]
> 试试最新测试版 格式like: ![image](https://user-images.githubusercontent.com/102887808/276233520-22fb3dfe-457b-44af-8782-4d7aecef23f7.png)
> 
> 直接不用滑上去找了（感觉设置太多颜色并没用从根本上解决问题，以后可能会变成眼花缭乱的一堆各种颜色

好的我试试测试版，这个方案确实比再区分颜色好得多，可以说是解决问题了
