### ISSUE TITLE
开始唤醒任务加一个点击

### ISSUE THREAD

**Issue by zhangweijian97** [MaaAssistantArknights/MaaAssistantArknights#699]
信用商店如果卡在买东西结束之后黑黑的页面。下一次再执行任务链的时候，就只有到基建收菜的时候，才会因为未知原因解开，并继续运行，基建前面的任务都不能正常运行。

希望在开始唤醒任务加一个点击页面，来解开卡信用商店的情况。然后任务链就正常了

**Comment by MistEO** [comment]
如果只是因为信用商店卡住，那之前的版本已经修复了_(:з」∠)_
