### ISSUE TITLE
增加公招三星Tag时不使用加速券的选项

### ISSUE THREAD

**Issue by HoshinoAyako** [MaaAssistantArknights/MaaAssistantArknights#6996]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by HoshinoAyako** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/40bf64ab-3249-4665-b0e2-846781aa5e7f)
例如这样点满后，在勾选自动使用加急许可的情况下，按顺序点立即招募。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/6c0e5306-86b7-4d50-95dd-6d840a2891f0)
然后再全点聘用候选人，然后再全部招募

**Comment by HoshinoAyako** [comment]
而不是只在一个招募格内加速招募。。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/1dc8fb57-4db7-47b8-90f4-c4e12cd95dbe)

**Comment by Constrat** [comment]
What difference would it make? 
At the end of they day you will use the same amount of recruit permits and expedited plans.
(While complicating the algorithm)

**Comment by zzyyyl** [comment]
有什么意义吗，效率是一样的吧

**Comment by HoshinoAyako** [comment]
这只会在一个格子内识别并刷新词条，加速招募。后面剩下的三个格子同样刷新了词条，但是并没有得到识别招募与加速的机会，所有的加速都在一个格子内使用了。

**Comment by zzyyyl** [comment]
一次招募 = 一次刷新词条
刷新词条也没有浪费，招募次数也一样多，这不是完全一样吗（

**Comment by HoshinoAyako** [comment]
说到底还是加速券的使用都在一个格子了，只有用完了才会对其他格子进行招募。
如果给加速券添加一个设定，只有识别到TAG是4星以上才使用这样呢

**Comment by zzyyyl** [comment]
@ABA2396 @horror-proton 摇几个人来看看

**Comment by zzyyyl** [comment]
> 说到底还是加速券的使用都在一个格子了，只有用完了才会对其他格子进行招募。 如果给加速券添加一个设定，只有识别到TAG是4星以上才使用这样呢

你觉得现在的逻辑会损失黄票吗？

**Comment by Constrat** [comment]
Wait we went from "round robing" the recruits in the 4 slots to give 4★ priority with the expedited plan.

Part of what you're saying is a duplicate of: if I recruit only 1 at a time, and it's always a 4★, MAA will not refresh the other recruits (which is differe if I'm understanding correctly)

**Comment by HoshinoAyako** [comment]
> Wait we went from "round robing" the recruits in the 4 slots to give 4★ priority with the expedited plan.
> 
> Part of what you're saying is a duplicate of: if I recruit only 1 at a time, and it's always a 4★, MAA will not refresh the other recruits (which is differe if I'm understanding correctly)

sorry i didn't say clearly :(
for beginning i suggest the recruit slots should for fill. the recruit tag already frush when i done the recruit. i don't wanna miss the tag if frush the 4★ or other.
than i realize i should suggest the expedited plan when not gonna use in 3★ case。
the expedited plan are waste to use to recruit 3★。

**Comment by zzyyyl** [comment]
自动使用加急券是在你需要大量招募的时候用的，它也只生效一次。

之前说过了，后面的格子刷新出四星的概率和你在这个格子出四星的概率是一样的（
而且就算后面格子出了四星，明天还能招募啊，也没浪费

**Comment by status102** [comment]
玄学？感觉没必要

**Comment by HoshinoAyako** [comment]
> 自动使用加急券是在你需要大量招募的时候用的，它也只生效一次。
> 
> 之前说过了，后面的格子刷新出四星的概率和你在这个格子出四星的概率是一样的（ 而且就算后面格子出了四星，明天还能招募啊，也没浪费

准确点说。。公招券很多，加速券很少，想把加速券用在有用的tag，不想浪费在3星：(
而且公招是黄票稳定收入的来源之一。

**Comment by Constrat** [comment]
Efficiency wise nothing would change.
The only way to get inefficiency Is if:
MAA always picks a 4★ in the first recruit slot and doesn't use the refreshes correctly.
The expedited plan would only be useful if there are ONLY 4★ in all the slots so and the finish time is >>> than the next refresh time cap, but honestly that's a remote possibility

**Comment by ABA2396** [comment]
加急许可的那个选项只是单次生效啊。而且白票的获取数量一天招4次都不够吧(30+40+35+5)/30=3.7，如果一天跑一次任务，白票还比加急少估计挺少见的
