### ISSUE TITLE
日服信用商店无视黑名单购买了碳

### ISSUE THREAD

**Issue by MejiroSilence** [MaaAssistantArknights/MaaAssistantArknights#6997]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

日服信用商店购物，黑名单以及优先购买为默认的
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59904337/14526c08-a344-4c95-8aa6-d751e0d1ab47)
然而依旧购买了碳
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59904337/d2741a72-5dac-4705-8e2a-7406edc3de0d)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13034634/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13034635/gui.log)
大概16539行开始

**Comment by MejiroSilence** [comment]
看了看之前的issue，说只要填客户端对应文本即可，明天试试
（虽然但是，是不是应该根据MAA选择的客户端，调整一下默认的选项）

**Comment by zzyyyl** [comment]
这部分的 OCR 是直接识别子串的，没有经过翻译）

**Comment by ABA2396** [comment]
这玩意没做替换，识别到啥就用啥判断
