### ISSUE TITLE
刷理智时选择关卡的时候无法滑动导致刷理智失败

### ISSUE THREAD

**Issue by Shaun-tshp** [MaaAssistantArknights/MaaAssistantArknights#7000]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷理智任务时在选择主线关卡的时候无法进行滑动操作

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13038013/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13038017/gui.log)

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71317322/84bd9a4d-60f7-472c-ae4f-8940ee11e429

### 还有别的吗？

MuMu12
Win10 22H2

**Comment by zzyyyl** [comment]
v4.26.0-b1 的 maatouch 有 bug，已经在内测版修复。
