### ISSUE TITLE
beta.1.d031.gfb13a0f94 | 肉鸽战斗结束后直接放弃探索

### ISSUE THREAD

**Issue by HoshinoAyako** [MaaAssistantArknights/MaaAssistantArknights#7003]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽进入关卡战斗结束后，直接放弃探索了。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13041561/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13041562/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/3415665d-5edb-44f4-adeb-119e0340649c)

**Comment by HoshinoAyako** [comment]
此前4.26.0-beta.1.d010并没有出现这个情况。

**Comment by HoshinoAyako** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/0b112ca6-3e43-4882-bee8-91848c4fc0e2)

**Comment by HoshinoAyako** [comment]
@zzyyyl

**Comment by HoshinoAyako** [comment]
我又重新试了下，确信这是可以复现的情况。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/35a1c185-e42d-4dae-a09b-fffdc9a76952)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/6ae225ec-fe5c-49c0-aa9f-abe073fb6fd4)

**Comment by yyyy52** [comment]
出现同样问题

**Comment by Xi-ZiLang** [comment]
出现同样问题，重新下也一样

**Comment by Qiansyyy0215** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/101891119/60dfa7a4-16c1-4495-a9e5-18542d054e6e)
出现同样问题

**Comment by Constrat** [comment]
Let me have a look at this.
[alpha/v4.26.0-beta.1.d010.g7c01a3a14](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/alpha%2Fv4.26.0-beta.1.d010.g7c01a3a14) Works
[alpha/v4.26.0-beta.1.d031.gfb13a0f94](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/alpha%2Fv4.26.0-beta.1.d031.gfb13a0f94) Does not work?
@HoshinoAyako

**Comment by Lancarus** [comment]
In every theme

i don’t know why 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/c5ec2770-2226-4d59-b257-35c97ff3dea1)
Abadon task is here
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/4c26c539-e633-4e11-a2fc-cd70c9544b79)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/f6e2a2a7-23a3-4312-8c59-5840d59e47d1)

**Comment by Constrat** [comment]
How about:
- 4beb733fcffbb430df849d712bb27ac0c660ef33
- #6844

**Comment by XIYUMEXU** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/148470807/3be37f51-15fb-4a9a-a641-17959ee7ee6e)
出现同样问题

**Comment by zzyyyl** [comment]
probably fixed by 86601f4fac6673207a9bbb00efd1d0decc5a4834

anyone test?

**Comment by Constrat** [comment]
Let me try real quick
