### ISSUE TITLE
自动专三功能

### ISSUE THREAD

**Issue by tsctsc6** [MaaAssistantArknights/MaaAssistantArknights#7005]
### 在提问之前...

- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

建议出自动专三功能

### 有什么好的想法？

* 可以用爬虫，从[prts.wiki](https://prts.wiki/w/%E9%A6%96%E9%A1%B5)获取某个干员的专三材料
* 结合“仓库识别”功能，计算需要合成的材料和缺少的蓝材料（2级材料）
* 根据上一步的结果，让MAA自动合成材料，自动专精
* 我写了个[项目](https://github.com/tsctsc6/Arkgihts_Operators_Skill_Level10_GUI)，完成了前两步，但是我对MAA的结构和图像识别什么的不熟悉，剩下的就交给大佬了

**Comment by MobiusT** [comment]
期望能在此基础上增加专精列表 ，a干员1技能，b干员3技能等 如果找不到（基建占用、等级不够等）则跳过并专精下一个
