### ISSUE TITLE
在刷难度的时候，当成功打到最终关的时候发通知提醒手操

### ISSUE THREAD

**Issue by XingHaiHuShen** [MaaAssistantArknights/MaaAssistantArknights#7006]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我没有很多的时间来打肉鸽，但是我仍然想要肉鸽的蚀刻章，为此我需要刷到一定的肉鸽难度，因此我想要通过MAA来刷好的藏品和角色，以减少凹度，但是我发现前边过的很简单，唯独在最后一关的阵亡率非常高，以至于不能更方便的刷高难度

### 有什么好的想法？

我希望能添加一个肉鸽策略：刷难度，尽可能稳定的打到最终关然后发个通知提醒用户已经打到最终关了，然后最终关让用户来打而不是MAA自己打然后最后一关很难过

**Comment by Saratoga-Official** [comment]
在萨卡兹肉鸽已实现

**Comment by XingHaiHuShen** [comment]
十分感谢，已经在用了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月12日(周一) 晚上6:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 在刷难度的时候，当成功打到最终关的时候发通知提醒手操 (Issue #7006)




 
在萨卡兹肉鸽已实现
