### ISSUE TITLE
suface go 2 win11家庭版无法启动maa

### ISSUE THREAD

**Issue by Tox5411** [MaaAssistantArknights/MaaAssistantArknights#7008]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

4.25和4.26都无法启动，换arm64提示无法在电脑版本上运行s9

### 日志文件

无日志

### 截图

无

### 还有别的吗？

模拟器 mumu12
系统   windows家庭版22h2  
设备 suface go 2 8+128 m3-8100y

**Comment by Constrat** [comment]
This seems very strange. If Windows's running there shouldn't be any issues as everything is handled by the OS.
Make sure you have the necessary C++ redistributions.
Example:
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/b192c45e-73ef-466a-8687-a60701db50f1)

**Comment by zzyyyl** [comment]
修好了？修好了就关
