### ISSUE TITLE
自动战斗作业 CE-6无法使用技能

### ISSUE THREAD

**Issue by zaiziw** [MaaAssistantArknights/MaaAssistantArknights#701]
当摆好水月和神之后，水月迟迟不使用技能，甚至后续部署红蒂也无法成功
[水月你为什么只是看着啊-CE-6_水月+异客+浊心斯卡蒂.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8822524/-CE-6_.%2B.%2B.zip)

**Comment by zaiziw** [comment]
群友说是地图识别有误，附上地
![AS@M_{~SSRPH9```09Y6~HM](https://user-images.githubusercontent.com/27818332/171601319-3bc84e44-83b4-41aa-b06d-a2237bf42e8f.jpg)
图

**Comment by MistEO** [comment]
是的，有部分地图识别不准，在修了（~~新建文件夹~~

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/bfbae56e3e3ad3015da9c328d7d4ab6e1c4a9f4e fixed
