### ISSUE TITLE
基建自动换班怎么不能自选按照哪个换班了

### ISSUE THREAD

**Issue by Zincccccck** [MaaAssistantArknights/MaaAssistantArknights#7011]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

由于我并不习惯总是挂着MAA，电脑总是要干一些其他事情的，一直挂模拟器占内存。并且经常会忙的顾不上换班，基建自动换班所以我是设置好几套配置，直接在需要的时候切换的，并不是固定时间。以前换班的时候只需要点选一下现在是换A组还是B组。但是最近更新怎么只要一点开始就会立马切回去。之前一直是可以的，完全是负优化

### 有什么好的想法？

希望回调，手动切换基建计划点开始不会立马自动改回去

### 其他内容

![Snipaste_2023-10-20_13-25-44](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94158391/2ac57c7d-87af-45ac-8879-4dbeab3d8fd6)
![Snipaste_2023-10-20_13-25-54](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94158391/05f9eeba-dc0c-4ebb-9891-c43a0e72fac8)

**Comment by zzyyyl** [comment]
不是固定时间你就别写period

**Comment by Private233** [comment]
#6921

**Comment by Private233** [comment]
> #6921

1自己去json文件把period字段删除
2在一图流网站写排班的时候把时间删去变成灰字

**Comment by ABA2396** [comment]
8950d2ceaffb9934e77677ec4b64fd71fff1ff5f fixed
