### ISSUE TITLE
macOS Sonoma 使用给定playover启动明日方舟闪退

### ISSUE THREAD

**Issue by isaacveg** [MaaAssistantArknights/MaaAssistantArknights#7018]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

按照要求使用相应playcover和脱壳版明日方舟，使用macOS Sonoma developer beta，在M2 MacBook air 16g版上无法打开明日方舟官服脱壳app，显示闪退。

### 日志文件

[macos生成错误报告.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13055106/macos.txt)

### 截图

<img width="528" alt="截屏2023-10-20 22 07 16" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57183571/ac3ede6e-7564-4bb8-9879-da527002a535">
！
<img width="527" alt="截屏2023-10-20 22 07 20" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57183571/0931a3c7-e24d-472d-9282-5b33c7b208cb">
<img width="519" alt="截屏2023-10-20 22 07 25" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57183571/a587ad7b-187f-4098-a839-fce8a30dc0e3">
<img width="517" alt="截屏2023-10-20 22 07 12" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57183571/f5462a9b-7d9d-4fbb-806d-a895fa04071d">

### 还有别的吗？

之前可以正常使用，某天开始突然无法正常启动，具体日期忘了，怀疑和macOS更新有关

**Comment by wangl-cc** [comment]
https://github.com/hguandl/PlayCover/issues/6#issuecomment-1763438517

**Comment by hguandl** [comment]
移到 #7083 继续讨论。
