### ISSUE TITLE
我想把无人机换成加速赤金生产，但是无人机用途被锁死了想问下这个变灰的部分怎么搞

### ISSUE THREAD

**Issue by xzf0509** [MaaAssistantArknights/MaaAssistantArknights#7020]
### 说说你遇到的问题？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59432567/788b3f63-de6f-48f3-9957-580d4f8d7f13)
如图
<img width="600" alt="Snipaste_2023-10-21_01-06-50" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59432567/9a870e20-6070-48a1-a4ff-360ab11b7b59">

**Comment by Constrat** [comment]
With custom base on, you can't change that option from MAA.
You have to change it in the .json (it's hardcoded)
Example: 
```json

"title": "GOLD",
"author": "Constrat",
"description": "Drone: GOLD",
"plans": [
{
	"name": "LOW TRADING",
	"description": "FAC UP",
	"period": [
		[
			"09:40",
			"12:59"
		]
	],
	"drones": {
		"enable": true,
		"index": 3,
		"room": "manufacture",
		"order": "pre"
	},
...
```
