### ISSUE TITLE
选择休眠动作则结束后脚本没时间运行

### ISSUE THREAD

**Issue by Private233** [MaaAssistantArknights/MaaAssistantArknights#7023]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我设置了结束后脚本森空岛签到，今天选了这条maa完成后动作，发现maa完成后，结束脚本没时间进行，系统直接休眠了。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108540840/47143ddf-19dd-44d1-9c40-46d988b36518)
打开电脑后脚本如图。
<img width="735" alt="5fc858d0ed7ae3c6cec01fe777201ad9" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108540840/da833c72-9b15-48e4-8b2e-9f79edb2039f">

### 日志文件

其他选项情况暂未测试。

**Comment by zzyyyl** [comment]
@ABA2396

**Comment by zzyyyl** [comment]
`start /wait`?
