### ISSUE TITLE
萨米肉鸽不期而遇 先行一步 无法选择干员

### ISSUE THREAD

**Issue by AdenCat** [MaaAssistantArknights/MaaAssistantArknights#7025]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽进入先行一步后无法选择干员，随后自动放弃。

### 日志文件

2023-10-21 18:37:29.083 自动放弃探索
2023-10-21 20:46:38.662 主动停止mma运行
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13060747/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13060756/asst.zip)

**Comment by HoshinoAyako** [comment]
duplicate of #6460
