### ISSUE TITLE
用新出的迷城界面maa就会识别不出来

### ISSUE THREAD

**Issue by KutahaniSayo** [MaaAssistantArknights/MaaAssistantArknights#7026]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我这两天maa都说识别错误，重装了以后也这样。
今天我心血来潮把界面皮肤换成其他的就可以运行了

### 日志文件

111

### 还有别的吗？

mumu，WIN11 RTX3070ti

**Comment by HoshinoAyako** [comment]
在提问前：
我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况。

请更新MAA版本。
