### ISSUE TITLE
MAA在我没选嗑药的情况下自动嗑药并且没提示

### ISSUE THREAD

**Issue by FreeSleep** [MaaAssistantArknights/MaaAssistantArknights#7028]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在我没选使用体力药的时候 MAA在我理智清空的时候自动嗑药了 并且MAA的记录里斌没有显示嗑药

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13062161/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13062165/gui.log)

2023.10.22 9：14：48——9：14：56

### 截图

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=4396921541742775334 skey=@crypt_79ed8144_103921e5f68d3d2b95aaa5632b535744 mmweb_appid=wx_webfilehelper](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/95733842/3f091616-612d-4124-9d89-45708947ccb2)

**Comment by HoshinoAyako** [comment]
你升级了兄弟~。

**Comment by status102** [comment]
21-6+131=>146

**Comment by status102** [comment]
`[2023-10-22 09:14:39.084][TRC][Px4410][Tx46cc] asst::WordOcr [{ {O4: [ 50, 100, 153, 69 ], score: 0.725546 }, { 等级提升: [ 259, 126, 171, 44 ], score: 0.999989 }, { 日: [ 102, 176, 46, 28 ], score: 0.446525 }] by OCR Pipeline , cost 71 ms`
