### ISSUE TITLE
自动战斗障碍物的问题

### ISSUE THREAD

**Issue by ZhaoGY-N** [MaaAssistantArknights/MaaAssistantArknights#703]
1. 自动战斗时概率性放障碍物放不到位。
2. 撤退障碍物已经指定了location但是还是错误的撤回了其他位置的， 再附上json作业（不能传json，改成了txt）。log里应该有好几次放不到位，最后一次是撤错的。
3. 现在开始战斗后需要等较长的时间才能识别干员，部分作业写不了。。。

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8822799/asst.log)
[4-4_安洁莉娜+阿消.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8822805/4-4_.%2B.txt)

**Comment by ABA2396** [comment]
> 

但是障碍物召唤物可以放好几个来着，这个咋撤

**Comment by MistEO** [comment]
> > 
> 
> 但是障碍物召唤物可以放好几个来着，这个咋撤

写坐标就好了，不写干员名

**Comment by MistEO** [comment]
等待较长时间，这个慢慢优化吧

其他俩都修了
