### ISSUE TITLE
萨米肉鸽在肉鸽结束并解锁新收藏品时卡住

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#7033]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

完成肉鸽后解锁了新的收藏品，然后就卡在这里了

猜测可能跟关卡结束后出现的页面数量有关，只会点一次然后出现了多个新页面导致卡住
猜测顺序：每月委托->解锁新收藏品->解锁xxx

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13063073/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13063077/asst.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/a1df6533-8be1-49f9-bec0-f68cdcf279d4)

（↓模拟器内置的截图）
![Screenshot_20231022-192705](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/e5920a29-512a-467d-9c36-39ce6509ce16)

（↓不知道啥的输出debug/roguelike/）
[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13063078/roguelike.zip)

### 还有别的吗？

v4.26.0-beta.1
win10 22H2

**Comment by status102** [comment]
奇怪，后面就都正常能跑，不会跟获得的个数有关吧

**Comment by status102** [comment]
也许跟解锁东西的种类数量有关？

**Comment by zzyyyl** [comment]
怎么不自己修！

**Comment by status102** [comment]
> 怎么不自己修！

在学cmake喵，看看怎么把fw糊进来（make more shit!

**Comment by zzyyyl** [comment]
我超，其实糊fw的最大难点在 taskdata -> pipeline

**Comment by zzyyyl** [comment]
不如设计一个fw友好的实现肉鸽的方法，或者想法子让fw也能用taskdata（x

**Comment by status102** [comment]
糊那个干啥，task太多不好整。先把controller糊了，截图效率upup

**Comment by zzyyyl** [comment]
fw截图比maa快得多吗（？

**Comment by status102** [comment]
玛丽说大概20ms

**Comment by status102** [comment]
然后我自己电脑的话，MAA截图大概200ms，大约差了10倍。没试过fw的项目不知道fw实际跑起来怎么样
