### ISSUE TITLE
自动肉鸽进入下一层时卡在密文板界面

### ISSUE THREAD

**Issue by Ptilopsis01** [MaaAssistantArknights/MaaAssistantArknights#7036]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，自动肉鸽进入第二层后会莫名其妙点击进入密文板界面并不停滑动密文板，且无进一步动作，手动退出该界面后仍然会重复滑动的操作
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/93318731/5f5ea721-3f2f-4a45-98c3-99410a50e1bc)

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13063396/debug.zip)

### 还有别的吗？

maa版本为最新测试版

**Comment by Constrat** [comment]
@Lancarus didn't this fix it?
- #6949

**Comment by Lancarus** [comment]
sorry, but my computer is broken.
i'm trying to buy a new graphic card in these days...please wait...
