### ISSUE TITLE
无法识别覆潮之下菜单

### ISSUE THREAD

**Issue by Stargazer020** [MaaAssistantArknights/MaaAssistantArknights#704]
程序跳到覆巢之下ss的主页面时就会卡住不动，疑似无法识别
手动退出页面后恢复正常

**Comment by Stargazer020** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8823466/asst.log)

**Comment by MistEO** [comment]
这个问题修了有几天了，更新一下版本吧~
