### ISSUE TITLE
有关模板（template）与文字识别（ROI）是否可以自定义使用

### ISSUE THREAD

**Issue by HoshinoAyako** [MaaAssistantArknights/MaaAssistantArknights#7049]
### 说说你遇到的问题？

比如说，给肉鸽的事件选择添加文字识别ROI，或者主题UI场景往后出新的主题时，可不可以自己在JSON改呢？

**Comment by Constrat** [comment]
```json
"LevelOfDifficulty": {
    "Doc": "base_task",
    "algorithm": "OcrDetect",
    "action": "ClickSelf",
    "text": [
        "环境",
        "PRTS"
    ],
    "roi": [
        26,
        565,
        302,
        155
    ],
    "sub": [
        "EnterChooseLevelOfDifficulty"
    ]
},
```
If this is what you are asking yes, you can change the ROI, just need to edit the 4 integers. 
Description:
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/0cf7fcc0-f87a-4fd7-9811-d9b20ac47791)

**Comment by zzyyyl** [comment]
可以啊，改完记得来pr

**Comment by HoshinoAyako** [comment]
我想给肉鸽加一个收藏品优先值的策略，与干员招募策略类似，这样就可以在商店购买藏品的时候，可以有个优先值考虑，甚至可以在交换藏品的时候，将一次性藏品交换出去以获取更优质的道具。

然后给肉鸽的事件策略添加一个根据文字或者模板选择对应的选项，这样就可以深度定制事件的选择。
可以更优质的挂机，类似多次选择，干员派遣，交换藏品等等。

**Comment by HoshinoAyako** [comment]
> 可以啊，改完记得来pr

可是我没学过编程类内容。都是我自己现看现理解的_(:з」∠)_

**Comment by SherkeyXD** [comment]
https://maa.plus/docs/3.4-%E4%BB%BB%E5%8A%A1%E6%B5%81%E7%A8%8B%E5%8D%8F%E8%AE%AE.html
