### ISSUE TITLE
[Feature Request] 关于肉鸽刷开局的需求

### ISSUE THREAD

**Issue by UVJkiNTQ** [MaaAssistantArknights/MaaAssistantArknights#705]
如题，也就是刷到第一个商店，看收藏品是否合意
可以想到的有这几个参数/需求：
1. 编队：初始编队选择>初始角色选择>是否选助战
2. 路线选择：是否需要大锁或者喉舌的剧情，不需要大锁就选+1希望，需要就-1希望。
3. 藏品评估：一般卡罐头or攻速（金酒之杯、骑士戒律等），多个藏品and或者or？
4. 道中处理：遇到招募券的处理方式，只选6星（某职业）干员或者 需求干员列表（如果是后勤开局+大锁目标，要注意大锁事件前留1希望）。非需求事件跳过之类的,，或者逐一指定处理选项？。领取剧目、藏品及源石锭。

**Comment by WWPXX233** [comment]
目前以刷取等级为主 借干员可以先进行手动借干员来到地图界面运行自动肉鸽 其余未来可能会做
