### ISSUE TITLE
蓝叠模拟器5完成任务后无法退出模拟器

### ISSUE THREAD

**Issue by LangYiHai** [MaaAssistantArknights/MaaAssistantArknights#7056]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在完成任务后无法退出模拟器，日志中显示获取模拟器主进程失败。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13096092/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13096114/gui.log)

### 还有别的吗？

蓝叠模拟器版本:5.13.215.1003 P64
操作系统:
版本	Windows 11 家庭中文版
版本	22H2
操作系统版本	22621.2428

**Comment by ABA2396** [comment]
hyperv的蓝叠要管理员权限才能关

**Comment by SherkeyXD** [comment]
> hyperv的蓝叠要管理员权限才能关

我的都不用诶（
