### ISSUE TITLE
肉鸽选人逻辑问题

### ISSUE THREAD

**Issue by Yumi0606** [MaaAssistantArknights/MaaAssistantArknights#7059]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选择异德 --> 再次点击异德 -->选择预备干员
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136778556/cb00fe91-42b4-435f-9bd3-a0310e62e877

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13110574/asst.log)
11:16后两分钟内

**Comment by Yumi0606** [comment]
![Snipaste_2023-10-24_12-02-29](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136778556/a18e4a99-60bd-43b5-b768-4d2eb254c3ce)
![Snipaste_2023-10-24_12-02-21](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136778556/eb7c6d3d-f3c2-4477-8236-49bb5c490148)

**Comment by Lancarus** [comment]
应该在 #7038 修复了，把异德识别成了两个人应该

**Comment by wengzhe** [comment]
纯艾的识别也有点问题，日志里看到了“纯烬艾雅法”，我更新一下https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7038
