### ISSUE TITLE
基建换人无法识别麒麟X夜刀

### ISSUE THREAD

**Issue by MUzyx** [MaaAssistantArknights/MaaAssistantArknights#7069]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA基建控制中枢更换干员无法识别麒麟X夜刀

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13125407/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13125412/asst.log)
出现时间：10.25日02点19分

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125632753/aefd87c5-720d-427e-bc75-8b1d2d7ccb96)

### 还有别的吗？

模拟器版本：雷电9.0.44
游戏版本：B服
MAA版本：4.26.0-beta2

**Comment by Constrat** [comment]
Maybe because the name is not `麒麟X夜刀` but `麒麟R夜刀`

**Comment by MUzyx** [comment]
> Maybe because the name is not `麒麟X夜刀` but `麒麟R夜刀`

我超，才发现居然改名了.....
