### ISSUE TITLE
软件设置自动回滚

### ISSUE THREAD

**Issue by helloIris415** [MaaAssistantArknights/MaaAssistantArknights#707]
经常性的设置会被初始化。比如入住心情变回30，自动加急许可取消，设置adb路径消失。
间隔比较随机，大多在电脑重启3次后设置会初始化。
文件路径：E:\MeoAssistantArknights
软件设置：
![image](https://user-images.githubusercontent.com/63986965/171653390-4948d964-90a4-49de-868f-3d23fae22635.png)
我很确认默认管理员启动与路径设置没有中文完全没有问题，但是还是会经常性出现设置回滚问题。从2.3开始用一直到现在一直都有这样的问题。
附上asst
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8824831/asst.log)
貌似会因为重启被清空

**Comment by WCB666** [comment]
信用商店在购买完最后一件物品后貌似不会自动退出物品的大图，经常得手动再点击一下才会自动继续且不会报错
