### ISSUE TITLE
连接adb阶段点击停止，导致MAA无法连接模拟器

### ISSUE THREAD

**Issue by CharlesChou73** [MaaAssistantArknights/MaaAssistantArknights#7070]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

打开MAA，点击Link Start，MAA开始连接adb；
这时发现有个任务没勾选，就点了停止，MAA卡住大概30秒，然后显示已停止；
再次点击Link Start，就会出现截图所示的提示。

重启MAA可以解决，所以好像不修问题也不大？

### 日志文件

[asst - Copy.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13160672/asst.-.Copy.log)

### 截图

![Snipaste_2023-10-25_10-19-07](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16950543/357cd361-fbc0-4233-9cc7-732785731d97)

### 还有别的吗？

蓝叠国际版

**Comment by zzyyyl** [comment]
#7052

**Comment by zzyyyl** [comment]
试试 v4.26.0-beta.2.d024.g3d26f97a3，先当作修了，有问题再开
