### ISSUE TITLE
一直弹出游戏资源正在更新，请勿退出MAA

### ISSUE THREAD

**Issue by MahiruSu** [MaaAssistantArknights/MaaAssistantArknights#7076]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

每次打开MAA，都弹出“游戏资源正在更新，请勿关闭MAA”的通知。但不论MAA挂几个小时，下次打开还是弹出。

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13167513/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13167516/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49871236/caf8371e-30a4-4577-8691-dfa4ba23bd74)

### 还有别的吗？

MuMu12，Win 11

**Comment by Constrat** [comment]
That's normal. Everytine you open the client, MAA will update it's cache/resource from MaaRelease to allow resource updating (without manually updating to a new version).

**Comment by Lixuhuilll** [comment]
我也是同样的问题，并且资源永远无法自动更新成功，只能手动从GitHub仓库拉取手动进行资源文件替换

**Comment by Constrat** [comment]
What do you mean they don't get updated correctly? You noticed the files not getting modified? Or missing content?

**Comment by Lixuhuilll** [comment]
Not getting modified. Automatic updates simply download version.json.checks.tmp
