### ISSUE TITLE
日服基建换班宿舍卡住

### ISSUE THREAD

**Issue by uuuumi** [MaaAssistantArknights/MaaAssistantArknights#7082]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA-v4.26.0-beta.2-win-x64在基建换班在换宿舍时候卡在点击右上角的筛选界面（右上角信赖度右上角的按钮）
beta2特有bug beta1还正常使用的，4.25正式版1.7有问题（beta已解决）。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13175157/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13175158/asst.log)

### 截图

![截屏2023-10-26 16 46 29](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/118824556/77b173ef-341e-4811-9042-74cb177476f0)

### 还有别的吗？

蓝蝶模拟器国际版5.13.200
win10 22H2

**Comment by Constrat** [comment]
Fixed with #7068
Update to a nightly
