### ISSUE TITLE
[macOS] PlayCover 在 macOS Sonoma 14.1 上无法使用

### ISSUE THREAD

**Issue by hguandl** [MaaAssistantArknights/MaaAssistantArknights#7083]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

需要等待上游解决 https://github.com/PlayCover/PlayCover/issues/1179

### 日志文件

N/A

**Comment by hguandl** [comment]
目前收集了一些反馈 #7018 https://github.com/hguandl/PlayCover/issues/5 https://github.com/hguandl/PlayCover/issues/6 和研究 https://github.com/PlayCover/PlayTools/pull/127 ，我会尽快尝试可能的方案

**Comment by hguandl** [comment]
新版本 [v3.0.0.maa.4](https://github.com/hguandl/PlayCover/releases/tag/v3.0.0.maa.4) 应该解决了

**Comment by gresgrta4gerg** [comment]
I am playing the Korean version and the problem was not resolved even with version .3.0.0.maa.4
