### ISSUE TITLE
macOS 14.1 MAA正确设置但无法开始任务的可能解决方案

### ISSUE THREAD

**Issue by isaacveg** [MaaAssistantArknights/MaaAssistantArknights#7089]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

macOS 14.1 中，使用最新MAA和最新playcover，能够正常打开游戏，但是无法继续进一步操作。    

具体表现为：点击开始后，可以正常启动playcover和游戏客户端，图标变为等待转圈，长时间后变回初始状态（即三角形开始图标）；重复点击后，图标立刻变为初始状态。

尝试解决：猜测为权限不够。新系统可能采用了不同的鉴权方式。以下是使用过的全部方法：

0. 首先确认是否将连接方式更改为macPlayTools，以及其他正确设置
1. 系统设置--通用--共享--高级--三项全开；
2. 系统设置--通用--共享--本地主机名--更改为非默认的名称并且不包含中文，不使用动态主机名；如：从XiaoMingde MacBook.local更改至foobarmac.local。灵感来源：(https://stackoverflow.com/a/72862978).      
3. 系统设置--隐私与安全性，将MAA手动加入开发者工具，辅助功能以及完全磁盘访问权限（谨慎）
4. maa连接设置中将localhost:port换成127.0.0.1:port

在进行上述操作后成功恢复连接。成功后尚书更改可以取消，暂时没有发现无法连接的情况。如果可以的话，可以加入docs中

### 日志文件

具体记录已消失，有一部分：

adb connection refused

device offline

**Comment by ABA2396** [comment]
cc @hguandl
