### ISSUE TITLE
MAA雷电模拟器点击错位

### ISSUE THREAD

**Issue by TianMing86** [MaaAssistantArknights/MaaAssistantArknights#7090]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA即使用管理员启动，点击“Link Start”后会进入活动或终端，然后一直点击左下角“终端”的位置，不能正常执行操作。 连接设置调整无效。
雷电9(127.0.0.1:5555)-官服
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91136817/cf52bf6b-6931-4be1-a0b1-ade17b9edba3

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13186936/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13186937/asst.log)

**Comment by zzyyyl** [comment]
考虑是不是你模拟器卡了；

另外可以更新一下版本

**Comment by zzyyyl** [comment]
有没有雷电模拟器的版本信息

**Comment by TianMing86** [comment]
9.0.61(9)/安卓9.0(64位)

**Comment by TianMing86** [comment]
雷电和MAA一周内下载的，试过改连接、改触控都没有

**Comment by zzyyyl** [comment]
link to #1171

**Comment by zzyyyl** [comment]
> 雷电和MAA一周内下载的，试过改连接、改触控都没有

这期间没有一次是正常的（？

我也用的雷电啊我怎么一直正常.jpg

**Comment by TianMing86** [comment]
用OBS录了一遍，我也不知道这个是什么情况
[将后缀.zip改为.mp4](https://tianchenbeiming.lanzoub.com/izxAx1d0khna)
刚刚用管理员改成MaaTouch再运行后行了一会，然后显示ADB连接失败，无法重连

**Comment by zzyyyl** [comment]
adb连接失败可能需要重启一下电脑

**Comment by TianMing86** [comment]
现在改成MaaTouch后能用了，不知所以然

**Comment by zzyyyl** [comment]
有空的话帮忙再测测minitouch，谢谢
顺带一提，更换触控方式需要重启maa

**Comment by ABA2396** [comment]
模拟器在桌面的时候是竖屏的还是横屏的

**Comment by TianMing86** [comment]
应该是调用了我安装在PROGRAM FILES的ADB，然后没有管理权限，所以只能点击左下角。已经解决了。
