### ISSUE TITLE
基建换班不使用无人机

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#7093]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

rt，未开启beta模式，无法使用无人机

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13190267/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13190271/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13190287/gui.log)

### 截图

<img width="902" alt="捕获" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90097743/f5379deb-a204-4c61-9c79-9bc61c562c37">

**Comment by Constrat** [comment]
How can it use drones when the Manufacturing station is not selected?
