### ISSUE TITLE
【无法识别】无法部署拉普兰德

### ISSUE THREAD

**Issue by Agnes4m** [MaaAssistantArknights/MaaAssistantArknights#7094]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

五星近位角色拉普兰德，在使用原始皮肤和精英2皮肤后，虽然可以被选择干员时正确识别，但是在部署的时候无法识别到角色，导致

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13191900/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13191901/asst.log)

### 截图

此处截图为我发现问题后，手动补上拉普兰德并截图
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70925546/a3a412f0-8124-4228-980f-f1494c80fc36)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70925546/9a452a0c-6bf4-4fd4-9c17-3ee0a5d6ecbf)

### 还有别的吗？

电脑：win10 64位置家庭版
模拟器：雷神模拟器9 64位

如果换成我最喜欢的拉普兰德的皮肤，似乎是可以正确部署的，但是无法识别其他皮肤明显是个错误。

**Comment by zzyyyl** [comment]
检查 cache/avatars

**Comment by Agnes4m** [comment]
已无问题
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70925546/2be9ad21-1e7a-4ebe-9522-914c154b66fc)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70925546/0c87546f-3a3d-4fc2-834b-d2374b56fbde)

**Comment by zzyyyl** [comment]
好像是识别成 铸铁 了，看看你的 cache/avatars/铸铁.png 的保存时间

缓存头像的问题是 4.26.0.b1 解决的，大概在 10.18 左右）

**Comment by Agnes4m** [comment]
确实，变成精英2皮肤了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70925546/523dfcf6-2b65-4746-9787-c0ac5277560b)

**Comment by Agnes4m** [comment]
出问题的时候，当前f版本号 4.26.0b2
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70925546/2a9717b8-8ede-4905-9ae5-df6bcfe6e803)
