### ISSUE TITLE
macos14系统，playcover版本3.0.0.maa.4，MAA版本v4.25.0（417），刷1-7：“任务出错：Fight”

### ISSUE THREAD

**Issue by ZoffyCapt** [MaaAssistantArknights/MaaAssistantArknights#7095]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

macos14系统，playcover版本3.0.0.maa.4，MAA版本v4.25.0（417），触控模式是MacPlayTools，1-7或：“任务出错：Fight”。
触控模式换成maatouch，多试几次，刷1-7偶尔能动起来。
但是肉鸽就一直在加载不动。日志和截图如下。1-7失败在4点50分，后续一直是肉鸽加载。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13193247/asst.log)

### 截图

<img width="1473" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111342242/b057373b-e638-4ff1-a402-27d43d12b176">
<img width="1474" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111342242/8b457243-eb3c-464d-9fce-6432bed0d1c7">

**Comment by ABA2396** [comment]
v4.25.0还没支持这个主题
