### ISSUE TITLE
程序停止在Startup任务

### ISSUE THREAD

**Issue by Lanstile** [MaaAssistantArknights/MaaAssistantArknights#7098]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在上周日应该是还可以用的，然而这周就显示了如题的问题。在进入主界面签到之后不会出现任何反应。强制替换ADB、切换触控模式、重启电脑、重装MAA均无反应。使用的是MUMU12模拟器最新版。
![QQ截图20231028170412](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149232604/1efa8b2e-643a-4d8e-a962-a61140558fc7)
![QQ截图20231028170537](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149232604/9966fd24-d619-4b0e-9cdb-ce41abb8a137)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13195003/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13195004/gui.log)

**Comment by zzyyyl** [comment]
换主题 or 更新测试版

**Comment by Lanstile** [comment]
> 换主题 or 更新测试版

什么意思

**Comment by zzyyyl** [comment]
你截图里游戏界面是迷城主题，换其它三个

**Comment by zzyyyl** [comment]
或者你把maa更新到测试版，测试版有迷城主题的支持

**Comment by Lanstile** [comment]
> 你截图里游戏界面是迷城主题，换其它三个

哦，好的，谢谢大佬！

**Comment by Lanstile** [comment]
> 你截图里游戏界面是迷城主题，换其它三个

谢谢，可以用了！

**Comment by Lanstile** [comment]
> > 你截图里游戏界面是迷城主题，换其它三个
> 
> 哦，好的，谢谢大佬！

现在可以正常使用MAA了，谢谢
