### ISSUE TITLE
选择“完成后退出maa和模拟器”结束任务后通知消失

### ISSUE THREAD

**Issue by shiguang2016** [MaaAssistantArknights/MaaAssistantArknights#7100]
### 说说你遇到的问题？

选择“完成后退出maa和模拟器”结束任务之后会弹出一个提示理智剩余多长时间恢复完全的弹窗
如果选择不关闭maa通知就会保存
选择关闭maa通知就会弹出同时被清除
这个问题应该是win11的问题吧，可以解决吗
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13195466/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13195467/asst.log)

**Comment by orilights** [comment]
遇到了同样的问题，设置任务结束后关闭MAA，通知弹出来闪一下就直接消失了，通知列表里也看不到，希望可以加一个选项，任务结束后延迟 x 秒再关闭MAA，或者用其他什么办法保留住这条通知。

MAA版本：v4.25.0
Windows版本：Windows 11 22621.2506

**Comment by Constrat** [comment]
If it's a Windows notification it will stay in the notification log only if:
- [ ] Show notifications in notification centre 

is selected

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/2a58db37-a3d9-4c91-952e-7e92ab127f7b)

**Comment by status102** [comment]
> If it's a Windows notification it will stay in the notification log only if:

设置了，而且似乎如果MAA直接关机，Toast就会被保留；如果手动关MAA，Toast就会被关闭
