### ISSUE TITLE
Win10 下 MuMu 模拟器6 启动 MAA 无限循环弹窗提示 "由于找不到 AdbWinApi.dll ..."

### ISSUE THREAD

**Issue by OrekiYuta** [MaaAssistantArknights/MaaAssistantArknights#7102]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

#### 环境
MAA: v4.25.0
OS: win10 x86
MuMu: 2.7.23.0

#### 详情
打开 MAA 点击 Link Start 启动后，无限弹窗提示 “缺少 AdbWinApi.dll” , 循环启动错误提示弹窗进程，导致系统卡死

在 MuMu 文件夹目录能够找到该 AdbWinApi.dll

出现该问题之前使用一切正常，无任何 MAA 和 MuMu 配置改动
但不确定是否外部其他软件等因素导致问题发生

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13195960/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13195961/gui.log)

### 截图

<img width="447" alt="Snipaste_2023-10-28_21-57-10" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45684547/a9bab5d3-7e72-43a4-a1c1-ce21686bddd2">
<img width="494" alt="Snipaste_2023-10-28_21-46-08" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45684547/d04178a5-0450-4093-91b6-d8595580731b">
<img width="273" alt="Snipaste_2023-10-28_21-46-28" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45684547/5af9b4fc-c27f-41a7-8f2e-d9a30f9374fe">
<img width="467" alt="Snipaste_2023-10-28_21-45-50" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45684547/def4f5e9-20c0-414f-aff5-806577fa2c2e">
<img width="254" alt="Snipaste_2023-10-28_21-46-41" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45684547/573d86aa-6c98-4c24-b8e5-a94c1727ace3">
<img width="245" alt="Snipaste_2023-10-28_21-49-09" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45684547/34e28307-38d5-4f40-ab36-ee8e2cf08500">

**Comment by Manicsteiner** [comment]
目前显然是使用了外部的adb.exe，建议将adb路径设置为最后一张图中的adb_server.exe并“强制替换 ADB”。详细参考使用说明 [MuMu 模拟器 6](https://maa.plus/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.html#%E2%9A%A0%EF%B8%8F-mumu-%E6%A8%A1%E6%8B%9F%E5%99%A8-6)

**Comment by OrekiYuta** [comment]
已解决，感谢
