### ISSUE TITLE
无法进行自动刷理智

### ISSUE THREAD

**Issue by N602FE** [MaaAssistantArknights/MaaAssistantArknights#7104]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选择刷理智之后卡死在选关界面，无法进入指定关卡，随后显示任务出错

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13196668/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13196669/gui.log)

发生于 10-29 04:23:08至04:24:30

### 截图

<img width="207" alt="屏幕截图 2023-10-29 042455" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149270526/fb97c8f7-d036-47cc-94b5-f86eaf9c23ba">

<img width="1079" alt="屏幕截图 2023-10-29 042418" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149270526/8529058d-e98a-4232-a5ce-4eb19c9e5998">
卡死在图二的界面不动

**Comment by Constrat** [comment]
I just noticed this as well. fix commit 4e792626a55792e4793d8d58a1ff6716e6cd64c9 has been pushed.
Nightly version has been started: https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/6679245123
Wait 20~25 minutes and then force nightly update

**Comment by Lanstile** [comment]
> I noticed this as well only now. (more insight as to what happened: they moved the screens, inverting the new chapter with the event as it should be) fix commit [4e79262](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/4e792626a55792e4793d8d58a1ff6716e6cd64c9) has been pushed. Nightly version has been started: https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/6679245123 Wait 20~25 minutes and then force nightly update

我不确定您说的是不是已经更新了新版本的MAA。就在刚才我也遇到了相同的问题并在看到此问题后更新了MAA（现在MAA显示为最新版本），但此问题仍然没有解决。现在我尝试的代替方法是选择“上次作战”代替直接定位到IS关卡

**Comment by status102** [comment]
> 我不确定您说的是不是已经更新了新版本的MAA。就在刚才我也遇到了相同的问题并在看到此问题后更新了MAA（现在MAA显示为最新版本），但此问题仍然没有解决。现在我尝试的代替方法是选择“上次作战”代替直接定位到IS关卡

如果你不确定是不是更新了最新版本的MAA，为啥不报一下你自己的版本（让别人猜吗
更新内测

**Comment by Lanstile** [comment]
> > 我不确定您说的是不是已经更新了新版本的MAA。就在刚才我也遇到了相同的问题并在看到此问题后更新了MAA（现在MAA显示为最新版本），但此问题仍然没有解决。现在我尝试的代替方法是选择“上次作战”代替直接定位到IS关卡
> 
> 如果你不确定是不是更新了最新版本的MAA，为啥不报一下你自己的版本（让别人猜吗 更新内测

版本号显示的是4.25.0，点了几遍检查更新显示的都是最新版（不过是稳定版）。是要更新到内测版吗？

**Comment by status102** [comment]
> 版本号显示的是4.25.0，点了几遍检查更新显示的都是最新版（不过是稳定版）。是要更新到内测版吗？

更内测，已经修了

**Comment by Lanstile** [comment]
> > 版本号显示的是4.25.0，点了几遍检查更新显示的都是最新版（不过是稳定版）。是要更新到内测版吗？
> 
> 更内测，已经修了

好的，谢谢。
不过我一直用的是稳定版，请问内测版比起稳定版会不会不稳定一些？

**Comment by status102** [comment]
> 好的，谢谢。 不过我一直用的是稳定版，请问内测版比起稳定版会不会不稳定一些？

肯定的，但是稳定版有些东西就要等

**Comment by Lanstile** [comment]
> > 好的，谢谢。 不过我一直用的是稳定版，请问内测版比起稳定版会不会不稳定一些？
> 
> 肯定的，但是稳定版有些东西就要等

好的，非常感谢
