### ISSUE TITLE
关于肉鸽招募的算法，希望能帮助减少招募造成的时间浪费

### ISSUE THREAD

**Issue by Misaka10745** [MaaAssistantArknights/MaaAssistantArknights#7105]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

我看了好久maa打肉鸽，发现每次招募maa都要从头刷一遍干员列表一直刷到尾，即使上一个券与这一个券相同
我就在想，maa是不是可以第一次招募的时候刷一遍box，然后把数据建一个缓存文件存下来
招募后，临时招募，随机直升这样的识别到给一个标记，这一局不再用
我知道这个很难实现，并且可能影响底层代码，就是提供一个小小的思路
还有就是连续肉鸽的时候开局抓谁基本上是固定的，是不是也可以用上面的办法节约时间，毕竟连续打干员练度肯定不会变
希望对你们有帮助！

**Comment by SherkeyXD** [comment]
但是新出现的临时招募和随机直升还是要识别的吧

**Comment by Lancarus** [comment]
难以实现

**Comment by status102** [comment]
如果把肉鸽数据迁移了应该就好糊
