### ISSUE TITLE
maa无法正确识别“叙拉古人”活动

### ISSUE THREAD

**Issue by cjyfs** [MaaAssistantArknights/MaaAssistantArknights#7106]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

之前一切正常，今早maa忽然卡在终端界面无法选择“叙拉古人”活动

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13197073/gui.log)
asst.log压缩后也太大了（

### 截图

![Image_1698546395661](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120154447/63a7dcdd-48c2-4799-b056-405134642885)

**Comment by enifeder** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/65483484/872048b8-4a68-455f-bb58-9a82b744a4d0)
IS-Open 无法识别，怀疑是代币挡了一部分

**Comment by status102** [comment]
fixed by v4.26.0-beta.2.d051.g4e792626a

**Comment by Ptilopsis01** [comment]
现在可以正常进入活动界面，但没法开始战斗
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13197260/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13197261/gui.log)

**Comment by cjyfs** [comment]
换到4.26.0公测版之后会选中IS-1
