### ISSUE TITLE
AVD通用模式连接失败

### ISSUE THREAD

**Issue by RWoxiN** [MaaAssistantArknights/MaaAssistantArknights#711]
更新到3.9版本之后就出现了该问题，此版本之前运行正常

日志报错：Uuid command failed to exec
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8829114/asst.log)

![image](https://user-images.githubusercontent.com/78133217/171776148-d6167142-8c32-4d7b-9795-d87685e9acdc.png)

AVD系统版本：
![image](https://user-images.githubusercontent.com/78133217/171777007-e032e1a2-c028-427c-8c35-baa0d49abbbb.png)

**Comment by MistEO** [comment]
换 `兼容模式` 试一下

**Comment by RWoxiN** [comment]
> 换 `兼容模式` 试一下
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8829313/asst.log)
还是连不上

**Comment by MistEO** [comment]
打开日志照着命令手动敲下试试，这端口压根连不上，先保证手动能连上吧（

**Comment by RWoxiN** [comment]
> 打开日志照着命令手动敲下试试，这端口压根连不上，先保证手动能连上吧（

尴尬，是这样，端口不知道啥时候变成5555了
