### ISSUE TITLE
IS关卡导航失败

### ISSUE THREAD

**Issue by dylanhz** [MaaAssistantArknights/MaaAssistantArknights#7111]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新到最新内测版后， 不再卡在终端页面，但是在选关页面卡住了，选不到IS-10。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13197262/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13197263/gui.log)

### 截图

![Snipaste_2023-10-29_13-36-57](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/53137516/5c0a2d78-90fb-4e6e-afbe-ec4bee780ef5)

**Comment by Yingge02** [comment]
遇到了同样的问题……

**Comment by cjyfs** [comment]
我是更新到公测版4.26.0之后设置了IS-8结果选到IS-1去了

**Comment by Dilrevx** [comment]
+1，刷 IS-8 选到 IS-1 了

**Comment by joshua0blake** [comment]
草，我也是，直接开is-1了
