### ISSUE TITLE
剿灭异常刷取次数问题

### ISSUE THREAD

**Issue by TouchedOVO** [MaaAssistantArknights/MaaAssistantArknights#7121]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

从凌晨1点开始，一直到9点，一直在刷剿灭

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13200030/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13200031/gui.log)

**Comment by ABA2396** [comment]
这是没有扫荡券吗

**Comment by TouchedOVO** [comment]
破案了，是点完开始战斗不管了，一直刷的模拟战，模拟战是不会停的

**Comment by TouchedOVO** [comment]
如果能分辨能不能刷模拟战就好了
