### ISSUE TITLE
周常卡OF-1停止

### ISSUE THREAD

**Issue by uuuumi** [MaaAssistantArknights/MaaAssistantArknights#7124]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷OF-1过周常显示掉落识别错误、无奖励关卡，已停止，然后自己清剩余理智去了。关卡选择手动填的OF-1，也能识别，就是不打

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13200910/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13200912/gui.log)

**Comment by MistEO** [comment]
设计如此，可以刷 OF-2 之类的

**Comment by uuuumi** [comment]
好滴 感谢！
