### ISSUE TITLE
完成后动作追加一个"返回桌面"

### ISSUE THREAD

**Issue by Miuzarte** [MaaAssistantArknights/MaaAssistantArknights#7132]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

启动游戏和启动模拟器的时间都太长了，增加一个返回桌面的选项把游戏挂到后台，省电的目的达到了 再次回到游戏也不需要太多时间
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66856838/4665e810-ce90-4eea-af28-596855ccea4c)

**Comment by Manicsteiner** [comment]
是指windows系统返回桌面还是安卓虚拟机返回桌面（写完windows的返回桌面才想起来）

**Comment by Miuzarte** [comment]
> 是指windows系统返回桌面还是安卓虚拟机返回桌面（写完windows的返回桌面才想起来）

啊抱歉  这里没表示清楚，指的是返回虚拟机的桌面，游戏挂到后台减少资源消耗

**Comment by Manicsteiner** [comment]
https://github.com/Manicsteiner/MaaAssistantArknights/tree/feat_home
弄好了，等我现在的这个pr好了之后再开pr。
没想到模拟器里把游戏切后台真能省CPU资源。
不过windows返回桌面是段windows only的代码，等pr的时候再问怎么办吧。
已知问题：WSA能接收这个指令，也会把游戏切后台省CPU资源，表现为音乐停止，画面保留最后的图像不动。
