### ISSUE TITLE
是否需要添加lua支持以编写更复杂的作业

### ISSUE THREAD

**Issue by 0O0o0oOoO00** [MaaAssistantArknights/MaaAssistantArknights#7135]

**Comment by Constrat** [comment]
Do we need more complex jobs?🤨

**Comment by bakashigure** [comment]
来点使用场景

**Comment by 0O0o0oOoO00** [comment]
> 来点使用场景

我也没有想到太合适的场景()，只是觉得或许maa的作业应该支持一种脚本形式的作业编写以完成更加复杂的操作，或许对肉鸽和保全有帮助？

**Comment by zzyyyl** [comment]
现在的协议足够用了（

**Comment by Lancarus** [comment]
能实现xx敌人到坐标x，y进行xx动作的效果？

**Comment by zzyyyl** [comment]
> 能实现xx敌人到坐标x，y进行xx动作的效果？

...这也得 core 先支持啊（

**Comment by 0O0o0oOoO00** [comment]
> 能实现xx敌人到坐标x，y进行xx动作的效果？

本质上是把core的数据和部分操作函数暴露给作业脚本层面调用和判断
我这两天尝试去嵌入lua发现很困难（太难绷了）

**Comment by Constrat** [comment]
I don't feel there's a need for this. In prts.plus there are already some amazing jobs just with json "scripting" (it's not a scripting language I know, but we are using it that way.
Creating a new way to make copilots is heavy on the user. Some of them will try to use it and make even more crazy stuff, but for the majority it would just be overwhelming.
I'm with @zzyyyl on this. Against it.

**Comment by 0O0o0oOoO00** [comment]
> I don't feel there's a need for this. In prts.plus there are already some amazing jobs just with json "scripting" (it's not a scripting language I know, but we are using it that way. Creating a new way to make copilots is heavy on the user. Some of them will try to use it and make even more crazy stuff, but for the majority it would just be overwhelming. I'm with @zzyyyl on this. Against it.

Yeap, considering the current farme, it's very hard to add lua support. And even if added, i think only a small group of job maker would like to study lua language and maa team also need more time to maintenance this : )

**Comment by Constrat** [comment]
Yeah, we already have enough issues without it XD
