### ISSUE TITLE
希望公招3星可以添加词条偏好

### ISSUE THREAD

**Issue by 750759779** [MaaAssistantArknights/MaaAssistantArknights#7136]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如果自动公招时仅自动确认4星及以上，公招券会越积越多。而选择自动确认3星后又会导致公招券消耗过快。
由于公招时3星词条也有概率获得5星，且存在两个公招限定5星，所以我曾经手动公招时仅当出现“近卫干员”、“重装干员”、“生存”其中之一时才会确认招募3星词条，否则就等待刷新。这样不仅能更大概率招到限定5星(或想要的5星)，还能把公招券数量稳定在一定范围，更高效地利用公招券。

### 有什么好的想法？

希望能在自动确认3星选项下加个偏好条件，仅当出现某些特定词条时才自动确认3星，否则等待刷新tags

另：一些词条组合如“近战位”+“输出”也有不小的概率得到公招限定5星，如果可以的话希望能在偏好里选择组合词条

**Comment by Constrat** [comment]
1. This WON'T increase the probability of 5★. As the probabilities are already guaranteed when starting the recruit. @ABA2396 correct me if I'm wrong but iirc adding more tags won't change anything (ex: if you choose three `4★ tags`, you will the same probability of getting a `4★` even if you only choose 1 tag
2. If you choose only 3 recruits per day, it will stabilize the usage, without consuming too many of them. I can run MAA automatically 3-times a day and every time it will recruit once. This way I don't use too many recruits but can safely do the issues

**Comment by Constrat** [comment]
So if I understand: in the REMOTE CASE of a 5★ probability you want to choose which tag it comes from?
I thought you meant adding more 3★ tags to increase the probability of 4★/5★ ops

**Comment by 750759779** [comment]
> So if I understand: in the REMOTE CASE of a 5★ probability you want to choose which tag it comes from? I thought you meant adding more 3★ tags to increase the probability of 4★/5★ ops

Yes! Because it's usual to recruit hundreds of times per year, and I may use MAA for a long time in the future, I don't want to miss any opportunity to get Vulcan and Indra, who can't be recruited by other ways.

**Comment by Constrat** [comment]
Ok ok but this has been discussed like 2 years on some forums.
If you choose X,y,Z 3* tags and the game selects a 5* operator, it's not necessarily dependant on the tags so in the remote case of a 5* operator from 3* tags, if you choose guard OR NOT it won't change the roll possibility

**Comment by 750759779** [comment]
Oh...If it's independent of tags, the 3* tags are likely to be crossed out in the remote case. But in my experience, very few tags were crossed out in the remote case. Nevertheless, I kown it is indeed difficult to make statistics on this case.
In that case, there is no need for this enhancement now. 
But if possible, could MAA add a feature to recognize which operator is  recruited with different tag? And then MAA upload the data to penguin-stats.cn or others. It will be helpful to understand the mechanisms of recruit, and resolve the argument on those forums.  ( • ω • )

**Comment by Constrat** [comment]
All the recruit results are already sent. But as of today only the recruit tags are sent at the start of the recruit, not at the end.
To implement it for the end first we would need penguin-logistics to implement a new warehouse option.
It's definitely doable as we could detect the tags (crossed and not crossed) and then open the recruit and check the operator  name / rarity, but we first need penguin-logistics to make the first step.
@MistEO do you have any idea if this has been discussed before? It's planned? It's in early implementation?

**Comment by WSMTBG** [comment]
hmm...I thought you might need this？
https://prts.wiki/w/%E5%85%AC%E6%8B%9B%E8%AE%A1%E7%AE%97

**Comment by Toby-Shi-cloud** [comment]
may have been solved by #8868 ? ([v5.2.3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v5.2.3))
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/85665268/affee231-18f9-4385-b0a1-de8dc4cd599f)
