### ISSUE TITLE
基建自定义排班功能plan_index错误累加

### ISSUE THREAD

**Issue by scorpion0po** [MaaAssistantArknights/MaaAssistantArknights#7144]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

定时任务保存排班方案1，执行下次基建换班时实际使用排班方案2；
参考日志时间[2023-10-31 21:09:21.872]与[2023-11-01 00:52:52.515]部分；
两次任务之间MAA自动更新到v4.26.0；
此前10.25到10.30日均有类似问题，29日前index累加错误集中发生在1点与9点之间，这个时间段中2点有skylland定时任务，30号在定时队列中去掉了该任务，改为9点任务启动批处理的模式；
排班模板为内置243一天4换，为方便检查30日修改排班方案2名称为A+B 2组 8H，同时因为专精砾将方案中砾改为了斑点。

### 日志文件

[日志文件.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13222861/default.zip)

**Comment by Private233** [comment]
想看一眼你的排班文件

**Comment by scorpion0po** [comment]
> 想看一眼你的排班文件
[243_layout_4_times_a_day.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13223784/243_layout_4_times_a_day.json)

**Comment by ABA2396** [comment]
是说开了自定义基建+自定义定时配置吗 感觉不是很好处理，没写时间字段的话是换完一次班之后切换下一班，感觉如果要用自定义定时配置的话就得把基建配置里也写上对应的时间段了
