### ISSUE TITLE
搓玉时候基建换班卡住

### ISSUE THREAD

**Issue by pointm** [MaaAssistantArknights/MaaAssistantArknights#715]
在三个号都出现类似的问题了，应该是玉补货不足所以说卡住了。
![233](https://user-images.githubusercontent.com/49180699/171790842-2f5aceec-ac7c-4609-a5d0-183c7da5eaff.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8829689/asst.log)
是最新版的脚本

**Comment by MistEO** [comment]
v3.9.3 fixed
