### ISSUE TITLE
4.26.0版本萨米肉鸽还是会在第一关进入节点选人后自动退出

### ISSUE THREAD

**Issue by KAJIKAJIYUJI** [MaaAssistantArknights/MaaAssistantArknights#7150]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题4.26.0版本萨米肉鸽还是会在第一关进入节点选人后自动退出，使用老版本4.24.0萨米肉鸽基本正常，但有些节点会卡住，好像是脚本点太快的原因。
下载4.24.0版本后取消自动更新、自动下载也还是会下载最新版本，导致无法正常运行萨米肉鸽

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13229822/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13229823/gui.log)

### 截图

![GX_W}X0AQ%3{AN_ N)` M1N](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149611530/ebcb2b86-d7a6-4bbe-8496-92448c79031e)

**Comment by zzyyyl** [comment]
FormationConfirm 后面没有识别到 ReturnToMap
cc @Lancarus

**Comment by zzyyyl** [comment]
没有复现，需要更多信息

**Comment by zzyyyl** [comment]
考虑是不是界面有遮挡

打包上传一下 debug\roguelike 文件夹

**Comment by KAJIKAJIYUJI** [comment]
[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13240837/roguelike.zip)

**Comment by KAJIKAJIYUJI** [comment]
[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13240845/roguelike.zip)

**Comment by KAJIKAJIYUJI** [comment]
> 考虑不是界面有亮点
> 
[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13252734/roguelike.zip)
4.26.1也这样 哭了
> 压缩包上传一下debug\roguelike文件夹

**Comment by zzyyyl** [comment]
别开调试啊（

左上角的返回键会遮挡的

**Comment by KAJIKAJIYUJI** [comment]
_(:з」∠)_omg 感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月4日(周六) 中午1:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 4.26.0版本萨米肉鸽还是会在第一关进入节点选人后自动退出 (Issue #7150)




 
别开调试啊（
 
左上角的返回键会遮挡的
