### ISSUE TITLE
B服启动无法跳过

### ISSUE THREAD

**Issue by hu1m** [MaaAssistantArknights/MaaAssistantArknights#7151]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启动mumu12模拟器后再启动maa，点击link start，期间游戏弹出隐私提示无法跳过，显示动作运行失败

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13230182/asst.zip)
时间2023年11月2日01:08

### 截图

![1(GIOED%JT`WQCKB5IHM5%F](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149614705/38a6b5a5-7820-45cb-8594-d38c8c8ed3a2)

**Comment by zzyyyl** [comment]
给张模拟器720p大图

**Comment by ABA2396** [comment]
> 给张模拟器720p大图

隐私策略本来就不会去点
