### ISSUE TITLE
萨米肉鸽探寻前路节点无法正常运行

### ISSUE THREAD

**Issue by N602FE** [MaaAssistantArknights/MaaAssistantArknights#7152]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

进入探寻前路事件后会卡住不进行下一步，随后自行退出。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13230225/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13230227/gui.log)

发生于00:42:48到00:46:43

### 截图

<img width="596" alt="屏幕截图 2023-11-02 015608" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149270526/9c0f188b-2df9-4154-ab9b-206bed256c0b">

### 还有别的吗？

刚才搜了一下发现已经不是第一次出现了，之前修复的可能失效了

**Comment by zzyyyl** [comment]
打包发一下 `debug\Roguelike`

**Comment by N602FE** [comment]
![2023-11-02_00-05-28-205_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149270526/380285c3-7c8c-4e9e-a850-acfb1c1fb539)
![2023-11-02_00-11-36-347_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149270526/4f6a1654-e8a5-4ce2-bf06-8dd103a0f8f7)
![2023-11-02_00-14-44-599_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149270526/cd2f0a06-ba0e-4c67-9ca0-814ec6a19dd9)
![2023-11-02_00-32-56-609_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149270526/69e09f4c-3af3-430c-8bcd-d2613a83da25)
![2023-11-02_00-42-50-234_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149270526/a285d91f-6aa8-43ba-8acc-7024261a89f5)
![2023-11-02_00-46-04-407_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149270526/dd79f533-b173-4777-9315-5c8a443b068c)
![2023-11-02_00-46-12-940_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149270526/f5cbbcdd-5145-475f-90c3-f204c80870c3)

**Comment by zzyyyl** [comment]
没通结局.jpg

**Comment by jiangxuezhaocanlou** [comment]
我也遇到了探寻前路节点卡住不动
