### ISSUE TITLE
任务栏隐藏的MAA重复退出时报错

### ISSUE THREAD

**Issue by XiaoXKKK** [MaaAssistantArknights/MaaAssistantArknights#7154]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在任务栏隐藏的MAA退出时确认窗口有时不会在桌面顶层出现，且未操作确认窗口再次退出会有报错
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/37475561/dc03b589-0739-4b52-b559-f6699aa02849)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/37475561/54a1bec4-1121-49d7-99b3-31e5d48c68a5)

### 有什么好的想法？

再次点退出时检查下是否已经弹出了二次确认窗口

**Comment by ABA2396** [comment]
~~草，那这也是强制关闭的一种手段了罢~~
