### ISSUE TITLE
更新日志贡献者错误

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#7155]
### 说说你遇到的问题？

[v4.26.0](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v4.26.0)
`修复美服肉鸽卡在放弃行动弹窗界面的问题`
对应issue #6931 
我也妹参与这个
smjb

**Comment by Rbqwow** [comment]
remove en

**Comment by Rbqwow** [comment]
remove rougelike

**Comment by zzyyyl** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/b8a62357-b78f-41f1-8d34-6638a2ebe3c9)
@ABA2396 不要再 merge remote-tracking branch 辣！

**Comment by zzyyyl** [comment]
ChangelogGenerator 更新前，这样的 merge commit 会被理解为一个 `Merge remote-tracking branch ...` 的 PR，里面有
- `fix: 修复...` @zzyyyl
- `doc: 添加...` @Rbqwow 
- ...

然后就会把里面的作者拿到外面：）
虽然说现在更新之后不会了，但是 Merge remote-tracking branch 依然是坏行为，应该避免使用

**Comment by ABA2396** [comment]
刚装新电脑好像默认是merge，之后就改了.jpg
