### ISSUE TITLE
官服/B服新版本支持连续代理作战，希望增加使用该功能

### ISSUE THREAD

**Issue by AdiEcho** [MaaAssistantArknights/MaaAssistantArknights#7156]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

新版本中增加了连续代理作战功能，使用该功能时会跳过多次代理作战所需的点击开始行动的步骤，只结算一次。

### 有什么好的想法？

支持通过连续代理作战来节约时间

### 其他内容

![A4XON177B98}Z{ANOV`WK3D](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30563671/59036364-bef0-428c-9222-32dcdc6db903)
![_(OR89S~I5BRL5JQL_QMNQ9](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30563671/1dd72470-4d32-4e1f-801c-6eb55897f895)

**Comment by Constrat** [comment]
Have a bit of patience, this was released less than 24 hrs ago.
