### ISSUE TITLE
肉鸽开局选择干员的问题

### ISSUE THREAD

**Issue by GrainRR** [MaaAssistantArknights/MaaAssistantArknights#7157]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在使用『焰影苇草』开局时，选择“近卫，辅助，医疗”的组合时，MAA出现了不招募近卫干员的现象（这时候首选一般是『月见夜』，在已经练了月见夜的前提下依然不进行选择）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13234801/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13234803/gui.log)

问题出现在2023/11/2的凌晨

### 还有别的吗？

MUMU模拟器

**Comment by GrainRR** [comment]
事实上在选择随心所欲的时候也会出现不选干员的问题

**Comment by shendeguize** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30931540/6ac91149-dbb0-4bfa-8228-1c869fe66260)
同样的问题
版本:
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30931540/d2384fb5-55f8-4128-84d1-78fe3d4a4cb2)

目录模拟器
