### ISSUE TITLE
龙门币不足会导致自动公招无限循环

### ISSUE THREAD

**Issue by ZGLinus** [MaaAssistantArknights/MaaAssistantArknights#7159]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

龙门币不足以完成一次公招时，还导致maa自动公招无限循环，无法进入下一个步骤。MAA已是最新版本。

### 日志文件

[2023-11-02 06:18:30.388] 至 [2023-11-02 06:20:15.450]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13237716/gui.log)
[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13237727/asst.bak.zip)

**Comment by horror-proton** [comment]
实际上并不会无限循环, 不过确实重试太多次了
