### ISSUE TITLE
萨米肉鸽探寻前路无操作

### ISSUE THREAD

**Issue by datpo-channel** [MaaAssistantArknights/MaaAssistantArknights#7160]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽里进入探寻前路后无操作，手动操作后回复正常流程

### 日志文件

[file.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13237669/file.zip)
在2023-11-02 18:22:07.910进入探寻前路事件
在2023-11-02 18:22:14.239至2023-11-02 18:23:28.098区间貌似出现了很多重复的操作

**Comment by zzyyyl** [comment]
考虑是不是没通二结局

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6460#issuecomment-1730963272
