### ISSUE TITLE
`asst::ranges` 统一使用 `std::ranges`

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantArknights#7163]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/a15807ce-eb3b-41fc-8ac4-738b67e204df)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/3c8381b8-3830-4895-b6dc-0f553bc003e4)

从左到右依次为：

GCC libstdc++ | Clang libc++ | MSVC STL | Apple Clang*
-- | -- | -- | --

如图，Apple Clang 已经支持 constrained algorithms 了，但是 range adaptors 还没

也就是 `ranges::remove` 这类的已经支持了，只不过 `views::keys` 这类还不完全支持（？

**Comment by zzyyyl** [comment]
@horror-proton 带带

**Comment by horror-proton** [comment]
说起来我感觉现在的判断方法并不正确
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/60d2e11e1315cd94dae3ce3cfc9f6129a5aa7bff/src/MaaCore/Common/AsstConf.h#L4-L5
这两个带 `lib` 的特性宏好像是在标准库的头文件里面 #define 的, 而不是编译器预定义的, 所以在没有
```cpp
#if __has_include(ranges)
#include <ranges>
#endif
```
之前
并不能用来判断能否支持 ranges

**Comment by horror-proton** [comment]
因为 ranges 是标准库而不是编译器的特性, 所以如果用正确的判断方法的话之前也应该都用 std (clang 用不了那是 clang 有 bug, 应该另外判断)
但现在我也不知道是为啥能正常工作, 两个 bug 抵消了?

**Comment by zzyyyl** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7148/commits/6c90fdce0022cbdab05073685e4e4e09796bb5b6

**Comment by horror-proton** [comment]
别真的这么搞吧, 快把
```
feat: 移除 range-v3 依赖
fix: 重新使用 range-v3 的 views::keys, views::values
```
从 `fix/taskdata_back` 去掉 :crying_cat_face:

**Comment by zzyyyl** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/a15807ce-eb3b-41fc-8ac4-738b67e204df)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/3c8381b8-3830-4895-b6dc-0f553bc003e4)

从左到右依次为：

GCC libstdc++ | Clang libc++ | MSVC STL | Apple Clang*
-- | -- | -- | --

**Comment by zzyyyl** [comment]
> 别真的这么搞吧, 快把
> 
> ```
> feat: 移除 range-v3 依赖
> fix: 重新使用 range-v3 的 views::keys, views::values
> ```
> 
> 从 `fix/taskdata_back` 去掉 😿

为啥不好（

**Comment by horror-proton** [comment]
std 如果不行就用 range-v3 吧, 哪有混着用的. 就算能工作也不应该把 range-v3 支持全删了吧.
而且上面提到了这个判断方法也是错的, 之后得找个更准确的判断方法 (比如比较具体的编译器版本)
比如这个 https://godbolt.org/z/r3daqx7Ms 它会认为 clang 13 也能用 ranges, 但实际上那个编译器 bug 并没有修好

**Comment by zzyyyl** [comment]
> std 如果不行就用 range-v3 吧, 哪有混着用的. 就算能工作也不应该把 range-v3 支持全删了吧. 而且上面提到了这个判断方法也是错的, 之后得找个更准确的判断方法 (比如比较具体的编译器版本) 比如这个 https://godbolt.org/z/r3daqx7Ms 它会认为 clang 13 也能用 ranges, 但实际上那个编译器 bug 并没有修好

主要是 range-v3 有的玩意和标准库实现的不一样啊（
比如 ranges::remove 相关的几个

**Comment by horror-proton** [comment]
哦是你那个 pr 要用到的吗, 那先能跑就行. 
我还以为是无关的修改 (

**Comment by zzyyyl** [comment]
> 哦是你那个 pr 要用到的吗, 那先能跑就行. 我还以为是无关的修改 (

其实我把 ranges::remove 换成 std::remove 就行了，但是看到 std 不爽（x

**Comment by zzyyyl** [comment]
我把相关修改放到分支 feat/std_constrained_algorithms 了，那个 pr 先用 std
