### ISSUE TITLE
【公告】繁中服游戏资源无限期停更

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#7165]
由于没有新版本繁中服游戏资源的获取途径，我们无法继续对繁中服进行资源自动更新（目前定格在了 `照我以火` 版本）

在未来的版本中，繁中服 MAA 将会出现的问题包括但不限于：

- 公招识别 依然按老版本 tag 计算，可能会错误的提醒 4、5 星，也可能会漏掉新加入的 4、5 星
- 关卡掉落识别、仓库识别 不认识新出的材料（不过企鹅物流没有繁中汇报，无需担心）
- 自动战斗抄作业、自动肉鸽、干员 box 识别 不认识新出的干员
- 自动肉鸽 无法识别新关卡，不部署摆烂；肉鸽商店新道具 不会购买

若您有游戏数据获取的能力，欢迎向我们提供新版本的繁中服资源获取方式！
若您有耐心手动更新这些文件，也欢迎向我们提出 PR 更新它们！[公招数据](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/global/txwy/resource/recruitment.json) [材料数据](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/global/txwy/resource/item_index.json) [干员数据 1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/battle_data.json) [干员数据 2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/global/txwy/resource/tasks.json#L304) [肉鸽关卡名数据](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/global/txwy/resource/tasks.json#L1751) [肉鸽道具数据](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/global/txwy/resource/tasks.json#L2603) 
非常感谢！

相关讨论：https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/7074 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7079

**Comment by Tsuk1ko** [comment]
已邮件联系

**Comment by Constrat** [comment]
I forgot to close this one.
