### ISSUE TITLE
WindowsDefender 报毒

### ISSUE THREAD

**Issue by TacitR** [MaaAssistantArknights/MaaAssistantArknights#7169]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Detected:Trojan:Script/Wacatac.B!ml
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/48092314/653bed13-8761-43ea-994b-f150b040eee7)

### 日志文件

无

### 还有别的吗？

Windows10
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/48092314/324726ce-edd5-4e30-9909-391022b7985f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/48092314/1dc22eb8-0235-46a1-96f4-57f852fd1f6a)

**Comment by status102** [comment]
Duplicate of #6662
