### ISSUE TITLE
312更新到392用不了

### ISSUE THREAD

**Issue by davis515sa3** [MaaAssistantArknights/MaaAssistantArknights#717]
！！！请尽可能详细的描述你遇到的问题，并附上助手软件目录下的 `asst.log` 日志文件！！！
本来用的雷神，312版本，然后更新一下就一直启动不了，一直卡者，abd路径也没问题，因为能用之后就没动过。
现在是换了夜神模拟器（以下log也是夜神的，雷神的那会删掉了，软件也重新下了）
雷神那会的问题是分辨率拉满了，软件也会提示分辨率过低。
夜神目前是只会显示”连接失败，请检查连接设置“
！！！日志文件是可以直接拖拽进来的，没有日志文件的 bug 反馈我们会直接关掉！！！
[asst.log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8837419/asst.log)
](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8830663/asst.log)

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_
![1O G8)2~I@UE{6LUSV%LJL1](https://user-images.githubusercontent.com/72510392/171814103-1317cc41-f021-473e-b303-db7b7bfb5b8b.png)
![0IF_BL5@ZQ5PPHCT%EC3F2W](https://user-images.githubusercontent.com/72510392/171814110-73fccaee-908f-4654-8a27-8512d452c978.png)

Thanks♪(･ω･)ﾉ

**Comment by davis515sa3** [comment]
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Friday, Jun 3, 2022 4:09 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 312更新到392用不了 (Issue #717)





 
看你的日志全是 v3.1.2 的，没有新版本 v3.9.2 的日志。重发下看看？

**Comment by YUehai231** [comment]
我好像也有出现类似的问题，使用的是蓝叠模拟器
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8837395/asst.log)

**Comment by davis515sa3** [comment]
> 看你的日志全是 `v3.1.2` 的，没有新版本 `v3.9.2` 的日志。重发下看看？
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8837403/asst.log)

**Comment by YUehai231** [comment]
但这个确实是我删除原本的文件之后，今天早上重新下载解压产生的日志。稍等，我一会再去进行一次尝试。

**Comment by YUehai231** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8840050/asst.log)
我c重新下载安装了

**Comment by davis515sa3** [comment]
> [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8840050/asst.log)
> 我c重新下载安装了

我不会看log信息，你是不是回复错了( •̥́ ˍ •̀ू )

**Comment by MistEO** [comment]
重新下载新版本试下吧 ✿✿ヽ(°▽°)ノ✿
