### ISSUE TITLE
需求建议：增加在关卡开始前的连续代理次数的识别和自动切换功能

### ISSUE THREAD

**Issue by Yingge02** [MaaAssistantArknights/MaaAssistantArknights#7170]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在更新至最新版本后，虽然可以识别到连续代理的次数，但是在第一次连续代理次数较高但理智不够时会卡在使用理智药的界面直至报错（如设置连续代理ZT-8关卡6次，共计126理智，但此时只有120理智）。

### 有什么好的想法？

增加关卡开始前的连续代理次数识别和调整。
当进行连续代理时，如果可直接进入关卡，则正常代理作战。如果理智不足，触发“使用理智药”界面时（并未在MAA勾选“吃理智药”选项），返回并打开代理次数设置，识别能够进行代理且不使用理智药的最高连续代理次数，设置对应次数后继续代理。

### 其他内容

ZT-8举例：
![26AB9AD4B55ABD7C6AE1E9502E8E42BE](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76812811/ed5e42c5-5b25-49ea-8af1-bd341e29e9d9)
![9E3441BA448D8B0255E025DF36FE39D3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76812811/4dad9a2e-b0a9-4906-ad88-50b511b5ec69)
![C8AA97741F5563D019DAF4F0E37ADADD](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76812811/be9bb6fa-9b72-45af-919f-b57e1b6ebdd9)
![345510033B6A6670B56516C87ECE7652](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76812811/89743845-1141-4144-beee-ad7397867d61)

**Comment by status102** [comment]
duplicate of #7156
