### ISSUE TITLE
分辨率变化导致 账号切换-B服 出错

### ISSUE THREAD

**Issue by aaaaaaaaaaaaa223123** [MaaAssistantArknights/MaaAssistantArknights#7171]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

开始唤醒菜单，使用B服进行账号切换时，在4.26.1稳定版会导致“任务出错”。
maa退出原账号登陆后，没有点击下拉按钮，等待后出现报错

查看asst.log日志，发现账号切换时，会访问“/global/txwy/resource/version.json”文件。

访问该文件，发现接口报错，报错信息为“版本不支持”。

检查该文件，发现版本文件未随着版本更新，建议更新该json文件
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110537237/2e6e0f1c-65f0-429c-8656-6727be39e708)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13246180/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13246182/gui.log)
最后一项的报错，拉到底部就可以看到。

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110537237/0df25c65-56e0-448c-8ef8-921d10b0ebdd)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110537237/b04ecb32-4d95-4e66-ab4c-a6f22562b34d)

**Comment by zzyyyl** [comment]
跟txwy的version没关系，你又不是台服（

**Comment by Constrat** [comment]
Why txwy mentioned lol?

**Comment by status102** [comment]
看看任务出错时候模拟器画面是咋样的

**Comment by aaaaaaaaaaaaa223123** [comment]
> 看看任务出错时候模拟器画面是咋样的
模拟器卡在这个页面
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110537237/72e4213b-b105-4f05-b060-74e82b10986a)

**Comment by status102** [comment]
看上去B站这个窗口调整了一下缩放比例，晚点重新做一下适配
方便的话，麻烦截一张展开了账号列表的图片

**Comment by aaaaaaaaaaaaa223123** [comment]
> 看上去B站这个窗口调整了一下缩放比例，晚点重新做一下适配 方便的话，麻烦截一张展开了账号列表的图片

这是展开账号列表的图片
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110537237/4bc83298-f0cd-49da-8b27-ed8b18d1af52)
fe

非常感谢解答

**Comment by status102** [comment]
> > 看看任务出错时候模拟器画面是咋样的
> > 模拟器卡在这个页面
> > ![image](https://user-images.githubusercontent.com/110537237/280454443-72e4213b-b105-4f05-b060-74e82b10986a.png)

刚看到你的模拟器分辨率为1600*900，还要麻烦你调到1280*720截一张这个页面的了，谢谢

**Comment by aaaaaaaaaaaaa223123** [comment]
> > 模拟器卡在这个页面
> > ![image](https://user-images.githubusercontent.com/110537237/280454443-72e4213b-b105-4f05-b060-74e82b10986a.png)
> 
> 刚看到你的模拟器分辨率为1600x900，还要麻烦你调到1280x720截一张这个页面的了，谢谢
好的，没问题。以下的1280*720的页面截图（通过MUMU模拟器进行截图）。
![MuMu12-20231104-165228](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110537237/2a14b016-fbb3-4078-a019-35920fd80ae9)

**Comment by Constrat** [comment]
@status102 Seems like it's somehow DPI bound. Like what happens in YostarEN with the texts

**Comment by ABA2396** [comment]
> 看上去B站这个窗口调整了一下缩放比例，晚点重新做一下适配
> 方便的话，麻烦截一张展开了账号列表的图片

不是，不同的分辨率b站这个框大小不一样）

**Comment by ABA2396** [comment]
这个原来是咋处理的来着

**Comment by status102** [comment]
> 这个原来是咋处理的来着

直接识别bilibili游戏那个logo然后走插件逻辑，这里只是判一个logo，确定是哪版客户端，然后走对应的账户列表匹配

**Comment by aaaaaaaaaaaaa223123** [comment]
我有个想法，能不能识别logo后，记录logo的坐标，向下移动X个像素或者X%，模拟点击打开列表？

**Comment by status102** [comment]
> 我有个想法，能不能识别logo后，记录logo的坐标，向下移动X个像素或者X%，模拟点击打开列表？

打开列表不是问题，比较有问题的是后半部分

**Comment by zzyyyl** [comment]
不同分辨率、dpi 的 logo 大小都不一样（

**Comment by status102** [comment]
> 不同分辨率、dpi 的 logo 大小都不一样（
> 
> 是不是在 “识别logo” 这一步就出问题了

对，卡这了

**Comment by ABA2396** [comment]
> > 不同分辨率、dpi 的 logo 大小都不一样（
> > 是不是在 “识别logo” 这一步就出问题了
> 
> 对，卡这了

识别"bilibili 游戏"的那个"游戏"）

**Comment by status102** [comment]
> 识别"bilibili 游戏"的那个"游戏"）

判bilibili吧，晚点有空修修，还要看看底下账号列表可能有要修正的roi

**Comment by zzyyyl** [comment]
> > 识别"bilibili 游戏"的那个"游戏"）
> 
> 判bilibili吧，晚点有空修修，还要看看底下账号列表可能有要修正的roi

打算用 MatchTemplate 还是 OCR ？ 我怎么觉得两个都不太行

**Comment by status102** [comment]
> 打算用 MatchTemplate 还是 OCR ？ 我怎么觉得两个都不太行

现在先match，匹配到每一行后加偏移ocr

**Comment by ABA2396** [comment]
> > 打算用 MatchTemplate 还是 OCR ？ 我怎么觉得两个都不太行
> 
> 现在先match，匹配到每一行后加偏移ocr

来个官服的图看看，我感觉总有些可以ocr的地方吧？

**Comment by status102** [comment]
> 来个官服的图看看，我感觉总有些可以ocr的地方吧？

这种能特征吗，fw那边有特征（比划
ocr估计就上次登录了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/943d31f2-a971-4b9c-a737-ef2708961434)

**Comment by status102** [comment]
看了下Official似乎不会因为分辨率变化而改变，是直接放大的

**Comment by ABA2396** [comment]
“切换“其他账号和“登录”其他账号）

**Comment by status102** [comment]
> “切换“其他账号和“登录”其他账号）

Too magic and may be invalid anytime

**Comment by ABA2396** [comment]
但是模板匹配现在还不能处理缩放的情况吧

**Comment by status102** [comment]
> 但是模板匹配现在还不能处理缩放的情况吧

Ocr bilibili 和 鹰角

**Comment by zzyyyl** [comment]
我觉得bilibili是OCR不出来的.jpg

**Comment by status102** [comment]
我傻逼了，为啥要匹配这个，让Gui传个版本过来不就ok
选官方就用官服的走，选B服就用B服的走

**Comment by BiologyHazard** [comment]
这个界面的大小不是固定的而是跟着模拟器dpi变的

**Comment by siuze** [comment]
有任何进展吗？我在切换账号时也出现该问题了，或者说1280X720下应该用多大的DPI才标准？

**Comment by ABA2396** [comment]
> 有任何进展吗？我在切换账号时也出现该问题了，或者说1280X720下应该用多大的DPI才标准？

好像是说准备之后再多传一个客户端类型，得等5.x之后重构了

**Comment by siuze** [comment]
> > 有任何进展吗？我在切换账号时也出现该问题了，或者说1280X720下应该用多大的DPI才标准？
> 
> 好像是说准备之后再多传一个客户端类型，得等5.x之后重构了

我修改task让他跳过服务器识别这个步骤后，又卡在识别已登录账号列表的右侧垃圾桶这个步骤上了，一直报 `select_account unable to match trash button in account list`

**Comment by status102** [comment]
> 有任何进展吗？我在切换账号时也出现该问题了，1280X720 DPI320

那试试240? 因为一开始素材用的别人给的（我也不知道dpi多少

**Comment by status102** [comment]
会卡的，b/官服从roi到各种偏移都不一样，dpi不一样就寄。

**Comment by siuze** [comment]
怎么调DPI都不行，然后把自己的截图裁剪一下替换官方的模板就好了TAT

**Comment by aaaaaaaaaaaaa223123** [comment]
能不能用ocr识别svg格式的图片进行判断？

比如说，b服的logo是
![biligame-logo-w200 e54786d](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110537237/6edb3d65-b57a-4836-a71b-30fdaeff518f)

如果这个能帮到的话，我可以帮忙找一下官b的各种图。垃圾桶这类的

**Comment by status102** [comment]
Logo现在已经没有问题了，问题是现在还没有办法处理垃圾桶的缩放

**Comment by aaaaaaaaaaaaa223123** [comment]
> Logo现在已经没有问题了，问题是现在还没有办法处理垃圾桶的缩放

我看了一下，垃圾桶的失败是png格式的位图，如果换成矢量图呢？比如说svg的格式，svg缩放不会失真，不知道可不可以，如果可以用svg进行ocr识别，我可以帮忙找垃圾桶的svg矢量图

（一点开发的思路）
