### ISSUE TITLE
肉鸽凹精二干员功能建议将开局干员和刷精二干员分开

### ISSUE THREAD

**Issue by newyyyy** [MaaAssistantArknights/MaaAssistantArknights#7174]
### 说说你遇到的问题？

凹精二干员只有在使用烧开水策略才会出现，但烧开水又会把难度播到0难，导致无法正常使用

**Comment by zzyyyl** [comment]
凹精二是指，烧水的同时凹到精二就停

**Comment by newyyyy** [comment]
> 凹精二是指，烧水的同时凹到精二就停
> 
> 也就是烧水高难开的时候才会凹，0难没影响的

比如说我想凹精二薇薇安娜开局，但是薇薇安娜并不能烧开水，如果我仅勾选凹精二开局的话可能烧完开水他会凹到存在随机精二六星后停止。但选择开局干员为薇薇安娜后，即使是0难也烧不了开水。 起初我以为该功能是省去手动刷直升六星的功能，但目前仅能在该干员能烧开水后附加使用，所以我认为该功能存在些许问题

**Comment by zzyyyl** [comment]
薇薇安娜为什么不能烧水！

**Comment by newyyyy** [comment]
> 薇薇安娜为什么不能烧水！

打不过，首先得选近锋队，然后她是挡1！开局是奶和梓兰，第一层的几关无外援的情况不对轴都会漏，第二层也是漏成筛子，探索个七八次都没办法用maa到第三层

**Comment by ABA2396** [comment]
那这样的话就算烧出来能用吗（）

**Comment by zzyyyl** [comment]
总之是希望增加功能：使用的干员和指定的精二可以设置不同的干员

**Comment by Lancarus** [comment]
> 总之是希望增加功能 `开局` 和 `凹精二` 可以设置不同的干员，对吧
> 
> cc @Lancarus

我没这需求。。。等哪个佬有这个需求就自己实现吧（）

**Comment by SherkeyXD** [comment]
看起来不算太难实现 但是懒得写（
