### ISSUE TITLE
掉落识别错误

### ISSUE THREAD

**Issue by 30000lightyears** [MaaAssistantArknights/MaaAssistantArknights#7176]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新4.26.1后使用连续代理作战，仍然出现掉落识别错误的情况

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13246860/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13246861/gui.log)
问题出现时间点：11-03 13:09:54

### 截图

<img width="595" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66123770/7adfffd0-3412-4f2f-ab48-3329c900be94">
![2023-11-03_13-09-54-267_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66123770/cffac49a-df4a-42c0-b1af-67533d6244be)

### 还有别的吗？

模拟器：mumu12
操作系统：Windows 11 23H2 Build 22631.2506

**Comment by 30000lightyears** [comment]
![2023-11-03_13-09-54-267_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66123770/038ed0dd-c833-46f4-81fc-c8177cbe6c68)

**Comment by 30000lightyears** [comment]
后面识别一次成功了，应该是偶发事件

**Comment by 30000lightyears** [comment]
不过当前次数统计好像还是有点问题……
<img width="201" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66123770/4e5b62a7-6512-4d17-abce-30567c89d017">

**Comment by ABA2396** [comment]
5*6=30次）

**Comment by ABA2396** [comment]
掉落的材料种类太多了，还没完全展示的时候就去判断就识别错误了
