### ISSUE TITLE
Qodana 相关代码分析处于不可用状态

### ISSUE THREAD

**Issue by hxdnshx** [MaaAssistantArknights/MaaAssistantArknights#7177]
### 说说你遇到的问题？

https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6675

关于相关问题的进展之后更新在这里。

**Comment by SherkeyXD** [comment]
好消息 2023.3 EAP 要来了

**Comment by hxdnshx** [comment]
他说这周.png

**Comment by SherkeyXD** [comment]
似乎又炸了（
正常的测试能跑 但是会多出来1w6个奇怪的报错

qodana 在干嘛啊（

# [Qodana](https://qodana.cloud/projects/3P0oy/reports/DrDXd) for .NET

**16035 new problems** were found

| Inspection name | Severity | Problems |
| --- | --- | --- |
| `Unexpected text token error` | 🔴 Failure | 14993 |
| `XML highlighting` | 🔴 Failure | 32 |
| `Unresolved file reference` | 🔴 Failure | 3 |
| `Redundant using directive` | 🔶 Warning | 386 |
| `Redundant argument with default value` | 🔶 Warning | 98 |
| `Unknown property` | 🔶 Warning | 59 |
| `Method return value is never used (private accessibility)` | 🔶 Warning | 57 |
| `Invalid XML documentation comment` | 🔶 Warning | 26 |
| `Possible 'System.NullReferenceException'` | 🔶 Warning | 19 |
| `The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.` | 🔶 Warning | 18 |
| `Async method invocation without await expression` | 🔶 Warning | 17 |
| `Auto-property accessor is never used (non-private accessibility)` | 🔶 Warning | 13 |
| `Usage of <inheritdoc /> is invalid` | 🔶 Warning | 10 |
| `Conditional access qualifier expression is known to be null or not null` | 🔶 Warning | 5 |
| `Rider toolset and environment errors` | 🔶 Warning | 5 |
| `Access to modified captured variable` | 🔶 Warning | 4 |
| `Bitwise operation on enum is not marked by [Flags] attribute` | 🔶 Warning | 4 |
| `Code is unreachable` | 🔶 Warning | 4 |
| `Type member is never used (private accessibility)` | 🔶 Warning | 2 |
| `Deprecated property` | 🔶 Warning | 1 |
| `No matching files` | 🔶 Warning | 1 |
| `Redundant type declaration body` | 🔶 Warning | 1 |
| `Local function return value is never used` | 🔶 Warning | 1 |
| `Unused local variable` | 🔶 Warning | 1 |
| `Unused schema declaration` | 🔶 Warning | 1 |
| `Use preferred namespace body style` | ◽️ Notice | 74 |
| `Method return value is never used (non-private accessibility)` | ◽️ Notice | 74 |
| `Type member is never used (non-private accessibility)` | ◽️ Notice | 45 |
| `Member can be made private (non-private accessibility)` | ◽️ Notice | 16 |
| `RoslynAnalyzers Mark members as static` | ◽️ Notice | 12 |
| `Non-accessed field (non-private accessibility)` | ◽️ Notice | 11 |
| `RoslynAnalyzers Non-constant fields should not be visible` | ◽️ Notice | 10 |
| `Some values of the enum are not processed inside 'switch' statement and are handled via default section` | ◽️ Notice | 9 |
| `Use preferred style of 'new' expression when created type is evident` | ◽️ Notice | 5 |
| `Type is never used (non-private accessibility)` | ◽️ Notice | 5 |
| `Convert constructor into primary constructor` | ◽️ Notice | 3 |
| `Inline temporary variable` | ◽️ Notice | 3 |
| `Overlapping sections` | ◽️ Notice | 2 |
| `Unused parameter (non-private accessibility)` | ◽️ Notice | 2 |
| `RoslynAnalyzers Do not assign a property to itself` | ◽️ Notice | 1 |
| `Event is never subscribed to (non-private accessibility)` | ◽️ Notice | 1 |
| `Some values of the enum are not processed inside 'switch' statement` | ◽️ Notice | 1 |



☁️ [View the detailed Qodana report](https://qodana.cloud/projects/3P0oy/reports/DrDXd)

<details>
<summary>Contact Qodana team</summary>

Contact us at [qodana-support@jetbrains.com](mailto:qodana-support@jetbrains.com)
  - Or via our issue tracker: https://jb.gg/qodana-issue
  - Or share your feedback: https://jb.gg/qodana-discussions
</details>


_Originally posted by @github-actions in https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7554#issuecomment-1854967956_

**Comment by hxdnshx** [comment]
> 似乎又炸了（ 正常的测试能跑 但是会多出来1w6个奇怪的报错
> 
> qodana 在干嘛啊（
> 
> # [Qodana](https://qodana.cloud/projects/3P0oy/reports/DrDXd) for .NET
> **16035 new problems** were found
> 
> Inspection name	Severity	Problems
> `Unexpected text token error`	🔴 Failure	14993
> `XML highlighting`	🔴 Failure	32
> `Unresolved file reference`	🔴 Failure	3
> `Redundant using directive`	🔶 Warning	386
> `Redundant argument with default value`	🔶 Warning	98
> `Unknown property`	🔶 Warning	59
> `Method return value is never used (private accessibility)`	🔶 Warning	57
> `Invalid XML documentation comment`	🔶 Warning	26
> `Possible 'System.NullReferenceException'`	🔶 Warning	19
> `The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.`	🔶 Warning	18
> `Async method invocation without await expression`	🔶 Warning	17
> `Auto-property accessor is never used (non-private accessibility)`	🔶 Warning	13
> `Usage of <inheritdoc /> is invalid`	🔶 Warning	10
> `Conditional access qualifier expression is known to be null or not null`	🔶 Warning	5
> `Rider toolset and environment errors`	🔶 Warning	5
> `Access to modified captured variable`	🔶 Warning	4
> `Bitwise operation on enum is not marked by [Flags] attribute`	🔶 Warning	4
> `Code is unreachable`	🔶 Warning	4
> `Type member is never used (private accessibility)`	🔶 Warning	2
> `Deprecated property`	🔶 Warning	1
> `No matching files`	🔶 Warning	1
> `Redundant type declaration body`	🔶 Warning	1
> `Local function return value is never used`	🔶 Warning	1
> `Unused local variable`	🔶 Warning	1
> `Unused schema declaration`	🔶 Warning	1
> `Use preferred namespace body style`	◽️ Notice	74
> `Method return value is never used (non-private accessibility)`	◽️ Notice	74
> `Type member is never used (non-private accessibility)`	◽️ Notice	45
> `Member can be made private (non-private accessibility)`	◽️ Notice	16
> `RoslynAnalyzers Mark members as static`	◽️ Notice	12
> `Non-accessed field (non-private accessibility)`	◽️ Notice	11
> `RoslynAnalyzers Non-constant fields should not be visible`	◽️ Notice	10
> `Some values of the enum are not processed inside 'switch' statement and are handled via default section`	◽️ Notice	9
> `Use preferred style of 'new' expression when created type is evident`	◽️ Notice	5
> `Type is never used (non-private accessibility)`	◽️ Notice	5
> `Convert constructor into primary constructor`	◽️ Notice	3
> `Inline temporary variable`	◽️ Notice	3
> `Overlapping sections`	◽️ Notice	2
> `Unused parameter (non-private accessibility)`	◽️ Notice	2
> `RoslynAnalyzers Do not assign a property to itself`	◽️ Notice	1
> `Event is never subscribed to (non-private accessibility)`	◽️ Notice	1
> `Some values of the enum are not processed inside 'switch' statement`	◽️ Notice	1
> ☁️ [View the detailed Qodana report](https://qodana.cloud/projects/3P0oy/reports/DrDXd)
> 
> Contact Qodana team
> _Originally posted by @github-actions in [#7554 (comment)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7554#issuecomment-1854967956)_

盲猜是 baseline不向前兼容，于是就出问题了，我今天根据main分支重新定一下baseline看看
