### ISSUE TITLE
启动脚本后libpng warning: sBIT: invalid

### ISSUE THREAD

**Issue by 201802330205** [MaaAssistantArknights/MaaAssistantArknights#7178]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

只要Updater(path, Version.Stable).update()升级版本就会报内存问题double free or corruption (!prev)。注释掉版本升级这句就能成功连接了但没有任何反应还会报libpng warning: sBIT: invalid这个问题，我把其他都注释完了就留了一个fightTask依然没有任何反应报libpng warning: sBIT: invalid这个问题。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13247874/asst.log)

### 截图

![2023-10-31_20-48-38-304_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/81202976-c3ce-4fca-a20b-360451f05574)
![2023-10-31_20-58-52-996_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/d35e01a6-c5d5-4454-84c7-a6a220ae983f)
![2023-10-31_20-49-01-947_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/8c535ed9-42cb-4c51-9ad1-1d0c5408e7eb)
![2023-10-31_21-20-23-237_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/c13e91f1-6280-442d-b41f-4f9233f09b93)
![2023-10-31_20-59-17-542_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/029053f8-2078-43e2-8978-6d3b9b2d4cc2)
![2023-10-31_21-20-45-456_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/12fa1027-be5e-4fde-b25b-77b6a439e6dd)
![2023-10-31_22-06-02-927_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/d8997616-50bd-411f-90cf-3ac130f9a8d2)
![2023-10-31_22-06-40-934_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/278720ed-6977-466b-9ea2-0037868fb33b)
![2023-11-01_06-56-21-283_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/cd28a52f-598c-489c-befe-ba88570445a0)
![2023-11-01_06-56-48-702_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/442f218b-33db-46ac-aca6-68c09134195c)
![2023-11-03_13-41-31-149_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/fb37986c-c26d-46a5-86ed-f6de53b46730)
![2023-11-03_13-45-59-841_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/7b030873-445c-4b94-8d83-89a53dde7d13)
![2023-11-03_13-45-35-576_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/397a24f2-aff3-4a4c-bf4b-5f6ff160c336)
![2023-11-03_14-14-54-349_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/d9db4f9b-bd42-4fdf-b2c5-15882a9b52b6)
![2023-11-03_14-14-30-155_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/69d9e8ab-9326-4895-80cb-7c4f18179300)
![2023-11-03_15-02-15-156_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/dc26bc39-4be3-4f53-a108-36cfc5ef8fd6)
![2023-11-03_15-01-50-910_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/18caba7b-e566-41a3-a351-57c227d7f5b8)
![2023-11-03_15-35-31-210_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/992ed8e4-4b22-4adc-a7a5-ca60e77063ae)
![2023-11-03_15-35-07-970_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/f1beb98d-b4b2-46bc-bc55-684786444ca9)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59409465/29a2b8fd-7284-4b1a-b7f0-0166e4311e84)

### 还有别的吗？

waydroid容器
Linux Mint 21系统
基于 [Ubuntu] 22.04 LTS
xfce桌面
1366×768显示器
容器1280×720分辨率
RGBA色彩空间
libpng warning: sBIT: invalid可能与图像格式或色彩空间相关

**Comment by horror-proton** [comment]
不用理睬 libpng 的警告, 根据日志 MAA 在正常工作但是有东西没有识别到, 你应该尝试切换回默认的界面主题或者更新 MAA

**Comment by Cryolitia** [comment]
我使用waydroid同样出现了这个报错，不影响使用

**Comment by 201802330205** [comment]
> 不用理睬 libpng 的警告, 根据日志 MAA 在正常工作但是有东西没有识别到, 你应该尝试切换回默认的界面主题或者更新 MAA

谢谢换回默认的界面主题问题已经解决
