### ISSUE TITLE
最小化到系统托盘后不定时闪退

### ISSUE THREAD

**Issue by AshdoII** [MaaAssistantArknights/MaaAssistantArknights#7183]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在最小化到系统托盘后maa任会继续运行一小会，并在我不知情的情况下闪退（一般模拟器此时 处于最小化状态）。当我点开系统托盘的时候会很短暂地显示一小下maa图标，然后消失。有时可以正常运行有时不可以，完全看运气。一般模拟器停在替换基建干员的位置。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13250452/asst.log)
[Uploading gui.log…]()

### 截图

![Screenshot_2023 11 03_21 06 49 448](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111554896/4ef84bd1-79f0-444d-9078-1c9abda33dd4)
这是最近一次模拟器停在的位置。

**Comment by AshdoII** [comment]
![Screenshot_2023 11 03_21 06 49 448](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111554896/aea8d629-4fea-4c37-8311-28d5eeb0f317)
这是未上传成功的截图。

**Comment by Constrat** [comment]
GUI.log as not been uploaded.
Not the screenshot

**Comment by AshdoII** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13255824/gui.log)

**Comment by ABA2396** [comment]
看日志没啥信息，就是在模板匹配的时候突然闪退了，现在还有这个问题吗？ ~~感觉像是内存不够了被windows杀了之类的问题~~
