### ISSUE TITLE
刷理智功能一次吃2个理智药

### ISSUE THREAD

**Issue by Meipuluu** [MaaAssistantArknights/MaaAssistantArknights#7187]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

2023-11-03 15:13:34.502
使用自动吃理智药功能，MAA连续吃了两个理智药。
该问题为偶发，但是近两日发生过3次。
模拟器：MUMU 12
MAA版本 v4.26.1

### 日志文件

[日志.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13254451/default.txt)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13254452/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149436637/60c21f51-c0cf-4cc6-8261-1e8f9989b95a)

**Comment by status102** [comment]
模拟器平时用起来会有卡顿现象么
