### ISSUE TITLE
MAA在游戏退到后台后继续点击（缺乏后台检测）

### ISSUE THREAD

**Issue by pingplug** [MaaAssistantArknights/MaaAssistantArknights#7188]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

昨晚睡前挂肉鸽，在第二天发现并未结束关机，且发现界面处于一个未知游戏的登录界面。退回桌面时，发现模拟器内已经安装数十款游戏（并消耗100G网络流量）。进入肉鸽后发现进入的是关卡结算界面，说明不是在关卡中闪退（闪退应该是直接肉鸽失败）。可能是游戏在特殊情况下（情况未知，似乎是重连ADB并重启游戏时）进入了后台，而maa没有发现，导致点击了模拟器的游戏推荐，从而连续安装了多款游戏。

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13255571/debug.zip)

似乎gui.log丢了，问题在3:44分附近自然之怒关卡那里。

### 还有别的吗？

系统：Windows 11
因为核显A卡兼容性的问题，模拟器用的是夜神。
希望增加一个识别到游戏外内容后直接停止任务的功能，或者能否发现游戏不在前台？

**Comment by Manicsteiner** [comment]
[2023-11-04 03:43:59.694][TRC][Px108][Tx1978] asst::WordOcr [{ 围内广招贤士中,无论资历: [ 4, 58, 288, 21 ], score: 0.992629 }] by OCR Pipeline , cost 49 ms
鉴定为模拟器弹窗广告

**Comment by pingplug** [comment]
> [2023-11-04 03:43:59.694][TRC][Px108][Tx1978] asst::WordOcr [{ 围内广招贤士中,无论资历: [ 4, 58, 288, 21 ], score: 0.992629 }] by OCR Pipeline , cost 49 ms 鉴定为模拟器弹窗广告

有没有推荐的无兼容性问题的模拟器。。。

**Comment by zzyyyl** [comment]
> [2023-11-04 03:43:59.694][TRC][Px108][Tx1978] asst::WordOcr [{ 围内广招贤士中,无论资历: [ 4, 58, 288, 21 ], score: 0.992629 }] by OCR Pipeline , cost 49 ms 鉴定为模拟器弹窗广告

这句话我记得是游戏内的加载画面啊，好像是 "罗德岛......广招贤士中，无论资历"

**Comment by zzyyyl** [comment]
> 识别到游戏外内容后直接停止任务

我觉得 maa 很难做到分辨哪个是游戏内容哪个不是吧（

而且由于 JustReturn 任务（不做任何识别直接点击）的存在，基本上是不可能避免这种情况的

**Comment by Manicsteiner** [comment]
> > [2023-11-04 03:43:59.694][TRC][Px108][Tx1978] asst::WordOcr [{ 围内广招贤士中,无论资历: [ 4, 58, 288, 21 ], score: 0.992629 }] by OCR Pipeline , cost 49 ms 鉴定为模拟器弹窗广告
> 
> 这句话我记得是游戏内的加载画面啊，好像是 "罗德岛——注册医药研发公司；在各国范围内广招贤士中，无论资历。"
> 
> ref: [PRTS贴士一览](https://prts.wiki/w/%E8%B4%B4%E5%A3%AB%E4%B8%80%E8%A7%88#%E9%80%9A%E5%B8%B8)

那就是再往下 03:44:10 开始的 “游戏中心” “试试大仙侠”，总之是这么个问题

**Comment by Manicsteiner** [comment]
> 有没有推荐的无兼容性问题的模拟器。。。

我以前被模拟器弹窗整烦了之后就只用AVD了。兼容问题我手里没有AMD的设备，不清楚什么情况。如果不方便换模拟器的话可以试试进安卓设置-应用，显示系统应用，找到名称带AD、Game之类可能是广告程序的能删就删，不能删就冻结，启动器、应用商店都换掉，大概能让模拟器内清净一段时间。

**Comment by pingplug** [comment]
> > > [2023-11-04 03:43:59.694][TRC][Px108][Tx1978] asst::WordOcr [{ 围内广招贤士中,无论资历: [ 4, 58, 288, 21 ], score: 0.992629 }] by OCR Pipeline , cost 49 ms 鉴定为模拟器弹窗广告
> > 
> > 
> > 这句话我记得是游戏内的加载画面啊，好像是 "罗德岛——注册医药研发公司；在各国范围内广招贤士中，无论资历。"
> > ref: [PRTS贴士一览](https://prts.wiki/w/%E8%B4%B4%E5%A3%AB%E4%B8%80%E8%A7%88#%E9%80%9A%E5%B8%B8)
> 
> 那就是再往下 03:44:10 开始的 “游戏中心” “试试大仙侠”，总之是这么个问题

游戏中心是模拟器自带的应用，桌面底部有一排推荐游戏，应该是游戏进后台了。

**Comment by pingplug** [comment]
所以是什么操作让游戏进后台，导致MAA点到桌面推荐游戏？

**Comment by ABA2396** [comment]
之前mumu是因为“后台保活”功能导致maa获取到的图片和实际点击的桌面不同，夜神最近有更新什么类似的功能吗

**Comment by KJH-x** [comment]
同问，遇到不是第一次了，都是在挂(不)完肉鸽后发生的
猜测1：粥卡死退出，猜测2：粥被意外切换到后台：
<img width="640" alt="截图_20240103012635" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/53437291/a1ad1dba-9b26-4e92-b549-f51f855512b7">

通过防火墙出站规则阻止了癌症扩散：
对`NoxVMHandle.exe`(通过分析软件可以发现所有模拟器出口流量都从此转发)添加了以下出站tcp阻止，此举验证当下有效（如图Nox仍能加载广告app被点击但是无法开始下载），但是可能会因为CDN变更/服务器IP变化需要更新：
```
116.136.239.29
123.57.212.121
221.194.181.201
47.94.211.254
```

由于MAA与Nox配置了全自动（到点由脚本启动Nox与MAA，由MAA定时任务开始执行，以下截取日志均在无人值守，不知道具体屏幕活动），观察asst.log可以发现重复执行了大量识别操作（3小时22万行）在vscode minimap中很容易发现有大量大段几乎一样的log，而gui.log鲜有报告（四小时20行），欢迎讨论

截取时间段：
asst:`2024-01-02 19:24:52.569 ~ 2024-01-02 22:35:49.711`
gui:`2024-01-02 19:23:51.735 ~ 2024-01-02 23:54:37.012`
[report.24.01.02.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13812515/report.24.01.02.zip)

欢迎要求更多日志内容

**Comment by ntgmc** [comment]
实际上我在 #2893 就提出过该问题
