### ISSUE TITLE
[EN][Mac]更新4.26后自动刷理智有问题

### ISSUE THREAD

**Issue by a4840639** [MaaAssistantArknights/MaaAssistantArknights#7192]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

4.25的时候刷理智是有一些问题，不支持11图（12图刚开我想就更不行），自动吃过期药也不工作
但是让他直接刷上次刷的图还是能工作的

更新了4.26以后理智基本上刷个一两把以后就会失败进到下一步

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13255775/asst.bak.log)

11-03 15:53:90

### 截图

<img width="447" alt="test" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12200912/6bfcb720-60bb-4e60-b622-e99447a7ff2a">

**Comment by a4840639** [comment]
又成这样了，真的吓人
<img width="1728" alt="Screenshot 2023-11-04 at 12 03 43 AM" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12200912/5dcd7837-6e2d-456c-9e2a-d74f62753cae">
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13256012/asst.log)

**Comment by Constrat** [comment]
This is definitely unexpected as MAA will not go in the settings because there are no tasks that allow it. I have no idea how it managed to reach all the way to the account deletion.
cc @zzyyyl

**Comment by a4840639** [comment]
@Constrat The weird thing is the background is not even the settings (But if I click on cancel here settings will show up)

**Comment by Constrat** [comment]
> @Constrat The weird thing is the background is not even the settings (But if I click on cancel here settings will show up)

I think that when it asks to delete the account it makes you leave settings, but if you cancel the action it brings you back there, (spaghetti coding on HG side probably)
