### ISSUE TITLE
关卡掉落物过多时，识别掉落物无法识别全部内容

### ISSUE THREAD

**Issue by tiyamikatto** [MaaAssistantArknights/MaaAssistantArknights#7194]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在关卡掉落物较多（诸如本次活动多种掉落物+可以同时多次代理），
屏幕无法一次性展示所有掉落物的时候，
掉落物识别会无视那些没有被展示出来的掉落物。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13255929/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13255930/gui.log)

### 截图

![_0S4E0MJGE~S6~I1C}0)2KP](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104922165/f5cf23a5-9ff9-4e68-9f17-bdeb4f25f00f)
抱歉，没有截图到对应游戏中画面，但是可以确定，这次掉落物中有全新装置，只是被挡住了一半。

### 还有别的吗？

MAA版本- v4.26.1-
夜神模拟器7.0.5.0

**Comment by Jonesau** [comment]
+1
有遇到相同情况，掉落家具后，识别掉落物全新装置数量没有增加
