### ISSUE TITLE
[TODO] 连战次数调整实现

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#7196]
### 思路
1. 直接战斗到不吃药的最大次数
2. 按吃药不溢出走
3. 重复1

### 需要调整的地方
1. 中途断连次数回滚
2. StartButton2 post_delay自适应
3. drop成功次数回调

<details>
<summary>部分信息记录</summary>

有理智药且理智不足时，列表为正常显示，不足的次数带蓝+表示吃药

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/3cd849d7-ed70-41d5-b0af-0192162cf1da)

无理智药时，次数为灰色显示

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/e7e2b891-b2e2-48b1-97d2-bc87e0305994)

</details>

**Comment by status102** [comment]
- link to #7156 
- link to #7170

**Comment by status102** [comment]
好麻烦，还有掉线的次数回滚，不想整了

**Comment by status102** [comment]
哦，除了回滚还有startbutton2的postdelay

**Comment by MobiusT** [comment]
吃源石选项是否可以设置改成连续6次连战呢？

**Comment by status102** [comment]
> 吃源石选项是否可以设置改成连续6次连战呢？

如果一颗石头的理智不够，会自动改成碎两颗吗

**Comment by ABA2396** [comment]
我感觉不要搞这么麻烦，直接博朗台模式直接设置成1次好了，其他情况用户设置成几次连战就打几次连战

**Comment by status102** [comment]
> 我感觉不要搞这么麻烦，直接博朗台模式直接设置成1次好了，其他情况用户设置成几次连战就打几次连战

如果用户之前6次就清不成理智了

**Comment by ABA2396** [comment]
> > 我感觉不要搞这么麻烦，直接博朗台模式直接设置成1次好了，其他情况用户设置成几次连战就打几次连战
> 
> 如果用户之前6次就清不成理智了，而且会造成指定次数的行为不一致

加个提示，要是刷理智一次都没执行就结束的话加个通知

**Comment by status102** [comment]
> 加个提示，要是刷理智一次都没执行就结束的话加个通知

我觉得不好

**Comment by ABA2396** [comment]
指定次数n，连战次数m，打的次数就n*m，吃药或者吃源石也不够下一轮就直接停

**Comment by MobiusT** [comment]
> > 吃源石选项是否可以设置改成连续6次连战呢？
> 
> 如果一颗石头的理智不够，会自动改成碎两颗吗

先碎一颗 ，然后理智不足再度弹框要求碎石，理智足够则正常下一步

**Comment by MobiusT** [comment]
> > > 我感觉不要搞这么麻烦，直接博朗台模式直接设置成1次好了，其他情况用户设置成几次连战就打几次连战
> > 
> > 如果用户之前6次就清不成理智了，而且会造成指定次数的行为不一致
> 
> 加个提示，要是刷理智一次都没执行就结束的话加个通知

这个会有一个问题 大部分玩家是希望无人值守状态下maa能确保清空理智 而不是因为某次人工修改成6次后忘记改回来而导致清空失败，仅发送桌面通知而导致下次执行前理智提前满 目前maa也没有比较好的出错后告警方式（serverchan，邮件等，现有的功能似乎只有完成任务提醒，而且也不是所有玩家具备远程操作的能力

**Comment by ABA2396** [comment]
> > > 吃源石选项是否可以设置改成连续6次连战呢？
> > 
> > 如果一颗石头的理智不够，会自动改成碎两颗吗
> 
> 先碎一颗 ，然后理智不足再度弹框要求碎石，理智足够则正常下一步
> 在多次刷芯片2时很容易有这个情况，
> 还会有比如某种理智药不够，要碎另一种理智药时也会出现

补体力的时候会选上足够的量，当要手动调整的时候就已经是不够了吧

**Comment by MobiusT** [comment]
> > > > 吃源石选项是否可以设置改成连续6次连战呢？
> > > 
> > > 如果一颗石头的理智不够，会自动改成碎两颗吗
> > 
> > 先碎一颗 ，然后理智不足再度弹框要求碎石，理智足够则正常下一步
> > 在多次刷芯片2时很容易有这个情况，
> > 还会有比如某种理智药不够，要碎另一种理智药时也会出现
> 
> 补体力的时候会选上足够的量，当要手动调整的时候就已经是不够了吧

我现在手头没有理智药可以测试，但是之前遇到的情况应该是只有1瓶10理智小样，但需要超过10的理智，就会多次弹窗，根据你的回复推测可能是我没有其他理智药，需要再碎石的情况，被我记错了

**Comment by ABA2396** [comment]
那回一次也已经溢出上限了，再等就是纯亏了啊）

**Comment by status102** [comment]
把PRTS1拿插件阻塞掉（暴论

**Comment by ABA2396** [comment]
> 把PRTS1拿插件阻塞掉，战斗结束再释放（暴论

所以是想做成类似指定13次按6+6+1这种方式打吗）

**Comment by status102** [comment]
> 所以是想做成类似指定13次按6+6+1这种方式打吗）

对的

**Comment by SherkeyXD** [comment]
这玩意儿怎么没动静了（

**Comment by status102** [comment]
> 这玩意儿怎么没动静了（

![Screenshot_2023-12-12-15-59-53-408_com.tencent.mobileqq-edit.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/4f9ae520-ea82-44eb-8280-9df622e4625b)

待定部分没确定下来

**Comment by MobiusT** [comment]
我现在选择吃源石，启动maa清理智，maa改连战1，然后我等一局打完刚出来的瞬间立刻改成6 （和maa斗智斗勇

**Comment by ABA2396** [comment]
> 我现在选择吃源石，启动maa清理智，maa改连战1，然后我等一局打完刚出来的瞬间立刻改成6 （和maa斗智斗勇

好，企鹅物流的垃圾数据就是这么来的

**Comment by dreamcaptorzyl** [comment]
<img width="1794" alt="continuous_fight" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131790327/2e4a1d50-296e-4545-94e8-35cb7f74867b">
5年菜鷄PM畫了個流程圖，如果有機會希望能幫開發組畫畫流程，理理邏輯什麽的，如果有需要的話可以隨時聯係我！

**Comment by Bright1996** [comment]
大佬 能不能先出个简化版 不考虑其他逻辑 
目前搓玉党为了优化1-7的效率 只能手动改源码实现这个功能 QAQ
![1704422195553](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/41429222/9b0de161-4d37-42d6-8a9f-2b1fe1b57f5d)

**Comment by ABA2396** [comment]
> 大佬 能不能先出个简化版 不考虑其他逻辑 目前搓玉党为了优化1-7的效率 只能手动改源码实现这个功能 QAQ ![1704422195553](https://private-user-images.githubusercontent.com/41429222/294378649-9b0de161-4d37-42d6-8a9f-2b1fe1b57f5d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjMzOTgsIm5iZiI6MTcwNDQyMzA5OCwicGF0aCI6Ii80MTQyOTIyMi8yOTQzNzg2NDktOWIwZGUxNjEtNGQzNy00MmQ2LThhOWYtMmIxZmUxYjU3ZjVkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDAyNTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZWY0MjQ4NDA0OWUzNjU2MzA4MDg0OGM5NjY4MjdkODIxMmZhMWIyNzlmNjg0YzU1MzgwY2QyMDgzNGM5ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qmEpqlg42ACdoax4VSlgxiNVIsl7mMKbaELm3lcuxiw)

那你改源码不如改resource/tasks.json里-1的roi)

**Comment by ABA2396** [comment]
@status102 要不先再高级设置里塞个连战次数，好歹能手动选一下）

**Comment by status102** [comment]
> @status102 要不先再高级设置里塞个连战次数，好歹能手动选一下）

这几天看看怎么糊这坨吧，等不到什么有价值的信息了

**Comment by keywet06** [comment]
需要识别信息：
1. 当前关卡单次理智
2. 当前剩余理智
3. 理智药列表

配置信息：
1. 允许最高连战次数
2. 关卡运行次数限制（x/inf）
3. 理智药选择限制（不吃/吃x天内/吃x次/无限吃（吃x=inf次））
4. 碎石策略（最多吃x源石）
5. 选择连战策略：
	1. 每次选择不吃药情况下最高连战次数，若允许吃药，在理智不足1次的情况下才选择吃药 『不足吃药策略』
	2. 每次选择所有限制下最优策略，若允许吃药，先假定吃完了药，算出最高连战次数，再计算最少吃几次药，吃完药后进行连战 『最大连战策略』

建议操作逻辑 『最大连战策略』：
```python
unit_cost = 当前关卡单次理智
left_sanity = 当前剩余理智
max_count = min(允许最高连战次数, 关卡运行次数限制)

need_sanity = unit_cost * max_count
sum_sanity = left_sanity

设置连战次数为 max_count

while need_sanity > sum_sanity and 还有能吃的理智药:
	list = 理智药列表
	add_sanity = 能吃的理智药中优先级最高的理智药容量
	sum_sanity += add_sanity
	吃下当前理智药

if need_sanity > sum_sanity and 允许碎石:
	unit_stone = 碎一个源石能获得的理智
	stone_num = min(剩余源石数量, (need_sanity - num_sanity - 1) // unit_stone + 1)
	sum_sanity += unit_stone * stone_num
	碎 stone_num 次石头

final_count = sum_sanity // unit_cost

设置连战次数为 final_count

if final_count=0:
	return 任务结束

开始战斗
```

**Comment by keywet06** [comment]
感觉列表中“不足的次数带蓝+表示吃药”这个信息用处不是特别大，还要考虑碎石的问题

**Comment by status102** [comment]
> 感觉列表中“不足的次数带蓝+表示吃药”这个信息用处不是特别大，还要考虑碎石的问题

碎石和吃药在别的地方有控制，而且是分离的

**Comment by keywet06** [comment]
如果还是分离做的话就不能一直取最大连战数了，如果要做最优策略必须要一起考虑，感觉还是合并起来做好一点

**Comment by keywet06** [comment]
合并考虑技术上没有啥太大难点啊

**Comment by keywet06** [comment]
上面的控制逻辑需要改一改，不然会出现吃了药但是不够打一关的情况，还是不够优

**Comment by keywet06** [comment]
```python
unit_cost = 当前关卡单次理智
left_sanity = 当前剩余理智
max_count = min(允许最高连战次数, 关卡运行次数限制)

need_sanity = unit_cost * max_count
sum_sanity = left_sanity

设置连战次数为 max_count

list = 理智药列表
while need_sanity > sum_sanity and 还有能吃的理智药:
	add_sanity = 能吃的理智药中优先级最高的理智药容量
	sum_sanity += add_sanity
	在list中删除当前理智药

if need_sanity > sum_sanity and 允许碎石:
	unit_stone = 碎一个源石能获得的理智
	stone_num = min(剩余源石数量, (need_sanity - num_sanity - 1) // unit_stone + 1)
	sum_sanity += unit_stone * stone_num

final_count = sum_sanity // unit_cost
need_sanity = final_count * unit_cost
sum_sanity = left_sanity

list = 理智药列表
while need_sanity > sum_sanity and 还有能吃的理智药:
	add_sanity = 能吃的理智药中优先级最高的理智药容量
	sum_sanity += add_sanity
	在list中删除当前理智药
	吃下当前理智药

if need_sanity > sum_sanity and 允许碎石:
	unit_stone = 碎一个源石能获得的理智
	stone_num = min(剩余源石数量, (need_sanity - num_sanity - 1) // unit_stone + 1)
	sum_sanity += unit_stone * stone_num
	碎stone_num次石

设置连战次数为 final_count

if final_count=0:
	return 任务结束

开始战斗
```

**Comment by SherkeyXD** [comment]
现在是不是就差回到最大次数了）

**Comment by status102** [comment]
> 现在是不是就差回到最大次数了）

（最近没啥热情写这个了
现在是刷的次数是 连战次数x指定次数

**Comment by ABA2396** [comment]
> 用户选择次数过多时是打备用关卡还是回到最大次数吧（？

备选是不开放才打的，现在是打不了就打剩余理智，剩余理智是一把把打的（所以感觉现在的连战没啥用）

**Comment by SherkeyXD** [comment]
那或者加一个选项 "使用最大连战次数进行作战" ？
