### ISSUE TITLE
重启/强制替换adb依然连接失败

### ISSUE THREAD

**Issue by KAJIKAJIYUJI** [MaaAssistantArknights/MaaAssistantArknights#7199]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

11/4号中午之前都是正常的，下午两点左右就连接不上了
重启/强制替换/重下maa、模拟器/使用了群里的【MAA各种问题解决方案3.18】均不能解决

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13256844/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13256845/gui.log)

### 截图

![~XI@5(1`VY3Q65%QLMT9ZBW](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149611530/349a8429-043a-43da-8b1f-6d678c8ccb7e)

### 还有别的吗？

蓝叠模拟器

**Comment by ABA2396** [comment]
```
[2023-11-04 22:09:29.431][INF][Px1dcc][Tx4034] Call ` E:\maa\MAA-v4.26.1-win-x64\adb\platform-tools\adb.exe connect 127.0.0.1:5555 ` ret 0 , cost 36 ms , stdout size: 29 , socket size: 0
[2023-11-04 22:09:29.431][TRC][Px1dcc][Tx4034] stdout output:
connected to 127.0.0.1:5555


[2023-11-04 22:09:29.468][INF][Px1dcc][Tx4034] Call ` E:\maa\MAA-v4.26.1-win-x64\adb\platform-tools\adb.exe -s 127.0.0.1:5555 shell settings get secure android_id ` ret 1 , cost 36 ms , stdout size: 15 , socket size: 0
[2023-11-04 22:09:29.468][TRC][Px1dcc][Tx4034] stdout output:
error: closed
```
看日志是连上了但之后被close了，有开着其他adb软件如xxx手机助手之类的吗？有试过重启模拟器和重启电脑吗？

**Comment by KAJIKAJIYUJI** [comment]
> ```
> [2023-11-04 22:09:29.431][INF][Px1dcc][Tx4034] Call ` E:\maa\MAA-v4.26.1-win-x64\adb\platform-tools\adb.exe connect 127.0.0.1:5555 ` ret 0 , cost 36 ms , stdout size: 29 , socket size: 0
> [2023-11-04 22:09:29.431][TRC][Px1dcc][Tx4034] stdout output:
> connected to 127.0.0.1:5555
> 
> 
> [2023-11-04 22:09:29.468][INF][Px1dcc][Tx4034] Call ` E:\maa\MAA-v4.26.1-win-x64\adb\platform-tools\adb.exe -s 127.0.0.1:5555 shell settings get secure android_id ` ret 1 , cost 36 ms , stdout size: 15 , socket size: 0
> [2023-11-04 22:09:29.468][TRC][Px1dcc][Tx4034] stdout output:
> error: closed
> ```
> 
> 看日志是连上了但之后被关闭了，有开着其他adb软件如xxx手机助手之类的吗？有试过重启模拟器和重启电脑吗？

没有开着其他的东西，模拟器、电脑都重启过，重启直连还是连接失败

**Comment by ABA2396** [comment]
你这是hyperv的蓝叠？

**Comment by ABA2396** [comment]
https://maa.plus/docs/1.2-常见问题.html#蓝叠模拟器每次启动端口号都不一样-hyper-v

**Comment by KAJIKAJIYUJI** [comment]
> [https://maa.plus/docs/1.2-常见问题.html#蓝叠模拟器每次启动端口号都不一样-hyper-v](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7-hyper-v)

试过了，还是连接失败
