### ISSUE TITLE
增加一个战斗任务超时提醒

### ISSUE THREAD

**Issue by ABA2396** [MaaAssistantArknights/MaaAssistantArknights#720]
现在在战斗过程中闪退MAA不会有任何提示，而且闪退后会一直进行识别操作，从日志中可以看到，因为没有能匹配上的项，每0.5秒都会去识别一次
![image](https://user-images.githubusercontent.com/99072975/171834757-718ec9df-17f9-4dab-91d7-f1d36349a086.png)
现在已经有了记录上次代理时间的功能了
所以我的想法是：
1. 第一次战斗中  
- 第一次超过一定时间（例如15分钟`如果能区分剿灭的话时间可以更短`）进行弹窗提示
- 第二次超过一定时间（例如20分钟`如果能区分剿灭的话时间可以更短`）停止当前任务。
2. 第二次战斗及以后
- 第一次超过上一次战斗时间1.5倍时间进行弹窗提示
- 第二次超过上一次战斗时间2.5倍时间停止当前任务。

**Comment by MistEO** [comment]
检测到崩溃直接重启，不需要了（
