### ISSUE TITLE
【获取信用】里面的【访问好友】不能取消

### ISSUE THREAD

**Issue by chaofanlin** [MaaAssistantArknights/MaaAssistantArknights#7201]
### 说说你遇到的问题？

【获取信用及购物】里面的【访问好友】锁死选择了，不能取消？
版本v4.26.1
[https://i2.100024.xyz/2023/11/05/aqhnz.webp](https://i2.100024.xyz/2023/11/05/aqhnz.webp)

**Comment by Constrat** [comment]
Has always been like this.
