### ISSUE TITLE
萨米肉鸽先行一步会卡住无法继续

### ISSUE THREAD

**Issue by ranxiya233** [MaaAssistantArknights/MaaAssistantArknights#7205]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在自动肉鸽选择刷等级情况下，遇到先行一步，错误选择派遣干员（虽然截图显示选择询问土著选项，但是发现时处在派遣干员界面），进入选择派遣干员界面后无法继续，根据时间来看卡了大概两分钟了

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13258086/gui.log)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13258087/asst.log)

时间（MAA报告进入该事件的时间）2023.11.5 09:05:07

### 截图

![2023-11-05_09-05-09-300_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149914463/3983180c-5163-45d0-a160-4b7bc82bb4fd)

### 还有别的吗？

使用mumu模拟器12
操作系统为Windows11专业版

**Comment by broken-paint** [comment]
duplicate of #7160
