### ISSUE TITLE
刷理智刷错关卡

### ISSUE THREAD

**Issue by PlasmaXBill** [MaaAssistantArknights/MaaAssistantArknights#7208]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用刷理智功能，关卡选择ZT-8，但刷完之后发现全部刷的是先锋/辅助芯片关

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13258582/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13258583/gui.log)

### 截图

使用的MAA设置如图
<img width="600" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/109256576/a4102979-49d5-41a8-8503-356f55087ca7">

### 还有别的吗？

模拟器：网易Mumu
操作系统：Windows 11 家庭中文版 22H2
相关配置：CPU：AMD Ryzen 9 7940H w/ Radeon 780M Graphics        4.00 GHz

**Comment by zzyyyl** [comment]
日志不对，发 asst.bak.log
