### ISSUE TITLE
活动关卡信息无法获取，MAA官网无法获取版本信息，更新内容无法获取

### ISSUE THREAD

**Issue by nityourk** [MaaAssistantArknights/MaaAssistantArknights#7209]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，老版本客户端存在该问题，目前从GitHub上更新最新客户端后问题仍未解决。以下截图为2023年11月5日MAA客户端界面截图及官网页面截图，关卡信息中未见活动关卡。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13258665/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13258666/gui.log)

### 截图

![微信截图_20231105123617](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146436106/652e0874-f38d-4152-bf39-fb685c997c51)
![微信截图_20231105123716](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146436106/7df04c90-be90-48dc-b079-3a5261d708fe)

### 还有别的吗？

Windows操作系统，雷电模拟器

**Comment by zzyyyl** [comment]
活动信息是热更的，点 `检查更新` 然后等一会儿

**Comment by nityourk** [comment]
> 活动信息是热更的，点 `检查更新` 然后等一会儿

![微信图片_20231105125919](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146436106/9d678ad1-91b
![微信截图_20231105130110](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146436106/2ed0a313-7f5e-44a8-b356-f9b30177b92d)
f-48eb-977d-185640dbf063)
点击后显示获取更新信息失败，但是进入客户端时显示关卡数据获取成功

**Comment by nityourk** [comment]
> > 活动信息是热更的，点 `检查更新` 然后等一会儿
> 
> ![微信图片_20231105125919](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146436106/9d678ad1-91b ![微信截图_20231105130110](https://user-images.githubusercontent.com/146436106/280507287-2ed0a313-7f5e-44a8-b356-f9b30177b92d.png) f-48eb-977d-185640dbf063) 点击后显示获取更新信息失败，但是进入客户端时显示关卡数据获取成功
![微信图片_20231105125919](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146436106/4773824f-2d57-4aaa-be5f-ff546509ee30)

**Comment by zzyyyl** [comment]
有代理的话填下代理试试（？

**Comment by zzyyyl** [comment]
哦，好像是ota的证书炸了

**Comment by SherkeyXD** [comment]
Due to #7204

**Comment by nityourk** [comment]
> Due to #7204
