### ISSUE TITLE
肉鸽开局选取干员问题

### ISSUE THREAD

**Issue by WuxBB** [MaaAssistantArknights/MaaAssistantArknights#721]
肉鸽开局选人时自动跳过干员山，选了煌，我大号小号都是这样，原因不明

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8832085/asst.log)

**Comment by MistEO** [comment]
似乎是识别错了，帮忙在招募界面截一张图看看（需要模拟器自带的截图工具截的原图）

**Comment by WuxBB** [comment]
![MuMu20220603203451](https://user-images.githubusercontent.com/68009949/171854774-512d7e6a-429e-4508-a989-fe0a4c2ecf7c.png)
是这样吗

**Comment by WuxBB** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8832357/asst.log)

**Comment by WuxBB** [comment]
模拟器是mumu模拟器，分辨率1080，dpi320

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/171855994-f214b91d-2548-4ec9-9428-1fb0dbdd889d.png)
山喜提新别称

**Comment by WuxBB** [comment]
哈哈哈，笑死（doge
