### ISSUE TITLE
自动公招的现有逻辑可能导致联络次数溢出

### ISSUE THREAD

**Issue by FSeagle** [MaaAssistantArknights/MaaAssistantArknights#7214]
### 说说你遇到的问题？

按现有自动公招的逻辑，在出现3星tag时会使用联络次数刷新，在出现4星tag时会直接招募。
这就导致，在连续出现4星tag的情况下，MAA会直接招募，一直到最大招募次数。
出现4星tag虽然概率低，但是还挺常见的

在实际使用过程中，
如果我把每次最大招募次数设置为“2”，只要连续2次自动出现4tag，就相当于本次执行MAA时没有消耗联络次数。
联络次数上限是3次，8小时一次，考虑到基建办公室，一天是3-5次，也就是大半天就会刷满。
假如我一天早晚执行2次MAA，那就只要4次公招里有3次刷出4星tag，就会联络次数溢出。
4次公招里有3次刷出4星tag，这个概率虽然低，但玩上半年总能发生一次的，说不定比有些人的高资出现率还高

这个问题影响的收益很小很小，如果最大招募次数设置的是3，那发生的概率就更低了。
但总归有那么一点点瑕疵
最好OCR判定一下联络次数，要是联络次数不为0，招募许可也有剩，就继续公招把联络次数用完，要是4个槽都满了，就加急许可腾出槽位

**Comment by zzyyyl** [comment]
这也太corner case了，谁爱写谁写吧.jpg

**Comment by Constrat** [comment]
This has been discussed multiple times. The complexity of the algorithm would increase exponentially, while the "benefits" will only be counted on the fingers of a hand.... Not ideal.
