### ISSUE TITLE
建议信用商店购物增加按性价比自动购物的功能

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#7216]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前的信用商店购物只有白名单和黑名单，没有对于打折的办法。在打折时，原先价值较低的物品，如破损装置，赤金等，也会优于高价值物品。

### 有什么好的想法？

建议增加按照一图流中的信用商店商店性价比购买的功能，这样可以最大限度地利用信用，毕竟蚊子腿再小也是肉（）

**Comment by ABA2396** [comment]
在白名单买完之后不是从前往后买的吗？打折的都在前面吧

**Comment by aliezlo** [comment]
> 在白名单买完之后不是从前往后买的吗？打折的都在前面吧

这样还不够全面，为了避免买到低价值的物品，需要设置黑名单；但是原先低价值的物品在打折之后就变成高价值了。
如果为了这样不把低价值的物品设置到黑名单，那么在购买未打折物品时，又会购买低价值物品。
总而言之，目前的黑白名单机制是有疏漏的。

**Comment by zzyyyl** [comment]
事实上每天获取的信用足够买完所有打折商品，没必要给 _破损装置_ ，_赤金_ 这些设黑名单，黑名单设 _碳_ 这些就够了：）

**Comment by zzyyyl** [comment]
有人觉得需要的话可以自己写完提 PR）
