### ISSUE TITLE
也许需要一个截图耗时情况展示给UI

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#7217]
Copilot、肉鸽 战斗与截图耗时存在高度关联

Copilot直接提供一个区域显示 平均 / 最大用时 （均为最近2分钟）
主界面在用时超过阈值时输出一条Log（一定时间内 / 直到缓解前 只输出一次

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/438f1067-e864-44ce-b0ca-6585bf1f3090)

**Comment by Constrat** [comment]
For Integrated Strategies there's a lot of space here

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/9773dca1-794e-4bf0-b267-3759ff9cc58a)

**Comment by status102** [comment]
> For Integrated Strategies there's a lot of space here
> 
> ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/9773dca1-794e-4bf0-b267-3759ff9cc58a)
> 

oh, here, it's a good idea

**Comment by Constrat** [comment]
(Even though it's technically an "Advanced" information)
But we have more settings in the Advanced than in the General

**Comment by status102** [comment]
it may be not a problem. This page usually is not showed

**Comment by ABA2396** [comment]
我感觉常规任务还是直接输出到日志栏吧，copilot之类的再多个标签显示

**Comment by Constrat** [comment]
> 我感觉常规任务还是直接输出到日志栏吧，copilot之类的再多个标签显示

Yeah consistency wise it doesn't make sense, but with I.S. the amount log outputted is a lot, the `Screencap Delay` could get lost?

**Comment by status102** [comment]
> Yeah consistency wise it doesn't make sense, but with I.S. the amount log outputted is a lot, the `Screencap Delay` could get lost?

可以考虑每隔5/10分钟以Error格式输出，肉鸽那边可能会调整一些日志输出（比如投资

**Comment by Constrat** [comment]
How about if its >1000ms it will output?

**Comment by status102** [comment]
不过其他任务不像Copilot类任务那样要求较高的截图时效，大一些延迟也无所谓。或许可以考虑提供一个开关来控制输出，或者Growl.Info（不会超时自动消失，但是每次运行MAA只显示一次），就像#7103
