### ISSUE TITLE
雷电模拟器minitouch点击位置错误

### ISSUE THREAD

**Issue by Vinorie-Yurio** [MaaAssistantArknights/MaaAssistantArknights#7220]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

<del>原来更改触控方式需要重启maa啊，能不能在设置里加一下说明，看日志前我还以为切换成功了。<del/>

1. 启动游戏后能正常识别GameStart.png并点击屏幕（坐标正确但不确定是不是真点了这个坐标）。
2. 之后能正常识别StartToWakeUp.png并获取正确坐标((629, 505)附近)，但游戏内没有成功点击“开始唤醒”，不确定点了哪儿，我换了个脚本器点击该坐标是能成功点击并进入游戏的。
3. 手动点击“开始唤醒”再用maa执行自动公招，同样能获取正确点击坐标(1001, 516)，但实际可能点在了图中位置，进入了终端界面。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13260389/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13260391/gui.log)

1. 点击开始游戏在asst.log 984行。
2. 点击开始唤醒在asst.log 998行。
3. 点击自动公招在asst.log 2116行。

### 截图

![(JS_AAZ@ 5UDM 4)I89Q{(I](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/84728168/2b09ec87-4ca9-423a-86ff-0329861ca73f)

### 还有别的吗？

模拟器为雷电模拟器9.0.61(9)，模拟器分辨率为720x1280。开启强制锁定横屏。
系统为win10，a卡au。系统2k分辨率125%缩放率。因为触控方式成功换成maatouch后能正常玩了正在挂机所以不想重开测试缩放率是否有影响了（但我寻思“终端”和“公招”的位置好像跟缩放率没关系）。

**Comment by status102** [comment]
- Duplicate of #7090

**Comment by ABA2396** [comment]
模拟器在桌面的时候是竖屏的还是横屏的

**Comment by Vinorie-Yurio** [comment]
> 模拟器在桌面的时候是竖屏的还是横屏的

横屏的。

**Comment by ABA2396** [comment]
~~11月6号找了雷电，到现在还没回应~~
