### ISSUE TITLE
絮雨、麒麟X夜刀在基建识别中的异常

### ISSUE THREAD

**Issue by SWETzero** [MaaAssistantArknights/MaaAssistantArknights#7221]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在自定义基建里，絮雨和夜刀正在基建相应的位置，但是MAA没法识别到她们，重复了三次流程后放弃了，因为干员数量多，这两步花费了将近20分钟左右的时间。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13261929/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13261930/gui.log)

### 截图

![pic](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55302904/92810972-b6c5-46d9-921c-041752b46af3)

### 还有别的吗？

使用的MUMU模拟器12，之前在使用蓝叠中也会发生，全部都是Win10平台，平时使用的电脑和开发的电脑都有这个问题。

**Comment by ABA2396** [comment]
麒麟X夜刀改名麒麟R夜刀了，还有你配置表的絮雨前面多了个空格
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/d69514fd-7e5c-4541-af4c-dbdcfeb8d8fb)

**Comment by SWETzero** [comment]
原来是这样，这是之前老版本时候做的自定义排班，当时估计就没注意，终于解决了。
