### ISSUE TITLE
建议信用商店购物增加按性价比自动购物的功能

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#7222]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前的信用商店购物只有白名单和黑名单，没有对于打折的办法。在打折时，原先价值较低的物品，如破损装置，赤金等，也会优于高价值物品。
为了避免买到低价值的物品，需要设置黑名单；但是原先低价值的物品在打折之后就变成高价值了。
如果为了这样不把低价值的物品设置到黑名单，那么在购买未打折物品时，又会购买低价值物品。
关键在于目前的购买机制是按前后排列的顺序来购买，但是yj不会将物品按照价值顺序排列。
总而言之，目前的黑白名单机制是有疏漏的。

### 有什么好的想法？

建议增加按照一图流中的信用商店商店性价比购买的功能，这样可以最大限度地利用信用，毕竟蚊子腿再小也是肉（）

**Comment by SherkeyXD** [comment]
黑名单放的是你不想买的东西，这些东西不会因为打折而让你想买
比如你会因为碳-99%而去买碳吗

**Comment by SherkeyXD** [comment]
Dupicate of #7216
一个问题开一个issue讨论就够了
