### ISSUE TITLE
萨米肉鸽烧水遇到999源石锭卡死

### ISSUE THREAD

**Issue by Tessiess** [MaaAssistantArknights/MaaAssistantArknights#7225]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

当使用萨米肉鸽烧开水模式时，假如源石锭已满（为999），程序会直接退出到肉鸽的主页面，并且显示任务已完成（实际上还在第一层商店），疑似烧开水的模式套用存钱模式，直接以存钱模式的终止条件退出

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13263849/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13263861/asst.zip)
2023/11/6  15：20附近

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/795a9ce4-f44e-4dd6-99f4-5b92a27f3327)

**Comment by Tessiess** [comment]
哦哦，我以为这个条件是只有刷源石锭的时候才生效 TnT
