### ISSUE TITLE
在使用迷城主题界面并且有月卡即将到期提示时，自动信用购物任务出错

### ISSUE THREAD

**Issue by JodyJoyce** [MaaAssistantArknights/MaaAssistantArknights#7226]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如标题所述

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13264854/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13264856/gui.log)

### 截图

![Screenshot_2023 11 06_17 31 59 719](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150012895/a5824606-efc6-41a5-bb28-fdf7759f474b)
![屏幕截图 2023-11-06 173241](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150012895/e4a93f4d-87ff-4ad4-8122-7e0ed7c83729)

### 还有别的吗？

蓝叠win11

**Comment by Constrat** [comment]
Duplicate of #7175
