### ISSUE TITLE
使用Playcover的时候找不到adb的连接地址

### ISSUE THREAD

**Issue by Chris-Headline** [MaaAssistantArknights/MaaAssistantArknights#7227]
### 说说你遇到的问题？

原来的方法是在打开的窗口上方有显示连接地址，但是我更新了版本之后没有找见这个地址，只显示明日方舟
这导致了我的maa他连接不上了😭
谁能告诉我还有啥方法可以搞到这个连接地址

**Comment by ABA2396** [comment]
cmd里输入adb devices可以吗？没连上可能没输出，但可以试一下。
