### ISSUE TITLE
萨米肉鸽提丰不开技能

### ISSUE THREAD

**Issue by broken-paint** [MaaAssistantArknights/MaaAssistantArknights#7228]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

关卡是最后的巍峨银淞
另外，之前有次点到异德后一直不撤退，挂了很久（当时忘截下来了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13265380/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13265383/gui.log)

**Comment by Lancarus** [comment]
#6582 原因在这，改进方法应该是添加干员部署的验证之类的，比如放下去干员之后待部署列表里面不存在该干员之后才认为部署成功
