### ISSUE TITLE
希望肉鸽增加刷时长的功能

### ISSUE THREAD

**Issue by broken-paint** [MaaAssistantArknights/MaaAssistantArknights#7230]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

肉鸽一局时间不稳定，有些时候一个半小时有些时候半个小时，按次数刷的话时间不稳定

**Comment by Constrat** [comment]
Timer, when the timer stops, just kill the run, or leave it as-is for the user to continue next time, or let MAA continue it next time.
I.S. is too random to give timing to the runs
