### ISSUE TITLE
强制定时启动时无法做到一直碎源石刷关卡

### ISSUE THREAD

**Issue by MobiusT** [MaaAssistantArknights/MaaAssistantArknights#7231]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

关于这个iss更新后的额外补充
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/4601#issuecomment-1646563476

体验了[强制定时启动功能]，这个功能很棒，但是我遇到一个问题，定时重启时因为刷理智的吃源石选项为一次性选项，导致重启后没法继续碎石刷关卡，请问当前版本有没有办法能处理呢？

### 有什么好的想法？

个人想法是加一个[视源石如粪土]选项将吃源石选项保存（可以弹出警告重复确认：该选项会导致源石清空，请手动输入xxx确认开启选项等），达成24小时碎石，期间定时执行基建等任务

**Comment by status102** [comment]
印象中以前碎石是分一次性和保存来的，后来不知道为啥给取消了保存的设定

**Comment by ABA2396** [comment]
> 印象中以前碎石是分一次性和保存来的，后来不知道为啥给取消了保存的设定

不，碎石一直都是只执行一次的，最开始的时候界面显示的就是 “吃理智药”“吃源石*”，所有界面带*的都是只生效一次

**Comment by ABA2396** [comment]
源石这个风险确实有点大，挂半天可能就一百多块钱出去了，得想想有没有什么更好的办法。

或者说加个开关，开了之后和吃理智药一样，右键单次左键常驻，但这个提示必须得做到位）

**Comment by MobiusT** [comment]
可以弹出警告重复确认：该选项会导致源石清空，请手动输入xxx确认开启选项等
这个提示方式可行吗

**Comment by status102** [comment]
> 源石这个风险确实有点大，挂半天可能就一百多块钱出去了，得想想有没有什么更好的办法。
> 
> 或者说加个开关，开了之后和吃理智药一样，右键单次左键常驻，但这个提示必须得做到位）

高级设置里面加一条（比划
不然不允许打勾，只允许方块
