### ISSUE TITLE
希望萨米肉鸽增加刷隐藏坍缩选项

### ISSUE THREAD

**Issue by bubbugum** [MaaAssistantArknights/MaaAssistantArknights#7232]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

手刷过于精污

### 有什么好的想法？

n3指挥分队开局，选择刻意漏怪的下人方式，打完两局后检查坍缩范式列表，没有则重开，有则交给人工接管。

**Comment by Saratoga-Official** [comment]
#9172 已增加
