### ISSUE TITLE
连续代理指挥导致的战斗次数错误，理智浪费

### ISSUE THREAD

**Issue by partial-cyber** [MaaAssistantArknights/MaaAssistantArknights#7233]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### **连续代理指挥导致的战斗次数错误，理智浪费**

当玩家手动使用连战功能进行代理指挥成功后，**之后登录时会保留连续作战次数的设定，此时MAA不会取消连战设定，而是已连战设定进行操作。**
**例如：**
已狗粮本LS-6为例，一场一次是36理智，而使用连战进行一场两次需要72二理智
玩家手动使用连战功能进行一场两次连续作战的代理指挥，**结束后明日方舟并不会在下一次登录的时候把连战设定重置**
**依然是已一场两次的连战设定进行**

当玩家第二天已满理智进游戏(128为例) 
此时如果MAA打LS-6，第一次消耗的理智是72而非36，进行一场LS-6后理智剩余 128 - 72 = 56 。当MAA结束第一场时，进入第二场此时的设定依然是连战一场两次消耗72理智。MAA会点击一次开始，**如果没有设定吃理智液或者打剩余理智关卡则会直接结束战斗任务，导致原本能刷3次的LS-6只刷了两次剩下的56理智会全部用于刷剩余理智关卡或者直接浪费。**

### 日志文件

[2023-11-07 00:11:59.920] - [2023-11-07 00:27:32.441]
这里即为LS-6打了2次剩了54理智没有刷第三次LS-6而是直接去打1-7(这里的1-7是一场两次的设定所以次数少)
log文件这边一直something went really wrong 传不上来
https://w-dnmd.lanzoub.com/it8uM1e0swsj

### 截图

![QQ截图20231107002828](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76105797/31feecc2-64f4-43f4-bf5e-2e9ed082a537)
![QQ截图20231107001139](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76105797/fb504cbd-7651-433d-a596-f330a783cda4)
![QQ截图20231107002820](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76105797/31c78e37-623a-4294-9e09-3e860edf9c0b)

### 还有别的吗？

可以通过计算利用连战系统直接一次一场战斗打完全部可打的次数
如128理智 LS-6 ，36一场 ，算出最多三次，之后直接让MAA设定连战为3去打

**Comment by SherkeyXD** [comment]
Duplicate of #7197
