### ISSUE TITLE
希望远程控制的访问端点可以用HTTP服务

### ISSUE THREAD

**Issue by ZGLinus** [MaaAssistantArknights/MaaAssistantArknights#7234]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前远程控制协议需要提供的服务必须需要HTTPS端点，但是内网使用HTTPS没有必要，希望可以加入HTTP的选项。

### 有什么好的想法？

使用HTTP端点作为服务时，可以加入数据传输不安全的警告。

**Comment by SherkeyXD** [comment]
内网的话 试试自签名证书？
