### ISSUE TITLE
新增外部通知方式：Bark

### ISSUE THREAD

**Issue by U98de** [MaaAssistantArknights/MaaAssistantArknights#7237]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

~~serverchan免费版只有5条（~~
以及不能直接在通知里看到通知内容
https://github.com/Finb/Bark
~~不过Bark只有ios端~~

**Comment by SherkeyXD** [comment]
谁来写.jpg
