### ISSUE TITLE
将萨米特定肉鸽的关卡干员位置更改的建议

### ISSUE THREAD

**Issue by github123520** [MaaAssistantArknights/MaaAssistantArknights#7238]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

MAA-v4.26.0-win-x64\resource\roguelike\Sami\autopilot 没有尽头的路.json

### 有什么好的想法？

建议将近战的5,1定位更改为5,5 可以避免“深入调查中用不会攻击，不被眩晕的景观巨蘑卡住小怪导致游戏时长大大增加”的情况

### 其他内容

无

**Comment by Constrat** [comment]
cc @Lancarus

**Comment by Lancarus** [comment]
自己改一下就行了
