### ISSUE TITLE
fight recruit出错

### ISSUE THREAD

**Issue by Katachy** [MaaAssistantArknights/MaaAssistantArknights#724]
蓝叠五国际版
勾选开始唤醒、刷理智、自动公招、基建换班
唤醒成功后刷理智、公招失败，基建换班成功
![QQ截图20220603232747](https://user-images.githubusercontent.com/104708686/171886553-ab6940e9-378a-46c8-8f6d-724fee34dd61.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8833398/asst.log)

**Comment by MistEO** [comment]
卡在 `今日配给` 界面了么？还是卡在哪了

如果是的话更新 v3.9.3 试一下，已经修复了
