### ISSUE TITLE
萨米肉鸽抗干扰为零时遇到纵向树篱会卡死

### ISSUE THREAD

**Issue by AmemiyaMiomy** [MaaAssistantArknights/MaaAssistantArknights#7241]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

昨天偶然遇见的小概率事件，忘记截图和日志时间，抱歉只能描述了。
抗干扰点数为0，刚好纵向节点是树篱之途，一直重复“点击树篱之途”，“确认消耗抗干扰点数”，“点数为0消耗失败”，“点击树篱之途”...陷入死循环了。
推测是树篱之途优先级过高？建议在纵向移动前加入一步抗干扰点数为0的识别。不过这个概率挺小的，挂了好多天也就这一次卡住了。

### 日志文件

抱歉……

**Comment by SUPERDAIDAI007** [comment]
![Snipaste_2023-11-08_17-04-38](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115518104/ea23621f-597e-4e96-a378-4dcc52f0e2dc)
![Snipaste_2023-11-08_17-05-11](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115518104/5a7af0af-0130-4137-ad05-8157009880e3)
![Snipaste_2023-11-08_17-11-34](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115518104/ac9a16d7-0217-49c1-8508-e69d342ffc6b)
同样状况

**Comment by Lancarus** [comment]
打板子引起的bug，全面勘察打在了纵向节点上，一般情况下没有抗干扰识别不到纵向的节点类型
