### ISSUE TITLE
在基建时莫名其妙崩溃了

### ISSUE THREAD

**Issue by SSG233** [MaaAssistantArknights/MaaAssistantArknights#7245]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

崩溃时 鼠标迟钝 崩溃后 windows下面应用鼠标移上去缩略框内容不再为动态

### 日志文件

2023/11/8 12：36前5min大概时间
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13292141/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13292142/gui.log)

### 还有别的吗？

mumu12 windows10
RTX 3060 12G 锁算力版
i7 12700
16G DIMM

**Comment by SSG233** [comment]
内测版最新版（当前时间）

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/caefa276-0be3-4803-a536-ece6bc43fdf3)
ui的日志甚至显示12:07:50就退出了，这是咋跑起来的）
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7b5a56ba-7f44-4b2b-95b7-9e063436f1d0)
之后还有遇到这个问题吗？
