### ISSUE TITLE
肉鸽烧水难度选择错误

### ISSUE THREAD

**Issue by Geraldgu** [MaaAssistantArknights/MaaAssistantArknights#7248]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽选择烧开水时会在调整到0难完成烧水后调回原难度时直接调整到N15(原先选择N10）

### 日志文件

[Uploading asst.zip…]()
[Uploading gui.zip…]()

**Comment by Constrat** [comment]
Duplicate of #7248
