### ISSUE TITLE
请求在自动更新的部分添加代理设置

### ISSUE THREAD

**Issue by HansBug** [MaaAssistantArknights/MaaAssistantArknights#725]
如题，因为众所周知的原因，简中服用户们挺容易被卡在自动更新这里的，因为github asset的访问速度很慢且不稳定。因此如果可以加一个代码设置（可以参考浏览器插件，或者一些IDE中的此类配置）的话，应该使用体验会顺滑很多。

当然，也有另一种替代方案，那就是考虑在gitee/codechina/coding等墙内平台配置一个镜像仓库，将release asset等一并进行同步，并使用墙内链接（考虑到可能有外网用户，因此可以考虑检测一下网络环境）。

一点建议~~

**Comment by MistEO** [comment]
就是加了的，设置里有个 `http proxy` 可以填。

我们打算自己直接搭一个 server, 支持增量更新而不是完整下载 release, 然后目前进度可以看 [这个 repo](https://github.com/MaaAssistantArknights/MaaDownloadServer)

**Comment by HansBug** [comment]
> 就是加了的，设置里有个 http proxy 可以填。

唔，才看到，抱歉。
这部分的话不知道支不支持socks5协议，毕竟买的梯子一般都是这个协议。
另外，`软件更新` 这部分似乎没看见能用来测试连接的功能。其实倒未必一定得加个 `测试连接` button，如果能像app一样加个手动 `检查更新` 的icon其实也能起到类似的效果。

> 我们打算自己直接搭一个 server, 支持增量更新而不是完整下载 release, 然后目前进度可以看 [这个 repo](https://github.com/MaaAssistantArknights/MaaDownloadServer)

已star，保持关注~~

**Comment by zhongfly** [comment]
> 这部分的话不知道支不支持socks5协议，毕竟买的梯子一般都是这个协议。

不都是代理客户端连接代理节点，然后开本地代理给本机的软件使用吗？
代理客户端基本都支持提供http代理

如果是直接提供socks5代理节点的那种，倒是十分罕见
