### ISSUE TITLE
战斗列表中“添加突袭的模式”的优化建议

### ISSUE THREAD

**Issue by github123520** [MaaAssistantArknights/MaaAssistantArknights#7250]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在战斗列表可以一键拉取多个关卡，但是突袭仍然要通过单个拉取再右键添加，较为麻烦，能加一个按钮吗？功能是：为当前关卡添加突袭难度且排列在各自的后面

**Comment by status102** [comment]
按照突袭关卡格式为不同关卡作业命名后添加即可

**Comment by github123520** [comment]
> 按照突袭关卡格式为不同关卡作业命名后添加即可

例如ZT-EX-1~ZT-EX-8 是直接修改JSON文件内的哪些地方呢？
我看了一下只有两个地方：
1.  "stage_name": "act29side_ex02",
2.   "doc": {
    "title": "崔林特尔梅之金 - ZT-EX-2 - 对位法",
搜了一下专门突袭的json作业，似乎也没找到修改的地方,ZT-EX-1-Adverse,这个部分请教一下改动json的标题还是内容？

**Comment by status102** [comment]
改文件名

**Comment by github123520** [comment]
> 改文件名

好的谢谢！
