### ISSUE TITLE
自动编队-补充低信赖干员 可能会编入 干员组 中用于替补的没练过干员

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#7251]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题

### 日志文件

无

**Comment by ABA2396** [comment]
发现了盲点）

**Comment by status102** [comment]
> 发现了盲点）

你觉得编队完之后把编队情况传递给战斗模块怎么样
影响：
耦合++
问题--
新特性get!（再把干员组排序一下，就能支持高低练度干员组了

**Comment by ABA2396** [comment]
选信赖的时候把备选的排除了（bushi）

**Comment by status102** [comment]
> 选信赖的时候把备选的排除了（bushi）

那可能就得每个干员选择之后截图一下左边id了，识别耗时++++

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/10602fbb-4f97-468d-8e0f-869217194d9c)
