### ISSUE TITLE
无法加载 DLL“MaaCore.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)

### ISSUE THREAD

**Issue by dayumsista** [MaaAssistantArknights/MaaAssistantArknights#7254]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

 Visual C++ Redistributable
NET Framework 4.8
安装并重启操作已经尝试 Not work lmao

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13305958/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147481512/6a904f8a-311d-41e0-89f1-fba0630c0071)

**Comment by SherkeyXD** [comment]
发一下你 maa 的文件夹截图看看

**Comment by zzyyyl** [comment]
你不会是在压缩包里直接双击打开了吧

**Comment by BNUZ-NFZWE** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147481512/7a9dde15-2399-4633-9f5f-7f6fa4424a35)

**Comment by zzyyyl** [comment]
cc @ABA2396

**Comment by ABA2396** [comment]
不到啊，感觉没啥有用信息，跟着手册走一遍运行库-win10rt-[Microsoft C++ 生成工具](https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/)呗

**Comment by BNUZ-NFZWE** [comment]
过了一遍了啊  还是这样 MMABH3都能正常使

**Comment by zzyyyl** [comment]
是不是什么 x64 arm 的问题

**Comment by zzyyyl** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3083#issuecomment-1354159512

**Comment by ABA2396** [comment]
搞不懂）说起来这个文件夹名字为啥是1999的

**Comment by dayumsista** [comment]
huh my bad
这俩都报错 粥和亿亿韭韭韭
发张截图我就拿了亿韭韭韭的

**Comment by ABA2396** [comment]
[Sample.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10242519/Sample.zip)

试试这个放到目录下跑跑是什么结果
