### ISSUE TITLE
希望添加在停止后可以调用的脚本

### ISSUE THREAD

**Issue by schulice** [MaaAssistantArknights/MaaAssistantArknights#7256]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我使用maa连接局域网内手机，在任务停止时没有办法重置开始前脚本调节的分辨率等设置。同时，也不能通过取消所有任务来无副作用的调用结束后脚本（如图）。

### 有什么好的想法？

1. 添加停止后脚本。
2. 使选中的任务为0时仍调用结束后脚本。

### 其他内容

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/109664121/cbbae922-a7b1-4542-a02b-63d268a7d428)

**Comment by WSMTBG** [comment]
勾个开始唤醒试试？

**Comment by schulice** [comment]
> 勾个开始唤醒试试？

希望是可以无副作用，这样还要再等待游戏启动
