### ISSUE TITLE
如果在基建宿舍干员心情满时启动基建换班，可能出现换班异常的情况

### ISSUE THREAD

**Issue by lapplandert** [MaaAssistantArknights/MaaAssistantArknights#7258]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在基建宿舍内干员心情满的时候使用换班功能时，可能会出现以下情况：
1.MAA在清空选择后随意选择几个干员就点击确认的情况，完全不会选择排班表里的干员
2.MAA在清空选择后选中了排班表上的干员，然后一直右滑，划到尽头很长时间才停下，之后在随便选择了几个干员，或者根本没有选择其他干员填满宿舍空位的情况下点击确认切换到下一个宿舍，而不是切换至信赖值倒序然后选择最低信赖干员蹭信赖。
我的排班表ID：1699534297842797

### 日志文件

[日志文件.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13309994/default.zip)

### 截图

![Screenshot_20231109-234331](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/107452962/4fdfa95d-ffd3-4cda-94fd-e3e5ab654215)

### 还有别的吗？

使用雷电模拟器9，最新版本

**Comment by Ptilopsis01** [comment]
这个问题我之前也反馈过，但一直没回复

**Comment by thjyneg** [comment]
有没规避方法？休息时间拉长有用不

**Comment by lapplandert** [comment]
> 有没规避方法？休息时间拉长有用不

似乎重点在于宿舍干员心情满且没有其他心情不满的干员，只要没有干员需要进入宿舍回复心情，就有可能触发这一BUG，我个人的解决办法是每次换班前手动检查是否有干员心情不满需要换班，是就启用基建换班系统，否则不启用

**Comment by ABA2396** [comment]
感觉像是信赖啥的挡住了名字会造成的结果，现在只能说建议把要指定入住的都放在第一个宿舍里，每个宿舍放一个宿管现在可能还做不到，除非之前的宿舍里都指定满了

**Comment by Ptilopsis01** [comment]
> > 有没规避方法？休息时间拉长有用不
> 
> 似乎重点在于宿舍干员心情满且没有其他心情不满的干员，只要没有干员需要进入宿舍回复心情，就有可能触发这一BUG，我个人的解决办法是每次换班前手动检查是否有干员心情不满需要换班，是就启用基建换班系统，否则不启用

不是，它是只要有宿舍在选干员的时候完全没有心情未满的就会触发，比如我有15个干员要进宿舍，那最后一间就会没有，按理说应该选信赖低的，但是事实上会触发这个bug

**Comment by lapplandert** [comment]
> > > 有没规避方法？休息时间拉长有用不
> > 
> > 
> > 似乎重点在于宿舍干员心情满且没有其他心情不满的干员，只要没有干员需要进入宿舍回复心情，就有可能触发这一BUG，我个人的解决办法是每次换班前手动检查是否有干员心情不满需要换班，是就启用基建换班系统，否则不启用
> 
> 不是，它是只要有宿舍在选干员的时候完全没有心情未满的就会触发，比如我有15个干员要进宿舍，那最后一间就会没有，按理说应该选信赖低的，但是事实上会触发这个bug

哦，这正是我要说的意思，是我表达不当，感谢指正。
我个人推测了一下这个BUG的触发原理。
先从换班与干员心情检测说起，干员心情分三种，心情值满时为绿脸，心情不满不空为黄脸，心情空为红脸，平时MAA检测干员心情，是通过干员的脸色红黄绿来确定的。
我推测平时宿舍换班的逻辑如下：
第一步：检查排班表中要求入住的干员，例如我要这宿舍里把四个杜林都放进去，模拟器找到这四位杜林，入住宿舍，第一步结束，进入第二步。
第二步：启动心情监测系统，调整心情为倒序从心情最低的干员开始选中，直到填满宿舍（但是这一步不会寻找绿脸，只会寻找黄脸和红脸干员，是BUG之源），若宿舍未填满就已经选中了所有黄脸与红脸，进入第三步。
第三步：关闭心情监测系统，不再寻找黄脸与红脸干员。
若排班表中未选择填满空位，宿舍换班结束。
若排班表选择填满空位，找几个有心情技能的填满。
若开启蹭信赖选项，就把信赖最低的几个塞进去蹭信赖。

BUG触发逻辑：在执行第二步时，MAA会先执行“用黄脸和红脸填满宿舍”的命令，执行完毕后才会进入第三步。如果在给这个宿舍填干员时一开始就没有“黄脸和红脸干员”用于执行第二步，将导致逻辑紊乱，BUG触发，GG。
大概就是没有红脸和黄脸给MAA执行第二步，所以MAA不知道该怎么做了，于是BUG。

如果我这一套BUG的触发逻辑没有理解错的话，那么解决办法就是检测心情技能，如果有心情技能的干员被左滑找不到了依旧没有找到红脸与黄脸干员，进入第三步。

**Comment by ABA2396** [comment]
cc @MistEO

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/cc4173af-f91a-4b88-91bc-107b1209244d)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/a1903b8d-4e7a-4c1b-a600-3330147fbfb7)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/4e2036db-1a1a-4203-b39f-47e2ea92a6e9)
