### ISSUE TITLE
Maa v4.26.1無法啓動bluestacks5

### ISSUE THREAD

**Issue by CoolCoolWind** [MaaAssistantArknights/MaaAssistantArknights#7260]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如題

### 日志文件

log 不在 C:\Users<用户名>\AppData\Roaming\maa-x\logs 中
![Snipaste_2023-11-10_17-06-38](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/ae6d19e3-2547-4209-844a-a1fbb8e7e327)

但 在maa 本身的debug\gui.log
![Snipaste_2023-11-10_17-10-38](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/9373b547-84b5-4f51-a537-4feaf0a968c0)

Gui.log
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13317752/gui.log)

備注：打開模擬器后是能啓動明日方舟的

### 还有别的吗？

Bluestack 5.13 Maa v4.26.1 windows 10

**Comment by ABA2396** [comment]
这两个填了吗
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/0fef388b-168a-4d64-8fce-1f251f0ff470)

**Comment by CoolCoolWind** [comment]
![Snipaste_2023-11-10_20-06-42](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/61d7abb6-2c94-4fad-ba2c-9f65f4ab8fd5)
![Snipaste_2023-11-10_20-06-14](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/af5c9150-1e84-4ca6-9ea3-4fe01395d66c)

**Comment by CoolCoolWind** [comment]
![Snipaste_2023-11-10_20-09-40](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/55c0ef10-f468-47b0-8b30-408369aee456)
已經使用管理員身份啓動
![Snipaste_2023-11-10_20-11-24](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/fe9c04e4-0202-47c1-ae88-029aad5f4889)
正常路徑

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/77f7292f-118c-4edf-a9e4-09da22f72077)

**Comment by CoolCoolWind** [comment]
所以爲什麽log 不在 C:\Users<用户名>\AppData\Roaming\maa-x\logs 中

**Comment by ABA2396** [comment]
你这是maa不是maax啊
