### ISSUE TITLE
“MaaWpfGui.Configuration.ConfigFactory”的类型初始值设定项引发异常。 程序集“netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”中有名称为“System”的重复类型。

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#7262]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/8f2e0bbf-f3aa-412d-b32f-6b0a35dc2878)
“MaaWpfGui.Configuration.ConfigFactory”的类型初始值设定项引发异常。
程序集“netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”中有名称为“System”的重复类型。

已安装.NETFramework4.8和C++常见运行库

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13319293/gui.log)
[gui.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13319298/gui.json)

**Comment by ABA2396** [comment]
cc @Cryolitia

**Comment by Cryolitia** [comment]
这玩意都多久没动了，怎么今天突然又炸了

**Comment by Cryolitia** [comment]
请给出此问题的复现方法，程序的来源（热更新？Release下载？自行编译？）并尝试最新的发布版是否有此问题。

我注意到这一部分代码已经超过一个月没有发生过修改，问题的来源似乎更像是编译和动态库加载问题而非代码逻辑问题
