### ISSUE TITLE
【国际服】有概率不领取信用商店中的信用并购物

### ISSUE THREAD

**Issue by RiichiTsumo** [MaaAssistantArknights/MaaAssistantArknights#7263]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，但访问好友基建的信用会正常领取
且GUI中未显示任何错误

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13325439/asst.log)

删除了原来的asst.log后重新跑的，时间大概是20：14左右

### 截图

![mmexport1699619973949](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/77238633/6c32bac7-0f94-4426-857d-2b6a1b941d59)
游戏右上角显示的时间是西七区时间，与MAA GUI中显示的时间一致
![mmexport1699619981636](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/77238633/824d8fa9-7572-49e3-b94b-cf155e3e56c1)

### 还有别的吗？

这个问题似乎是概率发生的，触发条件暂不明确
模拟器是最新版的国际版蓝叠，启动方式是开机卡+MAA定时任务的全无人值守模式（MAA定时启动已与开机卡启动设置时间差）

**Comment by Constrat** [comment]
Asst.log id completely wrong. It has 20:43:XX times.
Look for the asst.log.bak one

**Comment by RiichiTsumo** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/77238633/a9770bac-2114-44b2-ba7f-7aaa77c64b3f

asst.log已更新，这里是bug发生时的视频录像
只进入了商店，然后就直接显示任务完成返回了

**Comment by Constrat** [comment]
Looking at the video it seems like the framerate is very low (too low) for MAA to perform correctly.
Is this the effect of recording the screen at low fps? Or are you normally using MAA with that framerate?

**Comment by RiichiTsumo** [comment]
> Looking at the video it seems like the framerate is very low (too low) for MAA to perform correctly.
> Is this the effect of recording the screen at low fps? Or are you normally using MAA with that framerate?
> 
> Everything is detected correctly:
> ```js
> [2023-11-11 20:14:44.900][TRC][Px4b6c][Tx4efc] asst::PipelineAnalyzer::analyze CreditStoreOcr
> [2023-11-11 20:14:44.978][TRC][Px4b6c][Tx4efc] asst::WordOcr [{ ture Store: [ 0, 100, 77, 17 ], score: 0.962891 }, { Credit Store: [ 158, 98, 91, 19 ], score: 0.966964 }] by OCR Pipeline , cost 78 ms
> [2023-11-11 20:14:44.978][TRC][Px4b6c][Tx4efc] Proced [{ Credit Store: [ 1158, 98, 91, 19 ], score: 0.966964 }]
> [2023-11-11 20:14:44.979][INF][Px4b6c][Tx4efc] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"OcrDetect","exec_times":1,"max_times":2147483647,"task":"CreditStoreOcr"},"first":["MallBegin"],"pre_task":"Mall","subtask":"ProcessTask","taskchain":"Mall","taskid":6,"uuid":"fa8b327ef85da9f5"}
> [2023-11-11 20:14:44.982][TRC][Px4b6c][Tx4efc] minitouch click: (1800, 153)
> [2023-11-11 20:14:45.084][INF][Px4b6c][Tx4efc] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"OcrDetect","exec_times":1,"max_times":2147483647,"task":"CreditStoreOcr"},"first":["MallBegin"],"pre_task":"Mall","subtask":"ProcessTask","taskchain":"Mall","taskid":6,"uuid":"fa8b327ef85da9f5"}
> [2023-11-11 20:14:45.084][TRC][Px4b6c][Tx4efc] ready to sleep 500
> [2023-11-11 20:14:45.585][TRC][Px4b6c][Tx4efc] end of sleep 500
> ```
> BUT
> ```js
> [2023-11-11 20:14:45.585][INF][Px4b6c][Tx4efc] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["CollectCredit","CreditStoreFailed","Stop"]},"first":["MallBegin"],"pre_task":"CreditStoreOcr","subtask":"ProcessTask","taskchain":"Mall","taskid":6}
> [2023-11-11 20:14:46.258][INF][Px4b6c][Tx4efc] Call ` C:\Program Files\BlueStacks_nxt\.\HD-Adb.exe -s emulator-5554 exec-out "screencap | gzip -1" ` ret 0 , cost 672 ms , stdout size: 2448036 , socket size: 0
> [2023-11-11 20:14:46.305][TRC][Px4b6c][Tx4efc] asst::PipelineAnalyzer::analyze CollectCredit
> [2023-11-11 20:14:46.305][INF][Px4b6c][Tx4efc] asst::TemplResource::get_templ lazy load CollectCredit.png
> [2023-11-11 20:14:46.322][TRC][Px4b6c][Tx4efc] asst::PipelineAnalyzer::analyze CreditStoreFailed
> [2023-11-11 20:14:46.322][INF][Px4b6c][Tx4efc] asst::TemplResource::get_templ lazy load CreditStoreFailed.png
> [2023-11-11 20:14:46.333][TRC][Px4b6c][Tx4efc] match_templ | CreditStoreFailed.png score: 0.637059 rect: [ 49, 95, 116, 24 ] roi: [ 0, 45, 216, 124 ]
> [2023-11-11 20:14:46.333][TRC][Px4b6c][Tx4efc] asst::PipelineAnalyzer::analyze Stop
> ```
> CreditStoreFailed was not detected correctly.
> 
> Tried testing what happened reducing my frames to 5 and it still worked.
> 
> NVM, noticed that also in my case the templ match of CreditStoreFailed is too low to work. (low frames is the probable cause here)

只是录制视频时使用了较低的帧率，游戏是正常以60帧运行的
