### ISSUE TITLE
肉鸽在选择烧热水时，如果没有取消勾选“储备源石锭达到上限时停止”，源石锭满时会在第二层直接退出

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#7267]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，肉鸽在选择烧热水时，如果没有取消勾选“储备源石锭达到上限时停止”，源石锭满时会在第二层直接退出。
asst.log直接干了200多mb，传不上来

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13324201/gui.log)

### 截图

<img width="599" alt="捕获" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90097743/b945af0e-09d7-4097-9182-cd5b46ef837e">
<img width="590" alt="捕获2" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90097743/e08e8fd0-843c-4672-9371-72af22e17a58">
<img width="960" alt="2023-11-11" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90097743/8a489db4-eda6-4b8d-aa91-c5d77eac1995">

**Comment by aliezlo** [comment]
取消勾选投资源石锭之后，仍然会投资一次之后直接退出。

**Comment by status102** [comment]
asst.log试试压缩后上传

**Comment by aliezlo** [comment]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13324426/asst.zip)

**Comment by aliezlo** [comment]
目前刷等级可以取消勾选投资源石锭，烧热水不行，仍然会投资一次后直接退出

**Comment by SherkeyXD** [comment]
烧热水的时候应该是可以取消勾选源石锭投资的啊 只有刷源石锭模式才是强制开启的

**Comment by aliezlo** [comment]
> 烧热水的时候应该是可以取消勾选源石锭投资的啊 只有刷源石锭模式才是强制开启的

取消了也不行，见截图

**Comment by aliezlo** [comment]
> 烧热水的时候应该是可以取消勾选源石锭投资的啊 只有刷源石锭模式才是强制开启的

取消了也没用，还是会退出
