### ISSUE TITLE
WpfGui反复调用弹出系统提示，感觉无用且让人烦躁。

### ISSUE THREAD

**Issue by Private233** [MaaAssistantArknights/MaaAssistantArknights#7268]
### 说说你遇到的问题？

<img width="930" alt="280477160-0f8a4169-74d6-4f42-ae75-0f364442591c" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108540840/14011f67-8c90-41ad-8a52-6e31f02bcef7">
<img width="600" alt="280477159-a3aec2de-7653-4afa-ab3c-cb7e127976b0" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108540840/bae415f3-1c83-4bff-a9c8-ccc0170b53fe">
每次打开maa，都会弹窗提示“游戏资源正在更新，请勿关闭maa”。不知更新内容不知更新进度。我本人目前使用maa是调了两个配置切换着用，每次切换弹窗还得再弹一次，非常让人烦躁。
而像图2的通知，在游戏内容更新后也才有弹，感觉比较合理。
是否可以考虑整改取消这个系统通知。

**Comment by ABA2396** [comment]
内测版加了进度

**Comment by ABA2396** [comment]
这玩意也是跟着游戏更新的，只有游戏有更新且本地没更新成功过才会每次弹。

**Comment by status102** [comment]
Duplicate of #6666
