### ISSUE TITLE
为啥我挂机肉鸽只执行一次

### ISSUE THREAD

**Issue by liyangyuan** [MaaAssistantArknights/MaaAssistantArknights#7273]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

两天前开始直到现在，挂机肉鸽执行一次就停了

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13325956/debug.zip)
我运行了一次才上传的，所以最新的日志应该就有

### 截图

![屏幕截图 2023-11-11 101549](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/135389310/a16cf910-a2a1-4a0b-b3e0-3ac206cb3f03)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/218cc0da-214c-41fc-b18f-a8c1c542a56b)

**Comment by liyangyuan** [comment]
> ![image](https://user-images.githubusercontent.com/99072975/282253749-218cc0da-214c-41fc-b18f-a8c1c542a56b.png)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/135389310/98128433-a978-4067-82b7-9c764b814a29)
我是这样设置的

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/9c954dfe-4a93-4f28-a8a7-4cdbc23c90f9)

**Comment by liyangyuan** [comment]
!原来如此，感谢！！！
