### ISSUE TITLE
日服 无法识别家具掉落

### ISSUE THREAD

**Issue by Manicsteiner** [MaaAssistantArknights/MaaAssistantArknights#7275]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

无法识别家具掉落。

[2023-11-12 08:21:34.682] <1><> 掉落统计: 
龍門幣 : 180 (+180)
Unknown : 1 (+1)
初級異鉄 : 1 (+1)
飛行データチップ : 15 (+15)
[2023-11-12 08:21:34.683] <1><> UnknownDropType，放弃上传企鹅物流

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13326877/gui.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13326878/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13326879/asst.log)

### 截图

![Screenshot_1699748490](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/ec0a26f9-5133-49ed-8a85-c08aa7ffcbc4)

### 还有别的吗？

MAA Debug version, commit ac2d9d4, 2023-11-10
模拟器 AVD Android13

**Comment by Constrat** [comment]
Did they change the text? Was it always LUCKY?

**Comment by Manicsteiner** [comment]
> Did they change the text? Was it always LUCKY?

In my memory, this field has always been using LUCKY

**Comment by Constrat** [comment]
Log shows a templ match of: `0.645178`, the threshold is `0.65`
```js
[2023-11-12 08:21:32.576][TRC][Px750][Tx4108] match_templ | StageDrops-DropType-Furniture.png score: 0.645178 rect: [ 257, 639, 70, 21 ] roi: [ 225, 639, 138, 25 ]
```

**Comment by Manicsteiner** [comment]
Finally drop again on native 720p emulator. It's also failed, score is also very low.
[2023-11-19 23:05:28.705][TRC][Px2390][Tx2de8] match_templ | StageDrops-DropType-Furniture.png score: 0.681998 rect: [ 257, 639, 70, 21 ] roi: [ 225, 639, 138, 25 ]
![2023-11-19_23-05-31-535_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/d9d8fb97-2cff-4596-8949-bfb16d162725)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13403652/asst.log)

**Comment by Constrat** [comment]
I'm finishing my ideas. Maybe trying to update the template could do something? 0.68 is really low. I feel like it should be at least `>0.90`.

**Comment by Constrat** [comment]
![Cropped_rect_257_640_68_17](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/e466ac8d-9122-47db-8a77-1116a5a9bc8f)
As a desperate measure. Try using this template (just replace it). Hope for another lucky drop and let's see if it changes anything.

**Comment by Manicsteiner** [comment]
[2023-11-21 08:44:30.490][TRC][Px3b94][Tx2548] match_templ | StageDrops-DropType-Furniture.png score: 0.959273 rect: [ 257, 640, 68, 17 ] roi: [ 225, 639, 138, 25 ]
Finally it works. I think a more reasonable explanation is that they changed the color of the font. The B value of the original font color is always above 10, and the new version is always below 10.
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/1f689d88-5210-44f6-bac0-9f05acb5995a)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/623f8214-c5ef-4bc8-92bf-ced9e7a0a9cd)
