### ISSUE TITLE
考虑合并稳定版和公测版

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#7279]
### 说说你遇到的问题？

先说结论 稳定版和公测版是否可以合并为一个发行版
MAA 目前存在三个软件版本周期 稳定版 公测版 内测版
目前已经出现很多由于稳定版更新不及时导致的问题 而这些问题的解决方案大多都是更新至公测版 也因此“稳定”版存在误导性
虽然文档里写了推荐使用公测版 但在那个角落 国内用户九成是看不见
公测版同样也是人工发版 不会出现上次内测版自动构建发版导致的严重问题 少个版本周期也能少点工作量
或许也可以等热更新做好再看 现在的热更新体验属实是有点不明所以
~而且稳定版也没比公测版稳定多少~

**Comment by status102** [comment]
有些东西需要一定的时间和一定数量的用户来进行测试稳定性，这个就可能不好往稳定版里塞，公测就比较好

**Comment by ABA2396** [comment]
内测版也是手动发的）

**Comment by Rbqwow** [comment]
~好好好 人工连不能运行都没发现是吧~
等热更新做好再看✓
希望小水管没事

**Comment by status102** [comment]
第三方软件稳定版适配更新延后不是很正常吗？测试需要时间需要人力。

**Comment by status102** [comment]
或者透露一下鹰角下一个功能是啥，好提前开始适配工作
