### ISSUE TITLE
龙门币识别错误，导致刷理智 `指定材料` 无法正常工作

### ISSUE THREAD

**Issue by ABA2396** [MaaAssistantArknights/MaaAssistantArknights#7282]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

会不会和 #7202 滑动识别超过一页的掉落有关？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13328180/asst.log)

### 截图

![Snipaste_2023-11-12_21-45-39](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/5c6b62f3-e178-4450-ad5c-8a8cdd75b4db)
[drops.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13328174/drops.zip)

**Comment by horror-proton** [comment]
奇怪, 理论上这不可能发生啊, 日志里面 `offset: 0` 说明划动前后图片没变化, 除非第一次截图发生在划动之后? 或者一进入结算界面就已经不在最开始的位置了?

**Comment by ABA2396** [comment]
会不会和等级有关？满级就不显示经验？

**Comment by ABA2396** [comment]
看日志感觉就是识别错了，但为什么会是0呢）

**Comment by horror-proton** [comment]
很可能是掉落的数字太长, 被切掉了, 我去跑一下看看 (也许之前不会出现这么多的掉落

**Comment by horror-proton** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/d5a68bf277077dff617240a96a02e2b9ba18f262/src/MaaCore/Vision/Miscellaneous/StageDropsImageAnalyzer.cpp#L712
破案了, 这个阈值太大, 日志里面在 0.787 左右

**Comment by ABA2396** [comment]
> https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/d5a68bf277077dff617240a96a02e2b9ba18f262/src/MaaCore/Vision/Miscellaneous/StageDropsImageAnalyzer.cpp#L712
> 
> 
> 破案了, 这个阈值太大, 日志里面在 0.787 左右, 应该是龙门币数字比较长, 挡住太多引起的

之前写基建的时候发现了在列表结尾的时候滑动结束后不能直接截图，因为到底之后会有个回正的动画，在这个时候截图截出来的就是不完整的，这个有影响吗

**Comment by horror-proton** [comment]
> 之前写基建的时候发现了在列表结尾的时候滑动结束后不能直接截图，因为到底之后会有个回正的动画，在这个时候截图截出来的就是不完整的，这个有影响吗

划动后有个 sleep 的 (而且还挺长的+
