### ISSUE TITLE
游戏资源获取失败

### ISSUE THREAD

**Issue by LXHcat123** [MaaAssistantArknights/MaaAssistantArknights#7287]
### 说说你遇到的问题？

已多次重启maa客户端。
第一次发生是在两天前，那天晚上获取资源，下载速度特别慢，似乎是会卡在95%，然后我开加速器尝试更新，然后它应该是显示更新完成，是一串英文。然后昨天和今天都是更新卡在11%( ゜- ゜)つロ，如有其他需要提交可对我说，上线较少

**Comment by Donate684** [comment]
Confirm
![MAA_nWXDADfK8m](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50923740/099b43b5-17b8-4cb8-ba98-3e923fc4b9cb)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13334682/gui.log)

**Comment by Donate684** [comment]
> https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/item_index.json 下载失败了，这个链接打得开吗

yep 

![rTrdozj](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50923740/2290c330-b8d2-4553-a6c2-a46b4a3dcb11)

I try VPN with many countries but same

**Comment by LXHcat123** [comment]
> https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/item_index.json 下载失败了，这个链接打得开吗

可以

**Comment by ABA2396** [comment]
感觉像是服务器的问题了，我去问问

**Comment by LXHcat123** [comment]
> 感觉像是服务器的问题了，我去问问

麻烦了  ˶╹ꇴ╹˶

**Comment by LXHcat123** [comment]
> 感觉像是服务器的问题了，我去问问

今天可以了，更新资源成功了
一开始识别点击位置错误，我更换了分辨率解决了

**Comment by Sait0Yuuki** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13412219/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13412220/gui.log)
同卡在11%，访问出错任务的url都正常

**Comment by ABA2396** [comment]
#7329 fixed
还没进公测和正式版
