### ISSUE TITLE
自动肉鸽的“自动识别干员及练度”似乎不准确（？）也没有使用助战

### ISSUE THREAD

**Issue by wlz-remake** [MaaAssistantArknights/MaaAssistantArknights#7288]
### 说说你遇到的问题？

（萌新博士，刚玩一个星期orz）
maa选开局干员在如下图情况时会选临时招募的三星预备干员，我的干员强度（例如薇薇安那、塑心）还不如这些临时招募的三星预备干员吗？
有时候拿到辅助招募券时，maa既不选塑心也不选临时招募的三星预备干员，而是选了波登可，这个干员有什么特别之处吗？
还有我已经勾选了“开局干员使用助战”及“可以使用非好友助战”，为什么开局干员从来没见过maa主动打开选择助战呢？（我手动点进去它倒自己会选）

开局选近卫：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105090141/546fa85f-14fb-4f5f-9f40-c6335f2871f3)

开局选辅助：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105090141/5d9b47fb-ded3-41cc-b903-8020c46f355f)

maa设置：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105090141/f45a9163-0f47-45b7-afbe-33c708c568d9)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105090141/5f28625e-7d97-4608-927f-685c7a1dda78)

**Comment by zzyyyl** [comment]
你也没指定开局干员啊

**Comment by zzyyyl** [comment]
> 我的干员强度（例如薇薇安那、塑心）还不如这些临时招募的三星预备干员吗？

根据经验，节省希望用于招募主C更有用

**Comment by github123520** [comment]
解释一下，你的开局干员（单个）那下面的框框，写上你希望借的角色中文名就好，比如羽毛笔/棘刺 写一个就行
