### ISSUE TITLE
無法連接adb

### ISSUE THREAD

**Issue by saunpcnaye** [MaaAssistantArknights/MaaAssistantArknights#7291]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

顯示無法連接與嘗試重開ADB伺服器 不知目前問題出在哪

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13335243/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13335244/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108626172/8b71bbd0-2cae-4dc1-8f72-f366878ffe62)

### 还有别的吗？

win11系統 雷電9

**Comment by Donate684** [comment]
ADB enabled in settings?

Or use emulator when adb enabled by default like mumu12

**Comment by ABA2396** [comment]
看日志没看出来啥问题，是第一次用吗？有试过在任务管理器里手动结束adb.exe和重启电脑吗？都不行的话在关闭模拟器和adb的情况下点一下设置里的强制替换adb之后再试试
