### ISSUE TITLE
繁中服 最新內測版刷理智卡住

### ISSUE THREAD

**Issue by vonnoq** [MaaAssistantArknights/MaaAssistantArknights#7292]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

繁中服會因為還沒有實裝連戰系統而卡住五分鐘左右才進行下次戰鬥

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13339360/asst.log)

### 还有别的吗？

Core Version: v4.26.2-alpha.1.d137.gf817944d8

**Comment by ABA2396** [comment]
#7294 fixed
