### ISSUE TITLE
Ubuntu 部署求助

### ISSUE THREAD

**Issue by TJJ120635** [MaaAssistantArknights/MaaAssistantArknights#7295]
### 说说你遇到的问题？

我有一台 Ubuntu 的迷你主机用作服务器，想要装个 MAA 平时自动跑一跑。在官网文档提到有[Linux模拟器的支持](https://maa.plus/docs/1.5-Linux%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.html)，但是不确定选哪个比较合适。
想问一下有没有有经验的大佬，用的是AVD还是Waydroid来跑方舟？另外是不是需要开 Xserver 图形界面连进服务器里才能操作。

**Comment by cccccccccooool** [comment]
大佬配置好了吗？我现在也想配置一个，但是不知道没有图形页面的服务器能不能也能用

**Comment by TJJ120635** [comment]
补充一下，对于上班党来说，可能最方便的方式还是用手机连电脑，然后电脑上挂MAA。Ubuntu的方式太折腾了hhh
[官方教程，非常简单](https://maa.plus/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.html#%E2%9A%99%EF%B8%8F-%E6%89%8B%E6%9C%BA%E3%80%81%E5%B9%B3%E6%9D%BF%E7%AD%89%E5%AE%9E%E4%BD%93%E5%AE%89%E5%8D%93%E8%AE%BE%E5%A4%87)

**Comment by cccccccccooool** [comment]
> > 大佬配置好了吗？我现在也想配置一个，但是不知道没有图形页面的服务器能不能也能用
> 
> 在 Ubuntu 上装了一个 redroid，但是最近没空继续弄了。有一个麻烦的问题是，我不能访问家里的Ubuntu，要用frp穿透到公网服务器上再访问。但是我的xrdp容易出现黑屏问题，和Ubuntu原生的桌面环境有冲突。用向日葵远程控制也会有一直加载进不去的问题。 所以我的解决方案就是简单粗暴地买一根hdmi线插到显示器上，然后远程家里的台式机，再用Windows远程rdp桌面控制Ubuntu。
> 
> 如果没有图形界面的话你可以装一个xrdp来远程控制，然后再装一个gdm3之类的桌面环境，可以参考 [这个](https://qiita.com/QiitaYkuyo/items/c8e700da451e894e5d53#%E3%82%B3%E3%83%B3%E3%82%B9%E3%83%88%E3%83%A9%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3)。但是关键在于你可能要开一个虚拟显示器，相当于假装给电脑插上一个显示器，不然就算有xrdp也没有屏幕可以给你访问。[这个](https://qiita.com/QiitaYkuyo/items/816e6440793a3f3a1a14#---) 教程里有讲。 我按照教程一步步走但是复现失败了，可能跟Ubuntu本身的桌面冲突有关。
> 
> @cccccccccooool

多谢大佬了，周末我去试试看看
