### ISSUE TITLE
基建换班问题

### ISSUE THREAD

**Issue by tsctsc6** [MaaAssistantArknights/MaaAssistantArknights#7297]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

总是无法把红云、卡达、稀音、龙舌兰、卡夫卡安排进设施

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13344877/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13344879/gui.log)
2023/11/14中午

### 还有别的吗？

模拟器：Bluestacks 5.13.0.6501 P64
操作系统：Windows10
我感觉，我猜，是不是我干员太多，导致没划到？因为我手动安排时，感觉目标干员在挺后面的

**Comment by ABA2396** [comment]
能来个选人过程的视频吗，怀疑是所选干员在最后导致触底反弹选中的错误的干员

**Comment by zzyyyl** [comment]
嗯？ #6960 不是修了吗

**Comment by ABA2396** [comment]
> 嗯？ #6960 不是修了吗

那次加了延时但没啥用，要么看看这个怎么判断有没有到底） a17f156d78150f471114c408d890e76d3afa15b1

**Comment by tsctsc6** [comment]
并没有选择错误干员，而是没有选

**Comment by ABA2396** [comment]
> 并没有选择错误干员，而是没有选

要的是选的过程，看日志是选了错误的干员，然后在复查的时候发现选错了又给取消掉了

**Comment by ABA2396** [comment]
因为干员太多选不到是不可能的，我全干员都能滑到底，感觉就是你的这几个人排在最后一页，然后在触底回弹的地方提前截图导致点到的和识别到的不是一个人，这个问题前几天的内测版修过，如果有时间的话可以测测更新现在的内测版之后能不能正常跑

**Comment by tsctsc6** [comment]
等过了一个基建换班的周期，我再看看

**Comment by tsctsc6** [comment]
我发现，好像无论如何，maa都会在复查的时候，觉得选错了；
我录了个视频，在这个[仓库](https://github.com/tsctsc6/maa-debug-video/tree/video)的Release

**Comment by ABA2396** [comment]
照理来说换班之前是会先切换到技能页选好人然后再切换到工作状态页确认
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f00dd334-4387-410e-85c9-5419be78288e)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/03827fbd-5442-49d0-87aa-81570e704386)
这边好像是没识别到技能直接stop了，但这玩意都一年没改了）
cc @MistEO

**Comment by tsctsc6** [comment]
奇怪，最近两次都挺正常

**Comment by tsctsc6** [comment]
奇怪，今晚又漏选干员了
我又录了个视频，在这个[仓库](https://github.com/tsctsc6/maa-debug-video/tree/video)的Release，video2.0中
新的日志：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13403736/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13403738/gui.log)

**Comment by tsctsc6** [comment]
我发现很有可能是我模拟器开启了2560x1440分辨率，现在改为1920x1080后，就没有问题了。
