### ISSUE TITLE
肉鸽模式 酒商运输队 总会将一个干员放到没有格子的地方

### ISSUE THREAD

**Issue by LengmoAngel** [MaaAssistantArknights/MaaAssistantArknights#730]
肉鸽模式酒商运输队 总会将一个干员放到没有格子的地方

![image](https://user-images.githubusercontent.com/74064769/171942728-30eee692-0f4e-4887-b17e-a1bec7e83951.png)

没定位到日志 等会再找找

**Comment by LengmoAngel** [comment]
看画面就算梅尔被移动到左上角

**Comment by HansBug** [comment]
对，我这边也遇见过，把梓兰一个劲往左上没有部署位（非地面也非高台）的地方拖。
一开始以为AI是不是学会偏爆炸无人机了，看了几遍才发现不对劲 🤣

**Comment by MistEO** [comment]
所以日志呢（

你不用定位的直接把那个巨大的 log 发上来就好了（太大的话可能要压缩一下

**Comment by Yjun233** [comment]
我也遇到了一样的问题，顺便还遇到了关卡结算后最后一样物品（目击到的有招募券、战术道具）不拾取而直接退出的问题
用的是雷电模拟器国际版4.0
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8837098/asst.zip)

**Comment by LengmoAngel** [comment]
[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8838097/asst.-.zip)

**Comment by MistEO** [comment]
问题原因是有两张地图都叫 “酒商运输队”。。。不知道咋整了，没法判断 orz

**Comment by MistEO** [comment]
fixed
