### ISSUE TITLE
肉鸽关卡布置错误

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#7300]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽待宰的兽群逆天阵型布置，不知道是哪里出了问题

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13348209/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13348217/gui.log)

### 截图

<img width="960" alt="2023-11-14" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90097743/3e212898-6293-4bb6-8024-cfe8ec5c7aa8">
<img width="960" alt="2023-11-14" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90097743/e43b144c-8f7d-4a88-90a2-b4da66d79424">

**Comment by aliezlo** [comment]
看文件里面有对(6,3)格子的布置，不知道为什么没放

**Comment by aliezlo** [comment]
另外开肉鸽时，maa也错误地将保全识别成了肉鸽，感觉可能是笔记本没插电导致的运行问题

**Comment by status102** [comment]
什么是把保全识别成了肉鸽？详细讲讲？

**Comment by pxinz** [comment]
同问题
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120245073/b3f33495-65b3-495b-babb-a8039c9a2e31)

**Comment by Lancarus** [comment]
fixed in #8447
