### ISSUE TITLE
刷龙门币时会卡在这个界面，需要手动点击画圈的按钮才能进入下一步

### ISSUE THREAD

**Issue by DashBeiqing** [MaaAssistantArknights/MaaAssistantArknights#731]
刷龙门币时会卡在这个界面，需要手动点击画圈的按钮才能进入下一步

![截图](https://user-images.githubusercontent.com/68020610/171976703-7500e36d-51c6-426b-b766-25e000698c83.jpg)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8836862/asst.log)

**Comment by Zzzzzzouhang** [comment]
我也碰到了相同的情况，关卡选择选龙门币，模拟器是夜神7.0.2.6，分辨率2560*1440

**Comment by ABA2396** [comment]
已经修了，还没发包
