### ISSUE TITLE
基建选了未进驻情况下菲亚梅塔找不到人

### ISSUE THREAD

**Issue by WSMTBG** [MaaAssistantArknights/MaaAssistantArknights#7311]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

菲亚梅塔和巫恋换心情的时候因为我之前检查基建的时候点了未进驻，就一直没找到巫恋，能增加一个检查是否选择了未进驻的流程吗

### 日志文件

应该不用吧...

### 截图

![屏幕截图 2023-11-15 173006](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32087250/1b2d82a9-a28a-4e8f-a9d7-3032108a98c6)

### 还有别的吗？

MAA版本号: v4.26.2-alpha.1.d142.geb7439b4f
模拟器：蓝叠国际版5.10.220.1008 N64

**Comment by Constrat** [comment]
MAA won't work as expected if the user touches.

**Comment by WSMTBG** [comment]
> MAA won't work as expected if the user touches.

I touched in the middle of the day，the MAA runs automatically in the afternoon

**Comment by status102** [comment]
需要日志

**Comment by status102** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/b96cce93-40e6-456f-b145-1811f9e6e28d)
