### ISSUE TITLE
助战刷好感问题

### ISSUE THREAD

**Issue by CCFF00** [MaaAssistantArknights/MaaAssistantArknights#7312]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

助战里面有风笛，导致maa无法选取第一位风笛的位置，直接卡死

### 日志文件

太大了

**Comment by Constrat** [comment]
Too big is not an excuse. You can:
- compress it
- edit the file and leave only the the timestamp of when the issue happens.
