### ISSUE TITLE
用MAA刷肉鸽每次必招募阿米娅

### ISSUE THREAD

**Issue by miaomiaonei** [MaaAssistantArknights/MaaAssistantArknights#7314]
### 说说你遇到的问题？

我的阿米娅练度很烂的说，就是好奇这是制作组特意设置的么(单纯好奇问问)

**Comment by zzyyyl** [comment]
水月好像有，其他没有

**Comment by SherkeyXD** [comment]
按理说练度不高会降低权重的啊（

**Comment by miaomiaonei** [comment]
> 按理说练度不高会降低权重的啊（

但是它真的，哪怕希望数足够招小羊它也会去招阿米娅，它真的我哭死

**Comment by zzyyyl** [comment]
有没有日志

**Comment by Constrat** [comment]
No logs, no help.
Reopen if you need more help (with logs :))
