### ISSUE TITLE
肉鸽没有自动开叔叔技能

### ISSUE THREAD

**Issue by Zincccccck** [MaaAssistantArknights/MaaAssistantArknights#7316]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在这一关其他人的技能都会自动好了就开，只有叔叔的没动过，可能是没有识别出来，也算是个无关紧要的bug吧，单纯反映一下

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13365058/asst.zip)
问题应该是在几分钟前吧，没过多久

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94158391/2bd4f0a6-a285-4f93-9d9b-0c54322e3ae8

![微信截图_20231115211344](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94158391/ce2168ff-b853-4298-8f39-44785de14b2f)

**Comment by Constrat** [comment]
In this map it doesn't really seem like an issue. If the map is cleared correctly, it's cleared. End of story.

**Comment by Lancarus** [comment]
#6582
