### ISSUE TITLE
干员识别错漏

### ISSUE THREAD

**Issue by islcyr** [MaaAssistantArknights/MaaAssistantArknights#7317]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

多次尝试干员识别功能，漏识别浊心斯卡蒂。
同时若识别干员后再次进行识别，仅识别最后一页干员，不会自动返回第一页。

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13367288/debug.zip)
debug文件的最后可以找到识别的记录

### 截图

五张debug/oper，一张结果截图

![2023-11-16_00-43-11-610_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61719225/5dd8af42-0af0-4e77-8993-5de6c121b1e6)
![2023-11-16_00-43-12-948_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61719225/22ebfb6b-4740-4fbf-bd4f-e9d136909c49)
![2023-11-16_00-43-40-571_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61719225/9a3b575e-ebc8-4b42-87c3-a65fb7843f52)
![2023-11-16_00-43-41-829_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61719225/fe18ea15-e3ed-47ca-b514-dabf4fc15922)
![2023-11-16_00-43-43-065_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61719225/0a9bea8f-fcc4-47a7-867a-e9d715fa5480)

<img width="400" alt="result" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61719225/8066f2db-d514-45fe-b375-5329022fe5e7">

### 还有别的吗？

模拟器：mumu模拟器12  V3.6.2(2305)

**Comment by Constrat** [comment]
Do not favourite operators. Unfortunately MAA can't distinguish characters correctly when the Favourite flag is displayed

**Comment by islcyr** [comment]
> Do not favourite operators. Unfortunately MAA can't distinguish characters correctly when the Favourite flag is displayed

那为什么只有这一个识别不出来呢，其他的标记的干员也有识别。同时考虑到这个标记功能也是可能比较通用的，后续考不考虑添加这方面的适配呢？

**Comment by Constrat** [comment]
Now It has been fixed for skadi alter. 
Why she's the only one? Because her name is long at the OCR algorithm thinks the favourite mark is a Japanese character.

**Comment by islcyr** [comment]
> Now It has been fixed for skadi alter. Why she's the only one? Because her name is long at the OCR algorithm thinks the favourite mark is a Japanese character.
OK 感谢
