### ISSUE TITLE
想询问一下，MAA特定作业中，SKIP剧情的代码怎么写？

### ISSUE THREAD

**Issue by github123520** [MaaAssistantArknights/MaaAssistantArknights#7319]
### 说说你遇到的问题？

似乎有些作业有skip 有的没有，点开json文件发现没有相关代码，真诚求教，感谢！

**Comment by ABA2396** [comment]
我记得开头剧情是自动跳过的，过程中的剧情不行吧？

**Comment by status102** [comment]
> 我记得开头剧情是自动跳过的，过程中的剧情不行吧？

过程中也行（比如教学关），但是是纯代码，不涉及作业部分。如果遇到无法跳过，希望能提供log跟时间

**Comment by status102** [comment]
如果不跳过，可能是bug，需要提供log
