### ISSUE TITLE
MAA 的界面元素在触屏下无法正常滚动

### ISSUE THREAD

**Issue by undefined-moe** [MaaAssistantArknights/MaaAssistantArknights#7320]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

系统版本 Windows 11（Microsoft Windows [版本 10.0.22621.2428]）

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29992205/15502159-4c31-4d1c-9be6-a842b8730f80)

使用触屏无法翻动右侧说明，使用触摸板与鼠标滚轮正常。
（目测是触屏滑动操作被当成鼠标点击拖动操作处理了

### 日志文件

N/A

**Comment by Cryolitia** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/5356ad94396e10e2b9c9900e9a2d5959228597bb/src/MaaWpfGui/Views/UI/CopilotView.xaml#L328

Just for clear, what's the reason to set it disabled? CC @ABA2396
