### ISSUE TITLE
MUMU12启动任意操作后跳转到模拟的应用商店

### ISSUE THREAD

**Issue by AwenSun4261** [MaaAssistantArknights/MaaAssistantArknights#7323]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在Mumu12模拟器版本版本号V3.5.12（1972）下，连接模拟器正常，但是无论选中任何操作，都会自动跳转到mumu的应用商店

### 日志文件

2023-11-16 14:00后
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13372975/debug.zip)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/4925f4f0-701a-4850-abab-07c56b2046a2)

**Comment by ABA2396** [comment]
根据 mumu 的说法，3.5.8 以上的版本已经支持后台保活运行。然而，需要将游戏页面置于顶部才能正常工作。虽然可以在分屏模式下进行操作，但如果游戏页面不在顶部，adb 将无法识别游戏页面并自动停止点击操作。只有切换回游戏界面后，才能正常继续执行 maa 的流程。

然而，根据日志显示，maa 一直能够识别到页面上的返回按钮并点击。如果方舟在前台还是跳转到模拟器的应用商店，可能是由于版本原因。mumu 那边在 3.6.4 版本下测试正常运行。如果愿意，可以尝试更新模拟器。

另外，如果愿意，可以留下联系方式。mumu 的技术人员将会与你联系，详细了解问题的情况，并进行远程排查。
