### ISSUE TITLE
基建换班，在宿舍换班时，在心情tag下，一直向后滑动无法完成干员选择。

### ISSUE THREAD

**Issue by BGLX** [MaaAssistantArknights/MaaAssistantArknights#7324]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建换班，在宿舍换班时，在心情tag下，一直向后滑动无法完成干员选择。
按道理，应该是信赖度填充空位才对。

### 日志文件

17：20左右
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13375567/debug.zip)

**Comment by mikage3miya** [comment]
日服，出现类似情况，进入信赖度部分后无法完成选择，会卡在选择第4人后的如下画面
![Screenshot_2023 11 18_15 05 14 642](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/68894391/a41f141e-11fe-4a9f-830a-56813c52be15)


[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13399169/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13399171/gui.log)
