### ISSUE TITLE
自动肉鸽开局选择干员第二次招募时，不计算第一页干员

### ISSUE THREAD

**Issue by wlz-remake** [MaaAssistantArknights/MaaAssistantArknights#7325]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我将阿米娅和能天使设置为了key干员，但发现当她们在初始招募的第二次招募中时，第二次招募总是不选择她们
（第一个视频里没选阿米娅，第二个视频没选能天使）
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105090141/5189fa23-b28f-4a3b-a063-6d2eb9df847b
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105090141/2145054b-7a84-489e-bc7a-bb642bfb1272

查看日志发现第二次招募时的每页干员识别列表和优先级比较错位，优先级比较没有计算到第一页干员

异常情况：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105090141/c4fb40f9-daa8-4d5f-b775-259ebdee2ffa)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105090141/1dda121d-d749-4984-a9a0-4c81144f2990)

正常情况：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105090141/9fecc79a-3be1-43ed-b7c8-730d1a8a4302)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105090141/230dd86e-f9fd-449c-b5b8-c0fd533add2c)

### 日志文件

[2023-11-16 17:53:49.774] 不招募能天使
[2023-11-16 17:59:58.666] 不招募阿米娅
[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13376526/asst.-.zip)

**Comment by Lancarus** [comment]
请在高级设置-开局干员里面填写需要开局的干预
