### ISSUE TITLE
feat: SSS#2 YostarEN implementation

### ISSUE THREAD

**Issue by dbtigalima** [MaaAssistantArknights/MaaAssistantArknights#7327]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Theres an issue when trying to copilot SSS on YostarEN server.
Its alway says "Recognition Error or JSON does not support this." This SSS copilot issue never happen before even if I using copilot outside from the resources files (at least for me).
Theres no issue when trying copilot for other stage, but this issues occured when I trying SSS.

### Log files

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13378372/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13378375/asst.log)

### Screenshots

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151040880/b6260744-5b7c-4722-b24d-bbd9638aa59f

### Anthing else?

[SSS_雷神工业测试平台_浊蒂版.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13378386/SSS_._.json)
Emulator : Bluestack 5.13, Android 11
OS : Windows 11

**Comment by Manicsteiner** [comment]
New stages are not supported yet.
If you have the ability, you can add the name translation of the new stages to "SSSStageNameOCR" in ```/resource/global/YoStarEN/resource/tasks.json``` so that it can be supported. Or you need to wait for the contributor who usually handles such issues to handle it.

**Comment by Constrat** [comment]
Yeah no shit. Unfortunately SSS adaptation takes time and patience as especially for EN there's no easy way to do it, unless I test all 16 stage names and HOPE that there are no duplicates.
Today I didn't have time. I should be able to adapt this during the weekend.

If you want to help, you can send a screenshot of the different 16 stage names, so that I can start implementing them for the OcrReplace
