### ISSUE TITLE
在普通关卡的结算界面，开始肉鸽任务，MAA会反复尝试识别，卡在这里

### ISSUE THREAD

**Issue by CharlesChou73** [MaaAssistantArknights/MaaAssistantArknights#7330]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

先用了自动刷理智打ZT-8，刷到一半点了停止，想着马桶上拿手机打一会，这样代理打完后游戏会停在结算界面

但是我刷森空岛刷得太开心忘记打开游戏了

厕所回来让maa直接开始肉鸽任务，就一直卡在这个结算界面了

看日志maa在反复截图尝试识别，和结算界面斗智斗勇

### 日志文件

大概今天16点开始的，卡了半个小时才发现

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13389265/asst.zip)

### 截图

好多截图，都一样的，挑了一张上传
![2023-11-17_16-00-32-790_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16950543/d1e13f8f-92f8-407e-b114-2142f00243f1)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16950543/e55949d2-9ace-4d39-864e-ce2b762d9c48)

### 还有别的吗？

蓝叠国际版

**Comment by Lancarus** [comment]
请在主页、肉鸽主页、肉鸽大地图启动肉鸽功能
