### ISSUE TITLE
点击链接报错

### ISSUE THREAD

**Issue by sz-w** [MaaAssistantArknights/MaaAssistantArknights#7333]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

点作业分享，还有报错弹窗的三个链接都会报错，关闭报错窗口后几秒会关掉maa

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13396847/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13396848/gui.log)
重新解压的，只有这一点的日志

### 截图

![截图](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/82028802/9feb087d-f9b6-426a-8178-2151cfacd006)

### 还有别的吗？

mumu12
win10
实体机云电脑

**Comment by ABA2396** [comment]
在Windows默认应用里面要选下默认的浏览器

**Comment by SherkeyXD** [comment]
能不能检测默认浏览器啊 能的话写一个检测得了）

**Comment by ABA2396** [comment]
是没有默认浏览器，你咋检测啊
