### ISSUE TITLE
游戏资源更新失败

### ISSUE THREAD

**Issue by andykeppel** [MaaAssistantArknights/MaaAssistantArknights#7337]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

游戏资源更新失败，卡在编写索引这一步。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13398792/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13398793/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62137704/a15f517a-3d02-4a77-a859-b55d5cb6d684)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62137704/ab199547-3e43-44e5-b38a-649cb7b6fe91)

**Comment by onlookerLi** [comment]
你好 请问是如何解决的

**Comment by ABA2396** [comment]
> 你好 请问是如何解决的

如果正式版v4.27.0之后还有问题那就是别的原因，带上日志去发个新的issue
