### ISSUE TITLE
自定义基建计划找不到thrm-ex

### ISSUE THREAD

**Issue by why002** [MaaAssistantArknights/MaaAssistantArknights#7344]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自定义基建计划找不到thrm-ex
我看它找了四遍了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13399898/asst.log)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13399899/gui.log)
17:31:00

### 截图

![MuMu12-20231118-173110](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55909876/54e1b10b-7188-435c-ab3b-39c2f63dd7fd)

**Comment by ABA2396** [comment]
不知道为啥识别成 HRM-EX 了，之后再瞅瞅
