### ISSUE TITLE
萨米肉鸽抗干扰为0时反复尝试竖着走

### ISSUE THREAD

**Issue by Arklapp** [MaaAssistantArknights/MaaAssistantArknights#7345]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在抗干扰指数为0且商店处于不同线路上需要消耗抗干扰指数进入时，maa会无限尝试进入商店，导致maa一直卡在这一步无法继续正常进行肉鸽。在手动进入下一个节点后，maa退出了当次探索。

### 日志文件

问题出现于11-18 18:03:59~11-18 18:27:27

[asst_gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13400040/asst_gui.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151367961/9a716f26-3057-4343-aed5-95b68291b095)

**Comment by SherkeyXD** [comment]
Duplicate of #7241

**Comment by SherkeyXD** [comment]
Duplicate of #7241

> 打板子引起的bug，全面勘察打在了纵向节点上，一般情况下没有抗干扰识别不到纵向的节点类型
