### ISSUE TITLE
水月肉鸽无法初始化

### ISSUE THREAD

**Issue by undefined-moe** [MaaAssistantArknights/MaaAssistantArknights#7348]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29992205/487cd851-d554-482c-a9ea-e6c990b6bcee)
设备分辨率 1080x1920，水月肉鸽卡在选择难度页

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13401507/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13401508/gui.log)

**Comment by Constrat** [comment]
1. No logs
2. Choose a difficulty, it's not that hard
3. Fixed the problem.
