### ISSUE TITLE
自动编队重岳三技能错选成二技能

### ISSUE THREAD

**Issue by broken-paint** [MaaAssistantArknights/MaaAssistantArknights#7349]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

rt 

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13402022/asst.log)

**Comment by SherkeyXD** [comment]
这个好像是技能描述太长导致三技能被挤下去了

**Comment by zzyyyl** [comment]
老老老问题了，也许可以考虑在选三技能的时候先来个滑动操作
