### ISSUE TITLE
萨米肉鸽第五层最后卡住

### ISSUE THREAD

**Issue by teikazusa** [MaaAssistantArknights/MaaAssistantArknights#7352]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

（之前描述不清楚，更新了下问题）萨米肉鸽走到“事件: 走过萨米的臂膀”之后，调整密文板之后会将近卡上二十分钟再进入最终boss关。问题表现为“点进密文板-滑动一阵-退出”就退回选关不动了。问题大概复现过三四次，第一次自己主动停止了，后面几次都是将近卡上二十分钟之后，才进入最终boss关。

### 日志文件

gui log时间点
[2023-11-19 07:25:47.265] <1><> 事件: 走过萨米的臂膀
[2023-11-19 09:58:04.978] <1><> 事件: 走过萨米的臂膀
[2023-11-19 16:23:55.323] <1><> 事件: 走过萨米的臂膀
[asst&gui logs.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13404834/asst.gui.logs.zip)

### 截图

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/148912688/a92cb37b-db87-4172-b439-6c4b2d400d33)
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/148912688/9e4ebc14-859d-4c1b-ac79-6754ee605a77)
![3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/148912688/416f9822-a0ca-4a04-896f-d274b8a35d92)

### 还有别的吗？

模拟器：雷电9.0.62 Minitouch
Windows 11
MAA Core Version: v4.27.0-beta.1.d026.g5dfa38eb5

**Comment by ABA2396** [comment]
cc @Lancarus

**Comment by ImYiFeng** [comment]
一模一样的bug
