### ISSUE TITLE
自动战斗一直点击查看折光

### ISSUE THREAD

**Issue by jmdpress** [MaaAssistantArknights/MaaAssistantArknights#7353]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动战斗时一直重复点击查看折光信息

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13404617/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13404619/gui.log)

**Comment by jmdpress** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/28856643/c63e0e18-c39e-4a74-ba1c-6ab211465445)

**Comment by ABA2396** [comment]
怪，为啥识别成 `折光Z` 了
