### ISSUE TITLE
萨米肉鸽经常打完一次战斗就不动了

### ISSUE THREAD

**Issue by elegia0130** [MaaAssistantArknights/MaaAssistantArknights#7355]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

每一次运行完一次战斗节点以后就会卡在战利品或者地图页面一动不动，根本无法使用。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13407744/gui.log)

### 还有别的吗？

使用的是mumu模拟器12

**Comment by status102** [comment]
缺少asst.log
