### ISSUE TITLE
希望可以自定义StartUp任务的超时时间

### ISSUE THREAD

**Issue by WYH2004-MC** [MaaAssistantArknights/MaaAssistantArknights#7356]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在模拟器刚启动游戏的时候可能会导致启动时间过长，导致出现StartUp任务因为超时而失败，然后后面所有的步骤都跑不下去

### 有什么好的想法？

希望可以自定义开始唤醒这个任务的超时时间，或者在进入游戏前一直循环运行开始唤醒的步骤。

**Comment by status102** [comment]
用MAA启动的模拟器吗

**Comment by Constrat** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/7aeb8d72-990e-4348-99d9-3d3b7fa556f7)
You already have this option:

**Comment by WYH2004-MC** [comment]
> 用MAA启动的模拟器吗，是的话，可以在启动设置里面设置等待模拟器启动的时间。

并不是，可能是我描述的不清楚，我的意思是，在模拟器已经启动，但是游戏还没启动的情况下。
开始运行脚步，第一步是“开始唤醒”（startup），但是由于游戏加载速度过慢，会导致脚步在第一步的时候因为超时而跳过，这样后面的步骤都跑不下去了
我希望可以自定义“开始唤醒”这一步骤的超时时间

**Comment by ABA2396** [comment]
看到模拟器路径下面那个附加命令了吗？那个就是用来启动应用的，比如 mumu 第一个实例的 b服 就是 `-p com.hypergryph.arknights.bilibili -v 0`，第二个实例的官服就是 `-p com.hypergryph.arknights -v 1` 如果你不会找这个附加命令，那就新建一个应用的快捷方式，然后把这个快捷方式的路径填入模拟器路径，比如 `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\多开1.lnk` 

参考 [自动启动多开模拟器](https://maa.plus/docs/1.1-%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.html#%E8%87%AA%E5%8A%A8%E5%90%AF%E5%8A%A8%E5%A4%9A%E5%BC%80%E6%A8%A1%E6%8B%9F%E5%99%A8)
