### ISSUE TITLE
自动检测连接后使ADB路径变作错误路径

### ISSUE THREAD

**Issue by archer0079** [MaaAssistantArknights/MaaAssistantArknights#7358]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

连接设置页面，正常adb路径为
\Program Files\BlueStacks_nxt_cn\HD-Adb.exe
勾选自动连接后，一旦点击一键长草页面中的Link start！按键
adb路径立刻变为
\Program Files\BlueStacks_nxt_cn\ . \HD-Adb.exe
这个点莫名其妙的就出现在adb路径中
然后就导致连接失败

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13412625/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13412640/gui.log)
最后一次时间点

### 截图

点击link start前的路径
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/68234534/3ea7339c-41c8-421d-95aa-f02090d506bf)
点击后的路径
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/68234534/a183f9b2-9a90-4d8f-9589-dddd9a2f7b74)

### 还有别的吗？

蓝叠模拟器（Hyper-V）
每次端口都会变化
现在要想连接每次我都需要手动修改一次端口

**Comment by ABA2396** [comment]
\ . \是当前目录，加不加没影响的啊

**Comment by ABA2396** [comment]
看你的端口一直在变，是hyperv版本的蓝叠？
[1.2-常见问题.html#蓝叠模拟器每次启动端口号都不一样-hyper-v](https://maa.plus/docs/1.2-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7-hyper-v)

**Comment by archer0079** [comment]
对，Bluestacks.Config.Keyword和Bluestacks.Config.Path都指定过了

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/9b5dc8fc-804a-406e-a6fb-c44bf5f2be60)
但下面看这个端口号并没有改变，确定Bluestacks.Config.Keyword填对了吗？如果是多开核心或者一起开过别的，Bluestacks.Config.Keyword的值得去找对应的模拟器的key。
该文件的话要在maa关闭的时候改，要是改完保存之后启动maa文件又变回去的话就是改的内容格式错了

**Comment by archer0079** [comment]
解决了，感谢
