### ISSUE TITLE
操作实体手机时添加手机唤醒的步骤

### ISSUE THREAD

**Issue by Nchyn** [MaaAssistantArknights/MaaAssistantArknights#736]
如标题，我的设备为xzp，在自动操作过程中无法由休眠模式自动唤醒，需要手动按一下电源键或scrcpy 右键唤醒，希望可以在MAA任务startup中添加唤醒手机的步骤，感谢您

**Comment by ntgmc** [comment]
maa不建议使用实体手机，实体手机建议使用安卓apk脚本（比较方便）
