### ISSUE TITLE
界面设置-重要信息弹出系统通知显示异常

### ISSUE THREAD

**Issue by xiamocc** [MaaAssistantArknights/MaaAssistantArknights#7360]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在界面设置中勾选重要信息弹出系统通知后,弹出的测试消息会有一个当前显示器不包含任务栏的一个遮罩.并在遮罩右下显示通知,关闭通知后遮罩会一起消失,非测试通知也是同样的问题
版本信息如下
UI Version: DEBUG VERSION
Core Version: v4.27.0-beta.1.d026.g5dfa38eb5

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13416513/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13416514/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29580333/2f1c4071-7176-47c4-bea2-3c51c9052e1c)

**Comment by ABA2396** [comment]
这玩意是在系统通知不支持的时候才会显示这个格式的通知，提供一下windows相关信息

**Comment by xiamocc** [comment]
版本	Windows 11 专业版
版本	23H2
安装日期	‎2023/‎10/‎2
操作系统版本	22631.2715
体验	Windows Feature Experience Pack 1000.22677.1000.0

这是我的windows版本

**Comment by xiamocc** [comment]
> 这玩意是在系统通知不支持的时候才会显示这个格式的通知，提供一下windows相关信息

版本	Windows 11 专业版
版本	23H2
安装日期	‎2023/‎10/‎2
操作系统版本	22631.2715
体验	Windows Feature Experience Pack 1000.22677.1000.0

这是我的windows版本信息,还需要其他什么具体信息呢?

**Comment by ABA2396** [comment]
感觉23H2出了很多问题，等下看看是不是这个原因

**Comment by xiamocc** [comment]
Core Version: v4.27.0
今天更新到4.27已经解决这个问题
