### ISSUE TITLE
「开机自动启动」勾选后仍然无效

### ISSUE THREAD

**Issue by Szyoo** [MaaAssistantArknights/MaaAssistantArknights#7362]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我曾经将MAA所在文件清空，并重新下载MAA的最新压缩包在同样文件路径解压过一次
在那之后即使我勾选了「开机自动启动MAA」，下一次开机时也并未自启
（在这之前是正常的，之所以重新解压是因为资源更新一直失败并且不知道怎么卸载）

有时候还会看到勾选的「开机自动启动MAA」变为未勾选的状态
（可能是MAA更新后就会变回未勾选，暂时没能够确认，但是确实很多次了）

另外无论重启前后都能在任务管理器的启动选项卡看到MAA.exe为启用状态，但是确实从来都没有启动过。。。（见截图）

（顺带一提，也就该问题发生的差不多的时候，电脑上安装的度盘在开机的时候总是提示“系统限制了文件目录的读写权限，请重新安装”，度盘和MAA都在D盘，会不会是这个原因？虽然不清楚为什么会这样就是了。。）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13417409/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13417411/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/37945314/310bb37f-96d8-475d-a438-3bc2e98719f8)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/37945314/a491ac73-8cd3-4909-a996-5b6c72ad3b76)

### 还有别的吗？

模拟器NOX安卓9 64位7.0.5.9
Windows 11 22H2
还需要什么吗？

**Comment by ABA2396** [comment]
> 有时候还会看到勾选的「开机自动启动MAA」变为未勾选的状态

这个是因为启动时候的判断条件写错了） 在 ec6cdecb1eb83dabe5fb863ba90b7ba380c9deb8 已经改了，和启动失败不是一个原因。

Program Files 目录是受到保护的系统目录，普通用户没有写入权限，除非是软件的自己选的默认路径，尽量不要把其他软件装在这里，或者用管理员权限启动。

可以 win+r 打开运行窗输入 shell:Startup 打开文件目录，看看里面有没有 `MAA_{一堆数字字母}.exe`，有的话应该就是可以开机自启的了

**Comment by Szyoo** [comment]
确实是Program Files权限的问题，移动至其他路径解决了
（虽然不清楚为什么之前一直没问题）
谢谢大佬的回复，已解决
