### ISSUE TITLE
繁中服“退出明日方舟”无效的问题

### ISSUE THREAD

**Issue by Karl3302** [MaaAssistantArknights/MaaAssistantArknights#7363]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

**问题描述:**
繁中服 _退出明日方舟_ 动作无效, 包括:
- _一键长草_ 界面的 _完成后退出明日方舟_ 动作
- _设置 - 定时执行_ 中 _强制定时启动_ 触发的重启游戏动作

**bug定位;**
resource/config.json 文件(86行) stop语句中:
`grep -E '(packageName|Activities)=[^\\n]+rknights' 2>/dev/null`
由于[^\\n]排除字符n, 繁中服明日方舟包名为 tw.txwy.**and**.arknights 含n, 从而被排除
导致繁中服stop语句无法抓取明日方舟包名. 

另, 其他服由于包名不含字符n所以只有繁中服出现此bug.
- 简中服 com.hypergryph.arknights
- 英服 com.YoStarEN.Arknights 
- 日服 com.YoStarJP.Arknights
(字符A的问题我看最新文件已经改成rknights了所以就不再赘述)

### 日志文件

问题输出在asst.log 48行
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13418626/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13418628/gui.log)

**Comment by ABA2396** [comment]
是改了，但是是在 v4.26.2 第一次上了，耐不住你是 v4.26.1 啊

**Comment by ABA2396** [comment]
更新下公测版或者等正式版推送吧

**Comment by Karl3302** [comment]
> 是改了，但是是在 v4.26.2 第一次上了，耐不住你是 v4.26.1 啊

4.27.0-beta.1和4.26.1是同样的问题, 目前线上的代码也是.

**Comment by ABA2396** [comment]
再发下asst.log

**Comment by ABA2396** [comment]
那个是json字符串，实际跑的就是\n

**Comment by Karl3302** [comment]
这个是今天更新的 4.27.0 的asst.log:
报错在最下面的780行
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13438156/asst.log)

还是与之前同样的问题: 无法退出繁中版明日方舟
bug位置也一样:
resource/config.json 文件(86行) stop语句中,
`grep -E '(packageName|Activities)=[^\\n]+rknights' 2>/dev/null`
这个传递给adb的grep命令中的正则表达式[^\\n]排除了字符n, 导致stop语句无法抓取繁中版明日方舟包名(繁中版包名tw.txwy.**and**.arknights含有字符n).

config.json的确是一个json文件, 但里面定义了stop的具体实现, 也就是从一系列通过adb发送给安卓的命令. 
其中关键步骤就是从安卓返回的字段中通过grep抓取到明日方舟的包名. 

**[^\\n]** 表达匹配除了"\\"和“n”以外任何字符的合集, 当初排除它们的理由你们肯定有自己的考量. 
但因为繁中版明日方舟的包名含有“n”所以被排除在外, 导致stop无论如何都抓不到繁中版明日方舟的包名.

目前我这边自己把 **[^\\n]** 改成 **[^\\]** 之后就可以实现关闭繁中版明日方舟了. 
4.26.1, 4.27.0-beta.1 和 4.27.0 均是如此. 
但当初排除字符n肯定是有理由的, 具体如何修复这个bug并不导致新的bug还需你们找到当初排除字符n的理由.

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f614665e-6168-4387-8d11-e1b2686518eb)
转义之后传的就是\n，排除的不是n是\n

**Comment by Karl3302** [comment]
> ![image](https://user-images.githubusercontent.com/99072975/284902587-f614665e-6168-4387-8d11-e1b2686518eb.png) 转义之后传的就是\n，排除的不是n是\n

log输出里是[^\n], 因为在打印log时没有经过文本化处理, 把第一个\当成了控制符. 
但实际执行的是[^\\n].

**Comment by Karl3302** [comment]
> 所以试试看改成 [^\n]能跑吗？这个原来就是为了排除换行的

嗯, 是可以的.

**Comment by ABA2396** [comment]
1c9b648fa3055a9994121093b084f88865d06a22 cc @AnnAngela

**Comment by AnnAngela** [comment]
> [1c9b648](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1c9b648fa3055a9994121093b084f88865d06a22) cc @AnnAngela

LGTM
