### ISSUE TITLE
会客室可以自选进驻干员范围

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#7364]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

众所周知，会客室的效率是与进驻干员的基建技能和等级挂钩的，但是maa在放人的时候不会考虑等级，导致它天天放精0的四爷，效率相当低。

### 有什么好的想法？

会客室可以自选进驻干员范围，通过修改json之类的来实现

**Comment by ABA2396** [comment]
效率是和星级和技能有关啊？现在有判断技能等级，你要是觉得是技能效率识别错了那发个asst.log看看

**Comment by aliezlo** [comment]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13424576/asst.zip)

**Comment by aliezlo** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13424800/asst.log)
这个是只有基建的版本

**Comment by aliezlo** [comment]
哎它好像又没放四爷，等放了再发
