### ISSUE TITLE
不懂就问，自定义排班表怎么写可以跳过进驻某一干员

### ISSUE THREAD

**Issue by KuiPer-LTW** [MaaAssistantArknights/MaaAssistantArknights#7365]
### 说说你遇到的问题？

问题：我想让菲亚梅塔进驻到最下一层的宿舍
           但大多数情况菲亚梅塔的心情是最低的，所以就直接被进驻到第一层宿舍了

原因：每层宿舍我都安排了宿管，第一层的最高效率宿管负责默认进驻的四个心情最低的干员
           但菲亚梅塔不吃心情加成，所以占位置了

如何在json文件里加入跳过进驻某一干员的字段，我认真的查看过自定义排班教程，没找到

**Comment by ABA2396** [comment]
按现在的逻辑没办法，要么只能写死全部宿舍

**Comment by KuiPer-LTW** [comment]
寄，那我写成建议了

**Comment by KuiPer-LTW** [comment]
> 按现在的逻辑没办法，要么只能写死全部宿舍

寄，那我写成建议了
