### ISSUE TITLE
希望未来能加入自设基建换班阵容的功能

### ISSUE THREAD

**Issue by MigdalBavel** [MaaAssistantArknights/MaaAssistantArknights#737]
这样既不用费心基建收益计算的逻辑，又可以让基建收益最大化。目前自带的换班逻辑换出来的和自己平时还是差异蛮大的，说实话不是特殊情况没时间上线的话不太好选择用自动换班，而换了之后也会和后续的循环发生冲突。

软件很好用，已star，非常感谢。

**Comment by MistEO** [comment]
说实话大部分用户手换的不如现在的效率高，而且我们已经在计划做全局最优解了。所以不会去支持手动换班
