### ISSUE TITLE
游戏资源反复更新失败

### ISSUE THREAD

**Issue by Imipenem1265** [MaaAssistantArknights/MaaAssistantArknights#7372]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

从自动更新至v4.27.0-beta.1直到Nov 22（今天），期间一直显示：
"游戏资源更新失败，请稍后尝试“
PS：刷理智、自动公招等可用，但是在开启合约时（21日下午至22日凌晨）无法导引至感谢庆典活动关卡”崔林特尔梅之金“。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13432872/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13432873/gui.log)

### 截图

<img width="600" alt="屏幕截图 2023-11-22 101701" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143390409/9dedf555-fdaf-4cdd-9a0e-ebc23730a2a7">

### 还有别的吗？

OS：Windows 10 22H2
模拟器：MuMu 12 v3.6.4

**Comment by onlookerLi** [comment]
你好 请问是如何解决的
