### ISSUE TITLE
疑似maa导致鼠标左右键无反应

### ISSUE THREAD

**Issue by setsuan233** [MaaAssistantArknights/MaaAssistantArknights#7373]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在maa中鼠标左右键正常使用；在桌面左右键无反应，任务栏同样。关闭maa后暂时恢复正常，稍后左右键又无反应。只能通过物理重启按钮，重启电脑解决。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13433573/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13433574/asst.log)

### 截图

https://www.aliyundrive.com/s/MQzf6wqUKfP
由于视频较大无法上传，故使用云盘。手机拍屏请见谅。

### 还有别的吗？

系统：Windows 10 企业版 LTSC       21H2
模拟器：mumu模拟器       V3.6.4(2333)

**Comment by cr941131** [comment]
+1，确实存在这个问题，不过，可以通过打开任务管理器重启资源管理器来解决

**Comment by ABA2396** [comment]
没搞懂，是最近更新之后出现的吗

**Comment by setsuan233** [comment]
> 没搞懂，是最近更新之后出现的吗

不清楚，目前为止就出现了这一次，很神奇。

**Comment by ABA2396** [comment]
~~太抽象了，感觉是windows的问题~~

**Comment by ABA2396** [comment]
都没见多少人反馈，会不会是windows新补丁的问题）
