### ISSUE TITLE
4.27 Macos版 无法连接

### ISSUE THREAD

**Issue by prodrodc** [MaaAssistantArknights/MaaAssistantArknights#7376]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MACOS卸载4.23后重新安装最新版4.27，无法连接（卡在正在连接……）
连接地址设置没有问题，playcover也升级到了最新版。
换回4.23后使用正常

### 日志文件

没有

**Comment by Constrat** [comment]
No log. No help.
