### ISSUE TITLE
对“连战次数更改为1”这个功能增加开关

### ISSUE THREAD

**Issue by gxy12345** [MaaAssistantArknights/MaaAssistantArknights#7377]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

能够理解这个改动是为了避免刷不完理智的情况出现，但是对于1-7这种低理智消耗的图，使用连战会显著提高效率，目前也没有任何手段能够让MAA在开启连战的情况下进行战斗

### 有什么好的想法？

增加一个开关来控制

**Comment by SherkeyXD** [comment]
`使用连战会显著提高效率` 是怎么个说法

**Comment by ABA2396** [comment]
> `使用连战会显著提高效率` 是怎么个说法

每天能省个两分钟的样子

**Comment by trhei** [comment]
> `使用连战会显著提高效率` 是怎么个说法

连战会跳过结算界面和重复点击开始战斗而变成执行设置的次数完毕后一起结算，这样的话就减少了1局一次频繁出现结算画面和重新点击关卡开始战斗的过程，这对于低体力的1-7来说能省不少时间

**Comment by Deo-777** [comment]
+1，但我直接启用旧版了- -
另外连战还可以减少联网次数，对网卡的地方还有额外提升。

**Comment by MisterCoBen** [comment]
也许可以在作战开始前直接自动计算并选择合适的连续作战次数，这样应该还能节省计算资源

**Comment by status102** [comment]
Duplicate of #7196

**Comment by status102** [comment]
> 也许可以在作战开始前直接自动计算并选择合适的连续作战次数，这样应该还能节省计算资源

- #7196 已经提出了，但是没人写

**Comment by ZauberViolino** [comment]
> +1，但我直接启用旧版了- - 另外连战还可以减少联网次数，对网卡的地方还有额外提升。

连战每次战斗结束之后会连一次网。公孙长乐的视频有提到过联网确认理智剩余量。我刚刚可能网络不好，手动刷到3/3结束的时候等了会网络。

**Comment by dreamcaptorzyl** [comment]
<img width="1794" alt="continuous_fight" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131790327/2e170337-2cf3-4321-9616-657c4c8b49e3">

5年菜鷄PM畫了個流程圖，還挺希望幫到開發組的，如果有需要的話可以隨時聯係我！
