### ISSUE TITLE
连续作战可以调整更改

### ISSUE THREAD

**Issue by yinyang-234** [MaaAssistantArknights/MaaAssistantArknights#7378]
### 在提问之前...
/

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

游戏里红票关每次不知道为什么系统默认连续代理次数，导致maa识别理智不够，跳过刷理智的任务

### 有什么好的想法？

增设一步识别连续代理次数，最大效益理智消耗

**Comment by SherkeyXD** [comment]
#7196

**Comment by status102** [comment]
最新的正式版会将连续战斗次数调整为1
