### ISSUE TITLE
肉鸽编队时澄闪重复点击导致未选中

### ISSUE THREAD

**Issue by wlz-remake** [MaaAssistantArknights/MaaAssistantArknights#7379]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105090141/63938e60-f4d6-48d0-9631-e15aa90c3919

见视频，澄闪没选中

### 日志文件

[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13445157/asst.-.zip)
[gui - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13445158/gui.-.log)
2023-11-23 08:08:08发生

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105090141/48dddeaf-a496-489d-a977-d76faa1707f4)

**Comment by ABA2396** [comment]
看日志确实点了两次
```
[2023-11-23 08:08:21.265][TRC][Px5de8][Tx2694] minitouch click: (701, 685)
[2023-11-23 08:08:21.366][TRC][Px5de8][Tx2694] minitouch click: (706, 701)
```
