### ISSUE TITLE
增加对肉鸽月度小队的支持

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#738]
希望增加对月度小队的支持。在现有的情况下，以月度小队的方式开始肉鸽，会在确认小队成员之后收藏品那里卡住。即使手动点击屏幕跳转到肉鸽关卡的界面，也不会选择关卡开始战斗。如果能增加对月度小队的支持，保证肉鸽正常识别关卡开始战斗，哪怕只是按照普通肉鸽的方式推进剧情也比现在强。

**Comment by zhongfly** [comment]
常规肉鸽的打法很可能打不过，那么就得每月更新对应的打法……
我的建议是直接去B站找作业抄，一个月也就一次

**Comment by xiaoweiXX** [comment]
> 常规肉鸽的打法很可能打不过，那么就得每月更新对应的打法…… 我的建议是直接去B站找作业抄，一个月也就一次 6月的部分关卡挂机作业 https://www.bilibili.com/video/BV1S5411D7nZ

不是说对打法特别优化，而是起码别在开始的地方卡住
