### ISSUE TITLE
自定义基建找不到暗锁

### ISSUE THREAD

**Issue by why002** [MaaAssistantArknights/MaaAssistantArknights#7385]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我又来了，这次它找不到暗锁了（我觉得可能是我的问题了）

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13451497/gui.log)
[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13451530/asst.-.zip)

### 截图

![MuMu12-20231123-231117](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55909876/79bfc1f5-eada-4e78-904d-cc667285aaea)

**Comment by ABA2396** [comment]
有没有一种可能是“暗索”不是“暗锁”
