### ISSUE TITLE
请问能否支持手机连电脑，然后电脑控制手机？

### ISSUE THREAD

**Issue by loliSAKURA** [MaaAssistantArknights/MaaAssistantArknights#7386]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我想在公司上挂MAA，但是公司电脑性能不行同时还需要办公。性能上不能跑模拟器。

### 有什么好的想法？

通过数据线（或者无线）adb连接电脑，实现电脑maa程序来控制手机玩。从原理来说应该和adb控制模拟器差不多

**Comment by SherkeyXD** [comment]
https://maa.plus/docs/1.3-%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.html#%E2%9A%99%EF%B8%8F-%E6%89%8B%E6%9C%BA%E3%80%81%E5%B9%B3%E6%9D%BF%E7%AD%89%E5%AE%9E%E4%BD%93%E5%AE%89%E5%8D%93%E8%AE%BE%E5%A4%87
