### ISSUE TITLE
肉鸽挂机过程中maa程序会突然关闭

### ISSUE THREAD

**Issue by yindoukiad** [MaaAssistantArknights/MaaAssistantArknights#7387]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Core Version: v4.27.1-alpha.1.d010.g496e990ae，此版本及上个内测版本更新后出现的问题，主要表现为，夜间傀影肉鸽挂机过程中突然maa程序闪退，白天发现游戏界面停在某一界面但无卡死表现，maa程序已关闭，估计maa运行时间为3-4小时左右，因maa关闭，无法准确预估发生事件

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13454377/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13454485/asst.zip)
[asst (2).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13454487/asst.2.zip)
请把asst.2.zip改为asst.z01后解压。发生时间约为11-22至11-24凌晨0-7点时间范围内，具体因夜间挂机，无法准确预估

### 还有别的吗？

mumu模拟器12，win10，2个版本前的内测版使用过程中并未有此表现，只在4点游戏掉线后表现为不能重连

**Comment by yindoukiad** [comment]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13459513/asst.zip)
重新上传了asst，最后一次肉鸽中闪退了

**Comment by NianGuu** [comment]
+1,在挂傀影肉鸽的时候会突然随机挑选一次结算界面闪退，前天晚上打一把就退了，大早上起床一看血压都高了

**Comment by horror-proton** [comment]
> +1,在挂傀影肉鸽的时候会突然随机挑选一次结算界面闪退，前天晚上打一把就退了，大早上起床一看血压都高了

有保留日志吗

**Comment by horror-proton** [comment]
看了下日志, 感觉这块比较可疑 @status102 
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/496e990ae15a82b787f5f638a41a7cc17c815d12/src/MaaCore/Task/Roguelike/RoguelikeSettlementTaskPlugin.cpp#L106-L108

**Comment by NianGuu** [comment]
> > +1,在挂傀影肉鸽的时候会突然随机挑选一次结算界面闪退，前天晚上打一把就退了，大早上起床一看血压都高了
> 
> 有保留日志吗

早上急着挂日常没留，晚上留意一下

**Comment by status102** [comment]
4d9e089 fixed
