### ISSUE TITLE
maa 無法正確領取獎勵·

### ISSUE THREAD

**Issue by CoolCoolWind** [MaaAssistantArknights/MaaAssistantArknights#7389]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如題，在maa表示已完成后 在上綫，發現每天獎勵和每周獎勵一個都沒領取
最後停止畫面
![Snipaste_2023-11-24_17-47-15](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/91040d98-f9c8-490b-8ae5-44af77ef9771)
報告已完成
![Snipaste_2023-11-24_17-47-02](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/41d9b3fe-ff19-4fc5-b922-a1a48c63df97)
獎勵未領取
![Snipaste_2023-11-24_17-50-40](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/8d219af0-3508-4ff9-b3d3-c4b0d806a247)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13457656/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13457661/gui.log)

### 还有别的吗？

系統Win10,bluestack 5.13，。還有如何在手動輸入關卡模式下，讓maa自動打當前/上次的關卡？

**Comment by ABA2396** [comment]
> 系統Win10,bluestack 5.13，。還有如何在手動輸入關卡模式下，讓maa自動打當前/上次的關卡？

留空

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/1d896ebe-3751-44d1-9d9c-f46fabfcb953)
这个勾了吗？
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/887e1e59-0071-4a3a-b2ac-d3aa5252ffb8)
看传给core的参数里两个都没选

**Comment by CoolCoolWind** [comment]
![PixPin_2023-11-28_11-26-19](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/23a8a71e-885b-4d48-92ee-f077c09342f5)

**Comment by CoolCoolWind** [comment]
![Screenshot_2023 12 06_22 46 38 920](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/28a3b9a7-5721-4171-89c4-abcf1b6ff82c)
周常

**Comment by ABA2396** [comment]
这个模板图似乎糊很多，试试看把\resource\global\txwy\resource\template\ReceiveAward.png删了能不能跑？

**Comment by CoolCoolWind** [comment]
![ReceiveAward](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/cbe0625c-6617-4837-b7ff-ba5dc0535de8)
我自己弄了一張都不可以

**Comment by CoolCoolWind** [comment]
而且\resource\global\txwy\resource\template\ReceiveAward.png删了后連日常獎勵都識別不到

**Comment by Constrat** [comment]
You have to take a 1280x720 screen
Crop the receive all button (please do a decent crop) and replace the file in txwy/resources/tenplate

**Comment by Constrat** [comment]
If you give a moment I can do it for you.

**Comment by CoolCoolWind** [comment]
![Screenshot_2023 12 10_20 49 44 725](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/5f58d1d4-f010-4435-ad2d-5edd7887b7ec)
the screenshot using the function of Bluestacks

**Comment by CoolCoolWind** [comment]
![ReceiveAward](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/1c17746d-7857-45e2-b333-05794aa12f2d)
I make this photo and it works.

**Comment by Constrat** [comment]
![ReceiveReward](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/dd7e1312-a56a-43ae-93a9-a34d17ac10b7)
We'll use this one.
