### ISSUE TITLE
肉鸽在诡异行商那里卡住

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#739]
使用雷电模拟器。肉鸽选择尽量往前打，第一层诡异行商能够进行投资，这次运气好，存了8个源石锭，又买了一个藏品（瞄了一眼好像是玩具士兵，按源石锭数量加攻速）。进入第二层的时候两个选项，一个是不期而遇一个是作战，选择了不期而遇；之后紧随又一个诡异行商，进入之后便卡住不动了。我手动点击离开诡异行商，然后软件就自动退出当前的肉鸽重新开了一把。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8837663/asst.log)

**Comment by MistEO** [comment]
大概是啥样的界面卡住了，有截图么_(:з」∠)_

**Comment by xiaoweiXX** [comment]
> 大概是啥样的界面卡住了，有截图么_(:з」∠)_

莫得。我猜是两个行商隔得太近了导致出了什么原因卡住，MAA也没有啥提示
