### ISSUE TITLE
会客室进驻错误

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#7390]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用自定义基建，会客室选择自动填充，它放了精0的四爷进去

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13457869/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13457871/gui.log)

### 截图

<img width="960" alt="2023-11-24 (1)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90097743/fa35b2e5-bfdd-456e-a1ba-de647f336b4b">
<img width="960" alt="2023-11-24 (2)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90097743/30a2811a-f9ad-4db4-a29c-ba9d486479ce">

### 还有别的吗？

蓝叠

**Comment by aliezlo** [comment]
<img width="960" alt="2023-11-24 (3)" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90097743/cc396e61-6b8a-4a10-9ea6-0ac11134d2be">

**Comment by zzyyyl** [comment]
那应该放啥（

**Comment by Constrat** [comment]
What is the issue? It's auto filled, so MAA will choose the best combo. Ines and Vigil have the highest % in RR.
