### ISSUE TITLE
肉鸽烧开水自选难度

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#7392]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在的烧开水会自动选择N15难度，但很多时候（比如打角标）不想打N15

### 有什么好的想法？

可以让maa在烧热水之前自动记录当前的难度，在0难度烧完之后回到之前记录的难度

**Comment by zzyyyl** [comment]
Duplicate of #6494
