### ISSUE TITLE
能否实现一个“回到主页”任务

### ISSUE THREAD

**Issue by hsyhhssyy** [MaaAssistantArknights/MaaAssistantArknights#7401]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

产生这个需求的原因是我在使用远控功能的时候，我发现如果远端想要获取当前状态，获取截图的时候，截图的位置往往停留在最后一个完成任务的界面，一般来说是领取周常的页面。

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/5977110/1d99a808-00b4-4f98-b4ee-909d633aa664)

就好像上面，我自己写的一个远控MAA的网站，我做了一个查看任务结果的功能，但是每次只能面对周常任务界面发呆。

我问了一下玛丽，能否配置一个结束后脚本，实现在LinkStart任务结束后，回到主界面的功能。这样在远端发出LinkStart任务后，后续的截图任务可以比较直观的看到LinkStart的结果。
但是玛丽说这个不好做，可能需要做到Core里。

但是我C++不太熟，怕改出内存泄露，所以看看各位大佬有什么想法。

### 有什么好的想法？

目前直观的方案就是去MAACore里，加一个新的任务类型“回到主页”。

**Comment by status102** [comment]
不知道遥控的任务链受不受wpf的限制，如果不受限的话，追加一个StartUp任务应该就行

**Comment by hsyhhssyy** [comment]
> 不知道遥控的任务链受不受wpf的限制，如果不受限的话，追加一个StartUp任务应该就行

StartUp一定最终停在主页是吗？那可以确实通过追加一个StartUp来实现，我试一下。

**Comment by status102** [comment]
至少目前是，不过这种属于未定义的东西随时可能会被更改（StartUp这个行为应该不会改就是了

**Comment by hsyhhssyy** [comment]
> 至少目前是，不过这种属于未定义的东西随时可能会被更改（StartUp这个行为应该不会改就是了

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/5977110/a2695749-9be2-423d-b3cf-80f7e105e50d)

我试了一下，在周常任务领取页面，启动一个StartUp，会直接结束，不会回到主页。

**Comment by status102** [comment]
那我记错了（倒

**Comment by Constrat** [comment]
@status102 wouldn't this just the generic "Go home" task that is used in between tasks?
For example, after infrastructure -> visit friends, will exit the base and pass through the main menu. 
Same thing happens if you are in a completely different location (for example an event page) if you choose the base infrastructure task it will regressively go back until it's in the terminal and go in the base after that.

**Comment by status102** [comment]
@Constrat yes, we need that part of task chain. But I think we may need a new type of task for various simple tasks like this or make a free Gacha per day when it is available

**Comment by zzyyyl** [comment]
`ReturnButton` ？

**Comment by Constrat** [comment]
Technically spamming just the ReturnButton could easily work for almost every interface, except very specific ones.
Something like this could work?
```c
if (isTerminal)
    stop;

while(returnbutton is true) {
    clickReturn;
    if (isreturn)
        continue
    else
       break
}    
```

**Comment by hsyhhssyy** [comment]
我发现，LinkStart如果最后一个任务是收取奖励，并且是勾选了收取邮件的话，最终会停留在首页，因此至少远控LinkStart目前是可以实现“最终停留在首页以供截图的”。

因此目前暂时没有特别的场景需要这个功能了。可能该需求的优先级可以下调，甚至于先关闭。

**Comment by ABA2396** [comment]
回到主页是想看什么信息？ ~~我感觉森空岛提供的api可能更全面~~

**Comment by hsyhhssyy** [comment]
> 回到主页是想看什么信息？ ~我感觉森空岛提供的api可能更全面~

其实没什么信息要看，目前我这边的场景下，就是单纯从用户观感上来说，截图时停在领取奖励的页面，或者关卡结束的页面，不太好看。

**Comment by ABA2396** [comment]
最后这个获取截图是怎么做的？其实传给core一个自定义任务 `ReturnButton ` 应该就可以了

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/03e7fe40-1ae3-42af-a658-4a7da11e50a3)
