### ISSUE TITLE
日服基建功能无法识别斥罪、麒麟R夜刀、火龙S黑角、淬羽赫默等

### ISSUE THREAD

**Issue by Xiaoritu** [MaaAssistantArknights/MaaAssistantArknights#7402]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

看到之前也有类似的box识别功能无法识别出斥罪的反馈，一开始推测是ペナンス比斥罪宽两个字的原因造成。孤星版本我修改了基建换班文件，加入了缪尔赛思、淬羽赫默排班，使用时无法识别出斥罪、麒麟R夜刀、火龙S黑角、淬羽赫默几个干员，一直向后翻找。最后根据外服适配攻略下载了相关软件，截图并尝试修改MAA\resource\global\YoStarJP\resource\tasks.json，在淬羽赫默后加入一行"roi": [
         （main.py截出的四个数字)后重新运行maa，显示数据损坏。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13466497/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13466498/gui.log)
11-26 16：57

**Comment by Constrat** [comment]
That's not how it should be done. There can only be one "roi" field in the json per object.
I'm guessing the issue is in the `"CharsNameOcrReplace"`. The roi is directly inherited from the chinese tasks.json.
The main solutions are using regex to allow different options as masks. 
For example this is what was made for Silverash, allowing a flexible recognition result.
```json
            [
                "シルバーアッシュ",
                "银灰"
            ],
            [
                "ル.*ーアッ.*シュ",
                "银灰"
            ],
            [
                "レ.*ーアッ.*シュ",
                "银灰"
            ],
```

**Comment by Constrat** [comment]
Also, I've took a look at the asst.log and I couldn't find any ocrReplace issues.
If you have a specific timestamp of when it happened, I can try giving it a better look.

**Comment by Xiaoritu** [comment]
尝试修改为：
                "淬羽サイレ.*ス",
                "淬羽赫默"
            ],
            [
                ".*サイレ.*ス",
                "淬羽赫默"
            ],
            [
                "卒羽サイレ.*ス",
                "淬羽赫默"
运行无效，时间点大概在这个时候开始找不到干员[2023-11-26 16:55:32.698][INF][Pxef0][Tx2b20]

**Comment by Constrat** [comment]
Oh, I now understand the issue. 
All the alter operators are identified as the "normal" operators because there are no "starting" and "ending" characters for the regex.

**Comment by Constrat** [comment]
@Xiaoritu I've added a fix.
Try it WITHOUT your changes. If it works: good, there is nothing else to do.
If it doesn't, check again the logs and modify the regex accordingly. This time it will take effect because it will not misrecognize the ALTERS as non-ALTERS
