### ISSUE TITLE
公招无稀有tag放弃刷新建议

### ISSUE THREAD

**Issue by theAIzx** [MaaAssistantArknights/MaaAssistantArknights#7403]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

可否出一个选项，如果此次公招无四星及以上和支援机械的tag，则设定为1小时无tag然后放弃招募刷新tag

**Comment by Constrat** [comment]
This doesn't make sense. It would just be a waste of recruitment permits, LMD and certificates.

**Comment by SherkeyXD** [comment]
Some may do this to get a quick refresh of tags —— mostly when they have plenty of  recruitment permits.

**Comment by Constrat** [comment]
> Some may do this to get a quick refresh of tags —— mostly when they have plenty of recruitment permits.

If you have a lot of permits, I can understand but it's just a waste... Just use the expedited plans.
If you always put 7:40 hours , 9hours you will always go negative with the recruit permits. It will just be a huge niche, with the possibility of user error (forgot that he had the skip on and loses all the permits)

**Comment by SherkeyXD** [comment]
Maybe we can add it as a tool ?

**Comment by TiSpH** [comment]
> > Some may do this to get a quick refresh of tags —— mostly when they have plenty of recruitment permits.
> 
> If you have a lot of permits, I can understand but it's just a waste... Just use the expedited plans. If you always put 7:40 hours, 9hours you will always go negative with the recruit permits. It will just be a huge niche, with the possibility of user error (forgot that he had the skip on and loses all the permits)

It's not a waste for those who want to recruit 1 star operators quickly. There is an achievement "L2＆C3" that requires potential 5 Lancet-2 and Castle-3.

**Comment by ABA2396** [comment]
3星拉1小时也是能出小车的，我重装小车满潜里面4个都是1小时无词条出的
