### ISSUE TITLE
MAA V4.27.0 无法在基建会客室中识别伊内斯

### ISSUE THREAD

**Issue by DrAlkahest** [MaaAssistantArknights/MaaAssistantArknights#7406]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

通过一图流自定义基建排班表执行自动基建替换时，MAA 无法在会客室选人界面识别到伊内斯。左上角筛选模式为“技能”，已尝试过改为其他筛选模式依然无法识别。选人菜单拉到底重复三次后进行了手动纠正，下一个任务可以正常继续。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13469369/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13469370/gui.log)
发生时间 11-26 21:31:37

### 截图

![F6EfJ9RHgD](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/152129014/fe1c1001-f86b-4988-ba67-0137a5a12e64)

### 还有别的吗？

蓝叠模拟器海外版 5.4.100.1026 N32

**Comment by ABA2396** [comment]
人叫伊内丝
