### ISSUE TITLE
尝试剿灭作战时卡在情报汇总界面，导致战斗及其他任务均出错

### ISSUE THREAD

**Issue by zhimian** [MaaAssistantArknights/MaaAssistantArknights#7408]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

剿灭作战时卡在了情报汇总界面，战斗以及后续任务均出错，手动点击退出情报汇总界面后任务正常

### 日志文件

时间点为2023-11-27 14:54:39.812，此时卡在情报汇总界面，后续任务均出错
[gui - Copy.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13470325/gui.-.Copy.zip)
[asst - Copy.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13470326/asst.-.Copy.zip)

### 截图

![QQ截图20231127150221](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/20293201/5570ddc8-ea1f-4d56-a840-fd7819cd3422)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/20293201/54b2b8e2-2fc0-431e-8cee-03e01f14353c)

**Comment by zzyyyl** [comment]
#3617
