### ISSUE TITLE
疑似因开启了mumu“动态调整帧率为10fps”帧率过低，模拟器置于后台时挂肉鸽出现下干员卡住、开技能卡住等无反应情况

### ISSUE THREAD

**Issue by HolaAsuka** [MaaAssistantArknights/MaaAssistantArknights#7411]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

mumu模拟器开启“动态调整帧率为10fps”，模拟器置于后台时肉鸽挂机可能会出现：下干员卡在选定朝向界面、完全不下干员、卡在开技能界面错误，从而导致战斗失败

尝试修改为“动态调整帧率为25fps”，模拟器置于后台，肉鸽挂机正常
推测是因为帧率太低导致判定or操作bug？能否添加个“检测模拟器最低帧率限制”之类的功能

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13470923/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13470924/asst.log)

### 截图

![QQ截图20231127151402](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/67731575/2efb32e0-2310-416e-8de6-a31c0f9650d2)

### 还有别的吗？

mumu v3.5.17

**Comment by ABA2396** [comment]
所以这个检测到有什么用（？） ~~自动战斗相关的一般都是要求60帧往上的~~

**Comment by HolaAsuka** [comment]
> 所以这个检测到有什么用（？） ~自动战斗相关的一般都是要求60帧往上的~

主要就是想有个判定终止或者提示低帧率运行会有bug什么的2333这个问题莫名其妙困扰我一个多月了，今天才想起来可能是后台低帧率模式的锅

**Comment by HolaAsuka** [comment]
> > 所以这个检测到有什么用（？） ~自动战斗相关的一般都是要求60帧往上的~
> 
> 我也觉得检测fps没必要，不如加个检测并跳出卡死状态的机制。 都用maa了，一般当然是挂在后台，低帧率运行很合理吧（

太痛了，挂了三天全是第一关卡死X(

**Comment by lengyanyu258** [comment]
在 `resource/task.json` 文件中有各种各样的 `preDelay`、`postDelay` 设置，有的延迟 200 毫秒，有的 2000 毫秒，比如：

```json
"BattleStartSimulation": {
    "action": "ClickSelf",
    "roi": [
        417,
        567,
        444,
        153
    ],
    "postDelay": 2000
},
...
"BattleUseOper": {
    "algorithm": "JustReturn",
    "preDelay": 150,
    "postDelay": 200,
    "Doc": "pre 是从点击干员，到干员信息弹出来等待的时间；post 是干员上场，到设置朝向之间等待的时间"
},
"BattleSwipeOper": {
    "algorithm": "JustReturn",
    "preDelay": 400,
    "postDelay": 100,
    "Doc": "pre 是将干员滑动到场上的 duration 系数；post 是设置干员朝向滑动的 duration",
    "specialParams": [
        400,
        100,
        2,
        0,
        100
    ],
    "specialParamsDoc": [
        "设置朝向时的滑动距离",
        "补偿距离上限",
        "滑动初速度（平均速度是固定的，初速度快末速度慢相当于一直减速）",
        "滑动末速度",
        "将干员滑动到场上的 最小滑动 duration"
    ]
},
```

当模拟器的帧数过低时，出现这种情况的原因可能是 `preDelay`、`postDelay` 的时间相对过短，使得操作失败。
解决方法是手动将 `preDelay`、`postDelay` 等值设置得更高，这样才能在低帧率下操作成功，当然实际的战斗中操作延迟就更大了，而且 MAA 每次更新都会覆盖 `task.json` 文件，你需要每次都重新调高好几个延迟的值，非常麻烦。
所以一劳永逸的解决办法就是

**Comment by HolaAsuka** [comment]
> 在 `resource/task.json` 文件中有各种各样的 `preDelay`、`postDelay` 设置，有的延迟 200 毫秒，有的 2000 毫秒，比如：
> 
> ```json
> "BattleStartSimulation": {
>     "action": "ClickSelf",
>     "roi": [
>         417,
>         567,
>         444,
>         153
>     ],
>     "postDelay": 2000
> },
> ...
> "BattleUseOper": {
>     "algorithm": "JustReturn",
>     "preDelay": 150,
>     "postDelay": 200,
>     "Doc": "pre 是从点击干员，到干员信息弹出来等待的时间；post 是干员上场，到设置朝向之间等待的时间"
> },
> "BattleSwipeOper": {
>     "algorithm": "JustReturn",
>     "preDelay": 400,
>     "postDelay": 100,
>     "Doc": "pre 是将干员滑动到场上的 duration 系数；post 是设置干员朝向滑动的 duration",
>     "specialParams": [
>         400,
>         100,
>         2,
>         0,
>         100
>     ],
>     "specialParamsDoc": [
>         "设置朝向时的滑动距离",
>         "补偿距离上限",
>         "滑动初速度（平均速度是固定的，初速度快末速度慢相当于一直减速）",
>         "滑动末速度",
>         "将干员滑动到场上的 最小滑动 duration"
>     ]
> },
> ```
> 
> 当模拟器的帧数过低时，出现这种情况的原因可能是 `preDelay`、`postDelay` 的时间相对过短，使得操作失败。
> 
> 解决方法是手动将 `preDelay`、`postDelay` 等值设置得更高，这样才能在低帧率下操作成功，当然实际的战斗中操作延迟就更大了，而且 MAA 每次更新都会覆盖 `task.json` 文件，你需要每次都重新调高好几个延迟的值，非常麻烦。
> 
> 所以一劳永逸的解决办法就是将模拟器的帧数设置成 30 fps.（也许需要在文档中提示不要将帧数设置过低）

感谢🐂🍺

**Comment by status102** [comment]
> 所以一劳永逸的解决办法就是将模拟器的帧数设置成 30 fps.（也许需要在文档中提示不要将帧数设

不太推荐手动修改这一块，会容易导致某些自动战斗作业的时间轴出现偏移。部分卡部署的情况在尝试解决，但是帧数过低（<30）可能造成的点击丢失始终不好解决
