### ISSUE TITLE
AUR 包无法正常使用

### ISSUE THREAD

**Issue by Eletary** [MaaAssistantArknights/MaaAssistantArknights#7415]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我按照指引，执行了如下指令：

```
yay -S maa-assistant-arknights
ln -s /usr/share/maa-assistant-arknights/Python/asst ~/MAA
sudo cp -r /usr/share/maa-assistant-arknights/Python/sample.py ~/MAA
vim ~/MAA/sample.py
python3 ~/MAA/sample.py
```

发现无论如何总是连接错误。

阅读 python 代码后，我发现 sample.py 将当前路径下的 `../..` 视为库文件所在路径，但是实际上在上述操作中，`../..` 为 `~`，显然不是正确的位置（实际上位于 `/usr/share/maa-assistant-arknights`）。

### 日志文件

~~没有成功运行，无此文件。~~

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13474727/asst.log)

**Comment by horror-proton** [comment]
这个 python 脚本只是一个例子, 并不适合日常使用, 如果日常使用的再装一个 maa-cli 比较方便
aur 的安装指导中提示了要编辑 sample.py 并设置正确的 path

**Comment by Eletary** [comment]
> 这个 python 脚本只是一个例子, 并不适合日常使用, 如果日常使用的再装一个 maa-cli 比较方便 aur 的安装指导中提示了要编辑 sample.py 并设置正确的 path

额，我没有对安装指导进行截图，可能是我漏了这一句

我知道这个py只是为了测试能否工作的。
