### ISSUE TITLE
集成文档 AsstAppendTask 中 Roguelike 任务没有烧水模式

### ISSUE THREAD

**Issue by NFLSCode** [MaaAssistantArknights/MaaAssistantArknights#7416]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

这个应该是要有的罢

### 日志文件

.

### 还有别的吗？

[文档链接](https://maa.plus/docs/3.1-%E9%9B%86%E6%88%90%E6%96%87%E6%A1%A3.html#asstappendtask)

**Comment by SherkeyXD** [comment]
因为是后来开发的所以就没写进去（
