### ISSUE TITLE
任务列表全选反选菜单有一个UI上的小问题

### ISSUE THREAD

**Issue by BTreeNewBee** [MaaAssistantArknights/MaaAssistantArknights#742]
似乎是反选取消没有取消选项卡的状态导致的
我甚至为此录了个gif
![maa](https://user-images.githubusercontent.com/18378664/172004058-118e825c-94b4-43a4-ac89-6e8dd8b610fd.gif)

**Comment by ABA2396** [comment]
这不是`全/反选`的问题，那是你之前点到过`刷理智`那一行复选框外的地方（就是平时用来拖动标签的地方），只是点了按钮让蓝色选中效果不显示了，但实际上选中的还是`刷理智`这一项，就算不是`全/反选`按钮，你点击`自动关机`/`停止`/`LinkStart!`/`吃理智药`/`吃石头`/`指定次数`/`关卡选择`等地方都能看到一样的现象

**Comment by MistEO** [comment]
> 这不是`全/反选`的问题，那是你之前点到过`刷理智`那一行复选框外的地方（就是平时用来拖动标签的地方），只是点了按钮让蓝色选中效果不显示了，但实际上选中的还是`刷理智`这一项，就算不是`全/反选`按钮，你点击`自动关机`/`停止`/`LinkStart!`/`吃理智药`/`吃石头`/`指定次数`/`关卡选择`等地方都能看到一样的现象

懂了

**Comment by qianxu2001** [comment]
> 

草，我到现在才知道原来是可以拖动的

**Comment by qianxu2001** [comment]
> 这不是`全/反选`的问题，那是你之前点到过`刷理智`那一行复选框外的地方（就是平时用来拖动标签的地方），只是点了按钮让蓝色选中效果不显示了，但实际上选中的还是`刷理智`这一项，就算不是`全/反选`按钮，你点击`自动关机`/`停止`/`LinkStart!`/`吃理智药`/`吃石头`/`指定次数`/`关卡选择`等地方都能看到一样的现象

草，我到现在才知道原来是可以拖动的

**Comment by soundofautumn** [comment]
这玩意原来可以拖的啊，建议在文档里加上（

**Comment by ABA2396** [comment]
> 这玩意原来可以拖的啊，建议在文档里加上（

详细介绍.md

`其他乱七八糟的说明：`

`- 主界面上要执行的任务，是可以拖动改变顺序的。同样设置中基建换班的顺序，也是可以拖动改变的。`
