### ISSUE TITLE
[JP]Auto combat on the Stultifera Navis stage doesn't work, possibly due to different UI.

### ISSUE THREAD

**Issue by nullyin** [MaaAssistantArknights/MaaAssistantArknights#7421]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

As the title suggests.

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13496577/asst.log)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13496580/gui.log)

### Screenshots

![Screenshot_2023 11 29_14 52 21 595](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/132637628/659d9874-9abc-4963-8b31-3ce621ab2829)

![Screenshot_2023 11 29_14 52 02 460](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/132637628/90e0062a-715f-4671-bd19-3b104a77bfc3)

![sn](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/132637628/f089d36b-68ff-4193-b218-529d77250609)

**Comment by ABA2396** [comment]
#7417

**Comment by ABA2396** [comment]
现在发一个内测版，如果急着用上的话过半个小时左右更新下内测版就行了

**Comment by Constrat** [comment]
No MaaRelease API has been modified. Need to manually update the version.

**Comment by nullyin** [comment]
感谢您的支持和配合。Thank you for your support.
