### ISSUE TITLE
EN服务器的愚人号无法用“上次/当前”

### ISSUE THREAD

**Issue by lirao** [MaaAssistantArknights/MaaAssistantArknights#7422]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

现在的en服愚人号复刻没法刷理智，应该是识别不出关卡开始的部分？
如果需要什么别的截图我可以提供

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13497602/asst.log)

### 截图

![Screenshot_2023 11 28_23 50 31 900](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6883412/81ffb0ab-7880-44e7-ad31-8eeb2ae175e5)

### 还有别的吗？

bluestacks
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6883412/089c8330-a1e7-47fc-9729-b197e1c05390)

**Comment by ABA2396** [comment]
#7421

**Comment by ABA2396** [comment]
可以先参考 #7417 改下，或者再等等）

**Comment by Constrat** [comment]
@ABA2396 it was correct closing it. I've already pushed the changes in MaaRelease.
