### ISSUE TITLE
萨米肉鸽时不时的会在商店页面卡住不操作了

### ISSUE THREAD

**Issue by aaaazdxzds** [MaaAssistantArknights/MaaAssistantArknights#7427]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA新版本萨米肉鸽时不时的会在商店页面卡住不操作了

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13500515/gui.log)
File size too big: 25 MB are allowed, 31 MB were attempted to upload
ass.log太大了
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13500529/asst.zip)

[2023-11-29 19:59:03.129] <1><> 关卡: 安全的角落
[2023-11-29 19:59:07.150] <1><> 事件: 科考站
问题出在这里，在这里卡住了，并且昨晚也卡住了

**Comment by aaaazdxzds** [comment]
雷电和mumu都会卡住

**Comment by TrellM** [comment]
MUMU9和12都卡住，只能自己操作，但是点到任何购买会自动取消退出
