### ISSUE TITLE
基建换干员人数减少或这没了

### ISSUE THREAD

**Issue by why002** [MaaAssistantArknights/MaaAssistantArknights#7429]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA找不齐三个干员，就会选择再找一次找不到的干员，然后找到了，就只选择那个找不到的干员了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13502260/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13502263/gui.log)

**Comment by leolbyy** [comment]
我也有碰到同样的问题。

**Comment by leolbyy** [comment]
已经merge了吗？今天还是碰到了这个问题

**Comment by ABA2396** [comment]
> 已经merge了吗？今天还是碰到了这个问题

什么版本

**Comment by leolbyy** [comment]
> > 已经merge了吗？今天还是碰到了这个问题
> 
> 什么版本

maaCore 5.3.1
<img width="422" alt="Screenshot 2024-06-09 at 20 07 38" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/80955869/b585cadf-880a-4b39-8fbc-501232993f8a">

**Comment by ABA2396** [comment]
正式版还没更新
