### ISSUE TITLE
刷理智的关卡选择：当前/上次 执行一次后卡死不再继续执行

### ISSUE THREAD

**Issue by SHMiris** [MaaAssistantArknights/MaaAssistantArknights#7431]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

11.30凌晨MAA进行游戏资源更新后出现此问题
刷理智模块，关卡选择为当前/上次，刷AP-5红票本，执行一次之后掉落识别正常，但是卡在行动结束界面，不执行下一步操作
两个120级账号均存在此问题
发现卡死之后点击停止按钮，一分钟以上无法停止，只能点击关闭按钮强制退出

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13503170/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13503174/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131992167/ddd96cb7-62c7-4a75-b55c-a3fa1cc57fe3)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131992167/066226aa-0cef-4e88-9f84-b185647e62ff)

### 还有别的吗？

雷电模拟器9.0.61，win 10家庭中文版，已排除网络问题

**Comment by ZauberViolino** [comment]
我刷1-7，从统计掉落到开始下一次大概间隔10分50秒。
相关Issue：#7430 #7432

**Comment by ZauberViolino** [comment]
另外，我这边尝试停止后没有卡死，只是等了十分钟罢了。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/67864718/39a08561-4657-4343-a6e3-410ff2aecf07)

**Comment by DogeCA** [comment]
测试内测、公测和稳定版都出现卡住问题，另外不止刷理智，其它功能完成后切换到下个功能都会卡住

**Comment by ABA2396** [comment]
企鹅物流503了，上报卡住了

**Comment by TimCrownie** [comment]
> 企鹅物流503了，上报卡住了

也就是说…取消“上报企鹅物流”能够解决？
不太清楚是否可行，先去测试一下。

**Comment by TimCrownie** [comment]
> > 企鹅物流503了，上报卡住了
> 
> 也就是说…取消“上报企鹅物流”能够解决？ 不太清楚是否可行，先去测试一下。

测试报告：
在取消“上报企鹅物流”后，“刷理智”任务可正常进行和完成。
