### ISSUE TITLE
运行刷理智时每关结束不会自动点击战斗完成界面

### ISSUE THREAD

**Issue by hu1m** [MaaAssistantArknights/MaaAssistantArknights#7432]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

运行刷理智时每关结束不会自动点击战斗完成界面，需要等待5-6分钟后才能进行下一步骤

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13503245/asst.zip)
2023-11-30 00:20

**Comment by TimCrownie** [comment]
我也有同样的问题，不过是在作战完成界面等待约30分钟后仍然无反应。
开始以为是alpha版漏洞就没有截图和保存日志，直接保留config后卸载安装release版；但是经过测试发现问题仍然存在。

**Comment by AjinKimxu** [comment]
+1，经测试会在公招结束后、结束代理的作战后、肉鸽进入商店后卡住

**Comment by ABA2396** [comment]
企鹅物流503了，上报卡住了

**Comment by TimCrownie** [comment]
> +1，经测试会在公招结束后、结束代理的作战后、肉鸽进入商店后卡住

在“刷理智”的高级设置中关闭“上传企鹅物流”后，刷理智和公招均恢复正常

**Comment by Constrat** [comment]
^ Solution

**Comment by bodayw** [comment]
是否考虑减少上报遇到网站 503 错误时的重试次数？从日志来看它重试了差不多 10 分钟，感觉并不必要。

**Comment by ABA2396** [comment]
写的有点问题，照理应该是在后台重试的，不影响到正常运行
