### ISSUE TITLE
"task:刷理智"中，首次运行后无法较正常的进行下一步操作

### ISSUE THREAD

**Issue by TimCrownie** [MaaAssistantArknights/MaaAssistantArknights#7434]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

设定任务：刷理智，指定次数1，关卡选择当前/上次
模拟器与MAA的连接正常，掉落识别上报正常；但停留在作战完成界面，未正常返回；此时点击MAA的停止按钮，会卡在“正在停止”。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13503819/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13503820/gui.log)

**Comment by TimCrownie** [comment]
_https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/7431#issuecomment-1832422320_
缓解方式：不使用自带的“上传企鹅物流”功能
**注意：仅进行了“刷理智”的测试。**

**Comment by AjinKimxu** [comment]
刷理智-设置-高级设置-取消勾选“上报企鹅物流”

**Comment by TimCrownie** [comment]
> 刷理智-设置-高级设置-取消勾选“上报企鹅物流”

解决了，不知道企鹅物流数据统计什么时候恢复
