### ISSUE TITLE
MAA Weblate 无法合并仓库

### ISSUE THREAD

**Issue by Zachary-Muadib** [MaaAssistantArknights/MaaAssistantArknights#7436]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Weblate 不能在更新仓库时合并上游更改。~~（五万年前出的问题了~~

### 日志文件

Rebasing (1/1)
Auto-merging src/MaaWpfGui/Views/UserControl/RoguelikeSettingsUserControl.xaml.cs
CONFLICT (content): Merge conflict in src/MaaWpfGui/Views/UserControl/RoguelikeSettingsUserControl.xaml.cs
Auto-merging src/MaaWpfGui/Views/UserControl/RoguelikeSettingsUserControl.xaml
CONFLICT (content): Merge conflict in src/MaaWpfGui/Views/UserControl/RoguelikeSettingsUserControl.xaml
Auto-merging src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
Auto-merging src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
CONFLICT (content): Merge conflict in src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
Auto-merging src/MaaWpfGui/Res/Localizations/zh-tw.xaml
Auto-merging src/MaaWpfGui/Res/Localizations/zh-cn.xaml
Auto-merging src/MaaWpfGui/Res/Localizations/ko-kr.xaml
Auto-merging src/MaaWpfGui/Res/Localizations/ja-jp.xaml
Auto-merging src/MaaWpfGui/Res/Localizations/en-us.xaml
Auto-merging src/MaaWpfGui/Main/AsstProxy.cs
Auto-merging src/MaaWpfGui/MaaWpfGui.csproj
CONFLICT (content): Merge conflict in src/MaaWpfGui/MaaWpfGui.csproj
Auto-merging src/MaaWpfGui/Helper/ToastNotification.cs
CONFLICT (content): Merge conflict in src/MaaWpfGui/Helper/ToastNotification.cs
CONFLICT (modify/delete): src/MaaWpfGui/FodyWeavers.xml deleted in HEAD and modified in bd5ecd1d9 (revert: 回退相关更改). Version bd5ecd1d9 (revert: 回退相关更改) of src/MaaWpfGui/FodyWeavers.xml left in tree.
Auto-merging src/MaaWpfGui/Constants/ConfigurationKeys.cs
CONFLICT (modify/delete): src/MaaWpfGui/Configuration/SpecificConfig.cs deleted in bd5ecd1d9 (revert: 回退相关更改) and modified in HEAD. Version HEAD of src/MaaWpfGui/Configuration/SpecificConfig.cs left in tree.
CONFLICT (rename/delete): src/MaaWpfGui/Configuration/RootConfig.cs deleted in bd5ecd1d9 (revert: 回退相关更改) and renamed to src/MaaWpfGui/Configuration/Root.cs in HEAD. Version HEAD of src/MaaWpfGui/Configuration/Root.cs left in tree.
CONFLICT (modify/delete): src/MaaWpfGui/Configuration/PropertyChangedEventDetailArgs.cs deleted in bd5ecd1d9 (revert: 回退相关更改) and modified in HEAD. Version HEAD of src/MaaWpfGui/Configuration/PropertyChangedEventDetailArgs.cs left in tree.
CONFLICT (modify/delete): src/MaaWpfGui/Configuration/ConfigFactory.cs deleted in bd5ecd1d9 (revert: 回退相关更改) and modified in HEAD. Version HEAD of src/MaaWpfGui/Configuration/ConfigFactory.cs left in tree.
Auto-merging src/MaaCore/Vision/Roguelike/RoguelikeRecruitSupportAnalyzer.cpp
Auto-merging src/MaaCore/Vision/MultiMatcher.cpp
CONFLICT (content): Merge conflict in src/MaaCore/Vision/MultiMatcher.cpp
Auto-merging src/MaaCore/Vision/Miscellaneous/StageDropsImageAnalyzer.cpp
Auto-merging src/MaaCore/Vision/Matcher.cpp
CONFLICT (content): Merge conflict in src/MaaCore/Vision/Matcher.cpp
Auto-merging src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.cpp
CONFLICT (content): Merge conflict in src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.cpp
Auto-merging src/MaaCore/Task/Roguelike/RoguelikeControlTaskPlugin.h
Auto-merging src/MaaCore/Task/Roguelike/RoguelikeControlTaskPlugin.cpp
CONFLICT (content): Merge conflict in src/MaaCore/Task/Roguelike/RoguelikeControlTaskPlugin.cpp
Auto-merging src/MaaCore/Task/Roguelike/RoguelikeBattleTaskPlugin.h
Auto-merging src/MaaCore/Task/Miscellaneous/BattleProcessTask.cpp
Auto-merging src/MaaCore/Task/Interface/StartUpTask.cpp
CONFLICT (content): Merge conflict in src/MaaCore/Task/Interface/StartUpTask.cpp
Auto-merging src/MaaCore/Task/Interface/RoguelikeTask.cpp
CONFLICT (content): Merge conflict in src/MaaCore/Task/Interface/RoguelikeTask.cpp
Auto-merging src/MaaCore/Task/Interface/DebugTask.cpp
Auto-merging src/MaaCore/Task/Interface/CopilotTask.cpp
Auto-merging src/MaaCore/Task/Infrast/InfrastAbstractTask.cpp
CONFLICT (content): Merge conflict in src/MaaCore/Task/Infrast/InfrastAbstractTask.cpp
Auto-merging src/MaaCore/Task/Fight/SideStoryReopenTask.h
Auto-merging src/MaaCore/Task/BattleHelper.cpp
Auto-merging src/MaaCore/Task/AbstractTask.cpp
Auto-merging src/MaaCore/Config/TaskData.h
CONFLICT (content): Merge conflict in src/MaaCore/Config/TaskDaterror: could not apply bd5ecd1d9... revert: 回退相关更改
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply bd5ecd1d9... revert: 回退相关更改
a.h
Auto-merging src/MaaCore/Config/TaskData.cpp
CONFLICT (content): Merge conflict in src/MaaCore/Config/TaskData.cpp
Auto-merging src/MaaCore/Common/AsstTypes.h
Auto-merging resource/tasks.json
CONFLICT (content): Merge conflict in resource/tasks.json
Auto-merging resource/roguelike/Sami/recruitment.json
CONFLICT (content): Merge conflict in resource/roguelike/Sami/recruitment.json
Auto-merging resource/roguelike/Sami/autopilot/违和.json
Auto-merging resource/roguelike/Sami/autopilot/虫虫别回头.json
CONFLICT (content): Merge conflict in resource/roguelike/Sami/autopilot/虫虫别回头.json
Auto-merging resource/roguelike/Sami/autopilot/狡兽九窟.json
CONFLICT (content): Merge conflict in resource/roguelike/Sami/autopilot/狡兽九窟.json
Auto-merging resource/roguelike/Sami/autopilot/没有尽头的路.json
CONFLICT (content): Merge conflict in resource/roguelike/Sami/autopilot/没有尽头的路.json
Auto-merging resource/roguelike/Sami/autopilot/新部族.json
CONFLICT (content): Merge conflict in resource/roguelike/Sami/autopilot/新部族.json
Auto-merging resource/roguelike/Sami/autopilot/弄假成真.json
Auto-merging resource/roguelike/Sami/autopilot/幽影与鬼魅.json
Auto-merging resource/roguelike/Sami/autopilot/巍峨银凇.json
Auto-merging resource/roguelike/Sami/autopilot/夙愿将偿.json
CONFLICT (content): Merge conflict in resource/roguelike/Sami/autopilot/夙愿将偿.json
Auto-merging resource/roguelike/Sami/autopilot/何处无山海.json
Auto-merging resource/roguelike/Sami/autopilot/低空机动.json
CONFLICT (content): Merge conflict in resource/roguelike/Sami/autopilot/低空机动.json
Auto-merging resource/roguelike/Phantom/autopilot/覆水难收.json
Auto-merging resource/global/YoStarKR/resource/tasks.json
CONFLICT (content): Merge conflict in resource/global/YoStarKR/resource/tasks.json
Auto-merging resource/global/YoStarEN/resource/tasks.json
CONFLICT (content): Merge conflict in resource/global/YoStarEN/resource/tasks.json
Auto-merging resource/copilot/old/SSS_约翰老妈在建地块_浊蒂水陈版.json
Auto-merging resource/copilot/SSS_阿尔斯特甜品制作平台-澄闪铃兰核v1.3（不兼容应急）.json
CONFLICT (content): Merge conflict in resource/copilot/SSS_阿尔斯特甜品制作平台-澄闪铃兰核v1.3（不兼容应急）.json
Auto-merging resource/copilot/SSS_荒废灯塔-重岳核v2.0（兼容应急）.json
CONFLICT (content): Merge conflict in resource/copilot/SSS_荒废灯塔-重岳核v2.0（兼容应急）.json
Auto-merging docs/zh-tw/3.4-任務流程協議.md
CONFLICT (content): Merge conflict in docs/zh-tw/3.4-任務流程協議.md
Auto-merging docs/zh-tw/2.2-開發相關.md
Auto-merging docs/ko-kr/2.2-개발_환경_구축하기.md
Auto-merging docs/ja-jp/3.4-タスクAPI.md
CONFLICT (content): Merge conflict in docs/ja-jp/3.4-タスクAPI.md
Auto-merging docs/ja-jp/2.2-プルリクエスト.md
Auto-merging docs/en-us/3.4-TASK_SCHEMA.md
CONFLICT (content): Merge conflict in docs/en-us/3.4-TASK_SCHEMA.md
Auto-merging docs/en-us/2.2-DEVELOPMENT.md
Auto-merging docs/3.4-任务流程协议.md
CONFLICT (content): Merge conflict in docs/3.4-任务流程协议.md
Auto-merging docs/2.2-开发相关.md
 (1)

**Comment by zzyyyl** [comment]
（起因是之前在 dev 上的一次 force-push）
