### ISSUE TITLE
掉落识别掉落物名字过长时看不到数字

### ISSUE THREAD

**Issue by guojunyu196** [MaaAssistantArknights/MaaAssistantArknights#744]
![uTools_1654355500103](https://user-images.githubusercontent.com/76220347/172011122-b45e2de6-6f36-46ba-915c-6f3e77f92412.png)

**Comment by guanosine-diphosphate** [comment]
你把窗口大小往右边拉一点就看到了
![image](https://user-images.githubusercontent.com/78458966/172030573-8ee80bf7-8c73-4bc7-9db4-516fd293394c.png)

**Comment by ABA2396** [comment]
这个大概没必要改.jpg

**Comment by ABA2396** [comment]
好吧还是小改一下
