### ISSUE TITLE
定时自动执行的任务无法战斗

### ISSUE THREAD

**Issue by lethefrost** [MaaAssistantArknights/MaaAssistantArknights#7444]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动执行的任务会一直失败，但是保持所有配置不变，手动点击运行就可以正常运行。大概是最近1-2周开始发生的，期间更新过一次MAA但是问题仍然存在，应该最近两个版本的MAA结合我当前版本的其他环境（安卓模拟器、方舟、操作系统等）都有此问题。不确定有没有其他人遇到这个问题？issue里似乎没搜到……我目前装有MAA v4.27.0（431），macOS Sonoma 14.1.1，模拟器是Android Studio自带的Android Emulator，Android API UpsideDownCake ARM64。

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13517083/asst.bak.log)

### 截图

任务出错时GUI截图大概这样（详见log），有时候会除了唤醒后面每一项任务都失败。
<img width="573" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/47198693/5cf51d24-37fa-4630-99de-d2fb2154b0e3">

### 还有别的吗？

谢谢！

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/99fa0ed9-0c02-4f27-abb7-23e2939059c1)
游戏闪退重启了吧

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/b3b60312-e08f-482b-a0f9-34e28e6136a8)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/0e450c9d-5c15-45d0-b19c-2d0b5b6c454f)
游戏闪退了吧？一开始在有返回的地方，开始唤醒判断启动成功了，然后到公招就又到了启动界面了
