### ISSUE TITLE
希望能够添加一键启动多配置功能（通过快捷方式中的启动参数）

### ISSUE THREAD

**Issue by TimCrownie** [MaaAssistantArknights/MaaAssistantArknights#7445]
### 在提问之前...

- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

因为是多模拟器同时使用，每次打开MAA都要一个一个打开，不太方便。
如果是一次启动四个然后逐个改配置，大概需要略少于1分钟的时间，但需要逐个操作；如果单个打开再改配置就更久更麻烦。

### 有什么好的想法？

希望能够通过添加启动参数的支持（类似Folding@Home快捷方式/Steam中的自带参数），来一键启动多个配置。
例如我目前使用的配置名称为"α-EN""α""β""γ"，则可在启动参数中表现为类似"--start-configuration α-EN+α+β+γ"的形式；启动时若带有此启动参数，则双击就启动四个分别带有上述四个配置的MAA。

### 其他内容

实现方式举例：
<img width="330" alt="屏幕截图 2023-12-01 122408" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63519560/eb73f50c-beba-4bf5-86d8-948315342575">
<img width="632" alt="屏幕截图 2023-12-01 122550" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63519560/2f1f1de4-f30c-4115-9e70-a0a60ac60551">

**Comment by ABA2396** [comment]
现在有 --config +配置名  但只能传一个）

**Comment by ABA2396** [comment]
但一般来说是不建议这样用的，一来如果改了配置，最后一个关闭后会覆盖掉之前全部的修改，二来记录的日志肯定有问题。
core开始是支持多开的，但经过这么久也不知道有没有会因为多开遇到问题的新功能，而ui一开始就没奔着多开去）

**Comment by TimCrownie** [comment]
> 但一般来说是不建议这样用的，一来如果改了配置，最后一个关闭后会覆盖掉之前全部的修改，二来记录的日志肯定有问题。 core开始是支持多开的，但经过这么久也不知道有没有会因为多开遇到问题的新功能，而ui一开始就没奔着多开去）

多开的话，会有概率出问题（文件占用还是什么来着，通常在启动过快的情况下出现）
然后现在用着还不错，没出什么大问题。说实话多开时能用就已经很开心了，不然还要用同步器手搓或者一次用一个（

**Comment by ABA2396** [comment]
写个bat来启动吧）中间加点延迟估计也行

**Comment by TimCrownie** [comment]
> 写个bat来启动吧）中间加点延迟估计也行

好文明（
可惜不会（悲

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/ccbdc3c6-b53d-4472-93e0-9864d08da351)
如果bat不在MAA同目录下的话就把MAA.exe换成"完整路径/MAA.exe"

**Comment by horror-proton** [comment]
如果需要更多的自动化可以尝试使用 [maa-cli](https://github.com/MaaAssistantArknights/maa-cli), 不过暂时不清楚 maa-cli 在 Windows 下能否正常使用

**Comment by TimCrownie** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/287202433-ccbdc3c6-b53d-4472-93e0-9864d08da351.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjA4NTMsIm5iZiI6MTcwMTQyMDU1MywicGF0aCI6Ii85OTA3Mjk3NS8yODcyMDI0MzMtY2NiZGMzYzYtYjUzZC00NDcyLTkzZTAtOTg2NGQwOGRhMzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA4NDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZGY2ZDEyYmU3NTMwNGZjOTRmMjI1Zjc0NzgwOGFjZTVmNDNiNGFlNGFkMWRkNzI3MzllZmIzMjUxZTkyNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ln3TF4MrwI8j5pcfbqtzIEBS6aCZbaqZk2QEcRCqswA) 如果bat不在MAA同目录下的话就把MAA.exe换成"完整路径/MAA.exe"

帮大忙了，谢谢喵

**Comment by TimCrownie** [comment]
多谢友友们，已经解决力
