### ISSUE TITLE
博朗台模式无法正确触发

### ISSUE THREAD

**Issue by shuiyunxiaoge** [MaaAssistantArknights/MaaAssistantArknights#7446]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用蓝叠模拟器，刷理智已勾选博朗台模式，但在理智回复界面并没有做剩余时间判断，直接使用了理智药。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13523545/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13523546/gui.log)
近日多次在不同设备上复现，刚刚发生是在2023年12月1日17:29

### 截图

<img width="190" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66132751/98b75768-d492-4b8e-8920-de97eba92d65">

### 还有别的吗？

蓝叠模拟器5.11.100.6501 P64，win11系统，均使用最新版本MAA -v4.27.0

**Comment by status102** [comment]
不超理智上限的理智药使用不会触发葛朗台等待

**Comment by TimCrownie** [comment]
看上去是使用买月卡给的理智药？
就我所知，博朗台模式是针对理智溢出问题的，所以这个没造成理智溢出的话应该就不会触发博朗台模式

**Comment by status102** [comment]
> 看上去是使用买月卡给的理智药？
> 就我所知，博朗台模式是针对理智溢出问题的，所以这个没造成理智溢出的话应该就不会触发博朗台模式

以前是碎石吃药都会等，后来改成吃药不溢出就不等了

**Comment by Sduck-Inverse** [comment]
> > 看上去是使用买月卡给的理智药？
> > 就我所知，博朗台模式是针对理智溢出问题的，所以这个没造成理智溢出的话应该就不会触发博朗台模式
> 
> 以前是碎石吃药都会等，后来改成吃药不溢出就不等了

为什么现在又不溢出也会等了？

**Comment by status102** [comment]
> 为什么现在又不溢出也会等了？

log and new issue
