### ISSUE TITLE
萨米肉鸽选人后直接结束探索

### ISSUE THREAD

**Issue by xuan12315** [MaaAssistantArknights/MaaAssistantArknights#7447]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽开始阶段使用招募卷后直接退出本次探索

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13523635/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13523638/gui.log)

### 截图

![屏幕截图 2023-12-01 174754](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/152603518/dba815a1-7f62-4ec0-ac49-638d124cad82)
![屏幕截图 2023-12-01 174821](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/152603518/0fd7a823-faef-486c-98fb-48dc77ebb34d)

### 还有别的吗？

mumu模拟器12

**Comment by Jisu-Woniu** [comment]
傀影肉鸽也出现相同情况：

日志与截图文件：

[debug.tar.gz](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14082273/debug.tar.gz)

环境：

Arch Linux + maa-cli + Waydroid

**Comment by Jisu-Woniu** [comment]
Any update on this?
