### ISSUE TITLE
公开招募选中多个四星tag时选出了无关的三星tag

### ISSUE THREAD

**Issue by lpowo** [MaaAssistantArknights/MaaAssistantArknights#7452]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

#3819 #92 等issue中需求的功能是公开招募出现多个四星tag或tag组合时，尽可能多选四星tag。
#6900 的PR后，在选完一个四星tag组合后：
若未选满到三个tag，仍会选择三星tag（例如下面的断点调试）；
若后续四星tag组合超出了三个tag的限制，会导致只选一部分tag，使得该四星tag组合不完整，降级为三星tag（例如出现
{“狙击”，“生存”，“先锋”，“治疗”，“新手”}）“狙击”“生存”=杰西卡，“先锋”+“治疗”=桃金娘，那么肯定有个tag组合会被不完整地选入。

疑问：在选完所有可能的五星/四星tag后，玩家还会选择无关的三星tag吗？（不清楚方舟公招算法）

例如：通过断点测试如下情况，可保证大概率出现四星的“削弱”/“削弱”+“术士”的tag组合被选中，但未选满三个tag，所以还多选了不会保证有四星的“生存”tag
<details>

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113409320/8a3139b6-c6ab-44d1-a3bb-4b4599ec8a81)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113409320/49e6c9ca-b569-4565-94ee-9977098bd08c)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113409320/05ae500b-7f40-4b56-af7d-88312d7a3492)

</details>

### 有什么好的想法？

get_select_tags函数取出了来自result_vec排序的tag，取满三个为止。
是否应该改为取出尽可能多的五星/四星的完整的tag组合。

<details>

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113409320/77af20c8-e5e7-4aea-8f7b-975c76ad72e2)
result_vec的排序规则：
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/f5dec98883285f77264abce4603404c1b21de541/src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp#L412-L429
get_select_tags选满三个为止：
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/f5dec98883285f77264abce4603404c1b21de541/src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp#L710-L727

</details>

**可能的修改方案：**
在result_vec的排序规则中，min_level的优先级最高保持不变，提高tag数少的优先级；
get_select_tags函数中，保证选择的comb的min_level>=4且comb要么完整选入，要么不选，然后break；

### 其他内容

如果采用修改建议的话，可以将issue assign给我嘛，作为一个开源社区的新手和maa的使用者，我很希望能为maa做一些贡献！
我是maa的忠实粉丝！

**Comment by broken-paint** [comment]
但是那几个issue的意思不就是选中4星tags有概率被划掉导致变成3星，所以选满3个tags，这样被划的时候体感上更可能划掉更低级的tags吗（

**Comment by broken-paint** [comment]
而不是4星tags选完了就停下来，这样只有一种4星组合时就还会只选一个，更可能被划掉
而且只有一种4星组合的情况应该是更常见的？个人认为多选上3星tags多消耗的那点lmb算不了啥，半个基建订单就回来了（）

另外如果想参与开发的话可以直接提pull request，可以link到这个issue来

**Comment by lpowo** [comment]
@broken-paint 我也觉得不是lmb多少的问题，但是不知道玩家是否选择额外的三星tag，或者说额外选三星tag有无收益。


另外，提到的这两个issue的需求似乎也是出现了多个四星tag组合之后需要选满，而未提到选三星tag。
* https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2410
* https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5191

**Comment by broken-paint** [comment]
之前做的时候也讨论过这个问题来着（
只勾复数4星tags应该也可以单独做个选项吧，反正我是4星3星一起选（

**Comment by horror-proton** [comment]
如果要在等价或者基本上等价的四星组合中选择 tag 数量更多的一项, 可以直接修改排序规则.
但现在 #6900 改成了直接强行选 3 个, 而且还可能是互相冲突的 tag, 我不明白为啥要这样 (

**Comment by broken-paint** [comment]
因为我没见过4星tag被划留一个3星
如果只复选4星的话只有一组4星tag时就只会选一组，然后还是可能出现issue说的4星被划，导致少黄票的问题。

![屏幕截图 2023-12-02 200300](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131476796/8e026d1f-536a-4b4c-9f9f-20c5b9c91d87)

比如这个组合只选4星就只会单选爆发，可能被划

**Comment by lpowo** [comment]
@broken-paint 已在 #6900 的基础上单独做了选项，并把选项合并到了一个栏目

**Comment by lpowo** [comment]
> 多选有得有失，除非用AI来处理复杂情况选择最优。
> 比如只选defender dps可以固定为五星，但是如果多选了一个Nuker， 就有概率触发Nuker DPS组合降为四星

此issue考虑到这个问题，打算的解决办法是先固定最高星，然后在高星里面多选tag，比如在你描述的tag组合中，tag选择被固定到五星，不会再考虑可能的四星tag。
但是如 @broken-paint 所说，多选了低星的tag并不一定会导致词条被划掉。

**Comment by horror-proton** [comment]
很难证明有什么方法能提高四星的概率, 比如选两个 {tag_a, tag_b} 没划掉至少能出四星干员, 只选 { tag_c } 没划掉也至少四星, 但没有干员同时满足这三个 tag.

我们不知道鹰角是怎么划 tag 的, 有可能把三个都选上出四星的概率还不如选其中一个组合
