### ISSUE TITLE
萨米肉鸽藏品四叶草化石导致得偿所愿卡死

### ISSUE THREAD

**Issue by xuanwu666** [MaaAssistantArknights/MaaAssistantArknights#7455]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽后勤分队开得偿所愿图像识别卡死，焰苇开局，四个选项，零抗干扰，只有第一个选项和第四个选项可供选择，maa卡死在这里，当手动点击其中一个选项后，maa又自动运行下去，推测是图像识别问题
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/122015134/e7846d87-3298-4a2b-bd72-5de62fa415c3)

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13533326/debug.zip)
2023年12月2日11.27左右，12点左右发生第二次。第一次我未截图，于debug文件夹找到部分截图打包了压缩文件，以下截图部分为我第二次手动截图，但debug的肉鸽文件夹并无自动截图。

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/122015134/e7846d87-3298-4a2b-bd72-5de62fa415c3)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/122015134/47fe6311-9a1f-45dd-9b7b-79bad53a4fc2)
以上图片是第二次卡死时截图。下方压缩文件是maa中debug文件夹内11.27时，即第一次卡死时的自动截图
[roguelike.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13533341/roguelike.zip)

### 还有别的吗？

mumu12模拟器，win11家庭版，萨米肉鸽 后勤分队焰苇开 刷等级，

**Comment by zzyyyl** [comment]
@Lancarus

**Comment by Constrat** [comment]
It's definitely the four-leaf clover relic fault. Gives another option to the relic collection. Creating a go-around for this might be very tricky.
How would we check if the four clover leaf exists? And in case we find a way to, do we add another field to encouter.json with the corrected choice?

**Comment by SherkeyXD** [comment]
其实最理想的解决方案是进入不期而遇时检查有多少个选项，并且这些选项是否可用，然后再去选择
这样还能一并解决没过结局导致先行一步选项少一个的问题
