### ISSUE TITLE
使用备选，剿灭完成后能否默认跳过，不通知（报错） 

### ISSUE THREAD

**Issue by shawnyuan-cn** [MaaAssistantArknights/MaaAssistantArknights#7458]
使用备选，剿灭完成后能否默认跳过，todo界面没有剿灭也就意味着本周的剿灭已经刷完了，每次都报错提醒有点小题大做的感觉。

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105029931/aa049ab8-6b28-42e7-a89b-a70b434be526)

_Originally posted by @shawnyuan-cn in https://github.com/MaaAssistantArknights/MaaAssistantArknights/discussions/7299_

**Comment by leolbyy** [comment]
@ABA2396 
其实和https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9327这个问题类似。

报错会导致的情况是，在设置了报错retry后，会导致任务反复重试直到设置的重试上限。

我有查看当前的剿灭逻辑，即只判断当前待办事项中有无剿灭作战，那是否可以添加一个判断逻辑，即待办事项中无剿灭作战，则进入常态事务页面判断是否剿灭作战已完成？
甚至简单一点，在待办事务中没有剿灭作战时，判断为已完成，不返回error code

**Comment by ABA2396** [comment]
> @ABA2396 
> 其实和https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9327 这个问题类似。
> 
> 报错会导致的情况是，在设置了报错retry后，会导致任务反复重试直到设置的重试上限。
> 
> 我有查看当前的剿灭逻辑，即只判断当前待办事项中有无剿灭作战，那是否可以添加一个判断逻辑，即待办事项中无剿灭作战，则进入常态事务页面判断是否剿灭作战已完成？
> 甚至简单一点，在待办事务中没有剿灭作战时，判断为已完成，不返回error code

不一样，有时候当期剿灭没打没有代理的话也会出错

**Comment by leolbyy** [comment]
> 事项中有无剿灭作战，那是否可

那会修改现在“待办事项找不到剿灭作战”的报错逻辑吗？还是会维持现状呢？

**Comment by ABA2396** [comment]
这和 #9327 不是同一个问题吗
