### ISSUE TITLE
建议加入信用商店只购买打折商品（优先除外），以及300以下信用点停止购买商品的功能

### ISSUE THREAD

**Issue by EnderOre** [MaaAssistantArknights/MaaAssistantArknights#7466]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

每次都要把信用用完，没法攒一波等第二天手动换

经常买那种不打折巨贵的商品

### 有什么好的想法？

1.加入信用商店只购买打折商品（优先除外）
打折商品比较便宜，可以留下更多的信用点

2. 300以下信用点停止购买商品
有时候想要攒到第二天多买点东西

**Comment by EnderOre** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66881284/f9e8893d-4633-451a-94e4-ae7529f3bb55)

比如说这里就多买了320的东西，看着我心疼

**Comment by EnderOre** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66881284/9fdc4caf-d882-40d2-9577-22b9dd4b6343)
希望能在这里加

**Comment by TimCrownie** [comment]
感觉是强迫症福音，好文明（

**Comment by lpowo** [comment]
如果301点信用点购买了200点的商品，剩下101点符合 `300点以下停止购买` ，但符合 `攒到第二天多买点东西` 的需求吗？

**Comment by EnderOre** [comment]
> 如果301点信用点购买了200点的商品，剩下101点然后停止购买，这符合 “300点以下停止购买” ，但符合 “攒到第二天多买点东西” 的需求吗？

1.可以将“只买折扣物品”和“300以下停止购买”结合起来；之前发issue的目的就是因为这个。300以下了还会继续购买非打折商品，不如直接停下来留到第二天
2.301信用点买了200的商品这个确实是个问题，并没有达到“节省信用点”。因此最好还是和只买折扣物品结合起来

3.实际上这两个功能真要一起加的话应该是必须得结合起来的，而且或许可以这样子设置：
a.只会购买折扣物品以及优先购买列表中的物品 
b.在购买完折扣物品后若信用点仍300以上则继续购买非黑名单中的低价商品直到低于300为止
c.在开启300以下不购买的功能时，若溢出信用点则从非折扣非黑名单物品中优先选择最低价的商品

4.如果玩家只选择了“300信用点以下停止购买”，则判定逻辑或许可以类似3c。

**Comment by EnderOre** [comment]
> > 如果301点信用点购买了200点的商品，剩下101点然后停止购买，这符合 “300点以下停止购买” ，但符合 “攒到第二天多买点东西” 的需求吗？
> 
> 1.可以将“只买折扣物品”和“300以下停止购买”结合起来；之前发issue的目的就是因为这个。300以下了还会继续购买非打折商品，不如直接停下来留到第二天 2.301信用点买了200的商品这个确实是个问题，并没有达到“节省信用点”。因此最好还是和只买折扣物品结合起来
> 
> 3.实际上这两个功能真要一起加的话应该是必须得结合起来的，而且或许可以这样子设置： a.只会购买折扣物品以及优先购买列表中的物品 b.在购买完折扣物品后若信用点仍300以上则继续购买非黑名单中的低价商品直到低于300为止 c.在开启300以下不购买的功能时，若溢出信用点则从非折扣非黑名单物品中优先选择最低价的商品
> 
> 4.如果玩家只选择了“300信用点以下停止购买”，则判定逻辑或许可以类似3c。

3c 不一定是最低价，应该用一图流的价值排序来购买
