### ISSUE TITLE
MAA启动“Link Start”期间，计算机出现卡顿情况

### ISSUE THREAD

**Issue by kagura-shigure** [MaaAssistantArknights/MaaAssistantArknights#7468]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，从约v4.20.0版本开始，该卡顿情况一直存在。且卡顿后概率导致图片识别有误

- 点击“Link Start”，Maa开始运行，此时电脑开始卡顿，包括但不限于：鼠标移动时卡顿，其他运行游戏掉帧、Chrome观看视频掉帧
- 点击“停止”，该卡顿情况即刻消失
- 卡顿的时间节点一般是Maa进行操作的瞬间，比如进行点击、滑动等操作时
- 自v4.20.0版本以来，尝试过数次下载新包覆盖源文件、重新下载Maa、更换模拟器等操作

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13538073/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13538074/gui.log)

### 截图

**执行任务中的Maa和Mumu12模拟器**
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/58117103/d07f9ca6-50af-4881-9144-c9e3f12bf134)

**执行任务中的Maa和雷电模拟器**
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/58117103/35c73636-3e75-4e14-a563-987ecaab2248)

**执行任务中的任务管理器**
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/58117103/d031ccfd-614b-4850-bd15-dba0bfb3936f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/58117103/c6820426-529f-4952-bda0-0c25bc864743)

**自定义基建计划下，Maa不识别干员伊芙利特**
图片中出现了伊芙利特但并未选中，一直在向后翻找
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/58117103/25282f6f-691d-4a3d-a3db-3c541b6aaaf6)

### 还有别的吗？

**模拟器：Mumu12模拟器（3.5.20.2151）、雷电模拟器
操作系统：Windows11专业版 22H2
配置：CPU/i5-13600KF、GPU/NVIDIA RTX 4070Ti**

**Mumu模拟器配置信息：**
基础信息
UUID :  04478158-f1e1-4ecb-955f-36b8606393df
模拟器版本 :  3.5.20.2151
模拟器磁盘（可用/总）空间 :  104GB/125GB
日志路径 :  D:\Game\MuMuPlayer-12.0\vms\MuMuPlayer-12.0-0\logs\

运行环境
VT :  开启
Hyper-V :  关闭
网络环境检测 :  正常
以管理员运行方式 :  是
DirectX 11是否安装 :  是
防火墙 :  开启（建议关闭）

电脑配置
主板型号 :  Manufacturer: ASUSTeK COMPUTER INC.  Product: ROG STRIX Z790-A GAMING WIFI
CPU :  13th Gen Intel(R) Core(TM) i5-13600KF
系统版本 :  Windows 11 64-bit Kernel 10.0.22621
显卡驱动 :  正常
显卡驱动型号 :  31.0.15.4592 (20231019)
所有显卡 :  NVIDIA GeForce RTX 4070 Ti  |  Microsoft Basic Render Driver
当前使用显卡 :  NVIDIA GeForce RTX 4070 Ti
安装磁盘(可用/总)空间 :  347.9GB/1907.7GB
可用内存/总内存 :  39.3GB/63.8GB

模拟器设置
Root :  关闭
显卡渲染模式 :  DirectX 模式
性能设置 :  6核/12GB
手机型号 :  Xiaomi 12S Pro
分辨率 :  1920 * 1080
高帧率 :  开启

连接设备
音频输入 :  已连接
音频输出 :  已连接

网络信息
MuMu DNS :  192.168.31.1
电脑DNS :  192.168.31.1
Rom MAC地址 :  08:32:7b:92:50:00

ADB调试端口 :  16384
MuMu出口IP地址 :  10.0.2.15
电脑出口IP地址 :  39.185.124.44

其它信息
其它版本信息 :  vm: 120.1.32.001 hyperv: 6.3.15.0 renderer: 0.0.125.0
Vendor :  NetEase
OpenGL Renderer :  MuMu GL (NVIDIA GeForce RTX 4070 Ti Direct3D11 vs_5_0 ps_5_0)
OpenGL Version :  OpenGL ES 3.1
运行时间 :  0 : 14 : 38

**雷电模拟器配置信息**
操作系统：Microsoft Windows 11 64位  22H2
CPU型号：13th Gen Intel(R) Core(TM) i5-13600KF
主板：华硕 ROGSTRIXZ790-AGAMINGWIFI
总内存：63.8 GB
可用内存：42.1 GB
显卡型号：OrayIddDriver Device (20221115)
显卡型号：NVIDIA GeForce RTX 4070 Ti (20231019)【当前使用】
OpenGL：4.6.0 NVIDIA 545.92
HyperV:关闭
Root:关闭
模拟器版本：9.0.62(9)
模拟器路径：C:\Software\leidian\LDPlayer9\
日志路径：C:\Users\majiu\AppData\Roaming\leidian9\log
vt:开启
运行参数：CPU(4核) 内存：(4096M) 正在运行(1) 高速(1)
分辨率：1920x1080 dpi 280 fps 120
总大小24 G，剩余17 G

**Comment by ABA2396** [comment]
把Windows的内核隔离关了

**Comment by kagura-shigure** [comment]
曾尝试过该手段，Windows内核隔离是关闭的，但是鼠标移动、视频观看仍然会出现卡顿情况。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/58117103/6ea73d3b-f792-4e61-aafb-73a91dc64c7f)

**Comment by ABA2396** [comment]
没搞懂，感觉就像是开了内核隔离和hyperv会遇到的情况。关了之后有重启过电脑吗？试试看下个老版本的maa会不会遇到这种情况

**Comment by zzyyyl** [comment]
换个模拟器试试（小声

**Comment by kagura-shigure** [comment]
确实怀疑是win11的问题，我想办法回退一下系统试试吧

**Comment by Constrat** [comment]
Seems like it's MAA-independent, closing for now.
