### ISSUE TITLE
模拟器退出时关闭了其他模拟器

### ISSUE THREAD

**Issue by 1742035356** [MaaAssistantArknights/MaaAssistantArknights#7469]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

电脑上有蓝叠和雷电两个模拟器，Maa设置中连接设置的是蓝叠模拟器，Maa启动时可以正确的启动蓝叠模拟器并打开明日方舟。但是如果蓝叠模拟器和雷电模拟器都在运行的情况下，Maa的退出模拟器则是关闭的雷电模拟器
我又试了下同时打开mumu模拟器和蓝叠模拟器，可以正常关闭蓝叠模拟器

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13538181/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13538182/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99705099/815439cc-b214-4ee7-888a-bfce114571cf)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99705099/80d751b6-de65-4f0e-84cb-6f6eb58708c5)

### 还有别的吗？

蓝叠模拟器5.4.100
雷电模拟器9.0.46
win11操作系统

**Comment by ABA2396** [comment]
把蓝叠的连接地址改成127.0.0.1:5555

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7bba385b-82c2-499f-9683-eda5cb3db1e6)
9.0.57以下版本和蓝叠是同一个端口，通过端口关模拟器谁都不知道会关掉哪个

**Comment by 1742035356** [comment]
> 过端

好的谢谢，我升级雷电试试

**Comment by 1742035356** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/287575322-7bba385b-82c2-499f-9683-eda5cb3db1e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDAwNDcsIm5iZiI6MTcwMTczOTc0NywicGF0aCI6Ii85OTA3Mjk3NS8yODc1NzUzMjItN2JiYTM4NWItODJjMi00OTlmLTk2ODMtZWRhNWNiM2RiMWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAxMjkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNGVhNGRkNmEyZGE5ZmY3ZWFkNzk2NDFhMjRmM2JiNTJjNGU2N2E4ZThhOTkxYTljYTBkODUwZjZmZDFiOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pUihs7nNUTPut_J60nr9GPDsBEL5TVFhSOxP-UEwSUg) 9.0.57以下版本和蓝叠是同一个端口，通过端口关模拟器谁都不知道会关掉哪个

雷电升级到了最新版本，关闭的还是雷电模拟器。

**Comment by ABA2396** [comment]
再来个日志

**Comment by 1742035356** [comment]
> 再来个日志

[asst.log](https://gith
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13553995/gui.log)
ub.com/MaaAssistantArknights/MaaAssistantArknights/files/13553993/asst.log)

**Comment by 1742035356** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13553997/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13553998/gui.log)


> 再来个日志

**Comment by ABA2396** [comment]
看着像是通过127.0.0.1:5555查出来的pid是雷电的而不是蓝叠的，我去问问雷电咋说

**Comment by 1742035356** [comment]
> 看着像是通过127.0.0.1:5555查出来的pid是雷电的而不是蓝叠的，我去问问雷电咋说
这是雷电和蓝叠的端口情况，不知道是否能作为参考
![Snipaste_2023-12-05_10-10-39](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99705099/8122aa7b-f188-45e5-af81-42cd9d8b4038)

**Comment by ABA2396** [comment]
国际版蓝叠关闭的方法是通过netstat -ano|findstr "5555"这种样子查pid的，cmd看看查出来有什么

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/5622276c-3fcc-4431-a834-9847abd84cb6)
照理来说查到的这个就是HD-Player的PID了，不知道为啥能把雷电给关了

**Comment by 1742035356** [comment]
> 国际版蓝叠关闭的方法是通过netstat -ano|findstr "5555"这种样子查pid的，cmd看看查出来有什么

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99705099/15fddf6f-bd2e-46a1-b023-1b6eeb7a0811)

**Comment by ABA2396** [comment]
看看这几个对应的是什么

**Comment by 1742035356** [comment]
> 看看这几个对应的是什么

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99705099/1550c148-c377-4014-b3d5-7a500973a62a)

**Comment by ABA2396** [comment]
感觉模拟器一般不会用到 0.0.0.0 和 [::] 吧？但 f3c68789c42c234dd27869723b81c22d3eb8eb6b 里最开始的提交里就有这两个，雷电现在是通过控制台关了，还有别的模拟器需要 0.0.0.0 吗？

cc @cgldimo

**Comment by ABA2396** [comment]
发个内测试试看

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/7095869296
