### ISSUE TITLE
GUI更新弹窗转移反斜杠处理错误

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#7470]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如截图所示，客户端弹窗表现与release note实际表现不服

### 日志文件

无需日志

### 截图

<img width="450" alt="截图_20231203235501" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/53437291/4c3b13f2-d004-47f6-b11a-5e7937dbf74e">

**Comment by KJH-x** [comment]
<img width="450" alt="截图_20231212235608" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/53437291/2c4c2663-e326-4e03-99f8-79767984d379">
似乎没修好？

**Comment by ABA2396** [comment]
> <img alt="截图_20231212235608" width="450" src="https://private-user-images.githubusercontent.com/53437291/289922551-2c4c2663-e326-4e03-99f8-79767984d379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTg1NjUsIm5iZiI6MTcwMjM5ODI2NSwicGF0aCI6Ii81MzQzNzI5MS8yODk5MjI1NTEtMmM0YzI2NjMtZTMyNi00ZTAzLTk5ZjgtNzk3Njc5ODRkMzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE2MjQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhODU4ZDgzMDY5MTIyM2UzZDY0YmQ1NzQ5ZDQzMmExMzE5NDY4NGMzOGRiYmJjZWJiMjAwMzVmYTYzMjE3MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nNiver-QHwoW5x15ah_bdtcCoIwwKB1pSFIWR_64sUg"> 似乎没修好？

发版的时候changelog忘合了，这个是上个版本的changelog）
