### ISSUE TITLE
肉鸽刷等级模式增加 达到等级上限就停止

### ISSUE THREAD

**Issue by zlqd123** [MaaAssistantArknights/MaaAssistantArknights#7471]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

肉鸽等级满了也会一直打，有点浪费

**Comment by status102** [comment]
Duplicate of #3869
