### ISSUE TITLE
ADB连接失败

### ISSUE THREAD

**Issue by sryhm123456** [MaaAssistantArknights/MaaAssistantArknights#7474]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

换了好几个模拟器，也重启了很多遍，但始终显示ADB连接失败，不知道该怎么解决

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13543607/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13543609/gui.log)

### 截图

![屏幕截图 2023-12-04 162445](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144112930/6f96ba3e-7df4-4f0d-8d89-83d3ba249de2)

### 还有别的吗？

Windows11
雷电9/夜神/mumu12

**Comment by ABA2396** [comment]
```
* daemon not running; starting now at tcp:5037

adb: CreateFileW 'nul' failed: 系统找不到指定的文件。 (2)

* failed to start daemon

error: cannot connect to daemon
```
感觉像是系统问题
https://stackoverflow.com/questions/64595641/daemon-not-running-adb-createfilew-nul-failed-the-system-cannot-find-the-fi
参照这个操作试试看能不能跑？

**Comment by ABA2396** [comment]
similar #7182

**Comment by sryhm123456** [comment]
之前用的window10系统运行的没问题，升级成11就不行了ᯤᯅᯤ
