### ISSUE TITLE
识别问题

### ISSUE THREAD

**Issue by Aoxi200** [MaaAssistantArknights/MaaAssistantArknights#7475]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

未进入相应的地点进行割草
基建换班进了危机合约
刷理智一直在戳助理干员
获取信用及购物变成了进入公开招募
领取奖励变成进入干员列表（角色管理）

### 日志文件

1

**Comment by Constrat** [comment]
No log, no screen, no info

**Comment by Aoxi200** [comment]
> 没有日志，没有屏幕，没有信息

已经解决

**Comment by ABA2396** [comment]
隐私策略是不会碰的，但一般来说这个只要点掉一次就不会弹出来了，除非隐私策略更新了

**Comment by Aoxi200** [comment]
> 隐私策略是不会碰的，但一般来说这个只要点掉一次就不会弹出来了，除非隐私策略更新了

原来如此，我还以为是我设置没设置好，导致需要自己点 XD 。官服应该没有这种弹窗吧？要是模拟器或者B服什么时候出个不再显示就好了
