### ISSUE TITLE
Wrong OCR in Roguelike Settlement for Latin characters

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#7479]
### Description

@status102 you added the settlement for the Integrated Strategies, but in the second page it seems like the algorithm being used it NumberOcrReplace: MAA correctly Identifies `Calm Seas`, but wrongly replaces `l` as `1` to `Ca1m Seas`. 

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/c74368181852a1e7b263b26a2cb83c47f6446aa9/resource/tasks.json#L8750-L8751

### Log files

```py
[2023-12-04 21:06:06.565][TRC][Px1d48][Tx33d8] asst::WordOcr [{ Calm Seas: [ 0, 0, 124, 35 ], score: 0.933574 }] by OCR Rec , cost 34 ms
[2023-12-04 21:06:06.565][TRC][Px1d48][Tx33d8] Proced [{ Ca1m Seas: [ 748, 370, 124, 35 ], score: 0.933574 }]
```

**Comment by status102** [comment]
It is difficult to find where a mistake happened in former part or in number part .

 Splitting the task may be useful.

**Comment by Constrat** [comment]
Yeah I see what you mean, in difficulty 0 (Calm Seas) there is no number, but in other difficulties the number starts to show up.
If I for example create a NumberOcrReplace task in the YostarEN will this bypass the official one?ù
cc @zzyyyl

**Comment by status102** [comment]
对此添加一个`Ca1m` -> `Calm`可能要好过去覆盖掉NumberOcrReplace？

**Comment by Constrat** [comment]
Yeah, I looked at NumberOcrReplace, thinking I could change it to `"^l$"` -> "1" but this is too much regex (and it's untested) so it will definitely break something.

**Comment by Constrat** [comment]
Yeah, I looked at NumberOcrReplace, thinking I could change it to `"^l$"` -> "1" but this is too much regex (and it's untested) so it will definitely break something.

I can't remember if adding "`Ca1m`" -> "`Calm`" will fix, because if it first replace `l` with `1` I don't think it will check again.
Also testing this is going to be fun... Unless I create a custom task to test, I can't be bothered to let MAA clear a full I.S. run every time.

**Comment by status102** [comment]
从代码上来讲，这样是可行的，只要你把这一个替换放在`l`→`1`之后
