### ISSUE TITLE
刷理智任务在没有源石和理智药库存的情况下会卡住不执行下一步任务

### ISSUE THREAD

**Issue by Argonautes0607** [MaaAssistantArknights/MaaAssistantArknights#7481]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

这个问题其实一直就有，之前有库存就没在意这次买皮肤源石空了所以来提了，应该是识别错误，不知道是Mac还是EN服没什么人的原因没看到其他人提

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13554773/asst.log)

### 截图

<img width="1732" alt="截屏2023-12-05 11 35 06" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106745133/0b1a8577-a105-42c9-a5a2-fd6690bb7e44">
<img width="1732" alt="截屏2023-12-05 11 36 38" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106745133/82df86c4-9161-4d60-a3f6-22f1e7268f1c">

### 还有别的吗？

Mac playcover ,MacOS 14.1 ,Mac mini M1

**Comment by ABA2396** [comment]
en没有NoStone这张图
![NoStone](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/cad123d9-1ba8-4b09-b69b-7fe4690fac48)
需要一张类似这样的原尺寸截图，mac有什么办法提供吗

**Comment by ABA2396** [comment]
好像把下面的给截掉也行？试试看

**Comment by ABA2396** [comment]
![NoStone](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7b6ae7a1-bf45-4973-99ce-d569112623f8)
用这张图替换下\resource\template里的NoStone.png看看行不行

**Comment by Argonautes0607** [comment]
替换了好像不行

**Comment by ABA2396** [comment]
替换之后重启下，如果还是不行再发下日志

**Comment by Argonautes0607** [comment]
MAA和模拟器重启了也都不行
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13555006/asst.log)

**Comment by ABA2396** [comment]
``` log
[2023-12-05 12:08:39.451][TRC][Pxde42][Tx7a8f] match_templ | NoStone.png score: 0.510056 rect: [ 828, 256, 213, 186 ] roi: [ 800, 250, 350, 250 ]
```
识别到了但得分很低，不知道国服是不是也有这个问题，得检查下
cc @hguandl @Constrat @zzyyyl @status102

**Comment by Constrat** [comment]
@ABA2396 Can confirm for YostarEN we never had that template because I have something like 1000 originiums (I won't spend all of them).

On the other hand it seems strange that if we change all the templates, it still won't work.
I'll have a look at the ROIs

**Comment by ABA2396** [comment]
40f38b8db7112b370fb9610732746ad3b5482bbe 重新获取了截图，我本地测试执行良好，如果
![NoStone](https://raw.githubusercontent.com/MaaAssistantArknights/MaaAssistantArknights/40f38b8db7112b370fb9610732746ad3b5482bbe/resource/template/NoStone.png)
仍不起作用，估计只能从对应的客户端获取截图了

**Comment by Argonautes0607** [comment]
刚刚重新替换了还是不行
