### ISSUE TITLE
萨米肉鸽抗干扰为0仍然持续要走岔路

### ISSUE THREAD

**Issue by 100210110** [MaaAssistantArknights/MaaAssistantArknights#7484]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

出bug情况：萨米肉鸽，抗干扰为0时，走岔路，岔路后是商店，会持续试图走岔路，右上角提示抗干扰指数不足，然后继续重复尝试

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13559485/debug.zip)
12/5 19:14开始持续了十分多钟

### 截图

![MuMu12-20231205-192543](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104227884/ffcba5af-9aa3-4e0b-8bdb-ad2cabb78249)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/104227884/91e8f250-dd48-4f1b-8615-e10d515c1fd2)

### 还有别的吗？

我觉的应该是操作逻辑的问题，系统配置什么的应该不用

**Comment by Constrat** [comment]
cc @Lancarus

**Comment by SherkeyXD** [comment]
Duplicate of #7345
