### ISSUE TITLE
萨米肉鸽结局前反复尝试使用密文版导致卡住

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#7486]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA在打到萨米肉鸽普通结局BOSS之前容易各种卡住。首先是MAA会不停尝试组合密文板，表现的犹豫不决，反复打开密文板界面浏览密文板却并不组合。或者干脆直接卡住不动，不进行任何操作，数分钟之后才开始操作。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13560469/asst.zip)

### 截图

![屏幕截图 2023-12-05 211416](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92417243/8669173a-6f2e-40c2-b0bb-e5cd2cc43eba)
![屏幕截图 2023-12-05 211705](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92417243/561cd70a-0283-487b-af44-caa0c42bbca7)

### 还有别的吗？

log太大无法直接上次，所以我压缩了一下。
模拟器是雷电4，系统Windows11专业版，MAA4.28.0beta1

**Comment by SherkeyXD** [comment]
这个归根结底还是密文版的问题

**Comment by ABA2396** [comment]
> 这个归根结底还是密文版的问题

能不能先给密文板加个开关，策略之后再改）

**Comment by SherkeyXD** [comment]
> 能不能先给密文板加个开关，策略之后再改）

我只会写ui.jpg
