### ISSUE TITLE
maa今天更新资源重启后显示“资源损坏，请重新下载完整安装包”

### ISSUE THREAD

**Issue by kizfive** [MaaAssistantArknights/MaaAssistantArknights#7487]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

进入maa后 maa自动更新数据，应该是更新今天的新ss的数据 所以我等待更新完之后按提示重启maa却显示“资源损坏，请重新下载完整安装包” 
尝试过去官网重新下载安装
一开始刚下下来能成功启动，但是在同样更新完数据重启后提示一样的“资源损坏，请重新下载完整安装包” 

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13560521/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13560522/gui.log)
[2023-12-05 21:17:11.879][ERR][Px5ef8][Tx45f8] Json open failed D:\MAA-v4.27.0-win-x64\cache\resource\tasks.json
怀疑是在asst的这里出现了问题
根据报错找到tasks.json后用gbk编码的vscode打开发现有乱码 不知道是不是问题所在 截图在下方

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/86387790/c2ce6c43-da1c-41fa-a01e-30f55f084f9e)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/86387790/5a04916c-c6ca-43d1-a6b6-8d8da2210acf)

### 还有别的吗？

用的win11 mumu12

**Comment by ABA2396** [comment]
文件编码是UTF-8。文件最后多了个逗号，删了就好了，这儿写错了
\cache\resource\tasks.json
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f84aebb1-5b9c-465f-8314-8c90d26a74db)
