### ISSUE TITLE
CPU占用异常

### ISSUE THREAD

**Issue by Xiong917** [MaaAssistantArknights/MaaAssistantArknights#7490]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA运行时CPU占用过高

### 日志文件

时间 2023/12/5/ 23:50左右
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13562403/asst.zip)

### 截图

![屏幕截图 2023-12-05 234934](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36437964/debcc9f2-243e-4121-b557-8b5c01279001)

### 还有别的吗？

模拟器：MUMU12
配置：
    处理器	13th Gen Intel(R) Core(TM) i5-13600KF   3.50 GHz
    机带 RAM	64.0 GB (63.8 GB 可用)
    GPU RTX4070ti

**Comment by TimCrownie** [comment]
在打肉鸽/自动战斗的时候通常都会占用较多的CPU资源，与持续进行图像识别/调用策略等有关（大概）
以我的笔记本（i7-13700H，16GB DDR5-5200 RAM）为例，三开模拟器并双开肉鸽时CPU会保持满载，但三开刷理智的话CPU负载基本上不会超过50%。

**Comment by graydovee** [comment]
我也遇到了同样的问题，我i9 13900k单开MUMU模拟器肉鸽占用55%左右，想问下是否可以限制下识别频率，或者有计划使用GPU识别？

**Comment by zzyyyl** [comment]
> 我也遇到了同样的问题，我i9 13900k单开MUMU模拟器肉鸽占用55%左右，想问下是否可以限制下识别频率，或者有计划使用GPU识别？

See #4016

**Comment by zhayier** [comment]
这个软件能不能做成靠gpu出主力，cpu为辅助？我一个朋友看了这个软件的代码以后跟我说可以用替换法来让gpu负责，cpu辅助，这样能占用低点，纯属好奇

**Comment by ABA2396** [comment]
当然可以，让你朋友来写个pr呗

**Comment by a1623382** [comment]
> > 我也遇到了同样的问题，我 i9 13900k 单开 MUMU 模拟器肉鸽占用 55% 左右，想问下是否可以限制下识别频率，或者有计划使用 GPU 识别？
> 
> See #4016

已经依照推荐将maa中的onnxruntime.dll换成了gpu的版本，但是在我这里的cpu占用还是很高。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34230652/261a4619-e678-4ac5-a9f5-03f9fa30c27f)

i7-14700kf 32G RAM 4070TI SUPER
已安装cuda 12.4 
单开 MUMU 模拟器打肉鸽

**Comment by ABA2396** [comment]
#9236
