### ISSUE TITLE
请问现在哪个模拟器截图方式耗时最短?

### ISSUE THREAD

**Issue by gdf159159** [MaaAssistantArknights/MaaAssistantArknights#7493]
### 说说你遇到的问题？

我看新增了一个截图测试耗时

我用的雷电显示666ms

pr 的那个180ms是什么模拟器?

影响截图效率的最大因素是电脑配置还是模拟器兼容性?

**Comment by Constrat** [comment]
Main reason is related to the computer hardware you are using.
Faster processor means faster screen times. The emulator can only change so much. Usually it either works (with decent times) or it directly doesn't work
