### ISSUE TITLE
有关自动给好友送线索的

### ISSUE THREAD

**Issue by HugeHamster-YWang** [MaaAssistantArknights/MaaAssistantArknights#7495]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我不知道这玩意有没有必要改，但是maa昨天给我同一个好友送了3个线索7被吐槽了
![W4SPHCD{L5U@C4M6S_O J)J](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121331408/63a1b9b1-4c67-451d-9acd-f06c4e1f9e88)

### 有什么好的想法？

emm不太明白现在舟送线索界面是怎么排序的，也不太明白送线索的算法，但是是不是可以加一些随机翻页来规避这种情况？

### 其他内容

太麻烦就算了，也不是什么大问题
_No response_

**Comment by ABA2396** [comment]
~是故意的~
选的是最上面的三张吧，那个好像是按时间来的
