### ISSUE TITLE
繁中服 自動肉鴿卡住

### ISSUE THREAD

**Issue by cwc02777** [MaaAssistantArknights/MaaAssistantArknights#7497]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我目前是用雷電(9.0.29)
其他功能都很正常，唯獨自動肉鴿，之前使用也沒問題
但最近想繼續用的時候發現，MAA前面選關什麼的都很正常
但進入戰鬥後就完全不會動，也不會放幹員，直到任務失敗也都沒反應
再過一陣子模擬器就會整個卡死
看log發現，MAA似乎一直在送adb指令，但就是沒任何反應

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13587079/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/15338376/275eb1f1-44ef-4f4f-955c-9e9ddde2caba)

### 还有别的吗？

系統：window 10 專業版 21H2
模擬器：雷電9 (9.0.29)
CPU：i5-13500
RAM：64GB
GPU：RTX 3060 Ti

**Comment by Constrat** [comment]
If MAA is working, but the emulator is struggling to keep a decent framerate there really is nothing MAA can do.

**Comment by TimCrownie** [comment]
雷電模擬器/LDPlayer存在長時間使用時RAM溢出的問題，但是你這邊的表現並不像。
看日誌文檔顯示是在用1600*900，但是這個也是16:9…按理說不應該是這裡出問題。
