### ISSUE TITLE
MAA账号切换问题

### ISSUE THREAD

**Issue by AzzyDreamurr** [MaaAssistantArknights/MaaAssistantArknights#7499]
### 说说你遇到的问题？

我看了MAA的说明文档, 里面没有说明切换账号是否支持多个账号..(账号A全套代理完后根据写好的账号切换至账号B进行代理这种)
如果可以的话, 账号需要使用什么分隔符分开?

**Comment by ABA2396** [comment]
只能填一个，多账号可以在 设置-切换配置 里新建配置
