### ISSUE TITLE
在非三星结算时未能正常终止

### ISSUE THREAD

**Issue by Chiichen** [MaaAssistantArknights/MaaAssistantArknights#7503]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在如果是最后一个怪进入目标点导致的非三星结算无法自动终止

### 有什么好的想法？

如果是抄作业的话能不能加一个可选字段来表示这个时候应该站场的某些核心干员，如果不在场上了就认为无法完成这个任务就退出，自动战斗的话倒还没想到好的办法

**Comment by status102** [comment]
当前未设计非三星结算时自动退出关卡
