### ISSUE TITLE
建议加入“一键长草”和“自动战斗”任务完成后可选的Windows通知提醒功能

### ISSUE THREAD

**Issue by chy5301** [MaaAssistantArknights/MaaAssistantArknights#7507]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

每次把MAA打开后进行一键长草和战斗任务任务时（尤其是使用自动战斗退新图的场景）一般会把模拟器和MAA都切后台挂着去做其他事情。经常一切走就忘记切回来了，等一两个小时后反应过来任务已经结束很久了。

### 有什么好的想法？

可以增加在Windows通知弹出相关的提醒信息的功能，并且在设置任务时可以选择通知功能是否开启。

**Comment by chy5301** [comment]
查看设置注意到有“外部通知”的设置，但是没有一个可以方便的在“一键长草”和“自动战斗”界面设置的“任务已完成”的Windows系统通知功能

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/dd7ba5bc-59a9-4457-ac03-52d29fa13be2)
这个在任务完成的时候不是会有windows的吐司通知吗？
