### ISSUE TITLE
日服基建换班无法正确识别萃羽赫默，斥罪

### ISSUE THREAD

**Issue by 53nemu** [MaaAssistantArknights/MaaAssistantArknights#7508]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建换班无法正确识别萃羽赫默，斥罪，麒麟夜刀，火龙黑角

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13610544/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13610546/gui.log)

### 还有别的吗？

日服，雷电9模拟器，分辨率1280*720

**Comment by 53nemu** [comment]
在使用了4.28.0-beta1版本后仍然无法正确识别麒麟夜刀，火龙黑角和萃羽赫默已可以正确识别
麒麟夜刀和车尼尔依旧无法正常识别

**Comment by ABA2396** [comment]
再来个日志

顺便是车尔尼不是车尼尔

**Comment by TimCrownie** [comment]
> 再来个日志
> 
> 顺便是车尔尼不是车尼尔

再顺便
是淬羽赫默不是翠羽赫默（？）

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/1441e0e4-9291-405c-b7d5-328c651f464b)
草，被认成林了）

**Comment by ABA2396** [comment]
麦哲伦那个是因为刷信赖的表情会挡住名字，如果开了的话就不能在后面指定干员了

**Comment by 53nemu** [comment]
> 麦哲伦那个是因为刷信赖的表情会挡住名字，如果开了的话就不能在后面指定干员了

ご返信ありがとうございます。
刚才测试了下，斥罪还是不能识别，我把日志也传了上来
同时建议的刷信赖会影响加工站干员更换的问题，这份日志上我是关闭了刷信赖选项的，加工站不能正确更换年，也可以麻烦再确认一下吗，谢谢
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13612961/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13612978/gui.log)

**Comment by ABA2396** [comment]
加工站那个日志我没看懂
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/d12ea181-c432-4052-8d99-45819fa433a6)
照理来说会先输出下设施名，类似这样
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/e0b75941-ea18-402a-aaee-e2539f4f35b7)
重启下maa然后重跑一遍基建，如果还有问题的话再发一下日志

**Comment by 53nemu** [comment]
> 加工站那个日志我没看懂 ![image](https://private-user-images.githubusercontent.com/99072975/289061761-d12ea181-c432-4052-8d99-45819fa433a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMzk2MDAsIm5iZiI6MTcwMjAzOTMwMCwicGF0aCI6Ii85OTA3Mjk3NS8yODkwNjE3NjEtZDEyZWExODEtYzQzMi00MDUyLThkOTktNDU4MTlmYTQzM2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDEyNDE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZjQyZGQ5MDdiNzQ4NjZhOGI4MThmOWE3NmE1OTg1MzRlMTZlMzQyN2E3ZDY4Mzk5ZjcwYzg2MTNjNGFhYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c02xWc8tOImyRxmuO4y9oZhrxj1pb2eFiPKjanhVaiU) 照理来说会先输出下设施名，类似这样 ![image](https://private-user-images.githubusercontent.com/99072975/289062208-e0b75941-ea18-402a-aaee-e2539f4f35b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMzk2MDAsIm5iZiI6MTcwMjAzOTMwMCwicGF0aCI6Ii85OTA3Mjk3NS8yODkwNjIyMDgtZTBiNzU5NDEtZWExOC00MDJhLWFhZWUtZTI1MzlmNGYzNWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDEyNDE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYjJjYTlhYTcyMTAyZWZlZDIwMzM4ODI4OTZjYjhkOWI0YmFlMDBiMjNjMmM0MGU2YjllYjEwNjhmYWMyY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qgQzB2m5oNMo6YaQmSIcs2aP7--etwKBQ-LJdq7vwSM) 重启下maa然后重跑一遍基建，如果还有问题的话再发一下日志

谢谢回复，依旧是一样的情况，同时附上截图，运行基建换班（在高级设置中只勾选加工站）之后
MAA会迅速选择第一层从左数起第二个房间，然后不断向左划，日志内容和上次上传的相同
勾选会客室办公室加工站，之前部分运行正常，但是加工站和上述一样的出错内容和表现，所以应该不是只勾选加工站出现的问题
麻烦您再帮忙确认一下，谢谢
环境是雷电9
![Screenshot_20231208-214650](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153263868/1162c12e-f434-413a-bf90-f0cfbd29c6ad)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13614211/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13614214/asst.log)

**Comment by 53nemu** [comment]
[1702039526448305.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13614574/1702039526448305.json)
测试用的排班表

**Comment by ABA2396** [comment]
> 谢谢回复，依旧是一样的情况，同时附上截图，运行基建换班（在高级设置中只勾选加工站）之后 MAA会迅速选择第一层从左数起第二个房间，然后不断向左划，日志内容和上次上传的相同 勾选会客室办公室加工站，之前部分运行正常，但是加工站和上述一样的出错内容和表现，所以应该不是只勾选加工站出现的问题 麻烦您再帮忙确认一下，谢谢 环境是雷电9 
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13614211/gui.log) 
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13614214/asst.log)

这份里面的asst.log失效了

**Comment by 53nemu** [comment]
> > 谢谢回复，依旧是一样的情况，同时附上截图，运行基建换班（在高级设置中只勾选加工站）之后 MAA会迅速选择第一层从左数起第二个房间，然后不断向左划，日志内容和上次上传的相同 勾选会客室办公室加工站，之前部分运行正常，但是加工站和上述一样的出错内容和表现，所以应该不是只勾选加工站出现的问题 麻烦您再帮忙确认一下，谢谢 环境是雷电9
> > [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13614211/gui.log)
> > [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13614214/asst.log)
> 
> 这份里面的asst.log失效了

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13622655/asst.bak.log)
已重新上传，不好意思，麻烦你了

**Comment by ABA2396** [comment]
得来两张加工站的图
原始大小和点了Notification之后缩小的图
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/b30c3abc-c4c8-41b8-bf54-f42e6e84fa74)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/caf50d81-0d82-452f-9e85-8aa88d7d07b9)

**Comment by ABA2396** [comment]
加工站是后加的，只有官服和en的图
The processing station is a later addition, with only official and en
cc @Constrat

**Comment by Constrat** [comment]
Manufacturing station doesn't work for JP?
I don't have a JP account unfortunately

**Comment by 53nemu** [comment]
![Screenshot_20231209-164033](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153263868/fc5d710d-27e7-40bf-80e8-9b864936f1eb)
![Screenshot_20231209-164023](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153263868/339f2b08-374e-4ac4-834d-c934fdd48927)
大概是这样

**Comment by ABA2396** [comment]
全部拉到最右边然后截图，就像我上面发的两张一样

**Comment by 53nemu** [comment]
![Screenshot_20231209-172603](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153263868/ac69da35-f58a-4bc4-b6ed-230e5c6a7361)
![Screenshot_20231209-172613](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153263868/d10d202c-946f-4cc1-a89d-6298154465fe)
这样可以吗

**Comment by ABA2396** [comment]
`InfrastProcessing`
![InfrastProcessing](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/6b7a56f8-e802-46c7-9283-a63727bd6d0a)

`InfrastProcessingMini`
![InfrastProcessingMini](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/d7467d9b-9e37-4448-b598-afd98df45dd9)

试试把这两个放到 \resource\global\YoStarJP\resource\template 文件夹里

**Comment by Constrat** [comment]
> `InfrastProcessing` ![InfrastProcessing](https://private-user-images.githubusercontent.com/99072975/289268784-6b7a56f8-e802-46c7-9283-a63727bd6d0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjIwMjAsIm5iZiI6MTcwMjEyMTcyMCwicGF0aCI6Ii85OTA3Mjk3NS8yODkyNjg3ODQtNmI3YTU2ZjgtZTgwMi00NmM3LTkyODMtYTYzNzI3YmQ2ZDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDExMzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMTBhMDhmMGY2OWZjZTM2NmRjOWQ0ZDUyNjcyMWZmOWMzZDFjZDAyOGE4MGVkZWE3OWZmY2JiMzg0ZjBmOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9g_1vDHH3mTEbAeSUxX7X2mCvdhFFTJeQolJ-qoX5BE)
> 
> `InfrastProcessingMini` ![InfrastProcessingMini](https://private-user-images.githubusercontent.com/99072975/289268787-d7467d9b-9e37-4448-b598-afd98df45dd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjIwMjAsIm5iZiI6MTcwMjEyMTcyMCwicGF0aCI6Ii85OTA3Mjk3NS8yODkyNjg3ODctZDc0NjdkOWItOWUzNy00NDQ4LWI1OTgtYWZkOThkZjQ1ZGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDExMzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NzM5YWUzYzQyZDg2NDMxNThjNDg0MDc2ODljYWJiYjA4ZjA3ZWVlNjU0OTE5YTY0OGMxYTUzOGYwYjhmYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zSxDmPnmGv3IUmpxijqJWkJuwpc1UuxfODO_KuZEP_8)
> 
> Try putting these two in the \resource\global\YoStarJP\resource\template folder

You think the template masking is not enough?

**Comment by ABA2396** [comment]
official：`加工站`
jp：`加工所`

**Comment by 53nemu** [comment]
感谢处理，已经可以正常交换了
这个list下的问题已经全部解决了，谢谢aba2396様和Constrat様

**Comment by Constrat** [comment]
Oooooh it was the `processing` (`workshop` localized, my bad, I thought manufacturing, I forgot).
