### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by Abigail000000** [MaaAssistantArknights/MaaAssistantArknights#7509]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

什么方法都试了换了模拟器也不行，求帮忙看一看谢谢

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13612190/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13612192/gui.log) 

### 截图

![IJZD) G2LTQB~RBS{`V7LM7](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153182695/2e56cb2b-ea98-436f-ab7a-6259b378adef)

**Comment by ABA2396** [comment]
看日志里一直报的adb.exe: device unauthorized.雷电有USB调试开关吗?感觉很少见有模拟器报未授权的，有装什么手机助手吗，有试过重启电脑和管理员权限启动maa吗

**Comment by Abigail000000** [comment]
> 看日志里一直报的adb.exe：设备未授权。雷电有USB调试开关吗？感觉很少见有模拟器报未授权的，有装什么手机助手吗，有尝试过重启电脑和管理员启动权限maa吗

你好，雷电没有USB调试开关，管理员重启都试过了，没有装手机助手

**Comment by ABA2396** [comment]
cc @MistEO
