### ISSUE TITLE
关于日志生成

### ISSUE THREAD

**Issue by soundofautumn** [MaaAssistantArknights/MaaAssistantArknights#751]
能不能创建个logs文件夹，最新的日志记为latest.log，然后每次启动就把之前的日志重命名为log-1.log，log-2.log等等等，再在latest.log中记录最新的日志，感觉这样对排查问题什么的会方便的，毕竟一般需要的只有最新的（

**Comment by ABA2396** [comment]
那还不如直接日期）

**Comment by soundofautumn** [comment]
也可以（

**Comment by MistEO** [comment]
现在不就是吗（

**Comment by ABA2396** [comment]
> 现在不就是吗（

他说的是log的名字，现在只有一个log和bak.log

**Comment by soundofautumn** [comment]
？原来是这样的吗，但我上次用python连好像就是原log追加，是每次启动maa重置吗

**Comment by MistEO** [comment]
> ？原来是这样的吗，但我上次用python连好像就是原log追加，是每次启动maaGui重置吗

每次启动会检查文件大小，超过 4M 会新建一个

**Comment by soundofautumn** [comment]
但其实之前的日志基本上没什么用，不如直接开新的（

**Comment by MistEO** [comment]
有用的，用户大多数不是一出问题立马就来提 issue, 如果直接开新的，等他们发来的时候日志早就不知道在哪个文件了。总不能把一堆都发出来

**Comment by soundofautumn** [comment]
啊这
