### ISSUE TITLE
烧热水，打到第三层就退出”有bug

### ISSUE THREAD

**Issue by github123520** [MaaAssistantArknights/MaaAssistantArknights#7510]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

选择 水月肉鸽 “烧热水，打到第三层就退出”有bug，会出现 模拟器截图延迟过高，无法开启探索的问题
选择另外两个选项则没问题 分别是 第二层就退出 多打几层 这两个

### 日志文件

1

### 截图

1

### 还有别的吗？

1

**Comment by status102** [comment]
> @status102 Only that start is locked behind the screencap delay? Doesn't make sense? Also, no logs, can't help.

I don't know what he said. I just added printed messages, no block, no extra thing.

And,
为什么连截图都不舍得给？翻了下你提的所有issue，从来不提供日志，这样没法定位问题

**Comment by status102** [comment]
为什么连截图都不舍得给？翻了下你提的所有issue，从来不提供日志，这样没法定位问题

**Comment by github123520** [comment]
> 为什么连截图都不舍得给？翻了下你提的所有issue，从来不提供日志，这样没法定位问题

非常抱歉 今天我会尝试重新复现bug并且提供日志
