### ISSUE TITLE
夜神模拟器、mumu12模拟器adb连接失败

### ISSUE THREAD

**Issue by therryuer** [MaaAssistantArknights/MaaAssistantArknights#7516]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

试过夜神模拟器和mumu模拟器都不成功，也切换过触控模式、试过管理员启动和自动检测连接。问题是昨晚出现的，中间也重装了一次MAA，而且其他脚本adb连接是正常的。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13622934/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13622935/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/109951122/18c88d54-9506-4559-aab3-87912bf89e1b)

**Comment by ABA2396** [comment]
看日志一直创建进程失败
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/0cb47fe3-e23c-4ea6-b103-20895576045b)
这个玩意应该不是maa能解决的。
有试过重启电脑后手动选择对应模拟器的adb和填写对应端口吗？可以在cmd中试试输入
 ```
"C:\Program Files\Netease\MuMuPlayer-12.0\shell\adb.exe" connect 127.0.0.1:16384
```
看看能不能连上，地址填自己的adb路径英文引号框起来，端口换成对应模拟器的端口，如果是重启电脑后连接成功的话应该会是这样的输出
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/91133d3f-5507-444d-abae-c30e430d1ed3)

> 其他脚本adb连接是正常的

adb要求要和其他软件用的同一个adb，不然不同版本的adb启动会关闭其他的adb导致连接失败

**Comment by therryuer** [comment]
![屏幕截图 2023-12-10 101315](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/109951122/8ab86182-9ae5-4acf-aebf-c95b9a2ced30)
填上两个模拟器的端口运行后都是这个输出，MAA也还是连不上。

**Comment by ABA2396** [comment]
cc @MistEO

**Comment by cwc02777** [comment]
這有可能是adb.exe 的問題
我之前用雷電很正常都可以連線
今天想說換夜神也是這樣
最後我是指定使用雷電的 adb 然後用夜神開 就正常了
你可以試試看，看哪個模擬器的adb可以用，或是去找通用adb看看

**Comment by therryuer** [comment]
> 這有可能是adb.exe 的問題 我之前用雷電很正常都可以連線 今天想說換夜神也是這樣 最後我是指定使用雷電的 adb 然後用夜神開 就正常了 你可以試試看，看哪個模擬器的adb可以用，或是去找通用adb看看

我现在一头雾水😂

**Comment by ABA2396** [comment]
看log里应该是已经强制替换过adb了，用的就是谷歌的那个adb了，要么自己下一个然后放maa的文件夹里试试

**Comment by 610807421** [comment]
> ![屏幕截图 2023-12-10 101315](https://private-user-images.githubusercontent.com/109951122/289333757-8ab86182-9ae5-4acf-aebf-c95b9a2ced30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMzYzOTcsIm5iZiI6MTcwMjIzNjA5NywicGF0aCI6Ii8xMDk5NTExMjIvMjg5MzMzNzU3LThhYjg2MTgyLTlhZTUtNGFjZi1hZWJmLWM5NWI5YTJjZWQzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxOTIxMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGNlMGFlNTM2NzRkMTg4Nzk1MDY5ZTk4ZTU2ODgyN2MxZTRkNDM0NWFkNDc2NmVlYTZlZDQyMDc2YWQ2MWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ae-mSd0aLF72jc8JGqitU-PrQyFVAaDAe3HGd-TQbEE) 填上两个模拟器的端口运行后都是这个输出，MAA也还是连不上。

这个问题啊，我一个月总会遇到两三次。是adb服务器的问题。只需要手动输入“adb disconnect 无法连接的模拟器", 然后再重新输入"adb connect 无法连接的模拟器" 就行了
说白了就是adb连接已断开, 但系统误以为连接依然存在. 手动断开再重连就行了

**Comment by therryuer** [comment]
> > ![屏幕截图 2023-12-10 101315](https://private-user-images.githubusercontent.com/109951122/289333757-8ab86182-9ae5-4acf-aebf-c95b9a2ced30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMzYzOTcsIm5iZiI6MTcwMjIzNjA5NywicGF0aCI6Ii8xMDk5NTExMjIvMjg5MzMzNzU3LThhYjg2MTgyLTlhZTUtNGFjZi1hZWJmLWM5NWI5YTJjZWQzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxOTIxMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGNlMGFlNTM2NzRkMTg4Nzk1MDY5ZTk4ZTU2ODgyN2MxZTRkNDM0NWFkNDc2NmVlYTZlZDQyMDc2YWQ2MWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ae-mSd0aLF72jc8JGqitU-PrQyFVAaDAe3HGd-TQbEE) 填上两个模拟器的端口运行后都是这个输出，MAA也还是连不上。
> 
> 这个问题啊，我一个月总会遇到两三次。是adb服务器的问题(不过也有可能是MAA断开adb连接的时候产生了bug)。只需要手动输入“adb disconnect 无法连接的模拟器", 然后再重新输入"adb connect 无法连接的模拟器" 就行了 说白了就是adb连接已断开, 但系统误以为连接依然存在. 手动断开再重连就行了

还是不行，有空了试试重装模拟器得了😂

**Comment by a0wsxz9** [comment]
> > ![屏幕截图 2023-12-10 101315](https://private-user-images.githubusercontent.com/109951122/289333757-8ab86182-9ae5-4acf-aebf-c95b9a2ced30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMzYzOTcsIm5iZiI6MTcwMjIzNjA5NywicGF0aCI6Ii8xMDk5NTExMjIvMjg5MzMzNzU3LThhYjg2MTgyLTlhZTUtNGFjZi1hZWJmLWM5NWI5YTJjZWQzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxOTIxMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGNlMGFlNTM2NzRkMTg4Nzk1MDY5ZTk4ZTU2ODgyN2MxZTRkNDM0NWFkNDc2NmVlYTZlZDQyMDc2YWQ2MWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ae-mSd0aLF72jc8JGqitU-PrQyFVAaDAe3HGd-TQbEE) 填上两个模拟器的端口运行后都是这个输出，MAA也还是连不上。
> 
> 这个问题啊，我一个月总会遇到两三次。是adb服务器的问题(不过也有可能是MAA断开adb连接的时候产生了bug)。只需要手动输入“adb disconnect 无法连接的模拟器", 然后再重新输入"adb connect 无法连接的模拟器" 就行了 说白了就是adb连接已断开, 但系统误以为连接依然存在. 手动断开再重连就行了

还真是，亲测太有用了。手动断开重连再用maa就连上了！多谢。

**Comment by ABA2396** [comment]
> 这个问题啊，我一个月总会遇到两三次。是adb服务器的问题(不过也有可能是MAA断开adb连接的时候产生了bug)。只需要手动输入“adb disconnect 无法连接的模拟器", 然后再重新输入"adb connect 无法连接的模拟器" 就行了 说白了就是adb连接已断开, 但系统误以为连接依然存在. 手动断开再重连就行了

这种情况大概直接任务管理器里把adb.exe杀了会更快吧）

**Comment by a0wsxz9** [comment]
> > 这个问题啊，我一个月总会遇到两三次。是adb服务器的问题(不过也有可能是MAA断开adb连接的时候产生了bug)。只需要手动输入“adb disconnect 无法连接的模拟器", 然后再重新输入"adb connect 无法连接的模拟器" 就行了 说白了就是adb连接已断开, 但系统误以为连接依然存在. 手动断开再重连就行了
> 
> 这种情况大概直接任务管理器里把adb.exe杀了会更快吧）

不不不，杀adb进程是没用的，之前就试过几次了。唯一有用的一次就是像[610807421]说的一样。
