### ISSUE TITLE
应用崩溃问题

### ISSUE THREAD

**Issue by EtrusUp** [MaaAssistantArknights/MaaAssistantArknights#7517]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在使用MAA进行肉鸽挂机过程中出现了应用崩溃退出的情况，日志、系统日志如下（发生时间在12.9的中午11:25:45）

### 日志文件

发生时间在12.9的中午11:25:45
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13622932/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13622933/gui.log)

### 截图

![微信图片_20231209141148](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124549771/256e3ee9-3bf8-4e98-877d-509789f2a261)

### 还有别的吗？

mumu12v3.6.4
win11 22631.2792

**Comment by status102** [comment]
日志不包含所述时间段

**Comment by status102** [comment]
由于时间过久，日志大概率丢失且无法找回。如有复现请重新提issue，谢谢

**Comment by ABA2396** [comment]
崩溃之后应该还会有个dmp文件存下来的
