### ISSUE TITLE
自动代理肉鸽时模拟器闪退，但是还能听见游戏运行的声音

### ISSUE THREAD

**Issue by freeskywind** [MaaAssistantArknights/MaaAssistantArknights#7519]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

肉鸽刷钱的时候模拟器消失了，任务管理器的应用和后台程序里都找不到，但是还能听到游戏运行的声音，MAA上也没有异常提示，重启模拟器之后MAA才会提示与模拟器的连接断开。最近大概是12月10日10：30~10：50之间发生的，之前也发生过几次。不知道是模拟器的问题还是MAA。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13626337/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13626338/gui.log)

### 还有别的吗？

夜神模拟器7.0.5.6，win10。

**Comment by Constrat** [comment]
MAA will not crash the emulator, unless something strange happens with ADB, but this has never happened directly before.
The only way can affect this is if the system is not powerful enough to keep MAA template resources and the emulator.
