### ISSUE TITLE
关卡导航技能-5会卡在终端页面

### ISSUE THREAD

**Issue by zhazha405** [MaaAssistantArknights/MaaAssistantArknights#752]
模拟器：BlueStacks 5 Nougat 64 位 (Hyper-V)
MAA：V3.9.3
情况：使用刷理智，关卡选择 技能-5，无法进到技能-5的关卡页面
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8839635/asst.log)
![Screenshot_2022 06 05_17 07 03 228](https://user-images.githubusercontent.com/13600095/172043525-05f8d9e5-9bd5-4384-a357-cbe01310a9b1.png)
![5U6FQ942J$1ZCH~}3JC FJN](https://user-images.githubusercontent.com/13600095/172043526-19948df1-3ac1-446a-81a3-2aa7fac638d6.png)

**Comment by ABA2396** [comment]
已经修了，还没发，别的issue里提过了

**Comment by ABA2396** [comment]
现在要用的话可以去dev分支下把task.json下载下来替换掉

**Comment by zhazha405** [comment]
> 现在要用的话可以去dev分支下把task.json下载下来替换掉

了解，感谢
