### ISSUE TITLE
SSS LT-n stage_name standardization

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#7522]
### Discussed in https://github.com/orgs/MaaAssistantArknights/discussions/7342

<div type='discussions-op-text'>

<sup>Originally posted by **status102** November 18, 2023</sup>
```
[2023-11-18 16:22:01.810][TRC][Px5da4][Tx18e4] │││││ asst::WordOcr [{ 海涎.: [ 0, 0, 149, 43 ], score: 0.860574 }] by OCR Rec , cost 16 ms
[2023-11-18 16:22:01.811][TRC][Px5da4][Tx18e4] │││││ Proced [{ 海涎.: [ 129, 261, 149, 43 ], score: 0.860574 }]
[2023-11-18 16:22:01.811][TRC][Px5da4][Tx18e4] ││││└ asst::SSSStageManagerTask::analyze_stage | leave, 211 ms
```
LT-n 可以减少翻译问题、以及可能可以减少错误识别问题</div>

**Comment by Constrat** [comment]
```json
    "SSSStageNameOCR": {
        "roi": [
            33,
            272,
            80,
            36
        ],
```

```json
...
    "stages": [
        {
            "stage_name": "LT-1",
            "strategies": [
                {
                    "tool_men": {
                        "pioneer": 1
...
```

**Comment by Constrat** [comment]
@ABA2396 What was the issue / fear you had? Because if there are no major concerns, I'll just adapt everything and completely move it to this "new" structure, as it seems much more flexible, standardized and easier to maintain especially for overseas.

**Comment by Constrat** [comment]
@status102 is the location of LT-`n` equal to EN's?
```
roi
33,
272,
80,
36
```

**Comment by status102** [comment]
how does MAA distinguish it from 10 stages?
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/5bee1466-8765-47ce-8b42-b0f7102bbbed)

**Comment by status102** [comment]
看上去只能让每个关卡同时拥有两个字段以标识OCR代号和实际代号，像这样
```
            "ocr_name": "LT-1",
            "stage_name": "lt_01_01",
```

**Comment by status102** [comment]
LT-4需要大一些的范围，location是对的

或许：
```
33,
272,
90,
36
```

**Comment by status102** [comment]
看起来是一个Break change，感觉要放到大版本变更（指天国的v5.0.0

**Comment by ABA2396** [comment]
现在不是用的stage name吗，那只要加上那两个字段就可以了吧，没有就还是看stage name

**Comment by status102** [comment]
> 现在不是用的stage name吗，那只要加上那两个字段就可以了吧，没有就还是看stage name

stage_name就需要翻译加翻译，最好就干脆一起改掉移除了

- #7525 
而且本来文档里面说的支持stageId和levelId，看了一圈跑了下实际上不行

**Comment by ABA2396** [comment]
那就协议里说一句已废弃，仅供兼容老版本，然后把作业都改成新格式
