### ISSUE TITLE
外文文档目录结构需要更新 | Document translation and directory structure refactoring required

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#7524]
### 说说你遇到的问题？

#7423 对简中文档目录结构重构后，结构不一致，且由于没有编号，有时候不知道文档对应哪个

**Comment by SherkeyXD** [comment]
我当时本来想一起改的，但是发现有几个文档其他语言的版本甚至没有，于是就搁置了

**Comment by status102** [comment]
> 我当时本来想一起改的，但是发现有几个文档甚至没有其他语言的版本，于是就搁置了

感觉文件名可能还是要一个x.x或者类似的标号，方便找

**Comment by SherkeyXD** [comment]
现在 frontmatter 里面写了 order 作为文件夹内的排序，可以拿那个作为参考（

**Comment by SherkeyXD** [comment]
要不要 pin 起来摇人翻译（

**Comment by status102** [comment]
~~直接机器翻译~~

**Comment by Rbqwow** [comment]
btw readme里面的文档链接全都404了🤨

**Comment by SherkeyXD** [comment]
> 是非release不会更新文档吗

对的，只有发版流程会更新文档
