### ISSUE TITLE
关于VS编译器在Debug x64下在Logger.hpp中报“无法推导模板类参数”的问题

### ISSUE THREAD

**Issue by LoserFeng** [MaaAssistantArknights/MaaAssistantArknights#7526]
### 说说你遇到的问题？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/77104026/7915a834-c36c-4381-b465-dec160a57399)

为什么VS编译器会报这个错误，但是编译却能够通过，本人C++萌新，求救QAQ

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/45f1d242-faee-4561-bfa3-b8ffe4ced262)

**Comment by LoserFeng** [comment]
QAQ
