### ISSUE TITLE
<自动肉鸽>可以通过右键选中仅运行一次

### ISSUE THREAD

**Issue by shawnyuan-cn** [MaaAssistantArknights/MaaAssistantArknights#7528]
### 有什么好的想法？

* 肉鸽其实是不需要做到日常挂机的，即便每月奖励更新后也只需要运行个5~7次就能拿完奖励。
* 于是，希望可以实现<自动肉鸽>通过右键选中仅运行一次，当然最好也能在MAA处于运行状态下也能取消锁定实现勾选。
以此来**节省短期内反复设置的操作**。

**Comment by SherkeyXD** [comment]
<img width="600" alt="865f343a7696d6446319686d6078f502" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57581480/0dc66baf-e11b-4aa9-8358-026ca1d317bb">

你可以这么做

**Comment by ABA2396** [comment]
> 你可以这么做

他的意思是这个设成5然后月初找个时间把日常和肉鸽一起挂了然后自动恢复只刷日常的样子吧）

**Comment by shawnyuan-cn** [comment]
> 他的意思是这个设成5然后月初找个时间把日常和肉鸽一起挂了然后自动恢复只刷日常的样子吧）

@SherkeyXD 
我也是这个意思，肉鸽是不需要像每日一样反复刷的，而脚本运行状态下<自动肉鸽>是锁定的，必须先停止后选中再运行，不需要刷肉鸽了又要再取消选中，所以才形容是“短期内反复设置”。
因此才提出像现在已经有的功能，类似<吃理智药>一样可以通过右键仅运行一次来优化。
<div align=left><img src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105029931/372a74a2-cd56-48a9-bddf-7306dcf7bf1c" width="500"></div>

**Comment by ABA2396** [comment]
这两个勾选框的实现逻辑不太一样，得看看怎么搞

**Comment by status102** [comment]
> 这两个勾选框的实现逻辑不太一样，得看看怎么搞

右键任务的设置直接追加一个该任务（就不要加一列按钮了
