### ISSUE TITLE
识别物品错误

### ISSUE THREAD

**Issue by IranksAdral** [MaaAssistantArknights/MaaAssistantArknights#753]
![XCE PYB1VJZ0 %`ZO3SXFJ8](https://user-images.githubusercontent.com/87361258/172050639-4f189670-3740-4a68-a72f-aa3e67415a0d.png)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8839956/asst.zip)
MUMU模拟器偶尔会出现识别错误，这个是在刷SV-9的时候掉了装置却没法识别的问题……
版本应该是v3.9.3

**Comment by MistEO** [comment]
看了下日志没获取到什么有用的信息，需要图片看一下咋回事。但是好像出现的概率不高？我看你日志里刷了很多只有这一次报错的

加了个识别错误自动保存图片的功能，在 err 文件夹下面，（需要更新今天之后的版本），下次再遇到帮忙发下图片看看_(:з」∠)_

**Comment by MistEO** [comment]
很可能是桃金娘背景的时候，掉落了家具和材料。今天遇到这个 case 了，已修复~
