### ISSUE TITLE
萨米肉鸽，maa哪个分队哪个初始角色通关率比较高？

### ISSUE THREAD

**Issue by atkdefender** [MaaAssistantArknights/MaaAssistantArknights#7531]
### 说说你遇到的问题？

box依据强度榜较全
打到最终boss刚好吃完饭，坐下手动点几下总算首通了hiahiahia

**Comment by Constrat** [comment]
Leaving everything as default already has the higher % of clearing.
+
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/ea8d48f6-7b2f-4d03-9edc-c4493af55439)
