### ISSUE TITLE
肉鸽中关于处决者的行为

### ISSUE THREAD

**Issue by lbgod2222** [MaaAssistantArknights/MaaAssistantArknights#7533]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

最近才使用MAA，需求主要集中在肉鸽。目前三类肉鸽的干员抓取有极大概率会选择翼德，但是翼德的使用就目前来看相当死板，似乎只会在相应的位置重复拔插干员，往往在战斗中发挥作用很小。

### 有什么好的想法？

**1：他能针对精英怪或者BOSS旁边位置重复拔插** 
**2：在敌方单位靠近蓝门时再响应式的拔插**

**Comment by ABA2396** [comment]
现在没有做敌人位置的识别
