### ISSUE TITLE
基建换班使用"自定义排班"时, 在某些情况下无法按照排班表中的时间选择方案

### ISSUE THREAD

**Issue by 610807421** [MaaAssistantArknights/MaaAssistantArknights#7539]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我写了一份一天换5次班的排班表, 每天18:00时定时启动, 在基建内放入第四次班干员. 但MAA总是在这一次计划任务中, 错误的选择班次方案, 15:00-17:59时段的第三班次干员. 
`"name":"15:00岁组合晚班","period":[["15:00","17:59"]]`
`"name":"18:00生产设施大班","period":[["18:00","23:59"],["00:00","00:59"]]`

15:00定时运行**可以**正确选择班次
`[2023-12-12 15:00:17.530][INF][Px11268][Txc3dc] asst::Assistant::append_task Infrast {"facility":["Control","Trade","Mfg","Power","Reception","Office","Processing","Dorm"],"drones":"Money","threshold":0.3,"dorm_notstationed_enabled":false,"dorm_trust_enabled":false,"replenish":true,"mode":10000,"filename":"C:\\Users\\zhuxinyu\\Desktop\\MAA-v4.11.0-win-x64\\Untitled-1.json","plan_index":2}`

18:00定时运行**无法**正确选择班次
`[2023-12-12 18:00:20.186][INF][Px11268][Txc3dc] asst::Assistant::append_task Infrast {"facility":["Control","Trade","Mfg","Power","Reception","Office","Processing","Dorm"],"drones":"Money","threshold":0.3,"dorm_notstationed_enabled":false,"dorm_trust_enabled":false,"replenish":true,"mode":10000,"filename":"C:\\Users\\zhuxinyu\\Desktop\\MAA-v4.11.0-win-x64\\Untitled-1.json","plan_index":2}`

在**18:00后手动运行**基建换班任务, 则**可以**正确选择班次方案.
`[2023-12-12 20:21:33.401][INF][Pxf354][Tx13d84] asst::Assistant::append_task Infrast {"facility":["Control","Trade","Mfg","Power","Reception","Office","Processing","Dorm"],"drones":"Money","threshold":0.3,"dorm_notstationed_enabled":false,"dorm_trust_enabled":false,"replenish":true,"mode":10000,"filename":"C:\\Users\\zhuxinyu\\Desktop\\MAA-v4.11.0-win-x64\\Untitled-1.json","plan_index":3}`

### 日志文件

由于重启过MAA, 18:00定时运行的log保存在备份log文件中
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13648119/asst.bak.log)
重启后手动运行任务产生的log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13648120/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13648121/gui.log)
排班表, 可用于测试
[Untitled-1.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13648152/Untitled-1.json)

### 还有别的吗？

我一开始以为是这一班的json时间格式错误, 从一图流网站的排班工具生成了一份排班表后, 确认格式应该是正确的, 但今天还是出错了

**Comment by ABA2396** [comment]
你这时间卡太好了，要不试试把定时改成18:01
