### ISSUE TITLE
自动作业选择干员问题

### ISSUE THREAD

**Issue by scyphozoax** [MaaAssistantArknights/MaaAssistantArknights#754]
_log文件以及其他信息我放在了最下面。_
# 问题具体内容
使用自动作业，在选择干员的时候出现了向后寻找直到最后一列干员也不停止的问题。
# asst.log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8840228/asst.log)
# 截图
![8 ZYSA~KMF5VPZ`C YL_E41](https://user-images.githubusercontent.com/50261377/172057824-d8a84137-0979-4f2b-97a2-62a9ba1cc602.png)

建议先默认取消自动编队的选项。。。。估计是因为一个类型中任选其一的干员选项太多造成的问题。。。

**Comment by scyphozoax** [comment]
截图中作业需要的干员我全都有

**Comment by MistEO** [comment]
你的日志怎么和截图不一致 orz

**Comment by scyphozoax** [comment]
> 你的日志怎么和截图不一致 orz 我看了半天才发现怎么对不上

不清楚，群里有作业文件可以运行一下看看

**Comment by ABA2396** [comment]
可以把日志删了重开一局看看
