### ISSUE TITLE
账号切换失败后续任务处理逻辑优化

### ISSUE THREAD

**Issue by Yunzhongzhulu** [MaaAssistantArknights/MaaAssistantArknights#7540]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如果由于电脑或网络卡顿等导致账号切换失败，maa继续在原账户进行接下来的活动显然会导致排班错乱、刷关错误、理智药源石误用等的问题

### 有什么好的想法？

若账号切换不为空，且切换任务出错，maa应该停止执行所有后续任务而不是继续尝试进行

**Comment by zzyyyl** [comment]
@status102

**Comment by status102** [comment]
看看是卡在哪里，只要是退到登录界面的话，后续任务都应该完成不了才是
