### ISSUE TITLE
游戏资源更新失败（index 1/2 正在编制索引）

### ISSUE THREAD

**Issue by UnfortunateFlame** [MaaAssistantArknights/MaaAssistantArknights#7541]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

产生BUG的具体操作流程：
1.照旧打开MAA点击Link start!
2.发现提示“游戏资源正在更新”（近段时间频发提示）
3.点击“停止”按钮意图让MAA进行“游戏资源更新”
4.紫字提示“游戏资源更新失败”
5.尝试过重启以及重新下载v4.27.1均无法解决问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13649868/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13649869/gui.log)

### 截图

![215defed86f1fa9238e1e602a9c38eb4](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/81245657/825aa25f-ace3-4bf5-ba03-5a9a51417324)
![b610e6758b368aad6292dda893c4ad98](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/81245657/506a4775-f55a-4c08-a5a5-223ef3df1529)

### 还有别的吗？

1.蓝叠模拟器
2.WIN10操作系统
3.默认ADB链接

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/6e430dd4-c588-44fa-9155-5b87486eb963)

**Comment by UnfortunateFlame** [comment]
> ![图像](https://private-user-images.githubusercontent.com/99072975/289933023-6e430dd4-c588-44fa-9155-5b87486eb963.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzEwODgsIm5iZiI6MTcwMjQzMDc4OCwicGF0aCI6Ii85OTA3Mjk3NS8yODk5MzMwMjMtNmU0MzBkZDQtYzU4OC00NGZhLTkxNTUtNWI4NzQ4NmViOTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDAxMjYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNzk1MDlmZDg3YzcxNjcwOWNjYjdmYzE3ODI4MmU2MzMzMTQyYzliZjRlMjM4ZTFjNzlkMGM3NjRiMTdlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4glXLGYtDnNNFuDyqfOYYIYaixSOv55GmWOwhKxJNeM)

收到
