### ISSUE TITLE
希望可以增加自动换训练室功能

### ISSUE THREAD

**Issue by rinadedi** [MaaAssistantArknights/MaaAssistantArknights#7544]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

训练到半夜得爬起来（
可不可以增加一下捕捉训练时间自动启动？
有小鸟的情况二级时能自动五小时左右前换人就更好了

**Comment by ABA2396** [comment]
~~没有自动换训练室，但是现在有自动收取和继续专精了~~
