### ISSUE TITLE
每次启动都提示：游戏资源更新失败，请稍后尝试。

### ISSUE THREAD

**Issue by shawn01234** [MaaAssistantArknights/MaaAssistantArknights#7546]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![QQ截图20231213103813](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35185500/34051050-735a-4f24-84fb-acb06e310a69)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13655253/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13655254/gui.log)

**Comment by ABA2396** [comment]
#7541 #7538
