### ISSUE TITLE
运行MAA时被识别病毒

### ISSUE THREAD

**Issue by QianZhouwww** [MaaAssistantArknights/MaaAssistantArknights#7547]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启动MAAv2.28.0-beta.2时被系统识别出病毒并停用，再次启动时报错

### 日志文件

[Uploading gui.log…]()
[Uploading asst.log…]()

### 截图

[bug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13655978/bug.zip)

**Comment by ArcturusYu** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40350185/25916418-1695-443f-a032-eb7235cdba2e)

**Comment by status102** [comment]
- #6662
