### ISSUE TITLE
Roguelike模式下会尝试在0抗干扰值时走竖向节点导致游戏卡死

### ISSUE THREAD

**Issue by hzxjy1** [MaaAssistantArknights/MaaAssistantArknights#7549]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如标题所示，推测问题为未对游戏提示框“抗干扰指数数量不足”进行模板识别

### 日志文件

[asst_log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13656152/asst_log.zip)

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50268154/1da49227-d852-48f6-976e-ef539f4d548f

### 还有别的吗？

操作系统：Archlinux
模拟器：Waydriod
maa版本：maa-cli v0.4.0 MaaCore v4.28.0-beta.2
问题报告出现在日志文件的第221223至226144行处。
以及可以考虑适当减少max_times的值。

**Comment by SherkeyXD** [comment]
Duplicate of #7241

**Comment by ABA2396** [comment]
要不先把全面勘察的板子去掉吧？之后在做这种节点的判断，除了砍坍缩也没别的用处了，少点功能也比卡死好）

**Comment by SherkeyXD** [comment]
检查一下抗干扰指数不好吗（

**Comment by ABA2396** [comment]
我看了下日志里也没有用到巡视啊，为什么会有勘察

**Comment by ABA2396** [comment]
翻了下wiki，说是部分节点不受上述影响始终处于标准勘察状态，那看样子是得做抗干扰的识别了

**Comment by Lancarus** [comment]
fix in #9223
