### ISSUE TITLE
运行着就把自己删掉了，连exe文件都没了

### ISSUE THREAD

**Issue by Rithen** [MaaAssistantArknights/MaaAssistantArknights#7552]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天打开电脑发现MAA关掉了，以为是闪退，结果发现桌面快捷方式没了，去找安装文件夹，exe可执行文件也没了。然后又来githhub下载了一次，更新之后，MAA运行着还在换基建就又是exe可执行文件也没了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13657413/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13657414/gui.log)

### 截图

![屏幕截图(12)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39794172/56e934b0-ca79-4668-a89d-7b5cbc95afd5)

**Comment by zzyyyl** [comment]
检查 Windows Defender

**Comment by hacker20070307** [comment]
老哥我也遇到了，目前我尚未修复这个问题，我用的是mumu模拟器12，win11系统，我个人认为是杀毒软件的问题，导致卸载的，但是我已经将文件放进白名单中，还是没用，不太清楚怎么回事

**Comment by Acture** [comment]
+1，刚刚碰到这个问题

**Comment by iceyisee2002** [comment]
+1，一样的情况，但当maa不是最小化时就不会出现这种情况

**Comment by moxingwusheng** [comment]
+1，我没最小化，结果它也没有了

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662
