### ISSUE TITLE
运行途中闪退，连exe文件都删除

### ISSUE THREAD

**Issue by ala-404** [MaaAssistantArknights/MaaAssistantArknights#7553]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

运行途中闪退，连exe文件都删除，该怎么解决?

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13657910/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13657926/asst.log)

**Comment by status102** [comment]
Duplicate of #7552
