### ISSUE TITLE
繁中服開啟生息演算

### ISSUE THREAD

**Issue by yokito0305** [MaaAssistantArknights/MaaAssistantArknights#7555]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

繁中服開始了生息演算，想請問是否能恢復生息演算的功能？

**Comment by ABA2396** [comment]
cc @momomochi987
#6267
src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs 里的服务器和开放时间也要改一下

**Comment by Constrat** [comment]
@momomochi987 when does Reclamation Algorithm: Fire within the Sand end? So, I can commit the corrected changes.

**Comment by Constrat** [comment]
@yokito0305 THIS JUST ADDS THE TASK OPTION
IT PROBABLY WILL NOT WORK AS NO ONE HAS ADAPTED IT YET.
I'm just adding the task so if someone wants to help, they can now do it.
@ABA2396 this will probably just create a lot of useless issues
