### ISSUE TITLE
自动战斗

### ISSUE THREAD

**Issue by hu1m** [MaaAssistantArknights/MaaAssistantArknights#7556]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用自动战斗功能，复制作业代码后点击开始显示未识别的关卡

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13658128/asst.zip)
时间点2023-12-13 16:16

### 截图

![R``P4L9LBV7LLX218X}7@03](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/149614705/04f004d4-0c42-436d-8515-26d606ebdc11)

**Comment by hu1m** [comment]
截图是下载json文件之后的情况，也显示为不支持

**Comment by ABA2396** [comment]
地图没更新，4271有几个图下不下来，如果点了设置里的检查更新还用不了的话先更新下公测版
