### ISSUE TITLE
mac版maa基建宿舍只会进驻一个人

### ISSUE THREAD

**Issue by uesakayou** [MaaAssistantArknights/MaaAssistantArknights#7558]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

几周前就遇到这个问题了，现在发现还没被修复，不会是mac限定吧（
maa在基建进驻宿舍时会一顿操作最后就进驻一个人，导致我心情崩盘，请看jpg（
试过更改设置都不行，重开游戏和maa也不行

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13658531/asst.log)

### 截图

![WX20231213-165557@2x](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/86504999/5bc182dd-419a-4b69-8c65-cfad1366e9da)
![WX20231213-165619@2x](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/86504999/db023b9c-8f3b-41a8-9e97-a66a58c776f7)

**Comment by ABA2396** [comment]
cc @hguandl 

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/42297978-be04-4084-ac43-76c6e2000080)
还有是不是应该给mac加个触控的日志，看log都不知道点了什么地方

**Comment by hguandl** [comment]
好，我看看其他Controller怎么写的日志

**Comment by uesakayou** [comment]
补充一下，目前基本不会出现1/5这样极端的情况了，偶尔看得见4/5
目前主要的表现情况：
宿舍换班之后有更低心情的干员没有被换进宿舍，但宿舍内已经填充了更高心情的或者满心情的用于蹭信赖的干员了
这种情况偶尔不会出现，但体感发生概率不低
但现在没法上传log，因为好像干员心情都满了，明天早上如果能复现我可以试试录屏顺便上传log

**Comment by uesakayou** [comment]
我现在因为需要nightly版playcover，没有使用原生的明日方舟而是mumu pro模拟器，貌似不会出现这种情况，我现在尝试下载旧版playcover

**Comment by uesakayou** [comment]
重新安装playcover和ipa后貌似不会复现了，不知道什么原因，但是貌似解决了？如果之后再出现我再提交吧
