### ISSUE TITLE
繁中服生息盐酸无法正确挂机

### ISSUE THREAD

**Issue by BoIeyn** [MaaAssistantArknights/MaaAssistantArknights#7566]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

区块选择节点后，不会进入，过一会就会退出放弃生息演算.

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13663273/asst.log)

**Comment by BoIeyn** [comment]
![2440872453](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/132142162/d5609323-f915-4431-90d4-bba900dec93e)
maa版本：4.28.0-beta2
模拟器：playcover 3.0.0.maa.4
服务器：繁中服
操作系统：macOS

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/bd2e064f-91d2-4b0d-abac-497a63b17bc3)

**Comment by Constrat** [comment]
@ABA2396 Isn't this issue similar to the one in the global? Where the iOS version wasn't working because the resources were not synced correctly? I might be remembering incorrectly.

**Comment by ABA2396** [comment]
> @ABA2396 Isn't this issue similar to the one in the global? Where the iOS version wasn't working because the resources were not synced correctly? I might be remembering incorrectly.

The macos portal should have been left open, this issue was raised when version 4280 was not yet released, even if #7559 works properly after that version is still not available.

**Comment by momomochi987** [comment]
@BoIeyn 把 MAA 更新到 4.28.0 再試試看?

4.28.0-beta2 沒有繁中的生息演算相關內容，4.28.0 才有
