### ISSUE TITLE
自定义基建配置groups干员编组无法使用

### ISSUE THREAD

**Issue by H-XZ** [MaaAssistantArknights/MaaAssistantArknights#7568]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用groups设置干员编组，"use_operator_groups":false 的房间可以正常读取首选干员并换班，设定为true无法正常换班，gui中不显示首选干员，一直向后滚动寻找干员并往复，无法选取编组干员。
[2天6班.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13663496/2.6.json)

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13663487/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13663489/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/118260498/d125649a-8665-4a5e-b41a-4ddbf7461998)

### 还有别的吗？

MuMu12模拟器，win10

**Comment by H-XZ** [comment]
> ```
> [2023-12-14 00:53:40.905][TRC][Px747c][Tx6138] asst::OcrPack::~OcrPack | enter
> [2023-12-14 00:53:40.905][TRC][Px747c][Tx6138] asst::OcrPack::~OcrPack | leave, 0 ms
> ```
> 
> log最后为0053，还没到0104。麻烦传一下包含换班的部分
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13670082/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13670083/gui.log)

抱歉，这是重新复现的log

**Comment by status102** [comment]
根据log看，还未完成遍历干员，可能后续会优化逻辑。

当前执行是要先遍历一遍干员确定可用的干员，然后才会进入换班
