### ISSUE TITLE
新版本安装包里有病毒

### ISSUE THREAD

**Issue by DaemoN-RSDK** [MaaAssistantArknights/MaaAssistantArknights#7569]
### 说说你遇到的问题？

我今天一起来就发现maa不能用了，查了半天最后选择重装，然后发现原来是安装包有病毒

**Comment by pramadito** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/13034156/ab401b6e-85b8-4b28-87d0-55159a0c7805)
virus found in this

**Comment by DaemoN-RSDK** [comment]
> ![image](https://private-user-images.githubusercontent.com/13034156/290345880-ab401b6e-85b8-4b28-87d0-55159a0c7805.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MDg4MTAsIm5iZiI6MTcwMjUwODUxMCwicGF0aCI6Ii8xMzAzNDE1Ni8yOTAzNDU4ODAtYWI0MDFiNmUtODViOC00YjI4LTg3ZDAtNTUxNTlhMGM3ODA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDIzMDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkOTA4NWMyYThiMjFhOTc0NTJhMzA3ZGJkMTY0YTc0NTMzNTBkMDM1ZDQwNWEyYzk1ZGJiODAwNWYyZTJkZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ppUw5bjc2WaWkvOz0129iwGDXFe3izVmIIijQj1iyM) virus found in this
> 
> ![image](https://private-user-images.githubusercontent.com/13034156/290346343-786d73dd-4e3f-4cd9-863f-68942179b7f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MDg4MTAsIm5iZiI6MTcwMjUwODUxMCwicGF0aCI6Ii8xMzAzNDE1Ni8yOTAzNDYzNDMtNzg2ZDczZGQtNGUzZi00Y2Q5LTg2M2YtNjg5NDIxNzliN2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDIzMDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMDUyNDA5NGZmOGI0YzYwMjEyODI3ZThmY2M3NmJjYTM1NmRiOWY5MjYxZjg4MWM3MWFlMmY3MDY0M2RlMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9ynrVLZYBt-iLOhdTxBvZG4FrGtpnWsRXlJdAUrgCAg)

Yes, it’s this one. Should I allow or just delete it?

**Comment by status102** [comment]
#6662
