### ISSUE TITLE
[Enhancement] 开机自启动选项及自动开始定时任务

### ISSUE THREAD

**Issue by lhhxxxxx** [MaaAssistantArknights/MaaAssistantArknights#757]
prec. feat. 开启模拟器

**Comment by ABA2396** [comment]
`控制面板`->`管理工具`->`任务计划程序`->`创建基本任务`
触发器选择MAA里定时启动的前几分钟

**Comment by cglcv** [comment]
程序开机自启动的话可以直接reg写注册表`计算机\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`
这个位置应该不需要管理员权限
