### ISSUE TITLE
近几个版本发生MAA运行一段时间后删掉自己的问题

### ISSUE THREAD

**Issue by binglingyao** [MaaAssistantArknights/MaaAssistantArknights#7574]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在近两个版本中,发生了MAA在运行一段时间后删掉自己的问题
- MAA.exe

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13667645/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13667647/gui.log)

### 还有别的吗？

-  MuMu12模拟器(V3.6.11(2438))
- 11th Gen Intel(R) Core(TM) i9-11900F @ 2.50GHz   2.50 GHz
- DDR4 3600MHz 32.0 GB

**Comment by masquevil** [comment]
绝了，maa 被 windows 检测报病毒，并且自己运行一段时间后会把自己删了… 不会真的被植入病毒了吧？

**Comment by SherkeyXD** [comment]
Duplicate of #6662

**Comment by Lin2heCh1** [comment]
我也遇到了 更新完 启动文件不见了。。。

**Comment by binglingyao** [comment]
附加信息: 查找了病毒隔离库,并未查到病毒警告,且未在病毒隔离中找到MAA.exe

**Comment by Xiaoqiduo** [comment]
windows defender报毒：Trojan:Win32/Wacatac.B!ml

**Comment by ABA2396** [comment]
#6662
