### ISSUE TITLE
开始挂机之后突然闪退，并且重新打开时maa.exe已经消失不见

### ISSUE THREAD

**Issue by soapmiku** [MaaAssistantArknights/MaaAssistantArknights#7575]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在开始挂机后不久，maa突然就闪退掉了，从快捷方式打开是提示已找不到maa.exe，到根目录后确实如此，删除maa重新安装了两三次，还是一样的问题。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115915351/3fdcaf48-56d7-45c2-9017-07373f5e8bd2)

### 日志文件

时间大概是在2023年10点24分左右闪退的
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13667819/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13667820/gui.log)

### 还有别的吗？

模拟器：蓝叠5国际版 5.13.215.1003 P64
系统： Windows 11 22621.2861

**Comment by ABA2396** [comment]
#6662
