### ISSUE TITLE
潜在病毒风险bug

### ISSUE THREAD

**Issue by 4nmos** [MaaAssistantArknights/MaaAssistantArknights#7577]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今早更新MAA后发现闪退之后不能用了，重启无法解决，重新下载安装包也不行，OS提示说存在潜在病毒风险，希望能解决

### 日志文件

无

### 截图

<img width="341" alt="屏幕截图 2023-12-14 120928" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115219802/596014cd-4ac6-4a63-a58b-c531d4ce50d0">

**Comment by ABA2396** [comment]
#6662
