### ISSUE TITLE
MAA 遇到了问题：无法加载 DLL“MaaCore.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。

### ISSUE THREAD

**Issue by DejaVu68** [MaaAssistantArknights/MaaAssistantArknights#7579]
版本：4.23.3（2023/12/24，更新的）
我看去年也有这个相同的issues，不知道最终是如何解决的。

详细信息
System.DllNotFoundException: 无法加载 DLL“MaaCore.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 MaaWpfGui.Services.MaaService.AsstGetVersion()
   在 MaaWpfGui.ViewModels.UI.VersionUpdateViewModel..ctor()
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   在 Stylet.BootstrapperBase.Start(String[] args)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

文件夹现状
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61177805/e86c020f-e5ee-4585-bc9d-dd686ef0e27f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61177805/fc31db37-2409-47f7-a7f5-9748b61c60a2)

**Comment by ABA2396** [comment]
.old文件夹里的东西不是给你用的，主目录下的maa.exe没了，看看是不是被windows defender删了

**Comment by tsctsc6** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/93368014/5ee8d2b9-f528-4161-b174-311a5b434894)

**Comment by ABA2396** [comment]
还原之后添加maa文件夹白名单就好了
