### ISSUE TITLE
是否可以考虑开发自定义基建排班功能

### ISSUE THREAD

**Issue by Nanofats-Teio** [MaaAssistantArknights/MaaAssistantArknights#758]
现版本尚不能完成跨设施最优换班，那么是否可以加入玩家可以自定义时间与换班角色的功能呢？如果能新增自定义排班功能，那么对极限效率无所谓的玩家可以继续用自动换班，而追求极限效率的也可以自行排班一劳永逸了。

**Comment by MistEO** [comment]
不会考虑，自定义排班对开发者和用户工作量都很大，有这时间不如去做全局最优解（~~已经新建文件夹了~~
