### ISSUE TITLE
MAA快捷方式打不开

### ISSUE THREAD

**Issue by DaemoN-RSDK** [MaaAssistantArknights/MaaAssistantArknights#7580]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 遇到了问题
无法加载 DLL“MaaCore.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
解决方案
请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.DllNotFoundException: 无法加载 DLL“MaaCore.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 MaaWpfGui.Services.MaaService.AsstGetVersion()
   在 MaaWpfGui.ViewModels.UI.VersionUpdateViewModel..ctor()
   在 lambda_method(Closure , IRegistrationContext )
   在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   在 StyletIoC.Internal.Container.Get[T](String key)
   在 MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   在 Stylet.BootstrapperBase.Start(String[] args)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

此次Windows更新之后出现的问题，重新下载的在文件里的maa可以打开，但是创建的快捷方式不行，尽管文件内的maa可以打开并运行却无法控制模拟器，我已经将maa添加进了Windows的信任名单，常见问题的网页目前404

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13668350/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/88162105/ac156eea-f234-4b6f-a882-801bb9d8354e)

### 还有别的吗？

win10 昨天更新了一下系统

**Comment by ABA2396** [comment]
常见问题点进去看了吗

**Comment by DaemoN-RSDK** [comment]
> 常见问题点进去看了吗

目前这个常见问题的网页是404 状态

**Comment by ABA2396** [comment]
https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html

**Comment by tsctsc6** [comment]
#7579

**Comment by DaemoN-RSDK** [comment]
> https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html

好的，我看看，谢谢

**Comment by ABA2396** [comment]
你说的快捷方式是咋创建的，右键点击然后 `发送到 桌面快捷方式` ？

**Comment by DaemoN-RSDK** [comment]
> 你说的快捷方式是咋创建的，右键点击然后 `发送到 桌面快捷方式` ？

我选择直接拖到桌面了，是我傻逼了，应该选择哪个运行程序右键创建快捷方式的，目前问题已解决
