### ISSUE TITLE
MAA被windows安全中心删除

### ISSUE THREAD

**Issue by the4thDusk** [MaaAssistantArknights/MaaAssistantArknights#7583]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天启动MAA后显示自动更新，更新完之后打开mumu模拟器开始挂机，没一会就发现被windows安全中心删掉了

### 日志文件

12/14 0:52被windows安全中心删除
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13669271/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13669272/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12511947/28e0c6e4-63bf-4d87-98e1-3835187b862f)
图中了解更多的链接： https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FSabsik.FL.A!ml&threatid=2147780199

**Comment by lihaozzx** [comment]
虽然直接信任了就能用，但是想知道 ‘发生什么事了’.mp4

**Comment by status102** [comment]
#6662

**Comment by status102** [comment]
duplicate
