### ISSUE TITLE
MAA把自己删除了

### ISSUE THREAD

**Issue by Superbigyam** [MaaAssistantArknights/MaaAssistantArknights#7585]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在我启动模拟器和MAA之后就玩其他游戏了，结果我回来的时候模拟器停留在基建页面，并且进入文件夹找不到MAA.exe. 

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13669753/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13669754/gui.log)

### 截图

文件夹有敏感内容，无法提供截图

**Comment by zzyyyl** [comment]
See #6662
