### ISSUE TITLE
日服换班BUG&无法正确识别火龙黑角

### ISSUE THREAD

**Issue by 53nemu** [MaaAssistantArknights/MaaAssistantArknights#7586]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

用简单易懂的表示：
换班前：1,2,3,4,5
换班预设：6,7,8,9，火龙黑角
运行初期：6,7,8,9能够正产选中，但是黑角无法识别（有时会重复几次）
运行后期：开始识别火龙黑角，成功识别火龙黑角，然后重复几轮
运行结果：火龙黑角only，其余4空位
（1,2,3,4,5,6,7,8,9分别代表其他干员）

识别火龙黑角的时候，第一轮识别：失败，重复几轮失败后MAA会只寻找火龙黑角
此时是能识别到火龙黑角的，但是成功识别后依旧会重复寻找火龙黑角的任务，重复多次后会出现中枢只换班一个火龙黑角，其余能够识别的干员都不换班的情况（语文比较垃圾）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13670110/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13670128/gui.log)

### 截图

![屏幕截图 2023-12-14 163654](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153263868/6d02e61f-ddc4-4b8b-895f-794a9926e135)

### 还有别的吗？

雷电9，日服

**Comment by ABA2396** [comment]
试试把 `resource/global/YoStarJP/resource/tasks.json` 文件里的 `"レウスSノイルホーン"` 替换成 `"レウス[Sこ]ノイルホーン"` 看看能不能跑

**Comment by 53nemu** [comment]
> 试试把 `resource/global/YoStarJP/resource/tasks.json` 文件里的 `"レウスSノイルホーン"` 替换成 `"レウス[Sこ]ノイルホーン"` 看看能不能跑

其实在没有任何修正的情况下也能成功跑，我本来昨天希望提出的，结果复现的时候没有任何问题一次成功了……
