### ISSUE TITLE
程序闪退

### ISSUE THREAD

**Issue by zhengprince** [MaaAssistantArknights/MaaAssistantArknights#7588]
程序运行过程中，突然闪退，此时并没有link start。之后尝试重开程序，无反应，从任务管理器中并没有找到MAA.exe，看了下是不是杀软（McAfee）误杀，也没有记录。（顺便提一下程序图标也消失了）。再尝试用MAA-v4.27.1-win-x64.zip覆盖，报错说MAA.exe被占用，又看了眼任务管理器依然没有找到MAA.exe。然后重启电脑，再次启动启动程序，就出现了如下错误弹窗。再尝试用MAA-v4.27.1-win-x64.zip覆盖安装目录，错误依旧。再尝试解压到新建目录，运行后错误依旧。

```
> MAA 遇到了问题
> 该字符串未被识别为有效的布尔值。
> 解决方案
> 请参考文档: 常见问题 - 闪退 进行操作。
> 详细信息
> System.FormatException: 该字符串未被识别为有效的布尔值。
>    在 System.Boolean.Parse(String value)
>    在 MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
>    在 lambda_method(Closure , IRegistrationContext )
>    在 StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
>    在 StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
>    在 StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
>    在 StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
>    在 StyletIoC.Internal.Container.Get[T](String key)
>    在 MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
>    在 Stylet.BootstrapperBase.Start(String[] args)
>    在 System.Windows.Application.OnStartup(StartupEventArgs e)
>    在 MaaWpfGui.App.OnStartup(StartupEventArgs e)
>    在 System.Windows.Application.<.ctor>b__1_0(Object unused)
>    在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by gaotako** [comment]
我看到的是MAA被Windows11的Defender给删除了，现在暂时加入白名单

**Comment by Constrat** [comment]
Windows defender problems:
Whitelist maa.exe and everything should work properly.
Check https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662

**Comment by zhengprince** [comment]
Defender并没有启用，因为McAfee已启用。在McAfee中启用白名单后错误依旧。

**Comment by Roentgeni** [comment]
Win11的记录
已检测:Trojan:Win32/Wacatac.B!ml
状态:已隔离
隔离的文件在不会损害设备的受限区域内。系统将自动删除它们。

日期:2023/12/14 13:02
详细信息:这个程序很危险,而且执行来自攻击者的命令。

受影响的项目:

file: C:\*****\Downloads\MAA-v4.28.1-win-x64\MAA.exe

**Comment by Constrat** [comment]
See? It was Windows defender.
McAfee (or any other antivirus) will not disable Windows Defender, it will integrate more functions.
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662

**Comment by Constrat** [comment]
To fix, just whitelist the folder `C:*****\Downloads\MAA-v4.28.1-win-x64`
As said in https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662, .NET8 will probably fix this. Until then this is the only solution.

**Comment by ABA2396** [comment]
> To fix, just whitelist the folder `C:*****\Downloads\MAA-v4.28.1-win-x64` As said in #6662, .NET8 will probably fix this. Until then this is the only solution.

这是升级后配置文件已经修改了，但是又用老版本的ui直接覆盖（或者是被防火墙删了从.old或者其他文件夹里拉了个回来），导致初始化失败。这次更新之后公招的一个参数从bool变成了int，新版本兼容老版本的配置文件，但老版本的用不了新版本的配置文件

**Comment by zhengprince** [comment]
> See? It was Windows defender. McAfee (or any other antivirus) will not disable Windows Defender, it will integrate more functions. Duplicate of #6662

No, it's not my log, my Defender or McAfee didn't report anything.

> > To fix, just whitelist the folder `C:*****\Downloads\MAA-v4.28.1-win-x64` As said in #6662, .NET8 will probably fix this. Until then this is the only solution.
> 
> 这是升级后配置文件已经修改了，但是又用老版本的ui直接覆盖（或者是被防火墙删了从.old或者其他文件夹里拉了个回来），导致初始化失败。这次更新之后公招的一个参数从bool变成了int，新版本兼容老版本的配置文件，但老版本的用不了新版本的配置文件

I think this the real root cause. And it is a bug that the NEW version doesn't adapting the config of OLD version.

**Comment by ABA2396** [comment]
新版本能用旧版本的配置，旧版本不能用新版本的配置
