### ISSUE TITLE
远程控制功能开发者文档仍然链接到错误的网页

### ISSUE THREAD

**Issue by NishikiAsumi0** [MaaAssistantArknights/MaaAssistantArknights#7591]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

描述可参考issue #6817
在4.28.0版本中远程控制协议仍然跳转到https://maa.plus/docs/3.8-%E8%BF%9C%E7%A8%8B%E6%8E%A7%E5%88%B6%E5%8D%8F%E8%AE%AE.html

实际应为https://maa.plus/docs/%E5%8D%8F%E8%AE%AE%E6%96%87%E6%A1%A3/%E8%BF%9C%E7%A8%8B%E6%8E%A7%E5%88%B6%E5%8D%8F%E8%AE%AE.html

### 日志文件

无

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/58659973/952434d7-044f-4578-ae45-488e00f27b31)

**Comment by ABA2396** [comment]
dev已经改了
