### ISSUE TITLE
沒錢時不能退出公招

### ISSUE THREAD

**Issue by CoolCoolWind** [MaaAssistantArknights/MaaAssistantArknights#7593]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如題，我本人在這次開活動時把所有錢升夜刀了，導致龍門幣少於490，令maa不停嘗試公招后必定無法公招，然後卡死

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13672665/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13672668/gui.log)

### 截图

![Screenshot_2023 12 14_19 26 32 869](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/ef6c1c49-f032-47ae-81bf-7cc4404b7936)

**Comment by zzyyyl** [comment]
hard to reproduce XD

**Comment by CoolCoolWind** [comment]
that's mean give up sloving this bug?

**Comment by CoolCoolWind** [comment]
I think add the a detection of the clouor of the money reqiured.When it is red than break and then the problem can stop
like:
if the_capture_of_money == the_capture_of_money_that_is_red:
      than break and print gui
else continue

**Comment by horror-proton** [comment]
可是从日志并没看出 MAA 卡死了, 而是你自己点了停止.
MAA 如果尝试了几次没能成功招募会自动返回任务失败, 应该不会卡死

**Comment by CoolCoolWind** [comment]
我以爲maa 沒想過這種情景，沒做防卡死，故發issue
