### ISSUE TITLE
v4.28.1-alpha版本依旧出现水月肉鸽无法正常烧开水情况

### ISSUE THREAD

**Issue by Auirwind** [MaaAssistantArknights/MaaAssistantArknights#7596]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

v4.28.1-alpha版本依旧出现水月肉鸽无法正常烧开水情况
已看到下午的更新尝试修复肉鸽层级策略
但是试用后在观察下依旧会无法烧水
表现为到3层不退出 会一直往下打
并且失败重开后依旧选择静音难度 不会切换N15检索是否有希望
且在肉鸽探索中MAA本体的CPU占用率总是非常高

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13674841/debug.zip)
时间点 2023/12/14 22:40:00后

### 截图

![QQ截图20231214225612](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56145440/2b1114c7-320d-414f-baa9-bf53052fb9e8)
![QQ截图20231214225347](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56145440/93f37dba-812b-4351-b03b-9a6d3b52b5d4)

### 还有别的吗？

雷电9
本次使用设备 WIN11 I7 9700KF

**Comment by zzyyyl** [comment]
像是roi的问题，可以参照上面的commit先自己改改tasks.json试试
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/23178f4f-b14d-4b62-a101-7f77874d0294)

**Comment by zzyyyl** [comment]
#6053 @Lancarus 不知道当时的 roi 是哪个肉鸽上取的，这样改不知道会不会有问题）

```json
    "Roguelike@LevelName": {
        "algorithm": "OcrDetect",
        "cache": false,
        "text": [],
        "roi": [
            593,
            0,
            186,
            129
        ],
        "next": [
            "Roguelike@NextLevel"
        ]
    },
```

**Comment by zzyyyl** [comment]
嘶，不对，好像是NextLevel会点一下然后StrategyChange就识别不到了（

**Comment by Auirwind** [comment]
> 水月肉鸽好像是在 NextLevel 和 StrategyChange 之间会多一个点击骰子的 DiceConfirm？有点晚了，明天看看

每层进入会roll一次 可能有这个原因 但是不知道为什么重开了也不换难度

**Comment by Auirwind** [comment]
尝试了commit修改tasks.json
会直接导致本体程序资源损坏

**Comment by zzyyyl** [comment]
> > 水月肉鸽好像是在 NextLevel 和 StrategyChange 之间会多一个点击骰子的 DiceConfirm？有点晚了，明天看看
> 
> 每层进入会roll一次 可能有这个原因 但是不知道为什么重开了也不换难度

重开不换难度是因为maa觉得你没过第三层.jpg

**Comment by anyagile** [comment]
v4.28.2的a测版本依旧有同样的问题。水月肉鸽选择尽量往下打就会在第二层关底自动放弃探索，但是选择烧热水会一直打下去，同时烧热水会自动选择最低难度。
log放在压缩包里了。
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13693287/debug.zip)
![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153818344/69369515-b056-408c-8b6e-7b0c97259ef6)
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153818344/6dbb3053-4700-4df2-95e7-45e406618535)

**Comment by zzyyyl** [comment]
还没修呢别急 XD
