### ISSUE TITLE
出现未知错误（有重載過）

### ISSUE THREAD

**Issue by XZKpo666** [MaaAssistantArknights/MaaAssistantArknights#7599]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

MAA 遇到了问题
設定屬性 'System.Windows.ResourceDictionary.DeferrableContent' 時擲回例外狀況。
已經加入項目。字典中的索引鍵: 'TrainingCompleted'  加入的索引鍵: 'TrainingCompleted'
解决方案
出现未知错误
详细信息
System.Windows.Markup.XamlParseException: 設定屬性 'System.Windows.ResourceDictionary.DeferrableContent' 時擲回例外狀況。 ---> System.ArgumentException: 已經加入項目。字典中的索引鍵: 'TrainingCompleted'  加入的索引鍵: 'TrainingCompleted'
   於 System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   於 System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)
   於 System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__299_0(Object target, Object value)
   於 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   於 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   於 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   於 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   於 System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   於 MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverterCore(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   於 MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStreamCore(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   於 System.Windows.ResourceDictionary.set_Source(Uri value)
   於 MaaWpfGui.Helper.LocalizationHelper.Load()
   於 MaaWpfGui.Main.Bootstrapper.OnStart()
   於 Stylet.BootstrapperBase.Start(String[] args)
   於 System.Windows.Application.OnStartup(StartupEventArgs e)
   於 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   於 System.Windows.Application.<.ctor>b__1_0(Object unused)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Log files

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13677126/gui.log)

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/122241156/cb205b3f-a98d-4c0f-97d1-7eda156f87e3)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/122241156/7e45bdb4-b6d3-43dc-8748-c945afd0e2a6)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/122241156/4bbc21e4-7233-4f71-a433-bb8e5aa05292)

**Comment by Constrat** [comment]
Most likely related to
- #7164 @broken-paint

**Comment by status102** [comment]
[e0d5d1b](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/e0d5d1bf1dc8d9dfb939066f2593a3a06957b84d) fixed

**Comment by status102** [comment]
A nightly version has been being built to fix it.

**Comment by ABA2396** [comment]
v4.28.2 fixed，可以先把 \config\gui.json 中的 "GUI.Localization" 的值改为 "zh-cn" 升级后换回来
