### ISSUE TITLE
自动作业不会开技能了

### ISSUE THREAD

**Issue by HMZyueshen** [MaaAssistantArknights/MaaAssistantArknights#760]
干员技能设置成自动开技能，maa会开，但是战斗流程里设置开技能maa不开了
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8840854/asst.log)

**Comment by ABA2396** [comment]
看下作业是咋样的

**Comment by HMZyueshen** [comment]
[tough_10-01_德克萨斯+风笛+令+能天使.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8841334/tough_10-01_.%2B.%2B.%2B.zip)
[tough_10-03_令+山+桃金娘+风笛.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8841335/tough_10-03_.%2B.%2B.%2B.zip)
