### ISSUE TITLE
生息演算多久会在台服开放呢？

### ISSUE THREAD

**Issue by bwkdbewkhbiwk** [MaaAssistantArknights/MaaAssistantArknights#7604]
### 说说你遇到的问题？

我现在是用的4.28.0，但是我没有看到生息演算选项，是还没开放吗？我看到有些人的界面有这个选项
<img width="251" alt="Screenshot 2023-12-15 at 12 19 43" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153872940/138e9b26-468e-4211-b7e0-354fbbb5b15c">

**Comment by bighead945** [comment]
應該是已經開放了，昨日我就有使用過生息演算這個功能，不過今日早上的新版本有問題，所以目前還不知道。

**Comment by Constrat** [comment]
Just update it to the latest main release `v.4.28.2` and make sure to select `txwy` client then RESTART. 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/a62526e0-d9f6-483a-937a-ff8b2a4f0e3c)
