### ISSUE TITLE
v3.9.4-beta.1 LinkStart 后模拟器内没反应

### ISSUE THREAD

**Issue by qianxu2001** [MaaAssistantArknights/MaaAssistantArknights#761]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8841090/asst.log)
蓝叠模拟器国际版 Hyper-V，如图：
![image](https://user-images.githubusercontent.com/62287903/172076891-aedad842-d769-48b4-8810-964eab5e4f28.png)

**Comment by soundofautumn** [comment]
一样的问题，系统win11
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8841111/asst.log)

**Comment by zhongfly** [comment]
同样问题，夜神国际版 安卓9
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8841324/asst.log)

**Comment by yijin840** [comment]
一样的问题，夜神模拟器7.0.2.8，win11
