### ISSUE TITLE
公招优先选择含new的最高星tag

### ISSUE THREAD

**Issue by overloadwolf** [MaaAssistantArknights/MaaAssistantArknights#7611]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

公招识别中可以识别出new干员，选择词条的时候并不会优先选择含new的高星词条
![识别](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/37205846/365a33bb-fc8a-4d43-9962-5afba70fedc3)
![结果](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/37205846/e8f8b0c4-dfbe-4005-b337-72ae9ab3e253)

### 有什么好的想法？

在最高星级词条组合中优先选择含未拥有干员的词条进行招募（尽管五星概率很低）

**Comment by ABA2396** [comment]
缓存是ui做的，core不知道你有什么干员。而且是存的之前`干员识别`的数据，如果没重新识别过也是不准确的
