### ISSUE TITLE
MAA啟動失敗

### ISSUE THREAD

**Issue by fs910175** [MaaAssistantArknights/MaaAssistantArknights#7614]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

啟動時顯示如下的訊息：
已重抓檔案，依然出現

MAA 遇到了问题
設定屬性 'System.Windows.ResourceDictionary.DeferrableContent' 時擲回例外狀況。
已經加入項目。字典中的索引鍵: 'TrainingCompleted'  加入的索引鍵: 'TrainingCompleted'
解决方案
出现未知错误
详细信息
System.Windows.Markup.XamlParseException: 設定屬性 'System.Windows.ResourceDictionary.DeferrableContent' 時擲回例外狀況。 ---> System.ArgumentException: 已經加入項目。字典中的索引鍵: 'TrainingCompleted'  加入的索引鍵: 'TrainingCompleted'
   於 System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   於 System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)
   於 System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__299_0(Object target, Object value)
   於 MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   於 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   於 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   於 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   於 System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   於 MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverterCore(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   於 MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStreamCore(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   於 System.Windows.ResourceDictionary.set_Source(Uri value)
   於 MaaWpfGui.Helper.LocalizationHelper.Load()
   於 MaaWpfGui.Main.Bootstrapper.OnStart()
   於 Stylet.BootstrapperBase.Start(String[] args)
   於 System.Windows.Application.OnStartup(StartupEventArgs e)
   於 MaaWpfGui.App.OnStartup(StartupEventArgs e)
   於 System.Windows.Application.<.ctor>b__1_0(Object unused)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13679984/gui.log)

### 截图

![2023-12-15 09 48 51](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66399943/f579f302-9ac8-4b68-82b9-1a9fb40df491)

### 还有别的吗？

Windows 11

**Comment by status102** [comment]
Duplicate of #7599

**Comment by ABA2396** [comment]
v4.28.2 fixed，可以先把 \config\gui.json 中的 "GUI.Localization" 的值改为 "zh-cn" 升级后换回来

**Comment by fs910175** [comment]
> v4.28.2 fixed，可以先把 \config\gui.json 中的 "GUI.Localization" 的值改为 "zh-cn" 升级后换回来

試了一下改了也無效，我等一下.2的編譯版再重新抓好了，thx
