### ISSUE TITLE
基建换班-未能自动领取专精

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#7615]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

12/15 0951开始执行自定义基建，未能领取专精

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13680041/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13680042/gui.log)

### 截图

![Screenshot_20231215-100004](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/29b0dea1-4a66-4b0b-b923-6e9082ee1e52)

**Comment by ABA2396** [comment]
不开自定义的能收吗

**Comment by status102** [comment]
> 不开自定义的能收吗

默认的没跑完，但是一开始没收，进换班流程了（我觉得也不行

**Comment by ABA2396** [comment]
bool continue_training = params.get("continueTraining", false);是不是写错了，应该是bool continue_training = params.get("continue_training ", false);吧？我看传过来的是["continue_training"] = continueTraining,

**Comment by status102** [comment]
> bool continue_training = params.get("continueTraining", false);是不是写错了，应该是bool continue_training = params.get("continue_training ", false);吧？我看传过来的是["continue_training"] = continueTraining,

我看看修完能不能跑，不继续专精所以不领取有点怪了
