### ISSUE TITLE
MAA.exe会莫名其妙消失

### ISSUE THREAD

**Issue by GeWuYou** [MaaAssistantArknights/MaaAssistantArknights#7616]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

启动了Maa开始执行任务，在执行过程中有概率会卡死自动退出，然后打开Maa的程序路径发现MAA.exe莫名其妙不见了，第一次出现这种问题的时候是更新到4.28.0的时候，更新完毕后发现路径下没有MAA.exe，后面我又重新下了一个直接解压覆盖了，但依旧会有概率出现这种情况

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13680329/debug.zip)

**Comment by ABA2396** [comment]
#6662

**Comment by zhengprince** [comment]
跟我昨天遇到 #7588 的一样，如果杀软没有任何报告的话就不是 #6662 的问题
我觉得这个回答更可信https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/7588#issuecomment-1857150653

**Comment by GeWuYou** [comment]
我使用的是卡巴斯基免费版作为杀毒软件，我查看了它的报告，但并没有报出MAA.exe存在病毒

**Comment by ABA2396** [comment]
> 跟我昨天遇到 #7588 的一样，如果杀软没有任何报告的话就不是 #6662 的问题 我觉得这个回答更可信[#7588 (comment)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/7588#issuecomment-1857150653) ，如果这是事实，那就是个新版本没有适配老版本配置的bug

这个问题是繁中服的翻译键名冲突，最多是打不开，不会导致exe消失
