### ISSUE TITLE
win11 defender（安全中心）显示MAA带病毒“Trojan:Win32/Wacata.B!ml”

### ISSUE THREAD

**Issue by freeeeesd** [MaaAssistantArknights/MaaAssistantArknights#7618]
### 说说你遇到的问题？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102841290/628c13f6-e0af-4e53-86fd-6d0d5db1b767)
请问这是否正常？

**Comment by helloworld1631** [comment]
我也遇到了，Win11 defender 直接把MAA.exe 给删除了。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44239564/3e8d7e80-ce45-4352-b01c-a877a09b9a01)

**Comment by ABA2396** [comment]
#6662

**Comment by freeeeesd** [comment]
放进白名单一段时间后也给我删了。。。已经重新安装3次了
