### ISSUE TITLE
MeoAsstGui已停止工作

### ISSUE THREAD

**Issue by jumpinggalaxy** [MaaAssistantArknights/MaaAssistantArknights#762]
蓝叠模拟器，使用管理员身份运行后停止工作，已安装运行库，指令集支持AVX
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8841236/asst.log)
![2265ced520616636f78f016ea796cd7](https://user-images.githubusercontent.com/106938196/172079896-a34c8501-44b4-4331-ba0f-b4ea10f09525.png)
![39aade6b98d6f1bc236956b4bb1df5c](https://user-images.githubusercontent.com/106938196/172079903-56249074-2664-4f1c-b657-1827a80a5fc4.png)

**Comment by MistEO** [comment]
之前有使用过么，像是以下原因之一

- 下载的包不完整，重新下载解压一次试试
- 没有文件夹下的读写权限，换个目录试试
- 配置文件损坏，把 `gui.json` 删了试试
- 检查更新崩溃，不知道咋整，先把网断了试试（）
