### ISSUE TITLE
Windows security 报告 存在病毒

### ISSUE THREAD

**Issue by PODF-x** [MaaAssistantArknights/MaaAssistantArknights#7621]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

从4.28.0自动升级到4.28.2的时候报告的病毒，4.28.0及之前的版本均未出现此问题。重新下载也提示一样的内容。报告的病毒类型为：Trojan:Win32/Sabsik.FL.A!ml

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13681860/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13681861/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/69449056/ef754b84-ec46-46b0-9374-fa30a552e4f1)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/69449056/fbb7b15e-90b7-49b5-82dc-a8b398b00616)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/69449056/7444b01d-09e0-468e-82f7-b2bb7b979907)

### 还有别的吗？

另（Windows前天更新了后就有点抽风报病毒，但是和MAA.exe报告的内容并不相同，尚不清楚是否存在关联）

**Comment by zzyyyl** [comment]
#6662
