### ISSUE TITLE
傀影肉鸽进入第三层时卡死

### ISSUE THREAD

**Issue by Hanmu233** [MaaAssistantArknights/MaaAssistantArknights#7623]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

傀影进入第四层双不期而遇时卡死显示紧急作战

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13682212/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13682218/asst.zip)

### 截图

![6ddc4951824296b338fc5300d1e7cbe](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137816415/9fa35bf8-7cbb-4e0d-89f3-2c37fc7721b1)
![5ee8748107583c7816c01445b220293](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137816415/8a209b40-b287-466a-aa37-2d3bf412a7fb)

### 还有别的吗？

mumu12最新版本，win11

**Comment by Hanmu233** [comment]
更正，这是第四层，但在第三层也遇到过相同bug，另外还出现过关卡结束游戏卡死的bug，未知原因，正在尝试复现

**Comment by zzyyyl** [comment]
没看你的日志，我觉得大概是识别到了右边的灰色节点

**Comment by Hanmu233** [comment]
> 没看你的日志，我觉得大概是识别到了右边的灰色节点

前面没这问题，是更版本的时候动到屎山了吗

**Comment by zzyyyl** [comment]
前面可能也有这问题，只不过打傀影的人少（确信

**Comment by Hanmu233** [comment]
> 前面可能也有这问题，只不过打傀影的人少（确信

刚看下面楼还有一个同问题的XD
有点怪，我昨天前天都没什么问题

**Comment by zzyyyl** [comment]
应该是之前修的 StrategyChange 生效了，导致作战的优先级在不期而遇之前了
