### ISSUE TITLE
【投票】训练室艾丽妮解决方案

### ISSUE THREAD

**Issue by 1235789gzy1** [MaaAssistantArknights/MaaAssistantArknights#763]
### [点击参与投票](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/763#issuecomment-1214322924)
艾丽妮的训练技能可以使下次专精时间缩短一半，但是训练室任意一方离开就触发不了这个效果，所以我希望能在识别到基建协助者为艾丽妮的时候不进驻宿舍
如果顺带做个自动专精就好了

**Comment by zzyyyl** [comment]
麻了，名字打错搜不到这个 issue ......

**Comment by zzyyyl** [comment]
这个问题好多 issue 提了，建议早日提上日程（

**Comment by MistEO** [comment]
这个问题似乎同样可以通过识别 `未进驻` 来解决

**Comment by zzyyyl** [comment]
> 这个问题似乎同样可以通过识别 `未进驻` 来解决

不行吧，其他干员进驻训练室的时候完全可以进宿舍啊（

**Comment by MistEO** [comment]
我的艾妮莉现在就在训练室（

![image](https://user-images.githubusercontent.com/18511905/184362092-5e4c6a56-3a82-46d5-b714-1d65955a49d2.png)
![image](https://user-images.githubusercontent.com/18511905/184362189-35f758a5-cfef-41a0-9749-e9fac1e01ae5.png)

**Comment by zzyyyl** [comment]
说一下之前和玛丽讨论过的解决方案：
新增一个自选是否换人的设施 “训练室”（跟控制中枢、贸易站、制造站等并列），然后识别未进驻来保证不更换训练室时人员不会被撤到宿舍。

这个解决方案如何，投个票呗（？

**Comment by MistEO** [comment]
好消息：联合国以122票赞成、1票反对、1票弃权通过了在全球范围内禁止核武器的公约。

坏消息：美中俄英法均未参加该公约谈判。

**Comment by MistEO** [comment]
这个通过未进驻标签来过滤之后，是不是相当于 fix 了

**Comment by zzyyyl** [comment]
> 这个通过未进驻标签来过滤之后，是不是相当于 fix 了

现在所有的训练室干员都不会被主动换下，确实解决了问题。
不过没有达成最初的解决方案，因为还不能主动选择是否更换训练室干员
等到有人提 issue 的时候再说吧，现在问题就当解决了（
