### ISSUE TITLE
傀影肉鸽关卡识别异常

### ISSUE THREAD

**Issue by smt66667720** [MaaAssistantArknights/MaaAssistantArknights#7635]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

傀影肉鸽关卡识别异常，控制台一直在刷屏，模拟器界面也无操作

### 日志文件

[Uploading Desktop.zip…]()

### 截图

![8U05ZFWV1Y JVJ} HH()NCR](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153900198/d64fe64c-115b-4c41-bf33-42770c142de7)

### 还有别的吗？

雷电模拟器

**Comment by Constrat** [comment]
fixed with ff3a8f4
