### ISSUE TITLE
檔案包含病毒或潛在的垃圾軟體

### ISSUE THREAD

**Issue by Berry85** [MaaAssistantArknights/MaaAssistantArknights#7636]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA 遇到了问题
因為檔案包含病毒或潛在的垃圾軟體，所以作業未順利完成。
解决方案
出现未知错误
详细信息
System.ComponentModel.Win32Exception (0x80004005): 因為檔案包含病毒或潛在的垃圾軟體，所以作業未順利完成。
   於 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   於 MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndUpdateNow()
   於 MaaWpfGui.ViewModels.UI.RootViewModel.OnViewLoaded()
   於 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   於 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   於 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   於 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   於 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   於 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   於 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   於 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   於 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   於 System.Windows.Interop.HwndTarget.OnResize()
   於 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   於 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13687151/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13687152/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/51792299/831fed65-f9ca-4db9-a530-7c59f945d808)

### 还有别的吗？

系統 win11
在更新4.28.2的時候報錯
這個報錯好像越來越頻繁了, 有時候不會, 有的時候重新下載可以

**Comment by ABA2396** [comment]
#6662
