### ISSUE TITLE
更新后maa被识别成病毒，并别微软系统自动删除

### ISSUE THREAD

**Issue by Qiaozhu1** [MaaAssistantArknights/MaaAssistantArknights#7637]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

更新最新版本的maa后微软系统将其直接识别为病毒删除

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13687640/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13687641/gui.log)
[2023-12-16 00:38:58.219]

### 截图

![屏幕截图 2023-12-16 004655](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153789303/5b35c9b0-6648-4b71-a5e5-2fc68df24a0b)

### 还有别的吗？

mumu模拟器（不过我觉得这跟模拟器没关系。。。）
win10和win11我都试过，都有这个问题，更低的没试过

**Comment by ABA2396** [comment]
#6662

**Comment by zhanghongshen** [comment]
我也是，被判定为特洛伊木马了
