### ISSUE TITLE
蓝叠模拟器用多个maa多开时adb无法连接上正确的模拟器

### ISSUE THREAD

**Issue by kayair1019** [MaaAssistantArknights/MaaAssistantArknights#7638]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

问题同 #6103 
按照使用说明中 #通过使用模拟器或应用的快捷方式来进行多开操作 的步骤设置了Amaa和Bmaa，以及A模拟器和模拟器B。
运行的时候Amaa能正常启动并且adb连接上模拟器A。此时我在Amaa运行的同时，打开Bmaa，打开Bmaa时启动的是模拟器B，但adb连接上的却是模拟器A。此时Amaa正在A模拟器上进行基建排班，Bmaa连接上A模拟器后退出基建，进入公招界面。

Amaa 的模拟器路径：C:\ProgramData\Microsoft\Windows\Start Menu\Programs\BlueStacks 5.lnk
Bmaa 的模拟器路径：C:\ProgramData\Microsoft\Windows\Start Menu\Programs\BlueStacks App 芜湖.lnk

### 日志文件

Amaa：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13687741/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13687742/gui.log)

Bmaa：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13687724/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13687725/gui.log)

问题出现的时间点是在[2023-12-15 23:25:08.738] 附近。

### 还有别的吗？

蓝叠国际版 操作系统win10.

设置参考资料：https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.html#%E9%80%9A%E8%BF%87%E4%BD%BF%E7%94%A8%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%88%96%E5%BA%94%E7%94%A8%E7%9A%84%E5%BF%AB%E6%8D%B7%E6%96%B9%E5%BC%8F%E6%9D%A5%E8%BF%9B%E8%A1%8C%E5%A4%9A%E5%BC%80%E6%93%8D%E4%BD%9C

**Comment by ABA2396** [comment]
手动设置一下b的adb端口，和模拟器路径没关系

**Comment by kayair1019** [comment]
> 手动设置一下b的adb端口，和模拟器路径没关系

请问你指的是修改连接设置下的     ADB路径（相对/绝对）  这里的配置吗？我的maa勾选了 “自动检测连接” 这个选项，无法手动设置adb端口。

**Comment by ABA2396** [comment]
你是hyperv的蓝叠？如果不是的话就把自动检测关了，如果是的话就把maa本体复制一份，然后在gui.json里指定一下模拟器实例，文档里有说方法

**Comment by kayair1019** [comment]
> 你是hyperv的蓝叠？如果不是的话就把自动检测关了，如果是的话就把maa本体复制一份，然后在gui.json里指定一下模拟器实例，文档里有说方法

我使用的是hyperv的蓝叠。
我按照文档里的方法做了，指定了模拟器实例，还是连接不上，但报错信息有变化。当我开了两个模拟器时报错信息变成了检测到多个模拟器，当我只开了一个模拟器的时候显示连接失败。我试了一下把其中一个模拟器换成Nougat64 核心，但问题还是存在。

指定的模拟器实例在文件的134行
模拟器A：
[gui.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13693662/gui.json)
模拟器B：
[gui.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13693667/gui.json)


![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97491069/25ce4449-6102-4b48-b89b-2b4ce3df1abb)

**Comment by SherkeyXD** [comment]
https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%AF%8F%E6%AC%A1%E5%90%AF%E5%8A%A8%E7%AB%AF%E5%8F%A3%E5%8F%B7%E9%83%BD%E4%B8%8D%E4%B8%80%E6%A0%B7-hyper-v

在多开 Hyper-V 蓝叠模拟器与 maa 时，对每一个 maa，你都需要设置其对应的核心名称，这样 maa 才能自动匹配端口

**Comment by SherkeyXD** [comment]
日志显示你的 B maa 并没有检测到正确的端口号

你确定你的核心设置正确了吗？我看到你 gui.json 里面写的是 `Pie64` `Pie64_2`，但实际启动的核心是 `Pie64` `Pie64_1`

**Comment by kayair1019** [comment]
> 日志显示你的 B maa 并没有检测到正确的端口号
> 
> 你确定你的核心设置正确了吗？我看到你 gui.json 里面写的是 `Pie64` `Pie64_2`，但实际启动的核心是 `Pie64` `Pie64_1`

感谢帮助，改了之后可以双开了！
