### ISSUE TITLE
MAA触发windows defender杀毒？

### ISSUE THREAD

**Issue by LDYang694** [MaaAssistantArknights/MaaAssistantArknights#7639]
### 说说你遇到的问题？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62846124/810b7095-0a64-4580-8005-cbfe0c3e20ef)
MAA运行期间触发windows defender杀毒，导致无法使用？

**Comment by Constrat** [comment]
#6662 is pinged.
Duplicate.
