### ISSUE TITLE
maa毫无预兆的崩溃,并且软件本身出现问题

### ISSUE THREAD

**Issue by G0hiking** [MaaAssistantArknights/MaaAssistantArknights#7640]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在4.28.2版本更新后,maa正常运行时突然崩溃,并且maa.exe消失,多次重装后依然存在问题

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13688988/gui.log)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13688986/asst.log)

### 还有别的吗？

我多开了两个雷电模拟器,并且其中一个使用了alas,不过二者从未混用

**Comment by G0hiking** [comment]
win11,版本号22000.1335
雷电模拟器版本:9.0.62(9)

**Comment by ZephyrGeo** [comment]
windows defender自动拦截删除了这个文件
![QQ截图20231216043100](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/33949957/cee947e1-b0ad-4506-a0f8-4f888969d372)
