### ISSUE TITLE
自动作战添加下一条作业按钮

### ISSUE THREAD

**Issue by MercuryBP** [MaaAssistantArknights/MaaAssistantArknights#7643]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在使用自动作战的战斗列表功能时，对于同一个ss的作业，需要反复复制或者更改作业号

### 有什么好的想法？

希望可以添加一个下一条作业的按钮，因为同一个ss的作业多半是连号的，这样可以简化使用

**Comment by SherkeyXD** [comment]
你可以用战斗列表功能

此外作业也不一定是连号的吧？倒是可以考虑给作业站那边做一个作业组的功能

**Comment by MercuryBP** [comment]
> 你可以用战斗列表功能
> 
> 此外作业也不一定是连号的吧？倒是可以考虑给作业站那边做一个作业组的功能

作业组功能确实合理一点感觉，期待上线！

**Comment by MobiusT** [comment]
输入作业组，一键导入进作战列表！

**Comment by status102** [comment]
不同作业用的干员不一定相同，作业组可能（

**Comment by ABA2396** [comment]
> 不同作业用的干员不一定相同，作业组可能（

整个全部的干员，没有的就一个个抄吧）

**Comment by MobiusT** [comment]
我的想法是这样，
作业站中新增设置：加入作业集
1、可选择本人已有作业集或新增作业集，新增作业集后可获得一个短链 如maa://groupxxxx
2、考虑到部分关卡普通突袭适用同一个作业，最好在加入作业集中有突袭相关设置，类似战斗列表的左右键添加，由作者决定是否将单个作业以先普通后突袭的方式加入作业集，还是只有普通or突袭
3、作业站提供接口解析作业集短链，当maa调用接口时，解析1中的地址并将所有集内作业返回
4、maa自动战斗链接处输入作业集链接，maa调用作业站接口获取作业集列表后逐个加入战斗列表，并根据2中的设置，根据设置自动创建成先普通后突袭，或单个关卡
5、后续操作同现有流程

**Comment by MercuryBP** [comment]
> 不同作业用的干员不一定相同，作业组可能（

不是有自动编队嘛，这个功能只需要批量导入作业就可以了，剩下的感觉都可以以现有的功能实现

**Comment by MobiusT** [comment]
> 
> 得核对有没有作业所需的干员、练度、模组

我认为这个核对不应该由maa完成，现有的自动战斗有校验逻辑吗

如果要加，我觉得可以在作业站上展示作业集需要的干员（去重） 由玩家在选择作业组的时候自行判断是否使用这个作业组

**Comment by status102** [comment]
可能遇到的问题
1. 比如一个活动16个关卡，其中有两个关卡用到了A干员 / 支持突袭但拿不到章，如何快速找出是哪个关卡的作业并替换
2. 关卡顺序有强制要求，替换掉两个关卡的作业后要把作业放进去操作上可能存在问题
3. 战斗列表导入过程有`检查关卡名是否正确`这一步骤，如果是本地导入，还可以修改文件名来跳过内置检测；如果是在线作业，如果内置检测判断错关卡名可能就无法修改了

**Comment by MercuryBP** [comment]
> 可能遇到的问题
> 
> 1. 比如一个活动16个关卡，其中有两个关卡用到了A干员 / 支持突袭但拿不到章，如何快速找出是哪个关卡的作业并替换
> 2. 关卡顺序有强制要求，替换掉两个关卡的作业后要把作业放进去操作上可能存在问题
> 3. 战斗列表导入过程有`检查关卡名是否正确`这一步骤，如果是本地导入，还可以修改文件名来跳过内置检测；如果是在线作业，如果内置检测判断错关卡名可能就无法修改了

这几个问题感觉只需要每个人都能定制自己的作业组就可以解决了？毕竟作业组是在作业站上的功能，只需要在作业站上整合出适合自己的作业组之后，导入maa即可。如果有替换作业的需求可以复制别人的作业组然后自己在作业站里进行更改

**Comment by SherkeyXD** [comment]
> 这几个问题感觉只需要每个人都能定制自己的作业组就可以解决了？毕竟作业组是在作业站上的功能，只需要在作业站上整合出适合自己的作业组之后，导入maa即可。如果有替换作业的需求可以复制别人的作业组然后自己在作业站里进行更改

定制自己的作业组就是目前的战斗列表功能啊

**Comment by status102** [comment]
感觉有些伪需求了，考虑批量导入在线作业
使用范围：几乎全干员的懒人，直接用别人给的复制粘贴（但是容易出现翻车

**Comment by MobiusT** [comment]
我认为这个对于用户的体验变化是这样的

现有操作
1、作业站找单个关卡作业，复制链接
2、maa黏贴链接，加入战斗列表，有突袭则再右键加入作战列表
3、重复1~2步直至所有关卡加入列表（一般8次或更多）
4、启动maa挂机


新功能操作
1、作业站找关卡作业组，复制链接
2、maa黏贴链接，加入作战列表，该作业组所有关卡包括突袭进入作战列表
3、启动maa挂机

关于检查干员，应该放作业站页面上检查，只不过原来是检查单个关卡作业，现在修改成检查所有作业组里的全部关卡，又或者全干员不需检查

关于修改作业组，如果作业组某一关自己抄不了，但是其他关卡都能抄，可以一键加入作业组后单独在战斗列表取消勾选或叉掉不适用的作业，再单独找合适的作业使用现有的单作业加入列表的方式加入，并手动拖动顺序即可自行修改。如果大部分关卡都需要修改的话应该更换合适的作业组或者全部单关卡加入列表

关于翻车，现有战斗列表也会翻车，maa检查通关失败后会取消勾选当前作业并停止，这部分我认为不在本需求涉及修改的范围内，无需处理

就我个人评估，这个改动的重点其实在作业站上如何加入作业组功能并方便的查找、检查干员等，而maa部分只需兼容作业组链接并循环执行现有的添加关卡到作业列表功能就行了（没有看不起大佬们工作量的意思
