### ISSUE TITLE
MAA繁中服 生息演算錯誤

### ISSUE THREAD

**Issue by MiTSeal** [MaaAssistantArknights/MaaAssistantArknights#7645]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

MAA生息演算啟動與掛機中途沒問題，但第五天敵人攻家時不會退出演算便開始下一輪掛機，導致卡在第五天輪迴

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13691211/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13691213/asst.log)

2023/12/16 

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150085813/efdf4b07-ec9d-4e25-aca1-a542ba237b1e

**Comment by momomochi987** [comment]
@MiTSeal 

把 `resource\global\txwy\resource\tasks.json` 裡的 `Reclamation@GiveupAlgorithm` 換成下面這個

```
  "Reclamation@GiveupAlgorithm": {
    "text": [
      "放",
      "棄",
      "赦",
      "癒"
    ]
  }

```
然後再試試看?

**Comment by MiTSeal** [comment]
成功修復了 非常感謝
