### ISSUE TITLE
MAA是否错误的泄露了一个asst.log句柄给adb?

### ISSUE THREAD

**Issue by yyjdelete** [MaaAssistantArknights/MaaAssistantArknights#7649]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

测试版本: `v4.28.2`

现在在win上, 如果运行一次Link Start(开和关ADB Lite/退出时释放ADB的模式都测试过), 退出MAA后手动删除debug/asst.log时会提示被adb占用(该进程命令行 为`adb -L tcp:5037 fork-server server --reply-fd 640`)，但adb实际上没有在此文件中写入任何数据

这个也影响到了MAA正常的日志滚动功能，以至于我的日志常年有几百M到一个G, 只要不重启电脑就会一直增加， 我一直还以为MAA不会滚动日志...

能否限制下让asst.log句柄不被adb继承?

### 日志文件

与此无关

### 截图

![9535b5da4b1dc2496ecfd229f1f31240](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/1819074/8d9ed089-89e1-4efd-9d01-c6da3cd62c6a)

### 还有别的吗？

看能不能参考下
白名单(>=Vista)：https://devblogs.microsoft.com/oldnewthing/20111216-00/?p=8873
黑名单(在最初创建ofstream的时候，就利用一个非公开的构造函数，构造一个已经设置好关闭继承的File传进去)：
https://stackoverflow.com/questions/55513974/controlling-inheritability-of-file-handles-created-by-c-stdfstream-in-window (fopen=>_fsopen?)
https://stackoverflow.com/questions/475853/can-i-use-createfile-but-force-the-handle-into-a-stdofstream

**Comment by horror-proton** [comment]
很大概率是这样的, 实际上这个问题之前修改过, 但是不知道为啥被 revert 了 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/3029e6d9b9466ec89c825190bc572cba5723666e

我手头没有 Windows 设备, 不清楚具体情况是什么 :thinking:
