### ISSUE TITLE
ALAS添加MAA介面異常

### ISSUE THREAD

**Issue by ForgetMeNot9649** [MaaAssistantArknights/MaaAssistantArknights#7650]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在ALAS中新增template-maa 配置文件模板後，介面顯示錯誤

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13691734/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13691735/gui.log)

### 截图

![2023-12-16 153821](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153910040/d67aad01-5797-4d1a-ac7d-3d017196957e)

**Comment by ABA2396** [comment]
tw的4281有问题，语言设置成简中或者用4282
