### ISSUE TITLE
傀影肉鸽关卡中出现两个不期而遇关卡识别不了

### ISSUE THREAD

**Issue by asywygg** [MaaAssistantArknights/MaaAssistantArknights#7651]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

![IMG_20231216_170319](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153983826/e6085235-cf5d-4571-b0ae-0763a48fb036)
![IMG_20231216_162101](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153983826/36b05904-ce35-49cd-90be-86d388e0f892)
同一层第一关两个节点都是不期而遇时识别不出来一直卡在这里如果不手动点一下就会一直卡在这个界面

### 日志文件

![IMG_20231216_162101](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153983826/9f3d14b3-c6fc-4b93-822a-f088435aabf3)
![IMG_20231216_170319](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153983826/3b2bfb7f-69d9-4c2b-9208-5c8152cb6bf0)
23年12月16日更新完银心湖列车后出现

### 还有别的吗？

雷电模拟器
win11
i7加4060笔记本

**Comment by ABA2396** [comment]
修了等发版

**Comment by yuanzzzi** [comment]
我也遇到这种情况了，请问修改了吗
