### ISSUE TITLE
在水月肉鸽选择尽可能刷等级的过程中一直都是2层15步就放弃探索

### ISSUE THREAD

**Issue by fzj-official** [MaaAssistantArknights/MaaAssistantArknights#7652]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在水月肉鸽选择尽可能刷等级的过程中一直都是2层15步就放弃探索

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13692022/debug.zip)
12月16日

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144503397/0d8e7f2d-366f-4f10-b1ff-faf4c8c6ddcf)

**Comment by fzj-official** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144503397/d2680c18-6ed6-4db2-95f2-ebdc47e76d5c)
很明显，当我选了烧热水之后，肉鸽通关了

**Comment by fzj-official** [comment]
但选烧热水会自动选最低难度

**Comment by anyagile** [comment]
水月肉鸽和你遇到一模一样的问题。补充一下，在v4.27.1的正式版里是可以正常进入第二层关底关卡并继续往下探索的，但是似乎从v4.28.0的测试版开始就会出现卡在第二层关底，不点击关卡，大约20秒左右自动放弃探索。目前使用的v4.28.2正式版依旧存在这个问题。
另外，在水月肉鸽中为什么在希望充足的情况下，maa在重装和另一个招募券之间选择了重装招募券，但是却没有选择任何重装就放弃了招募。（现有阵容只有斑点，可以招募塞雷娅和其他很多高星重装的情况下放弃了招募）
下面是截图和log压缩文件。
![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153818344/b9b589ea-04ab-47e3-8bfa-fc6751f5e637)
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153818344/cd4848a1-59b4-4465-b7d8-bd546af9dbab)
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13693273/debug.zip)

**Comment by zzyyyl** [comment]
发一下 debug/roguelike 文件夹的相关截图

**Comment by fzj-official** [comment]
![2023-12-16_17-10-55-212_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144503397/14dbe32c-ed0a-4fe9-a119-e98e8d119a8f)
![2023-12-16_17-10-59-770_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144503397/a91a834a-de27-4442-ae74-c8bb1e176105)

**Comment by fzj-official** [comment]
![2023-12-16_17-10-59-770_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144503397/fdc33b6a-7f4a-448e-a766-abe3131b6b0d)
![2023-12-16_17-10-55-212_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144503397/2f4654a4-c1bb-4894-a385-3f8c906c5866)
时间12-16 17.10
