### ISSUE TITLE
肉鸽识别错误

### ISSUE THREAD

**Issue by kmmumukl** [MaaAssistantArknights/MaaAssistantArknights#7655]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在肉鸽挂机时，进入第二层后将不期而遇识别为紧急作战，然后就卡住了，直到我看到手动停止。

### 日志文件

12月16号14点46分

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13692585/debug.zip)

### 截图

![Screenshot_20231216-103542](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142652226/adbc6aa6-0499-425c-bb46-ec1dc96052ab)
![屏幕截图 2023-12-16 194722](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142652226/b495b129-ffda-4099-aa42-5c7fab95a31d)

### 还有别的吗？

模拟器：
雷电模拟器9.0.63
电脑系统及配置：
处理器	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
机带 RAM	16.0 GB (15.4 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2023/‎8/‎19
操作系统版本	22621.2715
华硕天选2

**Comment by ABA2396** [comment]
修了等发版
