### ISSUE TITLE
maa会自动删除MAA.exe

### ISSUE THREAD

**Issue by Endymion2288** [MaaAssistantArknights/MaaAssistantArknights#7656]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在运行过程中，选取退出maa和模拟器后，会在文件夹里将maa.exe自动删除。eset日志没有发现有删除文件的行为。
![1702737070388](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131605660/f55a8243-a168-4b18-8b26-fb2f7a88a987)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13692858/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13692859/asst.log)
12月16日

### 截图

![1702737070388](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131605660/420a0138-5f68-46bb-bbd4-a8ef625f4352)
删除后文件夹截图如图

### 还有别的吗？

蓝叠模拟器（国外版）
win11 x86

**Comment by ABA2396** [comment]
#6662

**Comment by Endymion2288** [comment]
我似乎没有在windows defender的日志里找到删掉的记录，所以也没法解决。我刚刚重新下载了压缩包并使用了一次，出现了重复的问题。应该如何调试杀毒软件？

**Comment by dd8378** [comment]
我这边也多次出现同样问题，使用的是卡巴斯基，也没有在wd或者卡巴斯基找到删除的记录

**Comment by ABA2396** [comment]
不懂，但软件再怎么崩溃也不会导致exe消失啊，只能是被什么东西删掉了

**Comment by cjyfs** [comment]
我的maa也会在开机之后消失不见，我还以为是我之前的误操作导致的

**Comment by dherorunner** [comment]
我的maa也一样，用的火绒，没有找到任何的删除或者隔离记录，但是exe文件就是直接消失了

**Comment by GiantBamboo** [comment]
我的也是同样的问题，从4.28.1开始就会自动删除maa.exe，而且我桌面的快捷方式也一起删除了。

**Comment by burnningwings** [comment]
同样。模拟器-MUMU模拟器12. 版本-4.28.2

**Comment by ningolus** [comment]
版本4.28.2遇到同样问题，Windows defender会显示原因为Torjan：Win32/Wacatac.B!ml

**Comment by Animer3000** [comment]
同样的问题，用的卡巴斯基，但是没有任何删除或者隔离记录

**Comment by Pinkhai** [comment]
同样的问题，被系统报毒删掉了

**Comment by Eirmero** [comment]
同样的问题，还没法恢复

**Comment by qiutongxue** [comment]
被当木马杀掉了😢

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/53330358/1b5c18c0-639c-42b0-8086-ad3800ae8a31)

**Comment by aknyzsd** [comment]
同问，之前怀疑过杀毒软件的问题，但是并无相关记录![Screenshot_20231217_132024_com.wujie.connect.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121467598/eca0f6a7-b683-46a9-b07e-eed65ce2e6c1)![Screenshot_20231217_132156_com.wujie.connect.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121467598/18a34771-a603-477f-a07e-2c89574f7aec)

**Comment by lpdink** [comment]
应该是Windows Defender删除的，不知道什么原因没有被保护历史记录记录，但在信任maa的exe所在文件夹后，不再被删除了。

**Comment by keytears** [comment]
同火绒，关闭系统自带的defender，两个地方都没有任何防护记录，已经自删四次了。。。甚至放了火绒白名单区也会自删并且没记录。。win11  mumu模拟器

**Comment by Pinkhai** [comment]
![maa](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/107166389/9b75dd9f-3c05-4153-af7f-4ed11c4cb6c9)
被当做木马了

**Comment by aknyzsd** [comment]
> 同问，之前怀疑过杀毒软件的问题，但是并无相关记录![Screenshot_20231217_132024_com.wujie.connect.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121467598/eca0f6a7-b683-46a9-b07e-eed65ce2e6c1)![Screenshot_20231217_132156_com.wujie.connect.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121467598/18a34771-a603-477f-a07e-2c89574f7aec)

问题解决，是由Windows defender删除的，在里面选择信任此文件就可以了，我这边在Win11系统下Windows defender并没有操作记录，需要把exe文件重新解压再用defender快速扫描一次就可以看见日志了![Screenshot_20231217_175828_com.wujie.connect.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121467598/4f67638c-85d2-42ed-a380-8f7a35c8a462)![Screenshot_20231217_175846_com.wujie.connect.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121467598/90bc0b9e-a69a-4af3-bf72-fb5a562f5fb9)

**Comment by aknyzsd** [comment]
> +1,被Windows Defender 疯狂隔离
> ![微信截图_20231217205948](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153105243/379faaab-a6fe-45d8-a097-9ba592172060)
> 

选择信任应该就可以了吧，实在不行就把Windows defender服务关了？（应该可以关）

**Comment by fs910175** [comment]
最近的版本有被Windows Defender及NOD刪除過，不過加入排除之後就正常了。
有被刪除的可以嘗試加入排除試試。

**Comment by TINKOUBUN** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/81556885/5573a853-f525-4c95-86c2-2da8026ea3a6)
本来没启用WD 用的是火绒 MAA被删了两边都找不到删除的日志
WD手动快速扫描跑一遍才能看到这个
WD看来还是在后台工作

**Comment by DreamLeePKU** [comment]
windows defender的报错是Trojan:Script/Wacatac.B!ml
虽然设为白名单即可解决问题，但还是想知道新版本使用了什么新技术以至于突发大规模被检测为病毒

**Comment by ABA2396** [comment]
> windows defender的报错是Trojan:Script/Wacatac.B!ml
> 虽然设为白名单即可解决问题，但还是想知道新版本使用了什么新技术以至于突发大规模被检测为病毒

没啥新玩意，所有版本都是人报有人没报，只是这个版本报的多了（虽然在我电脑上还是没报）。
看到报毒信息里的那个ml了吗，那是machine learning的意思，maa的打包用的是一个开源的第三方库，可以做到把dll之类的都打到一个exe里面（.net5之后提供了单文件发布，但是maa现在用的是.net framework4.8），可能是很多病毒软件都用了这个库打包，然后杀软学习到了这个特征，认为用这个库的软件都是病毒，然后就杀了

**Comment by Zachary-Muadib** [comment]
可以尽快给MAA白嫖个电子签名吗，之前在群里提过的，就是编译发版可能要麻烦一点
