### ISSUE TITLE
Phantom Integrated Gets Permanently stuck in v4.28.3-alpha.1.d004.ge033ce0aa

### ISSUE THREAD

**Issue by whylorainer** [MaaAssistantArknights/MaaAssistantArknights#7658]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Sometimes Auto I.S. module will get stuck trying to enter a fight, and never leave, staying in that screen for hours, without aborting the run, seriously compromising efficiency. MAA will only work again once the run is aborted and the task restarted.

This bug has been reported before, but seems resilient and still present in the new nightly.

### Log files

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13693354/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13693355/asst.log)

### Screenshots

Screenshot of one the fights where MAA gets stuck during Phantom I.S.
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/42009605/aa35994e-85e9-4816-bbb9-dfc5308be08f)

### Anthing else?

Using windows 10, latest MAA nightly build.

**Comment by Lancarus** [comment]
Maybe the roi of this is too small？
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/09485a50-569b-472d-bdf8-860df8a26c2b)
