### ISSUE TITLE
自动返回唤醒界面

### ISSUE THREAD

**Issue by alon74** [MaaAssistantArknights/MaaAssistantArknights#766]
开始任务一段时间后自动返回唤醒页面
![image](https://user-images.githubusercontent.com/42845804/172106785-9da7f91c-0836-4176-84c3-33d39e2f10e9.png)
![image](https://user-images.githubusercontent.com/42845804/172106604-df358528-5b06-4d92-afe4-902074f8f210.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8842280/asst.log)

**Comment by MistEO** [comment]
这应该是掉线了。。

**Comment by alon74** [comment]
问题是现在基本可以稳定复线，每次都掉线吗

**Comment by alon74** [comment]
我这边目前也是刷SV-9大约20局就会返回主界面
是否可以更新一个让MAA在Fight任务中检测到掉线就自动执行StartUP的功能，否则目前基本无法无限刷SV-9

**Comment by ABA2396** [comment]
> 我这边目前也是刷SV-9大约20局就会返回主界面 是否可以更新一个让MAA在Fight任务中检测到掉线(异常返回主界面)就自动执行StartUP的功能，否则目前基本无法无限刷SV-9

有考虑，但是现在没有检测掉线。现在方向是检测超时

**Comment by alon74** [comment]
OK，方法无所谓 能解决问题就行
