### ISSUE TITLE
[日服]信用购物黑白名单功能疑似失效

### ISSUE THREAD

**Issue by mikage3miya** [MaaAssistantArknights/MaaAssistantArknights#7661]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

4.28.2公测版
日服环境下购物环节的行为目测是直接从前往后按顺序购买，黑白名单功能并未产生效果
如下截图所示，白名单未购买而购买了黑名单内容
难道我应该用日语写这个设置项……？

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13693798/asst.log)

### 截图

![Screenshot_2023 12 17_04 56 39 181](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/68894391/ce91c24c-2296-44c9-86c0-7f77455b200e)
![无标题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/68894391/1cb6e973-07ef-487c-941d-cf5db0c47ae7)

**Comment by SherkeyXD** [comment]
日服好像要写日文来着

**Comment by ABA2396** [comment]
是这样的）
