### ISSUE TITLE
MUMU用MAA的退出有问题

### ISSUE THREAD

**Issue by 1458963** [MaaAssistantArknights/MaaAssistantArknights#7663]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Uploading QQ录屏20231217094537.mp4…

### 日志文件

2023 12 17 9：57
[Uploading asst.log…]()
[Uploading gui.log…]()

**Comment by 1458963** [comment]
[Uploading asst.log…]()
[Uploading gui.log…]()

**Comment by 1458963** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13694427/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13694428/gui.log)

**Comment by 1458963** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13694430/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13694431/gui.log)

**Comment by ABA2396** [comment]
mumu6没啥好办法退出，要么升级12，要么把模拟器的名字改成“明日方舟”或者“明日方舟 - MuMu模拟器”

**Comment by 1458963** [comment]
> mumu6没啥好办法退出，要么升级12，要么把模拟器的名字改成“明日方舟”或者“明日方舟 - MuMu模拟器”

就是12

**Comment by ABA2396** [comment]
那你链接设置里选的是12吗

**Comment by 1458963** [comment]
散了吧，散了吧，有笨蛋一种用着 6 的设置
