### ISSUE TITLE
mumu模拟器3.6版本分辨率设置为平板4k（dpi540）后，maa在关卡导航时每次向左滑动超过1横屏导致关卡识别失败

### ISSUE THREAD

**Issue by Yus-git** [MaaAssistantArknights/MaaAssistantArknights#7665]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

mumu模拟器3.6版本分辨率设置为平板4k（dpi540）后，maa（4.28.2版本）在进行fight关卡导航时，每次向左滑动超过1整个横屏，导致关卡RS-6显示不完全，识别失败，升级模拟器到最新的3.6.12版本后依旧无法正确识别

重设模拟器分辨率为2k（dpi360）后，关卡导航进行滑动后，RS-6刚好在屏幕中间，能够被正确识别到

之前模拟器一直使用的4k分辨率，RS-6导航一直没问题，近期有调整过windows系统的缩放，有调整过双屏排列，以及自动重启升级到了4.28版本，不清楚会不会和这些有关
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61584378/2a154222-24db-4b2a-b156-678ff696164d)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61584378/2404414a-1361-4019-b456-e2704750c8dd)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61584378/943e1048-6292-4790-a79e-2486b390513e)

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13694530/debug.zip)
时间为2023-12-17 07:00:00的定时执行任务，因为未识别到RS-6关卡fight失败

**Comment by Yus-git** [comment]
另一个蓝叠模拟器始终使用2k分辨率，没有出现过这个问题

**Comment by ABA2396** [comment]
没办法，方舟只有在关卡界面的滑动距离和分辨率有关，其他地方都是一样的，所以很难去做缩放，只能调分辨率了

**Comment by ABA2396** [comment]
或许是和dpi有关，可以调整试试。不过也不推荐分辨率调这么高。会导致截图时间增加

**Comment by status102** [comment]
4k分辨率未支持
