### ISSUE TITLE
点击位置坐标错误

### ISSUE THREAD

**Issue by Obscure-Rain** [MaaAssistantArknights/MaaAssistantArknights#7666]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

使用MuMu12模拟器，繁中服，初始设置为竖屏时，出现实际点击位置与应点击位置横纵坐标交换（截图功能正常），尝试重装MAA和MuMu均无效

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13694629/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13694630/gui.log)
在大约1个月前出现该问题，更新MAA、MuMu和明日方舟客户端均无法解决

**Comment by SherkeyXD** [comment]
@ABA2396 我记得有人提过这个？当时怎么解决的来着

**Comment by ABA2396** [comment]
> @ABA2396 我记得有人提过这个？当时怎么解决的来着

当时是雷电模拟器吧？试试看把模拟器初始的换成横屏。

**Comment by zzyyyl** [comment]
可以试试换 maatouch

**Comment by bighead945** [comment]
分辨率問題嗎？ 還是換個模擬器看看？

**Comment by horror-proton** [comment]
初始设置为竖屏? 好怪

**Comment by Obscure-Rain** [comment]
> > @ABA2396 我记得有人提过这个？当时怎么解决的来着
> 
> 当时是雷电模拟器吧？试试看把模拟器初始的换成横屏。

换成横屏就解决了，不过MAA以前的版本没有这个问题

**Comment by ABA2396** [comment]
和版本没关系，之前还有雷电点的坐标颠倒呢，传过去的坐标值是对的。
