### ISSUE TITLE
MacOS（14.1.2 (23B92)使用mac版 v4.28.2（442）基建排班无法正确识别 清流+温蒂+异客

### ISSUE THREAD

**Issue by joneszhuang** [MaaAssistantArknights/MaaAssistantArknights#7669]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

大部分时候都是卡在清流然后直接整组跳过，并且所有组别都经常有重复反选四五次才点击确认键的情况。我用的是M1Pro 16寸，系统版本是14.1.2 (23B92)，并且尝试过内置的所有触屏方式，没有明显区别，bug可重现

### 日志文件

mac找不到debug文件夹，求指明

### 截图
<img width="899" alt="截屏2023-12-17 12 51 08" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36681026/536765fc-00be-40f8-a4c8-c49bf2f42199">

_No response_

**Comment by novemberei** [comment]
菜单栏“文件”菜单项目下有“打开日志文件夹”选项。只有运行日志没有gui日志
