### ISSUE TITLE
maa刷魁影而肉鸽，遇到两个路径都是不期而遇的时候将其识别为紧急作战

### ISSUE THREAD

**Issue by mm317670** [MaaAssistantArknights/MaaAssistantArknights#7671]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa刷魁影而肉鸽，遇到两个路径都是不期而遇的时候将其识别为紧急作战，并且没有其余任何操作，将其停止运行后重新开始运行恢复正常.问题出现时间：12-17  15:28:25
asst.log和gui.log以及视频截图有上传

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13695125/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13695126/gui.log)

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142766247/9785c213-6ad9-4c55-be4a-529373b001d5

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142766247/ccc0263b-bb15-4aaa-b4e7-4ddad02e4718

### 截图

![QQ图片20231217154409](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142766247/4b712ead-73a4-4209-b11d-9c843f55b4be)

**Comment by ShaTang886** [comment]
我也遇到了，刚刚提交

**Comment by zzyyyl** [comment]
`v4.28.3-alpha.1.d004.ge033ce0aa` fixed
