### ISSUE TITLE
萨米肉鸽使用密文版避免困难战斗

### ISSUE THREAD

**Issue by joy-joy-joy-joy-joy-joy-joy** [MaaAssistantArknights/MaaAssistantArknights#7672]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用maa刷萨米肉鸽时，似乎不会进行密文版的宣告导致前几层可以避免的困难战斗无法避免而猝死

### 有什么好的想法？

可以加入特定组合的密文版识别逻辑，比如战斗节点和+50%生命值，变为行商节点等，增加前几层的通关率

**Comment by Rbqwow** [comment]
已经会自动用密文板了
~~虽然忘了什么时候加的~~
