### ISSUE TITLE
Window Defender 多次报毒误杀，导致maa无法正常运行。

### ISSUE THREAD

**Issue by Chen-Yixing123** [MaaAssistantArknights/MaaAssistantArknights#7673]
### Window Defender 多次报毒误杀，导致maa无法正常运行

今天中午的时候，maa突然自己退出，桌面的快捷方式无法运行，检查发现是win系统的杀毒报毒了。于是我重新下载了maa，但问题又再次出现，一样是maa被隔离了
![Windows 安全中心 2023_12_17 17_24_23](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71218592/fad1585f-b2ee-45f6-b608-17c2ffd60d2d)

**Comment by status102** [comment]
Duplicate of #6662
