### ISSUE TITLE
刷傀影肉鸽时，进入新层时，在特定的双不期而遇开局时，会识别错误

### ISSUE THREAD

**Issue by ShaTang886** [MaaAssistantArknights/MaaAssistantArknights#7674]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刷傀影肉鸽时，进入新层时，在特定的双不期而遇开局时，会识别错误，会不断点击后方的未开启关卡，日志太大了，压缩了也传不了，我稍微删除了一点前面日期的，bug是从12-17号，17:12:38开始产生的，前面几天也触发过，贴吧上也有人反馈过相似的问题，但在别的肉鸽上这种类似的关卡是都能正常识别，只有傀影会卡

### 日志文件

[jl.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13695523/jl.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153991491/acf105a8-b19b-4c58-86c9-700fa16f3725)
![image2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153991491/f10dcd45-c1fc-4f3d-992a-69cd0726184f)

**Comment by zzyyyl** [comment]
`v4.28.3-alpha.1.d004.ge033ce0aa` fixed
