### ISSUE TITLE
希望支持其他分辨率

### ISSUE THREAD

**Issue by Kumokasumi** [MaaAssistantArknights/MaaAssistantArknights#7676]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

版本号: v4.28.2
由于模拟器分辨率不支持720P或更低分辨率及非16:9尺寸，在使用时会导致报错

### 有什么好的想法？

希望支持720P以下（譬如1024×576）以节省资源或非16:9尺寸

**Comment by ABA2396** [comment]
图太小了，信息丢失太多，压缩之后的图在模板匹配中特征对不上
