### ISSUE TITLE
Windows Defender报毒并强制删除MAA

### ISSUE THREAD

**Issue by StevenKxy** [MaaAssistantArknights/MaaAssistantArknights#7679]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

最新版的MAA会被Windows Defender识别为病毒并强制删除，暂未找到解决方案，无法通过白名单躲掉强删

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13697373/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13697374/gui.log)

### 截图

![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/69781522/616e0d3d-b507-43c4-91a4-ad03cf2739db)

**Comment by todomato** [comment]
遇到同樣的問題

**Comment by ABA2396** [comment]
加文件夹白名单不行吗
#6662

**Comment by Do7and** [comment]
遇到同样问题，直接帮我删了maa，找到老的包重新安装重现了maa识别为病毒然后被删除

**Comment by hutaowolaopo** [comment]
我也遇到同样问题

**Comment by 524388475** [comment]
同样问题

**Comment by ABA2396** [comment]
别同样问题了，根据 #6662 操作过了吗

**Comment by hutaowolaopo** [comment]
操作之后，由于之后重新装了一个先前版本，暂时没有出现问题
