### ISSUE TITLE
肉鸽挂机卡在不期而遇，疯狂错报成紧急作战

### ISSUE THREAD

**Issue by SGFT27** [MaaAssistantArknights/MaaAssistantArknights#7681]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

挂机傀影肉鸽当新一层的开局节点是不期而遇的时候MMA就会呆住，右侧疯狂的不停刷新紧急作战的播报

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13697446/debug.zip)

12月18日凌晨2点10前后

### 截图

![1414](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154086312/502eda2b-4071-47c2-b7d3-1a30055bf48e)
![2323](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154086312/0d2fcacf-5485-42d2-afba-7a1b6bc0ccfd)

### 还有别的吗？

雷电模拟器   WIN10

**Comment by zzyyyl** [comment]
alpha fixed
