### ISSUE TITLE
maa被系统自动删除

### ISSUE THREAD

**Issue by Realms61** [MaaAssistantArknights/MaaAssistantArknights#7685]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

maa在使用一段时间之后自动关闭，桌面快捷方式消失，文件夹内无MAA.exe文件，疑似被火绒删除

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13703213/gui.log)

**Comment by status102** [comment]
#6662
