### ISSUE TITLE
刚更新怎么报毒了

### ISSUE THREAD

**Issue by Centursy** [MaaAssistantArknights/MaaAssistantArknights#7688]
### 说说你遇到的问题？

这个2b系统自动给我删了，折断了我的翅膀
![GF3AKBE7{ MZ_V55YYYJA1T](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/98018410/fd378398-9f56-46a5-87b5-5545e87491d2)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/98018410/7153e966-cbaa-4743-a0b0-36c0d7aa401a)

**Comment by status102** [comment]
#6662
