### ISSUE TITLE
萨米肉鸽请添加自动搜索稀有坍缩功能

### ISSUE THREAD

**Issue by kkujukk** [MaaAssistantArknights/MaaAssistantArknights#7689]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

水月肉鸽已经有了搜索指路麟功能，萨米能不能添加一个自动寻找稀有坍缩图鉴功能

### 有什么好的想法？

每次游戏都会有4种坍缩泛式，maa自动检测到4种后识别图片如果有稀有坍缩开启2级图鉴 没有稀有坍缩直接重开

**Comment by Saratoga-Official** [comment]
#9172 已增加
