### ISSUE TITLE
傀影肉鸽自动作战卡死

### ISSUE THREAD

**Issue by Marcent** [MaaAssistantArknights/MaaAssistantArknights#7692]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

傀影肉鸽的自动作战时，如果每层的开场是两个不期而遇，程序会不断尝试选择紧急作战，从而卡死无法继续自动肉鸽。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13705900/gui.log)

**Comment by zzyyyl** [comment]
alpha fixed
