### ISSUE TITLE
傀影肉鸽错误识别紧急作战并且可能导致在遇到特定关卡结构时MAA卡死

### ISSUE THREAD

**Issue by wifi7cs** [MaaAssistantArknights/MaaAssistantArknights#7693]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

- 在傀影肉鸽中，当首次遇到紧急作战节点后，之后所有作战节点（除boss关卡外）均会被错误识别为“关卡：紧急作战”；

- 并且在换层后遇到的两个平行的可选节点均为不期而遇时（具体关卡结构如图所示，每一次bug均在该情况下出现），MAA仍会以每秒一次左右的速度错误识别并在log中报告为“关卡：紧急作战”，从而无法进行后续的任何操作。

### 日志文件

问题出现的时间点：[2023-12-19 00:10:31.986]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13706929/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13707098/asst.zip)

### 截图

![maa_bug](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/48312003/828349b5-f239-4e9d-b333-b1f5042085a5)

### 还有别的吗？

MAA：v4.28.2
模拟器：雷电模拟器9.0.60
操作系统：Windows 11

**Comment by ABA2396** [comment]
v4.28.3-alpha.1.d004.ge033ce0aa fixed
