### ISSUE TITLE
安装目录下启动程序自动消失

### ISSUE THREAD

**Issue by MrDrown32** [MaaAssistantArknights/MaaAssistantArknights#7697]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

不知道为什么启动器在运行一段时间后会消失

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13711718/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13711719/gui.log)

### 截图

<img width="568" alt="屏幕截图 2023-12-19 135247" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145359981/dc266d9a-7d72-4842-8ba2-84222995b88c">

**Comment by status102** [comment]
#6662
