### ISSUE TITLE
[台服] 自定義基建換班辨認 麒麟R夜刀 失敗

### ISSUE THREAD

**Issue by kobi1108** [MaaAssistantArknights/MaaAssistantArknights#7698]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

辨認 麒麟R夜刀 失敗，掃了幾次抓不到截圖
BlueStack5 最新版
maa V4.28.2
2K DPI320
window11

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13712128/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13712136/gui.log)

19/12/2023 14:32

### 截图

https://youtu.be/BN3AxMdNj5U
由於檔案太大，改爲YT上傳
![螢幕擷取畫面 2023-12-19 144136](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140871439/a3207d41-d4c5-49cc-ad4d-f05ddfa5efa3)

**Comment by Constrat** [comment]
Well this is strange. The auto-updated did not add Kirin R Yato to the txwy ocrReplace.
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/cfa92f367c52e3544500d3be9424bcd67b5194d3#diff-341485e6cc4320865559610c800d639a69cd01d479b325b1506b8f6ab1a9e4a4

**Comment by Constrat** [comment]
@zzyyyl Through tasks inheritance is there a way to inherit the ocrReplace values? Or should I just copy this to the txwy tasks?
```json
            [
                ".*麟.*夜刀$",
                "麒麟R夜刀"
            ],
            [
                "麒.+夜刀$",
                "麒麟R夜刀"
            ],

```

**Comment by kobi1108** [comment]
![螢幕擷取畫面 2023-12-24 144726](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140871439/614cb89a-9b73-43e6-b880-f8e576e6d483)
剛剛換班之後就變成這樣 其他幹員忘記點選了

![螢幕擷取畫面 2023-12-24 144851](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140871439/05f46129-fc40-4af3-9227-1f085a846f18)


[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13761076/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13761077/gui.log)
24/12/2023 14:06:22

**Comment by kobi1108** [comment]
2024/2/13更新 問題依舊存在
大部分時候最後會只選中夜刀 其餘4個空的
BS 最新版
maa beta最新版 

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140871439/ae74b0da-6d38-4057-8e6b-68843a3aa57f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140871439/1134aa6f-8086-430b-b749-202cf9e78768)

[2024-02-13 14:09:25]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14258244/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14258246/asst.log)
