### ISSUE TITLE
傀影肉鸽进下一层后卡死

### ISSUE THREAD

**Issue by Freeamiya** [MaaAssistantArknights/MaaAssistantArknights#7699]
傀影肉鸽在进到第三层或者第四层后会出现卡死现象，具体表现为无法识别“不期而遇”，一直刷屏“紧急作战”
<img width="1092" alt="屏幕截图 2023-12-19 170235" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/152605987/2bf71970-c1c7-474f-946f-1eb972af39f4">

**Comment by zzyyyl** [comment]
alpha fixed
