### ISSUE TITLE
自动肉鸽关卡摆放优化建议

### ISSUE THREAD

**Issue by guojunyu196** [MaaAssistantArknights/MaaAssistantArknights#770]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8842813/asst.log)
自动肉鸽关卡“斗兽笼”建议将近战干员优先放于中间，肉鸽自动战斗时将干员优先放于四周了，导致中间的怪全漏，关卡失败

**Comment by guojunyu196** [comment]
![Screenshot_2022 06 06_17 17 38 544](https://user-images.githubusercontent.com/76220347/172133099-64eff5dd-9fc5-4c25-8bc9-664209b754d8.png)
开门请当心近卫摆放位置不正确

**Comment by guojunyu196** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8844459/asst.log)
[录屏.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8844463/default.zip)
奇怪的干员放置bug

**Comment by ABA2396** [comment]
现在的肉鸽逻辑就是堵蓝门，会把干员往靠近蓝门的地方放，斗兽笼因为都是蓝门，所以）

**Comment by MistEO** [comment]
fixed
