### ISSUE TITLE
傀影肉鸽进行至三层后会莫名判定“紧急作战”关卡导致自动肉鸽卡住

### ISSUE THREAD

**Issue by Lacrimosa2236** [MaaAssistantArknights/MaaAssistantArknights#7702]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如标题所言，傀影肉鸽挂机一段时间后会在刚进入第三层时判定识别到紧急作战节点然后莫名的卡住并反复识别紧急作战节点导致任务卡死……

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13715038/debug.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71539538/f30cc76e-5579-41e5-ae55-70c8fe8dbb52)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71539538/24572d9d-0260-4866-8434-7933cd404e28)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71539538/24abaac8-8dcb-4a9b-b4f9-7deea33da3c5)

![Screenshot_20231219-193535](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71539538/92b02d73-b0a9-41eb-82cc-b7da1b41c79e)
注：maa卡住的时候并没有进入不期而遇节点，当时为了得过且过尝试点进去让maa继续运行但是失败了（泪

### 还有别的吗？

模拟器：雷电模拟器9.0.60（9）
操作系统：win11
第一次发issue，如有纰漏还请谅解，我的qq是1259984721，需要的话可以加我qq沟通哦，辛苦啦~

**Comment by Tillana** [comment]
同样遇到了这个bug，不过若是手动过了不期而遇的节点进入下一个作战又会恢复正常

**Comment by zzyyyl** [comment]
alpha fixed
