### ISSUE TITLE
连接模拟器连接失败

### ISSUE THREAD

**Issue by Serein1207** [MaaAssistantArknights/MaaAssistantArknights#7703]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

运行了半个月一直正常，今天突然连接失败，重新安装了Maa也没用，重启模拟器也没用

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13715712/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13715713/gui.log)

### 截图

![1702989281767](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/152179215/d6853fc8-4b26-473a-9643-9d3fbead958f)

### 还有别的吗？

使用的是mumu12模拟器，Windows x64系统

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/2d2eafe9-12f8-4cbc-85e7-bb013c20cb6e)

**Comment by SherkeyXD** [comment]
看看你的连接设置

**Comment by Ramiel-s** [comment]
我也遇到了类似的问题，之前一年半使用正常，更新后再也无法自动打开模拟器。常用的管理员权限打开，重装重启之类的都尝试过了。用的是蓝叠国际版，手动设置Bluestacks.Config.Path 也不行。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/132727635/31bcff6c-0558-46c6-8a2e-33e5fd57bbee)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/132727635/b8d2d7eb-24b8-4c6e-9d7f-7694a4b49c50)

**Comment by ABA2396** [comment]
> 我也遇到了类似的问题，之前一年半使用正常，更新后再也无法自动打开模拟器。常用的管理员权限打开，重装重启之类的都尝试过了。用的是蓝叠国际版，手动设置Bluestacks.Config.Path 也不行。
 ![image](https://private-user-images.githubusercontent.com/132727635/292026271-31bcff6c-0558-46c6-8a2e-33e5fd57bbee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjM1NjcsIm5iZiI6MTcwMzEyMzI2NywicGF0aCI6Ii8xMzI3Mjc2MzUvMjkyMDI2MjcxLTMxYmNmZjZjLTA1NTgtNDZjNi04YTJlLTMzZTVmZDU3YmJlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwMTQ3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTlkMWMzMTE1ZjU5MjI3OTZkYmRiODUyMzZjNDQ1NWI3MmI5MTc5OWFiMTMyMTkyMGY2ODQ1ODRkYjJiYzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UldUWS_h6nXRiGcZbCmoYYVpsvQc7Ej5QVek_GrCYU4) ![image](https://private-user-images.githubusercontent.com/132727635/292026348-b8d2d7eb-24b8-4c6e-9d7f-7694a4b49c50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjM1NjcsIm5iZiI6MTcwMzEyMzI2NywicGF0aCI6Ii8xMzI3Mjc2MzUvMjkyMDI2MzQ4LWI4ZDJkN2ViLTI0YjgtNGM2ZS05ZDdmLTc2OTRhNGI0OWM1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwMTQ3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjU1MzVhOTAwMGM2YTQ2NzM0NGUzMTFmYjY0NTVhM2M1NDRmMTgyOTIxMGNiMzcyZDk4M2E0NzM2YmQwMmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qVEN6-6xwLKhbppo6DdwDcqsv5AM4noL2LLSkqSwGC0)

遇到问题发日志，而不是截两张图就完事了，这能看出什么

**Comment by ABA2396** [comment]
> 看看你的连接设置

看日志估计是电脑里还开了其他的adb，先试试强制替换ADB，再不行的话就找找有没有开着什么手机助手，都给关了。
```
adb server version (19045) doesn't match this client (41); killing...

could not read ok from ADB Server

* failed to start daemon

error: cannot connect to daemon
```
再不行的话就是adb的版本太高了和 client 对不上，但用的是 MuMu 自己的 adb，基本不可能会是这个原因，上面都试过不行的话在去下个.41版本的adb

**Comment by ABA2396** [comment]
> 看看你的连接设置

看日志估计是电脑里还开了其他的adb，先试试强制替换ADB，再不行的话就找找有没有开着什么手机助手，都给关了。
```
adb server version (19045) doesn't match this client (41); killing...

could not read ok from ADB Server

* failed to start daemon

error: cannot connect to daemon
```
再不行的话就是adb的版本太高了和 client 对不上，但用的是 MuMu 自己的 adb，基本不可能会是这个原因，上面都试过不行的话在去下个.41版本的adb

**Comment by SherkeyXD** [comment]
> adb server version (19045) doesn't match this client (41); killing...

应该就是360手机助手的锅了，我记得之前有过 issue

**Comment by SherkeyXD** [comment]
> 我也遇到了类似的问题，之前一年半使用正常，更新后再也无法自动打开模拟器。常用的管理员权限打开，重装重启之类的都尝试过了。用的是蓝叠国际版，手动设置Bluestacks.Config.Path 也不行。

建议新开个 issue，这样什么都看不出来

**Comment by Serein1207** [comment]
> > 查看您的连接设置
> 
> 看日志估计是电脑里还打开了其他的adb，先试试强制替换ADB，再不行的话就找有没有开着什么手机助手，都给关了。
> 
> ```
> adb server version (19045) doesn't match this client (41); killing...
> 
> could not read ok from ADB Server
> 
> * failed to start daemon
> 
> error: cannot connect to daemon
> ```
> 
> 再不行的话就是adb的版本和客户端对不上，但用的是MuMu自己的adb，基本不可能会是这个原因，上面都试过不行的话在去下个.41版本的adb

谢谢，卸载了360手机助手以后就能正常运行了，但是出现了如图所示的红字部分，不知道会不会有什么影响。
![1703399156126](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/152179215/db6e2745-4704-475f-b85b-4fe6d9b3ea97)

**Comment by Serein1207** [comment]
> > adb 服务器版本 (19045) 与此客户端 (41) 不匹配；杀...
> 
> 应该就是360手机助手的锅了，我记得之前有过问题
> 
> @Serein1207看看是不是安装了这东西，是的话关掉再启动maa试试，不行的话卸载再看看

谢谢，确实是360手机助手的问题，卸载以后就能运行了
