### ISSUE TITLE
Maa.exe忽然又自己消失了

### ISSUE THREAD

**Issue by SaltedFish9487** [MaaAssistantArknights/MaaAssistantArknights#7704]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

這幾天都有用maa代理，就今天下午的時候突然window defender又把maa刪除了，想著重新下載然後依然會跳警告

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13715884/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13715886/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154337199/53eb9180-5452-486a-9dd3-5f92ff19f525)
![圖片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154337199/f3f8f36a-412d-4a66-b130-9f8cf6724a3a)

**Comment by Effrontery** [comment]
我与你的情况相同，并且我安装了火绒并且已经把MAA整个文件夹都放入信任区中，但依然是：
1. 桌面的快捷方式已被删除
2. 文件夹内的启动项已被删除，.olds文件也被删除
<img width="577" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64764218/26f9e8f7-9a8b-49b7-b85c-d565219059e1">

我想请问这个截图内容和日志文件在哪里可以找到

**Comment by SaltedFish9487** [comment]
> 我与你的情况相同，并且我安装了火绒并且已经把MAA整个文件夹都放入信任区中，但依然是：
> 
>     1. 桌面的快捷方式已被删除
> 
>     2. 文件夹内的启动项已被删除，.olds文件也被删除
> 
> 
> <img alt="image" width="577" src="https://private-user-images.githubusercontent.com/64764218/291598698-26f9e8f7-9a8b-49b7-b85c-d565219059e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTI5MDcsIm5iZiI6MTcwMjk5MjYwNywicGF0aCI6Ii82NDc2NDIxOC8yOTE1OTg2OTgtMjZmOWU4ZjctOWE4Yi00OWI3LWI4NWMtZDU2NTIxOTA1OWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEzMzAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZjI3YjE5MmY4NTFiODI3YzFiZmZkOWEzZDNjOWI1Mzk3NWVkZjcyMGM5Y2M0MmE2ODdhZGZkMmY5NjI3ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZiQXZxdLycoWEuB07iOScot4b8n-TPLsYAgZEzFD_MU">
> 
> 我想请问这个截图内容和日志文件在哪里可以找到，就是您的问题中的那些内容

debug檔案夾 那裏

**Comment by status102** [comment]
#6662
