### ISSUE TITLE
MAA.exe会毫无理由的消失

### ISSUE THREAD

**Issue by FallenSequoia** [MaaAssistantArknights/MaaAssistantArknights#7708]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我不清楚这bug是怎么发生的，MAA在近期自动更新的版本会出现exe执行程序莫名消失的情况
我尝试手动下载了最新版本，但使用了两次后又显示快捷方式找不到maa.exe
检查过火绒和Windows defender的历史记录，没有发现任何删除情况

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13717405/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13717406/gui.log)

### 还有别的吗？

网易mumu12模拟器，win11系统
配置：i9 13900HX，32G内存，RTX4060，MAA安装于固态硬盘内

**Comment by status102** [comment]
#6662
请将MAA所在文件夹添加至杀软白名单
