### ISSUE TITLE
傀影肉鸽异常卡在两个不期而遇位置无限循环紧急作战

### ISSUE THREAD

**Issue by hugoking1986** [MaaAssistantArknights/MaaAssistantArknights#7709]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

傀影肉鸽异常卡在两个不期而遇位置无限循环紧急作战

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13718089/debug.zip)

### 截图

![BUG](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38581263/7b2881e0-618e-4056-94d4-2a164fab9184)

**Comment by ABA2396** [comment]
alpha fixed
