### ISSUE TITLE
肉鸽模式无法运行

### ISSUE THREAD

**Issue by 2680665965** [MaaAssistantArknights/MaaAssistantArknights#7710]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动肉鸽运行以后立即完成
手动打一次肉鸽在启动也有该问题

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13722147/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13722156/asst.log)
九点半左右

### 还有别的吗？

mumu12 win系统
https://www.bilibili.com/video/BV19a4y1z7d9/ 问题操作录屏

**Comment by ABA2396** [comment]
高级设置里是不是把次数设成0了

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/765ed257-ffb7-4915-9ec8-f6feb80b5f1d)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/cc4a45fb-ea1c-43c2-8f89-2158634a60b2)

**Comment by 2680665965** [comment]
> 高级设置里是不是把次数设成0了

卧槽 大佬牛逼  真的是 不知道啥时候改的
