### ISSUE TITLE
【建议】能否增加自动打剿灭的功能

### ISSUE THREAD

**Issue by SKIE1** [MaaAssistantArknights/MaaAssistantArknights#7711]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

提供一个选项，如果当前剿灭收益未满且有体力，则优先打剿灭。可能只需要在终端主界面识别是否有剿灭进度条。

**Comment by status102** [comment]
刷理智-关卡-剿灭模式

**Comment by status102** [comment]
可以去搜搜看看，不知道有没有人提过
