### ISSUE TITLE
傀影肉鸽遇到两个不期而遇会卡死

### ISSUE THREAD

**Issue by suisuiyang** [MaaAssistantArknights/MaaAssistantArknights#7713]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

自动打傀影肉鸽时，如果进到新的一层时最开始的时两个不期而遇，那maa会卡死不动，并且过了10分钟后不会自动重开，手动选择一个不期而遇后会自动重开肉鸽

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13723722/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13723723/gui.log)
出现时间：12.20 02:17:15

### 截图

![屏幕截图(458)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30796619/e91805f8-80ae-4c95-a285-1afbed11cd8b)
![屏幕截图(459)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30796619/868d96bb-e8c0-4b7d-a82c-b3ee6d52cf08)

### 还有别的吗？

使用的模拟器是雷电9

**Comment by zzyyyl** [comment]
alpha fixed
