### ISSUE TITLE
在打肉鸽傀影与猩红孤钻的时候遇到了卡关卡不识别无法继续继续的现象

### ISSUE THREAD

**Issue by Mirichii** [MaaAssistantArknights/MaaAssistantArknights#7716]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

在打肉鸽傀影与猩红孤钻的时候遇到了卡关卡不识别无法继续继续的现象

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13724143/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13724144/asst.log)

### 截图

![2023-12-20_145729](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154409645/d8bb4378-6408-4b8f-9004-6108161a78f0)
![2023-12-20_145742](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154409645/3503a9d2-0364-4eaa-a607-0491dd01f803)

### 还有别的吗？

MUMU模拟器

**Comment by Mirichii** [comment]
是肉鸽，打错字了

**Comment by zzyyyl** [comment]
alpha fixed
