### ISSUE TITLE
萨米肉鸽多次放弃探索

### ISSUE THREAD

**Issue by Saratoga-Official** [MaaAssistantArknights/MaaAssistantArknights#7718]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

萨米肉鸽多次放弃探索，用的刷等级策略

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13724210/asst.zip)

### 截图

![SYMDMMANO)10`Q7%LHCLCG3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151550168/3ff3e079-7972-4caf-8c8e-9de116d28ca1)
![J(S1{OZZ 7T6{NDZN Z QNH](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151550168/68a5aed9-e539-42bc-8748-e776b8721996)
![F_9ENXZW(}K(3VPUHM)LKDT](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151550168/894ee089-3a37-4a61-ad2f-43309763367f)
![((OQXM~WVZ5%VD)G3L8F9VL](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151550168/5bcf8189-382a-41b5-877a-e58bf969b46f)

**Comment by zzyyyl** [comment]
debug/roguelike的截图打包一下？

另外内测版有肉鸽相关的更新，可以试试先

**Comment by Saratoga-Official** [comment]
截图打包太大了传不上去。。。
已经在试更新内测版了

**Comment by zzyyyl** [comment]
看看这个： debug\roguelike\2023-12-20_14-30-32-621_raw.png

**Comment by Saratoga-Official** [comment]
![2023-12-20_14-30-32-621_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151550168/3461c375-1c5d-4db4-8775-f45bb7dfa251)

**Comment by zzyyyl** [comment]
你传的asst.log里就只有这一次放弃，先修了.jpg

其实肉鸽挂一天放弃个两三次算正常情况了（x
