### ISSUE TITLE
萨米肉鸽前行的林地卡住

### ISSUE THREAD

**Issue by fzj-official** [MaaAssistantArknights/MaaAssistantArknights#7721]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽前行的林地卡住，当抗干扰指数为0时

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13726580/debug.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144503397/704a0971-80a3-47e4-a3a5-8346f07b2229)

**Comment by status102** [comment]
Duplicate of #7789
