### ISSUE TITLE
maa重连模拟器失败后，提示桌面合成已禁用，修改缩放比例到100%，并造成黑屏死机

### ISSUE THREAD

**Issue by Afishflyinthesky** [MaaAssistantArknights/MaaAssistantArknights#7722]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在模拟器卡住之后，maa尝试重启但是重启失败，我手动重启模拟器之后，maa在工作了一段时间之后，开始修改我的缩放比例到100%，然后我的电脑就弹出了一个提示窗口0x00007FFA4F234ED0指令引用了0x0000000000000020内存。该内存不能为 read .
之后电脑只剩两个提示窗口，重启之后电脑花屏了一个

### 日志文件

操作无法完成，因为已禁用桌面合成。 (异常来自 HRESULT:0x80263001)解决方案出现未知错误详细信息System.Runtime.InteropServices.COMException (0x80263001): {已禁用桌面合成} 操作无法完成，因为已禁用桌面合成。 (异常来自 HRESULT:0x80263001)   在 Standard.NativeMethods.DwmExtendFrameIntoClientArea(IntPtr hwnd, MARGINS& pMarInset)   在 System.Windows.Shell.WindowChromeWorker._ExtendGlassFrame()   在 System.Windows.Shell.WindowChromeWorker._UpdateFrameState(Boolean force)   在 System.Windows.Shell.WindowChromeWorker._HandleDwmCompositionChanged(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean& handled)   在 System.Windows.Shell.WindowChromeWorker._WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)   在 System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 截图

![IMG_20231220_232700](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99204699/08b2a240-b35a-469d-9306-7116e3b60035)
![IMG_20231220_232704](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99204699/279ca475-0ad1-4ab1-b95f-589933f0b912)

**Comment by ABA2396** [comment]
还真是第一次见到这玩意，发一下gui.log

**Comment by Afishflyinthesky** [comment]
> 还真是第一次见到这玩意，发一下gui.log

电脑重启之后，可以在哪里找到这个guide.log，我当时只能复制下来他的报错信息，所有的点击都没有反应

**Comment by ABA2396** [comment]
debug/gui.log

**Comment by TimCrownie** [comment]
> > 还真是第一次见到这玩意，发一下gui.log
> 
> 电脑重启之后，可以在哪里找到这个guide.log，我当时只能复制下来他的报错信息，所有的点击都没有反应
MAA文件夹/debug处的gui.log

**Comment by Afishflyinthesky** [comment]
> debug/gui.log

**Comment by Afishflyinthesky** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13730181/gui.log)

**Comment by ABA2396** [comment]
看样子不像是maa引起的，倒像是模拟器崩了然后把显卡驱动也给炸了）

**Comment by Afishflyinthesky** [comment]
我已收到

**Comment by Afishflyinthesky** [comment]
我已收到
