### ISSUE TITLE
傀影肉鸽在进入新一层时偶尔会把不期而遇识别为紧急作战，然后卡住

### ISSUE THREAD

**Issue by bronzitro** [MaaAssistantArknights/MaaAssistantArknights#7725]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

傀影肉鸽在进入新一层时偶尔会把不期而遇识别为紧急作战，然后卡住

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13739437/asst.log)

### 截图

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/4899212/2701d092-d91f-4992-a514-4d190f352a22)

**Comment by zzyyyl** [comment]
alpha fixed
