### ISSUE TITLE
基建换班偶尔识别错误，常见于会客室伊内丝换不上

### ISSUE THREAD

**Issue by SK-ileana** [MaaAssistantArknights/MaaAssistantArknights#7727]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

基建换班，偶尔会在某个房间识别不到干员导致换班换不上，比较常见的是会客室要换上伊内丝的时候，伊内丝识别不到，导致换班失败，其他干员识别失败比较少见，图中是 12月21日16时04分50秒时贸易站换班但书、摩根、推王失败的截图，之前伊内丝换班失败没有截图

### 日志文件

[2023-11-15 03:56:07.337] 伊内丝, 陈 换班失败
[2023-12-02 16:05:26.298] 伊内丝, 伺夜 换班失败
[2023-12-18 03:55:44.512] 伊内丝，陈 换班失败
[2023-12-21 16:04:50.359] 但书, 摩根, 推进之王 换班失败
[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13741696/log.zip)

### 截图

![捕获](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154521098/95967b2d-67f8-4a71-8230-3b4788741efd)

### 还有别的吗？

BlueStacks 5.9.410.1001 国际版 Nougat32
Windows 10 专业版 21H2

**Comment by ABA2396** [comment]
InfrastClearButton （就那个清空干员的按钮）点击失败了，感觉像是模拟器卡住了没进到设施里面去，所以找不到这玩意。
@zzyyyl ["InfrastOperListTabSkillUnClicked","Stop"]这玩意里面是不是应该再加个重试
