### ISSUE TITLE
蓝叠经常卡死怎么办

### ISSUE THREAD

**Issue by zhangweijian97** [MaaAssistantArknights/MaaAssistantArknights#7728]
### 说说你遇到的问题？

如题。一两天就得重启。
我一台电脑，win11。i7-10700 CPU @ 2.90GHz (16 CPUs)，16G内存。无独显，Intel(R) UHD Graphics 630。
然后用多开，同时开两个，官服和b服。两个蓝叠的配置都是4cpu，4G内存。其他都是默认设置，比如240DPI。性能模式方面。之前是高性能，这两天改成均衡。没区别，照样卡死。
我平常都错开来运行maa，比如，官服8点开始，b服9点开始。可是还是经常卡死。

请问该怎么设置比较好？应该给蓝叠分类多少资源？蓝叠的设置应该如何设置？maa运行的时候会占用多少资源？

**Comment by zzyyyl** [comment]
蓝叠经常卡死？那换模拟器呗（确信

**Comment by zhangweijian97** [comment]
> 蓝叠经常卡死？那换模拟器呗（确信

决定换mumu了。顺带一提，蓝叠把我c盘占用了122GB。也不知道怎么搞的
