### ISSUE TITLE
傀影肉鸽进入第二层识别错误，无法进行

### ISSUE THREAD

**Issue by 2woniu** [MaaAssistantArknights/MaaAssistantArknights#7729]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

傀影肉鸽第二层不期而遇持续识别为紧急作战，卡住无法进行

### 日志文件

MAA已删除，无文件

**Comment by status102** [comment]
尝试使用内测版，问题看起来修了（没有log无法确定实际问题
