### ISSUE TITLE
干员识别错误

### ISSUE THREAD

**Issue by uzhao** [MaaAssistantArknights/MaaAssistantArknights#7736]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

异格鲨鲨没有识别到

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13747620/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13747621/gui.log)

### 截图

![2023-12-21_18-13-03-319_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/5157125/e39ddcba-9da0-4256-bb6d-93b37fa2132c)
![2023-12-21_18-18-20-993_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/5157125/b07580b2-4cf0-4c80-bac4-909ba1e66d9e)
![2023-12-21_18-18-32-298_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/5157125/9f979f35-3040-446c-8bf4-873125fdfa0e)

**Comment by zzyyyl** [comment]
特别关心会挡识别
