### ISSUE TITLE
建议添加森空岛自动签到

### ISSUE THREAD

**Issue by ShiliangLu** [MaaAssistantArknights/MaaAssistantArknights#7737]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我是懒鬼

### 有什么好的想法？

森空岛自动签到解放双手防止忘记

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantSkland

**Comment by status102** [comment]
duplicate of #6167
