### ISSUE TITLE
使用一键代理复刻 SS 活动功能时，出现了导航错误

### ISSUE THREAD

**Issue by starrin** [MaaAssistantArknights/MaaAssistantArknights#7739]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在今天照我以火复刻活动开放后，我使用参数SSReopen-FC尝试一键代理所有关卡，一直到FC-5都一切正常，但是MAA并没有进入到FC-6，而是似乎在一系列操作后转回了FC-1（当时我并没有在留意屏幕所以不是特别确定），并在重打一次FC-1后开始尝试进入FC-2。此时我发现了异常并主动停止了MAA的执行。
我的剩余理智应该在打完FC-5后就剩得不多了，不够打FC-6，怀疑可能是吃理智药的动作造成了干扰

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13750854/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13750855/gui.log)

**Comment by SilentC1ty** [comment]
这功能咋打开，我好像没找到入口

**Comment by ABA2396** [comment]
我看着发现点了俩下吃药但没吃到，应该是吃药这一步骤有问题
