### ISSUE TITLE
蓝叠国际版5.5.100.1040 N64 在更新到最新测试版后无法进行任务

### ISSUE THREAD

**Issue by one-pyy** [MaaAssistantArknights/MaaAssistantArknights#774]
![image](https://user-images.githubusercontent.com/72590023/172150537-b01792d8-9bee-418a-ae6e-4b7ad893707d.png)
如图, 会在这里卡死
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8843981/asst.log)

**Comment by one-pyy** [comment]
另外, 看过adb端口是正确的

**Comment by zzyyyl** [comment]
我雷电，也差不多
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8843992/asst.log)
![image](https://user-images.githubusercontent.com/74587068/172151073-ea043d65-3748-49b8-9091-139d4508b175.png)

**Comment by iiSlash** [comment]
相同问题 蓝叠国际版PIE执行任务没反应 MUMU可用
