### ISSUE TITLE
SSReopen 覆盖哪些关卡？

### ISSUE THREAD

**Issue by fuyn101** [MaaAssistantArknights/MaaAssistantArknights#7740]
### 说说你遇到的问题？

https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6230

问一下 顺序是什么
从1到9 还是从1到8 还是 从代号的开头到代号结尾 
例如有一个XX-11 那会从XX-1 推到XX-11么

**Comment by ABA2396** [comment]
当时写的是1~9，但肯定是有问题的，之后改一下。

**Comment by status102** [comment]
目前有啥活动是有11关的么

**Comment by fuyn101** [comment]
> 目前有啥活动是有11关的么

只是一个虚拟的例子 因为有不同长度的本
8 9 10什么的 我只是在问 最后一关会不会打（）
