### ISSUE TITLE
无法上传企鹅物流

### ISSUE THREAD

**Issue by surenry** [MaaAssistantArknights/MaaAssistantArknights#7743]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA更新之后我刷FC-6无法上传企鹅物流，今天更新前刷1-7的时候还是正常的。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13753113/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13753120/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114335781/bb5a0000-d55b-4a76-8b06-acb76b07199f)

**Comment by husy8** [comment]
看起来像是企鹅物流那边的问题。我把 `debug/drops` 下的截图用企鹅物流官方的截图识别都报了异常掉落

**Comment by broken-paint** [comment]
老问题了，之前一些活动关卡也出现过这个bug，如果刷主线常驻关卡汇报应该没问题

**Comment by ABA2396** [comment]
要等地图资源和企鹅那边的汇报接口更新
