### ISSUE TITLE
自动战斗崖心识别出错

### ISSUE THREAD

**Issue by broken-paint** [MaaAssistantArknights/MaaAssistantArknights#7744]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

灵知悖论模拟，精二立绘，好像识别成 `崖心8` 和`崖I` 了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13754325/asst.log)

### 截图

<img width="960" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131476796/c1a2e69d-74a7-4dca-b905-11afbc9d73d8">

**Comment by Constrat** [comment]
Should be "easily" fixable by tweaking the OCR white / black threshold
