### ISSUE TITLE
GUI窗口H较小时，关卡信息提示滚动显示不完全

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#7750]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如截图GIF所示，在GUI窗口高度较小时。FC-7的关卡信息在单次wheel down和单次wheel up不能显示完全（被掠过）

### 日志文件

无

### 截图

![截图_20231223114423](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/53437291/c5b7168a-a193-4510-b2b5-8b93d64d3f02)

### 测试条件：
Win缩放150%，Master3S段落模式，并使用python ctypes.windll.user32.mouse_event复现成功
<details> 
    <summary>python code</summary>
```python
import ctypes
MOUSEEVENTF_WHEEL = 0x0800
WHEEL_DELTA = 120 # 根据MS定义，WELL_DELTA采用120为一次滚动
def mouse_event(dwFlags, dx, dy, dwData, dwExtraInfo):
    ctypes.windll.user32.mouse_event(dwFlags, dx, dy, dwData, dwExtraInfo)
def mouse_wheel_event(scoll: int):
    mouse_event(MOUSEEVENTF_WHEEL, 0, 0, scoll * WHEEL_DELTA, 0)
mouse_wheel_event(-1)
mouse_wheel_event(1)
...
```
</details>

### GUI窗口大小：
|探测方法|W|H|
|:--:|:--:|:--:|
|win32gui.SetWindowPos|895 |514|
|截图窗口捕获|1279 |901|
|WinSpy++|1280|900|

<details> 
    <summary>Win10 22H2</summary>
    <p>版本	Windows 10 专业版</p>
    <p>版本号	22H2</p>
    <p>安装日期	‎2021/‎8/‎24</p>
    <p>操作系统内部版本	19045.3324</p>
   <p> 体验	Windows Feature Experience Pack 1000.19041.1000.0</p>
</details>

**Comment by ABA2396** [comment]
@moomiji 我想把这个惯性滚动给关了，hc:ScrollViewer支持自定义这玩意吗

**Comment by moomiji** [comment]
> @moomiji 我先把这个惯性滚动给关了，hc:ScrollViewer支持自定义这玩意吗

hc 是从 System.Windows.Controls.ScrollViewer 继承的
