### ISSUE TITLE
GUI:勾选碎石时，自动勾选的理智液（也许）也应为单次？

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#7751]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，既然碎石的设置是**一次性**的，那么自动勾选的理智液是否也应该为**一次性**的？

### 日志文件

无

### 截图

![截图_20231223122659](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/53437291/7f033b20-c2bc-4eff-b2a5-290b42239940)

**Comment by ABA2396** [comment]
等我睡醒了写（）
