### ISSUE TITLE
自动战斗-自动编队 闪灵识别错误

### ISSUE THREAD

**Issue by zerocak** [MaaAssistantArknights/MaaAssistantArknights#7752]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

对照我以火FC-EX-8的maa://31248自动战斗作业，自动编队时将华法琳识别成了闪灵并选择。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13758098/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13758099/gui.log)

### 截图

![MuMu12-20231223-133336.png](https://s11.ax1x.com/2023/12/23/pi7dAJg.png)

### 还有别的吗？

Mumu模拟器12
MAA v4.28.3

**Comment by zerocak** [comment]
![Uploading 1.png…]()

**Comment by zerocak** [comment]
[MuMu12-20231223-133336.png](https://s11.ax1x.com/2023/12/23/pi7dAJg.png)

**Comment by status102** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/dc4df1ff-65ce-4a67-8c6d-3cc6f39cc09a)

每个位置都出现了偏移，没想明白咋回事，再看看（

**Comment by zzyyyl** [comment]
滑动没停就截图了吧，换 maatouch 试试

**Comment by status102** [comment]
> 滑动没停就截图了吧，换 maatouch 试试

这几个都是排在最前面的，切换完职业应该不会向左边滑动吧，要滑也应该是向右滑
