### ISSUE TITLE
更新后无法启动

### ISSUE THREAD

**Issue by supermcclear** [MaaAssistantArknights/MaaAssistantArknights#7753]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

之前正常使用（一般周末刷体力药），今天更新后正常fighting，完成一次战斗后闪退，快捷方式也没了。点击应用程序无法加载 DLL“MaaCore.dll”: 找不到指定的模块。 在官网重下，如果覆盖源文件下载还是这个问题；重新放一个文件夹，说有病毒，然后自动把应用程序删了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13758128/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13758129/gui.log)

### 截图

![e212544dd1aac8d214628430b24c539](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137293351/016c6e81-4d19-4555-9bb1-f8d350cf45d6)

**Comment by ABA2396** [comment]
#6662
