### ISSUE TITLE
请问能增加在指定时间段抽卡的功能吗

### ISSUE THREAD

**Issue by EBHRIKEY** [MaaAssistantArknights/MaaAssistantArknights#7758]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

你们设计的自动抽卡很有创意❤️。但是能增加在指定时间段抽卡的功能吗？比如我想在凌晨1点抽卡 如果更新了定时抽卡的功能可以让我不用熬夜 。

### 有什么好的想法？

请问能增加在指定时间段抽卡的功能吗？给Maa跪了❤️😭

**Comment by EBHRIKEY** [comment]
顶

**Comment by ntgmc** [comment]
你好，你的提议很有意思，但是为什么你要在凌晨1点抽卡？
