### ISSUE TITLE
建议自动战斗增加保全刷章模式

### ISSUE THREAD

**Issue by ShooinXue** [MaaAssistantArknights/MaaAssistantArknights#7759]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

自动保全战斗的时候有时候需要一命通关拿蚀刻章。中途某一关卡失败就会无法获得本次的章，需要从头再开一局。但maa会反复打失败关卡，直至本次通关。

### 有什么好的想法？

增加一个保全蚀刻章可选项，如果勾选，本次保全某一关失败后自动重头开始，方便刷章。

**Comment by Saratoga-Official** [comment]
这个其实能解决，就是把保全作业的json下载下来，然后记事本打开把所有的"retry_times": 后面加的数字改成1，就能让maa失败结束战斗了，配合循环次数就能刷了

**Comment by ShooinXue** [comment]
> 这个其实能解决，就是把保全作业的json下载下来，然后记事本打开把所有的"retry_times": 后面加的数字改成0，就能让maa失败结束战斗了，配合循环次数就能刷了
> 
> 缺点是不能借助战，不然maa不会自动重新开始

好的好的，十分感谢，原来还有这么个字段！

**Comment by Constrat** [comment]
If the answer has been given.
CLOSE THE ISSUE
