### ISSUE TITLE
萨米肉鸽遇见[树篱之途 前行的林地]事件 自身抗干扰指数为0时卡死

### ISSUE THREAD

**Issue by yueming15** [MaaAssistantArknights/MaaAssistantArknights#7762]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽遇见（树篱之途 前行的林地事件） 自身抗干扰指数为0时卡死

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13759636/debug.zip)
18：42：43 出现的问题

### 截图

![F(U@TQ_PH0QYOE(@8@V1T$N](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/123758383/ec3db0a9-749d-4b9b-afe6-064db8ae345b)

### 还有别的吗？

使用MUMU模拟器12 
系统win10

**Comment by SherkeyXD** [comment]
Duplicate of #7549
