### ISSUE TITLE
Roguelike is not longer automated properly

### ISSUE THREAD

**Issue by Lysergic-Acid** [MaaAssistantArknights/MaaAssistantArknights#7766]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

The program no longer selects the "deep dive" button and remains in an endless loop of selecting units, exiting the current run, and restarting. 

### Log files

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13760716/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13760717/asst.log)

### Screenshots

![](https://i.imgur.com/DB5YXBN.png)

**Comment by whylorainer** [comment]
Still happening in Yostar-EN @ 4.28.6

**Comment by Constrat** [comment]
![Screenshot_2024 01 03_15 22 59 078](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/d5494e8a-9c4c-450c-b81c-5560318ad18c)
Can confirm they changed the interface @zzyyyl @Manicsteiner

**Comment by zzyyyl** [comment]
还真是改了 UI，#2719 那里的就是 Enter Castle ：）

**Comment by Constrat** [comment]
They love changing interfaces

**Comment by Manicsteiner** [comment]
JP server has not changed

**Comment by zzyyyl** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/62c5da55-4d8a-40f9-85b7-8137aebf25fb)
