### ISSUE TITLE
日服保全识别问题

### ISSUE THREAD

**Issue by Eric9877** [MaaAssistantArknights/MaaAssistantArknights#7767]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

日服保全一直在识别浊蒂的海嗣和鸿雪的打字机，无论是皮肤还是原皮都识别不了，导能原件能量扰动放大器和应急的绝缘水泥也不能识别，白金精二立绘换成精一立绘解决了
第3层选择导能原件的时候不能不能识别确认按钮，需要手动操作
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154685127/5a61fcc5-36bf-41c4-b4ac-c89b3441bd06)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13761364/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13761365/gui.log)
自动战斗从12-24 16:41开始，每一关都会复现

### 截图

![MuMu12-20231224-170314](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154685127/52555be0-77c9-4825-85d4-20131857d726)
![MuMu12-20231224-170625](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154685127/85709b04-5eab-4933-95b5-6a654a4662b0)
![MuMu12-20231224-171541](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154685127/83005f1e-4915-436e-b8e4-08683037996f)
![MuMu12-20231224-172702](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154685127/fae5958a-4719-417f-a53b-ae54084d4eb1)

### 还有别的吗？

MuMu模拟器版本 :  3.6.11.2438

运行环境
VT :  开启
Hyper-V :  关闭
网络环境检测 :  正常
以管理员运行方式 :  是
DirectX 11是否安装 :  是
防火墙 :  开启（建议关闭）

系统版本 :  Windows 10 64-bit Kernel 10.0.19045

模拟器设置
Root :  关闭
显卡渲染模式 :  Vulkan 模式（独家）
性能设置 :  4核/4GB
手机型号 :  HONOR V40
分辨率 :  1920 * 1080
高帧率 :  开启
后台保活 :  关闭

其它信息
其它版本信息 :  vm: 120.1.44.001 hyperv: 6.3.16.0 renderer: 0.0.135.0
Vendor :  NetEase
OpenGL Renderer :  MuMu GL (Vulkan 1.3.242 NVIDIA GeForce GTX 1660 Ti 536.40 _A_)
OpenGL Version :  OpenGL ES 3.2

**Comment by Constrat** [comment]
@Manicsteiner Do you want to try XD?

**Comment by Manicsteiner** [comment]
line 8580, 8745, 8915 斯卡蒂的海嗣名字太长，没识别完整
line 4283, 4304 水泥名字太长，没识别完整
打字机没有找到
白金和便携式医疗设备看起来一切正常，如果是换个皮肤就认出来了的话，看看 MAA\cache\avatars 目录下的头像缩略图，如果图和名称对不上就删掉
 > 第3层选择导能原件的时候不能不能识别确认按钮，需要手动操作
已知问题，如果是从前三层连贯打过来就会只认”選択を確認“的前四个字，如果在这个地方暂停任务重新开始就能认出全部五个字，很迷惑

**Comment by Constrat** [comment]
> line 8580, 8745, 8915 Skaty's heir's name is too long to be fully recognized

I remember I changed to OCR range box for YostarEN to easily read <= 30 chars names.

**Comment by Eric9877** [comment]
> line 8580, 8745, 8915 斯卡蒂的海嗣名字太长，没识别完整 line 4283, 4304 水泥名字太长，没识别完整 打字机没有找到 白金和便携式医疗设备看起来一切正常，如果是换个皮肤就认出来了的话，看看 MAA\cache\avatars 目录下的头像缩略图，如果图和名称对不上就删掉

查看了下白金是未精二头像，能量扰动放大器识别成了凛冬，绝缘水泥识别成了年，打字机貌似识别成了梓兰，我先删掉再运行看看
![白金](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154685127/d76976ee-86af-4c1e-b989-ddafb398a125)
![凛冬](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154685127/4e0e2821-61f9-40ee-8c63-7fc992e5fcb9)
![年](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154685127/b134f998-09d2-4823-af4d-6db45ee38fb9)
![梓兰](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154685127/00f18f91-b68b-41cc-8814-306f5cd23627)

**Comment by Eric9877** [comment]
> > line 8580, 8745, 8915 斯卡蒂的海嗣名字太长，没识别完整 line 4283, 4304 水泥名字太长，没识别完整 打字机没有找到 白金和便携式医疗设备看起来一切正常，如果是换个皮肤就认出来了的话，看看 MAA\cache\avatars 目录下的头像缩略图，如果图和名称对不上就删掉
> 
> 查看了下白金是未精二头像，能量扰动放大器识别成了凛冬，绝缘水泥识别成了年，打字机貌似识别成了梓兰，我先删掉再运行看看 ![白金](https://private-user-images.githubusercontent.com/154685127/292676250-d76976ee-86af-4c1e-b989-ddafb398a125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MzA1MDIsIm5iZiI6MTcwMzQzMDIwMiwicGF0aCI6Ii8xNTQ2ODUxMjcvMjkyNjc2MjUwLWQ3Njk3NmVlLTg2YWYtNGMxZS1iOTg5LWRkYWZiMzk4YTEyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQxNTAzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Mjc3ZTkxNWY3ZmZjN2U5ZGJkMDQ2OWQ1ZDhmMmY4N2U0N2MwODBhNDZlMDEzYmNmYTllOGIxM2ZiMjQ5MDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s6ZyMeWZKSKf0emB9EG19wVNcOAyUUbMOpiJJmo9VRI) ![凛冬](https://private-user-images.githubusercontent.com/154685127/292676409-4e0e2821-61f9-40ee-8c63-7fc992e5fcb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MzA1MDIsIm5iZiI6MTcwMzQzMDIwMiwicGF0aCI6Ii8xNTQ2ODUxMjcvMjkyNjc2NDA5LTRlMGUyODIxLTYxZjktNDBlZS04YzYzLTdmYzk5MmU1ZmNiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQxNTAzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTczOGI4ODQzM2NlYzM3NzkzMjI1Yjk4NWFmZjc5YjhiYTEyNjYwNzAxNzJkNmZlNzU5YzNmNzU3NTYyNjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2AtCTcixD5FTDlPhEruTPutF-j34GvUNu0Zr6DXA2RE) ![年](https://private-user-images.githubusercontent.com/154685127/292676416-b134f998-09d2-4823-af4d-6db45ee38fb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MzA1MDIsIm5iZiI6MTcwMzQzMDIwMiwicGF0aCI6Ii8xNTQ2ODUxMjcvMjkyNjc2NDE2LWIxMzRmOTk4LTA5ZDItNDgyMy1hZjRkLTZkYjQ1ZWUzOGZiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQxNTAzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmUyYWI1MDA0YzMxMDIwYmQ1MmExY2Q3YmVlZmJiNWQwNDFjZGFmOTNlYThmZjJiOGE4NWM5MzUxMTQ2MzgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FB13ptWIlla56NNiRPS25YlAyCuDeOQ2Mivw6RfTy2s) ![梓兰](https://private-user-images.githubusercontent.com/154685127/292676455-00f18f91-b68b-41cc-8814-306f5cd23627.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MzA1MDIsIm5iZiI6MTcwMzQzMDIwMiwicGF0aCI6Ii8xNTQ2ODUxMjcvMjkyNjc2NDU1LTAwZjE4ZjkxLWI2OGItNDFjYy04ODE0LTMwNmY1Y2QyMzYyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQxNTAzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWUxODlmOGMzMDY3ZjQwMjdiMDYwYmU0OWFhOTdhODMxN2IwODllYWZkMzMzMzc1MzJiMGMwYjA4NmVkMWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7fh3sEZagjZk0mqXHooh_CkfZ5EUhVfC1NbIxmty03Q)

删掉之后除了海嗣以外绝缘水泥，能量扰动放大器和打字机还是无法识别
![MuMu12-20231224-233535](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154685127/b8563e47-6578-4916-aa19-3ea6fd7046b1)

**Comment by Constrat** [comment]
It's avatar related. The issue is with the complexity of the name. The linked PR should fix this.

**Comment by Manicsteiner** [comment]
[2023-12-25 00:14:22.648][TRC][Px52ac][Tx2ae8] asst::WordOcr [{ [夕イプライ夕ー|: [ 0, 0, 172, 25 ], score: 0.841421 }] by OCR Rec , cost 23 ms
[2023-12-25 00:14:22.654][TRC][Px52ac][Tx2ae8] Proced [{ [夕イプライ夕ー|: [ 9, 110, 172, 25 ], score: 0.841421 }]
[2023-12-25 00:14:22.654][WRN][Px52ac][Tx2ae8] ocr with preprocess got a invalid name, try to use detect model
[2023-12-25 00:14:22.692][TRC][Px52ac][Tx2ae8] asst::WordOcr [{ [タイプライター|: [ 6, 6, 174, 21 ], score: 0.881145 }] by OCR Pipeline , cost 34 ms
[2023-12-25 00:14:22.702][TRC][Px52ac][Tx2ae8] Proced [{ [タイプライター|: [ 6, 111, 174, 21 ], score: 0.881145 }]
打字机的识别也太离谱了……
