### ISSUE TITLE
基建 排班 會一直重復選取 拉動

### ISSUE THREAD

**Issue by EROTCZ** [MaaAssistantArknights/MaaAssistantArknights#7769]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

每次基建排班 只要輪到 多羅西 白面鴞 槐琥
會一直重復  選取>拉動畫面>選取>拉動畫面  

至少3~4次 才確認

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13761533/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13761537/asst.log)

### 截图

![螢幕擷取畫面 2023-12-24 183803](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153876121/3f25a26e-c9ad-48e8-9170-a32c65d92f5d)

### 还有别的吗？

模擬器BlusStacks 5.12.115.2304 P64
WIN 11

**Comment by ABA2396** [comment]
为啥这里白没识别到（）
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/0842698d-a084-4be4-9ec2-5f3f60bb0a04)

**Comment by ABA2396** [comment]
@zzyyyl 这玩意咋整, "白?" 吗

**Comment by zzyyyl** [comment]
> @zzyyyl 这玩意咋整, "白?" 吗

^面鸮$

**Comment by ABA2396** [comment]
> > @zzyyyl 这玩意咋整, "白?" 吗
> 
> ^面鸮$

问题是这玩意是繁中的）单独写两个啊
