### ISSUE TITLE
希望能添加待办事项设定功能

### ISSUE THREAD

**Issue by frospear** [MaaAssistantArknights/MaaAssistantArknights#777]
希望能加个todo。举个简单的例子，设定10次rogue后进行一次资源刷取。

**Comment by ntgmc** [comment]
现版本可以通过设置开始探索次数（例如10次）
![image](https://user-images.githubusercontent.com/74061867/201552485-dd0bb66f-15f5-4944-b2ce-fb84462d291b.png)
后maa自动停止，并通过设置定时启动来执行该操作
