### ISSUE TITLE
自动换班宿舍自动填充错误

### ISSUE THREAD

**Issue by H-XZ** [MaaAssistantArknights/MaaAssistantArknights#7770]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

排班表设定最后一个宿舍保留爱丽丝，其余自动填充。（Plan: Day2 1）
[output.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13761555/output.json)
进行宿舍4排班前宿舍内有爱丽丝及另一名满心情干员，排班后仅剩余三名干员且不存在爱丽丝

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13761559/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13761560/gui.log)
最后一段，，MAA的最后一次执行

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/118260498/8b275f5a-f2d1-4637-93f0-828a12561ac8)

### 还有别的吗？

#7101 #7258 存在相同问题，但没有解决

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/cc4173af-f91a-4b88-91bc-107b1209244d)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/a1903b8d-4e7a-4c1b-a600-3330147fbfb7)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/4e2036db-1a1a-4203-b39f-47e2ea92a6e9)
