### ISSUE TITLE
保全自动战斗时CPU占用异常

### ISSUE THREAD

**Issue by Lee-Juntong** [MaaAssistantArknights/MaaAssistantArknights#7774]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA尝试尽可能多的占用CPU，这是多个版本使用保全自动战斗以来首次出现问题
当一个MAA占用的少时另一个会立刻多占用，使得CPU占用始终在100%附近
使用了mumu模拟器双开保全，一个官服一个B服，模拟器均为默认设置

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13762267/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13762270/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13762272/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13762273/asst.zip)
时间是北京时间晚上11点40左右
前俩是一组 后俩是一组

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55589340/ed873234-2199-4f4e-a107-63da1c8663ab)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55589340/cf933f6c-5c32-4b35-9964-3a8eb61173ff)

### 还有别的吗？

使用的作业均为 塔山农业实验平台-兼容应急-澄闪提丰核
系统为win11专业版 22H2
CPU为i9-13900H
GPU为RTX4060

**Comment by Lee-Juntong** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55589340/113bbf40-7741-4afb-b16b-e43c96a54492)
当关闭其中一个MAA时，另一个仍然会尝试占用所有CPU资源

**Comment by Lee-Juntong** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55589340/5302a825-d97c-4675-9116-4c53fdf1b01f)
均停止自动战斗 CPU占用回归正常

**Comment by LHC-mo** [comment]
这自动战斗很消耗cpu资源的 所以不算bug 要优化费时费力

**Comment by scqy2000** [comment]
v4.28.7发现相同问题

**Comment by ABA2396** [comment]
检查下是不是开着内核隔离和hyperv，可以的关掉再试试看
