### ISSUE TITLE
ADB连接失败

### ISSUE THREAD

**Issue by yukizasa** [MaaAssistantArknights/MaaAssistantArknights#7775]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

大约2023年12月初开始发现MAA被Windows Defender识别为Trojan杀掉，多次重新下载MAA后仍发生，在Windows Defender的Exclusion中把MAA文件夹添加后不再发生同样的问题。

但是我发现大概同时间出现了MAA无法唤醒MUMU12（目前为V.3.6.12 2454）的问题，在Github上看到了同样的Issue报告，但是点开后发现结论是360手机助手的问题，我没有安装过。

尝试过重新安装MUMU模拟器和MAA，都没有效果，手动尝试连接adb.exe会出现10061错误，asst.log中也有。

管理员运行MAA没有效果，替换adb也没有效果。

目前只能在手动开启MUMU12模拟器后运行MAA才能正常运行。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13762304/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13762305/gui.log)

### 截图

![adb issue](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75836176/1cbe6241-7cf6-48ae-a69d-3f1c8be210f0)
![MAA settings](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75836176/713bbdcb-be37-4fa5-9ebc-f047af734eaf)
![MUMU settings](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75836176/c7d55fce-7e3a-46f9-abcb-f0ad529f783d)

### 还有别的吗？

Edition	Windows 10 Home
Version	22H2
Installed on	‎06/‎11/‎2020
OS build	19045.3803
Experience	Windows Feature Experience Pack 1000.19053.1000.0

**Comment by ABA2396** [comment]
adb.exe: device '127.0.0.1:16384' not found 你确定你的模拟器端口是这个？如果是多开过的模拟器的话后面的端口是不一样的，可以在mumu的诊断信息里面看到具体实例的端口号

**Comment by yukizasa** [comment]
> ~adb.exe: device '127.0.0.1:16384' not found 你确定你的模拟器端口是这个？如果是多开过的模拟器的话后面的端口是不一样的，可以在mumu的诊断信息里面看到具体实例的端口号~
> 
> > 但是我发现大概同时间出现了MAA无法唤醒MUMU12
> 
> ![image](https://private-user-images.githubusercontent.com/99072975/292713963-0d780740-cc05-446b-ac4f-cee165a83c62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Mjc2ODEsIm5iZiI6MTcwMzUyNzM4MSwicGF0aCI6Ii85OTA3Mjk3NS8yOTI3MTM5NjMtMGQ3ODA3NDAtY2MwNS00NDZiLWFjNGYtY2VlMTY1YTgzYzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDE4MDMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNmYwM2I0MDc4NTg2MzJmNDczYWU1ZGVjYjMwODRkNTNlMmQwMzdiMGQ0NDQxNDIzODZjMjM5NTkzNTQxNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Azp3glwDY6z5eUdEBZZo5155e7VAKGYFAW2_abC_ig)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13766935/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13766936/gui.log)
![ADB option ticked](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75836176/d31b0f9c-1adb-49a3-8ebb-03c11778da91)

这个选项我忘了说，勾选与否是同样的问题。

**Comment by zzyyyl** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/820d2623-a515-4e0c-9c30-955f837b01f1)
模拟器路径填对了么

**Comment by yukizasa** [comment]
> ![image](https://private-user-images.githubusercontent.com/74587068/292789211-820d2623-a515-4e0c-9c30-955f837b01f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDA4NzEsIm5iZiI6MTcwMzYwMDU3MSwicGF0aCI6Ii83NDU4NzA2OC8yOTI3ODkyMTEtODIwZDI2MjMtYTUxNS00ZTBjLTljMzAtOTU1ZjgzN2IwMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE0MjI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMjFhYjJmOWNhZjg1NjcxZjVkYTA3NDFkMDEyZmViNTEwNGEzMDQyYzc3OTQ4ZTRiNjAxNzI4N2I1NjUyYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qYSET0ncndN5SHKM4_0UvDvGFul6C2W4lcoFr_Z_80c) 模拟器路径填对了么

是正确的

**Comment by ABA2396** [comment]
现在模拟器启动失败好像没有日志，之后得加下，看看你路径填了啥

**Comment by Cotangen** [comment]
开机直接使用MAA时是正常的，当打开UU加速器，加速其他游戏时，ADB连接就会失败

**Comment by yukizasa** [comment]
> 现在模拟器启动失败好像没有日志，之后得加下，看看你路径填了啥

往上第三层楼，我在那里添加了日志文件

**Comment by ABA2396** [comment]
> > 现在模拟器启动失败好像没有日志，之后得加下，看看你路径填了啥
> 
> 往上第三层楼，我在那里添加了日志文件

不是，我是说启动失败没有添加日志，所以日志里没有有用的信息，所以要看一下你模拟器路径填的是什么，文件管理器里直接输入那个路径能不能开启模拟器

**Comment by yukizasa** [comment]
非常抱歉耽误大家时间了，我发现是模拟器路径错了，可能是被Microsoft Defener杀了之后变了。
