### ISSUE TITLE
定时任务结束后自动切换回Default配置，以及刷理智关卡可以选择是否为全局配置

### ISSUE THREAD

**Issue by H-XZ** [MaaAssistantArknights/MaaAssistantArknights#7777]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

设置了每天三次定时为特定配置，但其他时间如果有其他操作想要自动完成（如刷公招，清肉鸽等）必须手动切换回default以免修改定时配置，有时忘记了就会无法正常换班，额外消耗之类（定时排班，其他时间会把排班关掉）

以及刷理智模块每次想改需求需要把四个配置全换一遍，很麻烦有时还会忘（然后它就自动刷了上次关卡，10次ex8……）

### 有什么好的想法？

添加一个选项，勾选后每次定时任务完成后自动切换回Default配置，以及增加当前关卡设置为全局配置的选项

**Comment by status102** [comment]
可以试试单开一个MAA，并且在启动参数指定启动的配置为Default
ex8没奖励会自动停的吧，为了这个把刷理智改成全局感觉不好（

**Comment by ABA2396** [comment]
ex照理来说打一遍就停了，如果没停发个日志）

**Comment by H-XZ** [comment]
> 可以试试单开一个MAA，并且在启动参数指定启动的配置为Default ex8没奖励会自动停的吧，为了这个把刷理智改成全局感觉不好（

那应该是我记错了（）单开一个是指再复制一个文件夹吗

**Comment by status102** [comment]
> 单开一个是指再复制一个文件夹吗

不是，还是同一个文件夹的，可以用快捷方式来指定
