### ISSUE TITLE
maa经常无故消失

### ISSUE THREAD

**Issue by Ywzoom** [MaaAssistantArknights/MaaAssistantArknights#7778]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

最近启动maa之后经常会自己消失，先开始以为是安全软件自行清理了，将maa相关文件夹放进白名单后仍未见改善，每次出现如上情况只能删除重装maa

### 日志文件

问题出现在2023/12/25 11.20左右
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13763706/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121286238/058ec59d-9f88-426a-9da8-1a8a9c6908a7)

### 还有别的吗？

用的mumu12模拟器

**Comment by Ywzoom** [comment]
还有雷电模拟器，上传的gui.log是雷电模拟器使用的maa上的

**Comment by ABA2396** [comment]
#6662

**Comment by ABA2396** [comment]
再加下wd的文件夹白名单

**Comment by Ywzoom** [comment]
> 再加下wd的文件夹白名单

我是用的火绒，在火绒里加了白名单，找不到windowsdefender的白名单在哪里
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121286238/a4bf67fa-509d-44ee-bf9d-7179f21934c0)

**Comment by ABA2396** [comment]
感觉是Windows的问题，说说关了其实后台还在跑，先把火绒关了开起来原来的，加完白名单再开火绒
