### ISSUE TITLE
Bilibili服无法完成后“退出明日方舟”

### ISSUE THREAD

**Issue by Yaklo** [MaaAssistantArknights/MaaAssistantArknights#7779]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在完成所有任务后无法退出游戏，B服

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13763742/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13763744/gui.log)

**Comment by ABA2396** [comment]
你是一个模拟器里同时装了两个吗

**Comment by Yaklo** [comment]
> 你是一个模拟器里同时装了两个吗
没，有两个模拟器都只装了一个游戏，在maa里有做配置切换，时间也间隔的很长不会冲突
![Snipaste_2023-12-26_10-40-32](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50908861/2766f468-1474-41af-ae8b-a662609b5025)
![Snipaste_2023-12-26_10-40-43](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50908861/e3e462c4-2b31-4451-87f8-e06fec09b749)

**Comment by ABA2396** [comment]
摇人看看）
@zzyyyl 这个包名匹配的时候没匹配上后面的.bilibili

**Comment by HDAnzz** [comment]
一样的问题，我是蓝叠模拟器国际版5.20.10.1003安卓11 64位，但是是一个实例里面装了两个服的明日方舟，请问这个问题会解决吗？
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14135713/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14135714/gui.log)

**Comment by Rbqwow** [comment]
#9352 fixed
