### ISSUE TITLE
自动战斗，子弹时间等待期间，在下一步前点击暂停并取消子弹时间

### ISSUE THREAD

**Issue by dogsshift** [MaaAssistantArknights/MaaAssistantArknights#7780]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA自动战斗时，进入子弹时间后，在该进行下一步操作（开技能、放龙都有）时，双击暂停按键后直接退出子弹时间
还出现过卡在子弹时间后的下一步，不操作的情况
双击暂停在局内非子弹时间步骤中间也出现过，MAA仅双击暂停，没有点击红色再部署小龙或其他干员进行识别

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13764028/asst.log)
[Uploading gui.log…]()
时间点[2023-12-25 12:43]往后，上传的日志文件使用的模拟器为蓝叠国际版

### 还有别的吗？

模拟器：蓝叠国际版5.12.115.1001+Mumu12，两者皆出现过该情况
上传的日志文件使用的模拟器为蓝叠国际版
使用作业：maa://31277 令单人FC-6

**Comment by dogsshift** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13764055/gui.log)
未上传成功的gui.log

**Comment by status102** [comment]
#8337 fixed
