### ISSUE TITLE
保全派驻异常

### ISSUE THREAD

**Issue by octshee** [MaaAssistantArknights/MaaAssistantArknights#7782]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动战斗中选择了自带的保全派驻作业，开始后显示截图中的内容，然后就显示完成任务了 时间点为20:04左右

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13765970/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13765971/gui.log)

### 截图

![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154809466/f634c6ef-00dc-409f-940a-ca86e621b06b)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154809466/c412a798-051a-4775-b903-59b7b76e6a1b)

### 还有别的吗？

mumu模拟器12，win11

**Comment by Saratoga-Official** [comment]
你这个问题目前解决方法只能是重装maa

**Comment by octshee** [comment]
重装之后就解决了，谢谢谢谢！
