### ISSUE TITLE
萨米肉鸽存钱，分数结算时MAA本体有概率闪退

### ISSUE THREAD

**Issue by IberianCabbage** [MaaAssistantArknights/MaaAssistantArknights#7785]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如标题，晚上挂MAA刷钱，半夜起来看了三次，三次MAA都没有在正常运行。通过看log确认maa在12-25 23:07:51和12-26 04:58:06时发生闪退，这两次闪退的时候游戏都停留在结算界面并且MAA没有输出结算分数相关信息，推测是计算结算分数的时候有概率闪退？
此外，log中12-26 01:59:37的时候MAA也停止运行了，但不是闪退，和本issue想重点反馈的问题应该不一致

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13767474/gui.log)
[asst.log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13767476/asst.log.zip)

### 还有别的吗？

模拟器：mumu12 V3.6.11（2438），系统：win10，未启用Windows Defender

**Comment by IberianCabbage** [comment]
补充一下截图，看电脑发现MAA闪退的时候模拟器每次都是停留在这个位置，今天白天挂机又成功闪退了一次
![QQ截图20231226142703](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96757630/08aa5817-182d-4363-8af1-8b053ac9b919)

**Comment by status102** [comment]
> 补充一下截图，看电脑发现MAA闪退的时候模拟器每次都是停留在这个位置，今天白天挂机又成功闪退了一次

尝试一下最新的内测版是否还会复现（不过刷钱模式本来不应该输出肉鸽结算信息

**Comment by ABA2396** [comment]
> > 补充一下截图，看电脑发现MAA闪退的时候模拟器每次都是停留在这个位置，今天白天挂机又成功闪退了一次
> 
> 尝试一下最新的内测版是否还会复现（不过刷钱模式本来不应该输出肉鸽结算信息，要刷等级模式才有可能复现了

之前看到个说第一层没商店会继续打下去，会不会是这个原因

**Comment by status102** [comment]
> 不对啊怎么打两把就寄了）

log显示寄在结算，估计之前改结算ocr替换改出bug了，概率触发就很迷惑

**Comment by gracesong617** [comment]
遇到了相同的问题，我用的是PlayCover3.0.0.maa.4 (4), 系统macOS12.5
经常会出现游戏卡在肉鸽结算画面上，maa自动关闭
