### ISSUE TITLE
萨米肉鸽前行的林地卡死

### ISSUE THREAD

**Issue by Maius-17** [MaaAssistantArknights/MaaAssistantArknights#7789]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

到了事件前行林地后卡在选择不动，已多次发生
2023-12-26 12:54:44.491
2023-12-26 14:45:24.320
2023-12-26 16:53:36.181
均卡住

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13770830/debug.zip)

### 截图

![{4E914F9F-C7ED-49a3-97FD-3477A54F8654}](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/47728722/49fa4c5d-64e6-4d82-a4dc-f2e5ea29ad2e)

### 还有别的吗？

模拟器：方舟专版 mumu 3.6.10 (2423)

**Comment by LHC-mo** [comment]
确定存在 我也遇到了 估计一直在尝试点击进入 当抗干扰值不够时则卡住

**Comment by 0AHA0** [comment]
+1+1+1+1+1+1

**Comment by ABA2396** [comment]
cc @zzyyyl  ~~抗干扰值检测什么时候才能有啊）~~

**Comment by SherkeyXD** [comment]
~~抗干扰检测也不难写吧~~
