### ISSUE TITLE
屏幕熄灭后肉鸽挂机子弹时间不退出

### ISSUE THREAD

**Issue by Zhang-Jia-Qi** [MaaAssistantArknights/MaaAssistantArknights#7790]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

屏幕熄灭（不是睡眠）后，MAA挂机肉鸽无法退出子弹时间，会卡死在一个干员的子弹时间页面，屏幕重新亮起后也不会恢复，帮助maa手动退出子弹时间后恢复正常

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13773219/asst.zip)

**Comment by 610807421** [comment]
个人经验这个和屏幕熄灭没关系，应该是识别错误或者点击误差导致的。我从不熄屏也会遇到。感觉是纯随机事件

**Comment by YinChenming** [comment]
我哪怕没有熄屏也会出现这种情况，和熄屏无关。
