### ISSUE TITLE
在使用网易UU加速器的时候，原本正常连接并运行的MAA会被断开连接。（模拟器是蓝叠模拟器）

### ISSUE THREAD

**Issue by Cotangen** [MaaAssistantArknights/MaaAssistantArknights#7791]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

当我使用MAA，已经连接上模拟器并运行时，此时使用UU加速器加速STEAM社区，或其他游戏，MAA会直接断开与模拟器的连接

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13774226/debug.zip)
模拟器在12-27 8：03前都是正常运行，8：03启动UU加速器，模拟器自动断开，关闭UU加速器仍然无法正常使用，只有重启电脑才能恢复

### 还有别的吗？

使用的模拟器是蓝叠模拟器

**Comment by ABA2396** [comment]
没办法，你开了uu之后得去任务管理器里重启adb和模拟器，要么就等uu连完了之后再连模拟器，不然开关都有影响
