### ISSUE TITLE
EN服 无法自动吃大理智药

### ISSUE THREAD

**Issue by lirao** [MaaAssistantArknights/MaaAssistantArknights#7793]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

之前在https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/7765#issuecomment-1868422361 这里也顺便提到过这个问题不过这次应该是最新版
设置了“吃理智药”，可是只吃了小药，大药就卡住在这个截图位置。
如果手动点击了吃药，然后点击maa的停止，gui的log会多出一行吃了理智药（可是这是我手动吃的和maa没关系啊

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13775687/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13775695/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6883412/fdd22632-bd5a-4df1-b2bd-871502bf01b6)
![Screenshot_2023 12 27_13 22 30 967](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6883412/120cc552-4808-421b-8e25-83513cbf8d18)

**Comment by lirao** [comment]
如果手动点击了吃药然后停止maa就会出现这样
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6883412/9bccd881-8ecc-4a70-aee9-e7453ea3c1a6)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13775712/asst.log)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/07b86017-687b-4afd-a55c-ea2021daebe9)
鼠标放上去看看提示

**Comment by lirao** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/292974263-07b86017-687b-4afd-a55c-ea2021daebe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NTEyMDYsIm5iZiI6MTcwMzk1MDkwNiwicGF0aCI6Ii85OTA3Mjk3NS8yOTI5NzQyNjMtMDdiODYwMTctNjg3Yi00YWZkLWE1NWMtZWEyMDIxZGFlYmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDE1NDE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxODUyMDU3MjZlNzA5YWIzMTZkNDAxMzI0ZTZiZDJiMDQzZjNkYzZlZTE2NmVjYmI0MWE5MmI1OTVlN2MzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EZhVRASjO5wYGytOX0yVQ4x57oMdqvbm_NZRdUryWnQ) 鼠标放上去看看提示

你要不看看实际等了多长时间？

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/ff2a2ab5-a819-47ea-9204-a30ad34b51a7)
@Constrat Do you have a chance to look at this roi range?

**Comment by Constrat** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/339065c4-4d9e-4166-bc8f-0dc34ac1778b)
@ABA2396 Definitely not enough

**Comment by ABA2396** [comment]
> ![image](https://private-user-images.githubusercontent.com/56174894/293470107-339065c4-4d9e-4166-bc8f-0dc34ac1778b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NTM4MTUsIm5iZiI6MTcwMzk1MzUxNSwicGF0aCI6Ii81NjE3NDg5NC8yOTM0NzAxMDctMzM5MDY1YzQtNGQ5ZS00MTY2LWJjOGYtMGRjMzRhYzE3NzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDE2MjUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYzEyM2IwMWQ4ZTBhYThkMGExMjdlNjAwNjAxYjBlOTBkOGZkYzdhN2I2MDkwNWY2YzRmMzk5MGU1MGMwNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OHDAsej0Q0yDsFmER9fGeK8wBhb0DH0mMu44aW4PYJY) @ABA2396 Definitely not enough. Unless you just want the "minute". The problem is, as you can see, with specific numbers (probably 2 3 5 7 8 9, it covers the seconds)

Maybe we have to come up with a compromise. It's late. We'll talk about it in the group tomorrow.

**Comment by Constrat** [comment]
(A good ROI can be `50, 376, 245, 40`). But this will also get the numbers that may be "hidden"

**Comment by status102** [comment]
> (A good ROI can be `50, 376, 245, 40`). But this will also get the numbers that may be "hidden". 

could we ignore the last number and wait 10 more seconds for it?

**Comment by Constrat** [comment]
@ABA2396 any updates?

**Comment by ABA2396** [comment]
> @ABA2396 any updates?

Now there are two ways to say this, one is `n:??` as `n:59`, `n:m?` as `n:m9`, and the other is to take a screenshot every few seconds and wait until the first bit changes, but this can be a bit cumbersome

**Comment by Constrat** [comment]
First option is bit a less refined / precise but it definitely does the job.
