### ISSUE TITLE
肉鸽能否新增开局刷指定干员精二

### ISSUE THREAD

**Issue by nanmingxwx** [MaaAssistantArknights/MaaAssistantArknights#7795]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

职业分队开局概率出现精二，每次重开都要等一分钟，能否自动刷指定的精二干员，然后再自己玩

**Comment by SherkeyXD** [comment]
现在的烧开水模式就可以刷精二开局了，如果想只刷精二的话等 #7795 合了就行

**Comment by nanmingxwx** [comment]
烧开水要到第三层，开局也就是多个选项，不给招募券的话很难精二。
职业分队刷精二只要重开就行了，想拿精二自己打

**Comment by SherkeyXD** [comment]
那就等 #7705（
那个合了之后就能只刷精二了
