### ISSUE TITLE
肉鸽在干扰指数为0时在密境林地卡住

### ISSUE THREAD

**Issue by NekoVicky** [MaaAssistantArknights/MaaAssistantArknights#7799]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

干扰指数为0
应该是MAA要优先选使用干扰指数，次选润

### 日志文件

[Maa alpha.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13777377/Maa.alpha.zip)

### 截图

![1703669497073](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40619465/037c6ac4-0148-4f1e-b57e-fa8d97625e78)

**Comment by ABA2396** [comment]
#7789

**Comment by status102** [comment]
Duplicate of #7789
