### ISSUE TITLE
[Feature] 萨米肉鸽增加对抗干扰指数的检测

### ISSUE THREAD

**Issue by SherkeyXD** [MaaAssistantArknights/MaaAssistantArknights#7800]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前在需要使用抗干扰点数，而抗干扰点数为 0 时必定会引起卡死

包括但不限于：
+ 不期而遇选项
+ 希望的角落选项
+ 竖向节点

### Releated
+ #7549
+ #7789

### 有什么好的想法？

做一个抗干扰指数识别 或是至少增加一个多次尝试失败之后的处理 这样卡着不是办法

### 其他内容

进阶一点，是否 希望/源石锭/目标生命值/目标生命上限 也需要这样的识别呢

**Comment by LHC-mo** [comment]
这次bug感觉是肉鸽逻辑由原来的保守变成过于激进导致 更新公告有个 Hortus de Escapismo navigation 不知道是不是这个更新导致的寻路激进

**Comment by Manicsteiner** [comment]
> 这次bug感觉是肉鸽逻辑由原来的保守变成过于激进导致 更新公告有个 Hortus de Escapismo navigation 不知道是不是这个更新导致的寻路激进

那不是空想花庭的导航吗……

**Comment by zzyyyl** [comment]
肉鸽策略很久前就更新了，只不过之前因为层名识别 bug 一直没正常工作：）
