### ISSUE TITLE
萨米肉鸽每探索一次，就会放弃探索一次的bug

### ISSUE THREAD

**Issue by WQhuanm** [MaaAssistantArknights/MaaAssistantArknights#7805]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![无标题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111880052/cef54fac-a747-4c50-85c2-96b0c0fd5a03)

如图，产生的原因是每次探索时，脚本都会选择自然探索，但是这次探索完后，他下一次难度会直接拉满到15，选完干员，然后又结束探索，重新选择自然探索？？？！！！

我的配置如下：
![无标题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111880052/98618aa3-a135-406b-9a3f-e26bf5edad9a)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13783062/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13783064/gui.log)

### 还有别的吗？

win10，夜神模拟器

**Comment by ABA2396** [comment]
肉鸽策略选的啥

**Comment by WQhuanm** [comment]
> 肉鸽策略选的啥

如下面的图，烧热水

**Comment by ABA2396** [comment]
烧热水不就是低层刷到第三层然后去高层看有没有热水瓶，没有就继续刷吗

**Comment by WQhuanm** [comment]
@ABA2396 

所以我想要热水，就应该限定他次数为奇数次？不然我每次自己玩的时候都没有热水？（毕竟他探寻后立刻放弃探索）

**Comment by ABA2396** [comment]
应该是没刷到热水才会放弃啊？要么是没过第三层，要么是开局给的藏品里没有加希望的，所以重新刷

**Comment by WQhuanm** [comment]
真的我盯了好多次了，刷过好多次热水或者希望+2，但是都是退出了。
（再说我使用maa到目前为止打那么多局肉鸽，每次都是打一次放弃一次。总不可能一次热水/希望都刷不到吧，这概率...)

**Comment by WQhuanm** [comment]
@ABA2396 [我把视频录下来了，你可以看看

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111880052/e3f8ceb9-a79e-41e1-8d9c-68598bd9ef11

**Comment by Lancarus** [comment]
没问题啊，烧完开水发现没凹到精二，重新开始

**Comment by WQhuanm** [comment]
不好意思，我理解错那个凸的意思了（以为是当前对局优先精二谁）（捂脸）
