### ISSUE TITLE
12/28更新后刷理智无法导航至FC关卡

### ISSUE THREAD

**Issue by SUPERDAIDAI007** [MaaAssistantArknights/MaaAssistantArknights#7807]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

12/28更新后，无法导航至FC-7

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13785625/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13785626/gui.log)

**Comment by lewispumpkin** [comment]
遇到了同样的问题，MAA界面显示“任务出错：fight“，游戏内的情况是点进作战界面然后就没有后续操作了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/48039629/33fed2bd-6fcf-4505-a38f-0255e80c5916)

**Comment by lpowo** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113409320/39711d9b-f0e2-4ce8-9e58-fe5424e3b122)

**Comment by ABA2396** [comment]
6b35a9ced0ee6d53e2088e150d40631a3f69c471 fixed
