### ISSUE TITLE
12/28萨米新关卡识别错误

### ISSUE THREAD

**Issue by Chitaoji** [MaaAssistantArknights/MaaAssistantArknights#7808]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

12/28肉鸽更新以后，在萨米肉鸽烧开水，遇到新关卡时报错`关卡识别错误`，看到没有这个issue就提了

### 日志文件

问题出现时间：2023-12-28 22:34:17.858
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13787343/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13787344/gui.log)

**Comment by SherkeyXD** [comment]
由 #7818 统一追踪
