### ISSUE TITLE
萨米肉鸽存钱放弃之后会点错导致无法开启下一轮

### ISSUE THREAD

**Issue by Mrzcpf** [MaaAssistantArknights/MaaAssistantArknights#7809]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在一轮游戏存钱结束后，脚本会在商店退出该轮，并停在如图片这个位置，且下一次点击会点到“继续探索”区域，之后快速退出回到这个界面之后循环上述流程。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13787361/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13787363/gui.log)

### 截图

![QQ截图20231228224605](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/85926600/7cc1dcbd-9eee-4c50-a454-5e86f45ca1e7)
![QQ截图20231228225038](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/85926600/dc099a05-4d67-49a5-89c4-755111c9e4f8)

### 还有别的吗？

mumu12

**Comment by Mrzcpf** [comment]
![QQ截图20231228224605](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/85926600/16b39722-064f-464f-9ef7-8921c88fddae)

**Comment by SherkeyXD** [comment]
试试换回之前的背景 看看会不会有问题

**Comment by WQhuanm** [comment]
@SherkeyXD  我也是遇到一样的问题，版本更新后一直这样
![无标题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111880052/3bd48a6b-d0b6-4b4b-846a-de827af25fe9)

**Comment by Mrzcpf** [comment]
> 试试换回之前的背景 看看会不会有问题

换背景后确实恢复了，谢谢解答

**Comment by Mrzcpf** [comment]
> @SherkeyXD 我也是遇到一样的问题，版本更新后一直这样 ![无标题](https://private-user-images.githubusercontent.com/111880052/293302566-3bd48a6b-d0b6-4b4b-846a-de827af25fe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MjUwNTUsIm5iZiI6MTcwMzgyNDc1NSwicGF0aCI6Ii8xMTE4ODAwNTIvMjkzMzAyNTY2LTNiZDQ4YTZiLWQwYjYtNGI0Yi04NDZhLWRlODI3YWYyNWZlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQwNDM5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTkzZmRjOTY4N2IxMTE2YTQ2ZDIwMTllYzdjZmY0YzRjZmIyN2RiN2MwZDZmMTgwYWQ5Y2Q4YWNlMWIzNWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8SywD30RaOqBnA9BtYTjMwFrAZdHTEhQTZZdfde4Gz4)

在肉鸽里把封面换回之前的背景就可以解决

**Comment by zzyyyl** [comment]
@SherkeyXD 要不给那个 放弃本次探索 多截几张图做多模板匹配吧，或者用ocr？

**Comment by SherkeyXD** [comment]
>  要不给那个 :x: 多截几张图做多模板匹配吧，或者 ocr `放弃本次探索`？

之前水月肉鸽是怎么处理的来着
