### ISSUE TITLE
不识别人物和召唤物

### ISSUE THREAD

**Issue by zxc173123** [MaaAssistantArknights/MaaAssistantArknights#7811]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

台服不识别缄默德克萨斯，不识别令的召唤物

### 日志文件

无

### 截图

无

### 还有别的吗？

无

**Comment by Manicsteiner** [comment]
请提供日志文件以确定错误的识别结果

**Comment by Constrat** [comment]
Until logs, the issue is closed.
I hate random issues where authors just rant about something not working.
