### ISSUE TITLE
萨米肉歌关卡事不过四总是识别失败，不放干员

### ISSUE THREAD

**Issue by fulante** [MaaAssistantArknights/MaaAssistantArknights#7812]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

事不过四关卡总是识别不出来，导致干员无法放置

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13788055/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13788057/gui.log)
以下均为关卡识别错误时间点
23：03：32
23：38：49
23：56：44
00：10：43
00：15：16
00：19：15

### 还有别的吗？

使用的mumu12，window x64

**Comment by SherkeyXD** [comment]
由 #7818 统一追踪
