### ISSUE TITLE
萨米肉鸽新关卡需要更新战斗策略

### ISSUE THREAD

**Issue by SherkeyXD** [MaaAssistantArknights/MaaAssistantArknights#7818]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

- #7808
- #7812

### 有什么好的想法？

至少先把关卡识别做了（

**Comment by s-yh-china** [comment]
要不，手搓一下地图数据(?)
我先发个事不过四的地图数据的pr去XD

**Comment by njnknjnk** [comment]
现在修复了吗

**Comment by zzyyyl** [comment]
v4.28.7-alpha.1.d005.g9c0f6cfc0 加了地图，策略还没人写
