### ISSUE TITLE
能不能加个碎石前识别……？

### ISSUE THREAD

**Issue by Sduck-Inverse** [MaaAssistantArknights/MaaAssistantArknights#7821]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？
![(B%EW9YBCJ$HC2KJK2T(3Y0](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87361258/a344249e-e70a-4446-bd43-d47e35a11907)

以前一直想说能不能不要浪费这一点理智……

### 有什么好的想法？

主要是避免快要满体力可以进本的那一次先试试能不能进本然后再碎石吧

**Comment by ABA2396** [comment]
没懂，碎石和吃药都是单独的一条数据，而且能进本也不会出回复理智的界面

**Comment by status102** [comment]
也许在找，博朗台

**Comment by Sduck-Inverse** [comment]
现在的模式是就算进21的本有20理智也会在回满21的时候继续碎石，这样就多了一个石头吧？
我希望能在回一点后先进本试试看是不是正好能进了，然后再决定是否碎石，明白了吗？
18理智本同理……

**Comment by SherkeyXD** [comment]
> 现在的模式是就算进21的本有20理智也会在回满21的时候继续碎石，这样就多了一个石头吧？
> 我希望能在回一点后先进本试试看是不是正好能进了，然后再决定是否碎石，明白了吗？
> 18理智本同理……

你的要求就是博朗台模式的设定

**Comment by Sduck-Inverse** [comment]
> > 现在的模式是就算进21的本有20理智也会在回满21的时候继续碎石，这样就多了一个石头吧？
> > 我希望能在回一点后先进本试试看是不是正好能进了，然后再决定是否碎石，明白了吗？
> > 18理智本同理……
> 
> 你的要求就是博朗台模式的设定

我现在用的就是博朗台，但还是溢出了一个石头啊，不然不会回满，直接回到0理智了，就是因为在20理智的时候就一直在待机回满后碎石，回到21后再吃石头不是回到135/135了吗？？

**Comment by ABA2396** [comment]
这个是进图前截图的，就是0+135啊

**Comment by Sduck-Inverse** [comment]
> 这个是进图前截图的，就是0+135啊

现在换了主楼图……

**Comment by ABA2396** [comment]
我记得是超过4分钟以上的不等，4分钟内回复的才等

**Comment by ABA2396** [comment]
那就去发个日志

**Comment by status102** [comment]
Duplicate of #3639
