### ISSUE TITLE
萨米肉鸽12月内容扩充后刷源石锭无法放弃探索的问题

### ISSUE THREAD

**Issue by Chonchlishbysh** [MaaAssistantArknights/MaaAssistantArknights#7825]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽内容扩充后，使用刷源石锭策略进入第二层立即退出至萨米肉鸽主界面时无法点击“放弃本次探索”，导致再次进入肉鸽时卡死在第二层入场界面
疑似因主题背景变化而导致无法点击放弃行动

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13792244/debug.zip)

### 截图

![MuMu12-20231229-171334](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/118043535/cb9f6286-ceb2-4ad1-ae86-8bcebaaf22a7)
![MuMu12-20231229-171339](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/118043535/08fbbd3e-c4e5-4a94-a63e-a7f2ecc8d6bd)

### 还有别的吗？

Win10，性能足够，使用的模拟器为MuMu12

**Comment by zzyyyl** [comment]
#7809
