### ISSUE TITLE
Maa v4.28.6 照我以火刷理智缺少关卡的问题

### ISSUE THREAD

**Issue by qingfengxdm** [MaaAssistantArknights/MaaAssistantArknights#7826]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

这里少了一个FC-6，我不知道是我的maa有问题还是版本的bug，求解答

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13792271/debug.zip)

### 截图

<img width="600" alt="29bd9d1b42e0e8a90e201815d4965c7e" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137624999/d29dcd79-936b-49c0-88af-c290c3be7f18">

### 还有别的吗？

使用mumu12模拟器，win11 22H2系统

**Comment by Constrat** [comment]
fixed with MaaRelease/3ce36cafbac03c8385c40419ee773afb2b39ae30
