### ISSUE TITLE
刷理智界面的关卡选择选项中FC-6选项消失

### ISSUE THREAD

**Issue by lewispumpkin** [MaaAssistantArknights/MaaAssistantArknights#7828]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如图，2023/12/29更新了V4.28.6以后，刷理智界面的关卡选择选项中FC-6选项消失，关卡小提示里面也没有显示FC-6

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13792316/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13792317/asst.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/48039629/3738b674-9fde-463d-a7fb-feda9c661715)

**Comment by qingfengxdm** [comment]
a，这问题我前面发了  cwc！

**Comment by status102** [comment]
duplicate of #7826

**Comment by lewispumpkin** [comment]
> a，这问题我前面发了 cwc！

我还特地翻了一下issue都没看见QAQ看来是我瞎了
