### ISSUE TITLE
繁中服开始唤醒自动点击Google登录/Facebook登录

### ISSUE THREAD

**Issue by Maiomi9** [MaaAssistantArknights/MaaAssistantArknights#7832]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

繁中服登录账号每天固定掉一次 基本没有开始唤醒的页面 MAA绑定模拟器启动经常卡在这个登录页面 
一般都要手动点一下登录MAA才能正常唤醒

### 有什么好的想法？

在开始唤醒内添加一个自动登录事件

### 其他内容

![jt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91836807/16c4ce01-803e-41ba-a54d-5d16402a1471)

**Comment by kobi1108** [comment]
#7149 好像有計劃做
臨時解決辦法 重新安裝
