### ISSUE TITLE
萨米肉鸽刷源石锭卡在放弃探索

### ISSUE THREAD

**Issue by dreamexile** [MaaAssistantArknights/MaaAssistantArknights#7833]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

放弃探索放弃不了，应该是改了界面按不到那个“放弃本次探索“的””红X了

### 日志文件

大致时间在12月30日0:00-1:30
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13795195/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13795196/gui.log)

### 截图

![QQ图片20231230013123](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/60901047/fb5f7f16-a120-4875-8268-03771e63f2f9)
![QQ图片20231230013147](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/60901047/5caa4af2-62ac-4a7d-bd97-577644f593f2)

**Comment by SherkeyXD** [comment]
Duplicate of #7809
