### ISSUE TITLE
肉鸽刷源石锭能不能加一个消费干净源石锭的功能

### ISSUE THREAD

**Issue by Shizuka00** [MaaAssistantArknights/MaaAssistantArknights#7835]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

因为这个月的任务正好有个消费一百源石锭和投资就挂了一会儿，投资不算在消费里，所以想建议加个这个功能。

**Comment by status102** [comment]
勾选进入二层，没投资完的钱就会拿去花掉
