### ISSUE TITLE
萨米肉鸽无法正确放弃探索

### ISSUE THREAD

**Issue by MarvelousDT** [MaaAssistantArknights/MaaAssistantArknights#7837]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽在投资源石锭模式下，完成一层探索后可以正常退出到肉鸽主界面，但不会选择放弃探索（图1）；一段时间后会点击继续探索，然后一直卡在图2界面

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13797027/debug.zip)
时间‎2023‎年‎12‎月‎30‎日，‏‎11:20:51

### 截图

![2023-12-30_11-20-30-918_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96490529/2de45138-a916-4ff3-a36d-b7ea9ea2d07b)
![2023-12-30_11-20-51-299_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96490529/fd5ce972-85d0-40cb-9e43-588d0238ef16)

**Comment by ABA2396** [comment]
#7809
