### ISSUE TITLE
萨米肉鸽无法放弃探索

### ISSUE THREAD

**Issue by inkchills** [MaaAssistantArknights/MaaAssistantArknights#7838]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

放弃探索时，点击的是继续探索，然后又点击返回，一直在这里循环

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13797321/debug.zip)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57298119/25827bb6-ba9a-4ece-94fc-400d33536fb3)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57298119/94917dcf-eda5-450f-951f-df09097064e2)

### 还有别的吗？

模拟器：mumu模拟器
操作系统:Windows10 22H2
视频链接：https://clipchamp.com/watch/cwNSfVy40xl

**Comment by ABA2396** [comment]
#7809
