### ISSUE TITLE
萨米肉鸽刷源石锭无法正确重开

### ISSUE THREAD

**Issue by DearPlayer** [MaaAssistantArknights/MaaAssistantArknights#7840]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽投资源石锭无法正常退出探索反复重进，导致无法正常存储商店源石锭

### 日志文件

12-30 15:47:34  开始肉鸽
12-30 15:51:56  完成投币放弃战斗，出现了无法正常退出探索反复进出的情况
12-30 15:52:45  手动停止maa本次肉鸽
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13797495/debug.zip)

### 还有别的吗？

能够正常退出商店，但是不能退出，而是直接重进游戏，是否可能是肉鸽背景换了导致无法识别放弃本次探索？

**Comment by ABA2396** [comment]
> 试试内测版，昨天应该修复了

正式版也发了
