### ISSUE TITLE
不知道叫什么名字（重发日志）

### ISSUE THREAD

**Issue by Sduck-Inverse** [MaaAssistantArknights/MaaAssistantArknights#7841]
### 在提问之前...

- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13797638/asst.log)

### 有什么好的想法？

就是想在理智还差一点就可以进本的时候不要碎石了……

**Comment by ABA2396** [comment]
方舟的理智结算方式是进图的时候扣一点，然后出图的时候扣剩下的理智，也就是说大部分情况下，碎石补理智的情况智都是会有一分半左右（一把的时间）不恢复理智的

所以只有在整好0理智补体力且立刻进图，才会保下这次的一分半的理智回复时间，但这种情况几乎不存在，只有任务失败-1理智才有可能达到类似的情况。正常情况下，下次进图肯定是超过上限的，不管你怎么操作，都是不会回复理智。就算是你说的这种极端情况，下次进就是0理智等了一分半多，会等到1理智再下一把，这时候补理智又会变成136，136-1=135还是超过上限，这一把仍然不会回复，也就是说完全没有收益，只会增加额外的尝试消耗

**Comment by Sduck-Inverse** [comment]
我之前的图是传错了，意思不是在0理智的情况下碎石有问题，是在已经够理智进本的情况下再碎了一个石头，那一分半是溢出了135理智的意思……等出本后就会出现135/135的情况了，不知道这次说清楚了没（擦汗）

uye ***@***.***> 于2023年12月30日周六 18:50写道：

**Comment by ABA2396** [comment]
我觉得是你还没看懂我的意思。除非这一把是你要打的最后一把，如果要继续打的话这一分半的回复时间是保不下来的

**Comment by Sduck-Inverse** [comment]
我知道是出本才扣体力，所以说回满1点直接进本，再出本从0开始碎石比先碎石出本后满体力是一样的么？

uye ***@***.***> 于2023年12月30日周六 18:57写道：

**Comment by status102** [comment]
假设：理智上限135，在刷1-7速刷，60s一把，一把6理智；**不计算过图、结算等耗时**

### 情况1

1. 当前理智为6，且下一次理智恢复时间为6min后
2. 刷本一次
3. 当前理智为0，下次恢复为5min后
4. 等待5min
5. 当前理智为1
6. 碎石
7. 当前理智为136，理智溢出
8. 进本（扣除理智1点，此时理智为135，理智溢出
9. 刷本1min
10. 刷本结算：扣除5点理智，此时理智为130，下次恢复为6min后（**理智开始自然恢复**

### 情况2（当前执行逻辑

1. 当前理智为5
2. 等待理智恢复
3. 当前理智为6
4. 碎石
5. 当前理智为141，理智溢出
6. 进本（扣除理智1点，此时理智为140，理智溢出
7. 刷本1min
8. 刷本结算：扣除5点理智，此时理智为135，理智溢出
9. 当前理智为135
10. 进本（扣除理智1点，此时理智为134，下次恢复为6min后（**理智开始自然恢复**

**Comment by Sduck-Inverse** [comment]
是啊，我只是想避免第二种情况，希望都能避免溢出的时间少一点……能进为什么还要溢出不理解

**Comment by status102** [comment]
> 我只是想避免第二种情况，希望都能避免溢出的时间少一点……能进为什么还要溢出不理解

无论情况1还是情况2都会溢出一次刷本的时间，能进也会溢出刷本时间

**Comment by Sduck-Inverse** [comment]
行，关闭吧，就当我没说

**Comment by status102** [comment]
> 行，关闭吧，就当我没说

或许#7196能省下结算时间

**Comment by Sduck-Inverse** [comment]
> > 行，关闭吧，就当我没说
> 
> 或许#7196能省下结算时间

虽然有看没有懂，我每天要碎几十个石头应该来不及调整，还是谢谢大佬
