### ISSUE TITLE
银淞主题任务异常

### ISSUE THREAD

**Issue by aiirry** [MaaAssistantArknights/MaaAssistantArknights#7843]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

清理智就任务出错，也不能用自动战斗和进肉鸽，重装maa和清缓存都没用。
在这次ss开始后出现的问题。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13797883/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13797884/asst.log)

### 截图

![QQ截图20231230192602](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/155233246/b6205fbb-c855-472f-a07f-c039e9d8873d)

### 还有别的吗？

模拟器：mumu12
win10系统

**Comment by status102** [comment]
```
[2023-12-30 19:11:16.498][TRC][Px964][Tx1ab8] match_templ | TerminalSami.png score: 0.782275 rect: [ 901, 121, 138, 80 ] roi: [ 880, 100, 180, 120 ]
```

**Comment by status102** [comment]
不对，如果这个匹不上的话应该都用不了才对

**Comment by SherkeyXD** [comment]
<img width="846" alt="d740ecd957edb29ebb563d07bb3773b1" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57581480/de0f1748-6e6a-405e-91d6-c358e4324b08">

这都识别的什么啊（

**Comment by zzyyyl** [comment]
单纯的只是萨米主界面的透明度太高了吧）

换个主界面试试先

**Comment by zzyyyl** [comment]
还是说这次肉鸽更新顺带改了点主界面（？

**Comment by aiirry** [comment]
谢谢 换了主界面解决了
