### ISSUE TITLE
 在萨米树洞或水月肉鸽一层（有概率）卡死

### ISSUE THREAD

**Issue by mikechu-2006** [MaaAssistantArknights/MaaAssistantArknights#7851]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，有时候进去就没问题，有时候进去因为看不到最左边的关卡就一直卡住不动，手动向右滑动页面后可以解决，但是挂机时就会一直卡死在这里。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13800647/gui.log)
[asst - 副本.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13800646/asst.-.zip)

### 截图

![001](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/68594660/bef01f4e-e927-44c4-a604-6c669cb13438)
![004](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/68594660/5b9f8603-6984-413b-b8c9-916cf7423044)

**Comment by ABA2396** [comment]
方舟的问题，得重启游戏才能正常

**Comment by mikechu-2006** [comment]
> 方舟的问题，得重启游戏才能正常

那能不能加一个功能，就是在这种情况下左滑到底，或者重启一下呢？因为我不止一次遇到这种情况
