### ISSUE TITLE
macOS 从 hguandl.com 更新时，404导致无法更新

### ISSUE THREAD

**Issue by yy4382** [MaaAssistantArknights/MaaAssistantArknights#7856]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

https://maa-release.hguandl.com/macos/MAA-v4.28.7-macos-universal.dmg 这个URL已经好几个版本是404状态了

查看 <https://maa-release.hguandl.com/macos/appcast.xml>， 其中的几个delta文件是可以下载的，但是由于我是从更老的版本升级的，所以maa会请求上面的那个完整dmg，然后显示更新失败。

这个域名应该是 @hguandl 的，@ 一下他

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13801650/asst.log)
应该没有用

### 还有别的吗？

macOS 14.1
从4.28.4升级至4.28.7时失败，再之前升级的也有问题

**Comment by zzyyyl** [comment]
@hguandl

**Comment by hguandl** [comment]
已经手动上传了，但是不知道为什么CI没有上传DMG。再观察一下后面的版本看看。
