### ISSUE TITLE
萨米肉鸽 停滞不动 手动点击游戏后恢复

### ISSUE THREAD

**Issue by windxisteal** [MaaAssistantArknights/MaaAssistantArknights#7858]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140688857/d052caea-f196-438c-b8f0-d31ce90c5044)
如图所示，在11:41:10 之后maa暂停运行。没有报错。
当我使用鼠标点击游戏后，maa又再次恢复正常。

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13802724/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13802725/gui.log)

### 还有别的吗？

操作系统： Windows 11 23H2
模拟器： WSA 2311.40000.4.0
连接配置：兼容模式
触控模式：ADB input

**Comment by SherkeyXD** [comment]
`Sami@Roguelike@StrategyChange` 这个 task 卡了很久
```json
{
    "class": "asst::ProcessTask",
    "details": {
        "cur_retry": 15,
        "retry_times": 20,
        "to_be_recognized": [
            "Sami@Roguelike@StrategyChange"
        ]
    },
    "first": [
        "Sami@Roguelike@Begin"
    ],
    "pre_task": "Sami@Roguelike@NextLevel",
    "subtask": "ProcessTask",
    "taskchain": "Roguelike",
    "taskid": 6
}
```

然后之后的 task 的 `to_be_recognized` 似乎变成了所有的肉鸽事件？

@ABA2396 来看看）

**Comment by ABA2396** [comment]
> @ABA2396 来看看）

~肉鸽我不熟啊~

**Comment by Constrat** [comment]
```
Emulator: WSA 2311.40000.4.0
Connection Configuration: Compatibility Mode
Touch Mode: ADB input
```
Could this be a reason? WSA + Compatibility + ADB Input is not really a great combo for MAA

**Comment by windxisteal** [comment]
It could be. But it seems to be the only choice if I want to use WSA for MAA.
Since I click the game window, maa will automactically runs normally in one second.

**Comment by Constrat** [comment]
Yeah, WSA is not that greatly supported with MAA because the other input don't work as expected. ADB Input is a last resort. 
All copilots do not work with ADB Input, most functions have other timing troubles.

**Comment by zzyyyl** [comment]
卡在什么界面？

**Comment by windxisteal** [comment]
一般是卡在肉鸽选择下一个节点的阶段，没有选择任何一个节点。也没有滑动界面。似乎多数时候出现在新开一次肉鸽探索或者选择存钱策略时停在第二层后。
