### ISSUE TITLE
[Enhancement]可保存可加载的任务配置文件

### ISSUE THREAD

**Issue by cglcv** [MaaAssistantArknights/MaaAssistantArknights#786]
可以把目前所有执行的任务配置保存成一个文件，可以在需要执行类似任务串时加载，也可以作为无人值守文件在助手启动时自动加载文件并执行相应任务以及完成任务后的动作（关机等）
配合#757 的开机自启与启动模拟器，做到完全的无人值守

**Comment by ABA2396** [comment]
任务配置倒是有了，自动切换倒是没有）
