### ISSUE TITLE
.NET升级提示提供winget命令（一键自动安装）

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#7860]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我懒，winget他全自动
⚠此feature可能会导致部分用户不确定/就此feature提出疑问，欢迎讨论

### 有什么好的想法？

"如果您有winget"
+运行/复制命令/打开wt:`winget install Microsoft.DotNet.DesktopRuntime.8`

**Comment by zzyyyl** [comment]
@ABA2396

**Comment by ABA2396** [comment]
所以用winget的人多吗） ~~感觉大部分人反而会感到疑惑~~

**Comment by wryx166** [comment]
之前我尝试使用winget来给新电脑部署dotnet sdk，msvc等运行库。
但是大多数人的电脑都没法直连ms store或者根本就没有winget，要么卡在第一步：更新软件源，可以通过换镜像源解决；要么卡在第二步：软件下载。
后面直接放弃了。不如手动下载离线包，然后写个一键安装脚本省事。
