### ISSUE TITLE
萨米肉鸽，树篱之途（前行的林地）节点BUG

### ISSUE THREAD

**Issue by wocazhanshen** [MaaAssistantArknights/MaaAssistantArknights#7862]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

进入树篱之途节点后，如果抗干扰指数是0，会卡在页面不动，不会尝试选择离开选项，从gui.log文件中2024-01-02 05:19:57.140进入节点开始

### 日志文件

[Uploading gui.log…]()
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13806151/asst.zip)

### 还有别的吗？

使用的模拟器：mumu模拟器12版本v3.6.12
操作系统win10 22H2
maa版本v4.28.8-alpha.1.d035.g984ba72b9

**Comment by wocazhanshen** [comment]
[Uploading gui.log…]()

**Comment by wocazhanshen** [comment]
[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13806188/gui.zip)

**Comment by HongSLin** [comment]
我也遇到了一样的bug，应该是少了一个针对抗干扰指数为零的branch

**Comment by sanwusang** [comment]
我也是一样的bug，这个bug存在很久很久了，希望可以早日修复

**Comment by status102** [comment]
Duplicate of #7789
