### ISSUE TITLE
WpfGui界面设置-界面主题、重要信息弹出系统通知 修改后无法保存

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/MaaAssistantArknights#7869]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

界面设置-<界面主题>、<重要信息弹出系统通知>修改后无法保存，重启后恢复

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13807978/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/212992ca-21ec-4cdf-aa48-4b6063ad9c6b)

### 还有别的吗？

Version: v4.28.8-alpha.1.d035.g984ba72b9

config/gui.new.json存在，修改设置后文件的修改日期未变化。
移除该文件后，界面主题还原为`跟随系统`，并且修改后不会创建`gui.new.json`文件

- link to #6752

**Comment by ABA2396** [comment]
好像是net8分支里Alisa改配置的时候把fody的PropertyChanged也删了）

**Comment by ABA2396** [comment]
#7683
