### ISSUE TITLE
萨米肉鸽在抗干扰指数为0的情况下无法正确选择路线

### ISSUE THREAD

**Issue by wwhsdhr** [MaaAssistantArknights/MaaAssistantArknights#7870]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

抗干扰指数为0的情况下，会不断尝试跨路线进入商店或是不断尝试进入同路线树洞。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13810075/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13810076/gui.log)
2024-01-02 19:26:59.767开始无限尝试进入商店

**Comment by SherkeyXD** [comment]
#7800
