### ISSUE TITLE
<[萨米肉鸽自动作战]>:在康干扰为零时无法选择除消耗康干扰以外的策略

### ISSUE THREAD

**Issue by Kalivocle** [MaaAssistantArknights/MaaAssistantArknights#7871]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽抗干扰为零时遇到树洞会导致卡死
(如图,下午4点开始代理,于6:40左右遇到树洞卡死了)

### 日志文件

![datFEA4C](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/155414237/7ef7c477-4f2f-440b-88f0-33677840d568)

### 截图

![shuB](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/155414237/89108678-e0be-4df1-8b68-8f152c578b41)

### 还有别的吗？

模拟器:MUMU12
系统:windows 10 22H2
MAA版本:V4.28.7

**Comment by SherkeyXD** [comment]
Duplicate of #7800
