### ISSUE TITLE
maa ui出现显示错误

### ISSUE THREAD

**Issue by yellow2077** [MaaAssistantArknights/MaaAssistantArknights#7873]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

出现了字体异常被拉伸的奇怪问题，随着鼠标移动会不断地刷新，只有光标移动到的位置才会正常显示

### 日志文件

今日下午打开就出现了这个问题

### 截图

如图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151049808/2be9a773-cc8e-48a7-be3f-8913c383330a

<img width="600" alt="Image_1704206719294" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151049808/4ef0305b-08ba-4732-a239-bd77bff678df">

<img width="600" alt="Image_1704206918891" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151049808/fc243211-9a11-48d7-b1a9-237f35307613">

### 还有别的吗？

与模拟器无关
系统:windows 11 23H2
MAA版本:V4.28.8

**Comment by yellow2077** [comment]
补充图片

**Comment by SherkeyXD** [comment]
与 #6935 很像

**Comment by yellow2077** [comment]
> 与 #6935 很像
> 
> 检查一下你的显卡驱动啥的？不像是 maa 侧的问题，感觉是 wpf 的锅

我重新下载了maa，疑似在4.28.7的版本没这个问题，自动更新后问题马上复现了

**Comment by ABA2396** [comment]
问题就是这玩意很难复现，不如问问微软）

**Comment by SherkeyXD** [comment]
#8197
