### ISSUE TITLE
自动公招提示公招识别错误，未执行招聘就结束执行了

### ISSUE THREAD

**Issue by BTreeNewBee** [MaaAssistantArknights/MaaAssistantArknights#788]
界面提示公招识别错误
![图片](https://user-images.githubusercontent.com/18378664/172410134-66f0852f-f887-4f29-b597-4692bbc992b2.png)
抽取的招聘相关日志
[招募日志.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8854218/default.log)

之后重新执行公招招聘成功了。

**Comment by MistEO** [comment]
试试新版本（
