### ISSUE TITLE
萨米肉鸽刷等级时放弃探索

### ISSUE THREAD

**Issue by Saratoga-Official** [MaaAssistantArknights/MaaAssistantArknights#7884]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，之前看了一眼刷的好好的一个没注意回头看就放弃了

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13819154/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13819155/gui.log)

### 截图

这是maa的截图
![}X)VIM~FQNZG _QQS8XC~H5](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151550168/823fbf72-ba37-4a79-a368-e67ad61df8b7)
这是debug里面的截图
![2024-01-03_20-41-37-844_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151550168/9f3a7cf0-5772-4eca-98a6-67fa877e2720)

### 还有别的吗？

mumu12模拟器

**Comment by RWoxiN** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13819471/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13819473/gui.log)

出现相同问题，多次突然放弃探索。

**Comment by zzyyyl** [comment]
第二层进入第三层时的 "完成本层后将获得xxx" 没识别到，有没有人找找原因

**Comment by zzyyyl** [comment]
大概是 StageEncounterClickToLeave 把 NextLevel 的界面点掉了）
