### ISSUE TITLE
美服傀影肉鸽卡在选完人界面不开始探索

### ISSUE THREAD

**Issue by white9610** [MaaAssistantArknights/MaaAssistantArknights#7886]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

雷电模拟器，dpi320，美服卡在选完干员界面不开始探索，卡大概30s左右自动重选干员然后继续卡住，手动开始可以探索

### 日志文件

1

### 截图

![Image_1704288239848](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/128057817/58b059df-08c5-4cc9-8604-49d85d91dd39)

### 还有别的吗？

雷电模拟器，用maatouch也没有反应

**Comment by Manicsteiner** [comment]
The text of confirmation button in the picture is "Deep Dive", but the text of Phantom@Roguelike@EnterAfterRecruit.png is "Enter Castle".
@Constrat can you have a look?

**Comment by zzyyyl** [comment]
Yostar 又改 UI 了？

**Comment by Constrat** [comment]
I honestly wouldn't be surprised. I'll check it right now

**Comment by Constrat** [comment]
Duplicate of #7766
