### ISSUE TITLE
肉鸽通关后反复回溯

### ISSUE THREAD

**Issue by slzhcveosl** [MaaAssistantArknights/MaaAssistantArknights#7891]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

挂肉鸽发现通关了，但是maa没有开始下一轮肉鸽，而是一直停留在结算界面，观察后发现好像在结算后maa会不停回溯历程
时间是1.3晚11：10左右

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13820810/asst.zip)
13820782/gui.log)

### 截图

![捕获](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146112980/5863ff13-3218-4c2e-a16d-cb2ad25f8253)
![捕获2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146112980/5d012492-d50f-476e-a683-e7c0ae22eda6)

**Comment by status102** [comment]
v5.0.0-beta.1 fixed
