### ISSUE TITLE
日服水月肉鸽刷钱在开端和骑士事件无限循环

### ISSUE THREAD

**Issue by haibaoAzarashi** [MaaAssistantArknights/MaaAssistantArknights#7892]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，开启肉鸽刷钱遇到这个事件就会一直徘徊在选项2和3之间，不会选定某个选项。第一次发现的时候循环了一个小时
![QQ图片20240104012444](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108400596/c7ebf569-1252-406b-be52-5436188905e3)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13821249/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13821269/asst.log)
bug出现时间就是截图中遇到天灾信使的时间点

**Comment by SherkeyXD** [comment]
这也不是天灾信使事件啊（

应该是识别错了

**Comment by SherkeyXD** [comment]
这也不是天灾信使事件啊（

应该是识别错了

**Comment by haibaoAzarashi** [comment]
坏了，暴露我不看关卡标题了（

**Comment by haibaoAzarashi** [comment]
刚刚到家发现今天卡在骑士事件的画面了，是三个选项的事件都会卡嘛

**Comment by SherkeyXD** [comment]
奇怪 骑士事件按理说不会卡的 
第一个问题是因为识别错事件了，天灾信使事件是只有两个选项的，所以才会卡

**Comment by haibaoAzarashi** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108400596/db50e01b-0158-449e-a24b-bccfa68979d3

传个视频，看着还挺呆萌的（）

**Comment by haibaoAzarashi** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108400596/7a6e261d-ac48-4d4c-bda9-30d24fb4de5b

bug的时候大概长这样，还挺呆萌
