### ISSUE TITLE
maa用mumu12挂机时间长了会出现弹窗 模拟器运行失败

### ISSUE THREAD

**Issue by Natsuki-Hui** [MaaAssistantArknights/MaaAssistantArknights#7899]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

根据模拟器上面的提示这个地址https://mumu.163.com/help/20230109/35046_1062212.html 要我升级显卡驱动 但我的显卡驱动是最新的4633版本 所以觉得是maa的原因引起崩溃![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40132199/92054fb7-3967-4b65-a0b2-245d7fd00225)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13827504/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13827505/asst.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40132199/15400eef-984e-48af-8cb8-668e8152748b)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40132199/fcebb182-d5d6-4373-9e4d-8f5a29c3de29)

**Comment by ABA2396** [comment]
期间有开加速器什么的东西吗，adb炸了模拟器也会报这个

**Comment by Natsuki-Hui** [comment]
> 期间有开加速器什么的东西吗，adb炸了模拟器也会报这个

开了clash

**Comment by ABA2396** [comment]
这问题感觉还是问问mumu更加靠谱

**Comment by xiaofeiTM233** [comment]
似乎不是maa的问题而是mumu的问题，可以尝试问问mumu客服？之前看到类似问题似乎分配更多内存/处理器解决了

**Comment by Kutius** [comment]
类似的问题 我的表现是直接闪退
