### ISSUE TITLE
萨米肉鸽事件：前行的林地卡住

### ISSUE THREAD

**Issue by shanguangtiaotiaotang** [MaaAssistantArknights/MaaAssistantArknights#7900]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽**事件：前行的林地**在**没有抗干扰指数**的时候会卡住，应该是默认选择消耗抗干扰指数选项的原因

### 日志文件

无

### 截图

无

### 还有别的吗？

无

**Comment by status102** [comment]
duplicate of #7789
