### ISSUE TITLE
MAA打开后过了一会儿就自动关闭了，没有任应用程序报错，但是事件管理器有个报错

### ISSUE THREAD

**Issue by xueqi5201314** [MaaAssistantArknights/MaaAssistantArknights#7907]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA启动正常，郭磊一会儿大概在自动打开模拟器的时候就会突然关闭，也不提示错误，而在事件查看器里面显示有错误

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13830091/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13830094/gui.log)

### 截图

事件查看器截图
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108047693/21ac8ef0-377e-476a-8d9e-abfd5899706b)
关于.NET 8 是否安装的确认
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108047693/6dcf35d3-85dc-42ee-9e46-85705b7f0cdc)

### 还有别的吗？

操作系统信息
版本	Windows 11 专业版
版本	23H2
安装日期	‎2023/‎6/‎12 ‎星期一
操作系统版本	22635.2841
体验	Windows Feature Experience Pack 1000.22681.1000.0
使用的模拟器是**蓝叠模拟器**

**Comment by xueqi5201314** [comment]
没人吗？

**Comment by xueqi5201314** [comment]
最近这个问题再次出现，常常发生在OTA升级之后

**Comment by ABA2396** [comment]
这是 ucrtbase.dll 的问题吧？试试看sfc /scannow或者重新下个 ucrtbase.dll 替换下

**Comment by xueqi5201314** [comment]
> 这是 ucrtbase.dll 的问题吧？试试看sfc /scannow或者重新下个 ucrtbase.dll 替换下

系统扫描过，没有问题，覆盖安装不会有这个问题，只有MAA升级会出现

**Comment by xueqi5201314** [comment]
> 这是 ucrtbase.dll 的问题吧？试试看sfc /scannow或者重新下个 ucrtbase.dll 替换下
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108047693/8dff8a52-897f-4fad-a019-12c850f1dfc0)
这个是今天上午的闪退报错

**Comment by ABA2396** [comment]
报错了发日志啊，这个能看出什么

**Comment by xueqi5201314** [comment]
> 报错了发日志啊，这个能看出什么

没有弹窗报错，直接就关闭了，
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14160817/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14160819/gui.log)

**Comment by ABA2396** [comment]
> 没有弹窗报错，直接就关闭了， [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14160817/asst.log) [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14160819/gui.log)

日志里只到[2024-02-04 23:40:26.039]，没有今天上午的记录

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/2f3497ab-f179-4ec6-845a-bc525f8a7adf)
你这发的也不是一个路径的日志啊

**Comment by xueqi5201314** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/302196144-2f3497ab-f179-4ec6-845a-bc525f8a7adf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDEzNDEsIm5iZiI6MTcwNzE0MTA0MSwicGF0aCI6Ii85OTA3Mjk3NS8zMDIxOTYxNDQtMmYzNDk3YWItZjE3OS00ZWM2LTg0NWEtYmM1MjVmOGE3YWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEzNTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZTY1Njc1YTdlMzZjZjQxYjc3YjgwZGU3M2VmZWMyYzMyYzZhNzA3OWM0MTgxM2IyMDRhOTc5MzBjMGI2YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cWiy1_qsC92DamGIwdjlkRKbZ4d_RrbTZvxP94K56rk) 你这发的也不是一个路径的日志啊

两个MAA，都是这样闪退，这是另外一个的
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14166471/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14166475/gui.log)

**Comment by xueqi5201314** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108047693/8ebca063-0e91-49db-973b-2b29670ce102)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/5470a3b8-5011-4c80-a008-d05b327f21c5)
@Cryolitia 来瞅瞅这个，
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/28685109-d416-4b61-9466-daf5940be1ec)
这样起了个模拟器然后就炸了

**Comment by Cryolitia** [comment]
我看着没什么头绪，可能需要内存转储。

https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

**Comment by Cryolitia** [comment]
https://learn.microsoft.com/en-us/windows/win32/debug/system-error-code-lookup-tool

可以用这个工具查找错误代码的具体含义，我现在在Linux下，有时间会看一下，或者你们谁方便顺手查一下

**Comment by xueqi5201314** [comment]
我发现最近几次关闭有的是识别错误导致的，但是一月那一个确实是在没有任何征兆的情况下直接关闭（没有maa的报错，也没有来自Windows的无响应提醒，直接就没有了）
