### ISSUE TITLE
MAA进行1-7清剩余理智时会一直在选择连续清体力的次数

### ISSUE THREAD

**Issue by louis062211** [MaaAssistantArknights/MaaAssistantArknights#7909]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA在1-7进行最后一次剩余理智清理时，会不断地点击循环次数而不清理体力。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13830625/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13830627/gui.log)
21：27-21：35

### 截图

![MuMu12-20240104-221011](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/155645693/c1b153ee-f098-4de7-b8a5-51f81342a76e)

### 还有别的吗？

系统：windows10
模拟器：MUMU模拟器

**Comment by ABA2396** [comment]
@status102 这玩意透明度是不是变了

**Comment by status102** [comment]
> @status102 这玩意透明度是不是变了

感觉有点怪，看21点的那个匹配正常
```
[2024-01-04 21:00:35.980][TRC][Px1d00][Tx3248] match_templ | FightSeries-Indicator.png score: 0.982782 rect: [ 954, 445, 45, 51 ] roi: [ 940, 190, 80, 380 ]
```

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7ead5bd9-6bee-4218-988d-a051788dca03)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/d4cfb83b-22c1-4567-8089-1339bcdea1c7)
可能是红票的背景比较方正）

**Comment by louis062211** [comment]
是吗？就是准备进行最后一次扫荡时一直在点循环次数。然后好像又点了旁边取消，然后又点选择，持续了几分钟才好。

**Comment by ABA2396** [comment]
说起来为什么你这个图里的数字颜色怎么淡）
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f49b936f-457b-42ae-a071-dfd1c6847d5f)

**Comment by status102** [comment]
> 说起来为什么你这个图里的数字颜色怎么淡） ![image](https://private-user-images.githubusercontent.com/99072975/294243752-f49b936f-457b-42ae-a071-dfd1c6847d5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MTYwNDgsIm5iZiI6MTcwNDQxNTc0OCwicGF0aCI6Ii85OTA3Mjk3NS8yOTQyNDM3NTItZjQ5YjkzNmYtNDU3Yi00MmFlLWEwNzEtZGZkMWM2ODQ3ZDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDAwNDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NmM3YmI4NWIwNWNkMmIxOTgyYjRjZGZlY2MwMzIzMThmZmVkOTc4ZmViZDBiNmIzMGRmOWM0ZTgzZmQ4OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nmGdw5CeHYKfvdl-JrHEGRXm6VRVX8vLUNsxqMvF93Y)

没理智药的时候理智不够就是淡颜色了

**Comment by louis062211** [comment]
这个我知道。我这图看着也怪，看截图明明够体力清一次1-7了，结果颜色是淡淡的。但实际上这是我后来补截的。发现问题那会这里是有颜色的，因为有颜色是这么个情况，我才反馈的。
