### ISSUE TITLE
也许可以加入听歌识曲的api？

### ISSUE THREAD

**Issue by drunkenQCat** [MaaAssistantArknights/MaaAssistantArknights#791]
这样就可以用音乐变化来判断状态了。

**Comment by MistEO** [comment]
这是 maa 有史以来最离谱的需求（

**Comment by drunkenQCat** [comment]
草，确实离谱（
不过理论上会稍微降低一些计算量。毕竟声纹数据量要更小一些。

**Comment by MistEO** [comment]
一般模拟器挂机的静音的吧

**Comment by zhongfly** [comment]
> 一般模拟器挂机都静音的吧

确实

**Comment by ABA2396** [comment]
静音也是能收集到数据的吧，我远控电脑静音的时候还是能收到声音的

**Comment by MistEO** [comment]
> 静音也是能收集到数据的吧，我远控电脑静音的时候还是能收到声音的

是模拟器静音不是电脑静音，相当于模拟器这个应用程序没有音频输出

**Comment by drunkenQCat** [comment]
> > 静音也是能收集到数据的吧，我远控电脑静音的时候还是能收到声音的
> 
> 是模拟器静音不是电脑静音，相当于模拟器这个应用程序没有音频输出

如果真要解决挂机静音又能收集声音的问题，其实很简单，把模拟器的声音引向一个虚拟的“声卡”就好了。不过这样又很难兼顾各个系统，因为各个系统的声卡API都完全不一样。
