### ISSUE TITLE
<[肉鸽]>建议新增肉鸽连战功能

### ISSUE THREAD

**Issue by Kalivocle** [MaaAssistantArknights/MaaAssistantArknights#7911]
### 说说你遇到的问题？

肉鸽在通关一个结局以后会停止在数据回溯结算界面,MAA显示任务已完成
<{[(我知道有定时执行,但肉鸽一局什么时候打完是不确定的)]}>
想刷经验,在通关后停止了,下午浪费了几个小时

**Comment by SherkeyXD** [comment]
默认就是连续作战啊 你是不是哪个设置写错了

**Comment by zzyyyl** [comment]
通关一个结局卡了好像是bug，不太确定）

**Comment by zzyyyl** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/f72eec99-c195-4a0e-8928-38cbac34c308)
如果你的 “开始探索N次后停止任务” 不是很小的数值，也没勾选带 “停止” 的复选框，建议开个 bug issue，带上日志
