### ISSUE TITLE
执行遇到卡死时在debug文件夹生成过多相同图片占用存储

### ISSUE THREAD

**Issue by Kalivocle** [MaaAssistantArknights/MaaAssistantArknights#7913]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

- #7910 

在执行遇到卡死时会在\debug\Roguelike产生过多相同截图图片占用内存
(如下图)

### 日志文件

![CA22C674](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/155414237/3cf0feaf-21c7-4a33-97e5-d1d6044b986f)

### 截图

![6](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/155414237/d3eea0c4-04ee-4f3e-b156-01c4f5f9f6cc)

### 还有别的吗？

模拟器:MUMU12
系统:Windows10 22H2
MAA版本:V4.28.7

**Comment by TimCrownie** [comment]
太真实了
我之前傀影肉鸽卡死一晚上能卡出足足2GB的图来，可惜当时被吓得光速删除了（
