### ISSUE TITLE
The given key 'GeneralWithoutScreencapErr' was not present in the dictionary.

### ISSUE THREAD

**Issue by CoolCoolWind** [MaaAssistantArknights/MaaAssistantArknights#7915]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我有一個手機，而我想嘗試adb 連手機打粥，然後跳了這個報告

![PixPin_2024-01-05_14-00-44](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150428210/3e1f5266-11ee-45f9-beb7-201379da9946)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13838439/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13838443/gui.log)

### 还有别的吗？

win10家用版，三星A32 5G,adb 在maa鏈接下的

**Comment by CoolCoolWind** [comment]
至於爲什麽不用模擬器是因爲我電腦太拉了，開不了模擬器

**Comment by ABA2396** [comment]
GeneralWithoutScreencapErr别选自动检测连接吧？只能手动填端口
https://maa.plus/docs/用户手册/模拟器和设备支持/Android实体设备.html

**Comment by CoolCoolWind** [comment]
我就是手動填了端口發現連不上才嘗試自动检测连接。p.s 我用adb 檢測ok 后才讓maa跑

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/1132e17c-fb63-4419-a16b-5208431bae9c)
不是很懂安卓的截图，摇人看看）另外 minitouch 在实体机上不一定能用，换 adb input 试试

**Comment by ABA2396** [comment]
cc @MistEO
