### ISSUE TITLE
保全派驻时CPU占用异常 

### ISSUE THREAD

**Issue by scqy2000** [MaaAssistantArknights/MaaAssistantArknights#7916]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用内置保全派驻作业时CPU占用异常，基本会达到100%占用率导致模拟器运行卡顿，停止自动战斗后恢复正常。
CPU为i5-9400，GPU为RTX-2060。发现MaaAssistantArknights/issues/7774 存在相同问题且配置较高，排除是本机配置导致的占用异常。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13840349/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13840394/asst.zip)
问题出现在2024-01-05 16:56:00位置，往后都是保全过程中的log

### 截图

![任务管理器](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/19802266/ced872b0-f61b-49bf-9016-3de79d89e8e6)

**Comment by scqy2000** [comment]
However, when using other functions of MAA, the FPS is completely normal and can stably reach more than 100FPS. This abnormality did not occur several versions ago. And the same problem still exists in MaaAssistantArknights/issues/7774 , but his CPU is i9-13900H, so I am skeptical about the conclusion that this problem is caused by an old CPU.

**Comment by ABA2396** [comment]
检查下是不是开着内核隔离和hyperv，可以的关掉再试试看

**Comment by scqy2000** [comment]
确认自从系统安装时内核隔离就是关闭状态且从未启用过Hyper-V

**Comment by status102** [comment]
提供一下模拟器的配置设置看看

copilot类任务和其他任务的性能开销不一样，就拿截图频次来说，有些任务可以等几秒甚至几十秒在截下一张图，自动战斗可等不了那么久。不过开销应该也没那么大

**Comment by status102** [comment]
加上战斗时游戏本身还有资源开消

同时有截图耗时不稳定，200~500（常时），战斗中（500-1400，峰值1700ms

**Comment by scqy2000** [comment]
模拟器配置如图，机身是32GB RAM
![模拟器配置](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/19802266/44505112-a1d8-44ba-9e2b-06c75e2b38e9)

**Comment by status102** [comment]
可以尝试一下切换显卡渲染，看看有无改善

**Comment by scqy2000** [comment]
切换显卡渲染后略有改善，除去较为明显的卡顿感，平均帧率能到70左右，但是MAA占用依然会导致CPU满载

**Comment by scqy2000** [comment]
在自动肉鸽状态下MAA并未出现CPU满载情况并且帧率稳定没有明显卡顿，仅保全派驻模式下有异常表现

**Comment by status102** [comment]
> 切换显卡渲染后略有改善，除去较为明显的卡顿感，平均帧率能到70左右

尝试锁帧看看能不能解决卡顿，明日方舟支持的最高帧数为60

**Comment by scqy2000** [comment]
![锁](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/19802266/4b3c6515-4418-4116-8d2c-187b3621d6c1)
锁60帧后无明显改善，MAA依旧会跑满CPU占用，并且运行表现和不锁帧情况下差不多，都是较稳定的平均帧加上频发的轻微卡顿

**Comment by status102** [comment]
方便的话看看主线关用MAA操作打的时候CPU战斗多少，试试13章主线血魔大军招一堆小怪的，H13-4好像就是，或者非H关最后一关

不是`刷理智`，而是和保全一样的自动战斗

**Comment by status102** [comment]
方便的话看看主线关用MAA操作打的时候CPU战斗多少，试试13章主线血魔大军招一堆小怪的，H13-4好像就是，或者非H关最后一关

不是`刷理智`，而是和保全一样的自动战斗

**Comment by scqy2000** [comment]
测试了主线13-21磨难，前期部署阶段MAA占用大概在50%~75%之间波动并伴随轻微卡顿，在17杀之后逐渐进入打年糕阶段MAA占用均未超过15%同时帧率稳定无卡顿发生。血魔大君召唤虫子似乎对MAA占用没什么影响。

**Comment by ABA2396** [comment]
识别部署栏的干员头像是否有变化很耗费性能的，其他任务中部署栏的人一般是一直减少的，到最后剩不下几个人，所以后期就没什么消耗了，而保全还有补人的机制，到最后基本都是拉满的。

试试看把cache/avatars里的干员头像删了再跑一遍试试，我估计就是这个问题
