### ISSUE TITLE
在Minitouch模式下启动MAA，无法连接至AVD

### ISSUE THREAD

**Issue by Manicsteiner** [MaaAssistantArknights/MaaAssistantArknights#7917]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

此问题已经存在半年以上，只是我一直用ADBinput把这个问题忘了
以ADB input模式启动MAA，再切换至Minitouch，可以正常使用。但以Minitouch模式启动MAA，无法连接至AVD，直接切换触控模式至ADB input也不能使用，需要退出MAA重新启动。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13841163/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13841164/gui.log)

18:50前为AVD正常运行中，杀死adb进程后，以ADB input模式启动MAA，运行一次“领取奖励”任务，切换至Minitouch模式，运行一次“领取奖励”任务，退出MAA
18:50后为AVD正常运行中，杀死adb进程后，以Minitouch模式启动MAA，运行一次“领取奖励”任务，切换至ADB input模式，运行一次“领取奖励”任务

### 还有别的吗？

AVD 33.1.24, Android 13
ADB 34.0.5 (Android Studio)
MAA Latest Debug Build

**Comment by Manicsteiner** [comment]
可能相关的issue https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5355
补充：以Maatouch模式启动和使用也是正常的。同样的，以Minitouch模式启动，再改为Maatouch模式，也不能正常使用。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13843337/asst.log)

**Comment by SherkeyXD** [comment]
更改触控模式要重启 maa 的（

**Comment by Manicsteiner** [comment]
fix in https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/c25c29d7dd74aea87d77edb94bc141d2bdd31f72
