### ISSUE TITLE
肉鸽自行放弃探索

### ISSUE THREAD

**Issue by RWoxiN** [MaaAssistantArknights/MaaAssistantArknights#7920]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

出现多次。在任意需要识别的界面概率性突然停住不进行下一步，而后在近一分钟后放弃本次探索。

这次出现看了日志感觉像是识别错误，在诡异行商准备买玻璃小鸟，但实际点开的是存源石锭的界面，而后在该界面卡住一段时间，随后放弃探索。

之前在先行一步派干员界面和不期而遇选择界面均出现过该情况，而后放弃探索；上个月刷等级无该现象。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13842869/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13842872/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/78133217/16851e5c-e41b-40f5-9bc0-9fa5d1e36316)

**Comment by Golden-Pigeon** [comment]
我也遇到了这个问题。在自动萨米肉鸽的时候，到先行一步节点时，MAA点击选择干员，然后突然停住，然后过了一分多钟自动放弃探索。最近已经遇到两次了。
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14468741/debug.zip)
