### ISSUE TITLE
雷电模拟器点击位置错误

### ISSUE THREAD

**Issue by wingoflan** [MaaAssistantArknights/MaaAssistantArknights#7927]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/25313481/1c975b0e-b413-4bba-ad38-1bb37ab1601b)
任务进行到公招时，MAA会点击终端而非公招按钮，然后就在停在终端页面没有任何操作了。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13847655/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13847656/gui.log)

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/25313481/1c649423-ce35-4283-8c7d-fdc149b6333a

详细现象见视频。

模拟器自带主界面截图如下
![Screenshot_20240106-081843](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/25313481/5587ff45-4923-4a87-bd32-05066d7cbfcf)

### 还有别的吗？

模拟器 雷电 9.0.64
系统相关信息
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/25313481/a0acc2be-1d0a-4281-87d9-99c7fff64c80)
之前使用mumu模拟器的时候没有这个问题，但是使用mumu时会一段时间卡住一次不知道为啥，所以就换雷电试试，然后碰到这个问题。

**Comment by status102** [comment]
- link to #7090 
- link to #7220

**Comment by wingoflan** [comment]
> * link to [MAA雷电模拟器点击错位 #7090](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/7090)
> * link to [雷电模拟器minitouch点击位置错误 #7220](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/7220)

改成maaTouch后已解决。看看能不能把这个加到Q&A里？看上去是已知且暂时解决不了的问题。
