### ISSUE TITLE
MAA在肉鸽战斗中闪退（但是之后可以正常启动）

### ISSUE THREAD

**Issue by zht04** [MaaAssistantArknights/MaaAssistantArknights#7928]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

想挂一晚上刷源石锭，但是早上起来发现MAA已经没了，判断是程序崩溃了，之后我重开maa可以正常重开和使用。大概是在凌晨时间闪退，之前从未出现过这种情况。我挂源石锭之前重启过电脑，，和电脑关系应该不大。

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13848064/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13848067/asst.zip)

**Comment by zoe4477** [comment]
闪退加一，最后的界面停留在肉鸽失败的界面

**Comment by zht04** [comment]
> 闪退加一，最后的界面停留在肉鸽失败的界面。 之前还遇到过肉鸽通关后一直卡在通关界面无法继续的情况。

我这个情况不一样，我是整个maa的运行没了

**Comment by zoe4477** [comment]
> > 闪退加一，最后的界面停留在肉鸽失败的界面。 之前还遇到过肉鸽通关后一直卡在通关界面无法继续的情况。
> 
> 我这个情况不一样，我是整个maa的运行没了

我是说的两种情况，maa闪退的也遇到过两次了。游戏最后都是停留在肉鸽失败/通关的界面，感觉可能是一个原因造成的。
