### ISSUE TITLE
使用pythonAPI接口时的问题

### ISSUE THREAD

**Issue by 2363600182** [MaaAssistantArknights/MaaAssistantArknights#7933]
### Discussed in https://github.com/orgs/MaaAssistantArknights/discussions/7931

<div type='discussions-op-text'>

<sup>Originally posted by **2363600182** January  6, 2024</sup>

![11111111111111](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111691569/98742663-0615-4605-ac51-40350db45fb5)

就像是这样
报了两次libpng warning: sBIT: invalid的错误之后
再过一段时间之后程序会结束而模拟器无任何反应
不知道是哪出问题了</div>

**Comment by 2363600182** [comment]
这个问题，是python的API与maa图形化界面的功能存在差别导致，我想当然的认为既然图形化界面的startup功能能为我启动明日方舟，那么API应该也一样，事实上Python的API不会为我启动明日方舟
![02c912a0b986ef6d31f4e310d5c59374](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111691569/d000cb1c-f59e-4090-8583-d8d2557680b8)
而是会直接开始检测这个界面或者主页，所以当检测不到这个页面时，程序就陷入了循环，最终在数次尝试后停止
[asst_1.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13849876/asst.log)
[asst_2.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13849883/asst.log)
通过查看日志能明显的看出图形化界面和API执行任务的逻辑不同
asst_2 的676行附近 与 asst_1的672-699附近能看出图形化界面和API执行任务的逻辑不同

**Comment by 2363600182** [comment]
asst_1.log是图形化界面产生的日志
_2则是APi产生的

**Comment by ABA2396** [comment]
启动游戏要额外参数的
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/6b230d07-efda-41d9-82d8-2e7b617ae417)

**Comment by 2363600182** [comment]
艹，我没仔细看集成文档
