### ISSUE TITLE
前行的林地抗干扰指数0无动作

### ISSUE THREAD

**Issue by KISSIN20** [MaaAssistantArknights/MaaAssistantArknights#7938]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽前行的林地事件抗干扰指数0无动作

### 日志文件

[新建文件夹 (2).zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13849972/2.zip)
2024.1.6 19：08：17 事件：前行的林地

**Comment by ABA2396** [comment]
#7904 fix

**Comment by FssKlotho** [comment]
我也一样，卡在“前行的林地”情况出现了好几次，但是我的情况不是无动作，而是在抗干扰指数为0时，MAA仍旧在不停点击“消耗1抗干扰指数”的选项，所以就卡住了。
我观察代码里明明是有抗干扰指数大于1时才会点击这个选项的设置
{
            "name": "前行的林地",
            "option_num": 2,
            "choose": 1,
            "choice_require": [
                {
                    "name": "树上就不能走吗？",
                    "Vision": {
                        "value": "1",
                        "type": ">"
                    }
                }
那是不是MAA在“抗干扰指数为0时候出现了识别问题”，还是干脆没有“抗干扰指数为0时"的其他选项
