### ISSUE TITLE
无法领取限时活动物品比如端午签到活动

### ISSUE THREAD

**Issue by desktop4025** [MaaAssistantArknights/MaaAssistantArknights#794]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8857933/asst.zip)
无法自动领取，只能手动领取，遇到这个界面会自动关闭

**Comment by MistEO** [comment]
没这功能（

**Comment by desktop4025** [comment]
好的 抱歉

**Comment by ABA2396** [comment]
之前写过矿场和每日一抽的，但是用户需求不一样，可能有的人想要有的人不想要，每个分开的话又太多了

**Comment by desktop4025** [comment]
好的谢谢
