### ISSUE TITLE
击杀数识别好像还是有问题

### ISSUE THREAD

**Issue by HMZyueshen** [MaaAssistantArknights/MaaAssistantArknights#795]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8857941/asst.log)
[tough_10-03_令+山+桃金娘+风笛.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8857944/tough_10-03_.%2B.%2B.%2B.zip)

模拟器：mumu

**Comment by MistEO** [comment]
看日志击杀数识别的都对的，遇到的具体啥问题？

**Comment by HMZyueshen** [comment]
![image](https://user-images.githubusercontent.com/106477016/172522717-eefe84c8-9189-4a54-b0c7-67136a68918c.png)

**Comment by HMZyueshen** [comment]
它不开技能

**Comment by MistEO** [comment]
是不是点开干员之后（倾斜的视角），然后一直卡着不动？看起来像是技能识别错了

**Comment by HMZyueshen** [comment]
没点开，它直接没操作

**Comment by MistEO** [comment]
那就是点歪了（）

**Comment by HMZyueshen** [comment]
0.0

**Comment by HMZyueshen** [comment]
又能摸一天

**Comment by MistEO** [comment]
试试用坐标开技能（

**Comment by HMZyueshen** [comment]
但不填击杀数这个条件它又会开技能

**Comment by HMZyueshen** [comment]
填了坐标是能开技能了

**Comment by HMZyueshen** [comment]
但我是懒狗不想填xy
