### ISSUE TITLE
刷理智选择红票关卡时会点击一次奖励显示，然后不退出导致刷理智失败

### ISSUE THREAD

**Issue by SnowParaselene** [MaaAssistantArknights/MaaAssistantArknights#7950]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

刷理智选择红票本时出现的问题，进入关卡选择后会点一下ap-5然后点报酬显示，就卡主了，刷了几次都是失败，理智没有用掉

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13853020/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13853021/gui.log)

### 截图

![QQ图片20240107183838](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120864040/15c0e76e-b1fe-4d2e-9b1b-14b0ceb6946f)

**Comment by status102** [comment]
v4.28.8 fixed

**Comment by ABA2396** [comment]
这个提交没放进去吧（？）

**Comment by status102** [comment]
[6fcc266](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7866/commits/6fcc266125b94f9bb9a4d33c574c32ce9d042f92)
放了的
