### ISSUE TITLE
关于基建宿舍 补满空位问题

### ISSUE THREAD

**Issue by CCFF00** [MaaAssistantArknights/MaaAssistantArknights#7957]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

补满空位会选择塑心导致后面宿舍里我固定入住的塑心无法入住

### 日志文件

1

**Comment by ABA2396** [comment]
自动填充的话会因为信赖遮挡名字/筛选未进驻等原因无法指定干员，尽量把要指定的人放在第一个宿舍里
