### ISSUE TITLE
关于吃理智药+剩余体力的关卡选择问题 

### ISSUE THREAD

**Issue by gezhigezhige** [MaaAssistantArknights/MaaAssistantArknights#7961]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/72693458/2eb696cd-c1d7-4ae5-a2a1-c84f197f8bd5)
如图，正常逻辑来讲，正常顺序应该是一直打红票5，直到吃完8管理智药，最后剩余的一点体力打1-7.
但实际操作下来，会出现在第一次体力打完红票5后就开始执行剩余理智开始打1-7，而后吃的8管理智药全用来打1-7了

**Comment by status102** [comment]
这不是一个建议而是bug吧，提供一下log
