### ISSUE TITLE
Linux使用Python的updater获取安装更新错误

### ISSUE THREAD

**Issue by LinSoap** [MaaAssistantArknights/MaaAssistantArknights#7962]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我在使用linux Python接口时，要求更新时每次都卡住，文件能够成功获取，但是无法安装更新，检查updater类后，发现updater只对zip和gz的后缀进行了处理，但是updater从服务器下载的文件是AppImage格式，导致无法更新成功

### 日志文件

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73208166/0f0af93a-5775-4b95-99a8-245a6f4df329)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73208166/fab5f2ce-9305-4653-abd0-76f75ab264e8)

**Comment by wangl-cc** [comment]
Linux 的 `tar.gz` 包还在，只是 python 的 updater 先匹配到了 appimage，可以改一下匹配

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2d21ba3a6e569379184f02f9fffbab8ae85a0686/src/Python/asst/updater.py#L118-L133

把 `system_platform` 加上扩展名应该就行了。

**Comment by CoronaAustralis** [comment]
我也遇到这个问题，我把get_download_url函数里的pattern函数改成```pattern =  r"^MAA-.*" + re.escape(system_platform) + r".*gz$" ```就可以下载覆盖了，但是这是一个全量更新，直接把所有文件全部覆盖了，能否适配增量更新呢，只更新关卡信息之类的

**Comment by wangl-cc** [comment]
> 我也遇到这个问题，我把get_download_url函数里的pattern改成`pattern = r"^MAA-.*" + re.escape(system_platform) + r".*gz$" `就可以下载覆盖了，但是这是一个全量更新，直接把所有文件全部覆盖了，能否适配增量更新呢，只更新关卡信息之类的

如果你说的关卡信息是指每次新活动的导航的话，相关的文件在一个额外的仓库里面https://github.com/MaaAssistantArknights/MaaRelease/tree/main/MaaAssistantArknights/api/resource. 然后还有一些游戏相关数据的资源你可以在 https://github.com/MaaAssistantArknights/MaaResource 仓库找到，这个仓库也包含前面的那一个仓库的资源。你可以把这个库 clone 下来，然后每次加载资源的时候在额外加载里面的资源就行。这是比较好实现的一个热更新的办法，也是 maa-cli 热更新的方式。
