### ISSUE TITLE
肉鸽烧水自选难度

### ISSUE THREAD

**Issue by gew5251** [MaaAssistantArknights/MaaAssistantArknights#7963]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

肉鸽烧热水打完三层退出后, 会自动选15层难度并进入, 没有自己选难度的机会

### 有什么好的想法？

能否退出后直接停止,可以自己选难度,下一局我想打12层难度的.15层打不过

**Comment by zzyyyl** [comment]
目前还没有指定难度的功能，打完三层退了就停可能是个好想法，但下一把开的时候不一定有水壶啊（

---

@SherkeyXD @Lancarus 做一个肉鸽难度选择？还是简单点做个选项打完直接停？

**Comment by gew5251** [comment]
我的意思是打完直接停就行,因为我个人感觉虽然平常看主播直播的时候都是n15难度,但平常大家打n15以下的还是多的,毕竟没有主播那技术....

没有水壶的话手动再来一次就好了,因为烧水一次得十几分钟,不费事,但是难度选完是真改不了了()

**Comment by SherkeyXD** [comment]
> 做一个肉鸽自定义难度选择？还是简单点做个选项打完直接停？

难度选择吧 这个做了其他模式还可以复用的

**Comment by gew5251** [comment]
可以,辛苦了

**Comment by zzyyyl** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/ca41017b-9839-4a20-9027-30c0e6c344c5)

哎，这个功能是不是可以通过直接把这个改成1实现（

**Comment by SherkeyXD** [comment]
> 哎，这个功能是不是可以通过直接把这个改成1实现（

那你烧水的意义何在）

**Comment by zzyyyl** [comment]
> 那你烧水的意义何在）

不想自己打三层.jpg

**Comment by bighead945** [comment]
> ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/ca41017b-9839-4a20-9027-30c0e6c344c5)
> 
> 
> 
> 哎，这个功能是不是可以通过直接把这个改成1实现（
> 
> 
> 
> （指的是 `打完三层退了就停` 这个功能）

那為什麼不直接把執行次數改成一次就好呢？

**Comment by zzyyyl** [comment]
> 請問燒開水是什麼意思，刷熱水壺嗎？

是的，就是这里的第三个选项

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/e4dd858e-c740-435e-a0d1-faa965dc0370)

不过虽然叫烧水，实际上好像刷到演讲稿也会停：）

**Comment by 4573qu** [comment]
之前用这个选项烧水的时候，MAA在切难度的时候我手动打断并选择了6难，然后他就烧到N11的水去了......
不知道是不是可以用这个方法干预难度

**Comment by KobeIverson0** [comment]
我最高只打倒n10，但是在MAA烧热水的时候永远是打的n1，这个功能就用不了了。

**Comment by status102** [comment]
Duplicate of #6494
