### ISSUE TITLE
MAA開啟正常但運行即出錯

### ISSUE THREAD

**Issue by SmallLava** [MaaAssistantArknights/MaaAssistantArknights#7965]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

查找過類似文題解決方法但依舊無法解決(已嘗試路徑更改為全英文、重啟)

### Log files

MAA 遇到了問題
並未將物件參考設定為物件的執行個體。
解決方法
出現未知錯誤
詳細資訊
System.NullReferenceException: 並未將物件參考設定為物件的執行個體。
   於 MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<LinkStart>d__80.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Screenshots

![螢幕擷取畫面 2024-01-08 231257](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/47445581/2dc66e05-38ea-474a-b562-238a498df9ba)
![螢幕擷取畫面 2024-01-08 231401](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/47445581/95f12a6d-3c58-49b0-8f8f-96e668153846)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7693e0bd-4053-4d3f-ae71-198f9bd0c894)

**Comment by ABA2396** [comment]
看样子是你把生息演算拉到前面去了，这玩意应该只能排在最后一个

**Comment by ABA2396** [comment]
看下  \config\gui.json ，把里面的"TaskQueue.Order.xxxx"都删了，估计是因为你把生息演算拉到前面之后入口关了又开了引起的（之前说是延长了10天）

**Comment by SmallLava** [comment]
感謝!
問題解決了
