### ISSUE TITLE
4.28.8游戏资源更新失败

### ISSUE THREAD

**Issue by onlookerLi** [MaaAssistantArknights/MaaAssistantArknights#7967]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96764403/7ef8a8af-84e8-4b78-b8a3-b2184899c34d)
已经是最新版版的MAA,很多个版本都一直出现这个问题，找不到原因。

### 日志文件

时间：1.9 1.10左右

**Comment by onlookerLi** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13864382/asst.log)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13864384/gui.log)
刚才没有成功提交

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/2e6e613e-40d2-4f38-b6c8-a16cd847717b)
这单纯就是网不好连不上吧？试试把\config\gui.json里的"VersionUpdate.ResourceApi"删了重启下让它重新找个镜像试试。不过来ota.maa.plus都连不上的话很多功能都是用不了的（比如新活动导航、自动战斗）

还有你的maa是放在下载文件夹的，那玩意的路径是在USER下面，但是你的电脑名用的是你的名字，之后发日志的时候注意下隐私

**Comment by onlookerLi** [comment]
是的，新活动关卡导航和自动战斗导入神秘代码这里两个功能我一直无法使用，在我删除"VersionUpdate.ResourceApi": "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/"，这个镜像后 重新启动还是这个并没有发生变化，我能在哪里找到其他镜像代替他呢？
关于网络，我换过许多不同的网络，都无法正常连接。
另外感谢你的提醒 下次我会注意。

**Comment by onlookerLi** [comment]
是的，新活动关卡导航和自动战斗导入神秘代码这里两个功能我一直无法使用，在我删除"VersionUpdate.ResourceApi": "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/"&nbsp;这个个镜像后重新启动还是加载的这个网址，并没有发生变化，我能在哪里找到其他镜像代替他呢？
关于网络，我换过许多不同的网络，都无法正常连接。
另外感谢你的提醒 下次我会注意。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月21日(星期天) 下午3:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 4.28.8游戏资源更新失败 (Issue #7967)





 
image.png (view on web)
 这单纯就是网不好连不上吧？试试把\config\gui.json里的"VersionUpdate.ResourceApi"删了重启下让它重新找个镜像试试。不过来ota.maa.plus都连不上的话很多功能都是用不了的（比如新活动导航、自动战斗）
 
还有你的maa是放在下载文件夹的，那玩意的路径是在USER下面，但是你的电脑名用的是你的名字，之后发日志的时候注意下隐私

**Comment by ABA2396** [comment]
感觉没啥办法，试试重新安装 [.NET Framework 4.8](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-offline-installer) 有没有用，不过正式版也马上要上 .net8 了，也可以直接安装 [.net8](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.1-windows-x64-installer) 看看。不过我估计是系统证书的问题，自己搜搜看有没有什么解决办法

**Comment by Kagura-Nanaa** [comment]
把maa写个规则，然后gui里面别配置代理，实测成功更新
![NVIDIA_Overlay_m32fgNKt1f](https://github.com/user-attachments/assets/b6464535-fda6-41ec-b557-07138b8cf3c1)
