### ISSUE TITLE
肉鸽自行放弃探索

### ISSUE THREAD

**Issue by asndje** [MaaAssistantArknights/MaaAssistantArknights#7969]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

到达商店后不在继续进行探索，而是结束任务。
4.28.7及以前版本maa正常工作，升级到4.28.8后出现此情况。

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13868756/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13868757/gui.log)

### 截图

![VZPBP)$( P({O M8G@)C686](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119422597/a64149df-df0a-43c2-b985-a974953de7f4)
<img width="598" alt="13c317bce5b510abec107d812dac2e75" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119422597/ffeeac01-d50d-4a0e-87cd-0a7417d86c17">

### 还有别的吗？

mumu12模拟器 Win11系统 
![}HXPU8%F`}2 E D8D$8E1PJ](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119422597/9a06a6d1-8b2d-4dc0-b5c0-c9fe356f0f7a)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/eb398b2b-259c-4285-94f6-9eafc91170f2)
