### ISSUE TITLE
繁中版生息演算無法重複作業

### ISSUE THREAD

**Issue by diaochan36910** [MaaAssistantArknights/MaaAssistantArknights#7973]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

查詢過其他人的MAA能正常放棄，我操作的時候開始演算跑過幾天後退出要放棄該局時會沒有任何回應。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13872219/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13872221/gui.log)
大約1730之後

### 截图

![MuMu12-20240109-180503](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156074643/5ce9aa64-0c29-4aae-b0b1-2da65dabaf31)

### 还有别的吗？

基础信息
UUID :  fd938cdc-28c2-4672-b025-d85be9fe981d
模拟器版本 :  3.6.11.2438
模拟器磁盘（可用/总）空间 :  116.9GB/125GB
日志路径 :  C:\Program Files\Netease\MuMuPlayer-12.0\vms\MuMuPlayer-12.0-0\logs\

运行环境
VT :  开启
Hyper-V :  关闭
网络环境检测 :  正常
以管理员运行方式 :  否
DirectX 11是否安装 :  是

电脑配置
主板型号 :  Manufacturer: Micro-Star International Co., Ltd.  Product: MPG B550I GAMING EDGE WIFI (MS-7C92)
CPU :  AMD Ryzen 5 5600 6-Core Processor
系统版本 :  Windows 10 64-bit Kernel 10.0.19045
显卡驱动 :  正常
显卡驱动型号 :  31.0.15.3623 (20230608)
所有显卡 :  NVIDIA GeForce RTX 3060 Ti  |  Microsoft Basic Render Driver
当前使用显卡 :  NVIDIA GeForce RTX 3060 Ti
安装磁盘(可用/总)空间 :  21.5GB/465.1GB
可用内存/总内存 :  2.5GB/15.9GB

模拟器设置
Root :  关闭
显卡渲染模式 :  DirectX 模式
性能设置 :  4核/4GB
手机型号 :  Samsung Galaxy S22 Ultra
分辨率 :  1920 * 1080
高帧率 :  开启
后台保活 :  开启

UI版本號 v4.28.8
Core版本號 v4.28.8
Resource 跨年歡慶-相逢

**Comment by ABA2396** [comment]
看日子没看到有生息演算相关的内容，还有我看ui的日志这里说是4.28.4版本
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/fa64ec5c-93d4-4b4f-88d9-6fe8953c4421)
