### ISSUE TITLE
刷理智时掉落识别错误（不是新材料的问题，可以看截图）

### ISSUE THREAD

**Issue by zht04** [MaaAssistantArknights/MaaAssistantArknights#7979]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

刷理智时掉落识别错误（不是新材料的问题，可以看截图），但是不是每次都识别错误，有时候就能识别正确
![8707a5bec0fe2b870376df7cbd24169f](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/144e752a-bee0-410d-a705-ad870e59e954)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13882498/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13882499/asst.log)

### 截图

![8707a5bec0fe2b870376df7cbd24169f](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/29e75477-809b-49f2-940a-83360d2d6696)

**Comment by zzyyyl** [comment]
发一下debug\drops里的相应截图呗？

**Comment by zht04** [comment]
> 发一下debug\drops里的相应截图呗？

![2024-01-10_11-25-06-848_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/813aefca-ba88-4784-a75b-36fd0b29425b)
![2024-01-10_11-22-29-191_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/182e0b14-3e59-4a3a-9de7-e61e16382194)
![2024-01-10_11-19-51-497_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/e39d5c65-ad86-409d-a70e-259d214a1bd3)
![2024-01-10_11-17-11-726_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/efb1d2cf-5781-4970-acfc-3223299beabb)
![2024-01-10_11-14-25-420_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/2a2da3c0-b6e8-49b3-840a-eb1387ea5fd1)
![2024-01-10_11-11-49-713_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/a67928b1-f37a-4115-94b2-37500e0d6548)
![2024-01-10_11-09-14-823_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/cb678bb4-3b97-40a5-b2c3-93663443fdac)
![2024-01-10_11-06-28-724_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/7f243afe-8472-4c49-af38-5c4aa82881b6)
![2024-01-10_11-03-35-028_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/ba2a56af-2c33-4d64-b59f-7b2f338fe2ab)
![2024-01-10_11-00-47-752_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/15d06983-d59b-4f41-94a0-ebca9046f05c)
![2024-01-10_10-57-56-351_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/b2c90d10-87ef-450e-9998-c4cb910e2dfb)
![2024-01-10_10-55-05-929_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/2a2ecb34-90d9-4f57-bfb3-8f66cd6bfb6e)
![2024-01-10_10-52-29-198_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/6490f0ed-b64c-4e91-9555-1a21b10c56d6)
![2024-01-10_10-49-54-305_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/15ddbefd-7b8c-43bb-9537-5406ef6fb02f)
![2024-01-10_10-47-10-613_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/e340d81f-e248-4af2-910d-47325d303c4d)
![2024-01-10_10-44-18-332_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/fc66fe82-5993-4920-a632-4a36fdb12d76)
![2024-01-10_10-41-29-225_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/b5698735-4ffc-4543-9884-1bb9a6cedf16)
![2024-01-10_10-38-40-626_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/4aa8b912-e37a-47bc-be37-21f87948b68b)
差不多都这样

**Comment by zzyyyl** [comment]
@MistEO @horror-proton cc

**Comment by ABA2396** [comment]
酯原料和双酮的数量识别错了，而其匹配得分比较低

不过就算识别对了也没用，还是会报UnknownStage

**Comment by horror-proton** [comment]
酯原料是 `30051` 是根本没识别到, 很奇怪.
我这里没复现出来

> 酯原料和双酮的数量识别错了，而且匹配得分比较低
> 
> 不过就算识别对了也没用，还是会报UnknownStage

并不是数量识别错了, 只是材料得分太低数量直接返回 0 了
