### ISSUE TITLE
软件热更新

### ISSUE THREAD

**Issue by zhangweijian97** [MaaAssistantArknights/MaaAssistantArknights#798]
我MAA一直开着，经常落后好几个版本。

能不能做两个按钮，”检查更新“，”重启软件“。

要不然，现在想要更新MAA的话，就要把MAA关掉，然后开启一次，让他下载安装包。下载好了之后，再关掉，再启动。这样才能更新。太麻烦了。

**Comment by MistEO** [comment]
加了个检查更新按钮，热更等新 UI 吧
