### ISSUE TITLE
每次烧完热水都是15难

### ISSUE THREAD

**Issue by why7682** [MaaAssistantArknights/MaaAssistantArknights#7983]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

首先提个小小的建议，希望下次能添加一个烧完热水的难度，谢谢。。其次每次我烧完热水都是15难，有试过先打一把但是没用。。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13889076/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13889078/gui.log)

**Comment by SherkeyXD** [comment]
Duplicate of #7963
