### ISSUE TITLE
希望在肉鸽选项中加入在选择招募干员时只选择扫描六星和特殊目标干员，以加速肉鸽刷取速度

### ISSUE THREAD

**Issue by TobyLi223** [MaaAssistantArknights/MaaAssistantArknights#7984]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

每选择招募一个干员时，都要把页面滑到最底，使得很大一部分时间浪费在选择招募干员上。

### 有什么好的想法？

除了如标题所述，还可以设计每个人可以自定义的开局招募券干员选择列表

**Comment by Saratoga-Official** [comment]
Duplicate of #9898
