### ISSUE TITLE
需求建议 - 远程通知 - Notification Through Telegram Bot

### ISSUE THREAD

**Issue by aoyin1106** [MaaAssistantArknights/MaaAssistantArknights#7987]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我希望MAA能够实现发送任务完成的通知到telegram。我知道这两个服务：auto bangumi 和watchtower 提供了配置telegram bot的token和chat id来让bot实现消息通知。

**Comment by ABA2396** [comment]
https://maa.plus/docs/协议文档/远程控制协议.html

**Comment by SherkeyXD** [comment]
他这个不是远控吧 应该是外部通知？

**Comment by ABA2396** [comment]
远控也有汇报端点，想自定义的话直接用结束后脚本也是可以的

**Comment by KevinT3Hu** [comment]
考虑到Telegram Bot使用的普遍性，确实可以再封装一层更方便使用。但似乎不适合作为maa本身的功能，如有必要可以另开一个repo
