### ISSUE TITLE
肉鸽通关后会卡在过关结算界面

### ISSUE THREAD

**Issue by Maverick-Y** [MaaAssistantArknights/MaaAssistantArknights#7988]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38951434/d2ee9397-7de0-4c4c-887a-9851f80a2834)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38951434/f4640d45-39ee-481b-8906-a47013d8b867)

早上检查MAA，发现日志不停在显示通关，从9点显示到了12点。检查游戏，我发现貌似卡在结算画面（不停往下滚动的那个）。我打开游戏时在播放结算画面，手动点了右上角的skip后，MAA不知道点了哪里导致再次开始播放了结算画面，导致卡住

第一次提示通关在9点46分

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13897249/debug.zip)

**Comment by HX3N** [comment]
It appears that the same issue is occurring on YoStarKR as well. Although it may not be precisely identical, based on my findings on YoStarKR, executing "minitouch (2, 2)" after recognizing the "Roguelike@GamePass" template results in the same error.

When executing "minitouch (2, 2)," it seemed to transition from the "settlement screen" to the "ending credits."

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/128385247/763c1ae2-03e6-4323-857e-1df9a4b20897)

The current issue also seems to involve an infinite loop after executing "minitouch (3, 3)," similar to the error observed on YoStarKR. Initially, I thought it might be a problem unique to YoStarKR, but it appears to occur on other servers as well. This is all the information I have gathered so far.

**Comment by status102** [comment]
v5.0.0-beta.1 fixed
