### ISSUE TITLE
MAA不弹窗 启动无反应

### ISSUE THREAD

**Issue by 875630979** [MaaAssistantArknights/MaaAssistantArknights#7989]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

启动MAA总是自己消失，点完没反应
昨天是第一次下载  补全了所有的运行库

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13898327/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13898328/gui.log)

### 截图

![V3 I4B6DP~4C3$DZEAL@_QQ](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156289063/ed6b9870-0027-417d-b00b-494dd2111a1b)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/2840e9fc-e43b-4c2d-b593-9f3f0c2ec5e7)
这玩意好像是windows之前补丁的问题，最近有更新过电脑吗

**Comment by ABA2396** [comment]
试试这个，不过要装.net8
https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v4.28.9-alpha.1.d155.gfeea4f1ac

**Comment by ABA2396** [comment]
#6125

**Comment by 875630979** [comment]
> 試試這個，但要裝.net8 https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v4.28.9-alpha.1.d155.gfeea4f1ac
net8之前有装， 我下了这个链接的压缩包就可以启动了   谢谢！！！爱您！！！
