### ISSUE TITLE
[Warning] UI version / Core version mismatch

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#7990]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/36669502-7caa-44b8-aa50-31308dfb8faf)

**Comment by Constrat** [comment]
@ABA2396

**Comment by ABA2396** [comment]
d8b012193808da80d5c0d926a30946f030bebcb1 fixed
