### ISSUE TITLE
【需求】【低优先级】信用商店购买添加支持信用超过300时购买黑名单商品

### ISSUE THREAD

**Issue by dragove** [MaaAssistantArknights/MaaAssistantArknights#7992]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有时候白名单商品买光了信用也还在300以上，这样就浪费了。

### 有什么好的想法？

当白名单东商品买光了信用还超过300时，按照黑名单顺序继续购买商品

### 其他内容

蚊子腿需求，可能没什么用，如果实现起来特别简单可以考虑做，不然可以直接把这个issue关了。

以下是一个样例截图：

![1705036386155](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/24190403/e08bc8d2-3835-40a4-9cd4-ec10d255c293)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/86beba9c-7534-443b-ac88-2a22b7a01f51)

**Comment by dragove** [comment]
我蠢了
