### ISSUE TITLE
maa水月肉鸽中某些关卡会发生卡死情况

### ISSUE THREAD

**Issue by kkf666** [MaaAssistantArknights/MaaAssistantArknights#7994]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

<img width="473" alt="屏幕截图 2024-01-12 195407" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156429568/b3690858-92e6-4f75-8f69-3dfd172846c7">
在这关里面有的时候没有最后一个选项，只有前两个选项的时候，而且你没有五源石锭，不能选择第一个选项，maa就会一直卡住。还有类似的地方不能选择maa想选择的选项（源石锭，希望不满足）就会一直卡住

### 日志文件

![Uploading 屏幕截图 2024-01-12 195407.png…]()

**Comment by Manicsteiner** [comment]
copy of #7910

**Comment by Constrat** [comment]
duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/7910
