### ISSUE TITLE
Base Droning with Fiammetta.

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#7997]
### The problems you have encountered?

- Using a custom base infrastructure, with Fiammetta = `true`. MAA will start `first` by droning the selected infrastructure.
When Fiammetta is off, MAA will not instantly go to the selected infrastructure, it will wait when MAA selects the infrastructure to change operators and then will drone. I find this strange because it seems the behaviour of the droning shouldn't be related to Fiammetta behaviour, or am I missing something?

- The custom json has `"skip": true` for all Manufactures. MAA (After already droning as explained, still enters all Mfg without a reason)

<details><summary>Screen</summary>
<p>

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/27955bf7-4a88-4f52-ba44-2b74118a83ee)

</p>
</details> 

<details><summary>Custom base json</summary>
<p>

```json
                "manufacture": [
                    {
                        "skip": true,
                        "operators": [
                            "清流",
                            "温蒂",
                            "森蚺"
                        ],
                        "sort": false,
                        "autofill": false
                    },
                    {
                        "skip": true,
                        "operators": [
                            "斑点",
                            "砾",
                            "迷迭香"
                        ],
                        "sort": false,
                        "autofill": false
                    },
                    {
                        "skip": true,
                        "operators": [
                            "至简",
                            "槐琥",
                            "断罪者"
                        ],
                        "sort": false,
                        "autofill": false
                    },
                    {
                        "skip": true,
                        "operators": [
                            "红云",
                            "稀音",
                            "帕拉斯"
                        ],
                        "sort": false,
                        "autofill": false
                    }
                ],
```

</p>
</details>

**Comment by ABA2396** [comment]
If the drone and Fiammetta are on（pre） at the same time, the drone will be executed first.

Drones do not enjoy the acceleration effect, but can enjoy the bonus effect of certain skills, such as "巫恋" and "龙舌兰",Their skill effect is related to the working hours. If you change shifts, you will lose this bonus. so it will be used before or after a shift.

"skip" Just skip the shift change process. Other processes are not affected.

**Comment by Constrat** [comment]
> If the drone and Fiammetta are on（pre） at the same time, the drone will be executed first.

> Drones do not enjoy the acceleration effect, but can enjoy the bonus effect of certain skills, such as "巫恋" and "龙舌兰",Their skill effect is related to the working hours. If you change shifts, you will lose this bonus. so it will be used before or after a shift.

So considering Fiammetta will be mainly used with the purpose of "healing" Tequila / Shamare / Proviso etc, the droning will be done before, in pretty much any case? (It doesn't really change much as there are no dead times in the droning process).

>"skip" Just skip the shift change process. Other processes are not affected.
 
In this case it did not enter the Power Plants, Command Center as they are all on `skip`, but it still entered all 4 of the manufacturing? Could this be because of the droning choice? Even if was already done as it's selected as `pre`.
