### ISSUE TITLE
Support Discord External Notifications

### ISSUE THREAD

**Issue by Nocretsis** [MaaAssistantArknights/MaaAssistantArknights#7999]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

希望加入 Discord bot 的通知

### 有什么好的想法？

我有用python写了个个人用的discord bot 通知，可是感觉效率不太高
希望在底层可以支援简单的discord bot的通知

可以照顾没有用微信的国外网友，而且也没有消息数量限制

### 其他内容

[我写的python脚本以作参考](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13924081/discord_noti_template.py.txt)
以及 [C++ Discord API lib](https://dpp.dev/)

**Comment by Constrat** [comment]
Closed with 
- #8628
