### ISSUE TITLE
掉落不识别

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#800]
软件又出现了不识别掉落的情况。
![屏幕截图 2022-06-08 194533](https://user-images.githubusercontent.com/92417243/172608716-af5da49e-7140-42ba-a1d0-99b55c8f692e.jpg)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8861186/asst.log)

**Comment by xiaoweiXX** [comment]
软件版本是3.9.3

**Comment by MistEO** [comment]
这个问题 v3.9.4 已经修复了~
