### ISSUE TITLE
萨米肉鸽半夜MAA刷源石锭刷到400多自动停止

### ISSUE THREAD

**Issue by Denlist** [MaaAssistantArknights/MaaAssistantArknights#8000]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

好几次晚上刷萨米肉鸽源石锭 刷到400多停止，时间不固定。游戏界面是刚新开一层肉鸽就停了。不知道能不能修复，感觉得开定时启动先顶一阵子了。

### 日志文件

~~[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13926461/asst.log)~~
[asst.bak.log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13926762/asst.bak.log.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13926462/gui.log)

**Comment by status102** [comment]
asst.log不包含问题发生时间段的日志，传一下asst.bak.log看看？

**Comment by Denlist** [comment]
asst.bak.log 109MB好像上传不上来

**Comment by status102** [comment]
> asst.bak.log 109MB好像上传不上来

压缩包

**Comment by Denlist** [comment]
[asst.bak.log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13926762/asst.bak.log.zip)

**Comment by Denlist** [comment]
今天换成雷电模拟器去测试 执行100次肉鸽任务后暂停了 刷到了8点多 
之前用的是mumu关闭动态帧率后刷的时间也延长了 不过还是会自动暂停

**Comment by Sait0Yuuki** [comment]
我之前也遇到过，然后今天打开mumu弹提示说肉鸽模式存在内存溢出问题，不知道是不是这个引发的
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/33438025/5aa097bd-b185-4a28-85c9-be8b17d8dcfe)

**Comment by Sonoda-Kotori** [comment]
我是夜神模拟器，最近一段时间maa刷肉鸽第一把没问题，第二把或者第三把的第一场就不进行操作直到战斗失败，然后游戏就没了，还没搞清楚是怎么回事

**Comment by coldshineb** [comment]
> 我之前也遇到过，然后今天打开mumu弹提示说肉鸽模式存在内存溢出问题，不知道是不是这个引发的 ![image](https://private-user-images.githubusercontent.com/33438025/298263071-5aa097bd-b185-4a28-85c9-be8b17d8dcfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDEyOTgsIm5iZiI6MTcwOTM0MDk5OCwicGF0aCI6Ii8zMzQzODAyNS8yOTgyNjMwNzEtNWFhMDk3YmQtYjE4NS00YTI4LTg1YzktYmU4YjE3ZDhkY2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDAwNTYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYzgzYTgyNDZiYTIyNDA0ZjUzNzk5YjFlYmZjYmNiODk1MWEyMGZhNDg2ZGI4YTg5NDEyNTRmM2E4MDU0YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s_2CuFHlLAIVZ41iwCjvg4-CEnJpX1bDvrLHMintUK4)

不光肉鸽，只要长时间（3小时以上）挂游戏必溢出，设置4G给我飙到了8G，整个电脑都卡的用不了了，即使把Mumu退出也无法恢复到正常的内存状态
