### ISSUE TITLE
启动MAA时出现以下提示

### ISSUE THREAD

**Issue by hijack114514** [MaaAssistantArknights/MaaAssistantArknights#8002]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

启动时显示“UI与Core版本不一致”

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13927288/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13927289/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142242356/ce154852-2fe6-4ab1-92f5-409450c13c7a)

### 还有别的吗？

还有一个小问题就是MAA在显示的隐藏的图标中会出现好多个，并且打开后都是同样的MAA程序

**Comment by status102** [comment]
Duplicate of #7990
