### ISSUE TITLE
Bug: 重复托盘图标

### ISSUE THREAD

**Issue by Miuzarte** [MaaAssistantArknights/MaaAssistantArknights#8003]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在开了稍微长点的一段时间后托盘会出现第二个maa图标
![e45ef3c132647ceb0c395c52127ef62e](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66856838/3741576f-7e2a-4c0d-b5b7-8c99edacb1b4)

### 日志文件

不知道什么时候出现的
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13927550/gui.log)

**Comment by Constrat** [comment]
Have you tried opening and closing the icon taskbar? Usually it's just windows that "forgets" to close other MAA istances

**Comment by Miuzarte** [comment]
> Have you tried opening and closing the icon taskbar? Usually it's just windows that "forgets" to close other MAA istances

This is not a problem with Windows, both icons are real existing, double-clicking on them both will pop up the MAA window.

**Comment by Constrat** [comment]
So you're saying a new MAA instance will randomly open?

**Comment by Miuzarte** [comment]
> So you're saying a new MAA instance will randomly open?

I only have one instance，but it shows two icon in taskbar. Double-clicking on them will pop up the same MAA window.

**Comment by ABA2396** [comment]
是必现吗

**Comment by Miuzarte** [comment]
> 是必现吗

前两个版本也出现过，目前从昨晚22:50开到现在还没复现

**Comment by LingFeng16** [comment]
> > 是必现吗Is it inevitable
> 
> 前几个版本也出现过，目前从昨晚22:50更新重启到现在还没复现
> 
> Previous versions have appeared, but haven't since the 22:50 update reboot last night
> 
> 哎，睡前开了个OBS录了一晚上也没复现
> 
> Hey, I opened a OBS before going to bed and recorded it all night without replicating it

我今天碰到了
![屏幕截图 2024-01-16 160713](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/127475595/2e903383-c5e5-4c8d-b917-de6cee8b8092)

**Comment by Miuzarte** [comment]
> > > 是必现吗Is it inevitable
> > 
> > 
> > 前几个版本也出现过，目前从昨晚22:50更新重启到现在还没复现
> > 哎，睡前开了个OBS录了一晚上也没复现
> 
> 我今天碰到了

我两个晚上没复现出来，太奇怪了这玩意

**Comment by ABA2396** [comment]
有没有可能是Windows的问题）是win11吗？我截图软件也遇到了

**Comment by Miuzarte** [comment]
> 有没有可能是Windows的问题）是win11吗？我截图软件也遇到了

.Net

> 有没有可能是Windows的问题）是win11吗？我截图软件也遇到了

.net的锅？我电脑里只有MAA出现过几次

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66856838/a3b08649-a641-4180-9659-f5f3244bd171)
楼上那位应该也是win10

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f748129f-b03e-4efb-9cac-9c668ef5163e)
~~好，这下轮到火绒消失了~~
最近公测版也发了，看看是不是普遍问题

**Comment by LingFeng16** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/297035116-f748129f-b03e-4efb-9cac-9c668ef5163e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTAyMDUsIm5iZiI6MTcwNTQwOTkwNSwicGF0aCI6Ii85OTA3Mjk3NS8yOTcwMzUxMTYtZjc0ODEyOWYtYjAzZS00ZWZiLTljYWMtOWM2NjhlZjUxNjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEyNTgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYzViY2VmNTAyZjk1NTgyZTZkODAyNGM5MWU4ZDA5M2E2ODhiODM3NGI0YTM0YWJmZmVhMWVlZTY4ODE3NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KETHkxsdJZpbFxGCfOb9gFmG1D5n9dFzPxFAzbTjkb8) ~好，这下轮到火绒消失了~ 最近公测版也发了，看看是不是普遍问题
我再看看能不能复现

**Comment by Sisyphe42** [comment]
same，我这边复现率100%，设置的定时执行（maa本身挂着），每次执行后都会再次创建一个托盘图标。和maa窗口状态无关。
我是最近长期远程后才有的，怀疑是win的问题

**Comment by Miuzarte** [comment]
刚刚把游戏改成独占全屏再改回窗口化就突然多出来一个图标，但是重启MAA后没成功复现

**Comment by ABA2396** [comment]
> 刚刚把游戏改成独占全屏再改回窗口化就突然多出来一个图标，但是重启MAA后没成功复现

我之前遇到图标问题的时候直接重启explorer之后都能解决，我估计这是Windows的问题

**Comment by Ai-Himmel** [comment]
同样的问题，在远程桌面断开链接后会出现
类似的问题曾在nVidia控制面板中出现过
> A new NVIDIA icon is created in the system tray each time a user switch takes place in Windows [4251314]

**Comment by MigdalBavel** [comment]
同样问题，没法解决吗？

**Comment by Constrat** [comment]
Unfortunately this seems something completely unrelated to MAA

**Comment by Aoi-cn** [comment]
<img width="320" alt="8406c89a00c290fd2e90609a9dcf41d" src="https://github.com/user-attachments/assets/a5f8ba45-d558-4c2d-9945-43ddbdd8a3ae">

当你打开一段比较长的时间后belike
