### ISSUE TITLE
当次更新重启后,热键会失效,需把maa退出再打开才重新生效

### ISSUE THREAD

**Issue by gew5251** [MaaAssistantArknights/MaaAssistantArknights#8006]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

当次更新重启后,热键会失效,需把maa退出再打开才重新生效,或者当次再设置一下, 但是考虑到内侧更新还挺频繁, 每次更新重启后都要再重启一次, 或者去设置页面设置,有点麻烦(我是双开,两个都要再设置或者重启)
![Snipaste_2024-01-13_23-19-41](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99937172/ca4fd82c-759b-4f41-bfbd-fb4447350f03)

**Comment by ABA2396** [comment]
好像是因为热键冲突，更新完那一瞬间其实是有两个maa同时存在的

**Comment by gew5251** [comment]
> 好像是因为热键冲突，更新完那一瞬间其实是有两个maa同时存在的

是么,但是我两个maa设置的热键不同也会冲突么
