### ISSUE TITLE
每次开始任务时，都会显示截图时间过长

### ISSUE THREAD

**Issue by tangzixuan95** [MaaAssistantArknights/MaaAssistantArknights#8007]
### 说说你遇到的问题？

每次开始任务时，都会显示截图时间过长，不知道是我电脑的问题，还是我使用软件的问题，请问有什么步骤可以进行操作来改善这一情况吗

**Comment by Constrat** [comment]
If you don't have any issues running the tasks, it's nothing to worry about.
