### ISSUE TITLE
无人机不能在换班后使用（使用自定义基建配置）

### ISSUE THREAD

**Issue by asdLeaving** [MaaAssistantArknights/MaaAssistantArknights#8010]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在自定义基建配置.json文件中，写明换班后使用无人机如下：
```json
"drones":{
    "enable":true,
    "index":1,
    "room":"trading",
    "order":"post"
    },
```
实际在换完班之后直接退出基建，没有使用无人机加速。

### 日志文件

2024-01-14 09:35:34.831 ：开始读取基建配置
2024-01-14 09:40:15 ：结束宿舍换班，之后没有执行无人机加速
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13930105/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13930106/gui.log)
基建配置文件如下：
[day2_1682648815984761.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13930112/day2_1682648815984761.json)

### 还有别的吗？

蓝叠国际版5.11.56.1002 N64，Win11，拯救者Y9000P 2023
bug并非最近版本的MAA才出现，大约两个月前就存在。

**Comment by ABA2396** [comment]
cc @MistEO
