### ISSUE TITLE
[3.9.4-beta3] 唤醒设置中 客户端版本 为空

### ISSUE THREAD

**Issue by MuelNova** [MaaAssistantArknights/MaaAssistantArknights#802]
Mumu 模拟器。
依稀记得未更新前时可以选择B服/官服的

![image](https://user-images.githubusercontent.com/68760718/172615516-79adef9a-f209-420d-854e-34062560e38c.png)

**Comment by ABA2396** [comment]
这不狠狠批斗一下玛丽

**Comment by lhhxxxxx** [comment]
#792
下个版本修复
