### ISSUE TITLE
多应用卡顿问题

### ISSUE THREAD

**Issue by hjy52013** [MaaAssistantArknights/MaaAssistantArknights#8021]
### 说说你遇到的问题？

Hi Guys

我想在刷图的过程中玩别的游戏，现在的问题是如果我单独使用模拟器的话 是没有任何问题的，但是如果我开始玩其他游戏，把模拟器放到副屏的话，开始刷图就会很卡，包括不仅限于干员放不下去，技能放不出来

有没有什么办法能让我在玩别的游戏的时候模拟器也正常运行呢，我电脑配置没问题，13代i7 4070ti，如果有人知道如何设置下，能告诉我就太感谢了！！！

**Comment by Manicsteiner** [comment]
一般来说，模拟器会消耗大量cpu资源。如果另一个游戏也需要大量cpu资源，那么出现卡顿是正常的。
我建议您在模拟器和另一个游戏同时运行时打开任务管理器-性能页面-cpu，右键图表-将图形更改为-逻辑处理器，观察cpu运行状况。
如果您仍在使用Windows10系统，那么在13代酷睿cpu上，系统可能会认为副屏上运行的模拟器是后台进程，并将其移至小核心上运行，导致性能不足。

**Comment by hjy52013** [comment]
@Manicsteiner 我把模拟器移到主屏之后就可以了 多谢！！

**Comment by hjy52013** [comment]
close resolved
