### ISSUE TITLE
Fiammetta Infrastructure Algorithm

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#8022]
### The problems you have encountered?

Currently, when `"Fiammetta": true`. MAA will 
1. select `Dorm 0`, 
2. choose the target operator, 
3. confirms. 
4. Exits the `Dorm 0`. 
5. Re enters `Dorm 0`
6. Deselects the target operator
7. Reselects the target operator and looks for Fiammetta.
8. Sorts Fiammetta and `target` (to have the `target` in front).

Why are steps 3, 4, 5, 6 necessary?
Might be a stupid question but is there a need to exit the dorm after selecting only the target operator?
I did a small bit of testing and noticed that Fiammetta still works as intended in this algorithm:
1. Enter `Dorm 0`
2. Deselect all operators
3. Look for and select `target`
4. Look for and select Fiammetta
5. Sort `target` before Fiammetta
6. Confirm

**Comment by ABA2396** [comment]
Fiammetta's skill effective target is sometimes bugged, and this issue has been encountered many times, so this is the safest way to go

**Comment by Constrat** [comment]
Oh, I understand. Thank you
