### ISSUE TITLE
火山旅梦（日服/国际服）SL-Open roi

### ISSUE THREAD

**Issue by Manicsteiner** [MaaAssistantArknights/MaaAssistantArknights#8023]
目前由于国服的task.json中SL-Open roi指定在屏幕中部（领航者活动后会改动至此），日服/国际服虽已经写好了text替换，但没有更改roi为屏幕左下，导致无法使用。现在需要在这两个服务器的task.json中SL-Open字段添加roi，改为"0,500,500,150"，并通过MaaRelease向用户推送热更新。
可惜我的电脑目前无法连接至github，只有手机客户端可以使用，麻烦其他开发者进行此更新。

**Comment by Constrat** [comment]
Wait. The event has the notification in the middle? Or in the bottom left?

**Comment by Constrat** [comment]
Oh nevermind I have the original CN screenshot

**Comment by Manicsteiner** [comment]
> Wait. The event has the notification is in the top-middle? Or in the bottom-left?
> (International still wasn't updated)

It appears in bottom-left in first two week, then moves to middle. Now in bottom-left corner.

**Comment by Constrat** [comment]
Yeah because of the Trials of Navigator. (I don't know what Yostar schedule will do). I'll fix it.

**Comment by Constrat** [comment]
@Manicsteiner It should work, but can you test it? Just in case.

**Comment by Manicsteiner** [comment]
> @Manicsteiner It should work, but can you test it? Just in case.

It works 👍
