### ISSUE TITLE
4.28版本在主界面“反选”功能无法选中“自动肉鸽”

### ISSUE THREAD

**Issue by 4573qu** [MaaAssistantArknights/MaaAssistantArknights#8029]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

当选中”自动肉鸽“选项时选择反选会取消选中”自动肉鸽“，但在未选中”自动肉鸽“选项时点击反选缺不会选中”自动肉鸽“

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13954786/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13954787/gui.log)

**Comment by Constrat** [comment]
4.28? We are already on 5.0.0

**Comment by ABA2396** [comment]
> 4.28? We are already on 5.0.0

自动肉鸽不是日常任务，全反选都是排除的
