### ISSUE TITLE
建议空宿舍自动进驻低信赖/未满信赖（可选）干员

### ISSUE THREAD

**Issue by zoeyek** [MaaAssistantArknights/MaaAssistantArknights#803]
如果距上次基建排班不久一些干员心情满了被放出来而值班的心情又没有那么低（总之就是有宿舍空闲下来了），考虑将低信赖或未满信赖干员入住从而在第二天进基建时吃到一波信赖加成（是有这个机制吧？）

**Comment by ABA2396** [comment]
还有人是把九色鹿或者年配两个回心情的人放在最后一个宿舍 ~另外我没记错的话宿舍没有按信赖排的功能吧?~ 换基建副手倒是可以考虑一下

**Comment by ABA2396** [comment]
现在宿舍有填充干员刷信赖了，可以更新后去设置里开启
