### ISSUE TITLE
在执行任务时CPU占用异常过高

### ISSUE THREAD

**Issue by HS7097** [MaaAssistantArknights/MaaAssistantArknights#8030]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

本机如图所示，若使用9700k运行时，CPU的风扇基本都是拉满的状态

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13957189/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13957191/asst.log)
预计是在上午8:50之后

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/103177863/98195cb7-34cf-4ce1-afea-b72a7e63b36d)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/103177863/4bd47e74-a549-4733-ba1a-ab56257e1e3b)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/103177863/7b8c5e69-03b4-44f6-a639-2a6b69377953)

**Comment by ABA2396** [comment]
#8044 fixed
