### ISSUE TITLE
日服保全员派驻遗嘱

### ISSUE THREAD

**Issue by QWE545102** [MaaAssistantArknights/MaaAssistantArknights#8032]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

日服保全派驻雷神工业作业 进入战斗后所有操作都是 暂停识别后，抽卡，暂停下人，到10多个击杀中期时间就一直，暂停，选人，然后什么都不做，过几秒又暂停，选人，什么都不做，一关打完几乎要20分钟以上，及其拖延

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13963205/asst.log)

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13963204/asst.bak.log)

### 截图

![QQ图片20240117203358](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156914154/28918aeb-edf2-494d-aefe-387683d16e3d)

### 还有别的吗？

模拟器MUMU12
操作 WIN10

**Comment by Constrat** [comment]
@Manicsteiner Well this is interesting: the first part is correctly identified `ニアール` but it seems to somehow read (from the background image)? some gibberish `へわ家ぶ`.
```py
[2024-01-17 19:41:46.605][TRC][Px3248][Tx49b0] asst::WordOcr [{ ニアールへわ家ぶ: [ 0, 0, 293, 35 ], score: 0.620025 }] by OCR Rec , cost 13 ms
[2024-01-17 19:41:46.613][TRC][Px3248][Tx49b0] Proceed [{ ニアールへわ家ぶ: [ 9, 103, 293, 35 ], score: 0.620025 }]

```

**Comment by Constrat** [comment]
An easy fix would be just bypassing `ニアール.*`. If this was EN it would be dangerous as it will also bypass the alter, but looking at Nearl Alter name in JP it seems like `ニアール` is at the end so it should not create proboems. `耀騎士ニアール`

**Comment by Constrat** [comment]
@QWE545102 Provide a screenshot made with the emulator instead of manually screencapping. The screen you provided is 16:9 and we can't work with it. In MUMU there should be the option to take a screen directly from the emulator.

**Comment by Manicsteiner** [comment]
@Constrat  `ニアールへわ家ぶ` should be recognized after PR https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7968 merged, at line 1028.

**Comment by Constrat** [comment]
Well I just noticed
Version being used is `4.28.8`
