### ISSUE TITLE
MAA运行状态下雷电9帧数较低、MAAcpu占用较大

### ISSUE THREAD

**Issue by FallenM1x** [MaaAssistantArknights/MaaAssistantArknights#8034]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA挂机过程中，雷电9帧数较低，仅20-30帧
移动端R9-7945HX MAA单个应用CPU占用率较高，时常为40-50%

### 日志文件

<img width="738" alt="微信图片_20240118002816" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156936878/9bae06bd-505a-4752-9282-b37cea1960bb">

### 截图

<img width="690" alt="微信图片_20240118002801" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156936878/27629444-12c5-4847-a56d-c0a98073f237">
<img width="690" alt="微信图片_20240118002812" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156936878/cc23f563-75a7-4a89-8ff0-3c7ce238829b">
<img width="690" alt="微信图片_20240118002814" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156936878/55b13155-37f8-4bc8-b813-0d7641f1d492">
<img width="960" alt="微信图片_20240118002818
src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156936878/ff0c86c7-9b20-4b56-804a-4a8f8c9c8173">
<img width="960" alt="微信图片_20240118002821" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156936878/00ee1d83-9d2f-4972-997f-cb26642f78a3">
<img width="960" alt="微信图片_20240118002823" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156936878/c1b62c3e-a0bf-4bd3-8abb-c3c2b33ccb71">

### 还有别的吗？

模拟器：雷电9
Win11 23H2
CPU r9 7945HX
RAM 32g 5200mhz

**Comment by Constrat** [comment]
That CPU usage is completely normal. In a copilot operation, MAA will adb screenshot every 200ms. And every time it will extract information from the image (both OCR and template recognition), as for the emulator performance I have a R9 6900HX and I manage to hit 60 fps in stages with lots of particles, so I'm pretty sure it's not MAA-related
