### ISSUE TITLE
关于执行自动肉鸽时遇到稀有坍缩时的检测与行为的建议

### ISSUE THREAD

**Issue by YueZheng-Sea-angle** [MaaAssistantArknights/MaaAssistantArknights#8035]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

![稀有坍缩](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62352027/3c0ce3b2-25f4-456a-9e2c-1cb1de4ba8ec)
发现maa最近这段时间每天晚上存钱时把两个稀有坍缩【目空一些】【图像损坏】都刷到了，很不容易，可惜还没来得及加深就被顶掉了，导致图鉴不完整

### 有什么好的想法？

稀有坍缩的出率极低，不说在存钱时碰巧遇到，就算是专门刷取也跟指路鳞一样是很难碰到的。
可考虑在自动肉鸽中增加一个选项：进入二层后截图检测一次是否为稀有坍缩，若遇到稀有坍缩【目空一些】【图像损坏】则【停止一切行动】或【跳过“自动肉鸽”项，执行下一步任务】，等玩家回归电脑时手动操作进一步加深坍缩。

**Comment by Saratoga-Official** [comment]
#9172 已增加
