### ISSUE TITLE
在进行自动战斗或者自动肉鸽时,CPU占用异常

### ISSUE THREAD

**Issue by o2die** [MaaAssistantArknights/MaaAssistantArknights#8039]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在自动战斗或者自动肉鸽时CPU(14900K)占用高达90%-100%,几乎是处于吃光所有剩余资源的状态(卡到机箱里RGB灯都卡了,Armoury Crate弹出建议开启低资源占用模式的程度).这台是刚换不久的电脑,之前在老电脑上没有出现过这种情况(R7 2700x+2060 6G+32G内存)
<img width="1920" alt="MAA-CPU占用100%" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/22813528/cf47eb67-9440-4ec8-821f-4b3f84607ae8">

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13978830/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13978836/gui.log)
只需查看1月18日22点后部分即可.

### 还有别的吗？

系统版本及硬件配置如下:
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/22813528/8e1ac054-2f8c-46e1-97e6-6df0f0c86afa)
![{~W5~2D@P 2RL S9AWWRMNH](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/22813528/db38230e-31c2-431e-8ee3-253eb4a9df43)
模拟器版本及设置如下:
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/22813528/8198c15e-93ca-4b09-9c54-2affe56d67ff)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/22813528/def324b2-7a94-46d0-876f-749133226029)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/22813528/41bf8176-7ded-4777-b3f6-7b99c398688e)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/22813528/239b5b2b-e4c6-46e0-b82b-b24020554d78)
尝试过调低模拟器刷新率至60FPS,未解决问题.模拟器移到主屏,问题依旧.模拟器vt已开.系统内核隔离和Hyper-V均未开启.删除cache/avatars下文件重开未见明显效果.

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/671faaa7b31d17a1ba0ac9cda43cc5be17b87908 这个 commit 引入了高频率的干员费用 OCR，但大部分场景是不需要识别干员费用的，解决方法可能是加个 flag 仅针对需要的场景进行识别

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/76acccc4-e825-4a5d-847d-a6244c90aa73)
改了下，开局的情况下大概50上下波动（不开maa的话是14%占用），后续挂机的时候大概30上下波动

**Comment by Yinsngl** [comment]
遇到相同问题，5.0.0beta版13900HX在保全自动战斗时不时跑出100的cpu占用，maa经常性出现80%以上的占用
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13999912/asst.log)
rizhidan日志当中11：12分之后就是出问题的时间段

**Comment by Yinsngl** [comment]
<img width="488" alt="屏幕截图 2024-01-21 115250" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142474767/1dfa89a6-fcdc-4288-9f5a-61bac6d1a021">
<img width="481" alt="屏幕截图 2024-01-21 115327" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142474767/d3216a17-effd-4929-9fee-502082bb2fc4">
<img width="481" alt="屏幕截图 2024-01-21 115342" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142474767/b441c343-80e3-4b9f-97e4-98482b7f9946">
补几张图

**Comment by ABA2396** [comment]
#8044 fixed
