### ISSUE TITLE
 YoStarKR - OCR issue with operators in specific skins

### ISSUE THREAD

**Issue by HX3N** [MaaAssistantArknights/MaaAssistantArknights#8040]
### The problems you have encountered?

```
[2024-01-18 19:36:48.977][TRC][Px34f9c][Tx1093fc] asst::WordOcr [{ 사가D-2: [ 0, 0, 182, 30 ], score: 0.670071 }] by OCR Rec , cost 27 ms
[2024-01-18 19:36:48.979][TRC][Px34f9c][Tx1093fc] Proceed [{ 사가D2: [ 10, 111, 182, 30 ], score: 0.670071 }]
```
During battles, certain operators equipped with skins have characters, numbers, or special characters appended behind their OCR

<br>

An issue has occurred with Operator '사가' (Same as 'Saga'). When equipped with a skin, it should be displayed as '사가,' but it appears as '사가D-2.' Even after OcrReplace, it is still recognized as '사가D2' and not being recognized properly.
*Special characters "-" have been removed by OcrReplace.

In addition, several other operators are also experiencing the same issue. For example, Chen, Siege, etc.
<br>

tasks.json "ocrReplace"
```json
            [
                "^사가.{0,2}$",
                "사가"
            ],
            [
                "^사가$",
                "嵯峨"
            ],
```
<br>

Currently addressed the issue using the following regular expression.
However, adding regex individually for operators with problems seems inefficient.
Since error reporting for maa is not active in the Korean community, it is also challenging to receive error reports.

Is there a better way to handle this?

<br>

**Comment by Constrat** [comment]
The threshold needs to be changed.

**Comment by HX3N** [comment]
>The threshold needs to be changed.
<br>

>But as ZH_CN, EN and probably ZN_TW don't seem to have issues regarding this, I highly suggest implementing the "specialParams": [] in the various tasks.json of the different clients.

The threshold needs to be adjusted, and to make this adjustment, new functionality must be added.
Therefore, until the feature allowing modification of the current threshold is added, there is no alternative but to use regular expressions.

Am I understanding it correctly?

**Comment by HX3N** [comment]
> The threshold needs to be changed.

> Something needs to be added to do image manipulation before line 732? But as ZH_CN, EN and probably ZN_TW don't seem to have issues regarding this, I highly suggest implementing the `"specialParams": []` in the various tasks.json of the different clients.

The threshold needs to be adjusted, and to make this adjustment, new functionality must be added.
Therefore, until the feature allowing modification of the current threshold is added, there is no alternative but to use regular expressions.

Am I understanding it correctly?

**Comment by Constrat** [comment]
Unfortunately yes
