### ISSUE TITLE
傀影肉鸽个别关卡识别错误

### ISSUE THREAD

**Issue by LingFeng16** [MaaAssistantArknights/MaaAssistantArknights#8043]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在一些关卡中会出现无法识别，最终导致放弃任务
截图在#debug#文件中并未找到
例如：
恐怖传说
从众效应
感化

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13984920/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13984922/gui.log)
恐怖传说 2024-1-19 11:11:36
从众效应 2024-1-19 11:30:29
恐怖传说 2024-1-19 13:22:27
感化        2024-1-19 13:39:01

### 截图

![屏幕截图 2024-01-19 140142](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/127475595/2cef9c9f-a8e0-43a6-b265-1f06de2e4053)
![屏幕截图 2024-01-19 140202](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/127475595/ad4ae485-e8da-4250-ac42-0dc84ec018c2)
![屏幕截图 2024-01-19 140217](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/127475595/5e2e42ff-bf85-4af0-a7fc-c8ebe01a08a1)
![屏幕截图 2024-01-19 140229](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/127475595/dc4b97ed-fd36-48e5-8495-bf1b7a85b0ce)

**Comment by ABA2396** [comment]
这也没报错啊，只是单纯的没打过吧

**Comment by LingFeng16** [comment]
> 这也没报错啊，只是单纯的没打过吧

没打过是会显示*战斗失败*，不是直接放弃
