### ISSUE TITLE
【需求建议】复刻活动一键扫荡

### ISSUE THREAD

**Issue by wolfgitpr** [MaaAssistantArknights/MaaAssistantArknights#8045]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

希望MAA增加复刻活动一键扫荡功能，使用代理过一遍全图、获取复刻奖励

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/63c7978c-e41c-4221-b392-87317a949420)
