### ISSUE TITLE
跪求开发大佬添加登临意关卡WB-6

### ISSUE THREAD

**Issue by qingfengxdm** [MaaAssistantArknights/MaaAssistantArknights#8048]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

求求开发大佬添加一个WB-6（搓玉关卡）吧，谢谢各位开发大佬 辛苦了

**Comment by SherkeyXD** [comment]
这关挫玉效率不高啊（

还有就是可以使用 当前/上次 这个功能来打任意的关卡，只要你上次打的是 WB6 就行

**Comment by SherkeyXD** [comment]
Done in [`e7ec95a`](https://github.com/MaaAssistantArknights/MaaRelease/commit/e7ec95a6a64de86b0f461817fbd074e13e545cb5)
