### ISSUE TITLE
Maa在Macbook Air上無法檢測到由App Store下載的明日方舟（台服）

### ISSUE THREAD

**Issue by EnderLam** [MaaAssistantArknights/MaaAssistantArknights#8049]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

之前在Windows使用模擬器能順利使用Maa，但轉到Macbook平台用在App Store下載的明日方舟後卻無法檢測，也不能使用

### 有什么好的想法？

製作組能否讓App Store下載的明日方舟也可以使用Maa，感謝🙏

**Comment by ABA2396** [comment]
https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E6%A8%A1%E6%8B%9F%E5%99%A8%E5%92%8C%E8%AE%BE%E5%A4%87%E6%94%AF%E6%8C%81/Mac%E6%A8%A1%E6%8B%9F%E5%99%A8.html
