### ISSUE TITLE
加入活动搓玉关的导航

### ISSUE THREAD

**Issue by 415050203** [MaaAssistantArknights/MaaAssistantArknights#8050]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

希望在可以搓玉的活动中加入搓玉关的导航，比如这次的WB-6

**Comment by SherkeyXD** [comment]
Done in e7ec95a6a64de86b0f461817fbd074e13e545cb5

**Comment by ABA2396** [comment]
> Done in [`e7ec95a`](https://github.com/MaaAssistantArknights/MaaRelease/commit/e7ec95a6a64de86b0f461817fbd074e13e545cb5)

这玩意儿没用吧？tasks里没这个任务的，跑起来估计直接报错了。

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaRelease/commit/2657166f6a48765cc861bfad6781a5b89c4b403d fixed
