### ISSUE TITLE
最小化图标重复

### ISSUE THREAD

**Issue by WLLEGit** [MaaAssistantArknights/MaaAssistantArknights#8054]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

每次远程桌面启动后托盘栏里的MAA图标就会多一个，关闭其中一个所有图标都会消失。

还有件怪事是一直用的自动公测版更新，前段时间出现“UI和Core版本不一致”的提示，不知道相不相关。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71222785/19d1903d-a0ff-405c-821c-81982e61fdbe)

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13999713/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13999714/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71222785/37f39c8a-572b-4f08-9873-dd9a04b123a1)

**Comment by SherkeyXD** [comment]
Duplicate of #8003
