### ISSUE TITLE
萨米肉鸽运行过程中点击到密文板界面，并点击到密文板左上角系统说明界面并卡住

### ISSUE THREAD

**Issue by luciferwrite** [MaaAssistantArknights/MaaAssistantArknights#8056]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14000348/gui.log)

### 还有别的吗？

蓝叠国际版，win11，RTX2070+AMD3600桌面版
+16GB，使用最新公测版本maa

**Comment by luciferwrite** [comment]
![屏幕截图 2024-01-21 142334](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61314020/c5228203-e798-4daa-852e-b02b306245e5)
如图，模拟器截图到大量的说明界面

**Comment by ABA2396** [comment]
会用秘闻板，但不会点开说明。是不是这个模拟器第一次用密文板

**Comment by luciferwrite** [comment]
> 会用秘闻板，但不会点开说明。是不是这个模拟器第一次用密文板

实际上，我从未见过它打肉鸽用过密文板。
我猜是每次它试图用密文板的时候就会被说明页卡住。曾经也出现过几次这种现象，那是之前在逍遥模拟器用4.28版本的时候出现的。

**Comment by luciferwrite** [comment]
> 会用秘闻板，但不会点开说明。是不是这个模拟器第一次用密文板

就在刚刚，我看见它试图用密文板了。
但是在选择了两个红色密文板后，它没选节点直接退出了。
会不会是点击左上角退出时点到了旁边的说明？
