### ISSUE TITLE
肉鸽烧开水功能，科学主义分队会异常结束任务

### ISSUE THREAD

**Issue by Electric-sheep31** [MaaAssistantArknights/MaaAssistantArknights#8066]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

科学主义分队，初始难度烧开水功能异常，战斗一次，进入商店投资一次之后就结束了任务，用特训分队则正常烧开水。希望开发者能解决一下，让废物博士能无痛开局。感恩

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14017957/asst.log)
[gui.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14017958/gui.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14017959/gui.log)

### 截图

<img width="404" alt="1" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/58034511/aa60bb36-ad0a-4a26-a754-88ebc4808e1e">
<img width="379" alt="2" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/58034511/836f29aa-dcfa-49a1-ac2d-b48c583157b3">

**Comment by ABA2396** [comment]
@status102 现在刷开局是不是强制开投资了？那这个投资选了刷开局就直接editable给关了呗

@Electric-sheep31 点开投资源石锭之后把达到上限停止给关了

**Comment by status102** [comment]
> @status102 现在刷开局是不是强制开投资了？那这个投资选了刷开局就直接editable给关了呗

我觉得可以把强制开投资取消掉（感觉没必要

**Comment by ABA2396** [comment]
> > @status102 现在刷开局是不是强制开投资了？那这个投资选了刷开局就直接editable给关了呗
> 
> 我觉得可以把强制开投资取消掉（感觉没必要

不管开不开，但至少得让界面显示的内容和传给core的内容是一样的，我看日志里传的是 "investment_enabled":true,"investment_enter_second_floor":false,"investments_count":9999999,"stop_when_investment_full":true 但界面上投资的没勾，这样对用户来说太混沌了

**Comment by ABA2396** [comment]
@status102 要不别在这里判断了，直接在RoguelikeMode的set里改RoguelikeInvestmentEnabled？

**Comment by status102** [comment]
> @status102 要不别在这里判断了，直接在RoguelikeMode的set里改RoguelikeInvestmentEnabled？

放set好，这里有点抽象了
