### ISSUE TITLE
刷理智设置内的手动输入关卡名只支持特定关卡

### ISSUE THREAD

**Issue by BlackL1ght** [MaaAssistantArknights/MaaAssistantArknights#8068]
### 说说你遇到的问题？

输入如使用说明提示关卡如OF-1可以正常开始，但是输入CW-6就会提示不支持的关卡
![QQ截图20240123192850](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102863784/f5659661-7e09-4f17-82b6-71d863848fcb)
![QQ图片20240123192911](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102863784/9200aa61-37fa-475b-9286-9b462bdff320)

**Comment by Constrat** [comment]
Because it's not in the list of supported levels, simple as that.
The levels that are supported are the "farming" ones (for events usually the 8, 9, 10. Or 6, 7, 8)
In this case CW only supports CW-8 CW-9 and CW-10 as shown here:
```json
    "CW-10": {
        "algorithm": "JustReturn",
        "sub": [
            "CW-Open"
        ],
        "next": [
            "CW-10@SideStoryStage",
            "CW-10@SwipeToStage"
        ]
    },
    "CW-9": {
        "algorithm": "JustReturn",
        "sub": [
            "CW-Open"
        ],
        "next": [
            "CW-9@SideStoryStage",
            "CW-9@SwipeToStage"
        ]
    },
    "CW-8": {
        "algorithm": "JustReturn",
        "sub": [
            "CW-Open"
        ],
        "next": [
            "CW-8@SideStoryStage",
            "CW-8@SwipeToStage"
        ]

```

**Comment by BlackL1ght** [comment]
@Constrat 
Thanks for your reply.
But I still have a question if there is a way for individuals to customize the farm list.
(All of the above uses a translator, and I'm sorry if there are any ambiguities)
