### ISSUE TITLE
日服 基建 错误的将褐果识别为陈

### ISSUE THREAD

**Issue by ShirasawaYui** [MaaAssistantArknights/MaaAssistantArknights#8075]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

ass里记录如下 
[2024-01-24 08:14:35.985][TRC][Px710][Tx2084] asst::WordOcr [{ チェストナット: [ 0, 0, 115, 15 ], score: 0.999920 }] by OCR Rec , cost 14 ms
[2024-01-24 08:14:35.989][TRC][Px710][Tx2084] Proceed [{ 陈: [ 3, 3, 115, 15 ], score: 0.999920 }]

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14031135/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14031136/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/11786799/295c0c8b-13d7-413c-b777-aed4ff70d4f0)

### 还有别的吗？

使用mumu12，win10 22h2。

**Comment by Manicsteiner** [comment]
奇怪了，ocr_config里也没有`ス`和`ン`的等价啊，咋识别成这样了
理论上已解决，稍后发pr
急用的话请自行修改`/resource/global/YoStarJP/resource/tasks.json` 第212行，`"^チェ[シン]"` 改为 `"^チェ[シン]^[ス]"`
