### ISSUE TITLE
使用MAA一定概率导致电脑强制重启

### ISSUE THREAD

**Issue by SocttJame** [MaaAssistantArknights/MaaAssistantArknights#8076]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用MAA的时候有一定的概率导致电脑瞬间黑屏，然后自动重启。据观察多发生在基建代理期间。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14031817/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14031819/gui.log)

### 还有别的吗？

Resource Version: 登临意·复刻
UI Version: v4.28.8
Core Version: v4.28.8
使用的模拟器为MUMU模拟器V3.6.2
系统是Windows11

**Comment by Rbqwow** [comment]
如果是因为CPU占用 那内测版已提供GPU加速功能 同时添加了最小截图间隔 已经优化CPU占用
这种问题得看系统的事件查看器 不过八成是运气不好cpu体质差
(maa的突发占用是比烤机猛的
