### ISSUE TITLE
小工具干员识别功能圣约送葬人识别错误

### ISSUE THREAD

**Issue by kisaragi-xq** [MaaAssistantArknights/MaaAssistantArknights#8078]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

无法识别在库的圣约送葬人（精一立绘）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14034214/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14034232/gui.log)

### 截图

![2024-01-24_14-50-10-875_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57785791/e5195831-cdba-44bb-8457-e23d632db679)
![Screenshot_2024 01 24_15 00 35 863](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57785791/7669d8c8-dfe8-4e8d-aecc-41ee32c0380a)
![MAA](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57785791/8c9c51b9-ee0a-4a67-a16a-dad514901ec4)

**Comment by Constrat** [comment]
Favourite operators are not supported, as the OCR becomes pretty much impossible
