### ISSUE TITLE
i18n: Challenge Mode / Adverse Environment / Hard Mode incosistency

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#8080]
### Reason

In most of the GUI localizations `Adverse` is used to describe the harder stage difficulty. This is not entirely accurate as the harder mode should be `Challenge`.

This issue became apparent and could create confusion considering the new main Story stages from Chapter 10 and after.

Chapter 10 introduced the Adverse Environment which allowed players to quickly play `Challenge` stages, but as of now, only the main story uses the "new" term `Adverse`, all sidestories and mini events use `Challenge`.

The term `Hard` is never used in-game specifically, but it can definitely be used in the GUI to explain both `Challenge` and `Adverse`.

Using the term `Adverse` in the Battle List of the Copilot tab is just wrong. As technically this is not an Adverse Environment (from the main story, but just a Challenge Mode of a Sidestory).
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/8ed09eba-8932-48b6-9237-96e652fb1c5e)

As far as I can understand zh_cn, the Official client uses `突袭` (translated as `raid`) for Challenge Mode. Is it also used for stages in Adverse Environment?

### Inconsistency:
In the Farming tab, the user is required to add `-Hard` in case it wants MAA to use `Adverse` environment (this only works for Chapter 10, 11, 12 etc, as chapter 9 uses the new Environment interface but doesn't have the option for `Adverse`)

### Suggestions:
1. Consistency > Clarity: Just use `Hard` for all menus and tasks, instead of `Adverse` in Copilot and `Hard` in farming.
2. Clarity > Consistency: considering that through `prts.plus` and Copilot we can clear pretty much every stage in the game (both `Adverse` and `Challenge` stages, the most logical solution would be to just switch the `Copilot` tab with a generic `Hard` (unless we can identify which stages are `Adverse` and which are `Challenge`, honestly a pain and a useless thing, as the user would need to know what stage is what. For this reason `Hard` seems the most logical answer.
Meanwhile in the `Farming` stage implementing `Adverse` as the manual entry of stages it mostly for farming stages and no `Challenge` stages are ever farmed / cleared automatically through farming.

Wow I just noticed how much I wrote. TL;DR just read the `Suggestions`

**Comment by status102** [comment]
Sorry, I imported wrong thing. I got the word `Adverse` from `BattleStartAdverse.png`. But I mistook the picture. I may change it to `Raid`. `BattleStartRaid.png` seems the right pic.

**Comment by Constrat** [comment]
The pic is not really the problem. The problem is pretty much the entire GUI and user input

**Comment by status102** [comment]
> The pic is not really the problem. The problem is pretty much the entire GUI and user input

yeh, i will fix it soon

**Comment by status102** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/9c4191e8-1461-48b0-a460-7a41f90381b4)

now like that

**Comment by status102** [comment]
Or do you like `OF-1(Raid)`

**Comment by Constrat** [comment]
I think -Gard is the better choice, more globally understandable

**Comment by status102** [comment]
> I think `-Hard` is the better choice, more globally understandable.
`-Hard`已经用于描述主线关的磨难难度，不应于突袭模式混淆

**Comment by Constrat** [comment]
And that's why the issue is open. The Farming one is wrong.

**Comment by status102** [comment]
I couldn't understand `Farming` clearly.

**Comment by status102** [comment]
我不太赞成把`Adverse`和`Raid`合并。虽然看上去鹰角想用`Adverse`去替换`Raid`，但是这两个的设置入口并不一致，前者处于关卡列表，后者处于关卡开始处。

**Comment by Constrat** [comment]
But having Adverse in Battle list makes even less sense, as you are definitely going to use it for more than just Adverse, as you can clear pretty much every level.
