### ISSUE TITLE
能不能加一个不自动弹出公告的设置

### ISSUE THREAD

**Issue by bronzitro** [MaaAssistantArknights/MaaAssistantArknights#8084]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

每次有新公告的时候开启都会自动弹出另一个公告窗口，需要手动点不再提示然后关掉，很繁琐。

### 有什么好的想法？

希望可以设置不显示或者不自动弹出公告窗口。
必要的信息可以在一键长草的信息栏里提示。

**Comment by SleepSheep3s** [comment]
公告栏最下方有“下次不再提示”选项

**Comment by bronzitro** [comment]
> 公告栏最下方有“下次不再提示”选项

下次不再提示的只是当前这个公告。下次有新的公告还是会弹出来，默认没有勾上下次不再提示，得手动再点“下次不再提示”，然后才能关掉

**Comment by Rbqwow** [comment]
你猜猜它为什么叫公告

**Comment by bronzitro** [comment]
就算一定要显示公告，能不能默认把下次不再显示勾上？

**Comment by bronzitro** [comment]
> ~你猜猜它为什么叫公告~

就算一定要显示公告，能不能默认把下次不再显示勾上？
