### ISSUE TITLE
maa无法连接雷电模拟器最新版本（猜测）

### ISSUE THREAD

**Issue by SleepSheep3s** [MaaAssistantArknights/MaaAssistantArknights#8085]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

2024-01-25 10:49:25.858使用maa时无法连接模拟器，尝试强制替换adb和选择模拟器文件夹中的adb均没有成功解决，于2024-01-25 19:36:24.066将昨晚刚刚更新的模拟器回退到2023-12-15的9.0.64版本问题解决，猜测2024-1-11的9.0.65版本与maa之间存在某种未知问题
由于并不清楚具体情况以及专业知识的欠缺，以上内容均为我的实际经历与简单猜测，我并不确定具体原因，如果猜测错误我表示抱歉
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140258034/5dc26922-165b-4e4f-b0c5-a43929c97bf3)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14051295/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14051296/gui.log)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/3e4474df-570e-4ca7-920c-316740a6edbc)
看日志是因为端口号不对或者是模拟器的端口调试没开，不过雷电应该是默认开启的，等等看后续有没有类似的问题报告

**Comment by zzyyyl** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74587068/6859a639-d6b2-4049-a54d-b970f738316a)

**Comment by lskdjfowe** [comment]
我把MAA退回到v4.28.6，雷电模拟器退回到了9.0.64版本，但是还是无法连接，之前那会儿都还能正常使用的，不知道怎么回事。跟楼主一样，尝试强制替换adb和选择模拟器文件夹中的adb均没有成功解决，但是我尝试回退到以前的版本也并没有成功解决。
![Snipaste_2024-01-27_00-07-29](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52398012/7932eea5-a313-410c-a419-9a04cdf1702e)

**Comment by zzyyyl** [comment]
重启电脑试试
