### ISSUE TITLE
国际版基建换班无法识别苍苔

### ISSUE THREAD

**Issue by RyougiAzaka** [MaaAssistantArknights/MaaAssistantArknights#8089]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA版本：稳定版 版本号4.28.8
模拟器：bluestackes 5.14.10
使用MAA自动换班自定义配置时无法识别苍苔

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14059480/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14059481/gui.log)
时间2024-01-26 上午9：10-9：40

### 截图

![Snipaste_2024-01-26_09-50-21](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36186993/640b689a-7de2-4a60-b815-2b909d7b29b1)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/122b4de9-bfae-4417-a857-be91bebad451)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/1ef09cc7-9075-41e5-838e-c64eb9cfd63a)
v4.28.8得更新资源之后才能用这个，https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/90a6c36b1738a27c548e7f04a46b6c73c66e5b3f 你现在标题栏里的活动显示的什么？

**Comment by Constrat** [comment]
> MAA Version: Stable Version No. 4.28.8

Updating to latest beta will fix.
