### ISSUE TITLE
能否添加批量代理关卡的功能

### ISSUE THREAD

**Issue by heixiui** [MaaAssistantArknights/MaaAssistantArknights#8090]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在刷复刻活动有需要从第一关到ex8关卡的首通任务，这种任务目前没有在maa上找到相关功能，只能手动一关一关打，能否添加一个任务单功能，能够自定义多个关卡和次数

**Comment by status102** [comment]
已有普通关1~9的自动
