### ISSUE TITLE
建议“吃理智药”功能不要记忆勾选状态

### ISSUE THREAD

**Issue by YOUQY979** [MaaAssistantArknights/MaaAssistantArknights#8091]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

刷理智时勾选了“吃理智药”功能，完成任务后关闭maa，当下次打开maa时，这个地方记忆了勾选状态，多吃了我2个理智药。

### 有什么好的想法？

我认为吃理智药这个功能没必要记忆勾选，一般都是一次性的，一次任务完成后自动取消勾选比较好。

**Comment by status102** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/808ddc5a-53ca-454d-8d9a-d75d5b0840ee)

**Comment by YOUQY979** [comment]
这功能有点藏得太深了，我在高级设置里没找到，原来在外面，建议直观一点，或者勾选后给个“生效一次还是多次”的提示
