### ISSUE TITLE
Mumu更新之后，无法运行，出现“截图失败”、“无法连接”等等错误

### ISSUE THREAD

**Issue by foreverlong** [MaaAssistantArknights/MaaAssistantArknights#8093]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

已经重启电脑、重装mumu，重装maa。以前是没事的，mumu自动更新之后出现的问题。而且很奇怪的是，有时候是能运行的，但大多数时候都无法运行。运行maa之后，命令行输入F:\Netease\MuMuPlayer-12.0\shell\.\adb.exe devices，并没有显示有设备。
Core Version: v5.0.0-beta.2
UI Version: v5.0.0-beta.2

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14071468/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14071469/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43675453/af8e62a6-a709-467c-8250-836054fb9b66)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43675453/96e96a4d-c777-4be0-8b97-d400523f3e3a)

**Comment by ABA2396** [comment]
感觉和这个类似 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8109
