### ISSUE TITLE
完成任务后附加一个弹窗功能

### ISSUE THREAD

**Issue by dinghaoh** [MaaAssistantArknights/MaaAssistantArknights#8094]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在长时间任务之后经常不知道何时完成，建议在“完成后”的选项中加一个“弹出系统弹窗”

### 有什么好的想法？

建议在“完成后”的选项中加一个“弹出系统弹窗”选项

### 其他内容

null

**Comment by status102** [comment]
有个重要通知，或者可以用完成后脚本

**Comment by ABA2396** [comment]
默认右下角就有吐司通知的吧
