### ISSUE TITLE
Windows 11更新至26040后，MAA卡在正在连接模拟器

### ISSUE THREAD

**Issue by abbaccadd0** [MaaAssistantArknights/MaaAssistantArknights#8096]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

Windows 11更新至26040后，MAA会长时间卡在正在连接模拟器

Resource Version: 登临意·复刻
UI Version: v5.0.0-beta.2
Core Version: v5.0.0-beta.2

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14071971/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14071972/asst.log)

### 截图

![Snipaste_2024-01-27_18-38-54](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39579855/d1d3aaff-7a07-4e90-9918-b2f3172f45ea)

### 还有别的吗？

更新Windows前可以正常连接，更新后无法连接
Mumu版本为3.7.10
因为删除了Windows.old，我无法回退至上个版本
但是我换了其他停留在26020的电脑，没有使用问题

如果是Windows导致的无法使用的问题，建议公告里提一嘴🚀

**Comment by ABA2396** [comment]
试试看把 设置-连接设置-使用 ADB Lite 关了

**Comment by abbaccadd0** [comment]
> 试试看把 设置-连接设置-使用 ADB Lite 关了

我在设置-连接设置中关闭了ADB Lite，但是问题没有修复

**Comment by ABA2396** [comment]
日志

**Comment by abbaccadd0** [comment]
> 日志

我刚刚运行了下，不在卡住，开始报错了
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14075754/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14075756/gui.log)

**Comment by ABA2396** [comment]
cc @MistEO

**Comment by ABA2396** [comment]
看日志里一直在超时，所以没照着这个绿字操作过吗
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/b86538e1-6712-41f7-a208-a5bfcf33215f)

**Comment by fireg958** [comment]
你开没开hyper-v，我更新后自动开了这个导致连不上模拟器，关掉试试？

**Comment by ABA2396** [comment]
再发下日志
