### ISSUE TITLE
允许直接复制<干员识别>的结果（即拥有以及未拥有的干员），而非json

### ISSUE THREAD

**Issue by wryx166** [MaaAssistantArknights/MaaAssistantArknights#8097]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

图中的<复制到剪切板>按钮实际作用为复制结果json到剪切板，并非复制输出结果(即界面显示的拥有以及未拥有的干员)。
希望能允许直接复制<干员识别>的结果（即拥有以及未拥有的干员）

### 其他内容

![界面截图](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/81759142/866173e6-f902-44ff-8d05-22b45c10a8bf)

![<复制到剪切板>按钮的实际功能](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/81759142/f5400352-e839-4252-8258-562dd712c629)

**Comment by ABA2396** [comment]
改了下，可以直接选择复制
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/60da1dc4-567b-4436-ab45-1cf9d38cb52e)
``` 
已拥有: 14 名: 

	芙蓉        	梓兰        	12F         	巡林者      	
	黑角        	夜刀        	杜林        	Lancet-2    	
	Castle-3    	THRM-EX     	正义骑士号  	泰拉大陆调查团	
	U-Official  	Friston-3  
```

**Comment by ABA2396** [comment]
改了下，可以直接选择复制
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/60da1dc4-567b-4436-ab45-1cf9d38cb52e)
``` 
已拥有: 14 名: 

	芙蓉        	梓兰        	12F         	巡林者      	
	黑角        	夜刀        	杜林        	Lancet-2    	
	Castle-3    	THRM-EX     	正义骑士号  	泰拉大陆调查团	
	U-Official  	Friston-3  
```
