### ISSUE TITLE
基建bug（又好像不算bug？）

### ISSUE THREAD

**Issue by zhsuuw** [MaaAssistantArknights/MaaAssistantArknights#81]
基建制造站会选零心情的干员，最后零心情的干员全到宿舍里回心情了，制造站根本没人干活。有时候会在制造站的干员列表里翻半天，最后啥都没换就到下一个制造站里去了

**Comment by MistEO** [comment]
麻烦附下日志文件吧

**Comment by zhsuuw** [comment]
> 麻烦附下日志文件吧
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7776595/asst.log)

**Comment by zhsuuw** [comment]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7776597/asst.log)

**Comment by zhsuuw** [comment]
> 麻烦附下日志文件吧
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7776874/asst.log)

**Comment by MistEO** [comment]
新版本陆陆续续修了一些基建的 bug, 不知道这个问题还存不存在了，有兴趣再试试看吧~
