### ISSUE TITLE
萨米肉鸽在某些情况下弹出教程页卡住

### ISSUE THREAD

**Issue by Yumi0606** [MaaAssistantArknights/MaaAssistantArknights#8100]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

1.弹出密文宣告页卡住的情况: 尝试打深入调查，卡住约两小时被我手动终止，发现MAA是在第三层非BOSS关前点开了密文板。正常来说密文板只会在第五层BOSS关前用。感觉不是密文板的问题，是我打深入探索可能中途弹出了别的东西，操作不匹配了。
2.在debug文件夹看见很多重复截图，难道没做这些页面的识别吗？记录一下

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14075465/asst.log)
[asst2.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14075466/asst2.log)

### 截图

![2024-01-28_14-19-07-205_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136778556/d78cf06d-a3a9-4356-946f-a976febb9a07)
![2024-01-28_12-57-21-349_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136778556/3241299f-98e1-4f7c-bd99-f31f7eda4b4f)
![2024-01-28_14-53-21-605_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/136778556/7fb50f8a-c3a7-42f5-b575-04dc812bce75)

### 还有别的吗？

UI Version: v5.0.0-beta.2
Core Version: v5.0.0-beta.2
Resource Version: 登临意·复刻

**Comment by QingXuer** [comment]
同样也遇到了，而且遇到了两次![IMG_20240128_202559.jpg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97309254/8fdb6e9d-3c6e-4e91-ad93-ac9cae397e86)

**Comment by zhangweijian97** [comment]
我印象中教程页面一直不会点的，所以新安装的明日方舟，我都是手动开一次肉鸽把教程页面关了。然后再用maa

**Comment by ABA2396** [comment]
> 我印象中教程页面一直不会点的，所以新安装的明日方舟，我都是手动开一次肉鸽把教程页面关了。然后再用maa

就是不知道这个是maa点开的还是因为第一次进自动弹出来的
