### ISSUE TITLE
【逍遥模拟器】除开始唤醒外，执行任务都先进入该模块然后无响应，“出现错误，已返回”

### ISSUE THREAD

**Issue by PlayerMo** [MaaAssistantArknights/MaaAssistantArknights#8101]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

Resource Version: 登临意·复刻
UI Version: v5.0.0-beta.2
Core Version: v5.0.0-beta.2

  例如 执行寻访/Recruit时，先进入“寻访”页面，然后未响应，最后“出现错误，已返回”

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14076560/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14076561/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/68996781/8b30055d-fc89-4717-8bc1-1e67a4287c2f)
![Uploading Screenshot_20240128-232818.png…]()

### 还有别的吗？

逍遙模擬器，这个情况是最近更新MAA之后才出现的。
版本：Windows 10 专业版 22H2 19045.3570
逍遥模拟器的adb可以查看到设备（已手动将逍遥模拟器的adb换成MAA的）

**Comment by Mioscout** [comment]
把逍遥模拟器渲染模式从opengl切倒DX
Opengl的问题不止这一处，还有不吃药，吃药之后不打提示任务完成直接跳下一个任务，自动战斗选人出错和无法进行自动战斗直接报错。
