### ISSUE TITLE
基建换班时，宿舍的自动填充有时会填不满人

### ISSUE THREAD

**Issue by IberianCabbage** [MaaAssistantArknights/MaaAssistantArknights#8102]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我的基建换班在宿舍长期使用的是autofill方式，但是最近这段时间时不时就会出现宿舍放不满人的状况，有的时候一个宿舍只进4人甚至只进3人，出问题的宿舍的编号也不固定，出问题时对应的换班波次也不固定，不知道出现这个问题的原因是什么
之前几次出问题的时候没注意记录，以下截图和log对应的出问题的换班时间是1.28 23:00（截图是第二天早晨发现问题时截的所以是满心情）

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14078444/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14078446/asst.log)

### 截图

![QQ截图20240129081532](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96757630/b3b6f6c1-fa61-4f25-83f0-084f84cd1908)
![QQ截图20240129082432](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96757630/7c324155-7818-4423-b4a4-72be2e2f1f2a)

### 还有别的吗？

使用模拟器：mumu12 V3.6.11(2438)
系统：win10

**Comment by IberianCabbage** [comment]
正好今天早晨又遇到了一次这个问题，这一次是2号宿舍人没上齐，时间为8:36，把这次的log也传上来了
![QQ截图20240130083741](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96757630/fbe03e85-ef3d-4627-b8c3-ec3c2bdcb3a3)
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14091419/debug.zip)

**Comment by ABA2396** [comment]
奇怪，这里甚至还复查过了选上了5个人
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7be4cef1-ec3b-479d-af60-7febcc8a9167)
抓人来看看 cc @zzyyyl

**Comment by zzyyyl** [comment]
（修了么

感觉可能需要给复查前加一段小延迟？

**Comment by RichieXu** [comment]
我也出现了这个问题 每个宿舍中只填入了三人
