### ISSUE TITLE
【账号切换】账号切换时能选中账号，但是不能点击登录

### ISSUE THREAD

**Issue by diein3-6** [MaaAssistantArknights/MaaAssistantArknights#8104]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

从账号A切换到账号B时，可以选中账号B，但是无法触发账号B的登录
版本：
Resource Version: 登临意·复刻
UI Version: v5.0.0-beta.2
Core Version: v5.0.0-beta.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14079346/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14079370/gui.log)

### 截图

![QQ图片20240129113230](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/51123729/efc13ea0-dc96-416a-b5db-1ee5852e88f4)

### 还有别的吗？

模拟器 蓝叠4 64位

**Comment by status102** [comment]
> cc @status102

![AccountManagerLoginButton](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/88d9f593-70fb-4cfc-b2df-3f8998402d82)

卡这玩意了，有时候不行，有时候重新开始就行，怪怪的；以前没遇到过，最近才开始
