### ISSUE TITLE
使用逍遥模拟器时无法最小化启动和完成任务后关闭模拟器

### ISSUE THREAD

**Issue by ZGLinus** [MaaAssistantArknights/MaaAssistantArknights#8107]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

启动时我已经勾选了最小化模拟器和MAA，但是模拟器没有最小化启动
完成后动作我选择的是退出模拟器，但是模拟器没有退出。
debug是删除之前日志重新生成的
```
Resource Version: 登临意·复刻
UI Version: v4.28.8
Core Version: v4.28.8
```

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14081067/debug.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/69845097/926a5ff9-15db-40a3-8c17-d9fb9d2f0a47)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/69845097/b7cb32f5-d375-475f-9877-d18e45207ac8)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/69845097/6a045b00-ae5b-4bf6-8868-d9c38d94584c)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/69845097/e54169cc-532d-4cc5-b601-3a8d39dcdc68)

### 还有别的吗？

以下内容为模拟器自带的系统诊断内容
```
VT特性	支持 （Hyper-V）
操作系统	正常
显卡驱动	正常
声音	正常
帧数	60fps

硬件信息
CPU&内存	AMD Ryzen 7 4800H with Radeon Graphics (16核15GB)
显卡 1	NVIDIA GeForce GTX 1650
显卡 2	AMD Radeon(TM) Graphics

软件信息
OS版本	Microsoft Windows 11 家庭版 23H2 (22631.3007) 64
显卡驱动	30.0.14.7219 - 9-23-2021
OpenGL Version	4.6.0 NVIDIA 472.19
OpenGL Render	NVIDIA GeForce GTX 1650/PCIe/SSE2

模拟器信息
设备信息	9.0.9.0 (p) - Asus ROG 3 Android 9.0.0 (64bit) (cn)
运行配置	8核 6144MB 1600x900 300 dpi OpenGL (w/ opt)
```

**Comment by ZGLinus** [comment]
另外说明一下，截图是后面补上的，所以和log里面的时间对不上

**Comment by ABA2396** [comment]
权限不够，逍遥模拟器的控制台是管理员权限的，你得用管理员权限启动maa

**Comment by ZGLinus** [comment]
已解决，谢谢
