### ISSUE TITLE
Maa开始工作之后打开unity editor，maa无法正常操作模拟器

### ISSUE THREAD

**Issue by DFFHSEVDH** [MaaAssistantArknights/MaaAssistantArknights#8108]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

maa正常工作并已经开始操作模拟器后，打开unity editor，maa此时无法操作模拟器，且无任何bug提示。
先启动unity editor后启动maa不会出错，先启动maa并开始工作后再启动unity editor大概率出现不工作情况。

### 日志文件

时间大概在2024-1-29 5时左右。

### 还有别的吗？

电脑为win11系统，模拟器为蓝叠模拟器。
maa没有使用自动检测连接。

**Comment by status102** [comment]
缺少日志

**Comment by ABA2396** [comment]
感觉和加速器一个道理）

**Comment by DFFHSEVDH** [comment]
asst.log
gui.log

**Comment by DFFHSEVDH** [comment]
github 提交文件一直失败，用qq微云传了一下[https://share.weiyun.com/lUaf6X05](url)

**Comment by DFFHSEVDH** [comment]
unity editor打开之后好像会运行一个安卓adb，不知道是不是这个原因

**Comment by ABA2396** [comment]
那是有影响的，adb启动会关闭其他版本的adb，两个都用一个adb就行了，比如把unity editor的adb路径填到maa里。当然这个adb得要能和模拟器的版本匹配
