### ISSUE TITLE
【逍遥模拟器】在理智足够的情况下，连续作战会卡在结算页面并且有概率无法领取信用

### ISSUE THREAD

**Issue by ZGLinus** [MaaAssistantArknights/MaaAssistantArknights#8110]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

1. 在09:34:42处，在连续作战时会卡在结算页面。
2. 在09:21:39-09:22:34处，获取信用和购物时，出现了无法领取信用的情况，但是，在之后进行另外一个账号的获取信用时，又可以正常领取信用
```
Resource Version: 登临意·复刻
UI Version: v4.28.8
Core Version: v4.28.8
```

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14091813/debug.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/69845097/bd58c818-87b2-4dce-a22f-314605ced012)

### 还有别的吗？

诊断信息
VT特性	支持 （Hyper-V）
操作系统	正常
显卡驱动	正常
声音	正常
帧数	60fps

硬件信息
CPU&内存	AMD Ryzen 7 4800H with Radeon Graphics (16核15GB)
显卡 1	NVIDIA GeForce GTX 1650
显卡 2	AMD Radeon(TM) Graphics

软件信息
OS版本	Microsoft Windows 11 家庭版 23H2 (22631.3007) 64
显卡驱动	30.0.14.7219 - 9-23-2021
OpenGL Version	4.6.0 NVIDIA 472.19
OpenGL Render	NVIDIA GeForce GTX 1650/PCIe/SSE2

模拟器信息
设备信息	9.0.9.0 (p) - Asus ROG 3 Android 9.0.0 (64bit) (cn)
运行配置	8核 6144MB 1600x900 300 dpi OpenGL (w/ opt)

**Comment by ABA2396** [comment]
这种情况日志里看着还不少，很多连续截图十几次才截到一张有数据的图，maa默认的任务重试次数是20次，达到上限之后就报错了

**Comment by ABA2396** [comment]
09:09:21到09:46:38截图到黑屏219次，就算里面有个十几次真的是在黑屏动画，这个出错率也太高了

**Comment by ZGLinus** [comment]
确实存在这种现象，看来是模拟器而不是MAA的问题。
