### ISSUE TITLE
萨米肉鸽刷源石锭任务没完成但是显示任务已完成

### ISSUE THREAD

**Issue by zht04** [MaaAssistantArknights/MaaAssistantArknights#8111]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽刷源石锭任务没完成但是显示任务已完成，在探索第100次后发生这种情况，但是设置的次数是默认的999999，时间是10.22左右，源石锭只刷到818。探索第100次后进入一层就直接显示完成了，一关都没打，也没进商店，感觉可能是探索次数的问题

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14092433/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14092436/asst.zip)

**Comment by ABA2396** [comment]
@MistEO 是因为这玩意吗？https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/f2b30c363b9298b06642a9d5bef57206e4d027ef/src/MaaCore/Task/Interface/RoguelikeTask.cpp#L68
