### ISSUE TITLE
完全在后台运行的maa

### ISSUE THREAD

**Issue by zjh790** [MaaAssistantArknights/MaaAssistantArknights#8114]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

当使用系统自带的时间计划启动maa时总是会影响用户的正常使用，所以希望可以添加此功能
当然，最影响的还是模拟器启动时的影响，所以我希望可以得到一个解决方法
如果是在别的桌面运行的话也是可以的

**Comment by ABA2396** [comment]
设置里有最小化启动模拟器，如果用不了的话也可以让模拟器回到桌面，这样模拟器只占300M左右内存，cpu和gpu基本没有占用
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/819fa6f3-b22d-453e-9dbd-c3a74fac82c8)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f98159c5-c818-47e8-9dc1-a1b1fbec604c)

**Comment by zjh790** [comment]
> 感谢，除了当模拟器启动完成的时候会弹出以外

这个有什么解决办法吗

**Comment by ABA2396** [comment]
之前就试过了写不了，我用的模拟器不支持最小化启动，要是有模拟器支持附加参数也可以用类似
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/048c7085-27db-4b23-89c2-b56d75dfe305)的方式，但我估计大部分的都没有这玩意。
所以用
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/c6319806-1acb-447c-9c11-8cb20149270c)
