### ISSUE TITLE
基建换班时在会客室卡住 后续任务无法继续执行 但显示完成任务: Infrast

### ISSUE THREAD

**Issue by wjdmxx** [MaaAssistantArknights/MaaAssistantArknights#8115]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/24445882/2e4508fa-4181-441f-816b-b10520a3a3dd)
在发电站之后进入会客室 但是会卡住 之后进行后续任务的时候无法进行 会一直卡住 然后跳过后边的设施 但是在基建的环节也不会报错
Resource Version: 登临意·复刻
UI Version: v5.0.0-beta.2
Core Version: v5.0.0-beta.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14096648/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14096649/gui.log)
时间点: 01-30 16:06:22左右出现问题

**Comment by txsiny** [comment]
同样的问题 而且触发概率极高
<img width="197" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/42532696/39d25a33-3993-4f1b-bf59-401ed6a2bbd0">

**Comment by Mou-Froski** [comment]
会不会是maa识别不了线索交流完成的原因？
不过也不像，我那次卡住的是会客室干员，后续任务倒是正常

**Comment by Mou-Froski** [comment]
会不会是maa识别不了线索交流完成的原因？
不过也不像，我那次卡住的是会客室干员，后续任务倒是正常
