### ISSUE TITLE
MAA运行就重启电脑

### ISSUE THREAD

**Issue by irvingwnz** [MaaAssistantArknights/MaaAssistantArknights#8118]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我今天刚换了一个主板，然后按照往常一样操作MAA，但是MAA一但运行一小会，我的电脑就会重启，想知道到底怎么回事

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14108197/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14108198/asst.log)

### 还有别的吗？

使用的MUMU12模拟器，win10操作系统
![QQ浏览器截图20240131144842](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/158256530/9df06be8-76a7-4368-9572-7bf848f4731e)

**Comment by Manicsteiner** [comment]
怎么听着像散热器没撕膜，过热关机了……
log没看出问题
如果是瞬间黑屏，重启时过蓝屏界面，建议跑个烤机压力测试，如果也会黑屏重启就该排查硬件问题了

**Comment by irvingwnz** [comment]
应该不是过热关机，游戏都正常玩的，但是我这MAA一但运行，动一下就重启了，我还下了另个模拟器雷电，也是同样运行就重启，搞不太清楚为什么会这样

**Comment by Rbqwow** [comment]
事件查看器里应该会有重启的原因 可以试着找找看
找不到就在任务栏那个搜索里面搜

**Comment by Manicsteiner** [comment]
> 应该不是过热关机，游戏都正常玩的，但是我这MAA一但运行，动一下就重启了，我还下了另个模拟器雷电，也是同样运行就重启，搞不太清楚为什么会这样

游戏的CPU负载往往不如模拟器

隔空修电脑这事也没法整，建议还是自己一点点排除问题
1. 查看MAA完成后选项，如果是完成后关机就成笑话了
2. 备份MAA\config目录下的文件，删除config目录和cache目录，尝试重新配置MAA
3. 不使用MAA，手动打开模拟器进行一段时间的游戏
4. 运行一个高负载程序（如烤机测试）

如果是MAA的问题，前两步就能解决了

**Comment by irvingwnz** [comment]
我这maa是运行了几秒钟后电脑就自动重启了，然后我这两天都是手动打开的模拟器进行游戏，并没有出现重启的情况，我刚才将整个MAA删除进行重新安装设置，还是有一样的问题，所以也有点搞不懂了，这是我从事件查看器上找到的信息，因为我本身看不懂，能麻烦你看下是怎么回事吗，如果实在还不行，我就去线下看看能不能找人查看是什么问题。
![信息1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/158256530/a718b543-fe18-45f6-bc25-a9a6a387722f)

![信息2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/158256530/45182823-ad47-491e-928d-e0016e0679b3)

**Comment by LiamSho** [comment]
> 我这maa是运行了几秒钟后电脑就自动重启了，然后我这两天都是手动打开的模拟器进行游戏，并没有出现重启的情况，我刚才将整个MAA删除进行重新安装设置，还是有一样的问题，所以也有点搞不懂了，这是我从事件查看器上找到的信息，因为我本身看不懂，能麻烦你看下是怎么回事吗，如果实在还不行，我就去线下看看能不能找人查看是什么问题。 ![信息1](https://private-user-images.githubusercontent.com/158256530/301467518-a718b543-fe18-45f6-bc25-a9a6a387722f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTA2MTYsIm5iZiI6MTcwNjg1MDMxNiwicGF0aCI6Ii8xNTgyNTY1MzAvMzAxNDY3NTE4LWE3MThiNTQzLWZlMTgtNDVmNi1iYzI1LWE5YTZhMzg3NzIyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwNTA1MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTY4Y2UyM2M4NGY2YWVlZWE0OWM5Yzk1NjU4ZDM2MzNlM2Y3MjJmMWY0Yjk0MjAxOGNlYmVhZTdmMzMwZGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L-PjruyReuIc6Jn20QNLN1FeCrcFAWSF63cIr3XsKWM)
> 
> ![信息2](https://private-user-images.githubusercontent.com/158256530/301467533-45182823-ad47-491e-928d-e0016e0679b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTA2MTYsIm5iZiI6MTcwNjg1MDMxNiwicGF0aCI6Ii8xNTgyNTY1MzAvMzAxNDY3NTMzLTQ1MTgyODIzLWFkNDctNDkxZS05MjhkLWUwMDE2ZTA2NzliMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwNTA1MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDY4NDhlMzk1YzUxN2NjZDRiMWRhMzViMTBjNjFlZGI5YzhlOGFjZGQzZjM5N2ZkZWFiZTgxODc3YjEzNDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NKVZv6S6BK9OpaeEuSQfqBrH1ari8jEmsOCxDRz9wMk)

出现 `Microsoft-Windows-Kernel-Power` 一般就是：CPU/GPU 过热，CPU/GPU 供电不足，电源供电不稳定、电源过载
