### ISSUE TITLE
一个关于Linux运行MAA-GUI的想法

### ISSUE THREAD

**Issue by PianCat** [MaaAssistantArknights/MaaAssistantArknights#8119]
### 说说你遇到的问题？

通过利用Wine、Winetricks来安装.NET 8.0 Desktop Runtime
然后使用Wine来在Linux上运行MAA-Windows
一种很偏门但是可能有用的Linux获得GUI控制界面的方法
有人试过吗？

BTW：Proton或许也是可选项

**Comment by PianCat** [comment]
https://github.com/Winetricks/winetricks/pull/2179
隔壁在整dotnetdesktop8的支持
但是旧版的dotnetdesktop6可以用
不知道有没有人试一试

**Comment by Manicsteiner** [comment]
猜您在找：[MaaX](https://github.com/MaaAssistantArknights/MaaX)
折腾了一圈，还是没能在linuxmint上跑起来，感觉MaaX是运行权限问题，dotnet6版本是wine依赖有问题。
如果你想尝试Dotnet6版本的话可以用我自己用的Dotnet6版本 https://github.com/Manicsteiner/MaaAssistantArknights/releases
