### ISSUE TITLE
台服不识别弦惊

### ISSUE THREAD

**Issue by zxc173123** [MaaAssistantArknights/MaaAssistantArknights#8120]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述
能识别令但是识别不了令的弦惊
![QQ截图20240131174734](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56154254/77eb4620-9faa-41fc-9601-a746fcd216cd)

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14109910/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14109913/gui.log)

### 截图

![QQ截图20240131174517](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56154254/c54a5d4c-0b39-4f4c-97c9-c489db4a6045)

**Comment by Manicsteiner** [comment]
asst.bak.log 只截止至1月30日，请上传asst.log
根据已有的信息，弦惊的图片缓存已生成在 \cache\avatars\“弦惊”.png，即以前成功通过文字OCR识别过。建议先查看 \cache\avatars 目录下的所有图片缓存，删除文件名称和干员形象（含当前所用皮肤）不对应的所有图片缓存后重启MAA。

**Comment by Constrat** [comment]
Reopen when logs are sent.
