### ISSUE TITLE
“牛牛抽卡”无法使用限定池的每日赠送寻访机会抽卡

### ISSUE THREAD

**Issue by 3141592653589793238462643383279502884** [MaaAssistantArknights/MaaAssistantArknights#8127]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

“牛牛抽卡”无法使用限定池的每日赠送寻访机会抽卡

### Version

Resource Version: 登临意·复刻
UI Version: v5.0.0-beta.2
Core Version: v5.0.0-beta.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14125199/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14125202/gui.log)

### 截图

<img width="641" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56119112/503d3e7f-9642-466b-98e4-9c529bdcd69f">
![Screenshot_20240201-201946](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56119112/bb9a6611-e65e-4828-bd5d-9c2ee35cd4a5)
<img width="641" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56119112/44cd2130-4695-45ea-91b5-a5304885850f">

**Comment by ABA2396** [comment]
@status102 来瞅瞅这张图能不能截成只有一个勾
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/5c163434-1bff-4682-ab86-1bc302d14c9a)
