### ISSUE TITLE
肉鸽如果不pin到主页识别不了

### ISSUE THREAD

**Issue by huailo** [MaaAssistantArknights/MaaAssistantArknights#8128]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

肉鸽页面改了，只有pin在主页并且主题对应才好用，否则会卡死

### Version

Core Version: v5.0.0-beta.2.d027.gb56eaa948

### 日志文件

[asst.log](https://github.com/MaaAs
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14125451/gui.log)
sistantArknights/MaaAssistantArknights/files/14125445/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/82349739/dcc22646-09a2-400d-9404-b0f43de23fa6)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/82349739/7ad8d9d6-7d49-4197-89aa-889c1b0d8b4f)

### 还有别的吗？

日志是pin水月maa萨米的结果 上传前清了以前的方便查看

**Comment by status102** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/161f474b-591f-4170-947f-3044ecc4a624)
