### ISSUE TITLE
蓝叠国际版无法正常使用

### ISSUE THREAD

**Issue by PianCat** [MaaAssistantArknights/MaaAssistantArknights#813]
![Snipaste_2022-06-09_23-54-33](https://user-images.githubusercontent.com/50688679/172891261-7f5f410c-f832-4272-adbc-8640a8745671.png)
蓝叠国际版 Pie 64 Beta下，使用ADB端口以及蓝叠模拟器模式（将ADB设置为蓝叠目录下的HD-Adb）进行连接后无法正常继续操作，卡在Start Up这一步
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8871953/asst.log)

**Comment by nvkou** [comment]
看起来是截图失败。没蓝叠。等玛丽

**Comment by Kagura-Nanaa** [comment]
一样的bug

**Comment by MistEO** [comment]
奇怪我明明用 select 加了超时了 orz

晚上我去试试蓝叠 Pie 的

**Comment by MistEO** [comment]
> 一样的bug

你也是 蓝叠 Pie 么

**Comment by recgo** [comment]
一样的问题，蓝叠国际版 Pie 64无法使用，可以启动游戏但后面的开始唤醒什么的都没有反应。连接Nougat64的就可以正常用。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8876106/asst.log)
