### ISSUE TITLE
720P下关卡名识别错误

### ISSUE THREAD

**Issue by jiafjioajfijaiofnkan** [MaaAssistantArknights/MaaAssistantArknights#8132]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

720P分辨率下，活动被识别成`怀委离`。
尝试更改tasks.json为如下：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/152603055/d2a76b98-a693-424e-9a21-eda0f784fe29)
依旧报错：
```
[2024-02-02 00:24:28.108][TRC][Px23a0][Tx6174] asst::WordOcr [{ 怀委离>活动已开放: [ 111, 42, 170, 18 ], score: 0.884888 }, { : [ 391, 37, 44, 58 ], score: 0.000000 }, { 5/O: [ 33, 63, 31, 13 ], score: 0.896232 }, { 20天: [ 5, 89, 71, 19 ], score: 0.942741 }] by OCR Pipeline , cost 250 ms
```

### Version

Core Version: v5.0.0-beta.2.d033.gf6ffd5ea8

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14128162/asst.log)

### 还有别的吗？

MUMU12模拟器，720P分辨率

**Comment by jiafjioajfijaiofnkan** [comment]
好了，之前只改了resource文件夹下的，连cache/resource下的也改了就好了。

**Comment by ABA2396** [comment]
https://maa.plus/docs/%E5%8D%8F%E8%AE%AE%E6%96%87%E6%A1%A3/%E4%BB%BB%E5%8A%A1%E6%B5%81%E7%A8%8B%E5%8D%8F%E8%AE%AE.html
加ocrReplace，别直接改text
