### ISSUE TITLE
MAA出现了未知错误

### ISSUE THREAD

**Issue by MUzyx** [MaaAssistantArknights/MaaAssistantArknights#8135]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

弹窗提示Object reference not set to an instance of an object.

### Version

MAAComponent-OTA-v5.0.0-beta.2.d027.gb56eaa948_v5.0.0-beta.2.d034.gd520dad86-win-x64

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14130348/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14130357/asst.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125632753/b01e169c-ce2d-47f7-b6fe-3d30065ae4d7)

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125632753/7315f250-698a-4678-9ada-777a13c7cdf6)

**Comment by MUzyx** [comment]
自动更新到如图版本，然后就报错了.....重试了几遍，依旧报错
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125632753/db329b80-4061-4527-bedb-2927783b48a3)

**Comment by MUzyx** [comment]
绷不住了，手动解压完压缩包的内容然后覆盖后就更新成功能正常启动了，所以说这修复自动更新报错修复的是个榔头🔨🔨🔨

**Comment by MUzyx** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125632753/54c3bdaa-6af1-4290-be72-876549434c04)
现在又无限开始任务出错了......

**Comment by MUzyx** [comment]
显示为识别错误

**Comment by Constrat** [comment]
It's in the pinned issues. You did not check the pinned issues. Don't open duplicates.

**Comment by Constrat** [comment]
Duplicate of #8129

**Comment by ABA2396** [comment]
> 绷不住了，手动解压完压缩包的内容然后覆盖后就更新成功能正常启动了，所以说这修复自动更新报错修复的是个榔头🔨🔨🔨
> 

修的就是你这个版本用不了自动更新，新版本能自动更新和你这个版本不能自动更新有什么关系吗
