### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by LBacteria** [MaaAssistantArknights/MaaAssistantArknights#8137]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

打开就报错，重启无效

### Version

打不开软件，无法查看，但是昨天晚上开活动之后还是能用的

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14132316/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14132318/gui.log)

**Comment by status102** [comment]
#8129
