### ISSUE TITLE
追加指定干员无法识别新干员黍

### ISSUE THREAD

**Issue by hanpeiyuan26** [MaaAssistantArknights/MaaAssistantArknights#8139]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在自动战斗-作业路径下，勾选自动编队-追加指定干员时，无法正确识别新干员黍，但小满等新干员可正确识别。实测使用小工具-干员识别也无法识别新干员黍

### Version

Core Version: v5.0.0-beta.2.d027.gb56eaa948

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14132984/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14132986/gui.log)

### 截图

![I6CXDF8 )FT7_LBTSP4@SN](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/126241221/f2318943-4678-4b9e-9c04-0994eb941fff)
![O$J9YQA`DHJ94)CQUJ`P(CJ](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/126241221/903ead08-c37d-4112-9f65-0d1bac4d63be)
![CZUZO_V58ES9L4`J07)}TNB](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/126241221/ba1acf82-d1c3-4c9b-b1b5-52dd7efd4583)

**Comment by ABA2396** [comment]
![8607e238be8e7111b249b19f2e553d6d](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/69cb9ce4-f940-4a47-b48b-ac3f6d3c2488)
连文字都没识别到，我试了下720和1080p都可以识别到，先调低下分辨率看看这个有没有影响
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/419438a9-6add-4252-bf21-14f07f17f5f8)
