### ISSUE TITLE
更新BUG

### ISSUE THREAD

**Issue by 2572190756** [MaaAssistantArknights/MaaAssistantArknights#8140]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

<img width="1012" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74443980/013ea853-1254-4b54-b977-3cae934030f7">

MAA在更新时出现此错误

### Version

MAA打不开了 ，无法查看版本

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14133061/debug.zip)
.

### 还有别的吗？

雷电模拟器， win11

**Comment by ABA2396** [comment]
到现在都还没装.net8还在用MAA_win7吗

**Comment by 2572190756** [comment]
> 到现在都还没装.net8还在用MAA_win7吗

<img width="933" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74443980/28a4942c-1c9a-4586-9b0a-dcad153653c6">

**Comment by ABA2396** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8129
