### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by 6AdnaP9** [MaaAssistantArknights/MaaAssistantArknights#8142]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

2024.02.02十点半刚自动更新就出错了

### Version

应该是从测试版？昨天就能打新本了

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14133506/gui.log)
2024-02-02 10：40左右

**Comment by 6AdnaP9** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14133520/asst.log)

**Comment by ABA2396** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8129
