### ISSUE TITLE
新版本下载能否有进度显示

### ISSUE THREAD

**Issue by lz0709** [MaaAssistantArknights/MaaAssistantArknights#815]
请问可以在软件内aria下载新版本的时候，增加一个大概的进度下载显示吗，每一次新版本下载的时候都因为许久没有下好而怀疑下载出错，最后还是自己到github下载

**Comment by forgiveme0** [comment]
确实确实，我刚想反馈这个问题，就看见你已经说了

**Comment by MistEO** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/727
