### ISSUE TITLE
怀黍离相关关卡自动战斗无法使用

### ISSUE THREAD

**Issue by astatine-213** [MaaAssistantArknights/MaaAssistantArknights#8155]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

直接引用的MAA copilot链接或者下载好的JSON文件均无法使用，提示“读取文件失败！”“不支持的关卡，请检查关卡名！”
使用JSON时：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43698118/09247e77-fddf-4280-8afa-7601903d67b4)
使用链接时：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43698118/54d87ee2-24c7-4749-aa0a-81bc3f397fa1)

已经点击过“检查更新”按钮，提示：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43698118/da182999-04f2-475d-be1c-97e999d476b3)

已尝试过重启电脑、重启应用，均无效

### Version

资源版本号：登临意·复刻
UI版本号：v4.28.8
Core版本号：v4.28.8
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43698118/b727af7b-6d08-45ff-aa6d-f1159d31eb27)

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14136775/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14136776/asst.log)

**Comment by status102** [comment]
临时解决方案：找到config/gui.json下的
VersionUpdate.ResourceApi
删除字段，打开MAA，重新检查资源更新

**Comment by CaliInn-Li** [comment]
> 临时解决方案：找到config/gui.json下的 VersionUpdate.ResourceApi 删除字段，打开MAA，重新检查资源更新

删除以后检查更新的按钮就禁用了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40906144/db336347-85af-4917-881d-9871c2ecea92)

**Comment by ABA2396** [comment]
现在可以了，重启重新检查下更新
