### ISSUE TITLE
更新后出现异常

### ISSUE THREAD

**Issue by 1902520039** [MaaAssistantArknights/MaaAssistantArknights#8158]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

大概是在2024/2/2 16：25分左右打开MAA，自动更新，瞥了一眼看到了“修复自动更新报错，虽然报错的人也更新不了”的字样。然后在自动更新完成后就无法打开。
显示：Object reference not set to an instance of an object.     解决方案：出现未知错误

### Version

无法打开不知道

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14137398/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14137399/gui.log)
大概是在16：25分打开的，就自动更新了。

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52557812/6570c8c5-acb4-4901-bda2-9cf15a760a46)

### 还有别的吗？

OS:WIN10

**Comment by 1902520039** [comment]
重新下载并安装，更新后已修复

**Comment by Qboter** [comment]
版本为最新版内测：v5.0.0-beta.2.d034.gd520dad86
回退至公测v5.0.0-beta.2目前正常
错误是一样的，系统版本为Win11专业版22H2

**Comment by ABA2396** [comment]
> 版本为最新版内测：v5.0.0-beta.2.d034.gd520dad86 回退至公测v5.0.0-beta.2目前正常 错误是一样的，系统版本为Win11专业版22H2

d034是没问题的，有问题的是d027和d032，这两个版本走不到安装更新包的那一步
