### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by Evelyntly** [MaaAssistantArknights/MaaAssistantArknights#8160]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

启动失败

### Version

v5.0.0-beta.2.d027.gb56eaa948_v5.0.0-beta.2.d034.gd520dad86

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14137870/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14137872/gui.log)

### 截图

![屏幕截图 2024-02-02 170914](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131582847/d83edd01-fc24-4d27-a3ed-a579462f76e5)
![屏幕截图 2024-02-02 170939](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131582847/41ad0340-adc6-4fe5-80e7-800fb6e90759)

**Comment by ABA2396** [comment]
#8129
