### ISSUE TITLE
萨米肉鸽安全的角落没有抗干扰指数一直在点击使用而不选择下一关

### ISSUE THREAD

**Issue by Icesowrd** [MaaAssistantArknights/MaaAssistantArknights#8162]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽到了安全角落之后，没有抗干扰指数一直点击使用卡关，不自动选择后面关卡

### Version

Resource Version: 千秋一粟
UI Version: v4.28.8
Core Version: v4.28.8

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14139099/gui.log)

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14139137/asst.zip)

2024/2/2 18.57.00-18.57.51

### 截图

![e3b396d62b4640a7b1325ce305cae973](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/132558984/cebbbaaa-f9e0-4dd6-a297-bafaf67321f3)

**Comment by SherkeyXD** [comment]
Link to #7800

**Comment by Icesowrd** [comment]
能否加个当前关卡重复多少次自动选择另外一条分支或者放弃这次探索来解决这个呢

**Comment by SherkeyXD** [comment]
> 能否加个当前关卡重复多少次自动选择另外一条分支或者放弃这次探索来解决这个呢

这个 #7904 其实写了 但是那个pr现在烂尾了（

**Comment by ABA2396** [comment]
> > 能否加个当前关卡重复多少次自动选择另外一条分支或者放弃这次探索来解决这个呢
> 
> 这个 #7904 其实写了 但是那个pr现在烂尾了（

已经可以用了，但是先发正式版

**Comment by ABA2396** [comment]
之后要做的是做事件识别，至少现在估计抗干扰选第几个是可以做到了，卡住了也会从下往上选一遍

**Comment by Icesowrd** [comment]
感谢修正
