### ISSUE TITLE
mac版playcover能否更新一个基于nightly 623或后续版本的版本？

### ISSUE THREAD

**Issue by uesakayou** [MaaAssistantArknights/MaaAssistantArknights#8164]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在mac os版本更新之后，部分ipa安装会出现报错，为了解决这一问题，playcover更新了nightly 623版本（明日方舟不会报错，但是有其他需要的ipa会）
但是更新官方的playcover导致无法在原生明日方舟上使用maa了，只能暂时用mumu pro模拟器（但是试用7天之后就要钱）
希望能更新一下，谢谢

**Comment by Zer0zaki** [comment]
请问哪里有最新版的脱壳ipa啊

**Comment by uesakayou** [comment]
> 请问哪里有最新版的脱壳ipa啊

度盘/s/1kF7nKFJ6BdLZcByUcFzpzA?pwd=xjr7

**Comment by Zer0zaki** [comment]
感谢楼上。请问有mac玩家的社区或者群吗

**Comment by uesakayou** [comment]
> 感谢楼上。请问有mac玩家的社区或者群吗

这我就不知道了

**Comment by Argonautes0607** [comment]
playcover可以添加https://decrypt.day/library，或者去https://decrypt.day/上搜，每次更新很快就有人砸壳上传

**Comment by uesakayou** [comment]
> playcover的ipa资源库可以添加 https://decrypt.day/library ，或者去 https://decrypt.day/ 上搜，每次更新很快就有人砸壳上传

这次的8小时前才更新，所以才有人问（

**Comment by Zer0zaki** [comment]
> > playcover的ipa资源库可以添加 https://decrypt.day/library ，或者去 https://decrypt.day/ 上搜，每次更新很快就有人砸壳上传
> 
> 这次的8小时前才更新，所以才有人问（

确实。感谢您
