### ISSUE TITLE
自动战斗 无法识别的关卡

### ISSUE THREAD

**Issue by AEDELSTAN** [MaaAssistantArknights/MaaAssistantArknights#8165]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，无法使用新活动HS的作业
蓝叠国际

另外请求，加一个强制进行作业的操作😂

### Version

Resource Version: 千秋一粟
UI Version: DEBUG VERSION
Core Version: v5.0.0-beta.2.d034.gd520dad86

### 日志文件

应该就是最新的那部分
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14140339/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14140342/asst.log)

**Comment by ABA2396** [comment]
你这用的啥作业，连关卡名都没有

**Comment by ABA2396** [comment]
\resource\Arknights-Tile-Pos文件夹里没有act31side_04-activities-act31side-level_act31side_04.json这个文件吗

**Comment by status102** [comment]
上传一下作业文件 / 使用的作业代码

**Comment by status102** [comment]
> 另外请求，加一个强制进行作业的操作

强制也没用，现在是读不到地图，就算开始了也下不对干员位置

**Comment by AEDELSTAN** [comment]
> 你这用的啥作业，连关卡名都没有

抱歉没有说详细，我昨天用hs-4所有的作业都不能开始。以前游戏更新 新地图，那些作业前几天我也是不能用，过了几天再试才可以正常开始。这种情况有3、4次了吧

**Comment by AEDELSTAN** [comment]
> 你这用的啥作业，连关卡名都没有

刚刚重装了，也是发现原因了
应该是昨天，maa自动更新了一个内测版本，导致崩溃打不开。然后我就去下载了最新的zip，直接覆盖maa目录。
刚刚发现在这通操作之后，打开maa不会自动更新游戏数据了，设置里也找不到手动更新游戏数据，于是重新下了个maa，现在是可以正常运行了
