### ISSUE TITLE
Object reference not set to an instance of an object.  出现未知错误

### ISSUE THREAD

**Issue by ThymeNK** [MaaAssistantArknights/MaaAssistantArknights#8167]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

24/02/02 22:06 更新后无法打开，如截图所示

### Version

24/02/02 22:06 更新后无法打开查看版本

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14141101/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14141102/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/79644707/6479330d-4f52-4d99-a7e9-8ede2f9e44d1)

**Comment by IsabellaC0504** [comment]
遇到同样问题

**Comment by Patch0uli** [comment]
遇到同样问题

**Comment by Rbqwow** [comment]
#8129
不看说明建议别用内测版

**Comment by IsabellaC0504** [comment]
> #8129 不看说明建议别用内测版

谢谢
