### ISSUE TITLE
MAA 遇到了问题。（无法打开GUI界面）

### ISSUE THREAD

**Issue by ZB052-A** [MaaAssistantArknights/MaaAssistantArknights#8169]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新后就打不开了。

### Version

v5.0.0-beta.2.d034.gd520dad86

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14141815/gui.log)

### 还有别的吗？

是内测更新后GUI出问题了好像是。
操作系统：Win11 22H2
模拟器：蓝叠4

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/12c4b9bb-bccc-443b-ab70-6752730484e4)
