### ISSUE TITLE
开机自启动卡死

### ISSUE THREAD

**Issue by ability66** [MaaAssistantArknights/MaaAssistantArknights#817]
![image](https://user-images.githubusercontent.com/106503132/172979318-00620961-a129-4c46-b05d-d5fee6ce6cca.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8875337/asst.log)

**Comment by MistEO** [comment]
v3.9.5 修复了，更新下看看

**Comment by ability66** [comment]
现在变成这样了
![image](https://user-images.githubusercontent.com/106503132/172980712-fcee3727-c5a5-431c-95d6-83144005ad7e.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8875390/asst.log)

**Comment by MistEO** [comment]
> 现在变成这样了 ![image](https://user-images.githubusercontent.com/106503132/172980712-fcee3727-c5a5-431c-95d6-83144005ad7e.png) [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8875390/asst.log)

你要选择客户端版本的，MAA 的启动设置里

**Comment by ability66** [comment]
嗷嗷，谢谢

**Comment by MistEO** [comment]
没问题我就关咯~
