### ISSUE TITLE
v5.0.0-beta.2.d027至v5.0.0-beta,2.d032版本自动更新功能出错，需要手动解压升级包

### ISSUE THREAD

**Issue by 0124li** [MaaAssistantArknights/MaaAssistantArknights#8173]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

可正常下载增量包重启解压报错
删除下载的增量包后可正常启动并再次下载增量包
重启后再次解压报错

### Version

v5.0.0-beta.2.d027.gb56eaa948
更新至
v5.0.0-beta.2.d032.g1bc32ff06

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14145060/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14145061/gui.log)

**Comment by Rbqwow** [comment]
？

**Comment by status102** [comment]
duplicate of #8129
