### ISSUE TITLE
自动战斗请求网络服务错误

### ISSUE THREAD

**Issue by xingkong662** [MaaAssistantArknights/MaaAssistantArknights#8174]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动战斗请求网络服务错误，使用json读取文件失败。
检查更新获取更新失败。

### Version

Resource Version: 跨年欢庆·展望
UI Version: v4.28.8
Core Version: v4.28.8

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14149009/gui.log)

### 截图

![23T%X)(KF D9I__K2VBJKM](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/158647304/012e9713-235b-4a09-8a96-8b0cbfbf4637)
![E6({1}MTM`F S33 A(K)1D6](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/158647304/26e31b4b-bbb8-4b85-8d5a-1c6b68d7d539)
![YIS001NSVW5A_ZFE~MJAYSK](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/158647304/ed2307ad-9045-4e79-9fbd-af181d22fecb)

### 还有别的吗？

mumu12
win10

**Comment by ABA2396** [comment]
Resource Version版本不对，都没到最新的活动

**Comment by xingkong662** [comment]
下载最新版之后还是出现相同问题

**Comment by xingkong662** [comment]
自动战斗使用json可以正常使用，神秘代码仍是请求网络服务错误
点击更新后仍是获取更新信息失败

**Comment by xingkong662** [comment]
在官网下载最新版之后，自动战斗使用json可以正常使用，神秘代码仍是请求网络服务错误
点击更新后仍是获取更新信息失败

**Comment by xingkong662** [comment]
[Uploading gui.log…]()

**Comment by xingkong662** [comment]
[Uploading gui.log…]()

**Comment by ABA2396** [comment]
看日志所有联网操作都被拦截了，有设过防火墙规则什么的吗
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/90ec6076-564b-4d59-baf4-efbf2b6764e2)

**Comment by xingkong662** [comment]
是的，找到问题并解决问题了。谢谢大佬的提供的帮助。
