### ISSUE TITLE
基建换班能否增加禁用训练室的选项？

### ISSUE THREAD

**Issue by Mudrockiii** [MaaAssistantArknights/MaaAssistantArknights#8179]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有时候我会使用艾丽妮进行专精，能否增加禁用训练室换班来让我自己进行更换。
我使用的是5.0版本，公测，模拟器是最新的mumu。

### 其他内容

![QQ拼音截图未命名](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110472431/287a76c4-08cb-4ea3-ad03-53ce32f07bd6)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/22c77552-13b2-47ea-80a0-1ae890467eed)
