### ISSUE TITLE
ADB无法连接

### ISSUE THREAD

**Issue by 147551866** [MaaAssistantArknights/MaaAssistantArknights#8183]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14150905/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14150906/gui.log)
MAA没法自动打开mumu12模拟器，显示adb连接失败，但是如果模拟器开着的话再点link就可以正常使用，我用cmd的adb connect 127.0.0.1:16384命令，开着模拟器就可以正常连接，没开模拟器也没法连，显示 由于目标计算机积极拒绝，无法连接(10061)，是不是mumu12没开模拟器的话这个端口就不监听啊？

**Comment by 147551866** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/48267371/fe7ef3ef-3779-4067-aefa-fd95df1a5ff6)
补一张图

**Comment by ABA2396** [comment]
没开哪来的端口给你连

自动开模拟器在这里
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/c508e3df-85f6-4802-a268-17bdf806cbca)
或者
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/671bf475-4a01-493e-9fec-d92bb3ef3054)
