### ISSUE TITLE
自动肉鸽没有反应，显示截图用时较长，使用自动类功能出现异常

### ISSUE THREAD

**Issue by lx159xl** [MaaAssistantArknights/MaaAssistantArknights#8186]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新5.0版本后自动肉鸽无法运行，一直卡在终端界面，之前可以

### Version

Resource Version: 千秋一粟
UI Version: v5.0.0
Core Version: v5.0.0

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14151203/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14151209/asst.zip)
时间2.3

### 截图

![屏幕截图 2024-02-03 193616](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/128458272/8f05abcf-f740-496f-b190-5eab6a96c519)

### 还有别的吗？

mumu12
x64

**Comment by ABA2396** [comment]
肉鸽入口变了，现在还没写新逻辑，如果你终端界面东西太多了肉鸽不在里面是找不到的

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/22d422cc-2b31-4fce-ba35-20d6db94f004)
没改之前要在这里才能找到
