### ISSUE TITLE
自动战斗自动开技能 在没有后续任务的时候不会开技能

### ISSUE THREAD

**Issue by zaiziw** [MaaAssistantArknights/MaaAssistantArknights#819]
举例以下作业
[LE-8（带镀层）_老鲤+山+棘刺+流明.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8875807/LE-8._.%2B.%2B.%2B.zip)
在没有添加尾部11杀切换二倍速时
在部署完老鲤之后任务结束，接下来流明和棘刺的技能好了却不会放
在添加了尾部11杀切换二倍速后，流明和棘刺的技能好了正常释放

**Comment by ABA2396** [comment]
这个确实，在考虑加个DoNothing字段解决这个问题
