### ISSUE TITLE
V5.0启动问题

### ISSUE THREAD

**Issue by Ranyang-Zhou** [MaaAssistantArknights/MaaAssistantArknights#8192]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

已经安装NET 8.0前提下，不管是直接启动还是管理员启动，maa.exe没有反应（既没有报错，也没有启动）

### Version

MAA winx64 V5.00

### 日志文件

无

**Comment by ABA2396** [comment]
文件夹里重新下一个完整包试试，就算打不开应该也会创建几个文件
