### ISSUE TITLE
不勾选“重要信息弹出系统通知”依然弹出系统通知

### ISSUE THREAD

**Issue by Immueggpain** [MaaAssistantArknights/MaaAssistantArknights#8193]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

不勾选“重要信息弹出系统通知”依然弹出系统通知。比如完成一键长草后。

### Version

Resource Version: ????
UI Version: v5.0.0
Core Version: v5.0.0

（复制过来就是问号）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14151763/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14151764/gui.log)
一键长草后，大概21点10分？

**Comment by ABA2396** [comment]
89c5788325db3871cf7d3e064dcaf79eed21d484 fixed

但资源版本为啥会显示???)

**Comment by Immueggpain** [comment]
> [89c5788](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/89c5788325db3871cf7d3e064dcaf79eed21d484) fixed
> 
> 但资源版本为啥会显示???)

@ABA2396  应该是这个原因： #8204
