### ISSUE TITLE
日服 作战模式 慑砂被认定为冷却中而跳过识别

### ISSUE THREAD

**Issue by Manicsteiner** [MaaAssistantArknights/MaaAssistantArknights#8195]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

干员 慑砂/Sesa/シェーシャ
不是文本识别问题，而是在第一次识别时直接跳过该干员，后两次尝试识别unknown oper时也是直接暂停后继续，不点开此干员。日志显示识别为cooling oper。我认为此问题可能同样存在于其他服务器。
测试时每次启动MAA前会清空cache/avatars目录。

### Version

v5.0.0 同版本 Debug build

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14151844/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14151845/gui.log)
line 970~1364, 2883~3276

### 截图

![Screenshot_1706970996](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/0ff90972-d0f4-48ad-b361-ac779c2c5fd2)
![OF-1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/cce48c0b-f455-4241-89da-7a74b101eead)

**Comment by Manicsteiner** [comment]
在初始费用足够的SL-MO-1测试了一下，能够识别，我怀疑是费用不足时较暗加脸黑的问题
这次没清avatars
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14151990/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14151991/asst.log)
![慑砂](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/130c157e-6f77-4858-9c52-17b092bcbada)
![Screenshot_1706973996](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/86b679e2-f627-4e73-9464-506dfed16da1)

**Comment by ABA2396** [comment]
草，cooling 好像就是根据颜色判断的，这一圈红头发和cooling的时候好像

**Comment by Manicsteiner** [comment]
E2沙子哥也不认
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14155211/asst.log)
2024-02-04 10:09 起
![Screenshot_1707012589](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/5fbe9d30-6b9a-4bc7-b7a4-82ab375c13df)

**Comment by Manicsteiner** [comment]
fixed by https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1a65cd840bb38059c73e6424178f5653d38a6d08
