### ISSUE TITLE
使用MAA自动萨米肉鸽，必定黑屏重启

### ISSUE THREAD

**Issue by rfvb1599** [MaaAssistantArknights/MaaAssistantArknights#8196]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在开启自动肉鸽后不到两分钟必定自动黑屏重启，debug\rouguelike中并未记录该错误的截图，电脑烤甜甜圈几次并未发现问题，上个月使用时并未出现该问题

### Version

Resource Version: 怀黍离v2.2.01
UI Version: v5.0.0
Core Version: v5.0.0
使用的模拟器为雷电模拟器V90.61(9)
系统是Windows10

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14151898/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14151899/gui.log)

**Comment by Rbqwow** [comment]
如果是因为CPU占用 那内测版已提供GPU加速功能 同时添加了最小截图间隔 已经优化CPU占用
这种问题得看系统的事件查看器 不过八成是运气不好cpu体质差
(maa的突发占用是比烤机猛的
