### ISSUE TITLE
下载最新版后，无法自启动

### ISSUE THREAD

**Issue by WT70** [MaaAssistantArknights/MaaAssistantArknights#8201]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新版本后，无法使用自启动，根据公告的方法删了文件重新选项也没用

### Version

Resource Version: 千秋一粟
UI Version: v5.0.0
Core Version: v5.0.0

### 日志文件

![屏幕截图 2024-02-04 023726](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/158768038/c046876e-7bbb-41bb-b7b7-0860a029ac8b)

### 截图

![屏幕截图 2024-02-04 023846](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/158768038/c46c2fa3-8cd3-474c-abdd-3b5613be2a54)
·
![屏幕截图 2024-02-04 023821](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/158768038/6b4b5892-e51f-4db3-af20-8f0aca402bee)
![屏幕截图 2024-02-04 023800](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/158768038/dfba22fc-f33e-4b5b-8806-6c963df47227)

**Comment by SherkeyXD** [comment]
【【公告】关于.net8版本更新后开机自启设置问题解决方案-哔哩哔哩】 https://b23.tv/UmtcpvJ

**Comment by WT70** [comment]
> 【公告】关于.net8版本更新后开机自启设置问题解决方案-哔哩哔哩】 https://b23.tv/UmtcpvJ
> 
> 你这没删除带maa的项啊

这个是已经删除过重新勾选后的了

**Comment by ABA2396** [comment]
所以注册表里的罗技 百度云 steam edge都有开机自启吗？感觉是被别的软件拦截了

**Comment by WT70** [comment]
> 所以注册表里的罗技 百度云 steam edge都有开机自启吗？感觉是被别的软件拦截了

关闭大部分其他自启动应用后依旧没用
