### ISSUE TITLE
自动肉鸽在傀影肉鸽中会卡在“以血还血”事件

### ISSUE THREAD

**Issue by NorthernStar0186** [MaaAssistantArknights/MaaAssistantArknights#8203]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动肉鸽功能打傀影肉鸽的时候，一旦遇到“以血还血”事件就会一直尝试第一与第二个选项，即便不满足要求（没有“友谊之证”或足够目标生命）也不会选择第三个选项，导致自动肉鸽会一直卡在这里，直到我手动选择

### Version

Resource Version: 千秋一栗
UI Version: v5.0.0
Core Version: v5.0.0

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14154224/asst.zip)

### 截图

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131336622/1e991a59-232b-49cd-8355-cd055568670b)

**Comment by Mou-Froski** [comment]
我也是，没有友谊之证，血不够2点，maa只会尝试选需要友谊之证的选项，连扣血选项都不看。
b站视频：BV1Fu4m1N7Z4

**Comment by ABA2396** [comment]
等 #7904 合了应该就好了

**Comment by DCxDESIGN** [comment]
我使用的是当前的最新内测版 (https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/alpha%2Fv5.1.1-alpha.1.d010.g6c79ff49e )，遇到了同样的问题，到选择界面就一直卡住不动了

![SShot-20240216-140603-NemuPlayer](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/48208459/fd1ee913-4c97-404c-8a38-eb225fc21d1e)

日志： [240216.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14307789/240216.zip)

所以 #7904 是还没合并对吧
