### ISSUE TITLE
MAA 5.0版本一直提示“连接失败 正在尝试重启ADB Server”

### ISSUE THREAD

**Issue by Derekzhym** [MaaAssistantArknights/MaaAssistantArknights#8209]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

反复报错几次后提示“连接失败 请检查连接设置或尝试重启模拟器与ADB或重启电脑”，但无论是重启电脑，重装MAA，还是重启模拟器，都无法解决问题。

### Version

稳定版本5.0.0和内测版本5.1.0均出现此问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14155339/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14155340/gui.log)

### 截图

![微信截图_20240204112052](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62647576/5ba3bee4-12ff-4423-b737-b61e84d44aaf)

**Comment by Yucheng-Z** [comment]
同样问题

**Comment by ABA2396** [comment]
error: protocol fault (couldn't read status): connection reset

检查adb要用的5037端口是否被其他软件占用，如xx手机助手

cmd下可以用 netstat -aon|findstr "5037" 查找占用的软件及pid

**Comment by TowardsXY** [comment]
> error: protocol fault (couldn't read status): connection reset
> 
> 尝试在任务管理器中重启adb.exe；是否在连接前后使用过游戏加速器之类的软件，如uu加速器；检查adb要用的5037端口是否被其他软件占用，如xx手机助手
> 
> cmd下可以用 netstat -aon|findstr "5037" 查找占用的软件及pid

检查过任务管理器，没有adb.exe的进程，在cmd中也核实了5037端口未被占用，然后还是无法连接上adb

**Comment by foreverlong** [comment]
同样的问题，一直没有解决，而且重启一下就好，有时候重启也好不了，时好时坏

**Comment by ABA2396** [comment]
那就去找模拟器客服吧，这里问没用了。adb是模拟器或者谷歌提供的，adb连不上模拟器maa也没办法

**Comment by Yucheng-Z** [comment]
我已经解决了，首先我重新卸载了模拟器重新下载了原来是用的版本较旧的蓝叠，假期回来更新之后就遭遇了该问题，于是卸载换了新版本的mumu，正好也已经支持多端口了。其次我检查了一下系统路径，发现以前保存了maa自带的adb.exe的路径和maa自动使用的模拟器内置adb路径不是同一个，不知道是否因此导致了某种bug，于是将adb从系统路径中删除了。之后再次启动并没有遇到该问题。希望有参考价值。
