### ISSUE TITLE
一鍵長草中的開始喚醒功能 繁中版需要選擇facebook或google登入的功能

### ISSUE THREAD

**Issue by rockmantay1** [MaaAssistantArknights/MaaAssistantArknights#8212]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

繁中版的登入有時效 
時間過了會自動登出 卡在選擇facebook登入或google登入的畫面

### 有什么好的想法？

在一鍵長草添加這個畫面的自動截圖辨識

### 其他内容

貼圖尺寸 1280*720
![Screenshot_20240204-132101](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55077005/025e0376-819d-434a-a711-f96bbfd27120)

**Comment by status102** [comment]
Duplicate of #7832
