### ISSUE TITLE
生息演算最后的“删除存档”操作无限循环点击无法继续

### ISSUE THREAD

**Issue by qshcjn1** [MaaAssistantArknights/MaaAssistantArknights#8213]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

生息演算到了最后“删除存档”的地方会无限循环卡在这里。
其他功能均正常使用。

### Version

v5.1.0-beta.1（462），已测试用最新beta版本（由于只有win版）resource文件夹替换软件包内resource文件夹，问题依然存在。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14155734/asst.log)

时间大概13点50分之前，视频录制后未进行太多操作，应该接近log文件尾段
Mac电脑的debug文件夹内没有找到gui.log文件

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/158798596/e4cfbe77-1bc8-4787-9340-daa225d7e82b

### 还有别的吗？

计算机：M2芯片Mac台式机
模拟器环境：PlayCover

**Comment by uesakayou** [comment]
我也有这个问题，有时候会触发有时候不会，概率很高

**Comment by ABA2396** [comment]
> 我也有这个问题，有时候会触发有时候不会，概率很高

遇到问题发日志，而不是说一句我也遇到了就能解决问题

**Comment by uesakayou** [comment]
> > 我也有这个问题，有时候会触发有时候不会，概率很高
> 
> 遇到问题发日志，而不是说一句我也遇到了就能解决问题

您好，不慎冒犯到您非常抱歉，个人考虑到是同一个环境下遇到同一个问题我就没有再发一个issue了，在下面回复只是之前学来的陋习，以后尽量避免。
我十分感谢各位作出的贡献，也希望maa能越做越好。
最后，既然提到发日志，我就顺便提一句，我#7558的issue去年12月13日发布，至今无人回应，类似的问题至今仍然存在，宿舍换班的结果不尽人意，每次基建换班之后我都需要手动重新换一遍宿舍的干员。
