### ISSUE TITLE
生息演算删除存档重开后，强制对话部分报错并停止运行

### ISSUE THREAD

**Issue by FengYaHe** [MaaAssistantArknights/MaaAssistantArknights#8219]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在删除存档后进入地图，会遇到强制对话部分，之后分以下三种情况：
1、在森蚺要求进入后舍的界面停住，等待一段时间后maa报错退出（见视频）；
2、进入后舍之后触发对话，在对话的第一句停住（见截图），等待一段时间后maa报错退出；
*3、进入后舍之后触发对话，在对话的第一句停住，**迅速手动进行完所有的对话操作**，森蚺和图耶离开地图后，maa可以识别到退出按钮并正常继续运行；
不知道可否在进入后舍后，等待短暂一段时间，并执行在屏幕右侧对话按钮部分连续点击一定次数，以跳过初始强制对话，直至可以识别到退出按钮？
![Screenshot_20240204-160754](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/93574211/2441b146-db2c-4906-8793-c08c5f48e2c8)

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/93574211/bf3e8a7c-7c0b-4a40-9a4c-1a25d6f1e447

### Version

Resource Version: 千秋一粟
UI Version: DEBUG VERSION
Core Version: v5.1.0-beta.1.d002.gc17c7e5ac

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14156056/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14156058/gui.log)

### 截图

![Screenshot_20240204-160754](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/93574211/476ec32b-ac1c-4da3-8634-4343b97e43c3)

**Comment by ABA2396** [comment]
0ba66601d59308dc7aec2eabebefdb625cf74a9a fixed
