### ISSUE TITLE
目前自动启动不支持多开（蓝叠模拟器国际版）

### ISSUE THREAD

**Issue by yh4231** [MaaAssistantArknights/MaaAssistantArknights#822]
蓝叠模拟器国际版。

方舟装在了多开实例01里，快捷方式如下（地址1）
"C:\Program Files\BlueStacks_nxt\HD-Player.exe" --instance Nougat32_1 --cmd launchApp --package "com.hypergryph.arknights"

自动启动只能打开实例00，即：
"C:\Program Files\BlueStacks_nxt\HD-Player.exe"

把上面的地址1直接输入也没用，没反应，打不开。

补充：下面是实例00的快捷方式（不过我这里没装方舟）
"C:\Program Files\BlueStacks_nxt\HD-Player.exe" --instance Nougat32 --cmd launchApp --package "xxxxxxxxxx"

**Comment by ABA2396** [comment]
现在只能打开.exe为后缀的

**Comment by ABA2396** [comment]
可以写一个打开模拟器快捷方式的exe文件，然后把那个地址填进去。

**Comment by ABA2396** [comment]
可以参考这个#842 直接把快捷方式的文件名填进去(.lnk后缀的文件)而不是填快捷方式指向的内容，例如你的快捷方式放在了桌面，那就直接写 `C:\Users\用户名\Desktop\快捷方式名.lnk`
