### ISSUE TITLE
继续专精失败

### ISSUE THREAD

**Issue by cutapaper** [MaaAssistantArknights/MaaAssistantArknights#8224]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如图，并没有尝试继续专精，进训练室后出去了，然后又进训练室，然后又出去了，然后显示任务已结束，但并没有继续专精成功。

### Version

Core Version: v5.1.0-beta.1.d002.gc17c7e5ac的上个版本，出bug后更新了一下

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14156396/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14156397/gui.log)

### 截图

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156570912/7f255a13-2cc1-4170-8f2b-d4c99fd5a32b)

**Comment by cutapaper** [comment]
万顷同款问题，昨天试了一次专精等级3的红隼，也不行，但当时怀疑可能是因为专三就不会继续了。今天的专一万顷依旧没法继续专精
![) RWG S{OHG~EWUGC(_U6$L](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156570912/14b07a07-c8eb-4540-83de-9e35c4f0000f)

**Comment by ABA2396** [comment]
cc @broken-paint

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/18ce88e8-9dcf-405d-a9ca-f1bd512303ad)
技能识别有点问题，把这些特殊符号全部在ocrReplace里换成""

**Comment by cutapaper** [comment]
我看公告写优化了，又试了下还是不行，可能是优化的不是这个bug？总之再发一遍
![专精](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156570912/9473555f-5840-4355-8623-aaa781542142)
