### ISSUE TITLE
MAA开机自启动问题

### ISSUE THREAD

**Issue by FrinendJ** [MaaAssistantArknights/MaaAssistantArknights#8228]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新5.0版本后，"设置"->"启动设置"->勾选"开机自启动MAA“后开机自启动两个MAA
"设置"->"启动设置"->取消勾选"开机自启动MAA“后开机自启动一个MAA

### Version

Resource Version: 千秋一粟
UI Version: v5.0.0
Core Version: v5.0.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14156489/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14156490/gui.log)

**Comment by Rbqwow** [comment]
MAA设置→关于我们→查看公告

**Comment by Constrat** [comment]
Duplicate of #8201
