### ISSUE TITLE
2024.02.04 生息演算在进入第四日时报错

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#8231]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如下图，在这个步骤会出现红字“出现错误: custom”然后结束生稀盐酸，一个小时之内出现了三次。

在“还有别的吗？”下有备注。

### Version

Resource Version: 千秋一粟
UI Version: DEBUG VERSION
Core Version: v5.1.0-beta.1.d002.gc17c7e5ac

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14157341/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14157343/gui.log)

### 截图

![MuMu12-20240204-232830](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/b47be4d5-a1bc-44ed-ba84-681ca01dab2d)

### 还有别的吗？

我看到在/resource/tasks.json中的第16022行，
Core Version: v5.1.0-beta.1.d012.g11689cc86
更新了“开启今日”的识别方法
我会在2024.02.05，从大约19:30到23:59尝试复现，如果问题已经被解决，我会在这个时间之后回来关闭issue。

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/ade43e1e-eccc-446b-86bf-42a71fc52951)
@status102 测测看点了那个点击任意位置后多久才能跳出开启今日，改改这个postDelay）

**Comment by ABA2396** [comment]
4s

**Comment by Daydreamer114** [comment]
> 4s

这个是过多久之后会被采纳吗，我看现在这个版本还没应用改动

**Comment by Daydreamer114** [comment]
啊不好意思，最新版是昨天发的

**Comment by Daydreamer114** [comment]
<img width="223" alt="屏幕截图 2024-02-06 044427" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/5145bb7f-087d-4163-a788-5829dce41083">
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14171898/asst.log)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14171891/gui.log)



Core Version: v5.1.0-beta.1.d034.gb01ddac69 中，延迟的逻辑好像出现了小改动，也不知道有没有关联
这次不是第四日卡住了，是卡在第二日进第三日点右上角那个步骤，我还是白天尝试复现一下

**Comment by Daydreamer114** [comment]
<img width="1274" alt="屏幕截图 2024-02-06 133951" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/c7181fbe-637f-411e-92af-8f0e92660ed6">
asst.log消失了。。。
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14175145/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14175146/gui.log)

这个卡退频率是maa的问题还是我的问题。。。

**Comment by ABA2396** [comment]
加了5s延迟，要是20s都进不去就没办法了，时间再长就影响正常流程了，我这里3秒图就加载完了
