### ISSUE TITLE
自动战斗 在教学关卡中自动跳过剧情

### ISSUE THREAD

**Issue by Manicsteiner** [MaaAssistantArknights/MaaAssistantArknights#8234]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

以 #8226 的TR-14为例，TR类作战在进入战斗后（大约是”BattleOfficiallyBegin“）仍会出现需要跳过的对话，需要用户手动跳过。另一些TR关卡甚至会有作战进行到一半时跳出的对话。
溯源源代码后发现是 src/MaaCore/Task/BattleHelper.cpp 91行 常态的 update_deployment 所用的 wait_until_start 参数为false，所以识别到开始作战后就不会执行跳过对话。
尝试将该参数改为true后编译运行，可以跳过对话，但CPU占用激增，属于不可接受级别。

### 有什么好的想法？

暂时没想好，或许可以用个计数器，大概每5秒一次的执行 update_deployment 时，给 wait_until_start 改为赋值 true 执行一次？估计还是会很麻烦。

**Comment by ABA2396** [comment]
与其这样感觉还是写进作业里感觉比较好）

**Comment by Daydreamer114** [comment]
> 与其这样感觉还是写进作业里感觉比较好）

我尝试过在作业里面写东西，但是maa根本识别不到作战开始，也就无法跳过剧情（无法执行作业中的任何步骤）

**Comment by Daydreamer114** [comment]
> 与其这样感觉还是写进作业里感觉比较好）

我怀疑是识别战斗开始的位置被剧情给挡住了，也许更换或者增加识别位置能修复这个问题，比如说出现费用条

**Comment by Daydreamer114** [comment]
在识别到战斗开始之后，maa可以正常识别剧情和教程，并可以正常执行跳过并二倍速

**Comment by status102** [comment]
印象中之前有人做过教学关的剧情跳过，和教学关作业一起上的

**Comment by Manicsteiner** [comment]
#7354 更详细的说法是这个，作战开始后识别到完整的暂停按钮后再出现的对话可以跳过（TR-22），而TR-14这种暂停按钮和skip几乎同时出现的没法跳过

**Comment by Daydreamer114** [comment]
> #7354 更详细的说法是这个，作战开始后识别到完整的暂停按钮后再出现的对话可以跳过（TR-22），而TR-14这种暂停按钮和skip几乎同时出现的没法跳过

是的，现在不是识别剧情的问题，是开局就出现剧情阻挡了原有战斗开始的识别

**Comment by Manicsteiner** [comment]
目前我测试了的解决方法是 src/MaaCore/Task/BattleProcessTask.cpp 401行后加上
`if (!m_in_battle) check_skip_plot_button(image);`
不过这样让 check_in_battle 的weak参数没多大用了，无论是或否都会查一遍 check_skip_plot_button
