### ISSUE TITLE
终端首页未固定肉鸽时，无法”寻路“到肉鸽界面

### ISSUE THREAD

**Issue by Miuzarte** [MaaAssistantArknights/MaaAssistantArknights#8237]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

开始自动肉鸽后，游戏无限在`主界面`和`终端`之间循环

PIN在终端第一页后是没问题的

自动肉鸽设置：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66856838/7dc38c46-6137-4535-b816-bf667fdf9904)

### Version

Resource Version: 千秋一粟
UI Version: DEBUG VERSION
Core Version: v5.1.0-beta.1.d002.gc17c7e5ac

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14157988/asst.log)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14157989/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66856838/81a3ce50-733c-45b1-a197-ade46a505f4d)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66856838/8065c2f0-c22b-43a8-b551-dba5b4f82ad4)

**Comment by Miuzarte** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66856838/c901361f-ea75-404a-9a75-7aa274484b2a)
这下固定也救不了了（，只能手动点进肉鸽里

**Comment by Daydreamer114** [comment]
> ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66856838/c901361f-ea75-404a-9a75-7aa274484b2a)
> 这下固定也救不了了（，只能手动点进肉鸽里

我的首页里没出现过保全，一直有个肉鸽
你要是想先将就用的话应该是可以把保全的pin关掉，肉鸽就出来了

**Comment by status102** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/8de686d2-cd78-4826-a5a7-a952d83164e5)
