### ISSUE TITLE
在win7中v5.0.0的maa启动后内存占用异常

### ISSUE THREAD

**Issue by ypdgy** [MaaAssistantArknights/MaaAssistantArknights#8238]
### 说说你遇到的问题？

如视频所示，启动后内存占用高达5个G，而在资源监视器内其只提交了638MB不到，也不知道是怎么占用的
（视频：https://gy114.lanzoul.com/ilQX31ndtk5c      密码：1145      视频太大github传不上来）

**Comment by ABA2396** [comment]
win7竟然还能跑5.0的吗？按微软的意思来说.net8不支持win7，不知道会不会是运行时一直在报错

**Comment by Manicsteiner** [comment]
> win7竟然还能跑5.0的吗？按微软的意思来说.net8不支持win7，不知道会不会是运行时一直在报错

按微软的说法，DotNet7/8 不再支持 win7/8 ，但可以“不受支持的运行”

如果怀疑是DotNet8运行时的问题，可以尝试安装最后一个名义上支持win7的[DotNet6 runtime](https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-aspnetcore-6.0.6-windows-x64-installer)，运行我修改的[MAA on DotNet6](https://github.com/Manicsteiner/MaaAssistantArknights/releases)

**Comment by ypdgy** [comment]
> win7竟然还能跑5.0的吗？按微软的意思来说.net8不支持win7，不知道会不会是运行时一直在报错

然而在安装的时候没有任何兼容性报错

**Comment by ABA2396** [comment]
https://github.com/dotnet/msbuild/issues/8404#issuecomment-1666903883

**Comment by ypdgy** [comment]
> [dotnet/msbuild#8404 (comment)](https://github.com/dotnet/msbuild/issues/8404#issuecomment-1666903883)

我就知道是net的问题（恼，那谢谢啦

**Comment by ABA2396** [comment]
按那个方法里的设置下环境变量看看，说是有缓解，但到底怎么运行的就是未定义了）
