### ISSUE TITLE
生息演算Day 1进图后报错结束任务，不能自动退出地图

### ISSUE THREAD

**Issue by yliu-fe** [MaaAssistantArknights/MaaAssistantArknights#8240]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

【版本特异性问题】这是今天（2月5日）早晨更新内测版本（版本号见下方）后的新问题，昨天（4日）的内测版可以稳定进行生息演算的刷分操作。
【问题描述】操作严格按照内测版生息演算自动任务的说明进行。进Day 1过对话没有问题，进第一个节点可以顺畅加载地图，按说接着就应该直接退出地图，此时MAA直接报错，停止自动任务，游戏则仍然处于被打开的地图中，需要玩家自行退出地图并退出任务。
【伴生问题】昨天的版本有截图时间偏长（700ms）的Warning，今天升级为时间过长（1500ms）的红色提示。

### Version

Resource Version: 千秋一粟
UI Version: DEBUG VERSION
Core Version: v5.1.0-beta.1.d012.g11689cc86

### 日志文件

Caution 1：截图时间过长（1561ms），2024年2月5日 9:18:07
Caution 2："任务出错：Custom"（无法退图并直接结束自动任务），9:23:49

### 截图

<img width="600" alt="屏幕截图 2024-02-05 093425" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34157793/e52f40a8-99ee-466f-9c01-3031c1ba8cd0">

### 还有别的吗？

模拟器：Mumu 12，版本号3.7.5（2533）
操作系统：Windows 11
硬件：Intel I7-13700H（开启HyperV）+32G RAM+ Iris Xe 96EU，无独立显卡

**Comment by yliu-fe** [comment]
抱歉，日志文件没能上传成功
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14159442/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14159445/gui.log)

**Comment by ABA2396** [comment]
点开始行动之后没识别到弹窗，队伍里放人了？
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/b0cd3cd6-14ad-41fb-adbb-a5418aa8fc65)

**Comment by yliu-fe** [comment]
> 点开始行动之后没识别到弹窗，队伍里放人了？ ![image](https://private-user-images.githubusercontent.com/99072975/302154067-b0cd3cd6-14ad-41fb-adbb-a5418aa8fc65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTkxNTIsIm5iZiI6MTcwNzA5ODg1MiwicGF0aCI6Ii85OTA3Mjk3NS8zMDIxNTQwNjctYjBjZDNjZDYtMTRhZC00MWZiLWFkYmItYTU0MThhYThmYzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAyMDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YzhlMTk1NzRmODBlNmI4NjAyZjIxZTZkNTZiMmU0NmQzOWRiZTA4ZGZkZGU0MjUzZGVjNTczNDdjZTNiYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XRhW3YzpqDLclFvtxpRMPgoZupzpudsUcR9-CC6MJOc)

有可能，我检查一下配队表

**Comment by yliu-fe** [comment]
@ABA2396 问题解决，这不是MAA的问题。
我昨天晚上关掉MAA后手动打了一会，忘记清空配队了。
