### ISSUE TITLE
自动连战有剩余理智时卡在选关界面

### ISSUE THREAD

**Issue by yahayao** [MaaAssistantArknights/MaaAssistantArknights#8241]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

用刷理智时连战6次HS-9后就卡住了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91776775/e5c3c4c0-616d-44dd-b66a-30762316fed4)
好像进入刷剩余理智，所以又开了一次Fight任务

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0-beta.1
Core Version: v5.1.0-beta.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14159564/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14159565/gui.log)

### 截图

![MuMu12-20240205-100313](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/91776775/53188770-a578-42e1-8b01-d931e2a051d1)

### 还有别的吗？

mumu v3.7.10
win10

**Comment by ABA2396** [comment]
cc @status102

**Comment by status102** [comment]
老毛病，那个指示器标又检不到了，看看咋修

**Comment by status102** [comment]
7a25ccf fixed
