### ISSUE TITLE
生息演算中出现错误点击

### ISSUE THREAD

**Issue by xiao-MC666** [MaaAssistantArknights/MaaAssistantArknights#8243]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

运行到一半的时候就有点击错误，卡在无法进行下一步

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/82203609/8f7e9b66-dd57-41a9-ba9f-51d279fe97a6
视频内有点击反馈，可以看到退出后就一直点击，没有下一步操作

### Version

Resource Version: 千秋一粟
UI Version: DEBUG VERSION
Core Version: v5.1.0-beta.1.d012.g11689cc86

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14160680/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14160681/asst.log)

### 还有别的吗？

蓝叠中国版5.14p64。分辨率1280*720。240DPI。未启用root权限

**Comment by Chal1ce** [comment]
确实，我这边也会，mac端playcover，只要加载慢一点就卡住了
