### ISSUE TITLE
更新生息演算后, 从主界面无法自动跳转至肉鸽界面

### ISSUE THREAD

**Issue by yinw27** [MaaAssistantArknights/MaaAssistantArknights#8248]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

一键长草只选择了"开始唤醒"和"自动肉鸽", 当进入到"终端"界面时, 因肉鸽的图标被"生息演算"替换, 导致"自动肉鸽"无法进入到肉鸽主界面

### Version

Resource Version: 千秋一粟
UI Version: v5.0.0
Core Version: v5.0.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14161873/asst.log)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/0f70552b-a610-48ab-9223-4b11cb96352b)

**Comment by box1111** [comment]
倒是可以手动调整在肉鸽界面开始执行任务就不需要识别（）人工代替算法

**Comment by lx159xl** [comment]
我也遇到了一样的问题

**Comment by godsafe** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/302214883-0f70552b-a610-48ab-9223-4b11cb96352b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTg3NzEsIm5iZiI6MTcwNzk5ODQ3MSwicGF0aCI6Ii85OTA3Mjk3NS8zMDIyMTQ4ODMtMGY3MDU1MmItYTYxMC00OGFiLTkyMjMtNGIxMWNiOTYzNTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDEyMDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMGEzMmVlYmZjYmQ4ZDc2ODgwZDVlNjcwOTdjNjM3ZmUwZmQyNjgyNTJkNTYwOTZjYmEwMzM2MDg5ZDNmYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iiggvOvjRWy_uwfDLQtH0dFi4h7ZGQ9bPES8W2yCs38)

要不要做两个版本（以后国内外进度还是不同，根据进度国外低版本，国内用最新版本）或则不嫌累的话可以单独做一个国际版的），区别国服和外服。

**Comment by Log20** [comment]
遊戲設定內不是有選擇用戶端類型的下拉選單嗎? 可以試試用那個綁定生息演算/肉鴿位置的判斷 再按照各服什麼時候出望黍離什麼時候更新

**Comment by La1xuan** [comment]
因为其他的图标没变，是否可以根据其他图标来定位肉鸽的入口的相对位置呢？

**Comment by Manicsteiner** [comment]
fixed by #8764
