### ISSUE TITLE
新功能生息演算问题

### ISSUE THREAD

**Issue by TeseVar** [MaaAssistantArknights/MaaAssistantArknights#8249]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我在挂机的时候，偶尔会出现一局结束还没回到生息演算主页面就开始点击开始的情况
然后MAA报错。

### 有什么好的想法？

建议一轮结束以后，添加0.5s-1s的延迟“点击开始”来确保可以循环开始

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/e8e353bc-91e6-4e43-a8bb-ffb407f7023d)
