### ISSUE TITLE
宿舍放置无法识别新干员小满

### ISSUE THREAD

**Issue by fateneko** [MaaAssistantArknights/MaaAssistantArknights#8250]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在更换宿舍干员时，无法识别新干员小满，浏览全部干员两边后仍旧无法选择新干员小满

### Version

Core Version: v5.0.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14163866/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14163868/gui.log)

最新问题时间[2024-02-05 04:55:44.550]

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/c884f394-8970-4748-a21c-efed02d4019e)
咋就一个core version

![c744c926e7f62f21da0ec2c5dbff8677](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/d31facba-dc93-40b2-a49e-f5f8e8cfe556)
@status102 这玩意有啥想法？`小.*满` 是不是太大了，还是先只改个 `/` 看看？

**Comment by status102** [comment]
> @status102 这玩意有啥想法？`小.*满` 是不是太大了，还是先只改个 `/` 看看？

只改个/先吧，or 小.?满
