### ISSUE TITLE
生息演算会卡在剧情

### ISSUE THREAD

**Issue by acsy2009** [MaaAssistantArknights/MaaAssistantArknights#8251]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![QQ截图20240205185434](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39452380/2de547ed-cf6b-408a-be2b-695ae2013076)
多次测试，会卡在这个地方无法进行

### Version

v5.1.0-beta.1.d029.gb69a66ecf

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14164652/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14164656/gui.log)

### 截图

![Screenshot_20240205-185609](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39452380/9b28b5ed-b445-4c30-9096-ac0505a34346)

### 还有别的吗？

夜神模拟器 7.0.5.0
 Android7.0 32位

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/9be6ee15-dcf7-4c9b-aaae-dbe081ad29f3)
这玩意的得分咋这么低草

**Comment by ABA2396** [comment]
![Reclamation2BeginPlot](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/80a5f68f-c6ec-49f4-a255-23ce016cce18)
试试看把\resource\template\Reclamation2BeginPlot.png 换成这个

**Comment by acsy2009** [comment]
> ![Reclamation2BeginPlot](https://private-user-images.githubusercontent.com/99072975/302273160-80a5f68f-c6ec-49f4-a255-23ce016cce18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzQyNzYsIm5iZiI6MTcwNzEzMzk3NiwicGF0aCI6Ii85OTA3Mjk3NS8zMDIyNzMxNjAtODBhNWY2OGYtYzZlYy00OWY0LWEyNTUtMjNjZTAxNmNjZTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDExNTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNzBhYWVlMjk5ZWM4MWJhMDAyNjMyZTgyZmFlNzY0Y2QxMmFhYjI3MzQ1YjhhY2I0ZmEwYjhkN2EyZGFmOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fAnRw7Vx-krqqutD9HL2meLlMBacU0hG6b9lhMjid1I) 试试看把\resource\template\Reclamation2BeginPlot.png 换成这个


还是任务出错卡在这里，我重下maa试试

**Comment by acsy2009** [comment]
> ![Reclamation2BeginPlot](https://private-user-images.githubusercontent.com/99072975/302273160-80a5f68f-c6ec-49f4-a255-23ce016cce18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzQzODEsIm5iZiI6MTcwNzEzNDA4MSwicGF0aCI6Ii85OTA3Mjk3NS8zMDIyNzMxNjAtODBhNWY2OGYtYzZlYy00OWY0LWEyNTUtMjNjZTAxNmNjZTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDExNTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MjEyNWU4ZjhjMWYzNjJjZDhhOWZkYjU3N2YxNTUyYjQ1Y2M5NmVkZTJhMzkxZmY4Njg2NWQwNWUxNzhhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fH9nntLXJTHMUjkByLKYlRLzdKX9Xk0r7fiymaP-kfo) 试试看把\resource\template\Reclamation2BeginPlot.png 换成这个

实际上下午挂了一下没问题，晚上再想挂就一直卡住了

**Comment by cenfusheng** [comment]
我也是更新了最新一版后卡在这了（既然你发了日志我就不发了，+1催催x）

**Comment by acsy2009** [comment]
> 我也是更新了最新一版后卡在这了（既然你发了日志我就不发了，+1催催x）

非常的神必，运行三次（存疑）之后必定会卡，重装MAA会暂时缓解，然后运行三次（这三次是正常循环的，只要不关MAA）继续卡，无限循环

**Comment by acsy2009** [comment]
> 我也是更新了最新一版后卡在这了（既然你发了日志我就不发了，+1催催x）

完了，装了个新的也不管用，我再试试别的办法

**Comment by acsy2009** [comment]
> 我也是更新了最新一版后卡在这了（既然你发了日志我就不发了，+1催催x）

无法复现，刚才新装的MAA又卡了一次，重开就正常了
