### ISSUE TITLE
生息演算-删除存档返回主界面后，会出现任务

### ISSUE THREAD

**Issue by wf-xian** [MaaAssistantArknights/MaaAssistantArknights#8254]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

删除存档返回主界面后，任务会进入无响应状态，一段时间后任务出错。
这种情况不是每次都发生，但概率高，通常任务自动执行十几分钟就出错中断。
主界面以外的节点也会出现异常，但是很少发生。

### Version

Core Version: v5.1.0-beta.1.d034.gb01ddac69

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14168052/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14168070/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50934425/2e1fb239-18e8-4019-a95b-45a788c74d8a)
![{CS1NT)9 T@2{(8R%T@E$F](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50934425/eb2790a9-3404-4ea7-a3fc-a4e796ae438f)

### 还有别的吗？

MAA版本：5.1.0-beta
模拟器版本：mumu12 ，V3.7.1，1280×720 (DPI 240) 分辨率
设备系统：w11

**Comment by ABA2396** [comment]
日志链接挂了，重新传一下

**Comment by dingcheg** [comment]
你好，我这也发现了类似的问题。这是我的logs。
MAA版本：v5.1.0-beta. 1
模拟器; 雷电模拟器 9.0.62(9)，1280×720 (DPI 240) 分辨率
操作系统：win 10
logs:
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14174686/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14174687/gui.log)

**Comment by wf-xian** [comment]
> 日志链接挂了，重新传一下

已经替换了issue例的日志文件

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1302f0885e8829a3622ff57afa49743394bb8b9a fixed
