### ISSUE TITLE
Hiding series farming for not-updated clients

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#8255]
Description

Currently the only clients that support the series auto farming are the Official and BiliBili. Showing this option to other clients (Yostar and txwy) might lead to incomprehension and maybe useless new issues.
How about hiding this from wpfGui and only showing it to Official and BiliBili
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/610688f4-753a-43be-9ef1-7629b3da2bd1)

cc @status102 @ABA2396 

### Version

Resource Version: So Long, Adele: Home Away From Home
UI Version: DEBUG VERSION
Core Version: v5.1.0-beta.1.d034.gb01ddac69

**Comment by ABA2396** [comment]
Officials don't take much either. I'll add an entrance tomorrow
