### ISSUE TITLE
不将协助训练的干员自动放回宿舍

### ISSUE THREAD

**Issue by fireg958** [MaaAssistantArknights/MaaAssistantArknights#8258]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题，艾丽妮被自动放回宿舍导致无法协助专精，别的干员也会有在训练过程中被放回宿舍的情况

### 有什么好的想法？

在默认策略中新增“体力非空时不将艾丽妮放回宿舍““体力非空时协助干员不放回宿舍”等选项

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/152ef053-3bd6-4b78-9894-e84c874ec40b)
