### ISSUE TITLE
一直卡在”正在连接模拟器“进程的问题

### ISSUE THREAD

**Issue by skylink12** [MaaAssistantArknights/MaaAssistantArknights#826]
![VRA3WT8 3%O}Y)8 QSLGD{3](https://user-images.githubusercontent.com/107050880/173056149-333b8c49-355b-4310-9223-3a9903432d3e.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8878410/asst.log)

使用的是mumu模拟器，之前的夜神、蓝叠同样无法使用，一直卡在”正在连接模拟器“进程

**Comment by MistEO** [comment]
你模拟器自带的 adb 不知道为什么打不开，自己下载个adb 试试
