### ISSUE TITLE
3.9.5输入了企鹅物流的ID刷理智，但是过几分钟企鹅物流还是查不到汇报（雷电模拟器4）

### ISSUE THREAD

**Issue by Voldemore** [MaaAssistantArknights/MaaAssistantArknights#827]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8878891/asst.log)

辛苦啦

**Comment by MistEO** [comment]
看日志都上传成功了，多等一会吧，企鹅有延迟的，这个延迟不短，可能要几十分钟。你可以试试在网页上手动上传看看多久才能看到_(:з」∠)_

**Comment by Voldemore** [comment]
现在成功啦！谢谢_(:з」∠)_
