### ISSUE TITLE
會客室不會選取伺夜(繁中服)

### ISSUE THREAD

**Issue by shmily554554** [MaaAssistantArknights/MaaAssistantArknights#8271]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如同標題，會客室偵測到幹員"伺夜"之後，選取會直接跳過

### Version

v5.0.0

### 日志文件

11

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159156029/da35e592-4923-4f85-ada4-1d0a3d490a8b)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/94c87504-62e4-4d0a-8a2f-bf1389780967)

**Comment by Constrat** [comment]
reopen with logs
