### ISSUE TITLE
MAA5.0更新后，自动肉鸽出现大范围的异常，表现为以下几个方面

### ISSUE THREAD

**Issue by daydreamofscience** [MaaAssistantArknights/MaaAssistantArknights#8276]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA5.0更新后，自动肉鸽出现大范围的异常，表现为以下几个方面
1.招募干员时，有一定概率直接跳过招募（见死囚之夜截图中开局未招募奶妈安塞尔）
2.战斗时，所有干员必定不使用技能
3.战斗时，只会摆放少量干员（如锏开，只放锏和奶），有一定概率直接一个人不放，大开国门
4.有一定概率，会在选择纵向道路时，卡在选择是否使用抗干扰指数界面（并非0抗卡死，而是有抗干扰时候卡死）
NEW！新！：5.MAA会突然闪退

综合导致结果为：无法正常刷源石锭和经验，几乎无法见到坎诺特，绝大数情况下会死在第一关，导致每局刷的经验是0
同时，刷理智也偶尔会出现显示为任务失败，直接结束任务

### Version

Resource Version: 千秋一粟
UI Version: v5.0.0
Core Version: v5.0.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14190404/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14190408/gui.log)

主要肉鸽日志位于2点到3点之间
log可能比较短，因为本人重装了一次MAA和模拟器
将继续挂MAA以提供更多log

日志已补充在评论区

### 截图

已在评论区补充

### 还有别的吗？

逍遥模拟器
系统诊断
VT特性	支持 （已开启）
操作系统	正常
显卡驱动	正常
声音	正常
帧数	60fps

硬件信息
CPU&内存	Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4核7.9GB)
显卡 1	NVIDIA GeForce GTX 1050
显卡 2	Intel(R) HD Graphics 630

软件信息
OS版本	Microsoft Windows 10 家庭中文版 22H2 (19045.3930) 64
显卡驱动	31.0.15.4633 - 12-6-2023
OpenGL Version	4.6.0 NVIDIA 546.33
OpenGL Render	NVIDIA GeForce GTX 1050/PCIe/SSE2

模拟器信息
设备信息	9.1.0.0 (p) - Xiaomi 9 Android 9.0.0 (64bit) (cn)
运行配置	4核 4096MB 1280x720 240 dpi OpenGL (w/ opt)

**Comment by daydreamofscience** [comment]
log可能比较短，因为本人重装了一次MAA和模拟器
将继续挂MAA以提供更多log

**Comment by daydreamofscience** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14191069/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14191072/gui.log)
从2月7日15点45挂到 16点45 一共探索9次，没有一次见到坎诺特
截图：
队友呢队友呢救一下啊
![队友呢队友呢救一下啊](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73294057/b0dd4e4b-c082-4a0d-89de-1cd4cf6df7d3)
开局异常（已勾选非好友助战，仍然不选择锏开局
![开局异常（已勾选非好友助战](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73294057/da8426a3-e94c-4c41-892c-719d72035562)
有时候却能正常开局
![正常开局](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73294057/710beed9-1be4-4498-912b-8fa9884ad1f0)
跳过招募，没来得及截图，右下角人数仍然是3人，希望和等级也对的上
![跳过招募，右下角人数](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/73294057/6ef9d841-b2e4-468a-93ca-30df0827d0cf)

**Comment by Manicsteiner** [comment]
一层的autopilot文件好像没有锏开局打法的优化
勾选刷原石锭模式下，作战结束后不会招募干员，以节约时间
如果只是刷原石锭的话，建议开局配置都由MAA默认选择

**Comment by daydreamofscience** [comment]
> 一层的autopilot文件好像没有锏开局打法的优化 勾选刷原石锭模式下，作战结束后不会招募干员，以节约时间 如果只是刷原石锭的话，建议开局配置都由MAA默认选择

不只是这些，还包括，不开技能不上人，总之就是坎诺特都见不到更别说刷源石锭了

**Comment by horror-proton** [comment]
别的我不大清楚, 技能一个两个漏开了有可能是画面有干扰没识别到, 但全不使用肯定是不正常的 :thinking:

**Comment by daydreamofscience** [comment]
最新日志：5点45第二次闪退，第一次闪退时间未知
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14191769/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14191771/gui.log)

**Comment by Manicsteiner** [comment]
日志里比较奇怪的是动不动就在stdout output放出来一个PNG文件的二进制
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/a802d58f-3bbd-4ad1-8505-6ff0fad899b2)
看文件头的话大小是1280*720，但后面全是00还这么短的话应该是空图片，应该是截图获取失败。测试adb截图方法时 nc 不支持，gzip 返回data is not empty, but image is empty

**Comment by daydreamofscience** [comment]
更新日志：6点第三次闪退，目前的情况是，第二关必定闪退，原因未知
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14192238/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14192307/gui.log)

另外5点15附近，刷理智时报错，原因是截图识别是黑屏，建议适当延长截图时间与次数

**Comment by Manicsteiner** [comment]
17:42 的asst.log最后全都是截图失败的内容，感觉可以甩锅给模拟器了

**Comment by horror-proton** [comment]
有 PNG 图片的二进制是截图失败的, 之前版本有个 bug #8280 会导致连续截图失败因为 floating point exception 崩溃

**Comment by status102** [comment]
看上去问题都修完了
