### ISSUE TITLE
MMA5.0自动肉鸽指定主题后无法找到入口

### ISSUE THREAD

**Issue by mis-match** [MaaAssistantArknights/MaaAssistantArknights#8277]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

启动自动肉鸽后将会停在这个界面
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96474692/e869578c-0735-4e89-9605-5ab41845ab99)
我选择的是傀影肉鸽，正确的寻路应当是
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96474692/bf7409c8-725d-4faf-8b59-b4193b5aca96)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96474692/1cab8682-01c5-4558-acd7-5d24d314c47a)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96474692/e82f55ba-712b-4d87-b809-7b0c0520e3f1)

### Version

MAA V5.0.0

### 日志文件

-

**Comment by Rbqwow** [comment]
你确定已经检查了置顶议题吗
