### ISSUE TITLE
启动即闪退

### ISSUE THREAD

**Issue by Toxiad** [MaaAssistantArknights/MaaAssistantArknights#828]
![image](https://user-images.githubusercontent.com/50210227/173076464-6ab6e118-0cfa-446d-81fc-dea9f5e6e38b.png)
启动时卡死，几秒后闪退。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8879228/asst.log)

**Comment by Toxiad** [comment]
![image](https://user-images.githubusercontent.com/50210227/173076834-81f30f5a-5cf0-4e4c-abc3-e6efa21b9853.png)
CPUZ
![image](https://user-images.githubusercontent.com/50210227/173076942-68d59f55-8103-4696-8be4-2eba8b48d920.png)
系统版本
![image](https://user-images.githubusercontent.com/50210227/173077042-9227e2dd-866d-44d0-bef6-9ff1461a305b.png)
运行库

**Comment by MistEO** [comment]
之前有使用过么，像是以下原因之一

- 下载的包不完整，重新下载解压一次试试
- 没有文件夹下的读写权限，换个目录试试
- 配置文件损坏，把 `gui.json` 删了试试
- 检查更新崩溃，不知道咋整，先把网断了试试（）

**Comment by Toxiad** [comment]
可以了，不知道为啥之前下的包没有config（
