### ISSUE TITLE
mumu在mac平台出了新的安卓模拟器，开发者要考虑适配吗

### ISSUE THREAD

**Issue by Axeva-star** [MaaAssistantArknights/MaaAssistantArknights#8281]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by Axeva-star** [comment]
最近mumu在最近出了新的mumu-pro在mac平台上面，我看maa还没有适配，会考虑适配吗

**Comment by Rbqwow** [comment]
#8098

**Comment by Constrat** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8098
