### ISSUE TITLE
为什么识别不到煌？？？

### ISSUE THREAD

**Issue by StarMonthStudio** [MaaAssistantArknights/MaaAssistantArknights#8289]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![JT6 {@5P9F%2U7255`0C2AJ](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61019628/74d768ba-7093-43e0-bc4f-35b779318d0b)

### Version

UI Version: v5.1.0-beta.2.d004.g4fcfa56b1

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14207382/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14207383/asst.log)

### 截图

![JT6 {@5P9F%2U7255`0C2AJ](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61019628/29a2a684-e150-4529-84dc-2c88328c1bee)

**Comment by Daydreamer114** [comment]
翻译：识别不了星标（特别关注干员）
这个是老早就说过的事情了
