### ISSUE TITLE
地图识别错误

### ISSUE THREAD

**Issue by HMZyueshen** [MaaAssistantArknights/MaaAssistantArknights#829]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8879912/asst.log)
[tough_10-06_史尔特尔+山+泥岩（bug）.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8879919/tough_10-06_.%2B.%2B.bug.zip)

**Comment by MistEO** [comment]
@yuanyan3060 泰——迪——

这关磨难关卡识别结果和普通关卡是一样的，tough (10, 1) 这个点错了，还有其他几个点也错了

![image](https://user-images.githubusercontent.com/18511905/173143487-1b7388ae-a99b-4d58-8cbd-4cdcf95c7cca.png)

tough_10-06
![map](https://user-images.githubusercontent.com/18511905/173143252-14a84935-c1ec-4cde-8183-089653017113.png)


main_10-06
![map](https://user-images.githubusercontent.com/18511905/173143703-beb45119-5e67-4830-915e-9eb7f0ad3ad5.png)

**Comment by yuanyan3060** [comment]
> @yuanyan3060 泰——迪——
> 
> 这关磨难关卡识别结果和普通关卡是一样的，tough (10, 1) 这个点错了，还有其他几个点也错了
> 
> ![image](https://user-images.githubusercontent.com/18511905/173143487-1b7388ae-a99b-4d58-8cbd-4cdcf95c7cca.png)
> 
> tough_10-06 ![map](https://user-images.githubusercontent.com/18511905/173143252-14a84935-c1ec-4cde-8183-089653017113.png)
> 
> main_10-06 ![map](https://user-images.githubusercontent.com/18511905/173143703-beb45119-5e67-4830-915e-9eb7f0ad3ad5.png)

stageId里会包含难度的信息，easy开头是简单，main是普通，tough是磨难(

**Comment by MistEO** [comment]
> > @yuanyan3060 泰——迪——
> > 这关磨难关卡识别结果和普通关卡是一样的，tough (10, 1) 这个点错了，还有其他几个点也错了
> > ![image](https://user-images.githubusercontent.com/18511905/173143487-1b7388ae-a99b-4d58-8cbd-4cdcf95c7cca.png)
> > tough_10-06 ![map](https://user-images.githubusercontent.com/18511905/173143252-14a84935-c1ec-4cde-8183-089653017113.png)
> > main_10-06 ![map](https://user-images.githubusercontent.com/18511905/173143703-beb45119-5e67-4830-915e-9eb7f0ad3ad5.png)
> 
> stageId里会包含难度的信息，easy开头是简单，main是普通，tough是磨难(

我当然知道，，就是正确的设置了之后，tough 出来的是 main 的格子
