### ISSUE TITLE
萨米肉鸽存钱maa总是自己跑去打安洁莉娜探索者档案导致一块钱也没存

### ISSUE THREAD

**Issue by mmqm123** [MaaAssistantArknights/MaaAssistantArknights#8290]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![988B90165F17871B9054209CB7BE36D3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159435944/f81f90b8-2d9d-413d-9ff5-91c88c96e413)
就是这样，maa刚开始还能正常刷钱，我一没看它就跑去打安洁莉娜肉鸽了

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0-beta.1.d043.g7e3782433
Core Version: v5.1.0-beta.1.d043.g7e3782433

### 日志文件

[Uploading asst.log…]()

### 截图

![988B90165F17871B9054209CB7BE36D3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159435944/73352a90-3af5-4d9e-b5af-f92f6af9331b)

### 还有别的吗？

mumu模拟器12

**Comment by mmqm123** [comment]
补充一句我发现我每次结束maa打杰哥肉鸽后，重进肉鸽等待时长都会非常长，几分钟到十几分钟不等

**Comment by Rbqwow** [comment]
日志没发上来 重发一下

**Comment by status102** [comment]
需要选择到常规行动，MAA不会选的要自己选

以及，你MAA该更新了，内测bug多更新频繁，你现在大概率停在了一个肉鸽投资有bug的版本上
