### ISSUE TITLE
自动战斗替换干员选项

### ISSUE THREAD

**Issue by ImYiFeng** [MaaAssistantArknights/MaaAssistantArknights#8291]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

实际使用自动战斗时，很多干员都可以平替，比如黍和塞雷娅，奶羊和蜜莓。
很多时候，当作业中有两个干员我没有，且其中一个可以平替，我一般都会将作业下载下来，并修改作业文件，直接替换干员名称，这样修改之后同样可以打过，于是有了这个想法

### 有什么好的想法？

增加一个替换干员的复选框，选择后，将作业文件用到的所有干员列出来，每一个干员右边都有一个输入框，用户输入替换干员的名字，即可完成替换，不用修改作业源文件，方便快捷

**Comment by KevinT3Hu** [comment]
并没有很多情况能直接替换的吧，比如技能的使用上的差别。
作业上也可以用干员组标出可以替换的干员

**Comment by ImYiFeng** [comment]
> 并没有很多情况能直接替换的吧，比如技能的使用上的差别。 作业上也可以用干员组标出可以替换的干员

以目前MAA Copilot摆完挂机作业为主，替换功能应该还是很实用的，就我个人使用而言，也经常需要编辑作业文件去手动替换。挂机技能也没有使用方法

**Comment by MobiusT** [comment]
这是我上周想提的，后面想了下有些情况会很麻烦，并且感觉有相同需求的人不多，就没正式提，既然看到了我说下我的想法吧

一、实现方式
我设想的是用类似追加自定干员的方式，以一定规则（如塞雷娅1:黍1）进行，勾选后如果添加作业有对应的技能就自动替换。主要是想解决作业没有设置干员组，但是我想替换其中某个干员的情况，在战斗列表的时候一个个作业下载替换非常麻烦。
二、考虑的问题
1、需要检测作业是否同时使用了平替和被平替的技能，无脑替换会导致重复干员出问题
2、遇到被平替干员在作业组情况下（作业要求 塞雷娅1，作业组奶盾【黍1，临光1，古米.......】）要如何选择作业组干员和平替干员，是否还会触发 #7251 问题

**Comment by infstellar** [comment]
搓了一个python脚本，通过直接改战斗json文件来替换干员（凑合
https://github.com/infstellar/MAACopilotReplacer
对于网上下载的作业也是有效的，因为是改缓存目录下的缓存战斗文件。
