### ISSUE TITLE
非16:9分辨率屏幕使用WSA永远无法成功截图

### ISSUE THREAD

**Issue by SamuNatsu** [MaaAssistantArknights/MaaAssistantArknights#8293]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用的是新版本 WSA，并且按照说明进行了配置

由于我使用的屏幕是非16:9尺寸，且不希望专门为了 MAA 调整屏幕分辨率，所以MAA进行截图时不管是否全屏都会报错

### Version

Res Ver: 千秋一粟
UI Ver: v5.0.0
Core Ver: v5.0.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14217443/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14217444/gui.log)

asst.log 625行左右，WSA屏幕尺寸为2560x1600，不符合16:9要求

### 截图

这个图片是使用 MAA 调用的 adb 命令截图出来的，很明显需要裁剪处理才能正常工作

![screen](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49141130/586cd469-0bd6-4650-aed8-99ab8f8c37f1)

### 还有别的吗？

由于 WSA 默认将整个屏幕作为桌面进行 adb 截图，且窗口化的 WSA 应用只会占用一部分桌面，导致adb截图大部分为黑色，即使将 WSA 应用手动调整为 16:9 大小

所以对于非 16:9 的屏幕可能需要在 AdbController 中对图片进行裁剪，提取出 WSA 应用的真实占用图像才行

具体可行方法为 adb 截图之后使用 winAPI 获取 WSA 应用窗口位置，然后利用窗口位置进行截图裁剪，提取出真实图像

因为 MAA 相关控制代码没太看懂（注释过少诉讼），本来想自己写个 pr 上去的但是咕咕咕了，希望有个好心人能帮忙解决

**Comment by Rbqwow** [comment]
~~你们就不能用点正经打游戏的模拟器吗~~
#6937

**Comment by SherkeyXD** [comment]
现在是有 wsa controller 的
但是没集成进去（

**Comment by SamuNatsu** [comment]
看看啥时候能合并进去罢，太扯了
