### ISSUE TITLE
代理失误数次后自动停止

### ISSUE THREAD

**Issue by SYLDNA** [MaaAssistantArknights/MaaAssistantArknights#8294]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

代理失误了一百次净亏100理智，痛心疾首

### 有什么好的想法？

增加一个可选项，代理失误出现非3星数次后自动停止，并右下角弹窗提示，该次数可自定义，防止连续代理失误未被发现

**Comment by YuhangTom** [comment]
支持一下，上次闪断之后加了伤害导致HS-9速刷疯狂代理失败，定时执行一觉醒来人傻了TAT，如果点了吃理智药就是更加亏麻了

**Comment by ABA2396** [comment]
这个逻辑是有做过的，如果有问题发日志，没日志很难找问题

**Comment by Constrat** [comment]
No log. Reopen
