### ISSUE TITLE
Reclamation Algorithm label

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#8297]
Considering the implementation of the new gamemode as permanent it is suggested to add a new label and labeling system `reclamation` to better organize the issues.
I'm missing the keywords for the CN / JP and KR clients.

**Comment by Rbqwow** [comment]
CN CHS keywords: 
`生息|演算|沙洲遗闻|决断|量定|繁荣(?:点数|馈赠)|技术(?:点数|脉络)|粗制赤金|陌域|黄绿茂林|盐河荒滩|白水绿洲|幽邃禁坑`
without places:
`生息|演算|沙洲遗闻|决断|量定|繁荣(?:点数|馈赠)|技术(?:点数|脉络)|粗制赤金`
without places and resource:
`生息|演算|沙洲遗闻|决断|量定`
maybe too long or too short idk 🤔

**Comment by Constrat** [comment]
Thank you very much, for now I guess we can just go with `生息演算|沙洲遗闻`. Hopefully the issues will mention at least one of these two.

**Comment by Constrat** [comment]
Fire within the sand test

**Comment by Constrat** [comment]
Reclamation

**Comment by Constrat** [comment]
Reclamation

**Comment by Constrat** [comment]
Good
