### ISSUE TITLE
Hardware acceleration for OCR, availability and pre-build binary distribution

### ISSUE THREAD

**Issue by reberu-7-xd** [MaaAssistantArknights/MaaAssistantArknights#8299]
### Before raising the issue...

- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I'm probably sure this is a new feature/suggestion and not a bug encountered (please attach logs if you're not sure)

### The problems you have encountered?

The fastdeploy included in the released binaries did not compile with GPU.
Therefore, configurations using AsstSetStaticOption or using the gpu_ocr option in maa-cli will result in an error.
```
[WARNING] D:\a\MaaDeps\MaaDeps\vcpkg\buildtrees\maa-fastdeploy\src\7b46ddfce2-ca3f4b205b.clean\fastdeploy\runtime.cc(246)::fastdeploy::RuntimeOption::UseGpu    The FastDeploy didn't compile with GPU, will force to use CPU.
```

### Any good ideas?

I thought about building it myself but it is difficult and there are other users who want to use GPU.
So please release binaries compiled with GPU or explain how to build them.
It would also be better if the GUI had a GPU option as well.

**Comment by ABA2396** [comment]
cc @MistEO

**Comment by Cryolitia** [comment]
Now support CUDA only, DirectML support is on TODO list but would not be really implemented soon.

Here's a NUR package example that enables CUDA support https://github.com/Cryolitia/nur-packages/blob/master/pkgs/MaaAssistantArknights/default.nix

It's now still a difficult work to release binary with CUDA support.
1. ONNXRuntime CUDA Provider is a standalone library, cannot be packed in to one binary.
2. It's hard to build ONNXRuntime, fastdeploy, as MaaCore's dependency on Github Actions. Build script here: https://github.com/MaaAssistantArknights/MaaDeps

**Comment by Cryolitia** [comment]
Another thing could be discussed is that whether we should add the DirectML support on Windows. It could support kinds of different GPUs, but still has a problem that it's hard to release binary. Another doubt is that how faster could it be than CPU. We haven't done any performance tests yet.

**Comment by SherkeyXD** [comment]
DirectML 再怎么着都比 CPU 好吧（

**Comment by ZeroAurora** [comment]
ONNX Runtime provides choices for execution backends as [execution providers](https://onnxruntime.ai/docs/execution-providers/#summary-of-supported-execution-providers).

**Comment by ZeroAurora** [comment]
Drawback of DirectML is that it's Windows only. Fallback must be considered in this case.

**Comment by Cryolitia** [comment]
> DirectML 再怎么着都比 CPU 好吧（

不一定喔，比如跑在AMD 7840U的XDNA上，毕竟你永远不知道用户在用什么环境，不过最大的阻碍还是二进制分发，剩下的都好说，多写几个选项给用户选就是了

**Comment by Cryolitia** [comment]
https://github.com/ROCm/ROCm/discussions/2631

根据这个讨论，ROCm似乎在移动端低功耗AMD平台没有很显著的提升。等待AMD XDNA的测试表现。
