### ISSUE TITLE
刷理智模块识别错误

### ISSUE THREAD

**Issue by darthfoxz** [MaaAssistantArknights/MaaAssistantArknights#8303]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

刷活动关HS-8和HS-9的时候理智全部刷完后，会先退出至主界面，之后重新进到资源收集的副本选择界面。在选择界面一直向右滑动很长时间直到Fight报错然后执行下个任务。（虽然不影响Fight任务完成）

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0-beta.2
Core Version: v5.1.0-beta.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14229111/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14229112/gui.log)
2024-02-10 12:35:34.071

### 还有别的吗？

MuMu12 V3.17.10 DirectX模式
Windows 10 专业版 22H2 19045.3324
RTX 3060 Ti
i5-12600KF

**Comment by ABA2396** [comment]
你剩余理智选了PR-A-2，但是今天没开
