### ISSUE TITLE
自动公招增加刷新四星Tag

### ISSUE THREAD

**Issue by addicter2017** [MaaAssistantArknights/MaaAssistantArknights#8304]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前的自动公招不支持刷掉四星tag，根据b站up的统计，如果四星招的过多可能减少出高资的概率，希望增加这个功能

**Comment by KevinT3Hu** [comment]
参考文献请求

**Comment by Rbqwow** [comment]
🤔看看BV号？

**Comment by addicter2017** [comment]
https://www.bilibili.com/video/BV1Ry4y1J7pS/?spm_id_from=333.337.search-card.all.click&vd_source=3cf6937066d47596992d4cbce32e5137

**Comment by ABA2396** [comment]
感觉太不靠谱了，完全没有数据支持，这up甚至连银灰崖心是远程还是近战都不知道，很难让我相信他研究过公招机制
