### ISSUE TITLE
刷理智剩余理智增加当前关卡选项

### ISSUE THREAD

**Issue by nanmingxwx** [MaaAssistantArknights/MaaAssistantArknights#8305]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

开启多次连战次数后，体力比需求差一点就不会清空体力，建议剩余理智增加当前关卡，并把连战调成一次

**Comment by SherkeyXD** [comment]
现阶段只能手动设置相同关卡了
