### ISSUE TITLE
在只有mumu模拟器和明日方舟作为前台主运行项目的情况下，maa占用疑似过高造成卡顿

### ISSUE THREAD

**Issue by zhayier** [MaaAssistantArknights/MaaAssistantArknights#8315]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

用的是笔记本，i7 13700hx，相当于12600k，显卡4060，用的mumu模拟器12，版本3.8.1（2675），电脑系统win11，版本22H2，前台主要运行mumu模拟器和maa，在挂肉鸽，从运行开始，全程cpu占用都很高，最低也有20%，最高能去到80-100之间持续一段时间（在开始对局战斗的时候），查看其他lssue也看见说已解决占用过高，但实际占用还是这么高，我觉得不太对劲

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0-beta.2
Core Version: v5.1.0-beta.2

### 日志文件

[log.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14238720/log.txt)
拉到最下面看九点12-15分即可，前面挂着的也混杂了一部分日志看不看都行，但只要一开始挂肉鸽就全程高占用

### 截图

![Z7~XDJOZ67BUA_U08LMXH)O](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159781960/44030b02-3b5d-4e7a-989d-e09141b36199)
![EE0OM9{XFR$_V($NWA5@HF6](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159781960/74155440-a2fa-4e57-9d03-01cd64a5dc9e)
![9V83H~ ZLLU@ACVRF9 OC7N](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159781960/13416964-f728-4792-a7f7-ca5a9c79f7ad)
![{)EXG}9N3CT3P_R~0A $}PC](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159781960/fbf2d6dc-8cf3-4714-ae00-ef4b1f7819
![KO{($ZDYZO9 7{3G)YY~TCV](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159781960/98585e44-9e2c-4fcb-988e-65fefe418e12)
58)
![_PXBW(@M3FTW~}ZOV4(0QX0](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159781960/fb016f7d-63e6-4897-9cef-0fc9e6a2fa22)
![272R~P4C4ORBQ M5QU7N60T](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159781960/54e3d96e-493c-4d81-962b-7e50e2ae1d00)

**Comment by zhayier** [comment]
不管挂多久，cpu占用都很高，配置比我低，i3 8100+亮机卡的用户也跟我说不卡，如有需要补充的信息的，我看见后会尽可能快的补充上，我能想到的相关信息就这些，根据贴吧那边，雷神之类的模拟器也有这种情况。更具体的模拟器信息截图忘放了

基础信息
UUID :  baccae57-16cc-47cc-93b5-5e2a93d9528d
模拟器版本 :  3.8.1.2675
模拟器磁盘（可用/总）空间 :  73.5GB/126GB
日志路径 :  D:\MUMU\emulator\MuMuPlayer-12.0\vms\MuMuPlayer-12.0-0\logs\

运行环境
VT :  开启
Hyper-V :  关闭
网络环境检测 :  正常
以管理员运行方式 :  否
DirectX 11是否安装 :  是
防火墙 :  关闭

电脑配置
主板型号 :  Manufacturer: HP  Product: 8BC2
CPU :  13th Gen Intel(R) Core(TM) i7-13700HX
系统版本 :  Windows 11 64-bit Kernel 10.0.22621
显卡驱动 :  正常
显卡驱动型号 :  31.0.15.5123 (20240118)
所有显卡 :  NVIDIA GeForce RTX 4060 Laptop GPU  |  Microsoft Basic Render Driver
当前使用显卡 :  NVIDIA GeForce RTX 4060 Laptop GPU
安装磁盘(可用/总)空间 :  185.4GB/1907.4GB
可用内存/总内存 :  6.3GB/15.7GB

模拟器设置
Root :  开启
显卡渲染模式 :  DirectX 模式
性能设置 :  6核/6GB
手机型号 :  HONOR Magic4 Pro
分辨率 :  720 * 1280
高帧率 :  开启
后台保活 :  开启

连接设备
音频输入 :  已连接
音频输出 :  已连接

网络信息
MuMu DNS :  192.168.1.1
电脑DNS :  192.168.1.1
Rom MAC地址 :  08:8c:04:3b:30:00

ADB调试端口 :  16384
MuMu出口IP地址 :  10.0.2.15
电脑出口IP地址 :  223.74.93.55

其它信息
其它版本信息 :  vm: 120.1.52.004 hyperv: 6.3.16.0 renderer: 0.0.162.0
Vendor :  NetEase
OpenGL Renderer :  MuMu GL (NVIDIA GeForce RTX 4060 Laptop GPU Direct3D11 vs_5_0 ps_5_0)
OpenGL Version :  OpenGL ES 3.1
运行时间 :  0 : 28 : 56

**Comment by Rbqwow** [comment]
内测版已提供GPU加速功能 同时添加了最小截图间隔 已经成功优化
