### ISSUE TITLE
生息演算出现奇遇选项时会任务报错停止任务

### ISSUE THREAD

**Issue by YizhouTian** [MaaAssistantArknights/MaaAssistantArknights#8317]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

生息演算出现“众人会聚之地---一张便条”选项时会任务报错停止任务
<img width="938" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/68794127/818f5ffd-779c-4f14-9139-70e660afdb91">

### Version

Core Version: v5.1.0

### 日志文件

<img width="208" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/68794127/60a7cf52-ec61-4c3a-b07e-2524a62d6405">

### 截图

<img width="939" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/68794127/e1abba9d-1f73-4125-88a4-b1c036ef0847">

**Comment by SherkeyXD** [comment]
别光截图啊 log 文件放上来

**Comment by Mou-Froski** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14274944/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14274950/gui.log)
我家maa卡在每日结算界面，报错时间为11:29:43，要不看看？

**Comment by Mou-Froski** [comment]
@SherkeyXD

**Comment by wu-sv** [comment]
我估计我也是同样的问题
