### ISSUE TITLE
maa更新V5.1.0之后无法连接模拟器

### ISSUE THREAD

**Issue by Wh1teArrow** [MaaAssistantArknights/MaaAssistantArknights#8318]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

这次更新后，maa无法连接模拟器(更新之前能正常使用)，重启电脑、重新下载maa之后依然无法连接
Mumu模拟器版本
![QQ截图20240213094322](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159859107/19fc5e03-6241-4b62-bea9-d387224e0b2c)

![QQ截图20240213094441](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159859107/bf18afdc-ccd6-4c9f-802e-15a4db6d79bf)

### Version

UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14254652/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14254653/gui.log)

**Comment by Rbqwow** [comment]
MAA 在 v5.1.0 放弃了对mumu6的支持 因为官方已经在半年前停止更新了
但使用通用连接模式 手动配置adb和连接地址仍然可以正常连接
mumu6的端口是7555 而非12的16384
连接本地的模拟器应该还有个地址 例如`127.0.0.1:7555` 而非只有`7555`

**Comment by the4thDusk** [comment]
遇到了同样的问题，看了下楼上的回复，检查了下连接设置，我用的mumu12，连接地址仍然只有127.0.0.1:7555。
然后我发现上面有个自动检测连接，勾选了就好了
