### ISSUE TITLE
MAA v5.1.0 HS-7 出现企鹅物流上传失败

### ISSUE THREAD

**Issue by fengziyun** [MaaAssistantArknights/MaaAssistantArknights#8319]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

2024年02月12日时更新到了5.0.0版本，昨天运行良好。今天早上启动时要求更新资源，更新完后版本来到了v5.1.0.

模拟器使用的“mumu明日方舟”版本 v3.7.11（2641），明日方舟为官服。

运行刷理智，配置为：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/28677290/67fdc1e5-e2f8-4643-8dc4-a66261dbee22)
报错也为图上所示。

### Version

Resource Version: 登临意·复刻
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14254814/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14254819/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/28677290/186c3d7e-3e48-4ce0-8e76-f21f0d27e380)

**Comment by Constrat** [comment]
Check
```
[2024-02-13 09:52:26.610][ERR][Px5a1c][Tx2cb0] asst::StageDropsTaskPlugin::_run upload_to_penguin failed
[2024-02-13 09:52:26.612][TRC][Px5a1c][Tx2cb0] Finish folder cleanup delete  0  files from  D:\MAA-v4.24.0-win-x64\debug\drops
[2024-02-13 09:52:26.612][TRC][Px5a1c][Tx2cb0] Save image debug\drops\2024-02-13_09-52-26-612_raw.png
```
`debug\drops\2024-02-13_09-52-26-612_raw.png`

**Comment by Sduck-Inverse** [comment]
![5$@2FU@_SY{Q@JX@) 824RE](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87361258/bf56d8ff-9eee-498f-88c3-14acd9fb258e)
我也是今天晚上更新版本后刚出现这关不能识别了突然，早上还好好的……

**Comment by ABA2396** [comment]
资源版本都还在登临意，咋可能认识新版本的活动
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/2ad418a1-4559-4492-b67a-ee5497d3bb63)

**Comment by Sduck-Inverse** [comment]
> 资源版本都还在登临意，咋可能认识新版本的活动 ![image](https://private-user-images.githubusercontent.com/99072975/305439715-2ad418a1-4559-4492-b67a-ee5497d3bb63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMjY5MjUsIm5iZiI6MTcwODEyNjYyNSwicGF0aCI6Ii85OTA3Mjk3NS8zMDU0Mzk3MTUtMmFkNDE4YTEtNDU1OS00NDkyLWI2N2EtZWU1NDk3ZDNiYjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDIzMzcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZTY1YmQ3YjJkYzQwYWU0ZjMzM2E3ZDE4ODE4MTliYzhmNDMxOTM3YjFmNmUyZGI5YzJjNTNiMjk0OGI0YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B3aGCEOwMzayMlPafeYJUYd3_OHt7KvXodB6hQoWlH4)

![9 BBIZ1ZWF96$GS (VA5LB5](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87361258/0ba15488-2c6e-411f-a004-b2a77055fbdc)
版本对了也一样哎

**Comment by Manicsteiner** [comment]
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/b281e6aa-6063-407d-9bc5-b0c2a774a8dd)
我也遇见这个问题好久了，前一阵子刷活动以为是资源更新不及时，或者是企鹅物流不收其他服务器的资源汇报了，现在刷红票应该不是资源更新的问题
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14319169/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14319170/asst.log)

**Comment by zhangfelix** [comment]
> > 资源版本都还在登临意，咋可能认识新版本的活动 ![image](https://private-user-images.githubusercontent.com/99072975/305439715-2ad418a1-4559-4492-b67a-ee5497d3bb63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMjY5MjUsIm5iZiI6MTcwODEyNjYyNSwicGF0aCI6Ii85OTA3Mjk3NS8zMDU0Mzk3MTUtMmFkNDE4YTEtNDU1OS00NDkyLWI2N2EtZWU1NDk3ZDNiYjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDIzMzcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZTY1YmQ3YjJkYzQwYWU0ZjMzM2E3ZDE4ODE4MTliYzhmNDMxOTM3YjFmNmUyZGI5YzJjNTNiMjk0OGI0YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B3aGCEOwMzayMlPafeYJUYd3_OHt7KvXodB6hQoWlH4)
> 
> 
> 
> ![9 BBIZ1ZWF96$GS (VA5LB5](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87361258/0ba15488-2c6e-411f-a004-b2a77055fbdc)
> 
> 版本对了也一样哎

@Sduck-Inverse 你那边“怀黍离”HS-EX，HS-S系列关卡的自动战斗正常吗？

**Comment by Sduck-Inverse** [comment]
> > > 资源版本都还在登临意，咋可能认识新版本的活动 ![image](https://private-user-images.githubusercontent.com/99072975/305439715-2ad418a1-4559-4492-b67a-ee5497d3bb63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMjY5MjUsIm5iZiI6MTcwODEyNjYyNSwicGF0aCI6Ii85OTA3Mjk3NS8zMDU0Mzk3MTUtMmFkNDE4YTEtNDU1OS00NDkyLWI2N2EtZWU1NDk3ZDNiYjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDIzMzcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZTY1YmQ3YjJkYzQwYWU0ZjMzM2E3ZDE4ODE4MTliYzhmNDMxOTM3YjFmNmUyZGI5YzJjNTNiMjk0OGI0YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B3aGCEOwMzayMlPafeYJUYd3_OHt7KvXodB6hQoWlH4)
> > 
> > 
> > ![9 BBIZ1ZWF96$GS (VA5LB5](https://private-user-images.githubusercontent.com/87361258/305580464-0ba15488-2c6e-411f-a004-b2a77055fbdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDkzOTQsIm5iZiI6MTcwODI0OTA5NCwicGF0aCI6Ii84NzM2MTI1OC8zMDU1ODA0NjQtMGJhMTU0ODgtMmM2ZS00MTFmLWEwMDQtYjJhNzcwNTVmYmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA5MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MmM4NjI4MzRiOTdmZDQ1OTBkOWMwNjFjNWJiY2FmMTIyMzFlNWFmNWU2YjkxYjI0MDM5NzdkYjU2NDZmZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3BC-r_Fa91rC-PMo8oki7nFPBshvOBykDswZKAWOmLE)
> > 版本对了也一样哎
> 
> @Sduck-Inverse 你那边“怀黍离”HS-EX，HS-S系列关卡的自动战斗正常吗？

为什么ex关也要用MAA打？

**Comment by FlazeNaive** [comment]
是不是还没修啊（改了企鹅物流id之后会上传失败，用默认似乎是成功的）
