### ISSUE TITLE
肉鸽存原石锭显示有问题

### ISSUE THREAD

**Issue by zht04** [MaaAssistantArknights/MaaAssistantArknights#8320]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在6:58:20的投资还是正常 ，但是下一次投资7:06:21显示的就有问题，之后的投资就一直有问题了，具体可以看图片（最后那个截图失败、模拟器断开等等，是模拟器崩溃了，和这个应该没啥关系）

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14255397/asst.zip)
[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14255403/gui.zip)

### 截图

![bug1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/113323371/fd1f4361-966c-42ec-b49c-b2c9b5de5998)

**Comment by ABA2396** [comment]
cc @status102
