### ISSUE TITLE
生息演算与基建换班中的训练室均执行出错

### ISSUE THREAD

**Issue by kwanKC** [MaaAssistantArknights/MaaAssistantArknights#8321]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

有两个报错的地方
1.基建换班执行到训练室时maa会卡住，接着程序自己挂了
2.生息演算执行直接报错
看了下日志，两个报错的提示似乎都是Task not found

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst - 基建训练室报错.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14256307/asst.-.log)
[asst - 生息演算报错.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14256309/asst.-.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14256310/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/69830945/2336a41d-5949-4d9d-9d23-b3b5ab418209)

**Comment by SherkeyXD** [comment]
生稀盐酸部分可能是你的游戏资源没有成功更新，在网络通畅的情况下使用一下 maa 的检查更新
