### ISSUE TITLE
#7698更新 前幾次嘗試不能辨識夜刀 最後只有夜刀被選中

### ISSUE THREAD

**Issue by kobi1108** [MaaAssistantArknights/MaaAssistantArknights#8324]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

繼承 #7698 issue
問題往奇怪方向發展 
現在前幾次會一直嘗試找夜刀

大部分時候 到最後會只選中夜刀 其餘4個空的

### Version

Resource Version: 前路迴響
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[2024-02-13 14:09:25]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14258244/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14258246/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140871439/ae74b0da-6d38-4057-8e6b-68843a3aa57f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140871439/1134aa6f-8086-430b-b749-202cf9e78768)

**Comment by Constrat** [comment]
No need to open another issue. You can just give more info directly in #7698

**Comment by Constrat** [comment]
Duplicate of #7698
