### ISSUE TITLE
肉鸽，建议规避开局奖励选择-1希望拿藏品

### ISSUE THREAD

**Issue by ChristineBlank** [MaaAssistantArknights/MaaAssistantArknights#8327]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在”策略“里选择"刷等级”之后，MAA似乎会自动选择第一个奖励，如果不巧是-1希望拿藏品它也会照选。这样会导致无法六星开局。更糟的是，如果选了“借助战”它就会一直刷新助战界面（只有5希望时这样做当然是没用的）。

### 有什么好的想法？

建议给开局的那几个奖励的选择加上优先级。就像选择”刷开局"之后它会做的那样

**Comment by Manicsteiner** [comment]
是哪个主题，水月吗

**Comment by status102** [comment]
duplicate of #7610
