### ISSUE TITLE
肉鸽挂机大约2~3小时左右后游戏自行关闭

### ISSUE THREAD

**Issue by 520firewire520** [MaaAssistantArknights/MaaAssistantArknights#8334]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

刚回坑，上次使用还是在去年5月，以前一挂机可以挂到隔天天亮，但现在却出问题了，连续3天这样了，一开始以为是电脑休眠的问题，第2天试了一下发现不是，我又觉得可能是模拟器的问题，但我第2天手刷萨米至少8小时模拟器也没关掉，那为啥睡觉前把maa一挂，3小时内就会自己停掉且模拟器跳回首页呢?

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14291703/debug.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/126182822/385c41f3-d1ae-4890-bfe4-be0e7c89258f)
如截图所示，挂机时间约为6:57~9:41

### 还有别的吗？

使用蓝mumu12模拟器(v3.8.1)2675
处理器:i5-7400
记忆体8g
64位元,x64
操作系统:win10专业版
maa資料夾放在c槽

**Comment by ABA2396** [comment]
谁闪退就是谁的问题

**Comment by Constrat** [comment]
Isn't this emulator related?

**Comment by Rbqwow** [comment]
`/data/anr/`里面有app未响应的记录
`/data/system/dropbox/`里面有app崩溃的记录
找找看？

**Comment by suujonH** [comment]
近期使用蓝叠模拟器挂肉鸽，遭遇同样问题。推测与模拟器无关。
但这个手刷肉鸽没关闭，有点玄学....MAA会导致游戏bug？

**Comment by ABA2396** [comment]
maa用的adb和模拟器交互，要是是模拟器没处理好通讯导致内存泄漏之类的事情闪退了也是模拟器的问题，这种解决不了
可能和8G内存有点关系，占用上去了确实可能带不动
