### ISSUE TITLE
MAA报错 试图运行无效的指令

### ISSUE THREAD

**Issue by qingfengxdm** [MaaAssistantArknights/MaaAssistantArknights#8335]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

一打开maa就显示：无效的命令，试图预估无效的指令

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[Desktop.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14292380/Desktop.zip)

### 截图

![QQ截图20240215143032](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137624999/5376d2ab-9b1a-42d4-8344-1597ead85cea)

**Comment by status102** [comment]
缺少更详细的信息，比如是第一次使用MAA吗？win7win10？弹窗是何时弹出的？完全启动后还是启动前？有录像吗？

看起来不太像是由MAA本身导致的问题

**Comment by Rbqwow** [comment]
我先猜一个ntstatus码
```
0xC000001D
{EXCEPTION} Illegal Instruction An attempt was made to execute an illegal instruction.
```
看看事件查看器有没有啥东西
~~和内核爆了~~
