### ISSUE TITLE
自动编队经常把锏识别为煌

### ISSUE THREAD

**Issue by qwew2331** [MaaAssistantArknights/MaaAssistantArknights#8338]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动编队经常会把锏识别为煌，已经重新安装过，用的内测版，已经好几个版本了这个问题都没有解决，不知道是不是个例，以前没有这个问题，最近才开始这样。

### Version

Resource Version: 千秋一粟
UI Version: v5.1.1-alpha.1.d010.g6c79ff49e 
Core Version: v5.1.1-alpha.1.d010.g6c79ff49e

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14298004/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14298005/gui.log)

### 还有别的吗？

操作系统win10 模拟器为mumu12

**Comment by status102** [comment]
log内未搜索到`锏`相关内容，能给一下不包含其他内容的log吗
