### ISSUE TITLE
挂着MAA定时任务到一半电脑就关了

### ISSUE THREAD

**Issue by YuhangTom** [MaaAssistantArknights/MaaAssistantArknights#8340]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

电脑一直开着挂MAA定时任务和模拟器，结果很多次发现电脑直接被关了，没有开执行任务后关机，并且重新开以后会发现MAA执行任务到一半就没了，比如基建换完了但是理智还没清，不敢保证是MAA有问题但不知道记录里能不能看出点什么

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

这次出现是在日志记录里2024-02-15 15:01:00（我定时执行的时间）左右
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14303271/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14303274/gui.log)

### 截图

我的任务顺序，应该可以看出来执行到一半就没了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45880737/ac8ef8ca-518a-4ce9-b085-7e58e7ccf226)

### 还有别的吗？

BlueStacks 5.13.5.1001 P64
Win11 10.0.22631

**Comment by Rbqwow** [comment]
看看事件查看器 里面有关机原因

**Comment by YuhangTom** [comment]
好像是没记录具体原因的意思
[-](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8340#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8340#) <System>
  <Provider Name="Microsoft-Windows-Kernel-Power" Guid="{331c3b3a-2005-44c2-ac5e-77220c37d6b4}" /> 
  <EventID>41</EventID> 
  <Version>9</Version> 
  <Level>1</Level> 
  <Task>63</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000400000000002</Keywords> 
  <TimeCreated SystemTime="2024-02-15T22:52:46.8992465Z" /> 
  <EventRecordID>116984</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="4" ThreadID="8" /> 
  <Channel>System</Channel> 
  <Computer>YTL3080</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
[-](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8340#) <EventData>
  <Data Name="BugcheckCode">0</Data> 
  <Data Name="BugcheckParameter1">0x0</Data> 
  <Data Name="BugcheckParameter2">0x0</Data> 
  <Data Name="BugcheckParameter3">0x0</Data> 
  <Data Name="BugcheckParameter4">0x0</Data> 
  <Data Name="SleepInProgress">0</Data> 
  <Data Name="PowerButtonTimestamp">0</Data> 
  <Data Name="BootAppStatus">0</Data> 
  <Data Name="Checkpoint">0</Data> 
  <Data Name="ConnectedStandbyInProgress">true</Data> 
  <Data Name="SystemSleepTransitionsToOn">0</Data> 
  <Data Name="CsEntryScenarioInstanceId">10</Data> 
  <Data Name="BugcheckInfoFromEFI">false</Data> 
  <Data Name="CheckpointStatus">0</Data> 
  <Data Name="CsEntryScenarioInstanceIdV2">10</Data> 
  <Data Name="LongPowerButtonPressDetected">false</Data> 
  <Data Name="LidReliability">false</Data> 
  <Data Name="InputSuppressionState">0</Data> 
  <Data Name="PowerButtonSuppressionState">0</Data> 
  <Data Name="LidState">3</Data> 
  </EventData>
  </Event>

**Comment by Rbqwow** [comment]
不是睡眠睡死了就是电源供电不足
烤个机试试

**Comment by YuhangTom** [comment]
好的 我研究研究 谢谢！
