### ISSUE TITLE
刷理智任务因未知原因卡住

### ISSUE THREAD

**Issue by Mou-Froski** [MaaAssistantArknights/MaaAssistantArknights#8341]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

执行刷理智任务时，进入终端界面，然后不动了

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14304262/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14304264/gui.log)

### 截图

02-16 09:36:20 开始任务：Fight
02-16 09:36:51 任务出错：Fight
02-16 09:36:51 任务已全部完成！

### 还有别的吗？

mumu12

**Comment by ABA2396** [comment]
重启下

**Comment by Mou-Froski** [comment]
好吧……重启mumu模拟器后能自动刷理智了
