### ISSUE TITLE
信用购物优先购买子串问题：区分**装置**和**破损装置**

### ISSUE THREAD

**Issue by veteran233** [MaaAssistantArknights/MaaAssistantArknights#8342]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA的“获取信用及购物”中，优先购买为：**固源岩;装置**
在实际购买中，没有办法区分**装置**和**破损装置**

### Version

|||
|-|-|
|资源版本号|千秋一粟|
|UI版本号|v5.1.1-alpha.1.d010.g6c79ff49e|
|Core版本号|v5.1.1-alpha.1.d010.g6c79ff49e|

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14305616/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14305620/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14305623/asst.log)

**Comment by ABA2396** [comment]
这玩意是不是可以加个引号包起来表示全字匹配什么的（？）
cc @MistEO  @status102

**Comment by status102** [comment]
直接full match? 除了对玩外服的人可能不太友好
