### ISSUE TITLE
B服登录有时会弹出隐私政策提示

### ISSUE THREAD

**Issue by liemark** [MaaAssistantArknights/MaaAssistantArknights#8343]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

由于经常有多设备切换账号的需求，B服可能时常会弹出隐私政策提示，而MAA启动时不会点击同意，遇到了很多次，应该是没有加入这个功能？

### 有什么好的想法？

希望启动时能够识别隐私政策提示并点击同意

### 其他内容

![Screenshot_20240216-151336](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115876720/cbe11385-99a2-4f39-ad98-e23fef812232)

**Comment by ABA2396** [comment]
不会做这个功能的
