### ISSUE TITLE
自动战斗进入子弹时间后无法开启技能

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#8347]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

抱歉没时间去翻以前的issue，正在改自动战斗作业，如有关联麻烦下面加上吧
maa://32969
每个maa进程，第一次运行时，可以正常放技能，但是第二次及以后会按两下暂停然后退出子弹时间

### Version

Resource Version: 千秋一粟
UI Version: v5.1.1-alpha.1.d010.g6c79ff49e
Core Version: v5.1.1-alpha.1.d010.g6c79ff49e

### 日志文件

第一组：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14310499/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14310501/gui.log)

第二组：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14310504/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14310505/gui.log)

第三组：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14310506/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14310507/gui.log)

对于第三组有一处时间：

<img width="210" alt="微信图片_20240216194613" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/2d3ecf69-83a3-4e98-8059-200415a3465b">
图中19:00:57的bullet time处就是8杀10费想要放技能的位置
在这个时间之前以第一组、第二组、第三组的使用顺序测了大约十遍，都是maa进程启动后的第一次运行可以正常放技能，之后就不行

### 截图

自动战斗操作如下，第二次运行及以后，放技能写不写坐标都开不出来
<img width="560" alt="微信图片_20240216195026" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/596632a1-d0a8-4225-83a9-e8c87dfc0215">

下面是放技能失败实录

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/13e434b6-e1be-4cfd-ab38-3554feb9e2e9

下面是群友的放技能成功拍屏

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/55e22e3b-9b15-4540-a3a4-7ad0aaccaec9

### 还有别的吗？

好群友给试了一遍，他的maa第二次运行也放出来技能了，所以可能是我设备或者maa的问题，我这三组maa是复制粘贴出来的
写issue的时候脑子比较乱，有啥忘说了的回来再说

**Comment by Daydreamer114** [comment]
关联问题： #7780

**Comment by status102** [comment]
如果同7780，则已解决，更新最新内测看看
