### ISSUE TITLE
hs-s关无法被识别

### ISSUE THREAD

**Issue by zeto1979** [MaaAssistantArknights/MaaAssistantArknights#8348]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

s关显示无法被识别，不知道是普遍的还是我个人这样

### Version

Resource Version: 千秋一粟
UI Version: v5.1.1-alpha.1.d010.g6c79ff49e
Core Version: v5.1.1-alpha.1.d010.g6c79ff49e

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14311141/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14311145/asst.log)
20：40左右

### 截图

![QQ截图20240216204849](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144797799/d82b6fe8-f0ab-47a1-85dd-492bba9800fb)

**Comment by ABA2396** [comment]
地图资源没更新吧？重启下试试

**Comment by status102** [comment]
```
[2024-02-16 20:44:45.200] <1><> HTTP: OK GET https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/version.json
[2024-02-16 20:44:45.302] <1><> HTTP: NotModified GET https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/version.json
```

**Comment by status102** [comment]
打开MAA，等待资源热更，然后重启即可解决

**Comment by zeto1979** [comment]
> 打开MAA，等待资源热更，然后重启即可解决 刚刚关掉了一台滞后的资源热更服务器（不知道为何被错误的打开了

解决了，非常感谢
