### ISSUE TITLE
5.1.0版本 怀黍离 自动战斗无法识别关卡

### ISSUE THREAD

**Issue by zhangfelix** [MaaAssistantArknights/MaaAssistantArknights#8349]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新版本选择“稳定版”，点击检查更新，显示是最新版。此时
直接引用的MAA copilot链接或者下载好的JSON文件均无法使用，提示“读取文件失败！”“不支持的关卡，请检查关卡名！”
![Xnip2024-02-16_20-55-58](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16531867/9bc1e85a-1f8e-4866-8822-d4bc734d00e4)

更新版本选择“内测版”，点击检查更新，显示是最新版。同样是上面的提示。

### Version

![Xnip2024-02-16_21-01-53](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16531867/54e0eb95-ed1e-4ad0-8515-9dd728c740bd)

### 日志文件

暂无资料

**Comment by zhangfelix** [comment]
在“一键长草”的刷理智环节会出现“UnknownStage，放弃上传企鹅物流“的提示。
![Xnip2024-02-16_21-43-03](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/16531867/9f928699-beba-4a1f-a8b5-dcd8fb584e57)

**Comment by status102** [comment]
![1 EHPYL2~EBPA{9B43{X)4W](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/5307361d-178f-4484-ac1d-272dad016159)
