### ISSUE TITLE
希望能加一个基建换班表的功能

### ISSUE THREAD

**Issue by morlegion** [MaaAssistantArknights/MaaAssistantArknights#835]
现在已经有了抄作业功能了，可以把基建换班表也弄成类似的文档，启动后选择换班表则按照换班表在固定位置换上/换下固定干员。目前有了黑键以后迷迭香宇宙大加强，所以如果能支持迷迭香宇宙就好啦。

**Comment by MigdalBavel** [comment]
附议一下。全局自动逻辑虽然理论上可以做到，但比如每当出个新的基建干员尤其是新基建技能逻辑需要重写也会增加不少额外工作量吧？换班表可以作为不冲突的另一种选择同时存在挺好的。

**Comment by MistEO** [comment]
准备做自定跨设施计算了，不会做排班表
