### ISSUE TITLE
专精技能完成后识别信息显示干员名称（黍）错误

### ISSUE THREAD

**Issue by RedosWho** [MaaAssistantArknights/MaaAssistantArknights#8352]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

总之是黍一技能专精完成之后maa识别到了，但是显示的信息里不是“黍”而是“委”。
一个无伤大雅的小问题（

### Version

UI Version: v5.1.1-alpha.1.d013.gf4df22907
Core Version: v5.1.1-alpha.1.d013.gf4df22907

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14317723/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14317724/asst.log)

### 截图

![Snipaste_2024-02-17_12-32-20](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/130947843/c591311a-162b-4037-8396-13dbfe077834)

**Comment by SherkeyXD** [comment]
因为黍这个字经常识别成委 后端做了替换但是日志输出的还是原来的）
