### ISSUE TITLE
萨米肉鸽卡在了密文宣告

### ISSUE THREAD

**Issue by lioshounet** [MaaAssistantArknights/MaaAssistantArknights#8353]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在挂机肉鸽一段时间之后，模拟器会卡在，密文宣告界面，目前在雷电模拟器和mumu模拟器都有触发，且maa并不会因此自我停止，而是处于一种运行，但无动作的状态

### Version

UI：5.1.0
core：5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14317740/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14317741/gui.log)

时间是在02-17 11:30到02-17 12:30之间

### 截图

![Snipaste_2024-02-17_12-38-16](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49356266/22531fa1-e40c-4e28-9d55-4b6bd3593f01)

### 还有别的吗？

目前在雷电模拟器和mumu模拟器都有触发，mumu12 V3.8.1，雷电9.0.66
windows11 22H2 22621.3155

**Comment by SherkeyXD** [comment]
这应该是你在这个模拟器上第一次打萨米肉鸽并且打开宣告界面吧

关掉之后下次应该就正常了 maa目前没有做这个适配

**Comment by fayeharuna** [comment]
我也有这个问题，肉鸽过程中会莫名打开密文版然后卡住。

**Comment by ABA2396** [comment]
这个界面只有重装方舟后第一次打开会遇到
