### ISSUE TITLE
自动肉鸽模式下因终端任务栏被占用无法开启

### ISSUE THREAD

**Issue by Shvak1** [MaaAssistantArknights/MaaAssistantArknights#8356]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在进入自动肉鸽模式后，游戏会进终端，但此时如果终端右侧栏被生息演算和其他占用而没有显示肉鸽的话，maa不会自动点击下方的栏目进入肉鸽，只会一直不断地退出终端然后再次进入再次退出

### Version

Resource Version: 千秋一粟
UI Version: v5.1.1-alpha.1.d014.g4a464c14e
Core Version: v5.1.1-alpha.1.d014.g4a464c14e

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14318966/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14318968/gui.log)

### 还有别的吗？

mumu12

**Comment by SherkeyXD** [comment]
Duplicate of #8248
