### ISSUE TITLE
战斗功能的剩余体力规划

### ISSUE THREAD

**Issue by Deo-777** [MaaAssistantArknights/MaaAssistantArknights#8361]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

在maa终端填写的预期使用的体力药/石头<1时，更改游戏客户端内连战次数为从下往上数最后一个没有带有特殊标记的战斗次数的选项。

**Comment by status102** [comment]
自动调整次数与指定次数设置冲突，可以使用剩余理智功能清剩下的理智，或者指定次数为1
