### ISSUE TITLE
*不确定错误来源，仅作为参考用*雷电模拟器emulator-5554端口出现连接故障

### ISSUE THREAD

**Issue by TimCrownie** [MaaAssistantArknights/MaaAssistantArknights#8363]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

前置条件说明：
1. 雷电模拟器的ADB端口以emulator-5554开始，后续每新增一个模拟器依次在端口号末尾+2（5554、5556、5558、5560）；
2. 本人在此之前一直使用雷电模拟器国际版且有超长期运行历史（模拟器一整个月没有关闭，期间仅对MAA进行更新），均无下文提到的异常情况。

问题描述：
1. 在撰写此Issue前几日偶然发现，emulator-5554会在运行一段时间内直接断开ADB连接（表现为MAA处显示“连接断开”，在Terminal中输入"adb devices"后列出设备亦不存在emulator-5554；但emulator-5556、5558均表现正常；
3. 在更换至Bluestacks 5后出现了较为严重的闪退问题（运行十几分钟至数小时后随机掉落）、MuMu则出现了更严重的内存溢出问题（运行一段时间后，在MemReduct开启97%阈值清理的情况下仍然出现内存溢出，系统直接卡死），综合上述体验和操作习惯，决定停留在雷电模拟器，安装了雷电模拟器绿色版（版本号不知道，但模拟器Android版本为Android 9），而后正常运行了约8小时，期间没有出现任何问题；
4. 在今天早上醒来后，发现所有与模拟器连接的MAA均报错（包括但不限于“连接断开”“截图失败”等，log中如果包含配置名称为α/β/γ的均为与模拟器连接的配置），但与手机连接的MAA表现正常；
5. 连接错误时若尝试重新连接，出错的模拟器与MAA将会异常占用巨量CPU（表现为CPU占用从通常的20%上下飙升至50-60%，三开模拟器下的处理器总功耗从50W左右飙升至70W以上，甚至达到100W的自定义PL1），但仍无任何反应，且直接进行点击等操作均仍表现正常；
6. 发现问题后重新安装回雷电模拟器国际版，但采取了弃用emulator-5554的方式（保留使用该端口的模拟器但不使用，然后建立新的模拟器），截至撰写此Issue时仍表现正常，截图速度与操作均无异样（上传的log中应同时包含有出错片段与正常执行片段）。

### Version

Resource Version: 千秋一粟
UI Version: v5.1.1-alpha.1.d014.g4a464c14e
Core Version: v5.1.1-alpha.1.d014.g4a464c14e

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14321791/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14321795/gui.log)

### 截图

本人因为过于心急所以没有截图，实在非常抱歉（土下座

### 还有别的吗？

模拟器版本: 雷电模拟器国际版1.2.5.1
操作系统：Windows 10 Pro 22H2（内部版本号19045.3391），2024年2月1日安装
配置：Intel Core i7-13700H+16GB RAM+nVIDIA GeForce RTX 4060 Laptop+2*1TB SSD
MAA交流群内有群友提到雷电模拟器的如下问题：
1. ADB连接会莫名中断，需要重新设置再重启才能连接
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63519560/9b569f12-f8c2-4114-ba41-e9546844b1ff)
2. 刷理智出错和肉鸽运行了没反应
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63519560/eb5b2c92-cd66-4768-b1de-38a624984b02) 
![image_2024-02-18_10-23-51](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63519560/512e2423-91a8-4d92-a00d-029806504b72)

PS. 不太会用Discussion，所以先发了个Issue；严格上来说不太能算得上是合格Issue，因为到现在也没有真正找到问题的源头，请见谅。

**Comment by AshdoII** [comment]
同样遇到模拟器连接问题且不确定问题来源，重新设置任然无效。回退到5.0.0版本可以正常使用，5.1.0版本就无法正常连接。模拟器是mumu2.3.6，系统为Windows Server 2022。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14322664/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14322665/gui.log)

**Comment by Rbqwow** [comment]
> 同样遇到模拟器连接问题且不确定问题来源，重新设置任然无效。回退到5.0.0版本可以正常使用，5.1.0版本就无法正常连接。模拟器是mumu2.3.6，系统为Windows Server 2022。 [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14322664/asst.log) [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14322665/gui.log)

自5.1.0开始 mumu6已放弃支持 想用需要关闭自动检测 换成通用模式 然后手动填adb和连接地址
~~这模拟器官方都放弃半年了该换了~~

**Comment by AshdoII** [comment]
> > 同样遇到模拟器连接问题且不确定问题来源，重新设置任然无效。回退到5.0.0版本可以正常使用，5.1.0版本就无法正常连接。模拟器是mumu2.3.6，系统为Windows Server 2022。 [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14322664/asst.log) [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14322665/gui.log)
> 
> 自5.1.0开始 已经放弃对mumu6的特殊支持 想用需要关闭自动检测 换成通用模式 然后手动填adb和连接地址 ~这模拟器官方都放弃半年了该换了~

改用通用模式正常使用，感谢。不过模拟器是大概率不会换的，因为我用的是windows server并且通过远程连接控制，没有物理连接的显示器。mumu2.3.6是一个能比较好的在这个状况下调用显卡的版本（最开始我尝试的是和pc上一样的雷电模拟器，模拟器本身问题不断）。

**Comment by Rbqwow** [comment]
简单看了一眼日志 出错的部分都看不到了
asst日志从6:25开始 对应gui日志的第3644行 但是gui日志里写着最后一次出错是6:22 在第3598行 正好错过
(你干嘛要反复开关那么多次还跑了遍长草日志都顶掉了喂

**Comment by TimCrownie** [comment]
> 同样遇到模拟器连接问题且不确定问题来源，重新设置任然无效。回退到5.0.0版本可以正常使用，5.1.0版本就无法正常连接。模拟器是mumu2.3.6，系统为Windows Server 2022。 [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14322664/asst.log) [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14322665/gui.log)

建议更换模拟器，然后看看问题是否仍然存在

**Comment by TimCrownie** [comment]
> 简单看了一眼日志 出错部分的核心日志都看不到了 asst日志从6:25开始 对应gui日志的第3644行 但是gui日志里写着最后一次出错是6:22 在第3598行 正好错过 (你干嘛要反复开关那么多次还跑了遍长草日志都顶掉了喂

草 因为我后面处理好之后就在正常刷理智干活啥的了（
