### ISSUE TITLE
肉鸽存钱时投资显示异常

### ISSUE THREAD

**Issue by 0512www** [MaaAssistantArknights/MaaAssistantArknights#8364]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在第8次投资时出现第1次异常，显示已投资-261（+-295），第18次投资时出现第2次异常，显示已投资-607，存款显示变成15

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14322074/asst.zip)
[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14322076/gui.zip)

### 截图

<img width="198" alt="屏幕截图 2024-02-18 182023" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/160393519/e63ad5d7-4604-4237-a55e-4f8a3d3a4121">
<img width="204" alt="屏幕截图 2024-02-18 182037" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/160393519/3c4ec321-edd9-4512-888c-7be90449f59e">

**Comment by ABA2396** [comment]
#8326 fixed

**Comment by ABA2396** [comment]
#8326 fixed
