### ISSUE TITLE
關於繁中服的"登入"導致無法成功喚醒的問題

### ISSUE THREAD

**Issue by tommy5837947** [MaaAssistantArknights/MaaAssistantArknights#8368]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

當繁中服在登入時，每過一段時間會跳出此畫面，導致無法正常喚醒，請問可否加個點擊登入的步驟?~
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/85089982/0d39b2a9-f545-4add-b781-3b74d645daa0)

### Version

Resource Version: 前路迴響
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14323812/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14323813/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/85089982/43e387c6-f1a4-4c5b-82af-a273f20f77b4)

### 还有别的吗？

其他操作都正常 只是每過一段時間會因此卡住，所以希望能夠修復，辛苦作者了~

**Comment by status102** [comment]
Duplicate of #7832
