### ISSUE TITLE
还是基建顺序无法保存问题

### ISSUE THREAD

**Issue by Sduck-Inverse** [MaaAssistantArknights/MaaAssistantArknights#8369]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

#4568 虽然说修复了，但是好几个号还是打开都是默认换班顺序，按照脚本应该是先换菲亚梅塔的，人在控制中心，应该宿舍第一还是中枢第一？

### Version

Resource Version: 千秋一粟
UI Version: v5.1.1-alpha.1.d022.g1a65cd840
Core Version: v5.1.1-alpha.1.d022.g1a65cd840

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14325162/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14325163/gui.log)
[1708314095702167托管.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14327544/1708314095702167.json)

**Comment by ABA2396** [comment]
ui的日志里只看到了17号有执行过换班任务，core的日志只有19号之后的。菲亚梅塔 `是否使用` 和 `是在换班前还是换班后恢复心情` 是根据这些参数决定的，你要选了换班后换那就是最后换
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/1473d7cf-7ecd-4c83-914e-b2a10706ee6e)

**Comment by status102** [comment]
asst.log不包含换班相关信息，请重新上传，如果使用了自定义基建，请一并附带自定义文件

**Comment by Sduck-Inverse** [comment]
谢谢，不过为什么我写了换班前用还是在最后换晚班才……

**Comment by Sduck-Inverse** [comment]
> asst.log不包含换班相关信息，请重新上传，如果使用了自定义基建，请一并附带自定义文件

了解，不包括换班信息是因为主号一直挂着，多开关闭不会保存小号信息吧？等活动结束了我一个个换号保存。

**Comment by status102** [comment]
日志文件在>4mb后会有日志翻转，以及提供一下自定义文件方便开发人员测试
