### ISSUE TITLE
建议OF-1除了刷助战再新增一个刷模组任务

### ISSUE THREAD

**Issue by ghg6666678** [MaaAssistantArknights/MaaAssistantArknights#8370]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

<img width="600" alt="679aa7cc6a52d174507c6a235ec14cf0" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97784469/ddb4bbe9-6c7e-40d7-b94a-4a63249264aa">
如图所示，无法进行标题所述操作（图上是改了关卡，实际上就是OF-1）

### 有什么好的想法？

建议OF-1除了刷助战再新增一个刷模组任务，就是可以选定代理次数，而不是一次就停

**Comment by status102** [comment]
可以用自动战斗指定次数

**Comment by ABA2396** [comment]
OF-2之后的也都可以刷，或者就自动战斗里选下拉框里那个OF-1的作业，带个先锋
