### ISSUE TITLE
萨米肉鸽抗干扰指数不足，且并行分支与直线下一步节点都为诡异行商时会出现无限点击并行分支的诡异行商导致无法推进

### ISSUE THREAD

**Issue by Lumomoo** [MaaAssistantArknights/MaaAssistantArknights#8374]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽抗干扰指数不足，且并行分支与直线下一步节点都为诡异行商时会出现无限点击并行分支的诡异行商导致无法推进bug

### Version

UI Version: v5.1.0

### 日志文件

-

### 截图

![1708420867822](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110466731/8143cb88-9f3f-467e-a906-7be0d9d6ce75)
![1708420912028](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110466731/dd98bd59-37f5-4569-9e31-aca4511c8328)

### 还有别的吗？

-

**Comment by SherkeyXD** [comment]
Duplicate of #7549
