### ISSUE TITLE
自动安装更新后未能正确重启maa

### ISSUE THREAD

**Issue by MobiusT** [MaaAssistantArknights/MaaAssistantArknights#8376]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

maa设置了定时任务和自动检查更新，其中昨天19点任务正常处理完毕，早上5点因为maa关闭导致任务没有执行，maa和模拟器我均未手动关闭，推测是自动安装更新重启后没能正确重启，但是手动开启maa能正确启动并弹出更新日志页面，因为默认maa不关闭，没有设置定时任务启动maa，个人评估应该和之前说的的换.net8导致定时任务异常的issue没有关系

### Version

Resource Version: 千秋一粟
UI Version: v5.1.1-alpha.1.d025.g15b537b0e
Core Version: v5.1.1-alpha.1.d025.g15b537b0e

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14351761/gui.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14351763/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14351765/asst.log)
[gui.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14351801/gui.json)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62053271/bfe88cd8-d156-4a6c-a944-2e72ed0de6dd)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62053271/0617ead4-6960-45dc-8df7-3cc607b9144b)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62053271/71c8a535-1b1b-4f75-96ca-2c4d52a37f48)

### 还有别的吗？
我是双开两个maa+两个模拟器，还有个maa配置就是json里小号配置，同样早上处于maa关闭的状态，如有需要我另外提供日志
_No response_

**Comment by Constrat** [comment]
@MobiusT I have a very similar setup to yours. 2 MAA, with 2 emulators running with a schedule. The only suggestion I can give you is this:
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/01f6408b-45f0-4f16-b682-924bcee1920e)
Remove `Schedule Update Check`, but most importantle "Auto Install Update".
As MAA is running completely out of your supervision this will completely remove the possibility of issues.

**Comment by MobiusT** [comment]
@Constrat Thank you for your suggestion，I' ll follow it to avoid the same situation.

Actually，I just think that MAA can' t restart after update is unusual, and trying to report this situation
