### ISSUE TITLE
基建换班干员选择错位

### ISSUE THREAD

**Issue by Ptilopsis01** [MaaAssistantArknights/MaaAssistantArknights#8377]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

基建自动换班时所有干员选择都出现了错位，即实际选择的是列表中和他相邻的干员，完全没法用，希望尽快修复

### Version

Resource Version: 千秋一粟
UI Version: v5.1.1-alpha.1.d029.g396460fe7
Core Version: v5.1.1-alpha.1.d029.g396460fe7

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14356929/debug.zip)

**Comment by status102** [comment]
cc @horror-proton

**Comment by horror-proton** [comment]
草, 符号写反了

**Comment by Tsukiko-Official** [comment]
我也遇见了这个问题，怎么解决的？
