### ISSUE TITLE
夜神模拟器自动连接路径错误

### ISSUE THREAD

**Issue by FredEdie** [MaaAssistantArknights/MaaAssistantArknights#838]
自动连接后路径自动带了一个\.
手动删除后连接还会加上
![QQ截图20220611123231](https://user-images.githubusercontent.com/18080521/173172609-07a43a25-9ebe-41f9-ba27-1815a25e5a24.jpg)

昨晚上还没事，今天更新3.9.5.2后出现的，重新安装3.9.5还是一样连接不上
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883231/asst.log)

**Comment by MistEO** [comment]
不是那个点的问题，你日志被刷新掉了，再发一个看看
