### ISSUE TITLE
执行maa时蓝屏

### ISSUE THREAD

**Issue by delaube1** [MaaAssistantArknights/MaaAssistantArknights#8381]
### 说说你遇到的问题？

一挂maa就有几率蓝屏，不挂就没有出现过，最近很频繁，挂maa就蓝屏
发生于2024-02-22 12:58之前，版本是Core Version: v5.1.0
操作系统win10，mumu12，r7-4800h，rtx2060,16g运行内存且磁盘空间充足

**Comment by ABA2396** [comment]
那我只能帮你算一卦了

**Comment by status102** [comment]
缺少信息
