### ISSUE TITLE
萨米肉鸽：刷等级，抗干扰不足时重复进入树篱

### ISSUE THREAD

**Issue by jiachenhan** [MaaAssistantArknights/MaaAssistantArknights#8382]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽刷等级时，由于抗干扰等级不足。重复进入树篱。
观察一段时间没有退出处理导致死循环

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14369089/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14369091/gui.log)

### 截图

![f9647c841e9cc6c705ef4778830ffdb](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59958633/00b35f32-954c-439a-b0aa-e357ed776388)
![62615a6a1c3d9f0ec4d9d4f210dfc9b](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59958633/5bec1f90-92ed-4d1f-bacf-4b6275fd95bb)

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59958633/23f48685-b377-48b3-a6f6-a7911e968da4)

**Comment by status102** [comment]
Duplicate of #7789
