### ISSUE TITLE
基建换班宿舍菲亚梅塔识别错误

### ISSUE THREAD

**Issue by hkhllyzh** [MaaAssistantArknights/MaaAssistantArknights#8383]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在自动换班之中，对宿舍进行干员进驻时找不到菲亚梅塔干员，导致一直循环卡死。
如果在换班过程中手动对菲亚梅塔进行点击确认跳过该宿舍则后续正常进行（？）所以似乎只是菲亚梅塔一个干员没识别出来？
如图，卡了3分钟的宿舍换班（在最开始的菲亚梅塔环节已经手动将肥鸭放进去了，到了dorm0阶段则一直循环，zhi'zhi直至可能触发了超时跳过？）

### Version

Resource Version: 千秋一粟
UI Version: v5.1.1-alpha.1.d030.g078feead6
Core Version: v5.1.1-alpha.1.d030.g078feead6

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14369101/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14369102/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/26716996/9ae0ba73-9ed9-410a-aa84-570204a12ddc)

### 还有别的吗？

模拟器BlueStacks App Player2 5.10.0.1085 N64
操作系统Win10
配置如下
[gui.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14369117/gui.json)

**Comment by ABA2396** [comment]
是不是因为开了排除已进驻干员，但是菲亚梅塔在宿舍里，排除之后就看不到了

**Comment by hkhllyzh** [comment]
> 是不是因为开了排除已进驻干员，但是菲亚梅塔在宿舍里，排除之后就看不到了

不是的，是没有勾选未进驻，并且已经屏幕划过去了仍然不会选中肥鸭
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/26716996/dc88129f-68c0-4b40-b93c-8f529073f8c8)
再补一个把肥鸭放在宿舍外面的实验（也没识别选中
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/26716996/7a905803-63a7-4178-90bf-0b031ac1d22c)

**Comment by hkhllyzh** [comment]
这个bug的问题在于如果不在maa换带有肥鸭的宿舍的时候手动确认肥鸭，则后续的换班选人全部都不对（不知道是不是点错了），而手动确认第一次的肥鸭007巫恋之后，后续从trade0到manufac3都没问题，但是回到dorm0之后则又会混乱，如果不手动干预则会将此房间本应该进驻的车尔尼和爱丽丝也影响

**Comment by horror-proton** [comment]
fixed in 6f00c2db39bf55073b0335fbceee57d7e5821585
