### ISSUE TITLE
肉鸽 不期而遇时闪退

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#8384]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

一进这个界面就闪退，有佬帮忙看看log吗

### Version

Resource Version: 千秋一粟
UI Version: v5.1.1-alpha.1.d051.g573a16e14
Core Version: v5.1.1-alpha.1.d051.g573a16e14

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14372172/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14372176/gui.log)
我刚开了一次肉鸽，发生点很往后，印象里是17:37左右

### 截图

![MuMu12-20240222-174905](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/32f91799-191b-485a-8bdc-d7227e183f7a)

**Comment by Daydreamer114** [comment]
![MuMu12-20240222-175357](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/f96a2815-3fdd-4876-9347-81090fa21593)
这个也闪，是我肉鸽资源缺失了吗

**Comment by Daydreamer114** [comment]
现在是进不期而遇就闪退了
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14372459/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14372461/gui.log)

**Comment by Daydreamer114** [comment]
闪退方式是卡死然后闪退

**Comment by ABA2396** [comment]
可能和 7e97aadb5fa3f84942e350dff958c19db78de00f 有关，等下看看

**Comment by Daydreamer114** [comment]
啊？等我找下

**Comment by Daydreamer114** [comment]
<img width="1512" alt="截屏2024-02-22 19 41 59" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/3eda96ce-6af1-4752-9ac6-69b30629511b">
这个，tu图里最后一句就是闪退后打开看见的最后一句

**Comment by Daydreamer114** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/d53294e4-c882-4c65-b7ef-42e30c39c0e6

**Comment by Daydreamer114** [comment]
> 2024.02.22.19.46.55.mp4

目前任何不期而遇事件都是这个流程，点开之后卡死闪退

**Comment by Traciaz** [comment]
我也有这个问题 进不期而遇直接闪退 昨天没问题

**Comment by Traciaz** [comment]
我是挂的傀影 同款闪退 进不期而遇在选项的地方直接自己消失 雷电模拟器

**Comment by ABA2396** [comment]
7fe35dfa244dce51a53396c18ee59dafec7eaa6b Should fixed

**Comment by ABA2396** [comment]
本地跑了下好像可以，过半小时内测版打出来更新看看

**Comment by Daydreamer114** [comment]
> 本地跑了下好像可以，过半小时内测版打出来更新看看

嗯能用了，辛苦
