### ISSUE TITLE
在打开某些网址时报错

### ISSUE THREAD

**Issue by 2958918762** [MaaAssistantArknights/MaaAssistantArknights#8388]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动战斗页面，最下面的‘自动战斗作业分享’和‘自动战斗地图坐标’打开会报错，以及报错页面的链接，打开时也报错

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14381535/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14381536/gui.log)

### 截图

![b0da78de21a164d18489ae56b715743](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/107120299/a0d5b045-5ed4-47e7-b322-96e7f6dfd9da)

### 还有别的吗？

不知道是不是最近重装了一次系统的原因，c盘清空了，但保留了其他盘，一开始maa都打不开，后来重下用到现在，最近想用自动战斗用不了
mumu模拟器，Win10

**Comment by 2958918762** [comment]
没事了，改了电脑上几个浏览器的默认浏览器就好了

**Comment by SherkeyXD** [comment]
> 去设一下默认浏览器

我当初就说肯定会有人没有默认浏览器（

**Comment by ABA2396** [comment]
这种一般只有重装系统会遇到吧？edge肯定会把自己设成默认的）
