### ISSUE TITLE
希望【自动战斗】里能加一个【识别干员】的开始延迟设置

### ISSUE THREAD

**Issue by YlovexLN** [MaaAssistantArknights/MaaAssistantArknights#839]
运行剧情关卡作业的过程中需要手动跳过剧情，
但是【自动战斗】中的【识别干员】这一步骤开始时间过早，
手动跳过步骤刚结束，
【识别干员】就已经在识别第二到第三个干员，
导致第一个干员不能部署，
![QQ截图20220611145524](https://user-images.githubusercontent.com/50139687/173177568-25307961-7fdc-468b-89a0-926366d5150e.png)

故：望能加一个【识别干员】的【延迟识别】之类的设置
       或让MAA自己跳过剧情

**Comment by MistEO** [comment]
现在应该不会了
