### ISSUE TITLE
自动编队逻辑问题

### ISSUE THREAD

**Issue by 2322739526** [MaaAssistantArknights/MaaAssistantArknights#8390]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

![Snipaste_2024-02-23_16-09-22](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/54304280/91e69c6a-e6e3-40eb-94bd-e4702e16c705)
循环到没有的干员直接退出了

### 有什么好的想法？

应该记录缺失干员，继续寻找后续，完成编队后报错，显示所有缺失的干员（如果只缺少一个干员可以设置个借用选项）

**Comment by KevinT3Hu** [comment]
~偷懒被发现了~

在修了在修了

**Comment by KevinT3Hu** [comment]
关于自动借助战
refer to #6458
