### ISSUE TITLE
引航者试炼#4TN-4自动战斗干员放置异常

### ISSUE THREAD

**Issue by AlEcK98** [MaaAssistantArknights/MaaAssistantArknights#8399]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

当maa放置我的锏时，maa将锏放在了（7，4）这一格，而作业中是将锏放置在（7，3）的，不知为何maa将干员放在了错误的位置

### Version

UI Version: v5.1.1-alpha.1.d059.g762e43303
Core Version: v5.1.1-alpha.1.d059.g762e43303

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14392404/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14392405/gui.log)

### 截图

![act4bossrush_04](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161121931/8743cb35-c770-4a12-97e8-8bc860f2892c)
![ZZVEU3ZV 9ABZ 223SRX0ZE](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161121931/8a5cb7ff-f6a1-4f10-a8a2-b78cb88cbc75)
![RD15AV$7{WOQF7KL46 VOJW](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161121931/6ba93617-e922-471d-a292-2d39e432560b)

### 还有别的吗？

官网模拟器

**Comment by AlEcK98** [comment]
追加作业文件
[Uploading MAACopilot_TN-4 - 辞旧岁 (2).json…]()

**Comment by AlEcK98** [comment]
追加作业文件
[MAACopilot_TN-4 - 辞旧岁 (2).json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14392475/MAACopilot_TN-4.-.2.json)

**Comment by status102** [comment]
647cf6d fixed，等待数据热更后重启即可

**Comment by status102** [comment]
下次觉得还有问题的话，直接reopen就好，commit那边评论有可能没看到

**Comment by status102** [comment]
未能复现，建议上传gui.log看看

![Uploading image.png…]()

**Comment by AlEcK98** [comment]
作业代码maa://33494
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14392616/gui.log)

**Comment by status102** [comment]
看上去资源热更出现了点问题，先打了个内测应急一下，等下一个内测更新吧

**Comment by AlEcK98** [comment]
请帮忙看看是否可以排除作业设计出错，谢谢

**Comment by status102** [comment]
> 请帮忙看看是否可以排除作业设计出错，谢谢

如果作业代码和上面那个文件是一样的话就没问题，我拿文件跑着是ok的。
内测预计半小时能内发出来

**Comment by AlEcK98** [comment]
感谢帮助

**Comment by status102** [comment]
> 感谢帮助

感谢反馈
