### ISSUE TITLE
已经修改过config文件的MAA5.1.0版本使用蓝叠模拟器进行多开，自动检测总是导向其中同一个实例而无法精确检测对应实例

### ISSUE THREAD

**Issue by macrolide0** [MaaAssistantArknights/MaaAssistantArknights#8400]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

正如标题所说，在之前版本使用时均无发生过问题。目前我只能不断的手动改变链接地址，似乎读取规则变成了自动读取最新打开实例的链接地址。但在同时作为参考，我使用5.1.1-alpha.1.d054.gac3dcd917版本的MAA时并未出现上述问题，每次均能检测到对应实例。

### Version

UI Version: v5.1.0
Resource Version: 千秋一粟
Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14392473/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14392474/gui.log)

**Comment by SherkeyXD** [comment]
https://maa.plus/docs/用户手册/常见问题.html#蓝叠模拟器每次启动端口号都不一样-hyper-v

手动指定使用的核心编号
