### ISSUE TITLE
生息演算在第一天任务出错

### ISSUE THREAD

**Issue by gwwydsb** [MaaAssistantArknights/MaaAssistantArknights#8404]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，如图

### Version

UI Version: v5.1.1-alpha.1.d069.g33dac7196

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14393289/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14393290/gui.log)
问题出现时间23：14

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/98566957/277fbe92-78f2-4144-a6b3-3cfdeb2abb99)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/98566957/3943fbb0-f05e-4d65-90b0-255822c809e6)

### 还有别的吗？

模拟器：雷电模拟器9.0.64
分辨率：1600×900
操作系统：win10

**Comment by gwwydsb** [comment]
今天换了个分辨率1920×1080又好了

**Comment by gwwydsb** [comment]
刚发完好了它又出错了，今天挂了几个小时都没问题

**Comment by gwwydsb** [comment]
又出错了这次是在任务刚开始在驻扎营地里的时候，游戏内忘截图了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/98566957/e4df38f3-55
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14395409/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14395410/asst.log)
ea-420a-b878-0e10b2ca52c0)

**Comment by SUPERDAIDAI007** [comment]
相同问题，多出现于第一天第一战结束之后
