### ISSUE TITLE
自动肉鸽导航失败

### ISSUE THREAD

**Issue by zwsr** [MaaAssistantArknights/MaaAssistantArknights#8405]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![QQ截图20240225040512](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/5520859/5ce492a3-98b2-407e-bb8f-491650227bc6)
在主菜单直接开始肉鸽任务后导航无法进入肉鸽，卡在如图界面和主界面循环

### Version

千秋一粟
ui:v5.1.0
core:v5.1.0

### 日志文件

日志文件如下
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14394344/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14394345/asst.log)

**Comment by status102** [comment]
duplicate
