### ISSUE TITLE
自动肉鸽无法正确导航

### ISSUE THREAD

**Issue by mc-xx6** [MaaAssistantArknights/MaaAssistantArknights#8407]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

开始自动肉鸽后会进入导航页然后卡住
![Snipaste_2024-02-25_14-00-41](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/79131968/5f079d0d-7e8a-4e07-b5f6-129fc18731f6)
![Snipaste_2024-02-25_14-02-18](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/79131968/4ff6c72d-6d8a-4ec4-a9c9-a1db0453d964)

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14395458/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14395460/asst.log)

**Comment by status102** [comment]
duplicate
