### ISSUE TITLE
疑似启动功能导致软件闪退

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#841]
之前软件正常使用，今天我发现软件增加了启动时同时启动模拟器功能，所以我就打开尝试了一下。打开此功能之后，软件会在启动后几秒内闪退，显示下图错误：
![屏幕截图 2022-06-11 175057](https://user-images.githubusercontent.com/92417243/173182923-3b7fe181-3185-43a3-91eb-6f50d7e3984b.jpg)
之后关闭此功能，软件依然会闪退。以下是log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883620/asst.log)

**Comment by xiaoweiXX** [comment]
现在软件无法正常使用

**Comment by xingyu1272** [comment]
会卡在fight界面 游戏内是在活动关选关界面 也会闪退

**Comment by ABA2396** [comment]
#828 看看这个里面说的方法有没有用

**Comment by ABA2396** [comment]
> 会卡在fight界面 游戏内是在活动关选关界面 也会闪退

有截图和log么

**Comment by xingyu1272** [comment]
> 

关内截图没有 只来的及截到一个已停止工作
这是log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883737/asst.log)

**Comment by ABA2396** [comment]
> > 
> 
> 关内截图没有 只来的及截到一个已停止工作 这是log [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883737/asst.log)

看起来像是adb炸了，建议重启）

**Comment by xiaoweiXX** [comment]
> #828 看看这个里面说的方法有没有用

试了一下，断网有用。但是不知道启动功能是咋影响检查更新功能的🤔

**Comment by MistEO** [comment]
你是 win7 么，不要勾选设置里 `使用 Windows 系统通知推送`

**Comment by xiaoweiXX** [comment]
> 你是 win7 么，不要勾选设置里 `使用 Windows 系统通知推送`

不是Windows7，是Windows10

**Comment by xiaoweiXX** [comment]
> 你是 win7 么，不要勾选设置里 `使用 Windows 系统通知推送`

疑似是更新相关问题导致的，我启动的时候断网就没问题了，但是这样用起来很不方便。
