### ISSUE TITLE
美服傀影肉鸽在别打扰他们事件进入自缚，导致失败

### ISSUE THREAD

**Issue by Lu3422** [MaaAssistantArknights/MaaAssistantArknights#8414]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

美服傀影肉鸽中“别打扰他们”事件选择“靠近听听他们在说什么”进入自缚，导致关卡失败，能否自动选择离开选项

### Version

Resource Version: Trials for Navigator
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14406452/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14406453/gui.log)
13450行，[2024-02-26 22:37:07.270] <1><> 事件: 别打扰他们

### 截图

![2024-02-26_22-37-18-451_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161338518/4b2d9fc7-3eb6-4a8d-90f2-65cc89233219)

### 还有别的吗？

使用雷神模拟器

**Comment by Lu3422** [comment]
选择打层数，别打扰他们是进第四结局的，难度较大，容易失败

**Comment by Lu3422** [comment]
模拟器是雷电模拟器，打错了

**Comment by Lu3422** [comment]
谢谢

**Comment by ABA2396** [comment]
存钱和不存钱是两组策略，如果肉鸽设置里的策略选的是刷源石锭的话走的是encounter_for_deposit
