### ISSUE TITLE
连战次数自动选择当前剩余理智的最大连战次数

### ISSUE THREAD

**Issue by AlearXS** [MaaAssistantArknights/MaaAssistantArknights#8416]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

连战功能能够极大地减少挂机时间，尤其是挂1-7的时候，但是当前功能只支持手动选择连战次数，不是很方便。

### 有什么好的想法？

maa已经可以识别当前理智剩余量，可以根据这个计算并选择连战次数。这个功能显然也可以兼容自定义作战次数的使用场景。

**Comment by status102** [comment]
次数拉满+剩余理智基本会比每次计算更快
