### ISSUE TITLE
會客室無法辨識伊內絲(繁中服)

### ISSUE THREAD

**Issue by shmily554554** [MaaAssistantArknights/MaaAssistantArknights#8417]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如標題，會尋找很久依然找不到伊內絲，最後索性什麼幹員都不選取

### Version

Core Version: v5.1.0

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14417751/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14417766/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159156029/d7005df3-cead-4123-941c-aec20ff47a3e)

**Comment by ABA2396** [comment]
9867a461068c2c0039e65e55171959a9ec7e0c17 fixed
你这是没更新资源吧
