### ISSUE TITLE
蓝叠开机自启动打开模拟器多开出现问题

### ISSUE THREAD

**Issue by xingyu1272** [MaaAssistantArknights/MaaAssistantArknights#842]
蓝叠模拟器安装时方舟自动装在了多开player1上 但是开机自启动只能打开另一个多开。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883661/asst.log)

**Comment by ABA2396** [comment]
你试试弄个exe文件去打开你装方舟的模拟器，然后把那个的地址填进去

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/173185319-c2b84af7-b500-4f5a-ba7e-632122206784.png)
比如写这样一个文件，把编译出来的exe的路径填进MAA里

**Comment by MistEO** [comment]
> ![image](https://user-images.githubusercontent.com/99072975/173185319-c2b84af7-b500-4f5a-ba7e-632122206784.png) 比如写这样一个文件，把编译出来的exe的路径填进MAA里

玩这么花（

**Comment by ABA2396** [comment]
> > ![image](https://user-images.githubusercontent.com/99072975/173185319-c2b84af7-b500-4f5a-ba7e-632122206784.png) 比如写这样一个文件，把编译出来的exe的路径填进MAA里
> 
> 玩这么花（

因为以前是直接一个exe或者bat打开模拟器+方舟的）

**Comment by xingyu1272** [comment]
嘶 那个不会写exe 桌面上可以整了一个快捷方式 打开是对的 但是一打开原文件所在位置 打开就是另一个多开 然后填在mma里面的快捷方式自动定位到了原文件 所以打开的就是另一个多开

**Comment by ABA2396** [comment]
> 嘶 那个不会写exe 桌面上可以整了一个快捷方式 打开是对的 但是一打开原文件所在位置 打开就是另一个多开 然后填在mma里面的快捷方式自动定位到了原文件 所以打开的就是另一个多开

现在maa还只能填exe，现在要用的话可以把那个快捷方式的路径发一下，我先给你整个）

**Comment by xingyu1272** [comment]
![5PTIZWR5H1ZFS3Q4{_ MUUF](https://user-images.githubusercontent.com/107303890/173185862-59bf63ad-a866-46a2-aeb1-4aaa846c17bb.png)

**Comment by xingyu1272** [comment]
> > 嘶 那个不会写exe 桌面上可以整了一个快捷方式 打开是对的 但是一打开原文件所在位置 打开就是另一个多开 然后填在mma里面的快捷方式自动定位到了原文件 所以打开的就是另一个多开
> 
> 现在maa还只能填exe，现在要用的话可以把那个快捷方式的路径发一下，我先给你整个）

"C:\Users\Lenovo\Desktop\arknights - BlueStacks App Player 1.lnk"

**Comment by ABA2396** [comment]
[Project.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883751/Project.zip)
不知道那个带空格能不能行）先试试

**Comment by xingyu1272** [comment]
> > > 嘶 那个不会写exe 桌面上可以整了一个快捷方式 打开是对的 但是一打开原文件所在位置 打开就是另一个多开 然后填在mma里面的快捷方式自动定位到了原文件 所以打开的就是另一个多开
> > 
> > 
> > 现在maa还只能填exe，现在要用的话可以把那个快捷方式的路径发一下，我先给你整个）
> 
> "C:\Users\Lenovo\Desktop\arknights - BlueStacks App Play

> [Project.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883751/Project.zip) 不知道那个带空格能不能行）先试试
![F5M2WRQ~{K Z@4YSEWGG)PO](https://user-images.githubusercontent.com/107303890/173186035-6faf6b9b-03c4-49a6-8dcd-9b32e20c8626.png)

**Comment by xingyu1272** [comment]
> [Project.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883751/Project.zip) 不知道那个带空格能不能行）先试试

好像不太行

**Comment by ABA2396** [comment]
> > [Project.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883751/Project.zip) 不知道那个带空格能不能行）先试试
> 
> 好像不太行

找不到就下一个）这个百度一下就有了

**Comment by ABA2396** [comment]
> 

试了下，你直接把这段填进去就可以了，不要点那个 `选择`

**Comment by xingyu1272** [comment]
> > 
> 
> 试了下，你直接把这段填进去就可以了，不要点那个 `选择`

嘶 好的 我试试

**Comment by ABA2396** [comment]
> > > 
> > 
> > 
> > 试了下，你直接把这段填进去就可以了，不要点那个 `选择`
> 
> 嘶 好的 我试试

C:\Users\Lenovo\Desktop\arknights - BlueStacks App Play.lnk

**Comment by xingyu1272** [comment]
> C:\Users\Lenovo\Desktop\arknights - BlueStacks App Player 1.lnk

！好了 谢谢
