### ISSUE TITLE
Combat/Fight Task always erroring

### ISSUE THREAD

**Issue by ajk992** [MaaAssistantArknights/MaaAssistantArknights#8424]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

Attempting to run the Combat option always causes the task to fail. No progress is made from the home screen after the task is ran. I've tried running the Combat task on Bluestacks, Mumu and LDPlayer with the same results.

### Version

Resource Version: The Black Forest Wills A Dream
UI Version: v5.1.0
Core Version: v5.1.0

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14428792/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14428793/gui.log)

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161551584/bd6506d9-8333-4ccc-8815-344cf0750664)

### Anthing else?

Emulators I've tried and get this error on:
LDPlayer 9
Bluestacks 10
Mumu Player 12

All at 1920x1080 resolution.

Everything to my knowledge was working fine prior to the Typhon update. The rest of the tasks still seem to work fine.

**Comment by status102** [comment]
Try switching your UI theme to normal one like this

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/dbeaaf94-558c-433e-94f3-d9378205b39a)

and run it again

**Comment by CyberSleeper** [comment]
The issue is coming from YoStarEN which means the UI theme hasn't come out to global yet, so the UI theme is already default. I got the same issue while using Bluestacks 10 at the exact same specification version and 1920x1080 res

**Comment by Ryoj1** [comment]
I have the same issue since the Typhon update , the Recruit and Combat keep getting error

YoStarJP
mumu 12 Player

**Comment by Constrat** [comment]
Already fixed for EN. Update to the latest nightly version.
@Manicsteiner KR has alreayd been fixed. if you have time for the JP, thank you :>

**Comment by Constrat** [comment]
Oh I'm sorry, I didn't notice there was already a commit. 
Well there's already another nightly released for JP
Thank you
