### ISSUE TITLE
mumu模拟器更改分辨率后maa失效

### ISSUE THREAD

**Issue by Fizz0329** [MaaAssistantArknights/MaaAssistantArknights#8425]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

mumu模拟器更改为2560*1440（DPI 360）后，maa功能无法使用，本人使用天选4

### Version

Resource Version: 千秋一粟
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

2024.2.28 一点半之后
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14429409/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14429410/gui.log)

**Comment by status102** [comment]
```
[2024-02-28 13:44:05.326] <1><> 公招识别结果: 
重装干员
医疗干员
先锋干员
费用回复
减速
[2024-02-28 13:44:05.327] <1><> 3 ★ Tags
[2024-02-28 13:44:06.540] <1><> 已刷新标签
[2024-02-28 13:44:10.635] <1><> 当前槽位已刷新1次
[2024-02-28 13:44:11.403] <1><> 公招识别结果: 
近卫干员
医疗干员
治疗
新手
生存
```

MAA仍然处于运行当中，未找到相关内容，描述一下具体行为？

**Comment by Constrat** [comment]
As a purely info comment. The suggested resolution anyway for all clients is 1280x720 and for EN is 1920x1080. IF you are using MAA I don't suggest going any higher than that. As it reduces emulator and MAA performance especially in intensive tasks

**Comment by Fizz0329** [comment]
oh，thanks

**Comment by Fizz0329** [comment]
今天又试了一遍，运行没问题了
