### ISSUE TITLE
更新最新版本，會客室依然無法辨識幹員(繁中服)

### ISSUE THREAD

**Issue by shmily554554** [MaaAssistantArknights/MaaAssistantArknights#8426]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如標題，更新最新版本之後，依然是找不到伊內絲、見行者，最後直接略過不放置幹員

asst日誌文件檔案太大無法上傳

### Version

Resource Version: 猶在影中
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14432127/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159156029/e347630c-8f5a-4ec6-82de-96a0241402e2)

**Comment by ABA2396** [comment]
把cache文件夹删了重新触发下资源更新试试。没asst.log等于一点信息都没用

**Comment by shmily554554** [comment]
> Referen

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14446025/asst.log)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/1d131057-680a-461f-9434-14e4c128dc0b)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/1a66987e-ce08-4198-9e30-16fa86dd55ac)
tasks里是有做替换的，要是你的资源版本对了这里就直接替换掉了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/14aa104f-4bcc-4d3c-bead-6f954082748c)

**Comment by shmily554554** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/309125257-1d131057-680a-461f-9434-14e4c128dc0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTYwOTQsIm5iZiI6MTcwOTI5NTc5NCwicGF0aCI6Ii85OTA3Mjk3NS8zMDkxMjUyNTctMWQxMzEwNTctNjgwYS00NjFmLTk0MzQtMTRlNGMxMjhkYzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEyMjMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNGQ5Nzk0ZGU0ZDgxZWY2NzVmZmIwYWU5MjMyM2RiZmMxMWQxMDlkMjRiMjA0MmI4YTg2OGQ4YWIzY2RhZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F8xgTsvB3cNz2fewHiaos8vTC8L0gSxvP56IY7Ha7LE) ![image](https://private-user-images.githubusercontent.com/99072975/309125348-1a66987e-ce08-4198-9e30-16fa86dd55ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTYwOTQsIm5iZiI6MTcwOTI5NTc5NCwicGF0aCI6Ii85OTA3Mjk3NS8zMDkxMjUzNDgtMWE2Njk4N2UtY2UwOC00MTk4LTllMzAtMTZmYTg2ZGQ1NWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEyMjMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkN2RhODViYTQ4ODc0NzY1NzQ0NTdjYzgwNGMzOTk4MzUzZDNiNDNlMmQ3NGU0ZjUzMzg1MGFhYmM5YWQ3OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.58v9VaY6eXl7RDXcqGfQfxBt3K_FcQJO_2dXjgFEViY) tasks里是有做替换的，要是你的资源版本对了这里就直接替换掉了 ![image](https://private-user-images.githubusercontent.com/99072975/309125506-14aa104f-4bcc-4d3c-bead-6f954082748c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTYwOTQsIm5iZiI6MTcwOTI5NTc5NCwicGF0aCI6Ii85OTA3Mjk3NS8zMDkxMjU1MDYtMTRhYTEwNGYtNGJjYy00ZDNjLWJlYWQtNmY5NTQwODI3NDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEyMjMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4M2UwZDY0MWY4NGUzZjY1MWNiNzRlZTEwYmJiZGMwZDlmNTAzZDRlNWM3YmRiY2FiYjJhYjM2OGY4YjRhMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vl07qJxucyfO0C7O2deFR4HJPARzQXbaHkCKQu8uvkI)

已經全部刪除重新下載MAA，依然找不到幹員...

**Comment by ABA2396** [comment]
感觉不应该啊，外服的tasks应该是直接跟着资源更新走的
那你试试在设置-软件更新-更新版本 里选内测版，更新完再跑一遍试试

**Comment by shmily554554** [comment]
> 感觉不应该啊，外服的tasks应该是直接跟着资源更新走的 那你试试在设置-软件更新-更新版本 里选内测版，更新完再跑一遍试试

內測版真的可以，感謝
請問使用內測板會有什麼問題嗎?

**Comment by ABA2396** [comment]
照理来说资源更新是所有版本一致的，但是内测版的更新包会自带新版本的资源，正式版和公测版需要额外下载

内测版是开发分支，如果引入新功能或修改原有功能有可能会引入新的bug，测试基本稳定后发公测版，公测版测试稳定后就是正式版

**Comment by shmily554554** [comment]
> 照理来说资源更新是所有版本一致的，但是内测版的更新包会自带新版本的资源，正式版和公测版需要额外下载
> 
> 内测版是开发分支，如果引入新功能或修改原有功能有可能会引入新的bug，测试基本稳定后发公测版，公测版测试稳定后就是正式版

知道了 謝謝
