### ISSUE TITLE
游戏资源更新完成后也弹出一键重启的提示

### ISSUE THREAD

**Issue by TobyLi223** [MaaAssistantArknights/MaaAssistantArknights#8429]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by status102** [comment]
勾选自动安装会自动重启
