### ISSUE TITLE
ios mac playcover  国际服（美服）无法从主界面进入刷理智任务

### ISSUE THREAD

**Issue by Argonautes0607** [MaaAssistantArknights/MaaAssistantArknights#8431]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，从终端进入开始理智任务没问题，个人猜测是Terminal的“l“被活动横幅挡住了

### Version

Mac好像没法复制，MAA V5.1.0 (466)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14441414/asst.log)

### 截图

![屏幕快照 2024-02-29 的 08 45 57 上午](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106745133/dac34104-c217-4072-a3ac-9b5aeb4a59d2)

**Comment by Manicsteiner** [comment]
两天前的安装包更新中微调了主界面UI，导致识别失效。
Mac端好像没有内测版，我也不太清楚怎么整，或许可以暂时用[ci build](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/8075512044)的版本

**Comment by butterfly815** [comment]
日服也是相同狀況刷不了理智 主頁也進不了公招頁面  並且在startup進入主頁面後一樣會卡在startup不會開始recruit
目前只有基建跟領信用能正常運行

**Comment by ABA2396** [comment]
> 日服也是相同狀況刷不了理智 主頁也進不了公招頁面  並且在startup進入主頁面後一樣會卡在startup不會開始recruit
> 目前只有基建跟領信用能正常運行
> 

Windows可以先用内测版，mac的话可能得自己先替换下图片？不太清楚mac是怎么样的

**Comment by liuyifan-eric** [comment]
> 日服也是相同狀況刷不了理智 主頁也進不了公招頁面  並且在startup進入主頁面後一樣會卡在startup不會開始recruit
> 
> 目前只有基建跟領信用能正常運行
> 
> 

我也遇到了这个问题，研究了一下应该是yostar微调了字体，尤其是公開求人的公看得比较明显
需要更新一下template

**Comment by Argonautes0607** [comment]
观察了下确实是其他地方都有点改变，应该是为界面主题更换做准备
