### ISSUE TITLE
增加定时执行功能自动启动模拟器的功能

### ISSUE THREAD

**Issue by RacherStormer** [MaaAssistantArknights/MaaAssistantArknights#8432]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

定时执行功能必须要挂着模拟器才能自动执行，但是一直挂着模拟器占用电脑资源

### 有什么好的想法？

希望能够增加一个勾选框，让maa能够在定时执行的基础上自动开启模拟器

**Comment by ABA2396** [comment]
设置里都有
