### ISSUE TITLE
国际服 更新后，勾选 自动基建-源石碎片自动补货 会在制造界面长时间无操作

### ISSUE THREAD

**Issue by luvleizi** [MaaAssistantArknights/MaaAssistantArknights#8439]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

稳定、公测、内测均有该现象。更新前勾选该项就没有办法实现补货至99，但不会影响正常运行。更新后若勾选择会导致在Mfg0源石制造间长时间无操作，数分钟后没有补货就继续进入下一房间，进入Mfg3 源石制造间后再一次长时间无操作。不勾选则依然正常。gui.log最后一段可以看到Mfg0后，Mfg3后 均有长达六分半的无操作时间。在此期间主动点左上角返回主界面仍无操作，但若在Mfg0后主动返回主界面，等到Maa再次运行，进入基建后，则会跳过后面的制造站，直接进入贸易站。（见[2024-03-01 13:46:09.272] <1><> 当前设施: Trade 0）

### Version

UI Version: v5.1.1-alpha.1.d119.g9b2da02bd

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14456854/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14456999/gui.log)

### 截图

debug下五个文件夹中没有找到相关截图

### 还有别的吗？

雷电模拟器 win10

**Comment by Constrat** [comment]
Let me know if this helps / changes anything.
I suggest you copying the images from https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/690c99c4e3c21c80ff382525d86ece9ec293b8ad and overwriting them in `MAA\resource\global\YoStarEN\resource\template`

**Comment by Constrat** [comment]
Duplicate of #5367
