### ISSUE TITLE
希望能自定义基建排班表

### ISSUE THREAD

**Issue by zoe4477** [MaaAssistantArknights/MaaAssistantArknights#844]
迷迭香宇宙太强了，想用一键换班但又觉得损失了很多收益。
希望能有自定义基建排班表的功能，每天在指定时间自动按照排班表换班。
不知道这个功能难不难实现，要是能有就太好了。

**Comment by Shawnsdaddy** [comment]
@MistEO 我也觉得可以先实现个用户自定义排班，然后再实现全自动

**Comment by MistEO** [comment]
准备做跨设施计算了，不会做自定义了
