### ISSUE TITLE
水月肉鸽通关卡在肉鸽总结界面

### ISSUE THREAD

**Issue by Simongxm** [MaaAssistantArknights/MaaAssistantArknights#8440]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

水月肉鸽通关之后会卡在肉鸽结局总结界面，无法正常通过识别‘skip’或‘continue'继续。

### Version

Resource Version: 千秋一粟UI Version: v5.1.0Core Version: v5.1.0

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14458156/gui.log)

**Comment by status102** [comment]
缺少asst.log

**Comment by Simongxm** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14468688/asst.log)

**Comment by status102** [comment]
asst.log不包含问题发生的时间段`2024-02-29 23:53:47.422`，建议检查asst.log.bak是否包含
