### ISSUE TITLE
关于公开招募的需求功能

### ISSUE THREAD

**Issue by YueHen14** [MaaAssistantArknights/MaaAssistantArknights#8441]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

希望可以做一个自定义词条选择，有些罕见的词条选择我发现maa并不会选择。希望可以采纳

**Comment by Toby-Shi-cloud** [comment]
你可能需要这个： #8868 
已经在稳定版中发布：[v5.2.3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v5.2.3)
