### ISSUE TITLE
关于MAA完成所有任务后的休眠

### ISSUE THREAD

**Issue by livzsoo** [MaaAssistantArknights/MaaAssistantArknights#8449]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在的休眠没有提醒，完成任务后就瞬间黑屏进入休眠状态

### 有什么好的想法？

能不能改成像“关机”那样延迟1分钟再进入休眠？

**Comment by ABA2396** [comment]
Windows 休眠命令是没有延迟参数的
