### ISSUE TITLE
新活动自动清理智故障

### ISSUE THREAD

**Issue by helloIris415** [MaaAssistantArknights/MaaAssistantArknights#845]
![image](https://user-images.githubusercontent.com/63986965/173185942-db085e2a-ff84-42e4-a8ae-2fb7e293f858.png)
关卡选择为LE-6的情况下，能正常进入关卡，但是进入关卡后会被识别为任务出错，然后自动开始其余功能。
【不清楚是LE都有还是只有LE-6会出问题，我只刷了6】
log文件出现问题的时间点在10：40和19：25左右。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883753/asst.log)

**Comment by helloIris415** [comment]
确定为关卡识别问题，使用上次作战选项也会卡识别
![image](https://user-images.githubusercontent.com/63986965/173186409-ee8ed32a-5571-493e-9acc-10a02a8f4313.png)

**Comment by ABA2396** [comment]
这个大概是资源没更新上，重新下载一下安装包替换一下文件就好了

**Comment by helloIris415** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883771/asst.log)

**Comment by helloIris415** [comment]
> 这个大概是资源没更新上，重新下载一下安装包替换一下文件就好了

然而这个版本我就是替换文件的。甚至我刚才重新覆盖了一遍还是一样的问题

**Comment by ABA2396** [comment]
> > 这个大概是资源没更新上，重新下载一下安装包替换一下文件就好了
> 
> 然而这个版本我就是替换文件的。甚至我刚才重新覆盖了一遍还是一样的问题

那把gui.json拎出来，放进新下的里面试试
