### ISSUE TITLE
Maa combat can't be start

### ISSUE THREAD

**Issue by EfJun1** [MaaAssistantArknights/MaaAssistantArknights#8451]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

![MAA_v5_hzfNIVozpm](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/130586677/24d5d5d5-2270-4a32-b2d0-0bf93ec7104b)
Tried to use Maa combat to farm stages but was getting this error, tried to download two fresh new files from the download section and still receiving this issue.

### Version

Resource Version: The Black Forest Wills A Dream
UI Version: v5.1.0
Core Version: v5.1.0

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14468051/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14468052/gui.log)

### Screenshots

![MAA_v5_hzfNIVozpm](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/130586677/2d583fc3-637c-4924-bdd3-32a289a8c31e)

### Anthing else?

I am using bluestacks 5 version 5.21.0.1043 P64, windows 10 pro. Didn't change any configuration.

**Comment by NyanSequitur** [comment]
Update to nightly, fix has not yet made it to stable.
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/437ae363aed8a2abb451bc7baf6c581b4671e3a6

**Comment by EfJun1** [comment]
> Update to nightly, fix has not yet made it to stable. [437ae36](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/437ae363aed8a2abb451bc7baf6c581b4671e3a6)

Thank you very much, will do.

**Comment by Constrat** [comment]
>  I have checked the latest beta update and there is no mention of the bug being fixed.
