### ISSUE TITLE
萨米肉鸽鲍勃杂货店卡死步骤问题

### ISSUE THREAD

**Issue by Yuxag** [MaaAssistantArknights/MaaAssistantArknights#8454]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在萨米肉鸽的时候maa会自动选择一些消耗抗干扰指数的步骤，但是在鲍勃杂货店他会因为抗干扰指数用光而导致选择不了下面的两个选项，最上面的那个选项他又不会去选择，就会出现卡死在这个界面的情况（其他类似的事件也可能导致此结果），

### Version

Core Version: v5.1.1-alpha.1.d119.g9b2da02bd
内测版

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14468737/gui.log)
[2024-03-02 16:08:30.447] <1><> 事件: 鲍勃杂货店

### 截图

![95EUI`2_CJO%UM3QLN`S6CI](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161931740/7232614d-ece8-4593-be8b-c3845cd6aae3)

### 还有别的吗？

mumu12

**Comment by chenyinggu** [comment]
把encounter_for_deposit中对应的事件改成
        {
            "name": "鲍勃杂货店",
            "option_num": 3,
            "choose": 1,
            "choice_require": [
                {
                    "name": "选择他手中的货品",
                    "Vision": {
                        "value": "1",
                        "type": "<"
                    }
                },
                {
                    "name": "选择他脚边的货品",
                    "Vision": {
                        "value": "1",
                        "type": ">"
                    }
                },
                {
                    "name": "选择仓库深处的货品",
                    "Vision": {
                        "value": "3",
                        "type": ">"
                    }
                }
            ]
            尝试修改成这样，没测试，感觉可以。

**Comment by chenyinggu** [comment]
我也有这样的问题：也是mumu12

**Comment by A112F** [comment]
遇到很多次了
