### ISSUE TITLE
标准10-3掉落物显示错误

### ISSUE THREAD

**Issue by 04linshi** [MaaAssistantArknights/MaaAssistantArknights#846]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883815/asst.log)

Thanks♪(･ω･)ﾉ
![G5UH67E25VHF%X$CS_O% ~L](https://user-images.githubusercontent.com/106676717/173187263-aa41b308-a773-4752-af47-9005a2e89daf.png)

**Comment by 04linshi** [comment]
![Screenshot_20220611-202341](https://user-images.githubusercontent.com/106676717/173187823-a93b86d0-f245-4867-b541-fed54889e026.png)
![LA D3BW(K7G}`HHU2QKMUGY](https://user-images.githubusercontent.com/106676717/173187829-e2acc971-6336-41ff-9362-92820447924a.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883868/asst.log)

**Comment by 04linshi** [comment]
![Screenshot_20220611-203111](https://user-images.githubusercontent.com/106676717/173188051-743f1eb2-4e18-4df1-a7ce-44b1e6b3e69f.png)
[Uploading asst.log…]()
![W 9U@@ 5A`N1 OPW8`5S6LS](https://user-images.githubusercontent.com/106676717/173188056-b939b52c-6c7b-48d8-abf9-bab0341578ce.png)

**Comment by 04linshi** [comment]
![Screenshot_20220611-203306](https://user-images.githubusercontent.com/106676717/173188101-53d6fa51-4bd6-4481-8b8f-eb8179cd5e50.png)
![~N }5F5FX3}O%D9%K5J0DOO](https://user-images.githubusercontent.com/106676717/173188103-c501294a-392a-4d9c-969b-914a2a10d7ca.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883876/asst.log)

**Comment by ABA2396** [comment]
@MistEO 怎么又把凝胶当成异铁碎片了

**Comment by MistEO** [comment]
> @MistEO 怎么又把凝胶当成异铁碎片了

没有识别错，是识别漏了一个
