### ISSUE TITLE
自动战斗增加投降、助战功能

### ISSUE THREAD

**Issue by Xtzdd** [MaaAssistantArknights/MaaAssistantArknights#8463]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

1，引航者试炼自动战斗刷分，后续关卡编写麻烦且实测不稳定，因此计划只打第一关。
希望能出个自动投降功能，从而加快每局的循环。
2，对于绝大多数低配作业来说，难免用到一个需要借的高练助战；对于引航者试炼，部分作业常会用到一个相对冷门的角色。也即助战在自动战斗中的使用率较高，而目前自动战斗尚无法很好适配助战功能。

### 有什么好的想法？

对于1，希望MAA Copilot编写指令中增加一个投降指令，允许增加前置条件，例如切换相机视角时，战斗时间超出时（类似于watchdog）。
类似模块或已在生息演算和肉鸽中存在，只是未应用至自动战斗中。
对于2，希望在自动编队以外，出一个独立的借助战功能。因在反复刷关时自备角色无需反复调整，但助战需要每次配置，无法自动配置助战会影响自动循环。
可以提供一个输入框和一个备选框，前者输入需借助战的角色名，后者选择技能。操作上应当可以自动划动刷新助战列表，直至找到并点选匹配的目标角色。

**Comment by Saratoga-Official** [comment]
目前来说你这两条都挺难
第一条要修改战斗协议，加投降动作，目前好像没人愿意写，我之前提的修改部署用法过了几个月都没信
第二条之所以MAA为啥迟迟没实装借助战功能，因为要识别技能，技能图标就一大堆，所以这也挺难的，肉鸽不用识别技能，所以肉鸽早就有借助战了

**Comment by status102** [comment]
Duplicate of #6023
