### ISSUE TITLE
部分功能无法实现

### ISSUE THREAD

**Issue by haibaoAzarashi** [MaaAssistantArknights/MaaAssistantArknights#8466]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

日服更新提丰故事集后部分功能无法实现，持续数日了

### Version

Resource Version: 樹影にて眠る
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14471859/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14471860/gui.log)

### 截图

![无标题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108400596/5ebfc5d5-b9de-49d1-807c-0c842c2017f6)

**Comment by Constrat** [comment]
asst.log you sent it useless. Check asst.bak.log

**Comment by Constrat** [comment]
Also, regarding the Typhon event. There is no need for farming stages as it's a "mini-event". For this reason you don't see FD-6 -7 -8 in the stages.

**Comment by haibaoAzarashi** [comment]
> asst.log you sent it useless. Check asst.bak.log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14478819/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14478821/asst.bak.log)

**Comment by Constrat** [comment]
Only now I understood the issue. Just update to the latest nightly.
