### ISSUE TITLE
从上个版本更新后无法肉鸽

### ISSUE THREAD

**Issue by Ga1en70** [MaaAssistantArknights/MaaAssistantArknights#847]
![image](https://user-images.githubusercontent.com/98802522/173188832-197eecd4-8a4f-4c3f-9424-ac463ad28c70.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8883905/asst.log)

**Comment by Ga1en70** [comment]
![image](https://user-images.githubusercontent.com/98802522/173188855-e435aac1-d551-4f26-8e04-37b465713fcc.png)
会一直卡在这个界面

**Comment by Ga1en70** [comment]
就算我手动点进肉鸽界面再开始也不行，是否和ui更新之后这个页面没有肉鸽的进入选项有关系呢

**Comment by ABA2396** [comment]
> 就算我手动点进肉鸽界面再开始也不行，是否和ui更新之后这个页面没有肉鸽的进入选项有关系呢

确实 之前肉鸽就是点这个页面的肉鸽进去的
