### ISSUE TITLE
日服 水月肉鸽关卡译名重复

### ISSUE THREAD

**Issue by Manicsteiner** [MaaAssistantArknights/MaaAssistantArknights#8471]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

日服将关卡 [犹豫不决](https://prts.wiki/w/ISW-DU_%E7%8A%B9%E8%B1%AB%E4%B8%8D%E5%86%B3) 和 [瞻前顾后](https://prts.wiki/w/ISW-NO_%E7%9E%BB%E5%89%8D%E9%A1%BE%E5%90%8E) 均译作 優柔不断 ，因此无法正确分辨这两个关卡。

犹豫不决
Obt/Roguelike/RO2/level_rogue2_t-1

瞻前顾后
Obt/Roguelike/RO2/level_rogue2_3-8

![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/88e7a2f4-805b-4a0a-b4a8-1066c82c58ef)
目前按照json中的顺序会全部替换为犹豫不决。

### Version

latest debug build，并且在测试一些额外修改

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14475783/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14475784/gui.log)

### 还有别的吗？

理论上遇到瞻前顾后的概率高一些，或许可以调整json中的顺序先提高它的替换优先级

**Comment by Argonautes0607** [comment]
悠星小杯翻译

**Comment by Manicsteiner** [comment]
> 悠星小杯翻译，EN/JP服的Mac版几时可以刷理智啊

请暂时使用 [ci build](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/workflows/ci.yml) 版本
