### ISSUE TITLE
EN/JP服启动失败

### ISSUE THREAD

**Issue by EvATive7** [MaaAssistantArknights/MaaAssistantArknights#8472]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

Startup已经成功进入主界面，但是长时间未结束，然后报TaskChainError。
该情况与 #8470 中提及的情况交替发生。

### Version

Resource Version:The Black Forest Wills A Dream
UI Version:5.1.0
Core Version:5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14476071/asst.log)
(集成调用不含gui.log)

**Comment by Manicsteiner** [comment]
请切换至内测版更新渠道，或手动更新至v5.1.1-alpha.1.d118.g999f9087b及以后的版本
