### ISSUE TITLE
仓库识别只剩两页？

### ISSUE THREAD

**Issue by insine-inverse** [MaaAssistantArknights/MaaAssistantArknights#8474]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

突发的问题好像是，复制发现主要的材料都没有了，不知道发生了什么？

### Version

Resource Version: 千秋一粟
UI Version: v5.1.1-alpha.1.d144.g9aa361cb6
Core Version: v5.1.1-alpha.1.d144.g9aa361cb6

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14477341/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14477342/gui.log)

### 截图

![I9 }9Q0TEGGS2ZS}Z5RN$N6](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87361258/3e46d15c-718e-4ef1-901a-e692f5711df7)
![2024-03-04_14-20-31-874_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87361258/39e45026-95f4-49a0-a410-67176f2fa2cb)
![2024-03-04_14-20-32-292_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87361258/11d9da47-e767-4335-aca5-0bdefc744e36)

**Comment by Sduck-Inverse** [comment]
奇怪……过了一天就好了，是修复了吗？

**Comment by Sduck-Inverse** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87361258/5a61861d-bdf3-4d44-80de-754c298fdf04)
又来了，芯片识别不全
![2024-03-06_12-13-36-614_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87361258/6e25e051-ea19-442a-997d-45067fcd80b7)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14504551/asst.log)

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14504552/gui.log)

**Comment by FreeSky-X** [comment]
没修，不稳定 （
