### ISSUE TITLE
如何判断本地maa是否已经热更成功？

### ISSUE THREAD

**Issue by WindStill** [MaaAssistantArknights/MaaAssistantArknights#8477]
### 说说你遇到的问题？

如何判断服务器是否存在热更数据，已经本地是否已经成功更新了热更数据？（Mac 版maa）

**Comment by status102** [comment]
Mac没有热更机制

**Comment by WindStill** [comment]
> Mac没有热更机制

这样吗？那应该如何获取热更数据，如果没有发布新版本的话？

**Comment by status102** [comment]
> > Mac没有热更
> 
> 这样吗？那应该如何获取热更数据，如果没有发布新版本的话？

cc @hguandl

**Comment by status102** [comment]
> > Mac没有热更机制
> 
> 这样吗？那应该如何获取热更数据，如果没有发布新版本的话？

那只能自己看一下WpfGui的对着下了

**Comment by WindStill** [comment]
> 好像是通过 Etag 判断 https://ota.maa.plus/MaaAssistantArknights/api/resource 里面的内容是否有变化

请问是否可以手动下载并替换软件包里的文件？我记得之前的版本我试过修改，但是未成功。新版本是否支持，或者说还是修改其他的文件？

**Comment by WindStill** [comment]
下载了 Arknights-Tile-Pos 目录下的overview.json 和 新关卡的json文件，可以解决了新关卡的识别问题。

希望新版本能引入自动热更机制，或者手动一建更新。辛苦各位！
