### ISSUE TITLE
maa不能进行热更地图（新剿灭）

### ISSUE THREAD

**Issue by Naumanyiran** [MaaAssistantArknights/MaaAssistantArknights#8478]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

目前是三月四号下午五点十九分，部分群友已经可以正常使用作业打剿灭，但是我在尝试了几个小时后仍然发现没有办法更新最新版本，使用作业时显示不支持的地图。资源版本无法更新

### Version

Resource Version: 千秋一粟
UI Version: v5.1.1-alpha.1.d144.g9aa361cb6
Core Version: v5.1.1-alpha.1.d144.g9aa361cb6

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14479238/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14479240/gui.log)

### 截图

![QQ图片20240304171757](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/162110003/90d4e8c4-f87e-4f2e-9a0c-90727f7270f0)

**Comment by ABA2396** [comment]
点设置里的检查更新没用吗？如果还是不行把cache文件夹删了重新检查一遍试试

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/b804a52d-2990-416a-b3b5-4334a7bf5354)
镜像服务器文件未同步

**Comment by Naumanyiran** [comment]
> 点设置里的检查更新没用吗？如果还是不行把cache文件夹删了重新检查一遍试试

删除cache正常更新了，谢谢佬
