### ISSUE TITLE
基建排班有明显算法问题

### ISSUE THREAD

**Issue by 1arkn** [MaaAssistantArknights/MaaAssistantArknights#848]
在我中枢放了个焰尾，效果是基建里红松骑士团干员生产作战记录加10，生产赤金减10，结果放了一堆红松骑士团去生产赤金，放了迷迭香又不放絮语之类的干员。我想了半天没想出来为什么三个干员生产力只有百分之28。希望能对这些基建体系进行优化

**Comment by ABA2396** [comment]
现在的基建是计算的单设施最高效率，所以选人也不会去选那种跨设施的技能，你这是自己选了跨设施还有负面效果的技能吧。已经有大佬在写全局基建了，但现在用的还是单设施计算效率

**Comment by zzyyyl** [comment]
自定义基建！
