### ISSUE TITLE
仓库扫描无法结束

### ISSUE THREAD

**Issue by uzhao** [MaaAssistantArknights/MaaAssistantArknights#8480]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

扫描到最后一部分的时候不停向右拉,没有三次后中断

### Version

UI Version: v5.1.1-alpha.1.d156.gd393a227e

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14489703/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14489706/gui.log)
最后一部分

### 还有别的吗？

蓝叠5, win10

**Comment by FreeSky-X** [comment]
识别的物品齐全吗

**Comment by uzhao** [comment]
> 识别的物品齐全吗

识别未结束的时候看不到全部内容.刚刚又试了一下又可以结束了,可能是个偶发的bug
