### ISSUE TITLE
EN wrong recognition in credit store for "Battle Record"

### ISSUE THREAD

**Issue by luvleizi** [MaaAssistantArknights/MaaAssistantArknights#8482]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

in ass.log, [2024-03-05 09:12:01.933] , "Record" was recognized as "Recorc" , at the same time [2024-03-05 09:12:02.221] the "Record" was recognized correctly. But [2024-03-05 12:51:51.593] the same "Drill Battle Record" was recognized as "Recoro". 

### Version

UI Version: v5.1.1-alpha.1.d156.gd393a227e

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14491154/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14491155/gui.log)

### Anthing else?

LDplayer win10

**Comment by Constrat** [comment]
I never noticed. 
@ABA2396 the credit store does not use the tasks.json regex. Any suggestions?

**Comment by ABA2396** [comment]
Just writing `Recor` works from a usage standpoint alone, but this should be changed

**Comment by Constrat** [comment]
I'm trying to understand the CreditShopImageAnalyzer item vector. There are 2 fries for priority, and one try for black list
[2024-03-05 07:12:23.935][INF][Px1c88][Tx0588] asst::CreditShopImageAnalyzer::whether_to_buy_analyze [Recruitment Permit] mode 1


[2024-03-05 07:12:25.525][INF][Px1c88][Tx0588] asst::CreditShopImageAnalyzer::whether_to_buy_analyze [Recruitment Permit] mode 1

[2024-03-05 07:12:27.480][INF][Px1c88][Tx0588] asst::CreditShopImageAnalyzer::set_black_list [Carbon, Furniture Part, Expedited Plan, Courier, Gavial, Dur-nar]

**Comment by Constrat** [comment]
> Add "ocrReplace" to "CreditShop-ProductName" and you're done

As soon as I get back on machine. Thank you for the help

**Comment by Constrat** [comment]
@luvleizi you noticed this issue because you whitelisted the items and they were not getting recognized?
I'm having some troubles understanding the logic of the priorities. In my case, there are also recognition issues, but MAA still buys what is whitelisted, regardless of the asst.log issue.
So fi you are telling me that even though you whitelisted "Battle Records" and MAA was not buying them I'll add some replacing, otherwise I feel like leaving this alone would be best. If it's working, let's leave it at that, regardless of the logs.
If it's not working, I'll add the regex for the battle records.

**Comment by luvleizi** [comment]
@Constrat  record was on my black list,  MAA did buy it. the store doesn't have record today, so i don't know whether it's useful to write "recor" instead.

**Comment by Constrat** [comment]
Have you checked 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/81796066-71e3-4abd-9f2f-25a4f22309f2)
Ignore credits overflow?

**Comment by luvleizi** [comment]
no i have never ticked it
![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/107036550/83a774fe-7c06-498e-8753-a79fc1815bfb)

**Comment by Constrat** [comment]
Well then, let's try with just `Recor`. Let me know if anything changes in the next few days hopefully the shop will rotate correctly.

**Comment by luvleizi** [comment]
yes，though the recognition does not get wrong, it works just write `Recor` or `Battle`

**Comment by Constrat** [comment]
Seems like whitelist and blacklist doesn't follow any ocrReplace unfortunately. It just follows user input. In case of errors, the user has to change the input. 
This makes sense as we would need two layers: understanding the user input and then understanding the emulator image.
