### ISSUE TITLE
为日服/美服进行萨米肉鸽适配

### ISSUE THREAD

**Issue by THSLP13** [MaaAssistantArknights/MaaAssistantArknights#8489]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

日服萨米肉鸽已于3月5日开放，美服则在3月6日凌晨开放。
是时候为它们进行适配了。

### 有什么好的想法？

I can help(Not really so QAQ)

### 其他内容

日服和美服因为表达方式问题，存在非常严重的排版与国服不一致的问题。
例如乐理之灾的节点选取页面就出现了文字不在一般位置的情况，在战利品为密文板子的小字描述也相当的小(手机上已经几近看不清了!)
![7E4E0DDDDA667161DDAF3B28D3C99039](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62548119/cd2787d0-1178-4732-b2ec-6fb5eb14ba01)
![1FC4415934DE7E519824AFA07658562A](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62548119/e13f8d5b-5c7a-4433-b2b9-04bb63c6c712)

**Comment by Manicsteiner** [comment]
根据BattleStageName的roi信息，程序应该是在进入战斗后、正式开始战斗前的显示ISW-NO的界面识别的，提供图片的界面不影响
密文版小字不用识别
日服已经基本适配，大概下一个内测版就会有，现在急用可以用我的[FakeOTA](https://github.com/Manicsteiner/MaaAssistantArknights/releases/tag/v5.2.0-beta.1-JPupdate)手动替换本地文件使用。美服大概要晚上或明后天。

**Comment by Constrat** [comment]
Guys, we are humans. I know the IS has been released, but it's not a simple implementation. Be patient.
