### ISSUE TITLE
Auto IS on IS4 not working

### ISSUE THREAD

**Issue by MasamuneDate99** [MaaAssistantArknights/MaaAssistantArknights#8494]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

Expected Behavior :
- Start the run normally

Result Behavior : 
- Exiting IS page
- Returning to main menu
- Stuck at main menu

I do already try it again for IS3, and it's work without any problem. If i start expedition manually, MAA will simply just abbandon current exploration, wait for the timer run out, and go straight to home page.

### Version

Resource Version: Dorothy's Vision - Retrospection
UI Version: v5.1.0
Core Version: v5.1.0

### Log files

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14508725/debug.zip)

### Screenshots

// Starting from IS4 Page
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/24244933/c83d31d5-a895-438e-b68f-6bb710682252)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/24244933/f2eabb07-74b3-4845-bdeb-583e147fdd4c)

// Starting from Home page
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/24244933/cf473f7a-bb3c-47d1-9b76-edb50a35eae0)

### Anthing else?

Used emulator : Mumu Player 6
OS : WIndows

**Comment by Constrat** [comment]
1. You are on the 5.1.0 main version (no updates)
2. no changelogs have been released saying this was implemented
3. it's not even a day after the IS has been released. IS adaptation is complicated and requires a lot of time. Have patience.
