### ISSUE TITLE
萨米肉鸽存源石锭出错

### ISSUE THREAD

**Issue by xingkong122** [MaaAssistantArknights/MaaAssistantArknights#8496]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽存源石锭时总是识别错误，商店识别多一位数

### Version

Resource Version: 引航者试炼
UI Version: v5.2.0-beta.1
Core Version: v5.2.0-beta.1

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14511040/gui.log)

### 截图

![Uploading 微信图片_20240306221855.png…]()

**Comment by Constrat** [comment]
Before sending / confirming edit. Make sure the file has finished uploading.

**Comment by xingkong122** [comment]
![微信图片_20240306221855](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/162462980/d9aac1b1-4edf-4216-ac03-80fa736afc0f)

**Comment by xingkong122** [comment]
> Before sending / confirming edit. Make sure the file has finished uploading.

如何修改

**Comment by Constrat** [comment]
No asst.log
No help

**Comment by xingkong122** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14511306/asst.log)

**Comment by status102** [comment]
日志中的最早信息为 2024-03-06 21:20:51.265，检查一下asst.bak.log中是否包含相关信息

日志存在滚动机制，>4mb会滚动防止文件过大

**Comment by xingkong122** [comment]
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14525508/asst.bak.log)

**Comment by Lancarus** [comment]
用正则匹配一下只保留右边最多三位数字？

**Comment by xingkong122** [comment]
> 用正则匹配一下只保留右边最多三位数字？

什么意思不太懂

**Comment by Lancarus** [comment]
> 什么意思不太懂

跟开发说的（）

**Comment by status102** [comment]
小修下试试，下版本复现后再重新提个

**Comment by status102** [comment]
记得记得log传全，没log查不了问题

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/848f2f41-37df-4ec4-8299-fa0690612882)

**Comment by xingkong122** [comment]
不好意思，第一次用不太熟练

**Comment by status102** [comment]
没事没事，主要是没log不知道MAA干了啥，没法修
