### ISSUE TITLE
Issue with the Terra Research Commission regex recognition for YoStarEN

### ISSUE THREAD

**Issue by swablueme** [MaaAssistantArknights/MaaAssistantArknights#8498]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

WordOCR has issues with detecting Terra Research Commission (泰拉大陆调查团) regex in YoStarEN (Arknights Global) in base.

The current regex pattern is not detecting the operator
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/10569495/cd1b1210-90ac-4187-a7c0-a87d820f0f81)

Currently I am using `.*ommissi?o.*` to detect this operator. 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/10569495/889dafda-2467-4393-89a5-c0211c49fbab)

### Version

 v5.2.0-beta.1 (has been happening ever since Terra Research Commission has been released)

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14516798/asst.log)

### Screenshots

Examples of failing logs:
1)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/10569495/1f5d6b4d-8036-41d0-b928-7388ad321f7e)
2)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/10569495/c8761adf-65df-4f68-a920-298ca3aff0a9)
3)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/10569495/2b4808c0-4b6c-4254-80c8-c7f8e164520e)

### Anthing else?

Ldplayer 9

**Comment by Constrat** [comment]
Considering it has been happening since release.
1. Is this 1920x1080
2. Recognition in infrastructure, or through the Operator list recognition?

**Comment by swablueme** [comment]
@Constrat Higher internal res (1920x1080) fixes it. I think I might as well stick with higher internal res as operator list also has troubles with detection

**Comment by Constrat** [comment]
You NEED to use 1920x1080 for YostarEN, it's in the FAQ as well. There are too many discrepancies between the various resolutions
