### ISSUE TITLE
设置-自动公招-自动使用加急许可选项状态无法保存

### ISSUE THREAD

**Issue by SunshineboyZj** [MaaAssistantArknights/MaaAssistantArknights#850]
https://user-images.githubusercontent.com/81549837/173205295-5dc730cb-6759-4f98-85b5-ee08b1dadb44.mp4
系统环境：Windows10 21H2
软件存放于D盘（非系统盘下），无论是否以管理员身份启动，都是如此（此选项无论如何都无法保存）

**Comment by SunshineboyZj** [comment]
上传了个几秒钟的视频。
![image](https://user-images.githubusercontent.com/81549837/173205420-da7ba41e-f7ca-4e24-8fd4-c45aaf0749f8.png)

**Comment by SunshineboyZj** [comment]
v3.9.5.2MaaAssistantArknights

**Comment by MistEO** [comment]
by design
