### ISSUE TITLE
自动编队+补充低信赖干员，当作业中包含干员组，且其中包含低信赖干员时，可能引起异常。

### ISSUE THREAD

**Issue by EuropeanWithSSR** [MaaAssistantArknights/MaaAssistantArknights#8504]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39738950/c704f086-8766-4d32-996f-e7daa26d3a13)
如图，作业中包含干员组，其中中有塞雷娅和黍两位干员。
【自动编队】            选择  塞雷娅1技能，
【补充低信赖干员】 选择  黍（默认3技能）。
操作过程中 deploy 了3技能的黍。

### 有什么好的想法？

自动编组选择干员组中某个干员后，行动过程中固定 deploy 编队时选择的干员，而不要 deploy “干员组”。

**Comment by EuropeanWithSSR** [comment]
[与此问题有关但表现不同](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/7251)

**Comment by status102** [comment]
Duplicate of #7251
