### ISSUE TITLE
【无法回到主界面】无法从彩六二期联动活动界面返回主界面

### ISSUE THREAD

**Issue by siuze** [MaaAssistantArknights/MaaAssistantArknights#8506]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

彩六二期联动活动界面内，左上角返回按钮UI较以往发生了变化，致使无法成功执行返回主界面的任务动作，使得刷理智之后的任务无法正常执行。

### Version

Version: v5.2.0-beta.1.d021.g90be17900

### 日志文件

line 6227开始  
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14524507/asst.log)

### 截图

左上角的返回箭头  
![after_公招](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/54578647/7a8b03f5-dc36-4790-84a6-3522c0eb0347)

**Comment by siuze** [comment]
已在最新OTA中适配

**Comment by flower-knight** [comment]
请问这个问题你已经解决的了吗？我在v5.2.0-beta.2版本还是遇到了
