### ISSUE TITLE
希望取消“无奖励关卡”的识别机制

### ISSUE THREAD

**Issue by FSeagle** [MaaAssistantArknights/MaaAssistantArknights#8508]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/37961319/d9e31c5d-24b0-40b1-aa13-e03c508e97fc)
火蓝之心是0体力无奖励关卡，并且关卡简单，很适合用来刷模组任务。
模组任务大多数需要先手打1次，再代理作战4次。MAA可以有效辅助进行剩下的4次作战。
在以前版本的MAA，是可以这么做的。而现在会提示“无奖励关卡，已停止”。
0体力无法只用官方的连续作战，只能手点，因此MAA是很有必要的。
我认为做“无奖励关卡，已停止”这个功能的人没有考虑到刷模组任务的问题，错误认为刷无奖励关卡是完全无价值的。建议删除此功能

### 有什么好的想法？

回滚更新

**Comment by starrin** [comment]
这个限制只针对OF~1，是为了避免有人开了OF-1借助战蹭信用功能然后又用“上次作战”功能刷体力导致无限刷OF-1而设计的，你可以用MAA正常刷OF-2或者更后面的关卡

**Comment by status102** [comment]
自动战斗可以重复刷N次
