### ISSUE TITLE
新的R6主题导致任务错误

### ISSUE THREAD

**Issue by BiTingHunk** [MaaAssistantArknights/MaaAssistantArknights#8509]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

新的R6银行金库的主题UI无法被MMA识别，导致任务错误，只有切换回别的主题UI后MMA才能识别并进行预订任务。

### Version

Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14527208/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14527209/gui.log)

**Comment by Constrat** [comment]
1. It's MAA
2. Either way you're on a older version
3.  You have to wait for someone to fix it (or do it yourself)

**Comment by Constrat** [comment]
Duplicate of
- #8508
