### ISSUE TITLE
关于肉鸽选人逻辑

### ISSUE THREAD

**Issue by xingyu1272** [MaaAssistantArknights/MaaAssistantArknights#851]
看了#167 等
发现实际操作中自动识别练度的程序不会选择六星 一般都是选一个羽毛笔和巫恋 不知道如何调整选人策略

**Comment by xingyu1272** [comment]
就是说 显然其他六星近卫练度肯定比精一的羽毛笔高（甚至剑兔也是精二） 但是为什么选择了精一60级的羽毛笔

**Comment by xingyu1272** [comment]
草 正在写这个issue的时候看了看 发现正好出了个骑士戒律 于是立马把任务关掉了（）但是他到现在没给我抓一个六星 只能说试试看吧（）所以什么时候能加个藏品识别

**Comment by ABA2396** [comment]
是不是你精二的干员有点少，这个是只识别第一页里的所有干员，但是怕希望不够所以是从低星开始选，一般第一页都是六星的话就不会出现这种情况）

**Comment by MistEO** [comment]
因为肉鸽里面，没法看出来是精一还是精二。大家都是精一，羽毛笔抓位很高

**Comment by MistEO** [comment]
> 是不是你精二的干员有点少，这个是只识别第一页里的所有干员，但是怕希望不够所以是从低星开始选，一般第一页都是六星的话就不会出现这种情况）

没有从低星开始选的逻辑了

**Comment by xingyu1272** [comment]
> 

嘶 可以调编队吗 看好像以前是可以调的
