### ISSUE TITLE
mumu模拟器更新后maa用不了了

### ISSUE THREAD

**Issue by Yuxag** [MaaAssistantArknights/MaaAssistantArknights#8511]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

mumu更新了一下maa连接不到模拟器了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161931740/43da6eab-0f5a-4f33-a7d3-33dc8f5b4ca3)

### Version

UI Version: v5.2.0-beta.1.d021.g90be17900

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14527895/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14527908/asst.log)

### 还有别的吗？

mumu模拟器

**Comment by rainRb** [comment]
应该不是mumu模拟器的问题，我现在mumu模拟器版本就是v3.8.5（2722），能正常连接。连接问题的话，要不你试试启动一下mumu内置的问题诊断（在mumu右上角三个杠里），在里面找到adb端口号然后手动输入到maa里试试？
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97787236/0cc24eb2-6dba-4702-bb6d-f8043dd0d491)
或者检查一下是不是adb被你不小心关掉了？
（个人意见，仅供参考）

**Comment by Yuxag** [comment]
> 应该不是mumu模拟器的问题，我现在mumu模拟器版本就是v3.8.5（2722），能正常连接。连接问题的话，要不你试试启动一下mumu内置的问题诊断（在mumu右上角三个杠里），在里面找到adb端口号然后手动输入到maa里试试？ ![image](https://private-user-images.githubusercontent.com/97787236/310984458-0cc24eb2-6dba-4702-bb6d-f8043dd0d491.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzcwNjYsIm5iZiI6MTcwOTgzNjc2NiwicGF0aCI6Ii85Nzc4NzIzNi8zMTA5ODQ0NTgtMGNjMjRlYjItNmRiYS00NzAyLWJiNmQtZjgwNDNkZDBkNDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE4MzkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYTNmZTk3MTI0OWU4M2JmYjQxZWZkZDZkYWEwYmJjZTQ5NzVjNWY5YjMxMWU3YzVhOTk4MDc2MDJhZTc2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CeEi0GV6khPzKcL-1zbJIxaRK_xNrv3kQBcPdH5wGbc) 或者检查一下是不是adb被你不小心关掉了？ （个人意见，仅供参考）

重启了一下电脑就没问题了。很奇怪，不过还好现在正常使用了
