### ISSUE TITLE
新版本自动编队功能无法编入煌

### ISSUE THREAD

**Issue by deathkeft** [MaaAssistantArknights/MaaAssistantArknights#8512]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

先按照程序编入了第一个角色——艾雅法拉，然后编入第二个角色——煌的时候，maa就像是没看见煌一样，翻看了整个干员列表之后，也没有报错，直接跳过了这个角色，开始编入下一个角色

### Version

5.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14528327/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14528329/gui.log)

**Comment by status102** [comment]
能说一下具体发生时间吗，相关内容较多难以直接搜索
