### ISSUE TITLE
Sami Roguelike stuck in loop

### ISSUE THREAD

**Issue by Abolfazl137791** [MaaAssistantArknights/MaaAssistantArknights#8514]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

Hi! I am trying to use MAA for Sami roguelike but it stuck in loop. this is the loop: Home, Terminal, Opening Sami from Terminal, in the home screen of Sami nothing happening and MAA bring the game back to it's main home screen and start again.

### Version

Resource Version: Dorothy's Vision - Retrospection
UI Version: v5.2.0-beta.1.d021.g90be17900
Core Version: v5.2.0-beta.1.d021.g90be17900

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14530182/asst.log)

### Anthing else?

I am using Mumu 3.6.3 (2317)

**Comment by Constrat** [comment]
#8493
