### ISSUE TITLE
Toggle Warnings

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#8515]
### Before raising the issue...

- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I'm probably sure this is a new feature/suggestion and not a bug encountered (please attach logs if you're not sure)

### The problems you have encountered?

In settings (perhaps GUI) option to disable yellow warnings such as "OptimizationTips" and "FastestWayToScreencapWarningTip".
Especially when debugging / working with MAA they can become annoying as they clutter the logs.
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/74350ff0-1b80-4667-8b39-8514fba93d0a)

**Comment by status102** [comment]
考虑在DEBUG VERSION下直接禁用该警告了，以及后面第二条感觉有点长
