### ISSUE TITLE
国际服（EN）自动肉鸽在萨米主题运行异常

### ISSUE THREAD

**Issue by JerryIsCoding** [MaaAssistantArknights/MaaAssistantArknights#8516]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在连接国际服的时候，maa自动肉鸽会卡住在肉鸽界面，好像是无法识别并进入萨米肉鸽，卡住一段时间后会返回主界面并重新尝试进入萨米肉鸽，并且始终无法进入。仅萨米肉鸽如此，其余两个肉鸽运行都正常

### Version

版本：
Resource Version: Dorothy's Vision - Retrospection
UI Version: v5.2.0-beta.1.d021.g90be17900
Core Version: v5.2.0-beta.1.d021.g90be17900

### 日志文件

两个文件出错的位置都在文件的最后，倒数的那几行
[asst&debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14531636/asst.debug.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141092742/bc9ddd07-8544-4491-a02a-923c758abdbb)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141092742/7eaa7abe-adb7-4643-b6c9-968c91ad20a6)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141092742/dae3ccc3-b88f-4151-93db-4d42f5641c29)

**Comment by Constrat** [comment]
#8493
