### ISSUE TITLE
获取信用和购物那里有bug

### ISSUE THREAD

**Issue by yxy5485426** [MaaAssistantArknights/MaaAssistantArknights#8517]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

访问好友基建因为ui改动后，原先的就不能用了，现在在好友界面停止一会，就开始进行下一个任务了。

### Version

资源版本：水晶箭行动
UI版本号：v5.1.0
core版本号：v5.1.0

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14531956/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14531958/asst.log)

**Comment by Rbqwow** [comment]
duplicate of #8503
