### ISSUE TITLE
Stucks on Integrated Strategies choice page when doing IS#4 Sami

### ISSUE THREAD

**Issue by CyberSleeper** [MaaAssistantArknights/MaaAssistantArknights#8518]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

It seems that the MAA is not yet functioning for the entire IS#4. 
1) In normal flow (login -> homepage -> IS page), it stuck on IS choice page and proceed to infinite loop between homepage and IS choice page.
2) If we force it to starts the MAA on the Sami homepage, it will choose to go back to Arknight homepage and back to case (1).
3) Yet if we start the exploration and starts MAA, it is able to abandon the exploration.

### Version

Resource Version: Dorothy's Vision - Retrospection
UI Version: v5.2.0-beta.1.d032.g9da3312a2
Core Version: v5.2.0-beta.1.d032.g9da3312a2

### Log files

I was trying to reproduce the issue starting around 2024-03-08 08:58. Below is my logs.

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14532362/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14532364/gui.log)

### Screenshots

case (1)
![case1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/51506024/43d93f32-5681-4ad9-9f3b-1573c6cba0b8)
case(2)
![case2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/51506024/e9806ce3-f1f0-4272-ae20-4d19a0a6fc04)
case(3), if we starts MAA here, the exploration will be abandoned.
![case3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/51506024/472ea38d-fed6-4e84-9ca3-dad85a8efc90)

### Anthing else?

- I've pinned the IS#4 to the terminal
- IS#2 and IS#3 still works fine
- YostarEN
- Global Server
- BlueStack 5.12.110.1006 P64

**Comment by swablueme** [comment]
@CyberSleeper PR#8493 shows that they are still in the progress of implementing it, but they are dealing with crashes and the text is different from IS3 so it's not easy.
