### ISSUE TITLE
执行任务后软件闪退

### ISSUE THREAD

**Issue by guojunyu196** [MaaAssistantArknights/MaaAssistantArknights#852]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8885044/asst.log)

**Comment by guojunyu196** [comment]
不只是刷理智任务，在其它任务也会闪退
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8885118/asst.log)

**Comment by MistEO** [comment]
看起来是内存不够了，这块相比之前没有变化，尝试把后台其他东西清点掉吧。后续有计划更新一下飞桨，可能会缓和这个问题
