### ISSUE TITLE
涤火杰西卡盾牌的问题

### ISSUE THREAD

**Issue by breaktime1903** [MaaAssistantArknights/MaaAssistantArknights#8520]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA好像在肉鸽中无法识别杰西卡的盾牌，经常把盾牌往高台放，如果拿涤火杰西卡开局，可能对刷肉鸽的速率有比较大的影响

### Version

Resource Version: 水晶箭行动
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14532815/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14532854/gui.log)

### 还有别的吗？

蓝叠模拟器

**Comment by Manicsteiner** [comment]
看看/cache/avatars，有没有机动盾牌，或者机动盾牌的图片对应哪个名称

**Comment by Manicsteiner** [comment]
萨米和傀影的干员分类里把盾牌放在大龙一类了，水月没有提及它的分类，作战方案里也基本没用过这个分类

**Comment by Lancarus** [comment]
> 萨米和傀影的干员分类里把盾牌放在大龙一类了，水月没有提及它的分类，作战方案里也基本没用过这个分类

因为放置逻辑都是放在主阻挡位旁边一格。总之不推荐用dj开局，策略没有那么智能
