### ISSUE TITLE
自动基建换人时，源石订单的贸易站会被错误放入龙舌兰巫恋卡夫卡套组

### ISSUE THREAD

**Issue by xmanthony** [MaaAssistantArknights/MaaAssistantArknights#8527]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

龙舌兰/柏喙，巫恋，卡夫卡套组或者有但书的套组针对的都是赤金订单，在放入源石订单的贸易站时吃不到额外加成的收益。
源石订单的贸易站应该只能放单独加速的套组

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0-beta.1
Core Version: v5.2.0-beta.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14537216/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14537221/gui.log)

**Comment by Manicsteiner** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8358
