### ISSUE TITLE
自动战斗功能无法正常撤退干员

### ISSUE THREAD

**Issue by Skadi-Official** [MaaAssistantArknights/MaaAssistantArknights#8529]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

水晶箭行动自动战斗功能无法正常撤退干员

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0-beta.1.d040.g11c541987
Core Version: v5.2.0-beta.1.d040.g11c541987

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14539538/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14539539/gui.log)

### 截图

maa作业生产基地群有录屏

### 还有别的吗？

mumu模拟器12，排除作业的坐标问题

**Comment by Saratoga-Official** [comment]
和#8473是一个bug
