### ISSUE TITLE
卡在登录认证失效页面不会自动重登

### ISSUE THREAD

**Issue by zoe4477** [MaaAssistantArknights/MaaAssistantArknights#853]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8885128/asst.log)
设置了定时任务, 任务启动前如果手机登录顶过号,  会卡在登录认证失效页面不会自动重新登录
![Snipaste_2022-06-11_19-16-27](https://user-images.githubusercontent.com/38827851/173212796-adf9b9ea-529f-4e79-8326-ca9dac373485.jpg)
![Snipaste_2022-06-11_19-16-40](https://user-images.githubusercontent.com/38827851/173212798-58e1556f-3151-4287-a797-ac5ef7fa677c.jpg)

**Comment by ntgmc** [comment]
该功能已经修复，感谢您的反馈！
