### ISSUE TITLE
彩六主题识别异常

### ISSUE THREAD

**Issue by L4A1onE** [MaaAssistantArknights/MaaAssistantArknights#8530]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

购买并使用了新出的彩虹六号的围攻主题后，主界面操作无法正常识别

### Version

Resource Version: 水晶箭行动
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14539970/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14539971/gui.log)
问题发生在2024.3.8 23：30左右

**Comment by Lemon-miaow** [comment]
Duplicate of #8507 .
