### ISSUE TITLE
MAA在愚人号活动无法刷理智

### ISSUE THREAD

**Issue by bwkdbewkhbiwk** [MaaAssistantArknights/MaaAssistantArknights#8532]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

显示任务出错

### Version

v5.2.0-beta.1

### 日志文件

[asst copy.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14543818/asst.copy.log)

**Comment by bwkdbewkhbiwk** [comment]
v5.1.0也不行

**Comment by status102** [comment]
繁中服？试试内测
