### ISSUE TITLE
关卡选择里面能否增加CR-5，这关可以用来搓玉

### ISSUE THREAD

**Issue by Mudrockiii** [MaaAssistantArknights/MaaAssistantArknights#8536]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by drnarika** [comment]
首先：在刷理智任务的高级设置中，你可以勾选手动输入关卡名来实现这一需求；
其次，即使你不想这么做，你也可以通过先打一次本关卡然后选择列表中的 当前/上次 来解决这一问题。

**Comment by z14git** [comment]
> 首先：在刷理智任务的高级设置中，你可以勾选手动输入关卡名来实现这一需求； 其次，即使你不想这么做，你也可以通过先打一次本关卡然后选择列表中的 当前/上次 来解决这一问题。

1. 手动输入CR-5，会提示“不支持的关卡: CR-5”
2. 选择 "当前/上次" 会影响 借助战打 OF-1
