### ISSUE TITLE
EN 国际服 1.访问好友失败 2.无法从主界面识别仓库 

### ISSUE THREAD

**Issue by Argonautes0607** [MaaAssistantArknights/MaaAssistantArknights#8537]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新最新版后失效

### Version

MAA v5.2.0-beta.2（470）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14544904/asst.log)

**Comment by Constrat** [comment]
Duplicate of #8540
