### ISSUE TITLE
无法识别新的彩虹六号主题

### ISSUE THREAD

**Issue by chawei9374** [MaaAssistantArknights/MaaAssistantArknights#8538]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用彩虹六号主题，MAA无法开始任务

### 有什么好的想法？

希望更新识别彩六主题

### 其他内容

无

**Comment by status102** [comment]
使用5.2.0-beta.2
