### ISSUE TITLE
模拟器自动开启建议

### ISSUE THREAD

**Issue by soundofautumn** [MaaAssistantArknights/MaaAssistantArknights#854]
能不能自定义模拟器启动命令，因为蓝叠能直接生成一键启动游戏的快捷方式，这样就不用通过adb启动了
"C:\Program Files\BlueStacks_nxt\HD-Player.exe" --instance Nougat64 --cmd launchApp --package "com.hypergryph.arknights"
![image](https://user-images.githubusercontent.com/62000745/173217505-919eba3d-7aaf-4bf7-9701-5ac57be8a13c.png)

**Comment by ABA2396** [comment]
你直接把这个.lnk的路径填进去就好了，不要点那个选.exe的按钮，直接点文本框输入.lnk路径
