### ISSUE TITLE
EN 访问好友时 访问点成名片

### ISSUE THREAD

**Issue by luvleizi** [MaaAssistantArknights/MaaAssistantArknights#8540]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

3/9 日 9:00开始执行的任务。 我的换班表是一日三换，有些干员在换了一班后继续，而另一部分则进入宿舍。不换人房间没有影响，而换人的房间则没有得到补充。会客室内两人，有一人更换另一人不变，但没有出错。办公室正常换人。这张排班表没有变过，本身没有问题。刚13:54手动执行的时候发现是先进行获取信用，在好友列表时出错，误点击了个人名片，而不是进行访问，从而导致卡死。13:55一直停在好友界面不动，知道13:58才返回到主界面后进入基建，进入基建后跳过了前面的房间直接从会客室开始。因此会客室和办公室才没出错。并且后面的宿舍也没出错，所以才出现不换人的设施没出错，而换了人的设施无人值班。先执行基建则不会出现换班问题。

### Version

UI Version: v5.2.0-beta.1.d043.gf12323dee

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14545665/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14545666/asst.log)

### 截图

![Screenshot_20240308-212841](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/107036550/9b3b8101-57c0-48d3-be59-3c8fba5521df)
![Screenshot_20240308-214928](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/107036550/e72ef53e-36fb-4fbe-ab90-d4240f680a35)
![Screenshot_20240308-214907](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/107036550/91532f3a-f58d-4c3f-b2d4-f8e32b3455b3)

### 还有别的吗？

雷电模拟器 win10
[搓玉.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14545095/default.json)

**Comment by luvleizi** [comment]
所以，我猜只要访问好友那里不出错就好了

**Comment by Argonautes0607** [comment]
歪楼问下楼主国际服用排班表换班现在还稳定吗，我之前试过老是有干员识别不出就放弃了

**Comment by luvleizi** [comment]
更新 UI Version: v5.2.0-beta.2 公测版后问题依然存在

**Comment by Constrat** [comment]
Ok... This is interesting. Did they switch the buttons? I can't remember if the visit was on the left or on the right. Just experienced the same thing.

**Comment by Constrat** [comment]
For the time being, the quickest fix is to open resource\global\YoStarEN\resource\tasks.json and add this:
```json
    "StartToVisit": {
        "doc": "Temp fix until Overseas gets the same interface as Official",
        "roi": [
            920,
            91,
            162,
            141
        ]
    },

```
