### ISSUE TITLE
无法进入基建

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#8541]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

开始基建换班任务后，错误点进皮肤页面？然后返回到主界面后一直无反应。5分钟后提示任务出错进行下一任务

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0-beta.1.d043.gf12323dee
Core Version: v5.2.0-beta.1.d043.gf12323dee

### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14545228/asst.-.log)

### 截图

![{E7378227-B873-4c40-B21F-26E41268F01C}](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/756d348d-9c4f-4169-b7d3-063ab52fd079)

### 还有别的吗？

主题为银淞

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/aee58349-482c-41ee-a5f7-9f6e16cae765)
又是因为透明度太高识别不到
