### ISSUE TITLE
银凇主题下无法进入基建

### ISSUE THREAD

**Issue by islcyr** [MaaAssistantArknights/MaaAssistantArknights#8543]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

银凇主题下无法从主界面进入基建，MAA会卡住在“开始任务:Infrast”，切换主题如日间后恢复

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0-beta.2
Core Version: v5.2.0-beta.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14545481/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14545483/gui.log)

**Comment by islcyr** [comment]
怀疑可能是透明度或其他的问题

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/581b95db0d132dec9917f10d1212c3c9105555c7 fixed
