### ISSUE TITLE
蓝叠模拟器多开，在正确配置关键词时，两个MAA实例会指向同一个模拟器实例

### ISSUE THREAD

**Issue by camuschen** [MaaAssistantArknights/MaaAssistantArknights#8547]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

已正确配置两个MAA的gui.json配置，两个模拟器引擎分别为Rvc64和Rvc64_5
Bluestack配置文件中检查对应关键词也可以指向对应的引擎。

在第一次通过MAA启动对应模拟器实例时，可以正确获取到端口，但是停止后再次开启任务，就会出现第二个MAA获取到第一个实例的端口。
第一个实例：14022端口
第二个实例：14039端口

### Version

Core Version: v5.2.0-beta.2

### 日志文件

[asst - Rcv64_5.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14545654/asst.-.Rcv64_5.log)
[gui - Rcv64_5.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14545655/gui.-.Rcv64_5.log)
[asst - Rcv64.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14545656/asst.-.Rcv64.log)
[gui - Rcv64.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14545657/gui.-.Rcv64.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/3182731/91b02f61-8446-43f8-b07d-26be3999c9ac)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/3182731/864a1ee6-c73e-482e-bf25-8b22f7f173e0)

**Comment by ABA2396** [comment]
感觉是这个问题，不确定行不行，现在发一个内测版，大概半小时后打出来。之后如果还有问题再reopen
