### ISSUE TITLE
MAA有时会出现打开却不执行任何任务

### ISSUE THREAD

**Issue by hijack114514** [MaaAssistantArknights/MaaAssistantArknights#8549]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA有时会出现打开却不执行任何任务，一段时间后虽然图标会显示MAA但是却点不开，而任务管理器中仍有MAA进程

### Version

UI Version: v5.2.0-beta.2
Core Version: v5.2.0-beta.2

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14546007/gui.log)

### 还有别的吗？

蓝叠模拟器，win10
顺带提一嘴，在某个v4版本后，长时间使用MAA会出现下图情况
![屏幕截图 2024-03-07 212734](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142242356/7766d9cc-1fb9-4bc5-a191-cbe150835ddd)
而且每一个图标都能正常点开不知道为什么

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/665fc70d-c5e8-4b1e-8a9b-2cfe64338792)
~~如果重启资源管理器还这样的话，估计是Windows的问题）~~

**Comment by hijack114514** [comment]
那那个第一个问题呢

**Comment by ABA2396** [comment]
没看懂，什么叫打开但不执行任何任务

**Comment by hijack114514** [comment]
就是我开机自启动两个MAA，有一个会随机宕机，任务管理器可以找到这个宕机的MAA的进程但是点图标点不开，也不执行任何任务
