### ISSUE TITLE
MAA退出时不关闭adb问题

### ISSUE THREAD

**Issue by soundofautumn** [MaaAssistantArknights/MaaAssistantArknights#855]
想要看日志的时候发现的
MAA执行任务时直接点右上角的叉关闭后日志文件还是占用状态，占用的程序是adb，导致每次都要任务管理器手动kill一下

**Comment by zzyyyl** [comment]
确实，不过只需要在启动maa前先调用 `adb devices` 就能避免这个问题（

**Comment by MistEO** [comment]
感谢反馈。c# 界面写了这么久了我们居然一直没做释放，刚刚发现 orz
