### ISSUE TITLE
日服：萨米肉鸽进度卡住

### ISSUE THREAD

**Issue by Eric9877** [MaaAssistantArknights/MaaAssistantArknights#8550]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

日服萨米抗干扰指数0的时候出现预感相同的节点会一直在节点之间切换

### Version

Resource Version: 翠玉の夢・復刻
UI Version: v5.2.0-beta.2
Core Version: v5.2.0-beta.2

### 日志文件

[maa.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14546024/maa.zip)
2024-3-9 18:15左右

### 截图

![MuMu12-20240309-184514](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/154685127/cdaa7d48-cc61-4859-8adb-ffa0f6d68edc)

**Comment by Manicsteiner** [comment]
`Sami@Roguelike@StageFerociousPresageEnter.png` ocr得分太低了，换一张或许可以解决
<img width="100" alt="Sami@Roguelike@StageFerociousPresageEnter" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/ad12598b-29d9-4910-a4cf-f749ad9758e8">
试试用这个替换 `\resource\global\YoStarJP\resource\template\Sami@Roguelike@StageFerociousPresageEnter.png` ，或许能行

**Comment by Eric9877** [comment]
> `Sami@Roguelike@StageFerociousPresageEnter.png` ocr得分太低了，换一张或许可以解决 <img alt="Sami@Roguelike@StageFerociousPresageEnter" width="100" src="https://private-user-images.githubusercontent.com/63437036/311435168-ad12598b-29d9-4910-a4cf-f749ad9758e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5ODcwMDYsIm5iZiI6MTcwOTk4NjcwNiwicGF0aCI6Ii82MzQzNzAzNi8zMTE0MzUxNjgtYWQxMjU5OGItMjlkOS00OTEwLWE0Y2YtZjc0OWFkOTc1OGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDEyMTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NDgxMTljNzUzMGZlODk2NjNlYjFjYjA4YzhmYzQ5N2JkZTdmZGQ3Yzg5NTg4ODRmMmJjNzgyOThkMjA5MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ITwgMxuGczeWIYfPVQl5lleNWEAjrwsm8MXtfJTiUX4"> 试试用这个替换 `\resource\global\YoStarJP\resource\template\Sami@Roguelike@StageFerociousPresageEnter.png` ，或许能行

可以了，感谢
