### ISSUE TITLE
日服肉鸽 开局时有概率放弃招募次要干员

### ISSUE THREAD

**Issue by Manicsteiner** [MaaAssistantArknights/MaaAssistantArknights#8551]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽，默认开局，开局干员使用焰影苇草，使用助战。可以正常招募。但其他两个招募位会在识别完干员列表后不做选择退出。
5.2.0-beta2版本及beta2.d009版本存在此问题，将MaaCore.dll替换为5.2.0-beta1.d021版本可以正常招募。

### Version

见上

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14546082/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14546083/gui.log)
查找 Did not choose oper

### 还有别的吗？

在两台设备进行了测试，应当与操作延迟无关，而是代码改动造成的

**Comment by Manicsteiner** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14546306/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14546307/asst.log)
开局不使用助战也是如此，主要干员能够招募，次要干员放弃招募

**Comment by Manicsteiner** [comment]
Core Version: v5.2.0-beta.1.d032.g9da3312a2 可以
Core Version: v5.2.0-beta.1.d040 不行
应该是这两个版本间的修改造成的，这些测试只替换了MaaCore.dll，没有改动资源文件。

**Comment by Constrat** [comment]
Transferred to #8572

**Comment by Constrat** [comment]
Fixed in [f90fc74](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/f90fc74916d9971922f4430e1bbb580a548dbdd1)
