### ISSUE TITLE
日服薩米肉鴿-遇到事件沼澤裏的抽泣聲會自動放棄探索

### ISSUE THREAD

**Issue by meowings20000** [MaaAssistantArknights/MaaAssistantArknights#8552]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

日服的薩米肉鴿中 遇到事件沼澤裏的抽泣聲會自動放棄探索

### Version

Resource Version: 翠玉の夢・復刻 UI Version: v5.2.0-beta.2 Core Version: v5.2.0-beta.2

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14546284/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14546286/asst.zip)

### 截图

![圖片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92568546/288e6182-490c-4a50-8fb6-6ef370ed91eb)

**Comment by meowings20000** [comment]
看到應該是選了第一個選項 會卡在準備戰鬥的畫面 然後放棄探索

**Comment by Manicsteiner** [comment]
看一下\debug\roguelike目录下有这个事件的截图吗，有的话会方便分析一点

**Comment by meowings20000** [comment]
![2024-03-09_10-43-28-377_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92568546/59ada2c5-237e-40ec-9a47-b63a05b8b3e7)

**Comment by meowings20000** [comment]
在前一個選項（有3個選項的）則沒有截圖

**Comment by Manicsteiner** [comment]
只有这个界面的截图应该就是卡在这个界面了，接下来应该识别 `Sami@Roguelike@StageEncounterOptionUnknown` ，看log似乎没有识别到，也没给ocr得分
