### ISSUE TITLE
使用彩六联动ui后无法正常运行

### ISSUE THREAD

**Issue by aliensnccxx** [MaaAssistantArknights/MaaAssistantArknights#8553]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用彩六联动ui后maa无法正常运行，在开始任务之后就无法进行下一步了

### 有什么好的想法？

1

### 其他内容

1

**Comment by ABA2396** [comment]
更新
