### ISSUE TITLE
[获取信用及购物]好友界面更新导致自动访问好友获取信用功能失效

### ISSUE THREAD

**Issue by RunawayRanger** [MaaAssistantArknights/MaaAssistantArknights#8554]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

水晶剑行动更新后，个人界面连带着好友界面一并更新，导致获取信用任务中的访问好友功能识别不到好友，无法自动访问获取交流信用。

<img width="545" alt="屏幕截图 2024-03-09 232526" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/93019076/06417886-7cc6-4400-8367-f5dea35b7413">

### Version

资源版本号：水晶剑行动
UI 版本号：v5.1.0
Core 版本号：v5.1.0

### 日志文件

为了把问题任务的log单拎出来，我在[2024-03-09 23:21:44.926]这个时间点单独运行了任务，自动购物和OF-01都没有勾选，可以在最后面查找翻看。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14546790/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14546791/gui.log)

### 还有别的吗？

模拟器：蓝叠5.12.115.2201 P64
系统：Win10专业工作站版 22H2 19045.4046

**Comment by Manicsteiner** [comment]
最新公测版已适配
