### ISSUE TITLE
无法识别适配彩六新礼包的UI

### ISSUE THREAD

**Issue by LuYY0908** [MaaAssistantArknights/MaaAssistantArknights#8556]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

彩六礼包新UI围攻，无法正常识别，功能基本全都用不了

### Version

Resource Version: 水晶箭行动
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14547129/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14547131/gui.log)
直接翻到最新一次使用的log

**Comment by Constrat** [comment]
If you don't update MAA, it's obvious it won't work.
