### ISSUE TITLE
无法连接mumu模拟器

### ISSUE THREAD

**Issue by 957176113** [MaaAssistantArknights/MaaAssistantArknights#8557]
### 说说你遇到的问题？

![QQ截图20240310005045](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/29860795/ad5949a2-786e-4811-ab07-61c11ac9c40a)
一直在用，突然就链接不上了，MUMU模拟器和MAA全部重新下载了一样无效（是不保留数据，卸载 再安装）
WIDOWS 使用ABD命令可以连接 MUMU模拟器 127.0.0.1:16384

**Comment by a0wsxz9** [comment]
用adb disconnect一下就好了。感觉是现在maa完成任务断开连接有问题。

**Comment by status102** [comment]
缺少日志等信息
