### ISSUE TITLE
无法识别新的彩虹六号联动主题的问题

### ISSUE THREAD

**Issue by ActivatorL** [MaaAssistantArknights/MaaAssistantArknights#8560]
### 说说你遇到的问题？

在使用新的彩虹六号联动主题时，会在主界面卡住不动后判定任务完成，使用其他主题时则没问题，个人倒是无所谓，先问问之后会有更新识别新的主题的打算吗？

**Comment by Lemon-miaow** [comment]
Duplicate of #8507 #8556 #8553 #8538 #8530 #8519 #8509 .
Please update MAA to 5.2.0-beta.2 .
