### ISSUE TITLE
MAA完成后选择退出MAA，无其他MAA则关机

### ISSUE THREAD

**Issue by huanxui** [MaaAssistantArknights/MaaAssistantArknights#8561]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA完成后选择退出MAA，无其他MAA则关机，3.4.3.5号还能正常使用，最近它不运作了，可能是个人向问题寻求解决方法

### Version

Resource Version: 水晶箭行动
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14549059/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14549060/gui.log)

### 截图

![PI3RKYILZA(}7Y3B)~`LC{S](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/162861985/c3446d4a-c621-41e9-b6e0-b7399d225e3e)

**Comment by ntgmc** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/865cc19f-144e-4afb-a028-baec61d39429)
已增加该功能
