### ISSUE TITLE
无法从彩六二期联动活动界面返回主界面 

### ISSUE THREAD

**Issue by flower-knight** [MaaAssistantArknights/MaaAssistantArknights#8562]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

战斗后无法从彩六二期联动活动界面返回主界面，导致后续任务无法进行。我看见有一个一样的问题[#8506 ](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8506)发生在beta1的测试版，但他自己关了说已解决。我更新到v5.2.0-beta.2依然会出现卡在彩六活动页的情况。

### Version

v5.2.0-beta.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14549062/asst.log)

### 截图

![Snipaste_2024-03-10_13-58-03](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75349850/42a65d1e-c646-468e-89c2-9e97c850166c)

### 还有别的吗？

maa跑在Unraid（Slackware 15.0 x86_64）上，使用node-red调用。
游戏跑在镜像redroid/redroid:11.0.0-230331上，操作系统也是Ubuntu 22.04.2 LTS

**Comment by ABA2396** [comment]
这个要拉API的tasks之后才行，里面临时把returnbutton的阈值改成了0.65，Linux的是不是没有这个逻辑？

**Comment by flower-knight** [comment]
> 这个要拉API的tasks之后才行，里面临时把returnbutton的阈值改成了0.65，Linux的是不是没有这个逻辑？

请问具体咋改啊，我手动改一下算了

**Comment by ABA2396** [comment]
resource/tasks.json 搜ReturnButton，把第一个0.7改成0.65

**Comment by flower-knight** [comment]
> resource/tasks.json 搜ReturnButton，把第一个0.7改成0.65

感谢，解决了。顺便请教下win版是比对哪个网址实现替换的，我用node-red写个流程看看能不能自动化一下

**Comment by ABA2396** [comment]
https://ota.maa.plus/MaaAssistantArknights/api/resource/ 中有需要附加的tasks.json
https://ota.maa.plus/MaaAssistantArknights/api/gui/StageActivity.json 中有当前各服开放的关卡
https://ota.maa.plus/MaaAssistantArknights/api/lastUpdateTime.json 是更新的时间

tasks.json中的内容不是完整的task，是要附加到本地的tasks.json中的，可以直接传入core让它额外加载一次资源，参考https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/2992a1a02e6438a719a1969fca1aa48b764197d6/src/MaaWpfGui/Main/AsstProxy.cs#L199-L237

**Comment by ABA2396** [comment]
cc @hguandl mac有类似的问题吗？应该也会遇到
