### ISSUE TITLE
使用开始唤醒退出当前账号时在游戏的"开始唤醒"界面进行maa开始唤醒动作失败，导致无法切换账号

### ISSUE THREAD

**Issue by ReimsWwW** [MaaAssistantArknights/MaaAssistantArknights#8563]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

勾选开始唤醒，可以正常退出当前账号，但是在游戏启动界面会呆住，不进行下一步动作，楞一会儿然后提示startup失败。不是每次都会触发，但是基本5次里有3次。

### Version

UI Version: v5.2.0-beta.2.d017.g84b722ab2
最新的内测版

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14549277/debug.zip)

### 还有别的吗？

mumu12，官服

**Comment by ReimsWwW** [comment]
不会打开账号选择界面，所以其实不换号也会卡住。直接在启动界面运行的话基本没有问题

**Comment by ABA2396** [comment]
cc @status102
