### ISSUE TITLE
日服萨米肉鸽遇到unknown fog节点时卡住

### ISSUE THREAD

**Issue by Edsater** [MaaAssistantArknights/MaaAssistantArknights#8564]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

maa在萨米肉鸽中，遇到多个并列可选的模糊的无法勘察的节点（即unknown fog）时，会卡住不动，一直不进行任何操作。

### Version

Core Version: v5.2.0-beta.1.d021.g90be17900

### 日志文件

问题出现在2024-03-10 16:54:26之后一点点（之前也出现过很多次）
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14549619/debug.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/80636626/c99356d3-64b7-4f0c-83fd-72559bf6a15e)
在这个位置maa会停止操作

### 还有别的吗？

没有了

**Comment by ArndtEistert** [comment]
YostarEN亦遇到相似问题，MUMU12，UI Version: v5.2.1-alpha.1.d002.g7cc1e7b55
