### ISSUE TITLE
【基建换班】识别训练室专精结果时，干员艾拉的名称识别错误

### ISSUE THREAD

**Issue by pyreymo** [MaaAssistantArknights/MaaAssistantArknights#8566]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

基建换班：识别训练室专精结果时，干员艾拉的名称识别错误。

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0-beta.2.d017.g84b722ab2
Core Version: v5.2.0-beta.2.d017.g84b722ab2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14550027/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14550028/gui.log)
问题出现的大致时间点: 03-10 19:54:32

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45317256/b0637b16-8146-455b-b091-e783510ba9db)

### 还有别的吗？

模拟器：bluestacks
OS: win11
基建换班相关配置截图：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45317256/a1ed4d70-de16-4be1-82de-9af48127fa66)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45317256/9790cc0c-fadf-4f13-b474-5838cf656aa2)

**Comment by pyreymo** [comment]
#8352 专精技能完成后识别信息显示干员名称（黍）错误

**Comment by ABA2396** [comment]
这个问题还不太一样，是没识别到前面的[，但是传给ui的内容是raw_str.substr(1, separation_pos - 1)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/398b35a3-f5e8-4d9d-8901-877aca7c14c1)
等于把第一个字切了一半出来
