### ISSUE TITLE
显示器分辨率识别错误导致无法开启

### ISSUE THREAD

**Issue by AlanFenix** [MaaAssistantArknights/MaaAssistantArknights#857]
先奉上日志[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8885548/asst.log)

然后奉上dmp文件[crashlog_3.0.1727_20220612164821_meoasstgui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8885551/crashlog_3.0.1727_20220612164821_meoasstgui.zip)

下面是问题描述：
1、在双屏（皆为横屏）完全没问题的前提下，加了一个竖屏，且设置竖屏为主屏，分辨率都是1080p，但软件打开后无法识别分辨率（附图
![XRZZYS9_DCTI`)0{ML8Q JQ](https://user-images.githubusercontent.com/17558552/173226726-d35367a8-aa34-4788-bc3b-785456f22539.png)
![PO7)33HD7R 22 }LID0W$_4](https://user-images.githubusercontent.com/17558552/173226683-828f7669-3d80-400f-8da1-7e3fb748eeee.png)
![K()A1J0X(9@VAMQDOH28QU3](https://user-images.githubusercontent.com/17558552/173226696-2da1954b-07e2-4f72-8b94-ea8ea8c61a4d.png)
）

2、然后发现程序在没有任何弹窗提示（仅有声音提示）的情况下自动关闭窗口（进程依然存在），且会自动生成一个dmp文件。强制终止进程且重新安装最新版本后问题解决。

**Comment by MistEO** [comment]
和电脑分辨率没有关系，提示已经写得很清楚了，分辨率过低，显然指的是模拟器分辨率。从日志来看你的模拟器分辨率是 540p 的

```
[2022-06-12 16:55:14.143][TRC][Px4694][Tx59c4] Call ` C:\Program Files (x86)\MuMu\emulator\nemu\EmulatorShell\..\vmonitor\bin\adb_server.exe -s 127.0.0.1:7555 shell dumpsys window displays | grep init= | awk ' { print $3 } ' ` ret 0 , output size: 14 
[2022-06-12 16:55:14.143][TRC][Px4694][Tx59c4] output: cur=864x540
```

**Comment by AlanFenix** [comment]
![image](https://user-images.githubusercontent.com/17558552/173228872-2633ced1-333a-4dc5-abdc-e48a8fc7314f.png)
好吧，确实，应该是模拟器默认在竖屏中启动，导致其分辨率默认值过低。。。
