### ISSUE TITLE
[JP] 水月在完成第一關後戰利品介面卡住

### ISSUE THREAD

**Issue by Mion354D** [MaaAssistantArknights/MaaAssistantArknights#8570]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

水月在第一關勝利後, 戰利品介面卡住, 必定重現

### Version

Core Version: v5.2.0-beta.2.d017.g84b722ab2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14550784/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14550785/gui.log)

### 截图

![20240310-233327](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/7450570/16eccbba-ef98-4c98-a964-8aa73d832fe6)

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/7450570/f3cf9f82-c428-4f1c-8a66-8cf00da53f84)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/7450570/fc1e797c-e21d-419d-b68d-d99f0bd6e695)

**Comment by Manicsteiner** [comment]
看log是作战结束后根本没进getdrop的任务。
由于MAA现在有其他问题，我在用 v5.2.0-beta.1.d032.g9da3312a2 版本，没有复现这个bug，如果急用可以尝试回退至此版本。

**Comment by Mion354D** [comment]
Seems fixed in v5.2.0-beta.2.d042.gc6ee06318

**Comment by Constrat** [comment]
Good, but I don't think any changes were made regarding this. Might have been a one off, as it was not reproductible.
