### ISSUE TITLE
生息演算闪退

### ISSUE THREAD

**Issue by 0107zjy** [MaaAssistantArknights/MaaAssistantArknights#8573]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用mumu模拟器12最新版V3.8.7(2746)，其他一键长草功能正常，但是使用生息演算·沙洲遗闻时候会闪退，上一个月用的时候还没有这个现象，在生息演算奖励更新后再刷就变成这样了，每次到这一步MAA就闪退，MAA公测版，稳定版都试过了，没用，编队什么的都清空的
![搜狗截图20240311092840](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/162936726/110d411f-9984-4c6b-962e-d8dbaefebf4a)

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0-beta.2
Core Version: v5.2.0-beta.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14552621/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14552622/gui.log)

### 截图

![搜狗截图20240311092840](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/162936726/a1eb7a9f-aa89-424f-9c69-b5ef31a3c29b)

### 还有别的吗？

使用mumu模拟器12最新版V3.8.7(2746)，windows系统

**Comment by Rbqwow** [comment]
或许可以找找事件查看器里记录的日志？

**Comment by 0107zjy** [comment]
打扰了，我清的是外边的四个编队，不是里面的编队，我太傻了
