### ISSUE TITLE
基建换班卡死在宿舍

### ISSUE THREAD

**Issue by Zincccccck** [MaaAssistantArknights/MaaAssistantArknights#8575]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

换班卡死在最后一步，在宿舍，详见附的视频和图片，我发现问题已经是半个小时以后了

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0-beta.2
Core Version: v5.2.0-beta.2

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14555016/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14555018/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94158391/4e49c900-3922-483c-8bcb-5dd6b2799eac)

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94158391/507dc20e-178e-4c7c-ad91-685f428f20c0

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/94158391/f155cd12-e534-46d1-96c4-aadfde153a05

**Comment by Zincccccck** [comment]
第二个视频是我手动停止以后的

**Comment by GodotR** [comment]
遇到了同样的bug
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15010684/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15010687/gui.log)
以及使用蹭信赖功能时，不按照信赖从低到高顺序选取干员
宿舍03选干员后，不切换到信赖，而是继续遍历干员列表。
该情况在5.2.1更新前未发生过
