### ISSUE TITLE
萨米主题 导致无法执行基建换班

### ISSUE THREAD

**Issue by zlqd123** [MaaAssistantArknights/MaaAssistantArknights#8576]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

选择MAA除肉鸽和生息以外所有功能时，一套执行下来会跳过基建换班。
单独执行基建换班则正常

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0-beta.2
Core Version: v5.2.0-beta.2

### 日志文件

[asst 基建不执行.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14555359/asst.log)
[gui 基建不执行.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14555361/gui.log)

[asst 基建单独执行.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14555410/asst.log)
[gui 基建单独执行.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14555411/gui.log)

### 截图

一套下来执行结果如图
![QQ截图20240311160430](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32678715/de51c145-a3e4-406d-b88d-9abac1ecaaca)

### 还有别的吗？

官服
MUMU模拟器12
Win11 23H2

**Comment by ABA2396** [comment]
估计是这次更新之后又改了ui的透明度，原来能跑的主题又出问题了

**Comment by zlqd123** [comment]
[asst 单独排班失败.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14566745/asst.log)
[gui 单独排班失败.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14566746/gui.log)
这是萨米主题单独执行排班也失败的案例；

换了谜城，试了一次是好的，之后再看看

**Comment by RimuruChan** [comment]
成功复现

**Comment by SherkeyXD** [comment]
我的萨米肉鸽主题也出问题了
要不改个阈值？
