### ISSUE TITLE
新版UI，获取信用时，不能识别好友宿舍进去

### ISSUE THREAD

**Issue by Ericcccccca** [MaaAssistantArknights/MaaAssistantArknights#8577]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

新版UI，获取信用时，不能识别好友宿舍进去

### Version

Resource Version: 水晶箭行动
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14555924/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14555927/gui.log)
时间点：16:38

**Comment by ABA2396** [comment]
5.2.0-beta.2 fixed
