### ISSUE TITLE
生息演算总是在第一天第二个场景卡死

### ISSUE THREAD

**Issue by growyyyyyy** [MaaAssistantArknights/MaaAssistantArknights#8579]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![c6590dae1e6438aa0e385c13f28ea2ae](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110042555/fe8497ea-0b69-4d65-8a41-75959dc93a3d)
在生息日1的第二个场景不退出，显示任务出错，直接停止。
是Mac用户

### Version

MAA v5.2.0-beta.2 是当前的最新版本。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14560019/asst.log)

### 截图

![c6590dae1e6438aa0e385c13f28ea2ae](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110042555/f84e4d3c-8ca3-434d-92e3-a0e2a1f798f4)

### 还有别的吗？

mac自带的play cover，其他功能都没有问题

**Comment by AoJ0c1** [comment]
出问题好久了 5.1也不行

**Comment by Wineondili** [comment]
我也是，macOS上使用maa执行生息演算总是会显示任务出错，直接停止
