### ISSUE TITLE
国际服 到肉鸽商店会卡住 然后MAA会立刻关闭

### ISSUE THREAD

**Issue by beaverfloof** [MaaAssistantArknights/MaaAssistantArknights#8582]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

和这个bug一样https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8445

当使用自动肉鸽时, 每到商店MAA总是卡住并自动闪退

我试过Bluestacks和Nox，都是一样的结果

上传了BS和Nox闪退之前的log

### Version

Resource Version: Dorothy's Vision - Retrospection
UI Version: v5.2.0-beta.2.d017.g84b722ab2
Core Version: v5.2.0-beta.2.d017.g84b722ab2

### 日志文件

[asst_nox.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14564753/asst_nox.log)
[gui_nox.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14564756/gui_nox.log)
[asst_bs.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14564868/asst_bs.log)
[gui_bs.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14564874/gui_bs.log)

**Comment by Constrat** [comment]
Already been fixed. No ETA on new version.
