### ISSUE TITLE
基建换班时发生冲突增添一个强制切换的功能

### ISSUE THREAD

**Issue by 1479997810** [MaaAssistantArknights/MaaAssistantArknights#8584]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我的基建换班是243的，3班循环的时候当天的第三班的制造站2会和第二天上午的第一班制造站1的位置冲突，导致一个制造站摆烂，如果调整第三班制造站1和2的位置又会导致第二班和第三班发生冲突，没办法进行有效的循环，附图如下，希望在基建换班时发生冲突增添一个强制切换的功能

### 有什么好的想法？

希望在基建换班时发生冲突增添一个强制切换的功能

### 其他内容

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97530508/9fa35abe-b10d-4509-a1f4-64f99e517c5f)
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97530508/0c999d62-63e1-4587-b82e-0bb095a7112c)
![3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97530508/19631c55-6474-4518-97cb-77475deb66d3)

**Comment by ABA2396** [comment]
现在发生冲突就是不管冲突直接塞进去的啊

**Comment by 1479997810** [comment]
> 现在发生冲突就是不管冲突直接塞进去的啊

不会啊，冲突它就直接跳过了啊。。。

**Comment by ABA2396** [comment]
那就是bug，另启一个bug report。干员冲突会有一个弹窗问你是否继续，maa都是直接点确定的

**Comment by Constrat** [comment]
Transferred to 
- #8585
