### ISSUE TITLE
基建换班时发生冲突直接跳过，导致工作摆烂

### ISSUE THREAD

**Issue by 1479997810** [MaaAssistantArknights/MaaAssistantArknights#8585]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我的基建换班是243的，3班循环的时候当天的第三班的制造站2会和第二天上午的第一班制造站1的位置冲突，导致一个制造站摆烂，如果调整第三班制造站1和2的位置又会导致第二班和第三班发生冲突，没办法进行有效的循环，附图如下

### Version

UI Version: v5.2.0-beta.2.d017.g84b722ab2

### 日志文件

[Uploading debug.zip…]()

### 截图

![4](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97530508/c285a8a4-db03-4c7d-933c-724d30f51d37)
![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97530508/d84c9379-fe74-4f0d-aac0-c6928d053cef)
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97530508/4a86ba4f-b73e-4d08-a38a-ed4dcce69cef)
![3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97530508/b13765d7-4a7e-4ed7-a0ea-05759ba06d4d)

### 还有别的吗？

蓝叠模拟器5；安卓系统

**Comment by 1479997810** [comment]
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14566990/debug.zip)

**Comment by ABA2396** [comment]
这玩意能复现吗，最好录个视频看看
看日志是那时候模拟器非常的卡，退出设施的时候按了返回键但模拟器并不能立刻响应，退出去的时候刚和和第二次返回叠加了，直接就退出了基建
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/6e656053-110c-48cf-b2bf-e0f4a6d45e83)
正常来说应该是这样的
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/e0499dd4-d14b-4b3f-bec2-2c8516b258a9)
