### ISSUE TITLE
明日方舟国际服傀影肉鸽第一层商店存钱后maa闪退

### ISSUE THREAD

**Issue by bhc0916** [MaaAssistantArknights/MaaAssistantArknights#8588]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

尝试过重新下载maa和模拟器，电脑配置是联想拯救者Y9000P 4060ti， 国际服在近期更新一次客户端之后试用maa在傀影肉鸽第一层商店存钱后maa会直接闪退，采用刷取源石锭的方案没有该问题，但是选择刷取等级就会闪退。没有任何报错或者弹窗提示，maa会直接退出。以及国际服目前是否还无法使用萨米肉鸽？选择萨米肉鸽会卡在肉鸽主题的选择界面。

### Version

Resource Version: Dorothy's Vision - Retrospection
UI Version: v5.2.0-beta.2.d017.g84b722ab2
Core Version: v5.2.0-beta.2.d017.g84b722ab2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14569081/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14569082/gui.log)

**Comment by Constrat** [comment]
Duplicate of #8582
Already fixed

**Comment by Constrat** [comment]
Duplicate of #8582
