### ISSUE TITLE
使用彩虹六号的新界面主题无法正常识别

### ISSUE THREAD

**Issue by unreliable-boy** [MaaAssistantArknights/MaaAssistantArknights#8589]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用新版彩虹六号的主题时，任务识别会出错，切换回普通主题后可以正常使用

### Version
稳定版
Resource Version: 水晶箭行动
UI Version: v5.1.0
Core Version: v5.1.0
### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14570113/asst.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14570118/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14570119/gui.log)
3/12 17:28左右

### 截图

![微信截图_20240312173053](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57299332/e6c6dabe-76ae-40ce-9bda-e4dfd5cbe5f8)
![微信截图_20240312173532](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57299332/928457b3-72cf-44ee-bbec-8fbb72c59931)

**Comment by ABA2396** [comment]
[v5.2.0-beta.2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v5.2.0-beta.2) fixed
