### ISSUE TITLE
自动作战1-3次后与蓝叠模拟器断开连接

### ISSUE THREAD

**Issue by shadow2334** [MaaAssistantArknights/MaaAssistantArknights#859]
![Y0FFO 679S4)4K UEXPN_6U](https://user-images.githubusercontent.com/107349000/173229135-ace04fbb-49d6-4780-b293-b7d99798acc8.jpg)
进行其他任务不会这样，就只有自动战斗也就是刷理智的时候会断开连接。
用的是蓝叠模拟器国际版，重启模拟器之后仍然会出现此问题。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8885654/asst.log)

**Comment by MistEO** [comment]
一般机器截图大概消耗 100 - 500 ms, 于是我们设置了一个 3 秒的超时。

但是你的电脑实在太卡了 orz, 是真的用了不止 3 秒。。后续版本我们会考虑把这个超时时间改大一点

**Comment by shadow2334** [comment]
不会吧，真有这么离谱吗。。
![image](https://user-images.githubusercontent.com/107349000/173229640-9fed1e75-6415-490a-8c10-e50b5fb65ca9.png)
显卡也是NTX 2060的，，

**Comment by zzyyyl** [comment]
> 一般机器截图大概消耗 100 - 500 ms, 于是我们设置了一个 3 秒的超时。
> 
> 但是你的电脑实在太卡了 orz, 是真的用了不止 3 秒。。后续版本我们会考虑把这个超时时间改大一点

也许可以放个自定义设置

**Comment by zzyyyl** [comment]
> 不会吧，真有这么离谱吗。。 ![image](https://user-images.githubusercontent.com/107349000/173229640-9fed1e75-6415-490a-8c10-e50b5fb65ca9.png) 显卡也是NTX 2060的，，

这配置跟我一模一样！

你是不是没插电（？

**Comment by shadow2334** [comment]
> 

插了电呀。

**Comment by zzyyyl** [comment]
> > 
> 
> 插了电呀。

怪耶，我同配置用雷电截图时间不到300ms（
~~总不会是蓝叠的原因吧~~

**Comment by shadow2334** [comment]
> 

我这也不是刚用，用很久了。也就这几天出现的问题，也不知道啥原因。

**Comment by zzyyyl** [comment]
会不会是 nc 的原因（？
看日志里 `cat /proc/net/arp` 好像有两行，这块我不太懂，但是是最近加的（

**Comment by zzyyyl** [comment]
草，仔细看了日志，这个时间差太离谱了吧，300ms到3000ms都有（
玛丽要不要加一个是否使用socket截图的自定义选项？
@MistEO
