### ISSUE TITLE
水月肉鸰事件远销海外卡死

### ISSUE THREAD

**Issue by Bamboo6899** [MaaAssistantArknights/MaaAssistantArknights#8590]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

水月肉鸰事件节点远销海外卡死
在此节点时，很多情况下源石锭会不足5个，但脚本却只会选择第一个选项(消耗5源石锭获得3希望)，导致卡死在此节点。 理想情况下应该选择离开。
![Bug](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/162856255/c65587af-b973-4656-81ce-c2758f5fead4) (在此节点卡了1小时以上)
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/162856255/fc5ef7b4-310a-4d35-b4db-474926adaf30)

### Version

UI Version: v5.1.0

### 日志文件

[BUG.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14570914/BUG.zip)
时间点:
[2024-03-12 17:07:10.521] <1><> 戰鬥完成
[2024-03-12 17:07:43.643] <1><> 事件: 远销海外
[2024-03-12 18:21:55.195] <1><> 關卡: 普通作戰

### 截图

![Bug](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/162856255/ca1a4b94-c1ec-4e3c-8b74-aa05d0524984)
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/162856255/4ffdff04-9018-424b-85a5-e2af5940745b)

### 还有别的吗？

MuMu 12

**Comment by flurrymouse** [comment]
遇到了相同的问题
