### ISSUE TITLE
日服 刷理智 掉落辨识错误

### ISSUE THREAD

**Issue by amasoiD** [MaaAssistantArknights/MaaAssistantArknights#8591]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

刷术狙晶片关时无法正常辨识掉落物

### Version

Resource Version: 翠玉の夢・復刻
UI Version: v5.2.0-beta.2.d042.gc6ee06318
Core Version: v5.2.0-beta.2.d042.gc6ee06318

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14571314/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14571315/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120790328/24c79b95-fe06-42fd-a997-9b3de39905ba)

debug\drops截图

![2024-03-12_18-55-03-862_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120790328/5fea3e5e-9c37-42d2-83d8-652361f57423)
![2024-03-12_18-57-00-818_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120790328/1e8e93c9-6efa-44d8-bd2c-e60c14fa004f)
![2024-03-12_18-58-57-796_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120790328/0bfef503-2dbf-4b80-a21f-07b8a146df04)
![2024-03-12_19-00-54-732_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120790328/d34546dd-c90b-4ae3-8ac3-a47c4b3d9fe0)

### 还有别的吗？

雷电模拟器9.0.57(9)
Windows 10 家用版 20H2

**Comment by Constrat** [comment]
(https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/f90fc74916d9971922f4430e1bbb580a548dbdd1) should have fixed all the ocr issues.
