### ISSUE TITLE
基建換班 Lancet-2與Castle-3 辨認異常

### ISSUE THREAD

**Issue by EROTCZ** [MaaAssistantArknights/MaaAssistantArknights#8593]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

BUG 1
3-13 00:03:36 Castle-3 食鐵獸 斷罪者  <只勾選 食鐵獸 斷罪者 然後Castle-3 一直沒偵測到
3-13 00:07:00 終於偵測到Castle-3了 但是 不知道為啥 他原本食鐵獸與斷罪者 沒勾選到 就確認排班了
該狀況跟 #7072 一模一樣
BUG 2
3-13 00:11:19  偵測不到Lancet-2   但是他有勾選到  一直不進行確認?
3-13 00:13:05  偵測不到Lancet-2
3-13 00:16:25  偵測不到Lancet-2
因為遲遲沒有結果 00:19:43 我直接幫按確認了
該狀況跟 #8026 一模一樣

### Version

Resource Version: 愚人號·復刻
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14575699/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14575705/gui.log)

### 截图

![MuMu12-20240312-122402](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153876121/ef463a6c-e8cb-4793-890d-ac6b2b084bda)
![MuMu12-20240312-122435](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153876121/a78afa30-04bc-4873-9b12-7daeb8d97762)

### 还有别的吗？

MuMu Player 12 V3.8.3 (2696)
windows 11

**Comment by ABA2396** [comment]
上传的两个日志404了，重新传一下

**Comment by EROTCZ** [comment]
> ~~上传的两个日志404了，重新传一下~~
> 好像是GitHub的缓存服务器炸了，现在文件都是404

404好像好了
還是不行的話 我上傳百度網盤

https://pan.baidu.com/s/1QpWis5cu50R-R9cweg5X1g?pwd=1111

**Comment by EROTCZ** [comment]
> ~v5.2.0
修复 | Fix
基建換班 Lancet-2/Castle-3 识别异常 @ABA2396

我有下載更新版的V5.2.0 MAA
該BUG 好像還是存在  我再傳最新的asst.log跟gui.log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14602900/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14602904/gui.log)

**Comment by ABA2396** [comment]
哦草忘了外服不是直接继承的了，找一下仓库里的 resource/global/txwy/resource/tasks.json 替换下本地的文件应该就好了（或者等过会儿资源更新应该也会过去）
