### ISSUE TITLE
使用彩六联动界面长草卡死

### ISSUE THREAD

**Issue by 1792636138** [MaaAssistantArknights/MaaAssistantArknights#8595]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

用了彩六界面之后，开长草任务无反应，换回普通界面后正常

### Version

Resource Version: 水晶箭行动
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14580878/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14580879/gui.log)

2024-03-13 09:44:08.448

**Comment by ABA2396** [comment]
5.2.0-beta.2 fixed
