### ISSUE TITLE
换班时在训练室 MAA闪退

### ISSUE THREAD

**Issue by kkujukk** [MaaAssistantArknights/MaaAssistantArknights#8596]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

今天自动更新后，发现maa在执行自动基建时会在点击训练室后闪退(maa闪退，后台直接掉了，不是蓝叠闪退)，尝试了3次，闪退了3次

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0-beta.2.d042.gc6ee06318
Core Version: v5.2.0-beta.2.d042.gc6ee06318

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14582413/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14582414/gui.log)

**Comment by ABA2396** [comment]
今天GitHub的文件换成服务器好像出问题了，文件都下不下来
上午修了下这个问题，现在打个新的内测版，过半个小时看看

**Comment by kkujukk** [comment]
> 今天GitHub的文件换成服务器好像出问题了，文件都下不下来 上午修了下这个问题，现在打个新的内测版，过半个小时看看

刚试了下 还闪退

**Comment by ABA2396** [comment]
cc @status102 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/2725b30841f831c47e618b3af152941e34dec099 这里ocrreplace写错了

@kkujukk 试试把这个文件里的 `"^[",` 替换成 `"^\\["`,

**Comment by status102** [comment]
f9599282f929b55234e3a7b45ad566c0594cac79
