### ISSUE TITLE
Mac maa可以通过playcover打开舟，但是不操作

### ISSUE THREAD

**Issue by FroPho** [MaaAssistantArknights/MaaAssistantArknights#8598]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

macmini：从用户手册中的链接下载了最新playcover，完成配置。但点击上方运行按钮后，此处开始转圈加载，能够打开舟但不能对打开的窗口进行任何操作。在正常运行下，上方应该为实心正方形，并开始操作，而此处仍然为表开始的三角形。如下图所示。即使手动单机进入到开始唤醒界面，甚至进入到游戏页面中仍无反应，
![微信图片_20240313184635](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119748608/f22ce7a7-52b6-4dc0-a235-8971fb55baae)
![微信图片_20240313184639](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119748608/b2736117-8144-4285-8332-b0d39a424347)
![微信图片_20240313184831](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119748608/1cd9c091-9d9b-48f4-a1d7-ce342efc8a77)

### Version

maa v5.1.0 (466)

### 日志文件

时间：大版本更新后最近的几次都是，比如2024.03.13 18：45左右。然后日志文件夹例没有gui.log文件，有的文件全上传了。
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14586477/asst.bak.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14586481/asst.log)

### 截图

debug文件夹内容如图：两个.log文件已上传，剩余两个文件夹里是一些图片，看日期标注应该在大版本更新之前，因此是在问题出现之前的。这里为以防万一，也
[other.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14586525/other.zip)
打包上传。![微信图片_20240313185441](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119748608/dc7e6d69-4884-49f2-b8f4-8f6f319412d9)
[sanity.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14586526/sanity.zip)

### 还有别的吗？

我看issue里之前也有一个帖子#8546问了相同内容，但是因为没上传日志文件就没有后续了，所以这里重开一个。他的macos是14以上的，好像也不行。其实mac上的maa之前也都是好的，就是从这次水晶箭行动大版本更新后坏掉的。
macOS Ventura 13.3
Playcover 3.0.0.maa4 (4)
明日方舟 Bundle 版本号：2.2.21
![微信图片_20240313190029](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119748608/023e00d7-695b-450a-bd17-9545ade2d012)

**Comment by horror-proton** [comment]
这似乎是 mac 客户端的问题, 另外你是不是在关卡名里填了 CR-7 可能是这个不支持的关卡造成了问题, 关掉刷理智任务再试试

**Comment by FroPho** [comment]
今天试了一下 突然就好了 但是这两天win和mac都同时出现了卡在主菜单无法进基建的情况 看到其他人已经反馈了
