### ISSUE TITLE
每次开始任务会显示触控模式不可用再开始运行任务

### ISSUE THREAD

**Issue by GYF0814** [MaaAssistantArknights/MaaAssistantArknights#8599]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/88437660/3b0dc16f-e44b-46a4-9d00-338cd437fd84)
如图片所示，每次在重启电脑或是重启mumu模拟器之后便会出现这个问题，之前填的是固定端口但是连了两次之后就连不了，于是现在用的是自动检测连接和每次重新检测，但每次（具体如上所示）都会出现这个

### Version

UI Version: v5.2.0-beta.2.d057.gf9599282f

并不是只有这个版本才有问题 从5.0开始就在用 一直有这个问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14587147/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14587148/gui.log)

### 截图

![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/88437660/78ad6fff-aad1-4ae0-bf2f-3a4cdfa08037)

### 还有别的吗？

模拟器：mumu12 
操作系统：win11 23h2

**Comment by ABA2396** [comment]
mumu有时候刚启动的时候adb会有问题，试试在设置里延长等待模拟器启动时间

**Comment by GYF0814** [comment]
> mumu有时候刚启动的时候adb会有问题，试试在设置里延长等待模拟器启动时间

应该不是这个问题 在学校机房试了一下就没有这个问题 不过在这个电脑就能复现 试过重装也没啥用

**Comment by Noitolar** [comment]
我这边也是这个问题，等待解答
