### ISSUE TITLE
Recruitment priority | Squad priority in I.S.

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#8600]
After finally fixing the elite / level detection for I.S., the recruitment priority seems still off.
MAA decides to recruit the 预备干员-近战 (E1 60), when there are much better alternative options, for example: 休谟斯. Priority seems very low, considering all the other alternatives. (Just a 泡普卡 has a priority of 460). Is there a reason for this?
```py 
[TRC][Px4744][Tx1134] asst::RoguelikeRecruitTaskPlugin::_run | Top priority oper: 预备干员-近战 108 page 4 / 5
```
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14588080/asst.log)

**Comment by Constrat** [comment]
Thank you very much. This clears a lot of things.

**Comment by Lancarus** [comment]
> [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14600816/asst.log) Also squad formation priority seems off. MAA tries to select all operators (12) even though there are only 6 spaces available. Because of this, 6* core operators (even E2) are not selected. Seems like they are placed behind all the others and because there are not enough spaces available they can't get selected.
> 
>  output.mp4
It‘s no problem.Maa will first step select core operators.Seen in recruitment.json "team_complete_condition". Then select operators in rank of level high to low. Last select alternative operators.
