### ISSUE TITLE
B服 基建换班功能运行到训练室（技能专精）时固定闪退

### ISSUE THREAD

**Issue by JUEQI34** [MaaAssistantArknights/MaaAssistantArknights#8602]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

B服使用一键长草功能时运行到训练室自动闪退，有多次现象

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0-beta.2.d057.gf9599282f
Core Version: v5.2.0-beta.2.d057.gf9599282f

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14590435/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14590436/gui.log)
2024-03-13 23:16:10.322发生问题

**Comment by status102** [comment]
duplicate of #8596
