### ISSUE TITLE
好友基建无法访问

### ISSUE THREAD

**Issue by ChoppySweep** [MaaAssistantArknights/MaaAssistantArknights#8604]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA不进行好友访问，在好友界面直接直接卡住然后跳过，疑似UI更新后无法识别导致

### Version

Core Version: v5.1.0
UI Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14591083/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14591084/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125214646/53ab9d30-4118-4757-8447-ab6758838975)

### 还有别的吗？

蓝叠模拟器国际版

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/56651f5b-85a4-41c4-90d5-3973f88cd185)
[v5.2.0-beta.2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v5.2.0-beta.2) fixed
