### ISSUE TITLE
干员识别错误

### ISSUE THREAD

**Issue by maidangdang1** [MaaAssistantArknights/MaaAssistantArknights#8605]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

已拥有295名干员，仅识别出187名

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0-beta.2
Core Version: v5.2.0-beta.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14591758/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14591760/gui.log)
2024-03-14 01:53:40.538

### 截图

[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14591828/oper.zip)
[oper1.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14591826/oper1.zip)
图片太多，分开两个上传

### 还有别的吗？

未拥有: 132 名: 

	阿          	锏          	薇薇安娜    	赫德雷      	
	鸿雪        	黑键        	灰烬        	霍尔海雅    	
	银灰        	夜莺        	艾雅法拉    	艾丽妮      	
	莱伊        	迷迭香      	铃兰        	刻俄柏      	
	年          	夕          	黍          	塞雷娅      	
	灵知        	空弦        	棘刺        	安洁莉娜    	
	傀影        	山          	左乐        	斥罪        	
	焰影苇草    	纯烬艾雅法拉	圣约送葬人  	歌蕾蒂娅    	
	陈          	能天使      	焰尾        	菲亚梅塔    	
	归溟幽灵鲨  	百炼嘉维尔  	推进之王    	涤火杰西卡  	
	麒麟R夜刀   	帕拉斯      	琴柳        	提丰        	
	淬羽赫默    	琳琅诗怀雅  	艾拉        	惊蛰        	
	雪绒        	和弦        	寒檀        	奥斯塔      	
	杏仁        	微风        	夏栎        	铎铃        	
	万顷        	慑砂        	雪雉        	冰酿        	
	燧石        	苦艾        	红隼        	医生        	
	海蒂        	蚀清        	稀音        	温米        	
	戴菲恩      	小满        	闪击        	鞭刃        	
	阿米娅      	巫恋        	华法琳      	夜魔        	
	达格达      	耶拉        	临光        	白面鸮      	
	亚叶        	刺玫        	拜松        	特米米      	
	野鬃        	幽灵鲨      	因陀罗      	凛冬        	
	承曦格雷伊  	贝娜        	拉普兰德    	诗怀雅      	
	桑葚        	凛视        	摩根        	折光        	
	薄绿        	灰喉        	图耶        	晓歌        	
	狮蝎        	苍苔        	休谟斯      	罗比菈塔    	
	桃金娘      	深靛        	豆苗        	跃跃        	
	夜烟        	安比尔      	艾丝黛尔    	讯使        	
	铅踝        	缠丸        	石英        	伊桑        	
	维荻        	布丁        	梅          	杜宾        	
	宴          	慕斯        	安德切尔    	斑点        	
	玫兰莎      	泡普卡      	米格鲁      	梓兰        	
	翎羽        	安赛尔      	夜刀        	Castle-3    	
	

已拥有: 187 名: 

	W           	缄默德克萨斯	风笛        	止颂        	
	伊芙利特    	斯卡蒂      	号角        	水月        	
	伺夜        	卡涅利安    	瑕光        	缪尔赛思    	
	玛恩纳      	麦哲伦      	塑心        	仇白        	
	林          	白铁        	赫拉格      	森蚺        	
	早露        	多萝西      	令          	重岳        	
	流明        	泥岩        	伊内丝      	莫斯提马    	
	温蒂        	老鲤        	澄闪        	假日威龙陈  	
	耀骑士临光  	黑          	闪灵        	远牙        	
	异客        	浊心斯卡蒂  	星熊        	凯尔希      	
	史尔特尔    	嵯峨        	煌          	火哨        	
	锡兰        	莱恩哈特    	暴行        	断崖        	
	格拉尼      	吽          	乌有        	贾维        	
	四月        	陨星        	安哲拉      	布洛卡      	
	卡夫卡      	暮落        	暴雨        	双月        	
	见行者      	石棉        	铸铁        	风丸        	
	掠风        	玫拉        	送葬人      	爱丽丝      	
	星极        	子月        	苇草        	空构        	
	谜图        	月禾        	九色鹿      	柏喙        	
	蜜蜡        	格劳克斯    	梅尔        	食铁兽      	
	但书        	海沫        	哈洛德      	埃拉托      	
	真理        	火龙S黑角   	霜华        	德克萨斯    	
	初雪        	洋灰        	极境        	濯尘芙蓉    	
	芙兰卡      	战车        	蜜莓        	隐现        	
	明椒        	普罗旺斯    	炎狱炎熔    	崖心        	
	白金        	罗宾        	截云        	夜半        	
	寒芒克洛丝  	雷蛇        	空          	絮雨        	
	赫默        	天火        	熔泉        	赤冬        	
	车尔尼      	槐琥        	龙舌兰      	洛洛        	
	灰毫        	火神        	守林人      	至简        	
	绮良        	导火索      	羽毛笔      	星源        	
	可颂        	蓝毒        	炎客        	极光        	
	红          	青枳        	深律        	烈夏        	
	松果        	泡泡        	清流        	褐果        	
	罗小黑      	砾          	杰西卡      	嘉维尔      	
	孑          	流星        	猎蜂        	清道夫      	
	蛇屠箱      	深海色      	断罪者      	调香师      	
	地灵        	酸糖        	阿消        	红云        	
	霜叶        	白雪        	角峰        	古米        	
	末药        	暗索        	杰克        	格雷伊      	
	波登可      	坚雷        	卡达        	芳汀        	
	远山        	刻刀        	苏苏洛      	红豆        	
	芙蓉        	克洛丝      	月见夜      	空爆        	
	芬          	香草        	史都华德    	炎熔        	
	卡缇        	12F         	杜林        	巡林者      	
	黑角        	U-Official  	泰拉大陆调查团	Lancet-2    	
	正义骑士号  	Friston-3   	THRM-EX

**Comment by Rbqwow** [comment]
模拟器分辨率和 DPI 是多少

720P 以上的分辨率都有可能识别出错
