### ISSUE TITLE
MAA-cli安装错误，资源下载失败

### ISSUE THREAD

**Issue by FelixTennouji** [MaaAssistantArknights/MaaAssistantArknights#8607]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

资源下载失败

### Version

maa-cli v0.4.2
MaaCore v5.2.0

### 日志文件

-./maa install--force 
Fetching MaaCore version info（channel:stable）...
Downloading MaaCore 5.2.0...
Already downloaded，skip downloading Installing MaaCore...
Extracting archive file...
Done！
正在克隆 '/root/.local/share/maa/MaaResource'..
致命错误：无法访问：'https://git.maa-org.net/MAA/MaaResource.git/'：gnutls_handshake() failed：TLS链接非正常地终止了Error:Failed to clone resource repository

**Comment by wangl-cc** [comment]
MaaAssistantArknights/maa-cli#219，镜像目前在维护，请在 `cli.toml` 里面设置 `resource.remote.url` 为 `https://github.com/MaaAssistantArknights/MaaResource.git`。

**Comment by wangl-cc** [comment]
镜像站已恢复
