### ISSUE TITLE
基建换班 功能无法正常使用   

### ISSUE THREAD

**Issue by lieraaa** [MaaAssistantArknights/MaaAssistantArknights#8622]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

一直停留在 主界面 有时会点进去商城的皮肤界面  有时会点进去抽卡界面  但就是不换班  别的功能都正常  

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.1-alpha.1.d008.g478765a2d
Core Version: v5.2.1-alpha.1.d008.g478765a2d

### 日志文件

[新建 WinRAR ZIP 压缩文件.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14610658/WinRAR.ZIP.zip)

### 截图

![V`G1YSN%)BT%SYP4EZ5C__W](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/93400299/07433a7c-e544-4748-83b0-eaddf99923a1)

### 还有别的吗？

蓝叠5国际版
win10

**Comment by lieraaa** [comment]
有时候可以换班 但是只换了一部分



![3B_%YZP1$7I`N0R3PBHNULG](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/93400299/10bb3a52-1ac9-4001-aa24-e813b9011b9a)
![RA)CUC% 4O${PBK}61VD$76](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/93400299/db577a4b-ae78-4744-a93d-56d954660944)

**Comment by ZJR30** [comment]
我也遇到了，只能手动点进去

**Comment by FroPho** [comment]
确实如此，mac版和win版都遇到了这个问题，就卡在主界面，手动点一下基建然后才能继续下去。

**Comment by hggg666** [comment]
大佬能不能优先修这个bug，这个挺严重的

**Comment by ABA2396** [comment]
用的萨米肉鸽的那个主题？

**Comment by hggg666** [comment]
> 用的萨米肉鸽的那个主题？

主题名叫银凇，不过我印象里之前换这个主题时是可以正常用maa的，好像就是更新到水晶箭活动版本后就不行了，现在我换成那个默认主题就可以正常执行了

**Comment by ABA2396** [comment]
> > 用的萨米肉鸽的那个主题？
> 
> 主题名叫银凇，不过我印象里之前换这个主题时是可以正常用maa的，好像就是更新到水晶箭活动版本后就不行了，现在我换成那个默认主题就可以正常执行了

水晶箭出围城的时候好像是顺带改了银凇的UI透明度，图片匹配不上了

**Comment by hggg666** [comment]
> > > 用萨米肉鸽的那个主题？
> > 
> > 
> > 主题名叫银凇，不过我印象里换这个主题之前时候是可以正常用maa的，希望就是更新到水晶箭活动版本后就不行了，现在我换成那个默认主题就可以正常执行了
> 
> 水晶箭出围城的时候是顺带改了银凇的UI漏洞，图片希望匹配不上

嗷，懂了，那我先换其他主题顶着@lieraaa 楼主可以看看换其他主题行不行

**Comment by ZJR30** [comment]
换了主题确实可以了

**Comment by LiuChip** [comment]
大佬我觉得还是修一下PRTS银凇主题把，感觉还得重新切换回原始的主题才能用基建
