### ISSUE TITLE
萨米肉鸽刷开局预见板子存在bug

### ISSUE THREAD

**Issue by wobushigehanhan** [MaaAssistantArknights/MaaAssistantArknights#8625]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述
第一次用这个。。。不知道你们那边能不能看到我这张图，总之就是，用萨米肉鸽开局刷遇见板子的时候，如果不是指定的板子，它会回退到萨米肉鸽的主界面，但是不会自动“放弃本次探索”，也就导致不能继续自动刷

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

我不到啊，不懂这个

### 截图

![bug](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/163523281/d7516def-9b2d-4485-8031-3ca1c51843dc)

**Comment by status102** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/9f90bb39-2ff6-4dc0-856c-b0fb87e6eec2)

**Comment by Constrat** [comment]
At least he gave us the version...

**Comment by Lancarus** [comment]
有没有可能开局间隔有1分钟
