### ISSUE TITLE
自动战斗页面，水晶箭EX关卡读取文件失败，不支持

### ISSUE THREAD

**Issue by Ricardo-pluto** [MaaAssistantArknights/MaaAssistantArknights#8627]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动战斗水晶箭EX关卡报错：读取文件失败，不支持的关卡，请检查关卡名

### Version

水晶箭行动V5.2.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14616853/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34275852/30155617-7301-4dde-af18-2ad9ac05672c)

**Comment by SherkeyXD** [comment]
现在还有这问题吗 之前是资源热更新出问题了
