### ISSUE TITLE
[EN/Global] OCR not properly recognizing Eyja Alter in Copilot Auto Squad and in Operators list

### ISSUE THREAD

**Issue by ajk992** [MaaAssistantArknights/MaaAssistantArknights#8629]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

OCR scanning doesn't appear to be recognizing Eyja Alter when using the Auto Squad option in Copilot with JSONs from https://prts.plus/ as well as when scanning through the operators list with the Operator option under Toolbox. The list says I don't own her when I do (See screenshots). She appears to be showing up in screenshots in the oper folder (third screenshot in the list). #8605 may also be a similar issue, at least with the Operator scanning.

### Version

Resource Version: Dorothy's Vision - Retrospection
UI Version: v5.2.1-alpha.1.d019.gc686f8e18
Core Version: v5.2.1-alpha.1.d019.gc686f8e18

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14621717/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14621718/gui.log)

Looking at my asst.log file at timestamp [2024-03-15 19:53:02.004], could it be that the OCR isn't properly matching her English name to her Chinese name?
> [2024-03-15 19:53:02.004][TRC][Px8c34][Tx82e4] asst::WordOcr [{ Eyjafjala the Hvit Aska: [ 0, 0, 113, 20 ], score: 0.983965 }] by OCR Rec , cost 10 ms
[2024-03-15 19:53:02.004][TRC][Px8c34][Tx82e4] Proceed [{ Eyjafjalla the Hvít Aska: [ 678, 321, 113, 20 ], score: 0.983965 }]

Compare to a different operator:
> [2024-03-15 19:53:02.015][TRC][Px8c34][Tx82e4] asst::WordOcr [{ Shining: [ 0, 0, 54, 22 ], score: 0.999689 }] by OCR Rec , cost 10 ms
[2024-03-15 19:53:02.016][TRC][Px8c34][Tx82e4] Proceed [{ 闪灵: [ 882, 319, 54, 22 ], score: 0.999689 }]

Copilot error:
> [2024-03-15 19:53:16.291][INF][Px8c34][Tx82e4] Assistant::append_callback | SubTaskError {"class":"asst::BattleFormationTask","details":{"opers":[["纯烬艾雅法拉"]]},"subtask":"BattleFormationTask","taskchain":"Copilot","taskid":1,"uuid":"fcdcd41212341975","why":"OperatorMissing"}

Operator scan starts at timestamp [2024-03-15 20:02:24.981].

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161551584/699c9d98-dd38-4cde-ae3b-554a1008deef)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161551584/db84dfeb-7760-404b-bdc7-51cf1d12c799)
![2024-03-15_20-02-28-579_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161551584/d8909df9-f03a-4718-bf7a-02948284c1a4)

### Anthing else?

MuMu Player 12 at 1920x1080
Windows 10 22H2
Copilot JSON used: maa://28422

**Comment by Constrat** [comment]
Regexing might be a bit off. A week ago I revisited all replaces, to reduce load on MAA, I might've added/removed something for Eyja's
