### ISSUE TITLE
自动肉鸽摆放bug

### ISSUE THREAD

**Issue by helloIris415** [MaaAssistantArknights/MaaAssistantArknights#863]
![image](https://user-images.githubusercontent.com/63986965/173237268-549c8049-7df8-4d96-9124-669fffc70684.png)
如图，酒商运输队会一直拉远程干员去左上角没有放置区域的地方。

**Comment by MistEO** [comment]
附一下日志吧，另外这个问题之前有人提过了 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/730
