### ISSUE TITLE
EN服 萨米肉鸽 Bosky Passage节点卡死

### ISSUE THREAD

**Issue by peter1997546** [MaaAssistantArknights/MaaAssistantArknights#8631]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

EN服 萨米肉鸽 Bosky Passage节点卡死

### Version

Resource Version: Dorothy's Vision - Retrospection
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

大概在3月16日 10:55-11:00之间

[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14622205/log.zip)

### 截图

<img width="365" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/23149848/450cc5d5-584f-4913-888d-b45676dfd60b">

![Screenshot_2024 03 16_11 04 17 168](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/23149848/5f2b6682-9be6-4060-90ec-ef8112a6fec1)

**Comment by Constrat** [comment]
If only we started updating to nightlies before opening useless issues.
This has already been addressed.
