### ISSUE TITLE
日服萨米肉鸽 战斗后密文板奖励二选一卡死

### ISSUE THREAD

**Issue by pocha19** [MaaAssistantArknights/MaaAssistantArknights#8634]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

maa在萨米肉鸽中，战斗结束后如果遇到密文板/干员招募二选一时，会卡住不动，一直不进行任何操作。
这里只有密文板二选一卡死的log，如果遇到干员招募卡死会再上传。

ps：部分不期而遇事件maa无脑选加护盾选项，结果进紧急战斗maa直接结束本次探索，有记录到会上传。

### Version

Core Version: v5.2.1-alpha.1.d023.g531e169a1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14622571/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14622572/gui.log)
13:31:30 战斗完成 13:32左右吧 

### 截图

![com YoStarJP Arknights_Screenshot_2024 03 16_13 44 30](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61786766/f25f8d60-6b34-462a-96d4-0fc1f997bb25)

### 还有别的吗？

模拟器是蓝叠国际版

**Comment by Constrat** [comment]
@pocha19 

> ps：部分不期而遇事件maa无脑选加护盾选项，结果进紧急战斗maa直接结束本次探索，有记录到会上传。

Send it here: 
- #8613
  We have a dedicated issue
