### ISSUE TITLE
EN服 萨米肉鸽 Premonition of Mystery节点卡死 #8631

### ISSUE THREAD

**Issue by peter1997546** [MaaAssistantArknights/MaaAssistantArknights#8635]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

EN服 萨米肉鸽 Premonition of Mystery节点卡死 #8631

### Version

Resource Version: Dorothy's Vision - Retrospection
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

大概在3月16日 15:05-15:14之间

[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14622761/log.zip)

### 截图

![Screenshot_2024 03 16_15 15 34 534](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/23149848/57279485-2849-4de1-8043-79602edb7b1f)

<img width="316" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/23149848/cb34df81-a7d5-4f70-8f34-a8ef94f1a690">

**Comment by Constrat** [comment]
If only we started updating to nightlies before opening useless issues.
This has already been addressed.
