### ISSUE TITLE
保全派驻 循环卡住

### ISSUE THREAD

**Issue by zlqd123** [MaaAssistantArknights/MaaAssistantArknights#8636]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用保全派驻自动作业并选择循环次数时，一轮6关打完之后打下一轮，会卡在选装置的界面，
以前没这个问题

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14623716/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14623717/gui.log)

### 还有别的吗？

MUMU12
官服
win11 23H2

**Comment by Manicsteiner** [comment]
选装置是依赖手动更新的，等更新吧
