### ISSUE TITLE
完成一键长草任务后，随机出现Maa闪退重启

### ISSUE THREAD

**Issue by MomentOnMoon** [MaaAssistantArknights/MaaAssistantArknights#8638]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

Maa在启动并完成一键长草所有任务后，约30秒后有大约50%几率会闪退并立即重启，重启后因为我设置了自动开始任务，会再做一遍日常，这时似乎不会再次出现闪退重启（不会循环发生此问题）。

### Version

UI Version: v5.2.1-alpha.1.d027.g302a82eb6
Core Version: v5.2.1-alpha.1.d027.g302a82eb6
（该问题疑似自5.0版本后就在我的两台PC上均出现，且直至目前最新的稳定版和内测版均还会出现）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14624650/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14624651/gui.log)

### 还有别的吗？

模拟器：Mumu12 最新版
操作系统：Windows11 23H2 系统更新至最新

**Comment by ABA2396** [comment]
勾了自动安装吧？在执行中是不会重启的，会等到任务结束之后重启

**Comment by status102** [comment]
看上去都是计划中的重启
