### ISSUE TITLE
刷图闪退、任务出错

### ISSUE THREAD

**Issue by alon74** [MaaAssistantArknights/MaaAssistantArknights#864]
上次作战出现报错和闪退
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8886199/asst.log)

今天又出错了，MAA设定如下，定位关卡后在理智药界面报错
![image](https://user-images.githubusercontent.com/42845804/173414216-589dbc71-66a2-4a91-af74-6abab1d4816d.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8893347/asst.log)

**Comment by MistEO** [comment]
不支持从吃理智药界面开始任务的

**Comment by MistEO** [comment]
然后我在这个日志里没看到那里闪退了，下次在遇到再帮忙发一下，时间长就被刷掉了_(:з」∠)_

**Comment by alon74** [comment]
> 然后我在这个日志里没看到哪里闪退了，下次在遇到再帮忙发一下，时间长就被刷掉了_(:з」∠)_

现在有个能稳定复现的闪退
![image](https://user-images.githubusercontent.com/42845804/174426167-b7a0516b-f43e-4e48-8c1c-acc4d534cb08.png)
设置勾选是这些
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8933077/asst.bak.log)
点击开始后会跳到游戏终端界面然后卡住，
![image](https://user-images.githubusercontent.com/42845804/174426244-f7c92739-746c-4215-b887-1700760355c0.png)

如果此时手动点击活动界面会尝试重新连接模拟器然后闪退

**Comment by MistEO** [comment]
这个问题新版本已经没有了，更新一下版本吧，测试版的

**Comment by MistEO** [comment]
所以说测试版才是真正的稳定版（bushi，~~什么 MIUI~~

**Comment by alon74** [comment]
> 所以说测试版才是真正的稳定版（bushi，~什么 MIUI~

好的，我升测试版试一下看还有没有问题
