### ISSUE TITLE
肉鸽刷开局支持选择使用的难度

### ISSUE THREAD

**Issue by Hapenia-Lans** [MaaAssistantArknights/MaaAssistantArknights#8646]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前肉鸽刷开局仅能确定使用的分队，默认在最高难度开局。目前不能实现烧完水之后 N12 开之类的操作，只能手动打断然后进入。

### 有什么好的想法？

希望增加一个选择开局难度的功能。

**Comment by status102** [comment]
Duplicate of #6494
