### ISSUE TITLE
繁中服基建換班 濯塵芙蓉辨認異常

### ISSUE THREAD

**Issue by EROTCZ** [MaaAssistantArknights/MaaAssistantArknights#8648]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

03-17 23:15:53 辨認到其他4位  無法辨認濯塵芙蓉
03-17 23:17:45
03-17 23:21:08 好像辨認出 濯塵芙蓉 但是其他4位沒勾選 單人上班

### Version

Resource Version: 愚人號·復刻
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14627925/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14627926/gui.log)

### 截图

![螢幕擷取畫面 2024-03-17 233519](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153876121/4a3b41b4-1737-4cd5-bc54-7fba4dce3eda)

### 还有别的吗？

MuMu Player 12 V3.8.3 (2696)
windows 11

**Comment by EROTCZ** [comment]
後來 看了那夜刀代碼  亂填這串  能辨識到了
                ".*濯.*芙蓉$",
                "“濯尘芙蓉”"
            ],
            [
                ".*塵.*芙蓉$",
                "“濯尘芙蓉”"

**Comment by Constrat** [comment]
Looks like a duplicate string, also after checking the json, there should not be `“` `”`  
It should just be:
```json
            [
                ".*塵.*芙蓉$",
                "濯尘芙蓉"
            ]
```

You can create a PR, so that we can merge it.

**Comment by EROTCZ** [comment]
github 我看不懂 這麼弄項目  
所以修改的事 還是你們弄 我怕給你們添麻煩 謝謝

> Looks like a duplicate string, also after checking the json, there should not be `“` `”` It should just be:
> 
> ```json
>             [
>                 ".*塵.*芙蓉$",
>                 "濯尘芙蓉"
>             ]
> ```
> 
> You can create a PR, so that we can merge it.

**Comment by HsiaoZong** [comment]
我也有遇到類似的問題，但我的是在貿易站，目標是圖耶、鴻雪、但書
他會先找到鴻雪和但書，但找不到圖耶
之後會清除所有勾選的後就找到圖耶，但就只會讓圖耶單人進貿易站而已
請問這要怎麼處理

**Comment by EROTCZ** [comment]
> 我也遇到類似的問題，但我在貿易站，目標是圖耶、鴻雪、但書 他會先找到鴻雪和但書，但找不到圖耶 之後會清除所有勾選的後就找到圖耶，但只是讓圖耶單人進貿易站而已 請問這要怎麼處理

再開新帖  說明狀況/發生時間點/截圖
上傳2個檔案asst.log
跟gui.log
