### ISSUE TITLE
在“启动设置”中添加“每次启动时均使用某一配置”选项

### ISSUE THREAD

**Issue by LinYanxi0** [MaaAssistantArknights/MaaAssistantArknights#8651]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

点上“启动maa后直接运行”及“最小化”后，是以上次关闭时的配置进行运行的
在主配置清日常副配置随缘刷肉鸽的情况下，第一次开启容易忘记所选配置

### 有什么好的想法？

rt，给予“默认以某一配置启动maa”选项，当配置多于一项时成为可选项

**Comment by status102** [comment]
启动时候传参传入要使用的配置
