### ISSUE TITLE
Maa for Mac 理智药文案错误、活动关卡名不在下拉列表

### ISSUE THREAD

**Issue by Ding-Joe** [MaaAssistantArknights/MaaAssistantArknights#8652]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

Maa for Mac 使用理智药的提示信息一直是“已使用理智药1次”（计数是对的，在使用指定次数的理智药后会结束刷理智任务）；
且当次活动关卡名不在下拉选项列表中，需要手动输入（可以正确导航）。

### Version

v5.2.0（472）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14630532/asst.log)

**Comment by ABA2396** [comment]
关卡列表是要从热更服务器拉的，现在 @hguandl 应该在做mac的热更支持

**Comment by status102** [comment]
> 理智药应该是因为 core 传过来的 `MedicineConfirm` 任务的 `exec_times` 永远是 1， 不知道是哪个版本更新之后变得。

之前修改理智药使用按瓶计算时候改掉的，有另外返回使用次数的回调
