### ISSUE TITLE
EN服 无法从主界面进入仓库进行识别

### ISSUE THREAD

**Issue by Argonautes0607** [MaaAssistantArknights/MaaAssistantArknights#8653]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

无法从主界面进入depot，手动点进去后可以正常识别

### Version

v5.2.0（472）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14632455/asst.log)

### 截图

![屏幕快照 2024-03-18 的 15 31 21 下午](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106745133/4e1e9b3a-b962-4782-9581-a1b1d5a4488e)

### 还有别的吗？

Mac mini M1
macOS 14.4

**Comment by ABA2396** [comment]
仓库的匹配得分很低，来张截图看看
cc @hguandl
