### ISSUE TITLE
MAA总是无法连接模拟器

### ISSUE THREAD

**Issue by HAKSALESCA** [MaaAssistantArknights/MaaAssistantArknights#8656]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA无法连接模拟器，重启MAA，电脑，模拟器，替换adb都试过了，换模拟器也没用

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.1-alpha.1.d033.gc3e18d3ee
Core Version: v5.2.1-alpha.1.d033.gc3e18d3ee

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14645257/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14645259/asst.log)

3月19日上午10点半左右

**Comment by status102** [comment]
看起来像#7703

**Comment by WisOcean** [comment]
我也有同样的问题

**Comment by status102** [comment]
@HAKSALESCA 有检查有无安装手机助手类软件吗

**Comment by status102** [comment]
缺少信息
