### ISSUE TITLE
剿灭作战不能使用技能

### ISSUE THREAD

**Issue by astr0mfly** [MaaAssistantArknights/MaaAssistantArknights#8657]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用作业完成剿灭，其中作业中的干员在技能条满时，不能正确使用技能

### Version

Core Version: v5.2.1-alpha.1.d033.gc3e18d3ee

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14645906/asst.zip)

### 截图

![屏幕截图 2024-03-19 133730](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/19238372/6cb5e456-e20d-46c9-875c-b4a05adcc648)

**Comment by ABA2396** [comment]
地图的镜头高度问题，用原来的固定位子点不到技能和撤退，现在在写动态判断点击位置
