### ISSUE TITLE
吃源石超出限定

### ISSUE THREAD

**Issue by Yuanlailai** [MaaAssistantArknights/MaaAssistantArknights#8658]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![f8a76fc2e57074ee8d338de18b7c0df6](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46029173/27844031-7e14-4916-8d67-eae15cb6d1df)
releasev5.2.0

### Version

5.2.0

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14646243/asst.zip)
[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14646246/gui.zip）
2024年3月19日早3点10分左右

**Comment by Yuanlailai** [comment]
[2024-03-19 03:11:30.660][INF][Px3238][Tx4148] asst::Assistant::append_task Fight {"stage":"CR-8","medicine":999,"stone":20,"times":2147483647,"series":1,"report_to_penguin":true,"report_to_yituliu":true,"client_type":"Official","penguin_id":"233841215","DrGrandet":false,"expiring_medicine":9999,"server":"CN"}

stone数实为20

**Comment by Yuanlailai** [comment]
[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14646362/gui.zip)

**Comment by Yuanlailai** [comment]
> ### 在提问之前...
> * [x]  我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
> * [x]  我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
> * [x]  我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
> * [x]  我已检查了置顶议题（pinned issue），确认我的问题未被提及
> 
> ### 问题描述
> ![f8a76fc2e57074ee8d338de18b7c0df6](https://private-user-images.githubusercontent.com/46029173/313941603-27844031-7e14-4916-8d67-eae15cb6d1df.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzAyMzcsIm5iZiI6MTcxMDgyOTkzNywicGF0aCI6Ii80NjAyOTE3My8zMTM5NDE2MDMtMjc4NDQwMzEtN2UxNC00OTE2LThkNjctZWFlMTVjYjZkMWRmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA2MzIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOWNkNDBmZGI5Yzg2OTZiODkwMGU4NzI4OWZhYTlmNzkxOTJlYWYzNTYzYmRkNmI2OWIxMjA0NTY0OTEwNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dpiV0NBzCbHkCDsWv_CZgAr3E4kj_6jJzRXVoUz8Is8) releasev5.2.0
> 
> ### Version
> 5.2.0
> 
> ### 日志文件
> [asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14646243/asst.zip) 
[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14646372/gui.zip)
2024年3月19日早3点10分左右
> 
> ### 截图
> _No response_
> 
> ### 还有别的吗？
> _No response_

**Comment by ABA2396** [comment]
太抽象了
刷理智分为两个关卡，一个是关卡选择，一个是剩余理智，这两个关卡是分别append_task的
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/988cd951-c9e5-43c9-80e9-3e70b7ebc1b2)
这里设置刷理智任务一直失败，失败的原因是剩余理智填了0，这玩意不是一个合法的关卡名，ui给报错拦截了，但core收到了关卡选择的信息并添加了一个append_task
在前面失败的5次任务中实际上是写入了5次花20源石刷CR-8的任务，所以才会有
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/b27954c7-562f-462c-b7aa-c202a2dc1630)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/65443f36-cb55-486a-ae99-1020ad5eae2c)
