### ISSUE TITLE
自动编队经常识别不到山

### ISSUE THREAD

**Issue by NishikiAsumi0** [MaaAssistantArknights/MaaAssistantArknights#8659]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动编队的时候山经常识别不到，反复翻找找不到山

举例：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/58659973/9a8cc8df-b985-49b9-88a3-f5e89bb5c51a)
作业maa://35098
其中“替换”代表山2或推进之王2
但是编队会忽略掉练度更高的山而选用只有精二1级的推进之王
结合之前多次出现的识别不到山，推测是MAA根本没有识别到山而选用的推进之王2
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/58659973/6b932ed9-cec4-4694-82a4-7f61955a454f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/58659973/4303a47e-ea42-4ccf-983a-086af5bb6405)

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14650045/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14650049/gui.log)

**Comment by Radiums** [comment]
类似的问题，识别到无皮肤塞雷亚但是从来不上场

**Comment by Yuanlailai** [comment]
同样的问题，山特别容易出现

**Comment by status102** [comment]
93f34fa fixed
