### ISSUE TITLE
会客室不会自动赠送线索

### ISSUE THREAD

**Issue by SilnaMasiro** [MaaAssistantArknights/MaaAssistantArknights#866]
如果在基建设置中单独选择会客室会进行线索赠送，如果勾选了其他设施（我除了控制中枢都选了）这个时候脚本不会进行线索赠送，尝试过重新下载 但是问题依然存在
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8886328/asst.log)
[gui.json.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8886330/gui.json.txt)

**Comment by ABA2396** [comment]
记得没错的话是满了才会送）

**Comment by MistEO** [comment]
> 会客室仅当自有线索满时，才会送出线索，并且只送三个。有需要的同学可自行修改 resource/tasks.json 中 SelectClue - maxTimes 字段，自定义送出个数。

[详细介绍.md](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md#%E7%89%B9%E6%AE%8A%E8%AF%B4%E6%98%8E)

**Comment by SilnaMasiro** [comment]
> > 会客室仅当自有线索满时，才会送出线索，并且只送三个。有需要的同学可自行修改 resource/tasks.json 中 SelectClue - maxTimes 字段，自定义送出个数。
> 
> [详细介绍.md](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/docs/%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md#%E7%89%B9%E6%AE%8A%E8%AF%B4%E6%98%8E)

我这边是已经全部换班结束去看的时候才发现已经满线索了，而且尝试过重新执行基建换班，但是依然没有赠送线索，设置中只选择会客室时脚本进行了线索赠送，可否修改代码使脚本即使线索未满也能进行赠送呢？

**Comment by MistEO** [comment]
日志重新发一下吧，不要截取的，信息太少了
