### ISSUE TITLE
肉鸽开局刷热水壶时，maa识别不到已经完成任务

### ISSUE THREAD

**Issue by picgca** [MaaAssistantArknights/MaaAssistantArknights#8661]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

策略选了刷热水壶开，确认过没有勾选其他开局条件。在已经刷到热水壶完成任务的情况下，开局出现了热水壶而且maa也自动选取了，却视为没有完成任务，放弃后重新开始刷取。
怀疑是maa没有识别到开局精二导致的，但是我的分队是科学分队，开局干员一栏也是空白的，不可能有精二开。

### Version

UI Version: v5.2.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14651179/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14651181/gui.log)

**Comment by letdawn** [comment]
我观察了观察，感觉maa好像只认热水壶，2希望之类的开局赠品都不认
