### ISSUE TITLE
今天早上自动更新后，无法连接至MUMU模拟器

### ISSUE THREAD

**Issue by Darling-Harker** [MaaAssistantArknights/MaaAssistantArknights#8664]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在其他配置均无变动的情况下，早上MAA进行了自动更新，随后无法连接至模拟器

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14657921/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14657922/gui.log)

**Comment by Hapenia-Lans** [comment]
可复现

**Comment by Hapenia-Lans** [comment]
可能与 MUMU 模拟器的更新有关

**Comment by Hapenia-Lans** [comment]
目前的替代方案是使用强制替换 adb，这可以让 MAA 正常运行

**Comment by Darling-Harker** [comment]
目前已经正常运行，感谢

**Comment by Saratoga-Official** [comment]
能运行就把issue关了，这种简单的连接问题最好加个maa用户群，找人解答就行，用不着提issue
