### ISSUE TITLE
在活动结尾刷理智遇到maa行为异常

### ISSUE THREAD

**Issue by 4573qu** [MaaAssistantArknights/MaaAssistantArknights#8668]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在水晶箭行动最后4个小时我选择了刷理智（碎石 数量50）
由于一些原因我选择了当前/上次而非CR-X
但在活动结束后由于活动关无法进入MAA没有停止工作，反而继续刷取了可访问的上次关卡10-12导致额外碎了好多石
我觉得理论上应该加入一个前后关卡是否一致的判断（又或者添加一个说明，表示该选项可能遇到此情况）

又或者说，即使这个属于我个人操作失误的问题
MAA在转向10-12后也没有检查连续代理，导致每次进入关卡都是连续代理6次，导致挂理智大部分时间（或者更多时间）理智处于溢出状态
即使转向关卡本身不属于maa设计问题，是不是也应该加入这样一个判断？（不然MAA每次作战重设成只代理1次就没意义了吧）

### Version

资源版本：水晶箭行动
UI版本号：v4.28.8（因不明原因5.0的UI版本在较长时间连续代理后会自动崩溃并引发模拟器异常，因此选择了旧版UI，但是并不是本问题出现的原因）
Core版本号：v5.0.0-beta.2

### 日志文件

//因不明原因我无法正确看到要上传哪个文件，故有可能上传错文件，见谅
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14676031/gui.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14676090/asst.bak.log)

**Comment by status102** [comment]
连续代理次数在指定的时候肯定按照指定的来，比较推荐在1-7的时候设置为6次。自适应最大化有考虑做，但是缺乏人手

**Comment by status102** [comment]
如果觉得连续代理6次理智溢出太多，可以改为3次或者更少
