### ISSUE TITLE
繁中服基建換班無法同時放但書、鴻雪、圖耶在貿易站

### ISSUE THREAD

**Issue by HsiaoZong** [MaaAssistantArknights/MaaAssistantArknights#8669]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我原本希望能夠在貿易站編入但書、鴻雪、圖耶
但一開始只能找到但書和鴻雪，找不到圖耶
多次辨識不到後會清空已選擇的幹員(也就是但書和鴻雪)就找到圖耶了
最後就只讓圖耶一個人在貿易站上班

### Version

Resource Version: 孤星
UI Version: v5.2.1-alpha.1.d060.gde43c04f6
Core Version: v5.2.1-alpha.1.d060.gde43c04f6

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14676272/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14676273/gui.log)

### 截图

![擷取](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39250319/62e4a11a-7cf0-4a40-abf7-6b7613eb2d9b)

**Comment by HsiaoZong** [comment]
更準確地說，其實一開始但書、鴻雪、圖耶三個人maa都找的到，但是它會將圖耶取消選取重新找

**Comment by HsiaoZong** [comment]
我觀察了一下asst.log，我發現MAA有可能把圖耶辨識成固耶，我在想是不是這個原因
![擷取](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39250319/9ebe4afd-c692-42e3-b339-c786b05077d6)

**Comment by HsiaoZong** [comment]
我暫時在task.json中添加了一新的判斷，目前就沒有問題了，我會再觀察一陣子會不會有問題
![圖耶](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39250319/cbd81b39-605b-4b96-a574-b27259410049)

**Comment by Constrat** [comment]
If the changes you added are stable and working. Open a PR
