### ISSUE TITLE
繁中（台服）获取信用及购物时无法访问好友基建问题

### ISSUE THREAD

**Issue by Htwos** [MaaAssistantArknights/MaaAssistantArknights#8672]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

繁中服在日常执行获取信用及购物任务时无法正常点击进入好友基建，会自主点击进入好友列表但是仅在列表发呆，发呆一会会自动进行之后的任务。

### Version

Resource Version: 孤星 
UI Version: v5.2.0 
Core Version: v5.2.0

### 日志文件

暂无

**Comment by Constrat** [comment]
Fym no logs...
No logs, no help.

**Comment by Htwos** [comment]
> Fym no logs... No logs, no help.

shit off alright? I just simply listed out the problem.

**Comment by Htwos** [comment]
> Fym no logs... No logs, no help.

if you just can't fix this, shut up ur ass

**Comment by Constrat** [comment]
Opening issues without logs is as useless as listing them. 
Without log there's no way of knowing what went wrong.
