### ISSUE TITLE
信用购买卡在购买完成界面

### ISSUE THREAD

**Issue by Deo-777** [MaaAssistantArknights/MaaAssistantArknights#8674]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，虽然观测到的三次卡顿都是卡在了招聘许可的购买完成界面，但是我发现卡在这之后还会直接跳过任务队列里的其他任务。
个人建议1.检查是不是确实因为招聘许可所以卡住，2.卡在其他界面是否需要识别界面或跳出卡顿的功能，3.给卡顿增加一个可开关的按钮，开启后，所有需要响应的节点增加额外响应时长的期望。
祝您生活愉快。

### Version

UI Version: v5.2.0
Core Version: v5.2.0
Resource Version: 源石尘行动·复刻

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14695042/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14695044/gui.log)

### 还有别的吗？

谢谢大家的辛苦付出，祝大家身体健康！

**Comment by ABA2396** [comment]
在debug\other\下应该有截图，看看卡哪儿了

**Comment by Deo-777** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/60177926/93b8c81d-032b-4af8-abf5-3a3d432290c2)
近七成的图都卡在了招聘许可这里

**Comment by ABA2396** [comment]
来张截图，你这个CreditShop-Bought没匹配上
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/02a9d8b0-770a-4a7c-861b-6fc38c3132d2)
把这个文件夹打包下发上来

**Comment by Deo-777** [comment]
[template.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14787504/template.zip)
有CreditShop-Bought这个文件，不清楚您说的是什么
[other.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14787526/other.zip)

**Comment by ABA2396** [comment]
cc @status102 不知道为啥他这个CreditShop-Bought的得分特别低，连分数都没显示
