### ISSUE TITLE
补充低信赖干员会补充满信赖干员

### ISSUE THREAD

**Issue by BX2333** [MaaAssistantArknights/MaaAssistantArknights#8676]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

补充低信赖干员会补充满信赖干员

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14704285/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14704286/gui.log)

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87287646/fbcf86e5-800d-4f08-a300-3f8825295ba2

### 还有别的吗？

mumu12模拟器 之前都好好的就突然有一天就这样了，内测版稳定版都这样，重新下载也没用

**Comment by status102** [comment]
特关置顶导致，等有空了给加个关掉置顶的步骤

**Comment by status102** [comment]
634117c fixed
