### ISSUE TITLE
资源版本更新到源石尘复刻以后一键长草无法选择复刻关卡

### ISSUE THREAD

**Issue by Yumeow** [MaaAssistantArknights/MaaAssistantArknights#8677]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新资源版本以后，自动战斗可以识别复刻关卡，但是一键长草页面不能选择复刻关卡
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115551020/dc4c3c32-747d-41e1-838f-b3a26b7c8b1f)

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.1-alpha.1.d066.g99e53443c
Core Version: v5.2.1-alpha.1.d066.g99e53443c

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14715714/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14715716/gui.log)
时间为2024-03-22 09：00左右

**Comment by starrin** [comment]
maa还没适配源石尘行动的导航，先手打吧

**Comment by status102** [comment]
这不是一个bug，等待支持
