### ISSUE TITLE
繁中服無法自動訪問好友獲取信用

### ISSUE THREAD

**Issue by HsiaoZong** [MaaAssistantArknights/MaaAssistantArknights#8678]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用獲取信用及購物中的訪問好友功能時，他會停在好友列表一陣子沒反應，之後就離開好友列表去商店購物。
前陣子這個功能還正常，都能正常訪問好友取得信用，但最近都沒反應

### Version

Resource Version: 孤星
UI Version: v5.2.1-alpha.1.d066.g99e53443c
Core Version: v5.2.1-alpha.1.d066.g99e53443c

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14716922/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14716923/asst.log)

**Comment by Manicsteiner** [comment]
大概还是UI调整的影响，像这样加上StartToVisit试试 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/3e3c2450c80631720ee7d1ad21d2fdadd8a04748

**Comment by HsiaoZong** [comment]
感謝幫忙，這樣改動後的確能夠正常執行任務了\
