### ISSUE TITLE
刷肉鸽经常卡在技能释放界面

### ISSUE THREAD

**Issue by Gdorom** [MaaAssistantArknights/MaaAssistantArknights#868]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8888098/asst.zip)
![bug](https://user-images.githubusercontent.com/41352516/173285551-1e5e3dbe-fe6d-4bdf-9566-c4d9efc95760.png)

肉鸽每次打到这里（与虫为伴）都会点法术干员的技能然后卡进时停，还有另外一张图也有bug但是没接上图，遇到了之后我再贴出来。

**Comment by Gdorom** [comment]
![image](https://user-images.githubusercontent.com/41352516/173415739-3568419f-7e50-4a7d-9b06-029bece59e26.png)
棘刺也会有相同的问题
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8893384/asst.zip)

**Comment by MistEO** [comment]
> ![image](https://user-images.githubusercontent.com/41352516/173415739-3568419f-7e50-4a7d-9b06-029bece59e26.png) 棘刺也会有相同的问题 [asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8893384/asst.zip)

你这个压缩包是空的 orz

**Comment by MistEO** [comment]
肉鸽的那个，下次遇到的话再帮忙发一下日志吧

**Comment by MistEO** [comment]
v3.9.9-beta.1 修了自动战斗不放技能的问题，如果更新后没遇到就不用试了

肉鸽那个没修，还不知道是啥问题
