### ISSUE TITLE
自动战斗-补充低信赖干员出错

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#8683]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动战斗-自动编队-补充低信赖干员时不能正确补充。详见视频
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/7d982484-084e-4946-aa31-81d26aefab40

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.1-alpha.1.d074.g558f35e39
Core Version: v5.2.1-alpha.1.d074.g558f35e39

### 日志文件

[asst - 副本.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14723423/asst.-.log)

**Comment by PercyDan54** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/634117 的后遗症
在resource/task.json加回clickself能解决
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/50285552/76b12c4d-e7b9-4c0f-85e5-457c78ec5421)

**Comment by status102** [comment]
303162ed fixed
