### ISSUE TITLE
自动战斗将闪击识别成煌

### ISSUE THREAD

**Issue by YTH-ao** [MaaAssistantArknights/MaaAssistantArknights#8684]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动战斗自动编队中添加低信赖时添加的是高信赖成员（注：选择信赖选项卡时少点了一下）
自动战斗将闪击识别成煌（队伍中自动战斗中本该放下煌的操作，却会放下一个闪击）

### Version

Core Version: v5.2.1-alpha.1.d074.g558f35e39

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14725267/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14725271/gui.log)
凌晨十二点左右

**Comment by status102** [comment]
检查一下cache/avatar文件夹中煌的头像

**Comment by status102** [comment]
信赖duplicate of #8683

**Comment by YTH-ao** [comment]
确实是文件夹中煌头像出错了，删除后已经正常运行了，辛苦了
