### ISSUE TITLE
使用MAA自动肉鸽挂水月卡界面

### ISSUE THREAD

**Issue by 247999728** [MaaAssistantArknights/MaaAssistantArknights#8689]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在使用MAA挂机水月肉鸽时候 每次打到第二第三层最后的紧急关或者BOSS关就会卡在查看地图的界面 
前面已经把傀影跟萨米都挂满了没有出现这种问题 

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.1-alpha.1.d074.g558f35e39
Core Version: v5.2.1-alpha.1.d074.g558f35e39

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14730186/debug.zip)

### 截图

![20240323120232](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/68092096/f1c65eae-fa66-44b8-8570-7acf31c793c7)
这里的地图是我自己打开的  刚看到的时候点掉MAA才继续操作

### 还有别的吗？

雷电9

**Comment by 247999728** [comment]
就是在3点左右开始挂 起来就发现一直卡在地图那 点掉就继续操作了
不是第一次卡 好多次都是他打到这个进度就卡在那里

**Comment by yrssy** [comment]
我也是这样，现在我挂机都是用刷源石碇那个，到第二层退出

**Comment by aliuhau** [comment]
我也是，雷电9

**Comment by ALINGCAT** [comment]
MuMu也出现了这个问题 本该进入距离boss的前一个节点的战斗格 但是maa会选中boss格然后卡在boss格的地图预览

**Comment by Yuanlailai** [comment]
水月3层boss关很容易点开地图，然后卡着不动了
