### ISSUE TITLE
MAA打不开，完全没反应

### ISSUE THREAD

**Issue by NoxGoBo** [MaaAssistantArknights/MaaAssistantArknights#8690]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA突然打不开了，点exe文件完全没反应，什么窗口都没弹，后台也没有进程，尝试了重装公测版和内测版都一样打不开，老版本也打不开。要求的.Net是安装了的，前一天还没问题第二天突然就不行了。

### Version

[v5.2.0]

### 日志文件

卸载重装之后一次没有启动成功过，没有debug文件夹

**Comment by ABA2396** [comment]
有没有单独把exe拖到桌面之类的操作

**Comment by status102** [comment]
incomplete
