### ISSUE TITLE
在内存较小的设备启动闪退报错

### ISSUE THREAD

**Issue by yang932** [MaaAssistantArknights/MaaAssistantArknights#8692]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在启动时，任务栏会出现maa图标，鼠标划过后立即消失，后报错“maa已停止工作”，该bug存在于4.28.3至5.2.1之间的所有版本，在5.2.1中异常代码为c000001d，而4.28.3中错误代码无法识别

### Version

4.28.3至今

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14730570/debug.zip)

**Comment by ABA2396** [comment]
日志里没看出来啥东西，4.28.3的报错是你没装.net48，但现在到了5.x的版本了也不用管.net48了
5.2.1的日志里没有报错信息，重新触发下然后发个日志，然后给报错的界面截个图看看

**Comment by yang932** [comment]
[Desktop.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14804199/Desktop.zip)
测试环境为新装的Windows8.1，但其在Windows10上仍会出现（因为就因为报错我才换回来Windows8.1的），但Windows10不会出现弹窗（可能是因为我之前禁用了Windows诊断的缘故），另外启动时CPU与硬盘占用率会突升，然后在数秒后迅速回落并从任务管理器中消失（闪退了），但同时Windows问题报告的占用率会迅速攀升至MAA崩溃前水平并保持至关闭报错弹窗

**Comment by yang932** [comment]
另外4.x装了net48也一样报错

**Comment by yang932** [comment]
补充，把资源文件删除后（或者说将resource中的config.json）删除后便能进入程序（虽然资源文件删除后提示重新下载且无法正常使用），但退出后仍会报错
![捕获](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35618570/5ad14166-4320-454b-bd5a-6bc8dedceba4)
![捕获2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35618570/30586d3c-7a74-48eb-befa-564252665997)
