### ISSUE TITLE
自动编队无法识别到能天使

### ISSUE THREAD

**Issue by NanNing00** [MaaAssistantArknights/MaaAssistantArknights#8693]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

box里存在能天使，maa无法识别到并编入队伍，除能天使外的其他干员正常识别

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.1-alpha.1.d079.g006201d12
Core Version: v5.2.1-alpha.1.d079.g006201d12

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14730765/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14730766/gui.log)
2024.3.23 15:30-16:20

### 截图

![Screenshot_20240323-161344](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131198104/95437834-46b4-40e3-b071-4cecba2316a3)
![4BBC73E6AAA1AC67A440DA3DF183F741](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131198104/28a1fb79-07d1-4ce7-8674-082fa510f3df)

### 还有别的吗？

模拟器：mumu12；雷电9
系统：Windows 11 23H2 22631.3296 家庭中文版
CPU:intel i7-11800H
显卡：NVIDIA RTX 3060 Laptop
内存：16GB

**Comment by status102** [comment]
030b3f7 fixed
