### ISSUE TITLE
自动战斗无法使用战斗列表自动刷图，会程序闪退

### ISSUE THREAD

**Issue by silveryoung830** [MaaAssistantArknights/MaaAssistantArknights#8700]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

录入多个战斗关卡链接后，点击开始，程序卡在连接模拟器步骤，大概5-8秒后程序闪退

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.1-alpha.1.d083.g030b3f718
Core Version: v5.2.1-alpha.1.d083.g030b3f718

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14734475/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14734476/gui.log)
点击开始战斗后的5-8秒

**Comment by ABA2396** [comment]
两个日志时间都没对上
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/3e05610e-ce4c-4260-ae40-56527fbe1ab7)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/29a2db4c-899e-430a-bd61-3a3386aceacd)
日志距离遇到闪退的时间太久了被刷掉了

**Comment by status102** [comment]
incomplete
