### ISSUE TITLE
繁中服(twxy)幹員選定問題

### ISSUE THREAD

**Issue by Messiahtw** [MaaAssistantArknights/MaaAssistantArknights#8702]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

於基建排班功能無法選中幹員謬爾賽思，幹員編成部分尚未測試，但研判應為無法成功識別

[2024-03-24 16:42:53.912] <1><> 首選幹員: 焰尾, 灵知, 玛恩纳, 银灰, 缪尔赛思
[2024-03-24 16:51:08.471] <1><> 首選幹員: 缪尔赛思

### Version

Resource Version: 孤星
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14734915/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14734916/gui.log)

### 截图

<img width="136" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30199348/555546f5-338b-455a-b3bc-9b70096d9883">

### 还有别的吗？

Windows 11 23H2
BS國際板5.21.0.1043 P64

**Comment by Messiahtw** [comment]
已知 霍爾海雅 繆爾賽思 明椒 三位幹員無法識別

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30199348/20d8dcb4-8ea1-45b7-bb37-b7cba086c038)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14734968/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14734969/gui.log)

**Comment by ABA2396** [comment]
这几个是2024-03-19更新之后加上的，在maa获取更新之后还是不能识别吗

**Comment by EROTCZ** [comment]
> 這幾個是2024-03-19更新之後加上的，在maa獲取更新之後還是不能辨識嗎

我沒霍爾海雅    剛用繆爾賽思/明椒 測試基建 辨識不到

然後說到更新 這陣子繁中服 啟動MAA 沒顯示任何更新 提醒  [頂多就彈出關卡數據更新而已]

不知道是不是這個原因?
點檢查更新 也只顯示 已最新版

我看電腦中的MAA  resource\global\txwy\resource\tasks.json
比對後 缺少霍爾海雅/繆爾賽思/明椒

github的tasks.json  有看到霍爾海雅/繆爾賽思    但沒看到明椒

**Comment by Messiahtw** [comment]
5/11 
幹員明椒依舊無法識別
霍爾海雅及繆爾賽思已可正常識別
