### ISSUE TITLE
萨米肉鸽刷源石锭 作战结束后不会拿取掉落的源石锭

### ISSUE THREAD

**Issue by AgCl-cdqz** [MaaAssistantArknights/MaaAssistantArknights#8704]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如截图所示，完成作战后不会拿取掉落的源石锭，而是选择直接离开

### Version

Resource Version: 水晶箭行动
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14737763/debug.zip)

### 截图

![Screenshot_2024 03 25_09 38 59 511](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110602463/c91082df-e994-4fb8-be47-1992c9f50bfe)

**Comment by status102** [comment]
预期行为，绝大部分情况下都用不完开局带的钱
