### ISSUE TITLE
Using maatouch

### ISSUE THREAD

**Issue by tingfengwanxiao** [MaaAssistantArknights/MaaAssistantArknights#8706]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49578058/24f002d1-1a0d-4766-ba36-a3af80c39098)
Hello,when I use maatouch by this command , It seems no error ,but my phone not light or click or swipe,How can I do ?

**Comment by ABA2396** [comment]
Higher versions of android might not be able to use this? Maybe you can only use adb input on a physical machine, but then it's more recommended to use an emulator, because adb input is really slow
