### ISSUE TITLE
萨米肉鸽，得偿所愿节点拾取收藏品卡死

### ISSUE THREAD

**Issue by yltx** [MaaAssistantArknights/MaaAssistantArknights#8708]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽中，如果抗干扰降成0，则在得偿所愿中只能选择第一个收藏品。而MAA的逻辑似乎是至少选择第二个，所以依旧会卡死。

### Version

UI Version: v5.2.1-alpha.1.d083.g030b3f718
Core Version: v5.2.1-alpha.1.d083.g030b3f718
Resource Version: 源石尘行动·复刻

### 日志文件

[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14742106/gui.zip)

### 截图

![QQ截图20240325181715](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/37734213/9a0d65fd-179c-4224-8b95-cc84f867dc32)
![QQ图片20240325181912](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/37734213/2cbf18c7-8d01-4823-99c5-bf4e4ff6559f)

### 还有别的吗？

mumu12
windows 11

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/60bcacfe-443c-4a9f-ae25-f5be1bf00407)
有改过配置文件吗？照理来说只有抗干扰>1的时候才会选第二个，看日志是识别到了0但还是选了第二个
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/67a8fec6-eeb4-4177-870c-42721e61bf67)

**Comment by yltx** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/317663221-60bcacfe-443c-4a9f-ae25-f5be1bf00407.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTQ3NTIsIm5iZiI6MTcxMTcxNDQ1MiwicGF0aCI6Ii85OTA3Mjk3NS8zMTc2NjMyMjEtNjBiY2FjZmUtNDQzYy00YTlmLWFlMjUtZjViZTFiZjAwNDA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDEyMTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZjU5MWQxOTJkZDkwMGQ1ZTE0MmJjZjFhNGE0ODA0ZmI4ZWMyNzhiNmNmNGU3YWNiZjYyMWQwZjQ3YjljMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EGxFij3o7WnZnxIA2M-BBPsTXKAH8S0PKPqnGPLFLeE) 有改过配置文件吗？照理来说只有抗干扰>1的时候才会选第二个，看日志是识别到了0但还是选了第二个 ![image](https://private-user-images.githubusercontent.com/99072975/317663680-67a8fec6-eeb4-4177-870c-42721e61bf67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTQ3NTIsIm5iZiI6MTcxMTcxNDQ1MiwicGF0aCI6Ii85OTA3Mjk3NS8zMTc2NjM2ODAtNjdhOGZlYzYtZWViNC00MTc3LTg3MGMtNDI3MjFlNjFiZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDEyMTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NmNkZDcyNDhhNjFhM2NkZjlkYmIzMTMwZjMxMzM1YzczNTllYjE3ZTVjYjYwNTQ2YzMyNmNiODUzMzAzMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XOYhcHT679ss_VatR8JUKhYKtYZHD1JDIwwm2-eqKCg)

没改过，我都压根不会改啊
