### ISSUE TITLE
IS4 Stuck at encounter choice

### ISSUE THREAD

**Issue by sinyovercosy** [MaaAssistantArknights/MaaAssistantArknights#8709]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

Whenever MAA reaches the "It's black rain..." event it is unable to progress further. In the log it seems that it have OCR'd the first choice but not sure what went wrong afterwards.

### Version

Resource Version: Come Catastrophes or Wakes of Vultures
UI Version: v5.2.1-alpha.1.d083.g030b3f718
Core Version: v5.2.1-alpha.1.d083.g030b3f718

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14746829/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14746830/gui.log)

### Screenshots

![MuMu20240325122839](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/24600407/e87bfd54-f65b-4668-af80-5290ce948f8c)

**Comment by HX3N** [comment]
```log
[2024-03-25 12:24:56.549][TRC][Px970][Tx0cf4] asst::WordOcr [{ Rain!<e: [ 113, 93, 73, 23 ], score: 0.783034 }, { 'It's black rain..: [ 114, 126, 105, 19 ], score: 0.903382 }, { 'We just finished harvesting a few samples' the man says in a numb voice,'but now both: [ 115, 146, 607, 19 ], score: 0.937258 }, { samples and eguipment are destroved, and my people have run away... What do I do abo: [ 115, 171, 608, 14 ], score: 0.931225 }, { money I owe the company?: [ 111, 187, 195, 22 ], score: 0.950031 }] by OCR Pipeline , cost 7198 ms
[2024-03-25 12:24:56.564][TRC][Px970][Tx0cf4] Proceed []
[2024-03-25 12:24:56.565][INF][Px970][Tx0cf4] Unknown Event
```

The garbage values at the end seem to be the cause of the recognition issue.

**Comment by Constrat** [comment]
The issues seems to be the `e`. I ocr only the `<`

**Comment by sinyovercosy** [comment]
Thanks for the quick fix! What's the protocol for cutting a new tag with the fix in an alpha release?

**Comment by Constrat** [comment]
Sorry about the delay.
The new nightly release is already up. 
[alpha/v5.2.1-alpha.1.d088.g6b289e9c9](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/alpha%2Fv5.2.1-alpha.1.d088.g6b289e9c9)
