### ISSUE TITLE
自动肉鸽无法使用

### ISSUE THREAD

**Issue by Lihuayy** [MaaAssistantArknights/MaaAssistantArknights#8710]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在5.2.0版本中自动肉鸽任务启动后无法正常进入肉鸽，使用mumu12模拟器

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14751974/gui.log)
进行自动肉鸽时会卡住不动，一会会重新尝试导航，但还是无法进入

### 还有别的吗？

使用mumu12模拟器

**Comment by ABA2396** [comment]
#8248
