### ISSUE TITLE
开始唤醒模块，添加一个自动选择最后一个账号登录的功能。

### ISSUE THREAD

**Issue by zlq193852347** [MaaAssistantArknights/MaaAssistantArknights#8711]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

我希望添加一个功能，就是每次打开游戏，他都是自动打开账号列表点击最后一个账号进行游戏，可以选择开启这个功能和关闭这个功能，这个功能需要考虑，最后一个账号是否已经过期了，不能登录了，这个时候任务不要停止开始试图尝试倒数第二个账号，一次类推，如果都是失败的那就弹窗提示，如何结束这次任务。本人长期两个号互相切换有点麻烦，这边你看看能不能解决一下这个痛点。

**Comment by status102** [comment]
两个号长期切可以考虑做两份配置，配置里写上对应的账号即可

**Comment by zlq193852347** [comment]
> 两个号长期切可以考虑做两份配置，配置里写上对应的账号即可

这个配置在哪里设置？

**Comment by status102** [comment]
设置最上面就是
