### ISSUE TITLE
开始唤醒选择切换账号后自动代理功能失败

### ISSUE THREAD

**Issue by jeffzhou315** [MaaAssistantArknights/MaaAssistantArknights#8712]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

开始唤醒中选择“账号切换”（电话号码切换）后自动代理导航至剿灭，关闭账号切换功能后恢复正常

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

时间节点：最新
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14758209/asst.log)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/0d733f1a-48e6-4f2a-95fd-eb4e5c9c352a)

**Comment by jeffzhou315** [comment]
最新复现，在另一台设备上测试没问题，这台的MAA是由4.23.3升至5.2.0的，测试没问题的是由4.27.0升至5.2.0
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14785778/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14785780/asst.log)

**Comment by ABA2396** [comment]
怎么感觉是因为模拟器很卡造成的
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/bbee3b3e-d420-4d66-b8d3-994128554a93)
过程是这样的：
识别到终端并点击->等待3s->又识别到了终端并点击->等待3秒
但在点第二次的时候已经进到了终端页面，再点就是右上角的剿灭了
要么是刚好在识别到终端并点击的瞬间进去了，要么是模拟器卡了给了张之前的图
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/ed9b87a3-41c3-482e-a86f-e0f661865c8c)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/8b921517-cea0-43d2-861f-0891344c7485)

cc @status102

**Comment by jeffzhou315** [comment]
但是我测试过很多遍，五个账号，五个MAA（都是4.23.3升级到5.2的）分别都测过几次，都有这个问题，我试试换个设备，当时看模拟器的延迟也不是很高，我拿采集卡录制试试

**Comment by jeffzhou315** [comment]
5.2.0直接下载的是没问题的

**Comment by jeffzhou315** [comment]
但是我关了切换账号这个功能之后又恢复正常了

**Comment by status102** [comment]
太奇怪了，想要一份带触摸位置显示的故障录像
