### ISSUE TITLE
如果游戏启动时间过长，会导致StartUp任务失败

### ISSUE THREAD

**Issue by OJuis** [MaaAssistantArknights/MaaAssistantArknights#8713]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

本人使用MuMu模拟器，点开游戏后由于电脑性能问题进入游戏启动页面过慢，MAA直接显示StartUp任务失败，并直接开始下一个任务

### 有什么好的想法？

我认为期望的结果应该是，或说改进后的结果可以是：
-  让用户决定启动时的等待界面时间
-  在识别失败后应该进行更多次的识别，并且通过通知询问用户是否继续
-  如果截屏识别到已经进入游戏，就可以跳过StartUp任务并且直接开始下一任务而非报错

**Comment by status102** [comment]
可以让MAA自己启动模拟器，那个功能可以设置启动后等待
