### ISSUE TITLE
繁中服 訪問好友信用 沒反應

### ISSUE THREAD

**Issue by EROTCZ** [MaaAssistantArknights/MaaAssistantArknights#8718]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在B站看到了 來上傳log 
18:57:18 開始任務
後會停在 好友列表 完全沒反應
然後直接去信用商店領信用

### Version

Resource Version: 孤星
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14788114/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14788120/gui.log)

### 截图

![螢幕擷取畫面 2024-03-28 185755](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153876121/93d8e8aa-5692-4c59-8779-aa070384bdfe)

### 还有别的吗？

win 11
mumu模擬器 V3.8.3 (2696)

**Comment by ABA2396** [comment]
#8682 fixed
first appeared in [alpha/v5.2.1-alpha.1.d074.g558f35e39](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/alpha/v5.2.1-alpha.1.d074.g558f35e39)
等下发个公测版
