### ISSUE TITLE
萨米肉鸽增加前两层刷隐藏坍缩功能

### ISSUE THREAD

**Issue by Jovyyyyy** [MaaAssistantArknights/MaaAssistantArknights#8721]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

隐藏坍缩手刷太困难

### 有什么好的想法？

难度3指挥分队开局，锏1技能普通关晚部署轻松漏1，前两层打完检测到隐藏坍缩就停止等待手刷，没检测到就退出重开

**Comment by Saratoga-Official** [comment]
#9172 已增加
