### ISSUE TITLE
기반시설 맨 왼쪽 위 오퍼레이터 미인식 문제

### ISSUE THREAD

**Issue by xczsonn** [MaaAssistantArknights/MaaAssistantArknights#8722]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

2달 정도 돌렸는데 익게이가 이미 제조소에 있는데 다시 익게이를 선택하는 부분에서 인식이 안 되는듯 정확히는, 익게이가 맨 왼쪽 위 위치에 있을 때 인식을 건너뜀

제조소에 익게이가 1번슬롯에 있고 그 외의 오퍼 2명 조합이 이미 들어가 있을 때 : 익게이 인식을 건너뛰고 나머지 2명 오퍼를 찾고 무한 왼쪽 스와이핑을 하다가 갑자기 익게이 빼고 다 쫓아냄 [https://gofile.io/d/XhMQez](https://oo.pe/https://gofile.io/d/XhMQez)

위 이유로 제조소에 익게이가 1번 슬롯에 혼자만 들어가 있을 때 : 익게이 인식 못하고 나머지 둘만 인식 후 무한 왼쪽 스와이핑 [https://gofile.io/d/XxoWGE](https://oo.pe/https://gofile.io/d/XxoWGE)

### Version

5.2.0

### 日志文件

로그 본문 포함

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12751277/4d669569-5870-44ee-8a2a-d8bf5025a653)

### 还有别的吗？

1280x720 dpi 320

**Comment by ABA2396** [comment]
cc @HX3N 
Can you please take a look at the ocr issue, at line 2596 of asst.log
[2024-03-28 15:52:05.246][TRC][Px28ac][Tx244c] asst::WordOcr [{ 미그페루터디텍스포메데리: [ 0, 0, 113, 9 ], score: 0.837720 }] by OCR Rec , cost 32 ms
[2024-03-28 15:52:05.252][TRC][Px28ac][Tx244c] Proceed [{ 미그페루터디텍스포메데리: [ 8, 6, 113, 9 ], score: 0.837720 }]

**Comment by HX3N** [comment]
It's only the OCR recognition that's the issue, right...? (I'm not familiar with the custom infrast feature, so)

It seems like the regex would work properly if modified as follows.
```(.+그.+큐터.+|.*스포.+데레)``` > ```(.+그.+큐터.+|.*스포.+데.+)```

by the way, recognition is really weird :P

**Comment by ABA2396** [comment]
It still doesn't seem to work, the fourth one recognizes `루` instead of `큐` It feels like the name is too long and the characters are too small and the recognition rate is plummeting

**Comment by HX3N** [comment]
It seems like it's not the alpha version, right? Jessica should be recognized.


Eyjafjalla the Hvít Aska & Executor the Ex Foedere will now be recognized properly.

<details><summary> change </summary>

```json
            [
                "(.+그.+큐터.+|.*스포.+데.+)",
                "이그제큐터디엑스포에데레"
            ],
            [
                "이그제큐터디엑스포에데레",
                "圣约送葬人"
            ],
```

```json
            [
                "(.+야.+라더.+|.*퍄.+라.+|.+크비트.+|^더카.+$)",
                "에이야퍄들라더크비트아스카"
            ],
            [
                "에이야퍄들라더크비트아스카",
                "纯烬艾雅法拉"
            ],
```

</details>

<details><summary>regex test</summary>

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/128385247/528d3718-b9a7-413a-bb13-5a2c1f50f8d4)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/128385247/038804a0-f705-432f-b9c2-5fd526912767)

</details>
