### ISSUE TITLE
模拟器关闭失败

### ISSUE THREAD

**Issue by konglenghui** [MaaAssistantArknights/MaaAssistantArknights#8724]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

模拟器关闭失败 最近偶尔发生模拟器关不掉的情况 maa红字提示模拟器关闭失败

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.1-beta.1
Core Version: v5.2.1-beta.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14797598/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14797599/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62045233/e438072c-bd89-455d-a21f-0449ecb83f7c)

### 还有别的吗？

模拟器是蓝叠国际版 安卓11 
操作系统 win11

**Comment by Daydreamer114** [comment]
你的asst.log有点短，到七点四十八就结束了，麻烦找找有没有包含了八点五十三的版本

**Comment by ABA2396** [comment]
日志只到[2024-03-29 07:48:48.355]
不过关模拟器和core无关，只要gui.log就行了
