### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by Johnnylov** [MaaAssistantArknights/MaaAssistantArknights#8726]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
Object reference not set to an instance of an object.
解决方案
出现未知错误
详细信息
System.NullReferenceException: Object reference not set to an instance of an object.
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.LinkStart()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

UI Version: v5.2.1-beta.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14798542/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14798543/gui.log)

**Comment by ABA2396** [comment]
没太看懂是咋触发的，是打开就报错还是点了开始报错

**Comment by Johnnylov** [comment]
点了开始然后报错

**Comment by Johnnylov** [comment]
已解决 用过MAA_win7.exe启动开始后，MAA.exe启动开始会报错，但使用MAA_win7.exe开始不会报错，同时MAA.exe界面出现问题，也启动不了
![屏幕截图 2024-03-29 105607](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87256842/5b4e5f52-f8fd-43c4-b182-5ad75412bb24)

**Comment by status102** [comment]
试试删一下config文件夹再启动MAA.exe，不推荐使用同一份配置文件混用新版和旧版maa

**Comment by Johnnylov** [comment]
删除config文件夹，再启动MAA.exe，成功运行

**Comment by ABA2396** [comment]
_win7还是4.28的版本，能开5.x就不用留着win7了
