### ISSUE TITLE
Discussion on the timeliness and availability of multi-language localization of the documentation site

### ISSUE THREAD

**Issue by Cryolitia** [MaaAssistantArknights/MaaAssistantArknights#8734]
### 说说你遇到的问题？

目前 MAA 的文档站 https://maa.plus/docs/ 提供了多种语言的文档，包括简体中文、繁体中文、英文、日文、韩文。

在本issue中，我们称简体中文、英文为通用语言，繁体中文、日文、韩文为少数语言。<sub>这种分类是基于世界上的语言使用者数量，MAA团队的人员构成，为方便本issue讨论而做出的，并不暗含和假定任何褒贬色彩。我们始终对多元文化持开放包容态度，并欢迎所有语言的使用者使用和加入建设我们的产品。</sub>

已知问题：

- 少数语言的文档站可能且正在面临更新不及时的问题，部分文档版本严重落后于通用语言文档站，而没有注明。绝大部分普通用户在已有本地化语言的情况下不会主动查阅其他语言版本的文档站，可能会传递过时信息，误导用户。
- 少数语言文档站可能面临翻译质量低下的问题。许多将少数语言作为第一母语，而同时习得多门语言的用户，会更希望直接阅读通用语言的文章，而不是首先被展示机器翻译或OpenCC自动转换下的质量低劣的母语文章。

可行的解决办法：

- 招募本地化语言团队负责维护少数语言的文档站。
- 直接删除客观上确实缺乏本地化团队维护的文档站。
- 在少数语言的文档站中显著标明本文档可能过时，请同时参阅其他语言版本。
- 使用非人工方式自动翻译和同步少数语言的文档。

**Comment by Constrat** [comment]
The main issue was that for small and/or big changes in documentations (mainly small) only the Chinese documentation was updated. About 6 months ago I reread almost the entire documentation and translated it in English as best as I could, but I noticed more and more updates to the current Chinese documentation and couldn't keep up.
I also don't feel like translating nowadays as it's a very taxing and time consuming thing.

**Comment by Cryolitia** [comment]
I think we should only keep Chinese and English, delete all others. Restrict each PR of docs should change both Chinese and English.

What's your point with this?

**Comment by Constrat** [comment]
I agree. Fortunately a KR and a JP maintainer appeared and they both speak either Chinese and English.
Also the docs related to the coding/implementation part are viewed by a very small % of the entire userbase.
Once the refactoring will be made, I'll see if I can create time to start translating

**Comment by HX3N** [comment]
I'm not sure about other language-speaking countries, but in KR, some users obtain information about MAA from posts on the community. However, some users still try to use MAA by referring to docs. (FAQ or information about available Emulator list)

For existing users, having just two documents in CN/EN should be fine, but for new KR users, it might be a bit challenging.
<br>

If it's not decided that overseas docs are being deleted, I'll also take the time to translate them.

**Comment by Cryolitia** [comment]
@HX3N Rather, they were removed due to lack of translation. If you are willing to be a stable docs localization maintainer, we can certainly just add a "potentially outdated" tag and keep the Korean language.

**Comment by HX3N** [comment]
> Rather, they were removed due to lack of translation. If you are willing to be a stable docs localization maintainer, we can certainly just add a "potentially outdated" tag and keep the Korean language.

Oh, I see. That sounds fine then 😄
