### ISSUE TITLE
自动战斗功能中 在为干员添加"特别关注"后不能识别需要选中的干员。

### ISSUE THREAD

**Issue by GitHub-Inull** [MaaAssistantArknights/MaaAssistantArknights#874]
在需要选中"德克萨斯"时因为我的干员添加了"特别关注"而不能职别。在进行复现时发现只要为任意干员添加了"特别关注"mma就不能识别出需要选中的干员

**Comment by ABA2396** [comment]
自动编队的问题又被发现多了一个.jpg

**Comment by MistEO** [comment]
这个问题比想象中的要麻烦，那个亮黄色和名字较长的干员名重合了，第一个字压根没法识别，干员名区域检测也非常难做。

![image](https://user-images.githubusercontent.com/18511905/174430982-1f366713-9f93-48ad-9403-b70e0f025f39.png)

加了一行界面提示，暂时摆烂了

**Comment by one-pyy** [comment]
> 这个问题比想象中的要麻烦，那个亮黄色和名字较长的干员名重合了，第一个字压根没法识别，干员名区域检测也非常难做。
> 
> ![image](https://user-images.githubusercontent.com/18511905/174430982-1f366713-9f93-48ad-9403-b70e0f025f39.png)
> 
> 加了一行界面提示，暂时摆烂了

因为黄色的rgb是(255,255,0), 所以可以考虑先过一遍b>220?

```python
import cv2
from itertools import product
p=cv2.imread('./screen.png')

for y,x in product(range(p.shape[0]),range(p.shape[1])):
  if p[y,x,0]>200:
    p[y,x]=[0,0,0]
  else:
    p[y,x]=[255,255,255]
cv2.imwrite('./screen_out.png',p)
```

进去前是这样
![screen](https://user-images.githubusercontent.com/72590023/176328929-53b142b5-5306-432a-863c-9cf2eb3c5c57.png)
出来是这样
![screen_out](https://user-images.githubusercontent.com/72590023/176328946-0a731734-aee9-4080-ace6-aca757be0523.png)
应该就可以识别了

(不太清楚maa里面能不能这样搞)

**Comment by ABA2396** [comment]
> > 这个问题比想象中的要麻烦，那个亮黄色和名字较长的干员名重合了，第一个字压根没法识别，干员名区域检测也非常难做。
> > ![image](https://user-images.githubusercontent.com/18511905/174430982-1f366713-9f93-48ad-9403-b70e0f025f39.png)
> > 加了一行界面提示，暂时摆烂了
> 
> 因为黄色的rgb是(255,255,0), 所以可以考虑先过一遍b>220?
> 
> ```python
> import cv2
> from itertools import product
> p=cv2.imread('./screen.png')
> 
> for y,x in product(range(p.shape[0]),range(p.shape[1])):
>   if p[y,x,0]>200:
>     p[y,x]=[0,0,0]
>   else:
>     p[y,x]=[255,255,255]
> cv2.imwrite('./screen_out.png',p)
> ```
> 
> 进去前是这样 ![screen](https://user-images.githubusercontent.com/72590023/176328929-53b142b5-5306-432a-863c-9cf2eb3c5c57.png) 出来是这样 ![screen_out](https://user-images.githubusercontent.com/72590023/176328946-0a731734-aee9-4080-ace6-aca757be0523.png) 应该就可以识别了
> 
> (不太清楚maa里面能不能这样搞)

天才的想法（）可以识别r通道取出来赋值给其他两个 ~~但我猜现在是直接灰度识别的~~ ~~还有imread读取的通道顺序应该是bgr而不是rgb吧~~

**Comment by ABA2396** [comment]
给识图加个选择通道的参数（~~不是~~）默认用灰度，传参数就用指定通道（？）

**Comment by ABA2396** [comment]
> > > 这个问题比想象中的要麻烦，那个亮黄色和名字较长的干员名重合了，第一个字压根没法识别，干员名区域检测也非常难做。
> > > ![image](https://user-images.githubusercontent.com/18511905/174430982-1f366713-9f93-48ad-9403-b70e0f025f39.png)
> > > 加了一行界面提示，暂时摆烂了
> > 
> > 
> > 因为黄色的rgb是(255,255,0), 所以可以考虑先过一遍b>220?
> > ```python
> > import cv2
> > from itertools import product
> > p=cv2.imread('./screen.png')
> > 
> > for y,x in product(range(p.shape[0]),range(p.shape[1])):
> >   if p[y,x,0]>200:
> >     p[y,x]=[0,0,0]
> >   else:
> >     p[y,x]=[255,255,255]
> > cv2.imwrite('./screen_out.png',p)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 进去前是这样 ![screen](https://user-images.githubusercontent.com/72590023/176328929-53b142b5-5306-432a-863c-9cf2eb3c5c57.png) 出来是这样 ![screen_out](https://user-images.githubusercontent.com/72590023/176328946-0a731734-aee9-4080-ace6-aca757be0523.png) 应该就可以识别了
> > (不太清楚maa里面能不能这样搞)
> 
> 天才的想法（）可以识别b通道取出来赋值给其他两个 ~但我猜现在是直接灰度识别的~ ~还有imread读取的通道顺序应该是bgr而不是rgb吧~

**Comment by one-pyy** [comment]
(咦, 忽然发现有些不对)

我的图是自己游戏里出来的, 所以好像比较宽

![image](https://user-images.githubusercontent.com/72590023/176356225-baef0c7b-fe91-4b67-884e-dbc588b54d8d.png)

但在这张图里有些坏事

![image](https://user-images.githubusercontent.com/72590023/176356336-6b398fe1-d998-4476-8118-50fd777db5d5.png)

(那么可能识别效果对于部分屏幕大小就不太好了233)

**Comment by one-pyy** [comment]
```python
import cv2
from itertools import product
from numba import jit

@jit
def bfs(img, y, x):
  if img[y][x][0]!=0:
    return
  queue=[]
  for dy in range(3):
    for dx in range(6):
      queue.append((y+dy,x+dx))
  while(len(queue)!=0):
    current_pixel=queue.pop(-1)
    if current_pixel[0]<0 or current_pixel[0]>=img.shape[0] or current_pixel[1]<0 or current_pixel[1]>=img.shape[1]:
      continue
    if img[current_pixel][0]==0:
      img[current_pixel] = [255, 255, 255]
      queue.append((current_pixel[0]-3, current_pixel[1]-3))
      queue.append((current_pixel[0]-3, current_pixel[1]+3))
      queue.append((current_pixel[0]+3, current_pixel[1]-3))
      queue.append((current_pixel[0]+3, current_pixel[1]+3))

if __name__=='__main__':
  img=cv2.imread('./screen.png')
  for y, x in product(range(img.shape[0]), range(img.shape[1])):
    if img[y, x, 0] > 220 or (img[y, x, 0]>160 and (img[y,x,1]-img[y,x,0]<10 or img[y,x,0]-img[y,x,1]<10)):
      img[y, x] = [0, 0, 0]
    else:
      img[y, x] = [255, 255, 255]
  bfs(img, img.shape[0]//11,img.shape[1]//3)
  cv2.imwrite('./screen_out.png',img)
```

于是就有了这个复杂了亿点点的思路(且python跑起来有些慢, 优化看大佬的了)

思路是先用b通道二值化, 然后此时外秒有一个黑色边框, 然后bfs扩散为白色。扩散的时候为了避免把字去掉, 所以只扩散当前像素的7*7的四个角, 然后取3*6的方格作为扩散起点
![screen](https://user-images.githubusercontent.com/72590023/176371190-c41c9015-ad3f-4613-b798-96d78d8de0a1.png)
这个是adb取出来的截图

![screen_out](https://user-images.githubusercontent.com/72590023/176371249-de8bd4d3-4c02-4228-9e10-94330653f488.png)
运行完是这样的

我个人觉得效果已经可以了(就是复杂度不ok)

**Comment by MistEO** [comment]
黄色好办，白色的 < 解决不掉啊

**Comment by one-pyy** [comment]
> 黄色好办，白色的 < 解决不掉啊

(又研究了一下, 发现其实和字有细微的差别? 可能锐化一下就行)

```python
import cv2
from itertools import product
import numpy as np
if __name__=='__main__':
  img=cv2.imread('./screen.png')
  kernel = np.array([[0, -1, 0], [-1, 4, -1], [0, 0, 0]])#卷积核, 不要出下边框
  img = cv2.filter2D(img, -1, kernel)#锐化
  for y, x in product(range(img.shape[0]), range(img.shape[1])):
    if img[y, x, 2] > 253:
      img[y, x] = [0, 0, 0]
    else:
      img[y, x] = [255, 255, 255]
  cv2.imwrite('./screen_out.png',img)
```
![screen_out](https://user-images.githubusercontent.com/72590023/176409621-f5c4aeba-c674-4ea9-ba55-a04cf4bf1d01.png)
(实际上就我自己adb导出来这张可以用, 上面那张不太行, 可能是因为上面那张是截图? 但可能是个可以的解决方案)

**Comment by zzyyyl** [comment]
好强！所以什么时候加到 MAA 里（
