### ISSUE TITLE
weblate 宕机

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#8742]
### 说说你遇到的问题？

连接报hsts错误 查看证书发现根本和maa没关系
readme里还有图片和超链接 是临时维护还是...?

**Comment by ABA2396** [comment]
临时维护

**Comment by ChingCdesu** [comment]
服务已经恢复了。
因为ACME Account变过了，所以要等一会let's encrypt的证书会发
