### ISSUE TITLE
刷理智列表没有最新的关卡

### ISSUE THREAD

**Issue by Dyinglight5** [MaaAssistantArknights/MaaAssistantArknights#8743]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

能正常更新，但是活动关卡有一段时间没出来了

### Version

UI Version: v5.1.0
Core Version: v5.1.0
Resource Version: 源石尘行动·复刻

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14813741/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14813744/gui.log)
3月31日

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150124520/dd445648-b4be-41ca-9978-81ed23d6fe51)

### 还有别的吗？

mumu模拟器
win1123h2

**Comment by Dyinglight5** [comment]
不是今天活动关了出现的，是前几天活动开着的时候就没有

**Comment by Rbqwow** [comment]
这咋今天才发issue 凌晨四点活动都结束了 关卡已经没了
或许可以试试删掉 config/gui.json 里面的 `"VersionUpdate.ResourceApi"` 行
或者等下次活动再看
