### ISSUE TITLE
自动检测无法获取到蓝叠国际版的adb路径

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#8748]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题 已尝试勾选 `每次自动检测`

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.1-beta.1
Core Version: v5.2.1-beta.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14816878/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14816879/gui.log)

### 截图

检测后的结果截图
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55343783/a36e5364-9891-489f-bc04-99768196d88d)

### 还有别的吗？

BlueStacks 5.21.0.1043 Android 11

add gui

**Comment by D3adEr1c** [comment]
https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E7%A1%AE%E8%AE%A4-adb-%E5%8F%8A%E8%BF%9E%E6%8E%A5%E5%9C%B0%E5%9D%80%E6%AD%A3%E7%A1%AE

**Comment by D3adEr1c** [comment]
按照文档进行手动配置：
https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html#%E8%BF%9E%E6%8E%A5%E9%94%99%E8%AF%AF
