### ISSUE TITLE
外国人可能很难知道MAA支持外服

### ISSUE THREAD

**Issue by zhangweijian97** [MaaAssistantArknights/MaaAssistantArknights#875]
如下图所示，直接在github搜Arknights的话，MAA的简介是“《明日方舟》小助手，自动刷图、智能基建换班，全日常一键长草！”。外国人看不懂就跳过了，建议加上英文，support Arknights_US client，support Auto battle function，之类的

<img width="1473" alt="image" src="https://user-images.githubusercontent.com/52686008/173479002-3fa7e872-e180-4435-b66c-7858c55e122b.png">

**Comment by ABA2396** [comment]
然而界面也是中文的，虽然可以全选然后开始）

**Comment by MistEO** [comment]
现在支持的功能太少了，~~没脸拿出去丢人~~，不过确实可以写上

**Comment by MistEO** [comment]
文档的翻译似乎也有点问题，不应该叫 NA client/server, 回头一起改改
