### ISSUE TITLE
以自动检测连接选项启动后，某些情景下“退出模拟器”选项会把正在运行的其他模拟器退出

### ISSUE THREAD

**Issue by H-XZ** [MaaAssistantArknights/MaaAssistantArknights#8751]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

装了两个模拟器，蓝叠只用来挂定时任务，mumu12只用来游玩，挂定时任务的maa配置连接选项和“开始唤醒”选项指定的是蓝叠，
临时需要maa时用的配置“开始唤醒”选择的是自动检测连接与每次重新检测（因为如果已经开了模拟器懒得重开一个），取消自动检测可以看见默认是mumu12的配置，但当自动检测连接到蓝叠，且在连接到蓝叠后再启动mumu，完成后退出模拟器时会把两个都退掉。

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.1-beta.1
Core Version: v5.2.1-beta.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14817133/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14817135/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/118260498/ec18e762-a60b-438c-acc8-2586d5d78f92)

**Comment by ABA2396** [comment]
退出的时候是通过mumu的控制台退的，退完之后会再杀一下端口，但是配置选的mumu，端口写的蓝叠的5555，所以会被杀两次。你得保证配置选的和模拟器是一样的
