### ISSUE TITLE
定时启动突然失效，以前没问题的

### ISSUE THREAD

**Issue by Chenyinlin-Yiking** [MaaAssistantArknights/MaaAssistantArknights#8754]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我基本就是早上开机，设置了自动执行，晚上就关机，一直长草。好像是几天前我自己上去想打打活动才发现定时执行出问题了，maa并没有在我原来设定的时间自动执行，以前都是没问题的，最近都不行了我也不清楚为什么，开机自启动是没问题的。

### Version

v5.2.0

### 日志文件

[Uploading asst.log…]()
[Uploading gui.log…]()

### 还有别的吗？

我使用模拟器：mumu
操作系统：win11
系统重装过，游戏本除了steam游戏外，没有安装额外的库文件。没有C，python编译环境，没有anaconda。

**Comment by Chenyinlin-Yiking** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14818114/gui.log)

**Comment by Chenyinlin-Yiking** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14818117/asst.log)

**Comment by ABA2396** [comment]
从什么时候开始的？现在开机自启可能只有不能打开管理员权限的情况了

**Comment by Chenyinlin-Yiking** [comment]
> 从什么时候开始的？现在开机自启可能只有不能打开管理员权限的情况了

上周吧，具体日期我不太清楚

**Comment by Chenyinlin-Yiking** [comment]
![1711953495193](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75869957/66e03857-9a62-4150-b29c-4b19aaab1cdd)
这是啥bug，为什么中文字全变了？我之前装了赛博朋克2077的vortex mod管理器，装了个net6，会对这个有影响吗

**Comment by Chenyinlin-Yiking** [comment]
> 从什么时候开始的？现在开机自启可能只有不能打开管理员权限的情况了

又有问题了，我是否需要重装？
![error](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75869957/4655df92-6737-46d1-b2db-d044b828c929)

**Comment by Chenyinlin-Yiking** [comment]
> #8755

不好意思还是要打扰，那定时启动会失效这个问题，我需要做什么？需要重装吗？

**Comment by ABA2396** [comment]
没看懂，看日志里那些13点19点的定时不都正常跑起来了吗
定时执行是要maa挂在后台才会定时执行的，如果没开的话是不会自动启动的

**Comment by Chenyinlin-Yiking** [comment]
> 没看懂，看日志里那些13点19点的定时不都正常跑起来了吗 定时执行是要maa挂在后台才会定时执行的，如果没开的话是不会自动启动的

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75869957/2e67667e-0028-44eb-9e2b-449e080f70e6)
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75869957/b0fd9522-6d19-4b25-b7a6-4b0d41804840)
从中午执行过后一直开着，就这样，log两个我都看了，只有你说的13点19分的纪录，没有任何其他别的

**Comment by ABA2396** [comment]
> 定时执行是要maa挂在后台才会定时执行的，如果没开的话是不会自动启动的

你选的不是完成后退出模拟器和MAA吗？MAA后台都退了还怎么开始定时任务

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/29be92f5-05e0-4160-af3e-736fc4e01b86)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/0da80c47-04d4-4758-b9fb-050bdddf60c8)

**Comment by ABA2396** [comment]
> ![1](https://private-user-images.githubusercontent.com/75869957/318418845-2e67667e-0028-44eb-9e2b-449e080f70e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzQzNzMsIm5iZiI6MTcxMTk3NDA3MywicGF0aCI6Ii83NTg2OTk1Ny8zMTg0MTg4NDUtMmU2NzY2N2UtMDAyOC00NGViLTllMmItNDQ5ZTA4MGY3MGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEyMjExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3M2E4OWYwZTBiMGMzNTQ0Mzk4NmFhZTI3YjhmNTRkMWRjOTlhMmEyYzk4NmU1MmY4Mzc3YTI5MjZmYmQ4NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fcVEdcP2rHUwUL2hxM-T-TRgQbxlqDHE0dMMeLDfzhQ)

这段时间电脑有休眠吗？休眠的时候软件也都是跑不了的

**Comment by Chenyinlin-Yiking** [comment]
> > ![1](https://private-user-images.githubusercontent.com/75869957/318418845-2e67667e-0028-44eb-9e2b-449e080f70e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzQzNzMsIm5iZiI6MTcxMTk3NDA3MywicGF0aCI6Ii83NTg2OTk1Ny8zMTg0MTg4NDUtMmU2NzY2N2UtMDAyOC00NGViLTllMmItNDQ5ZTA4MGY3MGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEyMjExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3M2E4OWYwZTBiMGMzNTQ0Mzk4NmFhZTI3YjhmNTRkMWRjOTlhMmEyYzk4NmU1MmY4Mzc3YTI5MjZmYmQ4NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fcVEdcP2rHUwUL2hxM-T-TRgQbxlqDHE0dMMeLDfzhQ)
> 
> 这段时间电脑有休眠吗？休眠的时候软件也都是跑不了的

我可能今天操作有问题，我今晚不关机挂后台看一下他明早会不会自启动，那时候再联系您，谢谢

**Comment by Chenyinlin-Yiking** [comment]
> > ![1](https://private-user-images.githubusercontent.com/75869957/318418845-2e67667e-0028-44eb-9e2b-449e080f70e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzQzNzMsIm5iZiI6MTcxMTk3NDA3MywicGF0aCI6Ii83NTg2OTk1Ny8zMTg0MTg4NDUtMmU2NzY2N2UtMDAyOC00NGViLTllMmItNDQ5ZTA4MGY3MGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEyMjExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3M2E4OWYwZTBiMGMzNTQ0Mzk4NmFhZTI3YjhmNTRkMWRjOTlhMmEyYzk4NmU1MmY4Mzc3YTI5MjZmYmQ4NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fcVEdcP2rHUwUL2hxM-T-TRgQbxlqDHE0dMMeLDfzhQ)
> 
> 这段时间电脑有休眠吗？休眠的时候软件也都是跑不了的

![3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75869957/a64e5f2a-3cbd-47f7-84ca-6dc8f1c27beb)
真的不行，你看一下，我晚上开的，一直挂到现在，我设置了7点自动执行

**Comment by ABA2396** [comment]
> 这段时间电脑有休眠吗？休眠的时候软件也都是跑不了的

所以你电脑有设自动休眠吗

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/c3189f7f-747f-46ce-a3ae-0a3d878687c1)
这两种情况对软件来说和关机没什么两样，都是不能运行的

**Comment by Chenyinlin-Yiking** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/318612429-c3189f7f-747f-46ce-a3ae-0a3d878687c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjY2MDgsIm5iZiI6MTcxMjEyNjMwOCwicGF0aCI6Ii85OTA3Mjk3NS8zMTg2MTI0MjktYzMxODlmN2YtNzQ3Zi00NmNlLWEzYWUtMGEzZDg3ODY4N2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA2MzgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZWY4MzhmZGRiNTY4MWZlZGZhNmI0NTFhNmYwZjUzMzk1NjI2ZmJhYjQ5MjY3YjI4OWM2OTAyYTg2NTBiMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ByYXt8_-eWfdISJCapE0LqiQK-_be0N77FgI-rY6IX8) 这两种情况对软件来说和关机没什么两样，都是不能运行的



> > 这段时间电脑有休眠吗？休眠的时候软件也都是跑不了的
> 
> 所以你电脑有设自动休眠吗

我一直插着电源的，电脑电源设置如图
![1712126526361](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75869957/7d2ebc2e-4dde-4afe-8fc7-375eb2d48f4d)

**Comment by ABA2396** [comment]
cc @status102
