### ISSUE TITLE
愚人节彩蛋无法进入MAA设置

### ISSUE THREAD

**Issue by FSPaul2498** [MaaAssistantArknights/MaaAssistantArknights#8755]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

触发愚人节彩蛋之后无法进入MAA设置，会报错后强制退出

### Version

MAA版本为5.2.0，因无法打开MAA设置而无法提供更准确的版本信息

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14818115/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14818121/gui.log)

### 截图

![Snipaste_2024-04-01_08-24-38](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35190475/02c73dbe-b3a7-40f7-bb36-981cfd2ba1c7)

### 还有别的吗？

[err_window.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14818143/err_window.txt)
这是弹窗报错的全文内容

**Comment by Sduck-Inverse** [comment]
太好了……我还以为只有我一个人报错T T
<img width="600" alt="5bbee6ee4aeabf7023e64882fc1e455c" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87361258/4f52863d-6b91-49c3-8b31-70931cf7e20c">

**Comment by AmemiyaMiomy** [comment]
+1，双服玩家想要切预设直接闪退没办法用了，支持搞彩蛋但别影响正常使用吖 QAQ

**Comment by SovietBall** [comment]
+1，不过彩蛋的确挺有趣的ww，才想起今天是愚人节x

**Comment by WSMTBG** [comment]
+1 能给个重启恢复正常的选项吗（）

**Comment by SovietBall** [comment]
> +1 能给个重启恢复正常的选项吗（）

好像重启就恢复正常了（x

**Comment by Gooooooooooooooooooooooooooooooooooooda** [comment]
> > +1 能给个重启恢复正常的选项吗（）
> 
> 好像重启就恢复正常了（x

我重启也不行，依然会报那个错

**Comment by Saratoga-Official** [comment]
> > > +1 能给个重启恢复正常的选项吗（）
> > 
> > 好像重启就恢复正常了（x
> 
> 我重启也不行，依然会报那个错

多重启几次，一次不行

**Comment by Saratoga-Official** [comment]
#8753 可以看看这个

**Comment by zuiluo1116** [comment]
好耍

**Comment by Montaro2017** [comment]
多重启几次，有个提示就变正常了

**Comment by FengHao-coder** [comment]
我还以为中病毒了

**Comment by shendeguize** [comment]
好活,下次别整了

**Comment by GanbaRubyyy** [comment]
博士，你怎么晕乎乎的？

**Comment by CafeKiller** [comment]
重启了20多次还是没用，还是出现这个报错，是不是只能重装了

**Comment by Saratoga-Official** [comment]
> 重启了20多次还是没用，还是出现这个报错，是不是只能重装了

等明天看看吧，没剩几个小时了

**Comment by CafeKiller** [comment]
悲〒▽〒 不是说愚人节只过半天的吗？怎么还能被整到悲X﹏X

**Comment by YYuX-1145** [comment]
果然是个bug，把cache文件夹删了就正常了

**Comment by yuanbug** [comment]
我是2号才碰到这个问题，同样是把cacha删除恢复
不过就算它没这个bug，每次跑完就来个摇摇晃晃弹窗也很烦人😒

**Comment by JohnHe327** [comment]
同遇到，弹窗弹一次就行了每次换号切换配置都弹，我挂在后台没人管的被这样耽误事了，而且今天二号了还没完

**Comment by 4873** [comment]
好活
我差点就要卸载重装了

**Comment by qaz1qazlol2** [comment]
这个彩蛋一整我的maa配合阿里云云手机自动代理直接崩了
白花我1块多

**Comment by AzzyDreamurr** [comment]
啊? 这是彩蛋啊c
我同时开俩MAA, 就挂小号的这个是这样(ˉ▽ˉ；)...
已经一礼拜多了
~~(配合自动定时重启软件一起用的, 一直就没管. 今天才看到c)~~
