### ISSUE TITLE
Nightly changelog formatting

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#8757]
### Description

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/01e29e03-04f1-40f7-b025-cdeac04b6042)
Seems like there are some missing new lines.
- `###` is not recognized, most likely because they are not the first characters.
- also all the info regarding the previous / current version seems a bit much and could use some tiding.

### Version

Resource Version: Come Catastrophes or Wakes of Vultures
UI Version: v5.2.1-beta.1.d009.gb3b09a966
Core Version: v5.2.1-beta.1.d009.gb3b09a966

**Comment by Constrat** [comment]
cc @AnnAngela @SherkeyXD

**Comment by Constrat** [comment]
Also to prevent going to a new line when reading the versions, is it possible to manually `\n` them?
For example:
From: alpha/v5.2.1-beta.1.d008.gcd347b73e
To: v5.2.1-beta.gb3b09a966

Another point: Why only `From` has the `alpha/` in front?

**Comment by status102** [comment]
sad

**Comment by Constrat** [comment]
Unfixable @_@

**Comment by status102** [comment]
is there any way to keep the new line

**Comment by Constrat** [comment]
I just noticed that this lost the `from` `to` version thing. Not that it was vital necessary

**Comment by status102** [comment]
it's exceptable, not lost

**Comment by status102** [comment]
looks good?

**Comment by Constrat** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/34e2d52d-ed57-4074-9e91-7ed8b83532ca)
Sorry for the delay.
Yeah looks very good. 
Is it supposed to duplicate the version?

**Comment by status102** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/246a628acfe9e71679a71bebb635ca703197e791
try perf

**Comment by Constrat** [comment]
I'll just build it myself.

**Comment by Constrat** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/d3f4a750-7461-4521-aa9e-d174e89f958f)
@status102 Looks very good.
