### ISSUE TITLE
使用【借助战打of-1赚信用】及关卡选择【当前/上次】通关【OF-1】的处理逻辑。

### ISSUE THREAD

**Issue by SunShineJF** [MaaAssistantArknights/MaaAssistantArknights#8758]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

当活动结束或者重启MAA等情况下，配置选择了【借助战打of-1赚信用】及关卡选择【当前/上次】，并且【当前/上次】关卡刚好是【OF-1】时候，MAA会通关一次【OF-1】，提示“掉落识别错误，无奖励关卡，已停止”，实际上我理智是够进入备战关卡的。

### 有什么好的想法？

遇到【当前/上次】关卡为【OF-1】或者是其他通关后提示“掉落识别错误，无奖励关卡，已停止”的关卡时，
若配置了【备选】关卡，可以不停止，此时可以先判断理智是否足够，进而选择进入备选关卡或者停止Fight。
还可以在【借助战打OF-1赚信用】这里增加提醒，可能会存上述情况，建议配置备选关卡。

### 其他内容

MAA版本v5.2.1-beta.1
模拟器：蓝叠5.21.111.1001 N64
发现问题日期：2024.04.01，刚好是愚人节，MAA还遇到了愚人节彩蛋导致打不开设置的问题，不过有人提交issue。
测试日期：2024.04.02 9点，理智足够和理智不够都测试了，都会停止Fight。
![企业微信截图_17120210305189](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49141302/82e63e3c-eff4-4bee-b0af-37acaf6d11a4)

**Comment by ABA2396** [comment]
core接收的参数就只有一个关卡，ui的备选关卡个根据星期去判断的，传给core的信息是关卡选择和备选中第一个开放的关卡，因为 当前/上次 是常驻的，所以只会告诉core打 当前/上次。ui是不知道游戏内情况的，而且就算知道了也没用，在任务链的情况下也只能往最后一个任务之后插，但这样会在跑完剩余理智的任务之后执行刷理智，更加有问题。

至于你说的关卡选择从活动关变成当前/上次，这个是要活动结束后再重启才会变。在结束后活动关卡仍会存在列表中，并且下面那个关卡开放提示会提示这个关卡未开放，在重启后才会移除活动关卡，并变成当前/上次

**Comment by SunShineJF** [comment]
明白了，好像这种情况确实没办法靠MAA处理。只能手动调整
