### ISSUE TITLE
愚人节活动助手

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#8759]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我是一无所有的那个

### 有什么好的想法？

maa对小怪头像进行识别，找出对应敌人，在prts.wiki中调取生命、攻击、物抗法抗、元素损伤进度等信息，将各项数值输出，然后输出双方每个小怪1v1打桩的信息用做参考

**Comment by Daydreamer114** [comment]
喵

**Comment by Daydreamer114** [comment]
基本上啥怪都是随机刷的了，打表没啥用，除非兵种碾压
有新想法欢迎啊

**Comment by status102** [comment]
not planed
