### ISSUE TITLE
在正常执行任务时突然出现任务出错：Fight

### ISSUE THREAD

**Issue by LBEILC** [MaaAssistantArknights/MaaAssistantArknights#876]
执行任务时，可以开始，但一旦开始后会直接出现任务出错

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8895999/asst.log)

![image](https://user-images.githubusercontent.com/74463574/173484677-845670d5-c0f4-4eb1-a65e-98262e06c3db.png)

**Comment by MistEO** [comment]
你手动点的和定时任务（11点的）撞车了
