### ISSUE TITLE
希望肉鸽在刷开局的条件下新增一个自选难度几的选项

### ISSUE THREAD

**Issue by 520firewire520** [MaaAssistantArknights/MaaAssistantArknights#8761]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在肉鸽刷开局会自动选择最高的难度，对我来说也就是难15，但我本人不是那么厉害的集批，我想在难12刷刷角标，但偶尔也会想开把15挑战自己一把， 目前个人解决这个问题的方法是设定只打一局，就不会自动选难15，但是如果这次没烧到水要在弄一次，不是很方便

### 有什么好的想法？

希望能增加一个选肉鸽等级难度的选项，就跟最近新增的刷密文版一样

**Comment by status102** [comment]
Duplicate of #6494
