### ISSUE TITLE
在基建内无法跳转访问好友，直接进商店购物

### ISSUE THREAD

**Issue by feiqingbiss** [MaaAssistantArknights/MaaAssistantArknights#8775]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

主题为迷城，设置了基建换班，但是其实只是收菜，设置了访问好友，但是在收菜完就提示mall，卡在会客室，然后回到主页直接开始信用购物，没有访问好友。

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.1-beta.1.d051.gdcf331fab
Core Version: v5.2.1-beta.1.d051.gdcf331fab

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14854201/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14854204/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36787768/e54155cb-4c9a-4670-aed0-2730c5c88fdb)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36787768/513166c0-1ef3-417b-8ea7-d39a2f4053f4)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36787768/fa721822-b6cf-4362-a31e-237e80048c40)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36787768/c10335ff-dfae-4093-ac18-8762c75818da)

### 还有别的吗？

用的MUMU12模拟器，win11 23H2

**Comment by Hydrogina** [comment]
遇到同样的问题 以下是节选asst.log
[节选asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14878921/asst.log)

卡在这一步，重试了20次，然后on_run_fails
[2024-04-05 09:49:05.292][INF][Px5e14][Tx1738] {"class":"asst::ProcessTask","details":{"cur_retry":20,"retry_times":20,"to_be_recognized":["VisitNext","VisitNext@LoadingText","VisitNextBlack","VisitNextOcr"]},"first":["VisitBegin"],"pre_task":"StartToVisit","subtask":"ProcessTask","taskchain":"Mall","taskid":11}

卡在这个界面
![Screenshot_2024 04 05_09 59 41 823](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46482682/20f3e11f-4a72-4a12-b520-35a4666ced8d)

**Comment by ABA2396** [comment]
有点抽象，这玩意竟然能匹配上
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/b74d1a85-bdc7-45b0-800b-6b3607dc3f18)

**Comment by mamalalarouroufan** [comment]
我遇到的问题是    在选了 获取信用及购物 标签时    并且好友页面的第一位好友他的标签背景是新出的红蓝黑的那个名片时   这时程序会卡住   等了好久后直接跳过访问好友基建  开始进入信用商店购买逻辑        
另一个遇到的问题是   先手动把好友列表拉取到中间  且此时展示的第一位好友他的标签背景是新出的红蓝黑的那个名片时   并且maa只选 获取信用及购物 标签    此时点击linkstart  也会触犯识别不了的问题   会回退到游戏的主页面而非正常的直接进入下一个好友基建内   
我是遇到了这两个问题    用的mumu模拟器   win10系统  maa一直都是更新的最新版

**Comment by mamalalarouroufan** [comment]
我遇到的问题是    在选了 获取信用及购物 标签时    并且好友页面的第一位好友他的标签背景是新出的红蓝黑的那个名片时   这时程序会卡住什么都不做   等了一会后直接跳过访问好友基建  开始进入信用商店购买逻辑        
另一个遇到的问题是   先手动把好友列表拉取到中间  且此时展示的第一位好友他的标签背景是新出的红蓝黑的那个名片时   并且maa只选 获取信用及购物 标签    此时点击linkstart  也会触犯识别不了的问题   会回退到游戏的主页面而非正常的直接进入下一个好友基建内   
我是遇到了这两个问题    用的mumu模拟器   win10系统  maa一直都是更新的最新版
