### ISSUE TITLE
i18n: Copilot operator localization

### ISSUE THREAD

**Issue by rayveiled** [MaaAssistantArknights/MaaAssistantArknights#8776]
### Before raising the issue...

- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I'm probably sure this is a new feature/suggestion and not a bug encountered (please attach logs if you're not sure)

### The problems you have encountered?

Currently, "Copilot" does not fully support the English language.
When loading a Chinese JSON from PRTS.Plus, it uses the script as is, with the Chinese Operator names for Auto Squad
International players can greatly benefit from converting it to the language that the Arknights Version that MAA has selected in the Client tab of Settings. (YoStarEN, YoStarJP....)

Conversely, this could help allow for English/International players to slowly help contribute to the Copilot Database if it could convert other languages scripts to Chinese.

### Any good ideas?

Have a script to automatically convert Chinese operator names to English or any required language and vice versa.
Attach a game version to the JSON file, and convert it if it is a different version of the game. (CN/YoStarEN/JP/KR)

**Comment by Constrat** [comment]
I'll try and see if this can be done. No promises :-/

**Comment by Constrat** [comment]
Nvm I don't think it's even feasible.
Considering it's all hard coded, for every log message we would need to call `battle_data.json`, cycle through all operators until a match is found (if it is found) after that outputting the correct localized name_xx, just like for the OperBox task, but in that case the battle_data.json was already implemented.

@ABA2396 Any ideas and / or if this is worth continuing?
