### ISSUE TITLE
基建换班无法自动进入基建

### ISSUE THREAD

**Issue by ctyszdnbx** [MaaAssistantArknights/MaaAssistantArknights#8777]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

基建换班需要自己点一下基建才能进入基建，无法自动进入，以前可以自动进入基建，现在进行基建换班因为无法自动进入而会呆在主页面不动

### Version

UI Version: v5.2.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14863226/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14863228/gui.log)

时间点：基建换班

### 还有别的吗？

mumu模拟器
win11
4060 i9

**Comment by Constrat** [comment]
The log (and the issue) looks identical to:
- #8772

**Comment by Constrat** [comment]
Fixed with https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/8795
