### ISSUE TITLE
识别干员功能 第二纵列干员字体异常 

### ISSUE THREAD

**Issue by WhiteBSK** [MaaAssistantArknights/MaaAssistantArknights#8779]
### 说说你遇到的问题？

看着好晕，希望修一下

**Comment by ABA2396** [comment]
没看懂，啥有问题
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/3a51c99e-8227-4f43-8f4f-d169f525c655)

**Comment by WhiteBSK** [comment]
哦是windows缩放比例导致的字体模糊，没事了
