### ISSUE TITLE
copilot 需要新增关卡类别支持

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaAssistantArknights#878]
方便Copilot UI 搜索

别老整那些没啥用的feature

再催一下地图的资源以及全关卡的列表

**Comment by MistEO** [comment]
啥叫关卡类别

**Comment by Shawnsdaddy** [comment]
> 啥叫关卡类别

比如说 肉鸽，悖论模拟，主线关卡，活动关，之类的，在copilotserver上也可以搜索

**Comment by MistEO** [comment]
新增这个不关 core 的事情啊，我不需要知道关卡是什么类别的。

server 和 ui 这边做就好了
