### ISSUE TITLE
宿舍换班错误

### ISSUE THREAD

**Issue by 147551866** [MaaAssistantArknights/MaaAssistantArknights#8785]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在宿舍换班的时候，空宿舍放塑心，车尔尼，爱丽丝的时候，总是会跳过塑心，只放车尔尼和爱丽丝，该宿舍也没法自动放心情不满的干员。这个bug在以前设置3个班次的时候是没有的，但是我这两天换成6个班次之后就出现了
PS：另附上我的排版表，在第三班换第四班的时候，最下面的宿舍会复现这个bug

### Version

源石尘行动·复刻：v5.2.1-beta.1：v5.2.1-beta.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14892202/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14892203/gui.log)
[排班表.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14892204/default.json)

**Comment by chenyinggu** [comment]
试试把第四班的人放第一个宿舍

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/cca6de7f-84d5-47f3-927a-8951b436ef9f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/be2d6532-a6f6-4ff9-bf74-b177c54c919d)
把要指定的人都往前放
