### ISSUE TITLE
蓝叠国际版模拟器无法完成后退出

### ISSUE THREAD

**Issue by ZGLinus** [MaaAssistantArknights/MaaAssistantArknights#8790]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

蓝叠国际版模拟器完成任务后无法退出，以前可以正常退出的。

### Version

UI Version: v5.2.0
Core Version: v5.2.0
Resource Version: 源石尘行动·复刻

### 日志文件

```
2024-04-06 05:42:10.647
2024-04-06 08:45:52.803
```
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14893870/debug.zip)

### 还有别的吗？

模拟器版本5.20.10.1003 N64

**Comment by SherkeyXD** [comment]
你的maa是管理员模式吗

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/103bac62-ed1e-4609-823b-7a0d90f28b1f)
没蓝叠的权限大查不到信息，是最近给了蓝叠管理员权限启动还是原来给了maa管理员权限现在下了

**Comment by ABA2396** [comment]
> 你的maa是管理员模式吗

如果是管理员启动的话在MaaAssistantArknights GUI started后面会输出一条信息的

**Comment by SherkeyXD** [comment]
不过这个问题我也遇到了 而且蓝叠和maa都是非管理员（

**Comment by ZGLinus** [comment]
莫名其妙的又好了，不过蓝叠模拟器是不需要管理器权限的。

**Comment by Constrat** [comment]
Bluestacks on 5.20.0.1037, MAA closes the emulator correctly.
```py
[2024-04-10 11:11:58.884] <1><> All task(s) completed!
Sanity will be full at 2024-04-10 21:35 (In 10h 23m)
[2024-04-10 11:11:58.908] <1><> Info: `C:\Program Files\BlueStacks_nxt\bsconsole.exe` not found. This may be the BlueStacks International emulator, try to kill the emulator by the port.
[2024-04-10 11:11:58.908] <1><> address: 127.0.0.1:5555, port: 5555

```
