### ISSUE TITLE
win11更新后MAA在白天不可用

### ISSUE THREAD

**Issue by Menganase** [MaaAssistantArknights/MaaAssistantArknights#8791]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA之前正常可用，近期win11更新后，MAA只有在每天晚上的时间段（时间段未测试，大约是9点到12点）可用，白天使用时点击开始无反应，信息提示正在连接中，之后提示出错尝试重新启动adb、重新启动模拟器等等，替换adb后亦是如此。晚上使用时非常正常。

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.1-beta.1
Core Version: v5.2.1-beta.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14896479/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14896480/gui.log)

### 还有别的吗？

个人看了下gui.log，然后看到是一个<.NET TP Worker>中午会提示return=false，晚上就是return=true。我不会使用.net，一开始猜测是.NET的相关服务在win11更新后被关闭了，在我使用其他软件后启动了这个服务导致晚上的时间段MAA在其他程序启动过后可用，但是逐一尝试启动常用软件后启动MAA均无果，但一到晚上就使用正常。
也尝试过从蓝叠国际版更换为雷电模拟器，仍只可在晚间段使用，白天用不了。

**Comment by ABA2396** [comment]
你这啥版本的雷电，现在不都是固定emulator-5554了吗
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/1f7063b6-be72-47bd-a359-bf6816f10cf3)

.net和更新没关系，倒是adb可能和加速器/代理/手机助手什么的有冲突，看 https://maa.plus/docs/用户手册/常见问题.html#连接错误

**Comment by SennaObtusifolia** [comment]
重灌win11直接顯示無法在您的電腦上執行
![image](https://github.com/user-attachments/assets/97b08f21-1ae2-409d-94df-2d92b61fdd8e)

**Comment by ABA2396** [comment]
你下错版本了，你的电脑是win-x64，不是win-arm64 @SennaObtusifolia

**Comment by SennaObtusifolia** [comment]
學到了，感謝
