### ISSUE TITLE
水月肉鸽异常卡死

### ISSUE THREAD

**Issue by laisonlin** [MaaAssistantArknights/MaaAssistantArknights#8792]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

执行自动肉鸽时，有概率卡死在地图界面。

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14896803/gui.zip)

### 截图

![image](https://gith
![2024-04-07_18-21-45-953_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66906448/97fac8de-bba0-403b-bdec-44d57ee60478)
ub.com/MaaAssistantArknights/MaaAssistantArknights/assets/66906448/e068b025-fb0c-4df4-8ec0-4af7c42d1fc0)

### 还有别的吗？

模拟器：MUMU12
操作系统：windows11

**Comment by laisonlin** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66906448/8393762d-a768-49ad-8f6f-51e7062e9531)
buis
补充maa截图

**Comment by horror-proton** [comment]
看上去是 ` 17:17:53` 的时候点不期而遇插件的问题
