### ISSUE TITLE
使用英文命名所有的文档 | Name all document files in English

### ISSUE THREAD

**Issue by wangl-cc** [MaaAssistantArknights/MaaAssistantArknights#8794]
当前不同语言的文档都是使用其对应语言命名，这导致想要找到同一份文档的另一个语言版本十分困难。因此我提议将所有的文档都用英文命名，确保同一文档不同语言版本共享同一名称，以便于快速识别和定位。这样可以方便维护，也方便可能的机器翻译。

此外，我提议将所有的简体中文文档也放在 `zh-CN` 子文件夹中以保持和其他语言文档的一致性。

相关 issue: #7524, #8734

**Comment by ABA2396** [comment]
命名的问题感觉可以在文件开头加个英文注释？这样搜开头也能找到

**Comment by wangl-cc** [comment]
> 命名的问题感觉可以在文件开头加个英文注释？这样搜开头也能找到

这样也可以，使用统一的文件名的另一个好处是相对链接的可以更容易复用。

**Comment by Rbqwow** [comment]
话说旧链接需要做一些301跳转吗 或者404自动跳回到主页
