### ISSUE TITLE
能否添加干员喂经验书升级的小功能

### ISSUE THREAD

**Issue by zhongfly** [MaaAssistantArknights/MaaAssistantArknights#88]
主要是想使用基础/初级作战记录升级（毕竟日常零碎获得太多了），自己手动点的话有些累，虽然可以长按，但每次上限40，这也是游戏的一个痛点，希望开发者能提供这样的功能~

**Comment by MistEO** [comment]
有计划提供一个杂项小工具箱，包括 自动加急公招 等功能，会考虑把这个也加进去。

~~在做了（新建文件夹~~

**Comment by Shawnsdaddy** [comment]
#266 重复
yj 已经实装
