### ISSUE TITLE
MAA v5.2.1b1: 界面的各种中文文字变成酒类图标字体或为空白

### ISSUE THREAD

**Issue by AzzyDreamurr** [MaaAssistantArknights/MaaAssistantArknights#8800]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

不知道触发方式, 最近一周打开就是这种情况( )
极少概率打开是正常的.
整体文件还保留着, 如果需要分析我可以上传到网盘里.

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.1-beta.1
Core Version: v5.2.1-beta.1

### 日志文件

[DebugLog.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14912241/DebugLog.zip)

### 截图

下面是一些截图:
1.一键长草界面:
![Snipaste_2024-04-09_08-59-40](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43215420/9a7d770b-3a59-428e-a4a6-727f1ca361e2)
![Snipaste_2024-04-09_08-51-10](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43215420/bccaecbf-a66f-47c7-a615-e3e14f6a4d3c)
2.自动战斗页面:
![Snipaste_2024-04-09_09-00-00](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43215420/eda38899-8faa-4c88-a4fd-9641c03a6964)
3.小工具页面:
![Snipaste_2024-04-09_09-00-09](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43215420/63d5dbed-5c6a-4984-9a0d-582a9f8da358)
4.设置页面点击就报错崩溃:
![Snipaste_2024-04-09_09-00-23](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43215420/85caf746-1425-4691-9dad-2367ffc7688e)

### 还有别的吗？

点击设置页签时候的报错信息
[报错信息.md](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14912246/default.md)

**Comment by ABA2396** [comment]
#8755

**Comment by ABA2396** [comment]
之前版本每个配置文件是分开的，遇到了别点设置直接右上角叉掉重启一下就好了
