### ISSUE TITLE
干员识别未能正确识别黍

### ISSUE THREAD

**Issue by wonder041** [MaaAssistantArknights/MaaAssistantArknights#8801]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

干员识别未能正确识别黍

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

2024-04-09 13:22:22.751 开始干员识别
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14913797/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14913798/gui.log)
[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14913782/oper.zip)

### 截图
![2024-04-09_13-22-32-186_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/19471830/c106c234-8541-4c33-b870-39faf82ffb11)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/19471830/8790b1cf-16b2-4755-958b-0c79de7bfb2d)

### 还有别的吗？

蓝叠国际版 5.12.102.1001
Windows 10 企业版 22H2 19045.4170

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/2b9254ea-88d0-4fd0-b4a9-0a5fea4fdd07)
识别错了还好说，这连字都没识别到就没办法了
cc @MistEO
