### ISSUE TITLE
快速更新

### ISSUE THREAD

**Issue by chesha1** [MaaAssistantArknights/MaaAssistantArknights#8809]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

每次 maa 更新都要走完 18/18，而且速度很慢，这个是下载过程还是 maa 本体的更新过程，能否快一点

**Comment by ABA2396** [comment]
这个是检查资源更新，比如活动地图、干员数据、公招信息等，不影响正常任务，直接开始任务不管就行。如果开了自动安装的话会在任务结束后重启，如果没开下次启动加载也无所谓
