### ISSUE TITLE
未知原因闪退

### ISSUE THREAD

**Issue by desktop4025** [MaaAssistantArknights/MaaAssistantArknights#881]
我是在一直开着的主机上设的定时刷，但是我这次上来看的时候发现停留在结算页面，然后软件也关闭了，原因未知。
[Desktop.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8901220/Desktop.zip)

**Comment by weedi0** [comment]
同点击更新闪退

**Comment by MistEO** [comment]
v3.9.9 这部分逻辑改了一点，~~但不知道有没有用~~

**Comment by MistEO** [comment]
这部分修改了一些，先关了，后面如果还在再来个日志看看
