### ISSUE TITLE
更新完游戏资源重启maa显示“资源损坏，请重新下载完整安装包”

### ISSUE THREAD

**Issue by 3ySuk1** [MaaAssistantArknights/MaaAssistantArknights#8810]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新完游戏资源重启maa显示“资源损坏，请重新下载完整安装包”

### Version

5.2.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14942349/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14942351/gui.log)

### 截图

![QQ截图20240411144217](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106969011/d900967e-2caa-4790-be5f-f7bcd0754c11)

**Comment by HoshinoAyako** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/145320853/ae308ca2-2e66-4026-b3c9-d4790a1a1da8)
这四个图标文件，是这次新增的。估计是没下载成功。你去把这四个文件手动下载到resource\template\infrast里就行

**Comment by 3ySuk1** [comment]
> ![image](https://private-user-images.githubusercontent.com/145320853/321529669-ae308ca2-2e66-4026-b3c9-d4790a1a1da8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MTg3OTAsIm5iZiI6MTcxMjgxODQ5MCwicGF0aCI6Ii8xNDUzMjA4NTMvMzIxNTI5NjY5LWFlMzA4Y2EyLTJlNjYtNDAyNi1iM2M5LWQ0NzkwYTFhMWRhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwNjU0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDczNmMwMzI3OGU4ZDExYzBjNWNlNTZhNjI5OGQxNDlhNWI2N2ZmNTAxMTAwZDgyYmE4MjRjNzIyMTk5ZjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XJHGnKVqxBEO6YxEUcAFBTuMbv51VZjQsJ5A2YQzaV4) 这四个图标文件，是这次新增的。估计是没下载成功。你去把这四个文件手动下载到resource\template\infrast里就行

已解决
