### ISSUE TITLE
生息演算任务出错: ReclamationAlgorithm

### ISSUE THREAD

**Issue by sakana155** [MaaAssistantArknights/MaaAssistantArknights#8812]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

生息演算过完剧情后进入第一个关卡后报任务出错:ReclamationAlgorithm

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.1-beta.1.d072.g4c505faa8
Core Version: v5.2.1-beta.1.d072.g4c505faa8

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14945097/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14945099/gui.log)

### 截图

![QQ截图20240411184623](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124866649/5c0c3ee1-0b08-4e47-b897-b1f113ac3dd8)
![QQ截图20240411184631](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/124866649/a7d9e323-613a-49c5-8b62-987231796649)

### 还有别的吗？

mumu模拟器12,：版本 :V3.8.11 (2788)
操作系统Windows10专业版22h2
显卡：NVIDIA GeForce GTX1050 Ti
cpu：Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/c7712ce7-2106-4b72-a10e-13b108069b82)
