### ISSUE TITLE
mac版本经常提示“不支持的关卡，请更新 MAA 软件版本！”

### ISSUE THREAD

**Issue by 281069483** [MaaAssistantArknights/MaaAssistantArknights#8813]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

mac版本经常提示“不支持的关卡，请更新 MAA 软件版本！”。已经是最新的了，但是还是提示这个，然后要等好久，等更新了下一个版本后才能用。是不是mac版本总是落后于windows的版本？有没有别的办法能解决这个问题。

**Comment by ABA2396** [comment]
@hguandl 正在做 mac 的热更新 ~~（大概）~~
但是好像最近比较忙

**Comment by 281069483** [comment]
谢谢，辛苦大佬了，期待早日更新。

**Comment by kingwhite1216** [comment]
如果没有办法做好热更，能不能就上一个只更新地图资源的那种版本，只是想抄个作业……
上次彩6新活动ex关，还有引航者试炼，一直在等地图更新，最后等到活动快结束了都没有更新，只好最后几天临时手动补。
这次新活动也差不多第三天了，也没有更，新图打不了那只能手操吧，让maa打老图，都要注意把新干员在编队下了
知道各位开发都很辛苦，但这实在是有些影响体验了

**Comment by Saratoga-Official** [comment]
有一个临时解决方法，如果maa的win内测版已经更新地图了的话，就下载一份win内测版，然后把里面的资源文件夹放到mac里面就能用了，如果win内测版也没更新就不行

**Comment by 281069483** [comment]
> 有一个临时解决方法，如果maa的win内测版已经更新地图了的话，就下载一份win内测版，然后把里面的资源文件夹放到mac里面就能用了，如果win内测版也没更新就不行

感谢大佬，亲测有效，非常感谢！

**Comment by 281069483** [comment]
Mac版的小伙伴可以试下@kingwhite1216

**Comment by 947140185** [comment]
确实能解决

以及如果身边有人用win版的话等ta热更完要一份resource直接替换mac同名文件就行

**Comment by donlv1997** [comment]
> 有一个临时解决方法，如果maa的win内测版已经更新地图了的话，就下载一份win内测版，然后把里面的资源文件夹放到mac里面就能用了，如果win内测版也没更新就不行

感谢，一直想用mac抄作业（石头想搞到IOS端）

**Comment by Saratoga-Official** [comment]
现在这个是不是可以关了，win都取消热更了，可以直接使用＃10033的方法
