### ISSUE TITLE
刷理智没有新关卡

### ISSUE THREAD

**Issue by Dyinglight5** [MaaAssistantArknights/MaaAssistantArknights#8814]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

maa能更新，但是刷不出来新关卡的索引

### Version

UI Version: v5.2.1-beta.1
Resource Version: 巴别塔
Core Version: v5.2.1-beta.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14952663/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14952665/gui.log)
上个活动就有这个问题，今天活动更新了发现还是不行

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150124520/55efbdc0-891f-474a-a90f-c31ab05a7b9b)

### 还有别的吗？

mumu模拟器
windows11

**Comment by AnnAngela** [comment]
关闭MAA，进入MAA所在文件夹，删掉cache文件夹后重新运行MAA即可

**Comment by ABA2396** [comment]
> 关闭MAA，进入MAA所在文件夹，删掉cache文件夹后重新运行MAA即可

他这是连不上ota.maa.plus，没办法访问到api

**Comment by ABA2396** [comment]
看着就4.3号上午连上过一次，之后就没成功过了，这用的是啥网络

**Comment by AnnAngela** [comment]
要不让他把配置文件里的 `ota.maa.plus` 换成 `maa-ota.annangela.cn`

**Comment by ABA2396** [comment]
> 要不让他把配置文件里的 `ota.maa.plus` 换成 `maa-ota.annangela.cn`

不是资源，是api，镜像不提供这个

**Comment by WeiyeShao** [comment]
我从很早的版本开始就有这个问题了，经常是一个活动结束了都不一定能刷出新关卡

**Comment by Dyinglight5** [comment]
> 我从很早的版本开始就有这个问题了，经常是一个活动结束了都不一定能刷出新关卡

我是挂上代理再进去就刷出来了，如果你原来开过代理可能是这个原因

**Comment by WeiyeShao** [comment]
您好，您的邮件已收到，我会尽快处理并给您回复。邵伟业

**Comment by WeiyeShao** [comment]
> > 我从很早的版本开始就有这个问题了，经常是一个活动结束了都不一定能刷出新关卡
> 
> 我是挂上代理再进去就刷出来了，如果你原来开过代理可能是这个原因

还真的是，这个有办法重置吗

**Comment by Dyinglight5** [comment]
> > > 我从很早的版本开始就有这个问题了，经常是一个活动结束了都不一定能刷出新关卡
> > 
> > 
> > 我是挂上代理再进去就刷出来了，如果你原来开过代理可能是这个原因
> 
> 还真的是，这个有办法重置吗

挂一次刷出来之后好像第二次就不用挂也能刷出来了

**Comment by WeiyeShao** [comment]
您好，您的邮件已收到，我会尽快处理并给您回复。邵伟业
