### ISSUE TITLE
訪問好友功能:會跳到好友頁面，但不會進去好友基建去拿取信用點，玩的是台版

### ISSUE THREAD

**Issue by hsd325** [MaaAssistantArknights/MaaAssistantArknights#8815]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

訪問好友功能:會跳到好友頁面，但不會進去好友基建去拿取信用點，玩的是台版

### Version

Resource Version: 尖滅測試作戰
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14953247/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14953248/asst.log)
時間為2024/4/12的上午9:50~10:14之間，大概是

### 还有别的吗？

使用的模擬器為MuMu12，版本為V3.8.13

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7ce43be8-6de2-46a1-8eb3-7acad7fc2e60)
卡在了这个界面？
看日志的得分很低，StartToVisit.png 的匹配得分普遍只有0.5到0.6
![StartToVisit](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/a15906b6-e849-4928-876a-ee570075ef98)

来个页面截图看看

**Comment by hsd325** [comment]
對的，是卡在這個頁面不會進去
![螢幕擷取畫面 2024-04-12 113457](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/100175482/9a9fcccc-7b17-4e31-b07b-d7a6ad249de1)
不過頁面好像跟你的不太一樣，我這是台版的頁面

**Comment by ABA2396** [comment]
用模拟器自带的截图，不然改不了

**Comment by hsd325** [comment]
好的，是這個嗎?
![MuMu12-20240412-115141](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/100175482/e24b2ebd-26c0-48d3-b52b-6889fbff7bba)

**Comment by ABA2396** [comment]
没太看懂为什么得分这么低，重新做了个模板
把
![StartToVisit](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/432ec98b-d34b-47e7-a3d5-e91962ee1340)
放到 `/resource/global/txwy/resource/template/` 文件夹里重启跑一下看看有没有用

**Comment by ABA2396** [comment]
cc @momomochi987

**Comment by momomochi987** [comment]
> momomochi987

收

我下班後再找時間看 🫠
