### ISSUE TITLE
生息演算任务出错ReclamationAlgorithm

### ISSUE THREAD

**Issue by Pinng999** [MaaAssistantArknights/MaaAssistantArknights#8816]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

每次开始任务到任务出错中间固定相隔15分钟左右，出错界面不确定（可能在刚开头、可能在进行下一天之前等非开始战斗场景），已确定队伍配置已清空，且其它设置符合要求

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.1-beta.1
Core Version: v5.2.1-beta.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14953428/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14953429/gui.log)
任务开始于04-12 10:13:11
任务出错于04-12 10:28:44

### 截图

<img width="600" alt="PixPin_2024-04-12_10-45-53" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108909863/e51dcdfe-b6e1-4f19-b28e-2ee9f8284200">

**Comment by DeparturePluto** [comment]
我出错时间在1分钟左右
![微信图片_20240412153745](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/101921030/cc5c1953-c973-4bbb-ad62-3f20a955403e)
![Uploading QQ截图20240412153731.png…]()

**Comment by DeparturePluto** [comment]
我也是，但是我是两分钟左右就出错

**Comment by labmen001nanodesu** [comment]
问题出现在第一天的第二场战斗，进入后就没反应了，正常情况应该进入战斗之后就退出
![937420490efb41e850ac34fbb1be733](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/167050683/b19a3d01-da1f-46bf-a403-d14f96d05b92)
![d99aead64f22a8bf08264a05cdc78ff](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/167050683/09985d3b-1e17-4c0b-816c-4b15e6d30c55)

**Comment by Brett6492** [comment]
> 问题出现在第一天的第二场战斗，进入后就没反应了，正常情况应该进入战斗之后就退出 ![937420490efb41e850ac34fbb1be733](https://private-user-images.githubusercontent.com/167050683/322346254-b19a3d01-da1f-46bf-a403-d14f96d05b92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTYyODQsIm5iZiI6MTcxMzE1NTk4NCwicGF0aCI6Ii8xNjcwNTA2ODMvMzIyMzQ2MjU0LWIxOWEzZDAxLWRhMWYtNDZiZi1hNDAzLWQxNGY5NmQwNWI5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwNDM5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzlhM2VjMTFlNzQyOWZhMDQzNTA3Y2MwNDQzZGY2ZTVlNjM0NzdkZTQzOGZiNzhhNWNkNWY0MDQ5OTc5NTQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aZjfNRQcPpvot92X808AHU4ALTrlZHosl52J7EZYGG0) ![d99aead64f22a8bf08264a05cdc78ff](https://private-user-images.githubusercontent.com/167050683/322346261-09985d3b-1e17-4c0b-816c-4b15e6d30c55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTYyODQsIm5iZiI6MTcxMzE1NTk4NCwicGF0aCI6Ii8xNjcwNTA2ODMvMzIyMzQ2MjYxLTA5OTg1ZDNiLTFlMTctNGMwYi04MTZjLTRiMTVlNmQzMGM1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwNDM5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2E0OTRhZDgyODBmY2NmNTU1ODdjYzJjMTk1NThjYjUwNmFiNTZmNDY3NjFjZmVhMWMwNTU2MGVjODEzMGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QvBN-Z4TVBkNpCQDDgG1vWLmB38_psR0na3Tpj13C90)

其他关卡都正常，是不是左上角的退出按钮和地块上的图案重叠导致的

**Comment by labmen001nanodesu** [comment]
> > 问题出现在第一天的第二场战斗，进入后就没反应了，正常情况应该进入战斗之后就退出![937420490efb41e850ac34fbb1be733](https://private-user-images.githubusercontent.com/167050683/322346254-b19a3d01-da1f-46bf-a403-d14f96d05b92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTYyODQsIm5iZiI6MTcxMzE1NTk4NCwicGF0aCI6Ii8xNjcwNTA2ODMvMzIyMzQ2MjU0LWIxOWEzZDAxLWRhMWYtNDZiZi1hNDAzLWQxNGY5NmQwNWI5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwNDM5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzlhM2VjMTFlNzQyOWZhMDQzNTA3Y2MwNDQzZGY2ZTVlNjM0NzdkZTQzOGZiNzhhNWNkNWY0MDQ5OTc5NTQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aZjfNRQcPpvot92X808AHU4ALTrlZHosl52J7EZYGG0) ![d99aead64f22a8bf08264a05cdc78ff](https://private-user-images.githubusercontent.com/167050683/322346261-09985d3b-1e17-4c0b-816c-4b15e6d30c55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTYyODQsIm5iZiI6MTcxMzE1NTk4NCwicGF0aCI6Ii8xNjcwNTA2ODMvMzIyMzQ2MjYxLTA5OTg1ZDNiLTFlMTctNGMwYi04MTZjLTRiMTVlNmQzMGM1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwNDM5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2E0OTRhZDgyODBmY2NmNTU1ODdjYzJjMTk1NThjYjUwNmFiNTZmNDY3NjFjZmVhMWMwNTU2MGVjODEzMGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QvBN-Z4TVBkNpCQDDgG1vWLmB38_psR0na3Tpj13C90)
> 
> 其他关卡都正常，是不是左上角的退出按钮和地块上的图案重叠导致的

还真是，进去之后我拖了一下地图就正常运行了，那应该怎么彻底解决这个问题

**Comment by ABA2396** [comment]
来张模拟器截的图，我看看重新做个模板有没有用

**Comment by labmen001nanodesu** [comment]
> 来张模拟器截的图，我看看重新做个模板有没有用

![d325d18cb0283f41925e619324605b9](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/167050683/7c4b9182-596a-4e8a-acd0-28bfa01034ab)
这样？

**Comment by labmen001nanodesu** [comment]
![MuMu12-20240415-153105](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/167050683/a5314914-a43f-47e1-887b-2b4753723797)
这是用模拟器自带的截图功能截的图

**Comment by 1127626014** [comment]
我会卡在这

**Comment by labmen001nanodesu** [comment]
> 来张模拟器截的图，我看看重新做个模板有没有用

![MuMu12-20240415-153105](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/167050683/59a72c00-99f2-4345-82c9-d10d888fbc17)
这是用模拟器自带的截图功能截的图

**Comment by 1127626014** [comment]
![Uploading Screenshot_20240415-152923.png…]()
我会卡在这

**Comment by 1127626014** [comment]
![Screenshot_20240415-152923](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57735361/e9d3fdd6-8124-40c3-a67a-12023ce4b38f)

**Comment by 1127626014** [comment]
![Screenshot_20240415-152923](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57735361/70417e40-4cc5-486c-9dd7-339bea840b96)
我会卡在这

**Comment by 1127626014** [comment]
> ![Screenshot_20240415-152923](https://private-user-images.githubusercontent.com/57735361/322392355-70417e40-4cc5-486c-9dd7-339bea840b96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjY5NTQsIm5iZiI6MTcxMzE2NjY1NCwicGF0aCI6Ii81NzczNTM2MS8zMjIzOTIzNTUtNzA0MTdlNDAtNGNjNS00ODZjLTlkZDctMzM5YmVhODQwYjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA3MzczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NThlZTUyMzlkMzdjNWMwNjRjMDZmMDJiMDE4MjhkNWM0ZTBmYzUyNDZhZTNhYTFkM2U2NTEyNTRjNWY5NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sE4XT8cbLoOU2GmWcydQwwnfHrBhONJB46paF8xZ0Hw) 我会卡在这

以前是没问题的

**Comment by ABA2396** [comment]
cc @status102 
这玩意都好久没变了，以前能跑照理来说现在也不会有区别

**Comment by ABA2396** [comment]
@labmen001nanodesu 试试看把这张图放到 \resource\template 然后重启下
![Reclamation2LeaveStage](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/36dde417-f901-4bff-ab4a-82d9adb3abe4)

**Comment by 1127626014** [comment]
> cc @status102 这玩意都好久没变了，以前能跑照理来说现在也不会有区别

我把ADB input换回Minitouch就又可以了，但是前几版本用ADB input可以

**Comment by DeparturePluto** [comment]
> @labmen001nanodesu 试试看把这张图放到 \resource\template 然后重启下 ![Reclamation2LeaveStage](https://private-user-images.githubusercontent.com/99072975/322394472-36dde417-f901-4bff-ab4a-82d9adb3abe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjgxNjMsIm5iZiI6MTcxMzE2Nzg2MywicGF0aCI6Ii85OTA3Mjk3NS8zMjIzOTQ0NzItMzZkZGU0MTctZjkwMS00YmZmLWFiNGEtODJkOWFkYjNhYmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA3NTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZmZmZmEyOGI5YTRhMWI3NjNkZDU5YTI2M2I0M2U5MmY4NTYyZjExYmVkNTgwOTQ4OTdmNzljOTIzNDcyYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kPm1Jnaf5XAdrvk7IHziIF-GJLnI_Ljbob0nnDlGbxo)

还是同样的情况，在第二个场景出现错误
![QQ截图20240415160243](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/101921030/b3d39198-d827-411d-9fc1-a10313433e8b)

**Comment by labmen001nanodesu** [comment]
> @labmen001nanodesu 试试看把这张图放到 \resource\template 然后重启下 ![Reclamation2LeaveStage](https://private-user-images.githubusercontent.com/99072975/322394472-36dde417-f901-4bff-ab4a-82d9adb3abe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjczNzYsIm5iZiI6MTcxMzE2NzA3NiwicGF0aCI6Ii85OTA3Mjk3NS8zMjIzOTQ0NzItMzZkZGU0MTctZjkwMS00YmZmLWFiNGEtODJkOWFkYjNhYmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA3NDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkOWMwMDYzNzZlOTFkNDk4YWNjODZkYWMzZjA1YjBiZWQ4YWEyNDI2NGJjM2QxMzM2NDQ3MTM2ODgyNjk5NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4eUutDsSPo6JiM2vmhIQY2qoPo4_rF4mnKG7g3ub1_s)

如果直接把图片拖进去的话没有效果，我尝试重命名替换掉旁边那个类似的文件时会导致第一场战斗也无法退出，同样拖一下就能识别上，第二场战斗也是如此，要不干脆加一个拖动的动作吧。

**Comment by labmen001nanodesu** [comment]
> @labmen001nanodesu 试试看把这张图放到 \resource\template 然后重启下 ![Reclamation2LeaveStage](https://private-user-images.githubusercontent.com/99072975/322394472-36dde417-f901-4bff-ab4a-82d9adb3abe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjczNzYsIm5iZiI6MTcxMzE2NzA3NiwicGF0aCI6Ii85OTA3Mjk3NS8zMjIzOTQ0NzItMzZkZGU0MTctZjkwMS00YmZmLWFiNGEtODJkOWFkYjNhYmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA3NDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkOWMwMDYzNzZlOTFkNDk4YWNjODZkYWMzZjA1YjBiZWQ4YWEyNDI2NGJjM2QxMzM2NDQ3MTM2ODgyNjk5NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4eUutDsSPo6JiM2vmhIQY2qoPo4_rF4mnKG7g3ub1_s)

如果直接把图片拖进去的话没有效果，我尝试重命名替换掉旁边那个类似的文件时会导致第一场战斗也无法退出，同样拖一下就能识别上，第二场战斗也是如此，要不干脆加一个拖动的动作吧。
![ed7bf1e73870c7ed0ed923868aebdee](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/167050683/e79135b8-c383-41c5-947c-62dfff830bef)

**Comment by labmen001nanodesu** [comment]
> > @labmen001nanodesu 试试看把这张图放到 \resource\template 然后重启下 ![Reclamation2LeaveStage](https://private-user-images.githubusercontent.com/99072975/322394472-36dde417-f901-4bff-ab4a-82d9adb3abe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjczNzYsIm5iZiI6MTcxMzE2NzA3NiwicGF0aCI6Ii85OTA3Mjk3NS8zMjIzOTQ0NzItMzZkZGU0MTctZjkwMS00YmZmLWFiNGEtODJkOWFkYjNhYmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA3NDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkOWMwMDYzNzZlOTFkNDk4YWNjODZkYWMzZjA1YjBiZWQ4YWEyNDI2NGJjM2QxMzM2NDQ3MTM2ODgyNjk5NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4eUutDsSPo6JiM2vmhIQY2qoPo4_rF4mnKG7g3ub1_s)
> 
> 如果直接把图片拖进去的话没有效果，我尝试重命名替换掉旁边那个类似的文件时会导致第一场战斗也无法退出，同样拖一下就能识别上，第二场战斗也是如此，要不干脆加一个拖动到地图最左上的动作吧。 ![ed7bf1e73870c7ed0ed923868aebdee](https://private-user-images.githubusercontent.com/167050683/322401345-e79135b8-c383-41c5-947c-62dfff830bef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjg2ODcsIm5iZiI6MTcxMzE2ODM4NywicGF0aCI6Ii8xNjcwNTA2ODMvMzIyNDAxMzQ1LWU3OTEzNWI4LWMzODMtNDFjNS05NDdjLTYyZGZmZjgzMGJlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwODA2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmZhYmVmMDY1ZjNmNzRlY2Q3NTYwYjUxN2Y4MjBkZDIyNzc0NjNmYTFlNTgwMDJlY2NlNTc2MTM2YWRiYmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EVPeRKZoIM8rHsPTAsXQjSP7VRLAscg7NoI3SyoTDB4)

**Comment by status102** [comment]
log看着有点奇怪，卡演算首页了，0.65，而且15次之后甚至没有score了（有屏蔽？

```
[2024-04-12 10:28:39.772][TRC][Px128c][Tx29f8] asst::ProcessTask::_run | enter
[2024-04-12 10:28:39.772][INF][Px128c][Tx29f8] {"class":"asst::ProcessTask","details":{"cur_retry":15,"retry_times":20,"to_be_recognized":["Reclamation2BeginPlot"]},"first":["Reclamation2BeginPlotEnterLoading@Reclamation2Begin"],"pre_task":"Reclamation2BeginPlotLoading","subtask":"ProcessTask","taskchain":"ReclamationAlgorithm","taskid":1}
[2024-04-12 10:28:39.944][INF][Px128c][Tx29f8] Call ` E:\MuMuPlayer-12.0\shell\.\adb.exe -s 127.0.0.1:16416 exec-out "screencap | nc -w 3 10.0.2.2 12561" ` ret 0 , cost 172 ms , stdout size: 0 , socket size: 5760016
[2024-04-12 10:28:39.949][TRC][Px128c][Tx29f8] asst::PipelineAnalyzer::analyze Reclamation2BeginPlot
[2024-04-12 10:28:39.951][TRC][Px128c][Tx29f8] match_templ | Reclamation2BeginPlot.png score: 0.655089 rect: [ 56, 53, 44, 43 ] roi: [ 0, 0, 100, 100 ]
[2024-04-12 10:28:39.951][TRC][Px128c][Tx29f8] asst::ProcessTask::_run | leave, 179 ms
[2024-04-12 10:28:39.951][TRC][Px128c][Tx29f8] ready to sleep 500
[2024-04-12 10:28:40.452][TRC][Px128c][Tx29f8] end of sleep 500
[2024-04-12 10:28:40.452][TRC][Px128c][Tx29f8] asst::ProcessTask::_run | enter
[2024-04-12 10:28:40.452][INF][Px128c][Tx29f8] {"class":"asst::ProcessTask","details":{"cur_retry":16,"retry_times":20,"to_be_recognized":["Reclamation2BeginPlot"]},"first":["Reclamation2BeginPlotEnterLoading@Reclamation2Begin"],"pre_task":"Reclamation2BeginPlotLoading","subtask":"ProcessTask","taskchain":"ReclamationAlgorithm","taskid":1}
[2024-04-12 10:28:40.639][INF][Px128c][Tx29f8] Call ` E:\MuMuPlayer-12.0\shell\.\adb.exe -s 127.0.0.1:16416 exec-out "screencap | nc -w 3 10.0.2.2 12561" ` ret 0 , cost 187 ms , stdout size: 0 , socket size: 5760016
[2024-04-12 10:28:40.645][TRC][Px128c][Tx29f8] asst::PipelineAnalyzer::analyze Reclamation2BeginPlot
[2024-04-12 10:28:40.646][TRC][Px128c][Tx29f8] asst::ProcessTask::_run | leave, 194 ms
[2024-04-12 10:28:40.646][TRC][Px128c][Tx29f8] ready to sleep 500
[2024-04-12 10:28:41.147][TRC][Px128c][Tx29f8] end of sleep 500
[2024-04-12 10:28:41.147][TRC][Px128c][Tx29f8] asst::ProcessTask::_run | enter
[2024-04-12 10:28:41.147][INF][Px128c][Tx29f8] {"class":"asst::ProcessTask","details":{"cur_retry":17,"retry_times":20,"to_be_recognized":["Reclamation2BeginPlot"]},"first":["Reclamation2BeginPlotEnterLoading@Reclamation2Begin"],"pre_task":"Reclamation2BeginPlotLoading","subtask":"ProcessTask","taskchain":"ReclamationAlgorithm","taskid":1}
[2024-04-12 10:28:41.476][INF][Px128c][Tx29f8] Call ` E:\MuMuPlayer-12.0\shell\.\adb.exe -s 127.0.0.1:16416 exec-out "screencap | nc -w 3 10.0.2.2 12561" ` ret 0 , cost 329 ms , stdout size: 0 , socket size: 5760016
[2024-04-12 10:28:41.481][TRC][Px128c][Tx29f8] asst::PipelineAnalyzer::analyze Reclamation2BeginPlot
[2024-04-12 10:28:41.483][TRC][Px128c][Tx29f8] asst::ProcessTask::_run | leave, 336 ms
```

**Comment by Lyricistys** [comment]
生息演算蓝叠模拟器每次挂半个小时左右稳定闪退是因为什么呀
