### ISSUE TITLE
自动肉鸽，在没有抗干扰的情况下尝试拐弯

### ISSUE THREAD

**Issue by yltx** [MaaAssistantArknights/MaaAssistantArknights#8822]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA在0抗的情况下想拐弯，然后提示抗干扰不够，但是MAA仍然坚定的往下拐
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/37734213/99788b3e-3cb1-4085-af52-7d14f3d4299f)
之前反馈过在抗不足的时候在得偿所愿尝试选高阶藏品，应该跟那个是一个问题。

### Version

Resource Version: 巴别塔
UI Version: v5.2.1-beta.1.d072.g4c505faa8
Core Version: v5.2.1-beta.1.d072.g4c505faa8

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14969519/asst.zip)
从今早0点一直到下午接近一点，一直都是这个问题卡着在

**Comment by Lancarus** [comment]
fix in #9223
