### ISSUE TITLE
请问能否增加bb-4的选择？

### ISSUE THREAD

**Issue by missy-yan** [MaaAssistantArknights/MaaAssistantArknights#8824]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

无

### 有什么好的想法？

无

### 其他内容

无

**Comment by D3adEr1c** [comment]
大部分博士的需求为刷取蓝材料，有其他需求请自行通过手动输入关卡设置 
点击 刷理智 旁边设置符号→
点击高级设置 →
勾选手动输入关卡名 →
点击常规设置 →
在关卡选择处填写 BB-4

**Comment by ABA2396** [comment]
> 大部分博士的需求为刷取蓝材料，有其他需求请自行通过手动输入关卡设置 点击 刷理智 旁边设置符号→ 点击高级设置 → 勾选手动输入关卡名 → 点击常规设置 → 在关卡选择处填写 BB-4

bb-4不支持导航，要么就用当前/上次刷
