### ISSUE TITLE
无法上传战斗结果

### ISSUE THREAD

**Issue by maidangdang1** [MaaAssistantArknights/MaaAssistantArknights#8826]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

关卡：BB-8
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46847241/e709b22b-365d-49a3-bc84-a4772df2b5e6)

### Version

Resource Version: 巴别塔
UI Version: v5.2.1-beta.1
Core Version: v5.2.1-beta.1

### 日志文件

2024-04-15 01:25:06
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14971576/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14971577/gui.log)

### 截图

`debug/drops`
![2024-04-15_01-32-09-387_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46847241/a1b35fd0-4356-4e1b-a5cd-279ce4b7be83)
![2024-04-15_01-34-29-154_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46847241/f68d802d-d802-4f64-9930-febcc67d59e2)
![2024-04-15_01-29-48-315_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46847241/38aefd3a-a4f1-4462-aaca-1eaefb695d65)

**Comment by MoXiaoX** [comment]
同样出现此问题，很神秘

**Comment by status102** [comment]
asst.log不包含故障时间段，检查asst.bak.log

**Comment by Daydreamer114** [comment]
哈哈哈哈终于有人反馈了

**Comment by maidangdang1** [comment]
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14974395/asst.bak.log)

**Comment by ABA2396** [comment]
没看懂，把\cache\etag.json删了试试

**Comment by maidangdang1** [comment]
可以了😀
