### ISSUE TITLE
获取信用及购物的功能有bug

### ISSUE THREAD

**Issue by kcsocrat** [MaaAssistantArknights/MaaAssistantArknights#8828]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

一键长草中如果多个选用任务的情况下，每次到获取信用及购物的时候都会跳过好友访问基建的那个流程，直接到商店换东西，只有单选这个任务的时候才会访问基建，希望修改一下

### Version

Core Version: v5.2.0

### 日志文件

应该是4-15 的11点35分后

**Comment by kcsocrat** [comment]
[Uploading debug.zip…]()

**Comment by ABA2396** [comment]
已经修了，正式版还没发

**Comment by kcsocrat** [comment]
> 已经修了，正式版还没发

好的
