### ISSUE TITLE
萨米肉鸽刷等级会因为检测到存款达到999导致结束刷等级任务

### ISSUE THREAD

**Issue by gugugu1145** [MaaAssistantArknights/MaaAssistantArknights#8830]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

打开的是萨米肉鸽刷等级的选项，但是到了商店层会因为源石锭达到上限而直接停止，并提示任务已完成
![QQ图片20240415115525](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/167051143/ef9a5ba0-44f4-461d-8006-2d006e5a0d4d)

### Version

Core Version: v5.2.0

### 日志文件

时间为2024/4/15 11.45-11.50
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14973790/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14973791/gui.log)

**Comment by ABA2396** [comment]
设置里自己关

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/6995f721-cd06-4f7e-8cb8-fe3a1afca36a)
