### ISSUE TITLE
海外热更新下载缓慢

### ISSUE THREAD

**Issue by hifocus** [MaaAssistantArknights/MaaAssistantArknights#8833]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

热更新域名 `ota.maa.plus` 在海外更新的时候下载缓慢，每次可能都要 2 分钟才能下载好。

### 有什么好的想法？

能不能套层 CloudFlare 加个海外 CDN 海外节点，加速一下海外热更新速度。

也可以考虑使用对象存储，或者干脆多加一个 GitHub Release...总之能有很多方法，乐意提供协助。

### 其他内容

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30528433/37f44943-d8b0-4814-9330-bf25b374c10f)

**Comment by ABA2396** [comment]
只有api是走的ota，热更大概率走的是镜像，应该连不到ota去吧？

**Comment by hifocus** [comment]
奇怪了，看 DNS log 确实看到 r2 对象存储 `maa.r2.imgg.dev` 这个域名。

另外提醒一下 `ota.maa.plus` 用的是 TrustAsia 免费一年证书，这个证书很快就不提供一年时长的了，可能需要尽早设置个 certbot 或者 acme.sh 自动续期。

**Comment by hifocus** [comment]
![MAA_IDkeLDjAwJ](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30528433/5893c4d6-7655-4439-9428-055444a0bbf2)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/30528433/c1726fc5-dd1a-4779-8d4c-c7d36e16a2a4)

实际更新体验如上所示。下载 v5.0.0 然后更新到最新版本的日志如下：

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14975694/gui.log)

看上去请求了一堆 json，虽然还是很难理解为什么 r2 请求几十个文件会这么慢（可能是因为缓存的问题？），但是是否有可能这些 json 也版本控制，每次直接下载一个压缩包然后本地解压？r2 是按请求数计费的，不知道免费的计划够不够这么多用户的项目用，但是这么做有助于降低请求数。

无论如何很感谢开发和维护项目♥

**Comment by ABA2396** [comment]
这个倒不是海外热更新慢了~~而是这里限速了，所有人更新都是一秒一跳~~ maa-ota.annangela.cn 和 s3.maa-org.net 都有设 QPS
反正这个更新是下载地图资源和干员数据之类的东西，不影响正常的任务，下次启动时重启也没关系
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/ae58248a-acdf-4114-a63e-72c9688702a5)

**Comment by hifocus** [comment]
懂了，只不过强迫症比较容易犯

Thanks for answering!
