### ISSUE TITLE
ui和core版本不一致

### ISSUE THREAD

**Issue by Tabshhh** [MaaAssistantArknights/MaaAssistantArknights#8836]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/54019007/d960fbed-f6f0-4fd7-8946-46dc763854fe)
ui和core版本不一致，更新也一直没法一致，不知道该如何解决，是否删除重装可以解决？（因为看说不要手动替换，不知道重装是否会有数据残留）

### Version

UI版本v5．0．0
Core本号5．2．1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14981249/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14981250/gui.log)

**Comment by ABA2396** [comment]
你这怎么从5.1开始就一直报了，是不是更新的时候后台还开着另一个maa

**Comment by Tabshhh** [comment]
> 你这怎么从5.1开始就一直报了，是不是更新的时候后台还开着另一个maa

是的是的、、一直是两个maa一起用，这样会有影响是吗？

**Comment by ABA2396** [comment]
就比如你开了A、B两个maa，A在更新的时候要替换MAA.exe这个文件，但B还开着，文件就被B占用了，A就不能覆盖掉这个文件，更新就失败了

多开的情况参考 [链接](https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.html#%E8%87%AA%E5%8A%A8%E5%90%AF%E5%8A%A8%E5%A4%9A%E5%BC%80%E6%A8%A1%E6%8B%9F%E5%99%A8) 若需要多开模拟器同时操作，可将 MAA 文件夹复制多份，使用 不同的 MAA、同一个 adb.exe、不同的连接地址 来进行连接。

**Comment by Tabshhh** [comment]
> 就比如你开了A、B两个maa，A在更新的时候要替换MAA.exe这个文件，但B还开着，文件就被B占用了，A就不能覆盖掉这个文件，更新就失败了
> 
> 多开的情况参考 [链接](https://maa.plus/docs/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.html#%E8%87%AA%E5%8A%A8%E5%90%AF%E5%8A%A8%E5%A4%9A%E5%BC%80%E6%A8%A1%E6%8B%9F%E5%99%A8) 若需要多开模拟器同时操作，可将 MAA 文件夹复制多份，使用 不同的 MAA、同一个 adb.exe、不同的连接地址 来进行连接。

我是复制了两个maa，在同一个顶层文件夹的不同子文件夹下面的两个maa，按照“不同的 MAA、同一个 adb.exe、不同的连接地址”连接的，不知道是否是因为直接复制的文件夹，所以两个maa的源是一样的？如果是这样的话，是不是应该重新从压缩包解压呢？

**Comment by ABA2396** [comment]
直接下最新的完整包覆盖安装下吧

**Comment by Tabshhh** [comment]
> 直接下最新的完整包覆盖安装下吧

好的谢谢您
