### ISSUE TITLE
Copilot: skip story not working (EN & KR)

### ISSUE THREAD

**Issue by xczsonn** [MaaAssistantArknights/MaaAssistantArknights#8845]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8644 에서 다뤘고
5.2.1 update note에서 수정되었다고 표기되어 있지만 MAA는 여전히 전투 전에 나오는 스토리에서 SKIP을 누르지 않습니다.
1280x720 dpi320, 1920x1080 dpi320 에서 테스트 해보았지만 모두 인식되지 않았습니다.
아래 스크린샷과 로그는 한국 서버에 업데이트 된 13-2에서의 1920x1080 스크린샷과 로그입니다.

<hr>

addressed this in #8644 and it is marked as fixed in the 5.2.1 update note, but MAA still does not skip the story before combat. I tested it on 1280x720 dpi320 and 1920x1080 dpi320, but it was not recognized in either. Below are the screenshots and logs from the Korean server update 13-2, taken at 1920x1080

### Version

Resource Version: 분쟁 연의
UI Version: v5.2.1
Core Version: v5.2.1

### 日志文件

[debug_2.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15001920/debug_2.zip)

### 截图

![Screenshot_20240417-044527](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12751277/040b9c72-e440-4ee6-a05a-c6ccdcf8d1ae)

### 还有别的吗？

LD Player Windows 11

**Comment by HX3N** [comment]
Could the low recognition rate of the image, being below 0.8, be the reason? The recognition rate doesn't appear in the log

<details><summary>log</summary>

```
[2024-04-17 04:44:29.955][TRC][Px8fc][Tx5314] asst::PipelineAnalyzer::analyze SkipThePreBattlePlot
[2024-04-17 04:44:29.955][INF][Px8fc][Tx5314] asst::TemplResource::get_templ lazy load SkipThePreBattlePlot.png
[2024-04-17 04:44:29.966][TRC][Px8fc][Tx5314] asst::PipelineAnalyzer::analyze Stop
```
</details>

**Comment by Argonautes0607** [comment]
EN服抄作业同样不会跳过故事

**Comment by Constrat** [comment]
@Argonautes0607 I was trying yesterday to fix this, but I didn't have enough time. I'll see what I can do later.

**Comment by Constrat** [comment]
I'm fairly certain the issue is in the delay during the loading 3000 ms doesn't seem to be enough.
After using both CN and Global, the CN seems to be more optimized with the loading times. Tested both Mumu and Bluestacks on 64 bit system. I'll try and see if increasing to 5000 ms fixes it (in the hope of not breaking anything else)
