### ISSUE TITLE
[YostarEN] auto combat doesn't function properly on chapter 13

### ISSUE THREAD

**Issue by BlackNorton** [MaaAssistantArknights/MaaAssistantArknights#8849]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

Try to farm 13-15 adverse and it only run one time then stop at the operator selection screen.

### Version

Resource Version: From Gleams And Smoke I Emerge
UI Version: v5.2.1
Core Version: v5.2.1

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15009053/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15009054/gui.log)

### Screenshots

![Screenshot_2024 04 17_02 27 19 639](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/65427501/9880c708-d176-49bc-b87e-64a7f73c349f)

### Anthing else?

BlueStacks 5.0.230.1001 N32, 1920x1080, 320 dpi

**Comment by Constrat** [comment]
@BlackNorton Do me a favor and try again replacing this png:
MaaAssistantArknights\resource\global\YoStarEN\resource\template
![StartButton2Adverse](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/a5c1a3f7-cd12-4186-b914-7c7a76f6f1d6)

**Comment by Constrat** [comment]
Ok I can also replicate this. No need for further discussion on this issue.
I'll start working on it on my own.

**Comment by BlackNorton** [comment]
> Strange that it only happens on Chapter 13, have you tried previous chapters?

Yeah I use MAA on a daily base for farming 1-7 or CE-6, no problem with these old levels. It's possible that the adverse mode mission start button is causing the issue. So I only change the png for adverse mode on both "StartButton2Adverse.png" and "BattleStartAdverse.png", it's working now and I've run 12 cycles without any issues.

**Comment by Constrat** [comment]
From the looks of the errors, @BlackNorton changing only the adverse one shouldn't have made any difference, as this seems a problem with the "normal" start button
