### ISSUE TITLE
Does not function with new menu themes

### ISSUE THREAD

**Issue by Antivash** [MaaAssistantArknights/MaaAssistantArknights#8852]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

With the release of chapter 13 and the UI updates, MAA doesn't function with any of the non-default themes. 

### Version

Core Version: v5.2.1
UI Version: v5.2.1
Resource Version: From Gleams And Smoke I Emerge

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15013073/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15013074/gui.log)

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/336178/e5f4d78b-2908-4f44-9302-06464c192d74)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/336178/1eefe80e-dee9-442b-b674-4716d5201fce)

**Comment by Constrat** [comment]
Give me some time to implement them.
