### ISSUE TITLE
建议：关卡/材料次数累计功能

### ISSUE THREAD

**Issue by Kyusumi** [MaaAssistantArknights/MaaAssistantArknights#8853]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

比如遇到活动关卡，我有很多次太过于依赖maa的自动战斗，且忙于生活中的事情而疏于关注是否在活动中刷够了代币，导致代币溢出只能兑换少量龙门币，而因此浪费的理智点也弥足珍贵。

### 有什么好的想法？

因为每一次能够支持自动刷理智的理智量并不多，刷够一次活动代币需要多次自动战斗和统计，如果可以的话希望可以每一次操作结束后统计本次所刷代币数，并且加和之前几次操作刷的代币数，最终统计是否达到所设定的代币数；如果无法实现，也可以人工干预，偶尔上线看看还差多少代币可以搬空商店，并在最后一次设定一个所需的量，以防止理智浪费（主要想搓玉）。此功能也可以放在平时刷材料，比如需要八个大芯片，五个某材料等。

### 其他内容

如果此建议已有人提出，那很抱歉浪费了你们的工作时间，如果此建议不太合理，欢迎交流沟通。第一次上传需求建议，如有不合规的地方请谅解并指正，谢谢。

**Comment by AnnAngela** [comment]
指定材料有了：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/9762652/b802a2d3-fe5b-4ba5-be53-1098212bbf7e)
代币的话要问问其他人

**Comment by ABA2396** [comment]
代币和理智强相关，算这个还不如算关卡次数

**Comment by Kyusumi** [comment]
> 指定材料有了： ![image](https://private-user-images.githubusercontent.com/9762652/323427673-b802a2d3-fe5b-4ba5-be53-1098212bbf7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDc2MzksIm5iZiI6MTcxMzQwNzMzOSwicGF0aCI6Ii85NzYyNjUyLzMyMzQyNzY3My1iODAyYTJkMy1mZTViLTRiYTUtYmU1My0xMDk4MjEyYmJmN2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMDIyODU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODMwOTdkZDk0NzZkNmViYmQ3MjZiYzVjZjM5YTkyMzQ4ZWEzNDNiZTgxNjE0OGFmMTcwMWRlMzRjNDdhMWU2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pHPvHTyPEzOC95lh7LXq9Ld7L7uMqQSpC-7jrYAWUkw) 代币的话要问问其他人

但现在面临的问题是指定材料刷到一个即停止，如果需要刷若干个指定材料的话还是需要人工干预

**Comment by Kyusumi** [comment]
> 代币和理智强相关，算这个还不如算关卡次数

这么一说确实，直接计算关卡次数，但是如果能有统计历史积攒的代币数量的功能就好了

**Comment by ntgmc** [comment]
Duplicate of #7454
