### ISSUE TITLE
每次开机使用MAA只能连接一次模拟器，再次连接就需要重启电脑

### ISSUE THREAD

**Issue by StarWC** [MaaAssistantArknights/MaaAssistantArknights#8854]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用mumu12模拟器，在使用MAA连接后选择了自动退出MAA与模拟器，过了十几个小时第二次打开MAA选择连接，提示“连接失败请检查连接设置或尝试重启模拟器与ADB或重启电脑”这个情况持续了好久了，每次都需要重启电脑才能开刷就很烦

### Version

Resource Version: 巴别塔
UI Version: v5.2.1
Core Version: v5.2.1

### 日志文件

[Uploading gui.log…]()
[Uploading asst.log…]()
出现时间点是4月18日00:15

### 截图

![Uploading image.png…]()

### 还有别的吗？

模拟器：MUMU模拟器12
系统：windows11专业版

**Comment by StarWC** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15014358/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15014359/asst.log)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49085785/027bdeec-42fb-4a86-be18-aae3719a0c67)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/7ff444fa-2ba4-4119-94e1-cb2959d13bff)
有开过加速器/手机助手之类的东西吗

**Comment by ABA2396** [comment]
https://mumu.163.com/help/20240321/35047_1144608.html

**Comment by 610807421** [comment]
有可能是adb的一个连接断开错误问题（但我是一两个月才会碰到一次）
下次试试退出maa后在adb的位置启动cmd，输入“adb devices"，看看显示是在连接状态还是断开状态。
有时候模拟器已经关闭了，连接却没有断开，会导致端口被占用，adb就连接失败了。
手动”adb disconnect 目标端口“然后”adb connect 目标端口“可以单次解决问题。

如果是这个原因导致的，可以尝试在”连接设置“里把”连接失败后尝试重启ADB server“&”退出时释放ADB"勾选上

**Comment by ABA2396** [comment]
> 有可能是adb的一个连接断开错误问题（但我是一两个月才会碰到一次） 下次试试退出maa后在adb的位置启动cmd，输入“adb devices"，看看显示是在连接状态还是断开状态。 有时候模拟器已经关闭了，连接却没有断开，会导致端口被占用，adb就连接失败了。 手动”adb disconnect 目标端口“然后”adb connect 目标端口“可以单次解决问题。
> 
> 如果是这个原因导致的，可以尝试在”连接设置“里把”连接失败后尝试重启ADB server“&”退出时释放ADB"勾选上

他日志里是connection reset，大概率是代理之类的问题

**Comment by StarWC** [comment]
确实是开着加速器，我之后试试勾上那个重启adb的选项

**Comment by ABA2396** [comment]
> 确实是开着加速器，我之后试试勾上那个重启adb的选项

重启adb没用的，要么照着文档里说的启停加速器后重启maa、adb、模拟器后重新连接，要么指定加速器使用路由模式后重启电脑
