### ISSUE TITLE
mumu12模拟器连接异常

### ISSUE THREAD

**Issue by a0wsxz9** [MaaAssistantArknights/MaaAssistantArknights#8859]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在最近的稳定版中一直存在连接失败的问题，需要手动执行adb disconnect 断开操作，虽然adb看似已经没有连接了，但是依然需要进行如此进行一次操作，maa才能连接上，具体原因未查明。

在之前issue中就遇到过，[夜神模拟器、mumu12模拟器adb连接失败 #7516](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/7516)其中610807421提出了解决办法，我也亲测可用，后面发生频率不算高就没管了。但是最近发生频率明显变高，将近一天一次，不得不录一下视频，以及提供相关日志文件以供参考，希望能早日解决吧。

### Version

Resource Version: 源石尘行动·复刻
UI Version: v5.2.0
Core Version: v5.2.0

### 日志文件

视频时间节点在4.18 14:16。gui日志中出现的其它连接错误均是按这样的操作进行处理的，不过未进行录屏。

由于体积过大，asst.log文件只完整截取了16日到今天的日志。

[asst.connect.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15020996/asst.connect.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15020998/gui.log)

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/23079970/7e8e57a1-2d5e-45a3-b418-b5b77a2cb189

### 还有别的吗？

模拟器：mumu12 V3.7.10(2634)
操作系统：win10 22H2

**Comment by 58761** [comment]
可以在maa里设置个开启前脚本，我这边设置后就没出现问题了。
<img width="356" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168245874/5fc6edec-cd31-4d7b-acb0-6ec3dd291f03">

@echo off
start cmd /k "cd/d G:\Program Files (x86)\MuMuPlayer-12.0\shell&&adb disconnect 127.0.0.1:16384"

**Comment by a0wsxz9** [comment]
> @echo off start cmd /k "cd/d G:\Program Files (x86)\MuMuPlayer-12.0\shell&&adb disconnect 127.0.0.1:16384"

Nice啊！兄弟！竟然内置有这个功能了，那就还行。不然头疼死我了。
