### ISSUE TITLE
maa自动战斗异常

### ISSUE THREAD

**Issue by DFFHSEVDH** [MaaAssistantArknights/MaaAssistantArknights#8860]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

4月18日巴别塔ex关更新之后使用自动战斗功能maa只显示下干员，并不操作模拟器。重试多次都不行，重启电脑也试过了。

### Version

UI Version: v5.2.2-alpha.1.d021.gec27c4184
Core Version: v5.2.2-alpha.1.d021.gec27c4184
Resource Version: 巴别塔

### 日志文件

文件
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15031533/asst.zip)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114905282/8c0719c8-c570-4e70-88c7-a4e4fa14e8bb)

### 还有别的吗？

模拟器使用mumu12
日志传不上去
https://share.weiyun.com/lUaf6X05
使用腾讯微云上传了一下。

**Comment by status102** [comment]
日志时间不对应
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/5e5fc3fa-4ab1-4aab-8c8d-ea14aa0b4ba7)


gui.log
```
[2024-01-30 09:46:30.377] <1><> 开始任务: Fight
[2024-01-30 09:46:55.984] <1><> 已开始行动 1 次
理智: 95/135
[2024-01-30 09:48:16.579] <1><> 掉落统计: 
龙门币 : 72 (+72)
固源岩 : 1 (+1)
基础作战记录 : 1 (+1)
[2024-01-30 09:48:23.158] <1><> 已开始行动 2 次
理智: 89/135
[2024-01-30 09:49:45.135] <1><> 掉落统计: 
龙门币 : 144 (+72)
固源岩 : 2 (+1)
基础作战记录 : 2 (+1)
[2024-01-30 09:49:51.721] <1><> 已开始行动 3 次
理智: 83/135
```

asst.log
```
[2024-01-30 09:49:54.424][TRC][Px1bac][Tx4328] asst::PipelineAnalyzer::analyze Fight@StartButton2WaitTime
[2024-01-30 09:49:54.424][INF][Px1bac][Tx4328] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"JustReturn","exec_times":3,"max_times":2147483647,"result":null,"task":"StartButton2WaitTime"},"first":["FightBegin"],"pre_task":"Fight@StartButton2TryAgain","subtask":"ProcessTask","taskchain":"Fight","taskid":4,"uuid":"3c9dd1d492d098b0"}
[2024-01-30 09:49:54.424][TRC][Px1bac][Tx4328] ready to sleep 65000
```

**Comment by DFFHSEVDH** [comment]
https://share.weiyun.com/1aW7GDgJ
不好意思上传成了上一次提交的log





发自我的iPad


------------------ 原始邮件 ------------------
发件人: status102 ***@***.***&gt;
发送时间: 2024年4月19日 08:06
收件人: MaaAssistantArknights/MaaAssistantArknights ***@***.***&gt;
抄送: DFFHSEVDH ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] maa自动战斗异常 (Issue #8860)





 
日志时间不对应
 image.png (view on web)
 
gui.log
 [2024-01-30 09:46:30.377] <1&gt;<&gt; 开始任务: Fight [2024-01-30 09:46:55.984] <1&gt;<&gt; 已开始行动 1 次 理智: 95/135 [2024-01-30 09:48:16.579] <1&gt;<&gt; 掉落统计:  龙门币 : 72 (+72) 固源岩 : 1 (+1) 基础作战记录 : 1 (+1) [2024-01-30 09:48:23.158] <1&gt;<&gt; 已开始行动 2 次 理智: 89/135 [2024-01-30 09:49:45.135] <1&gt;<&gt; 掉落统计:  龙门币 : 144 (+72) 固源岩 : 2 (+1) 基础作战记录 : 2 (+1) [2024-01-30 09:49:51.721] <1&gt;<&gt; 已开始行动 3 次 理智: 83/135  
asst.log
 [2024-01-30 09:49:54.424][TRC][Px1bac][Tx4328] asst::PipelineAnalyzer::analyze ***@***.*** [2024-01-30 09:49:54.424][INF][Px1bac][Tx4328] Assistant::append_callback | SubTaskStart ***@***.***","subtask":"ProcessTask","taskchain":"Fight","taskid":4,"uuid":"3c9dd1d492d098b0"} [2024-01-30 09:49:54.424][TRC][Px1bac][Tx4328] ready to sleep 65000

**Comment by status102** [comment]
提交一下所使用的作业

**Comment by status102** [comment]
[2024-04-18 21:11:04.463][ERR][Px25f8][Tx4bb0] No loc (7, 4)

有点怪，不确定，再看一眼

**Comment by hydra24-njus** [comment]
遇到了相同的问题。使用的作业是maa://36078，BB-EX-1 和 maa://36056，BB-EX-2

**Comment by DFFHSEVDH** [comment]
重新更新了一下maa
Resource Version: 巴别塔
UI Version: v5.2.2-alpha.1.d021.gec27c4184
Core Version: v5.2.2-alpha.1.d021.gec27c4184
自动战斗仍然有问题，还是只显示放下干员但是不操作。
https://share.weiyun.com/sZWubKb8
今天更新maa后的日志文件

**Comment by DrRua** [comment]
前不久因为使用mumu12的过程中win11蓝屏导致mumu12卡在98%无法正常启动，我就去官网重新下载了一个并且安装了一次，使用日常的基建换班，刷理智那些功能均无问题，萨米肉鸽能正常下干员，只有作业那里日志显示已经下了干员，但是实际一个都没下

**Comment by Saratoga-Official** [comment]
这个问题目前就只能重装maa解决，我在作业里也写了

**Comment by hydra24-njus** [comment]
> 这个问题目前就只能重装maa解决，我在作业里也写了

我这边找到maa安装文件夹 删除cache下的所有文件然后重启maa，会自动更新资源，更新后就没问题了。

**Comment by Saratoga-Official** [comment]
> > 这个问题目前就只能重装maa解决，我在作业里也写了
> 
> 我这边找到maa安装文件夹 删除cache下的所有文件然后重启maa，会自动更新资源，更新后就没问题了。

更新资源和cache没大关系，有些人更新好了照样不行，我觉得是更新的资源有问题，把资源文件替换成好的就能用

**Comment by status102** [comment]
> 前不久因为使用mumu12的过程中win11蓝屏导致mumu12卡在98%无法正常启动，我就去官网重新下载了一个并且安装了一次，使用日常的基建换班，刷理智那些功能均无问题，萨米肉鸽能正常下干员，只有作业那里日志显示已经下了干员，但是实际一个都没下。 更新：保全也能正常下干员

上传一下/resource/Arknights-Tile-Pos看看

**Comment by DFFHSEVDH** [comment]
> > 前不久因为使用mumu12的过程中win11蓝屏导致mumu12卡在98%无法正常启动，我就去官网重新下载了一个并且安装了一次，使用日常的基建换班，刷理智那些功能均无问题，萨米肉鸽能正常下干员，只有作业那里日志显示已经下了干员，但是实际一个都没下。 更新：保全也能正常下干员
> 
> 上传一下/resource/Arknights-Tile-Pos看看

https://share.weiyun.com/NaJJw7f6
这是我这边有问题的maa的/resource/Arknights-Tile-Pos文件夹，但是这个出bug的maa的cache文件夹让我删了重新下载了一下

**Comment by Saratoga-Official** [comment]
反正很有可能是地图资源的问题，感觉坐标可能存在错误，或者没有坐标，然后maa就不知道往哪放了

**Comment by DFFHSEVDH** [comment]
> 反正很有可能是地图资源的问题，感觉坐标可能存在错误，或者没有坐标，然后maa就不知道往哪放了

感觉像是角色识别的问题，出bug时候maa进图会点暂停，但是不会识别下面一排的干员，然后界面就直接提示部署，不操作模拟器。

**Comment by Saratoga-Official** [comment]
> > 反正很有可能是地图资源的问题，感觉坐标可能存在错误，或者没有坐标，然后maa就不知道往哪放了
> 
> 感觉像是角色识别的问题，出bug时候maa进图会点暂停，但是不会识别下面一排的干员，然后界面就直接提示部署，不操作模拟器。

如果cache里面有不需要点下面的干员也能下

**Comment by status102** [comment]
> 感觉像是角色识别的问题，出bug时候maa进图会点暂停，但是不会识别下面一排的干员，然后界面就直接提示部署，不操作模拟器。

不是识别问题，是地图里面没找到对应的坐标
[2024-04-18 21:11:04.463][ERR][Px25f8][Tx4bb0] No loc (7, 4)

待部署区干员头像有缓存，缓存的就不会挨个点开看

**Comment by DrRua** [comment]
> > 前不久因为使用mumu12的过程中win11蓝屏导致mumu12卡在98%无法正常启动，我就去官网重新下载了一个并且安装了一次，使用日常的基建换班，刷理智那些功能均无问题，萨米肉鸽能正常下干员，只有作业那里日志显示已经下了干员，但是实际一个都没下。 更新：保全也能正常下干员
> 
> 上传一下/resource/Arknights-Tile-Pos看看

https://share.weiyun.com/VJsAnsCM
这是仍然有问题的那个版本的文件。

**Comment by Dean-Mon10** [comment]
今天更新s关和mo关之后，我在资源更新后到/resource/Arknights-Tile-Pos下查看，没有act33-s关和mo关。在把github上dev分支下/resource/Arknights-Tile-Pos中共5个关卡9个JSON手动添加进去后，就可以使用自动战斗了。不知道是不是资源更新资源不全的原因？ @status102

**Comment by status102** [comment]
> 今天更新s关和mo关之后，我在资源更新后到/resource/Arknights-Tile-Pos下查看，没有act33-s关和mo关。在把github上dev分支下/resource/Arknights-Tile-Pos中共5个关卡9个JSON手动添加进去后，就可以使用自动战斗了。不知道是不是资源更新资源不全的原因？ @status102 

提交log以诊断问题

**Comment by Dean-Mon10** [comment]
> > 今天更新s关和mo关之后，我在资源更新后到/resource/Arknights-Tile-Pos下查看，没有act33-s关和mo关。在把github上dev分支下/resource/Arknights-Tile-Pos中共5个关卡9个JSON手动添加进去后，就可以使用自动战斗了。不知道是不是资源更新资源不全的原因？ @status102
> 
> 提交log以诊断问题

asst.log
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15108644/asst.zip)

**Comment by status102** [comment]
> > > 今天更新s关和mo关之后，我在资源更新后到/resource/Arknights-Tile-Pos下查看，没有act33-s关和mo关。在把github上dev分支下/resource/Arknights-Tile-Pos中共5个关卡9个JSON手动添加进去后，就可以使用自动战斗了。不知道是不是资源更新资源不全的原因？ @status102
> > 
> > 提交log以诊断问题
> 
> asst.log
> [asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15108644/asst.zip)
> 

缺少gui.log

**Comment by Dean-Mon10** [comment]
> > > > 今天更新s关和mo关之后，我在资源更新后到/resource/Arknights-Tile-Pos下查看，没有act33-s关和mo关。在把github上dev分支下/resource/Arknights-Tile-Pos中共5个关卡9个JSON手动添加进去后，就可以使用自动战斗了。不知道是不是资源更新资源不全的原因？ @status102
> > > 
> > > 
> > > 提交log以诊断问题
> > 
> > 
> > asst.log
> > [asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15108644/asst.zip)
> 
> 缺少gui.log

[log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15108742/log.zip)

**Comment by status102** [comment]
> > > > > 今天更新s关和mo关之后，我在资源更新后到/resource/Arknights-Tile-Pos下查看，没有act33-s关和mo关。在把github上dev分支下/resource/Arknights-Tile-Pos中共5个关卡9个JSON手动添加进去后，就可以使用自动战斗了。不知道是不是资源更新资源不全的原因？ @status102
> > > > 
> > > > 
> > > > 提交log以诊断问题
> > > 
> > > 
> > > asst.log
> > > [asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15108644/asst.zip)
> > 
> > 缺少gui.log
> 
> [log.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15108742/log.zip)
> 

谢谢

**Comment by status102** [comment]
更新到最新内测即可
