### ISSUE TITLE
MAA mac版本关卡识别错误

### ISSUE THREAD

**Issue by derpt2023** [MaaAssistantArknights/MaaAssistantArknights#8863]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用MAA活动新地图进行自动战斗时，出现错误提示：不支持的关卡，请更新MAA软件版本，但检查版本已是最新版本

### Version

v5.2.1（476）

### 日志文件

找不到QAQ

### 截图

![b8db2604074197feda82af4b43867739](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146498932/03fea8f3-6d31-49a5-adfc-a1718ecf4874)

### 还有别的吗？

操作系统：macOS 14.4.1

**Comment by wangl-cc** [comment]
Duplicate of #8813
