### ISSUE TITLE
MAA无法关闭蓝叠4

### ISSUE THREAD

**Issue by Zerohound** [MaaAssistantArknights/MaaAssistantArknights#8867]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA设定完成后退出模拟器，但完成后并没有退出模拟器，倒是可以手动关模拟器

### Version

Resource Version: 巴别塔
UI Version: v5.2.1
Core Version: v5.2.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15046710/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15046711/gui.log)

### 还有别的吗？

模拟器版本
BlueStacks
v4.280.4.4002,64位元 Android

**Comment by Zerohound** [comment]
补充一下执行完毕后模拟器和MAA的截图，之前用其他模拟器没出现过模拟器没关掉的情况
![QQ截图20240421124002](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/86946902/d67d4757-12c2-445e-9689-9d27be3f58a1)
![QQ截图20240421124113](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/86946902/c51fe7a8-adf2-4bb3-994a-23b6ddd99aa8)

**Comment by ABA2396** [comment]
蓝叠4是双进程的吧？杀端口杀不掉进程 ~~所以为什么不用蓝叠5~~

**Comment by Zerohound** [comment]
> 蓝叠4是双进程的吧？杀端口杀不掉进程 ~所以为什么不用蓝叠5~

不是很懂蓝叠4的情况。。
蓝叠5我也用过很长一段时间，或许是因为电脑配置较低，某天下载了蓝叠4之后感觉用蓝叠4玩方舟效果更好，于是就一直用4了 ~只是不能被MAA关掉这点比较难受~
