### ISSUE TITLE
添加自动作战，所有BB-ex都识别

### ISSUE THREAD

**Issue by Dearmy520** [MaaAssistantArknights/MaaAssistantArknights#8869]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

复制链接或者下载Json文件添加到战斗都不行,重装了也是这样

### Version

Resource Version: 巴别塔
UI Version: v5.2.2-alpha.1.d021.gec27c4184
Core Version: v5.2.2-alpha.1.d021.gec27c4184

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15048358/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15048359/gui.log)

### 截图

![QQ图片20240420213503](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106601893/476e578c-5a7f-4375-9fa4-c1fc33d0b440)

**Comment by Manicsteiner** [comment]
v5.2.2-alpha.1.d021 的数据不含本次EX关的数据，启动后等个资源热更新就好。
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/93b321f1-eee9-46d4-83c1-9372c41bd399)

**Comment by Dearmy520** [comment]
所以要怎么做，更换版本吗，我的是内测版，启动后勾选自动下载跟自动安装更新包吗

**Comment by ABA2396** [comment]
每次启动maa的时候都会检查一次资源更新，如果还是不行的话试试把cache/etag.json删了强制触发下

**Comment by Dearmy520** [comment]
淦 终于可以了，还以为我被孤立在了这个版本，停了好几天

**Comment by Charonics** [comment]
游戏资源总是更新失败，有大佬遇到过吗
