### ISSUE TITLE
肉鸽打法自定义器

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#887]
首先非常感谢大佬们的持续开发
一个大胆的设想，弄个设计自己干员的打法思路
大概的功能如下：
- 1.让玩家填写自己的思路
	- 对于每一个可能出现的关卡：
		- 对于每一步：
			- 格子名称（如果可行的话，可以引用[这里的](https://map.ark-nights.com/)格子名称？）
			- 干员，干员朝向

- 2.导出一个可以被这个软件识别的配置（有劳各位大佬实现）

这样~~我觉得可以大幅度~~减少肉鸽自动发病的次数

**Comment by MistEO** [comment]
肉鸽开放大范围的自定义支持是伪需求，我用 MAA 就是为了省事，结果还要让我配一堆东西，这不合理

优化肉鸽的干员摆放位置确实是在计划中的了

**Comment by KJH-x** [comment]
好的，我也仔细想了想，做这个确实是伪需求，感谢
