### ISSUE TITLE
基建换班正确选人后不点确认，而是反复试图前拖，直至重选，该过程重复四次

### ISSUE THREAD

**Issue by eadric13** [MaaAssistantArknights/MaaAssistantArknights#8870]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

具体表现为进入基建需要换班的设施后，能正常向后拖动干员列表并能正确选取指定的干员，但全部选取完毕后不会点下确认，而是会将干员列表往前拖到顶，并不断尝试前拖。一段时间后会清空已选干员，继续将列表从前往后翻接着选取。该过程重复四次。发生该bug时，几乎所有的生产设施都会重复这一过程（每个制造站、贸易站、发电站、办公室和会客室，但中枢很多时候能正常一次性换班，宿舍则从来没有出现这一情况。）有时重复四次后会正常换班干员，有时会导致设施空置（我多次发现贸易站里巫恋龙舌兰卡夫卡组只上了巫恋，不确定是否为巧合）

这个bug（疑似）有点离奇，一直存在，偶尔发生。我翻了gui.log里从23年12月开始的统计，大部分时候都是正常运行，两百多条换班记录里一共出现过13次上述情况（具体信息记在下面）。4月20日（今天）该bug再次发生（asst.log中2024-04-20 20:58左右开始）。平常使用自定义换班，这一段时间用过的两个json文件已附在日志里上传（今天发生bug时使用的文件是243正常，正在换班成组3）。

这一bug只发生在给基建排班里某几个组换班的过程中。我统计了自24年来所有发生bug的日期（日志均在gui.org可查），以及发生bug时正进行换班的组，并附上了所用排班的示意图，也许能派上用场。

上传的截图是 MAA已完成干员选取，正不断尝试将到顶的干员列表继续往前拖  的瞬间。

我今年使用MAA换班基本一天两次雷打不动，不管是正常组还是搓玉组大部分情况都正常运行，只是偶尔会出现上述bug，实在想不明白是由什么导致。翻了十几页已提交的issue也没看到类似的问题，所以新提交issue问一下试试。

### Version

Resource Version: 巴别塔
UI Version: v5.2.1
Core Version: v5.2.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15048536/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15048537/gui.log)
[243正常.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15048817/243.json)
[333搓玉.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15048819/333.json)

### 截图

![bug发生时](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146954994/8e1201dc-8639-43cd-a6cf-22ad52fbee97)
![MAA截图](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146954994/bce6b65d-6834-4267-9a85-da2d1f0cf3a3)
![243正常排班表](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146954994/be1b71cb-3c56-4f2a-acca-5bd253c16240)
![333搓玉排班表](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146954994/6efb589b-f8d3-435c-af14-5aafdbeb4d19)

### 还有别的吗？

发生bug的具体日期和当时正换班的组记录如下（均在gui.org可查）
2024-01-12（搓玉 组3）
2024-01-24（搓玉 组3）
2024-01-26（搓玉 组3）
2024-01-29（搓玉 组3）
2024-02-07（正常 组1）
2024-03-03（正常 组3）
2024-03-10（正常 组1）
2024-03-30（正常 组3）
2024-04-02（正常 组1）
2024-04-09（搓玉 组3）
2024-04-17（正常 组1）
2024-04-18（正常 组3）
2024-04-20（正常 组1）

换班都为顺序换班，按组1-组2-组3-组1的顺序三班倒，无定时启动。

**Comment by Bright1996** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/41429222/95467fc5-2574-43a4-a698-6225420d8312)
我好想也遇到了
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15125481/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15125482/gui.log)

**Comment by Xiaodx912** [comment]
出现相同情况  

初步分析对应部分日志，发现在失败时均有大量重试`InfrastOperListTabWorkStatusUnClicked`的日志。  
在上述二位的asst.log中搜索`Assistant::append_callback | SubTaskError {"class":"asst::ProcessTask","details":{},"first":["InfrastOperListTabWorkStatusUnClicked"], `也均可找到大量类似片段。  

初步怀疑是[此处](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/f7d30de2630141183d3d434b847cdd0af972047b/src/MaaCore/Task/Infrast/InfrastProductionTask.cpp#L702)前一项点击`InfrastOperListTabSkillUnClicked`失败，导致执行本项时“工作状态”tab仍处于选中状态，识别失败导致重试。观察提问者截图也可得知此时不可能找到`InfrastOperListTabWorkStatusUnClicked`。

附上一段截去无关内容的错误发生时日志。这次bug发生时要选择的仅有一个干员，且没有滑动需求，分析难度相对较低。

[gui.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15434815/gui.txt)
[asst.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15434816/asst.txt)
