### ISSUE TITLE
b服无法切换账号

### ISSUE THREAD

**Issue by IAMTERRIFIED** [MaaAssistantArknights/MaaAssistantArknights#8871]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

卡在账号选择界面，没有点击下拉的操作，然后报错：“任务出错：startup”。模拟器是MUMU12，更换过电脑和模拟器，并且尝试过其他分辨率和dpi，还是同样的问题，截图时的分辨率为720p，dpi为180。

### Version

Resource Version: 巴别塔
UI Version: v5.2.1
Core Version: v5.2.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15049401/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15049403/gui.log)

在最后面，01:25

### 截图

![MuMu12-20240421-023553](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/167642927/29cd5c68-b4c9-43bc-a994-4e19f227724a)

**Comment by Saratoga-Official** [comment]
其实账号切换不太好用，不如直接双开

**Comment by ABA2396** [comment]
我记得b服有dpi的问题
cc @status102

**Comment by status102** [comment]
> 我记得b服有dpi的问题
> cc @status102 

老问题，没想好怎么解决

**Comment by status102** [comment]
Duplucate of #7171
