### ISSUE TITLE
maa在自动肉鸽时仅在借助战干员时截图失败

### ISSUE THREAD

**Issue by WendyismyXP** [MaaAssistantArknights/MaaAssistantArknights#8872]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题
虽然我的电脑配置确实有点垃，但是平常跑其他关（包括打自动肉鸽时，如果跳过让maa选助战的环节）maa也是能正常跑的

### Version

v5.2.0（5.2.1还没试过）

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15050235/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15050236/asst.log)
asst.bak.log（github死活发不上来，只能用网盘了）
链接：https://pan.baidu.com/s/1N1O9y-8OdsLYTuFmqmIy3w 
提取码：vy9z 

### 截图

![2024-04-14_18-07-05-335_raw]
(https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/167098890/e88a07f4-0361-4377-89d5-38d56262f3f1)
另外两张截图
链接：https://pan.baidu.com/s/14c2PnC-kZOcS-UFKKBl7lw 
提取码：1i86 

### 还有别的吗？

模拟器：雷电模拟器9（上面传的截图加日志文件都是在雷电9跑的）
系统：win7
配置：处理器:
Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz 2.40 GHz
安装内存(RAM):
4.00 GB (3.86 GB可用)
系统类型:
64位操作系统

以下是我在考虑了电脑配置，拿雷电模拟器4运行v5.2.0maa的日志文件和截图

![2024-04-14_20-45-41-243_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/167098890/2f44fb34-7c30-44ab-8500-9d5596c5479b)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15050244/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15050243/gui.log)

**Comment by Manicsteiner** [comment]
> [2024-04-14 18:01:05.621][INF][Px1c10][Tx11d4] Call ` adb/platform-tools/adb.exe -s 127.0.0.1:5555 shell "screencap | gzip -1" ` ret 0 , cost 445 ms , stdout size: 17912 , socket size: 0
> [2024-04-14 18:01:05.621][INF][Px1c10][Tx11d4] screencap_end_of_line is set to CRLF but no `\r\n` found, set it to LF
> 
> [2024-04-14 18:08:59.239][INF][Px1c10][Tx11d4] data is not empty, but image is empty
> [2024-04-14 18:08:59.239][INF][Px1c10][Tx11d4] try to cvt lf
> [2024-04-14 18:08:59.273][INF][Px1c10][Tx11d4] screencap_end_of_line is changed to CRLF

日志里是截图的 End Of Line 总像这样在LF和CRLF之间变来变去
