### ISSUE TITLE
建议添加重复执行某项“一键长草”任务的功能

### ISSUE THREAD

**Issue by airuma0603** [MaaAssistantArknights/MaaAssistantArknights#8875]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

存在以下情况：
在通过maa的“自动公招”完成游戏内每日招募的任务后，游戏内日常奖励领取仍包含招募券，而这个招募券便无法在当日继续使用（因为“自动公招”任务已经执行过一次了）。
或是类似的：在完成每日打关任务后，游戏内日常奖励仍包含理智液，而此理智液便无法在当日继续使用。

### 有什么好的想法？

若任务可设置多个，则可在领取奖励后再次执行任务。

**Comment by Saratoga-Official** [comment]
首先这些都可以通过定时设置来实现，其次你就非要当天把能用的都用了吗
