### ISSUE TITLE
周一自动打剿灭

### ISSUE THREAD

**Issue by airuma0603** [MaaAssistantArknights/MaaAssistantArknights#8876]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

自动战斗高级设置里添加周一无视优先级自动打满剿灭功能

**Comment by status102** [comment]
主关卡选剿灭 备选关卡其他的
