### ISSUE TITLE
mac端存在心情为零干员时无法正确将干员放入宿舍

### ISSUE THREAD

**Issue by PolarisIr** [MaaAssistantArknights/MaaAssistantArknights#8877]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

当存在红脸干员时，放入干员的策略较为奇怪，仅放入正常按照理智排序时第二列及之后的三位干员。举例而言，现将正常情况下应该放入的五位干员编号为12345，则正常的点击顺序也应为12345。但在存在红脸干员时，点击顺序为1122345，导致干员1、干员2被二次点击从而不放入。当存在多个红脸干员时这一情况仍然出现，并在多于五个红脸干员时每个宿舍仅可放入一人，点击机制仍未查明。当不存在红脸干员时未观察到问题。推测判断是否选中的逻辑与干员红脸存在矛盾导致这一情况。

另：在翻阅以往的部分issue时发现曾经有其他issue也报告过相似的问题，但未提到与红脸干员存在的相关性。或许能够从其他的issue中也推测出逻辑的相关问题。

又及：这一问题在过去的多个版本中持续存在。

### Version

Version：v5.2.1（476）

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15051055/asst.bak.log)
04-21 15:27:36开始宿舍换班

### 截图

![1713684638528](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/167517606/7fc85a90-a121-413a-ab60-dfd121cd85ef)

### 还有别的吗？

模拟器：Playcover版本3.0.0.maa.4 (4)
操作系统：Mac OS Ventura 13.0.1 (22A400)
机型：Macbook Pro 13-inch, M1, 2020

**Comment by Sduck-Inverse** [comment]
虽然但是人家不叫理智叫心情/笑哭

**Comment by PolarisIr** [comment]
补充：新测试发现当存在一个红脸干员时每个宿舍仅可放入三人，当存在两个及以上红脸干员时每个宿舍仅可放入一人，且放进去的并不是红脸干员而是之后心情仍未清零的干员，导致这一现象一旦出现便会持续存在。

**Comment by SOLE-Y** [comment]
同样的问题，玛雅这个issue都要一年了，mac用户真就不被重视

**Comment by chx-hu** [comment]
+1

**Comment by PolarisIr** [comment]
补充：issue#8102，issue#7073描述情况与此issue疑似类似，可合并

**Comment by Toby-Shi-cloud** [comment]
> 同样的问题，玛雅这个issue都要一年了，mac用户真就不被重视

看[MaaMacGui](https://github.com/MaaAssistantArknights/MaaMacGui) 的 fork 和 star 数量，就知道有多寒酸了。你们要不也去点个 star 吧，说不定就有人维护了（x）

**Comment by Toby-Shi-cloud** [comment]
remove "client: WpfGui", remove "client: MacGui", remove "module: others"

**Comment by PolarisIr** [comment]
更新：此问题在v5.4.1仍然存在。观测更新：当且仅当仅存在一名红脸干员，且其余需放入宿舍回复的干员与此红脸干员不处于同一页面上时，maa能够在存在红脸干员的情况下宿舍放满成员。
