### ISSUE TITLE
无法识别并编入队员 山

### ISSUE THREAD

**Issue by Rojomoo** [MaaAssistantArknights/MaaAssistantArknights#8878]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

故事集巴别塔EX关卡，无法识别并编入队员 山，所有皮肤均编队失败

### Version

Core Version: v5.2.1

### 日志文件

时间：4月21日 17:30:06 无法识别干员 山
4月21日 17:33:00 未报错，但仍未识别编队干员 山

以下为系统文件
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15051303/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15051305/gui.log)

### 截图

![Screenshot_20240421-173452](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/167678610/075d1a9b-980e-4fcf-a6f6-f72c85cf4904)
![QQ截图20240421173018](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/167678610/40ece247-8dbc-4c43-9029-e2c97283f073)

**Comment by Lancarus** [comment]
倒序或者选点人点几下排序让山到下排，就能识别到了，检测模型的问题，老问题了

**Comment by Saratoga-Official** [comment]
首先maa编队是文字识别，和皮肤没关系，应该是识别错了，你最好把特别关注都取消，然后分辨率调大一点，一般来说都能解决
