### ISSUE TITLE
博朗台询问关于碎石的建议

### ISSUE THREAD

**Issue by Sduck-Inverse** [MaaAssistantArknights/MaaAssistantArknights#8879]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

因为发现似乎系统连战更能节约时间，但是一直用6次连战好像溢出理智的时间也会更长很浪费……现在的模式只能用单次战斗或者多次战斗是吧？

### 有什么好的想法？

就想问有没有可能做到碎石后先打一次战斗，等到结算后开始自回体了再选择五次战斗之类的模式？然后没理智的时候再循环一次或者两次战斗，不知道各位大佬有没有可能实现这种有点奢侈的功能（捂脸），或者还有其他更好的方法？

### 其他内容

我也不清楚6次连战12分钟溢出多少点理智，或者3次连战是不是6分钟正好回满一次体力……如果实在没办法就当在下胡言乱语关闭吧（擦汗）

**Comment by ABA2396** [comment]
真博朗台就别用连战了

比如6连战1-7要花36点，现在你有34点，这个时候吃了个石头进去了，你得打完这6把才会开始回理智
