### ISSUE TITLE
Combat task causes Bluestacks 5 to repeatedly hit the back button and fail the combat task

### ISSUE THREAD

**Issue by Lostmaniac9** [MaaAssistantArknights/MaaAssistantArknights#8881]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

Before I attempt to run a combat task for any stage I go to the UI location where I select a stage and it says "Start". I then hit "Link Start!" on MAA and it connects successfully to the Bluestacks 5 emulator. However, once this happens it repeatedly starts hitting the back button in the upper left of the screen. It will keep hitting it without stopping until the task fails in MAA. I have Bluestacks running at 1920x1080.

I apologize if this issue has already been addressed elsewhere. I have been using a translator for the Chinese but of course I could have made a mistake. Thank you for the help!

### Version

v5.2.1

### Log files

08:08am is when the program is run and when it fails

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15051791/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15051797/gui.log)

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/26028438/3d97b4c2-c020-4907-958e-224bec739813)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/26028438/6fbd4a13-7e24-42eb-a629-4483555f992b)

### Anthing else?

Emulator: Bluestacks 5
Bluestacks 5 is running in administrator mode with Hyper-V enabled

OS: Windows 11

**Comment by Lostmaniac9** [comment]
I was using the dark theme and switching the theme to white did fix the issue. Thank you very much.

**Comment by Constrat** [comment]
> I was using the dark theme and switching the theme to white did fix the issue. Thank you very much.

You can update to a nightly, and use any theme you want.
