### ISSUE TITLE
建议加入对兆懿运行平台的兼容

### ISSUE THREAD

**Issue by ganlinte** [MaaAssistantArknights/MaaAssistantArknights#8882]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

兆懿运行平台https://www.wndroid.com/index/
该模拟器使用了微软的WSL功能
adb可以连接成功，开始任务没有任何反应，提示截图用时过长（4000ms）。

### 其他内容

![MAA](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/160194569/c50d890f-8810-47f5-989a-362960e20517)

**Comment by ABA2396** [comment]
#4047
