### ISSUE TITLE
自动战斗中循环作战功能在一些关卡无法正常使用

### ISSUE THREAD

**Issue by 12345ph** [MaaAssistantArknights/MaaAssistantArknights#8883]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

6-7、11-17等关卡在结束行动后不会回到关卡详情界面，而是会进入截图所示状态，导致无法循环作战

### Version

Resource Version: 巴别塔:UI Version: v5.2.2-alpha.1.d028.g4c031484a:Core Version: v5.2.2-alpha.1.d028.g4c031484a

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15064098/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15064103/gui.log)

### 截图

![2024-04-22_21-28-52-808_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108412928/61952dd6-036f-4cb6-b05e-8f49509fc633)

**Comment by status102** [comment]
感觉是yj的问题，有些关卡会回，有些不会，还没找到规律
