### ISSUE TITLE
配置了蓝叠模拟器多开但是总是连接到同一个端口

### ISSUE THREAD

**Issue by lthon-sha** [MaaAssistantArknights/MaaAssistantArknights#8887]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

有两个配置分别对应启动不同的模拟器，单独启动任意配置都可以在未打开模拟器的时候运行成功，但是当已经使用配置 1 运行一个模拟器的时候，再启动配置 2，只会连接到同一个模拟器。

相关设置（具体配置文件见后）
- Hyper-V 已开启
- 使用蓝叠模拟器国际版 5.13
- 复制了 MAA
- 统一使用模拟器自带 adb（试过自定义为自己下载的 adb，但是失败后自动改回模拟器自带的路径）
- 通过为模拟器 exe 附加命令来进行多开操作
    - `--instance Pie64 --cmd launchApp --package "com.hypergryph.arknights"`
    - `--instance Pie64_1 --cmd launchApp --package "com.hypergryph.arknights"`
- 添加了 Bluestacks.Config.Keyword
    - `"Bluestacks.Config.Keyword": "bst.instance.Pie64.status.adb_port",`
    -  `"Bluestacks.Config.Keyword": "bst.instance.Pie64_1.status.adb_port",`
- 勾选 自动检测连接 和 每次重新检测
- 连接配置均为蓝叠模拟器

Keyword 设置和单独启动配置运行的模拟器核心都对的上（见截图）

#### 配置
配置 3608
- [gui.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15071110/gui.json)

配置 2872
- [gui.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15071107/gui.json)

### Version

Resource Version: 巴别塔
UI Version: v5.2.1
Core Version: v5.2.1

### 日志文件

配置 3608
- [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15071056/gui.log)
- [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15071057/asst.log)

配置 2872
- [gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15071060/gui.log)
- [asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15071061/asst.log)

#### 3608 配置和单独启动时的模拟器进程
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134971804/9c228992-bef0-462e-8177-e4192ab197c7)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134971804/266ad32e-ddf8-45cc-acf4-75dc644b9b55)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134971804/984983d3-4710-4eb4-be76-44846a4a6dc7)

#### 2872 配置和单独启动时的模拟器进程
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134971804/92dd3fb4-5b39-4f42-8650-d0552e8cae8b)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134971804/b24d4176-a827-4a4c-97bb-f6d20cc9dbdf)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/134971804/2ab76de8-87d1-4a52-bb34-239e1a6e77ed)

### 还有别的吗？

蓝叠国际版 5.13

**Comment by MobiusT** [comment]
关掉自动检测链接，我是这么配置的
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62053271/8287d523-6a6b-4512-8f86-de986dec3e80)

**Comment by lthon-sha** [comment]
突然想到，我好像可以只用一个 maa、两个配置、一个模拟器，定时切换配置运行就行。

**Comment by lthon-sha** [comment]
> 关掉自动检测链接，我是这么配置的 ![image](https://private-user-images.githubusercontent.com/62053271/324838786-8287d523-6a6b-4512-8f86-de986dec3e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNDk5NzIsIm5iZiI6MTcxNDE0OTY3MiwicGF0aCI6Ii82MjA1MzI3MS8zMjQ4Mzg3ODYtODI4N2Q1MjMtNmE2Yi00NTEyLThmODYtZGU5ODZkZWMzZTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDE2NDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZGVlMTI1OGMxZTQwNjBlZjc2MTNlYjFjYjJjNmMxNGFlOTA4Yzc2ZjI5MTYwYjk3N2I4ZThmYjEwYzZkY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E72DONo4hdlHB2h_itLITLpae5bNHnT8BNPh937IfhY)

谢谢，但是我开启了 hyper-v，用的是蓝叠，每次打开端口都会变的，没办法固定住。

**Comment by starrin** [comment]
> 突然想到，我好像可以只用一个 maa、两个配置、一个模拟器，定时切换配置运行就行。

是可以的，我现在就意识到多开模拟器其实不是很有必要，除非存在多个账号需要同时开始刷的需求，而这种时候其实不是很多，并且这种情况下很可能需要准备两个maa，更麻烦了
