### ISSUE TITLE
基建领取专精后未自动进行下一阶段专精

### ISSUE THREAD

**Issue by MobiusT** [MaaAssistantArknights/MaaAssistantArknights#8888]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62053271/2122a717-5102-451f-905d-f33ec53843a8)
预期在专精完成时会自动领取并开始下一阶段专精，直至专三完成，但是并未开启下一阶段专精，并不仅限杜宾，之前也多次发现过这个情况，gui日志上看会多出一次训练室空闲中，但是不是必定发生，中间也有正常继续专精的情况，可以参考历史gui日志

### Version

Resource Version: 巴别塔
UI Version: v5.2.2-alpha.1.d028.g4c031484a
Core Version: v5.2.2-alpha.1.d028.g4c031484a

### 日志文件

反馈的是时间20.16分，
另外gui里[2024-04-21 05:11:15.123] 时间点也有类似日志
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15076986/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15077016/gui.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15077038/asst.bak.log)

### 还有别的吗？

庆祝一下自己喜提#8888

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/a7678326-0949-4e7c-9e4e-17c139a9b1c9)
这里符号识别有问题，两次识别到的不是一个名字

**Comment by MobiusT** [comment]
@ABA2396 请问下这个问题有优化方案吗？
我评估下来需要文字ocr主要还是因为可能有的人技能本来就只留在专1、2并不打算专三，只是另一个技能需要专精，考虑是否能增加一个兼容模式，不再通过文字ocr的方式判断技能，而是判断图标，检查与专精完成相同等级的图标，如果识别没有或出现多个相同等级的则停止继续专精

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62053271/afe16848-5ea6-4687-9b73-d15bb99e74bd)

#8979 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62053271/b26f424f-f322-421f-b84f-f7d57b74bdbd)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62053271/3b446a06-9add-44de-95ec-1f0ac19c829e)

**Comment by ABA2396** [comment]
cc @broken-paint

**Comment by broken-paint** [comment]
考虑把文字识别技能名改成把图标接下来做临时的模板识别，这种可以实现吗（）
