### ISSUE TITLE
定时执行 有时会卡在日刷的“数据更新”页面

### ISSUE THREAD

**Issue by pearhield** [MaaAssistantArknights/MaaAssistantArknights#889]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8909243/asst.log)

**Comment by pearhield** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8909247/asst.log)

**Comment by ntgmc** [comment]
更新到最新版再试试，有问题再发issue
