### ISSUE TITLE
盐酸内容扩展开放后，作战无法导航到巴别塔关卡

### ISSUE THREAD

**Issue by starrin** [MaaAssistantArknights/MaaAssistantArknights#8893]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

今天闪断更新后主入口被替换成了盐酸，巴别塔的关卡都进不去了，巴别塔活动还有一周才结束，这一周都只能用上次作战的方式来导航的话比较不方便，每天自动借助战的功能基本不能用了

### Version

v5.2.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15108217/asst.log)

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaRelease/commit/645d74ced0fab13e79632c656c2ea84d5fc6e0c3 fixed 
重启触发右上角关卡更新弹窗后生效
