### ISSUE TITLE
刷材料一直报任务出错

### ISSUE THREAD

**Issue by argent-dawn** [MaaAssistantArknights/MaaAssistantArknights#8898]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

执行巴别塔活动刷理智在进入活动页面后，始终无法选择关卡，然后报任务出错
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12173772/19a9ada7-192c-4bce-8596-a93d7d189b5d)
能够进入活动关卡，可以正常滚动到关卡列表末尾，但无法选择目标关卡，每次都卡在截图位置
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12173772/65483683-8d30-4e8e-ab4a-24121b30e753)

### Version

Resource Version: 巴别塔
UI Version: v5.2.2-alpha.1.d047.g5e9055d5d
Core Version: v5.2.2-alpha.1.d047.g5e9055d5d

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15111967/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15111947/gui.log)

**Comment by D3adEr1c** [comment]
遇到同样的问题

**Comment by D3adEr1c** [comment]
遇到同样的问题
Version
Resource Version: 巴别塔
UI Version: v5.2.2-alpha.1.d047.g5e9055d5d
Core Version: v5.2.2-alpha.1.d047.g5e9055d5d

**Comment by Nothing1031** [comment]
相同问题+1，感觉是今天的资源更新导致，昨天正常
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15112496/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15112497/gui.log)

**Comment by 68star89** [comment]
楼上的难兄难弟可以先改用（当前/上次）关卡选项刷理智应个急，这选项目前还没问题（

**Comment by bronzitro** [comment]
稳定版也有此问题
