### ISSUE TITLE
借助战打OF-1时希望能选择指定编队

### ISSUE THREAD

**Issue by SnowParaselene** [MaaAssistantArknights/MaaAssistantArknights#8899]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

四个编队，有时候会有不想被更改的但是经常用的编队，但OF-1选择干员时是更改当前编队，每次被换了得自己重新一个个找，比较麻烦

### 有什么好的想法？

在打OF-1的时候能多一步选择一个编队，以后默认改这个编队，这样偶尔调整自己编队的时候不会被误改了

**Comment by status102** [comment]
已有功能
