### ISSUE TITLE
活动搬空商店选项

### ISSUE THREAD

**Issue by mutr21** [MaaAssistantArknights/MaaAssistantArknights#8905]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

maa活动刷的太顺了,我都不用管,怕一不小心活动过了,我商店还没买

### 有什么好的想法？

能不能出个活动搬空商店的奖励,因为每次活动代币都是溢出的,只要搬空就好了,也不需要考量我需不需要放弃一些资源而去换其他资源

**Comment by status102** [comment]
Duplicate of #6096
