### ISSUE TITLE
刷理智功能无法进入巴别塔活动关卡

### ISSUE THREAD

**Issue by lansandan** [MaaAssistantArknights/MaaAssistantArknights#8913]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

刷理智功能无法进入巴比塔活动关卡（选择bb-6,bb-7,bb-8,bb-4），会卡在终端界面，其他关卡则正常

### Version

Resource Version: 巴别塔|UI Version: v5.2.2-alpha.1.d053.g2ed9e994a|Core Version: v5.2.2-alpha.1.d053.g2ed9e994a

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15137217/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15137218/gui.log)
04-27 14:04:06>04-27 14:04:50

### 截图

![MuMu12-20240427-141144](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168259432/f3ed5aff-b658-460e-aa13-206cce408d86)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168259432/f3cfec3c-28b8-45df-90fd-af85f28ea890)

### 还有别的吗？

MuMu模拟器12
Windows 11

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaRelease/commit/aec32f92654478efc0f139c18ce17f47c4393284 fixed
重启maa

**Comment by lansandan** [comment]
@ABA2396 
尝试过了，仍然不行，刚刚还尝试通过重装MAA解决问题，还是不行。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15137796/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15137799/gui.log)
Resource Version: 巴别塔|UI Version: v5.2.1|Core Version: v5.2.1
04-27 17:59:29>04-27 18:00:08

**Comment by ABA2396** [comment]
看这日志像是900x1600分辨率的问题了，识别不到巴别塔这几个字，试试看换成720p，再不行还是用 当前/上次 吧，如果换成图片导航的话就得所有人都更新版本才能用了

**Comment by lansandan** [comment]
@ABA2396 
还是不行，个人猜测是游戏内的图太糊了导致的。
![屏幕截图 2024-04-27 203328](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168259432/fd3cbe11-d4ec-4774-8e82-364084973839)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15138208/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15138209/gui.log)
04-27 20:32:36>20:33:23
Resource Version: 巴别塔|UI Version: v5.2.1|Core Version: v5.2.1
