### ISSUE TITLE
保全自动作战异常

### ISSUE THREAD

**Issue by aliezlo** [MaaAssistantArknights/MaaAssistantArknights#8916]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

rt，满费了不下人

### Version

Resource Version: 巴别塔
UI Version: v5.2.1
Core Version: v5.2.1

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15138136/asst.bak.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15138137/gui.log)
晚8点后

**Comment by aliezlo** [comment]
看作业up主说好像这bug4月一直有，不知道修没修

**Comment by Saratoga-Official** [comment]
可能和保全节能模式有关系，试试这个方法解决![af12b245-6180-4996-b31a-e01c1e65ac9c.png](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151550168/3846b65f-925e-46bc-a356-99a6025af569)

**Comment by Saratoga-Official** [comment]
可能和保全节能模式有关系，试试这个方法解决![af12b245-6180-4996-b31a-e01c1e65ac9c.png](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151550168/3846b65f-925e-46bc-a356-99a6025af569)

**Comment by ABA2396** [comment]
> 可能和保全节能模式有关系，试试这个方法解决![af12b245-6180-4996-b31a-e01c1e65ac9c.png](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/151550168/3846b65f-925e-46bc-a356-99a6025af569)
> 
> 

他说的删的东西是技能识别的模型，和节能模式无关，节能模式是120s部署栏没变化放缓截图，不可能说等了50秒到99费都不下一个人

**Comment by Saratoga-Official** [comment]
明白了，主要是他写的保全比较多我就以为是这个原因，原来是搞错了
那就可能是maa识别问题吗？试试删cache能不能解决
（我用手机看不了log，也不太会看）只能说试试能不能解决了，不行我也不知道了

**Comment by aliezlo** [comment]
补充一点，又开了一把
它其实是会选中干员的，只是下不下去，好像拖不到？选中之后零点几秒就退出选中了，如此往复

**Comment by aliezlo** [comment]
我好像观察出来为什么了
多索雷斯保全的LT-4的高台位识别有问题，浊蒂的上面识别不出来

**Comment by aliezlo** [comment]
<img width="530" alt="捕获" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90097743/69800e6e-f094-49b8-b25a-d5e28869e184">

**Comment by aliezlo** [comment]
就是这样

**Comment by aliezlo** [comment]
https://prts.plus/?op=36037作业评论区也有同样的问题

**Comment by Saratoga-Official** [comment]
问题是我自己打没这个问题，就很奇怪，如果单纯是高台位问题所有人都会有，我们写作业的不可能不会发现

**Comment by status102** [comment]
> 看作业up主说好像这bug4月一直有，不知道修没修
> 

btw，这里是第一个相关issue，有问题及时提出

**Comment by haohanyuzmx** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57041322/a1c5883a-2cee-48b0-9d9e-e6f5a1f4bd6b)
这关我也有问题，一直失败

**Comment by ABA2396** [comment]
这一款之前yj改过地图坐标，试试把这关的地图删了，重新下载一遍。不知道在哪里的话，重新下一个完整包，然后覆盖一下。
