### ISSUE TITLE
不支持的关卡 请检查资源版本更新与关卡名

### ISSUE THREAD

**Issue by gdf159159** [MaaAssistantArknights/MaaAssistantArknights#8917]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/8487256/8c9a6439-aa83-4c04-8a95-4555abcfdaf3)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/8487256/ec9c06da-0158-4832-8055-7fc3c1238cd7)

### Version

5.2.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15138216/asst.log)

**Comment by status102** [comment]
提交gui.log以及resource/Arknights-Tile_Pos/overview.json

**Comment by gdf159159** [comment]
> 提交gui.log以及resource/Arknights-Tile_Pos/overview.json

今早启动maa 有新的资源更新  更新之后可以用了
