### ISSUE TITLE
雷电模拟器使用3.9.7版本刷理智持续出现“游戏崩溃，重新启动”提示，实际模拟器并未出现问题

### ISSUE THREAD

**Issue by Taki1001** [MaaAssistantArknights/MaaAssistantArknights#892]
PC版本：win 11 64位
模拟器版本：雷电模拟器 4.0.82
MAA版本：3.9.7
可以正常连接，公招等其他功能正常，但一刷理智就显示游戏崩溃
![image](https://user-images.githubusercontent.com/102930243/173871793-878be715-925a-49af-8b39-87e7fdb1b7c2.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8911104/asst.log)

**Comment by MistEO** [comment]
点开始行动之后，识别到了这玩意，这是在哪个界面的？

```
[2022-06-15 08:38:42.928][TRC][Px28e4][Tx47c0] OcrPack::recognize | raw :  然环境严配 : [ 106, 96, 112, 27 ], score: 0.934026, 萨斯帝国一一以乌萨 : [ 0, 59, 218, 29 ], score: 0.961666,  
```

另外问下，这关你是刷的特别快么，代理指挥掐表 40 秒以内？_(:з」∠)_

**Comment by MistEO** [comment]
你可以自己尝试修改 `resource/tasks.json` - `StartButton2` 这里的延迟

![image](https://user-images.githubusercontent.com/18511905/173889408-549e6fad-9095-444a-bed2-59cdf53cbfd1.png)

把 40000 再改大一点（单位毫秒）

因为 40 秒已经足够有的玩家一局刷完进到结算界面了，所以这个我们没法改，只能你自己改自己的用了_(:з」∠)_

**Comment by Taki1001** [comment]
啊这边打的是当期LE关 都是二倍速以后耗时90秒以上的 游戏内战斗并未结束处于正常页面出现跳错提前结束
我检查一下模拟器分辨率是
[image: image.png]
我仔细观察了一下出错时机 确实跳出了一些额外文字但为什么被识别和报错就不清楚了
[image: image.png]


MistEO ***@***.***> 于2022年6月15日周三 10:32写道：

**Comment by MistEO** [comment]
> 

你看下我编辑后的

**Comment by Taki1001** [comment]
好的 我改成1.3minl等我体力回上来我再开一把看看[image: image.png]

MistEO ***@***.***> 于2022年6月15日周三 10:54写道：

**Comment by Taki1001** [comment]
哦哦可以正常运行了 感谢制作MAA 真的很好用[image: image.png]

1001 ***@***.***> 于2022年6月15日周三 11:00写道：
