### ISSUE TITLE
MAA无法找到adb时显示的错误提示不明确

### ISSUE THREAD

**Issue by Kendox07** [MaaAssistantArknights/MaaAssistantArknights#8921]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA无法找到adb时，在MAA内的提示不是无法找到adb，而是提示“请检查连接设置货尝试重启模拟器与ADB或重启电脑”，需要自行指定adb的绝对路径才能正常使用。请问是否考虑在MAA中内置adb？

### Version

Resource Version: 巴别塔
UI Version: v5.2.1
Core Version: v5.2.1

### 日志文件

具体问题出现点大概在[2024-04-28 00:22:54.428]左右，并且在[2024-04-28 00:10:15.955]也有相关日志。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15138996/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15138997/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/42028506/defac879-a6b6-4692-ab9f-1ff31612ece2)

**Comment by ABA2396** [comment]
蓝叠照理来说是可以自动检测到配置和adb路径的，但 #8748 也有提到检测出问题了

**Comment by Kendox07** [comment]
> 蓝叠照理来说是可以自动检测到配置和adb路径的，但 #8748 也有提到检测出问题了

是的，感觉可能是蓝叠国际版在A11的新版本搞了什么奇怪的东西。之前在Hyper-V专版蓝叠国际上是可以正常工作的。
不过我在重装系统之后并没有将adb加入到环境变量中，这可能是这个问题发生的一个原因？

**Comment by Kendox07** [comment]
> 蓝叠照理来说是可以自动检测到配置和adb路径的，但 #8748 也有提到检测出问题了

刚刚尝试了一下，蓝叠国际内置的hd-adb是可以正常工作的，应该是MAA的检测出了什么问题
