### ISSUE TITLE
希望加入账号切换下拉框

### ISSUE THREAD

**Issue by shimmergloom1985** [MaaAssistantArknights/MaaAssistantArknights#8923]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有多个账号，每次手输账号略麻烦。

### 有什么好的想法？

1.希望账号切换输入框能保存输入过的手机号，改成下拉框模式。
2.如果更近一步的话，拉下框里面多个账号是勾选框，多选的话，执行任务会把2个账号都执行一遍。

**Comment by starrin** [comment]
多个账号的话，可以通过切换profile的方式来保存，给每个账号设置一个profile，之后只需要选profile就好
然后通过定时任务+自动切换profile就能把所有的账号都跑一遍了
