### ISSUE TITLE
adb連接一直失敗

### ISSUE THREAD

**Issue by FeliumMata** [MaaAssistantArknights/MaaAssistantArknights#8924]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

 
我跟隨常見問題嘗試强制替換ADB
但是也是失敗了
重啓3次電腦也是沒有用
模式改了也沒用
想看看有沒有人能夠幫幫我

### Version

Resource Version: 煙塵に瞬く
UI Version: v5.2.1
Core Version: v5.2.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15140788/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15140789/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125759352/dcf8e46b-c05f-4926-95e4-91682bf3c7fd)

**Comment by Kendox07** [comment]
可以尝试下自行下载ADB（https://developer.android.com/tools/releases/platform-tools）并且解压到某个路径，然后在MAA的设置中中以绝对路径的方式选择你下载的ADB。貌似现在在蓝叠国际版上有奇怪的ADB连接问题

**Comment by ABA2396** [comment]
用的是普通的蓝叠还是Hyper-V的蓝叠

**Comment by FeliumMata** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125759352/28525bfa-2afc-4722-bf8c-8eb0e91a4446)
後來我發現是藍叠預設沒有打開這個

**Comment by ABA2396** [comment]
这个在模拟器支持里有写
