### ISSUE TITLE
刷理智时识别不了活动关卡

### ISSUE THREAD

**Issue by digdeath** [MaaAssistantArknights/MaaAssistantArknights#8925]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在“刷理智”中选择巴别塔活动关卡，maa会停留在“终端”界面，无法跳转活动完成作战。其他消耗理智关卡均可跳转作战，譬如主线、龙门币、经验等，唯独活动不能跳转。

### Version

Resource Version: 巴别塔
UI Version: v5.2.1
Core Version: v5.2.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15141149/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15141150/gui.log)

### 截图

[MAA (Default) - v5.2.1 - 巴别塔 - MuMu 模拟器 12 (127.0.0.1_16384) - 官服 2024-04-28 15-09-30.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15141169/MAA.Default.-.v5.2.1.-.-.MuMu.12.127.0.0.1_16384.-.2024-04-28.15-09-30.zip)

### 还有别的吗？

mumu模拟器12

**Comment by ABA2396** [comment]
同 #8913 ，现在大部分人是能跑的，如果改了的话只有更新版本才能用，其他现在能用的人不更新的话就用不了了，先用 当前/上次 将就下吧

**Comment by IAMTERRIFIED** [comment]
同样问题，我是把mumu12设置里的显存使用策略改成画面表现更好解决的，可以参考一下。

**Comment by lansandan** [comment]
@ABA2396 
> 同样问题，我是把mumu12设置里的显存使用策略改成画面表现更好解决的，可以参考一下。
原因看来是MUMU12的显存使用策略没有调成画面表现更好导致的。改了后就能正常用了。

**Comment by digdeath** [comment]
> 同样问题，我是把mumu12设置里的显存使用策略改成画面表现更好解决的，可以参考一下。

搞好了！真是妙手回春啊师傅
