### ISSUE TITLE
干员识别有误，归溟幽灵鲨未识别

### ISSUE THREAD

**Issue by gIt-SpLasHeR** [MaaAssistantArknights/MaaAssistantArknights#8927]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

小工具的干员识别功能，统计有误，box中包含归溟幽灵鲨但是统计结果是未拥有，见截图。
同时附上asst.log文件和debug/oper文件夹的压缩包。

### Version

Resource Version: 巴别塔
UI Version: v5.2.1
Core Version: v5.2.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15141419/asst.log)

### 截图

![Snipaste_2024-04-28_16-42-09](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/8559113/d484aff3-9992-44d2-a64e-416594a98b10)

### 还有别的吗？

[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15141444/oper.zip)

debug/oper文件夹的压缩包。

**Comment by Saratoga-Official** [comment]
是因为特别关注的原因，不是bug，你把特关取消了就好了，特别关注的黄标会挡住干员名，maa识别不了
