### ISSUE TITLE
建议在任务完成以后返回一下基建，将制造站的任务调至最高

### ISSUE THREAD

**Issue by muben233** [MaaAssistantArknights/MaaAssistantArknights#8928]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

搓玉时由于以前的石头不多，导致在基建排班任务时收获完玉，能够制造的玉任务为0，而之后刷理智获得的石头不会自动的加入制造任务。例如：基建排班收获完玉后没有石头了，这时候制造任务为0，而刷完理智后有了50石头，而maa结束后，制造任务依然为0，浪费了很多时间。

### 有什么好的想法？

一是可以把基建排班和刷理智调换一下顺序
或者在刷完理智之后加入一个maa返回基建更新制造任务的选项

**Comment by Saratoga-Official** [comment]
可以用鼠标拖动刷理智和基建两功能的位置的，不是固定的，你可以自己调整

**Comment by muben233** [comment]
> 可以用鼠标拖动刷理智和基建两功能的位置的，不是固定的，你可以自己调整

感谢
