### ISSUE TITLE
生息演算自动到第一天结束前后出错

### ISSUE THREAD

**Issue by BigB0Bro** [MaaAssistantArknights/MaaAssistantArknights#8929]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

1.我已删除存档，并清空编队
2.在自动时，可能在某一个资源关卡卡主后报错，也可能在第一天结束时报错。

### Version

V5.2.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15141962/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15141965/gui.log)
04-28 19:35:43

**Comment by Saratoga-Official** [comment]
你确定你清的是生息的编队？有报错时候模拟器的截图吗？

**Comment by BigB0Bro** [comment]
感觉是转场的时候  加载时间过长导致的报错（未能同步到神经网络）

**Comment by Saratoga-Official** [comment]
要是网络的事maa也没办法
