### ISSUE TITLE
借助战打OF-1赚信用不执行

### ISSUE THREAD

**Issue by SHMiris** [MaaAssistantArknights/MaaAssistantArknights#8930]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

一键长草-获取信用及购物，在勾选借助战打OF-1赚信用情况下不会执行

### Version

Resource Version: 巴别塔
UI Version: v5.2.1
Core Version: v5.2.1

### 日志文件

自行翻阅gui.log后发现最后一次执行是4.13，此后因为个人时间问题直到最近几天才发现问题
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15142578/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15142579/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131992167/5ebd8f53-54a5-4ef4-af74-947f73dfa12a)
![Snipaste_2024-04-28_23-07-14](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/131992167/fa87a4df-7e3a-4707-a979-90a9405344c6)

### 还有别的吗？

雷电9.0.65
Win 10 家庭中文版

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/69445f43-d788-4be1-87c2-5daa47d6feb2)

**Comment by SHMiris** [comment]
没看见这提示，懂了
因为生息演算更新以后UI有概率找不到关卡，才选择的当前/上次
