### ISSUE TITLE
指定战斗次数无效

### ISSUE THREAD

**Issue by zlqd123** [MaaAssistantArknights/MaaAssistantArknights#8937]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在作战次数中设置战斗一次，但实际上战斗到没有理智才结束

### Version

Resource Version: 巴别塔
UI Version: v5.2.1
Core Version: v5.2.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15144854/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15144855/gui.log)

### 截图

![屏幕截图 2024-04-29 092853](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/32678715/a124dfc4-3ab1-4049-9f02-34f30fc8436d)

### 还有别的吗？

MUMU12
win11

**Comment by ABA2396** [comment]
指定 “当前/上次” 一次，然后所有剩余理智打BB-8，有什么问题吗？

**Comment by Saratoga-Official** [comment]
你把剩余理智选项取消了就正常了，不是bug，直接把issue关了吧
