### ISSUE TITLE
肉鸽自定义选择难度烧开水

### ISSUE THREAD

**Issue by LYYAradn** [MaaAssistantArknights/MaaAssistantArknights#8938]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

box很菜，新三幻神又没有，高难打不过喵，能做的话就大感谢了

**Comment by AI-Kyo-er** [comment]
+1，同样的问题，MAA在N15很有可能无法烧开开水

**Comment by ntgmc** [comment]
Duplicate of #8926
