### ISSUE TITLE
开机自启动maa会同时打开两个maa

### ISSUE THREAD

**Issue by Viviannas** [MaaAssistantArknights/MaaAssistantArknights#8940]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

开机自启动maa会同时打开两个maa，但是后面手动运行就是正常打开一个maa

### Version

Resource Version: 巴别塔
UI Version: v5.2.2
Core Version: v5.2.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15147737/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15147740/gui.log)

**Comment by ABA2396** [comment]
我记得这个公告都挂了好久了吧？

如果正式版（v4.28.8）用户在安装运行库之后发现设置里的开机自启显示为未勾选，但实际上开机时可以自启，请不要再次勾选，显示问题已在新版本修复，请在更新v5.x版本后再根据下方内容操作。
其余版本遇到开机自启的问题（无法开机自启 / 开机自启多个），请按照以下步骤进行设置：
1. 打开注册表编辑器：Win + R，输入 regedit，回车。
2. 导航至 计算机\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run。
3. 找到值是maa路径的项并全部删除。
4. 重启maa，重新设置开机自启。

**Comment by status102** [comment]
已提供解决方案，超时关闭
