### ISSUE TITLE
过了一晚上突然多出来247GB的log

### ISSUE THREAD

**Issue by Rindonn** [MaaAssistantArknights/MaaAssistantArknights#8941]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![Snipaste_2024-04-30_09-50-11](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/26965857/2c58a09f-f82b-487e-b265-f5f7edb25a95)
一晚上多出来247GB的log，之前没有出现过类似情况。
同时伴随模拟器崩溃和磁盘空间占用满，原因不明

### Version

v5.2.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15156479/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15156480/gui.log)
问题出现时间在4.29 18:00-4.30 9:00之间，但经检查asst中并没有昨天晚上的相关记录，asst.bak由于文件太大影响系统性能只能删除。

### 还有别的吗？

模拟器是mumu3.8.19（2854）
机器信息由aida64生成
[Report.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15156512/Report.txt)
同时间在跑模型训练，不过预留了3GB左右的显存空间，应该影响不大，之前也是这种负载状况没出现过问题。

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/d452aa8e-692b-4c83-9b22-0b62af875a46)
看ui的日志是19:02:37就进入第四个制造站然后core一直卡那儿了，不过就算一直进入退出也不至于有这么大啊，就算跑一天肉鸽也不一定有几个G的日志，有没有可能是mumu报崩溃之后一直往adb里塞信息？
有查看过asst.bak的内容吗？~~虽然我感觉这么大的文件应该已经打不开了~~

cc @MistEO @status102

**Comment by ABA2396** [comment]
模拟器崩溃报的是显卡驱动崩溃吗？导出以下诊断信息

**Comment by status102** [comment]
日志滚动一直有点问题（

**Comment by ABA2396** [comment]
就算日志滚动有问题你开一个月也跑不到247G啊）

**Comment by status102** [comment]
正常滚动的话，大概率还能传一个部分的输出（虽然写入量还是那么多），现在看上去是已经删除了

**Comment by Rindonn** [comment]
模拟器崩溃是指画面不动，任何操作无反应，个人怀疑应该是磁盘空间满了导致的？
文件内容打不开。。为了继续跑模型只能先删除了sad

**Comment by zeptolee** [comment]
可以考虑日志容量超过阈值（例如 1GB）时候分文件存储，且仅保留一下最近 10 个，这样即使被刷爆日志也空间不会耗尽

**Comment by ABA2396** [comment]
> 可以考虑日志容量超过阈值（例如 1GB）时候分文件存储，且仅保留一下最近 10 个，这样即使被刷爆日志也空间不会耗尽

日志超过4M的时候启动就会重新建一个文件

**Comment by Constrat** [comment]
Now with the new Mumu fast screenshot, the size is drastically increased as there's almost x10 times the amount of screens.

**Comment by TiSpH** [comment]
<img width="1042" alt="Screenshot 2024-06-08 at 3 10 38 PM" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/14122965/a60580f2-e5c5-456b-89f8-eb291e8b4525">

在macOS上复现了，直接把其他软件卡崩溃了
log最后几行全在重复这个:
```
[2024-06-08 14:55:11.254][TRC][Pxb92][Txe811] Analyze name filter
[2024-06-08 14:55:11.254][TRC][Pxb92][Txe811] Analyze name filter
[2024-06-08 14:55:11.254][TRC][Pxb92][Txe811] Analyze name filter
[2024-06-08 14:55:11.254][TRC][Pxb92][Txe811] Analyze name filter
[2024-06-08 14:55:11.254][TRC][Pxb92][Txe811] Analyze name filter
[2024-06-08 14:55:11.254][TRC][Pxb92][Txe811] Analyze name filter
[2024-06-08 14:55:11.254][TRC][Pxb92][Txe811] Analyze name filter
[2024-06-08 14:55:11.254][TRC][Pxb92][Txe811] Analyze name filter
[2024-06-08 14:55:11.254][TRC][Pxb92][Txe811] Analyze name filter
[2024-06-08 14:55:11.254][TRC][Pxb92][Txe811] Analyze name filter
[2024-06-08 14:55:11.254][TRC][Pxb92][Txe811] Analyze name filter
[2024-06-08 14:55:11.254][TRC][Pxb92][Txe811] Analyze name filter
```

**Comment by TiSpH** [comment]
虽然不知道发生了什么，建议先把 `MaaAssistantArknights/src/MaaCore/Task/Infrast/InfrastProductionTask.cpp` 第 501 行的 `while` 条件从 `!=` 改成 `<=`

<img width="906" alt="Screenshot 2024-06-08 at 3 44 57 PM" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/14122965/3498c343-2082-4cc6-9971-0ad5b905668d">

**Comment by TiSpH** [comment]
`asset.log` 的 112.86 GB 中只有前 756 KB 是有效的，后面全是重复相同内容
精简版在这：[asst_short.log](https://github.com/user-attachments/files/15749935/asst_short.log)

**Comment by horror-proton** [comment]
Let me guess, the correct behaviour should be
```diff
if (name_analyzer.analyze()) {
  ...
} else {
  hash_matched = false;
}
```
