### ISSUE TITLE
使用作业集战斗列表时，不能跳过剧情

### ISSUE THREAD

**Issue by LinYanxi0** [MaaAssistantArknights/MaaAssistantArknights#8947]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

rt

### 有什么好的想法？

在添加作业集并勾选战斗列表时，战斗前后检测剧情并跳过

**Comment by status102** [comment]
这是Bug，需要提供log，新开一个issue吧
