### ISSUE TITLE
日服 ツヴィリングトゥルムの黄金 自动战斗选择错误

### ISSUE THREAD

**Issue by ajk946009123** [MaaAssistantArknights/MaaAssistantArknights#8948]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动战斗的时候会点到上面的奖励获取

### Version

Resource Version: ツヴィリングトゥルムの黄金
UI Version: v5.2.3-alpha.1.d004.g084fbb6f1
Core Version: v5.2.3-alpha.1.d004.g084fbb6f1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15176478/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15176479/gui.log)

### 截图

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46643530/19c176c3-d896-450f-a33b-6cf2ccda2a54)

**Comment by Constrat** [comment]
cc @Manicsteiner

**Comment by Manicsteiner** [comment]
没有复现此问题，但遇到了奇怪的逻辑问题。
使用“当前-上次”，进入ZT-8，会在不修改连续作战次数的情况下开始作战。但是会匹配到一个 FightSeries-Indicator.png ，ROI位置都能完美复现：
```
[2024-05-01 19:11:49.291][TRC][Px8760][Txa0dc] match_templ | FightSeries-Indicator.png score: 0.80207 rect: [ 951, 432, 45, 51 ] roi: [ 940, 190, 80, 380 ]
```
```
[2024-05-01 22:02:38.999][TRC][Px758][Tx4c1c] match_templ | FightSeries-Indicator.png score: 0.802997 rect: [ 951, 432, 45, 51 ] roi: [ 940, 190, 80, 380 ]
```

**Comment by Manicsteiner** [comment]
大概理解原因了，就是错误识别到了 FightSeries-Indicator.png 导致点击了报酬区域。
目前的想法是 task.json 的 FightSeries-Indicator 任务添加一个 templThreshold 0.9 或 0.95，正常可以达到 0.99 以上。
