### ISSUE TITLE
自动战斗干员下不去

### ISSUE THREAD

**Issue by 2314933036** [MaaAssistantArknights/MaaAssistantArknights#8949]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动战斗不会自动下干员，第一个干员费转好后没下去后面几个干员在几秒内日志显示都下去了，实际一个都没下去，空城寄了属于是

### Version

5.2.2巴别塔

### 日志文件

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/38069007/9e5429a7-4bfe-46b5-ae5e-43c8fb67bba2)

使用的是蓝叠模拟器国际版

**Comment by 2314933036** [comment]
试了5，6份作业都这样，一个干员都放不下去

**Comment by 2314933036** [comment]
试了下打开“暂停下干员”一直在暂停立马继续，干员并没下去

**Comment by Constrat** [comment]
That's not a log file.
check
- debug/asst.log
- debug/asst.log.bak

**Comment by status102** [comment]
缺少log关闭
