### ISSUE TITLE
我刚用了两天，有几点建议

### ISSUE THREAD

**Issue by KuiPer-LTW** [MaaAssistantArknights/MaaAssistantArknights#895]
（按我个人需求的轻重缓急排序）
1. [x] 刷固定数目材料时偶发的识图错误导致多打关卡浪费理智——能否在每次结束作战是点一下材料确认数量，又或者是发生了识图错误后会主动点击报酬查看数量纠正，又或者是彻底解决识图错误hh

2. [x] 把使用无人机的功能独立，就是在基建设置里独立——因为现在要是用无人机就必须勾选贸易站换班，我个人是只有一个贸易站用巫恋组加菲亚梅塔永续的，不需要换班，所以建议无人机独立，多个贸易站就优先选择巫恋组使用

3. [x] 自动公招三星时能把时间定为7小时40分吗，能省一丁点龙门币（积少成多嘛），四星就还是9小时吧，我个人是有7小时40的四星被划掉的

4. [x] 考虑到每个人的box都不一样，可不可以基建换班时就单纯的识别名字，然后由用户自定义换班干员，再加上已有的心情检测，我看会客室甚至可以选择对应派系的干员，这个功能应该不难吧（我啥也不懂，如果冒犯到了果咩）（其实这应该是官方要做的功能才对，不过大概率基建2.0都不可能有这功能了，这样就可以人为降低基建效率→多氪源石刷钱和狗粮）

5. [ ] 理智报警（可以自定义多少理智）和基建定时检查（定时进入基建收菜以及专精，心情消耗和好友线索接收提醒），不过这些前提是软件能放后台，就最小化到任务栏右下角，不然做出来我也不愿意一直挂个软件在底下

6. [ ] 每周一访问好友基建时，固定访问五次（每周任务）

7. [x] 信用商店优先购买可露希尔的大减价，还有同一种商品优先购买更大折扣的
（6、7我没有在详细介绍里看到，姑且先写上）

非常感谢你们的付出！

**Comment by ABA2396** [comment]
基建现在有了自定义基建配置，都是识别文字，无人机的使用也可以配置，详细可以看https://yituliu.site/riicCal
公招设置里现在加了3星指定7小时40分的功能，可以去设置里开
商店是逻辑是优先购买白名单从前往后买，再排除黑名单从前往后买，降价的本来就排在前面，所以会优先购买

如果还有其他的建议可以开一个新的issue
