### ISSUE TITLE
公招出现新标签【元素】，无法进行手动确认

### ISSUE THREAD

**Issue by sakuraxp** [MaaAssistantArknights/MaaAssistantArknights#8953]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前应该是只有新的辅助小车用得到【元素】标签。当出现【元素】标签时，虽然已经检测到了1星tag（或tags组合），但还是当三星tag自动处理了。

### 有什么好的想法？

调整“”手动确认【支援机械】”的处理逻辑，增加【元素】，使得可以收工确认。

**Comment by SherkeyXD** [comment]
干脆给这个选项改为“手动确认一星词条得了”（

**Comment by ABA2396** [comment]
只能说这个词条刚好现在只有小车）

**Comment by Toby-Shi-cloud** [comment]
目前硬编码了一个）因为发现原『支援机械』tag就是硬编码的。。。
