### ISSUE TITLE
水月肉鸽无法部署维什戴尔

### ISSUE THREAD

**Issue by canmio** [MaaAssistantArknights/MaaAssistantArknights#8955]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用自动肉鸽功能时，指定开局干员维什戴尔，可以正常招募和编队，但是进入肉鸽关卡后一直选中维什戴尔拖动后并未部署到场地上，之后会一直重复该动作

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.2
Core Version: v5.2.2

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15186329/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15186362/asst.zip)
问题出现时间大概为17:30左右

### 还有别的吗？

模拟器为mumu模拟器，怀疑将维什戴尔识别为了地面单位，部署的时候没有往高台上拖

**Comment by yuanweifeng823** [comment]
萨米肉鸽存在相同问题，经过多局观察，原因为：维什戴尔会往地面部署导致无法成功部署

**Comment by Manicsteiner** [comment]
还没更新肉鸽的部署方案呢，需要等人工适配
