### ISSUE TITLE
在活动结束前设置活动关卡的材料刷取计划，活动结束后跳转到非备用关卡刷取材料

### ISSUE THREAD

**Issue by blackmoonow0** [MaaAssistantArknights/MaaAssistantArknights#8958]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，在5.2晚上设定巴别塔活动BB-7的刷取计划，且指定了备用关卡，但是在4点活动结束后，MAA未跳转到指定关卡刷取材料，而是跳转到了汐斯塔 新旅店大道 刷理智

### Version

V5.2.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15196954/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15196957/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49943092/9608bac8-17c8-45bf-8cb6-996b5318a7d1)
材料刷取时的设置
MAA的运行截图不小心点掉了，所以没放上来

### 还有别的吗？

使用模拟器:MUMU12
操作系统:win11 家庭版 64位
相关配置：
处理器:	12th Gen 英特尔 酷睿 i5-12400 六核
主板:	华硕 TUF GAMING B760M-PLUS WIFI (  )
内存:	32GB DDR5 6400MHz ( 16GB + 16GB )
显卡:	NVIDIA GeForce RTX 4060 Ti ( 8GB / 七彩虹 )
显示器:	Redmi Monitor [小米 XMI23C3] ( 23.8英寸 )
硬盘:	ZHITAI PC005 Active 1TB ( 1024GB )
	ZHITAI TiPlus7100 2TB ( 2048GB )

**Comment by ABA2396** [comment]
4点闪断后是没有导航的，直接进的上次关卡

**Comment by blackmoonow0** [comment]
草，好合理，断线重连进关卡就是进上次打的那一关
