### ISSUE TITLE
粥专用版mumu不支持最新的低延迟模式

### ISSUE THREAD

**Issue by LiGithubYu** [MaaAssistantArknights/MaaAssistantArknights#8965]
### 说说你遇到的问题？

RT 试了没反应 装mumu官网的最新版才能用

**Comment by ABA2396** [comment]
嗯，这两个更新是分开的

**Comment by Saratoga-Official** [comment]
插一句题外话，最好别用方舟专版mumu，比官方mumu垃圾多了，能用官方还是建议用官方

**Comment by LiGithubYu** [comment]
> 插一句题外话，最好别用方舟专版mumu，比官方mumu垃圾多了，能用官方还是建议用官方

好的谢谢
