### ISSUE TITLE
使用最新版的mumu连接，无法操作

### ISSUE THREAD

**Issue by haibara-brownie** [MaaAssistantArknights/MaaAssistantArknights#8969]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用最新版的mumu连接，延迟显示很低，但是无法操作，mumu路径已改为正确路径，mumu是官网更新的最新版，maa是推送的内测版最新版

### Version

UI Version: v5.2.4-alpha.1.d002.g605dcda98
Core Version: v5.2.4-alpha.1.d002.g605dcda98
Resource Version: 慈悲灯塔

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15204443/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15204445/gui.log)
大概时间在3点45左右

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/71000573/9c960f06-4af3-45e5-a14d-b1e9cc62368a)

**Comment by status102** [comment]
```
[2024-05-04 03:46:22.525][TRC][Px52b0][Tx56e8] asst::WordOcr [{ [分钟,100%领现金红包: [ 6, 19, 161, 13 ], score: 0.881651 }, { 荒野迷: [ 259, 111, 40, 17 ], score: 0.999440 }, { 恐龙快: [ 259, 134, 40, 13 ], score: 0.918491 }] by OCR Pipeline , cost 238 ms
[2024-05-04 03:46:22.525][TRC][Px52b0][Tx56e8] Proceed []
[2024-05-04 03:46:22.525][TRC][Px52b0][Tx56e8] asst::PipelineAnalyzer::analyze Visit@NotDownloadVoice
```

看上去像是Mumu桌面去了，检查是否填写正确，特别是多开

**Comment by a1623382** [comment]
我这里也遇到了同样的问题，但是没有多开的情况，请问该如何获取正确的实例编号和屏幕编号

**Comment by Rbqwow** [comment]
把后台保活关了就行 具体说明等官网文档部署上去再看

**Comment by a1623382** [comment]
> 把后台保活关了就行 具体说明等官网文档部署上去再看

这个我看commits已经解决了，但是里面的“实例屏幕”看了还是需要愣一下😂
