### ISSUE TITLE
在出现多个非同时开启的活动时会出现识别失误等bug

### ISSUE THREAD

**Issue by KIRIZAMERAN** [MaaAssistantArknights/MaaAssistantArknights#897]
模拟器：MUMU
版本：2.6.27.0（x64）（20220511141628）
模拟器分辨率：1920*1080  DPI：320
助理版本：3.9.8
助理日志：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8914921/asst.log)
问题描述：
1.在未勾选“刷肉鸽”的情况下，“刷理智”功能会在终端界面中进入集成战略，造成任务出错，并且无论是直接选关卡还是“上次作战”均无法正确识别，长时间放置会出现点开公告无法退出的情况，不知是否因为在集成战略更新“沉默之章”后，终端界面中“尘影余音”在左侧的入口被“集成战略”替代的影响。
2.终止任务后，取消“刷理智”功能，保留访问好友、收取信用、领取奖励功能并重新启动后，依然无法正常运行，表现为会打开设置界面并停顿，一段时间后显示“任务已完成”。

**Comment by lz0709** [comment]
版本更新后同遇到了这个问题，感觉应该是每一个版本更新，界面变动之后基本都会遇到的问题，只能等大佬肝更新，但绝对这个样子其实比较麻烦。希望可以增加一个手动进入活动的过程，如未识别到关卡入口时，弹出通知，让玩家手动进入，虽然增加了玩家端的操作，但是可以避免每一次界面更新之后，短时间内难以进入刷理智的过程。如果可以甚至可以记录玩家的每一步操作点坐标，并提供开关，首次执行以后之后就由系统根据录制的玩家操作来进入活动关卡

**Comment by ABA2396** [comment]
重新写了导航，但是选择 `上一次` 照理来说不会有影响，看日志里有识别到 `继承` 两字，这个是在哪里的

**Comment by KIRIZAMERAN** [comment]
在任务进程进入集成战略后，放置并等到提示任务出错后，会出现点击进入“本月委托栏”界面现象，“继承”出现于此处。
![image](https://user-images.githubusercontent.com/37176898/174044276-538cf4c9-3fdd-478b-aa13-26d462e445f0.png)
此外，若等待到刷理智任务出错，由助手继续下一步时，便会出现第二点的情况：打开设置——退出设置——打开公告——
提示任务完成。
并且日志中
OcrPack::recognize | raw :  耳排 : [ 20, 95, 101, 31 ], score: 0.607087, 电19 : [ 149, 92, 77, 34 ], score: 0.753696, 手 : [ 187, 16, 61, 49 ], score: 0.181199, 公开招募 : [ 30, 11, 120, 42 ], score: 0.984461, 
是在进入集成战略后界面后，打开本月委托栏前出现的

**Comment by zzyyyl** [comment]
> 关卡选择所有选项失效，全都会进入集成战略界面

这跟我 #901 说的一样，表现的也差不多

**Comment by zzyyyl** [comment]
这个问题的引发原因不是标题所说 `在出现多个非同时开启的活动时会出现识别失误`，而是因为截图失败引起的（
大概原因可能是我在 #901 说的

> 模拟器上的表现就是点进终端然后停了，好像 m_image **没更新也没释放** ，导致第二次重新使用了之前的图，又点了终端的位置，但由于这个时候已经在界面里了，直接点到肉鸽（

~~总之是玛丽的原因不是学姐的原因（大概~~

**Comment by MistEO** [comment]
修了，试试这个版本 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/2509473470

**Comment by KIRIZAMERAN** [comment]
使用正常了
