### ISSUE TITLE
virtualbox占用cpu非常高

### ISSUE THREAD

**Issue by qq994376571** [MaaAssistantArknights/MaaAssistantArknights#8971]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

截图时间一开始都正常，没一会就跑到1000ms，然后模拟器卡死，一看virtualbox headless frontend把cpu占满了。这应该不是性能问题，不开maa的话virtualbox headless frontend 占用很低10-20%，再加上重装系统前都正常，也是win10系统。随着maa开启战斗第一轮该占用会翻倍，第二轮战斗又会翻倍，最后cpu吃满卡死。我感觉是每次点击都会导致占用提升且不会降低。所以这是什么原因导致的？用的雷电9

### Version

最新的稳定版，其余版本也有这个问题

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15205332/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15205334/gui.log)

**Comment by status102** [comment]
duplicate

（先关了discuss，后来又在discuss那边讨论就关issue了
