### ISSUE TITLE
萨米肉鸽凹密文板开局会进入战斗

### ISSUE THREAD

**Issue by kjsbhyy** [MaaAssistantArknights/MaaAssistantArknights#8972]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在使用MAA凹开局密文板的时候会莫名其妙进入战斗开始打架

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.3
Core Version: v5.2.3

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15205612/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168874278/d1f203f4-8223-4777-895e-24fe47b0dbda)

**Comment by status102** [comment]
cc @Lancarus

**Comment by Lancarus** [comment]
请上传asst.log
