### ISSUE TITLE
关卡名识别错误(14-20)

### ISSUE THREAD

**Issue by heeeeeeeelp** [MaaAssistantArknights/MaaAssistantArknights#8973]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，在尝试代理14-20的时候会卡住，但是换成其他关卡都没有这个问题·

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.3
Core Version: v5.2.3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15205827/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15205828/gui.log)

### 截图

<img width="1228" alt="017a4b93d481cc6ec78c4a21535e7f7" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/116091601/a4d61448-b223-4ed8-981d-1614f5dbc986">

### 还有别的吗？

系统是win10，我确定昨天还能正常跑，但是今天更新的时候报了个错，之后就卡在14-20了，已经尝试了重启模拟器，重启maa，重装maa，但是一直这样

**Comment by ABA2396** [comment]
14-20有时候会识别成1420，没太搞懂为什么，到时候要重新训练一下模型了
