### ISSUE TITLE
保全派驻模式异常：多索雷斯商业地块LT-4 闻风而来 高台干员部署不上 疑似坐标问题+干员不放技能

### ISSUE THREAD

**Issue by junyihan233** [MaaAssistantArknights/MaaAssistantArknights#8974]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

保全派驻模式异常：
我是该保全作业的作者，DL_君逸寒。
多人找我反馈：多索雷斯商业地块LT-4 闻风而来，高台干员部署不上。
我自己跑了一下，确实如此。明明之前5.2.1版本是好用的（悲...
我核对了作业站和脚本文件，确认脚本数据无误。

坐标[7,2][7,4]位置的干员一直部署不上，应该是坐标问题；
同时发现，干员的技能放不出来（日志文件中，[7,3]位置的刻俄柏不放技能，不知道能不能体现出来），可能是节能模式的问题：因为高台干员没摆上，所以手牌区一直没变化，就进入了节能模式？

当前maa版本：MAA-v5.2.4-alpha.1.d002.g605dcda98-win-x64

希望早日修复

### Version

当前maa版本：MAA-v5.2.4-alpha.1.d002.g605dcda98-win-x64

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15206078/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15206079/gui.log)

完全就是第四关的日志，之前的日志我删了，直接打开第四关跑的，直接看就行

### 截图

![Screenshot_20240504-091114](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/84064064/344611bb-b8de-4426-9704-4e88fa827bdb)
这是我在另一个模拟器跑的图，意思是那个意思，[7,2][7,4]坐标放不上人，其他位置技能也放不出来，可能是节能模式的问题

**Comment by junyihan233** [comment]
![闻风而来](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/84064064/0db8bae6-5a97-42cf-8ca2-a0d4fc4f68bb)
debug里的地图坐标图

**Comment by junyihan233** [comment]
![闻风而来](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/84064064/cce8ccd7-7411-47fd-acfd-af2a4e333002)
再补一张，这是我另一个双开的maa的debug里的地图坐标图

**Comment by ABA2396** [comment]
cc @yuanyan3060

**Comment by Neptune1990** [comment]
+1

**Comment by yuanyan3060** [comment]
鹰角修改了这个地图的参数
资源库已修复（https://github.com/yuanyan3060/ArknightsGameResource/commit/65323bc596be6d3782889a6bc51a8d5e97085919）

需要重新拉取资源文件

**Comment by yuanyan3060** [comment]
![Uploading 4.png…]()

**Comment by yuanyan3060** [comment]
![4](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/58114805/8f8bd27e-1689-4582-ad99-5125c80925bd)
