### ISSUE TITLE
”自动检测连接“疑似异常：检测路径持续错误

### ISSUE THREAD

**Issue by Ahelucie** [MaaAssistantArknights/MaaAssistantArknights#8975]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

打开”自动检测连接“后，MAA无法找到模拟器（MuMu12），自行确认后，发现自动检测的路径与实际不符

### Version

v5.2.3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15206349/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15206350/gui.log)

### 截图

![屏幕截图 2024-05-04 100031](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168856903/3d6027f4-28ad-4b53-ba91-a4946c51aa5d)

### 还有别的吗？

模拟器：MuMu12（刚下的）
（几周前也是·由于MuMu12经常性连不上，后来换了蓝叠5，使用正常）

**Comment by xiaofeiTM233** [comment]
你的安装路径是图上这个吗，因为我记得默认安装路径是`MuMuPlayer-12`来着
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55832499/9591eaa4-3935-4cd4-8b2a-033cc6e1f32d)

**Comment by Ahelucie** [comment]
> 你的安装路径是图上这个吗，因为我记得默认安装路径是`MuMuPlayer-12`来着 ![image](https://private-user-images.githubusercontent.com/55832499/327991406-9591eaa4-3935-4cd4-8b2a-033cc6e1f32d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4ODY4OTYsIm5iZiI6MTcxNDg4NjU5NiwicGF0aCI6Ii81NTgzMjQ5OS8zMjc5OTE0MDYtOTU5MWVhYTQtMzkzNS00Y2Q0LThiMmEtMDMzY2M2ZTFmMzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDA1MjMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNDk4ZjA2ZGJlZWQ3OWQ2MjY3Mjg1MzRlN2M4MjE2MDAwZmY5MmJiODEzMjNiMDYzM2RjNDIwMDY5OGZlMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4OXsIO7Fh4Pr2NuLvKYSdXrkXB_fktTzeoIXVR02L2E)

是

**Comment by ABA2396** [comment]
.\ 是当前路径，这两个是一样的。
asst.log 只到 09:05:13.917 ，没有你说的这个时间段的日志

**Comment by Ahelucie** [comment]
> .\ 是当前路径，这两个是一样的。 asst.log 只到 09:05:13.917 ，没有你说的这个时间段的日志

这个文件到这之后就不更新了
![屏幕截图 2024-05-04 100031](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168856903/544b1db2-d04a-46f6-a1af-ee11e3ac386e)

**Comment by ABA2396** [comment]
关了maa之后再提交

**Comment by Ahelucie** [comment]
> 关了maa之后再提交

没有。而且前两晚都是选的“关闭 MAA 和 模拟器”，它也确实自己关了的

**Comment by Ahelucie** [comment]
> 关了maa之后再提交

删了文件才开始重新记录，里面最早的时间也只到刚才
