### ISSUE TITLE
水月肉鸽结算画面异常

### ISSUE THREAD

**Issue by nongjialaoxianyu** [MaaAssistantArknights/MaaAssistantArknights#8976]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

水月肉鸽结算时maa无法进行下一局，停留在结算画面上，maa系统无法识别，不能进行下一步重开一局

### Version

UI Version: v5.2.3-alpha.1.d019.g60af8c0f1
Core Version: v5.2.3-alpha.1.d019.g60af8c0f1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15206406/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15206407/gui.log)

### 截图

![2024-05-03_23-11-16-129_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168881974/53e15d8e-9c8d-4f81-85b0-a0053202e87a)
![2024-05-03_23-11-16-129_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168881974/6cc97bb4-962c-47f8-8e56-9502e405f48d)

### 还有别的吗？

mumu模拟器12

**Comment by nongjialaoxianyu** [comment]
maa卡在数据回溯就不动了，且maa行为列表无任何记录

**Comment by megumi77625** [comment]
同，一开始还能继续，现在常常碰到结算卡住，不知道什么情况

**Comment by DeparturePluto** [comment]
同，结算时maa会卡住，最后一条记录为开始关卡，也不会触发error导致任务结束
![微信图片_20240515153534](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/101921030/55b9fc51-b9af-4e62-91ec-a06b2f96b24b)

**Comment by xxXie-1075121458** [comment]
我也碰到了同样的问题

**Comment by 742974687** [comment]
碰到了一样的问题，而且魁影和水月都有这个问题，结算界面有几页不识别，卡在那里不会继续

**Comment by yangqingyuan-byte** [comment]
我也遇到了一样的问题，希望可以解决
