### ISSUE TITLE
maa每日限定池免费赠送单抽寻访出错

### ISSUE THREAD

**Issue by jxdragon103** [MaaAssistantArknights/MaaAssistantArknights#8977]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

运行领取奖励中的“进行限定池赠送的每日免费单抽”时，在正常进入干员寻访界面后未自动判断是否为限定卡池导致在抽取界面出错。

### Version

![0fc6c7bee15246f8e1b993f1edb8771](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168882325/f9d39a63-8e7f-4746-b816-1b3bb14c45b5)

### 日志文件

11时26分开始,只运行领取奖励中的“进行限定池赠送的每日免费单抽”,大约20秒后出错
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15206523/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15206524/gui.log)

### 截图

![ca4a5bc7f51a7a183e78504a0167051](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168882325/d80ea49c-987a-4b7e-86e0-e50369b6d0ee)
![a520bb8f1863fa635d5d090172e9c7d](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168882325/ee369d4f-b0b7-466e-890a-64564e2d75fa)
![fecafde6b0e1723c981b051f0812666](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168882325/a3eb9ec3-787b-4c43-809f-c04e55520066)

### 还有别的吗？

MuMu模拟器12，Windows10操作系统

**Comment by status102** [comment]
是新手池子吗

**Comment by jxdragon103** [comment]
> 抽的是新手池子吗？
> 
> 最后进抽卡页面固定进第一个池子，加上新手池子抽完没，估计没做卡池的切换

是新手池，没有进行判断就自动点击了

**Comment by status102** [comment]
> 是新手池，没有进行判断就自动点击了

点完会抽吗，看上去好像报错自动中止了

**Comment by jxdragon103** [comment]
> > 是新手池，没有进行判断就自动点击了
> 
> 点完会抽吗，估计报错自动中止了

没有抽，在最后提示否花费合成玉的时候卡住了
