### ISSUE TITLE
使用 MuMu 截图方式无法导航至磨难关卡

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#8978]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题 测试使用14-16磨难 使用其他截图方式则无问题

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.4-alpha.1.d002.g605dcda98
Core Version: v5.2.4-alpha.1.d002.g605dcda98

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15206582/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15206583/asst.log)

### 截图

![MuMu12-20240504-121606](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55343783/a95c4639-8b26-4fee-af21-de7c25e8e476)

### 还有别的吗？

对使用mumu截图的issue做点特殊标记吧 有些问题是只在mumu截图下才会出现的
add fight

**Comment by status102** [comment]
Duplicate of #8983

**Comment by status102** [comment]
猜测不是`只有mumu截图才会`，而是原本的延迟比较大，延迟大幅减少导致。之前测过一段时间的minicap，有些其他问题最后没上，上了估计也会有同样的问题
