### ISSUE TITLE
MUMU touch无法正常识别肉鸽关卡

### ISSUE THREAD

**Issue by Black1312** [MaaAssistantArknights/MaaAssistantArknights#8982]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

专用touch无法正常识别肉鸽关卡，minitouch识别正常。

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.4-alpha.1.d002.g605dcda98
Core Version: v5.2.4-alpha.1.d002.g605dcda98

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15208331/asst.log)

### 截图

![e7cd2166890c0124758552966150e6a7](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64343218/c20fa8d6-7dcc-4fc0-a1a7-5effc892bcea)

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64343218/525f619c-13db-4d66-9555-95c2a9e0ef40)

**Comment by ABA2396** [comment]
touch是触控，和识别有啥关系)

**Comment by ABA2396** [comment]
afbe5e2e034018a33169e044d7091579867445e2 fixed
