### ISSUE TITLE
肉鸽开局干员是否可以加上维什戴尔？

### ISSUE THREAD

**Issue by houshuheng** [MaaAssistantArknights/MaaAssistantArknights#8985]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在维什戴尔的强度非常高，已经有很多高难度单人通关各类肉鸽了

### 有什么好的想法？

也不需要维什戴尔单通，但加入开局干员个人觉得更容易挂机

**Comment by status102** [comment]
可以手动输入
