### ISSUE TITLE
[日服] 水月在開端事件反覆選擇選項2與選項3, 無法繼續.

### ISSUE THREAD

**Issue by Mion354D** [MaaAssistantArknights/MaaAssistantArknights#8988]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

[日服] 水月在開端事件反覆選擇選項2與選項3, 但不點選任意選項確定, 無法繼續.

### Version

Resource Version: ツヴィリングトゥルムの黄金
UI Version: v5.2.4-alpha.1.d002.g605dcda98
Core Version: v5.2.4-alpha.1.d002.g605dcda98

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15209557/debug.zip)

### 截图

![0240504-193124](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/7450570/36348133-a622-4116-ad65-644d5c3cefbe)
![20240504-193116](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/7450570/219773cc-d88b-40e0-86a7-d8b599f50f44)

**Comment by Manicsteiner** [comment]
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/971bd1be-78bc-4815-8996-302cfb66a876)
终于知道这关为啥总是识别不出来了，，，字太多，关卡名称卡在识别框外面了
