### ISSUE TITLE
MUMU截图增强模式无法进行操作

### ISSUE THREAD

**Issue by Ahick2** [MaaAssistantArknights/MaaAssistantArknights#8989]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

CPU占用大，时不时就占用40%以上，而且无法进行下一步，可以启动游戏但不会进行操作，游戏bgm卡顿，关闭模式后正常使用

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.4-alpha.1.d016.g7677fac78
Core Version: v5.2.4-alpha.1.d016.g7677fac78

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15209892/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15209893/gui.log)

### 截图

![屏幕截图 2024-05-04 215553](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/65848545/f1eb2f75-2c0c-4d91-91c3-29f0c5138d21)

**Comment by ABA2396** [comment]
把后台保活关了或者把屏幕编号设对，你现在开着后台保活方舟的屏幕编号不是0，截图截到的都是模拟器桌面
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/5abe4c66-27f1-4027-8ec6-a4d5392eee28)

**Comment by Ahick2** [comment]
后台保活关闭后能用了

**Comment by Ahick2** [comment]
开启后台保活后只开启方舟的情况下，把屏幕编号设置为1也可以正常运行

**Comment by Ahick2** [comment]
刚刚测试了下，更改屏幕编号后截图并不是MumuExtrax，而是其他的，延迟也在200ms以上，把屏幕编号改为0后就启用了MumuExtrax延迟也在30ms以内，也就是如果启用后台保活，就要更改屏幕编号，但改完屏幕编号之后就无法使用MumuExtrax来进行截图
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15210031/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15210032/gui.log)

**Comment by Rbqwow** [comment]
已知问题 难修 maa和mumu两头都有问题
