### ISSUE TITLE
自动公招识别报错

### ISSUE THREAD

**Issue by LiGithubYu** [MaaAssistantArknights/MaaAssistantArknights#8994]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

用的mumu极速模式，自动公招提示识别错误已返回，但最终能完成自动公招

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.4-alpha.1.d016.g7677fac78
Core Version: v5.2.4-alpha.1.d016.g7677fac78

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15211429/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15211430/gui.log)

### 截图

![Snipaste_2024-05-05_09-24-29](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/48920551/9e395596-71f3-489c-a81d-d709495efdfe)

**Comment by Rbqwow** [comment]
前几个版本就修了 一直没关(
