### ISSUE TITLE
今早起来自动更新重启之后就一直显示无法找到mumu12模拟器的路径了=.=

### ISSUE THREAD

**Issue by youmengjc** [MaaAssistantArknights/MaaAssistantArknights#8995]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

重启等方式已经试过，也确认了adb端口的路径是正确的（或者可能安装的是内测版的缘故？）

### Version

版本：Core Version: v5.2.4-alpha.1.d021.g79cc49c51（内测版）

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15211608/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15211609/gui.log)
debug中的文件在这儿，问题触发的时间点约为今早10点半刚开电脑这会？（大概）

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168946657/6dc71deb-b271-48a7-bd1f-9464a33df033)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168946657/08cacdd5-1a37-437e-8c71-287eb7d7181c)

### 还有别的吗？

模拟器：mumu12模拟器（最近的几次更新被忽略了）
操作系统：win12，64位
配置总没啥问题，模拟器内部该开的权限也都已经开了

**Comment by AmemiyaMiomy** [comment]
早上一次更新修复了这个问题，然后g79cc49c51这个版本一更新又开始了

**Comment by xutianzhuo** [comment]
同这个问题 ，还没找到解决法子

**Comment by outrosul** [comment]
出现同样的问题，没回退版本，使用MAA_win7.exe可以正常抄作业，MAA.exe就不行

**Comment by mxh1999** [comment]
@youmengjc 把启用Mumu截图增强模式勾上，下面填写模拟器路径就能用了

**Comment by youmengjc** [comment]
> @youmengjc 把启用Mumu截图增强模式勾上，下面填写模拟器路径就能用了

okok，感谢！

**Comment by youmengjc** [comment]
> @youmengjc 把启用Mumu截图增强模式勾上，下面填写模拟器路径就能用了

但是给我卡在连接模拟器这一块了TTvTT
