### ISSUE TITLE
自动战斗补充低信赖干员仅选择特别关注

### ISSUE THREAD

**Issue by ICraZY-EE** [MaaAssistantArknights/MaaAssistantArknights#8996]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

以前自动战斗补充低信赖干员时，会保持在特别关注干员的列表内选择低信赖的干员。最近观察到会先取消特别关注的列表，在全部干员的列表内寻找低信赖干员。

### 有什么好的想法？

希望增加一个选择项，控制是否选择特别关注干员。对于想优先刷6星干员信赖的来说，加在特别关注里面可以最先刷。否则就要去输入追加自定干员。

### 其他内容

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57562450/cbdd0d9e-4505-4829-b730-4ce569e441f4)

**Comment by status102** [comment]
观察到如果特别关注都是满信赖后将会添加满信赖的特别关注干员进入编队，遂添加关闭特别关注的机制。

如果有想要优先刷取的，可以使用补充指定干员
