### ISSUE TITLE
萨米肉鸽路线规划不合理

### ISSUE THREAD

**Issue by BerserkAsuna** [MaaAssistantArknights/MaaAssistantArknights#8998]
### 说说你遇到的问题？

这种情况不应该直接走不期而遇吗？假设下路的不期而遇之后是作战节点，岂不是多了一次作战？况且直走肯定比拐下路耗时短
![QQ图片20240505124007](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97227924/61fc85da-f5c9-4afc-96b9-4fb416fe0688)

**Comment by Saratoga-Official** [comment]
maa不会看下个节点之后是什么节点的，没那么智能

**Comment by Rbqwow** [comment]
解释一下：maa的肉鸽策略是和森蚺一样的“我寻思能行” 全是穷举和固定策略 没有ai成分 不会灵活判断

**Comment by Constrat** [comment]
Considering the new Foldartal view, something could be implemented, maybe not necessarily with a neural network. Just imagining all the paths moving through them and giving a +1, -1 score related to what the event will be. Still, stupidly hard to implement and won't change the result much. (Some runs are doomed, especially on high difficulty.)
