### ISSUE TITLE
ADB连接地址检测错误，在正确地址前提下提示Mumu Emulator 12 Path Not Found

### ISSUE THREAD

**Issue by wr123go** [MaaAssistantArknights/MaaAssistantArknights#8999]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

已检查确认Mumu地址填写正确，并设置正确的adb连接地址，开始连接后模拟器正常启动，但无法检测到对应路径下的adb。
同样配置下，5.4及之前一切运行正常。
自行检测后发现，在启用mumu截图增强模式，并在下方地址中重新填写正确的mumu地址后。adb检测成功。填入截图增强路径，但关闭截图增强功能时，adb检测成功。删除路径，并关闭截图增强功能后，adb检测失败。
本错误可以复现，见下方截图。怀疑是adb路径检测使用了错误的路径变量。

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.4-alpha.1.d021.g79cc49c51
Core Version: v5.2.4-alpha.1.d021.g79cc49c51

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15211803/gui.log)

### 截图

![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44311148/b97369ad-2af2-4700-a11e-ddea7bf5f1ab)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44311148/9277260c-566f-45f9-babd-9898c4062c1f)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44311148/cec46a55-b216-4439-9aae-2da211d26973)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44311148/0846358f-60ab-4e2c-ab75-fc639fbabbac)
上图为，未启用截图增强，在正确填入路径，可以自动启动模拟器的情况下，adb检测报错。
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44311148/930414b1-a1b3-445b-8bd3-c66bd293cf07)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44311148/f17492de-bd75-4062-a5a7-970e78993d23)
上图为，启用截图增强后，重新填入路径，adb检测正常，并成功运行。

### 还有别的吗？

windows10
mumu12
昨天更新内测版前一切正常，可正常运行

**Comment by status102** [comment]
v5.2.4-alpha.1.d024 fixed
