### ISSUE TITLE
使用命令行启动

### ISSUE THREAD

**Issue by hjhjfhjhujhh** [MaaAssistantArknights/MaaAssistantArknights#90]
我找了找，好像没有非GUI的版本？里面只有一个本体exe
而且通过命令行打开会报初始化错误
希望加入启动的时候能使用命令行配置参数的功能，至少能配置启动后自动开始，这样就能用bat实现完全自动化了
或者加个“下次启动时自动执行”的设置什么的
（小声：隔壁本体就是命令行，毕竟是py写的，gui是单独的exe，跟那个差不多就行，下图是隔壁的命令行参数）
![B)WDWLXM LQ`I6~9T MZJ2F](https://user-images.githubusercontent.com/89215821/147880703-c35e15a0-62c8-497a-b815-557d4fd726a4.png)

**Comment by MistEO** [comment]
有提供python接口呀，如果会写bat的话，python也可以试一下？_(:з」∠)_

**Comment by hjhjfhjhujhh** [comment]
啊，在readme最上面，对不起没看到...
不过加入命令行支持还是很方便的吧，实现起来也应该不是很难

**Comment by MistEO** [comment]
已有计划提供基于 Python 的 cli 版本，正在开发中_(:з」∠)_
