### ISSUE TITLE
Tile keys `asst::TileKey::Telin`, `asst::TileKey::Telout` means teleporter in/out? 

### ISSUE THREAD

**Issue by horror-proton** [MaaAssistantArknights/MaaAssistantArknights#900]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/fc09e989ae5d1c69ac360188cd2424865d4b743c/src/MeoAssistant/TilePack.h#L42-L43

比较了下主线的几个关卡, 看上去 `levels.json` 里的 `tile_telout`, `tile_telin` 有点像传送门出入口的意思, 数量和位置都挺符合, 不知道对不对 🤔
@MistEO

**Comment by horror-proton** [comment]
非常抱歉没有注意到 issue 模板, 因为我是从代码视图的 reference in new issue 那边创建的, 有可能不符合格式 orz

**Comment by MistEO** [comment]
一开始把 start 和 end 搞混了，分不清哪个是红门哪个是蓝门，换个名字感觉好理解一点（~~也可能只是对我来说好理解一点~~
