### ISSUE TITLE
萨米肉鸽凹维什戴尔开局精二maa看完重装券就重开了，不看狙击券

### ISSUE THREAD

**Issue by cluelsophiet** [MaaAssistantArknights/MaaAssistantArknights#9000]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽凹维什戴尔开局精二maa看完重装券就重开了，不看狙击券

### Version

Core Version: v5.2.3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15211998/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15212000/gui.log)
大概在5月5日14:40左右

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/88939173/ae991964-308a-465c-96b1-af1d59fa23c2)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/88939173/c34d17d9-6e55-4335-97c7-ca63814dabf3)

### 还有别的吗？

mumu12模拟器

**Comment by ABA2396** [comment]
凹维什戴尔开局精二那你倒是在开局干员里写上名字啊
