### ISSUE TITLE
希望自动公招可以手动选择【支援机械】词条的功能可以添加手动选择【元素】词条

### ISSUE THREAD

**Issue by enthlinn-1228** [MaaAssistantArknights/MaaAssistantArknights#9002]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

新的辅助小车有新的【元素】词条并且可以单锁小车，希望可以加入手动选择功能里

### 有什么好的想法？

希望【元素】词条可以进行手动选择

**Comment by Rbqwow** [comment]
duplicate of #8953
