### ISSUE TITLE
希望自动战斗能增加一个可选功能：编队时若缺少某干员，自动借助战

### ISSUE THREAD

**Issue by Sigritstorm** [MaaAssistantArknights/MaaAssistantArknights#9006]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

战斗列表功能非常好用，不过由于缺少某个作业常客干员，导致编队无法进行，因而只能手动借助战再用自动战斗

### 有什么好的想法？

因为往往只缺少一个干员，如果能在自动编队检测到缺少这一个干员后，直接去助战中借来进入战斗就好了
不过可能实现上确实会有些麻烦，比如要额外去识别助战干员的技能之类的

**Comment by Rbqwow** [comment]
#6458

**Comment by status102** [comment]
Duplicate of #6023
