### ISSUE TITLE
MAA无法识别肉鸽特里蒙旅行社特派团,遇见后无法下一步然后自动结束当次探索

### ISSUE THREAD

**Issue by TheMass114** [MaaAssistantArknights/MaaAssistantArknights#9007]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA无法识别肉鸽特里蒙旅行社特派团,遇见后无法下一步然后自动结束当次探索

### Version

UI Version: v5.2.4-alpha.1.d023.g76b03fdda

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15212731/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15212732/gui.log)
18点19分,遇见截图上的事件后不动了然后MAA自动退出

### 截图

![QQ图片20240505193820](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168968481/d10168d0-9e38-46d7-8982-54ff659701fb)

**Comment by Manicsteiner** [comment]
asst.log 是空的，请上传 asst.bak.log
