### ISSUE TITLE
挂肉鸽会死机

### ISSUE THREAD

**Issue by dazzlingwind** [MaaAssistantArknights/MaaAssistantArknights#9009]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

单选肉鸽模式开始挂机，在一段时间后会死机本次问题发生在2024-05-05 20:16:26.135之后，死机状态为卡死，不显示蓝屏

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.3
Core Version: v5.2.3

### 日志文件

[asst&gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15213051/asst.gui.zip)

### 还有别的吗？

模拟器为mumu，操作系统为win11（22631.3447），i7-13700k，DDR4-32GB，3080TI

**Comment by Daydreamer114** [comment]
asst.log没有涵盖错误发生的时间段

**Comment by dazzlingwind** [comment]
bak.log里有算吗
