### ISSUE TITLE
v3.9.8 雷电模拟器无法正常运行

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantArknights#901]
软件是能打开的，也能连上模拟器，但是好像截了一张图后面就寄了，上log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8915645/asst.log)

画风是这样的
```
asst::Controller::screencap  | enter 
asst::Controller::call_command | `D:\leidian\LDPlayer64\adb.exe -s emulator-5554 shell "screencap | nc -w 3 172.16.1.2 6723"`  | enter 
Call ` D:\leidian\LDPlayer64\adb.exe -s emulator-5554 shell "screencap | nc -w 3 172.16.1.2 6723" ` ret 0 , output size: 3686412 
asst::Controller::call_command | `D:\leidian\LDPlayer64\adb.exe -s emulator-5554 shell "screencap | nc -w 3 172.16.1.2 6723"`  | leave, 198 ms 
asst::Controller::convert_lf  | enter 
asst::Controller::convert_lf  | leave, 2 ms 
data is not empty, but image is empty 
asst::Controller::screencap  | leave, 201 ms 
```
然后不断循环

模拟器上的表现就是点进终端然后停了，好像 m_image **没更新也没释放** ，导致第二次重新使用了之前的图，又点了终端的位置，但由于这个时候已经在界面里了，直接点到肉鸽（
![Screenshot_20220616-122720](https://user-images.githubusercontent.com/74587068/173991258-b05fc4f4-2c10-4f0f-95be-8b8af58bcf43.png)
![Screenshot_20220616-122723](https://user-images.githubusercontent.com/74587068/173991263-794c5cd1-2141-45a1-b0fc-52fac2ebf029.png)
最后停在这个界面
![Screenshot_20220616-122805](https://user-images.githubusercontent.com/74587068/173991331-3346afd4-84dd-4aec-9657-067c20fd2c14.png)

~这几天忙着考试，27考完我就来看看maa~

**Comment by zzyyyl** [comment]
看了 [#896](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/896#issuecomment-1157133914) 的日志，跟我是一个问题，不过表现不一样

**Comment by suzu0bronya** [comment]
我也是滴，耐心等等吧....

**Comment by MistEO** [comment]
修了，试试这个版本 https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/2509473470

**Comment by zzyyyl** [comment]
> `v3.9.8-fix.1` fixed ~奇怪的版本号增加了~

这不会自动更新是不是bug（？

**Comment by zzyyyl** [comment]
@MistEO  `v3.9.9-beta.1` 不能更新到 `v3.9.9`（

**Comment by zzyyyl** [comment]
草， `v3.9.9-beta.1` 甚至不能更新到 `v3.10.0-alpha.1`

**Comment by MistEO** [comment]
> 草， `v3.9.9-beta.1` 甚至不能更新到 `v3.10.0-alpha.1`

我发现了，版本号解析写错了。这下必须得发 4.0 了

**Comment by zzyyyl** [comment]
> > 草， `v3.9.9-beta.1` 甚至不能更新到 `v3.10.0-alpha.1`
> 
> 我发现了，版本号解析写错了。这下必须得发 4.0 了

还有就是断网的时候检查更新也显示的”已是最新版本“，应该要改改显示（？

**Comment by MistEO** [comment]
> > > 草， `v3.9.9-beta.1` 甚至不能更新到 `v3.10.0-alpha.1`
> > 
> > 
> > 我发现了，版本号解析写错了。这下必须得发 4.0 了
> 
> 还有就是断网的时候检查更新也显示的”已是最新版本“，应该要改改显示的文本内容（？

不会写啊（）
