### ISSUE TITLE
日服自動戰鬥無法辨識純燼艾雅法拉、夜鶯；多數幹員辨識時出現錯誤

### ISSUE THREAD

**Issue by GlycosidEMT** [MaaAssistantArknights/MaaAssistantArknights#9012]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

明日方舟-JP服
使用模擬器：BS5 P64
使用自動戰鬥-自動編隊功能時 無法識別純艾(2024-05-06 02:41:17.115)、夜鶯(2024-05-06 02:42:30.051)。
手動編隊進入戰鬥後，不會布置這兩名幹員並且後續不會進行任何動作。
使用幹員辨識功能時，出現多數錯誤(銀灰、塑心、纯烬艾雅法拉、百煉嘉維爾、麒麟R夜刀、艾雅法拉...等等，以及大量四星角色沒有辨識到)

有嘗試使用7z、Bandizip(自動偵測模式)兩種方式解壓縮MAA檔案，多次重裝以及使用公測版、穩定版交叉測試，問題依舊存在。

### Version

Resource Version: ツヴィリングトゥルムの黄金
UI Version: v5.2.3
Core Version: v5.2.3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15214208/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15214209/gui.log)

### 截图

[oper.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15214218/oper.zip)
[oper2.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15214220/oper2.zip)

**Comment by Constrat** [comment]
cc @Manicsteiner
