### ISSUE TITLE
傀影肉鸽进入地图卡在第一关反复重后反复

### ISSUE THREAD

**Issue by Vandi29** [MaaAssistantArknights/MaaAssistantArknights#9014]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

进入地图后第一关在屏幕外（截图界面），导致MAA识别不到反复重新进入肉鸽，时间大概在2024/5/6 的12点20-12点24，我在12点24.40-12点26复现了一次

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.3
Core Version: v5.2.3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15215976/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15215977/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/169016970/aa310372-30a9-4e66-9610-8fe7fc4a97c3)

**Comment by ABA2396** [comment]
重启下游戏，这是方舟的问题，有时候卡成这样之后拖动都不生效了，只能重启游戏解决
