### ISSUE TITLE
MuMu adb 连接超时导致截图失败 / 触控模式不可用

### ISSUE THREAD

**Issue by XuanSuHS** [MaaAssistantArknights/MaaAssistantArknights#9017]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

偶尔出现连不上的问题，即 `触控模式不可用。请进入 设置 - 连接设置 切换其他触控模式。`

自己手动 adb connect 后启动MAA，报错变为 `截图失败，如反复出现请尝试重启或更换模拟器！`

重启几次 MAA 后又好了

补充：关闭 MuMu 截图增强模式可正常使用
### Version

Resource Version : `慈悲灯塔`
UI Version: `v5.2.4-alpha.1.d023.g76b03fdda`
Core Version: `v5.2.4-alpha.1.d023.g76b03fdda`

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15218337/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15218338/gui.log)

## 截图

------
#### 连接设置
![连接设置](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61779028/d61cc6de-3f69-47fb-9a8d-c607f04303d0)

------
#### 任务失败截图
![任务失败](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61779028/082dd8dc-52c8-4a09-a22d-ef841e5f2d36)

------
#### 重启 MAA 后连接成功
![重启后成功](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61779028/b64cd152-9937-4ad4-a479-b700ae466499)

**Comment by XuanSuHS** [comment]
罪魁祸首找到了，是卡巴防火墙
之前参照 [这里](https://www.bilibili.com/read/cv25817263/) 的教程把几个 IP 屏蔽掉了，结果就是每次 `adb connect` 连上 MuMu 之后要等待大概 30s 才能操作。
在教程文章评论区看到也有人出现了这个情况，不知道是不是 MuMu 的特意设计
有没有办法放宽一下 MAA 这边的连接延迟，这大概是一种解决方法？

**Comment by ABA2396** [comment]
启动设置里有启动模拟器后的等待时间

**Comment by XuanSuHS** [comment]
试了下还是不行，附上这次的log
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15231411/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15231413/gui.log)

------
### 图片
![01](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61779028/c2ec4d77-446b-467b-bbf1-42956dddf76c)
------
![02](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61779028/1e78b6ed-66e4-48f8-95a6-a60314643642)

MAA 在首次连接成功之后获取 android_id 超时，后面 把 minitouch 推过去、chmod加权限和执行这三个步骤就炸了

等待启动结束重新开始的时候 MAA 直接就开始调用 minitouch 了，这时候并未重新拿 android_id ，minitouch 也是不存在的，然后就截图失败了
只能手动重启 MAA 让他完整来一遍，这时候 adb 连接过了 30s 就变成正常状态了

**Comment by ABA2396** [comment]
cc @MistEO

**Comment by xiaofeiTM233** [comment]
> 连上 MuMu 之后要等待大概 30s 才能操作

大概不止30s……我通常要1~3分钟才能获取到android_id……所以干脆新建了个任务单独启动模拟器（迫）
去改下专栏让大伙都知道吧……
另，链一下主issue #8109

**Comment by XuanSuHS** [comment]
> > 连上 MuMu 之后要等待大概 30s 才能操作
> 
> 大概不止30s……我通常要1~3分钟才能获取到android_id……所以干脆新建了个任务单独启动模拟器（迫） 去改下专栏让大伙都知道吧…… 另，链一下主issue #8109
> 
> 补充：
> 
> > 在教程文章评论区看到也有人出现了这个情况，不知道是不是 MuMu 的特意设计
> 
> [LmeSzinc/AzurLaneAutoScript#3335](https://github.com/LmeSzinc/AzurLaneAutoScript/issues/3335) 这里有佬抓包看了，似乎是刻意设计

我这边是 adb 连接后任意操作都会卡这 30s
既然如此写个脚本启动 mumu 和 maa 就可以
adb会卡在连接后第一条指令直到 mumu 那边响应完成，这时候再启动 MAA 就绕过去了

```
@echo off
start \path\to\MuMu-Arknights.lnk
:wait
ping 127.1 -n 3 >nul
echo one
"%MUMUPATH%\shell\MuMuManager.exe" api -v 0 player_state | findstr "start_finished" >nul
if NOT %ERRORLEVEL% == 0 ( goto wait )
adb connect 127.0.0.1:16384
adb shell pm uninstall --user 0 com.mumu.store
adb shell pm uninstall --user 0 com.mumu.decorate
start \path\to\MAA.lnk
exit
```

**Comment by xiaofeiTM233** [comment]
> 既然如此写个脚本启动 mumu 和 maa 就可以 adb会卡在连接后第一条指令直到 mumu 那边响应完成，这时候再启动 MAA 就绕过去

干脆让MAA多连一次
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55832499/4672a118-5ce6-43f4-9be8-7297715492ab)

**Comment by XuanSuHS** [comment]
问题出在 android_id，链接主 issue https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8109
