### ISSUE TITLE
希望加入登录人机验证功能

### ISSUE THREAD

**Issue by ghg11** [MaaAssistantArknights/MaaAssistantArknights#9019]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

实体机经常玩粥 导致模拟器不定时跳滑块认证导致maa不能正常工作 希望可以有人机验证的功能

**Comment by ntgmc** [comment]
同一台设备登录太多次才会触发验证码
