### ISSUE TITLE
自动公招bug

### ISSUE THREAD

**Issue by weedi0** [MaaAssistantArknights/MaaAssistantArknights#902]
![image](https://user-images.githubusercontent.com/87680595/174066104-9cb42914-260c-421b-84d0-c3fa1d02695d.png)
![image](https://user-images.githubusercontent.com/87680595/174066158-c32fa528-4b39-4e35-a878-7fed6246427f.png)
因为未选资深干员系统弹出警告信息从而卡死任务。

**Comment by MistEO** [comment]
请附上日志，谢谢~
