### ISSUE TITLE
mumu增强截图模式，如果重启模拟器不重启MAA无法重连上，提示截图失败

### ISSUE THREAD

**Issue by WolfCanglong** [MaaAssistantArknights/MaaAssistantArknights#9021]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

mumu增强截图模式，如果重启模拟器不重启MAA无法重连上，会提示截图失败
重启maa后可以正常用
![QQ截图20240506221408](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40590525/7b7d90e6-a75c-40ff-adbc-c20e3b5e0659)
如果是其他模式，重启模拟器以后MAA是可以重连的

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.4-alpha.1.d023.g76b03fdda
Core Version: v5.2.4-alpha.1.d023.g76b03fdda

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15222018/asst.bak.log)

**Comment by ABA2396** [comment]
你开了模拟器没开方舟，没有序号1的窗口mumu直接报错了。要么自己把方舟开起来，要么把后台保活关了之后窗口序号填0

**Comment by WolfCanglong** [comment]
> 你开了模拟器没开方舟，没有序号1的窗口mumu直接报错了。要么自己把方舟开起来，要么把后台保活关了之后窗口序号填0

没开后台保活，不开这个模式重启模拟器可以自动启动方舟，开了这个不是重连的情况下也能自动启动方舟

**Comment by WolfCanglong** [comment]
> 你开了模拟器没开方舟，没有序号1的窗口mumu直接报错了。要么自己把方舟开起来，要么把后台保活关了之后窗口序号填0

很容易复现的一个问题 你开这个模式完正常运行停止，然后重启下模拟器再开始就知道了

**Comment by ABA2396** [comment]
因为重连第一步就是截图测速，但是你填了窗口一又没有窗口一就报错了，最简单的办法就是把mumu后台保护活了，然后填零。

**Comment by ABA2396** [comment]
因为重连第一步就是截图测速，但是你填了窗口一又没有窗口一就报错了，最简单的办法就是把mumu后台保护活了，然后填零。

**Comment by WolfCanglong** [comment]
> 你开了模拟器没开方舟，没有序号1的窗口mumu直接报错了。要么自己把方舟开起来，要么把后台保活关了之后窗口序号填0




> 因为重连第一步就是截图测速，但是你填了窗口一又没有窗口一就报错了，最简单的办法就是把mumu后台保护活了，然后填零。

我填的是窗口0啊 1是模拟器编号，我这里还有其他多开 每个都是一样的，我填法应该是没问题的，冷启动只要不重启模拟器都是正常的
另外我试了就算手动点开方舟一样是截图失败

**Comment by WolfCanglong** [comment]
> 因为重连第一步就是截图测速，但是你填了窗口一又没有窗口一就报错了，最简单的办法就是把mumu后台保护活了，然后填零。

你说的那个没窗口一的之前也试过 报错不是这样的 是什么mumu extras失败

**Comment by ABA2396** [comment]
cc @MistEO

**Comment by WolfCanglong** [comment]
5.4.0beta1依然有这个问题，同样类似的模式ALAS的nemu_ipc就没有这个问题，重启了模拟器依然可以连上

**Comment by LUYE2233** [comment]
同样的问题
我是单开的，用maa唤起mumu，实例0窗口0就会截图失败，必须先启动mumu再启动maa

**Comment by 050644zf** [comment]
5.4.0beta2仍然有该问题

**Comment by WolfCanglong** [comment]
5.4.1alpha还是有这个问题 真的挺影响使用的 模拟器卡了重启一下也得重启MAA
我觉得可以试试ALAS的逻辑 如果闲置了就把mumu那个截图释放了，下次操作时候再重新连一下

**Comment by ABA2396** [comment]
@MistEO
