### ISSUE TITLE
萨米肉鸽0抗干扰点数一直选择歧路诡意行商

### ISSUE THREAD

**Issue by xinxin1086** [MaaAssistantArknights/MaaAssistantArknights#9023]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽0抗干扰点数一直重复选择歧路诡意行商，然而因为没法扣除抗干扰指数（抗干扰指数为0）所以卡死。

### Version

UI Version: v5.2.4-alpha.1.d023.g76b03fdda

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15228955/debug.zip)

### 截图

![QQ截图20240507105921](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106382379/cdb5741c-ecf6-441c-b1b4-46022a0385cc)
![9ff114eef90241dad31e9076295b4e3b](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106382379/b3682b39-4283-43bf-a052-bce47fa3c0d9)

**Comment by xinxin1086** [comment]
![5894ee7d987fa0f33d7f522ea5bb893c](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/106382379/1550e3f8-96df-46f4-9a16-4d257f70f56d)

**Comment by Lancarus** [comment]
fix in #9223
