### ISSUE TITLE
PlayBridge: External MAA Error

### ISSUE THREAD

**Issue by Erastia** [MaaAssistantArknights/MaaAssistantArknights#9026]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

Google play Beta don't use the maa

### Version

5.2.4-alpya

### Log files

MAA에서 오류가 발생했습니다
External component has thrown an exception.
해결 방법
예상치 못한 오류가 발생했습니다
세부 정보
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at MaaWpfGui.Services.MaaService.AsstConnect(IntPtr handle, Byte* adbPath, Byte* address, Byte* config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(IntPtr handle, String adbPath, String address, String config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<>c__DisplayClass79_0.<ConnectToEmulator>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.ConnectToEmulator()
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.LinkStart()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Screenshots

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/169155371/66d917ef-8fc6-41da-9dc8-7c60d7b6645e)
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/169155371/b3142a13-9c2e-44cf-a7b0-12dfc0e24140)
![3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/169155371/6c91cf31-77fd-4a47-ad84-25e623e13f0a)

**Comment by HX3N** [comment]
I'm not sure if this will solve the problem, but I'll leave the information here

Currently, in YoStarKR, can run MAA using [PlayBridge](https://github.com/ACK72/PlayBridge) on Google Play Beta.

**Comment by Erastia** [comment]
QHD, dpi no
debug.zip link : https://drive.google.com/file/d/1UHnOO8ZdqVyY6zq1sPhSLpDuBl8e98u5/view?usp=sharing
@HX3N thnaks you for me answer

**Comment by Constrat** [comment]
@HX3N 
Wait a minute. This guy made a fucking repo and we never heard of it before?

**Comment by Constrat** [comment]
Also, considering this a bit of a convoluted technique + the repo seems pretty stale, as somehow implementing ADB on something that does not allow it seems a bit of a dream + from the looks of it it's stuck on ADB input (as Minitouch and MAAtouch are all locked out thanks to SELinux, and if there's no ADB, there will never be anyway to get root access and modify /dev/input/..).
Pretty sure this is a wontfix

**Comment by HX3N** [comment]
In the KR community, there are people who say it works fine without any issues.
It might just be a personal problem after all. (~They may not have updated MAA to the latest development version yet~)

**Comment by HX3N** [comment]
It seems that the code has been modified while adding the `MUMU12 screenshot enhancement` feature, leading to the occurrence of this error. It doesn't seem like it will be resolved unless the PlayBridge developer makes the modifications.

Since it worked fine before `version 5.2.3 alpha`, if you intend to use it, please use `version 5.2.3`.

**Comment by HX3N** [comment]
\+ Updated

[PR](https://github.com/ACK72/PlayBridge/pull/2)  addressing the issue has been submitted. Please await the release of the PlayBridge version.

**Comment by ACK72** [comment]
It looks like you filed an issue report in the wrong place.

MAA does not officially support Google Play Games, and PlayBridge is a separate project created to support it.
Therefore, if you are using PlayBridge and experiencing conflicts with MAA, please file an issue report to PlayBridge repo first.

**Comment by ACK72** [comment]
@Constrat

When I created PlayBridge, I didn't tell the MAA team because this is an experimental project.

As you may have noticed if you've played Arknights on Google Play Games Beta, there are some graphical differences between that version and the actual Android version.

Due to the nature of the MAA, which basically works by capturing the screen and recognizing it, I didn't want to inform the MAA team of the additional work that would be required if this project were to be officially covered by the MAA.

Fortunately, aside from a few small issues, it seems to be working well on the Yostar KR server so far.

Supporting other servers shouldn't be too much of a challenge, so if the MAA developers are interested in doing so, please let me know.

Thanks for reading.

**Comment by Constrat** [comment]
Considering how stable Play Games Beta seems to be I think it's definitely worth giving it a try

**Comment by ACK72** [comment]
When I used it, I didn't have any major issues with it, except for a few issues below. Fortunately, everything worked fine.

However,
1. your computer's resolution must meet the 16:9 ratio. This has nothing to do with the resolution of the game within the Google Play Games Beta.

As an aside, and this only needs to be maintained until you launch Google Play Games Beta and Arknights, meaning that as soon as you get to the Arknights login screen, you can change your resolution to something else.

2. You may experience DPI-related issues. If your Windows native resolution scaling is not 100%, you may experience issues as the screen resolution captured by Google Play Games Beta being smaller than what you see.
