### ISSUE TITLE
希望设置里可以多加一些定时

### ISSUE THREAD

**Issue by IAMTERRIFIED** [MaaAssistantArknights/MaaAssistantArknights#9027]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前8个定时，如果多账号做日常一个账号一天登录两遍，那一个maa可以只能做四个号的定时任务，每个定时间隔在3小时。个人感觉效率是不太高的，因为这个间隔完全是可以再放一个甚至是两个定时任务的（平均刷日常一个小时内是可以搞定的）

### 有什么好的想法？

也许可以有一个添加更多定时的选项？

**Comment by Constrat** [comment]
How about using multiple MAAs? You can just copy paste the folder.
