### ISSUE TITLE
日服基建無法辨識塑心

### ISSUE THREAD

**Issue by Godkiller12345** [MaaAssistantArknights/MaaAssistantArknights#9028]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如標題所示， 日版基建在安排塑心進入基建的時候會遇到反覆嘗試識別的問題
我的塑心是用精二立繪

### Version

UI Version: v5.2.4-alpha.1.d036.gcdec1e192
Core Version: v5.2.4-alpha.1.d036.gcdec1e192

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15236382/asst.zip)

[2024-05-07 21:18:20.332][INF][Px61c4][Tx08d8]開始

**Comment by Constrat** [comment]
`ブイルトゥオーサ`

`ヴイルトゥオーサ`

cc @Manicsteiner It doesn't seem that bad, a simple first character regex should do the trick.

**Comment by Manicsteiner** [comment]
[2024-05-07 21:30:34.809][TRC][Px61c4][Tx5e44] asst::WordOcr [{ ヴイルトゥオーサ: [ 0, 0, 117, 13 ], score: 0.929775 }] by OCR Rec , cost 12 ms
[2024-05-07 21:30:34.816][TRC][Px61c4][Tx5e44] Proceed [{ 塑心: [ 3, 4, 117, 13 ], score: 0.929775 }]

It just seems can not be recognized every time. Any oper names starting with [アフワウ] are likely to suffer from similar problems, or simply be missing the first character.
Well, I don't own this operator, I can't give a further test.

**Comment by Constrat** [comment]
Let's not worry too much about this. I'll just regex the first char for now. If more issues arise, we'll investigate :)
`ヴ?イルトゥオーサ` should be enough

**Comment by Constrat** [comment]
(now everything is broken)
