### ISSUE TITLE
maa和网易UU加速器冲突

### ISSUE THREAD

**Issue by kitee11** [MaaAssistantArknights/MaaAssistantArknights#9030]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

maa在挂机过程中如果用加速器加速，会直接断掉并提示连接失败

### Version

慈悲灯塔
5.2.3
5.2.3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15247442/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15247444/gui.log)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/9502b428-a014-4f8a-a84d-4b79191d8445)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/92b55c59-92eb-459e-981c-41ed7e0aa238)
