### ISSUE TITLE
日服 滌火潔西卡 辨識經常出現問題

### ISSUE THREAD

**Issue by Godkiller12345** [MaaAssistantArknights/MaaAssistantArknights#9032]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

同昨天的塑心辨識問題
在基建內辨識滌火潔西卡的時候時常會遇到無法辨識 或 只選取滌火潔西卡

### Version

Resource Version: ツヴィリングトゥルムの黄金
UI Version: v5.2.4-alpha.1.d036.gcdec1e192
Core Version: v5.2.4-alpha.1.d036.gcdec1e192

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15249789/asst.log)
[2024-05-08 21:34:23.398]左右

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/14999036/93d3b2fe-6bc7-48f9-866a-681bdf11d22e)

**Comment by Constrat** [comment]
- First kanji gets completely garbled up
	`燦火ジェシ力`
	`降火ジェシ力`
	`修火ジェシ力`
	`篠火ジェシカ`

**Comment by Constrat** [comment]
Current regex will never be enough.
@Manicsteiner What do you think about just using `滌?ジェシカ` (prettu much like yesterday)
```json
            "[終条冬]火ジェシカ",
            "涤火杰西卡"
```

**Comment by Manicsteiner** [comment]
> @Manicsteiner What do you think about just using `滌?ジェシカ` (pretty much like yesterday), because this would look a bit silly:

`"滌?火ジェシカ"` seems not working. Let me have more tests.
