### ISSUE TITLE
自动战斗选人时因滑到底回弹选错人

### ISSUE THREAD

**Issue by MobiusT** [MaaAssistantArknights/MaaAssistantArknights#9036]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动战斗选人时因为拖到最右侧后有一个回弹动作，导致选人时选到左边干员（作业maa://37349）使用了mumu增强截图
例：maa拖动后截图时尚未回弹（选桃子）
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62053271/443752a9-711e-49e5-bc37-d876669bc036)
回弹后：选中截图的位置导致红豆被选中
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62053271/111b5050-c229-448d-ac90-58de04fdfade)
选小车时同理选中了泡普卡
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/62053271/c039c436-2be8-405b-9c81-a9c556a9175d)

### Version

UI Version: v5.2.4-alpha.1.d036.gcdec1e192
Resource Version: 慈悲灯塔
Core Version: v5.2.4-alpha.1.d036.gcdec1e192

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15252008/asst.log)

**Comment by Manicsteiner** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/212836c466e29462618bff43e096c8d126fd60a7
