### ISSUE TITLE
一键长草-14-20磨难刷理智无法选择代理次数和开始作战

### ISSUE THREAD

**Issue by CliLiore** [MaaAssistantArknights/MaaAssistantArknights#9039]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

刷理智指定14-20磨难关卡时，maa可自行操作至选择14-20磨难关卡，但无法选择代理作战次数并开始作战

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.3
Core Version: v5.2.3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15256376/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15256377/gui.log)
time：2024-05-09 09:02:26.043 ------2024-05-09 09:03:44.350

### 截图

![MuMu12-20240509-091315](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156680254/b6c207d3-7927-4bed-aa76-361ee20d4ef0)
![ea40dfaa04dd36c5ff774294f3ce6d5](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/156680254/001ba4de-27eb-40df-8c64-9a5cb683cc97)

### 还有别的吗？

模拟器：mumu-v3.7.5（2533）
操作系统：
版本	Windows 10 家庭中文版
版本号	22H2
配置：
处理器	13th Gen Intel(R) Core(TM) i7-13700H   2.40 GHz
机带 RAM	16.0 GB (15.6 GB 可用)
GPU       NVIDIA GeForce RTX 4060 Laptop GPU

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/a4c445a7-a997-4961-bc5e-ca30b29fda8e)
14-20识别成1420了，不知道有啥好办法

**Comment by CliLiore** [comment]
佬回得好早，~~你也是早八悲惨大学生吗（悲）~~佬辛苦了

**Comment by ABA2396** [comment]
6c62a8462d0623784ac648f960d05f2273251b87 fixed

**Comment by CliLiore** [comment]
佬好快的fix，瑞斯拜
