### ISSUE TITLE
希望剩余理智栏能和关卡选择一样同步更新今日可选关卡

### ISSUE THREAD

**Issue by Rmeoyanshen** [MaaAssistantArknights/MaaAssistantArknights#9043]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

我使用的是“关卡选择”剿灭一次，“剩余理智”刷材料，但经常由于忘记该日关卡没开而漏刷体力

### 有什么好的想法？

希望“剩余理智”能和“关卡选择”一样同步今日可选关卡或者如果昨日刷的关卡关闭了则“剩余理智”不显示关卡。

### 其他内容

确实下方有今日关卡选择通知。但缺乏一个快速反馈会导致刷完活动关再刷回普通关的时候漏看

**Comment by ABA2396** [comment]
那为什么不用备选关卡）

**Comment by Rmeoyanshen** [comment]
> 那为什么不用备选关卡）

嘶有道理
