### ISSUE TITLE
mac版自动更新存在问题，检查更新会提示v5.2.2是最新版

### ISSUE THREAD

**Issue by hemingyuan** [MaaAssistantArknights/MaaAssistantArknights#9045]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

mac版检查更新会提示v5.2.2是最新版，导致maa不会自动更新到v5.2.3
从官网下载v5.2.3覆盖旧版本依然提示最新版为5.2.2

### Version

macOS通用版v5.2.2

### 日志文件

无

### 截图

![v5.2.2的提示](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/22365305/64a69418-aa96-470a-9dd4-ff302d43585a)
![v5.2.3的提示](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/22365305/b382854d-4d69-45c7-89c3-95c84d8b4c31)

**Comment by ABA2396** [comment]
之前5.2.3文档有问题部署出错了，之后应该没问题了（
