### ISSUE TITLE
干员识别出现错误，百炼嘉维尔未识别

### ISSUE THREAD

**Issue by pKiraChan** [MaaAssistantArknights/MaaAssistantArknights#9046]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

干员识别，未对百炼嘉维尔进行识别

### Version

UI Version: v5.2.4-alpha.1.d036.gcdec1e192
Core Version: v5.2.4-alpha.1.d036.gcdec1e192

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15263409/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15263412/gui.log)
2024年5月9日21时52分附近

### 截图

![2024-05-09_21-52-23-734_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/169372472/389d4f2e-de6a-43df-b124-d06b036d2718)
![QQ截图20240509215621](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/169372472/b4a5a8e4-8a4f-4a75-82a5-8fe003144a2e)

**Comment by Rbqwow** [comment]
所有涉及到干员名识别的场景都不能有特别关注干员
比如自动编队 干员识别

**Comment by Constrat** [comment]
^

**Comment by Constrat** [comment]
We should add a line of text that says: remove all operators from the favourite, before opening an issue.
