### ISSUE TITLE
解压新版之后连接设置有问题

### ISSUE THREAD

**Issue by ability66** [MaaAssistantArknights/MaaAssistantArknights#905]
写的就是之前的adb路径但是连接失败
![image](https://user-images.githubusercontent.com/106503132/174221687-f0e1bcc9-fc4e-4b8c-8aee-247263d091a9.png)
![image](https://user-images.githubusercontent.com/106503132/174221712-adc93b5b-d409-492e-981b-de051f13d618.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8924422/asst.log)

**Comment by MistEO** [comment]
mumu 的 adb 炸了，重启试试

另外不要放中文路径
