### ISSUE TITLE
水月打到2層15步自動放棄，已多次嘗試。以及選項會上下跳不會確認。

### ISSUE THREAD

**Issue by Ponguu** [MaaAssistantArknights/MaaAssistantArknights#9050]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我是這週才開始使用MAA的用戶，昨晚開始掛水月跑了27趟都到2層15步(王關前)就自動放棄，有看到其他人提出一模一樣的問題，但似乎沒有解決方案...
這邊是日服，但請朋友測試了陸服也有一樣的問題。
另外如果在到了王關前，MAA開始沒動作時去點一下編成或查看目前幹員，MAA就不會自動放棄進入王關接著打下去。

還有一個比較常遇到的是進入事件後會在2~3個選項間上下選擇，但都不會按確定。(需要我手動幫他按)

內測、公測、穩定都測試過了都一樣。
以上是比較常遇到的問題，希望可以修復...

### Version

~v5.2.4~
UI Version: v5.2.4-alpha.1.d036.gcdec1e192

### 日志文件

[Desktop.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15266840/Desktop.zip)

從[2024-05-09 02:29:42.278]開始滿大一部分都可以看到在2層15步放棄

### 截图

![1715282813016](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/169396457/e8a41a1b-44a2-41b4-a7e4-79eac6949a43)

**Comment by Ponguu** [comment]
> ### 在提问之前...
> * [x]  我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
> * [x]  我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
> * [x]  我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
> * [x]  我已检查了置顶议题（pinned issue），确认我的问题未被提及
> 
> ### 问题描述
> 我是這週才開始使用MAA的用戶，昨晚開始掛水月跑了27趟都到2層15步(王關前)就自動放棄，有看到其他人提出一模一樣的問題，但似乎沒有解決方案... 這邊是日服，但請朋友測試了陸服也有一樣的問題。 另外如果在到了王關前，MAA開始沒動作時去點一下編成或查看目前幹員，MAA就不會自動放棄進入王關接著打下去。
> 
> 還有一個比較常遇到的是進入事件後會在2~3個選項間上下選擇，但都不會按確定。(需要我手動幫他按)
> 
> 內測、公測、穩定都測試過了都一樣。 以上是比較常遇到的問題，希望可以修復...
> 
> ### Version
> v5.2.4
> 
> ### 日志文件
> [Desktop.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15266840/Desktop.zip)
> 
> 從[2024-05-09 02:29:42.278]開始滿大一部分都可以看到在2層15步放棄
> 
> ### 截图
> ![1715282813016](https://private-user-images.githubusercontent.com/169396457/329363454-e8a41a1b-44a2-41b4-a7e4-79eac6949a43.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyODM1MTQsIm5iZiI6MTcxNTI4MzIxNCwicGF0aCI6Ii8xNjkzOTY0NTcvMzI5MzYzNDU0LWU4YTQxYTFiLTQ0YTItNDFiNC1hN2U0LTc5ZWFjNjk0OWE0My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxOTMzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2ZmNjNlZWU4ZThjYzQ4NmNhYWQxOWI5ZmFhMWVkMmI4ZWJkY2Y5MDc1MTVjODUxNGQzNzRkNzJlZmRkNDFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.52PSm_bfOGUyfeTYLxoemAmhn77DgtsLVgBlPIQBp3I)
> 
> ### 还有别的吗？
> _No response_

另外還有幹員選擇都會從低星開始挑選，有高練度小羊但都會抓低練度阿米婭，還有奶媽有其他更好的選擇卻總是抓白面之類的

**Comment by Constrat** [comment]
cc @Manicsteiner we might be looking at a duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8613, but from what I could translate the issues were ALSO present in the official?

**Comment by Manicsteiner** [comment]
```
[2024-05-09 19:36:54.147][TRC][Px5cc][Tx4568] asst::PipelineAnalyzer::analyze Mizuki@Roguelike@StageEmergencyDps
[2024-05-09 19:36:54.203][TRC][Px5cc][Tx4568] match_templ | Mizuki@Roguelike@StageEmergencyDps.png score: 0.906785 rect: [ 347, 183, 129, 44 ] roi: [ 0, 53, 1280, 554 ]
[2024-05-09 19:36:54.203][TRC][Px5cc][Tx4568] asst::PipelineAnalyzer::analyze Mizuki@Roguelike@StageCombatDps
[2024-05-09 19:36:54.252][TRC][Px5cc][Tx4568] match_templ | Mizuki@Roguelike@StageCombatDps.png score: 0.921031 rect: [ 349, 180, 126, 44 ] roi: [ 0, 53, 1280, 554 ]
```

> 2層15步(王關前)就自動放棄

大概是这里，Mizuki@Roguelike@StageCombatDps OCR得分稍低于要求 0.95

> 另外如果在到了王關前，MAA開始沒動作時去點一下編成或查看目前幹員，MAA就不會自動放棄進入王關接著打下去。

没遇到过，也许是刷新一下界面后提升了Mizuki@Roguelike@StageCombatDps OCR得分

> 進入事件後會在2~3個選項間上下選擇，但都不會按確定。

说明当前没有认出此事件的名称，相应 gui.log 里也不会记录这个事件，如果能指出此事件发生时间可以更好的帮助解决此问题。
已知日服的 サバイバルのプロ/野外生存专家 有概率无法识别， ローカル信号増幅局756号/在地公共信号放大站756号 トリマウンツ旅行社特派団/特里蒙旅行社特派团 ローカル移動局N6号/在地公共移动站N6号 也可能存在此问题，但事件太少见了没有机会检查。

```
[2024-05-09 19:47:47.677] <1><> 事件: 狗眼婆娑
[2024-05-09 19:48:09.275] <1><> 開始戰鬥: 瞻前顾后
```
#8471 一个愚蠢的问题，当前日服 狗眼婆娑-瞻前顾后 作战不可能通过，如果主玩日服，建议自行修改 /resource/roguelike/Mizuki/encounter.json 狗眼婆娑 choose 2

**Comment by Manicsteiner** [comment]
```
[2024-05-10 22:58:10.499][TRC][Px277c][Tx13f8] asst::PipelineAnalyzer::analyze Mizuki@Roguelike@StageEmergencyDps
[2024-05-10 22:58:10.578][TRC][Px277c][Tx13f8] match_templ | Mizuki@Roguelike@StageEmergencyDps.png score: 0.906764 rect: [ 347, 425, 129, 44 ] roi: [ 0, 53, 1280, 554 ]
[2024-05-10 22:58:10.578][TRC][Px277c][Tx13f8] asst::PipelineAnalyzer::analyze Mizuki@Roguelike@StageCombatDps
[2024-05-10 22:58:10.652][TRC][Px277c][Tx13f8] match_templ | Mizuki@Roguelike@StageCombatDps.png score: 0.921083 rect: [ 349, 422, 126, 44 ] roi: [ 0, 53, 1280, 554 ]
```
![2024-05-10_22-58-16-955_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/4860216a-5de0-4b15-9598-220f1a79df6b)
![2024-05-10_22-58-19-808_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/fcacbb0b-95b4-488b-8a38-bb5cf0d183ed)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/d234d5f8-2c65-4e69-876f-fe2f22af5bdf)

[asst.part.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15276569/asst.part.log)

坏消息，这个问题似乎是普遍出现的，大概是最近又调整了这个发光效果，要么重做 StageCombatDps.png，要么尝试调整得分需求，都需要更多测试

**Comment by Constrat** [comment]
Looking at the current scores and templates, changing all scores should be the last option.
Tweaking the templates might the better first step, even though they really all look kind of similar, so increasing to 0.95 all of them. 
Combat: 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/038565b9-f154-49c2-8b38-62eead408362)
Emergency:
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/9e066873-8037-45d9-91f4-6c0a70ed07b4)
Dreadful: 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/b2350b72-b775-4708-8e85-5f95ae709d6c)
Dreadful 5:
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/2b728b01-3417-4274-8a3a-74502d017736)

**Comment by Ponguu** [comment]
所以是因為營運更新的那個發光效果造成MAA認不出他是關卡嗎?
不知道還有沒有機會修復...

另外提一下我上面提到的，遇到BOSS關卡時，在他自動放棄前點選查看目前幹員的地方就會正常繼續打下去，但我的MAA還沒有成功打到結局的BOSS關卡，所以無法確認是不是只要是BOSS關卡MAA都會認不出來。
