### ISSUE TITLE
水月肉鸽打到道中boss时会进入地图预览然后卡住不动

### ISSUE THREAD

**Issue by Squirrel016** [MaaAssistantArknights/MaaAssistantArknights#9053]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

水月肉鸽打到道中boss时会进入地图预览然后卡住不动

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.3
Core Version: v5.2.3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15269115/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15269116/gui.log)

在log的最末尾处

**Comment by Manicsteiner** [comment]
asst.log 是空的，（下次）请上传 asst.bak.log
问题在 #9050 已提及，不过也感谢提供信息，说明这是个所有服务器都可能存在的问题
