### ISSUE TITLE
刷理智模块中循环卡在关卡选择无法进入备选关卡

### ISSUE THREAD

**Issue by zhimian** [MaaAssistantArknights/MaaAssistantArknights#9054]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/20293201/1a983b35-ff7e-4310-b4ed-6a9e4c48e2b7)
刷理智中设置为优先剿灭然后开始备选关卡，但是maa似乎始终在剿灭中循环。
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/20293201/60e6f6dd-1524-4408-9b19-2cead74fe733)
并且该bug没法稳定复现，不稳定出现该bug

### Version

Core Version: v5.2.3
UI Version: v5.2.3

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15270109/asst.zip)
[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15270110/gui.zip)
5/10 早上8点开始

**Comment by ABA2396** [comment]
开始唤醒都失败了，游戏都没进去怎么开始刷理智

**Comment by ABA2396** [comment]
看着日志是启动了游戏但游戏闪退回到桌面了

**Comment by zhimian** [comment]
不好意思刚刚发现了
