### ISSUE TITLE
使用Mumu截图增强模式后，多账号切换出现问题

### ISSUE THREAD

**Issue by SoraRy** [MaaAssistantArknights/MaaAssistantArknights#9056]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用内测版的Mumu截图增强模式后，多账号切换开启时无法进入游戏，已检查关闭增强模式后恢复正常。经排查推测是在点开账号选择的下拉框后，进行了一次下滑（如图所示），因此无法识别位于最上方的账号（当前账号），无法进入游戏。
![{9FFC0747-FF59-445b-8C7B-6CA38C8E4AB4}](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114374770/edc074b4-395d-49ca-9c0d-b8ed65f3e395)

### Version

Core Version: v5.2.4-alpha.1.d036.gcdec1e192

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15270343/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15270357/asst.log)
出现在最新的几行中

### 截图

![{9FFC0747-FF59-445b-8C7B-6CA38C8E4AB4}](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/114374770/139a2367-8a25-45ad-904a-cc217957a522)

### 还有别的吗？

mumu12最新版

**Comment by ABA2396** [comment]
cc @status102

**Comment by status102** [comment]
也许晚点会看看，这个功能优先级较低

**Comment by kpAjun** [comment]
这个大概率还是截图太快，导致打开下拉界面的过渡动画被截图了，系统因为没有找到账号号码（还没加载出来）自动下滑，我这里复现的概率不高不过

**Comment by Rbqwow** [comment]
#9542

修...修了吧 大概(

**Comment by SoraRy** [comment]
> #9542
> 
> 修...修了吧 大概(

更新到最新的内测版试了一下已经修复了！感谢各位～辛苦啦
