### ISSUE TITLE
MAA自动公招无法识别元素标签

### ISSUE THREAD

**Issue by WoolBallLi** [MaaAssistantArknights/MaaAssistantArknights#9059]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA自动公招无法识别元素标签，选择了其他词条而不是停止招募。

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.3
Core Version: v5.2.3

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15273874/debug.zip)
2024年5月10日18点30分

**Comment by WoolBallLi** [comment]
gui.log
[2024-05-10 18:22:31.075] <1><> 公招识别结果: 
医疗干员
先锋干员
治疗
快速复活
元素
[2024-05-10 18:22:31.077] <1><> 4 ★ Tags
[2024-05-10 18:22:31.277] <1><> 选择 Tags：
快速复活
[2024-05-10 18:22:32.109] <1><> 已确认招募
[2024-05-10 18:22:32.391] <1><> 上报失败，放弃上传企鹅物流

**Comment by SherkeyXD** [comment]
fixed in ＃9047
