### ISSUE TITLE
目前公招tag”元素“会锁定新的辅助小车，应该和”支援机械“一样需要手动确认

### ISSUE THREAD

**Issue by BarelyCare** [MaaAssistantArknights/MaaAssistantArknights#9062]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前公招tag”元素“会锁定新的辅助小车，应该认定为一星tag。当”元素“和四星tag同时出现的时候，现版本的MAA会默认点选四星Tag并公招，应该加一个和“支援机械”类似的手动确认勾选框，或者和”支援机械“一样默认需要手动确认。

![元素](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142829752/7b844362-767b-4a24-b903-b1b910ec7b3e)

**Comment by Toby-Shi-cloud** [comment]
duplicate of #8953 
solved by #9047 
不过目前这个修复还没有进入任何发布版，请耐心等待。
