### ISSUE TITLE
maa连接手机，使用maa的切换账号功能失败

### ISSUE THREAD

**Issue by Ninja-Predator** [MaaAssistantArknights/MaaAssistantArknights#9064]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

maa使用adb连接手机，手机分辨率设置为720*1280，在startup任务中设置切换账号为159，maa的操作为：点击账号管理->点下拉框-选择159开头的账号->等待一会->点下拉框（使用模拟器试的话这时候点的是登录，模拟器是没有这个问题的）。
日志文件附在下边了，发生的时间大概是以下两条日志前：
[2024-05-11 15:26:21.756] <1><> 任务出错: StartUp
[2024-05-11 15:32:15.952] <1><> 任务出错: StartUp

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.4-alpha.1.d059.g4dd3f0cba
Core Version: v5.2.4-alpha.1.d059.g4dd3f0cba

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15282019/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15282020/gui.log)

### 截图

这两张是手机上出这个问题的截图
![01](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/67259980/d198b345-d62e-44cf-b028-1157eb0846d7)
![02](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/67259980/cb4dc8dc-4a66-49c9-a600-1290c3043363)

**Comment by Constrat** [comment]
If I remember correctly this was already a problem because of DPI differences between mobile and emulator. Hence the account selector changes size and position making it hard if not impossible to correctly detect the accounts.

**Comment by Ninja-Predator** [comment]
> If I remember correctly this was already a problem because of DPI differences between mobile and emulator. Hence the account selector changes size and position making it hard if not impossible to correctly detect the accounts.

so i can use adb to modify both the DPI and resolution to solve this issue? I'll try that, thanks

**Comment by Constrat** [comment]
That should hopefully help.
If it doesn't will have a closer look.

**Comment by Ninja-Predator** [comment]
> That should hopefully help. If it doesn't will have a closer look.

Making adjustments to DPI and resolution helps to some extent, but the problem is not completely resolved. The DPI of my emulator is set to 320, and the resolution is 1280*720. I also changed the resolution of my phone to 320. At this point, after selecting the account, it no longer opens the drop-down menu, but it still doesn't click the login button.

the log is below. time is here:[2024-05-11 16:15:02.203] <1><> 任务出错: StartUp
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15282148/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15282150/gui.log)

**Comment by Ninja-Predator** [comment]
after i change both resolution and dpi, it stuck at choose the account. i think my settings are not wrong. here is my settings.
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/67259980/182453b3-eb2e-422f-b55f-f00061d0e6bd)
logs are here
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15282189/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15282190/gui.log)
