### ISSUE TITLE
连接成功后无任何操作

### ISSUE THREAD

**Issue by Stargazer020** [MaaAssistantArknights/MaaAssistantArknights#907]
![屏幕截图 2022-06-17 133747](https://user-images.githubusercontent.com/105034454/174232352-8be5e3ad-5aa9-4aa5-a14f-f4a164ef6bf1.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8924800/asst.log)
可以连接到夜神模拟器，但是不会做任何操作
今天突然出现的问题，之前都可以顺利运行

**Comment by MistEO** [comment]
你的分辨率变了，不是 16:9 的

之前可以用的时候
> [2022-06-16 17:12:58.077][TRC][Px4930][Tx4fc0] output: cur=1920x1080

现在
> [2022-06-17 13:34:01.362][TRC][Px4fc0][Tx3b08] output: cur=1920x864
