### ISSUE TITLE
新版本启用连接失败后尝试重启 ADB Server 会使 MAA 意外退出

### ISSUE THREAD

**Issue by xiaofeiTM233** [MaaAssistantArknights/MaaAssistantArknights#9074]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新到新版本后任务无法完成致 MAA 意外退出
~~个人能力问题真的只能写这么不明确的标题了，因为不知道具体原因~~
~~具体情况请看OCR和日志~~

### Version

v5.2.4-alpha.1.d036.gcdec1e192 至最新（v5.3.0-beta.1）
旧版本无问题，仅会因为无法截图而任务出错，而不会关闭MAA

### 日志文件

截取了v5.3.0-beta.1该次运行的日志，此前已执行过一次任务
[asst.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15282934/asst.txt)
[gui.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15282936/gui.txt)
对照版本日志也有留存，需要查看可以提出

### 截图

各事故现场（均可直接拉到视频末尾对照）：

v5.3.0-beta.1 前的几个 Alpha 就发现了问题，Beta 更新后发现仍有此问题，故来提交 issue

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55832499/ab6ed579-0ce2-43ea-9c8a-8e88c874e139

v5.2.4-alpha.1.d036.gcdec1e192 最早复现对照（均为默认设置，开启连接 ADB 失败自动启动模拟器，为节省视频时间调整为等待 20s）：

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55832499/3e826a9d-9cb4-450a-87ef-e767377aa106

v5.2.4-alpha.1.d023.g76b03fdda 理想情况对照（v5.2.4-alpha.1.d036.gcdec1e192 的上一 Alpha 版本，均为默认设置，开启连接 ADB 失败自动启动模拟器，为节省视频时间调整为等待 20s）：

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55832499/36ef99ab-f07e-4a1c-8a99-00e3e6768e2f

**Comment by xiaofeiTM233** [comment]
刚刚看了一下，似乎与`连接失败后尝试重启ADB Server`有关，关闭后就正常了

**Comment by ABA2396** [comment]
看样子应该是和 #8966 有关

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/31f7b026-1f78-494a-ac2b-182564ec87e7)
@MistEO 有给mumu做过什么特殊处理吗？为什么这里connect failed还会继续跑任务）

**Comment by ABA2396** [comment]
说起来触控模式不可用是不是和这个问题比较像，看模拟器启动后还报了个网络连接的问题 #9017

**Comment by xiaofeiTM233** [comment]
不是同个问题吧

**Comment by ABA2396** [comment]
触控模式无效UI会有尝试重启adb的动作，但8966在core加了个wakeup失败尝试一直启动游戏的动作，不知道是不是因为这个有冲突了

**Comment by xiaofeiTM233** [comment]
> 但8966在core加了个wakeup失败尝试一直启动游戏的动作

启动游戏会应该不会导致MAA崩溃的，我看看他写了啥

**Comment by xiaofeiTM233** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/de5dd23b3628ccb848b23b128ab55cebfd7221c4 的版运行会直接弹触控模式不可用，也不知道是不是我的问题
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55832499/c3d16b97-edaa-4b41-806c-d4b4229bb50a)
然后就不会关闭 MAA 了，问题解决

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55832499/00ee8302-3d68-4b0e-a023-01a1d4b5d58a

不知道有没有正常获取到android id，不过这次没有出现截图失败，有待进一步测试
