### ISSUE TITLE
[日服] 水月在「狂徒妄念」事件反覆選擇選項2與選項3, 無法繼續

### ISSUE THREAD

**Issue by Mion354D** [MaaAssistantArknights/MaaAssistantArknights#9075]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

[日服] 水月在「狂徒妄念」事件反覆選擇選項2與選項3, 但不點選任意選項確定, 無法繼續.

### Version

Resource Version: ツヴィリングトゥルムの黄金
UI Version: v5.3.0-beta.1
Core Version: v5.3.0-beta.1

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15283445/debug.zip)

### 截图

![20240512-001531](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/7450570/3771c021-1ece-4f1c-b8c9-adbc5a6f3f02)
![20240512-001543](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/7450570/53098bbf-bc2b-4f5d-ae0c-294d2d0b7e05)

**Comment by Manicsteiner** [comment]
> [2024-05-12 00:14:46.516][TRC][Px5c60][Tx22e0] asst::WordOcr [{ 凶徒の妄幸丸: [ 113, 108, 120, 27 ], score: 0.989275 }, { 空で炎が思うままに燃え盛り、騎士の肩当てに降りかかづてはかすかな: [ 115, 146, 605, 18 ], score: 0.956761 }, { 化していく。騎士は相棒を急き立て、波濤の上を疾駆した。辺りを見渡: [ 116, 172, 605, 17 ], score: 0.991901 }, { だ紺碧ばかリが目に入り、耳元に轟く波の音が止むことはない。麦穂が: [ 115, 196, 606, 21 ], score: 0.977875 }, { >: [ 118, 226, 13, 13 ], score: 0.302606 }] by OCR Pipeline , cost 306 ms

逆天拆字
