### ISSUE TITLE
导航至 14-20磨难 时会卡在选关界面

### ISSUE THREAD

**Issue by Miuzarte** [MaaAssistantArknights/MaaAssistantArknights#9077]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

刷理智导航到 `14-20 磨难` 时候，会在选关界面等待较长的一段时间
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66856838/d4fe564d-898b-4123-a274-0cda4b526209)
****

### Version

Resource Version: 慈悲灯塔
UI Version: v5.2.4-alpha.1.d036.gcdec1e192
Core Version: v5.2.4-alpha.1.d036.gcdec1e192

### 日志文件

11:32:14 ~ 11:43:11

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15285008/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15285009/gui.log)

### 截图

下图是之后截取的，暂时无法复现，希望日志能有帮助
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66856838/c1789d89-35e0-4c88-b7de-5d33798db1da)

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66856838/554a4b15-bf7c-4d4b-9cc4-d41dc82638b3)

**Comment by ABA2396** [comment]
[v5.3.0-beta.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v5.3.0-beta.1) fixed
