### ISSUE TITLE
萨米肉鸽-何处无山海关卡，一直把焰苇往已经有杆子的地块放，一直放不上去然后漏怪到失败

### ISSUE THREAD

**Issue by icevilth** [MaaAssistantArknights/MaaAssistantArknights#9079]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽-何处无山海关卡，一直把焰苇往已经有杆子的地块放，一直放不上去然后漏怪到失败

### Version

UI Version: v5.3.0-beta.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15285299/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15285300/gui.log)

**Comment by HoshinoAyako** [comment]
请重新上传相关的asst.log。你上传的只有短短几行内容，并没有与你描述相关的log内容
