### ISSUE TITLE
夜神模拟器不能正常使用

### ISSUE THREAD

**Issue by GreyMna** [MaaAssistantArknights/MaaAssistantArknights#908]
<!无论怎么开始，最多只能进行两次任务，就会直接弹出或者闪退，后面无法继续使用
![%M~4K8_X_ASW $K ITAZR)8](https://user-images.githubusercontent.com/107677847/174266700-b8a695c7-87e0-41c9-8c66-a30c2b5b957c.png)

**Comment by MistEO** [comment]
请附上日志，谢谢~

**Comment by GreyMna** [comment]
> 请附上日志，谢谢~

直接闪退了，直接没了，截不到图

**Comment by GreyMna** [comment]
> 请附上日志，谢谢~
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8926994/asst.log)

**Comment by GreyMna** [comment]
> 看起来像是资源文件不完整，重新手动下载个完整的包再试试。可能自动更新的解压出问题了

这个重新下载过很多次，都不太行=-= 现在换蓝叠了，好一点了
