### ISSUE TITLE
Workflow: How to do release-nightly-ota?

### ISSUE THREAD

**Issue by HX3N** [MaaAssistantArknights/MaaAssistantArknights#9081]
### The problems you have encountered?

In the recent commit, the `\n` was removed on ko-kr.xaml, resulting in strange-looking output. 
So I have updated the translation, but it has not been incorporated into the current Nightly(Beta) version yet.

Thus, I wish to release the updated YoStarKR translation as a nightly version but am uncertain how to proceed.
I ask questions to prevent any potential issues from incorrect methods.

I understand that both the `Release note` and `Commit to build (git checkout)` can be either left blank or filled out—correct?

Should I keep the `Number of releases to fetch from MaaAssistantArknights` and `Number of releases to fetch from MaaRelease` at the default value of `30`, or should I specify a different number?

**Comment by ABA2396** [comment]
just
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/9cde3bbf-f6ea-4223-b72f-19353a72a5b6)

**Comment by HX3N** [comment]
Ah, it looks like there's nothing to edit. Thank you.
