### ISSUE TITLE
剩余理智显示改进

### ISSUE THREAD

**Issue by FOX0601** [MaaAssistantArknights/MaaAssistantArknights#9084]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

现版本剩余理智显示一点难以理解

### 有什么好的想法？

将当前剩余理智一行显示在下一次行动之前，方便用户的阅读与理解

**Comment by status102** [comment]
以前是分开的

```
hh:ss 当前理智 99/135
hh:ss 已开始行动 20 次
```

后来考虑到行间距和信息量进行合并，就放一起了。

已开始行动作为主要信息放在第一行，理智、吃药、碎石次数作为辅助信息放在第二行（实际上都是可有可无，对于机器来说

暂不考虑进行调换

而且开始战斗后是看不见理智信息的，能看到理智的时候只有进本前
