### ISSUE TITLE
Thorns Elite 1 in Sami is set to use Skill 2, but in Phantom it is set to use Skill 1. 

### ISSUE THREAD

**Issue by minhlong94** [MaaAssistantArknights/MaaAssistantArknights#9086]
### The problems you have encountered?

Thorns skill priority in Phantom: https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/e36b1855056baa5e9f008157b23b0d323dd340e0/resource/roguelike/Phantom/recruitment.json#L10

In Sami: https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/e36b1855056baa5e9f008157b23b0d323dd340e0/resource/roguelike/Sami/recruitment.json#L332

I wonder why it is the case? Preferably I would like Throns in Sami to also use Skill 1

**Comment by Constrat** [comment]
cc @Lancarus

**Comment by Lancarus** [comment]
> cc @Lancarus

Sadly, Throns is too weak to be starting operator in Sami. No matter he use Skill 1,2,or3. I suggest to use Reed the flame shadow in Sami for starting.
