### ISSUE TITLE
基建相关功能提议

### ISSUE THREAD

**Issue by LiuLiHuaYue** [MaaAssistantArknights/MaaAssistantArknights#9087]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

“刷理智”高级设置的剩余理智处理方法中没有设计加速基建无人机的选项，觉得可以加一个
另，由于刷理智和基建换班这两个功能使用耗时较长，若基建换班放在刷理智之前，可能刷完理智之后又有一堆基建设施需要进行操作了；若基建换班放在刷理智之后，每次启动时又不能及时很好利用基建系统，容易浪费了刷理智的时间。建议可以设置两个基建换班的功能，自由放置选择

**Comment by ntgmc** [comment]
刷理智一天最多半小时吧，基建又要换班？
