### ISSUE TITLE
mumu截图增强功能是否支持mumu明日方舟专版

### ISSUE THREAD

**Issue by El-Dong** [MaaAssistantArknights/MaaAssistantArknights#9088]
### 说说你遇到的问题？

mumu截图增强功能是否支持mumu明日方舟专版
将路径设置为专版安装路径识别失败
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/81756207/db142eac-637e-490e-ba03-4efbff4da675)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/81756207/042e1f23-fb05-4a2d-a531-804f5f71f0fb)

**Comment by ABA2396** [comment]
按mumu的说法最新的专版是可以的
