### ISSUE TITLE
肉鸽模式里锏的三技能问题

### ISSUE THREAD

**Issue by KJOY0314** [MaaAssistantArknights/MaaAssistantArknights#9089]
### 说说你遇到的问题？

只要她的三技能转好了，maa就会自动不断反复尝试触发她，会浪费非常非常多的时间，直到附近有人出现在技能范围里才能释放出来。然后再转好了就又会重复这个过程。

**Comment by HoshinoAyako** [comment]
建议参考文档 - 肉鸽辅助协议，手动调整锏的携带技能。
