### ISSUE TITLE
新测试版v3.9.8-fix的问题

### ISSUE THREAD

**Issue by GreyMna** [MaaAssistantArknights/MaaAssistantArknights#909]
会经常卡在开不了技能图标的干员身上（例如蓝毒一技能），导致子弹时间会浪费特别多的时间
![}4TEUKC7D0(P~LNSXLEG6_2](https://user-images.githubusercontent.com/107677847/174267351-8104cec3-3de8-49d2-b455-f20deff3467d.png)

**Comment by MistEO** [comment]
请附上日志，谢谢~

**Comment by GreyMna** [comment]
> 请附上日志，谢谢~
进程是正常的，就是卡在这个技能过程不动，一般不都是点完技能会自动回到战斗中么，这个就好像点了一下技能但回不到正常作战中了

**Comment by MistEO** [comment]
提 bug 的时候这个提示应该很明显了，请不要忽略无视

![image](https://user-images.githubusercontent.com/18511905/174288396-8f7f15d8-9e2b-464e-a2ad-456076da1d65.png)

**Comment by GreyMna** [comment]
> 提 bug 的时候这个提示应该很明显了，请不要忽略无视
> 
> ![图像](https://user-images.githubusercontent.com/18511905/174288396-8f7f15d8-9e2b-464e-a2ad-456076da1d65.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8926984/asst.log)
抱歉。。我没看清楚这些

**Comment by GreyMna** [comment]
有时候还会出现识别地图错误
![UBT@0 Y_TF0U``F7MEOWS](https://user-images.githubusercontent.com/107677847/174289932-6ca60f18-4bc7-4b44-920b-68dbe893ec44.png)
![O `L0P5C11C HPXNKS3NU1](https://user-images.githubusercontent.com/107677847/174289943-5d0e0c64-5785-4696-ab8e-cf76af41146a.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8927034/asst.log)
