### ISSUE TITLE
傀影肉鸽三个BUG

### ISSUE THREAD

**Issue by dzy199806** [MaaAssistantArknights/MaaAssistantArknights#9090]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

1.选完分队选完角色后进入第一层后，初始画面不在路线最左边，导致无法识别到第一个作战关卡，从而重复开始退出肉鸽
可开局补充一步左划操作后开始识别(附图1)
2.手动划动后正常开始，但会在识别不到可选节点的位置结束肉鸽而不是左划识别(附图3)，并且结束后会停止在“the end”画面不继续(附图2)

### Version

v5.2.3

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15287004/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15287005/asst.log)

### 截图

![2024-05-13_00-22-04-194_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/33895444/9ba7f48f-1161-4aa2-9d5b-a833a990951a)
![2024-05-13_00-15-29-014_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/33895444/f3518351-4bf9-42a8-bd71-b1ae4243c418)
![2024-05-13_00-13-09-403_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/33895444/f4539df3-9a64-4907-b369-3cffeb379909)

**Comment by dzy199806** [comment]
新：重启MAA和模拟器后第一把暂时没有开局BUG

**Comment by Constrat** [comment]
This is a bug of Arknights. It's a known issue, but it's a wontfix
