### ISSUE TITLE
进入14章识别关卡时，会从14-1开始向右划动，到14-10左右便开始往回划动，识别不到14-10往后的关卡，导致刷理智失败

### ISSUE THREAD

**Issue by John95465** [MaaAssistantArknights/MaaAssistantArknights#9091]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

进入14章识别关卡时，会从14-1开始向右划动，到14-10左右便开始往回划动，识别不到14-10往后的关卡，导致刷理智失败

### Version

Core Version: v5.3.0-beta.1.d005.g16036b1b5

### 日志文件

.

**Comment by ABA2396** [comment]
.
