### ISSUE TITLE
mumu截图增强功能专版和官网版均无法识别模拟器路径

### ISSUE THREAD

**Issue by CatoSicarius0** [MaaAssistantArknights/MaaAssistantArknights#9094]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

mumu截图增强功能专版和官网版均无法识别模拟器路径，其他功能都能正常使用，未开启挂机保活

### Version

Resource Version: 慈悲灯塔
UI Version: v5.3.0-beta.1.d005.g16036b1b5
Core Version: v5.3.0-beta.1.d005.g16036b1b5

### 日志文件

拖到最后就能看到
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15287769/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15287770/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/169619541/5e98cb2b-d1a8-462e-9eb6-c811d7219c5f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/169619541/a52e1770-c2bc-40d5-af09-f5dd308d93ba)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/169619541/880fc0f5-d724-4774-bb30-0772c40554fd)

**Comment by yagol2020** [comment]
mumu安装路径好像是一个文件夹？比如你这个应该是`"E\Netease\MuMu Player12\"`，好像有提示文字

**Comment by ABA2396** [comment]
点开选项的时候有弹窗提示
