### ISSUE TITLE
Mumu截图增强功能会导致公招时出现识别错误问题

### ISSUE THREAD

**Issue by liyu-kun** [MaaAssistantArknights/MaaAssistantArknights#9095]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在打开Mumu截图增强功能后，截图速率提高到了100ms以内（好像是20到30ms之间吧，记不清楚了），此时会导致公招时出现“识别错误”问题，推测是由于确认招募后在淡出动画未结束前直接进行了下一个公招栏位的点击操作，游戏没有响应此次点击导致。
![QQ图片20240513074409](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/13912598/6cdc65ae-a9cd-463f-b2af-24adf815fa09)

### Version

Resource Version: 慈悲灯塔
UI Version: v5.3.0-beta.1
Core Version: v5.3.0-beta.1

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15287975/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15287976/asst.log)

**Comment by Notofnice** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63146701/a552226d-2db3-4753-be08-e61ea323b452)
遇到同样的情况,开启MUMU12截图增强功能导致点击过快,没有招募成功,在这卡循环了

**Comment by Rbqwow** [comment]
前几个版本应该就修完了一直没关 先关了 复现再开
