### ISSUE TITLE
希望能给萨米肉鸽加一个刷隐藏坍缩的功能

### ISSUE THREAD

**Issue by ChenParsifal** [MaaAssistantArknights/MaaAssistantArknights#9097]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

这玩意手刷属实太精污了，和水月的指路鳞异曲同工了属于是。

### 有什么好的想法？

选指挥分队，至少难度3开，检测到剩只剩最后一个敌人的情况下撤退全部干员，快速在第一层刷出一个坍缩。
看一眼是不是隐藏坍缩，如果是的话就停止肉鸽（后续转手动以确保可以拿到二级坍缩）。不是的话直接重开。
两种坍缩最好能分开勾选，避免重复刷已经收集过的。

**Comment by Saratoga-Official** [comment]
#9172 已增加
