### ISSUE TITLE
刷理智-关卡选择功能不会进行难度切换

### ISSUE THREAD

**Issue by DemiurgeZ** [MaaAssistantArknights/MaaAssistantArknights#9100]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

刷理智-关卡选择-选择“14-16标准”，若此时难度设置为磨难，MAA刷本前不会检查、切换到标准难度，而是直接打磨难难度的关卡

### Version

Resource Version: 慈悲灯塔
UI Version: v5.3.0-beta.1
Core Version: v5.3.0-beta.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15291857/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15291859/gui.log)

### 截图

![2024-05-13 162226](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/44410173/8c2380c8-02ef-4239-97c4-f4def6e910bd)

**Comment by ABA2396** [comment]
link #9101
