### ISSUE TITLE
自动战斗关卡难度选择错误

### ISSUE THREAD

**Issue by StarWC** [MaaAssistantArknights/MaaAssistantArknights#9101]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如图1所示，我退出时停留在磨难难度，并在MAA中选择了刷14-16普通，但MAA最终选择的还是磨难难度，反过来如果选择磨难难度，则MAA会自动在左下角切换难度

### Version

Resource Version: 慈悲灯塔
UI Version: v5.3.0-beta.1
Core Version: v5.3.0-beta.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15291872/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15291873/gui.log)
发生时间在5月13日16:50附近

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49085785/fb3f2845-2501-4e84-966a-813547328209)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49085785/d5bc511a-a956-4e2a-a610-b4dcc895c18a)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49085785/6eb90a9a-f787-4e7c-9997-596df50dc705)

### 还有别的吗？

基础信息
UUID :  862b246b-63ee-4710-b54a-acfb424be60b
模拟器版本 :  3.8.21.2869
模拟器磁盘（可用/总）空间 :  97.4GB/126GB
日志路径 :  G:\Program Files\MuMu\emulator\MuMuPlayer-12.0\vms\MuMuPlayer-12.0-0\logs\

运行环境
VT :  开启
Hyper-V :  关闭
网络环境检测 :  正常
以管理员运行方式 :  是
DirectX 11是否安装 :  是
防火墙 :  关闭

电脑配置
主板型号 :  Manufacturer: Maxsun  Product: MS-Terminator B660M
CPU :  12th Gen Intel(R) Core(TM) i5-12490F
系统版本 :  Windows 11 64-bit Kernel 10.0.22631
显卡驱动 :  正常
显卡驱动型号 :  552.22 (20240411)
所有显卡 :  NVIDIA GeForce RTX 2080  |  Microsoft Basic Render Driver
当前使用显卡 :  NVIDIA GeForce RTX 2080
安装磁盘(可用/总)空间 :  271.7GB/894.2GB
可用内存/总内存 :  15.5GB/31.8GB

模拟器设置
Root :  关闭
显卡渲染模式 :  Vulkan 模式（独家）
性能设置 :  6核/12GB
手机型号 :  vivo IQOO Neo 7SE
分辨率 :  1920 * 1080
高帧率 :  开启
后台保活 :  开启

连接设备
音频输入 :  已连接
音频输出 :  已连接

网络信息
MuMu DNS :  223.5.5.5
电脑DNS :  223.5.5.5
Rom MAC地址 :  08:f0:81:90:20:00

ADB调试端口 :  16384
MuMu出口IP地址 :  10.0.2.15
电脑出口IP地址 :  113.214.242.29

其它信息
其它版本信息 :  vm: 120.1.62.002 hyperv: 6.3.17.0 renderer: 0.0.171.0
Vendor :  NetEase
OpenGL Renderer :  MuMu GL (Vulkan 1.3.277 NVIDIA GeForce RTX 2080 552.22 _A_)
OpenGL Version :  OpenGL ES 3.2 V132
运行时间 :  0 : 24 : 9

**Comment by ABA2396** [comment]
@AnnAngela 普通难度后面要加-NORMAL

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaRelease/commit/4b4720df3a469344aa42e8ef2cee75cd27fa9ff7 fixed，过两分钟重启maa就好了
