### ISSUE TITLE
mumu12 模拟器无法最小化

### ISSUE THREAD

**Issue by lanzhendong** [MaaAssistantArknights/MaaAssistantArknights#9105]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在maa启动设置中勾选了最小化启动模拟器，但还是会自动弹出模拟器，已使用管理员模拟打开MAA
![Snipaste_2024-05-14_13-25-04](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/123225602/08bf5c47-a873-457f-b4f9-7f495b88ec8a)

### Version

UI Version: v5.3.0-beta.1.d005.g16036b1b5
Core Version: v5.3.0-beta.1.d005.g16036b1b5

### 日志文件

日志时间：2024.5.14
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15303155/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15303156/gui.log)

**Comment by lanzhendong** [comment]
使用的是mumu模拟器12的最新版本：
![Snipaste_2024-05-14_13-32-29](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/123225602/5a813b2e-d34d-420e-afa6-e569dd187630)

**Comment by ABA2396** [comment]
mumu的启动分成了两段，这样写的话会最小化启动读条的窗口，但mumu在启动之后还是会弹出窗口
我去和mumu那边沟通下，看看能不能解决
