### ISSUE TITLE
似乎最近不能自动访问好友来获取信用

### ISSUE THREAD

**Issue by Nanyuting** [MaaAssistantArknights/MaaAssistantArknights#9106]
### 说说你遇到的问题？

![QQ图片20240514144836](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/112244407/71eec9e0-6a5c-43e9-a6fb-00c73f089763)
如图，设置是默认访问好友的。但是实际是没有访问的。
![QQ图片20240514144942](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/112244407/1548db11-e8b7-45e5-a76f-3266efc30412)
这是我手工访问的，可知MAA没有访问。请问是我的设置哪里有问题吗？

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/69eeff19-1c9a-4034-9817-acf41d11f57a)
不更新是这样的

**Comment by jckuangren** [comment]
我这边是一直不行，更新到v5.2.3了也一样，看了下提bug的那个后就把排第一用“健将”主题的好友删了，又行了，感觉没修好

**Comment by ABA2396** [comment]
> 我这边是一直不行，更新到v5.2.3了也一样，看了下提bug的那个后就把排第一用“健将”主题的好友删了，又行了，感觉没修好

健将那个是新加的，5.2.3还没有。
