### ISSUE TITLE
日服）湮灭之相识别错误

### ISSUE THREAD

**Issue by Amahokori** [MaaAssistantArknights/MaaAssistantArknights#9110]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![スクリーンショット 2024-05-14 230057](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/117272747/d57bd9d8-5b5b-4aeb-892f-8ee243017671)
![スクリーンショット 2024-05-14 230326](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/117272747/e4a4d008-6d04-4c6e-95a2-947ebdd2d409)

似乎是文字设别错误导致avatars文件夹内不能创建缓存，不能正确下干员抄作业。

### Version

Core Version: v5.3.0-beta.1.d005.g16036b1b5

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15309565/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15309567/asst.log)

**Comment by GlycosidEMT** [comment]
如果你進到\resource\global\YoStarJP\resource\tasks.json的地方 裡面找到湮滅之相 把湮改成".?"就能識別到且能順利運行作業。
個人測試的方法，僅供參考。一切以開發大佬的為最終標準。
![messageImage_1715700733023](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/168992786/dd394455-6d7f-4ab9-b9ac-4858628451e0)

**Comment by Amahokori** [comment]
感谢，已经成功！
