### ISSUE TITLE
在自动肉鸽中异格W的技能在手动取消可以释放后会立刻手动取消

### ISSUE THREAD

**Issue by Tashar0472** [MaaAssistantArknights/MaaAssistantArknights#9113]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

发现在水月肉鸽1级难度第四层那个有庞贝的关里，不确定其他手动确认关闭的技能是否也有这个问题

### Version

Core Version: v5.3.0-beta.1.d005.g16036b1b5

### 日志文件

00：:30的那个作战
[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15311575/debug.zip)

### 还有别的吗？

蓝叠模拟器国际版

**Comment by R0Bill** [comment]
mumu模拟器，core:5.3.0-beta.2。肉鸽自动作战异w无论如何都是开了3技能设一炮立马取消

**Comment by ABA2396** [comment]
截图太快了，点了之后技能开出来有延迟，第二张图已经截进去了，以为技能还没开就又点了一次，感觉两次开技能之间应该加个默认延迟

**Comment by Rbqwow** [comment]
前几个版本就修了 一直没关(

**Comment by R0Bill** [comment]
> 繁中服目前出現了上述的問題，使用異W掛薩米肉鴿時，技能打一砲就關閉了。版本是5.14.1。

这是一个已关闭的issue，常规情况下不会有开发者关注，如有需要请新开一个issue。
