### ISSUE TITLE
开始唤醒后无法进行公招识别

### ISSUE THREAD

**Issue by maderzhi** [MaaAssistantArknights/MaaAssistantArknights#9117]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

开始唤醒后会一直停在公招界面，没有报错没有其他反应

### Version

Resource Version: 慈悲灯塔
UI Version: v5.3.0-beta.1
Core Version: v5.3.0-beta.1

### 日志文件

[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15317126/asst.zip)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15317127/gui.log)

### 截图

![QQ截图20240515142828](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49891085/b7d7005f-b436-45b4-a1b2-8e2af905cf32)

### 还有别的吗？

使用的模拟器为mumu12，并且开了截图增强功能

**Comment by zhengpip** [comment]
试试mumu模拟器设置中关闭“后台挂机时保活运行”
<img width="669" alt="image" src="https://github.com/user-attachments/assets/b089eb40-0d1b-4a51-b972-813abbce20fa">

**Comment by Saratoga-Official** [comment]
看log能看出来ocr一直在识别专享活动四个字，这四个字应该不是游戏里的，大概率没关后台保活导致的
