### ISSUE TITLE
JP Client cannot detect Virtuosa during custom infra

### ISSUE THREAD

**Issue by marihuana69** [MaaAssistantArknights/MaaAssistantArknights#9120]
### The problems you have encountered?

Based on asst.log, the ocr keeps detecting ヴィルトゥオーサ as ヴイルトゥオーサ,ブイルトゥオーサ,ブイルトウオーサ etc

I want to change the task.json file so that it compensates for the ocr problem, however I don't know how the grammar works for [] and .* in this file.
I have currently written "[ヴブワウフ][イィ]ルト[ワウフゥ]オーサ", would this work properly?

**Comment by ABA2396** [comment]
Japanese has a special treatment, some are treated as the same word to judge, see details `\resource\global\YoStarJP\resource\ocr_config.json`, a bracketed are treated as equivalent.

maa uses std::regex regular matching, you can search for the detailed syntax yourself

**Comment by ABA2396** [comment]
cc @Manicsteiner

**Comment by Manicsteiner** [comment]
seems already fixed in #9068
