### ISSUE TITLE
定制基础设施（beta）使用过程中，偶尔会出现宿舍空置的情况。

### ISSUE THREAD

**Issue by js1004b** [MaaAssistantArknights/MaaAssistantArknights#9129]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

因为使用了翻译器，所以可能会有不顺畅的部分。 请谅解。

以前也有过一个宿舍空着的情况，误以为是定制基础设施json的错误，修改了文件。 但是这次发生了其他宿舍空着的情况，怀疑这是不是maa的问题，所以写了这篇文章。除设施名称Dorm1外，所有布局区域均处于布局完成状态。事件发生的时间估计为2024-05-1716:04:04至16:04:30，尚不确定。如果要推测出现问题的原因，则推测是选择操作员后在对准和初始化过程中出现了问题。据推测，在按下确认按钮之前，在执行确认操作员是否正确选择的过程的过程中，如果操作员没有选择，处于对齐状态，则会发生直接按下确认按钮的情况，从而产生错误。准确的是要确认日志才能知道的事实，所以就推测到这里吧。 因为是偶尔发生的现象，所以不太在意，但因为是自动驾驶基础设施，所以有点麻烦。

还有什么需要告诉我的，请告诉我。 我会尽力配合的。

### Version

Resource Version: 츠빌링슈튀르메의 가을 UI Version: v5.2.3 Core Version: v5.2.3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15345463/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15345482/gui.log)

### 还有别的吗？

使用的模拟器: BlueStacks App Player 4
操作系统: Windows 11 Home

**Comment by ABA2396** [comment]
在高级设置里把dorm调到最后面，在换班结束之后再安排宿舍

**Comment by js1004b** [comment]
https://ark.yituliu.cn/tools/schedule
id: 1715899039854995

我在maa高级设置中选择了住宿选项。 此外，json文件中住宿设置没有空。操作员的状态极限是100%。
闲聊、整理宿舍优先的理由是,这段时间所有的轮班工作结束后,偶尔会有宿舍的空位,所以变更了一次。 但是最后让我整理宿舍的话，我会重新修复的。

首先，我按照你说的更改了宿舍的执行位置，但如果再次出现问题，我会重新上传日志。
