### ISSUE TITLE
控制中枢基建换班红隼问题

### ISSUE THREAD

**Issue by hisseulgi** [MaaAssistantArknights/MaaAssistantArknights#9134]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

排班干员为红隼、暴雨、清道夫、阿米娅
自动换班时始终只能自动识别到暴雨、清道夫、阿米娅，多次尝试后自动变更为红隼单人或无人入驻

### Version

Resource Version: 罗德岛促融共竞
UI Version: v5.3.0-beta.2
Core Version: v5.3.0-beta.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15358987/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15358988/gui.log)
2024-05-18 08:04:19 开始

### 截图

![微信截图_20240518080550](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121664042/900ad719-31a2-4532-aca8-03c9e71677cc)

**Comment by singlelove** [comment]
我也是控制中枢红隼始终无法正常被放入，还有一个宴始终无法放入宿舍，永远都是这两个人，没出现过别人，换成别人就都正常。

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/ff7cfd38-96fc-4156-b268-e87701b635ef)
红隼被识别成红了，这玩意还不好改，因为真的有红）

**Comment by hisseulgi** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/336354201-ff7cfd38-96fc-4156-b268-e87701b635ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NTMxOTAsIm5iZiI6MTcxNzU1Mjg5MCwicGF0aCI6Ii85OTA3Mjk3NS8zMzYzNTQyMDEtZmY3Y2ZkMzgtOTZmYy00MTU2LWIyNjgtZTg3NzAxYjYzNWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDAyMDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YWQwNWZiNWVhMzFkZGU4MDVjMTU1OTE0OGFmZGNhYTI4ZDNjMmZkYWIxMWIzZGNiZGFlYWE0ZDRlN2Y4ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YOPaMYikwAZmkcZ0PLLs5fdlwS5CDrIOVob2kBVGC24) 红隼被识别成红了，这玩意还不好改，因为真的有红）

是因为隼是偏僻字？红豆不会出问题，阿米娅和阿也没问题
