### ISSUE TITLE
建议：手动输入关卡名时确保进行标准而非磨难作战

### ISSUE THREAD

**Issue by oiketes** [MaaAssistantArknights/MaaAssistantArknights#9136]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

勾选手动输入关卡名选项时，输入关卡名13-18，执行时进入的是磨难险地环境，Maa未确认是标准作战就开始代理，导致连续65次NotThreeStars.

### 有什么好的想法？

勾选手动输入关卡名时，在选择10到14章且未添加-HARD后缀时，可以在进入关卡前增加一个选择标准作战的操作。

**Comment by ABA2396** [comment]
普通加-NORMAL，不加就是进默认
