### ISSUE TITLE
在萨米肉鸽中抗干扰指数不足时选择纵向通路时会卡死

### ISSUE THREAD

**Issue by molingAwA** [MaaAssistantArknights/MaaAssistantArknights#9140]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题

### Version

Resource Version: 罗德岛促融共竞
UI Version: v5.3.0-beta.2
Core Version: v5.3.0-beta.2

### 日志文件

[新建文本文档.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15362924/default.txt)

**Comment by Lancarus** [comment]
fix in #9223
