### ISSUE TITLE
自动公招-指定3星tag公招系统无法识别重装干员tag

### ISSUE THREAD

**Issue by star-ocean** [MaaAssistantArknights/MaaAssistantArknights#9141]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

指定tag公招无法识别重装干员词条，在有重装词条的时候会随机选择词条确认。
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12841566/98e82129-b1b7-49a1-96d5-3fb663a04d8b)

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12841566/389319a7-11aa-4c19-920b-efbbe33800ad)

### Version

Resource Version: 罗德岛促融共竞
UI Version: v5.3.0-beta.2
Core Version: v5.3.0-beta.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15362945/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15362946/gui.log)
2024:05:18 18:30:50
2024:05:18 19:12:19

### 截图

![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12841566/98e82129-b1b7-49a1-96d5-3fb663a04d8b)
![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12841566/389319a7-11aa-4c19-920b-efbbe33800ad)
![QQ图片20240518191835](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12841566/59ec7ef3-5b59-4127-b829-568c4c712518)
![QQ图片20240518191844](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12841566/1f54f566-ddae-4378-bfd0-57ff7d6dd734)
![QQ图片20240518191848](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12841566/9c18016a-282d-486e-aed7-83fd14dd334a)

**Comment by star-ocean** [comment]
更正：主楼图片附件有误，未能表述具体填入的tag信息，补图：
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12841566/98e82129-b1b7-49a1-96d5-3fb663a04d8b)

![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/12841566/389319a7-11aa-4c19-920b-efbbe33800ad)

**Comment by Constrat** [comment]
You can edit the main issue post, for easier understaing please.
