### ISSUE TITLE
截图增强模式：维什戴尔肉鸽技能秒关

### ISSUE THREAD

**Issue by insine-inverse** [MaaAssistantArknights/MaaAssistantArknights#9143]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

维什戴尔在傀影肉鸽有概率3技能秒开秒关，特别是前两层的时候发现这个现象……

### Version

Resource Version: 罗德岛促融共竞
UI Version: v5.3.0-beta.2
Core Version: v5.3.0-beta.2

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15365425/debug.zip)

**Comment by yagol2020** [comment]
+1，在抄作业（自动战斗）的时候也有这种情况

**Comment by C1rno9** [comment]
同上

**Comment by y2293456** [comment]
同上 + 1

**Comment by ABA2396** [comment]
67cb180ba8f624217a5575f258eda3e424756c84 fixed 
大概有用）
