### ISSUE TITLE
傀影肉鸽无法进图

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#9144]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如视频所示
[video.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15365736/video.zip)

### Version

Resource Version: 罗德岛促融共竞
UI Version: v5.3.0-beta.2
Core Version: v5.3.0-beta.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15365735/asst.log)

### 截图

![268f601a01378f9f9b5f8420bf088634](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/9c3e059c-75cc-40a1-bcb8-02d2e8ed2ad8)

### 还有别的吗？

反馈来源QQ：2897095546

**Comment by ntgmc** [comment]
补充一例萨米的
[gui.log](https://github.com/user-attachments/files/15517317/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/15517318/asst.bak.log)

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/f89b320e-c885-4574-8637-bfe95d80020e

**Comment by ImYiFeng** [comment]
我遇到了同款问题，应该是识别不到关卡位置所以取消了，也不知道是啥原因

**Comment by SymmFz** [comment]
> 我遇到了同款问题，应该是识别不到关卡位置所以取消了，也不知道是啥原因

更新到 MAA 最新公测版后萨米的问题解决了

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9214#issuecomment-2156510651
