### ISSUE TITLE
增加看完当前录像再一键长草的功能

### ISSUE THREAD

**Issue by inxinxinx** [MaaAssistantArknights/MaaAssistantArknights#9147]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

有时候想单独用某一关去清一下体力，懒得在刷理智里面去找某个关卡或者掉落物，手动挂了连续几次的录像，这时候如果我想挂完录像再用maa一键长草（宿舍、公招、尤其是挂肉鸽）的话，就要等看完录像再点maa的link start，对于晚上困了或者有别的事的情况不太友好。

### 有什么好的想法？

在link start边上加一个勾选框（或者类似各个功能设置的子界面），对应的功能就是：连接到模拟器后，等完成当前录像后（判断一下结算界面？录像乱轴就直接结束）再执行一键长草。

**Comment by ntgmc** [comment]
刷理智-高级设置-手动输入关卡名，比如你要刷14-17（标准）直接输入14-17，要刷14-17（磨难）直接输入14-17-Hard
