### ISSUE TITLE
肉鸽新关卡无法识别

### ISSUE THREAD

**Issue by GEOMETRYH** [MaaAssistantArknights/MaaAssistantArknights#915]
肉鸽更新后的新关卡“死斗”无法识别
进入关卡之后不会进行任何操作
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8932913/asst.zip)
![Screenshot_20220617-204335](https://user-images.githubusercontent.com/80257514/174422371-aec50908-796c-41a0-b947-a01ed3fe1187.png)
![Screenshot_20220617-204422](https://user-images.githubusercontent.com/80257514/174422373-210176d7-28d7-46e6-9d76-e76b4dcbb73a.png)

**Comment by MistEO** [comment]
最新测试版改过了，试试看
