### ISSUE TITLE
v5.2.3 公招识别错误

### ISSUE THREAD

**Issue by w200090** [MaaAssistantArknights/MaaAssistantArknights#9150]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

公招无招聘许可，但是显示已确认招募，重试多次后显示识别失败。

### Version

v5.2.3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15367244/asst.log)

时间：2024-05-19T09:05

### 截图

![屏幕截图 2024-05-19 090559](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/88914104/dd3d1bcf-1079-4606-b183-aa6e72a505c7)

**Comment by ji-zhe** [comment]
同

**Comment by ABA2396** [comment]
公招无招聘许可一直都是报错返回的吧

**Comment by w200090** [comment]
> 公招无招聘许可一直都是报错返回的吧

不是的，之前会提示无招聘许可，不是爆红

**Comment by yqf0625** [comment]
同

**Comment by horror-proton** [comment]
> 公招无招聘许可一直都是报错返回的吧

好像是有个识别的, 但是现在龙门币没了可能 roi 位置就错了 (
