### ISSUE TITLE
萨米肉鸽树篱之途反复选取

### ISSUE THREAD

**Issue by mk84698361** [MaaAssistantArknights/MaaAssistantArknights#9152]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

挂了一个晚上，早上打开电脑屏幕发现MMA在反复选择树篱之途，可能是想进去，但是抗干扰指数不够了，于是又不给进，
就不停重复 选择树篱之途-出现提示询问是否使用抗干扰-抗干扰不够只能选取消-又选树篱之途 重复循环

### Version

UI Version: v5.0.0

### 日志文件

早上打开屏幕的事件约为11:19，那个时候就已经开始重复选取了，
至于具体发生的时间就不知道了，因为我在睡觉。
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15367456/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15367457/gui.log)

**Comment by ABA2396** [comment]
修了你也没更新啊

**Comment by coburnsith** [comment]
核心版本v5.3.0依然存在这个问题
