### ISSUE TITLE
截图为Encode时开始唤醒时卡在主界面

### ISSUE THREAD

**Issue by YiyangWilliam** [MaaAssistantArknights/MaaAssistantArknights#9157]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用powershell管理员运行maa时最快截图耗时总是Encode并卡在开始唤醒界面无法点击。其他两种截图方式可以进入游戏

### Version

Resource Version: 罗德岛促融共竞
UI Version: v5.3.0-beta.2
Core Version: v5.3.0-beta.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15371285/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15371286/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/52186336/461ba9ef-ae90-4afc-9e71-b3fef9d0638f)

**Comment by zhengpip** [comment]
试试在mumu模拟器设置中关闭“后台挂机时保活运行”
<img width="669" alt="image" src="https://github.com/user-attachments/assets/7c98ea91-adb2-43e8-b10a-cd675fbb9592">

**Comment by status102** [comment]
Mumu12有自己的选项吧，不要用通用模式试试
