### ISSUE TITLE
mumu截图增强模式，自动公招会误触到停止招募

### ISSUE THREAD

**Issue by LiGithubYu** [MaaAssistantArknights/MaaAssistantArknights#9158]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

mumu截图增强模式，自动公招会误触到停止招募

### Version

Resource Version: 罗德岛促融共竞
UI Version: v5.3.0-beta.2.d012.gb4fc3528d
Core Version: v5.3.0-beta.2.d012.gb4fc3528d

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15371297/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15371298/gui.log)

### 截图

![Snipaste_2024-05-20_08-12-22](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/48920551/b60edce5-8679-466a-b58f-89f5bfe86e15)

**Comment by Rbqwow** [comment]
新版本加了点延迟 应该修了 先关了 复现再开
