### ISSUE TITLE
使用mumu截图增强模式，在公招中报错以及在基建换班中无响应

### ISSUE THREAD

**Issue by LspColor** [MaaAssistantArknights/MaaAssistantArknights#9160]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

<img width="962" alt="962fa5b2f71b7180d58d4cd6f2446be5" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105090376/d106c982-62fd-4d13-a7c0-4d94f19e6137">
如题如图 问题出现的时间点分别为11:46:50以及11:50:17

### Version

Resource Version: 罗德岛促融共竞
UI Version: v5.3.0-beta.2.d012.gb4fc3528d
Core Version: v5.3.0-beta.2.d012.gb4fc3528d

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15374261/gui.log)
[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15374266/asst.bak.zip)

**Comment by maderzhi** [comment]
请问你是直接用maa启动的模拟器吗，我遇到了相同的问题上报了还没反馈

我发现运行一次完成后关闭重新打开maa能够解决这个问题，但是原理不明

**Comment by LspColor** [comment]
并不是



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月22日(周三) 中午12:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 使用mumu截图增强模式，在公招中报错以及在基建换班中无响应 (Issue #9160)




 
请问你是直接用maa启动的模拟器吗，我遇到了相同的问题上报了还没反馈
 
我发现运行一次完成后关闭重新打开maa能够解决这个问题，但是原理不明

**Comment by maderzhi** [comment]
那我就不清楚了，等修吧

**Comment by horror-proton** [comment]
公开招募是卡在什么地方了, 看日志好像按了确认招募的那个蓝色勾之后出的问题

**Comment by LspColor** [comment]
> 公开招募是卡在什么地方了, 看日志好像按了确认招募的那个蓝色勾之后出的问题

他并没有卡住，只是报个了个错，没有实际上的影响，功能也正常

**Comment by kpAjun** [comment]
我也遇到了类似的问题，不报错但是在基建里面卡住，过了很久才发现问题

**Comment by Rbqwow** [comment]
新版本加了点延迟 应该修了 先关了 复现再开
