### ISSUE TITLE
5.2.3稳定版 获取信用及购物 里的 访问好友 没有正常执行

### ISSUE THREAD

**Issue by SilentHonorDarkKnight** [MaaAssistantArknights/MaaAssistantArknights#9162]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如标题，切换到好友列表后就停住了，什么也不操作过一段时间自己返回就接着进行后面的任务了，也不报错，初步怀疑是更新了名片背景导致的？

### Version

UI Version: v5.2.3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15379075/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15379077/gui.log)
最后几次的都没有正常执行，但是我在maa里是没看到报错的

**Comment by ABA2396** [comment]
Release v5.3.0-beta.2 fixed
