### ISSUE TITLE
自动战斗会将棘刺的持续伤害特效识别为技能就绪

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9171]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

2024.05.22 22.54.11开了一把自动战斗，其中棘刺打了的怪走到了肥鸭的上面，然后maa就点击了肥鸭，企图开启肥鸭的技能，我进行了手动干预继续了战斗，之后肥鸭技能好的时候就不再自动点了
其余情况不好找log了，大致就是走到棘刺上方的怪会导致maa开棘刺技能，如果作业刚好写的是“好了就开（制定次数）2次”的话，棘刺就无法正常开技能

### Version

v5.3.0-beta.2

### 日志文件

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15405886/asst.bak.log)
[asst(1).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15405888/asst.1.log)
[gui.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15405889/gui.bak.log)
[gui(1).log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15405891/gui.1.log)

### 还有别的吗？

目前写作业可以先把棘刺，台风这种干员写成好了就开（不限次数），这样即使误触也能正常运行

**Comment by Daydreamer114** [comment]
不止是棘刺特效，还有调香师皮肤、cost+1等

**Comment by ntgmc** [comment]
其实棘刺就是直接写不限次数既简单还方便

**Comment by Daydreamer114** [comment]
1
