### ISSUE TITLE
希望能够支持已复刻活动的代理

### ISSUE THREAD

**Issue by 117034130** [MaaAssistantArknights/MaaAssistantArknights#9173]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前输入OF或GT以外的复刻活动关卡时显示:不支持的关卡:MB-6，无法代理

### 其他内容

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/165804231/71b9015d-0dd6-43e8-a56f-8cd90898939b)

**Comment by ABA2396** [comment]
用 当前/上次
