### ISSUE TITLE
Yostar kr服务器启动画面上出现公告事项时，maa不会关闭公告事项

### ISSUE THREAD

**Issue by js1004b** [MaaAssistantArknights/MaaAssistantArknights#9175]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在使用maa的过程中，如果出现公告事项，maa不会自动点击画面，而是静止不动。如果出现公告事项,我手动按下确认按钮,maa才能进行。

### Version

Resource Version: 츠빌링슈튀르메의 가을 UI Version: v5.2.3 Core Version: v5.2.3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15407540/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15407541/gui.log)

### 截图

![Screenshot_2024 05 23_03 33 20 621](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/170081549/15eaf405-2bc1-433c-9ce7-c43417089360)

### 还有别的吗？

使用的模拟器: BlueStacks App Player 4
操作系统: Windows 11 Home

**Comment by Constrat** [comment]
iirc this is the maintenance notification. It's only there when a maint is in progress, meaning you wouldn't log either way (with or without MAA)
cc @HX3N

**Comment by HX3N** [comment]
AFAIK, it seems that the notice doesn't appear on other servers. To fix it, it seems like we'll need to add individual tasks.

Please paste this into `MAA/resource/global/YoStarKR/resource/task.json` and test it out. It worked when I tested it.

```json
    "StartUpThemes": {
        "next": [
            "GameStart",
            "StartUpNotificationKR",
            "StartToWakeUp",
            "StartToWakeUpOCR",
            "StartLoginBServer",
            "StartUpConnectingFlag",
            "MainThemes#next",
            "CloseAnnos#next",
            "OfflineConfirm"
        ]
    },
    "StartUpNotificationKR": {
        "doc": "This is a task for handling KR-specific announcements.",
        "action": "ClickSelf",
        "algorithm": "OcrDetect",
        "text": [
            "알겠습니다"
        ],
        "next": [
            "StartUpThemes#next"
        ]
    },
```

**Comment by js1004b** [comment]
It works! Thank you
Just in case, I'll upload the log file

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15410455/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15410456/gui.log)
