### ISSUE TITLE
定时执行没有切换到指定配置 

### ISSUE THREAD

**Issue by yunyiC** [MaaAssistantArknights/MaaAssistantArknights#9176]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我设定了每天早上自动开启后自动执行配置A，但是如果我前一天晚上关闭之前使用的是配置B，那么第二天早上会卡在配置B上，而没有正确切换到配置A

### Version

Resource Version: 罗德岛促融共竞
UI Version: v5.2.3
Core Version: v5.2.3

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15410347/debug.zip)
问题发生在2024年5月23日早上09:05

**Comment by ABA2396** [comment]
怎么设置的早上自动开启后自动执行配置A？
看日志是开了启动后立即执行吧，有两种方法
1. 关闭启动后立即执行，打开定时里的自定义配置，提前几分钟启动maa，让它定时执行之前重启换配置
2. 用附加命令直接打开指定配置的maa，比如maa的路径是 `C:\Users\*\Desktop\MAA\MAA.exe` ，那一般的目标是 `C:\Users\*\Desktop\MAA\MAA.exe`，但在后面加上 `--config 配置名` 可以直接打开对应配置的maa
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f7eb6e6f-edc8-4377-a785-9156cd32e1d4)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/51ebf738-f5fa-478e-8bb7-bd9123352fcc)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/c0e2589a-b0b1-490a-af60-33def03a24a4)

**Comment by ABA2396** [comment]
试试看拉长点间隔时间，这个是提前两分钟才重启切换配置的，我看日志里第一次启动的时间基本都是9:03多
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/de06497e-1c97-4622-87cd-856c313e918b)

**Comment by yunyiC** [comment]
好的，感谢大佬
