### ISSUE TITLE
自动公招-可能无法识别新增的“元素”tag

### ISSUE THREAD

**Issue by RunrunXi** [MaaAssistantArknights/MaaAssistantArknights#9178]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

“元素”tag是一个新增的一星tag，用于招募一星的巫医小车，但是MAA可能因为没有添加此tag导致无法识别，如果已经添加了此tag，建议和“支援机械”一样，添加一个能手动/自动确认招募的设置
提交时的MAA版本：v5.2.3“罗德岛促融共竞”
![MAA界面](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111105781/e293a583-174f-4db7-a68c-df3a1ded1bf3)
![Wiki界面](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111105781/98fe2614-950a-49b4-b2fc-db1ecea65a1b)

### 有什么好的想法？

添加此tag的支持或者添加手动/自动确认的选项

**Comment by Manicsteiner** [comment]
v5.3.0-beta1 后的版本已支持 #9047
