### ISSUE TITLE
联动森空岛签到

### ISSUE THREAD

**Issue by zlq193852347** [MaaAssistantArknights/MaaAssistantArknights#9180]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

在明日方舟登陆的时候，发送一个请求，森空岛登陆然后签到的请求

**Comment by yagol2020** [comment]
gitee上有类似的py（关键字`skyland-auto-sign`），可以配合使用MAA的`开始前脚本`自动签到

**Comment by SherkeyXD** [comment]
[MaaAssistantSkland](https://github.com/MaaXYZ/MaaAssistantSkland)
