### ISSUE TITLE
MUMUExtras未生效，没开后台保活，填了路径

### ISSUE THREAD

**Issue by zenoangel** [MaaAssistantArknights/MaaAssistantArknights#9183]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，填了模拟器路径但就是未生效，别的能正常运行
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/53809240/caf1dc88-a60e-4225-b15b-39da3fe32e13)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/53809240/59b0e6fe-fc7f-49f0-9872-1c2e88a2e866)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/53809240/b81a6618-495f-45e3-9217-b038be77b93d)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/53809240/68eec6c5-3842-428c-8498-7e76d63311e8)

### Version

Resource Version: 罗德岛促融共竞
UI Version: v5.3.0-beta.2
Core Version: v5.3.0-beta.2

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15417082/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15417083/gui.log)

**Comment by ABA2396** [comment]
啥版本的mumu

**Comment by Constrat** [comment]
Looking at the files date: 2024/03/08, I'm guessing it's not the latest version, as some would be either modified / more recent dates for the new update.

**Comment by zenoangel** [comment]
更新mumu后OK了，有段日子没想着更mumu了
