### ISSUE TITLE
自动公招最大招募次数未能正常运行

### ISSUE THREAD

**Issue by MagakiReimu** [MaaAssistantArknights/MaaAssistantArknights#9186]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动公招设置了最大公招次数999，但是实际执行次数未达到99次
![微信图片_20240524090800](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36392404/4765660b-fcb6-4445-be58-47a770f833df)
启动了2次，都是正常提示公招任务完成，第二次完成后自动执行肉鸽
已截图剩余白票263，加速165

### Version

Resource Version: 罗德岛促融共竞
UI Version: v5.3.0-beta.3
Core Version: v5.3.0-beta.3

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15425710/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15425712/asst.log)

gui.log 
[2024-05-24 08:06:15.599] <1><> 任务已全部完成！
[2024-05-24 08:31:22.253] <1><> 完成任务: Recruit

### 截图

![微信图片_20240524090800](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36392404/fc5cf93c-e7f0-4d57-b012-69add66f2813)
![微信图片_20240524090813](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36392404/a8789aa5-ee27-409b-94fc-3c2a54aded12)
![微信图片_20240524092337](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36392404/42bd4eba-8e73-4787-81d7-cf2ba37a24f4)

**Comment by horror-proton** [comment]
看日志这是因为招募的时候出现了几次加急许可使用失败的情况, MAA 认为耗尽了加急许可所以停止使用了

**Comment by MagakiReimu** [comment]
> 看日志这是因为招募的时候出现了几次加急许可使用失败的情况, MAA 认为耗尽了加急许可所以停止使用了

这里是不是可以加一个识别加急许可的剩余数量？然后如果失败了，中间增加间隔重试？有可能是Win10的自动更新吃了一点资源，导致模拟器卡顿了
