### ISSUE TITLE
因为有新界面，会执行动作，但是因为访问好友功能无法识别，不访问好友了

### ISSUE THREAD

**Issue by baibaizhi** [MaaAssistantArknights/MaaAssistantArknights#9188]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [x] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

应该是新增了新界面的关系，访问好友功能无法识别，不会执行。

### Version

Resource Version: 慈悲灯塔，UI Version: v5.2.3，Core Version: v5.2.3

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15427054/asst.log)

**Comment by Rbqwow** [comment]
看公告

**Comment by Constrat** [comment]
How about we start updating and checking latest beta before opening issues?

> * [ ]  I have reviewed the update for the latest beta version and did not mention that the bug has been fixed
> * [ ]  I have checked the pinned issue to make sure my question is not mentioned

You've checked these two, but clearly haven't done either.
I'm sorry if I'm sounding rude, but those checks are there for this exact reason. To reduce duplicates and useless issues which have already been fixed.
