### ISSUE TITLE
国际服傀影肉鸽不期而遇卡死

### ISSUE THREAD

**Issue by delishalita** [MaaAssistantArknights/MaaAssistantArknights#9190]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

傀影肉鸽遭遇‘不期而遇’关卡（我看到的是‘以血还血’），未识别出事件（gui.log上未记录）从而卡死，人工选择后正常运行。
看了眼截图，出现问题的时间点无截图但前面发现相同事件的截图存在问题，maa截图截快了可能
顺带吐个小槽，战斗关卡‘雕匠与石像’ 把斑点放左侧柱子下方且最后放，蓝门门口三条路上路铃兰中路空着下路棘刺，maa的作战思路是有点东西的

### Version

Resource Version: Il Siracusano - Retrospection
UI Version: v5.2.3
Core Version: v5.2.3

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15430123/gui.log)
[asst.bak.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15430145/asst.bak.zip)
时间点为[2024-05-24 14:59:55.131] 左右

### 截图

![2024-05-22_22-30-56-134_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141008785/b8abcfa6-dcae-443a-a49b-b0739abae615)

### 还有别的吗？

mumu12模拟器
分辨率为1920*1080

**Comment by Manicsteiner** [comment]
> [2024-05-24 15:00:23.416][TRC][Px51f0][Tx2e44] asst::WordOcr [{ 3Eye For an Eye: [ 80, 88, 165, 34 ], score: 0.914899 }, { A refined,well-dressed Sarkaz gentleman stands before you.He politely asks if you know: [ 115, 128, 607, 17 ], score: 0.958273 }, { innocent man who was once wrongfully punished because of him. You ask him to elaborai: [ 115, 150, 607, 14 ], score: 0.936472 }, { that,because of a mistake he made,the villagers all mistook his friend for a Vampire and: [ 114, 169, 606, 17 ], score: 0.950469 }, { here.The man promises a sizable reward if you lend him your help.: [ 113, 190, 454, 17 ], score: 0.956448 }] by OCR Pipeline , cost 2875 ms

> "title": "Eye For an Eye"

多识别到一个字，没认出关卡名

**Comment by delishalita** [comment]
ok，主要因为让maa刷着放后台，有时候看一眼的确会卡在需要选择的不期而遇（包括之前萨米的对决斗蛐蛐上）
