### ISSUE TITLE
基建换班时候，总是会有个别低心情干员没进入宿舍。

### ISSUE THREAD

**Issue by Mudrockiii** [MaaAssistantArknights/MaaAssistantArknights#9195]
### 说说你遇到的问题？

![f998ec9a7589488c15d615f5f593856](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110472431/7682039a-af96-433d-9ca2-f4367b0070d7)
![d3c91613c8d4b11b69ca6de3b5f0f47](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/110472431/655dfba7-d8fd-44c7-a38a-f991d440d38a)

**Comment by ABA2396** [comment]
宿舍放最后换

**Comment by Nothing1031** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34674655/c2f5c2d3-38d4-440c-a5e1-d2c7b75703b9)
我也遇到相同的问题，多次出现宿舍放了低信赖满心情的干员，但是有心情不满且没在工作的干员没有放进宿舍

**Comment by ABA2396** [comment]
> ![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34674655/c2f5c2d3-38d4-440c-a5e1-d2c7b75703b9)
> 我也遇到相同的问题，多次出现宿舍放了低信赖满心情的干员，但是有心情不满且没在工作的干员没有放进宿舍

宿舍放最后换

**Comment by Nothing1031** [comment]
> > ![image](https://private-user-images.githubusercontent.com/34674655/333795176-c2f5c2d3-38d4-440c-a5e1-d2c7b75703b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDA0ODAsIm5iZiI6MTcxNjY0MDE4MCwicGF0aCI6Ii8zNDY3NDY1NS8zMzM3OTUxNzYtYzJmNWMyZDMtMzhkNC00NDBjLWE1ZTEtZDJjN2I3NTcwM2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEyMjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3N2NiOTQzYWIwZDIwNjk4Zjc3NGM5MTBiYmQzNzZkNTJhMmU2Yzc4Mzk4NzI1OTExNjcyMmI2ZTAyYWM5OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AeTfrXEONh-Q-hBLuITMYBiP3LF7Nc_KQw7-8bfMbJQ)
> > 我也遇到相同的问题，多次出现宿舍放了低信赖满心情的干员，但是有心情不满且没在工作的干员没有放进宿舍
> 
> 宿舍放最后换

截图的执行顺序，宿舍后面不是就只有加工站和训练室吗，心情没满的干员可以确定不是从这两个房间换出来的
