### ISSUE TITLE
傀影肉鸽关卡一直识别错误

### ISSUE THREAD

**Issue by dbwng** [MaaAssistantArknights/MaaAssistantArknights#9199]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

识别关卡的时候只会识别成 关卡：紧急作战
五周年版本的时候没有这个问题

### Version

Resource Version: 孤星·复刻
UI Version: v5.3.0
Core Version: v5.3.0

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15442448/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/170797531/ce3f2d9f-8d30-4625-a354-6ff75910099e)

**Comment by Manicsteiner** [comment]
请上传 asst.log 和 asst.bak.log

**Comment by dbwng** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15448212/asst.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15448213/asst.bak.log)


> 请上传 asst.log 和 asst.bak.log

**Comment by Manicsteiner** [comment]
> [2024-05-25 19:17:54.912][TRC][Px3700][Txb600] match_templ | Phantom@Roguelike@StageEmergencyDps.png score: 0.953984 rect: [ 330, 303, 121, 46 ] roi: [ 0, 53, 1280, 554 ]
> [2024-05-25 19:17:55.886][TRC][Px3700][Txb600] match_templ | Phantom@Roguelike@StageEmergencyDpsEnter.png score: 0.972826 rect: [ 1086, 424, 120, 118 ] roi: [ 1035, 370, 226, 300 ]

识别成紧急作战了，应该不影响进行作战，组队也正常，然后似乎突然就卡死了
复现了普通关卡识别为紧急作战，但后续仍然一切正常
感觉应该是个小概率问题

**Comment by dbwng** [comment]
> > [2024-05-25 19:17:54.912][TRC][Px3700][Txb600] match_templ | Phantom@[Roguelike@StageEmergencyDps.png](mailto:Roguelike@StageEmergencyDps.png) score: 0.953984 rect: [ 330, 303, 121, 46 ] roi: [ 0, 53, 1280, 554 ]
> > [2024-05-25 19:17:55.886][TRC][Px3700][Txb600] match_templ | Phantom@[Roguelike@StageEmergencyDpsEnter.png](mailto:Roguelike@StageEmergencyDpsEnter.png) score: 0.972826 rect: [ 1086, 424, 120, 118 ] roi: [ 1035, 370, 226, 300 ]
> 
> 识别成紧急作战了，应该不影响进行作战，组队也正常，然后似乎突然就卡死了 复现了普通关卡识别为紧急作战，但后续仍然一切正常 感觉应该是个小概率问题

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/170797531/04e02293-aa35-4437-99d3-81570012ad23)
这个问题一直出现，而且有时会出现红色的关卡识别错误，导致一个干员都不放

[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15470747/asst.bak.log)
