### ISSUE TITLE
公开招募改进需求

### ISSUE THREAD

**Issue by sakuraxp** [MaaAssistantArknights/MaaAssistantArknights#92]
当同时出现两组不同的四星tag时（如：位移，狙击干员，生存），现在的逻辑是选择其中一组（如 位移）。由于tag有一定概率会yj被划掉，希望能支持同时选上两组可以提高容错。

**Comment by tkkcc** [comment]
还有这种操作！

**Comment by MistEO** [comment]
和另一个需求有冲突，之前有群友说 Tag 尽量少，因为选多了更费龙门币 orz
所以现在是按照尽可能高星的同时尽可能少 Tag 来选的。。

可能考虑做成一个选项吧，属于是新建文件夹了（

**Comment by zhongfly** [comment]
我一般都是把能出高星的全选上，也多不了几个龙门币

**Comment by pengliansheng** [comment]
确实做一个选项好一点，我也是习惯把能选的都先满，这样有些三星tag也有概率出四星，龙门币又不是很缺，黄票是真缺啊
