### ISSUE TITLE
如果可能的话，可以加一个模拟器清内存的设置（？

### ISSUE THREAD

**Issue by desktop4025** [MaaAssistantArknights/MaaAssistantArknights#920]
如果设置定时刷的话，长时间开着模拟器，模拟器会越来越卡，感觉清一下模拟器内存会好一点？
或许有哪个比较适合长时间开着的模拟器（？现在用的是蓝叠国际版

**Comment by MistEO** [comment]
直接关了模拟器就好了，有计划做了

Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/894

**Comment by AkagiYui** [comment]
> 直接关了模拟器就好了，有计划做了
> 
> Duplicate of #894

目前我是24小时开着蓝叠国际版模拟器的，感觉没什么问题，我是不希望在我使用电脑时自动开关模拟器的，因为这样会突然弹出窗口，这在一些情况下会造成不好的电脑使用体验。

**Comment by desktop4025** [comment]
> 

所以我是建议加一个这个功能给有需要的人用嘛

**Comment by AkagiYui** [comment]
抱歉，在错误的issue中回复了。
