### ISSUE TITLE
完成任务后会弹出win10提示音

### ISSUE THREAD

**Issue by haoshishaodeng** [MaaAssistantArknights/MaaAssistantArknights#9212]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题

### 有什么好的想法？

希望能不弹通知

**Comment by Manicsteiner** [comment]
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/5d0bab1f-e05f-4595-928c-ef04c2c264de)
可以关掉这个选项
