### ISSUE TITLE
开机无法自启

### ISSUE THREAD

**Issue by boluochu** [MaaAssistantArknights/MaaAssistantArknights#9213]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

每次勾选完开机自启maa后，重新打开maa都会取消了勾选。并且重启电脑也无法正常使用自启功能

### Version

Resource Version: 孤星·复刻 UI Version: v5.3.1 Core Version: v5.3.1

### 日志文件

因为闪退问题重新安装maa，然后就有这个问题了
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446530/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446532/gui.log)
[ocr_config.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446535/ocr_config.json)
[recruitment.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446536/recruitment.json)
[stages.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446537/stages.json)
[tasks.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446538/tasks.json)
[version.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446539/version.json)
[battle_data.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446540/battle_data.json)
[config.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446541/config.json)
[dynamic_list.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446542/dynamic_list.txt)
[infrast.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446543/infrast.json)
[item_index.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446544/item_index.json)
[allFileDownloadComplete.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446548/allFileDownloadComplete.json)
[etag.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446549/etag.json)
[lastUpdateTime.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15446550/lastUpdateTime.json)

### 截图

![24fcf29109607a0452ac0396ae3ff74d](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/170851788/eab95694-372c-4bfc-962b-9cce74dc1cbe)

**Comment by ABA2396** [comment]
日志报了Attempted to perform an unauthorized operation.说明maa没权限打开注册表去放开机自启的命令。这个问题得你自己检查下，比如你登录Windows的账号有没有足够的权限访问或修改注册表键，组策略有没有限制修改注册表
