### ISSUE TITLE
萨米肉鸽无限放弃探索

### ISSUE THREAD

**Issue by SymmFz** [MaaAssistantArknights/MaaAssistantArknights#9214]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在萨米肉鸽中，MAA选择干员后，进入路线选择界面时，会直接点击左上角放弃探索，然后重新开始一局新的肉鸽并再次放弃探索，导致无限循环放弃探索。

模拟器: MuMu12
模式: 增强截图模式和普通模式均有此问题。

预期行为：
MAA 应该继续探索，而不是自动放弃探索。

### Version

Resource Version: 孤星复刻
UI Version: v5.3.1
核心版本：v5.3.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15447006/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15447007/gui.log)

### 截图

![Clip_2024-05-26_18-12-31](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66204453/b903cad0-4bc4-4206-bcaa-c9c91e110692)
![Clip_2024-05-26_18-18-05](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/66204453/65ad7a52-49b6-4ac1-9541-4847cc6a6911)

**Comment by ntgmc** [comment]
Also duplicate of #9144

**Comment by SymmFz** [comment]
更新到公测版本 `v5.4.0-beta.1` 后，无限放弃探索的问题解决了
