### ISSUE TITLE
选择维什戴尔开局，但maa选了取长补短分队

### ISSUE THREAD

**Issue by cortana112** [MaaAssistantArknights/MaaAssistantArknights#9216]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

选择维什戴尔开局，但maa选了取长补短分队，

### Version

Resource Version: 孤星·复刻
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15447773/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15447774/gui.log)
5月26日 21:54 22:08 各试了一次

### 截图

无

### 还有别的吗？

mumu12 Windows
有21:54的视频https://www.bilibili.com/video/BV1Yn4y1o7zA/?spm_id_from=333.999.0.0&vd_source=0065929f86c6df81092a42cac6db3fe1

**Comment by Lancarus** [comment]
自己选一下分队
