### ISSUE TITLE
建议更新字库-逻各斯一技能名称“殁亡”中的“殁”无法显示

### ISSUE THREAD

**Issue by RunrunXi** [MaaAssistantArknights/MaaAssistantArknights#9217]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

逻各斯一技能名称“殁亡”中的“殁”无法显示
![logos](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111105781/873674bb-cccc-4d33-9dd7-b8bedb18292c)
![pic](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111105781/aa925760-5afe-4da5-999e-07a6a6175f73)

### 有什么好的想法？

建议更新字库

**Comment by 1553767977** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39228172/834812b7-2ea3-47bc-a379-bb4246d744db)
我遇到的是这个样子的.jpg

**Comment by status102** [comment]
ocr结果问题
