### ISSUE TITLE
基建排班宿舍不会填满干员

### ISSUE THREAD

**Issue by dundanjiang** [MaaAssistantArknights/MaaAssistantArknights#9219]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用MAA自带的243一天极限四换排班表经常宿舍指定干员会少一两个，而且不会自动填满，已勾选蹭信赖
如图上面的宿舍没有填满干员，下面的宿舍少了伊芙利特

### Version

Resource Version: 孤星·复刻
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15454530/gui.log)
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15454549/asst.zip)

### 截图

![微信截图_20240527180728](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121685132/33a860db-fb80-40dc-ab8b-94c3d803014b)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/a351f57a-ea0f-4f6c-b052-617a1d56af92)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/08824903-c7f6-4566-bc11-86d62c9a1aca)

**Comment by dundanjiang** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/334071714-ef1be0ae-fbed-49d0-906c-e45a393b47d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDg0MzgsIm5iZiI6MTcxNjgwODEzOCwicGF0aCI6Ii85OTA3Mjk3NS8zMzQwNzE3MTQtZWYxYmUwYWUtZmJlZC00OWQwLTkwNmMtZTQ1YTM5M2I0N2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDExMDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NDBjMmIzMjA5MDEzMTJiOWY1YzJjMDk5YzA0N2FiZmE2OWViZDhhYjM2M2QzYzI1YWJlYWMzYmFiMTJjNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rfK_E7ch4JICAvfRZs1UNBtca7mOK0yTm6psK3iwn8w) ![image](https://private-user-images.githubusercontent.com/99072975/334071421-a351f57a-ea0f-4f6c-b052-617a1d56af92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDg0MzgsIm5iZiI6MTcxNjgwODEzOCwicGF0aCI6Ii85OTA3Mjk3NS8zMzQwNzE0MjEtYTM1MWY1N2EtZWEwZi00ZjZjLWIwNTItNjE3YTFkNTZhZjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDExMDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmY2I2NjFhNzIwYjY5YTI2NWI1ZjU5ODAyZjUwYzU1NWZiYjgyM2MzMWVhYjM5ZjUwYzA2YmE2MzE3ZTBkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BVjrYU9mM59jL2I5vBIBWApizUfaql3MifZWOyR7t0A) ![image](https://private-user-images.githubusercontent.com/99072975/334071519-08824903-c7f6-4566-bc11-86d62c9a1aca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDg0MzgsIm5iZiI6MTcxNjgwODEzOCwicGF0aCI6Ii85OTA3Mjk3NS8zMzQwNzE1MTktMDg4MjQ5MDMtYzdmNi00NTY2LWJjMTEtODZkNjJjOWExYWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDExMDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMTg3MzdjYzNmYWQ3ZmZkMWU2OGQwZjkzNzI3MDI5YjhhNDU0MzM4NTFjMWNmODA0NzQ0NjVjZmQxZmYxYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PPyEpTmjkM3d63KZtPsV1a3FTq87rLPejLtYBIooOgU)

请问一下，我用的还是旧版的界面，没有补满干员这个开关，那我是要把空位置蹭信赖关了吗

**Comment by ABA2396** [comment]
比如你现在是
```
1: 菲亚梅塔 自动
2: 自动
3: 爱丽丝, 车尔尼, 塑心 自动
4: 赫默, 伊芙利特, 塞雷娅, 白面鸮 自动
```
你得改成
```
1: 菲亚梅塔, 爱丽丝, 车尔尼, 塑心, 赫默
2: 伊芙利特, 塞雷娅, 白面鸮 自动
3: 自动
4: 自动
```
这种样子

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/074b54a0-25dd-47cd-bb43-fe95d544a6a2)
用了自动补满空位之后的宿舍就别用指定干员了

**Comment by dundanjiang** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/334082020-074b54a0-25dd-47cd-bb43-fe95d544a6a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTY2ODksIm5iZiI6MTcxNjgxNjM4OSwicGF0aCI6Ii85OTA3Mjk3NS8zMzQwODIwMjAtMDc0YjU0YTAtMjVkZC00N2NkLWJiNDMtZmU5NWQ1NDRhNmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEzMjYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZmQxYTQwYjgyYWQwOTU1NGVlMGZmMjRmZWZlMTNiZTYzYjcxODI1ODQxOWM0Y2U4MTllNThhNDA3NTBhZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mofst81CH4pyZh6IS0hk9RUgvcnqiJw5oVutFKe7t04) 用了自动补满空位之后的宿舍就别用指定干员了

![微信截图_20240527212514](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121685132/205749b4-54ce-41a2-9654-a55ea49e9407)
![微信截图_20240527212531](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121685132/ccce60af-7ed0-44bc-ab59-f74d39dc28cc)
我现在用的是这个版本的MAA，直接用的自带的排班表，里面是第一张图那样的，我现在是需要把“宿舍剩余位置蹭信赖”这个关了就行，还是说在这个排班表的基础上重新改一下改成5个指定干员放在一间的呢

**Comment by ABA2396** [comment]
这两个排班表有问题，在基础上改一下，我找找写这个的人说一下

**Comment by bodayw** [comment]
@dundanjiang 

你现在用的这个排班表是我做的。我来试图详细解释一下：

> 我用的还是旧版的界面，没有补满干员这个开关

那个界面不是 maa 的，是一图流网站上的排班表编辑器，也就是这个：
https://ark.yituliu.cn/tools/schedule

这个排班表编辑器里专门做了个提示，其实也就是对应了上面 @ABA2396 发的 maa 排班表协议里的一句注释：
`// 注意可能和后面自定义的干员产生冲突，比如把后面需要的干员拿到这里用了，请谨慎使用，或将 autofill 的房间顺序放到最后`

意思是说，排班表里要小心使用 `autofill`（自动填充干员）这个功能，以宿舍为例（我的表里也只有宿舍用了 `autofill`）的话，因为 maa 运行时，是对四个宿舍从上到下按顺序处理的，所以理论上为了稳妥，应该让需要指定的干员进入靠前的宿舍，然后其余宿舍空位使用自动填充，否则，如果靠前的宿舍先启用了自动填充，maa 有可能“提前”把某个后面指定的干员放进前面的宿舍了，然后运行到后面的宿舍，maa 就会把前面放进去的干员又拿出来放在这个宿舍，或者说如果开启了“不将已进驻的干员放入宿舍”，maa 可能会找不到指定的干员，总之都会导致宿舍没有全部放满（影响迷迭香的制造效率）。

我在做这个排班表时是知道这个问题的，但我还是选择了这样排，理由我在这里解释了一下：
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/8825#issuecomment-2134807588

我看了你上传的日志文件里除了第一次使用这个排班表以外最近 8 次的记录，可以看到 maa 在每一次执行到最后一个宿舍时都在同一屏识别到了赫默、伊芙利特、塞雷娅和白面鸮这四个干员，说明这四个人是已经在这个宿舍里的（这四个人都没有宿舍基建技能，如果不是已经进驻，排序会很靠后），是符合我的设计的，所以我不知道为什么最后反而会缺人（比如伊芙利特反而被移出了宿舍）。

我暂时能想到的一个可能性是，maa 在选择进驻干员时，会先清空当前选择，然后按排班表上指定的干员去点击选择，结果在点击的时候恰好碰到游戏客户端触发了服务器同步，结果一部分点击没有生效。这种情况我也是遇到过的，本来已经设别完了该选 5 个人，结果只进去了 4 个人，不过这种情况应该说并不会经常发生。

**Comment by dundanjiang** [comment]
> @dundanjiang
> 
> 你现在用的这个排班表是我做的。我来试图详细解释一下：
> 
> > 我用的还是旧版的界面，没有补满干员这个开关
> 
> 那个界面不是 maa 的，是一图流网站上的排班表编辑器，也就是这个： https://ark.yituliu.cn/tools/schedule
> 
> 这个排班表编辑器里专门做了个提示，其实也就是对应了上面 @ABA2396 发的 maa 排班表协议里的一句注释： `// 注意可能和后面自定义的干员产生冲突，比如把后面需要的干员拿到这里用了，请谨慎使用，或将 autofill 的房间顺序放到最后`
> 
> 意思是说，排班表里要小心使用 `autofill`（自动填充干员）这个功能，以宿舍为例（我的表里也只有宿舍用了 `autofill`）的话，因为 maa 运行时，是对四个宿舍从上到下按顺序处理的，所以理论上为了稳妥，应该让需要指定的干员进入靠前的宿舍，然后其余宿舍空位使用自动填充，否则，如果靠前的宿舍先启用了自动填充，maa 有可能“提前”把某个后面指定的干员放进前面的宿舍了，然后运行到后面的宿舍，maa 就会把前面放进去的干员又拿出来放在这个宿舍，或者说如果开启了“不将已进驻的干员放入宿舍”，maa 可能会找不到指定的干员，总之都会导致宿舍没有全部放满（影响迷迭香的制造效率）。
> 
> 我在做这个排班表时是知道这个问题的，但我还是选择了这样排，理由我在这里解释了一下： [#8825 (comment)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/8825#issuecomment-2134807588)
> 
> 我看了你上传的日志文件里除了第一次使用这个排班表以外最近 8 次的记录，可以看到 maa 在每一次执行到最后一个宿舍时都在同一屏识别到了赫默、伊芙利特、塞雷娅和白面鸮这四个干员，说明这四个人是已经在这个宿舍里的（这四个人都没有宿舍基建技能，如果不是已经进驻，排序会很靠后），是符合我的设计的，所以我不知道为什么最后反而会缺人（比如伊芙利特反而被移出了宿舍）。
> 
> 我暂时能想到的一个可能性是，maa 在选择进驻干员时，会先清空当前选择，然后按排班表上指定的干员去点击选择，结果在点击的时候恰好碰到游戏客户端触发了服务器同步，结果一部分点击没有生效。这种情况我也是遇到过的，本来已经设别完了该选 5 个人，结果只进去了 4 个人，不过这种情况应该说并不会经常发生。

感谢解答，我这边基本上一天会出现两次这个情况，除了两个短班宿舍全部指定的班次外，其他两个都会出现这个问题，我这边去一图流里取消勾选了自动填充，勾选上了按顺序选中，并且重新安装了MAA，看看能不能解决，如果还是不行我再来反馈

**Comment by bodayw** [comment]
> 感谢解答，我这边基本上一天会出现两次这个情况，除了两个短班宿舍全部指定的班次外，其他两个都会出现这个问题，我这边去一图流里取消勾选了自动填充，勾选上了按顺序选中，并且重新安装了MAA，看看能不能解决，如果还是不行我再来反馈

这里的问题应该和是否按顺序无关，按顺序是为了保证进驻顺序，避免换班时给有暖机类技能的人变了位置而需要从头暖机

你如果取消了自动填充，那应该把需要进驻的手动排上，不然 maa 就直接给空着了

所以说你遇到问题的时候具体是怎样的情况？四个宿舍分别都放进了哪些人？每次都是伊芙利特和塑心没放进去吗？没能放进去的干员是最近才招到（信赖不满）还是说你手动拿去在基建上过班（心情有消耗）？

**Comment by dundanjiang** [comment]
> > 感谢解答，我这边基本上一天会出现两次这个情况，除了两个短班宿舍全部指定的班次外，其他两个都会出现这个问题，我这边去一图流里取消勾选了自动填充，勾选上了按顺序选中，并且重新安装了MAA，看看能不能解决，如果还是不行我再来反馈
> 
> 这里的问题应该和是否按顺序无关，按顺序是为了保证进驻顺序，避免换班时给有暖机类技能的人变了位置而需要从头暖机
> 
> 你如果取消了自动填充，那应该把需要进驻的手动排上，不然 maa 就直接给空着了
> 
> 所以说你遇到问题的时候具体是怎样的情况？四个宿舍分别都放进了哪些人？每次都是伊芙利特和塑心没放进去吗？没能放进去的干员是最近才招到（信赖不满）还是说你手动拿去在基建上过班（心情有消耗）？

放不进去的都是随机的，塞雷娅伊芙利特白面鸮都出现过没进去的情况，这几个心情一直都是满的，就很奇怪不知道为什么会出现这种问题

**Comment by bodayw** [comment]
那没被放进去的人是被放进了更靠前的宿舍里吗？如果没有的话，那应该可以排除是自动填充导致的，要在其他方面找原因了。

（哦，话说我看见你没有勾选“不将已进驻的干员放入宿舍”，那既然最后一个宿舍里还会缺人，基本也可以排除是自动填充的问题了）

**Comment by dundanjiang** [comment]
> 那没被放进去的人是被放进了更靠前的宿舍里吗？如果没有的话，那应该可以排除是自动填充导致的，要在其他方面找原因了。
> 
> （哦，话说我看见你没有勾选“不将已进驻的干员放入宿舍”，那既然最后一个宿舍里还会缺人，基本也可以排除是自动填充的问题了）

今天又出现这个问题了，我自己重新做了个排班表是  "赫默","伊芙利特", "塞雷娅" "麦哲伦",  "远牙"，5个指定的也缺了3个，只放进去了远牙和麦哲伦，autofill也是false状态，重新跑了一遍当次排班又没问题了，应该能排除是排班表的问题，感觉像是MAA自己的问题

**Comment by leolbyy** [comment]
> "dorm_notstationed_enabled":true

**Comment by leolbyy** [comment]
> "dorm_notstationed_enabled":true
想问一下这个配置在cli配置文档里有效吗？在集成文档没有看到相关参数，但是从实际效果来看这个参数被默认设置为true了

**Comment by leolbyy** [comment]
> > （哦，话说我看见你没有勾选“不将已进驻的干员放入宿舍”，那既然最后一个宿舍里还会缺人，基本也可以排除是自动填充的问题了）
> 
> 更正：我在日志里看到了 `"dorm_notstationed_enabled":true`，而且看 `minitouch click` 记录确实执行了点击筛选 - 未进驻、以及确认按钮，所以在日志记录的时候肯定是勾选了的。
> 
> 不管怎么样，结论不变。日志里可以看到每次都识别到了赫默、伊芙利特、塞雷娅和白面鸮，而且排在一起，maa 也对排在最前面的四个干员卡片坐标执行了点击……
> 
> 不过我毕竟还是对 maa 的内部架构不熟悉，看日志也只是望文生义，有可能漏过了什么关键信息。

"dorm_notstationed_enabled":true"
请问这个参数在cli的配置里有效吗？集成文档没有看到相关参数，但是从实际效果来看这个参数是被默认设置为true，并且导致了很多bug

**Comment by bodayw** [comment]
今天客户端更新之后，乌尔比安大概率会进 243 极限排班表。如果本帖的问题暂时没能解决的话，我会在更新的排班表里手动指定所有进驻宿舍的干员来规避，副作用就是如果你需要手动把在加工站和训练室用过的干员放进宿舍休息。

After the game client update today, Ulpianus is likely joining the new schedule. So I will try to manually specify all ops in the dorm to work around this issue if it's not fixed by then. Downside would be that you'll have to manually put those ops worked in the workshop / training room into the dorm.

**Comment by bodayw** [comment]
> We discussed something similar before. My biggest suggestion is to just edit the file, and manually fill the dormitories (it can be a bit of a hassle the first time, but it will be worth it, as no conflicts will appear).

> So I will try to manually specify all ops in the dorm to work around this issue if it's not fixed by then.

Oh, I must have overlooked the last comment from the OP above:

> 我自己重新做了个排班表是 "赫默","伊芙利特", "塞雷娅" "麦哲伦", "远牙"，5个指定的也缺了3个，只放进去了远牙和麦哲伦，autofill也是false状态

Rough translation: I made a schedule myself with 5 designated operators and `autofill` set to `false`, the issue still happened.

Not sure this actually has the same cause, and I do feel like the issue could happen more often when MAA is trying to auto-fill, but manually designating all operators to put into the dorm may not completely avoid the issue, either...
