### ISSUE TITLE
自定义基建排班无法执行却直接识别为任务已完成

### ISSUE THREAD

**Issue by 2041314737** [MaaAssistantArknights/MaaAssistantArknights#9221]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我导入了通过基建可视一图流自制的自定义基建排班表，并点开了基建换班功能，整个换班过程仅能实现菲亚梅塔的使用，后续的基建排班无法完成，但maa日志却显示任务已完成：Infrast

### Version

Resource Version: 孤星·复刻
UI Version: v5.3.2-alpha.1.d013.g1652647f1
Core Version: v5.3.2-alpha.1.d013.g1652647f1

### 日志文件

[Uploading gui.log…]()

### 截图

![MuMu12-20240527-234155](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/170962156/da085061-e33e-492b-8555-b731375852a6)
![maa1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/170962156/da74c2f1-17c4-49bd-826c-444a7be91063)
![maa2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/170962156/b341058a-5002-4376-9ee0-4cecd9287a09)

- 

### 还有别的吗？

[1716821771298567.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15457794/1716821771298567.json)
[1716823461094774.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15457795/1716823461094774.json)

**Comment by 2041314737** [comment]
![MuMu12-20240527-234155](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/170962156/cfad8fca-6623-44e7-9af4-5a5787ff9ef0)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15457837/asst.log)

**Comment by ABA2396** [comment]
你这是把设置里所有设施的勾都取消了？
