### ISSUE TITLE
up我用的时候自动战斗老是延迟放下干员导致漏怪

### ISSUE THREAD

**Issue by siyuetiantang** [MaaAssistantArknights/MaaAssistantArknights#923]
up我用的时候自动战斗老是延迟放下干员导致漏怪，我WIN11系统，自动编队好像也找不到干员。

**Comment by ABA2396** [comment]
发下日志看看。自动编队之前是发现了个问题，加了特别关注的干员就识别不上，这个要之后想想怎么改了。自动战斗延时是差很多还是怎么样？差的不多试试一倍速的作业。

**Comment by MistEO** [comment]
请附上日志，谢谢
