### ISSUE TITLE
自动肉鸽开局干员建议添加逻各斯

### ISSUE THREAD

**Issue by AzuresongZ** [MaaAssistantArknights/MaaAssistantArknights#9231]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by Daydreamer114** [comment]
建议先手动logos开局然后看看效果发出来

**Comment by AzuresongZ** [comment]
经测试，通过在开局干员手动输入logos即可开局，问题已解决，谢谢！


> 建议先手动logos开局然后看看效果发出来

**Comment by AzuresongZ** [comment]
在开局干员手动输入logos即可开局，问题已解决
