### ISSUE TITLE
RawWithGzip截图耗时时间长

### ISSUE THREAD

**Issue by karaipsum** [MaaAssistantArknights/MaaAssistantArknights#9235]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

此前好像并不显示经由 RawWithGzip 截图，截图时间大约在 200-300ms 上下
显示 RawWithGzip 后截图时间明显上升，今天达到约 700ms
昨天在延长的截图时间后出现公招识别失败（不确定是否与截图时间有关），然后直接跳转到下一个任务的问题
目前自动战斗等功能似乎都正常，没有测试自动肉鸽或生息演算表现

### Version

Resource Version: 孤星·复刻
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

2024-05-28 22:29：公招识别错误
2024-05-29 12:57：截图时间达到 707ms
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15488535/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15488536/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/47909133/d4460053-bd50-4146-bdff-c7410f96fbd0)

### 还有别的吗？

模拟器：BlueStacks 5.13.200.1026 P64
系统：Windows 11 专业版 23H2 22631.3593 Windows Feature Experience Pack 1000.22700.1003.0
简要配置：5900X, 32G RAM

**Comment by status102** [comment]
仅供展示，自动选最快
