### ISSUE TITLE
在amd的23.40.33.04测试版本的显卡驱动上频繁出现电脑突然重启问题

### ISSUE THREAD

**Issue by Maboroshinatsu** [MaaAssistantArknights/MaaAssistantArknights#9237]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我的显卡是5600xt
在电脑上运行MAA时，连接游戏一段时间后经常会出现突然重启现象，每一次运行都可以稳定复现，但具体发生时间不确定
具体表现为屏幕内容突然定住，声音卡住，然后黑屏重启
目前怀疑是测试版驱动原因，此版本驱动版本号为23.40.33.04，是24.5.1驱动的新预览版本，下为版本说明
https://www.amd.com/en/resources/support-articles/release-notes/RN-RAD-WIN-24-5-1-AL2-TECH-PREVIEW.html
我会在明天尝试使用正式版驱动运行maa

### Version

Resource Version: 孤星·复刻
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15508627/asst.log)
[gui.log](https://github.com/user-attachments/files/15508629/gui.log)

### 还有别的吗？

使用的是mumu模拟器
操作系统为windows10

**Comment by Maboroshinatsu** [comment]
更换正式版5.1版本驱动后仍然出现此问题

**Comment by Maboroshinatsu** [comment]
我并没有安装这个软件，但图吧工具箱中包含了一个叫ramdisk的软件，但我并没有用过，我会尝试卸载后运行maa

**Comment by Maboroshinatsu** [comment]
卸载后仍然出现此问题

**Comment by Rbqwow** [comment]
在事件查看器里找找有没有相关的事件
maa现在还不会调用gpu 如果真是显卡问题那应该是模拟器的锅
