### ISSUE TITLE
挂机槐影肉鸽时发现地图与藏品存在冲突

### ISSUE THREAD

**Issue by xianyuking666** [MaaAssistantArknights/MaaAssistantArknights#9241]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在槐影肉鸽中，如果藏品选择了凯旋号角或者精神治疗录像带（即延长怪物被控制时间的藏品），那么在雪山上的来客这张图中，左边的怪会被无限冻住（图中画红圈的地方），MAA挂机无法识别就会卡在这里（因为干员全放在蓝门口了，打不到被冻住的怪）
![8BAU 11IUZQB7(JKKIVX)5E](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/171376629/d58313ca-2f0a-4c63-bf4e-16b1e39eaf6a)

### 有什么好的想法？

建议取消选择凯旋号角或者精神治疗录像带这俩藏品或者是避免进入雪山上的来客这张图，亦或是调整一下干员位置，不然挂机时卡在这还挺难受的......

**Comment by laowangji** [comment]
这个问题解决了吗？2025年也遇到了这个问题
