### ISSUE TITLE
肉鸽编队异常

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9243]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

不带ew，带了一堆预备干员

### Version

Resource Version: 孤星·复刻
UI Version: v5.3.2-alpha.1.d022.g23e60d386
Core Version: v5.3.2-alpha.1.d022.g23e60d386

### 日志文件

[gui.log](https://github.com/user-attachments/files/15520431/gui.log)
[asst.txt](https://github.com/user-attachments/files/15520432/asst.txt)

### 截图

https://www.bilibili.com/video/BV1fMTWegELa/
49分钟处

**Comment by Daydreamer114** [comment]
嘶 每次不小心看到maa选人的时候，生怕划了第一下不划第二下

**Comment by Lancarus** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/7be03487-e4f0-4e5f-a49a-f1ec337b0294)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/9bdd85d2-6232-42eb-8170-f71849450fb4)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34369130/86befbf5-0543-4ea2-ba35-6486e4a15f3b)
应该是出现复数个预备干员，让analyze函数提前返回，max page判定为1，没有重置到最左边，直接在第二页按照第一页的位置选干员了
