### ISSUE TITLE
孤星复刻都快结束了，内测版SSReopen的适配还没有做

### ISSUE THREAD

**Issue by pein0saga** [MaaAssistantArknights/MaaAssistantArknights#9246]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

孤星复刻都快结束了，SSReopen的适配还没有做

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/2074641/6e1accab-bbbf-4fd7-8004-5f03fff0902b)

**Comment by ABA2396** [comment]
这次的活动是有单独任务的，要按自己的顺序打，所以不做一键复刻
