### ISSUE TITLE
一键长草刷不能代理作战的关卡时出错

### ISSUE THREAD

**Issue by mimai114514** [MaaAssistantArknights/MaaAssistantArknights#9251]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动长草设置剩余理智刷经验本，但经验-5/6均无法代理作战时，MAA会在不勾选代理作战的情况下直接开始作战，第一次行动失败后回到经验本选关界面，第二次在作战失败界面卡死

### Version

Resource Version: 孤星·复刻
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15522157/asst.log)
[gui.log](https://github.com/user-attachments/files/15522159/gui.log)
两次错误发生在22:00到22:02之间

### 截图

![f1d6e7afc194c38503dcbbee3f3437a4](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115885201/e470582b-e600-4509-ba13-ba81f7464d50)
第一次作战失败后回到此界面
![0817685d2cd41656aa3b77d926580eec](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115885201/52f7a806-f32a-47ac-8990-7406387bab58)
第二次作战失败后卡在此界面
![d113cf5ab222e95511d64f2b3a375631](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115885201/1c6eaeff-a872-4fa7-a826-239baeeab4be)
![9dd46ae17ade7bc3b4335f1497d1d01e](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115885201/366da9b2-4a1a-4988-ad63-1dd85c7afd62)
作战相关设置

### 还有别的吗？

模拟器：mumu12 v3.8.22(2892)
模拟器分辨率：1280*720

**Comment by ABA2396** [comment]
这玩意只会打6/5，你要打4的话手动打一次然后选 当前/上次

**Comment by mimai114514** [comment]
我知道，但是不能代理的情况下不是应该直接跳过这个任务吗？而且代理作战失败也不算多罕见的事情，MAA遇到了不应该直接卡住吧

**Comment by mimai114514** [comment]
> 这玩意只会打6/5，你要打4的话手动打一次然后选 当前/上次

我知道，但是不能代理的情况下不是应该直接跳过这个任务吗？而且代理作战失败也不算多罕见的事情，MAA遇到了不应该直接卡住吧
