### ISSUE TITLE
基建换班相关，无人机用途和默认的宿舍换班

### ISSUE THREAD

**Issue by Kurohane0** [MaaAssistantArknights/MaaAssistantArknights#9253]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

无人机用途，我选择的是制造站-赤金，目前无人机的使用好像是和换班绑定的，希望能在不进行制造站换班的情况下让MAA自动使用无人机。
宿舍的换班，默认的换班好像是会将回复心情的干员放入，希望放入回复心情类干员时增加过滤菲亚梅塔的选项
![QQ图片20240601231201](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/96478704/fbc238d5-2c11-4a8e-b174-29ca5e42cc65)
基建工作心情阈值，没搞懂这个怎么用的，选100%和0%都会自动换班
用的是MUMU12，MAA是5.3.1，win10

**Comment by ntgmc** [comment]
> 默认的换班好像是会将回复心情的干员放入，希望放入回复心情类干员时增加过滤菲亚梅塔的选项

我这怎么不会放入回复心情的干员……可能是BUG

> 希望能在不进行制造站换班的情况下让MAA自动使用无人机。

较难实现。
