### ISSUE TITLE
建议添加连战次数智能识别功能

### ISSUE THREAD

**Issue by RunrunXi** [MaaAssistantArknights/MaaAssistantArknights#9254]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前只能手动设置连战次数，而清理体力时设置连战6次，如果体力刚好少一次就容易导致体力溢出，而如果设置1次会让刷关效率变低

### 有什么好的想法？

可以通过识别连续作战数字右上方的加号来判断需要的连战次数，添加智能判断连战次数的功能
![fight](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/111105781/e610b73f-54c9-4b0f-8b6a-b7059c3e4b09)

**Comment by status102** [comment]
与指定次数冲突，指定3x6，然后选了x5
