### ISSUE TITLE
为什么提示资源损坏？？？？

### ISSUE THREAD

**Issue by aierxiya** [MaaAssistantArknights/MaaAssistantArknights#9261]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

今天打开之后自动更新，然后就提示资源损坏，重新下载后还是这样

### Version

使用的最新内测版

### 日志文件

[asst.log](https://github.com/user-attachments/files/15524183/asst.log)
[gui.log](https://github.com/user-attachments/files/15524184/gui.log)

### 截图

![微信截图_20240602123212](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/86341129/f44066e2-cd52-4cfe-b433-aed245c1629d)

**Comment by Lancarus** [comment]
已修复，重新下载一下
