### ISSUE TITLE
肉鸽开局助战设置指定好友

### ISSUE THREAD

**Issue by EricWangxy** [MaaAssistantArknights/MaaAssistantArknights#9263]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 有什么好的想法？

不同博士的干员练度参差不齐，maa借人的时候有可能借到练度比较低的干员导致肉鸽失败，效率变低，希望可以出一个借指定博士干员的功能，这样可以保证每次借的干员练度都是比较高的。

**Comment by Manicsteiner** [comment]
游戏ID这种东西用OCR识别的正确率太低了，不太可能，但或许可以设置一个最低干员等级要求
