### ISSUE TITLE
关于暂停/继续maa任务建议

### ISSUE THREAD

**Issue by cjh200300** [MaaAssistantArknights/MaaAssistantArknights#9266]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

在使用 maa时，当前存在一些问题影响游戏体验，例如：
1.	在肉鸽模式中，即使快要漏掉干员，系统也不会将干员放置在必经之路或蓝门前。
2.	当没有先锋时，系统会等待维什戴尔冷却完毕再放置，但由于奶妈朝向不对，导致干员被磨死。
3.	系统在放置干员时与玩家操作冲突，且朝向不正确。

### 有什么好的想法？

1.暂停/继续功能
希望游戏能增加暂停/继续功能，使肉鸽玩法更加友好。例如，如果干员的位置摆放不当，导致怪物即将进入蓝门，而干员却远离蓝门。在点击暂停后，maa会暂停游戏，恢复后会检测当前游戏是否处于暂停状态。如果是，则观察干员的摆放位置等。如果不是，则先暂停游戏。
在局外也是如此，例如在肉鸽玩法中，maa会先观察当前干员、收藏品、密文板、血量和地图等，根据设定好的优先级进行选择。

2.智能化建议（小声bb）
其实maa可以更智能，不仅在肉鸽放位上，甚至在其他很多活动和基建方面也能有所作为。由于肉鸽能够重开且任务量较大，因此不奢求实现所有功能。

最后，祝各位开发团队和使用者愉快，希望maa拥有更加美好的未来。

### 其他内容

这是ai给的意见：
为了解决这些问题，提出以下优化建议：
1. 智能路径判断和干员放置
希望 maa 能够智能判断干员放置的最佳位置，特别是在关键时刻。例如：
•	在怪物即将漏掉时，优先将干员放置在必经之路或蓝门前，确保防线稳固。
•	自动检测当前战局，动态调整干员位置。
2. 动态朝向调整
在放置干员时，自动调整干员的朝向，以确保他们能最大限度地发挥作用。例如：
•	在放置维什戴尔时，自动检测奶妈的朝向，并进行调整，确保奶妈能有效治疗干员。
3. 操作协调
系统应当能够与玩家的操作进行协调，避免操作冲突。例如：
•	在玩家进行放置操作时，maa 暂停其自动放置功能，待玩家完成操作后再恢复。
•	提供一个选项，让玩家能够手动调整干员朝向。
通过这些优化，maa 将能够更好地支持玩家，提升 Roguelike 游戏的体验。
具体实现建议
1. 路径判断和干员放置
json
复制代码
{ "function": "PlaceOperator", "context": "roguelike", "position": { "x": "calculated_x", "y": "calculated_y" }, "priority": "high", "on_leak": true } 
2. 朝向调整
json
复制代码
{ "function": "AdjustOrientation", "context": "healer", "operator_id": "visdel", "direction": "auto_detect" } 
3. 操作协调
json
复制代码
{ "function": "PauseAuto", "context": "roguelike", "when_player_action": true } 
希望以上建议能帮助 maa 更加智能地进行操作，提高玩家的游戏体验。

**Comment by ntgmc** [comment]
1. MAA无法识别怪的位置，只能识别击杀数，费用等，无法判断 `怪物即将漏掉` 的情况。
2. MAA目前肉鸽策略是写死的，不能动态调整朝向，也不会根据干员部署位置而改变，如果您有更好的策略，欢迎修改 `./resource/roguelike/对应肉鸽/autopilot/地图.json` 中的策略并提交PR。
3. 我没看懂你的 `暂停/继续功能` 是啥意思

**Comment by ZauberViolino** [comment]
3. 我猜他说的是人工接管？见#9265
