### ISSUE TITLE
Copilot选人逻辑优化

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaAssistantArknights#927]
目前是无脑往右刷。

从阵容，按职介+等级顺序选择 会不会快一点。

我看好几个Issue 都和选人相关

**Comment by ABA2396** [comment]
现在有个选人问题是特别关注的人左下的黄边和名字重合了，识别不出来名字，所以带了关注的人就会选不上

**Comment by MistEO** [comment]
修了
