### ISSUE TITLE
生息演算普通模式下无法刷去点数

### ISSUE THREAD

**Issue by Fengxx9403** [MaaAssistantArknights/MaaAssistantArknights#9271]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

生息演算普通模式下第二天卡住，原来不卡的 ，看了下操作应该是第二天消磨时光之后应该再有一下点击的操作的，老版本的没有问题，麻烦牛牛尽快解决了

### Version

5.3.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15527880/asst.log)
6月3日早上9.30左右
[gui.log](https://github.com/user-attachments/files/15527881/gui.log)
6月3日早上9.30左右

**Comment by PcTuoDK** [comment]
同样的问题

**Comment by HoshinoAyako** [comment]
duplicate #9272

**Comment by kelo-kelo** [comment]
Core Version: v5.3.2-alpha.1.d033.gf89d71d5c版本也有这个问题，运行2分钟就停了

**Comment by ABA2396** [comment]
#9273 fixed
