### ISSUE TITLE
期望在【刷理智】的功能中增加对代理失败的作战的录屏功能

### ISSUE THREAD

**Issue by tiyamikatto** [MaaAssistantArknights/MaaAssistantArknights#9274]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

平时自己打的代理会出现一些在极端情况下的代理失败问题。
而哪怕是自己手动去刷理智，也有可能根本不知道问题出在了哪里，等反应过来已经是代理失败的界面了。
这时候哪怕想复现，找出问题，也因为发生的概率较小而无果。

### 有什么好的想法？

那么如果可以在【刷理智】的功能里，增加一个“对失败作战录屏”的可选项，
在用户勾选的情况下，每次代理开始后，进行录屏，若代理最终导致作战无法达成3星，则保存这句的录像并提示用户。
这样用户就可以通过录像找出翻车点。
由于是可选功能，所以不会对一些电脑性能普通的用户造成太大的负面使用体验。

**Comment by Daydreamer114** [comment]
你的逻辑好怪啊，反正都得手动，你自己点上obs，刷完看一眼maa的log决定看不看录屏不就好了

**Comment by tiyamikatto** [comment]
> 你的逻辑好怪啊，反正都得手动，你自己点上obs，刷完看一眼maa的log决定看不看录屏不就好了

我点obs，录多久？理智药all-in，自动战斗几个小时，我录个20GB的视频在电脑里面吗？

>你要的东西变成了一个自动开始、结束录屏和自动删除录屏的脚本？
这有问题吗？maa既然可以知道作战有没有失败，自然可以只保存失败的作战录像，而不保存别的。

这个想法更加像是我想了个代理，现在要检查这个代理跑起来有没有问题，但是一把把看我得烦死。
那么干脆maa代理，出现问题甚至可以自动停止来“提示用户”。用户去查看这句代理录像就行。


都用脚本了，还对别人想要一个脚本plus感到“逻辑好怪”，才是真的奇怪吧？

**Comment by Daydreamer114** [comment]
> > 你的逻辑好怪啊，反正都得手动，你自己点上obs，刷完看一眼maa的log决定看不看录屏不就好了
> 
> 我点obs，录多久？理智药all-in，自动战斗几个小时，我录个20GB的视频在电脑里面吗？
> 
> > 你要的东西变成了一个自动开始、结束录屏和自动删除录屏的脚本？
> 
> 这有问题吗？maa既然可以知道作战有没有失败，自然可以只保存失败的作战录像，而不保存别的。
> 
> 这个想法更加像是我想了个代理，现在要检查这个代理跑起来有没有问题，但是一把把看我得烦死。 那么干脆maa代理，出现问题甚至可以自动停止来“提示用户”。用户去查看这句代理录像就行。
> 
> 都用脚本了，还对别人想要一个脚本plus感到“逻辑好怪”，才是真的奇怪吧？

我每天就是录出来60多GB啊。。。不跟你争
这东西的问题在于怎么录，你能给出你的解决方案吗

**Comment by Daydreamer114** [comment]
> > 你的逻辑好怪啊，反正都得手动，你自己点上obs，刷完看一眼maa的log决定看不看录屏不就好了
> 
> 我点obs，录多久？理智药all-in，自动战斗几个小时，我录个20GB的视频在电脑里面吗？
> 
> > 你要的东西变成了一个自动开始、结束录屏和自动删除录屏的脚本？
> 
> 这有问题吗？maa既然可以知道作战有没有失败，自然可以只保存失败的作战录像，而不保存别的。
> 
> 这个想法更加像是我想了个代理，现在要检查这个代理跑起来有没有问题，但是一把把看我得烦死。 那么干脆maa代理，出现问题甚至可以自动停止来“提示用户”。用户去查看这句代理录像就行。
> 
> 都用脚本了，还对别人想要一个脚本plus感到“逻辑好怪”，才是真的奇怪吧？

我每天就是录出来60多GB啊。。。不跟你争
这东西的问题在于怎么录，你能给出你的解决方案吗

**Comment by Daydreamer114** [comment]
> > 我每天就是录出来60多GB啊。。。不跟你争 这东西的问题在于怎么录，你能给出你的解决方案吗
> 
> 我并不认为一天录60多个GB的素材是一个普通玩家会有日常。。。 如果我是一个攻略up，我录屏个几小时的素材后自查没问题， 但是我不是，我只是想有这个功能提高游戏体验和maa的使用功能。
> 
> > ### 在提问之前...
> > 
> > * [x]   我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）
> 
> 我只是期望有一个新功能而提出了建议， 我认为提出一个建议和是否有解决方案是没有直接关系的。
> 
> 既然你问了，临时可以想到的可行的方案有： 一，基础功能中增加录屏功能，独立于之前的截图。 二，多数模拟器自带录屏功能，maa如果可以获取对应模拟器的接口，可以直接调用。 三，调用window自带的屏幕录制功能（可能需要管理员权限）

真喜欢脑测。。有没有可能我问你实现方法是因为我不会
放这吧，有人觉得能写出来的话会写的，要是被管理员closed as not planned了就没办法了

**Comment by tiyamikatto** [comment]
> 真喜欢脑测。。有没有可能我问你实现方法是因为我不会 放这吧，有人觉得能写出来的话会写的，要是被管理员closed as not planned了就没办法了

我寻思我也没参与项目组，不知道内部有哪些功能，只能脑测很正常。。。
你非得问，我回答的还说别人脑测有点离谱了
本来就是一个“建议”罢了，能行与否自然看各位大佬。
你非得呛别人做什么？

**Comment by Daydreamer114** [comment]
> > 真喜欢脑测。。有没有可能我问你实现方法是因为我不会 放这吧，有人觉得能写出来的话会写的，要是被管理员closed as not planned了就没办法了
> 
> 我寻思我也没参与项目组，不知道内部有哪些功能，只能脑测很正常。。。 你非得问，我回答的还说别人脑测有点离谱了 本来就是一个“建议”罢了，能行与否自然看各位大佬。 你非得呛别人做什么？



> 我只是期望有一个新功能而提出了建议， 我认为提出一个建议和是否有解决方案是没有直接关系的。

你在脑测我言语背后的目的。你本来可以单纯的进行问题的交流。包括我在呛人也是你自己想出来的。

**Comment by Daydreamer114** [comment]
> > 真喜欢脑测。。有没有可能我问你实现方法是因为我不会 放这吧，有人觉得能写出来的话会写的，要是被管理员closed as not planned了就没办法了
> 
> 我寻思我也没参与项目组，不知道内部有哪些功能，只能脑测很正常。。。 你非得问，我回答了想法还说我脑测有点离谱了 本来就是一个“建议”罢了，能行与否自然看各位大佬。 你非得呛别人做什么？

解决方案的话是这样的，
1-写基础功能很费时费力，这个方面他们基本上不会管。
2-要对所有有内置录屏功能的模拟器挨个写一遍。
3-自带的录屏工具要选位置什么的，而且选的是显示器录制，看上去是比obs还麻烦的。

**Comment by tiyamikatto** [comment]
> > 我只是期望有一个新功能而提出了建议， 我认为提出一个建议和是否有解决方案是没有直接关系的。
> 
> 我对你这句话感到有些不适。

？？这句话有什么问题吗？

我提出的不是建议吗？提建议必须要附带解决方案吗？



> 你的逻辑好怪啊，反正都得手动，你自己点上obs，刷完看一眼maa的log决定看不看录屏不就好了 你要的东西变成了一个自动开始、结束录屏和自动删除录屏的脚本？

你在别人提建议的时候，开局一句“你的逻辑好奇怪啊”，然后问一个给脚本建议的人“你的要是不是一个脚本”？

> 这东西的问题在于怎么录，你能给出你的解决方案吗

然后是你先问的我“解决方案”
我给出大概的思路，你直接反手一句

> 真喜欢脑测

合理吗？？

> 有没有可能我问你实现方法是因为我不会 

我真的不知道你到底在这里想表达什么？

**Comment by Daydreamer114** [comment]
> > > 我只是期望有一个新功能而提出了建议， 我认为提出一个建议和是否有解决方案是没有直接关系的。
> > 
> > 
> > 我对你这句话感到有些不适。
> 
> ？？这句话有什么问题吗？
> 
> 我提出的不是建议吗？提建议必须要附带解决方案吗？
> 
> > 你的逻辑好怪啊，反正都得手动，你自己点上obs，刷完看一眼maa的log决定看不看录屏不就好了 你要的东西变成了一个自动开始、结束录屏和自动删除录屏的脚本？
> 
> 你在别人提建议的时候，开局一句“你的逻辑好奇怪啊”，然后问一个给脚本建议的人“你的要是不是一个脚本”？
> 
> > 这东西的问题在于怎么录，你能给出你的解决方案吗
> 
> 然后是你先问的我“解决方案” 我给出大概的思路，你直接反手一句
> 
> > 真喜欢脑测
> 
> 合理吗？？
> 
> > 有没有可能我问你实现方法是因为我不会
> 
> 我真的不知道你到底在这里想表达什么？

我想表达的是你可以就事论事。
我为最开始的发言致歉。我的意思大概是，这个功能rarely会被用到，想让人写并把它加给所有用户有些怪。
（我明白你的意思，这句话你不用反驳，我们不需要相互说服。）
再吵就不是close的问题了，是被删整个enhancement，所以好好放这吧。

**Comment by tiyamikatto** [comment]
> 我想表达的是你可以就事论事。 我为最开始的发言致歉。我的意思大概是，这个功能rarely会被用到，想让人写并把它加给所有用户有些怪。 （我明白你的意思，这句话你不用反驳，我们不需要相互说服。） 再吵就不是close的问题了，是被删整个enhancement，所以好好放这吧。

嗯，我也语言过于冲了，抱歉

**Comment by Daydreamer114** [comment]
> 一，基础功能中增加录屏功能，独立于之前的截图。
> 二，多数模拟器自带录屏功能，maa如果可以获取对应模拟器的接口，可以直接调用。
> 三，调用window自带的屏幕录制功能（可能需要管理员权限）

你可以把这个直接加到“有什么好的想法？”里，免得他们看咱俩吵架。

**Comment by Daydreamer114** [comment]
方舟关卡不是0，2，3嘛（
以及，有可能会搞一个截屏，零点几秒截一次，这样不用解决录屏的问题了，你也有的看了

**Comment by ABA2396** [comment]
![fde65c5d6587a378ffbb0e797e7e670b](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/195f6aa2-2bfd-497f-958b-c8ff1ef9f0d7)
感觉这样都能跑了（）

**Comment by Saratoga-Official** [comment]
下面的讨论太长不看，我就只说个人的看法
如果要实现的话，maa必须在刷理智的时候时刻保持录屏，因为不知道哪一次会失败，这样就会产生更多的占用，然后录屏完的文件让maa也占更大空间，我觉得不现实

**Comment by tiyamikatto** [comment]
> 下面的讨论太长不看，我就只说个人的看法 如果要实现的话，maa必须在刷理智的时候时刻保持录屏，因为不知道哪一次会失败，这样就会产生更多的占用，然后录屏完的文件让maa也占更大空间，我觉得不现实

录屏确实会导致资源占用，所以这个功能充其量是可选项而非默认项。

存储导致的空间占用问题：这个并不要求从头录到尾，只需要每局录屏，如果正常结束，这次录屏就删除了，最终只有出现问题的那局录像被保留，用这个功能的玩家目的就是得到这个录像，因此这点硬盘空间还是有的。

**Comment by Saratoga-Official** [comment]
我还是觉得没做的必要，需要这功能的人太少了，挂机就不能用个能稳定挂机的作业吗

**Comment by tiyamikatto** [comment]
> 我还是觉得没做的必要，需要这功能的人太少了，挂机就不能用个能稳定挂机的作业吗

嘛啊...真要这么说也没办法
主要就是越是稳定的作业，平时挂机出现代理失误的概率越低。但是要是恰好就是因为练度/平替等导致很偶然的失误，但偏偏给注意到了，结果自己刷就是复现不了，还是挺烦的。

**Comment by Saratoga-Official** [comment]
而且现在有了ew之类的干员翻车率几乎没有，MAA目前有一堆ToDo都比这优先，先关了
