### ISSUE TITLE
MAA自动肉鸽，电脑蓝屏死机

### ISSUE THREAD

**Issue by WoolBallLi** [MaaAssistantArknights/MaaAssistantArknights#9277]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA自动肉鸽，cpu占用率极高，电脑蓝屏死机，重复出现三次，其中两次在砍诺特死机。蓝屏的时候开启软件额为MAA，mumu，obs，tim，steam，火绒，bing壁纸。r23，3dmark，ad64烤机可稳定通过。重新下载MAA，关闭mumu增强截图，cpu占用率下降。
显卡：6800xt，主板：华硕b550m-plus，cpu：5900x

### Version

Resource Version: 孤星·复刻
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[debug.zip](https://github.com/user-attachments/files/15542390/debug.zip)
蓝屏死机时间为2024年6月4日，10点15分，10点24分，11点20分

**Comment by WoolBallLi** [comment]
https://b23.tv/V1RGqEv

**Comment by WoolBallLi** [comment]
> https://b23.tv/V1RGqEv

第三次从开始到死机的录像

**Comment by ABA2396** [comment]
视频放完也没看到蓝屏，看cpu占用也就60上下啊，蓝屏问题不如直接找售后

**Comment by WoolBallLi** [comment]
> 视频放完也没看到蓝屏，看cpu占用也就60上下啊，蓝屏问题不如直接找售后

蓝屏死机了，录屏就结束了呗。那可是5900x的60%啊！12个核心MAA占用7个半？我的电脑只有maa会蓝屏死机。其他r23，3dmark，ad64烤机都不会。打2042，怪物猎人之类的单机也不会蓝屏死机。梁星逢远程我的说MAA有大量无用数据识别，猜测是cpu性能过剩导致全部逻辑单元给MAA会让CPU吃满。

**Comment by WoolBallLi** [comment]
![H@GQM3C~1Q9_C(}Y7S6(1BQ](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35244773/ecdeaf8f-c222-498f-820c-c8b3ad3d9e13)
今天还碰见群友i7-12650 雷电模拟器 MAA 70%占用率的

**Comment by ABA2396** [comment]
就算你CPU一直占着90%，出现蓝屏也是电脑的问题，哪有占用一上去就蓝屏的道理

**Comment by Cryolitia** [comment]
你蓝屏的错误代码呢，蓝屏页面微软让你拍下来发给社区的那个二维码呢？

很抱歉让您失望了，开发者不是萨米人，不会通过烧龟甲来修bug。

**Comment by ABA2396** [comment]
5900怎么了，制程差两代也不是旗舰，轻薄本7840U跑在30W的性能都比5900的45W高
蓝屏错误代码呢，核心转储呢，开发者不是靠烧龟甲和跳大神来修bug的，就算开发者是萨米人也不行

**Comment by ABA2396** [comment]
CPU的占用本来就是截图越快，用的越多，要是用不上这么快的响应速度，那就把截图增强关掉呗

**Comment by Daydreamer114** [comment]
AMDYES了属于是，i712700打肉鸽能占到100%也没见过蓝屏啊

**Comment by WoolBallLi** [comment]
> CPU的占用本来就是截图越快，用的越多，要是用不上这么快的响应速度，那就把截图增强关掉呗

那麻烦你把问题关掉吧，没钱换电脑

**Comment by WoolBallLi** [comment]
> 你蓝屏的错误代码呢，蓝屏页面微软让你拍下来发给社区的那个二维码呢？
> 
> 微软官方的指南：https://learn.microsoft.com/zh-cn/troubleshoot/windows-client/performance/generate-a-kernel-or-complete-crash-dump

蓝屏瞬间就重启了。没钱换电脑，关掉这个问题吧

**Comment by Daydreamer114** [comment]
> > CPU的占用本来就是截图越快，用的越多，要是用不上这么快的响应速度，那就把截图增强关掉呗
> 
> 那麻烦你把问题关掉吧，没钱换电脑

你自己也能关）

**Comment by Cryolitia** [comment]
什么叫蓝屏瞬间就自动重启了，到底有没有蓝屏页面，是操作系统蓝屏还是EC/晶闸管切电。描述不清楚就用手机录完整过程视频。

提示：只有屏幕变成蓝色才叫蓝屏，这是一个望文生义的词汇。

**Comment by WoolBallLi** [comment]
> 什么叫蓝屏瞬间就自动重启了，到底有没有蓝屏页面，是操作系统蓝屏还是EC/晶闸管切电。描述不清楚就用手机录完整过程视频。
> 
> 提示：只有屏幕变成蓝色才叫蓝屏，这是一个望文生义的词汇。

![QQ图片20240604185541](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35244773/c416d821-2c2b-47d1-b368-a63afdf40493)

**Comment by Daydreamer114** [comment]
图不是很高清，给一下你的那个终止代码
C:\Windows\Minidump里应该有崩溃文件，可以找找；.dmp也是
“打开事件查看器（Event Viewer），可以帮助你找到有关蓝屏错误的进一步信息。打开事件查看器，导航到“Windows日志” > “System”，查找有关错误的条目。”

**Comment by WoolBallLi** [comment]
> 图不是很高清，给一下你的那个终止代码 C:\Windows\Minidump里应该有崩溃文件，可以找找；.dmp也是 “打开事件查看器（Event Viewer），可以帮助你找到有关蓝屏错误的进一步信息。打开事件查看器，导航到“Windows日志” > “System”，查找有关错误的条目。”

[060424-5390-01.zip](https://github.com/user-attachments/files/15550431/060424-5390-01.zip)

**Comment by Daydreamer114** [comment]
> > 图不是很高清，给一下你的那个终止代码 C:\Windows\Minidump里应该有崩溃文件，可以找找；.dmp也是 “打开事件查看器（Event Viewer），可以帮助你找到有关蓝屏错误的进一步信息。打开事件查看器，导航到“Windows日志” > “System”，查找有关错误的条目。”
> 
> [060424-5390-01.zip](https://github.com/user-attachments/files/15550431/060424-5390-01.zip)

![8D3679048804E44B27336440D418729C](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/b91156c2-8059-4715-a354-d49cae969ddd)
这个位置有个“终止代码：”，你的图片不是很高清，看不清，你在你那认一下然后发一下文本

**Comment by Cryolitia** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/23723294/8b0337f8-a20f-4acb-9f5a-79f5ecc6f4ae)
这是你故意拍不清的还是没渲染清楚

**Comment by WoolBallLi** [comment]
> > > 图不是很高清，给一下你的那个终止代码 C:\Windows\Minidump里应该有崩溃文件，可以找找；.dmp也是 “打开事件查看器（Event Viewer），可以帮助你找到有关蓝屏错误的进一步信息。打开事件查看器，导航到“Windows日志” > “System”，查找有关错误的条目。”
> > 
> > 
> > [060424-5390-01.zip](https://github.com/user-attachments/files/15550431/060424-5390-01.zip)
> 
> ![8D3679048804E44B27336440D418729C](https://private-user-images.githubusercontent.com/74444214/336424519-b91156c2-8059-4715-a354-d49cae969ddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTk3MDEsIm5iZiI6MTcxNzQ5OTQwMSwicGF0aCI6Ii83NDQ0NDIxNC8zMzY0MjQ1MTktYjkxMTU2YzItODA1OS00NzE1LWEzNTQtZDQ5Y2FlOTY5ZGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDExMTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNDJhNWIzN2ZmY2U3YmUzNGExZTJiNTM4NTkxNGRjNzg5ODFiZjRhNTQxYTFiOTI3N2IzYjI0ODMwNWI1ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7AdKN4YcKfqzHZBNAH0jTdUBbRaDAH6UqcchPZzceQE) 这个位置有个“终止代码：”，你的图片不是很高清，看不清，你在你那认一下然后发一下文本

当时只用手机qq拍了这一张照片，没有更多的图片了

**Comment by WoolBallLi** [comment]
> <img alt="截屏2024-06-04 19 12 27" width="807" src="https://private-user-images.githubusercontent.com/74444214/336425379-e7f746f7-4b4c-4b4c-8b43-c5efeb90bf58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDAzMjMsIm5iZiI6MTcxNzUwMDAyMywicGF0aCI6Ii83NDQ0NDIxNC8zMzY0MjUzNzktZTdmNzQ2ZjctNGI0Yy00YjRjLThiNDMtYzVlZmViOTBiZjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDExMjAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNjg1YzJkYTdkNWEwY2RkYzgyZTdiZDEzZTVhYTBjNTM1ODEyZGZmZjlhM2RmMTgwYjZlMTZlODhjYWI2NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LqZ07NsFfs2wWhCgP6t3HPwxJsfnEgyw9MPd49fXIZk"> 可能是“WHEA_UNCORRECTABLE_ERROR” 基本上是你的硬件炸了

应该是了吧，把mumu增强截图关掉，打了一把萨米肉鸽，正常了。重启再打一把，又不行了。给cpu加电压，打了一把又行了。

**Comment by WoolBallLi** [comment]
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:21:32
我现在开MAA截图增强
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:21:47
你看CPU还在上去不
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:22:22
重新开一局肉鸽

【潜水】诗(woolball)(879076299) 13:23:37
60%了
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:24:02
?
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:24:11
你的U怎么回事
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:25:25
不对
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:25:32
你MAA有大量无用数据识别 
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:29:03
怪事
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:29:17
需要限制在4个逻辑处理器才※
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:29:57现在不会了
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:30:02甚至都不会超过50%
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:02
我还是第一次见CPU性能太好
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:07MAA吃满了的情况

【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:28全部逻辑单元给MAA会让你CPU吃满
--
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:37现在给了MAA4个
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:44正常了

【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:02本来截图增强模式是减压的
--
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:10大部分截图识别的工作直接交给模拟器了
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:19现在倒好了
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:37性能太好了。反而MAA工作效率过高了
【潜水】分逼不氪，服务器蛀虫，主打一个陪伴(2286406155) 13:33:44他这个算个例吧
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:53我反正第一次见

【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:34:10我就说为啥会供电导致蓝屏
--
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:34:32我还以为你CPU太差了

**Comment by WoolBallLi** [comment]
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:21:32
我现在开MAA截图增强
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:21:47
你看CPU还在上去不
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:22:22
重新开一局肉鸽

【潜水】诗(woolball)(879076299) 13:23:37
60%了
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:24:02
?
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:24:11
你的U怎么回事
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:25:25
不对
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:25:32
你MAA有大量无用数据识别
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:29:03
怪事
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:29:17
需要限制在4个逻辑处理器才※
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:29:57现在不会了
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:30:02甚至都不会超过50%
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:02
我还是第一次见CPU性能太好
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:07MAA吃满了的情况
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:28全部逻辑单元给MAA会让你CPU吃满

【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:37现在给了MAA4个
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:44正常了
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:02本来截图增强模式是减压的

【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:10大部分截图识别的工作直接交给模拟器了
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:19现在倒好了
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:37性能太好了。反而MAA工作效率过高了
【潜水】分逼不氪，服务器蛀虫，主打一个陪伴(2286406155) 13:33:44他这个算个例吧
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:53我反正第一次见
【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:34:10我就说为啥会供电导致蓝屏

【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:34:32我还以为你CPU太差了

**Comment by Daydreamer114** [comment]
> 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:21:32 我现在开MAA截图增强 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:21:47 你看CPU还在上去不 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:22:22 重新开一局肉鸽
> 
> 【潜水】诗(woolball)(879076299) 13:23:37 60%了 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:24:02 ? 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:24:11 你的U怎么回事 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:25:25 不对 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:25:32 你MAA有大量无用数据识别 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:29:03 怪事 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:29:17 需要限制在4个逻辑处理器才※ 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:29:57现在不会了 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:30:02甚至都不会超过50% 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:02 我还是第一次见CPU性能太好 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:07MAA吃满了的情况 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:28全部逻辑单元给MAA会让你CPU吃满
> 
> 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:37现在给了MAA4个 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:31:44正常了 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:02本来截图增强模式是减压的
> 
> 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:10大部分截图识别的工作直接交给模拟器了 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:19现在倒好了 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:37性能太好了。反而MAA工作效率过高了 【潜水】分逼不氪，服务器蛀虫，主打一个陪伴(2286406155) 13:33:44他这个算个例吧 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:33:53我反正第一次见 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:34:10我就说为啥会供电导致蓝屏
> 
> 【管理员】梁星逢（有事@我，远程私聊我(794023437) 13:34:32我还以为你CPU太差了

哎，有盒你是真开啊

**Comment by WoolBallLi** [comment]
> 哎，有盒你是真开啊

不懂，删除了
