### ISSUE TITLE
maa启动异常

### ISSUE THREAD

**Issue by Schwarzwald3** [MaaAssistantArknights/MaaAssistantArknights#9279]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在某次电脑蓝屏死机后，再启动maa只会显示一个空白界面，数秒后自动关闭，下载新版本maa运行也是同一情况

### Version

v5.3.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/15542869/gui.log)
[asst.log](https://github.com/user-attachments/files/15542870/asst.log)

### 截图

![屏幕截图 2024-06-04 131336](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/171652435/11ff8711-888e-4cff-8404-926bd7813a54)

**Comment by ABA2396** [comment]
看日志倒是没啥问题，没见过这种情况，试试看重装下运行库？
https://maa.plus/docs/用户手册/常见问题.html#可能性-2-运行库问题

**Comment by Schwarzwald3** [comment]
重装运行库后还是不行 :(

**Comment by wlwxj** [comment]
网络问题maybe，或者换稳定版试试

**Comment by Schwarzwald3** [comment]
此问题突然又在某次重启后好了，只能说很奇怪
