### ISSUE TITLE
生路关卡高台识别偏移

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9286]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

地图站里写的地面，然后maa识别点位为地面
当ew放在3,4朝右时，自动战斗概率不开技能

### Version

Resource Version: 生路
UI Version: v5.3.2-alpha.1.d049.g8cc7fe3e3
Core Version: v5.3.2-alpha.1.d049.g8cc7fe3e3

### 日志文件

[gui(2).log](https://github.com/user-attachments/files/15583657/gui.2.log)
[asst(2).log](https://github.com/user-attachments/files/15583663/asst.2.log)
时间为gui中最后一次自动战斗

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/c41e066c-aa35-480c-9417-7d580a0ce7ef)

**Comment by ABA2396** [comment]
草 按道理来说这玩意确实是地面）

**Comment by Daydreamer114** [comment]
像这关比较典型，怪物没有可能来拆3,4 4,4 5,4之类的，可以考虑直接在作业站里标成高台
