### ISSUE TITLE
bp-6 UnknownStage，放弃上传企鹅物流

### ISSUE THREAD

**Issue by LiGithubYu** [MaaAssistantArknights/MaaAssistantArknights#9288]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

bp-6 UnknownStage，放弃上传企鹅物流

### Version

Resource Version: 孤星·复刻
UI Version: v5.3.2-alpha.1.d049.g8cc7fe3e3
Core Version: v5.3.2-alpha.1.d049.g8cc7fe3e3

### 日志文件

[asst.log](https://github.com/user-attachments/files/15588617/asst.log)
[gui.log](https://github.com/user-attachments/files/15588625/gui.log)

### 截图

![Snipaste_2024-06-05_21-48-22](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/48920551/156d95e2-1765-4bdf-891f-77317d63c920)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/541e9add-b530-41a3-ac3f-98bd3604d686)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/0cd4e7ed-a8e8-4982-b5fb-b32b35dc0ef2)
点检查更新看看有没有更新资源，没有的话试试关了maa之后把cache/etag.json删了重新开一遍
