### ISSUE TITLE
肉鸽第一层刷金酒之杯

### ISSUE THREAD

**Issue by rfzmiaoling** [MaaAssistantArknights/MaaAssistantArknights#929]
肉鸽第一层难度较低，即便是灾厄应该也能打过。
想法有两种，一种是用脚本本身硬刷，通过概率堆上去，
另一种是考虑到肉鸽第一层阵容是固定的，可以提供一个面向肉鸽的框架，让玩家自己输入第一层的所有作业供肉鸽识别

**Comment by WWPXX233** [comment]
目前以刷取等级为主 未来可能会做
