### ISSUE TITLE
生息演算 通过制造刷点数失败

### ISSUE THREAD

**Issue by Yuke-Hu** [MaaAssistantArknights/MaaAssistantArknights#9295]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

生息演算新功能，通过制造刷点数失败。
具体出错环节是在回档时，停留在回档界面，未能选择左边那个天数回档。
<img width="557" alt="9b9bd7659a6fb099dc5abba0bb4bbaf3" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161836703/db8b6007-a1b2-49cb-812d-6bb51eda2c07">
gui.log未有有效信息
asst.log说明在选择读档按钮的下一步出错，然后重试了20次（）
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161836703/16cf9c48-22ef-457a-b980-456eadfe7792)

### Version

Resource Version: 生路
UI Version: v5.3.2-alpha.1.d049.g8cc7fe3e3
Core Version: v5.3.2-alpha.1.d049.g8cc7fe3e3

### 日志文件

[gui.log](https://github.com/user-attachments/files/15614563/gui.log)
[asst.log](https://github.com/user-attachments/files/15614565/asst.log)

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161836703/8ec9627f-583e-4011-be47-ac3ec09e2d87)

**Comment by ABA2396** [comment]
点了读取存档之后应该有两个确认弹窗，在读存档的地方原来是不能返回的，看样子是这几天yj又更新了下把这个弹窗去掉了
把resource/tasks.json里 `"Reclamation2ExReadArchiveEnter": ` 任务的sub里第一行的 ` "Reclamation2ExReadArchiveConfirm*2", `删掉试试
