### ISSUE TITLE
自动添加高星低信赖干员

### ISSUE THREAD

**Issue by IDA2099** [MaaAssistantArknights/MaaAssistantArknights#9296]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前自动添加低信赖干员不是根据星数高低来补充，而是根据信赖值进行补充，优先让信赖值为0的干员上场，有些六星干员信赖值没满的情况下并不会被选上。但是一般情况下六星干员的信赖刷取是最优先的，请开发组添加六星干员优先/按照稀有度进行添加的筛选机制。

**Comment by ntgmc** [comment]
楚你说的是宿舍的 `蹭信赖` 还是自动战斗的 `补充低信赖干员` ？
如果是自动战斗的，可以使用 `追加自定干员` 功能。

**Comment by status102** [comment]
如上所述

**Comment by IDA2099** [comment]
抱歉没说清楚，我是指自动战斗的干员是填充信赖最低而不是按照星级高低排。感谢您指出自定干员，但我遇到的问题是我需要刷信赖的六星干员太多了，有十几个，我不知道如果都自定会不会影响到抄作业，我这就去试试，感谢🥹
