### ISSUE TITLE
自动肉鸽中，技能机制为子弹的干员会自动关闭技能

### ISSUE THREAD

**Issue by AbidingLuv** [MaaAssistantArknights/MaaAssistantArknights#9297]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

肉鸽作战时，类似如维什戴尔三技能等技能为子弹机制的干员，常出现自动发动技能后马上自动关闭的情况。

### Version

Core Version: v5.3.1
Resource Version: 生路
UI Version: v5.3.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/15621493/gui.log)
[asst.log](https://github.com/user-attachments/files/15621593/asst.log)
最近一次自动肉鸽中，基本每一关都存在。

**Comment by ABA2396** [comment]
开了截图加速之后两次判断间隔时间太短了，开了技能之后的过度动画又识别到了技能好了又点了一次
67cb180ba8f624217a5575f258eda3e424756c84 加了点重复开技能的间隔，秒关是没了，但是测了下有些时候和部分背景重叠的时候还是会识别错关掉（比如黄色的自爆虫或者部分技能特效）
