### ISSUE TITLE
避免关掉{专注失调}角色的技能

### ISSUE THREAD

**Issue by C1rno9** [MaaAssistantArknights/MaaAssistantArknights#9298]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

由于专注失调会自动开技能，不过子弹类型技能的干员会被MAA开技能的动作导致技能立刻关掉

### 有什么好的想法？

检测到干员被专注失调影响后不去主动开该干员的技能

p.s. 我不知道这能否简单实现，不过还是先感谢MAA的各位开发者。

**Comment by Daydreamer114** [comment]
有log吗？maa不主动关子弹技能，可能是技能就绪的识别错误

**Comment by SherkeyXD** [comment]
是不是开mumu极速模式了）

**Comment by C1rno9** [comment]
那麽应该是mumu极速模式造成的问题，log的话我看看能不能复现看看

**Comment by ABA2396** [comment]
主要是部分干员的技能开启后会有一段过度动画，那个动画期间头顶还是有技能图标的。如果响应速度足够快的话是一定会识别到的，开了mumu截图加速只是增加了概率

**Comment by C1rno9** [comment]
所以就只能把mumu截图加速关掉了嗎？

**Comment by ABA2396** [comment]
没啥好办法，这个就算关了截图加速一样会遇到

**Comment by Lancarus** [comment]
专注失调会在技能好了那一帧出现技能ready标，会被maa抓到，非弹药类技能开一下也没啥，弹药类会出现秒开秒关
