### ISSUE TITLE
基建宿舍犯浑，一直在往右滑动不知道找谁

### ISSUE THREAD

**Issue by Chenyinlin-Yiking** [MaaAssistantArknights/MaaAssistantArknights#9299]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我自定义的基建是自动补全空位，加上maa的蹭信赖，具体排班代码放在下面：
`{
  "author": "Studyofslag",
  "description": "243中等龙门币经验书",
  "id": 1713367846832518,
  "title": "243中等",
  "buildingType": 243,
  "planTimes": "3班",
  "plans": [
    {
      "name": "A+B组",
      "description": "描述1",
      "Fiammetta": {
        "enable": false,
        "target": "",
        "order": "pre"
      },
      "drones": {
        "room": "manufacture",
        "index": 1,
        "enable": true,
        "order": "pre"
      },
      "rooms": {
        "trading": [
          {
            "skip": false,
            "product": "LMD",
            "operators": [
              "空弦",
              "伺夜",
              "但书"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": false,
            "product": "LMD",
            "operators": [
              "巫恋",
              "柏喙",
              "龙舌兰"
            ],
            "sort": false,
            "autofill": false
          }
        ],
        "manufacture": [
          {
            "skip": false,
            "product": "Pure Gold",
            "operators": [
              "清流",
              "温蒂",
              "森蚺"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": false,
            "product": "Pure Gold",
            "operators": [
              "苍苔",
              "砾",
              "斑点"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": false,
            "product": "Battle Record",
            "operators": [
              "红云",
              "稀音",
              "刻俄柏"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": false,
            "product": "Battle Record",
            "operators": [
              "至简",
              "槐琥",
              "断罪者"
            ],
            "sort": false,
            "autofill": false
          }
        ],
        "power": [
          {
            "skip": false,
            "operators": [
              "格雷伊"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": false,
            "operators": [
              "布丁"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": false,
            "operators": [
              "伊芙利特"
            ],
            "sort": false,
            "autofill": false
          }
        ],
        "dormitory": [
          {
            "skip": false,
            "operators": [
              "凛冬"
            ],
            "sort": true,
            "autofill": true
          },
          {
            "skip": false,
            "operators": [
              "推进之王"
            ],
            "sort": true,
            "autofill": true
          },
          {
            "skip": false,
            "operators": [
              "夜莺"
            ],
            "sort": true,
            "autofill": true
          },
          {
            "skip": false,
            "operators": [
              "流明"
            ],
            "sort": true,
            "autofill": true
          }
        ],
        "control": [
          {
            "skip": false,
            "operators": [
              "战车",
              "闪击",
              "霜华",
              "灰烬",
              "凯尔希"
            ],
            "sort": false,
            "autofill": false
          }
        ],
        "meeting": [
          {
            "skip": false,
            "operators": [
              "陈",
              "守林人"
            ],
            "sort": false,
            "autofill": false
          }
        ],
        "hire": [
          {
            "skip": false,
            "operators": [
              "普罗旺斯"
            ],
            "sort": false,
            "autofill": false
          }
        ],
        "processing": [
          {
            "skip": false,
            "operators": [],
            "sort": false,
            "autofill": false
          }
        ]
      },
      "period": [
        [
          "19:00",
          "23:59"
        ],
        [
          "00:00",
          "06:59"
        ]
      ]
    },
    {
      "name": "B+C 组",
      "description": "描述2",
      "Fiammetta": {
        "enable": false,
        "target": "",
        "order": "pre"
      },
      "drones": {
        "room": "manufacture",
        "index": 2,
        "enable": true,
        "order": "pre"
      },
      "rooms": {
        "trading": [
          {
            "skip": false,
            "product": "LMD",
            "operators": [
              "巫恋",
              "龙舌兰",
              "柏喙"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": false,
            "product": "LMD",
            "operators": [
              "德克萨斯",
              "能天使",
              "拉普兰德"
            ],
            "sort": false,
            "autofill": false
          }
        ],
        "manufacture": [
          {
            "skip": false,
            "product": "Pure Gold",
            "operators": [
              "苍苔",
              "砾",
              "斑点"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": false,
            "product": "Pure Gold",
            "operators": [
              "泡泡",
              "火神",
              "贝娜"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": false,
            "product": "Battle Record",
            "operators": [
              "至简",
              "槐琥",
              "断罪者"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": false,
            "product": "Battle Record",
            "operators": [
              "食铁兽",
              "红豆",
              "霜叶"
            ],
            "sort": false,
            "autofill": false
          }
        ],
        "power": [
          {
            "skip": false,
            "operators": [
              "格劳克斯"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": false,
            "operators": [
              "煌"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": false,
            "operators": [
              "雷蛇"
            ],
            "sort": false,
            "autofill": false
          }
        ],
        "dormitory": [
          {
            "skip": false,
            "operators": [
              "凛冬"
            ],
            "sort": true,
            "autofill": true
          },
          {
            "skip": false,
            "operators": [
              "推进之王"
            ],
            "sort": true,
            "autofill": true
          },
          {
            "skip": false,
            "operators": [
              "夜莺"
            ],
            "sort": true,
            "autofill": true
          },
          {
            "skip": false,
            "operators": [
              "流明"
            ],
            "sort": true,
            "autofill": true
          }
        ],
        "control": [
          {
            "skip": true,
            "operators": [],
            "sort": false,
            "autofill": false
          }
        ],
        "meeting": [
          {
            "skip": false,
            "operators": [
              "远山",
              "断崖"
            ],
            "sort": false,
            "autofill": false
          }
        ],
        "hire": [
          {
            "skip": false,
            "operators": [
              "伊桑"
            ],
            "sort": false,
            "autofill": false
          }
        ],
        "processing": [
          {
            "skip": false,
            "operators": [],
            "sort": false,
            "autofill": false
          }
        ]
      },
      "period": [
        [
          "07:00",
          "12:59"
        ]
      ]
    },
    {
      "name": "A+C组",
      "description": "描述3",
      "Fiammetta": {
        "enable": false,
        "target": "",
        "order": "pre"
      },
      "drones": {
        "room": "manufacture",
        "index": 3,
        "enable": true,
        "order": "pre"
      },
      "rooms": {
        "trading": [
          {
            "skip": false,
            "product": "LMD",
            "operators": [
              "空弦",
              "伺夜",
              "但书"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": true,
            "product": "LMD",
            "operators": [],
            "sort": false,
            "autofill": false
          }
        ],
        "manufacture": [
          {
            "skip": false,
            "product": "Pure Gold",
            "operators": [
              "清流",
              "温蒂",
              "森蚺"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": true,
            "product": "Battle Record",
            "operators": [],
            "sort": false,
            "autofill": false
          },
          {
            "skip": false,
            "product": "Battle Record",
            "operators": [
              "红云",
              "稀音",
              "刻俄柏"
            ],
            "sort": false,
            "autofill": false
          },
          {
            "skip": true,
            "product": "Battle Record",
            "operators": [],
            "sort": false,
            "autofill": false
          }
        ],
        "power": [
          {
            "skip": true,
            "operators": [],
            "sort": false,
            "autofill": false
          },
          {
            "skip": true,
            "operators": [],
            "sort": false,
            "autofill": false
          },
          {
            "skip": true,
            "operators": [],
            "sort": false,
            "autofill": false
          }
        ],
        "dormitory": [
          {
            "skip": false,
            "operators": [
              "凛冬"
            ],
            "sort": true,
            "autofill": true
          },
          {
            "skip": false,
            "operators": [
              "推进之王"
            ],
            "sort": true,
            "autofill": true
          },
          {
            "skip": false,
            "operators": [
              "夜莺"
            ],
            "sort": true,
            "autofill": true
          },
          {
            "skip": false,
            "operators": [
              "流明"
            ],
            "sort": true,
            "autofill": true
          }
        ],
        "control": [
          {
            "skip": true,
            "operators": [],
            "sort": false,
            "autofill": false
          }
        ],
        "meeting": [
          {
            "skip": true,
            "operators": [],
            "sort": false,
            "autofill": false
          }
        ],
        "hire": [
          {
            "skip": false,
            "operators": [
              "伊桑"
            ],
            "sort": false,
            "autofill": false
          }
        ],
        "processing": [
          {
            "skip": false,
            "operators": [],
            "sort": false,
            "autofill": false
          }
        ]
      },
      "period": [
        [
          "13:00",
          "18:59"
        ]
      ]
    }
  ],
  "scheduleType": {
    "planTimes": 3,
    "trading": 2,
    "manufacture": 4,
    "power": 3,
    "dormitory": 4
  }
}`

### Version

Core Version: v5.3.1

### 日志文件

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75869957/c6df02f5-e34b-42c9-85bc-76e9ef1fd091)
卡在这张图动不了，基建干员列表一直到最右边全部都是一星车子，还在往右滑动不知道找谁

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/4fa36c48-f239-4079-9134-92be84905d9d)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/bc77ae1d-0f0f-4116-863c-16e218671356)

**Comment by Chenyinlin-Yiking** [comment]
[gui.log](https://github.com/user-attachments/files/15687791/gui.log)

**Comment by Chenyinlin-Yiking** [comment]
[asst.log](https://github.com/user-attachments/files/15687793/asst.log)

**Comment by Chenyinlin-Yiking** [comment]
这个是我按照图片里勾选了补满空位，但还是有这个bug。一直在这里往右滑动
[(宿舍调整版)_243中等龙门币经验书_1698972219281262.json](https://github.com/user-attachments/files/15747427/_243._1698972219281262.json)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75869957/2861433c-def3-4c44-830c-e8c32afcdb90)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/6103d5c5-8ad6-416a-a858-fb79172b746b)

**Comment by Chenyinlin-Yiking** [comment]
意思是我宿舍如果要勾选maa的自动蹭信赖，就不应该入住任何指定干员，全部放空是吗

**Comment by ABA2396** [comment]
如果前面的宿舍勾了自动，后面再指定人就可能会出问题。把所有要指定的人都往前放完再开自动

**Comment by Chenyinlin-Yiking** [comment]
不好意思我还是不太明白，我希望每个宿舍都留下第一个位置放一个宿舍加速心情回复的干员，剩余位置补充心情未满干员（最好优先），然后还有余量蹭信赖，想请教一下应该如何设置这个排班

**Comment by ABA2396** [comment]
那没办法，每个宿舍都要指定的话就得把每个人都写死，除了最后一个宿舍能开自动其他都不能开
