### ISSUE TITLE
合成玉的制造站有时不会选择25效率的基建技能

### ISSUE THREAD

**Issue by Monoclinic** [MaaAssistantArknights/MaaAssistantArknights#930]
如题。
似乎搓玉的制造站经常会被空着，有的时候明明有干员可以用（一般是那种25加成的通用干员），但是maa会直接不选然后把制造站空着。
asst.log传不上来（可能因为太大了）…就不传了

**Comment by MistEO** [comment]
压个压缩包，没有日志这 bug 报了等于没报
