### ISSUE TITLE
关卡选择无法选择BP-XX系列关卡

### ISSUE THREAD

**Issue by hhtcyuan** [MaaAssistantArknights/MaaAssistantArknights#9307]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA无法识别BP-XX系列关卡，并返回错误报告CombatError
内测版本显示为孤星·复刻，多次重启和检查更新后依然无法更新至生路
关卡提示正常显示生路系列关卡

### Version

Resource Version: 孤星·复刻
UI Version: v5.3.2-alpha.1.d049.g8cc7fe3e3
Core Version: v5.3.2-alpha.1.d049.g8cc7fe3e3

### 日志文件

[asst.log](https://github.com/user-attachments/files/15738241/asst.log)
[gui.log](https://github.com/user-attachments/files/15738242/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/140221085/dee91e4c-ef07-4629-8b8a-991af6034ebf)

### 还有别的吗？

mumu模拟器12版本：V3.8.27（2950）

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/25eeaa9a-9dad-4363-8b67-c2748e1f940c)

**Comment by Daydreamer114** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/337719236-25eeaa9a-9dad-4363-8b67-c2748e1f940c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzkzMjYsIm5iZiI6MTcxNzc3OTAyNiwicGF0aCI6Ii85OTA3Mjk3NS8zMzc3MTkyMzYtMjVlZWFhOWEtOWRhZC00MzYzLThiNjctYzI3NDhlMWY5NDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDE2NTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZjZkNTU0ODJiNjk2ZjY2ZTE3NDA1ZDU2Zjg3ODUxZjM2YTkxZGY5YmJmZWJhMTQ3MThjZTkxYmNkZGQxM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vs1XGFQbxCeaS70aY2SEHMi8mgpl43aDRh4KH_kP_IE)

他的ui ver.和core ver.都是最新的，为什么资源版本能不对呢

**Comment by ABA2396** [comment]
资源版本是单独的，和ui和core都没关系，是走的[ota的api](https://ota.maa.plus/)

**Comment by ABA2396** [comment]
不知道咋整的话最简单的办法就是在关闭MAA的情况下把cache删了重启一下，但会丢掉点其他的缓存数据

**Comment by hhtcyuan** [comment]
> 不知道咋整的话最简单的办法就是在关闭MAA的情况下把cache删了重启一下，但会丢掉点其他的缓存数据

好的，我试一下
