### ISSUE TITLE
自动公招可以稍微修改一下下吗，心疼爆炸了

### ISSUE THREAD

**Issue by CHENGJINGXUAN9** [MaaAssistantArknights/MaaAssistantArknights#9308]
### 说说你遇到的问题？

在我公招出现六星tag后我激动的点击准备招募，但是MAA自动帮我刷新掉了这个tag，并且当时是有提示是否要刷新tag的弹窗但是MAA直接选择了刷新，非酋博士十分心疼啊，十分心疼！！！

**Comment by Daydreamer114** [comment]
你开mumu截图增强模式了吗

**Comment by ABA2396** [comment]
抢操作手动点回去的吧

**Comment by ntgmc** [comment]
你可以

- 等MAA运行完再招募
- 停止MAA，招募

出现该问题的原因（猜测）是MAA刚识别完下一个槽你手动点回有六星词条的槽，MAA3星tag自动刷新
如果非上述原因，请携带日志反馈BUG
