### ISSUE TITLE
MuMu模拟器在勾选最小化启动状态下不能最小化启动

### ISSUE THREAD

**Issue by ykw-9826** [MaaAssistantArknights/MaaAssistantArknights#9310]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

模拟器版本V3.8.21

### Version

Core Version: v5.3.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/15743115/gui.log)

**Comment by ABA2396** [comment]
之前和mumu那边沟通过了，得看他们怎么处理
