### ISSUE TITLE
[bili服]生息演算制造刷点数不能自动回档

### ISSUE THREAD

**Issue by BlackNorton** [MaaAssistantArknights/MaaAssistantArknights#9312]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用生息演算功能刷点数，可以正常选择材料并制造，但是到结算日后尝试回档，会在回档界面报错然后停止

### Version

Resource Version: 孤星·复刻
UI Version: v5.3.2-alpha.1.d049.g8cc7fe3e3
Core Version: v5.3.2-alpha.1.d049.g8cc7fe3e3

### 日志文件

[gui.log](https://github.com/user-attachments/files/15743712/gui.log)
[asst.log](https://github.com/user-attachments/files/15743713/asst.log)

### 截图

![Screenshot_2024 06 07_11 33 33 107](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/65427501/881d3493-5dc1-424c-a94a-3c14dd56d852)

### 还有别的吗？

蓝叠国际版5.0.230.1001 N32, 1920x1080, 320dpi

**Comment by ntgmc** [comment]
似乎是鹰角删除了一个确定框，导致流程出错了，坐等修复即可
