### ISSUE TITLE
建议任务执行完后新增“退出MAA和模拟器（仅一次）”

### ISSUE THREAD

**Issue by pongzhe** [MaaAssistantArknights/MaaAssistantArknights#9313]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

基本上我每次运行maa只左键勾画启动任务，其他用右键安排任务，即运行单次任务，任务完成后仅保留启动任务。如果我选择任务完成后“退出MAA和模拟器”，那么会导致新启动maa后，游戏启动完成后紧接着退出的尴尬情况。

### 有什么好的想法？

任务执行完后新增“退出MAA和模拟器（仅一次）”

**Comment by ntgmc** [comment]
1. 为啥要每次都运行单次任务？
2. 为啥要单选启动之后再右键运行单次任务？直接在第一次就右键设置好任务并勾选开始唤醒不行吗

**Comment by Cryolitia** [comment]
related: #6488 

duplicated: #6477

**Comment by pongzhe** [comment]
因为我访问好友，公招这类功能一天只用一次，但是清理智我一天会使用多次。每次启动游戏所完成的任务不同，所以我大多数用的是单次任务

铃语 ***@***.***> 于 2024年6月8日周六 09:27写道：
