### ISSUE TITLE
希望增加抽卡查询，源石记录查询功能

### ISSUE THREAD

**Issue by ikun14514** [MaaAssistantArknights/MaaAssistantArknights#9315]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

我发现每次去鹰角官网查询抽卡记录和源石获取都要登录，有一些麻烦

### 有什么好的想法？

鹰角官网的api:
查询个人token:https://web-api.hypergryph.com/account/info/ak-b

查询抽卡记录，分页:ak.hypergryph.com/user/api/inquiry/gacha?page=1&token=xxxxxx&channelId=2

### 其他内容

希望加在小工具那一栏

**Comment by ntgmc** [comment]
涉及账号密码或token的功能是高危功能，可能会导致隐私泄露，不会考虑。
