### ISSUE TITLE
当水月肉鸽通关后会停在结算界面的前一步

### ISSUE THREAD

**Issue by Rana7wu** [MaaAssistantArknights/MaaAssistantArknights#9318]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

从零开始水月肉鸽，水月肉鸽通关后会停在结算界面的前一步，如果这次因失败而未能通关，则会顺利结算并进行下一次肉鸽探索，但当成功通关结局后，会停在一段剧情页面，无法结算

### Version

Resource Version: 生路, UI Version: v5.3.1, Core Version: v5.3.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15746330/asst.log)
[gui.log](https://github.com/user-attachments/files/15746331/gui.log)
问题在最后一次肉鸽结算页面

**Comment by ABA2396** [comment]
#9276 fixed
