### ISSUE TITLE
自动战斗令切换技能后无法使用召唤物

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9320]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

举例：在自动战斗中使用令3技能后，若运行使用令2技能的作业，maa无法使用召唤物
可用解决方法：关闭maa，进入根目录\cache\avatars，全选删除，重新开启maa；此时可正常使用任意技能，但切换技能时需要重复执行上述步骤

### Version

Resource Version: 生路
UI Version: v5.3.2-alpha.1.d049.g8cc7fe3e3
Core Version: v5.3.2-alpha.1.d049.g8cc7fe3e3

or:
UI Version: v5.4.0-beta.1
Core Version: v5.4.0-beta.1

### 日志文件

正在复现

**Comment by Daydreamer114** [comment]
[asst.bak.log](https://github.com/user-attachments/files/15747303/asst.bak.log)
[gui.log](https://github.com/user-attachments/files/15747304/gui.log)
6月8号下午四点多

**Comment by status102** [comment]
Duplicate of #6060, #6024

**Comment by Daydreamer114** [comment]
这东西去年8月就有人提了啊（
