### ISSUE TITLE
[Windows Toast] 减少非必要`任务出错:Fight`错误通知

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#9327]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

我的任务设置是：

> 关卡选择  ：剿灭（很长一段时间一直是这个）
> 　备选　  ：活动关（或者其他）
> （备选2）：1-7

每次周一打完剿灭后，从剿灭fallback到备选时，总是弹出任务出错:Fight错误通知，而显然这是没必要的(应为warning而非error）

### 有什么好的想法？

- 对于使用了备选功能的，只有在fallback漏穿的情况下才用 Windows Toast 通知错误
- 同样的（同时），GUI里已经给出了：“剩灭任务失败，将尝试使用剩余备选关卡，部分战斗设置将不生效”，因此也不应该在此warning（黄字）之前保留错误的Error（红字）
- 也即：如图中的绿色框部分完全没必要提示
<img width="210" alt="截图_20240609001244" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/53437291/dbe8d266-a101-4338-972b-c02eb207a8a1">

### 其他内容

我以关键词`任务出错:Fight`和`Toast`搜索issue未见其他符合描述的报告，也许应该归类为一个日志级别错误？

**Comment by ABA2396** [comment]
黄字是ui对剿灭做的特殊处理，在stage选择为剿灭的时候额外添加了备选关卡给了core，也就是添加了两个“刷理智”任务，对core来说第一个任务找不到入口就是error

**Comment by KJH-x** [comment]
能理解这个逻辑，但是用户使用体验不太一致，也许有什么其他办法实现？（要不先晾着吧，反正问题不大）

**Comment by ABA2396** [comment]
在ui层面应该可以稍微处理下，之后有空看看

**Comment by KJH-x** [comment]
那是否可以不将“剿灭没找到入口”这个状态报告为error的返回，而是比如像：剩余理智不足继续？（或者其他理由）

（我的理解是此时的“找不到入口”并非游戏或者maa的“错误”而引起的问题，确实不应该归类为error？）

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/1b34e61d-6498-4009-be77-045c68bfb0ee)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/548bc2bb-a7f9-461b-9855-81e25a663334)
