### ISSUE TITLE
Stuck at Running out of OP Screen

### ISSUE THREAD

**Issue by ItsukaHiro** [MaaAssistantArknights/MaaAssistantArknights#9329]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

In case running out of both OP and Sanity Potions, MAA Stuck at Fight task, show [Task error: Fight].
If there is any other tasks, MAA will stuck at the OP screen forever (until it stoped because every task fail)

### Version

Resource Version: Il Siracusano - Retrospection
UI Version: v5.4.0-beta.1
Core Version: v5.4.0-beta.1

### Log files

[asst.log](https://github.com/user-attachments/files/15749873/asst.log)
[gui.log](https://github.com/user-attachments/files/15749874/gui.log)

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64533662/b9762fe2-8d51-4304-b892-932471b0bb14)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64533662/e405e069-18fd-490d-b1a0-1a940877ecbb)
![Screenshot_2024 06 09_06 18 44 013](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/64533662/45782ef1-a023-493c-8eec-3b9d9da59220)

### Anthing else?

Emulator: BlueStacks 5 (1080p)
OS: Windows 11 (24H2)

**Comment by swablueme** [comment]
Just untick the 'perform battles 999 times' thing, that is probably what is messing you up. You don't need to specify the maximum amount of battles, it will run until it clears all your sanity (and top up with sanity pots or originite) automatically then it swaps to the next task.

**Comment by ABA2396** [comment]
> Just untick the 'perform battles 999 times' thing, that is probably what is messing you up. You don't need to specify the maximum amount of battles, it will run until it clears all your sanity (and top up with sanity pots or originite) automatically then it swaps to the next task. If it is reporting that it can't perform 999 battles that is probably what is causing the error.

No, it's because the NoStone.png image had such a low match score that it was considered a failed match. I don't know why this one didn't work, a new screenshot might help.
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/26b84630-415a-4878-bcc6-f3bb94fdf122)

**Comment by ABA2396** [comment]
@ItsukaHiro I need you to confirm that putting this image into `C:\Users\uyee\source\repos\MaaAssistantArknights\resource\global\YoStarEN\resource\template` works.
将图片改名为 `NoStone.png`
![NoStone](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/0046e4eb-fd7a-472f-8062-4cfb7a8b6921)

**Comment by ItsukaHiro** [comment]
@ABA2396 I check all template image from all client (EN, KR, JP, CN,...) and there is no file have the same content.
I'll try to delete and redownload MAA later to check.

**Comment by ABA2396** [comment]
> @ABA2396 I check all template image from all client (EN, KR, JP, CN,...) and there is no file have the same content. I'll try to delete and redownload MAA later to check.

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/534511e3-e317-4a68-9f25-7af2098a481a)
It's not necessary, I checked because it's a different image size than the official one, and template matching is size-sensitive

**Comment by Constrat** [comment]
I never added the template, because I'm at ~1000 OP :P
