### ISSUE TITLE
选人问题

### ISSUE THREAD

**Issue by red000000** [MaaAssistantArknights/MaaAssistantArknights#933]
山的练度比煌高很多，但只选煌
![image](https://user-images.githubusercontent.com/104003896/174488345-05985229-28f5-4f12-bbf0-833b2cd6a5e4.png)
![image](https://user-images.githubusercontent.com/104003896/174488371-b7db80f5-2e45-4042-a3be-d3f31f67db31.png)

**Comment by MistEO** [comment]
请附上日志，谢谢
