### ISSUE TITLE
用户界面“只凹开局干员直升精二”未按预期显示

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9334]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

从刷等级切换到刷开局任务后进入高级设置，第一次勾选“凹开局干员直升精二”时不会显示“只凹开局干员直升精二不进行作战”，需要取消勾选后再次勾选才会显示

### Version

Resource Version: 生路
UI Version: v5.4.0-beta.1
Core Version: v5.4.0-beta.1

### 日志文件

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/807f09b5-d1b0-4837-89fb-f3aaec2dd064

**Comment by ABA2396** [comment]
准备把显示和状态分开 这个之后一起做

**Comment by Daydreamer114** [comment]
1

**Comment by Daydreamer114** [comment]
@ABA2396 这个修好了吧

**Comment by ABA2396** [comment]
是吧）
