### ISSUE TITLE
生息演算自动到第一天结束前后出错 

### ISSUE THREAD

**Issue by KeQingsocute520** [MaaAssistantArknights/MaaAssistantArknights#9335]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

按照要求清除编队，但是运行到第一天结束就会卡出错
![9c7d2642a61bb76f625b5b7cc7801d94](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/129736566/c0896150-ae44-4093-a432-d6318378cdbf

### Version

Resource Version: 生路
UI Version: v5.3.2-alpha.1.d033.gf89d71d5c
Core Version: v5.3.2-alpha.1.d033.gf89d71d5c

### 日志文件

[asst.log](https://github.com/user-attachments/files/15751234/asst.log)
[gui.log](https://github.com/user-attachments/files/15751235/gui.log)

**Comment by ABA2396** [comment]
@HoshinoAyako 看看这个，之前改了 Reclamation2SkipDays1.png 之后在普通模式能匹配上吗
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f4a71af8-ff2e-4ca1-ac74-659f89639d26)

**Comment by HoshinoAyako** [comment]
#9273 你版本不对，这个问题在d038修复的。你版本是d033

**Comment by ABA2396** [comment]
> +1，我也遇到了一样的问题

什么版本，这个问题 v5.4.0-b1 应该已经修了
