### ISSUE TITLE
开始唤醒的账号切换有点错误

### ISSUE THREAD

**Issue by LinShuangPei** [MaaAssistantArknights/MaaAssistantArknights#9339]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

滑动方舟内记录的账号（有多个）时，只能往下滑，往上滑时maa触屏的位置偏上了，滑不到
当前粥是A账号，maa的“切换账号”也是A账号时，有几率会这样
换账号时maa先往下拉（概率遇到），然后再点A账号的位置，但此时A账号已经 被拉到上面了，maa点不动

### Version

UI Version: v5.4.0-beta.1

### 日志文件

应该是最新的时间
24.06.10   03:29:38
[gui.log](https://github.com/user-attachments/files/15753954/gui.log)
[asst.log](https://github.com/user-attachments/files/15753955/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/172211889/eb6383ee-5680-466c-b107-69edfa7a2b28)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/172211889/fc6d69ae-5469-4a81-9279-7b2a738824c5)

### 还有别的吗？

mumu12
win11
1600*900

**Comment by Rnreck** [comment]
现在问题依然存在，而且只要执行账号切换功能就一定报错，且不执行任何操作
