### ISSUE TITLE
有个问题，最新版加了任务完成关闭模拟器选项，但是定时刷的话只能在开启的模拟器中开始任务，建议linkstart加一个开启模拟器的功能

### ISSUE THREAD

**Issue by desktop4025** [MaaAssistantArknights/MaaAssistantArknights#934]
虽然解决了之前一直开着模拟器卡的问题，但没完全解决（x

**Comment by desktop4025** [comment]
我突然想到可以用windows计划任务做到相同的效果，再加上启动程序自动运行，自动打开模拟器就可以了（x

**Comment by ABA2396** [comment]
> 我突然想到可以用windows计划任务做到相同的效果，再加上启动程序自动运行，自动打开模拟器就可以了（x

我一直都是这么干的（x
