### ISSUE TITLE
MUMU模拟器下，自动肉鸽W技能开启后自动关闭

### ISSUE THREAD

**Issue by orangeEx** [MaaAssistantArknights/MaaAssistantArknights#9341]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在mumu模拟器下，开启了快速截图功能，自动肉鸽，在傀影和水月中，均出现异格W三技能开启之后秒关闭的情况，造成W打不出输出

### Version

UI Version: v5.3.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/15755660/gui.log)
[asst.log](https://github.com/user-attachments/files/15755661/asst.log)
时间段在2024/06/10 早上9:50-10:05左右多局游戏出现

**Comment by Rbqwow** [comment]
duplicate of #9113
