### ISSUE TITLE
贸易站基建效率提高

### ISSUE THREAD

**Issue by bwddddd** [MaaAssistantArknights/MaaAssistantArknights#9345]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

精二摩根+推王能提供80%的贸易站效率，但是可能是因为推王在贸易站选择干员时没有技能的缘故导致不会被识别，

### 有什么好的想法？

就是想问一下能不能出一个摩根和推王绑定的贸易站选取

### 其他内容

no

**Comment by ntgmc** [comment]
请使用 `自定义基建`
