### ISSUE TITLE
雷电模拟器任务完成后，无法退出明日方舟

### ISSUE THREAD

**Issue by fireflame-opx** [MaaAssistantArknights/MaaAssistantArknights#9349]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，使用雷电模拟器运行B服明日方舟，MAA选择“完成后：退出 明日方舟”。在任务完成后，明日方舟并未被关闭。

### Version

Resource Version: 生路
UI Version: v5.4.0-beta.1
Core Version: v5.4.0-beta.1

### 日志文件

说明问题出现的大致时间点：2024.06.10 15:20前后
[asst.log](https://github.com/user-attachments/files/15758138/asst.log)
[gui.log](https://github.com/user-attachments/files/15758139/gui.log)

### 还有别的吗？

模拟器：雷电9
系统：win11
明日方舟是B服的

**Comment by Rbqwow** [comment]
后台有运行官服明日方舟吗

**Comment by fireflame-opx** [comment]
没有，模拟器里只安装了B服明日方舟一个软件
不过我模拟器是多开的，其他模拟器装的是别的游戏，也没装官服明日方舟

**Comment by abc1763613206** [comment]
```
star2qltechn:/ $ dumpsys activity activities 2>/dev/null | grep -i -o -E '(packageName|Activities)=.+arknights'
Activities=[ActivityRecord{2f36d93 u0 com.hypergryph.arknights
packageName=com.hypergryph.arknights.bilibili processName=com.hypergryph.arknights
```
----
```
Welcome! If you need help getting started, check out our developer FAQ page at:

    https://g.126.fm/04jewvw

We're committed to making our emulator as useful as possible for developers,
so if you have any specific requirements or features that you'd like to see
in the emulator, please let us know. We're always open to new ideas and suggestions.
You can find our contact information on the FAQ page as well.

Thanks for using our emulator, happy coding!
2206122SC:/ $ dumpsys activity activities 2>/dev/null | grep -i -o -E '(packageName|Activities)=.+arknights'
packageName=com.hypergryph.arknights.bilibili processName=com.hypergryph.arknights
```

**Comment by abc1763613206** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blame/ace690ec25846a1033bc5ef517a1de8acc930623/resource/config.json#L79

Blame 了下，初始就采用了 Activities 判断，后期引入了 packageName .
如上所示，与 MuMu 模拟器相比，雷电模拟器会优先匹配到一个 ActivityRecord ，导致整体判断出错
个人认为可以把 Activities 扬掉，仅判断 packageName ，再看后期测试。

**Comment by abc1763613206** [comment]
另外为了方便调试，建议您尝试进入对应 adb shell 后 输入 `dumpsys activity activities 2>/dev/null | grep -i -o -E '(packageName|Activities)=.+arknights'` ，查看一下输出。

`adb -s emulator-xxxx shell "dumpsys activity activities 2>/dev/null | grep -i -o -E '(packageName|Activities)=.+arknights'"`，xxxx根据具体情况替换
