### ISSUE TITLE
希望增加肉鸽干员抓取黑名单

### ISSUE THREAD

**Issue by Miragelapse** [MaaAssistantArknights/MaaAssistantArknights#9350]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

用maa刷肉鸽等级发现会抓一些我的练度不高的干员如：阿米娅，蜜梅，感觉这种时候不如跳过攒希望

### 有什么好的想法？

增设一个黑名单功能，把这些我不希望maa抓的干员列出来

**Comment by Daydreamer114** [comment]
你可以自行进入根目录\resource\roguelike\对应肉鸽\recruitment.json自行修改优先级，如果抓了Amiya或者蜜梅，说明你整体练度就很低并且缺少主力干员

**Comment by Daydreamer114** [comment]
至于你说的黑名单功能，实现方式是把干员的招募优先级设置到预备干员以下

如果你看到了的话可以自己关一下issue
