### ISSUE TITLE
Python调用MAA报错

### ISSUE THREAD

**Issue by yokinanya** [MaaAssistantArknights/MaaAssistantArknights#9351]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用MAA提供的sample.py同样会报错

### Version

Core Version: v5.4.0-beta.1.d009.g7c58f1d49

### 日志文件

Exception ignored in: <function Asst.__del__ at 0x000002047CC8C900>
Traceback (most recent call last):
  File "d:\Software\MeoAssistantArknights\Python\asst\asst.py", line 96, in __del__
OSError: exception: access violation writing 0x0000000000000000

### 还有别的吗？

影响范围：v5.4.0-beta.1 - 最新版本

**Comment by ABA2396** [comment]
看看是不是类似 #9321

**Comment by yokinanya** [comment]
> 看看是不是类似 #9321

和运行库没关系，直接使用maaui能正常运行

**Comment by ABA2396** [comment]
62行 if asst.connect('adb.exe', '127.0.0.1:5555'):改成你自己的adb和模拟器端口

**Comment by yokinanya** [comment]
> 62行 if asst.connect('adb.exe', '127.0.0.1:5555'):改成你自己的adb和模拟器端口

报错是在连接上模拟器之后发生的

**Comment by ABA2396** [comment]
所以日志呢？控制台输出呢？光一个报错能看出啥

**Comment by yokinanya** [comment]
> 所以日志呢？控制台输出呢？光一个报错能看出啥

控制台输出只有这个报错，没其他任何东西

**Comment by HoshinoAyako** [comment]
你试试按用32位的python试试？

https://stackoverflow.com/questions/32676543/pyperclip-copy-causing-an-oserror

**Comment by ABA2396** [comment]
不用管这个，这个是没加回调的时候析构时候报的错，程序结束了不管怎么样都释放了

**Comment by ABA2396** [comment]
1b2cc439f2dcdf2def8090fd419b7adf256703a9 fixed
