### ISSUE TITLE
希望添加萨米的藏品指定/优先购买选择藏品

### ISSUE THREAD

**Issue by Tacenda5618** [MaaAssistantArknights/MaaAssistantArknights#9354]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

类似水月有指路鳞 萨米也有难刷的藏品例如黑白舞鞋 （只有第三层和第五层boss战出，和告解板子有概率出） 希望能增加优先选择/商店优先购买藏品来点亮这个

**Comment by HoshinoAyako** [comment]
水月的指路鳞在商店可以刷到。
黑白舞鞋这个要么事件出，要么关卡掉落奖励。这个没办法
