### ISSUE TITLE
蓝叠国际版启动提示分辨率错误

### ISSUE THREAD

**Issue by Chiichen** [MaaAssistantArknights/MaaAssistantArknights#9355]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

蓝叠模拟器启动时报错 `模拟器分辨率不支持，请设置为 720p 或更高，且为 16:9 比例`。使用的是`MaaTouch`，强制替换adb后出现该报错

### Version

Resource Version: 生路
UI Version: v5.4.0-beta.1.d009.g7c58f1d49
Core Version: v5.4.0-beta.1.d009.g7c58f1d49

### 日志文件

[asst.log](https://github.com/user-attachments/files/15789310/asst.log)
[gui.log](https://github.com/user-attachments/files/15789311/gui.log)

时间点可参考 `2024-06-11 22:10:25` 前后

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39649411/ca44e96f-a386-435d-8038-489b33238772)

**Comment by Rbqwow** [comment]
adb 获取到的是 2220x1080
重启一下模拟器电脑之类的试试..?

**Comment by Chiichen** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/39649411/e641d4f7-c89d-461d-8960-4fd31b480c39)
破案了.jpg

**Comment by Chiichen** [comment]
可是为什么会连到这来(

**Comment by SherkeyXD** [comment]
> 可是为什么会连到这来(

你 adb 地址填错了吧（
