### ISSUE TITLE
萨米肉鸽在抗干扰指数为0时，依旧会选择探索新路径

### ISSUE THREAD

**Issue by Asterisis** [MaaAssistantArknights/MaaAssistantArknights#9356]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在挂机萨米肉鸽的时候，有时候抗干扰指数降到0了，MAA还一直想要探索新路径

### Version

Core Version: v5.4.0-beta.1.d009.g7c58f1d49

### 日志文件

[asst.log](https://github.com/user-attachments/files/15789986/asst.log)
[asst.log](https://github.com/user-attachments/files/15789986/asst.log)
[asst.log](https://github.com/user-attachments/files/15789986/asst.log)
[gui.log](https://github.com/user-attachments/files/15789990/gui.log)
[gui.log](https://github.com/user-attachments/files/15789990/gui.log)
[gui.log](https://github.com/user-attachments/files/15789990/gui.log)

6/11 18:30之后

**Comment by Lancarus** [comment]
日志没有包含相应时段，请上传asst.bak.log

**Comment by Asterisis** [comment]
[asst.bak.zip](https://github.com/user-attachments/files/15791175/asst.bak.zip)
