### ISSUE TITLE
干员识别重复出现阿米娅

### ISSUE THREAD

**Issue by XiatianJKY** [MaaAssistantArknights/MaaAssistantArknights#9358]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

干员识别重复出现阿米娅，其中阿米娅在已拥有中出现一次，在未拥有中又出现了一次阿米娅-MEDIC，详情图片已附在下文

### Version

UI Version: v5.4.0-beta.1.d009.g7c58f1d49

### 日志文件

[asst.log](https://github.com/user-attachments/files/15792837/asst.log)
[gui.log](https://github.com/user-attachments/files/15792839/gui.log)
时间为2024-06-12 01:30左右

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/172425398/8640c764-5b13-4744-9f58-02c7ad4cae0f)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/172425398/0590b6f5-fa9f-4458-86e3-9d31563e79b2)
[oper.zip](https://github.com/user-attachments/files/15792834/oper.zip)

### 还有别的吗？

使用MUMU模拟器V3.8.21，且为mumu截图模式

**Comment by ABA2396** [comment]
没复现出来，照理来说 #9347 改完之后应该没这个问题了
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/8c21c20d-8275-4086-a0b3-98b78867dcb9)

**Comment by XiatianJKY** [comment]
我这边一直能够复现，不知道是什么问题导致的，而且我这边总干员数因为医疗阿米娅变成332了，发个整包看看吧
夸克3dcdd9491178

**Comment by ABA2396** [comment]
现在发个内测版，过半小时更新下看看
