### ISSUE TITLE
任务框的点击事件

### ISSUE THREAD

**Issue by Anonywp** [MaaAssistantArknights/MaaAssistantArknights#936]
为啥要有蓝色的选中效果呢，感觉没什么用啊，直接合并到打勾不是更方便

**Comment by zzyyyl** [comment]
蓝色选中我也很早就想说了，强迫症震怒（
其实用户有一种可行的解决方案，就是在不小心点出蓝色选中的时候拖动一下就好了 :eyes:

**Comment by MistEO** [comment]
不会写.jpg
