### ISSUE TITLE
基建换班可以设置换不换人，并且在不进行换人操作的情况下使用无人机加速

### ISSUE THREAD

**Issue by Lnmes** [MaaAssistantArknights/MaaAssistantArknights#9360]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

基建不能设置不换人，一天早上九点晚上九点，一般是早上不换人，晚上一起全部换一次人，但是好像并不能设置早上不换人，这会导致一大堆干员理智不满，而且取消勾选需要换人的设施后，无人机加速也不会进行

### 有什么好的想法？

直接添加一个只收菜不换人的按钮（线索交流也只获取线索，不换人），很多情况下干员理智还有很多就换掉了，而且可以使用无人机加速（取消勾选需要换人的设施后，无人机加速也不会进行）

### 其他内容

![080de31c4f2572b4a9e3663e5cd45663](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/65465406/b193275c-7fdc-4bb6-a523-d2e7bf14c258)

**Comment by ABA2396** [comment]
你把工作心情阈值拉的太低了，按你现在的设置高于0心情的人只要效率比剩下的高就不会被换下来
既然你一天两换又不用自定义基建的话，把阈值拉到30-40%就差不多了

**Comment by Lnmes** [comment]
> 你把工作心情阈值拉的太低了，按你现在的设置高于0心情的人只要效率比剩下的高就不会被换下来 既然你一天两换又不用自定义基建的话，把阈值拉到30-40%就差不多了

设置为0还是会换人的

**Comment by ABA2396** [comment]
感觉你还没理解阈值和换班的关系，自动换班的逻辑就是在高于心情阈值的人里面选效率最高的人，你现在这个设置就是效率高的人一定要做到红脸才会被换下来

**Comment by Lnmes** [comment]
> 感觉你还没理解阈值和换班的关系，自动换班的逻辑就是在高于心情阈值的人里面选效率最高的人，你现在这个设置就是效率高的人一定要做到红脸才会被换下来

啊，这样设置还是会把人换下来的，没用，这个阈值有没有都没有意义，我设置成0，立马把刚放进去的干员换了，所以想不换人只能关了，但是完全关了无人机就不会加速了

**Comment by ABA2396** [comment]
所以为啥有只用无人机不换班的需求，是缺这么点时间吗）那你可以用自定义基建自己写个排班表，然后全部的设施全写跳过，选一个设施设置使用无人机

**Comment by Lnmes** [comment]
> 所以为啥有只用无人机不换班的需求，是缺这么点时间吗）那你可以用自定义基建自己写个排班表，然后全部的设施全写跳过，选一个设施设置使用无人机

不是时间的问题，是一天换几次班会导致一堆干员理智不满，要是只能自己去设置基建自定义才能弄的话那就算了，反正就是一天两次，一次只加速获取情报不换人，一次加速换人

**Comment by ABA2396** [comment]
我还是那句话，默认心情阈值设在30%是有原因的，如果你没搞懂阈值和换班的关系的话还是保持默认吧
