### ISSUE TITLE
内测版更新后闪退

### ISSUE THREAD

**Issue by Xtzdd** [MaaAssistantArknights/MaaAssistantArknights#9361]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新版本=内测版。今日更新后软件出现闪退状况，具体表现为更新后软件窗口一闪而过，状态栏有软件logo但鼠标晃过后消失。
已尝试以下操作：
1，根据近似问题#9321 中的说明（https://www.bilibili.com/opus/940613080927174676 ）安装两运行库并重启系统，重启后无法启动MAA。
2，从官网下载正式版（MAA-v5.3.1-win-x64），解压到另一处位置运行，MAA启动正常。
3，使用正式版安装包中所有内容替换已无法运行的版本，替换后运行正常，但因为启用了自动下载和更新，软件自动执行更新后无法启动MAA。
4，重复步骤3，赶在下载完成之前取消自动更新，根目录得到包体名称=MAAComponent-OTA-v5.3.1_v5.4.0-beta.1.d009.g7c58f1d49-win-x64.zip，重启软件后执行更新再次无法启动MAA。
5，尝试绕开软件更新，手动将OTA中文件替换运行文件更新，更新后无法启动MAA。
6，将步骤2产生的正式版的更新选项切换为内测版，执行步骤5中的手动更新，更新后无法启动MAA。

### Version

我已无法提供确切的最后一个可用的内测版本号，但可以确认截止到24年6月11日上午内测版更新后可用。
目前可用的正式版版本号：
资源版本：孤星·复刻，界面版本：v5.3.1，核心版本：v5.3.1

### 日志文件

以下两文件出自常用副本：
[asst.zip](https://github.com/user-attachments/files/15799541/asst.zip)
[gui.zip](https://github.com/user-attachments/files/15799542/gui.zip)
以下两文件出自测试用副本：
[asst.zip](https://github.com/user-attachments/files/15799712/asst.zip)
[gui.zip](https://github.com/user-attachments/files/15799713/gui.zip)
6月12日的部分。

### 还有别的吗？

有关安装包：
[MAAComponent-OTA-v5.3.1_v5.4.0-beta.1.d009.g7c58f1d49-win-x64.zip](https://github.com/user-attachments/files/15799627/MAAComponent-OTA-v5.3.1_v5.4.0-beta.1.d009.g7c58f1d49-win-x64.zip)
系统版本	Windows 10 企业版 LTSC
版本号	21H2
安装日期	‎2023/‎1/‎30
操作系统内部版本	19044.4529
体验	Windows Feature Experience Pack 1000.19058.1000.0

**Comment by Xtzdd** [comment]
补充上述测试思路。
步骤2，大致排除系统环境问题。
步骤3，大致排除因用户数据产生的问题。
步骤4，得到更新包体。
步骤5，大致排除软件自行更新相关的问题。
步骤6；大致排除路径名称，文件权限相关产生的问题。

**Comment by ABA2396** [comment]
之前有解压过win10rt吗？来个文件夹的截图看看

**Comment by ABA2396** [comment]
> 步骤2，大致排除系统环境问题。

这个大概率就是环境问题，GitHub Actions Runner 前几天更新了，打出来的东西也比较新）

**Comment by Xtzdd** [comment]
> 之前有解压过win10rt吗？来个文件夹的截图看看

请问是哪个win10rt？
安装后文件状况如下：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161123932/fdbcab2b-f00c-40d8-9386-a671333b4936)

**Comment by Xtzdd** [comment]
我测试了一下公测版，更新包名：MAAComponent-OTA-v5.3.1_v5.4.0-beta.1-win-x64.zip，同样的问题。

**Comment by ABA2396** [comment]
一样的，因为GitHub Actions Runner就是5.4.0-b1前一天更新的

**Comment by ABA2396** [comment]
你在安装vc_redist.x64的时候提示的是哪个版本？
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/11289d49-3f26-4b84-ac1b-9f981eeb6da0)

**Comment by Xtzdd** [comment]
还想请问一下，用户个人设置文件保存在哪里？
这样在未来软件崩溃时，可以复制少量文件出来替换到新的副本上来继承设置。

**Comment by ABA2396** [comment]
config/gui.json

**Comment by ABA2396** [comment]
> config/gui.json

现在迁移还没做完，之后应该是 config/gui.new.json

**Comment by Xtzdd** [comment]
VC版本比较多：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/161123932/71a9286a-8e82-4d19-86e3-721ef538ce8b)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/d1b0310f-0749-427c-b069-ec59334e8207)
这个版本不对，最新的应该是上面图里的这个

**Comment by ABA2396** [comment]
VC++: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Xtzdd** [comment]
> VC++: https://aka.ms/vs/17/release/vc_redist.x64.exe

好的已经正常了，看来是这个问题，VC版本不对。
