### ISSUE TITLE
自动战斗添加关闭技能功能

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9364]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

ew自动战斗需要关技能但没法写

### 有什么好的想法？

把使用技能的代码照搬，然后把识别图标的部分删了，或者改成识别子弹技能的图标

**Comment by ABA2396** [comment]
开技能不用识别头顶的图标的啊，直接作业里写开技能不行吗

**Comment by Daydreamer114** [comment]
> 开技能不用识别头顶的图标的啊，直接作业里写开技能不行吗

![D6E36008AB35F7E88B5A7BD90F0D2F0E](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/4f0845d0-d379-46ab-9d8f-516f3a4afc66)
e 发过的图

如图，作业站里的使用技能是点开角色之后对技能是否就绪进行识别（这样就同时完成了子弹时间和秒开技能）
（目前如果识别不到技能就绪，有一个超时设定，超时后会让战斗继续）
希望可以添加一个相同的策略，点开角色之后对弹药技能进行识别和关闭

另外，存在ew的转火、ew的祖宗节弹和水陈的节弹，可以把技能未就绪的识别也加进来，在进行关闭技能的操作时如果识别到技能未就绪就认为弹药技能已结束，往旁边点一下然后让战斗继续

**Comment by ABA2396** [comment]
点开角色之后的弹药技能不就是BattleSkillStioOnClick吗
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/9201e70b-4422-40f7-aff4-02a5ca305f5b)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/bc0ca9ef-a15f-4a7b-bb9f-ff6c6b339b7a)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/6dabd52c-2a97-4603-9008-5e0159cbb197)

**Comment by Daydreamer114** [comment]
使用技能的代码里也会识别弹药技能的图标？那可就又是偏移的问题了
