### ISSUE TITLE
萨米肉鸽选完干员后电脑黑屏重启

### ISSUE THREAD

**Issue by Maboroshinatsu** [MaaAssistantArknights/MaaAssistantArknights#9366]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

这个issue反馈的问题应该和 #9237 是同一个问题，但是排除了显卡驱动问题
我重新安装了一遍mumu模拟器12，然后出现此问题，萨米肉鸽选完干员后电脑黑屏重启，在重新安装maa后问题仍旧
在这之前电脑黑屏重启为概率问题，有过几次长时间未出现问题的，都是自动运行生息演算时，但大多数时候都会重启，尤其是肉鸽（至少水月和萨米是这样，愧影没打过不清楚）
在 #9237 中Rbqwow建议我在事件查看器里找找有没有相关的事件，但是请原谅我没有理解事件管理器指的是asst.log还是gui.log或是其他的东西（），如果是的话请原谅我看不懂:(

### Version

Resource Version: 生路
UI Version: v5.4.0-beta.1
Core Version: v5.4.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15808724/asst.log)
[gui.log](https://github.com/user-attachments/files/15808726/gui.log)

### 截图

![2024-06-13_01-12-06-358_Page2_Error](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/171314009/48af5847-a40d-4c95-b0ba-3621f259514e)

### 还有别的吗？

mumu12

**Comment by Daydreamer114** [comment]
#9237

**Comment by Rbqwow** [comment]
事件查看器就叫事件查看器啦 是Windows的一个组件 所有和系统有关系的日志都能在这查到 win+s打开搜索框里面搜就有
另外github打 `#数字` 记得前后空格 不然它识别不了跳转的

**Comment by ShirasawaYui** [comment]
其实是WHEA1事件，我也有，而且所有出现这个故障的人都是使用mumu12并且应该是开了截图增强导致cpu占用率激增

cpu如果是定频定压则不会出现WHEA事件，使用Bitsum最高性能模式电源计划也能完全规避。

如果开启了任何节能或者全auto则会在maa执行任何与自动战斗相关的任务时cpu各个核心的电压因为调节跟不上频率与使用率的剧烈变化而随机触发WHEA1

原因的本质是自己的CPU是雷，刚刚摸到出厂合格证的那种。
不如直接别用截图增强，反正我个人的现象是要么全核定频要么关截图增强，这样就暂时再也没有重启现象了。
或者你也可以试试平衡-平衡电源模式，这种模式不会那么激进的降低CPU核心电压，个人臆测也能缓解出现的频率。
反正别让maa碰最佳能效和效率模式这两玩意

**Comment by ShirasawaYui** [comment]
不如说换个角度，maa也能作为测试cpu超频稳定性的一款实用工具了

可喜可贺可喜可贺。

**Comment by ABA2396** [comment]
这个这个问题得找mumu反馈了

**Comment by ShirasawaYui** [comment]
> 这个这个问题得找mumu反馈了

我寻思找mumu没用，回复都想好了，请使用Intelbaseline和关闭amdpbo

其实非要说还是maa自己的问题，毕竟搜issue早在23年就有黑屏重启的报告了，那时候连截图增强的影子都没有，mumu截图增强无非就是扩大了这个故障的发生范围。
要么就是大家都是硅渣，一遇到这种“我叫maa，我搞自动战斗的原则就是淦你娘塞爆，接下来我要在每个截图周期中随机抽取几个幸运线程塞爆，cpu跑过来问我为什么频率变化这么剧烈，我tm怎么知道”的不怎么常见的事再多运行一秒就会爆炸，要么就是maa的确在某个不起眼的地方会随机引发whea事件，毕竟所有的稳定性测试软件都说ok，就maa会whea虽然换硬件运气好的确解决100%问题，但你maa难道就没有（ry

我觉得就单纯是用户群体里几个倒霉鬼聚堆了而已，没得修，比起找mumu不如找Intel，哦，Intel已经发布了baseline了啊？那没事了。

**Comment by ShirasawaYui** [comment]
当然，也有可能的确是mumu截图增强功能有问题，也许现在集中爆发的都使用mumu12过程中的黑屏和23年的黑屏根本不是一回事。那样联系mumu的确能有用
大概吧，也许。
我乱说的我根本没懂，我脑子根本没思考。

**Comment by JYlYK** [comment]
最近我电脑也总是在开了maa后不久就蓝屏，而且cpu也搞过降压，难道是因为这个原因？
