### ISSUE TITLE
请求 基建 - 加工站 - 拆解家具 功能

### ISSUE THREAD

**Issue by Xiangze-Li** [MaaAssistantArknights/MaaAssistantArknights#9368]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

有时我会需要更多家具零件，而仓库里有不少掉落的家具，但是手动拆解太麻烦了

### 有什么好的想法？

提供一个功能：将关卡掉落的家具 A.全部拆解 或 B.拆解到只剩1套，不拆解活动获得/限定购买的家具

**Comment by HoshinoAyako** [comment]
一般情况下，家具零件是溢出的。而且有的家具套装里，单个家具不止一件，处理起来很麻烦。

**Comment by Xiangze-Li** [comment]
在我这里的case是因为不会去刷建材关，家具零件总是紧平衡，偶尔不够用。不知道是否有人也是这样的。

关于处理逻辑，简单一些的话实现成 关卡掉落家具全部拆解 或许就足够了？毕竟家具的数量总是很过剩。

**Comment by Xiangze-Li** [comment]
> 关卡掉落家具过一段时间都会变成可购买家具的，那就又回到要无法确定保留数量的问题了

我没有理解这里的问题？变成可购买的关卡掉落家具也可以全部拆解呀？

我的逻辑换一种表述应该是 只要不是限定家具（活动商店、签到赠送、礼包购买 etc），拆掉会导致无法再次获取的，都可以拆。

**Comment by ABA2396** [comment]
没毛病，但你怎么判断这个家具是不是限定）

**Comment by ABA2396** [comment]
看了下掉落的好像拆掉一个只有5个零件，幸运掉落的概率是3%，也就是说刷一年可能可以凑出一千个零件不到）这个功能可能一年都用不上一次
