### ISSUE TITLE
模拟器连接出错

### ISSUE THREAD

**Issue by yzh020304** [MaaAssistantArknights/MaaAssistantArknights#937]
使用的时候每次都会显示连接失败，请检查连接设置。有时候关掉重开有几率可以连上。
使用的是雷神模拟器。
![image](https://user-images.githubusercontent.com/80802484/174506820-4389ab5d-9b3d-407a-a0ba-1d01720911c3.png)
![image](https://user-images.githubusercontent.com/80802484/174506842-507fb707-5bc1-4c32-adc9-7d783b590009.png)

**Comment by yzh020304** [comment]
也试过连接这里下载的adb，效果是一样的

**Comment by MistEO** [comment]
请附上日志文件，谢谢~
