### ISSUE TITLE
更新4.0.0以后点LinkStart就闪退

### ISSUE THREAD

**Issue by BlackCG** [MaaAssistantArknights/MaaAssistantArknights#938]
更新4.0.0版本后软件可以打开，但是点击LinkStart后在连接模拟器那一步就会闪退了，重新手动下载更新包也不行

![QQ截图20220620092524](https://user-images.githubusercontent.com/107821344/174509875-ee5e66f6-fa52-4040-ba61-a2a3c465aeee.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8936877/asst.log)

**Comment by MistEO** [comment]
闪退原因可能是 adb 没找到，`E:\youxi xiang guan\shou you\Arknights\MeoAssistantArknights_v3.1.3\platform-tools\adb.exe` 检查一下你输入的这个路径
