### ISSUE TITLE
Roguelike investment broke

### ISSUE THREAD

**Issue by reb1rthgamer** [MaaAssistantArknights/MaaAssistantArknights#9385]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

MAA doesnt invest while on invest page

### Version

Resource Version: Il Siracusano - Retrospection
UI Version: v5.4.0-beta.1.d020.g90d3c140f
Core Version: v5.4.0-beta.1.d020.g90d3c140f

### Log files

ln42299 is when investment stops working
[debug.zip](https://github.com/user-attachments/files/15836180/debug.zip)

**Comment by ABA2396** [comment]
StageTraderInvestConfirm.png The match score is very low, has there been a change since the update
![Roguelike@StageTraderInvestConfirm](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/21b510cb-6f8c-47c0-96c7-0b1a56b424e0)
cc @Constrat

**Comment by Constrat** [comment]
I remember I had a similar issue, but it was my fault in setting up MAA. I feel like it's the usual not 1920x1080 resolution thing.
Let me check resolution

**Comment by reb1rthgamer** [comment]
> I remember I had a similar issue, but it was my fault in setting up MAA. I feel like it's the usual not 1920x1080 resolution thing. Let me check resolution

this might be it

**Comment by Constrat** [comment]
The stdout shows 1920x1080. So I don't think it's res-related unfortunately.

**Comment by Constrat** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/8b9a585c-9de4-47a2-ba70-2a2af635b77d)
It's investing correctly.

**Comment by reb1rthgamer** [comment]
yea im letting it do a run while in 1920x1080 rn

**Comment by reb1rthgamer** [comment]
no it wasnt, ive no idea when or why

**Comment by Constrat** [comment]
@ABA2396 Is there any option we could put a small placeholder for YostarEN remembering to use 1920x1080 here for example?
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/a9a7c191-b80f-4d6b-a7d8-fa6c4e742f42)

**Comment by Constrat** [comment]
> no it wasnt, ive no idea when or why

Log was lying then XD

**Comment by reb1rthgamer** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/172769216/44454bae-eb61-4a3b-8508-ccceebb97abd)
ok yea its working
