### ISSUE TITLE
优化使用连战功能，增加全盘葛朗台模式

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#9388]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

我不小心把连战功能当成了材料刷取数量，错误的选择了连战次数，同时我又勾选了使用理智药选项，使得MAA在刷理智的时候因为理智不够连战的，所以开了一瓶理智药，造成理智溢出。

### 有什么好的想法？

将连战功能放入二级菜单，并且在可能造成理智溢出时增加二次确认步骤。MAA也可以增加全盘葛朗台模式，以避免任何可能造成理智溢出的操作，或者在这类操作中增加二次确认步骤。

**Comment by status102** [comment]
连战次数设置框可关
