### ISSUE TITLE
水月肉鸽结算时卡住

### ISSUE THREAD

**Issue by CCDX04** [MaaAssistantArknights/MaaAssistantArknights#9389]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

水月肉鸽，打完水月四结局之后在结算界面会过前两个结算界面，就是第一个介绍你干了什么，和第二个哪些干员获得排异反应，之后就会卡在第三个界面，就是通关各个层数的灯火情况。并且不会显示。在日志里就是gui中
[2024-06-13 00:11:00.289] <1><> 开始战斗: “命运的宠儿”
这一条开始之后，长达三小时没有变，一直到三点半发现问题。
而在之后的挂机中没有出现该问题。（忘记截图了）
而在
[2024-06-14 14:59:16.791] <1><> 开始战斗: 人之光辉
后，同样出现了该问题，并没有动电脑，战斗也是成功的（这两个都是）
另外就是出现问题后发现右下角托盘里maa的图标变成了两个

### Version

Resource Version: 生路
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[gui.zip](https://github.com/user-attachments/files/15839117/gui.zip)
[asst.zip](https://github.com/user-attachments/files/15839120/asst.zip)

**Comment by ABA2396** [comment]
#9276 fixed
