### ISSUE TITLE
刷理智增加跳过掉落识别选项

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9391]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

若用户不需要了解掉落情况，那么等待掉落完全显示然后进行识别会浪费时间（还会费电

### 其他内容

...也要速通（bushi

**Comment by ntgmc** [comment]
Duplicate of #2359 #2384

**Comment by Daydreamer114** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2384#issuecomment-1287661025

@ntgmc 不太一样，识别本身不耗时，但是至少现在的识别是要等材料全部显示的，退出结算界面只需要最左边的经验俩显示完就可以退了

<img width="255" alt="截屏2024-06-15 21 31 38" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74444214/8181b3f2-9cbf-46ae-9a5d-cec388ed344f">

**Comment by ntgmc** [comment]
几秒而已，你可以选择连战次数6更省时间

**Comment by Daydreamer114** [comment]
这种东西自己写有可能merge吗
