### ISSUE TITLE
[MacGUI]日志报错GUI未正常显示

### ISSUE THREAD

**Issue by sjfhsjfh** [MaaAssistantArknights/MaaAssistantArknights#9392]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，找log找到了报错但窗口里啥也不显示就停了，让人摸不着头脑
翻了下源码找到打log的位置但对C++一窍不通提不了pr（哭
复现步骤：
1. 使用默认配置的MAA编辑任务列表中的“刷理智”一项
2. 勾选“手动输入关卡名“
3. 输入一个类似于"BP-5"这样过不了正则的关卡名
4. 预期行为：直接终止执行所有任务并不显示任何log信息

### Version

v5.4.0-beta.1（492）

### 日志文件

{"stage":"BP-5","client_type":"","enable":true,"penguin_id":"","DrGrandet":false,"server":"CN","report_to_penguin":false,"expiring_medicine":999}

### 还有别的吗？

https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/d2e5001e7e1a8adebce80a93b736dffc0d77069f/src/MaaCore/Task/Fight/StageNavigationTask.cpp#L29
以及这句是不是有typo
以及这个正则如果是拿来判主线关卡是不是有点不合适（

**Comment by ABA2396** [comment]
@hguandl appendTask里加个catch吧
https://github.com/MaaAssistantArknights/MaaMacGui/blob/3c1787a5118723a9da653a7bd48732e2f8edefab/MeoAsstMac/Model/MAAViewModel.swift#L305
