### ISSUE TITLE
保全派驻（多索雷斯商业地块）异常

### ISSUE THREAD

**Issue by hcm426759** [MaaAssistantArknights/MaaAssistantArknights#9394]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

保全派驻模式本期更新之后，多索雷斯商业地块总是卡在第四关前选择配件界面，手动点击之后也无法正常进行，重装maa和更新内测版都无效果

### Version

Resource Version: 生路
UI Version: v5.4.0-beta.1.d035.gd2e5001e7
Core Version: v5.4.0-beta.1.d035.gd2e5001e7

### 日志文件

[asst.log](https://github.com/user-attachments/files/15845781/asst.log)
[gui.log](https://github.com/user-attachments/files/15845782/gui.log)

### 截图

![9D2C7AD1737C387850B908D8E6B52047](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90763790/afcc5d5a-345c-444c-bb89-f0e6517ebd38)
![BC084672504EF3D5665F9683A7D3C4DB](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/90763790/71926947-3c64-4902-b506-b9284d3b9223)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/ec887cee-17ba-440b-8648-7c3673c6f5ec)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/6525adce-4b28-49b2-a5bd-77c86b955ac9)
这怎么能识别出这种东西的，怀疑是4k的图片压缩的问题了，试试看改成1080p或者720p有没有这个问题

**Comment by hcm426759** [comment]
把模拟器分辨率修改为2k及以下后可以正常运行了，感谢。后续可以有别的优化方案吗，4k显示器用不了对应分辨率总感觉还是别扭了

**Comment by ABA2396** [comment]
感觉加点4k压缩到720p的训练集重新训练下可能有用
cc @Plumess

**Comment by Plumess** [comment]
> 感觉加点4k压缩到720p的训练集重新训练下可能有用 cc @Plumess

是这个思路，此前的训练集都没有考虑到这个情况，我找个时间正好重训一下
