### ISSUE TITLE
ew关技能bug

### ISSUE THREAD

**Issue by yh77777777** [MaaAssistantArknights/MaaAssistantArknights#9395]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

ew开技能后会立刻自动关闭，可能是因为打开了mumu截图增强模式

### Version

Resource Version: 生路
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/15846328/gui.log)

**Comment by IzakyL** [comment]
已经在测试版中修复 #9379 稍后会推送到正式版
