### ISSUE TITLE
日服 自动公招无法侦测到招聘许可不足

### ISSUE THREAD

**Issue by amasoiD** [MaaAssistantArknights/MaaAssistantArknights#9397]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120790328/737c5c7b-1887-491c-9208-0c6c01920ad4

### Version

Resource Version: シラクザーノ・復刻
UI Version: v5.4.0-beta.1.d035.gd2e5001e7
Core Version: v5.4.0-beta.1.d035.gd2e5001e7

### 日志文件

[asst.log](https://github.com/user-attachments/files/15847543/asst.log)
[gui.log](https://github.com/user-attachments/files/15847545/gui.log)

**Comment by Manicsteiner** [comment]
RecruitNoPermit 是图像识别，应该不需要翻译，log里得分只有0.6多一点，更具体的原因就不好说了
[2024-06-15 19:59:48.494][TRC][Px80c4][Tx8078] match_templ | RecruitNoPermit.png score: 0.609781 rect: [ 365, 658, 96, 25 ] roi: [ 300, 600, 190, 110 ]

**Comment by Manicsteiner** [comment]
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/26883049-fd9c-430d-ac25-d78196511ddc)
流汗了，截图带个灰边，还刚好遇上了一块粒子效果，识别不到也正常吧
[RecruitNoPermit.zip](https://github.com/user-attachments/files/15848331/RecruitNoPermit.zip)
试试用这个 RecruitNoPermit.png 替换 resource/template 的同名文件，看看能不能识别

**Comment by amasoiD** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/120790328/54ce286d-6650-4b18-a028-560236b77b44)
还是不行
[asst.log](https://github.com/user-attachments/files/15849248/asst.log)
[gui.log](https://github.com/user-attachments/files/15849284/gui.log)

**Comment by Daydreamer114** [comment]
是1920x1080吗

**Comment by amasoiD** [comment]
1280x720的模拟器，1920x1080的显示器

**Comment by Daydreamer114** [comment]
> 1280x720的模拟器，1920x1080的显示器
> 繁中服测试都没有问题，到了日服就一直报错

可以试试1920x1080的模拟器，我是这么解决的，体验下来不同服识别率最高的分辨率不一样
