### ISSUE TITLE
双击maa无法运行

### ISSUE THREAD

**Issue by The-gold-of-wind233** [MaaAssistantArknights/MaaAssistantArknights#9399]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

双击maa无法运行

### Version

无法打开maa

### 日志文件

[asst.log](https://github.com/user-attachments/files/15856527/asst.log)
[gui.log](https://github.com/user-attachments/files/15856528/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/169917985/d80762ce-caab-4c0c-b3be-4a4d6439ac50)

**Comment by ABA2396** [comment]
更新解压失败了，有进程占用了maa的文件，尝试手动解压目录下的 MAAComponent-OTA 更新包
