### ISSUE TITLE
“上次作战”功能工作不正常

### ISSUE THREAD

**Issue by bgli100** [MaaAssistantArknights/MaaAssistantArknights#940]
刷理智选“上次作战”执行稳定出错（测了1-7和10-4, 此处是1-7的log），出错时截图如图所示
指定关卡（测了CE-6/LS-6/AP-5）可以正常工作

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8937575/asst.log)

![Screenshot_2022 06 20_12 46 50 569](https://user-images.githubusercontent.com/7760499/174527163-47214365-17f7-4653-b9a9-147c75a77e4e.png)

MAA的图不截了，就一个红字任务出错: Fight 然后结束

BlueStacks 5 国际版 x64 Hyper-V

**Comment by ABA2396** [comment]
`[2022-06-20 12:43:37.135][TRC][Pxa0d4][Tx9ee4] OcrPack::recognize | roi :  [ 900, 500, 280, 100 ] `
看你日志里这一行roi的位置和最新的task.json里的好像是不太一样，那个导航我之前修改过，现在用的是最新版吗，试着更新一下或者手动替换一下最新的task.json试试

**Comment by bgli100** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8940846/asst.log)

用master上面的tasks.json覆盖了安装路径里的，行为没有变化
日志如上

**Comment by ABA2396** [comment]
> > 
> 
> 版本是4.0.0, 检测更新按钮提示已经是最新版本
> 
> 没注意task.json哪里获取，直接master上面拿？

去dev分支下的resource/task.json下下来替换下试试，照理来说不应该识别到其他东西来着

**Comment by bgli100** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8940863/asst.log)

dev分支的tasks.json，行为还是一致，未变化

**Comment by MistEO** [comment]
看起来是选了国际服？因为国际服都是英文的界面，会影响识别的

**Comment by bgli100** [comment]
对
这个设置想了想和识别关系很大，但是放在了启动设置里所以一开始没注意到

P.S. 不知道adb能不能获取前台包名决定识别方式？或者建议把这个设置单拿出来提前面一点
