### ISSUE TITLE
检测不到模拟器

### ISSUE THREAD

**Issue by The-gold-of-wind233** [MaaAssistantArknights/MaaAssistantArknights#9405]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

检测不到模拟器，之前是可以的，但今天中午的时候出现了问题，我就删了重下，重下了之后就检测不到模拟器了

### Version

Resource Version: 生路
UI Version: v5.4.0-beta.1
Core Version: v5.4.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15858116/asst.log)
[gui.log](https://github.com/user-attachments/files/15858117/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/169917985/4ad4aae6-ac50-4ee4-b604-53913a46c76e)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/169917985/705bf1f7-5bdd-4ece-98c4-8cdc074df881)

**Comment by ABA2396** [comment]
所以模拟器开了吗

**Comment by chisato2233** [comment]
所以模拟器开了吗
