### ISSUE TITLE
打肉鸽打久了cpu占用过高

### ISSUE THREAD

**Issue by ZERO-0123** [MaaAssistantArknights/MaaAssistantArknights#9406]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

打傀影肉鸽挂了几个小时，然后只要是战斗关卡中，cpu占用就会到99%
![0aa801ac-edd4-4040-b537-08bee53e0c6d](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61305814/2e203cc1-207a-4ac3-afdb-e3aa0690d6b4)

### Version

Resource Version: 生路UI Version: v5.4.0-beta.1Core Version: v5.4.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15858657/asst.log)
[gui.log](https://github.com/user-attachments/files/15858658/gui.log)
我发现的时间是22点左右

### 截图

![0aa801ac-edd4-4040-b537-08bee53e0c6d](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61305814/d4b8037c-0ce2-40df-aebe-a7269e33cf7c)

**Comment by ABA2396** [comment]
d6572b2c7e4e73070aa67728a85d19d676af5065 后支持使用 gpu
https://www.bilibili.com/opus/942868514035728392
