### ISSUE TITLE
生息演算任务出错

### ISSUE THREAD

**Issue by kal-yukari82** [MaaAssistantArknights/MaaAssistantArknights#9407]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

第一次使用生息演算，打开正常，进入关卡后显示任务出错，自动结束
<img width="635" alt="屏幕截图 2024-06-17 065928" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/173009608/774da243-105c-42cb-964a-3aad08f51ded">

### Version

Core Version: v5.4.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15860120/asst.log)
[gui.log](https://github.com/user-attachments/files/15860121/gui.log)

### 截图

<img width="635" alt="屏幕截图 2024-06-17 065928" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/173009608/1c1348a1-3af0-47e8-95bb-becd164afcd9">

### 还有别的吗？

版本	Windows 11 家庭中文版
版本号	23H2
安装日期	‎2023/‎6/‎14
操作系统版本	22631.3737
体验	Windows Feature Experience Pack 1000.22700.1009.0

处理器	AMD Ryzen 9 7940H w/ Radeon 780M Graphics        4.00 GHz
机带 RAM	16.0 GB (15.2 GB 可用)
设备 ID	ED5FF223-9AF0-4F7C-966F-C46F1A951107
产品 ID	00342-30983-82728-AAOEM
系统类型	64 位操作系统, 基于 x64 的处理器

mumu
V3.8.29（2972）

**Comment by ABA2396** [comment]
编队没删吧

**Comment by ZomSky** [comment]
兄弟，你需要自己开之前，单独进一次盐酸，把编队删了，再开MAA
