### ISSUE TITLE
对量化检测模型以降低硬件使用率的需求探讨

### ISSUE THREAD

**Issue by LoSealL** [MaaAssistantArknights/MaaAssistantArknights#9408]
### 说说你遇到的问题？

目前MAA使用的模型均为FP32，其中算力需求较大的为`deploy_direction_cls`和`operators_det`这两个模型。在使用CPU推理时，根据我的经验，其量化后大概能减少50%的算力需求，适合中低端笔记本在生息演算、肉鸽等频繁调用模型的场景。

而对于GPU推理，结论也成立，而且即使仅转为FP16模型，也能减少大概20%的算力。

**Comment by kpAjun** [comment]
在一些特别优化的显卡上这会不会有更大的性能提升？我之前也见到过很多FP32转FP16之后性能剧增的案例

**Comment by LoSealL** [comment]
> 在一些特别优化的显卡上这会不会有更大的性能提升？我之前也见到过很多FP32转FP16之后性能剧增的案例

的确会，但就是看这些corner-case值不值得来做了。不过FP32转FP16倒是非常容易，也不影响CPU推理（ORT的CPU EP会自动转回FP32）

**Comment by kpAjun** [comment]
到现在还没有大佬来看一下这个问题吗（）我这个渣渣先研究一下吧orz

**Comment by LoSealL** [comment]
> 到现在还没有大佬来看一下这个问题吗（）我这个渣渣先研究一下吧orz

看起来没什么需求，不太值得去做，能跑模拟器的都不是太弱的机器

**Comment by LoSealL** [comment]
至少没其他人来讨论=_=

**Comment by ABA2396** [comment]
cc @dantmnf

**Comment by kpAjun** [comment]
> 至少没其他人来讨论=_=

我这里是试着处理过了模型，但是手里没有数据集不太好做测试=_=，有空了上粥去多截一点图吧

**Comment by LoSealL** [comment]
[MaaTestSet](https://github.com/MaaAssistantArknights/MaaTestSet) 不过10个月没更新了……
