### ISSUE TITLE
MuMu截图增强功能使用出现问题

### ISSUE THREAD

**Issue by callmep** [MaaAssistantArknights/MaaAssistantArknights#9415]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用”MuMu截图增强功能”后MAA全部功能无效。
不启用该功能截图延迟高，虽然换班日常可以用但表示疑惑，毕竟电脑配置足够。

### Version

Resource Version: 生路
UI Version: v5.4.0-beta.1.d037.g98ecb301b
Core Version: v5.4.0-beta.1.d037.g98ecb301b

### 日志文件

复现了一次，上传日志，时间为2024/6/19 0:17
[gui.log](https://github.com/user-attachments/files/15889611/gui.log)
[asst.log](https://github.com/user-attachments/files/15889613/asst.log)

### 截图

<img width="600" alt="微信图片_20240618235945" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43133160/3e44effb-7ec5-41f6-be68-bf4ac196694c">
<img width="600" alt="微信图片_20240618235959" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43133160/ccdf008c-16ad-42bf-aa7f-aab57a96333b">
<img width="600" alt="微信图片_20240619000004" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43133160/7b9e9dcf-836b-4aaa-a930-3df1ef722469">
<img width="600" alt="微信图片_20240619001318" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43133160/187479ee-820d-4616-830f-bff7e7daba83">
<img width="600" alt="微信图片_20240619001437" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43133160/164a23a8-7cbf-4974-a089-47b5b10f4360">
<img width="600" alt="微信图片_20240619002334" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/43133160/9ff7b160-cb16-4b2c-b2ae-186868c704fd">

**Comment by Rbqwow** [comment]
首先 你没看文档 没正确处理后台保活 关了就好了

其次 有关mumu截图的问题有专门的issue模板

不过文档现在是有点乱 就快改好了

**Comment by FADURANE** [comment]
可以开后台保活，要正确设置屏幕编号
我的是mumu12 3.9.0 maa5.4.0-beta.2
假设舟是排在首页标签页后面，也就是第一个打开的应用，那MAA那边屏幕编号填2就行，正常运行，无需关闭保活
理论上屏幕编号按标签页顺序填就行，我没测试过

**Comment by Rbqwow** [comment]
最开始我们都是这么想的 实际测试没法用
可以从开始唤醒试一次

**Comment by callmep** [comment]
> 可以开后台保活，要正确设置屏幕编号 我的是mumu12 3.9.0 maa5.4.0-beta.2 假设舟是排在首页标签页后面，也就是第一个打开的应用，那MAA那边屏幕编号填2就行，正常运行，无需关闭保活 理论上屏幕编号按标签页顺序填就行，我没测试过

感谢回复，我把实例编号设为0，屏幕编号设为2后成功运行了截图增强功能，截图耗时也进入了50ms以内

**Comment by FADURANE** [comment]
> > 可以开后台保活，要正确设置屏幕编号 我的是mumu12 3.9.0 maa5.4.0-beta.2 假设舟是排在首页标签页后面，也就是第一个打开的应用，那MAA那边屏幕编号填2就行，正常运行，无需关闭保活 理论上屏幕编号按标签页顺序填就行，我没测试过
> 
> 感谢回复，我把实例编号设为0，屏幕编号设为2后成功运行了截图增强功能，截图耗时也进入了50ms以内

我偶尔出现截图变回普通截图的情况，重启模拟器即可解决
顺带一提我最近出现干员无法正确部署的情况，我不确定是不是增强截图的问题，重启maa后就消失了，maa在出现这个bug之后连续开了好几把肉鸽，然后全在第一关探索失败，因为重启软件就解决了，我没有单独开issue，如果你使用增强截图也出现此类问题，请回复我

**Comment by callmep** [comment]
我主要的使用场景，是利用开机自启动配合插线板定时开机，来完成换班和刷理智的自动化操作。对截图速度的要求其实并不高，顶多就一月一次的保全代打和心血来潮的肉鸽刷钱。因开起增强功能后还未尝试肉鸽与保全，故对干员无法部署情况尚不知情。


在今早的实例运行时我也出现了变回普通截图的情况（截图时间又掉到了400ms，因为还能用，也就没在意）。您所说的重启解决法应该能完全满足我的使用需求。本人代码能力较薄弱，没有去细看代码或研究日志，若您的问题频繁出现且影响使用体验，建议单独开issue提问。


再次感谢你提供的帮助



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月3日(周三) 上午8:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] MuMu截图增强功能使用出现问题 (Issue #9415)




   
可以开后台保活，要正确设置屏幕编号 我的是mumu12 3.9.0 maa5.4.0-beta.2 假设舟是排在首页标签页后面，也就是第一个打开的应用，那MAA那边屏幕编号填2就行，正常运行，无需关闭保活 理论上屏幕编号按标签页顺序填就行，我没测试过
  
感谢回复，我把实例编号设为0，屏幕编号设为2后成功运行了截图增强功能，截图耗时也进入了50ms以内
  
我偶尔出现截图变回普通截图的情况，重启模拟器即可解决
 顺带一提我最近出现干员无法正确部署的情况，我不确定是不是增强截图的问题，重启maa后就消失了，maa在出现这个bug之后连续开了好几把肉鸽，然后全在第一关探索失败，因为重启软件就解决了，我没有单独开issue，如果你使用增强截图也出现此类问题，请回复我
