### ISSUE TITLE
部分作业集“不支持的关卡，请检查关卡名.....或尝试更新资源版本”

### ISSUE THREAD

**Issue by KissshotAH** [MaaAssistantArknights/MaaAssistantArknights#9416]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

朋友出现的问题，这次ex关的作业集都用不了，普通关的能用
采取的措施包括：
1.按公告要求，在命令行里输入指令下载安装运行库
2.重新安装maa
3.多个作业集文件尝试
4.软件已更新到最新版本，maa设置与能正常使用的机器保持一致

### Version

Resource Version: 生路
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

没有联系上当事人...后续摸鱼时间看看能不能找朋友要到
点击自动战斗页面的【开始】后出现问题

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/171537698/c3688023-9536-427c-97a4-968f13382ebd)

### 还有别的吗？

模拟器为mumu12，其他方面使用正常
系统win11

**Comment by hundun000** [comment]
我也遇到了类似问题。

观察到`gui.log`有
> HTTP: NotFound GET https://s3.maa-org.net:25240/maaassistantarknights/MaaAssistantArknights/MaaAssistantArknights/resource/Arknights-Tile-Pos/act34side_ex01#f#-activities-act34side-level_act34side_ex01.json

用浏览器访问该链接亦为404。而上一步网络获取的`dynamic_list.txt`中含有该json路径无误。

**Comment by Constrat** [comment]
- No logs
- Not the latest beta version

Update to the latest nightly, retry. If issue persists, reopen

**Comment by ABA2396** [comment]
> 我也遇到了类似问题。
> 
> 观察到`gui.log`有
> 
> > HTTP: NotFound GET [s3.maa-org.net:25240/maaassistantarknights/MaaAssistantArknights/MaaAssistantArknights/resource/Arknights-Tile-Pos/act34side_ex01#f#-activities-act34side-level_act34side_ex01.json](https://s3.maa-org.net:25240/maaassistantarknights/MaaAssistantArknights/MaaAssistantArknights/resource/Arknights-Tile-Pos/act34side_ex01#f#-activities-act34side-level_act34side_ex01.json)
> 
> 用浏览器访问该链接亦为404。而上一步网络获取的`dynamic_list.txt`中含有该json路径无误。

\# 照理来说是会替换成 %23 的，没搞懂为什么还会去找这个，不过新版本改了下
