### ISSUE TITLE
点击“Link Start”后MAA有概率无响应

### ISSUE THREAD

**Issue by TimCrownie** [MaaAssistantArknights/MaaAssistantArknights#9418]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

似乎是在更新至最近数个内测版本后随机出现的，表现为点击“Link Start”后MAA有概率无响应，过一段时间（数秒至数十秒）后可自行恢复，无法稳定复现。
猜测是在同时打开多个MAA后的资源调用问题？

### Version

Resource Version: Il Siracusano - Retrospection
UI Version: v5.4.0-beta.1.d037.g98ecb301b
Core Version: v5.4.0-beta.1.d037.g98ecb301b

### 日志文件

[asst.log](https://github.com/user-attachments/files/15895829/asst.log)
[gui.log](https://github.com/user-attachments/files/15895834/gui.log)
PS. 由于是多开MAA，日志应该会很乱。

### 截图

抓取了一段不太完整的录屏（发病前期未录制到）

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63519560/0b931d2f-34df-416b-8aaf-ae02216a1d4c

### 还有别的吗？

模拟器：雷电模拟器国际版1.2.52
操作系统：Windows 10 Pro 22H2
配置：Intel Core i7-13700H+16GB RAM+RTX 4060 Laptop

**Comment by ABA2396** [comment]
不是日志应该会很乱，是根本存不下来日志

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f332b8a1-f3e0-41c9-b069-ab245fcddc15)

**Comment by TimCrownie** [comment]
> 不是日志应该会很乱，是根本存不下来日志
草 原来（

**Comment by TimCrownie** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/341054796-f332b8a1-f3e0-41c9-b069-ab245fcddc15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MTY3MTIsIm5iZiI6MTcxODgxNjQxMiwicGF0aCI6Ii85OTA3Mjk3NS8zNDEwNTQ3OTYtZjMzMmI4YTEtZjNlMC00MWM5LWIwNjktYWIyNDVmY2RkYzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE3MDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNDBmMWUyN2YwYzBjZDgyNjYyZDJkYjY3YTA5Y2Q2YjBiMjlkM2M1OGM0MTg0NzI2NTYxNWEwNmNiMjAwYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EFzkKGZn9LUr2mKmFPrc-3MdejpxcmntyZdX-DzYwEs)

好的
之前没问题应该只是MAA在硬撑吧（不是

**Comment by TimCrownie** [comment]
Update:
在关闭GPU加速后似乎解决了该问题？需要进一步测试。
