### ISSUE TITLE
挂在后台的MAA被Ctrl+C异常唤起

### ISSUE THREAD

**Issue by fatefate0727** [MaaAssistantArknights/MaaAssistantArknights#9419]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

这个问题已经有很长一段时间
具体表现为：
        1.下午15点到17点左右
        2.操作电脑使用Ctrl+C复制快捷键时有概率唤起MAA主面板，并且原本的复制操作未完成
        3.此时最小化主面板后再次使用Ctrl+C快捷键将重复以上【2】出现的问题
        4.大概在重复2-4次之后，再次使用Ctrl+C快捷键将会在鼠标指向位置出现电脑托盘MAA右键菜单，且该菜单仅能通过点击电脑托盘MAA图标隐藏
很可惜的是，MAA的debug中日志文件没有该时间段的记录，电脑事件查看器中也没有找到问题。
我的设备最近进行过重置，清除了所有数据，基本可以保证是全新的系统，MAA也是重新下载的，但在今日依旧出现该问题。

### Version

Resource Version: 生路
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/15897697/gui.log)
[asst.log](https://github.com/user-attachments/files/15897700/asst.log)

### 还有别的吗？

版本	Windows 10 专业版
版本号	22H2
安装日期	‎2024/‎6/‎16
操作系统内部版本	19045.4529
体验	Windows Feature Experience Pack 1000.19058.1000.0

BlueStacks 5
5.21.210.1023 P64

**Comment by ABA2396** [comment]
太抽象了，设置里的热键设置有设过吗

**Comment by fatefate0727** [comment]
> 太抽象了，设置里的热键设置有设过吗

没有，我这边不使用热键，一直是默认的。我甚至想要有个关闭热键的开关

**Comment by ABA2396** [comment]
热键全删光就是关闭

**Comment by fatefate0727** [comment]
> 热键全删光就是关闭

好的，我再观察一段时间
