### ISSUE TITLE
肉鸽-新关卡死斗的摆放+奶妈试图奶羽毛笔

### ISSUE THREAD

**Issue by Cymxx** [MaaAssistantArknights/MaaAssistantArknights#942]
肉鸽第一层死斗里面，歌姬可能刷到家门口上方的岩浆地砖上，MAA放置干员到家门口时会被歌姬打，进而晕倒或死亡，导致大面积漏怪；MAA会试图用奶妈奶羽毛笔等绝食干员
![MUHYYHY}8(%E%9CL92}ABUK](https://user-images.githubusercontent.com/107874479/174640468-85eed55f-a597-4420-a008-ae896d2366cd.png)

**Comment by WWPXX233** [comment]
修地图啦关
