### ISSUE TITLE
未知问题

### ISSUE THREAD

**Issue by Yingge02** [MaaAssistantArknights/MaaAssistantArknights#9422]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
TimeSpan 周期必须大于或等于零。 (Parameter 'value')
解决方案
出现未知错误
详细信息
System.ArgumentOutOfRangeException: TimeSpan 周期必须大于或等于零。 (Parameter 'value')
   at System.Windows.Threading.DispatcherTimer.set_Interval(TimeSpan value)
   at MaaWpfGui.Main.AsstProxy.ProcTaskChainMsg(AsstMsg msg, JObject details)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

Resource Version: 生路
UI Version: v5.4.0-beta.1
Core Version: v5.4.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15903968/asst.log)
[gui.log](https://github.com/user-attachments/files/15903969/gui.log)

**Comment by Yingge02** [comment]
补充：
猜想是否和理智恢复周期的值有关，因为该错误可复现，如：当理智为满，设置刷理智连战使用的总理智大于已有理智，且备选关卡设置为“不选择”，此时会出现“任务完成，理智将在XXXX-XX-XX后回满（0h 0m后）”。
“TimeSpan 周期必须大于或等于零。 (Parameter 'value')”里的TimeSpan是否为“0h0m”的值？
![F172BC4B85966D5E2C0A34190EBC9E8B](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76812811/a4e446ab-db6a-48d0-aaf5-8cece9fc0e6b)
![A0C046875FD6D6F887AAEF056BE5F800](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/76812811/7a424ebd-2556-4b37-8a38-8f21622b817f)

**Comment by ABA2396** [comment]
b1ecfd83042e2c68dac2dadbcb026517a72253a9 fixed
