### ISSUE TITLE
startup无法进行，一直任务错误

### ISSUE THREAD

**Issue by Chenyinlin-Yiking** [MaaAssistantArknights/MaaAssistantArknights#9424]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

maa截图无法完成startup，然后就会出现一直识别错误。

### Version

Core Version: v5.3.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/15907125/gui.log)

[asst.log](https://github.com/user-attachments/files/15907131/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75869957/aca71dba-f50c-4a51-b759-508ec7f254a3)

**Comment by Chenyinlin-Yiking** [comment]
不只是这个，后面的都有问题，基建换班，结果跑去抽卡，6
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75869957/a41ecc06-e709-4887-906c-74f8d25f1450)

**Comment by Lemon-miaow** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/61692393/7b0b2613-97c8-4774-ac2f-1a0715d28216)
识别到的似乎是广告（

**Comment by ABA2396** [comment]
开了后台保活吧

**Comment by Chenyinlin-Yiking** [comment]
是开了后台，所以问题是出在哪里，没明白

**Comment by Chenyinlin-Yiking** [comment]
> 开了后台保活吧

是开了后台，所以请问，问题是出在哪里，不是很明白

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/53d062f5-e728-4c8e-840d-4869a750555a)
开的时候没看提示吗

**Comment by Chenyinlin-Yiking** [comment]
> ![image](https://private-user-images.githubusercontent.com/61692393/341280615-7b0b2613-97c8-4774-ac2f-1a0715d28216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjgyNjgsIm5iZiI6MTcxODg2Nzk2OCwicGF0aCI6Ii82MTY5MjM5My8zNDEyODA2MTUtN2IwYjI2MTMtOTdjOC00Nzc0LWFjMmYtMWEwNzE1ZDI4MjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA3MTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMmY5N2VlNzUxMWQ0ZmI1MjJlMmNmODk4ODJhNTYyN2NiMTAxY2Y2OGIzY2QyY2EwMjE3OTRkMWVjNDZmZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o4KVejLU2XsO7uf-Y2wp8fA5_ZmnEhN_msGl8KA56Ak) 识别到的似乎是广告（

其实很有意思，我开了maa里面那个mumu12增强截图模式，关了就啥事没有

**Comment by Chenyinlin-Yiking** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/341312096-53d062f5-e728-4c8e-840d-4869a750555a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Njg1MjEsIm5iZiI6MTcxODg2ODIyMSwicGF0aCI6Ii85OTA3Mjk3NS8zNDEzMTIwOTYtNTNkMDYyZjUtZTcyOC00YzhlLTg0MGQtNDg2OWE3NTA1NTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA3MjM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwODE4NjgzODY2OTMyNzY4YWNmMDllODMzYzY1NGI1OWZiZGZkZDk1NGNmMThkMjkxYjE0ZjE3ZGI5MjA1YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ffyn6vPsEul4vUrb6yq7nMy-i5Q5fckDhCavax9Cj8s) 开的时候没看提示吗

我按照要求填写了，但还是出问题

**Comment by ABA2396** [comment]
adb截图是根据顶层窗口来的。截图增强是mumu提供的接口，开了后台保活之后你填第几个窗口给的就是第几个窗口的图，你填的0给的就是桌面，谁知道你方舟是在第几个窗口

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/40571f7b-705e-4074-b9ff-3715f850e576)

**Comment by ABA2396** [comment]
后台保活是给多标签用的，和放后台有什么关系，合着maa和mumu的提示都没看啊

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/d01aab0a-4bc9-45bf-a8e0-707674f40a40)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/1e039038-3875-4ec1-a959-fd64f5f50e21)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f852027d-1c42-41b7-a186-952131120ca6)

**Comment by Chenyinlin-Yiking** [comment]
> 后台保活是给多标签用的，和放后台有什么关系，合着maa和mumu的提示都没看啊

我不知道什么后台保活，我的意思只是我只会把maa和mumu最小化放后台他们自己跑，至于我现在开了多少个窗口我鬼知道，填哪个窗口编号还要自己根据窗口个数来决定，这功能我关了不用就是了

**Comment by Chenyinlin-Yiking** [comment]
> 后台保活是给多标签用的，和放后台有什么关系，合着maa和mumu的提示都没看啊

我不知道什么后台保活，我的意思只是我只会把maa和mumu最小化放后台他们自己跑，至于我现在开了多少个窗口，每次都不一样，填哪个窗口编号还要自己根据窗口个数来决定，我也不放在顶层。这功能我关了不用就是了
