### ISSUE TITLE
进行自动公招时经常识别错误，多次返回主界面或误点击停止招募

### ISSUE THREAD

**Issue by rainRb** [MaaAssistantArknights/MaaAssistantArknights#9425]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及
- [X] 我正在使用最新的 MAA 内测版本和最新的**官版** MuMu 模拟器
- [X] 我已参考文档确定安装路径、实例编号、屏幕编号填写正确，并确认在关闭截图增强模式后问题消失
- [ ] 我未开启高帧率模式，且显存使用策略为“画面表现更好”
- [ ] 我正在使用后台保活功能，并确定该问题仅在开启后台保活时出现

### 问题描述

当进行自动公招时经常识别错误，多次返回主界面或误点击停止招募，有时会导致任务无法进行。具体请看视频

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97787236/e3fc98ba-f54c-4720-a958-c3cfa46b2636

 

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97787236/f6a5260b-9266-47df-a154-5da9f74ef554

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97787236/27c11a47-4b42-435a-b834-ea13b5e3b1fd

### Version

Resource Version: 生路
UI Version: v5.3.1
Core Version: v5.3.1
mumu版本：V3.8.30（3010）

### MAA 日志文件

[asst.log](https://github.com/user-attachments/files/15911907/asst.log)
[gui.log](https://github.com/user-attachments/files/15911908/gui.log)

时间大约在2024/6/20 17:00之后

### MuMu 问题诊断

基础信息
UUID :  fe8a8440-194f-42ed-9cc3-a8964d9bb64c
模拟器版本 :  3.8.30.3010
模拟器磁盘（可用/总）空间 :  101.3GB/125GB
日志路径 :  C:\Program Files\Netease\MuMuPlayer-12.0\vms\MuMuPlayer-12.0-0\logs\

运行环境
VT :  开启
Hyper-V :  关闭
网络环境检测 :  正常
以管理员运行方式 :  否
DirectX 11是否安装 :  是
防火墙 :  关闭

电脑配置
主板型号 :  Manufacturer: ASUSTeK COMPUTER INC.  Product: FX507VV
CPU :  13th Gen Intel(R) Core(TM) i7-13700H
系统版本 :  Windows 11 64-bit Kernel 10.0.22631
显卡驱动 :  正常
显卡驱动型号 :  551.86 (20240312)
所有显卡 :  NVIDIA GeForce RTX 4060 Laptop GPU  |  Intel(R) Iris(R) Xe Graphics  |  Microsoft Basic Render Driver
当前使用显卡 :  NVIDIA GeForce RTX 4060 Laptop GPU
安装磁盘(可用/总)空间 :  224.1GB/1880.2GB
可用内存/总内存 :  16.5GB/31.6GB

模拟器设置
Root :  开启
显卡渲染模式 :  Vulkan 模式（独家）
性能设置 :  6核/12GB
手机型号 :  vivo IQOO 10 Pro
分辨率 :  1280 * 720
高帧率 :  开启
后台保活 :  关闭

连接设备
音频输入 :  已连接
音频输出 :  已连接

网络信息
MuMu DNS :  192.168.66.1
电脑DNS :  192.168.66.1
Rom MAC地址 :  08:5a:5c:2f:e0:00

ADB调试端口 :  16384
MuMu出口IP地址 :  10.0.2.15
电脑出口IP地址 :  ***.***.***.***（已隐去）
其它信息
其它版本信息 :  vm: 120.1.68.009 hyperv: 6.3.19.0 renderer: 0.0.176.0
Vendor :  NetEase
OpenGL Renderer :  MuMu GL (Vulkan 1.3.277 NVIDIA GeForce RTX 4060 Laptop GPU 551.86 _A_)
OpenGL Version :  OpenGL ES 3.2 V132
运行时间 :  1 : 36 : 16

### 截图

![MuMu12-20240620-174751](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97787236/b54bc647-63f0-4de8-abbf-8cd7783f3f5d)
![MuMu12-20240620-174806](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/97787236/d16f4836-8d6b-4687-b37f-3e70651b0ff3)

### 还有别的吗？

设备名称	Ruike4
处理器	13th Gen Intel(R) Core(TM) i7-13700H   2.40 GHz
机带 RAM	32.0 GB (31.6 GB 可用)
设备 ID	C03BE6E0-57CE-4948-AD5F-8ADB7E91439B
产品 ID	00330-80000-00000-AA031
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

版本	Windows 11 专业版
版本号	23H2
安装日期	‎2023/‎6/‎4
操作系统版本	22631.3737
体验	Windows Feature Experience Pack 1000.22700.1009.0

GPU：NVIDIA GeForce RTX 4060 Laptop GPU

天选4

**Comment by Rbqwow** [comment]
已知问题 高帧率导致maa截到了多出来的过渡动画的帧 如果不想更新内测版就先关一下

内测版加了截图延迟 *或许*解决了这个问题 但还没有实际测试

**Comment by rainRb** [comment]
> 已知问题 高帧率导致maa截到了多出来的过渡动画的帧 如果不想更新内测版就先关一下
> 
> 内测版加了截图延迟 _或许_解决了这个问题 但还没有实际测试
> 
> ~2k屏开720p 还开高帧 这什么似玩非玩的玩法~

感谢回复~
开720p是因为baas（一个碧蓝档案脚本）的要求，这个脚本不支持其他分辨率，最近没怎么好好玩所以也就没调，自己打的时候就调回2k了）

**Comment by Rbqwow** [comment]
> > 已知问题 高帧率导致maa截到了多出来的过渡动画的帧 如果不想更新内测版就先关一下
> > 
> > 内测版加了截图延迟 _或许_解决了这个问题 但还没有实际测试
> > 
> > ~2k屏开720p 还开高帧 这什么似玩非玩的玩法~
> 
> 感谢回复~
> 开720p是因为baas（一个碧蓝档案脚本）的要求，这个脚本不支持其他分辨率，最近没怎么好好玩所以也就没调，自己打的时候就调回2k了）

但是baas早就支持高分16:9了 只支持720p的是baah(

**Comment by rainRb** [comment]
> 已知问题 高帧率导致maa截到了多出来的过渡动画的帧 如果不想更新内测版就先关一下
> 
> 内测版加了截图延迟 _或许_解决了这个问题 但还没有实际测试
> 
> ~2k屏开720p 还开高帧 这什么似玩非玩的玩法~

emm我截图
开720p是因为baas（一个碧蓝档案脚本）的要求，这个脚本不支持其他分辨率，最近没怎么好好玩所以也就没调，自己打的时候就调回2k了）

> > > 已知问题 高帧率导致maa截到了多出来的过渡动画的帧 如果不想更新内测版就先关一下
> > > 内测版加了截图延迟 _或许_解决了这个问题 但还没有实际测试
> > > ~2k屏开720p 还开高帧 这什么似玩非玩的玩法~
> > 
> > 
> > 感谢回复~
> > 开720p是因为baas（一个碧蓝档案脚本）的要求，这个脚本不支持其他分辨率，最近没怎么好好玩所以也就没调，自己打的时候就调回2k了）
> 
> 但是baas早就支持高分16:9了 只支持720p的是baah(

啊？感情我委屈自己好几个月啥意义没有了...
以及还有一点网卡了没发出来，我录像的时候模拟器貌似是30帧诶 我去试一下关了高帧率还好使吗

**Comment by rainRb** [comment]
好吧开60帧确实好使，我以为动态调整帧率到30之后就不用考虑高帧率的问题来着
