### ISSUE TITLE
台服萨米肉鸽无法运行

### ISSUE THREAD

**Issue by bwkdbewkhbiwk** [MaaAssistantArknights/MaaAssistantArknights#9428]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

会一直 主界面，肉鸽，主界面，肉鸽循环，不会报错但是什么都没干。

### Version

v5.3.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15913065/asst.log)
[asst.bak.log](https://github.com/user-attachments/files/15913068/asst.bak.log)

没找到gui.log

### 截图

<img width="1023" alt="Screenshot 2024-06-20 at 23 45 16" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153872940/07806655-b810-486d-809f-73c7e38788f6">
<img width="741" alt="Screenshot 2024-06-20 at 23 45 27" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153872940/0fefc523-1d2f-4dfc-92ad-d0d7d8d1433b">
<img width="978" alt="Screenshot 2024-06-20 at 23 47 39" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153872940/673bcde4-0df1-474c-bfd5-e7ed5b6bde2b">

<img width="978" alt="Screenshot 2024-06-20 at 23 47 45" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153872940/6c0c4a13-9801-4e78-a7f3-70b600938a3d">
<img width="978" alt="Screenshot 2024-06-20 at 23 47 58" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153872940/dfc1662b-b583-407f-9154-31f58522847c">
<img width="978" alt="Screenshot 2024-06-20 at 23 48 06" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/153872940/fcbc49a7-b1ca-4b1f-9b45-2ad67b3d49aa">

进了过后就会退出会主界面，然后重新开始

**Comment by momomochi987** [comment]
兄弟別急 在做了在做了🫠

**Comment by yatayork** [comment]
> ### 在提问之前...
> * [x]  我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
> * [x]  我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
> * [x]  我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
> * [x]  我已检查了置顶议题（pinned issue），确认我的问题未被提及
> 
> ### 问题描述
> 会一直 主界面，肉鸽，主界面，肉鸽循环，不会报错但是什么都没干。
> 
> ### Version
> v5.3.1
> 
> ### 日志文件
> [asst.log](https://github.com/user-attachments/files/15913065/asst.log) [asst.bak.log](https://github.com/user-attachments/files/15913068/asst.bak.log)
> 
> 没找到gui.log
> 
> ### 截图
> <img alt="Screenshot 2024-06-20 at 23 45 16" width="1023" src="https://private-user-images.githubusercontent.com/153872940/341397347-07806655-b810-486d-809f-73c7e38788f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MDk5OTMsIm5iZiI6MTcxODkwOTY5MywicGF0aCI6Ii8xNTM4NzI5NDAvMzQxMzk3MzQ3LTA3ODA2NjU1LWI4MTAtNDg2ZC04MDlmLTczYzdlMzg3ODhmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQxODU0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDkzOWFjYjVjOTkzYWFlN2ViMzBmN2I5OTllNDdlYWMzNDg0ZGUxYzkxNWNmNDNlMmNlZGUyNjRmOWE0NTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cLVkBQgscSn-viHclUD0e2wHmloiGbnKMbsAIkAO2NY"> <img alt="Screenshot 2024-06-20 at 23 45 27" width="741" src="https://private-user-images.githubusercontent.com/153872940/341397405-0fefc523-1d2f-4dfc-92ad-d0d7d8d1433b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MDk5OTMsIm5iZiI6MTcxODkwOTY5MywicGF0aCI6Ii8xNTM4NzI5NDAvMzQxMzk3NDA1LTBmZWZjNTIzLTFkMmYtNGRmYy05MmFkLWQwZDdkOGQxNDMzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQxODU0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OThmMTZiNDk1MWYyMTAwNTYyMGE4N2JhYTlhOWM5OWQ1N2M3MmU3ODA3NjhmYjY1NjhhY2ZlZDc3OGIyZjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZdRfwTN4DFuMwUwGnYAdlLkNw1poC4K4lepv5wLdQXU"> <img alt="Screenshot 2024-06-20 at 23 47 39" width="978" src="https://private-user-images.githubusercontent.com/153872940/341398006-673bcde4-0df1-474c-bfd5-e7ed5b6bde2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MDk5OTMsIm5iZiI6MTcxODkwOTY5MywicGF0aCI6Ii8xNTM4NzI5NDAvMzQxMzk4MDA2LTY3M2JjZGU0LTBkZjEtNDc0Yy1iZmQ1LWU3ZWQ1YjZiZGUyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQxODU0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWQ5MTIzMTgwNDc1MTY0N2NmZjIzOTc0MjE4ZDM0OTcyODNjMmMwYTM2M2ZkNjNlYTNjNWNlYjg5YmU3ZjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v4JAXmt2HXjFWw8l1vf1gJKnChPvjwlXXdMsHyu20Ao"> <img alt="Screenshot 2024-06-20 at 23 47 45" width="978" src="https://private-user-images.githubusercontent.com/153872940/341398049-6c0c4a13-9801-4e78-a7f3-70b600938a3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MDk5OTMsIm5iZiI6MTcxODkwOTY5MywicGF0aCI6Ii8xNTM4NzI5NDAvMzQxMzk4MDQ5LTZjMGM0YTEzLTk4MDEtNGU3OC1hN2YzLTcwYjYwMDkzOGEzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQxODU0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDlkNTc5YjZiZmY2YzZjNDMyMjM3OGU1OTBiOWE0YjkxNDUyYjlhMDQyNzZhODM0MTM5MzExMmY1MWQ0ODdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GNOf0KEhn54sA61mMz9ML75p0-5_RJdB2ISs953XzrM"> <img alt="Screenshot 2024-06-20 at 23 47 58" width="978" src="https://private-user-images.githubusercontent.com/153872940/341398104-dfc1662b-b583-407f-9154-31f58522847c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MDk5OTMsIm5iZiI6MTcxODkwOTY5MywicGF0aCI6Ii8xNTM4NzI5NDAvMzQxMzk4MTA0LWRmYzE2NjJiLWI1ODMtNDA3Zi05MTU0LTMxZjU4NTIyODQ3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQxODU0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWNmNjdiNTI0ZDgwODViYTdmYjgyMDI1YTBkNjkwODY2YTY1OTM3MzI1YTNhOWEzODFjNDM1NGUwOWFiZDYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NqjrdTll9zoztC5v_q--7sqTzAgJ-jkYvqeIcLxNiQQ"> <img alt="Screenshot 2024-06-20 at 23 48 06" width="978" src="https://private-user-images.githubusercontent.com/153872940/341398160-fcbc49a7-b1ca-4b1f-9b45-2ad67b3d49aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MDk5OTMsIm5iZiI6MTcxODkwOTY5MywicGF0aCI6Ii8xNTM4NzI5NDAvMzQxMzk4MTYwLWZjYmM0OWE3LWIxY2EtNGIxZi05YjQ1LTJhZDY3YjNkNDlhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQxODU0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjM5Yjc3YWRjNjM2ZDQzYWJiYzdkNWQ3NDFlMDA1NTg3OTgyMjNmNDhiM2ZjMWE5YTk1NjdhZDU1NmEwNjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.atkIMapMCUK1CKIrHtym1nsDPr50khZXPLbzNVmrbOg">
> 进了过后就会退出会主界面，然后重新开始
> 
> ### 还有别的吗？
> _No response_

看了global 裡txwy裡的task.json基本上是沒有，基本就到傀影跟水月而已
當初水月王關畫面"打贏後結尾畫面的辨識"也是有問題的 不過我當初是沒打王沒差只刷等級就去改task.json讓他boss關就Exit掉
就不用擔心卡在打贏畫面了

薩米就像上面的貢獻者兄弟說的還在做 等著
可以先看一下官網的教學去抓roi跟圖整理到裡面再去看看有甚麼問題先在本機上試也行
主要是 <獲得"驚訝"等等的那個畫面>與<一開始選角完後的"探索冰原">和<"最後結局(風雪蔽目)">等等畫面可能要重抓畫面
打boss 打一般關卡 拿資源選項倒是沒有出現過問題(基本上不是識別字的都還好) 
應該主要是出在字體識別出錯 或者roi不在正確位置 可以自己修改試試 
有修出不錯的東西 再PR也行

**Comment by samreproduction** [comment]
還有發現在進入不期而遇 “吉兆” 事件時，會不斷點下面兩個選項但不會完成事件。

**Comment by momomochi987** [comment]
> 還有發現在進入不期而遇 “吉兆” 事件時，會不斷點下面兩個選項但不會完成事件。

嗨

有 log 檔可以提供嗎？

再找時間來看看是什麼問題

**Comment by Meowmeowbenze** [comment]
我的情况是会卡在开始界面不进去
<img width="1440" alt="image" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/173524446/d3f05e7c-806e-4859-b63d-53e56dc2c1d0">
过一会之后maa会自动退出然后结束这次探索 可能是识别到问题了（？）

**Comment by momomochi987** [comment]
[Meowmeowbenze](https://github.com/Meowmeowbenze)

把 '你的 MAA 資料夾\resource\global\txwy\resource\template' 中的 Sami@Roguelike@EnterAfterRecruit.png 移除
讓他用陸服那邊的圖片試試?
看看會不會還有同樣問題

**Comment by yatayork** [comment]
> 我的情况是会卡在开始界面不进去 <img alt="image" width="1440" src="https://private-user-images.githubusercontent.com/173524446/341928262-d3f05e7c-806e-4859-b63d-53e56dc2c1d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMzIwMjYsIm5iZiI6MTcxOTAzMTcyNiwicGF0aCI6Ii8xNzM1MjQ0NDYvMzQxOTI4MjYyLWQzZjA1ZTdjLTgwNmUtNDg1OS1iNjNkLTUzZTU2ZGMyYzFkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQwNDQ4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjZlYWYwODViZGU2N2UyNzQ5ZjMyMGNjZjI1ZGU4YTQyMTM5MGIzZjlhNDUxNTUyMmY1NjcyYzJjYjEzMDJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IHlD1_8rQ2Ua9_nuE52gdn03g2vXygPM1hgpolP5mQ8"> 过一会之后maa会自动退出然后结束这次探索 可能是识别到问题了（？）

我的情況在使用公測板之後除了特定某一關不會放角色之外其他都沒什麼問題了

忘記那關叫啥 不過那關只有最下面那兩排可以放 第二排只有最右邊可以放一隻的關卡

**Comment by Meowmeowbenze** [comment]
> [Meowmeowbenze](https://github.com/Meowmeowbenze)
> 
> 把 '你的 MAA 資料夾\resource\global\txwy\resource\template' 中的 Sami@[Roguelike@EnterAfterRecruit.png](mailto:Roguelike@EnterAfterRecruit.png) 移除 讓他用陸服那邊的圖片試試? 看看會不會還有同樣問題

感谢回复）尝试了一下但是不太会，不过重装了楼上说的公测版 现在没问题了🤔👍

**Comment by samreproduction** [comment]
> > 還有發現在進入不期而遇 “吉兆” 事件時，會不斷點下面兩個選項但不會完成事件。
> 
> 嗨
> 
> 有 log 檔可以提供嗎？
> 
> 再找時間來看看是什麼問題

請問要什麼log 檔

**Comment by momomochi987** [comment]
> 請問要什麼log 檔

就是你發生 「吉兆」 這個事件卡住的時候，
debug 資料夾裡面的 asst.log 跟 gui.log

但我今天用 v5.4.0-beta2 這個版本掛了一個早上，
遇到的「吉兆」都沒有發生你說的問題，
我覺得可以再觀察看看。

如果有再遇到的話可以再提新的 issue 出來~
