### ISSUE TITLE
选了吃一个理智药后任务被按顺序重复执行

### ISSUE THREAD

**Issue by hckkk** [MaaAssistantArknights/MaaAssistantArknights#943]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8944865/asst.log)
选了吃一个理智药以后的任务逻辑好像有问题，先全部任务执行了一边以后又执行了一遍所有任务（这次吃了理智药）

**Comment by MistEO** [comment]
你是不是点了开始马上又点了停止，接着又点了开始。现在这块的同步逻辑有点小问题，没加锁，不能这么玩的。

**Comment by hckkk** [comment]
很有可能，我点了开始以后想到用一个理智药然后可能手速快了，趁他不注意加了一个理智药
