### ISSUE TITLE
【新功能】材料的图形化展示，库存管理和合成

### ISSUE THREAD

**Issue by Kaminingyo** [MaaAssistantArknights/MaaAssistantArknights#9430]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

玩太空工程师玩的.jpg 有没有考虑过制定一个材料库存计划表？就是每种材料都有一个期望数量，小于这个阈值就会自动从下级材料合成（绿蓝紫石头）或者消耗体力刷关卡获取（1-7），大于这个数量就会被优先转化成其他材料（或者不消耗它）。最后再把材料缺口展示出来，显示还差多少。

### 有什么好的想法？

从仓库识别材料已经有了，基建排班也有，合成材料的干员优先级也可以排。

### 其他内容

期望MAA造福更多人

**Comment by Constrat** [comment]
Out of scope
