### ISSUE TITLE
公招完成后在该界面停止了一分钟，而没有进行下一个任务。推测可能是重复上报企鹅物流失败导致的。

### ISSUE THREAD

**Issue by Windsland52** [MaaAssistantArknights/MaaAssistantArknights#9431]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

公招完成后在该界面停止了一分钟，而没有进行下一个任务。推测可能是重复上报企鹅物流失败导致的。

### Version

Resource Version: 生路
UI Version: v5.4.0-beta.1.d037.g98ecb301b
Core Version: v5.4.0-beta.1.d037.g98ecb301b

### 日志文件

[asst.bak.log](https://github.com/user-attachments/files/15923464/asst.bak.log)
[gui.log](https://github.com/user-attachments/files/15923495/gui.log)

### 截图

![屏幕截图 2024-06-21 135929](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/86581225/ca30ad68-72bb-44d4-be7b-a5aa341861fd)

### 还有别的吗？

无

**Comment by ABA2396** [comment]
确实，虽然上报是异步的，但也是在单个任务内（公招）异步，下一个任务还是得等完才会跑

**Comment by ntgmc** [comment]
> 确实，虽然上报是异步的，但也是在单个任务内（公招）异步，下一个任务还是得等完才会跑

我现在也是 运行完一个任务之后要想一分钟才开始下一个

**Comment by ABA2396** [comment]
是不是因为一图流服务器炸了？我去问问

**Comment by ABA2396** [comment]
好像是企鹅炸了（）

**Comment by ABA2396** [comment]
![a69f860bd785d4aa273daefa1860de86](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/8ee96d62-9b12-4453-8f27-070850447c1d)
企鹅刚刚确实抽了一下，不过感觉是偶然事件，之后再观察下吧

**Comment by ntgmc** [comment]
[asst - 副本.log](https://github.com/user-attachments/files/15937312/asst.-.log)
[gui - 副本.log](https://github.com/user-attachments/files/15937314/gui.-.log)
@ABA2396

**Comment by TimCrownie** [comment]
> ![a69f860bd785d4aa273daefa1860de86](https://private-user-images.githubusercontent.com/99072975/341950322-8ee96d62-9b12-4453-8f27-070850447c1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwODI5NjIsIm5iZiI6MTcxOTA4MjY2MiwicGF0aCI6Ii85OTA3Mjk3NS8zNDE5NTAzMjItOGVlOTZkNjItOWIxMi00NDUzLThmMjctMDcwODUwNDQ3YzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE4NTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNmM2MmE0YmNhNjQ0MTcwZjM3OGU5NTIxMzQ0ZTQwYTIzNjYwZjNlMmRlMjkzY2NiMDM0YTA2YjBhOTRiMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W9HwaEEUihmCgChGj6kgVllKfNE_H7ay6h3Hf4iV0Tw) 企鹅刚刚确实抽了一下，不过感觉是偶然事件，之后再观察下吧

到现在依然存在同样的问题，在刷理智和公招时都是要等接近1min才（

**Comment by Mou-Froski** [comment]
顺带一提，如果触发了这个bug的时候手动停止任务，maa会直接卡住
![bug](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159701770/78b6f78b-feb6-4639-a8cd-9e0011c20430)

**Comment by TimCrownie** [comment]
> ![a69f860bd785d4aa273daefa1860de86](https://private-user-images.githubusercontent.com/99072975/341950322-8ee96d62-9b12-4453-8f27-070850447c1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTU0OTcsIm5iZiI6MTcyMDI5NTE5NywicGF0aCI6Ii85OTA3Mjk3NS8zNDE5NTAzMjItOGVlOTZkNjItOWIxMi00NDUzLThmMjctMDcwODUwNDQ3YzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDE5NDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNTYxMTAwNzBmMjY2YjQ2MzIyOWVlNjExOWRkODNiODY4ZDk3NWRjNDlmNzdmMWQ5MDNlMTVlZTY2YjkyNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N711TcWrAXEAq0LustQ8ou934fYV8VyeH7YE_kSqqSg) 企鹅刚刚确实抽了一下，不过感觉是偶然事件，之后再观察下吧

直到现在都还有，感觉不是偶然事件（挠头
目前是刷理智和公招都会有这个问题

**Comment by ABA2396** [comment]
现在最多等15s，等发版

**Comment by Windsland52** [comment]
> 现在最多等15s，等发版

好好好

**Comment by TimCrownie** [comment]
> 现在最多等15s，等发版

![image](https://github.com/user-attachments/assets/b119ef92-be49-47a6-9536-f9a02f4ccb6c)
寄（

**Comment by ABA2396** [comment]
比一分钟好多了（bushi）
