### ISSUE TITLE
日服 自动作战 卡在跳过剧情界面 

### ISSUE THREAD

**Issue by ShirasawaYui** [MaaAssistantArknights/MaaAssistantArknights#9435]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如视频
以前是点击跳过的
不知道哪个版本更新后就这样了
感觉是点错了位置

### Version

Resource Version: シラクザーノ・復刻
UI Version: v5.4.0-beta.1.d037.g98ecb301b
Core Version: v5.4.0-beta.1.d037.g98ecb301b

### 日志文件

[asst.log](https://github.com/user-attachments/files/15925120/asst.log)
[gui.log](https://github.com/user-attachments/files/15925123/gui.log)

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/11786799/50a92abb-9bdb-47eb-9723-344b5aebeafb

**Comment by Constrat** [comment]
cc @Manicsteiner has the ☑️ icon been modified? Or perhaps the background is interfering? Usually the problem was the SKIP not getting recognized, but now it's the ☑️

**Comment by ShirasawaYui** [comment]
顺带一提，进入作战后弹出来的教学对话点击跳过也有相同故障，忘记录了就提一嘴。

**Comment by Manicsteiner** [comment]
前两天时发现了这个问题，还以为是小概率事件来着
折腾了半天，重做了 SkipThePreBattlePlotConfirm.png 也还是只有0.6左右，最后调整了maskrange的下限，从100下调到了30，结果就可以了，上限的修改应该没有影响。
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/22eb2ea1-4621-4977-8454-3723e2bf74c1)
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/daf0ae6f-e94b-47d1-bfe4-4772ca3ef937)
这个问题可能影响所有服务器，具体修改的数值也需要进一步测试，就不是我能直接修改的了。

**Comment by KiriyaXX** [comment]
不确定和这个问题有没有关联但是自动战斗的 deploy 打火石也是用不了，没有反应
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57272409/86e4898f-aa10-458b-bbc3-acaf1dc92d53)

**Comment by Constrat** [comment]
Transferred to 
- #9443

**Comment by Manicsteiner** [comment]
> 不确定和这个问题有没有关联但是自动战斗的 deploy 打火石也是用不了，没有反应

打火石一直不能用是因为上游数据仓库一直没有更新，https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/a36c8f7644f7c2b7ca2e69dbfaa25888e23564a1 应当已解决
