### ISSUE TITLE
维什戴尔水月肉鸽运行中时三技能的开启问题

### ISSUE THREAD

**Issue by Lucas060912** [MaaAssistantArknights/MaaAssistantArknights#9436]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

maa运行时在三技能爆裂黎明开启后不会等待六发弹药完全打出后自动关闭技能，而是会在开启技能之后立马又再次操作把技能关闭，导致一发弹药都没有打出，造成技能无效

### Version

Resource Version: 生路
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[bug文件.zip](https://github.com/user-attachments/files/15925285/bug.zip)

### 还有别的吗？

mumu模拟器，操作系统是win10

**Comment by ntgmc** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/67cb180ba8f624217a5575f258eda3e424756c84 fixed
更新到最新公测版即可
