### ISSUE TITLE
maa core加上状态输出接口

### ISSUE THREAD

**Issue by cglcv** [MaaAssistantArknights/MaaAssistantArknights#944]
目前UI中执行过程的显示都是由UI控制的，可以考虑让core提供一个消息输出接口，UI只负责解释并显示这些信息就足够了。同时core可以输出更多的错误信息（操作错误、ocr识别错误等），方便用户使用和故障排除
这样无论新旧UI都可以显示相同的消息，同时用户和开发者也可以更容易的发现问题

**Comment by MistEO** [comment]
没理解你的意思，现在的消息都是 core 给出的，ui 只负责显示

**Comment by cglcv** [comment]
确实，我疏忽了（
