### ISSUE TITLE
copilot无法跳过战斗前剧情

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/MaaAssistantArknights#9443]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

官服 内容同#9435
附上视频和log

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/74061867/f1bd8fbf-fa78-4852-9b35-b0f6c98c2a55

### Version

Resource Version: 生路
UI Version: v5.4.0-beta.2
Core Version: v5.4.0-beta.2

### 日志文件

[asst - 副本.log](https://github.com/user-attachments/files/15930597/asst.-.log)
[gui - 副本.log](https://github.com/user-attachments/files/15930601/gui.-.log)

**Comment by Constrat** [comment]
Same as YostarEN, we can merge all issues in same one.
