### ISSUE TITLE
Disable changelog after updates

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#9444]
### Before raising the issue...

- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I'm probably sure this is a new feature/suggestion and not a bug encountered (please attach logs if you're not sure)

### The problems you have encountered?

I'm running 4 different MAAs in a small GUI server, everytime I update (only betas to make sure no bugs come) I have to close the changelogs.

### Any good ideas?

In update tab close to `changelog`
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/c54d2249-daf9-4d9c-a017-df410b089641)
A checkmark for disabling the changelog window, or if possible making it disappear automatically after an amount of time.

**Comment by ABA2396** [comment]
I don't think displaying this feature directly to the users in the interface is a good choice, but you can refer to this commit for implementation.
e295c1a8307b0e2dc1d76a4262dc2dbe274ed41b
