### ISSUE TITLE
建议增加公招选择——招募次数0次时仍然刷新三星tag

### ISSUE THREAD

**Issue by pongzhe** [MaaAssistantArknights/MaaAssistantArknights#9449]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

使用mower时见到的选择，感觉挺好，在公招券低于某个阈值时，不再使用公招券，仅仅刷新三星tag

**Comment by ABA2396** [comment]
设置里有

**Comment by pongzhe** [comment]
设置里的是无招聘许可时可以刷新标签。我指的是有招聘许可时，可以在不招募的情况下刷新。现在的情况是招募次数0次，maa直接无动作，并不能刷新

uye ***@***.***> 于 2024年6月22日周六 15:10写道：

**Comment by ABA2396** [comment]
那你可以选择招募四次然后把自动招募三星关掉
