### ISSUE TITLE
自动公招功能有时同一画面判断两次的问题

### ISSUE THREAD

**Issue by TimothyChan44** [MaaAssistantArknights/MaaAssistantArknights#945]
- 幻境：
  - 模拟器： Nox

- Q1：
   -  bug描述：
      自动公开招募有几率遇到重复判断同一画面的情况，并且有几率因此报错；

   -  bug表现：
前端日志显示两次tags判断逻辑；
当出现该情况时会操作两次点击导致出现 8 h 招募的情况；
   - Screenshot：
![image](https://user-images.githubusercontent.com/49863417/174704190-3cb7be62-aaea-45f3-8f76-9d4fe34f2d4f.png)

   - 错误日志：
[bug01.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8945291/bug01.log)

**Comment by zzyyyl** [comment]
草，果然出问题了，先贴上我之前的分析
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/574#issuecomment-1160444028
（玛丽你是不是没看）

**Comment by horror-proton** [comment]
```
[2022-06-21 10:29:21.384][TRC][Px4e78][Tx69f4] Call ` G:\noxvms\Nox\bin\.\nox_adb.exe -s 127.0.0.1:62001 shell input tap 567 368 ` ret 0 , output size: 0
[2022-06-21 10:29:21.384][TRC][Px4e78][Tx69f4] asst::Controller::call_command | `G:\noxvms\Nox\bin\.\nox_adb.exe -s 127.0.0.1:62001 shell input tap 567 368`  | leave, 783 ms
[2022-06-21 10:29:21.483][TRC][Px4e78][Tx56e0] Call ` G:\noxvms\Nox\bin\.\nox_adb.exe -s 127.0.0.1:62001 exec-out "screencap | nc -w 3 172.17.100.2 6723" ` ret 0 , output size: 5760012
[2022-06-21 10:29:21.483][TRC][Px4e78][Tx56e0] asst::Controller::call_command | `G:\noxvms\Nox\bin\.\nox_adb.exe -s 127.0.0.1:62001 exec-out "screencap | nc -w 3 172.17.100.2 6723"`  | leave, 881 ms
[2022-06-21 10:29:21.486][TRC][Px4e78][Tx56e0] asst::Controller::screencap  | leave, 884 ms
[2022-06-21 10:29:21.490][TRC][Px4e78][Tx56e0] match_templ | RecruitTimeReduce.png score: 0.982214 rect: [ 385, 185, 120, 82 ] roi: [ 385, 185, 120, 82 ]
```

有可能虽然 `tap` 返回了, 但是 0.1 秒后就截图, 方舟还没有处理完这次操作, 所以画面上的数字截图的时候还是 01 (所以变成 09 之后又被点了一次

**Comment by zzyyyl** [comment]
对的，这我也提了一次
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/574#issuecomment-1160444110

**Comment by zzyyyl** [comment]
> > 对的，这我也提了一次 [#574 (comment)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/574#issuecomment-1160444110)
> 
> 我的意思有点不同, 确实这里让主线程等待 `input` 返回肯定是更合理的, 但就算真的等到 `input` 跑完了返回了, 也只是系统完成了点击操作, 也不能保证方舟是否处理完了点击操作, 所以可能还是 sleep 长一点比较好?

确实应该sleep，但是如果不阻塞的话是不是sleep了也是白搭（？比如你sleep一秒钟结果input就跑了两秒（看看 #574 的那位

**Comment by zzyyyl** [comment]
> ```
> [2022-06-21 10:29:21.384][TRC][Px4e78][Tx69f4] Call ` G:\noxvms\Nox\bin\.\nox_adb.exe -s 127.0.0.1:62001 shell input tap 567 368 ` ret 0 , output size: 0
> [2022-06-21 10:29:21.384][TRC][Px4e78][Tx69f4] asst::Controller::call_command | `G:\noxvms\Nox\bin\.\nox_adb.exe -s 127.0.0.1:62001 shell input tap 567 368`  | leave, 783 ms
> [2022-06-21 10:29:21.483][TRC][Px4e78][Tx56e0] Call ` G:\noxvms\Nox\bin\.\nox_adb.exe -s 127.0.0.1:62001 exec-out "screencap | nc -w 3 172.17.100.2 6723" ` ret 0 , output size: 5760012
> [2022-06-21 10:29:21.483][TRC][Px4e78][Tx56e0] asst::Controller::call_command | `G:\noxvms\Nox\bin\.\nox_adb.exe -s 127.0.0.1:62001 exec-out "screencap | nc -w 3 172.17.100.2 6723"`  | leave, 881 ms
> [2022-06-21 10:29:21.486][TRC][Px4e78][Tx56e0] asst::Controller::screencap  | leave, 884 ms
> [2022-06-21 10:29:21.490][TRC][Px4e78][Tx56e0] match_templ | RecruitTimeReduce.png score: 0.982214 rect: [ 385, 185, 120, 82 ] roi: [ 385, 185, 120, 82 ]
> ```
> 
> 有可能虽然 `tap` 返回了, 但是 0.1 秒后就截图, 方舟还没有处理完这次操作, 所以画面上的数字截图的时候还是 01 (所以变成 09 之后又被点了一次

我觉得这里用检测 09 代替检测 01 就能解决这个问题，检测不到 09 retry 一两次还检测不到就是真的 01，而且截图的操作肯定不会到点击操作的前面（adb 应该是FIFO的吧？）而且截图好像是阻塞的，不会出现之前那种问题

**Comment by horror-proton** [comment]
> 

09 检测错误最多多点跑几次数字总会回到 09 的, 01 检测错误就麻烦了. 
不过上面那个问题得先解决了, 不然会出现 
```
点击↓ -> 截图还是01 -> 方舟处理点击变成09 -> 点击08 -> 截图09 -> 方舟处理点击变成08 -> boom
```

**Comment by horror-proton** [comment]
~还有 `RecruitTimeReduce.png` 为啥把那个飞来飞去的小黑点也截进去了, 强迫症狂怒~

**Comment by zzyyyl** [comment]
![image](https://user-images.githubusercontent.com/74587068/174713742-09897182-f63b-48d0-9842-f0055f93ebbb.png)
我觉得这里硬编码减时间的按键不好，应该加个 match template ，因为好像会点歪（？
