### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by Lucas060912** [MaaAssistantArknights/MaaAssistantArknights#9451]
### 说说你遇到的问题？

请问如何切换软件版本？比如从稳定版切换到公测版？我从稳定版切换到公测版重启之后软件核心版本没有变，要怎么操作呢

**Comment by ABA2396** [comment]
所以你现在是什么版本

**Comment by ntgmc** [comment]
切换版本换的是要更新到的下一个版本，不是立刻切换，也不能回退版本

**Comment by Lucas060912** [comment]
> 所以你现在是什么版本

V5.4.0-beta.2.d007.ga36c8f764
我也不太知道是什么版本，因为异w三技能bug的问题想更新到公测版可是我切换到公测版检查更新之后说已经是最新版本了然后我又换到内测版也说是最新版本现在整得我也不知道我在用哪个

**Comment by ABA2396** [comment]
正式版现在是v5.3.1，公测版是v5.4.0-beta.2，内测版是v5.4.0-beta.2.d007.ga36c8f764
v5.3.1<v5.4.0-beta.2<v5.4.0-beta.2.d007.ga36c8f764

**Comment by Lucas060912** [comment]
> 切换版本换的是要更新到的下一个版本，不是立刻切换，也不能回退版本

那请问怎么才能用到公测版呢

**Comment by Lucas060912** [comment]
> 正式版现在是v5.3.1，公测版是v5.4.0-beta.2，内测版是v5.4.0-beta.2.d007.ga36c8f764 v5.3.1<v5.4.0-beta.2<v5.4.0-beta.2.d007.ga36c8f764

请问怎么才能换到公测版呢

**Comment by ABA2396** [comment]
你现在的版本比公测版还高，所有公测版的提交在这里都有，为什么想着要用公测版呢？

**Comment by Lucas060912** [comment]
> 你现在的版本比公测版还高，所有公测版的提交在这里都有，为什么想着要用公测版呢？

这样呀，因为异w技能有个bug有人跟我说换到公测版就能解决，之前用的是稳定版所以就一直纠结想换到公测版去，现在知道了就不用想着换了

**Comment by Lucas060912** [comment]
> 你现在的版本比公测版还高，所有公测版的提交在这里都有，为什么想着要用公测版呢？

谢谢你
