### ISSUE TITLE
繁中服薩米肉鴿進入特地關卡無法辨識

### ISSUE THREAD

**Issue by shmily554554** [MaaAssistantArknights/MaaAssistantArknights#9453]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如標題，進入某關之後都無法辨識關卡，導致失敗

### Version

UI Version: v5.4.0-beta.2.d007.ga36c8f764
Core Version: v5.4.0-beta.2.d007.ga36c8f764

### 日志文件

[gui.log](https://github.com/user-attachments/files/15936295/gui.log)

**Comment by momomochi987** [comment]
#9450 

我有調整部分關卡名的辨識，可以等更新後再觀察看看~

**Comment by HX3N** [comment]
Please upload the debug/asst.log file if it still doesn't work after the update.

**Comment by shmily554554** [comment]
> #9450
> 
> 我有調整部分關卡名的辨識，可以等更新後再觀察看看~

更新後還是會卡住呢
asst檔案太大無法上傳  我也不會壓縮

**Comment by shmily554554** [comment]
[Uploading asst.zip…]()

**Comment by shmily554554** [comment]
[Uploading asst.log…]()

**Comment by shmily554554** [comment]
[asst.log](https://github.com/user-attachments/files/15937620/asst.log)

**Comment by stupidegg8576** [comment]
[asst.log](https://github.com/user-attachments/files/15985754/asst.log)
![2024-06-26_17-23-10-025_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/17807218/fdae3a48-09c9-4e4e-bdab-97aebb5eacc4)
飢渴祭壇會被辨識為凱渴祭壇或仇渴祭壇
