### ISSUE TITLE
生息演算到第一关对话界面就提示出错，已全部完成

### ISSUE THREAD

**Issue by 123xiaohongmao** [MaaAssistantArknights/MaaAssistantArknights#9454]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

生息演算进第一关的对话界面就提示出错，然后就显示任务已全部完成，不往下进行了
编队和存档确定是都删除了

### Version

UI Version: v5.4.0-beta.2.d007.ga36c8f764
Core Version: v5.4.0-beta.2.d007.ga36c8f764

### 日志文件

[asst.log](https://github.com/user-attachments/files/15937089/asst.log)
[gui.log](https://github.com/user-attachments/files/15937090/gui.log)

6月21日和6月22日的日志应该都是生息演算的

### 截图

![PixPin_2024-06-22_22-20-03](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/173554426/da4e4148-945f-4761-aa56-96cc773e67cd)

### 还有别的吗？

MUMU模拟器12 V3.8.30

**Comment by ABA2396** [comment]
![Reclamation2BeginPlot](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/fcc40ddb-3f5b-4702-b37e-c739019ed258)
左上角这个的匹配得分太低了，来个截图
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/b60ca95e-7c53-462f-ae8b-2bb33613bd0a)

**Comment by 123xiaohongmao** [comment]
> ![开垦2开始绘图](https://private-user-images.githubusercontent.com/99072975/341978679-fcc40ddb-3f5b-4702-b37e-c739019ed258.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDMwNjQsIm5iZiI6MTcxOTE0Mjc2NCwicGF0aCI6Ii85OTA3Mjk3NS8zNDE5Nzg2NzktZmNjNDBkZGItM2Y1Yi00NzAyLWIzN2UtYzczOTAxOWVkMjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDExMzkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMGNjODI4Y2U2YWNkNWVlNGFiYzkzNjRlYzdjODVhMTI4NmZjMDY2OGI0MTU0NTBlOWU2Njk0YjA2YjUxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DRgZd1UWGvkdBZ4SYIlI4J7ZLH9gBWzJhC4uBYjWsYw)左上角这个的匹配得分太低了，来个截图 ![图像](https://private-user-images.githubusercontent.com/99072975/341978707-b60ca95e-7c53-462f-ae8b-2bb33613bd0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDMwNjQsIm5iZiI6MTcxOTE0Mjc2NCwicGF0aCI6Ii85OTA3Mjk3NS8zNDE5Nzg3MDctYjYwY2E5NWUtN2M1My00NjJmLWFlOGItMmJiMzM2MTNiZDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDExMzkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YTY0NDBkMjZjZTY4MWFkZDhkZTEwN2I5NDNlMzcxOTY3ZmY2MjZmZjkwOTQ5NjczZWNiMjM0ZGZjM2QyNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ymf48PFkX2HsM4n16e9uvsg-woaX3sOenOMRriGqVLE)

![MuMu12-20240623-195232](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/173554426/b2c2ecde-aa76-4bb7-a2ac-75419f8364e4)
这样的图可以吗

**Comment by ABA2396** [comment]
我本地没复现出这个问题，得你自己那边试试看
把下面这张图放到resource/template中并重命名为Reclamation2BeginPlot.png
![Reclamation2BeginPlot](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/258e2d99-4d6c-4357-b17c-077dce28d674)
修改resource/tasks.json中的
``` json
    "Reclamation2BeginPlot": {
        "Doc": "点指定区域，直到左上角出现退出",
        "roi": [
            0,
            0,
            100,
            100
        ],
        "cache": false,
        "sub": [
            "Reclamation2ClickBeginPlotTalk*10"
        ],
        "next": [
            "Reclamation2LeaveStage",
            "#self"
        ]
    },
```
为
``` json
    "Reclamation2BeginPlot": {
        "Doc": "点指定区域，直到左上角出现退出",
        "roi": [
            0,
            0,
            100,
            100
        ],
        "maskRange": [ 1, 255 ],
        "cache": false,
        "sub": [
            "Reclamation2ClickBeginPlotTalk*10"
        ],
        "next": [
            "Reclamation2LeaveStage",
            "#self"
        ]
    },
```

**Comment by 123xiaohongmao** [comment]
> 我本地没复现出这个问题，得你自己那边试试看 把下面这张图重命名为Reclamation2BeginPlot.png并替换resource/template中的对应图片 ![Reclamation2BeginPlot](https://private-user-images.githubusercontent.com/99072975/342063131-258e2d99-4d6c-4357-b17c-077dce28d674.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTMxMjYsIm5iZiI6MTcxOTE5MjgyNiwicGF0aCI6Ii85OTA3Mjk3NS8zNDIwNjMxMzEtMjU4ZTJkOTktNGQ2Yy00MzU3LWIxN2MtMDc3ZGNlMjhkNjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAxMzM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5OWQyOWY4YTk5NTExNTVhYmRhZDIwNDFmNDE4NmQ2ZTEzMDVjZTJhMjY1MDc5ODc0NTIwNmQ4MWUzYzBiZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Av0UzKDiysuMvJPyND579cVaBaTc6AbsOkXLZ2yKpP0) 修改resource/tasks.json中的
> 
> ```json
>     "Reclamation2BeginPlot": {
>         "Doc": "点指定区域，直到左上角出现退出",
>         "roi": [
>             0,
>             0,
>             100,
>             100
>         ],
>         "cache": false,
>         "sub": [
>             "Reclamation2ClickBeginPlotTalk*10"
>         ],
>         "next": [
>             "Reclamation2LeaveStage",
>             "#self"
>         ]
>     },
> ```
> 
> 为
> 
> ```json
>     "Reclamation2BeginPlot": {
>         "Doc": "点指定区域，直到左上角出现退出",
>         "roi": [
>             0,
>             0,
>             100,
>             100
>         ],
>         "maskRange": [ 1, 255 ],
>         "cache": false,
>         "sub": [
>             "Reclamation2ClickBeginPlotTalk*10"
>         ],
>         "next": [
>             "Reclamation2LeaveStage",
>             "#self"
>         ]
>     },
> ```

我把对话框左上角的（log）图标重截替换了Reclamation2BeginPlot   ，resource/tasks.json也改了  还是出现一样的问题

**Comment by ABA2396** [comment]
日志

**Comment by 123xiaohongmao** [comment]
[asst.log](https://github.com/user-attachments/files/15949092/asst.log)
[gui.log](https://github.com/user-attachments/files/15949093/gui.log)

**Comment by 123xiaohongmao** [comment]
> 日志

发下面了

**Comment by ABA2396** [comment]
没搞懂，你这个报错是什么时候弹出来的？感觉是模拟器比较卡进图的时间太长了然后在黑屏的时候去识别了

**Comment by 123xiaohongmao** [comment]
> 没搞懂，你这个报错是什么时候弹出来的？感觉是模拟器比较卡进图的时间太长了然后在黑屏的时候去识别了

是在进图的时候   出俩人对话的时候      这里
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/173554426/4edd7237-3228-45bb-8e2b-1cbc78d3d887)

**Comment by ABA2396** [comment]
看这样就是太卡了，等待进图时间设的是8秒，但你这8秒跑完图还没加载完
试试看把
``` json
    "Reclamation2BeginPlotLoading": {
        "algorithm": "JustReturn",
        "action": "DoNothing",
        "postDelay": 8000,
        "next": [
            "Reclamation2BeginPlot"
        ]
    },
```
里的 8000 自己改大一点

**Comment by ABA2396** [comment]
80000你得等80秒）

**Comment by 123xiaohongmao** [comment]
> 80000你得等80秒）

就是 改到了15000 20000 30000还是一样的情况   想着看看直接改大点hhhh

**Comment by ABA2396** [comment]
![Reclamation2BeginPlot](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f50c6fc4-273b-4ce6-b0a0-85f8364fb198)
把这个改回去然后时间改成 15000 试试

**Comment by ABA2396** [comment]
跑完发个日志

**Comment by 123xiaohongmao** [comment]
> 跑完发个日志

[asst.log](https://github.com/user-attachments/files/15988511/asst.log)
[gui.log](https://github.com/user-attachments/files/15988512/gui.log)
好像找到问题了   把MuMu截图增强关了就好了 开着把进图时间改成20000也不行

**Comment by ABA2396** [comment]
你这实在是太卡了，从点了开始到进图花了30秒才加载完，正常来说开了截图加速后花费的时间都是个位数或者十几毫秒
建议你检查下到底是模拟器还是电脑性能的问题

默认的情况下是0.5识别一次，重试20次，也就是等你大约8+0.5\*20=18s
临时的解决方法就是增加任务之间的间隔
打开 \resource\config.json ，把 "taskDelay": 500, 改的稍微大一点，比如 1500，这样就会等你 8+1.5\*20=38s

但这样的影响就是其他所有任务的速度都会变慢，两次识别的间隔起码有1.5s

**Comment by 123xiaohongmao** [comment]
> 你这实在是太卡了，从点了开始到进图花了30秒才加载完，正常来说开了截图加速后花费的时间都是个位数或者十几毫秒 建议你检查下到底是模拟器还是电脑性能的问题
> 
> 默认的情况下是0.5识别一次，重试20次，也就是等你大约8+0.5*20=18s 临时的解决方法就是增加任务之间的间隔 打开 \resource\config.json ，把 "taskDelay": 500, 改的稍微大一点，比如 1500，这样就会等你 8+1.5*20=38s
> 
> 但这样的影响就是其他所有任务的速度都会变慢，两次识别的间隔起码有1.5s

是不最好是不开MuMu截图增强

**Comment by ABA2396** [comment]
正常情况下肯定是推荐开的，但你这加载速度实在是太慢了，反倒是多出来的截图时间让你多等了会儿

比如你一次截图花了一秒钟，那重复20次就是花了20s，可能这18+20=38s的时候进去了，那就不会卡住
但是开了之后截图只要50ms，那重复20次就是花了1s，18+1=19就进不去了

看情况自己选择吧

**Comment by 123xiaohongmao** [comment]
> 正常情况下肯定是推荐开的，但你这加载速度实在是太慢了，反倒是多出来的截图时间让你多等了会儿
> 
> 比如你一次截图花了一秒钟，那重复20次就是花了20s，可能这18+20=38s的时候进去了，那就不会卡住 但是开了之后截图只要50ms，那重复20次就是花了1s，18+1=19就进不去了
> 
> 看情况自己选择吧

好的好的明白了  万分感谢解答
