### ISSUE TITLE
国际服萨米肉鸽无法选择锏开局

### ISSUE THREAD

**Issue by TanChunHong717** [MaaAssistantArknights/MaaAssistantArknights#9455]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，在国际服萨米肉鸽选择锏开局，MAA无法识别并选择锏，卡在了近卫招募界面，最后选择了百嘉开

### Version

Resource Version: The Rides to Lake Silberneherze
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15937289/asst.log)
[gui.log](https://github.com/user-attachments/files/15937290/gui.log)

2024-6-22 23：37：07 开始探索
2024-6-22 23：39：15 停止

PS: 问题日志，以供参考
[2024-06-22 23:37:30.036][INF][Px8628][Tx91c8] asst::RoguelikeRecruitImageAnalyzer::analyze Degenbrecher 1 80 [ 609, 178, 86, 19 ]
......
[2024-06-22 23:37:30.113][INF][Px8628][Tx91c8] asst::RoguelikeRecruitTaskPlugin::recruit_appointed_char | Oper list: [玛恩纳, Degenbrecher, 重岳, 赫拉格, 陈, 止颂, 薇薇安娜, 艾丽妮]

### 截图

设置：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92709914/57145034-bf18-4918-90e2-89ff56a15832)
模拟器运行：
![MuMu20240622234903](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92709914/3eaefa3a-255c-41ab-998e-a59ee27dc7f7)
![MuMu20240622235022](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/92709914/1e44844d-91b5-43aa-8103-6ff61cf0ba68)

**Comment by Constrat** [comment]
Updated to the latest nightly.
The commit with Degenbrecher (and subsequentially the new operator was committed yesterday).
!!!!!!!!!!!!
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/2e365744-0f5d-45ef-8e8f-df3e07e26682)
!!!!!!!!!!!!

**Comment by TanChunHong717** [comment]
The problem still persist in the latest version.
