### ISSUE TITLE
萨米肉鸽刷源石锭模式一层路线优化

### ISSUE THREAD

**Issue by huaji749** [MaaAssistantArknights/MaaAssistantArknights#9456]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

现在maa在一层选择的路线并不总是战斗最少的路线，而减少战斗可以大幅增加刷源石锭的效率

### 有什么好的想法？

可以在第一层开始前先对一层的节点进行识别，自动选择战斗最少的一条路线，从而最快进入商店开始存钱

**Comment by Constrat** [comment]
Unfeasable
