### ISSUE TITLE
未知原因闪退+1

### ISSUE THREAD

**Issue by alice8059** [MaaAssistantArknights/MaaAssistantArknights#946]
在刷肉鸽时会闪退 脚本自行关闭 模拟器点击几下后报错
3.9.3版本不会这样 4.0.0高强度闪退
清理智等不会闪退
模拟器是夜神 
LOG最后一段是闪退
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8945501/asst.log)

**Comment by MistEO** [comment]
模拟器点几下报错，是个啥现象？maa 闪退的时候游戏卡在哪个界面了？

**Comment by alice8059** [comment]
> 

模拟器点几下报错，是个啥现象？
我又运行了几次 没截到 模拟器点几下后就死机了 之前好像是“虚拟机报错”？

maa 闪退的时候游戏卡在哪个界面了？
都是卡在了肉鸽作战结束后 结算 XX作战 成功通过的界面

另外我还发现了新的BUG 就是比如类似正义的关卡 漏最后一个兵去打医疗 会陷入死循环 关卡永远无法结束

**Comment by MistEO** [comment]
不会死循环的，超过5分钟会自动撤掉所有干员

**Comment by MistEO** [comment]
看起来是夜神的锅，模拟器出错了，MAA没做处理也跟着崩了。升级一下夜神的版本，不行换个模拟器试试

**Comment by alice8059** [comment]
> 看起来是夜神的锅，模拟器出错了，MAA没做处理也跟着崩了。升级一下夜神的版本，不行换个模拟器试试

好的 我试试 谢谢

不会死循环的，超过5分钟会自动撤掉所有干员
当时MAA自己也关掉了 我还以为是BUG hhh 结果还是闪退的问题

**Comment by alice8059** [comment]
> 看起来是夜神的锅，模拟器出错了，MAA没做处理也跟着崩了。升级一下夜神的版本，不行换个模拟器试试
瞎蒙瞎改了下夜神的兼容设置 现在好了不会闪退了
