### ISSUE TITLE
肉鴿戰鬥結束後無法選擇密文版

### ISSUE THREAD

**Issue by rein7555** [MaaAssistantArknights/MaaAssistantArknights#9460]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如上，密文版選擇時只會點開又關閉，無法選擇導致卡死

### Version

Resource Version: 眠於樹影之中
UI Version: v5.4.0-beta.2.d017.g8bfb223da
Core Version: v5.4.0-beta.2.d017.g8bfb223da

### 日志文件

[asst.log](https://github.com/user-attachments/files/15942853/asst.log)
[gui.log](https://github.com/user-attachments/files/15942854/gui.log)

**Comment by Manicsteiner** [comment]
此份asst.log中没有有效信息，请上传asst.bak.log

**Comment by rein7555** [comment]
[asst.bak.log](https://github.com/user-attachments/files/15944253/asst.bak.log)

**Comment by momomochi987** [comment]
這個我自己遇到的是

「開始宣告」被識別成「開始宜告」

下次提 PR 的時候補上
