### ISSUE TITLE
繁中服更新到最新版本还是会卡在选干员的地方

### ISSUE THREAD

**Issue by fifteenight** [MaaAssistantArknights/MaaAssistantArknights#9461]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新到最新的内测版本，开始还能刷，刷了2小时，刷到110，模拟器闪退，之后不管是重新下载maa还是重新下载明日方舟，都不能刷源石锭了，都会卡在选完干员准备进入肉鸽的界面

### Version

v5.4.0-beta.2.d017.g8bfb223da

### 日志文件

[asst.log](https://github.com/user-attachments/files/15944086/asst.log)
[gui.log](https://github.com/user-attachments/files/15944087/gui.log)

### 截图

 
[Uploading MuMu12-20240623-180651.png…]

### 还有别的吗？

mumu12模拟器

**Comment by momomochi987** [comment]
@fifteenight 

試試下面這個圖片?
下載下來改名成  Sami@Roguelike@EnterAfterRecruit.png

![Sami@Roguelike@EnterAfterRecruit](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/45387477/2d2f0311-ac73-4d16-be74-7f1e445cc454)

改完名之後放入 "你的 MAA 資料夾 \ resource \ global \ txwy \ resource \ template"
然後再重新啟動 MAA 看看 (?

**Comment by fifteenight** [comment]
> @fifteenight
> 
> 試試下面這個圖片? 下載下來改名成 Sami@[Roguelike@EnterAfterRecruit.png](mailto:Roguelike@EnterAfterRecruit.png)
> 
> ![Sami@Roguelike@EnterAfterRecruit](https://private-user-images.githubusercontent.com/45387477/342061033-2d2f0311-ac73-4d16-be74-7f1e445cc454.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDQzNDYsIm5iZiI6MTcxOTE0NDA0NiwicGF0aCI6Ii80NTM4NzQ3Ny8zNDIwNjEwMzMtMmQyZjAzMTEtYWM3My00ZDE2LWJlNzQtN2YxZTQ0NWNjNDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDEyMDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMTI4Mjk1ZjZmY2M2N2FmMzdmMDFkZWZkNGEwNjg5MDEzYTA4Mjg0ZjhkYmVmYjYzZmI5MzQ3N2JmZGUxMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QNIOAJwNzrpMeChtQujWRyoN1lQ72wsOW00Tgke-UHU)
> 
> 改完名之後放入 "你的 MAA 資料夾 \ resource \ global \ txwy \ resource \ template" 然後再重新啟動 MAA 看看 (?

成功了，谢谢
