### ISSUE TITLE
打开或关闭MAA的任务栏图标

### ISSUE THREAD

**Issue by ycy-9216** [MaaAssistantArknights/MaaAssistantArknights#9464]
### 在提问之前...

- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

我在使用任务栏美化软件StartAllBack时,点击任务栏右下角MAA的图标就会出现系统卡死,资源管理器崩溃的情况.

### 有什么好的想法？

希望MAA能推出隐藏任务栏图标的功能.

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/213461ac-aa94-4f2a-84b3-66588d8e401e)
