### ISSUE TITLE
繁中服 自動肉鴿-薩米 刷原石碇策略存錢

### ISSUE THREAD

**Issue by IzuYanze** [MaaAssistantArknights/MaaAssistantArknights#9465]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我在使用自動肉歌功能 用自動存錢策略的時候  發現經常在第一層進入商店後直接離開商店到下一層
我提供的LOG檔 在進入下一層顯示啟示的時候把MAA停止了
還請開發人員多多幫忙

### Version

Resource Version: 眠於樹影之中
UI Version: v5.4.0-beta.2.d017.g8bfb223da
Core Version: v5.4.0-beta.2.d017.g8bfb223da

### 日志文件

[asst.log](https://github.com/user-attachments/files/15944785/asst.log)
[gui.log](https://github.com/user-attachments/files/15944786/gui.log)

### 还有别的吗？

補充 我有將https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9461%E6%8F%90%E4%BE%9B%E7%9A%84%E8%A7%A3%E6%B1%BA%E6%96%B9%E6%B3%95%E6%8A%8A%E5%9C%96%E7%89%87%E8%A3%9C%E4%B8%8A 所以才能運作 這部分會跟一開始的版本不太一樣

模擬器版本: 藍疊國際板 5.21.111.1001 P64

**Comment by IzuYanze** [comment]
補充  我有將https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9461提供的解決方法把圖片補上 所以才能運作 這部分會跟一開始的版本不太一樣

**Comment by shlhu** [comment]
第一次用maa，在国际服发现了类似的问题，不过是在点进投资后不确认直接选“算了”。用的是2560x1440的mumu12
看了一下log
[2024-06-24 15:42:21.898][TRC][Px4be0][Tx5254] match_templ | Roguelike@StageTraderInvestConfirm.png score: 0.596312 rect: [ 900, 472, 178, 44 ] roi: [ 852, 422, 278, 144 ]
[2024-06-24 15:42:21.898][TRC][Px4be0][Tx5254] asst::PipelineAnalyzer::analyze Sami@Roguelike@StageTraderInvestCancel
[2024-06-24 15:42:21.898][INF][Px4be0][Tx5254] asst::TemplResource::get_templ lazy load Roguelike@StageTraderInvestCancel.png
[2024-06-24 15:42:21.903][TRC][Px4be0][Tx5254] match_templ | Roguelike@StageTraderInvestCancel.png score: 0.908368 rect: [ 538, 470, 163, 48 ] roi: [ 507, 418, 242, 149 ]
貌似识别不了那个确认键。
想了一下决定试试1920x1080，结果没问题了
[2024-06-24 16:13:43.483][TRC][Px31ec][Tx1514] match_templ | Roguelike@StageTraderInvestConfirm.png score: 0.856884 rect: [ 903, 472, 178, 44 ] roi: [ 852, 422, 278, 144 ]

0.857 过了，可是比起b服的.99x好像差了不少。如果想优化一下这个截图的辨认率有办法么？

**Comment by shlhu** [comment]
楼主我看了一眼你的log，没有肉鸽的过程。大概率是您遇到问题后重开过maa？如果想帮debug有可能需要复刻一遍问题然后直接上传。
如果只是想尽快开刷也可以试试换一下分辨率

**Comment by IzuYanze** [comment]
### 问题描述

我再用了一次
這是新版本的  沒注意有沒有這個狀況

### Version

Resource Version: 眠於樹影之中
UI Version: v5.4.0-beta.2.d017.g8bfb223da
Core Version: v5.4.0-beta.2.d025.gfa7f04c55

### 日志文件

[asst.bak.log](https://github.com/user-attachments/files/15983416/asst.bak.log)
[gui.log](https://github.com/user-attachments/files/15983418/gui.log)

[](url)

### 还有别的吗？

模擬器版本: 藍疊國際板 5.21.111.1001 P64

**Comment by BUAAHM** [comment]
**问题描述**
7月9号更新 v5.4.0 熔炉还魂记  后，投资模式也遇到了这个问题，但是之前是没有问题的。第一层进入商店后直接离开，打完第二层才退出。
**版本**
资源版本：熔炉还魂记
UI版本： v5.4.0
核心版本： v5.4.0

**日志文件**
[asst.log](https://github.com/user-attachments/files/16154847/asst.log)

[gui.log](https://github.com/user-attachments/files/16154844/gui.log)


![20240710-103807](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/175175251/bd3aeb7b-b780-480b-aa11-749ab231222a)

**Comment by ABA2396** [comment]
丫丁更新之后投资的位置变了
