### ISSUE TITLE
台服 - 萨米肉鸽 - 识别错误

### ISSUE THREAD

**Issue by cloakmann** [MaaAssistantArknights/MaaAssistantArknights#9466]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

雷电模拟器9，win11， 萨米肉鸽问题
1. 选完人后就不动了，等了一会之后maa 直接退出重进
2.  无法识别提丰（应该是截图资源等未更新）

### Version

Resource Version: 理想城：長夏狂歡季·復刻
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[Uploading bug logs.zip…]()

### 截图

![bug1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46238532/a3364f4f-a6ba-412e-897d-46e00bdd0356)

**Comment by cloakmann** [comment]
[bug logs.zip](https://github.com/user-attachments/files/15945135/bug.logs.zip)

**Comment by paul0665** [comment]
#9461

**Comment by Constrat** [comment]
You can't expect it work when you are using a 1 month old version.
Update to a nightly.
