### ISSUE TITLE
5.3.1资源更新失败

### ISSUE THREAD

**Issue by ishkong** [MaaAssistantArknights/MaaAssistantArknights#9468]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

完全重新下载的5.3.1无法更新资源
游戏资源更新失败，请稍后尝试。
同网段下的5.4.0-beta.2正常

### Version

Resource Version: 孤星·复刻
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15949272/asst.log)
[gui.log](https://github.com/user-attachments/files/15949273/gui.log)

**Comment by xmanthony** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147403590/85184630-5418-4fe5-8691-ea45bace5978)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147403590/7abd564e-4ab9-41bb-8553-a45e3fe5b5f3)
同样的更新不了
[asst.log](https://github.com/user-attachments/files/15963706/asst.log)
[gui.log](https://github.com/user-attachments/files/15963707/gui.log)

**Comment by ABA2396** [comment]
54dcd2736a96f5f140b6b42a58b0eaa6c587907d fixed
