### ISSUE TITLE
切换成自动刷源石锭策略锁死选择导致源石锭不能投资了！

### ISSUE THREAD

**Issue by SperenzaNarra** [MaaAssistantArknights/MaaAssistantArknights#9470]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

当选择自动刷源石锭策略的时候
高级选择中的投资源石锭选项就变成不可选
导致我刷了个寂寞

### 其他内容

话说什么时候可以让自动刷源石锭策略从难度0开始？

**Comment by status102** [comment]
是锁定为启用状态
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/102887808/40b8718b-e573-417c-845e-eeea0375c7c2)
无需理会
