### ISSUE TITLE
基建截图添加延时，以避免信用提示遮挡右上角快速收菜提示

### ISSUE THREAD

**Issue by Viel0320** [MaaAssistantArknights/MaaAssistantArknights#9474]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

如果在进入基建时，触发了线索收集回信用的提示，将对界面右上角的快速收菜进行遮挡，导致基建快速收菜不会执行

### 有什么好的想法？

建议对上述操作对应的基建截图操作添加2-3s左右的延时，以避免信用提示遮挡问题

**Comment by Manicsteiner** [comment]
根据当前的任务流程，在主界面点击右下角的“基建”后，会有5秒的延迟，然后识别基建界面左上角的“建造模式OFF”，成功后立即识别右上角的任务通知按钮。
按问题描述来看，可能是这5秒的延迟不足以覆盖基建界面的加载和线索信用提示，或许可以为识别左上角的 InfrastEnteredFlag 任务也加上一个 postdelay。
[tasks.json](https://github.com/user-attachments/files/15957789/tasks.json)
这是一份 v5.4.0-beta.2.d017.g8bfb223da 版本的 resource/task.json ，已经为 InfrastEnteredFlag 添加了2秒的后置延迟，如果有需求可以自行替换本地的task.json使用。

**Comment by Constrat** [comment]
I can +1 this. Especially when someone send you a lot of clues and you haven't opened arknights for quite a while, the notification spam is heavy. Technically it doesn't craete many issues as MAA will just try to enter the designated room (which will probably have an item to get) meaning it will click twice.

**Comment by Viel0320** [comment]
> 根据当前的任务流程，在主界面点击右下角的“基建”后，会有5秒的延迟，然后识别基建界面左上角的“建造模式OFF”，成功后立即识别右上角的任务通知按钮。 按问题描述来看，可能是这5秒的延迟不足以覆盖基建界面的加载和线索信用提示，或许可以为识别左上角的 InfrastEnteredFlag 任务也加上一个 postdelay。 [tasks.json](https://github.com/user-attachments/files/15957789/tasks.json) 这是一份 v5.4.0-beta.2.d017.g8bfb223da 版本的 resource/task.json ，已经为 InfrastEnteredFlag 添加了2秒的后置延迟，如果有需求可以自行替换本地的task.json使用。

感谢，测试我这边加2s是没问题的，这个issue我先关闭了，看你们主线tasks要不要作这个改动
