### ISSUE TITLE
刷理智功能异常，进入错误章节并无操作

### ISSUE THREAD

**Issue by BenLeung-moon** [MaaAssistantArknights/MaaAssistantArknights#9478]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

选定刷理智功能，并且指定1-7关卡，但MAA进入第三章并卡在选择关卡界面直到MAA自动停止

### Version

Resource Version: 生路
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

时间点为10:08:16至10:09:18
[asst.log](https://github.com/user-attachments/files/15963553/asst.log)
[gui.log](https://github.com/user-attachments/files/15963558/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70994374/8246d28f-ada6-4fcc-90b2-744961651544)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/70994374/9c4ebb88-538b-4083-bc7e-5b39005aa5ca)

**Comment by ABA2396** [comment]
看日志是在选章节的时候划了但划不动
打开 mumu内设置-关于手机 滑到底点五下版本号打开开发者选项
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/9dcd50d1-8ec6-4502-9137-15fb42332530)
返回上一层-系统-开发者选项-打开显示点按操作反馈
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/a9d8d891-0d66-4240-ae06-71a3ae4ca91c)
重新跑一遍1-7看看是怎么滑的，最好再录个屏

**Comment by BenLeung-moon** [comment]
今天重新测试了一遍，问题已经不存在了
