### ISSUE TITLE
干员无法正常识别

### ISSUE THREAD

**Issue by AKiSA07** [MaaAssistantArknights/MaaAssistantArknights#9479]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

干员伊芙利特在被设置为特别关心的情况下无法被正常识别

### Version

Resource Version: 生路
UI Version: v5.4.0-beta.2.d017.g8bfb223da
Core Version: v5.4.0-beta.2.d017.g8bfb223da

### 日志文件

[asst.zip](https://github.com/user-attachments/files/15963904/asst.zip)
[gui.log](https://github.com/user-attachments/files/15963906/gui.log)

### 截图

![photo_2024-06-25_10-29-54](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137269505/b3e026db-e395-4cba-a5a5-5b27f570a84c)
![photo_2024-06-25_10-34-40](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/137269505/19944bae-b5b3-459b-ae24-62957cdc317b)

### 还有别的吗？

模拟器:mumu12
分辨率:1280×720

**Comment by ABA2396** [comment]
大部分名字长的特别关心都会识别不到
