### ISSUE TITLE
指定材料不能关联关卡

### ISSUE THREAD

**Issue by IceKyrin** [MaaAssistantArknights/MaaAssistantArknights#948]
刚选取了术师芯片，作战关卡为默认，结果跑到剿灭去了。能不能自动关联一下材料关卡，或者加个提示、需要手动更改关卡
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8945713/asst.log)

**Comment by zzyyyl** [comment]
maa目前还没这个功能，不算bug，我改一下标签
