### ISSUE TITLE
基建功能增加仅领取产物功能

### ISSUE THREAD

**Issue by BlackNorton** [MaaAssistantArknights/MaaAssistantArknights#9487]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用153基建时，由于产能太高，导致16小时长班期间基建会满仓并停止工作，需要一个能只进基建收取产物但不进行换班的设置

**Comment by Daydreamer114** [comment]
你把所有房间都勾上跳过房间？
