### ISSUE TITLE
繁中服 自動肉鴿-薩米

### ISSUE THREAD

**Issue by MiTSeal** [MaaAssistantArknights/MaaAssistantArknights#9489]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

招募完幹員後不會點擊密文版和探索冰原開始肉鴿

### Version

v5.3.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15980206/asst.log)
[gui.log](https://github.com/user-attachments/files/15980207/gui.log)
2024-06-25 19:37

### 截图

![螢幕擷取畫面 2024-06-25 194051](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/150085813/cac4192d-456e-4323-a578-358d164e5984)

### 还有别的吗？

使用模擬器:Mumu

**Comment by I-am-zeroZ** [comment]
#9484

換成內側版吧
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/54610201/f8fd6a51-ee8f-4475-b5a1-b6ace29d985f)

**Comment by MiTSeal** [comment]
成功了 非常感謝
