### ISSUE TITLE
繁中服  薩米肉鴿  卡在選完幹員畫面不會進入探索

### ISSUE THREAD

**Issue by HankHsuABoo** [MaaAssistantArknights/MaaAssistantArknights#9495]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

繁中服薩米肉鴿，策略選擇刷等級、默認分隊、默認職業組，進行到選完幹員之後會卡住不進入探索，一直放置之後會退出探索並且重複動作。

### Version

Resource Version: 眠於樹影之中
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[Uploading asst.log…]()
[Uploading gui.log…]()

### 截图

![Screenshot_2024 06 26_23 44 14 224](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121720941/5597bb63-ae32-45b4-8ab0-f0dda2b9302f)

**Comment by EvilTurtle0428** [comment]
遇到同樣問題 一直沒有動作

**Comment by Manicsteiner** [comment]
当前请使用内测版本

**Comment by Constrat** [comment]
>  I've reviewed the latest beta version of the update and don't mention that the bug has been fixed
No you didn't.
