### ISSUE TITLE
内测版GPU加速选择UHD770时 公开招募识别失败（RX7800xt正常）

### ISSUE THREAD

**Issue by kamikitameme** [MaaAssistantArknights/MaaAssistantArknights#9498]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

内测版最新，GPU加速选择UHD770时 公开招募识别失败（RX7800xt正常），尝试过多分辨率（都是16比9），多画质模式，DX和VK引擎切换结果一样，不知道是否为BUG还是UHD770自身的问题，部署方面UHD770没有出现明显错误提示，但是在选择干员时可能出现识别不到（7800xt也偶见过）

### Version

Resource Version: 空想花庭·复刻
UI Version: v5.4.0-beta.2.d025.gfa7f04c55
Core Version: v5.4.0-beta.2.d025.gfa7f04c55

### 日志文件

[asst.log](https://github.com/user-attachments/files/16023576/asst.log)
[gui.log](https://github.com/user-attachments/files/16023577/gui.log)
出现时间大约在上午6/28 10点40分以后

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46212141/15fd2641-8980-402a-a2fe-1d394ff7c5c0)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46212141/d1f03b74-6260-4089-b1fd-5651ad6aed19)

### 还有别的吗？

mumu模拟器V3.9.0（3034），137k 7800xt win11 22h2

**Comment by Manicsteiner** [comment]
![图片](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/42d139d8-332b-464f-887a-febad2b3a4b5)
我也是UHD770，一切正常，驱动版本 31.0.101.5590
另一台的移动端UHD620识别速度非常慢，但也能正常运行

**Comment by kamikitameme** [comment]
> ![图片](https://private-user-images.githubusercontent.com/63437036/344138897-42d139d8-332b-464f-887a-febad2b3a4b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODA0NjAsIm5iZiI6MTcxOTU4MDE2MCwicGF0aCI6Ii82MzQzNzAzNi8zNDQxMzg4OTctNDJkMTM5ZDgtMzMyYi00NjRmLTg4N2EtZmViYWQyYjNhNGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDEzMDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YTExOTA4MDRjNWNkMzM1ZmY3YWQzNDUwOWUwN2MwYzBkYzIzMDQyMWE4NWE4YzA3MjNiNjliNDA5NjJjMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rZFLR7jquenF40EUsiFSi0JZTy2AEIiaCmotK0toBN8) 我也是UHD770，一切正常，驱动版本 31.0.101.5590 另一台的移动端UHD620识别速度非常慢，但也能正常运行

可否问一下你用的模拟器名字，分辨率，启动模式设置，我自己这边更新一下同款版本或者接近的版本驱动尝试一下我在mumu模拟器下+增强截图模式 有无改善

**Comment by df4d** [comment]
mumu 3.8.5（2722） 1600x900（240）偶尔也会卡在招募那里不动 显卡是A770 16G 驱动版本5590

**Comment by abigailsothoth0** [comment]
> 蓝叠模拟器 5.2.111.1002 1600×900（240）显卡6600xt 反复进出公招识别[

更新驱动后恢复正常
