### ISSUE TITLE
肉鸽选人与开局策略增加更多自定义选项

### ISSUE THREAD

**Issue by CesareEligos** [MaaAssistantArknights/MaaAssistantArknights#950]
1.虽然目前+4生命是通用情况下稳定度和下限最高的开局策略，但每个玩家box不同思路不同，如果能增加开局策略自由选择能让更多用户探索更适合自己box的开局方法，也能强化maa肉鸽的上限与乐趣。
2.肉鸽拿人策略增加更多自定义选项：
a.根据在群内和群主的交流，我理解在优先级列表和练度间是有个分界线的，就是等级练度超过几级以后看等级，否则优先看列表，这个分界线如果可以自定义的话选人灵活度也可以高不少。
b.肉鸽中选人是否翻页也希望可以自定义，想一把刷更快的可以选择摆烂不翻页，想让maa追求上限的可以定制更适合自己的拿人逻辑，并为了让maa更好的贯彻这个逻辑选择肉鸽选人时翻页。
maa很方便也很有意思，希望能越做越好，并且带来更多的方便和乐趣。

**Comment by MistEO** [comment]
It's in progress now: https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1344
