### ISSUE TITLE
雷电模拟器，在基建运行返回过程中，概率出现停留在返回弹窗，无法进行返回

### ISSUE THREAD

**Issue by DDS-DS** [MaaAssistantArknights/MaaAssistantArknights#9500]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

问题：雷电模拟器（9.0.73.3），在基建运行返回过程中，概率出现停留在返回弹窗，无法进行返回
尝试过的方法：模拟器升级、重装、主板BIOS的更新、驱动的更新等方式都没有解决
其他设备：在笔记本上的7945HX+4060的组合，同样的配置，无法复现该问题

### Version

问题已存在多个版本中，仅列举当前日志所用版本
Resource Version: 空想花庭·复刻
UI Version: v5.4.0-beta.2.d032.gbc14fcb0d
Core Version: v5.4.0-beta.2.d032.gbc14fcb0d

### 日志文件

[gui.log](https://github.com/user-attachments/files/16024519/gui.log)
[asst.log](https://github.com/user-attachments/files/16024520/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/75608102/fde91c85-00d2-43e2-b876-837bc65e364e)

### 还有别的吗？

问题设备参数：
系统: Microsoft Windows 10 64位 22H2
CPU: AMD Ryzen 9 5950X 16-Core Processor            
主板: 华硕 ROGSTRIXX570-EGAMING
内存: 可用内存(115.4GB) 内存(127.9GB)
屏幕: 2560x1440
显卡: NVIDIA GeForce RTX 3070 Ti(20240601)
OpenGL: 4.6.0 NVIDIA 555.99
VT:已开启
HyperV:已关闭
Root:关闭
以管理员身份运行: 否
安装磁盘: F盘(SSD-NTFS) 可用空间(112GB) 总空间(539GB)
模拟器版本: 9.0.73.3(64)
运行参数: CPU(4核) 内存(4096M) 分辨率(1280x720 DPI 240) FPS(60)
多开参数: 当前序号(0) 正在运行(1) 高速模式(1) FPS限制(60)
可用空间: 类型(自动扩充) 可用空间(23GB) 总空间(28GB)
机型: 品牌(Xiaomi) 型号(22081212C)
ASTC: 关闭
ROOT 权限: 关闭
模拟器路径: F:\leidian\LDPlayer9\
日志路径: C:\Users\admin\AppData\Roaming\leidian9\log

笔记本参数：
操作系统：Microsoft Windows 10 64位  22H2
CPU型号：AMD Ryzen 9 7945HX with Radeon Graphics        
主板：机械革命 MRID6-23
总内存：31.2 GB
可用内存：7.9 GB
显卡型号：NVIDIA GeForce RTX 4060 Laptop GPU (20230408)【当前使用】
显卡型号：AMD Radeon(TM) Graphics (20221214)
OpenGL：4.6.0 NVIDIA 531.61
HyperV:关闭
Root:关闭
模拟器版本：9.0.63(9)
模拟器路径：D:\leidian\LDPlayer9\
日志路径：C:\Users\DDS\AppData\Roaming\leidian9\log
vt:开启
运行参数：CPU(4核) 内存：(4096M) 正在运行(4) 高速(1)
分辨率：1280x720 dpi 240 fps 0
总大小24 G，剩余19 G

**Comment by ABA2396** [comment]
先去设置里把这个退出窗口给关了吧，之后有空了再看看是啥原因

**Comment by DDS-DS** [comment]
> 先去设置里把这个退出窗口给关了吧，之后有空了再看看是啥原因

谢谢大佬解答，刚刚试了一下，触控模式换成 maatouch，目前没有问题
