### ISSUE TITLE
Mumu12 1920x1080 繁中服 萨米肉鸽无法自动肉鸽问题（干员招募完后无法进入肉鸽，关卡识别错误）

### ISSUE THREAD

**Issue by Htwos** [MaaAssistantArknights/MaaAssistantArknights#9505]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

Mumu12 1920x1080 繁中服 萨米肉鸽无法自动肉鸽问题

具体体现为干员招募完后无法点击探索冰原进入肉鸽，且部分关卡识别错误

一开始用的2560x1440，看到其他人也出现了萨米肉鸽无法正常代理的问题，但是有的人切换分辨率后得到解决了。我试了一下结果发现我切换了1920x1080之后还是无法正常启动

希望能尽快得到帮助，非常感谢

### Version

Resource Version: 火山旅夢
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16038798/asst.log)
[gui.log](https://github.com/user-attachments/files/16038799/gui.log)
很抱歉本人电脑没有办法打开log查看）我也看不懂sorry

问题出现的大致时间点应该是2024.6.29 12:50 左右，应当是上传log时最近启动MAA时发生的问题，直接看最后的log内容应该对应的就是问题发生对应的log？）

### 截图

![eg](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/164329828/50531515-2f8e-4c1b-8f47-f5263ac174cc)

### 还有别的吗？

MUMU12模拟器 Windows11

**Comment by Rbqwow** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55343783/5571c855-e4c3-481d-b8eb-a47e2ef86ded)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/55343783/18022596-fa04-4c6c-bb03-e98f2c15b540)

先更新公测

**Comment by Htwos** [comment]
公测版可以打肉鸽了，感谢
