### ISSUE TITLE
日服 自动战斗 战斗期间无法识别到艾雅法拉

### ISSUE THREAD

**Issue by ShirasawaYui** [MaaAssistantArknights/MaaAssistantArknights#9512]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

编队时可以正确识别到艾雅法拉，进入战斗后则无法识别到
无法在缓存里avatars下生成艾雅法拉头像

[2024-06-30 19:22:49.493][TRC][Px3738][Tx39e8] The best match is { name: , matched: [ 0, 0, 60, 60 ] } 

[2024-06-30 19:22:49.981][ERR][Px3738][Tx39e8] No oper 艾雅法拉

我记得以前是没有这个问题的，真奇怪

### Version

Resource Version: 銀心湖鉄道
UI Version: v5.4.0-beta.2.d032.gbc14fcb0d
Core Version: v5.4.0-beta.2.d032.gbc14fcb0d

### 日志文件

[asst.log](https://github.com/user-attachments/files/16044143/asst.log)

### 还有别的吗？

mumu12 720P900P1080P切换过 增强模式开关切换尝试过，无影响
GPU加速 7900xt 开关切换过无影响

**Comment by Manicsteiner** [comment]
エイヤフィヤトラ识别成了エイヤフヤトラ，缺字，个人没遇到过，下次一起改吧

**Comment by ShirasawaYui** [comment]
于今日将模拟器分辨率修改为2k后顺利识别
