### ISSUE TITLE
在基建换班结束时候 开始了刷理智任务十秒然后出现了刷理智错误

### ISSUE THREAD

**Issue by zhangchuangyuan** [MaaAssistantArknights/MaaAssistantArknights#9513]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

应该是一个概率性事件 在基建换班结束时候 开始了刷理智任务十秒然后出现了错误

理智开始任务在[2024-06-30 08:10:28.202]

### Version

Resource Version: 空想花庭·复刻
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16044192/asst.log)
[gui.log](https://github.com/user-attachments/files/16044193/gui.log)

**Comment by SUPERDAIDAI007** [comment]
同刷理智时出现的，会卡在吃理智药环节
![Snipaste_2024-07-06_11-16-27](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115518104/197f32d7-d35c-4ad2-91e6-4eb3f4a356ed)
![Snipaste_2024-07-06_11-16-43](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/115518104/149b1a9f-6b62-448a-85e6-768b4776d4d1)
[gui.log](https://github.com/user-attachments/files/16114747/gui.log)
[asst.log](https://github.com/user-attachments/files/16114748/asst.log)
