### ISSUE TITLE
繁中服 自動肉鴿卡密文版選擇

### ISSUE THREAD

**Issue by IzuYanze** [MaaAssistantArknights/MaaAssistantArknights#9514]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用自動肉鴿的時候 會卡在這兩個畫面反覆橫跳
可能是部分圖片資料缺失  但我不會修  還請開發人員多多幫忙
![Screenshot_2024 07 01_22 57 12 996](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99862702/8908ddf3-c5c1-44b9-9a01-3a9119ac50b5)
![Screenshot_2024 07 01_22 57 16 362](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99862702/0f783680-1ba4-450b-a35c-2a4b28e58f55)

### Version

Resource Version: 火山旅夢
UI Version: v5.4.0-beta.2.d017.g8bfb223da
Core Version: v5.4.0-beta.2.d032.gbc14fcb0d

### 日志文件

[asst.log](https://github.com/user-attachments/files/16054810/asst.log)
[gui.log](https://github.com/user-attachments/files/16054811/gui.log)
事情發生約於2024.7.1 22~23點左右

### 截图

設定如下
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99862702/7957ac59-2381-4171-a0d8-e7ee3f6caba3)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99862702/54df981d-9ffd-4c09-b170-74d9d3b3c2c3)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99862702/47897ffe-7dc3-4270-935e-2c54913e9486)

### 还有别的吗？

Blue Stack國際版版本:
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99862702/879ad3b5-d4b9-4585-96cf-0c7e219cc36d)
辛苦開發人員了

**Comment by momomochi987** [comment]
@IzuYanze 

嗨，可以幫我照著這裡提到的方法再試一次，看會不會發生同樣問題嗎?

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9472#issuecomment-2212828949

**Comment by IzuYanze** [comment]
不好意思  我現在更新到Core Version: v5.4.1-alpha.1.d022.ga340d515a   請問還需要降版本回去(雖然我不知道有沒有簡單的方法)做測試嗎?

**Comment by momomochi987** [comment]
> @momomochi987 不好意思 我現在更新到Core Version: v5.4.1-alpha.1.d022.ga340d515a 請問還需要降版本回去(雖然我不知道有沒有簡單的方法)做測試嗎?

可以用你目前的版本試就好

只要確認 resource\global\txwy\resource\template 裡
同時有 Sami@Roguelike@GetDropSelect.png 跟 Sami@Roguelike@GetDropSelectReward.png 這兩張圖片

tasks.json 直接用上面提到的留言裡面附的檔案取代就好


再麻煩你試試看，謝謝 :D

**Comment by ABA2396** [comment]
感觉不一定行吧，内测版加了几个task，如果少了可能会报错

**Comment by ABA2396** [comment]
照着那个方式自己改下可以

**Comment by momomochi987** [comment]
> 感觉不一定行吧，内测版加了几个task，如果少了可能会报错

這部分我忘記了，謝提醒 QQ

@IzuYanze 我剛剛自己更新到最新內測版，用內測版測
發現會有其他問題會讓你沒辦法自動肉鴿
（詳細可以閱讀目前的置頂 issue,有在處理了）

可能要麻煩你另外下載 5.4.0，
用 5.4.0 這個版本去嘗試看看
