### ISSUE TITLE
会客室：只差一个线索时，使用晓歌以及对应线索的干员

### ISSUE THREAD

**Issue by KobeIverson0** [MaaAssistantArknights/MaaAssistantArknights#9515]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

只差一个线索时，永远对晓歌视而不见，仍然使用伺夜和普通加速干员，导致很难拿到需要的线索。

**Comment by Constrat** [comment]
The enhanced % that the clue operator gives is virtually non-existant. This would require a lot of code and algorithm for a FEAT that does not really make sense. Exchange clues with friends (which MAA already does)
