### ISSUE TITLE
繁中服薩米肉鴿選完初始幹員後，沒有開始探索

### ISSUE THREAD

**Issue by phzhao12** [MaaAssistantArknights/MaaAssistantArknights#9518]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

1.臺服薩米肉鴿選完初始幹員後，沒有開始探索。
2.等待一段時間後，MAA放棄本次探索
3.MAA自動開啟下一輪薩米肉鴿並且開始選擇初始幹員
4.再次卡在沒有開始探索的步驟
(5.當我「手動」按下開始探索後，後續的關卡戰鬥功能都是正常的，每次新的一輪都會卡在開始探索)

我推測MAA沒有正確辨識開始探索的圖標，或者是沒有正確的點擊開始探索的螢幕位置
![螢幕擷取畫面 (2)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143981658/2e8f8cb6-37a5-4d54-b357-a175b5be193a)
![螢幕擷取畫面 2024-07-03 103418](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143981658/e6a611de-8e84-4228-95d6-5e33ac0f368a)

### Version

資源版本號：火山旅夢
UI版本號：v5.3.1
Core版本號：v5.3.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16076314/asst.log)
[gui.log](https://github.com/user-attachments/files/16076316/gui.log)

### 截图

![2024-07-03_10-04-54-690_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143981658/15c0042c-5463-4e18-a0f7-8eae7cc45c8b)
![2024-07-03_10-05-00-045_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143981658/187fdf58-96f4-4d05-ba0e-c97ac6588acf)
![2024-07-03_10-33-10-782_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143981658/60460b8e-e945-43b2-a98f-5fa367fe9bba)
![2024-07-03_10-33-14-708_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/143981658/9a9541aa-d183-4aa5-ab0a-4733be1bb1ab)
這些是debug資料夾內相關的圖片

### 还有别的吗？

使用的模擬器：藍疊Bluestacks 5 Android 11 x64 版本
操作系統：Windows 11 家用版
解析度：1920x1080

**Comment by Daydreamer114** [comment]
[resource/template/Sami@Roguelike@EnterAfterRecruit.png](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/template/Sami%40Roguelike%40EnterAfterRecruit.png)

识别这个图片的任务执行了，但是连0.5的得分都没有
是否考虑改为clickRect或为台服图标重新截图？

**Comment by XuQingTW** [comment]
今天1280*720跑沒問題
明天調高測試

**Comment by Daydreamer114** [comment]
此问题已在5.4.0修复，若再次遇到请再次提交issue
