### ISSUE TITLE
生息演算，经常在网络连接较长时间（超过），直接退出

### ISSUE THREAD

**Issue by xinoer** [MaaAssistantArknights/MaaAssistantArknights#9519]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

生息演算功能，mumu12模拟器，在链接神经网络时（结算），网络连接较长时间（超过10s），直接说任务出错，任务完成，可以延长等待时间
![1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/20312330/efe2d8c6-992e-4af6-a212-e549120c4e69)
![2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/20312330/4167b8e4-d065-444a-a7db-293e1d0bee3a)

### Version

MAA-5.3.0到5.4.0-bata2均存在该问题

### 日志文件

[asst.log](https://github.com/user-attachments/files/16076774/asst.log)
[gui.log](https://github.com/user-attachments/files/16076775/gui.log)
图片中有时间

### 还有别的吗？

mumu12最新版，win11专业版

**Comment by SindelXD** [comment]
相同问题

**Comment by RicKang22** [comment]
我之前也是，试了下把高级设置中的通过制造刷点数去掉后就行了

**Comment by grzzk** [comment]
同样的问题，我是没有存档刷点数，然后只要一卡就会任务失败。
基本上半小时就会出现一次。
我使用的是雷神模拟器。

**Comment by Alan-Charred** [comment]
您好，感谢反馈。生息演算任务流已被重构，请使用 MAA 最新版本试试。如果还出现同样的问题，请上传新的 asst.log，我们会尽快优化。评论区的诸位也是。

我们已经在许多地方加入了等待流程，MAA 若识别到加载界面文字 <正在提交反馈至神经>，会选择等待而不是直接报错。虽然依然有概率因为文字淡入淡出或别的原因出问题，但不应频繁发生。

@grzzk 您使用的是最新版本吗？如果这个情况一直出现，请上传一下 asst.log 文件，提供一下任务失败时的游戏画面截图，感谢。

**Comment by grzzk** [comment]
@Alan-Charred  是的。 我使用的是 5.6.0 公测版的资源和构建日期是9月6号1:26分的版本。
生息使用的是"无存档，通过进出关卡刷生息点数“
[asst.bak.zip](https://github.com/user-attachments/files/17005075/asst.bak.zip)
我在刷取的时候，基本上是半小时左右必出一次失败。
失败时的游戏截图因为我已经守着把点数刷完了，所以没法截图。
基本上都是卡在和楼主差不多的位置（就是在对话完后，点击左上角退出，离开当前区块，确认离开之后）
文件比较大（23M） 所以我打包成了 zip 文件
asst.log

**Comment by Alan-Charred** [comment]
> 本上是半小时左右必出一次失败。
> 失败时的游戏截图因为我已经守着把点数刷完了，所以没法截图。
> 基本上都是卡在和楼主差不多的位置（就是在对话完后，点击左上角退出，离开当前区块，确认离开之后）
> 文件比较大（23M） 所以我打包成

您好，您描述的问题，我们已经在 #10464 中尝试修复。下个月请您用最新的 MAA版本再试试，如果还遇到这样的问题，开一个新的 issue，感谢！

**Comment by Alan-Charred** [comment]
修复补丁已经推出一段时间了，我现在关闭这个 Issue。
如果还遇到同样的问题，欢迎 reopen 并分享最新的日志文件与截图（有录屏更好）。
如果遇到新的问题，还请新开一个 Issue，我们会尽快处理～
