### ISSUE TITLE
5.4.0beta2版本无法启动，5.3.1版本正常，运行库已更新

### ISSUE THREAD

**Issue by stickdate** [MaaAssistantArknights/MaaAssistantArknights#9523]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

5.4.0beta2版本启动就报错，单独解压纯净版MAA也没有解决，运行库已经更新，版本如图。

### Version

5.4.0-beta.2-win-x64

### 日志文件

[gui.log](https://github.com/user-attachments/files/16091910/gui.log)

### 截图

![版本截图](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/147569944/14e9c496-cf73-4b47-b2db-933a00596660)

### 还有别的吗？

系统windows7

**Comment by ABA2396** [comment]
win7用不了了

**Comment by ABA2396** [comment]
不是因为加了啥东西，是因为GitHub action更新之后打出来的包win7跑不了（）

**Comment by Rbqwow** [comment]
v5.4.0-beta.1.d037.g98ecb301b 开始不能用的 不知道微软干啥了 或许可以试试自己编译

**Comment by stickdate** [comment]
也就是以后WIN7就得告别MAA了。

**Comment by ABA2396** [comment]
按.net8的支持来分，最后支持的版本是4.28.3。按能运行的最后版本来看，是5.3.1
