### ISSUE TITLE
MAA启动报错“无效的命令 试图运行无效的命令”

### ISSUE THREAD

**Issue by yang932** [MaaAssistantArknights/MaaAssistantArknights#9525]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在打开MAA主程序时，会弹出Windows的报错窗口“MAA.exe - 异常”，窗口内容为“无效的命令 试图运行无效的命令”
![屏幕截图(77)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35618570/215cf8f3-046f-42d5-8975-dfcccfa95de8)
此时MAA主程序窗口可正常操作，但所有游戏设置和连接设置均无法更改，任务无法启动
![屏幕截图(78)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35618570/644255ba-a17b-4cc6-8909-6f0454883db9)
![屏幕截图(79)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35618570/eb2e5dfc-e919-4d20-adc9-ae3a305a2c5a)
此时通过任何方式关闭报错窗口（点击“确定”或直接关闭窗口）均会使MAA主程序直接退出

### Version

Resource Version: 空想花庭·复刻
UI Version: v5.4.0-beta.2.d032.gbc14fcb0d
Core Version: v5.4.0-beta.2.d032.gbc14fcb0d

### 日志文件

[asst.log](https://github.com/user-attachments/files/16094184/asst.log)
[gui.log](https://github.com/user-attachments/files/16094185/gui.log)

### 截图

![屏幕截图(77)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35618570/28b2de59-082f-4098-a07c-dfbd86439e43)
![屏幕截图(78)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35618570/5f983d88-364d-4007-86e7-77638c20e6a1)
![屏幕截图(79)](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35618570/c15db61c-6459-4f8a-a096-8a99bef8d542)

### 还有别的吗？

Microsoft Windows 版本21H2（操作系统内部版本19044.1288）（Windows 10 LTSC 2021）
未安装任何除驱动程序之外的Windows更新
已安装Microsoft Visual C++运行库2008、2010、2012、2013、2015-2022全部x64、x86版本与Microsoft Windows Desktop Runtime - 8.0.6 (x64)

**Comment by Manicsteiner** [comment]
图二，未填写adb连接地址

**Comment by yang932** [comment]
> 图二，未填写adb连接地址

不，该项处于不可更改状态，无法填写adb连接地址

**Comment by yang932** [comment]
> 图二，未填写adb连接地址

该项已在问题描述中详细说明
> 所有游戏设置和连接设置均无法更改

**Comment by Manicsteiner** [comment]
再往上一级的客户端类型也没有选择

**Comment by yang932** [comment]
> 再往上一级的客户端类型也没有选择

那个也选不了
> **所有**游戏设置和连接设置均无法更改

**Comment by yang932** [comment]
> 再往上一级的客户端类型也没有选择那个也选不了> **所有**游戏设置和连接设置均无法更改发件人: ***@***.*** ***@***.***> 代表 Manicsteiner ***@***.***>发送时间: 星期五, 七月 5, 2024 10:39:47 上午收件人: MaaAssistantArknights/MaaAssistantArknights ***@***.***>抄送: Yang Chenjian ***@***.***>; Author ***@***.***>主题: Re: [MaaAssistantArknights/MaaAssistantArknights] MAA启动报错“无效的命令 试图运行无效的命令” (Issue #9525)
再往上一级的客户端类型也没有选择

**Comment by yang932** [comment]
> 再往上一级的客户端类型也没有选择


那个也选不了
> **所有**_游戏设置_和_连接设置_均无法更改

**Comment by Rbqwow** [comment]
#8335
大概率和maa没关系 有关系也不知道为啥 微软自己的东西都乱七八糟的

**Comment by yang932** [comment]
> #8335
> 大概率和maa没关系 有关系也不知道为啥 用的都是微软自己的东西
> 看看事件查看器里有没有啥东西吧

确实有![屏幕截图(82).png](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/35618570/98c25a44-83e8-445a-823c-88212e4e2b52)
