### ISSUE TITLE
繁中服無法辨識純燼艾雅法拉及麒麟X夜刀

### ISSUE THREAD

**Issue by laetita0319** [MaaAssistantArknights/MaaAssistantArknights#9526]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在使用作業代碼時
發現只要遇到麒麟X夜刀
及純燼艾雅法拉時
就會卡住

### Version

5.3.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16100450/asst.log)
[gui.log](https://github.com/user-attachments/files/16100453/gui.log)

麒麟X夜刀無法辨識時間點
2024-07-04 22:20:41.753
2024-07-04 22:25:23.054

純燼艾雅法拉無法辨識時間點
2024-07-04 22:38:21.268
2024-07-04 22:41:41.418

**Comment by Constrat** [comment]
> 5.3.1

> - [X]  我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况

**Comment by paul0665** [comment]
最新內側版尚未修復

[asst.log](https://github.com/user-attachments/files/16102251/asst.log)
[gui.log](https://github.com/user-attachments/files/16102253/gui.log)

**Comment by paul0665** [comment]
不知道跟這有沒有關係
作業網站上的是顯示X不是R
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/47947919/d230d077-d208-4041-80a6-9ed94b07e8ed)

**Comment by Constrat** [comment]
Probably. Hypergryph decided to change the name of the operator. All older copilots are now broken, as MAA now uses `R` instead of `X`
