### ISSUE TITLE
MumuExtras未生效，V3.9.2

### ISSUE THREAD

**Issue by Ark-Schwarz** [MaaAssistantArknights/MaaAssistantArknights#9529]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及
- [X] 我正在使用最新的 MAA 内测版本和最新的**官版** MuMu 模拟器
- [X] 我已参考文档确定安装路径、实例编号、屏幕编号填写正确，并确认在关闭截图增强模式后问题消失
- [ ] 我未开启高帧率模式，且显存使用策略为“画面表现更好”
- [ ] 我正在使用后台保活功能，并确定该问题仅在开启后台保活时出现

### 问题描述

Mumu模拟器默认路径为这个，改了名称之后模拟器就启动不了了，如果maa路径为这个就会提示安装路径错误。
Shell是安装路径，但每次都无法生效
图片放在"截图"里面了

### Version

Resource Version: 空想花庭·复刻
UI Version: v5.4.0-beta.2.d032.gbc14fcb0d
Core Version: v5.4.0-beta.2.d032.gbc14fcb0d
Mumu12: V3.9.2

### MAA 日志文件

[asst.log](https://github.com/user-attachments/files/16103932/asst.log)
[gui.log](https://github.com/user-attachments/files/16103933/gui.log)

### MuMu 问题诊断

基础信息
UUID :  d448d084-aafb-4c4f-a524-cc730caf5a48
模拟器版本 :  3.9.2.3069
模拟器磁盘（可用/总）空间 :  115.7GB/125GB
日志路径 :  D:\APP\Mumu\MuMu Player 12\vms\MuMuPlayer-12.0-0\logs\

运行环境
VT :  开启
Hyper-V :  关闭
网络环境检测 :  正常
以管理员运行方式 :  是
DirectX 11是否安装 :  是
防火墙 :  开启（建议关闭）

电脑配置
主板型号 :  Manufacturer: LENOVO  Product: LNVNB161216
CPU :  AMD Ryzen 7 5800H with Radeon Graphics
系统版本 :  Windows 11 64-bit Kernel 10.0.22000
显卡驱动 :  正常
显卡驱动型号 :  555.99 (20240601)
所有显卡 :  NVIDIA GeForce RTX 3060 Laptop GPU  |  Microsoft Basic Render Driver
当前使用显卡 :  NVIDIA GeForce RTX 3060 Laptop GPU
安装磁盘(可用/总)空间 :  104.4GB/294.7GB
可用内存/总内存 :  17.9GB/31.9GB

模拟器设置
Root :  开启
显卡渲染模式 :  Vulkan 模式（独家）
性能设置 :  6核/12GB
手机型号 :  Samsung Galaxy S22 Ultra
分辨率 :  2560 * 1440
高帧率 :  开启
后台保活 :  关闭

连接设备
音频输入 :  已连接
音频输出 :  已连接

网络信息
MuMu DNS :  202.96.199.133
电脑DNS :  202.96.199.133
Rom MAC地址 :  08:73:c2:da:80:00

ADB调试端口 :  16384
MuMu出口IP地址 :  
电脑出口IP地址 :  

其它信息
其它版本信息 :  vm: 120.1.70.008 hyperv: 6.3.23.0 renderer: 0.0.178.0
Vendor :  NetEase
OpenGL Renderer :  MuMu GL (Vulkan 1.3.278 NVIDIA GeForce RTX 3060 Laptop GPU 555.99 _A_)
OpenGL Version :  OpenGL ES 3.2 V132
运行时间 :  0 : 21 : 40

### 截图

<img width="598" alt="屏幕截图 2024-07-05 094206" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46624134/962c5e42-5fc1-4b91-b5a1-0f7386ec35cf">
<img width="453" alt="屏幕截图 2024-07-05 094213" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46624134/ebbab3bd-4ce7-48e1-9371-6fb68d501de1">
<img width="192" alt="屏幕截图 2024-07-05 094226" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46624134/7c1df7b6-0996-45f2-bbe9-795c8263cc9d">
<img width="706" alt="屏幕截图 2024-07-05 094259" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46624134/e4c97144-c14b-4381-acef-b77d2f59604e">
<img width="661" alt="屏幕截图 2024-07-05 094556" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46624134/719c87cb-3a89-46fb-a797-fd272db0f602">
<img width="661" alt="屏幕截图 2024-07-05 094609" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46624134/07a30ce8-af63-4e53-8af1-7e298bb00365">

**Comment by dupontjoy** [comment]
路径写错了，写到mumuplayer 12就夠了

**Comment by Ark-Schwarz** [comment]
可以了，mumuplayer 12后面不能带\，带\ 切换页面后就直接空了
