### ISSUE TITLE
打不开，直接闪退，甚至没有log

### ISSUE THREAD

**Issue by vista98** [MaaAssistantArknights/MaaAssistantArknights#953]
C++运行库我也装了，.NET我也装了，CPU是AMD R7-5800H，指令集也肯定没问题，可就是打不开啊
没有log我不敢传bug，就建其他了
望解答！

**Comment by MistEO** [comment]
下的 ota 包？

**Comment by vista98** [comment]
OK，明白了，我就是照着官网试了半天....
