### ISSUE TITLE
肉鸽刷源石锭

### ISSUE THREAD

**Issue by ZacKoliy** [MaaAssistantArknights/MaaAssistantArknights#9530]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

N15刷 源石锭很容易失败, 

### 有什么好的想法？

希望, 可以指定难度等级,然后刷源石锭

**Comment by Rbqwow** [comment]
本来就是自己手动选择难度啊...?
