### ISSUE TITLE
Auto I.S stuck on "Signal Lost" when doing Sami Roguelike

### ISSUE THREAD

**Issue by Faryzal2020** [MaaAssistantArknights/MaaAssistantArknights#9536]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

Just as the title says, MAA does not proceed when the exploration fails and stops in the Signal Lost screen, with no error showing up in the GUI debug screen

### Version

Resource Version: Il Siracusano - Retrospection
UI Version: v5.4.0-beta.2
Core Version: v5.4.0-beta.2

### Log files

[debug.zip](https://github.com/user-attachments/files/16114863/debug.zip)

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/8612170/e36c597d-7792-46f1-b973-92716f0019c0)

**Comment by ABA2396** [comment]
cc @Constrat

**Comment by Constrat** [comment]
@Faryzal2020 GUI debug usually doesn't show much. We use asst.log for that.
Sami@Roguelike@MissionFailedFlag.png score: 0.79178 rect: [ 552, 351, 158, 47 ] roi: [ 504, 163, 480, 267 ]
The score is just under and 0.8 threshold. 
This is usually caused by not using the recommended resolution. Are you on 1920x1080? if not change to 1920x1080 and the issue will disappear

**Comment by Constrat** [comment]
@ABA2396 I'm thinking of changing the EN template to add the resolution. As 80% of the issues come from that. No one reads the FAQ apparently XD

**Comment by ABA2396** [comment]
Are there any that are templates to recognize text and do they work above 1080p, like 2k?
But it's true that 2k+ isn't really recommended either, and Ark doesn't handle sliding very well in certain scenes

**Comment by Constrat** [comment]
I don't think so. Every template is very precise and connected to that resolution (especially the ones containing text). But usually the blurriness is enough to make it not work. 
In this case Sami@Roguelike@MissionFailedFlag is made of text. 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/999894c1-484c-4757-9a18-6a9b623ea067)
I remember we switched this from OCR (can't remember why)

**Comment by Constrat** [comment]
> Are there any that are templates to recognize text and do they work above 1080p, like 2k? But it's true that 2k+ isn't really recommended either, and Ark doesn't handle sliding very well in certain scenes

The most common issue is actually the opposite. By default most Emulators come with 1600x900, or even 1280x720. On the CN 1280x720 works really well, the text is still visible enough, but on YostarEN the text is much smaller making the OCR almost impossible (it's better downscale it through software than to render it directly at 1280. I could change every template to 1600x900 but I'm not sure about the text rendering)

**Comment by ABA2396** [comment]
Not all of us who play the US client use English feedback, I feel that we should do it in the ui prompt or let the bot add a comment when adding the client:EN.

**Comment by Constrat** [comment]
Oh, the UI looks interesting. A custom prompt when changing from "any" -> "YostarEN", that under "Restart immediately to apply changes" adds a "Make sure the emulator is running at 1920x1080" with i18n.
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/b6d6686a-86f2-45e0-8523-e81b919f4fee)

**Comment by Faryzal2020** [comment]
> @Faryzal2020 GUI debug usually doesn't show much. We use asst.log for that. Sami@[Roguelike@MissionFailedFlag.png](mailto:Roguelike@MissionFailedFlag.png) score: 0.79178 rect: [ 552, 351, 158, 47 ] roi: [ 504, 163, 480, 267 ]
> 
> ### The score is just under and 0.8 threshold.
> ### This is usually caused by not using the recommended resolution. Are you on 1920x1080? if not change to 1920x1080 and the issue will disappear

i'm playing on memu with default resolution which is 720p, i'll set it to 1080p and test again.

**Comment by Faryzal2020** [comment]
> @ABA2396 I'm thinking of changing the EN template to add the resolution requirement. As 80% of the issues come from that. No one reads the FAQ apparently XD
> 
> ~- [ ] Is the emulator set to 1920x1080?~
> 
> * [ ]  I'm sure the emulator is set to 1920x1080
> 
> Perhaps it should not even be a check. But directly a notification before opening the issue.

i didn't see anything about requiring 1080p in FAQ (https://maa.plus/docs/en-us/1.2-FAQ.html), but i've read an info about MEmu in https://maa.plus/docs/en-us/1.3-EMULATOR_SUPPORTS.html that says its recommended to use mainstream resolutions, includes 720p, so i assumed that it would be fine to use that resolution.

**Comment by Constrat** [comment]
It's in the beginner's guide, my bad. But it's true that it's not easily accessible. It's something that's needed in the client itself. I'm working on a feat for it.
