### ISSUE TITLE
国际服萨米肉鸽中无法选择锏开局（未解决）

### ISSUE THREAD

**Issue by TanChunHong717** [MaaAssistantArknights/MaaAssistantArknights#9537]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

此问题已在 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9455#issue-2367883034 提起，但未得到解决。在国际服萨米肉鸽中选择锏开局，MAA无法识别并选择锏，卡在了近卫招募界面，最后选择了百嘉开。

### Version

Resource Version:  Celebration - Kernel
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

14：38：41 开始肉鸽
14：38：57 开始探索
[asst.bak.log](https://github.com/user-attachments/files/16115118/asst.bak.log)
[gui.log](https://github.com/user-attachments/files/16115119/gui.log)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/39e2459c-79ad-4d8b-8089-8af34c5832cb)
版本还没更新，5.3.1没有支持这个
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/d4530223-506c-4eba-9883-76d4bcbe898c)
