### ISSUE TITLE
傀影肉鸽卡在选人界面

### ISSUE THREAD

**Issue by 576217396** [MaaAssistantArknights/MaaAssistantArknights#9540]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

傀影肉鸽最高难度开局会给负面道具，如果给了加干员招募希望的道具，就会让6星干员的招募希望大于上限，选择了开局借好友干员时，就会一直在好友助战界面刷新，无法正常挂机

### Version

资源版本：空想花庭·复刻
界面版本：V5.3.1
核心版本：V5.3.1

### 日志文件

[asst.bak.log](https://github.com/user-attachments/files/16115744/asst.bak.log)
[gui.log](https://github.com/user-attachments/files/16115746/gui.log)

**Comment by 576217396** [comment]
> 你的日志没有上传成功，请重新上传。
> 
> Your log did not upload successfully, please re-upload it.

[asst.log](https://github.com/user-attachments/files/16115770/asst.log)
[gui.log](https://github.com/user-attachments/files/16115771/gui.log)

刚发完就又出现了一次，这是新日志和截图
![捕获](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/174872921/5a49ede4-94ec-4fd5-bbf8-c821f80c22da)

**Comment by Saratoga-Official** [comment]
duplicate of 10108

无计划，原因同上
