### ISSUE TITLE
连续开启maa大约30小时，内存占用8.7g,

### ISSUE THREAD

**Issue by HHD5488** [MaaAssistantArknights/MaaAssistantArknights#9541]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

连续开启maa大约30小时，内存占用8.7g,此前的版本未出现该类情况，在更新新版本后只开启了gpu加速推理，其他未变
<img width="572" alt="Screenshot 2024-07-06 200505" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/155243040/623cb1ee-1923-4ec3-af4b-fb73f34f1a84">

### Version

Resource Version: 空想花庭·复刻
UI Version: v5.4.0-beta.2
Core Version: v5.4.0-beta.2

### 日志文件

[gui.log](https://github.com/user-attachments/files/16115983/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/16115984/asst.bak.log)

### 截图

<img width="572" alt="Screenshot 2024-07-06 200505" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/155243040/cb1d8127-39eb-4c82-a458-9057db273f46">

### 还有别的吗？

mumu模拟器
ultra5 155h 无独显
32g lpddr5x内存

**Comment by Constrat** [comment]
When you see for "30 hours". Was it running IS? SSS? Or was it just open without running tasks? I have 3 MAAs open on a server of mine that stay for weeks and have never encountered this.

**Comment by Rbqwow** [comment]
在跑什么吗 自动肉鸽或者定时任务之类的

感觉很像摸不到头脑的偶发事件
