### ISSUE TITLE
MAA无法连接模拟器ADB

### ISSUE THREAD

**Issue by kourindoupota** [MaaAssistantArknights/MaaAssistantArknights#9544]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新后无法连接模拟器，表现为只显示“正在连接模拟器..."
手动检查adb后发现单启动模拟器可以使用 connect指令获得反馈，启动maa后cmd界面无法反馈

### Version

Core Version: v5.4.0-beta.2.d032.gbc14fcb0d

### 日志文件

[gui.log](https://github.com/user-attachments/files/16118119/gui.log)
[asst.log](https://github.com/user-attachments/files/16118120/asst.log)
问题在12：16分以后持续

**Comment by ABA2396** [comment]
你端口号呢，自己没填就打开自动检测啊

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/0ba6507c-85f4-4093-a82c-5784e9b107f8)
你光给个 `> adb connect` 肯定也连不上模拟器啊

**Comment by kourindoupota** [comment]
![19B307194FB0226D7FEC8FA4D9E11DAD](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/7702118/845e490b-1186-4d6f-be44-15133e58cb5c)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/7702118/e992db82-a328-4c36-8715-0fe15a2fc896)

可能有些误会我补充一下，自动也连不上，手动写端口（上图）也是连不上的，端口我是照搬的mumu诊断显示的端口号netstat也看得到，就一直显示这些，按停止也没有效果

**Comment by kourindoupota** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/7702118/830ff16d-4635-4b72-b432-01384243f3a8)
[asst.log](https://github.com/user-attachments/files/16118856/asst.log)
[gui.log](https://github.com/user-attachments/files/16118857/gui.log)
可能有些误会，log里面记录的自动检测的端口是空的，我不知道是怎么回事，但是我自动检测和手动输入都又试过一次了（log里面从18：16开始），后面20分左右手动输入的端口和mumu诊断的应该是一致的，麻烦您检查一下

**Comment by kourindoupota** [comment]
还是说要用那个出口ip地址？

**Comment by Rbqwow** [comment]
```
"address":"127.0.0.1:16348"
```
你输错了啊(

**Comment by kourindoupota** [comment]
![QQ截图20240707222742](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/7702118/e81816e1-14fb-460c-933e-2c6272306936)
按您说的改了下设置
[asst.log](https://github.com/user-attachments/files/16119697/asst.log)
[gui.log](https://github.com/user-attachments/files/16119698/gui.log)
似乎还是不太行的样子，劳烦两位了，慢慢解决吧不着急

**Comment by ABA2396** [comment]
有点没看懂，这里connect又超时了，感觉和之前mumu加的联网验证有点像了。点 关于我们-QQ群 加群找个管理远程看看吧
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/e4a6b1ea-fbaa-43f7-9abf-ea9ddbfb0de0)

**Comment by ABA2396** [comment]
还有adb是分版本的，你要保证你新开的adb和之前开着的是同一个，不然新开一个adb可能会遇到连不上或者直接把前一个adb杀了，要在任务管理器里把adb.exe给关了

**Comment by Rbqwow** [comment]
咋样了(
