### ISSUE TITLE
完成后能否添加“退出明日方舟和MAA”选项

### ISSUE THREAD

**Issue by Mioscout** [MaaAssistantArknights/MaaAssistantArknights#9545]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

我的模拟器除舟外还有其他用途，因此通常会使用退出明日方舟这一选项。然后手动关掉MAA。

### 有什么好的想法？

鉴于退出明日方舟和退出MAA均是已经实现的功能，能否将这两个功能结合，再添加一个“退出明日方舟和MAA”的选项

**Comment by Rbqwow** [comment]
cc @ABA2396

说好的net8之后写呢((

**Comment by ABA2396** [comment]
所以写的人呢）

**Comment by Rbqwow** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6477#issuecomment-1857162548
