### ISSUE TITLE
繁中服萨米肉鸽关卡奖励卡住

### ISSUE THREAD

**Issue by vonnoq** [MaaAssistantArknights/MaaAssistantArknights#9547]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

打完关卡后有机会卡在奖励领取页面

感觉常常在三个以上时遇到

看日志似乎在不断取消暂停

MAA停止并重新开始可正常继续运作

### Version

Resource Version: 火山旅夢
UI Version: v5.4.0
Core Version: v5.4.0

### 日志文件

[asst.zip](https://github.com/user-attachments/files/16118956/asst.zip)
[gui.log](https://github.com/user-attachments/files/16118957/gui.log)

### 截图

![Screenshot_2024 07 07_19 25 29 102](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121179930/5260c2ef-1d6d-4427-b925-74a7fbbd1b82)

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/121179930/9371593a-505a-4da9-99d4-16c718bdb4fc

**Comment by momomochi987** [comment]
@vonnoq 

嗨，可以幫我照著這裡提到的方法再試一次，看會不會發生同樣問題嗎?

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9472#issuecomment-2212828949
