### ISSUE TITLE
在设置了完成任务动作后，在公招识别进行识别会触发动作

### ISSUE THREAD

**Issue by SnailZq** [MaaAssistantArknights/MaaAssistantArknights#955]

**Comment by zzyyyl** [comment]
草，公招问题那么多的吗（？发个日志谢谢

**Comment by zzyyyl** [comment]
> > 公招问题那么多的吗（？发个日志谢谢
> 
> 不是，现在任务完成会给 `AllTaskCompleted` 消息，wpf 那边收到消息就 自动关机/退出模拟器/。。。了

也就是说跟 #956 是一个问题对吧（
要不要关一个？

**Comment by zzyyyl** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/v4.0.0/src/MeoAsstGui/Helper/AsstProxy.cs#L289

不对吧，`AllTasksCompleted` 会直接在 UI 上显示任务已全部完成，但是公招识别的时候没有这玩意啊？

**Comment by zzyyyl** [comment]
Author 是不是在公招的时候点了停止（？
@SnailZq
