### ISSUE TITLE
[Feature Request] 文档翻译接入 Weblate

### ISSUE THREAD

**Issue by SherkeyXD** [MaaAssistantArknights/MaaAssistantArknights#9550]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

Weblate 前阵子更新了版本，支持 md 文件的翻译了

可以接入 Weblate 实现文档翻译流程的简化

### 有什么好的想法？

貌似得 Weblate 管理员来

### 其他内容

这个本来应该在文档重构时候实现的，但是拖太久了所以文档那个先合了

**Comment by SherkeyXD** [comment]
以及目前 Weblate 貌似又有冲突

**Comment by AlisaAkiron** [comment]
emmm, Weblate 对 Markdown 的支持还只能说是：如有（

不是很可用

https://docs.weblate.org/en/latest/formats/markdown.html
