### ISSUE TITLE
水月肉鸽卡在第一层：战斗完成界面。每次都有3个源石锭和一张招募券

### ISSUE THREAD

**Issue by 2907420372** [MaaAssistantArknights/MaaAssistantArknights#9557]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

水月肉鸽卡在第一层：战斗完成界面。每次都有3个源石锭和一张招募券，上一个版本就有了

### Version

Resource Version: 空想花庭·复刻
UI Version: v5.4.0
Core Version: v5.4.0

### Log files

[debug.zip](https://github.com/user-attachments/files/16121441/debug.zip)

### Screenshots

![水月反馈](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/162801316/37c960c9-c1ab-4351-996c-148ce5ca3e73)

**Comment by Alan-Charred** [comment]
请问现在这个bug还存在吗？应该修好了。

**Comment by 841003695** [comment]
> 请问现在这个bug还存在吗？应该修好了。

没有哇，我今天刷的时候还是这样

**Comment by Alan-Charred** [comment]
> > 请问现在这个bug还存在吗？应该修好了。
> 
> 
> 
> 没有哇，我今天刷的时候还是这样

您使用的是5.4.0版本吗？请试试看最新的5.4.1版本。

**Comment by 841003695** [comment]
重启了一下可以了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月15日(星期一) 中午12:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 水月肉鸽卡在第一层：战斗完成界面。每次都有3个源石锭和一张招募券 (Issue #9557)





   
请问现在这个bug还存在吗？应该修好了。
  
没有哇，我今天刷的时候还是这样
  
您使用的是5.4.0版本吗？请试试看最新的5.4.1版本。

**Comment by 2907420372** [comment]
重启一下，都不用修bug了，出bug重新开始嘛，对吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月15日(周一) 下午3:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 水月肉鸽卡在第一层：战斗完成界面。每次都有3个源石锭和一张招募券 (Issue #9557)




 重启了一下可以了 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "MaaAssistantArknights/MaaAssistantArknights"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年7月15日(星期一) 中午12:08 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 水月肉鸽卡在第一层：战斗完成界面。每次都有3个源石锭和一张招募券 (Issue #9557) 
 
 
 
 
 
     
 请问现在这个bug还存在吗？应该修好了。 
    
 没有哇，我今天刷的时候还是这样 
    
 您使用的是5.4.0版本吗？请试试看最新的5.4.1版本。

**Comment by Alan-Charred** [comment]
> 重启一下，都不用修bug了，出bug重新开始嘛，对吧
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月15日(周一) 下午3:12 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 水月肉鸽卡在第一层：战斗完成界面。每次都有3个源石锭和一张招募券 (Issue #9557) 重启了一下可以了
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "MaaAssistantArknights/MaaAssistantArknights" ***@***.***&amp;gt;; 发送时间:&amp;nbsp;2024年7月15日(星期一) 中午12:08 ***@***.***&amp;gt;; ***@***.******@***.***&amp;gt;; 主题:&amp;nbsp;Re: [MaaAssistantArknights/MaaAssistantArknights] 水月肉鸽卡在第一层：战斗完成界面。每次都有3个源石锭和一张招募券 (Issue #9557) 请问现在这个bug还存在吗？应该修好了。 没有哇，我今天刷的时候还是这样 您使用的是5.4.0版本吗？请试试看最新的5.4.1版本。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我相信这个Issue是我在5.4.0里因为失误引入的，并且已经在之后的测试版，包括最新的5.4.1里得到修复。请尝试一下。如果最新版本还遇到这样的问题，请直接在这里发消息告知我，我会第一时间检查。谢谢。

**Comment by Alan-Charred** [comment]
纠正一下，目前这个Bug只在内测版[v5.4.1-alpha.1.d070.gcef579741](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v5.4.1-alpha.1.d070.gcef579741)及之后版本得到修复。以防万一这个Issue开始先开着，下一个稳定版本发布后再来检查一下。

**Comment by zzyyyl** [comment]
这个问题是 DropsFlag 相关的 task 继承出问题导致 roi 变为全屏 [0 ,0, 1280, 720] 引起的，现在可以认为被 cache 默认值改为 false 修复了，之后我再修 roi 继承错误的问题
