### ISSUE TITLE
v5.4.1-内测版 自动肉鸽报错 Value cannot be null. (Parameter 'value')

### ISSUE THREAD

**Issue by jjolraman** [MaaAssistantArknights/MaaAssistantArknights#9559]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at MaaWpfGui.Main.AsstProxy.ProcSubTaskStart(JObject details)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

~~MAA-v5.4.0-beta.2-win-x64~~
v5.4.1-alpha.1.d022.ga340d515a

### Log files

[asst.log](https://github.com/user-attachments/files/16122348/asst.log)
[gui.log](https://github.com/user-attachments/files/16122349/gui.log)

**Comment by lirao** [comment]
Same issue
EN服 萨米肉鸽时发生的，画面停在结算页
![Screenshot_2024 07 07_20 56 15 182](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/6883412/c22b78ad-adba-4c42-8603-466c1448c95a)


[gui.log](https://github.com/user-attachments/files/16122476/gui.log)
[asst.log](https://github.com/user-attachments/files/16122477/asst.log)

**Comment by Elegetic** [comment]
The same issue for simplified Chinese server
萨米肉鸽刷源石锭时弹出，若不关闭报错窗口则不影响识别

Resource Version: 空想花庭·复刻
UI Version: v5.4.1-alpha.1.d022.ga340d515a
Core Version: v5.4.1-alpha.1.d022.ga340d515a

[asst.log](https://github.com/user-attachments/files/16122652/asst.log)
[gui.log](https://github.com/user-attachments/files/16122653/gui.log)

**Comment by Dean-Mon10** [comment]
+1，简中官服。出错时运行模式为肉鸽刷源石锭。
[log.zip](https://github.com/user-attachments/files/16123817/log.zip)

**Comment by Constrat** [comment]
cc @ABA2396 I also can't let MAA run (no errors on my side, it just stops working). I released a Nightly yesterday night (no nightly for an entire week)

**Comment by crazysmile-PhD** [comment]
我也遇到了相同的問題，當進行選擇角色時，系統會不斷地退出角色選擇界面並重新進入選擇流程。

**Comment by laetita0319** [comment]
繁中服
跟以上報錯相同問題+1

![valuecannotbenull](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141286706/ed95b0ba-9bc7-46de-ba55-30557b9a55d7)

**Comment by Constrat** [comment]
Unless you want to add an additional asst.log. We already have enough feedback and are working on it. Please, no more +1, same or anything like that.
