### ISSUE TITLE
MAA 遇到了問題 Value cannot be null. (Parameter 'value') 解決方法 出現未知錯誤

### ISSUE THREAD

**Issue by crazysmile-PhD** [MaaAssistantArknights/MaaAssistantArknights#9560]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at MaaWpfGui.Main.AsstProxy.ProcSubTaskStart(JObject details)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
這是她突然跳出來的視窗，把他按掉後就閃退了。

### Version

UI Version: v5.4.1-alpha.1.d022.ga340d515a
Core Version: v5.4.1-alpha.1.d022.ga340d515a

### 日志文件

[asst.log](https://github.com/user-attachments/files/16123798/asst.log)
[gui.log](https://github.com/user-attachments/files/16123799/gui.log)
2024/7/8下午2點50分左右

### 还有别的吗？

BlueStacks 5

[Android 11 64-bit]5.21.218.1001P64

**Comment by ABA2396** [comment]
没看到你说的这段，但是
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/78dde9eb-da91-46cb-ae9f-1d2c48b4ca21)
有文件被其他进程占用了，是不是同时开了多个实例或者有其他操作

**Comment by Constrat** [comment]
Duplicate of #9559

**Comment by crazysmile-PhD** [comment]
> 引用回復

使用單獨的裝置進行格式化，而不涉及其他應用程式或操作，我有建立記憶體映像檔案，通常不會有什麼影響。如果確實因此造成問題，我會表示歉意。
