### ISSUE TITLE
日服客户端 无法进入 傀影、水月主题肉鸽

### ISSUE THREAD

**Issue by Manicsteiner** [MaaAssistantArknights/MaaAssistantArknights#9563]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

见视频，自动肉鸽选择傀影、水月主题，则运行时MAA直接闪退，萨米主题正常
暂时猜测是 #9172 引入了逻辑死循环或没有正确隐藏一些参数传递环节

### Version

最新内测版
Resource Version: ロドスの道のり・中堅
UI Version: v5.4.1-alpha.1.d022.ga340d515a
Core Version: v5.4.1-alpha.1.d022.ga340d515a

### 日志文件

[asst.log](https://github.com/user-attachments/files/16126733/asst.log)
[gui.log](https://github.com/user-attachments/files/16126735/gui.log)

### 截图

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/557bccb1-f81b-464f-a2e9-403622a62b56

https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/63437036/cf7414ad-f129-45e7-9363-4c2a12840dff

**Comment by Rbqwow** [comment]
大概 修了 ...?

**Comment by Manicsteiner** [comment]
fixed by #9573
