### ISSUE TITLE
mumu模拟器连接失败的问题

### ISSUE THREAD

**Issue by skylink12** [MaaAssistantArknights/MaaAssistantArknights#957]
![}4OG6LFI( `24Y}}16P{X9P](https://user-images.githubusercontent.com/107050880/174994790-9625c94d-7504-43fd-8685-ef67558a38d1.png)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8956296/asst.log)

**Comment by zzyyyl** [comment]
好像是因为 adb 路径带空格的原因（

**Comment by skylink12** [comment]
> 好像是 adb 路径带空格的原因（

就是说模拟器的安装路径不能出现空格，是这个意思吗？

**Comment by zzyyyl** [comment]
你在这边调用`adb_server.exe devices`看看有没有输出？

**Comment by zzyyyl** [comment]
不行的话可以重新下一个 adb 试试

**Comment by zzyyyl** [comment]
居然真的是空格的问题，我刚刚把 adb 移到带空格的路径里也能运行，真是奇怪

**Comment by zzyyyl** [comment]
可能是不同路径权限不同引起的问题吧（大概

**Comment by skylink12** [comment]
> 空格应该是能运行的，你刚刚换路径的时候是不是换了个盘（？ 可能是不同路径权限不同引起的问题吧（大概
![2YJ9H3YCMZR@EMD3%PYEGBC](https://user-images.githubusercontent.com/107050880/175049626-18392613-aa2a-4c06-93bf-c0f81fcdad5c.png)
重新安装在同一个盘的不同文件夹

**Comment by zzyyyl** [comment]
有没有一种可能，你刚刚少了个文件

**Comment by zzyyyl** [comment]
那个 `AdbWinApi.dll` 你刚才给的图里没有（

**Comment by skylink12** [comment]
> 那个 `AdbWinApi.dll` 你刚才给的图里没有（

阿这，那我就不清楚了
