### ISSUE TITLE
萨米肉鸽出现弹窗报错，值为null

### ISSUE THREAD

**Issue by x-Armin** [MaaAssistantArknights/MaaAssistantArknights#9572]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

肉鸽出现弹窗报错，值为null

### Version

Resource Version: 空想花庭·复刻

UI Version: v5.4.1-alpha.1.d022.ga340d515a
Core Version: v5.4.1-alpha.1.d022.ga340d515a

### 日志文件

[asst.log](https://github.com/user-attachments/files/16130965/asst.log)
[gui.log](https://github.com/user-attachments/files/16130969/gui.log)

[2024-07-08 22:53:00] 左右吧，前面也出现过一次

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/36064285/a322b69b-f87d-49b7-ae43-afbff3aaed57)

### 还有别的吗？

MUMU模拟器12

12700+4070tis，开启了GPU加速推理

**Comment by Constrat** [comment]
Duplicate of #9559
