### ISSUE TITLE
繁中服萨米肉鸽刷投资时每次战斗结束在选择密文版时一直在循环打开和关闭选择页面不能选中

### ISSUE THREAD

**Issue by ZQYQK** [MaaAssistantArknights/MaaAssistantArknights#9574]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

萨米肉鸽刷投资时每次战斗结束会在选择密文板选项是循环很长时间

### Version

资源版本：火山旅梦  ui版本：v5.40  核心版本：v5.40

### Log files

[日志.zip](https://github.com/user-attachments/files/16133159/default.zip)
2024年7月9日02:18

**Comment by momomochi987** [comment]
@ZQYQK 

這個問題前面已經有人回報過囉

可以幫我試試下面這個方法，
看還會不會發生同問題或是出現其他問題嗎？

https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9472#issuecomment-2212828949

**Comment by ZQYQK** [comment]
解决了，感谢

**Comment by ZQYQK** [comment]
通过替换之前问题下的解决方法里下载的tasks.json文件可以解决这个问题，十分感谢
