### ISSUE TITLE
自动肉鸽总是卡在事件选择界面

### ISSUE THREAD

**Issue by AziMeow** [MaaAssistantArknights/MaaAssistantArknights#9576]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动肉鸽总是卡在选择界面，就是那个下面两个选项需要抗干扰指数的界面，且日志文件异常大，asst.log有两个多g

### Version

Resource Version: 空想花庭·复刻
UI Version: v5.3.1
Core Version: v5.3.1

### 日志文件

![屏幕截图 2024-07-09 091518](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/165452914/ada64bf6-74de-4b65-8ffe-2c0c5c4f6599)

[gui.log](https://github.com/user-attachments/files/16135817/gui.log)
另一日志文件异常大，压缩了也发不出来
时间是2024.7.8 20点到21点以及7.9的0点到1点

### 截图

![2024-07-09_08-47-36-386_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/165452914/fdc0bef6-a930-43c5-bf7b-751412e6f81f)

![2024-07-08_20-06-31-952_raw](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/165452914/a3133254-0ea8-432a-82c2-0ae861b6ffc5)
每次都是卡在这个界面

### 还有别的吗？

mumu模拟器 配置是4070tisuper+i5+13600KF

**Comment by Saratoga-Official** [comment]
没日志也解决不了，把原来的日志删掉让maa重新记录再上传
