### ISSUE TITLE
部分 MAA 无法更新 `熔炉“还魂”记` 游戏资源

### ISSUE THREAD

**Issue by Hhone2** [MaaAssistantArknights/MaaAssistantArknights#9580]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

前天开始没法更新资源版本，不论是内测版或者稳定版和公测版，一直停留在空想花庭，通过官网重新下载打开同样是卡在空想花庭版本，但同一台电脑另一个MAA却能正常更新到新活动

### Version

Resource Version: 空想花庭·复刻
UI Version: v5.4.1-alpha.1.d022.ga340d515a
Core Version: v5.4.1-alpha.1.d022.ga340d515a

### 日志文件

[asst.log](https://github.com/user-attachments/files/16140916/asst.log)
[gui.log](https://github.com/user-attachments/files/16140918/gui.log)
大概出现在前天

### 截图

![46b4ce2e6a2cdf511657a2bb78295b1f](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/175104712/ce4f8f6c-bee6-4b09-8eb4-b2ffe87edf1f)
![1d9790509fa624dadf639aab2e265c70](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/175104712/7aa94b4b-854f-471f-8559-9700a6591944)
这是出错的MAA截图
![be095b65f731de2c8e8e8fd0e752b935](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/175104712/9f5c3a69-ba84-4146-962f-e9a2c16f7909)
这是能正常更新的MAA的截图

### 还有别的吗？

mumu模拟器 已经安装了两个运行库

**Comment by Dean-Mon10** [comment]
挂梯子可解，具体原因不晓得

**Comment by Hhone2** [comment]
> 挂梯子可解，具体原因不晓得

还真是，就很奇怪，另一个MAA啥事没有

**Comment by Rbqwow** [comment]
gui.json 里面找到 `"VersionUpdate.ResourceApi"` 这一行然后删了再试
注意json的逗号

**Comment by zzyyyl** [comment]
@Rbqwow 是不是可以把源列出来给用户选（？

**Comment by ABA2396** [comment]
> @Rbqwow 是不是可以把源列出来给用户选（？

换一次镜像就要重新下一遍资源，两边的etag是不一样的

**Comment by Rbqwow** [comment]
> @Rbqwow 是不是可以把源列出来给用户选（？

学姐说会有一窝蜂效应 除非做真正的负载均衡

**Comment by zzyyyl** [comment]
> > @Rbqwow 是不是可以把源列出来给用户选（？
> 
> 换一次镜像就要重新下一遍资源，两边的etag是不一样的

那可以给个提示，告诉用户你换了要重下，总比下不了要好（？

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/fc9c29c6-ba22-4dc3-9161-5f6b48f23f37)
怎么感觉是s3的问题，照理来说传过去的都是%23

**Comment by Rbqwow** [comment]
> > > @Rbqwow 是不是可以把源列出来给用户选（？
> > 
> > 
> > 换一次镜像就要重新下一遍资源，两边的etag是不一样的
> 
> 那可以给个提示，告诉用户你换了要重下，总比下不了要好（？

检查更新旁边做个重置更新按钮(? 点一下重新抽

**Comment by ABA2396** [comment]
![0f860277905ae43f47c05ddaea659042](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/2cee2f04-3dda-40e7-8b0b-7030be1b87b5)
![396ba28773ec330d01998c1caa9fde63](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/b49628ea-1735-41da-a9df-bcbbff2f6f46)
不对啊，我这里试了下都是可以正确转换#的

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/f45895dc-8f42-4ced-b9d2-68abc90e38ae)
以及这个代理是怎么设的，看你的截图里也没设代理啊

**Comment by Hhone2** [comment]
> ![图像](https://private-user-images.githubusercontent.com/99072975/346919682-f45895dc-8f42-4ced-b9d2-68abc90e38ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MjI2NDMsIm5iZiI6MTcyMDUyMjM0MywicGF0aCI6Ii85OTA3Mjk3NS8zNDY5MTk2ODItZjQ1ODk1ZGMtOGY0Mi00Y2VkLWI5ZDItNjhhYmM5MGUzOGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEwNTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZjg5N2VjYTA0Yjc3OTI5Zjc1MDFhMmUxMjQyNDI0Zjg0YTFhOWU4NjIzMWQ5OGM1MmJjZGVhYmVkN2RlNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xYaS3xkEBl_IYNZQDF8YkdXSfktzXtgi-pwp_JJy0OA)以及这个代理是怎么设的，看你的截图里也没设代理啊

这个时间好像是我挂着梯子上了下Steam的工坊，但我当时好像是没成功更新我记得

**Comment by AllanJinYosoro** [comment]
感觉挂梯子也不行，试了港澳台、新加坡、日本、美国节点依旧无法成功更新

**Comment by Golden-Pigeon** [comment]
话说这个URL里面的#f#是做什么用的呀？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/20119392/790bc3e3-cb3e-4b17-925b-57a8676a5ef2)

我在浏览器里面试了下，把#f#去掉就可以获取到资源了，否则就会返回

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/20119392/b143ec5e-8e62-41ef-adb1-b30f40ff15af)


\#后的部分就直接被截掉了

**Comment by Golden-Pigeon** [comment]
应该还是井号转换的问题，#换成%23就能拿到资源了，不知道为什么日志里面显示的是井号

**Comment by ABA2396** [comment]
带#和不带#是两个不同的关，这就得问yj为啥这么取名了。照理来说传出去的链接都是%23，不知道是不是服务器处理的问题

**Comment by ChingCdesu** [comment]
URL规范中，"#"之后的部分表示锚点，会定位到某个相同id的元素上，是作用于浏览器上的，但会截断后面的path部分，实际上只有"#"之前的部分称为path

**Comment by chazzqwq** [comment]
看了评论区，挂了个梯子就更新上了

**Comment by Weedy233** [comment]
挂梯子确实有用，记得要选全局模式。之前开的规则模式一直更新不了，还以为是机场又抽风了，换了全局模式就好了

**Comment by SherkeyXD** [comment]
fixed
