### ISSUE TITLE
5.4.1内测版自动肉鸽闪退

### ISSUE THREAD

**Issue by aWeriG** [MaaAssistantArknights/MaaAssistantArknights#9585]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

1、夜神模拟器7.0.5.9版本下,使用MAA5.4.1内测版时,在启动水月自动肉鸽功能后会自动闪退,可以多次复现.
2、此前曾手动更改过肉鸽协议,替换为MAA5.4.0官方协议后此情况仍能复现.考虑并非更改肉鸽协议导致.
3、VCRedist x64及.NET 8环境多次重复部署,此情况仍能复现,考虑并非环境导致.
4、MAA5.4.0稳定版可正常运行,无此情况出现.

### Version

UI Version: v5.4.1-alpha.1.d022.ga340d515a
Core Version: v5.4.1-alpha.1.d022.ga340d515a

### 日志文件

[asst.log](https://github.com/user-attachments/files/16142896/asst.log)
[gui.log](https://github.com/user-attachments/files/16142897/gui.log)

### 截图

莫得← ←

### 还有别的吗？

也莫得← ←

**Comment by Manicsteiner** [comment]
duplicate of #9563 
是程序问题，在修了.jpg，先用 v5.4.0
