### ISSUE TITLE
MAA自动肉鸽 刷原石锭无法正常进行

### ISSUE THREAD

**Issue by a-Giong** [MaaAssistantArknights/MaaAssistantArknights#9589]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我的maa版本是稳定版v5.4.0，选用萨米肉鸽，策略是“刷原石锭，到达第二层后直接退出”。但当maa进入第一层商店后，maa会购买东西，然后在没有存入原石锭的情况下退出商店。问题出现的时间点可以参考最后的截图。（Ps:我同学也出现了相应问题，我是从他那得知并尝试的）

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.0
Core Version: v5.4.0

### 日志文件

[asst.log](https://github.com/user-attachments/files/16145096/asst.log)
[gui.log](https://github.com/user-attachments/files/16145100/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/142110385/bedbca1f-1db0-4650-9f84-ef143b4e6a79)

**Comment by zzyyyl** [comment]
#9590 fixed
