### ISSUE TITLE
未知原因出现游戏资源更新失败？

### ISSUE THREAD

**Issue by A-ui-OL** [MaaAssistantArknights/MaaAssistantArknights#9593]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

卡在编制游戏资源索引 然后就出更新失败请稍后再试了

### Version

UI Version: v5.4.0 Core Version: v5.4.0 Resource Version: 空想花庭·复刻

### 日志文件

[asst.log](https://github.com/user-attachments/files/16147547/asst.log)
[gui.log](https://github.com/user-attachments/files/16147548/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/175150713/1f73bb25-6979-4758-a446-66c60cfd9c15)

**Comment by Rbqwow** [comment]
duplicate of #9580

[临时解决方案](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9580#issuecomment-2217165120)
