### ISSUE TITLE
出现未知错误

### ISSUE THREAD

**Issue by berberfly** [MaaAssistantArknights/MaaAssistantArknights#9594]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA代理打傀影水月肉鸽时点击完开始MAA就闪退，打萨米肉鸽正常，刷理智也可以，刚才挂了一会萨米肉鸽就出现检测到未知错误，但我不把这个错误提示叉掉代理还能继续，最新的两个运行库也安装了
下午自动抄作业的时候有几把战斗开始后不下干员的情况，这个问题重启程序之后就好了

### Version

Core Version: v5.4.1-alpha.1.d022.ga340d515a
UI Version: v5.4.1-alpha.1.d022.ga340d515a
Resource Version: 熔炉“还魂”记

### 日志文件

2024.7.10 01:03开始打银灰模组开始出现问题一直到三点这个范围
[asst.bak.log](https://github.com/user-attachments/files/16149528/asst.bak.log)
[gui.log](https://github.com/user-attachments/files/16149529/gui.log)

### 截图

![屏幕截图 2024-07-10 025820](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/175154875/e50e6ff9-386a-487b-b3b7-45aa4aa999b7)
![Uploading 屏幕截图 2024-07-10 025820.png…]()
[屏幕截图 2024-07-10 025820.zip](https://github.com/user-attachments/files/16149494/2024-07-10.025820.zip)

### 还有别的吗？

mumu模拟器
处理器	13th Gen Intel(R) Core(TM) i9-13900HX   2.20 GHz
机带 RAM	16.0 GB (13.7 GB 可用)
设备 ID	34744596-9E04-422E-8CF1-5C319826D406
产品 ID	00342-31417-08681-AAOEM
系统类型	64 位操作系统, 基于 x64 的处理器
版本	Windows 11 家庭中文版
版本号	23H2
安装日期	‎2023/‎7/‎8
操作系统版本	22631.3737
体验	Windows Feature Experience Pack 1000.22700.1009.0

**Comment by Rbqwow** [comment]
duplicate of #9559
