### ISSUE TITLE
启动MAA无任何反应无法打开

### ISSUE THREAD

**Issue by Wsal4** [MaaAssistantArknights/MaaAssistantArknights#9599]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

启动MAA时无任何反应，通过任务管理器可以查看到进程启动一瞬然后就没了。已尝试重新下载、重启电脑、管理员身份运行、替换可能存在问题的文件结果均是一样的，文件夹内没有debug的文件夹/文件生成。

### Version

MAA-v5.4.0-win-x64

### 日志文件

文件夹内没有debug的文件夹/文件生成。

### 截图

![微信图片_20240710094139](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141443309/1c6a331e-939c-4156-a544-bdddb78223ea)
![微信图片_20240710094142](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/141443309/92fd458d-4fb1-4127-b332-fe0430b372bb)

### 还有别的吗？

系统为Windows10专业版版本号是22H2

**Comment by ABA2396** [comment]
运行库装了没

**Comment by ABA2396** [comment]
https://maa.plus/docs/zh-cn/manual/faq.html#运行库问题

**Comment by Wsal4** [comment]
此前是可以运行的，也尝试过安装旧版本的使用，也是无法打开的，刚刚检查过运行库没有查看出问题，这边尝试重新安装一下相关运行库试试。
________________________________
发件人: uye ***@***.***>
发送时间: 2024年7月10日 2:35
收件人: MaaAssistantArknights/MaaAssistantArknights ***@***.***>
抄送: Wsal4 ***@***.***>; Author ***@***.***>
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] 启动MAA无任何反应无法打开 (Issue #9599)


https://maa.plus/docs/zh-cn/manual/faq.html#运行库问题<https://maa.plus/docs/zh-cn/manual/faq.html#%E8%BF%90%E8%A1%8C%E5%BA%93%E9%97%AE%E9%A2%98>

―

**Comment by Rbqwow** [comment]
8.0.1不能用 得8.0.3以上 更新一下就好
