### ISSUE TITLE
在未勾选自动公招的情况下执行自动公招

### ISSUE THREAD

**Issue by guojunyu196** [MaaAssistantArknights/MaaAssistantArknights#960]
![uTools_1655911912650](https://user-images.githubusercontent.com/76220347/175074415-6a2fc83c-61ef-4a14-bcdc-f6f765e60f01.png)
![uTools_1655911946456](https://user-images.githubusercontent.com/76220347/175074423-54c9ef40-c908-43e6-9f59-44ff0d8f2351.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8959286/asst.log)

**Comment by MistEO** [comment]
应该和 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/943 是同一个问题，点得太快了 MAA 没反应过来
