### ISSUE TITLE
基建换班-自定义基建排班制作器 链接异常

### ISSUE THREAD

**Issue by Mou-Froski** [MaaAssistantArknights/MaaAssistantArknights#9601]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

见截图

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.0
Core Version: v5.4.0

### 日志文件

（这个要传日志吗x

### 截图

![屏幕截图 2024-07-10 102811](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159701770/d233b9be-602d-4833-92d7-5f87b9ee0895)
![屏幕截图 2024-07-10 102839](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/159701770/65532ad6-22be-45f0-9b98-4356e1167147)

**Comment by Mou-Froski** [comment]
看了下
maa给的链接是https://maa.plus/docs/%E5%8D%8F%E8%AE%AE%E6%96%87%E6%A1%A3/%E5%9F%BA%E5%BB%BA%E6%8E%92%E7%8F%AD%E5%8D%8F%E8%AE%AE.html
但是基建排班协议的网址是https://maa.plus/docs/zh-cn/protocol/base-scheduling-schema.html
不知道是不是这个原因（痴呆

**Comment by ABA2396** [comment]
哦，链接改过了）
不对啊，官网怎么没发版就已经更新了？文档不应该随版本发布的吗，怎么推上去了
@Rbqwow @SherkeyXD

**Comment by SherkeyXD** [comment]
> 哦，链接改过了）
> 不对啊，官网怎么没发版就已经更新了？文档不应该随版本发布的吗，怎么推上去了
> @Rbqwow @SherkeyXD 

前阵子重构完文档手动部署了一次

**Comment by ABA2396** [comment]
这玩意pr里已经改成了$"{MaaDocs}/{Language}/protocol/base-scheduling-schema.html";，新版本应该就没问题了

**Comment by Rbqwow** [comment]
这...这个不是一图流的制作器...嘛...?

**Comment by ABA2396** [comment]
之前一图流不是换域名吗，为了兼容给换成官网链接了

**Comment by Constrat** [comment]
Latest nightly does not present this issue. Link fixed
