### ISSUE TITLE
更新后内测版本仍会复现#9559的报错 v5.4.1-alpha.1.d042.g1b8911f55

### ISSUE THREAD

**Issue by Aurora903** [MaaAssistantArknights/MaaAssistantArknights#9602]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

国服。使用刷取源石锭功能时，进入不期而遇节点后，在点击选项时会出现报错，放置不管后不影响maa正常运行，我连续刷了几轮都有这一现象，和#9559一致，但我使用的是更新后的版本。
尝试：1 改变难度。n0 n3 n15都会出现这一现象；
           2 重装。将maa彻底删除并重装后，仍会出现这一报错，版本为内测版最新版本；
           3 修改分辨率。2560*1440与1920*1080分辨率下均出现此问题。
多次重复后，发现次报错只会在不期而遇节点中，点击选择项时出现，如果第一层遇见三场战斗则不会出现报错。特别是“”雨！”这一节点，选择第一分支获取抗干扰指数时，会弹出很多报错窗口（应该是4个），而其他不期而遇时间中选择时只会弹出一个报错窗口。此外，如果遇见多个不期而遇事件，每次进入并作出选择时，都会弹出报错，而非一次探索只会出现一次。固定使用后勤分队，稳扎稳打职业组，维什戴尔开局，未测试其他选项。弹窗内容如下：

MAA遇到了问题
 Value cannot be null. (Parameter 'value')
解决方案
 出现未知错误
详细信息
 System.ArgumentNullException: Value cannot be null. (Parameter 'value')
    at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
    at MaaWpfGui.Main.AsstProxy.ProcSubTaskStart(JObject details)
    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, 
 Object args, Int32 numArgs)
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.1-alpha.1.d042.g1b8911f55
Core Version: v5.4.1-alpha.1.d042.g1b8911f55

### 日志文件

[asst.log](https://github.com/user-attachments/files/16154857/asst.log)
[gui.log](https://github.com/user-attachments/files/16154859/gui.log)

### 截图

<img width="449" alt="捕获" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/78003714/51e02ad8-9548-4416-a99f-3937f135c2c0">

**Comment by Manicsteiner** [comment]
修复在 #9573 里，还没进主线，可能还要再改改

**Comment by status102** [comment]
尚未修复

**Comment by status102** [comment]
Duplicate of #9559
