### ISSUE TITLE
MAA闪退

### ISSUE THREAD

**Issue by a1623382** [MaaAssistantArknights/MaaAssistantArknights#9603]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

正常开启maa，在等待30s后自动闪退；尝试过跳过等待，手动点击开启，依旧闪退

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.1-alpha.1.d042.g1b8911f55
Core Version: v5.4.1-alpha.1.d042.g1b8911f55

### 日志文件

[asst.log](https://github.com/user-attachments/files/16155209/asst.log)
[gui.log](https://github.com/user-attachments/files/16155210/gui.log)

### 还有别的吗？

mumu模拟器，最新版
windows11

**Comment by TianyaoPRC** [comment]
+1

**Comment by nickname1959** [comment]
我也是这样

**Comment by status102** [comment]
- #9559 估计是因为这个
