### ISSUE TITLE
OurPlay模拟器可以支持吗

### ISSUE THREAD

**Issue by fatcat1y** [MaaAssistantArknights/MaaAssistantArknights#9608]
### 说说你遇到的问题？

自动识别识别不出，我在文件夹里面找得到adb.exe文件，请问下这个模拟器可以支持MAA吗

**Comment by Constrat** [comment]
Isn't OurPlay just a link for GmsCore? To allow Google Services to work on a device that should not support it? Like root etc.?

**Comment by Rbqwow** [comment]
理论上所有可以通过adb调试的模拟器都被支持 实际自测

**Comment by horror-proton** [comment]
我也只知道 OurPlay 是个 GMS 模拟器 + 游戏加速器, 好像还有 PC 用的加速器, 没找到有啥 Android 模拟器啊, 有参考链接吗

**Comment by SherkeyXD** [comment]
尝试在启动模拟器后用 `adb devices` 查看本地是否有 adb server
