### ISSUE TITLE
强化API接口的交互性

### ISSUE THREAD

**Issue by Minepig** [MaaAssistantArknights/MaaAssistantArknights#961]
目前的API接口功能是”下达任务→执行任务“，即使使用回调也无法根据当前情况临时下达指令
希望加入类似”上报→回复“的API，这样可以更好的控制任务，类似于给MAA添加一个后端
（例如：MAA将识别到的基建人员信息传给程序，程序处理后把换班细节回传给MAA，由MAA执行）

**Comment by MistEO** [comment]
> 具体的执行逻辑不打算交给调用方来做，由 core 一并完成

如果需要强调某些换班细节等，目前的设计是会新增参数字段，由 core 进行额外的处理来实现
