### ISSUE TITLE
MAA未知错误，并且在未点击错误框时依旧能正常使用，点击后（例如关闭错误框）立即结束软件

### ISSUE THREAD

**Issue by AnkorTn** [MaaAssistantArknights/MaaAssistantArknights#9611]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
Value cannot be null. (Parameter 'value')
解决方案
出现未知错误
详细信息
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at MaaWpfGui.Main.AsstProxy.ProcSubTaskStart(JObject details)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.1-alpha.1.d049.g4473a45e6
Core Version: v5.4.1-alpha.1.d049.g4473a45e6

### 日志文件

[gui.log](https://github.com/user-attachments/files/16162832/gui.log)
[asst - 副本.txt](https://github.com/user-attachments/files/16162836/asst.-.txt)

### 还有别的吗？

Windows11操作系统，MUMU模拟器12

**Comment by AnkorTn** [comment]
好像在我刚更新之后就没这个问题了，刚刚及时更新的。。。不好意思

**Comment by AnkorTn** [comment]
在用MAA挂机肉鸽时出现的wenti问题，但是只要没有关闭这个错误界面就能够继续挂机，并且侧边状态栏依旧在更新。

该问题稳定复现，基本在6~8分钟后就会出现

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57738756/6fc8a189-77c1-4896-9f85-cb6bcd57c9b4)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57738756/c372472d-ca1b-40eb-84c9-ef53452eb18a)



![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57738756/d1152e97-47f8-44ff-bacf-a49e568432c1)

**Comment by Rbqwow** [comment]
duplicate of #9559
