### ISSUE TITLE
繁中服maa薩米出現招募卷時會卡住

### ISSUE THREAD

**Issue by Yuanlas** [MaaAssistantArknights/MaaAssistantArknights#9614]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

繁中 薩米出現一張招募卷可以選多個職業或多個密文板時會卡住

### Version

Resource Version: 火山旅夢
UI Version: v5.4.0
Core Version: v5.4.0

### 日志文件

[新增資料夾.zip](https://github.com/user-attachments/files/16164490/default.zip)

[2024-07-10 23:13:35.436] <1><> 開始戰鬥: 利刃所指
[2024-07-10 23:16:15.908] <1><> 戰鬥完成
[2024-07-10 23:23:17.349] <1><> 事件: 在地公共移动站N6号

### 截图

![螢幕擷取畫面 2024-07-10 232202](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/175227912/7c247c97-5ebb-4352-87b8-31a62a72fd44)

### 还有别的吗？

mumu12

**Comment by zzyyyl** [comment]
这是密文版不是招募券（

#9584 fixed，可以试试内测版 v5.4.1-alpha.1.d049.g4473a45e6
