### ISSUE TITLE
希望增加最小化到托盘的功能

### ISSUE THREAD

**Issue by LmeSzinc** [MaaAssistantArknights/MaaAssistantArknights#962]
不少模拟器都可以最小化到托盘，脚本也能的话就很棒，再折叠一下托盘区，正常工作的时候不会看到有游戏和脚本，体验++

**需要增加的功能**

- 点击按钮，maa最小化到系统托盘区
- 点击托盘区图标，重新显示maa

**Comment by MistEO** [comment]
这功能很早之前就想做了，但是 WPF 实在不会弄 orz, 等个有缘的大佬帮忙写

Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/102, https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/341
