### ISSUE TITLE
设置里关于我们下的常见问题链接404

### ISSUE THREAD

**Issue by wanqian-windrunner** [MaaAssistantArknights/MaaAssistantArknights#9626]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

设置->关于我们->常见问题   链接404了

### Version

Resource Version: 空想花庭·复刻
UI Version: v5.4.0
Core Version: v5.4.0

### 日志文件

无

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/119412909/6e28fdf3-b2be-4fec-bd75-1d9720e6df61)

**Comment by Rbqwow** [comment]
已知问题 (土下座

内测是对的
