### ISSUE TITLE
自动萨米肉鸽持续出现关卡识别错误

### ISSUE THREAD

**Issue by ChianHawk** [MaaAssistantArknights/MaaAssistantArknights#9627]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

mumu模拟器，更新后进行萨米肉鸽自动时无法识别关卡，重新安装maa后仍然有相同问题

### Version

Resource Version: 空想花庭·复刻
UI Version: v5.4.0
Core Version: v5.4.0

### 日志文件

[asst.log](https://github.com/user-attachments/files/16174736/asst.log)
[gui.log](https://github.com/user-attachments/files/16174742/gui.log)

**Comment by Constrat** [comment]
@ABA2396 Is this something similar to the shift in position of the Investment mode?

**Comment by ChianHawk** [comment]
在其它重新尝试后发现maa在模拟器处于出现关卡名称前的黑屏画面时便进行了“无法识别关卡”的报错。因此，该bug可能是由于较低性能设备运行模拟器时加载关卡、出现关卡名称前的黑屏时间过长，导致maa错误地将黑屏画面作为存在关卡名的画面进行识别。或许可以通过改变关卡识别的逻辑来规避该问题的发生？

**Comment by zzyyyl** [comment]
方便提供你的设备信息么，系统/内存/cpu 等

**Comment by zzyyyl** [comment]
看到你使用的是 MuMu 12，你或许可以在 `连接设置` 中 `启用 MuMu 截图增强模式` 试试
