### ISSUE TITLE
肉鸽中，技能“自动触发”的干员会停在技能点击面直到关卡结束

### ISSUE THREAD

**Issue by Rana7wu** [MaaAssistantArknights/MaaAssistantArknights#9628]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

肉鸽中，会自动点击角色技能，技能“自动触发”的干员会因此停在技能点击面直到关卡结束，因为此页面会大幅度拖延战斗时间，影响挂机效率。

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.0
Core Version: v5.4.0

### 日志文件

[asst.log](https://github.com/user-attachments/files/16177704/asst.log)
[gui.log](https://github.com/user-attachments/files/16177705/gui.log)

### 截图

![01e90d7f-7005-494f-81a1-203ff10d35ae](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/162982360/90ed456e-1245-45a8-8314-55505fe5f568)

### 还有别的吗？

模拟器：mumu12 
windows11

**Comment by zzyyyl** [comment]
日志不全；
有可能是 BattlePauseCancel 导致的，就当 26420530960eecc448aadb47806230d504502859 fixed 了
