### ISSUE TITLE
肉鸽选到夜半后会一直尝试把夜半部署在地面位并且不部署其后的干员

### ISSUE THREAD

**Issue by SinoButcher** [MaaAssistantArknights/MaaAssistantArknights#963]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8962215/asst.log)
使用的是夜神模拟器7.0.0.8，刷肉鸽固定以山、安塞尔、梓兰开局；选人拿到夜半后，在关卡中会依次部署山、安塞尔、梓兰，然后在部署夜半时尝试将其拖拽至地面位进行部署，继而部署失败弹出子弹时间，过几秒又重复尝试在地面位部署夜半，如此循环，而且不会尝试部署除夜半以外的其他干员。不知道其他远程先锋是否也有这个部署问题

**Comment by SinoButcher** [comment]
![Screenshot (38)(1)](https://user-images.githubusercontent.com/108033702/175179304-804a2503-af3e-4a94-aa02-13ec8cc91356.png)
补图，由于是后面再遇到的同样情况，图中的操作并不在刚才上传的日志里

**Comment by SinoButcher** [comment]
> 肉鸽现在是按职业区分高台还是地面的，并没有识别人。这个问题改起来还有点麻烦，可能短期解决方案是不选高台先锋（

也就是说高台先锋、地面辅助、高台特种都没法上场了，怪不得我刚刚还遇到了把阿往地上丢的情况，但可能是因为优先级不高丢了一次就停手了（指转头去丢夜半），那么可以通过修改肉鸽配置文件来不招募特定干员吗，比如把resource文件夹里的roguelike_recruit.json中，对应干员的信息直接删掉？

**Comment by MistEO** [comment]
> > 肉鸽现在是按职业区分高台还是地面的，并没有识别人。这个问题改起来还有点麻烦，可能短期解决方案是不选高台先锋（
> 
> 也就是说高台先锋、地面辅助、高台特种都没法上场了，怪不得我刚刚还遇到了把阿往地上丢的情况，但可能是因为优先级不高丢了一次就停手了（指转头去丢夜半），那么可以通过修改肉鸽配置文件来不招募特定干员吗，比如把resource文件夹里的roguelike_recruit.json中，对应干员的信息直接删掉？

是的

**Comment by SinoButcher** [comment]
> > > 肉鸽现在是按职业区分高台还是地面的，并没有识别人。这个问题改起来还有点麻烦，可能短期解决方案是不选高台先锋（
> > 
> > 
> > 也就是说高台先锋、地面辅助、高台特种都没法上场了，怪不得我刚刚还遇到了把阿往地上丢的情况，但可能是因为优先级不高丢了一次就停手了（指转头去丢夜半），那么可以通过修改肉鸽配置文件来不招募特定干员吗，比如把resource文件夹里的roguelike_recruit.json中，对应干员的信息直接删掉？
> 
> 是的

懂了，多谢！
