### ISSUE TITLE
最新主线版本无法运行萨米肉鸽

### ISSUE THREAD

**Issue by Manicsteiner** [MaaAssistantArknights/MaaAssistantArknights#9631]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

又是卡死闪退（）
报错位置如图

### Version

UI Version: DEBUG VERSION
Latest Debug build at commit [970e452](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/970e45209a0255a6aba7474ccaab391d31d9d4bd)
UI Version: v5.4.1-alpha.1.d068.g970e45209 也是了

### 日志文件

[asst.log](https://github.com/user-attachments/files/16186485/asst.log)
[gui.log](https://github.com/user-attachments/files/16186487/gui.log)

### 截图

![图片](https://github.com/user-attachments/assets/006b571d-8ae8-4d89-9520-a86fd22b49da)

**Comment by status102** [comment]
@Alan-Charred

**Comment by Alan-Charred** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/9633
