### ISSUE TITLE
未成年人定时脚本

### ISSUE THREAD

**Issue by BxcdMouKun** [MaaAssistantArknights/MaaAssistantArknights#9638]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

学生党没时间。拜托了这对未成年人来说很重要（虽然我剩两年

### 有什么好的想法？

加入每晚8点开始自动执行脚本

**Comment by yc080713** [comment]
这个需求当前定时功能可以实现啊？

**Comment by sunsheep1018** [comment]
從設定-定時執行那邊設定
