### ISSUE TITLE
建议 cache 删了

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantArknights#9639]
### 说说你遇到的问题？

现在 cache 在 AsstTypes.h 和 TaskData.cpp 中默认值定义不同
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/8c3643b6914cf35187d433aaf5228dbf76ff7541/src/MaaCore/Common/AsstTypes.h#L424
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/8c3643b6914cf35187d433aaf5228dbf76ff7541/src/MaaCore/Config/TaskData.cpp#L705

cache 不影响识别结果，对识别速度的影响也很小，而且曾经有很多 bug 是因为 cache 为 true 引起的

**Comment by Lancarus** [comment]
不如删了（）

**Comment by zzyyyl** [comment]
cc @MistEO

**Comment by MistEO** [comment]
不如删了（

**Comment by zzyyyl** [comment]
嗯？还没删呢

**Comment by SherkeyXD** [comment]
建议删了（
cache能带来多少性能提升呢

**Comment by zzyyyl** [comment]
cache 引起的问题又多一例！ #9557
