### ISSUE TITLE
错误的游戏崩溃判断

### ISSUE THREAD

**Issue by cglcv** [MaaAssistantArknights/MaaAssistantArknights#964]
WSA，刷理智过程中刷一半报游戏崩溃（实际上游戏正常运行），然后任务异常结束了~然后电脑就休眠了~
可能是WSA截了个空图干扰了maa的判断
日志（发生时间在22日23：55-23日0：15间，共发生两次）：
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8963314/asst.log)

截图（发生时处于关卡中，截图时刚好进结算）：

![2022-06-23](https://user-images.githubusercontent.com/35825310/175198331-518278af-b358-4fcd-a69b-fc2b282f1594.png)

**Comment by MistEO** [comment]
确实是截到了错误的图的问题，但不是一帧，从 `2022-06-22 23:57:25.135` 开始，截图的大小全部是 `10608` （一张图片不可能这么小的），后面连续几分钟一直都是这样。

没啥好办法，如果确实是截图问题，可能得等微软修复了
