### ISSUE TITLE
MAA自动战斗过程中无法正确使用令濯缨皮肤的召唤物

### ISSUE THREAD

**Issue by HYY1116** [MaaAssistantArknights/MaaAssistantArknights#9646]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在自动战斗作业中使用令三技能（其他技能未测试）且令皮肤为濯缨时，无法正常部署令的召唤物，在使用原皮后可正常部署

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.1-alpha.1.d070.gcef579741
Core Version: v5.4.1-alpha.1.d070.gcef579741

### 日志文件

7.13 11:45后
[asst.log](https://github.com/user-attachments/files/16200803/asst.log)
[gui.log](https://github.com/user-attachments/files/16200804/gui.log)

### 截图

![MuMu12-20240713-115145](https://github.com/user-attachments/assets/c5265c26-f893-44f9-945e-b5da871612d6)
![QQ截图20240713115138](https://github.com/user-attachments/assets/c6d080de-0906-4158-bf5a-c653633c3e6c)
原本在费用足够后会放置大龙，但是在使用皮肤后就不进行下一步了

**Comment by SherkeyXD** [comment]
盲猜缓存问题
删了 cache/avatars 文件夹试试
