### ISSUE TITLE
模拟器连接失败

### ISSUE THREAD

**Issue by wuyue1ye** [MaaAssistantArknights/MaaAssistantArknights#965]
夜神模拟器，一直连接失败
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8963370/asst.log)
![_U5`4`KB@MBNHQ)}U_Q(KF3](https://user-images.githubusercontent.com/108042821/175200178-3c284c05-9971-4a30-ab5f-e15e38e6b410.png)
![0CG3LRCA(`O}T4((P3KYFKK](https://user-images.githubusercontent.com/108042821/175200197-573ba74a-57cd-4ded-bbd1-4d4175663d7f.png)

**Comment by MistEO** [comment]
模拟器 adb 端口 offline 了，这种情况如果重启也没用，一般我就推荐换模拟器了。

~~但毕竟人家夜神帮我们免费推广了，所以这个问题我报给他们开发了，等他们看看吧~~

**Comment by wuyue1ye** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8964654/asst.log)
换了mumu模拟器还是一样的问题

**Comment by MistEO** [comment]
这就很奇怪了，再换个蓝叠国际版的试试

**Comment by zzyyyl** [comment]
> 模拟器 adb 端口 offline 了，这种情况如果重启也没用，一般我就推荐换模拟器了。
> 
> ~但毕竟人家夜神帮我们免费推广了，所以这个问题我报给他们开发了，等他们看看吧~

`adb server version (41) doesn't match this client (36)`
看日志不是端口 offline，是adb版本和夜神模拟器版本对不上 
（但是用的不是夜神自己带的 adb 么，版本匹配不上怎么想都是他们的问题）

**Comment by MistEO** [comment]
> > 模拟器 adb 端口 offline 了，这种情况如果重启也没用，一般我就推荐换模拟器了。
> > 
> > ~但毕竟人家夜神帮我们免费推广了，所以这个问题我报给他们开发了，等他们看看吧~
> 
> `adb server version (41) doesn't match this client (36)`
> 看日志不是端口 offline，是adb版本和夜神模拟器版本对不上 
> （但是用的不是夜神自己带的 adb 么，版本匹配不上怎么想都是他们的问题）

offline 的时候就会报这个（

**Comment by wuyue1ye** [comment]
> 这就很奇怪了，再换个蓝叠国际版的试试

是不是我的系统问题还是啥，蓝叠也是一样的问题
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8972732/asst.log)

**Comment by zzyyyl** [comment]
你去下一个 1.0.36 的 adb，然后把路径填到 `设置-连接设置-adb路径` 再试试

**Comment by MistEO** [comment]
> 你去下一个 1.0.36 的 adb，然后把路径填到 `设置-连接设置-adb路径` 再试试

多半也没用（

**Comment by ChildeRolando** [comment]
应该是多开换端口了吧
cmd看一下新的模拟器实例占用的端口，然后填到 设置-连接设置-链接地址
同款问题，我是这样解决的
