### ISSUE TITLE
模拟器分辨率不支持

### ISSUE THREAD

**Issue by 098Loyyer** [MaaAssistantArknights/MaaAssistantArknights#9665]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

连接失败
模拟器分辨率不支持，请设置为720p或更高，且为16:9比例
我使用的是1080p*1920p但仍然失败

### Version

Resource Version: 引航者試煉
UI Version: v5.4.1
Core Version: v5.4.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16228624/asst.log)
[gui.log](https://github.com/user-attachments/files/16228627/gui.log)

### 截图

![95c042c6b0a943df9bac029455079d5](https://github.com/user-attachments/assets/52e27a67-d90b-4768-8f9a-43134bd5195c)

### 还有别的吗？

雷电模拟器
WIN11
AMD Ryzen7 7800XD + 4070
台服

**Comment by 098Loyyer** [comment]
今天问题突然就没有了，难道这就是重启的伟大吗
![f5bd2a1d0e6ca56fdc09a4962b8c6d3](https://github.com/user-attachments/assets/03c0914b-7dae-421c-bed9-f485f4a24da2)
[asst.log](https://github.com/user-attachments/files/16231834/asst.log)
[gui.log](https://github.com/user-attachments/files/16231830/gui.log)

**Comment by Rbqwow** [comment]
1080p dpi就写320吧 小了有可能影响识别

**Comment by 098Loyyer** [comment]
好的，谢谢大大
