### ISSUE TITLE
添加周日自动剿灭选项

### ISSUE THREAD

**Issue by Sakuya209** [MaaAssistantArknights/MaaAssistantArknights#9666]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

周一想起上周挂MAA长草了没打剿灭

### 有什么好的想法？

在理智清理选项中添加自动剿灭选项，检测到当前日期为星期日时优先刷剿灭

**Comment by status102** [comment]
使用备选关卡并首选剿灭
