### ISSUE TITLE
任务被重复执行

### ISSUE THREAD

**Issue by guojunyu196** [MaaAssistantArknights/MaaAssistantArknights#967]
![QQ截图20220623220815](https://user-images.githubusercontent.com/76220347/175319820-6280a27d-ca45-46e0-8508-8d12b8f16902.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8968032/asst.log)

**Comment by guojunyu196** [comment]
隔了得有十秒左右

**Comment by zzyyyl** [comment]
点 `停止` 之后，点 `LinkStart！` 之前，有没有 `任务已全部完成` 的提示
没有的话是已知 bug，在修了

**Comment by guojunyu196** [comment]
确实没有提示，那就是已知bug了

**Comment by MistEO** [comment]
简单修了一下，不过这个问题的根源其实是运行期不能修改刷理智的设置，那支持一下好了
