### ISSUE TITLE
能否使maa可以调用tcc运行模式的显卡进行推理加速

### ISSUE THREAD

**Issue by aknyzsd** [MaaAssistantArknights/MaaAssistantArknights#9670]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

机器上组了多卡，为了防止win出现调度问题，推理卡走的tcc工作模式，maa选项里只显示了我在WDDM模式下工作的亮机卡

**Comment by dantmnf** [comment]
目前的 GPU 推理是通过 DX12 调用，所以只支持 WDDM 模式。

暂时不会考虑增加依赖某一厂商硬件的功能。
