### ISSUE TITLE
自动肉鸽报错

### ISSUE THREAD

**Issue by yukiryo** [MaaAssistantArknights/MaaAssistantArknights#9671]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

自动肉鸽报错，关闭窗口自动退出maa，不关闭窗口正常运行

### Version

v5.4.1-alpha.1.d042.g1b8911f55

### 日志文件

[asst.log](https://github.com/user-attachments/files/16230162/asst.log)
[gui.log](https://github.com/user-attachments/files/16230163/gui.log)

### 截图

![image](https://github.com/user-attachments/assets/18e41489-f254-44a1-976c-2d9251acb65f)

**Comment by Rbqwow** [comment]
Duplicate of #9559
