### ISSUE TITLE
薩米肉鴿在戰鬥結束後，選密文板時候會卡住(繁中服)

### ISSUE THREAD

**Issue by shearer0118** [MaaAssistantArknights/MaaAssistantArknights#9673]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

薩米肉鴿在戰鬥結束後，選密文板時候會點開，然後在(兩個密文板選擇的地方)和(點開密文板的地方)鬼打牆

### Version

Resource Version: 引航者試煉，UI Version: v5.4.1，Core Version: v5.4.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16233914/asst.log)
[gui.log](https://github.com/user-attachments/files/16233915/gui.log)

### 截图

![Untitled](https://github.com/user-attachments/assets/51757eaf-bf66-4908-bc72-b1d4db8d4472)

**Comment by zzyyyl** [comment]
使用内测版试试
