### ISSUE TITLE
更新后热键设置失效

### ISSUE THREAD

**Issue by xjr353171020** [MaaAssistantArknights/MaaAssistantArknights#9676]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新至5.4.1之前，我使用Ctrl+Alt+M来触发Link start/stop。由于更换了电脑，全新安装5.4.1之后，热键设置消失变为not set，并且无法被设置为Ctrl+Alt+M。因为在安全模式下能录入快捷键，但是正常重启后又被清除，所以不排除是其他软件占用了此快捷键导致无法录入，但我并未找到使用此快捷键组合的软件。

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.1
Core Version: v5.4.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16237983/asst.log)
[gui.log](https://github.com/user-attachments/files/16237987/gui.log)
出现问题至上传文件前，没有进行过任务。有过一次失败连接。

**Comment by Constrat** [comment]
Just tried with `v5.4.2-alpha.1.d104.g2428a4610` and it's working.
