### ISSUE TITLE
繁中服保全作業卡在導能配件甄選

### ISSUE THREAD

**Issue by laetita0319** [MaaAssistantArknights/MaaAssistantArknights#9678]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

試了保全派駐的作業
包含預設資料夾內和prts.plus上下載的
全都卡在導能配件甄選的畫面上
如果手動點擊
後面就不會自動運行了

### Version

UI Version: v5.4.2-alpha.1.d104.g2428a4610
Core Version: v5.4.2-alpha.1.d104.g2428a4610

### 日志文件

[asst.zip](https://github.com/user-attachments/files/16241654/asst.zip)
[gui.log](https://github.com/user-attachments/files/16241639/gui.log)
時間在7/16 6:36和6:57左右

### 截图

![Screenshot_2024 07 16_08 29 17 341](https://github.com/user-attachments/assets/462663c5-ea25-4213-85e2-7acb2d58ca5d)

### 还有别的吗？

模擬器Bluestacks 5

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/ecf2ca90-72fc-43db-9d87-c9666ffa2a92)
这玩意识别出来的结果太奇怪了，要不试试看换下分辨率。先试试720p的识别结果

**Comment by laetita0319** [comment]
> 这玩意识别出来的结果太奇怪了，要不试试看换下分辨率。先试试720p的识别结果

我調整了1280*720的分辨率
還是卡在相同的地方
[asst.zip](https://github.com/user-attachments/files/16244715/asst.zip)
[gui.log](https://github.com/user-attachments/files/16244698/gui.log)
15:20左右

**Comment by Manicsteiner** [comment]
增强组件的分支选项没写进 CharsNameOcrReplace，等更新修正或自己手动添加
昨天刚聊过 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1b8911f55023c9a7e5de5c88f5d3d2663d0f40af#r144251477

**Comment by Constrat** [comment]
The changes I made were only for EN.
So currently what's fixes is just:
- JP
- EN
- KR only removed duplicates
- TW @momomochi987 if you want to have a look at it. Resource Updater unfortunately does not support this. I could implement it, but more files need to be downloaded and the amount of logic will be a lot.

**Comment by momomochi987** [comment]
@laetita0319 

我在復現同樣問題的時候，發現應該是 "請進行戰地援護無人機...." 這串字的辨識問題。

我把 "SSSDropRecruitmentFlag" 的 roi 調整一下，問題就解決了 (?

<details>

<summary>把 \resource\global\txwy\resource 的 tasks.json 做這些更改</summary>

1. `"SSSDropRecruitmentFlag"` 加上
```
        "roi": [
            387,
            78,
            501,
            92
        ]
```

2. `"CharsNameOcrReplace"` 的 `"ocrReplace"` 裡加上

```
	[
	    "靶向修復製劑",
	    "靶向修復製剂"
	],
	[
	    "受體激動製劑",
	    "受体激动製剂"
	]
```

以上補上的內容記得加上逗號 (要符合 json 格式)

</details>


改完 tasks.json 重開 MAA，再進行童操作，看看還會不會有同樣問題發生

**Comment by momomochi987** [comment]
> I could implement it, but more files need to be downloaded and the amount of logic will be a lot.

If you have free time and it’s not too much trouble, it would be great to do the changes like EN and JP.

But I think, it might be simpler if I manually add the relevant content when the SSS map changed (?

**Comment by Constrat** [comment]
The map already changed today.
Technically the strings are already available on the gamedata, but to implement in the resource updater. It would be such a big work for something that gets updated once every 6 months. Not worth it

**Comment by momomochi987** [comment]
> The map already changed today.
> 
> Technically the strings are already available on the gamedata, but to implement in the resource updater. It would be such a big work for something that gets updated once every 6 months. Not worth it

Got it.
After the mentioned solution is confirmed to be fine, 
I'll create Pull Request to add the content for SSS #3.

Thanks for telling me 😀

**Comment by laetita0319** [comment]
> 我在復現同樣問題的時候，發現應該是 "請進行戰地援護無人機...." 這串字的辨識問題。
> 我把 "SSSDropRecruitmentFlag" 的 roi 調整一下，問題就解決了 (?
> 把 \resource\global\txwy\resource 的 tasks.json 做這些更改
> 改完 tasks.json 重開 MAA，再進行同樣操作，看看還會不會有同樣問題發生
感謝，問題解決，不會卡在第四層了
但會卡在循環次數上
所以我參照更改方式
在同一個文件的"SSSBuffChoose"裡"ocrReplace"加上

	[
	    "溢能回收轉化器",
	    "溢能回收转化器"
	],
	[
	    "戰地援護無人機",
	    "战地援护无人机"
	]

後就能解決無法循環次數的問題

再次感謝！
