### ISSUE TITLE
更新完成后不显示 CHANGELOG 弹窗

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaAssistantArknights#968]
似乎 cs 这边存在某个 crash, 但被异常捕获兜住了, 我这里是必现的

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/1a6dc9be67a0b6bba42bdab58b990d5c3aba01a2/src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs#L99

似乎是崩在这里了

**Comment by MistEO** [comment]
![image](https://user-images.githubusercontent.com/18511905/175811258-9f7a7bcc-ee62-48d4-a739-86c9f6ee602b.png)

**Comment by MistEO** [comment]
不知道为啥在我这必现崩溃，不过既然你们都没遇到这个问题那就关了吧先

**Comment by MistEO** [comment]
目前看来是非个例问题，reopened

**Comment by zzyyyl** [comment]
我这不是必现，之前有过，但是最近两次更新都没弹窗

**Comment by MistEO** [comment]
问题再次出现，reopened

**Comment by zzyyyl** [comment]
要不把 Exception 存个 log 或者弹个窗？
