### ISSUE TITLE
开启GPU加速推理后MAA闪退

### ISSUE THREAD

**Issue by PandaYuuHa** [MaaAssistantArknights/MaaAssistantArknights#9684]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

将GPU加速推理选项，由不使用切换至系统默认GPU或直接选择显卡(型号是RTX3060 laptop)后，在点击一键长草的开始按钮后就会闪退

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.1
Core Version: v5.4.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16248335/asst.log)
[gui.log](https://github.com/user-attachments/files/16248337/gui.log)

### 还有别的吗？

操作系统是Win10，显卡型号RTX 3060 laptop

**Comment by Rbqwow** [comment]
看看事件查看器里面有没有相关事件 炸的好突然

**Comment by Rbqwow** [comment]
试试重装一下显卡驱动...?

**Comment by Rbqwow** [comment]
`C:\WINDOWS\System32\DriverStore\FileRepository\nvltig.inf_amd64_6ff1713c80bf5424\nvwgf2umx.dll`

直观看上去就是显卡驱动问题 DDU卸的应该也没残留

或者再找找别的有没有什么 超频 全局OSD游戏内覆盖 之类的

**Comment by ABA2396** [comment]
这时候应该cc @dantmnf

**Comment by dantmnf** [comment]
`C:\Users\*\AppData\Local\CrashDumps` 内有没有 MAA.exe 的 dmp 文件？

**Comment by dantmnf** [comment]
nvidia 驱动开了 omit frame pointer 导致 dump 里没有什么有价值的信息，https://driver-symbols.nvidia.com/ 上也没有对应版本的驱动文件，这边只能建议换个驱动版本还有 sfc 之类的了（
