### ISSUE TITLE
MAA-v5.4.1-xin-x64无法打开，无限报错

### ISSUE THREAD

**Issue by kabishoubushifeizhai** [MaaAssistantArknights/MaaAssistantArknights#9688]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

启动EXE文件后提示MAA遇到了问题，需按照常见问题-闪退进行操作 已重新下载过5.4.1安装包进行解压并重启电脑 运行库文件也已重装，但仍然无法启动，继续报错

### Version

5.4.1-xin-x64

### 日志文件

[gui.log](https://github.com/user-attachments/files/16252291/gui.log)

### 截图

![QQ图片20240716231213](https://github.com/user-attachments/assets/380a922e-8d58-42c6-aea3-53afcf106201)

**Comment by Rbqwow** [comment]
参见文档常见问题置顶
