### ISSUE TITLE
新下载的MAA提示游戏资源更新失败

### ISSUE THREAD

**Issue by aierxiya** [MaaAssistantArknights/MaaAssistantArknights#9693]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在今天更新资源时一直卡在5/120

### Version

V5.4.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16259073/asst.log)
[gui.log](https://github.com/user-attachments/files/16259074/gui.log)

### 截图

![微信截图_20240717115644](https://github.com/user-attachments/assets/5af1de45-cde0-4fa6-ab3d-663facfc7628)

**Comment by LinXu-LinXu** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9580
挂梯子，记得选全局

**Comment by ChingCdesu** [comment]
目前s3机房处于过热状态，如果你遇到下载一半没速度了，请耐心等待一会或者稍后再试

**Comment by EiveLL** [comment]
最新版本（v5.5.0）也出现这个问题，我是从GitHub上下载的
