### ISSUE TITLE
刷理智显示任务出错

### ISSUE THREAD

**Issue by JasonWhite999** [MaaAssistantArknights/MaaAssistantArknights#9696]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

<img width="564" alt="4bec84e476cf4c23a204b02f586bb8a" src="https://github.com/user-attachments/assets/a02e64ee-b83c-4f42-943e-61ad36b787b7">
不知为何搓土块时无法开始任务

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.1
Core Version: v5.4.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16267026/asst.log)
[gui.log](https://github.com/user-attachments/files/16267027/gui.log)

**Comment by Rbqwow** [comment]
关一下后台保活

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/8438824d-805c-4847-8aad-9657a21011e2)
![image](https://github.com/user-attachments/assets/db6231a5-db87-452c-b814-b11c5a6ccb91)
