### ISSUE TITLE
萨卡兹肉鸽战斗掉落结算识别问题

### ISSUE THREAD

**Issue by DCxDESIGN** [MaaAssistantArknights/MaaAssistantArknights#9703]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨卡兹肉鸽的刷钱功能已经可用了，非常感谢开发组

目前发现战斗掉落结算时似乎并不能识别到所有的源石锭掉落，见图
![SShot-20240718-055654-PotPlayerMini64_1](https://github.com/user-attachments/assets/cf665f48-48a0-4345-93c4-51c532c99876)

 只抓了第二个源石锭掉落，第一个被无视了

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.2-alpha.1.d139.gf2f158ba6
Core Version: v5.4.2-alpha.1.d139.gf2f158ba6

### 日志文件

[gui.log](https://github.com/user-attachments/files/16275198/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/16275205/asst.bak.log)

07-18 05:43 左右

### 截图

![SShot-20240718-061407-PotPlayerMini64](https://github.com/user-attachments/assets/a01d9ef3-cfcd-46b8-8463-0d00b2765cf9)

**Comment by Lancarus** [comment]
为了省时间，跑路按钮出来第一时间跑路
