### ISSUE TITLE
萨卡兹肉鸽 反复开始、放弃探索，且中途无动作

### ISSUE THREAD

**Issue by zht04** [MaaAssistantArknights/MaaAssistantArknights#9704]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我一开始设置了“刷开局”模式，但是刷开局的时候就一直开始探索，选人，然后放弃探索，问了一下说刷开局还没适配，我就切换回刷源石锭模式，然后发现还是会有这个问题：开始探索，选人，放弃探索。这样反复循环。可见下图
![ec88a5673f36ee97184ad429d3bdcadd](https://github.com/user-attachments/assets/7a601d7a-97bf-4aab-b03f-2ed724b6c57c)

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.2-alpha.1.d129.g6691f7c52
Core Version: v5.4.2-alpha.1.d129.g6691f7c52

### 日志文件

时间点：9.48前后；
[asst.log](https://github.com/user-attachments/files/16276641/asst.log)
[gui.log](https://github.com/user-attachments/files/16276643/gui.log)

**Comment by ABA2396** [comment]
asst.log被刷掉了，发asst.bak.log

**Comment by zht04** [comment]
[asst.bak.log](https://github.com/user-attachments/files/16276900/asst.bak.log)
这是asst.bak.log

**Comment by zht04** [comment]
> asst.log被刷掉了，发asst.bak.log

[asst.bak.log](https://github.com/user-attachments/files/16276920/asst.bak.log)

**Comment by ABA2396** [comment]
是卡在选关卡的那个地方吗，截个图看看卡哪里了

**Comment by zht04** [comment]
> 是卡在选关卡的那个地方吗，截个图看看卡哪里了

就是刚进一层，然后往右划一下到一层中间。
我没有当时的截图了，下面是一个示意图，几乎是一样的：
<img width="640" alt="4daa230a524e50489bf0f398ba3549ed_720" src="https://github.com/user-attachments/assets/69d3e85e-c09f-468e-9e00-507327f3fad3">

**Comment by ABA2396** [comment]
这玩意好像是方舟的老毛病了，这个滑动不是maa滑的，重启下游戏或者模拟器应该就行

**Comment by zht04** [comment]
> 这玩意好像是方舟的老毛病了，这个滑动不是maa滑的，重启下游戏或者模拟器应该就行

哦哦好的，我有空试一下，谢谢啦
