### ISSUE TITLE
萨卡兹肉鸽戴冠式操作异常

### ISSUE THREAD

**Issue by yunxiiyun** [MaaAssistantArknights/MaaAssistantArknights#9705]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

进入戴冠式出来之后会卡住，然后过一会会直接退出这次探索

### Version

UI Version: v5.4.2-alpha.1.d129.g6691f7c52

### 日志文件

[asst.log](https://github.com/user-attachments/files/16276735/asst.log)
[gui.log](https://github.com/user-attachments/files/16276736/gui.log)

### 截图

![image](https://github.com/user-attachments/assets/65766853-521f-409f-bc5a-0fbe0a491ebd)

**Comment by xiaoweiXX** [comment]
我也是，能听见MAA一直在点，但是一直没反应，手动点一下不期而遇就能继续

**Comment by bkmz888** [comment]
卡死+1 会停在第二层操作完戴冠式以后

**Comment by ABA2396** [comment]
现在只有第一层刷钱

**Comment by DavidWang19** [comment]
已修复
