### ISSUE TITLE
新肉鸽当思维混乱或者阻滞时，会卡住不动

### ISSUE THREAD

**Issue by lingxinquan** [MaaAssistantArknights/MaaAssistantArknights#9706]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

新肉鸽当思维混乱或者阻滞时，会卡住不动

### Version

UI Version: v5.4.2-alpha.1.d139.gf2f158ba6
Core Version: v5.4.2-alpha.1.d139.gf2f158ba6
Resource Version: 熔炉“还魂”记

### 日志文件

n

**Comment by xiaoweiXX** [comment]
我刚才也在这里卡住了，丢个日志

**Comment by xiaoweiXX** [comment]
[asst.txt](https://github.com/user-attachments/files/16277105/asst.txt)

**Comment by xiaoweiXX** [comment]
> [asst.txt](https://github.com/user-attachments/files/16277105/asst.txt)

不知道为啥.log格式不让上传，改了下后缀

**Comment by soundofautumn** [comment]
刷钱的话把下面这个关了就不会有这个问题了
高级设置：投资模式启用购物、招募

**Comment by xiaoweiXX** [comment]
> 刷钱的话把下面这个关了就不会有这个问题了 高级设置：投资模式启用购物、招募

刷等级的就暂时无解了？

**Comment by soundofautumn** [comment]
等等吧，丢思绪的还在做

**Comment by Daydreamer114** [comment]
> > 刷钱的话把下面这个关了就不会有这个问题了 高级设置：投资模式启用购物、招募
> 
> 刷等级的就暂时无解了？

还没做刷等级

**Comment by Daydreamer114** [comment]
fixed #9711
