### ISSUE TITLE
游戏资源多次更新失败

### ISSUE THREAD

**Issue by a1121611810** [MaaAssistantArknights/MaaAssistantArknights#9708]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

多次尝试关闭再打开，都会提示
游戏资源正在更新。
游戏资源更新失败，请稍后尝试。
![image](https://github.com/user-attachments/assets/3d50b587-9505-4b56-b9c6-2baa0b003005)

### Version

Resource Version: 熔炉”还魂”记
Ul Version: v5.4.2-alpha.1.d104.g2428a4610
Core Version:v5.4.2-alpha.1.d104.g2428a4610

### 日志文件

[asst.log](https://github.com/user-attachments/files/16276839/asst.log)
[gui.log](https://github.com/user-attachments/files/16276840/gui.log)

### 还有别的吗？

使用模拟器：MUMU

操作系统相关：
版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎2/‎20
操作系统版本	22631.3880
体验	Windows Feature Experience Pack 1000.22700.1020.0

**Comment by ABA2396** [comment]
这个稍后是真的稍后）
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9693#issuecomment-2232841136

**Comment by kaliannafunk** [comment]
![933d429d389d65ac068970b8d1ee6ebf](https://github.com/user-attachments/assets/ccf93812-8481-4bb4-b9de-980ecff40af3)
它真的能更新吗？

**Comment by kaliannafunk** [comment]
> ![933d429d389d65ac068970b8d1ee6ebf](https://private-user-images.githubusercontent.com/175906608/349763946-ccf93812-8481-4bb4-b9de-980ecff40af3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzExMTYsIm5iZiI6MTcyMTI3MDgxNiwicGF0aCI6Ii8xNzU5MDY2MDgvMzQ5NzYzOTQ2LWNjZjkzODEyLTg0ODEtNGJiNC1iOWRlLTk4MGVjZmY0MGFmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwMjQ2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2Q1Y2E2Njk5OGVmYTg4ZTA3NTcxNzYzOTM1YzY3N2QwMGZhNTJjMzNkMTkzNDQyNmM3Njk1NjkwYzJhZmNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1f-pVpjup3CBR_0mAXbd95Inv4tbCd_lboYvaPCt0kM)它真的能更新吗？

更新了一个多小时还在更，然后失败，如果是bug，那有点难绷

**Comment by ABA2396** [comment]
> 更新了一个多小时还在更，然后失败，如果是bug，那有点难绷

这个问题解决很容易，加钱加服务器加宽带就行了，问题就是没钱

**Comment by ABA2396** [comment]
和代理没关系，现在是连接数打满了，同时有很多人更新就直接返回了
