### ISSUE TITLE
萨卡兹肉鸽，命运所指节点内戴冠式事件，事件结束后无后续响应，不会进入后续节点

### ISSUE THREAD

**Issue by wocazhanshen** [MaaAssistantArknights/MaaAssistantArknights#9709]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨卡兹肉鸽，命运所指节点，戴冠式事件，事件结束后无后续响应，不会进入后续节点，而是超时退出当前探索
尝试过重启MAA无效
模拟器为MUMU12，开启了MAA的MUMU急速触控
时间在7月18上午10点左右
在萨卡兹肉鸽第二层“锻铁根须”中，第一个节点必定是这个戴冠式
每次都会卡在这里

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.2-alpha.1.d139.gf2f158ba6
Core Version: v5.4.2-alpha.1.d139.gf2f158ba6

### 日志文件

[asst.zip](https://github.com/user-attachments/files/16276903/asst.zip)
[gui.log](https://github.com/user-attachments/files/16276904/gui.log)

### 截图

![MuMu12-20240718-102247](https://github.com/user-attachments/assets/211b2c96-562d-40d3-b111-217f0d2ef9c4)

**Comment by ABA2396** [comment]
现在只能刷锭，模式选第二个

**Comment by wocazhanshen** [comment]
> 现在只能刷锭，模式选第二个

这样的吗，谢谢

**Comment by ABA2396** [comment]
刷锭能刷的话就关了）其他的还在写
