### ISSUE TITLE
更新选项中，更新版本中的内测版选项消失

### ISSUE THREAD

**Issue by xiaoweiXX** [MaaAssistantArknights/MaaAssistantArknights#9714]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

设置→软件更新→更新版本中，原本有稳定版、公测版和内测版三个选项，现在内测版选项消失，只剩下稳定版和公测版两个选项。

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.2-alpha.1.d139.gf2f158ba6
Core Version: v5.4.2-alpha.1.d139.gf2f158ba6

### 日志文件

[asst.log](https://github.com/user-attachments/files/16278661/asst.log)
[gui.log](https://github.com/user-attachments/files/16278663/gui.log)

### 截图

![屏幕截图 2024-07-18 141808](https://github.com/user-attachments/assets/18290df5-21c3-47b7-ae54-46c7b0dcdd2b)

**Comment by status102** [comment]
预期行为

**Comment by xiaoweiXX** [comment]
> 预期行为

那我要是想更新内测版咋更新啊

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/27e85f5e-eb2d-423f-8a20-7358095dd096)

**Comment by xiaoweiXX** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/349920434-27e85f5e-eb2d-423f-8a20-7358095dd096.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDAyODIsIm5iZiI6MTcyMTI5OTk4MiwicGF0aCI6Ii85OTA3Mjk3NS8zNDk5MjA0MzQtMjdlODVmNWUtZWIyZC00MjNmLThhMjAtNzM1ODA5NWRkMDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEwNTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiODM2MzQ5NGQxNWU0MDc1NjNlMGJiMDZmYTg5YTgzMDdmOGUyMjYwMTRlYzZiMmUzYjM5MWIxZDA3MzNjNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.084kHkN862i9fbkkRDSKK6fFPEG8zqONREmRzIW0CH0)

我看置顶里链接的那个议题写的是更新方法保密，我还是不太知道要怎么更新。需要我留个邮箱之类的联系方式私密告知吗？

**Comment by xiaoweiXX** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/349920434-27e85f5e-eb2d-423f-8a20-7358095dd096.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDE1MzcsIm5iZiI6MTcyMTMwMTIzNywicGF0aCI6Ii85OTA3Mjk3NS8zNDk5MjA0MzQtMjdlODVmNWUtZWIyZC00MjNmLThhMjAtNzM1ODA5NWRkMDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDExMTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxOTI2MGEwNzNkY2U2YzgzMmNjNTUxMjA5YjQyYjQwZmYyZWY3YTYwM2ExNDI0Nzc4NzFlM2ZhZGQ2MzIzYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YJbvH0JoZ9iK9x4ePy9Om6fmHYZDNpeCWsGciAHYeIk)

直接下载对应的OTA压缩包然后覆盖文件是否可行？我刚才试了一下，打开显示新版本了，就是不知道是否有什么后遗症之类的。

**Comment by ABA2396** [comment]
~~折叠框里的是base64加密的教程，随便找个解下就好了~~
我就说这玩意改的太隐秘了

**Comment by xiaoweiXX** [comment]
> ~折叠框里的是base64加密的教程，随便找个解下就好了~ 我就说这玩意改的太隐秘了

平常不太接触base64，所以看不太出来，上次用base64还是为了把Steam APP里面的验证器密钥找出来。不过还是感谢提醒了，我已经用覆盖文件的方式更新了。
