### ISSUE TITLE
傀影肉鸽无法投资（别的肉鸽未测）

### ISSUE THREAD

**Issue by qshcjn1** [MaaAssistantArknights/MaaAssistantArknights#9716]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

傀影肉鸽到了第一层最后的商店，进去之后大概等待几秒，没有任何操作直接前往了下一层。
MacOS系统（M2芯片），使用Mumu Pro模拟器。
![1E59922D-F5B0-4052-B61A-31D62079ED6D](https://github.com/user-attachments/assets/5177e623-de2b-4878-bd83-566e9d89fdf7)

### Version

v5.4.1(498)

### 日志文件

[asst.log](https://github.com/user-attachments/files/16279549/asst.log)

**Comment by status102** [comment]
缺少相关信息，如时间

**Comment by qshcjn1** [comment]
> 缺少相关信息，如发生时间

抱歉，如图大概15:40:46左右，测试了几次，这是最后一次

![ACF2F5D7-4D55-4A6A-AADB-5EF8C831C4CB](https://github.com/user-attachments/assets/7947a32e-ab6d-4cbb-a5af-c9932be35808)

**Comment by status102** [comment]
推测是位置变动，等待下版本更新即可
