### ISSUE TITLE
建议在刷理智部分增加与刷图规划的适配

### ISSUE THREAD

**Issue by ttxs25830** [MaaAssistantArknights/MaaAssistantArknights#972]
#### 建议允许用户设定更加详细的刷图规划而非仅能选取上次关卡和指定的几个关卡
如果可以，可以考虑与[企鹅物流](https://penguin-stats.cn/planner)联动
如果不行，可以让用户自行填写刷图规划表

**Comment by ABA2396** [comment]
这个之前有考虑过，但是现在的写法全关卡导航会比较麻烦，之后看看怎么弄

**Comment by MistEO** [comment]
规划表不是问题，不管是和企鹅联动还是用户自行填写，这都是简单的工作。

关卡导航才是大问题，大几百个关卡我们要一个个适配 + 测试的

**Comment by cglcv** [comment]
> 规划表不是问题，不管是和企鹅联动还是用户自行填写，这都是简单的工作。
> 
> 关卡导航才是大问题，全游戏几百个关卡我们要一个个适配 + 测试的

只是刷材料的话用不到相当多的图吧……可以只把刷图上报数量多的那些图的适配做出来，没人刷的、不必刷的（活动图1~4）、不掉材料的（火蓝之心、喧闹法则插曲）、固定编队、剧情关就不适配了
