### ISSUE TITLE
[feature] 移除Hash任务类型

### ISSUE THREAD

**Issue by soundofautumn** [MaaAssistantArknights/MaaAssistantArknights#9720]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

tasks.json里只剩一个Hash类型的任务了，该干掉了

**Comment by zzyyyl** [comment]
代码里就基建有两行

cc @MistEO
