### ISSUE TITLE
自动战斗提示 不支持的关卡

### ISSUE THREAD

**Issue by weiby3** [MaaAssistantArknights/MaaAssistantArknights#973]
![image](https://user-images.githubusercontent.com/30197106/175439240-0612d17d-09ae-4838-967b-bcf44e94cb03.png)
用的是下面的json，翻json文件看了最低要求4.0，maa已经是4.0了
![image](https://user-images.githubusercontent.com/30197106/175439357-7fd3e16c-f3ab-428b-9a5b-c135ecb72208.png)
[磨难10-2_德克萨斯+风笛+令+能天使.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8972280/10-2_.%2B.%2B.%2B.txt)

**Comment by MistEO** [comment]
Duplicate of #970
