### ISSUE TITLE
maa更新版本无法选择内测版

### ISSUE THREAD

**Issue by toggletoN** [MaaAssistantArknights/MaaAssistantArknights#9733]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

打开maa后在设置->软件更新处点击更新版本后只有公测版和稳定版两个选项，无法更新为最新的内测版

### Version

UI Version: v5.4.2-alpha.1.d151.gf507bae32
Core Version: v5.4.2-alpha.1.d151.gf507bae32
Resource Version: 熔炉“还魂”记

### 日志文件

[asst.log](https://github.com/user-attachments/files/16286094/asst.log)
[gui.log](https://github.com/user-attachments/files/16286095/gui.log)
大概在7.18号出现该问题

### 截图

![屏幕截图 2024-07-19 000952](https://github.com/user-attachments/assets/32e78d32-522c-4bae-9979-b685c21caae9)

**Comment by toggletoN** [comment]
![屏幕截图 2024-07-19 001242](https://github.com/user-attachments/assets/14ac13cd-2ef4-48d8-833b-8b74a4b1cb82)
截错图了，应该是这样

**Comment by Saratoga-Official** [comment]
不是bug，现在就是设计成不能更新内测
