### ISSUE TITLE
使用idm下载最新的内测版时出现异常

### ISSUE THREAD

**Issue by vandark-9527** [MaaAssistantArknights/MaaAssistantArknights#9734]
### 说说你遇到的问题？

![QQ图片20240719005848](https://github.com/user-attachments/assets/41b5cb47-849a-4fa9-bbfe-bb16486e74d3)
![QQ图片20240719005900](https://github.com/user-attachments/assets/9cf4e96d-26db-49da-aedc-ec97c0a95aa2)
尝试过多次重启电脑，网络在wifi和手机流量切换，以及是否开启vpn，均未解决问题
浏览器为chrome

**Comment by Rbqwow** [comment]
![image](https://github.com/user-attachments/assets/bccf65f5-1cce-4067-a452-485f1b79f4c1)

原因不明 换浏览器下
