### ISSUE TITLE
萨卡兹肉鸽关卡 ISW-NO 拆东补西无法正常通关

### ISSUE THREAD

**Issue by Yiserk** [MaaAssistantArknights/MaaAssistantArknights#9737]
### 说说你遇到的问题？

挂了七八次全是卡在这一关，干员下的位置挺奇怪的，ew总是被绳子捆死，之后就不部署干员了，只会在蓝点门口放重装，其他的干员再部署转好也不下。
![QQ20240719-084000](https://github.com/user-attachments/assets/8731dfb2-7601-4977-95a1-1f84c6c3a715)
![QQ20240719-084326](https://github.com/user-attachments/assets/0938f635-2517-4314-8656-04a0e5f368c1)

**Comment by Daydreamer114** [comment]
close as not planned

**Comment by Saratoga-Official** [comment]
maa现在还不支持刷等级，只能刷钱

**Comment by Yiserk** [comment]
> maa现在还不支持刷等级，只能刷钱
好嘟

**Comment by Yiserk** [comment]
> maa现在还不支持刷等级，只能刷钱

好嘟
