### ISSUE TITLE
经典老问题，卡在每日签到奖励领取界面

### ISSUE THREAD

**Issue by guojunyu196** [MaaAssistantArknights/MaaAssistantArknights#974]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8973590/asst.log)
![Screenshot_2022 06 24_14 01 42 930](https://user-images.githubusercontent.com/76220347/175473059-06dd3ae8-43cb-48c2-9dc4-efb8b5a5f8af.png)

**Comment by Shawnsdaddy** [comment]
+1
