### ISSUE TITLE
Mac端更新5.5.0-beta1后，仍然没有萨卡兹肉鸽选项

### ISSUE THREAD

**Issue by zhangweijian97** [MaaAssistantArknights/MaaAssistantArknights#9740]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题

### Version

关于MAA：v5.5.0-beta.1（500）

### 日志文件

N/A

### 截图

<img width="352" alt="image" src="https://github.com/user-attachments/assets/e2a94880-5316-4534-aa81-1d9db8c0527b">

**Comment by Daydreamer114** [comment]
mac还没写呢

**Comment by status102** [comment]
not bug
