### ISSUE TITLE
萨卡兹肉鸽卡在思绪负荷界面

### ISSUE THREAD

**Issue by blUwUe** [MaaAssistantArknights/MaaAssistantArknights#9743]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

战斗完成后卡在清理思绪界面不动近3小时，截图后尝试关闭思维负荷界面再重新打开便恢复正常。

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[debug.zip](https://github.com/user-attachments/files/16302163/debug.zip)

### 截图

![PixPin_2024-07-19_12-01-29](https://github.com/user-attachments/assets/eb02e898-be17-4d5f-b94c-56bc3c70238e)

### 还有别的吗？

uu模拟器，windows11

**Comment by DavidWang19** [comment]
@Daydreamer114
