### ISSUE TITLE
信用商店购买黑名单和优先级错误

### ISSUE THREAD

**Issue by hongleng** [MaaAssistantArknights/MaaAssistantArknights#9747]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![Screenshot 2024-07-19 134735](https://github.com/user-attachments/assets/07a981f1-8473-41b8-913c-1d3cc8215e29)
我看着MAA购买时买了加急和碳（在黑名单中），并且跳过了不在黑名单中的赤金

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16302652/asst.log)
[gui.log](https://github.com/user-attachments/files/16302654/gui.log)
问题出现的大致时间点：07/19 1:40PM前后

### 截图

我看了一下，debug文件夹里不包含信用商店的截图

### 还有别的吗？

Mumu 12模拟器，win 11。

**Comment by Rbqwow** [comment]
发1下领取信用及购物→高级设置的截图

**Comment by hongleng** [comment]
![Screenshot 2024-07-19 180309](https://github.com/user-attachments/assets/0facda86-0284-4534-b68c-ba2f434f9054)
![Screenshot 2024-07-19 180351](https://github.com/user-attachments/assets/c53967c5-3605-4b47-b0c2-af262b75e2ae)

**Comment by Rbqwow** [comment]
cc @ABA2396 

这里是不是所有区服都得写中文 还是不能有空格来着
我记得之前讨论过

---

所以你国服为啥要写英语啊( 改成中文就好了

**Comment by ABA2396** [comment]
> cc @ABA2396 
> 
> 这里是不是所有区服都得写中文 还是不能有空格来着

不是，这个是显示啥写啥

**Comment by hongleng** [comment]
OK。可能是因为我是英文环境，所以maa一开始是英文的，这里也是英文的。我修改设置后，这里没有自动修改
