### ISSUE TITLE
更新清空刷理智关卡选择

### ISSUE THREAD

**Issue by wnwdled** [MaaAssistantArknights/MaaAssistantArknights#9748]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

时不时更新就会把我设置好的关卡选择刷新掉，就今天更新我没注意浪费了100理智。

### 有什么好的想法？

每次更新不清空关卡选择或者清空关卡选择的更新时加个醒目的提示

**Comment by ABA2396** [comment]
信息太少了，完全不知道你说的是什么情况

关卡变回 当前/上次 现在基本就两种情况。一种是开了隐藏当日未开放的关卡，要是活动结束了会换回去。第二种的开了备选关卡，活动结束后还会保持原来的选择，但是开始任务的时候会跳过去找下一个开放的关卡，直到重启maa之后再变成 当前/上次
