### ISSUE TITLE
雷电模拟器无法正常工作

### ISSUE THREAD

**Issue by LeeSpo** [MaaAssistantArknights/MaaAssistantArknights#975]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8975705/asst.log)
已开启本地ADB调试

![image](https://user-images.githubusercontent.com/75921239/175523167-3ca3d1fe-f878-49e0-82e4-dcdad874b64f.png)
模拟器界面无动作
上一次打开（3h前）均能够正常，并且未更改模拟器、MAA软件配置

**Comment by MistEO** [comment]
模拟器服务炸了，重启试试
