### ISSUE TITLE
关于萨卡兹肉鸽刷源石锭

### ISSUE THREAD

**Issue by Whitestar1497** [MaaAssistantArknights/MaaAssistantArknights#9750]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

当前的萨卡兹肉鸽存钱流程可以优化

### 有什么好的想法？

蓝图测绘分队的存钱逻辑显然是错误的，最快流程应为选人后进入第一层，然后直接刷新一次节点，出了不期而遇直接进入，不期而遇中刷出事件“相遇”后直接选择藏品“希望时代的涂鸦”，后续遇到作战直接刷新成不期而遇，一路通过到商店存钱。
这是萨卡兹肉鸽目前存钱效率最高的方式，希望尽快优化蓝图队的存钱逻辑。

**Comment by Daydreamer114** [comment]
急
close as processing

**Comment by AstroNot233** [comment]
是的，感觉MAA效率太低了，一小时四十几块钱。我昨天受不了，边刷视频边手动打，一个小时刷了两百多。

**Comment by ABA2396** [comment]
> 是的，感觉MAA效率太低了，一小时四十几块钱。我昨天受不了，边刷视频边手动打，一个小时刷了两百多。

那你这也太慢了，我挂了一个下午就999了

**Comment by DavidWang19** [comment]
#9773
