### ISSUE TITLE
希望有能在完成任务后自动切换账号

### ISSUE THREAD

**Issue by zxmydmug** [MaaAssistantArknights/MaaAssistantArknights#9751]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

在切换账号时手动或者用定时启动无法准确的预估时间导致任务未完成而开启了下一个任务
结束后的脚本不会编辑（

### 有什么好的想法？

希望能有一个在完成当前1账号后启动2账号的功能，是自动而不是手动，我已清楚有自定义配置切换的功能，能不能将它集成到一条任务链上，连续然后再结束任务。能集成在一键长草界面的（完成后）的选项吗,谢谢了

### 其他内容

![Snipaste_2024-07-19_16-37-16](https://github.com/user-attachments/assets/077f46f4-7c0c-4f8e-b333-8557b73375de)
![Snipaste_2024-07-19_16-36-48](https://github.com/user-attachments/assets/f58ada1c-b0f2-46a7-844b-5f3c3c19c840)
![Snipaste_2024-07-19_16-34-28](https://github.com/user-attachments/assets/82d82f20-8aff-4d6d-aa6c-44d1b698f0bd)

**Comment by zxmydmug** [comment]
额，还有人吗

**Comment by ABA2396** [comment]
按我个人的想法是不去做多账号的，要有多个的话就开多个模拟器和maa一起跑或者岔开时间跑。

你真要用一个maa和模拟器实现也有办法，写两个配置然后写个结束后脚本来控制开哪个maa，maa是可以通过启动命令来切换开的哪个配置，只要在后面加上 `--config "配置名"` 就行
