### ISSUE TITLE
MAC版萨米肉鸽不存钱

### ISSUE THREAD

**Issue by Sanxun-in-a-month** [MaaAssistantArknights/MaaAssistantArknights#9753]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用Macbook，从MAA官网下载了macOS通用，下载版本v5.4.1，模拟器用的是mumu。
下载后打开MAA可以直接联动模拟器。设置在萨米肉鸽选择存钱策略，并勾选存钱选项，但是运行到第一层关底商店时直接跳过不存钱。

### Version

v5.4.1

### 日志文件

请教教我，我不知道怎么在macbook版本里找这个——

### 截图

<img width="891" alt="Screenshot 2024-07-19 at 7 42 46 PM" src="https://github.com/user-attachments/assets/d8737ea3-a8c4-45a3-861a-7bf4badb906d">
<img width="889" alt="Screenshot 2024-07-19 at 7 42 58 PM" src="https://github.com/user-attachments/assets/790a1c3e-f88f-478a-aa80-10426d0e6cca">

**Comment by Constrat** [comment]
iirc the invest layout was changed for the official CN about 2 weeks ago and the 5.4.1 does not support it anymore (especially on MacOS as the updates are more complicated as there's not many devs for mac)

**Comment by Sanxun-in-a-month** [comment]
> iirc the invest layout was changed for the official CN about 2 weeks ago and the 5.4.1 does not support it anymore (especially on MacOS as the updates are more complicated as there's not many devs for mac)

Oh no really? I was just trying to get the last few tokens for Sami... But it is realistic as there's only few on Mac. Thank you so much for explaining to me.

**Comment by ABA2396** [comment]
dev已经修改了，下个beta版本应该就能用上。等之后mac也支持热更应该就没这种问题了）

cc @hguandl
