### ISSUE TITLE
萨卡兹肉鸽卡在肉鸽主题选择界面

### ISSUE THREAD

**Issue by qshcjn1** [MaaAssistantArknights/MaaAssistantArknights#9754]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA设置萨卡兹肉鸽，进入时会卡在主题选择界面，隔一小会儿划拉一下然后继续卡在这里进不去。
MAA从18点12分11秒开始启动肉鸽任务，大概18点12分28秒左右进入主题选择页面然后一直卡住。

<img width="892" alt="截屏2024-07-19 18 09 13" src="https://github.com/user-attachments/assets/27ca42a8-a102-4060-b893-8a9b03154f79">

### Version

<img width="127" alt="截屏2024-07-19 18 15 35" src="https://github.com/user-attachments/assets/7708c099-a7ef-4021-80a3-3613da56d7e4">

### 日志文件

[asst.log](https://github.com/user-attachments/files/16310644/asst.log)

**Comment by Rbqwow** [comment]
已知问题 把萨卡兹肉鸽添加订阅到终端

**Comment by qshcjn1** [comment]
> 已知问题 导航之后再修 打哪个主题就先把哪个主题添加订阅到终端

收到，已解决，感谢大佬！
