### ISSUE TITLE
新肉鸽部署问题

### ISSUE THREAD

**Issue by DracoBogard** [MaaAssistantArknights/MaaAssistantArknights#9755]
### 说说你遇到的问题？

锏开局 MAA选了1技能波登可和嘉维尔 最后下锏 还不在医疗范围里

**Comment by Rbqwow** [comment]
第几层 什么关卡 提供的信息不够

现在的肉鸽逻辑暂时只考虑了维什戴尔开局 别急 在写了

**Comment by DracoBogard** [comment]
你好，本人正忙，稍后回复

**Comment by Daydreamer114** [comment]
强烈建议使用维什戴尔开局，同时这关不建议使用地面干员

**Comment by Nothing1031** [comment]
![image](https://github.com/user-attachments/assets/217200fe-8790-410f-973e-aab53f2babdb)
帮忙补个图，应该是和我遇到的同一个问题

**Comment by Daydreamer114** [comment]
> ![image](https://private-user-images.githubusercontent.com/34674655/350424055-217200fe-8790-410f-973e-aab53f2babdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTg5MzAsIm5iZiI6MTcyMTM5ODYzMCwicGF0aCI6Ii8zNDY3NDY1NS8zNTA0MjQwNTUtMjE3MjAwZmUtODc5MC00MTBmLTk3M2UtYWFiNTNmMmJhYmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE0MTcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ODljYTBhMjc4M2IxOWUyZjMwMzMxM2QxMmZmNDgxYTQ3N2VmOGYzNzkwMGVkMWRjY2ZjOGU0NjdiZDhiYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kMzKlL9kvIefUWUUJh-IODaWfHVG9BmmReVPHtYNCmw) 帮忙补个图，应该是和我遇到的同一个问题

这关就没写奶，我加一下吧

**Comment by Nothing1031** [comment]
原来逻辑都是大佬一个个图手搓的么？一下子觉得工作量好大

**Comment by Daydreamer114** [comment]
> 原来逻辑都是大佬一个个图手搓的么？一下子觉得工作量好大

有一个通用算法能顶替没写的，目前只写了5张图的
