### ISSUE TITLE
萨卡兹肉鸽 卡在竣工仪式

### ISSUE THREAD

**Issue by ShiLu1211** [MaaAssistantArknights/MaaAssistantArknights#9758]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题在竣工仪式停滞不前

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/16311344/gui.log)
[asst.log](https://github.com/user-attachments/files/16311345/asst.log)
2024-07-19 12:02:42.428

**Comment by Constrat** [comment]
Reopen when updated asst.log

**Comment by ShiLu1211** [comment]
[asst.log](https://github.com/user-attachments/files/16317693/asst.log)
