### ISSUE TITLE
萨卡兹肉鸽卡在进入门的干员归队

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9760]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

位置应该是进入下一层，和先行一步的归队一样
触发方式是用掉了生成门的思绪

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[asst - 副本.log](https://github.com/user-attachments/files/16311635/asst.-.log)
2024.07.19 18:57:40

### 截图

![MuMu12-20240719-195044](https://github.com/user-attachments/assets/ff831be2-5d06-483c-93f3-010a6965c6cb)

### 还有别的吗？

现在识别的是什么？在先行一步归队的位置加一个multi-tempelate？
@DavidWang19

**Comment by Daydreamer114** [comment]
[MuMu12-20240719-195044.zip](https://github.com/user-attachments/files/16311693/MuMu12-20240719-195044.zip)

**Comment by DavidWang19** [comment]
识别的这个×号

**Comment by Daydreamer114** [comment]
有位移吗

**Comment by DavidWang19** [comment]
fix by 0ed1171
