### ISSUE TITLE
萨卡兹肉鸽卡死在思绪舍弃界面

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9762]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

OCR是在干什么？
还没看log

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1.d018.g4ab5c5416
Core Version: v5.5.0-beta.1.d018.g4ab5c5416

### 日志文件

[asst.log](https://github.com/user-attachments/files/16312714/asst.log)
[gui.log](https://github.com/user-attachments/files/16312716/gui.log)

### 截图

![MuMu12-20240719-213630](https://github.com/user-attachments/assets/9c4a1fec-89e8-4a75-afa7-1fc29ec78dd3)

### 还有别的吗？

@Daydreamer114

**Comment by DavidWang19** [comment]
9c41379

**Comment by Daydreamer114** [comment]
Duplicate of #9738

**Comment by Daydreamer114** [comment]
实际bug为重复使用板子进入了“Sarkaz@Roguelike@ReturnConfirm"任务，此任务中没有通向舍弃思绪的出口，从而卡死
但已经修复了重复使用板子的bug，故无需修复此bug
