### ISSUE TITLE
萨卡兹肉鸽里发现ew三技能开启后会立即终止技能，不确定其他可终止的技能是否有相同问题

### ISSUE THREAD

**Issue by Nothing1031** [MaaAssistantArknights/MaaAssistantArknights#9768]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

打萨卡兹肉鸽的时候发现ew三技能开启后maa会立即去终止技能，每次只能打一发弹药，日志应该在23:53左右

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[debug.zip](https://github.com/user-attachments/files/16314320/debug.zip)

**Comment by Saratoga-Official** [comment]
你是不是mumu模拟器，是不是开了截图增强，如果截图太快maa会秒关的，最好关了增强再挂

**Comment by Nothing1031** [comment]
确实是Mumu，但是MAA的连接配置选的是通用模式，截图增强是要选择Mumu模拟器之后才能勾选的吧？而且在萨米肉鸽里ew的技能开关是正常的，目前只有在萨卡兹肉鸽里遇到这个问题

**Comment by Nothing1031** [comment]
> 确实是Mumu，但是MAA的连接配置选的是通用模式，截图增强是要选择Mumu模拟器之后才能勾选的吧？而且在萨米肉鸽里ew的技能开关是正常的，目前只有在萨卡兹肉鸽里遇到这个问题

刚刚又开了一把萨米，发现也有一样的问题了。。。之前还没有的

**Comment by ABA2396** [comment]
> 你是不是mumu模拟器，是不是开了截图增强，如果截图太快maa会秒关的，最好关了增强再挂

这玩意之前是加过最小时间间隔的，应该不是一个问题

**Comment by zhongfly** [comment]
在使用自动战斗打保全派驻时也出现了，而且模拟器是蓝叠模拟器，不是mumu，截图耗时较长，应该不是前面所说的截图较快导致
当前最新内测版 Core Version: v5.6.0-beta.1.d129.gf40ba2e58

**Comment by BlackFrog0216** [comment]
繁中服目前出現了上述的問題，使用異W掛薩米肉鴿時，技能打一砲就關閉了。版本是5.14.1。
