### ISSUE TITLE
关于萨卡兹无法正确导航的问题

### ISSUE THREAD

**Issue by YueHen14** [MaaAssistantArknights/MaaAssistantArknights#9774]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，MAA会一直导航去萨米肉鸽

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1.d018.g4ab5c5416
Core Version: v5.5.0-beta.1.d018.g4ab5c5416

### 日志文件

[asst.log](https://github.com/user-attachments/files/16316618/asst.log)
[gui.log](https://github.com/user-attachments/files/16316620/gui.log)

### 还有别的吗？

雷电模拟器9.0.73
1920x1080（dpi280）

**Comment by Rbqwow** [comment]
Duplicate of #9754

**Comment by YueHen14** [comment]
好的
