### ISSUE TITLE
萨卡兹肉鸽因藏品“无主的回忆”卡死

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9775]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题
这次无主的回忆在战斗掉落时获取

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1.d018.g4ab5c5416
Core Version: v5.5.0-beta.1.d018.g4ab5c5416

### 日志文件

[asst.bak - 副本.log](https://github.com/user-attachments/files/16317254/asst.bak.-.log)

### 截图

[MuMu12-20240720-053414.zip](https://github.com/user-attachments/files/16317230/MuMu12-20240720-053414.zip)
![MuMu12-20240720-053414](https://github.com/user-attachments/assets/0bee1c03-5d05-4bf5-900b-bdfd5f339ffc)
![MuMu12-20240720-053419](https://github.com/user-attachments/assets/bb7a744a-b727-4aa6-9ef0-037f692feb9c)
![MuMu12-20240720-053433](https://github.com/user-attachments/assets/10d416dc-de22-4525-842f-b516b77222fb)

### 还有别的吗？

喵

**Comment by DavidWang19** [comment]
fixed by 8ae3d9a
