### ISSUE TITLE
一个参数越界的错误

### ISSUE THREAD

**Issue by S7R31CH** [MaaAssistantArknights/MaaAssistantArknights#9779]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在执行“基建换班”后，出现错误弹窗，但不影响自动任务执行，后续任务正常结束。

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/16318563/gui.log)
[asst.log](https://github.com/user-attachments/files/16318564/asst.log)

错误发生在  2024-07-20 10:20:54 左右

### 截图

![屏幕截图 2024-07-20 102729](https://github.com/user-attachments/assets/62d93ba7-23e1-4240-b5e0-4181a12827d2)

**Comment by ABA2396** [comment]
看看你的排班表

**Comment by S7R31CH** [comment]
> 看看你的排班表

[罗德岛基建排班表v2.1.json](https://github.com/user-attachments/files/16319466/v2.1.json)
排班表是一图流自动生成的，应该没有自己直接改过json

**Comment by ABA2396** [comment]
之前有用过一天4换的排班表吗？刚发现了个bug，但应该是被兜底兜住了

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/5c513ddd-0b96-4e72-83b8-21e4faa93a9a)
看日志是之前切换过排班表但没选计划
