### ISSUE TITLE
在肉鸽中关内掉线/闪退 maa会持续等待

### ISSUE THREAD

**Issue by ErebusGleam** [MaaAssistantArknights/MaaAssistantArknights#9782]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用maa以及mumu12运行方舟的时候 在四点方舟自动更新后 然后就会maa呆滞，比如在关卡内掉线之后maa一直在等待关卡结束 

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16318825/asst.log)
[gui.log](https://github.com/user-attachments/files/16318826/gui.log)
大约4:00am时发生

### 还有别的吗？

mumu12 V3.93（3098）

**Comment by Saratoga-Official** [comment]
可以在四点定时让maa强制启动就行

**Comment by Saratoga-Official** [comment]
Duplicate of #9780

**Comment by Constrat** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9780
