### ISSUE TITLE
在肉鸽存钱模式中增加刷新商店的功能

### ISSUE THREAD

**Issue by ErebusGleam** [MaaAssistantArknights/MaaAssistantArknights#9783]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

在使用maa在肉鸽商店中存钱，发现存完钱就直接离开钱在购买藏品后仍有冗余

### 有什么好的想法？

建议在投资完成后，增加商店刷新功能并购买藏品，甚至可以增加藏品仓检仅购买未持有藏品

**Comment by DavidWang19** [comment]
在高级设置中打开“投资模式启用购物、招募”即可
