### ISSUE TITLE
建议肉鸽存钱策略，选蓝图队的时候进行刷新操作，尽量避战提高效率

### ISSUE THREAD

**Issue by MigdalBavel** [MaaAssistantArknights/MaaAssistantArknights#9784]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

蓝图队使用刷新尽量走不期而遇之类的非战节点存钱会快很多

**Comment by Rbqwow** [comment]
#9653
