### ISSUE TITLE
萨卡兹肉鸽用蓝图队刷源石锭策略可以优化

### ISSUE THREAD

**Issue by Oxalis3010** [MaaAssistantArknights/MaaAssistantArknights#9790]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

蓝图队有一个免费刷新次数，而一层节点只有战斗和不期而遇，可以让maa识别到战斗节点后刷新为不期而遇，有希望涂鸦选希望，然后速通一层

**Comment by Rbqwow** [comment]
在写了 别急
