### ISSUE TITLE
萨卡兹肉鸽反复刷新刷新次数用尽的紧急作战节点导致卡死

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9796]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

谁写的）

### Version

v5.5.0-beta.1.d064.g0e1cf6d04

### 日志文件

[asst.log](https://github.com/user-attachments/files/16321369/asst.log)
[gui.log](https://github.com/user-attachments/files/16321370/gui.log)

### 截图

![MuMu12-20240720-222315](https://github.com/user-attachments/assets/d80a3d6a-e1b3-463f-8a9c-cac94f4891b3)
[MuMu12-20240720-222315.zip](https://github.com/user-attachments/files/16321373/MuMu12-20240720-222315.zip)

**Comment by Daydreamer114** [comment]
应该是评分问题吧？次数用尽的threshold是不是太高了

**Comment by DavidWang19** [comment]
2cbc61b
