### ISSUE TITLE
Mac版什么时候能上线萨卡兹肉鸽存钱功能急急急

### ISSUE THREAD

**Issue by RArturia** [MaaAssistantArknights/MaaAssistantArknights#9797]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

更新了官网上的5.50Mac版但是打开还是没有萨卡兹肉鸽的选项
<img width="893" alt="image" src="https://github.com/user-attachments/assets/2910fcfd-451c-40e7-b948-f95737b62f27">

**Comment by Super-JX3** [comment]
最支持的一集

**Comment by Rbqwow** [comment]
https://maa.plus/docs/zh-cn/manual/cli/

太着急可以先用用 cli(

mac gui 有点缺人

**Comment by DavidWang19** [comment]
implemented in 994e78e
