### ISSUE TITLE
萨卡兹肉鸽驼兽归队导致卡死

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9798]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

是个不期而遇，巴别塔雇员
Ciallo～(∠・ω< )⌒★

### Version

v5.5.0-beta.1.d064.g0e1cf6d04

### 日志文件

[asst - 副本.log](https://github.com/user-attachments/files/16321528/asst.-.log)
[gui.log](https://github.com/user-attachments/files/16321529/gui.log)

### 截图

![MuMu12-20240720-231225](https://github.com/user-attachments/assets/afb7685c-5d21-47a9-95c6-5344f40bfe12)
[MuMu12-20240720-231225.zip](https://github.com/user-attachments/files/16321491/MuMu12-20240720-231225.zip)

**Comment by DavidWang19** [comment]
我在想这一系列问题是不是因为 CloseCollectionContinue 和 CloseEvent 的 roi 都不够大导致的

**Comment by DavidWang19** [comment]
不是 CloseEvent 是 CloseCollection

**Comment by DavidWang19** [comment]
fix by 0ed1171
