### ISSUE TITLE
萨卡兹肉鸽如何卸下负荷干员？

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9799]
### 说说你遇到的问题？

若新增代码，则截图三个头像并记住，然后点进去，匹配到这三个头像，进行点击

在已有的框架中，
最基本的思路，如何识别哪些干员在负荷上？
进而，如何通过批量点击的操作让所有干员都下负荷？

**Comment by Lancarus** [comment]
识别篮框和数字，这个要插件实现

**Comment by Daydreamer114** [comment]
目前正在尝试写插件，逻辑如下：
截屏->裁出3个位置的图像并用作template->点击一个位置->全屏做template match然后clickself
