### ISSUE TITLE
萨卡兹肉鸽 二层戴冠式 获取随机藏品概率卡死

### ISSUE THREAD

**Issue by NightAurora4** [MaaAssistantArknights/MaaAssistantArknights#9800]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [x] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

藏品效果为获取其他藏品或思绪时会只点一下然后一直卡在获取页面
如 无名图腾

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1.d032.gb60eea2de
Core Version: v5.5.0-beta.1.d032.gb60eea2de

### 日志文件

[asst.log](https://github.com/user-attachments/files/16321713/asst.log)
[gui.log](https://github.com/user-attachments/files/16321714/gui.log)
时间于2024-07-20 13:29:38.565

### 还有别的吗？

MUMU模拟器12

**Comment by DavidWang19** [comment]
你提供的 asst.log 是空的，你可以现在看看 asst.log.bak 还包不包含你说的时间（

**Comment by NightAurora4** [comment]
> 你提供的 asst.log 是空的，你可以现在看看 asst.log.bak 还包不包含你说的时间（

哦……已经被21号的覆盖完了（闭目）还有别的办法能找到历史记录吗T T

**Comment by Daydreamer114** [comment]
> 你提供的 asst.log 是空的，你可以现在看看 asst.log.bak 还包不包含你说的时间（

fixed by 8ae3d9a ?

**Comment by NightAurora4** [comment]
不止戴冠式，战斗结束获取藏品的时候如果藏品效果是立即获得思绪就会卡住，目前确定的藏品有 无主的回忆、一袋构想和无名图腾
[gui.log](https://github.com/user-attachments/files/16328004/gui.log)
[asst.bak.log.zip](https://github.com/user-attachments/files/16328012/asst.bak.log.zip)
时间于2024-07-22 06:19:29.787
检查更新显示maa已于最新版本

**Comment by Daydreamer114** [comment]
Duplicate of #9775
