### ISSUE TITLE
adb_lite 连接问题 （连接失败）

### ISSUE THREAD

**Issue by yc080713** [MaaAssistantArknights/MaaAssistantArknights#9805]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

开启 adb_lite 后，MAA 无法连接到蓝叠模拟器
关闭 adb_lite 则正常连接

这是 adb nodaemon server 的输出。问题发生时间同该输出

> adb.exe I 07-21 03:35:03 31680 34804 auth.cpp:416] adb_auth_init...
adb.exe I 07-21 03:35:03 31680 34804 auth.cpp:152] loaded new key from 'C:\Users\Administrator.Bili-2022KOIXUA\.android\adbkey' with fingerprint 464B811A3B571C2A6ADD00188B2C5CF3F498503C08BC1F2BA4A27C0A56E85383
adb.exe I 07-21 03:35:18 31680 29500 transport.cpp:335] 127.0.0.1:55955: read thread spawning
adb.exe I 07-21 03:35:18 31680 30816 transport.cpp:307] 127.0.0.1:55955: write thread spawning
adb.exe I 07-21 03:35:18 31680 34804 adb.cpp:172] 127.0.0.1:55955: already offline
adb.exe I 07-21 03:35:20 31680 34804 transport.cpp:1155] kicking transport 017b5560 127.0.0.1:55955
adb.exe I 07-21 03:35:20 31680 34804 transport.cpp:407] BlockingConnectionAdapter(127.0.0.1:55955): stopping
adb.exe I 07-21 03:35:20 31680 29500 transport.cpp:339] 127.0.0.1:55955: read failed: Invalid argument
adb.exe I 07-21 03:35:20 31680 29500 transport.cpp:1248] 127.0.0.1:55955: connection terminated: read failed
adb.exe I 07-21 03:35:20 31680 34804 transport.cpp:425] BlockingConnectionAdapter(127.0.0.1:55955): stopped
adb.exe I 07-21 03:35:20 31680 34804 adb.cpp:176] 127.0.0.1:55955: offline
adb.exe I 07-21 03:35:20 31680 34804 transport.cpp:931] destroying transport 127.0.0.1:55955
adb.exe I 07-21 03:35:20 31680 34804 transport.cpp:400] BlockingConnectionAdapter(127.0.0.1:55955): already stopped
adb.exe I 07-21 03:35:20 31680 34804 transport.cpp:294] BlockingConnectionAdapter(127.0.0.1:55955): destructing
adb.exe I 07-21 03:35:20 31680 34804 transport.cpp:400] BlockingConnectionAdapter(127.0.0.1:55955): already stopped
adb.exe I 07-21 03:35:22 31680 22352 transport.cpp:335] 127.0.0.1:55955: read thread spawning
adb.exe I 07-21 03:35:22 31680  3264 transport.cpp:307] 127.0.0.1:55955: write thread spawning
adb.exe I 07-21 03:35:22 31680 34804 adb.cpp:172] 127.0.0.1:55955: already offline

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1.d064.g0e1cf6d04
Core Version: v5.5.0-beta.1.d064.g0e1cf6d04

### 日志文件

[gui.log](https://github.com/user-attachments/files/16322136/gui.log)
[asst.log](https://github.com/user-attachments/files/16322137/asst.log)

---
这是配置文件
[gui.json](https://github.com/user-attachments/files/16322149/gui.json)
![image](https://github.com/user-attachments/assets/e3ef8336-0fa0-4d1d-9755-779181fe5691)

### 还有别的吗？

蓝叠模拟器 5.21.217.1010 Pie64

**Comment by yc080713** [comment]
希望作为一个待修复的 issue ，因为 adb lite 我曾经能用（昨天）

**Comment by Saratoga-Official** [comment]
所以为什么要开，都写实验功能肯定存在一些问题的

**Comment by Rbqwow** [comment]
草 问题不是开不开 问题是为什么会出问题

日志没看太懂 得等玛丽学姐她们看看

**Comment by Saratoga-Official** [comment]
我问学姐，学姐也说没看懂。。。

**Comment by yc080713** [comment]
> 勾选“连接失败后尝试重后ADBServer”看看

无效果，仍然连接失败
（是否要提供日志？）

**Comment by yc080713** [comment]
> 日志里的 `ÓÉÓÚÄ¿±ê¼ÆËã»ú»ý¼«¾Ü¾ø£¬ÎÞ·¨Á¬½Ó¡£` 似乎指的是“服务器没有响应（或本地服务器的套接字没有正确设置）”。 ​​adb-lite 会尝试与 127.0.0.1:5037 通信，不知道这个网络连接是否正常。

噢，这可能是个关键点！
因为我修改了 ANDROID_ADB_SERVER_PORT ，使其跑在了非 5037 端口上（该端口经常被占用）
现在我再尝试恢复原先的配置

**Comment by yc080713** [comment]
在复原 ANDROID_ADB_SERVER_PORT 后可正常连接
![image](https://github.com/user-attachments/assets/967e5637-b9f8-4ce7-bd44-e6356252319b)
![image](https://github.com/user-attachments/assets/56f79e35-cb2e-4370-85c7-88aca9c9d2ca)
（图中更换模拟器实例测试，也具有代表性）
