### ISSUE TITLE
基建无人机用于贸易站时只执行一次，导致无人机浪费

### ISSUE THREAD

**Issue by gnaw6403400** [MaaAssistantArknights/MaaAssistantArknights#9806]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题，这个问题注意到挺久了。每次基建换班用无人机的时候都只加速一次就出去了，希望能改进一下

**Comment by ABA2396** [comment]
无人机是会用完的，如果只用一次应该是bug，带上日志发bug反馈，最好有截图和录屏
