### ISSUE TITLE
思绪固化功能根本没做

### ISSUE THREAD

**Issue by AnonymousIIIII** [MaaAssistantArknights/MaaAssistantArknights#9807]
### 在提问之前...

- [ ] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨卡兹肉鸽无法思绪固化，固化关卡全部跳过

### Version

5.5.0版本

### 日志文件

[gui.log](https://github.com/user-attachments/files/16322805/gui.log)

**Comment by ABA2396** [comment]
好的，交给你来写好了

**Comment by SherkeyXD** [comment]
首先，请注意你提 issue 的语气，萨卡兹肉鸽还处于初期适配阶段，功能不完善是很正常的事，开发者们都有自己的生活，不可能全天候给你写 MAA。你可以提出 Feature Request，但友好且合理的语气是交流沟通的前提
其次，该功能已经出现在 dev 分支中，请至少看过 commit 记录再提 issue
