### ISSUE TITLE
萨卡兹肉鸽当蓝图分队为第一个分队时，MAA无法识别到蓝图分队

### ISSUE THREAD

**Issue by HYY1116** [MaaAssistantArknights/MaaAssistantArknights#9808]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

当额外分队仅解锁蓝图分队时，由于蓝图分队会排在指挥分队前面成为第一个分队，此时MAA无法正确识别蓝图分队位置（无法识别到），导致反复翻找分队

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1.d064.g0e1cf6d04
Core Version: v5.5.0-beta.1.d064.g0e1cf6d04

### 日志文件

[asst.log](https://github.com/user-attachments/files/16322904/asst.log)
[gui.log](https://github.com/user-attachments/files/16322905/gui.log)
10:34-10:38

### 截图

https://github.com/user-attachments/assets/cba447d0-a695-4726-8f96-e184d8fffcdc

### 还有别的吗？

Mumu模拟器，使用极速截图

**Comment by DavidWang19** [comment]
duplicate of #9793

**Comment by DavidWang19** [comment]
2bfbc1b
