### ISSUE TITLE
益达蓝图开局奖励选择问题

### ISSUE THREAD

**Issue by KoushuiFish** [MaaAssistantArknights/MaaAssistantArknights#9809]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

益达蓝图开局奖励选择希望减一导致五希望无法选择益达

### Version

Core Version: v5.5.0-beta.1.d064.g0e1cf6d04

### 日志文件

[asst.log](https://github.com/user-attachments/files/16323069/asst.log)
[gui.log](https://github.com/user-attachments/files/16323070/gui.log)
大概在7.21的12：00到12:10之间

### 还有别的吗？

我喜欢你！

**Comment by DavidWang19** [comment]
fixed by e5c6bc5
