### ISSUE TITLE
现在是没有内测版这个选项了么？？

### ISSUE THREAD

**Issue by aierxiya** [MaaAssistantArknights/MaaAssistantArknights#9810]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

一大早起来自动更新，发现只有稳定和公测两个选项了

### Version

UI Version: v5.5.0-beta.1.d077.g2cbc61b08
Core Version: v5.5.0-beta.1.d077.g2cbc61b08

### 日志文件

[asst.log](https://github.com/user-attachments/files/16323078/asst.log)
[gui.log](https://github.com/user-attachments/files/16323079/gui.log)

### 截图

![微信截图_20240721122147](https://github.com/user-attachments/assets/9b648a86-8dae-4369-8d2b-1b8769fc8b52)

**Comment by DavidWang19** [comment]
#9733
