### ISSUE TITLE
自动公招功能失效，没有进行公招而直接跳过

### ISSUE THREAD

**Issue by CrazyStudent13** [MaaAssistantArknights/MaaAssistantArknights#9814]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

问题情况：
自动公招勾选后，没有进行自动公招，直接跳过公招步骤，且MAA执行界面显示任务完成，详情参考截图。
我尝试过更新最新版本（内测版），但是依然无效
最后感谢您的工具，非常感谢。

### Version

Core Version: v5.4.1
UI Version: v5.4.1
Resource Version: 熔炉“还魂”记

### 日志文件

[asst.log](https://github.com/user-attachments/files/16323275/asst.log)

[gui.log](https://github.com/user-attachments/files/16323276/gui.log)

时间是2024/07/21，下午13点到14点半期间发现的。  

### 截图

![QQ_1721542118016](https://github.com/user-attachments/assets/7cfe3ba3-39db-4dc2-96c2-b1510918bc06)

![QQ_1721542156686](https://github.com/user-attachments/assets/de6a1228-5b0b-433e-bdc5-4b819cc8da90)

### 还有别的吗？

模拟器：mumu12
操作系统： win11

**Comment by Saratoga-Official** [comment]
有没有打开截图增强和gpu加速，有就关掉

**Comment by CrazyStudent13** [comment]
是的，目前关闭GPU加速就解决，感谢

**Comment by Rbqwow** [comment]
是intel显卡吗

**Comment by CrazyStudent13** [comment]
![image](https://github.com/user-attachments/assets/7738f970-ec49-4630-90f5-2e6b18e74c6b)

**Comment by Rbqwow** [comment]
maa的gpu加速还是能用独显就用独显吧 核显的问题太奇怪了(

**Comment by CrazyStudent13** [comment]
all right

**Comment by CrazyStudent13** [comment]
> maa的gpu加速还是能用独显就用独显吧 核显的问题太奇怪了(

all right

**Comment by Saratoga-Official** [comment]
目前经常有开gpu加速出问题的，要不要给gpu加速加点说明，或者不建议使用

**Comment by CrazyStudent13** [comment]
> 目前经常有开gpu加速出问题的，要不要给gpu加速加点说明，或者不建议使用

要目在常用的FAQ文档中加入说明  或者在更新的tips中加入提示也可以
