### ISSUE TITLE
在肉鸽中不能识别同一职业的不同分支之间的区别

### ISSUE THREAD

**Issue by raku8947** [MaaAssistantArknights/MaaAssistantArknights#982]
在肉鸽中似乎会将罗宾(陷阱师)识别为普通的特种干员而试图将其摆放在近战位上，并在失败后反复尝试。此外也会认为调香师(群愈师)具有正常医师的射程而将需要治疗的近战位干员摆放在射程之外。

**Comment by raku8947** [comment]
不好意思，才看到之前已经有人报过相同的bug了……

**Comment by zzyyyl** [comment]
攻击范围的问题其实还没人提过，不过也是老问题了，估计很难处理

**Comment by MistEO** [comment]
> 攻击范围的问题其实好像还没人提过，不过也是老问题了，估计很难处理

好处理，泰迪的数据里有。只是我懒得做，感觉区别并不大

**Comment by zzyyyl** [comment]
> > 攻击范围的问题其实好像还没人提过，不过也是老问题了，估计很难处理
> 
> 好处理，泰迪的数据里有。只是我懒得做，感觉区别并不大

原来 _攻击范围_ 和 _不同分支部署位置_ 的问题性质不一样的吗（那没事了

**Comment by MistEO** [comment]
> > > 攻击范围的问题其实好像还没人提过，不过也是老问题了，估计很难处理
> > 
> > 好处理，泰迪的数据里有。只是我懒得做，感觉区别并不大
> 
> 原来 _攻击范围_ 和 _不同分支部署位置_ 的问题性质不一样的吗（那没事了

一样的，数据里也有，我一开始没想到高台先锋这码事（

**Comment by MistEO** [comment]
修了
