### ISSUE TITLE
萨米肉鸽里，晋升已有干员和随机直升干员哪个优先级更高？

### ISSUE THREAD

**Issue by Nothing1031** [MaaAssistantArknights/MaaAssistantArknights#9820]
### 说说你遇到的问题？

今天挂机萨米肉鸽，战斗结算招募的时候可以选择精二ew，另外有个直升的莱伊，maa选择了莱伊，请问逻辑上是随机直升的优先级更高吗？

**Comment by Manicsteiner** [comment]
当前版本 ew 精二优先级为1000，莱伊随机直升e2 优先级 801，临时招募有额外加成（当前版本为+600），所以 1000<1401 优先招募了莱伊，大概就是这样的逻辑，如果随机直升的干员本身优先级较低（比如五星）则照常为ew精二。
相关数据在 resource\roguelike\Sami\recuriment.json。

**Comment by Nothing1031** [comment]
![image](https://github.com/user-attachments/assets/6a1c117a-78a4-4a38-abd1-aac5f05d89d3)
不知道我有没有理解对，意思是莱伊基础的招募优先级是681，但是有益达的情况下要-300，也就是381？关于直升或者临时招募不知道是什么关键词，这个文件里没找到

**Comment by Nothing1031** [comment]
另外好奇这些优先级排序不会都是手搓的吧？那也太牛了，能梳理得这么详细

**Comment by Daydreamer114** [comment]
手搓的，但有py工具
-300理解对了
直升、临时招募是固定加权，400好像

**Comment by Daydreamer114** [comment]
@Lancarus 这个offset的-300，这种情况没生效吗

**Comment by Nothing1031** [comment]
随机直升的加权是多少呢？当时的情况是精二ew和莱伊随机直升中选，最后MAA选了直升的莱伊。
精二ew我看优先级是1000，莱伊不算直升的加权应该才381，直升的加权这么大吗？

**Comment by Daydreamer114** [comment]
直升和临时我印象里是一样的
第一次回答你的佬说是600，我的印象里是400，但是如果offset生效了的话怎么说也不应该招莱伊

**Comment by Nothing1031** [comment]
那就很奇怪了，这次我也是恰巧双手离开键盘了瞄了一眼副屏，平时都没特别关注挂机的情况，本来只是感觉好奇来问问的

**Comment by Lancarus** [comment]
> @Lancarus 这个offset的-300，这种情况没生效吗

日志里会显示评分，建议传一下日志看看

**Comment by Lancarus** [comment]
临时招募是+600，随机直升是招募分和精二分加算，这里是681+801-300>1000了应该把分数调整一下，把key去掉，因为maa应该不太会用莱伊

**Comment by Daydreamer114** [comment]
> 临时招募是+600，随机直升是招募分和精二分加算，这里是681+801-300>1000了应该把分数调整一下，把key去掉，因为maa应该不太会用莱伊

ew的分还是低了（暴论
