### ISSUE TITLE
日服肉鴿小羊問題

### ISSUE THREAD

**Issue by XDXDMAN** [MaaAssistantArknights/MaaAssistantArknights#9821]
### 在提问之前...

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

日服肉鴿會招募小羊，進入戰鬥也會編入小羊，但是從沒下過小羊

### Version

Resource Version: 登臨意・復刻
UI Version: v5.4.1
Core Version: v5.4.1

### 日志文件

[debuglog_20240721.zip](https://github.com/user-attachments/files/16323526/debuglog_20240721.zip)

**Comment by Constrat** [comment]
@Manicsteiner no .PNG in cache probably. Regex not working for op detection when it's selected to create the avatar

**Comment by Manicsteiner** [comment]
```
[2024-07-21 05:09:22.826][TRC][Px87e0][Tx68d4] asst::WordOcr [{ エイヤフィヤ: [ 0, 0, 100, 18 ], score: 0.999865 }] by OCR Rec , cost 13 ms
[2024-07-21 05:09:22.837][TRC][Px87e0][Tx68d4] Proceed [{ エイヤフィヤ: [ 1010, 449, 100, 18 ], score: 0.999865 }]
```
Should be fixed by #9692 , please have a try with v5.5.0-beta1
