### ISSUE TITLE
在萨卡兹肉鸽中无法正确识别驮兽离开的事件

### ISSUE THREAD

**Issue by SST-03** [MaaAssistantArknights/MaaAssistantArknights#9823]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题。
我不确定为什么没有正确识别，但是maa就是卡了30min不动，甚至没有在debug/roguelike文件夹里留下报错图。

发生时间：今日17:35~18:05（卡了30min）、约18:11（重启maa后试图从当前页面继续肉鸽，仍然卡着，且没有报错）、18:28（同第二个时间点）

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1.d077.g2cbc61b08
Core Version: v5.5.0-beta.1.d077.g2cbc61b08

### 日志文件

[debug.zip](https://github.com/user-attachments/files/16323837/debug.zip)
[debug2.zip](https://github.com/user-attachments/files/16323875/debug2.zip)
内含asst.log和gui.log。

debug.zip包括了前两个时间点，debug2.zip是第三个时间点从MAA开启到关闭的日志
### 截图

![Screenshot](https://github.com/user-attachments/assets/bf968463-7759-4c79-bfd8-18b82d1e6ada)

**Comment by Rbqwow** [comment]
Duplicate of #9798

**Comment by SST-03** [comment]
> Duplicate of #9798

还有个问题，d077是最新的alpha版啊，也就是说实际问题可能是没修好

**Comment by Rbqwow** [comment]
那是因为修了还没发版 以commit历史为准

**Comment by SST-03** [comment]
> 那是因为修了还没发版 以commit历史为准

懂了
