### ISSUE TITLE
肉鸽中，建议在策略为“刷源石锭“时尽量避战

### ISSUE THREAD

**Issue by lxtyin** [MaaAssistantArknights/MaaAssistantArknights#9824]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前自动刷源石锭效率比较低，主要在于maa在“刷源石锭“策略下仍然会选择在第一层多打架；能否改成尽可能避战的策略？

### 有什么好的想法？

尽量走不期而遇，萨卡兹肉鸽中还可以把战斗节点刷掉。
还有，在商店投资完之后可以直接退出不需要进入第二层。

**Comment by status102** [comment]
确实是避战的策略，但是有些时候会识别错误，导致错误进入了战斗关卡

**Comment by Daydreamer114** [comment]
蓝图还没发版吧

**Comment by Daydreamer114** [comment]
duplicate #9750 #9790

**Comment by status102** [comment]
> 蓝图还没发版吧

不是蓝图的问题，旧肉鸽都有

**Comment by Daydreamer114** [comment]
避战有，不知道前仨怎么写的
萨卡兹肉鸽刷新节点已经在dev里了
进第二层是为了拿分

**Comment by DavidWang19** [comment]
最后一条在高级设置里关闭投资时招募购物即可

**Comment by DavidWang19** [comment]
另外蓝图队刷新节点的逻辑已经写好了，还没有发beta版

**Comment by lxtyin** [comment]
> 最后一条在高级设置里关闭投资时招募购物即可

原来如此，感谢
