### ISSUE TITLE
关于萨卡兹肉鸽刷源石碇，蓝图分队刷新节点避战提高效率的建议。

### ISSUE THREAD

**Issue by luoye240** [MaaAssistantArknights/MaaAssistantArknights#9825]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

我想到一种提高刷源石碇的效率的方法。

### 有什么好的想法？

在使用maa的过程中，我注意到脚本在蓝图分队中不会通过刷新节点得到非战斗节点，是否可以添加一个功能，即刷源石碇策略中，蓝图分队在战斗节点主动刷新（或者有构想时主动刷新），从而提高效率。感谢开发者的查阅

**Comment by status102** [comment]
> duplicate #9750 #9790 #9824

重复的记得关掉

Duplicate of #9750 #9790 #9824
