### ISSUE TITLE
肉鸽拿到获得思绪的藏品后会卡在思绪界面

### ISSUE THREAD

**Issue by LinYanxi0** [MaaAssistantArknights/MaaAssistantArknights#9829]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

rt，通过藏品获得思绪后会卡在获得思绪后弹出的那个界面
如 无名图腾（立刻获得3缕不同种类的思绪）

### 有什么好的想法？

动作超时不动的时候，点三下屏幕中间把思绪过了，然后继续或重开

### 其他内容

目前查wiki只看到这个是通过藏品获得思绪的

**Comment by Daydreamer114** [comment]
Duplicate of #9775

**Comment by SherkeyXD** [comment]
下一个内测版即将修复
