### ISSUE TITLE
萨卡兹肉鸽 干员在下一层从门里逃出来的界面（XXX从混沌未来中逃脱）会因为识别不了而卡住

### ISSUE THREAD

**Issue by wufenghuonb** [MaaAssistantArknights/MaaAssistantArknights#9832]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题

### Version

UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[日志文件.zip](https://github.com/user-attachments/files/16325313/default.zip)

### 截图

多次卡死经查看均为该情况

### 还有别的吗？

MUMU12 Win10

**Comment by Rbqwow** [comment]
Duplicate of #9760
