### ISSUE TITLE
日服自動戰鬥問題

### ISSUE THREAD

**Issue by XDXDMAN** [MaaAssistantArknights/MaaAssistantArknights#9834]
### 说说你遇到的问题？

請問日服的自動戰鬥是否有問題，今天試著用神秘代碼/作業那邊的自動戰鬥連N次WB-7，我也設定好連續戰鬥次數了，但是MAA戰鬥一次之後回到選擇關卡就會停止了

**Comment by Saratoga-Official** [comment]
如果你觉得有问题，提个bugissue，没log我们也不知道有没有问题
