### ISSUE TITLE
在使用`v5.5.0-beta.1.d109.g50ddefa76`时一点Link Start就

### ISSUE THREAD

**Issue by WallBreakerNO4** [MaaAssistantArknights/MaaAssistantArknights#9838]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

更新至最新内测版后无法正常使用，点击`Link Start`就直接闪退

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1.d109.g50ddefa76
Core Version: v5.5.0-beta.1.d109.g50ddefa76

### 日志文件

[asst.log](https://github.com/user-attachments/files/16327245/asst.log)
[gui.log](https://github.com/user-attachments/files/16327246/gui.log)

**Comment by ABA2396** [comment]
423a37bfbbc1c24b09d412a28436a9ff55eb864f 85f1a719a326476853bf23f156718a17b51f5d3c fixed
等待 action https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/10033837247
