### ISSUE TITLE
萨卡兹肉鸽目前还有出现某个界面一直卡住的情况，是否可以增加功能，过一段时间后重启

### ISSUE THREAD

**Issue by fzj-official** [MaaAssistantArknights/MaaAssistantArknights#9839]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

**Comment by Saratoga-Official** [comment]
为啥不直接把卡住的地方修了呢，提个bugissue说一下你卡的地方

**Comment by Daydreamer114** [comment]
Owner不喜欢治标不治本的方法（逃
你可以去看一下open着和close了的issue，应该已经有你遇到过的情况了

**Comment by Saratoga-Official** [comment]
我是觉得可以未计划关闭

**Comment by Rbqwow** [comment]
那倒说一下是哪卡住了 方便复现

是bug得修的
