### ISSUE TITLE
MAA在部分紧急作战关卡无法进入

### ISSUE THREAD

**Issue by AlEcK98** [MaaAssistantArknights/MaaAssistantArknights#9844]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在我使用MAA的自动肉鸽功能时，当遇到部分紧急作战MAA无法进入编队状态而是反复点击出发前往

### Version

UI Version: v5.5.0-beta.1.d064.g0e1cf6d04
Core Version: v5.5.0-beta.1.d064.g0e1cf6d04

### 日志文件

[asst.log](https://github.com/user-attachments/files/16328424/asst.log)
[gui.log](https://github.com/user-attachments/files/16328425/gui.log)

### 截图

![MAA](https://github.com/user-attachments/assets/d6ea9b7d-709b-4f61-948e-007f55b1e7b2)
![模拟器](https://github.com/user-attachments/assets/4f9d98c3-8334-48d9-a663-7e2c120e3e4b)

### 还有别的吗？

使用mumu模拟器，win11系统

**Comment by Daydreamer114** [comment]
Duplicate of #9796

**Comment by Daydreamer114** [comment]
Fixed by 2cbc61b
