### ISSUE TITLE
萨卡兹肉鸽在驮兽离开队伍时卡死

### ISSUE THREAD

**Issue by AlEcK98** [MaaAssistantArknights/MaaAssistantArknights#9846]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨卡兹肉鸽在驮兽离开队伍时，MAA似乎会反复无效点击，从而使界面卡住

### Version

UI Version: v5.5.0-beta.1.d064.g0e1cf6d04
Core Version: v5.5.0-beta.1.d064.g0e1cf6d04

### 日志文件

[gui.log](https://github.com/user-attachments/files/16329861/gui.log)
[asst.log](https://github.com/user-attachments/files/16329862/asst.log)

### 截图

https://github.com/user-attachments/assets/5eb23603-16ce-4597-84f0-d975cc120825

**Comment by Rbqwow** [comment]
Duplicate of #9798

fixed
