### ISSUE TITLE
突然上报失败？

### ISSUE THREAD

**Issue by insine-inverse** [MaaAssistantArknights/MaaAssistantArknights#9849]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

今天早上开始就识别报错，只打了主线12-17标准

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16330584/asst.log)
[gui.log](https://github.com/user-attachments/files/16330585/gui.log)

### 截图

<img width="196" alt="1721638464597" src="https://github.com/user-attachments/assets/d6790d05-ff90-43e9-bbba-bc555e2d7478">

**Comment by ABA2396** [comment]
企鹅炸了
