### ISSUE TITLE
群里牛牛没了

### ISSUE THREAD

**Issue by 1arkn** [MaaAssistantArknights/MaaAssistantArknights#985]
速修复，急

**Comment by GitHub-Inull** [comment]
牛牛😭我的牛牛。没了你我怎么活啊😭😭😭

**Comment by ABA2396** [comment]
https://github.com/InvoluteHell/Pallas-Bot

**Comment by 1arkn** [comment]
不是啊maa群里的牛牛无了

**Comment by zzyyyl** [comment]
牛牛相关的问题到[这里](https://github.com/InvoluteHell/Pallas-Bot/issues)发

**Comment by MistEO** [comment]
虽然但是，这是新功能，喝了酒开枪有概率崩到自己。修复什么。。
