### ISSUE TITLE
刷萨卡兹肉鸽时跳转到充值界面

### ISSUE THREAD

**Issue by ImYiFeng** [MaaAssistantArknights/MaaAssistantArknights#9852]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如图，刷萨卡兹肉鸽一段时间后回来再看，MAA在反复放弃探索，游戏在充值界面。期间可以保证没有任何干扰模拟器的操作

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[asst.bak.log](https://github.com/user-attachments/files/16331697/asst.bak.log)
[gui.log](https://github.com/user-attachments/files/16331701/gui.log)
问题出现大致时间点：2024-07-22 17:29:01.164

### 截图

![08f3caff928cb90cfcb5bbd0b42a6dd2](https://github.com/user-attachments/assets/b480188c-bb78-47e2-96e3-5dea572f209f)

### 还有别的吗？

mumu12模拟器，启用mumu截图增强模式，windows11操作系统，开启GPU推理加速，GPU为RTX4060LAPTOP

**Comment by ImYiFeng** [comment]
> 你有一些文件没有上传成功，请重新上传。
> 
> You have some files that did not upload successfully, please re-upload them.

已重新上传

**Comment by status102** [comment]
看看debug\roguelike下的图片
例如debug\roguelike\2024-07-22_17-29-18-376_raw.png

**Comment by ImYiFeng** [comment]
> 看看debug\roguelike下的图片 例如debug\roguelike\2024-07-22_17-29-18-376_raw.png

你提到的这张图片是我一开始试图用MAA去挂妮芙的月度小队，卡在选择妮芙的页面，貌似没有参考价值

我提供一些有参考价值的截图：
2024-07-22_17-32-11-680_raw.png
![2024-07-22_17-32-11-680_raw](https://github.com/user-attachments/assets/5079cc0b-a911-4e86-9113-1c463bbf1846)
2024-07-22_17-32-42-791_raw.png
![2024-07-22_17-32-42-791_raw](https://github.com/user-attachments/assets/fd6538f1-7484-4a7d-ae25-298948822a87)

另外，在本Issue提出后这种情况有复现。时间太久日志已经丢失，只能提供一些截图

2024-07-22_19-49-42-097_raw.png
![2024-07-22_19-49-42-097_raw](https://github.com/user-attachments/assets/5e2944aa-3718-4b02-aff8-40744ff47d7b)
2024-07-22_19-50-52-097_raw.png
![2024-07-22_19-50-52-097_raw](https://github.com/user-attachments/assets/f027df5b-8087-4fba-805a-1eea3134c622)
2024-07-22_19-51-17-424_raw.png
![2024-07-22_19-51-17-424_raw](https://github.com/user-attachments/assets/283fce6e-61ee-4966-9e7d-6b5cc8fa807a)
2024-07-22_19-52-20-385_raw.png
![2024-07-22_19-52-20-385_raw](https://github.com/user-attachments/assets/92346697-b334-4756-a628-1522bf56e035)

**Comment by Saratoga-Official** [comment]
感觉可能是截图增强原因，maa点快可能点出去了？可以试试关了
也有可能是gpu加速原因，最近有几例因为gpu加速导致的识别异常，不过用的集显，所以这种可能性比较低
