### ISSUE TITLE
萨卡兹肉鸽寻路存在问题

### ISSUE THREAD

**Issue by x5p9** [MaaAssistantArknights/MaaAssistantArknights#9857]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

寻路最后会卡死在下面那个截图界面

### Version

Core Version: v5.5.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16333659/asst.log)
[gui.log](https://github.com/user-attachments/files/16333662/gui.log)
2024.07.22 20:58:00 开始进行自动肉鸽，随后因为寻路问题卡住了

### 截图

![Screenshot_2024 07 22_21 00 42 481](https://github.com/user-attachments/assets/15b932fe-82ad-4062-903a-0a48b5d70816)

**Comment by Daydreamer114** [comment]
Duplicate of #9754

**Comment by ntgmc** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/797bf26c4015bc57f9e00cd5a46a868222eb734b
