### ISSUE TITLE
SSScopilot运行出错

### ISSUE THREAD

**Issue by ioakkkk** [MaaAssistantArknights/MaaAssistantArknights#9858]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在开始部署界面无法运行SSScopilot

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1.d032.gb60eea2de
Core Version: v5.5.0-beta.1.d032.gb60eea2de

### 日志文件

[asst.log](https://github.com/user-attachments/files/16333774/asst.log)
[gui.log](https://github.com/user-attachments/files/16333775/gui.log)

### 截图

![image](https://github.com/user-attachments/assets/43124cec-5c15-4b82-a154-b24d16bb9f94)

**Comment by Daydreamer114** [comment]
```python
[2024-07-22 09:12:22.001][TRC][Px2e2c][Tx6338] asst::ProcessTask::_run | enter
[2024-07-22 09:12:22.001][INF][Px2e2c][Tx6338] {"class":"asst::ProcessTask","details":{"cur_retry":1,"retry_times":20,"to_be_recognized":["0000026803B4EDF0@SSSBegin","SSSStartFighting"]},"first":["0000026803B4EDF0@SSSBegin","SSSStartFighting"],"pre_task":"","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":1}
[2024-07-22 09:12:22.013][TRC][Px2e2c][Tx6338] asst::PipelineAnalyzer::analyze 0000026803B4EDF0@SSSBegin
[2024-07-22 09:12:22.060][TRC][Px2e2c][Tx6338] asst::WordOcr [{ : [ 0, 0, 288, 144 ], score: 0.000000 }] by OCR Pipeline , cost 47 ms
[2024-07-22 09:12:22.060][TRC][Px2e2c][Tx6338] Proceed []
[2024-07-22 09:12:22.060][TRC][Px2e2c][Tx6338] asst::PipelineAnalyzer::analyze SSSStartFighting
[2024-07-22 09:12:22.106][TRC][Px2e2c][Tx6338] asst::WordOcr [{ : [ 0, 0, 288, 144 ], score: 0.000000 }] by OCR Pipeline , cost 45 ms
[2024-07-22 09:12:22.106][TRC][Px2e2c][Tx6338] Proceed []
[2024-07-22 09:12:22.106][TRC][Px2e2c][Tx6338] asst::ProcessTask::_run | leave, 105 ms
[2024-07-22 09:12:22.106][TRC][Px2e2c][Tx6338] ready to sleep 500
[2024-07-22 09:12:22.607][TRC][Px2e2c][Tx6338] end of sleep 500

**Comment by Daydreamer114** [comment]
这是你第一次把模拟器拉这么长用吗

**Comment by status102** [comment]
```
[2024-07-22 09:11:11.334][TRC][Px30d8][Tx6228] asst::WordOcr [{ 重返未来999: [ 388, 21, 93, 15 ], score: 0.698816 }, { 年最后一天雨: [ 387, 45, 114, 13 ], score: 0.800353 }, { [周: [ 0, 55, 96, 30 ], score: 0.604483 }, { : [ 324, 86, 24, 12 ], score: 0.000000 }, { 命运契: [ 387, 90, 53, 15 ], score: 0.766552 }, { : [ 5, 112, 69, 11 ], score: 0.000000 }, { : [ 0, 88, 52, 23 ], score: 0.000000 }, { 命运印记赴之: [ 387, 114, 112, 15 ], score: 0.777686 }, { : [ 25, 206, 41, 25 ], score: 0.000000 }, { : [ 25, 220, 44, 31 ], score: 0.000000 }, { 应用分身: [ 16, 266, 60, 19 ], score: 0.865423 }, { 系统应用: [ 237, 266, 60, 19 ], score: 0.715227 }, { 小工具: [ 464, 267, 46, 16 ], score: 0.731152 }] by OCR Pipeline , cost 760 ms
[2024-07-22 09:11:11.335][TRC][Px30d8][Tx6228] Proceed []
```
开了后台保活？
![image](https://github.com/user-attachments/assets/042a2147-f702-40a2-a69e-f6b4117884e1)

**Comment by ioakkkk** [comment]
> 这是你第一次把模拟器拉这么长用吗

“拉这么长”指窗口还是？

**Comment by ioakkkk** [comment]
> ```
> [2024-07-22 09:11:11.334][TRC][Px30d8][Tx6228] asst::WordOcr [{ 重返未来999: [ 388, 21, 93, 15 ], score: 0.698816 }, { 年最后一天雨: [ 387, 45, 114, 13 ], score: 0.800353 }, { [周: [ 0, 55, 96, 30 ], score: 0.604483 }, { : [ 324, 86, 24, 12 ], score: 0.000000 }, { 命运契: [ 387, 90, 53, 15 ], score: 0.766552 }, { : [ 5, 112, 69, 11 ], score: 0.000000 }, { : [ 0, 88, 52, 23 ], score: 0.000000 }, { 命运印记赴之: [ 387, 114, 112, 15 ], score: 0.777686 }, { : [ 25, 206, 41, 25 ], score: 0.000000 }, { : [ 25, 220, 44, 31 ], score: 0.000000 }, { 应用分身: [ 16, 266, 60, 19 ], score: 0.865423 }, { 系统应用: [ 237, 266, 60, 19 ], score: 0.715227 }, { 小工具: [ 464, 267, 46, 16 ], score: 0.731152 }] by OCR Pipeline , cost 760 ms
> [2024-07-22 09:11:11.335][TRC][Px30d8][Tx6228] Proceed []
> ```
> 
> 开了后台保活？ ![image](https://private-user-images.githubusercontent.com/102887808/351015124-042a2147-f702-40a2-a69e-f6b4117884e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzM3MjEsIm5iZiI6MTcyMTY3MzQyMSwicGF0aCI6Ii8xMDI4ODc4MDgvMzUxMDE1MTI0LTA0MmEyMTQ3LWY3MDItNDBhMi1hNjllLWY2YjQxMTc4ODRlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxODM3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDZiMDhkY2QwYTdhOTA5OTgzMzFhNzVkNDlmYzdlMDNjYWNkYTcyNGM0YjYwN2MxMzVjZDc0MmMzMGQ3YWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IRFwHjUWnt348k7vA_KfVTJR3WP_Oq8RADvpNHCPykg)

![image](https://github.com/user-attachments/assets/67b62ddd-5fdb-41bf-885d-8b851531fff0)
重启后关了保活还是出问题

**Comment by status102** [comment]
> > ```
> > [2024-07-22 09:11:11.334][TRC][Px30d8][Tx6228] asst::WordOcr [{ 重返未来999: [ 388, 21, 93, 15 ], score: 0.698816 }, { 年最后一天雨: [ 387, 45, 114, 13 ], score: 0.800353 }, { [周: [ 0, 55, 96, 30 ], score: 0.604483 }, { : [ 324, 86, 24, 12 ], score: 0.000000 }, { 命运契: [ 387, 90, 53, 15 ], score: 0.766552 }, { : [ 5, 112, 69, 11 ], score: 0.000000 }, { : [ 0, 88, 52, 23 ], score: 0.000000 }, { 命运印记赴之: [ 387, 114, 112, 15 ], score: 0.777686 }, { : [ 25, 206, 41, 25 ], score: 0.000000 }, { : [ 25, 220, 44, 31 ], score: 0.000000 }, { 应用分身: [ 16, 266, 60, 19 ], score: 0.865423 }, { 系统应用: [ 237, 266, 60, 19 ], score: 0.715227 }, { 小工具: [ 464, 267, 46, 16 ], score: 0.731152 }] by OCR Pipeline , cost 760 ms
> > [2024-07-22 09:11:11.335][TRC][Px30d8][Tx6228] Proceed []
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 开了后台保活？ ![image](https://private-user-images.githubusercontent.com/102887808/351015124-042a2147-f702-40a2-a69e-f6b4117884e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzM3MjEsIm5iZiI6MTcyMTY3MzQyMSwicGF0aCI6Ii8xMDI4ODc4MDgvMzUxMDE1MTI0LTA0MmEyMTQ3LWY3MDItNDBhMi1hNjllLWY2YjQxMTc4ODRlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxODM3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDZiMDhkY2QwYTdhOTA5OTgzMzFhNzVkNDlmYzdlMDNjYWNkYTcyNGM0YjYwN2MxMzVjZDc0MmMzMGQ3YWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IRFwHjUWnt348k7vA_KfVTJR3WP_Oq8RADvpNHCPykg)
> 
> ![image](https://private-user-images.githubusercontent.com/129583163/351078825-67b62ddd-5fdb-41bf-885d-8b851531fff0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTI2MDksIm5iZiI6MTcyMTY5MjMwOSwicGF0aCI6Ii8xMjk1ODMxNjMvMzUxMDc4ODI1LTY3YjYyZGRkLTVmZGItNDFiZi04ODVkLThiODUxNTMxZmZmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQyMzUxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzVkM2U5MzM0ZjFkZWM0OWQzZDQ1MTk1OWYxZTQzMDAyMzlhOTg1MTMxODUxMDAwMzgzMzE3OWY2OGIwMzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DsiAEpYvOnjazJDEhnwFHEveqsDpVTBkD2lwJY7zTDU) 重启后关了保活还是出问题

复现后给个log吧（
没有log怎么查问题呀，给你算一卦吗~

**Comment by status102** [comment]
能复现的话，点下reopen吧，点按钮不花钱的

**Comment by ioakkkk** [comment]
[asst.log](https://github.com/user-attachments/files/16341402/asst.log)
[gui.log](https://github.com/user-attachments/files/16341403/gui.log)


> 能复现的话，点下reopen吧，点按钮不花钱的

怎么reopen, 没搞过真不懂，reopen 按钮也没看到

**Comment by status102** [comment]
> 怎么reopen, 没搞过真不懂，reopen 按钮也没看到

![image](https://github.com/user-attachments/assets/2511e89b-bedb-442c-a627-f16c11b058bf)

**Comment by ioakkkk** [comment]
> > 怎么reopen, 没搞过真不懂，reopen 按钮也没看到
> 
> ![image](https://private-user-images.githubusercontent.com/102887808/351151662-2511e89b-bedb-442c-a627-f16c11b058bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTY4OTMsIm5iZiI6MTcyMTY5NjU5MywicGF0aCI6Ii8xMDI4ODc4MDgvMzUxMTUxNjYyLTI1MTFlODliLWJlZGItNDQyYy1hNjI3LWYxNmMxMWIwNThiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwMTAzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGI0ZGI0N2NkYTc4YWUyNGRjNDgyYjY1MDc4ZTVlMDY3ZTdlNzE3NmM4NTQxYmNkNTgzN2M5ZjMyZGU5MzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sisQnZjQUxUsCfk1-8Gc2m1nK1zX4lKoVdpgpoUtrvw)

![image](https://github.com/user-attachments/assets/4d8c1d0c-c4b4-42c9-8f3b-e715e80cad61)

**Comment by status102** [comment]
那不太清楚了，主要是close的issue容易被忽略

**Comment by ioakkkk** [comment]
![image](https://github.com/user-attachments/assets/b07a3cda-330c-41a7-9ce8-080fc49015b4)
刷关也刷不了，但自动肉鸽还是可以运行
[asst.log](https://github.com/user-attachments/files/16341499/asst.log)
[gui.log](https://github.com/user-attachments/files/16341500/gui.log)

**Comment by Saratoga-Official** [comment]
有没有开gpu加速

**Comment by status102** [comment]
> > ```
> > [2024-07-22 09:11:11.334][TRC][Px30d8][Tx6228] asst::WordOcr [{ 重返未来999: [ 388, 21, 93, 15 ], score: 0.698816 }, { 年最后一天雨: [ 387, 45, 114, 13 ], score: 0.800353 }, { [周: [ 0, 55, 96, 30 ], score: 0.604483 }, { : [ 324, 86, 24, 12 ], score: 0.000000 }, { 命运契: [ 387, 90, 53, 15 ], score: 0.766552 }, { : [ 5, 112, 69, 11 ], score: 0.000000 }, { : [ 0, 88, 52, 23 ], score: 0.000000 }, { 命运印记赴之: [ 387, 114, 112, 15 ], score: 0.777686 }, { : [ 25, 206, 41, 25 ], score: 0.000000 }, { : [ 25, 220, 44, 31 ], score: 0.000000 }, { 应用分身: [ 16, 266, 60, 19 ], score: 0.865423 }, { 系统应用: [ 237, 266, 60, 19 ], score: 0.715227 }, { 小工具: [ 464, 267, 46, 16 ], score: 0.731152 }] by OCR Pipeline , cost 760 ms
> > [2024-07-22 09:11:11.335][TRC][Px30d8][Tx6228] Proceed []
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 开了后台保活？ ![image](https://private-user-images.githubusercontent.com/102887808/351015124-042a2147-f702-40a2-a69e-f6b4117884e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzM3MjEsIm5iZiI6MTcyMTY3MzQyMSwicGF0aCI6Ii8xMDI4ODc4MDgvMzUxMDE1MTI0LTA0MmEyMTQ3LWY3MDItNDBhMi1hNjllLWY2YjQxMTc4ODRlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxODM3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDZiMDhkY2QwYTdhOTA5OTgzMzFhNzVkNDlmYzdlMDNjYWNkYTcyNGM0YjYwN2MxMzVjZDc0MmMzMGQ3YWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IRFwHjUWnt348k7vA_KfVTJR3WP_Oq8RADvpNHCPykg)
> 
> ![image](https://private-user-images.githubusercontent.com/129583163/351078825-67b62ddd-5fdb-41bf-885d-8b851531fff0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTg0ODUsIm5iZiI6MTcyMTY5ODE4NSwicGF0aCI6Ii8xMjk1ODMxNjMvMzUxMDc4ODI1LTY3YjYyZGRkLTVmZGItNDFiZi04ODVkLThiODUxNTMxZmZmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwMTI5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGNhOWUzZDM2ZDAyYTY2NzI3ZjYwODAyNzM2ODI3MTk0ZmM1NTQxN2RjNzQwOWYwODEyYTJhZjc3YjRmYWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v43ATeye4x-pPxsp9egTocHYk0fEjKlQYyPdsj9t-Qg) 重启后关了保活还是出问题

```
[2024-07-22 14:46:17.227][INF][Px2c70][Tx4ba8] {"class":"asst::ProcessTask","details":{"cur_retry":14,"retry_times":20,"to_be_recognized":["0000015908708150@SSSBegin","SSSStartFighting"]},"first":["0000015908708150@SSSBegin","SSSStartFighting"],"pre_task":"","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":1}
[2024-07-22 14:46:17.241][TRC][Px2c70][Tx4ba8] asst::PipelineAnalyzer::analyze 0000015908708150@SSSBegin
[2024-07-22 14:46:17.329][TRC][Px2c70][Tx4ba8] asst::WordOcr [{ 始署: [ 105, 71, 102, 26 ], score: 0.850789 }] by OCR Pipeline , cost 89 ms
[2024-07-22 14:46:17.329][TRC][Px2c70][Tx4ba8] Proceed []
[2024-07-22 14:46:17.329][TRC][Px2c70][Tx4ba8] asst::PipelineAnalyzer::analyze SSSStartFighting
[2024-07-22 14:46:17.425][TRC][Px2c70][Tx4ba8] asst::WordOcr [{ 始署: [ 105, 71, 102, 26 ], score: 0.850789 }] by OCR Pipeline , cost 94 ms
[2024-07-22 14:46:17.425][TRC][Px2c70][Tx4ba8] Proceed []
```
看起来是奇怪的ocr导致

**Comment by ioakkkk** [comment]
> 有没有开gpu加速
显示系统默认GPU,算开了吧

**Comment by Saratoga-Official** [comment]
关了应该就解决了

**Comment by ioakkkk** [comment]
> 把gpu加速关了应该就解决了，gpu不能用集显，系统默认的集显 最近好几例因为开gpu加速ocr识别异常的

解决了，谢谢

**Comment by ioakkkk** [comment]
解决了，谢谢
