### ISSUE TITLE
基建搓玉制造站不放人

### ISSUE THREAD

**Issue by helloIris415** [MaaAssistantArknights/MaaAssistantArknights#986]
基建制造站会出现不放人的bug。
![image](https://user-images.githubusercontent.com/63986965/175811806-8858aa2f-7435-4e4c-b0f1-6f1d1ed2801e.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8986477/asst.log)

**Comment by MistEO** [comment]
v4.2.2-beta.1 修了一个基建滑动失效的问题，可能是这个原因，不过现在也没啥头绪总之先关了，之后再出现再来个日志看看（
