### ISSUE TITLE
是否可以对萨卡兹肉鸽的刷原石锭策略进行改进

### ISSUE THREAD

**Issue by x5p9** [MaaAssistantArknights/MaaAssistantArknights#9860]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

https://www.bilibili.com/video/BV1U4421Z7WA 参照该视频，是否可以调整萨卡兹肉鸽刷源石锭的策略，用蓝图队速刷源石锭数量，提高刷取效率

**Comment by Daydreamer114** [comment]
Duplicate of 我都不想找了快关

**Comment by Daydreamer114** [comment]
Duplicate of #9750 #9790 #9825

**Comment by ntgmc** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/0e1cf6d040b2fe39bf49a58af41d07b2c094f67f
