### ISSUE TITLE
萨卡兹肉鸽ew开局选取四星

### ISSUE THREAD

**Issue by ala-404** [MaaAssistantArknights/MaaAssistantArknights#9867]
### 说说你遇到的问题？

https://github.com/user-attachments/assets/65984c3f-058e-4239-9490-d700db63285a

开局阶段重装干员会直接选取斑点而不是古米，这个选取逻辑是按照等级来判断的吗

**Comment by Lancarus** [comment]
稍微把等级拉一拉，不会选精1 50级以下的
