### ISSUE TITLE
用windows任务计划从休眠状态开启maa后无法连接模拟器

### ISSUE THREAD

**Issue by RyuGaGotoku3** [MaaAssistantArknights/MaaAssistantArknights#9869]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

maa执行所有任务后自动休眠，使用Windows任务计划自动定时启动maa后会自动开启但无法连接模拟器，只有重新启动后可以连接

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.1
Core Version: v5.4.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/16337402/gui.log)
[asst.log](https://github.com/user-attachments/files/16337403/asst.log)

**Comment by Rbqwow** [comment]
@ABA2396 这个是不是也是 MuMu 断网 adb 超时的问题 看日志挺像

**Comment by RyuGaGotoku3** [comment]
怎么解决呢

**Comment by RyuGaGotoku3** [comment]
> @ABA2396 这个是不是也是 MuMu 断网 adb 超时的问题 看日志挺像

怎么解决呢

**Comment by RyuGaGotoku3** [comment]
> @ABA2396 这个是不是也是 MuMu 断网 adb 超时的问题 看日志挺像

我选择的是完成任务后关闭maa和模拟器并休眠。

**Comment by RyuGaGotoku3** [comment]
> @ABA2396 这个是不是也是 MuMu 断网 adb 超时的问题 看日志挺像

解决了，把设置里的断线自动重练关掉就可以了
