### ISSUE TITLE
v4.0.0 掉线统计出错

### ISSUE THREAD

**Issue by zzyyyl** [MaaAssistantArknights/MaaAssistantArknights#987]
掉线统计出错，导致开始行动统计次数异常（多减了一次）
![image](https://user-images.githubusercontent.com/74587068/175812354-31ba822f-b39a-4ea6-8209-fb5d06375f48.png)
日志：
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8986507/asst.zip)

**Comment by zzyyyl** [comment]
大概找到了问题的原因，`GameStart` / `OfflineConfirm` 有几率多次进入导致 
 `reduceOtherTimes` 重复执行

**Comment by zzyyyl** [comment]
可能需要改改 `reduceOthrtTimes` 的逻辑，比如最多 reduce 一次之类的？

**Comment by lhhxxxxx** [comment]
![image](https://user-images.githubusercontent.com/91231470/184656178-b956b9d3-079b-499d-9fae-4e0c243dee90.png)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/9337862/asst.log)
类似问题
