### ISSUE TITLE
希望在主页增加重启maa的按键

### ISSUE THREAD

**Issue by TranslationBot2046** [MaaAssistantArknights/MaaAssistantArknights#9870]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用maa大概半年，发现maa的开发更新比较频繁，很多使用场景都是在我正需要使用maa而打开它时，更新要求我首先重启maa，maa的更新频率不太有空间调整，把maa一直挂在后台随时自动更新也不是时刻都能做到，所以比较好的解决办法应该是改进一下自动更新的操作流程。

### 有什么好的想法？

希望作者在maa主页增加一键重启的按键，可以至少减少一下手动打开maa→等待更新结束→关闭maa并再次打开这个流程的麻烦。

**Comment by Rbqwow** [comment]
设置→自动安装更新

版本更新和资源更新就都会自动重启了

**Comment by Saratoga-Official** [comment]
自动安装更新包勾选上可以自动重启，减少更新频率可以使用稳定版，至少十天半个月才更新一次的
