### ISSUE TITLE
ci: Resource Updater workflow rule violation

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#9872]
### Description

https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/10045959677/job/27764388916
@zzyyyl Rules not being bypassed? What rules were being bypassed before. Pushing directly do dev?
Anyway they are not being bypassed anymore

```
remote: error: GH013: Repository rule violations found for refs/heads/dev.        
remote: Review all repository rules at http://github.com/MaaAssistantArknights/MaaAssistantArknights/rules?ref=refs%2Fheads%2Fdev        
remote: 
remote: - 2 of 2 required status checks are expected.        
remote: 
To https://github.com/MaaAssistantArknights/MaaAssistantArknights.git
 ! [remote rejected]     HEAD -> dev (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/MaaAssistantArknights/MaaAssistantArknights.git'
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (D:\a\_actions\ad-m\github-push-action\master\start.js:30:21)
    at ChildProcess.emit (node:events:[51](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/10046555529/job/27766255432#step:21:52)9:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1
}
```

the github-push-action is one of the only ones not updated as it's already @ master

Could the           github_token: ${{ secrets.MAA_RESOURCE_SYNC }}
not be enough to bypass?

**Comment by zzyyyl** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/settings/rules/228939

The ruleset is also not updated and it already has the bypass of the 'Write' role. It's weird to be able to push (with the write role) but not bypass.

I rollback the secret used in the push-action to "MISTEOWORKFLOW".

**Comment by Constrat** [comment]
Rulesets seem a bit broken to me, especially the bypasses.
Being only able to merge through the Github app is crazy

**Comment by Constrat** [comment]
@zzyyyl Still broken. I'm guessing the issue is not really the secret being used but this 
![image](https://github.com/user-attachments/assets/8689ff2f-d517-4c0b-a3a6-8af673cf0bd1)

**Comment by Constrat** [comment]
I'll revert everything temporarily as we need the resource updater to be up and running.

**Comment by Constrat** [comment]
I think it's a combination, perhaps not only the push itself, but also the commits need to use MISTEOWORKFLOW? Or just the commits need MISTEOWORKFLOW? Or at least a secret that has the right permissions for the bypass.

**Comment by Constrat** [comment]
I'll do some more testing off production

**Comment by Constrat** [comment]
(Also why is there always your name in the Authenticated user XD)

**Comment by zzyyyl** [comment]
> (Also why is there always your name in the Authenticated user XD)

Because I generate the MAA_RESOURCE_SYNC :smile:

**Comment by Constrat** [comment]
Oh, before it was using the one that enabled the workflow, or the one that pushed manually for res update. I think it made more sense before? At least for the manual push.

**Comment by zzyyyl** [comment]
Actually I don't know why the $env:ACTOR is always your name XD

Maybe we could just use `secrets.GITHUB_TOKEN` and the committer should be `github-actions[bot]`

**Comment by zzyyyl** [comment]
> After reading around, I really think the MAA_RESOURCE_SYNC is wrongly configured.

maybe need a test `MAA_RESOURCE_SYNC` -> `MISTEOWORKFLOW`

**Comment by zzyyyl** [comment]
the MAA_RESOURCE_SYNC permission: https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/9635#issuecomment-2225208786

**Comment by Constrat** [comment]
I don't know anymore

**Comment by Constrat** [comment]
Nothing, not even GITHUB_TOKEN works. I have no more ideas. I would just disable that stupid checker tbh.

**Comment by Constrat** [comment]
https://github.com/orgs/community/discussions/25305
This is a discussion similar, that says the default github_bot can't as it would be stupid.

**Comment by Constrat** [comment]
Ok I tried EVERYTHING. 
this is how I'm feeling: 
![image](https://github.com/user-attachments/assets/b098903d-314d-4b9b-8873-d9139f942c12)

**Comment by Constrat** [comment]
I fucking hate not being able to bypass the push action.
@zzyyyl I can't always be checking the actions to see the if the updater is working or not.

**Comment by Constrat** [comment]
I can't believe this
I cannot fucking believe it.

The fucking `actions/checkout` makes it's token hereditary EVERYWHERE
