### ISSUE TITLE
Mac版本没有萨卡兹肉鸽选项

### ISSUE THREAD

**Issue by zycBruce** [MaaAssistantArknights/MaaAssistantArknights#9873]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

Mac版本打开自动肉鸽没有萨卡兹肉鸽选项

**Comment by Rbqwow** [comment]
Duplicate of #9797
