### ISSUE TITLE
在Mac版本中切换客户端版本的时候,包名不会更改,导致自动启动客户端功能失败(iOS)

### ISSUE THREAD

**Issue by royli1994** [MaaAssistantArknights/MaaAssistantArknights#9878]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

在Mac版本中切换客户端版本的时候,包名不会更改,导致自动启动客户端功能失败.
使用的Mac 模拟器是PlayCover 3.0.0.maa.5（5）
MAA:v5.5.0-beta.1（500）
官服:com.hypergryph.arknights
日服:com.YoStarJP.Arknights

### 有什么好的想法？

希望能有配置文件切换之类的功能.

### 其他内容

另:切换客户端之后可能会出现一些未知的识别失败,重启MAA之后解决.
希望能有一些内部软重启之类的功能

**Comment by Daydreamer114** [comment]
切换明日方舟客户端服务器，maa从来都是要求重启的，mac端的maa在切换服务器的时候不提示你重启maa吗

**Comment by royli1994** [comment]
> 切换明日方舟客户端服务器，maa从来都是要求重启的，mac端的maa在切换服务器的时候不提示你重启maa吗

使用中未见到相关提示

**Comment by ABA2396** [comment]
cc @hguandl

**Comment by status102** [comment]
```
bool asst::PlayToolsController::start_game(const std::string& client_type [[maybe_unused]])
{
    return true;
}
```
Mac的MAA应该是不会开游戏的吧（？
