### ISSUE TITLE
萨卡兹肉鸽中下干员不避开毒圈

### ISSUE THREAD

**Issue by ytfh44** [MaaAssistantArknights/MaaAssistantArknights#9886]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨卡兹肉鸽中，MAA部署干员时不会规避带毒的地块，这导致干员快速倒下，无法起到战斗中的作用

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/16344782/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/16344784/asst.bak.log)

### 还有别的吗？

模拟器：maa最新版
操作系统：win11 23h2
配置：MAAtouch，但貌似无关

附：希望在别的肉鸽中，也识别并规避刺箱（）

**Comment by Saratoga-Official** [comment]
萨卡兹目前除了第一层，剩下的关卡都没写专门的战斗逻辑，是maa自己放的，所以不会规避毒圈，这不是bug，这是没做完

**Comment by Saratoga-Official** [comment]
而且毒圈位置是固定的还有方法规避，刺箱是随机的且maa没那么高级识别出战斗中的刺箱，你要求太高了

**Comment by Daydreamer114** [comment]
not planned
