### ISSUE TITLE
开代理更新时下载速度还是没有起来

### ISSUE THREAD

**Issue by aierxiya** [MaaAssistantArknights/MaaAssistantArknights#9889]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

不知道是不是我http格式填错了还是怎么第，麻烦各位看看拉

### Version

UI Version: v5.5.0-beta.1.d064.g0e1cf6d04
Core Version: v5.5.0-beta.1.d064.g0e1cf6d04

### 日志文件

[asst.log](https://github.com/user-attachments/files/16346060/asst.log)
[gui.log](https://github.com/user-attachments/files/16346061/gui.log)

### 截图

![微信截图_20240723164228](https://github.com/user-attachments/assets/003c3856-78f3-43f0-9696-6dddca9c8e0b)
![微信截图_20240723164223](https://github.com/user-attachments/assets/22b1db78-e911-46fd-be4f-4aeab69f1849)

**Comment by Rbqwow** [comment]
这咋说呢 也不能都和我一样搞规则 @ABA2396 

maa服务器最近带不动了 要是自动更新太慢就上github release下完手动更新吧

**Comment by ABA2396** [comment]
要不还是加个勾选框来优先使用github代理吧

**Comment by Rbqwow** [comment]
先workaround等资源更新重构¿
