### ISSUE TITLE
关于萨卡兹肉鸽无法刷存款的问题

### ISSUE THREAD

**Issue by TAN90temp** [MaaAssistantArknights/MaaAssistantArknights#9890]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

目前问题是在开启刷存款模式的情况下在一层不会对商店节点进行进入操作，而是在进行印象加深后卡住，然后结束本次探索，且无报错信息，如图

### Version

UI Version: v5.5.0-beta.1.d177.ge8d4a64e1
Core Version: v5.5.0-beta.1.d177.ge8d4a64e1

### 日志文件

[gui.log](https://github.com/user-attachments/files/16347380/gui.log)
[新建压缩.zip](https://github.com/user-attachments/files/16347401/default.zip)

### 截图

![屏幕截图 2024-07-23 183053](https://github.com/user-attachments/assets/68442dae-c168-4d46-bbea-2850af46d0b1)
[故障视频.zip](https://github.com/user-attachments/files/16347463/default.zip)

### 还有别的吗？

使用mumu模拟器V3.9.5（3129）

**Comment by TAN90temp** [comment]
主要是上个版本还能刷，这个版本不行了，可能是此版本新增的插件判断相关功能判断出问题了

**Comment by qqoo1224** [comment]
同发现此问题，环境：
UI Version: v5.5.0-beta.1.d220.g2e7aa2d1f
Core Version: v5.5.0-beta.1.d220.g2e7aa2d1f

mumu12-3.9.5(3129)，尝试过修改分辨率为720p，问题依旧
