### ISSUE TITLE
萨卡兹肉鸽 戴冠式 卡住

### ISSUE THREAD

**Issue by UVJkiNTQ** [MaaAssistantArknights/MaaAssistantArknights#9891]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

卡在获取的灵感 “天灾”

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/16348084/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/16348087/asst.bak.log)

### 截图

![Screenshot_20240723-193736](https://github.com/user-attachments/assets/e4e95936-d5d0-4e4c-87e9-12e7f6dff66b)

**Comment by Saratoga-Official** [comment]
Duplicate of #9775

**Comment by Daydreamer114** [comment]
> Duplicate of #9775

帅
