### ISSUE TITLE
希望萨卡兹肉鸽刷钱到二层开头可以选了藏品再退

### ISSUE THREAD

**Issue by InfraFour** [MaaAssistantArknights/MaaAssistantArknights#9894]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题，二层开头命运所指固定给一个藏品，拿了再退的话可以在大量刷钱中兼顾贪一点刷分数效率和补藏品图鉴的几率。
直接选择烧开水或尽可能打完功能的话，体感时间上就花得太长了，相比之下多走一个固定事件不需要运气也不容易bug

### 有什么好的想法？

希望可以评估一下藏品得分是否值得做个分支

**Comment by Daydreamer114** [comment]
如果要做的话得做个ui开关，刷钱默认时间效率优先

**Comment by SherkeyXD** [comment]
刷钱模式一切以效率为先，想刷等级用刷等级模式

萨卡兹肉鸽选择蓝图会自动使用速刷模式，效率并不低
