### ISSUE TITLE
萨卡兹自动肉鸽换层遇到灵感弹窗无法识别进行下一步动作

### ISSUE THREAD

**Issue by mozun54** [MaaAssistantArknights/MaaAssistantArknights#9895]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

换层时出现的灵感详细说明的弹窗，MAA无法识别并点击进行下一步操作
![QQ20240724-015340](https://github.com/user-attachments/assets/516b4320-2369-4cc7-ba50-7f6f9158e026)
会出现不断进行放弃探索的指令
![QQ_1721757242031](https://github.com/user-attachments/assets/be8aa0b3-f23f-41b9-875b-b3754d799698)

### Version

Resource Version: 熔炉“还魂”记，UI Version: v5.5.0-beta.1.d177.ge8d4a64e1，Core Version: v5.5.0-beta.1.d177.ge8d4a64e1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16352599/asst.log)
[gui.log](https://github.com/user-attachments/files/16352600/gui.log)

### 还有别的吗？

Mumu模拟器

**Comment by LunaGlaze** [comment]
附言：
Resource Version: 熔炉“还魂”记 
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1
使用雷电模拟器，出现了相同问题

**Comment by DavidWang19** [comment]
fixed by 2e7aa2d
