### ISSUE TITLE
肉鸽使用已有干员列表加速招募选人动作

### ISSUE THREAD

**Issue by KJH-x** [MaaAssistantArknights/MaaAssistantArknights#9898]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

对于肉鸽招募环节，
通过识别的、导入的干员列表，（或，额外地，配合招募券类型），在已知编队成员和希望的条件下，应该可以在开始招募之前通过配置算出当前应该抓谁（对于每一次招募，各个职业，都可以生成一个各稀有度的抓序），而不需要每次都重新翻阅整个可招募列表，点入券后直接选完走人，减少时间消耗

### 有什么好的想法？

若能实现该方案，其效果应该与开局选指定干员的速度相似

### 其他内容

应当作为肉鸽设置的可选项

extra feature

- 可以在开始此种设置肉鸽时列出提示，让用户知道当前记录的干员列表是何时导入/自动识别的干员列表
- 并在列表超过一段时间（如一个月）的时候以warning提醒重新识别或者通过新增一个按钮确认列表无需更新（将记录的添加日期改到当前）等

**Comment by HoshinoAyako** [comment]
缓存大爆炸~

**Comment by Constrat** [comment]
To be fair it won't save much time: 
- To select the operator, MAA still needs to swipe and check names, so instead of two checks it would only do one. 
- MAA checks for E2 and levels. When using the class starts (vanguard / guard for example), some E2 will be random, meaning that MAA would still have to check for operators. 

The logic as already been optimized once, to skip operators that can't be recruited because of low morale.
Logically speaking implementing some sort of caching or using the operator detection toolbox, wouldn't be any useful as the I.S. can still be very random, and MAA needs to check for all possibilities.

**Comment by KJH-x** [comment]
> To be fair it won't save much time: 
> 
> - To select the operator, MAA still needs to swipe and check names, so instead of two checks it would only do one. 
> 
> - MAA checks for E2 and levels. When using the class starts (vanguard / guard for example), some E2 will be random, meaning that MAA would still have to check for operators. 
> 
> 
> 
> The logic as already been optimized once, to skip operators that can't be recruited because of low morale.
> 
> Logically speaking implementing some sort of caching or using the operator detection toolbox, wouldn't be any useful as the I.S. can still be very random, and MAA needs to check for all possibilities.

Your opinion is acceptable when we try to let MAA play better in I.S.(clear more nodes for more score).

However when it comes to 'invest and quit' choice, there is apparently fewer battles nodes to cover (usually < 2, and relatively easier for it's 1F). In this scenario, my suggestion might be more profitable in terms of saving time.

It's common among my friends that they wait for auto investment to complete. Small optimisation would be helpful.

Or perhaps we can be even more aggressive. We can provide an option to skip all recruitment if user is confident enough with it.

**Comment by Constrat** [comment]
For the investing choice, there's already a different algorithm used, which not aggressive, compared to the main runs that try to clear as many nodes as possible.

To skip all recruitments there needs to be luck in getting no fights at all. In case there's even one fight, the run will have to restart and the optimized "seconds" you gain from skipping recruit are all gone.

As I said. The optimizations you can get in the run is minimal. Yes, it can add up in case of multiple runs especially for the investing choice but the risk increases exponentially compared to the saved time.

**Comment by KJH-x** [comment]
What I mean by "skip all recruitment" is to skip recruitment chances after battle or from other sources, where the initial recruitment is excluded.

With the strong-enough initial team, it's OK to reach the 2F, almost without a problem.

**Comment by KJH-x** [comment]
整理一下目前的诉求，还是比较希望能落地这个功能。
**基于以下事实**
- 维什戴尔(Wiš'adel)很强大，精一(E1)足以在低难情况下碾压第一层
- 蓝图队在不持有死仇的情况下，较高概率刷新出非战斗节点
- 一层的战斗不难，即使有漏也漏不了太多，单人可以完成

**基于以下诉求**
- 大多数刷钱的都希望越快越好（高强度集成战略玩家）

**功能描述：**

在选择刷钱后在高级设置提供一个独立的选项：使用蓝图维什戴尔
注：也可以使用助战

1. 选择蓝图分队，选择含有狙击的招募
2. 仅招募维什戴尔，编入思绪（减少两次招募时间）
3. 地图阶段遇到战斗节点刷新一次（避免战斗）
4. 结束战斗等道中获得招募券选择不招募，放弃机会（减少招募时间）
5. 存钱
6. 结束
