### ISSUE TITLE
希望可以在会客室添加一个可选功能：会客室线索超过一定数量自动赠送好友

### ISSUE THREAD

**Issue by 1113132859** [MaaAssistantArknights/MaaAssistantArknights#9900]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 有什么好的想法？

希望可以在会客室添加一个可选功能：会客室线索超过一定数量自动赠送好友

**Comment by sunsheep1018** [comment]
想問自動贈送線索的好友能指定嗎

**Comment by ABA2396** [comment]
现在是线索满了送三个
