### ISSUE TITLE
MAA资源更新多次失败

### ISSUE THREAD

**Issue by AssassinVIX** [MaaAssistantArknights/MaaAssistantArknights#9904]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA多次游戏资源更新失败，重新安装也不好使

### Version

5.5.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16363164/asst.log)
[gui.log](https://github.com/user-attachments/files/16363166/gui.log)

### 还有别的吗？

电脑版本Win1123H2

**Comment by xiaoweiXX** [comment]
MAA服务器不行，多等等吧

**Comment by Constrat** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9708

**Comment by KUAPT** [comment]
尝试全局魔法再次更新，或许能解决问题（我看log感觉是这样，我自己是这样解决的
