### ISSUE TITLE
萨卡兹肉鸽蓝图分队存钱逻辑问题

### ISSUE THREAD

**Issue by beijinren** [MaaAssistantArknights/MaaAssistantArknights#9907]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在刷新节点次数用完时，若仍未刷出不期而遇，则会直接卡住，不会进入作战。

### Version

Resource Version: 熔炉“还魂”记
**UI Version: v5.5.0-beta.1.d220.g2e7aa2d1f**
**Core Version: v5.5.0-beta.1.d220.g2e7aa2d1f**

### 日志文件

2024.7.25 10.30左右

**Comment by DavidWang19** [comment]
你的日志文件呢

**Comment by Saratoga-Official** [comment]
> 你的日志文件呢

看#9912 的日志吧，反正是一个问题
