### ISSUE TITLE
“开始唤醒”任务失败时停止任务链

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9908]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

如果开始任务失败的话就不执行剩下的勾选任务以免出现未知问题
![屏幕截图 2024-07-25 120741](https://github.com/user-attachments/assets/46fa8f5e-ea6c-429c-bd9a-b34ed8bfcb7d)

**Comment by status102** [comment]
没啥必要感觉，唤醒不成功，后面执行也跑不成

**Comment by Rbqwow** [comment]
有duplicate 但我忘了(
