### ISSUE TITLE
开始唤醒无法自动同意用户协议更新

### ISSUE THREAD

**Issue by JRQBill** [MaaAssistantArknights/MaaAssistantArknights#9909]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

开始唤醒切换账号后会卡在同意用户协议更新的界面无法进行下一步操作

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.1
Core Version: v5.4.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16370506/asst.log)
[gui.log](https://github.com/user-attachments/files/16370508/gui.log)
12：05任务出错

### 截图

![MuMu12-20240725-124147](https://github.com/user-attachments/assets/27babc87-11ea-4b73-b1bb-852c3b092ae7)

**Comment by Saratoga-Official** [comment]
maa不会自动帮你同意协议的，这个必须自己同意
