### ISSUE TITLE
登录时能不能加个协议自动同意确认

### ISSUE THREAD

**Issue by zoe4477** [MaaAssistantArknights/MaaAssistantArknights#9914]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

yj现在时不时会更新协议需要重新同意，MAA定时任务启动游戏就会卡在这登录不了，导致排班紊乱
![image](https://github.com/user-attachments/assets/a972f88a-b74c-41b4-ad4d-a2f30587b4b6)

**Comment by Saratoga-Official** [comment]
#9909 有说明
