### ISSUE TITLE
自动公招无法正常进行

### ISSUE THREAD

**Issue by zxmydmug** [MaaAssistantArknights/MaaAssistantArknights#9915]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在进行公招时，会卡在放弃招募然后跳到基建换班

### Version

5.50 beta 1

### 日志文件

拖不上来

### 还有别的吗？

mumu12，开启gpu加速和mumu增强
win10，其他功能正常

**Comment by Saratoga-Official** [comment]
都没日志，在这算命呢
