### ISSUE TITLE
萨卡兹肉鸽卡在肉鸽选择界面

### ISSUE THREAD

**Issue by xiao-MC666** [MaaAssistantArknights/MaaAssistantArknights#9916]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨卡兹肉鸽卡在肉鸽选择界面，长时间无响应

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/16378290/asst.log)
[gui.log](https://github.com/user-attachments/files/16378292/gui.log)

### 截图

![Screenshot_2024 07 25_21 16 51 114](https://github.com/user-attachments/assets/10296e07-1a0d-4881-90dc-5ba66674358a)

### 还有别的吗？

蓝叠模拟器，win10系统

**Comment by ABA2396** [comment]
b1的导航有点问题，点进肉鸽再开始任务

**Comment by Saratoga-Official** [comment]
保证主页里有肉鸽，固定完之后要清理剿灭或者保全给肉鸽腾出地方
