### ISSUE TITLE
基建无人机用于贸易站时只执行一次，导致无人机浪费

### ISSUE THREAD

**Issue by gnaw6403400** [MaaAssistantArknights/MaaAssistantArknights#9919]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如题，这个问题注意到挺久了。每次基建换班用无人机的时候都只加速一次就出去了

### Version

Core Version: v5.4.1

### 日志文件

[gui.log](https://github.com/user-attachments/files/16383945/gui.log)
[asst.log](https://github.com/user-attachments/files/16383946/asst.log)

### 截图

https://github.com/user-attachments/assets/842c37df-46f9-4dfe-9be3-31a0426b7786

### 还有别的吗？

win10，雷电模拟器9

**Comment by ABA2396** [comment]
这加速看着好奇怪，按视频里这样16分钟加速18分钟应该是直接结束这一单了，不会有剩下两三秒的情况。
maa在加速完之后如果还是 `获取订单中` 就会当做无人机不够加速了

**Comment by gnaw6403400** [comment]
是，我又观察了一下，有时候剩3秒也可以识别继续用，这个尝试的时间加一两秒会不会容错大点

**Comment by ABA2396** [comment]
怎么感觉是网络问题，我试了几次都是直接秒完成的，不会是本地时间和服务器时间不同步吧
cc @status102

**Comment by gnaw6403400** [comment]
这个要怎么查看，雷电模拟器在北美用会有这种问题吗

**Comment by ABA2396** [comment]
那和模拟器没关系，离方舟的服务器太远了）

**Comment by status102** [comment]
> 怎么感觉是网络问题，我试了几次都是直接秒完成的，不会是本地时间和服务器时间不同步吧 cc @status102

未能复现（（

**Comment by ABA2396** [comment]
看了下这玩意还真不好改，对流程影响很大，这玩意本来就做了3.5s的延迟，但是这个主要卡在了连接服务器上面。如果你要改的话可以自己去resource/tasks.json中把
```
    "DroneConfirm": {
        "action": "ClickSelf",
        "postDelay": 3500,
        "roi": [778, 501, 377, 165],
        "next": ["DroneConfirm@LoadingText", "DeliverableOrder", "DroneAssist-Trade-Stop", "DroneAssistMfg"]
    },
```
中的 `3500` 改大，比如改成 `10000` （等10s），就是每次版本更新之后得再改一次
