### ISSUE TITLE
刷关如果无法选择， maa 会卡住不动

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaAssistantArknights#992]
周一刷钱本，无法进入的话maa会一直卡住。

我想是不是应该跳过清体力？

**Comment by MistEO** [comment]
会跳过啊，你多等一会就好了

**Comment by Shawnsdaddy** [comment]
> 卡5>分钟算正常嘛？还是因为有时差问题？它以为我这周日呢？

**Comment by Shawnsdaddy** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8988599/asst.log)
