### ISSUE TITLE
萨卡兹肉鸽存钱模式到达商店自动退出

### ISSUE THREAD

**Issue by Elegetic** [MaaAssistantArknights/MaaAssistantArknights#9920]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

流程：打开MAA后选择萨卡兹肉鸽，点击存钱模式，干员与开局皆选择默认，分队选择蓝图分队

过程：正常到达诡异行商后使用思绪升级商店，后停留在思绪升级界面时间较长，停留结束后**在未进入商店的情况下选择重开**。

似乎在**留有足够思绪升级商店**的情况下会触发，若思绪在先前已用尽（在成功存钱的记录中都有紧急作战，应该是刷新完毕后的结果），则会正常存钱。
可能是思绪升级界面出现问题导致的？纯存钱模式的逻辑中应该无需对商店进行升级。

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1.d226.g34540de43
Core Version: v5.5.0-beta.1.d226.g34540de43

### 日志文件

[asst.log](https://github.com/user-attachments/files/16385013/asst.log)
[gui.log](https://github.com/user-attachments/files/16385014/gui.log)

为了复现问题重新下载了一次beta版开始游戏，log全程为问题测试。

### 还有别的吗？

模拟器：Mumu12，启用MuMuExtras与GPU加速
操作系统：Windows 11 Pro 23H2

CPU: AMD Ryzen 9 6900HX
GPU: RTX 3080Ti Laptop
内存：32G DDR5

**Comment by Saratoga-Official** [comment]
Duplicate of #9890

**Comment by Constrat** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9890

**Comment by Constrat** [comment]
Fixed with https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/c69e212be99a579e6247c0473488e932958422b2
