### ISSUE TITLE
添加游戏闪退时自动重开功能

### ISSUE THREAD

**Issue by HfSrJun** [MaaAssistantArknights/MaaAssistantArknights#9921]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

近期在MAA挂机时，游戏有概率会闪退，而MAA并不会对此做出任何回应，只会停在原地

### 有什么好的想法？

添加新功能，在单一页面或单一步骤消耗过长时间（或者其他判定方法）则判定为游戏已经崩溃，尝试重新执行启动游戏功能

**Comment by Saratoga-Official** [comment]
参考 #9780

**Comment by HfSrJun** [comment]
> 参考 #9780

问题并不相同
我指的闪退并非是四点数据更新产生的，而是游戏运行不正常导致的。例如昨晚我并没有挂肉鸽，只是运行收菜流程，但在公招完成后游戏崩溃。

**Comment by Rbqwow** [comment]
![ed0310f393410e76372a9df0f06fc3fe](https://github.com/user-attachments/assets/15e3398a-5af0-43d5-9253-bfcff244c16d)

**Comment by status102** [comment]
Duplicate of #5538
