### ISSUE TITLE
部分关卡MAA自动战斗无法自动使用技能

### ISSUE THREAD

**Issue by PandaYuuHa** [MaaAssistantArknights/MaaAssistantArknights#9923]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

部分关卡在自动战斗时一直在尝试使用技能，但无法正常点击使用按钮，目前我发现的有 货物运送 CE-6 和 水月肉鸽 ISW-NO 饥渴
疑似是由于地图形状导致的点击位置偏移

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.4.1
Core Version: v5.4.1

### 日志文件

[asst.bak.log](https://github.com/user-attachments/files/16388939/asst.bak.log)
[gui.log](https://github.com/user-attachments/files/16388944/gui.log)

大致是在7.26 16:30分前后，打到肉鸽关卡时尝试使用技能点不到，和前几天打CE-6的时候现象一致

### 截图

![饥渴](https://github.com/user-attachments/assets/2bc2b3c3-1b95-4af8-bcb6-204e461d8259)

### 还有别的吗？

使用的模拟器是mumu模拟器，另外在观察这两个关卡技能图标的时候，mumu自带的按键配置中的右键快捷释放技能，都是能点到的
我觉得可以参考mumu的配置来修改maa的点击位置

**Comment by Daydreamer114** [comment]
> ![acf9a3d338b3416f00a445f5507360a8](https://private-user-images.githubusercontent.com/55343783/352476065-37b08f42-c13e-42c0-a49e-fda2b775c736.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDEzMDcsIm5iZiI6MTcyMjAwMTAwNywicGF0aCI6Ii81NTM0Mzc4My8zNTI0NzYwNjUtMzdiMDhmNDItYzEzZS00MmMwLWE0OWUtZmRhMmI3NzVjNzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEzMzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4Yzc1M2FhMjFlMWRjMmViMTI1YWU1YWVlODhjZmE2Njk2ZmIxZDIyODRiZGE3MzhiZDA0ZDM2NGE0NDM1YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XUlOx2BTHAjJIwQUm53Av-ayOnnWSc3FT1kI5Jur6x8) 已知问题 都会错位 都在给丫丁擦屁股
> 
> 应该做模板匹配 但是找不到该咋匹配 只能先这样

template里有“BattleSkill”系列图片，在tasks里能获得识别成功的roi并进行加减后进行点击的操作吗

**Comment by Rbqwow** [comment]
识别不了 那个图案会扭曲

**Comment by ABA2396** [comment]
现在会进行矩阵映射然后匹配，应该已经解决了
