### ISSUE TITLE
萨卡兹蓝图刷钱bug

### ISSUE THREAD

**Issue by Adusun** [MaaAssistantArknights/MaaAssistantArknights#9924]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在更新之后，蓝图刷钱的策略似乎改变了，会出现战斗就直接进去而不刷新的问题，导致效率下降很多（似乎两条路都是战斗就直接进战斗）。
在商店前退出的问题还存在，如果思绪数量能够在商店进行加固，加固之后会停一段时间直接退出而不是进商店存钱（概率出现）

### Version

UI Version: v5.5.0-beta.1.d241.gbc3ad67a0
Core Version: v5.5.0-beta.1.d241.gbc3ad67a0

### 日志文件

[gui.log](https://github.com/user-attachments/files/16389905/gui.log)
[asst.log](https://github.com/user-attachments/files/16389906/asst.log)

### 截图

![微信截图_20240726174227](https://github.com/user-attachments/assets/4d2f7062-17f1-45f2-ba69-ea43732c1581)

### 还有别的吗？

mumu模拟器12
开了增强

**Comment by zzyyyl** [comment]
问个问题，印象加深之后卡住的时候你有没有注意过他卡在什么地方（游戏内什么界面，可以的话给个截图）

**Comment by Adusun** [comment]
> 问个问题，印象加深之后卡住的时候你有没有注意过他卡在什么地方（游戏内什么界面，可以的话给个截图）
![微信截图_20240727092306](https://github.com/user-attachments/assets/7ab529e4-4c0a-43c0-9024-a257a633d0cc)

**Comment by Adusun** [comment]
可能是点击过快没点到
