### ISSUE TITLE
先行一步之后干员返回时卡住

### ISSUE THREAD

**Issue by jiaxi9427** [MaaAssistantArknights/MaaAssistantArknights#9933]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

图中我的白雪没有精二不知道为什么去了先行一步,难道是门吗? 然后干员回来后就卡住了,差不多1小时没有操作.

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1
Core Version: v5.5.0-beta.1

### 日志文件

[asst&gui.zip](https://github.com/user-attachments/files/16397196/asst.gui.zip)

### 截图

![cc4e34b0f7dab05f13a61260f22e8c6](https://github.com/user-attachments/assets/ca83f507-bd21-4551-a82f-352c3ded4d78)

**Comment by Saratoga-Official** [comment]
Duplicate of #9760
