### ISSUE TITLE
请问什么时候萨卡兹肉鸽能蓝图队速刷存款策略

### ISSUE THREAD

**Issue by DarthMikuH** [MaaAssistantArknights/MaaAssistantArknights#9934]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

蓝图队速刷存款策略

### 有什么好的想法？

蓝图队速刷存款策略

### 其他内容

蓝图队速刷存款策略

**Comment by Saratoga-Official** [comment]
这issue可以直接关了
