### ISSUE TITLE
萨卡兹肉鸽去伪存真印象重建后卡死并任务完成

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9936]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

两个maa都出这个问题了

### Version

v5.5.0-beta.1.d247.g43cecbbed

### 日志文件

![屏幕截图 2024-07-27 112118](https://github.com/user-attachments/assets/943d4a5f-5e94-4898-b58a-519baf27793e)
[asst.bak - 副本.log](https://github.com/user-attachments/files/16397975/asst.bak.-.log)

![屏幕截图 2024-07-27 112341](https://github.com/user-attachments/assets/babb9010-8a4b-4977-b2bc-3d56bee8fb59)
[asst - 副本.log](https://github.com/user-attachments/files/16398000/asst.-.log)

### 截图

![MuMu12-20240727-112030](https://github.com/user-attachments/assets/465a2348-186c-42e1-8246-6e2dae2a3854)
[MuMu12-20240727-112030.zip](https://github.com/user-attachments/files/16397967/MuMu12-20240727-112030.zip)

**Comment by DCxDESIGN** [comment]
遇到了一样的问题，留个日志在这里参考

![SShot-20240727-133022-MuMuPlayer](https://github.com/user-attachments/assets/ac29d2be-3328-4535-82ce-bb2745576356)
[asst.log](https://github.com/user-attachments/files/16398594/asst.log)
[gui.log](https://github.com/user-attachments/files/16398596/gui.log)

**Comment by zzyyyl** [comment]
此问题已于公测版 v5.5.0-beta.2 修复。
