### ISSUE TITLE
[老问题又来了]卡关未能正确撤退

### ISSUE THREAD

**Issue by YipKei** [MaaAssistantArknights/MaaAssistantArknights#994]
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8988261/asst.zip)

我觉得可能是撤退逻辑出了问题
山是撤了，但是医疗没撤，结果一个奶奶着自己硬是奶了六个半小时。

**Comment by MistEO** [comment]
![示意图](https://gchat.qpic.cn/gchatpic_new/0/0-0-55F3F96FB038DF48BC76C9E776C6545F/0?term=3&file=55f3f96fb038df48bc76c9e776c6545f221709-562-291.png&vscodeDragFlag=1)

**Comment by YipKei** [comment]
![image](https://user-images.githubusercontent.com/53115298/175851769-106a0b76-7ba4-4a3c-82ee-8daf7dc1652c.png)

绿框是个肉鸽三星奶
上边还有一个还是两个我忘了，其中一个是肉鸽的三星术师
所有人朝向往右

一个小兵卡在这个奶的身后
山在部署区发呆很久了。
