### ISSUE TITLE
萨卡兹肉鸽把去伪存真节点的事件写进gui的log中

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9944]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

看log被误导到不期而遇，看了半天才发现正常通过不期而遇，且正常通过了去伪存真

**Comment by status102** [comment]
不要只看gui啊.jpg
这不还有asst.log呢

**Comment by Daydreamer114** [comment]
就是说按照gui的最后一个不期而遇事件去找时间了，然后asst里看了几百行发现不期而遇顺利通过了然后去伪存真也顺利通过了甚至进入下一层了

**Comment by DavidWang19** [comment]
implemented by 69de3b9
