### ISSUE TITLE
将“启动模拟器”增加到任务流中

### ISSUE THREAD

**Issue by Ptilopsis01** [MaaAssistantArknights/MaaAssistantArknights#9947]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

如题，目前maa挂在后台设置定时可以自动执行绝大多数任务，但前提是需要一直开着模拟器，而模拟器一直挂在后台对资源占用较多，希望可以在任务流中加入启动模拟器项目，这样只需要在执行任务时启动模拟器，不需要让模拟器一直挂在后台占用资源了

### 有什么好的想法？

如上所述

### 其他内容

或许可以给启动模拟器加一个启动后自动最小化的选项？不然每次启动都弹出来似乎也不太好（）

**Comment by ABA2396** [comment]
> 目前maa挂在后台设置定时可以自动执行绝大多数任务，但前提是需要一直开着模拟器

![image](https://github.com/user-attachments/assets/6134cdd3-ee05-405d-8112-20410d74dd24)

> 而模拟器一直挂在后台对资源占用较多

开着游戏的占用
![image](https://github.com/user-attachments/assets/52524027-b13f-43ed-8828-42bd81fdca3b)
回到模拟器桌面后的占用
![image](https://github.com/user-attachments/assets/a8c6e2dc-110d-4c97-9086-440391089314)

> 或许可以给启动模拟器加一个启动后自动最小化的选项？

有但不是所以模拟器都能用，mumu在加载和完成启动后会弹出两次，第一次最小化后还是会重新弹出，这个得向mumu那边反馈
![image](https://github.com/user-attachments/assets/30d96b86-5023-4ba8-b414-080ba6144402)

**Comment by Ptilopsis01** [comment]
> > 而模拟器一直挂在后台对资源占用较多
> 
> 开着游戏的占用 ![image](https://private-user-images.githubusercontent.com/99072975/352806323-52524027-b13f-43ed-8828-42bd81fdca3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjQxMzQsIm5iZiI6MTcyMjE2MzgzNCwicGF0aCI6Ii85OTA3Mjk3NS8zNTI4MDYzMjMtNTI1MjQwMjctYjEzZi00M2VkLTg4MjgtNDJiZDgxZmRjYTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDEwNTAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MjI2NWVhNDdkMGVlZWU1YjA0ZTBiOGZmYjg0MTU0ZmZmMTc0OTlhNDIzMjYzYTU1ZWQ3MTEyYjFhOGFjNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tf-oBPUwBcCtMW8KrGwfIKmH_beP5rCHXnu8fnQOlFo) 回到模拟器桌面后的占用 ![image](https://private-user-images.githubusercontent.com/99072975/352806410-a8c6e2dc-110d-4c97-9086-440391089314.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjQxMzQsIm5iZiI6MTcyMjE2MzgzNCwicGF0aCI6Ii85OTA3Mjk3NS8zNTI4MDY0MTAtYThjNmUyZGMtMTEwZC00Yzk3LTkwODYtNDQwMzkxMDg5MzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDEwNTAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwOTM2YmRiZDFlYzYyZWE3MjhmYTdkYWMzNTA4YzgzZmM4MWU2ZjU3OWI4MjVhNmQyZWYxZjIyMzQ1ZTVkODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DHpWv20ONNifRkfkKC_8rrLq8ADYUGa_v8hYtck3J_8)

这个占用就是前台窗口的占用，模拟器核心的实际占用是在后台的，主要是内存吃太多

> > 目前maa挂在后台设置定时可以自动执行绝大多数任务，但前提是需要一直开着模拟器
> 
> ![image](https://private-user-images.githubusercontent.com/99072975/352806247-6134cdd3-ee05-405d-8112-20410d74dd24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjQxMzQsIm5iZiI6MTcyMjE2MzgzNCwicGF0aCI6Ii85OTA3Mjk3NS8zNTI4MDYyNDctNjEzNGNkZDMtZWUwNS00MDVkLTgxMTItMjA0MTBkNzRkZDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDEwNTAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZjQyOTZiYTMyY2FjMmRhYTc3ODc3ZmY1ODU1M2UxNTI1MDI3ZDVhOGZjNTBhNjI0OTEwMGI0YjBmMGZkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RL1sIJobR3GjmA98WFh6zXppT78JMw1fC_3SrLhnnWA)

这个我试一下，没反应过来可以这么用

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/91d60ec3-1105-4c0f-ab94-0643dc6bd44f)
mumu回到桌面后基本就没啥占用了
