### ISSUE TITLE
mac版maa自动肉鸽-萨卡兹使用优先层数策略时仍会在第三层自动放弃探索

### ISSUE THREAD

**Issue by kautumnkong** [MaaAssistantArknights/MaaAssistantArknights#9950]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

mac版maa自动肉鸽-萨卡兹使用优先层数策略时仍会在第三层自动放弃探索

### Version

5.5.0-beta.2

### 日志文件

无

### 截图

<img width="841" alt="截屏2024-07-28 21 24 01" src="https://github.com/user-attachments/assets/64d6e824-b503-4dc1-a344-53eb6e661ed0">
<img width="845" alt="截屏2024-07-28 21 24 16" src="https://github.com/user-attachments/assets/6831f74f-2b26-4b22-87ab-39cc974bb398">

**Comment by ABA2396** [comment]
没日志看不了
cc @hguandl

**Comment by Constrat** [comment]
No log no help, reopen when logs :)
