### ISSUE TITLE
“借助战打 OF-1 赚信用”功能失效

### ISSUE THREAD

**Issue by BiologyHazard** [MaaAssistantArknights/MaaAssistantArknights#9956]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/user-attachments/assets/1069eb46-611e-4b8d-9a07-a6a51f236317)
MAA 勾选了 “借助战打 OF-1 赚信用”，我期望 MAA 会进入 OF-1 作战，但是实际上 MAA 点进信用交易所之后，就直接提示“完成任务: Mall”。

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.2
Core Version: v5.5.0-beta.2

### 日志文件

[asst.log](https://github.com/user-attachments/files/16404510/asst.log)

**Comment by status102** [comment]
日志不全

**Comment by BiologyHazard** [comment]
[asst.log](https://github.com/user-attachments/files/16407841/asst.log)
[gui.log](https://github.com/user-attachments/files/16407842/gui.log)

**Comment by BiologyHazard** [comment]
```
[2024-07-29 13:40:08.418][INF][Pxa874][Tx2428] asst::Assistant::append_task Mall {"credit_fight":false,"select_formation":3,"visit_friends":false,"shopping":false,"buy_first":["招聘许可"],"blacklist":["碳","家具零件","加急许可","讯使","嘉维尔","坚雷"],"force_shopping_if_credit_full":true,"only_buy_discount":false,"reserve_max_credit":false}
```
credit_fight为什么是false，我在GUI里勾了emm

**Comment by ABA2396** [comment]
你关卡选择选的啥

**Comment by BiologyHazard** [comment]
“刷理智”里面的“关卡选择”选的是“当前/上次”

**Comment by BiologyHazard** [comment]
改成选“红票-5”之后，借助战打 OF-1 赚信用可以正常进入 OF-1 了

**Comment by ABA2396** [comment]
你鼠标放刷of-1的勾选框上看看，有提示的
