### ISSUE TITLE
萨卡兹肉鸽小队点击开始肉鸽后卡在妮芙界面

### ISSUE THREAD

**Issue by Jingan2212** [MaaAssistantArknights/MaaAssistantArknights#9957]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨卡兹肉鸽小队点击开始肉鸽后卡在妮芙界面后，不进行下一步，等待后自动放弃肉鸽

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.2.d032.g3d73780c0
Core Version: v5.5.0-beta.2.d032.g3d73780c0

### 日志文件

10：16分 
[asst.log](https://github.com/user-attachments/files/16406491/asst.log)
[gui.log](https://github.com/user-attachments/files/16406492/gui.log)
[gui.log](https://github.com/user-attachments/files/16406493/gui.log)

### 截图

![PixPin_2024-07-29_10-06-21](https://github.com/user-attachments/assets/18152bd8-6f11-42ff-8ac3-9bd7586401fd)

### 还有别的吗？

MUMU12 WIN10

**Comment by Saratoga-Official** [comment]
目前没做相关的识别，月度小队得点进去选好人看到关卡才能挂

**Comment by AshdoII** [comment]
手动点两下就行，第一下点妮芙第二下点藏品，后面就能自动了。

**Comment by Saratoga-Official** [comment]
> 手动点两下就行，第一下点妮芙第二下点藏品，后面就能自动了。

选人最好自己来吧，卷是随机的，maa不知道会招谁
