### ISSUE TITLE
连接错误

### ISSUE THREAD

**Issue by UnluckyDogQAQ** [MaaAssistantArknights/MaaAssistantArknights#996]
![image](https://user-images.githubusercontent.com/98512700/175862306-6a701b00-cb6a-483e-958c-040877456086.png)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8988743/asst.log)
自动更新后就出现了无法连接的问题

**Comment by UnluckyDogQAQ** [comment]
![H9@`NO)J7QSTZ9 }70GCG)J](https://user-images.githubusercontent.com/98512700/175862420-147311b7-05ab-499f-aa05-e1c635b92155.png)

**Comment by UnluckyDogQAQ** [comment]
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8988744/asst.log)

**Comment by Shawnsdaddy** [comment]
我也有这种情况，停止重点几次试试？

**Comment by MistEO** [comment]
重启电脑 / 检查杀毒软件之类的防火墙设置 试试

**Comment by MistEO** [comment]
参考下 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1010，关掉防火墙/游戏加速器/网络代理软件等，然后重启下电脑试试
