### ISSUE TITLE
截图时间过长

### ISSUE THREAD

**Issue by Chenyinlin-Yiking** [MaaAssistantArknights/MaaAssistantArknights#9968]
### 说说你遇到的问题？

![image](https://github.com/user-attachments/assets/a867d861-ddbb-4703-a91d-ebebdf426c43)

截图用时很长，不知道是什么原因，想问一下有什么解决方案

**Comment by Constrat** [comment]
Could be anything: low spec hardware, bad emulator setup, bad adb config. Need much more info

**Comment by Chenyinlin-Yiking** [comment]
> Could be anything: low spec hardware, bad emulator setup, bad adb config. Need much more info Reopen when info.

这是最近出现的问题，前面一直很好，所有设置，硬件设备都没改过，唯一变动的就是基建排版表和我开了个集显加速。

**Comment by Chenyinlin-Yiking** [comment]
> GPU Acceleration might have something to do with it. Try playing with that setting. (Best way to drastically reduce the screen time even on fairly low end machines is to use Mumu enhanced mode) Documentation: https://maa.plus/docs/zh-cn/manual/connection.html#mumu-%E6%88%AA%E5%9B%BE%E5%A2%9E%E5%BC%BA%E6%A8%A1%E5%BC%8F

Thanks for your patient reply. I close the Mumu enhanced mode because last time I open it and then some wrong info appears, I will give it a try again
