### ISSUE TITLE
可以考虑加入仓库管理系统

### ISSUE THREAD

**Issue by VentusRanger** [MaaAssistantArknights/MaaAssistantArknights#997]
1 识别仓库内各项材料数值，以json文件存在本地，软件把json文件格式化输出出来，
2 根据升级、精英化、专精化、模组（可以让用户指定要练谁到什么练度），计算需要的材料、龙门币和狗粮等
3 计算需要的素材，并全自动刷取
总结：就是想着能不能在单一的材料导向性刷图之外，加上干员需求导向性刷图

前面的实现可能可以参考微信小程序《罗德岛人事中心》里面的《素材规划》part
希望Mist大大能看到！

**Comment by MistEO** [comment]
已经在做了，目前仓库识别已经完成了，下一步是干员及练度识别。

准备对接 [企鹅物流数据统计](https://penguin-stats.io/) 的刷图规划器 [ArkPlanner](https://penguin-stats.io/planner) ，并且 ~~我们和企鹅物流达成了某种不可告人的 py 交易~~ 他们也打算给我们开一些专用的接口，敬请期待吧~

**Comment by VentusRanger** [comment]
> 已经在做了，目前仓库识别已经完成了，下一步是干员及练度识别。
> 
> 准备对接 [企鹅物流数据统计](https://penguin-stats.io/) 的刷图规划器 [ArkPlanner](https://penguin-stats.io/planner) ，并且 ~我们和企鹅物流达成了某种不可告人的 py 交易~ 他们也打算给我们开一些专用的接口，敬请期待吧~

狠狠地期待了：）
