### ISSUE TITLE
增强模式任务无法进行

### ISSUE THREAD

**Issue by Chenyinlin-Yiking** [MaaAssistantArknights/MaaAssistantArknights#9970]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

![image](https://github.com/user-attachments/assets/590f1bbc-dee2-4d3f-b97a-a1deb462622c)
我不清楚这是不是bug或者错误，但是一直卡在这里。因为截图时长太久，我开启了mumu截图增强，然后就卡在这了。在设置里test 增强模式会弹出一个模拟器的图片：
![image](https://github.com/user-attachments/assets/02da6eb6-0ceb-4c74-b656-c42f9908f2d7)

想问一下是哪里弄错了。

### Version

Version: v5.5.0

### 日志文件

[asst.log](https://github.com/user-attachments/files/16415759/asst.log)
[gui.log](https://github.com/user-attachments/files/16415760/gui.log)

**Comment by Constrat** [comment]
I gave you the docs for a reason :)

[关于后台保活](https://maa.plus/docs/zh-cn/manual/connection.html#%E5%85%B3%E4%BA%8E%E5%90%8E%E5%8F%B0%E4%BF%9D%E6%B4%BB)
> 推荐关闭，此时实例屏幕始终为 0。
 开启时，MuMu 模拟器标签页的顺序应为实例屏幕的序号，如 0 为模拟器桌面，1 为明日方舟客户端。
针对后台保活的适配非常不完善，总会出现各种各样莫名其妙的问题，非常不建议使用。

**Comment by Chenyinlin-Yiking** [comment]
> I gave you the docs for a reason :)
> 
> [关于后台保活](https://maa.plus/docs/zh-cn/manual/connection.html#%E5%85%B3%E4%BA%8E%E5%90%8E%E5%8F%B0%E4%BF%9D%E6%B4%BB)
> 
> > 推荐关闭，此时实例屏幕始终为 0。
> > 开启时，MuMu 模拟器标签页的顺序应为实例屏幕的序号，如 0 为模拟器桌面，1 为明日方舟客户端。
> > 针对后台保活的适配非常不完善，总会出现各种各样莫名其妙的问题，非常不建

how to close it? I didn't find I have opened it.

**Comment by ABA2396** [comment]
在mumu的设置里
