### ISSUE TITLE
提高萨卡兹肉鸽桃金娘招募权重

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9974]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

**Comment by Daydreamer114** [comment]
添加一个offset，挡人先锋、地面阻挡什么的
萨米的桃金娘权重好低

**Comment by nagisa-eevee** [comment]
权重在MAA\resource\roguelike\Sarkaz\recruitment.json里 可以自己改

**Comment by Daydreamer114** [comment]
好多东西就是我写的）这个只是我懒得写放这了，谁爱写谁写

**Comment by Daydreamer114** [comment]
implemented with 9983
