### ISSUE TITLE
无法打开maa

### ISSUE THREAD

**Issue by 12354233** [MaaAssistantArknights/MaaAssistantArknights#9975]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
文件“D:\app\maa方舟辅助\MAA-v4.28.2-win-x64\MAA_win7.exe”正由另一进程使用，因此该进程无法访问此文件。
解决方案
出现未知错误
详细信息
System.IO.IOException: 文件“D:\app\maa方舟辅助\MAA-v4.28.2-win-x64\MAA_win7.exe”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   在 MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndUpdateNow()
   在 MaaWpfGui.ViewModels.UI.RootViewModel.OnViewLoaded()
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

MAAComponent-OTA-v5.5.0-beta.2_v5.5.0-win-x64

### 日志文件

[asst.log](https://github.com/user-attachments/files/16422293/asst.log)
[gui.log](https://github.com/user-attachments/files/16422295/gui.log)

**Comment by Daydreamer114** [comment]
电脑重启了吗

**Comment by 12354233** [comment]
> 电脑重启了吗

重启过了，还是一样的错误

**Comment by Saratoga-Official** [comment]
怎么还win7呢，直接删了maa重装吧

**Comment by Daydreamer114** [comment]
你如果实际使用的不是win7的话，可以试试把MAA_win7.exe删了

**Comment by Saratoga-Official** [comment]
> 你如果实际使用的不是win7的话，可以试试把MAA_win7.exe删了

不如直接删了重装

**Comment by 12354233** [comment]
之前就一直用的这个版本没问题，今天突然蹦了个错误，我看见有反馈就过来发一下，已经重装了

**Comment by Saratoga-Official** [comment]
> 之前就一直用的这个版本没问题，今天突然蹦了个错误，我看见有反馈就过来发一下，已经重装了

现在好了吗

**Comment by 12354233** [comment]
> > 之前就一直用的这个版本没问题，今天突然蹦了个错误，我看见有反馈就过来发一下，已经重装了
> 
> 现在好了吗

已经可以了
