### ISSUE TITLE
蓝叠模拟器用maa一段时间之后会无征兆闪退

### ISSUE THREAD

**Issue by andykeppel** [MaaAssistantArknights/MaaAssistantArknights#9976]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

蓝叠模拟器用maa一段时间之后会无征兆闪退，尝试重装蓝叠与maa后依旧出现此问题。

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0
Core Version: v5.5.0

### 日志文件

[asst.bak.log](https://github.com/user-attachments/files/16424458/asst.bak.log)
[gui.log](https://github.com/user-attachments/files/16424460/gui.log)

### 截图

![微信截图_20240730161658](https://github.com/user-attachments/assets/9d1d1e7d-db35-4858-8e5b-9b97d217a316)

**Comment by andykeppel** [comment]
> 哪个闪退就是哪个的问题(
> 
> 
> 
> 换个模拟器试试

可惜支持hyper-v的模拟器只有蓝叠。另外一个发现是如果我选择完成后“无动作”就不会闪退，如果选“退出模拟器，关闭MAA”就会闪退。

**Comment by Rbqwow** [comment]
> 可惜支持hyper-v的模拟器只有蓝叠。

啊 好多都支持了啊 文档里支持的都写了
顺带一提 MuMu12 刚发布的4.0还特意给hyperv做优化了 群友测试比以前好用多了

> 另外一个发现是如果我选择完成后“无动作”就不会闪退，如果选“退出模拟器，关闭MAA”就会闪退。

闪退应该是偶现的 和这个应该没啥关系 看看事件查看器里还能不能翻到崩溃事件

**Comment by SherkeyXD** [comment]
我的蓝叠也出现过这种问题 应该不是偶然事件

**Comment by slowpoke0520** [comment]
我也出现了这种情况，无征兆闪退。挂alas的模拟器也闪退，不知道什么原因，补个配置图
![build](https://github.com/user-attachments/assets/31e4b653-9a15-4413-b6d2-b9e68061d0e5)

**Comment by Rbqwow** [comment]
但是真的是谁闪退就是谁的问题 找找事件管理器里面的事件

**Comment by bronzitro** [comment]
曾经有段时间蓝叠偶尔卡死，后来MAA和游戏更新几个版本后就好了，原因不明
