### ISSUE TITLE
国际服客户端使用win版MAA借助战打OF-1的功能突然失效

### ISSUE THREAD

**Issue by XuTingyi** [MaaAssistantArknights/MaaAssistantArknights#9979]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

此前一直工作正常，近几个版本忽然失效，而且更新了版本也没有恢复，执行任务会自动跳过这一项。尝试过重新安装MAA也无效。

### Version

Resource Version: Where Vernal Winds Will Never Blow - Rerun
UI Version: v5.5.0
Core Version: v5.5.0

### 日志文件

[asst.log](https://github.com/user-attachments/files/16427320/asst.log)
[gui.log](https://github.com/user-attachments/files/16427323/gui.log)

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/dfcf766e-abaf-4047-a878-46b921f33a40)
