### ISSUE TITLE
更新开始下载之后就没反应了

### ISSUE THREAD

**Issue by x402** [MaaAssistantArknights/MaaAssistantArknights#998]
打开程序之后右下角弹出提示正在下载新版本，然后就一直等不到下载完成。重启同样，以管理员运行也没用
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8988978/asst.log)

**Comment by zzyyyl** [comment]
这种情况一般是网络太差等情况引起的。只要GUI界面没出问题应该不是bug（

还有就是，现在还没有下载进度显示等功能，不过已经有 issue 提到这个问题了，这里就先close
