### ISSUE TITLE
使用GPU加速推理增加提示或说明

### ISSUE THREAD

**Issue by Saratoga-Official** [MaaAssistantArknights/MaaAssistantArknights#9981]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

使用GPU加速推理如果使用性能较低的显卡会导致MAAOcr识别异常
asstlog显示如下：
[2024-07-30 21:01:11.663][TRC][Px2010][Tx19e4] asst::WordOcr [] by OCR Pipeline , cost 1 ms
[2024-07-30 21:01:11.663][TRC][Px2010][Tx19e4] Proceed []
选择不使用GPU加速推理即可恢复正常
目前已有多例因此出现问题

### 有什么好的想法？

使用GPU加速推理增加提示或说明提醒用户不要使用性能较低的显卡

**Comment by Rbqwow** [comment]
这东西有说核显不能跑的 但也有能跑的

按品牌来看Intel显卡问题比另外两家多 核显独显都是 但也有不出问题的

还有说 非活动显卡不能跑 活动显卡可以跑的

这该咋写( 先让用户试试(

**Comment by Saratoga-Official** [comment]
> 这东西有说核显不能跑的 但也有能跑的
> 
> 按品牌来看Intel显卡问题比另外两家多 核显独显都是 但也有不出问题的
> 
> 还有说 非活动显卡不能跑 活动显卡可以跑的
> 
> 这该咋写( 先让用户试试(

那就写个不建议使用，或者有问题就关闭之类的

**Comment by Saratoga-Official** [comment]
主要这个问题经常出现，但是影响的部分还不一样，有人是公招主页来回切换，有人是基建不能收菜，有人是肉鸽选不了蓝图分队等等，这些问题都是因为开了gpu加速导致的，然后我在用户群解决的
github也有一例是这个原因 #9858

**Comment by Constrat** [comment]
Since the prompt open to restart, we can add a: please make sure it's a dGPU and not integrated? 
![image](https://github.com/user-attachments/assets/64d67117-07d8-4d3e-81cc-f8146aeb8055)
Here

**Comment by Rbqwow** [comment]
都写出来了为啥不用( 这东西提升还挺明显的
要不加个鼠标悬浮提示 写“请勿选择核显”
或者把系统默认GPU的选项删了 避免MAA乱用显卡

更新：
独显也有这种问题吗¿

**Comment by Constrat** [comment]
Always used dedicated and never had any issues in two different systems (they are both Nvidia), I wouldn't be surprised if AMD has issue (lol)

**Comment by SherkeyXD** [comment]
@dantmnf 来看看（

**Comment by Rbqwow** [comment]
It's mainly using a large amount of CPU power consumption to replace a small amount of GPU power consumption.
After all general computing is not as efficient as dedicated computing.
It is obvious when using copilot.

There're many issues that its high CPU power consumption affects other applications.(even crash the computer)

**Comment by dantmnf** [comment]
Time to introduce [GPU blacklist](https://chromium.googlesource.com/chromium/src/gpu/+/master/config/software_rendering_list.json) 😆

**Comment by ABA2396** [comment]
> Always used dedicated and never had any issues in two different systems (they are both Nvidia), I wouldn't be surprised if AMD has issue (lol)
> 
> Regarding the improvement, to be fair I never noticed any improvement in using acceleration or not, as it's just inference acceleration and not screencap itself, it should reduce CPU% usage (but the reduction is not even 5% on my part)

Like this)
https://t.bilibili.com/942868514035728392
Copilot's case probably reduces cpu usage by more than 30 percent

**Comment by Constrat** [comment]
Never noticed it reduced by that much.
