### ISSUE TITLE
萨米肉鸽凹一层远见密文板后无法正常结束探索

### ISSUE THREAD

**Issue by Alaika0331** [MaaAssistantArknights/MaaAssistantArknights#9985]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

萨米肉鸽凹一层远见密文板后无法正常结束探索，显示“已放弃本次探索”，但是会卡在这个界面上
![`ZFJ7 4$43L{AL@NPRVKO T](https://github.com/user-attachments/assets/fa3b4833-d19c-4170-b94c-ca7fe445b743)

### Version

Core Version: v5.5.0

### 日志文件

[asst.log](https://github.com/user-attachments/files/16430319/asst.log)
[gui.log](https://github.com/user-attachments/files/16430322/gui.log)

07-30 23:39左右出现问题

### 截图

![`ZFJ7 4$43L{AL@NPRVKO T](https://github.com/user-attachments/assets/fa3b4833-d19c-4170-b94c-ca7fe445b743)

### 还有别的吗？

mumu12
几个adb设置都试过了，都有这个问题

**Comment by Alaika0331** [comment]
有大佬能帮忙看看吗

**Comment by juzai6** [comment]
我也发现这个问题了

**Comment by Daydreamer114** [comment]
![image](https://github.com/user-attachments/assets/b73d718b-015e-43f6-9857-618d9bef8110)
roi可能有点高了

**Comment by Daydreamer114** [comment]
想躲开那个3\nTEMP，得从523开始，写431是为了啥吗
