### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by insine-inverse** [MaaAssistantArknights/MaaAssistantArknights#9988]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

从昨天早上开始自动更新就一直失败状态，不管是公测还是稳定版都是这样

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0
Core Version: v5.5.0

### 日志文件

[asst.log](https://github.com/user-attachments/files/16435033/asst.log)
[gui.log](https://github.com/user-attachments/files/16435034/gui.log)

### 截图

<img width="164" alt="1722388835673" src="https://github.com/user-attachments/assets/2cc0a8eb-9902-4bfd-be96-5e8fbcaa30a7">
<img width="188" alt="1722388930034" src="https://github.com/user-attachments/assets/e11a2084-48b2-49b8-9e09-988f8939c916">

**Comment by ChingCdesu** [comment]
目前服务器压力过大，请稍后再试
