### ISSUE TITLE
改进纯网页端pr教程（update pr-tutorial.md）

### ISSUE THREAD

**Issue by Daydreamer114** [MaaAssistantArknights/MaaAssistantArknights#9991]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

1. 现在fork的默认branch已经是`dev`了
2. 提醒用户在修改时新建branch，而不是直接使用`dev`进行修改，以免后续再次修改+提交时，出现无效的、不符合commit name规范的commits
3. 提醒用户一旦pr上交后就不要点击`Sync-fork` -> `Update branch`了，以免出现不规范的commit name

**Comment by ABA2396** [comment]
出现不规范的commit name也无所谓啊，直接squash就是了）

**Comment by status102** [comment]
> Sync-fork -> Update branch了，以免出现不规范的commit name

也不是commit name啊，merge commit不管commit name是啥都会给爆的

**Comment by Daydreamer114** [comment]
现在的教程让在dev上直接改，但是现在的流程应该是fork之后新建branch再进行改动，不直接改dev

**Comment by Rbqwow** [comment]
是玛丽好久之前写的了 那时候commit name都是随便写的(

**Comment by status102** [comment]
> 现在的教程让在dev上直接改，但是现在的流程应该是fork之后新建branch再进行改动，不直接改dev

肯定是fork了再改，上来也没dev权限，怎么在dev上改

**Comment by Daydreamer114** [comment]
> 肯定是fork了再改，上来也没dev权限，怎么在dev上改

fork完之后别在自己的repo的dev改，要新建分支

**Comment by status102** [comment]
> > 肯定是fork了再改，上来也没dev权限，怎么在dev上改
> 
> fork完之后别在自己的repo的dev改，要新建分支

建不建分支有啥区别，最后不都合进主库dev

**Comment by Rbqwow** [comment]
我看看怎么改改

其实不新建分支也好 小改动无所谓 提醒一下没合并之前别点 update branch 应该就行

**Comment by Daydreamer114** [comment]
> > > 肯定是fork了再改，上来也没dev权限，怎么在dev上改
> > 
> > 
> > fork完之后别在自己的repo的dev改，要新建分支
> 
> 建不建分支有啥区别，最后不都合进主库dev😐

![image](https://github.com/user-attachments/assets/60be009e-091e-4a88-9d64-0b887966878f)
不建分支就会像这样，下一次用dev提交的时候，如果sync fork过，会留下所有，主仓库的commit记录

**Comment by status102** [comment]
> > > > 肯定是fork了再改，上来也没dev权限，怎么在dev上改
> > > 
> > > 
> > > fork完之后别在自己的repo的dev改，要新建分支
> > 
> > 
> > 建不建分支有啥区别，最后不都合进主库dev😐
> 
> ![image](https://private-user-images.githubusercontent.com/74444214/353785291-60be009e-091e-4a88-9d64-0b887966878f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjAwNDIsIm5iZiI6MTcyMjQxOTc0MiwicGF0aCI6Ii83NDQ0NDIxNC8zNTM3ODUyOTEtNjBiZTAwOWUtMDkxZS00YTg4LTlkNjQtMGI4ODc5NjY4NzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA5NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NjNiN2NiNGVjYzVjOWQ4NWI0YjUxMjg3YWFhYTVhZmI3N2MwNjI4ZmEzNDkwMGExZWQxNGM2MGE3MWNmZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-QSDGDdYc28bYGyzrUTxA-1uns5L3k7KrXqp6blW72E) 不建分支就会像这样，下一次用dev提交的时候，如果sync fork过，会留下所有，主仓库的commit记录

那是因为有人force改掉了dev分支😕

**Comment by Daydreamer114** [comment]
> 那是因为有人force改掉了dev分支😕

我force push之前就长这样了

**Comment by Constrat** [comment]
Are you sure? Because the only way to get the main branch MAA:dev commits to YOUR:dev is to git pull (and merge / rebase / whatever) or to sync directly from github. Just because the branch have the same name doesn't mean anything. You can call YOUR:branch whatever you want and no difference will be made.
Using YOUR:dev is the simplest as it's the most up to date branch when you fork from MAA repo

**Comment by Daydreamer114** [comment]
> Are you sure? Because the only way to get the main branch MAA:dev commits to YOUR:dev is to git pull (and merge / rebase / whatever) or to sync directly from github. Just because the branch have the same name doesn't mean anything. You can call YOUR:branch whatever you want and no difference will be made. Using YOUR:dev is the simplest as it's the most up to date branch when you fork from MAA repo

I means contributors need to create YOUR:new-branch if they want to pr more than two times or they will bring all commit in MAA:dev into their pr:

> ![image](https://private-user-images.githubusercontent.com/74444214/353785291-60be009e-091e-4a88-9d64-0b887966878f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjAzODAsIm5iZiI6MTcyMjQyMDA4MCwicGF0aCI6Ii83NDQ0NDIxNC8zNTM3ODUyOTEtNjBiZTAwOWUtMDkxZS00YTg4LTlkNjQtMGI4ODc5NjY4NzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwMDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YTJlNjRkZjQ3YTI5ZDUyOTM1Y2Y2Y2JhZmVjMGUwZmQxNjk4Y2ZmZTJjZjQzNzBiYThiNzEyZjhhYjRiNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fAUoyijddDkOexcTeMZBXA1r11t9uKHs-jmmIUUu9J0) 


But I'm going to do some tests to make sure that I'm right.

**Comment by Daydreamer114** [comment]
> But I'm going to do some tests to make sure that I'm right because of some doubts from status102.

Okay I was wrong, that was truely because of the force push.

So all we need is to inform contributors don't update branch before merge and list all prefixes for commit name that bot can analyze.
那要不就写个 别在合之前点update branch，然后列一下commit name的前缀都能写啥？

**Comment by status102** [comment]
能写啥公告里有

**Comment by Daydreamer114** [comment]
Maybe I'm overthinking it, but standardizing commit names should have its purpose. Otherwise, why not just restrict PR names and stop imposing requirements on commit names?

**Comment by status102** [comment]
不论你pr叫啥，最后合并的时候都能改

**Comment by Constrat** [comment]
You pretty much read my mind, but it feels like I'm the only that's not liking the recent changes XD:
- pre-commit.ci has been a disaster
	- prettifying is kinda useless, as it just doubles the commits needed and completely destroys the git blame history
	- optimization of templates I useful at the very least
- enforcing commit names should only be done in `dev` and not in PRs, as "PR merge" is discouraged

**Comment by Daydreamer114** [comment]
This enhancement created because "Black1312" asked me to give him a screen recording to show him how to create a PR, because he can't understand the tutorial nither from github nor from pr-tutorial.md. 
Thus I would like to make some changes on tutorials, show contributors a stantard workflow that make sure their work would meet our requirements like pre-commit.ci.

a little complain: if they think it dosen't matter if the commit name in a pr is nonstandard, then the pre-commit.ci in pr shouldn't exist, otherwise the only impact of pre-commit.ci is to mislead new contributors that they wrote something incorrect, and most new contributors know nothing about how to use git. They gonna ask, then learn git, or more possibly close their pr then create a new branch then create a new pr.

**Comment by Constrat** [comment]
cc @SherkeyXD

**Comment by status102** [comment]
so shall we teach everyone how to use git or github first ? 🙄

**Comment by Daydreamer114** [comment]
> so shall we teach everyone how to use git or github first ? 🙄

I'm talking about the pre-commit-ci. If this does NOT exist, we can commit anything we want rather than dealing with the format.

**Comment by status102** [comment]
> I'm talking about the pre-commit-ci. If this does NOT exist, we can commit anything we want rather than dealing with the format. That's a restriction from MAA, not from github.

噢，我还以为你说的是pr名字

**Comment by status102** [comment]
> Maybe I'm overthinking it, but standardizing commit names should have its purpose. Otherwise, why not just restrict PR names and stop imposing requirements on commit names?

因为非squash合并时，commit是会带入dev分支的，所以commit message必须要限制

**Comment by Daydreamer114** [comment]
> 因为非squash合并时，commit是会带入dev分支的，所以commit message必须要限制 并不是强制使用squash合并

现在还有pr用非squash合并吗？感觉有必要留commit的话也只可能是自己人写的

**Comment by ABA2396** [comment]
对于新的开发者，我不希望对格式要求过于严格。如果提交不符合格式要求，可以直接进行 squash 操作，并给出改进建议，而不是打击开发者的积极性，因为格式或者 commit 名字不符合规范而拒绝掉。

更新 dev 也没什么问题，只是推荐用 rebase 而不是直接 merge dev，不过都是纯网页端的 PR 教程了，肯定是假定用户是对 Git 流程不太熟悉。新建分支确实没什么必要，除非要有两次不同的 pr，而前一个还没有合并

**Comment by ABA2396** [comment]
有的，大提交都是 merge 的，多个零碎且相似的 commits 才会用 squash

**Comment by status102** [comment]
> > 因为非squash合并时，commit是会带入dev分支的，所以commit message必须要限制 并不是强制使用squash合并
> 
> 现在还有pr用非squash合并吗？感觉有必要留commit的话也只可能是自己人写的

大多都merge，除非里面pr太砸乱

**Comment by SherkeyXD** [comment]
The introduction of pre-commit.ci was meant to keep consistency of file format in our repo at least cost —— developers don't need to care about formats any more, just hand it to ci.
It does introduce some confusion to green hands, but we can simply bypass these rules for first-time developers

**Comment by Daydreamer114** [comment]
> As for the commit message limit, from my personal perspective, I'd like to treat it as a tutorial —— you can't just write random things about your contribution, a clear commit message is good for either our code review or later issue tracking. 

我也只是对pr的提出质疑。既然要留ci，我如果想好了怎么改文档，到时候再说。
