### ISSUE TITLE
maa日服不会放泵站。。。文件夹也没有扫描泵站...

### ISSUE THREAD

**Issue by qtweftq** [MaaAssistantArknights/MaaAssistantArknights#9997]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

maa日服不会放泵站。。。文件夹也没有扫描泵站...

### Version

Resource Version: 登臨意・復刻
UI Version: v5.4.1-alpha.1.d042.g1b8911f55
Core Version: v5.5.0

### 日志文件

.

### 截图

![20240731162825](https://github.com/user-attachments/assets/05db5792-0905-483d-94c2-dfb092f1e398)
![20240731162850](https://github.com/user-attachments/assets/79eccdb3-7de6-461a-a66f-8f3174f9a374)

### 还有别的吗？

.

**Comment by Saratoga-Official** [comment]
资源版本不对，泵站是怀黍离的吧，你这还是登临意
